### ISSUE TITLE
feature request: allow authorization based on ip address using built-in database

### ISSUE THREAD

**Issue by victorclaessen** [emqx/emqx#10004]
#### Environment

- OS: 
- Erlang/OTP: 
- EMQ: 5

#### Description

The built-in database authorizer is great because it does not have external dependencies (e.g. database server) and is replicated between the nodes (unlike an acl file), and is very easy to edit using the dashboard.
Currently, the built-in database only allows authorization based on username or clientid. It would be very useful to us if this authorizer would also allow selection based on client ip address.

**Comment by memoliyasti** [comment]
Hi all, 
is there any update on adding ipaddr to the built-in-database?

**Comment by zmstone** [comment]
Hi @memoliyasti 
This is not something we will consider as a standard feature.
We can assist you developing a plugin to meet your requirements if you are interested.
closing this issue.
