### ISSUE TITLE
Failed to execute emqx_web_hook,on_client_connect

### ISSUE THREAD

**Issue by duanjianhua** [emqx/emqx#10017]
### What happened?

I am running version 4.3.22 on a K8S cluster and curious as to why emqx is getting this error. 
This problem happens very frequently.
To be honest, I didn't understand the problem or EMQX, 
and I didn't find a response error in the apps source code for the master branch.

### What did you expect to happen?

If you have the same problem or can help, thank you very much！

### Anything else we need to know?

k8s evn:
            - name: EMQX_NAME
              value: "emqx"
            - name: EMQX_CLUSTER__DISCOVERY
              value: "k8s"
            - name: EMQX_CLUSTER__K8S__APP_NAME
              value: "emqx"
            - name: EMQX_CLUSTER__K8S__SERVICE_NAME
              value: "emqx-headless"
            - name: EMQX_CLUSTER__K8S__ADDRESS_TYPE
              value: "hostname"
            - name: EMQX_CLUSTER__K8S__APISERVER
              value: "https://kubernetes.default.svc:443"
            - name: EMQX_CLUSTER__K8S__SUFFIX
              value: "svc.cluster.local"
            - name: EMQX_CLUSTER__K8S__NAMESPACE
              value: "default"
            - name: EMQX_LISTENER__SSL__EXTERNAL__KEYFILE
              value: "/ssl-key/key.pem"
            - name: EMQX_LISTENER__SSL__EXTERNAL__CERTFILE
              value: "/ssl-key/cert.pem"
            - name: EMQX_LISTENER__SSL__EXTERNAL__CACERTFILE
              value: "/ssl-key/cacert.pem"
            - name: EMQX_LISTENER__SSL__EXTERNAL__HANDSHAKE_TIMEOUT
              value: "15s"
            - name: EMQX_LISTENER__SSL__EXTERNAL__VERIFY
              value: verify_none
            - name: EMQX_LISTENER__SSL__EXTERNAL__FAIL_IF_NO_PEER_CERT
              value: "false"
            - name: EMQX_LISTENER__SSL__EXTERNAL__PROXY_PROTOCOL
              value: "on"
            - name: EMQX_LISTENER__TCP__EXTERNAL__PROXY_PROTOCOL_TIMEOUT
              value: "15s"
            - name: EMQX_LOADED_PLUGINS
              value: "emqx_recon,emqx_retainer,emqx_management,emqx_dashboard,emqx_web_hook,emqx_auth_http"
            - name: EMQX_ALLOW_ANONYMOUS
              value: "true"
            - name: EMQX_AUTH__HTTP__REQUEST__RETRY_TIMES
              value: "3"
            - name: EMQX_AUTH__HTTP__REQUEST__RETRY_INTERVAL
              value: "3s"
            - name: EMQX_AUTH__HTTP__REQUEST__RETRY_BACKOFF
              value: "2.0"
            - name: EMQX_AUTH__HTTP__AUTH_REQ__URL
              value: "http://ip:8080/auth/user"
            - name: EMQX_AUTH__HTTP__AUTH_REQ__METHOD
              value: "post"
            - name: EMQX_AUTH__HTTP__AUTH_REQ__HEADERS__CONTENT_TYPE
              value: "application/json"
            - name: EMQX_AUTH__HTTP__AUTH_REQ__PARAMS
              value: "username=%u,password=%P,clientId=%c,ipaddr=%a"
            - name: EMQX_AUTH__HTTP__SUPER_REQ__URL
              value: "http://ip:8080/auth/super"
            - name: EMQX_AUTH__HTTP__SUPER_REQ__METHOD
              value: "post"
            - name: EMQX_AUTH__HTTP__SUPER_REQ__HEADERS__CONTENT_TYPE
              value: "application/json"
            - name: EMQX_AUTH__HTTP__SUPER_REQ__PARAMS
              value: "username=%u,clientId=%c,ipaddr=%a"
            - name: EMQX_AUTH__HTTP__ACL_REQ__URL
              value: "http://ip:8080/auth/acl"
            - name: EMQX_AUTH__HTTP__ACL_REQ__METHOD
              value: "post"
            - name: EMQX_AUTH__HTTP__ACL_REQ__HEADERS__CONTENT_TYPE
              value: "application/json"
            - name: EMQX_AUTH__HTTP__ACL_REQ__PARAMS
              value: "username=%u,topic=%t,clientId=%c,access=%A,ipaddr=%a"
            - name: EMQX_WEB__HOOK__URL
              value: "http://ip:8080/webhook"
            - name: EMQX_WEB__HOOK__HEADERS__CONTENT_TYPE
              value: "application/json"
            - name: EMQX_WEB__HOOK__HEADERS__ACCEPT
              value: "*/*"
            - name: EMQX_WEB__HOOK__RULE__CLIENT__CONNECT__1
              value: '{"action": "on_client_connect"}'
            - name: EMQX_WEB__HOOK__RULE__CLIENT__CONNACK__1
              value: '{"action": "on_client_connect"}'
            - name: EMQX_WEB__HOOK__RULE__CLIENT__CONNECTED__1
              value: '{"action": "on_client_connected"}'
            - name: EMQX_WEB__HOOK__RULE__CLIENT__DISCONNECTED__1
              value: '{"action": "on_client_disconnected"}'
            - name: EMQX_WEB__HOOK__RULE__CLIENT__SUBSCRIBE__1
              value: '{"action": "on_client_subscribe"}'
            - name: EMQX_WEB__HOOK__RULE__CLIENT__UNSUBSCRIBE__1
              value: '{"action": "on_client_unsubscribe"}'
            - name: EMQX_WEB__HOOK__RULE__SESSION__SUBSCRIBE__1
              value: '{"action": "on_session_subscribed"}'
            - name: EMQX_WEB__HOOK__RULE__SESSION__UNSUBSCRIBE__1
              value: '{"action": "on_session_unsubscribed"}'
            - name: EMQX_WEB__HOOK__RULE__SESSION__TERMINATED__1
              value: '{"action": "on_session_terminated"}'
            - name: EMQX_WEB__HOOK__RULE__MESSAGE__PUBLISH__1
              value: '{"action": "on_message_publish"}'
            - name: EMQX_WEB__HOOK__RULE__MESSAGE__DELIVERED__1
              value: '{"action": "on_message_delivered"}'
            - name: EMQX_WEB__HOOK__RULE__MESSAGE__ACKED__1
              value: '{"action": "on_message_acked"}'
          volumeMounts:
            - name: ssl-key
              mountPath: /ssl-key
      volumes:
        - name: ssl-key
          configMap:
            name: emqx-config

### EMQX version

<details>
4.3.22
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Log files

<details>
[Hooks] Failed to execute
{emqx_web_hook,on_client_connect,[{undefined}]}:
{error,undef,[	
		{emqx_web_hook,on_client_connect,
			[#{clean_start => true,
				clientid => <<"clientid">>,
				conn_mod => emqx_connection,
				conn_props => #{},
				connected_at => 1676972751904,
				expiry_interval => 0,
				keepalive => 400,
				peercert => [],
				peername => {{peername},46898},
				proto_name => <<"MQTT">>,
				proto_ver => 4,
				receive_maximum => 32,
				sockname => {{sockname},8883},
				socktype => proxy,
				username => <<"username">>},
				success,
				#{}{undefined}],
				[]},
		{emqx_hooks,safe_execute,2,[{file,"emqx_hooks.erl"},{line,214}]},
		{emqx_hooks,do_run_fold,3,[{file,"emqx_hooks.erl"},{line,193}]},
		{emqx_channel,handle_out,3,[{file,"emqx_channel.erl"},{line,1775}]},
		{emqx_connection,with_channel,3,[{file,"emqx_connection.erl"},{line,656}]},
		{emqx_connection,process_msg,2,[{file,"emqx_connection.erl"},{line,356}]},
		{emqx_connection,process_msg,2,[{file,"emqx_connection.erl"},{line,362}]},
		{emqx_connection,handle_recv,3,[{file,"emqx_connection.erl"},{line,320}]},
		{proc_lib,wake_up,3,[{file,"proc_lib.erl"},{line,236}]}
	]
}
</details>

**Comment by ieQu1** [comment]
Hello,

The following config parameter looks wrong:

` name: EMQX_WEB__HOOK__RULE__CLIENT__CONNACK__1
value: '{"action": "on_client_connect"}'`

You probably meant `{"action": "on_client_connack"}` ?

**Comment by ieQu1** [comment]
P.S. I've just reproduced this error and can confirm that it is indeed caused by this typo:

```
EMQX_WEB__HOOK__RULE__CLIENT__CONNACK__1='{"action": "on_client_connect"}' make quickrun
./_build/emqx/rel/emqx/bin/emqx console
Erlang/OTP 24 [erts-12.3.2.2] [emqx-c4c364bf23] [64-bit] [smp:16:16] [ds:16:16:8] [async-threads:4] [jit]

Starting emqx on node emqx@127.0.0.1
Start mqtt:tcp:internal listener on 127.0.0.1:11883 successfully.
Start mqtt:tcp:external listener on 0.0.0.0:1883 successfully.
Start mqtt:ws:external listener on 0.0.0.0:8083 successfully.
Start mqtt:ssl:external listener on 0.0.0.0:8883 successfully.
Start mqtt:wss:external listener on 0.0.0.0:8084 successfully.
Start http:management listener on 8081 successfully.
2023-02-22T21:30:56.642771+01:00 [warning] [Dashboard] Using default password for dashboard 'admin' user. Please use './bin/emqx_ctl admins' command to change it. NOTE: the default password in config file is only used to initialise the database record, changing the config file after database is initialised has no effect.
Start http:dashboard listener on 18083 successfully.
EMQ X Broker 4.3.22 is running now!
Eshell V12.3.2.2  (abort with ^G)
(emqx@127.0.0.1)1> 2023-02-22T21:31:07.437835+01:00 [error] 127.0.0.1:49634 [WebHook] HTTP request error: {shutdown,econnrefused}
2023-02-22T21:31:07.438513+01:00 [error] MzA5MzY5OTUxNDcxOTY3MjY2NjY1ODM1MzU4NzM3NTMwODI@127.0.0.1:49634 [Hooks] Failed to execute {emqx_web_hook,on_client_connect,[{undefined}]}: {error,undef,[{emqx_web_hook,on_client_connect,[#{clean_start => true,clientid => <<>>,conn_mod => emqx_connection,conn_props => #{},connected_at => 1677097867438,expiry_interval => 0,keepalive => 60,peercert => nossl,peername => {{127,0,0,1},49634},proto_name => <<"MQTT">>,proto_ver => 4,receive_maximum => 32,sockname => {{127,0,0,1},1883},socktype => tcp,username => undefined},success,#{'Assigned-Client-Identifier' => <<"MzA5MzY5OTUxNDcxOTY3MjY2NjY1ODM1MzU4NzM3NTMwODI">>},{undefined}],[]
```

**Comment by duanjianhua** [comment]
Configuration is indeed causing such problems, thank you very much for your help!@ieQu1
