### ISSUE TITLE
What should be known besides the upgrade from 4 - 5 change log

### ISSUE THREAD

**Issue by xtianus79** [emqx/emqx#10080]
### What would you like to be added or enhanced?

When upgrading to 2.1.1 and thus 5.0.14 how smooth would the transition be. The updates may have breaking changes and this might not be apparent from how one might expect. In short I don't want to just change the config and install. 

Can you post or update the documentation to talk about what should be watched for in that type of transition? 

### Why is this needed?

So that one can prepare for upgrading to 5.0 from the Kubernetes Emqx operator.

**Comment by Rory-Z** [comment]
> hi @Rory-Z , sorry I should have specified that I am coming from version 4 to 5 enterprise as well. Just wondering what I might expect. Is it going to be a major update on things like certificates and configuration or can I just update to the higher versions and everything should be good from there.

@zmstone @id @terry-xiaoyu Any ideas ?

**Comment by HJianBo** [comment]
Hi, @xtianus79 We plan to publish more detailed documentation to guide users on HOW to upgrade their EMQX cluster from v4.x to 5.x. 

For some features of EMQX 5.0 that are worth updating you can refer to [New features in EMQX 5.0](https://www.emqx.io/docs/en/v5.0/getting-started/new-features.html#user-friendly-emqx-dashboard-with-better-observability)
