### ISSUE TITLE
How to set Erlang kernel parameter inet_dist_use_interface

### ISSUE THREAD

**Issue by michaelcplusplus** [emqx/emqx#10151]
### What happened?

I want to set the erlang kernel parameter
-kernel inet_dist_use_interface 127.0.0.1

Is this possible in version 4.2.12 on windows?

### What did you expect to happen?

If I set in in vm.args 

`-kernel inet_dist_use_interface 127.0.0.1`

it is not taken over to the runtime config file e.g. vm.2023.03.16.10.50.18.args

### EMQX version

<details>

EMQ X version (e.g. emqx_ctl status): 4.2.12

### OS version

<details>

# On Windows:
BuildNumber  Caption                                 OSArchitecture  Version
17763        Microsoft Windows Server 2019 Standard  64-bit          10.0.17763
</details>

**Comment by lafirest** [comment]
@michaelcplusplus 
Most of the time I think there are no reasons to set this one. If you have multi interfaces, you only need to specify the interface you want in the listener's configuration

**Comment by michaelcplusplus** [comment]
I want to avoid emqx/erlang binding the  port (dist_listen_min = 6369) on public interface. For this I want to set inet_dist_use_interface 127.0.0.1

There are probably other ways to achieve this goal.
I would be grateful for any help.

**Comment by michaelcplusplus** [comment]
Thanks for the tip.

`set "ERL_ZFLAGS=-kernel inet_dist_use_interface {127,0,0,1}"`

This setting works for me.
