### ISSUE TITLE
Releasepackages for RHEL9

### ISSUE THREAD

**Issue by Bobobo-bo-Bo-bobo** [emqx/emqx#10159]
### What would you like to be added or enhanced?

Could you provide RPM packages for RHEL9 in addition to RHEL7 and RHEL8 packages?

### Why is this needed?

With the release of RHEL 9.1, it is considered stable for production.

I would like to migrate my existing instances (including the EMQX instance) to RHEL9 (x86_64).

Due to the more modern code base of RHEL9, other will think about updating too.

**Comment by id** [comment]
@Bobobo-bo-Bo-bobo it's already implemented, will be available starting from v5.0.21 https://github.com/emqx/emqx/blob/master/.github/workflows/build_packages.yaml#L216

**Comment by Bobobo-bo-Bo-bobo** [comment]
Hurray! ;)
