### ISSUE TITLE
Mongodb ${var} for `payload` creates a failure in the build template

### ISSUE THREAD

**Issue by xtianus79** [emqx/emqx#10168]
### What happened?

I couldn't figure it out but when I was trying to use my own template it kept failing. I found that `payload` was causing the issue. I am not sure if more "object" types are causing an issue as well. If you go with the default everything comes back as expected. 

```json
{
   "username": "${username}",
   "emqx_id": "${id}",
   "event": "${event}",
   "from": "${clientid}",
   "qos": "${qos}",
   "topic": "${topic}",
   "payload": "${payload}",
   "peerhost": "${peerhost}",
   "retain": "${retain}",
   "time_stamp": "${timestamp}",
   "message": "${message}",
   "from_username": "${from_username}",
   "from_clientid": "${from_clientid}",
   "flags": "${flags}",
   "metadata": "${metadata}",
   "publish_received_at": "${publish_received_at}",
   "pub_props": "${pub_props}",
   "node": "${node}"
}
```

### What did you expect to happen?

using `payload` would work as expected. 

### How can we reproduce it (as minimally and precisely as possible)?

Use the above object. 

### EMQX version

<details>

```console
$ ./bin/emqx_ctl broker
# paste output here
```

</details>

### OS version

<details>

```console
Ubuntu Kubernetes
EMQX Enterprise 4.4.14
```

</details>

### Log files

<details>

</details>

**Comment by thalesmg** [comment]
Hi @xtianus79 .

Could you please provide more details about your error and what are you trying to achieve?

1. Is the template you provided supposed to go into a rule action?
2. If so, which Rule Resource are you using for that?
3. Are there any EMQX logs with errors?  What do you mean by the template kept failing?

**Comment by thalesmg** [comment]
@xtianus79 Assuming that you are trying to persist messages to MongoDB based on your [recently closed issue](https://github.com/emqx/emqx/issues/9227), I tried to analyze and use your template and noticed there are a couple issues with it.

The fields `metadata` and `pub_props` are objects themselves, but in the template they were wrapped in quotes.  This ends up producing an invalid json of the form:

```json
{"metadata": "{"key": "value"}"}
```

Removing the quotes from `"${pub_props}"` and `"${metadata}"` worked for me.  For example, after fixing the template, this message could be persisted in Mongo:

```json
{ "_id" : ObjectId("641855b24d3f984431000002"), "emqx_id" : "0005F754519C6F3EF44000000B4D0009", "event" : "message.publish", "flags" : "{}", "from" : "my-clientid", "from_clientid" : "undefined", "from_username" : "undefined", "message" : "undefined", "metadata" : { "rule_id" : "rule:574052" }, "node" : "emqx@127.0.0.1", "payload" : "payload", "peerhost" : "undefined", "pub_props" : { "User-Property" : { "key" : "value" }, "User-Property-Pairs" : [ { "key" : "key", "value" : "value" } ] }, "publish_received_at" : "1679316402073", "qos" : "0", "retain" : "undefined", "time_stamp" : "1679316402073", "topic" : "t/topic", "username" : "undefined" }
```

Could you try fixing your template as above and checking if that works for you?

**Comment by xtianus79** [comment]
@thalesmg interestingly you are correct. BTW I am using the rules engine. 

Here is something interesting though. 

The default reads like this (meaning, no template):

```json
{
  "_id": {
    "$oid": "xxxxxxxxx"
  },
  "clientid": "xxxxx:xxxxx",
  "event": {
    "$symbol": "message.publish"
  },
  "flags": {
    "dup": false,
    "retain": false
  },
  "headers": {
    "peerhost": "xxxxx",
    "properties": {},
    "proto_ver": 5,
    "protocol": {
      "$symbol": "mqtt"
    },
    "username": "test"
  },
  "id": "xxxxx",
  "metadata": {
    "rule_id": "rule:xxxxxx"
  },
  "node": {
    "$symbol": "xxxxxxxx"
  },
  "payload": "{\n  \"xxxxx\": \"xxxxx\"\n}",
  "peerhost": "xxxxxx",
  "pub_props": {},
  "publish_received_at": {
    "$numberLong": "xxxxxxxxx"
  },
  "qos": 1,
  "timestamp": {
    "$numberLong": "xxxxx"
  },
  "topic": "xxxx",
  "username": "xxxxxx"
}
```

The fixed version which is all of the objects not in quotes (flags, headers, metadata, and payload): ***yes this is better it's proper json. Thanks!!!

```json
{
  "_id": {
    "$oid": "xxxxxx"
  },
  "emqx_id": "xxxxxx",
  "event": "message.publish",
  "flags": {
    "dup": false,
    "retain": false
  },
  "from": "xxxxx:xxxxx",
  "from_clientid": "undefined",
  "from_username": "undefined",
  "message": "undefined",
  "metadata": {
    "rule_id": "rule:xxxxx"
  },
  "node": "xxxxx",
  "payload": {
    "uniqueIdentifier": "xxxxx"
  },
  "peerhost": "xxxxx",
  "pub_props": {},
  "publish_received_at": "xxxxx",
  "qos": "1",
  "retain": "undefined",
  "time_stamp": "xxxxx",
  "topic": "xxxx",
  "username": "test"
}
```

**Comment by xtianus79** [comment]
@thalesmg btw is that for redis too regarding objects? don't quote them? I have quoted everything up to this point. I think it just strings the json and I have been dealing with it downstream. Redis isn't in json so I think it just works better that way.
