### ISSUE TITLE
Shows a 404 error when to view the payload of retained messages in dashboard

### ISSUE THREAD

**Issue by pandboy** [emqx/emqx#10169]
### What happened?
emqx dashboard 保留消息那点击查看payload 404
错误提示：
404 API_NOT_EXIST:Request Path Not Found

### What did you expect to happen?

能看正常显示

### How can we reproduce it (as minimally and precisely as possible)?

版本5.0.20

### EMQX version

<details>

```console
$ ./bin/emqx_ctl broker
#  5.0.20
```

</details>

### Log files

<details>

</details>

**Comment by HJianBo** [comment]
Hi @pandboy, could you try to use v5.0.21? This version is works for me

**Comment by HJianBo** [comment]
Sorry, 5.0.21 is preparing released these days. Could you try 5.0.20
https://www.emqx.io/downloads

**Comment by thalesmg** [comment]
I cannot reproduce this problem in 5.0.20 (tested with docker).  Please check that your request parameters are correct, or share more details about how you are using the API and if you have performed some configuration changes.

**Comment by pandboy** [comment]
> I cannot reproduce this problem in 5.0.20 (tested with docker). Please check that your request parameters are correct, or share more details about how you are using the API and if you have performed some configuration changes.

use emqx Dashboard, menu: Retained Messages, click  Show payload button, not using the api

**Comment by thalesmg** [comment]
> > I cannot reproduce this problem in 5.0.20 (tested with docker). Please check that your request parameters are correct, or share more details about how you are using the API and if you have performed some configuration changes.
> 
> use emqx Dashboard, menu: Retained Messages, click Show payload button, not using the api

That's right.  That uses the API.  And I couldn't observe any 404 issues.  Unless there are more steps involved in reproducing the issue.

**Comment by HJianBo** [comment]
@pandboy Did you install the older version before? Maybe you can try to force flush the Web browser (or clear the page cache) and try it again
