### ISSUE TITLE
data in Built-in-Database lost when I cut off the power of my machine

### ISSUE THREAD

**Issue by engureguo** [emqx/emqx#10177]
### What happened?

First, I run emqx on my machine as a docker container, and I modified the default account password of the dashboard in /opt/emqx/etc/emqx.conf (it was admin/public).

Then, I unplugged my machine to simulate a power outage. When I re-powered the machine, I found that the default account and password of the dashboard(login page) became admin/public again, and the authentication and authorization information in the built-in database were lost.

### What did you expect to happen?

If a sudden power outage occurs, when I start emqx docker container again:
1.username and password of dashboard are as set in the emqx.conf
2.data in buil-in-dabase still exists

### EMQX version

<details>

```console
$ ./bin/emqx_ctl broker
sysdescr  : EMQX
version   : 5.0.20
datetime  : 2023-03-20T14:49:18.806837283+00:00
uptime    : 23 minutes, 14 seconds
```

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
$ uname -a
Linux 549d24445163 5.19.0-35-generic #36~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Fri Feb 17 15:17:25 UTC 2 x86_64 GNU/Linux

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Log files

<details>

</details>

**Comment by thalesmg** [comment]
Hi @engureguo .

Could you share a few more details about your setup?

Since you mentioned you are using Docker, are you mounting `/opt/emqx/etc/emqx.conf` as an external volume?  

Since `/opt/emqx/etc/emqx.conf` is a file that comes with the container's filesystem, you would need to do mount it as an external volume if you want such configuration changes to persist between Docker container restarts.

I used the following command to mount and edit that configuration file, and it works as expected (changes to `emqx.conf` are persisted):

```sh
docker \
    run -it \
    -p 38083:18083 \
    -v /tmp/i10177/emqx.conf:/opt/emqx/etc/emqx.conf:ro \
    emqx:5.0.20
```

**Comment by thalesmg** [comment]
The same applies to the built-in database: if you don't mount `/opt/emqx/data` as an external volume, restarting the container will reset all changes made to files inside that directory, such as the built-in database.

**Comment by engureguo** [comment]
@thalesmg thx!

I created emqx docker container with these cmds:
```
chown -R 1000:1000 /root/services/emqx/data

docker \
    run -it -u 1000:1000 \
    -p 18083:18083 -p 1883:1883 \
    -v /root/services/emqx/emqx.conf:/opt/emqx/etc/emqx.conf \
    -v /root/services/emqx/data:/opt/emqx/data \
    emqx
```
and after configuring the authentication and authorization information of build-in-database,
again I unplugged my machine, when I restarted it, data were there!

thx again!
