### ISSUE TITLE
The http authentication becomes invalid after emqx starts for a period of time

### ISSUE THREAD

**Issue by mijjjj** [emqx/emqx#10182]
### What happened?

I am using emqx 5.0.20 version, and the same situation will occur in other versions before. I use dokcer for deployment. After a period of deployment, the client will often fail to connect. After checking the log, it shows that the resource is disabled, and http Authentication-related issues, but I can't get more useful troubleshooting information from the log, please help to find out what is the cause, this problem occurs in many versions, so that my project cannot be used normally

### What did you expect to happen?

After a period of normal deployment, there will be no failure to log in

### EMQX version

5.0.20

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Log files

<details>

</details>

[7df2960e07db40d50f3d6df38dc2f75509179dec5aa8f072168b9e75964e7908-json.log](https://github.com/emqx/emqx/files/11024281/7df2960e07db40d50f3d6df38dc2f75509179dec5aa8f072168b9e75964e7908-json.log)

**Comment by mijjjj** [comment]
After my inspection, my http service is normal. I have checked it when and after the error occurred, but this problem will appear after emqx has been running for a period of time, and it will be restored after restarting emqx, and there is no restart http server

**Comment by mijjjj** [comment]
I use docker to run emqx, and use a bridge network with the http server, but will it be restored after restarting the emqx container? Will there be such a problem when using a bridge network?

**Comment by mijjjj** [comment]
好的，我尝试下

**Comment by kjellwinblad** [comment]
@mijjjj :
> 好的，我尝试下

Have the issue been resolved by running EMQX on a more powerful machine? Do you think we can close this issue now?
