### ISSUE TITLE
can emqx support topic fuzzy search

### ISSUE THREAD

**Issue by 985492783** [emqx/emqx#10191]
### What would you like to be added or enhanced?

can emqx support topic fuzzy search？

### Why is this needed?

we have some same prefix topic to quick queries

**Comment by thalesmg** [comment]
Hi @985492783 .

You may use the Subscriptions menu in the dashboard for that.  It supports topic wildcards, so if you want to search for a topic with, for example, the `a/b` prefix, just search for `a/b/#`.

![Peek 2023-03-21 11-24](https://user-images.githubusercontent.com/16166434/226637014-3c05fd72-f4f2-4bdf-a0c6-8920892cac5f.gif)
