### ISSUE TITLE
kubernetes helm config 

### ISSUE THREAD

**Issue by BatUnt** [emqx/emqx#10223]
### What would you like to be added or enhanced?

good day, I would just like to ask if it would be possible to add clusterIP to the settings so that the ip can be set

### Why is this needed?

for use in the node locally from a permanent IP

**Comment by thalesmg** [comment]
Hi, thanks for your suggestion.

We'll look into adding this configuration to the charts.

**Comment by BatUnt** [comment]
thank you for such a quick response, but somehow it doesn't work at all
![image](https://user-images.githubusercontent.com/63431281/227325764-fa544dbe-d77d-460f-bdc4-6a2d516654b6.png)
![image](https://user-images.githubusercontent.com/63431281/227325898-dd766f5a-f081-4ec9-aa4d-3fcf23f90f3b.png)
![image](https://user-images.githubusercontent.com/63431281/227325987-e9d98bd8-eeb9-4305-9d6f-a5f725a81f77.png)
as you can see in the images, the image cannot be downloaded and the ip does not change after adding the clusterIP command,Many thanks for any help.

**Comment by thalesmg** [comment]
5.0.21 has not been released yet. You may want to try 5.0.20.

Also, as I mentioned, we are still looking into adding support for that, so it's not supported in the official charts yet.

**Comment by BatUnt** [comment]
yes, I'm using 5.0.20 now, only clusterIP doesn't work there, because in 5.0.20 there is no such change option yet.So I understand well that I will have to wait before  new version? thank you.

**Comment by thalesmg** [comment]
>So I understand well that I will have to wait before new version?

Correct, a new version will be required.  

Unless you want to try out our main branch after the feature is merged (not sure how easy is to tell Helm to use a git branch for a quick test, though).

**Comment by BatUnt** [comment]
I don't understand what you mean, could you give me some hint?

**Comment by thalesmg** [comment]
If you are in a hurry, after the #10224 PR is merged, you may try to use the HEAD of the `master` branch to try it out.
