### ISSUE TITLE
emqx4.4.16版，static集群模式，docker-compose启动文件内node配置不起作用，只能在外面配置环境变量

### ISSUE THREAD

**Issue by O-kai** [emqx/emqx#10227]
### What happened?

emqx版本：4.4.16
两台服务器，配置static集群模式，我在各自的emqx.conf文件中配置了node信息，但是启动就报错，错误已经贴在下面。
然后我尝试了很多方法，使用docker-compose启动，在docker-compose.yaml中如果配置
    environment:
      - EMQX_NAME=emqx1
      - EMQX_HOST=192.168.0.1
这两个环境变量，那就可以启动成功，并且组成静态集群。
这个光是在 /emqx/etc/emqx.conf 文件中的node配置\<name\>@\<host\>不起作用的问题请排查一下。

### What did you expect to happen?

希望可以排查一下问题，我在使用的时候方便配置文件统一归档。

### How can we reproduce it (as minimally and precisely as possible)?

直接使用static模式，然后不要配置docker-compose.yaml的环境变量启动就报错。

### Anything else we need to know?

可以随时联系我邮箱，可以提供复现视频 jsk_developer@163.com
谢谢！

### EMQX version

<details>

sysdescr  : EMQX Broker
version   : 4.4.16
uptime    : 7 minutes, 26 seconds
datetime  : 2023-03-24 03:01:40

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"



$ uname -a
Linux ecloud-zone-pre-01 3.10.0-957.el7.x86_64 #1 SMP Thu Nov 8 23:39:32 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux



</details>


### Log files

<details>
WARNING: Default (insecure) Erlang cookie is in use.
Please set node.cookie in /opt/emqx/etc/emqx.conf or override from environment variable EMQX_NODE_COOKIE
NOTE: Use the same config value for all nodes in the cluster.
!!!!!!
{"Kernel pid terminated",application_controller,"{application_start_failure,kernel,{{shutdown,{failed_to_start_child,net_sup,{shutdown,{failed_to_start_child,net_kernel,{'EXIT',nodistribution}}}}},{kernel,start,[normal,[]]}}}"}
Kernel pid terminated (application_controller) ({application_start_failure,kernel,{{shutdown,{failed_to_start_child,net_sup,{shutdown,{failed_to_start_child,net_kernel,{'EXIT',nodistribution}}}}},{kernel,start,[normal,[]]}}})

</details>

**Comment by qzhuyan** [comment]
@O-kai, In case you want fast feedback, could you write it in English? Not all developers could not understand Chinese.
Or ask Chinese in askemq.com
