### ISSUE TITLE
Questions about message persistence

### ISSUE THREAD

**Issue by lufuyang** [emqx/emqx#1025]
#### Environment

- OS: centos 6.5
- Erlang/OTP: 19
- EMQ: 2.1.2

#### Description
Hi,
I have tested EMQ version 2.1.2 for message and subscriptions persistence feature.I found that as long as there is one node to survive,the subscriptions and message router relationship will sync to other restarted node.but when all nodes restart at same time,the  subscriptions and message router relationship will disappear.I wonder if EMQ support to persist subscriptions and message router relationship when all nodes restart?
there is another questions, I found that when one node restart,one it can persist message which pub from local node ,but can't persist message which routed from other nodes.Can EMQ support this situation now?
thanks.

**Comment by turtleDeng** [comment]
@lufuyang 
The emqx-enterprise supports message persistence to the DB to ensure that messages are not lost.
https://www.emqx.io/downloads/emq/enterprise?osType=Linux
