### ISSUE TITLE
can't configure the authorization sources via environment variables with index 1

### ISSUE THREAD

**Issue by lafirest** [emqx/emqx#10264]
### What happened?

a user who uses environment variables with index 1 to set authorization sources will get a `validation_error`, but anything is going fine after changing the `1` to `2`.

env：
EMQX_AUTHORIZATION__DENY_ACTION:
EMQX_AUTHORIZATION__SOURCES__1__TYPE:
EMQX_AUTHORIZATION__SOURCES__1__SERVER:
EMQX_AUTHORIZATION__SOURCES__1__REDIS_TYPE:
EMQX_AUTHORIZATION__SOURCES__1__PASSWORD:
EMQX_AUTHORIZATION__SOURCES__1__CMD:

error log：
2023-03-28T13:51:41.560492+00:00 [error] #{kind => validation_error,matched_type => “authz:redis_single”,path => “authorization.sources.1”,reason => unknown_fields,unknown => “path”,unmatched => “auto_reconnect,database,…”}
ERROR: call_hocon_failed: -v -t 2023.03.28.13.51.41 -s emqx_conf_schema -c /opt/emqx/etc/emqx.conf -d /opt/emqx/data/configs generate

### What did you expect to happen?

Here, index 1 should also be fine.

### How can we reproduce it (as minimally and precisely as possible)?

[emqx-1.zip](https://github.com/emqx/emqx/files/11097386/emqx-1.zip)
The k8s file that the user is using.

### EMQX version

5.0.20

### Log files

<details>
2023-03-28T13:51:41.560492+00:00 [error] #{kind => validation_error,matched_type => “authz:redis_single”,path => “authorization.sources.1”,reason => unknown_fields,unknown => “path”,unmatched => “auto_reconnect,database,…”}
ERROR: call_hocon_failed: -v -t 2023.03.28.13.51.41 -s emqx_conf_schema -c /opt/emqx/etc/emqx.conf -d /opt/emqx/data/configs generate
</details>

**Comment by zmstone** [comment]
This is because .1 is used in config file.
You can try this:
```
EMQX_AUTHORIZATION__SOURCES=[]
```
followed by 
```
EMQX_AUTHORIZATION__SOURCES__1__TYPE:
EMQX_AUTHORIZATION__SOURCES__1__SERVER:
EMQX_AUTHORIZATION__SOURCES__1__REDIS_TYPE:
EMQX_AUTHORIZATION__SOURCES__1__PASSWORD:
EMQX_AUTHORIZATION__SOURCES__1__CMD:
```

**Comment by lafirest** [comment]
> This is because .1 is used in config file. You can try this:
> 
> ```
> EMQX_AUTHORIZATION__SOURCES=[]
> ```
> 
> followed by
> 
> ```
> EMQX_AUTHORIZATION__SOURCES__1__TYPE:
> EMQX_AUTHORIZATION__SOURCES__1__SERVER:
> EMQX_AUTHORIZATION__SOURCES__1__REDIS_TYPE:
> EMQX_AUTHORIZATION__SOURCES__1__PASSWORD:
> EMQX_AUTHORIZATION__SOURCES__1__CMD:
> ```

but our document (https://www.emqx.io/docs/en/v5.0/configuration/configuration.html) tells users that they can override the value of an element in an array by using the same index

**Comment by zmstone** [comment]
but if the element is a struct, the fields will be merged.
try this:
```
EMQX_AUTHORIZATION__SOURCES__1=null
```
followed by
```
EMQX_AUTHORIZATION__SOURCES__1__TYPE:
EMQX_AUTHORIZATION__SOURCES__1__SERVER:
EMQX_AUTHORIZATION__SOURCES__1__REDIS_TYPE:
EMQX_AUTHORIZATION__SOURCES__1__PASSWORD:
EMQX_AUTHORIZATION__SOURCES__1__CMD:
```
