### ISSUE TITLE
Bind Dashboard port to local network interface

### ISSUE THREAD

**Issue by michaelcplusplus** [emqx/emqx#10266]
#### Environment

- OS: Windows 2019
- Erlang/OTP: 22
- EMQ: 4.2.12

#### Description

*A description of the issue*
Is it poosible to bind the dashboard port only to the local network interface (127.0.0.1)

I would like to achieve that the dashboard is only accessible via localhost:30105.

**Comment by lafirest** [comment]
> Is it possible to set this setting in the emqx_dashboard.conf file or anywhere else? I don't want to modify the erlang source code.

Sorry, my fault, I had supposed you are using EMQX 5. Yes, you can directly modify the `emqx dashboard.conf` to update the bind value. But I don't familiar with EMQX 4.2, this is a retired version, and I suggest you upgrade to EMQX 4.4 or EMQX 5 if you could.

**Comment by michaelcplusplus** [comment]
Thank you for the support
