### ISSUE TITLE
Can not connect to mqtts when pass a option list

### ISSUE THREAD

**Issue by emnvn** [emqx/emqx#1027]
#### Environment

- OS: CentOS 7
- Erlang/OTP: 18
- EMQ: 2.1

#### Description

I have tried to connect to mqtt server via TLS.  My client use emqttc library to connect to mqtt server . When I pass only the option ssl, it connect well. 
Ex: 

`[{client_id,<<"id1@172.31.45.166">>},ssl,{host,"localhost"},{port,8883},{keepalive,60},{logger,{lager,debug}},auto_resub,{reconnect,{5,5,17280}}]`

But when I pass ssl option list, It can not connect whether I pass a empy list or a list with cert and key file

Ex1:

`[{client_id,<<"id1@172.31.45.166">>},{ssl,[]},{host,"localhost"},{port,8883},{keepalive,60},{logger,{lager,debug}},auto_resub,{reconnect,{5,5,17280}}]
`
or

`[{client_id,<<"id1@172.31.45.166">>},{ssl,[{certfile,"priv/ssl/cert.pem"},{keyfile,"priv/ssl/key.pem"}]},{host,"localhost"},{port,8883},{keepalive,60},{logger,{lager,debug}},auto_resub,{reconnect,{5,5,17280}}]
`
or

`[{client_id,<<"id1@172.31.45.166">>},{ssl,[{certfile,"priv/ssl/client-cert.pem"},{keyfile,"priv/ssl/client-key.pem"}]},{host,"localhost"},{port,8883},{keepalive,60},{logger,{lager,debug}},auto_resub,{reconnect,{5,5,17280}}]
`

I don't know what is the problem.

Thanks for any helps.

**Comment by tigercl** [comment]
You can refer https://github.com/emqtt/emqttc#ssl-socket
