### ISSUE TITLE
Failed to start LSB: Erlang MQTT Broker

### ISSUE THREAD

**Issue by Singh2901** [emqx/emqx#10290]
### What happened?

hi I am getting above error while starting EMQX,  Can someone help me with some solution?

/usr/lib/emqx/bin/nodetool: /usr/local/lib/libz.so.1: version `ZLIB_1.2.7.1' not found (required by /usr/lib/emqx/bin/nodetool)

![image](https://user-images.githubusercontent.com/129321562/228632403-2aa367da-bd76-4a82-a3ac-ac2d75a180c2.png)

### What did you expect to happen?

to start EMQX service

### EMQX version

<details>

```console
emqx-ubuntu16.04-v3.1.1_amd64.deb
```

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Log files

<details>

</details>

**Comment by lafirest** [comment]
@Singh2901 
Version 3.1.1 has been retired for a long time, I suggest you have a try with version 4.4.x or 5.0.x.

**Comment by zmstone** [comment]
I'm closing this issue as it's not actionable from our side.
Feel free to reopen or create a new one if issue persists with EMQX v4.4 and v5.0
