### ISSUE TITLE
emqx-5.0.21-el7-amd64.rpm，calling the authentication api returns {"code":"BAD_API_KEY_OR_SECRET","message":"Check api_key/api_secret"}

### ISSUE THREAD

**Issue by zundaren** [emqx/emqx#10295]
### What happened?

dashboard {
    listeners.http {
        bind = "0.0.0.0:8080"
    }
    default_username = admin
    default_password = jaya8888
}

curl -u admin:jaya8888 -X 'POST' -H 'Content-Type: application/json' -d '{"user_id":"admin", "password":"jaya8888","is_superuser": true}' 'http://localhost:61680/api/v5/authentication/password_based%3Abuilt_in_database/users'

return => {"code":"BAD_API_KEY_OR_SECRET","message":"Check api_key/api_secret"}. 
When the password = public， works properly.

The previous version can use a password  != public (emqx-5.0.9-el7-amd64.rpm)  works properly.

### What did you expect to happen?

dashboard set  default_password = jaya8888, curl -u admin:jaya8888 works properly.

### EMQX version

emqx-5.0.21-el7-amd64.rpm

### OS version

Linux izwz9czrwqo2s4tc3t328bz 3.10.0-514.26.2.el7.x86_64 #1 SMP Tue Jul 4 15:04:05 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

### Log files

<details>

</details>

**Comment by id** [comment]
This is the expected behavior since [v5.0.15](https://github.com/emqx/emqx/releases/tag/v5.0.15).
