### ISSUE TITLE
Data bridges would write non-utf8 strings to hocon-configs

### ISSUE THREAD

**Issue by terry-xiaoyu** [emqx/emqx#10377]
### What happened?

If the user copy some strings from an Office Word doc and then past them to the emqx Dashboard, something wrong could occur:

For example, paste to the payload tempalte of webhook:

![image](https://user-images.githubusercontent.com/11696433/231422195-5d3e6ec6-0f5d-4e0b-8abb-f49f12fedbf4.png)

And the config will be written to data/config/cluster-override.conf, then all the APIs are going to fail with the following error:

![image](https://user-images.githubusercontent.com/11696433/231422473-bfd170e1-cce3-48fe-be6d-a2e635ad1ac1.png)

### What did you expect to happen?

We could do some check in the hocon schema, deny any HTTP request if it provides non-utf8 strings.

### EMQX version

<details>

Opensource emqx 5.0.21

</details>

### OS version

Windows

### The cluster-override.conf
[cluster-override.conf.zip](https://github.com/emqx/emqx/files/11210113/cluster-override.conf.zip)

**Comment by zhongwencool** [comment]
https://github.com/emqx/emqx/pull/10626
