### ISSUE TITLE
Debian: Upgrade from v5.0.22 to v5.0.23 not working

### ISSUE THREAD

**Issue by alexdelprete** [emqx/emqx#10446]
### What happened?

I'm trying to upgrade to 5.0.23 on Debian 11, but the daemon fails to restart.

### What did you expect to happen?

Successful restart of upgraded service.

### How can we reproduce it (as minimally and precisely as possible)?

install 5.0.22 on debian 11
upgrade to 5.0.23 via apt (packagecloud repo configured)
service won't restart

### EMQX version

<details>

```console
sysdescr  : EMQX
version   : 5.0.22
datetime  : 2023-04-18T22:37:49.204096144+02:00
uptime    : 10 minutes, 50 seconds
```

</details>

### OS version

<details>

```console
PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

Linux emqx 6.2.9-1-pve #1 SMP PREEMPT_DYNAMIC PVE 6.2.9-1 (2023-03-31T10:48Z) x86_64 GNU/Linux
```

</details>

### Log files

[node_dump_20230418_224043.tar.gz](https://github.com/emqx/emqx/files/11266314/node_dump_20230418_224043.tar.gz)

**Comment by id** [comment]
@alexdelprete sorry about that. We are working on fixing this issue as well as on a test suite to avoid this kind of issues in the future.

**Comment by alexdelprete** [comment]
No problem, just thought to let you know in case you missed it. Thanks.
