### ISSUE TITLE
EMQX Crash after try to join

### ISSUE THREAD

**Issue by AngeloBestetti** [emqx/emqx#10456]
### What happened?

just upgrade to latest version 5.0.23 on the emqx@node2, when I start emqx,it just crash throwing this error:

[critical] msg: failed_to_init_config, mfa: emqx_conf_app:start/2, line: 40, exception: throw, reason: #{kind => validation_error,path => "listeners.ssl.default.limiter.bytes.burst",reason => #{expected_type => "emqx_limiter_schema:capacity()"},schema_module => emqx_conf_schema,unshown_errors_count => 13,value => infinity}, stacktrace: [{hocon_tconf,assert,2,[{file,"hocon_tconf.erl"},{line,1216}]},{hocon_tconf,map,4,[{file,"hocon_tconf.erl"},{line,303}]},{hocon_tconf,map_translate,3,[{file,"hocon_tconf.erl"},{line,99}]},{emqx_config,do_check_config,3,[{file,"emqx_config.erl"},{line,457}]},{emqx_config,check_config,3,[{file,"emqx_config.erl"},{line,443}]},{emqx_config,init_load,4,[{file,"emqx_config.erl"},{line,354}]},{emqx_conf_app,init_conf,0,[{file,"emqx_conf_app.erl"},{line,110}]},{emqx_conf_app,start,2,[{file,"emqx_conf_app.erl"},{line,32}]},{application_master,start_it_old,4,[{file,"application_master.erl"},{line,293}]}]
[os_mon] memory supervisor port (memsup): Erlang has closed
[os_mon] cpu supervisor port (cpu_sup): Erlang has closed

### What did you expect to happen?

I expect to emqx@node2 rejoin to the cluster

### How can we reproduce it (as minimally and precisely as possible)?

I do have two nodes (was working)
emqx@node1 (master) version: 5.0.21-g97e7c439
emqx@node2 just upgrade to 5.0.23

Both with External IP Addresses and all required ports open (was working)

### EMQX version

<details>

```console
$ ./bin/emqx_ctl broker
# paste output here
```
sysdescr  : EMQX
version   : 5.0.23
datetime  : 2023-04-20T00:05:01.532568291-03:00
uptime    : 3 minutes, 59 seconds
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
PRETTY_NAME="Ubuntu 22.04.2 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.2 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
$ uname -a
Linux vt02 5.15.0-69-generic #76-Ubuntu SMP Fri Mar 17 17:19:29 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Log files

<details>

</details>

**Comment by savonarola** [comment]
Seems to be the same problem as https://github.com/emqx/emqx/issues/10446

**Comment by savonarola** [comment]
Closing as duplicate
