### ISSUE TITLE
EMQX 5 opens a https connection to ec2-54-193-220-148.us-west-1.compute.amazonaws.com

### ISSUE THREAD

**Issue by michaelcplusplus** [emqx/emqx#10464]
### What happened?

After starting EMQX 5 there is for a short time a https connection to ec2-54-193-220-148.us-west-1.compute.amazonaws.com.

Output of TCPView 
erl.exe	1076	TCP	mylaptop.xxxx.local	59747	ec2-54-193-220-148.us-west-1.compute.amazonaws.com	https	ESTABLISHED	3	1.499	5	4.075						

What is the reason for this connection?
Can this request be turned off?

### What did you expect to happen?

No connection to ec2-54-193-220-148.us-west-1.compute.amazonaws.com

### EMQX version

<details>

```console
$ ./bin/emqx_ctl broker
sysdescr  : EMQX
version   : 5.0.17
```

</details>

### OS version

<details>

```console
BuildNumber  Caption                   OSArchitecture  Version
19044        Microsoft Windows 10 Pro  64-bit          10.0.19044
```

</details>

**Comment by savonarola** [comment]
Hello! That looks like the default value for telemetry endpoint (telemetry.emqx.io), please look
https://www.emqx.io/docs/en/v5.0/telemetry/telemetry.html#disabling-telemetry

**Comment by michaelcplusplus** [comment]
Thank You for the information

**Comment by zmstone** [comment]
Hi Just a bit more information to add:
In order for EMQ to understand better how our product is used, EMQX Open Source edition (but NOT Enterprise edition) reports some basic deployment data to our telemetry server.
All the reported data can be found here:
https://github.com/emqx/emqx/blob/master/apps/emqx_modules/src/emqx_telemetry.erl

And as @savonarola  pointed out above, you can turn it off if you do not feel comfortable sharing.
