### ISSUE TITLE
emqx_ctl mgmt insert missing in emqx 5.x

### ISSUE THREAD

**Issue by rgaufman** [emqx/emqx#10479]
### What would you like to be added or enhanced?

I found this in the manual for 4.x and it's fantastic:

```
$ ./bin/emqx_ctl mgmt insert dbcb6e023370b world
AppSecret: MjgzMzQ5MjYyMTY3ODk4MjA5NzMwODExODMxMDM1NDk0NDA
```

How do I achieve the same in 5.x? - the manual says to add an API from the web interface, but I would like to automate this.

### Why is this needed?

For infrastructure as code, it is important to be able to install EMQX without user intervention.

**Comment by qzhuyan** [comment]
have you read about our API doc?
https://www.emqx.io/docs/en/v5.0/admin/api-docs.html

or the bootstrap file:
https://www.emqx.io/docs/en/v5/configuration/configuration-manual.html#api-keys

**Comment by rgaufman** [comment]
I tried to use the bootstrap file to generate the initial key/secret, but maybe I did it wrong, I opened a ticket about it here: https://github.com/emqx/emqx/issues/10727

**Comment by id** [comment]
@rgaufman is it ok to close this issue now?

**Comment by rgaufman** [comment]
Yes, thank you :)
