### ISSUE TITLE
High Ram and CPU Spikes causing OOM

### ISSUE THREAD

**Issue by amosyuen** [emqx/emqx#10509]
### What happened?

I'm running EMQX in HA addon https://github.com/hassio-addons/addon-emqx, it basically creates a docker image from v5.0.23 https://github.com/hassio-addons/addon-emqx/blob/main/emqx/Dockerfile and runs it. I noticed that the image failed with OOM somtimes.

When monitoring memory I see it constantly fluctuating from 220MB to 2GB. The incoming message rate doesn't seem very high, so this doesn't sound like it should be normal behavior. 
Portainer stats: 
![image](https://user-images.githubusercontent.com/422794/234218982-8202cb4b-2f46-4997-867e-c00b44fc3700.png)

EMQX Dashboard snapshot: 
![image](https://user-images.githubusercontent.com/422794/234218887-72236883-2738-46a1-972b-63064bbdf85f.png)

### What did you expect to happen?

Memory and cpu usage should not fluctuate a lot, staying more constant and lower.

### How can we reproduce it (as minimally and precisely as possible)?

Just run docker image and view portainer stats

### EMQX version

<details>

```console
$ ./bin/emqx_ctl broker

sysdescr  : EMQX
version   : 5.0.22
datetime  : 2023-04-25T01:28:52.709127637-07:00
uptime    : 54 seconds
```

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release

PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

$ uname -a

Linux a0d7b954-emqx 6.1.24 #1 SMP PREEMPT_DYNAMIC Mon Apr 17 09:05:07 UTC 2023 x86_64 GNU/Linux
```

</details>

### Log files

node_dump:
[node_dump_20230425_015112.tar.gz](https://github.com/emqx/emqx/files/11320668/node_dump_20230425_015112.tar.gz)

Portainer Logs:
<details>

```console
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service base-addon-banner: starting
-----------------------------------------------------------
 Add-on: EMQX
 The most scalable open-source MQTT broker for IoT. An alternative for the Mosquitto add-on
-----------------------------------------------------------
 Add-on version: 0.2.7
 You are running the latest version of this add-on.
 System: Home Assistant OS 10.0  (amd64 / generic-x86-64)
 Home Assistant Core: 2023.4.6
 Home Assistant Supervisor: 2023.04.1
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
s6-rc: info: service base-addon-banner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service base-addon-timezone: starting
s6-rc: info: service base-addon-log-level: starting
s6-rc: info: service fix-attrs successfully started
[01:31:51] INFO: Configuring timezone (America/Los_Angeles)...
s6-rc: info: service base-addon-log-level successfully started
s6-rc: info: service base-addon-timezone successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service init-emqx: starting
s6-rc: info: service init-emqx successfully started
s6-rc: info: service emqx: starting
s6-rc: info: service emqx successfully started
s6-rc: info: service legacy-services: starting
[01:31:52] INFO: Starting EMQX...
s6-rc: info: service legacy-services successfully started
EMQX_PLUGINS__INSTALL_DIR [plugins.install_dir]: /data/emqx/plugins
EMQX_RPC__PORT_DISCOVERY [rpc.port_discovery]: manual
EMQX_LOG__FILE_HANDLERS__DEFAULT__ENABLE [log.file_handlers.default.enable]: false
EMQX_LOG__CONSOLE_HANDLER__ENABLE [log.console_handler.enable]: true
EMQX_NODE__DATA_DIR [node.data_dir]: /data/emqx/data
EMQX_NODE__COOKIE [node.cookie]: ******
EMQX_NODE__NAME [node.name]: emqx@homeassistant.local
2023-04-25T01:31:58.658788-07:00 [warning] msg: alarm_is_activated, mfa: emqx_alarm:do_actions/3, line: 416, message: <<"82.55% mem usage">>, name: high_system_memory_usage
Listener ssl:default on 0.0.0.0:8883 started.
Listener tcp:default on 0.0.0.0:1883 started.
Listener ws:default on 0.0.0.0:8083 started.
Listener wss:default on 0.0.0.0:8084 started.
Listener http:dashboard on :18083 started.
EMQX 5.0.22 is running now!
2023-04-25T01:32:58.661874-07:00 [warning] msg: alarm_is_deactivated, mfa: emqx_alarm:do_actions/3, line: 422, name: high_system_memory_usage
```

</details>

**Comment by amosyuen** [comment]
Comparison to mosquitto broker portainer stat which only use 16 MB with 0 connections and 24MB with active connections:
![image](https://user-images.githubusercontent.com/422794/234243342-795bbe36-d351-4c4e-adcf-50974853172b.png)

**Comment by qzhuyan** [comment]
Do you have the same problem with our image?

https://hub.docker.com/layers/emqx/emqx/5.0.22/images/sha256-e2f9b865a32293238095b26c38f67a2b32e969bf2ce86ad73c6d6a5cbfb065c8?context=explore

**Comment by qzhuyan** [comment]
I see the default config does not fit small device.

You could try to reduce mem with following config:

```
node {
  max_ports = 4096
  process_limit = 4096
}
```
The numbers are basicly the max number of connections you are going to have + 1024.

**Comment by amosyuen** [comment]
Tried setting those to 1034:

Add-on config for `env_vars`:
```yaml
- name: EMQX_NODE_MAX_PORTS
  value: "1034"
- name: EMQX_NODE_PROCESS_LIMIT
  value: "1034"
```

Confirmed that logs said they were overridden correctly:

```console
[01:46:21] INFO: Setting EMQX_NODE_MAX_PORTS to 1034
[01:46:22] INFO: Setting EMQX_NODE_PROCESS_LIMIT to 1034
```

Still seeing the spikes.
![image](https://user-images.githubusercontent.com/422794/234522408-ec48419d-449f-4db5-8819-d4f3f3fc25d7.png)

**Comment by amosyuen** [comment]
Tried running the normal emqx docker container emqx/emqx:5.0.22. Looks like no memory spikes at rest and cpu is within more expected levels.

![image](https://user-images.githubusercontent.com/422794/234527221-61aa6c56-1c35-4afa-8b00-3ba0e4a84d8a.png)

So seems to indicate that there is something wrong with the HA docker image then.

**Comment by qzhuyan** [comment]
> Tried setting those to 1034:
> 
> Add-on config for `env_vars`:
> 
> ```yaml
> - name: EMQX_NODE_MAX_PORTS
>   value: "1034"
> - name: EMQX_NODE_PROCESS_LIMIT
>   value: "1034"
> ```
> 
> Confirmed that logs said they were overridden correctly:
> 
> ```
> [01:46:21] INFO: Setting EMQX_NODE_MAX_PORTS to 1034
> [01:46:22] INFO: Setting EMQX_NODE_PROCESS_LIMIT to 1034
> ```
> 
> Still seeing the spikes. ![image](https://user-images.githubusercontent.com/422794/234522408-ec48419d-449f-4db5-8819-d4f3f3fc25d7.png)

you need `EMQX_NODE__PROCESS_LIMIT=1034` not `EMQX_NODE_PROCESS_LIMIT=1034`

**Comment by qzhuyan** [comment]
close due to issue unrelates to the EMQX.
