### ISSUE TITLE
constant server crash Cannot allocate 

### ISSUE THREAD

**Issue by gmonk** [emqx/emqx#1053]
#### Environment

- OS: Ubuntu 16.04
- Erlang/OTP: 19
- EMQ: 2.1.2 and 2.2 beta 

#### Description
Server never stays up more than two days without a crash this is a VPS server with 2cores and 1G Ram
only two publishers .  I have a nats.io instance running along side this with the same specs and no issues at all 

Crash dump is to big but here is a snippet
=erl_crash_dump:0.3
Tue May 16 17:07:00 2017
Slogan: eheap_alloc: Cannot allocate 367904368 bytes of memory (of type "old_heap").
System version: Erlang/OTP 19 [erts-8.1] [source-4cc2ce3] [64-bit] [async-threads:32] [hipe] [kernel-poll:true]
Compiled: Wed Oct 12 12:28:55 2016
Taints: dyntrace,crypto,asn1rt_nif,erl_tracer
Atoms: 33121
Calling Thread: scheduler:1
=scheduler:1
Scheduler Sleep Info Aux Work: 
Current Port: 
Run Queue Max Length: 0
Run Queue High Length: 0
Run Queue Normal Length: 0
Run Queue Low Length: 0
Run Queue Port Length: 0
Run Queue Flags: OUT_OF_WORK | HALFTIME_OUT_OF_WORK | NONEMPTY | UNKNOWN(134217728)
Current Process: <0.12949.1>
Current Process State: Garbing
Current Process Internal State: ACT_PRIO_NORMAL | USR_PRIO_NORMAL | PRQ_PRIO_NORMAL | ACTIVE | RUNNING | GC | ON_HEAP_MSGQ
Current Process Program counter: 0x00007fa78fec5a80 (emqttd_metrics:inc/3 + 384)
Current Process CP: 0x0000000000000000 (invalid)
Current Process Limited Stack Trace:
0x00007fa777fff470:SReturn addr 0xACC6A520 (gen_server2:handle_msg/2 + 1912)
0x00007fa777fff478:SReturn addr 0xAD895210 (proc_lib:init_p_do_apply/3 + 56)
0x00007fa777fff498:SReturn addr 0x8F8468 (<terminate process normally>)
=memory
total: 350050040
processes: 259854192
processes_used: 259822080
system: 90195848
atom: 1000625
atom_used: 979841
binary: 50611624
code: 25440686
ets: 5393544
=hash_table:atom_tab
size: 25717
used: 18619
objs: 33121
depth: 8
=index_table:atom_tab
size: 33792
limit: 1048576
entries: 33121
=hash_table:module_code
:

**Comment by emqplus** [comment]
@gmonk Please send me the crash.dump and error logs. mail: feng@emqtt.io

**Comment by emqplus** [comment]
@gmonk I checked the crash.dump you sent to me just now. It seems the crash is caused by OTP-7132: http://erlang.org/pipermail/erlang-questions/2014-February/076950.html 

Which package you deployed on the VPS?  emqttd-ubuntu16.04-v2.2-beta.1_amd64.deb?

**Comment by cjmNo1** [comment]
你好，解决了吗请问
