### ISSUE TITLE
Will messages not sent during client session takeover, violating MQTT 3.1.1 specification

### ISSUE THREAD

**Issue by jbrzozoski** [emqx/emqx#10551]
### What happened?

When an existing MQTT session is taken over by a new connection reusing the same client ID, the will message for the prior connection is not being published. This was tested using MQTT 3.1.1 clients and EMQX 5.0.19.

### What did you expect to happen?

The will message from the first connection must be published when it is closed as per the MQTT 3.1.1 spec. [search ref MQTT-3.1.2-8 in the [spec](https://docs.oasis-open.org/mqtt/mqtt/v3.1.1/os/mqtt-v3.1.1-os.html)]

### How can we reproduce it (as minimally and precisely as possible)?

Using a client of your choice, open two different connections using the same client ID and will messages. As each client connects, the other will be kicked off, but the will messages will not be published.

For example, with `mosquitto_sub` as the client, I ran these two commands in two different consoles, and never saw either will message published, even as they repeatedly kicked each other:
```
mosquitto_sub -L "mqtt://un:pw@testbroker.com/sandbox" -i debug_test1 -v --will-payload SESSION1_WILL --will-topic sandbox/willtest
mosquitto_sub -L "mqtt://un:pw@testbroker.com/sandbox" -i debug_test1 -v --will-payload SESSION2_WILL --will-topic sandbox/willtest
```

### Anything else we need to know?

This used to behave differently in EMQX 3.x, and used to publish the will messages in this session takeover.

### EMQX version

<details>

```console
$ ./bin/emqx_ctl broker
sysdescr  : EMQX
version   : 5.0.19
datetime  : 2023-04-27T13:46:46.540526478+00:00
uptime    : 38 seconds
```

</details>

### OS version

<details>

```console
$ cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
$ uname -a
Linux c48122d7b7e6 5.19.0-40-generic #41~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Fri Mar 31 16:00:14 UTC 2 x86_64 GNU/Linux
```
</details>

### Log files

<details>

[node_dump_20230427_142450.tar.gz](https://github.com/emqx/emqx/files/11344792/node_dump_20230427_142450.tar.gz)

</details>

**Comment by qzhuyan** [comment]
Could you provide a debug trace? following https://www.emqx.io/docs/en/v5.0/observability/log.html?

**Comment by jbrzozoski** [comment]
Here's another `node_dump` at DEBUG level.

[node_dump_20230428_194802.tar.gz](https://github.com/emqx/emqx/files/11356851/node_dump_20230428_194802.tar.gz)

**Comment by jbrzozoski** [comment]
No clustering, just a single node.

**Comment by qzhuyan** [comment]
> Here's another `node_dump` at DEBUG level.
> 
> [node_dump_20230428_194802.tar.gz](https://github.com/emqx/emqx/files/11356851/node_dump_20230428_194802.tar.gz)

There is no log file in the tar, could you find log files under log dir?

The debug log may also print in the console if you start with emqx console.

**Comment by jbrzozoski** [comment]
Sorry. I was testing with Docker and that setup does only console logging by default.
Here's a new node_dump and the matching console log at DEBUG level:

[console_log_20230501_125549.txt.gz](https://github.com/emqx/emqx/files/11365417/console_log_20230501_125549.txt.gz)

[node_dump_20230501_125549.tar.gz](https://github.com/emqx/emqx/files/11365418/node_dump_20230501_125549.tar.gz)

**Comment by qzhuyan** [comment]
thanks for the logs, it looks like a session take over scenario that one client take over another's session but there is no transport close before the take over thus no last will message gets published. EMQX treats it as client reconnect using new transport. This usually happens when a client switches to a new network like wifi to 4G, and it has to reconnect with new transport (using another IPaddr and port). I am not saying EMQX has 100% correct behavior, but it is reasonable behavior.

Usually, two clients shall not share the same session, What kind of issue do you get with this 'no will message' behavior?
Or what problem do you want to solve with receiving 'last will' message?

**Comment by jbrzozoski** [comment]
The [Eclipse Sparkplug protocol](https://sparkplug.eclipse.org/) maintains stateful connections and each connection has an ID number called it's bdSeq. There are situations that the server needs to know when a node did not gracefully close a connection and needs to see the LWT message announcing the termination of the prior bdSeq before it will properly accept and setup a new session with a new bdSeq.

**Comment by qzhuyan** [comment]
@jbrzozoski We will make a fix to it!

**Comment by jbrzozoski** [comment]
Any sense of time until this issue is fixed? Is this actively being looked at or is it just on the backlog?

**Comment by qzhuyan** [comment]
@jbrzozoski I found that this is a takeover scenario where it is not server close the connection AND client has a refreshed connection for use thus I close the ticket.

Let me know if you don't agree.

**Comment by jbrzozoski** [comment]
I'm reading section 3.1.4 of the MQTT 5 spec and I don't agree.

There's this non-normative comment when discussing a client connecting with the same client ID as an existing connection:

>If the Will Delay Interval of the existing Network Connection is 0 and there is a Will Message, it will be sent because the Network Connection is closed. If the Session Expiry Interval of the existing Network Connection is 0, or the new Network Connection has Clean Start set to 1 then if the existing Network Connection has a Will Message it will be sent because the original Session is ended on the takeover.

**Comment by qzhuyan** [comment]
But the network connection from the client is not closed, client just migrates to another connection.

**Comment by jbrzozoski** [comment]
"Network Connection" is defined as the single TCP connection, not the client session. It is explicitly closing "the network connection". This is a mandatory spec statement also from section 3.1.4 (emphasis added by me):

> If the ClientID represents a Client already connected to the Server, the Server sends a DISCONNECT packet to the existing Client with Reason Code of 0x8E (Session taken over) as described in section 4.13 and **MUST close the Network Connection of the existing Client**

**Comment by qzhuyan** [comment]
in mqtt 5,  3.1.2.5 Will Flag
> If the Will Flag is set to 1 this indicates that a Will Message MUST be stored on the Server and associated with the Session

IN mqtt 3.1.1, 3.1.2.5 Will Flag
> If the Will Flag is set to 1 this indicates that, if the Connect request is accepted, a Will Message MUST be stored on the Server and associated with the Network Connection

So in mqtt 3, will msg is associated with *connection* while in mqtt5, will msg is stored in *Session*.

**Comment by jbrzozoski** [comment]
I apologize for jumping back and forth between versions 3.1.1 and 5 earlier. I'll keep them separated this time. However, I think that the final behavior should be mostly the same between both versions if the "Will Delay" feature is not being used (i.e. set to 0) on MQTT 5.  Let's look at each one here:

### MQTT 3.1.1

Yes, the will is associated with a "Network Connection". And mandatory statement MQTT-3.1.2-8 says:

> If the Will Flag is set to 1 this indicates that, if the Connect request is accepted, a Will Message MUST be stored on the Server and associated with the Network Connection. The Will Message MUST be published when the Network Connection is subsequently closed unless the Will Message has been deleted by the Server on receipt of a DISCONNECT Packet.

Following my test procedure back at the beginning of this issue, the client never sends a DISCONNECT packet. The "Network Connection" is each unique TCP stream, not the overarching session, and the broker is closing the older Network Connection because a new one claimed the Client ID. The will message MUST be published. 

### MQTT 5

Yes, the will is assosciated with a "Session". Mandatory statement 3.1.2-8 says:

> The Will Message MUST be published after the Network Connection is subsequently closed and either the Will Delay Interval has elapsed or the Session ends, unless the Will Message has been deleted by the Server on receipt of a DISCONNECT packet with Reason Code 0x00 (Normal disconnection) or a new Network Connection for the ClientID is opened before the Will Delay Interval has elapsed.

This is admittedly more tricky now in detangling the Will Delay feature. Back in section 3.1.3.2.2 the only mandatory statement is MQTT-3.1.3-9:

> If a new Network Connection to this Session is made before the Will Delay Interval has passed, the Server MUST NOT send the Will Message

The exact test to determine if the "Will Delay Interval has passed" isn't immediately clear if the interval is 0. However, immediately below that they give this non-normative comment:

> If a Network Connection uses a Client Identifier of an existing Network Connection to the Server, the Will Message for the exiting connection is sent unless the new connection specifies Clean Start of 0 and the Will Delay is greater than zero. If the Will Delay is 0 the Will Message is sent at the close of the existing Network Connection, and if Clean Start is 1 the Will Message is sent because the Session ends.

Here, it explicitly calls out that the only time the Will Message isn't sent is if the Clean Start on the new connection is 0 and the Will Delay of the old connection is greater than 0.

**Comment by qzhuyan** [comment]
Yes. I agree for MQTT 3.1.1 in your case, will message should be published.

**Comment by qzhuyan** [comment]
EMQX doesn’t publish willmsg when client reconnects with a new connection without first DISCONNECT from the old connection gracefully.  

This does not follow MQTT 3.1.1 spec thus mark the ticket BUG.

The possible reasons for this client behavior could be
1. active network reconnect from the client such as client restart due to errors or reconnect due to network switch or network unreachable/timeout. 
2. passive network disconnect such as NAT rebinding

I need to investigate if the fix will be appreciated before making the fix because 

1. This behavior is mitigated in MQTT 5.0 with will msg delay interval which means this behavior in 3.1.1 may be troublesome.
2. The fix will effect already deployed service that may increase the load unexpectedly if the clients are suffering unstable networks. 
3. I need to check why our fuzzy tool didn't catch it or if it is actually a feature of optimization.

**Comment by jbrzozoski** [comment]
The behavior is "mitigated" in MQTT 5 only if the client is using a non-zero will delay. The spec explicitly calls out that sending the will is the REQUIRED BEHAVIOR with a Will Delay of 0 or a clean session flag set. This is not a "mistake" to repair, this is required and expected behavior. Our products use it. The [Eclipse Sparkplug protocol](https://sparkplug.eclipse.org/) which uses MQTT depends on it.

I also just ran a test by running these two commands in two different consoles:

```
mosquitto_sub --id gh10551 --host broker.emqx.io --topic gh10551/# --protocol-version 5 --property WILL will-delay-interval 0 --will-topic gh10551/will --will-payload LEFT
mosquitto_sub --id gh10551 --host broker.emqx.io --topic gh10551/# --protocol-version 5 --property WILL will-delay-interval 0 --will-topic gh10551/will --will-payload RIGHT
```

I confirmed that EMQX requests the older client disconnect with a "session taken over" reason code, but neither will message is sent at that time. I confirmed using Wireshark that both clients were connecting with "Clean Session" set to 1 and "Will Delay" set to 0. The MQTT 5 spec explicitly states that the will message must be sent in this condition, and EMQX is not doing it correctly in that case.

**Comment by qzhuyan** [comment]
Thanks for testing.

for MQTT 5.0 I think it states the will message is assosciated with a "Session", as the session is taken over, it should not require broker to publish the will message as there is no 'will message' associated with existing old connecion.

**Comment by jbrzozoski** [comment]
No. This is a specific quoted instruction from the MQTT 5.0 spec here:

> If a Network Connection uses **a Client Identifier of an existing Network Connection** to the Server, the Will Message for the exiting connection is sent unless the new connection specifies Clean Start of 0 and the Will Delay is greater than zero.

That instruction can ONLY apply when the ID of an existing Session is being re-used. If you're "will is tied to the Session" argument was true all the time, then that requirement wouldn't make any sense.

They specifically added the ability of the client to prevent the WILL from being sent by using "Clean Session" of 0 and and a non-zero "Will Delay". That implies that a new connection with  "Clean Session"  of 1 _or_ a "Will Delay" of 0 will cause the Will Message to be sent.

**Comment by qzhuyan** [comment]
relates to #8930

**Comment by icraggs** [comment]
Justin has asked me to comment. I'd like to point out that the MQTT 5.0 spec also says:

> If the ClientID represents a Client already connected to the Server, the Server sends a DISCONNECT packet to the existing Client with Reason Code of 0x8E (Session taken over) as described in [section 4.13](https://docs.oasis-open.org/mqtt/mqtt/v5.0/os/mqtt-v5.0-os.html#S4_13_Errors) and MUST close the Network Connection of the existing Client [MQTT-3.1.4-3]. If the existing Client has a Will Message, that Will Message is published as described in section 3.1.2.5.

Section 3.1.2.5 says 

> The Server SHOULD publish Will Messages promptly after the Network Connection is closed and the Will Delay Interval has passed, or when the Session ends, whichever occurs first. 

So when the will delay interval is 0 (the default, unless set) the broker should publish the will message when the network connection ends.

For comparison, I tried this scenario out with Mosquitto and HiveMQ, and they both sent the will message with both MQTT 3.1.1 and MQTT 5.0.

I hope that helps.

**Comment by qzhuyan** [comment]
@jbrzozoski  @icraggs thanks for the info. 
Yes. It is a bug as tagged.  I am playing around and making a fix.


I know spec is a spec.  My understanding is version 5.0 tries to mitigate the pain of this behavior(publishing will message for every abnormal connection close in 3.1.1) by introducing the "Will Delay Interval". In reality, it is not uncommon for devices living in the network which get abnormal connections close actively or passively.  

So the fix might not be appreciated for existing users, and we are seeking a method to solve that.

**Comment by qzhuyan** [comment]
> If a Network Connection uses **a Client Identifier of an existing Network Connection** to the Server, the Will Message for the exiting connection is sent unless the new connection specifies Clean Start of 0 and the Will Delay is greater than zero.

This is Non-normative comment
