### ISSUE TITLE
Connection congestion leading to message drops

### ISSUE THREAD

**Issue by maajidz** [emqx/emqx#10569]
```Emqx ver: 5.0.8
Ubuntu: ubuntu-focal-20.04-amd64-server-20220914
```

We are facing this issue since a while now, I'm not sure if it's an issue of increasing the message queue limit or something else. Suggestions?

Here's a sample log from the alarms

```
connection congested: #{buffer => 4096,clientid => <<"NVCB647645">>,conn_state => connected,connected_at => 1683008050587,high_msgq_watermark => 8192,high_watermark => 1048576,memory => 285048,message_queue_len => 0,peername => <<"117.98.124.2:31273">>,pid => <<"<0.5666.0>">>,proto_name => <<"MQTT">>,proto_ver => 4,recbuf => 131072,recv_cnt => 561,recv_oct => 2807,reductions => 957485,send_cnt => 987,send_oct => 41469,send_pend => 53,sndbuf => 46080,sockname => <<"172.31.41.153:1883">>,socktype => tcp,username => undefined}
```

**Comment by SergeTupchiy** [comment]
Hi @maajidz,

Could you please provide more details about the issue?
Connection congestion alarm itself doesn't cause a connection to be closed. It just says that there are packets waiting to be sent by the socket. 
Have you noticed any other relevant logs? If so, please share them as well or send full logs.
