### ISSUE TITLE
Optional keep alive timout delay based on receiving data

### ISSUE THREAD

**Issue by GunnarMorrigan** [emqx/emqx#10570]
### What would you like to be added or enhanced?

The current keepalive timeout delay is based on receiving a complete MQTT message. We would like the feature to delay keepalive timeout on receiving a `chunk` of one MQTT message.

### Why is this needed?

When sending large files over a slow connection the keep alive timeout can become a problem.
If we have a speed of 10Kb/s and a file that is 2MB this will take 26+ minutes to transfer. We could of course split the file into `chunks`. However, splitting into 10 chunks would still mean 2.6 minutes per chunk. The embedded devices are not capable of determining their internet speed and choosing an appropriate chunk size. 

Currently a solution would be to increase the keep alive timeout.
However, a high keep alive timeout will result in not discovering a possible broken TCP stream fast enough. The above scenario is quickly seen as a broken TCP stream while it is producing data.

We would like to keep the original keep alive timeout when the stream does not produce data and not kill the stream when it is actively producing data. 

This does not align with the MQTT specification of keep alive timeout. Thus, this could be an opt-in feature.

**Comment by qzhuyan** [comment]
We have TCP keep alive and MQTT keep alive, in your case I think you could reply on short TCP keep alive and set much longer keep alive on MQTT layer.
