### ISSUE TITLE
discovered nodes outside cluster:

### ISSUE THREAD

**Issue by HandsomeBoy01** [emqx/emqx#10638]
### What happened?

 
![image](https://user-images.githubusercontent.com/40994318/236821456-d5559908-07d3-4446-8816-25149b2fee08.png)

### What did you expect to happen?

The cluster restart will become like this, even if it is deleted, it will still be like this, how to solve it? version 4 4 11

### EMQX version

<details>

 4.4.11
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Log files

<details>

</details>

**Comment by id** [comment]
@HandsomeBoy01 could you share emqx configuration?

**Comment by id** [comment]
@HandsomeBoy01 

The IP range looks like it's docker network.
If, for example, each node manually joined the cluster, and then nodes restarted and got new IPs, this could be one explanation for this behavior.
