### ISSUE TITLE
Support for offline messages persistence

### ISSUE THREAD

**Issue by behrad** [emqx/emqx#1064]
It seems we currently have no offline message persistency in EMQ free edition (Don't know EMQ plus is free or not, no download link available), however this is a very popular/production needed feature.

I so, how can we safely deliver offline messages across broker restarts?

Is there any hooks available inside EMQ so we can develop an open source plugin to persist QOS=1 messages and make them deliver when client is connected again?

**Comment by emqplus** [comment]
Hi @behrad, we have released an enterprise edition of EMQ to support persistence in various backends. I plan to upgrade the emqtt.io site and publish the edition later:)

**Comment by behrad** [comment]
Is EMQ enterprise edition downloadable to be used free of charge @emqplus ?

**Comment by Max01010101010101** [comment]
Am sorry... so we can't deliver the offline messages when the client is connected again? 
@behrad Tell me that I'm wrong, please. This is a mega-basic and needed feature. Is like an iPhone with no battery.

**Comment by behrad** [comment]
> so we can't deliver the offline messages when the client is connected again?

If broker is restarted, then NO! client won't receive offline messages, since they are not persisted.

**Comment by Max01010101010101** [comment]
@behrad oh thanks, well is not so bad to me.

**Comment by gihad** [comment]
This is a pretty basic feature that is behind the paywall. A paywall that is very hard to understand as there is not transparency regarding pricing and conditions. 
Even worse is a feature like the Kafka bridge and others that simply disappeared from Github. I'm very disappointed with the business practices from the EMQ team.

**Comment by eladnava** [comment]
Completely agree. This is quite basic and if not built-in should be possible via a plugin. Guess I'll try VerneMQ which has built-in LevelDB persistence.

**Comment by mtsoleimani** [comment]
I have developed a tools called Silo to archive all mqtt messages. It support mysql, postgres and mongodb. we use emq as a message broker for chat application. to check offlline message simply you can store last visited message by user and compare it with archived message. now, we use Silo in production. 

check this:
https://github.com/mtsoleimani/Silo

**Comment by turtleDeng** [comment]
@behrad 
The emqx-enterprise supports message persistence to the DB to ensure that messages are not lost.
https://www.emqx.io/downloads/emq/enterprise?osType=Linux
