### ISSUE TITLE
The modification of /etc/emqx/emqx.conf does not take effect after restarting

### ISSUE THREAD

**Issue by AceBear** [emqx/emqx#10670]
### What happened?

I modified the default tcp port from 1883 to 7883 in /etc/emqx/emqx.conf
then restart emqx
but the tcp listening port is still 1883.

### What did you expect to happen?

I need the /etc/emqx/emqx.conf take effect

### How can we reproduce it (as minimally and precisely as possible)?

1.  start emqx as normal.
2.  modify some configuraions in dashboard UI (This will cause a conf file be generated in $EMQX_NODE__DATA_DIR/configs)
3.  modify tcp port from 1883 to 7883 in /etc/emqx/emqx.conf
4.  restart emqx

The tcp listening port is still 1883. 

### Anything else we need to know?

I'm the root user, and emqx service running in a limited account.
This cannot be acceptable that root user modified the tcp port, but does not take any effect!

I know I can modify/remove the file under $EMQX_NODE__DATA_DIR/configs to fix this.
But this is not a good behavior.

### EMQX version

<details>

```console
$ ./bin/emqx_ctl broker
EMQX 5.0.23
```

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
$ uname -a
Linux AAAA 3.10.0-1160.11.1.el7.x86_64 #1 SMP Fri Dec 18 16:34:56 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Log files

<details>

</details>

**Comment by qzhuyan** [comment]
did you change the port from dashboard?

**Comment by keynslug** [comment]
Hi @AceBear,

I can't reproduce the issue.

For reference, I'm running [emqx:5.0.23](https://hub.docker.com/layers/library/emqx/5.0.23/images/sha256-12e2463b0de9fe52971a2584364e2c9b304474670813cdf24b0c8a5ef67d6121?context=explore) as a podman container.

After performing all the steps you mentioned, here are:

1. My `emqx.conf` (TCP listener bound to port 7883).

<details><summary><code> ❯ podman exec emqx-10670 cat /opt/emqx/etc/emqx.conf</code></summary>

```
## NOTE:
## The EMQX configuration is prioritized (overlayed) in the following order:
## `data/configs/cluster.hocon < etc/emqx.conf < environment variables`.


node {
  name = "emqx@127.0.0.1"
  cookie = "emqxsecretcookie"
  data_dir = "data"
}

log {
  file_handlers.default {
    level = warning
    file = "log/emqx.log"
  }
}

cluster {
  name = emqxcl
  discovery_strategy = manual
}


listeners.tcp.default {
  bind = "0.0.0.0:7883"
  max_connections = 1024000
}

listeners.ssl.default {
  bind = "0.0.0.0:8883"
  max_connections = 512000
  ssl_options {
    keyfile = "etc/certs/key.pem"
    certfile = "etc/certs/cert.pem"
    cacertfile = "etc/certs/cacert.pem"
  }
}

listeners.ws.default {
  bind = "0.0.0.0:8083"
  max_connections = 1024000
  websocket.mqtt_path = "/mqtt"
}

listeners.wss.default {
  bind = "0.0.0.0:8084"
  max_connections = 512000
  websocket.mqtt_path = "/mqtt"
  ssl_options {
    keyfile = "etc/certs/key.pem"
    certfile = "etc/certs/cert.pem"
    cacertfile = "etc/certs/cacert.pem"
  }
}

# listeners.quic.default {
#  enabled = true
#  bind = "0.0.0.0:14567"
#  max_connections = 1024000
#  ssl_options {
#   verify = verify_none
#   keyfile = "etc/certs/key.pem"
#   certfile = "etc/certs/cert.pem"
#   cacertfile = "etc/certs/cacert.pem"
#  }
# }

dashboard {
    listeners.http {
        bind = 18083
    }
    default_username = "admin"
    default_password = "public"
}

authorization {
  deny_action = ignore
  no_match = allow
  cache = { enable = true }
  sources =  [
    {
      type = file
      enable = true
      # This file is immutable to EMQX.
      # Once new rules are created from dashboard UI or HTTP API,
      # the file 'data/authz/acl.conf' is used instead of this one
      path = "etc/acl.conf"
    }
  ]
}
```

</details>

2. My `cluster.hocon` file (where TCP listener is bound to 1883).

<details><summary><code> ❯ podman exec emqx-10670 cat data/configs/cluster.hocon</code></summary>

```
listeners {
  ssl {
    default {
      bind = "0.0.0.0:8883"
      max_connections = 512000
      ssl_options {
        cacertfile = "etc/certs/cacert.pem"
        certfile = "etc/certs/cert.pem"
        keyfile = "etc/certs/key.pem"
      }
    }
  }
  tcp {
    default {
      acceptors = 16
      bind = "0.0.0.0:1883"
      enable_authn = true
      enabled = true
      limiter {
        bytes {rate = "infinity"}
        client {
          bytes {rate = "infinity"}
          messages {rate = "infinity"}
        }
        messages {rate = "infinity"}
      }
      max_connections = 1024000
      proxy_protocol = false
      proxy_protocol_timeout = "3s"
      tcp_options {
        active_n = 100
        backlog = 1024
        buffer = "4KB"
        high_watermark = "1MB"
        nodelay = true
        reuseaddr = true
        send_timeout = "15s"
        send_timeout_close = true
      }
      zone = "default"
    }
  }
  ws {
    default {
      bind = "0.0.0.0:8083"
      max_connections = 1024000
      websocket {mqtt_path = "/mqtt"}
    }
  }
  wss {
    default {
      bind = "0.0.0.0:8084"
      max_connections = 512000
      ssl_options {
        cacertfile = "etc/certs/cacert.pem"
        certfile = "etc/certs/cert.pem"
        keyfile = "etc/certs/key.pem"
      }
      websocket {mqtt_path = "/mqtt"}
    }
  }
}
sys_topics {
  sys_event_messages {
    client_connected = true
    client_disconnected = true
    client_subscribed = true
    client_unsubscribed = true
  }
  sys_heartbeat_interval = "30s"
  sys_msg_interval = "1m"
}
```

</details>

After making all the changes and restarting the container with `podman restart emqx-10670` I still get TCP listener bound to 7883, as verified with `mosquitto_pub -h localhost -p 7883 -l -t t/topic`. Also, the dashboard shows `0.0.0.0:7883` as well.

Please double-check if the note at the end of https://www.emqx.io/docs/en/v5.0/configuration/configuration.html#configure-override-rules applies to your deployment.

**Comment by AceBear** [comment]
I installed an 


> did you change the port from dashboard?

Yes.

more details:

The server is located within the environment of a cloud service provider and is configured with additional firewall rules. Consequently, EMQX is configured to operate on a non-default port. The developers utilizing EMQX do not possess the necessary permissions and are unaware of the specific firewall rules in place. Despite attempting to modify the port, they encountered connection issues and ultimately reverted the changes.

Subsequently, I personally took the initiative to modify the firewall rules. However, upon restarting EMQX, I discovered that the modifications did not have the intended effect. This was due to the existence of a "cluster-override.conf" file within the "$EMQX_NODE__DATA_DIR/configs" directory. As a result, the alterations I made to the configuration file located in the "/etc" directory did not take effect.

**Comment by AceBear** [comment]
@keynslug 

I just retried, and this time the generated file under "$EMQX_NODE__DATA_DIR/configs" is named "cluster.hocon," whereas the previous file was named "cluster-override.conf."

The version I initially installed was an older version, likely 5.0.22 (possibly an earlier 5.0.x version). I then upgraded it to 5.0.23 using `yum update`. This version was intended for developer use in a standalone mode. Due to additional firewall rules set up by the cloud service provider, the default port couldn't be used. 

At that time, one of the developers encountered an issue with a connected IoT device and wanted to check if the device could only connect to the default port. They attempted to change the port in the EMQX dashboard but encountered issues due to the firewall rules. They reverted the changes back to the original configuration.

Later, I modified the firewall rules to help troubleshoot the IoT device issue. Once the device problem was resolved, I intended to restore EMQX to the initially configured port by modifying the `/etc/emqx/emqx.conf` file. However, the changes did not take effect because there was a `cluster-override.conf` file located in the `$EMQX_NODE__DATA_DIR/configs` directory. Removing the `cluster-override.conf` file allowed the port specified in `/etc/emqx/emqx.conf` to take effect. The issue was indeed caused by the "override rule." 

The confusion here is that even though I am the ROOT user, EMQX runs under its own user with lower privileges. EMQX shouldn't allow a lower-level user to override the port specifically assigned by the ROOT user. In this case, EMQX's user was unaware of the additional firewall rules.

**Comment by keynslug** [comment]
@AceBear, thanks for clearing this up.

You indeed hit the scenario described at the end of https://www.emqx.io/docs/en/v5.0/configuration/configuration.html#configure-override-rules, because EMQX 5.0.23 and later deliberately keeps pre-5.0.23 behavior if it sees `cluster-override.conf` when starting.

We're thinking about configuration in terms of priority and not in terms of privileges, yet priorities of configuration files of _clean_ EMQX ≥5.0.23 setup should be consistent with your expectations.
