### ISSUE TITLE
Expand column titles where the title is dynamic (topic name etc)

### ISSUE THREAD

**Issue by telefax** [emqx/emqx#10695]
### What happened?

Under "Topic metrics" for instance, I cannot see the full name of a topic.
At 100% zoom it just shows "officeZigbee/offi...", when I zoom out to 67% the whole topic is visible.

### What did you expect to happen?

To see the whole topic title under "topic metrics", either by manually resize the column or automatically (and/or provide this in tooltip).
I'm using firefox.

### How can we reproduce it (as minimally and precisely as possible)?

Just a long topic name, and the web interface will truncate the topic name.

### EMQX version

<details>
docker container emqx/emqx:5.0.24
</details>

### OS version

<details>
docker container emqx/emqx:5.0.24
</details>

### Log files

<details>

</details>

**Comment by lafirest** [comment]
@ysfscream 
Could you please have a look at this?

**Comment by telefax** [comment]
Example where I can't really tell the topics apart
<img width="731" alt="bild" src="https://github.com/emqx/emqx/assets/11796323/18fb0d17-64f1-4459-80f1-3c477ea1d142">

**Comment by ysfscream** [comment]
Hi, @telefax sorry for my late reply. You can hover your mouse over the truncated topic name to see the complete topic name. A tooltip will appear when you hover over the truncated topic name, displaying the full topic name.

<img width="545" alt="image" src="https://github.com/emqx/emqx/assets/21299158/7d9848d5-b399-4d89-8ec6-caf609fda9ef">

**Comment by telefax** [comment]
> Hi, @telefax sorry for my late reply. You can hover your mouse over the truncated topic name to see the complete topic name. A tooltip will appear when you hover over the truncated topic name, displaying the full topic name.
> <img alt="image" width="545" src="https://user-images.githubusercontent.com/21299158/239208884-7d9848d5-b399-4d89-8ec6-caf609fda9ef.png">

Hi, thanks for the reply. I see now that this does not work in firefox (113.0.1 ) but seems to work fine in Safari with tooltip, so maybe its very browser dependent?

**Comment by ysfscream** [comment]
Ah, this is indeed a browser-specific bug that I have reproduced as well. We will continue to investigate this issue and appreciate your feedback.

**Comment by ysfscream** [comment]
Hi, we have fixed this issue in this commit: https://github.com/emqx/emqx-dashboard5/commit/c39c651f8d8f84fd6731cccf74d529242a31edd9

Thank you for your feedback. The next version will include this fix.
