### ISSUE TITLE
Windows build of emqttd 2.2 beta.2 fails

### ISSUE THREAD

**Issue by michaelcplusplus** [emqx/emqx#1069]
#### Environment

- OS: Windows 10
- Erlang/OTP: 
- EMQ: 2.2 beta.2

#### Description
The windows build of emqttd with MSYS2 fails.

*A description of the issue*
I had no problems to build earlier versions of the emqtt broker in exactly this environment.
It seems to be a problem with the build of rebar.

Following steps:
```
git clone -b 'windows' https://github.com/emqtt/emq-relx.git
 cd emq-relx
make
$ make
 DEP    goldrush
make[1]: Verzeichnis „/home/ml/emq-relx/.erlang.mk/rebar“ wird betreten
./bootstrap
escript: exception error: no match of right hand side value "C:\\msys64\\home\\ml\\emq-relx\\.erlang.mk\\rebar\\ebin\\rebar.beam konnte nicht gefunden werden\r\n"
make[1]: *** [Makefile:12: all] Fehler 127
make[1]: Verzeichnis „/home/ml/emq-relx/.erlang.mk/rebar“ wird verlassen
/home/ml/emq-relx
{"init terminating in do_boot",{undef,[{rebar_utils,wordsize,[],[]},{erl_eval,do_apply,6,[{file,"erl_eval.erl"},{line,670}]},{erl_eval,expr,5,[{file,"erl_eval.erl"},{line,228}]},{erl_eval,expr,5,[{file,"erl_eval.erl"},{line,229}]},{erl_eval,expr_list,6,[{file,"erl_eval.erl"},{line,878}]},{erl_eval,expr,5,[{file,"erl_eval.erl"},{line,422}]},{erl_eval,exprs,5,[{file,"erl_eval.erl"},{line,122}]},{init,start_it,1,[{file,"init.erl"},{line,1091}]}]}}

Crash dump is being written to: erl_crash.dump...done
init terminating in do_boot ()

```

I can solve this *rebar* problem if I copy the .erlang.mk\rebar\ directory from an older build directoy.

After this I got the next error message:

```
ml@NB-5654 MSYS ~/emq-relx
$ make
 DEP    emqttd
 DEP    emq_modules
 DEP    emq_dashboard
 DEP    emq_retainer
 DEP    emq_recon
 DEP    emq_reloader
 DEP    emq_auth_clientid
 DEP    emq_auth_username
 DEP    emq_auth_ldap
 DEP    emq_auth_http
 DEP    emq_auth_mysql
 DEP    emq_auth_pgsql
 DEP    emq_auth_redis
 DEP    emq_auth_mongo
 DEP    emq_sn
 DEP    emq_coap
 DEP    emq_stomp
 DEP    emq_plugin_template
 DEP    emq_web_hook
 DEP    emq_lua_hook
make[1]: Verzeichnis „/home/ml/emq-relx/deps/goldrush“ wird betreten
make[1]: *** Keine Ziele.  Schluss.
make[1]: Verzeichnis „/home/ml/emq-relx/deps/goldrush“ wird verlassen
make: *** [erlang.mk:312: deps] Fehler 2
```

**Comment by michaelcplusplus** [comment]
Tested with 2.2-beta.3
The problem still exists:

![image](https://user-images.githubusercontent.com/24432169/26863876-7b965f82-4b55-11e7-9455-b68c84050f09.png)

![image](https://user-images.githubusercontent.com/24432169/26863997-0b92954c-4b56-11e7-9791-3007d2b82d51.png)

**Comment by 18801957105** [comment]
I met the same problem.Your problem solved?If solved, could you tell me is how to solve?Looking forward to your reply!thanks!

**Comment by michaelcplusplus** [comment]
The problem is not solved. I will wait to release 2.3.Until then I use the binary version.I need the build environment only for a elixir plugin enhancement.Am 06.07.2017 12:14 schrieb 18801957105 <notifications@github.com>:I met the same problem.Your problem solved?If solved, could you tell me is how to solve?Looking forward to your reply!thanks!

**Comment by huangdan** [comment]
@michaelcplusplus Current workarounds, you can try it:
```
1.cd .erlang.mk\rebar
2.touch/create ebin/rebar.beam
3.run bootstrap.bat
```

**Comment by michaelcplusplus** [comment]
The workaround does not solve the complete problem.
Now I got the following error:

```
 DEP    emq_lua_hook
 DEP    emq_auth_jwt
 DEP    emq_lwm2m
make[1]: Verzeichnis „/home/ml/emq-relx/deps/goldrush“ wird betreten
make[1]: *** Keine Ziele.  Schluss.
make[1]: Verzeichnis „/home/ml/emq-relx/deps/goldrush“ wird verlassen
make: *** [erlang.mk:312: deps] Fehler 2
```

**Comment by Gilbert-Wong** [comment]
The windows build of emqx3.0.0 release has fixed this problem. Hope that the latest release of emqx could help you.
