### ISSUE TITLE
Can anyone give the proper documentation of plugin for EMQX version=>5.0

### ISSUE THREAD

**Issue by sc-sityad** [emqx/emqx#10750]
### Discussed in https://github.com/emqx/emqx/discussions/10749

<div type='discussions-op-text'>

<sup>Originally posted by **sc-sityad** May 19, 2023</sup>
Q1) I am facing error after download the directory of emqx template plugin. I am not able to perform **make rel** command due to following error.     
 `/home/sitaram/Desktop/Emqx/plugins/emqx-plugin-template/rebar3 emqx_plugrel tar
escript: exception error: undefined function rebar3:main/1
  in function  escript:run/2 (escript.erl, line 758)
  in call from escript:start/1 (escript.erl, line 277)
  in call from init:start_em/1 
  in call from init:do_boot/3 
make: *** [Makefile:49: rel] Error 127
`
I think its related to erlang/OTP 25 related or something else. 

Q2) Is there any easy documentation which elaborate how to update plugins.
</div>

**Comment by ieQu1** [comment]
Hi,

I think `rebar3 tar` command is only found in EMQX fork of rebar3. We use this script to download the fork of rebar3: https://github.com/emqx/emqx/blob/master/scripts/ensure-rebar3.sh
