### ISSUE TITLE
HTTP read API support for retained messages

### ISSUE THREAD

**Issue by edsamonte** [emqx/emqx#1077]
Good work on adding the HTTP Publish API. It makes it easy to send data using REST.

However, I want to ask if it is possible to have an HTTP read API (not subscribe) from retained message? My scenario is that I have a battery-powered device and it sleeps on a particular interval. Which would mean that MQTT connection will consume so much power if used. (I know that the essence of emqttd is MQTT, but having to use this to IoT applications there will be scenarios for optimizing power consumption).

Not really a master in erlang but I tried to play around emqttd_http.erl and tried looking into the source code and I can't seem to understand where or how to pull the retained message from the storage.

I'm hoping you could lead me somewhere or give me hint.
Cheers!

**Comment by emqplus** [comment]
Hi @edmandiesamonte, I suggest to use the CoAP protocol on your LPWAN devices.  The CoAP Gateway provided by EMQ: https://github.com/emqtt/emq-coap

**Comment by edmandiesamonte** [comment]
Thanks, @emqplus. I'll look into it.

**Comment by edmandiesamonte** [comment]
Follow up question: does CoAP supports the auth and acl? Can't find what parameters needed to provide the username and password, though.

**Comment by emqplus** [comment]
@grutabow Does the CoAP gateway of EMQ support auth/ACL?

**Comment by grutabow** [comment]
@edmandiesamonte   RFC7252 stated that:

> CoAP itself does not provide protocol primitives for authentication or authorization; where this is required, it can either be provided by communication security (i.e., IPsec or DTLS) or by object security (within the payload).


emq-coap does not support authentication now. There are two options:
- DTLS
- carry username and password in customed coap options

What do you prefer?

**Comment by edmandiesamonte** [comment]
@grutabow not really familiar with CoAP though doing a quick Google search, seems like using DTLS is predominant. Does emq-coap supports that already? If so, I'll take a look at it.

Thank you.

**Comment by grutabow** [comment]
@edmandiesamonte   emq-coap has been refactored and new version supports following features:
1) authentication by username and password
2) DTLS

You can expect them in next official release.

**Comment by edmandiesamonte** [comment]
@grutabow Awesome! Thanks!
