### ISSUE TITLE
ACL returning `deny` does not close client connection

### ISSUE THREAD

**Issue by yandooo** [emqx/emqx#1080]
#### Environment

- OS: Alpine
- Erlang/OTP: 18
- EMQ: 2.2

#### Description

ACL plugin returning `deny` does not close client connectio (in v1.3 it was closing it).

Seeing the next in the logs and connection is still running 

```bash
20:36:28.427 [error] Client(clientId-1@9.83.128.2:62333): Cannot publish to testtopic/1 for ACL Deny
```

**Comment by emqplus** [comment]
@yandooo The EMQ R2 does not close the connection when a PUBLISH or SUBSCRIBE is denied. We have to adopt the MQTT 5.0 specification later to resolve the issue, I think.

**Comment by PiedPieper** [comment]
@emqplus is there any emqttd function that can be implemented in a custom plugin drop a client by clientid if the ACL fails?

**Comment by emqplus** [comment]
@PiedPieper Terminate the connection if ACL denied?

**Comment by PiedPieper** [comment]
Yes. If we have a custom ACL plugin, that plugin receives the ClientID along with some other arguments to determine if the client should have access to that topic. Inside that code, on an ACL deny, is there any function that can drop the connection with knowledge of the clientID?

**Comment by asanchezdelc** [comment]
@PiedPieper There seems to be a new API to kick a client using it's ID which is super useful. 

`emqttd_mgmt:kick_client(CLIENT_ID)` 

https://github.com/emqtt/emqttd/blob/b1842b535f89e08cb326501f6990c03063064f85/src/emqttd_rest_api.erl#L135
