### ISSUE TITLE
config node.name to domain name on EC2

### ISSUE THREAD

**Issue by rhwu** [emqx/emqx#1081]
#### Environment

- OS: Ubuntu 16.04
- Erlang/OTP: 
- EMQ: 2.1.2

#### Description

Tried to setup emq on Amazon EC2 with Ubuntu 16.04.

The EC2 instance has private ip address 172.31.xx.xx. Domain name msg.mydomain.com points to the public ip address of this EC2 instance.

Downloaded and installed emqttd-ubuntu16.04-v2.1.2_amd64.deb.

With node.name = emqttd@172.31.xx.xx, I can start/stop the server successfully.
sudo emqttd start/stop
sudo emqttd_ctl status

However with node.name = emqttd@msg.mydomain.com
emqttd never returns. emqttd_ctl shows "*** not responding to pings."

So my questions are:
1) Is this expected?
2) What is the proper way to config node.name to domain name when the server has private ip and public ip?

**Comment by rhwu** [comment]
Oh, the reason we want to use domain name is because we want to do ssl. We have ca signed server certificate. Assume we need to set the note name to match the domain name, correct?

**Comment by turtleDeng** [comment]
@rhwu cluster problem reference #496

**Comment by Xirui** [comment]
@terry-xiaoyu the FQDN/IP address mapping is correct. I am following the instructions from: https://medium.com/@emqtt/using-lets-encrypt-certificates-in-emq-b11e0e57efa6

Is it possible for you guys to write a blog specifically for deploying EMQ on Azure/AWS instance. Thanks!

**Comment by terry-xiaoyu** [comment]
@Xirui which EMQ version are you using?

Make sure your firewall config has allowed the port `4369` for `epmd`, and also the port range `6369-6379` for erlang distribution.

The erlang distribution ports are configured in etc/emq.conf:
```
node.dist_listen_min = 6369
node.dist_listen_max = 6379
```

**Comment by Xirui** [comment]
@terry-xiaoyu I am using emqttd-ubuntu16.04-v2.3.7.zip on standard Azure Ubuntu 16.04 VM. Port 4369 is allowed for epmd.

The instance has private ip address 10.2.xx.xx. Domain name msg.somedomain.com points to the public ip address of this instance.

**Comment by Xirui** [comment]
@terry-xiaoyu Mosquitto with TLS is working fine for me. But I really wish to have emq running, as it provides better performance & scalability. Thanks for the help!

**Comment by terry-xiaoyu** [comment]
@Xirui Please check the firewall configures and make sure it also allows `6369-6379` of your **public ip addr**. 

Configure TLS with EMQ will work but we recommend you setup a reverse proxy such as HAProxy or Nginx in front of EMQ, and config TLS only in the proxy.

**Comment by Xirui** [comment]
@terry-xiaoyu Thanks Terry, I checked those. Unfortunately I still could not make EMQ working. I tried vernemq instead, it took me 10 mins to make it up and running.

I am really not sure which part I missed :( 

Anyway, thanks for help. I might check EMQ sometime later.

**Comment by terry-xiaoyu** [comment]
@Xirui 

What's you problem now and what have you tried?

Are you just trying to config TLS on 8883 for your MQTT clients? Or are you configuring the distributed erlang over TLS to setup a cluster across data-centers? In case of the former, changing node name to a FQDN is not necessary. You could use your private IP. In case of the latter, `etc/ssl_dist.conf` should be configured.

You can post your configurations and error logs here. It should not be that difficult.

**Comment by Xirui** [comment]
@terry-xiaoyu I am just trying to config TLS on 8883 for MQTT clients. Attached is the conf file.

[emq.conf.zip](https://github.com/emqtt/emqttd/files/1948800/emq.conf.zip)

Thanks!
