### ISSUE TITLE
软件界面啥都没有

### ISSUE THREAD

**Issue by XBbox** [emqx/emqx#10845]
### What happened?

前两天用没问题，昨天发现打开MQTTX （ver :1.9.3）软件后什么都没显示

### What did you expect to happen?

能正常使用软件

### EMQX version

<details>

```console
$ ./bin/emqx_ctl broker
# paste output here
```

</details>
v1.9.3

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```
BuildNumber  Caption                          OSArchitecture  Version
22621        Microsoft Windows 11 家庭中文版  64 位           10.0.22621

</details>

### Log files

<details>

</details>

**Comment by terry-xiaoyu** [comment]
Created another issue on the MQTTX repo: https://github.com/emqx/MQTTX/issues/1311.
