### ISSUE TITLE
EMQ 2.1.2 freezes during a stress test

### ISSUE THREAD

**Issue by davidepozza** [emqx/emqx#1090]
#### Environment

OS: Docker alpine:3.4
Erlang/OTP: default installed from this alpine version repos
EMQ: v2.1.2

#### Description

After 2-3 hours of stress test (3000 parallel clients sending a message every 10secs) the broker freezes and all the clients got instantly disconnected for timeout (Timed out waiting for a response from the server (32000)).
The listener on 1883 seems to be still active (I can also estabilish a telnet session) but no messages are delivered.
The logs just stops writing without any error or crash notification.

Here's all the data collected after the freeze:

···
**/opt/emqttd # ./bin/emqttd_ctl status**
Node '9508c17d59e1@172.19.0.4' is started
emqttd 2.1.2 is running

**/opt/emqttd # ./bin/emqttd_ctl broker**
sysdescr  : Erlang MQTT Broker
version   : 2.1.2
uptime    : 2 hours, 50 minutes, 17 seconds
datetime  : 2017-06-07 12:18:57
**/opt/emqttd # ./bin/emqttd_ctl broker stats**
clients/count       : 3002
clients/max         : 3002
retained/count      : 0
retained/max        : 0
routes/count        : 2998
routes/max          : 2998
sessions/count      : 3002
sessions/max        : 3002
subscribers/count   : 3005
subscribers/max     : 3005
subscriptions/count : 3005
subscriptions/max   : 3005
topics/count        : 0
topics/max          : 0

**/opt/emqttd # ./bin/emqttd_ctl broker metrics**
bytes/received          : 142241698
bytes/sent              : 266154186
messages/dropped        : 5484
messages/qos0/received  : 2304
messages/qos0/sent      : 0
messages/qos1/received  : 1319078
messages/qos1/sent      : 2625716
messages/qos2/dropped   : 0
messages/qos2/received  : 0
messages/qos2/sent      : 0
messages/received       : 1321382
messages/retained       : 0
messages/sent           : 2625716
packets/connack         : 3012
packets/connect         : 5832
packets/disconnect      : 10
packets/pingreq         : 406
packets/pingresp        : 403
packets/puback/missed   : 0
packets/puback/received : 2625664
packets/puback/sent     : 1316083
packets/pubcomp/missed  : 0
packets/pubcomp/received: 0
packets/pubcomp/sent    : 0
packets/publish/received: 1321382
packets/publish/sent    : 2625716
packets/pubrec/missed   : 0
packets/pubrec/received : 0
packets/pubrec/sent     : 0
packets/pubrel/missed   : 0
packets/pubrel/received : 0
packets/pubrel/sent     : 0
packets/received        : 3956305
packets/sent            : 3948225
packets/suback          : 3011
packets/subscribe       : 3011
packets/unsuback        : 0
packets/unsubscribe     : 0
···
**/opt/emqttd # ./bin/emqttd_ctl clients list|wc -l**
3002

 **./bin/emqttd_ctl sessions list**
 Session(dev00000, clean_sess=false, subscriptions=1, max_inflight=32768, inflight=0, mqueue_len=0, mqueue_dropped=0, awaiting_rel=0, deliver_msg=0, enqueue_msg=0, created_at=1496828210)
 [...]
 Session(dev02994, clean_sess=false, subscriptions=1, max_inflight=32768, inflight=0, mqueue_len=0, mqueue_dropped=0, awaiting_rel=0, deliver_msg=0, enqueue_msg=0, created_at=1496829840)
 
**/opt/emqttd # ./bin/emqttd_ctl topics list|wc -l**
2998

**/opt/emqttd # ./bin/emqttd_ctl subscriptions list|wc -l**
3005

**/opt/emqttd # ./bin/emqttd_ctl vm load**
cpu/load1               : 1.54
cpu/load5               : 1.40
cpu/load15              : 1.18

**/opt/emqttd # ./bin/emqttd_ctl vm memory**
memory/total            : 268872096
memory/processes        : 143826104
memory/processes_used   : 143825672
memory/system           : 125045992
memory/atom             : 1123529
memory/atom_used        : 1104704
memory/binary           : 5728776
memory/code             : 25446832
memory/ets              : 49286904

**/opt/emqttd # ./bin/emqttd_ctl vm process**
process/limit           : 2097152
process/count           : 9255

**/opt/emqttd # ./bin/emqttd_ctl vm io**
io/max_fds              : 65536
io/active_fds           : 1

**/opt/emqttd # ./bin/emqttd_ctl listeners**
listener on mqtt:wss:8084
  acceptors       : 32
  max_clients     : 1000000
  current_clients : 0
  shutdown_count  : []
listener on mqtt:ws:8083
  acceptors       : 16
  max_clients     : 250000
  current_clients : 2
  shutdown_count  : []
listener on mqtt:ssl:8883
  acceptors       : 32
  max_clients     : 500000
  current_clients : 0
  shutdown_count  : []
listener on mqtt:tcp:1883
  acceptors       : 64
  max_clients     : 1000000
  current_clients : 5822
  shutdown_count  : [{idle_timeout,301}]
listener on stomp:61613
  acceptors       : 4
  max_clients     : 512
  current_clients : 0
  shutdown_count  : []
listener on dashboard:http:18083
  acceptors       : 2
  max_clients     : 512
  current_clients : 0
  shutdown_count  : []
···

Thank you in advance

**Comment by emqplus** [comment]
@davidepozza There is something wrong in your test case, I think. The broker works fine still for there are only thousands of concurrent clients and messages. Check the error logs and fix your test case.

The benchmark documentation of EMQ 2.0: http://emq-xmeter-benchmark-en.readthedocs.io/en/latest/
