### ISSUE TITLE
Authentication issues after PostgreSql restart.

### ISSUE THREAD

**Issue by may-cDev** [emqx/emqx#10925]
### What happened?

I have a 3 node EMQX cluster running in AKS and have authentication via Postgres enabled and in general it's working fine.

However, today I restarted my Postgres database (Azure hosted) and after it was up again I could not send messages via the EMQX broker anymore, neither by connecting with e.g. MQTTX nor with my application services that usually send and consume data.

In the logs I found a lot of messages looking like this:

`2023-06-02T02:30:05.862140+00:00 [error] msg: unrecoverable_error, mfa: emqx_resource_buffer_worker:handle_query_result_pure/3, line: 834, peername: BLANKED, clientid: BLANKED, id: <<"emqx_authn_pgsql:3">>, reason: {unrecoverable_error,{error,error,<<"26000">>,invalid_sql_statement_name,<<"prepared statement \"emqx_authn_pgsql:3\" does not exist">>,[]}}
2023-06-02T02:30:05.862382+00:00 [error] msg: postgresql_query_failed, mfa: emqx_authn_pgsql:authenticate/2, line: 140, peername: BLANKED, clientid: BLANKED, params: [<<"BLANKED">>], provider: emqx_authn_pgsql, reason: {unrecoverable_error,{error,error,<<"26000">>,invalid_sql_statement_name,<<"prepared statement \"emqx_authn_pgsql:3\" does not exist">>,[]}}, resource: <<"emqx_authn_pgsql:3">>, tag: AUTHN`

As soon as I delete an EMQX pod and it reboots everything is working fine again (on that specific pod).

I could reproduce this behaviour for my case easily.

### What did you expect to happen?

After some time of failures (while Postgres Reboot) I can connect to the EMQX broker again and authenticate with success.

### How can we reproduce it (as minimally and precisely as possible)?

Deploy EMQX with Postgres Authentication enabled and connected to a (Azure hosted) Postgres DB.
Reboot the Postgres DB.
Try to connect to the EMQX broker.

### EMQX version

<details>

sysdescr  : EMQX
version   : 5.0.21

</details>

**Comment by thalesmg** [comment]
Hi @may-cDev .

I can reproduce your problem in v5.0.21, but not in v5.0.26.  I believe there was a [recent change](https://github.com/emqx/emqx/pull/10362) that may have fixed that issue, and it's available since v5.0.25.

Could you try upgrading to the latest versions and see if the problem persists?

**Comment by may-cDev** [comment]
Hey @thalesmg,

thanks for that hint. I tried it with version 5.0.26 and indeed I can not reproduce the behaviour anymore.
Thanks for your help!
