### ISSUE TITLE
Increasing memory usage with persistent storage

### ISSUE THREAD

**Issue by rubengees** [emqx/emqx#10940]
### What happened?

We recently enabled persistent storage to keep messages across broker restarts. Since then, the memory usage continously increases until the limit is reached and the application is killed by k8s. This is a cluster of 3 EMQX nodes handling at most ~20 message/sec. Here are charts of one instance:

| Memory usage | CPU usage |
| -- | -- |
| ![memory](https://github.com/emqx/emqx/assets/8021265/51282452-53fb-4925-aa9c-2ff1dd7e3987) | ![cpu](https://github.com/emqx/emqx/assets/8021265/71e81cb2-a713-4e61-970e-a5a1e28420ac) |

The storage usage of the persistent volume is also continously increasing.

I looked at the files in `data/mnesia` and it looks like the `session_msg` file is the problem. Here is a list of files in the directory: 

```console
$ du -ah | sort -h
0	./emqx_persistent_msg-_tab.extrdb/LOCK
4.0K	./DECISION_TAB.LOG
4.0K	./cluster_rpc_commit.DCD
4.0K	./cluster_rpc_mfa.DCD
4.0K	./emqx_acl.DCD
4.0K	./emqx_activated_alarm.DCD
4.0K	./emqx_admin.DCD
4.0K	./emqx_admin_jwt.DCD
4.0K	./emqx_admin_jwt.DCL
4.0K	./emqx_app.DCD
4.0K	./emqx_app.DCL
4.0K	./emqx_authn_mnesia.DCD
4.0K	./emqx_banned.DCD
4.0K	./emqx_delayed.DCD
4.0K	./emqx_enhanced_authn_scram_mnesia.DCD
4.0K	./emqx_persistent_msg-_tab.extrdb/CURRENT
4.0K	./emqx_persistent_msg-_tab.extrdb/IDENTITY
4.0K	./emqx_psk.DCD
4.0K	./emqx_session_route_disc.DCL
4.0K	./emqx_session_trie.DCD
4.0K	./emqx_session_trie.DCL
4.0K	./emqx_telemetry.DCD
4.0K	./emqx_telemetry.DCL
4.0K	./emqx_trace.DCD
8.0K	./emqx_persistent_msg-_tab.extrdb/OPTIONS-000007
20K	./emqx_deactivated_alarm.DCD
20K	./emqx_session_route_disc.DCD
28K	./emqx_dashboard_monitor.DCL
44K	./schema.DAT
60K	./emqx_session_store.DCD
1.2M	./LATEST.LOG
1.6M	./emqx_persistent_msg-_tab.extrdb/000418.sst
1.8M	./emqx_session_store.DCL
2.6M	./emqx_persistent_msg-_tab.extrdb/LOG
2.9M	./emqx_dashboard_monitor.DCD
4.0M	./emqx_persistent_msg-_tab.extrdb/000416.sst
4.0M	./emqx_persistent_msg-_tab.extrdb/MANIFEST-000004
4.5M	./emqx_persistent_msg-_tab.extrdb/000417.log
11M	./emqx_session_msg.DCL
17M	./emqx_persistent_msg-_tab.extrdb
95M	./emqx_session_msg.DCD
128M	.
```

I checked `emqx_session_msg.DCD` and it seems to contain some topic names we send messages on very often. Does some cleanup routine not work as expected?

This does not happen when the ram cache is disabled, but then we have very high CPU usage.

### What did you expect to happen?

Memory, storage and cpu usage being stable.

### How can we reproduce it (as minimally and precisely as possible)?

Set the `EMQX_PERSISTENT_SESSION_STORE__ENABLED` and `EMQX_PERSISTENT_SESSION_STORE__RAM_CACHE` options to `true` and send messages over a period of time.

### Anything else we need to know?

Let me know if I can provide any other info or try any option to help with this issue.

### EMQX version

<details>

```console
$ ./bin/emqx_ctl broker
sysdescr  : EMQX
version   : 5.0.26
datetime  : 2023-06-05T06:47:00.773597872+00:00
uptime    : 2 days, 21 hours, 3 minutes, 46 seconds
```

</details>

### OS version

<details>

```console
$ cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

$ uname -a
Linux emqx-0 6.0.0-0.deb11.6-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.0.12-1~bpo11+1 (2022-12-19) x86_64 GNU/Linux
```

</details>

**Comment by lafirest** [comment]
@rubengees 
I am sorry to say that the current version of the persistent storage is not ready to get usable performance, we are improving it, please wait a while.

**Comment by rubengees** [comment]
Hi @lafirest,

thanks for the answer! Okay, we will disable this then for now.

Are improvements on this feature coming with one of the next versions (I think I read 5.1 may have them somewhere) or can we expect this to take a longer time?

**Comment by ieQu1** [comment]
Hi,

Technical overview of the new implementation of embedded message storage is maintained here:

https://github.com/emqx/eip/blob/main/active/0023-rocksdb-message-persistence.md

First PR of the feature has been merged recently:

https://github.com/emqx/emqx/pull/11108 (please don't mind BSL license, the resulting feature will be available under Apache license as soon as design is finalized)

Est. time of full delivery is this Fall.
