### ISSUE TITLE
How to use mongodb(with ssl) to maintain the client certificate revokation list(CRLs), Triggers emqx if cert is revoked.

### ISSUE THREAD

**Issue by sc-sityad** [emqx/emqx#10957]
### Discussed in https://github.com/emqx/emqx/discussions/10956

<div type='discussions-op-text'>

<sup>Originally posted by **sc-sityad** June  7, 2023</sup>
- I am using emqx 5.026 version in which there is only option to enabel the crl check which checks the CA authority certificate if it has the CRL list and checks if it revoked or not. 
- But I am using small step for certificate generation (CA) which does not support the CRLs and OCSP stapling. 
- I wanted to manage the CRLs with mongodb(with ssl) and integrate with emqx, How to do that can anyone guide me with detailed explanation?</div>

**Comment by zmstone** [comment]
Hi @sc-sityad 
The CRL feature in EMQX is provided by Erlang/OTP.
It only supports HTTP endpoint to download the data at the moment.

If you want to swap in a download from mongodb instead, you'll need to dig into the Erlang/OTP code base.
I'm afraid I don't know this part of OTP good enough to provide more pointers.
