### ISSUE TITLE
MQTT clients disconnect frequently

### ISSUE THREAD

**Issue by ypyaaa** [emqx/emqx#10958]
### What happened?

mqtt客户端经常断链 抓包发现
![RtSqGCFejU](https://github.com/emqx/emqx/assets/19565638/316ceddb-8ba3-442c-8f22-c4d6e7b3228b)
每次断连前都出现此情况

### What did you expect to happen?

希望连接能稳定下去

### EMQX version

4.3.18

### OS version

ubuntu 18.04 在docker中启动 docker版本20.10.17

### Log files

<details>

</details>

**Comment by ypyaaa** [comment]
![image](https://github.com/emqx/emqx/assets/19565638/74a9cd97-3475-4ad1-890c-9239c75567a7)

**Comment by ypyaaa** [comment]
@

> @ypyaaa Hi, first, version 4.3.18 is no longer maintained, second, it seems the `Disconnect Req` is sent from your clients, your need to find the reason from your code.
分析完整的包发现是服务端 主动调起的关闭

**Comment by ypyaaa** [comment]
> @ypyaaa Hi, first, version 4.3.18 is no longer maintained, second, it seems the `Disconnect Req` is sent from your clients, your need to find the reason from your code.
![image](https://github.com/emqx/emqx/assets/19565638/f0368903-e335-4517-b251-10001e41ee97)
服务端在正常接受数据的时候 直接发送关闭请求 导致客户端关闭了

**Comment by lafirest** [comment]
Could you provide a debug-level log, thanks.

**Comment by ypyaaa** [comment]
> Hi, first, version 4.3.18 is no longer maintained,

![image](https://github.com/emqx/emqx/assets/19565638/5a1d9641-1d5b-4f7b-8a1c-9c92024cc8fd)

我们将emqx版本提到了 4.4.18 打开了debug日志 发现这个报错

**Comment by lafirest** [comment]
> > Hi, first, version 4.3.18 is no longer maintained,
> 
> ![image](https://user-images.githubusercontent.com/19565638/243976921-5a1d9641-1d5b-4f7b-8a1c-9c92024cc8fd.png)
> 
> 我们将emqx版本提到了 4.4.18 打开了debug日志 发现这个报错

This is just information about the OOM check which is harmless, please paste your log file here if possible and make sure it contains connection logs.

**Comment by ypyaaa** [comment]
> This is just information about the OOM check which is harmless, please paste your log file here if possible and make sure it contains connection logs.
麻烦问下有没有啥关键字  这日志太多了 不太好找

**Comment by ypyaaa** [comment]
> > > Hi, first, version 4.3.18 is no longer maintained,
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/19565638/243976921-5a1d9641-1d5b-4f7b-8a1c-9c92024cc8fd.png)
> > 我们将emqx版本提到了 4.4.18 打开了debug日志 发现这个报错
> 
> This is just information about the OOM check which is harmless, please paste your log file here if possible and make sure it contains connection logs.

 2023-06-07T16:50:18.681113+08:00 [debug] {6a858b02-e43f-4249-8b14-6b031abf8bc6}@172.18.7.2:58660 [Mnesia] ACL ignored, Topic: <<"089/001/0002/scu_data_collection/30/a1_loop1_current">>, Action: publish for Client: #{anonymous => false,auth_result => success,clientid => <<"{6a858b02-e43f-4249-8b14-6b031abf8bc6}">>,is_bridge => false,is_superuser => false,mountpoint => undefined,peerhost => {172,18,7,2},protocol => mqtt,sockport => 1883,username => <<"zzmj_mqtt_default_user">>,zone => external}
2023-06-07T16:50:18.681336+08:00 [info] {6a858b02-e43f-4249-8b14-6b031abf8bc6}@172.18.7.2:58660 PUBLISH to 089/001/0002/scu_data_collection/30/a1_loop1_current: <<"{\"value\":\"0\",\"updateCount\":1225,\"state\":0,\"timestamp\":1686127767291}\n">>
2023-06-07T16:50:18.681410+08:00 [debug] {46c2b4e6-7a02-4093-b9ba-c66bfd393abd}@172.18.6.151:51147 file: emqx_connection.erl, line: 813, mfa: {emqx_connection,check_oom,1}, msg: check_oom, pid: <0.2294.0>, policy: #{max_heap_size => 67108864,message_queue_len => 10000}
2023-06-07T16:50:18.681507+08:00 [debug] {6a858b02-e43f-4249-8b14-6b031abf8bc6}@172.18.7.2:58660 [MQTT] RECV <<97,116,97,95,99,111,108,108,101,99,116,105,111,110,47,51,48,47,97,49,95,108,111,111,112,50,95,118,111,108,116,123,34,118,97,108,117,101,34,58,34,48,46,48,34,44,34,117,112,100,97,116,101,67,111,117,110,116,34,58,49,50,50,53,44,34,115,116,97,116,101,34,58,48,44,34,116,105,109,101,115,116,97,109,112,34,58,49,54,56,54,49,50,55,55,54,55,50,57,...>>
2023-06-07T16:50:18.681670+08:00 [debug] {6a858b02-e43f-4249-8b14-6b031abf8bc6}@172.18.7.2:58660 [MQTT] RECV PUBLISH(Q0, R1, D0, Topic=089/001/0002/scu_data_collection/30/a1_loop2_volt, PacketId=undefined, Payload=<<"{\"value\":\"0.0\",\"updateCount\":1225,\"state\":0,\"timestamp\":1686127767291}\n">>)
2023-06-07T16:50:18.681910+08:00 [debug] 3c304215-469d-c6b1-a211-90c58e01b703@172.18.7.2:58196 [MQTT] SEND PUBLISH(Q0, R0, D0, Topic=089/001/0002/scu/98/errors, PacketId=undefined, Payload=<<"{\"value\":\"1C1D\",\"updateCount\":1216,\"state\":0,\"timestamp\":1686127767291}\n">>)
2023-06-07T16:50:18.682053+08:00 [debug] 3c304215-469d-c6b1-a211-90c58e01b703@172.18.7.2:58196 [MQTT] SEND PUBLISH(Q0, R0, D0, Topic=089/001/0002/scu_power/98/errors, PacketId=undefined, Payload=<<"{\"value\":\"\",\"updateCount\":1216,\"state\":0,\"timestamp\":1686127767291}\n">>)
2023-06-07T16:50:18.682166+08:00 [debug] 3c304215-469d-c6b1-a211-90c58e01b703@172.18.7.2:58196 [MQTT] SEND PUBLISH(Q0, R0, D0, Topic=089/001/0002/scu_coupler/98/errors, PacketId=undefined, Payload=<<"{\"value\":\"\",\"updateCount\":1217,\"state\":0,\"timestamp\":1686127767291}\n">>)
2023-06-07T16:50:18.682320+08:00 [debug] 3c304215-469d-c6b1-a211-90c58e01b703@172.18.7.2:58196 [MQTT] SEND PUBLISH(Q0, R0, D0, Topic=089/001/0002/scu_coupler_switch/98/errors, PacketId=undefined, Payload=<<"{\"value\":\"\",\"updateCount\":1216,\"state\":0,\"timestamp\":1686127767291}\n">>)
2023-06-07T16:50:18.682444+08:00 [debug] 3c304215-469d-c6b1-a211-90c58e01b703@172.18.7.2:58196 [MQTT] SEND PUBLISH(Q0, R0, D0, Topic=089/001/0002/scu_data_collection/30/a1_loop1_volt, PacketId=undefined, Payload=<<"{\"value\":\"0.0\",\"updateCount\":1225,\"state\":0,\"timestamp\":1686127767291}\n">>)
2023-06-07T16:50:18.682544+08:00 [debug] 3c304215-469d-c6b1-a211-90c58e01b703@172.18.7.2:58196 [MQTT] SEND PUBLISH(Q0, R0, D0, Topic=089/001/0002/scu_data_collection/30/a1_loop1_current, PacketId=undefined, Payload=<<"{\"value\":\"0\",\"updateCount\":1225,\"state\":0,\"timestamp\":1686127767291}\n">>)
2023-06-07T16:50:18.682580+08:00 [info] {46c2b4e6-7a02-4093-b9ba-c66bfd393abd}@172.18.6.151:51147 file: emqx_connection.erl, line: 544, mfa: {emqx_connection,terminate,2}, msg: terminate, pid: <0.2294.0>, reason: {shutdown,message_queue_too_long}
2023-06-07T16:50:18.682879+08:00 [debug] client_id: <<"{46c2b4e6-7a02-4093-b9ba-c66bfd393abd}">>, file: emqx_cm.erl, line: 566, mfa: {emqx_cm,clean_down,1}, msg: emqx_cm_clean_down, pid: <0.1804.0>

是这行吗

**Comment by lafirest** [comment]
> > > > Hi, first, version 4.3.18 is no longer maintained,
> > > 
> > > 
> > > ![image](https://user-images.githubusercontent.com/19565638/243976921-5a1d9641-1d5b-4f7b-8a1c-9c92024cc8fd.png)
> > > 我们将emqx版本提到了 4.4.18 打开了debug日志 发现这个报错
> > 
> > 
> > This is just information about the OOM check which is harmless, please paste your log file here if possible and make sure it contains connection logs.
> 
> 2023-06-07T16:50:18.681113+08:00 [debug] {6a858b02-e43f-4249-8b14-6b031abf8bc6}@172.18.7.2:58660 [Mnesia] ACL ignored, Topic: <<"089/001/0002/scu_data_collection/30/a1_loop1_current">>, Action: publish for Client: #{anonymous => false,auth_result => success,clientid => <<"{6a858b02-e43f-4249-8b14-6b031abf8bc6}">>,is_bridge => false,is_superuser => false,mountpoint => undefined,peerhost => {172,18,7,2},protocol => mqtt,sockport => 1883,username => <<"zzmj_mqtt_default_user">>,zone => external} 2023-06-07T16:50:18.681336+08:00 [info] {6a858b02-e43f-4249-8b14-6b031abf8bc6}@172.18.7.2:58660 PUBLISH to 089/001/0002/scu_data_collection/30/a1_loop1_current: <<"{"value":"0","updateCount":1225,"state":0,"timestamp":1686127767291}\n">> 2023-06-07T16:50:18.681410+08:00 [debug] {46c2b4e6-7a02-4093-b9ba-c66bfd393abd}@172.18.6.151:51147 file: emqx_connection.erl, line: 813, mfa: {emqx_connection,check_oom,1}, msg: check_oom, pid: <0.2294.0>, policy: #{max_heap_size => 67108864,message_queue_len => 10000} 2023-06-07T16:50:18.681507+08:00 [debug] {6a858b02-e43f-4249-8b14-6b031abf8bc6}@172.18.7.2:58660 [MQTT] RECV <<97,116,97,95,99,111,108,108,101,99,116,105,111,110,47,51,48,47,97,49,95,108,111,111,112,50,95,118,111,108,116,123,34,118,97,108,117,101,34,58,34,48,46,48,34,44,34,117,112,100,97,116,101,67,111,117,110,116,34,58,49,50,50,53,44,34,115,116,97,116,101,34,58,48,44,34,116,105,109,101,115,116,97,109,112,34,58,49,54,56,54,49,50,55,55,54,55,50,57,...>> 2023-06-07T16:50:18.681670+08:00 [debug] {6a858b02-e43f-4249-8b14-6b031abf8bc6}@172.18.7.2:58660 [MQTT] RECV PUBLISH(Q0, R1, D0, Topic=089/001/0002/scu_data_collection/30/a1_loop2_volt, PacketId=undefined, Payload=<<"{"value":"0.0","updateCount":1225,"state":0,"timestamp":1686127767291}\n">>) 2023-06-07T16:50:18.681910+08:00 [debug] 3c304215-469d-c6b1-a211-90c58e01b703@172.18.7.2:58196 [MQTT] SEND PUBLISH(Q0, R0, D0, Topic=089/001/0002/scu/98/errors, PacketId=undefined, Payload=<<"{"value":"1C1D","updateCount":1216,"state":0,"timestamp":1686127767291}\n">>) 2023-06-07T16:50:18.682053+08:00 [debug] 3c304215-469d-c6b1-a211-90c58e01b703@172.18.7.2:58196 [MQTT] SEND PUBLISH(Q0, R0, D0, Topic=089/001/0002/scu_power/98/errors, PacketId=undefined, Payload=<<"{"value":"","updateCount":1216,"state":0,"timestamp":1686127767291}\n">>) 2023-06-07T16:50:18.682166+08:00 [debug] 3c304215-469d-c6b1-a211-90c58e01b703@172.18.7.2:58196 [MQTT] SEND PUBLISH(Q0, R0, D0, Topic=089/001/0002/scu_coupler/98/errors, PacketId=undefined, Payload=<<"{"value":"","updateCount":1217,"state":0,"timestamp":1686127767291}\n">>) 2023-06-07T16:50:18.682320+08:00 [debug] 3c304215-469d-c6b1-a211-90c58e01b703@172.18.7.2:58196 [MQTT] SEND PUBLISH(Q0, R0, D0, Topic=089/001/0002/scu_coupler_switch/98/errors, PacketId=undefined, Payload=<<"{"value":"","updateCount":1216,"state":0,"timestamp":1686127767291}\n">>) 2023-06-07T16:50:18.682444+08:00 [debug] 3c304215-469d-c6b1-a211-90c58e01b703@172.18.7.2:58196 [MQTT] SEND PUBLISH(Q0, R0, D0, Topic=089/001/0002/scu_data_collection/30/a1_loop1_volt, PacketId=undefined, Payload=<<"{"value":"0.0","updateCount":1225,"state":0,"timestamp":1686127767291}\n">>) 2023-06-07T16:50:18.682544+08:00 [debug] 3c304215-469d-c6b1-a211-90c58e01b703@172.18.7.2:58196 [MQTT] SEND PUBLISH(Q0, R0, D0, Topic=089/001/0002/scu_data_collection/30/a1_loop1_current, PacketId=undefined, Payload=<<"{"value":"0","updateCount":1225,"state":0,"timestamp":1686127767291}\n">>) 2023-06-07T16:50:18.682580+08:00 [info] {46c2b4e6-7a02-4093-b9ba-c66bfd393abd}@172.18.6.151:51147 file: emqx_connection.erl, line: 544, mfa: {emqx_connection,terminate,2}, msg: terminate, pid: <0.2294.0>, reason: {shutdown,message_queue_too_long} 2023-06-07T16:50:18.682879+08:00 [debug] client_id: <<"{46c2b4e6-7a02-4093-b9ba-c66bfd393abd}">>, file: emqx_cm.erl, line: 566, mfa: {emqx_cm,clean_down,1}, msg: emqx_cm_clean_down, pid: <0.1804.0>
> 
> 是这行吗

No, not here, although there is a termination caused by OOM.
For each `CONNECT` there would be a debug message which contains a `CON` world, and before each `DISCONNECT`  there would be some words like `closed`, `timeout`, and `take`, you can use these words as a filter.

**Comment by ypyaaa** [comment]
> > > > > Hi, first, version 4.3.18 is no longer maintained,
> > > > 
> > > > 
> > > > ![image](https://user-images.githubusercontent.com/19565638/243976921-5a1d9641-1d5b-4f7b-8a1c-9c92024cc8fd.png)
> > > > 我们将emqx版本提到了 4.4.18 打开了debug日志 发现这个报错
> > > 
> > > 
> > > This is just information about the OOM check which is harmless, please paste your log file here if possible and make sure it contains connection logs.
> > 
> > 
> > 2023-06-07T16:50:18.681113+08:00 [debug] {6a858b02-e43f-4249-8b14-6b031abf8bc6}@172.18.7.2:58660 [Mnesia] ACL ignored, Topic: <<"089/001/0002/scu_data_collection/30/a1_loop1_current">>, Action: publish for Client: #{anonymous => false,auth_result => success,clientid => <<"{6a858b02-e43f-4249-8b14-6b031abf8bc6}">>,is_bridge => false,is_superuser => false,mountpoint => undefined,peerhost => {172,18,7,2},protocol => mqtt,sockport => 1883,username => <<"zzmj_mqtt_default_user">>,zone => external} 2023-06-07T16:50:18.681336+08:00 [info] {6a858b02-e43f-4249-8b14-6b031abf8bc6}@172.18.7.2:58660 PUBLISH to 089/001/0002/scu_data_collection/30/a1_loop1_current: <<"{"value":"0","updateCount":1225,"state":0,"timestamp":1686127767291}\n">> 2023-06-07T16:50:18.681410+08:00 [debug] {46c2b4e6-7a02-4093-b9ba-c66bfd393abd}@172.18.6.151:51147 file: emqx_connection.erl, line: 813, mfa: {emqx_connection,check_oom,1}, msg: check_oom, pid: <0.2294.0>, policy: #{max_heap_size => 67108864,message_queue_len => 10000} 2023-06-07T16:50:18.681507+08:00 [debug] {6a858b02-e43f-4249-8b14-6b031abf8bc6}@172.18.7.2:58660 [MQTT] RECV <<97,116,97,95,99,111,108,108,101,99,116,105,111,110,47,51,48,47,97,49,95,108,111,111,112,50,95,118,111,108,116,123,34,118,97,108,117,101,34,58,34,48,46,48,34,44,34,117,112,100,97,116,101,67,111,117,110,116,34,58,49,50,50,53,44,34,115,116,97,116,101,34,58,48,44,34,116,105,109,101,115,116,97,109,112,34,58,49,54,56,54,49,50,55,55,54,55,50,57,...>> 2023-06-07T16:50:18.681670+08:00 [debug] {6a858b02-e43f-4249-8b14-6b031abf8bc6}@172.18.7.2:58660 [MQTT] RECV PUBLISH(Q0, R1, D0, Topic=089/001/0002/scu_data_collection/30/a1_loop2_volt, PacketId=undefined, Payload=<<"{"value":"0.0","updateCount":1225,"state":0,"timestamp":1686127767291}\n">>) 2023-06-07T16:50:18.681910+08:00 [debug] 3c304215-469d-c6b1-a211-90c58e01b703@172.18.7.2:58196 [MQTT] SEND PUBLISH(Q0, R0, D0, Topic=089/001/0002/scu/98/errors, PacketId=undefined, Payload=<<"{"value":"1C1D","updateCount":1216,"state":0,"timestamp":1686127767291}\n">>) 2023-06-07T16:50:18.682053+08:00 [debug] 3c304215-469d-c6b1-a211-90c58e01b703@172.18.7.2:58196 [MQTT] SEND PUBLISH(Q0, R0, D0, Topic=089/001/0002/scu_power/98/errors, PacketId=undefined, Payload=<<"{"value":"","updateCount":1216,"state":0,"timestamp":1686127767291}\n">>) 2023-06-07T16:50:18.682166+08:00 [debug] 3c304215-469d-c6b1-a211-90c58e01b703@172.18.7.2:58196 [MQTT] SEND PUBLISH(Q0, R0, D0, Topic=089/001/0002/scu_coupler/98/errors, PacketId=undefined, Payload=<<"{"value":"","updateCount":1217,"state":0,"timestamp":1686127767291}\n">>) 2023-06-07T16:50:18.682320+08:00 [debug] 3c304215-469d-c6b1-a211-90c58e01b703@172.18.7.2:58196 [MQTT] SEND PUBLISH(Q0, R0, D0, Topic=089/001/0002/scu_coupler_switch/98/errors, PacketId=undefined, Payload=<<"{"value":"","updateCount":1216,"state":0,"timestamp":1686127767291}\n">>) 2023-06-07T16:50:18.682444+08:00 [debug] 3c304215-469d-c6b1-a211-90c58e01b703@172.18.7.2:58196 [MQTT] SEND PUBLISH(Q0, R0, D0, Topic=089/001/0002/scu_data_collection/30/a1_loop1_volt, PacketId=undefined, Payload=<<"{"value":"0.0","updateCount":1225,"state":0,"timestamp":1686127767291}\n">>) 2023-06-07T16:50:18.682544+08:00 [debug] 3c304215-469d-c6b1-a211-90c58e01b703@172.18.7.2:58196 [MQTT] SEND PUBLISH(Q0, R0, D0, Topic=089/001/0002/scu_data_collection/30/a1_loop1_current, PacketId=undefined, Payload=<<"{"value":"0","updateCount":1225,"state":0,"timestamp":1686127767291}\n">>) 2023-06-07T16:50:18.682580+08:00 [info] {46c2b4e6-7a02-4093-b9ba-c66bfd393abd}@172.18.6.151:51147 file: emqx_connection.erl, line: 544, mfa: {emqx_connection,terminate,2}, msg: terminate, pid: <0.2294.0>, reason: {shutdown,message_queue_too_long} 2023-06-07T16:50:18.682879+08:00 [debug] client_id: <<"{46c2b4e6-7a02-4093-b9ba-c66bfd393abd}">>, file: emqx_cm.erl, line: 566, mfa: {emqx_cm,clean_down,1}, msg: emqx_cm_clean_down, pid: <0.1804.0>
> > 是这行吗
> 
> No, not here, although there is a termination caused by OOM. For each `CONNECT` there would be a debug message which contains a `CON` world, and before each `DISCONNECT` there would be some words like `closed`, `timeout`, and `take`, you can use these words as a filter.

我搜了一下 没有找到和此相关的日志 但是 我在emqx,conf里面扩大了 msg_queue队列从1000 到十万就不会再断了

**Comment by zmstone** [comment]
The last reply confirms that the reason of disconnect was OOM protection of process heap.
