### ISSUE TITLE
5.0 /authentication/{id} is broken?

### ISSUE THREAD

**Issue by jasonnmy** [emqx/emqx#10963]
### What happened?

I used why return this 
{
  "code": "INVALID_PARAMETER",
  "message": "Reason unsupported_operation"
} 
what am i missing
![Snipaste_2023-06-07_20-37-51](https://github.com/emqx/emqx/assets/10269349/437cccff-86c0-4f35-a975-fbb70f367dd4)
![image](https://github.com/emqx/emqx/assets/10269349/656f83f1-98fd-4261-b7c4-e227eab6627f)

### What did you expect to happen?

can be used

### How can we reproduce it (as minimally and precisely as possible)?

/api-docs/index.html

### Anything else we need to know?

The docker version I use

### EMQX version

<details>

```console
$ ./bin/emqx_ctl broker
sysdescr  : EMQX
version   : 5.0.26
```

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
#10075 ETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
$ uname -a
Linux 7c0a38b1cf7f 5.10.60 #1 SMP Fri Apr 21 06:19:48 CST 2023 x86_64 GNU/Linux

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Log files

<details>

</details>

**Comment by zmstone** [comment]
Hi @jasonnmy 

Only `built_in_databse` supports user management at the moment.
We'll add such information to the returned error message in the API.

**Comment by zmstone** [comment]
Just to clarify, the accepted enhancement is to add more detailed message to explain that the auth backend does not support user/device management. But not to implement user/device auth data management for MySQL etc.
