### ISSUE TITLE
Emqx not terminate the connection after default 15 min CRL check after the cert is revoked.

### ISSUE THREAD

**Issue by sc-sityad** [emqx/emqx#10992]
### Discussed in https://github.com/emqx/emqx/discussions/10956

<div type='discussions-op-text'>

<sup>Originally posted by **sc-sityad** June  7, 2023</sup>
- I am using emqx 5.026 version in which there is only option to enabel the crl check which checks the CA authority certificate if it has the CRL list and checks if it revoked or not. 
- But I am using small step for certificate generation (CA) which does not support the CRLs and OCSP stapling. 
- I wanted to manage the CRLs with mongodb(with ssl) and integrate with emqx, How to do that can anyone guide me with detailed explanation?</div>

**Comment by zmstone** [comment]
Hi @sc-sityad 

Currently, certificate revocation check is only performed during TLS handshake.
EMQX does not close already established connections.
