### ISSUE TITLE
Speed Issue 

### ISSUE THREAD

**Issue by fabltd** [emqx/emqx#10991]
### What happened?

I have an ESP32. I have tried different libiarys. All experience the same issue. Overtime the connection becomes very slow. 

I can send a message to the broker and in 60 seconds the device will respond, sometimes the device does not respond. 

Publishing from the device to EMQX is instant. 

This happens intermittatly some times its fast but most of the time is slow. Often the command is lost is never recived by the ESP32. 

Whats the best way to debug?

### What did you expect to happen?

Consitant connection results

### EMQX version

5.0.25

### OS version

Google GKE with K8s operator

### Log files

<details>

</details>

**Comment by fabltd** [comment]
Update: This appears to be an issue with deployment on GKE. There the loadbalancer is some how effecting the MQTT traffic. Any suggestions?

**Comment by qzhuyan** [comment]
check the TCP keepalives or enforce keep alive on MQTT layer using short timer like 10s.

**Comment by fabltd** [comment]
I have the option to set these both:

```
// MQTT_KEEPALIVE : keepAlive interval in Seconds. Override with setKeepAlive()
#ifndef MQTT_KEEPALIVE
#define MQTT_KEEPALIVE 5
#endif

// MQTT_SOCKET_TIMEOUT: socket timeout interval in Seconds. Override with setSocketTimeout()
#ifndef MQTT_SOCKET_TIMEOUT
#define MQTT_SOCKET_TIMEOUT 5
#endif
```

I am still seeing lagging. There are less disconnects but still occouring we lost packets 114-124:

```
Message arrived [devices/AC67B2532214/testing] hello world #112
Message arrived [devices/AC67B2532214/testing] hello world #113
Attempting MQTT connection...connected
Message arrived [devices/AC67B2532214/testing] hello world #124
Message arrived [devices/AC67B2532214/testing] hello world #125
Message arrived [devices/AC67B2532214/testing] hello world #126
Message arrived [devices/AC67B2532214/testing] hello world #127
Message arrived [devices/AC67B2532214/testing] hello world #128
Message arrived [devices/AC67B2532214/testing] hello world #129
Message arrived [devices/AC67B2532214/testing] hello world #130
Message arrived [devices/AC67B2532214/testing] hello world #131
Message arrived [devices/AC67B2532214/testing] hello world #132
Message arrived [devices/AC67B2532214/testing] hello world #133
Message arrived [devices/AC67B2532214/testing] hello world #134
Message arrived [devices/AC67B2532214/testing] hello world #135
Message arrived [devices/AC67B2532214/testing] hello world #136
Message arrived [devices/AC67B2532214/testing] hello world #137
Message arrived [devices/AC67B2532214/testing] hello world #138
Attempting MQTT connection...connected
Message arrived [devices/AC67B2532214/testing] hello world #149

```

**Comment by zmstone** [comment]
@fabltd 
Maybe you can use the "trace" feature from the EMQX dashboard to inspect all connection activities including heartbeats and disconnect reasons etc.

**Comment by qzhuyan** [comment]
if you want to ensure delivery, use QoS1 or Qos2, an unconfirmed message will be resent after reconnect.
