### ISSUE TITLE
Did v5.0.26 release get re-tagged?

### ISSUE THREAD

**Issue by chenrui333** [emqx/emqx#11011]
While trying to upgrade [erlang](https://github.com/Homebrew/homebrew-core/pull/133351), I found [emqx 5.0.26 tarball file checksum](https://github.com/Homebrew/homebrew-core/pull/133355) got changed. Raise this issue to double check on the checksum issue. Thanks!

(also relates to this PR, https://github.com/Homebrew/homebrew-core/pull/132270)

**Comment by id** [comment]
@chenrui333 yes, sorry about that.

We have found that the Dashboard version was not updated correctly in the build configuration after we tagged the release. Created this check to prevent this from happening in the future https://github.com/emqx/emqx/pull/10916

**Comment by carlocab** [comment]
Thanks for the clarification, @id.

It would be helpful for your users downstream if you avoid replacing tags after publishing then. The Git docs even have some [rather strong words](https://git-scm.com/docs/git-tag#_on_re_tagging) about doing this. Tagging 5.0.26.1 was probably more suitable for what you wanted to do here.

**Comment by id** [comment]
@carlocab totally agree, we will do our best to avoid retagging in the future.

**Comment by chenrui333** [comment]
Thanks @id!! Closing the issue.
