### ISSUE TITLE
emqx.conf replaced in upgrade

### ISSUE THREAD

**Issue by FernandoGarcia** [emqx/emqx#11066]
### What happened?

Hi!

I have upgraded from  `5.0.25` to `5.0.26` and lose all my configuration in `emqx.conf`.

It's an expected behaviour?

Best regards.

### What did you expect to happen?

Keep my file while upgrading.

### EMQX version

<details>

```console
$ ./bin/emqx_ctl broker
# paste output here
```

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Log files

<details>

</details>

**Comment by id** [comment]
Hi @FernandoGarcia. Could you give us more details?
* How exactly was `5.0.25` installed - via OS package, docker, k8s?
* What OS or docker platform did you use?
* How did you do the upgrade?

**Comment by zmstone** [comment]
prior to v5.0.26, the default listeners are put in emqx.conf,
in v5.0.26, listener configs are moved from emqx.conf to implicit default values in the config schema, but the config from earlier versions are compatible.

if you compare the default config files, it may appear to be 'deleted',
however emqx.conf to EMQX (as a program) is read-only, it does not mutate this file at runtime.

if you have changed emqx.conf before, but got replaced by the new config, it likely happened during the package extraction or installation step.

**Comment by FernandoGarcia** [comment]
> Hi @FernandoGarcia. Could you give us more details?
> 
>     * How exactly was `5.0.25` installed - via OS package, docker, k8s?
> 
>     * What OS or docker platform did you use?
> 
>     * How did you do the upgrade?

Hi!

It  was an unattended upgrade together with OS packages.

I'm using Ubuntu 22.04 and I'm not using any container.

Best regards.

**Comment by ieQu1** [comment]
Hello,
Sorry for late response. I will test package update on Ubuntu.

**Comment by ieQu1** [comment]
It looks like the behavior when updating deb package is correct. After installing 5.0.25, modifying `/etc/emqx/emqx.conf` and running `apt install emqx-5.0.26-ubuntu22.04-amd64.deb` I get the following prompt:

``` 
# sudo apt install emqx-5.0.26-ubuntu22.04-amd64.deb 
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Note, selecting 'emqx' instead of '/home/me/Downloads/emqx-5.0.26-ubuntu22.04-amd64.deb'
The following packages will be upgraded:
  emqx
1 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Need to get 0 B/39,8 MB of archives.
After this operation, 266 kB of additional disk space will be used.
Get:1 /home/me/Downloads/emqx-5.0.26-ubuntu22.04-amd64.deb emqx amd64 5.0.26 [39,8 MB]
(Reading database ... 708446 files and directories currently installed.)
Preparing to unpack .../emqx-5.0.26-ubuntu22.04-amd64.deb ...
Unpacking emqx (5.0.26) over (5.0.25) ...
Setting up emqx (5.0.26) ...

Configuration file '/etc/emqx/emqx.conf'
 ==> Modified (by you or by a script) since installation.
 ==> Package distributor has shipped an updated version.
   What would you like to do about it ?  Your options are:
    Y or I  : install the package maintainer's version
    N or O  : keep your currently-installed version
      D     : show the differences between the versions
      Z     : start a shell to examine the situation
 The default action is to keep your current version.
*** emqx.conf (Y/I/N/O/D/Z) [default=N] ?
```

It seems like unattended-upgrade defaults to Y, which leads to the problem. This behavior is configurable, it seems: https://serverfault.com/questions/1047559/unattended-upgrades-conffile-prompt

So I don't think there's anything wrong with the deb package.

**Comment by ieQu1** [comment]
Yes, on a second thought I realized that usually deb packages rarely ask this for the files in /etc/, so something is wrong with the file metadata.
