### ISSUE TITLE
EMQX has experienced noticeable message latency

### ISSUE THREAD

**Issue by ypyaaa** [emqx/emqx#11061]
### What happened?

EMQX has experienced noticeable message latency on MQTT messages:

Received a message at 20:41:55 seconds:
![image](https://github.com/emqx/emqx/assets/19565638/5acf5ee2-7803-4269-8396-34744881b214)

Only at 20:42:25 seconds did the message get sent out:
![image](https://github.com/emqx/emqx/assets/19565638/e2b3484a-b78c-46a5-944d-6268a37bc5fc)

After this message, the window was found to be blocked.
![image](https://github.com/emqx/emqx/assets/19565638/9687bb56-0c42-4448-a105-343fe6d0943a)

### EMQX version

4.4.18

### OS version

ubuntu 18.04 
docker 22.10.7

### Log files

![image](https://github.com/emqx/emqx/assets/19565638/2e558ed3-dba3-4a4c-8d7d-698419da80dd)

It received the message at minutes 42.

**Comment by zmstone** [comment]
It took 30 seconds after the message to reach debug log.
It could be that the process for this client is blocked doing something takes time for previous messages.
e.g. maybe ACL check.

Could you share the configs ?

**Comment by ypyaaa** [comment]
> It took 30 seconds for the message to reach debug log. It could be that the process for this client is blocked doing something takes time for previous messages. e.g. maybe ACL check.
> 
> Could you share the configs ?

配置很多 是要全部贴上来吗

**Comment by terry-xiaoyu** [comment]
1. start the obsever_cli:
```
emqx eval 'observer_cli:start()'
```
2. check if there are any processes has a long message queue by typing `mq` and then type Enter.
