### ISSUE TITLE
Error building plugin with EMQX v5.1.0

### ISSUE THREAD

**Issue by jcosentino11** [emqx/emqx#11119]
### What happened?

Hello, I'm unable to build a custom plugin when using EMQX v5.1.0 as a dependency.  

The plugin's rebar.config
```
{deps, [{emqx, {git_subdir, "https://github.com/emqx/emqx.git", {tag, "v5.1.0"}, "apps/emqx"}}]}.

{relx, [{release, {gg, "1.0.0"},
  [gg
  ]}
  , {dev_mode, false}
  , {include_erts, false}
]}.

{edoc_opts, [{preprocess, true}]}.
{erl_opts, [warn_unused_vars,
  warn_shadow_vars,
  %% warn_unused_import,
  warn_obsolete_guard,
  debug_info,
  {parse_transform}]}.

{xref_checks, [undefined_function_calls, undefined_functions,
  locals_not_used, deprecated_function_calls,
  warnings_as_errors, deprecated_functions]}.

{cover_enabled, true}.
{cover_opts, [verbose]}.
{cover_export_enabled, true}.

{project_plugins, [erlfmt]}.
```

Error message:
```
 ===> Fetching emqx_utils (from {path,"../emqx_utils"})
===> Failed to fetch and copy dep: {path,"../emqx_utils"}
```

### What did you expect to happen?

Plugin builds on linux

### How can we reproduce it (as minimally and precisely as possible)?

Build a plugin with `{deps, [{emqx, {git_subdir, "https://github.com/emqx/emqx.git", {tag, "v5.1.0"}, "apps/emqx"}}]}.` in rebar.config

### EMQX version

5.1.0

<details>

```console
$ ./bin/emqx_ctl broker
# paste output here
```

</details>

### OS version

<details>

ubuntu

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Log files

<details>

</details>

**Comment by thalesmg** [comment]
@jcosentino11 you might want to have a look at this template:

https://github.com/emqx/emqx-plugin-template

**Comment by jcosentino11** [comment]
Ah I missed the template updates since the last time I've looked at it, that should do it :)

**Comment by jcosentino11** [comment]
Yep builds just fine now, apologies for the false alarm
