### ISSUE TITLE
EMQX5.1启动出错

### ISSUE THREAD

**Issue by 1052915220** [emqx/emqx#11128]
### What happened?

![image](https://github.com/emqx/emqx/assets/110186678/00a390ee-fa5b-43a2-ab76-5b5c5a8475c3)

### What did you expect to happen?

正常启动

### Anything else we need to know?

5.0的就可以启动，5.1的尝试过两台Windows都无法启动，一台win10，一台win11

### EMQX version

<details>

EMQX ：5.1.0

</details>

### OS version

<details>
# On Windows:11，10

</details>

### Log files

<details>

</details>

**Comment by ieQu1** [comment]
Translation (via tesseract and deepl):
```
escript.exe is not an internal or external command, nor is it a runnable program
or batch processing documents.
```
After inspecting the windows package it looks indeed that erts version included in the package is different from what the release expects. Looks like a CI/packaging error.

**Comment by zmstone** [comment]
By the look of the file path, it looks like a amazon linux package (`amzn2`).‘
@1052915220  are you sure you are running the windows package ?

**Comment by 1052915220** [comment]
> By the look of the file path, it looks like a amazon linux package (`amzn2`).‘ @1052915220 are you sure you are running the windows package ?

是的，在emqx官网下载的Windows版本。
![image](https://github.com/emqx/emqx/assets/110186678/5313b8a4-0099-4d72-b4fb-d28d6d7c2a04)

**Comment by 1052915220** [comment]
> Translation (via tesseract and deepl):
> 
> ```
> escript.exe is not an internal or external command, nor is it a runnable program
> or batch processing documents.
> ```
> 
> This error looks as if there was a mismatch between ERTS (erlang runtime) version specified in the EMQX release and the one included in the package. However, after briefly looking at the contents of the zip archive, everything matches. Did you unpack the zip into a directory where a previous version of EMQX was installed? Could you try to unpack it into a clean directory and report the result? (Currently I don't have a windows machine at hand)

我的目录结构并没有覆盖旧版的emqx，如图
![image](https://github.com/emqx/emqx/assets/110186678/ce7691ef-3306-4fa7-8008-5b9fff62b3d8)
这样有问题吗？
并且我在启动新版本时已经停止了旧版本运行。

**Comment by ieQu1** [comment]
I think this reply pinpoints the issue: https://github.com/emqx/emqx/issues/11128#issuecomment-1603240147

It looks like you downloaded a **Linux** package for EMQX 5.1.0 which doesn't include windows executables. Correct package is this this: https://github.com/emqx/emqx/releases/download/v5.1.0/emqx-5.1.0-windows-amd64.zip
