### ISSUE TITLE
是否支持 用户认证的缓存配置?

### ISSUE THREAD

**Issue by joyanhui** [emqx/emqx#11155]
### What would you like to be added or enhanced?

访问控制的 权限配置支持缓存，用户认证能否支持缓存？

### Why is this needed?

降低后端数据库负担

**Comment by savonarola** [comment]
Hi! We are not going to implement this feature in v5 soon.

Currently, one of the ways to reduce load is e.g. to use JWT authentication which does not involve querying any internal or external storage.

**Comment by thousmile** [comment]
@joyanhui Redis 替换掉 数据库。

**Comment by joyanhui** [comment]
> Hi! We are not going to implement this feature in v5 soon.
> 
> Currently, one of the ways to reduce load is e.g. to use JWT authentication which does not involve querying any internal or external storage.

Thanks to savonarola, I have been gradually replacing to jwt

**Comment by joyanhui** [comment]
> @joyanhui Redis 替换掉 数据库。

我现在就是因为redis 负载太高了，
