### ISSUE TITLE
Not authorized if subscribe to a topic with a plus (+) sign 

### ISSUE THREAD

**Issue by jitbasemartin** [emqx/emqx#11154]
### What happened?

I have a case where a message is published to `a/a1/b/b1` and I subscribe to `a/+/b/+` with a JWT that contains an `acl` claim. The acl is `"sub": [ "a/a1/#" ]`

But I can see the error message:
```
2023-06-27T21:02:17.039915+00:00 [warning] msg: authorization_permission_denied, mfa: emqx_authz:authorize_non_superuser/5, line: 357, peername: 10.2.4.10:49262, clientid: my-client-id, topic: a/+/b/+, ipaddr: {10,2,4,10}, source: client_info, username: <<"my-username">>
```

On mosquitto this case works. My goal is to have 2 users. Each user have one namespace, `a/a1/#` for user 1 and `a/a2/#` for user 2. But in my application I would like to subscribe with user 1 or user 2 to `a/#` 
The client with user 1, receive only message on `a/a1/#` and user 2 only messages on `a/a2/#`

### What did you expect to happen?

Receive messages published on `a/a1/b/b1` but not `a/a2/b/b1` with no warning

### EMQX version

<details>

```console
sysdescr  : EMQX
version   : 5.0.24
datetime  : 2023-06-27T21:55:52.858124278+00:00
uptime    : 61 days, 23 hours, 33 minutes, 29 seconds
```

</details>

### OS version

<details>

```console
PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```

</details>

### Log files

<details>

</details>

**Comment by lafirest** [comment]
@jitbasemartin 
I think this is expected behaviour, you know the scope of `+` is larger than `a1`, we must respect your ACL setting.
If I understood right, what is wanted is the `a/${clientid}/#`
We support a few placeholders to represent runtime information, like the clientid, username and so on

**Comment by jitbasemartin** [comment]
Thanks 
In my case, one user can have multiple "namespaces"
The scenario of my issue works with Mosquitto

# Working scenario with Mosquitto:

## mosquitto.conf

```conf
listener 1883

allow_anonymous false
password_file /mosquitto/config/mosquitto-users.conf
acl_file /mosquitto/config/mosquitto-acls.conf
```

## mosquitto-users.conf

```conf
user1:$7$101$qonb6AK8847cfL0F$LouGJrIpjn+mwW1cJKQ6VrMRDpAO+ER5QnTgtU1IcYfikSyZObfomD1Rdu4JtXw1Q36dDZXi31+kkUwqNU0A1g==
user2:$7$101$UYDgBbq8wWYfQjrC$RcD9KuCCCTWpDuhQu0Oe19dHGTdDlB0RNTAEdvTR2nzjk17KxUn5X26qpcvAlBg4KLQQnF0dzHg6TIbefJvuWg==
user3:$7$101$cbv9t50DEV6dl6Bz$7gSwbNHH0Xw1ZV9JDHVjYvell0jMvpTKuplIEKJ1Xid9AnvqMe5L80T5FYA4BvHECYoDmegmE408XXouIjjZYA==
```

## mosquitto-acls.conf

```conf
# This affects access control for clients with no username.
topic deny #

# This only affects clients with username
user user1
topic write a/#

user user2
topic read a/a2/#

user user3
topic read a/a3/#
topic read a/a4/#


# This affects all clients.
pattern deny $SYS/broker/connection/%c/state
```

## Docker

```sh
docker run -v `pwd`/mosquitto.conf:/mosquitto/config/mosquitto.conf -v `pwd`/mosquitto-users.conf:/mosquitto/config/mosquitto-users.conf -v `pwd`/mosquitto-acls.conf:/mosquitto/config/mosquitto-acls.conf -p 1883:1883 eclipse-mosquitto:latest
```

## MQTT CLI

```sh
npm install mqtt -g
```

### Publisher user 1

```sh
DATE=`date`; for i in $(seq 1 4); do echo $i; USER=user1; mqtt pub -h 127.0.0.1 -p 1883 -C mqtt -i $USER -u $USER -P $USER -t "a/a$i/date" -m "{\"date\": \"$DATE\", \"idx\": $i }"; done
```

### Subscriber user 2 (allowed only on `a2`)

```sh
USER=user2; mqtt sub -v -h 127.0.0.1 -p 1883 -C mqtt -i $USER -u $USER -P $USER -t "a/+/date"
```

### Subscriber user 3 (allowed only on `a3` and `a4`)

```sh
USER=user3; mqtt sub -v -h 127.0.0.1 -p 1883 -C mqtt -i $USER -u $USER -P $USER -t "a/+/date"
```

# Results

As expected, user 2 receive only message on `a2` and user 3 receive only messages on `a3` and `a4`

### Publisher user 1

![image](https://github.com/emqx/emqx/assets/23301195/36f57f7a-fb4b-46a8-9d54-4065b3b98c26)

### Subscriber user 2

![image](https://github.com/emqx/emqx/assets/23301195/7e53fec7-08ac-42fc-8019-3356656be3bb)

### Subscriber user 3

![image](https://github.com/emqx/emqx/assets/23301195/5683c2ea-59e7-4afd-a55d-b3ad02f819cd)


**Is it possible to have the same behavior with EMQX ?**

**Comment by lafirest** [comment]
@jitbasemartin 
Thanks for your so detailed information, I think I have got your idea.
You used a precise topic as the ACL rule, and use a wildcard topic to 
subscribe, and only the message whose topic is equal to the precise topic can be delivered to this client.

Of course, in EMQX this is possible, but the way is different, or we can say is just the opposite.
For this case, In EMQX, 
1 The  ACL rule should be `a/${username}/date`
2 The subscribe should be `a/username of this client/date`, 
For convenience, step 2 can be omitted by the  feature `auto subscribe` which could auto-subscribe to some topics when a client connected

IMO, the behaviour of mosquitto is good but with a little confusion.

What do you think about this question, @savonarola

**Comment by savonarola** [comment]
EMQX denies subscription if the topic filter does not strictly fits the allowed rules.

There is no semantics like: "subscribe me to any allowed topics from this general pattern".
