### ISSUE TITLE
Questions about the rebalance feature in emqx 5

### ISSUE THREAD

**Issue by cwy1996** [emqx/emqx#11170]
### What happened?

Cannot found the rebalance options in the output of `./bin/emqx_ctl` command.

How can I do the node eviction?

### EMQX version

5+

### OS version

ubuntu 18.04

### Log files

<details>

</details>

**Comment by savonarola** [comment]
Hi! 
Do you use the latest enterprise version for trying rebalancing?

**Comment by cwy1996** [comment]
我尝试更新latest，现在5.1.1版本，但命令中仍没有文档中./bin/emqx_ctl后所体现的rebalance
![image](https://github.com/emqx/emqx/assets/76695859/6c8db6eb-a126-472d-8016-96f70ad04e24)

是否我所用的镜像与您所指的不一致
![image](https://github.com/emqx/emqx/assets/76695859/dfd35026-951f-4a5f-ae21-2dad8f25875f)

**Comment by id** [comment]
@cwy1996 node rebalance is an enterprise-only feature. The image you are using is community edition.
If you would like to evaluate enterprise edition, please try `emqx/emqx-enterprise:5.1.1` instead: https://hub.docker.com/r/emqx/emqx-enterprise
