### ISSUE TITLE
Auto subscribe problems

### ISSUE THREAD

**Issue by hjy30312** [emqx/emqx#11197]
### What happened?

I added auto subscribes in `emq.conf`

```
auto_subscribe {
  topics = [
    {
      topic = "${clientid}/w "
      qos   = 2
    }
  ]
}
```

### What did you expect to happen?

But, when I manually delete the subscription and then re-subscribe manually, the device can receive messages when data is published to the subscribed topic.

I'm not sure if this is a bug in version 5.0.11.

### EMQX version

[5.0.11](https://www.emqx.com/zh/changelogs/broker/5.0.11)

### OS version

linux   centos7.6

### Log files

<details>

</details>

**Comment by hjy30312** [comment]
使用日志追踪功能， 设备确实当时没有收到数据。   有可能是什么问题呢？

**Comment by qzhuyan** [comment]
We cannot help without logs. 

If the publisher and the subscriber are from the same client, check if the subscription was done with nl (no_local = true).
