### ISSUE TITLE
information on who published

### ISSUE THREAD

**Issue by pavankumarkatakam** [emqx/emqx#1119]
#### Environment

- OS: Ubuntu 16.04
- Erlang/OTP:  
  [{release,"Erlang/OTP","19","8.3",
[{kernel,"5.2","/usr/lib/erlang/lib/kernel-5.2"},
{stdlib,"3.3","/usr/lib/erlang/lib/stdlib-3.3"},
{sasl,"3.0.3","/usr/lib/erlang/lib/sasl-3.0.3"}],
permanent}]
- EMQ: latest

#### Description
Hi, I have setup the emqttd using the .deb file successfully setup emq_auth_mysql. If one user published message to topic how to get the who published (clientid or username) info when subscribed to that topic.
This infomation is usefull when creating the chat like apps.

*A description of the issue*
This is not a issue rather a question.

**Comment by pavankumarkatakam** [comment]
Is my question wrong?

**Comment by pavankumarkatakam** [comment]
is this what im looking for `mqtt.pubsub.by_clientid = true`.

**Comment by pavankumarkatakam** [comment]
Below is the data received when I subscribed to `presence` topic.
```
 Packet {
     cmd: 'publish',
     retain: false,
     qos: 0,
     dup: false,
     length: 20,
     topic: 'presence',
     payload: <Buffer 48 65 6c 6c 6f 20 6d 71 74 74> } }
```

There is no information abou the who(clientID or username) published that message

**Comment by emqplus** [comment]
@pavankumarkatakam Suggest to add the 'username' or 'clientid' in the payload if you are developing an IM application. For example:
```
{
"from": "john",
"to": "tom",
"body": "Hello"
}
```

**Comment by pavankumarkatakam** [comment]
I came to know that MQTT Spec doesn't have the **from** details, either we need to keep from details in the payload or create topic such that it has the **from** details

Im going with adding the from details to payload
what is the better way to put **from** details in the payload
1. at client side
2. at broker side

it is highly recommended and secure to keep at broker side if possible.

**Comment by pavankumarkatakam** [comment]
@emqplus, can you please guide me how to achieve this using the custom plugins. I think I need to hook into `message.publish` and change the payload right?
