### ISSUE TITLE
Suggestion: add clients from admin panel

### ISSUE THREAD

**Issue by Suko** [emqx/emqx#1120]
Hi, It would be nice if we could add/remove clients with auth through the admin panel.

**Comment by emqplus** [comment]
@Suko You can use the Redis, MySQL or PostgreSQL authentication plugins.

**Comment by Suko** [comment]
As I understand you need your own application to do clients management? Maybe I missed something but what I thought is that it is not important which plugin you are using you should be able to add/remove clients through the admin tool without an additional application it would really speed up the process at the start.

**Comment by emqplus** [comment]
@Suko Plan to support this feature in 2.3 release. Thanks for you suggestions.

**Comment by Gilbert-Wong** [comment]
EMQ X already supports to manage clients via emqx-dashboard panel. Please try latest emqx edition.
