### ISSUE TITLE
broker not responding to 'stop' command - using pkill beam to close the broker

### ISSUE THREAD

**Issue by syberkitten** [emqx/emqx#1121]
#### Environment
Mac OSX El-Capitan / Ubuntu 14.04LTS

after running the broker via: `./bin/emqttd start`
the command: `./bin/emqttd stop`

Always returns:
`Node 'emqlocal@mycomputername' not responding to pings.`

The behavior happens like stated on two machines
my local development and the production Ubuntu server running on Amazon EC.

I have to kill the beam manually every time before I can start
the broker again, via: `pkill beam`

**Comment by turtleDeng** [comment]
@syberkitten  Please check your ~/.erlang.cookie file exists,If it exists, delete it

**Comment by syberkitten** [comment]
I did, but it did not change the behavior.

**Comment by emqplus** [comment]
@syberkitten 

1. The node name should be Name@Host, where Host is IP address or the fully qualified host name.
2. Configure the `/etc/hosts` file if FQN is used, for example: `127.0.0.1   emq.mydomain`

**Comment by gurtyo** [comment]
I run emqtt first time on my mac os x 10.13.It failed to start and throwed some erlang error.After I saw the advice to delete `~/.erlang.cookie`,It works.Confusing
