### ISSUE TITLE
emqx 5.1.1 send messages failed via HTTP Bridge

### ISSUE THREAD

**Issue by wjy000** [emqx/emqx#11232]
### What happened?

After testing, it was found that sending requests to the API using a pure IP address resulted in failure, with eventual timeouts and discards. This issue also affected the official API service demonstrated in the Python examples, and it could be replicated even when using '127.0.0.1' as the address. However, when using the API address with a domain name, everything worked perfectly fine.

### What did you expect to happen?

HTTP Bridge should failed

### How can we reproduce it (as minimally and precisely as possible)?

The service demonstrated in the official documentation using a Python example can also be reproduced with 127.0.0.1.

### EMQX version

<details>

```console
$ ./bin/emqx_ctl broker
# paste output here
```

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Log files

<details>

</details>

**Comment by lafirest** [comment]
@wjy000
