### ISSUE TITLE
Debian 12 support

### ISSUE THREAD

**Issue by frenck** [emqx/emqx#11231]
### What would you like to be added or enhanced?

Debian 12 became released as stable on June the 10th 2023.

https://www.debian.org/News/2023/20230610

FR: Please add support / build packages for Debian 12 in the release process.

Thanks for considering.

../Frenck

### Why is this needed?

To keep up / remain compatible with the latest available version of one of the major Linux distributions out there. 🤷 

(Sorry, a little bit of captain obvious maybe, but I guess these should not be ignored for too long).

**Comment by id** [comment]
@frenck it's in my backlog along with Amazon Linux 2023. Planning to have it available by the next release v5.1.2.

**Comment by frenck** [comment]
Thanks for resolving this one @id 👍 

../Frenck
