### ISSUE TITLE
ExHook: can't reject client connection on the OnClientConnect hook

### ISSUE THREAD

**Issue by sekfung** [emqx/emqx#11267]
### What happened?

I want to write some code to reject connection by returning an error, like the code below, but it doesn't work,  as EMQX still allows illegal clients to connect.

BTW: EMQX does not have authentication enabled.

```golang
if in.Conninfo.ProtoName == "MQIsdp" && in.Conninfo.ProtoVer == "3" {
    return nil, status.Error(codes.Aborted, "MQTT 3.1 is not supported")
}
```

![image](https://github.com/emqx/emqx/assets/43331641/523c4c00-9c4f-497e-b7f3-7af1feceeda5)

### What did you expect to happen?

reject connection by returning an error

### EMQX version

<details>

```console
$ ./bin/emqx_ctl broker
# paste output here
```

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Log files

<details>

</details>

**Comment by HJianBo** [comment]
ExHook's `OnClientConnect` only serves as event notification and cannot reject some connections. If you need to reject a connection, please use the `OnClientAuthenticate` hook instead.

**Comment by sekfung** [comment]
Thx
