### ISSUE TITLE
emqx 4.0.0, the `$events/client_disconnected` is not triggered when client disconnected

### ISSUE THREAD

**Issue by ningtu** [emqx/emqx#11277]
### What happened?

我在规则里边创建了一个可以监听设备上下线的规则
![1689582161162](https://github.com/emqx/emqx/assets/54255570/d2de64d9-5160-4b53-b04e-734ef327ccc5)
，但是只有设备正常重启才能触发这个规则，设备断网断电触发不了

### What did you expect to happen?

期望只要设备断开连接就应该能触发该动作。

### EMQX version

4.0.0

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Log files

<details>

</details>

**Comment by lafirest** [comment]
@ningtu 
This version is out of maintenance, please consider upgrading.
And I think you should set a KEEPALIVE time for your client, so when it is shut down for some reason, EMQX can know this in the KEEPALIVE interval
