### ISSUE TITLE
Persistence issues with helm chart

### ISSUE THREAD

**Issue by daniele-arosio** [emqx/emqx#11287]
### What happened?

Hi,

 i'm using the 5.1.1 helm chart to deploy a EMQX broker with replicaCount:1 and persistence:true.

If the pod restarts, both the build-in dababase configuration for the authentication rules and the tracing configuration disappeared, as they are not properly set to be persistent.
File backend for authentication, data integration rules and and other system settings are instead properly persistent after the pod restart.

So i think it can be an issue with the persistece configuration in the helm templates.

### What did you expect to happen?

I expect that all the configurations, also the built-in database and the tracing configurations, will be restored after a pod restart.
I think persistence rules in the helm template need to be fixed.

### EMQX version

<details>
5.1.1
</details>

### Log files

<details>

</details>

**Comment by id** [comment]
@Rory-Z could you help on this one?

**Comment by Rory-Z** [comment]
Hi, @daniele-arosio Could you please confirm if the PVC has been successfully created?

I tried to use Helm to deploy EMQX 5.1.1 and used the following command:
```
helm install emqx emqx/emqx --set persistence.enabled=true
```

After waiting for EMQX to be ready, I created a built-in database configuration for the authentication rules through the EMQX Dashboard.
Then, the Pod was deleted using `kubectl scale --replicas=0 sts/emqx`, and the Pod was rebuilt using `kubectl scale --replicas=3 sts/emqx`. The rules I created were not lost.

**Comment by Rory-Z** [comment]
You're welcome, I will close this issue. If you have any questions, feel free to reopen it at any time.
