### ISSUE TITLE
Unable to update authn configuration during plugin load

### ISSUE THREAD

**Issue by jcosentino11** [emqx/emqx#11340]
### What happened?

Hello, I'm developing an emqx plugin which performs emqx configuration updates, among other things.  I noticed that if I try to execute `emqx_conf:update_conf` for the `authentication` key, within the plugin's `start` function, the update fails.

The issue was due to authn providers not being registered before the aforementioned update, because `emqx_authn` wasn't loaded at this point.  

I was able to workaround the issue by adding `emqx_authn` as an application dependency in `emqx_plugins.app.src`.

Wanted to report this issue, in case there may be similar situations; maybe it would make sense to load plugins after most other emqx apps have loaded

### What did you expect to happen?

See above

### EMQX version

5.1.1

### OS version

windows

### Log files

<details>

</details>

**Comment by id** [comment]
@jcosentino11 could you test it with 5.1.2?
In https://github.com/emqx/emqx/pull/11309 we fixed a few issues with application load and start order.
