### ISSUE TITLE
Clients cannot subscribe to MQTT event messages

### ISSUE THREAD

**Issue by mijjjj** [emqx/emqx#11341]
### What happened?

I am using version 5.0.20 and want to use the client to directly subscribe to MQTT events, but I configure in emqx.conf
![image](https://github.com/emqx/emqx/assets/37797122/6e472cd1-9b9d-4e41-8ba6-d364570cac9a)

Still can't take effect, client subscription $events/client_connected can't receive subscription request

### What did you expect to happen?

Unable to receive event request

### EMQX version

5.0.20

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Log files

<details>

</details>

**Comment by lafirest** [comment]
@mijjjj 
There seems to be some misunderstanding, the system topic is "$SYS" and not "$event" which is used in the rule engine.
https://www.emqx.io/docs/en/v5.0/advanced/system-topic.html
See the above link for details.
