### ISSUE TITLE
Closed soon after started

### ISSUE THREAD

**Issue by ian15937** [emqx/emqx#11345]
### What happened?

As tittle, it started without any strangy message. But it closed very soon without any reason.

### What did you expect to happen?

Normally start.

### EMQX version

<details>
5.1.2
</details>

### OS version

<details>

22621        Microsoft Windows 11 專業版  64 位元         10.0.22621

</details>

### Log files

[emqx.log](https://github.com/emqx/emqx/files/12160729/emqx.log)
[erl_crash.dump.txt](https://github.com/emqx/emqx/files/12160740/erl_crash.dump.txt)

**Comment by lafirest** [comment]
@ian15937 
Sorry, this may be a bug that only occurs in Windows, we will investigate and fix it, please wait a while.

**Comment by id** [comment]
Resolved in https://github.com/emqx/emqx/releases/tag/v5.1.3
