### ISSUE TITLE
Time deviation of device offline and offline activities

### ISSUE THREAD

**Issue by mijjjj** [emqx/emqx#11351]
### What happened?

I got the ts time stamp returned by the subscribed topic by subscribing to the on and off line activities of the system device, but the time stamp differs from the actual time by a few minutes. Sometimes it works normally after restarting the container, but it becomes inaccurate after running for a period of time. print container time is accurate

![image](https://github.com/emqx/emqx/assets/37797122/acab9ad5-0d1a-4ce0-b2a7-c5051cd26999)

### What did you expect to happen?

inaccurate time

### EMQX version

5.0.20

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Log files

<details>

</details>

**Comment by id** [comment]
@mijjjj thank you for the report, I created an issue in our internal bug tracking system to follow up.

For now, please try to uncomment the following line in `/etc/emqx/vm.args`, change it to `multi_time_warp`, and restart the node:

```
#+C no_time_warp
```
change to
```
+C multi_time_warp
```

**Comment by mijjjj** [comment]
It is normal in a short period of time after the current setting. What is the purpose of this setting? Has this bug been solved in the new version?

**Comment by id** [comment]
@mijjjj it's not a bug, it's documented and expected behavior of the Erlang VM. By default on this version the erlang vm (emqx node) will take system time offset when it started, and will then try to maintain the correct clock internally. Sometimes it's not very precise.

With `multi_time_warp` setting it will be syncing with system clock periodically.
