### ISSUE TITLE
Emqx not working with basic config on GKE Autopilot

### ISSUE THREAD

**Issue by FStefanni** [emqx/emqx#11364]
### What happened?

Hi,

I am using:
* EMQX 5.1.2 (OSS)
* EMQX operator for k8s
* Google Kubernetes autopilot (k8s version v.1.26.5-gke.1200)

I have just deployed the operator, and then copied and paste of the basic example of the doc:

<https://docs.emqx.com/en/emqx-operator/latest/tasks/configure-emqx-core-replicant.html#configure-emqx-cluster>

Unfortunately, it does not seems to work:

* There are 3 core instances (ok)
* There are no replicas (**KO**)
* There is no "listeners" service (but I was expecting one), just `emqx-headless` and `emqx-dashboard` services

If I run the following command (as reported in the doc), to verify the deployment:

```bash
kubectl get emqx emqx -o json | jq .status.emqxNodes
```

I get `null` as output, which is unexpected.
So I suppose there could be some sort of issues on GKE Autopilot? Or am I missing something?

Thank you,
regards

### What did you expect to happen?

To have a basic working config, and when running the command, to get an output similar to the one of the example doc.

### How can we reproduce it (as minimally and precisely as possible)?

* Create a GKE Autopilot instance
* Deploy the operator
* Deploy the doc example

### EMQX version

<details>

```console
$ ./bin/emqx_ctl broker
# paste output here
sysdescr  : EMQX
version   : 5.1.2
datetime  : 2023-07-28T10:13:39.384172226+00:00
uptime    : 13 minutes, 56 seconds
```

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Log files

<details>

</details>

**Comment by FStefanni** [comment]
Hi,

just a little update: since there is a newer version, I have tested it:
* operator: 2.2.0
* emqx container: 5.1.3

Now when I apply the EMQX configuration, it starts to create an infinite number of pods!
This is a huge bug.

Regards

**Comment by id** [comment]
Hi @FStefanni. Could you create an issue for https://github.com/emqx/emqx-operator/ instead?

**Comment by FStefanni** [comment]
Hi,

sure, done.
So I close this bug report.

Regards.
