### ISSUE TITLE
STOMP content-type was converted to text/plain

### ISSUE THREAD

**Issue by shinedd** [emqx/emqx#11369]
### What happened?

```
import stomp,time
class SampleListener(object):
    def on_message(self, frames):
        print('content-type: %s' % frames.headers['content-type'])


def stomp_test():
    conn = stomp.Connection12([('10.40.2.232', 61613)], auto_content_length=False)
    conn.set_listener(listener_name, SampleListener())
    conn.connect('', '', wait=True)
    conn.subscribe('topic','receiver')
    conn.send('topic', 'test info', content_type='application/vnd.bbf.usp.msg',headers={'reply-to-dest':'custom'})
    time.sleep(30)  
    conn.disconnect()


if __name__ == '__main__':
    try:
        stomp_test()
    except Exception as e:
        print(e)
```

I tried sending a frame with a content type of ‘application/vnd.bbf.usp.msg’ to the broker,
When I receive this frame, the content type becomes ‘text/plain’
        

### What did you expect to happen?

I expect the content type of the received frame to remain the same

### EMQX version

sysdescr  : EMQX
version   : 5.1.2
datetime  : 2023-07-31T14:33:56.089562446+08:00
uptime    : 3 days, 2 hours, 18 minutes, 46 seconds

### OS version

NAME="Ubuntu"
VERSION="18.04.5 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.5 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic

Linux shine 4.15.0-213-generic #224-Ubuntu SMP Mon Jun 19 13:30:12 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

### Log files

![image](https://github.com/emqx/emqx/assets/106661626/4a5e9701-8905-46bd-9d96-df6a8b178d26)

**Comment by id** [comment]
@HJianBo could you take a look at this one?
