### ISSUE TITLE
EMQX dashboard subscriptions.shared.count keep rising

### ISSUE THREAD

**Issue by IsaacDiane** [emqx/emqx#11387]
### What happened?

Hi,the team, these days we found the metric subscriptions.shared.count keep rising, there must be some mem leaking unexpected.
![image](https://github.com/emqx/emqx/assets/31270308/177251b1-c7ac-4ad0-9921-0fb861baf48e)
As shown in the image, there are 82 share subsriptions now, however, when searching in the subscriptions tab, there are only 12 shared subscriptions(2 shared topic with 6 mqtt clients). What happened with the rest share subscriptions counted by the metrics but not shown on dashboard?
We have already found the possible error code (subscribed but not unsubscribe when terminating), but I really want to know how to kickout the leaking subscriptions? Is it possible for these ghost subscriptions to get the shared message and lead to the message dropping?

### What did you expect to happen?

I want to clear the share subscriptions already aborted but not released caused by the wrong code. Restarting the mqtt service should be avoided as far as possible.

### How can we reproduce it (as minimally and precisely as possible)?

use two client to subscribe one shared subscription and do not unsubscribe when the main func return.

### EMQX version

<details>

```console
$ ./bin/emqx_ctl broker
# paste output here
```

</details>
shown 4.2.9 on the dashboard

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Log files

<details>

</details>

**Comment by id** [comment]
Hi @IsaacDiane. Please check out documentation for v4.2: https://www.emqx.io/docs/en/v4.2/advanced/cli.html#subscriptions-command.

Let me know if that helped.

Unfortunately, we are not supporting v4.2 anymore. Please consider upgrading to 5.1, or at least to 4.4.

**Comment by thalesmg** [comment]
Closing this as 4.2 is out of maintenance window.
