### ISSUE TITLE
EMQX fails to start after upgrading to 5.1.4

### ISSUE THREAD

**Issue by ruifung** [emqx/emqx#11380]
### What happened?

Due to the removal of the cacert option as per https://github.com/emqx/emqx/pull/11372
EMQX fails to start due to the removed option now resulting in an invalid configuration.

### What did you expect to happen?

For it to silently ignore the option or at least, not crash.

### How can we reproduce it (as minimally and precisely as possible)?

1. start with emqx 5.1.3
2. have a listener with the cacert option set.
3. upgrade to 5.1.4
4. watch as pods fail to start due to now invalid config.

### Anything else we need to know?

I think crashing due to removed config properties makes upgrading/downgrading difficult, especially when the properties are not directly set and set by emqx-operator, for example.

### EMQX version

<details>

```console
$ ./bin/emqx_ctl broker
# paste output here
```

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Log files

<details>

</details>

**Comment by ruifung** [comment]
@id Could you suggest how to fix the issue manually from a node running 5.1.3?

Because as it stands, trying to clear that setting from the admin UI seems to achieve nothing, and updating the image to 5.1.4 means it fails to start.

**Comment by id** [comment]
@thalesmg could you assist here?

**Comment by thalesmg** [comment]
@ruifung Could you try removing the `cacerts` option from `etc/emqx.conf` and `data/configs/cluster.hocon` before upgrading?

**Comment by zhongwencool** [comment]
Maybe we need add certs back, and mark its as deprecated.
```
2023-08-08T05:55:17.971448+00:00 [error] #{kind => validation_error,matched_type => "broker:mqtt_wss_listener",path => "listeners.wss.default.ssl_options",reason => unknown_fields,unknown => "cacerts",unmatched => "dhfile,password,..."}
```

**Comment by Rory-Z** [comment]
> @ruifung Could you try removing the `cacerts` option from `etc/emqx.conf` and `data/configs/cluster.hocon` before upgrading?

I think it's not work, because EMQX Operator will got EMQX's config by `Get /api/v5/configs` and storage it, so modifying the configuration file is meaningless.

**Comment by thalesmg** [comment]
> I think it's not work, because EMQX Operator will got EMQX's config by `Get /api/v5/configs` and storage it, so modifying the configuration file is meaningless.

Would it work if the stored configurations were edited manually (ConfigMap?), perhaps?

**Comment by thalesmg** [comment]
@ruifung [v5.1.5-build.3](https://github.com/emqx/emqx/releases/tag/v5.1.5-build.3) was just released.  Could please you try upgrading to that version?

**Comment by ruifung** [comment]
Excellent, updated the version in the emqx resource and it easily upgraded to 5.1.5-build.3 from 5.1.3
thanks.
