### ISSUE TITLE
Error mqtt ssl 

### ISSUE THREAD

**Issue by pedrit01** [emqx/emqx#11391]
#### Environment

- OS: Ubuntu 20.04 LTS
- Erlang/OTP:  R21/10.2.4
- EMQ: 3.2.7

#### Description
Hello,

We are getting this error trying to connect via mqtt ssl to our broker:

2023-08-03 17:02:41.967 [error]     supervisor: 'esockd_connection_sup - <0.1813.0>'
    errorContext: connection_shutdown
    reason: {options,{socket_options,{active,100}}}
    offender: [{pid,<0.3256.0>},
               {name,connection},
               {mfargs,{emqx_channel,start_link,
                                     [[{deflate_options,[]},
                                       {max_conn_rate,500},
                                       {active_n,100},
                                       {zone,external}]]}}]

Can anyone guide us through this error?

So many thanks!!

**Comment by id** [comment]
Hi @pedrit01. We have stopped supporting v3.x.x quite a while ago. Please consider upgrading to the latest version.
