### ISSUE TITLE
Blacklist feature of the HTTP-API should support int64 timestamp 

### ISSUE THREAD

**Issue by WonderLand33** [emqx/emqx#11404]
### What would you like to be added or enhanced?

The unitl field in the Blacklist feature of the HTTP-API should support int64 timestamp.

Version: v4.4.0
Documentation link: https://www.emqx.io/docs/en/v4.4/advanced/http-api.html#get-api-v4-banned

### Why is this needed?

Because the storage size of int type is 32 bits which can store a maximum value of 2^31 minus 1, approximately 2.147 billion (2,147,483,647). In other words, the maximum timestamp that can be represented in int type is January 19, 2038, 03:14:07.

**Comment by lafirest** [comment]
@WonderLand33 
Thanks for your feedback, although this is not so emergency, it is also better to improve. 
Another mention is that version 4.x is presently going to be out of maintenance, please consider upgradation.

**Comment by lafirest** [comment]
@WonderLand33 
in EMQX 5.1, the [maximum value](https://github.com/emqx/emqx/pull/11424) of the timestamp can reach 6000 AD, I think it is enough for use.
