### ISSUE TITLE
eMQ periodically loses connection on AWS with public IP

### ISSUE THREAD

**Issue by hackborn** [emqx/emqx#1140]
#### Environment

- OS: AWS Elastic Beanstalk, 64bit Amazon Linux 2017.03 v2.7.1 running Multi-container Docker 17.03.1-ce (Generic) 
- EMQ: 2.2-rc.2

#### Description

I'm trying to set up a bridge from a local eMQ node to one running on Amazon. I'm stuck trying to get the AWS node working with a public IP address. Everything is up and running, and if I let eMQ start up with its default node name, it uses the ec2 private address and it works fine. If I set the node name to one using the public address, eMQ can't start (can't ping the node), so I added a rule to make the public address pingable (Custom ICMP Rule, Echo Request, N/A, Allow anywhere) and this appeared to solve the problem, until I noticed my client is periodically losing the connection.

It stays up for maybe 15 seconds then goes down for about 5, regularly. The instance is still pingable even when the client is disconnected, and the client works fine whenever it's up.

I've looked at a few other issues to see if anything relates, but as far as I can tell nothing addresses this issue.
[1081](https://github.com/emqtt/emqttd/issues/1081)
[496](https://github.com/emqtt/emqttd/issues/496)
[516](https://github.com/emqtt/emqttd/issues/516)

thanks much for any info!

**Comment by zhengyupan** [comment]
Hi @hackborn ,
Please try the release 3.0. In the new release, the bridge is rewritten and works better.
