### ISSUE TITLE
expose the `clientid_prefix` configuration of the MQTT bridge in Dashboard 

### ISSUE THREAD

**Issue by lafirest** [emqx/emqx#11421]
### What would you like to be added or enhanced?

@ysfscream  Recently some users want to customize the client id of the MQTT bridge, it can be supported by setting the `clientid_prefix` configuration field, but this field is not visible in Dashboard.
A related issue #8498 

### Why is this needed?

Users want this and it is easy to implement.

**Comment by kjellwinblad** [comment]
I assigned @HJianBo to this issue as he is in the dashboard team. @HJianBo please assign it to someone else if you think someone else should handle this.

**Comment by kjellwinblad** [comment]
@wivwiv, FYI

**Comment by philippdzm** [comment]
+1

**Comment by philippdzm** [comment]
The 4.4.19 version of the software package has not been pushed to the APT repository. Did you stop pushing newer 4.4.X versions to your APT repository?

**Comment by id** [comment]
FYI @ysfscream @wivwiv

**Comment by tharaadiva** [comment]
hi, i have the same issue. any updates on this?

i am using EMQX v5.0.24 and i want to get data from remote broker to my local EMQX broker. 
i tried to set the clientid_prefix through the configuration file with this configuration below but it is still not working.

bridges {
mqtt.test {
enable = true
server = “server:port”
clientid_prefix = “clientid”
username = “username”
password = “password”
reconnect_interval = 15s
proto_ver = v4
bridge_mode = false
ingress {
remote {
topic = “$mytopicname”
qos = 1
}

  local {
    topic = "testdata"
    qos = "${qos}"
    retain = "${retain}"
    payload = "${payload}"
  }
}

#egress {
 # local {
  #  topic = "test"
  #}

  #remote {
   # topic = "test"
    #qos = "${qos}"
    #retain = "${retain}"
    #payload = "${payload}"
  #}
#}
}
}

kindly please help me if you have suggestions.

thanks!

**Comment by wivwiv** [comment]
@tharaadiva The configuration seems to be working, can you provide error logs?

**Comment by tharaadiva** [comment]
it's just showed up as "disconnected", 
![Screenshot 2024-04-25 115746](https://github.com/emqx/emqx/assets/49840058/33137c23-e488-4707-b7cb-8b120e35e93d)

**Comment by zmstone** [comment]
The client ID prefix config is now configurable from dashboard, at least 5.7.0 has it.
Closing this issue.
Related fix: https://github.com/emqx/emqx/pull/13216
