### ISSUE TITLE
mqtt client termination by emqx

### ISSUE THREAD

**Issue by dwenzi** [emqx/emqx#11475]
### What happened?

 2023-08-17 15:57:56.699 [error] hhhbYPBAsMojA9gzsyPQ7e ** Generic server <0.28861.1876> terminating ^M
  17009 ** Last message in was {'$gen_cast',^M
  17010                            {subscribe,<0.27075.1876>,^M
  17011                                {1,undefined,^M
  17012                                 [{<<"ser2cli_noti/969018edf68443e3b9856dc87aefe251">>,^M
  17013                                   #{nl => 0,qos => 0,rap => 0,rc => 0,^M
  17014                                     rh => 0}}]}}}^M
  17015 ** When Server state == {state,15000,true,#Fun<emqx_session.1.98926271>,^M
  17016                                <<"hhhbYPBAsMojA9gzsyPQ7e">>,^M
  17017                                <<"hhhbYPBAsMojA9gzsyPQ7e">>,<0.27075.1876>,^M
  17018                                undefined,1,0,#{},false,^M
  17019                                {emqx_inflight,32,{0,nil}},^M
  17020                                20000,undefined,^M
  17021                                {mqueue,true,1000,0,0,none,...},^M
  17022                                #{},100,300000,undefined,0,undefined,...}^M
  17023 ** Reason for termination == ^M
  17024 ** {{timeout,{gen_server,...}},[{...}|...]}^

### What did you expect to happen?

1、why mqtt client termination by mqtt server
2、how do i fix this problem

### How can we reproduce it (as minimally and precisely as possible)?

i have no idea

### EMQX version

<details>

sysdescr  : EMQ X Broker
version   : v3.1.0
uptime    : 68 days,8 hours, 13 minutes, 29 seconds
datetime  : 2023-08-18 10:35:53

</details>

### OS version

NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

### Log files

 /var/log/emqx/erlang.log.5 

2023-08-17 15:57:56.699 [error] hhhbYPBAsMojA9gzsyPQ7e ** Generic server <0.28861.1876> terminating ^M
  17009 ** Last message in was {'$gen_cast',^M
  17010                            {subscribe,<0.27075.1876>,^M
  17011                                {1,undefined,^M
  17012                                 [{<<"ser2cli_noti/969018edf68443e3b9856dc87aefe251">>,^M
  17013                                   #{nl => 0,qos => 0,rap => 0,rc => 0,^M
  17014                                     rh => 0}}]}}}^M
  17015 ** When Server state == {state,15000,true,#Fun<emqx_session.1.98926271>,^M
  17016                                <<"hhhbYPBAsMojA9gzsyPQ7e">>,^M
  17017                                <<"hhhbYPBAsMojA9gzsyPQ7e">>,<0.27075.1876>,^M
  17018                                undefined,1,0,#{},false,^M
  17019                                {emqx_inflight,32,{0,nil}},^M
  17020                                20000,undefined,^M
  17021                                {mqueue,true,1000,0,0,none,...},^M
  17022                                #{},100,300000,undefined,0,undefined,...}^M
  17023 ** Reason for termination == ^M
  17024 ** {{timeout,{gen_server,...}},[{...}|...]}^

**Comment by zmstone** [comment]
Hi @dwenzi 
Please note that v3 is no longer supported for bug fixes.
Please consider upgrading to v5.

Judging by the subscription call `timeout` in  the log, it seems to be due to system overload.
