### ISSUE TITLE
Message Repeates

### ISSUE THREAD

**Issue by fabltd** [emqx/emqx#11477]
### What happened?

Devices are set to have a peristant session.

Messages published get stuck in the Message Queue  and keep incrementing.  Messages are delivered to the device continusuly. 

The only way to stop messages is Kick the device out in the dashboard. 

When the device rejoins the Message Queue is flushed and finally the device is able to stop reciving messages. 

Only a few devices expierence this and its random when its happening. 

It renders the end device unusable and they are not able to recover by resetting the device as soon as it connects the que carrys on. The que never seems to empty.

### What did you expect to happen?

Continusly 

### How can we reproduce it (as minimally and precisely as possible)?

I am not sure. I cannot find the cause of the issue.

### EMQX version

<details>

Version:
[5.1.0](https://www.emqx.com/en/changelogs/broker/5.1.0)

</details>

### OS version

<details>

K8s on Google GKE
</details>

### Log files

<details>

</details>

**Comment by zmstone** [comment]
Hi @fabltd 
Is it QoS1 used by the subscribers?
It seems to be the subscriber client is not able to keep catch up.
Or the queue length can be configured with: `mqtt.max_mqueue_len = 100`

**Comment by fabltd** [comment]
Thanks yes this seems the issue. What does this flag do? Can I set from the UI

**Comment by zmstone** [comment]
Glad it helped. 

This flag can
1. protects slow subscribers from getting flood by too many undelivered messages.
2. lowers the RAM usage when a lot of subscribers have to buffer messages.

No, it's not exposed from the UI at the moment.
Will add it to dev team's backlog.

**Comment by zmstone** [comment]
sorry, it's actually in the UI.
![image](https://github.com/emqx/emqx/assets/164324/295a8789-f354-41d1-8ea2-68aa9280a1b3)
