### ISSUE TITLE
Problems in MQTT bridge retry(resend) interval time unit

### ISSUE THREAD

**Issue by jaspercloud** [emqx/emqx#11510]
### What happened?

I've created an MQTT Bridge to another MQTT Broker, and:
- If resend interval is set to 5 seconds, it does not work (no message sent)
- If set to 5 milli-second, it does work but sends after 5 seconds.

### What did you expect to happen?

时间单位错误

### EMQX version

<details>

```console
sysdescr  : EMQX
version   : 5.1.0
datetime  : 2023-08-24T06:06:34.399882102+00:00
uptime    : 8 days, 3 hours, 17 minutes, 12 seconds
```

</details>

### OS version

<details>

```console
docker image
REPOSITORY                     TAG       IMAGE ID   
emqx/emqx                      5.1.0     79771aa0c079

# On Linux:
$ cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
$ uname -a
Linux host-192-222-8-159 3.10.0-1062.el7.x86_64 #1 SMP Wed Aug 7 18:08:02 UTC 2019 x86_64 GNU/Linux

```

</details>

### Log files

<details>

</details>

**Comment by zmstone** [comment]
translation:

MQTT bridge retry(resend) interval unit bug:

If resend interval is set to 5 seconds, it does not work (no message sent)
If set to 5 milli-second, it does work but sends after 5 seconds.

**Comment by kjellwinblad** [comment]
@jaspercloud thanks for reporting this. I tried to reproduce this issues using my local machine and an EMQX build of latest master branch (development branch for the next 5.X release, commit 999988cab469e6218de5fa84a06351c6d81387db) and was not able to reproduce this issue.

I tested to send to to a remote broker through EMQX's MQTT bridge when my network connection was cut off. The message was delivered after I put my network connection on again both with 5 millisecond and 5 seconds retry time (when set to 5 millisecond the message was delivered almost directly and with 5 second it took a few seconds until I could see that the message was delivered).

I used QoS mode 2 both when sending the message to our broker and as the QoS setting under the egress configuration for EMQX's MQTT bridge.

Can you please check your QoS setting. If QoS mode is set to 0 there is no guarantee that the message will be delivered.

If you still think this issue exists, please give detailed instructions for exactly what one should do to reproduce the issue including how you configured the bridge.
