### ISSUE TITLE
Recurring full cluster partition failing to autoheal

### ISSUE THREAD

**Issue by ruifung** [emqx/emqx#11529]
### What happened?

On my 3 node cluster, the emqx cluster is occasionally going into a full partition where each node reports (emqx_ctl cluster status) every other node as down and gets stuck like that until I manually kill one of the pods. After it comes back up the rest of the cluster will successfully rejoin.

### What did you expect to happen?

For the cluster to self-heal and return to a functional state.

### How can we reproduce it (as minimally and precisely as possible)?

Unfortunately, I've not been able to manually reproduce it.

### Anything else we need to know?

Any suggestions on how to further troubleshoot this would be helpful.

### EMQX version

<details>

```console
$ ./bin/emqx_ctl broker
sysdescr  : EMQX
version   : 5.1.6
datetime  : 2023-08-26T07:36:20.535849618+00:00
uptime    : 7 minutes, 13 seconds
```

</details>

### OS version

<details>

```console
# Talos Linux Version
$ talosctl version
Server:
        NODE:        <redacted>
        Tag:         v1.5.1
        SHA:         40a22cdf
        Built:
        Go version:  go1.20.7
        OS/Arch:     linux/amd64
        Enabled:     RBAC

```
</details>

### Log files

Dump Files
[node_0_dump.tar.gz](https://github.com/emqx/emqx/files/12445448/node_0_dump.tar.gz)
[node_1_dump.tar.gz](https://github.com/emqx/emqx/files/12445449/node_1_dump.tar.gz)
[node_2_dump.tar.gz](https://github.com/emqx/emqx/files/12445450/node_2_dump.tar.gz)
And also pod logs for node-1 and node-2. Unfortunately at this point I've already killed and restarted node-0
[emqx-1.log](https://github.com/emqx/emqx/files/12445456/emqx-1.log)
[emqx-2.log](https://github.com/emqx/emqx/files/12445457/emqx-2.log)

**Comment by ieQu1** [comment]
Hello,

This could be related to the backward-incompatible changes in OTP25: https://www.erlang.org/doc/man/global.html#description

**Comment by ieQu1** [comment]
https://github.com/emqx/mria/pull/158

**Comment by ieQu1** [comment]
Thanks for the report, it should be fixed in the next release.
