### ISSUE TITLE
Closed after emqx started immediately

### ISSUE THREAD

**Issue by ian15937** [emqx/emqx#11525]
### What happened?

As title, emqx started, and then it is closed soon.

### What did you expect to happen?

Normally start.

### EMQX version

5.1.6

### OS version

<details>

```
BuildNumber  Caption                      OSArchitecture  Version
22621        Microsoft Windows 11 專業版  64 位元         10.0.22621
```

</details>

### Log files

[emqx.log](https://github.com/emqx/emqx/files/12441765/emqx.log)
[erl_crash.dump.txt](https://github.com/emqx/emqx/files/12441766/erl_crash.dump.txt)

**Comment by zhongwencool** [comment]
```
2023-08-26T00:37:39.135000+08:00 [error] tcp:default failed to listen on 1883 - eacces (permission denied)
```
It appears EMQX is unable to bind and listen on the default MQTT port 1883

This suggests something in the system configuration is preventing EMQX from opening that port

Some potential things to check:

- Network firewall rules - Port 1883 may be blocked

- **Process user permissions - EMQX process may not have rights to bind low ports**

- SELinux/AppArmor - These could impose additional restrictions

- Binding conflicts - Another process already using port 1883
