### ISSUE TITLE
After emqx is migrated, the enabled/disabled plug-in no longer writes to loaded_plugins files

### ISSUE THREAD

**Issue by maoyutofu** [emqx/emqx#11549]
### What happened?

Copy server emqx to server B. Starting emqx succeeded. Procedure If exhook is disabled, it will still be called. I noticed that loaded_plugins were not modified after disabling. When I tried to modify it manually, it didn't work either.

### What did you expect to happen?

exhook disabled takes effect

### EMQX version

<details>

```console
$ ./bin/emqx_ctl broker
sysdescr  : EMQ X Broker
version   : 4.4.10
uptime    : 3 hours, 9 minutes, 17 seconds
datetime  : 2023-08-31 11:35:51
```

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
NAME="Ubuntu"
VERSION="20.04.3 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.3 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```
</details>

### Log files

<details>

</details>

**Comment by tjz101** [comment]
Executing './bin/emqx_ctl exhook server disable default 'is successful.

**Comment by savonarola** [comment]
Hello! I experimented with the specified version and couldn't reproduce it. So the questions are:
# Isn't ExHook plugin running together with ExHook _module_?
# Could you please provide the logs of the new instance?
# Could you also provide a few more exact steps to reproduce?
