### ISSUE TITLE
官网的开源部分的文档都没法访问

### ISSUE THREAD

**Issue by crodling** [emqx/emqx#11589]
### What happened?

https://www.emqx.io/docs/en/v5.1/deploy/install.html
直接显示无法访问网站

### What did you expect to happen?

开源入口放的显目一些，隐藏起来至少自己不要忘了更新链接

### EMQX version

<details>

```console
$ ./bin/emqx_ctl broker
# paste output here
```

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Log files

<details>

</details>

**Comment by qzhuyan** [comment]
@crodling I don't have any issue accessing it.
I close it now, if you have issue of accessing from China Mainland. pls report it to https://askemq.com/
