### ISSUE TITLE
 Can not publish messages larger than 1KB in size

### ISSUE THREAD

**Issue by sambestsolutions** [emqx/emqx#11583]
### What happened?

Environment

OS: Ubuntu 22.04.2 LTS (Virtual Machines on GCP)
Spec: 2 vCPUs, 4GB RAM
Emqx Version: Emqx Community version - 5.1.5-build.3
Cluster: 2 machines

I have set up a 2-node Emqx community version cluster, and it works fine. However, when the message size exceeds 1 KB, the client gets disconnected and gets below error

`2023-09-08T19:55:18.815171+00:00 [debug] msg: authentication_result, mfa: emqx_authentication:authenticate/2, line: 247, peername: 172.16.5.3:64158, clientid: 999999, reason: chain_result, result: {stop,{ok,#{is_superuser => false}}}, tag: AUTHN 2023-09-08T19:55:18.816248+00:00 [debug] msg: insert_channel_info, mfa: emqx_cm:insert_channel_info/3, line: 159, peername: 172.16.5.3:64158, clientid: 999999
`

`2023-09-08T19:55:18.816449+00:00 [debug] msg: mqtt_packet_sent, mfa: emqx_connection:serialize_and_inc_stats_fun/1, line: 878, peername: 172.16.5.3:64158, clientid: 999999, packet: CONNACK(Q0, R0, D0, AckFlags=0, ReasonCode=0), tag: MQTT 2023-09-08T19:55:18.953174+00:00 [debug] msg: raw_bin_received, mfa: emqx_connection:when_bytes_in/3, line: 779, peername: 172.16.5.3:64158, clientid: 999999, bin: 3AD20C000D647269766572732F313233343500017B2274797065223A227363616E6E65725F747269705F61737369676E6564222C22686561646572223A7B2274797065223A227363616E6E65725F747269705F61737369676E6564222C2276657273696F6E223A312C22637265617465645F6174223A313639333238313832343436382C22657870697279223A313639333238313834392C226D6573736167655F6964223A313639333238313832343436383432383035357D2C22626F6479223A22643163393063653139366539397373647364736473646465666466646665336666333237636435386331356437326132633962356662313732333738646135336339663161323062303339643066643766326132383365643666396330653632383439633537396464326430633335663263656464393930623132323231393138333634363734323139643064313439363561346564663164323839616132663563386565373366323964303463363138393162616635306637633635656464656165323563623037313461613236336638623065376262326466333064353734363263373539633034373134376630373339656363326536616133323139313065373265343131303234326536613533356634643636343031353262383761303462383733303361343835353138346136343761313466363432383063333933643437363164313061386335353861376535333237666537323066313138353633393033346366626132323031353439623863373732343533646639643931363666353935633237323638653464336139363663313362336464373732656535666365376539653139613865346565376331356131333735366235633232323738376564373333616632383038636332663665326236343931303330383263316138616337363861633466346235623435616265303933666236333533323165343435653061656262356532306463336162306633303935666662353035616234326532626662343830323534646461396138333766636537353863353232653265383934303633306438613031303731383437623930373631636336353937616134626665306233663161326362636565326431616166393137343761666563666662643035646630616238303761626365323037633433373334653964666434656435373765346532626238353730303336346533643763383439353431346164633365376666393039623237386637306430303364313331303039656139343861326564393966653065383766386463366365303464393566376335393431393362633133323532633630316234303064363439616235623038353863636666313933666663623538363230306633383061353138363732323061343661343062663337303832366662636137306535623665366235303263613832666661323165646334363537383966346431383934343865326363616161356531616663366136333634633839306135313236636333346237316533376366623363643138376264376336633930653265653836313334313435666261323838333835363064383361613461363631623333393466613663343364393439656162303934383761303163303139356466626265336434316337646231383563313833643964313865653230633737643764613964613661376332386435376632306436366436343332393234643932336630356636353530636165326430653331616632663533396437323234396439346262303130653335613161373766643239613731383566303136356166333065636236303161386663303838303535393861376164303838336630383366343966633939643665343537666130363438363362353166653363363132333633313738363030313938393632636633346236373437373864336530663137643434316364366439373036666330366666666463363431393133653432616164656334366539333739356364663563303335323663303434333138373536363532643366636463613965386436346364633766386461376232613530333832333334383862313331613862343238633262663334376538303132336531363234306466643166363130653639303861643035393734356164303236363037326131356332613131323933306362616264386164656336616435633566393532643664227D, size: 1621, type: hex
`

`2023-09-08T19:55:18.954135+00:00 [debug] msg: emqx_connection_terminated, mfa: emqx_connection:terminate/2, line: 669, peername: 172.16.5.3:64158, clientid: 999999, reason: #{context => function_clause,exception => error,stacktrace => [{emqx_packet,format_payload,[<<"{\"type\":\"type1\",\"header\":{\"type\":\"type1\",\"version\":1,\"created_at\":1693281824468,\"expiry\":1693281849,\"message_id\":1693281824468428055},\"body\":\"d1c90ce196e99ssdsdsdsddefdfdfe3ff327cd58c15d72a2c9b5fb172378da53c9f1a20b039d0fd7f2a283ed6f9c0e62849c579dd2d0c35f2cedd990b12221918364674219d0d14965a4edf1d289aa2f5c8ee73f29d04c61891baf50f7c65eddeae25c"...>>,text],[{file,"emqx_packet.erl"},{line,617}]},{emqx_packet,format_variable,3,[{file,"emqx_packet.erl"},{line,506}]},{emqx_packet,format,2,[{file,"emqx_packet.erl"},{line,484}]},{emqx_trace_formatter,format_meta_map,3,[{file,"emqx_trace_formatter.erl"},{line,51}]},{emqx_connection,handle_msg,2,[{file,"emqx_connection.erl"},{line,575}]},{emqx_connection,process_msg,2,[{file,"emqx_connection.erl"},{line,493}]},{emqx_connection,process_msg,2,[{file,"emqx_connection.erl"},{line,499}]},{emqx_connection,handle_recv,3,[{file,"emqx_connection.erl"},{line,455}]},{proc_lib,wake_up,3,[{file,"proc_lib.erl"},{line,250}]}]}, tag: SOCKET
`

`2023-09-08T19:55:18.954494+00:00 [info] msg: terminate, mfa: emqx_connection:terminate/2, line: 674, peername: 172.16.5.3:64158, clientid: 999999, reason: #{context => function_clause,exception => error,stacktrace => [{emqx_packet,format_payload,[<<"{\"type\":\"type1\",\"header\":{\"type\":\"type1\",\"version\":1,\"created_at\":1693281824468,\"expiry\":1693281849,\"message_id\":1693281824468428055},\"body\":\"d1c90ce196e99ssdsdsdsddefdfdfe3ff327cd58c15d72a2c9b5fb172378da53c9f1a20b039d0fd7f2a283ed6f9c0e62849c579dd2d0c35f2cedd990b12221918364674219d0d14965a4edf1d289aa2f5c8ee73f29d04c61891baf50f7c65eddeae25c"...>>,text],[{file,"emqx_packet.erl"},{line,617}]},{emqx_packet,format_variable,3,[{file,"emqx_packet.erl"},{line,506}]},{emqx_packet,format,2,[{file,"emqx_packet.erl"},{line,484}]},{emqx_trace_formatter,format_meta_map,3,[{file,"emqx_trace_formatter.erl"},{line,51}]},{emqx_connection,handle_msg,2,[{file,"emqx_connection.erl"},{line,575}]},{emqx_connection,process_msg,2,[{file,"emqx_connection.erl"},{line,493}]},{emqx_connection,process_msg,2,[{file,"emqx_connection.erl"},{line,499}]},{emqx_connection,handle_recv,3,[{file,"emqx_connection.erl"},{line,455}]},{proc_lib,wake_up,3,[{file,"proc_lib.erl"},{line,250}]}]}
`

`2023-09-08T19:55:18.954745+00:00 [error] crasher: initial call: emqx_connection:init/4, pid: <0.3620.0>, registered_name: [], error: {function_clause,[{emqx_packet,format_payload,[<<"{\"type\":\"type1\",\"header\":{\"type\":\"type1\",\"version\":1,\"created_at\":1693281824468,\"expiry\":1693281849,\"message_id\":1693281824468428055},\"body\":\"d1c90ce196e99ssdsdsdsddefdfdfe3ff327cd58c15d72a2c9b5fb172378da53c9f1a20b039d0fd7f2a283ed6f9c0e62849c579dd2d0c35f2cedd990b12221918364674219d0d14965a4edf1d289aa2f5c8ee73f29d04c61891baf50f7c65eddea"...>>,text],[{file,"emqx_packet.erl"},{line,617}]},{emqx_packet,format_variable,3,[{file,"emqx_packet.erl"},{line,506}]},{emqx_packet,format,2,[{file,"emqx_packet.erl"},{line,484}]},{emqx_trace_formatter,format_meta_map,3,[{file,"emqx_trace_formatter.erl"},{line,51}]},{emqx_connection,handle_msg,2,[{file,"emqx_connection.erl"},{line,575}]},{emqx_connection,process_msg,2,[{file,"emqx_connection.erl"},{line,493}]},{emqx_connection,process_msg,2,[{file,"emqx_connection.erl"},{line,499}]},{emqx_connection,handle_recv,3,[{file,"emqx_connection.erl"},{line,455}]},{proc_lib,wake_up,3,[{file,"proc_lib.erl"},{line,250}]}]}, ancestors: [<0.2836.0>,<0.2835.0>,esockd_sup,<0.2688.0>], message_queue_len: 0, messages: [], links: [<0.2836.0>], dictionary: [{incoming_bytes,1659},{'$logger_metadata$',#{clientid => <<"999999">>,peername => "172.16.5.3:64158"}},{recv_pkt,1},{send_pkt,1},{outgoing_bytes,4},{guid,{1694202918816132,197598560390692,1}},{rand_seed,{#{bits => 58,jump => #Fun<rand.3.34006561>,next => #Fun<rand.0.34006561>,type => exsss,uniform => #Fun<rand.1.34006561>,uniform_n => #Fun<rand.2.34006561>},[144887117420521954|266771375895287299]}}], trap_exit: false, status: running, heap_size: 10958, stack_size: 28, reductions: 91545; neighbours:
`

`2023-09-08T19:55:18.955393+00:00 [debug] msg: emqx_cm_clean_down, mfa: emqx_cm:clean_down/1, line: 715, client_id: <<"999999">>`

`2023-09-08T19:55:18.955272+00:00 [error] supervisor: 'esockd_connection_sup - <0.2836.0>', errorContext: connection_crashed, reason: {function_clause,[{emqx_packet,format_payload,[<<"{\"type\":\"type1\",\"header\":{\"type\":\"type1\",\"version\":1,\"created_at\":1693281824468,\"expiry\":1693281849,\"message_id\":1693281824468428055},\"body\":\"d1c90ce196e99ssdsdsdsddefdfdfe3ff327cd58c15d72a2c9b5fb172378da53c9f1a20b039d0fd7f2a283ed6f9c0e62849c579dd2d0c35f2cedd990b12221918364674219d0d14965a4edf1d289aa2f5c8ee73f29d04c61891baf50f7c65eddea"...>>,text],[{file,"emqx_packet.erl"},{line,617}]},{emqx_packet,format_variable,3,[{file,"emqx_packet.erl"},{line,506}]},{emqx_packet,format,2,[{file,"emqx_packet.erl"},{line,484}]},{emqx_trace_formatter,format_meta_map,3,[{file,"emqx_trace_formatter.erl"},{line,51}]},{emqx_connection,handle_msg,2,[{file,"emqx_connection.erl"},{line,575}]},{emqx_connection,process_msg,2,[{file,"emqx_connection.erl"},{line,493}]},{emqx_connection,process_msg,2,[{file,"emqx_connection.erl"},{line,499}]},{emqx_connection,handle_recv,3,[{file,"emqx_connection.erl"},{line,455}]},{proc_lib,wake_up,3,[{file,"proc_lib.erl"},{line,250}]}]}, offender: [{pid,<0.3620.0>},{name,connection},{mfargs,{emqx_connection,start_link,[#{enable_authn => true,limiter => undefined,listener => {tcp,default},zone => default}]}}]`

`2023-09-08T19:55:19.248501+00:00 [debug] msg: emqx_connection_terminated, mfa: emqx_connection:terminate/2, line: 669, peername: 130.211.2.71:41414, reason: {shutdown,tcp_closed}, tag: SOCKET`

I have tested this behavior using both a Python MQTT publisher and the built-in WebSocket Client in the dashboard, and the behavior is the same in both cases.

Is there any Emqx-level or OS-level configuration that I may have missed?

Thanks.

### What did you expect to happen?

Able to publish messages eventhough it is larger than 1KB in size

### How can we reproduce it (as minimally and precisely as possible)?

install exact emqx version (5.1.5-build.3) and try to publish a message larger than 1KB in size 

### EMQX version

<details>

```console
$ ./bin/emqx_ctl broker

sysdescr  : EMQX
version   : 5.1.5-build.3
datetime  : 2023-09-10T13:34:17.551251894+00:00
uptime    : 1 days, 17 hours, 40 minutes, 31 seconds

```

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
PRETTY_NAME="Ubuntu 22.04.2 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.2 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy

$ uname -a
Linux dev-capp-emqx-community-5-1-5 6.2.0-1012-gcp #12~22.04.1-Ubuntu SMP Mon Aug 21 08:36:27 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

```

</details>

### Log files

<details>

</details>

**Comment by qzhuyan** [comment]
maybe relates to https://github.com/emqx/emqx/pull/11279

could you reproduce the issue when the debug logging/ tracing is disabled?

from the info you provide, looks like EMQX is not able to format the debug trace in text.

try change `trace.payload_encode` to `hex`

**Comment by qzhuyan** [comment]
duplicated in https://github.com/emqx/emqx/discussions/11582

**Comment by sambestsolutions** [comment]
> maybe relates to #11279
> 
> could you reproduce the issue when the debug logging/ tracing is disabled?
> 
> from the info you provide, looks like EMQX is not able to format the debug trace in text.
> 
> try change `trace.payload_encode` to `hex`

Yes when debug logging is disabled issue is no more, thank you very much
