### ISSUE TITLE
5370端口支持配置安全的协议及加密套件

### ISSUE THREAD

**Issue by candle-lion** [emqx/emqx#11606]
### What would you like to be added or enhanced?

端口安全排查过程中，发现5370端口支持不安全的协议（TLSv1、TLSv1.1）及加密套件，并且未找到配置方法

### Why is this needed?

因为5370端口本身只能被全0端口监听，若在使用不安全的协议和加密套件，意味增大了被攻击风险。

若支持配置指定的安全协议和加密套件，可以进一步增加系统整体安全性

**Comment by ieQu1** [comment]
Note: 5370 is `gen_rpc` TLS client port.
