### ISSUE TITLE
High CPU Usage after upgrade from emqx 4.3.8 to emqx 5.0.19

### ISSUE THREAD

**Issue by ctellechea2001** [emqx/emqx#11611]
### What happened?

We updated in the lower environment (DEV,SBX,UAT) the version from 4.3.8 to 5.0.19 a two month ago. Everything was fine in the lower enviroment. Today we did the same change in PRD (Logically the traffic and connections in PRD is higher than the lower enviroments) and we discovered that the CPU usage on each node have been increased. 

 
![image](https://github.com/emqx/emqx/assets/45426180/bea34195-b8d1-41d2-abd0-b28e8d8f87e2)

After the migration to 5.0.19 with the same cpu resources assigned as the 4.3.8 we started with the following errors:

`line: 416, message: <<"VM is overloaded on node:
line: 422, name: runq_overload
`
We needed to change the current Kubernetes EMQX Cluster Nodes resources limits. We removed the 1000m cpu limits and we increased the cpu request from 500m to 1. After that we stop receiving some random emqx connections issues. 

![image](https://github.com/emqx/emqx/assets/45426180/9a72190f-350c-4565-a405-0f67a27f5482)

Do you know if that is normal that High CPU Increase in the emqx 5.0.19 or is necessary to change something?

We have 920 connections in PRD in a cluster of tree nodes

### What did you expect to happen?

We need to discover the High cpu usage on emqx 5.0.19

### How can we reproduce it (as minimally and precisely as possible)?

emqx 5.0.19

### EMQX version

<details>

```console
$ ./bin/emqx_ctl broker
# paste output here
```

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Log files

<details>

</details>

**Comment by zhongwencool** [comment]
try to disable some vm prometheus collection, It's cost loading high.
```
prometheus {
  mnesia_collector = disabled
  vm_dist_collector = disabled
  vm_memory_collector = disabled
  vm_msacc_collector = disabled
  vm_statistics_collector = disabled
  vm_system_info_collector = disabled
}
```

**Comment by qzhuyan** [comment]
We have known perf issues in 5.0.19, you can find the perf improvements along the way in the changelogs.

pls try some newer versions.
