### ISSUE TITLE
Authentication and Authorization fail periodically 

### ISSUE THREAD

**Issue by seinshah** [emqx/emqx#11626]
### What happened?

I create a default `emqx.conf` file with initial configuration under `emqx/etc` path and then start the broker. Going to dashboard I can see that authorization and authentication configuration is successfully loaded.

However, when I try to connect to the broker under any port I see the following log and `Error: Connection refused: Not authorized` error:

```
2023-09-18T14:01:56.817774+00:00 [warning] msg: http_connector_do_request_failed, mfa: emqx_bridge_http_connector:on_query/3, line: 327, peername: 77.188.77.165:51792, clientid: ..., connector: <<"emqx_authn_http:3">>, reason: timeout
2023-09-18T14:01:56.818083+00:00 [error] msg: send_error, mfa: emqx_resource_buffer_worker:handle_query_result_pure/3, line: 902, peername: 77.188.77.165:51792, clientid: ..., id: <<"emqx_authn_http:3">>, reason: {recoverable_error,timeout}
```

But, if I do some updates on dashboard for authenticator and authorizer such as enable/disable or just simply press `update` button, I am able to connect to mqtt broker on all ports again (configs will be added to `data/configs/cluster.hocon`). But, again after a minute or so, I receive the same error as above and only if I perform an update again, client can establish a connection again.

**Default Config**  

<details>  

```
node {
  name = "emqx@127.0.0.1"
  role = core
  cookie = ""
  data_dir = "data"
}

cluster {
  name = "tandem_cluster_1"
  discovery_strategy = static
}

log {
  file_handlers.default {
    enable = true
    level = warning
    file = "log/emqx.log"
    rotation_count = 10
    rotation_size = 50MB
    formatter = text
  }
  console_handler {
    enable = true
    level = warning
    formatter = json
  }
}

listeners.ssl.default.enable = false
listeners.wss.default.enable = false

retainer {
  msg_expiry_interval = 3600s
  msg_clear_interval = 3605s
  backend {
    index_specs = [[1,2,4],[1,3,4]]
  }
}

flapping_detect {
  enable = true
  window_time = 1m
  max_count = 15
  ban_time = 5m
}

dashboard {
  default_username = "tandem"
  default_password = "tandem"
  listeners {
    http {
      bind  =  "0.0.0.0:18083"
    }
  }
}

authorization {
  sources = [
    {
      type = http
      enable = true

      url = ""
      request_timeout = 3s
      connect_timeout = 1s
      method = post
      body {
        username = "${username}"
        topic = "${topic}"
        action = "${action}"
      }
      ssl {
        enable = true
        verify = verify_none
      }
    }
  ]

  no_match = deny
  deny_action = ignore
  cache {
    enable = true
    max_size = 1000
    ttl = 5m
  }
}

authentication = [
  {
      mechanism = password_based
      backend = http
      enable = true

      method = post
      url = ""
      request_timeout = 3s
      connect_timeout = 1s
      body {
        username = "${username}"
        password = "${password}"
      }
      ssl {
        enable = true
        verify = verify_none
      }
  }
]

node.name = "emqx@10.0.1.4"
node.cookie = "cookie_name"
cluster.core_nodes = ["emqx@10.0.1.4"]
cluster.static.seeds = ["emqx@10.0.1.4"]
authorization.sources.1.url = "url/to/authz/${clientid}"
authentication.1.url = "url/to/authn/${clientid}"
```  

</details>

### What did you expect to happen?

I expect the default configuration for authn and authz to work indefinitely.

### EMQX version

<details>

```console
$ ./bin/emqx_ctl broker
sysdescr  : EMQX
version   : 5.1.6
datetime  : 2023-09-18T13:48:03.814959775+00:00
uptime    : 35 minutes, 12 seconds
```

</details>

### OS version

<details>

```console
$ cat /etc/os-release
PRETTY_NAME="Ubuntu 22.04.3 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.3 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
$ uname -a
Linux emqx 6.2.0-1011-azure #11~22.04.1-Ubuntu SMP Wed Aug 23 19:26:19 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
```

</details>

### Log files

<details>

</details>

**Comment by SergeTupchiy** [comment]
Hi @seinshah,

According to the logs you shared, authentication request failed due to the timeout, so EMQX couldn't receive a response from the HTTP authentication/authorization service within a configured timeout (3s).
It looks like there is nothing wrong with EMQX and errors are either caused by slow network and/or auth service.
Could you please also check your auth service and/or network performance to find out why requests can't be processed timely?
It also possible to increase timeout unless it's not acceptable for your use case...

**Comment by seinshah** [comment]
@SergeTupchiy thanks for the quick reply. I tried to investigate it more. The problem is that at the same time that I receive the timeout error from emqx for authentication, I run the following curl command from the same machine and get the response immediately. So, the auth server is responding without problem. Another thing to note is as soon as I click `update` on emqx dashboard in the setting page of http authenticator (without any change), authentication starts working again for a little while before it times out again.

**Curl Request - Responding within ms**

<details>

```
$ curl -d '{"username": "...", "password": "..."}' -H "accept:application/json" -H "cache-control: no-cache" -H "connection: keep-alive" -H "content-type: application/json" -H "keep-alive: timeout=30, max=1000" https://url/to/authn/<client_id>
{"result":"allow","is_superuser":true}
```

</details>

**Comment by SergeTupchiy** [comment]
@seinshah,
`/3` is the arity of the function, so `emqx_bridge_http_connector:on_query/3` is defined in module `emqx_bridge_http_connector` with the name `on_query` and 3 arguments. 
`:3` is just an ID ("emqx_authn_http:3").

Can you please confirm that once auth enters this error state it can never recover from it by itself (even after some more time) and all the subsequent requests fail with timeout unless you update authentication config in the dashboard? 
I'd like to double check it as the server may close a connection after keep alive timeout and the timeout error may occur, but it's expected to recover once a new connection is re-established...

Also, I would like to ask you for some more details:
1. Does this error occur when EMQX is not receiving any significant traffic or regardless of it? 
    For example, would it happen if there is a constant rate of subscribing clients during some period of time?
2.  According to the logs, HTTPS is used, would it be possible for you to check if the same error occurs with plain HTTP (e.g. in local/dev environment).
3. Is changing keepalive header in auth config have any effect? For example, if timeout is increased from 30s (default value) to 120s ("timeout=120, max=1000"), would the error start occurring after a longer period of time?

**Comment by seinshah** [comment]
@SergeTupchiy thanks for getting back to me and the information.

I confirm that once emqx enters this state, it never recovers (while curl command at the same time from the same machine works). But, as soon as configs are updated, it starts to work as expected again.

I was checking network traffic using `iftop` and when emqx is in the problematic state, I see that there are outbound traffic to auth server and 0 incoming traffic and this gets resolved when config is updated. I could not explain what's causing this exactly. But, on the auth server there is no incoming traffic from the broker whatsoever.

To answer the questions:
1. I'm in the process of setting up EMQX server from the scratch, so we have no live usage for the broker yet
2. I couldn't really replicate it on the local machine with http protocol, however staging auth server is behind ingress and only accepts https requests
3. Increasing keep-alive didn't change anything and emqx enters the problematic state after ~5mins from config changes regardless of the keep-alive value

By any chance do you have any hypothesis why it works after config update?

**Comment by seinshah** [comment]
One thing happened just now. I'm using MQTTX to test these connections and I was playing with configs, noticed that when broker enters this problematic state, I'd be able to establish the connection again if either:
- disable `Clean Start`
- enable `Clean Start` and set `Session Expiry Interval` to something bigger that I initially started the connection

May I get your insight?

**Comment by SergeTupchiy** [comment]
Thanks @seinshah, 

EMQX authenticates a user regardless of clean start /session expiry interval, so it must not be related. Probably it only appears to correlate with auth failures. 
If EMQX sends traffic to Auth service but Auth service doesn't receive anything, this must be caused by something in between them. Could you please check ingress, load balancer (if any)?

**Comment by seinshah** [comment]
One thing that I'm unable to explain that void every other hypothesis, is why does the problem gets reconciled when `update` button on dashboard in authentication page is pressed. If there is any type of network problem, it should be persistent I assume.
I tested 5.1.6 on ubuntu 22.04 and 5.0.3 on 20.04 and both resulted in the same problem.
I will keep debugging for a bit more to see if it's resolvable by any chance. Please let me know if you can think of something.

**Comment by SergeTupchiy** [comment]
@seinshah, updating auth config triggers full re-connection to HTTP Auth server, as the problem starts appearing only after some time, it explains why updating the config helps for a while..

**Comment by seinshah** [comment]
@SergeTupchiy thanks. May I know what do you mean by full reconnect? And considering that, do you have an idea what’s failing atm and how to fix it by any chance?

**Comment by SergeTupchiy** [comment]
@seinshah,
EMQX opens a pool of permanent connections (8 by default) to the remote HTTP auth server, reopening them if necessary, e.g., if they are closed by the remote peer. 

So it looks like a connection between EMQX and some intermediary (load balancer/reverse proxy, etc) is kept open, as  EMQX doesn't notice anything wrong and keeps sending data. However, this intermediary is likely not able to send the data to Auth server. At the same time, it also fails to communicate the problem back to EMQX, which should be done by closing the connection to EMQX.
This is just my assumption based on your observation:
> I was checking network traffic using iftop and when emqx is in the problematic state, I see that there are outbound traffic to auth server and 0 incoming traffic and this gets resolved when config is updated. I could not explain what's causing this exactly. But, on the auth server there is no incoming traffic from the broker whatsoever.

**Comment by seinshah** [comment]
@SergeTupchiy thank you for bearing with me and sorry for all the trouble. I had missed to attach a nat gateway to the vm apparently and that caused the problem. I'm gonna close this one. Thanks again
