### ISSUE TITLE
Migrating EMQX Server Settings, Including API Keys, Usernames, and Passwords

### ISSUE THREAD

**Issue by dineshwar21** [emqx/emqx#11678]
### What would you like to be added or enhanced?

Is there a way to migrate EMQX server settings, including API keys, usernames, and passwords, when moving from one server to another? Currently, we have an EMQX broker set up with specific configurations, such as built-in database usernames and passwords, and we've also added new API keys for API-level client fetch operations.

As we plan to migrate to a new server, we've reviewed the documentation and found a link discussing the export and import process. However, it seems to be tailored for the "Enterprise Edition." You can find the link here: [EMQX Backup and Restore Documentation](https://www.emqx.io/docs/en/v5/operations/backup-restore.html).

Our specific concern is how to ensure a smooth migration of API keys, usernames, and passwords for authentication purposes when transitioning to the new server.

If there is a way or any recommended methods for achieving this, we would greatly appreciate your guidance.

### Why is this needed?

Migrating EMQX Server Settings, Including API Keys, Usernames, and Passwords

**Comment by dineshwar21** [comment]
Hi @SergeTupchiy 

Thanks for your comment. In the latest version data export working fine. not in 5.0 the export command seems not found.

**Comment by SergeTupchiy** [comment]
@dineshwar21,  Yes, the reason is that data export/import was introduced in 5.1.

**Comment by dineshwar21** [comment]
Okay got it, Thanks @SergeTupchiy
