### ISSUE TITLE
EMQX clustering error (badrpc,econnrefused)  setting up Home Assistant addon and another docker container

### ISSUE THREAD

**Issue by hanley-development** [emqx/emqx#11708]
Wondering if anyone is has gotten EMQX clustering to work with the addon and another docker container?

I keep getting erconnectrefuse errors and wondering if it is because of env_vars.

```
- name: EMQX_NODE__NAME
  value: emqx2@192.168.0.140

- name: EMQX_NODE__COOKIE
  value: <changed>

- name: EMQX_CLUSTER__DISCOVERY_STRATEGY
  value: static

- name: EMQX_CLUSTER__STATIC__SEEDS
  value: "["emqx@192.168.20.86", "emqx2@192.168.0.140"]"
```

> 2023-09-28T12:30:51.268133-05:00 [error] crasher: initial call: gen_rpc_client:init/1, pid: <0.17899.0>, registered_name: [], exit: {{badrpc,econnrefused},[{gen_server,init_it,6,[{file,"gen_server.erl"},{line,407}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,226}]}]}, ancestors: [gen_rpc_client_sup,gen_rpc_sup,<0.1883.0>], message_queue_len: 0, messages: [], links: [<0.1889.0>], dictionary: [], trap_exit: true, status: running, heap_size: 2586, stack_size: 29, reductions: 7419; neighbours:

_Originally posted by @hanley-development in https://github.com/emqx/emqx/discussions/11707_

**Comment by ieQu1** [comment]
Hi,

Make sure you follow the instructions on how to configure the firewall and map the ports: https://www.emqx.io/docs/en/v5.2/deploy/cluster/security.html#port-mapping

**Comment by hanley-development** [comment]
emqx > emqx2 

root@emqx:~# netcat -zv 192.168.0.140 4372
192.168.0.140: inverse host lookup failed: Host name lookup failure
(UNKNOWN) [192.168.0.140] 4372 (?) open

root@emqx:~# netcat -zv 192.168.0.140 5369 
192.168.0.140: inverse host lookup failed: Host name lookup failure
(UNKNOWN) [192.168.0.140] 5369 (?) open

**Comment by zmstone** [comment]
Hi @hanley-development 

Which EMQX version are you running?
And in which node did `econnrefused` happen?

`econnrefused` implies that the peer node is reachable but not the port.
To check the port in use, you can execute `emqx remote_console` then evaluate this expression `rp(application:get_all_env(gen_rpc)).`
My output looks like this (the output is quite verbose, I copied only the important lines):
```
e5.3.0(emqx@172.17.0.3)1> rp(application:get_all_env(gen_rpc)).
[{socket_ip,{0,0,0,0}},
 {client_config_per_node,{internal,#{}}},
 {insecure_auth_fallback_allowed,true},
 {tcp_client_port,5369},
 {port_discovery,manual},
 {tcp_server_port,5369},
 {driver,tcp}]
ok
```


btw, it's probably unrelated, but the quotes look odd for EMQX_CLUSTER__STATIC__SEEDS,
this should work:
`value: "emqx@192.168.20.86,emqx2@192.168.0.140"`

**Comment by hanley-development** [comment]
@zmstone running v5.2.1

Getting it on both nodes:

emqx:
2023-09-28T08:56:36.538670-05:00 [error] event=connect_to_remote_server peer="emqx@192.168.0.140" result=failure reason="econnrefused"
2023-09-28T08:56:36.538817-05:00 [error] crasher: initial call: gen_rpc_client:init/1, pid: <0.14975.0>, registered_name: [], exit: {{badrpc,econnrefused},[{gen_server,init_it,6,[{file,"gen_server.erl"},{line,835}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,240}]}]}, ancestors: [gen_rpc_client_sup,gen_rpc_sup,<0.2130.0>], message_queue_len: 0, messages: [], links: [<0.2136.0>], dictionary: [], trap_exit: true, status: running, heap_size: 376, stack_size: 28, reductions: 3390; neighbours:

emqx2:
2023-09-29T15:29:37.623308-05:00 [error] event=connect_to_remote_server peer="emqx@192.168.20.86" result=failure reason="econnrefused"
2023-09-29T15:29:37.623442-05:00 [error] crasher: initial call: gen_rpc_client:init/1, pid: <0.2718.0>, registered_name: [], exit: {{badrpc,econnrefused},[{gen_server,init_it,6,[{file,"gen_server.erl"},{line,407}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,226}]}]}, ancestors: [gen_rpc_client_sup,gen_rpc_sup,<0.1883.0>], message_queue_len: 0, messages: [], links: [<0.1889.0>], dictionary: [], trap_exit: true, status: running, heap_size: 2586, stack_size: 29, reductions: 7419; neighbours:


I updated the value and restarted, but got the same error. They are on different VLANs but are wide open between each other just not with the rest of my network. VLAN 20 = IOT





```
v5.2.1(emqx@192.168.20.86)1> rp(application:get_all_env(gen_rpc)).
[{socket_keepalive_interval,75},
 {tcp_client_port,5369},
 {ssl_client_options,[]},
 {call_receive_timeout,15000},
 {default_client_driver,tcp},
 {rpc_module_control,disabled},
 {ssl_server_port,5369},
 {connect_timeout,5000},
 {authentication_timeout,5000},
 {tcp_server_port,5369},
 {server_inactivity_timeout,infinity},
 {client_config_per_node,{internal,#{}}},
 {socket_buffer,1048576},
 {socket_sndbuf,1048576},
 {client_inactivity_timeout,infinity},
 {ssl_client_port,5370},
 {driver,tcp},
 {max_batch_size,256},
 {insecure_auth_fallback_allowed,true},
 {send_timeout,5000},
 {sbcast_receive_timeout,15000},
 {port_discovery,stateless},
 {ssl_server_options,[]},
 {async_call_inactivity_timeout,infinity},
 {socket_recbuf,1048576},
 {socket_keepalive_idle,900},
 {socket_keepalive_count,9},
 {rpc_module_list,[]}]
ok
```



```
v5.0.26(emqx2@192.168.0.140)1> rp(application:get_all_env(gen_rpc)).
[{insecure_auth_fallback_allowed,true},
 {send_timeout,5000},
 {connect_timeout,5000},
 {client_inactivity_timeout,infinity},
 {tcp_server_port,5369},
 {socket_keepalive_interval,75},
 {server_inactivity_timeout,infinity},
 {ssl_client_options,[]},
 {default_client_driver,tcp},
 {ssl_server_port,5369},
 {socket_keepalive_count,9},
 {rpc_module_list,[]},
 {client_config_per_node,{internal,#{}}},
 {rpc_module_control,disabled},
 {max_batch_size,256},
 {socket_sndbuf,1048576},
 {sbcast_receive_timeout,15000},
 {async_call_inactivity_timeout,infinity},
 {tcp_client_port,5369},
 {ssl_server_options,[]},
 {call_receive_timeout,15000},
 {port_discovery,manual},
 {authentication_timeout,5000},
 {socket_buffer,1048576},
 {ssl_client_port,5370},
 {socket_recbuf,1048576},
 {driver,tcp},
 {socket_keepalive_idle,900}]
ok
```

**Comment by hanley-development** [comment]
{port_discovery,manual} on 192.168.0.140.... could that be the issue?

```
- name: EMQX_CLUSTER__DISCOVERY_STRATEGY
  value: static
- name: EMQX_CLUSTER__STATIC__SEEDS
  value: emqx@192.168.20.86,emqx2@192.168.0.140
```

**Comment by hanley-development** [comment]
```
- name: EMQX_NODE__NAME
  value: emqx2@192.168.0.140
- name: EMQX_NODE__COOKIE
  value: <Change>
- name: EMQX_CLUSTER__DISCOVERY_STRATEGY
  value: static
- name: EMQX_CLUSTER__STATIC__SEEDS
  value: "\"emqx@192.168.20.86,emqx2@192.168.0.140\""
- name: EMQX_RPC__PORT_DISCOVERY
  value: stateless
```
Yep that worked! thank you @zmstone !!!!!!!!!!!!!!!!!!!!!!!!!!!!
