### ISSUE TITLE
Support to listen IPv6 address of port 5370

### ISSUE THREAD

**Issue by zhupeijun** [emqx/emqx#11715]
### What happened?

```
Netid               State            Local Address:Port         
tcp                 LISTEN                 0.0.0.0:5370         
tcp                 LISTEN                       *:1883         
tcp                 LISTEN                       *:18083        
tcp                 LISTEN                       *:4370         
tcp                 LISTEN                       *:8083         
tcp                 LISTEN                       *:8883         
tcp                 LISTEN                       *:8084 
```

All other ports are supported to listen IPv6 address, except `5370` port.  Hope to have a configuration like other ports to listen IPv6 address of `5370` port, so that EMQX can be deployed under IPv6 only environment.

### What did you expect to happen?

There is a configuration to listen IPv6 address of `5370` port. 

### EMQX version

<details>

```console
$ ./bin/emqx_ctl broker
sysdescr  : EMQX
version   : 5.1.0
datetime  : 2023-10-02T11:02:05.936178417+08:00
uptime    : 2 days, 2 hours, 55 minutes, 37 seconds
```

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
$ uname -a
Linux emqx-1 3.10.0-1160.92.1.el7.x86_64 #1 SMP Tue Jun 20 11:48:01 UTC 2023 x86_64 GNU/Linux
```

</details>

### Log files

<details>

</details>

**Comment by zmstone** [comment]
related pull requests:
Peer address formatting issue: https://github.com/emqx/gen_rpc/pull/37
Force client to pick ipv6 when ipv6 is used in server settings: https://github.com/emqx/gen_rpc/pull/38

**Comment by zmstone** [comment]
@zhupeijun thank you for reporting this.

IPv6 was already supported, however there were two issues
1. The configuration is not exposed as EMQX config
2. A log formatting issue, which is now fixed see above comment

PR #11734 will address theses issues, in addition, it also included
1. Make possible to make EMQX pick ipv6 over ipv4 when running in dual-stack environment

please see the PR for more details

**Comment by zhupeijun** [comment]
Thank you for your support!

**Comment by zmstone** [comment]
will be a part of v5.3.1.
feel free  to test it out using this alpha release.
https://github.com/emqx/emqx/releases/tag/v5.3.1-alpha.1
