### ISSUE TITLE
Deploy across multiple data center

### ISSUE THREAD

**Issue by forest-yang** [emqx/emqx#1171]
#### Environment

- OS: All
- Erlang/OTP:  latest
- EMQ: All

#### Description
This is not a issue but a topic. how EMQ support deploy across multiple data center?
it's maybe some data synchronization mechanism or coordination when client connect with different data center.

**Comment by grutabow** [comment]
Bridge is able to sync data between brokers, please refer to http://emqtt.io/docs/v2/bridge.html.

**Comment by forest-yang** [comment]
thanks for the information. 
Bridge solution will sync ALL data between brokers, right? 
Let me describe this scenario/expectation:
Two system (EMQ server) deploy in two data center with active-active relation, so they can achieve Geo-redundancy.

MQTT client maybe connect any one of system of two system (by DNS).
For up-link message, when EMQ server receive message, it can handle, such as save into database or trigger event defined.
For down-link message, there are two sub-scenarios:
if client is online, then server know which EMQ system should use;
if client is offline, how to coordinate two EMQ across data center, when client wake-up and connect with one of EMQ server, it can fetch message.
