### ISSUE TITLE
Exhook publish error:  byte_size、erl_erts_errors

### ISSUE THREAD

**Issue by poxuan** [emqx/emqx#11738]
### What happened?

I use Exhook to write some data to database , Simple modification your example Exhook Server of Golang .
 https://github.com/emqx/emqx-extension-examples 

And It works well .

Today, when I cut in a new MQTT client by another Group，Exhook server not receive the payload. The payload seems like a normal json string.

`{
	"id":	"123456abcdef",
	"channel":	1,
	"number":	9,
	"rate":	4000,
	"sampleType":	1,
	"freq":	242.1875,
	"amp":	14.517294883728028
}`

When I Use the Mqttx to publish the same topic and payload, it works well, and I can listen the new client  publish data.

Exhook's fail count grow up, Here is the error log, error in file: emqx_exhook_pb.erl , but emqx_exhook_pb.erl is ignore by git, and I can't find it. 

`2023-10-10T12:57:49.826654+08:00 [error] msg: exhook_call_exception, mfa: emqx_exhook_server:do_call/5, line: 423, peername: 183.160.34.59:52033, clientid: <<49,50,51,52,53,54,97,98,99,100,101,102,160,15>>, function: on_message_publish, module: emqx_exhook_v_2_hook_provider_client, options: #{channel => <<"DataSave2">>,failed_action => deny,key_dispatch => <<49,50,51,52,53,54,97,98,99,100,101,102,160,15>>,timeout => 5000}, req: #{message => #{from => <<49,50,51,52,53,54,97,98,99,100,101,102,160,15>>,headers => #{<<"peerhost">> => <<"183.160.34.59">>,<<"protocol">> => <<"mqtt">>,<<"username">> => <<"bbkstest">>},id => <<"000607558C6CEA17F442DE047B630002">>,node => <<"emqx@127.0.0.1">>,payload => <<"{\n\t\"id\":\t\"123456abcdef\",\n\t\"channel\":\t0,\n\t\"number\":\t8,\n\t\"rate\":\t4000,\n\t\"sampleType\":\t1,\n\t\"freq\":\t454.1015625,\n\t\"amp\":\t3.286979913711548\n}">>,qos => 0,timestamp => 1696913869826,topic => <<"/bbkstest/123456abcdef/data">>},meta => #{cluster_name => "emqxcl",node => <<"emqx@127.0.0.1">>,sysdescr => "EMQX",version => "5.0.17"}}, stacktrace: [{erlang,byte_size,[{error,<<"123456abcdef">>,<<160,15>>}],[{error_info,#{module => erl_erts_errors}}]},{emqx_exhook_pb,e_type_string,3,[{file,"emqx_exhook_pb.erl"},{line,2514}]},{emqx_exhook_pb,encode_msg_message,3,[{file,"emqx_exhook_pb.erl"},{line,1791}]},{emqx_exhook_pb,e_mfield_message_publish_request_message,3,[{file,"emqx_exhook_pb.erl"},{line,2339}]},{emqx_exhook_pb,encode_msg_message_publish_request,3,[{file,"emqx_exhook_pb.erl"},{line,1197}]},{grpc_client,send,3,[{file,"grpc_client.erl"},{line,214}]},{grpc_client,unary,4,[{file,"grpc_client.erl"},{line,167}]},{emqx_exhook_server,do_call,5,[{file,"emqx_exhook_server.erl"},{line,387}]},{emqx_exhook,call_fold,4,[{file,"emqx_exhook.erl"},{line,64}]},{emqx_exhook_handler,on_message_publish,1,[{file,"emqx_exhook_handler.erl"},{line,233}]},{emqx_hooks,safe_execute,2,[{file,"emqx_hooks.erl"},{line,200}]},{emqx_hooks,do_run_fold,3,[{file,"emqx_hooks.erl"},{line,180}]},{emqx_broker,publish,1,[{file,"emqx_broker.erl"},{line,222}]},{emqx_channel,do_publish,3,[{file,"emqx_channel.erl"},{line,731}]},{emqx_connection,with_channel,3,[{file,"emqx_connection.erl"},{line,801}]},{emqx_connection,process_msg,2,[{file,"emqx_connection.erl"},{line,471}]},{emqx_connection,process_msg,2,[{file,"emqx_connection.erl"},{line,477}]},{emqx_connection,handle_recv,3,[{file,"emqx_connection.erl"},{line,433}]},{proc_lib,wake_up,3,[{file,"proc_lib.erl"},{line,236}]}]
2023-10-10T12:57:54.827658+08:00 [error] Unexecpted stream event: {gun_response,<0.24578.1246>,#Ref<0.2147576290.122421250.122476>,fin,200,[{<<"content-type">>,<<"application/grpc+proto">>},{<<"grpc-status">>,<<"4">>},{<<"grpc-message">>,<<"context deadline exceeded">>}]}, stream #{encoding => identity,hangs => [],mqueue => [],recvbuff => <<>>,sendbuff => [],sendbuff_last_flush_ts => 0,sendbuff_size => 0,st => {open,idle}}
2023-10-10T12:57:54.827838+08:00 [error] [gRPC Client] Stream shutdown reason: {stream_error,no_error,'Stream reset by server.'}, stream: #stream{st={open,idle}, buff_size=0, mqueue=[]} `

 
    what can I do to solve it? Is there something wrong with the payload ?

### What did you expect to happen?

success receive the payload in Exhook server

### EMQX version

5.0.17

### OS version

NAME="Alibaba Cloud Linux"
VERSION="3 (Soaring Falcon)"
ID="alinux"
ID_LIKE="rhel fedora centos anolis"
VERSION_ID="3"
PLATFORM_ID="platform:al8"
PRETTY_NAME="Alibaba Cloud Linux 3 (Soaring Falcon)"
ANSI_COLOR="0;31"
HOME_URL="https://www.aliyun.com/"

### Log files

<details>

</details>

**Comment by keynslug** [comment]
Hi @poxuan,

It's not readily obvious from the stacktrace, but this crash is caused by the fact that the MQTT client sent malformed _ClientID_ upon connecting.
```
#{message => #{from => <<49,50,51,52,53,54,97,98,99,100,101,102,160,15>>,...}}
```
As you can see here, there's a sequence of bytes `10100000 00001111` that can not be interpreted as [valid UTF-8 encoding][1].

Specification mandates that _ClientID_ should be [an UTF-8 encoded string][2], however EMQX does not validate that by default for the sake of efficiency. This can be changed through the configuration ([`mqtt.strict_mode`][3]).

On the other hand, gRPC also requires any strings to be UTF-8 encoded and crashes with such unattractive errors when they are not.

[1]: https://en.wikipedia.org/wiki/UTF-8#Encoding
[2]: https://docs.oasis-open.org/mqtt/mqtt/v5.0/os/mqtt-v5.0-os.html#_Toc3901059
[3]: https://www.emqx.io/docs/en/v5.0/configuration/configuration-manual.html#mqtt-basic-parameters

**Comment by poxuan** [comment]
thank you very much
