### ISSUE TITLE
Why can't I connect to the ws and wss protocols?

### ISSUE THREAD

**Issue by bbhxwl** [emqx/emqx#11744]
### What happened?

Why can't I connect to the ws and wss protocols?

![61ffa33bea9210d3c7ed79bb1dc4072](https://github.com/emqx/emqx/assets/26525599/b3bbd6f6-9b2f-4775-9a92-8fecd77f4ef6)
![image](https://github.com/emqx/emqx/assets/26525599/e25998ab-2621-48e5-8853-a74fa28c3425)

### What did you expect to happen?

Why can't I connect to the ws and wss protocols?

### EMQX version

5.1

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Log files

<details>

</details>

**Comment by keynslug** [comment]
Not enough information, please consider filling the missing bits of the issue template. What's the client? How's WSS listener [configured](https://www.emqx.io/docs/en/v5.0/configuration/listener.html#configure-secure-websocket-listener)? Why there's a connection crash related to regular TLS listener? Note that `wss` listener listens on port [8084 by default](https://www.emqx.io/docs/en/v5.0/configuration/listener.html#configure-tcp-listener).

**Comment by thalesmg** [comment]
Also, the error screenshot shows the `no_suitable_ciphers` error reason, which hints at the client not using appropriate TLS/cipher versions.  You may try to use TLS1.3 and configuring different ciphers on the client side.
