### ISSUE TITLE
Missing proper emqx.conf when running with Docker

### ISSUE THREAD

**Issue by igo** [emqx/emqx#11769]
### What happened?

As mentioned in https://hub.docker.com/r/emqx/emqx I should backup /opt/emqx/etc, however it fails on missing emqx.conf file.
Once empty emqx.conf is created (as mentioned at https://github.com/emqx/emqx/blob/master/apps/emqx/etc/emqx.conf), it fails on:

```
escript: exception throw: {emqx_conf_schema,[#{kind => validation_error,
                                      path => "node.cookie",
                                      reason => required_field},
                                    #{kind => validation_error,
                                      path => "node.data_dir",
                                      reason => required_field}]}
  in function  hocon_tconf:assert/2 (hocon_tconf.erl, line 1225)
  in call from hocon_tconf:map/4 (hocon_tconf.erl, line 303)
  in call from hocon_cli:get_values/3 (hocon_cli.erl, line 194)
  in call from hocon_cli:multi_get/2 (hocon_cli.erl, line 182)
  in call from escript:run/2 (escript.erl, line 750)
  in call from escript:start/1 (escript.erl, line 277)
  in call from init:start_em/1 
  in call from init:do_boot/3 
ERROR: call_hocon_failed: -s emqx_conf_schema -c /opt/emqx/etc/emqx.conf multi_get node.data_dir node.name node.cookie node.db_backend cluster.proto_dist node.dist_net_ticktime
```

### What did you expect to happen?

Let start the app with defaults or let it create valid file automatically or some valid documentation how to run it in docker

### How can we reproduce it (as minimally and precisely as possible)?

```sh
mkdir -p emqx-data/data emqx-data/etc emqx-data/log
cd emqx-data/etc && touch emqx.conf
sudo docker run -d --name emqx -p 127.0.0.1:1883:1883 -p 127.0.0.1:8083:8083 -p 127.0.0.1:8084:8084 -p 127.0.0.1:8883:8883 -p 127.0.0.1:18083:18083 -v $HOME/emqx-data/data:/opt/emqx/data -v $HOME/emqx-data/etc:/opt/emqx/etc -v $HOME/emqx-data/log:/opt/emqx/log --restart=always emqx/emqx:latest
```

### EMQX version

latest docker image

### OS version

NAME="Ubuntu"
VERSION="20.04.6 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.6 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal

Linux server1 5.4.0-163-generic #180-Ubuntu SMP Tue Sep 5 13:21:23 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

**Comment by thalesmg** [comment]
Hi @igo .

You can seed your `etc` directory with the files from a fresh container and start working from there.

```sh
# create a directory to get store the seed files; remember not give permissions only to root
mkdir /tmp/seed
# get the seed files from the image
docker run --rm -it \
       -v /tmp/seed:/tmp/seed \
       emqx/emqx:latest \
       bash -c 'cp -R /opt/emqx/etc /tmp/seed/'
# change the seed files in the volume as you need
# start the container with the volume mounted
docker run --rm -it \
       -v /tmp/seed/etc:/opt/emqx/etc \
       emqx/emqx:latest
```

**Comment by igo** [comment]
Thanks for info @thalesmg. This approach makes it harder to deploy it in docker. No one wants to run additional commands from docker just to be able to start the app. Just my 2 cents.

**Comment by id** [comment]
@igo you are right, we updated documentation https://hub.docker.com/r/emqx/emqx to remove `/opt/emqx/etc` from the list of directories which need to be persisted as this is not the case anymore. Will update the official docs soon as well.
