### ISSUE TITLE
How to configure on AWS?

### ISSUE THREAD

**Issue by hackborn** [emqx/emqx#1176]
#### Environment

- OS: Docker 17.03.1-ce on Amazon Linux 2017.03 v2.7.2
- Erlang/OTP: 
- EMQ: 2.3 beta 1

#### Description

Sorry for the basic question, but I'm stumped how to change the emq.conf file on AWS. As far as I know I should just need to copy over my new file from an .ebextensions file, but I can't figure out where to place it. I SSH'd into an EC2 instance running the official EMQ docker image, but the only existing emq.conf files are in odd places (./var/lib/docker/volumes/{some long value}/_data/emq.conf and ./var/lib/docker/devicemapper/mnt/{another long value}/rootfs/opt/emqttd/etc/emq.conf). I took a guess and tried to place it at ./opt/emqttd/etc/emq.conf but got a no file or directory error starting the instance. Where do the configuration files go?

**Comment by turtleDeng** [comment]
@hackborn You can modify the configuration through the environment variable.
https://github.com/emqtt/emq-docker

**Comment by hackborn** [comment]
Ahhh sorry, I didn't see the note that all cfg items were available, I thought that was a complete list. Thanks much for the info!

**Comment by turtleDeng** [comment]
Any cfg  item can be configured
