### ISSUE TITLE
”resource is blocked“ in the logs and Authentication failed

### ISSUE THREAD

**Issue by zhangkaqiu520** [emqx/emqx#11788]
### What happened?

”resource is blocked“ in the logs and Authentication failed 
number of ”No match“ in Dashbord is rapid growth
then i check my http auth service is ok

when i delete http Authentication on the dashbord and create a new one 
every thing is ok 

<img width="201" alt="image" src="https://github.com/emqx/emqx/assets/45962071/ab404c76-ad32-4fc3-9f38-b04643fa1e84">

### What did you expect to happen?

but this bug is repeat on my mqtt service day by day.

### EMQX version

<details>

```console
5.0.14
```

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Log files

<details>
{"time":1697629020260361,"tag":"AUTHN","response":{"error":"{resource_error,#{msg => \"resource is blocked\",reason => blocked}}"},"resource":"emqx_authn_http:9","request":{"path_query":"/auth/mqtt?clientid=Mua%40b45583e989b34a9398e2a2586c70f476%40Flutter","mody":"{\"username\":\"mua_579778\",\"password\":\"[password]\"}","method":"post","headers":{"keep-alive":"timeout=30, max=1000","content-type":"application/json","connection":"keep-alive","cache-control":"no-cache","accept":"application/json"},"base_url":"http://10.0.4.8:8083/auth/mqtt?clientid=${clientid}"},"provider":"emqx_authn_http","pid":"<0.21615.23>","peername":"[180.98.128.38:56137](http://180.98.128.38:56137/)","msg":"http_response","line":192,"level":"debug","is_trace":"false","clientid":"Mua@b45583e989b34a9398e2a2586c70f476@Flutter","mfa":"emqx_authn_http:authenticate/2"}
</details>

**Comment by thalesmg** [comment]
Hi @zhangkaqiu520 .

The logs indicate that your HTTP authn service might be overwhelmed, or it might have returned an error response to the authenticator, which made the connection to it to be blocked in an attempt for it to recover.

There were also some [improvements](https://github.com/emqx/emqx/pull/10562) to the webhook connector that help make it more stable.  You can try to upgrade to the latest version, or at least v5.0.25 to have those.
