### ISSUE TITLE
Seeing Degraded performance inverse to expected

### ISSUE THREAD

**Issue by vidhill** [emqx/emqx#1180]
#### Environment

- OS: Alpine (within docker image on Kubernetes)
- Erlang/OTP: R18/7.3.1
- EMQ: 2.1.2

#### Description
We have emq running on kubernetes, we have been doing load tests on it.

We have moved to a different Kubernetes environment, 
and for some reason In our load tests weren't able to achieve as high a number of connections..

Broadly the only major difference I can see between the two Kubernetes clusters is the number of cores, 8 core versus 16 cores

At a baseline, with no load... 
according to kubernetes, the pod running EMQ consumes 0.5Gb of ram (on the 8 core kube node)
And then the pod on the 16 core node seems to be using over 1Gb of ram, also with no load...

I was running with the theory that EMQ allocates some amount of RAM per core and that with the increased number or cores the RAM usage would be increasing in line with the number of cores....

Though more I read about how kubernetes allocates CPU core resources this theory of mine seems to be based on a wrong assumption...

Can you think of any reason why we would see degraded performance on what appears to be a more powerful kubernetes cluster?

**Comment by zhanghongtong** [comment]
Hi, we released emqx v3.0.0, you can see them on the [docker hub](https://hub.docker.com/r/emqx/emqx/tags), the new version improves performance, you can test with v3.0.0

**Comment by zhengyupan** [comment]
Hi @vidhill ,
The new release should solve this issue, if it reproduces, please reopen it.
