### ISSUE TITLE
OpenTelemetry exporter uses incorrect timestamp

### ISSUE THREAD

**Issue by singhbaljit** [emqx/emqx#11802]
### What happened?

We're sending EMQX metrics to an OpenTelemetry collector, which sends it to CloudWatch. However, it is unable to send the logs as the timestamp is invalid:

> 2023-10-22T03:56:22.332Z	error	cwlogs@v0.82.0/pusher.go:90	discard log entry with invalid timestamp	{"kind": "exporter", "data_type": "metrics", "name": "awsemf", "error": "the log entry's timestamp is older than 14 days or more than 2 hours in the future", "LogEventTimestamp": "2095-11-12 21:49:28.488 +0000 UTC", "CurrentTime": "2023-10-22 03:56:22.332941764 +0000 UTC"}

### What did you expect to happen?

The log entry to be correctly timestamped.

### How can we reproduce it (as minimally and precisely as possible)?

1. Set up an OpenTelemetry collector (i.e. ADOT on EKS)
2. Set up EMQX, with OpenTelemetry configuration pointing to the above collector

### EMQX version

<details>

```console
$ ./bin/emqx_ctl broker
sysdescr  : EMQX
version   : 5.3.0
datetime  : 2023-10-22T04:11:04.088514452+00:00
uptime    : 4 days, 10 hours, 17 minutes, 10 seconds
```

</details>

### OS version

<details>

Using Docker Image with tag 5.3.

</details>

### Log files

<details>

</details>

**Comment by SergeTupchiy** [comment]
Hi, @singhbaljit 
Thanks for reporting this issue, I've pushed the fix linked to this ticket.

**Comment by singhbaljit** [comment]
@SergeTupchiy great!
