### ISSUE TITLE
Bridging between emqtt and AWS Iot

### ISSUE THREAD

**Issue by PiedPieper** [emqx/emqx#1181]
#### Environment

- OS: Ubuntu 14
- Erlang/OTP: 19.2
- EMQ: 2.2

#### Description

Has anyone bridged between emqtt and AWS IoT? AWS IoT is an Amazon GUI that allows you to configure an AWS broker on their website and protects it from external attacks. There is documentation on how to bridge between mosquitto and AWS Iot, but none for emqtt. Ideally I would like to forward all packets from my emqtt instance hosted locally to the AWS IoT instance and vice versa, but it seems like that may not be possible. Is there any other tool for this that is used ?

Thanks!

**Comment by pritstift** [comment]
👍 
I would also like to have that feature. The EMQ docs say you can bridge two EMQ brokers together. Would be great if i could bridge to any other kind of broker.

**Comment by emqplus** [comment]
@pritstift @PiedPieper Plan to support this feature in R2.3 or 2.4 Release

**Comment by PiedPieper** [comment]
@emqplus How are you implementing this ? I am going to start working on this tomorrow and I'd love some pointers on how to implement it. If I can get it done maybe I can save you some work. Is it all done in emqttd_bridge.erl?

**Comment by PiedPieper** [comment]
@emqplus Or else, when is R2.3/2.4 coming out?

**Comment by PiedPieper** [comment]
@emqplus  I created a bridge a few weeks ago, I can share it if you'd like - Right now it works but I am concerned about the concurrency connecting to AWS - I am using emqttd:subscribe to create multiple listeners sharing the local subscription on the EMQ side, but as of now I can't figure out how to share subscriptions with multiple processes on the AWS side. For example, If i use emqttc:start_link to connect multiple subscribing processes to AWS, all will get all messages on that topic. 

How have you solved this?

**Comment by PiedPieper** [comment]
@emqplus Is there any update on when this feature will be released?

**Comment by RaymondMouthaan** [comment]
@emqplus @Piedpieper is there any progress on this ? I would like to do more of less the same with cloudmqtt.

**Comment by emqplus** [comment]
@RaymondMouthaan Plan to support this feature in 2.4. We have to upgrade `emqttc` library to support MQTT5.0 first:)

**Comment by Marc-drouet** [comment]
> @emqplus I created a bridge a few weeks ago, I can share it if you'd like - Right now it works but I am concerned about the concurrency connecting to AWS - I am using emqttd:subscribe to create multiple listeners sharing the local subscription on the EMQ side, but as of now I can't figure out how to share subscriptions with multiple processes on the AWS side. For example, If i use emqttc:start_link to connect multiple subscribing processes to AWS, all will get all messages on that topic.
> 
> How have you solved this?

Hi PiedPiper, could you share with me how you have configured emqtt in order to bridge with IOT AWS, i'm trying to do it but no success :(

**Comment by PiedPieper** [comment]
@Marc-drouet I'm not able to share the code, but I created a very basic plugin with one dependency, [emqttc](https://github.com/emqtt/emqttc.git) and connected to AWS. For a certain range of topics on AWS, I subscribed and then published those to emqttd using emqttd:publish. For a certain range of topics on emqttd, I used emqttd:subscribe and any messages received i forwarded over emqttc:publish to AWS IoT.

**Comment by Marc-drouet** [comment]
> @Marc-drouet I'm not able to share the code, but I created a very basic plugin with one dependency, [emqttc](https://github.com/emqtt/emqttc.git) and connected to AWS. For a certain range of topics on AWS, I subscribed using emqttc:subscribe and then published messages received from AWS to emqttd using emqttd:publish. For a certain range of topics on emqttd, I used emqttd:subscribe and any messages received i forwarded over emqttc:publish to AWS IoT.

Ok, thanks, i will try this kind of solution.

**Comment by zhengyupan** [comment]
Hi,
Bridging emq to AWS IoT is supported in the newly release emqx 3.0. Please check out and have a try.

**Comment by Marc-drouet** [comment]
> Hi,
> Bridging emq to AWS IoT is supported in the newly release emqx 3.0. Please check out and have a try.

Hi zhengyupan

Hi know that but i have tried without success, 
i have filled the following lines in file: /etc/emqx/emqx.conf

lines:

               bridge.aws.cacertfile =
               bridge.aws.certfile =
               bridge.aws.keyfile =

but when i run :  /usr/sbin/emqx_ctl  bridges start aws

i got

RPC to emqx@127.0.0.1 error: {{tcp_closed,
                                  {gen_statem,call,
                                      [<10598.11969.0>,connect,infinity]}},
                              {gen_server,call,
                                  [emqx_bridge_aws,start_bridge]}}

Probably it's an error on my side but i have found no documention concerning bridge with AWS

Regards

**Comment by Marc-drouet** [comment]
Hello,

No one to share a working "emqx.conf" file for establishing a bridge with AWS ?

**Comment by saqib-cielo** [comment]
Emqx as a bridge with AWS Iot broker behaving unexpectedly(getting duplicate messages burst with any Qos level), normally happen when we start publishing messages with some pace, check all config params but no luck, did anyone came across similar issue.
