### ISSUE TITLE
using  mqtt.js mqtt.Client#publish()  loop sending, the server receives messages that are out of order

### ISSUE THREAD

**Issue by XxSuper** [emqx/emqx#11826]
### What happened?

using  mqtt.js mqtt.Client#publish()  loop sending, the server receives messages that are out of order

### What did you expect to happen?

Server receives server guarantees sequential reception

### EMQX version

<details>

```console
$ ./bin/emqx_ctl broker
# paste output here
```

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Log files

<details>

</details>

**Comment by id** [comment]
@XxSuper when you say "server", do you mean subscriber?
Could you share client code to help us reproduce the problem?

**Comment by XxSuper** [comment]
import * as mqtt from 'mqtt/dist/mqtt.min'
import Event from './event.js'
import Logger from './logger/Logger.js'
const logger = new Logger('mqtt')

const DEBUG = '__duix-debug'

window.DUIXDEBUG = (flag) => {
  if (flag === false) {
    sessionStorage.removeItem(DEBUG)
  } else {
    sessionStorage.setItem(DEBUG, true)
  }
}

class MqttClient extends Event {
  constructor(options = {}) {
    super()
    this.connected = false
    this.url = options.url
    this.username = options.username
    this.password = options.password
    this.reconnectPeriod = 1000  // 1s自动重连
    if (!this.url || !this.username || !this.password) {
      throw new Error('Signalling service initialization failed.')
    }
    this.client = null
    // 未发送的消息
    this.unsent = []
  }

  open() {
    this.unsent = []
    const { url, username, password, reconnectPeriod } = this
    const client = this.client = mqtt.connect(url, {
      username,
      password,
      reconnectPeriod,
      clientId: 'duixmqttjs_' + Math.random().toString(16).slice(2, 8),
      properties: {
        sessionExpiryInterval: 10 * 1000
      }
    })
    client.on('connect', () => {
      logger.info('Mqtt client connect')
      this.connected = true
      this.emit('connect')
      if (this.unsent.length > 0) {
        this.unsent.forEach(([topic, message]) => {
          this.publish(topic, message)
        })
        this.unsent = []
      }
    })
    client.on('message', (topic, message) => {
      if (sessionStorage.getItem(DEBUG)) {
        logger.info('Receive message', topic, message.toString())
      }
      this.emit('message', topic, message.toString())
    })
    client.on('reconnect', function () {
      logger.info('Client reconnect')
    })
    client.on('close', () => {
      logger.info('Client close')
      this.connected = false
    })
    client.on('disconnect', () => {
      logger.info('Client disconnect')
      this.connected = false
    })
    client.on('offline', () => {
      logger.info('Client offline')
      this.connected = false
    })
    client.on('error', () => {
      logger.info('Client error')
      this.connected = false
    })
    client.on('end', () => {
      logger.info('Client end')
      this.connected = false
    })
  }

  close() {
    this.client?.end()
    this.unsent = []
  }

  // 订阅topic
  subscribe(topic) {
    return new Promise(resolve => {
      if (!this.isConnected()) {
        resolve(false)
      }
      this.client.subscribe(topic, { qos: 2 }, function (error) {
        if (error) {
          logger.error(`Subscribe ${topic} error`)
          resolve(false)
          return
        }
        logger.info(`Subscribe ${topic} success`)
        resolve(true)
      })
    })

  }

  // 取消订阅
  unsubscribe(topic) {
    return new Promise(resolve => {
      this.client.unsubscribe(topic, { qos: 2 }, (error) => {
        if (error) {
          logger.warn(`Unsubscribe ${topic} error`)
          resolve(false)
          return
        }
        logger.info(`Unsubscribe ${topic} success`)
        resolve(true)
      })
    })
  }

  // 发布消息
  publish(topic, message) {
    if (this.isInit() && !this.isConnected()) {
      this.unsent.push([topic, message])
      return
    }
    if (sessionStorage.getItem(DEBUG)) {
      logger.info('publish message', topic, message.toString())
    }
    this.client.publish(topic, message, { qos: 2 })
  }

  isInit() {
    return !!this.client
  }

  isConnected() {
    return this.isInit() && this.connected
  }

  destroy() {
    this.close()
    this.connected = false
    this.url = ''
    this.username = ''
    this.password = ''
    this.client = null
    this.unsent = []
    super.destroy()
  }
}

export default MqttClient

**Comment by id** [comment]
@XxSuper I adapted your code to run it from command line with node. But I still don't understand how to reproduce your problem with out of order messages.

```
const mqtt = require('mqtt')

class MqttClient {
  constructor(options = {}) {
    this.connected = false
    this.url = options.url
    this.username = options.username
    this.password = options.password
    this.reconnectPeriod = 1000 // 1s自动重连
    if (!this.url || !this.username || !this.password) {
      throw new Error('Signalling service initialization failed.')
    }
    this.client = null
    // 未发送的消息
    this.unsent = []
  }

  open() {
    this.unsent = []
    const { url, username, password, reconnectPeriod } = this
    const client = this.client = mqtt.connect(url, {
      username,
      password,
      reconnectPeriod,
      clientId: 'duixmqttjs_' + Math.random().toString(16).slice(2, 8),
      properties: {
        sessionExpiryInterval: 10 * 1000
      }
    })
    client.on('connect', () => {
      console.info('Mqtt client connect')
      this.connected = true
      if (this.unsent.length > 0) {
        this.unsent.forEach(([topic, message]) => {
          this.publish(topic, message)
        })
        this.unsent = []
      }
    })
    client.on('message', (topic, message) => {
      if (sessionStorage.getItem(DEBUG)) {
        console.info('Receive message', topic, message.toString())
      }
    })
    client.on('reconnect', function () {
      console.info('Client reconnect')
    })
    client.on('close', () => {
      console.info('Client close')
      this.connected = false
    })
    client.on('disconnect', () => {
      console.info('Client disconnect')
      this.connected = false
    })
    client.on('offline', () => {
      console.info('Client offline')
      this.connected = false
    })
    client.on('error', (error) => {
      console.error(`Client error: ${error}`)
      this.connected = false
    })
    client.on('end', () => {
      console.info('Client end')
      this.connected = false
    })
  }

  close() {
    this.client?.end()
    this.unsent = []
  }

  // 订阅topic
  subscribe(topic) {
    return new Promise(resolve => {
      if (!this.isConnected()) {
        resolve(false)
      }
      this.client.subscribe(topic, { qos: 2 }, function (error) {
        if (error) {
          logger.error(`Subscribe ${topic} error: ${error}`)
          resolve(false)
          return
        }
        console.info(`Subscribe ${topic} success`)
        resolve(true)
      })
    })

  }

  // 取消订阅
  unsubscribe(topic) {
    return new Promise(resolve => {
      this.client.unsubscribe(topic, { qos: 2 }, (error) => {
        if (error) {
          logger.warn(`Unsubscribe ${topic} error: ${error}`)
          resolve(false)
          return
        }
        console.info(`Unsubscribe ${topic} success`)
        resolve(true)
      })
    })
  }

  // 发布消息
  publish(topic, message) {
    if (this.isInit() && !this.isConnected()) {
      this.unsent.push([topic, message])
      return
    }
    if (sessionStorage.getItem(DEBUG)) {
      console.info('publish message', topic, message.toString())
    }
    this.client.publish(topic, message, { qos: 2 })
  }

  isInit() {
    return !!this.client
  }

  isConnected() {
    return this.isInit() && this.connected
  }

  destroy() {
    this.close()
    this.connected = false
    this.url = ''
    this.username = ''
    this.password = ''
    this.client = null
    this.unsent = []
    super.destroy()
  }
}

const mqttClient = new MqttClient({url: "ws://127.0.0.1:8083/mqtt", username: "test", password: "test"});
mqttClient.open();
```
