### ISSUE TITLE
dashboard over view display wrong memory usage in emqx-v4.4.19

### ISSUE THREAD

**Issue by robertzhouxh** [emqx/emqx#11839]
### What happened?

dashboard over view display wrong memory usage

### What did you expect to happen?

should display right memory usage

### EMQX version

v4.4.19

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Log files

<details>

</details>

**Comment by id** [comment]
Hi @robertzhouxh. Could you provide more details?

**Comment by robertzhouxh** [comment]
![CleanShot 2023-10-30 at 20 19 20@2x](https://github.com/emqx/emqx/assets/6504502/c9ff0a1f-9399-4b23-89ec-e4c282464be6)

**Comment by robertzhouxh** [comment]
our memory only allocate 8g for each pod , the emqx-v4.3.11 has no such problem, when i update from  v4.3.11 to v4.4.19, the problem comes up !

**Comment by id** [comment]
@robertzhouxh it's a known issue, and unfortunately we do not have solution for this.
