### ISSUE TITLE
The connection of the apk packets played by uniapp is unstable and often disconnected

### ISSUE THREAD

**Issue by ivanbearcat** [emqx/emqx#11847]
### What happened?

The connection of the apk packets played by uniapp is unstable and often disconnected

### What did you expect to happen?

Connection stabilization

### EMQX version

5.0.0

### OS version

Centos 8.5

### Log files

<details>

</details>

**Comment by id** [comment]
@ivanbearcat could you provide more information about your setup and attach emqx logs?
