### ISSUE TITLE
Mqtt automatic reconnection and subscription

### ISSUE THREAD

**Issue by kinghuisFFFF** [emqx/emqx#11893]
### What would you like to be added or enhanced?

Mqtt automatic reconnection and subscription, hoping to achieve automation without user intervention

### Why is this needed?

Mqtt automatic reconnection and subscription, hoping to achieve automation without user intervention

**Comment by ieQu1** [comment]
This issue is twofold:

1) Automatic reconnection should be handled by the client library. 

2) EMQX supports automatic subscription: https://docs.emqx.com/en/enterprise/latest/messaging/mqtt-auto-subscription.html#auto-subscribe 
This feature is exclusive to the Enterprise Edition.
