### ISSUE TITLE
Repeated errors on the EMQx core pods: "[error] crasher: initial call: mnesia_rocksdb:init/1 registered_name: [], error: {{badmatch,{error,{db_open,"IO error: While lock file: /opt/emqx/data/mnesia/emqx@emqx-core-79654b56cb-0.emqx-headless.ns.svc.cluster.local/emqx_ds_session-_tab.extrdb/LOCK: Resource temporarily unavailable"

### ISSUE THREAD

**Issue by sivarama-p-raju** [emqx/emqx#11934]
### What happened?

We had an issue with EMQx core pods during the weekend as part of which they were restarted. On restart, all EMQx core pods came up and we could connect to the EMQx dashboard and everything looked fine.

However, when looking at the logs on the Core pods (3 replicas), 2 of the core pods had the same error message repeating every 2 seconds, mentioned below:

`"[error] crasher: initial call: mnesia_rocksdb:init/1 registered_name: [], error: {{badmatch,{error,{db_open,"IO error: While lock file: /opt/emqx/data/mnesia/emqx@emqx-core-79654b56cb-0.emqx-headless.ns.svc.cluster.local/emqx_ds_session-_tab.extrdb/LOCK: Resource temporarily unavailable"`

The 3rd replica did not had this log.

On looking at the filesystem, the LOCK file is existent on all 2 pods with the errors. However, on those two pods, I could see 6 million and 5 million "LOG.old.xxxxx" files respectively.

Whereas, on the 3rd pod, which does not have the errors, had only two "LOG.old.xxxxx" files.

On the 2 pods, with the errors, when I look at one of the "LOG.old.xxxxx" file, I see the below messages:

```
2023/11/13-07:23:57.010266 304 DMutex implementation: pthread_mutex_t
2023/11/13-07:23:57.011301 304 [WARN] [db/db_impl/db_impl_open.cc:2073] DB::Open() failed: IO error: While lock file: /opt/emqx/data/mnesia/emqx@emqx-core-79654b56cb-2.emqx-headless.ns.svc.cluster.local/emqx_ds_session-_tab.extrdb/LOCK: Resource temporarily unavailable
2023/11/13-07:23:57.011333 304 [db/db_impl/db_impl.cc:496] Shutdown: canceling all background work
2023/11/13-07:23:57.011360 304 [db/db_impl/db_impl.cc:704] Shutdown complete
```

Need help to solve this issue.

### What did you expect to happen?

On the 3rd pod, without these errors in its logs, when I look at the "LOG.old.xxxxxx" file, I see the below:

```
2023/10/26-23:07:28.185520 302 Fast CRC32 supported: Not supported on x86
2023/10/26-23:07:28.185522 302 DMutex implementation: pthread_mutex_t
2023/10/26-23:07:28.193524 302 [db/db_impl/db_impl_open.cc:313] Creating manifest 1
2023/10/26-23:07:28.202983 302 [db/version_set.cc:5530] Recovering from manifest file: /opt/emqx/data/mnesia/emqx@emqx-core-79654b56cb-1.emqx-headless.ns.svc.cluster.local/emqx_ds_session-_tab.extrdb/MANIFEST-000001
2023/10/26-23:07:28.203687 302 [db/column_family.cc:631] --------------- Options for column family [default]:
2023/10/26-23:07:28.203692 302               Options.comparator: leveldb.BytewiseComparator
2023/10/26-23:07:28.203694 302           Options.merge_operator: None
2023/10/26-23:07:28.203695 302        Options.compaction_filter: None
2023/10/26-23:07:28.203696 302        Options.compaction_filter_factory: None
2023/10/26-23:07:28.203698 302  Options.sst_partitioner_factory: None
2023/10/26-23:07:28.203699 302         Options.memtable_factory: SkipListFactory
2023/10/26-23:07:28.203700 302            Options.table_factory: BlockBasedTable
2023/10/26-23:07:28.203723 302            table_factory options:   flush_block_policy_factory: FlushBlockBySizePolicyFactory (0x7f558803f120)
```

I would expect the same to happen on the other two EMQx core's, instead of the below:

```
2023/11/13-07:23:57.010265 304 Fast CRC32 supported: Not supported on x86
2023/11/13-07:23:57.010266 304 DMutex implementation: pthread_mutex_t
2023/11/13-07:23:57.011301 304 [WARN] [db/db_impl/db_impl_open.cc:2073] DB::Open() failed: IO error: While lock file: /opt/emqx/data/mnesia/emqx@emqx-core-79654b56cb-2.emqx-headless.ns.svc.cluster.local/emqx_ds_session-_tab.extrdb/LOCK: Resource temporarily unavailable
2023/11/13-07:23:57.011333 304 [db/db_impl/db_impl.cc:496] Shutdown: canceling all background work
2023/11/13-07:23:57.011360 304 [db/db_impl/db_impl.cc:704] Shutdown complete
```

I would also not expect those huge number of "LOG.old.xxxxxx" files on the pods (6 million and 5 million files respectively).

### How can we reproduce it (as minimally and precisely as possible)?

I am not sure how to reproduce this issue.

### EMQX version

<details>

```console
$ ./bin/emqx_ctl broker
sysdescr  : EMQX
version   : 5.1.6
datetime  : 2023-11-13T09:52:18.537575482+00:00
uptime    : 1 days, 1 hours, 56 minutes, 2 seconds
```

</details>

### OS version

<details>

```console
# On the EMQx core container
$ cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
$ uname -a
Linux emqx-core-79654b56cb-0 5.4.0-96-generic #109-Ubuntu SMP Wed Jan 12 16:49:16 UTC 2022 x86_64 GNU/Linux
```

```Console
# Kubernetes version
v1.24.9
# CNI
containerd://1.6.15
# Kubernetes node OS version
$ cat /etc/os-release
NAME="Ubuntu"
VERSION="20.04.3 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.3 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
$ uname -a
Linux node1 5.4.0-96-generic #109-Ubuntu SMP Wed Jan 12 16:49:16 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
#
```
</details>

### Log files

<details>

</details>

**Comment by ieQu1** [comment]
Hello,

I see that the node tries to open `emqx_ds_session` table, which is NOT supposed to be created or opened. Have you set `EMQX_persistent_session_store__ds` option to `true` or enabled this option somehow else? It can be checked by running `emqx_persistent_message:is_store_enabled().` command in the EMQX console. It must return `false`. 
This undocumented option enables a feature that is currently under active development and MUST NOT be enabled.

**Comment by ieQu1** [comment]
Hello,

Sorry, my previous message was based on a wrong version of EMQX. Please disregard it.
It looks like another process already locked the table. Can you make sure that only one EMQX process is running on the kubernetes node? If so, it should be ok to remove the LOCK file.
