### ISSUE TITLE
recon bin_leak is not working

### ISSUE THREAD

**Issue by amitjain-lr** [emqx/emqx#1193]
### Environment 
- OS: Ubuntu 16.04.2 LTS
- Erlang/OTP: R20/9.0
- EMQ: 2.2

### Description 
I'm running EMQ node with above environment. To check for the binary leaks, I ran recon:bin_leak/1 and it's throwing me _badarith_ error. Please help me resolve this issue.

```
bin/emqttd_ctl recon bin_leak
Reason:badarith, get_stacktrace:[{recon,'-bin_leak/1-lc$^1/1-1-',1,
                                     [{file,"src/recon.erl"},{line,324}]},
                                 {emq_recon_cli,cmd,1,
                                     [{file,"src/emq_recon_cli.erl"},
                                      {line,45}]},
                                 {emqttd_ctl,run,1,
                                     [{file,"src/emqttd_ctl.erl"},{line,74}]},
                                 {rpc,'-handle_call_call/6-fun-0-',5,
                                     [{file,"rpc.erl"},{line,197}]}]
RPC to node@ecommerce error: badarith
```

**Comment by lukebakken** [comment]
What version of `recon` is being used? It appears that [this PR](https://github.com/ferd/recon/pull/54) may have fixed this issue.

**Comment by Gilbert-Wong** [comment]
Please update EMQ to latest version and  run recon:bin_leak/1  again.
