### ISSUE TITLE
Topic Subscribe Gateway COAP does not accept QOS parameters

### ISSUE THREAD

**Issue by alandinh** [emqx/emqx#12031]
### What happened?

When I subscribe to a coap gateway topic on emqx and pass the QOS parameter. Then I went to the UI and went to the Subscriptions section to check and saw that the qos parameter was always equal to 1
Note: I am using node-coap library

### What did you expect to happen?

How do I make emqx receive the correct qos parameter that I pass up via parameter

### EMQX version

<details>

sysdescr : EMQX
version : 5.3.0

</details>

### OS version

<details>

Window 10

</details>

### Log files

<details>

</details>

**Comment by SergeTupchiy** [comment]
Hi @alandinh,
Thanks for reporting this issue, I've pushed the fix for it.
