### ISSUE TITLE
setting for node.name take no effect in emqx.conf when docker deployment 

### ISSUE THREAD

**Issue by szylmzs** [emqx/emqx#12050]
### What happened?

node.name take no effect when docker deployment until emqx restart 

below is settings in emqx.conf
![图片](https://github.com/emqx/emqx/assets/5236065/cf9092b6-b222-40b3-8fc3-2766107e8962)

below is console info when emqx start
![图片](https://github.com/emqx/emqx/assets/5236065/bd22b73b-856f-4c18-be13-8629ca952afb)

and below is console info when emqx restart from console
![图片](https://github.com/emqx/emqx/assets/5236065/9c4562db-365b-413a-a3d0-7ca9283c53f5)

### What did you expect to happen?

node.name should take effect

### EMQX version

<details>

```console
$ ./bin/emqx_ctl broker
# paste output here
sysdescr  : EMQ X Broker
version   : 4.2.1
uptime    : 17 hours, 4 minutes, 36 seconds
datetime  : 2023-11-29 01:51:44
```

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
$ uname -a
Linux deyi 3.10.0-1062.4.1.el7.x86_64 #1 SMP Fri Oct 18 17:15:30 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```

</details>

### Log files

<details>

</details>

**Comment by SergeTupchiy** [comment]
Hi @szylmzs, 
It's not possible to change node name without node restart.
Additionally, EMQX 4.4.1 is quite old, I'd recommend to consider upgrading, at least to the latest 4.4.x.

**Comment by szylmzs** [comment]
> Hi @szylmzs, It's not possible to change node name without node restart. Additionally, EMQX 4.4.1 is quite old, I'd recommend to consider upgrading, at least to the latest 4.4.x.

thanks, after that I found specifying docker env could resole this problem
and it is stable when using current version, can i upgrade directly using docker pull 4.4.x without other settings?

**Comment by SergeTupchiy** [comment]
@szylmzs, 
Unfortunately, I think it's not possible to smoothly upgrade from 4.2.1 to 4.4 or even 4.3...
Please take a look at these instructions:
- https://www.emqx.io/docs/en/v4.3/changes/upgrade-4.3.html
- https://www.emqx.io/docs/en/v4.4/changes/upgrade-4.4.html

**Comment by szylmzs** [comment]
> @szylmzs, Unfortunately, I think it's not possible to smoothly upgrade from 4.2.1 to 4.4 or even 4.3... Please take a look at these instructions:
> 
>     * https://www.emqx.io/docs/en/v4.3/changes/upgrade-4.3.html
> 
>     * https://www.emqx.io/docs/en/v4.4/changes/upgrade-4.4.html

thanks
