### ISSUE TITLE
Clustered Stopped nodes on running nodes

### ISSUE THREAD

**Issue by GibliX** [emqx/emqx#1206]
I have 3 nodes all hosted on AWS.
When I run the `emqttd_ctl cluster status` on each of the I get different result..

Host A output:
```
Cluster status: [{running_nodes,['HOST B',
                                 'HOST A']},
                 {stopped_nodes,['HOST C']}]
```

Host C output:
```
Cluster status: [{running_nodes,['HOST B',
                                 'HOST A',
                                 'HOST C']}]
```

Host B output:
```
Cluster status: [{running_nodes,['HOST C',
                                 'HOST B']},
                 {stopped_nodes,['HOST A']}]
```

On all nodes I ran `sudo service emqttd status` and got
```
pong
emqttd is running
```

The cluster seems to be up and replicating the topics..

**Comment by emqplus** [comment]
Partial network partition or firewall issue between Host A and C. Please try to grep "inconsistent_database event" logs/*  on Host A or C

**Comment by GibliX** [comment]
Output from HOST C

```
12:31:10.250 [error] Unexpected Info: {mnesia_system_event,{inconsistent_database,running_partitioned_network,'**HOST A**'}}
12:31:10.250 [critical] Mnesia inconsistent_database event: running_partitioned_network, '**HOST A**'
12:31:10.250 [error] Mnesia('**HOST C**'): ** ERROR ** mnesia_event got {inconsistent_database, running_partitioned_network, '**HOST A**'}
12:31:14.693 [error] Unexpected Info: {mnesia_system_event,{inconsistent_database,running_partitioned_network,'**HOST B**'}}
12:31:14.693 [critical] Mnesia inconsistent_database event: running_partitioned_network, '**HOST B**'
12:31:14.693 [error] Mnesia('**HOST C**'): ** ERROR ** mnesia_event got {inconsistent_database, running_partitioned_network, '**HOST B**'}
07:44:31.680 [error] Mnesia('**HOST C**'): ** ERROR ** mnesia_event got {inconsistent_database, starting_partitioned_network, '**HOST B**'}
07:44:31.680 [error] Mnesia('**HOST C**'): ** ERROR ** mnesia_event got {inconsistent_database, starting_partitioned_network, '**HOST A**'}
```

**Comment by emqplus** [comment]
@GibliX Are all the nodes in the same VPC?

**Comment by GibliX** [comment]
@emqplus Nope,
They are on different regions..

**Comment by GibliX** [comment]
Additional tests were made.
As I said,
I have 3 servers.
X,Y are in the same region.
Z is on a different region.

X can see that all nodes are running fine (clustered).
Y can see that X is running fine and Z is not stoped.
Z can see that X is running fine and Y is stopped.

When I publish to X, other nodes get the publish replicated.
When I publish to Y it is also replicated to all nodes.
When I publish to Z it also gets published to al nodes.

When I take X down, it leaves me with Y and Z which see each other as stopped.
Now, publishes does not work and does not replicate.
This means that in the first test, X was the bridge between Y and Z and when I took him down, there is no connection between Y and Z.

If I restart the emitted service on Y or Z then they can again see each other (until the next time they stop communicating).

Any conclusions from what I wrote up here?

**Comment by GibliX** [comment]
Any ideas guys?
It's blocking me from using this product :-\

**Comment by zhengyupan** [comment]
Hi @GibliX ,
The nodes in a cluster must be in a same VPC. Otherwise there could be inconsistency between the nodes.
If you are deploying application over regions please consider using bridge to connect the clusters in different regions.

**Comment by pantongren** [comment]
@zhengyupan If there are only two nodes in different region, how to cluster?

**Comment by turtleDeng** [comment]
@pantongren Does not support offsite  two nodes clusters.
