### ISSUE TITLE
Unable to startup 

### ISSUE THREAD

**Issue by zhaozusong** [emqx/emqx#12069]
### What happened?

WARNING: Using libs from '/root/emqx/dynlibs' due to missing from the OS.
ERROR: EMQX 5.0.21 using node name 'emqx@192.168.111.96' failed 120 probes.
ERROR: emqx@192.168.111.96 node is started, but failed to complete the boot sequence in time.
Please collect the logs in /root/emqx/log and report a bug to EMQX team at https://github.com/emqx/emqx/issues/new/choose
Shutting down emqx@192.168.111.96 from to_erl pipe.
Attaching to //root/emqx/data/root_erl_pipes/emqx@192.168.111.96/erlang.pipe.10 (^D to exit)

### What did you expect to happen?

正常启动

### EMQX version

<details>

```console
$ ./bin/emqx_ctl broker
# paste output here
```

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here
```

</details>

### Log files

<details>

</details>

**Comment by JimMoen** [comment]
Hi there! Thanks for reaching out.

I noticed that the issue you opened is missing some crucial details that would help us assist you better. Could you please provide information such as operating system version, installation method, and any relevant logs(or startup output by using command line: `./bin/emqx console`)?

Including these details will significantly expedite the troubleshooting process, allowing us to pinpoint the issue and provide a more effective solution. Your cooperation in providing this information is greatly appreciated!
