### ISSUE TITLE
EMQX bridge

### ISSUE THREAD

**Issue by thgebull** [emqx/emqx#12086]
### What would you like to be added or enhanced?

Dear Developer crew, 
I have one issues, about emqx bridge. 
 I doesn't know, how auto create table in Database, if connect a new iot and have uniq clientid.
Database Tdengine support autocreating tables if je stables.

### Why is this needed?

INSERT INTO iotbull.$clientid VALUES (
 now,
 '${clientid}',
  ${payload.rssi},
  ${payload.temperature}
)

**Comment by lafirest** [comment]
@thgebull 
Could you please clarify your situation, I'm not sure if my understanding is correct. You can manually create table or use the automatic mechanism, the bridge is not depend on how the table is created.
