### ISSUE TITLE
Axios Call Api Error By Cors

### ISSUE THREAD

**Issue by huynhttdev** [emqx/emqx#12088]
### What happened?

I use axios to call api as the docs mentioned, but it failed with cors. 
It is just working at postman.

### What did you expect to happen?

Solution for call api without cors error.

### EMQX version

<details>
v5

```console
$ ./bin/emqx_ctl broker
# paste output here
```

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here
```

</details>

### Log files

<details>

</details>

**Comment by lafirest** [comment]
@huynhttdev 
You need to set the `dashboard.cors` to `true`, you can find details at [here](https://www.emqx.io/docs/en/latest/configuration/configuration-manual.html).

**Comment by huynhttdev** [comment]
How can i find file config bro? @lafirest

**Comment by huynhttdev** [comment]
I had solution for it by update cors through API. Thanks @lafirest !

**Comment by windycloud** [comment]
@lafirest After set dashboard.cors is true, the error still persists because the browser makes a preflight request with the OPTIONS method, and it seems that this method is not supported.

**Comment by id** [comment]
@ysfscream could you assist here?

**Comment by huynhttdev** [comment]
> @huynhttdev did you find a solution for this problem ? if you find one what is it ?

I created nodejs demo project. In this project, I called to EMQX API without setup cors middleware. I fixed this by the following code:

`
const cors = require("cors");

app.use(cors());
`

**Comment by ysfscream** [comment]
I wasn't able to replicate this issue. After obtaining the API key, I requested the remote server from my local setup, and everything worked as expected. Here is an example of my code for reference.

<img width="1337" alt="image" src="https://github.com/emqx/emqx/assets/21299158/44bceaad-516d-4ab8-b257-e9654e8b5bfb">

Given the uncertainties regarding the specific project environment, if you are making Axios requests to the API within a browser-based frontend project, you might need to configure a reverse proxy to circumvent the CORS issue. This approach is a standard solution, especially when frontend applications need to communicate directly with backend services. I hope this information is helpful to you.

<img width="556" alt="image" src="https://github.com/emqx/emqx/assets/21299158/09ec7df7-5657-44ac-a4d3-9f2094f0d964">
