### ISSUE TITLE
webhook插件推送HEX内容失败

### ISSUE THREAD

**Issue by bbdlg** [emqx/emqx#12087]
### What happened?

原始hex内容： 【01 02 41 42 81 82】
通过webhook接收到的内容：..... "payload":"\u0001\u0002AB\ufffd", ....
解析后的hex内容：【01 02 41 42 EF BF BD】

### What did you expect to happen?

原始内容和接收到的内容应该都是 【01 02 41 42 81 82】

### Anything else we need to know?

通过反复测试，当hex字节大于128时，将会遇到编码错误的问题，导致出现 \ufffd 类似的字符。

### EMQX version

<details>

```console
$ ./bin/emqx_ctl broker
# paste output here
```

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here
```

</details>

### Log files

<details>

</details>

**Comment by lafirest** [comment]
@bbdlg 
Could you please provide more details, like the rule content you are using and  some test sample
