### ISSUE TITLE
同一主题消息推送多个webhook会导致消息传输过慢

### ISSUE THREAD

**Issue by pinzi** [emqx/emqx#12159]
### What happened?

同一个主题消息，创建了A,B,C三条规则，每条规则都是将该主题数据推送到不同的webhook地址。
当只启用规则A时，速度正常；当启用A,B,C时会发现A速度变慢了。
![image](https://github.com/emqx/emqx/assets/3843463/0f25d958-4850-44fb-93ff-c28433cfb599)

### What did you expect to happen?

三条规则所推送的数据速度应该是一样迅速，互不干扰的。

### EMQX version

4.4.16

### OS version

Windows Server 2022 Datacenter  21H2

### Log files

<details>

</details>

**Comment by qzhuyan** [comment]
how does the rules look like?

**Comment by zhongwencool** [comment]
You can avoid this issue by creating multiple connectors with the same configuration.
