### ISSUE TITLE
Build issue on Windows 7 for x86 architecture

### ISSUE THREAD

**Issue by vinayxbox** [emqx/emqx#1217]
#### Environment

- OS: Windows 7 x64
- Erlang/OTP: 20
- EMQ: 2.0,2.2,2.3

#### Description

I tried to build eMQTT to be installed on Windows 7 x86 system.

I installed Erlang OTP 20.0 for x86.

I installed MSYS2 for x86.

After that i tried this 

git clone -b windows https://github.com/emqtt/emqttd-relx.git

cd emqttd-relx && make

I am getting build error and with this request i have attached the erl_crash.dump logs also.

[erl_crash.dump.txt](https://github.com/emqtt/emqttd/files/1246764/erl_crash.dump.txt)

Below is the console output

$ make
 DEP    goldrush
make[1]: Entering directory '/home/Z0031CDA/emqttd-relx/.erlang.mk/rebar'
./bootstrap
escript: exception error: no match of right hand side value "Could Not Find C:\\msys32\\home\\Z0031CDA\\emqttd-relx\\.erlang.mk\\rebar\\ebin\\rebar.beam\r\n"
make[1]: *** [Makefile:12: all] Error 127
make[1]: Leaving directory '/home/Z0031CDA/emqttd-relx/.erlang.mk/rebar'
/home/Z0031CDA/emqttd-relx
{"init terminating in do_boot",{undef,[{rebar_utils,wordsize,[],[]},{erl_eval,do_apply,6,[{file,"erl_eval.erl"},{line,670}]},{erl_eval,expr,5,[{file,"erl_eval.erl"},{line,228}]},{erl_eval,expr,5,[{file,"erl_eval.erl"},{line,229}]},{erl_eval,expr_list,6,[{file,"erl_eval.erl"},{line,878}]},{erl_eval,expr,5,[{file,"erl_eval.erl"},{line,422}]},{erl_eval,exprs,5,[{file,"erl_eval.erl"},{line,122}]},{init,start_it,1,[{file,"init.erl"},{line,1097}]}]}}
init terminating in do_boot ({undef,[{rebar_utils,wordsize,[],[]},{erl_eval,do_apply,6,[{_},{_}]},{erl_eval,expr,5,[{_},{_}]},{erl_eval,expr,5,[{_},{_}]},{erl_eval,expr_list,6,[{_},{_}]},{erl_eval,exp

Crash dump is being written to: erl_crash.dump...done
 DEP    emqttd
 DEP    emq_modules
 DEP    emq_dashboard
 DEP    emq_retainer
 DEP    emq_recon
 DEP    emq_reloader
 DEP    emq_auth_clientid
 DEP    emq_auth_username
 DEP    emq_auth_ldap
 DEP    emq_auth_http
 DEP    emq_auth_mysql
 DEP    emq_auth_pgsql
 DEP    emq_auth_redis
 DEP    emq_auth_mongo
 DEP    emq_sn
 DEP    emq_coap
 DEP    emq_stomp
 DEP    emq_plugin_template
 DEP    emq_web_hook
 DEP    emq_lua_hook
 DEP    emq_auth_jwt
 DEP    emq_lwm2m
make[1]: Entering directory '/home/Z0031CDA/emqttd-relx/deps/goldrush'
make[1]: *** No targets.  Stop.
make[1]: Leaving directory '/home/Z0031CDA/emqttd-relx/deps/goldrush'
make: *** [erlang.mk:312: deps] Error 2

Can anybody help me in building emqtt for Windows7 x86 ?

**Comment by huangdan** [comment]
@vinayxbox  Current workarounds, you can try it:
```
1.cd .erlang.mk\rebar
2.touch ebin/rebar.beam
3.run bootstrap.bat
```

**Comment by emqplus** [comment]
@vinayxbox Please try to build the rebar manually:
```
cd .erlang.mk\rebar
touch ebin/rebar.beam
run bootstrap.bat
```
Notice that EMQ should not be deployed on Windows in production.

**Comment by vinayxbox** [comment]
@huangdan @emqplus  Thanks for the help.Build is successful after that.

@emqplus  So Windows emqtt  broker is not good for production ?
