### ISSUE TITLE
[Dashboard] Replicant Connection Number is Wrongly Displayed

### ISSUE THREAD

**Issue by TxMat** [emqx/emqx#12177]
### What happened?

I'm running a 4 node cluster with etcd on aws ECS and for unknown reason the connection number on the replica node is not always going down on a client disconnection
![image](https://github.com/emqx/emqx/assets/46858765/b6fce652-4785-4051-abd5-62a11fc08fa3)

![image](https://github.com/emqx/emqx/assets/46858765/9cadb5a5-483d-4aae-93e5-d308e41a81e9)

### What did you expect to happen?

The connection number to mirror the real one from the node

### How can we reproduce it (as minimally and precisely as possible)?

The error appeared by letting the cluster run for more than one day and connecting / disconnecting a large amount of client

### Anything else we need to know?

i'm using the following exhooks to manage the connections
![image](https://github.com/emqx/emqx/assets/46858765/8ae1d0be-4e08-4f14-ae19-a3815d529031)

### EMQX version

<details>

```console
$ ./bin/emqx_ctl broker
sysdescr  : EMQX
version   : 5.3.1
datetime  : 2023-12-15T08:45:12.925914183+00:00
uptime    : 2 days, 22 hours, 27 minutes, 34 seconds
```

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
$ uname -a
Linux ip-172-31-60-241.eu-west-2.compute.internal 5.10.198-187.748.amzn2.x86_64 #1 SMP Tue Oct 24 19:49:54 UTC 2023 x86_64 GNU/Linux
```

</details>

### Log files

<details>
Replicant Node Dump :
[node_dump_20231215_084501.tar.gz](https://github.com/emqx/emqx/files/13683340/node_dump_20231215_084501.tar.gz)
</details>

**Comment by thalesmg** [comment]
Hi @TxMat .

Do you perhaps mean that you expected "Connections" and "Live Connections" to be the same value?  For example, from your screenshots, did you expect the "Connections" field in the dashboard overview to display 5?

**Comment by TxMat** [comment]
Hi,

In a way yes, but I am a bit confused on what to expect because 2 of the core nodes were also connected to the Load Balancer and didn't suffer the same bug (or feature ?). Also the fact that sometimes the "connection" value decrements on a client disconnect and sometimes not is adding to the confusion

**Comment by thalesmg** [comment]
"All Connections" in the dashboard include also persistent sessions (i.e., clean start = false), even if the clients are disconnected.

Does "Live Connection" match what you expect?

**Comment by TxMat** [comment]
Oh okay thanks for the clarification, in that case how should I handle disconnection for the client to be "removed" from the persistent session ? I thought that not making a clean start resumes the current session if they were one or creates a new one if none was found.

Yes the live connection value is working as expected.

**Comment by thalesmg** [comment]
If you don't want clients to have sessions, you may set clean_start = true and `Session-Expiry-Interval` to 0, when using MQTT protocol v5, or just clean start = true when using older MQTT protocols: 

https://docs.emqx.com/en/enterprise/v5.3/deploy/cluster/introduction.html#session-across-nodes
