### ISSUE TITLE
5.3.2无法启动

### ISSUE THREAD

**Issue by 786744873** [emqx/emqx#12218]
### What happened?

执行`emqx start` 命令，报无法启动，报以下错误
```
ERROR: /usr/lib/emqx/erts-13.2.2/bin/beam.smp: error while loading shared libraries: libtinfo.so.6: cannot open shared object file: No such file or directory
ERROR: Please ensure it is running on the correct platform:
ERROR: arch: "x86_64-pc-linux-gnu"
wordsize: 64
os: "el8"
erlang: "25.3.2-2"
elixir: "none"
relform: "rpm"
ERROR: Version=5.3.2
ERROR: Required dependencies: openssl-1.1.1 (libcrypto), libncurses and libatomic1
```

### What did you expect to happen?

5.3.2无法启动在阿里云linux服务器上无法启动

### EMQX version

5.3.2

**Comment by id** [comment]
@786744873 which exactly package have you installed? Could you share a link?

**Comment by 786744873** [comment]
> @786744873 which exactly package have you installed? Could you share a link?

wget https://www.emqx.com/zh/downloads/broker/5.3.2/emqx-5.3.2-el8-amd64.rpm
sudo yum install emqx-5.3.2-el8-amd64.rpm -y

然后执行下方的命令，无法启动
emqx start

**Comment by id** [comment]
@786744873 try this one instead: https://www.emqx.com/zh/downloads/broker/5.3.2/emqx-5.3.2-el7-amd64.rpm

**Comment by 786744873** [comment]
ok. thanks
