### ISSUE TITLE
日志追踪日志无法删除

### ISSUE THREAD

**Issue by 786744873** [emqx/emqx#12229]
### What happened?

![image](https://github.com/emqx/emqx/assets/24601648/a484b750-60e6-4c1a-8aae-f5c93418ccbe)

### What did you expect to happen?

日志追踪菜单页面内点击删除，数字类型无法删除

### EMQX version

v5.3.2

### OS version

centos7

**Comment by zhongwencool** [comment]
我试了下，通过 HTTP API（dashboard） 创建不了纯数字的9886名称的 trace，
  好奇你是如何创建出来的呀？

**Comment by 786744873** [comment]
我之前是使用的5.2.0版本，可以创建，前几天升级成了5.3.2版本后，无法删除。是否可以升级下策略，创建时不允许创建纯数字的名称，删除不受限制。

**Comment by zhongwencool** [comment]
感谢提议。我们安排一下在 5.5.0 里面做。
如果你在当前的版本删除它，可以使用命令行来做删除：
```
./bin/emqx ctl traces delete 7890
```

**Comment by 786744873** [comment]
感谢支持，祝EMQ发展的越来越好。💪
