### ISSUE TITLE
EMQX docker environment variables of dashboard default username and password ignores `#` and its following characters.

### ISSUE THREAD

**Issue by Yavathar** [emqx/emqx#12231]
### What happened?

I set my emqx container's default dashboard password to `password12#45` when I ran emqx.
```
$ docker run -d --name emqx -p 18083:18083 -e EMQX_DASHBOARD__DEFAULT_PASSWORD="password12#45" emqx/emqx
```

The environment variable had a correct value in the container.
```
$ docker exec emqx env | grep PASSWORD
EMQX_DASHBOARD__DEFAULT_PASSWORD=password12#45
```

When I tried to log into emqx dashboard, `http://localhost:18083`, with the username `admin` and the password `password12#45`, it failed.

![image](https://github.com/emqx/emqx/assets/20412383/5facbce2-15db-44fc-be8b-fa16e6b28994)

But, if I tries it with the password `password12`, which I remove `#` and its following letters `45`, it succeeds.

![image](https://github.com/emqx/emqx/assets/20412383/8b002a93-c46f-4b77-abda-97f48d01b1d8)

> The environment variable `EMQX_DASHBOARD__DEFAULT_USERNAME` also has the same issue.

### What did you expect to happen?

I expected to set emqx dashboard's default password to `password12#45`.

### EMQX version

<details>

```console
emqx@c7b342cd0d06:/opt/emqx$ ./bin/emqx_ctl broker
sysdescr  : EMQX
version   : 5.4.0
datetime  : 2023-12-26T06:13:58.860957295+00:00
uptime    : 9 minutes, 1 seconds
emqx@c7b342cd0d06:/opt/emqx$```

</details>


### OS version

<details>

```console
Sonoma 14.1.2 on Macbook Pro 16-inch, 2029
```

</details>

### Log files

<details>

</details>

**Comment by zhongwencool** [comment]
`# ` is is explain for comment in hocon config file.
try to use `-e EMQX_DASHBOARD__DEFAULT_PASSWORD="\"password12#45\""`

**Comment by Yavathar** [comment]
> `# ` is is explain for comment in hocon config file. try to use `-e EMQX_DASHBOARD__DEFAULT_PASSWORD="\"password12#45\""`

It works!
Many thanks.
