### ISSUE TITLE
emqx使用static集群报连接

### ISSUE THREAD

**Issue by z499738316** [emqx/emqx#12239]
### What happened?

我有三台虚拟机  172.16.0.61，172.16.0.62，172.16.0.63  每台都安装了docker
分别在三台部署emqx  ，使用的是static  但是日志一致报
![image](https://github.com/emqx/emqx/assets/37020005/f4e03013-96d2-45fb-9d5d-337131fe2303)
在面板界面也看不到节点信息
![image](https://github.com/emqx/emqx/assets/37020005/775abe30-6761-4daa-837c-cfdea78b51a6)

这个是配置信息
![image](https://github.com/emqx/emqx/assets/37020005/6b2470a3-c52e-40f2-bc4a-f6d837ca0662)

### What did you expect to happen?

希望能集群成功

### EMQX version

![image](https://github.com/emqx/emqx/assets/37020005/cb7b9bf7-a94b-494d-8662-aca02a973404)

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here
```

</details>

### Log files

<details>

</details>

**Comment by z499738316** [comment]
有个图片错了
![image](https://github.com/emqx/emqx/assets/37020005/9d4149bc-a845-4002-ba76-a5b85b13f30c)

**Comment by id** [comment]
@z499738316 try to add `network_mode: "host"` parameter in your compose specification.
