### ISSUE TITLE
crash logs

### ISSUE THREAD

**Issue by roysG** [emqx/emqx#12230]
### What happened?

Hi,
Last night we had crash in 3/4 nodes for a minute

What is the steps to find the problem, where is the files logs of crash? 

Version: 4.3.5

### What did you expect to happen?

To make easier life in detect problems in node

### EMQX version

<details>

sysdescr  : EMQ X Broker
version   : 4.3.5
uptime    : 5 hours, 58 minutes, 8 seconds
datetime  : 2023-12-26 05:23:50

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here
```

</details>

### Log files

<details>

</details>

**Comment by id** [comment]
Hi @roysG.

Please check out documentation for information about log files, as well as other troubleshooting tips: https://www.emqx.io/docs/en/v4.3/getting-started/directory.html.

I will close the issue since 4.3 version family has reached End-of-life last year.
