### ISSUE TITLE
when the etcd cluster down for  1-2 minutes, then recover, emqx experiences an exception. and cannot recover

### ISSUE THREAD

**Issue by elysian-gc** [emqx/emqx#12255]
### What happened?

I create emqx  v5 cluster with etcd discovery, when  etcd down for 1-2min , then recover etcd , the emqx cannot accept  new connections,   All Connections  > Live Connections.  

and I restart all emqx cores, the cluster experiences a split-brain scenario.

### What did you expect to happen?

In actuality, it is inevitable that etcd will experience downtime. However, it should not affect the operation of emqx

### How can we reproduce it (as minimally and precisely as possible)?

- 1. launch 3 core + 3 replicant
- 2. Establishing 30,000 connections on 3 replicant node using emqtt_bench
- 3. down etcd and after 2min start etcd
- 4. create new connect
```
./bin/emqtt_bench sub -h 127.0.0.1 -p 1883 -c 2500 -n 1000000 -i 20 -k 120 -t /pressure/%i -q 1 --ifaddr 10.51.3.64 -l --force-major-gc-interval
```
- 5. Viewing the emqx web UI
![1](https://github.com/emqx/emqx/assets/44466800/a3a43518-50d3-4ec5-b02d-90885feb97fb)
- 6. restart all emqx core 

```
root@ip-10-51-5-148 emqx]# ./bin/emqx_ctl cluster status 
Cluster status: #{running_nodes =>
                      ['emqx-ApAmg7@10.51.4.203',
                       'emqx-nwQmZF@10.51.5.148','emqx-pFEHZ2@10.51.3.169'],
                  stopped_nodes => []}
```
- 7 restart a replicant ，it will lost connections
```
root@ip-10-51-5-148 emqx]# ./bin/emqx_ctl cluster status 
Cluster status: #{running_nodes =>
                      ['emqx-3wonfX@10.51.4.181','emqx-ApAmg7@10.51.4.203',
                       'emqx-nwQmZF@10.51.5.148','emqx-pFEHZ2@10.51.3.169'],
                  stopped_nodes => []}
```

### Anything else we need to know?

etcd  kv
```
I have no name!@etcd-0:/opt/bitnami/etcd$ etcdctl get "ap" --prefix
ap-pro-emqxv5-cls2/ekkacl/lock//694d8cd40e07b1f8

ap-pro-emqxv5-cls2/ekkacl/nodes/emqx-ApAmg7@10.51.4.203
emqx-ApAmg7@10.51.4.203
ap-pro-emqxv5-cls2/ekkacl/nodes/emqx-nwQmZF@10.51.5.148
emqx-nwQmZF@10.51.5.148
ap-pro-emqxv5-cls2/ekkacl/nodes/emqx-pFEHZ2@10.51.3.169
emqx-pFEHZ2@10.51.3.169
```

### EMQX version

<details>

```console
$ ./bin/emqx_ctl broker
[root@ip-10-51-4-181 emqx]# ./bin/emqx_ctl broker
sysdescr  : EMQX
version   : 5.2.1-g4d0483e0
datetime  : 2024-01-04T10:32:45.540999062+00:00
uptime    : 10 minutes, 6 seconds
```

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
[root@ip-10-51-4-181 emqx]# cat /etc/os-release
NAME="Amazon Linux"
VERSION="2"
ID="amzn"
ID_LIKE="centos rhel fedora"
VERSION_ID="2"
PRETTY_NAME="Amazon Linux 2"
ANSI_COLOR="0;33"
CPE_NAME="cpe:2.3:o:amazon:amazon_linux:2"
HOME_URL="https://amazonlinux.com/"
SUPPORT_END="2025-06-30"

$ uname -a

Linux ip-10-51-4-181.ap-northeast-1.compute.internal 5.10.198-187.748.amzn2.aarch64 #1 SMP Tue Oct 24 19:49:48 UTC 2023 aarch64 aarch64 aarch64 GNU/Linux
```

</details>

### Log files

[emqx.log.1.tar.gz](https://github.com/emqx/emqx/files/13829021/emqx.log.1.tar.gz)

**Comment by ieQu1** [comment]
Hello,

Thanks for the report, I can confirm that the supervision tree for the `etcd` client is not designed properly, and the failure in the discovery callback can escalate to the node level. It's a bug. We will take care of it.
