### ISSUE TITLE
Mqtt server crash {port_died,normal}

### ISSUE THREAD

**Issue by emnvn** [emqx/emqx#1225]
#### Environment

- OS: CentOS 6 (2.6.32-431.11.2.el6.x86_64)
- Erlang/OTP: 18
- EMQ: 2.2

#### Description

Recent days my MQTT sever sometime crashed. I check log file that I saw below erros. I may think the problem of out of disk because of "diskup terminating" message. But the my disk space still available more than 9GB.

One more reasons that I think the problem when I enable "auth_http_plugin".  Last week I enable this plugin to authenticate user. I think it may be the reason because this error does  not happened before.

Thanks for any helping.

-----------------------------------
** Generic server disksup terminating
** Last message in was {'EXIT',#Port<0.2800>,normal}
** When Server state == [{data,[{"OS",{unix,linux}},{"Timeout",1800000},{"Threshold",80},{"DiskData",[{"/",14151600,33},{"/dev/shm",509300,0},{"/boot",495844,12}]}]}]
** Reason for termination ==
** {port_died,normal}
2017-08-29 16:28:54 =CRASH REPORT====
 crasher:
   initial call: disksup:init/1
   pid: <0.888.0>
   registered_name: disksup
   exception exit: {{port_died,normal},[{gen_server,terminate,7,[{file,"gen_server.erl"},{line,826}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,239}]}]}
   ancestors: [os_mon_sup,<0.886.0>]
   messages: []
   links: [<0.887.0>]
   dictionary: []
   trap_exit: true
   status: running
   heap_size: 376
   stack_size: 27
   reductions: 88890
 neighbours:
2017-08-29 16:28:54 =SUPERVISOR REPORT====
    Supervisor: {local,os_mon_sup}
    Context:    child_terminated
    Reason:     {port_died,normal}
    Offender:   [{pid,<0.888.0>},{id,disksup},{mfargs,{disksup,start_link,[]}},{restart_type,permanent},{shutdown,2000},{child_type,worker}]

**Comment by emqplus** [comment]
@emnvn Please send me the log/crash.dump. My email: feng@emqtt.io

**Comment by emnvn** [comment]
Hi emqplus,

I sent you an email with crash.dump and crash.log file.

Thanks for review it.

**Comment by Gilbert-Wong** [comment]
Hi, @emnvn , Sorry for late reply, have your issue been resolved? We have released emqx3.0.0, hope that the latest emqx could help you resolved this issue.
