### ISSUE TITLE
Help: no info from $SYS Broker Status or from CoAP .well-known core

### ISSUE THREAD

**Issue by MDunagan** [emqx/emqx#1226]
#### Environment

- OS: Ubuntu 16.04
- Erlang/OTP: erlang/xenial 1:18.3-dfsg-1ubuntu3 all
- EMQ: v2.3 - beta 3

### MQTT
I apologize now for being a noob at this. I'm having trouble getting the $SYS Broker Status to display anything. I changed the settings in emqtt/etc/acl.conf to:

> {allow, {user, "dashboard"}, subscribe, ["$SYS/#"]}.
> {allow, {ipaddr, "127.0.0.1"}, pubsub, ["$SYS/#", "#"]}.
> {allow, all, subscribe, ["$SYS/#", {eq, "#"}]}.
> {allow, all}.

I'm using the app MQTT.fx (v1.5.0) to connect to my AWS server running eMQTT. So I'm able to connect to the Broker Status, but I never receive any information. Also because of this setting "mqtt.broker.sys_interval = 60" I leave the subscription running for a couple of minutes each test to see if the server will send any information. Any help would be greatly appreciated.

Additionally I tried installing mosquitto-clients so I could run mosquitto_sub from command line on localhost and this is all I get:

> username$ mosquitto_sub -t t -d
> Client mosqsub/24118-ip-172-31 sending CONNECT
> Client mosqsub/24118-ip-172-31 received CONNACK
> Client mosqsub/24118-ip-172-31 sending SUBSCRIBE (Mid: 1, Topic: t, QoS: 0)
> Client mosqsub/24118-ip-172-31 received SUBACK
> Subscribed (mid: 1): 0
> Client mosqsub/24118-ip-172-31 sending PINGREQ
> Client mosqsub/24118-ip-172-31 received PINGRESP

### CoAP
Also I'm having a similar problem when using the Copper extension (v1.0.1) for FireFox to try and discover the CoAP "/.well-known/core" for my server. I've enabled the emq_coap plugin, but either I'm missing a setting or perhaps this is not included? Again, any help would be greatly appreciated.

**Comment by grutabow** [comment]
coap .well-known resource will return an empty content. Plan to fill this resource in later version.

**Comment by MDunagan** [comment]
Understood. I'll wait for the new version to have content for the CoAP .well-known resource.

Any chance I can get some feedback about the MQTT $SYS Broker Status issue? Am I wrong to expect that it should return some information such as:
- Broker (version, uptime, subscriptions ...)
- Clients (connected, maximum, total ...)
- Messages (sent, received ...)

In the additional steps I mentioned above on my original post, I followed the steps described in [this comment](https://github.com/emqtt/emqttd/issues/1089#issuecomment-306973125) from another issue to try and get information from the $SYS Broker through the command-line on localhost of the server.

Am I missing a configuration option? Maybe this information is supplied on a different port than 1883? I'm running out of ideas to try.

**Comment by MDunagan** [comment]
I figured it out.
