### ISSUE TITLE
How to bridge two emqtt remotely?

### ISSUE THREAD

**Issue by Jowin** [emqx/emqx#1227]
#### Environment

- OS: Ubuntu 16.04
- Erlang/OTP: Erlang 19.3
- EMQ: v2.2 stable

#### Description
Two emqtt brokers are set up on identical systems on aws. I am trying to bridge emqttd@127.0.0.1 on server1 to emqttd2@127.0.01(externally visible as `broker.domain.com` on server 2. I am executing the following code to bridge :

`./emqttd_ctl bridges start emqttd2@broker.domain.com topic/+`

It results in a failure with : 
`error: {{shutdown,
            {failed_to_start_child,
                {emqttd_bridge,1},
                {cannot_connect_node,'emqttd2@broker.domain.com'}}},
        {child,undefined,
            {bridge_sup,'emqttd2@broker.domain.com',<<"topic/+">>},
            {emqttd_bridge_sup,start_link,
                ['emqttd2@broker.domain.com',<<"topic/+">>,
                 [{max_queue_len,10000},{ping_down_interval,1}]]},
            permanent,infinity,supervisor,
            [emqttd_bridge_sup]}}`

What's the proper way to set a remote bridge between two emqtt brokers?

**Comment by emqplus** [comment]
@Jowin Firewall should make the 4369, 6369 ports accessible for bridged nodes.

Deployment: http://emqx-enterprise-docs-en.readthedocs.io/en/latest/deploy.html

**Comment by marleau** [comment]
@Jowin Were you able to bridge remote brokers? I'm running into the same error message.

**Comment by Jowin** [comment]
No, I wasn't even after opening up the ports it gave an error. For now, I have parked this. 
Another alternative I came across (not an ideal solution) is to use a combination of [telegraf](https://github.com/influxdata/telegraf) and it's consumer, publish clients to achieve the same thing.

**Comment by samk-mesh** [comment]
I'm seeing the same behavior.

**Comment by psorobka** [comment]
Same message here, emq 2.3.11

**Comment by Eluso** [comment]
`vi etc/emqx.conf`

`bridge.aws.address = 127.0.0.1:1883` (change to your  bridge IP:port)
`bridge.aws.client_id = bridge_aws` (your client_id)
`bridge.aws.username = user` (your  username)
`bridge.aws.password = passwd` (your password)

other bridge.aws.* was optional

`./bin/emqx start`
`./bin/emqx_ctl bridges list `(check bridges status)
`./bin/emqx_ctl bridges start aws` (start/stop bridge)
