### ISSUE TITLE
User is able to publish/subscribe to the topic that they not allow when they subscribe '#' topic.

### ISSUE THREAD

**Issue by sambatlim** [emqx/emqx#12312]
### What happened?

I created two users with the rule as below:
1. user-01 =  permission: allow, topic: user-01
2. user-02 =  permission: allow, topic: user-02

when I log in as user-01 and subscribe to '#' ,i am able to see msg from topic user-02 as well which is not allowed for user 01.

 

### What did you expect to happen?

I expect user-01 to see only the message from the topic that they allowed when subscribe to '#'.

### EMQX version

<details>

```console
$ ./bin/emqx_ctl broker
sysdescr  : EMQX
version   : 5.4.1
datetime  : 2024-01-12T06:19:23.151914222+00:00
uptime    : 6 minutes, 17 seconds
```

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here
```

</details>

### Log files

<details>

</details>

**Comment by lafirest** [comment]
Hi, @sambatlim, I don't think this is a bug since the `#` means `to match all of the topics`.
And if possible, please paste your rules here, thanks

**Comment by ieQu1** [comment]
What is the value of `authorization.no_match` config parameter? 
https://www.emqx.io/docs/en/latest/access-control/authz/authz.html#configure-with-configuration-file

If it's `allow`, then the broker will allow the clients to subscribe any of the topics not covered by `deny` rules. If you want to use ACL in allowlist mode, you should set this parameter to `deny`.

**Comment by arno608rw** [comment]
![image](https://github.com/emqx/emqx/assets/3774145/4c5832a6-e6c2-41b1-98d4-d1a2337424b2)
![image](https://github.com/emqx/emqx/assets/3774145/bffe7beb-3086-4429-a33c-3313ac1b6ace)
![image](https://github.com/emqx/emqx/assets/3774145/394efebc-2384-4b09-9049-db5c79ce2200)
![image](https://github.com/emqx/emqx/assets/3774145/eb8ec547-b685-4b21-bc50-d258ccd160ea)

**Comment by sambatlim** [comment]
@lafirest The rules are as the images from @arno608rw

**Comment by zmstone** [comment]
I guess the default 'file' source is enabled?
The default 'file' authz source allows subscribing to # when the client is from 127.0.0.1 (given in the screenshot it's 'localhost' used).

**Comment by arno608rw** [comment]
> I guess the default 'file' source is enabled? The default 'file' authz source allows subscribing to # when the client is from 127.0.0.1 (given in the screenshot it's 'localhost' used).
> 
> ![image](https://private-user-images.githubusercontent.com/164324/296763427-6a3c923b-6a4a-4648-a122-c5f45f20b8b9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUzNzIwNDcsIm5iZiI6MTcwNTM3MTc0NywicGF0aCI6Ii8xNjQzMjQvMjk2NzYzNDI3LTZhM2M5MjNiLTZhNGEtNDY0OC1hMTIyLWM1ZjQ1ZjIwYjhiOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExNlQwMjIyMjdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05YTNiMTU5YjE0M2Q3MmY1YjZhNGFiMDQ2ZTExOTgzNTc0ZTFhNjg4YzNmMDRhZDA5MjAzNzZlZmJkNTEyNTQyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ymyIhu1o5YfBamLcIp9s4Nw_-s6UYuANJt_sihNbVoo)

I Disable Authorization on File
![image](https://github.com/emqx/emqx/assets/3774145/ad7e21b1-95c1-4163-9273-0f118889a535)

**Comment by zmstone** [comment]
Thank you @savonarola  for taking it, FYI. I cannot reproduce this.

**Comment by savonarola** [comment]
Hello! I couldn't reproduce also.

>I expect user-01 to see only the message from the topic that they allowed when subscribe to '#'.

With the specified settings none of the user should be allowed to subscribe to '#' at all. _After_ they subscribed to the topic, the ACL is not checked anymore for _receiving_.

However, from the specified screenshots of MQTT Explorer, it is impossible to see which messages were actually sent and received.

Received messages (if any) should be displayed near the host 
![image](https://github.com/emqx/emqx/assets/4236/31a9baac-271c-4134-9ca7-6dae248989db)


Could you reproduce the issue (ability to subscribe) with some terminal client, like `mosquitto_pub` & `mosquitto_sub`?

Like, subscribe to '#' in the terminal: 
```
>mosquitto_sub -d -t '#' -q 1 -u user-01 -P password
Client (null) sending CONNECT
Client (null) received CONNACK (0)
Client (null) sending SUBSCRIBE (Mid: 1, Topic: #, QoS: 1, Options: 0x00)
Client (null) received SUBACK
Subscribed (mid: 1): 1
Client (null) received PUBLISH (d0, q0, r1, m0, '$SYS/brokers', ... (14 bytes))
emqx@127.0.0.1
Client (null) received PUBLISH (d0, q0, r1, m0, '$SYS/brokers/emqx@127.0.0.1/sysdescr', ... (15 bytes))
EMQX Enterprise
Client (null) received PUBLISH (d0, q0, r1, m0, '$SYS/brokers/emqx@127.0.0.1/version', ... (5 bytes))
5.4.1
```

**Comment by sambatlim** [comment]
I got it solved by restarting the EMQX broker after config the authentication. Thanks.

**Comment by sambatlim** [comment]
Do we always need to restart the broker everytime we make change to the authentication setting? Because, sometime It works without restarting broker and sometime not work.

**Comment by zmstone** [comment]
Hi @sambatlim 
It could be due to authz cache which keeps the last acl check results for 1 minute by default (as in your screenshot)

**Comment by ieQu1** [comment]
BTW, if you use builtin database for authN/authZ, you can probably live just fine with ACL cache disabled: builtin database stores data locally in RAM, so reads are very fast.
