### ISSUE TITLE
Very very Buggest broker!

### ISSUE THREAD

**Issue by DxrMorgan** [emqx/emqx#12322]
### What happened?

Bridge dont work!
Subscription dotn work!

### What did you expect to happen?

Bridge dont work!
Subscription dotn work!

### EMQX version

Bridge dont work!
Subscription dotn work!

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here
```

</details>

### Log files

<details>

</details>

**Comment by ieQu1** [comment]
Please fill in the required fields. Otherwise we can't do anything to help with you problem.
