### ISSUE TITLE
not getting retained messages after client re-connects (after they were received in previous session)

### ISSUE THREAD

**Issue by syberkitten** [emqx/emqx#1233]
As i understand it is not clear from MQTT specs what should be the behavior when client
disconnects after subscribing to topics that have retained messages.

What is expectd is that if a client received a retained message,
got disconnected, connects again -> should get the retained messages again,
In spite actually receiving the message before (in previous session)

The expectation is that a retained messages will always be re-delivered,
since client re-connects should alway receive the default (retained) messages.

Is this possible?
what should we expect from EMQ?

I'm using this reference which states that MQTT using QoS 1 for (subscribe and publish)
should re-deliver the messages, but it does not work with EMQ

http://www.steves-internet-guide.com/mqtt-clean-sessions-example/

using EMQ version: 2.2 (relx)

**Comment by syberkitten** [comment]
@turtleDeng Can you please explain what is the Enterprise label
and what does it mean?

**Comment by syberkitten** [comment]
@turtleDeng @emqplus 

As far as I saw the MQTT specs leaves this area as grey, there is no clear definition
and It would be good to be able to configure if:

A. All retained messages will be re-send each time a subscribing client re-connects with (clean: 0)

B. Retained message will be sent only when updated (current behavior) - thus client has to keep internal state of previous retained messages, and will get only updated messages.

ps. When do you plan to release an Enterprise version / support?

**Comment by Gilbert-Wong** [comment]
@theronic the feature you want is in emqx enterprise edition. Please contact @zhengyupan  for more details.
