### ISSUE TITLE
Does HTTP publish tell if the message was delivered in the response?

### ISSUE THREAD

**Issue by CheyenneForbes** [emqx/emqx#1234]

**Comment by emqplus** [comment]
@CheyenneForbes No. The HTTP Publish API calls the MQTT Publish too.

**Comment by CheyenneForbes** [comment]
Can it be implemented? I want to use it in a webrtc project... if the "call" isnt delivered the caller would get an "unavailable" message.. if it cant be implemented, is there any way to know if a user is able to receive mqtt messages (has internet connection for example)

**Comment by CheyenneForbes** [comment]
would you mind adding this to the HTTP publish?

After a publish request the response will tell if the client is connected or disconnected if the request was passed with a "is_connected" query parameter (_http.://server/api/v2/mqtt/publish_**?is_connected=true**)

**Comment by emqplus** [comment]
@CheyenneForbes I will plan this feature in 2.4 release. Thanks.

**Comment by CheyenneForbes** [comment]
Thanks a lot, is there a planned release date for 2.4?
