### ISSUE TITLE
Health Check Interval repeats in configuration of the action and the connector

### ISSUE THREAD

**Issue by tigercl** [emqx/emqx#12355]
### What happened?

Click Create Connector in the Azure Event Hubs event and when I expand the advanced settings, I see the Health Check Interval option.

When I go back to the Action's configuration page and expand the Action's advanced settings, I see the Health Check Interval option again.

According to common sense, Health Check Interval should belong to Connector rather than Action?

HTTP Server also has this problem, I'm not sure if there are other Actions that have this problem. You can check them all.

### What did you expect to happen?

Health Check Interval should only belong to Connector.

### EMQX version

EMQX v5.4.1

### OS version

macOS 12

### Log files

<details>

</details>

**Comment by ysfscream** [comment]
Hi, @tigercl 

Indeed, it makes sense to be associated only with the Connector.

But the dashboard UI is rendered based on the backend’s /schema API, and currently, the issue might stem from the backend Schema, including the health_check_interval setting in both connectors and actions. I suggest involving a backend team member, @zmstone , to confirm and clarify this. Thanks all. 🙌

![image](https://github.com/emqx/emqx/assets/21299158/419f7ed3-fcb5-477d-9e56-a4e5981feb51)

![image](https://github.com/emqx/emqx/assets/21299158/18ba4b1a-4eb3-4851-86bf-8e2bb2d9c342)

**Comment by qzhuyan** [comment]
@ysfscream @tigercl since the issue is clear now, pls drive the issue.

**Comment by id** [comment]
Connector and Action do have their independent health checks. This is by design.
