### ISSUE TITLE
One of the server in the cluster crashed with error: no more index entries in error: no more index entries in atom_tab

### ISSUE THREAD

**Issue by roysG** [emqx/emqx#12369]
### What happened?

no more index entries in atom_tab (max=1048576)

Crash dump is being written to: /var/log/emqx/crash.dump...done
[os_mon] memory supervisor port (memsup): Erlang has closed
[os_mon] cpu supervisor port (cpu_sup): Erlang has closed

### What did you expect to happen?

No crash

### EMQX version

<details>

```console
$ ./bin/emqx_ctl broker
# paste output here
```
sysdescr  : EMQ X Broker
version   : 4.3.5
uptime    : 12 minutes, 30 seconds
datetime  : 2024-01-23 00:09:05

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here
```

NAME="Ubuntu"
VERSION="20.04.6 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.6 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal

Linux ip-172-31-30-122 5.15.0-1044-aws #49~20.04.1-Ubuntu SMP Mon Aug 21 17:09:32 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

</details>

### Log files

<details>

</details>

===== ALIVE Mon Jan 22 23:45:26 UTC 2024

===== Mon Jan 22 23:56:04 UTC 2024
no more index entries in atom_tab (max=1048576)

Crash dump is being written to: /var/log/emqx/crash.dump...done
[os_mon] memory supervisor port (memsup): Erlang has closed
[os_mon] cpu supervisor port (cpu_sup): Erlang has closed

=====
===== LOGGING STARTED Mon Jan 22 23:56:18 UTC 2024
====

**Comment by lafirest** [comment]
@roysG 
This is a known bug for 4.x versions, I guess you used some automatically script to call `emqx ctl`?
But sorry for that we have already retired 4.3, maybe you can update to the newest version

**Comment by qzhuyan** [comment]
@roysG as tmp workaround, you could try set envvar to bump that max number while start EMQX, below example 8 times the maximum. 

ERL_FLAGS=`+t  8388608`

but if you still keep calling `emqx ctl`, it will eventually  runs out again.

**Comment by roysG** [comment]
So the bug is because I call emqx ctl?

So in case is stop to call the it will gone?



בתאריך יום ג׳, 23 בינו׳ 2024 ב-19:27 מאת William Yang <
***@***.***>:

**Comment by qzhuyan** [comment]
> So in case is stop to call the it will gone?
yes
