### ISSUE TITLE
Wildcard handling, difference between Mosquitto/EMQX

### ISSUE THREAD

**Issue by Kbij** [emqx/emqx#12360]
### What happened?

While switching from Mosquitto to EMQX, i noticed a difference in how Mosquitto and EMQX handle mixed wildcard subsriptions.
I use the following wildcards in my application:

* app/SerialA/state
* app/SerialA/+/#

Mosquitto will send these topic to my application:
* app/SerialA/state
* app/SerialA/Device1/state
* app/SerialA/Device2/event

Mosquitto will NOT send these topics to my application:
* app/SerialA/someOtherTopic

EMQX will send these topics to my application:
* app/SerialA/state ← received twice
* app/SerialA/Device1/state
* app/SerialA/Device2/event
* app/SerialA/someOtherTopic → not correct in my opinion (does not match the app/SerialA/+/# subscription)

The subscription “app/SerialA/+/#” states that at least 4 parts must be present in the topic. But EMQX filters messages with 3 topic parts with this subscription.

### What did you expect to happen?

For the subscription: app/SerialA/+/#
Each filtered topic that comes thru this subscription, should contain at least 4 parts (like: app/SerialA/part3/part4)

And maybe (don't know exactly how Mosquitto handles this: if two subscriptions filter the same topic: receive the topic only once.
Currently in EMQX: because the two wildcard subscriptions filter the same topic: a single message send, is received by my application twice.

### How can we reproduce it (as minimally and precisely as possible)?

See above.

### EMQX version

<details>

```console
$ ./bin/emqx_ctl broker
# paste output here
```
sysdescr  : EMQX
version   : 5.3.0
datetime  : 2024-01-20T18:22:57.749945737+00:00
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here
```
PRETTY_NAME="Ubuntu 22.04.2 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.2 LTS (Jammy Jellyfish)"

</details>

### Log files

<details>

</details>

**Comment by qzhuyan** [comment]
for
>  if two subscriptions filter the same topic: receive the topic only once.

I think it is per broker implementation  as MQTT 5.0 spec states: 

the Server MAY deliver further copies of the message, one for each additional matching subscription and respecting the subscription’s QoS in each case.


for 
> app/SerialA/someOtherTopic → not correct in my opinion (does not match the app/SerialA/+/# subscription)


in MQTT 5.0 spec:

```
4.7.1.2 Multi-level wildcard 2949 The number sign (‘#’ U+0023) is a wildcard character that matches any number of levels within a topic. 
The multi-level wildcard represents the parent and any number of child levels.
```
also there is a "Non-normative comment":

```
“sport/#” also matches the singular “sport”, since # includes the parent level
```
