### ISSUE TITLE
EMQX Users to be deleted can connet to EMQX MQTT Broker

### ISSUE THREAD

**Issue by bkkoli** [emqx/emqx#12379]
### What happened?

I use EMQX applications with k8s cluster.

I delete EMQX Dashboard specific user in GUI of EMQX Dashboard.

But I can connect to EMQX MQTT Broker with deleted user.

What Can I solve this problem?

### What did you expect to happen?

Deleted User can not connect to broker

### How can we reproduce it (as minimally and precisely as possible)?

1. Delete user in EMQX Dashboard
2. try to connect to broker with deleted user.

### Anything else we need to know?

Server OS: debian 10
k8s: v1.18.6
k8s Storage Class: nfs
k8s cri: docker 19.03.12

### EMQX version

<details>

```console
$ ./bin/emqx_ctl broker
sysdescr  : EMQX
version   : 5.4.1
datetime  : 2024-01-24T06:52:48.558713962+00:00
uptime    : 8 minutes, 40 seconds
```

</details>

### OS version

<details>

```console
# OS
## Docker Image :
$ cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

$ uname -a
Linux emqx-statefulset-0 4.19.0-9-amd64 #1 SMP Debian 4.19.118-2+deb10u1 (2020-06-07) x86_64 GNU/Linux

## host :
$ cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 10 (buster)"
NAME="Debian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"


$ uname -a
Linux kmaster 4.19.0-9-amd64 #1 SMP Debian 4.19.118-2+deb10u1 (2020-06-07) x86_64 GNU/Linux
```

</details>

### Log files

<details>

</details>

**Comment by qzhuyan** [comment]
I could not reproduce the issue if I create the user via dashboard

 @bkkoli how do you create the user?

**Comment by bkkoli** [comment]
I create user in user tab of dashboard. After I remove user, I attempt to login with mqttx dashboard client.

**Comment by qzhuyan** [comment]
what is "mqttx dashboard client." ?

**Comment by bkkoli** [comment]
@qzhuyan  It means client created with dashboard

**Comment by zmstone** [comment]
@bkkoli  could you trace the client and share the logs with us ?
