### ISSUE TITLE
Helm: Allow to set `priorityClassName` for the pods

### ISSUE THREAD

**Issue by joggeli34** [emqx/emqx#12378]
### What would you like to be added or enhanced?

An optional parameter `priorityClassName` for setting the priority of the pods would help for running the broker more stable.

### Why is this needed?

In our usecase, we run the broker on the same cluster as we run the mqtt client applications which processes the data. We would like to run the broker with a higher priority, so that it is scheduled faster then the clients and it can not be preempted by the clients. 

https://kubernetes.io/docs/concepts/scheduling-eviction/pod-priority-preemption/#pod-priority

**Comment by qzhuyan** [comment]
@joggeli34 thanks for the info, good idea, could you make a PR for that? 
@Rory-Z FYI, consider add it to operator?

**Comment by joggeli34** [comment]
Yes, I can provide a PR in the next few days
