### ISSUE TITLE
Helm Chart for emqx does not support cluster topology

### ISSUE THREAD

**Issue by k2sebeom** [emqx/emqx#12382]
### What would you like to be added or enhanced?

In many of the emqx documents, it says that for cluster with more than 3 nodes, having replicant node is recommended. However, in helm chart, there is not any options to choose the role of certain subset of nodes.

### Why is this needed?

Helm-deployed cluster only supports all-core cluster. It is not desirable for a large cluster.

**Comment by id** [comment]
@k2sebeom for core+replicant setup we recommend to use https://github.com/emqx/emqx-operator/
