### ISSUE TITLE
Why stop releasing packages for Windows with EMQX v5.4.0

### ISSUE THREAD

**Issue by michaelcplusplus** [emqx/emqx#12394]
### What would you like to be added or enhanced?

We have been successfully using EMQX Broker on Windows systems for our customers for several years. The system load has so far been moderate and we have not experienced any problems with the Windows installations.

Why is support for Windows being discontinued? Is there a way to continue using the Broker in versions above 5.4.0 on Windows?
Best regards
Michael

### Why is this needed?

We have many installations on Windows Server and would like to continue using EMQX Broker.

**Comment by qzhuyan** [comment]
We have decided to kill it. There will be no more package release for windows. 

May you switch to linux VM or such? 

You could still build on your own and your contribution is always welcomed.

**Comment by michaelcplusplus** [comment]
What a pity. Thanks for the answer.
