### ISSUE TITLE
当时用http 桥接或者webhoo做数据转发的时候,遇到二进制数据会产生efbfbd

### ISSUE THREAD

**Issue by pslxx** [emqx/emqx#12412]
### What happened?

当时用http 桥接或者webhoo做数据转发的时候,遇到二进制数据会产生efbfbd

直接订阅的模式,就是能正常解码,使用webhook的模式,解码就不对

### What did you expect to happen?

希望正常

### EMQX version

<details>

```console
$ ./bin/emqx_ctl broker
# paste output here
```

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here
```

</details>

### Log files

<details>

</details>

**Comment by SergeTupchiy** [comment]
Hi @pslxx,
Could you please provide more information to help reproducing this issue:
* EMQX version
* EMQX config (bridge and rule config)
* message data example
