### ISSUE TITLE
Clarification about PUBACK missed

### ISSUE THREAD

**Issue by alifirat** [emqx/emqx#1242]
#### Environment

- OS: Debian 8 jessie
- Erlang/OTP: R19/8.3
- EMQ: 2.2

#### Description

In EMQ dashboard, I see a field called ``puback/missed`` > 0. It happens in a context of a load test with 300 publishers sending data at rate of ~ 60 / 70 msg / sec. I set up a cluster of 3 nodes, putting a consumer on each node and my consumers are receiving the good number of messages. 

But I also have a test on the publishers side, checking the number of  PUBACK at the end and it fails. Reading your (great) dashboard, it seems that my publishers didn't ACK all the messages send to the broker.  

But can you give a clear clarification of what represents the missed PUBACK please ?

Thank you,
Alifirat.

**Comment by Gilbert-Wong** [comment]
Sorry for so late reply, how did you configure your emqx, how do you set the configuration entry `max_inflight`?
