### ISSUE TITLE
Using DNS Autodiscovery and AAAA Records

### ISSUE THREAD

**Issue by Rotario** [emqx/emqx#12448]
### What happened?

I've set up EMQX with a Dockerfile, with two machines on fly.io trying to use auto DNS discovery to find each other

Fly offers a private DNS that resolves the IPs of an app
https://fly.io/docs/networking/private-networking/#fly-io-internal-addresses

Here's my current Docker env vars to set the config
Dockerfile.fly
```
ENV EMQX_CLUSTER__DISCOVERY_STRATEGY=dns
ENV EMQX_CLUSTER__DNS__NAME=emqx.internal
ENV EMQX_CLUSTER__DNS__RECORD_TYPE=a
ENV EMQX_CLUSTER__PROTO_DIST=inet6_tcp
```
I'm setting the node name dynamically on boot
boot_fly.sh
```
export EMQX_NODE__NAME="emqx@${FLY_PRIVATE_IP}"
```

Unfortunately when I spin up two instances of my fly app `emqx`
If I run `dig +short aaaa emqx.internal @fdaa::3` inside the app I get the expected two IPs
```
fd2xxxx:2
fd3xxxx:2
```
Meaning the fly private dns discovery is working
but when I run `emqx ctl cluster status`
I only get one running cluster (the machine that I run the command on)
```
Cluster status: #{running_nodes =>
                      ['emqx@fd2xxxx:2'],
                  stopped_nodes => []}
```

### What did you expect to happen?

I expected AAAA record-based DNS discovery to work

### How can we reproduce it (as minimally and precisely as possible)?

Run two EMQX machines on the Fly.io service, set up basic DNS discovery.

### Anything else we need to know?

I notice your Ekka library to cluster supports AAAA record as of Jul 2022

https://github.com/emqx/ekka/issues/174

But the record types supported are only SRV or A

https://www.emqx.io/docs/en/latest/deploy/cluster/create-cluster.html#configure-autocluster-by-dns-records

### EMQX version

<details>

```console
$ ./bin/emqx_ctl broker
sysdescr  : EMQX
version   : 5.4.1
datetime  : 2024-02-01T14:32:41.056148162+00:00
uptime    : 54 minutes, 4 seconds
```

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

$ uname -a
Linux 7811079f250548 5.15.98-fly #g2626e66887 SMP Mon Jan 29 07:34:38 UTC 2024 x86_64 GNU/Linux

```

</details>

### Log files

<details>

</details>

**Comment by Rotario** [comment]
I've got static discovery working using the fly DNS service and fixed machines as seeds
boot_fly.sh
```
export EMQX_NODE__NAME="emqx@${FLY_ALLOC_ID}.vm.emqx.internal"
```

Dockerfile.fly
```
ENV EMQX_CLUSTER__DISCOVERY_STRATEGY=static
ENV EMQX_CLUSTER__STATIC__SEEDS=[emqx@7811079f250548.vm.emqx.internal,emqx@7811079f250548.vm.emqx.internal]
````

**Comment by id** [comment]
Hi @Rotario.

Indeed, EMQX only supports A records, but not AAAA.

In your example config should've looked like this:
```
ENV EMQX_CLUSTER__DNS__RECORD_TYPE=aaaa
```

But right now we only allow "A".

I'm checking with the team if we can support AAAA in EMQX cluster auto discovery.

**Comment by Rotario** [comment]
Brill thanks for your support!

**Comment by id** [comment]
@wivwiv FYI
