### ISSUE TITLE
5.5.0 bridge/connector config issue

### ISSUE THREAD

**Issue by alexdelprete** [emqx/emqx#12452]
### What happened?

Upgraded from 5.4.1 to 5.5.0: errors in the UI when checking connectors section, the connectors have disappeared, list is empty:

![image](https://github.com/emqx/emqx/assets/7027842/0dbcd8f6-b730-40f0-885f-860429ef7bc3)

### What did you expect to happen?

I expected EMQX to work as usual, I didn't change anything in the config and 5.4.1 was running fine.

### How can we reproduce it (as minimally and precisely as possible)?

Upgrade from 5.4.1 to 5.5.0 with my connectors/bridges config

### Anything else we need to know?

I downgraded to 5.4.1 and everything's fine.

![image](https://github.com/emqx/emqx/assets/7027842/5ea9a334-fba9-4067-9e5b-2185fcfcbb7b)

### EMQX version

<details>

```console
$ ./bin/emqx_ctl broker
sysdescr  : EMQX
version   : 5.5.0
datetime  : 2024-02-01T19:00:47.811264297+01:00
uptime    : 8 minutes, 24 seconds

```

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 12 (bookworm)"
NAME="Debian GNU/Linux"
VERSION_ID="12"
VERSION="12 (bookworm)"
VERSION_CODENAME=bookworm
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

$ uname -a
Linux emqx 6.5.11-7-pve #1 SMP PREEMPT_DYNAMIC PMX 6.5.11-7 (2023-12-05T09:44Z) x86_64 GNU/Linux
```

</details>

### Log files

[node_dump_20240201_190453.tar.gz](https://github.com/emqx/emqx/files/14129235/node_dump_20240201_190453.tar.gz)

**Comment by HJianBo** [comment]
Hi @alexdelprete, thanks for your feedback. Can you provide us with your 5.4.1 emqx configuration file and cluster.hocon in the data directory? This will help us to reproduce the issue.

ps:  Depending on your installation approach, the location of the data directory you can find here.
 https://docs.emqx.com/en/enterprise/latest/deploy/install.html#files-and-directories

**Comment by HJianBo** [comment]
In addition, can you describe in detail how many nodes are in the cluster, what their roles are, and how you upgraded from 5.4.1 to 5.5.0?

**Comment by alexdelprete** [comment]
> You can send it to my email [heeejianbo@gmail.com](mailto:heeejianbo@gmail.com), and obfuscate some key information with

Mail sent.

> In addition, can you describe in detail how many nodes are in the cluster, what their roles are, and how you upgraded from 5.4.1 to 5.5.0?

It's a simple one node installation, Debian 12 Bookworm. I always upgrade through apt-get.

**Comment by HJianBo** [comment]
Thanks for your detailed information. I have reproduced this problem. The root cause is that **we can't handle the situation in 5.5.0 where we have a configuration with mqtt bridging in `data/cluster-override.conf`.**

i.e,
1. start a new emqx 5.5.0 node and save the following confs into the `data/cluster-override.conf`:
```
bridges {
  mqtt {
    test {
      bridge_mode = false
      clean_start = true
      egress {
        local {topic="hhhhhh"}
        remote {
          payload = "${payload}"
          qos = 1
          retain = false
          topic = hhhhhhhhhh
        }
      }
      enable = true
      keepalive = 300s
      proto_ver = v4
      resource_opts {
        health_check_interval = 15s
        inflight_window = 100
        max_buffer_bytes = 1GB
        query_mode = async
        request_ttl = 45s
        start_timeout = 5s
        worker_pool_size = 4
      }
      retry_interval = 15s
      server = "127.0.0.1"
      ssl {enable = false, verify = verify_peer}
    }
  }
}
```
2. Start the emqx, and we will get the following error logs:
```
2024-02-02T12:06:54.287849+08:00 [error] msg: load_bridge_failed, mfa: emqx_bridge:safe_load_bridge/4(159), error: throw, name: test, reason: bridge_not_found, stacktrace: [{emqx_bridge_v2,bridge_v1_id_to_connector_resource_id,2,[{file,"emqx_bridge_v2.erl"},{line,1766}]},{emqx_bridge_resource,create,4,[{file,"emqx_bridge_resource.erl"},{line,198}]},{emqx_bridge,safe_load_bridge,4,[{file,"emqx_bridge.erl"},{line,141}]},{emqx_utils,'-do_parallel_map/2-anonymous-0-',3,[{file,"emqx_utils.erl"},{line,608}]}], type: mqtt
```

3. At this point, if we open the dashboard's bridging page again, we get the 500 error mentioned in the issue.

**Comment by alexdelprete** [comment]
> The root cause is that **we can't handle the situation in 5.5.0 where we have a configuration with mqtt bridging in `data/cluster-override.conf`**

Would it be possible to automagically convert (once recognised) the old bridge config to the new connector one?

**Comment by RogerSelwyn** [comment]
Passing comment on this since I had the same problem when I upgrade to 5.5.0. With 5.5.1, all my connectors are duplicated, with one set saying they are unmanageable via the GUI..

**Comment by alexdelprete** [comment]
> With 5.5.1, all my connectors are duplicated, with one set saying they are unmanageable via the GUI..

When I upgraded to 5.5.0 and had the issue, I reverted back to 5.4.x. Then I upgraded to 5.5.1 and connectors configuration was imported/converted correctly.

**Comment by RogerSelwyn** [comment]
> > With 5.5.1, all my connectors are duplicated, with one set saying they are unmanageable via the GUI..
> 
> When I upgraded to 5.5.0 and had the issue, I reverted back to 5.4.x. Then I upgraded to 5.5.1 and connectors configuration was imported/converted correctly.

That’s what I did, but now have duplicates in 5.5.1. 

It looks like ClientIds have changed again in 5.5.1 which has broken a fussy connector so I may not be able to upgrade anyway, otherwise I’d just rebuild the connectors from scratch.
