### ISSUE TITLE
Per listener authentication built-in database user creation

### ISSUE THREAD

**Issue by Rotario** [emqx/emqx#12454]
### What happened?

Per listener authentication is available:
https://www.emqx.io/docs/en/latest/changes/auth-4.4-to-5.1-compatibility.html#per-listener-authentication

But there seems to be no way to add users to the built-in authentication database for this per listener auth?
(has been asked here: https://www.reddit.com/r/emqx/comments/195mluj/per_listener_authentication_missing_from_gui/)

With my Docker config like so
```
ENV EMQX_LISTENERS__TCP__DEFAULT__BIND=0.0.0.0:1883
ENV EMQX_LISTENERS__TCP__DEFAULT__AUTHENTICATION__1__BACKEND=built_in_database
ENV EMQX_LISTENERS__TCP__DEFAULT__AUTHENTICATION__1__MECHANISM=password_based
ENV EMQX_LISTENERS__TCP__DEFAULT__AUTHENTICATION__1__PASSWORD_HASH_ALGORITHM__NAME=sha256
ENV EMQX_LISTENERS__TCP__DEFAULT__AUTHENTICATION__1__PASSWORD_HASH_ALGORITHM__SALT_POSITION=suffix
ENV EMQX_LISTENERS__TCP__DEFAULT__AUTHENTICATION__1__USER_ID_TYPE=username
```

I can't see any authentication methods listed in the GUI, nor can I see it listed in the HTTP Api and I can't add any users, meaning it's 

### What did you expect to happen?

Be able to add users to my per-listener authentication method

### How can we reproduce it (as minimally and precisely as possible)?

Add a per listener auth method with built-in database. Try to add users to it either through GUI or through HTTP Api

### EMQX version

<details>

```console
$ ./bin/emqx_ctl broker
# paste output here
```

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here
```

</details>

### Log files

<details>

</details>

**Comment by SergeTupchiy** [comment]
Hi @Rotario,

Per listener authentication has been disabled since EMQX 5.1.0: https://github.com/emqx/emqx/releases/tag/v5.1.0.
IIRC, EMQX 5.0.0 allowed to add users through HTTP API: "/listeners/:listener_id/authentication/:id/users/".

I think you can workaround it by disabling authentication for your full mutual TLS listener. 
For example:
```
EMQX_LISTENERS__SSL__DEFAULT__ENABLE_AUTHN=false
```

**Comment by Rotario** [comment]
Thank you I've got that working well!
