### ISSUE TITLE
Can't distinguish if string has leading spaces in Dashboard

### ISSUE THREAD

**Issue by tigercl** [emqx/emqx#12461]
### What happened?

When I have a string with leading spaces, it looks no different in Dashboard's SQL Test than any other string without leading spaces:

![4621706758406_ pic](https://github.com/emqx/emqx/assets/15085956/31eb63f7-0f54-4ded-89f4-c94d8d666fea)

I guess it also exists in strings with trailing spaces.

### What did you expect to happen?

Please make leading and trailing spaces more visible

### EMQX version

EMQX v5.4.1

### OS version

macOS 13.4

### Log files

<details>

</details>

**Comment by ysfscream** [comment]
Thanks for your feedback. It looks good for viewing the test result data on the next EMQX version.

<img width="1019" alt="image" src="https://github.com/emqx/emqx/assets/21299158/14949837-a2e1-4e37-8880-27c7992d1ff3">

**Comment by zmstone** [comment]
closed as it's fixed in release-56
