### ISSUE TITLE
Characters starting with backslash cannot be used in SQL

### ISSUE THREAD

**Issue by tigercl** [emqx/emqx#12460]
My actual problems are as follows:

### Replenish

Expect:
```
rtrim('\t hello \r\n') = '\t hello'
tokens('a\rb\nc\r\nd', ';', 'nocrlf') = ['a', 'b', 'c', 'd']
```

Actual:
```
rtrim('\t hello \r\n') = '\\t hello  \\r\\n'
tokens('a\rb\nc\r\nd', ';', 'nocrlf') = ["a\\rb\\nc\\r\\nd"]
tokens('a\rb\nc\r\nd', '\r\n', 'nocrlf') = ['a', 'b', 'c', 'd']
```

My previous understanding is wrong, please ignore the quoted part:

> #### What happened?
>
> I have the following string, each item separated by `\n`:
> 
> ```
> a\nb\nc\nd
> ```
> 
> I planned to split them through the tokens function, but when I used the following SQL in > > Dashboard:
> 
> ```
> SELECT
>     tokens(payload, '\n')
> FROM "t/#"
> ```
> 
> I found that in the actual HTTP request made by Dashboard, the SQL became like this:
> 
> ```
> SELECT
>     tokens(payload, '\\n')
> FROM "t/#"
> ```
> 
> And the EMQX backend does not eliminate redundant backslashes, which means that as long as the SQL contains characters starting with a backslash, it will not work as expected.

> ### What did you expect to happen?
> 
> Can the SQL be base64 encoded in the HTTP request and transmitted to the backend to avoid unnecessary escaping?
> 
> ### How can we reproduce it (as minimally and precisely as possible)?
> 
> _No response_
> 
> ### Anything else we need to know?
> 
> _No response_
> 
> ### EMQX version
> 
> EMQX v5.4.1
> 
> ### OS version
> 
> macOS 13.4
> 
> ### Log files

**Comment by wivwiv** [comment]
<img width="972" alt="image" src="https://github.com/emqx/emqx/assets/25006774/0765fae4-792a-4353-9457-fb68c50bba6c">

The `\\n` seem to be added when the object is converted to JSON for submission. They should be converted back when executed on the backend. This appears to be a bug in the backend's JSON conversion.

**Comment by tigercl** [comment]
### Replenish

Expect:
```
rtrim('\t hello \r\n') = '\t hello'
tokens('a\rb\nc\r\nd', ';', 'nocrlf') = ['a', 'b', 'c', 'd']
```

Actual:
```
rtrim('\t hello \r\n') = '\t hello'
tokens('a\rb\nc\r\nd', ';', 'nocrlf') = ["a\\rb\\nc\\r\\nd"]
tokens('a\rb\nc\r\nd', '\r\n', 'nocrlf') = ['a', 'b', 'c', 'd']
```

**Comment by zhongwencool** [comment]
It's work as:
```
   rule_test {
      actions = []
      description = ""
      enable = true
      metadata {created_at = 1708919800638}
      name = ""
      sql = """~
                SELECT
                    tokens(payload, '
        	')
                FROM "x/3
        "~"""
    }
```
if we want to use `\n` as delimiter. just pass `\n` to http api. not `\\n`.
<img width="425" alt="image" src="https://github.com/emqx/emqx/assets/3116225/14585651-8830-44a2-9af8-3e1f0a77f0f9">

<img width="460" alt="image" src="https://github.com/emqx/emqx/assets/3116225/8fb4d61d-d7c7-4e73-8d11-fbfb8355cb76">

**Comment by wivwiv** [comment]
Expected results:
```sql
SELECT
  tokens('1
  2
  3
4', '\n') as c
FROM 't/#'

-- output
{ "c": ["1", "2", "3", "4"] }
```

```sql
SELECT
  tokens('1
  2
  3
4', '
') as c
FROM 't/#'

-- output
{ "c": ["1", "2", "3", "4"] }
```

**Comment by zmstone** [comment]
for internal ref: https://emqx.atlassian.net/browse/EMQX-11847

**Comment by kjellwinblad** [comment]
@zmstone, you are right that the issue seems to be lack of escape sequence support in the strings in the SQL like language. Another interesting thing I found is that it looks like double quote strings are supported but they get evaluated to `undefined`! However, double quote strings seems to work fine in the FROM clause. I wonder if we could have single quote strings to mean literal strings and use double quote strings to mean strings with escape sequence support?

Anyway I think an `unescape` function seems like a good first step solution as it kind of solves the problem but still allows us to extend the syntax of the SQL like language if we want to.

```
SELECT
  '\n' as single_q,
  "\n" as double_q,
  '
  ' as newline
FROM
  "t/#"
```
  
  RESULT:
  
```
{
  "double_q": "undefined",
  "newline": "\n  ",
  "single_q": "\\n"
}
```

**Comment by zmstone** [comment]
Thank you for the fix @kjellwinblad 

I remember there is a issue or ticket about double quotes, but I cannot find it.
Anyways, double quotes handling is a separate matter, should create a new ticket to track it.

**Comment by kjellwinblad** [comment]
I created a ticket for the double quote string issue: https://emqx.atlassian.net/browse/EMQX-11971
