### ISSUE TITLE
Authentication 功能中 Built-in Database 不支持密码为空的场景，是否可以支持一下？

### ISSUE THREAD

**Issue by itaa** [emqx/emqx#12463]
### What would you like to be added or enhanced?

Authentication 功能中 Built-in Database 不支持密码为空的场景，是否可以支持一下？

<img width="510" alt="image" src="https://github.com/emqx/emqx/assets/13126814/4486cd8e-b475-48cc-9a1f-ffe7ef0ef0f5">

### Why is this needed?

我们在使用第三方传感器的时候，子设备不支持密码，但是又不能完全开放认证功能，所以需要一个密码为空的场景。

**Comment by zmstone** [comment]
You can add a new listener with auth disable for such clients (and only for such clients to confine the scope).
