### ISSUE TITLE
Built-in functions cannot be used directly in arrays in Rule Engine SQL

### ISSUE THREAD

**Issue by tigercl** [emqx/emqx#12465]
### What happened?

The following SQL will report an error:

```
SELECT
    contains('a', [sin(1), cos(1)]) as t1
FROM "t/#"
```

Unless changed to the following form:

```
SELECT
    sin(1) as t1,
    cos(1) as t2,
    contains('a', [t1, t2]) as t3
FROM "t/#"
```

### What did you expect to happen?

Built-in functions can be used directly in arrays in Rule Engine SQL

### EMQX version

EMQX v5.4.1

### OS version

macOS 13.4

### Log files

<details>

</details>

**Comment by kjellwinblad** [comment]
PR with fix created:

https://github.com/emqx/emqx/pull/12657
