### ISSUE TITLE
Allow add mountpoint for each user

### ISSUE THREAD

**Issue by burner-** [emqx/emqx#12528]
### What would you like to be added or enhanced?

Currently there is mountpoint only for listener. Listener mountpoint can take user as parameter. How ever this will mount all users with spesific schema without any excaptions. 
It would be usefull to have feature what allow set custom mount point for user. 

### Why is this needed?

It would be usefull to configure so that users use schema to isolate. How even if we want "superuser"users who can see all other users traffic that will need feature what allow set mountpoint by user. 
Example:
mountpoint for users: users/${username}/
mountpoint for superuser: users/

**Comment by zmstone** [comment]
Feature request accepted for now. Will bring it to the product team for more discussion.

A similar feature: https://www.emqx.io/docs/en/latest/messaging/mqtt-topic-rewrite.html#topic-rewrite

**Comment by zmstone** [comment]
Hi @burner- 
I just noticed that mountpoint is already templated.
Supported placeholders are `${clientid}`, `${username}`.

e.g. start EMQX with environment variable
`env EMQX_LISTENERS__TCP__DEFAULT__MOUNTPOINT='users/${username}/'`

**Comment by zmstone** [comment]
Here are more solutions:
- Create a dedicated listener for super users.
- After PR https://github.com/emqx/emqx/pull/12750 is merged, you'll be able to configure `mountpoint = users/${client_attrs.ATTR_NAME}/`. The client attribute can be initialized from client properties or extended with authentication data (HTTP or JWT).

Please close this issue if you think the above will work for you.
"Feature" tag is removed.

**Comment by zmstone** [comment]
the bot was wrong. it's planed and will be released in 5.7.0

**Comment by burner-** [comment]
I try figure out how to use this but I must say that I did not find way. I find that I can set client attrs at general mqtt settings. But how I set so that some or users got mounter to users/$user and some of users will mounted to root with this? I look that I am not alone with this question
https://forum.emqx.io/t/listeners-with-mountpoints-and-authorization/325
https://forum.emqx.io/t/can-i-isolate-users-with-de-topic-rewrite/1138
Can you explain little bit more how to use that attribute for this? That template works if we do not want do super users or scoped "super users".

**Comment by zmstone** [comment]
Here is an example

## Config
```
mqtt {
  client_attrs_init = [
    {
      # this expression check if username starts with 'super-', if yes, set 'mtp' attribute as 'users/',
      # otherwise set the attribute as 'users/{{username}}/'
      expression = "iif(regex_match(username,'^super-.+$'),'users/',concat(['users/',username,'/']))"
      set_as_attr = mtp
    }
  ]

listeners {
  tcp {
    default {
      mountpoint = "${client_attrs.mtp}"
  }
}
```

## Start two clients

```
mqttx sub -t '#' -h localhost -p 1883 -i 'c1' -u 'super-u1'
mqttx sub -t '#' -h localhost -p 1883 -i 'c2' -u 'u2'
```

## Subscriptions

<img width="533" alt="image" src="https://github.com/emqx/emqx/assets/164324/b014180a-4dc1-490e-a866-020f3f57e8c5">


## More info

The `client_attrs_init` expressions are evaluated before authentication.
This example assumes that the username pattern is (going to be) validated by authentication rules/backends.
For more complex logic, `client_attrs` can be extended by

1. HTTP authentication results
2. Providing a `client_attrs` claim in JWT

Read more about client attributes here: https://docs.emqx.com/en/enterprise/latest/client-attributes/client-attributes.html
