### ISSUE TITLE
[error] failed_to_check_schema: emqx_conf_schema

### ISSUE THREAD

**Issue by N0tronic** [emqx/emqx#12532]
### What happened?

Hey guys, 

I´d deleted an old bridge config from the value.yml before I deploy emqx over helm. 
But emqx still expected the bridge config and go into an error by startup:

`[error] failed_to_check_schema: emqx_conf_schema`
`[error] #{kind => validation_error,path => "bridges.mqtt.bridge_name.server",reason => required_field}`

Is there any to do, before delete variables from the config file, to prevent this error?

cheers

### What did you expect to happen?

Start the emqx system without the deleted bridge config

### How can we reproduce it (as minimally and precisely as possible)?

Define a bridge in the values.yml, start the system and update the system after deleted the bridge from the values.yml

### EMQX version

<details>

```console
$ ./bin/emqx_ctl broker
# sysdescr  : EMQX
version   : 5.4.1
```

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
$ uname -a
# Linux emqx-mqtt-0 5.14.21-150400.24.100-default #1 SMP PREEMPT_DYNAMIC Mon Dec 4 19:12:13 UTC 2023 (3f5cd84) x86_64 GNU/Linux
```

</details>

### Log files

<details>

</details>

**Comment by thalesmg** [comment]
Hi, are you using persistence in k8s (PVC)?

If you made changes to the bridge configuration using the dashboard UI, then those changes would have been saved to `data/configs/cluster.hocon`.  In that case, you would need to either delete the bridge using the dashboard, or edit the persisted `cluster.hocon` files as well.

**Comment by thalesmg** [comment]
Are you upgrading from some older version to 5.4.1, or from 5.4.1 to 5.5.0?

How many nodes are in your cluster?

Could you please share the contents of your `data/configs` directory?  i.e.: `ls data/configs`.
I'm checking if that directory contains a `cluster-overrides.conf` file by any chance.

Also, after deleting the bridge via the dashboard UI, could you please confirm that `cluster.hocon` does not contain any traces of said bridge?

**Comment by N0tronic** [comment]
There´re 3 nodes in the cluster. The problem is not even, if I try to upgrade the version. Also if I did a helm upgrade only with deleted bridge values in the values.yml

![image](https://github.com/emqx/emqx/assets/28871810/5574e223-951a-4ebd-88b0-466a2e5e4894)

There´re no more bridge options in the cluster.hocon file.

**Comment by N0tronic** [comment]
Should I sync the cluster config after delete the bridge over emqx dashboard? For example with the emqx_ctl tool?

**Comment by thalesmg** [comment]
> Should I sync the cluster config after delete the bridge over emqx dashboard? For example with the emqx_ctl tool?

Shouldn't be needed.  Using the dashboard already takes care of that.

> It´s possible that this is the same problem? #12311

Only if you are using environment variables like in that issue.  If something like `EMQX_BRIDGES__MQTT__...` is also being set, then it's likely the cause.

Could you share your `values.yaml` file (with any sensitive data censored)?

**Comment by thalesmg** [comment]
@N0tronic was the problem solved after removing the bridge-related environment variables from `values.yaml`?

**Comment by N0tronic** [comment]
I've solved the problem, but it was a bit more complicated. First the failure was still there, after I deleted all bridge variables from the values.yml

Then I realized, that I outsourced the bridge user password into a secret, that loaded as environment variable during deployment. Deleting the secret solved the problem. 

But I'm not very satisfied with this restricted behavior of the system. One forgotten bridge variable prevents the whole deployment 😩

**Comment by N0tronic** [comment]
I understand, it's a narrow line.  Some systems gives the user more flexibility, cause they can decide to turn the strict mode on or off. It would be nice, if u can think about such possibilities 🙂 

But more details in the logs is also great as a first step 👍🏼
