### ISSUE TITLE
Time zone offset in function format_date

### ISSUE THREAD

**Issue by tigercl** [emqx/emqx#12585]
### What happened?

The Offset parameter of the rule engine built-in function `format_date` supports `±hh:mm:ss`, but actually including `ss` will cause a conversion error.

```
# Offset is +08:00
format_date('millisecond', '+08:00', '%Y-%m-%d %H:%M:%S.%3N%:z', 1708933353472) = '2024-02-26 15:42:33.472+08:00'
```
`2024-02-26 15:42:33.472+08:00` = `2024-02-26 07:42:33.472Z`.

```
# Offset is +08:00:20
format_date('millisecond', '+08:00:20', '%Y-%m-%d %H:%M:%S.%3N%:z', 1708933353472) = '2024-02-26 15:42:53.472+08:00'
```
`2024-02-26 15:42:53.472+08:00` = `2024-02-26 07:42:53.472Z`

But the correct UTC time should be `2024-02-26 07:42:33.472`.

### What did you expect to happen?

The offset ss should be recorded in the output.

```
format_date('millisecond', '+08:00:20', '%Y-%m-%d %H:%M:%S.%3N%:z', 1708933353472) = '2024-02-26 15 :42:53.472+08:00:20'
```

### EMQX version

EMQX v5.4.1

### OS version

macOS 13.4

### Log files

<details>

</details>

**Comment by zmstone** [comment]
placeholder for time zone shift at seconds level is `%::z`, `%:z` is for minute level, and `%z` is for hour level.

below expression should match
```
format_date('millisecond', '+08:00:20', '%Y-%m-%d %H:%M:%S.%3N%::z', 1708933353472) = '2024-02-26 15 :42:53.472+08:00:20'
```
