### ISSUE TITLE
Rule engine processing of large numbers

### ISSUE THREAD

**Issue by tigercl** [emqx/emqx#12588]
### What happened?

First, large numbers may be displayed incorrectly in the Dashboard.

`rfc3339_to_unix_ts('2024-02-23T15:56:30.535904509Z', 'nanosecond')` returns 1708703790535904509, but the Dashboard shows 1708703790535904500.

Second, large numbers may not be written to the Backend correctly, for example, the size of BigInt type in MySQL is 8 bytes, and the rules engine may produce integers longer than 8 bytes (via the bitsl function).

One solution is to break the large number into multiple integers. A function with similar functionality is `subbits`, but it currently only supports binary data as input.

### What did you expect to happen?

1. Correctly display large numbers in the Dashboard.
2. Provides a method for writing large numbers to Backend.

### EMQX version

EMQX v5.4.1

### OS version

macOS 13.4

### Log files

<details>

</details>

**Comment by zmstone** [comment]
confirmed from @ysfscream it's been fixed in 5.6 (current `release-56` branch)
