### ISSUE TITLE
The return value of the subbits function cannot be JSON encoded

### ISSUE THREAD

**Issue by tigercl** [emqx/emqx#12586]
### What happened?

When calling subbits(Bytes, Start, BitNum, OutputType, Signedness, Endianness) in the SQL of the rule engine, if BitNum is not an integer multiple of 8, an error will be reported. For example:

```
SELECT
  bin2hexstr(subbits(hexstr2bin('9F4E58'), 1, 6, 'bits', 'unsigned', 'big')) as test
FROM "t/#
```

### What did you expect to happen?

```
bin2hexstr(subbits(hexstr2bin('9F4E58'), 1, 8, 'bits', 'unsigned', 'big')) = '9F'
# 1001 1111 => 1001 11 => Leading zero padding => 0010 0111 => 
bin2hexstr(subbits(hexstr2bin('9F4E58'), 1, 6, 'bits', 'unsigned', 'big')) = '27'
```

### EMQX version

EMQX v5.4.1
</details>

### OS version

macOS 13.4

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here
```

</details>

### Log files

<details>

</details>

**Comment by kjellwinblad** [comment]
Hi,
 
I'm not sure if I understand your text under "What did you expect to happen?". My guess is that you want bin2hexstr to pad the input with leading zeros until the size is divisible by 8 (padding until it is divisible by 4 should be enough) and then do the conversion?
 
 @tigercl I think bitstrings returned by subbits where the size is not divisible by 8 should not be outputed directly in the SQL. They should only be used as an intermediate data format in computations. At least this is what I think the TIP here https://www.emqx.io/docs/en/latest/data-integration/rule-sql-builtin-functions.html#bit-sequence-functions tries to explain.

Maybe it is enough to extend  bin2hexstr so it accepts all bitstrings?

**Comment by kjellwinblad** [comment]
I made a PR that updates bin2hexstr to handle all bitstrings:

https://github.com/emqx/emqx/pull/12653

Do you think we should also handle when the rule output fields with bitstrings with a bit size that is not divisible by 8? I think it was not a good design to allow such bitstrings as return values from subbits (it creates a lot of complication and probably not so much value) but I guess we are stuck with it now...

**Comment by tigercl** [comment]
Hi @kjellwinblad 

Extending bin2hexstr is a good idea.

However, I'm not sure it makes sense that the output of some functions cannot be directly used as input to JSON, despite the additional instructions given in the documentation.

This breaks some convention and makes me unsure if there will be more functions like this.

**Comment by kjellwinblad** [comment]
> However, I'm not sure it makes sense that the output of some functions cannot be directly used as input to JSON, despite the additional instructions given in the documentation.

I agree, but that function already exists so I'm not sure that we can change it. Is there any way users could use it so that it output a binary with a bit size not divisible by 8 and not cause a crash? If not, maybe it is not too late to change it to no allow such outputs? If we can restrict it, I think that would be the best.
