### ISSUE TITLE
mqtt.client.max_publish_rate not implemented?

### ISSUE THREAD

**Issue by trehn** [emqx/emqx#1261]
#### Environment

emqttd-ubuntu16.04-v2.2.0_amd64.deb

#### Description

I was wondering about this in the default config:

```
# Max publish rate of Messages
mqtt.client.max_publish_rate = 5
```

I assume this means that clients can publish at most five messages per second. We're definitely exceeding that, despite the line being present in our emq.conf.

So I grepped the EMQ source (current master, fffc7400):

```
$ grep -R max_publish_rate *
etc/emq.conf:## mqtt.client.max_publish_rate = 5
priv/emq.schema:{mapping, "mqtt.client.max_publish_rate", "emqttd.client", [
priv/emq.schema:  [{max_publish_rate, cuttlefish:conf_get("mqtt.client.max_publish_rate", Conf)},
src/emqttd_cli_config.erl:    ConfigKeys = ["max_publish_rate",
src/emqttd_cli_config.erl:    ConfigKeys = ["mqtt.client.max_publish_rate",
test/emqttd_config_SUITE.erl:    SetConfigKeys = [{"max_publish_rate=100", int},
test/emqttd_config_SUITE.erl:    ["max_publish_rate", V] ->
test/emqttd_config_SUITE.erl:        {list_to_atom("max_publish_rate"), format(Type, V)};
```

To me that looks as if the limit is not actually enforced anywhere. Am I wrong?

**Comment by emqplus** [comment]
@trehn This feature is in TODO list still.

**Comment by markrey** [comment]
@emqplus Any updates on this one?

**Comment by davorozo** [comment]
Is this feature already available? This is an important feature.

**Comment by terry-xiaoyu** [comment]
@davorozo Not yet. We are planning to implement this in EMQ 3.0.

**Comment by Gilbert-Wong** [comment]
It has been implemented in emqx3.0.0 , please download the latest edition of emqx and try with the new feature.
