### ISSUE TITLE
View incoming messages and their content live at broker.

### ISSUE THREAD

**Issue by lucifercr07** [emqx/emqx#1265]
#### Environment
-OS: Photon
- EMQ: 2.3 docker image

#### Description
Is there a way to view messages live, along with its content. I want to view messages incoming to emqtt broker at broker itself. i don't want to use RETAIN Flag, just live message stream.
I tried trace to trace packets incoming from specific client but log file remains blank.
Also can I trace a topic with # I suppose it's not supported.

**Comment by Gilbert-Wong** [comment]
Hi, @lucifercr07 , I'm so sorry for so late response. You could try our persistence plugin in emqx enterprise edition to realize you requirement.
