### ISSUE TITLE
Node 'emqx@192.168.0.250' not responding to pings

### ISSUE THREAD

**Issue by blociot** [emqx/emqx#12713]
### What happened?

Trying to install EMQX on a SBC with Debian 11 without a Desktop.
Logged in as root. Followed the instruction on link below:
https://www.emqx.io/docs/en/latest/deploy/install-debian.html#arm64

curl -s https://assets.emqx.com/scripts/install-emqx-deb.sh | sudo bash
sudo apt-get install emqx
sudo systemctl start emqx

no error up to this step. 
When trying to see the status with "emqx ctl status" command, I get the error: 
Node 'emqx@192.168.0.250' not responding to pings

I can access the web dashboard from another machine within the same network with http://192.168.0.250:18083/, but after entering the username and password (admin/public), I get an error message "netwrok error" 
![image](https://github.com/emqx/emqx/assets/135381294/cfa0031c-8af8-4abf-9be9-0b0abd8b633d)

from this point, I can no longer access the web admin after refreshing the page and emqx ctl status still returns the same error as mentioned above.

My config file:
![image](https://github.com/emqx/emqx/assets/135381294/b55147b3-1bb2-46a5-a1d1-7f9cf65d3a5f)

### What did you expect to happen?

Accessing the web dashboard from another browser on the same network and login in with admin/public for the first time

### EMQX version

<details>

```console
$ ./bin/emqx_ctl broker
./bin/emqx_ctl: No such file or directory
```

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
BUILD_ID="V01.02.02-0-g883c59c"
VARIANT="IOT2050 Debian Example Image"
VARIANT_VERSION="1.0"
$ uname -a
Linux iot2050 5.10.64 #1 SMP PREEMPT Mon Feb 21 03:00:38 UTC 2022 aarch64 GNU/Linux

```

</details>

### Log files

<details>

</details>

**Comment by id** [comment]
Hi @blociot. It looks like you are using "IOT2050 Debian Example Image", not vanilla Debian 11.
We haven't tested EMQX with this debian flavor.

Is there a docker image available that we can use for testing?

**Comment by zmstone** [comment]
Could you check emqx logs.
And sys log too.

**Comment by id** [comment]
@blociot 

```
journalctl -al -u emqx
```

and log files in `/var/log/emqx`

**Comment by id** [comment]
Thanks, this seems to be fairly simple.
There is another process in the system which is using port 1883. 

You could try to find what process is it with e.g. `sudo lsof -i tcp:1883` and kill it if you don't need it, or configure emqx to use another port for mqtt tcp listener https://www.emqx.io/docs/en/latest/configuration/listener.html#configure-tcp-listener
