### ISSUE TITLE
Message are being dropped  even the receiver client is connected

### ISSUE THREAD

**Issue by atulgoswami21** [emqx/emqx#1277]
Environment
OS: 4.9.43-17.39.amzn1.x86_64
Erlang/OTP: How do I find this?
EMQ: 2.1.2
Description
Message drop count increases even the receiver client is connected and receiving messages.
some message are dropping continuously in qos1.
attaching screenshot for reference.
![screenshot from 2017-09-28 14-31-19](https://user-images.githubusercontent.com/11611949/30958296-4c3424dc-a45a-11e7-97ec-021c68c2208d.png)
![screenshot from 2017-09-28 14-31-45](https://user-images.githubusercontent.com/11611949/30958295-4c3245f4-a45a-11e7-8e1b-9b270fa59afd.png)

Please help me.

**Comment by swarno** [comment]
I was also facing similar issue. Did you tweak the Mqueue size in the emq.conf. I think it stores only 1000 messages by default which can be increased to unlimited. Emqtt drops messages if the queue is full even for qos1. Not sure if my understanding is correct but this fixed my problem to some extent.

**Comment by turtleDeng** [comment]
If a message is sent and there is no subscription to this message, it will be dropped.

**Comment by atulgoswami21** [comment]
Issue still not resolved. around 10 percentage of message are dropping continuously.
Please look into this as i have only one client that is receiving all these messages.

**Comment by atulgoswami21** [comment]
![screenshot from 2018-02-23 19-03-58](https://user-images.githubusercontent.com/11611949/36596635-567f2fcc-18cc-11e8-9320-cb28c65824db.png)

**Comment by emqplus** [comment]
@atulgoswami21 How many clients publishing QoS1 messages?

**Comment by atulgoswami21** [comment]
Publishing clients are around 200, and there is one client that is receiving messages published on two topics. And it is receiving messages but around 10% drop message are accumulated in dashboard statistics.

**Comment by atulgoswami21** [comment]
Current Status.

**Comment by atulgoswami21** [comment]
![screenshot from 2018-03-05 11-30-54](https://user-images.githubusercontent.com/11611949/36959545-b1c24cea-2068-11e8-9159-9478cdaa9a53.png)

**Comment by emqplus** [comment]
@atulgoswami21 Please provide more information for the case, we will try to reproduce the issue:

1. The topics which clients subscribed and published to.
2. The CPU/Mem of the VM which EMQ is running on.
3. Are you sure the subscriber never reconnects to the broker?

**Comment by atulgoswami21** [comment]
I can provide you the access to my droplet. If you want.

Topics are /location and /application-events

CPU is single core ram is 1gb. Basic 5$ droplet on digital ocean. 

My subscriber checks every 15 minutes if connected. If not then connect and subscribe again.

**Comment by homerzhou** [comment]
@emqplus I want to know where I can find the message which is dropped.(not use open log debug)

**Comment by Gilbert-Wong** [comment]
@homerzhou , Sorry for late response, open source edtion of emqx do not support the feature that persist messages to disk, so the messages which are dropped could not be found except log debug. And the priority of qos0 message is too low to ensure the message could be delivered to your device, I do not suggest you to frequently deliver qos 0 message in production environment. EMQ X 3.0 is released now, welcome to try with our latest emqx broker.
