### ISSUE TITLE
[Question] topic life cycle - about recycling/expiry/TTL?

### ISSUE THREAD

**Issue by MarcMagnin** [emqx/emqx#1280]
In a scenario where an unbounded number of topics are created by clients, how do we delete unused/olders topics?
Are topics automatically 'removed' when no one is subscribed and no more messages are in the queue?
Is there is a way to provide some sort of a TTL on topics?

Many thanks!

**Comment by emqplus** [comment]
@MarcMagnin The topics and routes are created when there are subscriptions on a node in the cluster, and removed dynamically if no subscriptions in the cluster.
