### ISSUE TITLE
[error] msg: unrecoverable_error, mfa: emqx_resource_buffer_worker:handle_query_result_pure

### ISSUE THREAD

**Issue by SHMay100G** [emqx/emqx#12819]
I confirm that the webhook configuration is correct and the service API interface is unobstructed, but the webhook still reports an error

[error] msg: unrecoverable_error, mfa: emqx_resource_buffer_worker:handle_query_result_pure/3(930), id: <<"action:http:iot_WH_D:connector:http:iot_WH_D">>, reason: {unrecoverable_error,#{body => <<"<html>\r\n<head><title>404 Not Found</title></head>\r\n<body>\r\n<center><h1>404 Not Found</h1></center>\r\n<hr><center>nginx</center>\r\n</body>\r\n</html>\r\n">>,headers => [{<<"date">>,<<"Mon, 01 Apr 2024 07:06:57 GMT">>},{<<"content-type">>,<<"text/html">>},{<<"content-length">>,<<"146">>},{<<"connection">>,<<"keep-alive">>}],status_code => 404}}

**Comment by SergeTupchiy** [comment]
Hi @SHMay100G,

EMQX received 404 error from the web server. 
If you are sure that the server is working fine, please check `URL` set in WEB hook configuration. Perhaps it's wrong and thus the server responds with 404.
