### ISSUE TITLE
AWS IoT Bridge

### ISSUE THREAD

**Issue by PiedPieper** [emqx/emqx#1281]
#### Environment

- OS: Any
- Erlang/OTP: Any
- EMQ: Any

#### Description

Hello,

I posted 2 months ago about bridging between AWS IoT and Emqtt, and I am looking for an update on the issue. I have built a bridge, but it is incredibly simple and just uses the emqttc client as a plugin to subscribe to the topic that I want to bridge and have it republish the message back to my broker.

This method does not support any queue like the emq to emq bridge. Is this the proper way to implement the bridge? You mentioned that you would support it in 2.3, which is in beta right now.

Please let me know any progress you have made, any ideas that you have that are different than using a simple subscriber, I would like to help build this product.

Thanks.

**Comment by zhanghongtong** [comment]
In the latest v3.0-rc.3 release we have supported bridging to AWS IoT, and you can subscribe to topics or forward topics via bridge.
You can refer to the steps below to configure EMQ X bridge to AWS IoT.
1. Modify the configuration of `etc/emqx.conf`.
```
$ vim etc/emqx.conf

## Bridge address: node name for local bridge, host:port for remote.
##
## Value: String
## Example: emqx@127.0.0.1,  127.0.0.1:1883
bridge.aws.address = a1memimzxxxxxx-ats.iot.ap-northeast-2.amazonaws.com:8883	//Address of the AWS IoT endpoint：8883
## The Clean start flag of a remote bridge.
##
## Value: boolean
bridge.aws.clean_start = true
## Bribge to remote server via SSL.
##
## Value: on | off
bridge.aws.ssl = on
## SSL Certfile of the bridge.
##
## Value: File
bridge.aws.certfile = etc/certs/aws/2d714b6de4-certificate.pem.crt	//AWS IoT certificate
## SSL Keyfile of the bridge.
##
## Value: File
bridge.aws.keyfile = etc/certs/aws/2d714b6de4-private.pem.key	//AWS IoT private key
```
2. Start EMQ X and start EMQ X bridge.
```
$ ./bin/emqx start
emqx 3.0 is started successfully!
$ ./bin/emqx_ctl bridges list
name: aws     status: Stopped
$ ./bin/emqx_ctl bridges start aws
start bridge successfully.
```
3. Subscribe to a new topic via bridge.
```
$ ./bin/emqx_ctl bridges add-subscription aws subAWS 1
Add-subscription topic successfully.
$ ./bin/emqx_ctl bridges subscriptions aws
topic: subAWS, qos: 1
topic: cmd/topic1, qos: 1
topic: cmd/topic2, qos: 1
```
4. Forward a new topic via bridge
```
$ ./bin/emqx_ctl bridges add-forward aws forwardAWS
Add-forward topic successfully.
$ ./bin/emqx_ctl bridges forwards aws
topic:   forwardAWS
topic:   topic1/#
topic:   topic2/#
```
The topics that EMQ X forwards through the bridge are prefixed, and `etc/emqx.conf ` can view or modify the prefix.
```
$cat etc/emqx.conf
...
## Mountpoint of the bridge.
##
## Value: String
bridge.aws.mountpoint = bridge/aws/${node}/
```
`${node} ` is the node.name of EMQ X, the default is `emqx@127.0.0.1`. So the theme that EMQ X forwards should be `bridge/aws/emqx@127.0.0.1/forwardAWS`, subscribe to this topic via AWS IoT

**Comment by saqib-cielo** [comment]
Emqx as a bridge with AWS Iot broker behaving unexpectedly(getting duplicate messages burst with any Qos level), normally happen when we start publishing messages with some pace, check all config params but no luck, did anyone came across similar issue.
