### ISSUE TITLE
EMQX 2.4.3 dashboard : request failed with status code 500 error

### ISSUE THREAD

**Issue by SHREEKANT-KUMAR-PRASAD** [emqx/emqx#12813]
### What happened?

Enviroment :
os - openEuler 23.09v1
Architecture- riscv
EMQ X version 4.2.2
Qemu-8.0.0

I took the git hub source of emqx-rel. built it locally on my machine and started emqx broker. broker started successfully
. But when i go to dashbaord keep getting request failed with status code 500 error.
Erlang shell was also not responding i.e not erlang commands working in shell of erlang
    not able to view the metrics
    not able to add rule
    not able to view plugins

### What did you expect to happen?

I took the git hub source of emqx-rel. built it locally on my machine and started emqx broker. broker started successfully
. But when i go to dashbaord keep getting request failed with status code 500 error.

    not able to view the metrics
    not able to add rule
    not able to view plugins

### How can we reproduce it (as minimally and precisely as possible)?

2 Pre-requisites
Use the following command,
$ dnf install git cmake make cargo rustc	
STEP1 -  Install erlang/OTP.
$ dnf install erlang*	
$  erl –version	
 $ root@openeuler-riscv64 ~]# erl	
Erlang/OTP 23 [erts-11.2.2.8] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1]	
Eshell V11.2.2.8  (abort with ^G)	
1>	
STEP2 - To compile emqx use following commands.
$ git clone https://github.com/emqx/emqx-rel.git	
$ cd emqx-rel        
$git checkout 4.2.2	
$ make -j$(nproc)	
STEP2 - As the build is done, execute the following commands.
$ _build/emqx/rel/emqx/bin/emqx console	
EMQX-4.2.2
-------------------
run bin/emqx start
Go to http://localhost:18083/#/
try to navigate through monitor clients etc
you will see the error as [attached](https://github.com/emqx/emqx/issues/url)
![dashboardemqxerror](https://github.com/emqx/emqx/assets/158438609/e5d71f2c-0c08-4d09-b2f9-4e720d9608ac)
  

### EMQX version

EMQX version-4.2.2

### OS version

Os-openEuler
Version-23.09V1
qemu-8.0.0

### Log files

<details>

</details>

**Comment by ieQu1** [comment]
Hello,

v4.2.2 release is 4 years old: https://github.com/emqx/emqx/releases/tag/v4.2.2 
We no longer support it.
