### ISSUE TITLE
connection congested:

### ISSUE THREAD

**Issue by homonto** [emqx/emqx#12829]
### What happened?

whenever I restart EMQX or Home Assistant I receive the message: "connection congested:"
It stays for 1 second and disappears
but these messages are crucial not to be lost

### What did you expect to happen?

after restart of EMQX or Home Assistant

### How can we reproduce it (as minimally and precisely as possible)?

restart EMQX or Home Assistante

### Anything else we need to know?

```
full error:
connection congested: #{buffer => 4096,clientid => <<"1bcpmtfmY6Uxso3ORhm014">>,conn_state => connected,connected_at => 1712229244047,high_msgq_watermark => 8192,high_watermark => 1048576,memory => 5732272,message_queue_len => 440,peername => <<"192.168.100.41:40761">>,pid => <<"<0.3280.0>">>,proto_name => <<"MQTT">>,proto_ver => 4,recbuf => 176056,recv_cnt => 6,recv_oct => 17945,reductions => 606643,send_cnt => 11,send_oct => 454977,send_pend => 9958,sndbuf => 348160,sockname => <<"172.18.0.4:1883">>,socktype => tcp,username => <<"mqttrpiuser">>}
```

### EMQX version

<details>

```console
$ ./bin/emqx_ctl broker
# paste output here
```

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 12 (bookworm)"
NAME="Debian GNU/Linux"
VERSION_ID="12"
VERSION="12 (bookworm)"
VERSION_CODENAME=bookworm
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
$ uname -a
Linux 3e29e479feef 6.1.0-18-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.76-1 (2024-02-01) x86_64 GNU/Linux
```

</details>

### Log files

<details>

</details>

**Comment by SergeTupchiy** [comment]
Hi @homonto,
Do you just observe these alarms or some more severe issues also occur alongside? 
Congestion alarm only signifies that there are packets waiting to be sent by the socket.
