### ISSUE TITLE
Error:Mysql Connector Test Connectivity Error

### ISSUE THREAD

**Issue by gongna-au** [emqx/emqx#12822]
## 测试连接报错

400 TEST_FAILED: {start_pool_failed,<<"t_probe_79e227f66e8157abmysql:probedryrun">>,econnrefused}

### What did you expect to happen?

Successfully connected to Mysql

### How can we reproduce it (as minimally and precisely as possible)?

完整过程

## 获取Docker镜像
```shell
docker pull emqx/emqx-enterprise:5.6.0
```

## 启动Docker容器
```shell
docker run -d --name emqx-enterprise -p 1883:1883 -p 8083:8083 -p 8084:8084 -p 8883:8883 -p 18083:18083 emqx/emqx-enterprise:5.6.0
```

## 运行Mysql 

```shell
docker run --name mysql -p 3307:3306 -e MYSQL_ROOT_PASSWORD=public -d mysql
```

```shell
docker exec -it mysql bash
```

```shell
mysql -u root -p
```
Enter password: 

```shell
mysql> CREATE DATABASE emqx_data CHARACTER SET utf8mb4;
Query OK, 1 row affected (0.01 sec)

mysql> use emqx_data;
Database changed
mysql> CREATE TABLE emqx_messages (
    -> id INT AUTO_INCREMENT PRIMARY KEY,
    -> clientid VARCHAR(255),
    -> topic VARCHAR(255),
    -> payload BLOB,
    -> created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    -> );
Query OK, 0 rows affected (0.03 sec)

mysql> CREATE TABLE emqx_client_events (
    ->   id INT AUTO_INCREMENT PRIMARY KEY,
    ->   clientid VARCHAR(255),
    ->   event VARCHAR(255),
    ->   created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    -> );
Query OK, 0 rows affected (0.02 sec)
```
## 连接器配置
服务器地址 127.0.0.1:3307
数据库名emqx_data
用户名 root
密码public
未启用TLS 

## 测试连接报错

400 TEST_FAILED: {start_pool_failed,<<"t_probe_79e227f66e8157abmysql:probedryrun">>,econnrefused}
![image](https://github.com/emqx/emqx/assets/72332089/36792715-2592-425d-822f-b3c40c8123bf)
### Anything else we need to know?

gongna@GongNadeMacBook-Air ~ % docker --version
Docker version 25.0.5, build 5dc9bcc

### EMQX version

<details>

```console
$ ./bin/emqx_ctl broker
# paste output here
```

</details>

 emqx/emqx-enterprise:5.6.0

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here
```

</details>

Darwin GongNadeMacBook-Air.local 23.1.0 Darwin Kernel Version 23.1.0: Mon Oct  9 21:28:12 PDT 2023; root:xnu-10002.41.9~6/RELEASE_ARM64_T8103 arm64

### Log files

<details>

</details>

**Comment by SergeTupchiy** [comment]
Hi @gongna-au,
Docker containers are isolated, EMQX running in a docker container can't reach MySql running in another container at `127.0.0.1:3307` even though you have bound Mysql container port to host port with `-p 3307:3306`.
You need to create a Docker network so that containers can communicate with each other, though it would be easier to use `docker-compose` and define EMQX and MySql services. 
Another quick work-around is to use Docker container IP address, but this can be changed after each container restart:
```
# Set this IP address to the bridge config: 
docker inspect  -f '{{range.NetworkSettings.Networks}}{{.IPAddress}}{{end}}' mysql
```

**Comment by gongna-au** [comment]
非常感谢@SergeTupchiy 的回复😘

## 创建Docker网络
```shell
docker network create my-network
```
## 运行emqx
```shell
docker run -d --name emqx-enterprise --network my-network -p 1883:1883 -p 8083:8083 -p 8084:8084 -p 8883:8883 -p 18083:18083 emqx/emqx-enterprise:5.6.0
```
## 运行Mysql
```shell
docker run --name mysql --network my-network -p 3307:3306 -e MYSQL_ROOT_PASSWORD=public -d mysql
```

## 创建数据库和表
```shell
docker exec -it mysql bash
```
```shell
mysql -u root -ppublic
```
```shell
CREATE DATABASE emqx_data CHARACTER SET utf8mb4;
```

```shell
use emqx_data;
```

```shell
CREATE TABLE emqx_messages (id INT AUTO_INCREMENT PRIMARY KEY,clientid VARCHAR(255),topic VARCHAR(255),payload BLOB,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE emqx_client_events (id INT AUTO_INCREMENT PRIMARY KEY,clientid VARCHAR(255), event VARCHAR(255),created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
```

## 仪表盘连接
![image](https://github.com/emqx/emqx/assets/72332089/252707dc-2b25-4ab9-afda-def5762c3b6d)

输入的Mysql地址为`mysql`而不是`127.0.0.1:3307`
至此访问http://localhost:18083/#/connector/create变可以创建Mysql连接器并连接

**Comment by gongna-au** [comment]
## 让emqx 和Mysql都运行在宿主机`--network host`

## 运行emqx
```shell
docker run -d --name emqx-enterprise --network host emqx/emqx-enterprise:5.6.0
```
这条命令会启动一个名为emqx-enterprise的容器，该容器直接使用宿主机的网络。这意味着，任何EMQX企业版在容器内监听的端口（例如1883, 8083, 8084, 8883, 18083）都会直接在宿主机上开放，无需进行端口映射。

注意事项：
确保宿主机的这些端口（1883, 8083, 8084, 8883, 18083）未被其他服务占用。

## 运行Mysql
```shell
docker run --name mysql --network host -e MYSQL_ROOT_PASSWORD=public -d mysql
```
这条命令将启动一个名为mysql的容器，容器直接使用宿主机的网络。MySQL服务将在其默认端口3306上监听，而不是通过Docker在宿主机上映射到3307端口。

注意事项：
由于容器使用宿主机网络，MySQL服务将在宿主机的3306端口上直接对外开放。如果宿主机上已经有服务监听3306端口（例如另一个MySQL实例），则可能会导致端口冲突。

## 创建数据库和表
```shell
docker exec -it mysql bash
```
```shell
mysql -u root -ppublic
```
```shell
CREATE DATABASE emqx_data CHARACTER SET utf8mb4;
```
```shell
use emqx_data;
```
```shell
CREATE TABLE emqx_messages (id INT AUTO_INCREMENT PRIMARY KEY,clientid VARCHAR(255),topic VARCHAR(255),payload BLOB,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE emqx_client_events (id INT AUTO_INCREMENT PRIMARY KEY,clientid VARCHAR(255), event VARCHAR(255),created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
```

当使用--network host参数运行Docker容器时，容器会直接使用后续机的网络命名空间。这意味着容器中的应用程序将直接在后续机的网络上运行，而不是在Docker自己的虚拟网络中因此，使用--network host时指定的任何如图所示的端口映射（-p或--publish参数）都将被忽略，正如 Docker 运行时给出的警告：
```shell
WARNING: Published ports are discarded when using host network mode
```
这是因为在一个机网络模式下，容器与一个机共享的网络堆栈，容器内的服务可以直接监听一个机的端口，而不是需要通过Docker进行端口映射。，如果你的服务（比如EMQX）或MySQL）配置为监听预设那么端口（例如EMQX默认监听1883），它们将直接在对应机的对应端口上可用，而不需要Docker来管理端口映射。

## 创建Mysql连接器

![image](https://github.com/emqx/emqx/assets/72332089/5800f8fa-29ff-4330-a802-0b74846f1402)
输入的Mysql地址为127.0.0.1:3306 而不是127.0.0.1:3307或者直接是mysql 🤔

**Comment by gongna-au** [comment]
@SergeTupchiy 
Regarding what you said, use the `docker inspect -f '{{range.NetworkSettings.Networks}}{{.IPAddress}}{{end}}' mysql` command to get the IP address of Mysql, and then use this in the connector configuration It is feasible to connect to Mysql using IP+Port👍
![image](https://github.com/emqx/emqx/assets/72332089/0410f0b3-0f05-43a9-be73-3d0f85125363)
The address of the configured Mysql server is the IP obtained by `docker inspect` + the port 3306 inside the container
Thank you for your patient reply

**Comment by SergeTupchiy** [comment]
Happy to help, @gongna-au!
