### ISSUE TITLE
Grafana dashboard should use $__rate_interval

### ISSUE THREAD

**Issue by uhthomas** [emqx/emqx#12864]
### What happened?

The Grafana dashboard for EMQX seems to not have been updated in a while and has some quirks. Specifically, all rates are calculated with a 20s interval. This causes issues for larger time ranges, and the `$__rate_interval` variable should be used instead.

https://grafana.com/grafana/dashboards/17446-emqx/

#### 6h

![image](https://github.com/emqx/emqx/assets/9749173/6dcec2a3-9c9c-41e5-af65-b52f2cee2076)

#### 12h

![image](https://github.com/emqx/emqx/assets/9749173/aef59304-c3a6-49d6-a8d4-8b3a63e86005)

#### 12h with $__rate_interval instead of 20s

![image](https://github.com/emqx/emqx/assets/9749173/cce366a8-6342-4611-97dc-0ed6af276cb1)

### EMQX version

<details>

```console
$ ./bin/emqx_ctl broker
# paste output here
```

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here
```

</details>

### Log files

<details>

</details>

**Comment by qzhuyan** [comment]
@ysfscream I think it is in your domain?

**Comment by ysfscream** [comment]
Hi @uhthomas. I'm sorry for not getting back to you sooner. We've confirmed the issue with the fixed 20-second interval and will update the dashboard to use `$__rate_interval` for better accuracy. We'll let you know once it's done. Thanks for your patience and helpful feedback! And thanks to @qzhuyan for mentioning me.

**Comment by ysfscream** [comment]
Hi @uhthomas, we've updated the dashboard to use `$__rate_interval` for rate metrics and kept the 20s min step. Thanks for your input! Check the latest version at https://grafana.com/grafana/dashboards/17446-emqx/. Your feedback is welcome!

I think this issue should be resolved now. If possible, we can close this issue. @qzhuyan @id @zmstone
