### ISSUE TITLE
Enhanced Authentication Failed with Reason Code 135 (Not Authorized).

### ISSUE THREAD

**Issue by ting-ms** [emqx/emqx#12860]
### What happened?

I was trying to test MQTT 5.0 enhanced authentication feature. Currently, EMQX has SCRAM authentication supported. 
Here's the details about the configuration and the encountered issues:
1. Create MQTT 5.0 enhanced authentication SCRAM through EMQX dashboard, with Password Hash set to sha256.
2. Create a user with username = "user1", password = "123456".
3. Connect to the broker using enhanced authentication.
4. Broker responded with ConAck with reason: "NotAuthorized".
<img width="1097" alt="image" src="https://github.com/emqx/emqx/assets/65648712/ca2411da-33ab-4321-9264-fd1ecff42049">

On the MQTT client side, I utilized [rustbase_scram](https://docs.rs/rustbase-scram/latest/rustbase_scram/) crate for calculating the client first and client final messages. I also experimented with a python version SCRAM library, available [here](https://pypi.org/project/scramp/#scramp-scramclient). Both RUST SCRAM and Python SCRAM generates the same client proof using the same client first and server first messages. This suggests that the client proof sent from the client is accurate. So I guess there might be another factor causing the authentication failure. Could you offer any advice on this matter? Additontally, I've included EMQX log information for further reference.

### What did you expect to happen?

More detailed information about the failure.

### EMQX version

Version: 5.5.1
Installed through Docker package.

### Log files

**Comment by qzhuyan** [comment]
nonce in client finial doesn't match. 

expecting: 

`LXJbjM+4lQHAvt|ZAn%=P0POHT2^e<yVdL&YQm`

get:

`LXJbjM+4lQHAv*t|ZAn%=P0POHT2^e<yVdL&YQm`

**Comment by ting-ms** [comment]
Hi @qzhuyan, Thank you for your response. The log information I shared earlier has "*" character being deleted while doing copy paste. I have included the complete log file along with the Wireshark captured packages in the attached zip folder.
[auth_test.zip](https://github.com/emqx/emqx/files/14953024/auth_test.zip)

**Comment by qzhuyan** [comment]
@ting-ms could you share your rumqttc branch will be helpful for me to trouble shoot.
So far I could just see the proof is wrong but don't know why.

**Comment by qzhuyan** [comment]
@ting-ms I guess I found the issue.

could you patch the emqx with this patch? just put the *.beam file under `patches` dir and restart emqx.

*remember to unzip first!*
[esasl_scram.beam.zip](https://github.com/emqx/emqx/files/14959757/esasl_scram.beam.zip)

**Comment by ting-ms** [comment]
@qzhuyan I have do the test again with the patch you provided, the issue persists. Please refer to the attached file for package information and the EMQX log.
[auth_test_0415.zip](https://github.com/emqx/emqx/files/14973694/auth_test_0415.zip)

How can I check whether the patch has been successfully applied?

**Comment by qzhuyan** [comment]
@ting-ms really appreciate your test. I compiled the [rustbase_scram](https://docs.rs/rustbase-scram/latest/rustbase_scram/)  and played with it and find it could not interop with the scram module (even with the patched one) in EMQX, 
I have narrowed the scope and investigating it.

**Comment by qzhuyan** [comment]
@ting-ms I managed to make it to work with [rustbase_scram](https://docs.rs/rustbase-scram/latest/rustbase_scram/)
from API to API testing, it looks fine, but I want to ensure it work end to end.

[esasl_scram.beam.zip](https://github.com/emqx/emqx/files/14979576/esasl_scram.beam.zip)
could you try above patch?  remember to unzip first!

to ensure the patch is loaded, you could run the following command:
```
emqx eval 'c:m(esasl_scram)'
```
it should print that the `Object file` points to the patched file

**Comment by ting-ms** [comment]
@qzhuyan Thank you for your efforts! I applied your patch and successfully passed the enhanced authentication.

**Comment by milelahiton** [comment]
Hello, I have an emqx in a deployment within kubernetes and I apply your patch. However, I cannot authenticate, I used a python client. Could you help me?
