### ISSUE TITLE
Can not view retained messages in admin dashboard after updating to 5.6.0 from 5.5.1

### ISSUE THREAD

**Issue by jandillmann** [emqx/emqx#12875]
### What happened?

I updated my EMQX cluster that is run via Docker on two nodes from 5.5.1 to 5.6.0. After the update, I am no longer able to see the "Retained Messages" under the "Monitoring" menu in the admin dashboard. The following error message is shown in a red alert popup as well as in the EMQX log:

`
500 INTERNAL_ERROR: exit, {{badarg,[{qlc,next_answers,[{error,qlc,{file_error,"/opt/emqx/fs_emqx@mydomain_1_10195.1",eacces}},20],[{file,"qlc.erl"},{line,535}]},{emqx_retainer_mnesia,qlc_next_answers,2,[{file,"emqx_retainer_mnesia.erl"},{line,413}]},{emqx_retainer_mnesia,page_read,4,[{file,"emqx_retainer_mnesia.erl"},{line,243}]},{emqx_retainer,handle_call,3,[{file,"emqx_retainer.erl"},{line,257}]},{gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,1131}]},{gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,1160}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,241}]}]},{gen_server,call,[emqx_retainer,{page_read,undefined,1,20},infinity]}}, [{gen_server,call,3,[{file,"gen_server.erl"},{line,419}]},{emqx_retainer_api,lookup_retained,2,[{file,"emqx_retainer_api.erl"},{line,188}]},{minirest_handler,apply_callback,3,[{file,"minirest_handler.erl"},{line,152}]},{minirest_handler,handle,2,[{file,"minirest_handler.erl"},{line,56}]},{minirest_handler,init,2,[{file,"minirest_handler.erl"},{line,27}]},{cowboy_handler,execute,2,[{file,"cowboy_handler.erl"},{line,41}]},{cowboy_stream_h,execute,3,[{file,"cowboy_stream_h.erl"},{line,318}]},{cowboy_stream_h,request_process,3,[{file,"cowboy_stream_h.erl"},{line,302}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,241}]}]
`

### What did you expect to happen?

I expected to be able to view the retained messages like before the update.

### EMQX version

<details>

```console
$ ./bin/emqx_ctl broker
sysdescr  : EMQX
version   : 5.6.0
datetime  : 2024-04-13T11:01:32.860448686+00:00
uptime    : 36 minutes, 5 seconds
```

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
PRETTY_NAME="Ubuntu 22.04.4 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.4 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
$ uname -a
Linux myhostname 5.15.0-102-generic #112-Ubuntu SMP Tue Mar 5 16:50:32 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
```

</details>

**Comment by zmstone** [comment]
eacces hints filesystem permission issue.
could you check if the dir /opt/emqx/fs_emqx (mounted to docker?) can be read by the `emqx` user?

**Comment by jandillmann** [comment]
Yes that was my first thought, too – but the directories were created by the Docker image of emqx 5.5.1 and are accessible by UID/GID 1000 (emqx inside the container).

Interestingly, after switching from Retained messages on disk to RAM and back to disk the error message changed:

`500 INTERNAL_ERROR: exit, {noproc,{gen_server,call,[emqx_retainer,{page_read,undefined,1,20},infinity]}}, [{gen_server,call,3,[{file,"gen_server.erl"},{line,419}]},{emqx_retainer_api,lookup_retained,2,[{file,"emqx_retainer_api.erl"},{line,188}]},{minirest_handler,apply_callback,3,[{file,"minirest_handler.erl"},{line,152}]},{minirest_handler,handle,2,[{file,"minirest_handler.erl"},{line,56}]},{minirest_handler,init,2,[{file,"minirest_handler.erl"},{line,27}]},{cowboy_handler,execute,2,[{file,"cowboy_handler.erl"},{line,41}]},{cowboy_stream_h,execute,3,[{file,"cowboy_stream_h.erl"},{line,318}]},{cowboy_stream_h,request_process,3,[{file,"cowboy_stream_h.erl"},{line,302}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,241}]}]`

**Comment by keynslug** [comment]
Hi @jandillmann,

> after switching from Retained messages on disk to RAM and back to disk the error message changed

I'm also curious why this happens.
1. Could you please describe what steps did you perform to make a switch?
2. Were there any warnings / errors in the EMQX service logs coinciding with this switch?

> `{file_error,"/opt/emqx/fs_emqx@mydomain_1_10195.1",eacces}`

I suspect that this is an unintended consequence of 58d0f040569a2a9a20dcaf6351c6493127c2067a. If so, forcing the container's workdir to `/opt/emqx/data` instead supposedly might help.

**Comment by keynslug** [comment]
> Could this be the issue, even if both directories and their sub-directories and files are owned by UID/GID 1000 and `rwx`?

No this should be fine I guess. It's the fact that `/opt/emqx` is not writable by UID 1000 in the container file system anymore that (supposedly) causes these weird errors. That's why I think you might try setting `working_dir: /opt/emqx/data` in `compose.yaml`, so that those temporary files EMQX want to write from time to time will reside there instead.

**Comment by jandillmann** [comment]
Sadly this did not help. I set `working_dir: /opt/emqx/data` in `compose.yaml` and restarted the stack with `docker compose down && docker compose up -d`, but the same error as in the [original issue](https://github.com/emqx/emqx/issues/12875#issue-2241512030) still shows.

**Comment by keynslug** [comment]
> Sadly this did not help.

Oh, that was unexpected. Thanks anyway for trying out and for the original report. Hopefully #12875 fixes this properly, which should land in the next release.
