### ISSUE TITLE
EMQX Clustering - Message Replication

### ISSUE THREAD

**Issue by KaeYan93** [emqx/emqx#12896]
### What would you like to be added or enhanced?

Does EMQX clustering supports message replication? So far, i only saw routing table data replication. If not mistaken, routing table is to track which node the client is connected to. 

### Why is this needed?

This is needed to reduce data loss and to fulfill requirement of minimal data loss.

**Comment by qzhuyan** [comment]
could you describe in which scenario you get data loss?

**Comment by KaeYan93** [comment]
Based on image below, at step 3: Routing, what if node 1 goes down before the message is routed? My understanding is that the message will be lost right? 

![image](https://github.com/emqx/emqx/assets/140130456/a4998d25-05a4-41cd-8906-6cd7cc4ef252)

**Comment by ieQu1** [comment]
EMQX v5.7 will include persistent messages with Raft-based replication.

**Comment by zmstone** [comment]
Closed because the feature is already in scope of 5.7 release.
