### ISSUE TITLE
Not getting Emqx dashboard 

### ISSUE THREAD

**Issue by SHREEKANT-KUMAR-PRASAD** [emqx/emqx#12891]
### What happened?

![getting blank dashboard of emqx after connecting with web browser](https://github.com/emqx/emqx/assets/158438609/0d731cfc-6aaa-435b-af5e-7382c954bd22)

![getting error while connecting emqx dashbord ](https://github.com/emqx/emqx/assets/158438609/ff4c0003-3b10-4b23-ba18-a7568982eba9)

After successful start of emqx service when I tried to connect of Emqx dashboard I getting blank page in place of dashboard and also get some error in log 

### What did you expect to happen?

After successful start of emqx service there we also able to access emqx dashboard on 
http://localhost:18083/ on web but its not coming up and in its logs throws error.

### How can we reproduce it (as minimally and precisely as possible)?

actually we are building emqx 5.0.0 for our os from github source and using Erlang otp 23 but after native build of emqx.the emqx service started but dashboard not up

### EMQX version

EMQX 5.0.0

### OS version

<details>

Os-OpenEuler-23.09v1
Welcome to 6.4.0-g0e93d276d93e

System information as of time: 	Tuesday 16 April 2024 03:05:05 PM CST

System load: 	4.13
Processes: 	154
Memory used: 	2.9%
Swap used: 	0.0%
Usage On: 	71%
IP address: 	10.0.2.15
Users online: 	2

</details>

### Log files

<details>

</details>
![Uploading after starting emqx  erlang shell.png…]()

**Comment by keynslug** [comment]
Hi @SHREEKANT-KUMAR-PRASAD,

> EMQX 5.0.0

I have to say this version is too old and unsupported for quite some time. Please try running more recent EMQX version.

Feel free to reopen this issue if you will observe similar issue.
