### ISSUE TITLE
STOMP GW does not send heartbeat to client

### ISSUE THREAD

**Issue by shinedd** [emqx/emqx#12911]
### What happened?

I am using obuspa as a stomp client to test with emqx stomp gw, and i get a error message:
![image](https://github.com/emqx/emqx/assets/106661626/49e3d4d6-d769-425f-8b09-f5d87b3c58d1)

### What did you expect to happen?

Could emqx stomp gw support sending heartbeat to stomp client

### EMQX version

sysdescr  : EMQX
version   : 5.5.1
datetime  : 2024-04-22T19:25:59.961416581+08:00
uptime    : 10 days, 9 hours, 35 minutes, 26 seconds

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here
```

</details>

### Log files

<details>

</details>

**Comment by HJianBo** [comment]
Hi, @shinedd I'm not sure what's kinds of `Heartbeat` you mentioned, because the standard stomp v1.2 protocol spec doesn't have heartbeat definition https://stomp.github.io/stomp-specification-1.2.html#Client_Frames

Could you give me some code examples to reproduce that?

**Comment by shinedd** [comment]
I'm new for stomp, i just find this problem during testing with tr369 client:
https://github.com/BroadbandForum/obuspa
And when i change cx > 0 or cy > 5000
![image](https://github.com/emqx/emqx/assets/106661626/189f1342-c7b4-44f8-b1f2-673da472cc84)
I will get this error log

**Comment by shinedd** [comment]
When i set cy to 5000, i found the heartbeat interval is about 15s in captured package
![image](https://github.com/emqx/emqx/assets/106661626/dbd3702b-f1b5-4e0d-83e4-494511d26fb3)

**Comment by cisiqo** [comment]
@shinedd yes, my branch had fix the bug, you can use to test.

**Comment by cisiqo** [comment]
Oh, no. Please pay attention to this https://github.com/emqx/emqx/pull/12920#issuecomment -2167477207

**Comment by shinedd** [comment]
I have tested with this branch https://github.com/cisiqo/emqx/tree/patch-6
The test results are the same

**Comment by cisiqo** [comment]
Try it again, i have fix it.

**Comment by shinedd** [comment]
![image](https://github.com/emqx/emqx/assets/106661626/b15ac89c-6f71-4af3-8af4-e6a6af647cb0)
it seems work, tks
