### ISSUE TITLE
EMQ bridge to/from AMQP/RabbitMQ?

### ISSUE THREAD

**Issue by Eric24** [emqx/emqx#1295]
I've been studying options for a better more scalable MQTT broker and I'm very impressed by EMQ. In reading the documentation and other information I could find on-line, I have a couple of questions about bridging with AMQP (specifically RabbitMQ):

1. Does that bridge plug-in exist (it's mentioned in the readme and shown on the "ins/outs diagram", but I can't find the actual plug-in)?
2. From other details in the documentation, it appears that such a bridge will allow messages to pass from EMQ to AMQP, but does it also work from AMQP to EMQ?
3. My ideal solution would allow EMQ to publish received MQTT messages to a RabbitMQ Exchange and to subscribe to a RabbitMQ Queue and forward those messages to MQTT subscribers. Is this possible?

Thank you in advance for your help!

**Comment by BorisPetelj** [comment]
Also interested. Any inputs by now?

**Comment by snoopckuu** [comment]
I am also interested any updates please?

**Comment by Talanor** [comment]
Hello, an (almost) monthly up in order to have news concerning this feature. Thanks.

**Comment by turtleDeng** [comment]
@Eric24 
emqx-enterprise support message bridge to RabbitMQ
https://www.emqx.io/downloads/emq/enterprise?osType=Linux
