### ISSUE TITLE
webhook监听上下线事件时，事件时序有误，原因不明（connected and disconnected events may out of order)

### ISSUE THREAD

**Issue by hotraygroup** [emqx/emqx#12954]
### What happened?

客户端：mqtt 3.1.1
eqmx:  5.4.1
通过webhook监听客户端断开和上线事件，一次断开重连的事件时序异常：
![image](https://github.com/emqx/emqx/assets/3041120/dbc1d99d-9b5a-4360-9c20-8cf50f639312) 重新上线时间
![image](https://github.com/emqx/emqx/assets/3041120/f72b1bca-1b60-4808-bd27-f95a03f6d35a) 前一次断开时间

### What did you expect to happen?

期望：前一次断开事件早于重新上线事件
现状：前一次断开事件晚于重新上线事件

### EMQX version

<details>
5.4.1
```console
$ ./bin/emqx_ctl broker
# paste output here
```

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here
```

</details>

### Log files

<details>

</details>

**Comment by hotraygroup** [comment]
非必现，时有发生

**Comment by zmstone** [comment]
Hello @hotraygroup 
这一个已知，但是不计划解决的问题。
重链后处理新连接的进程不是同一个，也可能不是同一个节点，事件被触发后也有可能是异步发送事件到 webhook（或者其他数据集成），所以也无法保证投递顺序。
要保证事件严格有序会需要引入全局锁，或者把事件序列化，对性能造成的损失可能远大于解决两个异步事件带来的收益。

**Comment by zmstone** [comment]
This is a known, but won't fix issue.

The new connection after reconned is handled by a different process,
when cluster, it might be handled by a different node.
The events might be delivered async-ly towards webhook (or other data sinks).

To ensure order, we may need to either introduce a global lock, or serialise the events by one single actor
--- we believe the performance loss does not worth it

**Comment by yurenchen000** [comment]
这种情况下 (外部程序) 如何得到/维护可靠的在线列表呢?
每次收到事件 再去 list接口 复查吗 (这感觉有点重)

**Comment by yurenchen000** [comment]
通过订阅 sys topic (disconnected, connected)
 获得上下线事件 是不是也面临类似情况
