### ISSUE TITLE
mqtt.max_packet_size

### ISSUE THREAD

**Issue by ulutomaz** [emqx/emqx#1298]
#### Environment

- OS: Ubuntu 16.04
- Erlang/OTP: 
- EMQ: 

#### Description

Was searching for a Slack or Irc, so I will just like to ask a quick question. Is it possible to have different rules about size of the message per different topics on broker? I would need, for one topic, to have bigger packet size configured. I need it for a "service topic" where I would have some firmware code and would need size to be around 400 KB. And I assume that size like this could mean a performance degradation if it would be set for all topics on a high load broker.

```
## Max Packet Size Allowed, 64K by default.
mqtt.max_packet_size = 64KB
```

Best,

**Comment by tigercl** [comment]
It's not a standard feature in MQTT 5.0, so we won't implement it right now.
