### ISSUE TITLE
For my project required kafka and kerberos integration with EMQX  opensource,So any how is it possible to do these integration with Emqx OPenSource version

### ISSUE THREAD

**Issue by SHREEKANT-KUMAR-PRASAD** [emqx/emqx#13000]
### What would you like to be added or enhanced?

As EMQX is used for multiple edge devices, if EMQX Open Source supports Kafka, it's easy to send messages to different sources. Kerberos is considered best for authentication.

### Why is this needed?

As EMQX is used for multiple edge devices, if EMQX Open Source supports Kafka, it's easy to send messages to different sources. Kerberos is considered best for authentication.

**Comment by kjellwinblad** [comment]
Hi,

EMQX Enterprise Edition supports Kafka with Kerberos authentication (both consumer and producer) (see: https://www.emqx.io/docs/en/latest/data-integration/data-bridge-kafka.html).

We have intentionally left such support out of the open source edition as we want users to pay for EMQX Enterprise Edition.

Hope this helps!

**Comment by zmstone** [comment]
As there is no plan to release kafka integration in Opensource edition, I’m closing this feature request.
