### ISSUE TITLE
Unable to change Web Dashboard user/pwd

### ISSUE THREAD

**Issue by jwestra** [emqx/emqx#1302]
#### Environment

- OS: Ubuntu 14
- Erlang/OTP: 
- EMQ:  2.3-RC1
 
#### Description
I cannot figure out how to change the default username/password for the EMQ Web Dashboard user.  Is this a documentation bug?  Examples missing?

**Comment by turtleDeng** [comment]
@jwestra 
http://emqtt.io/docs/v2/commands.html#admins-passwd

**Comment by jwestra** [comment]
Hi, I see there is a command.  Does that require the node to be running?  I don't want to start the node up with a 'public' password, change it, and then, restart. I'd rather configure in, say, plugins/emq_dashboard.conf and start one time.  Or, pass it on the commandline at start-up.

**Comment by Gilbert-Wong** [comment]
Sorry for so late reply, @jwestra , emqx 3.0 should fix the problem you refered. Please try with the emqx3.0.0 :p.
