### ISSUE TITLE
LDAP server treated as down due to wrong error returned than expected?

### ISSUE THREAD

**Issue by JJGadgets** [emqx/emqx#13099]
### What happened?

I am trying to use EMQX open source with authentication and authorization delegated to glauth, an LDAP server.

However, EMQX treats the LDAP server as "down" because the healthcheck queries the LDAP server with `cn=checkalive` as the query and expects *the correct error* of `InvalidDNSyntax`, while glauth is returning `insufficientAccessRights` because the base DN is missing.

### What did you expect to happen?

The LDAP server be treated as "Up" by the healthcheck.

### How can we reproduce it (as minimally and precisely as possible)?

Here is my EMQX CustomResource with the EMQX config: <https://github.com/JJGadgets/Biohazard/blob/fb28a64e4136ba5e93b08504a50fb1bb05c75770/kube/deploy/core/db/emqx/cluster/emqx.yaml#L13-L53>

Here is my glauth config: <https://github.com/JJGadgets/Biohazard/blob/fb28a64e4136ba5e93b08504a50fb1bb05c75770/kube/deploy/core/db/emqx/cluster/es.yaml#L29-L64>

### Anything else we need to know?

The code that I think is in question is <https://github.com/emqx/emqx/blob/625fcd5821ae932b8e940ff385f6f9d0df2f57ca/apps/emqx_ldap/src/emqx_ldap.erl#L217-L222>.

### EMQX version

<details>

```console
$ ./bin/emqx_ctl broker
sysdescr  : EMQX
version   : 5.6.1
datetime  : 2024-05-23T02:15:59.799114488+00:00
uptime    : 16 minutes, 55 seconds
```

</details>

### OS version

Running with public.ecr.aws/emqx/emqx:5.6.1@sha256:b14a3c6d04f680869e3ca181b552c9338b7cd20c2d43d8af6c1e3b8aec48a0cc container image in Kubernetes on Talos Linux.

### Log files

<details>

```
emqx-core-cc7b58b74-2 emqx 2024-05-23T02:01:09.054397+00:00 [info] msg: starting_ldap_connector, config: #{backend => ldap,base_dn => <<"cn=${username},ou=emqx,ou=users,dc=emqx,dc=io">>,enable => true,filter => <<"(objectClass=*)">>,mechanism => password_based,method => #{bind_password => <<"******">>,type => bind},password => "******",pool_size => 1,query_timeout => 10000,request_timeout => 10000,server => "glauth.emqx.svc.cluster.local.:636",ssl => #{ciphers => [],depth => 10,enable => true,hibernate_after => 5000,log_level => notice,reuse_sessions => true,secure_renegotiate => true,server_name_indication => "<censored>",verify => verify_none,versions => ['tlsv1.3','tlsv1.2']},username => <<"cn=search,ou=search,ou=users,dc=emqx,dc=io">>}, connector: <<"emqx_authn_ldap:5">>
emqx-core-cc7b58b74-2 emqx 2024-05-23T02:01:09.053818+00:00 [debug] msg: eldap_info, log: search request = {'SearchRequest',"cn=checkalive",wholeSubtree,derefAlways,0, 0,false, {approxMatch,{'AttributeValueAssertion',[],[]}}, []}
emqx-core-cc7b58b74-2 emqx 2024-05-23T02:01:09.059208+00:00 [debug] msg: eldap_info, log: search reply = {ok,{'LDAPMessage',2, {searchResDone, {'LDAPResult',insufficientAccessRights,[],[], asn1_NOVALUE}}, asn1_NOVALUE}}
emqx-core-cc7b58b74-2 emqx 2024-05-23T02:01:09.061530+00:00 [warning] msg: alarm_is_deactivated, name: <<"emqx_authz_ldap:3">>
emqx-core-cc7b58b74-2 emqx 2024-05-23T02:01:09.105194+00:00 [debug] msg: eldap_info, log: bind request = {'BindRequest',3, <<"cn=search,ou=search,ou=users,dc=emqx,dc=io">>, {simple,"******"}}
emqx-core-cc7b58b74-2 emqx 2024-05-23T02:01:09.147105+00:00 [debug] msg: eldap_info, log: bind reply = {ok,{'LDAPMessage',1, {bindResponse, {'BindResponse',success,[],[],asn1_NOVALUE, asn1_NOVALUE}}, asn1_NOVALUE}}
emqx-core-cc7b58b74-2 emqx 2024-05-23T02:01:09.148443+00:00 [info] msg: start_ecpool_ok, pool_name: <<"emqx_authn_ldap:5">>
emqx-core-cc7b58b74-2 emqx 2024-05-23T02:01:09.148874+00:00 [info] msg: starting_ldap_bind_worker, pool: <<"emqx_authn_ldap:5-bind_worker">>
emqx-core-cc7b58b74-2 emqx 2024-05-23T02:01:09.212256+00:00 [debug] msg: eldap_bind_info, log: bind request = {'BindRequest',3, <<"cn=search,ou=search,ou=users,dc=emqx,dc=io">>, {simple,"******"}}
emqx-core-cc7b58b74-2 emqx 2024-05-23T02:01:09.253780+00:00 [debug] msg: eldap_bind_info, log: bind reply = {ok,{'LDAPMessage',1, {bindResponse, {'BindResponse',success,[],[],asn1_NOVALUE, asn1_NOVALUE}}, asn1_NOVALUE}}
emqx-core-cc7b58b74-2 emqx 2024-05-23T02:01:09.254217+00:00 [info] msg: start_ecpool_ok, pool_name: <<"emqx_authn_ldap:5-bind_worker">>
emqx-core-cc7b58b74-2 emqx 2024-05-23T02:01:09.255878+00:00 [debug] msg: eldap_info, log: search request = {'SearchRequest',"cn=checkalive",wholeSubtree,derefAlways,0, 0,false, {approxMatch,{'AttributeValueAssertion',[],[]}}, []}
emqx-core-cc7b58b74-2 emqx 2024-05-23T02:01:09.263198+00:00 [debug] msg: eldap_info, log: search reply = {ok,{'LDAPMessage',2, {searchResDone, {'LDAPResult',insufficientAccessRights,[],[], asn1_NOVALUE}}, asn1_NOVALUE}}
emqx-core-cc7b58b74-2 emqx 2024-05-23T02:01:09.269837+00:00 [debug] msg: eldap_bind_info, log: search request = {'SearchRequest',"cn=checkalive",wholeSubtree,derefAlways,0, 0,false, {approxMatch,{'AttributeValueAssertion',[],[]}}, []}
emqx-core-cc7b58b74-2 emqx 2024-05-23T02:01:09.279270+00:00 [debug] msg: eldap_bind_info, log: search reply = {ok,{'LDAPMessage',2, {searchResDone, {'LDAPResult',insufficientAccessRights,[],[], asn1_NOVALUE}}, asn1_NOVALUE}}
emqx-core-cc7b58b74-2 emqx 2024-05-23T02:01:09.279668+00:00 [warning] msg: alarm_is_deactivated, name: <<"emqx_authn_ldap:5">>
```

</details>

**Comment by zmstone** [comment]
Thank you @JJGadgets for reporting it.
We'll fix it in 5.8.0

**Comment by lafirest** [comment]
@JJGadgets @zmstone 
I'm not sure I understood the question clearly, in fact here the result is not expected to be `{error, invalidDNSyntax/timeout}`, anything other than `{error, ladp_closed}` is considered alive.

**Comment by zmstone** [comment]
> @JJGadgets @zmstone I'm not sure I understood the question clearly, in fact here the result is not expected to be `{error, invalidDNSyntax/timeout}`, anything other than `{error, ladp_closed}` is considered alive.

Right. I did not take close enough look. Sorry.
I guess we need more clarification from @JJGadgets

**Comment by JJGadgets** [comment]
@lafirest @zmstone if that's the case, what would you reckon is causing EMQX to treat the glauth server as offline?

That error returned of `insufficientAccessRights` by glauth is not `ldap_closed` either, yet it's not treated as up, which was what prompted me to check the code base where I found the `invalidDNSyntax` stuff.

(Although, I'm not a programmer, so I'm really going off my best guess here)

**Comment by zmstone** [comment]
In the shared logs, there are alarm deactivation warnings following insufficientAccessRights

there isn’t alarm activation log. 
maybe try looking for older logs.

**Comment by zmstone** [comment]
This might fix it: https://github.com/emqx/emqx/pull/13521
