### ISSUE TITLE
MemoryDB certificate verification fails after upgrade to version 5.7.0

### ISSUE THREAD

**Issue by johannesfknx** [emqx/emqx#13146]
### What happened?

After upgrading EMQX from v5.6.1 to v5.7.0, the SSL/TLS handshake between EMQX and MemoryDB fails with 

`reason => {tls_alert,{handshake_failure,"TLS client: In state wait_cert_cr at ssl_handshake.erl:2136 generated CLIENT ALERT: Fatal - Handshake Failure\n {bad_cert,hostname_check_failed}"}},type => ssl_connect}`

### What did you expect to happen?

The version upgrade should not impact the authorization

### Anything else we need to know?

- Connection works after disabling `TLS verify` 
- `/etc/ssl/certs/ca-certificates.crt` seems to be the same in both versions
- SSL config: 
```
  ssl {
    enable = true
    verify = "verify_peer"
    cacertfile = "/etc/ssl/certs/ca-certificates.crt"
  }
```

### EMQX version

<details>

```console
$ ./bin/emqx_ctl broker
sysdescr  : EMQX
version   : 5.7.0
datetime  : 2024-05-28T13:12:04.900514118+00:00
uptime    : 36 minutes, 31 seconds
```

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 12 (bookworm)"
NAME="Debian GNU/Linux"
VERSION_ID="12"
VERSION="12 (bookworm)"
VERSION_CODENAME=bookworm
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
$ uname -a
Linux emqx-0 6.1.87 #1 SMP PREEMPT_DYNAMIC Wed May  8 18:54:00 UTC 2024 x86_64 GNU/Linux
```

</details>

### Log files

<details>

</details>

**Comment by savonarola** [comment]
Hello!
From v5.6.1 to v5.7.0 we didn't change redis-related connection settings. Can we check that v5.6.1 version still connects with the same tls settings? Wasn't the error caused by the very reconnection attempt?

**Comment by johannesfknx** [comment]
@savonarola Thanks for your reply!
We rolled back to v5.6.1 and connection works fine. We also changed the version back and forth with the same settings. Connection only fails with v5.7.0.

**Comment by johannesfknx** [comment]
Looking at the error message, it might be related to this cange: https://github.com/emqx/emqx/pull/12962https://github.com/emqx/emqx/pull/12962

**Comment by id** [comment]
@johannesfknx could you share cert from your MemoryDB instance with us? We'll try to reproduce the issue.

**Comment by savonarola** [comment]
Yes, this is the default change for all clients making checking rules more strict.

```
ssl {
    enable = true
    verify = "verify_peer"
    cacertfile = "/etc/ssl/certs/ca-certificates.crt"
  }
```
Could you provide the full authorization section of the config?

Also, what is 
* the hostname to which EMQX connects
* the host certificate CN's

**Comment by johannesfknx** [comment]
#### emqx.conf

```
node {
  name = "emqx@127.0.0.1" # this is overwritten with an env variable
  cookie = "emqxsecretcookie" # this is overwritten with an env variable
  data_dir = "data"
}
cluster {
  name = emqxcl
  discovery_strategy = manual # this is overwritten with an env variable
}
dashboard {
    listeners.http {
        bind = 18083
    }
}
authentication = [{
  auto_reconnect = true
  backend = "redis"
  cmd = "HMGET api:emqx:v0:mqtt_user:$${username} password salt"
  mechanism = "password_based"
  password_hash_algorithm {
    dk_length = 64
    iterations = 10000
    mac_fun = "sha512"
    name = "pbkdf2"
  }
  pool_size = 8
  redis_type = "cluster"
  servers = "$${var.cluster.config_redis_address}" # this is overwritten with an env variable
  ssl {
    enable = true
    verify = "verify_peer"
    cacertfile = "/etc/ssl/certs/ca-certificates.crt"
  }
}]
authorization {
  cache {
    enable = true
    max_size = 20000
    ttl = 30m
  }
  deny_action = "disconnect"
  no_match = "deny"
  sources = [
    {
      auto_reconnect = true
      cmd = "HGETALL api:emqx:v0:mqtt_acl:$${username}"
      pool_size = 8
      redis_type = "cluster"
      servers = "$${var.cluster.config_redis_address}" # this is overwritten with an env variable
      ssl {
        enable = true
        verify = "verify_peer"
        cacertfile = "/etc/ssl/certs/ca-certificates.crt"
      }
       type = "redis"
    }
  ]
}
telemetry {enable = false}
flapping_detect {
  enable = true

  ## The max disconnect allowed of an MQTT Client in `window_time`
  max_count = 10

  ## The time window for flapping detect
  window_time = 1m

  ## How long the clientid will be banned
  ban_time = 5m
}
# When a client subscribes with a wildcard topic, the server will send all matching retained messages at once, leading to a force shutdown of the connection
# this will trigger a reconnect on the client side and the server will send the retained messages again and again and thus create much load on the broker
# therefore, it is better to disable the force shutdown
force_shutdown {enable = false}

```

with 

```
EMQX_AUTHENTICATION__1__SERVERS : clustercfg.xxx-config-store.szcvcy.memorydb.eu-central-1.amazonaws.com:6379
EMQX_AUTHENTICATION__1__SSL__SERVER_NAME_INDICATION : *.xxx-config-store.szcvcy.memorydb.eu-central-1.amazonaws.com
EMQX_AUTHORIZATION__SOURCES__1__SERVERS : clustercfg.xxx-config-store.szcvcy.memorydb.eu-central-1.amazonaws.com:6379
EMQX_AUTHORIZATION__SOURCES__1__SSL__SERVER_NAME_INDICATION : *.xxx-config-store.szcvcy.memorydb.eu-central-1.amazonaws.com
```

#### Cert: 
```
Server certificate
subject=CN = *.xxx-config-store.szcvcy.memorydb.eu-central-1.amazonaws.com
issuer=C = US, O = Amazon, CN = Amazon RSA 2048 M02
```

Let me know if you need more information.

**Comment by savonarola** [comment]
As far as I understand,  SNI should contain the exact host, not a wildcard to match: not  `*.xxx-config-store.szcvcy.memorydb.eu-central-1.amazonaws.com` but `clustercfg.xxx-config-store.szcvcy.memorydb.eu-central-1.amazonaws.com`

**Comment by zmstone** [comment]
Not the first time to see people end up confusing wildcard certificate with SNI.

Some learning material: https://www.cloudflare.com/learning/ssl/what-is-sni/

To put it simple, SNI is the server's name (indicator) which is sent by the client to the server.
The server takes it to figure out which name the client used to address the server.

Most of the time, SNI is exactly the FQND the client uses to connect the server.
However, technically SNI can be anything, it's just `*` is most likely not going to work because in no way it's a "indicator"
