### ISSUE TITLE
how to configure different ACLs for different listeners

### ISSUE THREAD

**Issue by zhouruiruiruiyan** [emqx/emqx#13159]
### What happened?

I now have 2 listener ports, 8883 and 8884, and I want to configure ACL on port 8883 to intercept the topics of publish action/#, set/#。

To sum up, configure different ACLs for different listeners

### What did you expect to happen?

To sum up, configure different ACLs for different listeners

### EMQX version

<details>

```console
$ ./bin/emqx_ctl broker
# paste output here
```
版本 5.2.1
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here
```

</details>

### Log files

<details>

</details>

**Comment by zhouruiruiruiyan** [comment]
I see that the documentation has the following, but I don't know how to configure it. Document not found  
![image](https://github.com/emqx/emqx/assets/86469122/27f6acfd-cc1c-41d0-ab25-d2874a2943f7)

**Comment by savonarola** [comment]
Hello! Currently, only authentication may be set up per listener. Authorization is common for all the clients.

**Comment by zmstone** [comment]
Hi again @zhouruiruiruiyan 
You might need a bit more hint for the client attribute since what you want is one listener for `action/#` and another for `set/#`
The client attribute extraction is a expression which supports naive condition control flows.
In your case, if you have one listener in the `default` zone, and another listener in `myzone1`, you can write the client attribute exaction expression like this:

`iif(str_eq(zone,'default'),'action','set')`

<img width="871" alt="image" src="https://github.com/emqx/emqx/assets/164324/d19d6bcb-eb0b-466a-b4c9-c0d6273ac79e">

Then you can use `${client_attrs.topic_prefix}` in the ACL rules like the `${topic}` placeholder.

**Comment by zhouruiruiruiyan** [comment]
> Hi again @zhouruiruiruiyan You might need a bit more hint for the client attribute since what you want is one listener for `action/#` and another for `set/#` The client attribute extraction is a expression which supports naive condition control flows. In your case, if you have one listener in the `default` zone, and another listener in `myzone1`, you can write the client attribute exaction expression like this:
> 
> `iif(str_eq(zone,'default'),'action','set')`
> 
> <img alt="image" width="871" src="https://private-user-images.githubusercontent.com/164324/335192843-d19d6bcb-eb0b-466a-b4c9-c0d6273ac79e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcxMjIxMDEsIm5iZiI6MTcxNzEyMTgwMSwicGF0aCI6Ii8xNjQzMjQvMzM1MTkyODQzLWQxOWQ2YmNiLWViMGItNDY2YS1iNGM5LWMwZDYyNzNhYzc5ZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTMxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUzMVQwMjE2NDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05ODhiNTZmNWQ3MWFlN2YxYTZlOWU4OWEwYmQ1ZDRiOGVjYTExNzZjMWU0MjJhZGJiNzA5YzllODdlYmQ3MjUyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.sxPhuKjIS0tICyBAnK6siLNoggjQ8iVFbb5D1JFAVeQ">
> Then you can use `${client_attrs.topic_prefix}` in the ACL rules like this:
> 
> ```
> % acl.conf
> {allow, all, subscribe, "${client_attrs.topic_prefix}/#"}.
> ```


yes,it's help me. but What I want to achieve is to intercept all actions/#和set/# when no zone is set.  
 {deny, all, subscribe, "${client_attrs.topic_prefix}/#"}.

**Comment by zmstone** [comment]
To by default only allow permitted pub/sub actions, you must replace the last line `{allow, all}.` with `{deny, all}.` at the end of acl.conf

**Comment by zhouruiruiruiyan** [comment]
> To by default only allow permitted pub/sub actions, you must replace the last line `{allow, all}.` with `{deny, all}.` at the end of acl.conf

sorry ,i want to say : listeners.ssl want to intercept all actions/#和set/#,but listeners.tcp dont intercept

**Comment by zmstone** [comment]
> i dont kown how to config myzone1
To configure a zone: https://docs.emqx.com/en/enterprise/latest/configuration/configuration.html#zone-override

**Comment by zmstone** [comment]
>  intercept all actions/#和set/# when no zone is set.

There is no way to "intercept" anything at listener level.
The suggested solution is to associate listener (zone) as client's attribute, and then perform ACL checks based on client attributes.

If you set a client attribute as `topic_prefix` based on the listener (zone), below rule will do exactly what you wanted: per-listener ACL.

`{allow, all, subscribe, "${client_attrs.topic_prefix}/#"}.`

**Comment by zhouruiruiruiyan** [comment]
thanks,i have finished it.
I implemented a topic that port 8883 does not allow the publication of action/#和set/#。The rest of the ports are unlimited。
### emqx.conf add:
```
zones.devicezone.mqtt.max_packet_size=10485760 
mqtt {
 client_attrs_init = [ 
         { expression = "iif(str_eq(zone,'devicezone'),'action','none')" set_as_attr = action}, 
         { expression = "iif(str_eq(zone,'devicezone'),'set','none')" set_as_attr = set} ]
 }

listeners.ssl.default{ 
zone = devicezone
}
```

## acl add
`{deny, all, publish, ["${client_attrs.action}/#","${client_attrs.set}/#"]}.`

**Comment by zmstone** [comment]
An update.
Starting from 5.8.5,  you can use clinet_attrs in as the `who()` match condition in `acl.conf`.

below is the extended spec:
```
%% -type who() :: all |
%%                ipaddr() | ipaddrs() | username() | clientid() | client_attr() |
%%                {'and', [ipaddr() | ipaddrs() | username() | clientid() | client_attr()]} |
%%                {'or',  [ipaddr() | ipaddrs() | username() | clientid() | client_attr()]}.
```

Example:

  For example, the following rule allows clients with a `"type"` attribute set to `"internal"` to publish or subscribe to all topics: 

  `{allow, {client_attr, "type", "internal"}, all, ["#"]}.` 

  And the rule below denies clients with a `"type"` attribute prefixed with `"external-"` from publishi any messages:

  `{deny, {client_attr, "type", {re, "external-.*"}}, publish, ["#"]}.`
