### ISSUE TITLE
How to automatically create a configuration file after the container starts

### ISSUE THREAD

**Issue by Sangyang-qu8uu** [emqx/emqx#13158]
#### Environment

- OS: 
[root@h04 data]#  cat /etc/os-release
NAME="Kylin Linux Advanced Server"
VERSION="V10 (Sword)"
ID="kylin"
VERSION_ID="V10"
PRETTY_NAME="Kylin Linux Advanced Server V10 (Sword)"
ANSI_COLOR="0;31"
- EMQX version
emqx/emqx:5.5.1

#### Description
I use docker-compose to create containers. How to create configuration files automatically?
for example

services:
    emqx:
        container_name: ${CONTAINER_NAME}
        image: emqx/emqx:5.5.1
        deploy:
            resources:
                limits:
                    cpus: ${CPUS}
                    memory: ${MEMORY_LIMIT}
        ports:
            - ${HOST_IP}:${PORT_HTTP}:18083
            - ${HOST_IP}:${EMQX_PORT_1883}:1883
            - ${HOST_IP}:${EMQX_PORT_8083}:8083
            - ${HOST_IP}:${EMQX_PORT_8084}:8084
            - ${HOST_IP}:${EMQX_PORT_8883}:8883
        restart: always
        user: "0"
        volumes:
            - ./data:/opt/emqx/data
            - ./log:/opt/emqx/log
version: "3"

**Comment by Sangyang-qu8uu** [comment]
![image](https://github.com/emqx/emqx/assets/53424623/1c3e5dd4-3f6b-4093-b175-056f98e89aba)
like this

**Comment by id** [comment]
Not sure I understand the problem. What would you like to achieve?

**Comment by Sangyang-qu8uu** [comment]
Thank you. I solved this problem by studying.
