### ISSUE TITLE
[Website] Emqx.io Does Not Allow to Download The Open Source Version Anymore

### ISSUE THREAD

**Issue by TxMat** [emqx/emqx#13178]
### What happened?

https://www.emqx.io/downloads now redirects to https://www.emqx.com/en/try with no option to select the Open Source  version

![image](https://github.com/emqx/emqx/assets/46858765/6efc1adf-a799-4ac6-aeab-6e3d1bcdc552)

### What did you expect to happen?

Have an option to select open source when visiting https://www.emqx.com/en/try just like before the update

### How can we reproduce it (as minimally and precisely as possible)?

- go to https://www.emqx.io/downloads
- try to download the open source version

### Anything else we need to know?

This also means there is now no easy way to find the docker repo of Emqx nor a friendly installation section by os

**Comment by SergeTupchiy** [comment]
Hi,
EMQX Open Source is available for download: go to 'Self-managed' tab, then click 'Download' in front of 'EMQX Open Source' option:
![download-emqx-os](https://github.com/emqx/emqx/assets/25793403/61ea4107-ccce-47ae-88bc-8441d9356e26)

**Comment by TxMat** [comment]
My mistake. Thanks !
