### ISSUE TITLE
The Client ID prefix in the MQTT bridge does not take effect

### ISSUE THREAD

**Issue by tigercl** [emqx/emqx#13185]
### What happened?

Even if I set a prefix, the resulting Client ID is a completely random string.

<img width="1320" alt="image" src="https://github.com/emqx/emqx/assets/15085956/d90f30dd-ab3d-4d4e-bced-2c86f069f4b0">
<img width="1704" alt="image" src="https://github.com/emqx/emqx/assets/15085956/ef0af33a-2ff0-41a4-9a02-2513faddba3c">

### What did you expect to happen?

When I set a prefix for Client ID, like `myclient_`, I should get Client IDs like `myclient_edf10a`, `myclient_0902fb`.

The prefix of the Client ID is meaningful. For example, some IoT Hubs only authenticate the Client ID, so I need to register these Client IDs in advance or let the IoT Hub recognize the prefix of the Client ID.

### EMQX version

EMQX 5.7.0

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here
```

</details>

### Log files

<details>

</details>

**Comment by zhongwencool** [comment]
Related: https://askemq.com/t/topic/8281
https://emqx.atlassian.net/browse/EMQX-12264

This issue does indeed exist. We have set the total length of the clientid not to exceed **23 characters**.
To avoid this issue, you can set the prefix to be smaller.
After internal discussions, it was decided to add this limit to  the documentation.

https://github.com/emqx/emqx/blob/master/apps/emqx_bridge_mqtt/src/emqx_bridge_mqtt_connector.erl#L479-L480

**Comment by zmstone** [comment]
after seeing https://github.com/emqx/emqx/issues/13214, we decided to fix it a more flexible way.
see PR #13216 for more details.
