### ISSUE TITLE
Usage of 'mqtt.pubsub.pool_size' parameter

### ISSUE THREAD

**Issue by hbahn** [emqx/emqx#1318]
#### Environment

- OS: CentOS 7.x
- Erlang/OTP: R20/9.0
- EMQ: 2.3

#### Description

Could Someone explain what 'mqtt.pubsub.pool_size' parameters mean in emq.conf files?
We designed a broker cluster with high-load sub/unsub applications.

if we increase the number from 8 to 16 or higher, can we expect performance improvement?
What is the recommendation? our virtual machine 8 cores and 16 G RAM each.

**Comment by turtleDeng** [comment]
@hbahn The mqtt.pubsub.pool_size parameter is invalid and has been deleted.
