### ISSUE TITLE
emq_web_hook plugin, slowing down broker pathetically.

### ISSUE THREAD

**Issue by xerosanyam** [emqx/emqx#1321]
#### Environment

- OS: Ubuntu 16.04
- Erlang/OTP: 
- EMQ: 2.3

#### Description

I switched on emq_web_hook plugin and began to notice a significant drop in connection speed and speed of delivering messages.

On a side note, what is a better way to get all those values web_hook publishes.

**Comment by Gilbert-Wong** [comment]
It is normal because each message published by broker would trigger emqx to sent a http request.
