### ISSUE TITLE
Broker not public message to the Client while sub topic with qos 0

### ISSUE THREAD

**Issue by LiushengWang** [emqx/emqx#1322]
#### Environment

- OS: Ubuntu 14.2
- Erlang/OTP: 
- EMQ:   2.1.0
--

#### Description
I use mqtt 2.1.0 as broker, and a RTU as Mqtt client sub a topic with qos 0. As normal, this client can receive the message while the other client pub message to the same topic. some time , the RTU client can not receive the message but other clients can receive. 
 1、use  Wireshark to get the network data,the broker not pub to this client;
 2、from dashboard，the client sub the topic with qos 0;
 3、other clients can receive the message from the same topic with qos 0 at the same time; 
 4、this client can pub message;
 5、This problem doesn't happen very often, and the two day test （test more than 50 times）happens 4 times

**Comment by LiushengWang** [comment]
I found a scene where this problem occurred，this client is in the clients list，but can not find the session in the Sessions list.

**Comment by HJianBo** [comment]
@LiushengWang Would you please provide more informations? What caused the session to disappear?? It would help a lot.

For example: **Reappear Step**, **Connect Args** etc.

Thanks!

**Comment by LiushengWang** [comment]
@HJianBo Thanks for your responses,  

There is no accurate reconstruction procedure，I use the follow steps to connect mqtt broker:

the connect args is following: 
#Client connect:
   10 2e 00 04 4d 51 54 54
   04 c2 00 3c 00 0f 38 36
   31 38 35 33 30 33 31 34
   37 35 36 31 39 00 09 74
   61 6e 67 67 75 6f 6a 69
   00 06 74 74 67 67 6a 6a
and recevice  connack:
   20 02 00 00

#Client subscribe:
   82 23 00 00 00 1e 43 6c
   69 65 6e 74 2f 43 6f 6d
   6d 61 6e 64 2f 38 36 31
   38 35 33 30 33 31 34 37
   35 36 31 39 00
and recevice  suback:
   90 03 00 00 00

Thanks!
