### ISSUE TITLE
Feature Request: Add exact_match Parameter to JWT ACL

### ISSUE THREAD

**Issue by mofelee** [emqx/emqx#13247]
### What would you like to be added or enhanced?

We propose adding a new `exact_match` parameter to the [`acl`](https://docs.emqx.com/en/emqx/latest/access-control/authn/jwt.html#access-control-list-optional)  field in JWT. When users employ wildcard matching and `exact_match=true`, only precise topic subscriptions that meet the criteria should be allowed, while wildcard subscriptions should be denied.

Given the `acl`:

```json
{
  "topic": "c/+/public_key",
  "action": "subscribe",
  "permission": "allow",
  "exact_match": true
}
```
When a user subscribes to `c/37be7dc7-b564-4c32-8347-5c2fc1a25e00/public_key`, the subscription should be allowed.

However, if the user attempts to subscribe to `c/+/public_key`, the subscription should be denied.

### Why is this needed?

Enhanced security by restricting subscriptions to exact topics.
Greater control over topic access, preventing unintended access through wildcards.

### Request
Please consider adding the `exact_match` parameter to the JWT acl field to support this functionality.

**Comment by mofelee** [comment]
@qzhuyan 

In our scenario, all users persist their `public_key` to `c/{my_uuid}/public_key.` This `public_key` is intended for communication with other parties, so it is not possible to know in advance who the ACL should permit. Additionally, attempting to guess or collide UUIDs is not a simple task.

If subscribing to `c/+/public_key` is allowed, it could lead to a situation where every time a user sends their `public_key` to the MQTT broker for persistence, someone could receive a notification. A malicious user could monitor how many users are online and discover their UUIDs. Moreover, when a user subscribes to c/+/public_key, they would receive all persisted public keys in the system.

**Comment by mofelee** [comment]
Implementing this feature seems straightforward. When checking the ACL, if `exact_match=true`, simply verify that the subscribed topic does not contain `#` or `+` symbols.

**Comment by zmstone** [comment]
1. You can technically issue one a different JWT for each client. i.e. bake the uuid into JWT, instead of sharing one token for many clients.

2. As William pointed out above, you can use placeholders in "topic" like this:
```
{
  "topic": "c/${username}/public_key",
  "action": "subscribe",
  "permission": "allow"
}
```

**Comment by mofelee** [comment]
> 1. You can technically issue one a different JWT for each client. i.e. bake the uuid into JWT, instead of sharing one token for many clients.
> 2. As William pointed out above, you can use placeholders in "topic" like this:
> 
> ```
> {
>   "topic": "c/${username}/public_key",
>   "action": "subscribe",
>   "permission": "allow"
> }
> ```


If I have 100 users who need to get their keys, should I include 100 ACL rules in the JWT token, or one rule with exact_match=true ?


Or, is there a way to prevent others from using wildcard matches in the ACL, but allow specific feature matches? Additionally, this topic does not conform to the single responsibility principle. One topic field contains both topic filtering and topic subscription responsibilities. I believe that filtering allowed topics and subscription rules should not be handled by the same topic field.

**Comment by mofelee** [comment]
The term exact_match is somewhat abstract. Alternatively, is it possible to provide a way to filter subscribable topics using regular expressions? This would make the ACL more powerful.

**Comment by zmstone** [comment]
One JWT includes only the ACL rules which are applies to this single client which is using the token. But not for other clients.

**Comment by mofelee** [comment]
> One JWT includes only the ACL rules which are applies to this single client which is using the token. But not for other clients.

I think you might not fully understand the scenario I'm describing. Let me organize my content. I'm not a native English speaker, so there might be some issues with my description. Please bear with me.

**Comment by zmstone** [comment]
I don't know why you are so obsessed with the `exact_match` idea.
It is not needed in JWT because one token is for one client.

If you want a in-general rule to allow subscribing to `a/#` exactly, but not `a/1` or `a/2`, there is `eq` syntax in ACL rules.
use `"topic": "eq c/+/public_key",` to allow subscribing exactly to `c/+/public_key`.

here is an example with `eq`: https://gist.github.com/zmstone/464a72e382c83eb369c6765b034c08ad

**Comment by mofelee** [comment]
@zmstone 

Yes, this is the feature I need. Is this feature already implemented in JWT? I couldn't find it in the documentation.

**Comment by zmstone** [comment]
Yes, I'll add it to the doc later.
But I don't think that's the feature you needed.

> If I have 100 users who need to get their keys, should I include 100 ACL rules in the JWT token, or one rule with exact_match=true ?

This question shows that you don't really fully understand what ACL in JWT means.

**Comment by mofelee** [comment]
https://docs.emqx.com/en/emqx/latest/access-control/authz/authz.html

I found where this feature is located. Thank you very, very much for your patient answers. EMQX is a fantastic project!

**Comment by zmstone** [comment]
## I'd like to revisit what you wrote in the original post:

> When a user subscribes to c/37be7dc7-b564-4c32-8347-5c2fc1a25e00/public_key, the subscription should be allowed.
> However, if the user attempts to subscribe to c/+/public_key, the subscription should be denied.

If the "user" is the client itself, the above is where you want to get, below rules should work (the second rule is not necessary, but just added to be more explict)
```
[{
  "topic": "c/${username}/public_key",
  "action": "subscribe",
  "permission": "allow"
},
{
  "topic": "#",
  "action": "subscribe",
  "permission": "deny"
}]
```
`${username}` can also be`${clientid}`, or `${client_attrs.uuid}` if you can extract the uuid from some factor of the client like certificate etc.

## Now fast-forwarding to the above post

> allowing subscription to others' public keys.

This would require others to subscribe `c/+/public_key`.
But then you also said something contradicting: 

> If we allow subscribing to c/+/public_key, all user UUIDs will be leaked directly at the MQTT layer.

**Comment by mofelee** [comment]
@zmstone 

Sorry, I know you want to help me solve the problem, but I tried it yesterday, "eq" didn't solve my problem.

**Comment by zmstone** [comment]
换中文吧

**Comment by zmstone** [comment]
related discussion https://github.com/emqx/emqx/issues/13265
