### ISSUE TITLE
api/v5/prometheus/stats not have erlang_vm_* 指标没了吗？

### ISSUE THREAD

**Issue by zhengbucuo** [emqx/emqx#13287]
### What happened?

抓取不到erlang_vm_process_count 指标
![image](https://github.com/emqx/emqx/assets/31462232/162f644a-bb3d-4301-9430-049b8c5666f0)

### What did you expect to happen?

希望可以抓取到erlang_vm_process_count

### EMQX version

5.7

### OS version

ubuntu 22.04

**Comment by keynslug** [comment]
Hi @zhengbucuo, thanks for reporting. I don't think it's a bug though, it's sort of expected that not every single VM metric is exported. Not hard to add, but could you please share what's your use case for that?

**Comment by zhengbucuo** [comment]
我找到了问题所在需要开启才能采集
```yaml
prometheus {  
 collectors {
    mnesia = disabled
    vm_dist = enabled
    vm_memory = enabled
    vm_msacc = enabled
    vm_statistics = enabled
    vm_system_info = enabled
  }
}
```
