### ISSUE TITLE
延迟subscribe可能导致消息消费不到

### ISSUE THREAD

**Issue by LvChenhui** [emqx/emqx#13289]
Hi all 
我们使用消息重传有一些疑惑

使用的是java版本的client，mqtt v3.1.1。

当我们的客户端（这个客户端不是首次连接）初始化connect后，延迟30s再suscribe一个topic，会收不到消息，控台上看到卡在飞行窗口中，并且队列里是有积压数据的。

我们注意到客户端刚connect后会直接把消息推送过来，但是此时我们的listener还没有subscribe，所以这部分消息时丢弃的。我们不确定这部分消息是不是触发mqtt的重传机制？

_Originally posted by @LvChenhui in https://github.com/emqx/emqx/issues/13285#issuecomment-2175433364_

**Comment by zmstone** [comment]
你好。
如果从 EMQX 的控制台上看到消息已经发送到飞行窗口了。那么应该需要调查客户端为什么没有收到消息或者更大的可能是已经收到了但是没有处理。

如果客户端连上了还没订阅就收到消息，那么可能是 clean-start=false。
这种情况客户端是不需要重新订阅的，因为订阅都存在会话状态中了。

**Comment by LvChenhui** [comment]
> 你好。 如果从 EMQX 的控制台上看到消息已经发送到飞行窗口了。那么应该需要调查客户端为什么没有收到消息或者更大的可能是已经收到了但是没有处理。
> 
> 如果客户端连上了还没订阅就收到消息，那么可能是 clean-start=false。 这种情况客户端是不需要重新订阅的，因为订阅都存在会话状态中了。

感谢您的恢复。
是的，我们设置的clean-start=false，会保持会话。所以会造成"客户端连上了还没订阅就收到消息"，但是此时我们的listener还没有注册上来。
代码逻辑如下，client在连接的时候，延迟注册listener
```
public static void main(String[] args) throws Exception {
    MqttSubscribe subscribe = new MqttSubscribe();
    subscribe.connect("emqx_test_subscribe_10");

    new Thread(() -> {
        try {
           //延迟 20s
            Thread.sleep(10 * 1000);
            // 订阅
            MqttSubscription mqttSubscription = new MqttSubscription("testtopic10/10/#", 1);
            System.out.println(simpleDateFormat.format(System.currentTimeMillis()) + "subscribe");
            subscribe.client.subscribe(new MqttSubscription[]{mqttSubscription}, new IMqttMessageListener[]{new DefaultIMqttMessageListener()});
        } catch (Throwable throwable) {
            throwable.printStackTrace();
        }
    }).start();
}

void connect(String clientId) throws Exception {
    MemoryPersistence persistence = new MemoryPersistence();

    String broker = "xxxxx";
    client = new MqttClient(broker, clientId, persistence);
    // MQTT 连接选项
    MqttConnectionOptions connOpts = new MqttConnectionOptions();
    connOpts.setUserName("test");
    connOpts.setPassword("test".getBytes());
    // 保留会话
    connOpts.setCleanStart(false);
    connOpts.setSessionExpiryInterval(7200L);
    //自动重连
    connOpts.setAutomaticReconnect(true);

    // 建立连接
    System.out.println("Connecting to broker: " + broker);
    client.connect(connOpts);
}

**Comment by LvChenhui** [comment]
所以在飞窗里的消息还会重发吗

**Comment by zmstone** [comment]
> 但是此时我们的listener还没有注册上来

我不太理解什么是你们 listener。
- 如果客户端首次连接然后订阅， 那么这是一个 “新建一个订阅” 的请求
- 如果客户端重练，老的session还在EMQX里，那么连上之后就会立刻收到离线期间累积的消息。然后 20s 之后发送的那个订阅请求相当于是“修改原来的订阅的意思“。

**Comment by zmstone** [comment]
> 所以在飞窗里的消息还会重发吗

当前版本 EMQX，飞行窗口中的消息会重发，但是只有在客户端在线的情况下。
飞行窗口中重发消息的行为是违反协议的，在 5.8 中会修复：https://github.com/emqx/emqx/pull/13080
