### ISSUE TITLE
消息重传机制只会在重连的时候触发么

### ISSUE THREAD

**Issue by fhyw** [emqx/emqx#13285]
### What happened?

according to de doc : https://docs.oasis-open.org/mqtt/mqtt/v5.0/os/mqtt-v5.0-os.html#_Toc3901237
【
When a Client reconnects with Clean Start set to 0 and a session is present, both the Client and Server MUST resend any unacknowledged PUBLISH packets (where QoS > 0) and PUBREL packets using their original Packet Identifiers. This is the only circumstance where a Client or Server is REQUIRED to resend messages. Clients and Servers MUST NOT resend messages at any other time [MQTT-4.4.0-1].
】

消息重传机制是不是只会在重连的场景下触发？

### What did you expect to happen?

咨询上面这个问题

### EMQX version

5.7.0

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here
```

</details>

### Log files

<details>

</details>

**Comment by qzhuyan** [comment]
Yes.

**Comment by LvChenhui** [comment]
Hi 
我们使用消息重传有一些疑惑，麻烦帮忙一起看下

使用的是java版本的client，mqtt v1.3.3。

当我们的客户端（这个客户端不是首次连接）初始化connect后，延迟30s再suscribe一个topic，会收不到消息，控台上看到卡在飞行窗口中，并且队列里是有积压数据的。

我们注意到客户端刚connect后会直接把消息推送过来，但是此时我们的listener还没有subscribe，所以这部分消息时丢弃的。我们不确定这部分消息是不是触发mqtt的重传机制？

**Comment by fhyw** [comment]
代码逻辑如下，client在连接的时候，延迟注册listener 

public static void main(String[] args) throws Exception {
        MqttSubscribe subscribe = new MqttSubscribe();

        subscribe.connect("emqx_test_subscribe_10");

        new Thread(() -> {
            try {
               //延迟 20s
                Thread.sleep(10 * 1000);
                // 订阅
                MqttSubscription mqttSubscription = new MqttSubscription("testtopic10/10/#", 1);
                System.out.println(simpleDateFormat.format(System.currentTimeMillis()) + "subscribe");
                subscribe.client.subscribe(new MqttSubscription[]{mqttSubscription}, new IMqttMessageListener[]{new DefaultIMqttMessageListener()});
            } catch (Throwable throwable) {
                throwable.printStackTrace();
            }
        }).start();
    }

    void connect(String clientId) throws Exception {
        MemoryPersistence persistence = new MemoryPersistence();

        String broker = "xxxxx";
        client = new MqttClient(broker, clientId, persistence);
        // MQTT 连接选项
        MqttConnectionOptions connOpts = new MqttConnectionOptions();
        connOpts.setUserName("test");
        connOpts.setPassword("test".getBytes());
        // 保留会话
        connOpts.setCleanStart(false);
        connOpts.setSessionExpiryInterval(7200L);
        //自动重连
        connOpts.setAutomaticReconnect(true);

        // 建立连接
        System.out.println("Connecting to broker: " + broker);
        client.connect(connOpts);
    }
