### ISSUE TITLE
Broker will not publish disconnected $SYS message

### ISSUE THREAD

**Issue by wdhxwz** [emqx/emqx#1330]
#### Environment

- OS: 
- Erlang/OTP: 
- EMQ: 

#### Description
1.Client connect to mqtt server
2. then close the network of client,client will reconnect to mqtt server
3. After a few seconds，connecte to the network
4. broker will not publish disconnected $SYS message

In this process, the client id has not changed，on dashboard，i notice that the ip of client has not changed but the port has changed  

May I ask what is the cause of broker not publish disconnected $SYS message

**Comment by terry-xiaoyu** [comment]
@turtleDeng  Hi turtle, I noticed that this might be the same issue I submitted at 
 https://github.com/emqtt/emqttd/issues/1055
 The EMQ won't callback 'disconnected' plugins on 'kick' event.
 Could you have a check?

**Comment by emqplus** [comment]
@terry-xiaoyu Yes. The broker will not publish a `disconnected` $SYS message when a client is kicked out.
