### ISSUE TITLE
docker can't pull emqx:5.7.0 

### ISSUE THREAD

**Issue by happiren** [emqx/emqx#13311]
### What happened?

sudo docker pull emqx/emqx:5.7.0
can't pull emqx image
tip:  error pulling image configuration: download failed after attempts=6: dial tcp 162.125.8.1:443: i/o timeout

### What did you expect to happen?

pull emqx/emqx:5.7.0 

### EMQX version

<details>
emqx:5.7.0 

```console
$ ./bin/emqx_ctl broker
# paste output here
```

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here
```

</details>

### Log files

<details>

</details>

**Comment by weifengzyl** [comment]
What happened? We didn't have this problem two weeks ago, and now we can't pull the 5.7.0 image

**Comment by Altair-Bueno** [comment]
Seems more of a Docker Hub issue. I can definitely pull this image in EU-West:

![docker pull](https://github.com/emqx/emqx/assets/67512202/e0860c71-fdac-4907-886f-1e5494a05758)

The tag is available there: https://hub.docker.com/layers/emqx/emqx/5.7.0/images/sha256-e9898f04319fbf13766d2f47d0d7a10c0c7f0452bfb2842162cd5373edf05442?context=explore

**Comment by keynslug** [comment]
Hi @happiren,

> `dial tcp 162.125.8.1:443: i/o timeout`

Looks like some connectivity problems on your side, I'd start with checking your network configuration.
