### ISSUE TITLE
Managing the broker, how to delete subscriptions ?

### ISSUE THREAD

**Issue by syberkitten** [emqx/emqx#1337]
This is not a bug but a query...

1. how can all clients be purged from a running broker with their subscriptions?
2 how can all subscriptions be remove for a client?
3. or how can all subscriptions be removed?

The problem is mainly having old retained messages
that need to be purged.

should I try access the amnesia directly?

**Comment by turtleDeng** [comment]
@syberkitten 
emqttd_ctl command line could be used to query and administrate the EMQ broker.
```
subscriptions list                              # List all subscriptions
subscriptions show <ClientId>                   # Show subscriptions of a client
subscriptions add <ClientId> <Topic> <QoS>      # Add a static subscription manually
subscriptions del <ClientId>                    # Delete static subscriptions manually
subscriptions del <ClientId> <Topic>            # Delete a static subscription manually
```

**Comment by syberkitten** [comment]
@turtleDeng 
Yes I know this :)  

will have to write a script that queries topics
using 'subscriptions list' | and publishes retained 0 to each one
to reset the topics.

**Comment by rgaufman** [comment]
Is there any way to enable this functionality in the web interface? - I can see all the subscriptions but then I need to use the command line to delete one, would be convenient if it was possible to do right in the web interface :)

**Comment by HJianBo** [comment]
Maybe you can call the ['unsubscribe' REST API](https://developer.emqx.io/docs/broker/v3/en/rest.html#publish-subscribe):

```
POST api/v3/mqtt/unsubscribe

# Request
{
  "topic": "test_topic",
  "client_id": "mqttjs_ab9069449e"
}
```

**Comment by rgaufman** [comment]
I guess this is more of a feature request than a bug, would be nice to have this in the web interface :)
