### ISSUE TITLE
Plugin hook points not called when auto-booting plugin in a cluster

### ISSUE THREAD

**Issue by thomas-unger-zereos** [emqx/emqx#13378]
### What happened?

I created a custom plugin with one hook (client.authenticate). When the plugin is configured as auto-boot, the hook point is not called. The UI shows the plugin as active. When I stop and start the plugin, the hook point is called.

I made a custom docker image based on the official one, added the plugin files inside the plugin_dir and added the plugin vsn inside the emqx.conf so that it auto-loads.

When using a single-node cluster locally, the hook point works with auto-boot. When using a two-node cluster in kubernetes, the hook point doesn't work. Maybe it is because the node restarts for joining the cluster?

### What did you expect to happen?

The plugin's hook points should be always called when the plugin is reported as active and no error is logged.

I have found no other way of automatically enabling a plugin after startup.

### How can we reproduce it (as minimally and precisely as possible)?

I put the .tar.gz file as well as the extracted plugin files inside /opt/emqx/plugins for my docker image.

emqx.conf section
```    
    plugins {
      install_dir = plugins
      states = [
        {
          enable = true
          name_vsn = "emqx_my_plugin-1.0.0"
        }
      ]
    }
```

Plugin relevant code

```
-module(emqx_my_plugin).

-include_lib("emqx/include/emqx.hrl").
-include_lib("emqx/include/emqx_hooks.hrl").

%% for logging
-include_lib("emqx/include/logger.hrl").

-export([ load/1
        , unload/0
        ]).

%% Client Lifecycle Hooks
-export([ 
        on_client_authenticate/2
        ]).

%% Called when the plugin application start
load(Env) ->
    emqx_hooks:add('client.authenticate', {?MODULE, on_client_authenticate, []}, 965).

on_client_authenticate(ClientInfo = #{clientid := ClientId}, Result) ->
    case Result of
        {error, not_authorized} ->
            io:format("Client(~s) authentication failed, rewriting to bad username or password~n", [ClientId]),
            {stop, {error, bad_username_or_password}};
        _ ->
            {ok, Result}
    end.

unload() ->
    emqx_hooks:del('client.authenticate', {?MODULE, on_client_authenticate}).

```

### Anything else we need to know?

I also tried other hook points (client.connect, client.connack) with HP_HIGHEST, they don't work as well.

The logs show the plugin as started

```
2024-07-01T13:20:49.110591+00:00 [debug] msg: started_apps, apps: [emqx]
2024-07-01T13:20:49.110680+00:00 [debug] msg: starting_app, app: emqx_plugins
2024-07-01T13:20:49.114239+00:00 [debug] msg: started_plugin_app, app: emqx_my_plugin
2024-07-01T13:20:49.114704+00:00 [debug] msg: started_apps, apps: [emqx_plugins]
2024-07-01T13:20:49.114784+00:00 [debug] msg: starting_app, app: emqx_retainer
```

### EMQX version

Docker image emqx/emqx:5.7.1

### OS version

Docker / Kubernetes

**Comment by zmstone** [comment]
thank you you for reporting it @thomas-unger-zereos

**Comment by thalesmg** [comment]
Hi @thomas-unger-zereos .

Could you please share the code for your module implementing the `application` behavior?  That's the one that `emqx_my_plugin.app.src` points to under the `mod` key.

**Comment by thomas-unger-zereos** [comment]
Hi @thalesmg , and thank you for helping!

It is based on the emqx-plugin-template.

<details>
	<summary>emqx_my_plugin.app.src</summary>

	{application, emqx_my_plugin,
	 [{description, "***"},
	  {vsn, "1.0.0"},
	  {modules, []},
	  {registered, [emqx_my_plugin_sup]},
	  {applications, [kernel, stdlib]},
	  {mod, {emqx_my_plugin_app, []}},
	  {env, []},
	  {licenses, ["Apache-2.0"]},
	  {maintainers, ["***"]}
	 ]}.

</details>

<details>
	<summary>emqx_my_plugin_app.erl</summary>

	-module(emqx_my_plugin_app).

	-behaviour(application).

	-emqx_plugin(?MODULE).

	-export([ start/2
			, stop/1
			]).

	start(_StartType, _StartArgs) ->
		{ok, Sup} = emqx_my_plugin_sup:start_link(),
		emqx_my_plugin:load(application:get_all_env()),

		{ok, Sup}.

	stop(_State) ->
		emqx_my_plugin:unload().


</details>

<details>
	<summary>emqx_my_plugin_sup.erl</summary>

	-module(emqx_my_plugin_sup).

	-behaviour(supervisor).

	-export([start_link/0]).

	-export([init/1]).

	start_link() ->
		supervisor:start_link({local, ?MODULE}, ?MODULE, []).

	init([]) ->
		SupFlags = #{strategy => one_for_all, intensity => 3, period => 5},
		ChildSpecs = [],
		{ok, {SupFlags, ChildSpecs}}.


</details>

**Comment by thomas-unger-zereos** [comment]
Thanks a lot for the quick fix!
