### ISSUE TITLE
Is there a way to override client keepalive ?

### ISSUE THREAD

**Issue by xerosanyam** [emqx/emqx#1339]
#### Environment

- OS: All
- Erlang/OTP: All
- EMQ: 2.3

#### Description

The hardware team has hardcoded the value of keepalive to be 10000 :sob:
Is there a way to override this behavior from server side ?

**Comment by HJianBo** [comment]
Could not override the value of keepalive by configuration files, now.

Sorry about that.

**Comment by terry-xiaoyu** [comment]
@xerosanyam The server side keep-alive negotiation has been implemented in MQTT 5.0.
But I don't have any idea for solving your problem as you are using mqtt 3.1.1.
