### ISSUE TITLE
emqx_authn_pgsql resource down: unknown reason

### ISSUE THREAD

**Issue by JConoditbiot** [emqx/emqx#13396]
### What happened?

I use a EMQX broker with authentication enabled via PostgreSQL (password based). The authentication works _most_ of the time but occasionally it will fail and recover on its own. When it happens, it looks like the authentication mechanism get "stuck" in connecting status and the broker cannot talk to the database. The downtime is consistently 16 minutes and 36 seconds (+/- 2 seconds), so to me it seems like the connection is reset and it succeeds. If I catch the issue I can manually reset it and it works immediately. I am also able to log into the database using the broker credential while the authentication mechanism is down: I know the database is available during this time.

The error triggers an alarm: `emqx_authn_pgsql:1 resource down: unknow reason`. Looking around it looked similar to issue [#10925](https://github.com/emqx/emqx/issues/10925). The solution suggested is using version 5.0.26 which is the version I currently am on.

I have tried to modify the connection pool size thinking that I could be running into the maximum number but it has not helped

### What did you expect to happen?

The authentication plugin to remain stable over time

### How can we reproduce it (as minimally and precisely as possible)?

I attached the relevant section of the emqx.conf file which handles the authentication with username/password redacted.
[authentication_emqx_broker.txt](https://github.com/user-attachments/files/16073127/authentication_emqx_broker.txt)

### EMQX version

<details>
sysdescr : EMQX 

version : 5.0.26
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here
```

</details>

### Log files

<details>

</details>

**Comment by zmstone** [comment]
Hi @JConoditbiot 

Do you have logs from EMQX?

EMQX is now at 5.7, there had been a lot of fixes since 5.0, I would recommend upgrading to 5.7.

**Comment by JConoditbiot** [comment]
Hi,

I attached the logs just before the alarm is activated. 

I have tried multiple version including the latest at the time of testing (5.6.x if I recall correctly) and the issue still occurred so I went back to the version I was most familiar with. I can try 5.7 and see what happens but I am not sure this will fix the issue.

[emqx_logs.txt](https://github.com/user-attachments/files/16074090/emqx_logs.txt)

**Comment by zmstone** [comment]
Thank you for sharing the logs.
The log shows `econnrefused` reason, which is quite common.
I tried to reproduce it in 5.7.1, it seems the connectivity recovered not long after postgres server is brought back.
In my test, I stopped postgres docker container for a short while (less than 60s).

```
2024-07-02T23:34:26.029690+02:00 [warning] msg: alarm_is_activated, message: <<"resource down: Unknown reason">>, name: <<"emqx_authn_postgresql:21">>
2024-07-02T23:34:26.030237+02:00 [warning] msg: health_check_failed, id: <<"emqx_authn_postgresql:21">>, status: connecting
2024-07-02T23:35:26.037441+02:00 [warning] msg: alarm_is_deactivated, name: <<"emqx_authn_postgresql:21">>
```

**Comment by JConoditbiot** [comment]
Thank you for looking into the issue. I don't think the issue is the exact same as what you are simulating. If the database goes down the connection resumes as soon as it is back up. The issue I mentioned above happens without any sign of the server going down.

**Comment by JConoditbiot** [comment]
The issue still occurs when running v5.7.1 with the same logs. The recovery time is similar at around 15min and 50s.

What I believe is happening is one of the query fails or times out and the server thinks the database is down. When I look at the options here for postgresql https://docs.emqx.com/en/emqx/v5.7.1/hocon/#T-authentication-S-postgresql, I cannot find any options for query timeouts and/or retries. Other databases have options for this. Am I missing something and I can configure the timeout/retires?

**Comment by yanzhiemq** [comment]
@JConoditbiot Could you please provide more information about your PostgreSQL instance? This will help me reproduce the issue accurately. Thank you!
1. Is it a self-hosted instance or a SAAS instance?
2. What is the version of your PostgreSQL instance?
3. Could you provide details about the network latency between your EMQX instance and the PostgreSQL instance?

**Comment by zmstone** [comment]
A post close recap: there is only `econnrefused` posix error in the shared logs. This error code means the server (or maybe a proxy) refused EMQX to connect.
Usually happens when the server or proxy restarts.
Another reason could be the server (or proxy) has connection limit reached, or some other quota limit reached and decided to block the clients in EMQX for a while.
