### ISSUE TITLE
Subscriber question

### ISSUE THREAD

**Issue by rainmanwy** [emqx/emqx#1341]
#### Environment

- OS: CentOS 7
- Erlang/OTP: 
- EMQ: 2.3rc

#### Description

I am trying to do performance testing. And i use emqtt-jmeter to simulate PUB/SUB.
Here is my scenario:
1. 6000 VU as PUB, with rate 10 messages/sec, total messages are 6000000(qos0)
2. 1 VU as SUB

and I found PUB looks ok, with rate 56000 messages/sec
But SUB is not stable, the rate will decrease to 200 messages/sec

below is log of jmeter:

1510900507304,0,MQTT Sub Sampler,200,"Received 0 of message
1510900508693,0,MQTT Sub Sampler,200,"Received 13,207 of message
1510900510305,0,MQTT Sub Sampler,200,"Received 5,874 of message
1510900512307,0,MQTT Sub Sampler,200,"Received 4,447 of message
1510900514322,0,MQTT Sub Sampler,200,"Received 6,627 of message
1510900516323,0,MQTT Sub Sampler,200,"Received 4,228 of message
1510900518323,0,MQTT Sub Sampler,200,"Received 6,146 of message
1510900520328,0,MQTT Sub Sampler,200,"Received 390 of message
1510900522331,0,MQTT Sub Sampler,200,"Received 484 of message
1510900524333,0,MQTT Sub Sampler,200,"Received 3,525 of message
1510900526334,0,MQTT Sub Sampler,200,"Received 432 of message
1510900528334,0,MQTT Sub Sampler,200,"Received 480 of message
1510900530336,0,MQTT Sub Sampler,200,"Received 2,989 of message
1510900532335,0,MQTT Sub Sampler,200,"Received 4,569 of message
1510900534346,0,MQTT Sub Sampler,200,"Received 456 of message
1510900536383,0,MQTT Sub Sampler,200,"Received 492 of message
1510900538384,0,MQTT Sub Sampler,200,"Received 5,506 of message
1510900540394,0,MQTT Sub Sampler,200,"Received 480 of message
1510900542390,0,MQTT Sub Sampler,200,"Received 475 of message
1510900544392,0,MQTT Sub Sampler,200,"Received 595 of message
1510900546392,0,MQTT Sub Sampler,200,"Received 480 of message
1510900548516,0,MQTT Sub Sampler,200,"Received 480 of message
1510900550507,0,MQTT Sub Sampler,200,"Received 480 of message
1510900552507,0,MQTT Sub Sampler,200,"Received 1,629 of message
1510900554519,0,MQTT Sub Sampler,200,"Received 495 of message
1510900556519,0,MQTT Sub Sampler,200,"Received 1,104 of message
1510900558520,0,MQTT Sub Sampler,200,"Received 1,079 of message
1510900559524,0,MQTT Sub Sampler,200,"Received 2,429 of message
1510900561522,0,MQTT Sub Sampler,200,"Received 1,395 of message
1510900563522,0,MQTT Sub Sampler,200,"Received 3,136 of message
1510900564530,0,MQTT Sub Sampler,200,"Received 334 of message
1510900566532,0,MQTT Sub Sampler,200,"Received 436 of message
1510900568530,0,MQTT Sub Sampler,200,"Received 3,663 of message
1510900570528,0,MQTT Sub Sampler,200,"Received 2,393 of message
1510900572533,0,MQTT Sub Sampler,200,"Received 2,084 of message
1510900573534,0,MQTT Sub Sampler,200,"Received 2,683 of message
1510900575533,0,MQTT Sub Sampler,200,"Received 2,851 of message
1510900577534,0,MQTT Sub Sampler,200,"Received 1,056 of message
1510900579538,0,MQTT Sub Sampler,200,"Received 442 of message
1510900581538,0,MQTT Sub Sampler,200,"Received 3,701 of message
1510900583540,0,MQTT Sub Sampler,200,"Received 384 of message
1510900585541,0,MQTT Sub Sampler,200,"Received 504 of message
1510900587542,0,MQTT Sub Sampler,200,"Received 1,522 of message
1510900589543,0,MQTT Sub Sampler,200,"Received 3,392 of message
1510900591544,0,MQTT Sub Sampler,200,"Received 1,002 of message
1510900593544,0,MQTT Sub Sampler,200,"Received 285 of message
1510900594545,0,MQTT Sub Sampler,200,"Received 253 of message
1510900596558,0,MQTT Sub Sampler,200,"Received 0 of message
1510900598549,0,MQTT Sub Sampler,200,"Received 0 of message
1510900600712,0,MQTT Sub Sampler,200,"Received 0 of message
1510900602715,0,MQTT Sub Sampler,200,"Received 0 of message
1510900603716,0,MQTT Sub Sampler,200,"Received 0 of message
1510900605715,0,MQTT Sub Sampler,200,"Received 0 of message
1510900607716,0,MQTT Sub Sampler,200,"Received 0 of message
1510900609716,0,MQTT Sub Sampler,200,"Received 0 of message
1510900611725,0,MQTT Sub Sampler,200,"Received 0 of message
1510900612728,0,MQTT Sub Sampler,200,"Received 0 of message
1510900614726,0,MQTT Sub Sampler,200,"Received 0 of message
1510900616727,0,MQTT Sub Sampler,200,"Received 0 of message
1510900618745,0,MQTT Sub Sampler,200,"Received 0 of message
1510900620742,0,MQTT Sub Sampler,200,"Received 0 of message
1510900622742,0,MQTT Sub Sampler,200,"Received 0 of message
1510900624742,0,MQTT Sub Sampler,200,"Received 0 of message
1510900626743,0,MQTT Sub Sampler,200,"Received 161 of message
1510900628743,0,MQTT Sub Sampler,200,"Received 151 of message
1510900630743,0,MQTT Sub Sampler,200,"Received 0 of message
1510900632744,0,MQTT Sub Sampler,200,"Received 180 of message
1510900634744,0,MQTT Sub Sampler,200,"Received 182 of message
1510900636744,0,MQTT Sub Sampler,200,"Received 0 of message
1510900638745,0,MQTT Sub Sampler,200,"Received 165 of message
1510900640745,0,MQTT Sub Sampler,200,"Received 176 of message
1510900642745,0,MQTT Sub Sampler,200,"Received 0 of message
1510900644746,0,MQTT Sub Sampler,200,"Received 181 of message
1510900646746,0,MQTT Sub Sampler,200,"Received 199 of message
1510900648746,0,MQTT Sub Sampler,200,"Received 188 of message
1510900650747,0,MQTT Sub Sampler,200,"Received 175 of message
1510900652747,0,MQTT Sub Sampler,200,"Received 0 of message
1510900654747,0,MQTT Sub Sampler,200,"Received 114 of message
1510900656748,0,MQTT Sub Sampler,200,"Received 154 of message
1510900658748,0,MQTT Sub Sampler,200,"Received 167 of message
1510900660748,0,MQTT Sub Sampler,200,"Received 168 of message
1510900662749,0,MQTT Sub Sampler,200,"Received 144 of message
1510900664749,0,MQTT Sub Sampler,200,"Received 131 of message
1510900666749,0,MQTT Sub Sampler,200,"Received 0 of message
1510900668750,0,MQTT Sub Sampler,200,"Received 175 of message
1510900670750,0,MQTT Sub Sampler,200,"Received 188 of message
1510900672750,0,MQTT Sub Sampler,200,"Received 134 of message
1510900674750,0,MQTT Sub Sampler,200,"Received 169 of message
1510900676751,0,MQTT Sub Sampler,200,"Received 108 of message
1510900678751,0,MQTT Sub Sampler,200,"Received 0 of message
1510900680751,0,MQTT Sub Sampler,200,"Received 187 of message
1510900682752,0,MQTT Sub Sampler,200,"Received 145 of message
1510900684752,0,MQTT Sub Sampler,200,"Received 154 of message
1510900686752,0,MQTT Sub Sampler,200,"Received 145 of message
1510900688753,0,MQTT Sub Sampler,200,"Received 0 of message
1510900690753,0,MQTT Sub Sampler,200,"Received 189 of message
1510900692754,0,MQTT Sub Sampler,200,"Received 192 of message
1510900694754,0,MQTT Sub Sampler,200,"Received 185 of message
1510900696754,0,MQTT Sub Sampler,200,"Received 176 of message
1510900698754,0,MQTT Sub Sampler,200,"Received 0 of message
1510900700755,0,MQTT Sub Sampler,200,"Received 200 of message

Thank you very much!

**Comment by emqplus** [comment]
@rainmanwy One subscriber cannot consume more than 20K/S messages.  Please use shared subscription if there are many publishers and fan-in messages.

Docs: http://emqtt.io/docs/v2/advanced.html#shared-subscription
