### ISSUE TITLE
在软路由“”爱快（ikuai）”（debian12系统）上docker中安装eqmx启动报错

### ISSUE THREAD

**Issue by lldacing** [emqx/emqx#13429]
### What happened?

日志信息
![5e823c9a4cb7f4246b9d216e9134bb5](https://github.com/emqx/emqx/assets/43737696/3c9f7cc1-76ae-47f1-9130-414e381780ce)

### What did you expect to happen?

添加上缺少的依赖项

### EMQX version

5.7.1
5.7.0
只测试了这两个版本

### OS version

debian12

**Comment by zmstone** [comment]
请使用 apt 安装 deb 包。

**Comment by lldacing** [comment]
> 请使用 apt 安装 deb 包。

爱快没放开命令行，只支持它提供的菜单。emqx的docker版本为什么不自动安装完整的依赖呢

**Comment by id** [comment]
@lldacing could you elaborate? Which EMQX package exactly are you trying to run? And what is this platform?
Please provide URLs.

**Comment by lldacing** [comment]
> @lldacing could you elaborate? Which EMQX package exactly are you trying to run? And what is this platform? Please provide URLs.


It is a router system. It’s more complicated to explain. 
Here are two links

- https://www.ikuai8.com/component/download

- https://www.ikuai8.com/en

My steps and questions are:
1. I installed the ikuai routing system on the hardware.
2. Installed docker in the routing system.
3. Installed emqx in docker, but failed when starting emqx. The log showed missing dependencies.
4. Steps 2 and 3 are completed through the web interface provided by the routing system.
5. The routing system does not provide full ssh permissions, so I cannot install missing dependencies through ssh.


我的问题是: 
1.我在硬件上安装了ikuai路由系统
2.在路由系统中安装了docker
3.在docker中安装了emqx, 在启动emqx时失败了，日志显示缺少依赖
4.步骤2和3都是通过路由系统提供的web界面完成的。
5.路由系统没有提供完整的ssh权限，我无法通过ssh方式安装缺少的依赖。
@id @zmstone

**Comment by id** [comment]
@lldacing if you installed a .tar.gz package, then it's understandable. It only contains EMQX files, and expects to find openssl and other required libraries in the system.

I don't quite understand why you can't use official emqx docker image https://hub.docker.com/_/emqx directly, instead of pulling debian12 and installing emqx there manually?

**Comment by lldacing** [comment]
> @lldacing if you installed a .tar.gz package, then it's understandable. It only contains EMQX files, and expects to find openssl and other required libraries in the system.
> 
> I don't quite understand why you can't use official emqx docker image https://hub.docker.com/_/emqx directly, instead of pulling debian12 and installing emqx there manually?

Do you mean that the official image already includes those dependencies？ @id

**Comment by id** [comment]
@lldacing yes, exactly.

**Comment by id** [comment]
@dualven which host OS are you using?

**Comment by dualven** [comment]
docker启动emqx开源版报错，请问这是什么问题？ - EMQX - EMQ 问答社区
通过这个已经解决，希望你们在发布的时候也说明下。
centos7 系统 。 

找了两天才找到答案，且报错与解决方案看着没啥联系。

2025-05-06 

dualven 



发件人：Ivan Dyachkov ***@***.***>
发送时间：2025-04-30 18:33
主题：Re: [emqx/emqx] 在软路由“”爱快（ikuai）”（debian12系统）上docker中安装eqmx启动报错 (Issue #13429)
***@***.***>
***@***.***>***@***.***>

id left a comment (emqx/emqx#13429)
@dualven which host OS are you using?
