### ISSUE TITLE
在云服务器连接实例后部署EMQX遇到问题，

### ISSUE THREAD

**Issue by wuziyi176** [emqx/emqx#13428]
Running kernel seems to be up-to-date.

No services need to be restarted.

No containers need to be restarted.

No user sessions are running outdated binaries.

No VM guests are running outdated hypervisor (qemu) binaries on this host.
![Uploading 45454545454.png…]()

**Comment by zmstone** [comment]
please report the issue in text instead of screenshot.
also the link to the image seems to be broken, it appears as "Uploading 45454545454.png…"
