### ISSUE TITLE
在服务区上部署EMQX这一步出现以下问题

### ISSUE THREAD

**Issue by wuziyi176** [emqx/emqx#13427]
root@lavm-oer9vmmnhb:~# sudo apt-get install emqx
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following NEW packages will be installed:
  emqx
0 upgraded, 1 newly installed, 0 to remove and 144 not upgraded.
Need to get 46.0 MB of archives.
After this operation, 127 MB of additional disk space will be used.
Get:1 https://packages.emqx.com/emqx/emqx/ubuntu jammy/main amd64 emqx amd64 5.7.1 [46.0 MB]
20% [1 emqx 11.8 MB/46.0 MB 26%]                                                                                                                           1,210 kB/s 2822% [1 emqx 12.8 MB/46.0 MB 28%]                                                                                                                           1,210 kB/s 2724% [1 emqx 13.6 MB/46.0 MB 30%]                                                                                                                           1,210 kB/s 2625% [1 emqx 14.1 MB/46.0 MB 31%]                                                                                                                           1,210 kB/s 2626% [1 emqx 15.1 MB/46.0 MB 33%]                                                                                                                           1,210 kB/s 2528% [1 emqx 16.2 MB/46.0 MB 35%]                                                                                                                           1,210 kB/s 2430% [1 emqx 17.1 MB/46.0 MB 37%]                                                                                                                           1,210 kB/s 2331% [1 emqx 17.6 MB/46.0 MB 38%]                                                                                                                           1,210 kB/s 2332% [1 emqx 18.6 MB/46.0 MB 40%]                                                                                                                           1,210 kB/s 2234% [1 emqx 19.6 MB/46.0 MB 43%]                                                                                                                           1,210 kB/s 2136% [1 emqx 20.5 MB/46.0 MB 45%]                                                                                                                           1,210 kB/s 2137% [1 emqx 21.1 MB/46.0 MB 46%]                                                                                                                           1,210 kB/s 2038% [1 emqx 22.1 MB/46.0 MB 48%]                                                                                                                           1,719 kB/s 1339% [1 emqx 22.2 MB/46.0 MB 48%]                                                                                                                           1,719 kB/s 1340% [1 emqx 22.8 MB/46.0 MB 50%]                                                                                                                           1,719 kB/s 1341% [1 emqx 23.7 MB/46.0 MB 51%]                                                                                                                           1,719 kB/s 1243% [1 emqx 24.8 MB/46.0 MB 54%]                                                                                                                           1,719 kB/s 1245% [1 emqx 25.7 MB/46.0 MB 56%]                                                                                                                           1,719 kB/s 1146% [1 emqx 26.4 MB/46.0 MB 57%]                                                                                                                           1,719 kB/s 1147% [1 emqx 27.3 MB/46.0 MB 59%]                                                                                                                           1,719 kB/s 1049% [1 emqx 28.2 MB/46.0 MB 61%]                                                                                                                           1,719 kB/s 1050% [1 emqx 29.0 MB/46.0 MB 63%]                                                                                                                            1,719 kB/s 952% [1 emqx 29.6 MB/46.0 MB 64%]                                                                                                                            1,719 kB/s 954% [1 emqx 31.1 MB/46.0 MB 68%]                                                                                                                            1,719 kB/s 856% [1 emqx 32.1 MB/46.0 MB 70%]                                                                                                                            1,671 kB/s 857% [1 emqx 32.7 MB/46.0 MB 71%]                                                                                                                            1,671 kB/s 758% [1 emqx 33.6 MB/46.0 MB 73%]                                                                                                                            1,671 kB/s 761% [1 emqx 34.8 MB/46.0 MB 76%]                                                                                                                            1,671 kB/s 661% [1 emqx 35.3 MB/46.0 MB 77%]                                                                                                                            1,671 kB/s 663% [1 emqx 36.2 MB/46.0 MB 79%]                                                                                                                            1,671 kB/s 564% [1 emqx 36.8 MB/46.0 MB 80%]                                                                                                                            1,671 kB/s 566% [1 emqx 38.0 MB/46.0 MB 83%]                                                                                                                            1,671 kB/s 467% [1 emqx 38.6 MB/46.0 MB 84%]                                                                                                                            1,671 kB/s 469% [1 emqx 39.6 MB/46.0 MB 86%]                                                                                                                            1,671 kB/s 371% [1 emqx 40.9 MB/46.0 MB 89%]                                                                                                                            1,671 kB/s 373% [1 emqx 41.9 MB/46.0 MB 91%]                                                                                                                            1,671 kB/s 274% [1 emqx 42.3 MB/46.0 MB 92%]                                                                                                                            1,691 kB/s 274% [1 emqx 42.4 MB/46.0 MB 92%]                                                                                                                            1,691 kB/s 276% [1 emqx 43.6 MB/46.0 MB 95%]                                                                                                                            1,691 kB/s 176% [1 emqx 43.8 MB/46.0 MB 95%]                                                                                                                            1,691 kB/s 178% [1 emqx 44.9 MB/46.0 MB 98%]                                                                                                                            1,691 kB/s 0100% [Working]                                                                                                                                              1,691 kB/s 0                                                                                                                                                                        Fetched 41.5 MB in 27s (1,567 kB/s)
Selecting previously unselected package emqx.
(Reading database ... 79977 files and directories currently installed.)
Preparing to unpack .../archives/emqx_5.7.1_amd64.deb ...
Unpacking emqx (5.7.1) ...
Setting up emqx (5.7.1) ...
Adding group `emqx' (GID 121) ...
Done.
Adding system user `emqx' (UID 116) ...
Adding new user `emqx' (UID 116) with group `emqx' ...
Not creating home directory `/var/lib/emqx'.
● lavm-oer9vmmnhb
    State: degraded
     Jobs: 0 queued
   Failed: 1 units
    Since: Sat 2024-07-06 18:52:49 CST; 3h 1min ago
   CGroup: /
           ├─user.slice 
           │ └─user-0.slice 
           │   ├─session-15.scope 
           │   │ ├─14241 sshd: root@pts/0
           │   │ ├─14255 -bash
           │   │ ├─14984 sudo apt-get install emqx
           │   │ ├─14985 sudo apt-get install emqx
           │   │ ├─14986 apt-get install emqx
           │   │ ├─15040 /usr/bin/dpkg --status-fd 34 --configure --pending
           │   │ ├─15041 sh -c (test -x /usr/lib/needrestart/dpkg-status && /usr/lib/needrestart/dpkg-status || cat > /dev/null)
           │   │ ├─15042 sh -c (test -x /usr/lib/needrestart/dpkg-status && /usr/lib/needrestart/dpkg-status || cat > /dev/null)
           │   │ ├─15043 /bin/sh /usr/lib/needrestart/dpkg-status
           │   │ ├─15046 /bin/sh /var/lib/dpkg/info/emqx.postinst configure
           │   │ └─15098 systemctl status --no-pager
           │   └─user@0.service …
           │     └─init.scope 
           │       ├─14246 /lib/systemd/systemd --user
           │       └─14247 (sd-pam)
           ├─init.scope 
           │ └─1 /sbin/init autoinstall
           └─system.slice 
             ├─irqbalance.service 
             │ └─452 /usr/sbin/irqbalance --foreground
             ├─packagekit.service 
             │ └─2152 /usr/libexec/packagekitd
             ├─systemd-networkd.service 
             │ └─413 /lib/systemd/systemd-networkd
             ├─systemd-udevd.service 
             │ └─372 /lib/systemd/systemd-udevd
             ├─cron.service 
             │ └─684 /usr/sbin/cron -f -P
             ├─system-serial\x2dgetty.slice 
             │ └─serial-getty@ttyS0.service 
             │   └─700 /sbin/agetty -o -p -- \u --keep-baud 115200,57600,38400,9600 ttyS0 vt220
             ├─jdog_service.service 
             │ ├─ 474 /usr/local/share/jcloud/jdog-monitor/bin/jdog-watchdog
             │ ├─4001 /usr/local/share/jcloud/jdog-monitor/bin/jdog-monitor.1.2.0.60
             │ └─4080 /usr/local/share/jcloud/jdog-monitor/deploy/kunlunmirror/1_2e31777e1f369cb595a79acf5841f83e/bin/jdog-kunlunmirror
             ├─polkit.service 
             │ └─465 /usr/libexec/polkitd --no-debug
             ├─networkd-dispatcher.service 
             │ └─461 /usr/bin/python3 /usr/bin/networkd-dispatcher --run-startup-triggers
             ├─StartOnce.service 
             │ └─796 dhclient
             ├─multipathd.service 
             │ └─368 /sbin/multipathd -d -s
             ├─wpa_supplicant.service 
             │ └─484 /sbin/wpa_supplicant -u -s -O /run/wpa_supplicant
             ├─ModemManager.service 
             │ └─505 /usr/sbin/ModemManager
             ├─systemd-journald.service 
             │ └─331 /lib/systemd/systemd-journald
             ├─unattended-upgrades.service 
             │ └─519 /usr/bin/python3 /usr/share/unattended-upgrades/unattended-upgrade-shutdown --wait-for-signal
             ├─jdcloudservice.service 
             │ └─1603 /usr/bin/jdcloudservice -L=/var/log/jcloud/jdcloudservice
             ├─ssh.service 
             │ └─709 sshd: /usr/sbin/sshd -D [listener] 0 of 10-100 startups
             ├─NetworkManager.service 
             │ └─446 /usr/sbin/NetworkManager --no-daemon
             ├─rsyslog.service 
             │ └─466 /usr/sbin/rsyslogd -n -iNONE
             ├─chrony.service 
             │ ├─550 /usr/sbin/chronyd -F 1
             │ └─555 /usr/sbin/chronyd -F 1
             ├─jcs-agent-core.service 
             │ ├─1152 /usr/local/share/jcloud/agent/core/JCSAgentCore >/dev/null 2>&1
             │ └─1690 /usr/local/share/jcloud/agent/plugins/MonitorPlugin-3.0.1303.2912a9f/MonitorPlugin -l unix:///usr/local/share/jcloud/agent/plugins/MonitorPlugin-3.…
             ├─nscd.service 
             │ └─467 /usr/sbin/nscd
             ├─systemd-resolved.service 
             │ └─435 /lib/systemd/systemd-resolved
             ├─udisks2.service 
             │ └─483 /usr/libexec/udisks2/udisksd
             ├─dbus.service 
             │ └─445 @dbus-daemon --system --address=systemd: --nofork --nopidfile --systemd-activation --syslog-only
             ├─system-getty.slice 
             │ └─getty@tty1.service 
             │   └─708 /sbin/agetty -o -p -- \u --noclear tty1 linux
             ├─ifritd.service 
             │ ├─522 /usr/local/share/jcloud/ifrit/sbin/ifrit-supervise
             │ └─533 /usr/local/share/jcloud/ifrit/sbin/ifrit-agent
             └─systemd-logind.service 
               └─479 /lib/systemd/systemd-logind
Created symlink /etc/systemd/system/multi-user.target.wants/emqx.service → /lib/systemd/system/emqx.service.
Scanning processes... [                                                                                                                                                 Scanning processes... [=                                                                                                                                                Scanning processes... [==                                                                                                                                               Scanning processes... [===                                                                                                                                              Scanning processes... [====                                                                                                                                             Scanning processes... [======                                                                                                                                           Scanning processes... [=======                                                                                                                                          Scanning processes... [========                                                                                                                                         Scanning processes... [=========                                                                                                                                        Scanning processes... [===========                                                                                                                                      Scanning processes... [============                                                                                                                                     Scanning processes... [=============                                                                                                                                    Scanning processes... [==============                                                                                                                                   Scanning processes... [================                                                                                                                                 Scanning processes... [=================                                                                                                                                Scanning processes... [==================                                                                                                                               Scanning processes... [===================                                                                                                                              Scanning processes... [=====================                                                                                                                            Scanning processes... [======================                                                                                                                           Scanning processes... [=======================                                                                                                                          Scanning processes... [========================                                                                                                                         Scanning processes... [=========================                                                                                                                        Scanning processes... [===========================                                                                                                                      Scanning processes... [============================                                                                                                                     Scanning processes... [=============================                                                                                                                    Scanning processes... [==============================                                                                                                                   Scanning processes... [================================                                                                                                                 Scanning processes... [=================================                                                                                                                Scanning processes... [==================================                                                                                                               Scanning processes... [===================================                                                                                                              Scanning processes... [=====================================                                                                                                            Scanning processes... [======================================                                                                                                           Scanning processes... [=======================================                                                                                                          Scanning processes... [========================================                                                                                                         Scanning processes... [==========================================                                                                                                       Scanning processes... [===========================================                                                                                                      Scanning processes... [============================================                                                                                                     Scanning processes... [=============================================                                                                                                    Scanning processes... [===============================================                                                                                                  Scanning processes... [================================================                                                                                                 Scanning processes... [=================================================                                                                                                Scanning processes... [==================================================                                                                                               Scanning processes... [===================================================                                                                                              Scanning processes... [=====================================================                                                                                            Scanning processes... [======================================================                                                                                           Scanning processes... [=======================================================                                                                                          Scanning processes... [========================================================                                                                                         Scanning processes... [==========================================================                                                                                       Scanning processes... [===========================================================                                                                                      Scanning processes... [============================================================                                                                                     Scanning processes... [=============================================================                                                                                    Scanning processes... [===============================================================                                                                                  Scanning processes... [================================================================                                                                                 Scanning processes... [=================================================================                                                                                Scanning processes... [==================================================================                                                                               Scanning processes... [====================================================================                                                                             Scanning processes... [=====================================================================                                                                            Scanning processes... [======================================================================                                                                           Scanning processes... [=======================================================================                                                                          Scanning processes... [=========================================================================                                                                        Scanning processes... [==========================================================================                                                                       Scanning processes... [===========================================================================                                                                      Scanning processes... [============================================================================                                                                     Scanning processes... [=============================================================================                                                                    Scanning processes... [===============================================================================                                                                  Scanning processes... [================================================================================                                                                 Scanning processes... [=================================================================================                                                                Scanning processes... [==================================================================================                                                               Scanning processes... [====================================================================================                                                             Scanning processes... [=====================================================================================                                                            Scanning processes... [======================================================================================                                                           Scanning processes... [=======================================================================================                                                          Scanning processes... [=========================================================================================                                                        Scanning processes... [==========================================================================================                                                       Scanning processes... [===========================================================================================                                                      Scanning processes... [============================================================================================                                                     Scanning processes... [==============================================================================================                                                   Scanning processes... [===============================================================================================                                                  Scanning processes... [================================================================================================                                                 Scanning processes... [=================================================================================================                                                Scanning processes... [==================================================================================================                                               Scanning processes... [====================================================================================================                                             Scanning processes... [=====================================================================================================                                            Scanning processes... [======================================================================================================                                           Scanning processes... [=======================================================================================================                                          Scanning processes... [=========================================================================================================                                        Scanning processes... [==========================================================================================================                                       Scanning processes... [===========================================================================================================                                      Scanning processes... [============================================================================================================                                     Scanning processes... [==============================================================================================================                                   Scanning processes... [===============================================================================================================                                  Scanning processes... [================================================================================================================                                 Scanning processes... [=================================================================================================================                                Scanning processes... [===================================================================================================================                              Scanning processes... [====================================================================================================================                             Scanning processes... [=====================================================================================================================                            Scanning processes... [======================================================================================================================                           Scanning processes... [========================================================================================================================                         Scanning processes... [=========================================================================================================================                        Scanning processes... [==========================================================================================================================                       Scanning processes... [===========================================================================================================================                      Scanning processes... [============================================================================================================================                     Scanning processes... [==============================================================================================================================                   Scanning processes... [===============================================================================================================================                  Scanning processes... [================================================================================================================================                 Scanning processes... [=================================================================================================================================                Scanning processes... [===================================================================================================================================              Scanning processes... [====================================================================================================================================             Scanning processes... [=====================================================================================================================================            Scanning processes... [======================================================================================================================================           Scanning processes... [========================================================================================================================================         Scanning processes... [=========================================================================================================================================        Scanning processes... [==========================================================================================================================================       Scanning processes... [===========================================================================================================================================      Scanning processes... [=============================================================================================================================================    Scanning processes... [==============================================================================================================================================   Scanning processes... [===============================================================================================================================================  Scanning processes... [================================================================================================================================================ Scanning processes... [=================================================================================================================================================Scanning processes...                                                                                                                                                     
Scanning linux images... [                                                                                                                                              Scanning linux images... [===============================================                                                                                               Scanning linux images... [===============================================================================================                                               Scanning linux images... [==============================================================================================================================================Scanning linux images...                                                                                                                                                  

Running kernel seems to be up-to-date.

No services need to be restarted.

No containers need to be restarted.

No user sessions are running outdated binaries.

No VM guests are running outdated hypervisor (qemu) binaries on this host.

**Comment by zmstone** [comment]
Seems EMQX failed to start?
Could you share the logs in /var/log/emqx ?
