### ISSUE TITLE
"Mnesia is overloaded" messaggio di warning

### ISSUE THREAD

**Issue by AndreaSpolaorBT** [emqx/emqx#13440]
### What happened?

Hello everyone,

I would like to report the following issue: during the execution of the EMQX service, warning logs appeared indicating "Mnesia is overloaded." This caused a delay in message dequeueing of about 3 minutes.

Here are the logs:
![image](https://github.com/emqx/emqx/assets/136359222/b423b375-d785-4dd1-a5ba-5d4b2ba167c2)

I am showing the application logs that indicate a delay in message dequeueing.
![image](https://github.com/emqx/emqx/assets/136359222/24e99b6a-b64b-4e73-9b6f-8fe4b151ee79)

Meanwhile, the service that queues the messages did not encounter any problems or delays in sending them.
![image](https://github.com/emqx/emqx/assets/136359222/88ef6e47-d050-4093-990b-909e65cfc477)

If you need any further adjustments or additions, please let me know!

### What did you expect to happen?

I would have expected that the developed service responsible for dequeuing messages would not have this approximately 3-minute blockage during the message dequeueing phas

### How can we reproduce it (as minimally and precisely as possible)?

The issue is not reproducible, but it might occur when putting the MQTT broker under pressure.

### EMQX version

emqx v5.6.1 is running

### OS version

NAME="Red Hat Enterprise Linux"
VERSION="9.3 (Plow)"
ID="rhel"
ID_LIKE="fedora"
VERSION_ID="9.3"
PLATFORM_ID="platform:el9"
PRETTY_NAME="Red Hat Enterprise Linux 9.3 (Plow)"
ANSI_COLOR="0;31"
LOGO="fedora-logo-icon"
CPE_NAME="cpe:/o:redhat:enterprise_linux:9::baseos"
HOME_URL="https://www.redhat.com/"
DOCUMENTATION_URL="https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/9"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 9"
REDHAT_BUGZILLA_PRODUCT_VERSION=9.3
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="9.3"

**Comment by ieQu1** [comment]
"Mnesia overload" message doesn't occur on its own, and it's typically a consequence of some other load-related event. 
Do you have storms of clients (re)connecting or subscribing to topics?

**Comment by qzhuyan** [comment]
this is mostly due to slow disk I/O. 
Could you check you monitoring if disk I/O looks abnormal?  

Could you describe the business for us to understand what may cause the pressure on the disk I/O?

**Comment by ieQu1** [comment]
Not enough information to investigate the issue, closing.
