### ISSUE TITLE
mosquitto vs activemq vs emq

### ISSUE THREAD

**Issue by cofol1986** [emqx/emqx#1349]
#### Environment
- OS: ubuntu 14.04.5
- Erlang/OTP: embed
- EMQ: 2.3
we get emq from the url: http://emqtt.com/downloads/2306/ubuntu14_04

#### Description
I compare the fan-in performance between mosquitto, emq and activemq.

I have tune emq performance according the tunning guid provided by emq's website, the mosquitto and
activemq is as default.

In my testbed, I simulate 1000 mqtt clients and each one sends 10 message/s with only one subscriber to injest all the messages. 
The fanout testing results are as following:
mosquitto cpu:24% mem:3M
emq       cpu:130% mem:300M
activemq  cpu:60% mem:983M

I have try to optimize the CPU usage of EMQ by tuning the full sweep and force gc option, but the performance of emq still poor.

@emqplus   My question is:
EMQ consume too much CPU resources comparing mosquitto or activemq, Is this normal or there are some way to reduce it? 

By the way, my emq vm config is as follows:
`+W w
-kernel net_ticktime 60
-env ERL_CRASH_DUMP /var/log/emqttd/crash.dump
+e 256000
-env ERL_FULLSWEEP_AFTER 65535
+Q 65536
+P 256000
+A 32
+K true
-smp auto
-setcookie emqsecretcookie
-name emq@127.0.0.1`

Thanks in advance.

**Comment by cofol1986** [comment]
Hi @turtleDeng and @emqplus , what are your ideas about this issue?

**Comment by Gilbert-Wong** [comment]
@cofol1986 , I have tried with hipe, it is useless, but we have schedule to merge session and connection layer internal which would improve the performance significantly.

**Comment by Gilbert-Wong** [comment]
We have tested ERTS with hipe, it is useless, We have a schedule to merge connection layer and session layer which would bring a huge performance improvement.
