### ISSUE TITLE
connection_shutdown with reason: #{hint => invalid_password

### ISSUE THREAD

**Issue by tiaan-lg** [emqx/emqx#13508]
### What happened?

We use a websocket via a Flutter app to connect up to our broker and the credentials for 1 user works on our simulators and devices but from his device we get a bad username or password response from the mqtt client

We looked into our broker logs and found the following entries match up with the events

`2024--07-22T18:15:22.504472+00:00 [error] supervisor: {esockd_connection_sup,<0.1746199.0>}, errorContext: connection_shutdown, reason: #{hint => invalid_password,remaining_bytes_length => 12,parsed_length => 16724}, offender: [{pid,<0.1746199.0>},{name,connection},{mfargs,{emqx_connection,start_link,[#{listener => {tcp,default},limiter => undefined,enable_authn => true,zone => default}]}}]`

`2024--07-22T13:19:38.951113+00:00 [error] supervisor: {esockd_connection_sup,<0.484864.0>}, errorContext: connection_shutdown, reason: #{hint => invalid_password,remaining_bytes_length => 12,parsed_length => 21078}, offender: [{pid,<0.484864.0>},{name,connection},{mfargs,{emqx_connection,start_link,[#{listener => {tcp,default},limiter => undefined,enable_authn => true,zone => default}]}}]`

`2024--07-22T15:48:54.281288+00:00 [error] supervisor: {esockd_connection_sup,<0.1166730.0>}, errorContext: connection_shutdown, reason: #{hint => invalid_password,remaining_bytes_length => 12,parsed_length => 18768}, offender: [{pid,<0.1166730.0>},{name,connection},{mfargs,{emqx_connection,start_link,[#{listener => {tcp,default},limiter => undefined,enable_authn => true,zone => default}]}}]`

`2024-07-23T10:30:56.356740+00:00 [error] supervisor: {esockd_connection_sup,<0.6052919.0>}, errorContext: connection_shutdown, reason: #{hint => invalid_password,remaining_bytes_length => 12,parsed_length => 44334}, offender: [{pid,<0.6052919.0>},{name,connection},{mfargs,{emqx_connection,start_link,[#{listener => {tcp,default},limiter => undefined,enable_authn => true,zone => default}]}}]`

But we are not sure exactly what is going wrong on the broker 

### What did you expect to happen?

The excepted outcome is for the username and password to work on his device using the exact same mqtt client and credentials that work when we use them to connect

### EMQX version

<details>

```console
$ ./bin/emqx_ctl broker
sysdescr  : EMQX
version   : 5.5.0
datetime  : 2024-07-23T13:37:45.916212814+00:00
uptime    : 1 days, 1 hours, 34 minutes, 15 seconds
```
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
PRETTY_NAME="Ubuntu 22.04.3 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.3 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
$ uname -a
Linux fsk-apnliJCQM9T 6.5.0-1024-azure #25~22.04.1-Ubuntu SMP Mon Jun 17 18:38:57 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
```

</details>

### Log files

<details>
[emqx.log](https://github.com/user-attachments/files/16349655/emqx.log)

</details>

**Comment by id** [comment]
@tiaan-lg please check your client code. It looks like it's sending password which is way too large, and likely not what you intended to send as a password.

```
hint => invalid_password,remaining_bytes_length => 12,parsed_length => 44334
```

Here we can see that EMQX parsed 44334 bytes from the password field, and total data size was 44346 bytes.

**Comment by tiaan-lg** [comment]
Thank you for the quick response, we will check the client and see what could be causing this
