### ISSUE TITLE
emqx4.4.7 Node is already running

### ISSUE THREAD

**Issue by yupingsong-anylink-io** [emqx/emqx#13517]
### What happened?

集群有两个节点，分别部署在两台内网服务器，集群方式是cluster.discovery = static
两个节点node.name分别是emqx@emq.a-iot.internal，emqx@emq.b-iot.internal
4370, 5370端口都没修改，使用默认端口。

两台服务器同时开机时，emqx会随开机自启动。b节点的emqx正常启动了，但是a节点emqx启动时报错：
```
Eshell V12.1.5  (abort with ^G)
1> *** Terminating erlang (nonode@nohost)
There seem to be missing dynamic libs from the OS.
Using libs from /usr/apps/emqx4.4.7/dynlibs instead.
NOTE: EMQX's rpm or deb package installation is recommended!
Node is already running!
```
我看了一下4370和5370端口都没有占用，emqx/log下没有任何日志，通过ps -ef | grep emqx也没有正在运行的进程。
随后我手动启动了这个emqx节点，启动成功了，也没有报任何错误。

### What did you expect to happen?

emqx除了通过node.name判断是否处于running状态之外，还有其他判断的依据吗？

### EMQX version

4.4.7

### OS version

Amazon Linux 2023

**Comment by qzhuyan** [comment]
Maybe check the log of systemd? Assume you installed with rpm?

**Comment by yupingsong-anylink-io** [comment]
No, not rpm, I used zip file

**Comment by yupingsong-anylink-io** [comment]
I compared the systemd logs of other environments and found that there are relevant logs in the systemd, where emqx starts normally. 
But in my problematic environment, there is no emqx startup log.

**Comment by qzhuyan** [comment]
So you write your own systemd service file to be part of the boot procedure? could you share it? 

from below, I think the network isn't started causing EMQX has issue to get the node name. Maybe some race in systemd boot sequences. 
```
1> *** Terminating erlang (nonode@nohost)

```

**Comment by yupingsong-anylink-io** [comment]
Yes, emqx is started in my own systemd service. 
`autorun.service`:
```
[Unit]
Description=Autorun Script
After=network.target cloud-init.target

[Service]
LimitNOFILE=500000
ExecStart=/usr/apps/autorun.sh start
Type=simple
User=ec2-user
KillMode=process

[Install]
WantedBy=default.target
```

And the content of `autorun.sh` as follows:
```
#!/bin/sh
#chkconfig:2345 80 90
#description:auto_run
#batch run agent and stop agent.

prog_start(){
    echo $(date "+%m/%d-%H:%M:%S") "---emqx---">> /usr/apps/autorun.log
    cd /usr/apps/emqx4.4.7/bin
    ./emqx start >> /usr/apps/autorun.log 2>&1
}

case "$1" in
    start)
          prog_start
          ;;

      *)
        echo $"Usage: $0 {start}"
    exit 1
         ;;
esac
```

**Comment by qzhuyan** [comment]
ok. pls refer to our systemd.service file 
 https://github.com/emqx/emqx/tree/release-v44/deploy/packages

There are some tricks to make emqx works properly.

**Comment by qzhuyan** [comment]
sorry clicked closed ticket by accident.

**Comment by yupingsong-anylink-io** [comment]
Thanks for your help, I'll try it, and then provide feedback.

**Comment by zmstone** [comment]
The log is from here:
https://github.com/emqx/emqx/blob/v4.4.7/bin/emqx#L600

It simply means the node is currently running, so it cannot start with this same name.
It reported (nonode@nohost) because the temp node which runs the nodetool did not have a name assigned yet.

To start a daemon node, you'll need to stop it first.
In version 5, daemon mode is being deprecated, nobody in production uses daemon mode anymore.
If you want to implement your own supervise solution, maybe use `console` mode or `foreground` mode instead, it will be simpler.
