### ISSUE TITLE
JWT Payload Fails to pass the verification after the `Claim` and `Expected Value` are configured

### ISSUE THREAD

**Issue by yl-yue** [emqx/emqx#13512]
### What happened?

jwt Payload
```json
{
  "username": 10133,
  "exp": 1722160076
}
```

Payload Claims
![73e16fc5fae2cd5219050d2644d1e6bc_5617bbbdc099a4e053f6437a3b6047a82c44bfe0_2_690x101](https://github.com/user-attachments/assets/22698bc7-e88d-4e87-942b-535f20b62bbf)

The configuration here has been set repeatedly, setting flexible `${username}`, setting fixed values, etc., tossing references to keys, etc., all fail to pass jwt verification.

### What did you expect to happen?
Successfully established connection

### EMQX version
5.7.1 docker

### Log files

<details>

```log
2024-07-24T05:51:11.698383+00:00 [warning] msg: log_events_throttled_during_last_period, dropped: #{authentication_failure => 2}, period: 1 minutes, 0 seconds
2024-07-24T05:51:25.989950+00:00 [warning] tag: AUTHN, clientid: mqttx_552e016c, msg: authentication_failure, peername: 14.109.148.250:63261, username: 10133, reason: bad_username_or_password
```

</details>

**Comment by yl-yue** [comment]
After verification, jwt payload does not support the check digit type, only supports the string type, the username value with **double quotes** can pass the check:

```json
{
  "username": "10133",
  "exp": 1722160076
}
```

**Comment by qzhuyan** [comment]
So we close the issue?

**Comment by yl-yue** [comment]
@zmstone Hello, is this issue solved or does emqx not provide numeric type validation

**Comment by zmstone** [comment]
Hi @yl-yue 
All claims except for the timestamps should have string values.

**Comment by NotFound403** [comment]
> Hi [@yl-yue](https://github.com/yl-yue) All claims except for the timestamps should have string values.

https://datatracker.ietf.org/doc/html/rfc7519#section-4.1.4     you can see from that    

```
"exp" (Expiration Time) Claim

   The "exp" (expiration time) claim identifies the expiration time on
   or after which the JWT MUST NOT be accepted for processing.  The
   processing of the "exp" claim requires that the current date/time
   MUST be before the expiration date/time listed in the "exp" claim.
   Implementers MAY provide for some small leeway, usually no more than
   a few minutes, to account for clock skew.  Its value MUST be a number
   containing a NumericDate value.  Use of this claim is OPTIONAL.
```

About the term `NumbericDate` defined

```
NumericDate
      A JSON numeric value representing the number of seconds from
      1970-01-01T00:00:00Z UTC until the specified UTC date/time,
      ignoring leap seconds.  This is equivalent to the IEEE Std 1003.1,
      2013 Edition [[POSIX.1](https://datatracker.ietf.org/doc/html/rfc7519#ref-POSIX.1)] definition "Seconds Since the Epoch", in
      which each day is accounted for by exactly 86400 seconds, other
      than that non-integer values can be represented.  See [RFC 3339](https://datatracker.ietf.org/doc/html/rfc3339)
      [[RFC3339](https://datatracker.ietf.org/doc/html/rfc3339)] for details regarding date/times in general and UTC in
      particular.
```

**Comment by NotFound403** [comment]
> Hi [@yl-yue](https://github.com/yl-yue) All claims except for the timestamps should have string values.

#15521
