### ISSUE TITLE
esockd_connection_sup Error Interpretation

### ISSUE THREAD

**Issue by seinshah** [emqx/emqx#13529]
### What happened?

I have a cluster with two core nodes and ~4k live connections. I regularly see `esockd_connection_sup` related error logs with `connection_shutdown` error context almost every 5 to 10 minutes. These error have limited set of reason string which some of them are listed below.
My main concern is since I couldn't find any documentation, I'm not able to interpret these errors to understand whether they are caused by a faulty client request or is it triggered by the server.
Could you please point me to the right place to understand these error or help me debug them? 

### What did you expect to happen?

I didn't expect to see such errors as I don't see them on the staging environment with way less number of live connections. So, indeed they can be caused by higher number of connections and lack of resources somewhere or by a client with an invalid packet transmission.

JFYI, CPU and memory Utilization is below 50%.

### EMQX version

<details>

```console
$ ./bin/emqx_ctl broker
sysdescr  : EMQX
version   : 5.7.1
datetime  : 2024-07-26T17:40:44.485250738+00:00
uptime    : 3 hours, 37 minutes, 24 seconds
```

</details>

### OS version

<details>

```console
$ cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 12 (bookworm)"
NAME="Debian GNU/Linux"
VERSION_ID="12"
VERSION="12 (bookworm)"
VERSION_CODENAME=bookworm
ID=debian

$ uname -a
Linux ip-10-1-2-10.eu-central-1.compute.internal 6.1.97-104.177.amzn2023.aarch64 #1 SMP Tue Jul 16 15:18:22 UTC 2024 aarch64 GNU/Linux
```

</details>

### Log files

<details>

```
supervisor: {esockd_connection_sup,<0.1072615.0>}, errorContext: connection_shutdown, reason: #{invalid_property_code => 52}, offender: [{pid,<0.1072615.0>},{name,connection},{mfargs,{emqx_connection,start_link,[#{listener => {tcp,default},limiter => undefined,zone => default,enable_authn => true}]}}]
```

```
supervisor: {esockd_connection_sup,<0.1328324.0>}, errorContext: connection_shutdown, reason: #{invalid_property_code => 48}, offender: [{pid,<0.1328324.0>},{name,connection},{mfargs,{emqx_connection,start_link,[#{listener => {tcp,default},limiter => undefined,enable_authn => true,zone => default}]}}]
```

```
supervisor: {esockd_connection_sup,<0.859362.0>}, errorContext: connection_shutdown, reason: #{invalid_property_code => 57}, offender: [{pid,<0.859362.0>},{name,connection},{mfargs,{emqx_connection,start_link,[#{listener => {tcp,default},limiter => undefined,zone => default,enable_authn => true}]}}]
```

```
supervisor: {esockd_connection_sup,<0.1089714.0>}, errorContext: connection_shutdown, reason: #{cause => zero_remaining_len,header_type => 0}, offender: [{pid,<0.1089714.0>},{name,connection},{mfargs,{emqx_connection,start_link,[#{listener => {tcp,default},limiter => undefined,enable_authn => true,zone => default}]}}]
```

```
supervisor: {esockd_connection_sup,<0.1143844.0>}, errorContext: connection_shutdown, reason: #{cause => malformed_packet,header_type => 0}, offender: [{pid,<0.1143844.0>},{name,connection},{mfargs,{emqx_connection,start_link,[#{listener => {tcp,default},limiter => undefined,enable_authn => true,zone => default}]}}]
```

```
supervisor: {esockd_connection_sup,<0.842291.0>}, errorContext: connection_shutdown, reason: #{cause => zero_remaining_len,header_type => 3}, offender: [{pid,<0.842291.0>},{name,connection},{mfargs,{emqx_connection,start_link,[#{listener => {tcp,default},limiter => undefined,zone => default,enable_authn => true}]}}]
```

And similar logs. The following log might also give you some context if it's related

```
{"msg":"disconnecting_due_to_unexpected_message","packet":["mqtt_packet",["mqtt_packet_header",6,"false",2,"false"],["mqtt_packet_puback",29,0,{}],"undefined"]}
```

</details>

**Comment by qzhuyan** [comment]
hi, they are mostly  protocol violations from the client. document is the MQTT spec here, 
 https://docs.oasis-open.org/mqtt/mqtt/v5.0/os/mqtt-v5.0-os.html

Just take one example: 
```
supervisor: {esockd_connection_sup,<0.842291.0>}, errorContext: connection_shutdown, reason: #{cause => zero_remaining_len,header_type => 3}, offender: [{pid,<0.842291.0>},{name,connection},{mfargs,{emqx_connection,start_link,[#{listener => {tcp,default},limiter => undefined,zone => default,enable_authn => true}]}}]
```
`header_type => 3` means it is PUBLISH message, `cause => zero_remaining_len ` means the remaining len of the publish is 0.

**Comment by seinshah** [comment]
Hi @qzhuyan, thanks so much for getting back to me so quickly.

Then I'll go through mqtt protocol to understand these better and hopefully get verbose connection data by enabling lower log level as it's hard to pinpoint the client now.
More weird is header type 0 for some of them.

**Comment by zmstone** [comment]
https://docs.oasis-open.org/mqtt/mqtt/v5.0/os/mqtt-v5.0-os.html#_Toc3901024

3 types of messages, namely `DISCONNECT`, `PINGREQ`, and `PINGRSP` have one-byte (type and flags) message
All other messages must have more bytes following.

If you set logging level to debug, you should be able to see some raw bytes. My guess is it's probably not a MQTT client at all. .e.g if the port is open towards internet, some port scanner, content crawler may connect to it.
