### ISSUE TITLE
设备频繁断开连接，设备断开原因是 bad_frame_header

### ISSUE THREAD

**Issue by bookc-man** [emqx/emqx#13549]
### What happened?

centos 7
docker运行环境
使用的是5.7.1的版本

### What did you expect to happen?

centos 7
docker运行环境
使用的是5.7.1的版本

### EMQX version

5.7.1

### OS version

centos 7

### Log files

centos 7
docker运行环境
使用的是5.7.1的版本

**Comment by bookc-man** [comment]
![image](https://github.com/user-attachments/assets/f5586272-9a9e-4d50-be11-21889e3afaed)
这个关闭就可以了

**Comment by savonarola** [comment]
Hello!
Was the problem solved after switching off "Strict Mode"?

**Comment by zmstone** [comment]
@savonarola 
Maybe the screenshot was to indicate that Strict Mode is off.
Turning it on only causes more errors. 

@bookc-man 
bad_frame_header means EMQX is unable to decode the very first byte of the MQTT packet.
Maybe some bug on the client side code which corrupted the underlying send buffer.
You can try to trace the client ID, or turn on debug level logging, or use tcpdump/wireshark to inspect which bytes the client sent.

I don't think it's a bug in EMQX. So I am going to close this ticket.
