### ISSUE TITLE
共享订阅客户端主动断开连接后，`emqx`仍然会向离线的客户端推送消息，导致消息顺序错乱

### ISSUE THREAD

**Issue by yl-yue** [emqx/emqx#13564]
### What happened?

共享订阅客户端主动断开连接后，`emqx`也知道此客户端已离线，但仍然会向已离线的客户端推送消息，由于消息长时间未送达，`emqx`会重新选择节点推送消息，最终导致消息接收顺序错乱

### What did you expect to happen?

已离线的客户端，不会再被轮询，这样就可以避免消息顺序错乱

### How can we reproduce it (as minimally and precisely as possible)?

MQTTX创建3个客户端：
- 发布客户端
- 共享订阅客户端
- 共享订阅客户端

1. 发送消息确保订阅客户端都能接收消息
2. 离线一个共享订阅客户端
3. 发送多条带id顺序的消息
4. 确认还剩下的一个共享订阅客户端消息接收顺序

### EMQX version

5.7.1

### OS version

docker

**Comment by zmstone** [comment]
如果共享订阅的客户端在断线后会话保留了，那么会话会继续接收消息知道会话过期。
会话过期后消息会重新派发给组内其他成员。

建议不要使用保留会话（clean-session=true，或expiry-interval=0）

**Comment by zmstone** [comment]
这里有也相关讨论： https://github.com/emqx/emqx/discussions/13566
