### ISSUE TITLE
Connection Id 462860614 closing with reason: tcp_closed

### ISSUE THREAD

**Issue by venks-warrior** [emqx/emqx#1357]
#### Environment

- OS: Linux
- Erlang/OTP: OTP
- EMQ: 2.3

#### Description

Hi , 

I am using Spark job to read events from EMQTT brokers.I see that, client connection is lost regularly with following errors in emqtt broker.

09:52:22.497 [debug] Client(*.*.*.*:20594): Terminated for {shutdown,closed}
09:52:23.368 [error] Connection Id 462860614 closing with reason: tcp_closed
09:52:23.368 [error] gen_server <0.1889.0> terminated with reason: tcp_closed
09:52:23.369 [error] CRASH REPORT Process <0.1889.0> with 0 neighbours exited with reason: tcp_closed in gen_server:handle_common_reply/8 line 726
09:52:25.756 [error] Connection Id 462860789 closing with reason: tcp_closed
09:52:25.756 [error] gen_server <0.1890.0> terminated with reason: tcp_closed
09:52:25.756 [error] CRASH REPORT Process <0.1890.0> with 0 neighbours exited with reason: tcp_closed in gen_server:handle_common_reply/8 line 726
09:52:26.072 [debug] Client(10.200.8.176:5549): Terminated for {shutdown,closed}
09:52:26.369 [error] Connection Id 462860817 closing with reason: tcp_closed
09:52:26.369 [error] gen_server <0.1892.0> terminated with reason: tcp_closed
09:52:26.369 [error] CRASH REPORT Process <0.1892.0> with 0 neighbours exited with reason: tcp_closed in gen_server:handle_common_reply/8 line 726
09:52:26.756 [error] Connection Id 462860818 closing with reason: tcp_closed
09:52:26.756 [error] gen_server <0.1893.0> terminated with reason: tcp_closed
09:52:26.756 [error] CRASH REPORT Process <0.1893.0> with 0 neighbours exited with reason: tcp_closed in gen_server:handle_common_reply/8 line 726
09:52:46.369 [error] Connection Id 462862625 closing with reason: tcp_closed
09:52:46.369 [error] gen_server <0.1902.0> terminated with reason: tcp_closed
09:52:46.369 [error] CRASH REPORT Process <0.1902.0> with 0 neighbours exited with reason: tcp_closed in gen_server:handle_common_reply/8 line 726
09:52:46.756 [error] Connection Id 462862692 closing with reason: tcp_closed
09:52:46.756 [error] gen_server <0.1903.0> terminated with reason: tcp_closed
09:52:46.756 [error] CRASH REPORT Process <0.1903.0> with 0 neighbours exited with reason: tcp_closed in gen_server:handle_common_reply/8 line 726
09:52:46.756 [error] Connection Id 462862693 closing with reason: tcp_closed
09:52:46.756 [error] gen_server <0.1904.0> terminated with reason: tcp_closed
09:52:46.756 [error] CRASH REPORT Process <0.1904.0> with 0 neighbours exited with reason: tcp_closed in gen_server:handle_common_reply/8 line 726
09:52:52.497 [debug] Client(*.*.*.*:20614): Terminated for {shutdown,closed}
09:52:56.071 [debug] Client(10.200.8.176:5567): Terminated for {shutdown,closed}

[error] Supervisor 'esockd_connection_sup - <0.1346.0>' had child connection started with mochiweb_http:start_link({emq_dashboard,handle_request,[{state,"/usr/lib/emqttd/lib/emq_dashboard-2.3/priv/www",#Fun<emq_das..>}]}) at <0.1524.0> exit with reason {json_encode,{bad_term,{error,nodedown}}} in context connection_crashed
10:31:00.697 [debug] Mod:emqttd_rest_api, Fun:nodes, Args:['GET',[]]
10:31:00.699 [debug] Mod:emqttd_rest_api, Fun:stat, Args:['GET',[],"emq@10.200.6.68"]
10:31:00.701 [debug] Mod:emqttd_rest_api, Fun:broker, Args:['GET',[],"emq@10.200.6.68"]
10:31:07.701 [error] Execute API 'management/nodes/emq@10.200.6.68' Error: {function_clause,[{proplists,get_value,[version,{error,nodedown},undefined],[{file,"proplists.erl"},{line,215}]},{emqttd_rest_api,format_broker,1,[{file,"src/emqttd_rest_api.erl"},{line,305}]},{emqttd_rest_api,broker,3,[{file,"src/emqttd_rest_api.erl"},{line,267}]},{emqttd_http,'-dispatcher/1-fun-6-',3,[{file,"src/emqttd_http.erl"},{line,101}]},{mochiweb_http,headers,5,[{file,"src/mochiweb_http.erl"},{line,75}]}]}
10:31:07.702 [error] Supervisor 'esockd_connection_sup - <0.1346.0>' had child connection started with mochiweb_http:start_link({emq_dashboard,handle_request,[{state,"/usr/lib/emqttd/lib/emq_dashboard-2.3/priv/www",#Fun<emq_das..>}]}) at <0.1533.0> exit with reason {json_encode,{bad_term,{error,nodedown}}} in context connection_crashed

I have enabled debug logs.But nothing else seems to be wrong.Also, i am producing my events from java paho client and while producing no issues are seen.

*A description of the issue*

Please help me solve with this.

Following are the exception logs in my spark streaming job.

17/11/28 12:52:59 WARN ReceiverSupervisorImpl: Restarting receiver with delay 2000 ms: Connection lost 
Connection lost (32109) - java.io.EOFException
	at org.eclipse.paho.client.mqttv3.internal.CommsReceiver.run(CommsReceiver.java:146)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.EOFException
	at java.io.DataInputStream.readByte(DataInputStream.java:267)
	at org.eclipse.paho.client.mqttv3.internal.wire.MqttInputStream.readMqttWireMessage(MqttInputStream.java:65)
	at org.eclipse.paho.client.mqttv3.internal.CommsReceiver.run(CommsReceiver.java:107)
	... 1 more
17/11/28 12:52:59 INFO ReceiverSupervisorImpl: Stopping receiver with message: Restarting receiver with delay 2000ms: Connection lost : Connection lost (32109) - java.io.EOFException
17/11/28 12:52:59 INFO ReceiverSupervisorImpl: Called receiver onStop
17/11/28 12:52:59 INFO ReceiverSupervisorImpl: Deregistering receiver 0
17/11/28 12:52:59 INFO ReceiverSupervisorImpl: Stopped receiver 0
17/11/28 12:53:01 INFO ReceiverSupervisorImpl: Starting receiver again
17/11/28 12:53:01 INFO ReceiverSupervisorImpl: Starting receiver 0
17/11/28 12:53:01 INFO ReceiverSupervisorImpl: Called receiver 0 onStart
17/11/28 12:53:01 INFO ReceiverSupervisorImpl: Receiver started again
17/11/28 12:53:02 INFO MemoryStore: Block input-0-1511853781800 stored as bytes in memory (estimated size 956.0 B, free 912.0 MB)
17/11/28 12:53:02 WARN RandomBlockReplicationPolicy: Expecting 1 replicas with only 0 peer/s.
17/11/28 12:53:02 WARN BlockManager: Block input-0-1511853781800 replicated to only 0 peer(s) instead of 1 peers
17/11/28 12:53:02 INFO BlockGenerator: Pushed block input-0-1511853781800
17/11/28 12:53:21 WARN ReceiverSupervisorImpl: Restarting receiver with delay 2000 ms: Connection lost 
Connection lost (32109) - java.io.EOFException
	at org.eclipse.paho.client.mqttv3.internal.CommsReceiver.run(CommsReceiver.java:146)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.EOFException
	at java.io.DataInputStream.readByte(DataInputStream.java:267)
	at org.eclipse.paho.client.mqttv3.internal.wire.MqttInputStream.readMqttWireMessage(MqttInputStream.java:65)
	at org.eclipse.paho.client.mqttv3.internal.CommsReceiver.run(CommsReceiver.java:107)
	... 1 more
17/11/28 12:53:21 INFO ReceiverSupervisorImpl: Stopping receiver with message: Restarting receiver with delay 2000ms: Connection lost : Connection lost (32109) - java.io.EOFException
17/11/28 12:53:21 INFO ReceiverSupervisorImpl: Called receiver onStop
17/11/28 12:53:21 INFO ReceiverSupervisorImpl: Deregistering receiver 0
17/11/28 12:53:21 INFO ReceiverSupervisorImpl: Stopped receiver 0
17/11/28 12:53:23 INFO ReceiverSupervisorImpl: Starting receiver again
17/11/28 12:53:23 INFO ReceiverSupervisorImpl: Starting receiver 0
17/11/28 12:53:23 INFO ReceiverSupervisorImpl: Called receiver 0 onStart
17/11/28 12:53:23 INFO ReceiverSupervisorImpl: Receiver started again
17/11/28 12:53:23 INFO MemoryStore: Block input-0-1511853803600 stored as bytes in memory (estimated size 969.0 B, free 912.0 MB)
17/11/28 12:53:23 WARN RandomBlockReplicationPolicy: Expecting 1 replicas with only 0 peer/s.
17/11/28 12:53:23 WARN BlockManager: Block input-0-1511853803600 replicated to only 0 peer(s) instead of 1 peers
17/11/28 12:53:23 INFO BlockGenerator: Pushed block input-0-1511853803600
17/11/28 12:53:52 WARN ReceiverSupervisorImpl: Restarting receiver with delay 2000 ms: Connection lost 

I am using apache bahir library for reading through MQTT stream

**Comment by venks-warrior** [comment]
Can someone update pls?

**Comment by bradleyd** [comment]
I am seeing the same issue here in 2.3.5.  On line 309 `src/emqttd_rest_api.erl`  `Broker` is `{error,nodedown}`.  Feel like this is treating the symptom more than the cause, but maybe a better match in function head here?

**Comment by bradleyd** [comment]
Now that I have been looking at it more closely. I have a strange node because in the mix.  The ip range is k8s, but nothing is exposed on that IP..strange.

**Comment by bradleyd** [comment]
I killed my local epmd and restarted.  The errors went away if because the node from earlier sessions was gone.  Hope that helps @venks-warrior

**Comment by codebeautiful** [comment]
Just I also appear this problem, is finally found my own redis server unable to join, then put the redis service after restart this information will not print, don't know your problem said this reason, hope to help you.

**Comment by MyraBaba** [comment]
Terminated for {shutdown,closed} is a real pain..

I am trying to use qmqtt from Qt thread and want to re-connect if disconnected (server restart - network problem etc). When thread try to re-connect its always get:
Terminated for {shutdown,closed}

**Comment by Gilbert-Wong** [comment]
Hi, @MyraBaba , sorry for so late reply, Could you please tell me which emqx version did you use and the how did you connect to emqx?

**Comment by MyraBaba** [comment]
quite forget the reason I changed the version emqtd 2.x to solve problem.

I am connecting with Qt official qmqtt plugin. 

is therea good reason to upgrade to emqx ?

**Comment by Gilbert-Wong** [comment]
More features, More stable , better performance :p

Gilbert Wong
On Dec 26, 2018, 4:08 PM +0800, MyraBaba <notifications@github.com>, wrote:

quite forget the reason I changed the version emqtd 2.x to solve problem.

I am connecting with Qt official qmqtt plugin.

is therea good reason to upgrade to emqx ?

**Comment by MyraBaba** [comment]
:)

İs it working with Qt qmqtt client ?


Thx

**Comment by Gilbert-Wong** [comment]
If qmqtt follow the MQTT specification, it works.

Gilbert Wong
On Dec 26, 2018, 4:17 PM +0800, MyraBaba <notifications@github.com>, wrote:
:)

İs it working with Qt qmqtt client ?


Thx
