### ISSUE TITLE
为什么不提供windows版下载

### ISSUE THREAD

**Issue by dfengpo** [emqx/emqx#13580]
### What would you like to be added or enhanced?

提供windows版下载

### Why is this needed?

提供windows版下载

**Comment by zmstone** [comment]
我们在5.4版本开始不再支持基于 Windows 的编译。
直接在Windows运行的用户很少，Windows环境中有各种奇怪的问题。
建议在windows中运行虚拟机或者docker来运行emqx

**Comment by dfengpo** [comment]
好的，感谢回复
