### ISSUE TITLE
'CONNACK Timeout' when connect emq after massive connection lose immediately.

### ISSUE THREAD

**Issue by ForLina** [emqx/emqx#1358]
#### Environment

- OS: centos 7
- Erlang/OTP: 18.3
- EMQ: 2.0.3

#### Description
'CONNACK Timeout' when connect emq after massive connection lose immediately.

*A description of the issue*
These are steps to reappear  bug:
1.Create 100k connections to EMQ server, use emqttc, run this code in erlang shell.
2.Close all erlang shell for test, so all of the connections will lose.
3.Start one connection.
And this connection got an erorr(it is from emqttc.erl ,line 522)
`[error] [Client <0.306.0>] CONNACK Timeout!`

I traced the client id use the command 
`emqttd_ctl trace client benchmark0000000000001 log/clientid_trace.log`

In the log ,we found something useful,
`17:52:03.845 [info] Client(benchmark0000000000001@10.45.147.246:8004): RECV CONNECT(Q0, R0, D0, ClientId=benchmark0000000000001, ProtoName=MQTT, ProtoVsn=4, CleanSess=true, KeepAlive=200, Username=benchmark0000000000001, Password=******)
18:03:36.153 [info] Client(benchmark0000000000001@10.45.147.246:8004): SEND CONNACK(Q0, R0, D0, AckFlags=0, RetainCode=0)
18:03:36.153 [info] Client(benchmark0000000000001@10.45.147.246:8004): Shutdown for closed`

Emq received connect at 17:52:03.845, but it return CONNACK at 18:03:36.153,  emqttc set CONNACK time as 60s, that's why I got the CONNACK Timeout!.

I wonder why EMQ return the CONNACK after 11 mins?

**Comment by emqplus** [comment]
@ForLina How about the CPU/Memory of the EMQ broker you deployed?
