### ISSUE TITLE
Disonnect hook not fired when MQTT-SN client disconnects from broker with duration not 0

### ISSUE THREAD

**Issue by pritstift** [emqx/emqx#1359]
#### Environment

- OS: Alpine 3.5
- Erlang/OTP: 19
- EMQ: 2.3.0

#### Description

When a MQTT-SN client disconnects from the broker with the `duration` flag set, the `client.disconnected` hook is only called when the client does not reconnect within the defined time frame (defined by `disconnect` flag). On the other hand if you reconnect the client within the `duration`, the `client.connected`hoock gets called.

It would be helpful if could have a hook that fires when a client goes into sleep mode. I propose that if the client disconnect with the duration flag, the `client.disconnected` hook fires with `Reason = sleep` .

**Comment by grutabow** [comment]
When client sends a DISCONNECT with duration, broker will not call 'client.disconnected' hook until the duration time elapsed, which means the client has asleep timeout. This is reasonable.

If client sends CONNECT during asleep state, 'client.connected' hook will never be called which is against your statement. This is reasonable too. 

Your proposal is very good. Maybe we should apply two hooks what called'client.sleep' and 'client.wakeup'.

**Comment by pritstift** [comment]
These hooks would be very helpful. When do you plan to support these hooks?

**Comment by pritstift** [comment]
Any news on this issue? I could also try to contribute, if you give me some info on how the hooks are implemented. 

Keep rocking!

**Comment by pritstift** [comment]
Is there any update on this issue?

**Comment by Gilbert-Wong** [comment]
Hi, @pritstift , sorry for late response, this problem has been fixed in emqx3.0-rc.3

**Comment by pritstift** [comment]
Hi @Gilbert-Wong, will try it out! Thanks very much
