### ISSUE TITLE
管理端访问 主题 带 / 的功能时报错

### ISSUE THREAD

**Issue by morain137497** [emqx/emqx#13591]
### What happened?

管理端在访问 主题带 / 的功能时，报错 404

### What did you expect to happen?

我期望帮我解决这个问题

### EMQX version

<details>

```console
$ ./bin/emqx_ctl broker
# paste output here
```

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here
```

</details>

### Log files

<details>

</details>

**Comment by qzhuyan** [comment]
Do you accidentally post the issue with such less information?

**Comment by zmstone** [comment]
I guess it's because `/` was not escaped, should percent encode it: `%2F` for `/`.
e.g. `a/b/c` should be encoded as `a%2Fb%2Fc`
