### ISSUE TITLE
emqttd_ctl admins passwd - using a pre-hashed password

### ISSUE THREAD

**Issue by trevorfurnell** [emqx/emqx#1360]
#### Environment
- OS: All
- EMQ: 

Suggested Labels = Feature
Suggested Label = Enhancement

#### Description
Using the "`emqttd_ctl admins passwd`" command currently requires a clear text password  
  ie: `emqttd_ctl admins passwd admin this-is-my-password`

When deploying a scripted install of emqtt ie: using docker, terraform, ansible or other deployment  
system it would be usful if you could use a pre-hashed value for the password instead of it being stored in your code as clear text, as in the below suggested example.
  ie: `emqttd_ctl admins passwd -h admin $1$4ZbmIjmP$WJJn8PfAbe`

_**Note:**_ In the suggested example, I've added a **-h** switch to indicate that the password is already
hashed.  "$1$4ZbmIjmP$WJJn8PfAbe"  is the hashed version of  "this-is-my-password"

#### Usage case
Our first usage case is for Docker deploys.
  1. We create a base docker image from RHEL 7.4 .
  2. We install the emqtt-latest-version.zip into the docker image
  3. In the "Docker" file we set the web interface Admin password
     (This is where we would like to use the hashed value)
  4. We deploy this docker image into our emqtt cluster
  5. All the above code ie: Docker file is stored in our corporate gitlab repo.

Our Second usage case is for updates to the running cluster
ie: we weekly change the emqtt web interface Admin password using Ansible.
The Ansible script again uses the suggested command
  `emqttd_ctl admins passwd -h admin $1$4ZbmIjmP$WJJn8PfAbe`
and changes the admin password to the new value.
Again all the Ansible scripts are stored in our gitlab repo.

We currently use the following command to create hashed passwords for other systems. 
~~~
openssl passwd -1
  Password: <I type this-is-my-new-password here>
  Verifying - Password: <I again type this-is-my-new-password here>
  $1$4ZbmIjmP$WJJn8PfAbe
Note: The above line is the hashed value of "this-is-my-new-password"
~~~

#### Benifits:
Your code does NOT contain clear text passwords.

**Comment by HJianBo** [comment]
@trevorfurnell  It is a very useful suggestion! We plan to implement the feature in 2.4-beta.1, thanks :)

**Comment by Gilbert-Wong** [comment]
We'll both support emqx_ctl options and pre-hashed password in the future.

**Comment by Gilbert-Wong** [comment]
There is something different between emqx 3.0 and emqx 2.0. In emqx 2.0, the users generated by `emqx_ctl admins` command can be used for basic auth of the rest API. However, in emqx 3.0, you have to generate app key and app id via the dashboard.

**Comment by Gilbert-Wong** [comment]
So I'm no sure if it is still necessary to implement the feature you want.

**Comment by trevorfurnell** [comment]
I'm no longer with that company, so I don't know if it's still needed.

**Comment by turtleDeng** [comment]
Thank you for your participation, we will close this issue.
