### ISSUE TITLE
Configuration in emq_auth_username.conf does not work.

### ISSUE THREAD

**Issue by yyguo1986** [emqx/emqx#1362]
#### Environment

- OS: Linux
- Erlang/OTP: 
- EMQ: 2.3.0

#### Description
I followed the lastest doc to load the emq_auth_username plugin. A new user can be added successfully by "./bin/emqttd_ctl users add" command line and it works well. But when configuring a user in etc/plugins/emq_auth_username.conf and restarting emqttd, it doesn't work(Connection Refused: bad user name or password), although this user has been showed in "./bin/emqttd_ctl users list". It seems the password does not match. 

_http://docs.emqtt.cn/zh_CN/latest/plugins.html_

_#Uncommentd one example in emq_auth_username.conf
auth.user.1.username = admin
auth.user.1.password = public_

**Comment by HJianBo** [comment]
Could you please make sure that the emq_auth_username plugin has started? 

The plugin must started first when you authorize by username & password.

**Comment by yyguo1986** [comment]
Yes, emq_auth_username plugin is running. And the user configed in its conf file has been showen in  "./bin/emqttd_ctl users list".

**Comment by HJianBo** [comment]
For more conveniently manage users!  The `./bin/emqtt_ctl users` CLIs can be work well still, though the plugin has been stoped!

I've tested it before and it works fine!

**Comment by yyguo1986** [comment]
Uploaded some screenshots for your reference to clarify.

Found some intresting things : the behavior is inconsistent between win10/emq2.3.0-rc.2 and linux/emq2.3.0.  The user configured in emq_auth_username.conf will be added to the "./bin/emqtt_ctl users" in win10/emq2.3.0-rc.2, but will not in linux/emq2.3.0. However, the same is that the user configured in emq_auth_username.conf does not work.

![linux_emq2 3 0_username_dashboard](https://user-images.githubusercontent.com/33546285/33463539-199a1fe4-d679-11e7-9381-009b500d5117.png)
![linux_emq2 3 0_username_plugin](https://user-images.githubusercontent.com/33546285/33463540-19dcac60-d679-11e7-907f-784cdbda8ec5.png)
![linux_emq2 3 0_username_verify](https://user-images.githubusercontent.com/33546285/33463541-1a137880-d679-11e7-8583-6fca57c5b964.png)
![win10_emq2 3 0 rc 2_username_dashboard](https://user-images.githubusercontent.com/33546285/33463542-1a45bd90-d679-11e7-8bbc-de25365e4718.png)
![win10_emq2 3 0 rc 2_username_plugin](https://user-images.githubusercontent.com/33546285/33463543-1a7f4b28-d679-11e7-9e40-c7c5a8cab2f9.png)
![Uploading win10_emq2.3.0.rc.2_username_verify.png…]()

**Comment by yyguo1986** [comment]
Uploaded some screenshots for your reference to clarify.

Found some intresting things : the behavior is inconsistent between win10/emq2.3.0-rc.2 and linux/emq2.3.0.  The user configured in emq_auth_username.conf will be added to the "./bin/emqtt_ctl users" in win10/emq2.3.0-rc.2, but will not in linux/emq2.3.0. However, the same is that the user configured in emq_auth_username.conf does not work.

***linux/emq2.3.0***
![linux_emq2 3 0_username_plugin](https://user-images.githubusercontent.com/33546285/33464035-648ed506-d67b-11e7-97c1-189b594ae9ba.png)
![linux_emq2 3 0_username_verify](https://user-images.githubusercontent.com/33546285/33464037-66c2fdca-d67b-11e7-8aee-96c1548ab6e1.png)

***win10/emq2.3.0-rc.2***
![win10_emq2 3 0 rc 2_username_plugin](https://user-images.githubusercontent.com/33546285/33464046-69aa2d60-d67b-11e7-9356-a554c80192bd.png)
![win10_emq2 3 0 rc 2_username_verify](https://user-images.githubusercontent.com/33546285/33464047-6b0f296c-d67b-11e7-83e7-5ca80646b83d.png)

**Comment by HJianBo** [comment]
Q1:
> The user configured in emq_auth_username.conf will be added to the "./bin/emqtt_ctl users" in win10/emq2.3.0-rc.2, but will not in linux/emq2.3.0. 

Have you restart linux/emq2.3.0 after modified `emq_auth_username.conf `? If had, could you please more detail steps for reproducing this issue?

Q2: Why the unconfigured user can login success?
1. All authentication plugins will ignore unknown users when they are authenticated. **Except for empty username or password (it will be login failed).**
2. When the `mqtt.allow_anonymous ` flag is true, EMQ will pass the login request that is ignored by all of the auth plugins

So, please check the `mqtt.allow_anonymous` flag value in the `etc/emq.conf` file.

**Others:**
When the emq_auth_plugin restart, EMQ does not override the user's password if you have added the user before. Even though has modified the user's password in the `emq_auth_username.conf `

So, I sugget you deleting all users by the `./bin/emqtt_ctl users del <Username>` CLIs tool. restart EMQ broker and try login again.

**Comment by yyguo1986** [comment]
Q1: Yes, I restarted emq in both windows and linux. 
The linux/emq2.3.0 node was in a cluster before, but I removed it from cluster(users were also deleted automatically) and then restart it, the user configured in emq_auth_username.conf file also cannot be added to the "./bin/emqttd_ctl users list". 

Q2: I want to know why the unconfigured user can login too. 
I have checked the linux/emq2.3.0, the mqtt.allow_anonymous is false.

I have followed your suggestion to delete all users by CLI, and then restart EMQ. But same issues are there.

However, it seems I found some root cause for windows/emq. If there is a new line (line break) after the last line in emq_auth_username.conf, it works. Otherwise, it doesn't. 
**Following are reproduce steps. Configured two users: a/a  and b/b**
E:\emqttd>bin\emqttd_ctl users list
E:\emqttd>bin\emqttd restart
ok
E:\emqttd>bin\emqttd_ctl users list
b
a
E:\emqttd>mosquitto_sub  -t "topic" -d -u a -P a
Client mosqsub|24060-lenovo-PC sending CONNECT
Client mosqsub|24060-lenovo-PC received CONNACK
Client mosqsub|24060-lenovo-PC sending SUBSCRIBE (Mid: 1, Topic: topic, QoS: 0)
Client mosqsub|24060-lenovo-PC received SUBACK
Subscribed (mid: 1): 0
^C
E:\emqttd>mosquitto_sub  -t "topic" -d -u b -P b
Client mosqsub|16712-lenovo-PC sending CONNECT
Client mosqsub|16712-lenovo-PC received CONNACK
Connection Refused: bad user name or password.
Client mosqsub|16712-lenovo-PC sending CONNECT
Client mosqsub|16712-lenovo-PC received CONNACK
Connection Refused: bad user name or password.
^C
E:\emqttd>bin\emqttd_ctl users del a
ok
E:\emqttd>bin\emqttd_ctl users del b
ok
E:\emqttd>bin\emqttd_ctl users list
E:\emqttd>bin\emqttd restart
ok
E:\emqttd>bin\emqttd_ctl users list
b
a
E:\emqttd>mosquitto_sub  -t "topic" -d -u a -P a
Client mosqsub|2260-lenovo-PC sending CONNECT
Client mosqsub|2260-lenovo-PC received CONNACK
Client mosqsub|2260-lenovo-PC sending SUBSCRIBE (Mid: 1, Topic: topic, QoS: 0)
Client mosqsub|2260-lenovo-PC received SUBACK
Subscribed (mid: 1): 0
^C
E:\emqttd>mosquitto_sub  -t "topic" -d -u b -P b
Client mosqsub|42788-lenovo-PC sending CONNECT
Client mosqsub|42788-lenovo-PC received CONNACK
Client mosqsub|42788-lenovo-PC sending SUBSCRIBE (Mid: 1, Topic: topic, QoS: 0)
Client mosqsub|42788-lenovo-PC received SUBACK
Subscribed (mid: 1): 0
^C
E:\emqttd>

**Comment by yyguo1986** [comment]
Is there any update on this issue?

**Comment by HJianBo** [comment]
**Q1:** Linux/2.3.0 can't load users by `emq_auth_username.conf` file
Sorry, I can't reproduce  this issue.
whether the `emq_auth_username` plugin have started after restart the linux/2.3.0 broker?

**Comment by yyguo1986** [comment]
Yes， restarted the broker and the plugin also has started. 
I can reproduce this issue on another linux/emq2.3.0 broker. The reproduce steps in my environment:
a. Leave the node from the original cluster.
b. Add a new user in emq_auth_username.conf.
c. Unload the emq_auth_username plugin.
d. Reload the emq_auth_username plugin.
e. Restart the emqttd.
f. No user in "bin/emqttd_ctl users list".

**Comment by HJianBo** [comment]
#1372

**Comment by HJianBo** [comment]
On the Windows/2.3.0, The broker can not load the last user of `emq_auth_username.conf`.
I had opened a new issue at #1372. Thanks for your contribution!

**Comment by HJianBo** [comment]
@yyguo1986 
**Q1: Linux/2.3.0 can't load users by emq_auth_username.conf file.**

I found another reason, why your configuration doesn't work:

**The server won't load new configuration files, If you restart broker by `./bin/emqttd restart` command.**

So the restart command  should be as following:
```
./bin/emqttd stop
./bin/emqttd start
```

@emqplus Is there any need to improve our design?

**Comment by yyguo1986** [comment]
Great, it works after stopping then starting emqttd. So restart command has some issue currently.

**Comment by emqplus** [comment]
@yyguo1986 @HJianBo We should support reloading the config without a reboot, I think.
