### ISSUE TITLE
chain auth methods username and http in 2.3

### ISSUE THREAD

**Issue by wiiikiii** [emqx/emqx#1363]
#### Environment

- OS: freebsd 11.1
- Erlang/OTP: 19.3.6.4,4
- EMQ: 2.3

#### Description

as in ticket before i am trying to chain auth methods. i've added a user in acl like this

acl.conf

    {allow, {user, "office@domain"}, pubsub, ["base/#"] }.

emq_auth_username.conf

    auth.user.1.username = office@domain
    auth.user.1.password = GoodPassword

i've activated the emq_auth_username then.
also i added the plugin emq_auth_http after activation auth_username.

now when i auth a user office@domain which is in acl.conf there is still a http auth request?
too check, i unloaded auth_http and auth was still working only with username in file.

my data/loaded_plugins looks like

    emq_recon.
    emq_modules.
    emq_retainer.
    emq_dashboard.
    emq_auth_username.
    emq_auth_http.

**Comment by emqplus** [comment]
@wiiikiii The authentication/ACL chain will not work if you enabled emq_auth_http plugin:)

**Comment by wiiikiii** [comment]
is there a reason for?

with the http modul i can handle much more fine graded auth checks on path
and also on dynamic usernames. 

i have some server tasks they should not depend on http auth for stability and security reason.

is it likely you'll change this behaviour?

**Comment by emqplus** [comment]
@wiiikiii Plan to fix the issue in 2.4-beta.1

**Comment by jchapuis** [comment]
Any update on this issue? also suffering from this here. Thanks!

**Comment by Lance0312** [comment]
:+11:

**Comment by jchapuis** [comment]
I have created a PR which solves this issue: https://github.com/emqtt/emq-auth-http/pull/78 
No response yet. Thanks for your support!

**Comment by emqplus** [comment]
@jchapuis Thanks. I will review the PR and merge it into develop branch.
