### ISSUE TITLE
Error bind on port 443

### ISSUE THREAD

**Issue by vaart3333** [emqx/emqx#13696]
### What happened?

I installed emqx using deb and when I bind it to port 443 it can't run. Permission error even though I installed it as root

### What did you expect to happen?

bind success on port 443

### EMQX version

<details>
sysdescr  : EMQX
version   : 5.7.2
datetime  : 2024-08-26T10:01:56.796582691+07:00
uptime    : 2 minutes, 44 seconds
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
PRETTY_NAME="Ubuntu 22.04.4 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.4 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="ht
$ uname -a
Linux hostname-ofbi 5.15.0-60-generic #66-Ubuntu SMP Fri Jan 20 14:29:49 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
```

</details>

### Log files

<details>

</details>

**Comment by id** [comment]
@vaart3333 EMQX service is started under `emqx` user, it does not permissions to bind to 443.
