### ISSUE TITLE
Add option to configure pod labels via Helm Chart

### ISSUE THREAD

**Issue by waza-ari** [emqx/emqx#13704]
### What would you like to be added or enhanced?

The Helm chart allows adding annotations to the pods created via the STS. This issue is to propose adding a similar option to add additional labels.

### Why is this needed?

Some backup software (in our case, Velero)  uses a label to select or unselect resources. We follow an opt-in approach, meaning that the Pods (and therefore the volumes attached to it) should only be backed up if the pod has a certain label. We'd therefore very much appreciate the option to add custom labels to the STS pod template.

**Comment by id** [comment]
@Rory-Z what do you think about this?

**Comment by waza-ari** [comment]
To add a little more context, its basically about this part of the template:

https://github.com/emqx/emqx/blob/master/deploy/charts/emqx/templates/StatefulSet.yaml#L45,L53

It should be relatively easy to add a `podLabels` parameter (default empty), and add it to the `labels:` section. I'm also happy to contribute a PR if you're interested.

**Comment by Rory-Z** [comment]
@waza-ari Great idea, looking for your PR
