### ISSUE TITLE
Achieving Geographic redundancy

### ISSUE THREAD

**Issue by madhushreegc** [emqx/emqx#1371]
#### Environment

- OS: CentOS
- Erlang/OTP: All
- EMQ: EMQ 2.2
- Message Persistence - REDIS 4.0.1-1
#### Description

I have two EMQ X cluster with two nodes running in two graphically different location . Let say one is primary and another is secondary . I have to achieve geo redundancy here . Data from primary location has to be replicated and stored in geographically separate secondary location . How can i achieve here?

Does EMQ supports any data replication .
1. If I go with data replication of redis which we are using for message persistence is enough?
2. Since it is cluster , every node in the cluster will store a topic trie and route table in mnesia database.  Should we have to replicate this mnesia data also?

Please comment on this. Does emq provide anything for data replication?

**Comment by emqplus** [comment]
@madhushreegc 

1. The EMQ broker usually depends on backends such as Redis, MySQL or Cassandra to replicate the MQTT messages.
2. The topic trie and routing table in memory should not be replicated to remote cluster for all the topics and routes are created by the MQTT clients connected to local cluster.

**Comment by madhushreegc** [comment]
Thank you very much for your answer . Just for my confirmation i am asking it again . 

Assuming data replication happening from primary to secondary . For some reason mqtt client which had connected to primary cluster and now connects to secondary cluster works as  it is right without any hurdles?

**Comment by emqplus** [comment]
@madhushreegc Yes. The design should ensure that clients can receive pending messages from secondary cluster.

**Comment by turtleDeng** [comment]
@madhushreegc 
The emqx-enterprise supports message persistence to the DB.
https://www.emqx.io/downloads/emq/enterprise?osType=Linux
