### ISSUE TITLE
Can not parse float data  with 13 digits after the decimal point like: 31.3338467752013 in rule sql expression

### ISSUE THREAD

**Issue by jetgeng** [emqx/emqx#13785]
### What happened?

when i use the rule function of emqx version: 5.7.2. 
my payload is :

```json
{
    "test_data": 31.333846775201351
}
```
my rule expression is:

```sql

select payload.test_data as test_data
from 'topic'
```

i get a error on top of the page

![image](https://github.com/user-attachments/assets/4febfe9a-7784-4386-9919-e90e930fffe7)

when i chage 31.333846775201351 to 31.333846775201 every thing is ok

### What did you expect to happen?

i expect get the right data.

### EMQX version

<details>

5.7.2

</details>

### OS version

<details>

```console
# On Linux:
NAME="openKylin"
FULL_NAME="openKylin"
VERSION="1.0.1 (yangtze)"
VERSION_US="1.0.1 (yangtze)"
ID=openkylin
PRETTY_NAME="openKylin 1.0.1"
VERSION_ID="1.0.1"
HOME_URL="https://www.openkylin.top/"
VERSION_CODENAME=yangtze
PRODUCT_FEATURES=3
$ uname -a
Linux dev-2 6.1.0-3-generic #4ok2-openKylin SMP PREEMPT_DYNAMIC Tue Jul 25 10:43:06 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
```

</details>

### Log files

<details>

</details>

**Comment by ysfscream** [comment]
Hi, @jetgeng! Thank you so much for your feedback. It seems that there is a bug in the dashboard. We will fix it in the next version.

**Comment by jetgeng** [comment]
you are welcome , look forward to the new version

**Comment by zmstone** [comment]
will be a part of 5.8.1
