### ISSUE TITLE
Encoding and Decoding of Emojis

### ISSUE THREAD

**Issue by sohailgerman** [emqx/emqx#1378]
#### Environment

- OS: Ubuntu 14.04 AWS EC2 Instance
- Erlang/OTP: 19.2
- EMQ: 2.3

#### Description

I am trying to encode emojis with mochiweb but it crashes on dispatch. Please help regarding this issue.

**Comment by HJianBo** [comment]
Hi, @sohailgerman Sorry reply too late.

Could you describe more details information about this crashes error? Thanks a lot!
(Because I can't reproduce it... :(

**Comment by Gilbert-Wong** [comment]
Hi, @sohailgerman , this bug has been fixed beçause we replace mochiweb with cowboy as websocket server.
