### ISSUE TITLE
All connections of emqx single point are frequently interrupted and reconnected

### ISSUE THREAD

**Issue by QQLOVE123** [emqx/emqx#13794]
### What happened?

sometimes only once every few minutes
When the disconnection was observed, the log volume was over 2000 per minute, while normally it was several hundred per minute

### What did you expect to happen?

no disconnection

### EMQX version

<details>

4.3.19

</details>

### OS version

<details>

centos7.9
</details>

### Log files

<details>

</details>

**Comment by id** [comment]
@QQLOVE123 is it possible for you to upgrade to 4.4.x or 5.x? Both EMQX 4.3 version family and CentOS 7 are "End of life".
