### ISSUE TITLE
shared_subscription_strategy: local 共享策略问题

### ISSUE THREAD

**Issue by wunengbiao** [emqx/emqx#13802]
### What happened?

EMQX 5.5.0
共享策略设置为：shared_subscription_strategy: local 
如果在A节点发布消息，在B节点无法订阅该主题
A,B节点已经在一个集群当中

### What did you expect to happen?

希望本地优先，本地没有订阅就转发到集群其他的节点的订阅者

### EMQX version

5.5.0

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here
```

</details>

### Log files

<details>

</details>

**Comment by zmstone** [comment]
> 希望本地优先，本地没有订阅就转发到集群其他的节点的订阅者

当前行为就是这样的。如果没有本地客户端，策略就退化成 random 再选一次。
请确认是否客户端真的已经下线，以及会话已经超期。

**Comment by wunengbiao** [comment]
> > 希望本地优先，本地没有订阅就转发到集群其他的节点的订阅者
> 
> 当前行为就是这样的。如果没有本地客户端，策略就退化成 random 再选一次。 请确认是否客户端真的已经下线，以及会话已经超期。

找到原因了，搭建集群的的时候，先配置 A 节点， 再配置 B节点， 在 B节点手动加入 A，
这样配置会出现，B发送的消息无法在 A 订阅，已经验证。
