### ISSUE TITLE
Http 连接器创建页面，TLS 显示是关闭，但实际 是开启的，导致为配置证书的情况下，连通性测试一直不过

### ISSUE THREAD

**Issue by yanan-wyze** [emqx/emqx#13803]
### What happened?

在论坛上发了帖子，详见以下链接：
https://askemq.com/t/topic/9417

### What did you expect to happen?

修正Http 连接器创建页面TLS ->验证服务器证书 的显示；或者在服务端校验时，保持和页面逻辑一致；

### How can we reproduce it (as minimally and precisely as possible)?

连接器 ->新建http -> 地址输入：`https://www.baidu.com`

### EMQX version

5.6.1 和 5.7.1 均由改问题

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here
```

</details>

### Log files

<details>

</details>

**Comment by zmstone** [comment]
Thank you for reporting this issue.
It has been fixed already in the development branch of 5.8.1 

这个问题在 5.8.1 开发分支中已经修复。

**Comment by zmstone** [comment]
补充一下：这个是前端默认值填充的时候用错了参数。
