### ISSUE TITLE
EMQX dashboard not have auto subscribe tab, it is different with the document https://docs.emqx.com/en/emqx/latest/messaging/mqtt-auto-subscription.html

### ISSUE THREAD

**Issue by zhongcheng0519** [emqx/emqx#13859]
### What happened?

i can not find the auto subscribe tab in EMQX dashboard

### What did you expect to happen?

find the auto subscribe tab in EMQX dashboard

### Anything else we need to know?

I installed the emqx 5.8.0 using docker.

### EMQX version

<details>

```console
$ ./bin/emqx_ctl broker
# paste output here
```
sysdescr  : EMQX
version   : 5.8.0
datetime  : 2024-09-24T07:21:09.447733033+00:00
uptime    : 1 days, 2 hours, 28 minutes, 8 seconds
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
PRETTY_NAME="Ubuntu 22.04.4 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.4 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
$ uname -a
# paste output here
```
Linux chaozhou 5.15.153.1-microsoft-standard-WSL2 #1 SMP Fri Mar 29 23:14:13 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

</details>

### Log files

<details>

</details>

**Comment by zhongcheng0519** [comment]
![image](https://github.com/user-attachments/assets/f5bb05d1-5d96-4757-bc87-0ff1c08bdfe8)
![image](https://github.com/user-attachments/assets/922b5d5d-3422-4080-a959-8f7da6a1b23b)

**Comment by id** [comment]
This feature is only available in the Enterprise edition since 5.8.0 https://docs.emqx.com/en/emqx/latest/changes/breaking-changes-ce-5.8.html.
We will update documentation to reflect that.

**Comment by tonny1983** [comment]
Hi @id 
Is the feature itself only available in the Enterprise edition or not?
If no, how it can be configurated in open source edition?

I noticed in open source version 4.x, it can be done via `module.subscription.1.topic` in `emqx.conf` according to docs.

**Comment by id** [comment]
@tonny1983 the feature is available in the open source edition, but you cannot configure it via Dashboard.

Here is an example of emqx config that you could set in `emqx.conf`:

```
auto_subscribe {
  topics = [
    {
        topic = "clientid/${clientid}/username/${username}/host/${host}"
        qos = 1
    }
  ]
}
```

**Comment by tonny1983** [comment]
@id 
Thanks a lot for your kind reply.
It works perfectly!
