### ISSUE TITLE
使用paho-mqtt连接scram授权报错

### ISSUE THREAD

**Issue by XJPeng12** [emqx/emqx#13869]
### What happened?

在emqx中的客户端认证中配置scram，然后使用paho.mqtt连接报错。
emqx设置：
![image](https://github.com/user-attachments/assets/f4ddf93f-8f3f-457c-8830-155a7aa4a4e6)
python代码：
import random
import time
import paho.mqtt.client as mqtt
import logging
logging.basicConfig(level=logging.DEBUG)
# MQTT 服务器的 IP 地址和端口号
broker = "192.168.27.200" 
port = 1883 
username = "test3" 
password = "test3" 
topic = "sensor/temperature"
# 创建 MQTT 客户端
client = mqtt.Client()

# 使用 SCRAM 进行认证
client.username_pw_set(username, password)

# 连接到 MQTT 代理
client.connect(broker, port)

# 模拟每秒发送一条温度数据
def publish_temperature_data():
    try:
        while True:
            temperature = round(random.uniform(20.0, 30.0), 2)
            message = f"{{'temperature': {temperature}}}"

            client.publish(topic, message)
            print(f"Published: {message}")

            time.sleep(2)
    except KeyboardInterrupt:
        print("Publishing stopped.")

# 启动发布温度数据
publish_temperature_data()

# 断开连接
client.disconnect()
报错截图：
![image](https://github.com/user-attachments/assets/d3eff90e-535e-403b-a6e2-6ce9f1e48e18)

emqx日志：
2024-09-25T09:22:02.275515+00:00 [warning] tag: AUTHN, clientid: MzE4NjIyNTE2MzczNTcxMjg3NjMyMjk1Nzk4MjYxMDIyNzC, msg: authentication_failure, peername: 192.168.8.123:14024, username: test3, reason: not_authorized

### What did you expect to happen?

连接上emqx

### EMQX version

emqx=5.8.0

### OS version

emqx：
使用docker
docker pull emqx/emqx:latest
python程序：
windows10,
python=3.8

### Log files

2024-09-25T09:22:02.275515+00:00 [warning] tag: AUTHN, clientid: MzE4NjIyNTE2MzczNTcxMjg3NjMyMjk1Nzk4MjYxMDIyNzC, msg: authentication_failure, peername: 192.168.8.123:14024, username: test3, reason: not_authorized

**Comment by id** [comment]
paho.mqtt python library does not support SCRAM authentication, only regular username/password.

**Comment by XJPeng12** [comment]
> Collaborator
谢谢。我测试了paho.mqtt2.1.0版本使用JWT的方式连接emqx5.8.0是可以的
