### ISSUE TITLE
EMQX 5.8.0——WebSocket接收高频消息时会乱序地收到消息

### ISSUE THREAD

**Issue by fandecheng** [emqx/emqx#13871]
### What happened?

EMQX 5.8.0有个bug，当以高频率（10Hz）发送消息时，通过WS协议去接收消息，有概率会发生乱序。影响举例：大疆上云API的DRC模式的heart_beat必须以顺序接收，但这种乱序会导致heart_beat失效，从而无法维持DRC模式，过一秒多些就会退出。这个现象在5.7.2上没有。

### What did you expect to happen?

通过WS协议接收消息时，消息的顺序正确。

### How can we reproduce it (as minimally and precisely as possible)?

以高频率（10Hz，或0.1秒一次）发送消息，在消息中加上递增的序号，通过WS协议去接收消息。观察消息的顺序。

### EMQX version

<details>

```console
$ ./bin/emqx_ctl broker
sysdescr  : EMQX
version   : 5.8.0
datetime  : 2024-09-25T19:29:25.149959684+08:00
uptime    : 3 seconds
```

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
PRETTY_NAME="Ubuntu 24.04.1 LTS"
NAME="Ubuntu"
VERSION_ID="24.04"
VERSION="24.04.1 LTS (Noble Numbat)"
VERSION_CODENAME=noble
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=noble
LOGO=ubuntu-logo
$ uname -a
Linux flydemo90 6.8.0-45-generic #45-Ubuntu SMP PREEMPT_DYNAMIC Fri Aug 30 12:02:04 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
```

</details>

### Log files

<details>

</details>

**Comment by id** [comment]
@fandecheng what QoS are you using? Have you tried to publish and subscribe with QoS 2?

**Comment by fandecheng** [comment]
> @fandecheng what QoS are you using? Have you tried to publish and subscribe with QoS 2?

Both the sending end and the receiving end were QoS 0 during my test. I haven't tried subscribing with QoS 2 yet (may try when I have time). Publishing end is not within my control.

**Comment by 101github** [comment]
The WS protocol is implemented based on TCP.TCP retransmission mechanism leads to reordering.You can try it QoS 2，but It will reduce performance

**Comment by zmstone** [comment]
> The WS protocol is implemented based on TCP.TCP retransmission mechanism leads to reordering.You can try it QoS 2，but It will reduce performance

I do not agree. TCP is reliable transport, whatever retransmission is done at TCP layer, it's a TCP layer's issue to resolve.
When data is presented to application layer, there should be no ordering issue.

**Comment by zmstone** [comment]
> @fandecheng what QoS are you using? Have you tried to publish and subscribe with QoS 2?

I don't think MQTT QoS can  or should impact message ordering.

**Comment by zmstone** [comment]
Hi @fandecheng 

You mentioned that the messages are received with webscoket client.
Could you also let us know how the messages are published? 
Help to provide below information

- QoS level (which should not matter, but good to help narrow down the investigation scope)
- If it's QoS 1/2, did you observe any publisher retries due to for example timeout receiving ACK.
- If it's QoS 1/2, does the client set a inflight window size ?
- Did publisher client reconnect during the test?
- Did subscriber client reconnect during the test?
