### ISSUE TITLE
 Can't connect to Redis server: Connection refused

### ISSUE THREAD

**Issue by yuchao-wang** [emqx/emqx#13884]
### What happened?

what ever redis or mysql , open plugin ,then error

 Can't connect to Redis server: Connection refused

 Can't connect to Mysql server: Connection refused

### What did you expect to happen?

why 

### EMQX version

latest 5.8.0

centos 7.9 docker environment 

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here
```

</details>

### Log files

<details>

</details>

**Comment by yuchao-wang** [comment]
and I operate [ping my-redis-server-host.com] is also success

**Comment by keynslug** [comment]
Hi @yuchao-wang,

I'm afraid it's impossible to tell what's going wrong because there's almost no information.

Please double-check your network configuration, firewall settings and domain name resolution are configured properly.

**Comment by yuchao-wang** [comment]
> Hi @yuchao-wang,
> 
> I'm afraid it's impossible to tell what's going wrong because there's almost no information.
> 
> Please double-check your network configuration, firewall settings and domain name resolution are configured properly.

first,my server network success, and i excluded firewall issues, no domain, just ip visit

I exec the emqx container and ping the mysql or redis server in the container,  ping is success, but when I open the auth mysql plugin or auth redis plugin ,  it is error

Is it because I'm using the free version ? i am crazy by that 

{emqx_auth_redis,{bad_return,{{emqx_auth_redis_app,start,[normal,[]]},{'EXIT',{{badmatch,{error,{shutdown,{failed_to_start_child,emqx_auth_redis,{shutdown,{failed_to_start_child,worker_sup,{shutdown,{failed_to_start_child,{worker,1},{connection_error,econnrefused}}}}}}}}},[{emqx_auth_redis_app,start,2,[{file,"emqx_auth_redis_app.erl"},{line,30}]},{application_master,start_it_old,4,[{file,"application_master.erl"},{line,277}]}]}}}}}


![iShot_2024-09-27_17 08 20](https://github.com/user-attachments/assets/5d6d63a0-166a-479a-a31d-4a629bf06d83)

**Comment by yuchao-wang** [comment]
I kown why
docker volume not work, so redis config not work yet

**Comment by keynslug** [comment]
Good to know! Feel free to reopen if you find a good evidence EMQX is buggy.
