### ISSUE TITLE
Emqtt 2.3.1 crash error during pub message with reason "no try clause matching ok in emqttd_client"

### ISSUE THREAD

**Issue by totojack** [emqx/emqx#1389]
#### Environment

- OS: docker alpine:3.5
- Erlang/OTP: default installed from emq-docker Dockerfile
- EMQ: 2.3.1

#### Description
We're trying to test the release 2.3.1 using a docker container based on Dockerfile and start.sh taken from official repo https://github.com/emqtt/emq-docker

Sending a simple message from command line 

> mosquitto_pub -t "topic/path" -m "my message" -h 127.0.0.1 -p 1883

cause a crash log into Emqtt:

> 11:48:51.226 [error] gen_server <0.1542.0> terminated with reason: no try clause matching ok in emqttd_client:'-send_fun/2-fun-2-'/4 line 142
> 11:48:51.226 [error] CRASH REPORT Process <0.1542.0> with 0 neighbours exited with reason: no try clause matching ok in emqttd_client:'-send_fun/2-fun-2-'/4 line 142 in gen_server2:terminate/3 line 1157
> 11:48:51.227 [error] Supervisor 'esockd_connection_sup - <0.1392.0>' had child connection started with emqttd_client:start_link([{max_publish_rate,0},{client_idle_timeout,30000},{client_enable_stats,false},{max_clientid_len,...},...]) at <0.1542.0> exit with reason no try clause matching ok in emqttd_client:'-send_fun/2-fun-2-'/4 line 142 in context connection_crashed

and the client fails with output

> Error: The connection was lost.

This is the complete crash log from log/crash.log file:

> =ERROR REPORT====
> Generic server <0.1537.0> terminating Last message in was {inet_async,#Port<0.1453>,153,{ok,<<16,35,0,6,77,81,73,115,100,112,3,2,0,60,0,21,109,111,115,113,112,117,98,47,50,55,57,50,55,45,115,99,105,109,109,105,97>>}}
> When Server state == {client_state,{esockd_connection,[#Port<0.1453>,#Fun<esockd_transport.2.50479399>,[]]},{{172,17,0,1},44584},running,true,undefined,65536,{none,65536},{proto_state,{{172,17,0,1},44584},#Fun<emqttd_client.0.83186262>,false,undefined,<0.1537.0>,undefined,undefined,undefined,undefined,false,undefined,undefined,1.25,1024,undefined,{proto_stats,false,0,0,0,0},undefined,undefined,undefined,undefined},undefined,false,30000,171} Reason for termination ==
> ** {{try_clause,ok},[{emqttd_client,'-send_fun/2-fun-2-',4,[{file,"src/emqttd_client.erl"},{line,142}]},{emqttd_protocol,send,2,[{file,"src/emqttd_protocol.erl"},{line,348}]},{emqttd_protocol,process,2,[{file,"src/emqttd_protocol.erl"},{line,228}]},{emqttd_client,received,2,[{file,"src/emqttd_client.erl"},{line,322}]},{gen_server2,handle_msg,2,[{file,"src/gen_server2.erl"},{line,1046}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}
>=CRASH REPORT====
> crasher:
> initial call: emqttd_client:init/1
> pid: <0.1537.0>
> registered_name: []
> exception exit: {{{try_clause,ok},[{emqttd_client,'-send_fun/2-fun-2-',4,[{file,"src/emqttd_client.erl"},{line,142}]},{emqttd_protocol,send,2,[{file,"src/emqttd_protocol.erl"},{line,348}]},{emqttd_protocol,process,2,[{file,"src/emqttd_protocol.erl"},{line,228}]},{emqttd_client,received,2,[{file,"src/emqttd_client.erl"},{line,322}]},{gen_server2,handle_msg,2,[{file,"src/gen_server2.erl"},{line,1046}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]},[{gen_server2,terminate,3,[{file,"src/gen_server2.erl"},{line,1157}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}
> ancestors: [<0.1392.0>,<0.1391.0>,esockd_sup,<0.1146.0>]
> messages: [{keepalive,start,75},emit_stats,{inet_reply,#Port<0.1453>,ok},{inet_async,#Port<0.1453>,154,{error,closed}}]
> links: [<0.1392.0>,<0.1538.0>]
> dictionary: [{rand_seed,{#{max => 288230376151711743,next => #Fun<rand.8.41921595>,type => exsplus,uniform => #Fun<rand.9.41921595>,uniform_n => #Fun<rand.10.41921595>},[272688887393991216|231698297063294985]}},{guid,{1512646667178503,130326487631361,0}}]
> trap_exit: false
> status: running
> heap_size: 987
> stack_size: 27
> reductions: 999
> neighbours:
> =SUPERVISOR REPORT====
> Supervisor: 'esockd_connection_sup - <0.1392.0>'
> Context: connection_crashed
> Reason: {{try_clause,ok},[{emqttd_client,'-send_fun/2-fun-2-',4,[{file,"src/emqttd_client.erl"},{line,142}]},{emqttd_protocol,send,2,[{file,"src/emqttd_protocol.erl"},{line,348}]},{emqttd_protocol,process,2,[{file,"src/emqttd_protocol.erl"},{line,228}]},{emqttd_client,received,2,[{file,"src/emqttd_client.erl"},{line,322}]},{gen_server2,handle_msg,2,[{file,"src/gen_server2.erl"},{line,1046}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}
> Offender: [{pid,<0.1537.0>},{name,connection},{mfargs,{emqttd_client,start_link,[[{max_publish_rate,0},{client_idle_timeout,30000},{client_enable_stats,false},{max_clientid_len,1024},{max_packet_size,65536},{keepalive_backoff,1.25}]]}}]

Emqttd uses default configuration, but I don't understand if this crash is related to an authentication problem or if .

I start the container with this command

> docker run --rm -p 1883:1883 -p 18083:18083 local/alpine-emqtt:2.3.1

and this is the first output during startup

> listener.ssl.external.acceptors=32
> node.max_ets_tables=2097152
> node.process_limit=2097152
> listener.ws.external.acceptors=16
> node.name=72763087aec1@172.17.0.2
> listener.tcp.external.max_clients=1000000
> listener.ssl.external.max_clients=500000
> node.max_ports=1048576
> listener.tcp.external.acceptors=64
> log.console=console
> listener.ws.external.max_clients=250000
> name=72763087aec1
> Node '72763087aec1@172.17.0.2' not responding to pings.
> ['2017-12-07T11:48:40Z']:waiting emqttd
> Node '72763087aec1@172.17.0.2' not responding to pings.
> Exec: /opt/emqttd/erts-8.1/bin/erlexec -noshell -noinput +Bd -boot /opt/emqttd/releases/2.3.1/emqttd -mode embedded -boot_var ERTS_LIB_DIR /opt/emqttd/erts-8.1/../lib -mnesia dir "/opt/emqttd/data/mnesia/72763087aec1@172.17.0.2" -config /opt/emqttd/data/configs/app.2017.12.07.11.48.39.config -args_file /opt/emqttd/data/configs/vm.2017.12.07.11.48.39.args -vm_args /opt/emqttd/data/configs/vm.2017.12.07.11.48.39.args -- foreground
> Root: /opt/emqttd
> starting emqttd on node '72763087aec1@172.17.0.2'
> emqttd ctl is starting...[ok]
> emqttd hook is starting...[ok]
> emqttd router is starting...[ok]
> emqttd pubsub is starting...[ok]
> emqttd stats is starting...[ok]
> emqttd metrics is starting...[ok]
> emqttd pooler is starting...[ok]
> emqttd trace is starting...[ok]
> emqttd client manager is starting...[ok]
> emqttd session manager is starting...[ok]
> emqttd session supervisor is starting...[ok]
> emqttd wsclient supervisor is starting...[ok]
> emqttd broker is starting...[ok]
> emqttd alarm is starting...[ok]
> emqttd mod supervisor is starting...[ok]
> emqttd bridge supervisor is starting...[ok]
> emqttd access control is starting...[ok]
> emqttd system monitor is starting...[ok]
> emqttd 2.3.1 is running now
> ['2017-12-07T11:48:41Z']:waiting emqttd
> ['2017-12-07T11:48:42Z']:emqttd start
> Load emq_mod_presence module successfully.
> dashboard:http listen on 0.0.0.0:18083 with 2 acceptors.
> mqtt:tcp listen on 127.0.0.1:11883 with 16 acceptors.
> mqtt:tcp listen on 0.0.0.0:1883 with 64 acceptors.
> mqtt:ws listen on 0.0.0.0:8083 with 16 acceptors.
> mqtt:ssl listen on 0.0.0.0:8883 with 32 acceptors.
> mqtt:wss listen on 0.0.0.0:8084 with 4 acceptors.
> mqtt:api listen on 0.0.0.0:8080 with 4 acceptors.

**Comment by emqplus** [comment]
@totojack Please build from the master branch. We add a `[nosuspend]` option for `esockd_transport:async_send/2` function, unfortunately the API is not compatible with EMQ 2.3.1 now.

**Comment by MarsWarrior** [comment]
After this crash, and an automatic restart of emqtt, the authorization plugin is not started or enabled, so no clients can connect anymore.

Is this related or another issue?

**Comment by lv12312** [comment]
@emqplus How to fix this bug in v2.3.1 temporary. Thank you.

**Comment by hachreak** [comment]
I can confirm the issue.
If I use `esockd v4.2` it looks working.
Please, could you pin esockd version for [stable release](https://github.com/emqtt/emqttd/blob/v2.3.1/Makefile#L11)?

**Comment by emqplus** [comment]
@hachreak The esockd v5.1 improved the `esockd_transport:asynd_send/2` function, and unfortunately the upgrade is incompatible with v4.x. 

Please clone the latest master branch if you build EMQ from source. We pined the esockd version to fix the issue:
 
```
dep_esockd       = git https://github.com/emqtt/esockd v5.1
```

**Comment by mingchuno** [comment]
@emqplus building from either master or v2.3.2 won't work. I build using `emq-relx` which I have try both `dep_emqttd        = git https://github.com/emqtt/emqttd master` and `dep_emqttd        = git https://github.com/emqtt/emqttd v2.3.2`
