### ISSUE TITLE
obtain_cert_expiry_time_failed, when access to Prometheus endpoint, "/api/v5/prometheus/stats"

### ISSUE THREAD

**Issue by KevinKao809** [emqx/emqx#13907]
### What happened?

Try to access Prometheus endpoint, the data could be retrieve without problem, but on EMQX log, below error log occur in every time.
Error Log:
`2024-10-01T05:13:53.743421+00:00 [error] msg: obtain_cert_expiry_time_failed, error: error, reason: {badmatch,{generalTime,"20741231000000Z"}}, path: <<"data/certs/listeners/ssl/default/cert-AD34787E0E1746B5">>, stacktrace: [{emqx_prometheus,cert_expiry_at_from_path,1,[{file,"emqx_prometheus.erl"},{line,899}]},{emqx_prometheus,gen_point_cert_expiry_at,3,[{file,"emqx_prometheus.erl"},{line,888}]},{emqx_prometheus,'-do_points_of_listeners/2-fun-0-',4,[{file,"emqx_prometheus.erl"},{line,879}]},{lists,foldl,3,[{file,"lists.erl"},{line,1594}]},{emqx_prometheus,'-cert_data/1-fun-0-',3,[{file,"emqx_prometheus.erl"},{line,846}]},{lists,foldl,3,[{file,"lists.erl"},{line,1594}]},{emqx_prometheus,cert_data,1,[{file,"emqx_prometheus.erl"},{line,844}]},{emqx_prometheus,fetch_cluster_consistented_data,0,[{file,"emqx_prometheus.erl"},{line,273}]},{emqx_prometheus_cluster,raw_data,2,[{file,"emqx_prometheus_cluster.erl"},{line,57}]},{emqx_prometheus,collect_mf,2,[{file,"emqx_prometheus.erl"},{line,193}]},{prometheus_collector,collect_mf,3,[{file,"prometheus_collector.erl"},{line,173}]},{prometheus_registry,'-collect/2-lc$^0/1-0-',3,[{file,"prometheus_registry.erl"},{line,86}]},{prometheus_registry,collect,2,[{file,"prometheus_registry.erl"},{line,87}]},{prometheus_text_format,format,1,[{file,"prometheus_text_format.erl"},{line,74}]},{emqx_prometheus_api,collect,2,[{file,"emqx_prometheus_api.erl"},{line,215}]},{minirest_handler,apply_callback,3,[{file,"minirest_handler.erl"},{line,152}]},{minirest_handler,handle,2,[{file,"minirest_handler.erl"},{line,56}]},{minirest_handler,init,2,[{file,"minirest_handler.erl"},{line,27}]},{cowboy_handler,execute,2,[{file,"cowboy_handler.erl"},{line,41}]},{cowboy_stream_h,execute,3,[{file,"cowboy_stream_h.erl"},{line,318}]},{cowboy_stream_h,request_process,3,[{file,"cowboy_stream_h.erl"},{line,302}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,241}]}], resolved_path: data/certs/listeners/ssl/default/cert-AD34787E0E1746B5`

### What did you expect to happen?

The certificate is for MQTT, nothing with Prometheus (HTTP), why come with such error everytime?

### EMQX version

<details>

```console
$ ./bin/emqx_ctl broker
# paste output here
```

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here
```

</details>

### Log files

<details>

</details>

**Comment by ieQu1** [comment]
Similar issue was fixed here: https://github.com/emqx/emqx/pull/13412
Please consider upgrading to v5.7.2
