### ISSUE TITLE
why run "emqttd start" twice

### ISSUE THREAD

**Issue by biansf2001** [emqx/emqx#1391]
#### Environment

- OS: win10,winserver 2008
- Erlang/OTP: 
- EMQ: 2.3.1

#### Description

I download win10 64 zip file,when I run "emqttd start" first,It has nothing.
then CTRL+C,run again,it works.

**Comment by a414338069** [comment]
My Emqtt have same question.

**Comment by michaelcplusplus** [comment]
Workaround see: https://github.com/emqtt/emqttd/issues/803

**Comment by Gilbert-Wong** [comment]
https://github.com/emqx/emqx/issues/803
