### ISSUE TITLE
ssl works but wss doesn't work with the same certificates

### ISSUE THREAD

**Issue by Qtianv587** [emqx/emqx#1393]
#### Environment

- OS: CentOS
- Erlang/OTP: R20/9.0
- EMQ: emq22

#### Description
I used ssl://url:8883 to connect the mqtt server with java client, it worked. But after I changed to wss://url:8084, it didn't work and the **error log** when I tried to connect mqtt shows as this:

```
03:12:42.624 [error] Supervisor 'esockd_connection_sup - <0.1557.0>' had child connection started with mochiweb_http:start_link({emqttd_ws,handle_request,[]}) at <0.1639.0> exit with reason {ssl_error,{options,{certfile,"etc/certs/server_cert1.pem",{error,enoent}}}} in esockd_connection:upgrade/1 line 131 in context connection_crashed
03:12:42.626 [error] Error in process <0.1639.0> on node 'emqttd@192.168.129.187' with exit value:
{{ssl_error,{options,{certfile,"etc/certs/server_cert1.pem",{error,enoent}}}},[{esockd_connection,upgrade,1,[{file,"src/esockd_connection.erl"},{line,131}]},{mochiweb_http,init,2,[{file,"src/mochiweb_http.erl"},{line,30}]}]}
```

the emq.conf about wss as this:
![2017-12-12 3 32 45](https://user-images.githubusercontent.com/18344424/33872446-e1c75898-df51-11e7-93b6-5dd6f53f579f.png)

I connect the mqtt using wss protocol in node.js by using mqtt.js. The certificates are same as what I have used in Java program with ssl. The code using js are as this:
```
var cacert = fs.readFileSync(path + "/cacert.pem");
var cert_crt = fs.readFileSync(path + "/client_crt.pem");
var cert_key = fs.readFileSync(path + "/client_key.pem");

var options = {
    'username':"username",
    'password':"client",
    'clientId':"ssss",
    'retain':false
    ,
    'protocol': "mqtt",
    'key': cert_key,
    'cert': cert_crt,
    'ca': cacert,
    'passphrase': "client",
    'rejectUnauthorized': false
};

var client = mqtt.connect(broker, options);
```
I don't know why it happened? And someone could help me to solve this?

**Comment by sqwsummerwind** [comment]
I have the same problem. Do you fixed it ??

**Comment by HJianBo** [comment]
Hi @Qtianv587 
> {{ssl_error,{options,{certfile,"etc/certs/server_cert1.pem",{error,enoent}}}}

The error `{error,enoent}` means the directory does not exist. 
So please check your configuration files and make sure the certs has exist!
