### ISSUE TITLE
PBDKF2 authentication fails for password_error

### ISSUE THREAD

**Issue by pritstift** [emqx/emqx#1394]
#### Environment

- OS: Alpine 3.5
- Erlang/OTP: 19
- EMQ: 2.3.1

#### Description

I hash password using pbkdf2 + hmac + sha256 in the format `<algorithm>$<iterations>$<salt>$<hash>` which is defacto standard from my experience. Using 36000 iterations i get something like this (password is `'password'`): `pbkdf2_sha256$36000$jVzOPOCIrf3C$gWdG9Xk/UeYrxEagMJRSJZhdEYil73D6aTZ4cz9nqtQ=`.

In the `emq_auth_pgsql.conf` i configured:
```
## Authentication Query: select password or password, salt
auth.pgsql.auth_query = select substring(password,'^(?:pbkdf2_sha256\$36000\$)(?:.+\$)(.+)$') as password, substring(password,'^(?:pbkdf2_sha256\$36000\$)(.+)(?:\$.+)$') as salt from device_deviceauth where device_id= '%u'
auth.pgsql.password_hash = pbkdf2,sha256,36000,32

## Superuser Query
#auth.pgsql.super_query = select is_superuser from mqtt_user where username = '%u' limit 1

## ACL Query. Comment this query, the acl will be disabled.
auth.pgsql.acl_query = select allow, clientid, access, topic from device_deviceacl where device_id = '%c'
```

EMQ shows up with 
```
client 123 connected, connack: 4
client 123 disconnected, reason: auth_failure
14:10:50.801 [error] Client(123@172.17.0.1:54390): Username '123' login failed for password_error
```

1. Any idea what i am doing wrong here?
2. I would prefer emq_auth_pgsql to read the desired information directly from a string like `<algorithm>$<iterations>$<salt>$<hash>`. It would be less prone to failures due to wrong plugin configuration and would allow to switch the hashing algorithm at some point in time in production.

Thanks in advance

**Comment by pritstift** [comment]
After testing a bit i found that probably the encoding of the hash plays a role. Mine is base64 encoded. But it seem to work, when the last sign does not equal `=`

**Comment by HJianBo** [comment]
Hi @pritstift 
The `hash` field of `<algorithm>$<iterations>$<salt>$<hash>` should be filled by  hex string of encrypted data

See:
https://github.com/emqtt/emqttd/blob/f452469bc565f3d1aa7ff1afab6fdfd918828582/src/emqttd_auth_mod.erl#L63-L67
