### ISSUE TITLE
Clustering does not pass retained messages, they are not published even on same server

### ISSUE THREAD

**Issue by syberkitten** [emqx/emqx#1404]
#### Environment

- OS: Ubuntu 14.04
- Erlang/OTP:  Erlang/OTP 19 [erts-8.3.5] [source] [64-bit] [smp:2:2] [async-threads:10] [hipe] [kernel-poll:false]
- EMQ: 2.3.0

#### Description

When two broker cluster is established (two instances ServerA and ServerB)

- publishing a message from client-A to Server-A as retained.
- Client-B subscribes to the same topic, and does not receive the retained message.

only client disconnect and then re-connect, the retained message is received.

It happens both if client connects to serverA or serverB.

The behavior is simply retained messages not arriving
to online subscribing clients when connected to a cluster.

Once the cluster is disconnected, everything starts to work as expected.

**Comment by HJianBo** [comment]
Hi, @syberkitten it works fine in my test, I can't reproduce this issue. Could you please provide more details information to help reproduce this? 

(i.e: Detailed steps, The topic name, etc.) 

Thanks a lot!

**Comment by syberkitten** [comment]
Hi @HJianBo ,

1. connected two brokers to one cluster using the manual method. (each broker in different geo location, BrokerUsa  and BrokerJapan 

2. Both dashboards show the cluster is connected and I can see two nodes.

3. connect Client2 to BrokerJapan (or BrokerUsa for that matter) and subscribe to topic.

4. connect Client1 to BrokerUsa and send a retained message to a topic.

5.  Client2 will not get the retained message, unless it re-connects.

6. Client1 sends a retained message again -> Client2 should receive it (step5), but it does not arrive,
only when re-connecting.

I will try reproducing again, but it is not first time I tested clustering
mode and it failed to behave as expected.

once the nodes were disconnected from cluster,
all started working as expected.

Once we are over this issue, the next test i wish to make is whether
all topics are properly updated along the cluster.

**Comment by Gilbert-Wong** [comment]
This issue should have been solved in emqx 3.0
