### ISSUE TITLE
[v5.7.0] message processed by exhook could not be retained

### ISSUE THREAD

**Issue by yummykwok** [emqx/emqx#14075]
### What happened?

A message is published with retain flag, and its payload has been modified via exhook, but the retained payload is still the old one,  not the modified one.

### What did you expect to happen?

modified payload should retained instead of the old one.

### EMQX version

<details>

```console
$ ./bin/emqx_ctl broker
# paste output here
```

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
sysdescr  : EMQX
version   : 5.7.0
datetime  : 2024-10-25T06:31:31.909193186+00:00
uptime    : 1 days, 14 hours, 57 minutes, 33 seconds

$ uname -a
Linux
```

</details>

### Log files

<details>

</details>

**Comment by yummykwok** [comment]
payload used in rule engine also seems like the one before modified

**Comment by qzhuyan** [comment]
I guess the exhook runs after the retainer hook in 'message.publish' hook chain.

maybe try republish? 
https://docs.emqx.com/en/cloud/latest/data_integration/republish.html

will be helpful if you could provide some debug logs.
