### ISSUE TITLE
Concerns About Removal of "Delayed Publish" in EMQX 5.8.0

### ISSUE THREAD

**Issue by nosovk** [emqx/emqx#14080]
### What would you like to be added or enhanced?

Dear EMQX Team,

First and foremost, thank you for your continued efforts in developing and maintaining EMQX. We have been avid users of the open-source version, finding it robust and reliable for our product needs.

However, we have noted with concern a change in the recent 5.8.0 release notes indicating the removal of the "Delayed Publish" feature from the open-source edition. This feature is crucial for our operations, and its absence poses a significant challenge for us and potentially many other users dependent on it.

In light of this, we would like to discuss a few points:

Support for Previous Versions: As our transition to the current version is obstructed by the removed functionality, we are curious if there will be ongoing support for the 5.7 branch. Specifically, will bug and security fixes be backported to ensure the stability and security of users who decide to remain on this version?
Impact on Community Trust: The removal of existing functionality can lead to trust issues within the open-source community, as current users may rely heavily on these features. While adding a paywall to new features is understandable, maintaining existing functionality in open-source versions is crucial for community stability and satisfaction. 
Future Consideration: We kindly request reconsideration regarding the removal of such features in future releases. This will help maintain the trust and reliance users have on EMQX as a leading open-source solution.
We hope you understand our concerns and look forward to your feedback on how we might secure this crucial functionality for our use case moving forward. Your response will be invaluable to us and many other users navigating similar challenges.

### Why is this needed?

Thank you once again for your dedication and support.

Addendum: [link to release notes](https://github.com/emqx/emqx/blob/ae613ed7234b655ebbc1027780d4f0f7a6ef39e3/changes/e5.8.0.en.md?plain=1#L216), [link to previous issue](https://github.com/emqx/emqx/issues/2207)

**Comment by gujun720** [comment]
@nosovk Thank for you providing the feedback. We are evaluating this post and will reply shortly.

**Comment by Kowalski0805** [comment]
Dear EMQX Team,

The removal of "Delayed Publish" in 5.8.0 is a major setback for us and likely many other open-source users. This feature isn’t just useful—it’s essential. Without it, we’re forced to consider staying indefinitely on 5.7, which raises questions about future support and security for this version.

More importantly, this change could disrupt community trust. Removing foundational features in open-source editions erodes the reliability we count on. Please reconsider this decision, or at least provide long-term support for those on 5.7, to uphold EMQX's commitment to its open-source community.

Thank you for your consideration.

**Comment by gujun720** [comment]
Hi @nosovk , @Kowalski0805 

Thank you for your affinity and concern for the EMQX project.

In the EMQX 5.8 release, we made several feature adjustments between the EMQX open-source project and the EMQX Platform (the commercial product).

We have been developing the EMQX open-source project for a decade. EMQ's vision is to build up the best MQTT platform for emerging IoT scenarios. We believe in the value of open source, and switching to a proprietary license is not an option on our list.

To ensure the sustainability of the EMQ company and the EMQX project, we need to deliver enterprise-grade features to paid customers and enhance the EMQX Platform's business value. It's challenging to differentiate the commercial version while maintaining the competence of the open-source version. We decided to adjust the features related to **advanced clustering** and **usability** in the EMQX project. We will also continuously enhance the existing enterprise **data integration** and **security** features.

Advanced clustering features include cluster linking, cluster-level durable sessions, core-replica architecture, and others. Usability features include the graphic user interface (dashboard) and observability.

The '**Delayed Publish**' feature is still in the EMQX 5.8 open-source version. You can test it by sending messages to '**$delayed/**' topics. But you can no longer configure it on the dashboard. You should configure the parameters by editing the config files. This is one of the usability adjustments. 

The 'Note' in the 'Delayed Publish' document is inaccurate as we just introduced the changes and merged the open-source docs and enterprise docs into one copy. We will improve the document in the future release.

Thanks.
Jun

**Comment by nosovk** [comment]
Thanks for clarification!
