### ISSUE TITLE
"[error] Unexpected Info" when using modified mongo plugin

### ISSUE THREAD

**Issue by jlgm** [emqx/emqx#1408]
#### Environment

- OS: MacOS High Sierra
- Erlang/OTP: 20
- EMQ: 2.3.1 (built from master branch)

#### Description

I have done a very simple modification to the [emq-auth-mongo](https://github.com/topfreegames/emq-auth-mongo) plugin in order to make it support expirable subscriptions. For that, I modified the `check_acl` function to instead of just iterating over the {pubsub} array from the first occurrence of {username} in the ACL collection, iterate over all of existing arrays – using `find` instead of `find_one` in the mongo_api call. You can check my modification in [here](https://github.com/emqtt/emq-auth-mongo/compare/2635e6d7b85b7c500b5cf81a1d97247c97dc4830...topfreegames:master#diff-bdd84d55ab81ea672c8dbba3698993d7).

To simply illustrate what's been done, in this case:

`{ "_id" : ObjectId("5a3d08de0235bce8d4cbdc48"), "pubsub" : [ "ab" ], "username" : "joao" }`
`{ "_id" : ObjectId("5a3d08de0235bce8d4cbdc49"), "pubsub" : [ "cd" ], "username" : "joao" }`
`{ "_id" : ObjectId("5a3d08de0235bce8d4cbdc4a"), "pubsub" : [ "zz" ], "username" : "joao" }`

Default mongo plugin wouldn't allow user joao to subscribe in topics "cd" and "zz", which is the feature I'm trying to create.

Now, although my modification work as intended, whenever a user subscribes to a room, being allowed or not, I get the following error:

`14:16:12.356 [error] Unexpected Info: {ack,<0.2069.0>,{error,normal}}`

I tried to debug the code in order to find what was happening, but I didn't get anywhere close. This only happens in subscribe (doesn't happen with publish) and also doesn't happen when `ignore` is returned. That leads to the conclusion that the Cursor is causing the issue – which only makes things more confusing. 

If anyone could help me understand what is happening and how impactful this might be, I would really appreciate. 

Thanks in advance!

**Comment by HJianBo** [comment]
Hi, @jlgm I has checked your plugin and reproduced the issue. 
This error log  printed by [emqtt_client.erl  L286](https://github.com/emqtt/emqttd/blob/master/src/emqttd_client.erl#L286)

The `{ack,<0.2069.0>,{error,normal}}` message will be received, when you call the `mc_cursor:rest(Cursor)` function.

**Comment by jlgm** [comment]
Hi, @HJianBo. Thank you for your reply!

I was able to identify that the Cursor was causing the issue – in fact, even if you don't use `mc_cursor:rest` but instead use `mc_cursor:close`, the same error will happen.

Do you think this is something that might crash my application or I can simply ignore it for now?

**Comment by emqplus** [comment]
@jlgm The log mean that an unexpected message sent to the MQTT `connection` process, and which is ignored. This will not crash EMQ broker. 

@HJianBo Please fix the issue in 2.4-beta.1 release, Thanks.

**Comment by terry-xiaoyu** [comment]
Close as it is probably fixed in https://github.com/emqx/mongodb-erlang v3.0.7
