### ISSUE TITLE
go 客户端中，采用3.1协议，外网ip不能连接服务端

### ISSUE THREAD

**Issue by wanyushu** [emqx/emqx#14084]
### What happened?

![image](https://github.com/user-attachments/assets/e46549de-1a19-49cc-96c9-5f8959dcc647)

### What did you expect to happen?

 MQTT连接失败: network Error : write tcp 192.168.60.134:51546->47.76.137.22:1883: wsasend: Access is denied.

### EMQX version

<details>

```console
$ ./bin/emqx_ctl broker
# paste output here
```

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here
```

</details>

### Log files

<details>

</details>

**Comment by zmstone** [comment]
报bug时，请提供 emqx 的版本信息。

调试客户端可以把 debug 级别的日志大概，一般都能发现问题。

**Comment by wanyushu** [comment]
![image](https://github.com/user-attachments/assets/94d4ef55-bf1b-4e0e-a683-2e161fc91798)
![image](https://github.com/user-attachments/assets/e7338c04-a579-4258-8403-31f1bfced88d)

**Comment by wanyushu** [comment]
![image](https://github.com/user-attachments/assets/3cbe499e-e304-4797-bec8-e2bbf1b521f1)
在同一台服务器上面通过内网可以连接成功

**Comment by wanyushu** [comment]
![image](https://github.com/user-attachments/assets/d2d8c237-6224-426f-972e-be34fa8603cd)

**Comment by zmstone** [comment]
> 在同一台服务器上面通过内网可以连接成功

这说明问题不在 EMQX。

- 可以在服务器端用 tcp dump 抓下包看下 tcp 层是不是通的。
- EMQX （请告知版本好）开启 debug 日志看下有没有收到 MQTT 报文。
