### ISSUE TITLE
ekka:autocluster:88 Autocluster exception: {badmatch,undefined}

### ISSUE THREAD

**Issue by xerosanyam** [emqx/emqx#1412]
#### Environment

- OS: ubuntu
- Erlang/OTP: 
- EMQ: 2.3.1

#### Description

Getting error in error.log @ekka:autocluster:88 Autocluster exception: {badmatch,undefined}

What to do?

**Comment by emqplus** [comment]
@xerosanyam Please check if your plugins are loaded successfully. The exception is thrown in function `emqttd_app:after_autocluster/0`:

```
after_autocluster() ->
  emqttd_plugins:init(),
  emqttd_plugins:load(),
  start_listeners().
```

**Comment by xerosanyam** [comment]
Before crashing, it also says:
```
@emqttd_plugins:stop_app:201 Plugin emq_recon is not started
@emqttd_plugins:stop_app:201 Plugin emq_modules is not started
@emqttd_plugins:stop_app:201 Plugin emq_retainer is not started
@emqttd_plugins:stop_app:201 Plugin emq_dashboard is not started
```
But I have not changed anything in any of the above-mentioned modules.
This problem started when I changed cofig in emq_auth_mongo. But I have reverted it to original one, still getting this error.

**Comment by xerosanyam** [comment]
Verified. Plugins are loading successfully. Once the emqttd crashes for any reason, it crashes again and again

**Comment by xerosanyam** [comment]
any updates on this @emqplus ?

**Comment by emqplus** [comment]
@xerosanyam The exception is confusing and any suggestion to improve? I plan the fix for the 2.4-beta.1 release.

**Comment by z14633** [comment]
I got this problem too, and I want to ask.When is the version 2.4 released？？

**Comment by Gilbert-Wong** [comment]
EMQ X 3.0.0 has been released. Welcome to try with the latest edition.
