### ISSUE TITLE
cpu负载一直波动

### ISSUE THREAD

**Issue by xiaobaxiang** [emqx/emqx#14136]
### What happened?

最近观察cpu负载(beam.smp)一直在4%到15%上下波动
![Snipaste_2024-11-04_15-42-03](https://github.com/user-attachments/assets/8c2e157d-ec60-48fe-864f-9a3a292a9a6b)
，消息流入，流出都是正常的
![image](https://github.com/user-attachments/assets/660c8122-737f-4290-8825-8a31abeda10c)

### What did you expect to happen?

cpu负载如何降低

### EMQX version

<details>

```console
$ ./bin/emqx_ctl broker
sysdescr  : EMQX
version   : 5.6.0
datetime  : 2024-11-04T15:44:41.518766473+08:00
uptime    : 13 days, 5 hours, 8 minutes, 13 seconds
```

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
NAME="Alibaba Cloud Linux"
VERSION="3 (Soaring Falcon)"
ID="alinux"
ID_LIKE="rhel fedora centos anolis"
VERSION_ID="3"
PLATFORM_ID="platform:al8"
PRETTY_NAME="Alibaba Cloud Linux 3 (Soaring Falcon)"
ANSI_COLOR="0;31"
HOME_URL="https://www.aliyun.com/"

$ uname -a
Linux 5.10.84-10.3.al8.x86_64 #1 SMP Tue Mar 8 13:35:40 CST 2022 x86_64 x86_64 x86_64 GNU/Linux
```

</details>

### Log files

<details>
|Home(H)|Network(N)|System(S)|Ets(E)/Mnesia(M)|App(A)|Doc(D)|Plugin(P)recon:proc_count(memory, 45) Interval:1500ms     | 13Days 4:17:6    |
|Erlang/OTP 26 [erts-14.2.1] [emqx] [64-bit] [smp:4:4] [ds:4:4:8] [async-threads:4] [jit:ns]                                              | 
|System     | Count/Limit           | System                    | Status                | Stat Info            | Size                     |
|Proc Count | 12977/2097152         | Version                   | 26                    | Active Task          | 1                        | 
|Port Count | 12241/1048576         | ps -o pcpu                | 12.8%                 | Context Switch       | 2998163650               |
|Atom Count | 64116/1048576         | ps -o pmem                | 5.6%                  | Reds(Total/SinceLast | 819031605178/1895050     |
|Mem Type   | Size                  | Mem Type                  | Size                  | IO/GC:(1500ms)       | Total/Increments         |
|Total      | 508.0140 MB  | 100.0% | Binary                    | 3.6887 MB    | 00.73% | IO Output            | 35.5887 GB/88.6572 KB    | 
|Process    | 266.3609 MB  | 52.43% | Code                      | 48.3710 MB   | 09.52% | IO Input             | 22.0208 GB/50.4229 KB    | 
|Atom       | 2.0673 MB    | 00.41% | Port Parallelism (+spp)   | true                  | Gc Count             | 664976771/820            | 
|Ets        | 120.8736 MB  | 23.79% | RunQueue                  | 0                     | Gc Words Reclaimed   | 1001448027803/1751641    |
|No | Pid        |     Memory   |Name or Initial Call                  |           Reductions| MsgQueue |Current Function                 |
|1  |<0.2587.0>  |    3.1740 MB |emqx_cm                               |            100713957| 0        |gen_server:loop/7                |
|2  |<0.2553.0>  |    2.2468 MB |emqx_broker_helper                    |             69629832| 0        |gen_server:loop/7                |
|3  |<0.2046.0>  |    1.5012 MB |code_server                           |              5704278| 0        |code_server:loop/1               |
|4  |<0.2613.0>  |    1.0398 MB |esockd_connection_sup:init/1          |             56145607| 0        |gen_server:loop/7                |
|5  |<0.10.0>    |  139.4063 KB |erl_prim_loader                       |              3409191| 0        |erl_prim_loader:loop/3           |
|6  |<0.6216421.0|  107.4844 KB |emqx_connection:init/4                |          24423806635| 0        |emqx_connection:recvloop/2       |
|7  |<0.4986053.0|  107.4844 KB |emqx_connection:init/4                |          64303694128| 0        |emqx_connection:recvloop/2       |
|8  |<0.5765025.0|   87.2734 KB |emqx_connection:init/4                |          33108296784| 0        |emqx_connection:recvloop/2       |
|9  |<0.2102.0>  |   86.4922 KB |release_handler                       |              1016909| 0        |gen_server:loop/7                |
|10 |<0.6948424.0|   54.5547 KB |emqx_connection:init/4                |              5866645| 0        |emqx_connection:recvloop/2       |
|11 |<0.14533.0> |   54.2422 KB |emqx_connection:init/4                |             40005703| 0        |emqx_connection:recvloop/2       |
|12 |<0.5573.0>  |   54.2422 KB |emqx_connection:init/4                |             39973245| 0        |emqx_connection:recvloop/2       |
|13 |<0.8106571.0|   54.1953 KB |emqx_connection:init/4                |                51657| 0        |emqx_connection:recvloop/2       |
|14 |<0.8098393.0|   54.1953 KB |emqx_connection:init/4                |                85077| 0        |emqx_connection:recvloop/2       |
|15 |<0.8082224.0|   54.1953 KB |emqx_connection:init/4                |               172117| 0        |emqx_connection:recvloop/2       |
|16 |<0.8055630.0|   54.1953 KB |emqx_connection:init/4                |               314834| 0        |emqx_connection:recvloop/2       |
|17 |<0.8054092.0|   54.1953 KB |emqx_connection:init/4                |               324342| 0        |emqx_connection:recvloop/2       |
|18 |<0.8045002.0|   54.1953 KB |emqx_connection:init/4                |               389199| 0        |emqx_connection:recvloop/2       |
|19 |<0.8020985.0|   54.1953 KB |emqx_connection:init/4                |               494319| 0        |emqx_connection:recvloop/2       |
|20 |<0.7977885.0|   54.1953 KB |emqx_connection:init/4                |               758738| 0        |emqx_connection:recvloop/2       |
|21 |<0.7914731.0|   54.1953 KB |emqx_connection:init/4                |              1230811| 0        |emqx_connection:recvloop/2       |
|22 |<0.7911484.0|   54.1953 KB |emqx_connection:init/4                |              1302285| 0        |emqx_connection:recvloop/2       |
|23 |<0.7789256.0|   54.1953 KB |emqx_connection:init/4                |              2040891| 0        |emqx_connection:recvloop/2       |
|24 |<0.7630674.0|   54.1953 KB |emqx_connection:init/4                |              2557184| 0        |emqx_connection:recvloop/2       |
|25 |<0.7621653.0|   54.1953 KB |emqx_connection:init/4                |              2570649| 0        |emqx_connection:recvloop/2       |
|26 |<0.7582966.0|   54.1953 KB |emqx_connection:init/4                |              2707274| 0        |emqx_connection:recvloop/2       |
|27 |<0.7573642.0|   54.1953 KB |emqx_connection:init/4                |              2748215| 0        |emqx_connection:recvloop/2       |
|28 |<0.7560821.0|   54.1953 KB |emqx_connection:init/4                |              2811192| 0        |emqx_connection:recvloop/2       |
|29 |<0.7550066.0|   54.1953 KB |emqx_connection:init/4                |              2904870| 0        |emqx_connection:recvloop/2       |
|30 |<0.7394837.0|   54.1953 KB |emqx_connection:init/4                |              3728094| 0        |emqx_connection:recvloop/2       |
|31 |<0.7332398.0|   54.1953 KB |emqx_connection:init/4                |              4204329| 0        |emqx_connection:recvloop/2       |
|32 |<0.7321164.0|   54.1953 KB |emqx_connection:init/4                |              4305862| 0        |emqx_connection:recvloop/2       |
|33 |<0.7300564.0|   54.1953 KB |emqx_connection:init/4                |              4459514| 0        |emqx_connection:recvloop/2       |
|34 |<0.7283791.0|   54.1953 KB |emqx_connection:init/4                |              4572786| 0        |emqx_connection:recvloop/2       |
|35 |<0.7251374.0|   54.1953 KB |emqx_connection:init/4                |              4802571| 0        |emqx_connection:recvloop/2       |
|36 |<0.7221921.0|   54.1953 KB |emqx_connection:init/4                |              4891867| 0        |emqx_connection:recvloop/2       |
|37 |<0.6995508.0|   54.1953 KB |emqx_connection:init/4                |              5732290| 0        |emqx_connection:recvloop/2       |
|38 |<0.6850974.0|   54.1953 KB |emqx_connection:init/4                |              6387339| 0        |emqx_connection:recvloop/2       |
|39 |<0.6826561.0|   54.1953 KB |emqx_connection:init/4                |              6536912| 0        |emqx_connection:recvloop/2       |
|40 |<0.6799939.0|   54.1953 KB |emqx_connection:init/4                |              6718621| 0        |emqx_connection:recvloop/2       |
|41 |<0.6767523.0|   54.1953 KB |emqx_connection:init/4                |              6926160| 0        |emqx_connection:recvloop/2       |
|42 |<0.6677579.0|   54.1953 KB |emqx_connection:init/4                |              7642115| 0        |emqx_connection:recvloop/2       |
|43 |<0.6660723.0|   54.1953 KB |emqx_connection:init/4                |              7794628| 0        |emqx_connection:recvloop/2       |
|44 |<0.6534008.0|   54.1953 KB |emqx_connection:init/4                |              8215602| 0        |emqx_connection:recvloop/2       |
|45 |<0.6526260.0|   54.1953 KB |emqx_connection:init/4                |              8257735| 0        |emqx_connection:recvloop/2       |
|q(quit) p(pause) r/rr(reduction) m/mm(mem)b/bb(binary mem) t/tt(total heap size) mq/mmq(msg queue) 9(proc 9 info) F/B(page forward/back) |
</details>

**Comment by id** [comment]
There are a lot of factors, internal and external, which can cause this.
Unless it's causing issues in production, I can't consider this as a bug, or something we'd want to spend time on.

**Comment by xiaobaxiang** [comment]
Is this normal?
