### ISSUE TITLE
[5.8.1] a lot of WARN log messages for websocket clients: "emqx_session_mem_unknown_message" check_gc

### ISSUE THREAD

**Issue by zmstone** [emqx/emqx#14198]
### Discussed in https://github.com/emqx/emqx/discussions/14197

<div type='discussions-op-text'>

<sup>Originally posted by **gbrehmer** November  8, 2024</sup>
We updated today from 5.0.26 to 5.8.1 (clean installation).
Now our logfile is full with new warn level messages and I can not find any error description

One example:
```
2024-11-08T21:02:49.626424+00:00 [warning] clientid: <randomclientid>, msg: emqx_session_mem_unknown_message, peername: <ip>:443, username: <username>, message: {check_gc,#{cnt  ││ => 101,oct => 6612}}
```

All messages are similar, just another client, counts...
Is there a limit raised? Should we increase a setting somewhere? How can we disable the logging when its a false positive warning?</div>

**Comment by zhongwencool** [comment]
Hi @gbrehmer, Did you encounter this issue when configuring rate limits for WebSocket connections?

**Comment by gbrehmer** [comment]
we are not using any rate limiting feature I would say.

here are all websocket and limit related settings:

```
listeners {          
  ws.default {
    max_connections = 60000
    acceptors = 4
    websocket.idle_timeout = "45s"
...
mqtt {
  max_topic_alias = 0
  max_inflight = 100
  retry_interval = "20s"
  max_awaiting_rel = 1000
  max_mqueue_len = 200000           
}
force_shutdown {
  max_message_queue_len = 100000
  max_heap_size = "500MB"
}
```

**Comment by zhongwencool** [comment]
@gbrehmer okey, I see. I think this PR will fix the warning. 

After reviewing the code again, I found that the “rate limit“ is triggered every active_n connections. The default value of active_n is 100, which explains why this behavior occurs.
<img width="877" alt="image" src="https://github.com/user-attachments/assets/9e25ac88-c6c6-485c-a25f-682dae364e16">
```
listeners {
  ws {
    default {
      tcp_options {active_n = 100}
    }
  }
}
```
Although increasing this active_n can reduce such log, it is still recommended to use version 5.8.3.
Thanks for reporting :0

**Comment by gbrehmer** [comment]
great thanks for your fast reply & actions, as usual I would say 👍
