### ISSUE TITLE
[5.8.1] dashboard stats graphs/widgets > 1 hour shows wrong values

### ISSUE THREAD

**Issue by gbrehmer** [emqx/emqx#14196]
### What happened?

We updated today and installed cluster from scratch (= no history, clean setup)
Values from "Last hour" are fine, but all other values seems to be multiplied with number of hours

<img width="456" alt="Bildschirmfoto 2024-11-08 um 21 49 28" src="https://github.com/user-attachments/assets/14f891fb-6e8d-4b25-8b8d-91367c2dc53f">

<img width="474" alt="Bildschirmfoto 2024-11-08 um 21 49 17" src="https://github.com/user-attachments/assets/e87dbdaf-9089-4103-9981-f94ebb728b7b">

### What did you expect to happen?

correct stats values for each detail level

### EMQX version

<details>

5.8.1
K8s Operator 2.2.25

</details>

### OS version

<details>

Azure AKS
K8s Operator 2.2.25

</details>

### Log files

<details>

</details>

**Comment by thehellmaker** [comment]
We also see the same issue. We recently upgraded to 5.8.1 from 5.5.0 due to another issue and we see the same issue on 5.8.1 but 5.5.0 does not have this issue.

**Comment by zmstone** [comment]
Hi @thehellmaker 
This is fixed in https://github.com/emqx/emqx/pull/14023
Will be released in 5.8.2 (release cut planed on Monday Nov.11 2024)

**Comment by zmstone** [comment]
To be more clear:
Published messages are counters, the numbers on dashboard is visualized as non-negative derivatives (i.e. delta since last sample time), so should be summed up.

Connections however were gauges, 5.8.1 has all data points summed up, and the fix in 5.8.2 will not sum up the gagues.
