### ISSUE TITLE
http auth not blocking subscriptions

### ISSUE THREAD

**Issue by jonathan-dev** [emqx/emqx#14212]
### What happened?

I set up a http endpoint that returns the following json with return code 200
``` json
{
    "result": "allow",
    "is_superuser": false,
    "acl": [
        {
            "permission": "deny",
            "action": "all",
            "topics": [
                "$SYS/#",
                "#",
                "+"
            ]
        }
    ]
}
```

### What did you expect to happen?

When I try to subscribe to `$SYS/#` I should get an access denied if I understand correctly. However I only get that when I switch the result property to `deny` which blocks all requests. Am I misunderstanding the purpose of the `acl` property or do I have some other issue

### EMQX version

v5.81

### OS version

docker hub emqx/emqx:5.8.1

**Comment by savonarola** [comment]
Hello!

I couldn't reproduce. I set up HTTP auth with this body & 200 status code.

If I try to subscribe, I have successful auth but access denied:
```
>mosquitto_sub -t '$SYS/#' -q 1 -V mqttv5
All subscription requests were denied.
```
In the logs:
```
2024-11-13T00:52:37.983757+03:00 [warning]     tag: AUTHZ
    clientid: FAv7sOeGMkdYzCb4
    msg: authorization_permission_denied
    peername: 127.0.0.1:47674
    topic: $SYS/#
    action: SUBSCRIBE(Q1)
    source: http
```

Could you:
* check that there is no other authorization (like file-based) that works for the client.
* provide the full configuration.

**Comment by jonathan-dev** [comment]
Thanks for your response :)
I have disabled the file that is in place so that shouldn't interfere.
However this changes nothing for me. I only get a `authorization_permission_denied` when I change the `"result"` property to `"deny"` other changes seem to be completely ignored if they are still valid JSON.

I was also checking out the source code to figure what I might be doing wrong. There I also noticed that in the `emqx_authz_http.erl` file only the the `"result"` property is checked. The `"acl"` property seems to be parsed in the `emqx_authn_http.erl` file which looking at the name should be only concerned with authentication  ...

That confused me a bit 

could you share the HTTP endpoint code you used?

**Comment by jonathan-dev** [comment]
> Have you set up the endpoint for authentication or authorization?

Authorization

**Comment by savonarola** [comment]
I see. The logic is the following.

The format 
```
{
    "result": "allow",
    "is_superuser": false,
    "acl": [
        {
            "permission": "deny",
            "action": "all",
            "topics": [
                "$SYS/#",
                "#",
                "+"
            ]
        }
    ]
}
```
is denoted to be used for **authentication** (**not authorization**). The success of authentication (i.e. establishing MQTT session with CONNECT packed) is defined by the `result` field. On success authentication, the `acl` records are attached to the session and used as an authorization source. So the broker may avoid doing any queries via HTTP.


Another way is to set up HTTP **authorization**. Then, the request will be made on each action: publish, subscribe (and maybe cached, depending on the settings). In this case, the server's response shouldn't include `acl` part. The request should provide some information (via placeholders), and the server, based on that information, should allow or deny the action, sending only the `result` field in the response.

**Comment by jonathan-dev** [comment]
Wow OK that makes sense. So it turns out that I configured the authorization assuming that it would use the `"acl"` property. Now I set it up in the Authentication and now it works as I expected it before. Thanks a lot for clarifying 🙏🏼
