### ISSUE TITLE
Can not start emqttd_2.3.1 as service on windows server 2012

### ISSUE THREAD

**Issue by EagleSmith** [emqx/emqx#1425]
#### Environment

- OS: windows server 2012
- Erlang/OTP: ALL
- EMQ: ALL

#### Description

error: 1067：Process terminated unexpectedly

**Comment by EagleSmith** [comment]
emqttd_2.3.1: Not enough parameters for erlang service.

**Comment by michaelcplusplus** [comment]
Seems to be the same problem as https://github.com/emqtt/emqttd/issues/871

Workaround: https://github.com/emqtt/emqttd/issues/803
