### ISSUE TITLE
使用postman或非部署服务电脑访问会http://192.168.2.1:18083/api/v5/clients 会报BAD_API_KEY_OR_SECRET

### ISSUE THREAD

**Issue by 312353457** [emqx/emqx#14250]
### What happened?

使用postman或非部署服务电脑访问会http://192.168.2.1:18083/api/v5/clients 会报BAD_API_KEY_OR_SECRET

### What did you expect to happen?

使用postman或非部署服务电脑访问会http://192.168.2.1:18083/api/v5/clients 会报BAD_API_KEY_OR_SECRET

### EMQX version

<details>

5.7.2

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here
```

</details>

### Log files

<details>

</details>

**Comment by keynslug** [comment]
Hi @312353457,

In general API access should be authenticated, so it sounds like an expected response for unauthenticated access. Please consult https://docs.emqx.com/en/emqx/latest/admin/api.html#authentication for details.

**Comment by keynslug** [comment]
I'll close this issue. Feel free to ask followup questions or reopen if you have new evidence proving that it's indeed a bug.
