### ISSUE TITLE
Snap version of EMQX is outdated

### ISSUE THREAD

**Issue by jmgiaever** [emqx/emqx#14282]
### What happened?

Snap package is at version `4.2.0`.

### What did you expect to happen?

The package to be at latest, atm `5.8.2`

### How can we reproduce it (as minimally and precisely as possible)?

`sudo snap install emqx`

### EMQX version

4.2.0

### OS version

Ubuntu. 24.04

**Comment by id** [comment]
Hi @jmgiaever.

We do not consider this as a bug. Snap installation method is not supported for newer versions. We may consider supporting it in the future, and in the meanwhile one can use official deb packages from apt repository https://docs.emqx.com/en/emqx/latest/deploy/install-ubuntu-ce.html.

**Comment by jmgiaever** [comment]
Thanks for getting back to me. 

Can I ask what makes it unsupported?

**Comment by jmgiaever** [comment]
Depends how you see it; I'm doing a lot of my infrastructure in containers, but eventually they will be migrated to Ubuntu Core. And there's no APT there. Is there anything I could participate with, in regards of the snap package?

**Comment by id** [comment]
Good point, didn't know about this use case. We'll discuss this in the team and will get back to you.

**Comment by id** [comment]
We have added this into roadmap, planning to deliver in 5.9.0.

**Comment by jmgiaever** [comment]
That's awesome news. Thank you!
