### ISSUE TITLE
/metrics ,Prometheus invalid syntax

### ISSUE THREAD

**Issue by LoonCode** [emqx/emqx#14300]
### What happened?

When sending a request to the /metrics endpoint, it returns the value of nanomq_cpu_usage as "0.32%". However, Prometheus encounters an error where it attempts to use the strconv.ParseFloat function to parse this value, but fails with the error message "strconv.ParseFloat: parsing "0.32%": invalid syntax".

### What did you expect to happen?

When sending a request to the /metrics endpoint, it returns the value of nanomq_cpu_usage as "0.32%". However, Prometheus encounters an error where it attempts to use the strconv.ParseFloat function to parse this value, but fails with the error message "strconv.ParseFloat: parsing "0.32%": invalid syntax".

### EMQX version

<details>

```console
$ ./bin/emqx_ctl broker
# 0.19
``
</details>


### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here
```

</details>

### Log files

<details>

</details>

**Comment by zhongwencool** [comment]
"nanomq_cpu_usage" suggests that you are using `nanomq`, not the EMQX MQTT broker. The repository you are referring to is not for nanomq.

**Comment by zmstone** [comment]
Thank you for the issue report, but please kindly send it to https://github.com/nanomq/nanomq
