### ISSUE TITLE
Unable to implement HA for EMQTT consumers using Apache Nifi

### ISSUE THREAD

**Issue by arnaboss** [emqx/emqx#1436]
#### Environment

- OS: CentOS 
- EMQ: 2.3.0

#### Description

I have a Apache Nifi cluster of 4 nodes, which contains a ConsumeMQTT Processor to consume MQTT messages. My EMQTT broker is setup in clusters of 2, with 3 cluster in total (6 nodes total).

The ConsumeMQTT Processor has an abstraction, where it can run in any of the 4 nodes of Nifi with the config given to the client.

Scenario 1 : Assigning one client Id (consumer-1 say), creates a problem because the same 'consumer-1' id is being used by node1, and then by node2, leading to disconnection because of same client id.

Scenario 2 : The Scenario 1 disconnection issue has been fixed by assigning the client id (consumer-1) to a random GUID on every connection and fixing the ConsumeMQTT client to run only from the Primary Node(node1) of the cluster. This solves the problem for very small time. Unfortunately , the Primary Node(node1) changes to node2, that will lead to this new node getting all the old messages already received by node 1 (node 2 makes a new clientid with random GUID). This node2 when it again changes to node3, we again get all the messages, this goes on till all the different nodes (4 nodes) have received all the messages, creating a replication of _number of nodes times_ (4 in our case).

We are using the REST API to publish the messages, as follows:

_curl -X POST \
  http://hostname/api/v2/mqtt/publish \
  -H 'authorization: Basic *********' \
  -H 'content-type: application/json' \
  -d '{
    "topic": "topic-name",
    "payload": "hello-world",
    "qos": 0,
    "retain": false,
    "client_id": "client_id"
}'_

Questions:
1. Although the retain is set to 'false' and qos set to 0, meaning the messages are not stored in 'in-flight queue'. How does the messages come back?
2. Is it possible to delete message from broker once received by the client?
3. Why doesn't the client able to kick out the old connection with the same client id and allow the new connection with the same client id to connect successfully?
4. How do I avoid replicating my data and run across multiple consumer with either same client id or changing client id?

**Comment by zhengyupan** [comment]
Hi @arnaboss ,
According your description, I have a guess that all your 4 Nifi nodes were connected to the broker at a same time, although only one of them is active (and forwarding messages to other service). This can explain your scenario 1 the nodes cannot connect of id conflict and in scenario 2 all the nifi nodes got all messages.
Please check the connection number of your broker and make sure there is only one nifi connection (as your expected) on the broker at a same time. Non-active Nifi nodes should not have a connection to broker.

**Comment by Gilbert-Wong** [comment]
@arnaboss Have your issue been resolved ?

**Comment by arnaboss** [comment]
@zhengyupan All my nifi nodes were connected to one emq broker and were all consuming together.
The desired effect was a shared topic where there would be round robin way of consumption.

@Gilbert-Wong  This issue had been solved using a shared topic. This can be closed.
