### ISSUE TITLE
Java extension hook publishes message even when creating a ValuedResponse with STOP_AND_RETURN

### ISSUE THREAD

**Issue by frank-montyne** [emqx/emqx#14374]
### What happened?

I am writing a topic rate limiter. On a topic you can specify how much time must elapse before the next message is accepted.
Therefore I override 

`public void onMessagePublish(MessagePublishRequest request, StreamObserver<ValuedResponse> responseObserver)
`

and when I want to discard the message  I execute the following code:

```
// Create a response to signal message discard
ValuedResponse response = ValuedResponse.newBuilder().setType(ValuedResponse.ResponsedType.STOP_AND_RETURN).build();

// Send the response
responseObserver.onNext(response);
responseObserver.onCompleted();

```
All subscribed clients still get the message that was going to published but should have been discarded because of the code above. 
What am I doing wrong?

### What did you expect to happen?

I expected the message not to be published

### How can we reproduce it (as minimally and precisely as possible)?

Just create a simple hook with the code above

### EMQX version

EMQX 5.7.1

### OS version

Docker using Linux

### Log files

<details>

</details>

**Comment by id** [comment]
@frank-montyne in the example it is required to create a message object, and set value of the `allow_publish` header to `false`.

https://github.com/emqx/emqx-extension-examples/blob/for-emqx-v5.0/exhook-svr-java/src/main/java/io/emqx/exhook/ExServer.java#L289

**Comment by frank-montyne** [comment]
I used the example ex hook project and implemented a simple test with discarding messages for a specific topic:

```
@Override
public void onMessagePublish(MessagePublishRequest request, StreamObserver<ValuedResponse> responseObserver) {
	DEBUG("onMessagePublish", request);

	try {
		// Add any logic here to decide if the message should be discarded.
		// For example, discard messages based on topic or payload:
		String topic = request.getMessage().getTopic();
		String payload = request.getMessage().getPayload().toStringUtf8();

		logger.info("topic: %s, payload: %s".formatted(topic, payload));

		if ("forbidden".equals(topic)) {
			logger.info("discarding message");

			// Create a response to signal message discard
			ValuedResponse response = ValuedResponse.newBuilder().setType(ValuedResponse.ResponsedType.STOP_AND_RETURN).build();

			// Send the response
			responseObserver.onNext(response);
			responseObserver.onCompleted();
		}
		else {
			logger.info("accepting message from topic: %s".formatted(topic));

			// Allow the message to pass if it doesn't meet discard criteria
			ValuedResponse response = ValuedResponse.newBuilder().setType(ValuedResponse.ResponsedType.CONTINUE).build();
			responseObserver.onNext(response);
			responseObserver.onCompleted();
		}
	}
	catch (Exception e) {
		logger.info("exception handling message: %s".formatted(e.getMessage()));

		// Handle any exception and complete the observer to avoid hanging the process
		responseObserver.onError(e);
	}
}

```
but I keep on getting the messages published on the topic "forbidden" for any subscribed client

**Comment by frank-montyne** [comment]
I also tried using ValuedResponse.ResponsedType.IGNORE but the result is the same
