### ISSUE TITLE
当没有推送权限推送时不会报错

### ISSUE THREAD

**Issue by twelve-zs** [emqx/emqx#14381]
### What happened?

账号没有该主题的推送权限，但是我进行推送时不会报错，不过不会推送成功，emqx管理页面确实能看到被拒绝了。
![屏幕截图_20241210_193044](https://github.com/user-attachments/assets/bfa85cae-e7a8-4997-9c04-41850d42e9ef)
比如test账户并没有权限推送，实际也是没有推送成功，不过不报错（如果是订阅一个没有订阅权限的主题会正常报错）。dev是admin账户，操作都正常。

### What did you expect to happen?

正常来说应该要报错才行

### EMQX version

<details>

```console
$ mqttx -v
1.11.0
https://mqttx.app/changelogs/v1.11.0

```

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
NAME="Manjaro Linux"
PRETTY_NAME="Manjaro Linux"
ID=manjaro
ID_LIKE=arch
BUILD_ID=rolling
ANSI_COLOR="32;1;24;144;200"
HOME_URL="https://manjaro.org/"
DOCUMENTATION_URL="https://wiki.manjaro.org/"
SUPPORT_URL="https://forum.manjaro.org/"
BUG_REPORT_URL="https://docs.manjaro.org/reporting-bugs/"
PRIVACY_POLICY_URL="https://manjaro.org/privacy-policy/"
LOGO=manjarolinux

$ uname -a
Linux zangsheng-pc 6.11.10-2-MANJARO #1 SMP PREEMPT_DYNAMIC Mon, 25 Nov 2024 05:29:44 +0000 x86_64 GNU/Linux

```

</details>

### Log files

<details>

</details>

**Comment by id** [comment]
@twelve-zs by default mqttx will publish with QoS 0, and this is always successful since MQTT client does not expect any response from the broker. Try to add `-q 1` parameter to your mqttx call.
