### ISSUE TITLE
Allow forward of authentication credentials to support SSO 

### ISSUE THREAD

**Issue by apocaliss92** [emqx/emqx#14383]
### What would you like to be added or enhanced?

As an Authentik (sso system) user, I would like to be able to login to the EMQX open source dashboard using my main sso credentials

### Why is this needed?

Any implementation of Basic auth or trusted proxies would be very great!

**Comment by id** [comment]
EMQX does support SSO, but only in Enterprise edition https://docs.emqx.com/en/emqx/latest/dashboard/sso.html.

**Comment by apocaliss92** [comment]
Ouch, ok got it, thanks for the hints
No way to make this working somehow in an easy mode for open source? Even remoing completely the authentication would work for easy setups

**Comment by id** [comment]
I'm afraid, no, nothing easy comes to mind.
