### ISSUE TITLE
Question: Client Connection/Session Behavior

### ISSUE THREAD

**Issue by Eric24** [emqx/emqx#1440]
In "normal mode" (i.e. no Shared Sessions) with non-clean session and QoS 1 or 2, what is the default behavior of eMQTT when a new client with the same ClientID as an existing connection? I assume the existing connection will be disconnected and the new connection will be established (assume auth, etc.)? What about non-ack'ed messages sent to the existing connection? Will they be resent to the new connection? Can you confirm this behavior?

In "Shared Session" mode, I assume that any client that connects and subscribes to the shared topic will be a candidate for receiving new messages. But what about QoS 1 or 2 messages published to this topic when no clients are connected and subscribed to it? Will they be resent when a client later connects/subscribes? Also, what about non-ack'ed messages sent to one client? Will they be resent to a different client subscribed to the same shared topic? There's very little documentation on Shared Session mode, so any details you could provide on this would be very helpful.

**Comment by Gilbert-Wong** [comment]
Hi, @Eric24 ,Sorry for late reply. I do not understand the meaning of the `shared session`, what is it meaning? Does it mean that you set clean session as false when your mqtt client connected to emqx broker?

**Comment by Eric24** [comment]
By "shared session", I'm referring to "shared subscriptions": http://emqtt.io/docs/v2/advanced.html#shared-subscription

**Comment by Gilbert-Wong** [comment]
The `shared-subscription` has nothing with session. You can refer the definition of `shared-subscription` in mqtt 5 specification.

**Comment by Eric24** [comment]
To be clear, the use of the term "session" was my mistake. I'm only referring to "shared subscriptions". Given that, my original question should have been phrased like this (below):

In "normal mode" (i.e. not a shared-subscription) with non-clean session and QoS 1 or 2, what is the default behavior of eMQTT when a new client with the same ClientID as an existing connection? I assume the existing connection will be disconnected and the new connection will be established (assume auth, etc.)? What about non-ack'ed messages sent to the existing connection? Will they be resent to the new connection? Can you confirm this behavior?

In "shared-subscription" mode, I assume that any client that connects and subscribes to the shared topic will be a candidate for receiving new messages. But what about QoS 1 or 2 messages published to this topic when no clients are connected and subscribed to it? Will they be resent when a client later connects/subscribes? Also, what about non-ack'ed messages sent to one client? Will they be resent to a different client subscribed to the same shared topic? There's very little documentation on shared-subscription mode, so any details you could provide on this would be very helpful.

**Comment by Gilbert-Wong** [comment]
1. First Question, your assumption is right, the existing connection will be disconnected and the new connection will be established. If clean-session you set for your connection is false, the non-ack'ed message would sent to the session of the existed connection, and then the new connection with the same clientid built, it would resent to this new connection. You could try with emqx and emqx-dashboard by yourself.

2. Second Question, it is the same answer, it depends on the connection flag `clean session`.

**Comment by Eric24** [comment]
Thanks!
