### ISSUE TITLE
用的服务器是EMQ公司的mqtts服务器，有一个c语言开发的开发板连不上mqtts，怎么看mqtts的日志，想看一下为什么拒绝连接

### ISSUE THREAD

**Issue by esterllaf** [emqx/emqx#14416]
### What happened?

用的服务器是EMQ公司的mqtts服务器，有一个c语言开发的开发板连不上mqtts，怎么看mqtts的日志，想看一下为什么拒绝连接

### What did you expect to happen?

用的服务器是EMQ公司的mqtts服务器，有一个c语言开发的开发板连不上mqtts，怎么看mqtts的日志，想看一下为什么拒绝连接

### EMQX version

<details>

```console
$ ./bin/emqx_ctl broker
# paste output here
```

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here
```

</details>

### Log files

<details>

</details>

**Comment by zmstone** [comment]
麻烦提供一下更详细的信息。
连接的 emqx 服务器是哪个？本地跑的？运行在哪里？
