### ISSUE TITLE
Out of memory crash

### ISSUE THREAD

**Issue by frank-montyne** [emqx/emqx#1444]
#### Environment

- OS: Ubuntu Linux 14.04
- Erlang/OTP: 20
- EMQ: 2.3.0

#### Description
We are experiencing the same issue approximately every day. At some point in time the MQTT server memory starts going up (after having consumed an average of  about 60 MB for hours in a row). Messages are not sent any more to the subscriber. Then after some time more than 500 MB is consumed and an out of memory is triggered. I have no idea why this is happening. I attached the crash.dump and the log file. Can someone have a look to see if there is anything suspicious going on? We have multiple publishers (about 10) over SSL and one subscriber that processes all incoming messages. On average we have about 5 messages ov 150 bytes per second coming in.

Thanks,
Frank
[crash.zip](https://github.com/emqtt/emqttd/files/1611077/crash.zip)

**Comment by miks** [comment]
We are experiencing same behaviour. See #1070.
