### ISSUE TITLE
how do i network traffic control ??

### ISSUE THREAD

**Issue by 22factor** [emqx/emqx#1449]
#### Environment

- OS:  centos 7.4
- Erlang/OTP:  
- EMQ: 2.3.3

#### Description

There are emqtt listener questions.
One topic has multiple subscriptions attached to it
IDC traffic bandwidth issue occurs when payload capacity grows when publishing.
Is there a way to do this?
The "listener.tcp.external.rate_limit" option has no effect on testing.

I want to limit pub to % of interface bandwidth so that it does not affect the entire network.
Please help me

**Comment by Gilbert-Wong** [comment]
This feature has been implemented in latest emqx. Please download it and try with it.
