### ISSUE TITLE
Websocket performance

### ISSUE THREAD

**Issue by mademi** [emqx/emqx#1450]
#### Environment

- OS: Ubuntu 16.04
- Erlang/OTP:  xxx
- EMQ: 2.3.3

#### Description

We are using EMQ to send large packets (20k-30k bytes) very frequently from a single publisher, published within the same topic. Furthermore, these packets are received under the same topic by a single subscriber but we are having some issues with the performance of EMQ over WebSockets. 

We see that the transferring the same packets over TCP is almost half the time it takes to transmit the same packets over WebSockets. Do you have any guidelines or tips on where we can look to improve the performance? Or is it a limitation of EMQ WebSockets implementation? 

We notice that other brokers (eg: RabbitMQ) generate closer results for TCP vs WebSockets, with at most 5% difference but on EMQ the impact seems significantly larger for WebSockets.

Any help?

**Comment by ertanden** [comment]
To add more info, using the benchmark tool from https://github.com/hareeqi/mqtt-benchmark here are my results (not exactly scientific but still reproduces the problem experienced):

EMQ WS:
```
$ ./bin/mqtt-benchmark --broker=ws://emq-broker:8000/mqtt --size=25000 --clients=1 --count=1000

Trying to conenct to 1 clients ...
Conencted to 1 sucessfully

        Average result for each client of the 1 clients.

        Establishing connection (sec):   0.239
        Success in publishing (msg):     1000/1000
        Failure in publishing (msg):     0/1000
        Duraion in publishing (sec):     36.588
        Throughput (msg/sec):            27.3314
```
EMQ TCP: 
```
$ ./bin/mqtt-benchmark --broker=tcp://emq-broker:1883 --size=25000 --clients=1 --count=1000

Trying to conenct to 1 clients ...
Conencted to 1 sucessfully

        Average result for each client of the 1 clients.

        Establishing connection (sec):   0.162
        Success in publishing (msg):     1000/1000
        Failure in publishing (msg):     0/1000
        Duraion in publishing (sec):     17.468
        Throughput (msg/sec):            57.2475
```
RabbitMQ WS
```
$ ./bin/mqtt-benchmark --broker=ws://rabbitmq:28000/ws --size=25000 --clients=1 --count=1000

Trying to conenct to 1 clients ...
Conencted to 1 sucessfully

        Average result for each client of the 1 clients.

        Establishing connection (sec):   0.295
        Success in publishing (msg):     1000/1000
        Failure in publishing (msg):     0/1000
        Duraion in publishing (sec):     16.829
        Throughput (msg/sec):            59.4212
```
RabbitMQ TCP
```
$ ./bin/mqtt-benchmark --broker=tcp://rabbitmq:21883 --size=25000 --clients=1 --count=1000

Trying to conenct to 1 clients ...
Conencted to 1 sucessfully

        Average result for each client of the 1 clients.

        Establishing connection (sec):   0.128
        Success in publishing (msg):     1000/1000
        Failure in publishing (msg):     0/1000
        Duraion in publishing (sec):     16.811
        Throughput (msg/sec):            59.4849
```

**Comment by emqplus** [comment]
@ertanden Thanks for the benchmark report. @huangdan Please benchmark WS connections of EMQ with tool: https://github.com/hareeqi/mqtt-benchmark

**Comment by swinterberger** [comment]
This seems to be an issue with Mochiweb websocket implementation, which emqtt is leveraging.  That project is pretty much dead and is generally low performance due to having to maintain legacy support.

RabbitMQ (and VerneMQ) use cowboy websocket implementation which far more feature rich and much more performant.

**Comment by Eric24** [comment]
Is there any plan to move eMQTT to using Cowboy?

**Comment by gihad** [comment]
Are there reports of anyone using emqtt to achieve throughput levels of 1million msg/sec, 2million msg/sec, 5million msg/sec? This is considering 1 million, 2million or 5million subscribers.

**Comment by Gilbert-Wong** [comment]
We have migrate mochiweb to cowboy as websocket server. MQTT is lightweight protocol, it must cost less resources than websockt. We recommend you to connect to emqx via tcp not websocket. EMQX 3.0.0 has been released, please have a try with latest emqx.

**Comment by JaosnHsieh** [comment]
i run into same issue that `websocket` performance is much worse than `mqtt`   with `emqx 4.2.0` on my macos.

emqx 4.2.0 single instance and all default config with only extra `emqx-auth-username` plugin loaded.

benchmark by [mqtt-stresser](https://github.com/inovex/mqtt-stresser)


<details>
  <summary>mqtt protocol result</summary>
  
```
$ ./mqtt-stresser-darwin-amd64  -broker tcp://192.168.1.110:1883/ -num-clients 100 -num-messages 100  -rampup-delay 1s -rampup-size

# Configuration
Concurrent Clients: 100
Messages / Client:  10000

# Results
Published Messages: 10000 (100%)
Received Messages:  10000 (100%)
Completed:          100 (100%)
Errors:             0 (0%)

# Publishing Throughput
Fastest: 61269 msg/sec
Slowest: 15918 msg/sec
Median: 34353 msg/sec

  < 20453 msg/sec  9%
  < 24988 msg/sec  17%
  < 29523 msg/sec  31%
  < 34058 msg/sec  47%
  < 38593 msg/sec  66%
  < 43129 msg/sec  82%
  < 47664 msg/sec  89%
  < 52199 msg/sec  95%
  < 56734 msg/sec  96%
  < 61269 msg/sec  99%
  < 65804 msg/sec  100%

# Receiving Througput
Fastest: 104 msg/sec
Slowest: 18 msg/sec
Median: 41 msg/sec

  < 27 msg/sec  33%
  < 35 msg/sec  42%
  < 44 msg/sec  52%
  < 70 msg/sec  60%
  < 78 msg/sec  70%
  < 87 msg/sec  90%
  < 95 msg/sec  96%
  < 104 msg/sec  99%
  < 112 msg/sec  100%

```

</details>





<details>

<summary>websocket result </summary>


```
./mqtt-stresser-darwin-amd64  -broker ws://192.168.1.110:8083/ -num-clients 100 -num-messages 100  -rampup-delay 1s -rampup-size 1
0 -global-timeout 30s -timeout 20s -username admin -password public
10 worker started - waiting 1s
20 worker started - waiting 1s
30 worker started - waiting 1s
40 worker started - waiting 1s
50 worker started - waiting 1s
60 worker started - waiting 1s
70 worker started - waiting 1s
80 worker started - waiting 1s
90 worker started - waiting 1s
100 worker started
failed to unsubscribe: Not Connected
failed to unsubscribe: Not Connected
failed to unsubscribe: Not Connected
EEfailed to unsubscribe: Not Connected
Efailed to unsubscribe: Not Connected
EEEEEfailed to unsubscribe: Not Connected
failed to unsubscribe: Not Connected
failed to unsubscribe: Not Connected
failed to unsubscribe: Not Connected
failed to unsubscribe: Not Connected
EEETest timeout. Wait 5s to allow disconnection of clients.

# Configuration
Concurrent Clients: 100
Messages / Client:  10000

# Results
Published Messages: 6800 (68%)
Received Messages:  1766 (26%)
Completed:          0 (0%)
Errors:             11 (11%)
- ConnectFailed:      0 (0%)
- SubscribeFailed:    10 (91%)
- TimeoutExceeded:    1 (9%)
- Aborted:            67 (67%)

# Publishing Throughput
Fastest: 62473 msg/sec
Slowest: 17713 msg/sec
Median: 25810 msg/sec

  < 22189 msg/sec  16%
  < 26665 msg/sec  52%
  < 31141 msg/sec  66%
  < 35617 msg/sec  76%
  < 40093 msg/sec  84%
  < 44569 msg/sec  94%
  < 49045 msg/sec  99%
  < 66949 msg/sec  100%

# Receiving Througput
Fastest: 203 msg/sec
Slowest: 1 msg/sec
Median: 4 msg/sec

  < 21 msg/sec  79%
  < 41 msg/sec  91%
  < 61 msg/sec  93%
  < 81 msg/sec  96%
  < 122 msg/sec  97%
  < 142 msg/sec  99%
  < 203 msg/sec  100%

```

</details>

**Comment by id** [comment]
@HJianBo still relevant?

**Comment by HJianBo** [comment]
Yes, perhaps we need a conclusion from a performance test first.

As far as I know, WebSocket may have performance issues because it is based on different underlying socket libraries (Cowboy and Ranch). Therefore, we need to test it to understand the actual situation.  :thinking:
