### ISSUE TITLE
Getting more than one retained message

### ISSUE THREAD

**Issue by syberkitten** [emqx/emqx#1457]
#### Environment

- OS: Ubuntu 14.04
- Erlang/OTP: Erlang/OTP 19 [erts-8.3.5] [source] [64-bit] [smp:2:2] [async-threads:10] [hipe] -
- [kernel-poll:false]
- EMQ: 2.3.0

#### Description

There are many cases where client gets more then one retained message (for one topic)

if let's say client A writes more then one retained message, 
within a small time frame (lets say 1 second)

The receiving client (B) will get multiple retained messages instead
of only one.

if client B is subscribed with cleanSession = false and is not connected,
when it does connect, it will get multiple retained messages.

**Comment by emqplus** [comment]
@syberkitten The behavior of retained message should be the same to normal PubSub messages if the consumer client is online or `cleanSession` flag is false. 

According to the MQTT v3.1.1 specification, the broker should ensure only one retained message for a new subscription.

**Comment by chriswue** [comment]
I think that this is as per MQTT spec and mosquitto behaves the same (last time I check at least). This guy has a pretty good overview of the retain behaviour: http://www.steves-internet-guide.com/mqtt-retained-messages-example/
Effectively if you have a persistent subscription with QoS 1 then all message with QoS >= 1 get queued up whether they are flagged RETAIN or not doesn't matter.

**Comment by syberkitten** [comment]
@chriswue As far as i understood the QoS 1 / 0 /2 
are all contracts between broker and a client,
thus it ensures broker and client agree that
messages have been arrived on the application level (not only the TCP level)

there should be no stacking up of messages
and there should be only one retained message period.

what happens is that we get 10 retained messages
after the other because client published them with Qos2
so instead of getting the last 'state' we get 10 states
which ruins the whole idea of one retained message.

I think we should stick to 
simple and easy use cases without side effects.

There is no reason that QoS > 0 should stack up messages,
if subscribers are not connected, they are going to miss these 
messages unless a message is retained.

let's keep it simple stupid?  :)

**Comment by syberkitten** [comment]
I've made a few tests with EMQ 2.3.1, here is what i found:

- Client B Subscribes to topic "AAAA" with clean: false (Qos 0)
- Client B disconnects.
- Client A publishes 3 messages with Qos (0 or 1 or 2) to topic "AAAA" 

- Client B re-Connects, and receives 3 messages.

If client A publishes all the 3 messages as retained, all of them will be received
with a retain flag: true.

So there are 2 discrepancies:
1. messages should not be kept for Client B (except retained)
2. There should be always only one retained messages, not multiple

It's very easy to reproduce.

**Comment by chriswue** [comment]
@syberkitten 

Regarding:

> There is no reason that QoS > 0 should stack up messages,
if subscribers are not connected, they are going to miss these
messages unless a message is retained.

This is obviously incorrect - that's precisely what persistent subscriptions (Clean Session = False) are for.

If you create a persistent subscription then QoS > 0 means the broker must queue up the messages (unless it runs into practical limitation such as running out of storage). For QoS = 0 such a guarantee doesn't exist but it doesn't mean "the broker MUST discard those messages". MQTT doesn't specify what has to happen in that case and as such it's implementation defined. QoS level 0 doesn't "guarantee" message dropping, it just means for the broker it doesn't need to go the extra mile - but obviously it can if it wants to.
emqtt has a queue_qos0 setting (https://github.com/emqtt/emqttd/wiki/Configuration) which seems to default to true so the behaviour you're seeing is completely expected.

If your requirement is that when you newly connect to the broker and subscribe to a topic with a retained message you only ever want the retained message delivered then you need to make that connection with Clean Session = True, this makes the server discard any existing state (including any queued messages in case that client was previously subscribed to the same topic with a Clean Session = False connection) and you only get the retained message delivered.
That's the only "portable" way between MQTT brokers. You may have to keep two client connections around in case you need Clean Session = False for other topics (where you want queuing in case the client disconnects temporarily)

Now with emqtt you could probably set queue_qos0 = False and retry your experiment and it might get you what you want (I'm just not sure if that setting relates to the publisher or the subscriber QoS level)

**Comment by syberkitten** [comment]
Hello @chriswue 

Thanks for clarifying some of the forest up.

It sounds like you made a turn to make MQTT into a more classic message Queue
which somehow sounds to be a bit of an anti-pattern for MQTT Broker.

I've tried using queue_qos0 = False, it results in the fact that no message is retained
not even Qos1 / Qos 1 / Qos 3

test with store_qos0 = False:
- restart broker (after changing to store_qos0 = false)
- client A subscribe to topic with clean: false
- client A disconnect
- client B connect send retained message to topic
- client A - reconnects , no retained arrived.


And I really don't want to connect two mqtt clients.

what we do need is simply get the last retained message
with no other messages arriving.

**Comment by chriswue** [comment]
Hm, not entirely sure how you arrive at this conclusion:

> It sounds like you made a turn to make MQTT into a more classic message Queue
which somehow sounds to be a bit of an anti-pattern for MQTT Broker.

As per [MQTT Spec section 3.1.2.4](http://docs.oasis-open.org/mqtt/mqtt/v3.1.1/os/mqtt-v3.1.1-os.html)

> If CleanSession is set to 0, the Server MUST resume communications with the Client based on state from the current Session (as identified by the Client identifier). If there is no Session associated with the Client identifier the Server MUST create a new Session. The Client and Server MUST store the Session after the Client and Server are disconnected [MQTT-3.1.2-4]. After the disconnection of a Session that had CleanSession set to 0, the Server MUST store further QoS 1 and QoS 2 messages that match any subscriptions that the client had at the time of disconnection as part of the Session state [MQTT-3.1.2-5]. It MAY also store QoS 0 messages that meet the same criteria.

> If CleanSession is set to 1, the Client and Server MUST discard any previous Session and start a new one. This Session lasts as long as the Network Connection. State data associated with this Session MUST NOT be reused in any subsequent Session [MQTT-3.1.2-6].


> The Session state in the Client consists of:
·         QoS 1 and QoS 2 messages which have been sent to the Server, but have not been completely acknowledged.
·         QoS 2 messages which have been received from the Server, but have not been completely acknowledged. 

> The Session state in the Server consists of:
·         The existence of a Session, even if the rest of the Session state is empty.
·         The Client’s subscriptions.
·         QoS 1 and QoS 2 messages which have been sent to the Client, but have not been completely acknowledged.
·         QoS 1 and QoS 2 messages pending transmission to the Client.
·         QoS 2 messages which have been received from the Client, but have not been completely acknowledged.
·         Optionally, QoS 0 messages pending transmission to the Client. 

So queuing up messages (or persisting them in some form) for at least QoS > 0 is what's required to conform to the MQTT spec. In how far is this an MQTT broker antipattern?

Regarding the retained behaviour, sound like a bug, but I've tried reproduce this with a 2.3.3 instance (queue_qos0 = false) and it's working fine for me (using the mosquitto command line tools):

First create persistent subscription and using `mosquitto_pub -h localhost -q 1 -m "hello" -t "/test"` on a different console to publish the "hello" message after client is subscribed:

    mosquitto_sub -h localhost -q 1 -C 1 -t "/test" -d -v -c -i "myclient"
    Client myclient sending CONNECT
    Client myclient received CONNACK
    Client myclient sending SUBSCRIBE (Mid: 1, Topic: /test, QoS: 1)
    Client myclient received SUBACK
    Subscribed (mid: 1): 1
    Client myclient received PUBLISH (d0, q1, r0, m1, '/test', ... (5 bytes))
    Client myclient sending PUBACK (Mid: 1)
    /test hello
    Client myclient sending DISCONNECT

Then publish a retained message:

    mosquitto_pub -h localhost -q 1 -m "hello retained" -t "/test" -r

Then reconnect:

    mosquitto_sub -h localhost -q 1 -C 1 -t "/test" -d -v -c -i "myclient"
    Client myclient sending CONNECT
    Client myclient received CONNACK
    Client myclient sending SUBSCRIBE (Mid: 1, Topic: /test, QoS: 1)
    Client myclient received SUBACK
    Subscribed (mid: 1): 1
    Client myclient received PUBLISH (d0, q1, r0, m2, '/test', ... (14 bytes))
    Client myclient sending PUBACK (Mid: 2)
    /test hello retained
    Client myclient sending DISCONNECT

This is both pub/sub with qos 1. Retain keeps working with QoS 0 as well:

    mosquitto_pub -h localhost -q 0 -m "hello retained q0" -t "/test0" -r

    mosquitto_sub -h localhost -q 0 -C 1 -t "/test0" -d -v -c -i "myclient"
    Client myclient sending CONNECT
    Client myclient received CONNACK
    Client myclient sending SUBSCRIBE (Mid: 1, Topic: /test0, QoS: 0)
    Client myclient received SUBACK
    Subscribed (mid: 1): 0
    Client myclient received PUBLISH (d0, q0, r0, m0, '/test0', ... (17 bytes))
    /test0 hello retained q0
    Client myclient sending DISCONNECT

For normal messages (no retain flag) the messages get queued up only if both pub/sub are QoS > 0 (with store_qos0 = false)

**Comment by syberkitten** [comment]
@chriswue I guess we have been using MQTT broker in way which is pertaining to somewhat a different pattern, mostly all other brokers never saved QoS 0 messages out of the box.

on my Mac OSX running: 2.3.4
I'm unable to get retained messages when setting, store_qos0 
will test on version 2.4.1 - which is the one we'll use in production anyway.

**Comment by syberkitten** [comment]
When I'm testing broker nothing of the above seems stable,
sometimes i get only one retained message, sometimes i get none.

@chriswue  Are you running tests to cover all the different scenarios?
