### ISSUE TITLE
message loss during node 1 is down in a emqtt 2.x cluster 

### ISSUE THREAD

**Issue by ajeshpg** [emqx/emqx#1462]
#### Environment

- OS: Red Hat Enterprise Linux Server
- Erlang/OTP: 
- EMQ: 2.1.2

#### Description

I have a two node emqtt cluster behind an AWS ELB.
A java client subscriber (subscriber-1) with client Id (clientId-1) is connected to node-1 with cleanSession = False. After some time node-1 got stopped ( node-2 is still up and running). After I restart node-1 ,  I expect all the messages which are already published to the topic to be subscribed by subscriber 1. But it does not happened. I lost the messages published during the time period node-1 was down.

**Comment by msdevanms** [comment]
I just wondered by viewing this issue. It is supposed to be a feature of clustered emqtt, is n't it ?
Is it something we can achieve using some configuration changes ?

**Comment by toto1310** [comment]
I lost messages on my environment (not AWS ELB but emqtt 2.x cluster) too.

I published and subscribed messages with QoS1 and I expected that messages will be resent and duplicated, but I found that messages were lost and not duplicated.

Do you know Why so?  Please help me.

### Environment

- Server x3
- CentOS7
- EMQ 2.3.12 and clustered
- mqueue.length=0 (others are default value)

### Description

#### publisher

- paho Python Client
- QoS1
- 100 messages/seconds
- published to node-1

#### subscriber

- paho Java Client
- QoS1
- clear_session=false
- subscribed from node-2

#### My Operations

I stopped node-2 during publishing and subscribing messages as below.

```
$ sudo sytemctl stop emqttd
```

 
### Result

#### publisher

Succeed to publish messages without any errors.

#### subscriber

When node-2 was down, reconnected to another node.
But messages were lost.
On the other hand, some messages published during node-2 down were not lost.

If subscribed messages with QoS2, messages were not lost.

**Comment by turtleDeng** [comment]
@ajeshpg @msdevanms 

The emqx-enterprise supports message persistence to the DB to ensure that messages are not lost.
https://www.emqx.io/downloads/emq/enterprise?osType=Linux
