### ISSUE TITLE
About sharing subscriptions

### ISSUE THREAD

**Issue by promission** [emqx/emqx#1467]
#### Environment

- OS: Red Hat 4.4.7-16
- Erlang/OTP: 
- EMQ: 2.2

#### Description

If there are A, B, C three subscribers, the use of shared subscription. So how to achieve the publisher P on the line after sending multiple messages have been received by one subscription?
like this：
P online ->A
P->message1->A
P->message2->A
P->message3->A

Q online ->B
Q ->message1->B
Q ->message2->B
Q ->message3->B

W online ->A
W ->message1->A
W ->message2->A
W ->message3->A
E.g：Can share subscriptions based on clientid?

**Comment by emqplus** [comment]
@promission Good idea:) Plan to support this feature in 2.4-beta.1
