### ISSUE TITLE
QoS 2 message and broker restart

### ISSUE THREAD

**Issue by michaelcplusplus** [emqx/emqx#1481]
#### Environment

- OS:  Windows 10
- Erlang/OTP: R19/8.3
- EMQ: EMQ: 2.2

#### Description

Is there a possibiltity to persist not delivered QoS 2 messages.
In my testcase the not delivered QoS 2 messages are lost after a broker restart.

**Comment by zhengyupan** [comment]
Hi @michaelcplusplus ,
the persistence of QoS messages is supported by the EMQ X Enterprise Edition.
