### ISSUE TITLE
Shared Subscription - Persistent routing

### ISSUE THREAD

**Issue by sm2017** [emqx/emqx#1486]
I have a use case of `Shared Subscription` that I need to route message from a publisher always to a specific subscriber

If a topic has subscriber 1 ,2 ,... and publisher A,B,C,...

When A publish a message and subscriber 1 get it , all messages that A published to the topic must route to subscriber 1 until the subscriber disconnected

Can I implement this using shared subscription?
Is there better way?

**Comment by emqplus** [comment]
@sm2017 This feature will be implemented in 2.4-beta.1

**Comment by Gilbert-Wong** [comment]
This feature has been implemented here https://github.com/emqx/emqx/pull/1823
