### ISSUE TITLE
Cannot install to a destination that has spaces in the name

### ISSUE THREAD

**Issue by twmarr** [emqx/emqx#1487]
#### Environment

- OS:  Windows 10
- Erlang/OTP:  19
- EMQ: 2.3.4

#### Description
EMQ will not run from a directory that has spaces in the name.  For example, I need to install it to "c:\Program Files (x86)\My Company Name\emqttd"  and it will not run from there.

#### Output

PS C:\Program Files (x86)\My Company Name\emqttd> bin\emqttd start

C:\Program Files (x86)\My Company Name\emqttd>set args_file=-args_file "C:\Program Files (x86)\My Company Name\emqttd\etc\vm.args"

C:\Program Files (x86)\My Company Name\emqttd>set sys_config=-config "C:\Program Files (x86)\My Company Name\emqttd\etc\sys.config"
\MY was unexpected at this time.

C:\Program Files (x86)\My Company Name\emqttd>  set boot_script=C:\Program Files (x86)\My Company Name\emqttd\releases\2.3.4\emqttd

**Comment by Gilbert-Wong** [comment]
This bug has been fixed in emqx3.1-rc.1. Please try with the latest emqx release.
