### ISSUE TITLE
eheap_alloc: Cannot allocate 441485240 bytes of memory (of type "heap").

### ISSUE THREAD

**Issue by Cavduu** [emqx/emqx#1493]
#### Environment

- OS: AWS Ubuntu 16.04 server
- Erlang/OTP: Erlang/OTP 20
- EMQ: 2.3.3

#### Description

the emq server process has been killed automatically during the night
I checked the /var/log/emqttd and found a file was created: crash.dump
this dump is so big that the size is 3.7M
I checked the file and the slogan shows 
eheap_alloc: Cannot allocate 441485240 bytes of memory (of type "heap").

I think I need to provide more info but the current process has been killed
so Im not really sure if I run below commands will help
emqttd_ctl listeners
emqttd_ctl broker metrics
emqttd_ctl broker stats
emqttd_ctl plugins load emqttd_recon
emqttd_ctl recon bin_leak

please let me know how can I get the info so that we can find the root cause
I'm happy to do anything I  can to, thanks  : )
PS. Attach is crash.dump file
[emq.log](https://github.com/emqtt/emqttd/files/1702198/emq.log)

**Comment by grutabow** [comment]
What is the memory size of your ubuntu machine? Only 1GB?
And what is your log level? error? debug? The log module(lager_event) has consumed 376MB memory.
