### ISSUE TITLE
SSL Not working for wss when using wss from mqttJs in browser

### ISSUE THREAD

**Issue by arihantdaga** [emqx/emqx#1494]
#### Environment

- OS: CentOs 7
- Erlang/OTP:  Not Sure
- EMQ: EMQ: 2.1.2

#### Description
I am trying to enable ssl options for websocket. I am using letsencrypt for generating certificates. I generated certificates and updated these configurations to - 
```
listener.wss.external = 8084

listener.wss.external.acceptors = 16

listener.wss.external.max_clients = 102400

listener.wss.external.access.1 = allow all

## SSL Options
listener.wss.external.handshake_timeout = 15s

listener.wss.external.keyfile = /etc/letsencrypt/live/example.com/privkey.pem

listener.wss.external.certfile = /etc/letsencrypt/live/example.com/fullchain.pem

## listener.wss.external.cacertfile = etc/certs/cacert.pem

listener.wss.external.verify = verify_none

listener.wss.external.fail_if_no_peer_cert = false

``` 

"I Did not Use CaCert" since i did not get it in letsencrypt and i also set verify to verify_none, fail_if_no_peer_cert to false. 

In my browser.js

```
var host = 'wss://example.com:8084/mqtt'

var options = {
  keepalive: 10,
  clientId: clientId,
  protocolId: 'MQTT',
  protocolVersion: 4,
  clean: true,
  reconnectPeriod: 1000,
  connectTimeout: 30 * 1000,
  will: {
    topic: 'WillMsg',
    payload: 'Connection Closed abnormally..!',
    qos: 0,
    retain: false
  },
  username: 'i_am_admin',
  password: 'no_1_blocks_me',
  rejectUnauthorized: false
}

```

But i am getting this error in browser - 

`WebSocket connection to 'wss://example.com:8084/mqtt' failed: Error in connection establishment: net::ERR_INSECURE_RESPONSE
`
(I replaced my domain name with Example.com for this issue description)

Can someone point to me where i am doing wrong ? 

I think better documentation is required for setting up ssl.

**Comment by reejinbouk** [comment]
I got same trouble.

**Comment by reejinbouk** [comment]
got this at logs:

{{ssl_error,{options,{cacertfile,"/etc/letsencrypt/live/*****/chain.pem",{error,eacces}}}},[{esockd_connection,upgrade,1,[{file,"src/esockd_connection.erl"},{line,131}]},{mochiweb_http,init,2,[{file,"src/mochiweb_http.erl"},{line,48}]}]}

**Comment by grutabow** [comment]
Please refer to https://github.com/emqtt/emqttd/issues/765.

**Comment by erennyuksell** [comment]
same problem

**Comment by zmstone** [comment]
@erennyuksell could you please report a new issue or ask a question in discussion.
This thread was created for emqx 3 which is quite old and out of the maintenance window.
