### ISSUE TITLE
websocket ping frames lead to parsing errors

### ISSUE THREAD

**Issue by sandro97git** [emqx/emqx#1496]
#### Environment

- OS: Ubuntu 16.04
- Erlang/OTP: xxx
- EMQ: 2.3.3

#### Description

I have found an issue when using mqtt over websockets. When a websocket library is used which sends websocket ping frames you get parsing errors. 

```erlang
[error] WsClient(192.168.16.1:49850): Frame error: {function_clause,[{emqttd_parser,parse_utf,[<<data>>],[{file,"src/emqttd_parser.erl"},{line,206}]},{emqttd_parser,parse_frame,3,[{file,"src/emqttd_parser.erl"},{line,122}]},{emqttd_ws,ws_loop,3,[{file,"src/emqttd_ws.erl"},{line,103}]},{mochiweb_websocket,request,5,[{file,"src/mochiweb_websocket.erl"},{line,61}]},{proc_lib,wake_up,3,[{file,"proc_lib.erl"},{line,257}]}]}
```

I used the C# websocket library [WebSocket4Net](https://github.com/kerryjiang/WebSocket4Net). 
The problem seems to be that ping frames are not caught by mochiweb and therefore ping frames are interpreted as normal data frames. The payload inside the ping frame in my case is  a timestamp. EMQTT tries to parse this timestamp as mqtt message.

I don't know if this is the right place for  this issue or if i should open one in the mochiweb repository.

**Comment by HJianBo** [comment]
Yes, **mochiweb** not handle Ping frames. This implementation may be reasonable because:
>  A Ping frame MAY include "Application data".
> *- [Websocket RFC6455](https://tools.ietf.org/html/rfc6455#section-5.5.2)*

It's a better practice that sends MQTT Ping Request to verify that the remote endpoint is still responsive, not using Websocket Ping Request?
