### ISSUE TITLE
http://emqtt.com/downloads/latest/freebsd is emtpy

### ISSUE THREAD

**Issue by MartenVijn** [emqx/emqx#1499]
http://emqtt.com/downloads/latest/freebsd

is dead... 

#### Environment

- OS:  FreeBSD

- Erlang/OTP:  nvt
- EMQ:  Latested

#### Description

*no package avialble*

**Comment by Gilbert-Wong** [comment]
Sorry for that because we have not prepared bsd package until now... We'll try our best to make a bsd package as quick as possible.

**Comment by zhanghongtong** [comment]
You can use the docker to run emqx

**Comment by emanuelstanciu** [comment]
Hi @Gilbert-Wong 
Any news on the FreeBSD package? Would like to install eMQ on a pfSense box, so would like to minimise the amount of build requirements and Docker is also not an option.
Please let me know when you think a FreeBSD package will be available on the Downloads page.
Thanks

**Comment by jinfahua** [comment]
@emanuelstanciu what's your freebsd version?

**Comment by emanuelstanciu** [comment]
@jinfahua FreeBSD 11.2-RELEASE-p4 - based on https://docs.netgate.com/pfsense/en/latest/releases/versions-of-pfsense-and-freebsd.html

Thanks for your help

**Comment by emanuelstanciu** [comment]
Hi @Gilbert-Wong, any (good) news on this build?
I have seen this is slipping release after release. Do you have a timeframe in mind for enabling a build for FreeBSD?

Thanks for your time

**Comment by Gilbert-Wong** [comment]
We'll enable a FreeBSD build release in emqx 3.2.

**Comment by turtleDeng** [comment]
Already supported FreeBSD12 download in 3.1.0
```
https://www.emqx.io/downloads/broker/v3.1.0/emqx-freebsd12-v3.1.0.zip
```

**Comment by emanuelstanciu** [comment]
hi @turtleDeng, requirement and request for this was pfsense, which is not built from mainstream FreeBSD - as mentioned above it requires build for:

> FreeBSD 11.2-RELEASE-p4 - based on https://docs.netgate.com/pfsense/en/latest/releases/versions-of-pfsense-and-freebsd.html

Ideally, please reopen and address this issue in particular - thanks in advance for assistance
