### ISSUE TITLE
Please add prometheus monitoring support

### ISSUE THREAD

**Issue by haok3166** [emqx/emqx#1500]
Thanks for building such great mqtt broker. Please consider to add prometheus monitoring support.

**Comment by turtleDeng** [comment]
@haok3166 EMQX Enterprise Edition already support.

**Comment by haok3166** [comment]
Thanks for your reply. We have added our own prometheus exporter based on the HTTP API. Where to download the EMQ X Enterprise Edition?

**Comment by emqplus** [comment]
@haok3166 The prometheus monitoring plugin will be released in version 2.4-beta.1.

**Comment by haok3166** [comment]
Great, thanks.

**Comment by gihad** [comment]
@emqplus Just to clarify will the prometheus monitoring plugin be available in EMQ 2.4-beta.1. or just in EMQ-X?

**Comment by ricardoccpaiva** [comment]
any news on this @gihad / @emqplus ?

**Comment by HackToHell** [comment]
bump for anything regarding this. @emqplus

**Comment by NiekPeeters** [comment]
Any news on this? @emqplus

**Comment by sashaafm** [comment]
Bumping up @emqplus

**Comment by turtleDeng** [comment]
emq support prometheus. https://github.com/emqx/emqx-statsd

**Comment by huydinhle** [comment]
@turtleDeng  we are using 2.3.11, we are not planning to move to 3.0 just yet. I would like to try the `2.4-beta.1` preferably with docker image. Is there a place to download or get this docker image somewhere?

**Comment by turtleDeng** [comment]
@huydinhle  Sorry, can't support it at 2.3.11

**Comment by huydinhle** [comment]
How about `2.4-beta.1` ? Do we have a plan to release 2.4 at some point? Or  `emqx-statsd` will be only supported in 3.0? 
@turtleDeng

**Comment by turtleDeng** [comment]
@huydinhle 3.0.0 has been released, there will be no 2.4-beta.1
