### ISSUE TITLE
Shared subscription / same session id

### ISSUE THREAD

**Issue by perroudchris** [emqx/emqx#1501]
Hello 

I'm trying to make a shared subscription on a 2.3.3. emqtt cluster. I saw that the '$local/topic' works but I would like not to have this "prefix" on the topic of my mqtt "sending datas" devices. 

I found something but I don't know the exact behavior and if it's gonna be changed in the next versions. 

I used the same client id option (I'm using the mosquitto_sub command for my tests right now) for any of my "subscribers" and when a message is send to the broker, only one of my subscribers recieves the message. That's exactly what I would like to have (because it's not an obligation to put the '$local/$shared...' prefix anymore) but I haven't seen this solution in any documentation. Does it mean that this is gonna be changed ? If not, what's the repartition behavior on this case ? Is it a round robin ?  Is there any other solution for sharing subscription than use this specifical topic ? 

Thanks for now and sorry for my poor English :)

**Comment by grutabow** [comment]
Don's use a same client id for multiple mqtt clients, since only one of them could remain online and others will be kicked offline.

Please refer to the official document http://emqttd-docs.readthedocs.io/en/latest/advanced.html.

Here is an example of local shared subscription:
1. Client A/B/C all subscribe topic='$local/$share/group1/test'
2. Client D publish a message on topic='test'
3. One of A/B/C will receive a message on topic='test'. The other two clients will receive nothing.

**Comment by perroudchris** [comment]
Thanks for the answer :)

**Comment by grutabow** [comment]
What about clean-session=true? Broker will never sent messages to disconnected clients if session is destroyed. Does this meet your requirement?

**Comment by perroudchris** [comment]
Yes it does. You're right but I wanted to know if there's a possibility to send messages only to "real" active clients (who has the mosquitto_sub launched for example) and still keep messages that have not been recieved by anyone (for example if my 2 clients have a problem and disconnect at the same time). 

In summary : keep a persistence but only distribute the shared subscription to effective present and connected clients.  I don't think it's possible but I just wanted to be sure. 

In every case, thanks a lot for your helpfull replies :)

**Comment by grutabow** [comment]
Let's build a scenario:

1. A/B/C/D connected with clean-session=false
2. A/B/C/D all shared-subscribe a same topic
3. C/D get disconnected for some reason

You want to distribute messages between A/B, without C/D. Is it what you want? If so, emqttd does not support this feature.

**Comment by perroudchris** [comment]
Hello. That's exactly what I wanted to know. Thanks for the answer :)

**Comment by emqplus** [comment]
@perroudchris The shared subscription feature should be improved in 2.4 release, exactly to feed the scenario you required.

We should ensure a QoS1/2 MQTT message be delivered to an online client.

**Comment by zhengyupan** [comment]
Hi @perroudchris ,
We have improved the implementation of shared subscription, now it works as the scenario described by grutabow.

**Comment by perroudchris** [comment]
Thanks a lot :)

**Comment by gbrehmer** [comment]
@zhengyupan 
@spring2maz stated in https://github.com/emqx/emqx/pull/1823, that connection status is currently not part of dispatch logic for shared subscription messages. But the scenario of grutabow contains two offline clients

**Comment by spring2maz** [comment]
Since a session can be persistent, it may also be used for shared and non-shared subscription at the same time, there is not going to be a generic enough solution out of the box.
One workaround for now is to use only clean session for shared subscribers.
I am planing to add a connection state check in #1872. The idea is that shared dispatches will be negative-acked by the session if when there is not an active connection so the sender session can pick the next member in the group (next depends on the dispatch strategy).
The current plan is to only add this check for QoS1 and QoS2 messages though.

**Comment by perroudchris** [comment]
Hello. With clean session, everything is ok with the scenario we built. But let's build this one: 


   1.A/B/C/D connected with clean-session=false
   2. A/B/C/D all shared-subscribe a same topic
   3.  A/B/C/D get disconnected for some reason
   4. 12 messages from clients are coming on the broker
   5. A (alone) connects once again with clean-session= false
      At the moment, he only sees 25% of these messages... is it possible to see the 12 messages and not only 3 ?

**Comment by perroudchris** [comment]
> Since a session can be persistent, it may also be used for shared and non-shared subscription at the same time, there is not going to be a generic enough solution out of the box.
> One workaround for now is to use only clean session for shared subscribers.
> I am planing to add a connection state check in #1872. The idea is that shared dispatches will be negative-acked by the session if there is not an active connection so the sender session can pick the next member in the group (next depends on the dispatch strategy).
> The current plan is to only add this check for QoS1 and QoS2 messages though.

Was this (good) idea already implemented ?

**Comment by perroudchris** [comment]
Sadly I got the same result with QoS=0. When one of my clients (mosquitto_sub, -clean-session=false) quits, the messages are still distributed to his session whereas all messages should be taken by the others "still connected" clients.

**Comment by spring2maz** [comment]
@perroudchris I'll have a look into and get back to you later.

**Comment by perroudchris** [comment]
I think that I found something into the config : 
broker.shared_dispatch_ack_enabled has to be true. Now, with this parameter, the messages are delivered only to online "non-clean session" subscribers.  That's already a good point

Something that is still missing : when all my clients are disconnected, there's no persistence of the messages when I'm using the "$queue/" prefix in my topic.
