### ISSUE TITLE
Support for WebSockets permessage-deflate extension?

### ISSUE THREAD

**Issue by Eric24** [emqx/emqx#1510]
Does the current version of eMQTT support the permessage-deflate extension (https://tools.ietf.org/html/draft-ietf-hybi-permessage-compression-19)? If not, are there any plans to do this in the future?

**Comment by emqplus** [comment]
Hi @Eric24, EMQ R2 does not support this WS specification still. I can add the feature to the plan of EMQ R3.

**Comment by Gilbert-Wong** [comment]
This feature has been implemented and pull request [here](https://github.com/emqx/emqx/pull/2356), It should be released as emqx 3.1 beta4 in next week.

**Comment by Gilbert-Wong** [comment]
It has been fixed in emqx 3.1-rc.1, please check it.
