### ISSUE TITLE
MongoDB Auth timeout

### ISSUE THREAD

**Issue by gregwinn** [emqx/emqx#1513]
#### Environment

- OS: Ubuntu 16
- Erlang/OTP: 
- EMQ: 

#### Description

I am getting the following error when trying to use MongoDB for my auth:

`
[error] Client(mqttjs_3733db7f@IP-REMOVED:56788): Username 'a12345' login failed for {{badmap,{error,timeout}},[{maps,get,[<<"password">>,{error,timeout},undefined],[{file,"maps.erl"},{line,192}]},{emq_auth_mongo,'-check/3-lc$^0/1-0-',2,[{file,"src/emq_auth_mongo.erl"},{line,52}]},{emq_auth_mongo,check,3,[{file,"src/emq_auth_mongo.erl"},{line,52}]},{emqttd_access_control,auth,3,[{file,"src/emqttd_access_control.erl"},{line,60}]},{emqttd_protocol,authenticate,2,[{file,"src/emqttd_protocol.erl"},{line,536}]},{emqttd_protocol,process,2,[{file,"src/emqttd_protocol.erl"},{line,214}]},{emqttd_client,received,2,[{file,"src/emqttd_client.erl"},{line,324}]},{gen_server2,handle_msg,2,[{file,"src/gen_server2.erl"},{line,1046}]}]}
`

I see the timeout error but i am not sure what I am doing wrong. I have the server configured in the correct config file along with a user in the DB with that matching username.

**Comment by incowiz** [comment]
you can test your "mongodb auth" by using "mqttfx" tool.
- with this tool, firstly make sure "username" and "password" is correct.

**Comment by HJianBo** [comment]
This error will occur if the emq_auth_mongo can't reach MongoDB server.

Could you make sure that the EMQ server can login correctly to MongoDB by the following cmd:
```bash
mongo  mongoserver:27017/mqtt -u username -p password
```
