### ISSUE TITLE
dns clustering not working on aws ubuntu 16.04

### ISSUE THREAD

**Issue by incowiz** [emqx/emqx#1515]
#### Environment

- OS: AWS ubuntu 16.04
- Erlang/OTP: 20 [erts-9.0]
- EMQ: v2.3.4

#### Description

*A description of the issue*
my condition:
1. launch 2 EC2 instances on aws (ubuntu 16.04) - i opened all ports to remove port blocking during my test
2. set "emqttd/etc/emq.conf" 
(see my setting below:)

- the 1st EC2 instance 
`cluster.discovery = dns`
`cluster.dns.name = LB-xxxx-71698xxxx.ap-northeast-2.elb.amazonaws.com # this my aws classic load balancer's DNS A-record`
`cluster.dns.app = emq2`
`node.name = emq2@172.31.10.214`

- the 2st EC2 instance 
`cluster.discovery = dns`
`cluster.dns.name = LB-xxxx-71698xxxx.ap-northeast-2.elb.amazonaws.com # this my aws classic load balancer's DNS A-record`
`cluster.dns.app = emq`
`node.name = emq2@172.31.10.71`

- cluster status shows (these 2 emqtt node are not clustered!)
`./bin/emqttd_ctl cluster status`
`Cluster status: [{running_nodes,['emq2@172.31.10.214']}]`

i refered this link:  [Autocluster by DNS A Record](http://emqtt.io/docs/v2/cluster.html#node-discovery-and-autocluster)

**Comment by emqplus** [comment]
@incowiz The configurations are not right, the `cluster.dns.app` should be same in all the nodes.

- the 1st EC2 instance 

```
cluster.discovery = dns
cluster.dns.name = LB-xxxx-71698xxxx.ap-northeast-2.elb.amazonaws.com # this my aws classic load balancer's DNS A-record
cluster.dns.app = emq
node.name = emq@172.31.10.214
```

- the 2st EC2 instance 

```
cluster.discovery = dns
cluster.dns.name = LB-xxxx-71698xxxx.ap-northeast-2.elb.amazonaws.com # this my aws classic load balancer's DNS A-record
cluster.dns.app = emq
node.name = emq@172.31.10.71
```

**Comment by incowiz** [comment]
@emqplus 
thank you for your answer. 
but 
`DNS  auto-clustering still does not working`

i changed `cluster.dns.app` value to `emq`, thus now my all aws ec2 instance have the same `cluster.dns.app` value.

if i check "clustering status" with the below command on "emq@172.31.10.71" node: 
``` 
./bin/emqttd_ctl cluster status 
Cluster status: [{running_nodes,['emq@172.31.10.71']}] 
```
it shows only its status.

How can i fix it? please pass your opinion.

**Comment by emqplus** [comment]
@incowiz Did you change the nodes' name? Steps to debug the issue:

1. Start one node in console mode:

`./bin/emqttd_ctl console`

2. Check if the Erlang VM can lookup the DNS A records:

`inet_res:lookup("LB-xxxx-71698xxxx.ap-northeast-2.elb.amazonaws.com", in, a).`

**Comment by incowiz** [comment]
1. Start one node in console mode:
`./bin/emqttd console`
- I started my EC2 with the above command

2. Check if the Erlang VM can lookup the DNS A records:
```
inet_res:lookup("LB-xxxx-71698xxxx.ap-northeast-2.elb.amazonaws.com", in, a).
[{52,78,6,109},{13,124,5,130}]
```
- All these 2 IP address is NOT current my EC2's IP address.

How can i re-fresh them with my current EC2's IP address?
- should i remove `data/mnesia`?
(another question: why these IP are appeared?)

Thank you very much.

**Comment by vicary** [comment]
Found this during my search on docker auto cluster.

ELB points to instances’ public IP while the instance itself usually has no knowledge of, without doing some tricky lookups. I assume the node is using private IP directly from the available network interface. (Private IPs usually starts with 172)

Explicitly bind the node host to your public IP may work.

**Comment by zhengyupan** [comment]
Hi @incowiz ,
In your lookup test we can that the DNS service you used returns two public IPs, and in your configuration of emq you used two 172.31 address. That's why the DNS clustering didn't work for your.
As Vicary suggested, you can use the public IPs in your emq configuration to make them be recognized by dns auto clustering. But for an EC2 instance, it is not guaranteed that this instance will get the same public IP after it restarts. So, I will suggest that you use other ways to cluster up your nodes.
