### ISSUE TITLE
Dropped message update_counter badarg error

### ISSUE THREAD

**Issue by lv12312** [emqx/emqx#1518]
#### Environment

- OS: CentOS 7
- Erlang/OTP: erts 9.1
- EMQ: 2.3.1

#### Description

Sometimes if many messages have been dropped, these errors may throws:

```
2018-03-01 10:06:59.745 [error] emulator Error in process <0.8076.0> on node 'emq@172.x.x.x' with exit value:
{badarg,[{ets,update_counter,[mqtt_metric,{'messages/dropped',5},{2,1}],[]},{emqttd_metrics,inc,3,[{file,"src/emqttd_metrics.erl"},{line,216}]},{emqttd_pubsub,dispatch,2,[{file,"src/emqttd_pubsub.erl"},{line,102}]}]}
```
EMQ Team, is that a bug? 
Thanks !

**Comment by emqplus** [comment]
@lv12312 It seems the `mqtt_metric` ets table has gone. Are there any crash or error logs?

**Comment by lv12312** [comment]
The reason is that the server crash and restart automatically. The errors occurred when I benchmarked the performance.

**Comment by emqplus** [comment]
@lv12312 There will be OOM to crash the broker, if a slow subscriber cannot handle messages from too many publishers.

1. Use `shared subscription` to load balance the throughput: http://emqtt.io/docs/v2/advanced.html#shared-subscription

2. The broker will support 'Flow Control' and 'Slow Subscriber Detection' in next release.

**Comment by lv12312** [comment]
@emqplus  Thank you!
