### ISSUE TITLE
Order of delivery in broadcast

### ISSUE THREAD

**Issue by nagendraK6** [emqx/emqx#1527]
#### Environment
Ubuntu AWS t2.2xlarge
- OS: 
Ubuntu
- Erlang/OTP: 
- EMQ: 

#### Description

I want to know order in which EMQ sends the message to clients. We have EMQ server and ~2000 clients are connected with same topic. When we publish any data on topic in which order client receives the data. We observed that clients get the data order in which they connected to EMQ server.

*A description of the issue*

**Comment by emqplus** [comment]
@nagendraK6 The broker cannot ensure the order of a message published to many clients, for the dispatch process is asynchronous.
