### ISSUE TITLE
EMQ taking large amount of memory

### ISSUE THREAD

**Issue by rejji** [emqx/emqx#1535]
#### Environment

- OS: VMware Photon Linux 1.0
- Erlang/OTP: R19/8.1
- EMQ: 2.1.2

#### Description

EMQTT is taking large amount of memory. 
Setup has 1000 publishers, each sending 800 metrics, with two subscribers over 8883 (ssl). Memory taken by emqtt starts growing up and reaches upto 6.2GB and stays more or less at that level. QoS1 with queue.max_length=infinity. emqtt is installed as rpm from inside the Photon docker container. 

We had two runs (one was with 59 publishers and another one is with 1270 publishers).

Case1: 59 publishers 
Case2:1270 publishers 
excel sheet with data is attached.
(A) Could it be related reference counted binaries that are garbage collected much later in time (binary_alloc). We came across a post https://groups.google.com/forum/#!topic/rabbitmq-users/ALeIZ6VXJfc where faced an issue wrt binary_alloc of Erlang and resolved by tuning ERL_FLAGS to '+MBas aobf +MBlmbcs 512' in the context of RabbitMQ. These settings are not exposed at emqtt. Could it be useful for us to tune in these directions.

Does following impact the performance or could it be related here. 
(B) Publisher is sending large number of small messages vs the case where publisher is sending small number of large messages (with overall data size being same).
(C) If subscriber is putting messages into its own queue gated by a read or write lock, can it bring the memory consumption at emqtt high. Are there some commands or stats we can use to validate this part.

[MemoryComponents_1270connections_4pm.xlsx](https://github.com/emqtt/emqttd/files/1825898/MemoryComponents_1270connections_4pm.xlsx)
[Memory_59connections_8pm.xlsx](https://github.com/emqtt/emqttd/files/1825902/Memory_59connections_8pm.xlsx)
[emq.conf.txt](https://github.com/emqtt/emqttd/files/1825922/emq.conf.txt)

------------

#### Could you help in understanding following:

(D) If we want to check how many messages are held in different queues in memory, is there a command we can use to check for it.
(E) Where exactly queue is written to disk in case it is moved.
(F) What is the policy of moving the messages to disk - is it first in first out from memory to disk
(G) What is eviction policy in case queue gets full
(H) Does the memory to/from disk movement degrade performance and availability of emqtt (rpc to nodes). Is it severe to the extend of unresponsiveness at that time. 

Let me know if there is more information or data required here. Please consider it critical that is a show stopper for us and we need to resolve in coming day or two.

Thanks a lot.

**Comment by emqplus** [comment]
Hi @rejji, from the metrics and statistics in the attached documents, we found there are two issues in your case:

## SSL Subscribers

### Problem

The SSL subscribers should not connect to EMQ broker directly. We usually suggest deploying a HAProxy in the front of EMQ cluster to terminate the SSL connections for the SSL library of Erlang/OTP will not GC the binary references actively. If no global GC is enabled, the `memory/system` and `memory/binary` will increase over time. The stats showed in the Memory_59connections_8pm.xlsx:

Time | 8:05 | 8:35 | 11:11 | 12:04
-- | -- | -- | -- | --
Clients | 59 | 59 | 59 | 59
Docker-stats mem | 229533286.4 | 230162432 | 258788556.8 | 271371468.8
memory/total | 173655712 | 177480304 | 196890448 | 204269464
memory/system | 136742168 | 140071816 | 159436608 | 166511896
memory/binary | 54452480 | 57241728 | 73618688 | 79528920

### Solutions

1. Load the emq_recon plugin and enable the global GC in the 'etc/plugins/emq_recon.conf':
   `recon.gc_interval = 5m`
2. Deploy a HAProxy in the front of EMQ Cluster to terminate SSL connections:
   http://emqx-enterprise-docs-en.readthedocs.io/en/latest/deploy.html#haproxy-emq-x
3. Upgrade the EMQ to 2.3.5, and enable the force GC:

```
## Force GC the MQTT connections. Value 0 will disable the Force GC.
##
## Value: Number >= 0
mqtt.conn.force_gc_count = 100
```
## Many Publishers and Slow Subscriber

### Problem

If there is a slow subscriber which consumes messages published from many publishers, all the messages which cannot be delivered/acked by the subscriber will be accumulated in the memory of EMQ broker if `queue.max_length=infinity`. 

Erlang/OTP is a soft real-time system, which schedules all the processes via preemptive scheduling.  Each process will be assigned the same reductions and time slice of CPU. This makes things worse for a slow subscriber cannot get more CPUs though it has a lot of work to be done:)

The metrics in `MemoryComponents_1270connections_4pm` show there are almost 188K+ messages are accumulated in the memory queues of the subscribers:

Time | 4:07 | 4:37 | 5:00
-- | -- | -- | --
Clients | 1270 | 1270 | 1272
Docker-stats mem | 1286342705.152 | 1438814044.16 | 1503238553.6
messages/qos1/received | 7601929 | 8588905 | 9279696
messages/qos1/sent | 7421823 | 8403690 | 9091142
messages/received | 7601929 | 8588905 | 9279696
messages/sent | 7421823 | 8403690 | 9091142

### Solutions

1. Use `etop` to check if the subscribers' processes consume most memory:

···
./bin/emqttd attach

spawn(fun() -> etop:start([{lines, 20},  {sort, memory}]) end).
···
Notice that CTRL+D to quit the console!

2. A subscriber deployed in the local network can consume about 2K+ QoS1 messages/second in our benchmark. From the metrics in the MemoryComponents_1270connections_4pm.xlsx, the pub rate is about 500 messages/sec, we have to check if the subscribers can consume messages at the same rate.

3. Load balancing among a group of subscribers via shared subscription:
···
                           ---------
                            |       | --Msg1--> Subscriber1
Publisher--Msg1,Msg2,Msg3-->|  EMQ  | --Msg2--> Subscriber2
                            |       | --Msg3--> Subscriber3
                            ---------
···

4. If the subscribers consume messages and then insert them into databases, I suggest to upgrade EMQ to the enterprise edition, which helps store messages in a database directly:
   http://emqx-enterprise-docs-en.readthedocs.io/en/latest/backends.html

**Comment by terry-xiaoyu** [comment]
@rejji Hi, besides the `etop` to see the message queues and memory of the erlang processes, you could also use `./bin/emqttd_ctl sessions list` to inspect the current sessions:
```shell
$ ./bin/emqttd_ctl sessions list
Session(test1, clean_sess=false, subscriptions=1, max_inflight=32, inflight=0, mqueue_len=3, mqueue_dropped=0, awaiting_rel=0, deliver_msg=1, enqueue_msg=3, created_at=1521516149)
```
`mqueue_len` shows the current number of queued messages. And the inflight shows the number of messages not acked.

BTW, currently the community version of EMQ only keeps message queues in memory, it won't save them to disk.

**Comment by rejji** [comment]
Thanks for the quick response Feng, Shawn. We will take these inputs and include them.

**Comment by rejji** [comment]
@emqplus @terry-xiaoyu 

With qos0 and mqtt.queue.qos0=false, how much memory consumption is expected? It was reported to be accumulating memory and had a spike in the graphs. Could you confirm and give an insight.

'sessions list' mostly shows undefined.
Session(paho1555105973252863, clean_sess=true, subscriptions=undefined, max_inflight=undefined, inflight=undefined, mqueue_len=undefined, mqueue_dropped=undefined, awaiting_rel=undefined, deliver_msg=undefined, enqueue_msg=undefined, created_at=1521890135)

For points A..H, could you provide some info for us to debug and analyze further. 

Is there a trial version we can try with for the Enterprise edition?

**Comment by Gilbert-Wong** [comment]
First, if you set the `mqtt.queue.qos0=false`, the memory consumption would be down because server would not keep the qos0 message on your broker in memory.
Second, if you want to try Enterprise edition, please contact with @zhengyupan
