### ISSUE TITLE
EMQTT drop publish(qos==1) when benchmark

### ISSUE THREAD

**Issue by homerzhou** [emqx/emqx#1538]
#### Environment

- OS: Debian
- Erlang/OTP: docker  
- EMQ: 2.3.4

#### Description
when I try to benchmark EMQTT. 
My benchmark test is 100 clients receive publish and send back publish, and other 100 clients send publish and wait publish back.
If i send publish too quick,  there will be many publish can not back, and I see the DASHBOARD, the `the messages data->dropped`have the same count which publish is not back.
I check all publish have receive PUBACK. 100 clients which receive publish all receive the publish

Is it Related to `configure -> mqueue.max_length` ?
How can I avoid drop publish when publish is too much?

**Comment by HJianBo** [comment]
Hi, @homerzhou The value of `The messages data -> dropped` will be increased when a PUBLISH Topic does not exist any Subscribers.

So,  Is there exist available subscription relationship?

**Comment by homerzhou** [comment]
The topic is must exist.
My test case is, 100 clients recv data and echo data back.
I found only few publish message is not echo back

**Comment by homerzhou** [comment]
I want to know how can I find the message which is dropped.(not use open log debug)

**Comment by Gilbert-Wong** [comment]
Sorry for late respond @homerzhou , the emqx does not support to find the message which has been dropped. It is designed to be message broker, not recycle bin.
