### ISSUE TITLE
long_schedule warning happened

### ISSUE THREAD

**Issue by dingzhengkai** [emqx/emqx#1543]
#### Environment

- OS: CentOS 7.4
- Erlang/OTP: 
- EMQ: 2.3.5 (docker image)

#### Description

**console log**

> 2018-03-23 16:07:34.900 [warning] <0.1341.0>@emqttd_sysmon:handle_info:99 long_schedule warning: pid = <0.21027.24>, info: [{timeout,249},
>                                                   {in,{prim_inet,ctl_cmd,3}},
>                                                   {out,{prim_inet,ctl_cmd,3}}]
> [{initial_call,{proc_lib,init_p,5}},{current_function,{prim_inet,ctl_cmd,3}},{registered_name,[]},{status,running},{message_queue_len,1},{group_leader,<0.1163.0>},{priority,normal},{trap_exit,false},{reductions,190403074},{last_calls,false},{catchlevel,2},{trace,0},{suspending,[]},{sequential_trace_token,[]},{error_handler,error_handler},{memory,6993120},{total_heap_size,833047},{heap_size,833026},{stack_size,8},{min_heap_size,233}]
> 

The utilization of CPU on my server was up to 100%
On what condition this warning might happen?

**Comment by HJianBo** [comment]
The `long_schedule` warning will be reported, if a process in the system runs uninterrupted for at least `Time` wall clock milliseconds.

The `Time` can be specified in the `emq.conf`, default is:
```
## Enable Long Schedule(ms) monitoring.
##
## See: http://erlang.org/doc/man/erlang.html#system_monitor-2
##
## Value: Number
sysmon.long_schedule = 240
```

**Comment by terry-xiaoyu** [comment]
@dingzhengkai What were you doing at that time? Were you publishing a lot of messages to EMQ and decode them in your plugin? Decoding large messages such as JSON using NIFs might cause this kind of problem. 

Or your server was too busy at that time? The warning would also be reported if you run EMQ on a very busy server.

**Comment by dingzhengkai** [comment]
@terry-xiaoyu @HJianBo thanks for reply.
At that time, the utilization of cpu on my server was almost up to 100%(the emq erl process), but my server(or the emq server) did not run a lot of tasks, so i thought whether there was something wrong in emq.
My server was up about 60 days, i rebooted it to solve the problem.
