### ISSUE TITLE
Bridge from EMQ to a different broker

### ISSUE THREAD

**Issue by Marina190489** [emqx/emqx#1544]
#### Environment
- EMQ: 

#### Description
I need to create a bridge from my EMQ broker to another broker (not EMQ).
Is it possible and how should I configure it? All the options I've seen so far are from non EMQ broker to EMQ one and not the opposite way.

**Comment by victorclaessen** [comment]
I think that that is not possible right now. So far I've also only seen options to do it the other way around.

**Comment by Marina190489** [comment]
Thanks! I saw that someone mentioned that this feature should be avail on next versions- any idea if that's true and when it may happen?

**Comment by victorclaessen** [comment]
Sorry, I have no idea if and when that could happen. I've come to rely on the mosquitto-double-bridge workaround. Unfortunately, that workaround suffers from a lack of redundancy.

**Comment by Marina190489** [comment]
what is this workaround? you mean you use two mosquitto brokers instead of 1 EMQ and 1 mosquitto for example?

**Comment by Marina190489** [comment]
what is this workaround? you use 2 mosquitto brokers with a bridge between them?

**Comment by victorclaessen** [comment]
Oh sorry, I just assumed you'd come across it already. It's one mosquitto broker making two bridges (one to emqtt, and the other to where you would have liked emqtt to be able to connect to), described here: https://github.com/emqtt/emqttd/issues/1390#issuecomment-363561564

**Comment by zhengyupan** [comment]
Hi @Marina190489 , this feature is implemented in EMQ X 3.0-beta.3.
