### ISSUE TITLE
The topics of the subscription is missing

### ISSUE THREAD

**Issue by promission** [emqx/emqx#1546]
#### Environment

- OS: red hat 4.4.7-16
- Erlang/OTP: 
- EMQ: 2.2

A user "U" has established a connection and subscribed to the topic of the system offline message: "$SYS/brokers/+/clients/+/#" and "$local/$queue/E/T/C". After running for a few days, suddenly found that the subscription "$SYS/brokers/+/clients/+/#","$local/$queue/E/T/C" is gone, the background page and command queries are not visible. "U" is still connected!
What is the cause of this?

Today，start：
![image](https://user-images.githubusercontent.com/20593197/38130188-98518cc8-3434-11e8-9fd7-68fccba51458.png)
Wait a few days before seeing if there will be a message：（Waitting for results,continuous update）

**Comment by terry-xiaoyu** [comment]
@promission Hi! Did 'U' connect to the broker with `Clean Session` set to `true`? And would 'U' auto-reconnect to the broker if the connection was down?

If so, and if for some reason the connection is down, you might lost all of your subscriptions after the connection is re-establish. You should subscribe the topics again.

**Comment by promission** [comment]
thanks，you are right， i will try set "Clean Session" to "false"，then traceing for a few days.
