### ISSUE TITLE
Cannot retain message(topic=qtmqtt/topic1, payload_size=76334) for payload is too big!

### ISSUE THREAD

**Issue by MyraBaba** [emqx/emqx#1548]
#### Environment

- OS: Ubuntu
- Erlang/OTP: 
- EMQ: emqttd 2.3.5

#### Description

I try to use emqtt broker throuh Qt mqt module. All is working fine.
But when the message getting bigger it gives :

`Cannot retain message(topic=qtmqtt/topic1, payload_size=76334) for payload is too big!`

I increased mqtt.max_packet_size = 128KB

but still same error.

My packets generally between 100KB - 250KB

How can I send this type of payload data ?

thx.

**Comment by MyraBaba** [comment]
Thanks a lot.

We mainly using the rabbitMq but recently we want to give a shot to the emqtt. We love mqtt.

Only feature that we need a queue in system. like in the rabbitmq. I know it could be against to the emqtt idea.

Is there any such feature ; keep the mesaages in the emqtt until somebody receive it?

thanks again.

**Comment by terry-xiaoyu** [comment]
@MyraBaba Yes, you can set the `clean session = false`, and tune the `mqtt.mqueue.max_length` in emq.conf.

**Comment by MyraBaba** [comment]
Thanks..

is it removing the item if any subscriber took it , or it will keep all queue and any new subscriber get the full history ?

thx.

**Comment by MyraBaba** [comment]
I think this is 👍 
```
## Max queue length. Enqueued messages when persistent client disconnected,
## or inflight window is full.
mqtt.mqueue.max_length = infinity
```


So if the client persistent and lost the connection emq enqueing until client come back. 

I didnt fount the clean session  = false config item in emq.conf

**Comment by terry-xiaoyu** [comment]
@MyraBaba `clean session` is a flag in the `CONNECT` MQTT message. 

MQTT broker will buffer messages for every clients who have already subscribed your topics but stay offline, but not for the `new subscribers` of the topics. The message queues are created per ClientIDs.

I don't think EMQ is a replacement of RabbitMQ, it has never tried to do that.

MQTT is designed for IoT devices, in which scenario the count of connections would be massive, but the size of packages would be small. And the 3 level QoS are designed for unreliable networks.
