### ISSUE TITLE
How EMQ support Sync message mechanism ?

### ISSUE THREAD

**Issue by wujunze** [emqx/emqx#1551]
#### Environment

- OS:  All
- Erlang/OTP:  latest
- EMQ: ALl

#### Description

This is not a issue but a topic. how EMQ support Sync message mechanism ?
Like https://docs.wilddog.com/sync/Web/index.html

**Comment by terry-xiaoyu** [comment]
Are you looking for a MQTT `Chat Sepc` with multiple platforms synchronizing messages? Then [ASSChat](https://github.com/terry-xiaoyu/asschat) might be what you want. A English version will come soon.

The only problem is, if you're using MQTT v3.1.1, publishing to a topic to which a client has subscribed will cause an extra message being sent to the client itself. But you can easily filter out that message by providing a message-id in the message body.

**Comment by wujunze** [comment]
I can use MQTT v5.0.
Where have ASSChat's source code?  
From the document, ASSChat is able to keep the message that has not been received offline and the User can pull it back without losing the message, right?

Thanks  @terry-xiaoyu

**Comment by terry-xiaoyu** [comment]
Yes it is designed for IM services, offline messages SHOULD be stored at server.

I just get started on that project, the spec-design is about to finish. 
And I am planning to implement the `ASSChat Spec` in Erlang or Elixir, by creating plugins for EMQ.

In your case, you could let your clients of same user subscribe to a same Topic, like the method suggested in ASSChat.

**Comment by wujunze** [comment]
That sounds great.
Could you tell me when ASCHAT will release the implementation code with iOS or Android SDK?

**Comment by terry-xiaoyu** [comment]
Not planned. ASSChat is not a project in emqttd. You could post issues at that project.
