### ISSUE TITLE
SSL certificate depth

### ISSUE THREAD

**Issue by FartParty** [emqx/emqx#1552]
#### Environment

- OS:  Linux (Alpine Container)
- Erlang/OTP:  R19/8.3
- EMQ: 2.3.5

#### Description

I'm trying to debug client ssl certificate issues when connecting to an SSL broker.  I've set verify_peer and have a somewhat complex CA Chain.  The error message I'm getting is:

```
[error] SSL: certify: ssl_handshake.erl:1627:Fatal error: handshake failure - {bad_cert,max_path_length_reached}
```

My CA Chain is:  Root->Intermediate->Issuer->Client.
The Issuer has signed the client, but the default SSL settings appear to only verify a depth of 0, which according to documentation, only works if your client is signed by the Root.

In ssl_dist.conf shipped with the standard build I see that depth is set to 0 - I tried overriding this value and it had no effect.  How do I modify depth of the chain on the server?

Additional testing has revealed that even when I set options in ssl_dist.conf and tell emq.conf to pick up the config no settings in that config appear to be honored.

**Comment by terry-xiaoyu** [comment]
@FartParty Hello Jeffrey! Could you post your `ssl_dist.conf`? I've verified that with CA depth 1, and it works as expected.

I used the the following configuration in my test: 

in my etc/emq.conf:
```
node.proto_dist = inet_tls
node.ssl_dist_optfile = etc/ssl_dist.conf
```

in my etc/ssl_dist.conf:
```
[{server,
  [{certfile, "cert/ca/intermediate/certs/aerone.com.cn.cert.pem"},
   {keyfile, "cert/ca/intermediate/private/aerone.com.cn.key.pem"},
   {cacertfile, "cert/ca/intermediate/certs/ca-chain.cert.pem"},
   {verify, verify_peer},
   {fail_if_no_peer_cert, true},
   {secure_renegotiate, true},
   {depth, 1}
   ]},
 {client,
  [{secure_renegotiate, true},
   {certfile, "cert/ca/intermediate/certs/client.cert.pem"},
   {keyfile, "cert/ca/intermediate/private/client.key.pem"},
   {depth, 1},
   {cacertfile, "cert/ca/intermediate/certs/ca-chain.cert.pem"}
  ]}].
```

My CA chain: RootCA -> IntermediateCA

Then I signed the aerone.com.cn.cert.pem (the cert at server side) and the client.cert.pem (the cert at client side) using the IntermediateCA. These two certificates are both have no passphrase.

The file 'cert/ca/intermediate/certs/ca-chain.cert.pem' contains both the CA certificates at following order: IntermediateCA, RootCA.

**Comment by FartParty** [comment]
Hi @terry-xiaoyu, I ended up giving up on this and moving to terminating SSL with an nginx reverse proxy using `stream`.  In addition to modifying depth, I would need the ability to authorize a specific issuer that I'm looking for - I didn't see any options for that in the emqttd config.

In the end, I have to satisfy two conditions:
1. Authentication (client cert)
2. Authorization (check issuer DN, reject if not correct)

My `ssl_dist.conf` was this:
```
[{server,
  [{certfile, "certs/server/mqtt.pem"},
   {keyfile, "certs/server/mqtt.key"},
   {cacertfile, "certs/server/chain.pem"},
   {verify, verify_peer},
   {fail_if_no_peer_cert, true},
   {secure_renegotiate, true},
   {depth, 3}
   ]},
 {client,
  [{secure_renegotiate, true},
   {depth, 3},
   {cacertfile, "certs/server/chain.pem"}
  ]}].
```

**Comment by FartParty** [comment]
My nginx proxy config is as follows:
```
user  nginx;
    worker_processes  1;

    error_log  /dev/stdout info;
    pid        /var/run/nginx.pid;

    events {
        worker_connections  1024;
    }

    stream {

      # replace the CN= with the issuer you want to filter on
      map $ssl_client_i_dn $allowed_client {
          CN=[redacted] emqttd;
          CN=[redacted] emqttd;
          default failconn;
      }

      log_format basic '$remote_addr [$time_local] '
                 '$protocol $status $bytes_sent $bytes_received '
                 '$session_time';

      upstream emqttd {
        server 127.0.0.1:1883;
      }

      # make sure to use a port that isn't actually lisetening!
      upstream failconn {
        server 127.0.0.1:7777;
      }

      server {
          listen 9999 ssl;
          tcp_nodelay on;

          # map these into the nginx container using a volume secret
          ssl_certificate       /etc/nginx/ssl/tls.crt;
          ssl_certificate_key   /etc/nginx/ssl/tls.key;
          ssl_trusted_certificate /etc/nginx/ssl/CA/ca.pem;
          ssl_client_certificate /etc/nginx/ssl/CA/ca.pem;
          ssl_verify_client on;
          ssl_verify_depth 3;

          ssl_protocols TLSv1.2;
          ssl_ciphers 'ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256';
          ssl_prefer_server_ciphers on;

          ssl_session_cache shared:SSL:20m;

          error_log /dev/stdout info;
          access_log /dev/stdout basic;

          proxy_protocol on;
          proxy_pass $allowed_client;
       }
    }
```

This could probably be done better if I actually had something that rejected sessions listening on 7777 or something, but the end result is that a connection refused ends in a session that immediately terminates even though it passed a depth check.
