### ISSUE TITLE
Ekka connecting nodes with different cluster names...

### ISSUE THREAD

**Issue by PiedPieper** [emqx/emqx#1554]
I am trying to use multicast to connect my EMQ nodes, but it seems that the cluster name is not being checked. 

Here is my emqtt running on a box w/ ip address 192.168.1.97: 

> (EMQ@192.168.1.97)1> application:get_all_env(ekka).
> [{cluster_discovery,{manual,[]}},
>  {included_applications,[]},
>  {{callback,prepare},#Fun<emqttd.shutdown.1>},
>  **{cluster_name,emq97},**
>  {{callback,reboot},#Fun<emqttd.reboot.0>},
>  {cluster_autoclean,300000},
>  {cluster_autoheal,true}]

and here it is for my other EMQ:

> 
> (EMQ@192.168.1.101)1> 10:21:01.547 [info] Ekka(Membership): Node EMQ@192.168.1.97 up
> 10:21:01.572 [info] Ekka(Membership): Mnesia EMQ@192.168.1.97 up
> 
> (EMQ@192.168.1.101)1> application:get_all_env(ekka).
> [{cluster_discovery,{mcast,[{addr,{239,192,0,1}},
>                             {ports,[4369,4370]},
>                             {iface,{0,0,0,0}},
>                             {ttl,255},
>                             {loop,true}]}},
>  {{callback,reboot},#Fun<emqttd.reboot.0>},
>  {included_applications,[]},
>  **{cluster_name,emqcl},**
>  {{callback,prepare},#Fun<emqttd.shutdown.1>},
>  {cluster_autoclean,300000},
>  {cluster_autoheal,true}]
> (EMQ@192.168.1.101)2> 

It seems that the second box is connecting to the first, ignoring that the cluster names are different.

As additional info, we are using distributed ssl to connect the nodes. We just don't know how to prevent them from linking up...

Thanks for your time!

**Comment by emqplus** [comment]
@PiedPieper The `cluster.name` is not ignored in the current implementation. I will plan the feature in 0.3 release.

**Comment by zhengyupan** [comment]
@PiedPieper this is implemented in EMQ X 3.0-beta3, please check if it meets your requirement.
