### ISSUE TITLE
User With wrong username and password are also connecting to broker Even though Auth_Mongo Plugin is enabled

### ISSUE THREAD

**Issue by arihantdaga** [emqx/emqx#1555]
#### Environment

- OS: 
CentOs
- Erlang/OTP: 
- EMQ: 
2.3.4

#### Description

I have enabled Auth Mongo Plugin. But still users with any username and password combinations are connecting to the broker. 
This is what i have in my acl.conf

```
{allow, {user, "dashboard"}, subscribe, ["$SYS/#"]}.

{allow, {ipaddr, "127.0.0.1"}, pubsub, ["$SYS/#", "#"]}.

{deny, all, subscribe, ["$SYS/#", {eq, "#"}]}.
```
And in my emq_auth_mongo.conf - 
```
auth.mongo.acl_query = on

auth.mongo.acl_query.collection = mqtt_user

auth.mongo.acl_query.selector = username=%u

```

Am i doing something wrong ? Or is it the intended behaviour ? Can i restrict somehow all users who are not existing in my database from connecting to the broker.

**Comment by terry-xiaoyu** [comment]
@arihantdaga I believe what you want is `auth`, not `acl`. That is, you should configure the `auth.mongo.auth_query.collection`, not `auth.mongo.acl_query.collection`. See the doc [here](https://github.com/emqtt/emq-auth-mongo#mqtt_user-collection).

Access Control List (ACL) is only for denying/allowing PUBLISH/SUBSCRIBE a specific topic or a topic collection, and it has noting to do with the CONNECT.
 
BTW, don't forget to change the `mqtt.allow_anonymous` to `false` in etc/emq.conf.

**Comment by arihantdaga** [comment]
@terry-xiaoyu Thank you. But i already have that configured, I did not post my complete config up there but this is what i have in my authentication section 

```
## Authentication query.
auth.mongo.auth_query.collection = mqtt_user

auth.mongo.auth_query.password_field = password


```
