### ISSUE TITLE
Does emqtt support token authentication?

### ISSUE THREAD

**Issue by qwyinxiang** [emqx/emqx#1556]
#### Environment
 Qt version 4.2.0 on Window7 64bit.

#### Description
I create a mqtt client, the mqtt server need token authentication as username, My code is below like this:
client = new QMQTT::Client(QHostAddress(strHost), mqttPort);
client->setUsername(strAccessToken);
client->setKeepAlive(60);
client->connectToHost();
then, my program crashed.
But when I connect to a host without token authentication, my program is running well.
so, I want to know, if the emqtt client support token authentication?

**Comment by qwyinxiang** [comment]
Sorry，I express incorrect, I want to know does the mqtt client support token authentication? not the broker.
My broker need token authentication as username, but I don't know how to config the mqtt client?
when I set my client as "client->setUsername(strAccessToken);", my program crashed?

**Comment by terry-xiaoyu** [comment]
@qwyinxiang MQTT client don't support the authentication itself, it depends on the auth functionalities provided by the auth plugins (e.g. [emq-auth-mysql](https://github.com/emqtt/emq-auth-mysql)).

If you're using EMQ broker, you `MUST` provided the the password along with the username in the MQTT CONNECT message. In your case the password should be the JWT.

If you have any problem with regards to the `qmqtt`, please open an issue at https://github.com/emqtt/qmqtt.
