### ISSUE TITLE
How can i use SSL/TLS certificate based client authentication ?

### ISSUE THREAD

**Issue by rahulfk** [emqx/emqx#1557]
#### Environment

- OS: All
- Erlang/OTP: R20+
- EMQ: 2.3+

#### Description

I can see SSL/TLS certificate-based client authentication was released in v2.3.2 version but couldn't find any doc on how to use it.

can someone please provide any pointers??

**Comment by Gilbert-Wong** [comment]
You can refer this link <https://medium.com/@emqtt/securing-emq-connections-with-ssl-432672ab9f06>

**Comment by t2wu** [comment]
The linked page no longer exists, any new information?

**Comment by zmstone** [comment]
hi @t2wu there is a new article in the same topic: https://www.emqx.com/en/blog/enable-two-way-ssl-for-emqx

**Comment by t2wu** [comment]
@zmstone Thanks. Sorry for me being obtuse. Maybe I'm Googling for the wrong term. I currently have password-based authentication for user in Postgres (the mqtt_user table). I want the client to connect using certificate, and authenticate the user in the process. Is that possible?

I think I may have read somewhere that the Common Name of the client's certificate should match the username in the mqtt_user table, but I am not table to find the information anymore. Any pointer is appreciated, thank you.

**Comment by zmstone** [comment]
hi @t2wu i believe this is what you are looking for 
https://docs.emqx.io/en/broker/v4.3/configuration/configuration.html#listener-tcp-external-peer-cert-as-username

**Comment by t2wu** [comment]
@zmstone Thank you so much. This may be just what I'm looking for.
