### ISSUE TITLE
Feature Request - send only once for overlapped subscriptions

### ISSUE THREAD

**Issue by Zhang-Xianglong** [emqx/emqx#1560]
#### Environment

- OS: CentOS 6.9
- Erlang/OTP: 
- EMQ: emqttd 2.2

#### Description

*A description of the issue*

MQTT-3.3.5-1
> When Clients make subscriptions with Topic Filters that include wildcards, it is possible for a Client’s subscriptions to overlap so that a published message might match multiple filters. In this case the Server MUST deliver the message to the Client respecting the maximum QoS of all the matching subscriptions [MQTT-3.3.5-1]. In addition, the Server ***MAY*** deliver further copies of the message, one for each additional matching subscription and respecting the subscription’s QoS in each case.

The standard uses MAY. I used the emqttd 2.2 version test and found that the client received duplicate messages when matching multiple topic filters. Is it possible to configure this feature to disable and just sending a matching message with the highest QoS?

**Comment by Zhang-Xianglong** [comment]
why not fix this?

**Comment by Zhang-Xianglong** [comment]
why not fix this? @terry-xiaoyu @Gilbert-Wong

**Comment by Gilbert-Wong** [comment]
You should design your topic filter yourself to control this or contact @zhengyupan for further support in enterprise edition of emqx.

**Comment by hmonadjem** [comment]
For me, this happens even if all subscriptions have the same QoS, if so then its a bug. Correct?

**Comment by Zhang-Xianglong** [comment]
@hmonadjem I guess the message which you want matches multiple topic filters. From the author's reply, it's not a bug because of [MQTT-3.3.5-1] is not a mandatory standard, it probably is internal implementation logic. And it has nothing to do with the QoS.
