### ISSUE TITLE
EMQ Websocket issues with mqttjs

### ISSUE THREAD

**Issue by spydmobile** [emqx/emqx#1563]
#### Environment

- OS: centos7
- Erlang/OTP:  
- EMQ: 2.3.6

#### Description

*A description of the issue*
When connecting from the browser with the mqtt library, it seems there is some kind of websocket issue, while this may not be caused by EMQ it happens only with EMQ, we have an open issue over in the mqttjs project.
https://github.com/mqttjs/MQTT.js/issues/785

**Comment by spydmobile** [comment]
it would seem that this combo produces an extra get request which causes emq to return a 404 error. switching clients solves the issue but it would be nice for this to just work....

**Comment by terry-xiaoyu** [comment]
Hi, your path is not correct, use `mqtt.connect('ws://127.0.0.1:8083/mqtt')` instead.

The web-socket listen path will be able to configured in the future version, see https://github.com/emqtt/emqttd/pull/1537
