### ISSUE TITLE
too many time_wait connections and high CPU usage after disabling "net.ipv4.tcp_tw_recycle"

### ISSUE THREAD

**Issue by bhzhu203** [emqx/emqx#1566]
#### Environment
emqttd 2.1.2

- OS:     CentOS release 6.8  with linux kernel 4.15.15 /google BBR enabled
- Erlang/OTP: emqttd 2.1.2
- EMQ: emqttd 2.1.2

#### Description

too many time_wait connections and high CPU usage after disabling "net.ipv4.tcp_tw_recycle"
frp (fatedier/frp in github ) service connect to emqtt,showing like that

netstat -n | grep TIME_WAIT
tcp        0      0 127.0.0.1:53168             127.0.0.1:1883              TIME_WAIT   
tcp        0      0 127.0.0.1:53412             127.0.0.1:1883              TIME_WAIT   
tcp        0      0 127.0.0.1:53054             127.0.0.1:1883              TIME_WAIT   
tcp        0      0 127.0.0.1:53194             127.0.0.1:1883              TIME_WAIT   
tcp        0      0 127.0.0.1:52952             127.0.0.1:1883              TIME_WAIT   
tcp        0      0 127.0.0.1:53120             127.0.0.1:1883              TIME_WAIT   
tcp        0      0 127.0.0.1:53052             127.0.0.1:1883              TIME_WAIT   
tcp        0      0 127.0.0.1:53192             127.0.0.1:1883              TIME_WAIT   
tcp        0      0 127.0.0.1:53222             127.0.0.1:1883              TIME_WAIT   
tcp        0      0 127.0.0.1:53164             127.0.0.1:1883              TIME_WAIT   
tcp        0      0 127.0.0.1:52912             127.0.0.1:1883              TIME_WAIT   
tcp        0      0 127.0.0.1:52942             127.0.0.1:1883              TIME_WAIT   
tcp        0      0 127.0.0.1:53090             127.0.0.1:1883              TIME_WAIT   
tcp        0      0 127.0.0.1:53300             127.0.0.1:1883              TIME_WAIT   
tcp        0      0 127.0.0.1:53372             127.0.0.1:1883              TIME_WAIT   
tcp        0      0 127.0.0.1:53198             127.0.0.1:1883              TIME_WAIT   
tcp        0      0 127.0.0.1:53224             127.0.0.1:1883              TIME_WAIT   
tcp        0      0 127.0.0.1:53330             127.0.0.1:1883              TIME_WAIT   
tcp        0      0 127.0.0.1:53386             127.0.0.1:1883              TIME_WAIT   
tcp        0      0 127.0.0.1:52950             127.0.0.1:1883              TIME_WAIT   
tcp        0      0 127.0.0.1:53292             127.0.0.1:1883              TIME_WAIT   
tcp        0      0 127.0.0.1:53268             127.0.0.1:1883              TIME_WAIT   
tcp        0      0 127.0.0.1:53088             127.0.0.1:1883              TIME_WAIT   
tcp        0      0 127.0.0.1:52984             127.0.0.1:1883              TIME_WAIT   
tcp        0      0 127.0.0.1:53190             127.0.0.1:1883              TIME_WAIT   
tcp        0      0 127.0.0.1:53332             127.0.0.1:1883              TIME_WAIT   
tcp        0      0 127.0.0.1:53122             127.0.0.1:1883              TIME_WAIT   
tcp        0      0 127.0.0.1:53130             127.0.0.1:1883              TIME_WAIT   
tcp        0      0 127.0.0.1:53026             127.0.0.1:1883              TIME_WAIT   

.......100+  TIME_WAIT connetions

before disabling "net.ipv4.tcp_tw_recycle"  ,the CPU usage quite low and  excellent performance

**Comment by terry-xiaoyu** [comment]
@bhzhu203 any update of this problem?

**Comment by bhzhu203** [comment]
I finally find out not the "TIME_WAIT" problem.

emqttd have  a quite  high CPU usage and less memory uage .
Only having about 300 clients  (about  400~  ESTABLISHED connection)  ,there is 20% CPU usage and 10% sys CPU, 1.3 load . When we have about 800 clients ,it is showing that 85% CPU usage and 15% sys CPU, 3.8 load  in 4 core 8G machine (aliyun-network-performace-instance).

I  think there are some emqtt performance issues.Because our other project using emqtt in  1000~  ESTABLISHED connections only loads on 1 Core 1GB machine  of 0.3 load.

**Comment by terry-xiaoyu** [comment]
@bhzhu203 

What's is the current throughput?

How many subscribers do you have? And what kind of topic the subscribers are subscribed to?

**Comment by bhzhu203** [comment]
![_2018-04-28t12-01-26 892z](https://user-images.githubusercontent.com/3523160/39396339-06cccd24-4b1f-11e8-82a7-979bfdb5624f.png)


This project is a realtime comunication game program between teachers and students in international network.

**Comment by bhzhu203** [comment]
Do you talk about disk IO?  As you see ,the 'wa'  in the top command is 0%.I think it is network IO.

We run the EMQTT on Alicould machines which may use virtio network drivers. Is there any problem in virtio?

**Comment by bhzhu203** [comment]
Yes , I also find that EMQTT has  performance decline in multicore CPUs machine .
![_278](https://user-images.githubusercontent.com/3523160/39995506-fe243440-57ae-11e8-8b7f-fa4c25fa0708.jpg)

**Comment by Gilbert-Wong** [comment]
It is the `smp option` of erlang vm which is used to take advantage of multi-processor hardware architectures causing the performance decline. It is inevitable. EMQX 3.0.1 release would have a better performance.
