### ISSUE TITLE
Messages Published via HTTP REST are getting dropped 

### ISSUE THREAD

**Issue by dramasamy** [emqx/emqx#1571]
#### Environment

- OS: Ubuntu 16 
- Erlang/OTP: R19/8.3
- EMQ: 2.2 Stable 

#### Description

The publish is successful, but the message is dropped. 

dropped | 28

curl -v --basic -u test:test -d "qos=1&retain=0&topic=/a/b/c&message=hello from http..." -k http://x.x.x.x:8080/mqtt/publish
*   Trying x.x.x.x...
* Connected to x.x.x.x (x.x.x.x) port 8080 (#0)
* Server auth using Basic with user 'test'
> POST /mqtt/publish HTTP/1.1
> Host: x.x.x.x:8080
> Authorization: Basic dGVzdDp0ZXN0
> User-Agent: curl/7.49.0
> Accept: */*
> Content-Length: 54
> Content-Type: application/x-www-form-urlencoded
> 
* upload completely sent off: 54 out of 54 bytes
< HTTP/1.1 200 OK
< Server: MochiWeb/1.0 (Any of you quaids got a smint?)
< Date: Fri, 20 Apr 2018 04:22:03 GMT
< Content-Type: text/plain
< Content-Length: 2
< 
* Connection #0 to host x.x.x.x left intact

**Comment by terry-xiaoyu** [comment]
Hi, do you have any clients subscribed the topic `/a/b/c`? Are the subscribers able to receive the messages your published via HTTP?

If no subscribers, the message will be marked as`dropped`.

**Comment by dramasamy** [comment]
Hi Terry-xiaoyu, Thanks a lot. But is it possible to persist the message without the subscription and later subscribe and get te data?

**Comment by terry-xiaoyu** [comment]
It depends on your requirement. If you want update online status of your device, you could utilize the "retain" flag in the PUBLISH message header. 

https://www.hivemq.com/blog/mqtt-essentials-part-8-retained-messages

But that way only the last message will be retained. If you need to retain all of the messages, write your own plugins.

http://emqtt.io/docs/v2/plugins.html#plugin-development-guide
