### ISSUE TITLE
Not able to Join Cluster

### ISSUE THREAD

**Issue by arihantdaga** [emqx/emqx#1576]
#### Environment

- OS: 
CentOs 7
- Erlang/OTP: 
- EMQ: 
2.3.7

I am having difficulty in creating emq cluster. 
I followed this - http://emqtt.io/docs/v2/cluster.html.
Tried both manual and static  discovery. 
Fixed firewall - allowed port 4369 on both machines.
Added following snippet in `/releases/2.3.7/emqttd.script` in both machines. 

```
{inet_dist_listen_min, 20000},
{inet_dist_listen_max, 21000}
```
Restarted brokers using `./bin/emqttd restart`
I kept `node.name = emq2@PUBLIC_IP_OF_Machine_2` on Machine 2
I kept `node.name = emq1@PUBLIC_IP_OF_Machine_1` on Machine 1

Still when i run ` ./bin/emqttd_ctl cluster join emq2@PUBLIC_IP_OF_Machine_2` I get following error

`Failed to join the cluster: {node_down,'emq2@PUBLIC_IP_OF_Machine_2'}
`
Still when i run this command from one of my nodes. Can someone help me about what can be wrong here.

**Comment by arihantdaga** [comment]
@terry-xiaoyu Yes, The issue is with firewall, Once i disable it on one of the machine and did cluster join form another, it joined the cluster successfully. But once again if i enable my firewall it's not working. 
I even enabled this port range on my firewall. What else can i set in my firewall to make it work. 


```
18083/tcp                  ALLOW       Anywhere                  
4369                       ALLOW       Anywhere                  
20000:21000/tcp            ALLOW       Anywhere                  
18083/tcp (v6)             ALLOW       Anywhere (v6)             
4369 (v6)                  ALLOW       Anywhere (v6)             
20000:21000/tcp (v6)       ALLOW       Anywhere (v6)  

```
This is my current firewall status, which is not working. Can u suggest whats wrong by looking at it..

**Comment by terry-xiaoyu** [comment]
@arihantdaga

I'm sorry, the document is outdated. We'll update it soon.

Look for the following configs in etc/emq.conf:
```
node.dist_listen_min = 6369
node.dist_listen_max = 6379
```
That's the range of distributed ports, so you should allow this port range: 6369 ~ 6379.

**Comment by arihantdaga** [comment]
Ok.. @terry-xiaoyu Thank you. It worked..
