### ISSUE TITLE
anonymous authentication in combination with LDAP

### ISSUE THREAD

**Issue by victorclaessen** [emqx/emqx#1577]
#### Environment

- OS: Debian 9
- Erlang/OTP: 29/9.0
- EMQ: 2.3.6

#### Description

When I enable the LDAP plugin, anonymous access is no longer permitted, even though `mqtt.allow_anonymous = true` is set in emq.conf.

I would like to use the ACL to attain the following situation: Anonymous users will have only basic permissions (mainly subscribing). If users make a succesful LDAP authentication, they gain more rights (publishing).

Is it possible to configure emqtt like this?

**Comment by turtleDeng** [comment]
@victorclaessen emqttd 3.0 will support LDAP ACL.

**Comment by victorclaessen** [comment]
That is great news, but I'm not sure that that is the solution.

In the meantime I have been playing with the MySQL plugin, that already has _auth_ **and** _acl_ functions. But when I enable the MySQL plugin, the same problem occurs, _i.e._ anonymous connection is no longer possible.

I was thinking to rewrite the MySQL statements so that a blank username would also pass the authentication test, but I found out that emqttd doesn't even execute the query when no username is supplied by the client, so that didn't work.

**Comment by victorclaessen** [comment]
Perhaps I don't really see the rationale behind the `mqtt.allow_anonymous` configuration item. Because apparently that doesn't mean anything anymore whenever any authentication plugin is enabled, is that right?

**Comment by terry-xiaoyu** [comment]
@victorclaessen Hi, I think you are right. `mqtt.allow_anonymous` need to allow empty username login or we should simply delete this configuration.

**Comment by victorclaessen** [comment]
Hi @terry-xiaoyu,

The first option (to allow empty username login when `mqtt.allow_anonymous = true`) has my distinct preference 😄 .

**Comment by victorclaessen** [comment]
@terry-xiaoyu Have you guys given this some more thought?

**Comment by michael-c-jones** [comment]
@terry-xiaoyu this is also a requirement for my project, is this something that can be done ?  Either now or in the future ?

**Comment by Gilbert-Wong** [comment]
Hi, @michael-c-jones , this feature has been implemented in emqx enterprise edition., if you want to integrate this in your project, please contact with @zhengyupan for further information.

**Comment by victorclaessen** [comment]
Hi, @zhengyupan. I am also (still) interested in this feature. Can you tell us how to integrate this?

**Comment by Gilbert-Wong** [comment]
The ldap auth plugin has been implemented in emqx3.0.0 release, however, we have no schedule to implement the feature that do acl check for anonymous user in open source edition of emqx. Sorry, @victorclaessen .
