### ISSUE TITLE
emqttd mongo plugin how to set authentication database？

### ISSUE THREAD

**Issue by chxiaowu** [emqx/emqx#1578]
#### Environment

- OS: CentOS 7.2
- Erlang/OTP: 29/9.0
- EMQ: 2.3.6

#### Description

I am struggling with emq_auth_mongo to connect to MongoDB.

In my case, I'm using the MongoDB service provided by Tencent Cloud, and the connection URI looks like this: `mongodb://username:password@IP:27017/somedb?authSource=admin`

As you can see an extra option "authSource=admin" is needed.

My question is, how can we set the connection option "authSource=admin" in the emq_auth_mongo.conf?

And even further, could EMQ support connecting to MongoDB using URI?

**Comment by terry-xiaoyu** [comment]
The `authSource` is not supported right now. 

For now, you have to make sure the db of your Users/ACL collection is also the `authentication database`. In the [README's example](https://github.com/emqtt/emq-auth-mongo/blob/master/README.md), use `mqtt` as the authentication database.

We're planning to support the `Connection String URI Format`, maybe in EMQ R3.0.
