### ISSUE TITLE
Default EMQ certs overriding our custom certs?

### ISSUE THREAD

**Issue by erifghjkk** [emqx/emqx#1579]
More than likely an error in the way we are configuring our emq.conf. However, we would like confirmation.

### Environment
EMQ version 2.3.7

### Expected behavior
We would like our broker's custom certificates to be used for SSL (specifically restricted to TLS v1.2).

### Actual behavior
The default EMQ certs from etc/certs are used for SSL validation, instead of our certs.

Also, a note about the default certs, it appears that traffic is not being restricted to TLSv1.2 - openssl requests from TLSv1.0 and TLSv1.1 are accepted by the default certs. Since we don't want this happening for our custom certs, we'd like to determine if we have a configuration mistake that is allowing TLSv1.0 and TLSv1.1 (as this would be a serious security flaw).

See attached **emq.conf** - Section _MQTT/SSL - External SSL Listener for MQTT Protocol_
[emq.conf.txt](https://github.com/emqtt/emqttd/files/1955691/emq.conf.txt)

### Test code
Should be able to complete handshake with custom certificates created thusly:
```
openssl genrsa -des3 -out ca-key.pem 4096
openssl req -new -x509 -days 365 -key ca-key.pem -out ca-cert.pem
openssl genrsa -des3 -out server-key.pem 1024
openssl req -new -key server-key.pem -out server.csr
openssl x509 -req -days 365 -in server.csr -CA ca-cert.pem -CAkey ca-key.pem -set_serial 01 -out server-cert.pem
openssl genrsa -des3 -out client-key.pem 1024
openssl req -new -key client-key.pem -out client.csr
openssl x509 -req -days 365 -in client.csr -CA ca-cert.pem -CAkey ca-key.pem -set_serial 01 -out client-cert.pem
```

Openssl dummy client code to test whether certs work or not:
```bash
openssl s_client -tls1_2 -connect XX.XX.XX.XX:8883 -cert client-cert.pem -key client-key.pem -CAfile ca-cert.pem -state -debug
```

**Comment by terry-xiaoyu** [comment]
I'll check your configuration later, thanks.

**Comment by erifghjkk** [comment]
Here are all the active/uncommented lines within the config file:

cluster.name = `emqcl1` # Our custom cluster name
cluster.discovery = manual
cluster.autoheal = on
cluster.autoclean = 5m
node.name = `dev1@XX.X.X.X` # Local IP from Azure vnet
node.cookie = emqsecretcookie
node.smp = auto
node.kernel_poll = on
node.async_threads = 32
node.process_limit = 256000
node.max_ports = 65536
node.dist_buffer_size = 8MB
node.max_ets_tables = 256000
node.fullsweep_after = 1000
node.crash_dump = log/crash.dump
node.proto_dist = inet_tcp
node.dist_net_ticktime = 60
node.dist_listen_min = 6369
node.dist_listen_max = 6379
log.dir = log
log.console = console
log.console.level = error
log.error.file = log/error.log
log.error.size = 10485760
log.error.count = 5
log.crash = on
log.crash.file = log/crash.log
log.syslog = on
log.syslog.level = error
mqtt.allow_anonymous = true
mqtt.acl_nomatch = allow
mqtt.acl_file = etc/acl.conf
mqtt.cache_acl = true
mqtt.max_clientid_len = 1024
mqtt.max_packet_size = 64KB
mqtt.websocket_protocol_header = on
mqtt.keepalive_backoff = 0.75
mqtt.conn.force_gc_count = 100
mqtt.client.idle_timeout = 30s
mqtt.client.enable_stats = off
mqtt.session.max_subscriptions = 0
mqtt.session.upgrade_qos = off
mqtt.session.max_inflight = 32
mqtt.session.retry_interval = 20s
mqtt.session.max_awaiting_rel = 1000
mqtt.session.await_rel_timeout = 30s
mqtt.session.enable_stats = on
mqtt.session.expiry_interval = 2h
mqtt.session.ignore_loop_deliver = false
mqtt.mqueue.type = simple
mqtt.mqueue.max_length = 1000
mqtt.mqueue.low_watermark = 20%
mqtt.mqueue.high_watermark = 60%
mqtt.mqueue.store_qos0 = true
mqtt.broker.sys_interval = 1m
mqtt.pubsub.pool_size = 8
mqtt.pubsub.async = true
mqtt.bridge.max_queue_len = 10000
mqtt.bridge.ping_down_interval = 1s
mqtt.plugins.etc_dir =etc/plugins/
mqtt.plugins.loaded_file = data/loaded_plugins
listener.tcp.external = 0.0.0.0:1883
listener.tcp.external.acceptors = 16
listener.tcp.external.max_clients = 102400
listener.tcp.external.access.1 = allow all
listener.tcp.external.backlog = 1024
listener.tcp.external.send_timeout = 15s
listener.tcp.external.send_timeout_close = on
listener.tcp.external.nodelay = true
listener.tcp.external.reuseaddr = true
listener.tcp.internal = 127.0.0.1:11883
listener.tcp.internal.acceptors = 4
listener.tcp.internal.max_clients = 102400
listener.tcp.internal.backlog = 512
listener.tcp.internal.send_timeout = 5s
listener.tcp.external.send_timeout_close = on
listener.tcp.internal.nodelay = false
listener.tcp.internal.reuseaddr = true
listener.ssl.external = 8883
listener.ssl.external.acceptors = 16
listener.ssl.external.max_clients = 1024
listener.ssl.external.access.1 = allow all
listener.ssl.external.tls_versions = `tlsv1.2` # We would like to restrict traffic to TLSv1.2
listener.ssl.external.handshake_timeout = 15s
listener.ssl.external.keyfile = `etc/version1/server-key.pem` # Our password-protected server key, des3 encrypted - Note, an unencrypted no-password server key called `serverkeynopass.pem` has also been tried without success
listener.ssl.external.certfile = `etc/version1/server-cert.pem` # Our custom server certificate
listener.ssl.external.cacertfile = `etc/version1/ca-cert.pem` # Our custom self-signed CA certificate
listener.ssl.external.verify = `verify_peer` # Disabled by default but we enable
listener.ssl.external.fail_if_no_peer_cert = `true` # Disabled by default but we enable
listener.ssl.external.reuseaddr = true
listener.ws.external = 8083
listener.ws.external.acceptors = 4
listener.ws.external.max_clients = 102400
listener.ws.external.access.1 = allow all
listener.ws.external.backlog = 1024
listener.ws.external.send_timeout = 15s
listener.ws.external.send_timeout_close = on
listener.ws.external.nodelay = true
listener.ws.external.reuseaddr = true
listener.wss.external = 8084
listener.wss.external.acceptors = 4
listener.wss.external.max_clients = 64
listener.wss.external.access.1 = allow all
listener.wss.external.tls_versions = tlsv1.2,tlsv1.1,tlsv1
listener.wss.external.handshake_timeout = 15s
listener.wss.external.keyfile = etc/certs/key.pem
listener.wss.external.certfile = etc/certs/cert.pem
listener.wss.external.cacertfile = etc/certs/cacert.pem
listener.wss.external.verify = verify_peer
listener.wss.external.fail_if_no_peer_cert = true
listener.wss.external.backlog = 1024
listener.wss.external.send_timeout = 15s
listener.wss.external.send_timeout_close = on
listener.wss.external.reuseaddr = true
listener.api.mgmt = 0.0.0.0:8080
listener.api.mgmt.acceptors = 4
listener.api.mgmt.max_clients = 64
listener.api.mgmt.access.1 = allow all
listener.api.mgmt.backlog = 512
listener.api.mgmt.send_timeout = 15s
listener.api.mgmt.send_timeout_close = on
sysmon.long_gc = false
sysmon.long_schedule = 240
sysmon.large_heap = 8MB
sysmon.busy_port = false
sysmon.busy_dist_port = true

The EMQ config specifies a server key, but this password is never required or prompted by emqttd. We tested using server key without a password yet our client still has same problem connecting to this EMQ broker. (However, our client connects to an HAProxy server using the same CA cert.)

Thanks

**Comment by petergerten** [comment]
@erifghjkk did you also change the path in /emqx/etc/ssl_dist.conf?
