### ISSUE TITLE
Hook function can not stop message deliverd

### ISSUE THREAD

**Issue by solomonwzs** [emqx/emqx#1580]
#### Environment

- OS: 
- Erlang/OTP: 
- EMQ: 

#### Description

I try to write a plugin to control the message publish and delivered, so I register hook function: `message.publish` and `message.delivered`.

But I found it can not stop message deliverd even though it return `stop`, so I check the code `emqttd_protocol.erl` and found this:
 
```erlang
-spec(send(mqtt_message() | mqtt_packet(), proto_state()) -> {ok, proto_state()}).
send(Msg, State = #proto_state{client_id  = ClientId,
                               username   = Username,
                               mountpoint = MountPoint,
                               is_bridge  = IsBridge})
        when is_record(Msg, mqtt_message) ->
    emqttd_hooks:run('message.delivered', [ClientId, Username], Msg),
    send(emqttd_message:to_packet(unmount(MountPoint, clean_retain(IsBridge, Msg))), State);
```

It seem that it did not handle the hook function return. Are there any reason you design it like this, or am I missing something?

Thx.

**Comment by terry-xiaoyu** [comment]
Hook evens like `message.delivered` and `session.unsubscribed` are more like "Notify and forget it" than "Request and Wait for Response". It won't handle the reply of the hooked functions.

I'm happy with this design for now, and I would use `message.publish` to suppress the delivery of PUBLISH messages.

**Comment by solomonwzs** [comment]
My demand is, a client has subscribed a topic, but the admin want to prevent messages delivered to this client, or filter messages.

Do you have any suggestion to implement it?

Thx.

**Comment by terry-xiaoyu** [comment]
You could use ACL to prevent a client from publish/subscribe to specific topics.

Or you could filter only PUBLISH messages by hooking `message.publish` in your plugins. 

`message.delivered` will hook all of the MQTT message sent to the client, including the `PUBACK` and `PING` messages. I don't think you really want to stop theses kind of messages.

**Comment by solomonwzs** [comment]
Hi.

I mean the client has already subscribe the specific topics. For example, there are some people in a chat room, and I want to kick someone out of the room, but I can not ensure the client unsubscribe the room topics, and also I can not interrupt the client connection because it maybe subscribe other topics, so I want to prevent the messages of this room topics delivered to this client.

Thx.

**Comment by enix223** [comment]
I got the same problem as yours, what I am trying to solve this problem is using web hook API to unsubscribe the topic after ACL rule is updated. 

For your case, when the group admin kick someone, and you will remove that user from ACL list, and you can also make a unsubscribe request through web API hook.

**Comment by terry-xiaoyu** [comment]
Use REST API of emqx to subscribe/unsubscribe topics for a client is the right approach. The related docs can be found [here](http://emqtt.io/docs/v3/rest.html#create-a-subscription)
