### ISSUE TITLE
Crashing when AuthMongo Plugin is active

### ISSUE THREAD

**Issue by arihantdaga** [emqx/emqx#1581]
#### Environment

- OS: 
CentOs
- Erlang/OTP: 
- EMQ: 
2.3.7

#### Description

While setting up auth mongo plugin i am getting this error. 

```
09:05:57.368 [error] gen_server <0.1448.0> terminated with reason: killed
09:05:57.368 [error] CRASH REPORT Process <0.1448.0> with 1 neighbours exited with reason: killed in gen_server:decode_msg/9 line 410
09:05:57.368 [error] gen_server <0.1443.0> terminated with reason: killed
09:05:57.369 [error] CRASH REPORT Process <0.1443.0> with 1 neighbours exited with reason: killed in gen_server:decode_msg/9 line 410

```

I don't understand from these message, the actual reason behind this. 
I am also attaching my emq_auth_mongo.conf  - 

```
auth.mongo.type = rs
auth.mongo.rs_set_name = rs0
auth.mongo.server = MY_PRIV_IP:MY_PORT
auth.mongo.pool = 8
auth.mongo.login = MY_USERNAME
auth.mongo.password = MY_PASSWORD
auth.mongo.database = mqtt
auth.mongo.w_mode = unsafe
auth.mongo.r_mode = slave_ok
auth.mongo.topology.pool_size = 1
auth.mongo.topology.max_overflow = 0
auth.mongo.auth_query.collection = mqtt_user
auth.mongo.auth_query.password_field = password
auth.mongo.auth_query.password_hash = plain
auth.mongo.auth_query.selector = username=%u
auth.mongo.super_query = on
auth.mongo.super_query.collection = mqtt_user
auth.mongo.super_query.super_field = is_superuser
auth.mongo.super_query.selector = username=%u
auth.mongo.acl_query = on
auth.mongo.acl_query.collection = mqtt_user
auth.mongo.acl_query.selector = username=%u
```

Can anybody also suggest me about how to configure this plugin with mongodb running with replica sets.

**Comment by terry-xiaoyu** [comment]
@arihantdaga Sorry for late rely due to Labor Day. I'm investigating this issue.

**Comment by terry-xiaoyu** [comment]
Would [this comment](https://github.com/emqtt/emq-auth-mongo/issues/88#issuecomment-385885465) work for you ?

**Comment by GiviMAD** [comment]
I'm facing the same error connecting to mongo running with -replSet option, with just one mongo instance. With mongo version 3.6.3 and emqtt version 2.3.8.

**Comment by terry-xiaoyu** [comment]
Hi, @GiviMAD 

What's the result of mongo command `db.isMaster().hosts` ? Is it same as what you've configured in `auth.mongo.server` ?

**Comment by GiviMAD** [comment]
no, I'm running in docker-compose, the mongo db real ip should be resolved from the container name.

**Comment by GiviMAD** [comment]
I was able to connect after consult the db.isMaster().hosts result and provide it to the auth.mongo.server config. But running in containers this is not an option it could change, auth.mongo.server should be able to resolve the host name from the dns I think
