### ISSUE TITLE
Windows 10 ... bat script hangs on first run

### ISSUE THREAD

**Issue by gfbaggio** [emqx/emqx#1582]
#### Environment

- OS: windows 10
- Erlang/OTP: latest
- EMQ: latest

#### Description

zip file downloaded amd copied on c:\
cd \emqttd
bin\emqttd console **** and script hangs there,nothing happens
if I crtl-C I get message
terminate batch job (Y/N) and if I click N the script continues and console shows and mqtt server works properly
I bin\emqttd stop  ===  it stops
I bin\emqttd console and console works without script hanging  ==== all work good

BUT if I restart computer the hanging stuff begins again ?????

am I the only one with this ??

thanks

**Comment by michaelcplusplus** [comment]
Same problem as #803

**Comment by gwnpeter** [comment]
i add some delay in bat file,and fix it.

:create_mnesia_dir
@set create_dir_cmd=%escript% %nodetool% mnesia_dir %data_dir%\mnesia %node_name%
@for /f "delims=" %%Z in ('%%create_dir_cmd%%') do @(
  set mnesia_dir=%%Z
  sleep.exe 500
)
@goto :eof

:generate_app_config
@set mergeconf_cmd=%escript% %nodetool% mergeconf %etc_dir%\emq.conf %etc_dir%\plugins %data_dir%\configs
@for /f %%Z in ('%%mergeconf_cmd%%') do @(
  set merged_app_conf=%%Z
  sleep.exe 500
)
@set gen_config_cmd=%escript% %cuttlefish% -s %rel_dir%\schema -c %merged_app_conf% -d %data_dir%\configs generate
@for /f "delims=" %%A in ('%%gen_config_cmd%%') do @(
  set generated_config_args=%%A
  sleep.exe 500
)

**Comment by gwnpeter** [comment]
me too,
it stop at  line :  @for /f "delims=" %%Z in ('%%create_dir_cmd%%') do @(

**Comment by Gilbert-Wong** [comment]
Sorry, The priority of emqttd release isn't high enough. I recommend you use it on linux or unix.

**Comment by Gilbert-Wong** [comment]
Hi, @gfbaggio  This bug has been fixed in emqx3.1 rc.1.
