### ISSUE TITLE
High messages per second configuration, growing memory footprint 

### ISSUE THREAD

**Issue by tpiecora** [emqx/emqx#1589]
#### Environment

- OS: AWS Linux (CentOS 7)
- Erlang/OTP: R20/9.0
- EMQ: 2.3.6
- Hardware: (3) t2.xlarge - 4 CPU, 16GB MEM

#### Description

I am trying to optimize my setup for higher throughput in terms of messages per second.  My clients are mostly transient and short-lived and not many concurrent connections (< 10k).  Clients only needs to receive messages if they are connected, so there is no need to queue messages or persist them.  In my current testing setup, connected clients is roughly equal to messages per second.  With a 3 node cluster, it seems to be able to handle ~1000 messages per second pretty well, with trip time from publisher to subscriber remaining consistently low (~10ms)
Once I start pushing the cluster beyond this, the latency seems to climb.  If I double the number of clients (and the messages per second, the system seems to settle in around 1500 ms average and spikes of +5000ms.  

One node in my cluster also seems to have an increasing memory footprint over time (after running for 24 hours, one node was was over 10GB while the other two were less than 200MB).

What settings would have an impact on this use case? 
What are reasonable expectations in terms of messages per second?
Can I expect that adding more nodes to the cluster will equate to more messages per second?
How can I address the growing memory footprint?

**Comment by terry-xiaoyu** [comment]
Hi, I want to know more about your benchmark so I can reproduce it and find the bottleneck myself.

Do you have a load balancer in front of your cluster? And how about the load weight on each node? Or you forwarded all the load to only one of the nodes?

And the pub/sub model: Does your client connect to the broker, and then subscribe its topic, then publish a message to that topic(thus sent to itself), and then disconnect?

What about the payload size?

Did you setup the clients in the same subnet as the cluster? If not, what's your system's bandwidth?

If you're using tsung or emqtt_benchmark, could you post your test configs/options here?

**Comment by tpiecora** [comment]
Yes, it has a load balancer with equal weighting across all nodes.

I have worker nodes that spawn child processes in pairs. Each child has its own account and ACL. They both subscribe to the same topic and then post messages via http to an API. That API then publishes the messages to the topic. Once 25 messages has been sent, both clients disconnect and exit, then the worker deletes their user accounts and ACLs.

Workers are running in ECS Fargate with each worker handling 100 pairs of child processes. They are in the same VPC and AZ.

Messages are not large. Average is around 1KB.

I am using MySQL Auth in RDS.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by tpiecora** [comment]
Any thoughts here?

**Comment by terry-xiaoyu** [comment]
*On the node which consumes the most memory*,

Try to inspect the vm memory usage by:
`./bin/emqttd_ctl vm all`

And you could also inspect the status of the broker by:
`./bin/emqttd_ctl broker stats`
`./bin/emqttd_ctl sessions list`

Since I suspect the memory is probably hold by an erlang process, I suggest you attach into erlang shell by:
`./bin/emqttd attach`

and then inspect the process status while your test is running using:
```
(emq@127.0.0.1)3> spawn(fun() -> etop:start([{output, text}, {interval, 1}, {lines, 20}, {sort, memory}]) end).
```

**`Ctl+D` to quit.**
