### ISSUE TITLE
Cluster deployment behind Haproxy

### ISSUE THREAD

**Issue by lhucinequr** [emqx/emqx#1593]
#### Description

Hello,
This is more of cluster deployment question than an issue
Can I deploy a cluster of 2 instances of emqttd behind an Haproxy load balancer.
I am worried that a netsplit would occur in the cluster and Haproxy would continue to send 
connections to both instances, in which case  messages would not be delivered across all the nodes
Is it safe to deploy a cluster in this configuration?
Would a netsplit result in one/both of the nodes not accepting connections?

**Comment by terry-xiaoyu** [comment]
It is not safe if your requirement is to stop all the connections in case of netsplit. You could test this scenario yourself to know better about how EMQ works.

**Comment by lhucinequr** [comment]
Thank you for the quick reply
Could you please give some recommendations for this case.
What I'm trying to achieve here is to avoid the situation where the cluster is in a netsplit situation but both nodes continue to accept the connections as if nothing has happened.
Would an odd number of nodes in the cluster help resolve the situation?

**Comment by lhucinequr** [comment]
Any news concerning this?

**Comment by terry-xiaoyu** [comment]
Hi,

HAProxy won't realize the net split between EMQ nodes, so it's hard to stop it from delivering messages to the "island node". 

It's complicated to choose a right subset of nodes and make them continue working, while shutdown other nodes. There's no plan to support this feature, and I'm very glad to listen your idea about this.

**Comment by lhucinequr** [comment]
Thank you for your reply.
I was thinking, every time there a "stateful" cluster(read shared state) there should be some sort of quorum notion behind it.
It does not seem to be the case for EMQTT.
An isolated node should never continue to accept clients when it knows that it is not in the majority.

**Comment by victorclaessen** [comment]
Perhaps you could monitor this periodically with a cronjob (check output of _emqttd_ctl cluster status_), and try to rejoin cluster, or if that fails, to kill the node and alert a sysadmin?

**Comment by utkarshns** [comment]
I have a similar setup, in my case there wont be any data loss but there will surely be problems with serving realtime data to clients.
It would be great if there emqtt cluster management allows for re-connection on such events.

**Comment by zhengyupan** [comment]
Hi all,
This discussion is not getting updates since a while...
Actually since last two release the emqx is able to detect a brain-split and can heal it automatically: the nodes in the minority will shutdown and start and then join the majority. The cluster should have an odd number of nodes to ensure there will always be a majority and a minority when netsplit happens.
