### ISSUE TITLE
Bridge to NATS Server

### ISSUE THREAD

**Issue by Think7** [emqx/emqx#1602]
Hello,

I would love the ability for EMQTT to relay messages sent from a NATS server:
- https://nats.io/documentation/server/gnatsd-intro/

There is an native Erlang NATS Client here
- https://nats.io/download/yuce/teacup_nats/

The data my application receives is broadcast using NATS while my entire infrastructure is built around the fantastic emqttd broker and the MQTT protocol.

NATS and MQTT are almost identical protocols with the exception of NAT's request-reply mechanism (which wouldn't even need to be be implemented).

Currently I've written a small bridge application to do this however it feels like a complete hack. Ideally emqttd should be the aggregator and authority of all incoming streaming data.

**Comment by haok316** [comment]
Is this feature added to the latest version? With the increasing popularity of NATS, this feature is very useful.

**Comment by theronic** [comment]
I would also love to bridge EMQX data to NATS Streaming, primarily so that I can replay history in reverse order (latest first) from NATS. I'm using MQTT purely for the light packet frame to the edge, whereas NATS Streams are comparatively fat.

**Comment by tigercl** [comment]
Hi, @Think7 
> I would love the ability for EMQTT to relay messages sent from a NATS server:
Do you want to reply the messages from NATS server to your devices by EMQTT or reply the messages from EMQTT to NATS server?

**Comment by zmstone** [comment]
closing it due to low activity.
to be fully transparent, unless coming from a paid customer, it's hard to motivate emqx-devs team to work on it.
