### ISSUE TITLE
Authentication using JWT and ACL with redis

### ISSUE THREAD

**Issue by bharat-mehta** [emqx/emqx#1603]
#### Environment

- OS:Ubuntu 
- Erlang/OTP: 
- EMQ: 2.3.7

#### Description

I need to confirm if I can do authentication using JWT plugin and set up the ACLs using redis plugin. If yes, can you please give an example with sample configuration. Thanks

**Comment by terry-xiaoyu** [comment]
Of course you can. 

For the JWT configurations please read the [README here](https://github.com/emqtt/emq-auth-jwt). And [this](https://github.com/emqtt/emq-auth-redis#acl-rule-hash) for ACL configuration via Redis.

The JWT should be straight forward.

Redis ACL example:
```
# this will setup ACL using the result of redis cmd 'HGETALL mqtt_acl:<username>' 
# where <username> is the username field got from the CONNECT MQTT message.
auth.redis.acl_cmd = HGETALL mqtt_acl:%u
```

In your emq.conf:
```
mqtt.acl_nomatch = deny
```

And put following ACL entries to your redis:
```
# ACL entries are Hash tables with following format: 
# <topic>  <acl_type>
# where `<acl_type>` is of integer values:  1 - subscribe, 2 - publish, 3 - pubsub
HSET  mqtt_acl:shawn   topic1     1
HSET  mqtt_acl:xiaoyu   topic2     2
```

With above configuration and ACL entries in redis, all clients with username = "shawn" will be allowed to subscribe the topic = 'topic1', and all clients with username = "xiaoyu" will be allowed to publish to topic "topic2". All other combinations will be denied as we have set the `mqtt.acl_nomatch` to *deny*. 

Hope this helps.

**Comment by bharat-mehta** [comment]
@terry-xiaoyu Thanks for your quick reply. I have done the same configuration which you mentioned. However the authentication is failing, are there any private claims required in JWT payload for emq

**Comment by bharat-mehta** [comment]
@terry-xiaoyu  Thanks for your input. The settings which you mentioned worked findI have one more question regarding ACLs in emq. Like I mentioned earlier, I am using redis for storing the acls. Does emq uses any caching when it comes to reading acls for clients. Can you please throw some light on how this caching works and what is the eviction logic.
