### ISSUE TITLE
How to restrict ClientId for a given User

### ISSUE THREAD

**Issue by vedavidhbudimuri** [emqx/emqx#1609]
How to restrict clientId for a given user (username and password)?

When do we use emq-auth-clientid and emq-auth-username? as we already have emq_auth_redis and other auth plugins. Am I missing something?

Is there is way to try out EMQX Enterprise I could I try out?

**Comment by terry-xiaoyu** [comment]
To restrict clientId of a specific username, the easiest way is to change [emq_auth_redis.erl#L43](https://github.com/emqtt/emq-auth-redis/blob/59e444fb72a45157ab27162cfa2e7370a818b6d6/src/emq_auth_redis.erl#L43 ) to make it also verifies your clientid.

To try EMQX, you could contact @zhengyupan
