### ISSUE TITLE
How do i debug the messages dropped in my emqtt nodes?

### ISSUE THREAD

**Issue by venks-warrior** [emqx/emqx#1610]
Environment

    OS: Linux
    Erlang/OTP: OTP
    EMQ: 2.2

Description

Hi ,

I am seeing messages dropped in emqtt broker nodes in cluster mode even when my consumer is up and running 24*7 as a streaming spark job.

Wanted help in debugging this kind of issues seen once in a month.Could not find anything from EMQTT node logs.

**Comment by terry-xiaoyu** [comment]
How did you find the drop? Via EMQ dashboard?

**Comment by venks-warrior** [comment]
From HTTP APIs of nodes.

**Comment by terry-xiaoyu** [comment]
You published a MQTT message but it was not delivered to the subscribers? If that is the case, turn on the debug level log, and check the message ID which was dropped.

**Comment by venks-warrior** [comment]
May i know in what all cases the drop of messages happen?How will message Ids help me in debugging?

**Comment by terry-xiaoyu** [comment]
You could get the entire message flow between EMQ and your devices, e.g. subscribe, suback, publish, puback, etc. And you could then check if the message have been delivered to your device, if you know the message id of the "dropped" message.





You should use QoS1 or even QoS2 if necessary if you are concern about the delivery quality.

**Comment by venks-warrior** [comment]
I am relatively new to EMQTT. How do i get the workflow of a message from message id assuming i have it?Could you help me?
