### ISSUE TITLE
Two different documentation for using Docker

### ISSUE THREAD

**Issue by yuridiniz** [emqx/emqx#1611]
**OS:** Windows

I'm starting with emqttd and I'm really enjoying it, but I had a big question about using the broker with Docker.

According to the site documentation ([link](http://emqtt.io/docs/v2/install.html#install-via-docker-image)), the installation is done by manually downloading the emqttd image, but README.md from the  repository [emq-docker](https://github.com/emqtt/emq-docker) are different instructions.

I was wondering what documentation to follow, and I'm also wondering why emqttd is not in the docker Hub, is there any intention to publish in the Docker Hub?

Thank you!

**Comment by terry-xiaoyu** [comment]
We're going to maintain a docker hub in the future, but not for now.

The doc is guiding you to download and run a image directly, but the readme doc is for building the image by yourself.

**Comment by terry-xiaoyu** [comment]
We're going to maintain a docker hub in the future, but not for now.

The doc is guiding you to download and run a image directly, while the readme doc is for building the image by yourself.

**Comment by yuridiniz** [comment]
Is there anything the community can do to help with the publishing process on the Docker Hub platform?

**Comment by terry-xiaoyu** [comment]
We'll maintain a docker hub from EMQ 3.0.

**Comment by RaymondMouthaan** [comment]
Maybe i can help you out by this link to my repo https://hub.docker.com/r/raymondmm/emqtt/

I've created a github project to build emq docker images for arm64, arm32v6 and arm64, all of these are manifest listed.

@terry-xiaoyu , I've you are interested, I would like to participate to make a official emq docker images.

**Comment by zhanghongtong** [comment]
@RaymondMouthaan  Thank you for your love, this is the address of our [docker hub](https://hub.docker.com/r/emqx/emqx/)

**Comment by RaymondMouthaan** [comment]
@zhanghongtong, would it be possible to use the Erlang base image from [here](https://hub.docker.com/_/erlang/) instead of compiling from scratch? It reduces the build time significantly.

Currently I am working on the project to build images for arch arm32v6, arm32v7, arm64v8 and amd64, if all works well I can do a PR to this emqx project and all images can be pushed to the official docker hub repo.

Thanks,
Ray

**Comment by zhanghongtong** [comment]
We tried to use `elang:21-alpine` to make our image, but the size of the image is too large, so we made the image ourselves.
You can provide RP about emqx-docker [in this project](https://github.com/emqx/emqx-docker).
