### ISSUE TITLE
Listening Address Issue

### ISSUE THREAD

**Issue by marcotuna** [emqx/emqx#1617]
#### Environment

- OS: FreeBSD 11.1-RELEASE-p10
- Erlang/OTP: 19
- EMQ: 2.3.9

#### Description

I am trying to set the listening address to other than 0.0.0.0 (*) however I don't seem to get it right, I believe those ports correspond to clustering, which I don't need, is there any way I can disable it?

```
USER     COMMAND    PID   FD PROTO  LOCAL ADDRESS         FOREIGN ADDRESS
root     beam.smp   95483 13 tcp4   *:6369                *:*
root     epmd       93142 3  tcp4   *:4369                *:*
```

**Comment by terry-xiaoyu** [comment]
Don't do that. If you want to block these ports, configure your firewall rules instead.

**Comment by marcotuna** [comment]
@terry-xiaoyu Thanks for your answer. The problem is that I am running this on a FreeBSD Jail which bridges the interface with the main host, this ports will be listening on multiple addresses and I don't want that. Is there any particular reason why I shouldn't disable this? Can I configure this to listen on 127.0.0.1 or something?

**Comment by terry-xiaoyu** [comment]
Currently we don't want to support this in the emqx.conf, but you can kill the epmd process if you are using a single-node emq:

```
# ps -ef | grep epmd
root      6636     1  0 Nov25 ?        00:00:00 /root/emqx/_rel/emqx/erts-10.1/bin/epmd -daemon
root     24221 20553  0 10:39 pts/0    00:00:00 grep --color=auto --exclude-dir=.bzr --exclude-dir=CVS --exclude-dir=.git --exclude-dir=.hg --exclude-dir=.svn epmd

```

Or you could start the epmd manually with `-address `:

```
# /root/emqx/_rel/emqx/erts-10.1/bin/epmd -h
usage: epmd [-d|-debug] [DbgExtra...] [-address List]
            [-port No] [-daemon] [-relaxed_command_check]
       epmd [-d|-debug] [-port No] [-names|-kill|-stop name]

See the Erlang epmd manual page for info about the usage.

Regular options
    -address List
        Let epmd listen only on the comma-separated list of IP
        addresses (and on the loopback interface).
    -port No
        Let epmd listen to another port than default 4369
```
