### ISSUE TITLE
Question - How to avoid clientId collision?

### ISSUE THREAD

**Issue by emqplus** [emqx/emqx#162]
When two clients with the same clientId connect to the broker, they will try to kick the other one out. 

If they all try to reconnect all the time, clientId collision occured...

**Comment by lsxredrain** [comment]
i think it should have a system id that is genarted by emqttd，and system id is used as unique index of
everyt session. 
maybe clientid + clientPid = system id is a choose

**Comment by erylee** [comment]
@lsxredrain, ClientPid will change when client disconnect from and then reconnect to the broker again.

**Comment by lsxredrain** [comment]
clientid is used for persisted session  in server side? 
if cleansession flag is false, then client can restore info of session?   
the role of clientid is a confusion,   is It a session id?  but it is more like a  machine id of client or a username.
recently I was confused about why mqtt have so many id in the connection that was generatedsuch as username/password/clientid/willTopic/willMsg in client side, but have no one id that was generated in server side.
we can't change the function of  username/password/willTopic/willMsg, but maybe we can change the fucntion of the clientid to sessionid and let it  generated in server side。

**Comment by lsxredrain** [comment]
The Client Identifier (ClientId) identifies the Client to the Server. Each Client connecting to the Server has  a unique ClientId. The ClientId MUST be used by Clients and by Servers to identify state that they hold  relating to this MQTT Session between the Client and the Server

**Comment by Hades32** [comment]
Just my 2ct:
* Kicking the other client with the same ClientID out is importantant for predictability. As in many IoT scenarios you have pretty unreliable connection it can happen pretty often for a client to reconnect while it still seems to be connected
* I thought that with MQTT 3.1.1 it was introduced that when leaving the ClientID field empty, a random ID is generated by the broker.

**Comment by lsxredrain** [comment]
now i process clientId collision as follow，it can prevent kick off each other  forever.

Client = emqttd_cm:lookup(emqttd_util:bin(ClientId)),
         case (undefined =/= Client) of
                                true -> 
                                            #mqtt_client{client_id = ClientId, client_pid = ClientPid} = Client, 
                                            lager:info("This is  ClientPid: ~p self: ~p ~n",[ClientPid, self()]),
                                            case (self() =/= ClientPid) of
                                                true ->
                                                    Json = mochijson2:encode([{type,emqttd_util:bin(["duplicate"])}]),
                                                    ClientTopic = emqttd_util:bin(["/client/",  ClientId]),
                                                    Message = #mqtt_message{qos = 1,
                                                                  topic = ClientTopic,
                                                                  payload = emqttd_util:bin(Json),
                                                                  from = list_to_binary([ClientId])},
                                                    emqttd_pubsub:publish(Message),
                                                    {"tokeAuth", "duplicate"}; 
                                                false -> {"tokeAuth", "success"}
                                            end;
