### ISSUE TITLE
'systemctl restart emqttd.service' doesn't restart emqttd dashboard

### ISSUE THREAD

**Issue by archerian** [emqx/emqx#1630]
#### Environment

- OS: Centos 7
- Erlang/OTP: R20/9.0
- EMQ: 2.3.9

#### Description

systemctl restart emqttd.service doesn't restart emqttd dashboard. I added a node to another and after this command the dashboard didn't show the new node but emqttd_ctl cluster status did. Had to reboot to see the changes.

**Comment by terry-xiaoyu** [comment]
EMQ currently not supports hot reload, you could `systemctl stop emqttd.service && systemctl start emqttd.service` as a workaround.
