### ISSUE TITLE
may you change rpc to gen_rpc

### ISSUE THREAD

**Issue by hchw** [emqx/emqx#1632]
#### Environment

- OS: 
- Erlang/OTP: 20
- EMQ: 2.3.1

#### Description
may you change rpc to gen_rpc?
https://github.com/priestjim/gen_rpc.git
 or better technical scheme ？
we know rpc will crash when saturated messages
thx……^_^

**Comment by terry-xiaoyu** [comment]
`gen_rpc` has been used in the enterprise version of EMQ. 🙂

**Comment by emqplus** [comment]
@bbjj040471 @terry-xiaoyu This feature should be merged in EMQ X 3.0 open source edition

**Comment by bbjj040471** [comment]
@emqplus @terry-xiaoyu  Great, look forward to it.
