### ISSUE TITLE
emq plugin  use erlang-rabbitmq-client. then  make  err

### ISSUE THREAD

**Issue by ice2hu** [emqx/emqx#1635]
#### Environment

- OS: centos 7.2
- Erlang/OTP: 20.3.1
- EMQ: 2.3.9

#### Description

make[1]: Entering directory '/public/hubing/eMQTT/emq-relx/deps/emq_auth_redis'
make[2]: Entering directory '/public/hubing/eMQTT/emq-relx/deps/eredis'
sed "s/{{EXTRA_OPTS}}/ {d,namespaced_types},/" Emakefile.src > Emakefile
erl -noinput -eval 'up_to_date = make:all()' -s erlang halt
make[2]: Leaving directory '/public/hubing/eMQTT/emq-relx/deps/eredis'
make[2]: Entering directory '/public/hubing/eMQTT/emq-relx/deps/rabbitmq-erlang-client'
make[3]: Entering directory '/public/hubing/eMQTT/emq-relx/deps/rabbit_common'
make[4]: Entering directory '/public/hubing/eMQTT/emq-relx/deps/rabbitmq_codegen'
make[4]: Leaving directory '/public/hubing/eMQTT/emq-relx/deps/rabbitmq_codegen'
make[4]: Entering directory '/public/hubing/eMQTT/emq-relx/deps/ranch'
make[4]: Leaving directory '/public/hubing/eMQTT/emq-relx/deps/ranch'
make[3]: Leaving directory '/public/hubing/eMQTT/emq-relx/deps/rabbit_common'
make[2]: Leaving directory '/public/hubing/eMQTT/emq-relx/deps/rabbitmq-erlang-client'
 GEN    rebar.config
make[1]: Leaving directory '/public/hubing/eMQTT/emq-relx/deps/emq_auth_redis'
make[1]: Entering directory '/public/hubing/eMQTT/emq-relx/deps/emq_auth_mongo'
make[2]: Entering directory '/public/hubing/eMQTT/emq-relx/deps/mongodb'
make[3]: Entering directory '/public/hubing/eMQTT/emq-relx/deps/bson'
make[3]: Leaving directory '/public/hubing/eMQTT/emq-relx/deps/bson'
make[3]: Entering directory '/public/hubing/eMQTT/emq-relx/deps/poolboy'
make[3]: Leaving directory '/public/hubing/eMQTT/emq-relx/deps/poolboy'
make[2]: Leaving directory '/public/hubing/eMQTT/emq-relx/deps/mongodb'
 GEN    rebar.config
make[1]: Leaving directory '/public/hubing/eMQTT/emq-relx/deps/emq_auth_mongo'
make[1]: Entering directory '/public/hubing/eMQTT/emq-relx/deps/emq_sn'
make[1]: Leaving directory '/public/hubing/eMQTT/emq-relx/deps/emq_sn'
make[1]: Entering directory '/public/hubing/eMQTT/emq-relx/deps/emq_coap'
make[2]: Entering directory '/public/hubing/eMQTT/emq-relx/deps/gen_coap'
make[2]: Leaving directory '/public/hubing/eMQTT/emq-relx/deps/gen_coap'
make[1]: Leaving directory '/public/hubing/eMQTT/emq-relx/deps/emq_coap'
make[1]: Entering directory '/public/hubing/eMQTT/emq-relx/deps/emq_stomp'
 GEN    rebar.config
make[1]: Leaving directory '/public/hubing/eMQTT/emq-relx/deps/emq_stomp'
make[1]: Entering directory '/public/hubing/eMQTT/emq-relx/deps/emq_plugin_template'
 GEN    rebar.config
make[1]: Leaving directory '/public/hubing/eMQTT/emq-relx/deps/emq_plugin_template'
make[1]: Entering directory '/public/hubing/eMQTT/emq-relx/deps/emq_web_hook'
 GEN    rebar.config
make[1]: Leaving directory '/public/hubing/eMQTT/emq-relx/deps/emq_web_hook'
make[1]: Entering directory '/public/hubing/eMQTT/emq-relx/deps/emq_lua_hook'
make[2]: Entering directory '/public/hubing/eMQTT/emq-relx/deps/luerl'
make[2]: Nothing to be done for 'all'.
make[2]: Leaving directory '/public/hubing/eMQTT/emq-relx/deps/luerl'
make[1]: Leaving directory '/public/hubing/eMQTT/emq-relx/deps/emq_lua_hook'
===> Starting relx build process ...
===> Resolving OTP Applications from directories:
          /public/hubing/eMQTT/emq-relx/apps
          /public/hubing/eMQTT/emq-relx/deps
          /usr/lib64/erlang/lib
===> Failed to solve release:
 Dependency emq_auth_redis is specified as a dependency but is not reachable by the system.

I can make it ,but can't solve .
then I use  "./relx  -V 3 " 

[0;32m===> Starting relx build process ...
[0m[0;36m===> state(command_line):
          log: (3:debug),
          config file: 
          goals: 
          output_dir: /public/hubing/eMQTT/emq-relx/_rel
          lib_dirs: 
          providers: 
               tar,
               relup,
               release,
               resolve_release,
               overlay,
               rel_discover,
               app_discover,
          provider config values: 
               {overlay_vars,[]},
               {system_libs,true},
               {default_libs,true},
[0m
[0;36m===> Running provider app_discover
[0m[0;32m===> Resolving OTP Applications from directories:
          /public/hubing/eMQTT/emq-relx/apps
          /public/hubing/eMQTT/emq-relx/deps
          /usr/lib64/erlang/lib[0m
[0;36m===> Unable to load the application metadata from /public/hubing/eMQTT/emq-relx/deps/emq_auth_redis
[0m[0;36m===> Resolved the following OTP Applications from the system: 
          goldrush-0.1.9: /public/hubing/eMQTT/emq-relx/deps/goldrush
               Symlink: false
               Active Dependencies:
                    kernel,
                    stdlib,
                    syntax_tools,
                    compiler,
               Library Dependencies:
  
...................
[0m
[0;36m===> Provider successfully run: app_discover
[0m[0;36m===> Running provider resolve_release
[0m[0;36m===> Solving Release emqttd-2.3.9
[0m[0;36m===> Provider (resolve_release) failed with: {error,
                                                     {rlx_prv_release,
                                                      {failed_solve,
                                                       {unreachable_package,
                                                        emq_auth_redis}}}}
[0m[0;31m===> Failed to solve release:
 Dependency emq_auth_redis is specified as a dependency but is not reachable by the system.

and in  the emq_auth_redis dir ,I change  Makefile and rebar.config

 makefile,  I just only add DEPS with  rabbitmq-erlang-client
#DEPS = eredis ecpool clique 
DEPS = eredis ecpool clique rabbitmq-erlang-client

in rebar.config ,
{deps, [
{eredis,".*",{git,"https://github.com/wooga/eredis","master"}},{ecpool,".*",{git,"https://github.com/emqtt/ecpool","master"}},{clique,".*",{git,"https://github.com/emqtt/clique",""}},{rabbitmq-erlang-client,".*",{git,"https://github.com/rabbitmq/rabbitmq-erlang-client",""}}
]}.
{erl_opts, [debug_info,{parse_transform,lager_transform}]}.

what's wang with this?

*A description of the issue*

**Comment by ice2hu** [comment]
if I remove the rabbitmq-erlang-client ,that is ok

**Comment by terry-xiaoyu** [comment]
In your Makefile of emq_auth_redis, add a line for rabbitmq-erlang-client:
```
dep_rabbitmq-erlang-client = git https://github.com/rabbitmq/rabbitmq-erlang-client v3.7.5
```

And you need also to config your `relx.config` for rabbitmq-erlang-client.

Hope that helps.
