### ISSUE TITLE
Emqtt does not close connection when http acl rejected

### ISSUE THREAD

**Issue by thynson** [emqx/emqx#1641]
#### Environment

- OS:
- Erlang/OTP: 
- EMQ: 2.0.6(Qingcloud stock image) as well as Latest one from Docker

#### Description

We recently wanted to integrate emqtt with our auth server via http acl plugin, we found that when a publish attempt was rejected, the corresponding connection won't be closed. With QoS level 2, the client(mosquitto_pub/libmosquitto) will retry for infinity times without raising an error like timedout or connection reset, since PINGREQ/PINGRSP is okay.

In my opion, the behaviour of rejecting publish attempt should be changed, because it make the client hard to realize what's wrong with it, and with client using libmosquitto it's hard handle such case . Another server [mqtt.js] do close the connection for such scenario.

[mqtt.js]: https://www.npmjs.com/package/mqtt

**Comment by Gilbert-Wong** [comment]
This feature has been implemented, it would be released with emqx3.0.0.
