### ISSUE TITLE
Problem with SSL - error,eacces - Only Seems to run well as root

### ISSUE THREAD

**Issue by NoelzeN** [emqx/emqx#1643]
[Spoiler: While writing this issue another idea came to my mind and "solved" the issue (However I'm not happy with the solution). Running emqttd as Root User fixed the error however I don't think that's a good solution, is it? Will still post the complete Text I had already written since when running the emqttd as user emqtt which is the default gives the described error. For those looking for a quick fix without any thoughts about security (I think from the security point of view I can't recommend the fix), changing the Option RUNNER_USER= to root in /usr/sbin/emqttd stopped the error from occuring]

I have emqttd installed on Cent OS 7 via Package Manager. EMQ is version emqttd-2.3-1.el7.centos.x86_64
When I try to enable SSL for MQTT Access on Port 8883 I get errors in the Log and can't subscribe to MQTT. My emq.conf:
`listener.ssl.external = 8883
listener.ssl.external.acceptors = 16
listener.ssl.external.max_clients = 1024
listener.ssl.external.access.1 = allow all
listener.ssl.external.handshake_timeout = 15s
listener.ssl.external.keyfile = /etc/letsencrypt/live/example.com/privkey.pem
listener.ssl.external.certfile = /etc/letsencrypt/live/example.com/cert.pem
listener.ssl.external.cacertfile = /etc/letsencrypt/live/example.com/fullchain.pem
`
The same Configuration I had successfully established with emqttd 2.2 (Not installed via Repository but Downloaded the Standalone Folder including binaries) but when I tried migrating to a different server I started getting these errors:

> 2018-06-20 15:08:45 =CRASH REPORT====
  crasher:
    initial call: emqttd_client:init/1
    pid: <0.2466.0>
    registered_name: []
    exception error: {{ssl_error,{options,{certfile,"/etc/letsencrypt/live/example.com/cert.pem",{error,eacces}}}},[{esockd_connection,upgrade,1,[{file,"src/esockd_connection.erl"},{line,131}]},{emqttd_client,init,1,[{file,"src/emqttd_client.erl"},{line,103}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}
    ancestors: [<0.1416.0>,<0.1415.0>,esockd_sup,<0.1197.0>]
    message_queue_len: 0
    messages: []
    links: [<0.1416.0>]
    dictionary: []
    trap_exit: false
    status: running
    heap_size: 2586
    stack_size: 27
    reductions: 6415
  neighbours:
2018-06-20 15:08:45 =SUPERVISOR REPORT====
     Supervisor: 'esockd_connection_sup - <0.1416.0>'
     Context:    connection_crashed
     Reason:     {{ssl_error,{options,{certfile,"/etc/letsencrypt/live/example.com/cert.pem",{error,eacces}}}},[{esockd_connection,upgrade,1,[{file,"src/esockd_connection.erl"},{line,131}]},{emqttd_client,init,1,[{file,"src/emqttd_client.erl"},{line,103}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}
     Offender:   [{pid,<0.2466.0>},{name,connection},{mfargs,{emqttd_client,start_link,[[{max_publish_rate,0},{client_idle_timeout,30000},{client_enable_stats,false},{max_clientid_len,1024},{max_packet_size,65536},{keepalive_backoff,0.75}]]}}]

>2018-06-20 15:08:36.957 [error] <0.1416.0> Supervisor 'esockd_connection_sup - <0.1416.0>' had child connection started with emqttd_client:start_link([{max_publish_rate,0},{client_idle_timeout,30000},{client_enable_stats,false},{max_clientid_len,...},...]) at <0.2446.0> exit with reason {ssl_error,{options,{certfile,"/etc/letsencrypt/live/example.com/cert.pem",{error,eacces}}}} in esockd_connection:upgrade/1 line 131 in context connection_crashed
2018-06-20 15:08:38.037 [error] <0.2448.0> CRASH REPORT Process <0.2448.0> with 0 neighbours crashed with reason: {ssl_error,{options,{certfile,"/etc/letsencrypt/live/example.com/cert.pem",{error,eacces}}}} in esockd_connection:upgrade/1 line 131

It seems like emqttd can't access the Ceertificate File. I already tried everything that came to my mind, changing file permissions to 755, chowning the files to emqtt (The user emqttd is started as).

Due to that it came to my mind, why not try to run the service as root. So I modified the /usr/sbin/emqttd file putting RUNNER_USER=root and started the service again. Now it is not showing errors anymore. However I don't understand why. Does anyone have an idea 
- Why this is happening
- How I can run the service as user emqtt without errors?
Ownership of the Certificate Files was default as they're created by Certbot, Read Access is there for "others":

`[root@vmi112195 sbin]# ls -la /etc/letsencrypt/live/example.com/
total 8
drwxr-xr-x.  2 root root   93 Jun 12 10:15 .
drwx------. 16 root root 4096 Jun 20 11:51 ..
lrwxrwxrwx.  1 root root   44 Jun 12 10:15 cert.pem -> ../../archive/example.com/cert1.pem
lrwxrwxrwx.  1 root root   45 Jun 12 10:15 chain.pem -> ../../archive/example.com/chain1.pem
lrwxrwxrwx.  1 root root   49 Jun 12 10:15 fullchain.pem -> ../../archive/example.com/fullchain1.pem
lrwxrwxrwx.  1 root root   47 Jun 12 10:15 privkey.pem -> ../../archive/example.com/privkey1.pem
-rw-r--r--.  1 root root  682 Jun 12 10:15 README`

`[root@vmi112195 sbin]# ls -la /etc/letsencrypt/archive/example.com/
total 20
drwxr-xr-x.  2 root root   83 Jun 12 10:15 .
drwx------. 16 root root 4096 Jun 20 11:51 ..
-rw-r--r--.  1 root root 2167 Jun 12 10:15 cert1.pem
-rw-r--r--.  1 root root 1647 Jun 12 10:15 chain1.pem
-rw-r--r--.  1 root root 3814 Jun 12 10:15 fullchain1.pem
-rw-r--r--.  1 root root 1704 Jun 12 10:15 privkey1.pem`

**Comment by aaftio** [comment]
I have this problem too.

**Comment by Gilbert-Wong** [comment]
I don't know why there are such problems in you server. In our test server, there are no such problems. I suppose you guys didn't config your user permissions on your server correctly.
