### ISSUE TITLE
shutdown interval more than 1.5 keep alive time

### ISSUE THREAD

**Issue by hui6075** [emqx/emqx#1655]
#### Environment

- OS: RHEL6
- Erlang/OTP: 20
- EMQ: 2.3.0

#### Description

EMQ shutdown the client in 157 seconds after receive last ping request. but keep alive time is 90 second. 90 * 1.5 = 135 seconds.

18:06:19.642 [debug] Client(undefined@10.108.230.189:11116): RECV CONNECT(Q0, R0, D0, ClientId=MX0022c77d4cf4a9dd5310, ProtoName=MQTT, ProtoVsn=4, CleanSess=true, KeepAlive=90, Username=undefined, Password=undefined, Will(Q0, R0, Topic=/SHSIT/M2S/WILL, Msg=Ly8xMWI2NmMzYmUzYDhjYzQyMC8=))

18:07:51.969 [debug] Client(MX0022c77d4cf4a9dd5310@10.108.230.189:11116): RECV PINGREQ(Q0, R0, D0)
18:07:51.969 [debug] Client(MX0022c77d4cf4a9dd5310@10.108.230.189:11116): SEND PINGRESP(Q0, R0, D0)

18:09:22.034 [debug] Client(MX0022c77d4cf4a9dd5310@10.108.230.189:11116): RECV PINGREQ(Q0, R0, D0)
18:09:22.034 [debug] Client(MX0022c77d4cf4a9dd5310@10.108.230.189:11116): SEND PINGRESP(Q0, R0, D0)

18:11:59.649 [debug] Client(MX0022c77d4cf4a9dd5310@10.108.230.189:11116): Shutdown for keepalive_timeout

**Comment by terry-xiaoyu** [comment]
It is the fault of EMQ's keep-alive mechanism. 

It doesn't restart a new timer when a mqtt control packet comes. Instead, it starts a timer when the client connected,  and check if there're any new bytes came on the current connection after the timer expires.

http://docs.oasis-open.org/mqtt/mqtt/v3.1.1/os/mqtt-v3.1.1-os.html#_Keep_Alive

**Comment by terry-xiaoyu** [comment]
We decided not to fix this as the solutions for a accurate keep-alive interval may have some potential performance impact.
