### ISSUE TITLE
EMQ throughput when accepting connections

### ISSUE THREAD

**Issue by crazybg321** [emqx/emqx#1663]
#### Environment

- OS: Amazon Linux 2 AMI (HVM)
- Erlang/OTP: R20/9.0
- EMQ: 2.3.10

#### Description

We setup EMQ on a c5.9xlarge EC2 instance of AWS which has 36 cores and 72GB of RAM. We also followed the tuning guide for accepting 1 000 000 connections. The use case is as follows:

* We have 3 subscribers to a shared topic such that the load is split.
* We started spawning connections - 160 per second until we reached 32000 clients. Each connection sends 1 message/sec to the topic as soon as it is connected.
* The CPU load peaked to 90-100% while we were still spawning new connections and once it accepted all of them, dropped to 43%. However, the subscribers stopped receiving the messages at a certain point (when we had about 12-15k connections, meaning 12-15k messages/second). When all connections were accepted, the subscribers never actually got any of those messages, until we made sure we stop them and wait for EMQ to drop their sessions and then start them again.

The issue seems to be that EMQ is building up a large queue while accepting connections as it is prioritizing the acceptors and once it has no more connections to accept it never recovers from falling behind.

The publishers are publishing with QoS 1 and are using unsecured TCP port.

The subscribers are subscribing to the shared topic with QoS1 and are also using unsecured TCP port.

This is the config that we use. We are also using MySQL auth plugin.
[emq.txt](https://github.com/emqtt/emqttd/files/2163583/emq.txt)

**Comment by homerzhou** [comment]
Hi @crazybg321 :
How to know EMQ have drop their sessions. it will useful for my another problem.
Use dashboard or emqttd_ctl ?

**Comment by Gilbert-Wong** [comment]
Hi, @crazybg321 , Sorry for late respond, you can try to add emqx tcp acceptors or wss acceptors to resolve this problem. @You can know EMQ drop their connection other than session.
