### ISSUE TITLE
Shared topic miss message

### ISSUE THREAD

**Issue by homerzhou** [emqx/emqx#1665]
#### Environment

- OS: docker
- Erlang/OTP: 
- EMQ: 2.3.5

#### Description

Hi:

    I have a EMQTT cluster with 5 machine.
    I have 50 clients subscribe `$local/$share/1/hello/#` (every 10 client for one cluster node).
    I have 1 client subscribe `hello/world`
    Then I kill the 45 subscriber clients  and After 15 minute start the 45 subscriber clients.

    The publisher client send `hello/world` with 10 message.
    There will be 4 message can not be dispatch to one of 45 clients, the 4 message is missing.
    But another client which subscribe `hello/world`, It can receive 10 message.
    When I restart the EMQTT cluster, it will resolve this problem.

    If this problem happened again, what method I can do to debug this problem.
    This problem is happened in `production environment`, I can not open debug log. 
   
    ps. All subscriber client use `clean-session=true`, I guess if this problem is associate with Old session is exist. When I kill the subscriber client, How can I see if the EMQ is dropped this sessions

**Comment by spring2maz** [comment]
Hi @homerzhou $local/$share is now considered deprecated.
3.0 (beta 2 so far) has a new shared subscribe implementation and we believe there should be no such issue. Please give it a try.
