### ISSUE TITLE
Alive nodes can't send last will messages to subscribed clients when there is one node killed in the cluster.

### ISSUE THREAD

**Issue by qiujiancn** [emqx/emqx#1668]
#### Environment

- OS: centos 7
- Erlang/OTP: 
- EMQ: 2.3.1

I have a EMQTT cluster with 2 machine，nodeA and nodeB.
I have 1 client named device publish last will messages `device/will`，payload offline text，and it is connected to nodeA。
I have 1 client named receiver subscribe `device/will`， and it is connected to nodeB.

Then
1、When I killed device，receiver can receive the last will message offline.
2、When I killed nodeA，receiver can't receive the device last will message offline, then it means that the receiver still think the device would be online.
The nodeB should reload the nodeA clients status when nodeA is dead, but it didn't do it. If I must use  last will messages, what can I do to resolve this issue?

**Comment by Gilbert-Wong** [comment]
For now, emqx does not support to migrate or replicate sessions between different nodes. We'll support it in the future. Anyway, thanks for your feedback.

**Comment by turtleDeng** [comment]
Thank you for your participation, you can use the enterprise version for persistent operations

https://www.emqx.io/downloads#enterprise
