### ISSUE TITLE
subscribe 210 thousand topics, the dashboard login fail

### ISSUE THREAD

**Issue by juanli1247** [emqx/emqx#1669]
When i subscribe 200 thousand topics, the dashboard can show the topics successfully, but when the topic exceed about the 210 thousand, i input the admin/public and the dashboard web not response, Is it more than the upper limit?

By the way, I install the broker use the default setting. server hardware is 4 cpu, 8G memory.

**Comment by Gilbert-Wong** [comment]
Hi, @juanli1247, we have tried with emqx rc.3 and emqx 3.0.0 release and we do not reproduce the bug you encountered, maybe the emq version you test is too old. We have released emqx 3.0.0. welcome to try our latest broker.
