### ISSUE TITLE
Where are newly created users persisted?

### ISSUE THREAD

**Issue by hgascoigne** [emqx/emqx#1670]
#### Environment

- OS: emq-docker
- EMQ: v2.3.9

#### Description

Whenever I restart my EMQ instance, users created through the dashboard are no longer there. Where should my volume be mounted in order to persist those users across restarts?

**Comment by Gilbert-Wong** [comment]
Hi, hgascoigne. The Enterprise of EMQ is able to persist users info into databases, such as mysql, mongodb, etc.

**Comment by id** [comment]
@AdamJel no, open source version does persist users in internal database, and it also supports external services https://docs.emqx.com/en/emqx/latest/access-control/authn/mnesia.html
