### ISSUE TITLE
Error report: Generic server disksup terminating Last message in was timeout

### ISSUE THREAD

**Issue by yeahwangy** [emqx/emqx#1671]
#### Environment

- OS: CentOS Linux release 7.2.1511 (Core)
- Erlang/OTP: Erlang/OTP 20 [erts-9.0] [source] [64-bit] [smp:2:2] [ds:2:2:10] [async-threads:32] [hipe] [kernel-poll:true]
- EMQ: 2.3.9

#### Description

- [error.log](https://github.com/emqtt/emqttd/files/2186878/error.log)
- [crash.log](https://github.com/emqtt/emqttd/files/2186888/crash.log)
- [crash.dump](https://github.com/emqtt/emqttd/files/2186889/crash.dump.log)

**Comment by Gilbert-Wong** [comment]
What did you do on emq server? Could you give me more details?
