### ISSUE TITLE
Messages occasionally dropped in the cluster that using local+share subscriptions，but the Dropped  message Num didn't show it.

### ISSUE THREAD

**Issue by qiujiancn** [emqx/emqx#1674]
#### Environment

- OS: centos 7
- Erlang/OTP: 
- EMQ: 2.3.1

#### Description

We have 6 broker machines in the emqttd cluster, and  our receiver machine use local+share subscription mode.Usually the message received and sent are the same，but when we restart the receiver machine，then the message sent come down as the message dropped is still zero. The broker machines received the device publish message，and it showed that it had been sent the massage to the receiver machine，but the receiver machine didn't receive really.  Finally，we restart the 6 broker machines，and then the message received and sent are the same again，and no message is dropped now. So I think this is the emqttd cluster 's bug，maybe the cluster manage the invalid clients error，because I found there already have some old invalid receiver clients id in the cluster when I restarted the receiver.The cluster didn't remove the invalid clients.

Please help me to find how to fix this issue, thanks very much.

**Comment by qiujiancn** [comment]
#1665

**Comment by spring2maz** [comment]
trying to reproduce it.

**Comment by spring2maz** [comment]
Hi @qiujiancn I was trying to reproduce it in 3.0-beta.2 which turn out to have local-share deprecated already. It is a completely new implementation in 3.0 for shared subscription, please give it a try.
