### ISSUE TITLE
auth jwt

### ISSUE THREAD

**Issue by stefano055415** [emqx/emqx#1676]
#### Environment

- OS: debian9
- Erlang/OTP: 
- EMQ: 2.3.10

#### Description

auth jwt

using the same client I get "Bad username or password" with version 2.3.10 while with version 2.3.6 I can authenticate myself without problems
can someone help me?
thank you

**Comment by Gilbert-Wong** [comment]
More details please. Which client you use and please give use your config and log of emqx.
