### ISSUE TITLE
 Error generating configuration in phase rhs_subs

### ISSUE THREAD

**Issue by emqplus** [emqx/emqx#1678]
#### Environment

- OS: ALL
- Erlang/OTP: R21
- EMQ: R3.0

#### Description

The `./bin/cuttlefish` cannot compile `emqx.conf` if the 'log.syslog = on', 'log.syslog.level = error' configuration items are commented.

**Comment by turtleDeng** [comment]
Fix https://github.com/emqx/cuttlefish/commit/871e1dc20e93c58c8d63b4b6329b7640a8c3cd7f
