### ISSUE TITLE
If ekka:autocluster() fails mid-join, emqttd won't start

### ISSUE THREAD

**Issue by PiedPieper** [emqx/emqx#1679]
#### Environment

- OS: RHEL 7
- Erlang/OTP: ~~21~~ 20.2
- EMQ: 2.3.5

#### Description

> 14:50:11.083 [info] <0.1017.0> ekka_membership:handle_cast(218):  Ekka(Membership): Node UpdateServer@10.26.0.195 up
> 14:50:11.086 [error] <0.1128.0> **emqttd:shutdown(169):  EMQ shutdown for join**
> 14:50:11.087 [error] <0.1128.0> emqttd_plugins:stop_app(208):  Plugin emq_dashboard is not started
> 14:50:11.087 [error] <0.1128.0> emqttd_plugins:stop_app(208):  Plugin emq_retainer is not started
> 14:50:11.087 [error] <0.1128.0> emqttd_plugins:stop_app(208):  Plugin aws_bridge is not started
> 14:50:11.089 [info] <0.864.0> Undefined:Undefined(Undefined):  Application emqttd exited with reason: stopped
> 14:50:11.089 [info] <0.864.0> Undefined:Undefined(Undefined):  Application ekka exited with reason: stopped
> 14:50:11.089 [info] <0.864.0> Undefined:Undefined(Undefined):  Application mochiweb exited with reason: stopped
> 14:50:11.090 [info] <0.864.0> Undefined:Undefined(Undefined):  Application esockd exited with reason: stopped
> 14:50:11.090 [info] <0.864.0> Undefined:Undefined(Undefined):  Application gproc exited with reason: stopped
> 14:50:11.093 [info] <0.864.0> Undefined:Undefined(Undefined):  Application mnesia exited with reason: stopped
> 14:50:11.098 [debug] <0.1169.0> Undefined:Undefined(Undefined):  Supervisor mnesia_sup started mnesia_sup:start_event() at pid <0.1170.0>
> 14:50:11.098 [debug] <0.1169.0> Undefined:Undefined(Undefined):  Supervisor mnesia_sup started mnesia_ext_sup:start() at pid <0.1171.0>
> 14:50:11.099 [debug] <0.1172.0> Undefined:Undefined(Undefined):  Supervisor mnesia_kernel_sup started mnesia_monitor:start() at pid <0.1173.0>
> 14:50:11.099 [debug] <0.1172.0> Undefined:Undefined(Undefined):  Supervisor mnesia_kernel_sup started mnesia_subscr:start() at pid <0.1174.0>
> 14:50:11.099 [debug] <0.1172.0> Undefined:Undefined(Undefined):  Supervisor mnesia_kernel_sup started mnesia_locker:start() at pid <0.1175.0>
> 14:50:11.099 [debug] <0.1172.0> Undefined:Undefined(Undefined):  Supervisor mnesia_kernel_sup started mnesia_recover:start() at pid <0.1176.0>
> 14:50:11.099 [debug] <0.1172.0> Undefined:Undefined(Undefined):  Supervisor mnesia_kernel_sup started mnesia_tm:start() at pid <0.1177.0>
> 14:50:11.099 [debug] <0.1172.0> Undefined:Undefined(Undefined):  Supervisor mnesia_kernel_sup started mnesia_checkpoint_sup:start() at pid <0.1178.0>
> 14:50:11.099 [debug] <0.1172.0> Undefined:Undefined(Undefined):  Supervisor mnesia_kernel_sup started mnesia_controller:start() at pid <0.1179.0>
> 14:50:11.100 [debug] <0.1172.0> Undefined:Undefined(Undefined):  Supervisor mnesia_kernel_sup started mnesia_late_loader:start() at pid <0.1180.0>
> 14:50:11.100 [debug] <0.1169.0> Undefined:Undefined(Undefined):  Supervisor mnesia_sup started mnesia_kernel_sup:start() at pid <0.1172.0> 
> 14:50:11.100 [info] <0.864.0> Undefined:Undefined(Undefined):  Application mnesia started on node 'EMQ@10.26.0.195'
> 14:50:11.128 [error] <0.1128.0> ekka:autocluster(88):  **Autocluster exception: {badmatch,{no_exists,{mqtt_trie,cstruct}}}**
> 

After this point, emqtt won't attempt to restart.

Edit: Changed OTP version 21 to 20.2

**Comment by DanielRooks** [comment]
To my knowledge, EMQTT does not support Erlang 21 at the moment and will fail if you try to run it in an Erlang 21 environment.
That may be part of your problem.
Try installing Erlang 20 instead.

**Comment by Gilbert-Wong** [comment]
What DanielRooks said is right, please downgrade your erlang verision and restart EMQTT. I recommend you to use [asdf](https://github.com/asdf-vm/asdf) to switch erlang version.

**Comment by PiedPieper** [comment]
@DanielRooks @Gilbert-Wong  I made a mistake in my original post. The otp version I am using is 20.2. This issue is not unique to OTP 21
