### ISSUE TITLE
Tracking Throughput of a Topic

### ISSUE THREAD

**Issue by dimasmamot** [emqx/emqx#1685]
#### Environment

- OS: 
- Erlang/OTP: 
- EMQ: 

#### Description

How can I track the throughput of the broker in windowed time. I mean in mosquitto you have that topic, which show the moving average of the number of bytes received by the broker over different time intervals. The final "+" of the hierarchy can be 1min, 5min or 15min. The value returned represents the number of bytes received in 1 minute, averaged over 1, 5 or 15 minutes. called $SYS/broker/load/bytes/received/+

Is there similar topic or metrics in emqtt dashboard to show the moving average of each byte per second that received by the broker ?

**Comment by Gilbert-Wong** [comment]
We have no schedule to support this feature.
