### ISSUE TITLE
Using the entire certificate as username

### ISSUE THREAD

**Issue by tiagodeoliveira** [emqx/emqx#1688]
#### Environment

- OS: All
- Erlang/OTP: All
- EMQ: All

#### Description

I am working on a case where the devices authenticate using X509, but since we accept multiple CA's we cannot simply extract the DN or CN from the certificate and use the "username" to execute the authentication on the auth plugin, we actually need the entire certificate and on a second step validate the certificate against the custom CAs.

For that, I believe the simplest way is to allow the _peer_cert_as_username_ to be the certificate representation. We can then supply a _verify_fun_ that allows the SSL connection to be established with some specific certificates (self-signed for instance) and on the authentication plugin execute the logic.

We PR'ed the solution here #1645, please give your feedback if that is the way to proceed.

Thanks a lot.

**Comment by Gilbert-Wong** [comment]
This feature has been implemented in emqx3.0-rc.3
