### ISSUE TITLE
Offiline Queque buffering limited 1 hour

### ISSUE THREAD

**Issue by gpism** [emqx/emqx#1699]
#### Environment

- OS: ubuntu 14.04
- Erlang/OTP: 
- EMQ: 2.1

#### Description
Offline buffering mqtt device , we have a requirement  when device offline we require all messages to be buffered and sent client when it comes online next 
*A description of the issue*
Currently, offline message seems to be buffered only for one hour we tried two settings, but offline buffering seems to work for 1 hour 
mqtt.mqueue.max_length = infinity
mqtt.session.expiry_interval = 24h

Please me know is there any else setting we can change /tweak to achieve desired effect

**Comment by Gilbert-Wong** [comment]
Persist messages to databases.

**Comment by gpism** [comment]
Thanks for tip ...but How is there a plug-in for that ? Any link  to documentation or guide will help
    	

    	Get Outlook for iOS
    
  




On Sat, Jul 28, 2018 at 8:34 PM +0530, "Gilbert" <notifications@github.com> wrote:












Persist messages to databases.

**Comment by Gilbert-Wong** [comment]
Look at this link :[http://emqtt.io/docs/v2/plugins.html](http://emqtt.io/docs/v2/plugins.html). You could see that EMQ has mechanism to load plugins . And the feature you want is in enterprise edition of EMQ which support plugins to persist message to databases.

**Comment by gpism** [comment]
Thanks ! will try the plugin ...in case of any issues revert
