### ISSUE TITLE
Emq_auth_username plugin configuration failed

### ISSUE THREAD

**Issue by epc2018** [emqx/emqx#1701]
#### Environment

- OS: centos 7
- Erlang/OTP: 
- EMQ: 2.2

#### Description

*I use the eclips paho client to disable anonymous login, but I still return rc=0 when I subscribe to the client, indicating that the connection is successful. I loaded the emq_auth_username plugin and set the default user admin, please tell me the solution*

**Comment by huangdan** [comment]
@epc2018, I can't reproduce this issue, please describe the test steps in detail.
