### ISSUE TITLE
Rest API error when it has wildcards in topic

### ISSUE THREAD

**Issue by krittanon-w** [emqx/emqx#1706]
#### Environment

- OS: Official Docker 
- EMQ: 2.3.11

#### Description
I tested REST API feature (POST api/v2/mqtt/subscribe) and sent request
```javascript
{
     "topic": "home/1/room/+",
     "qos": 0,
     "client_id": "client_1"
}
```
then I got response
```javascript
{
    "code": 102,
    "message": "validate topic: home/1/room/+ fail" // <- question: I can't use wildcard or this is a bug?
}
```
but if I set topic with out wildcards level ( + or # )  
```javascript
{
     "topic": "home/1/room/1",
     "qos": 0,
     "client_id": "client_1"
}
```
and got response
```javascript
{
    "code": 0,
    "result": []
}
```
**p.s.**
- if this is not a bug how to make a subscription that use wildcard in topic e.g. home/1/room/+, home/1/room/# via REST API feature.

**Comment by tigercl** [comment]
hi @krittanon-w, 
This bug has been fixed in the emqx-3.0-beta.2
