### ISSUE TITLE
Reconnect with same clientid failed

### ISSUE THREAD

**Issue by gstar1987td** [emqx/emqx#1707]
#### Environment

- OS: centos7
- Erlang/OTP:  
- EMQ: 2.3.11

#### Description
I try to connect emqttd with paho and I used same clientid like "test" and set clean_session = false. Then the client send me a call back of lost connection. NOTE that my first connection with this clientid was successed, then i shut down my program and try again, the client send a call back of lost connection with IOE Exception. My emqttd version was 2.3.11

I tried on emqttd 2.3.0. This phenomenon didn't appear as I tried for many times.

Could anyone give me some advice?

*A description of the issue*

**Comment by samk-mesh** [comment]
I'm seeing similar behavior.

**Comment by samk-mesh** [comment]
Any updates on this? 
I've reverted to using mosquitto for now.

**Comment by Gilbert-Wong** [comment]
I tested as you said. There is no such problem on my machine with emqx 2.3.11

**Comment by samk-mesh** [comment]
Emqttd 2.3.11  (ubuntu host)
version 97dfb34b5a5ae13f3e9e0ebf1321774eb04b2851  of the golang paho library. 
Clean Session = False.
To reproduce: 
My first session with each unique client id works. 
If I reconnect without changing the client id, I see the same behavior as gstar. 

I can resolve by using clean session = true. 
Or rebooting my emq instance, manually forcing emq to forget the session.

**Comment by Gilbert-Wong** [comment]
I  tried with java paho library and it has no problem. I supposed maybe it is golang paho  bug? Anyway, I am busy these days and would test with golang paho library next week.

**Comment by gstar1987td** [comment]
I used paho and another mqtt client: https://github.com/fusesource/mqtt-client, and end up with same result. 
There are some points that I think they might be the key points:
1, Using same clientid caused this problem.
2, cleansession must be set to false.
3,  I set auto reconnection on both paho and fusesource mqtt client, and reconnect failed. Then I tried another method: I recreate another client instance with same connect options 30 seconds later. This time I could reconnect to emqtt.

**Comment by Gilbert-Wong** [comment]
Sorry, I still cannot reproduce your problem. And maybe you can have a try with emqx3.0.

**Comment by Gilbert-Wong** [comment]
First, I still can not reproduce your problem. Second, maybe you can have a new try with emqx3.0.

**Comment by samk-mesh** [comment]
I just reinvestigated this issue with my devs. 
They had forked the Go mqtt library, and I cannot reproduce with the main branch/ normal go mqtt library.
