### ISSUE TITLE
Get SubTopicCount in a topic

### ISSUE THREAD

**Issue by Lianmc9408** [emqx/emqx#1709]
#### Environment

- OS: ubuntu
- Erlang/OTP:  a
- EMQ:  stable version

#### Description

*A description of the issue*
How can I get SubTopicCount in a topic? Just like SubTopicCount in page "http://127.0.0.1:18083/#/topics" , thanks !

**Comment by Gilbert-Wong** [comment]
The feature has not been supported. We would add this feature to emqx 3.0.

**Comment by tigercl** [comment]
Hi, @Lianmc9408 Sorry for the late reply, what do you mean by the SubTopicCount? The number of topics subscribed by the client? Or number of topics owned by the node?
