### ISSUE TITLE
[Cluster] Message published as retained is not retained for client connected to other node

### ISSUE THREAD

**Issue by toomasz** [emqx/emqx#1710]
#### Environment

- OS: Centos7
- Erlang/OTP: 
- EMQ: 2.3.11

#### Description

To reproduce:

- Start EMQ with two nodes in cluster, lets call them emq1 and emq2
- Connect client(Client1) to emq1 and publish message to topic should/be/retained with value 1
- Disconnect client
- Connect another client(Client2) to emq2 and subscribe to should/be/retained

**Expected**:
- Client2 should receive message on topic should/be/retained with value 1 soon after connecting to node emq2

**Actual**:
- Client2 does not receive message on topic should/be/retained - incorrect, it should receive message regardless of EMQ node it connects to

**Remarks**:
- Client that connects to emq1 and subscribes to should/be/retained  gets message soon after connecting - that's correct
 

Attaching config files from node1 and node 2

[emq2.conf.txt](https://github.com/emqtt/emqttd/files/2259898/emq2.conf.txt)
[emq1.conf.txt](https://github.com/emqtt/emqttd/files/2259899/emq1.conf.txt)

**Comment by Gilbert-Wong** [comment]
The feature would be implemented in emqx3.0.

**Comment by tigercl** [comment]
@toomasz Sorry, I didn't reproduce this problem in EMQ 2.3.11, can you provide more logs?

**Comment by toomasz** [comment]
@tigercl Unfortunately i'm not longer using two node cluster anymore. if necessary, i can setup it again to obtain logs for you. Did you try my config files? I attached them.

**Comment by tigercl** [comment]
@toomasz I tried your config files and it works fine. If you have time, you can try again and provide more logs.
