### ISSUE TITLE
Emqttd Clustering issues with kubernetes

### ISSUE THREAD

**Issue by HackToHell** [emqx/emqx#1720]
#### Environment

- OS: Alpine
- Erlang/OTP: R20/9.1.5
- EMQ: 2.3.11

#### Description

When the network fails for a brief amount of time in kubernetes, the cluster split brains and doesn't reconcile it's state.

Steps to reduce:
1) Have a emqttd cluster with k8s clustering mode, with let's say 3 nodes
2) Remove one emqttd's node's network, the other nodes confirm this and the node goes to down and doesn't show up in cluster status as running.
3) When the node's network comes back up (within the auto clean time limit), ekka discovers a network partition and then tries to remedy it as per the steps described in the docs, and the coordinator restarts the smaller cluster.
4) The restarted node fails to join back to the original cluster and creates it's own cluster, resulting in a split brain.
 (In case this happens after the auto clean time limit, the re-clustering never happens and there are two clusters again)

**Comment by isman-usoh** [comment]
https://github.com/emqx/ekka/issues/14#issuecomment-318878900

**Comment by eastpav** [comment]
@isman-usoh  this isn't startup the cluster,  cluster is ok. the problem is the cluster cannot recovery from a netsplit automatically.

**Comment by popaaaandrei** [comment]
Has someone attempted a k8s configuration with the 3.0 release?

**Comment by nubunto** [comment]
We've been having the exact same issue with k8s. Any updates on this?

**Comment by Gilbert-Wong** [comment]
Cool! @nubunto .

**Comment by selvakn** [comment]
@nubunto : Do you mind sharing the kube config / code that you are using to solve this ?
