### ISSUE TITLE
On the problem of ACL control

### ISSUE THREAD

**Issue by acodercat** [emqx/emqx#1722]
Environment
OS: mac os
Erlang/OTP:
EMQ: 2.3.9
Description
With ACL, you can control the permissions through browsers in your own Dashboard panel, but TCP can't control it.

**Comment by terry-xiaoyu** [comment]
@acodercat Hi, when you saying `ACL`, do you mean the Access Control on the topics? I don't think we can configure the ACL via dashboard.
