### ISSUE TITLE
Docker image won't start

### ISSUE THREAD

**Issue by williamchanter** [emqx/emqx#1723]
#### Environment

- OS: Docker Container Latest (2.3.11) / openSUSE Tumbleweed (20180807) / Kernel 4.17.12-1-default 

#### Description

When running docker container it fails to start with this error in the `docker logs emq20` as seen below:

```sh
> docker logs emq20
standard_init_linux.go:185: exec user process caused "exec format error"
```
Not sure if I'm just missing something super obvious? I was running docker using this command `docker run -tid --name emq20 -p 1883:1883 -p 8083:8083 -p 8883:8883 -p 8084:8084 -p 8080:8080 -p 18083:18083 emqttd-docker-v2.3.11` 

Thanks in advance for any ideas

**Comment by zhanghongtong** [comment]
I use the `vagrant box` to create a virtual machine for `openSUSE-Tumbleweed v1.0.6.20180530`. In the virtual machine, use `Docker version 18.06.1-ce, build e68fc7a215d7` to run ` docker run -tid --name emq20 -p 1883:1883 -p 8083:8083 -p 8883: 8883 -p 8084:8084 -p 8080:8080 -p 18083:18083 emqttd-docker-v2.3.11`, the result is normal

**Comment by zhanghongtong** [comment]
@williamchanter  Closing this issue.
