### ISSUE TITLE
How can I revoke client certs?

### ISSUE THREAD

**Issue by hpham04** [emqx/emqx#1724]
#### Environment

- OS: Ubuntu 16.04
- Erlang/OTP: 
- EMQ: 2.3.11

#### Description
Sometimes we want to revoke client certificates so device no longer can connect to emqtt broker
*A description of the issue*
I don't know how to do it although it seems that revocation feature is supported

**Comment by Forsure-Wang** [comment]
I encountered the same issue,did you find any solution?

**Comment by Gilbert-Wong** [comment]
Sorry, @Forsure-Wang , we have no schedule to implement this feature.

**Comment by huanghuicheng** [comment]
emqx v3.0.0 以上版本支持了吗？？

**Comment by HJianBo** [comment]
Nope,  we don't have this schedule there. And if you want to control the device access, you should consider the auth_* plugins to implement first.
