### ISSUE TITLE
About emqtt client status

### ISSUE THREAD

**Issue by imalandu** [emqx/emqx#1726]
#### Environment

- OS: docker on CentOS 7.4
- Erlang/OTP: 
- EMQ: docker v2.2.0

#### Description

I have a emqtt cluster with 2 node, example nodeA and nodeB.

If a clientA is connected to nodeA, and the clientB subscribed to the topic($SYS/brokers/nodeB@x.x.x.x/clients/clientA/connected) on the nodeB.
But now, clientB cannot obtain the device status of clientA.

If I subscribe to this topic($SYS/brokers/nodeA@x.x.x.x/clients/clientA/connected)  on nodeA at any node, I can get device status

Is there a problem with my configuration or emqtt is like this?

thinks.

**Comment by Gilbert-Wong** [comment]
Refer from MQTT Specification
>The Server MUST NOT match Topic Filters starting with a wildcard character (# or +) with Topic Names beginning with a $ character [MQTT-4.7.2-1]. The Server SHOULD prevent Clients from using such Topic Names to exchange messages with other Clients. Server implementations MAY use Topic Names that start with a leading $ character for other purposes.
