### ISSUE TITLE
Shared subscriptions on Cluster

### ISSUE THREAD

**Issue by davorozo** [emqx/emqx#1728]
#### Environment

- OS: Windows
- Erlang/OTP: 
- EMQ: 2.3.8

#### Description

Is it supported shared subscriptions over cluster?. We need to deploy our system with high availability and we need to avoid duplicated messages in our applications that are distributed in different servers but listening to the same topic over the clustered brokers.

I started two brokers on local host: cluster.static.seeds = emq@127.0.0.1,emq2@127.0.0.1

--
Test1:
First client subscribes to the following topic on emq: $share/group/Topic
Second client subscribes to the following topic on emq2: $share/group/Topic

Both clients receive the message at the same time. Message is published to any broker.
--
Test2:
First client subscribes to the following topic on emq: $local/$share/group/Topic
Second client subscribes to the following topic on emq2: $local/$share/group/Topic

Message is received by the client that is connected to the broker wich receives the message. If the client is offline no message is received in the client connected to the other broker in the cluster.
--

If both clients are connected to the same broker and subscribed to topic  $local/$share/group/Topic it works as expected, but it does not work on clustered nodes.

How can we implement the system in order to get it working as expected?

Thank you.

**Comment by turtleDeng** [comment]
@davorozo https://github.com/emqtt/emqttd/issues/1052

**Comment by rjbaat** [comment]
I experience the same problem.
Some clients do receive the shared load correctly. But some get double messages. So i am processing duplicate data from the EMQ cluster and thats not what is supposed to happen.

**Comment by fair18** [comment]
I am getting the same issue as @rjbaat

**Comment by jupin-r** [comment]
The same issue: We have cluster of three mqqt brokers and multiple clients in shared topic. Sometimes the message is tripled, sometimes doubled.

**Comment by Gilbert-Wong** [comment]
Hi, this shared subscriptions in cluster has been implemented in emqx3.0-rc.1, please download the latest emqx and try again.
