### ISSUE TITLE
Everything reset after power cycle? Starting with Windows? 

### ISSUE THREAD

**Issue by dannieboiz** [emqx/emqx#1735]
#### Environment

- OS: Win 10
- Erlang/OTP: 
- EMQ: 2.2

All configuration lost after a reboot. 

Got a few topics going on for a couple days. Needed to reboot my PC for the first time since installing EMQTT. Assume I simply need to start the service, so that's all I did. When it came up, all of my subscription is gone.

Also, is there a way to start EMQQT with Windows?

**Comment by Gilbert-Wong** [comment]
This the bug of windows EMQ package.

**Comment by dannieboiz** [comment]
Gilbert... so are you saying this is just the nature of running it on a Windows machine?

**Comment by Gilbert-Wong** [comment]
Yes, the packege of windows has some problems and I noticed that the edition of EMQ you use is 2.2. The latest version of EMQ is 2.3.11 and it fixes a lot of bugs in EMQ 2.2. There are also some serious problems about services regist in EMQ 2.3.11 Windows package. The service regist bugs 
 on windows platform will be fixed this week. Personally, I recommend you run EMQ  docker on windows. There is no such problem you issued on linux and mac os.

**Comment by Gilbert-Wong** [comment]
Sorry for the ambiguous description before. The community edition of EMQX itself does not support to store subscriptions or messages on the local disk. You can contact @zhengyupan for enterprise support.
