### ISSUE TITLE
Processing ClientId duplicate problem

### ISSUE THREAD

**Issue by XiaoKaiRen** [emqx/emqx#1737]
#### Environment

- OS:  Ubuntu 18.04.1
- Erlang/OTP: 
- EMQ: 2.3.11

#### Description

My clientid will be the same for special reasons
I want the MQTT Broker not to rely on the ClientId to determine whether to repeat
or rename ClientId
Where do I want to modify him?

**Comment by XiaoKaiRen** [comment]
I hope to have the following features
https://mosquitto.org/man/mosquitto-conf-5.html
use_username_as_clientid
use username replace clientid 
How to achieve in EMQ？

**Comment by Gilbert-Wong** [comment]
EMQ does not support this feature now. you have to implement it by yourself on your mqtt client. We would support it in the future

**Comment by tigercl** [comment]
The feature has been implemented in emqx v3.0-rc.4
