### ISSUE TITLE
CONNACK Timeout

### ISSUE THREAD

**Issue by ice2hu** [emqx/emqx#1740]
#### Environment

- OS: centos 7
- Erlang/OTP: 9.0
- EMQ: 2.3.9

#### Description
When I use the emqtt_bench_pu connect emqttd server,
 ./emqtt_bench_pub -h 172.19.56.104 -p 1883 -c 258 -I 1000 -t sys/test4/%i -q 1 -s 256 -k 300 --ifaddr 172.19.56.82 -u test -P test

but it report ERR
client 243 EXIT: {shutdown,connack_timeout}
[error] [Client <0.843.0>] CONNACK Timeout!

emqttd err log.
error.log
2018-08-24 11:44:24.230 [error] <0.31822.26> gen_server <0.31822.26> terminated with reason: {timeout,{gen_server2,call,[<0.1443.0>,{start_session,true,{<<"172.19.56.82_pub_243">>,<<"test">>},<0.31822.26>},120000]}}

erlang.log
(emq@172.19.56.104)1> 12:37:42.373 [error] Supervisor 'esockd_connection_sup - <0.1548.0>' had child connection started with emqttd_client:start_link([{max_publish_rate,0},{client_idle_timeout,30000},{client_enable_stats,false},{max_clientid_len,...},...]) at <0.31822.26> exit with reason {timeout,{gen_server2,call,[<0.1443.0>,{start_session,true,{<<"172.19.56.82_pub_243">>,<<"test">>},<0.31822.26>},120000]}} in context connection_crashed

crash.log:
2018-08-24 11:44:24 =ERROR REPORT====
** Generic server <0.31822.26> terminating
** Last message in was {inet_async,#Port<0.445473>,28337,{ok,<<16,46,0,4,77,81,84,84,4,194,1,44,0,22,49,55,50,46,49,57,46,53,54,46,56,50,95,112,117,98,95,50,52,51,51,52,0,4,106,105,111,116,0,4,106,105,111,116>>}}
** When Server state == {client_state,{esockd_connection,[#Port<0.445473>,#Fun<esockd_transport.2.118520527>,[]]},{{172,19,56,82},37022},running,true,undefined,65536,{none,65536},{proto_state,{{172,19,56,82},37022},#Fun<emqttd_client.0.18944683>,false,undefined,<0.31822.26>,undefined,undefined,undefined,undefined,false,undefined,undefined,0.75,1024,undefined,{proto_stats,false,0,0,0,0},undefined,undefined,undefined,undefined,undefined},undefined,false,30000,189}
** Reason for termination ==
** {timeout,{gen_server2,call,[<0.1443.0>,{start_session,true,{<<"172.19.56.82_pub_243">>,<<"test">>},<0.31822.26>},120000]}}

*A description of the issue*

**Comment by ice2hu** [comment]
Erlang/OTP: 20

**Comment by terry-xiaoyu** [comment]
@ice2hu May I know your system info (Number of CPU cores, and how large is your MEM)? And the CPU usage when the error occurs?

You could follow this [guide](http://emqtt.com/docs/v2/tune.html) to tune your system.
The error says it cannot handle the incoming connections, i.e. the clients are connecting too fast.
