### ISSUE TITLE
all shared subscriptions receive the same retain message instead of load balance on startup

### ISSUE THREAD

**Issue by liusong1111** [emqx/emqx#1784]
#### Environment

- OS: Ubuntu 14.04
- Erlang/OTP: 
- EMQ: emqx-3.0-beta.1

#### Description

Step 1: 
```bash
mosquitto_pub -t 'hello' -m 'abc' -r
```

Step 2:
run two client, each with:
```bash
mosquitto_sub -t '$share/tasks/hello'
```

The problem: *both* terminals print "abc"
While I expect only *one* print.

After the two clients startup, run:
```bash
mosquitto_pub -t 'hello' -m '123' -r
```

*one* terminal prints "123", it seems ok.

**Comment by jerry-chao** [comment]
maybe mqtt broker cannot do it as what you want. The retained message will send to client when client  connect and you want it only the first client receive the retained msg. if you really don't want miss message and some clients handle it, maybe you can do it by kafka plugin or something else.  By the way, retained message only keep the last one.

**Comment by Gilbert-Wong** [comment]
@jerry-chao  Actually. The retained message will send to client when client subscribe the topic rather than connect to the broker. In his situation,  in former times,  he firstly use mosquitto to pub message which is a retained message before subscribers subscribe it. The retained message would be both published to the subscribers even it is share subscription.However,  in latter times, he has subscribed hello topic so that  the message he received is not retained message and it would follow the shared subscription rule.

**Comment by liusong1111** [comment]
Note the latter time, I published a **retained** message, which is load balanced to **one** subscription. 

The message type of **$share** or **$queue** is invented by **EMQ**, not by MQTT protocol.
So, **What** and **Why** they are born is interpreted by **EMQ**, and what will happen if message is retained is decided by **EMQ**, right?

I think they are about **Load Balance**, but now it's inconsistent and painful to use.

**Comment by Gilbert-Wong** [comment]
First , that is not retained message though the retain flag of this message has been set true because when the message published, you have subscribed the 'hello' topic., Second , the beta version of emqx  3.0 has supported partial features of mqtt 5.0 which support $share subscription. This is the beta version, I did not recommend you use it in the production environment

**Comment by jerry-chao** [comment]
@Gilbert-Wong thanks for your correct and i will have a look at share subscription of mqtt 5.0

**Comment by liusong1111** [comment]
@Gilbert-Wong Thanks for clarify($share is part of MQTT 5.0 protocol). 

I tried emq 2.x, It has the same behavior.

Please ref:
https://github.com/erlio/vernemq/issues/337

https://github.com/erlio/vernemq/issues/808

Back to the original intention, `retained` is for keeping the latest state and will be sent to client when it's connected and subscripted.  `$share` is for load balance. 

Imaging the following scenario:
I'm writing a IoT program named `device_manager`, which subscribes topic `device/+/status`.
 `+` means device_id, `status` is enum of `ready`,`running` or `crashed`.

When a new device comes up, it publishes a retained message(payload is `ready`) to `device/{device_id}/status`, and `device_manager` receives it, and if payload is `ready` or `crashed` then spawn a subprocess to handle the device messages. 

In the subprocess,  start a new MQTT client,  which publish a retained message(payload `running`) to `device/{device_id}/status`, and set the `last will message` as a retained message to topic `device/{device_id}/status` and payload `crashed`.
After that, the subprocess handles the business things, such as subscribing `device/{id}/message_stream` and handle it in loop. 

As `device_manager` or `subprocess` may crash or be killed manually, so I use **retained** and **last will* message to recover when they are restarted.

As `device_manager` can run on multiple server(each with a `device_manager`), I use **$share** staff to handle **Load Balance**.

But things won't go as expected.

A more detail concern is how they are load balanced. the precise way is routing by `device_id`(hash ring or something like that), but things may be  complicated.

**Comment by Gilbert-Wong** [comment]
The strategy you want could not be implemented with emqx now, but we have a schedule to support this strategy in emqx3.0 rc 1.

**Comment by liusong1111** [comment]
Thanks. Good job.

**Comment by Gilbert-Wong** [comment]
This feature has been implemented in the latest version of emqx, please upgrade emqx.
