### ISSUE TITLE
QoS 1 and 2 message length restriction emqx Version 3.0-beta.1

### ISSUE THREAD

**Issue by davorozo** [emqx/emqx#1793]
#### Environment

- OS: Ubuntu 16.04
- Erlang/OTP: 
- EMQ: emqx Version 3.0-beta.1 - Promises of Tomorrow

#### Description

For QoS 1 and 2, is not possible to publish messages larger than 1450 bytes aprox. 
There is no problem with QoS 0 messages, there is no restrictions in message length according to the configuration parameter set in config. 

Please let me know if there is a new configuration in emqx for QoS1 and 2 messages length. 

Thank you.

**Comment by Gilbert-Wong** [comment]
Are you sure you can not publish messages larger than 1450 byte ? I test with a 74 KB message . It was published successfully. The message length could be configured with the parameter `mqtt.max_packet_size`.

**Comment by Gilbert-Wong** [comment]
Maybe the beta version of emqx is not compatible with your mqtt client. Can you tell me which mqtt client do you use?

**Comment by davorozo** [comment]
I’m using jmeter and MQTTBox. The Max packet client is actually configured to 64KB. 
My issue is with QoS 1 and 2 and the client is using mqtt 3.1.1. Any ideas? 

Thank you. 

Enviado desde mi iPhone

**Comment by Gilbert-Wong** [comment]
We didn't reproduce the issue as you say, we need more details.
