### ISSUE TITLE
Auth and ACL Error

### ISSUE THREAD

**Issue by navSharma47** [emqx/emqx#1798]
#### Environment

- OS: Ubuntu 16
- Erlang/OTP: 
- EMQ: 3.0

#### Hi I am new to the Emqx , I am having some issue ,

1. I want to authenticate the client using the clientid , username , password using mySql database.
   right now the client is authenticating successfully with the username and password but It is not 
    taking care of the clientId , but i want to restrict the mqtt client to be connected only when the 
    username , clientid and password is same.
2. I want to restrict the mqtt clinet to publish and subscribe the topic according to the database 
    topic. The mqtt client should not be able to publish and subscribe the other topic then of the 
   database.
   For Example : I want to restrict the client named as testClient to only publish and subscribe to the  
   method .  client/testClient/data1 
   here 
   I want to make a topic like client/clientname followed by /topicdata

  Right now i have done some chanegs and able to restrict the subscribe but I am not able to stop publish of message.

This is my acl.config file

{allow, {user, "dashboard"}, subscribe, ["$SYS/#"]}.

{allow, {ipaddr, "127.0.0.1"}, pubsub, ["$SYS/#", "#"]}.

{deny, all, subscribe, ["$SYS/#", {eq, "#"}]}.

{allow, {client,"%c"}, pubsub, ["clients/%c/#"]}.

{deny, all, subscribe, ["$SYS/#", {eq, "#"}]}.

{deny, all}.

And my db is  : 
for mqtt_user

<img width="685" alt="screen shot 2018-09-07 at 1 49 20 pm" src="https://user-images.githubusercontent.com/36894340/45207164-e0298c00-b2a4-11e8-828c-3e6726e20baf.png">

for mqtt_acl

<img width="796" alt="screen shot 2018-09-07 at 1 49 08 pm" src="https://user-images.githubusercontent.com/36894340/45207212-07805900-b2a5-11e8-9d3b-cf30e957399c.png">

in the above mqtt_acl table i am trying diffrent diffrent topic method but non of them is owrking properly.

*A description of the issue*

**Comment by navSharma47** [comment]
Any update
Regarding this issue. Please let me know. How can i deny a publish .

**Comment by myie9** [comment]
how to config to authenticate the client using the  username , password.  and deny others with wrong usename

**Comment by terry-xiaoyu** [comment]
> I want to authenticate the client using the clientid , username , password using mySql database.
right now the client is authenticating successfully with the username and password but It is not
taking care of the clientId , but i want to restrict the mqtt client to be connected only when the
username , clientid and password is same.

You should config the `auth.mysql.auth_query` in `etc/plugins/emqx_auth_mysql.conf` to select auth entries only when username and client_id are both matched, for example:
`auth.mysql.auth_query = select password from mqtt_user where username = '%u' and client_id = '%c' limit 1`.

Also make sure you have the column `client_id` in table `mqtt_user`, you can create your table as following:
```
use mqtt;
CREATE TABLE `mqtt_user` (
    `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
    `username` varchar(100) DEFAULT NULL,
    `client_id` varchar(100) DEFAULT NULL,
    `password` varchar(100) DEFAULT NULL,
    `salt` varchar(100) DEFAULT NULL,
    `is_superuser` tinyint(1) DEFAULT 0,
    `created` datetime DEFAULT NULL,
    PRIMARY KEY (`id`),
    UNIQUE KEY `mqtt_username` (`username`)
    ) ENGINE=MyISAM DEFAULT CHARSET=utf8;
```

> I want to restrict the mqtt clinet to publish and subscribe the topic according to the database
topic. The mqtt client should not be able to publish and subscribe the other topic then of the
database.

- Keep your acl.conf as clean as possible, as we're using mysql:
```
{allow, {user, "dashboard"}, subscribe, ["$SYS/#"]}.
{allow, {ipaddr, "127.0.0.1"}, pubsub, ["$SYS/#", {eq, "#"}]}.
{deny, all, subscribe, ["$SYS/#", {eq, "#"}]}.
{deny, all}.
```

- You should set `acl_nomatch` in `emq.conf` to deny in your case:
```
allow_anonymous = false
acl_nomatch = deny
```

- For the data in `mqtt_acl` your table posted above is OK.
