### ISSUE TITLE
Remove /mqtt from url

### ISSUE THREAD

**Issue by nerdial** [emqx/emqx#1809]
#### Environment

- OS:  alpine:3.7
- Erlang/OTP:  not sure, using image docker https://github.com/omnys/docker-alpine-emqtt/
- EMQ:  v2.3.4

#### Description

*Is there any way to remove /mqtt from url ?.i checked the documentation could not find anything about it.each time i connect to emqtt socket, i need to add /mqtt at the end of the Url. wondering how i can remove this section from url*
- From : ws://yourdomain.com:port/emqtt
- To : ws://yourdomain.com:port/

**Comment by nerdial** [comment]
tnx a lot

**Comment by terry-xiaoyu** [comment]
Fixed by: https://github.com/emqx/emqx/pull/1814
