### ISSUE TITLE
Windows download for emqx Version 3.0-beta.1 missing

### ISSUE THREAD

**Issue by michaelcplusplus** [emqx/emqx#1810]
#### Environment

- OS: Windows
- Erlang/OTP: Windows 10
- EMQ: EMQ: emqx Version 3.0-beta.1 - Promises of Tomorrow

#### Description
The windows download for emqx Version 3.0-beta.1 missing

**Comment by zhanghongtong** [comment]
[Now you can download the bate2 version of Windows by clicking here](http://emqtt.com/downloads/3001/windows10)

**Comment by michaelcplusplus** [comment]
Thanks a lot!
