### ISSUE TITLE
ClusterStatus badrpc 

### ISSUE THREAD

**Issue by DuKaiming** [emqx/emqx#1816]
#### Environment

- OS: CentOS 7
- Erlang/OTP: R19/8.3
- EMQ: 2.2.0

#### Description
When clients count is 981,cluster's status is Badrpc.
*A description of the issue*
(emqttd@127.0.0.1)1> 14:01:12.068 [error] [error] acceptor on 0.0.0.0:1883 suspend 100(ms) for 2600 emfile errors!!!

(emqttd@127.0.0.1)1> 14:01:12.316 [error] The Node:'emqttd@127.0.0.1' bad rpc, Error: {'EXIT',{badarith,[{emqttd_vm,loads,0,[{file,"src/emqttd_vm.erl"},{line,159}]},{emq_dashboard_overview,node_info,0,[{file,"src/emq_dashboard_overview.erl"},{line,77}]},{rpc,'-handle_call_call/6-fun-0-',5,[{file,"rpc.erl"},{line,197}]}]}}

(emqttd@127.0.0.1)1> 14:01:12.316 [error] Error in process <0.3505.0> on node 'emqttd@127.0.0.1' with exit value:
{emfile,[{erlang,open_port,[{spawn,"\"/usr/lib64/emqttd/lib/os_mon-2.4.2/priv/bin/cpu_sup\""},[stream]],[]},{cpu_sup,start_portprogram,0,[{file,"cpu_sup.erl"},{line,718}]},{cpu_sup,port_server_init,1,[{file,"cpu_sup.erl"},{line,571}]}]}

(emqttd@127.0.0.1)1> 14:01:18.317 [error] Error in process <0.3504.0> on node 'emqttd@127.0.0.1' with exit value:
{{badmatch,{error,timeout}},[{cpu_sup,measurement_server_init,0,[{file,"cpu_sup.erl"},{line,498}]}]}

**Comment by Gilbert-Wong** [comment]
This error means that too many open files. You should tune your linux kernel first. Here is the instruction about how to tune your machine http://emqtt.io/docs/v2/tune.html
