### ISSUE TITLE
SSL EMQX

### ISSUE THREAD

**Issue by satrox28** [emqx/emqx#1820]
#### Environment

- OS: Ubuntu 16.04
- Erlang/OTP: R19/8.2
- EMQ: 2.2

#### Description
I have installed the emqx broker and configured ssl.
listener.ssl.external = 8883
listener.ssl.external.verify = verify_peer

#listener.ssl.external.fail_if_no_peer_cert = true

listener.ssl.external.keyfile = etc/certs/key.pem 

listener.ssl.external.certfile =etc/certs/cert.pem

listener.ssl.external.cacertfile = etc/certs/ca.pem

We are using CA signed SSL certificate and I am trying to connect from MQTT client tools and its working fine.

To test the SSL, I had modified  the certificate which client using with a random character but still am able to connect to the broker via SSL.

Client is using CA root certificate to connect to broker. Do I am missing any?.

**Comment by zhengyupan** [comment]
your configuration is fine. But I am not sure about your modification on the certificate. Usually modifying a cert makes it invalid, instead, you may re-issue a new certificate.

**Comment by satrox28** [comment]
If I modify the certificate in the starting line then its failing, if in middle if I change any it's still able to connect. Any idea?.
