### ISSUE TITLE
OS environment variable for api port

### ISSUE THREAD

**Issue by nerdial** [emqx/emqx#1822]
#### Environment

- OS: Ubuntu
- Erlang/OTP: R21.0
- EMQ: 3.0

#### Description

I believe there should be an env variable for api port, something like EMQ_WS_PORT under the name of :  EMQ_API_PORT

**Comment by Gilbert-Wong** [comment]
This feature would be realized in emqx 3.0-beta.3

**Comment by Gilbert-Wong** [comment]
@nerdial Hi, now you can configure `management.listener.http = 8080` in `etc/plugins/emqx_management.conf` which is the api port.
