### ISSUE TITLE
Standalone MQTT client?

### ISSUE THREAD

**Issue by gotthardp** [emqx/emqx#1825]
Hello. Would you please consider creating a standalone release of the emqx client? Something like emqttc. I would like to use the client, but don't want to include all the dependencies that are required by the server.

**Comment by Gilbert-Wong** [comment]
Of course we have schedule to create a standalone release of the emqx client. Please wait for few days.

**Comment by gotthardp** [comment]
Thanks a bunch!

**Comment by Gilbert-Wong** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [issue#1824](https://trello.com/c/kfBc3lpW/76-issue1824)

**Comment by ginahagg** [comment]
yes, we do need a standalone client with mqtt 5.0. We manage it now in dev phase by creating a client app by taking what we need out of emqx. But that's not a good approach for production. Thanks for reopening it.
