### ISSUE TITLE
How to get a list of clients in a specific topic with api ?

### ISSUE THREAD

**Issue by nerdial** [emqx/emqx#1828]
#### Environment

- OS: alpine:3.7
- Erlang/OTP: 
- EMQ: v2.3.4

#### Description

Is there any way to get a list of client ids in a specific topic. sometimes, in some cases we need a list of client ids, is it possible to consider as a feature in api ?

**Comment by Gilbert-Wong** [comment]
Sorry, we did not have schedule to realize the feature you want now.

**Comment by nerdial** [comment]
how may i contribute to the project ? i would like to implement this feature 
could you give me a hint ?

**Comment by Gilbert-Wong** [comment]
You can fork this project to your own repository, then implement yourself. Look forwarding to your pull request. 👍
