### ISSUE TITLE
SUBSCRIBE with "no local" set does not trigger PUBLISH of retained messages

### ISSUE THREAD

**Issue by ckrey** [emqx/emqx#1832]
#### Environment

- OS: Debian9
- Erlang/OTP: 19
- EMQ: 3.0 beta2

#### Description

PUBLISH a number of retained messages e.g. to topic/one, topic/two, topic/three

SUBSCRIBE to "topic/+" with "no local" set

client does not receive the 3 expected PUBLISHes of the retained topics

**Comment by tigercl** [comment]
Hi @ckrey,
If the value of "No Local" is 0, the retained messages will not be forwarded to a connection with a ClientID equal to the ClientID of the publishing connection. I'm not sure if you publish and subscribe on the same client, and I received retained messages on the another client.

**Comment by ckrey** [comment]
Other implementors don’t see stored retained messages as part of any client session, so the clientid of the PUBLISHING client isn’t relevant for later a SUBSCRIBE.

I asked the same question to Ian Craggs, let's see what his views are

**Comment by tigercl** [comment]
Hi, @ckrey, you can refer to the sepcification, our implementation is in accordance with the sepcification:
>  Bit 2 of the Subscription Options represents the No Local option. If the value is 1, Application Messages MUST NOT be forwarded to a connection with a ClientID equal to the ClientID of the publishing connection.
