### ISSUE TITLE
client disconnect or timeout

### ISSUE THREAD

**Issue by JXT-Eden** [emqx/emqx#1843]
Does the client have a reconnection mechanism if the client is disconnected or if the heartbeat has timed out?Do you need to re-subscribe to the subscribed topics?Whether the message is saved directly to the database?

**Comment by Gilbert-Wong** [comment]
English Please.

**Comment by jidushan** [comment]
Does the client have a reconnection mechanism if the client is disconnected or if the heartbeat has timed out?Do you need to re-subscribe to the subscribed topics?Whether the message is saved directly to the database?

**Comment by Gilbert-Wong** [comment]
emqx is broker rather than client, it has no reconnection mechanism.

**Comment by jidushan** [comment]
> 
> 
> emqx is broker rather than client, it has no reconnection mechanism.

Whether the received message can be saved to the specified database or file

**Comment by terry-xiaoyu** [comment]
@jidushan Message persistence feature is covered in EMQ X Enterprise. It supports persisting messages in to different backends, such as MySQL, PgSQL, MongoDB, Redis, etc.

The topic filter for persistence is configurable in in the plugins.
