### ISSUE TITLE
Connecting to the broker cluster

### ISSUE THREAD

**Issue by tharanga2006** [emqx/emqx#1844]
#### Environment

- OS: CentOS
- Erlang/OTP: 
- EMQ: emqttd-centos7-v2.3.11.zip

I have a 4 broker cluster. and I wanted to subscribe for the cluster. but I was not able to find a place to give "url list" when we starting subscriber. Appreciate if some one  can tell me how to achieve this

**Comment by Gilbert-Wong** [comment]
What “url list” do you mean ?
On Sep 21, 2018, 1:17 PM +0800, tharanga2006 <notifications@github.com>, wrote:
Environment

  *   OS: CentOS
  *   Erlang/OTP:
  *   EMQ: emqttd-centos7-v2.3.11.zip

I have a 4 broker cluster. and I wanted to subscribe for the cluster. but I was not able to find a place to give "url list" when we starting subscriber. Appreciate if some one can tell me how to achieve this

**Comment by Gilbert-Wong** [comment]
I got what you mean. I suppose you need to configure a load balancer for your emqx cluster. The load balancer would expose one url you want.

**Comment by tharanga2006** [comment]
Hi Gilbert,
Thanks.  Cant we handle this using MQTT client library ?.
https://github.com/mqttjs/MQTT.js/#connect

/*******************************
mqtt.connect([url], options)
Connects to the broker specified by the given url and options and returns a Client.

The URL can be on the following protocols: 'mqtt', 'mqtts', 'tcp', 'tls', 'ws', 'wss'. The URL can also be an object as returned by URL.parse(), in that case the two objects are merged, i.e. you can pass a single object with both the URL and the connect options.

You can also specify a servers options with content: [{ host: 'localhost', port: 1883 }, ... ], in that case that array is iterated at every connect.
**********************************/

But Im not sure how to call this properly .

Is anyone use this feature ?

**Comment by Gilbert-Wong** [comment]
I did not use MQTT client. Maybe you can try it , but use a load balancer for cluster is better choice.

**Comment by tharanga2006** [comment]
This works for me
var client  = mqtt.connect(
  {    servers:[
        {
          host: "localhost",
            port: 1890
        },
        {
          host: "localhost",
            port: 1983
        }
    ] })
