### ISSUE TITLE
Incorrect value of Maximum QoS

### ISSUE THREAD

**Issue by zinid** [emqx/emqx#1848]
#### Environment

- OS: Linux (Debian Testing)
- Erlang/OTP: OTP-21
- EMQ: hard to say, I compiled it from git using `make rel`, the last commit in the log is ba2e2fbd

#### Description

The server sets Maximum QoS property in the CONNACK packet with value `2`. However, it's explicitly forbidden to do so:
> It is a Protocol Error to include Maximum QoS more than once, or to have a value other than 0 or 1

http://docs.oasis-open.org/mqtt/mqtt/v5.0/cs02/mqtt-v5.0-cs02.html#_Toc514345356

**Comment by Gilbert-Wong** [comment]
Yes, you are right. We would fix it as quick as possible.

**Comment by Gilbert-Wong** [comment]
Hi, @zinid . The connack packet has not supported mqtt 5.0 specification now. There is no properties in CONNACK packet now. Please read spec again. It said that when this property `Maximum QoS` is absent in CONNACK packet, Client would use qos 2 as maximum qos. The maximum qos is not only used to pass it in CONNACK packet. It has another usage.

**Comment by zinid** [comment]
> There is no properties in CONNACK packet now

LOL wut? 😁 What's [this](https://github.com/emqx/emqx/blob/emqx30/src/emqx_protocol.erl#L484) then? I added `io:format()` and I see this:
```erl
#{'Maximum-Packet-Size' => 1048576,
  'Maximum-QoS' => 2,
  'Retain-Available' => 1,
  'Shared-Subscription-Available' => 1,
  'Subscription-Identifier-Available' => 1,
  'Topic-Alias-Maximum' => 0,
  'Wildcard-Subscription-Available' => 1}
```
> It said that when this property Maximum QoS is absent in CONNACK packet, Client would use qos 2 as maximum qos

Right. But Maximum QoS is not absent, it is there, in the CONNACK packet 😁

**Comment by Gilbert-Wong** [comment]
Yes, you are right. I forgot this code.

**Comment by Gilbert-Wong** [comment]
Now ,i t has been fixed in https://github.com/emqx/emqx/pull/1857#issuecomment-423733540
