### ISSUE TITLE
Beta 3 terrible consistency when receive message in json string

### ISSUE THREAD

**Issue by mzy2240** [emqx/emqx#1860]
#### Environment

- OS: Ubuntu 18.04
- Erlang/OTP:  21.0.5
- EMQ: 3.0 beta 3

#### Description
When using the paho mqtt python client to send a 70kb json string for every half a second, the only subscriber will experience the message burst, which is like some messages will get stuck and at some points the subscriber will receive all stucked messages. The test environment is in a local computer, so no reason for poor connection.
You can use the smallest case in [issue#1811](https://github.com/emqx/emqx/issues/1811) within a loop to reproduce the case. 
Thanks and Happy Mid-Autumn Festival!

P.S: please change the title to "Beta 3 terrible consistency when receive message in json string". Thanks!

**Comment by Gilbert-Wong** [comment]
Would be fixed in beta4.

**Comment by Gilbert-Wong** [comment]
Gotcha.

**Comment by mzy2240** [comment]
@emqplus @Gilbert-Wong I have checked the emqx.conf and my settings are the same as yours above, but still experience the message burst.

**Comment by Gilbert-Wong** [comment]
You should disable this option, cannot be same as above.

**Comment by mzy2240** [comment]
Thanks! Will test it tomorrow.


Sent from my Samsung Galaxy smartphone.
-------- Original message --------From: Gilbert <notifications@github.com> Date: 9/25/18  19:33  (GMT-06:00) To: emqx/emqx <emqx@noreply.github.com> Cc: mzy2240 <mao.mzy@gmail.com>, Mention <mention@noreply.github.com> Subject: Re: [emqx/emqx] Beta 3 terrible consistency when receive message in json string (#1860) 
You should disable this option, cannot be same as above.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/emqx/emqx","title":"emqx/emqx","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/emqx/emqx"}},"updates":{"snippets":[{"icon":"PERSON","message":"@Gilbert-Wong in #1860: You should disable this option, cannot be same as above."}],"action":{"name":"View Issue","url":"https://github.com/emqx/emqx/issues/1860#issuecomment-424545934"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/emqx/emqx/issues/1860#issuecomment-424545934",
"url": "https://github.com/emqx/emqx/issues/1860#issuecomment-424545934",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [emqx/emqx] Beta 3 terrible consistency when receive message in json string (#1860)",
"sections": [
{
"text": "",
"activityTitle": "**Gilbert**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@Gilbert-Wong",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"emqx/emqx\",\n\"issueId\": 1860,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"emqx/emqx\",\n\"issueId\": 1860\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/emqx/emqx/issues/1860#issuecomment-424545934"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 383104821\n}"
}
],
"themeColor": "26292E"
}
]

**Comment by mzy2240** [comment]
Just tested it. After commenting the last line of the config above, it works as it should. Still curious about the application of that burst mode.

**Comment by mzy2240** [comment]
Great work and thank you guys @Gilbert-Wong @emqplus
