### ISSUE TITLE
How do I use shared subscription with Hash or Random policies

### ISSUE THREAD

**Issue by phper-chen** [emqx/emqx#1864]
I have several services running as MQTT clients subscribing to `topic/+`, thus they would all be informed a message if a device sent one to the topic `topic/handshake`.

Does EMQ support shared subscription so that the traffic can be balanced among my services, using `consistent hashing` and/or `random` policy for example? Where can I find the docs? Thanks.

**Comment by lxl5lxl5lxl** [comment]
使用高级特性中的『共享订阅』功能，emq3.0版本支持emq 集群的『共享订阅』

**Comment by phper-chen** [comment]
Thank ur translation for me, that is to say I should use a Prefix "$share" in the sub uri to make the function take effect , isn`t it? But I don't know if this character "$share" is a variable or is it a string like this，can u tell me? thank u~

**Comment by emqplus** [comment]
@phper-chen You can configure the dispatch strategy in `etc/emqx.conf`:

```
## Dispatch strategy for shared subscription
##
## Value: Enum
## - random
## - round_robbin
## - hash
broker.shared_subscription_strategy = random
```

**Comment by phper-chen** [comment]
However, our current EMQ service is 2.0, and I handle EMQ docker "emqttd-docker-v2.3.1" with it. Does '2.0' support this featrue?

**Comment by Gilbert-Wong** [comment]
Sorry, it doesn’t support such strategy.Emqx beta2 support it.
On Sep 26, 2018, 11:37 AM +0800, chen <notifications@github.com>, wrote:

However, our current EMQ service is 2.0, and I handle EMQ docker "emqttd-docker-v2.3.1" with it. Does '2.0' support this featrue?

**Comment by phper-chen** [comment]
Wut a pity...
Then when does your stable version come out? I want to replace the old version.
Thank u any way~

**Comment by terry-xiaoyu** [comment]
@phper-chen The `$shared` prefix works with EMQ 2.x, but it only has the `random` balancing policy. And the shared subscription feature only works on single-node of emq with 2.x. 

So if you are using a single-node emq, and the `random` policy also satisfies you, then everything will be OK. If you do really want use the feature on a emq cluster, there's also a trick available by [combining the $local and $shared](https://www.jianshu.com/p/16d70dc20542) topic prefixes.

**Comment by phper-chen** [comment]
@terry-xiaoyu Thank ur proposal, now I am using a cluster mode EMQ service, and I will have a try as u mentioned above~
