### ISSUE TITLE
Get statics of specific mqtt user or clientID

### ISSUE THREAD

**Issue by ali-zohrevand** [emqx/emqx#1867]
#### Environment

- OS: mac os
- Erlang/OTP:  | R21/10.0.5
- EMQ:  3

#### Description

*Hi.
Is there any way to get statics of specific mqtt user? i've created unique user per device and i want to know  statics of message throughput of per device and user
I've searched for it but i could not find right solution for it.*

**Comment by Gilbert-Wong** [comment]
I think this feature would cost much computing resource and influence the performance of emqx. We need to discuss it tomorrow.

**Comment by c0otlass** [comment]
thanks, i really need it, please consider this feature or some thing like it to get statics of a topic or other similar functionality,
thanks again

**Comment by ginahagg** [comment]
i don't think this is realistic. we mine our logs for this and use exometer (or whatever metrics package you want to use). Even with all that,  definitely a cost on performance and should be only done if diagnosing a performance issue imho.
