### ISSUE TITLE
emq message self publish flag

### ISSUE THREAD

**Issue by watchworld** [emqx/emqx#1874]
#### Environment

- OS: centos7
- Erlang/OTP: 20+
- EMQ: 3.0

#### Description

The `ignore_loop_deliver` flag in `emqx.conf` has been deprecated, how to avoid loop delivery?

**Comment by Gilbert-Wong** [comment]
Hi, @watchworld , emqx 3.0 has partially supported mqtt v5.0 which has sub options to support this feature. According to your issue, I supposed that there are still so many people willing to use this feature in mqtt 3.0, so we would give back this feature in next edition of emqx.

**Comment by Gilbert-Wong** [comment]
It has been fixed in rc.4
