### ISSUE TITLE
Exposing GUID to the consumers? 

### ISSUE THREAD

**Issue by SergeyZSpb** [emqx/emqx#1881]
Hi! As it stated in MQTT standard, clients get packetId which is not a GUID. Inside EMQ, there is GUID assigned to messages. 

It is possible to somehow expose the GUID generated inside distributed EMQ to consumers (for instance, if the logical client is itself distributed and we would like to achieve exactly once semantics without message duplication)? Could you please direct me to the hook or plugin spi I may use for this? Or a place I may take a look at for the later commit and pull request? 

Does enterprise edition provide any solutions for easier building publishers<->dirtibutedEMQ<->distributed consumer kinda system?

Thanks a lot!

**Comment by Gilbert-Wong** [comment]
Sorry for late respond, and I really don't understand what you mean. Inside EMQ, guid is used to generate a client id ,not packet id. The prerequisite you give is wrong.

**Comment by SergeyZSpb** [comment]
np, I was referring to http://emqtt.io/docs/v2/design.html#packetid-and-messageid "A GUID(128-bit globally unique Id) will be generated by the broker and assigned to a MQTT message." 

The statement seems quite clear to me. Is there a way to expose this guid i.e., put it inside the message so that it's available to mqtt consumers? Where would someone who wants this take a look in code? 

Thanks

**Comment by Gilbert-Wong** [comment]
Sorry, I made a mistake, guid is also used to generate packetid and messageid. (They have the same meaning in emqx). According to mqtt spec, the packet id could only be placed in qos1 message and qos2 message. And if your client have access to get qos1 message and qos2 message from broker. Of course the packet ids are exposed.

**Comment by SergeyZSpb** [comment]
Thank you!
