### ISSUE TITLE
Proxy Protocol support for wss?

### ISSUE THREAD

**Issue by utkarshns** [emqx/emqx#1882]
#### Environment

- OS:
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.4 LTS
Release:	16.04
Codename:	xenial

- Erlang/OTP: Erlang/OTP 18 [erts-7.3] [source] [64-bit] [async-threads:10] [kernel-poll:false]
- EMQ: 2.3.11

#### Description
Can the HAProxy proxy-protocol not work with wss (8084) ?
Will shifting the ssl certs to haproxy and connecting to broker cluster unsecured work?
If yes, can somebody please help with the HAProxy config ?

**Comment by utkarshns** [comment]
@all
Anybody tried such a thing?

**Comment by myie9** [comment]
how to config wss ? i've config my websites cert to emq. but not ok.

**Comment by Gilbert-Wong** [comment]
Refer here: http://emqtt.io/docs/v2/config.html.

**Comment by Gilbert-Wong** [comment]
@utkarshns @zhanghongtong would help you config haproxy.

**Comment by utkarshns** [comment]
Hello Gilbert!

Sure. Please find the haproxy config: https://gist.github.com/utkarshns/423aaafb9bbe4b3fabe6840f5f6c24a3#file-haproxy-cfg

Also, trying to use proxy-protocol v1/v2 doesn't work.
server node_2 node2.example.com:8084 check-send-proxy send-proxy-v2

With the proxy-protocol enabled, no client is able to connect to the broker using wss. However, the same proxy-protocol config works for unsecured 1883 (mqtt).
Also, I would like to exercise TLS/SSL termination as I see that the default number of max wss connections is pretty low(64).

**Comment by Eluso** [comment]
Hello utkarshns,

Here the haproxy.cfg i used:
`listen wss`
`    bind *:8084`
`    mode tcp`
`    maxconn 5000`
`    option clitcpka`
`    option srvtcpka`
`    server mqtt-broker-1 node1:8084`
`    server mqtt-broker-2 node2:8084`

Haproxy:haproxy-1.5.14-3.el7.x86_64

**Comment by utkarshns** [comment]
@Eluso 
I am able to get the wss load balanced with HAProxy, what I want along with that is the proxy protocol so that I have the correct IP address of the client.

**Comment by Eluso** [comment]
@utkarshns 
Sorry,I miss some info.
for Proxy Protocol need add the line in etc/emqx.conf
`listener.wss.external.proxy_protocol = on`
`listener.wss.external.proxy_protocol_timeout = 3s`

**Comment by utkarshns** [comment]
Yeah, I tried that already. After doing so the clients can't connect using
wss.
I even put the proxy-protocol-v2 in haproxy config which makes it work for
TCP (1883 and 8883).

**Comment by Eluso** [comment]
Yes,because cowboy not support wss proxy protocol,so until now emq not support yet.

**Comment by Gilbert-Wong** [comment]
Sorry, cowboy does support wss proxy protocol.

**Comment by utkarshns** [comment]
I am not sure what cowboy is. However it's fine if proxy protocol isn't
working with wss.

**Comment by victorclaessen** [comment]
Cowboy seems to be a webserver module for Erlang (the language emq is written in): 
https://github.com/ninenines/cowboy

**Comment by utkarshns** [comment]
Thanks for the info. Will wait for wss with proxy protocol.

**Comment by Gilbert-Wong** [comment]
It has been supported in release of emqx rc.1.
