### ISSUE TITLE
How can I get the remote ip by mqtt? 

### ISSUE THREAD

**Issue by phper-chen** [emqx/emqx#1893]
#### Environment

- OS: 
- Erlang/OTP: 
- EMQ: 

#### Description

*A description of the issue*

Hi! friend:
I want to get the remote IP address of some device at the mqtt communication, but I can not find something about it. Can u give me a hand? thank U~

**Comment by Gilbert-Wong** [comment]
Hey, @phper-chen , the mqtt protocol works above tcp/ip layer. So you cannot directly get IP address from mqtt commuication. Maybe you can bind the ip info as part of client id for mqtt clients to provide ip information.

**Comment by phper-chen** [comment]
Yes, I can get Intranet IP address easily, but I can not get the External network IP address,
And I see the External network IP addresses at client dashboard web with 18083 port that EMQ provide,  that is to say,  EMQ knows it.

**Comment by Gilbert-Wong** [comment]
Of course EMQ knows it. But mqtt message itself does not carry the client ip information, so you can not directly get remote IP address of via mqtt communication. EMQ X provide Restful API to view clients remote ip. You can refer [here](http://emqtt.io/docs/v2/rest.html#retrieve-a-client-on-a-node). The broker would return a json data which include the remote ip you want.

**Comment by phper-chen** [comment]
It is great~Thank u~
