### ISSUE TITLE
Upgrade 2.3.* to 3.0

### ISSUE THREAD

**Issue by edgiru** [emqx/emqx#1904]
#### Environment

- OS: Ubuntu 16.04.5
- Erlang/OTP:  
- EMQ: 2.3.3

#### Description

How to upgrade to version 3.0?
If it is not possible how to remove the old version correctly?

**Comment by Gilbert-Wong** [comment]
Download the version 3.0 of emqx and stop version 2.3.3 of emqx and then you just need to stop the old version emq and start new version emq.

**Comment by arihantdaga** [comment]
I am also using prebuilt binaries on ubuntu. Is that the only way @Gilbert-Wong . That way with every new update, we'll have to reconfigure plugins and emqx.conf. And simply replacing files could also be dangerous if previous version config are not compatible with the newer version. 
I noticed a file called `install_upgrade_escript` in bin folder. I was wondering if that is intended for this reason, but i could not successfully run that script either.

**Comment by Gilbert-Wong** [comment]
Yeah, @arihantdaga , configuration migration for emqx update is really headache for us and our users. We have a schedule to introduce toml to emqx which aims to simplify the configuration logic.

**Comment by k32** [comment]
Hello,
EMQ X currently supports configuration import/export and migration: https://docs.emqx.io/en/broker/v4.3/advanced/data-import-and-export.html
This feature can be used to upgrade EMQ X without losing configuration. I hope this helps.
