### ISSUE TITLE
emq service deny new connection

### ISSUE THREAD

**Issue by E-brain-child** [emqx/emqx#1906]
#### Environment
- OS: ubuntu 1604  & ubuntu 1404
- Erlang/OTP: 
- EMQ: V230& V239 & V2310

#### Description
**Status：**
    start emqttd program and load web hook plugin, and post data to the url configured in webhook. The web server is just used to receive connect, disconnect and publish action data and interact with database.
**Problem：**
    It is frequently occurred that the port 1883 and 8083 deny new connections, we have to restart emqttd to solve this problem.

a.mqtt client（device and app) cannot connect to mqtt server.
b.emqttd dashboard is accessible.
c.use `lsof -i:1883` to check if the mqtt process which occupy 1883 port is still alive.
d.use `./emqttd_ctl status` to check emqttd status and it returned `Node 'emq@127.0.0.1' is started` which means that emqttd work properly. 

Attachment；Error log：
      http://note.youdao.com/noteshare?id=498d1e4416aecd627ace1b4c51d2a2a1
**question：**
   According to our test result, we suspect that maybe the lack of server memory cause this problem. Please tell me can you conclude reason from the information I provide?

**Comment by Gilbert-Wong** [comment]
@E-brain-child I can not infer the problem from your error log. As you say, it is possible that the insufficient of memory cause your problem. Could you please give me more information such as the hardware info, `etc/emq.conf` file , the number of the connections you created and so on?

**Comment by E-brain-child** [comment]
There are only 10 connections in case of failure;hardware information and etc/emq.conf file in this link:
http://note.youdao.com/noteshare?id=498d1e4416aecd627ace1b4c51d2a2a1

**Comment by Gilbert-Wong** [comment]
The error shows that your web server is not stable so that sometimes emqx-web-hook would request timeout.

**Comment by terry-xiaoyu** [comment]
What topics are the subscribers subscribing to? And what topics the publishers sent to? How many subscribers and publishers do you have? And what about the publishing speed?

BTW, try to set mqtt.cache_acl = false if you don't use ACL plugins.
