### ISSUE TITLE
Incorrect user name or password can also be verified.

### ISSUE THREAD

**Issue by hongdanyang1991** [emqx/emqx#1907]
#### Environment

- OS: mac os 10.13.6
- Erlang/OTP: 21 [erts-10.1.1]
- EMQ: 3.0

#### Description
emqx_auth_mysql. version 3.0. 
Incorrect user name or password can also be verified When entering user name and password

**Comment by Gilbert-Wong** [comment]
We'll check this problem.

**Comment by Gilbert-Wong** [comment]
Make sure that your emqx_auth_mysql is loaded and you have turned off the allow_anonymous option.
