### ISSUE TITLE
emqttAutocluster exception

### ISSUE THREAD

**Issue by NewBorn25** [emqx/emqx#1912]
#### Environment

- OS: centos 7.0
- Erlang/OTP: 
- EMQ: 2.3

#### Description

*A description of the issue*
We deployed emqtt through docker and k8s managed.when we start emqtt,the logs of following happend probability
   3Z']:emqttd start
   12:15:54.614 [error] Autocluster exception: function_cla

**Comment by terry-xiaoyu** [comment]
@NewBorn25 Could you post more detailed logs and your configurations here?

**Comment by zhanghongtong** [comment]
@NewBorn25 Where did you get the docker image? Is the version `v2.3.0`? Also, I noticed that your k8s-apiserver is port 443. This is usually used to provide HTTPS services instead of kube-api. Can you confirm that you can access kube-apiserver from this address?

**Comment by NewBorn25** [comment]
@zhanghongtong 
emqtt docker version is v2.3
![image](https://user-images.githubusercontent.com/26791729/47949787-d8742400-df83-11e8-8656-785119c6d3e4.png)
we deploy emqtt cluster based on k8s,like this 
![image](https://user-images.githubusercontent.com/26791729/47949767-8a5f2080-df83-11e8-942a-4c245f37fb5d.png)
EMQ_CLUSTER__K8S__APISERVER is the service ip of k8s

**Comment by NewBorn25** [comment]
Actually we deploy emqtt success and it works normally,but Sometimes this happens after a long period of work.
     - name: EMQ_CLUSTER__K8S__APISERVER
          value: http://172.31.22.81:8080
I notice that your EMQ_CLUSTER__K8S__APISERVER is not your service IP of service/kubernetes?which IP it is?
Recently it reported log "Autocluster exception:function_clause",and it can't work again ,I'm not sure the are the same problem or not .

**Comment by NewBorn25** [comment]
OK,another simple question ,this represent the version of emqtt is V2.3.0?
![image](https://user-images.githubusercontent.com/26791729/47982532-1059a380-e10b-11e8-9eaa-676510f62a0a.png)
maybe the question come from our emqtt version need to update

**Comment by zhanghongtong** [comment]
@NewBorn25 Yes, you can try to update emq to v2.3.11
