### ISSUE TITLE
The authentication is invalid

### ISSUE THREAD

**Issue by 1129921824** [emqx/emqx#1915]
#### Environment

- OS: ubuntu1604
- Erlang/OTP: R19/8.3-- R21/10.0.5
- EMQ: 2.3.10/2.3.11/3.0 beta1

#### Description

I can connect to MQTT over SSL using any user name and password

**Comment by Gilbert-Wong** [comment]
Please state your issue clearly. I don't know what you mean. I will close this issue, please open a new issue and make sure your issue is clear and detailed.
