### ISSUE TITLE
Incorrect user name or password can also be verified.

### ISSUE THREAD

**Issue by 1129921824** [emqx/emqx#1917]
Environment
OS: ubuntu1604
Erlang/OTP: R21/10.0.5
EMQ: 3.0 beta1

Description
I am sorry that I don't speak clearly.The problem is:
when I use mqtt client connect to mqtt server,
I can use incorrect username and password.
For example,The default username is admin and password is public,
I use adminxxx and public xxx also connect mqtt.I has closed
anonymous and open mysql auth.

**Comment by Gilbert-Wong** [comment]
https://github.com/emqx/emqx/issues/1916
