### ISSUE TITLE
In cluster mode, the api/v3 interface on port 8080 is unstable to obtain the info from some clienId

### ISSUE THREAD

**Issue by phper-chen** [emqx/emqx#1924]
#### Environment

- OS: unbuntu 16.04.4 LTS
- Erlang/OTP: docker
- EMQ: 3.0

#### Description

*The restful interface provided by EMX3.0 is unstable. In cluster mode, when the device is online, the interface often has 500 internal errors, but sometimes it is good.*
`
*git@AMS-API:/root$ curl -v --basic -u appId:secret -k *http://internalIP:8080/api/v3/connections/02931117C6B1B279
*   Trying 192.168....
* Connected to 192.168.... (192.168.....) port 8080 (#0)
* Server auth using Basic with user 'dbaa5e70f350d'
*> GET /api/v3/connections/02931117C6B1B279 HTTP/1.1
*> Host: 192.168......:8080
*> Authorization: Basic *ZGJhYTVlNzBmMzUwZDpNamcwTVRneU5qTTNNekl3TkRZeE5qRTNNVEE1TXpBNE5EY3hNRGd4T*mprM01qSQ==
*> User-Agent: curl/7.47.0
*> Accept: */*
*> 
*< HTTP/1.1 200 OK
*< content-length: 562
*< content-type: application/json
*< date: Sat, 27 Oct 2018 08:54:13 GMT
*< server: Cowboy
*< 
* Connection #0 to host 192.168...... left intact
*[{"clean_start":true,"client_id":"02931117C6B1B279","connected_at":"2018-10-27 *04:23:15","heap_size":6772,"ipaddress":"10.255.0.2","is_bridge":false,"is_super":false,"keepalive":*60,"mailbox_len":0,"mountpoint":"undefined","node":"97a347535bc7@10.0.0.5","peercert":"nossl"*,"port":41142,"proto_name":"MQTT","proto_ver":4,"recv_cnt":1732,"recv_msg":1729,"recv_oct":56**6924,"recv_pkt":1732,"reductions":423775363,"send_cnt":3365,"send_msg":1633,"send_oct":212*464,"send_pend":0,"send_pkt":3365,"username":"02931117C6B1B279","will_topic":"undefined","z*one":"external"}]

#### **Wrong response**

*git@AMS-API:/root$ curl -v --basic -u appId:secret -k *http://192.168....:8080/api/v3/connections/02931117C6B1B279
*   Trying 192.168.....
* Connected to 192.168.... (192.168.....) port 8080 (#0)
* Server auth using Basic with user 'dbaa5e70f350d'
*> GET /api/v3/connections/02931117C6B1B279 HTTP/1.1
*> Host: 192.168.....:8080
*> Authorization: Basic *ZGJhYTVlNzBmMzUwZDpNamcwTVRneU5qTTNNekl3TkRZeE5qRTNNVEE1TXpBNE5EY3hNRGd4T*mprM01qSQ==
*> User-Agent: curl/7.47.0
*> Accept: */*
*> 
*< HTTP/1.1 500 Internal Server Error
*< content-length: 14
*< content-type: text/plain
*< date: Sat, 27 Oct 2018 08:54:30 GMT
*< server: Cowboy
*< 
* Connection #0 to host 192.168.200.155 left intact
*Internal Error
`

**Comment by terry-xiaoyu** [comment]
Could you post the emq logs here, when the HTTP response is 500 ?

**Comment by phper-chen** [comment]
Hi, when could ur team handle this problem?  We have some business requirements associated with this API, should I roll back version 2.0?

**Comment by Gilbert-Wong** [comment]
3.0 is still a release candidate edition. We would fix this problem as quick as quickly.

**Comment by phper-chen** [comment]
> 3.0 is still a release candidate edition. We would fix this problem as quick as possible.

@Gilbert-Wong Thank you very much~

**Comment by phper-chen** [comment]
Hi, add a content that this bug has been occurred in verision-----emqx-docker-v3.0-rc.1

**Comment by Gilbert-Wong** [comment]
Please update to emqx-docker-v3.0-rc.3 to try again, and please give us the logs and your etc/config files.

**Comment by phper-chen** [comment]
@Gilbert-Wong yes, I had a try again with rc.3 and it works well in version of rc.3. But I think I should test the stability of this version.Thanks~

**Comment by phper-chen** [comment]
@Gilbert-Wong Im so sorry, it was my fault that tested it in a single node env and it works, But in a cluster mode, it still shows internal server error randomly. So I think it is a special case only at the cluster mode. Maybe the reason is the rebalance strategy that the EMQ use.

**Comment by Gilbert-Wong** [comment]
It has been fixed in rc.4

**Comment by phper-chen** [comment]
Thanks, I will have a try~
