### ISSUE TITLE
Failed to load the emq_auth_mysql plugins

### ISSUE THREAD

**Issue by JiangLiguoME** [emqx/emqx#1927]
#### Environment

- OS:      ubuntu 16.04LTS
- Erlang/OTP: 
- EMQ: 2.3.1
-MySQL: 5.7.3

#### Description
I just cannot load the emq_auth_mysql plugins.

My config is:
```
##--------------------------------------------------------------------
## MySQL Auth/ACL Plugin
##--------------------------------------------------------------------

## MySQL server address.
##
## Value: Port | IP:Port
##
## Examples: 3306, 127.0.0.1:3306, localhost:3306
auth.mysql.server = 127.0.0.1:3306

## MySQL pool size.
##
## Value: Number
auth.mysql.pool = 8

## MySQL username.
##
## Value: String
auth.mysql.username = "root"

## MySQL password.
##
## Value: String
auth.mysql.password = "my mysql passwd here"
```
The log shows that:
```
2018-10-27 21:46:50.138 [error] <0.1676.0> CRASH REPORT Process <0.1676.0> with 0 neighbours exited with reason: no match of right hand value {error,{shutdown,{failed_to_start_child,emq_auth_mysql,{shutdown,{failed_to_start_child,worker_sup,{shutdown,{failed_to_start_child,{worker,1},{1045,<<"28000">>,<<"Access denied for user ''@'localhost' (using password: NO)">>}}}}}}}} in emq_auth_mysql_app:start/2 line 33 in application_master:init/4 line 134
```

I don't know why emq cannot load my username or passwd!
Can anyone help me?
Thanks.

**Comment by terry-xiaoyu** [comment]
Remove the double quotation marks and try again, like this:
```
## Mysql Username
auth.mysql.username = root

## Mysql Password
auth.mysql.password = emqtt

## Mysql Database
auth.mysql.database = mqtt_test
```

**Comment by JiangLiguoME** [comment]
> Remove the double quotation marks and try again, like this:
> 
> ```
> ## Mysql Username
> auth.mysql.username = root
> 
> ## Mysql Password
> auth.mysql.password = emqtt
> 
> ## Mysql Database
> auth.mysql.database = mqtt_test
> ```

Thank you!
I tried it,but failed.And it showed the same wrong Error.
Then I tried to change to emqx version 3.0 and succeeded.
It seems that the version of mysql server isnot compatible.
