### ISSUE TITLE
How can I configure the revocation list

### ISSUE THREAD

**Issue by yunanxing** [emqx/emqx#1929]
#### Environment

- OS: windows 7
- Erlang/OTP: 
- EMQ:  EMQ 2.0

#### Description

Does EMQ support verification of certificate revocation?
If I revoke the certificate, the client should not be able to connect.But I can't find anywhere to be able to configure the revocation list.

**Comment by Gilbert-Wong** [comment]
Sorry, @yunanxing , not support yet.

**Comment by Jeyanthinath** [comment]
@gilbertwong96 any possible future plans for this ? and do you have any workaround for a time being ?

**Comment by gilbertwong96** [comment]
What about put a haproxy ahead the emqx cluster ?

**Comment by qiulian111** [comment]
I also meet this issue, is a big security issue for me, any possible future plans or workaround for this?

**Comment by gunnarpieter** [comment]
Same here, how can we think about security with certs and not be able to revoke?

**Comment by zmstone** [comment]
For ref, related SSL listener options:
https://erlang.org/doc/man/ssl.html#type-crl_check
https://erlang.org/doc/man/ssl.html#type-crl_cache_opts
We need to make them configurable.

**Comment by mononym** [comment]
This is on our radar, though I cannot give an estimation of when this will be completed. In the long run we need to support OCSP as well and so we are trying to make sure we approach this in the correct way.

@gunnarpieter, @qiulian111, and @Jeyanthinath, do you need the remote HTTP checks for certificate revocation or would the functionality for files in a local directory which can be checked be enough for your use cases? For a example of what I am talking about you can see [this](https://github.com/erlang/otp/blob/master/lib/ssl/test/ssl_crl_SUITE.erl#L153) line of an OTP test suite which uses this mechanism.

**Comment by gunnarpieter** [comment]
@mononym for HTTP i think an OCSP is best but i read up on this. And think its not as doable and CRLs are a better way.
https://discourse.haproxy.org/t/ocsp-on-haproxy/716/7


Anyway, I changed my view and believe that in front of any proper EMQx broker a load balancer i best. That could handle this much better and leave more processing room for EMQx to do communication/traffic handling.

**Comment by Ali-iotechsys** [comment]
Hello, I've noticed in your latest release  (**v5.0.22**) that CRL check been added for TLS MQTT listeners. 
However, I could not find any docs on how to configure it. Please could you guide me how to enable this feature?
Many thanks in advance.

**Comment by id** [comment]
@Ali-iotechsys work in progress https://github.com/emqx/emqx-docs/pull/1814

**Comment by Ali-iotechsys** [comment]
That sound great thanks
