### ISSUE TITLE
Ussing SSL cert I get Username 'undefined' although relevant config option is set.

### ISSUE THREAD

**Issue by petergerten** [emqx/emqx#1932]
#### Environment

- OS: Ubuntu 18.04
- EMQ: 3.0 rc2

#### Description
In my config I have:
`listener.ssl.external.peer_cert_as_username = cn`

I connect via ssl/cert:
`mosquitto_sub -t abc -h 172.17.0.2 -p 8883 -d --key MyClient1.key --cert MyClient1.pem --cafile MyRootCA.pem --insecure`

Output from mosquitto_sub:
```
Client mosqsub|9615-p51 sending CONNECT
Client mosqsub|9615-p51 received CONNACK (5)
Connection Refused: not authorised.
Client mosqsub|9615-p51 sending DISCONNECT

```
EMQ Log:
`2018-10-30 04:01:28.188 [error] <0.1875.0>@emqx_logger:error:51 MQTT(mosqsub|9127-x33@172.17.0.1:54096): Username 'undefined' login failed for username_or_password_undefined`

Expected behavior:
the CN of the certificate is used as username. I verified the CN of the cert via openssl - it is not empty.

Further Clarification:
I use emqx_auth_mongo. If i disable auth and disable the plugin I can connect via cert.
But I need auth for non-cert uses.

**Comment by jerry-chao** [comment]
you are missing username and password args for mosquitto_sub and you should add -u {Username} -P {Password}

**Comment by petergerten** [comment]
@jerry-chao thanks.

If I add username and password I get this error:

`Username 'certuser' login failed for auth_modules_not_found`

I don't know what that means (I have mongo auth plugin enabled which works fine using wss).
But despite the error message the username did not get replaces with the username.
```
listener.ssl.external.peer_cert_as_username = cn
listener.ssl.external.verify = verify_peer

```

**Comment by jerry-chao** [comment]
there are no auth_modules because mongo auth plugin was not enabled 
please check your plugins like this  
![image](https://user-images.githubusercontent.com/11730593/47847191-6e357500-de05-11e8-950a-4e16b3a3e153.png)

**Comment by petergerten** [comment]
@jerry-chao 
As I said it is activated. I use it with a wss client succesfully. When I then try to use ssh/cert I get the auth_modules_not_found error.

emqx_ctl plugins list shows
`Plugin(emqx_auth_mongo, version=3.0, description=EMQ X Authentication/ACL with MongoDB, active=true)
`

**Comment by jerry-chao** [comment]
i test it by myself local.  It print auth_modules_not_found when there are no user data in mongodb

```
Username 'xxxx' login failed for auth_modules_not_found
```
It connect  successfully after I add the userdata to mongoDB.  I try it with mqttbox in mqtt/tcp and mqtt/ws

It will print password_error if the password is error, and returnCode equal 5
```
Username 'xxx' login failed for password_error
```

**Comment by petergerten** [comment]
@jerry-chao again - I am using a wss client with mongodb auth successfully.
I also verified with
`db.mqtt_user.find()`
that I actually have users in there. (In my case I have 5 users)

**Comment by petergerten** [comment]
@jerry-chao Can you please also try to do this with ssl/cert? - as this is my use case that fails.

**Comment by jerry-chao** [comment]
I try it with ssl/cert and below is my command 

```
mosquitto_sub -h localhost -p 8883 --insecure --cafile etc/certs/cacert.pem -u demo -P 123456  -i demotcp  -t 'demo'
```
the server print some log like this
```
14:26:46.468 [debug] MQTT(127.0.0.1:49558): RECV <<16,33,0,4,77,81,84,84,4,194,0,60,0,7,100,101,109,111,116,99,112,0,4,100,101,109,111,0,6,49,50,51,52,53,54>>
14:26:46.468 [debug] MQTT(@127.0.0.1:49558): RECV CONNECT(Q0, R0, D0, ClientId=demotcp, ProtoName=MQTT, ProtoVsn=4, CleanStart=true, KeepAlive=60, Username=demo, Password=******)
14:26:46.469 [debug] this is UserMap #{<<"_id">> => {<<91,219,237,74,30,136,160,132,155,177,142,97>>},<<"is_superuser">> => false,<<"password">> => <<"123456">>,<<"salt">> => <<"plain">>,<<"username">> => <<"demo">>}
14:26:46.470 [debug] MQTT(demotcp@127.0.0.1:49558): SEND CONNACK(Q0, R0, D0, AckFlags=0, ReasonCode=0)
14:26:46.470 [debug] MQTT(127.0.0.1:49558): SEND <<32,2,0,0>>
14:26:46.470 [debug] MQTT(127.0.0.1:49558): Keepalive at the interval of 45
14:26:46.470 [debug] MQTT(127.0.0.1:49558): RECV <<130,9,0,1,0,4,100,101,109,111,0>>
14:26:46.470 [debug] MQTT(demotcp@127.0.0.1:49558): RECV SUBSCRIBE(Q1, R0, D0, PacketId=1, TopicFilters=[{<<"demo">>,
                                                                                                                                                #{nl => 0,qos => 0,rap => 0,rc => 0,rh => 0}}])
14:26:46.471 [debug] MQTT(demotcp@127.0.0.1:49558): SEND SUBACK(Q0, R0, D0, PacketId=1, ReasonCodes=[0])
14:26:46.471 [debug] MQTT(127.0.0.1:49558): SEND <<144,3,0,1,0>>
```
Sorry I cannot  reproduce your scenario locally and maybe there is none business with ssl/cert. And you can add some log to check it clearly , such as before and after Mod:check.

**Comment by Gilbert-Wong** [comment]
Please show me your CN of your certification.

**Comment by petergerten** [comment]
> I try it with ssl/cert and below is my command
> 
> ```
> mosquitto_sub -h localhost -p 8883 --insecure --cafile etc/certs/cacert.pem -u demo -P 123456  -i demotcp  -t 'demo'
> ```
I am confused. Where are you using a cert in that example?
I can't see the `"--cert"` and `"--key"`  parameters. There is only the cert for the rootCA.

**Comment by jerry-chao** [comment]
@petergerten I am so sorry for misunderstanding the question.  Client checked server's certificate, but the server donot request client's certificate.   You want to verify the client certificate.  And I try to add config like 

```
listener.ssl.external.peer_cert_as_username = cn
listener.ssl.external.verify = verify_peer
```

retry it with etc/certs/client-cert.pem 
```
mosquitto_sub -h localhost -p 8883 --insecure --cafile etc/certs/cacert.pem --key etc/certs/client-key.pem --cert etc/certs/client-cert.pem -i demotcp -u demo -P 123456  -t 'demo' -d
```

check the CN of client-cert.pem
```
zhangchao@zhangchao:~/work/github.com/emqx-rel% openssl x509 -noout -subject -in etc/certs/client-cert.pem
subject= /CN=MacBook-Air.local/O=client
```
Add new client to db
```
db.mqtt_user.insert({username: "MacBook-Air.local", password: "123456", salt: "plain", is_superuser: false})
```

I can login it successfully.

Finally I recheck  the command which you have run, you missed -u and -P args.  I reproduced your case with below command
```
mosquitto_sub -h localhost -p 8883 --insecure --cafile etc/certs/cacert.pem --key etc/certs/client-key.pem --cert etc/certs/client-cert.pem -i demotcp  -t 'demo' -d 
```

The username which you passed with args will be replaced by the CN of the client certificate.  You can check it https://mosquitto.org/man/mosquitto_sub-1.html
![image](https://user-images.githubusercontent.com/11730593/48999968-2818ca80-f193-11e8-901e-364084ee33da.png)
You must set password and username both.

You can try it with -u ${AnyName} and -P ${password}

**Comment by petergerten** [comment]
@jerry-chao thanks! Will try this.

**Comment by juwalter** [comment]
@petergerten were you ever able to solve this? I am having a similar issue #2972 (however, using Redis for ACL)

**Comment by petergerten** [comment]
@juwalter no, unfortunately not. I will get back looking into this soon now. Did you get further?

**Comment by juwalter** [comment]
heh, not really, I ended up terminating SSL at the Kubernetes Ingress (istio)

I did have a look into the erlang sources back then but had trouble getting everything setup and compile locally and then gave up
