### ISSUE TITLE
stop getting messages after a while.

### ISSUE THREAD

**Issue by MyraBaba** [emqx/emqx#1934]
#### Environment

- OS: MAc OS x 
- Erlang/OTP: erts-9.0
- EMQ: emqttd 2.3.4

#### Description
I am using emqtd for communication between C++ and python in the same server.

I am sending picture+text byte array around 80 KB each.

C++ sending ,  emqtd receving and python receiving messages through subscried channel.

After a while around after 350 message python stopping gettign message or emqtd stop sendin I dont know which one is happening.

Total messages is around 2000 and each of them around 80KB. 

I dont understadn why.

When I test only smal text messages both is working very fast and without problem.

DO I need to make a config ?

**Comment by tigercl** [comment]
Hi, @MyraBaba, Can you provide more emqttd's debug logs when this problem occurs? It can help us locate the problem. You can open the debug information with the following command:
`lager:set_loglevel(lager_console_backend, debug).`

**Comment by MyraBaba** [comment]
Dear @tigercl 
What I was found that message size limit was the problem so I increased the allowed message size than all is ok now.

Best wishes for you
