### ISSUE TITLE
To deny anonymous is invalid

### ISSUE THREAD

**Issue by dotyso** [emqx/emqx#1937]
#### Environment

- OS: centos 7.2
- Erlang/OTP: 
- EMQ:  emqx 3 rc.2 docker

#### Description
1.  set conf file to deny anonymous at emqx.conf:
![b3ec082f-996d-42f6-b82f-46be70f89f62](https://user-images.githubusercontent.com/2305796/47771350-e1fc5280-dd1d-11e8-8a5e-da6d0f8a6fa7.png)

2.  restart emqx:
`bin/emqx restart`
                         
3. enable username plugin and then add user:
```
./bin/emqx_ctl plugins load emqx_auth_username
./bin/emqx_ctl users add chasevalves 1234
```
![c50835ad-6927-4895-8dbe-90b1104c0b64](https://user-images.githubusercontent.com/2305796/47771413-12dc8780-dd1e-11e8-8bc8-818e92ede9ea.png)

4. to publish msg by mosquitto_pub

is correct: 
![23dbf341-1a07-43f2-b6aa-aafb2d7710b2](https://user-images.githubusercontent.com/2305796/47771141-102d6280-dd1d-11e8-8120-879bc5b6de11.png)

is correct: 
![10bc3418-e415-4666-95a3-80b5fa6ff222](https://user-images.githubusercontent.com/2305796/47771179-2fc48b00-dd1d-11e8-8db1-0fe20cf4c010.png)

**!!!!!!!!  but anonymous is still valid: !!!!!!!**
![ec250b79-679e-4459-9d9a-2974c53b9c14](https://user-images.githubusercontent.com/2305796/47771289-a5305b80-dd1d-11e8-9131-c6bd258e1d89.png)

**Comment by Gilbert-Wong** [comment]
Hi, @dotyso , did you disable the item `allow_anonymous` in emqx.conf?

**Comment by Gilbert-Wong** [comment]
After disable the `allow_anonymous` option, you should stop emqx then start emqx to take configuration into effect. Restart could not reload emqx.conf
