### ISSUE TITLE
Client disconnect on packet receive

### ISSUE THREAD

**Issue by archerian** [emqx/emqx#1938]
#### Environment

- OS: Windows
- Erlang/OTP: Builtin 
- EMQ: 2.3.10

#### Description
The broker randomly disconnects the client when a large binary packet is received. Large as a around 100KB. I tested the same client with mosquitto server, no problem with the same packet sizes.

**Comment by Gilbert-Wong** [comment]
What is the `Built in` meaning? You do not know the erlang/OTP version installed on your system, right? Can you show me the emq.conf you use? How did you config this item `mqtt.max_packet_size = 64KB`?

**Comment by archerian** [comment]
Hello Gilbert-Wong, thanks for your reply.

I am using Erlang that came with the Emqtt package, which is R20/9.0. mqtt.max_packet_size I have set to 50MB

**Comment by Gilbert-Wong** [comment]
I test this edition of emqx, and set mqtt.max_packet_size = 50 MB, send 1MB size of message, but did not reproduce the problem you stated. Could you please give me your error.log to provide more details?
