### ISSUE TITLE
question regarding notifications when device is disconnected

### ISSUE THREAD

**Issue by ljubo2015** [emqx/emqx#1939]
#### Environment

- OS: Windows 10
- Erlang/OTP:Builtin
- EMQ: 3.0-rc.2

#### Description - Question
Is there option to get notification when device is connected or disconnected, as i need to manage devices and i don't want to GET all the time api/v3/connections. I have found out that this was possible in version 2.x , can you please let me know how this was replaced in version 3.x? 
This topic: https://github.com/emqx/emqx/issues/1089

**Comment by Gilbert-Wong** [comment]
This is also possible in version 3.x
