### ISSUE TITLE
Question about Bridge and Cluster Subscriptions

### ISSUE THREAD

**Issue by protostartup** [emqx/emqx#1945]
#### Environment

- OS: Ubuntu
- Erlang/OTP: Erlang/OTP 20 [erts-9.3.1] [source] [64-bit] 
- EMQ: 2.3.0

#### Description

I have configured 2 Emq Cluster (A, B) each containing 2 Nodes (1, 2). I understand that subscription in the cluster is distributed in all the nodes. So all the nodes will have the same list of subscriptions at any point.

Now, I make a bridge between A1 and B2 on "***/#***" topic and there exist a Subscription on node B2(/Anything). So when I publish a msg on node A1 on topic "****/Anything****" 

1a.  Since there is a subscription on B2 the msg gets passed to the node B2 obviously, But does the msg go to Node B1 also since it is in the same cluster?? (I also see a subscription on Node B1 for the same.

2a. So since subscription exist on all the nodes, Publishing on node A2 and subscribing on B1 should work, But it is not working. What am I missing in the context 

![bridge3-2nsubs](https://user-images.githubusercontent.com/40563115/47950826-022a4c80-df7e-11e8-8b98-9d2cedf5b379.png)

**Comment by Gilbert-Wong** [comment]
Please refer [here](http://emqtt.io/docs/v2/cluster.html#cluster-design)

**Comment by protostartup** [comment]
Hi Gilbert,

Just read the doc you referred, My question is If Cluster A has Node A1 and A2 and Cluster B has node B1 and B2 and there exists a Bridge A2 ---/# ----- B2,

If I subscribe for a topic on A1 and Publish for the same topic on B1 will I receive the Msg???

**Comment by Gilbert-Wong** [comment]
Yes, you will.

**Comment by protostartup** [comment]
Why does the bridge node create 4 subscriptions ?? Any idea about that??

**Comment by protostartup** [comment]
The above setup was not working, This was because the bridge subscriptions are local to the node. 
Anyhow I solved the issue by making the subscriptions shared. 

Thanks for the help
