### ISSUE TITLE
how many message per scond emqx could handle?

### ISSUE THREAD

**Issue by ali-zohrevand** [emqx/emqx#1947]
#### Environment

- OS: ubuntu 18.04
- Erlang/OTP: 20
- EMQ:  3

#### Description

*Hi,
how many massage emqx could handle per second from single node? is there any stress test for it?
i read [this](https://github.com/emqx/emqx/issues/1167) issue but there was not any answer in it.
thanks
*

**Comment by Gilbert-Wong** [comment]
It depends on your hardware.

**Comment by ali-zohrevand** [comment]
let me ask better question.
what is minim hardware to achive handling emqx 40000 message/persecond  from single node?

**Comment by Gilbert-Wong** [comment]
If you have a machine which has 8 core cpu and 8G memory and you just want to send qos 0 message, that's enough.

**Comment by jinfahua** [comment]
> let me ask better question.
> what is minim hardware to achive handling emqx 40000 message/persecond from single node?

The message throughput is determined by several factors, you could refer to [FAQ](https://developer.emqx.io/docs/tutorial/en/faq/faq.html#q-how-to-estimate-resource-usage-of-emq-x) for the resource estimation.  

I suggest you to make a performance test against your biz scenario, and different tools can be leveraged, such as [JMeter MQTT plugin](https://github.com/emqx/mqtt-jmeter).

**Comment by terry-xiaoyu** [comment]
If you are considering choose a appropriate system config, 32 CPU and 16G memory is enough. The size of memory is related to the number of concurrent connections you have.

**Comment by terry-xiaoyu** [comment]
16G memory can support 1 million concurrent connections.
