### ISSUE TITLE
1 Publisher + 50K MSG/Sec = 100% CPU on one core.

### ISSUE THREAD

**Issue by Think7** [emqx/emqx#1952]
#### Environment

- OS: CentOS 7 64 Bit
- Erlang/OTP: R21/10.0.5
- EMX: 3.0
- Hardware: VMWare VM 4 Core @ 2.8GHZ / 4GB RAM

#### Description

Greetings,

We are attempting to publish 50,000 48-byte MSGS/Sec to single EMQX node via a single publisher on a single topic with QOS set to 0. 

This results in 100% usage on only one of the CPU cores. The others remain close to idle and RAM usage remains minimal.

Implementing the steps in the Tuning Guide did not appear to have an impact. CPU utilization remained pinned at 100% on the one core.

Do you have any suggestions on how to resolve this?

Note:
I've considered opening multiple connections to the broker however i would think this could cause messages to be received out of order. Preserving message order is vital.

Thanks for your time!

**Comment by Think7** [comment]
Something else (completely unrelated) i've noticed is running "systemctl emqx stop" takes about 3 mins to complete. Starting is instant.

**Comment by terry-xiaoyu** [comment]
Would you think

**Comment by Gilbert-Wong** [comment]
We have changed default logger from lager to erlang/otp logger. And it consumes a lot of computing resources and we have fixed it, in emqx3.0-rc.4, this issue should be fixed.

**Comment by Think7** [comment]
Thank you! Is this version available via YUM? Or should i just wait for emqx 3.1?

**Comment by Gilbert-Wong** [comment]
Hi, @Think7 , the emqx 3.0.0 has been released this week, we have do a log of optimize work. You could try with it again.
