### ISSUE TITLE
emqx_auth_http how to tell client bad user name or password

### ISSUE THREAD

**Issue by boboxiaodd** [emqx/emqx#1953]
#### Environment

- OS: centos7
- Erlang/OTP: 21
- EMQ: 3.0rc2

#### Description

*A description of the issue*
i use emqx_auth_http to auth client
but it can't tell client  "bad user name or password"

in mqtt protocol:
0 | Connection Accepted
4 | Connection Refused, bad user name or password
5 | Connection Refused, not authorized

**Comment by boboxiaodd** [comment]
@terry-xiaoyu   
when  client A connected with a same client_id of client B,  client B will be kickout ,
client B reconnect , will recv "bad user name or password" or "not authorized"   and stop reconnect

**Comment by tigercl** [comment]
@boboxiaodd Please confirm that the username and password used by your client are correct. Client B can be kick out by client A, and A can be kick out by B too if your username and password are correct.

**Comment by boboxiaodd** [comment]
@tigercl  i know , but client will reconnect which  be kickout, it's loop
client need a flag to know it is be kickout , and stop reconnect , so i need  4 or 5 flag return

**Comment by boboxiaodd** [comment]
@tigercl  our client will logout  when recv "bad user name or password" , so i need  emqx_auth_http can return flag 4

**Comment by tigercl** [comment]
@boboxiaodd If you want the server to return an "bad user name or password" when client has the correct password, we can't do it.

**Comment by boboxiaodd** [comment]
@tigercl  i use emqx_auth_http , correct password it return 200, bad password it return 4xx,
but client recv a disconnect , not flag 4

**Comment by Gilbert-Wong** [comment]
vernemq do the wrong thing, if your password and username are correct, mqtt should not return the flag 4 or 5, it doen't follow the semantic of mqtt spec.

**Comment by Gilbert-Wong** [comment]
Describe your scenario more detailed, I tried to understand what you mean, there are two client with the same clientid? And client A is connected, client B want to connect to the broker, both of your clients have reconnect mechanism, and if client B has connected  to the broker, client A would be kicked out without sending any packet. What you want? you want to let client B receive connack packet with flag return code 4 or 5 before connect to let your client stop loop to reconnect to broker ??? According your description , I assume that the the protocol you use is mqtt3.0, but the disconnect packet could only be delivered from client to server rather server to client in this version of mqtt protocol. I still do not understand the meaning of what you say  -- `but client recv a disconnect, not flag 4`.

**Comment by boboxiaodd** [comment]
@Gilbert-Wong 
our client recv flag 4 will stop reconnect,  how to do it with emqx ?
i use emqx_auth_http , my boss will not do change client code.

**Comment by Gilbert-Wong** [comment]
The opensource edition of emqx do not provide customized service like this which violate the mqtt 3.0 spec. Please contack with @zhengyupan for enterprise edition of emqx.

**Comment by boboxiaodd** [comment]
> @boboxiaodd如果您希望服务器在客户端使用正确的密码时返回“错误的用户名或密码”，我们就无法做到。

client's password is wrong , in emqx_auth_http , i return 40X,   but emqx_auth_http can't return flag 4 ,
