### ISSUE TITLE
How to know which client id is present

### ISSUE THREAD

**Issue by nerdial** [emqx/emqx#1955]
#### Environment

- OS: Ubuntu
- Erlang/OTP: 
- EMQ: 3

#### Description

Presence module was deprecated in version 2. is it still usable in version 3 ? if not, how may i know which user is present and which one is absent ? i need s.th similar to presence module or $SYS message and i have to check that programmatically not in dashboard.
thank you in advance

**Comment by Gilbert-Wong** [comment]
Hi, @nerdial , it is usable in version 3 now. Please try with the emqx3.0-rc3.

**Comment by nerdial** [comment]
Thanks a million

**Comment by nerdial** [comment]
another question, how may i use this feature in emqtt ? can  presence module detect ungraceful disconnect as well ?

**Comment by Gilbert-Wong** [comment]
`presence module` cannot detect ungraceful disconnect, you should use will msg to notify `ungraceful disconnect` action.

**Comment by nerdial** [comment]
is there any example for using it ? (will msg)

**Comment by Gilbert-Wong** [comment]
Please read mqtt spec, you can set will msg in your connect packet.
