### ISSUE TITLE
emqx docker fail unzip

### ISSUE THREAD

**Issue by giraffe-tree** [emqx/emqx#1959]
#### Environment

- OS: CentOS 7.2
- Erlang/OTP:  emqx-3.0-rc.3 
- EMQ: emqx-3.0-rc.3 

#### Description

use emqx-3.0-rc.3   with docker 

how to reappearance: 

1. ``` wget http://www.emqtt.com/downloads/3007/docker```

2. ```unzip docker```

return:

```
Archive:  docker
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of docker or
        docker.zip, and cannot find docker.ZIP, period.
```

**Comment by zhanghongtong** [comment]
Sorry, we have some negligence in making the docker zip file. You can use `docker pull emqx/emqx:v3.0-rc.3` to load our image on the [docker hub](https://hub.docker.com/r/emqx/emqx/tags/).
