### ISSUE TITLE
Impossible to publish a message with MQTT v5 User-Property

### ISSUE THREAD

**Issue by manifest** [emqx/emqx#1970]
#### Environment

- OS: macOS
- Erlang/OTP: 21
- EMQ: emqx30 (0785841 )

#### Description

At the moment it is impossible to publish a message that includes MQTT v5 User-Property using `emqx_client` because of error in type validation. There is a [PR](https://github.com/emqx/emqx/pull/1969) with fix.

**Comment by Gilbert-Wong** [comment]
Thanks for your pull request.
