### ISSUE TITLE
Incorrect docker image zip(3.0-rc.3) in emqtt official web

### ISSUE THREAD

**Issue by phper-chen** [emqx/emqx#1971]
#### Environment

- OS: ubuntu
- Erlang/OTP: 
- EMQ: 3.0-rc.3

#### Description

*A description of the issue*

![image](https://user-images.githubusercontent.com/20152358/48686936-cd62fa00-ebf9-11e8-837a-f46fc90d115c.png)

**Comment by zhanghongtong** [comment]
You need to execute unzip and then execute load
```
$ unzip emqx-docker-v3.0-rc.3.zip
Archive:  emqx-docker-v3.0-rc.3.zip
  inflating: emqx-docker-v3.0-rc.3
$ sudo docker load < emqx-docker-v3.0-rc.3
b598a212fb12: Loading layer  8.192kB/8.192kB
07d875135be8: Loading layer  56.54MB/56.54MB
741e8600eba9: Loading layer  11.78kB/11.78kB
d036ce3aacb7: Loading layer  34.11MB/34.11MB
Loaded image: emqx-docker-v3.0-rc.3:latest
```
Or you can load our image directly using `docker pull emqx/emqx:v3.0-rc.3`

**Comment by phper-chen** [comment]
thanks~
