### ISSUE TITLE
EMQ Authentications and permissions per topic

### ISSUE THREAD

**Issue by Marina190489** [emqx/emqx#1974]
Hi,
Is it possible in EMQ 2.2 to define authentications per topic?
for example if I have permissions for a specific topic I'll be able to subscribe only to this topic.

**Comment by lzh2nix** [comment]
hi, Marina190489, you can check http://emqtt.io/docs/v2/config.html#allow-anonymous-and-acl-file

I'm using v2.3.11 and it's worked for me.
