### ISSUE TITLE
How to send msg to specify client id, the point to point

### ISSUE THREAD

**Issue by vus520** [emqx/emqx#1982]
want to know  Best practices for PTP using.  We want to send msg to some specify client one time.

**Comment by Gilbert-Wong** [comment]
You mean P2P? Sorry, I dont't know what you mean.

**Comment by vus520** [comment]
P2P means point to point.

eg. ClientA and ClientB both subscribe TOPIC_XXX, but if you want to send a msg to ClientA only, you will understand the "MQTT P2P" issue.

If every client subscribe one self topic, so how can i send msg to these topic in one time?

**Comment by Gilbert-Wong** [comment]
You can set json format in mqtt payload, and set client id property to filter the message. You can decode this json to implement the p2p feature you want.

**Comment by vus520** [comment]
Happy to see the new version released. I did not see this issue mentioned in the release log, l'd like to know emq support p2p msg now?
