### ISSUE TITLE
No log record in case acl config is malformed

### ISSUE THREAD

**Issue by 0xfadeef** [emqx/emqx#1983]
#### Environment

- OS: any
- Erlang/OTP: 
- EMQ: 2.3.10

#### Description

In case acl configuration file is malformed and `acl reload` has failed, no log message is generated. Which is very confusing.

**Comment by tigercl** [comment]
Hi, @0xfadeef. Which authentication plugin are you using?

**Comment by 0xfadeef** [comment]
Hello, @tigercl! We are using `emq_auth_username` plugin.

**Comment by tigercl** [comment]
Sorry for the late reply, `emq_auth_username` doesn't have acl rule, are you referring to something in the `emq_auth_username.conf`?

**Comment by 0xfadeef** [comment]
I was talking about ACL file for `internal` module, by default it's located at `etc/acl.conf`. Afaik `acl reload` command reads only this single file.

**Comment by tigercl** [comment]
I got it, your suggestion is great, we will fix it as soon as possible.

**Comment by 0xfadeef** [comment]
Thank you, @tigercl! Really appreciate your work.
