### ISSUE TITLE
In the new version 3.0+, will emq  cluster support $queue?

### ISSUE THREAD

**Issue by ruijf** [emqx/emqx#1986]
#### Environment

- OS: CentOS Linux release 7.3.1611 (Core) 
- Erlang/OTP: 
- EMQ: 2.3.9

#### Description

For HA, I setup emq  cluster and several consumers subscribe topic by using $queue prefix,but I found  $queue only work on single node. And now I use Nginx stream balance two emq node, one for master, and the other for backup. Although It works but it's not really HA, I need to restart all emq node  when the backup back. 
In the new version 3.0+, will emq  cluster support $queue?

**Comment by Gilbert-Wong** [comment]
Yes.
