### ISSUE TITLE
EMQTT Web socket not working

### ISSUE THREAD

**Issue by ranvijayj** [emqx/emqx#1988]
#### Environment

- OS: Ubuntu 16.04
- Erlang/OTP: 
- EMQ: 2.3.11

#### Description

*I am running EMQTT on three ports. 2 tcp and 1 WS. The WS port 5432 comes up and I can see it on the sever but on the browser I can't seem to make WS running. The other 2 TCP ports I am able to publish and subscribe*
On the browser I get 

```
WebSocket connection to 'ws://ENDPOINT:5432/mqtt' failed: Connection closed before receiving a handshake response
```

**Comment by ranvijayj** [comment]
Also, sometimes first connection on WS fails and after that starts working.

**Comment by ranvijayj** [comment]
No, that was just a typo. @Gilbert-Wong

**Comment by Gilbert-Wong** [comment]
So which websocket client did you use? And could you please provide your error.log of emqx?

**Comment by ranvijayj** [comment]
That's the thing nothing related to this on the server side. 
on the browser I get 

```
WebSocket connection to 'ws://Endpoint:5432/mqtt' failed: Connection closed before receiving a handshake response
```

This is when I open the browser the first time and try to connect to MQTT. Subsequent requests go through and I get a green like in the below screenshot and starts connecting smoothly:

![screen shot 2018 11 26 at 6 16 54 pm](https://user-images.githubusercontent.com/10911504/49014903-98c9e200-f1a7-11e8-9751-d7e286028d77.png)

**Comment by Gilbert-Wong** [comment]
I still do not think it is the problem of emqttd. We have connected to the broker thousands of times via websocket interface with emqx-dashboard or mqttbox. And there is no such problem you encountered. So I want to know whether it is caused by your websocket client.

**Comment by ranvijayj** [comment]
I will check if I can make a debug build for my web JS SDK and share logs with you. 
I made some more changes around acceptors and all. 
Right now first connection fails. I refresh and then it keeps connected.
