### ISSUE TITLE
Simpler way to increase the max memory for EMQTT

### ISSUE THREAD

**Issue by ranvijayj** [emqx/emqx#1989]
#### Environment

- OS: Ubuntu 16.04
- Erlang/OTP: 
- EMQ: 2.3.11

#### Description

1. I have 2 2GB Memory machines where I am testing out Emqtt. How do I increase the max available memory for EMQTT broker on that machine? Max it is showing as around 500MB. I could not find any setting for that in emq.conf.  I want atleast 1500MB/2000MB to be available to the broker.

2. Also, there is high watermark and low watermark 
mqtt.mqueue.low_watermark = 30% 
mqtt.mqueue.highwatermark = 70% 
how do these work?  The node in the screenshot where memory show is around 490MB i changed watermark to 30 & 70 from default 20 & 60 so total memory has gone down somehow. 

![screen shot 2018-11-26 at 5 14 03 pm](https://user-images.githubusercontent.com/10911504/49014521-6a97d280-f1a6-11e8-98e6-aac52bed6b4e.png)

**Comment by Gilbert-Wong** [comment]
The mqueue is prepared for mqtt session and for qos1 or qos2 messages. Please read our [documentation](http://emqtt.io/docs/v2/config.html#mqtt-message-queue)

**Comment by ranvijayj** [comment]
Thanks, but can you tell me about the first point in my issue?

**Comment by Gilbert-Wong** [comment]
For emqx, more connections more memory consumed. And how to reserve memory for emqx, it depends on you, right?

**Comment by ranvijayj** [comment]
I understand @Gilbert-Wong 
But why does is show total as around 500MB on a 2GB server. It is a simple installation. I don't find the max memory even in the init script.

**Comment by Gilbert-Wong** [comment]
Because your connections to emq broker is not enough.

**Comment by ranvijayj** [comment]
I got it. Thanks.
