### ISSUE TITLE
Best working HAproxy config

### ISSUE THREAD

**Issue by rjbaat** [emqx/emqx#1990]
I have a question about EMQ behind HAproxy.
What is the best configuration? 
Sometimes my cluster restarts and then the client thinks he is still connected but he is actually not.
So no data is incoming on the subscription and i have to manually restart the client.
I use Node red with a default keep alive of 60 sec. 
My HA proxy config looks like:

```
defaults
  log global
  mode tcp
  option  tcplog
  timeout connect 5s
  timeout client 90s
  timeout server 90s

listen mqtt
    bind *:1883
    mode tcp
    maxconn 50000
    default_backend emq_cluster
    timeout client 3h
    timeout server 3h
    option clitcpka
    option srvtcpka

listen mqtt-ssl
    bind *:8883 ssl crt /cert/cert.pem
    mode tcp
    maxconn 50000
    default_backend emq_cluster
    timeout client 3h
    timeout server 3h
    option clitcpka
    option srvtcpka

backend emq_cluster
    mode tcp
    balance leastconn
    server mqtt-broker-1 xxx.xxx.xxx.xxx:xxx check send-proxy
    server mqtt-broker-2 xxx.xxx.xxx.xxx:xxx check send-proxy
    server mqtt-broker-3 xxx.xxx.xxx.xxx:xxx check send-proxy
```
Do you guys have a better config or suggestions on how to get the connection more stable and have it check better if the connection is actually alive?

**Comment by rjbaat** [comment]
Also emqtt thinks the connection to the cluster does exist when the same user reconnects but to another node. This happens with clients with persistent sessions.

**Comment by arihantdaga** [comment]
I am facing the same issue. This is my config
```
listen mqtt
  # MQTT binding to port 1885
  bind domain.com:24231
  bind domain.com:24232 ssl crt /etc/haproxy/certs/domain.com.pem
  bind domain2.com:24231

  maxconn 100000

  # communication mode (MQTT works on top of TCP)
  mode tcp
  option clitcpka # For TCP keep-alive
  timeout client 3h #By default TCP keep-alive interval is 2hours in OS kernal, 'cat /proc/sys/net/ipv4/tcp_keepalive_time'
  timeout server 3h #By default TCP keep-alive interval is 2hours in OS kernal
  option tcplog
  # balance mode (to choose which MQTT server to use)
  balance leastconn
  # MQTT server 1
  server mqtt_1 PRIVAYTE_IP:1883 check send-proxy-v2
  # MQTT server 2
  server mqtt_2 PRIVAYTE_IP:1883 check send-proxy-v2

  log         127.0.0.1 local2 err


```

Can someone help me figure out the right way to configure it..

**Comment by rjbaat** [comment]
What iam going to try is to use: 
balance source instead of
balance leastconn. 
This way a connection is remade to the same backend i suppose?

**Comment by rjbaat** [comment]
Hmm still got the problem. Last night all connections of all devices where down. There is no real issue and aim not sure what the problem was. All devices seams connected. But no data/msg where incoming. So its more like a false positive connection. Anyone an idea what this could cause?

**Comment by Eluso** [comment]
@rjbaat Your HAproxy looks good,I'm not very clear about your usage scenarios,some suggest:
1.Set reconnect at client.
2.Set same keepalive client,ha,emqx

**Comment by reedF** [comment]
I meat the same issue in Haproxy ,but when using nginx to proxy emq, auto reconnect work well.
Why?

**Comment by aaamitsingh** [comment]
Any update on this?

**Comment by emqplus** [comment]
@zhengyupan Please check the issue

**Comment by zhengyupan** [comment]
@aaamitsingh We are trying to reproduce this issue, our engineer is on it, will update here when we get progress.

**Comment by mononym** [comment]
Apologies for this getting lost in the shuffle. There is a blog post [here](https://www.emqx.com/en/blog/mqtt-broker-clustering-part-2-sticky-session-load-balancing) which gives details on how to set up sticky sessions with HAProxy.
