### ISSUE TITLE
Change the Dashboard http port while running on docker

### ISSUE THREAD

**Issue by sraghunathan** [emqx/emqx#1991]
#### Environment

- OS: CentOS
emq 2.3.11

#### Description

I'm tring to modify the dashboard.listener.http from 18083 8081 so just tried that

sudo docker run --rm -ti --name emqx1 -p 8080:8081 -e EMQX_DASHBOARD__LISTENER__HTTP= 8081 emqx:latest

but its not working, is there any way to modify the port?

**Comment by zhanghongtong** [comment]
Sorry, our configuration file does not now support changing the listening port of the dashboard, but you can map the 18083 port of the docker container to other ports on your host, like this:
```
sudo docker run --rm -ti --name emqx1 -p 8080:18083 emqx:latest
```
