### ISSUE TITLE
Client disconnecting after every 3 messages

### ISSUE THREAD

**Issue by ranvijayj** [emqx/emqx#1994]
#### Environment

- OS: 16.04
- Erlang/OTP: 
- EMQ: 2.3.11

#### Description

*I am using EMQTT 2.3.11. So, I send and receive messages via EMQTT. After every 3rd or 4th message MQTT subscribe on client fails. Then I refresh the page or reload the client, connect again and then I receive messages. It works fine for 10-20 seconds then stops working

Any limitations of the config I might be missing?

Also, if I send same messages 3-4 times in the same session could that be an issue? *

**Comment by ranvijayj** [comment]
sometimes I also see Duplicated subscribe: ancs/sds/fbfbd79fb989d8789fa3daf96dc85d7f, qos = 1 in logs

**Comment by tigercl** [comment]
Hi, @ranvijayj, sorry for the late reply, could you provide some log files about this issue?

**Comment by zsb7798169** [comment]
When we stop client for a while,our client will receive duplicate messages and be forced to disconnect,and I can see  Duplicated subscribe too,our version is 2.3.10,qos level is one,is the same problem?

**Comment by Gilbert-Wong** [comment]
Did you set retain flag as true when you publish messages? And how about `clean session` flag?

**Comment by zsb7798169** [comment]
clean session is false,retain flag is true

**Comment by Gilbert-Wong** [comment]
Please show me your etc/emqx.conf and your log file which could help me resolve your issue.

**Comment by Gilbert-Wong** [comment]
@zsb7798169 Have your problem been resolved?
