### ISSUE TITLE
One instance can't subscribe and publish at same time

### ISSUE THREAD

**Issue by nosixtools** [emqx/emqx#1997]
#### Environment

- OS: CentOS7.5
- Erlang/OTP: R21
- EMQ: 3.0-rc4

#### Description

*A description of the issue*
same clientId can't subscribe and publish at same time

**Comment by nosixtools** [comment]
the version of 3.0-rc3 can subscribe and publish use one instance of client

**Comment by Gilbert-Wong** [comment]
Sorry, could you please tell me how do you use one client to subscribe and publish messages at the same time？For example, which client did you use, it would help us find the problem.

**Comment by Gilbert-Wong** [comment]
@nosixtools please check your emqx.conf, and find out the mqtt.ignore_loop_deliver item to make sure its value is false.

**Comment by nosixtools** [comment]
Thanks for your solution
