### ISSUE TITLE
EMQTT mqueue.max_length cannot be set to infinity

### ISSUE THREAD

**Issue by pramodhkp** [emqx/emqx#2002]
#### Environment

 EMQ:
v2.3.4

#### Description

mqtt.mqueue.max_length cannot be set to infinity as suggested in the documentation (http://emqtt.io/docs/v2/config.html#mqtt-message-queue)

```
13:44:17.627 [error] Error generating configuration in phase transform_datatypes
13:44:17.628 [error] Error transforming datatype for: mqtt.mqueue.max_length
13:44:17.628 [error] "infinity" cannot be converted to a(n) integer
```
--

**Comment by spring2maz** [comment]
Hi @pramodhkp 
Thanks for reporting to us.
This is a bug in document.
I checked the code, it never allows `infinity` for this config.
Please use value `0` instead (it is treated as `infinity` in code).

We'll update the doc.
