### ISSUE TITLE
Faild to start emqx-auth-mysql plugin

### ISSUE THREAD

**Issue by Rebellioncry** [emqx/emqx#2014]
#### Environment

- OS: docker
- Erlang/OTP: docker
- EMQ: v3.0-rc.4

#### Description
After my tests, I found the following problems：
1.emqx-auth-mysql plugin can not connect to MySQL 8.0
2.emqx-auth-mysql plugin can not connect to MySQL when MySQL enable ssl

Q:Are these really there or am I doing something wrong?Hope you reply to me,thanks!

**Comment by Gilbert-Wong** [comment]
Hi, @Rebellioncry , Could you please provide your config and log information?

**Comment by Rebellioncry** [comment]
I am sorry to reply so late.
Here is the configuration file and log file.
[log.zip](https://github.com/emqx/emqx/files/2647928/log.zip)
This configuration file can be used on mysql5.7, but only changed the ip address to mysql8.0, other configurations are unchanged, emqx is given an error.Please check it.

**Comment by zhanghongtong** [comment]
Regarding the problem that mysql8.0 can't connect, there is an idea that mysql8.0 uses the caching_sha2_password plugin to encrypt the password by default. You need to change it to mysql_native_password, and then try to connect.
```
mysql> use mysql;
Reading table information for completion of table and column names
You can turn off this feature to get a quicker startup with -A

Database changed
mysql> select host, user, plugin from user;
+-----------+------------------+-----------------------+
| host      | user             | plugin                |
+-----------+------------------+-----------------------+
| %         | root             | caching_sha2_password |
| localhost | mysql.infoschema | caching_sha2_password |
| localhost | mysql.session    | caching_sha2_password |
| localhost | mysql.sys        | caching_sha2_password |
| localhost | root             | caching_sha2_password |
+-----------+------------------+-----------------------+
5 rows in set (0.00 sec)

mysql> ALTER USER 'root'@'%' IDENTIFIED WITH mysql_native_password BY 'you password';
Query OK, 0 rows affected (0.07 sec)

mysql> flush privileges;
Query OK, 0 rows affected (0.01 sec)

mysql> select host, user, plugin from user;
+-----------+------------------+-----------------------+
| host      | user             | plugin                |
+-----------+------------------+-----------------------+
| %         | root             | mysql_native_password |
| localhost | mysql.infoschema | caching_sha2_password |
| localhost | mysql.session    | caching_sha2_password |
| localhost | mysql.sys        | caching_sha2_password |
| localhost | root             | caching_sha2_password |
+-----------+------------------+-----------------------+
5 rows in set (0.00 sec)

```

**Comment by Rebellioncry** [comment]
@zhanghongtong Thank you for your answer,I also thought about the problem that may be caused by the new password mechanism of mysql8.0.But why can't emqx support compatibility?Just like java uses java driver, you can connect directly to mysql8.0 without changing the code.And I hope you can answer the second question.Can emqx connect mysql when mysql use ssl?Just like java driver set  "usessl = true".I look forward to your reply.

**Comment by zhanghongtong** [comment]
Sorry,` emqx-auth-mysql` does not currently support ssl connection, and mysql 8.0 new password mechanism, these features are in our development schedule, but not now

**Comment by Rebellioncry** [comment]
@zhanghongtong Ok, I know, thank you for your reply.
