### ISSUE TITLE
Build fails:  No rule to make target 'gen_coap.d'

### ISSUE THREAD

**Issue by mkrusemark** [emqx/emqx#2020]
#### Environment

- OS: armhf
- Erlang/OTP: 21
- EMQ: v3.0-rc.5 

#### Description

Build of v3.0-rc.5 fails with
make[1]: Entering directory '/root/emqx-rel/deps/emqx_coap'
make[2]: Entering directory '/root/emqx-rel/deps/gen_coap'
 XYRL   core_link_scanner.xrl core_link_parser.yrl
Compiler function leex:compile/3 failed:
{undef,[{leex,compile,
              ["/root/emqx-rel/deps/gen_coap/src/core_link_scanner",
               "/root/emqx-rel/deps/gen_coap/src/core_link_scanner",
               {options,[],"/root/emqx-rel/deps/gen_coap/src",undefined,[],1,
                        true,999,[],[],"/root/emqx-rel/deps/gen_coap"}],
              []},
        {erl_compile,compile_file,4,[{file,"erl_compile.erl"},{line,307}]},
        {erl_compile,compile3,3,[{file,"erl_compile.erl"},{line,288}]},
        {erl_compile,'-compiler_runner/1-fun-1-',1,
                     [{file,"erl_compile.erl"},{line,92}]}]}
make[2]: *** No rule to make target 'gen_coap.d'.  Stop.
make[2]: Leaving directory '/root/emqx-rel/deps/gen_coap'
make[1]: *** [../../erlang.mk:313: deps] Error 2
make[1]: Leaving directory '/root/emqx-rel/deps/emqx_coap'
make: *** [erlang.mk:312: deps] Error 2

**Comment by tigercl** [comment]
I have not reproduced this problem, dependencies you fetched may be incomplete because of bad network, so I suggest you can delete these dependencies and try again.

**Comment by mkrusemark** [comment]
@GilbertxWong: you are right! Installing the whole Erlang stuff on Debian Sid solves this issue. Thanks:-)

**Comment by mkrusemark** [comment]
Ticket can be closed.
