### ISSUE TITLE
EMQ takes up a lot of memory and cannot be freed

### ISSUE THREAD

**Issue by sylnkk** [emqx/emqx#2024]
#### Environment

- OS: 
- Erlang/OTP: 
- EMQ: 

#### Description
![default](https://user-images.githubusercontent.com/535491/49430920-36946100-f7e7-11e8-9423-6dc8fcbb181c.png)

[emq(1).conf.txt](https://github.com/emqx/emqx/files/2643130/emq.1.conf.txt)

EMQ takes up a lot of memory and cannot be freed.
How can i do?

*A description of the issue*

**Comment by Gilbert-Wong** [comment]
Hi, @sylnkk , please provide more details. For example, which version of emqx do you use, what the scenario you encountered with emqx and did you tune your linux ? Look forwarding to your reply.

**Comment by sylnkk** [comment]
EMQ Version：2.3.9
Centos Version：6.8
We use EMQ for three-terminal message push (android:tcp, ios:tcp, web:ssl).
By the way, we don't use haproxy.
All of our clients use qos0 links to emq for subscribe, and i use EMQ HTTP API to push message.

I keep EMQ start for several days, and the maximum number of clients per day is less than 2000.
I found that the EMQ take up more and more memory，and the memory cannot be freed.
How can i do to take down the memory?

This is the Dashboard Image
![default](https://user-images.githubusercontent.com/535491/49486901-32b21e80-f87b-11e8-95de-5eb5c4ee9c5e.png)

This is the emq.conf.
[emq.conf.txt](https://github.com/emqx/emqx/files/2646933/emq.conf.txt)

**Comment by ikoo** [comment]
we met the same problem, and have no idea

**Comment by ranvijayj** [comment]
Any update here?

@sylnkk 
1. Did you try to reduce the message retention time for clients? Make it to 1d or something less and try. 
2. Also, decreasing the timeout for clients connections helps reduce memory. 
3. What are the number of acceptors you have set for all the listeners?

**Comment by sylnkk** [comment]
@ranvijayj 

How can i reduce the message retention time?
I've decreased the timeout for clients, but the memory cannot be freed too.
listener.ssl.external.acceptors = 16

**Comment by Gilbert-Wong** [comment]
Sorry for late reply, maybe you could configure the `zone.external.session_expiry_interval` and `zone.external.max_mqueue_len` to reduce the memory consumption.
