### ISSUE TITLE
When nginx user is not www-data and proxy to dashboard, emqx in docker will crash

### ISSUE THREAD

**Issue by andares** [emqx/emqx#2025]
#### Environment

- OS: Docker emqx/emqx in Ubuntu 16.04
- Erlang/OTP: 21?
- EMQ: 3.0 rc-5

#### Description

crash condition:

1. nginx user is not www-data (same as docker user)
2. create a new container with ```docker-compose up -d```

use browser to visit dashboard, it will be blank page and will crash in twice visit.

> if nginx user is www-data when create container, and change user to other (same as docker user) will be ok.

**Comment by zhanghongtong** [comment]
Can we look at your `docker-compose.yml` file?

**Comment by andares** [comment]
you can see it in this issue: 

https://github.com/emqx/emqx/issues/2023

Could I send a mail to you?

**Comment by zhanghongtong** [comment]
Of course, you can send me an email. Also, is your nginx running on the host machine or running in the docker container?

**Comment by andares** [comment]
no, docker image is not changed.

**Comment by zmstone** [comment]
closing this issue due to inactive for long.
not sure if the issues is still relevant, but 3.x is rather old and out of our maintenance window
