### ISSUE TITLE
must execute two commands before normal startup succeeds

### ISSUE THREAD

**Issue by JXT-Eden** [emqx/emqx#2030]
- OS: win10 64bit
- Erlang/OTP: R19/8.3
- EMQ: 2

#### Description

sorry,my english is very poor!

after the computer starts, use the command "emqttd start"，wait a long time can not start,exit the current command and input emqttd start normal startup again

**Comment by Forsure-Wang** [comment]
I am experiencing the same problem.Frequently I need execute command “emqttd console” and press ctrl+c to console it and run "emqttd console" again,only in this way can emq startup successfully. Not solved.

**Comment by zhanghongtong** [comment]
Are you executing the command in `cmd` or in `powershell`?

**Comment by Forsure-Wang** [comment]
> Are you executing the command in `cmd` or in `powershell`?

In cmd.
This problem only occurs the first time emq runs on a computer.
It seems that this is not a serious problem.

**Comment by JXT-Eden** [comment]
> > Are you executing the command in `cmd` or in `powershell`?
> 
> In cmd.
> This problem only occurs the first time emq runs on a computer.
> It seems that this is not a serious problem.
> 
> I mean, if you restart the computer and then run "emqttd console" command in cmd,this problem occurs.

me too

**Comment by zhanghongtong** [comment]
Which version of emqx are you using? I am using the latest version of `v3.0-rc.5` and have not reproduced this problem.

**Comment by JXT-Eden** [comment]
> Which version of emqx are you using? I am using the latest version of `v3.0-rc.5` and have not reproduced this problem.

2.3.11

**Comment by Gilbert-Wong** [comment]
By the way, linux is the best place to deploy emqx. `emqx` has bad performance on windows. And if you want to try with emqx3.0, you have to upgrade your erlang to erlang/otp 21
