### ISSUE TITLE
Question: MQTT session at failover in clustering

### ISSUE THREAD

**Issue by aviscaerulea** [emqx/emqx#2032]
#### Environment

- OS: CentOS Linux release 7.5.1804 (Core)
- EMQ: emqttd 2.3.11

#### Description

I clustered EMQ 2.3.11 on two CentOS 7.
The MQTT client did not subscribe the QoS 2 message published during the failover.

I used the Mosquitto client and did the following work.
In actual development I use Java Eclipse Paho, but here I used Mosquitto easily.

1. Subscribe to EMQ-02 with Client ID=mosquitto, clean session=false, topic=sample, QoS=2.
```
$ mosquitto_sub -h EMQ-02 -q 2 -t sample -M 256 -c -i mosquitto
```
2. Publish with topic=sample, message="HELLO1", QoS=2 in EMQ-01. (Subscriber received)
```
$ mosquitto_pub -h EMQ-01 -t sample -q 2 -M 256 -m "HELLO1"
```
3. Kill the EMQ-02 process.
4. Publish with topic=sample, message="HELLO2", QoS=2 in EMQ-01. (again)
```
$ mosquitto_pub -h EMQ-01 -t sample -q 2 -M 256 -m "HELLO2"
```
5. Subscribe to EMQ-01 with Client ID=mosquitto, clean session=false, topic=sample, QoS=2.
```
$ mosquitto_sub -h EMQ-01 -q 2 -t sample -M 256 -c -i mosquitto
```
6. **"HELLO2" is not received.**

There are the following settings in `/etc/emqttd/emq.conf`.
```
mqtt.mqueue.max_length = 1000
mqtt.session.max_subscriptions = 0
mqtt.session.upgrade_qos = off
mqtt.session.max_inflight = 256
mqtt.session.retry_interval = 2 s
mqtt.session.max_awaiting_rel = 1000
mqtt.session.await_rel_timeout = 30 s
mqtt.session.enable_stats = on
mqtt.session.expiry_interval = 2h
mqtt.session.ignore_loop_deliver = false
```

Am I something wrong?
Or will the session be lost if EQM goes down?

**Comment by Gilbert-Wong** [comment]
@aviscaerulea So sorry for so late response, in emqx cluster mode, session would not be backup or migrated in different nodes. So if you stop one emqx node in cluster, the session on that node would be lost.

**Comment by aviscaerulea** [comment]
Thank you for your reply.
I seem to have misunderstood the following contents.
I understood it correctly.
http://emqtt.io/docs/v2/cluster.html#session-across-nodes
