### ISSUE TITLE
emqx_web_hook Advanced Config SUPPORT

### ISSUE THREAD

**Issue by lucafolin** [emqx/emqx#2042]
Hi, when I use and config "web_hook plugin" in Advanced Config there are two fields to fill in.

If I choose web hook only for message received I heve:

+-----------------------------------------------------------+
|  web.hook.rule.message.publish.$name  |
+-----------------------------------------------------------+

+-----------------------------------------------------------+
|                 web.hook.api.url                    |
+-----------------------------------------------------------+

The second field is ok for me ...it's the API URL to redirect the request to but what I have to insert into the first field "web.hook.rule.message.publish.$name" ??

L.

**Comment by linjunjj** [comment]
Hi @lucafolin lu
According to the EMQ documentation, you have to insert into the field, This will write the configuration in EMQ, Enable the corresponding method，

**Comment by Gilbert-Wong** [comment]
The first field you shoud insert is `hookpoint`, it is the event in emqx, you could refer README of this [project](https://github.com/emqx/emqx-web-hook), when the event `on_client_connected` and `on_client_disconnected` and so on triggered, the json would be delivered to your web server.
