### ISSUE TITLE
command 'emqx start' execute failure，no any message response

### ISSUE THREAD

**Issue by qianshui423** [emqx/emqx#2047]
#### Environment

- OS: macOS High Sierra 10.13.3
- Erlang/OTP: Erlang/OTP 21 [erts-10.0] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1]
- EMQ: emqx 3.0-rc.5

#### Description

command 'emqx start' execute failure，no any message response.

I can't find a solution. Help me, Please! Thx!

**Comment by qianshui423** [comment]
Here is my screenshot：

![image](https://user-images.githubusercontent.com/20347672/49873259-692d0200-fe56-11e8-8ea1-efbb919a628e.png)

**Comment by Gilbert-Wong** [comment]
Please try with `./emqx/bin/emqx_ctl status` to lookup the status of emqx.

**Comment by qianshui423** [comment]
> Please try with `./emqx/bin/emqx_ctl status` to lookup the status of emqx.

![image](https://user-images.githubusercontent.com/20347672/49910880-5995d380-febf-11e8-888b-52484d3a3b5f.png)

**Comment by Gilbert-Wong** [comment]
Then please try  with `./bin/emqx stop` to stop emqx, and if it still failed, you could kill -9 the emqx processes.

**Comment by qianshui423** [comment]
> Then please try with `./bin/emqx stop` to stop emqx, and if it still failed, you could kill -9 the emqx processes.

`./bin/emqx stop` result:
![image](https://user-images.githubusercontent.com/20347672/49914571-c6fc3100-fecc-11e8-9a9a-d0fce26b4b6b.png)

I can't find the emqx processes:
![image](https://user-images.githubusercontent.com/20347672/49914620-fe6add80-fecc-11e8-91a1-31cb3dabdb9e.png)

**Comment by qianshui423** [comment]
> Then please try with `./bin/emqx stop` to stop emqx, and if it still failed, you could kill -9 the emqx processes.

I found the cause of the problem.I changed the .erlang file in the Home directory.

Thank you for your attention to this issue.
