### ISSUE TITLE
number of messages held in memory

### ISSUE THREAD

**Issue by jvrahav** [emqx/emqx#2048]
#### Environment

- OS: linux
- Erlang/OTP: 
- EMQ: 2.1.2

#### Description

how can i get to know the number of messages held in memory that are yet to be consumed.

I generally rely on the broker metrics which shows the qos0 message in and out. this works when there is a sungle subscriber for a set of topics. However when there are mutiple subscribers for the same set of topics i see that after some time the count of msg out becomes more than the in.
in this scenario how can i determine the number of messages held in memory.

Thanks,
Rahav

**Comment by linjunjj** [comment]
Sorry for late response， Qos0 messages are not kept in memory

**Comment by Gilbert-Wong** [comment]
Hi, @jvrahav, we have configuration entry `zone.external.mqueue_store_qos0` to let you determine whether store qos0 messages in mqueue and `zone.external.max_mqueue_len` to determine the number of messages held in memory. Notice that these two configuration entries just works if you set clean_session is false in your mqtt connection.

**Comment by jvrahav** [comment]
If we take a case of a slow subscriber who is unable to consume messages in the rate at which they come into emqtt, what happens then. Will the qos 0 messages be held in memory until the subscriber reads it. In this case is it possible to determine the messages that are yet to be processed

**Comment by Gilbert-Wong** [comment]
No, qos 0 message could not be ensured to be delivered to your subscribers, in your scenario, I suppose that maybe qos 1 or qos 2 would be better.

Gilbert Wong
On Dec 18, 2018, 11:15 AM +0800, jvrahav <notifications@github.com>, wrote:

If we take a case of a slow subscriber who is unable to consume messages in the rate at which they come into emqtt, what happens then. Will the qos 0 messages be held in memory until the subscriber reads it. In this case is it possible to determine the messages that are yet to be processed
