### ISSUE TITLE
Publish Problem with cpu usage increase

### ISSUE THREAD

**Issue by yu-chun-young** [emqx/emqx#2049]
#### Environment

- OS: Windows Server 2012 R2 4Core 8GB(Web server), Windows Server 2012 R2 2core 2GB(Emq server)
- Erlang/OTP: 
- EMQ: emqttd-windows7-v2.3.11

The following same log continues to occur.
- From 00:08:00 to 00:19:00.
[error] <0.23484.5766>@emqttd_protocol:with_puback:350 Client(clientID@IP:PORT): PUBLISH 47434 error: dropped

Publishing web servers also increased CPU usage more than 80% 
and Emq server also increased CPU 60% more.
We are using Qos 2 messages.

What is the reason for it and how can I fix it?

**Comment by Gilbert-Wong** [comment]
Sorry for so late response, @yu-chun-young . Could you please tell me the hardware of your windows server machine ? For example, which cpu and how much memory. And how many qos2 messages you published each seconds? These information would help use dig into your problems.
