### ISSUE TITLE
Qos2 messages will be discarded when the consumer has a lower performance

### ISSUE THREAD

**Issue by 1181513953** [emqx/emqx#2050]
#### Environment

- OS: CentOS Linux release 7.4.1708 (Core) 
- Erlang/OTP: 
- EMQ: 3.0

#### Description

*A description of the issue*

**Comment by Gilbert-Wong** [comment]
What is the `consumer` do you mean? The client or the broker ? Could you please tell us more details?

**Comment by 1181513953** [comment]
A “consumer ”refers to a client which subscribes messages from broker.
A “producer”refers to a client which publishes messages to broker.
I meant that when a consumer is slower than producer ,some messages would be discarded even though the messages are qos2.
so，how can i do to avoid this problem?
e.g.
when “client  a“ publishes messages to the topic "/testTopic" at a speed of 100messges/s and "client  b" subscribe messages from the topic  "/testTopic" at a speed of 1messges/s，then 99 messges will be discarded。

**Comment by Gilbert-Wong** [comment]
Sorry for late reply, how do you configure the config entry `zone.external.max_mqueue_len`?
