### ISSUE TITLE
Erlang Auth plugin

### ISSUE THREAD

**Issue by ranvijayj** [emqx/emqx#2055]
#### Environment

- OS: Ubuntu 16.04 
- Erlang/OTP: 
- EMQ: 2.3.11

#### Description

*Its written that don't use LUA auth plugin as performance will be poor on a Erlang VM. I want  a conditional based multiple user auth. If Lua performance is poor at scale, can you guys help build an Erlang auth plugin. If I write the auth in Erlang, is there a way to plug it into EMQX? *

**Comment by Gilbert-Wong** [comment]
Hi, @ranvijayj , it's a good idea, I would engage into this erlang auth plugin if I have time.

**Comment by zmstone** [comment]
EMQ X now has quite a few auth supports.
including the mnesia based auth plugin.
