### ISSUE TITLE
Messages are being delivered multiple times

### ISSUE THREAD

**Issue by s4kibs4mi** [emqx/emqx#2063]
#### Environment

- OS: linux (Ubuntu)
- Erlang/OTP: 21
- EMQ: 3.0-rc.4

#### Description
I have published 50 messages asyn at a time. And found that for some messages `on_message_delivered` is being called multiple times and at consumer receiving the messages multiple times. as well some are being dropped.

I have tried same thing with messages 20 but worked fine. When I am increasing the number of messages it is making the issue. I am using a emqx plugin to publish messages which is using `emqx_mgmt.publish(msg)` to publish message.

`qos = 1`

Here is the log at consumer : https://gist.github.com/s4kibs4mi/8f1592554042e02b1e29e75d8f65b623

Note that I am using paho golang client to consume messages.

**Comment by s4kibs4mi** [comment]
```
19:38:56.197 [debug] [MQTT] RECV PUBREC(Q0, R0, D0, PacketId=31)
(emqx@10.12.0.81)1>
19:38:56.198 [debug] [MQTT] SEND PUBREL(Q1, R0, D0, PacketId=31)
(emqx@10.12.0.81)1>
19:38:56.198 [debug] [MQTT] RECV PUBCOMP(Q0, R0, D0, PacketId=1)
(emqx@10.12.0.81)1>
19:38:56.198 [debug] [MQTT] RECV PUBREC(Q0, R0, D0, PacketId=1)
(emqx@10.12.0.81)1>
19:38:56.198 [warn]  [Session] The PUBREC PacketId 1 is not found.
(emqx@10.12.0.81)1>
19:38:56.198 [debug] [MQTT] SEND PUBREL(Q1, R0, D0, PacketId=1)
(emqx@10.12.0.81)1>
19:38:56.198 [debug] [MQTT] RECV PUBREC(Q0, R0, D0, PacketId=2)

19:38:56.198 [warn]  [Session] Duplicated PUBREC PacketId 2

19:38:56.199 [debug] [MQTT] SEND PUBREL(Q1, R0, D0, PacketId=2)

19:38:56.199 [debug] [MQTT] RECV PUBREC(Q0, R0, D0, PacketId=3)

19:38:56.199 [warn]  [Session] Duplicated PUBREC PacketId 3

19:38:56.199 [debug] [MQTT] SEND PUBREL(Q1, R0, D0, PacketId=3)

19:38:56.199 [debug] [MQTT] RECV PUBREC(Q0, R0, D0, PacketId=4)

19:38:56.199 [warn]  [Session] Duplicated PUBREC PacketId 4
```

**Comment by s4kibs4mi** [comment]
@Gilbert-Wong any update ?

**Comment by Gilbert-Wong** [comment]
Sorry for late response. I'll check it.

**Comment by Gilbert-Wong** [comment]
Hi, @s4kibs4mi , Sorry for late response. You said that you published qos1 message, but the log you show me contains the packet required by qos2 message. I'm confused.

**Comment by s4kibs4mi** [comment]
@Gilbert-Wong sorry delayed reply. gist log is for qos 1 and 2nd comment log is for qos2. In both cases I am getting duplicate messages.

**Comment by Gilbert-Wong** [comment]
It is so awkward to reply to you so lately. @s4kibs4mi . It depends on mechanism of mqtt qos2 message deliver. If publisher did not receive `pubrec` packet, it would continue to publish `publish` packet. SO , the `on_message_delivered` hook would be triggered multiple times.
