### ISSUE TITLE
Emqtt subscribe hook cannot control error cases

### ISSUE THREAD

**Issue by berk-can** [emqx/emqx#2078]
#### Environment

- OS: MacOs 
- EMQ: 2.3.11

#### Description

In our handler hooks I can define on_client_connected in which first variable can be used to understand if acl succeeded or not, but in subscribe or publish error cases auto handled by emqtt which we do not have control on, is there a way to get status code even if it gets error like ACL deny

**Comment by Gilbert-Wong** [comment]
Are you user of emqx enterprise edition?

**Comment by berk-can** [comment]
No we are using free version

**Comment by Gilbert-Wong** [comment]
Really? emqx_bridge_kakka is not open source project and not integrated into free edition of emqx.

**Comment by berk-can** [comment]
I am sorry for misunderstanding it must be one of our class names, question is on client.subscribe hook we cannot listen for error cases

**Comment by Gilbert-Wong** [comment]
The feature you want is being implemented by my colleague, it should be implemeted in emqx3.0.0 release.

**Comment by berk-can** [comment]
that would be very helpful, thank you. I am closing issue
