### ISSUE TITLE
Bridge configuration

### ISSUE THREAD

**Issue by Odinysus** [emqx/emqx#2092]
#### Environment

- OS: centos 7.0
- Erlang/OTP: 
- EMQ: 3.0.5

#### Description

We bought a vps with mosquitto, how to bridge emqx to mosquitto?

**Comment by jinfahua** [comment]
what's your bridge direction? From mosquitto to EMQ, or EMQ to mosquitto ?

**Comment by Odinysus** [comment]
mosquitto to EMQ

**Comment by jinfahua** [comment]
So that should be check with mosquitto, nothing to configured in EMQ.

**Comment by jinfahua** [comment]
You can write an application to bridge message from mosquitto to EMQ by yourself. 

If you can change conf of mosquitto, you can refer to this [article](https://developer.emqx.io/docs/tutorial/zh/bridge/mosquitto_to_emqx.html).
