### ISSUE TITLE
can not load plugin when start emqx

### ISSUE THREAD

**Issue by kingsleycheung** [emqx/emqx#2104]
#### Environment

- OS: ubuntu 18.10
- Erlang/OTP: Erlang/OTP 21 [erts-10.0.5] [source] [64-bit] [smp:2:2] [ds:2:2:10] [async-threads:32] [hipe]
- EMQ: emqx-ubuntu18.04-v3.0-rc.5.zip

#### Description
我用deb的安装包.和上面的zip的都试过了,什么都不改,工作良好,,一旦开启一些插件就出现问题了,具体表现:
插件:emqx_auth_username
我修改插件配置文件,加入:
auth.user.1.username = admin
auth.user.1.password = public
然后:
 sudo ./emqx_ctl plugins load emqx_auth_username
这个时候,工作良好,一切正常,

当我关掉:sudo ./emqx stop
然后再打开,监听里面只有这两个端口,mqtt那些全都没起来:
![image](https://user-images.githubusercontent.com/12275305/50411835-4b8c6f00-083e-11e9-8e81-48fcdb60f994.png)
我使用 sudo ./bin/emqx console:
走到这里就卡住了:

kingsley@kingsley-server:~/runbin/emqx$ sudo ./bin/emqx console
Exec: /home/kingsley/runbin/emqx/erts-10.0.5/bin/erlexec -boot /home/kingsley/runbin/emqx/releases/3.0/emqx -mode embedded -boot_var ERTS_LIB_DIR /home/kingsley/runbin/emqx/erts-10.0.5/../lib -mnesia dir "/home/kingsley/runbin/emqx/data/mnesia/emqx@127.0.0.1" -config /home/kingsley/runbin/emqx/data/configs/app.2018.12.25.12.05.22.config -args_file /home/kingsley/runbin/emqx/data/configs/vm.2018.12.25.12.05.22.args -vm_args /home/kingsley/runbin/emqx/data/configs/vm.2018.12.25.12.05.22.args -- console
Root: /home/kingsley/runbin/emqx
/home/kingsley/runbin/emqx
Erlang/OTP 21 [erts-10.0.5] [source] [64-bit] [smp:2:2] [ds:2:2:10] [async-threads:32] [hipe]

Starting emqx on node emqx@127.0.0.1
Start http:management listener on 8080 successfully.
Start http:dashboard listener on 18083 successfully.
//---------------------
这时候,我发现,再这里面自动加了一行 我刚刚开启的插件,我如果删除掉这一行,就又正常了,
./emqx/data/loaded_plugins
但是.,很显然,这个emqx_auth_username 插件没有启动,显然我如果再次通过 sudo ./emqx_ctl plugins load emqx_auth_username 他又能正常工作,,
就是这样,
还有加你们qq群,3群,久久不能通过

**Comment by Gilbert-Wong** [comment]
Thanks for you feedback. We have fixed it in latest emqx3.0.0 release.
