### ISSUE TITLE
Installing From Source failed - Could not read from remote repository

### ISSUE THREAD

**Issue by jt-tech** [emqx/emqx#2105]
- OS:  Amazon Linux 2 AMI 
- Erlang/OTP:  Erlang/OTP 21 [erts-10.2] [source] [64-bit] [smp:1:1] [ds:1:1:10] [async-threads:1] [hipe]
- EMQ: emqx30

Installation from source fails.
Most likely there is no access to repositories.

# git clone -b X https://github.com/emqx/emqx-rel.git emqx-rel
Cloning into emqx-rel...
remote: Enumerating objects: 69, done.
remote: Counting objects: 100% (69/69), done.
remote: Compressing objects: 100% (43/43), done.
remote: Total 2589 (delta 37), reused 42 (delta 19), pack-reused 2520
Receiving objects: 100% (2589/2589), 3.44 MiB | 4.16 MiB/s, done.
Resolving deltas: 100% (1548/1548), done.

# cd emqx-rel && make
 DEP    cuttlefish
 DEP    goldrush
make[1]: Entering directory /home/ec2-user/software/emqx-rel/.erlang.mk/rebar
./bootstrap
Recompile: src/rebar
Recompile: src/rebar_abnfc_compiler
Recompile: src/rebar_app_utils
Recompile: src/rebar_appups
Recompile: src/rebar_asn1_compiler
Recompile: src/rebar_base_compiler
Recompile: src/rebar_cleaner
Recompile: src/rebar_config
Recompile: src/rebar_core
Recompile: src/rebar_cover_utils
Recompile: src/rebar_ct
Recompile: src/rebar_deps
Recompile: src/rebar_dia_compiler
Recompile: src/rebar_edoc
Recompile: src/rebar_erlc_compiler
Recompile: src/rebar_erlydtl_compiler
Recompile: src/rebar_escripter
Recompile: src/rebar_eunit
src/rebar_eunit.erl:279: Warning: crypto:rand_uniform/2 is deprecated and will be removed in a future release; use rand:uniform/1
src/rebar_eunit.erl:293: Warning: random:seed/3: the 'random' module is deprecated; use the 'rand' module instead
src/rebar_eunit.erl:295: Warning: random:uniform/0: the 'random' module is deprecated; use the 'rand' module instead
Recompile: src/rebar_file_utils
Recompile: src/rebar_getopt
Recompile: src/rebar_lfe_compiler
Recompile: src/rebar_log
Recompile: src/rebar_metacmds
Recompile: src/rebar_mustache
Recompile: src/rebar_neotoma_compiler
Recompile: src/rebar_otp_app
Recompile: src/rebar_otp_appup
Recompile: src/rebar_port_compiler
Recompile: src/rebar_proto_compiler
Recompile: src/rebar_proto_gpb_compiler
Recompile: src/rebar_protobuffs_compiler
Recompile: src/rebar_qc
Recompile: src/rebar_rel_utils
Recompile: src/rebar_reltool
Recompile: src/rebar_require_vsn
Recompile: src/rebar_shell
Recompile: src/rebar_subdirs
Recompile: src/rebar_templater
Recompile: src/rebar_upgrade
Recompile: src/rebar_utils
Recompile: src/rebar_xref
==> rebar (compile)
==> rebar (escriptize)
Congratulations! You now have a self-contained script called "rebar" in
your current working directory. Place this script anywhere in your path
and you can use rebar to build OTP-compliant apps.
make[1]: Leaving directory /home/ec2-user/software/emqx-rel/.erlang.mk/rebar
/home/ec2-user/software/emqx-rel
 DEP    emqx
ERROR: Repository not found.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
/bin/sh: line 0: cd: /home/ec2-user/software/emqx-rel/deps/emqx: No such file or directory
make: *** [/home/ec2-user/software/emqx-rel/deps/emqx] Error 1

**Comment by Gilbert-Wong** [comment]
It must be network problems, could you please make emqx_rel again?

**Comment by jt-tech** [comment]
> It must be network problems, could you please make emqx_rel again?

I tried to build the next day - everything compiled successfully.
I do not know why the whole previous day did not come out. The server was in Amazon EC2.

> And could you please tell me which branch of emqx-rel did you checkout ?

Last branch
