### ISSUE TITLE
reissue ssl

### ISSUE THREAD

**Issue by yu-chun-young** [emqx/emqx#2106]
#### Environment

- OS: Windows Server 2012 R2
- Erlang/OTP:  
- EMQ: v3.0.0

#### Description

My SSL will expire soon.
Should I stop and start working emq service? 
Is it possible to change the name of the new ssl to the name of the old ssl 
and paste it?

**Comment by Gilbert-Wong** [comment]
No, you have to restart emqx service. And did you successfully register emqx as windows service on windows server ? Could you please tell us how did you realize it ?

**Comment by yu-chun-young** [comment]
No, Emqx doesn't start on windows service. I just did emqx console / start / stop on cmd.

**Comment by Gilbert-Wong** [comment]
Ok, Anyway, Thanks for your feedback.

**Comment by Gilbert-Wong** [comment]
We plan to implement this feature in @yu-chun-young in 3.1-beta.1

**Comment by turtleDeng** [comment]
We will close this issue and you can reopen if there are any problems.
