### ISSUE TITLE
Very High CPU Usage

### ISSUE THREAD

**Issue by ranvijayj** [emqx/emqx#2122]
#### Environment

- OS: Ubuntu 16.04
- Erlang/OTP: 
- EMQ: 2.3.11

#### Description

*CPU continuously at above 90%. 30GB server + 4 cores AWS r4.xlarge
Load average is also at 4*
Please help.

![screen shot 2019 01 02 at 1 47 47 pm](https://user-images.githubusercontent.com/10911504/50640842-172a5880-0f8c-11e9-8b41-c59a44f9cf27.png)

**Comment by Gilbert-Wong** [comment]
How many connections did you established? Could you please describe your scenario more detailed?
