### ISSUE TITLE
REST API subscribe multiple topics Support

### ISSUE THREAD

**Issue by boboxiaodd** [emqx/emqx#2123]
#### Environment

- OS: centos7
- Erlang/OTP: 
- EMQ: 3.0.1

#### Description

*A description of the issue*
/api/v3/mqtt/subscribe
The client can subscribe multiple topics
but REST API not support

**Comment by Gilbert-Wong** [comment]
Of course, you can! http://emqtt.io/docs/v3/rest.html#subscriptions

**Comment by boboxiaodd** [comment]
@turtleDeng 
i have diffect qos of these topics ..

**Comment by Gilbert-Wong** [comment]
@boboxiaodd Sorry,  what is the `diffect qos` do you mean?

**Comment by boboxiaodd** [comment]
i mean is  topic1 's qos is 0 , and topic2 's qos is 2

**Comment by Gilbert-Wong** [comment]
Sorry, after discussion, we decide not to implement the feature you want.
