### ISSUE TITLE
Documentation: Updated Tuning Guide

### ISSUE THREAD

**Issue by claymcenter** [emqx/emqx#2131]
#### Environment

    OS: linux (Ubuntu)
    Erlang/OTP: 21
    EMQ: 3.0

#### Description

The number of connections on a 16 Core / 60 Gb RAM VM cannot go beyond 1.1 mn, is there an updated tuning guide available that can help us establish more connections using the same VM configuration. 

We have already followed the guide currently available on Github. 

Thanks.

**Comment by Gilbert-Wong** [comment]
Sorry, @claymcenter , I do not understand the `1.1 mn` you said. Could you please give me a more clear declare?
