### ISSUE TITLE
Custom ACL plugin in EMQ X v3.0 - wrong docs or Erlang records are missing from emqx.hrl

### ISSUE THREAD

**Issue by sashaafm** [emqx/emqx#2133]
#### Environment

- OS: Docker using Alpine 3.8 image
- Erlang/OTP: 21
- EMQ: 3.0

#### Description

Back in EMQ 2.11 we developed an ACL plugin in Elixir by following your docs. Now we're looking to migrate to v3.0. However, we haven't been able to properly migrate our ACL plugin because the `emqx.hrl` file seems to have changed and the docs do not describe how to properly develop an ACL plugin for version 3.0 of EMQ X.

For example, [here](https://developer.emqx.io/docs/emq/v3/en/plugins.html#register-auth-acl-modules) it is shown that we should include the `emqx.hrl` to use the `mqtt_client` record. Before we had the following implementation (now using the new header file) to extract the Erlang Record to be used in Elixir:

```
defmodule ACL.Models.Client do
  require Record

  import Record, only: [defrecord: 2, extract: 2]

  defrecord :mqtt_client, extract(:mqtt_client, from_lib: "emqx/include/emqx.hrl")
end
```

but this leads to the following error:

```
== Compilation error in file lib/models/client.ex ==
** (ArgumentError) no record mqtt_client found at /emqx/deps/emqx/include/emqx.hrl. Or the record does not exist or its entry is malformed or depends on other include files
    (elixir) lib/record/extractor.ex:56: Record.Extractor.extract_record/2
    lib/models/client.ex:6: (module)
    (stdlib) erl_eval.erl:680: :erl_eval.do_apply/6
make[1]: *** [Makefile:6: all] Error 1
```

by looking at the implementation of said [header file](https://github.com/emqx/emqx/blob/v3.0.0/include/emqx.hrl) we can see that no `mqtt_client` record exists. However, in the docs [here](https://developer.emqx.io/docs/emq/v3/en/plugins.html#register-auth-acl-modules) it is shown to use an `mqtt_client` record, same as before version 3.0.

Maybe I'm doing something wrong at the Erlang level (I'm more used to Elixir), but what I'm reporting seems an inconsistency between the docs and new EMQ X version. I'd like some help to continue migrating our ACL plugin to the new version.

**Comment by sashaafm** [comment]
I've now been able to migrate our ACL plugin by reading through the source code and altering the code accordingly, but I believe this proves that the docs are not up to date.

**Comment by Gilbert-Wong** [comment]
Sorry for our ill-defined documents. We would improve it as quick as possible.
