### ISSUE TITLE
Why the message lost?

### ISSUE THREAD

**Issue by gst6062825** [emqx/emqx#2136]
#### Environment

- OS: CentOS Linux release 7.2.1511 (Core)
- Erlang/OTP:
- EMQ: release,"emqx","3.0","10.0.5"

#### Description

import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.test.context.junit4.SpringRunner;
import java.io.IOException;

@RunWith(SpringRunner.class)
@SpringBootTest
public class MqttTest {
    @Autowired
    Mqtt mqtt;

    @Test
    public void sendToMqtt() throws InterruptedException, IOException {
        try {
            for (int j = 0; j < 100; j++) {
                Thread thread = new Thread(new HeartBeat(j));
                thread.run();
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        Thread.sleep(1000000000);
    }

    class HeartBeat implements Runnable {
        private Integer id;

        public HeartBeat(Integer id) {
            this.id = id;
        }

        @Override
        public void run() {
            try {
                for (int i = 0; i < 200; i++) {
                    String topic = "/charger/platform/fce89310273" + (int) (Math.random() * 20);

                    String content = "{\"key\":\"Heartbeat.req\",\"currentTime\":\"1546925314\",\"status\":\"onThread：" + id
                            + ",message：" + i + "\",\"hostid\":\"fce8928027b5\"}";

                    mqtt.sendToMqtt(topic, 0, content);
                    System.out.println(topic + ":" + content);
                }
            } catch (Exception e) {
                e.printStackTrace();
            }

        }
    }
}

I send 20,000 messages to emqx server,but the client which subscribe the topic "/charger/platform/+"  only received 4949 message.

 [root@****]# grep -o -a fce8931 device_service_mq.log|wc -l
4949

**Comment by jinfahua** [comment]
Could you please check the dashboard of emqx, and it will show the number of message that EMQ X received. 

Also, I would suggest to add a sleep time after ``mqtt.sendToMqtt(topic, 0, content);``.

100 threads without any sleep time between invocation of publish method will probably cause SDK failed to process.

**Comment by gst6062825** [comment]
> Could you please check the dashboard of emqx, and it will show the number of message that EMQ X received.
> 
> Also, I would suggest to add a sleep time after `mqtt.sendToMqtt(topic, 0, content);`.
> 
> 100 threads without any sleep time between invocation of publish method will probably cause SDK failed to process.

Thanks for the response,I just figure out is not the emqx server's problem.It's client's.
