### ISSUE TITLE
High CPU usage and takes a lot of memory

### ISSUE THREAD

**Issue by Bruce-Tian** [emqx/emqx#2140]
#### Environment

- OS: Linux 3.10.0-957.1.3.el7.x86_64
- Erlang/OTP: Erlang/OTP 20
- EMQ: 2.3.11

#### Description
The Nodes info
![image](https://user-images.githubusercontent.com/17424460/50903649-4e4fac80-1459-11e9-94e7-d7349daf7d54.png)

The clients and topics
![image](https://user-images.githubusercontent.com/17424460/50903575-1f393b00-1459-11e9-8dc4-b6ea5cdf8d50.png)

dirty_cpu_sch takes a large cpu usage,why?
![image](https://user-images.githubusercontent.com/17424460/50903395-a508b680-1458-11e9-9f6a-4372f2a64cba.png)

we turn on the info log in order to troubleshooting.
How can i reduce the cpu usage and free the memory?

**Comment by Gilbert-Wong** [comment]
Hi, @Bruce-Tian . Could you please give me more details? Such as your scenario, log file, crash.log and etc/emq.conf, which would help use dig into your problem.
