### ISSUE TITLE
emqx_ctl not working

### ISSUE THREAD

**Issue by biswaKL** [emqx/emqx#2146]
#### Environment

- OS: CentOS7
- Erlang/OTP: 
- EMQ: EMQX

#### Description

i have installed  EMQX in AWS (CentOS 7) using the rpm package,
everything is working but the emqx_ctl commands are not working,

```
[root@ip-172-31-28-38 bin]# emqx_ctl broker
Usage: emqx_ctl
--------------------------------------------------------------------------------
recon memory                                    # recon_alloc:memory/2
recon allocated                                 # recon_alloc:memory(allocated_types, current|max)
recon bin_leak                                  # recon:bin_leak(100)
recon node_stats                                # recon:node_stats(10, 1000)
recon remote_load Mod                           # recon:remote_load(Mod)
--------------------------------------------------------------------------------
retainer info                                   # Show the count of retained messages
retainer topics                                 # Show all topics of retained messages
retainer clean                                  # Clean all retained messages
--------------------------------------------------------------------------------
admins add <Username> <Password> <Tags>         # Add dashboard user
admins passwd <Username> <Password>             # Reset dashboard user password
admins del <Username>                           # Delete dashboard user
```

**Comment by linjunjj** [comment]
Hi @biswaKL  So sorry for so late response, What is your EMQX detailed version? Could you please provide more details information to help solve this?

**Comment by biswaKL** [comment]
its the latest one 3.0.0

**Comment by Gilbert-Wong** [comment]
Which emqx version did you use?

**Comment by biswaKL** [comment]
3.0.0

**Comment by biswaKL** [comment]
@linjunjj yes its running

**Comment by zhanghongtong** [comment]
Sorry, we are unable to reproduce this issue, please provide more details and logs

**Comment by mudphilo** [comment]
Make sure port 8080 is free. I had a similar proble only to realize a node application was running on port 8080 which is used by emqx_management. There emqx_management was failing to start

**Comment by NoelzeN** [comment]
Thanks for the hint with the management port. If 8080 is occupied (like in my case) one can simply change the port in plugins/emqx_management.conf

**Comment by fpirovani80** [comment]
Hi, I have the same problem.
Could you solve the problem?
Port 8080 is in use by emqx.
Attached link with screenshot.

[https://ibb.co/0D59YMQ](url)

Thank you

**Comment by NoelzeN** [comment]
@fpirovani80 I know it's a bit late, but just seen your post now. Looks like the path to the executable is incorrect, can you do a ls in the directory you're in?

**Comment by fpirovani80** [comment]
Thanks NoelzeN, I already solved it.

**Comment by arpitjayabt** [comment]
@NoelzeN  Can you please share how you solved this?
I am facing the same issue

Thank You!
