### ISSUE TITLE
How to list or enumerate allowed topics?

### ISSUE THREAD

**Issue by theronic** [emqx/emqx#2148]
#### Environment

- OS: Ubuntu 18.04.1 LTS
- Erlang/OTP: 20.0 (erts-9.2)
- EMQ: EMQ X Broker 3.0

#### Description

How do I get query the list of topics my user can subscribe to?

Or, at the very least, how do I query the rules that are defined for me, so that I can infer which topics I can subscribe to?

**Comment by Gilbert-Wong** [comment]
Hi, @theronic , as the emqx user, you have to design your topic filter by yourself based on your real requirement.

**Comment by turtleDeng** [comment]
@theronic 
The list of topics subscribed to by the client can be obtained through the API and emqx_ctl
API http://emqtt.io/docs/v3/rest.html#list-subscriptions-of-a-client-on-a-node
emqx_ctl
```
./bin/emqx_ctl
--------------------------------------------------------------------------------
subscriptions list                              # List all subscriptions
subscriptions show <ClientId>                   # Show subscriptions of a client
subscriptions add <ClientId> <Topic> <QoS>      # Add a static subscription manually
subscriptions del <ClientId> <Topic>            # Delete a static subscription manually
--------------------------------------------------------------------------------
```
