### ISSUE TITLE
Conn #PID<0.23231.0> is discarded by #PID<0.23240.0>

### ISSUE THREAD

**Issue by s4kibs4mi** [emqx/emqx#2149]
#### Environment

- OS: ubuntu
- Erlang/OTP: 21
- EMQ:  v3.0.0

#### Description

Client is being connected and getting disconnected, providing a warning,
```
10:51:17.909 [warn]  [Session] Conn #PID<0.23231.0> is discarded by #PID<0.23240.0>
```

**Comment by s4kibs4mi** [comment]
@Gilbert-Wong

**Comment by Gilbert-Wong** [comment]
So sorry for so late response, I'm very busy these days and I would dig into the issue you opened today or tomorrow.

**Comment by s4kibs4mi** [comment]
@Gilbert-Wong thanks. Please try to fix. emqx is getting too many issues which is making it unreliable to use.

**Comment by Gilbert-Wong** [comment]
Hi, @s4kibs4mi , which log level do you set in etc/emqx.conf ? Did you set it to error?

**Comment by s4kibs4mi** [comment]
@Gilbert-Wong didn't do any changes. It's the default.

**Comment by terry-xiaoyu** [comment]
@s4kibs4mi Don't start elixir logger in emqx, as it may delete/modify the erlang logger handlers. 
In your elixir plugin, use `:logger` instead.

For example:

```elixir
    def on_message_publish(message, _env) do
        #IO.inspect(["elixir on_message_publish", message])

        # add your elixir code here
        :logger.error("----- publish message!!!")

        {:ok, message}
    end
```

**Comment by s4kibs4mi** [comment]
@terry-xiaoyu ok I will try this, thank you. But it's terribly weird if this is the reason of client being disconnected !
