### ISSUE TITLE
EMQX3.0 crashes when EMQX_LOADED_PLUGINS is specified

### ISSUE THREAD

**Issue by PeiyiChi** [emqx/emqx#2151]
#### Environment

- OS: Docker 17.03.2
- Erlang/OTP: 
- EMQ: emqx:v3.0-rc.5

#### Description

EMQ sever starts crashing after I upgraded EMQ X Docker from emq24 to emqx30 in Kubernetes. I have narrowed it down to the use of env EMQX_LOADED_PLUGINS. Because as soon as EMQX_LOADED_PLUGINS is removed, the issue is gone.

apiVersion: apps/v1beta2
kind: StatefulSet
metadata:
  name: emqtt
spec:
  replicas: {{.Values.replicas}}
  selector:
    matchLabels:
      app: emqtt
  serviceName: emqtt
  template:
    metadata:
      labels: 
        app: emqtt
    spec:
      {{ if eq .Values.rbac.create true}}
      serviceAccountName: emqtt
      {{ end }}
      containers:
      - name: emqtt
        image: {{.Values.emqttimage}}
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 1883
          - containerPort: 8883
          - containerPort: 8080
          - containerPort: 18083
          - containerPort: 8083
          - containerPort: 8084
          - containerPort: 4369
          - containerPort: 4370
          - containerPort: 6369
          - containerPort: 6370
          - containerPort: 6371
          - containerPort: 6372
          - containerPort: 6373
          - containerPort: 6374
          - containerPort: 6375
          - containerPort: 6376
          - containerPort: 6377
          - containerPort: 6378
        readinessProbe:
          tcpSocket:
            port: 1883
          initialDelaySeconds: 5
          periodSeconds: 10
        env:
          - name: EMQX_NAME
            value: "emqtt"
          - name: EMQX_CLUSTER__DISCOVERY
            value: "k8s"
          - name: EMQX_CLUSTER__K8S__APISERVER
            value: "https://kubernetes.default:443"
          - name: EMQX_CLUSTER__K8S__NAMESPACE
            value: "default"    
          - name: EMQX_CLUSTER__K8S__SERVICE_NAME
            value: "emqtt"
          - name: EMQX_CLUSTER__K8S__ADDRESS_TYPE
            value: "ip"
          - name: EMQX_CLUSTER__K8S__APP_NAME
            value: "emqtt"
          - name: EMQX_NODE__COOKIE
            value: "secretcookieeeetfggggg"
          - name: EMQX_CLUSTER__NAME
            value: "emqcl"
          - name: EMQX_CLUSTER__AUTOHEAL
            value: "on"
          - name: EMQX_CLUSTER__AUTOCLEAN
            value: "5m"
          - name: EMQX_LOG__LEVEL
            value: "debug"
          - name: EMQX_ALLOW_ANONYMOUS
            value: "false"
          - name: **EMQX_LOADED_PLUGINS**
            value: "emqx_auth_http,emqx_auth_jwt,emqx_dashboard"
          - name: EMQX_AUTH__HTTP__AUTH_REQ
            value: "http://id-rest:8080/{}/login"
          - name: EMQX_AUTH__HTTP__AUTH_REQ__METHOD
            value: "get"
          - name: EMQX_AUTH__HTTP__AUTH_REQ__PARAMS
            value: "clientid=%c,username=%u,password=%P"
          - name: EMQX_AUTH__JWT__SECRET
            valueFrom:
              secretKeyRef:
                name: emq
                key: secret

Log:
node.process_limit=2097152
node.max_ets_tables=2097152
cluster.k8s.service_name=emqtt
cluster.k8s.service_name=emqtt
cluster.discovery=k8s
cluster.discovery=k8s
listener.ws.external.acceptors=16
node.cookie=secretcookieeeetfggggg
node.name=emqtt@172.17.0.11
cluster.k8s.app_name=emqtt
cluster.k8s.app_name=emqtt
cluster.k8s.apiserver=https://kubernetes.default:443
cluster.k8s.apiserver=https://kubernetes.default:443
cluster.k8s.namespace=default
cluster.k8s.namespace=default
cluster.autoclean=5m
cluster.autoclean=5m
auth.http.auth_req=http://id-rest:8080/{}/login
cluster.autoheal=on
cluster.autoheal=on
EMQX_LOADED_PLUGINS=emqx_auth_http,emqx_auth_jwt,emqx_dashboard
emqx 3.0 is started successfully!
2019-01-13 21:57:08.592 [info] Started Apps: [minirest,emqx_dashboard]
 2019-01-13 21:57:08.592 [info] Load plugin emqx_dashboard successfully
 Start mqtt:tcp listener on 127.0.0.1:11883 successfully.
 Start mqtt:tcp listener on 0.0.0.0:1883 successfully.
 Start mqtt:ws listener on 0.0.0.0:8083 successfully.
 Start mqtt:ssl listener on 0.0.0.0:8883 successfully.
 Start mqtt:wss listener on 0.0.0.0:8084 successfully.
 EMQ X Broker v3.0-rc.5 is running now!
 Eshell V10.0.6  (abort with ^G)
 (emqtt@172.17.0.11)1> ['2019-01-13T21:57:11Z']:waiting emqx
['2019-01-13T21:57:14Z']:waiting emqx
['2019-01-13T21:57:16Z']:waiting emqx
2019-01-13 21:57:18.214 [debug] 172.17.0.1:46456 [TCP] Terminated for {shutdown,closed}
 (emqtt@172.17.0.11)1> ['2019-01-13T21:57:18Z']:waiting emqx
['2019-01-13T21:57:21Z']:waiting emqx
['2019-01-13T21:57:23Z']:waiting emqx
['2019-01-13T21:57:23Z']:timeout error

*A description of the issue*

**Comment by zhanghongtong** [comment]
Sorry, this is our mistake. When you use`EMQX_LOADED_PLUGINS` to specify the plugin, you need to manually specify`emqx_management` and put it first, just like `docker run -it --rm -e EMQX_LOADED_PLUGINS="emqx_management,emqx_auth_http,emqx_auth_jwt,emqx_dashboard" emqx/emqx:v3.0.0`
