### ISSUE TITLE
How can I prevent multiple logins for same username and password

### ISSUE THREAD

**Issue by tangliming** [emqx/emqx#2155]
Hi, I am studying the document of emqx. In my scenario, one username and password can only login to server once, other device with the same username and password should be rejected by server.
but I don't find way to do such thing in document.

Does emqx has such mechanism?

**Comment by tangliming** [comment]
Just find the answer from #1272, this issue can be closed.

**Comment by roysG** [comment]
@tangliming, i am looking for the same answer, can you tell me how you did it?

**Comment by zmstone** [comment]
use username for client id.

**Comment by roysG** [comment]
@zmstone, 
You mean to change the settings in the emqx.conf for the parameter:
zone.external.use_username_as_clientid to equal true?

**Comment by zmstone** [comment]
> @zmstone, You mean to change the settings in the emqx.conf for the parameter: zone.external.use_username_as_clientid to equal true?

Hi @roysG 
What I meant was to change the clients' behaviour (by using assigned username as their client ID).
Setting `use_username_as_clientid` will change broker behaviour for the entire zone,
meaning you'll not be able to share credentials for some special clients (e.g. for monitoring or admin purposes)

Please note, by using username as clientid, the clients sharing the same username will start kicking each other as MQTT broker (cluster) only allows one client per ID.
If this is for access control purpose. I guess a better way is to use source-IP based ACL rule.
Or change to a new password so the unintended clients will not be able to connect.

**Comment by roysG** [comment]
Thanks!
