### ISSUE TITLE
EMQ client connectionLost always reConnected

### ISSUE THREAD

**Issue by xiaode123** [emqx/emqx#2157]
#### Environment

- OS: 
- Erlang/OTP: 
- EMQ: 

#### Description

*A description of the issue*
EMQ client setup 
After the EMQ client setting connection is lost, set the disconnection reconnection mechanism, but repeatedly start the disconnection and enter the infinite loop.

![image](https://user-images.githubusercontent.com/20831922/51238962-198ca980-19b3-11e9-8285-50922446f309.png)

![image](https://user-images.githubusercontent.com/20831922/51238718-8b182800-19b2-11e9-8a5f-e969504f2ae1.png)
![image](https://user-images.githubusercontent.com/20831922/51238763-ac791400-19b2-11e9-9ff2-6e77aae100fb.png)
![image](https://user-images.githubusercontent.com/20831922/51238773-b1d65e80-19b2-11e9-96e2-0f20bf1d03e0.png)
# @emqplus

**Comment by linjunjj** [comment]
@xiaode123  Maybe you need to open debug mode to view log information to find problem, set 'log.level = debug' in emqx.conf,

**Comment by Gilbert-Wong** [comment]
This is the bug of your client, please check your code and your mqtt sdk again.
