### ISSUE TITLE
2 nodes cluster behind HAproxy : retainer's problem

### ISSUE THREAD

**Issue by perroudchris** [emqx/emqx#2158]
#### Environment

- OS: Ubuntu 16.04
- Erlang/OTP: 
- EMQ: 3.0.0

Hello. I'm currently using a 2 nodes cluster behind a proxy and I found something strange in the behavior of the emqx 3.0 version. 

What I do : 

1)  A has : mosquitto_sub -h mybroker.local -p 38883  -t 'testTopic'  --cafile ./CA/ca.crt --cert ./client.crt  --key ./client.key  -q 2 -u "testUser" -P "pass" -c --id 1example1 -c

2) A disconnects

3 ) B sends 2 messages : 
mosquitto_pub -h mybroker.local -p 38883  -t "testTopic"  -u "testUser" -P "pass" --cafile ./CA/ca.crt --cert ./client.crt  --key ./client.key --id sessionB -q 1 -m "hi there"

mosquitto_pub -h mybroker.local -p 38883  -t "testTopic"  -u "testUser" -P "pass" --cafile ./CA/ca.crt --cert ./client.crt  --key ./client.key --id sessionB -q 1 -m "launch order 66"

4 ) A reconnects and becomes only . "hi there"..without the other

IMPORTANT REMARK : this happens when my 2 nodes are in cluster mode. If I stop one of the 2, the retainer works perfectly

eventually, there's my (common) retainer's config.
```
## Where to store the retained messages.
##
## Notice that all nodes in the same cluster have to be configured to
## use the same storage_type.
##
## Value: ram | disc | disc_only
##  - ram: memory only
##  - disc: both memory and disc
##  - disc_only: disc only
##
## Default: ram
retainer.storage_type = ram

## Maximum number of retained messages. 0 means no limit.
##
## Value: Number >= 0
retainer.max_retained_messages = 10000

## Maximum retained message size.
##
## Value: Bytes
retainer.max_payload_size = 1MB

## Expiry interval of the retained messages. Never expire if the value is 0.
##
## Value: Duration
##  - h: hour
##  - m: minute
##  - s: second
##
## Examples:
##  - 2h:  2 hours
##  - 30m: 30 minutes
##  - 20s: 20 seconds
##
## Defaut: 0
retainer.expiry_interval = 0
```

Any idea ? Thanks for now

**Comment by linjunjj** [comment]
Hi@perroudchris  sorry for the late reply. Do you mean to receive only retainer-type messages?

**Comment by turtleDeng** [comment]
We will close this issue and you can reopen if there are any problems.
