### ISSUE TITLE
After load web hook,http publish doesn't work

### ISSUE THREAD

**Issue by JackRanGitHub** [emqx/emqx#2163]
#### Environment

- OS: CentOS
- Erlang/OTP: Erlang/OTP 20 [erts-9.3]
- EMQ: 3.0.0

#### Description

After load web hook plugin,http publish doesn't work
`❯ curl -v --basic -u b546476d17fdc8:Mjg1NTE0Njc4Mzk1MzAyNzc5ODMxODA4NTUzNTI4ODUyNDI -H "Content-Type: application/json" -X POST  --data '{"topic":"groupChat/bc/4/164/178/1258","payload":"{\"msgid\":0,\"user_id\":16157702,\"name\":\"Jack\",\"thumb_pic\":\"http:\\/\\/thirdwx.qlogo.cn\\/mmopen\\/vi_32\\/eo4s3D2HffibX9lAicKxxQv1OHDrmdiciaMiaxKjqia6JJ1GQZGibK3eGfTWH3e20lhnBk9Ve00WhiaWC6eDGRu2stibtNQ\\/132\",\"msg\":{\"type\":10,\"username\":\"Jack\"},\"own\":true,\"role\":2,\"time\":1547777250,\"can_del\":true,\"is_new\":true}","qos":0,"retain":0,"client_id":"bc_Server_3_164_178_178_4_16157702"}' -k http://127.0.0.1:8080/api/v3/mqtt/publish`
`*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to 127.0.0.1 (127.0.0.1) port 8080 (#0)
* Server auth using Basic with user 'b546476d17fdc8'
> POST /api/v3/mqtt/publish HTTP/1.1
> Host: 127.0.0.1:8080
> Authorization: Basic YjU0NjQ3NmQxN2ZkYzg6TWpnMU5URTBOamM0TXprMU16QXlOemM1T0RNeE9EQTROVFV6TlRJNE9EVXlOREk=
> User-Agent: curl/7.54.0
> Accept: */*
> Content-Type: application/json
> Content-Length: 460
>
* upload completely sent off: 460 out of 460 bytes
< HTTP/1.1 500 Internal Server Error
< content-length: 14
< content-type: text/plain
< date: Fri, 18 Jan 2019 03:27:46 GMT
< server: Cowboy
<
* Connection #0 to host 127.0.0.1 left intact
Internal Error%`

We use EMQ:3.0.0-rc4 work well,but EMQ:3.0.0 does't work.Can you help me?Thank you very much!

**Comment by Gilbert-Wong** [comment]
Thanks for your feedback, it definitely is a bug. I will fix it soon.

**Comment by Gilbert-Wong** [comment]
It has been fixed and there would be no such problem in emqx 3.0.0 release.
