### ISSUE TITLE
Can`t get the right IP address by the API listenning to 8080

### ISSUE THREAD

**Issue by phper-chen** [emqx/emqx#2164]
#### Environment

- OS: ubuntu
- Erlang/OTP: 
- EMQ: 3.0 released version and any versions

#### Description

*A description of the issue*

No matter which version is used and what network the device is on, their ip address on emqtt is always 10.255.0.2 , it`s too Weird。
![image](https://user-images.githubusercontent.com/20152358/51376547-35d13900-1ace-11e9-91c3-d0d20f18d4a0.png)

**Comment by linjunjj** [comment]
Hi@phper-chen So sorry for late reponse, This is LAN ip.  Maybe you need to try again on other networks:blush:

**Comment by phper-chen** [comment]
> Hi@phper-chen So sorry for late reponse, This is LAN ip. Maybe you need to try again on other networks😊

Thanks for ur reply, How can I fix this pro? I`m not familiar with the Knowledge about routers😢

**Comment by linjunjj** [comment]
@phper-chen  It's no problem to get IP, Because the device you connect to is in a local area network. If you want to verify that getting IP is correct, You can try it on other networks. For example, Using external network.:wink:

**Comment by linjunjj** [comment]
@phper-chen  Sorry, I thought about it carefully. Do you use NAT(Network Address Translation) on the Internet:question:

**Comment by linjunjj** [comment]
@phper-chen What the server reads is that the public address of the router cannot read the address of the client LAN. I think both your server and client are in the LAN. So I got the IP address of the client router. That's why this IP is `10.255.0.2`.

**Comment by linjunjj** [comment]
I think you are a local area network with multi-level routing. You want the server to get the address and port of each client in the network, This one is not available.
