### ISSUE TITLE
START EMQX BROKER 

### ISSUE THREAD

**Issue by chrysa95** [emqx/emqx#2165]
#### Environment

- OS: 
- Erlang/OTP: 
- EMQ: 

#### Description

Hello,

I have install the emqx broker successfully , but  when i m trying to start the emqx broker , im getting the following error

```
hit2@hit2-Virtual-Machine:~/emqx-rel$ /bin/emqx start

bash: /bin/emqx: No such file or directory

```
 but the file exists

any possible answers?

**Comment by linjunjj** [comment]
@chrysa95  Try this command ，`./_rel/emqx/bin/emqx start`

**Comment by chrysa95** [comment]
@linjunjj  @Gilbert-Wong 
Hello ,

I have install the emqx broker like this unzip emqx-centos7-v3.0.zip.

Also, after that i have 3 files emqttd , emqx  and emqx-rel.
The file emqx doesn't include bin file
The file emqttd contains bin file which have emqttd,emqttd.cmd,emqttd_ctl,  ...etc
The file  emqx-rel contains bin file bin file which have emqx,emqx.cmd,emqx_ctl,  ...etc

Which of the above files should I run and how ?I'm confused

I try hit2@hit2-Virtual-Machine:~/emqx-rel$ ./bin/emqx start
      hit2@hit2-Virtual-Machine:~/emqx-rel$ ./emqx_rel/bin/emqx start
      hit2@hit2-Virtual-Machine:~/emqx-rel$ ./bin/emqx.cmd start
     hit2@hit2-Virtual-Machine:~/emqttd$ ./bin/emqttd start

**Comment by Gilbert-Wong** [comment]
If you use emqttd v2.3.11, they should be emqttd, emqttd_ctl, emqtt.cmd and so on.
