### ISSUE TITLE
"Network Error" when clicking start & config emqx_auth_mysql  

### ISSUE THREAD

**Issue by suijunqiang** [emqx/emqx#2166]
#### Environment

- OS: Ubuntu 18
- Erlang/OTP: R21/10.2
- EMQ: 3.1

#### Description
Enable the module of mysql
"Network Error" when clicking start & config emqx_auth_mysql

**Comment by linjunjj** [comment]
Hi @suijunqiang  Could you please give me some logs when this issue happend, and config information

**Comment by suijunqiang** [comment]
@linjunjj 
full error log as below after clicking config
2019-01-20 01:11:48.130 [error] GET /api/v3/nodes/emqx@127.0.0.1/plugin_configs/emqx_auth_mysql error: {badmatch,
                                                                        {error,
                                                                         {'EXIT',
                                                                          {badarg,
                                                                           [{ets,
                                                                             lookup,
                                                                             [emqx_config,
                                                                              emqx_auth_mysql],
                                                                             []},
                                                                            {emqx_mgmt_cli_cfg,
                                                                             read_config,
                                                                             1,
                                                                             [{file,
                                                                               "src/emqx_mgmt_cli_cfg.erl"},
                                                                              {line,
                                                                               70}]},
                                                                            {emqx_mgmt_config,
                                                                             read_,
                                                                             1,
                                                                             [{file,
                                                                               "src/emqx_mgmt_config.erl"},
                                                                              {line,
                                                                               89}]},
                                                                            {emqx_mgmt_config,
                                                                             read,
                                                                             1,
                                                                             [{file,
                                                                               "src/emqx_mgmt_config.erl"},
                                                                              {line,
                                                                               38}]},
                                                                            {rpc,
                                                                             local_call,
                                                                             3,
                                                                             [{file,
                                                                               "rpc.erl"},
                                                                              {line,
                                                                               321}]},
                                                                            {emqx_mgmt,
                                                                             rpc_call,
                                                                             3,
                                                                             [{file,
                                                                               "src/emqx_mgmt.erl"},
                                                                              {line,
                                                                               477}]},
                                                                            {emqx_mgmt_api_configs,
                                                                             get_plugin_configs,
                                                                             2,
                                                                             [{file,
                                                                               "src/emqx_mgmt_api_configs.erl"},
                                                                              {line,
                                                                               85}]},
                                                                            {minirest_handler,
                                                                             dispatch,
                                                                             3,
                                                                             [{file,
                                                                               "src/minirest_handler.erl"},
                                                                              {line,
                                                                               55}]}]}}}}, stacktrace:
[{emqx_mgmt_api_configs,get_plugin_configs,2,
                        [{file,"src/emqx_mgmt_api_configs.erl"},{line,85}]},
 {minirest_handler,dispatch,3,[{file,"src/minirest_handler.erl"},{line,55}]},
 {minirest,handle_request,2,[{file,"src/minirest.erl"},{line,66}]},
 {minirest,init,2,[{file,"src/minirest.erl"},{line,51}]},
 {cowboy_handler,execute,2,[{file,"src/cowboy_handler.erl"},{line,37}]},
 {cowboy_stream_h,execute,3,[{file,"src/cowboy_stream_h.erl"},{line,274}]},
 {cowboy_stream_h,request_process,3,
                  [{file,"src/cowboy_stream_h.erl"},{line,252}]},
 {proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,249}]}]

**Comment by Gilbert-Wong** [comment]
Did you start mysql and config your emqx_auth_mysql.conf correctly? Which mysql version do you use?

**Comment by suijunqiang** [comment]
@Gilbert-Wong 
It works well after setting emqx_auth_mysql.conf & restart the process of emqx.

Thanks anyway.
