### ISSUE TITLE
Docker EMQX no deps folder for plugin

### ISSUE THREAD

**Issue by lucafolin** [emqx/emqx#2169]
I have installed emqx docker but there is no deps plugin folder in the docker container.
If I need to modify and run emqx_plugin_template how can i do ?

**Comment by zhanghongtong** [comment]
You can read the [EMQ Loaded Plugins Configuration](https://github.com/emqx/emqx-docker/blob/emqx30/README.md#emq-loaded-plugins-configuration) and [EMQ X Plugins Configuration](https://github.com/emqx/emqx-docker/blob/emqx30/README.md#emq-x-plugins-configuration) chapters in the [emqx-docker documentation](https://github.com/emqx/emqx-docker/blob/emqx30/README.md) to solve your problem.

**Comment by Gilbert-Wong** [comment]
You can not use docker, you have to git clone emqx_rel repo and modify the code according to your requirements.
