### ISSUE TITLE
can't publish with http api

### ISSUE THREAD

**Issue by liping17** [emqx/emqx#2177]
#### Environment

- OS: WIN7
- Erlang/OTP: 
- EMQ: 2.3.11

#### Description
Neither of the following commands can be sent

curl -v --basic -u admin:public -d "qos=1&retain=0&topic=9999/b/c&message=hello from http..." -k http://localhost:8080/mqtt/publish

curl -v --basic -u admin:public -H "Content-Type: application/json" -d '{"topic":"9999/a/b","payload":"hello","qos":0,"retain":0,"client_id":"mqttjs_722b4d845f"}' -k http://localhost:8080/api/v2/mqtt/publish

And the console has the following errors：

16:29:19.781 [error] Error in process <0.455.0> on node 'emq@127.0.0.1' with exit value:
{function_clause,[{proplists,get_value,[<<"topic">>,<<"{topic:9999/a/b,payload:hello,qos:0,retain:0,client_id:mqttjs_722b4d845f}">>,undefined],[{file,"proplists.erl"},{line,226}]},{emqttd_http,'-check_params/2-fun-0-',2,[{file,"d:/emqtt/v2.3/2.3.11/emq-relx/deps/emqttd/src/emqttd_http.erl"},{line,189}]},{lists,any,2,[{file,"lists.erl"},{line,1225}]},{emqttd_http,check_params,2,[{file,"d:/emqtt/v2.3/2.3.11/emq-relx/deps/emqttd/src/emqttd_http.erl"},{line,189}]},{emqttd_http,'-dispatcher/1-fun-6-',3,[{file,"d:/emqtt/v2.3/2.3.11/emq-relx/deps/emqttd/src/emqttd_http.erl"},{line,95}]},{mochiweb_http,headers,5,[{file,"d:/emqtt/v2.3/2.3.11/emq-relx/deps/mochiweb/src/mochiweb_http.erl"},{line,93}]}]}
16:29:19.782 [error] Supervisor 'esockd_connection_sup - <0.441.0>' had child connection started with mochiweb_http:start_link({emqttd_http,handle_request,[{state,#Fun<emqttd_http.2.12940028>}]}) at <0.455.0> exit with reason no function clause matching proplists:get_value(<<"topic">>, <<"{topic:9999/a/b,payload:hello,qos:0,retain:0,client_id:mqttjs_722b4d845f}">>, undefined) line 226 in context connection_crashed
16:41:00.206 [error] Body:<<"qos=1&retain=0&topic=9999/b/c&message=hello">>

*A description of the issue*

**Comment by Gilbert-Wong** [comment]
Please try with the latest emqx edition. This problem should be resolved.
