### ISSUE TITLE
Starts & crashes in CentOS 

### ISSUE THREAD

**Issue by wajidp** [emqx/emqx#2178]
#### Environment

- OS:  CentOs 7
- Erlang/OTP: 21 
- EMQ: 3.0

#### Description
bin/emqx console 
starts and crashes what will be the reason

{"Kernel pid terminated",application_controller,"{application_start_failure,kernel,{{shutdown,{failed_to_start_child,kernel_safe_sup,{on_load_function_failed,crypto}}},{kernel,start,[normal,[]]}}}"}
Kernel pid terminated (application_controller) ({application_start_failure,kernel,{{shutdown,{failed_to_start_child,kernel_safe_sup,{on_load_function_failed,crypto}}},{kernel,start,[normal,[]]}}})

**Comment by Gilbert-Wong** [comment]
Hi, @wajidp , How do you install emqx on your centos7 ? Did you install emqx via rpm ?

**Comment by wajidp** [comment]
not via rpm

**Comment by Gilbert-Wong** [comment]
I have reproduced this problem, sorry for our careless work. We would fix it as soon as possible.

**Comment by wajidp** [comment]
can we have an ETA ?

**Comment by Gilbert-Wong** [comment]
Sorry, It is not emqx bug, you have to upgrade you open ssl library on your cent os.

**Comment by wajidp** [comment]
Update openssl now running OpenSSL 1.0.2q  20 Nov 2018 
But still same error

**Comment by zhanghongtong** [comment]
Sorry, I can't reproduce this question, please provide more information.

**Comment by Gilbert-Wong** [comment]
After I upgrade all packages on cent os 7 via `yum update`, there is no such problem again.
![image](https://user-images.githubusercontent.com/20479699/51817716-d44b6e80-2306-11e9-90ed-d6cbe1d0a021.png)

**Comment by wajidp** [comment]
Worked thanks

**Comment by rangeshgupta-altair** [comment]
**I also faced the same issue:**

{"Kernel pid terminated",application_controller,"{application_start_failure,kernel,{{shutdown,{failed_to_start_child,kernel_safe_sup,{on_load_function_failed,crypto}}},{kernel,start,[normal,[]]}}}"}
Kernel pid terminated (application_controller) ({application_start_failure,kernel,{{shutdown,{failed_to_start_child,kernel_safe_sup,{on_load_function_failed,crypto}}},{kernel,start,[normal,[]]}}})

But after upgrading the openssl library, service started. We do not need to upgrade all the packages.

**Versio before upgrade:** OpenSSL 1.0.1e-fips 11 Feb 2013

**Version after upgrade:** OpenSSL 1.0.2k-fips  26 Jan 2017

**Comment by JulyXing** [comment]
I faced same error,but I built openssl source package stilled not work。
openssl version info
```
OpenSSL 1.1.1a  20 Nov 2018
built on: Fri Aug 23 06:37:19 2019 UTC
platform: linux-x86_64
options:  bn(64,64) rc4(16x,int) des(int) idea(int) blowfish(ptr) 
compiler: gcc -fPIC -pthread -m64 -Wa,--noexecstack -Wall -O3 -DOPENSSL_USE_NODELETE -DL_ENDIAN -DOPENSSL_PIC -DOPENSSL_CPUID_OBJ -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DKECCAK1600_ASM -DRC4_ASM -DMD5_ASM -DAES_ASM -DVPAES_ASM -DBSAES_ASM -DGHASH_ASM -DECP_NISTZ256_ASM -DX25519_ASM -DPADLOCK_ASM -DPOLY1305_ASM -DNDEBUG
OPENSSLDIR: "/usr/local/ssl"
ENGINESDIR: "/usr/local/openssl/lib/engines-1.1"
Seeding source: os-specific

```

[https://docs.emqx.io/tutorial/v3/cn/faq/faq.html](https://docs.emqx.io/tutorial/v3/cn/faq/faq.html)

**Comment by wuweijie555** [comment]
worked
