### ISSUE TITLE
New logs stop being print out on console in Kubernetes 

### ISSUE THREAD

**Issue by PeiyiChi** [emqx/emqx#2185]
#### Environment

- OS: Kubenetes1.9
- Erlang/OTP: 
- EMQ: 3.0

#### Description

*A description of the issue*

This is an old issue I raised in ekka section (https://github.com/emqx/ekka/issues/36). Since I recently upgraded EMQ to 3.0 and found out the issue still exists, I feel like it would be better to mention it here as well.

My EMQ server is hosted in Kubenetes. It is all good when I use it during the day. But after leaving it over the weekend, the new logs stop being print out on console. Although I can still see the new logs from erlang.log file.

**Comment by zhanghongtong** [comment]
I noticed that the version of emqx in this [issue](https://github.com/emqx/ekka/issues/36) is 2.4. Is there still an issue in 3.0?

**Comment by PeiyiChi** [comment]
Yes, it is still an issue in 3.0

**Comment by zhanghongtong** [comment]
As you can see, this is a problem with `start.sh` in our docker images, we will try to fix this in the next version.

**Comment by zhanghongtong** [comment]
@PeiyiChi We have solved this issue, in `emqx/emqx:v3.1.1`, you can try it
