### ISSUE TITLE
How to use prometheus for monitoring EMQ

### ISSUE THREAD

**Issue by Frank111** [emqx/emqx#2186]
#### Environment

- OS: Centos7
- Erlang/OTP: 21
- EMQ: 3.0

#### Description
I want to monitor all MQTT topics of  EMQ by prometheus，I have looked following

https://github.com/inovex/mqtt_blackbox_exporter
https://github.com/emqx/emqx-statsd

**Comment by Gilbert-Wong** [comment]
Sorry, we have no plan to expose all mqtt topics for prometheus now.
