### ISSUE TITLE
LDAP authentication fails  auth_modules_not_found

### ISSUE THREAD

**Issue by wajidp** [emqx/emqx#2188]
#### Environment

- OS: CentOS
- Erlang/OTP: 21
- EMQ: 3.1

#### Description

LDAP authentication fails with username 'dcadministrator' login failed for auth_modules_not_found
anonymous authentication is disabled

> '[root@AKKA-01 ~]#  /usr/bin/emqx_ctl plugins list'

> Plugin(emqx_auth_clientid, version=3.0, description=EMQ X Authentication with ClientId/Password, active=false)
> Plugin(emqx_auth_http, version=v3.0.1, description=EMQ X Authentication/ACL with HTTP API, active=false)
> Plugin(emqx_auth_jwt, version=3.0, description=EMQ X Authentication with JWT, active=false)
> Plugin(emqx_auth_ldap, version=3.0, description=EMQ X Authentication/ACL with LDAP, active=true)
> Plugin(emqx_auth_mongo, version=3.0, description=EMQ X Authentication/ACL with MongoDB, active=false)
> Plugin(emqx_auth_mysql, version=3.0, description=EMQ X Authentication/ACL with MySQL, active=false)
> Plugin(emqx_auth_pgsql, version=3.0, description=EMQ X Authentication/ACL with PostgreSQL, active=false)
> Plugin(emqx_auth_redis, version=3.0, description=EMQ X Authentication/ACL with Redis, active=false)
> Plugin(emqx_auth_username, version=3.0, description=EMQ X Authentication with Username and Password, active=false)
> Plugin(emqx_coap, version=3.0, description=EMQ X CoAP Gateway, active=false)
> Plugin(emqx_dashboard, version=3.0, description=EMQ X Web Dashboard, active=true)
> Plugin(emqx_delayed_publish, version=3.0, description=EMQ X Delayed Publish, active=false)
> Plugin(emqx_lua_hook, version=3.0, description=EMQ X Lua Hooks, active=false)
> Plugin(emqx_lwm2m, version=3.0, description=EMQ X LwM2M Gateway, active=false)
> Plugin(emqx_management, version=3.0, description=EMQ X Management API and CLI, active=true)
> Plugin(emqx_plugin_template, version=3.0, description=EMQ X Plugin Template, active=false)
> Plugin(emqx_recon, version=3.0, description=EMQ X Recon Plugin, active=true)
> Plugin(emqx_reloader, version=3.0, description=EMQ X Reloader Plugin, active=false)
> Plugin(emqx_retainer, version=3.0, description=EMQ X Retainer, active=true)
> Plugin(emqx_sn, version=3.0, description=EMQ X MQTT SN Plugin, active=false)
> Plugin(emqx_statsd, version=3.0, description=Statsd for EMQ X, active=false)
> Plugin(emqx_stomp, version=3.0, description=EMQ X Stomp Protocol Plugin, active=false)
> Plugin(emqx_web_hook, version=3.0, description=EMQ X Webhook Plugin, active=false)

**Comment by Gilbert-Wong** [comment]
Could you please tell me how did you configure the ldap server on your local machine?

**Comment by wajidp** [comment]
through the plugin conf emqx_auth_ldap.conf

**Comment by Gilbert-Wong** [comment]
`emqx_auth_ldap.conf` itself doesn't configure ldap server, you have to configure your ldap server according to the readme.

**Comment by wajidp** [comment]
I have configured as per the readme & this is a working ldap settings 

> ##--------------------------------------------------------------------
> ## LDAP Auth Plugin
> ##--------------------------------------------------------------------
> 
> ## LDAP server list, seperated by ','.
> ##
> ## Value: String
> auth.ldap.servers = 192.168.0.100
> 
> ## LDAP server port.
> ##
> ## Value: Port
> auth.ldap.port = 389
> 
> ## LDAP pool size
> ##
> ## Value: String
> auth.ldap.pool = 8
> 
> ## LDAP Bind DN.
> ##
> ## Value: DN
> auth.ldap.bind_dn = cn=dcadministrator,cn=users,dc=dt,dc=local
> 
> ## LDAP Bind Password.
> ##
> ## Value: String
> auth.ldap.bind_password = XXXXXXX
> 
> ## LDAP query timeout.
> ##
> ## Value: Number
> auth.ldap.timeout = 30s
> 
> ## Device DN.
> ##
> ## Variables:
> ##
> ## Value: DN
> auth.ldap.device_dn = cn=users,dc=dt,dc=local
> 
> ## Specified ObjectClass
> ##
> ## Variables:
> ##
> ## Value: string
> auth.ldap.match_objectclass = users
> 
> ## attributetype for username
> ##
> ## Variables:
> ##
> ## Value: string
> auth.ldap.username.attributetype = sAMAccountName
> 
> ## attributetype for password
> ##
> ## Variables:
> ##
> ## Value: string
> auth.ldap.password.attributetype = userPassword
> 
> ## Whether to enable SSL.
> ##
> ## Value: true | false
> auth.ldap.ssl = false
> 
> ##TODO: SSL Support
> 
> ## auth.ldap.ssl.certfile = etc/certs/cert.pem
> 
> ## auth.ldap.ssl.keyfile = etc/certs/key.pem
> 
> ## auth.ldap.ssl.cacertfile = etc/certs/cacert.pem
> 
> ## auth.ldap.ssl.verify = verify_peer
> 
> ## auth.ldap.ssl.fail_if_no_peer_cert = true

**Comment by wajidp** [comment]
Find below 

`2019-01-28 14:38:16.476 [error] ad305941-c7c5-4d43-9b4f-1b0d73aa96e01548664054947@192.168.250.45:52392 Username 'dcadministrator' login failed for auth_modules_not_found`

**Comment by wajidp** [comment]
we have a working active directory in the specified host & the same parameters is used for gitlab ldap authentication which works fine

**Comment by Gilbert-Wong** [comment]
@wajidp Could you please set log level to `debug` and run again? The info you provide isn't not enough for me to dig into your problem.

**Comment by wajidp** [comment]
Find below
```
2019-01-28 14:51:54.748 [debug] ad305941-c7c5-4d43-9b4f-1b0d73aa96e01548672150374@192.168.250.45:53294 SEND CONNACK(Q0, R0, D0, AckFlags=0, ReasonCode=5)
2019-01-28 14:51:54.748 [debug] ad305941-c7c5-4d43-9b4f-1b0d73aa96e01548672150374@192.168.250.45:53294 Terminated for {shutdown,unauthorized_client}
2019-01-28 14:51:55.773 [debug] 192.168.250.45:53295 RECV <<16,101,0,4,77,81,84,84,4,194,0,10,0,49,97,100,51,48,53,57,52,49,45,99,
       55,99,53,45,52,100,52,51,45,57,98,52,102,45,49,98,48,100,55,51,97,97,57,
       54,101,48,49,53,52,56,54,55,50,49,53,48,51,55,52,0,15,100,99,97,100,109,
       105,110,105,115,116,114,97,116,111,114,0,21,100,99,97,100,109,105,110,
       105,115,116,114,97,116,111,114,35,64,50,48,50,48>>
2019-01-28 14:51:55.774 [debug] 192.168.250.45:53295 RECV CONNECT(Q0, R0, D0, ClientId=ad305941-c7c5-4d43-9b4f-1b0d73aa96e01548672150374, ProtoName=MQTT, ProtoVsn=4, CleanStart=true, KeepAlive=10, Username=dcadministrator, Password=******)
2019-01-28 14:51:55.775 [error] ad305941-c7c5-4d43-9b4f-1b0d73aa96e01548672150374@192.168.250.45:53295 Username 'dcadministrator' login failed for auth_modules_not_found
```

**Comment by Gilbert-Wong** [comment]
It means there is no such object `dcadministrator` in your ldap server.

**Comment by wajidp** [comment]
> we have a working active directory in the specified host & the same parameters are used for gitlab ldap authentication which works fine
> 
> ```
>  gitlab_rails['ldap_servers'] = YAML.load <<-'EOS'
>    main: # 'main' is the GitLab 'provider ID' of this LDAP server
>      label: 'DT'
>      host: '192.168.0.100'
>      port: 389
>      uid: 'sAMAccountName'
>      bind_dn: 'cn=dcadministrator,cn=users,dc=dt,dc=local'
>      password: 'XXXXXXXX'
>      encryption: 'plain' # "start_tls" or "simple_tls" or "plain"
>      verify_certificates: false
>      active_directory: true
>      allow_username_or_email_login: false
>      lowercase_usernames: false
>      block_auto_created_users: false
>      base: 'cn=users,dc=dt,dc=local'
>      user_filter: ''
>  EOS
> ```

The above works for me with gitlab dcadministrator

**Comment by wajidp** [comment]
ldapsearch result
```
# DCAdministrator, Users, dt.local
dn: CN=DCAdministrator,CN=Users,DC=dt,DC=local
objectClass: top
objectClass: person
objectClass: organizationalPerson
objectClass: user
cn: DCAdministrator
description: LDAP Authentication for Gitlab (Bigdata)
givenName: DCAdministrator
distinguishedName: CN=DCAdministrator,CN=Users,DC=dt,DC=local
instanceType: 4
whenCreated: 20190108065024.0Z
whenChanged: 20190118152741.0Z
displayName: DCAdministrator
uSNCreated: 104833633
uSNChanged: 107251647
name: DCAdministrator
objectGUID:: xsunRPR2jEmsLQMdY6ChBA==
userAccountControl: 66048
badPwdCount: 0
codePage: 0
countryCode: 0
badPasswordTime: 131931489761821599
lastLogoff: 0
lastLogon: 131931490315948032
pwdLastSet: 131914038244103197
primaryGroupID: 513
objectSid:: AQUAAAAAAAUVAAAA4m6hXfnjE8soEq+p1g8AAA==
adminCount: 1
accountExpires: 9223372036854775807
logonCount: 6
sAMAccountName: dcadministrator
sAMAccountType: 805306368
userPrincipalName: dcadministrator@dt.local
objectCategory: CN=Person,CN=Schema,CN=Configuration,DC=dt,DC=local
dSCorePropagationData: 20190108071432.0Z
dSCorePropagationData: 20190108065024.0Z
dSCorePropagationData: 16010101000000.0Z
lastLogonTimestamp: 131922988616502079

# search result
search: 2
result: 0 Success

# numResponses: 2
# numEntries: 1
```

**Comment by wajidp** [comment]
kindly note ldap is **microsoft active directory**

**Comment by Gilbert-Wong** [comment]
In ldap, we use uid to represent username rather objectclass, maybe you need to read ldap docs to know which is a better schema design in ldap.

**Comment by Gilbert-Wong** [comment]
Ok, I never tried with microsoft ldap, sorry I can't help you.
