### ISSUE TITLE
formatter_crashed: emqx_logger_formatter

### ISSUE THREAD

**Issue by kaido42** [emqx/emqx#2195]
#### Environment

- OS: 
ubuntu

- EMQ: 
3.0.1

#### Description

most probably caused by a binary message(s) posted.

2019-01-29 11:26:51.335 [debug] formatter_crashed: emqx_logger_formatter
    config: #{template =>
                  [time," [",level,"] ",
                   {client_id,
                       [{peername,
                            [client_id,"@",peername," "],
                            [client_id," "]}],
                       [{peername,[peername," "],[]}]},
                   msg,"\n"]}
    log_event: #{level => warning,
                 meta =>
                     #{gl => <0.4197.0>,pid => <0.4245.0>,
                       report_cb => #Fun<emqx_sys_mon.9.117256372>,
                       sysmon => true,time => 1548761211331101},
                 msg => {report,#{}}}
    reason: {error,function_clause,
                [{emqx_logger_formatter,format_msg,
                     [{"FORMAT ERROR: ~0tp - ~0tp",["[SYSMON] ~s~n~p",[]]},
                      unlimited,[]],
                     [{file,"src/emqx_logger_formatter.erl"},{line,143}]},
                 {emqx_logger_formatter,format,2,
                     [{file,"src/emqx_logger_formatter.erl"},{line,77}]}]}

2019-01-29 11:26:51.340 [debug] formatter_crashed: emqx_logger_formatter
    config: #{template =>
                  [time," [",level,"] ",
                   {client_id,
                       [{peername,
                            [client_id,"@",peername," "],
                            [client_id," "]}],
                       [{peername,[peername," "],[]}]},
                   msg,"\n"]}
    log_event: #{level => warning,
                 meta =>
                     #{gl => <0.4197.0>,pid => <0.4245.0>,
                       report_cb => #Fun<emqx_sys_mon.9.117256372>,
                       sysmon => true,time => 1548761211331101},
                 msg => {report,#{}}}
    reason: {error,function_clause,
                [{emqx_logger_formatter,format_msg,
                     [{"FORMAT ERROR: ~0tp - ~0tp",["[SYSMON] ~s~n~p",[]]},
                      unlimited,[]],
                     [{file,"src/emqx_logger_formatter.erl"},{line,143}]},
                 {emqx_logger_formatter,format,2,
                     [{file,"src/emqx_logger_formatter.erl"},{line,77}]}]}

**Comment by Gilbert-Wong** [comment]
Hi, @kaido42 .It has been fixed.
