### ISSUE TITLE
Cannot create user from API

### ISSUE THREAD

**Issue by Caldarelli** [emqx/emqx#2200]
#### Environment

- OS: CentOS 7
- Erlang/OTP:  Erlang/OTP 21 [erts-10.2.2]
- EMQ: v3.0.0

#### Expected behaviour

An user gets created

#### Description

When trying to create an user from API, it returns me a 404 response

here is my API call :
$ curl -v --user appname:appsecret -H "Content-Type: application/json" -d "{username: \"TestMember\", password:\"TestTest\"}" SERVER:8080/api/v3/users/

**Comment by Gilbert-Wong** [comment]
Sorry, this REST API has been deprecated in emqx 3.0.1 release now. We'll discuss about it whether to restore this api.

**Comment by Gilbert-Wong** [comment]
It has been implemented in emqx 3.1 beta.3
