### ISSUE TITLE
compile error for rel3.0

### ISSUE THREAD

**Issue by nixlong** [emqx/emqx#2202]
#### Environment

- OS:  ubuntu 18.04
- Erlang/OTP:   Erlang/OTP 21 [erts-10.2.3] 
- EMQ:  emq3.0 rel

#### Description

*A description of the issue*

when i download the emqx 3.0 rel code and compile, meet error as following:

```
........

./rebar get-deps
==> getopt (get-deps)
==> neotoma (get-deps)
==> cuttlefish (get-deps)
./rebar compile
==> getopt (compile)
==> neotoma (compile)
==> cuttlefish (compile)
./rebar skip_deps=true escriptize
==> cuttlefish (escriptize)
make[2]: 离开目录“~/workspace/emqx3.0/emqx-rel/deps/cuttlefish”
Error: No Makefile to build dependency ~/workspace/emqx3.0/emqx-rel/deps/jsx.
../../erlang.mk:297: recipe for target 'deps' failed
make[1]: *** [deps] Error 2
make[1]: 离开目录“~/workspace/emqx3.0/emqx-rel/deps/emqx”
erlang.mk:295: recipe for target 'deps' failed
make: *** [deps] Error 2
```

how should i solve this problem? please, thx

**Comment by Gilbert-Wong** [comment]
Please try with `git reset --hard` and `make distclean` , then make project again.

**Comment by nixlong** [comment]
> Please try with `git reset --hard` and `make distclean` , then make project again.

thx, it works... : )
