### ISSUE TITLE
User password is not updating

### ISSUE THREAD

**Issue by aaamitsingh** [emqx/emqx#2203]
#### Environment

- OS: 18.04.1 LTS
- Erlang/OTP: 
- EMQ: emqx 3.0

#### Description
I facing the following issue:
1. When I am changing the password of any user or adding any user from the dashboard UI its not reflecting when I'm using the command "./bin/emqx_ctl users list" from the cli. Similarly if I'm creating any user from cli its not reflecting on Dashboard.

2. If I create a user from the dashboard and update his/her password from the dashbard its works for dashboad login but not for mqtt connection authentication.  The mqtt connection get authenticated from the old password only.

3. When I create a user from cli and update the password by command I get the responce 'ok' but the mqtt connection authentication work with old password.

After changing the password I have done "./bin/emqx stop" and "./bin/emqx start" but still it work with old password instead of new password.

**Comment by aaamitsingh** [comment]
@Gilbert-Wong : Any update?

**Comment by linjunjj** [comment]
@aaamitsingh   Do you mean to use username and password authentication in plugin 'emqx_auth_username' ？

**Comment by linjunjj** [comment]
@aaamitsingh   Hi, Creating any user from cli its not reflecting on Dashboard,  From my test, When I  create a new user from cli , mqtt connection authentication work with new username and password.

**Comment by aaamitsingh** [comment]
> @aaamitsingh Do you mean to use username and password authentication in plugin 'emqx_auth_username' ？
@linjunjj : Yes

**Comment by aaamitsingh** [comment]
@linjunjj Have you tested it at your side?

**Comment by linjunjj** [comment]
@aaamitsingh  Yeah, Start the corresponding plugin, Create new username and password by cli. I use MQTTBOX tool, Both new password  and old password are available, If you don't want to use the old password, you can delete it by cli

**Comment by linjunjj** [comment]
@aaamitsingh  when you just want to use a new user and password, you could delete old user, then create new username and password, In the new PR, add a command to update the password

**Comment by aaamitsingh** [comment]
@linjunjj The problem is neither the password is updating nor the user is deleting from the CLI although when I'm giving the command for the update and delete I'm getting a response "OK".

**Comment by HJianBo** [comment]
Hi, @aaamitsingh Sorry too late reply there.  The mentioned Users Concept is not the same one

- The 'user' created by Dashboard or `emqx_ctl admins add` command is used for *Dashboard Login * NOT for *MQTT Connection*

- The 'username' configured `etc/plugins/emqx_auth_username.conf` or `emqx_ctl users add` command is only used for *MQTT Connection Authentication*

Besides, We have removed the default 'username' feature after EMQ X v3.1.rc.2

**Comment by HJianBo** [comment]
Hi, @aaamitsingh Is the problem solved?

I close it first. Plz reopen it if has any question there
