### ISSUE TITLE
memory footprint of emq

### ISSUE THREAD

**Issue by jvrahav** [emqx/emqx#2204]
#### Environment

- OS: 
- Erlang/OTP: 
- EMQ: 2.3

#### Description

Can someone share information on how is memory allocated for different components of EMQ
1. topic
2. subscription
3. connection

Which of the above are more memory intensive, im trying to find answer to a question like 
IS 
EMQ with 1000 clients each with 10 QOS 0 subscriptions more memory intensive than
EMQ with 10000 clients each with 1 QOS 0 subscription.

**Comment by zhengyupan** [comment]
Hi @jvrahav ,
Each connection in emqx takes about 4k MEM. 
The topics are always combined with subscription and route trie. they depend on your application scenario.
For the two cases you listed, you can do a quick test to get the answer.

In a normal use case, a client represents an end device, the number of clients is kind of fixed and depends on your application. If you have 1000 devices, it is usually not necessary to create 10 clients on each device an make there 10000 mqtt clients, or you could lost control on your client software.
