### ISSUE TITLE
No SUBACK on topic subscription. 

### ISSUE THREAD

**Issue by drPytho** [emqx/emqx#2206]
#### Environment

- OS: Docker image emqx/emqx:latest running on linux
- Erlang/OTP: 
EMQ X Broker v3.0.1 is running now!
Eshell V10.2.1  (abort with ^G)

#### Description
When subscribing to a topic, no suback is sent back.

**Comment by drPytho** [comment]
https://screenshots.firefox.com/nj3vOMhRisJHKXoT/localhost

**Comment by drPytho** [comment]
[out.pcap.log](https://github.com/emqx/emqx/files/2838115/out.pcap.log)

A wiresharc pcap file with .log to upload

**Comment by drPytho** [comment]
```
(51e68d20911d@172.17.0.2)1> 2019-02-06 21:10:25.979 [debug] 172.17.0.1:55966 RECV CONNECT(Q0, R0, D0, ClientId=866039040298482, ProtoName=MQIsdp, ProtoVsn=3, CleanStart=true, KeepAlive=0, Username=guest, Password=******)
(51e68d20911d@172.17.0.2)1> 2019-02-06 21:10:25.980 [debug] 866039040298482@172.17.0.1:55966 SEND CONNACK(Q0, R0, D0, AckFlags=0, ReasonCode=0)
(51e68d20911d@172.17.0.2)1> 2019-02-06 21:10:26.819 [debug] 866039040298482@172.17.0.1:55966 RECV <<130,6,0,0,0,1,99,1>>
(51e68d20911d@172.17.0.2)1> 2019-02-06 21:10:26.820 [debug] 866039040298482@172.17.0.1:55966 RECV SUBSCRIBE(Q1, R0, D0, PacketId=0, TopicFilters=[{<<"c">>,
                           #{nl => 0,qos => 1,rap => 0,rc => 0,rh => 0}}])
(51e68d20911d@172.17.0.2)1> 2019-02-06 21:10:26.824 [debug] 866039040298482@172.17.0.1:55966 Terminated for {shutdown,packet_id_invalid}
(51e68d20911d@172.17.0.2)1> 2019-02-06 21:10:26.824 [info] 866039040298482@172.17.0.1:55966 Shutdown for packet_id_invalid
```

**Comment by drPytho** [comment]
Is there some way to get around the packetId being zero?

**Comment by Gilbert-Wong** [comment]
Hi, @drPytho, which mqtt client do yhhou use ?

**Comment by drPytho** [comment]
Embedded C version of https://github.com/eclipse/paho.mqtt.embedded-c

**Comment by Gilbert-Wong** [comment]
It seems that it is the mqtt client you written by yourself. I suppose there is something wrong in your code. You could try with [mosquitto](https://mosquitto.org/) to test emqx.

**Comment by drPytho** [comment]
Yes, it was a poor implementation of the mqtt client. It worked with rabbitmq-mqtt so bad assumption on my side lead me to think something was off here. No issues here.
