### ISSUE TITLE
Question: Delayed Publish 

### ISSUE THREAD

**Issue by devmark88** [emqx/emqx#2207]
I'm looking for a solution to publish messages to a special topic after x seconds in EMQX. I've found EMQ X enterprise edition's feature table which shows `Delay and schedule message delivery` is a feature of enterprise edition not `Broker Edition`. On the other side [there is an official plugin](https://github.com/emqx/emqx-delayed-publish) in GitHub which do exactly what I want, Delayed Publish.

So my question is how much the plugin reliable? If you had planned to add this feature into the enterprise edition, why they should create an open source GitHub project to do exactly the same!

**Comment by Gilbert-Wong** [comment]
This feature both exists in open source edition and enterprise edition.

**Comment by nosovk** [comment]
Is it possible that this feature was removed from open source edition in latest releases?

**Comment by zmstone** [comment]
> Is it possible that this feature was removed from open source edition in latest releases?

This feature is still there in 5.8.
It was listed in the "deleted features from dashboard" announcement, but there were no UI for this feature anyway, so nothing is impcted.
