### ISSUE TITLE
on_client_subscribe username parameter is always undefined

### ISSUE THREAD

**Issue by jdavidagudelo** [emqx/emqx#2208]
#### Environment

- OS: Ubuntu 16.04
- Erlang/OTP: 21
- EMQ: 3.0

#### Description

I am trying to create the following LUA script:

```
function on_client_subscribe(clientid, username, topic)
    return topic .. username
end

function register_hook()
    return "on_client_subscribe"
end

```

The problem is that when I look the topic inside the web dashboard the **username is undefined**, despite the fact that I am sending the username and password inside the MQTT client:

```
mosquitto_sub -t my_topic -u my_username
```
inside EMQ 3.0 the resulting topic is:

```
my_topicundefined
```
But I am expecting to get:

```
my_topicmy_username
```

**Comment by Gilbert-Wong** [comment]
I have seen the pull request you opened under `emqx-lua-hook` project. There is still some small mistakes in your code. I would help you improve it. Anyway,thanks for your contribution

**Comment by Gilbert-Wong** [comment]
This bug has been fixed.
