### ISSUE TITLE
Message delivery fails for 30MB file

### ISSUE THREAD

**Issue by archerian** [emqx/emqx#2209]
#### Environment

- OS: Windows 10
- Erlang/OTP: 21
- EMQ: 3.0.1

#### Description

Message not delivered with retain flag = true for file of 30MB size. MQTT spec allows for files around 200MB.

**Comment by Gilbert-Wong** [comment]
Hi, @archerian , how do you config the item `mqtt.max_packet_size` ?

**Comment by archerian** [comment]
I have increased mqtt.max_packet_size = 50MB, also set retainer.max_payload_size = 50MB

**Comment by zmstone** [comment]
fixed in 4.3
