### ISSUE TITLE
could you please give me emqttd haproxy failover installation steps

### ISSUE THREAD

**Issue by sbcsuman** [emqx/emqx#2211]
#### Environment

- OS: 
- Erlang/OTP: 
- EMQ: 

#### Description

*A description of the issue*

**Comment by sbcsuman** [comment]
Hi Team,

I am created emqttd LB setup with roundrobin . but i want to failover setup

**Comment by Gilbert-Wong** [comment]
May this doc could help you. https://developer.emqx.io/docs/emq/v3/en/deploy.html#load-balancer-lb
