### ISSUE TITLE
SSl /tls aunthetication

### ISSUE THREAD

**Issue by rajkiranjeet** [emqx/emqx#2213]
#### Environment

- OS: windows
- Erlang/OTP: 
- EMQ: 2.3.11

#### Description
we are looking for ssl / tls client side authentication without client side pem file so client just use login password
*A description of the issue*
please explain setting how we can do that .'
thanks

**Comment by phanimahesh** [comment]
What do you mean by client side SSL/TLS authentication without a certificate? Authenticating TLS itself bidirectionally requires certificates.

If you simply want authenticated connections over TLS, just connect to the broker over port 8883 after setting up an ssl certificate on emqx.

**Comment by rajkiranjeet** [comment]
what protocol we have to select over ssl so we dont have to use certificate on client side ,please explain little more as we already setup ssl on emq dahsbpard.

**Comment by phanimahesh** [comment]
The protocol is up to you. You can use MQTT over TLS on 8883 or Websockets over TLS on 8084. The recommended method is to use a separate ssl terminator - like haproxy.

I believe you are mixing up unrelated things. Authenticating SSL clients with a certificate is a feature of SSL, and can be implemented for any protocol. There is nothing specific to emqx or even MQTT about it.

Using a protocol over SSL/TLS does not require a client certificate. Just like you don't need a certificate f your own to access https://github.com. The authentication, if any is then handled by the higher level protocol, like HTTP.

In case of MQTT over TLS, or MQTT over WebSockets over TLS, the authentication is handled by the MQTT layer using the MQTT username, password and clientid fields.

**Comment by rajkiranjeet** [comment]
Re you able to do some paid work to setup things for us if you have good experience,we already finding some one on upwork but no one we find ,please help us.
thanks

**Comment by zhengyupan** [comment]
Hi @rajkiranjeet please mail me at zhengyu.pan@emqx.io if you are interested in paid work.
