### ISSUE TITLE
Multiple listeners on same IP but different port

### ISSUE THREAD

**Issue by archerian** [emqx/emqx#2215]
#### Environment

- OS: Win 10
- Erlang/OTP: 21 
- EMQ: 3.0.1

#### Description

How do I modify the config file to allow EMQX to listen on multiple ports? Can I do in emqx.conf

listener.tcp.external = 0.0.0.0:1883
listener.tcp.external = 0.0.0.0:80
listener.tcp.external = 0.0.0.0:85

**Comment by linjunjj** [comment]
Hi @archerian  EMQ does not support multiple ports listening at present. Maybe you need to use an agent.

**Comment by Gilbert-Wong** [comment]
Sorry @archerian , this feature is supported by emqx. There is notion called `zone` in emqx3.0. 
![image](https://user-images.githubusercontent.com/20479699/52682735-66947900-2f7b-11e9-8e4e-38b94d4113ff.png)

The keyword `external` means that it is a listener of `external zone`. You could listen on multiple ports via creating multiple zones.

**Comment by archerian** [comment]
Thanks, looking at the file, seems like to create a new zone I have to add several zone. parameters, this seems like too much config for adding another listening port, especially when all the other zone parameters are the same. Maybe an enhancement to add a single line would be nice. But your suggestion works, for my current use I re purposed the internal zone to map to all IPs yet another port

**Comment by Gilbert-Wong** [comment]
Thanks for your advice, we'll take it into consideration.
