### ISSUE TITLE
Retainer message payload size

### ISSUE THREAD

**Issue by archerian** [emqx/emqx#2218]
#### Environment

- OS: Wins 10
- Erlang/OTP: 21 
- EMQ: 3.0.1

#### Description

Is this setting from emqx_retainer.conf still used? If I were to send a message of 30MB size with retain = true, I will have to modify this setting too right?

##
## Value: Bytes
retainer.max_payload_size = 1MB

**Comment by tigercl** [comment]
You are right. Sorry for later response, hope you've tried it yourself.

**Comment by turtleDeng** [comment]
We will close this issue and you can reopen if there are any problems.
