### ISSUE TITLE
EMQX RHEL and SUSE support?

### ISSUE THREAD

**Issue by rangeshgupta-altair** [emqx/emqx#2219]
#### Environment

- OS:  SUSUE/RHEL
- Erlang/OTP: 
- EMQ: 

#### Description

Does EMQX support RHEL and SUSE?  I do not the download package for this platform.

**Comment by zhanghongtong** [comment]
We don't have a RHEL and SUSE package right now. For RHEL, you can try the centos rpm. For SUSE, we welcome the contribution code.

**Comment by rangeshgupta-altair** [comment]
@zhanghongtong: Thanks for the reply! 

Can we compile it from source code for SUSE? Did anyone try it before and is there any bottleneck or challenge, which you guys are aware of it?

**Comment by zhanghongtong** [comment]
As far as I know, no one has done this yet. You can get the code from [here](https://github.com/emqx/emqx-rel) and try to compile it. The compiler environment recommends using Erlang/OTP 21.2.

**Comment by zhanghongtong** [comment]
@rangeshgupta-altair  I am going to close this issue. Please feel free to re-open if you still have the same trouble.
