### ISSUE TITLE
Shared Subscription Strategy round_robbin throws an error

### ISSUE THREAD

**Issue by encojosh** [emqx/emqx#2220]
#### Environment

- OS: Ubuntu 14.04
- Erlang/OTP: 21
- EMQ: 3.0.1

#### Description

Publishing a message to a shared topic produces the following error when using using the following config setting and MQTT.js clients.

broker.shared_subscription_strategy = round_robbin

Setting the strategy to random, hash, and sticky all seem to work as expected.

2019-02-13 16:05:43.566 [debug] 192.168.1.38:61169 RECV CONNECT(Q0, R0, D0, ClientId=MQTT_FX_Client, ProtoName=MQTT, ProtoVsn=4, CleanStart=true, KeepAlive=60, Username=hydroClient, Password=******)
2019-02-13 16:05:43.569 [debug] MQTT_FX_Client@192.168.1.38:61169 SEND CONNACK(Q0, R0, D0, AckFlags=0, ReasonCode=0)
2019-02-13 16:05:43.569 [debug] MQTT_FX_Client@192.168.1.38:61169 Keepalive at the interval of 45
2019-02-13 16:05:45.949 [debug] MQTT_FX_Client@192.168.1.38:61169 RECV <<52,15,0,11,104,101,108,108,111,47,119,111,114,108,100,0,1>>
2019-02-13 16:05:45.950 [debug] MQTT_FX_Client@192.168.1.38:61169 RECV PUBLISH(Q2, R0, D0, Topic=hello/world, PacketId=1, Payload=<<>>)
2019-02-13 16:05:45.952 [info] MQTT_FX_Client@192.168.1.38:61169 PUBLISH to hello/world: <<>>
2019-02-13 16:05:45.953 [debug] MQTT_FX_Client@192.168.1.38:61169 Terminated for {function_clause,
                   [{emqx_shared_sub,do_pick_subscriber,
                        [<<"hs">>,<<"hello/world">>,round_robbin,
                         <<"MQTT_FX_Client">>,2],
                        [{file,"src/emqx_shared_sub.erl"},{line,242}]},
                    {emqx_shared_sub,pick_subscriber,5,
                        [{file,"src/emqx_shared_sub.erl"},{line,239}]},
                    {emqx_shared_sub,do_pick,5,
                        [{file,"src/emqx_shared_sub.erl"},{line,234}]},
                    {emqx_shared_sub,dispatch,4,
                        [{file,"src/emqx_shared_sub.erl"},{line,91}]},
                    {emqx_broker,publish,1,
                        [{file,"src/emqx_broker.erl"},{line,171}]},
                    {emqx_protocol,do_publish,2,
                        [{file,"src/emqx_protocol.erl"},{line,556}]},
                    {emqx_connection,handle_packet,2,
                        [{file,"src/emqx_connection.erl"},{line,352}]},
                    {emqx_connection,process_incoming,2,
                        [{file,"src/emqx_connection.erl"},{line,332}]}]}
2019-02-13 16:05:45.959 [info] MQTT_FX_Client@192.168.1.38:61169 Shutdown for {function_clause,
                 [{emqx_shared_sub,do_pick_subscriber,
                      [<<"hs">>,<<"hello/world">>,round_robbin,
                       <<"MQTT_FX_Client">>,2],
                      [{file,"src/emqx_shared_sub.erl"},{line,242}]},
                  {emqx_shared_sub,pick_subscriber,5,
                      [{file,"src/emqx_shared_sub.erl"},{line,239}]},
                  {emqx_shared_sub,do_pick,5,
                      [{file,"src/emqx_shared_sub.erl"},{line,234}]},
                  {emqx_shared_sub,dispatch,4,
                      [{file,"src/emqx_shared_sub.erl"},{line,91}]},
                  {emqx_broker,publish,1,
                      [{file,"src/emqx_broker.erl"},{line,171}]},
                  {emqx_protocol,do_publish,2,
                      [{file,"src/emqx_protocol.erl"},{line,556}]},
                  {emqx_connection,handle_packet,2,
                      [{file,"src/emqx_connection.erl"},{line,352}]},
                  {emqx_connection,process_incoming,2,
                      [{file,"src/emqx_connection.erl"},{line,332}]}]}
2019-02-13 16:05:45.966 [error] MQTT_FX_Client@192.168.1.38:61169 ** Generic server <0.1620.0> terminating
** Last message in was {tcp,#Port<0.29>,
                            <<52,15,0,11,104,101,108,108,111,47,119,111,114,
                              108,100,0,1>>}
** When Server state == {state,esockd_transport,#Port<0.29>,
                            {{192,168,1,38},61169},
                            undefined,running,100,
                            {pstate,external,
                                #Fun<emqx_connection.0.118827427>,
                                {{192,168,1,38},61169},
                                nossl,4,<<"MQTT">>,<<"MQTT_FX_Client">>,false,
                                <0.1620.0>,undefined,undefined,
                                <<"hydroClient">>,<0.1622.0>,true,#{},1048576,
                                60,undefined,false,false,true,true,ignore,
                                #{msg => 0,pkt => 1},
                                #{msg => 0,pkt => 1},
                                true,
                                {1550,95543,567201},
                                false,
                                #{from_client => 0,to_client => 0}},
                            {none,#{max_packet_size => 1048576,version => 4}},
                            {emqx_gc,
                                #{cnt => {1000,999},oct => {1048576,1048522}}},
                            {keepalive,#Fun<emqx_connection.7.118827427>,54,
                                45,
                                {keepalive,check},
                                #Ref<0.2972970205.181927937.148007>,0},
                            true,#Ref<0.2972970205.181927937.148004>,
                            undefined,undefined,undefined,15000}
** Reason for termination ==
** {function_clause,[{emqx_shared_sub,do_pick_subscriber,
                                      [<<"hs">>,<<"hello/world">>,
                                       round_robbin,<<"MQTT_FX_Client">>,2],
                                      [{file,"src/emqx_shared_sub.erl"},
                                       {line,242}]},
                     {emqx_shared_sub,pick_subscriber,5,
                                      [{file,"src/emqx_shared_sub.erl"},
                                       {line,239}]},
                     {emqx_shared_sub,do_pick,5,
                                      [{file,"src/emqx_shared_sub.erl"},
                                       {line,234}]},
                     {emqx_shared_sub,dispatch,4,
                                      [{file,"src/emqx_shared_sub.erl"},
                                       {line,91}]},
                     {emqx_broker,publish,1,
                                  [{file,"src/emqx_broker.erl"},{line,171}]},
                     {emqx_protocol,do_publish,2,
                                    [{file,"src/emqx_protocol.erl"},
                                     {line,556}]},
                     {emqx_connection,handle_packet,2,
                                      [{file,"src/emqx_connection.erl"},
                                       {line,352}]},
                     {emqx_connection,process_incoming,2,
                                      [{file,"src/emqx_connection.erl"},
                                       {line,332}]}]}
2019-02-13 16:05:46.003 [error] MQTT_FX_Client ** Generic server <0.1622.0> terminating
** Last message in was {'EXIT',<0.1620.0>,
                           {function_clause,
                               [{emqx_shared_sub,do_pick_subscriber,
                                    [<<"hs">>,<<"hello/world">>,round_robbin,
                                     <<"MQTT_FX_Client">>,2],
                                    [{file,"src/emqx_shared_sub.erl"},
                                     {line,242}]},
                                {emqx_shared_sub,pick_subscriber,5,
                                    [{file,"src/emqx_shared_sub.erl"},
                                     {line,239}]},
                                {emqx_shared_sub,do_pick,5,
                                    [{file,"src/emqx_shared_sub.erl"},
                                     {line,234}]},
                                {emqx_shared_sub,dispatch,4,
                                    [{file,"src/emqx_shared_sub.erl"},
                                     {line,91}]},
                                {emqx_broker,publish,1,
                                    [{file,"src/emqx_broker.erl"},{line,171}]},
                                {emqx_protocol,do_publish,2,
                                    [{file,"src/emqx_protocol.erl"},
                                     {line,556}]},
                                {emqx_connection,handle_packet,2,
                                    [{file,"src/emqx_connection.erl"},
                                     {line,352}]},
                                {emqx_connection,process_incoming,2,
                                    [{file,"src/emqx_connection.erl"},
                                     {line,332}]}]}}
** When Server state == {state,15000,true,local,<<"MQTT_FX_Client">>,
                            <<"hydroClient">>,undefined,undefined,1,0,#{},
                            false,
                            {emqx_inflight,32,{0,nil}},
                            20000,undefined,
                            {mqueue,true,1000,0,0,none,infinity,
                                {queue,[],[],0}},
                            #{1 => {1550,95545,952740}},
                            100,300000,#Ref<0.2972970205.181927938.145366>,0,
                            undefined,true,
                            #Ref<0.2972970205.181927938.145367>,
                            {emqx_gc,
                                #{cnt => {1000,1000},
                                  oct => {1048576,1048576}}},
                            {1550,95543,568793},
                            undefined,undefined}
** Reason for termination ==
** {function_clause,[{emqx_shared_sub,do_pick_subscriber,
                                      [<<"hs">>,<<"hello/world">>,
                                       round_robbin,<<"MQTT_FX_Client">>,2],
                                      [{file,"src/emqx_shared_sub.erl"},
                                       {line,242}]},
                     {emqx_shared_sub,pick_subscriber,5,
                                      [{file,"src/emqx_shared_sub.erl"},
                                       {line,239}]},
                     {emqx_shared_sub,do_pick,5,
                                      [{file,"src/emqx_shared_sub.erl"},
                                       {line,234}]},
                     {emqx_shared_sub,dispatch,4,
                                      [{file,"src/emqx_shared_sub.erl"},
                                       {line,91}]},
                     {emqx_broker,publish,1,
                                  [{file,"src/emqx_broker.erl"},{line,171}]},
                     {emqx_protocol,do_publish,2,
                                    [{file,"src/emqx_protocol.erl"},
                                     {line,556}]},
                     {emqx_connection,handle_packet,2,
                                      [{file,"src/emqx_connection.erl"},
                                       {line,352}]},
                     {emqx_connection,process_incoming,2,
                                      [{file,"src/emqx_connection.erl"},
                                       {line,332}]}]}

**Comment by encojosh** [comment]
Any update on this issue?

**Comment by sshhawwnn** [comment]
I am facing this issue with round_robbin too.

3 subscribers with clean_sess=false

```
2019-04-15 11:43:18.706 [error] Publisher@172.20.0.1:54712 ** State machine <0.2622.0> terminating,
** Last event = {cast,,
{incoming,,
{mqtt_packet,,
 {mqtt_packet_header,3,false,0,false},,
 {mqtt_packet_publish,<<"home">>,undefined,,
	 undefined},,
 <<"CCB + 1">>}}},
** When server state  = {connected,,
{state,esockd_transport,,
{ssl_socket,#Port<0.120>,,
{sslsocket,,
 {gen_tcp,#Port<0.120>,tls_connection,undefined},,
 [<0.2624.0>,<0.2623.0>]}},,
{{172,20,0,1},54712},,
undefined,running,100,,
{pstate,external,#Fun<emqx_connection.0.79394866>,,
{{172,20,0,1},54712},,
undefined,4,<<"MQTT">>,<<"Publisher">>,false,,
<0.2622.0>,undefined,undefined,<<"dev">>,,
<0.2294.0>,false,#{},16777216,undefined,undefined,,
60,false,true,true,ignore,,
#{msg => 0,pkt => 1},,
#{msg => 0,pkt => 1},,
true,,
{1555,328596,694467},,
false,,
#{from_client => 0,to_client => 0},,
emqx_connection,,
#{auth_result => success,,
  client_id => <<"Publisher">>,,
  mountpoint => undefined,,
  peername => {{172,20,0,1},54712},,
  username => <<"dev">>,zone => external}},,
{none,#{max_packet_size => 16777216,version => 4}},,
{emqx_gc,,
#{cnt => {1000,982},oct => {1048576,1048521}}},,
{keepalive,#Fun<emqx_connection.3.79394866>,755,45,,
{keepalive,check},,
#Ref<0.4201072722.3496476674.78620>,0},,
true,#Ref<0.4201072722.3496476674.78608>,undefined,,
undefined,undefined,15000}},
** Reason for termination = error:function_clause,
** Callback mode = [state_functions,state_enter],
** Stacktrace =,
**  [{emqx_shared_sub,do_pick_subscriber,,
[<<"test">>,<<"home">>,round_robbin,<<"Publisher">>,3],,
[{file,"src/emqx_shared_sub.erl"},{line,261}]},,
{emqx_shared_sub,pick_subscriber,5,,
[{file,"src/emqx_shared_sub.erl"},{line,258}]},,
{emqx_shared_sub,do_pick,5,[{file,"src/emqx_shared_sub.erl"},{line,253}]},,
{emqx_shared_sub,dispatch,4,,
[{file,"src/emqx_shared_sub.erl"},{line,110}]},,
{emqx_broker,publish,1,[{file,"src/emqx_broker.erl"},{line,201}]},,
{emqx_session,publish,3,[{file,"src/emqx_session.erl"},{line,279}]},,
{emqx_protocol,do_publish,2,[{file,"src/emqx_protocol.erl"},{line,554}]},,
{emqx_connection,handle_packet,3,,
[{file,"src/emqx_connection.erl"},{line,417}]}],
```

**Comment by sshhawwnn** [comment]
@spring2maz would appreciate if you could resolve this asap. Thanks

**Comment by spring2maz** [comment]
will look into it

**Comment by spring2maz** [comment]
Hi. @sshhawwnn There is a typo in our config schema.
`round_robbin` should be `round_robin` instead.

e.g.
> `round_robbin, %% round robin alive subscribers one message after another`

Embarrassingly, the word `robin` was spelled correct in the comment, but not the enum declaration.

A remedy work around is to modify your `emqx.schema` file and replace `round_robbin` with `round_robin`.
Find the file in `INSTALL_DIR/releases/3.0/schema/emqx.schema`
`INSTALL_DIR` depends on how your emqx is installed, but it should be in the parent directory of `emqx` executable. e.g. in `/usr/lib/emqx` if it's installed from RPM.

**Comment by sshhawwnn** [comment]
Hi @spring2maz , I am currently using v3.1-rc.1 docker image and I tried `round_robin` which resulted in the broker unable to boot up.

**Comment by spring2maz** [comment]
@sshhawwnn I'll try to run it with a mounted emqx.schema file to verify.

**Comment by spring2maz** [comment]
Hi @sshhawwnn 
I verified with this command:
```
docker run --name test -v $PWD/emqx.conf:/opt/emqx/etc/emqx.conf -v $PWD/emqx.schema:/opt/emqx/releases/3.1/schema/emqx.schema emqx/emqx:v3.1-rc.1
```
where
`$PWD/emqx.conf` and `$PWD/emqx.schema` both have `round_robbin` replaced with `round_robin`.

**Comment by spring2maz** [comment]
also tried to reproduce with command:
`docker run --name test -v $PWD/emqx.conf:/opt/emqx/etc/emqx.conf emqx/emqx:v3.1-rc.1`
i.e. only fix the config, but not schema, then the node fail to start with error message:
```
2019-04-21T08:02:18.958145+00:00 [error] "round_robin" is not a valid enum value, acceptable values are: random, round_robbin, sticky, hash
```
