### ISSUE TITLE
can not start emqtt in windows10 x64

### ISSUE THREAD

**Issue by mozaiquan** [emqx/emqx#2221]
#### Environment

- OS: Windows 10 x64
- Erlang/OTP:  10.2
- EMQ:  emqttd-windows10-v2.3.11/emqx-windows10-v3.0.1

#### Description

Can not start emqtt service using  'emqttd start' or 'emqx start'.
Start output like:
![emqttcannotstart](https://user-images.githubusercontent.com/4318394/52772506-9a52ca00-3073-11e9-8a41-0af05f157b16.PNG)

when I use 'emqttd_ctl status' or 'emqx_ctl status' 
there is an error:
![emqttstatuserror](https://user-images.githubusercontent.com/4318394/52772566-c4a48780-3073-11e9-90cc-69a04a512bac.PNG)

The same error will happen when I use 'emqttd stop' or 'emqx stop'.

#

**Comment by Gilbert-Wong** [comment]
I suggest you to start emqx via `emqx.cmd start` on windows.

**Comment by mozaiquan** [comment]
> I suggest you to start emqx via `emqx.cmd start` on windows.

there will be another error:
![emqxstarterror](https://user-images.githubusercontent.com/4318394/52775883-a2af0300-307b-11e9-8f15-d7027da32361.PNG)

**Comment by Gilbert-Wong** [comment]
If you want to start emqx on windows , the path you place emqx should not contain space, you could place emqx in root directory of C disc. For example, `C:\emqx`. Anyway, it is not a good choice to run emqx on windows. I suggest you to run emqx on linux.

**Comment by mozaiquan** [comment]
> If you want to start emqx on windows , the path you place emqx should not contain space, you could place emqx in root directory of C disc. For example, `C:\emqx`. Anyway, it is not a good choice to run emqx on windows. I suggest you to run emqx on linux.

Works! Thanks very much.
