### ISSUE TITLE
io/max_fds undefined

### ISSUE THREAD

**Issue by sshhawwnn** [emqx/emqx#2222]
#### Environment

- OS: Centos 7.5
- Erlang/OTP: 
- EMQ: 3.0.1

#### Description

*A description of the issue*
Why is my max_fds undefined?
PS: I had already ran through all the tuning for the server.

cpu/load1               : 0.74
cpu/load5               : 0.52
cpu/load15              : 0.34
memory/total            : 118696456
memory/processes        : 29776752
memory/processes_used   : 29498904
memory/system           : 88919704
memory/atom             : 1148105
memory/atom_used        : 1136310
memory/binary           : 49576
memory/code             : 28660307
memory/ets              : 35807992
process/limit           : 2097152
process/count           : 386
io/max_fds              : undefined
io/active_fds           : undefined
ports/count           : 20
ports/limit           : 1048576

**Comment by sshhawwnn** [comment]
@tigercl @turtleDeng any fix for this?

**Comment by tigercl** [comment]
I'm sorry to trouble you with this problem. This is indeed a bug, and we will fix it in v3.1-beta.2

**Comment by terry-xiaoyu** [comment]
It has been be fixed, thanks
