### ISSUE TITLE
Time error receiving message for tools  websocket 

### ISSUE THREAD

**Issue by servucn** [emqx/emqx#2226]
#### Environment

* OS : window 2008 x64
* Erlang/OTP:
* EMQ:  3.0

#### Description

接收消息的时间显示错误，凌晨0点的时间显示为12点的，没有使用24小时，也没有加AM、PM.

**Comment by Gilbert-Wong** [comment]
Please open issue with English and provide more details.

**Comment by linjunjj** [comment]
@servucn   sorry, I can't reproduce your issues, please provide more details.

**Comment by servucn** [comment]
> details
![image](https://user-images.githubusercontent.com/6037332/52844733-3b0ebb80-3140-11e9-8ecd-549dd4f834d4.png)

**Comment by wivwiv** [comment]
@servucn We will use 24-hour formatting in next version.

**Comment by Gilbert-Wong** [comment]
Has been fixed in 3.1-beta.1.
