### ISSUE TITLE
emqtt can build for aarch64??

### ISSUE THREAD

**Issue by zhongtianxie** [emqx/emqx#2227]
#### Environment

- OS: 
- Erlang/OTP: 
- EMQ: 

#### Description

*A description of the issue*

**Comment by zhanghongtong** [comment]
Yes, we have v3.0.1 arm64 architecture package and docker image, you can access [here](https://github.com/emqx/emqx/releases) and [here](https://hub.docker.com/r/emqx/emqx/tags) to get

**Comment by zhongtianxie** [comment]
> Yes, we have v3.0.1 arm64 architecture package and docker image, you can access [here](https://github.com/emqx/emqx/releases) and [here](https://hub.docker.com/r/emqx/emqx/tags) to get

thanks a lot , i'd got it. thanks you effort .

**Comment by zhanghongtong** [comment]
@zhongtianxie Seems the issue is resolved. I am going to close this issue. Please feel free to re-open if you still have the same trouble.
