### ISSUE TITLE
where can I git emqttd2.0?

### ISSUE THREAD

**Issue by wigginskuang** [emqx/emqx#2228]
#### Environment

- OS: centos7
- Erlang/OTP:erlang20 
- EMQ: emqttd2.3.11

#### Description
你好，我想源码编译安装emq2.3.11，但当我从文档2.0--程序安装--源码编译安装--git clone https://github.com/emqtt/emq-relx.git页面  下载的确实emqx3.0

[http://emqtt.com/docs/v2/install.html#build-from-source](url)

**Comment by terry-xiaoyu** [comment]
Checkout the code from tag 2.3.11.
