### ISSUE TITLE
Emqx Broker .deb file size is 0

### ISSUE THREAD

**Issue by biswaKL** [emqx/emqx#2236]
Hi, I am trying to install emqx in raspberry pi, but while downloading the files for Raspberry PI, its downloading with 0KB

These files i tried:

- emqx-edge-raspbian8-v3.0.1.zip
- emqx-edge-raspbian8-v3.0.1_armhf.deb
- emqx-edge-raspbian9-v3.0.1.zip
- emqx-edge-raspbian9-v3.0.1_armhf.deb

From this URL:
https://www.emqx.io/downloads/broker/v3.0.1/

**Comment by zhanghongtong** [comment]
This is our mistake, now we are fixing this problem, you can get the required installation package from [here](https://github.com/emqx/emqx/releases/tag/v3.0.1).

**Comment by zhanghongtong** [comment]
This issue has been fixed, thank you for your attention
