### ISSUE TITLE
Is Emqx Edge available?

### ISSUE THREAD

**Issue by mzy2240** [emqx/emqx#2237]
#### Environment

- OS: 
- Erlang/OTP: 
- EMQ: 

#### Description

*A description of the issue*

This is not about an issue. I try to find more documents about the emqx edge, but cannot find more except for the few sentences in the homepage. So my question is, is edge available now or when will it be available? Thanks!

**Comment by jinfahua** [comment]
Edge is still under testing, and will be available in the 1Q of 2019.

**Comment by mzy2240** [comment]
Thanks!

**Comment by ajaywazir** [comment]
Is it available for Windows 10 IoT LTSB

**Comment by Gilbert-Wong** [comment]
Sorry,  @ajaywazir, for now, nope. I’ll as our team leader if we have schedule to support this platform.

Gilbert Wong
On May 22, 2019, 3:42 PM +0800, ajaywazir <notifications@github.com>, wrote:

Is it available for Windows 10 IoT LTSB
