### ISSUE TITLE
plugins can't load but compile successfully

### ISSUE THREAD

**Issue by wigginskuang** [emqx/emqx#2239]
#### Environment

- OS: centos7
- Erlang/OTP: erlang19
- EMQ: emqttd2.3.11

#### Description
I created a plugins named emq_zdc and then compiled successfully  through  the steps like this

[root@MQTT ~]# cd  emqx-rel-2.3.11/
[root@MQTT emqx-rel-2.3.11]# vim Makefile
DEPS += emq_zdc 
[root@MQTT emqx-rel-2.3.11]# vim relx.config
{emq_zdc, load},
[root@MQTT emqx-rel-2.3.11]# rm -rf _rel/ && make clean && make

then  I think I complie successfully

make[2]: Entering directory `/root/emqx-rel-2.3.11/deps/jwerl'
===> No entry for profile default in config.
===> Verifying dependencies...
===> Compiling jwerl
make[2]: Leaving directory `/root/emqx-rel-2.3.11/deps/jwerl'
make[1]: Leaving directory `/root/emqx-rel-2.3.11/deps/emq_auth_jwt'
make[1]: Entering directory `/root/emqx-rel-2.3.11/deps/emq_zdc'
 GEN    rebar.config
make[1]: Leaving directory `/root/emqx-rel-2.3.11/deps/emq_zdc'
===> Starting relx build process ...
===> Resolving OTP Applications from directories:
          /root/emqx-rel-2.3.11/deps
          /usr/local/lib/erlang/lib
          /root/emqx-rel-2.3.11/apps
===> Resolved emqttd-2.3.11
===> Including Erts from /usr/local/lib/erlang
===> release successfully created!

but when I load my plugins , it cant 't find my plugins. why?

[root@MQTT emqx-rel-2.3.11]# ./_rel/emqttd/bin/emqttd_ctl plugins load emq_zdc
load plugin error: not_found

**Comment by wigginskuang** [comment]
@emqplus

**Comment by phanimahesh** [comment]
Please allow some time for the team to triage the issue. It is rude to demand attention within 2 hours of posting.

Can you verify if `_rel/emqttd/lib`  has your plugin directory, with an `ebin` under it containing your beam and app files?

It is not directly related, but is there a reason you are using v2 instead of v3? Can you upgrade to emqx v3?

**Comment by terry-xiaoyu** [comment]
@wigginskuang Make sure you have `emq_zdc.config` in `_rel/emqx/etc/plugins/`, it is copied from `deps/emq_zdc/etc/emq_zdc.config` when building the project.

**Comment by turtleDeng** [comment]
We will close this issue and you can reopen if there are any problems.
