### ISSUE TITLE
Hi team i am getting below error in emqx server start

### ISSUE THREAD

**Issue by sbcsuman** [emqx/emqx#2240]
cd emqx && ./bin/emqx console
root@ip-172-31-26-124:/home/ubuntu/suman# cd emqx && ./bin/emqx console
Exec: /home/ubuntu/suman/emqx/erts-10.2/bin/erlexec -boot /home/ubuntu/suman/emqx/releases/3.0.1/emqx -mode embedded -boot_var ERTS_LIB_DIR /home/ubuntu/suman/emqx/erts-10.2/../lib -mnesia dir "/home/ubuntu/suman/emqx/data/mnesia/emqx@127.0.0.1" -config /home/ubuntu/suman/emqx/data/configs/app.2019.02.20.07.33.59.config -args_file /home/ubuntu/suman/emqx/data/configs/vm.2019.02.20.07.33.59.args -vm_args /home/ubuntu/suman/emqx/data/configs/vm.2019.02.20.07.33.59.args -- console
Root: /home/ubuntu/suman/emqx
/home/ubuntu/suman/emqx
Protocol 'inet_tcp': register/listen error: eaddrinuse

**Comment by phanimahesh** [comment]
Please check if some other program is using the needed ports, and/or change the ports emqx listens on in the config.

**Comment by terry-xiaoyu** [comment]
@sbcsuman You might have already started an emqx instance, or there's another process is using the tcp port that emqx required.  They are:
```
# emqx will occupy these port:
# - 1883 port for MQTT
# - 8883 port for MQTT(SSL)
# - 8083 for WebSocket/HTTP
# - 8084 for WSS/HTTPS
# - 8080 for mgmt API
# - 18083 for dashboard
# - 4369 for port mapping
# - 5369 for gen_rpc port mapping
# - 6369 for distributed node
```
