### ISSUE TITLE
"emqx_ctl users add  login password"   not reflected in file "emqx_auth_username.conf"

### ISSUE THREAD

**Issue by Marc-drouet** [emqx/emqx#2241]
#### Environment

- OS:  DEBIAN 8.2
- Erlang/OTP: 
- EMQ: 3.0.1

#### Description

*A description of the issue*

"emqx_ctl users add  login password"   not reflected in file "emqx_auth_username.conf"

probably i have missunderstood something, where are stored my list of users???

**Comment by phanimahesh** [comment]
The change is applied to the running broker. Configuration files are not updated.

Emqx does not modify any of its config files currently. It uses them to generate erlang/otp compatible config files when starting up, that's all.

**Comment by Marc-drouet** [comment]
> The change is applied to the running broker. Configuration files are not updated.
> 
> Emqx does not modify any of its config files currently. It uses them to generate erlang/otp compatible config files when starting up, that's all.

Hi,

So if i restart EMQX i will lost my users?

**Comment by terry-xiaoyu** [comment]
@Marc-drouet it won't. your user records will be stored into disk db files which is in your emqx data path, mostly it is `/var/lib/emqx/mnesia/` if you are using emqx for ubuntu.

**Comment by Marc-drouet** [comment]
ok, understood,  
you are right the file is there 
thanks a lot
