### ISSUE TITLE
emqx status not display

### ISSUE THREAD

**Issue by sbcsuman** [emqx/emqx#2242]
Hi Team,
I installed emqx server in ubuntu system. its working fine in webbrowser.
but when i check the emqx_ctl status command executed i am getting below error
Node 'emqx@127.0.0.1' not responding to pings.

**Comment by phanimahesh** [comment]
How are you running the broker?

**Comment by terry-xiaoyu** [comment]
@sbcsuman I guess you have solved the problem. Reopen this if you want.
