### ISSUE TITLE
Windows Server 2012 R2 启动失败(windows10-v3.0.1)

### ISSUE THREAD

**Issue by doudoustrongly** [emqx/emqx#2246]
#### Environment

- OS: Windows Server 2012 R2
- Erlang/OTP: 
- EMQ: emqx-windows10-v3.0.1

#### Description

用下列命令启动时失败：emqx start，emqx console,请问是什么原因？
另外我本机的win10系统是可以正常启动的

**Comment by Gilbert-Wong** [comment]
First, I do not recommend you to run emqx on windows server. Linux server is a better choice for emqx. Second, you should place emqx on windows path which could not contains `-` and ' ' and then execute `emqx.cmd console` to launch emqx.

**Comment by avivros** [comment]
I understand that Linux is a preferred option but why is not recommended to run Emqx on Windows Server?
Is it just that Linux performance is better or are there some limitations?

**Comment by Gilbert-Wong** [comment]
Because there are many problems in windows package of emqx. We'll improve it as soon as possible.

**Comment by pantongren** [comment]
@Gilbert-Wong  Does the emq2.3 of Windows also have problems in package?

**Comment by Gilbert-Wong** [comment]
Yes, via tuning the linux kernel, emqx would have better performance on linux.

**Comment by Gilbert-Wong** [comment]
And we have did some fix work on windows package, now you can start emqx-rc.1 successfully whether the path contains space or not. However, the function of emqx service register still do not work.

**Comment by Gilbert-Wong** [comment]
But I suppose that your issue could be closed? @doudoustrongly
