### ISSUE TITLE
emqx_auth_http and authentication filter chain

### ISSUE THREAD

**Issue by vborcea** [emqx/emqx#2250]
#### Environment

- OS: Ubuntu 18.04
- Erlang/OTP: 
- EMQ: ubuntu18.04-v3.0.0

#### Description
Desired scenario: 
I have loaded and configured 2 authentication plugins
emqx_auth_username
emqx_auth_http

Desired Result:
Try authentication for a client in a chain:
if it succeeds for any of the 2 ones, than the client is authenticated
if it doesn't than it's not authenticated

Current result:
It tries the authentication over HTTP and it failes because of
1. the authentication broker is not running/available
2. bad credentials

It doesn't try anymore the authentication with username/password

From what I have read in the documentation all the authentication plugins should be placed in the authentication filter chain and they should be tried in the plugin loading order defined aswell in data/loaded_plugins.

emqx_management.
emqx_recon.
emqx_retainer.
emqx_dashboard.
emqx_auth_username.
emqx_auth_http.

Note that there was a related issue which is marked as closed:
https://github.com/emqx/emqx/issues/1363

**Comment by Forsure-Wang** [comment]
@vborcea Maybe you should try to load the `emqx_auth_username` plugin first and then the `emqx_auth_http`

**Comment by zmstone** [comment]
prior to v5, there was a lack fo deterministic ordering of the auth checks provided by the auth plugins.
a deterministic auth-chain is implemented per this proposal: https://github.com/emqx/eip/blob/86358711dd55ed53ee8859c0365edcc77b2cf934/active/0015-unified-authentication.md
