### ISSUE TITLE
Anonymous authentication with enabled auth plugin

### ISSUE THREAD

**Issue by vytasmk** [emqx/emqx#2256]
#### Environment

- OS: Ubuntu 18.04.2 LTS, Docker version 18.06.1-ce, build e68fc7a 
- EMQ: Docker emqx/emqx:v3.0.1

#### Description

Was trying to migrate from Mosquitto broker to EMQX and have a problem with anonymous authentication when auth_http plugin is enabled. As I understand if client has no username and/or no password set it just drops connection even if _mqtt.allow_anonymous = true_ is set in configuration. 

In our case we need to allow anonymous user to access broker but access should be limited to few topics only. Client introduces itself to the system by sending request to one topic. System creates username and password for that client and sends back login data and certificate to the client using another topic. Then client connects to the broker using SSL connection with newly created credentials to start normal communication as authenticated client.

Mosquitto broker allows such behavior if anonymous authentication is enabled and if client comes without username it assigns new username as "anonymous" and passes it to authentication plugins. Could it be possible to change this behavior in EMQX broker to?

When _mqtt.allow_anonymous = true_ is enabled and client comes without username and/or password broker should set some new username let's say _anonymous_ by default. Even for more flexibility that username could be configurable from config file like _mqtt.anonymous_username = anonymous_. In this case authentication plugins will receive that username and empty password and should not brake any logic. If password is mandatory for plugins to work correctly it can be also set in configuration file (ex. _mqtt.anonymous_password = anonymous_). In such case we identify client as anonymous inside plugin and can control it to allow or deny to sub/pub to some topics. Also in addition we can check clientid if it matches some pattern (ex. it must be numeric in structure xx-xxxx-xxx) and allow connection or just drop it.

If _mqtt.allow_anonymous = false_ then it should work the same way as now when clients without username and password can't connect at all.

**Comment by vytasmk** [comment]
Found that some body already has asked very similar question one year ago: https://github.com/emqx/emqx-auth-http/issues/64. I think my proposed way with mapping anonymous clients to some username and/or password will solve that case to.

**Comment by victorclaessen** [comment]
Very similar to my question #1577. Hope this will get implemented soon.

**Comment by HJianBo** [comment]
Hi, @vytasmk  Thanks for your suggestion. I think we have implemented this feature

In the 4.0-x, we introduce the `anonymous` fields in the ClientInfo.  And you can get it in the `client.authenticate`,  `client.check_acl` hook callback function. 

Please check it! Thanks again  :]

**Comment by HJianBo** [comment]
I'll close it first. If there are any other questions, please open it again
