### ISSUE TITLE
/api/v3/subscriptions show only node-local subscriptions

### ISSUE THREAD

**Issue by brstgt** [emqx/emqx#2261]
#### Environment

Docker: emqx/emqx:v3.0.1

#### Description

When querying the subscriptions, the route should return all subscriptions, not only the local ones. For node-specific querying there are different endpoints.
Can easily be repro'ed in a multi-node cluster when requesting the URL from multiple nodes with a hand full of subs.

**Comment by HJianBo** [comment]
It had fixed in the v4.x
