### ISSUE TITLE
Node not responding to pings- how to track this?

### ISSUE THREAD

**Issue by Marina190489** [emqx/emqx#2268]
In version 2.1.1 is it possible to track the history of when the node was down or not responding to pings? 
trying to debug a case where I know that the node didn't respond to pings but I need to know when it started.

**Comment by Gilbert-Wong** [comment]
Sorry, impossible.

Gilbert Wong
On Feb 26, 2019, 8:49 PM +0800, Marina190489 <notifications@github.com>, wrote:

In version 2.1.1 is it possible to track the history of when the node was down or not responding to pings?
trying to debug a case where I know that the node didn't respond to pings but I need to know when it started.

**Comment by Marina190489** [comment]
Thanks.
Is it possible in version 3?

**Comment by Gilbert-Wong** [comment]
Sorry, neither.
