### ISSUE TITLE
开启Tracer失败

### ISSUE THREAD

**Issue by fangsj** [emqx/emqx#2270]
#### Environment

- OS: Centos7
- Erlang/OTP: R21/10.2.1
- EMQ: 3.0.1

#### Description

*开启Tracer失败，[error] trace client_id qqq: {handler_not_added,
                              {eacces,
                               {child,undefined,clientid_qqq,
                                {logger_h_common,start_link,
                                 [#{config =>
                                     #{burst_limit_enable => true,
                                       burst_limit_max_count => 500,
                                       burst_limit_window_time => 1000,
                                       drop_mode_qlen => 200,
                                       file => "log/qq.log",
                                       filesync_repeat_interval => 5000,
                                       flush_qlen => 1000,
                                       max_no_bytes => infinity,
                                       max_no_files => undefined,
                                       overload_kill_enable => false,
                                       overload_kill_mem_size => 3000000,
                                       overload_kill_qlen => 20000,
                                       overload_kill_restart_after => 5000,
                                       sync_mode_qlen => 10,type => halt},
                                    filesync_repeat_interval => no_repeat,
                                    filter_default => stop,
                                    filters =>
                                     [{meta_key_filter,
                                       {#Fun<emqx_tracer.0.23379586>,
                                        {client_id,<<"qqq">>}}}],
                                    formatter =>
                                     {emqx_logger_formatter,
                                      #{template =>
                                         [time," [",level,"] ",
                                          {client_id,
                                           [{peername,
                                             [client_id,"@",peername," "],
                                             [client_id," "]}],
                                           [{peername,[peername," "],[]}]},
                                          msg,"\n"]}},
                                    id => clientid_qqq,level => all,
                                    module => logger_disk_log_h}]},
                                temporary,2000,worker,
                                [logger_h_common]}}}<br/>*

*请问我需要怎么解决*

**Comment by ZZ-LGF** [comment]
你好。我也遇到这个问题，请问你怎么解决的？
