### ISSUE TITLE
Load plugin emqx_auth_redis error

### ISSUE THREAD

**Issue by aaamitsingh** [emqx/emqx#2272]
#### Environment

- OS: Ubuntu 18.04.2 LTS
- Erlang/OTP: 20.2.2
- EMQ: emqx-ubuntu18.04-v3.0.1_amd64.deb

#### Description
1. Getting the following error while enabling "EMQ X Authentication/ACL with Redis" plugin from dashboard:
![image](https://user-images.githubusercontent.com/25000347/53514934-e2033800-3aee-11e9-9f9b-e7c8403d23d6.png)

2. I'm getting an error while I'm loading the "emqx_auth_redis" plugin from the cli:
emqx_ctl plugins load emqx_auth_redis
=ERROR REPORT==== 27-Feb-2019::18:29:03.235701 ===
Load plugin emqx_auth_redis error, cannot start app emqx_auth_redis for {bad_return,
                                                                         {{emqx_auth_redis_app,
                                                                           start,
                                                                           [normal,
                                                                            []]},
                                                                          {'EXIT',
                                                                           {{badmatch,
                                                                             {error,
                                                                              {shutdown,
                                                                               {failed_to_start_child,
                                                                                emqx_auth_redis,
                                                                                {shutdown,
                                                                                 {failed_to_start_child,
                                                                                  worker_sup,
                                                                                  {shutdown,
                                                                                   {failed_to_start_child,
                                                                                    {worker,
                                                                                     1},
                                                                                    {connection_error,
                                                                                     econnrefused}}}}}}}}},
                                                                            [{emqx_auth_redis_app,
                                                                              start,
                                                                              2,
                                                                              [{file,
                                                                                "src/emqx_auth_redis_app.erl"},
                                                                               {line,
                                                                                24}]},
                                                                             {application_master,
                                                                              start_it_old,
                                                                              4,
                                                                              [{file,
                                                                                "application_master.erl"},
                                                                               {line,
                                                                                277}]}]}}}}
load plugin error: {emqx_auth_redis,
                    {bad_return,
                     {{emqx_auth_redis_app,start,[normal,[]]},
                      {'EXIT',
                       {{badmatch,
                         {error,
                          {shutdown,
                           {failed_to_start_child,emqx_auth_redis,
                            {shutdown,
                             {failed_to_start_child,worker_sup,
                              {shutdown,
                               {failed_to_start_child,
                                {worker,1},
                                {connection_error,econnrefused}}}}}}}}},
                        [{emqx_auth_redis_app,start,2,
                          [{file,"src/emqx_auth_redis_app.erl"},{line,24}]},
                         {application_master,start_it_old,4,
                          [{file,"application_master.erl"},{line,277}]}]}}}}}

**Comment by linjunjj** [comment]
Hi @aaamitsingh  Did you start redis? Please check redis state.

**Comment by aaamitsingh** [comment]
Yes, Redis is running.  I'm using "Amazon ElastiCache for Redis" and I can connect it from the Redis-cli running on same Ec2 instance where EMQX is installed.

**Comment by aaamitsingh** [comment]
@linjunjj @turtleDeng : Any help?

**Comment by linjunjj** [comment]
@aaamitsingh How do you configure your ‘emqx_auth_redis.conf’ profile?

**Comment by aaamitsingh** [comment]
@linjunjj : Here is my "emqx_auth_redis.conf" file:
![image](https://user-images.githubusercontent.com/25000347/53789598-d67a9b80-3f4a-11e9-84ba-a5db5b530171.png)

**Comment by linjunjj** [comment]
@aaamitsingh But the emqx plugin shows that the connection was rejected，Did you open a firewall?

**Comment by aaamitsingh** [comment]
@linjunjj : Yes, the firewall is open and I can connect to the Redis from the Redis-cli running on same Ec2 instance where EMQX is installed.

**Comment by linjunjj** [comment]
@aaamitsingh  I can't reproduce this problem. I offer my guess，Does your redis configuration use internal IP Address in redis and EMQ environments? If your redis configuration uses an extranet ip Address, make sure that the extranet IP Address is accessible.  How do you Redis-cli running? In Ec2？

**Comment by aaamitsingh** [comment]
@linjunjj : I have installed the redis-cli on the same server where emqx is running. I can access the Redis by using basic redis-cli command like "redis-cli -h MyServerAddress -p 6379"

**Comment by linjunjj** [comment]
@aaamitsingh if redis and emq on the same server.  You try local address `127.0.0.1:6379`

**Comment by RodaBVB** [comment]
Hi, @aaamitsingh  I'm encountering the same problem. Since you closed this issue, could you please suggest some solution?

**Comment by abhishekaj** [comment]
@aaamitsingh @linjunjj I am getting the same error. It is able to connect with redis-cli from emqx ec2 instance, but not through plugin. security groups are all open.  Could you please suggest some solution?
