### ISSUE TITLE
EMQ发布和订阅消息时，服务器就会主动断开连接

### ISSUE THREAD

**Issue by xiangjiangnan** [emqx/emqx#2278]
#### Environment

- OS: Ubuntu 16.04
- Erlang/OTP: 
- EMQ: 2.3.11

#### Description

I've setup an ACL and AUTH via emqx mysql plugin, but the client got disconnected when publishing msgs or subscribing topics.

#### A description of the issue

The logs:
```
22:31:17.189 [error] gen_server <0.1507.0> terminated with reason: no match of right hand value {error,einval} in esockd_cidr:parse_addr/1 line 61
22:31:17.190 [error] CRASH REPORT Process <0.1507.0> with 0 neighbours exited with reason: no match of right hand value {error,einval} in esockd_cidr:parse_addr/1 line 61 in gen_server2:terminate/3 line 1157
22:31:17.191 [error] Supervisor 'esockd_connection_sup - <0.1438.0>' had child connection started with emqttd_client:start_link([{max_publish_rate,0},{client_idle_timeout,30000},{client_enable_stats,false},{max_clientid_len,...},...]) at <0.1507.0> exit with reason no match of right hand value {error,einval} in esockd_cidr:parse_addr/1 line 61 in context connection_crashed
22:32:14.046 [error] gen_server <0.1593.0> terminated with reason: no match of right hand value {error,einval} in esockd_cidr:parse_addr/1 line 61
22:32:14.046 [error] CRASH REPORT Process <0.1593.0> with 0 neighbours exited with reason: no match of right hand value {error,einval} in esockd_cidr:parse_addr/1 line 61 in gen_server2:terminate/3 line 1157
22:32:14.047 [error] Supervisor 'esockd_connection_sup - <0.1438.0>' had child connection started with emqttd_client:start_link([{max_publish_rate,0},{client_idle_timeout,30000},{client_enable_stats,false},{max_clientid_len,...},...]) at <0.1593.0> exit with reason no match of right hand value {error,einval} in esockd_cidr:parse_addr/1 line 61 in context connection_crashed
22:37:30.545 [error] gen_server <0.1864.0> terminated with reason: no match of right hand value {error,einval} in esockd_cidr:parse_addr/1 line 61
22:37:30.546 [error] CRASH REPORT Process <0.1864.0> with 0 neighbours exited with reason: no match of right hand value {error,einval} in esockd_cidr:parse_addr/1 line 61 in gen_server2:terminate/3 line 1157
22:37:30.546 [error] Supervisor 'esockd_connection_sup - <0.1438.0>' had child connection started with emqttd_client:start_link([{max_publish_rate,0},{client_idle_timeout,30000},{client_enable_stats,false},{max_clientid_len,...},...]) at <0.1864.0> exit with reason no match of right hand value {error,einval} in esockd_cidr:parse_addr/1 line 61 in context connection_crashed
22:42:47.919 [error] gen_server <0.2140.0> terminated with reason: no match of right hand value {error,einval} in esockd_cidr:parse_addr/1 line 61
22:42:47.920 [error] CRASH REPORT Process <0.2140.0> with 0 neighbours exited with reason: no match of right hand value {error,einval} in esockd_cidr:parse_addr/1 line 61 in gen_server2:terminate/3 line 1157
```

**Comment by terry-xiaoyu** [comment]
@xiangjiangnan Hi, please check if you have any typos about IP addresses in your configuration file of mysql auth plugin.

**Comment by xiangjiangnan** [comment]
> @xiangjiangnan Hi, please check if you have any typos about IP addresses in your configuration file of mysql auth plugin.

I use the default config,does it any question? But my username authentication is also based on this mysql auth plugin and it runs ok.

**Comment by terry-xiaoyu** [comment]
Could you post the content of your emq_auth_pgsql.conf here?

**Comment by xiangjiangnan** [comment]
> Could you post the content of your emq_auth_pgsql.conf here?
This is my emq_auth_mysql.conf file.

## MySQL server address.
##
## Value: Port | IP:Port
##
## Examples: 3306, 127.0.0.1:3306, localhost:3306
auth.mysql.server = 127.0.0.1:3306

## MySQL pool size.
##
## Value: Number
auth.mysql.pool = 8

## MySQL username.
##
## Value: String
auth.mysql.username = root

## MySQL Password.
##
## Value: String
auth.mysql.password = xxxx(mysql password )

## MySQL database.
##
## Value: String
auth.mysql.database = mqtt

## Variables: %u = username, %c = clientid

## Authentication query.
##
## Note that column names should be 'password' and 'salt' (if used).
## In case column names differ in your DB - please use aliases,
## e.g. "my_column_name as password".
##
## Value: SQL
##
## Variables:
##  - %u: username
##  - %c: clientid
##
auth.mysql.auth_query = select password,salt from mqtt_user where username = '%u' limit 1
## auth.mysql.auth_query = select password_hash as password from mqtt_user where username = '%u' limit 1

## Password hash.
##
## Value: plain | md5 | sha | sha256 | bcrypt
auth.mysql.password_hash = md5,salt

## sha256 with salt prefix
## auth.mysql.password_hash = salt,sha256

## bcrypt with salt only prefix
## auth.mysql.password_hash = salt,bcrypt

## sha256 with salt suffix
## auth.mysql.password_hash = sha256,salt

## pbkdf2 with macfun iterations dklen
## macfun: md4, md5, ripemd160, sha, sha224, sha256, sha384, sha512
## auth.mysql.password_hash = pbkdf2,sha256,1000,20

## Superuser query.
##
## Value: SQL
##
## Variables:
##  - %u: username
##  - %c: clientid
auth.mysql.super_query = select is_superuser from mqtt_user where username = '%u' limit 1

## ACL query.
##
## Value: SQL
##
## Variables:
##  - %a: ipaddr
##  - %u: username
##  - %c: clientid
auth.mysql.acl_query = select allow, ipaddr, username, clientid, access, topic from mqtt_acl where ipaddr = '%a' or username = '%u' or username = '$all' or clientid = '%c'

**Comment by xiangjiangnan** [comment]
I'm so sorry .It's my fault , i insert a record containing NULL,but  i write to 'NULL'.
Thanks.
