### ISSUE TITLE
emqx_bridge_kafka can't recover after kafka restart

### ISSUE THREAD

**Issue by xpunch** [emqx/emqx#2280]
#### Environment

- OS: Docker Enterprise Image 
- EMQ: v3.0.0

#### Description

*The kafka cluster is broken down for some reason, so the emq failed to send message to kafka.
But when I restart the kafka cluster, emq stoped to run emqx_bridge_kafka.
I think emqx_bridge_kafka need a backoff mechanism to keep away from manual restart emqx_bridge_kafka plugin.*

`(emqx@172.23.0.4)1> 2019-03-05 01:39:38.176 [error] d12@172.23.0.1:47054 Call produce error: error, {timeout,
                               [{wolff_producer,send_sync,3,
                                    [{file,"src/wolff_producer.erl"},
                                     {line,133}]},
                                {emqx_bridge_kafka,msg_to_kafka,2,
                                    [{file,"src/emqx_bridge_kafka.erl"},
                                     {line,203}]},
                                {emqx_bridge_kafka,on_message_publish,2,
                                    [{file,"src/emqx_bridge_kafka.erl"},
                                     {line,151}]},
                                {emqx_hooks,run_,3,
                                    [{file,"src/emqx_hooks.erl"},{line,107}]},
                                {emqx_broker,publish,1,
                                    [{file,"src/emqx_broker.erl"},{line,169}]},
                                {emqx_protocol,do_publish,2,
                                    [{file,"src/emqx_protocol.erl"},
                                     {line,533}]},
                                {emqx_connection,handle_packet,2,
                                    [{file,"src/emqx_connection.erl"},
                                     {line,352}]},
                                {emqx_connection,process_incoming,2,
                                    [{file,"src/emqx_connection.erl"},
                                     {line,332}]}]}`

**Comment by Gilbert-Wong** [comment]
Hi, @xpunch, for enterprise edition emqx enterprise, you have to contact with @zhengyupan. We do not do technique support of emqx enterprise on github.
