### ISSUE TITLE
Plugins for Backhand Postgres

### ISSUE THREAD

**Issue by Sisipos** [emqx/emqx#2283]
#### Environment

- OS:  Windows 7
- Erlang/OTP: 
- EMQ:  EMQ X 3.0.0

#### Description
There is no emqx_backend_pgsql plugin loaded!

*A description of the issue*
In EMQ X documentation, there is plugins for published message to store to DB (like Posgresql)
but when i try to load ("./bin/emqx_ctl plugins load emqx_backend_pgsql)
gives and error like "not found plugins".
Is this "backend plugins" options of EMQ Enterprise  Edition? or I can use with EMQ X Broker?
I will appreciate for your answers.
Regards.

Ilker Turkyilmaz

**Comment by phanimahesh** [comment]
Yes, the backend plugins are not open source, and are bundled with EMQX enterprise edition.
