### ISSUE TITLE
Aliyun Iot Bridge

### ISSUE THREAD

**Issue by kscorpio** [emqx/emqx#2284]
Q1 How to bridge message to Aliyun Iot

Q2 If need to pre-create a product and device on Aliyun Iot，

Q3 If need pre-create, the device should be a general device or a gateway device?

**Comment by Eluso** [comment]
if your scenes to be used like this:
devices-->emqx-->cloud iot

please pre-creat gateway, for bridge please do: 

`vi etc/emqx.conf`

`bridge.aws.address = 127.0.0.1:1883` (change to your cloud iot IP:port)
`bridge.aws.client_id = bridge_aws` (your cloud iot gateway client_id)
`bridge.aws.username = user` (your cloud iot gateway username)
`bridge.aws.password = passwd` (your cloud iot gateway password)

other bridge.aws.*  was optional

`./bin/emqx start`
`./bin/emqx_ctl bridges list` (check bridges status)
`./bin/emqx_ctl bridges start aws` (start/stop bridge)

for Aliyun address,clientID,username,password please visit https://help.aliyun.com/document_detail/86706.html

**Comment by kscorpio** [comment]
Q 4 ,When to transmit local topic message to Aliyun Iot( send or receive) , how to configure the parameters below? 
 
# bridge.aliyun.forwards =   
# bridge.aliyun.subscription.1.topic = cmd/topic1
# bridge.aliyun.subscription.1.qos = 0 

# bridge.aliyun.subscription.2.topic = cmd/topic2
# bridge.aliyun.subscription.2.qos = 0

Q5 Because, Aliyun iot has a special device name gateway, which can control some sub-device. Can the devices of EMQx play the role of sub-device on Aliyun not

**Comment by Eluso** [comment]
`bridge.aliyun.forwards =topic1/#,topic2/#` will forward all topic under topic1/,topic2/
`bridge.aliyun.subscription.1.topic = cmd/topic1`  will sub topic
`bridge.aliyun.subscription.1.qos = 0`  qos level

**Comment by kscorpio** [comment]
I config  bridge.aliyun.forwards = /product/bridge_device/update ,  Because ,Aliyun IOT Limit topic functions only can publish or subscribe by the device named " bridge_device " , 
So on Aliyun ,EMQ is just a general device named  " bridge_device "

**Comment by kscorpio** [comment]
On the EMQ side , When l the devices just only publish to the topic /product/bridge_device/update,  EMQ can forward the message to Aliyun

**Comment by kscorpio** [comment]
Is there a method , realize the devices of EMQ communicate with the devices of Aliyun

**Comment by Gilbert-Wong** [comment]
Sorry for late response. Which kind of communication between EMQ and Aliyun you want ?

**Comment by Gilbert-Wong** [comment]
@kscorpio you can bridge emqx and aliyun to realize your purpose.
