### ISSUE TITLE
sub $queue/topic not work

### ISSUE THREAD

**Issue by elvizlai** [emqx/emqx#2285]
#### Environment

- OS: 
        docker
- Erlang/OTP: 
- EMQ: 
        v3.0.1

#### Description

pub to topic `test/abc`

and try to sub `$queue/test/abc` but not work.

but `$share/group/test/abc` works well.

**Comment by Eluso** [comment]
need use '$queue/test/+' or '$share/group/test/+'

**Comment by elvizlai** [comment]
@Eluso 

1、No need to use `+` or `#`, because topic name is clear.

2、only `$queue` not works

go client code
```
	// not work
	cli.Subscribe("$queue/test/abc/123", 1, func(c mqtt.Client, msg mqtt.Message) {
		fmt.Println("queue", string(msg.Payload()), msg.Duplicate(), msg.Retained(), msg.MessageID(), msg.Qos())
	})

	// works well
	cli.Subscribe("$share/group1/test/abc/123", 1, func(c mqtt.Client, msg mqtt.Message) {
		fmt.Println("share", string(msg.Payload()), msg.Duplicate(), msg.Retained(), msg.MessageID(), msg.Qos())
	})
```

**Comment by Eluso** [comment]
Thanks,get it.
Can your try other mqtt client sdk?
I have use JMeter4.0 + MQTT Plugin work normal.

JMeter:https://archive.apache.org/dist/jmeter/binaries/
Plugin:https://github.com/emqx/mqtt-jmeter

**Comment by linjunjj** [comment]
Hi@elvizlai  You may need to read the documents，The `$queue` can work for my test. The subscribe topic `$queue` is equivalent to load balancing. For example. When two clients connect to the emq broker, Subscribe to a `$queue/test/abc` topic , then publish a message, One of the two receives a message.

**Comment by elvizlai** [comment]
@Eluso @linjunjj may be there is something wrong with go sdk?

The dashboard shows $queue subscribe ok, but there is no message for go to print

![jietu20190307-150602 2x](https://user-images.githubusercontent.com/501861/53938397-22644680-40eb-11e9-9911-33bccb75a4e7.jpg)
![jietu20190307-151005 2x](https://user-images.githubusercontent.com/501861/53938400-255f3700-40eb-11e9-9663-5fa7118de132.jpg)

**Comment by elvizlai** [comment]
LOL... go mqtt client only support $share prefix now.

![jietu20190307-151635 2x](https://user-images.githubusercontent.com/501861/53938732-19c04000-40ec-11e9-93bb-c5cdcababced.jpg)

**Comment by Eluso** [comment]
@elvizlai I have try paho work normal, $queue &  $share  usually for share sub.
