### ISSUE TITLE
Does EMQX support MQTT-SN + DTLS(two-way SSL)?

### ISSUE THREAD

**Issue by motomyslen** [emqx/emqx#2286]
Hi,
Does EMQX support MQTT-SN + DTLS(two-way SSL)? I can see on main page that there are MQTT-SN and DTLS but I can't find nothing about usage in documentation.

**Comment by Gilbert-Wong** [comment]
Sorry, for now, emqx-sn plugin does not support DTLS. We'll support DTLS in the future.

**Comment by motomyslen** [comment]
Thanks for quick answer. https://github.com/emqx/esockd can't be combined with mqtt-sn as termination proxy? Maybe you know if solution like this will work: MQTT-SN client -> (DTLS encryption) -> (DTLS termination proxy) -> MQTT-SN Gateway?

**Comment by Gilbert-Wong** [comment]
For now, no, but we'll support this feature in the future.

**Comment by HJianBo** [comment]
It is now supported in 5.0. We have made more optimizations for multi-protocol support in 5.0, but the official release of 5.0 may take another 1-2 months.
