### ISSUE TITLE
emqx.conf may lead to start fail

### ISSUE THREAD

**Issue by kscorpio** [emqx/emqx#2287]
#### Environment

- OS: Ubuntu 14.04
- Erlang/OTP: 
- EMQ:  3.0.1

#### Description
 When change some parameters line 's order. EMQ may start fail, 

will not show message "emqx 3.0.1 is started successfully!" , and not run

**Comment by kscorpio** [comment]
If file emqx.conf has some errors , can emq shows the error lines when start

**Comment by kscorpio** [comment]
like ： bridge.edge.type = in may lead to start fail

**Comment by Gilbert-Wong** [comment]
Hi, @kscorpio , sorry for late reply. The `bridge.edge.type` should be `auto` or `manual`.

This feature would be fixed in 3.2.
