### ISSUE TITLE
Mosquitto bridge Connection Refused: not authorised

### ISSUE THREAD

**Issue by dophlin** [emqx/emqx#2288]
#### Environment

- OS: Linux Docker
- Erlang/OTP: 
- EMQ: v3.1-beta1

#### Description
Short: Mosquitto bridge gets an unauthorized error when trying to bridge a mosquitto broker to an EMQX broker.
Detail:
I've run an instance of latest EMQX docker container and an instance of Mosquitto docker container on a same machine. The mosquitto bridge config is:
```
log_type all
connection emqx
address lqmqtt:1883
topic messagebox/1/2 in 0
try_private false
remote_clientid mosquitto_id_emqx
remote_username mosquitto_user_emqx
remote_password password
bridge_protocol_version mqttv311
```

and, this is the acl.conf:

```
{allow, {user, "dashboard"}, subscribe, ["$SYS/#"]}.
{allow, {ipaddr, "127.0.0.1"}, pubsub, ["$SYS/#", "#"]}.
{allow, {user, "mosquitto_user_emqx"}, pubsub, ["messagebox/1/2"]}.
```
Everything works well until I add the EMQX_ACL_NOMATCH=deny variable in order to prevent other users to access the broker. When I add the  EMQX_ACL_NOMATCH=deny the bridge starts to say the client is not authorized. It seems, the bridge is not follow the acl.conf rules. Is there any additional configuration for mosquitto bridge acl configurations?

**Comment by phanimahesh** [comment]
No, can you manually try connecting to the client? What are your enabled plugins, and auth modules?

**Comment by dophlin** [comment]
@phanimahesh I can connect to the EMQX with the provided username and password through websocket client tool. Also, the client can subscribe to the message/1/2 and publish to the topic too. but the bridge of mosquitto is not successfull. Here is the mosquitto log:

```
1551983169: Connecting bridge sample (lqmqtt:1883)
1551983169: Bridge mosquitto_id_emqx sending CONNECT
1551983169: Received CONNACK on connection local.mosquitto_id_emqx.
1551983169: Connection Refused: not authorised
1551983169: Socket error on client local.mosquitto_id_emqx, disconnecting.
```

Here are the enabled plugins: emqx_dashboard, emqx_management, emqx_recon, emqx_retainer

**Comment by dophlin** [comment]
When I disable EMQX_ACL_NOMATCH=deny, the bridge connects successfully, in the EMQX dashboard, the protover of the bridge connection is v4. But in the mosquitto.conf I have set mqtt version as follow:
`bridge_protocol_version mqttv311`
Is it related to the issue?

**Comment by dophlin** [comment]
Any support?

**Comment by Gilbert-Wong** [comment]
Yes, in your scenario, you should disable the `EMQX_ACL_NOMATCH=deny` or modify the acl rule. You could refer our official [doc](https://developer.emqx.io/docs/emq/v3/en/config.html#allow-anonymous-and-acl-file).

**Comment by dophlin** [comment]
I've just solved my problem by getting the mosquitto user all access.

**Comment by phanimahesh** [comment]
Looks like the mosquitto bridge is trying to subscribe or publish to more topics then. You can try tracing its clientid with debug logging on emqx to see what exactly it is trying to do and why. It might be a bug in mosquitto to try connecting to more topics than configured.

That still shouldn't produce a connack error though, connection should succeed. ACL_NOMATCH has no bearing on connection success, only on access control. It's something worth investigating, in any case.

**Comment by Gilbert-Wong** [comment]
Hi, @dophlin, has your problem been resolved?
