### ISSUE TITLE
Handle exception in java client when token is expired

### ISSUE THREAD

**Issue by visit24ir** [emqx/emqx#2291]
#### Environment

- OS: Ubuntu 16.4
- Erlang/OTP: 
- EMQ: 

#### Description

Is there a clear way to handle exceptions when jwt token is expired ? 

In javascript client such as **mqtt.js** , when i send expired token to password field in connect method, offline method is called.In Java though, there is a package called: **Eclipse Paho** 'connectionLost' event is called.here is the thing : 

By and large, there is not an appropriate way to handle token expiration exception in clients.
connection lost event could occure  everywhere and every time, not just in token expiration 
for instance : when mqtt server is offline or when s.th happend to connection. so there is not a transparent way to handle this.

**1. What happens in backend side when an expired token is sent in password field ?**
**2. What event should be called in client side ?
3. How do detect in clients that emqx server denies the connection because there is an expired jwt token ?**

**Comment by linjunjj** [comment]
@visit24ir  Emq will disconnect client  when token is expired.

**Comment by visit24ir** [comment]
@linjunjj I believe disconnection alone is not just enough. i suppose there must be a way to handle exceptions such as sending non-zero return code "5"  not authorized.

**Comment by zhengyupan** [comment]
In the newly released EMQ X V3.1-beta.2, if the JWT is expired, a reason code (5) will be returned to the connecting client.
