### ISSUE TITLE
broker.sys_interval not working

### ISSUE THREAD

**Issue by dophlin** [emqx/emqx#2292]
#### Environment

- OS: Linux/Docker
- Erlang/OTP: R21/10.2.1
- EMQ: v3.1-beta.1

#### Description
I've changed the value of the broker.sys_interval, from 1m to 10s. But the iteration of publishing statistics to the $SYS topics is 1 minutes.

**Comment by linjunjj** [comment]
@dophlin  We checked and found this problem.

**Comment by linjunjj** [comment]
The problem has been fixed and will be released in v3.1-beta.2
