### ISSUE TITLE
log level configuration

### ISSUE THREAD

**Issue by Marina190489** [emqx/emqx#2298]
Hi,
is there any way to configure a level between info and warning for syslogs (in version 2.1 or 3)?
info is too much for the broker to handle and warning level is not enough for the data that we need.

Thanks,
Marina

**Comment by HJianBo** [comment]
Hi, @Marina190489 The EMQX support seven log levels, you can use the `notice` level between `info` and `warning`.  But maybe it doesn't have more different than `info` level.

We will improve the difference in all of the levels in the future version.

**Comment by Gilbert-Wong** [comment]
We have tune the log in emqx3.1-rc.1 release and the documentation would be completed soon.
