### ISSUE TITLE
Update documentation of plugin / hook design

### ISSUE THREAD

**Issue by pritstift** [emqx/emqx#2302]
#### Environment

- OS: 
- Erlang/OTP: 
- EMQ: 

#### Description

The documentation about hook usage is not up to date: https://developer.emqx.io/docs/emq/v3/en/design.html#hook-usage it still refers to the old emqttd repo.

**Comment by HJianBo** [comment]
Hi, @pritstift Thanks for you report this, I'll fix it later!

**Comment by Gilbert-Wong** [comment]
Hi, @pritstift , this work has been completed.
