### ISSUE TITLE
incorrect handling of incoming traffic at ethernet frame boundary ?

### ISSUE THREAD

**Issue by kaido42** [emqx/emqx#2303]
#### Environment

- OS: Linux ip-172-31-8-139 4.4.0-1065-aws #75-Ubuntu SMP Fri Aug 10 11:14:32 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
- Erlang/OTP: Erlang/OTP 21 [erts-10.2.3] [source] [64-bit] [smp:1:1] [ds:1:1:10] [async-threads:1]
- EMQ: emqx v3.1-beta.1

#### Description

getting the following in the emqx.log (ip-address changed):

2019-03-12 16:44:11.556 [error] 2175c4dd@9.9.9.9:23498 Parse failed for function_clause
Stacktrace:[{emqx_frame,parse_utf8_string,
                        [<<57,66,75,18,73,112,114,111,116,111,99,111,108,46,
                           99,58,50,52,53,58,51,58,84,101,115,116,105,110,103,
                           32,101,114,114,111,114,32,50,32,48,49,50,51,52,53,
                           54,55,56,57,48,49,50,51,52,53,54,55>>],
                        [{file,"src/emqx_frame.erl"},{line,354}]},
            {emqx_frame,parse_packet,3,
                        [{file,"src/emqx_frame.erl"},{line,163}]},
            {emqx_frame,parse_frame,4,
                        [{file,"src/emqx_frame.erl"},{line,104}]},
            {emqx_connection,process_incoming,3,
                             [{file,"src/emqx_connection.erl"},{line,371}]},
            {gen_statem,call_state_function,5,
                        [{file,"gen_statem.erl"},{line,1660}]},
            {gen_statem,loop_event_state_function,6,
                        [{file,"gen_statem.erl"},{line,1023}]},
            {proc_lib,wake_up,3,[{file,"proc_lib.erl"},{line,259}]}]
Error data:<<55,56,57,66,75,18,73,112,114,111,116,111,99,111,108,46,99,58,50,
             52,53,58,51,58,84,101,115,116,105,110,103,32,101,114,114,111,114,
             32,50,32,48,49,50,51,52,53,54,55,56,57,48,49,50,51,52,53,54,55,56,
             57,48,49,50,51,52,53,54,55,56,57,48,49,50,51,52,53,54,55,56,57,74,
             5,53,160,26,33,65>>

looked at the traffic with tcpdump/wireshark. the logged 'Error data' points exactly at the 2nd part of split tcp packet.

![image](https://user-images.githubusercontent.com/4962946/54224898-25a06d80-4503-11e9-9617-e39eadbe7cf1.png)

full tcpdump file is available on request (cannot share it publicly)

repeatable quite easily.

**Comment by HJianBo** [comment]
Hi, @kaido42 I have reviewed the frame parsing code, It seems to be right. Could you provide completely the 1st and  2nd part of raw data to help to dig out this problem?

**Comment by kaido42** [comment]
> Could you provide completely the 1st and 2nd part of raw data to help to dig out this problem?

sure, but not publicly. your email?

**Comment by HJianBo** [comment]
You can send it to: heeejianbo@gmail.com

**Comment by kaido42** [comment]
> You can send it to: [heeejianbo@gmail.com](mailto:heeejianbo@gmail.com)

sent.

**Comment by Think7** [comment]
I think i've encountered the same bug :(

Here are my logs:
https://gist.github.com/Think7/f93d267ef7646c11bc3a3ec4e10a5ca8

**Comment by kaido42** [comment]
easily repeatable with the following python code:

```
mport paho.mqtt.client as mqtt
import time


def main():
  client = mqtt.Client()
  client.connect("localhost", 4883 , 60) ## your broker address/port here
  client.loop_start()

  for x in range (16):
      msg = "_" + str(x)
      msg = msg.zfill(100)
      client.publish('kala/kala', payload=msg)

  time.sleep(2)
  client.loop_stop()

main()
```

**Comment by Think7** [comment]
> easily repeatable with the following python code:
> 
> ```
> mport paho.mqtt.client as mqtt
> import time
> 
> 
> def main():
>   client = mqtt.Client()
>   client.connect("localhost", 4883 , 60) ## your broker address/port here
>   client.loop_start()
> 
>   for x in range (16):
>       msg = "_" + str(x)
>       msg = msg.zfill(100)
>       client.publish('kala/kala', payload=msg)
> 
>   time.sleep(2)
>   client.loop_stop()
> 
> main()
> ```

Is there a workaround for this? Can i format my messages differently? I'll be very honest and say i don't fully understand the issue / cause.

**Comment by kaido42** [comment]
>> Is there a workaround for this? 

sure, the bug has to be fixed :)

**Comment by Think7** [comment]
> > > Is there a workaround for this?
> 
> sure, the bug has to be fixed :)

Haha, ok. :P

Just emailed @HJianBo some packet captures as well. Hopefully they are helpful. Didn't mean to be annoying by asking. Just a bit stuck using Mosquitto which cant handle the volume i need to throw at it.

**Comment by Gilbert-Wong** [comment]
This is exactly bug, @HJianBo is working on it. Thanks for your guys feedback.

**Comment by Think7** [comment]
I hate to be // that guy // but when will the fixed version be packaged and released? :P

**Comment by Gilbert-Wong** [comment]
emqx 3.1-beta.3, we would release it tomorrow.

**Comment by Think7** [comment]
Thank you! 🍍

**Comment by HJianBo** [comment]
Hi guys, the EMQX 3.1-beta.3 has released at two days ago. It has fixed this problem. 

I'll close this issue. Please reopen it, if you have any problems! Thanks for your report!
