### ISSUE TITLE
Clients from same IP connected to clustered brokers get only one message

### ISSUE THREAD

**Issue by archerian** [emqx/emqx#2310]
#### Environment

- OS: Centos 7
- Erlang/OTP: R21/10.2.1
- EMQ: v3.1-beta.1

#### Description

I have two brokers in a cluster configuration behind a haproxy LB. I'm using mosquitto_pub to send test messages on a topic from another computer on the same network. On that computer, I have two mosquitto_sub clients listening to the same topic. When I send messages I notice only 1 of the two subscribed clients get the message sent via mosquitto_pub. It isn't the same client every time, but only one client gets the message each time.

**Comment by Gilbert-Wong** [comment]
Hi, could you please tell me the topic you subscribed ?

Gilbert Wong
On Mar 14, 2019, 1:43 AM +0800, Arun Kirthi Cherian <notifications@github.com>, wrote:
Environment

  *   OS: Centos 7
  *   Erlang/OTP: R21/10.2.1
  *   EMQ: v3.1-beta.1

Description

I have two brokers in a cluster configuration behind a haproxy LB. I'm using mosquitto_pub to send test messages on a topic from another computer on the same network. On that computer, I have two mosquitto_sub clients listening to the same topic. When I send messages I notice only 1 of the two subscribed clients get the message sent via mosquitto_pub. It isn't the same client every time, but only one client gets the message each time.

**Comment by archerian** [comment]
mosquitto_pub.exe -h 10.167.36.179 -t Hello -m HelloTestMessage

**Comment by archerian** [comment]
It might still be random, but testing with 10 messages, its in a round robin format to each client, 1 message to 1st client, next to 2nd, next to 1st etc.

**Comment by archerian** [comment]
Looks like the clustering was broken sometime in between... so each publish was round robin sent to the other broker and hence the missing messages. I'll close this issue
