### ISSUE TITLE
Webhook problem

### ISSUE THREAD

**Issue by jgustavo99** [emqx/emqx#2321]
- OS: Ubuntu 18.04 LTS
- EMQ: 3.0.1

Good Morning.

I configured the webhook however in the configured URL I do not receive any POST or GET data.

What can it be?

**Comment by Gilbert-Wong** [comment]
Could you please provide more details? Such as log files and configure file?

**Comment by jgustavo99** [comment]
Hello!

In session events and connected devices is working.

but when I post a message on the topic I do not receive the data in the callback.

**Comment by Gilbert-Wong** [comment]
Yeah, this bug exactly existed in 3.0.1, but in latest release of emqx. It has been fixed.

**Comment by jgustavo99** [comment]
Is the beta case already fixed?

**Comment by Gilbert-Wong** [comment]
Yes, you could try with emqx 3.1 beta2.

Gilbert Wong
On Mar 18, 2019, 9:35 AM +0800, João Gustavo Balestrin dos Santos <notifications@github.com>, wrote:

Is the beta case already fixed?

**Comment by jgustavo99** [comment]
Thank you. A doubt. Is there any documentation that directs me to migrate one version to another?

For example, a beta for stable.

**Comment by Gilbert-Wong** [comment]
Sorry for our lagging documents. For now , there is no such docs. But we would improve it as quickly as possible.

Gilbert Wong
On Mar 18, 2019, 9:40 AM +0800, João Gustavo Balestrin dos Santos <notifications@github.com>, wrote:

Thank you. A doubt. Is there any documentation that directs me to migrate one version to another?

For example, a beta for stable.
