### ISSUE TITLE
Reload fails when the plugin started

### ISSUE THREAD

**Issue by jinrm** [emqx/emqx#2328]
#### Environment

- OS: Ubuntu 14.04
- Erlang/OTP: 
- EMQ: 3.1 beta 2

#### Description

The reload works well when the plugin is not started. But now the reload will fail if the plugin has been started. 

The error  is:
 
Reload plugin error:[{emqx_plugins,unload,
                         [{plugin,emqx_auth_clientid,"v3.1-beta.2",undefined,
                              "EMQ X Authentication with ClientId/Password",
                              undefined,true,undefined}],
                         [{file,"src/emqx_plugins.erl"},{line,238}]},
                     {emqx_mgmt_cli,plugins,1,
                         [{file,"src/emqx_mgmt_cli.erl"},{line,344}]},
                     {emqx_ctl,run_command,2,
                         [{file,"src/emqx_ctl.erl"},{line,64}]},
                     {rpc,'-handle_call_call/6-fun-0-',5,
                         [{file,"rpc.erl"},{line,197}]}]

**Comment by Gilbert-Wong** [comment]
We have fixed this problem and release beta2 yesterday.

**Comment by jinrm** [comment]
validated in the latest 3.1 beta.2 build, and it has been fixed.
