### ISSUE TITLE
SSL Letsencrypt

### ISSUE THREAD

**Issue by jgustavo99** [emqx/emqx#2335]
- OS: Ubuntu 18.04 
- EMQ: 3.1

Hello! 

How can I add the ssl letsencrypt certificate in EMQX (Websocket and MQTT)?

I've already tried using the tutorial: https://medium.com/@emqtt/using-lets-encrypt-certificates-in-emq-b11e0e57efa6
 
But I did not succeed since the tutorial is from version 2.3,

**Comment by zhengyupan** [comment]
Hi @jgustavo99 In principle the TLS configuration of 2.3 and 3.1 is very similar. Could you describe at which step do you have an issue exactly? If you can give us the output on emqx, it could be helpful.

**Comment by chimit** [comment]
The same problem in v3.1-rc.1. Did exactly what is described in [this article](https://medium.com/@emqtt/using-lets-encrypt-certificates-in-emq-b11e0e57efa6), but nothing works - HTTPS dashboard, WSS, TLS.

**Comment by fluffis** [comment]
Copying the certificate + key to /etc/emqx/certs/ and chown to emqx:emqx solves the error, but of cause creates an issue with the certbot reissue cycle and possible an issue with the privkey.

**Comment by chimit** [comment]
@turtleDeng any progress on this?

**Comment by jgustavo99** [comment]
> Copying the certificate + key to /etc/emqx/certs/ and chown to emqx:emqx solves the error, but of cause creates an issue with the certbot reissue cycle and possible an issue with the privkey.

But then what would be the best way to solve the problem? No problems with certificate renewal, etc.

**Comment by i906** [comment]
For renewal, I followed this guide: https://certbot.eff.org/docs/using.html#renewing-certificates and created this post deploy hook.

```sh
#!/bin/sh

set -e

for domain in $RENEWED_DOMAINS; do
        case $domain in
        example.com)
                daemon_cert_root=/etc/emqx/certs

                # Make sure the certificate and private key files are
                # never world readable, even just for an instant while
                # we're copying them into daemon_cert_root.
                umask 077

                cp "$RENEWED_LINEAGE/cert.pem" "$daemon_cert_root/cert.pem"
                cp "$RENEWED_LINEAGE/privkey.pem" "$daemon_cert_root/key.pem"
                cp "$RENEWED_LINEAGE/chain.pem" "$daemon_cert_root/cacert.pem"

                # Apply the proper file ownership and permissions for
                # the daemon to read its certificate and key.
                chown emqx:emqx "$daemon_cert_root/cert.pem" \
                        "$daemon_cert_root/key.pem" \
                        "$daemon_cert_root/cacert.pem"

                chmod 400 "$daemon_cert_root/cert.pem" \
                        "$daemon_cert_root/key.pem" \
                        "$daemon_cert_root/cacert.pem"

                service emqx restart >/dev/null
                ;;
        esac
done
```

**Comment by nightwolfz** [comment]
I managed to make it work in a slightly different way.

Use the script from @i906 but comment out the line that copies cacert.pem, then in your `emqx.conf` set it as following:

```
#### From letsencrypt
listener.wss.external.keyfile = /etc/emqx/certs/key.pem
listener.wss.external.certfile = /etc/emqx/certs/cert.pem

#### Has to be the one from EMXQ
listener.wss.external.cacertfile = /etc/emqx/certs/cacert.pem
```

**Comment by chimit** [comment]
Still waiting for a simple built-in solution.

**Comment by citkane** [comment]
From the Certbot docs:
https://certbot.eff.org/docs/using.html#where-are-my-certificates

It is OK to: 
```bash
chmod 0755 /etc/letsencrypt/{live,archive}
chgrp emqx /etc/letsencrypt/live/<domain>/privkey.pem
chgrp emqx /etc/letsencrypt/archive/<domain>/privkey1.pem
chmod 0640 /etc/letsencrypt/live/<domain>/privkey.pem
chmod 0640 /etc/letsencrypt/archive/<domain>/privkey1.pem
``` 
If you will never downgrade to an older version of Certbot.

I can confirm that this works on a fresh cert install.
The docs claim that these permissions will be retained across renewals, but I have not tested this yet.

My question is:
Does EMQX cache the cert files and will EMQX need to be restarted in a Certbot post deploy hook?

**Comment by a9965** [comment]
Hi.
I've been stuck in this problem for two days and I can't quite understand what the procedure is.

I direct the certificate path to live or archive?

Why do we give emqx permissions in the archive folder?

Thank you.

**Comment by zmstone** [comment]
sorry for the super late reply.
Erlang doc gave some hint: http://erlang.org/doc/man/ssl.html#clear_pem_cache-0
i.e. Erlang will cache PEMs and check changes on disk. I am not entirely sure about the check interval though.

As for SLL certificate files configuration, I believe this is the answer:
https://github.com/emqx/emqx/issues/3720#issuecomment-696487365

**Comment by teenkevo** [comment]
> For renewal, I followed this guide: https://certbot.eff.org/docs/using.html#renewing-certificates and created this post deploy hook.
> 
> ```shell
> #!/bin/sh
> 
> set -e
> 
> for domain in $RENEWED_DOMAINS; do
>         case $domain in
>         example.com)
>                 daemon_cert_root=/etc/emqx/certs
> 
>                 # Make sure the certificate and private key files are
>                 # never world readable, even just for an instant while
>                 # we're copying them into daemon_cert_root.
>                 umask 077
> 
>                 cp "$RENEWED_LINEAGE/cert.pem" "$daemon_cert_root/cert.pem"
>                 cp "$RENEWED_LINEAGE/privkey.pem" "$daemon_cert_root/key.pem"
>                 cp "$RENEWED_LINEAGE/chain.pem" "$daemon_cert_root/cacert.pem"
> 
>                 # Apply the proper file ownership and permissions for
>                 # the daemon to read its certificate and key.
>                 chown emqx:emqx "$daemon_cert_root/cert.pem" \
>                         "$daemon_cert_root/key.pem" \
>                         "$daemon_cert_root/cacert.pem"
> 
>                 chmod 400 "$daemon_cert_root/cert.pem" \
>                         "$daemon_cert_root/key.pem" \
>                         "$daemon_cert_root/cacert.pem"
> 
>                 service emqx restart >/dev/null
>                 ;;
>         esac
> done
> ```

When should I run this script. And is it possible to create some logic to run it automatically?

**Comment by zmstone** [comment]
There is no need to restart emqx for certs renewal, emqx relads the files everything 2 minutes or so.
Unless you’d like to force all clients to reconnect immediately.

> When should I run this script
anytime after the new certs are issued.

> And is it possible to create some logic to run it automatically?
Do you mean inside emqx?
I’m afraid not, because certs renewal is not quite a standardised procedure

**Comment by teenkevo** [comment]
> There is no need to restart emqx for certs renewal, emqx relads the files everything 2 minutes or so. Unless you’d like to force all clients to reconnect immediately.
> 
> > When should I run this script
> 
> anytime after the new certs are issued.
> 
> > And is it possible to create some logic to run it automatically?
> 
> Do you mean inside emqx? I’m afraid not, because certs renewal is not quite a standardised procedure

Thank you so much, you don’t how helpful this is.

**Comment by JiapengLi** [comment]
`emqx ctl pem_cache clean all` will force clear pem cache.

share my script in case someone may need.

```

#!/bin/bash

RENEWED_LINEAGE=/etc/letsencrypt/live/YOUR_DOMAIN
daemon_cert_root=/etc/emqx/certs

# Make sure the certificate and private key files are
# never world readable, even just for an instant while
# we're copying them into daemon_cert_root.
umask 077

cp "$RENEWED_LINEAGE/cert.pem" "$daemon_cert_root/cert.pem"
cp "$RENEWED_LINEAGE/privkey.pem" "$daemon_cert_root/key.pem"
cp "$RENEWED_LINEAGE/chain.pem" "$daemon_cert_root/cacert.pem"

# Apply the proper file ownership and permissions for
# the daemon to read its certificate and key.
chown emqx:emqx "$daemon_cert_root/cert.pem" \
        "$daemon_cert_root/key.pem" \
        "$daemon_cert_root/cacert.pem"

chmod 400 "$daemon_cert_root/cert.pem" \
        "$daemon_cert_root/key.pem" \
        "$daemon_cert_root/cacert.pem"
        
emqx ctl pem_cache clean all

```
