### ISSUE TITLE
when i run ./docker.sh build, i can't clone v3.0 from zhe github

### ISSUE THREAD

**Issue by homesangsang** [emqx/emqx#2338]
#### Environment

- OS: centos6.7
- Erlang/OTP: 
- EMQ:  v3.0

#### Description

*A description of the issue*
when I run `./docker.sh build`,  the env `EMQX_VERSION=v3.0` and `+ /bin/bash -c 'git clone -b v3.0 https://github.com/emqx/emqx-rel.git /emqx_rel     && cd /emqx_rel     && make distclean     && git checkout relx     && make     && mv _rel/emqx/* /emqx-amd64'
正克隆到 '/emqx_rel'...
fatal: 远程分支 v3.0 在上游 origin 未发现`
plase fix it

**Comment by zhanghongtong** [comment]
Emqx does not have a v3.0 tag, you can try v3.0.0
