### ISSUE TITLE
dashboard not change cluster node

### ISSUE THREAD

**Issue by 22factor** [emqx/emqx#2341]
#### Environment

- OS: Red Hat Enterprise Linux Server release 7.4 (Maipo) x86_64
- Erlang/OTP:  
- EMQ:  emqx 3.0.1

#### Description

If you change the server list from clustering to dashboard, the status information is not used.
 left menu (Connections / Sessions / Topics / Subscriptions)

**Comment by 22factor** [comment]
sorry. 
자세히 살펴보니 all node 가 안보이고, 개별 node 는 확인이 됩니다.

**Comment by HJianBo** [comment]
Hi @22factor, We already received this issue in https://github.com/emqx/emqx-dashboard/issues/37, and plan to fix it the future!

I'll close it, you can keep attention to another same issue. Thanks a lot!
