### ISSUE TITLE
$queue/foo，but rpc failed sometimes

### ISSUE THREAD

**Issue by iowarecc** [emqx/emqx#2354]
#### Environment

- OS: Cenos7
- Erlang/OTP: 21
- EMQ: 3.1

#### Description

2019-03-25 14:59:21.452 [error] event=connect_to_remote_server peer="emqx_pt_03@IP2" result=failure reason="econnrefused"
2019-03-25 14:59:21.453 [error] test1_Publisher_1@IP1:44362 [Broker] Failed to forward msg to emqx_pt_03@IP2: econnrefused
2019-03-25 14:59:21.452 [error] crasher:
    initial call: gen_rpc_client:init/1
    pid: <0.1725.0>
    registered_name: [] 
    exception exit: {badrpc,econnrefused}
      in function  gen_server:init_it/6 (gen_server.erl, line 358)
    ancestors: [gen_rpc_client_sup,gen_rpc_sup,<0.1056.0>]
    message_queue_len: 0
    messages: []
    links: [<0.1061.0>]
    dictionary: []
    trap_exit: true
    status: running
    heap_size: 1598
    stack_size: 27
    reductions: 3974
  neighbours:

build one cluster has 3 nodes: 
node1: emqx_pt_01@IP1
node2: emqx_pt_02@IP1
node3: emqx_pt_03@IP2

**Comment by zhengyupan** [comment]
Hi @iowarecc ,
Thanks for reporting. We can see in your error log there is 'econnrefused', which is often caused when a remote server is not accessible. Please check whether the necessary ports on the broker nodes are all accessible by each other and there is nothing prevents such access.
Also, '$queue/foo' is mentioned in the issue titile, please let us know how is it related to this issue.

**Comment by Gilbert-Wong** [comment]
Hi, @iowarecc, has your problem been resolved?

**Comment by mononym** [comment]
Closing as there has been no response for some time in spite of multiple requests for additional info.
