### ISSUE TITLE
CleanSession false, persistence not work

### ISSUE THREAD

**Issue by stringhuang** [emqx/emqx#2358]
#### Environment

- OS: CentOS Linux release 7.4.1708 (Core)
- Erlang/OTP: 20
- EMQ: 3.0.1
- node: uds-gww1, uds-gww2

#### Description

*A description of the issue*

 At 2019-03-26 00:00:40, clientId 'daluo15' subscribe topic 't15' with option -c (clean_session=false)
![image](https://user-images.githubusercontent.com/44996282/54935140-aaa37200-4f5a-11e9-882d-8007981b9f83.png)

And the clients, sessions, clients, subscriptions info of topic 't15' and clientId 'daluo15' is as below via command 'emqx_ctl' on both nodes:

![image](https://user-images.githubusercontent.com/44996282/54935266-e9392c80-4f5a-11e9-9f2c-8d3e757c049b.png)

![image](https://user-images.githubusercontent.com/44996282/54935285-f81fdf00-4f5a-11e9-9e24-7dc8e4fbf469.png)

we may see that the connection is on node uds-gww2.

At 2019-03-26 00:00:55, I manually broken the connection the re-subscribe:
![image](https://user-images.githubusercontent.com/44996282/54935420-3ae1b700-4f5b-11e9-86ad-ffbcefcc01b5.png)

And also check again the clients, sessions, clients, subscriptions info of topic 't15' and clientId 'daluo15' is as below via command 'emqx_ctl' on both nodes:

![image](https://user-images.githubusercontent.com/44996282/54935456-5056e100-4f5b-11e9-8c44-69a6c7430147.png)

![image](https://user-images.githubusercontent.com/44996282/54935488-5fd62a00-4f5b-11e9-843d-38d28b3d63ab.png)

This time, you may see the connection is on node uds-gww1.

At 2019-03-26 00:01:31, one message was published to topic 't15'. **But the subscriber did not get the message and from the debug info, it has the behavior of re-connect and re-subscribe !**

![image](https://user-images.githubusercontent.com/44996282/54935728-e0952600-4f5b-11e9-92e1-6881e0a51350.png)

![image](https://user-images.githubusercontent.com/44996282/54935673-ba6f8600-4f5b-11e9-8fab-a79ce25f6a42.png)

At 2019-03-26 00:01:36, one message was published to topic 't15' again, and the subscriber consumed the message successfully !
![image](https://user-images.githubusercontent.com/44996282/54935717-d6732780-4f5b-11e9-8d86-608720b9dd3d.png)

![image](https://user-images.githubusercontent.com/44996282/54935750-ed197e80-4f5b-11e9-8e30-e8a2fa450c27.png)

Indeed, I have done such test over 10 times, this "bug" will happen when under cluster environment and the connection is linked to another node compared to last connection.

From the capture of "the clients, sessions, clients, subscriptions info" under both nodes, 
I wonder whether the Synchronization of "sessions, subscriptions" is missing when cluster caused this event ?

**Comment by zhengyupan** [comment]
Thanks for reporting, we will look into it and come back to you again.

**Comment by HJianBo** [comment]
Hi, @stringhuang So sorry for late reply! 

I have checked your all described information and screenshots. There are two questions shown:

***Q1: Why not get `client&session` info by `emqx_ctl`***

Answer:  The `emqx_ctl clients` commands only show single node `client/session` info, not clusters. So it is a correct result as your test.

***Q2: A subscriber can't receive first publish message.***

I can't reproduce this problem, could you please provide more detail steps info about this and cluster status? Thanks

**Comment by stringhuang** [comment]
Hi @HJianBo , Sorry that, what are the  more detail steps info you need? Have you done test step by step from my guideline above ? Or else we could have online call on this.

**Comment by HJianBo** [comment]
Ok, You can mail me your WeChat ID

**Comment by stringhuang** [comment]
Hi @HJianBo , from your suggestion, I have tested the case under v3.1-rc.1 and it is great that the issue will not happen ! Cheers !
