### ISSUE TITLE
Retained message handling in EMQX cluster

### ISSUE THREAD

**Issue by archerian** [emqx/emqx#2359]
#### Environment

- OS: Windows 10
- Erlang/OTP:  R21/10.0.1
- EMQ: 3.0.0

#### Description

I'm running two EMQX brokers behind a Haproxy LB, lets call them e1 and e2.  Assume one client connects to the LB, gets assigned to e1, sends a retained message and disconnects.

1. If another client connects to the LB later and gets assigned to e2, will it get the retained message? 

2. If e1 gets shutdown after the initial client publishes a retained message on e1, will a client that later connects to the LB (and gets connected to e2) get the retained message?

**Comment by Gilbert-Wong** [comment]
No, if one node is down, all information on this node would be lost. The enterprise support the feature you want.

**Comment by HJianBo** [comment]
Hi, @archerian 
Q1: Yes, the second client will be received retained message published by the first client.
Q2: Can receive too

The retained message behavior defined by [emqx_retainer](https://github.com/emqx/emqx-retainer)

**Comment by HJianBo** [comment]
Hi, @archerian  Any remaining questions for there now? If not, we'll close this issue.

**Comment by archerian** [comment]
No more, thanks for the answers!
