### ISSUE TITLE
Maximum messages per second

### ISSUE THREAD

**Issue by gpstechsolucoes** [emqx/emqx#2365]
Can I limit the number of messages sent per client per second? To avoid brute force attacks for example? I want to do this directly in the EMQX configuration.

**Comment by Gilbert-Wong** [comment]
Hi, @gpstechsolucoes .
Yes, there is a configure entry called zone.external.publish_limit which is disabled by default. you could find this configure entry in emqx.conf and specify the publish limit of the external MQTT connections.

**Comment by HJianBo** [comment]
Hi @gpstechsolucoes Do you have any remaining questions. If not, We'll close it later.
