### ISSUE TITLE
Client disconnected when subscribing to multiple topics.

### ISSUE THREAD

**Issue by Think7** [emqx/emqx#2366]
#### Environment

- OS: Ubuntu 18.4
- Erlang/OTP: 10.2
- EMQ: 3.1-beta.3

#### Description

Hello,

If a client attempts to subscribe to multiple topics at once, or too quickly, it will be disconnected. EMXQ does not report any errors, it just drops the connection.

Another issue mentioned increasing the packet size. I set it to 10MB but still get disconnected.

Swapping out EMQX for mosquitto just for testing works as expected. All topics are subscribed and retained messages are delivered without the client being disconnected.

I have emailed logs and packet captures to @HJianBo

**Comment by HJianBo** [comment]
Hi, @Think7 I have checked the logs and captures. Unfortunately, I don't find these problems about multiple topics SUBSCRIBE Frame and Large PUBLISH Frame described above.

I'll try to reproduce these problems soon.

**Comment by HJianBo** [comment]
Hi, @Think7 I can't reproduce this problem. Could you provide more details about this?

**Comment by Think7** [comment]
I am writing an example project now. Give me 20 mins. 🍍

**Comment by Think7** [comment]
I emailed you an example project.

- Open the project in QtCreator
- Open MainWindow.cpp
- Change line 38 to TRUE to test subscribing multiple channels and see the disconnect.
- Change line 38 to FALSE to use a timer to subscribe to one topic per second.

**Comment by HJianBo** [comment]
Hi, @Think7 This problem was fixed and released at 3.1.rc.1.
