### ISSUE TITLE
 EMQTT cluster with k8s

### ISSUE THREAD

**Issue by ysyh15** [emqx/emqx#2368]
#### Environment

- OS: centos7
- Erlang/OTP: 
- EMQ: v3.0.1

#### Description
hello:
    I used k8s to set up the MQTT cluster, and when my pod was down, all my client connections were down as well. Is there any way to keep the connection up

**Comment by ysyh15** [comment]
In addition to the above environmental information
The k8s version is v1.13.4

**Comment by charlie-charlie** [comment]
only one pod down, but bring down all connections to the service? from what you mentioned, it isn't enough clear to me.  Are you using LB?

**Comment by zhanghongtong** [comment]
The MQTT protocol is based on TCP long connections, so it is normal for the client to disconnect when the pod is closed.

**Comment by charlie-charlie** [comment]
Yeah, if the client connected to one pod via service/LB, that client connection got disconnected when pod done, that is understandable. But it seems to me that ysyh15 said one pod done, all client connections disconnected. that is very weird.

**Comment by phanimahesh** [comment]
That is unclear, and would be extremely unusual. EMQX behaves relatively reasonably when losing members from its cluster.

**Comment by ysyh15** [comment]
thx a lot ,
