### ISSUE TITLE
emq_auth_mysql start with problem

### ISSUE THREAD

**Issue by hongcker** [emqx/emqx#2369]
#### Environment

- OS: 
- Erlang/OTP: 
- EMQ: 

#### Description
After I configerated emq_auth_mysql.conf and execute command "./emqttd plugins load emq_auth_mysql", an error occured as bellow shows:

[root@minan-kf-3 /data/emq/emqttd/bin]# ./emqttd_ctl plugins load emq_auth_mysql
load plugin error: {emq_auth_mysql,
                    {bad_return,
                     {{emq_auth_mysql_app,start,[normal,[]]},
                      {'EXIT',
                       {{badmatch,
                         {error,
                          {shutdown,
                           {failed_to_start_child,emq_auth_mysql,
                            {shutdown,
                             {failed_to_start_child,worker_sup,
                              {shutdown,
                               {failed_to_start_child,
                                {worker,1},
                                {{auth_method,<<"caching_sha2_password">>},
                                 [{mysql_protocol,build_handshake_response,5,
                                   [{file,"src/mysql_protocol.erl"},
                                    {line,310}]},
                                  {mysql_protocol,handshake,7,
                                   [{file,"src/mysql_protocol.erl"},
                                    {line,64}]},
                                  {mysql,init,1,
                                   [{file,"src/mysql.erl"},{line,499}]},
                                  {gen_server,init_it,2,
                                   [{file,"gen_server.erl"},{line,365}]},
                                  {gen_server,init_it,6,
                                   [{file,"gen_server.erl"},{line,333}]},
                                  {proc_lib,init_p_do_apply,3,
                                   [{file,"proc_lib.erl"},
                                    {line,247}]}]}}}}}}}}},
                        [{emq_auth_mysql_app,start,2,
                          [{file,"src/emq_auth_mysql_app.erl"},{line,33}]},
                         {application_master,start_it_old,4,
                          [{file,"application_master.erl"},{line,273}]}]}}}}}

I am thankful to you for help.

*A description of the issue*

**Comment by Gilbert-Wong** [comment]
Hi, @hongcker, could you please tell me which edition of mysql did you use ? If you use mysql 8.0, you should using the `mysql_native_password` as auth method instead of using `caching_sha2_password`

**Comment by rjbaat** [comment]
We have the same problem working with a DO managed mysql 8 server with legacy login method.
This is giving us this error:

```
{{emqx_auth_mysql_app,
7-4-2020 16:51:26 start,
7-4-2020 16:51:26 [normal,
7-4-2020 16:51:26 []]},
7-4-2020 16:51:26 {'EXIT',
7-4-2020 16:51:26 {{badmatch,
7-4-2020 16:51:26 {error,
7-4-2020 16:51:26 {shutdown,
7-4-2020 16:51:26 {failed_to_start_child,
7-4-2020 16:51:26 emqx_auth_mysql,
7-4-2020 16:51:26 {shutdown,
7-4-2020 16:51:26 {failed_to_start_child,
7-4-2020 16:51:26 worker_sup,
7-4-2020 16:51:26 {shutdown,
7-4-2020 16:51:26 {failed_to_start_child,
7-4-2020 16:51:26 {worker,
7-4-2020 16:51:26 1},
7-4-2020 16:51:26 {{auth_method,
7-4-2020 16:51:26 <<"caching_sha2_password">>},
7-4-2020 16:51:26 [{mysql_protocol,
7-4-2020 16:51:26 build_handshake_response,
7-4-2020 16:51:26 5,
7-4-2020 16:51:26 [{file,
7-4-2020 16:51:26 "/emqx_rel/_build/emqx/lib/mysql/src/mysql_protocol.erl"},
7-4-2020 16:51:26 {line,
7-4-2020 16:51:26 386}]},
7-4-2020 16:51:26 {mysql_protocol,
7-4-2020 16:51:26 handshake,
7-4-2020 16:51:26 7,
7-4-2020 16:51:26 [{file,
7-4-2020 16:51:26 "/emqx_rel/_build/emqx/lib/mysql/src/mysql_protocol.erl"},
7-4-2020 16:51:26 {line,
7-4-2020 16:51:26 72}]},
7-4-2020 16:51:26 {mysql_conn,
7-4-2020 16:51:26 init,
7-4-2020 16:51:26 1,
7-4-2020 16:51:26 [{file,
7-4-2020 16:51:26 "/emqx_rel/_build/emqx/lib/mysql/src/mysql_conn.erl"},
7-4-2020 16:51:26 {line,
7-4-2020 16:51:26 111}]},
7-4-2020 16:51:26 {gen_server,
7-4-2020 16:51:26 init_it,
7-4-2020 16:51:26 2,
7-4-2020 16:51:26 [{file,
7-4-2020 16:51:26 "gen_server.erl"},
7-4-2020 16:51:26 {line,
7-4-2020 16:51:26 374}]},
7-4-2020 16:51:26 {gen_server,
7-4-2020 16:51:26 init_it,
7-4-2020 16:51:26 6,
7-4-2020 16:51:26 [{file,
7-4-2020 16:51:26 "gen_server.erl"},
7-4-2020 16:51:26 {line,
7-4-2020 16:51:26 342}]},
7-4-2020 16:51:26 {proc_lib,
7-4-2020 16:51:26 init_p_do_apply,
7-4-2020 16:51:26 3,
7-4-2020 16:51:26 [{file,
7-4-2020 16:51:26 "proc_lib.erl"},
7-4-2020 16:51:26 {line,
7-4-2020 16:51:26 249}]}]}}}}}}}}},
7-4-2020 16:51:26 [{emqx_auth_mysql_app,
7-4-2020 16:51:26 start,
7-4-2020 16:51:26 2,
7-4-2020 16:51:26 [{file,
7-4-2020 16:51:26 "/emqx_rel/_build/emqx/lib/emqx_auth_mysql/src/emqx_auth_mysql_app.erl"},
7-4-2020 16:51:26 {line,
7-4-2020 16:51:26 38}]},
7-4-2020 16:51:26 {application_master,
7-4-2020 16:51:26 start_it_old,
7-4-2020 16:51:26 4,
7-4-2020 16:51:26 [{file,
7-4-2020 16:51:26 "application_master.erl"},
7-4-2020 16:51:26 {line,
7-4-2020 16:51:26 277}]}]}}}}
```
Now i see this FAQ:
https://github.com/emqx/FAQ/blob/master/en_US/errors.md

But we use already the Legacy – MySQL 5.x method of DO. This connection is working with other applications as expected. What else can we try?

As stated by DO: 

```
Having trouble connecting? Your MySQL client might not support the new MySQL 8 default password encryption. If you're experiencing issues with the Default (caching_sha2_password), change the mode to Legacy (mysql_native_password).
```
and that is what we did.

**Comment by rjbaat** [comment]
Also when inspecting the mysql user table the user we use is indeed setup with: mysql_native_password instead of: caching_sha2_password.

Do we need to setup the ENV with a different encryption?
EMQX_AUTH__MYSQL__PASSWORD_HASH

**Comment by HJianBo** [comment]
Nope. Not support yet. It only supports `mysql_native_password ` now

**Comment by rjbaat** [comment]
But we enabled mysql_native_password. The mysql user table confirms this. But it is still giving connection errors.
