### ISSUE TITLE
emq_auth_mysql start problem

### ISSUE THREAD

**Issue by hongcker** [emqx/emqx#2371]
#### Environment

- OS: 
- Erlang/OTP: 
- EMQ: 

#### Description

After I configerated emq_auth_mysql.conf and execute command "./emqttd plugins load emq_auth_mysql", an error occured as bellow shows:

[root@minan-kf-3 /data/emq/emqttd/bin]# ./emqttd_ctl plugins load emq_auth_mysql
load plugin error: {emq_auth_mysql,
                    {bad_return,
                     {{emq_auth_mysql_app,start,[normal,[]]},
                      {'EXIT',
                       {{badmatch,
                         {error,
                          {shutdown,
                           {failed_to_start_child,emq_auth_mysql,
                            {shutdown,
                             {failed_to_start_child,worker_sup,
                              {shutdown,
                               {failed_to_start_child,
                                {worker,1},
                                {{auth_method,<<"caching_sha2_password">>},
                                 [{mysql_protocol,build_handshake_response,5,
                                   [{file,"src/mysql_protocol.erl"},
                                    {line,310}]},
                                  {mysql_protocol,handshake,7,
                                   [{file,"src/mysql_protocol.erl"},
                                    {line,64}]},
                                  {mysql,init,1,
                                   [{file,"src/mysql.erl"},{line,499}]},
                                  {gen_server,init_it,2,
                                   [{file,"gen_server.erl"},{line,365}]},
                                  {gen_server,init_it,6,
                                   [{file,"gen_server.erl"},{line,333}]},
                                  {proc_lib,init_p_do_apply,3,
                                   [{file,"proc_lib.erl"},
                                    {line,247}]}]}}}}}}}}},
                        [{emq_auth_mysql_app,start,2,
                          [{file,"src/emq_auth_mysql_app.erl"},{line,33}]},
                         {application_master,start_it_old,4,
                          [{file,"application_master.erl"},{line,273}]}]}}}}}

I am thankful to you for your help

*A description of the issue*

**Comment by Gilbert-Wong** [comment]
Hi, @hongcker ,duplicated with issue #2369
