### ISSUE TITLE
build failing for emqx_rule_engine

### ISSUE THREAD

**Issue by s4kibs4mi** [emqx/emqx#2374]
#### Environment

- OS: ubuntu
- Erlang/OTP: 21
- EMQ: v3.1-beta.3

#### Description
```
erlang.mk:871: recipe for target '/root/emqx-rel/deps/emqx_rule_engine' failed
make: *** [/root/emqx-rel/deps/emqx_rule_engine] Error 128
```

**Comment by Gilbert-Wong** [comment]
Sorry, @s4kibs4mi , after discussion of our team, this repo has been made private. I suggest you to remove the emqx-rule-engine from the makefile.

**Comment by s4kibs4mi** [comment]
Ah, okay. Thanks @Gilbert-Wong

**Comment by Gilbert-Wong** [comment]
@s4kibs4mi, it is awkward to tell you that after discussion this morning, we decide to open source emqx-rule-engine again.

**Comment by s4kibs4mi** [comment]
Awesome man @Gilbert-Wong
