### ISSUE TITLE
Elixir based plugin is being skipped

### ISSUE THREAD

**Issue by s4kibs4mi** [emqx/emqx#2375]
#### Environment

- OS: ubuntu
- Erlang/OTP: 21
- EMQ: v3.1-beta.3

#### Description
Previous elixir based plugin is not working emqx version v3.1-beta.3. plugin is being built correctly but missing in release.

**Comment by Gilbert-Wong** [comment]
Hi, @s4kibs4mi ,could you please give a more detailed description, I do not understand what you mean from your description.

**Comment by s4kibs4mi** [comment]
@Gilbert-Wong So I have a emqx plugin written in Elixir following emqx_elixir_plugin guide line. In recent update of emqx it's not working. When I built emqx, plugin was being built correctly with other dependencies but when running emqx seems it's not being added in runtime.

**Comment by s4kibs4mi** [comment]
@Gilbert-Wong any update ?

**Comment by s4kibs4mi** [comment]
@Gilbert-Wong @terry-xiaoyu

**Comment by phanimahesh** [comment]
What was the last version where you have tested that it is working properly? Unfortunately there have been some internal changes that affect plugins recently.

What does the plugin do? Authentication, ACL, or hooking into events? Or is it something else?

**Comment by s4kibs4mi** [comment]
@phanimahesh thanks for your concern, last worked version is `v3.0.1`. The plugin uses both ACL, Auth mod and Hooks. The plugin is not even being shown in plugin list in dashboard. **I have noticed that mods are converted to hooks in recent release and I made changes accordingly at my plugin end**.

**Comment by HJianBo** [comment]
Hi, @s4kibs4mi Have you resolved this problem?

**Comment by s4kibs4mi** [comment]
@HJianBo no.

**Comment by s4kibs4mi** [comment]
@HJianBo Can you please check if elixir sample project works with the latest version?

**Comment by HJianBo** [comment]
Hi, @s4kibs4mi I have adapted the elixir plugin template to EMQ X v3.1.rc.1.  Hope help to you!

Please review https://github.com/emqx/emqx-elixir-plugin/pull/14

**Comment by s4kibs4mi** [comment]
@HJianBo Thank you. I am checking, will update you accordingly.

**Comment by s4kibs4mi** [comment]
@HJianBo I am not sure how did you adopt it. It's not working for me. Even I have tried  emqx_elixir_plugin but no luck.

**Comment by s4kibs4mi** [comment]
@HJianBo it's working. Thank you.

**Comment by pewh** [comment]
Hi @s4kibs4mi, how do you resolve the issue?

**Comment by s4kibs4mi** [comment]
@pewh followed @HJianBo's procedure and made some tweaking in Makefile to satisfy my requirements.
