### ISSUE TITLE
Mongodb authentication

### ISSUE THREAD

**Issue by jamesbonddd** [emqx/emqx#2379]
#### Environment
- OS: debian-stretch
#### Description
Hello, 
I'm enable to authenticate new clients to the broker using just the mongodb plugin, i've used the default configs and inserted a new user with just the username and password fields:
{ username: "a_user_name", password: "the_sha_256_hash_of_a_password"}
Then i disabled the allow_anonymous login.
when i tried to connect using the username and password, i can see the broker making database requests but i couldnt get authenticated
plugin configs: emqx_auth_mongo.conf:

auth.mongo.type = single
auth.mongo.server = 127.0.0.1:27017
auth.mongo.pool = 8
auth.mongo.database = mqtt
auth.mongo.topology.pool_size = 1
auth.mongo.topology.max_overflow = 0
auth.mongo.auth_query.collection = mqtt_user
auth.mongo.auth_query.password_field = password
auth.mongo.auth_query.password_hash = sha256
auth.mongo.auth_query.selector = username=%u
auth.mongo.super_query = on
auth.mongo.super_query.collection = mqtt_user
auth.mongo.super_query.super_field = is_superuser
auth.mongo.super_query.selector = username=%u
auth.mongo.acl_query = off
auth.mongo.acl_query.collection = mqtt_acl
auth.mongo.acl_query.selector = username=%u

Mongodb collection:
> db.mqtt_user.find().pretty()
{
        "_id" : ObjectId("5c9c94d03d574aed670d2e08"),
        "username" : "test",
        "password" : "56018FE135C84CB3AF995473A79669E46D0A02B12B8B3141ABA2D2AD19D66F70"
}
> db
mqtt

**Comment by jamesbonddd** [comment]
I finally got the problem, i have set the password_hash to plain text
auth.mongo.auth_query.password_hash = pain
then i tried it again without hashing the password and it worked, turns out the tool that i used for sha256 hash generation was outputting the wrong hash, so i tried another online tool for sha256 generation and it worked.
Maybe i will do a tutorial showing a concrete example on how this works although i still don't understand the concept of super query.

**Comment by Gilbert-Wong** [comment]
Appreciate that your solve your issue by yourself 👍
