### ISSUE TITLE
Messages lost in when using emqx-emqx bridge

### ISSUE THREAD

**Issue by anishmashankar** [emqx/emqx#2383]
#### Environment

- OS: Mac OSx
- Erlang/OTP: Packaged with Docker
- EMQ: 3.0.1

#### Description

I was simulating some failure scenarios when using bridges between brokers belonging to different networks. To simulate the failures on the docker networks, I used: pumba (https://github.com/alexei-led/pumba)
I have attached a zip folder containing the code I used to test and docker-compose files for provisioning the emqx cluster, the bridge node, and nginx proxy.
To summarize, this is the topology I set up in docker-compose:

```d
                                          ______ emqx-1
                                          |
producer ----> emqx-bridge ----> nginx ---|
                                   |      |______ emqx-2
                                   |
                                   |
                                   v
                                consumer
```
The producer is publishing messages to the bridge with QoS=1.
The consumer is consuming messages from nginx with QoS=1.

Run docker compose:
```sh
$ docker-compose -f docker-compose-infra.yml up -d
```
Start consumer:
```sh
$ python consumer.py
```
Start producer:
```sh
$ python producer.py
```
Initially, the pipeline works great. Messages get published on the bridge, and get replicated on the mounted point of the emqx cluster behind nginx.
However, when I introduces an abrupt disconnection, i.e.
```sh
$ pumba kill emqx-1 # can also be emqx-2 depending on where producer is connected
$ pumba kill emqx-2
```
### Scenario 1
So, the cluster is down and nobody can connect to it. That's alright. Then, I start the emqx-1 node:
```
$ docker start emqx-1
```
**The node doesn't start up at all** and throws docker logs like:
```
emqx-1         | Root: /opt/emqx
emqx-1         | /opt/emqx
emqx-1         | Starting emqx on node emqx@emqx.one
emqx-1         | ['2019-03-29T02:08:11Z']:waiting emqx
emqx-1         | ['2019-03-29T02:08:12Z']:waiting emqx
emqx-1         | ['2019-03-29T02:08:14Z']:waiting emqx
emqx-1         | ['2019-03-29T02:08:15Z']:waiting emqx
emqx-1         | ['2019-03-29T02:08:17Z']:waiting emqx
emqx-1         | ['2019-03-29T02:08:19Z']:waiting emqx
emqx-1         | ['2019-03-29T02:08:19Z']:timeout error
emqx-1 exited with code 1
```
## Scenario 2
If I immediately start emqx-2 after emqx-1, the cluster starts up correctly.
When the cluster is back up I observe that a ton of messages pushed to the bridge broker did not show up on the consumer. Only the messages published after successful formation of cluster showed up on the consumer.
As the messages published from bridge to cluster are done by a client with QoS 1, I expect that there wouldn't be such loss of data even if the cluster was down for some time. 

### Scenario 2.1
```
publisher----|            ___ emqx-1
             |---nginx---|
consumer-----|           |___ emqx-2 
```
In this case, I connected the producer and the consumer both to the nginx proxy. However, after taking the cluster down and bringing it back up, I observe data loss. But, I thought this could be related to the client library as I did not get receipt messages on any broker.

Test setup:
[emqx-test-cluster.zip](https://github.com/emqx/emqx/files/3021057/emqx-test-cluster.zip)

I could be missing some important configuration options in the bridging stanza.
Please let me know if I am doing something wrong.

**Comment by Gilbert-Wong** [comment]
We have done a large refactor for bridge functions before the emqx 3.1 release. Welcome to try the latest emqx.

**Comment by turtleDeng** [comment]
Thanks for using, emqx4.0 optimizes message bridging
https://www.emqx.io/downloads#broker
