### ISSUE TITLE
Need to delete "cluster remove" from the en doc for 3.0

### ISSUE THREAD

**Issue by jinrm** [emqx/emqx#2384]
#### Environment

- OS: 
- Erlang/OTP: 
- EMQ: 

#### Description

*A description of the issue*

Update  cluster.rst under https://github.com/emqx/emqx-docs-en/, and delete the description related to "cluster remove".

**Comment by HJianBo** [comment]
Maybe, we need to update the English documentation for EMQ X v3.0+ as soon as possible!
