### ISSUE TITLE
emq_auth_mysql error

### ISSUE THREAD

**Issue by FanMLei** [emqx/emqx#2392]
#### Environment

- OS: ubuntu16.04
- Erlang/OTP: R20/9.0
- EMQ: emqttd 2.3.11

#### Description
When I use MySQL authentication, most of the time it is normal. At some point, I found that if the username and password are entered casually, I can still connect successfully. If the correct username and password are wrong, the connection will fail. I have closed the anonymous connection. Function, what is the cause of this? Every time this happens, I need to restart the service to reconfigure.

**Comment by Gilbert-Wong** [comment]
Hi, @FanMLei , Could you please give a more detailed description ? I don't understand this sentence: `if the username and password are entered casually, I can still connect successfully.` Maybe the username and password entered casually are correct. I need more info. Please.

**Comment by FanMLei** [comment]
I checked the database, only two messages
![image](https://user-images.githubusercontent.com/19201217/55345119-bbfff780-54e1-11e9-9582-19d625f736fb.png)
Now I enter a username and password like this,connection succeeded
![image](https://user-images.githubusercontent.com/19201217/55345249-03868380-54e2-11e9-8896-00870ad731a5.png)
If I enter a correct username and wrong password,connection failed
![image](https://user-images.githubusercontent.com/19201217/55345602-e1d9cc00-54e2-11e9-8d51-da09bb00c23c.png)
Finally use the correct username and password,connection succeeded
![image](https://user-images.githubusercontent.com/19201217/55345748-439a3600-54e3-11e9-8585-e67822e8b386.png)
auth.mysql.auth_query:
```sql
select token as password from device where did = '%u' limit 1
```
I don't know if this can be said clearly.

**Comment by Gilbert-Wong** [comment]
Sorry, @FanMLei . From your screenshot, I cannot conclude enough information. How many auth plugins did you enabled and how do you config your `etc/*.configs`, and could you please give me log files?

**Comment by HJianBo** [comment]
Hi, @FanMLei These three results is be expected for EMQ Authentication mechanism.

So it works very well. What was it that confused you？

**Comment by turtleDeng** [comment]
We will close this issue and you can reopen if there are any problems.
