### ISSUE TITLE
mosquitto bridge emqtt, subscriber get duplicated msg

### ISSUE THREAD

**Issue by bailin520** [emqx/emqx#2394]
#### Environment

- OS: 
- Erlang/OTP: 
- EMQ: 

#### Description

*A description of the issue*

**Comment by zhengyupan** [comment]
Hi @bailin520 would you please describe your issue with more details?

**Comment by bailin520** [comment]
Hi @zhengyupan I use the mosquitto1.4-1.5 server to bridge to the emqttd server, then use the mqttfx tool to subscribe to a topic: "test"and open other a mqttfx tool to send toppic: "test", finally， found that there are 2 messages in the subscription. But using mosquitto as a server does not have this problem.
Thanks for much!

**Comment by Gilbert-Wong** [comment]
So @bailin520 , can you please tell us the emqx version you use ?

**Comment by Gilbert-Wong** [comment]
If the QoS level is 1, subscribers probably subscribers would get duplicated messages.

**Comment by turtleDeng** [comment]
Thank you for your participation, we will close this issue, if there are any problems, you can reopen.
