### ISSUE TITLE
Clients with the same IP will frequently disconnect when they exceed 200.

### ISSUE THREAD

**Issue by GoldLinPan** [emqx/emqx#2396]
#### Environment

- OS: Windows server 2008 R2
- Erlang/OTP: 19
- EMQ:  2.3.11

#### Description
If there are more than 200 clients with the same Ip connected the broker and each of them pub/sub with a different topic in an endless loop, a large number of them will disconnect after few seconds.  If spreading these clients over different Ip, they all work fine.  An IP should theoretically support 60000+ clients, but in fact, more than 200 will be disconnected frequently. What causes this calm? 
*A description of the issue*

**Comment by Gilbert-Wong** [comment]
Hi, @pantongren .First, if you use emqx 2.3.11, I suggest you to build emqx with erlang 20. Then according to what you said, `if there are more than 200 clients with the same IP connected the broker and each of them pub/sub with a different topic in an endless loop`, it should be impossible, we always do pressure test for emqx with same IP. But the environment we use is linux. I don't know if the os/env is the main factor cause your problem. Could you please give me your log file ? I need more info to dig into your problem.

**Comment by pantongren** [comment]
@Gilbert-Wong thank you, I mean start 200 clients at the same time. Every client has its own topic both for publish and subscribe. Each of them publishes a message every 1 second and never stop. When clients exceed 200, the broker didn't crash but a large number of clients throw connection time out.  No logs are generated in this case.  are there any limits? or how to modify the configuration file of emq?

**Comment by zhengyupan** [comment]
@pantongren I also have the feeling that  this issue is related to network setup or OS. Sometimes a firewall or security rules can prevent access too. Please redo your test and check the system log or event log when the clients start to drop.

**Comment by pantongren** [comment]
@zhengyupan  Yes, it's probably caused by network,   thanks.
