### ISSUE TITLE
How to configure the SSL Ony-way authentication

### ISSUE THREAD

**Issue by qiufengwu** [emqx/emqx#2397]
#### Environment

- OS:  ubuntu 16.04
- Erlang/OTP: 
- EMQ:  3.0.1

#### Description

照着文档配置：

```
## SSL Options
## listener.ssl.external.tls_versions = tlsv1.2,tlsv1.1,tlsv1
listener.ssl.external.handshake_timeout = 15s
listener.ssl.external.keyfile = etc/certs/key.pem
listener.ssl.external.certfile = etc/certs/cert.pem
## 开启双向认证
## listener.ssl.external.cacertfile = etc/certs/cacert.pem
## listener.ssl.external.dhfile = etc/certs/dh-params.pem
## listener.ssl.external.verify = verify_peer
## listener.ssl.external.fail_if_no_peer_cert = true
```
listener.ssl.external.cacertfile 按照文档是注释掉的，
在使用java client连接时报错：unable to find valid certification path to requested target
把listener.ssl.external.cacertfile上的注释去掉就好了

不用双向认证时listener.ssl.external.cacertfile 为啥要注释掉，有什么特殊原因要求必须这么做吗，打开注释会有什么问题？
如果必须要注释掉，那注释掉之后client该怎么操作？总不能每新接一个client就把证书手动加到client的信任列表里吧，那样的话就有点坑了啊
还是说我的配置或用法是有问题的，那正确的应该怎么配置？

**Comment by Gilbert-Wong** [comment]
Hi, @qiufengwu , Please open issue with English and @linjunjj will help answer your question.

**Comment by linjunjj** [comment]
Hi @qiufengwu  If you want unidirectional authentication to connect, you must comment out `listener.ssl.external.cacertfile`

**Comment by HJianBo** [comment]
@qiufengwu Do you have resolved this problem?

In my view, If you want to use One-way authentication over MQTT SSL, you just keep the `listener.ssl.external` section options to default. Then the client should connect to 8883, it will be work very well.

**Comment by qiufengwu** [comment]
@Gilbert-Wong 抱歉，英文太差，只会看，不会说，没法把我的问题翻译成英文，见谅。

@linjunjj @HJianBo 谢谢你们的回答，但还是没能解决我的疑惑，可能是我描述得不够清晰，我再重新描述下我的问题：

我按照默认配置（就是前面我贴出来的配置）启动时，通过ssl 8883建立连接始终报错：unable to find valid certification path to requested target，

当然，如果我按照你们的client示例文档http://www.emqtt.com/clients#java里说的：

```
加入JDK证书信任，jdk1.8.0_121\jre\lib\security目录下运行命令：
keytool -import -alias cacert -keystore cacerts -file 盘:目录/cacert.crt
```

这样的确就能正常工作的，但这种方式我觉得在生产环境用不太合理吧？那样岂不是所有的client在接入进来之前都要把证书导进JDK的信任列表？有的client甚至不是java写的，每种类型的都要搞一遍相应的操作就太麻烦了。另外，要是证书过期了，还得每个client都更换一遍，如果client数量非常多，那岂不是要累死了？

我的证书是通过正规渠道申请购买的，不是自己用openssl生成的，按理说按照证书链往上追溯是能找到受信的根证书才对的啊

后来我看到`## listener.ssl.external.cacertfile = etc/certs/cacert.pem`这个配置项，虽然没有深究它是干嘛的，只是把前面的注释去掉，然后把手工导入JDK信任列表的证书移除后，居然就不会报错了。所以我猜测是不是跟这个配置有关，但看文档里明确写了这个配置项是给双向认证用的，所以才有此疑问

**Comment by HJianBo** [comment]
Hi, @qiufengwu  Sorry too late reply there. Is the problem solved? If not, you can find me with WeChat Id *Lo_Alone*, which is better for solving the problem quickly.

If it is a bug of EMQ X, I'll open a new issue with explicit description!

Close it first. Close it first. Plz reopen it if has any question there.
