### ISSUE TITLE
SQL ACL not ordered

### ISSUE THREAD

**Issue by jbrzozoski** [emqx/emqx#2403]
#### Environment

- OS: CentOS Linux release 7.6.1810 (Core)
- Erlang/OTP: erts-10.2.1
- EMQ: v3.0.1

#### Description

When using the emqx-auth-mysql plugin for ACL (and probably other RDBS as well), the ACL matching algorithm in Erlang stops on the first row with a matching topic, but there is no guarantee on the order of rows returned by MySQL:

https://stackoverflow.com/questions/8746519/sql-what-is-the-default-order-by-of-queries

You probably want an ORDER BY in your example SQL query before someone runs into a bug on a complex ACL list in the database.

**Comment by HJianBo** [comment]
Hi, @jbrzozoski This is bad experience actually. It is necessary to show the importance of the ACL match, We'll improve this after daily discussion.

But now, you can add the `ORDER BY` section to the `acl_query` SQL to fix it. i.e:
```
auth.mysql.acl_query = select allow, ipaddr, username, clientid, access, topic from mqtt_acl where ipaddr = '%a' or username = '%u' or username = '$all' or clientid = '%c' order by <a_order_property>
```

**Comment by HJianBo** [comment]
Hi, @jbrzozoski  I have updated all document for it. Thanks for your feedback!

Close it first, plz reopen it if has any question there.
