### ISSUE TITLE
Unable to edit config files with Web editor

### ISSUE THREAD

**Issue by bkrajendra** [emqx/emqx#2404]
#### Environment

- OS: CentOS 7
- Erlang/OTP: R21/10.2.1
- EMQ: v3.1-beta.1

#### Description

Ive a web editor installed on my server to brows files from server. wheneven i try to edit file through it and save i get parse error and there is no way to get it back.
```
2019-04-07T09:57:42.236134+05:30 [error] Syntax error in /var/lib/emqx/configs/app.2019.04.07.09.57.40.conf after line 2559 column 1, parsing incomplete

```
What can be done ?
I tried editing  a auth plugin conf file or any other file i always stuck.

**Comment by phanimahesh** [comment]
We can not know what's wrong without atleast looking at the files. Most likely, your web editor is messing things up, or you are making some errors in editing.

Either way, I doubt there's anything we can do about it. You can try diffing the good version and the bad version to see what's going wrong and investigate further from there.

**Comment by bkrajendra** [comment]
I understand the info given is very less. But the issue is only that even if I save file without making any changes still it starts giving these errors. SO I wanted to understand what wrong could be going while a web editor is saving files to disc. when i make changes through nano it works properly.
Im using CentOS 7 and a CentOS Web Panel as my server manager for web servers. They have these file editor provided for editing file and I find it easy to edit conf file through my web interface.

**Comment by phanimahesh** [comment]
Then it definitely is an issue in your web editor. I'm not sure what we can do about this here.

Please try diffing the files to see if something extraneous is being introduced. That might help.

@Gilbert-Wong I vote to close this issue since it is out of scope for us.

**Comment by Gilbert-Wong** [comment]
From your statement, I suppose something wrong happens on your web editor.

**Comment by Gilbert-Wong** [comment]
Yes.

**Comment by bkrajendra** [comment]
Ok thanks @Gilbert-Wong  and @phanimahesh for quick response. I'll look into my web editor for whats wrong happening. But it will be very nice if all of the config file can be edited from EMQX web interface, specially main emqx.conf file is very long and its really tiresome to edit it through nano or vim.

If we can have something like all options editable through config forms, just like some plugins have it.

**Comment by Gilbert-Wong** [comment]
@bkrajendra , Can't agree more, we have plan to introduce toml as configuration language of emqx, it would simplify the emqx config.
