### ISSUE TITLE
Is there a plugin to get the status of EMQ and we get the less disconnect status if a lot of devices disconnect at once

### ISSUE THREAD

**Issue by lanliseve** [emqx/emqx#2407]
#### Environment

- OS:  Centos 7
- Erlang/OTP: 9.3
- EMQ: 2.3.11

#### Description
1. we create some devices to subscribe the sys topic get the message of online/offline. About ten thousands device connect to EMQ and keep the status. Now, the instance is down .We can't get any status of those devices.
2. If we  subscribe the sys topic get the message of online/offline, we can't get all the disconnect status if a lot of devices lost connection at once.

*A description of the issue*

**Comment by zhengyupan** [comment]
@lanliseve thank you for feedback.
1. If the instance is down, then all connection to this instance is disconnected. 
2. can you give more detials about it? Like how many disconnects you are talking about, the hardware you are using, etc.

**Comment by lanliseve** [comment]
with 2, we use the docker to run the emq instance with 2 core and 2G memory. About ten thousands connection connected the emq.

**Comment by zhengyupan** [comment]
@lanliseve Can you try it on a more powerful hardware and see if you can get all disconnections?

**Comment by lanliseve** [comment]
I will move it on a more powerful hardware and test again
