### ISSUE TITLE
after use error plugins conf must restart emq

### ISSUE THREAD

**Issue by Eluso** [emqx/emqx#2409]
#### Environment

- OS: ubuntu18.04
- Erlang/OTP: 
- EMQ: emqx v3.1-rc.1

#### Description

*A description of the issue*
1.Use error emqx_auth_mysql.conf,do `emqx_ctl plugins load emqx_auth_mysql` respone failed.
2.Change emqx_auth_mysql.conf,do `emqx_ctl plugins load emqx_auth_mysql` response failed.
3.restart emqx.
4.load plugin,respone success.

**Comment by Gilbert-Wong** [comment]
The second step, you should execute `emqx_ctl plugins reload emqx_auth_mysql` to enable plugin.

**Comment by HJianBo** [comment]
Maybe we need the more explicit document to describe what's these commands difference?
