### ISSUE TITLE
Make fails on Ubuntu 16.04

### ISSUE THREAD

**Issue by johnfwhitmore** [emqx/emqx#2411]
Just cloned this repo as I'm hitting an error with the pre-built binary.

Running Ubuntu 16.04
erlang   1:21.3.3-1
Erlang/OTP 21 [erts-10.3.2] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1]
Eshell V10.3.2  (abort with ^G)

When I try to make I get and error, following the instructions in the readme file.

~/emqx$ make
make[1]: Entering directory '/home/jwhitmore/emqx/deps/cuttlefish'
./rebar get-deps
==> getopt (get-deps)
==> neotoma (get-deps)
==> cuttlefish (get-deps)
./rebar compile
==> getopt (compile)
==> neotoma (compile)
==> cuttlefish (compile)
./rebar skip_deps=true escriptize
==> cuttlefish (escriptize)
make[1]: Leaving directory '/home/jwhitmore/emqx/deps/cuttlefish'
Error: No Makefile to build dependency /home/jwhitmore/emqx/deps/jsx.
erlang.mk:339: recipe for target 'deps' failed

**Comment by johnfwhitmore** [comment]
Found a solution:

https://github.com/emqx/emqx/issues/2202

But perhaps the readme file should be updated?

**Comment by johnfwhitmore** [comment]
Having gotten the code building the instructions in the readme - "cd _rel/emqx && ./bin/emqx console"

There's no such directory created so again instructions may need updating

**Comment by HJianBo** [comment]
Hi, @johnfwhitmore If you want to get executable *EMQ X Broker* by source, you should clone [emqx-rel](https://github.com/emqx/emqx-rel) and compile it, not the emqx repos.

**Comment by johnfwhitmore** [comment]
Thank you for your response. I went down that route and that ended with an error:

:~/emqx-rel$ bin/emqx console
vm.args needs to have a -name parameter.
  -sname is not supported.

Been searching for that "-name" error but it seems like it dates back to 2017:

https://github.com/emqx/emqx/issues/866

**Comment by HJianBo** [comment]
You must compile it first:
```shell
cd emqx-rel
make
```

Then run it with following commands:
```shell
cd _rel/emqx && ./bin/emqx console
```

Not execute `./bin/emqx console` directly in the emqx-rel directory

**Comment by johnfwhitmore** [comment]
Yes! Sorry '_rel' makes a huge difference. Thanks for your help

**Comment by johnfwhitmore** [comment]
This is all a bid to find out why emqx ver 3 disconnects the clients when V2 never did
