### ISSUE TITLE
How to system install from github version?

### ISSUE THREAD

**Issue by johnfwhitmore** [emqx/emqx#2413]
#### Environment

- OS: Ubuntu 16.04
- Erlang/OTP:  21
- EMQ: git clone https://github.com/emqx/emqx-rel.git

I have been installing the binary package emqx-ubuntu16.04-v3.1-beta.3_amd64.deb on a server but that has been repeatedly disconnecting the connection on publishing data. I was getting an Erlang stack trace in the log files, so installed from source (git clone https://github.com/emqx/emqx-rel.git) to have access to the source to be able to look at the files listed in the stack trace to see what the problem was.

However that install from github has resolved the issue, early days but so far so good. 

So the question now is how to I install emqx as a system utility from github so that there's a systemd service file, and emqx pulls its configuration from /etc/emqx/emqx.conf?

I can create my own service file but I'm not sure how to configure where emqx reads its configuration from?

**Comment by zhanghongtong** [comment]
You can check [emqx-packages](https://github.com/emqx/emqx-packages), this should help you.

**Comment by johnfwhitmore** [comment]
That repo has faults

Can't call method "as_string" on an undefined value at /usr/share/perl5/Dpkg/Changelog.pm line 249.                   │(emqx@127.0.0.1)1>
Makefile:19: recipe for target 'all' failed                                                                           │(emqx@127.0.0.1)1>
make: *** [all] Error 255

I'll try find a solution

**Comment by johnfwhitmore** [comment]
Changed makefile to not use /tmp
