### ISSUE TITLE
Can not send ACL and AUTH request (but superuser can)

### ISSUE THREAD

**Issue by fsfnt041** [emqx/emqx#2415]
官网下的CENTOS7 v3.1-rc1使用时HTTP授权插件时    ACLAUTH请求发不出去(user,superuser校验可以)，是要修改什么配置文件么？

**Comment by zhengyupan** [comment]
Hi @fsfnt041 ,
You will need to config the followings to make the ACL work:
auth.http.acl_req
auth.http.acl_req.method
auth.http.acl_req.params

**Comment by Gilbert-Wong** [comment]
Hi, @fsfnt041. Super user would not send acl request.

**Comment by fsfnt041** [comment]
@Gilbert-Wong  Thanks
