### ISSUE TITLE
[error] Supervisor 'esockd_connection_sup

### ISSUE THREAD

**Issue by Jojojoseph1994** [emqx/emqx#2417]
#### Environment

- OS: 
- Erlang/OTP: 
- EMQ: 

#### Description

*A description of the issue*
Hi, I am getting this error while publishing using mosquitto, I am new to emqx please help me.
I'm getting this error log

06:56:05.484 [error] Supervisor 'esockd_connection_sup - <0.1591.0>' had child connection started with emqx_connection:start_link([{max_conn_rate,1000},{zone,external}]) at <0.1868.0> exit with reason 135 in context connection_shutdown

**Comment by Gilbert-Wong** [comment]
Hi, @Jojojoseph1994, which emqx version do you use? And please give me more detailed logs.

**Comment by Jojojoseph1994** [comment]
@Gilbert-Wong,  I got the solution. Thank you for you response.

**Comment by Gilbert-Wong** [comment]
Can you tell me the solution you got if you don't mind it ? @Jojojoseph1994

**Comment by Jojojoseph1994** [comment]
Hi @Gilbert-Wong , I'm using http auth plugin. i made a mistake in super request side. i used post method there, but i my case, need to use get method there. thats it.
Thank you
