### ISSUE TITLE
Metrics like 'messages/qos2/dropped'  are not updated

### ISSUE THREAD

**Issue by tigercl** [emqx/emqx#2418]
#### Environment

- OS: macOS 10.13.6
- Erlang/OTP: 21
- EMQ: 3.1-rc.1

#### Description

Metrics like 'messages/qos2/dropped' will not be updated after the session is terminated.

**Comment by turtleDeng** [comment]
This bug has been fixed in emqx3.1-rc.2. Please try with the latest emqx release.
