### ISSUE TITLE
Building emqx and emqx_ctl from source project?

### ISSUE THREAD

**Issue by johnfwhitmore** [emqx/emqx#2419]
#### Environment

- OS: Uubntu 16.04
- Erlang/OTP: 21
- EMQ: source

#### Description

I'd like to make minor changes to the source code of the project to change the logging output from process. That means making minor changes to the emqx repo, which I can make from my own fork of the project. But performing a make on the project does not make the executable utilities 'emqx' and 'emqx_ctl'

The emqx-packages  repo does package up these executables but only from the emqx-rel repo so not from source. So how do I get from source to those two executables?

**Comment by johnfwhitmore** [comment]
I should add that perhaps I can run emqx from the erlang files produced from a 'make' in the 'emqx' repo clone directory, but I'm new to Erlang. If I can simply run from source build let me know and I'll just run that.

**Comment by HJianBo** [comment]
Just follow these commands to get executable broker:
```
git clone https://github.com/emqx/emqx-rel

cd emqx-rel

make
```

**Comment by johnfwhitmore** [comment]
You misunderstood me. If I make a change to source code of the project
building emqx-rel does not build that change into an executable.

So changing a source code line how do you include that in a build?

**Comment by johnfwhitmore** [comment]
Think I can edit emqx-rel Makefile to pull from my repo rather then the official. That might get me working.

**Comment by johnfwhitmore** [comment]
Still struggling with this. Have edited the source code in emqx-rel/deps/emqx and built the code.
Then copied the resulting execs from emqx-res/bin over the system installed versions in /usr/lib/emqx/bin

Trying now to execute 'emqx start' results in an error:

# emqx start
vm.args needs to have a -name parameter.
  -sname is not supported.


I'll go chasing that error.

**Comment by johnfwhitmore** [comment]
I can execute  '_rel/bin/emqx console' but I have no idea where that is logging to, certainly not /var/log/emqx

**Comment by johnfwhitmore** [comment]
OK Every time I execute emqx console an brand new config file is generated so I can't edit any configuration and change the logging level. Which was why I wanted to edit this code, to change logging info messages

**Comment by johnfwhitmore** [comment]
A lot of messing actually edit code and execute it but finally got it

**Comment by HJianBo** [comment]
Hi, @johnfwhitmore  Thanks so enthusiastic for this. After compiling successfully you can execute `_rel/emqx/bin/emqx console` to start  EMQ X in the front ground. And the logs directory is  `_rel/emqx/log/`

If you want to change the log level, there are two ways to do it:
1. Change the default log level in the `_rel/emqx/etc/emqx.conf`
    ```
    log.level = error
    ```
2. Or, using CLI commands `_rel/emqx/bin/emqx_ctl  log`
    ```
     _rel/emqx/bin/emqx_ctl  log set-level debug
    ```

About the more guides, you can see it: https://developer.emqx.io/docs/emq/v3/en

**Comment by HJianBo** [comment]
Hi, @johnfwhitmore Is the problem has been resolved?

**Comment by johnfwhitmore** [comment]
No I don't think it is, but I don't think the emqx organisation wants people to make changes to the code. Whilst the code is available here on github it's very difficult to clone emqx/emqx, make a change and bundle the change so that it can be deployed to a server for use.

So if I make a change to logging in emqx/emqx to actually build the code I'm pointed to the emqx/emqx-rel project which will build all the various parts that make up the full emqx deployment. That's great but that project emqx/emqx-rel will ignore any changes I have made and instead checkout a released version of the code from github rather then building my fork of the project with local changes.

Further to that if I want to package up the various parts to a local clone of emqx/emqx-rel you are pointed to another project emqx/emqx-packages. That project is brilliant, but again is written so that it ignores anything you've done locally and instead checks out a fresh version of emqx/emqx-rel from github to a temporary location in the file system, then emqx/emqx-rel clones from github all the sub projects and builds those in a temporary location. Local changes are the last thing you will ever be able to build into a deployable medium. 

I have a fork of emqx/emqx I can look at the code, change it, make it but execution of that code, with changes is a mammoth task. Maybe it's an Erlang thing ;)

**Comment by HJianBo** [comment]
Hi, @johnfwhitmore Sorry so late reply there.

> I have a fork of emqx/emqx I can look at the code, change it, make it but execution of that code, with changes is a mammoth task. Maybe it's an Erlang thing ;)

Yes, If you want to modify any others dependency of *emqx-rel* and release it, You should fork it and change the `Makefile` and `relx.config` of emqx-rel to point your repository. Then delete the `deps` directory and compile it again.

**Comment by johnfwhitmore** [comment]
Hadn't realised the significance of relx.config. I'll have a look into that, and see if I can't stream line the process.

I'm trying to make minor changes to emqx but leave all the other dependencies as they are.

Thanks a million for your help.
