### ISSUE TITLE
Something wrong with the online documentation

### ISSUE THREAD

**Issue by xyz361** [emqx/emqx#2424]
#### Environment

- OS: 
- Erlang/OTP: 
- EMQ: 

#### Description

https://developer.emqx.io/docs/emq/v3/cn/getstarted.html?highlight=emq%20conf#erlang

Is there a problem with "emqttd/etc/emq.conf"  ?

And I can't find "listener.tcp.external.max_clients" , just find "listener.tcp.external.max_connections" .

**Comment by xyz361** [comment]
In the next chapters I saw some place where the broker's name is  "emqtt" .

**Comment by HJianBo** [comment]
Hi, @xyz361  I'll fix later

**Comment by xyz361** [comment]
Tks @HJianBo

**Comment by HJianBo** [comment]
Hi, @xyz361  I have updated this, you can review it at https://github.com/emqx/emqx-docs-cn/pull/118
