### ISSUE TITLE
Fatal error: unexpected message and bad record mac and certificate unknown

### ISSUE THREAD

**Issue by dovedong** [emqx/emqx#2425]
#### Environment

- OS: centos7
- Erlang/OTP: 
- EMQ: 2.3.9

#### Description

My cluster has five machines（use MQTT/SSL 8883） and each of them has the follow problem.

 =ERROR REPORT====
SSL: {connection,{alert,2,20,{"ssl_cipher.erl",300},decryption_failed}}: ssl_connection.erl:845:Fatal error: unexpected message
2019-04-07 23:25:50 =SUPERVISOR REPORT====
     Supervisor: 'esockd_connection_sup - <0.1540.0>'
     Context:    connection_shutdown
     Reason:     {tls_alert,"unexpected message"}
     Offender:   [{pid,<0.14512.3204>},{name,connection},{mfargs,{emqttd_client,start_link,[[{max_publish_rate,0},{client_idle_timeout,30000},{client_enable_stats,false},{max_clientid_len,1024},{max_packet_size,65536},{keepalive_backoff,0.75}]]}}]

=ERROR REPORT====
SSL: connection: ssl_alert.erl:88:Fatal error: bad record mac
2019-04-09 04:07:56 =SUPERVISOR REPORT====
     Supervisor: 'esockd_connection_sup - <0.1540.0>'
     Context:    connection_shutdown
     Reason:     {tls_alert,"bad record mac"}
     Offender:   [{pid,<0.31106.5969>},{name,connection},{mfargs,{emqttd_client,start_link,[[{max_publish_rate,0},{client_idle_timeout,30000},{client_enable_stats,false},{max_clientid_len,1024},{max_packet_size,65536},{keepalive_backoff,0.75}]]}}]

=ERROR REPORT====
SSL: certify: ssl_alert.erl:88:Fatal error: certificate unknown

**Comment by HJianBo** [comment]
Hi, @dovedong Sorry too late reply.

Is the problem resolved now? Usually, the 8883 SSL services works well.  Can you provide more detail if the problem still exist
