### ISSUE TITLE
After publishing MQTT message via jmeter，the response data is null(jmeter version 5.0）

### ISSUE THREAD

**Issue by dofuntest** [emqx/emqx#2427]
*A description of the issue*

**Comment by Eluso** [comment]
![image](https://user-images.githubusercontent.com/20638270/56480271-ea269500-64eb-11e9-8dcd-0c5a29ce7e65.png)
In "MQTT Sub Sampler",Please choice Debug respone. If not solved,can your send JMeter script?
tks
