### ISSUE TITLE
Adding ACL rule using Rest API

### ISSUE THREAD

**Issue by Blacktoviche** [emqx/emqx#2431]
#### Environment

- OS: 
- Erlang/OTP: 
- EMQ: 

#### Description

*A description of the issue*

Is it possible to add new rule to acl.conf using Rest API 
I have been reading the whole documents in the website and here in issues 
Never see thing like this
Is it possible? without using db plugins 
I'm using emqx-auth-username

**Comment by zhengyupan** [comment]
@Blacktoviche Thanks for the advice, currently it is not possible to do it via API, we will discuss if we will implement in the future.

**Comment by mononym** [comment]
There are no plans to make the ACL rules in the configuration file amendable via an http api.

The core config file for ACL is the lowest priority and is overridden by other methods. The Mnesia ACL does have an API and given that it's Mnesia it means it is tightly integrated with the system.

If you need an ACL list configurable by an API we suggest you set up and use the Mnesia ACL feature.
