### ISSUE TITLE
Dependency mismanagement

### ISSUE THREAD

**Issue by s4kibs4mi** [emqx/emqx#2434]
#### Environment

- OS: any
- Erlang/OTP: any
- EMQ: v3.1-beta.3/any

#### Description

I have notified that emqx dependencies are tightly coupled. For example, I don't need any auth related plugins so I have removed them. And then emqx build process starts falling saying,
```
===> Failed to solve release:
 Dependency x is specified as a dependency but is not reachable by the system.
```
But then again when I add them the issue got solved. But it should work without these dependencies.

**Comment by phanimahesh** [comment]
When you add or remove a dependency, you should also edit relx.config to include/remove instructions for loading that dependency and all of its dependencies.

That is how relx works. It needs precise order in which each otp app is to be loaded and started, to build the release boot file.
