### ISSUE TITLE
Webhook cannot send will message when client closed

### ISSUE THREAD

**Issue by JackRanGitHub** [emqx/emqx#2435]
#### Environment

- OS: centos 6.8
- Erlang/OTP: 21
- EMQ: emqx 3.1

#### Description

I used websocket protocol to connect mqtt server, but I cannot receive will message by webhook plugins.I used mqtt.js 
code:
`var options = {
                clientId: '123456',
                will: {
                    topic: "clientWill",
                    payload: "aaaa",
                    retain: false,
                    qos: 0
                },
                clean: false
            }
            var client  = mqtt.connect(
                'ws://127.0.0.1:8083/mqtt',
                options
            )`
webhooks logs:
![image](https://user-images.githubusercontent.com/12415370/56102618-c057f600-5f60-11e9-8f0e-d4b1e3224acb.png)

When I use emqx3.0-rc1, I received the will message at last year.I don't know what cause. Can you help me?Thank you very much!

**Comment by Gilbert-Wong** [comment]
The will message strategy of emqx is that when session is terminated , the message would be published. And I have a question, did you enable the emqx_delayed_publish plugin ?

**Comment by JackRanGitHub** [comment]
I follow you idea do my test, but I still cannot receive will message by webhook plugins.
webhook logs:
![image](https://user-images.githubusercontent.com/12415370/56186313-9cc0a880-6051-11e9-93ec-75a0e8c4a44f.png)
plugins list:
![image](https://user-images.githubusercontent.com/12415370/56186376-ca0d5680-6051-11e9-83a8-0106869dea3a.png)
Can you help me?Thank you very much!

**Comment by tigercl** [comment]
Sorry for the late reply, I noticed that the reason in `session_terminated` is normal. I am not sure if you are disconnecting the client by DISCONNECT packet or other methods. It should be noted that the broker will not send will message if the broker receive a DISCONNECT packet (MQTT v3.1.1) or a DISCONNECT packet with a reason code 0 (MQTT v5).

**Comment by JackRanGitHub** [comment]
I closed web browser to disconnect the websocket connect, it should be a exception disconnect.Should I actively call the disconnection method and give it an error reason?

**Comment by mononym** [comment]
This appears to be the same issue as reported in #2274. The long and short of it is that closing the browser is not the same as a brutal kill of a connection. The browser and the client are likely disconnecting in a 'good' way and sending a proper disconnect signal which for a few versions would cause the message to not be sent.

This behavior changed in 3.2.
