### ISSUE TITLE
Generic server emqx_sm_locker terminating

### ISSUE THREAD

**Issue by kkang2** [emqx/emqx#2441]
#### Environment

- OS: CentOS Linux release 7.2.1511
- Erlang/OTP: Erlang/OTP 21 [erts-10.2.3]
- EMQ: emqx-3.0.1

#### Description

**Server is not work for a while with the following error.
How can I solve it?**

2019-04-14 15:06:56.217 [error] ** Generic server emqx_sm_locker terminating 
** Last message in was check_lease
** When Server state == {state,emqx_sm_locker,
                         {lease,15000,
                          {ok,
                           {interval,#Ref<0.4184905100.3699900430.216473>}}},
                         #{}}
** Reason for termination == 
** {badarg,[{ets,next,
                 [emqx_sm_locker,<<"488cff6d-8c05-4b8a-b9f7-f9e6d63918db">>],
                 []},
            {ekka_locker,check_lease,5,
                         [{file,"src/ekka_locker.erl"},{line,277}]},
            {ekka_locker,handle_info,2,
                         [{file,"src/ekka_locker.erl"},{line,237}]},
            {gen_server,try_dispatch,4,[{file,"gen_server.erl"},{line,637}]},
            {gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,711}]},
            {proc_lib,wake_up,3,[{file,"proc_lib.erl"},{line,259}]}]}
2019-04-14 15:06:56.220 [error] crasher:
    initial call: ekka_locker:init/1
    pid: <0.3499.0>
    registered_name: emqx_sm_locker
    exception error: bad argument
      in function  ets:next/2
         called as ets:next(emqx_sm_locker,
                            <<"488cff6d-8c05-4b8a-b9f7-f9e6d63918db">>)
      in call from ekka_locker:check_lease/5 (src/ekka_locker.erl, line 277)
      in call from ekka_locker:handle_info/2 (src/ekka_locker.erl, line 237)
      in call from gen_server:try_dispatch/4 (gen_server.erl, line 637)
      in call from gen_server:handle_msg/6 (gen_server.erl, line 711)
    ancestors: [emqx_sm_sup,emqx_sup,<0.3403.0>]
    message_queue_len: 0
    messages: []
    links: [<0.3498.0>,<0.1354.0>]
    dictionary: []
    trap_exit: false
    status: running
    heap_size: 6772
    stack_size: 27
    reductions: 3465207
  neighbours:
2019-04-14 15:06:56.223 [error] supervisor: {local,emqx_sm_sup}
    errorContext: child_terminated
    reason: {badarg,[{ets,next,
                          [emqx_sm_locker,
                           <<"488cff6d-8c05-4b8a-b9f7-f9e6d63918db">>],
                          []},
                     {ekka_locker,check_lease,5,
                                  [{file,"src/ekka_locker.erl"},{line,277}]},
                     {ekka_locker,handle_info,2,
                                  [{file,"src/ekka_locker.erl"},{line,237}]},
                     {gen_server,try_dispatch,4,
                                 [{file,"gen_server.erl"},{line,637}]},
                     {gen_server,handle_msg,6,
                                 [{file,"gen_server.erl"},{line,711}]},
                     {proc_lib,wake_up,3,[{file,"proc_lib.erl"},{line,259}]}]}
    offender: [{pid,<0.3499.0>},
               {id,locker},
               {mfargs,{emqx_sm_locker,start_link,[]}},
               {restart_type,permanent},
               {shutdown,5000},
               {child_type,worker}]
2019-04-14 15:06:56.791 [error] supervisor: 'esockd_connection_sup - <0.3512.0>'
    errorContext: connection_shutdown_error
    reason: normal
    offender: [{pid,[<0.10965.434>,<0.14436.432>]},
               {name,connection},
               {mfargs,{emqx_session,start_link,[]}}]
2019-04-14 15:06:56.806 [error] supervisor: 'esockd_connection_sup - <0.3621.0>'
    errorContext: connection_shutdown
    reason: {gen_server,call,
                [emqx_session_sup,
                 {start_session,
                     #{clean_start => true,
                       client_id => <<"f181bf73-98ad-468b-af87-d27371852c97">>,
                       conn_pid => <0.2125.436>,expiry_interval => 0,
                       max_inflight => 32,topic_alias_maximum => 0,
                       username => <<"tmapclient">>,will_msg => undefined,
                       zone => external}},
                 infinity]}
    offender: [{pid,<0.2125.436>},
               {name,connection},
               {mfargs,
                   {emqx_connection,start_link,
                       [[{active_n,100},{zone,external}]]}}]
2019-04-14 15:06:56.816 [error] supervisor: 'esockd_connection_sup - <0.3621.0>'
    errorContext: connection_shutdown
    reason: {gen_server,call,
                [emqx_session_sup,
                 {start_session,
                     #{clean_start => true,
                       client_id => <<"2004dc4d-bb17-4cd1-a926-a0e5631177dc">>,
                       conn_pid => <0.29023.434>,expiry_interval => 0,
                       max_inflight => 32,topic_alias_maximum => 0,
                       username => <<"tmapclient">>,will_msg => undefined,
                       zone => external}},
                 infinity]}
    offender: [{pid,<0.29023.434>},
               {name,connection},
               {mfargs,
                   {emqx_connection,start_link,
                       [[{active_n,100},{zone,external}]]}}]
2019-04-14 15:06:56.824 [error] [Stats]: duplicated update: sess_stats

**Repeat the same error.......**

2019-04-14 15:06:56.904 [error] 840b694b-c922-4945-b7a4-960debaccd4b@223.62.169.205:51616 [SM] Failed to discard <0.30831.424>: {noproc,
                                       {gen_server,call,
                                        [<0.30831.424>,
                                         {discard,<0.4369.434>},
                                         infinity]}}
2019-04-14 15:06:56.907 [error] 6c0d1c6f-401a-41f8-9743-48d567512b5d@223.62.222.74:9571 [SM] Failed to discard <0.8590.428>: {noproc,
                                      {gen_server,call,
                                       [<0.8590.428>,
                                        {discard,<0.26134.433>},
                                        infinity]}}
2019-04-14 15:06:56.921 [error] 0964be9b-8abf-461a-b447-d76b4fe16e7b@117.111.14.236:38494 [SM] Failed to discard <0.9375.428>: {noproc,
                                      {gen_server,call,
                                       [<0.9375.428>,
                                        {discard,<0.17998.430>},
                                        infinity]}}
2019-04-14 15:06:56.924 [error] 0102caa0-e5da-4aef-8189-0f39c0c2461f@106.102.11.97:20803 [SM] Failed to discard <0.11708.428>: {noproc,
                                       {gen_server,call,
                                        [<0.11708.428>,
                                         {discard,<0.6394.424>},
                                         infinity]}}

**Comment by hbahn** [comment]
Is there any update for this thread?

**Comment by Gilbert-Wong** [comment]
Hi, @hbahn, @kkang2  sorry for the late response. Could you please tell me that how many nodes in your cluster and how did you connect to emqx broker which could help us dig into your problem. And I would appreciate it if you can give us more log info. You can email to me <gilbertw@emqx.io>

**Comment by omere2** [comment]
happened to me as well.
cluster has only 1 node

`2019-05-18 21:43:07.672 [error] ** Generic server emqx_sm_locker terminating 
** Last message in was check_lease
** When Server state == {state,emqx_sm_locker,
                         {lease,15000,
                          {ok,
                           {interval,#Ref<0.1333669910.1083179009.177521>}}},
                         #{}}
** Reason for termination == 
** {badarg,[{ets,next,[emqx_sm_locker,<<"id">>],[]},
            {ekka_locker,check_lease,5,
                         [{file,"src/ekka_locker.erl"},{line,277}]},
            {ekka_locker,handle_info,2,
                         [{file,"src/ekka_locker.erl"},{line,237}]},
            {gen_server,try_dispatch,4,[{file,"gen_server.erl"},{line,637}]},
            {gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,711}]},
            {proc_lib,wake_up,3,[{file,"proc_lib.erl"},{line,259}]}]}
2019-05-18 21:43:07.673 [warning] [Alarm Handler] {supervisor_report,
                    [{supervisor,{local,emqx_sm_sup}},
                     {errorContext,child_terminated},
                     {reason,
                         {badarg,
                             [{ets,next,
                                  [emqx_sm_locker,<<"id">>],
                                  []},
                              {ekka_locker,check_lease,5,
                                  [{file,"src/ekka_locker.erl"},{line,277}]},
                              {ekka_locker,handle_info,2,
                                  [{file,"src/ekka_locker.erl"},{line,237}]},
                              {gen_server,try_dispatch,4,
                                  [{file,"gen_server.erl"},{line,637}]},
                              {gen_server,handle_msg,6,
                                  [{file,"gen_server.erl"},{line,711}]},
                              {proc_lib,wake_up,3,
                                  [{file,"proc_lib.erl"},{line,259}]}]}}]} set
2019-05-18 21:43:07.915 [error] id-reducted@10.0.24.157:58704 ** State machine <0.26077.386> terminating
** Last event = {cast,
                    {incoming,
                        {mqtt_packet,
                            {mqtt_packet_header,1,false,0,false},
                            {mqtt_packet_connect,<<"MQTT">>,4,false,true,
                                true,...},
                            undefined}}}
** When server state  = {idle,{state,esockd_transport,#Port<0.3403421>,
                                     {{10,0,24,...},58704},
                                     undefined,running,100,{...},...}}
`

**Comment by Gilbert-Wong** [comment]
Hi, @omere2 , in his case, he runs 17 nodes which is different from your case. From the error log you give, I cannot conclude what happens on your cluster. Do you mind sending me the whole log of this emqx node?

**Comment by omere2** [comment]
yes. I just emailed you the logs.

**Comment by hbahn** [comment]
@Gilbert-Wong 
So is there any news for this errors? even 17 nodes, this system should be stable I believe.
Thanks in advance.

**Comment by Gilbert-Wong** [comment]
@hbahn For now, if there are 17 nodes in one emqx cluster, the error your referred would be easy to occur. We'll improve the emqx cluster design in emqx 4.0 and to resolve this problem.

**Comment by hbahn** [comment]
@Gilbert-Wong Thanks for your answer.
We had the same node number in 2.x emqx version and this case we had no error like this at all.

**Comment by Gilbert-Wong** [comment]
Sorry, @hbahn, This is the a bug of emqx 3.0. It has been fixed in emqx 3.1.2 and beta.2. But we still do not recommend you to use 17 nodes in one emqx cluster now.
