### ISSUE TITLE
Truncating logged mqtt messages?

### ISSUE THREAD

**Issue by johnfwhitmore** [emqx/emqx#2442]
#### Environment

- OS: Ubuntu 16.04
- Erlang/OTP: 21
- EMQ: Compiled from source using emqx-packages/emqx-rel/emqx

#### Description

The process_incoming() function in the file emqx_connection.erl logs messages received using the line:

?LOG(debug, "RECV ~p", [Data]),

I've got very long MQTT messages and would like to truncate the messages logged when the logging level is set to "info" so something like:

Level = logger.get_primary_log_level()
if Level == debug ->  ?LOG(debug, "RECV ~p", [Data]);
   Level == info -> ?LOG(info, RECV ~p", [***TRUNCATED DATA***]);
   true -> ok
end,

I'm still working this through and trying to get my head around Erlang, so if someone could suggest how to truncate the data received to perhaps the first 40 bytes I'd be grateful of the help.

The idea is that when logging level is 'debug' you get the entire message received but if the log level is 'info' you only get a summary of the message received. Sounds very easy and it probably is if you have experience of Erlang.

**Comment by johnfwhitmore** [comment]
I did try to log using:

?LOG(info, "RECV ~p", [lists:sublist(Data, 1, 40)]),

and:

?LOG(info, "RECV ~p", [binary:part(Data, 0, 40)]),

but neither of those worked for me...

**Comment by johnfwhitmore** [comment]
A further enhancement would be to log the truncated message and the number of bytes removed from the message so that the output would be:

RECV <<48, 48, 48, 48,48, ... 600 Bytes Truncated>>

**Comment by johnfwhitmore** [comment]
Created pull request:

https://github.com/emqx/emqx/pull/2455

**Comment by terry-xiaoyu** [comment]
Close this as it has been fixed.

**Comment by johnfwhitmore** [comment]
As far as I know this issue has been fixed in a development branch and should be doing into the next release of the broker.
