### ISSUE TITLE
broker crash

### ISSUE THREAD

**Issue by czapsiu55** [emqx/emqx#2445]
#### Environment

- OS: Win10
- Erlang/OTP: 
- EMQ: v3.1-rc.2

#### Description

I have been using emqx for a short time. Currently, I try to adapt it to my needs. I have one publisher and one subscriber. I often crush the broker. I can not really find a problem.

Session(ChojnickieCentrumKultury) terminated: normal.2019-04-16 12:44:44.069 [error] ** Generic server emqx_statsd terminating 
** Last message in was {timeout,#Ref<0.3471622798.3712745474.127003>,
                                '#interval'}
** When Server state == {state,"http://127.0.0.1:9091",
                               #Ref<0.3471622798.3712745474.127003>,15000}
** Reason for termination == 
** {function_clause,
       [{proplists,get_value,[idle,0,0],[{file,"proplists.erl"},{line,215}]},
        {emqx_statsd,emqx_vm_data,0,[{file,"src/emqx_statsd.erl"},{line,332}]},
        {emqx_statsd,collect_mf,2,[{file,"src/emqx_statsd.erl"},{line,90}]},
        {prometheus_collector,collect_mf,3,
            [{file,"src/prometheus_collector.erl"},{line,157}]},
        {prometheus_registry,'-collect/2-lc$^0/1-0-',3,
            [{file,"src/prometheus_registry.erl"},{line,58}]},
        {prometheus_registry,collect,2,
            [{file,"src/prometheus_registry.erl"},{line,59}]},
        {prometheus_text_format,format,1,
            [{file,"src/formats/prometheus_text_format.erl"},{line,74}]},
        {emqx_statsd,handle_info,2,[{file,"src/emqx_statsd.erl"},{line,71}]}]}

**Comment by HJianBo** [comment]
Hi, @czapsiu55 This crash caused by [emqx_statsd](https://github.com/emqx/emqx-statsd/) plugin that can't support Windows OS to get CPU load status!  (You can find it at )

Maybe you can stop this plugin if not use it Or start EMQ X on someone of Unix systems.

**Comment by Gilbert-Wong** [comment]
What about running emqx on windows subsystem for linux :p ? Have anybody tried this ?

**Comment by turtleDeng** [comment]
@czapsiu55 
We have fixed it in 3.1-rc.3,Thanks for your feedback.
