### ISSUE TITLE
Changing size of log.rotation.size  ->  emqx no longer starts

### ISSUE THREAD

**Issue by johnfwhitmore** [emqx/emqx#2448]
#### Environment

- OS: Ubuntu 16.04
- Erlang/OTP: 21
- EMQ: commit 0c104faef728179385b22bd1cc7571ccd30f9dc1

#### Description

If the size of the logfile is changed in the configuration file /etc/emqx/emqx.conf  then to get emqx to start the contents of /var/log/emqx have to be removed, before emqx will successfully start.

**Comment by turtleDeng** [comment]
@johnfwhitmore 
Thank you very much, we will fix it as soon as possible and release it in 3.1-rc.3.
