### ISSUE TITLE
apt-get remove emqx does not remove /usr/bin/emqx*

### ISSUE THREAD

**Issue by johnfwhitmore** [emqx/emqx#2450]
#### Environment

- OS: Ubuntu 16.04
- Erlang/OTP: 21
- EMQ:  commit 0c104faef728179385b22bd1cc7571ccd30f9dc1

#### Description

If you remove emqx with the command 'apt-get remove emqx' to reinstall a fresh build the executables in '/usr/bin' are not removed.

**Comment by zhanghongtong** [comment]
We have not released the APT source of emqx. How do you install emqx with the apt command?

**Comment by johnfwhitmore** [comment]
Emqx/emqk-packages repo builds the Debian package which you can install
with dpkg -I

Then apt remove it

**Comment by zhanghongtong** [comment]
If you are using emqx installed with the `dpkg -i` command, you need to uninstall emqx using `dpkg -r emqx` or `dpkg -P emqx`

**Comment by phanimahesh** [comment]
afaik they should be equivalent. Apt is a dpkg frontend.

**Comment by HJianBo** [comment]
Close it first. Plz reopen it if has any question there
