### ISSUE TITLE
Webhook still cannot send will message when client closed

### ISSUE THREAD

**Issue by JackRanGitHub** [emqx/emqx#2451]
#### Environment

- OS: centos 6.8
- Erlang/OTP: 21
- EMQ: 3.1

#### Description

I follow you idea do my test, but I still cannot receive will message by webhook plugins.
webhook logs:
![image](https://user-images.githubusercontent.com/12415370/56281926-6f9ef380-6140-11e9-8945-508023e50020.png)

plugins list:
![image](https://user-images.githubusercontent.com/12415370/56281945-7cbbe280-6140-11e9-9a24-7dad13a33bc3.png)

Can you help me?Thank you very much!

**Comment by HJianBo** [comment]
Hi, @JackRanGitHub I have tested it, but it works very well! Can you provide more details about this? 

Or maybe you can subscribe the will-topic by another client to get this will message. If it received will-message but the Webhook is not working, you can paste the steps to help me to reproduce it!

**Comment by JackRanGitHub** [comment]
"Or maybe you can subscribe the will-topic by another client to get this will message".
I follow you idea,but I still cannot receive will message by webhook plugins.
Steps:
1、Use websocket as client connect emqx server
2、Close browser to close wesocket connect
3、watch webhook logs and emqx info logs
I use mqtt.js as client connect emqx server
js code:
`window.onload = function()
        {
            var options = {
                clientId: '123456',
                // username: '5c83c10d4d3dd',
                // password: 'Mjg2OTA2Mzc3NDAyOTM1NTc3NjMzMzY3NDU5MzcyMDcyOTG',
                will: {
                    topic: "clientWill",
                    payload: "aaaa",
                    retain: false,
                    qos: 0
                },
                // 这里是清除session
                clean: true
            }
            var client  = mqtt.connect(
                'ws://127.0.0.1:8083/mqtt',
                options
            )
            client.on('connect', function () {
                console.log('connect');
            })
            client.subscribe('presence', function (err) {

            })
            client.on('message', function (topic, message) {
              // message is Buffer
              console.log(message.toString())
            })
            client.on('error', function (error) {
                console.log('error:'+error.toString());
            });

            // 连接关闭
            client.on('close', function(){
                console.log('close');
            });
            // presence
            client.publish('presence', 'Hello mqtt')
}`
You can try it!Maybe you can find my problem.

**Comment by turtleDeng** [comment]
Same question https://github.com/emqx/emqx/issues/2435, we will close this issue
