### ISSUE TITLE
emqttd 2.3.9 ssl Problem

### ISSUE THREAD

**Issue by dovedong** [emqx/emqx#2452]
#### Environment

- OS: centos 7
- Erlang/OTP: 
- EMQ: 2.3.9

#### Description

*A description of the issue*

Most of the time the EMQ works perfect, but sometime the client cannot connect to the mqttBroker for the first time , need to connect again.

the error log is:
[error] Supervisor 'esockd_connection_sup - <0.24428.3092>' had child connection started with emqttd_client:start_link([{max_publish_rate,0},{client_idle_timeout,30000},{client_enable_stats,false},{max_clientid_l
en,...},...]) at <0.31846.5094> exit with reason {tls_alert,"record overflow"} in context connection_shutdown

**Comment by zmstone** [comment]
Sorry, I'm closing this issue now as version 2 is no longer in maintenance
