### ISSUE TITLE
EMQ X Broker v3.1-rc.2 RPM dashboard insecure - cannot change admin user password.

### ISSUE THREAD

**Issue by spydmobile** [emqx/emqx#2453]
#### Environment

- OS: CentOS 7
- Erlang/OTP: R21/10.3.2
- EMQ: EMQ X Broker v3.1-rc.2 RPM

#### Description
dashboard cannot change admin user password.

logging in as admin or as any other user will not allow the change of password for the admin user, when you try to type in the existing password it wont let you type it, tried this on chrome and firefox same result. this means you cannot secure the dashboard.

**Comment by spydmobile** [comment]
you can see this bug in action in both chrome and firefox:
https://youtu.be/2mt4jM1olUg

**Comment by spydmobile** [comment]
Hi Folks, the video is uploading should be viewable in a few minutes:
https://youtu.be/SToRLC5RBn0

**Comment by turtleDeng** [comment]
@spydmobile 
We have fixed it in 3.1-rc.3,Thanks for your feedback.

**Comment by spydmobile** [comment]
You are most welcome, and thanks for fixing it so quickly, I upgraded with :
`sudo rpm -Uvh emqx-centos7-v3.1-rc.3.x86_64.rpm`
then restarted with:
` sudo systemctl restart emqx`
Then changed the admin password to secure the dashboard successfully.
Have a great day!
