### ISSUE TITLE
Connection is broken

### ISSUE THREAD

**Issue by AaronZhao0301** [emqx/emqx#2462]
#### Environment

- OS: centos
- Erlang/OTP: 
- EMQ: emqttd-docker-v2.3.11

#### Description

*A description of the issue*
When the client and server establish a connection, the server always disconnects

**Comment by turtleDeng** [comment]
@AaronZhao0301 Please provide more log information.

**Comment by AaronZhao0301** [comment]
@turtleDeng 
There is no abnormal log on the server. I found the server disconnected through Wireshark. Maybe it is my computer's problem, I just restart the computer, but I did not restart the emqtt service, now it is normal

**Comment by AaronZhao0301** [comment]
@turtleDeng 

![image](https://user-images.githubusercontent.com/46880130/56480402-8486d880-64ec-11e9-866f-5b187efc73de.png)
192.168.101.189 is emqtt server

**Comment by HJianBo** [comment]
Hi, @AaronZhao0301 The picture doesn't have more information to help understand why the connection is broken.

Could you reproduce this issue with opening debug log and capturing net traffic? If it occurs again, please send these log and capture to here or my email: heeejianbo@gmail.com

**Comment by mononym** [comment]
Closing due to no response after a request for more information. @AaronZhao0301 if you still have this issue, especially in newer versions, please try to capture the debug logs and net traffic as requested above and get back in contact with us.
