### ISSUE TITLE
how to use emqx_statsd

### ISSUE THREAD

**Issue by reedF** [emqx/emqx#2463]
#### Environment

- OS: Linux
- Erlang/OTP: 
- EMQ: 3.0.1

#### Description

*A description of the issue*

I have set config for emqx_statsd to export data to statsd and start it, but can't get any data.
And when I check the log ,I can info for web_hooks but no emqx_statsd info.
how to use it?

**Comment by appdog** [comment]
@reedF Not sure if this is the right solution for you, but in our system we ended up using Prometheus Pushgateway:
https://github.com/prometheus/pushgateway

From there we can use Pushgateway as a scraping target for Prometheus and complement it with Grafana for monitoring.

EMQ X -> StatsD -> Prometheus Pushgateway -> Prometheus -> Grafana

You can also point your browser to the Pushgateway http endpoint and view the raw EMQ X metrics there.

**Comment by zmstone** [comment]
latest config doc:
https://docs.emqx.io/en/broker/v4.3/configuration/configuration.html#plugin-emqx-statsd
