### ISSUE TITLE
auth_mysql plugin fails to connect before mysql database initialization

### ISSUE THREAD

**Issue by r0mulux** [emqx/emqx#2465]
#### Environment

Docker image : emqx/emqx:v3.0.1
Docker-compose
Mysql docker container

#### Description

Hello, I'm using docker-compose to run emqx and mysql database. On first run, when database does not already exists, emqx auth_mysql plugin fails to connect before mysql database is created. 
If emqx container is restarted manually, everything works fine.

I found a possible workaround by using mysql healthcheck and "condition: service_healthy" in "depends_on" option of emqx container (docker-compose v2.1), but "condition" is not supported in higher versions of docker-compose.

Do you think it's possible to get emq auth plugin to retry connection to mysql database if connnection fails, as suggested here : https://docs.docker.com/compose/startup-order/ ?

Thanks !

**Comment by zhanghongtong** [comment]
Sorry to reply to you so late, I suggest you can write a shell script to detect the mysql service, run it before emqx starts, you can view emqx Dockerfile and other files [here](https://github.com/emqx/emqx-docker)
