### ISSUE TITLE
emqttd blocked the system shutdown

### ISSUE THREAD

**Issue by Zhang-Xianglong** [emqx/emqx#2466]
#### Environment

- OS: CentOS 6.9_64
- Erlang/OTP: 
- EMQ: 2.3.9

#### Description

emqttd blocked the system shutdown. As far as I know, emqttd does not use disk to store messages, it just uses memory. But the current phenomenon is that the longer it takes to use (the more messages are sent), the longer it takes to stop it.

![2a9acc0b3274a05dab29b3a0293c3a9](https://user-images.githubusercontent.com/25277179/56453751-487f3680-6379-11e9-933e-571fc334a24e.jpg)

**Comment by Zhang-Xianglong** [comment]
How to deal with this situation?

**Comment by Zhang-Xianglong** [comment]
How to properly shut down the service？

**Comment by zhengyupan** [comment]
Hi @Zhang-Xianglong ,
We didn't see your issue before and are unable to reproduce it. Did you try stop the emq on cli? How long it could take if you stop the emq service on cli?
