### ISSUE TITLE
make EMQ fail

### ISSUE THREAD

**Issue by kingTSong** [emqx/emqx#2467]
#### Environment

- OS: centos7.5
- Erlang/OTP: 21.3
- EMQ:   latest

#### Description
make EMQ ERROR: DEP ssl_verify_fun

**Comment by terry-xiaoyu** [comment]
Hi, remove the ssl_verify_fun dir from the `deps` and try again.

**Comment by kingTSong** [comment]
Today, I try it again and the problem has been solved,but I do nothing. Thanks!
