### ISSUE TITLE
emq_coap plugin can not work normally

### ISSUE THREAD

**Issue by shihuc** [emqx/emqx#2468]
#### Environment

- OS: Linux(CentOS7)
- Erlang/OTP: R20/9.0
- EMQ: V2.3.11

#### Description

I write a client program based org.eclipse.californium(element-connector-2.0.0-M7.jar, californium-core-2.0.0-M7.jar, scandium-2.0.0-M7.jar) to put message to my EMQ (V2) broker, but the response code is always 4.00. And, i check the log in EMQ broker, it is like this:
11:03:00.538 [error] CoAP-RES: put has error, Prefix=[<<"mqtt">>], Name=[<<"taikang">>,<<"coapt">>], Content={coap_content,undefined,60,<<"application/octet-stream">>,[],<<"helloSun Apr 21 11:02:06 CST 2019">>}
11:03:05.554 [error] CoAP-RES: put has error, Prefix=[<<"mqtt">>], Name=[<<"taikang">>,<<"coapt">>], Content={coap_content,undefined,60,<<"application/octet-stream">>,[],<<"helloSun Apr 21 11:02:11 CST 2019">>}

The client program is like this:
public class CoAPSender {

    public static void main(String[] args) throws URISyntaxException, InterruptedException {        
        //10.95.200.12 EMQTT, V2
        URI uri = new URI("coap://10.95.200.12:5683/mqtt/taikang/coapt?c=coaps1&u=water&p=water");
        CoapClient client = new CoapClient(uri);
        while (true) {
            String payload = "hello, " + new Date().toString();
            CoapResponse response = client.put(payload, APPLICATION_OCTET_STREAM);
            System.out.println(Utils.prettyPrint(response));
            Thread.sleep(5000);
        }
    }
}

BUT, BUT, when I change the broker from EMQTT(V2.3.11) to EMQX(V3.0.1), and the client java program URI is modified (IP is switched to the server where V3 version installed) and the others are same, the result is different. EMQX gives me a acceptable response, my client program scenario is not different.

Can you somebody give me an explanation what is wrong?

**Comment by terry-xiaoyu** [comment]
Do you mean v3.0.1 works but V2.3.11 doesn't? Then could you use V3.0.1 or later version? We've fixed many issues in it.

**Comment by shihuc** [comment]
> Do you mean v3.0.1 works but V2.3.11 doesn't? Then could you use V3.0.1 or later version? We've fixed many issues in it.

yes, v3.0.1 works, but v2.3.11 doesn't.
currently, we deployed our system based on v2.3.11, and, i find the difference is very big between v2 and v3,  I am not sure wheather it will impact the application or not if i upgrade it from v2 to v3.

**Comment by shihuc** [comment]
> Do you mean v3.0.1 works but V2.3.11 doesn't? Then could you use V3.0.1 or later version? We've fixed many issues in it.

And, I find another issue, v3.0.1 does not support coaps, my
