### ISSUE TITLE
subscirbe blocking or timeout with paho 

### ISSUE THREAD

**Issue by zender-projects** [emqx/emqx#2469]
#### Environment

- OS: Centos 7
- Erlang/OTP: 
- EMQ: 3.11.

#### Description

2019-04-22 14:03:36.556 [error] supervisor: 'esockd_connection_sup - <0.29528.53>'
    errorContext: connection_crashed
    reason: {{badmatch,{error,closed}},
             [{emqx_connection,init,1,
                               [{file,"src/emqx_connection.erl"},{line,146}]},
              {proc_lib,init_p_do_apply,3,
                        [{file,"proc_lib.erl"},{line,249}]}]}
    offender: [{pid,<0.446.54>},
               {name,connection},
               {mfargs,
                   {emqx_connection,start_link,
                       [[{deflate_options,[]},
                         {max_conn_rate,500},
                         {active_n,100},
                         {zone,external}]]}}]
2019-04-22 14:03:37.886 [error] crasher:
    initial call: emqx_connection:init/1
    pid: <0.451.54>
    registered_name: []
    exception error: no match of right hand side value {error,closed}
      in function  emqx_connection:init/1 (src/emqx_connection.erl, line 146)
    ancestors: [<0.29528.53>,<0.29527.53>,esockd_sup,<0.29342.53>]
    message_queue_len: 0
    messages: []
    links: [<0.29528.53>]
    dictionary: []
    trap_exit: false
    status: running
    heap_size: 4185
    stack_size: 27
    reductions: 4993
  neighbours:

the mqtt broker is always print this log in emqx.log.1, I do not know what it means. At the same time, when is subscribe by paho , the thead was blocking in sub,  java code like this:

sampleClient.connect(connOpts);
System.out.println("begin to subscribe topic " + ackTopic);
sampleClient.subscribe(ackTopic,1);   //it will blocking here
System.out.println("subscribe ack topic success");

and then , I set the connection timeout  like this:

sampleClient.setTimeToWait(3000);

it will throw Exception 
等待来自服务器的响应时超时
 (32000)
	at org.eclipse.paho.client.mqttv3.internal.Token.waitForCompletion(Token.java:112)
	at org.eclipse.paho.client.mqttv3.MqttToken.waitForCompletion(MqttToken.java:67)

i guess the reason is emq server configuration, but i have no some idea.

**Comment by HJianBo** [comment]
Hi, @zender-projects Sorry too late reply! In the first, could you give a more explicitly EMQ X version? 

And the crash logs of `emqx.log.1` shown that the connection is not correctly established with the client. So can you paste the details of the connection options in your Java client?

**Comment by JohnRoesler** [comment]
Hello - I am seeing this or a similar issue currently. What details can I provide to help in debugging?


Here is a log statement.
```
2020-10-07 10:40:38.545 [error] <<"CLIENT_ID">>@IP:48052   crasher:
    initial call: emqx_connection:init/4
    pid: <0.3164.5290>
    registered_name: []
    exception exit: {timeout,
                        {gen_server,call,
                            [<0.2221.0>,
                             {subscribe,
                                 <<"gateway/id/command/#">>}]}}
      in function  emqx_connection:terminate/2 (/emqx_rel/_build/emqx/lib/emqx/src/emqx_connection.erl, line 424)
    ancestors: [<0.2321.0>,<0.2320.0>,esockd_sup,<0.2085.0>]
    message_queue_len: 0
    messages: []
    links: [<0.2321.0>]
    dictionary: [{send_pkt,1},
                  {acl_keys_q,
                      {[{subscribe,<<"gateway/id/command/#">>}],
                       []}},
                  {'$logger_metadata$',
                      #{clientid =>
                            <<"CLIENT_ID">>,
                        peername => "IP:48052"}},
                  {recv_pkt,2},
                  {incoming_bytes,87},
                  {acl_cache_size,1},
                  {{subscribe,<<"gateway/id/command/#">>},
                   {allow,1602067233545}},
                  {outgoing_bytes,4},
                  {guid,{1602067233426642,157718347517020,1}}]
    trap_exit: false
    status: running
    heap_size: 1598
    stack_size: 27
    reductions: 3189
  neighbours:
```

EMQX version 4.1.0

I'm using the paho client with the [MaxReconnectInterval](https://godoc.org/github.com/eclipse/paho.mqtt.golang#ClientOptions.SetMaxReconnectInterval) set to 10 minutes. And I'm seeing the client subscription never reconnect (went for 4.5 hours before I rebooted it and it was able to reconnect).

**Comment by JohnRoesler** [comment]
Hello, do you have any suggestions for how to debug this further?

**Comment by HJianBo** [comment]
Hi @JohnRoesler The `{subscribe, <<"gateway/id/command/#">>}` timeout is caused that the guarantees of consistency for wildcard subscribing is very heavy in the cluster.  See the previous discussion: https://github.com/emqx/emqx/issues/2985
