### ISSUE TITLE
a node automatically leaves the cluster and does not automatically re-join

### ISSUE THREAD

**Issue by GoldLinPan** [emqx/emqx#2470]
#### Environment

- OS: windows server 2008
- Erlang/OTP: R19/8.3
- EMQ: 2.3.11

#### Description
Hello, I created a cluster with 2 nodes by static seeds， 3 days later，cluster broker down and the two nodes went back to working alone and no longer automatically join the cluster anymore unless one of the nodes is restarted. 
 log in node one says "Node 'emq@(node two)' not responding **
** Removing (timedout) connection ** ”.  
 log in node two says "Mnesia('emq@(node one)'): ** ERROR ** mnesia_event got {inconsistent_database, running_partitioned_network, 'emq@(node one)'}' ".

Why don't they cluster automatically anymore? thanks
*A description of the issue*

**Comment by Gilbert-Wong** [comment]
Because the mnesia databases are inconsistent in different databases. And if there are only two nodes in your cluster, you have to clean the mnesia database by yourself via deleting the data directory.

**Comment by pantongren** [comment]
@Gilbert-Wong  thanks for your answer,  if there are more than two nodes in the cluster ,this issue would not be produced ?

**Comment by Gilbert-Wong** [comment]
Yep.

**Comment by pantongren** [comment]
@Gilbert-Wong  if there are only two nodes ,  how do I delete the data directory?  delete the whole data directory or which files need to be deleted in the data directory?

**Comment by Gilbert-Wong** [comment]
@pantongren , please show me the files in data directory.

**Comment by pantongren** [comment]
@Gilbert-Wong  there are two directories 'configs' and 'mnesia' as well as a file 'loaded_plugins' in data directory,。And there are two directory named after the two nodes in 'mnesia' directory. And there are 7 files in each node directory，namely ‘shema.DAT‘，‘mqtt_quth_username.DCD’，‘mqtt_auth_clinetid.DCL’,'mqtt_auth_clientid.DCD','mqtt_admin.DCD', 'LATEST.LOG',  'DECISION_TAB.LOG' . The last two log files contain less content and some confused codes.

**Comment by pantongren** [comment]
@Gilbert-Wong ,hello, If the number of connections is large (200 clients)and communication is frequent, it is easier to report this error: "Mnesia('emq@(node one)'): ** ERROR ** mnesia_event got {inconsistent_database, running_partitioned_network, 'emq@(node one)'}' ". What is the reason? how to solve it ？ I don't use any databases in emqtt, why did it report this error?

**Comment by Gilbert-Wong** [comment]
@GoldLinPan, I'm so sorry to lay up this issue for so long time. We have improved the communication of the messages between different nodes in emqx 3.0. My suggestion is trying the latest stable emqx.

**Comment by turtleDeng** [comment]
Thanks for your feedback, we will close it.
