### ISSUE TITLE
 /lib/ld-musl-aarch64.so.1: bad ELF interpreter: No such file or directory

### ISSUE THREAD

**Issue by TongYuanOS** [emqx/emqx#2471]
#### Environment

- OS: centos 7.6 aarch64
- Erlang/OTP: erlang-21.2.4-1.el7.aarch64 erlang-otp_mibs-21.2.4-1.el7.aarch64
- EMQ: 3.0.0

#### Description

*A description of the issue*
/opt/emqtt/emqttd/erts-10.2.1/bin/run_erl 
-bash: /opt/emqtt/emqttd/erts-10.2.1/bin/run_erl: /lib/ld-musl-aarch64.so.1: bad ELF interpreter: No such file or directory

**Comment by phanimahesh** [comment]
How are you using emq? In docker, downloaded zip release, or did you compile it yourself?

**Comment by TongYuanOS** [comment]
> How are you using emq? In docker, downloaded zip release, or did you compile it yourself?

before, i download a arm64 binary ,but maybe this compile on debian distos(maybe ubuntu), share object said something wrong;
then, i cloned src and make it by myself, emqx will work.

**Comment by zhanghongtong** [comment]
Currently we only support the aarch64 platform on the Raspberry Pi. If you need to run emqx on other aarch64 platform operating systems, then you need to build emqx from the code.
