### ISSUE TITLE
Session is not cleared nor the will message is sent While the device is not in the client list.

### ISSUE THREAD

**Issue by arihantdaga** [emqx/emqx#2472]
#### Environment

- OS: 
Cent Os 7
- Erlang/OTP: 
I am not sure, i am using prebuilt binaries of EMQ 2.3.7
- EMQ: 
2.3.7

#### Description
I am using a cluster of emq with 2 brokers behind Haproxy. 
I am using esp8266 based hardwares connecting to the broker. 
Today i discovered this in the devices, one of the device got disconnected(or may be disconnected, i could not understand exactly whats happening). In the clients list in the dashboard, it does not show that device. However in the sessions, it shows that device's clientId.
Also in the device i am using asynmqtt library which thinks that the device is connected. 
The devices connects to the broker with a last will message of '0' on topic /status. But i am not receiving any retained message on that topic whenever i am subscribed to the device's last will topic. 
So i am not understanding if this is some sort of bug in which client is removed from client list but session still remains even after hours of device being disconnected and also the will message is not sent. Or if my haproxy configuration is wrong. 

I am having this haproxy config - 
```
listen mqtt
  bind my_host:1899
  bind mmy_host:9009 ssl crt /etc/haproxy/certs/my_host.pem

  maxconn 100000

  # communication mode (MQTT works on top of TCP)
  mode tcp
  option clitcpka # For TCP keep-alive
  timeout client 3h #By default TCP keep-alive interval is 2hours in OS kernal, 'cat /proc/sys/net/ipv4/tcp_keepalive_time'
  timeout server 3h #By default TCP keep-alive interval is 2hours in OS kernal
  option tcplog
  # balance mode (to choose which MQTT server to use)
  balance source
  server mqtt_1 MY_IP_1:1883 check send-proxy-v2
  server mqtt_2 MY_IP_2:1883 check send-proxy-v2
  log         127.0.0.1 local2 err

```
I am using balance as source, as someone suggested in an earlier issue. 
Can someone please help me here, if it is a bug or an expected behavior ? Or am i doing something wrong.. ?

**Comment by mononym** [comment]
This seems to have gotten buried in the shuffle. Given the numerous versions since this was posted, I'm going to go ahead and close this as it does not seem to be a common problem.

@arihantdaga if you are still having this issue please let us know and we will re open this and take a look.
