### ISSUE TITLE
build for centos 7 for on aarch64 platform

### ISSUE THREAD

**Issue by TongYuanOS** [emqx/emqx#2473]
#### Environment

- OS: 
- Erlang/OTP: 
- EMQ: 

#### Description

*A description of the issue*
I build a centos 7 package on aarch64 platform, if that can be pusblished to released, maybe a  good idea.

**Comment by zhanghongtong** [comment]
Currently we have no plans to release the package of the aarch64 platform, this will be implemented in the future.

**Comment by zmstone** [comment]
now we do. check out `main-v4.3` branch.
