### ISSUE TITLE
tcp_acceptor: init/1

### ISSUE THREAD

**Issue by DonxDaniyar** [emqx/emqx#2474]
#### Environment

- OS: 
- Erlang/OTP: 
- EMQ: 

#### Description

*A description of the issue*
2019-04-22 19:41:57 =ERROR REPORT====
** Generic server <0.209.0> terminating 
** Last message in was {inet_async,#Port<0.3643>,5606,{ok,#Port<0.5754>}}
** When Server state == {state,{emqtt_client_sup,start_client,[{<<"localhost">>,50000,false}]},#Port<0.3643>,5606,false,50000}
** Reason for termination == 
** {cannot_accept,{error,emfile}}
2019-04-22 19:41:57 =CRASH REPORT====
  crasher:
    initial call: tcp_acceptor:init/1
    pid: <0.209.0>
    registered_name: []
    exception exit: {{cannot_accept,{error,emfile}},[{gen_server,terminate,6,[{file,"gen_server.erl"},{line,744}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,239}]}]}
    ancestors: ['tcp_acceptor_sup_:::1883',<0.206.0>,emqtt_sup,<0.200.0>]
    messages: []
    links: [<0.207.0>]
    dictionary: []
    trap_exit: false
    status: running
    heap_size: 987
    stack_size: 27
    reductions: 283410
  neighbours:
2019-04-22 19:41:57 =SUPERVISOR REPORT====
     Supervisor: {local,'tcp_acceptor_sup_:::1883'}
     Context:    child_terminated
     Reason:     {cannot_accept,{error,emfile}}
     Offender:   [{pid,<0.209.0>},{name,tcp_acceptor},{mfargs,{tcp_acceptor,start_link,[{emqtt_client_sup,start_client,[{<<"localhost">>,50000,false}]},#Port<0.3643>]}},{restart_type,transient},{shutdown,brutal_kill},{child_type,worker}]

Hi all! I don't know this technology stack well. I am taking this error every 15 - 10 minute depends on the number of connections. I increasu ulimit on my ubuntu 16.04 and write max_connections in app.config to 100 000. Any ideas? "emqtt", "0.1.5" Thanks!

**Comment by DonxDaniyar** [comment]
i restart the emqtt every 10 minute but it's not a valid solution

**Comment by HJianBo** [comment]
Hi, @DonxDaniyar The `{error, emfile}`  caused by some of the system arguments is not enough.

You can see the tuning guide: https://developer.emqx.io/docs/emq/v3/en/tune.html

**Comment by DonxDaniyar** [comment]
> Hi, @DonxDaniyar The `{error, emfile}` would be triggered when some system arguments is not enough.
> 
> You can follow the tuning guide: https://developer.emqx.io/docs/emq/v3/en/tune.html

Thanks to reply! I use this tuning but i have errors same, nothings changes. One thing i can't find a emqx.conf file to rewrite some confs. Most of changes in tuning uses ipv4 but in error log i see :::1883 and my netstat -tlpn says about 1883 uses only ipv6 in beam.smp.

**Comment by HJianBo** [comment]
Hi @DonxDaniyar The v4.x has supported IPv6 listeners. You can try it later
