### ISSUE TITLE
Can't access slack

### ISSUE THREAD

**Issue by lewisdiamond** [emqx/emqx#2478]
Your slack links require already having an account or having an emqx.io email address. How do we get access to slack?

**Comment by zhengyupan** [comment]
Hi @lewisdiamond ,
The slack is currently limited to team internal usage only. Sorry for the confusion.  
If you have anything to discuss with emq team, you can open an issue here.

**Comment by lewisdiamond** [comment]
You should probably remove the links to slack then, there for example: https://www.emqx.io/services/support

**Comment by sgaoemq** [comment]
Hello there, 
Sorry for the confusion. I think it was our mistake to put the wrong link of EMQ slack channel for outside users.
Here is the right one:
https://join.slack.com/t/emqx/shared_invite/enQtNjIyMDYxMzg1MzUxLWY0NDQxNmRhYzg4NTJlZDk4ZGY4MWNlNTZiMTI4NjRiZWU1OTY0ZjUyN2RjMmI4Y2E5ODk4NTQzYzZkYjRlNTQ

**Comment by HJianBo** [comment]
Hi, guys. The right slack invitation URL and workspace URL has added to the README  file.

**Comment by ozbillwang** [comment]
@HJianBo 

This invite link is no longer active.

https://emqx.slack.com/join/shared_invite/enQtNjIyMDYxMzg1MzUxLWY0NDQxNmRhYzg4NTJlZDk4ZGY4MWNlNTZiMTI4NjRiZWU1OTY0ZjUyN2RjMmI4Y2E5ODk4NTQzYzZkYjRlNTQ

second, the slack in README `https://emqx.slack.com/` still need @emqx.io email address

**Comment by ozbillwang** [comment]
anyway, I have created a slack channel 

emqx-users.slack.com
