### ISSUE TITLE
If there are only two nodes in different regions, how to build a stable cluster?

### ISSUE THREAD

**Issue by GoldLinPan** [emqx/emqx#2479]
#### Environment

- OS: windows server 2008
- Erlang/OTP: R19/8.3
- EMQ: 2.3.11

#### Description
If there are only two nodes in different regions, how to build a stable cluster? I've built a cluster, but it's unstable, and it's disconnected at intervals due to error "Mnesia('emq@(node one)'): ** ERROR ** mnesia_event got {inconsistent_database, running_partitioned_network, 'emq@(node one)'}' ". if two nodes in different regions are not suitable for cluster, how to do  bidirectional forwarding by bridge? thanks.
*A description of the issue*

**Comment by turtleDeng** [comment]
@pantongren Has responded at https://github.com/emqx/emqx/issues/1206#issuecomment-486525311

**Comment by lightgao** [comment]
I have similar concern for this issue. Any suggestion for this? @turtleDeng . Does this related to "Network Partition Recovery" feature off EMQX?

**Comment by Gilbert-Wong** [comment]
Yes, if the cluster only have two nodes and the data is inconsistent between these two nodes, emqx cluster can not autoheal because emqx do not know which nodes data is more important and reliable, there is no election strategy in emqx cluster now.

**Comment by pantongren** [comment]
@Gilbert-Wong  That is to say, if more than two nodes are distributed in different public networks, a cluster of components can be stable, right? the same vpc is not required right?

**Comment by pantongren** [comment]
@turtleDeng That is to say, if more than two nodes are distributed in different public networks, a cluster of components can be stable, right? the same vpc is not required right?

**Comment by HJianBo** [comment]
@GoldLinPan No! If these nodes installed in the different VPC(means the network environment is not good for the distributed database data sync), the [Bridge](https://developer.emqx.io/docs/emq/v3/en/bridge.html) may be a good choice for you
