### ISSUE TITLE
emqx_coap does not support DTLS communicaton ???

### ISSUE THREAD

**Issue by shihuc** [emqx/emqx#2484]
#### Environment

- OS: CentOS7
- Erlang/OTP: R21/10.3.2
- EMQ: v3.0.1 & v3.1-rc.3

#### Description
emqx_coap does not support DTLS communicaton, attention, coap without DTLS can work.

I refer to the material https://github.com/eclipse/californium/tree/master/demo-apps/cf-secure/src/main/java/org/eclipse/californium/examples and write a demo program as the client to connect to my emqx coap gateway, neighter use coap://ip:5683/mqtt/{topic}?c={clientid}&u={usr}&p={pwd} nor coaps://ip:5683/mqtt/{topic}?c={clientid}&u={usr}&p={pwd}, the DTLS based communication failed.

I am sure the certificate with EC algorithm has no problem because it is successfully when I use the secureClient to connect to secureServer with the same client/server certificate and key.

can you give me some support or introduction about how to do to make it successfully with coap communication based DTLS?

**Comment by shihuc** [comment]
can you show me the procedure about how to make it work? document or demo...

**Comment by shihuc** [comment]
> #### Environment
> * OS: CentOS7
> * Erlang/OTP: R21/10.3.2
> * EMQ: v3.0.1 & v3.1-rc.3
> 
> #### Description
> emqx_coap does not support DTLS communicaton, attention, coap without DTLS can work.
> 
> I refer to the material https://github.com/eclipse/californium/tree/master/demo-apps/cf-secure/src/main/java/org/eclipse/californium/examples and write a demo program as the client to connect to my emqx coap gateway, neighter use coap://ip:5683/mqtt/{topic}?c={clientid}&u={usr}&p={pwd} nor coaps://ip:5683/mqtt/{topic}?c={clientid}&u={usr}&p={pwd}, the DTLS based communication failed.
> 
> I am sure the certificate with EC algorithm has no problem because it is successfully when I use the secureClient to connect to secureServer with the same client/server certificate and key.
> 
> can you give me some support or introduction about how to do to make it successfully with coap communication based DTLS?

**Comment by shihuc** [comment]
can you show me the procedure about how to make it work? document or demo...

**Comment by yunanxing** [comment]
I have the same problem,can't use DTLS
