### ISSUE TITLE
I want to know the maximum number of topics that can be subscribed to under a link? Is there anything wrong with that? Is there a more appropriate solution?

### ISSUE THREAD

**Issue by lichunyangVIP** [emqx/emqx#2488]
#### Environment

- OS: 
- Erlang/OTP: 
- EMQ: 

#### Description

*A description of the issue*

**Comment by tigercl** [comment]
Hi, @lichunyang321, the maximum number of subscriptions is determined by `max_subscriptions` in emqx.conf, and this option affects all connections under the listener, not just a single connection.

**Comment by lichunyang321** [comment]
Thanks@tigercl, But if I subscribe to a large number of topics on a single connection. Does this approach have adverse consequences?

**Comment by phanimahesh** [comment]
Typically it is the throughput that matters more than number of subscriptions. If your messages are infrequent you can get away with large number of subscriptions.

**Comment by mononym** [comment]
Closing this since the question was answered.
