### ISSUE TITLE
使用emqx_auth_username插件认证问题

### ISSUE THREAD

**Issue by cjcj125125** [emqx/emqx#2491]
#### Environment

- OS:  centos 7
- Erlang/OTP: 21
- EMQ:  emqx 3.0.1

#### Description

使用emqx_auth_username插件认证问题：
问题已提交至emqx_auth_username插件，希望得到帮助，谢谢
https://github.com/emqx/emqx-auth-username/issues/101

**Comment by HJianBo** [comment]
Ok, We'll check that, but don't open the repeated issue if you can
