### ISSUE TITLE
Clearing All Retained Messages Under Topic via API

### ISSUE THREAD

**Issue by Think7** [emqx/emqx#2492]
#### Environment

- OS: Ubuntu
- Erlang/OTP: 10.2
- EMQ: 3.1

#### Description

Hello,

Is there a way to clear all retained messages on a set of topics via the API? Or a way to publish a single retained messages that clears all topics under it?

Example:

Throughout the day, RETAINED messages get published to:

/app/data/live/obj1/dataset1
/app/data/live/obj1/dataset2

/app/data/live/obj2/dataset1
/app/data/live/obj2/dataset2

/app/data/live/obj3/dataset1
/app/data/live/obj3/dataset2

I need to clear all retained messages on topic "/app/data/live/+/dataset1" but leave "/app/data/live/+/dataset2" alone. Note the use of a + to specify any object.

**Comment by HJianBo** [comment]
We don't support this feature to delete all specified retained messages now. But I think it is useful for managing retained messages. So, we'll discuss this later. Thanks!

**Comment by HJianBo** [comment]
Hi, @Think7 We'll release this feature in the v3.1.1 after two weeks

**Comment by Think7** [comment]
Thank you so much! That is EXCELLENT NEWS! ❤️  🍍

**Comment by HJianBo** [comment]
Close it first. Plz reopen it if has any question there
