### ISSUE TITLE
After websocket client disconnected,I cannot receive will message publish by webhook plugins

### ISSUE THREAD

**Issue by JackRanGitHub** [emqx/emqx#2493]
#### Environment

- OS: centos6.8
- Erlang/OTP: 21
- EMQ: 3.1-rc3

#### Description
plugins list:
![image](https://user-images.githubusercontent.com/12415370/56858179-8cd98a80-69a8-11e9-9e4b-ca6f5995fc63.png)

webhook info list:
![image](https://user-images.githubusercontent.com/12415370/56858196-d7f39d80-69a8-11e9-9c01-f73d96ef17b8.png)

code list:
`<script type="text/javascript">
        window.onload = function()
        {
            var options = {
                clientId: '123456',
                // username: 'admin',
                // password: '123456',
                will: {
                    topic: "clientWill",
                    payload: "aaaa",
                    retain: false,
                    qos: 0
                },
                // 这里是清除session
                clean: true
            }
            var client  = mqtt.connect(
                'ws://127.0.0.1:8083/mqtt',
                options
            )
            client.on('connect', function () {
                console.log('connect');
            })
            client.subscribe('presence', function (err) {

            })
            client.on('message', function (topic, message) {
              // message is Buffer
              console.log(message.toString())
            })
            client.on('error', function (error) {
                console.log('error:'+error.toString());
            });

            // 连接关闭
            client.on('close', function(){
                console.log('close');
            });
            // presence
            client.publish('presence', 'Hello mqtt')
     }
</script>`

After websocket client disconnected, I cannot receive will message publish by webhook plugins.Can you help me?Thanks

**Comment by turtleDeng** [comment]
Same question https://github.com/emqx/emqx/issues/2435, we will close this issue.
