### ISSUE TITLE
Slogan: eheap_alloc: Cannot allocate 8162366936 bytes of memory (of type "heap").

### ISSUE THREAD

**Issue by lindabang** [emqx/emqx#2494]
#### Environment

- OS: ubuntu 18.04 LTS x86_64
- Erlang/OTP: R21/10.2
- EMQ: v3.1-rc3
- CPU: Intel(R) Xeon(R) CPU  L5520  @ 2.27GHz , 16 processors
- RAM: 32GB

#### Description
emqx crash:

root@netmoon-server:~# ls -lh /var/log/emqx/crash.dump 
-rw-r----- 1 emqx emqx 12G 4月  28 14:57 /var/log/emqx/crash.dump

root@netmoon-server:~# head -n 128 /var/log/emqx/crash.dump 
=erl_crash_dump:0.5
Sun Apr 28 14:49:27 2019
Slogan: eheap_alloc: Cannot allocate 8162366936 bytes of memory (of type "heap").
System version: Erlang/OTP 21 [erts-10.2] [source] [64-bit] [smp:16:16] [ds:16:16:10] [async-threads:32] [hipe]
Compiled: Tue Dec 11 11:48:26 2018
Taints: dyntrace,crypto,asn1rt_nif,bcrypt_nif
Atoms: 41330
Calling Thread: scheduler:0
=scheduler:1
Scheduler Sleep Info Flags: 
Scheduler Sleep Info Aux Work: DD_THR_PRGR | CNCLD_TMRS_THR_PRGR
Current Port: 
Run Queue Max Length: 0
Run Queue High Length: 0
Run Queue Normal Length: 0
Run Queue Low Length: 0
Run Queue Port Length: 0
Run Queue Flags: OUT_OF_WORK | NONEMPTY | EXEC
Current Process: <0.26780.19>
Current Process State: Running
Current Process Internal State: ACT_PRIO_NORMAL | USR_PRIO_NORMAL | PRQ_PRIO_NORMAL | ACTIVE | RUNNING
Current Process Program counter: 0x00007f4def64e708 (unknown function)
Current Process CP: 0x0000000000000000 (invalid)
Current Process Limited Stack Trace:
0x00007f4b8adc3220:SReturn addr 0xB7F51FC8 (emqx_protocol:do_publish/2 + 608)
0x00007f4b8adc3230:SReturn addr 0xB778BA98 (emqx_connection:handle_packet/3 + 144)
0x00007f4b8adc3258:SReturn addr 0x6D608818 (gen_statem:call_state_function/5 + 472)
0x00007f4b8adc3270:SReturn addr 0x6D601F08 (gen_statem:loop_event_state_function/6 + 232)
0x00007f4b8adc3290:SReturn addr 0x6DD92DD0 (proc_lib:init_p_do_apply/3 + 72)
0x00007f4b8adc32d0:SReturn addr 0xD4706D8 (<terminate process normally>)
=scheduler:2
Scheduler Sleep Info Flags: 
Scheduler Sleep Info Aux Work: DELAYED_AW_WAKEUP | DD | THR_PRGR_LATER_OP | CNCLD_TMRS
Current Port: 
Run Queue Max Length: 0
Run Queue High Length: 0
Run Queue Normal Length: 0
Run Queue Low Length: 0
Run Queue Port Length: 0
Run Queue Flags: OUT_OF_WORK | HALFTIME_OUT_OF_WORK | NONEMPTY | EXEC
Current Process: <0.26759.19>
Current Process State: Running
Current Process Internal State: ACT_PRIO_NORMAL | USR_PRIO_NORMAL | PRQ_PRIO_NORMAL | ACTIVE | RUNNING
Current Process Program counter: 0x00007f4def64e708 (unknown function)
Current Process CP: 0x0000000000000000 (invalid)
Current Process Limited Stack Trace:
0x00007f4b03526dc8:SReturn addr 0xB7F506D0 (emqx_protocol:process/2 + 5664)
0x00007f4b03526de8:SReturn addr 0xB778BA98 (emqx_connection:handle_packet/3 + 144)
0x00007f4b03526e08:SReturn addr 0x6D608818 (gen_statem:call_state_function/5 + 472)
0x00007f4b03526e20:SReturn addr 0x6D601F08 (gen_statem:loop_event_state_function/6 + 232)
0x00007f4b03526e40:SReturn addr 0x6DD92DD0 (proc_lib:init_p_do_apply/3 + 72)
0x00007f4b03526e80:SReturn addr 0xD4706D8 (<terminate process normally>)
=scheduler:3
Scheduler Sleep Info Flags: 
Scheduler Sleep Info Aux Work: DD_THR_PRGR
Current Port: 
Run Queue Max Length: 0
Run Queue High Length: 0
Run Queue Normal Length: 0
Run Queue Low Length: 0
Run Queue Port Length: 0
Run Queue Flags: OUT_OF_WORK | NONEMPTY | EXEC
Current Process: <0.26803.19>
Current Process State: Running
Current Process Internal State: ACT_PRIO_NORMAL | USR_PRIO_NORMAL | PRQ_PRIO_NORMAL | ACTIVE | RUNNING
Current Process Program counter: 0x00007f4def64e708 (unknown function)
Current Process CP: 0x0000000000000000 (invalid)
Current Process Limited Stack Trace:
0x00007f4c25d4e6a0:SReturn addr 0xF3283520 (application:get_env/3 + 72)
0x00007f4c25d4e6a8:SReturn addr 0xB7747380 (emqx_access_control:check_acl/3 + 152)
0x00007f4c25d4e6b8:SReturn addr 0xB7F55020 (emqx_protocol:check_pub_acl/2 + 536)
0x00007f4c25d4e6d8:SReturn addr 0xB7F55120 (emqx_protocol:run_check_steps/3 + 128)
0x00007f4c25d4e6e0:SReturn addr 0xB7F506D0 (emqx_protocol:process/2 + 5664)
0x00007f4c25d4e700:SReturn addr 0xB778BA98 (emqx_connection:handle_packet/3 + 144)
0x00007f4c25d4e720:SReturn addr 0x6D608818 (gen_statem:call_state_function/5 + 472)
0x00007f4c25d4e738:SReturn addr 0x6D601F08 (gen_statem:loop_event_state_function/6 + 232)
0x00007f4c25d4e758:SReturn addr 0x6DD92DD0 (proc_lib:init_p_do_apply/3 + 72)
0x00007f4c25d4e798:SReturn addr 0xD4706D8 (<terminate process normally>)
=scheduler:4
Scheduler Sleep Info Flags: 
Scheduler Sleep Info Aux Work: DD_THR_PRGR
Current Port: 
Run Queue Max Length: 0
Run Queue High Length: 0
Run Queue Normal Length: 0
Run Queue Low Length: 0
Run Queue Port Length: 0
Run Queue Flags: NONEMPTY | EXEC
Current Process: <0.26823.19>
Current Process State: Running
Current Process Internal State: ACT_PRIO_NORMAL | USR_PRIO_NORMAL | PRQ_PRIO_NORMAL | ACTIVE | RUNNING
Current Process Program counter: 0x00007f4def64b628 (unknown function)
Current Process CP: 0x0000000000000000 (invalid)
Current Process Limited Stack Trace:
0x00007f4c308ac988:SReturn addr 0xB776C2A0 (emqx_broker:dispatch/2 + 232)
0x00007f4c308ac990:SReturn addr 0x6DC8C6A8 (lists:foldl/3 + 112)
0x00007f4c308ac9b8:SReturn addr 0xB776B6B0 (emqx_broker:publish/1 + 752)
0x00007f4c308ac9d0:SReturn addr 0xB6C01580 (emqx_session:publish/3 + 712)
0x00007f4c308ac9d8:SReturn addr 0xB7F52008 (emqx_protocol:do_publish/2 + 672)
0x00007f4c308ac9e0:SReturn addr 0xB778BA98 (emqx_connection:handle_packet/3 + 144)
0x00007f4c308aca00:SReturn addr 0x6D608818 (gen_statem:call_state_function/5 + 472)
0x00007f4c308aca18:SReturn addr 0x6D601F08 (gen_statem:loop_event_state_function/6 + 232)
0x00007f4c308aca38:SReturn addr 0x6DD92DD0 (proc_lib:init_p_do_apply/3 + 72)
0x00007f4c308aca78:SReturn addr 0xD4706D8 (<terminate process normally>)
=scheduler:5
Scheduler Sleep Info Flags: 
Scheduler Sleep Info Aux Work: DD_THR_PRGR | THR_PRGR_LATER_OP | CNCLD_TMRS_THR_PRGR
Current Port: 
Run Queue Max Length: 0
Run Queue High Length: 0
Run Queue Normal Length: 0
Run Queue Low Length: 0
Run Queue Port Length: 0
Run Queue Flags: NONEMPTY | EXEC
Current Process: <0.26776.19>
Current Process State: Running
Current Process Internal State: ACT_PRIO_NORMAL | USR_PRIO_NORMAL | PRQ_PRIO_NORMAL | ACTIVE | RUNNING
Current Process Program counter: 0x00007f4def64e708 (unknown function)
Current Process CP: 0x0000000000000000 (invalid)
Current Process Limited Stack Trace:
0x00007f4b504715f8:SReturn addr 0xB6CE7AD8 (mnesia_index:dirty_read2/3 + 792)
0x00007f4b50471600:SReturn addr 0x6D92FEC0 (rpc:local_call/3 + 120)
0x00007f4b50471628:SReturn addr 0xB6C7B6F8 (mnesia:do_dirty_rpc/5 + 232)
0x00007f4b50471638:SReturn addr 0xB72E7CC0 (emqx_rule_runtime:'-apply_rules_fun/1-fun-0-'/2 + 72)
0x00007f4b50471678:SReturn addr 0xB72E5180 (emqx_rule_runtime:on_message_publish/2 + 608)
0x00007f4b50471688:SReturn addr 0xB77A4D60 (emqx_hooks:do_run_fold/3 + 328)
0x00007f4b50471698:SReturn addr 0xB776B500 (emqx_broker:publish/1 + 320)
0x00007f4b504716c8:SReturn addr 0xB6C01580 (emqx_session:publish/3 + 712)

**Comment by terry-xiaoyu** [comment]
@lindabang 

Hi, could you post your `crash.dump` file to a cloud disk and give the url here?

And may I ask some details of your scenario?

1. How many connected clients do you have?
2. Do you have any subscriber which is receiving lots of messages from many publishers? 

//Shawn

**Comment by lindabang** [comment]
60000 clients , 
We use about 60000 topics like topic/1, topic/2, topic/3 ...
and 1 consumers subscribe these topics like topic/#.
Messages published to each topic is about 1 packets per second

**Comment by Gilbert-Wong** [comment]
Hi, @lindabang , you mean that each client publish one message to each topic per second, could you please tell me the message qos level?

**Comment by lindabang** [comment]
Qos 0

**Comment by Gilbert-Wong** [comment]
The publish rate of your messages is 60000 msg/s. It is too high for emqx. You have to degrade your publish rate to 40000 msgs/s according your business. We have schedule to improve the msg publish performance in emqx 3.2.

**Comment by terry-xiaoyu** [comment]
@lindabang It is the single subscriber which crashes the EMQ. The subscriber cannot consume so many messages in time, so the messages are cached in the memory. You may need [Shared Subscription](https://developer.emqx.io/docs/broker/v3/en/advanced.html).

**Comment by terry-xiaoyu** [comment]
@lindabang 

We have a configuration to protect emqx from crash due to Out-Of-Memory. The way we chose is to disconnect the client if it cannot handle the traffic load. Lots of messages would drop but the broker survive.

Could you add a line in your `emqx.conf` and help test the same scenario again? Thanks.

```
## Max message queue length and total heap size to force shutdown connection/session process.
## Numbers delimited by `|'. Zero or negative is to disable.
zone.external.force_shutdown_policy = 10000|1024MB
```
