### ISSUE TITLE
where the rules be stored ??

### ISSUE THREAD

**Issue by naruto0916** [emqx/emqx#2496]
#### Environment

- OS: CentOS7
- EMQ: 3.0.1

Hi EMQ team:

I saw the emqx had supported the rule engine feature.
It is a very useful function.
I read the document about the rule command and have a question about it.
Where is the rule be stored when I add a new rule by rule command??
If my emqx server breakdown, have any way to restore my rules that added before ??

Cheers

**Comment by terry-xiaoyu** [comment]
It'll be stored in the mnesia tables -- persistent disk tables. The data file of mnesia is in the `data` directory of your emqx's installation path.

**Comment by terry-xiaoyu** [comment]
BTW the open source emqx only support limited features of rule-engine, basically you'd have to use emqx enterprise to get more rule-actions for example, handling and storing messages to MySQL or Redis.
