### ISSUE TITLE
Restful API Login 

### ISSUE THREAD

**Issue by johnfwhitmore** [emqx/emqx#2498]
#### Environment

- OS: Ubuntu 16.04
- Erlang/OTP: 
- EMQ: emqx-ubuntu16.04-v3.1-rc.3_amd64.deb

#### Description

There have been other issues raised about the Rest API but I haven't found a solution to logging into the API at port 8080. Apparently you have to create a login with the emqx_ctl admins command, which I have tried but whilst that executed ok the login credentials I created are not accepted when I attempt to login.

https://developer.emqx.io/docs/emq/v3/en/commands.html#admins

**Comment by HJianBo** [comment]
You should use the `mgmt insert <AppId> <Name>` to create the REST API credentials, not `admins` command

**Comment by johnfwhitmore** [comment]
So in the example given in the documentation:

$ ./bin/emqx_ctl mgmt insert dbcb6e023370b world
AppSecret: MjgzMzQ5MjYyMTY3ODk4MjA5NzMwODExODMxMDM1NDk0NDA

what are the username and password used for the API?

**Comment by johnfwhitmore** [comment]
Just to be clear I'm don't want authentication on MQTT Publishers and subscribers but the REST API

**Comment by johnfwhitmore** [comment]
Sorry I think I have some confusion about the port used for the REST API. I was using 8080 as mentioned in:

https://developer.emqx.io/docs/emq/v3/en/rest.html#cluster-and-node

Creating users and not gaining access. I seems that I want port 18083?

**Comment by HJianBo** [comment]
Nope. We don't recommend you using 18083 to access REST API. Because it designed by Dashboard not REST API.

Just follow this guide https://developer.emqx.io/docs/emq/v3/en/rest.html#cluster-and-node to access REST API

**Comment by HJianBo** [comment]
For example:

1. Add an App:
```bash
./bin/emqx_ctl mgmt insert a_app_id TestApp
AppSecret: Mjg3MTQwMTk2ODQwNzE4ODg0MDAzOTI3NDU5ODcwODAxOTC
```

2. Call REST an API:
```bash
curl -v --basic -u a_app_id:Mjg3MTQwMTk2ODQwNzE4ODg0MDAzOTI3NDU5ODcwODAxOTC -k http://localhost:8080/api/v3/brokers
```

**Comment by johnfwhitmore** [comment]
This is strange I'm not not getting anything from port 8080. Yesterday I was getting a login request from that port.

**Comment by johnfwhitmore** [comment]
Restart of the broker and there's still no response from port 8080

**Comment by Gilbert-Wong** [comment]
@johnfwhitmore , maybe you can try with command `lsof -i:8080` to find out that if some other service has occupied 8080 port.

**Comment by johnfwhitmore** [comment]
That port, like 18083 is controlled by beam, which is emqx. So whilst emqx is responding to port 18083 it is not responding to 8080, even if it has that port and is listening.

tcp        0      0 0.0.0.0:6369            0.0.0.0:*               LISTEN      27853/beam.smp
tcp        0      0 0.0.0.0:18083           0.0.0.0:*               LISTEN      27853/beam.smp
tcp        0      0 127.0.0.1:11883         0.0.0.0:*               LISTEN      27853/beam.smp
tcp        0      0 0.0.0.0:8080            0.0.0.0:*               LISTEN      27853/beam.smp
tcp        0      0 0.0.0.0:4369            0.0.0.0:*               LISTEN      870/epmd
tcp        0      0 0.0.0.0:8883            0.0.0.0:*               LISTEN      27853/beam.smp
tcp        0      0 0.0.0.0:8083            0.0.0.0:*               LISTEN      27853/beam.smp
tcp        0      0 0.0.0.0:8084            0.0.0.0:*               LISTEN      27853/beam.smp
tcp        0      0 0.0.0.0:5369            0.0.0.0:*               LISTEN      27853/beam.smp
tcp        0      0 0.0.0.0:1883            0.0.0.0:*               LISTEN      27853/beam.smp

**Comment by johnfwhitmore** [comment]
I'm currently using v3.1-rc.3 but I see that there's a version of v3.1 so I assume I should probably move to that version as v3.1 has been released?

**Comment by Gilbert-Wong** [comment]
Yes, @johnfwhitmore , welcome to try with emqx v3.1 :)
