### ISSUE TITLE
Dashboard doesn't work in emqx-edge

### ISSUE THREAD

**Issue by 0helong0** [emqx/emqx#2501]
#### Environment

- OS: raspberry - 2019-04-08-raspbian-stretch
- Erlang/OTP: 
- EMQ: emqx-edge-raspbian9-v3.1.0

#### Description

   Hello, I managed to startup an emqx-edge on my Raspberry Pi, the CLI works but I cannot access the dashboard via `127.0.0.1:18083`. Do you know what causes the problem?

**Comment by zhanghongtong** [comment]
Emqx edge broker does not support the plugin for dashboard

**Comment by terry-xiaoyu** [comment]
Hi, that's because emqx-edge doesn't have dashboard. The following plugins are not included in emqx-edge for saving memory:

```
emqx-lwm2m emqx-auth-ldap emqx-auth-pgsql emqx-auth-redis,
emqx-auth-mongo emqx-lua-hook emqx-plugin-template emqx-dashboard,
emqx-statsd
```

Dashboard on edge is not needed because we have [Strom](https://storm.emqx.io).

**Comment by 0helong0** [comment]
Thanks for the answer!
If I want to use Dashboard, what should I do, can I compile the source installation?
Thank you! ! !

**Comment by 0helong0** [comment]
Thanks for the answer!
I am going to use Storm now.

**Comment by zhanghongtong** [comment]
We will close this issue and you can reopen if there are any problems.
