### ISSUE TITLE
Problem with firewall and ports 6369:7369

### ISSUE THREAD

**Issue by arihantdaga** [emqx/emqx#2502]
#### Environment

- OS:  Ubuntu
- Erlang/OTP:  21
- EMQ: 3.1.0

#### Description
According to the docs - https://developer.emqx.io/docs/emq/v3/en/cluster.html#the-firewall we need to open the port 4369 and 6369-7369 for inter communication between the nodes. 
However i noticed that this doesnt work in the cluster and if 2 clients connected to 2 different nodes are subscribed to the same topic. Then if 1 publishes on that topic, the another one doesnt recieve. But it works as expected if firewall is turned off. 

Opening these ports in firewall doesnt have any effect, i have already tried that. 
```
22/tcp                     ALLOW       Anywhere                  
1883                       ALLOW       LOAD_BALANCERS_IP            
18083                      ALLOW       LOAD_BALANCERS_IP     
8080                       ALLOW       LOAD_BALANCERS_IP            
8087                       ALLOW       LOAD_BALANCERS_IP        
4369                       ALLOW       SECOND_BROKER_IP                     
6369:7369/tcp      ALLOW      SECOND_BROKER_IP                   
6369:7369/udp     ALLOW      SECOND_BROKER_IP       
22/tcp (v6)                ALLOW       Anywhere (v6)      

```

I doubt if the ports mentioned in the documentation are correct, or there is additional missing part. 
I have this in my emqx.conf also
```
node.dist_listen_min = 6369
node.dist_listen_max = 7369

```

**Comment by Gilbert-Wong** [comment]
What about the port `5369`, it is used by emqx for rpc.

**Comment by arihantdaga** [comment]
Ok... I'll try opening that also..

**Comment by arihantdaga** [comment]
@Gilbert-Wong  Thank you very much. After opening port 5369, It worked.

**Comment by Gilbert-Wong** [comment]
It's honored to help you.
2019年5月3日 +0800 PM9:53 arihant daga <notifications@github.com>，写道：

@Gilbert-Wong<https://github.com/Gilbert-Wong> Thank you very much. After opening port 5369, It worked.
