### ISSUE TITLE
Bad cookie in table definition mqtt_admin

### ISSUE THREAD

**Issue by mdrobny** [emqx/emqx#2511]
#### Environment

- OS: Amazon Linux AMI 
- Erlang/OTP: R21/10.2.1
- EMQ: https://github.com/emqx/emqx/releases/tag/v3.0.1

#### Description

Hi

I got this error in one of my cluster's instances (it is formatted like that, I didn't adjust error message formatting`:
```
 [error] [Ctl] CMD Error:{error,
                    {merge_schema_failed,
                        "Bad cookie in table definition mqtt_admin: 'emqx@172.20.60.214' = {cstruct,mqtt_admin,set,[],['emqx@172.20.36.112','emqx@172.20.60.181'],[],[],0,read_write,false,[],[],true,mqtt_admin,[username,password,tags],[],[],[],{{1557075594672367378,-576460752303422943,1},'emqx@172.20.60.181'},{{2,1},{'emqx@172.20.36.112',{1557,75729,900268}}}}, 'emqx@172.20.36.112' = {cstruct,mqtt_admin,set,[],['emqx@172.20.60.214','emqx@172.20.36.112'],[],[],0,read_write,false,[],[],true,mqtt_admin,[username,password,tags],[],[],[],{{1557002067418630231,-576460752303422991,1},'emqx@172.20.54.58'},{{2,95},{'emqx@172.20.60.214',{1557,76031,139891}}}}\n"}}, 

Stacktrace: [{ekka_mnesia,ensure_ok,1, [{file,"src/ekka_mnesia.erl"},{line,263}]},
                     {ekka_mnesia,join_cluster,1, [{file,"src/ekka_mnesia.erl"},{line,139}]},
                     {ekka_cluster,join,1, [{file,"src/ekka_cluster.erl"},{line,31}]},
                     {emqx_mgmt_cli,cluster,1, [{file,"src/emqx_mgmt_cli.erl"},{line,150}]},
                     {emqx_ctl,run_command,2, [{file,"src/emqx_ctl.erl"},{line,64}]},
                     {rpc,'-handle_call_call/6-fun-0-',5, [{file,"rpc.erl"},{line,197}]}]
```

Now this instance is not responding. Calling `./bin/emqx_ctl` results in 
```
Usage: emqx_ctl
RPC to emqx@172.20.60.214 failed: {'EXIT',
                                   {badarg,
                                    [{ets,match_object,[emqx_command,'_'],[]},
                                     {ets,tab2list,1,
                                      [{file,"ets.erl"},{line,763}]},
                                     {emqx_ctl,usage,0,
                                      [{file,"src/emqx_ctl.erl"},{line,85}]},
                                     {rpc,'-handle_call_call/6-fun-0-',5,
                                      [{file,"rpc.erl"},{line,197}]}]}}
```

This instance was running for couple of days and it went down and I just have to kill it to recover from it. I happened second time already

Issues that mention similar error with "bad cookie":
#2264 
https://github.com/emqtt/emq-dashboard/issues/32

**Comment by Gilbert-Wong** [comment]
It seems that network partition happens on your cluster, which caused that the mnesia database is inconsistent between different nodes. If there are two nodes in your cluster, you can delete mnesia directory under `data/` path of emqx. And could you please tell me how many emqx nodes in your emqx cluster ?

**Comment by mdrobny** [comment]
@Gilbert-Wong I have 2 to 3 instances currently - amount depends on metrics like cpu usage, memory usage, connection latency etc. So instances joined and leaved couple of time during this ~5 days period

**Comment by Gilbert-Wong** [comment]
If there are only 2 nodes in one cluster, you have to clean the `data/mnesia` directory in both nodes. And if there are 3 nodes in your cluster, the cluster did not autoheal successfully, I hope you can provide log file for us to find out if it is the cluster bug of emqx.

**Comment by mdrobny** [comment]
@Gilbert-Wong should I provide logs from 3 instances?

**Comment by mdrobny** [comment]
I sent it via email to @Gilbert-Wong

**Comment by Gilbert-Wong** [comment]
Ok, I’ll read it later.
On May 6, 2019, 8:20 PM +0800, Michał Drobniak <notifications@github.com>, wrote:

I sent it via email to @Gilbert-Wong<https://github.com/Gilbert-Wong>

**Comment by mdrobny** [comment]
I am not sure if this is related but can you suggest what is good value for `cluster.autoclean`
https://github.com/emqx/emqx/blob/master/etc/emqx.conf#L43?
Or what it should depend on? 
Is default 5m proper time period from your perspective?

**Comment by Gilbert-Wong** [comment]
Sorry for late reponse. @mdrobny. Yes, it is the proper time period.
