### ISSUE TITLE
more than 1000 devices connected to emqx concurrently, received internal subscription $SYS/brokers/+/clients/+/connected messages about 200

### ISSUE THREAD

**Issue by fangsj** [emqx/emqx#2514]
#### Environment

- OS: Centos7 64
- Erlang/OTP: R21/10.3.2
- EMQ: 3.1.0

#### Description

*Reboot emqx, more than 1000 devices connected to emqx concurrently, received internal subscription $SYS/brokers/+/clients/+/connected messages about 200, seems to have lost messages. Will there be such a problem?*

**Comment by turtleDeng** [comment]
We have fixed it and released at v3.1.2 yesterday!
Thanks for your feedback :)
