### ISSUE TITLE
Bridge Mode not working with Python

### ISSUE THREAD

**Issue by vrst37** [emqx/emqx#2516]
#### Environment

- OS: Docker image provided with V3.1.0 running on ubuntu 18.04 64bit
- Erlang/OTP: Whatever is in the docker image provided
- EMQ: V3.1.0

#### Description

So I did a lot of digging on how mosquitto bridges avoid message storms and loops. For example, if we have two mosquitto's pointing to each other as bridges and the bridges are to forward all data without topic remapping, then there will be a message storm because every message will keep going back and forth between the two brokers. Now mosquitto solves this problem by creating something called bridge mode. The solution is described [here](https://groups.google.com/forum/#!topic/mqtt/rIp1uJsT9Nk) in the 4th post by the author of mosquitto. This solution is implemented in the [paho python library](https://github.com/eclipse/paho.mqtt.python/blob/a8b2b4d039571e9bd873dd550a1dddabc6d3cb61/src/paho/mqtt/client.py#L1256) as well. However, when I run the following code with emqx broker, I end up getting my own message back to me

```
import paho.mqtt.client as mqtt
from time import sleep

def on_connect(client, userdata, flags, rc):
    print("Connected with result code "+str(rc))
    # subscribing
    client.subscribe("123")
    # now publishing
    client.publish("123", "456")

def on_message(client, userdata, msg):
    print(msg.topic+" "+str(msg.payload))

client = mqtt.Client()
client.enable_bridge_mode()
client.on_connect = on_connect
client.on_message = on_message

client.connect("127.0.0.1", 1885, 60)

client.loop_start()

while True:
    sleep(5)
```
A few questions:

How does emqx avoid loop avoidance problem?

[This](https://emqx-enterprise-docs-en.readthedocs.io/en/latest/_images/bridges_4.png) image shows how mosquitto is bridging to emqx, in this case from my understanding, sensor will send a message to mosquitto which will then forward it to emqx, then emqx will send that message to both brokers and the sensor from which the data originated will get the data back. The the emqx will get that message and forward to both mosquittos, thus creating an endless message storm. How to solve this problem of loopback?

Is emqx going to support the solution implemented by mosquitto and python library?

**Comment by Gilbert-Wong** [comment]
Hi, @vrst37 , emqx has supported bridge mode and the feature you want. You can just  set config entry `mqtt.ignore_loop_deliver` as true to resolve your problem.

**Comment by vrst37** [comment]
Ok, now if I set this config option, then it will impact all clients. Is there a solution where the setting is modified for specific clients only. For example, in mosquitto, I can set bridge mode from client side thus declaring that I do not want my own messages (breaking mqtt compliance) however, if I want my own messages, then I can just run in regular mode.

**Comment by Gilbert-Wong** [comment]
Sorry for the late response, @vrst, the problem you referred indeed exists. I'll fix this problem as soon as possible.

**Comment by turtleDeng** [comment]
Thank you for your participation, emqx4.x has optimized message bridging, welcome to use.
