### ISSUE TITLE
emqx node auto discovery via etcd is not available on v3.1.0

### ISSUE THREAD

**Issue by HarveyHu-CN** [emqx/emqx#2519]
#### Environment

- OS:  Amazon Linux 2  [4.14.114-103.97.amzn2.x86_64]
- Erlang/OTP:  Erlang/OTP 21 [erts-10.3.4]
- EMQ:  v3.1.0

#### Description

I use etcd cluster to do node discovery.
etcd config info:
![image](https://user-images.githubusercontent.com/11242211/57356640-8e266680-71a3-11e9-8c99-0db6991ff1e0.png)

cluster name:
![image](https://user-images.githubusercontent.com/11242211/57356671-a302fa00-71a3-11e9-81ea-f196f0e659d0.png)

node info:
![image](https://user-images.githubusercontent.com/11242211/57356690-b44c0680-71a3-11e9-9aee-a7b84b733569.png)

the emqx node do have connection to etcd cluster via port 2379

but when I start both nodes, and check the cluster status, the nodes did not join to one cluster as expected.

then I check the key-pair info in etcd cluster, as following:
![image](https://user-images.githubusercontent.com/11242211/57356994-61bf1a00-71a4-11e9-8a65-71ef1cbb7ea0.png)

node  info does not exist in the etcd, but prefix and cluster name are created, which is strange.

then I did one more test on v3.0.1,   there is no issue however:
![image](https://user-images.githubusercontent.com/11242211/57357078-b19de100-71a4-11e9-98c3-68168bd18299.png)

so I suspect something went wrong on v3.1.0 concerning about etcd auto discovery.

thanks

**Comment by zhanghongtong** [comment]
Sorry to reply so lately, how do you install emqx, we have not released the `Amazon Linux 2` package

**Comment by HarveyHu-CN** [comment]
Hello

I compile emqx from source code based on repo:  https://github.com/emqx/emqx-rel  and tag v3.1.0.

One customized plugin is included in, aiming to transfer messages to redis, which should not cause this issue, I think.

**Comment by zhanghongtong** [comment]
It is recommended that you rebuild the EMQX using the v3.1.1 tag. You need to set the environment variable `EMQX_DEPS_DEFAULT_VSN=v3.1.1 ` before building.

**Comment by HarveyHu-CN** [comment]
Hi there

I remove the old code and tried to recompile emqx v3.1.1 from the beginning as you said.
The issue remains.

I  also tried to repeat these operations on a centos machine.
The issue remains.

I think you can reproduce this issue very easily.

Thanks

**Comment by zhanghongtong** [comment]
@HarveyHu-CN I use docker to execute the etcd cluster, it is normal, like the following
```
$ sudo docker run -d --rm -e EMQX_CLUSTER__DISCOVERY=etcd -e EMQX_CLUSTER__ETCD__SERVER=http://172.31.16.195:2379 -e EMQX_CLUSTER__ETCD__NODE_TTL=1m -e EMQX_NAME=emqx  emqx/emqx:v3.1.1
cc4e9136e7b645568c94c4cc8b31f045a788cb8c86d1150d514db284cd11dedb

$ sudo docker run -d --rm -e EMQX_CLUSTER__DISCOVERY=etcd -e EMQX_CLUSTER__ETCD__SERVER=http://172.31.16.195:2379 -e EMQX_CLUSTER__ETCD__NODE_TTL=1m -e EMQX_NAME=emqx  emqx/emqx:v3.1.1
9598284ea03d89e5759da70c95e67f939707d9f4e11bb7e16237326982457703

$ sudo docker exec 95982 sh -c "emqx_ctl cluster status"
Cluster status: [{running_nodes,['emqx@172.17.0.2','emqx@172.17.0.3']}]
```

Then I tried to build emqx on ubuntu18.04 using v3.1.1 tag and execute etcd cluster, it can also work.

**Comment by HarveyHu-CN** [comment]
sorry,  my bad. 
v3.1.1 seems ok on this issue.

but if two nodes have different versions, the latter one would fail to join the cluster and go to a crash.
env: one v3.1.1 and one v3.0.1

first time to start from cmd line:
![image](https://user-images.githubusercontent.com/11242211/57999229-3c68cf00-7b07-11e9-997e-586ac6b0ba03.png)

![image](https://user-images.githubusercontent.com/11242211/57999238-468acd80-7b07-11e9-8d95-5dcff863932b.png)

second time to start from cmd line:
![image](https://user-images.githubusercontent.com/11242211/57999250-51456280-7b07-11e9-8e5f-1db61c0a1941.png)

maybe an incompatible issue between two versions.

For another thing:

EVN: two nodes of v3.1.1 and use etcd as auto discovery service, 
When the second node joined the cluster, the following promt would be printed on the fist node in cluster.

![image](https://user-images.githubusercontent.com/11242211/57999405-e3e60180-7b07-11e9-86b6-0b081e8cfcc7.png)

But currently, everything seems fine.

**Comment by zhanghongtong** [comment]
Our cluster function does not support cross-versions for the time being, we recommend that you use v3.1.1 all.
