### ISSUE TITLE
”timeout of 10000ms exceeded“ when load emqx_auth_mysql plugin

### ISSUE THREAD

**Issue by mozaiquan** [emqx/emqx#2524]
#### Environment

- OS: Ubuntu 18.04.1 LTS
- Erlang/OTP: 
- EMQ: v3.1.0

#### Description

When try to start emqx_auth_mysql plugin from dashboard, there is an error saying ”timeout of 10000ms exceeded“, can the number of timeout be changed?

![超时](https://user-images.githubusercontent.com/4318394/57432367-4289c080-7268-11e9-82de-ada2e7101c6f.png)

**Comment by Gilbert-Wong** [comment]
Hi, @mozaiquan , which mysql version do you use?

**Comment by mononym** [comment]
Closing due to no response for important question for us to provide support.
