### ISSUE TITLE
Problems with HTTP API usage

### ISSUE THREAD

**Issue by gary101** [emqx/emqx#2525]
#### Environment

- OS: Win7
- Erlang/OTP: 
- EMQ: v3.0.1

#### Description
I am a fresh for EMQX, when I read the docs for Rest API, I'm very confused since the API just show the result for each api but no detail description for how to call rest api and send request with parameters.

For example, if I want to send message using api, is there any example code?

Could you please give me some more detailed reference or example? Thanks a lot!

*A description of the issue*

**Comment by gary101** [comment]
Could you please give me some example or reference for more detail documents with how to send api request with parameters for different api? Thanks a lot.

**Comment by turtleDeng** [comment]
https://developer.emqx.io/docs/broker/v3/en/rest.html#publish-message
