### ISSUE TITLE
Broker is failing

### ISSUE THREAD

**Issue by kort3z** [emqx/emqx#2526]
#### Environment

- OS: Official Docker container emqx/emqx:v3.0.0-amd64 in GKE Cluster

Variables : 

```
EMQX_NAME:                                  emqtt
EMQX_CLUSTER__DISCOVERY:                    k8s
EMQX_CLUSTER__K8S__APISERVER:               https://kubernetes.default:443
EMQX_CLUSTER__K8S__NAMESPACE:               default
EMQX_CLUSTER__K8S__SERVICE_NAME:            emqtt
EMQX_CLUSTER__K8S__ADDRESS_TYPE:            ip
EMQX_CLUSTER__K8S__APP_NAME:                emqtt
EMQX_NODE__PROCESS_LIMIT:                   2097152
EMQX_MAX_PORT:                              1048576
EMQX_NODE__COOKIE:                          secretcookie
EMQX_CLUSTER__NAME:                         emqcl
EMQX_CLUSTER__AUTOHEAL:                     on
EMQX_CLUSTER__AUTOCLEAN:                    5m
EMQX_MQTT__ALLOW_ANONYMOUS:                 false
EMQX_MQTT__MAX_PACKET_SIZE:                 256MB
EMQX_LOADED_PLUGINS: emqx_management,emqx_recon,emqx_retainer,emqx_dashboard,emqx_auth_http
EMQX_RETAINER__STORAGE_TYPE:                disc
EMQX_RETAINER__MAX_MESSAGE_NUM:             10000
EMQX_RETAINER__MAX_PAYLOAD_SIZE:            64KB
EMQX_RETAINER__EXPIRY_INTERVAL:             0
EMQX_LISTENER__SSL__EXTERNAL__KEYFILE:      /cert/tls.key
EMQX_LISTENER__SSL__EXTERNAL__CERTFILE:     /cert/tls.crt
EMQX_LISTENER__SSL__EXTERNAL__CACERTFILE:   /cert/tls.crt
EMQX_LISTENER__TCP__EXTERNAL__ACCEPTORS:    64
EMQX_LISTENER__TCP__EXTERNAL__MAX_CLIENTS:  1000000`
```

#### Description

Hi, 

We have a problem with the EMQX broker.
It seems that randomly in time, it starts to behave erratically.

I feel that this problem only happens when there is more than one node.

In attachment, my log file.
[emqx.logs.txt](https://github.com/emqx/emqx/files/3161714/emqx.logs.txt)

If you need more information, do not hesitate to ask.

**Comment by zhanghongtong** [comment]
Sorry to reply so late. It seems that emqx can't get the information of other nodes through k8s apiserver, please confirm whether the emqx pods can access apiserver normally, or you can use helm to deploy emqx cluster, we have [emqx-chart](https://github.com/emqx/emqx-chart)

**Comment by kort3z** [comment]
Hello,
I can confirm that the pods communicate with each other at least initially. Then at a random time I get this error.
I am in GKE 1.12.7-gke.10 with 3 nodes n1-standard-4.

**Comment by zhanghongtong** [comment]
The error record of the log indicates that the `emqtt@10.20.0.64` emqx broker information cannot be obtained through the k8s apiserver, please check it.

**Comment by HJianBo** [comment]
Hi, @kort3z Is the problem has solved?

**Comment by mononym** [comment]
Given the request for further confirmation and clarification about the ability to communicate through the k8s api server has not been answered in some time we're closing this. Please reopen if the issue appears again.
