### ISSUE TITLE
Information or guide for porting to an embedded target

### ISSUE THREAD

**Issue by gabrielrivas** [emqx/emqx#2528]
#### Environment

- OS: Linux
- Erlang/OTP: 21
- EMQ: 3.1.0

#### Description
Hello, 
Do you have any document or guide on how to port EMQX to any target platform? I would like to run it on some embedded ARM platforms. If you happen to provide a Yocto/Bitbake recipe would be really good.

**Comment by zhanghongtong** [comment]
On the ARM platform we recommend using the docker image to deploy emqx, such as emqx/emqx:v3.1.1-arm64v8, you can get them on the [docker hub](https://hub.docker.com/r/emqx/emqx/tags)

**Comment by NikolayVasilyev** [comment]
Have the same question with ARM platforms.
What to do if `docker` may not be used for some reasons, like limited kernel support or performance issues.

**Comment by zhanghongtong** [comment]
@NikolayVasilyev At present, our ARM platforms only have raspberry platforms in support, while we have no support in other platforms. Maybe you can [download our projects and build them](https://developer.emqx.io/docs/broker/v3/en/install.html#source-code-compilation-and-installation)

**Comment by mononym** [comment]
You can find an article on using EMQX with Nerves for embedded devices [here](https://github.com/savonarola/mqtt-article).
