### ISSUE TITLE
how can i change the max_fds as i deployed the emqx in k8s

### ISSUE THREAD

**Issue by ysyh15** [emqx/emqx#2533]
#### Environment

- OS:  centos 7
- Erlang/OTP: 
- EMQ:  v3.0.1

#### Description

as title

**Comment by ysyh15** [comment]
or some doc ? thx a lot

**Comment by HJianBo** [comment]
If you want to change the `max_fds` value only, just setting it by the `ulimit -n` command.

Furthermore, you can tune your machine by this guide: https://developer.emqx.io/docs/broker/v3/en/tune.html

**Comment by ysyh15** [comment]
so i should setting the command to every pod?  maybe  add sth to the k8s env config can solve it?

**Comment by ysyh15** [comment]
and i wanne know why the max_fds value is deffrent  between 3 pod?
![image](https://user-images.githubusercontent.com/27407491/57605624-a6c6c000-7599-11e9-99de-6ab78a9c91fd.png)

**Comment by zhanghongtong** [comment]
@ysyh15 You can view the kubernetes documentation https://kubernetes.io/docs/tasks/administer-cluster/sysctl-cluster/

**Comment by ysyh15** [comment]
> @ysyh15 You can view the kubernetes documentation https://kubernetes.io/docs/tasks/administer-cluster/sysctl-cluster/

thx, that is helpful,i will try
