### ISSUE TITLE
bench mark QPS information?

### ISSUE THREAD

**Issue by zz-mars** [emqx/emqx#2535]
#### Environment

- OS: 
- Erlang/OTP: 
- EMQ: 

#### Description

*A description of the issue*

is there any qps information for emq? e.g. how many upload publish & download publish packet can be processed by emq?

**Comment by tigercl** [comment]
@zz-mars I am so sorry for replying you so late. For your question, you can get QPS information in [here](https://emq-xmeter-benchmark-cn.readthedocs.io/en/latest/).
