### ISSUE TITLE
a node in a cluster fails to join the cluster

### ISSUE THREAD

**Issue by omere2** [emqx/emqx#2540]
#### Environment

- OS:  docker emqx/emqx:v3.1-rc.3
- Erlang/OTP: R21/10.2.1
- EMQ: v3.1-rc.3

#### Description

Testing a cluster with a few nodes. Deleted a few nodes, and one of the nodes keep trying to connect to the old cluster - does not discover the cluster has changed.

Desired: 6 nodes in a cluster
Actual: 5 nodes in the cluster, 1 node thinks the old cluster is dead and is alone.

Logs from the isolated node:
`2019-05-15 12:36:47.788 [error] Mjg3Mzg2MDQ0NDUzMjQ2MTU3MDYzNzU1NTE5NDM1NzM1MDE@10.0.18.185:37464 [Broker] Failed to forward msg to emqx@10.0.47.45: ehostunreach
2019-05-15 12:36:52.789 [error] event=connect_to_remote_server peer="emqx@10.0.25.194" result=failure reason="timeout"
2019-05-15 12:36:52.789 [error] Mjg3Mzg2MDQ2Njc3MjM0MTM3NTI3MDkyOTE4NDk5NDA5OTC@10.0.14.162:47910 [Broker] Failed to forward msg to emqx@10.0.25.194: timeout
Lock owner DOWN: <0.3342.0>
2019-05-15 12:36:57.791 [error] event=connect_to_remote_server peer="emqx@10.0.25.194" result=failure reason="timeout"
2019-05-15 12:36:57.791 [warning] [Alarm Handler] {cpu_high_watermark,100.0} set
2019-05-15 12:36:57.792 [error] Mjg3Mzg2MDQ2Nzk5MTY4NTkxNTkzODM4OTUxNDc4MDY3MjA@10.0.44.146:53024 [Broker] Failed to forward msg to emqx@10.0.25.194: timeout
Lock owner DOWN: <0.3392.0>
2019-05-15 12:37:02.793 [error] event=connect_to_remote_server peer="emqx@10.0.25.194" result=failure reason="timeout"
2019-05-15 12:37:02.793 [error] Mjg3Mzg2MDQ2ODEwNzY3MTY2Mzk3NjI0NTY5Mjk3NjMzMjI@10.0.44.146:55260 [Broker] Failed to forward msg to emqx@10.0.25.194: timeout
Lock owner DOWN: <0.3614.0>
2019-05-15 12:37:07.794 [error] event=connect_to_remote_server peer="emqx@10.0.25.194" result=failure reason="timeout"
2019-05-15 12:37:07.794 [error] Mjg3Mzg2MDQ2ODE3ODQ5NjA5MzE3Mjg0NjE0NjM4Nzk2ODA@10.0.0.101:60698 [Broker] Failed to forward msg to emqx@10.0.25.194: timeout
Lock owner DOWN: <0.3757.0>
Lock owner DOWN: <0.6790.0>
2019-05-15 12:37:12.795 [error] event=connect_to_remote_server peer="emqx@10.0.25.194" result=failure reason="timeout"
2019-05-15 12:37:12.795 [error] Mjg3Mzg2MDQ2ODAxODAzMzQwMDQ5ODg2ODg2NzgzMjIxNzG@10.0.14.162:48236 [Broker] Failed to forward msg to emqx@10.0.25.194: timeout
Lock owner DOWN: <0.3465.0>
2019-05-15 12:37:57.792 [warning] [Alarm Handler] {cpu_high_watermark,100.0} set`

Cluster status on isolated node:
`/opt/emqx $ emqx_ctl cluster status
Cluster status: [{running_nodes,['emqx@10.0.3.60']},
                 {stopped_nodes,['emqx@10.0.25.10','emqx@10.0.10.244']}]`

Cluster status on a joined node:
`/opt/emqx $ emqx_ctl cluster status
Cluster status: [{running_nodes,['emqx@10.0.3.31','emqx@10.0.1.90',
                                 'emqx@10.0.10.29','emqx@10.0.13.254',
                                 'emqx@10.0.10.30']}]`

**Comment by omere2** [comment]
docker configuration:
ENV EMQX_CLUSTER__NAME=emqx
ENV EMQX_JOIN_CLUSTER=emqx
ENV EMQX_CLUSTER__DISCOVERY=k8s
ENV EMQX_CLUSTER__K8S__APISERVER=https://kubernetes.default:443
ENV EMQX_CLUSTER__K8S__SERVICE_NAME=emqx
ENV EMQX_CLUSTER__K8S__ADDRESS_TYPE=ip
ENV EMQX_CLUSTER__K8S__APP_NAME=emqx
ENV EMQX_CLUSTER__K8S__NAMESPACE=default
ENV EMQX_NAME=emqx
ENV EMQX_LOG__TO=console
ENV EMQX_LOG__LEVEL=notice
ENV EMQX_LOADED_PLUGINS="emqx_management,emqx_recon,emqx_retainer,emqx_dashboard,emqx_auth_http"
ENV EMQX_MQTT__IGNORE_LOOP_DELIVER=true
ENV EMQX_NODE__HEARTBEAT=on

**Comment by zhanghongtong** [comment]
Please confirm that the communication before your pods is normal, it seems that emqx can not connect to the node ` emqx@10.0.25.194`
About deploying emqx clusters through k8s, we recommend using helm to deploy, you can check out https://github.com/emqx/emqx-chart

**Comment by omere2** [comment]
No, the node emqx@10.0.25.194 was already destroyed and rotated, but the isolated node failed to discover the new cluster.

**Comment by zhanghongtong** [comment]
I can't reproduce this problem. I used [emqx-chart](https://github.com/emqx/emqx-chart) to deploy six emqx nodes. After they run, I deleted a pods. The deployment automatically creates new pods. The emqx cluster works normally.
```
$ helm install --set deployment.replicaCount=6 --set deployment.image=emqx/emqx:v3.1-rc.3 .
NAME:   wrinkled-cheetah
LAST DEPLOYED: Mon May 20 07:25:49 2019
NAMESPACE: default
STATUS: DEPLOYED

RESOURCES:
==> v1/ConfigMap
NAME                             DATA  AGE
wrinkled-cheetah-emqx-chart-env  0     0s

==> v1/Pod(related)
NAME                                          READY  STATUS             RESTARTS  AGE
wrinkled-cheetah-emqx-chart-5d559f646f-8mdxc  0/1    ContainerCreating  0         0s
wrinkled-cheetah-emqx-chart-5d559f646f-8v7z4  0/1    ContainerCreating  0         0s
wrinkled-cheetah-emqx-chart-5d559f646f-bnbpm  0/1    ContainerCreating  0         0s
wrinkled-cheetah-emqx-chart-5d559f646f-ktb8d  0/1    ContainerCreating  0         0s
wrinkled-cheetah-emqx-chart-5d559f646f-l5dcq  0/1    ContainerCreating  0         0s
wrinkled-cheetah-emqx-chart-5d559f646f-zkjf5  0/1    ContainerCreating  0         0s

==> v1/Service
NAME                         TYPE       CLUSTER-IP    EXTERNAL-IP  PORT(S)                                                 AGE
wrinkled-cheetah-emqx-chart  ClusterIP  10.101.6.141  <none>       1883/TCP,8883/TCP,8080/TCP,8083/TCP,8084/TCP,18083/TCP  0s

==> v1/ServiceAccount
NAME                         SECRETS  AGE
wrinkled-cheetah-emqx-chart  1        0s

==> v1beta1/Role
NAME                         AGE
wrinkled-cheetah-emqx-chart  0s

==> v1beta1/RoleBinding
NAME                         AGE
wrinkled-cheetah-emqx-chart  0s

==> v1beta2/Deployment
NAME                         READY  UP-TO-DATE  AVAILABLE  AGE
wrinkled-cheetah-emqx-chart  0/6    6           0          0s
```
```
$ kubectl get pods
NAME                                           READY   STATUS    RESTARTS   AGE
wrinkled-cheetah-emqx-chart-5d559f646f-8mdxc   1/1     Running   0          24s
wrinkled-cheetah-emqx-chart-5d559f646f-8v7z4   1/1     Running   0          24s
wrinkled-cheetah-emqx-chart-5d559f646f-bnbpm   1/1     Running   0          24s
wrinkled-cheetah-emqx-chart-5d559f646f-ktb8d   1/1     Running   0          24s
wrinkled-cheetah-emqx-chart-5d559f646f-l5dcq   1/1     Running   0          24s
wrinkled-cheetah-emqx-chart-5d559f646f-zkjf5   1/1     Running   0          24s

$ kubectl exec -it wrinkled-cheetah-emqx-chart-5d559f646f-8mdxc sh
/opt/emqx # emqx_ctl cluster status
Cluster status: [{running_nodes,['emqx@10.244.2.12','emqx@10.244.1.12',
                                 'emqx@10.244.2.11','emqx@10.244.2.13',
                                 'emqx@10.244.1.14','emqx@10.244.1.13']}]

$ kubectl delete pods wrinkled-cheetah-emqx-chart-5d559f646f-zkjf5
pod "wrinkled-cheetah-emqx-chart-5d559f646f-zkjf5" deleted

$ kubectl get pods
NAME                                           READY   STATUS    RESTARTS   AGE
wrinkled-cheetah-emqx-chart-5d559f646f-8mdxc   1/1     Running   0          12m
wrinkled-cheetah-emqx-chart-5d559f646f-8v7z4   1/1     Running   0          12m
wrinkled-cheetah-emqx-chart-5d559f646f-bnbpm   1/1     Running   0          12m
wrinkled-cheetah-emqx-chart-5d559f646f-ktb8d   1/1     Running   0          12m
wrinkled-cheetah-emqx-chart-5d559f646f-l5dcq   1/1     Running   0          12m
wrinkled-cheetah-emqx-chart-5d559f646f-tl97f   1/1     Running   0          11m

$ kubectl exec -it wrinkled-cheetah-emqx-chart-5d559f646f-8mdxc sh
/opt/emqx # emqx_ctl cluster status
Cluster status: [{running_nodes,['emqx@10.244.2.14','emqx@10.244.2.12',
                                 'emqx@10.244.1.12','emqx@10.244.2.11',
                                 'emqx@10.244.1.14','emqx@10.244.1.13']},
                 {stopped_nodes,['emqx@10.244.2.13']}]
```

**Comment by appdog** [comment]
@zhanghongtong I can confirm we are experiencing the same problem as @omere2 

The only difference is that we set a custom name for `EMQX_CLUSTER__K8S__APP_NAME` and we have a `replicaCount` of 4.

**Comment by appdog** [comment]
Following up on the same issue; we did helm upgrade the nodes could not join the cluster even though we could see 4 pods. When trying to join the nodes using CLI manually we also encountered some issues. When adding the third node, one of the two first was replaced. We ended up reducing the replicaCount 2 for adding nodes manually to work.

**Comment by devrimbaris** [comment]
I am using a 3 node emqx broker with static setup and having the same issue.  For test purposes, I am shutting down network interface. The working nodes do not list the disconnected node  stopped. The disconnected node lists itself as the only working node.

cluster.autoheal = on
cluster.autoclean = 5m

After reconnecting the network interface, nothing is healed. The previously disconnected node does not join the cluster and to make things worse it accepts connections which is not good for our scenarios.
IS this expected behaviour?
