### ISSUE TITLE
Running a load test on a cluster results of all connections to drop with 'Lock owner DOWN' log error

### ISSUE THREAD

**Issue by omere2** [emqx/emqx#2541]
#### Environment

- OS: official docker
- Erlang/OTP: R21/10.2.1
- EMQ: v3.1-rc.3

#### Description

While running a load test (96k connections) on 3 emqx nodes in a cluster, the cluster doesn't hold and all connections drop.
The logs for all pods show hundreds of lines of the following:
`Lock owner DOWN: <40999.14400.15>
Lock owner DOWN: <0.13347.17>
Lock owner DOWN: <40999.7875.15>
Lock owner DOWN: <40999.15326.15>
Lock owner DOWN: <40999.32495.15>
Lock owner DOWN: <40899.13956.18>
Lock owner DOWN: <40999.32161.15>
Lock owner DOWN: <40999.16577.15>
Lock owner DOWN: <40999.31313.15>
Lock owner DOWN: <40999.31520.15>
Lock owner DOWN: <40999.5777.15>
Lock owner DOWN: <40999.10823.15>
Lock owner DOWN: <40999.31343.15>
Lock owner DOWN: <40899.16092.18>`

Docker configuration:
`ENV EMQX_CLUSTER__NAME=emqx
ENV EMQX_JOIN_CLUSTER=emqx
ENV EMQX_CLUSTER__DISCOVERY=k8s
ENV EMQX_CLUSTER__K8S__APISERVER=https://kubernetes.default:443
ENV EMQX_CLUSTER__K8S__SERVICE_NAME=emqx
ENV EMQX_CLUSTER__K8S__ADDRESS_TYPE=ip
ENV EMQX_CLUSTER__K8S__APP_NAME=emqx
ENV EMQX_CLUSTER__K8S__NAMESPACE=default
ENV EMQX_NAME=emqx
ENV EMQX_LOG__TO=console
ENV EMQX_LOG__LEVEL=notice
ENV EMQX_LOADED_PLUGINS="emqx_management,emqx_recon,emqx_retainer,emqx_dashboard"
ENV EMQX_MQTT__IGNORE_LOOP_DELIVER=true
ENV EMQX_NODE__HEARTBEAT=on`

**Comment by zhanghongtong** [comment]
Sorry for the late reply. What is the hardware configuration of the cluster? Is there a 'resource' setting for K8s pods?

**Comment by HJianBo** [comment]
Hi, @omere2 I'm very sorry for the late reply.  I'll close it first due to outdated.

If you have any questions, Plz reopen a it or open a new issue.
