### ISSUE TITLE
username/password and ACL

### ISSUE THREAD

**Issue by archerian** [emqx/emqx#2542]
#### Environment

- OS: Windows 
- Erlang/OTP: R21
- EMQ: 3.1.1

#### Description

I see in the ACL that it is possible to restrict access to topics via username/IP etc. But if I turn on emqx_auth_username then the ACL is not read. How to have BOTH authentication via username/password and topic authorization via ACL?

**Comment by archerian** [comment]
Isnt this a bug and not a support label? I'm thinking EMQX is supposed to offer both authentication and authorization and not only one?

**Comment by HJianBo** [comment]
Duplicated #2555
