### ISSUE TITLE
Client can't subscribe topic if the cleansession set false

### ISSUE THREAD

**Issue by zhang-yuxiang** [emqx/emqx#2543]
#### Environment

- OS: linux 
- Erlang/OTP: R21/10.3.2
- EMQ: v3.1.1

#### Description

When I set the connection option "clean Session" to false, the client can connect to the broker, but can't subscribe to the topic.

client:firmware or netty-based client .
Log as shown(trace client log):
cleanSession = true
![image](https://user-images.githubusercontent.com/26926467/57833828-8a22c600-77ed-11e9-9ffe-ae9d19468093.png)
cleanSession = false
![image](https://user-images.githubusercontent.com/26926467/57833935-bf2f1880-77ed-11e9-89c0-be2704a21c56.png)

**Comment by tigercl** [comment]
Hi, @zhang-yuxiang. Sorry for later reply, I didn't recurrence the issue you describe. Do you receive the SUBACK packet when 'Clean Session' is false and what's the reason code if you get it?

**Comment by zhang-yuxiang** [comment]
你好，我英语不好，所以用中文回复。之前在官方群中提到过这个问题，官方群一中的“波涛使者”已经复现了这个问题，复现除了github提到的条件外，还必须是restart emqx，如果是正常stop再start是没有问题的，有问题的是时候，是不会收到suback的，还有就是如果把emqx.conf文件中的session_registry关了，也没有问题，问题细节如果可以的话，可以问下“波涛使者”。谢谢！




------------------ 原始邮件 ------------------
发件人: "tigercl"<notifications@github.com>;
发送时间: 2019年7月1日(星期一) 中午11:22
收件人: "emqx/emqx"<emqx@noreply.github.com>;
抄送: "张玉祥"<1713522776@qq.com>;"Mention"<mention@noreply.github.com>;
主题: Re: [emqx/emqx] Client can't subscribe topic if the cleansession setfalse (#2543)




Hi, @zhang-yuxiang. Sorry for later reply, I didn't recurrence the issue you describe. Do you receive the SUBACK packet when 'Clean Session' is false and what's the reason code if you get it?

**Comment by HJianBo** [comment]
Yeah, it has fixed at https://github.com/emqx/emqx/commit/f46205daff6f102b1cac0207ecce36bdaaa74256 and released at v3.2.rc.2. You can try it!

Just close it first. If has any problems, let me know :)

**Comment by zhang-yuxiang** [comment]
好的，谢谢！




------------------ 原始邮件 ------------------
发件人: "JianBo He"<notifications@github.com>;
发送时间: 2019年7月1日(星期一) 下午2:26
收件人: "emqx/emqx"<emqx@noreply.github.com>;
抄送: "张玉祥"<1713522776@qq.com>;"Mention"<mention@noreply.github.com>;
主题: Re: [emqx/emqx] Client can't subscribe topic if the cleansession setfalse (#2543)




Yeah, it has fixed at f46205d and released at v3.2.rc.2. You can try it!
 
Just close it first. If has any problems, let me know :)
