### ISSUE TITLE
Connections page doesn't show all connections of a cluster when "All Nodes" is selected

### ISSUE THREAD

**Issue by FrederikP** [emqx/emqx#2544]
### Expected behavior

All connections of the cluster are shown when "All Nodes" is selected on the "Connections" page.

In my example I expect all three connections shown.

### Actual behavior

Only the connections of one machine are shown when "All Nodes" is selected. Selecting each node individually shows the correct connections per node.

In my example only one connection is shown, even though three exist.

You can see what I mean in this screencast:

![emqx-connections](https://user-images.githubusercontent.com/483596/57846240-0e684f80-77d4-11e9-8d1a-eabe94f354db.gif)

### EMQ version
v.3.1.0

### Docker version

Which docker-engine version?

```bash
Docker version 19.03.0-beta4, build e4666ebe81
```

### System

Running three nodes locally using docker-compose. They connect to each other successfully and pubsub works as expected (also for shared subscriptions).

### Hardware

My laptop (8 cores, 16G RAM)

If this is intended behavior, I would be grateful for an explanation. Thanks!

**Comment by Gilbert-Wong** [comment]
Hi, @FrederikP, our team has discussed the feature you want. There are some problems which block us to implement this feature. For example, if there are a lot of connections in different nodes. How do we present the connections on the web page, how do we page these connections? Anyway, this feature is exactly important and we'll do our best to implement it as we can.

**Comment by FrederikP** [comment]
Okay thanks. Sounds good.

I was just confused that the drop-down option says "All Nodes". That made me expect to show connections from all nodes. So I thought this was a bug and not a missing feature.

**Comment by Gilbert-Wong** [comment]
Finally, we decide to remove the `all nodes` option in the dashboard.

**Comment by FrederikP** [comment]
Okay, at least it's not so confusing I guess :)
