### ISSUE TITLE
ACL subscribe check uses invalid access value

### ISSUE THREAD

**Issue by foobarto** [emqx/emqx#2545]
#### Environment

- OS: Linux
- Erlang/OTP: 
- EMQ: 3.1.1

#### Description

With release of v3.1.1 I've noticed that a subscriber restricted by ACL only to sub to a topic stopped receiving any messages. It connected correctly but subscribing to a topic results in no feedback and no messages received.

I'm using a custom HTTP ACL backend and noticed that the `access` value for subscription requests is now `2`  - same as requests to publish to a topic.

Rolling back to v3.1.0 resolved this issue for me for now where `access` value for subscription is `1`.

**Comment by phanimahesh** [comment]
Found and fixed in https://github.com/emqx/emqx/commit/37784a76fa971199cb86a0e48083eaf6bd957d95

This was affecting all acl plugins. v3.1.1 fixed it, v3.1.0 had the bug.

Are you sure that the issue happens in 3.1.1 and not on 3.1.0?

**Comment by foobarto** [comment]
Positive. The bug is present in emqx/emqx:latest Docker image released
earlier today which is v3.1.1 and working correctly in tag v3.1.0

**Comment by HJianBo** [comment]
Hi, @foobarto Sorry for late reply.

I tested 3.1.0 and 3.1.1 image, and both of their access values returned 1. So both worked fine for me.

Then, I have checked the release note. This fix https://github.com/emqx/emqx/commit/37784a76fa971199cb86a0e48083eaf6bd957d95 was first released on v3.1-rc.1. So, the above tested behavior are correct.

**Comment by HJianBo** [comment]
Close it due to outdated. Thanks guys
