### ISSUE TITLE
External Network Settings

### ISSUE THREAD

**Issue by Schweig** [emqx/emqx#2550]
#### Environment

- OS: Ubuntu 18.04
- Erlang/OTP: R21/10.0.5
- EMQ: v3.0-rc.5

#### Description

*A description of the issue*
I currently have an emqx server running on an aws instance with devices sending messages once every 20 seconds and I am having many devices report that the keepalive_timeout is being triggered and they are disconnecting and then reconnecting as the paho cpp mqtt library has automatic reconnect functionality. Is there any other networking settings for the client that are needed for the devices to communicate stably with the cloud?

**Comment by Gilbert-Wong** [comment]
Hello, @Schweig, you can increase the keepalive value of your `MQTT` client or decrease the default `keepalive` value of the emqx instance to solve your problem.

**Comment by Gilbert-Wong** [comment]
Hi, @Schweig, has your problem been resolved?
