### ISSUE TITLE
How to change the port for the HTTP management or stop the http management service

### ISSUE THREAD

**Issue by mzy2240** [emqx/emqx#2552]
#### Environment

- OS: Windows, Debian 9
- Erlang/OTP: 
- EMQ: 3.1.1

#### Description

*A description of the issue*
In the emqx.conf, I am able to change the port like 1883, 18083, etc., however, for the http management port (8080), I did not find an option for changing that or shut down the service. Do you know the correct way to do that? Thanks!!

Also, for the emqx edge, can you give a config example that uses the minimal ram resource and only maintain the necessary service for the normal operation? Thank you in advance!!

**Comment by Gilbert-Wong** [comment]
Hi, @mzy2240, here it is.

![image](https://user-images.githubusercontent.com/20479699/57991541-37ddef80-7ae2-11e9-8fc0-db95c1b03789.png)

**Comment by mzy2240** [comment]
Hi @Gilbert-Wong,
Thank you for your reply. Is there also a way to turn off the http management service?

**Comment by HJianBo** [comment]
Just stop it using `emqx_ctl plugins unload emqx_management`

**Comment by Gilbert-Wong** [comment]
Sorry, @mzy2240, the HTTP management service is one of the essential components of emqx which used to provide rest API. Could you please tell me why you want to disable the emqx_management service?

**Comment by Gilbert-Wong** [comment]
So sad to tell you that the emqx_management plugin can not be unloaded for now.
<img width="756" alt="image" src="https://user-images.githubusercontent.com/20479699/61016352-e6573000-a3c1-11e9-9db1-6123214d0dcd.png">
