### ISSUE TITLE
cli mode client can't subscribe topic sometimes

### ISSUE THREAD

**Issue by nobject** [emqx/emqx#2553]
#### Environment

- OS: Centos 7.5
- Erlang/OTP: 
- EMQ: 3.0.1

#### Description

*A description of the issue*
I deploy cluster on my online environment, but it is unstabitily sometime.sometimes my client  reconnect but the subscription is failed and I use cli mode to subscribe to the topic ,the result shows ok, but actually，it is not subscribe successfully.  I can't find the reason why
![TIM截图20190520193041](https://user-images.githubusercontent.com/8804643/58018623-e2333280-7b35-11e9-98c9-78f7163f7b3e.png)

**Comment by HJianBo** [comment]
Hi, @nobject Sorry late reply there.

> sometimes my client reconnect but the subscription is failed

Can you paste the CONNECT parameters? i.e: cleansession etc.

(Some days ago, we find a BUG that the client connected with `cleansession=false` can not subscribe topic after executing `emqx restart` )

**Comment by HJianBo** [comment]
Hi, @nobject We have released this fix at v3.1.2. Please check it

Thanks!
