### ISSUE TITLE
Problems arising from using COAP protocol

### ISSUE THREAD

**Issue by chenguosi** [emqx/emqx#2554]
#### Environment

- OS: ubuntu18.4.1
- Erlang/OTP:  OPT21
- EMQ:   emqx-3.1.1

#### Description

*When I used emqx to publish COAP protocol requests, there was an error in the console, which was described as follows:

Erlang/OTP 21 [erts-10.0.1] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:32]

Starting emqx on node emqx@127.0.0.1
Start http:management listener on 8080 successfully.
Start http:dashboard listener on 18083 successfully.
=CRASH REPORT==== 20-May-2019::17:00:43.058000 ===
  crasher:
    initial call: lwm2m_coap_udp_socket:init/1
    pid: <0.397.0>
    registered_name: []
    exception error: no match of right hand side value {error,eaddrinuse}
      in function  lwm2m_coap_udp_socket:init/1 (src/lwm2m_coap_udp_socket.erl, line 51)
      in call from gen_server:init_it/2 (gen_server.erl, line 374)
      in call from gen_server:init_it/6 (gen_server.erl, line 342)
    ancestors: [lwm2m_coap_server,<0.387.0>]
    message_queue_len: 1
    messages: [{'$gen_cast',{set_pool,<0.388.0>}}]
    links: [<0.388.0>]
    dictionary: []
    trap_exit: true
    status: running
    heap_size: 610
    stack_size: 27
    reductions: 1039
  neighbours:

Start mqtt:tcp listener on 127.0.0.1:11883 successfully.
Start mqtt:tcp listener on 0.0.0.0:1883 successfully.
Start mqtt:ws listener on 0.0.0.0:8083 successfully.
Start mqtt:ssl listener on 0.0.0.0:8883 successfully.
Start mqtt:wss listener on 0.0.0.0:8084 successfully.
EMQ X Broker 3.1.1 is running now!
Eshell V10.0.1  (abort with ^G)
(emqx@127.0.0.1)1> =CRASH REPORT==== 20-May-2019::17:01:03.605000 ===
  crasher:
    initial call: emqx_coap_mqtt_adapter:init/1
    pid: <0.519.0>
    registered_name: []
    exception error: no case clause matching ok
      in function  emqx_protocol:send/2 (src/emqx_protocol.erl, line 691)
      in call from emqx_coap_mqtt_adapter:proto_init/5 (src/emqx_coap_mqtt_adapter.erl, line 258)
      in call from emqx_coap_mqtt_adapter:init/1 (src/emqx_coap_mqtt_adapter.erl, line 120)
      in call from gen_server:init_it/2 (gen_server.erl, line 374)
      in call from gen_server:init_it/6 (gen_server.erl, line 342)
    ancestors: [<0.518.0>,<0.516.0>,<0.515.0>,<0.377.0>,coap_server,
                  <0.374.0>]
    message_queue_len: 1
    messages: [{keepalive,start,90}]
    links: [<0.521.0>]
    dictionary: [{guid,{1558342863605000,268564305019399,0}},
                  {'$logger_metadata$',#{client_id => <<"client1">>}}]
    trap_exit: false
    status: running
    heap_size: 2586
    stack_size: 27
    reductions: 1892
  neighbours:

=ERROR REPORT==== 20-May-2019::17:01:03.605000 ===
** Generic server <0.521.0> terminating 
** Last message in was {'EXIT',<0.519.0>,
                           {{case_clause,ok},
                            [{emqx_protocol,send,2,
                                 [{file,"src/emqx_protocol.erl"},{line,691}]},
                             {emqx_coap_mqtt_adapter,proto_init,5,
                                 [{file,"src/emqx_coap_mqtt_adapter.erl"},
                                  {line,258}]},
                             {emqx_coap_mqtt_adapter,init,1,
                                 [{file,"src/emqx_coap_mqtt_adapter.erl"},
                                  {line,120}]},
                             {gen_server,init_it,2,
                                 [{file,"gen_server.erl"},{line,374}]},
                             {gen_server,init_it,6,
                                 [{file,"gen_server.erl"},{line,342}]},
                             {proc_lib,init_p_do_apply,3,
                                 [{file,"proc_lib.erl"},{line,249}]}]}}
** When Server state == {state,30000,true,#Fun<emqx_session.1.98926271>,
                               <<"client1">>,<<"GusChan">>,undefined,
                               undefined,1,0,#{},false,
                               {emqx_inflight,65535,{0,nil}},
                               0,undefined,
                               {mqueue,true,1000,0,0,none,0,{queue,[],[],0}},
                               #{},undefined,undefined,undefined,0,undefined,
                               true,undefined,undefined,
                               {1558,342863,598000},
                               undefined,undefined}
** Reason for termination == 
** {{case_clause,ok},
    [{emqx_protocol,send,2,[{file,"src/emqx_protocol.erl"},{line,691}]},
     {emqx_coap_mqtt_adapter,proto_init,5,
                             [{file,"src/emqx_coap_mqtt_adapter.erl"},
                              {line,258}]},
     {emqx_coap_mqtt_adapter,init,1,
                             [{file,"src/emqx_coap_mqtt_adapter.erl"},
                              {line,120}]},
     {gen_server,init_it,2,[{file,"gen_server.erl"},{line,374}]},
     {gen_server,init_it,6,[{file,"gen_server.erl"},{line,342}]},
     {proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,249}]}]}

=CRASH REPORT==== 20-May-2019::17:01:03.605000 ===
  crasher:
    initial call: emqx_session:init/1
    pid: <0.521.0>
    registered_name: []
    exception exit: {{case_clause,ok},
                     [{emqx_protocol,send,2,
                          [{file,"src/emqx_protocol.erl"},{line,691}]},
                      {emqx_coap_mqtt_adapter,proto_init,5,
                          [{file,"src/emqx_coap_mqtt_adapter.erl"},
                           {line,258}]},
                      {emqx_coap_mqtt_adapter,init,1,
                          [{file,"src/emqx_coap_mqtt_adapter.erl"},
                           {line,120}]},
                      {gen_server,init_it,2,
                          [{file,"gen_server.erl"},{line,374}]},
                      {gen_server,init_it,6,
                          [{file,"gen_server.erl"},{line,342}]},
                      {proc_lib,init_p_do_apply,3,
                          [{file,"proc_lib.erl"},{line,249}]}]}
      in function  gen_server:handle_common_reply/8 (gen_server.erl, line 751)
    ancestors: [emqx_session_sup,emqx_sm_sup,emqx_sup,<0.161.0>]
    message_queue_len: 0
    messages: []
    links: [<0.313.0>]
    dictionary: [{'$logger_metadata$',#{client_id => <<"client1">>}}]
    trap_exit: true
    status: running
    heap_size: 2586
    stack_size: 27
    reductions: 88853
  neighbours:

[log.txt](https://github.com/emqx/emqx/files/3200295/log.txt)

*

**Comment by Gilbert-Wong** [comment]
@chenguosi Thanks for your feedback, it is exactly a bug. We'll fix it in the `emqx` 3.2 release.

**Comment by HJianBo** [comment]
I think 3.1.2 is better

**Comment by Gilbert-Wong** [comment]
@chenguosi, It has been fixed and will be released with emqx 3.2.
