### ISSUE TITLE
Forcing TLS version for distribution

### ISSUE THREAD

**Issue by manolodd** [emqx/emqx#2562]
Hi,

please, could you tell me how to force distribution between emqx nodes in a cluster to be carried out using only tlsv1.2?

It's clear enough for TLS listeners, but I cannot find where to configure it for distribution. According to 
https://github.com/emqx/emqx-tutorial-en/blob/master/emq-distributed-tls.md there is not a place to set tls versions, isn't it?

My use case requires to be as closer as possible to PCI-DSS TLS requirements (https://blog.pcisecuritystandards.org/are-you-ready-for-30-june-2018-sayin-goodbye-to-ssl-early-tls) so, I've to be sure of the TLS version used in our whole stack.

Thanks in advance.

**Comment by HJianBo** [comment]
Hi, @manolodd I find the Erlang/OTP official document for Erlang Distributed TLS. it said:

> The options in the {server, Opts} tuple are used when calling ssl:ssl_accept/3, and the options in the {client, Opts} tuple are used when calling ssl:connect/4.
>    ----- *Ref by: http://erlang.org/doc/apps/ssl/ssl_distribution.html*

So according to [`Options` argument of `ssl:ssl_accept/3` function description](http://erlang.org/doc/man/ssl.html#ssl_accept-3) we can find the all supported options.

In a word, you can specify the TLS version using:
```erlang
[{server,
  [{certfile, "etc/certs/cert.pem"},
   {keyfile, "etc/certs/key.pem"},
   {secure_renegotiate, true},
   {versions, ['tlsv1.2']},
   {depth, 0}]},
 {client,
  [{secure_renegotiate, true}]}].
```

**Comment by manolodd** [comment]
Great @HJianBo, I'll test It Next week. Thank yo so much.

**Comment by manolodd** [comment]
Hi, @HJianBo, sorry for responding so late. I've tried it and the traffic distribution on TLS 1.2 is already working correctly. However I had to add my CA's certificate, which is self-signed. But finally everything works great. Thank you.

```
[{server,
  [{certfile, "/etc/emqx/certs/emqnode.pem.crt"},
   {keyfile, "/etc/emqx/certs/emqnode.pem.key"},
   {cacertfile, "/etc/emqx/certs/myownCA.pem.crt"},
   {secure_renegotiate, true},
   {versions, ['tlsv1.2']},
   {depth, 0}]},
 {client,
  [{secure_renegotiate, true}]}].
```

**Comment by HJianBo** [comment]
You'r welcome @manolodd 

Just close first. If you have any questions, please reopen it
