### ISSUE TITLE
adding users and clientid via config file

### ISSUE THREAD

**Issue by archerian** [emqx/emqx#2563]
#### Environment

- OS: Windows 10
- Erlang/OTP: 21
- EMQ: 3.1.1

#### Description
At several locations in the documentation, we see that its possible to add a username like below
to emqx_auth_username.conf ->

auth.user.1.username = root
auth.user.1.password = root

But I'm getting a crash when I do this and start the broker, it will not run. I have modified my emqx.conf to set allow anonymous to false. 

This seems to happen for adding clientid to emqx_auth_clientid.conf too.

**Comment by HJianBo** [comment]
Yes, Adding clientid/username by cofigure file has been removed at v3.1.0-rc.2

**Comment by archerian** [comment]
Thanks for the update HJianBo.
