### ISSUE TITLE
Mulit topic acl check failed

### ISSUE THREAD

**Issue by chowyu08** [emqx/emqx#2565]
#### Environment

- OS:  docker
- EMQ: 3.1.0

#### Description

client subscribe mult topics,  one topic check acl failed, other topic subscribe failed.  

Could you provide a method to close client's connection when  check acl failed.

**Comment by Gilbert-Wong** [comment]
Haha @chowyu08, we have implemented this feature you want.

Here is the configuration entry:

![image](https://user-images.githubusercontent.com/20479699/58307474-52d99800-7e31-11e9-9bd4-175b030910b0.png)

You can just set the `acl_deny_action =  disconnect` to achieve your purpose.
