### ISSUE TITLE
Prompt after startup：The license certificate is expired

### ISSUE THREAD

**Issue by CrazyCoolL** [emqx/emqx#2572]
#### Environment

- OS: Ubuntu Server 16.04.1
- Erlang/OTP: 21
- EMQ: V3.0

#### Description

*A description of the issue*
logs:
Erlang/OTP 21 [erts-10.3] [source] [64-bit] [smp:16:16] [ds:16:16:10] [async-threads:32] [hipe]

Starting emqx on node emqx@127.0.0.1
Start http:management listener on 8080 successfully.
Start http:dashboard listener on 18083 successfully.
Start mqtt:tcp listener on 127.0.0.1:11883 successfully.
Start mqtt:tcp listener on 0.0.0.0:8888 successfully.
Start mqtt:ws listener on 0.0.0.0:8083 successfully.
Start mqtt:ssl listener on 0.0.0.0:8883 successfully.
Start mqtt:wss listener on 0.0.0.0:8084 successfully.
EMQ X Broker e3.0.0 is running now!
"The license certificate is expired!"
2019-05-26 15:21:38.232 [critical] The license certificate is expired!
2019-05-26 15:21:38.232 [critical] The license certificate is expired! System shutdown!
Stop mqtt:tcp listener on 127.0.0.1:11883 successfully.
Stop mqtt:tcp listener on 0.0.0.0:8888 successfully.
Stop mqtt:ws listener on 0.0.0.0:8083 successfully.
Stop mqtt:ssl listener on 0.0.0.0:8883 successfully.
Stop mqtt:wss listener on 0.0.0.0:8084 successfully.
[os_mon] memory supervisor port (memsup): Erlang has closed
[os_mon] cpu supervisor port (cpu_sup): Erlang has closed

**Comment by wengad82** [comment]
现在这问题有解决了吗？ 我用3的版本，启动也会报license证书过期问题

**Comment by Gilbert-Wong** [comment]
Sorry, @wengad82, the emqx edition you use is enterprise edition, you have to buy the license and place the license file into the correct path.
