### ISSUE TITLE
 load emqx_auth_username error

### ISSUE THREAD

**Issue by sjxu1982** [emqx/emqx#2576]
#### Environment

- OS: 
- Erlang/OTP: 
- EMQ: 

#### Description

PS D:\emqx-windows10-v3.1.1> ./bin/emqx_ctl plugins load emqx_auth_username
escript: exception error: no function clause matching
                 erlang:set_cookie(nonode@nohost,rpc) (erlang.erl, line 3381)
  in function  nodetool__escript__1558__950980__808000__33:do_with_ret/3 (D:\emqx-windows10-v3.1.1\bin\nodetool, line 139)
  in call from nodetool__escript__1558__950980__808000__33:main/1 (D:\emqx-windows10-v3.1.1\bin\nodetool, line 29)
  in call from escript:run/2 (escript.erl, line 758)
  in call from escript:start/1 (escript.erl, line 277)
  in call from init:start_em/1 (init.erl, line 1111)
  in call from init:do_boot/3 (init.erl, line 819)

**Comment by sjxu1982** [comment]
step1: allow_anonymous = false
step2: ./bin/emqx_ctl plugins load emqx_auth_username
step3: ./bin/emqx_ctl users add <Username> <Password>

**Comment by sjxu1982** [comment]
OS: windows server 2019 standard

**Comment by sjxu1982** [comment]
OS: Windows Server 2019 Standard
Erlang/OTP: 10.3
EMQ: 3.1.1
Thanks for Gilbert

**Comment by Gilbert-Wong** [comment]
I have tested `load emqx_auth_username` on emqx3.2-rc.2 and I cannot reproduce the problem you referred. Could you please try with the latest emqx edition on your windows server?
