### ISSUE TITLE
Why not use golang instead of erlang?

### ISSUE THREAD

**Issue by zhaojh329** [emqx/emqx#2577]
Why not use golang instead of erlang?

**Comment by Gilbert-Wong** [comment]
Golang is not a functional programming language and sucks in its design. Golang lacks all the features we loved as a PL in the 21st century.
 
- Pattern match, binary match
- High-order function
- Curry and function composition
- List Comprehension
- Actor model and message passing
- Soft real-time with GC
- Preemptive Scheduling
- Fault tolerance with supervisor tree
- Low latency
- Dynamic and easy to maintain

Last but not least, we really don't like Go Gopher, the iconic mascot of golang.
