### ISSUE TITLE
Failed to open session: client_is_unavailable

### ISSUE THREAD

**Issue by xyz361** [emqx/emqx#2582]
#### Environment

- OS: 
- Erlang/OTP: 
- EMQ: 

#### Description
Clear_Session ：true 
QoS ：1
Client Library：https://github.com/mqttjs/MQTT.js
Log:
![image](https://user-images.githubusercontent.com/37579443/58546872-de3f9880-8238-11e9-8236-ac6f87699582.png)

See: #2580

**Comment by HJianBo** [comment]
Which version to EMQ X used?
