### ISSUE TITLE
Webhook vs Subscribe vs Rules Engine

### ISSUE THREAD

**Issue by Schweig** [emqx/emqx#2586]
#### Environment

- OS: ubuntu
- Erlang/OTP:R21/10.0.5 
- EMQ: v3.0-rc.5

#### Description

This is more of a question than an issue. If I am going to hook in a backend service with emqx eg a node server that is responsible for updating the database or sending emails/text messages with third party apis is there a recommended architecture to ensure that emqx performance is not impacted when there are a large number of connections. Is the webhook plugin sufficient or should my backend service be subscribing to the topics or is the rules engine a better way of doing it. I'm somewhat new to mqtt so I'm unsure what the best practices are when integrating services with a broker.

**Comment by wivwiv** [comment]
@Schweig 

The best way is to store it directly into the database through the rule engine.

Webhook takes the second place, and server subscription is not recommended
