### ISSUE TITLE
Generic server emqx_sm_locker terminating 

### ISSUE THREAD

**Issue by xyz361** [emqx/emqx#2588]
#### Environment

- OS: 
- Erlang/OTP: 
- EMQ: 

#### Description

2019-05-30 22:37:28.775 [error] ** Generic server emqx_sm_locker terminating 
** Last message in was check_lease
** When Server state == {state,emqx_sm_locker,
                         {lease,15000,
                          {ok,
                           {interval,#Ref<0.3293260844.1217658882.148097>}}},
                         #{}}
** Reason for termination == 
** {badarg,[{ets,next,
                 [emqx_sm_locker,
                  <<"172.16.178.64_bench_conn_81759_4082438091">>],
                 []},
            {ekka_locker,check_lease,5,
                         [{file,"src/ekka_locker.erl"},{line,277}]},
            {ekka_locker,handle_info,2,
                         [{file,"src/ekka_locker.erl"},{line,237}]},
            {gen_server,try_dispatch,4,[{file,"gen_server.erl"},{line,637}]},
            {gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,711}]},
            {proc_lib,wake_up,3,[{file,"proc_lib.erl"},{line,259}]}]}

**Comment by HJianBo** [comment]
Hi, @xyz361 We have fixed this and released at v3.1.2 yesterday.

Thanks for your feedback :)
