### ISSUE TITLE
Gen Server terminating with wait_for_reply

### ISSUE THREAD

**Issue by rahulwinzo** [emqx/emqx#2590]
#### Environment

- OS: Ubuntu 18.04.1 LTS
- Erlang/OTP: Erlang/OTP 21
- EMQ: 3.0

#### Description

I've been getting this a lot recently.

** Generic server <0.2714.4> terminating
...
...
** Reason for termination ==
** {timeout,[{emqx_broker,wait_for_reply,2,[{file,"src/emqx_broker.erl"},{line,308}]},{emqx_session,'-handle_cast/2-fun-0-',3,[{file,"src/emqx_session.erl"},{line,469}]},{emqx_session,handle_cast,2,[{file,"src/emqx_session.erl"},{line,458}]},{gen_server,try_dispatch,4,[{file,"gen_server.erl"},{line,637}]},{gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,711}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,249}]}]}

Clients are not able to connect to the broker due to this. What might be the reason behind this? How can this be fixed?

**Comment by rahulwinzo** [comment]
@Gilbert-Wong can you help with this?

**Comment by Gilbert-Wong** [comment]
Of course, @rahulwinzo, Sorry for so late response. I'm very busy these days, I would help you as soon as possible.

**Comment by terry-xiaoyu** [comment]
@rahulwinzo Hi, this might be caused a known issue which has been fixed in emqx 3.0.0. Would you update you emqx to 3.0.1 or 3.1.2 ?

**Comment by rahulwinzo** [comment]
Yes, I would like to update emqx to the latest stable version. I have a plugin for which I need to build emqx from source on the machines. Earlier I could provide the github link of my plugin in Makefile and build emqx along with my plugin successfully. I guess it has changed now and I'm not able to find any wiki on how to install a plugin. Can you please help me with this?

**Comment by terry-xiaoyu** [comment]
@rahulwinzo If you are using the 3.1.x, checkout [emqx-rel](https://github.com/emqx/emqx-rel/tree/v3.1.2) at tag v3.1.2 and specify your private plugin repo in the makefile, and then update your relx.config:

https://github.com/emqx/emqx-rel/blob/d0b889be2adaafa5231b59783e8a9728800262fc/Makefile#L7

If you prefer the latest version (it is v3.2-beta.3 at the time of writing), then checkout v3.2-beta.3 and update the sections `deps` and `relx` in rebar.config:

https://github.com/emqx/emqx-rel/blob/e58ff34a798e5237f3cb78e6fbe109354d338132/rebar.config#L5

Note that the format should be full [rebar3 deps format](https://www.rebar3.org/docs/dependencies):

```
{rebar, {git, "git://github.com/erlang/rebar3.git", {tag, "3.0.0"}}}.
```
And note that you need to add a module attribute `-emqx_plugin(?MODULE).` in you _app.erl file, like [emqx_auth_mysql_app.erl](https://github.com/emqx/emqx-auth-mysql/blob/d1f8b7eaa38f70f0f25f3bcffacb30d1d4011da7/src/emqx_auth_mysql_app.erl#L19).

**Comment by rahulwinzo** [comment]
@terry-xiaoyu I checked out the emqx-rel tag v3.1.2 and I was able to build it from source. But now when I'm doing `./bin/emqx start`, it's giving me this error:

> 07:11:23.245 [error] Error generating configuration in phase apply_translations
> 07:11:23.245 [error] Error running translation for kernel.logger_level, [error, badarg]

**Comment by rahulwinzo** [comment]
@terry-xiaoyu Any idea on how this error can be fixed?

**Comment by tradingtrace** [comment]
It seems there is something wrong with you `emqx.schema` file, maybe `_rel/emqx/releases/3.1.2/schema/emqx.schema` or `rel/schema/emqx.schema`.

Could you please check if these lines in your schema are the same as here:
https://github.com/emqx/emqx/blob/2ed5cb3b6a578d0b817ad365477170fcae4b9b5d/priv/emqx.schema#L465-L467

**Comment by rahulwinzo** [comment]
@tradingtrace Yes, these lines are the same in `_rel/emqx/releases/3.1.2/schema/emqx.schema` as you've mentioned above.

**Comment by tradingtrace** [comment]
Thanks @rahulwinzo 

Could you please check the directory `_rel/emqx/lib/cuttlefish-2.2.x` is `2.2.2` or `2.2.1`?
If your `emqx-rel` version is v3.1.2, but `cuttlefish` is `2.2.1`, you just need to backup your config files and `make distclean` then `make` again.

(The `emqx-rel v3.1.0` used `cuttlefish-2.2.1` and `emqx-rel v3.1.2` used `cuttlefish-2.2.2`, and the `cuttlefish-2.2.1` can't process the schema format above).

**Comment by rahulwinzo** [comment]
Thanks @tradingtrace.
The version that I can see in the directory `_rel/emqx/lib/` is `cuttlefish-v2.0.11`. I tried running `make distclean` and then `make` but I can see that the `_rel/emqx/lib/` is again having `cuttlefish-v2.0.11` and emqx is not able to start.

**Comment by tradingtrace** [comment]
Sorry, I don't know why it is `cuttlefish-v2.0.11`, just some notes hope to be helpful:
1. Make sure the current git tag/branch/ref point to v3.1.2, especially `Makefile`, `rebar.config` should be the same as v3.1.2.
2. Make sure the directory `_rel` and `deps` have been deleted after `make distclean`.

then run `make`, it should have `cuttlefish-2.2.2` in `_rel/emqx/lib/`, and as long as `cuttlefish` >= 2.2.2 the `kernel.logger_level, [error, badarg]` error should disappear.

**Comment by rahulwinzo** [comment]
Ok. I figured out what was going wrong with the cuttlefish version. And I was able to start emqx v3.1.2. But now, I see a new type of error. Please look at the stack trace from the logs:

> {{timeout,{gen_server,call,
>                          [<0.8191.0>,
>                           {subscribe,<<"social/im/msg/4240718/+">>}]}},
>     [{gen_server,call,2,[{file,"gen_server.erl"},{line,215}]},
>      {emqx_session,do_subscribe,5,[{file,"src/emqx_session.erl"},{line,1152}]},
>      {emqx_session,'-handle_cast/2-fun-0-',4,
>                    [{file,"src/emqx_session.erl"},{line,491}]},
>      {emqx_session,handle_cast,2,[{file,"src/emqx_session.erl"},{line,488}]},
>      {gen_server,try_dispatch,4,[{file,"gen_server.erl"},{line,637}]},
>      {gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,711}]},
>      {proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,249}]}]}

**Comment by rahulwinzo** [comment]
@terry-xiaoyu @Gilbert-Wong @tradingtrace I was hoping that upgrading to the latest emqx will solve this issue. But I'm stuck at the same issue. Please help in getting this issue resolved.

**Comment by Gilbert-Wong** [comment]
Hi, @rahulwinzo, this is a new problem, could you please open a new issue for this problem? What's more, please tell me how did you trigger this error, I want to reproduce this problem and confirm whether it is a bug.
