### ISSUE TITLE
ACL for authenticated user not working for me

### ISSUE THREAD

**Issue by ashishka** [emqx/emqx#2592]
#### Environment

- OS: Ubuntu 18.04
- Erlang/OTP:  
- EMQ: EMQX 3.1.1

#### Description

I have emqx instance with emqx_auth_username plugin. This is working well.
But i need to each user can subscribe his own message queue, i did that
{allow, {user, "%u"}, subscribe, ["queue/%u/#"]}.

but this is not work, i can subscribe with this {allow, all, subscribe, ["queue/%u/#"]}.
but this is not way to me. 

I have this is in the emqx.conf

allow_anonymous = false
acl_nomatch = deny
acl_deny_action = ignore

Can anybody explain me - if this possible what i want ? and what will be correct to do ?

Thanks!

**Comment by ashishka** [comment]
Hi there!

Managed to resolve the problem, the issue was I had to also give permissions to publish to $SYS/broker/connection/#, this seems to be a requirement of Mosquitto, e.g.

{allow, all, publish, ["$SYS/broker/connection/#"]}.

Thanks!

**Comment by Gilbert-Wong** [comment]
Good, @ashishka , you are welcome.
