### ISSUE TITLE
Load plugin emqx_auth_mysql failed,

### ISSUE THREAD

**Issue by chennian12789** [emqx/emqx#2594]
#### Environment

- OS: cent os 7
- Erlang/OTP: R21/10.2
- EMQ: 3.1

#### Description

*A description of the issue*
Enable the module of mysql
"Network Error" when clicking start & config emqx_auth_mysql

before use "emqx_ctl plugins load emqx_auth_mysql"  is error:
[Plugins] Load plugin emqx_auth_mysql failed, cannot start plugin emqx_auth_mysql for {bad_return,
                                                                                       {{emqx_auth_mysql_app,
                                                                                         start,
                                                                                         [normal,
                                                                                          []]},
                                                                                        {'EXIT',
                                                                                         {{badmatch,
                                                                                           {error,
                                                                                            {shutdown,
                                                                                             {failed_to_start_child,
                                                                                              emqx_auth_mysql,
                                                                                              {shutdown,
                                                                                               {failed_to_start_child,
                                                                                                worker_sup,
                                                                                                {shutdown,
                                                                                                 {failed_to_start_child,
                                                                                                  {worker,
                                                                                                   1},
                                                                                                  {{auth_method,
                                                                                                    <<"caching_sha2_password">>},
                                                                                                   [{mysql_protocol,
                                                                                                     build_handshake_response,
                                                                                                     5,
                                                                                                     [{file,
                                                                                                       "src/mysql_protocol.erl"},
                                                                                                      {line,
                                                                                                       382}]},
                                                                                                    {mysql_protocol,
                                                                                                     handshake,
                                                                                                     7,
                                                                                                     [{file,
                                                                                                       "src/mysql_protocol.erl"},
                                                                                                      {line,
                                                                                                       72}]},
                                                                                                    {mysql_conn,
                                                                                                     init,
                                                                                                     1,
                                                                                                     [{file,
                                                                                                       "src/mysql_conn.erl"},
                                                                                                      {line,
                                                                                                       90}]},
                                                                                                    {gen_server,
                                                                                                     init_it,
                                                                                                     2,
                                                                                                     [{file,
                                                                                                       "gen_server.erl"},
                                                                                                      {line,
                                                                                                       374}]},
                                                                                                    {gen_server,
                                                                                                     init_it,
                                                                                                     6,
                                                                                                     [{file,
                                                                                                       "gen_server.erl"},
                                                                                                      {line,
                                                                                                       342}]},
                                                                                                    {proc_lib,
                                                                                                     init_p_do_apply,
                                                                                                     3,
                                                                                                     [{file,
                                                                                                       "proc_lib.erl"},
                                                                                                      {line,
                                                                                                       249}]}]}}}}}}}}},
                                                                                          [{emqx_auth_mysql_app,
                                                                                            start,
                                                                                            2,
                                                                                            [{file,
                                                                                              "src/emqx_auth_mysql_app.erl"},
                                                                                             {line,
                                                                                              36}]},
                                                                                           {application_master,
                                                                                            start_it_old,
                                                                                            4,
                                                                                            [{file,
                                                                                              "application_master.erl"},
                                                                                             {line,
                                                                                              277}]}]}}}}
load plugin error: {emqx_auth_mysql,
                    {bad_return,
                     {{emqx_auth_mysql_app,start,[normal,[]]},
                      {'EXIT',
                       {{badmatch,
                         {error,
                          {shutdown,
                           {failed_to_start_child,emqx_auth_mysql,
                            {shutdown,
                             {failed_to_start_child,worker_sup,
                              {shutdown,
                               {failed_to_start_child,
                                {worker,1},
                                {{auth_method,<<"caching_sha2_password">>},
                                 [{mysql_protocol,build_handshake_response,5,
                                   [{file,"src/mysql_protocol.erl"},
                                    {line,382}]},
                                  {mysql_protocol,handshake,7,
                                   [{file,"src/mysql_protocol.erl"},
                                    {line,72}]},
                                  {mysql_conn,init,1,
                                   [{file,"src/mysql_conn.erl"},{line,90}]},
                                  {gen_server,init_it,2,
                                   [{file,"gen_server.erl"},{line,374}]},
                                  {gen_server,init_it,6,
                                   [{file,"gen_server.erl"},{line,342}]},
                                  {proc_lib,init_p_do_apply,3,
                                   [{file,"proc_lib.erl"},
                                    {line,249}]}]}}}}}}}}},
                        [{emqx_auth_mysql_app,start,2,
                          [{file,"src/emqx_auth_mysql_app.erl"},{line,36}]},
                         {application_master,start_it_old,4,
                          [{file,"application_master.erl"},{line,277}]}]}}}}}

**Comment by Gilbert-Wong** [comment]
It seems that the mysql version you use is 8.0, the default auth method `caching_sha2_password` has not been supported by emqx-auth-mysql now. We'll support this feature in the future. In your case, there is one temp workaround now, replace the caching_sha2_password with mysql_native_password. Hope my answer could help you.

**Comment by chennian12789** [comment]
ok, thanks for you.

**Comment by matiasnga** [comment]
hola Pablo, despues de casi un año de tener el sistema funcionando, EMQX no logra conectarse por WSS, ya que cuando inicio el servicio me tira error que no puede levantar el plugin emqx_auth_plugin. Desde el dashboard intento levantarlo manualmente pero genera el siguiente error "Request failed with status code 500".
Podrias darme una mano de por donde viene el error? gracias
