### ISSUE TITLE
Subscription module will lose subscription once EMQX restarts

### ISSUE THREAD

**Issue by sufish** [emqx/emqx#2595]
#### Environment

- OS: MacOS 10.12.6
- Erlang/OTP: 18 
- EMQ: 3.1.1

#### Description
I configured subscription module with following config:

```
module.subscription = on
module.subscription.1.topic = test
module.subscription.1.qos = 1
```
it works, new mqtt client will be subscribed to topic "test" automatticaly.

then i restared emqx broker, the same mqtt client reconnected, but the client will not be subscribed to topic "test" anymore. if i use a new clientId to connect to emqx , the new client will be subscribed to topic "test" . if i restart emqx once more,the samething will happen again.

**Comment by HJianBo** [comment]
Hi, @sufish We have fixed it and released at v3.1.2 yesterday!

Thanks for your feedback :)
