### ISSUE TITLE
AutoCluster by etcd fails Discovery error: {headers_error,not_strings}

### ISSUE THREAD

**Issue by bennygao** [emqx/emqx#2599]
#### Environment

- OS: CentOS 7.6
- Erlang/OTP: 
- EMQ: 3.1.1-1.el7

#### Description
When AutoCluster by etcd, it reports error as follow.
2019-06-04 18:24:32.711 [error] Ekka(AutoCluster): Discovery error: {headers_error,not_strings}

Version information of etcd:
etcd Version: 3.3.13
Git SHA: 98d3084
Go Version: go1.10.8
Go OS/Arch: linux/amd64

etcd starting command and arguments:
etcd --data-dir=/var/etcd --name etcnode1 --listen-client-urls http://0.0.0.0:2379 --advertise-client-urls http://0.0.0.0:2379 --listen-peer-urls=http://0.0.0.0:2380 --initial-advertise-peer-urls=http://0.0.0.0:2380 --enable-v2

*A description of the issue*

**Comment by HJianBo** [comment]
Hi, @bennygao Could you paste the related configurations to there?

**Comment by bennygao** [comment]
Thanks for your attention. The contents of `/etc/emqx/emqx.conf` are as follows.
--------
	cluster.name = emqxcl
	cluster.discovery = etcd
	cluster.autoheal = on
	cluster.autoclean = 5m
	cluster.etcd.server = http://10.0.2.10:2379
	cluster.etcd.prefix = emqxcl
	cluster.etcd.node_ttl = 1m
	node.name = emqx@10.0.2.10
	node.cookie = emqxsecretcookie
	node.data_dir = /var/lib/emqx
	node.async_threads = 32
	node.process_limit = 2048000
	node.max_ports = 1024000
	node.dist_buffer_size = 8MB
	node.max_ets_tables = 256000
	node.fullsweep_after = 1000
	node.crash_dump = /var/log/emqx/crash.dump
	node.proto_dist = inet_tcp
	node.dist_net_ticktime = 60
	node.dist_listen_min = 6369
	node.dist_listen_max = 6369
	rpc.tcp_server_port = 5369
	rpc.tcp_client_port = 5369
	rpc.connect_timeout = 5s
	rpc.send_timeout = 5s
	rpc.authentication_timeout = 5s
	rpc.call_receive_timeout = 15s
	rpc.socket_keepalive_idle = 900s
	rpc.socket_keepalive_interval = 75s
	rpc.socket_keepalive_count = 9
	log.to = both
	log.level = error
	log.dir = /var/log/emqx
	log.file = emqx.log
	log.chars_limit = 8192
	log.rotation.size = 10MB
	log.rotation.count = 5
	allow_anonymous = true
	acl_nomatch = allow
	acl_file = /etc/emqx/acl.conf
	enable_acl_cache = on
	acl_cache_max_size = 32
	acl_cache_ttl = 1m
	acl_deny_action = ignore
	mqtt.max_packet_size = 1MB
	mqtt.max_clientid_len = 65535
	mqtt.max_topic_levels = 0
	mqtt.max_qos_allowed = 2
	mqtt.max_topic_alias = 0
	mqtt.retain_available = true
	mqtt.wildcard_subscription = true
	mqtt.shared_subscription = true
	mqtt.ignore_loop_deliver = false
	zone.external.idle_timeout = 15s
	zone.external.enable_acl = on
	zone.external.enable_ban = on
	zone.external.enable_stats = on
	zone.external.acl_deny_action = ignore
	zone.external.force_gc_policy = 1000|1MB
	zone.external.keepalive_backoff = 0.75
	zone.external.max_subscriptions = 0
	zone.external.upgrade_qos = off
	zone.external.max_inflight = 32
	zone.external.retry_interval = 20s
	zone.external.max_awaiting_rel = 100
	zone.external.await_rel_timeout = 300s
	zone.external.session_expiry_interval = 2h
	zone.external.max_mqueue_len = 1000
	zone.external.mqueue_priorities = none
	zone.external.mqueue_default_priority = highest
	zone.external.mqueue_store_qos0 = true
	zone.external.enable_flapping_detect = off
	zone.external.flapping_threshold = 10, 1m
	zone.external.flapping_banned_expiry_interval = 1h
	zone.external.use_username_as_clientid = false
	zone.internal.allow_anonymous = true
	zone.internal.enable_stats = on
	zone.internal.enable_acl = off
	zone.internal.acl_deny_action = ignore
	zone.internal.max_subscriptions = 0
	zone.internal.max_inflight = 32
	zone.internal.max_awaiting_rel = 100
	zone.internal.max_mqueue_len = 1000
	zone.internal.mqueue_store_qos0 = true
	zone.internal.enable_flapping_detect = off
	zone.internal.flapping_threshold = 10, 1m
	zone.internal.flapping_banned_expiry_interval = 1h
	zone.internal.use_username_as_clientid = false
	listener.tcp.external = 0.0.0.0:1883
	listener.tcp.external.acceptors = 8
	listener.tcp.external.max_connections = 1024000
	listener.tcp.external.max_conn_rate = 1000
	listener.tcp.external.active_n = 100
	listener.tcp.external.zone = external
	listener.tcp.external.access.1 = allow all
	listener.tcp.external.backlog = 1024
	listener.tcp.external.send_timeout = 15s
	listener.tcp.external.send_timeout_close = on
	listener.tcp.external.nodelay = true
	listener.tcp.external.reuseaddr = true
	listener.tcp.internal = 127.0.0.1:11883
	listener.tcp.internal.acceptors = 4
	listener.tcp.internal.max_connections = 1024000
	listener.tcp.internal.max_conn_rate = 1000
	listener.tcp.internal.active_n = 1000
	listener.tcp.internal.zone = internal
	listener.tcp.internal.backlog = 512
	listener.tcp.internal.send_timeout = 5s
	listener.tcp.internal.send_timeout_close = on
	listener.tcp.internal.nodelay = false
	listener.tcp.internal.reuseaddr = true
	listener.ssl.external = 8883
	listener.ssl.external.acceptors = 16
	listener.ssl.external.max_connections = 102400
	listener.ssl.external.max_conn_rate = 500
	listener.ssl.external.active_n = 100
	listener.ssl.external.zone = external
	listener.ssl.external.access.1 = allow all
	listener.ssl.external.handshake_timeout = 15s
	listener.ssl.external.keyfile = /etc/emqx/certs/key.pem
	listener.ssl.external.certfile = /etc/emqx/certs/cert.pem
	listener.ssl.external.ciphers = ECDHE-ECDSA-AES256-GCM-SHA384,ECDHE-RSA-AES256-GCM-SHA384,ECDHE-ECDSA-AES256-SHA384,ECDHE-RSA-AES256-SHA384,ECDHE-ECDSA-DES-CBC3-SHA,ECDH-ECDSA-AES256-GCM-SHA384,ECDH-RSA-AES256-GCM-SHA384,ECDH-ECDSA-AES256-SHA384,ECDH-RSA-AES256-SHA384,DHE-DSS-AES256-GCM-SHA384,DHE-DSS-AES256-SHA256,AES256-GCM-SHA384,AES256-SHA256,ECDHE-ECDSA-AES128-GCM-SHA256,ECDHE-RSA-AES128-GCM-SHA256,ECDHE-ECDSA-AES128-SHA256,ECDHE-RSA-AES128-SHA256,ECDH-ECDSA-AES128-GCM-SHA256,ECDH-RSA-AES128-GCM-SHA256,ECDH-ECDSA-AES128-SHA256,ECDH-RSA-AES128-SHA256,DHE-DSS-AES128-GCM-SHA256,DHE-DSS-AES128-SHA256,AES128-GCM-SHA256,AES128-SHA256,ECDHE-ECDSA-AES256-SHA,ECDHE-RSA-AES256-SHA,DHE-DSS-AES256-SHA,ECDH-ECDSA-AES256-SHA,ECDH-RSA-AES256-SHA,AES256-SHA,ECDHE-ECDSA-AES128-SHA,ECDHE-RSA-AES128-SHA,DHE-DSS-AES128-SHA,ECDH-ECDSA-AES128-SHA,ECDH-RSA-AES128-SHA,AES128-SHA
	listener.ssl.external.reuseaddr = true
	listener.ws.external = 8083
	listener.ws.external.mqtt_path = /mqtt
	listener.ws.external.acceptors = 4
	listener.ws.external.max_connections = 102400
	listener.ws.external.max_conn_rate = 1000
	listener.ws.external.zone = external
	listener.ws.external.access.1 = allow all
	listener.ws.external.verify_protocol_header = on
	listener.ws.external.backlog = 1024
	listener.ws.external.send_timeout = 15s
	listener.ws.external.send_timeout_close = on
	listener.ws.external.nodelay = true
	listener.wss.external = 8084
	listener.wss.external.mqtt_path = /mqtt
	listener.wss.external.acceptors = 4
	listener.wss.external.max_connections = 16
	listener.wss.external.max_conn_rate = 1000
	listener.wss.external.zone = external
	listener.wss.external.access.1 = allow all
	listener.wss.external.verify_protocol_header = on
	listener.wss.external.keyfile = /etc/emqx/certs/key.pem
	listener.wss.external.certfile = /etc/emqx/certs/cert.pem
	listener.wss.external.ciphers = ECDHE-ECDSA-AES256-GCM-SHA384,ECDHE-RSA-AES256-GCM-SHA384,ECDHE-ECDSA-AES256-SHA384,ECDHE-RSA-AES256-SHA384,ECDHE-ECDSA-DES-CBC3-SHA,ECDH-ECDSA-AES256-GCM-SHA384,ECDH-RSA-AES256-GCM-SHA384,ECDH-ECDSA-AES256-SHA384,ECDH-RSA-AES256-SHA384,DHE-DSS-AES256-GCM-SHA384,DHE-DSS-AES256-SHA256,AES256-GCM-SHA384,AES256-SHA256,ECDHE-ECDSA-AES128-GCM-SHA256,ECDHE-RSA-AES128-GCM-SHA256,ECDHE-ECDSA-AES128-SHA256,ECDHE-RSA-AES128-SHA256,ECDH-ECDSA-AES128-GCM-SHA256,ECDH-RSA-AES128-GCM-SHA256,ECDH-ECDSA-AES128-SHA256,ECDH-RSA-AES128-SHA256,DHE-DSS-AES128-GCM-SHA256,DHE-DSS-AES128-SHA256,AES128-GCM-SHA256,AES128-SHA256,ECDHE-ECDSA-AES256-SHA,ECDHE-RSA-AES256-SHA,DHE-DSS-AES256-SHA,ECDH-ECDSA-AES256-SHA,ECDH-RSA-AES256-SHA,AES256-SHA,ECDHE-ECDSA-AES128-SHA,ECDHE-RSA-AES128-SHA,DHE-DSS-AES128-SHA,ECDH-ECDSA-AES128-SHA,ECDH-RSA-AES128-SHA,AES128-SHA
	listener.wss.external.backlog = 1024
	listener.wss.external.send_timeout = 15s
	listener.wss.external.send_timeout_close = on
	module.presence = on
	module.presence.qos = 1
	module.subscription = off
	module.rewrite = off
	plugins.etc_dir = /etc/emqx/plugins/
	plugins.loaded_file = /var/lib/emqx/loaded_plugins
	plugins.expand_plugins_dir = /var/lib/emqx/plugins/
	broker.sys_interval = 1m
	broker.enable_session_registry = on
	broker.session_locking_strategy = quorum
	broker.shared_subscription_strategy = random
	broker.shared_dispatch_ack_enabled = false
	broker.route_batch_clean = off
	sysmon.long_gc = 0
	sysmon.long_schedule = 240ms
	sysmon.large_heap = 8MB
	sysmon.busy_port = false
	sysmon.busy_dist_port = true
	os_mon.cpu_check_interval = 60s
	os_mon.cpu_high_watermark = 80%
	os_mon.cpu_low_watermark = 60%
	os_mon.mem_check_interval = 60s
	os_mon.sysmem_high_watermark = 70%
	os_mon.procmem_high_watermark = 5%
	vm_mon.check_interval = 30s
	vm_mon.process_high_watermark = 80%
	vm_mon.process_low_watermark = 60%

**Comment by HJianBo** [comment]
Hi, @bennygao we have checked it. And it has fixed at this commit.
https://github.com/emqx/ekka/commit/8b1bfdc8a3e54c654667548f1db2d182d0f10f4d

We will release it at v3.1.2. Thanks for your feedback!

**Comment by HJianBo** [comment]
We have released at v3.1.2. Please check it

Let me know please, if it does not solve your problem

Thanks

**Comment by bennygao** [comment]
After EMQX was upgraded to 3.1.2, this problem was solved.
