### ISSUE TITLE
When acl_deny_action is set to ignore, the other check will lose efficacy

### ISSUE THREAD

**Issue by Gilbert-Wong** [emqx/emqx#2610]
#### Environment

- OS: All
- Erlang/OTP: All
- EMQ: 3.1.1, 3.2.beta1

#### Description

When `acl_deny_action` is set to ignore, the other check functions can not be taken into effect.

**Comment by Gilbert-Wong** [comment]
It has been fixed. https://github.com/emqx/emqx/pull/2609/files

**Comment by HJianBo** [comment]
It has released at v3.2-beta.3
