### ISSUE TITLE
how to configure web hook on dashboard?

### ISSUE THREAD

**Issue by xlb0479** [emqx/emqx#2616]
#### Environment

- OS: Ubuntu16.04.4 LTS
- Erlang/OTP:  21
- EMQ: 3.0

#### Description

*A description of the issue*

I want to be notified when a client sub/unsub on some topic and I use dashboard to config the web hook plugin.

There are something like `web.hook.rule.message.delivered.$name` on the UI and I dont know whats that mean. Why `$name` looks like a variable, how to config it?

Any docs?

Thank you.

**Comment by turtleDeng** [comment]
Sorry, it is not supported to configure webbhook in the dashboard.

**Comment by turtleDeng** [comment]
Thank you for your participation, we will close this issue, if there are any problems, you can reopen
