### ISSUE TITLE
use_username_as_clientid does not work using certs

### ISSUE THREAD

**Issue by asierg95** [emqx/emqx#2618]
use_username_as_clientid doesn't work on my installation (CentOS 7 with emqx v3.1.1) as expected.
I have set

```
zone.external.use_username_as_clientid = true
zone.internal.use_username_as_clientid = true
```
I do authentication via TLS certificates

listener.ssl.external.peer_cert_as_username = cn
When I do emqx_ctl clients list I see the correct usernames but the clientid is the clientId that the client if providing. I want the clientid to be the same as username (the certificate CN).

I have tried without certificates and the clientId is the same as the username. But using certificates I don't know why, but is not working as expected.

If I manually give an user, it works fine, and the clientId is the provided username.

**Comment by HJianBo** [comment]
Hi, @asierg95 if you want to get the client certificates, you must enable the Two-way SSL authentication. Please check the following options:

*etc/emqx.conf*:
```properties
listener.ssl.external.keyfile = etc/certs/key.pem
listener.ssl.external.certfile = etc/certs/cert.pem
listener.ssl.external.cacertfile = etc/certs/cacert.pem
listener.ssl.external.verify = verify_peer
```

**Comment by asierg95** [comment]
> Hi, @asierg95 if you want to get the client certificates, you must enable the Two-way SSL authentication. Please check the following options:
> 
> _etc/emqx.conf_:
> 
> ```ini
> listener.ssl.external.keyfile = etc/certs/key.pem
> listener.ssl.external.certfile = etc/certs/cert.pem
> listener.ssl.external.cacertfile = etc/certs/cacert.pem
> listener.ssl.external.verify = verify_peer
> ```

Hi, JianBo yes really thanks, I have enabled the Two-way SSL authentication. When I list the users, it shows the CN of the certificate that is well. But when I list the clients, the clientId is not the CN. But if I use without certificates the user and the clientId are the same.

**Comment by HJianBo** [comment]
Sorry @asierg95  I have checked the release notes. This feature is packed to v3.2.beta.1 not v3.1.1.

**Comment by asierg95** [comment]
> Sorry @asierg95 I have checked the release notes. This feature is packed to v3.2.beta.1 not v3.1.1.

Okey I will try it. Thanks
