### ISSUE TITLE
Unable to repeatedly publish to MQTT-SN plugin

### ISSUE THREAD

**Issue by foufee** [emqx/emqx#2622]
#### Environment

- OS: Linux 4.15.0-47-generic #50-Ubuntu SMP Wed Mar 13 10:44:52 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
- Erlang/OTP: Erlang/OTP 22 [erts-10.4.1] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1]                                      │20190614 111948.400 ClientSendTask   stopped.
- EMQ:    R21/10.3
--

#### Description
Using the MQTT-SN plugin, and a client written using the Paho MQTTSNPacket library, PUBACK's stop being received after about 14 publishes.

Additionally, using the EMQX MQTT-SN simple_example.erl (slightly modified to repeat publishing), after about 20 packets, it stops responding.

Reconnecting the client works, for around 20 packets, and then the same behaviour happens again.

**Comment by foufee** [comment]
It appears to be time related, and close to 15s.

**Comment by HJianBo** [comment]
Close it. It has fixed by https://github.com/emqx/emqx-sn/pull/127
