### ISSUE TITLE
how long does mqtt session timeout ?

### ISSUE THREAD

**Issue by gi122281742** [emqx/emqx#2623]
in MQTT Clean Session:Clean Session’ is set to 0, which means that a persistent session is created. When the client is disconnected, the session still keeps and saves the offline message until the session times out.

how to set timeout?or how long does mqtt session default timeout ?

**Comment by turtleDeng** [comment]
```
zone.external.session_expiry_interval = 2h
```
For more information, please see https://developer.emqx.io/docs/broker/v3/en/config.html#mqtt-protocol-parameter-configuration
