### ISSUE TITLE
can not recover from flap ban status

### ISSUE THREAD

**Issue by LuckyITBoy** [emqx/emqx#2626]
#### Environment

- OS: Ubuntu1804
- Erlang/OTP: R21/10.3
- EMQ: v3.1.2 release

#### Description

*I can not recover from flap ban status， I check emqx.conf about flap*

```
zone.external.enable_flapping_detect = on
zone.external.flapping_threshold = 10, 1m
zone.external.flapping_banned_expiry_interval = 1m

flapping_clean_interval = 1m
```

first, My mqtt client is connected sucess, than I try disconnect and connecting 10 times, then it banned by flap detect.
but when timeout, It should be unban, but it did't work.  My mqtt client  still return  error 
 like this `Connection Refused: not authorised` 。

where is wrong？ i

**Comment by Gilbert-Wong** [comment]
@LuckyITBoy Yes, it is definitely bug of flapping. Thanks for your feedback very much. I'll fix it soon.

**Comment by turtleDeng** [comment]
Fix it at https://github.com/emqx/emqx/pull/2628
