### ISSUE TITLE
[Question] ACL Config by CIDR IP range

### ISSUE THREAD

**Issue by devmark88** [emqx/emqx#2630]
regarding to [ACL Design Documentation](https://github.com/emqx/emqx/wiki/ACL-Design#etcaclconfig) we can restrict `pub`|`sub`|`pubsub` with IP address in ACL configuration.
All the examples in the documents supposed a single IP address, Is the acl conf support [CDIR IP Range](https://en.wikipedia.org/wiki/Classless_Inter-Domain_Routing) (for example 74.125.227.0/29)?

**Comment by HJianBo** [comment]
In the `acl.conf`, just configure it with the following content:
```erlang
{allow, {ipaddr, "74.125.227.0/29"}, pubsub, ["$SYS/#", "#"]}
```

In Addition, the `emqx_auth_mysql`, `emqx_auth_pgsql` support these feature also.
