### ISSUE TITLE
Is it necessary to start/stop a client during each request-response?

### ISSUE THREAD

**Issue by sngyai** [emqx/emqx#2633]
#### Environment

- OS: Ubuntu 18.04
- Erlang/OTP: 21
- EMQ: master

#### Description
Hey, I noticed that [emqx_request_response_SUITE.erl](https://github.com/emqx/emqx/blob/master/test/emqx_request_response_SUITE.erl) has implemented request-respnose feature of MQTT v5. 

But accroding to this example, I must start/stop a new connection(client) everytime when I call request-response, as a result of `emqx_client` only sends `{publish, Msg}` to its `owner`.

Now I want to create a long-lived `emqx_client` between different request-response calls,
I've tried to use a `gen_server` as the `owner` of `emqx_client`, but I cannot `receive` in `handle_call` due to [https://stackoverflow.com/questions/39361736/can-receive-clause-be-used-in-a-gen-server-process](https://stackoverflow.com/questions/39361736/can-receive-clause-be-used-in-a-gen-server-process)

Do you have any idea? Thanks a lot.

**Comment by Gilbert-Wong** [comment]
No, @sngyai, if you start one request_sender client, you can send multiple request in one connection. And of course, you also need to set request handler for response handler.

**Comment by sngyai** [comment]
Got it, thanks a lot.
Now I have another problem, when responser offline, which means it cannot response the request, in this situation, the `owner` of `emqx_client` must wait for a timeout, and requests follow-up will be queued in the `owner` of `emqx_client` and then timeout, since the server cannot manage the request caller's behaviour, how to deal with this situation?

可能表达的不太准确，中文再来一遍：比如请求方是A，响应方为B，如果B不在线（或者在线也不响应），那么`emqx_client`的`owner`要一直等待`{publish, Msg}`消息，直到触发超时，在这期间`owner`新来的请求就得进入队列排队，而且可能会排队超时，随着这样的情况越来越多，队列可能还会不断增大，我们没法约束A和B的行为（比如B不在线，但是A一直请求，队列就会不断增大），在这种情况下该怎么处理呢？

**Comment by Gilbert-Wong** [comment]
Hi, @sngyai, From your description, I suppose that you let process A to call emqx_client process. If B is offline or B does not response, the A can do a mattern match such as

``` erlang

loop(Handler) ->
    receive
	    {response, CorrData, Payload} ->
             ?LOG("This is repsonse msg ~p", [Payload]),
	         Handler(Payload),
	         loop(Handler);
        _Other ->
             ?LOG("This is not repsonse msg ~p, Filtered it", [Payload]),
             loop(Handler)
    end.
```

If you write code like I write above, there will be no such problem your refered.

**Comment by sngyai** [comment]
You misunderstood me, but I've solved it myself, Thanks anyway.

**Comment by Gilbert-Wong** [comment]
Appreciate it if you are willing to share your solution :)

**Comment by sngyai** [comment]
I start a group of long-lived `gen_server` process, I call them `manager` which start `emqx_client`.

Then, for each request, I spawn a new process, which I call them `requester`, and  I send async request(`gen_server:cast`) to one of the `manager`s by `requester` and then wait for `{response, Resp}`.

I subscribe `response_topic` and publish to `request_topic` in `handle_cast` of `manager`, and then I record `requester`'s Pid and `request_id` to manager's `#state{}`

When message `{publish, Msg}` arrives, I process them in `manager`'s `handle_info`, I get `request_id` from `Msg`, and then get `requester` by `request_id` from  manager's `#state{}`.
Then I send these `Msg` back to `requester` if form of `{response, Resp}`.

Thus, I do not need to wait for timeout in `manager`, which is scarce resources, I just wait in separate `requester` and has no effect on other request.
