### ISSUE TITLE
What is the meaning of 'ExpiryInterval' on dashboard?

### ISSUE THREAD

**Issue by xlb0479** [emqx/emqx#2635]
#### Environment

- OS: ubuntu 18
- Erlang/OTP:  21
- EMQ:  3.0

#### Description

Column name 'ExpiryInterval' on the `Monitoring->Sessions` page, what is the meaning of it? How to set it?

When `cleansession` set to 0, ExpiryInterval is always 7.

I found the only configuration may be related to it is `zone.external.session_expiry_interval` but it was set  to 2h.

**Comment by tigercl** [comment]
Hi, @xlb0479, sorry for later response, the 'ExpiryInterval' you see on the dashboard is actually 'Session Expiry Interval' in MQTT protocol, and its value comes from your CONNECT packet. So, I suggest that you confirm your packet.

**Comment by tigercl** [comment]
Excuse me for previous reply, this is indeed a bug, we will fix it in next version.

**Comment by Gilbert-Wong** [comment]
Hi, this bug has been fixed in emqx3.2-rc.3, here is the pull request: https://github.com/emqx/emqx/pull/2663
