### ISSUE TITLE
Can we get milliseconds or microseconds for client's connection/disconnection events?

### ISSUE THREAD

**Issue by solitardj9** [emqx/emqx#2636]
#### Environment

- OS: Ubuntu 16.04
- Erlang/OTP: 
- EMQ: v3.0.0

#### Description

*A description of the issue*
In the Document for $SYS Topics (https://github.com/emqx/emqx/wiki/$SYS-Topics),
there are Client $SYS Topics for client's connection/disconnection events.

And parameters of 'connected' payload and 'disconnected' Payload are like this : 
{
    ipaddress: "127.0.0.1", 
    username: "test", 
    session: false, 
    protocol: 3, 
    connack: 0, 
    ts: 1432648482
}

{
    reason: normal,
    ts: 1432648486
}

In the above examples, ts supports timestamps in seconds.
Is it possible that ts supports timestamps in milliseconds.

and can you release this issue ASAP?

Thank you.

**Comment by Gilbert-Wong** [comment]
Of course, @solitardj9, it would be switched to millisecond in emqx3.2-rc.1.
