### ISSUE TITLE
Thermal Configuration not work

### ISSUE THREAD

**Issue by jyzhangbo** [emqx/emqx#2637]
#### Environment

- OS: CentOS Linux release 7.3.1611 (Core)
- Erlang/OTP: 
- EMQ: emqttd-centos7-v2.3.11

#### Description
The emq.conf config is:
```
log.dir = /var/log/emqttd
log.console = file
log.console.level = info
log.console.file = /var/log/emqttd/console.log
log.error.file = /var/log/emqttd/error.log
log.error.size = 10485760
log.error.count = 5
log.crash = on
log.crash.file = /var/log/emqttd/crash.log
log.syslog = on
log.syslog.level = error
```
I set log.console.level  as info,when I send a put request to /api/v2/configs/emqttd,and the request body is 
```
{
    "key"   : "log.console.level",
    "value" : "info"
}
```   
the response is 
```
{
    "code": 0,
    "result": []
}
```

but it do not work.

**Comment by Gilbert-Wong** [comment]
Hi, @jyzhangbo, could you please tell me how do you set the log level, did you use the command `emqttd_ctl` to set log level?

**Comment by jyzhangbo** [comment]
Hi, @Gilbert-Wong ,I set the log level through configuration file emq.conf. The version emqttd-centos7-v2.3.11 can not use the command emqttd_ctl to set the log level. 
I couldn't find the command to set it through emqttd_ctl, so I set it by send a put request,the uri is /api/v2/configs/emqttd,but it do not work.
Maybe what you said is trace command,but I want to monitor all clients.
