### ISSUE TITLE
EMQ Windows Version does not generate logs

### ISSUE THREAD

**Issue by xyz361** [emqx/emqx#2638]
#### Environment

- OS: Windows 10
- Erlang/OTP: 
- EMQ: 3.1.2

#### Description

*A description of the issue*
 I had started EMQ X instance , but I can't find the logs .

**Comment by Gilbert-Wong** [comment]
Hi, @xyz361, I have tested the latest emqx of windows edition. There is no problem you referred. Could you please give me more details ?
