### ISSUE TITLE
emqx3.1.2 Shared Subscription does not work

### ISSUE THREAD

**Issue by xiaode123** [emqx/emqx#2639]
#### Environment

- OS: 
- Erlang/OTP: 
- EMQ: 

#### Description

*A description of the issue*
When I upgrade emqx to version 3.1.2，I want to use the shared subscription feature，But it didn't work。
My emqx is a two-configured cluster,The configuration of the cluster is as follows：
![image](https://user-images.githubusercontent.com/20831922/59746243-11f66700-92a9-11e9-9e61-cb9d8c8f2da3.png)
The configuration of acl is as follows：
![image](https://user-images.githubusercontent.com/20831922/59746355-571a9900-92a9-11e9-87de-f7eaabed645e.png)
Two other clients are started to subscribe to messages and process data。
The subscription theme for the two client configurations is prefixed with the shared subscription.
Published topic is：chargingUp                  Subscription topic is：$queue/chargingUp
But both of my clients got the news of the release. Sometimes two clients can't get the news.
What is the reason for this?
What do I need to configure?
There is an urgent need to resolve this shared subscription feature！！！

**Comment by xiaode123** [comment]
@emqplus @farhadi @callbay

**Comment by xiaode123** [comment]
My local test started two clients,Can implement shared subscriptions normally。
However, the server deployed two clients, and one data is not received.

**Comment by Gilbert-Wong** [comment]
It is no problem. Two clients subscribe one shared topic and on one of them can recieve data, it is normal behaviour.

**Comment by Gilbert-Wong** [comment]
Hi, @xiaode123, has your problem been solved?
