### ISSUE TITLE
Debian apt install : "W: Conflicting distribution"

### ISSUE THREAD

**Issue by weinrank** [emqx/emqx#2640]
#### Environment

- OS: Debian 9.9
- Erlang/OTP: 
- EMQ: 3.1.2

#### Description

Hi, 
I'm running a debian 9.9 and when I'm trying to install the broker via the repository using apt, I'm getting a warning.
```
sudo apt update
Hit:1 http://security.debian.org/debian-security stretch/updates InRelease
Ign:2 http://ftp.de.debian.org/debian stretch InRelease
Hit:3 http://ftp.de.debian.org/debian stretch-updates InRelease
Hit:4 http://ftp.de.debian.org/debian stretch Release
Hit:5 https://repos.emqx.io/emqx-ce/deb/debian stretch InRelease
Reading package lists... Done
Building dependency tree
Reading state information... Done
All packages are up to date.
W: Conflicting distribution: https://repos.emqx.io/emqx-ce/deb/debian stretch InRelease (expected stretch but got )
```

**Comment by zhanghongtong** [comment]
@weinrank This is just a warning. You can ignore it

**Comment by Gilbert-Wong** [comment]
We'll fix this warning problem as soon as possible. Thanks for your feedback, @weinrank

**Comment by eveready1010** [comment]
I know this is just a warning, but is there any progress on this?

**Comment by adamhotep** [comment]
You need to specify a `Suite` and `Codename` in the Release file.

See also
* [Debian Mentors – Re: how to create a Release file](https://lists.debian.org/debian-mentors/2006/04/msg00294.html)
* [Debian Repository docs](https://wiki.debian.org/DebianRepository)
* https://github.com/Xpra-org/xpra/issues/3528#issuecomment-1105499721
