### ISSUE TITLE
can't load emqx-auth-mysql

### ISSUE THREAD

**Issue by JJLAAA** [emqx/emqx#2643]
#### Environment

- OS: Ubuntu16.04
- Erlang/OTP: R21/10.3.4
- EMQ: v3.1.1
- mysql version:8.0.16

#### Description

*A description of the issue*
I configured according to the steps of the official website, but the dashboard always displays "Request failed with status code 500"
here is the blog:

> 2019-06-20 07:53:17.729 [error] crasher:
    initial call: application_master:init/4
    pid: <0.12280.3>
    registered_name: []
    exception exit: {bad_return,
                     {{emqx_auth_mysql_app,start,[normal,[]]},
                      {'EXIT',
                       {{badmatch,
                         {error,
                          {shutdown,
                           {failed_to_start_child,emqx_auth_mysql,
                            {shutdown,
                             {failed_to_start_child,worker_sup,
                              {shutdown,
                               {failed_to_start_child,
                                {worker,1},
                                {{auth_method,<<"caching_sha2_password">>},
                                 [{mysql_protocol,build_handshake_response,5,
                                   [{file,"src/mysql_protocol.erl"},
                                    {line,382}]},
                                  {mysql_protocol,handshake,7,
                                   [{file,"src/mysql_protocol.erl"},
                                    {line,72}]},
                                  {mysql_conn,init,1,
                                   [{file,"src/mysql_conn.erl"},{line,90}]},
                                  {gen_server,init_it,2,
                                   [{file,"gen_server.erl"},{line,374}]},
                                  {gen_server,init_it,6,
                                   [{file,"gen_server.erl"},{line,342}]},
                                  {proc_lib,init_p_do_apply,3,
                                   [{file,"proc_lib.erl"},
                                    {line,249}]}]}}}}}}}}},
                        [{emqx_auth_mysql_app,start,2,
                          [{file,"src/emqx_auth_mysql_app.erl"},{line,36}]},
                         {application_master,start_it_old,4,
                          [{file,"application_master.erl"},{line,277}]}]}}}}
      in function  application_master:init/4 (application_master.erl, line 138)
    ancestors: [<0.12279.3>]
    message_queue_len: 1
    messages: [{'EXIT',<0.12281.3>,normal}]
    links: [<0.12279.3>,<0.1249.0>]
    dictionary: []
    trap_exit: true
    status: running
    heap_size: 987
    stack_size: 27
    reductions: 247
  neighbours:
2019-06-20 07:53:17.731 [error] [Plugins] Load plugin emqx_auth_mysql failed, cannot start plugin emqx_auth_mysql for {bad_return,
                                                                                       {{emqx_auth_mysql_app,
                                                                                         start,
                                                                                         [normal,
                                                                                          []]},
                                                                                        {'EXIT',
                                                                                         {{badmatch,
                                                                                           {error,
                                                                                            {shutdown,
                                                                                             {failed_to_start_child,
                                                                                              emqx_auth_mysql,
                                                                                              {shutdown,
                                                                                               {failed_to_start_child,
                                                                                                worker_sup,
                                                                                                {shutdown,
                                                                                                 {failed_to_start_child,
                                                                                                  {worker,
                                                                                                   1},
                                                                                                  {{auth_method,
                                                                                                    <<"caching_sha2_password">>},
                                                                                                   [{mysql_protocol,
                                                                                                     build_handshake_response,
                                                                                                     5,
                                                                                                     [{file,
                                                                                                       "src/mysql_protocol.erl"},
                                                                                                      {line,
                                                                                                       382}]},
                                                                                                    {mysql_protocol,
                                                                                                     handshake,
                                                                                                     7,
                                                                                                     [{file,
                                                                                                       "src/mysql_protocol.erl"},
                                                                                                      {line,
                                                                                                       72}]},
                                                                                                    {mysql_conn,
                                                                                                     init,
                                                                                                     1,
                                                                                                     [{file,
                                                                                                       "src/mysql_conn.erl"},
                                                                                                      {line,
                                                                                                       90}]},
                                                                                                    {gen_server,
                                                                                                     init_it,
                                                                                                     2,
                                                                                                     [{file,
                                                                                                       "gen_server.erl"},
                                                                                                      {line,
                                                                                                       374}]},
                                                                                                    {gen_server,
                                                                                                     init_it,
                                                                                                     6,
                                                                                                     [{file,
                                                                                                       "gen_server.erl"},
                                                                                                      {line,
                                                                                                       342}]},
                                                                                                    {proc_lib,
                                                                                                     init_p_do_apply,
                                                                                                     3,
                                                                                                     [{file,
                                                                                                       "proc_lib.erl"},
                                                                                                      {line,
                                                                                                       249}]}]}}}}}}}}},
                                                                                          [{emqx_auth_mysql_app,
                                                                                            start,
                                                                                            2,
                                                                                            [{file,
                                                                                              "src/emqx_auth_mysql_app.erl"},
                                                                                             {line,
                                                                                              36}]},
                                                                                           {application_master,
                                                                                            start_it_old,
                                                                                            4,
                                                                                            [{file,
                                                                                              "application_master.erl"},
                                                                                             {line,
                                                                                              277}]}]}}}}
2019-06-20 07:53:17.864 [error] PUT /api/v3/nodes/ae7f09b5ba7e@172.17.0.2/plugins/emqx_auth_mysql/load error: badarg, stacktrace:
[{jsx_parser,value,4,[{file,"src/jsx_parser.erl"},{line,163}]},
 {minirest_handler,jsonify,4,[{file,"src/minirest_handler.erl"},{line,152}]},
 {minirest,handle_request,2,[{file,"src/minirest.erl"},{line,91}]},
 {minirest,init,2,[{file,"src/minirest.erl"},{line,83}]},
 {cowboy_handler,execute,2,[{file,"src/cowboy_handler.erl"},{line,41}]},
 {cowboy_stream_h,execute,3,[{file,"src/cowboy_stream_h.erl"},{line,296}]},
 {cowboy_stream_h,request_process,3,
                  [{file,"src/cowboy_stream_h.erl"},{line,274}]},
 {proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,249}]}]

I have changed my plugin to 'mysql_native_password',But which encryption method should emqx be? I tried all the options but they are all the same error

**Comment by Eluso** [comment]
if your Mysql version >8,change mysql config file like:/etc/my.cnf,add this line:
`default_authentication_plugin=mysql_native_password`
restart your mysql and reload emqx_auth_mysql

**Comment by JJLAAA** [comment]
> if your Mysql version >8,change mysql config file like:/etc/my.cnf,add this line:
> `default_authentication_plugin=mysql_native_password`
> restart your mysql and reload emqx_auth_mysql

Thank you for your reply, but in the dashboard, which encryption method should I choose?
![无标题](https://user-images.githubusercontent.com/47405525/59836488-2a848100-937e-11e9-8dd2-ad2b682be3d4.png)
