### ISSUE TITLE
Using  emqx as an Elixir Application

### ISSUE THREAD

**Issue by alanj853** [emqx/emqx#2645]
#### Environment

- OS: Erlang VM
- Erlang/OTP: 21
- EMQ: Latest Master Branch

#### Description

This is more of a question than an issue.

Is it possible to run emqx as an application in Elixir, inside an Erlang VM?

I am working on an embedded system that uses an Elixir Application inside an Erlang VM (on top of Linux). We currently need an MQTT Broker for our app.

Rather than cross-compile and use the emqx linux binary, I am trying to include emqttd as part of my Elixir Application. I have added it to the dependencies in my mix.exs file in elixir, but it is failing to compile. I get the following error:

Unchecked dependencies for environment dev:
* emqx (/workdir/emqx)
  could not find an app file at "_build/dev/lib/emqx/ebin/emqx.app". This may happen if the dependency was not yet compiled, or you specified the wrong application name in your deps, or the dependency indeed has no app file (then you can pass app: false as option)
** (Mix) Can't continue due to errors on dependencies

It appears as though there is no app file for emqx.

So I want to know if this is in fact possible or not.

Thanks,

Alan

**Comment by Gilbert-Wong** [comment]
Hi, @alanj853, I suppose it is possible because both of the elixir and erlang code can run on Erlang VM. Actually, we have already supported to build emqx with elixir-plugin in the `emqx-rel` project. I have never built the erlang plugin in the elixir release project, so I do not know how to implement it and how to resolve the probelm in your case. I notice that the [phoenix](https://github.com/phoenixframework/phoenix) has integrated cowboy which is an erlang project. I suppose their solution can help you solve your problem.

**Comment by sarath-okcredit** [comment]
+1

**Comment by zmstone** [comment]
Now that emqx is a rebar3 project, I assume it should work fine for Elixir as a dependency.
Have you met any issue using it @sarath-okcredit ?

BTW, we are turning THIS project into an umbrella rebar3 project (checkout the `dev/v4.3.0` branch)
but emqx code is still at root level `src` and `priv` etc, we have not tested if this will affect emqx being used as a dependency.

**Comment by auror** [comment]
@zmstone 

Getting this error while running the bare minimum Elixir app, with EMQx as the dependency

```

15:11:12.256 [info]  event=server_setup_successfully driver=tcp socket="#Port<0.29>"

15:11:12.263 [info]  event=start
Starting emqx on node nonode@nohost

15:11:12.287 [info]      :alarm_handler: {:set, {:system_memory_high_watermark, []}}

15:11:12.835 [info]  Application emqx exited: exited in: :emqx_app.start(:normal, [])
    ** (EXIT) an exception was raised:
        ** (MatchError) no match of right hand side value: {:error, {:shutdown, {:failed_to_start_child, :emqx_sys_sup, {:shutdown, {:failed_to_start_child, :emqx_alarm, {:badarith, [{:erlang, :*, [:undefined, 1000], []}, {:timer, :seconds, 1, [file: 'timer.erl', line: 220]}, {:emqx_alarm, :init, 1, [file: '/Users/XXX/Programs/ei/deps/emqx/src/emqx_alarm.erl', line: 163]}, {:gen_server, :init_it, 2, [file: 'gen_server.erl', line: 417]}, {:gen_server, :init_it, 6, [file: 'gen_server.erl', line: 385]}, {:proc_lib, :init_p_do_apply, 3, [file: 'proc_lib.erl', line: 226]}]}}}}}}
            (emqx 4.2.7) /Users/XXX/Programs/ei/deps/emqx/src/emqx_app.erl:34: :emqx_app.start/2
            (kernel 7.2) application_master.erl:277: :application_master.start_it_old/4
** (Mix) Could not start application emqx: exited in: :emqx_app.start(:normal, [])
    ** (EXIT) an exception was raised:
        ** (MatchError) no match of right hand side value: {:error, {:shutdown, {:failed_to_start_child, :emqx_sys_sup, {:shutdown, {:failed_to_start_child, :emqx_alarm, {:badarith, [{:erlang, :*, [:undefined, 1000], []}, {:timer, :seconds, 1, [file: 'timer.erl', line: 220]}, {:emqx_alarm, :init, 1, [file: '/Users/XXX/Programs/ei/deps/emqx/src/emqx_alarm.erl', line: 163]}, {:gen_server, :init_it, 2, [file: 'gen_server.erl', line: 417]}, {:gen_server, :init_it, 6, [file: 'gen_server.erl', line: 385]}, {:proc_lib, :init_p_do_apply, 3, [file: 'proc_lib.erl', line: 226]}]}}}}}}
            (emqx 4.2.7) /Users/XXX/Programs/ei/deps/emqx/src/emqx_app.erl:34: :emqx_app.start/2
            (kernel 7.2) application_master.erl:277: :application_master.start_it_old/4
[os_mon] memory supervisor port (memsup): Erlang has closed
[os_mon] cpu supervisor port (cpu_sup): Erlang has closed

```

**Comment by zmstone** [comment]
Hi @auror 

emqx application requires configs generated from emqx.conf
ref: https://github.com/emqx/emqx-rel/blob/master/bin/emqx#L209-L250
