### ISSUE TITLE
Any recommendation on topic hierarchy limit?

### ISSUE THREAD

**Issue by xlb0479** [emqx/emqx#2661]
#### Environment

- OS:  ubuntu18
- Erlang/OTP:  21
- EMQ: 3.2

#### Description
I may have a topic more than 12 levels ,a/b/c/d/e/f..., eg. But I am wonderring if emqx perform as good as 2 or 3 levels of topic. Will I sufferring a performance lose?
Is topic levels a key factor on emqx's performance?
Thanks.

**Comment by terry-xiaoyu** [comment]
Emqx uses a [Trie](https://en.wikipedia.org/wiki/Trie) as the data structure for matching topics, for example, before delivering an MQTT PUBLISH message, so it is efficient.

But it do need more memory footprint and more time if you use topics with many levels, so keep it as  short as possible.
