### ISSUE TITLE
How to send message to one special client without sending to the others who're in the same topic.

### ISSUE THREAD

**Issue by jjuu** [emqx/emqx#2669]
I have clients who have subscribe the same topic. Now I want to publish message to one special subscriber, not send it to the others. Is it already supported by the emqx? Or is this must be done by a workaround way?

Thank you very much for your help.

**Comment by HJianBo** [comment]
No, there is no way or workaround to send it. And you can't design the architecture of topic.

Besides, The shared topic can dispatch message to one of group subscriber, but can not by specified by custom.

**Comment by jjuu** [comment]
Here's my idea. I want to use the hook to help client to subscribe a topic. For example, if he subscribe "topic/test", then the server will help to subscribe another "topic/test/<client_id>". What do you think of it, it isn't a workaround way? @HJianBo

**Comment by jjuu** [comment]
I have decided to help client to auto-subscribe a user topic, setting the "module.subscription" to "on".
Thanks for your help.

**Comment by wsysx123** [comment]
> Yes, it is. But the `mountpoint` is better for you. A client can be assigned a mountpoint property after connected emqx. e.g: `etc/emqx.conf`:
> 
> ```ini
> ## All the topics will be prefixed with the mountpoint path if this option is enabled.
> ##
> ## Variables in mountpoint path:
> ##  - %c: clientid
> ##  - %u: username
> ##
> ## Value: String
> zone.external.mountpoint = %c/
> ```
> 
> If a client's mountpoint is `client_id_1`. it really subscribed topic is `client_id_1/test` when the client subscribe to topic `test`. So, it can recevie the message published to `client_id_1/test`.
> 
> So using mountpoint allows you to distinguish between different clients of the same topic.
> 
> Besides, the [emqx_auth_http](https://github.com/emqx/emqx-auth-http) allow your web server to return a mountpoint for a connection.
> 
> Hope it works for you.

I have tried your advice,one of my device's clientId is client1,and the topic show in dashboard is %c/dev/devId/command  ,So I think if I want to pulish to this topic,I should publish to client1/dev/devId/command .But the client didn't get it. And if publish to /dev/devId/command ,all client will get it.I want to know how to solve it,thanks a lot!

**Comment by Gilbert-Wong** [comment]
Sorry, in your scenario, you have to set one special topic for one special client.

**Comment by HJianBo** [comment]
@wsysx123 Yeah, you should publish message to `client1/dev/devId/command` topic if the client mountpoint is undefined. 

But, if the pub client has a mountpoint, the topic will be added a prefix automatically. So the `/dev/devId/command` works instead of `client1/dev/devId/command`
