### ISSUE TITLE
lots of topics and sessions are  suddenly  dropped while in a production environment

### ISSUE THREAD

**Issue by GerogeLeon** [emqx/emqx#2670]
#### Environment

- OS: Ubuntu 16.04.5 LTS
- Erlang/OTP:  emq bult-in erlang 
- EMQ: v3.1.0

## the abnormal phenomenon:
![image](https://user-images.githubusercontent.com/25131163/60561280-9b1b9c80-9d85-11e9-833a-8a1633553e22.png)

## while the cpu/memory stays in normal status:
![image](https://user-images.githubusercontent.com/25131163/60560699-69a1d180-9d83-11e9-867c-448f6358be0b.png)

## i think:
that is strange, there may be a critical bug...  By the way, i have to complain that the emq doc is  so rough that it hardly afford a production use

**Comment by HJianBo** [comment]
Hi, @GerogeLeon sorry to hear about that. In emqx3.0 we continue to improve the documentation experience. It will better in the future

Besides, can you provide more detailed log after something dropped?

**Comment by GerogeLeon** [comment]
There are a mass of  errors in emqx.log.1 showed beneath, and they are the same.
The machine is [AWS t2.medium ](https://aws.amazon.com/ec2/instance-types/) that is 2 core 4GB mem.

I think that the error refers to the configuration `zone.external.idle_timeout = 15s` , but i am confused by its inconsistent explanation between in [the configuration file `emqx.conf`](https://github.com/emqx/emqx/blob/v3.1.0/etc/emqx.conf) and in [the web document](https://developer.emqx.io/docs/broker/v3/en/config.html#external-zone-parameter-settings). I don't know which one is the real.

I have tried to increase `zone.external.idle_timeout` to 60s, but it did not solve this massive error. howerver, some client connection failures occured, which had not occured before, while the  CPU/MEM was still sufficient.

I have searched the document, but have not seen any thing about this error. 

I want to know what is wrong with emq? 
what is the real meaning of `zone.external.idle_timeout`?


```
2019-07-04 00:12:45.025 [error] 172.31.19.149:6250 crasher:
    initial call: emqx_connection:init/1
    pid: <0.14331.384>
    registered_name: []
    exception exit: idle_timeout
      in function  gen_statem:loop_event_result/9 (gen_statem.erl, line 1158)
    ancestors: [<0.10780.13>,<0.10779.13>,esockd_sup,<0.10607.13>]
    message_queue_len: 0
    messages: []
    links: [<0.10780.13>]
    dictionary: [{force_shutdown_policy,
                      #{max_heap_size => 0,message_queue_len => 0}},
                  {'$logger_metadata$',#{peername => "172.31.19.149:6250"}}]
    trap_exit: false
    status: running
    heap_size: 6772
    stack_size: 27
    reductions: 99122
  neighbours:
2019-07-04 00:12:46.182 [error] 172.31.54.165:6270 ** State machine <0.20457.385> terminating
** Last event = {timeout,15000}
** When server state  = {idle,
                            {state,esockd_transport,#Port<0.2321611>,
                                {{172,31,54,165},6270},
                                undefined,running,100,
                                {pstate,external,
                                    #Fun<emqx_connection.0.73284863>,...},
                                {none,#{...}},
                                {...},...}}
** Reason for termination = exit:idle_timeout
** Callback mode = [state_functions,state_enter]
** Stacktrace =
**  [{gen_statem,loop_event_result,9,[{file,"gen_statem.erl"},{line,1158}]},
     {proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,249}]}]

```

**Comment by HJianBo** [comment]
The `idle_timeout` is 'The maximum time to wait for MQTT CONNECT packet after the TCP connection is established'

There are some tips:

- Check the speed of Network I/O.
- Tune the os parameters according to https://developer.emqx.io/docs/broker/v3/en/tune.html

In addition, could you provide all type errors to help me dig it

**Comment by alpha0geek** [comment]
@GerogeLeon Have you found any solution to this issue?

**Comment by GerogeLeon** [comment]
no

**Comment by GerogeLeon** [comment]
I have been considering switching to VerneMQ. 
I think there should be a critical implication problem in EMQX which  could not afford massive connections under a production load

**Comment by alpha0geek** [comment]
@GerogeLeon btw which analytics tool are you using for the graphs in your original post?

**Comment by GerogeLeon** [comment]
i was using AliYun cloud log service, but the emqx system topics should be subscribed and logged to a file whose content  is collected by the log service agent

**Comment by HJianBo** [comment]
Hi guys, Imo, These abnormal phenomenons is not caused by `idle_timeout`. This option just work for the maximum timeout after TCP established. And the normal curve lasted for more than 10 hours.

So there must have been some kind of problem at ’2019_07_02_09:50:28'. But I can't find out the problem by these illustration only.

Besides,  I have found a so weird part of chart when the 'Session dropped'.  **The Session count less than Connection count!!!**.  This is impossible in emqx because the number of sessions must be greater than or equal to connection!!

So, @GerogeLeon Which sys topics are these curves collected?

**Comment by GerogeLeon** [comment]
$SYS/brokers/${node}/stats/connections/count
$SYS/brokers/${node}/stats/sessions/count	

see: https://docs.emqx.io/broker/v3/en/guide.html#statistics
