### ISSUE TITLE
emqx 3.1.1 mongo authentication

### ISSUE THREAD

**Issue by csafu** [emqx/emqx#2672]
#### Environment

- OS: 
centos 6.5  /  windows 7
- EMQ: 
EMQX 3.1.1

#### Description

Hello,
I'm enable to mongodb plugin  authenticate to the broker, the settings is like this:

**in emqx.conf:**
allow_anonymous = false
acl_nomatch = allow

**plugin configs: emqx_auth_mongo.conf:**

auth.mongo.type = single
auth.mongo.server = 127.0.0.1:35248
auth.mongo.pool = 8
auth.mongo.database = fuyooiot_db
auth.mongo.login = fuyooiot
auth.mongo.password = fuyoo123$%
auth.mongo.topology.pool_size = 1
auth.mongo.topology.max_overflow = 0
auth.mongo.auth_query.collection = mqtt_users
auth.mongo.auth_query.password_field = password
auth.mongo.auth_query.password_hash = plain
auth.mongo.auth_query.selector = username=%u
auth.mongo.super_query = on
auth.mongo.super_query.collection = mqtt_users
auth.mongo.super_query.super_field = is_superuser
auth.mongo.super_query.selector = username=%u
auth.mongo.acl_query = on
auth.mongo.acl_query.collection = mqtt_acls
auth.mongo.acl_query.selector = username=%u

when i tried to connect using the username and password, i can see the broker making database requests but i couldnt get authenticated

**log error like this:**
2019-07-05 17:19:43.365 [error] crasher:
    initial call: mc_worker:init/1
    pid: <0.19155.2>
    registered_name: []
    exception error: <<"Can't pass authentification">>
      in function  mc_auth_logic:scram_sha_1_auth/5 (src/connection/mc_auth_logic.erl, line 55)
      in call from mc_worker:auth_if_credentials/5 (src/connection/mc_worker.erl, line 219)
      in call from mc_worker:init/1 (src/connection/mc_worker.erl, line 54)
    ancestors: [<0.2075.1>,<0.2074.1>,<0.1881.1>,<0.1880.1>,<0.1878.1>,
                  <0.1877.1>,<0.1875.1>,emqx_auth_mongo_sup,<0.1873.1>]
    message_queue_len: 0
    messages: []
    links: [<0.2075.1>,#Port<0.77029>,<0.2074.1>]
    dictionary: [{rand_seed,{#{jump => #Fun<rand.16.10897371>,
                                max => 288230376151711743,
                                next => #Fun<rand.15.10897371>,
                                type => exsplus},
                              [157979707231883450|120994963489259874]}}]
    trap_exit: false
    status: running
    heap_size: 987
    stack_size: 27

**Every times I use ./bin/emqx start and ./bin/emqx_ctl plugins reload emqx_auth_mongo restarted.
Can anybody help me?**

**Comment by HJianBo** [comment]
Hi, @csafu Sorry for late reply. Is the problem has solved? 

I have copied above configurations, but it works well for me.

Could you provide the mongo version?
