### ISSUE TITLE
emqx_auth_http not receive websocket cookie

### ISSUE THREAD

**Issue by frlzk** [emqx/emqx#2676]
#### Environment

- OS: ubuntu
- Erlang/OTP: 21.3
- EMQ: 3.2

#### Description
Use WebSocket connect emq. I can see cookie in web browser,but can not receive cookie in my web application. Username and password can receivce.

**Comment by Gilbert-Wong** [comment]
Sorry, @frlzk, the emqx could receive cookie info from the websocket connection. However, there is no auth plugin to do the auth check for cookie. We'll add emqx_auth_cookie plugin based on the websocket cookie in the future.

**Comment by frlzk** [comment]
Please support put cookie to http header
