### ISSUE TITLE
ClientId in ACL does not allow %c

### ISSUE THREAD

**Issue by lcofre** [emqx/emqx#2677]
#### Environment

- OS: Ubuntu 18.04.1 LTS
- Erlang/OTP: 
- EMQ: v3.1.2 (using docker image emqx/emqx:v3.1.2)

#### Description

Trying to make all clients able to subscribe only to a topic with their ClientId on it, I added these rules to acl.conf

```
{allow, {client, "%c"}, subscribe, ["some_prefix/%c"]}.

{deny, all}.
```

Now when I hardcode the ClientId it works:
```
{allow, {client, "the_client_id"}, subscribe, ["some_prefix/%c"]}.

{deny, all}.
```

How can I achieve this without adding all possible clients to the ACL config?

Thank you very much for your help

**Comment by Gilbert-Wong** [comment]
Yes, @lcofre, for now, the "%c" can only be used in the topic. To achieve your goal, I suggest you try the plugin `emqx_auth_clientid`. Hope my answer could help you.

**Comment by lcofre** [comment]
Thanks very much for your answer and suggestion.

I am closing it now and relating it with an issue it duplicates.

Thanks for your help.
Duplicate of #1672
