### ISSUE TITLE
Acl table allow- access problem

### ISSUE THREAD

**Issue by Aycayilmz** [emqx/emqx#2681]
When I change the access and permission values ​​in the Acl table, it has no effect. What exactly is pubsub, public, and allow? How to use?
For example, user A can only read, users B and C can both read and write. How can I do that?

**Comment by Gilbert-Wong** [comment]
Here is the doc of the acl mechanism in emqx: https://developer.emqx.io/docs/broker/v3/en/config.html#anonymous-authentication-and-acl-files Hope this doc could help you.
