### ISSUE TITLE
I can't remove Message Rule In the DashBoard

### ISSUE THREAD

**Issue by wsysx123** [emqx/emqx#2682]
#### Environment

- OS: Centos
- Erlang/OTP: R21/10.3.4
- EMQ: v3.1.0

#### Description
I installed the EMQ by docker from Aliyun,I think there may be a bug in the Dashboard about Message Rule.When I want to remove a rule,click 'remove',and it alert 'Delete success',but this rule is still effective and I can see it in dashboard.I want to know if I can delete rule by remove any files?

**Comment by Gilbert-Wong** [comment]
Hi, @wsysx123, the rule engine in emqx v3.1.0 is very immature, I recommend you to try the latest emqx release candidate version. By the way, we'll release the final version of emqx 3.2.0 this week.
