### ISSUE TITLE
static nodes auto cluster

### ISSUE THREAD

**Issue by mikeHuangHao** [emqx/emqx#2684]
#### Environment

- OS: ubuntu
- Erlang/OTP:  
- EMQ: EMQ X Broker/3.2-beta.3

Description

请问基于 static 节点列表自动集群，其中一个宕机后，使用emqx_ctl cluster status发现还在集群中

Excuse me, an automatic cluster based on the static node list, one of which is still in the cluster after downtime using emqx_ctl cluster status

**Comment by zhanghongtong** [comment]
Sorry, I can't reply your issue, please provide more information
