### ISSUE TITLE
idle_timeout of mqtt connecting  while the CPU/MEM is sufficient

### ISSUE THREAD

**Issue by GerogeLeon** [emqx/emqx#2686]
#### Environment

- OS: Ubuntu 16.04.5 LTS, 2core8GB
- Erlang/OTP: emq bult-in erlang
- EMQ: v3.1.0

#### Description
![image](https://user-images.githubusercontent.com/25131163/61036488-cb091680-a3fb-11e9-9fb1-c2ec3e08ab92.png)
While the CPU usage is 23.8%  and the MEM usage is 4.0%,  lots of idle_timeout occur, why is that??
What is the problem with emqx?
I tried VerneMQ, there was no these errors.

## config:
the OS have been tuned according to [the official doc](https://developer.emqx.io/docs/broker/v3/en/tune.html).

emqx config:
[emqx.txt](https://github.com/emqx/emqx/files/3381154/emqx.txt)

## idle_timeout error:
```
2019-07-10 23:52:16.500 [error] 172.31.71.193:63414 ** State machine <0.18524.2598> terminating
** Last event = {timeout,15000}
** When server state  = {idle,
                            {state,esockd_transport,#Port<0.17948958>,
                                {{172,31,71,193},63414},
                                undefined,running,100,
                                {pstate,external,
                                    #Fun<emqx_connection.0.73284863>,...},
                                {none,...},
                                {...},...}}
** Reason for termination = exit:idle_timeout
** Callback mode = [state_functions,state_enter]
** Stacktrace =
**  [{gen_statem,loop_event_result,9,[{file,"gen_statem.erl"},{line,1158}]},
     {proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,249}]}]
2019-07-10 23:52:16.501 [error] 172.31.71.193:63414 crasher:
    initial call: emqx_connection:init/1
    pid: <0.18524.2598>
    registered_name: []
    exception exit: idle_timeout
      in function  gen_statem:loop_event_result/9 (gen_statem.erl, line 1158)
    ancestors: [<0.1615.0>,<0.1614.0>,esockd_sup,<0.1353.0>]
    message_queue_len: 0
    messages: []
    links: [<0.1615.0>]
    dictionary: [{force_shutdown_policy,
                      #{max_heap_size => 0,message_queue_len => 0}},
                  {'$logger_metadata$',#{peername => "172.31.71.193:63414"}}]
    trap_exit: false
    status: running
    heap_size: 6772
    stack_size: 27
    reductions: 99046
  neighbours:
```

**Comment by terry-xiaoyu** [comment]
Idle timeout means emqx wait for MQTT CONNECT packet timeout after TCP connection is established. You could inspect your MQTT client to find out the problem.

**Comment by ioiogamboa** [comment]
I have similar problem. I have two clients that makes a subscriptions more than 60 seg.  And close connection. I need to disable client_idle_timeout or set to large value like 250 segs. Clients were not configured to send connection signal. But Emqx 4.3 don't have client_idle_timeout, old version 2.0 yes it has. How do I solve problem from server without reprogram client?
