### ISSUE TITLE
emqx-windows10-v3.1.2.zip has wrong version info

### ISSUE THREAD

**Issue by Forsure-Wang** [emqx/emqx#2688]
#### Environment

- OS:  windows 10
- Erlang/OTP:  22 [erts-10.4] [64-bit] [smp:6:6] [ds:6:6:10] [async-threads:32]
- EMQ:  3.1.2

#### Description

*I installed the emqx v3.1.2 windows version,but I saw the version info is 3.0.0 in dashboard and Erlang console*

![image](https://user-images.githubusercontent.com/17527834/61065421-2fe16280-a436-11e9-9a0a-9dad22c374ce.png)

![image](https://user-images.githubusercontent.com/17527834/61065181-bfd2dc80-a435-11e9-8a55-779791331637.png)

![image](https://user-images.githubusercontent.com/17527834/61065310-00caf100-a436-11e9-89f2-77d67d987ec0.png)

**Comment by Forsure-Wang** [comment]
And the plugins' version are not correct either,please check it.

![image](https://user-images.githubusercontent.com/17527834/61095386-e6206880-a485-11e9-8a6e-dc8f5ebc5f84.png)

**Comment by zhanghongtong** [comment]
Sorry that our 3.1.2 support for Windows is not perfect, we suggest using our 3.2.0 version on Windows
