### ISSUE TITLE
Hight Resources Consumption and EMQ shutdown when Subscribing with "#" or "+" topic

### ISSUE THREAD

**Issue by Richard9999** [emqx/emqx#2689]
#### Environment

- OS: CentOS 7 
- Erlang/OTP: R22
- EMQ: V3.0.1

#### Description
Here is the problem:
I use benchmark to imitate pub and sub, in order to figure out the max connection on different conditions. However, when I established 1000 connections for sub with "#", the server can only receive around 4000 connections for pub, and the memory exhausted dramatically, CPU went to 97%. it continued for about 1 min until emqx process shutdown. And when I established 50 connections for sub, and 20,000 connections for pub, this also resulted to emqx shutdown. At the same time, cpu went to 90% on mysql server. So according to the description, can I say even there is only one sub with "#" topic can surely result to shutdown of emqx and high cpu/mem resources consumption once there are too many connection, such as more than millions. 
I raise this issue to make sure whether I can use "#" or "+" to receive all messages from different topics, and how many sub like this I can establish. (pics as follow)

![EMQ-Status-#-topic-C](https://user-images.githubusercontent.com/27894059/61198640-76bcaa00-a70d-11e9-97d3-ac04ca558578.jpg)
![EMQ-Status-#-topic-M](https://user-images.githubusercontent.com/27894059/61198649-7d4b2180-a70d-11e9-9a10-2a4cc63c6342.jpg)
![Uploading EMQ-Status-#-topic-N.jpg…]()

**Comment by Richard9999** [comment]
I have no idea why I was kept waiting so long for answer to this question, it's been almost ONE month.

**Comment by terry-xiaoyu** [comment]
I guess the publish speed you were using is 1 msg per second on each process. If so the through put is 4K pub * 1K sub = 4M msg/s. That's too high for a single emqx broker to handle.

See our benchmark for details:

https://emq-xmeter-benchmark-en.readthedocs.io/en/latest/throughput.html or the Chinese one:
https://emq-xmeter-benchmark-cn.readthedocs.io/en/latest/throughput.html
