### ISSUE TITLE
Load emqx_web_hook plugin high CPU

### ISSUE THREAD

**Issue by huangyang1230** [emqx/emqx#2692]
#### Environment

- OS: ubuntu
- Erlang/OTP: 
- EMQ: 3.0

#### Description

*A description of the issue*
问题描述：
ubuntu V3.0 开启emqx_web_hook插件内存彪高卡死
现象：
![2](https://user-images.githubusercontent.com/19583387/61281733-b7d7bb80-a7ec-11e9-9036-99f67879d067.png)
![5](https://user-images.githubusercontent.com/19583387/61281753-bf976000-a7ec-11e9-8f67-b820e17016d3.png)
结果：
程序卡死
![4](https://user-images.githubusercontent.com/19583387/61281816-da69d480-a7ec-11e9-9128-7bb38fcd251e.png)
进程信息：
![3](https://user-images.githubusercontent.com/19583387/61281871-efdefe80-a7ec-11e9-8eb8-e578c53665c0.png)

**Comment by HJianBo** [comment]
Hi, @huangyang1230 Thanks for your feedback. 

This problem has bee fixed at v3.1, please check it!
