### ISSUE TITLE
mysql plugin load failed

### ISSUE THREAD

**Issue by dremfly** [emqx/emqx#2693]
#### Environment

- OS: centos7
- Erlang/OTP: 
- EMQ: 3.1.0

#### Description
mysql：8.0
已经设置default_authentication_plugin=mysql_native_password
root账户也改为mysql_native_password了，
启动插件报如下错误：
RPC to emqx@127.0.0.1 failed: timeout

**Comment by Gilbert-Wong** [comment]
Please give me more detailed logs. Thanks for your feedback.

**Comment by dremfly** [comment]
请问查看哪个日志文件，/var/log下的日志都看了，没有收获

**Comment by ioticos** [comment]
I am in the same,

Environment
OS: Ubuntu 18.04 LTS
Erlang/OTP:
EMQ: 3.1.0

**Comment by dremfly** [comment]
> Please give me more detailed logs. Thanks for your feedback.

please

**Comment by ioticos** [comment]
When I start in console mode, the only thing I see is what I pasted above.

One of those appears for each attempt to connect mqtt to the broker.

For a few moments it does not throw anything and it seems to work ok.

I put an incorrect password on the client to see if he rejects everything ok

I put back a correct password and it connects!

Then I put back an incorrect and connects :(

I look at the terminal and again the text that I detailed above appears on the console

I teach a course on IoT in udemy and base our practices with this excellent development.

We are about 180 students testing from version 3.0.1 to the last, having this type of instability give the mysql plugin.

By the way, I added in "environment" the fact that we work with an ec2 of aws.

We will be grateful for any help.

Pablo

**Comment by ioticos** [comment]
In my case, 
## Value: Number
auth.mysql.pool = 8

to

**Comment by dremfly** [comment]
> In my case, in emqx_auth_mysql.conf
> 
> ## Value: Number
> auth.mysql.pool = 8
> 
> to
> 
> ## Value: Number
> auth.mysql.pool = 1
> 
> and problem fixed.
> 
> Thanks to all
> 
> Pablo

when i upgrade to 3.2.0 version,my problem was solved
