### ISSUE TITLE
Websocket report error when websocket connection is disconnected

### ISSUE THREAD

**Issue by XuchengJie** [emqx/emqx#2695]
#### Environment

- OS: CentOS Linux release 7.6.1810
- Erlang/OTP: Erlang/OTP 21
- EMQ: v3.2.0

#### Description
Websocket连接无论是正常退出还是异常退出，都会有两条错误日志。
2019-07-18 17:15:32.334 [error] Ranch listener 'mqtt:ws' had connection process started with cowboy_clear:start_link/4 at <0.1717.0> exit with reason: {error,remote}
2019-07-18 17:15:32.334 [error] mqttjs_4128559ea6 ** Generic server <0.1720.0> terminating 
** Last message in was {'EXIT',<0.1717.0>,{error,remote}}
** When Server state == {state,external,15000,true,
                            #Fun<emqx_session.1.109586832>,
                            <<"mqttjs_4128559ea6">>,<<>>,undefined,undefined,
                            1,#{},
                            {emqx_inflight,32,{0,nil}},
                            undefined,
                            {mqueue,true,1000,0,0,none,infinity,
                                {queue,[],[],0}},
                            #{},undefined,0,undefined,undefined,
                            {emqx_gc,
                                #{cnt => {1000,1000},
                                  oct => {1048576,1048576}}},
                            {1563,441331,73178},
                            undefined,undefined}
** Reason for termination == 
** {error,remote}

2019-07-18 17:27:21.867 [error] Ranch listener 'mqtt:ws' had connection process started with cowboy_clear:start_link/4 at <0.1958.0> exit with reason: {error,{remote,1001,<<>>}}
2019-07-18 17:27:21.867 [error] mqttjs_4128559ea6 ** Generic server <0.1961.0> terminating 
** Last message in was {'EXIT',<0.1958.0>,{error,{remote,1001,<<>>}}}
** When Server state == {state,external,15000,true,
                            #Fun<emqx_session.1.109586832>,
                            <<"mqttjs_4128559ea6">>,<<>>,undefined,undefined,
                            1,#{},
                            {emqx_inflight,32,{0,nil}},
                            undefined,
                            {mqueue,true,1000,0,0,none,infinity,
                                {queue,[],[],0}},
                            #{},undefined,0,undefined,undefined,
                            {emqx_gc,
                                #{cnt => {1000,1000},
                                  oct => {1048576,1048576}}},
                            {1563,442040,593308},
                            undefined,undefined}
** Reason for termination == 
** {error,{remote,1001,<<>>}}

导致日志文件增长非常快。

**Comment by Gilbert-Wong** [comment]
Hi, @XuchengJie, in emqx 3.2.0, if your websocket client disconnects without sending disconnect packet, this error will be printed in the logs. However, this issue has been resolved in this [pull request](https://github.com/emqx/emqx/pull/2697), it will be released as 3.2.1. Anyway, thanks for you feedback.
