### ISSUE TITLE
MySQL plugin not function correctly after upgrade to 3.2.1

### ISSUE THREAD

**Issue by chan1600** [emqx/emqx#2712]
#### Environment

- OS: ubuntu 18.04
- Erlang/OTP: 
- EMQ: 3.2.1

#### Description
MySQL plugin keeps crashing after upgrade from 3.1.1. Do you know what the issue it?
my client is connected to the broker in the same machine.

```
2019-07-22 20:07:36.483 [error] client@127.0.0.1:49204 crasher:
    initial call: emqx_channel:init/1
    pid: <0.10238.0>
    registered_name: []
    exception exit: {noproc,
                        {gen_server,call,
                            [<0.5558.0>,
                             {param_query,
                                 "select allow, ipaddr, username, clientid, access, topic from MqttAcl where ipaddr = ? or username = ? or username = '$all' or clientid = ?",
                                 ["127.0.0.1",<<"user_name">>,<<"client">>],
                                 no_filtermap_fun,default_timeout},
                             infinity]}}
      in function  gen_server:call/3 (gen_server.erl, line 223)
      in call from mysql:query_call/2 (/tmp/emqx/v3.2.1/_checkouts/mysql/src/mysql.erl, line 751)
      in call from emqx_acl_mysql:do_check_acl/5 (/tmp/emqx/v3.2.1/_checkouts/emqx_auth_mysql/src/emqx_acl_mysql.erl, line 40)
      in call from emqx_acl_mysql:check_acl/5 (/tmp/emqx/v3.2.1/_checkouts/emqx_auth_mysql/src/emqx_acl_mysql.erl, line 31)
      in call from emqx_hooks:do_run_fold/3 (/tmp/emqx/v3.2.1/_checkouts/emqx/src/emqx_hooks.erl, line 131)
      in call from emqx_access_control:do_check_acl/3 (/tmp/emqx/v3.2.1/_checkouts/emqx/src/emqx_access_control.erl, line 59)
      in call from emqx_access_control:check_acl/3 (/tmp/emqx/v3.2.1/_checkouts/emqx/src/emqx_access_control.erl, line 50)
      in call from emqx_protocol:do_acl_check/5 (/tmp/emqx/v3.2.1/_checkouts/emqx/src/emqx_protocol.erl, line 1047)
    ancestors: [<0.4243.0>,<0.4242.0>,esockd_sup,<0.4068.0>]
    message_queue_len: 0
    messages: []
    links: [<0.4243.0>,<0.10242.0>]
    dictionary: [{rand_seed,
                      {#{bits => 58,jump => #Fun<rand.8.10897371>,
                         next => #Fun<rand.5.10897371>,type => exrop,
                         uniform => #Fun<rand.6.10897371>,
                         uniform_n => #Fun<rand.7.10897371>,
                         weak_low_bits => 1},
                       [237205485413575794|220086341180577563]}},
                  {force_shutdown_policy,
                      #{max_heap_size => 838860800,message_queue_len => 8000}},
                  {acl_cache_size,1},
                  {acl_keys_q,{[{publish,<<"dm/status">>}],[]}},
                  {{publish,<<"dm/status">>},{allow,1563826056462}},
                  {incoming_bytes,165},
                  {guid,{1563826056464360,268568599996414,2}},
                  {'$logger_metadata$',
                      #{client_id => <<"client">>,
                        peername => "127.0.0.1:49204"}}]
    trap_exit: true
    status: running
    heap_size: 28690
    stack_size: 27
    reductions: 505812
  neighbours:



2019-07-22 20:07:36.464 [error] client@127.0.0.1:49204 ** State machine <0.10238.0> terminating
** Last event = {cast,
                    {incoming,
                        {mqtt_packet,
                            {mqtt_packet_header,8,false,1,false},
                            {mqtt_packet_subscribe,48093,undefined,
                                [{<<"client/#">>,
                                  #{nl => 0,qos => 2,rap => 0,rc => 0,
                                    rh => 0}},
                                 {<<"frontend/request/#">>,
                                  #{nl => 0,qos => 2,rap => 0,rc => 0,
                                    rh => 0}},
                                 {<<"admin/request/#">>,
                                  #{nl => 0,qos => 2,rap => 0,rc => 0,
                                    rh => 0}}]},
                            undefined}}}
** When server state  = {connected,
                         {state,esockd_transport,
                          {ssl_socket,#Port<0.1059>,
                           {sslsocket,
                            {mqtt_packet_subscribe,48093,undefined,
                                [{<<"client/#">>,
                                  #{nl => 0,qos => 2,rap => 0,rc => 0,
                                    rh => 0}},
                                 {<<"frontend/request/#">>,
                                  #{nl => 0,qos => 2,rap => 0,rc => 0,
                                    rh => 0}},
                                 {<<"admin/request/#">>,
                                  #{nl => 0,qos => 2,rap => 0,rc => 0,
                                    rh => 0}}]},
                            undefined}}}
** When server state  = {connected,
                         {state,esockd_transport,
                          {ssl_socket,#Port<0.1059>,
                           {sslsocket,
                            {gen_tcp,#Port<0.1059>,tls_connection,undefined},
                            [<0.10240.0>,<0.10239.0>]}},
                          {{127,0,0,1},49204},
                          undefined,running,100,
                          {pstate,external,#Fun<emqx_channel.0.83793538>,
                           {{127,0,0,1},8883},
                           {{127,0,0,1},49204},
                           undefined,4,<<"MQTT">>,<<"client">>,false,
                           <0.10238.0>,undefined,undefined,<<"user_name">>,
                           <0.10242.0>,true,#{},undefined,undefined,60,false,
                           #{msg => 0,pkt => 1},
                           #{msg => 0,pkt => 1},
                           true,
                           {1563,826056,461361},
                           #{from_client => 0,to_client => 0},
                           emqx_channel,
                           #{anonymous => false,auth_result => success,
                             client_id => <<"client">>,
                             is_superuser => false,mountpoint => undefined,
                             peername => {{127,0,0,1},49204},
                             sockname => {{127,0,0,1},8883},
                             username => <<"user_name">>,ws_cookie => undefined,
                             zone => external},
                           undefined},
                          {none,#{max_size => 268435456,version => 4}},
                          {emqx_gc,
                           #{cnt => {1000,998},oct => {1048576,1048411}}},
                          {keepalive,#Fun<emqx_channel.3.83793538>,464,45,
                           {keepalive,check},
                           #Ref<0.972920636.2613837825.89884>,0},
                          undefined,undefined,undefined,true,
                          #Ref<0.972920636.2613837825.89877>,15000}}
** Reason for termination = exit:{noproc,
                                  {gen_server,call,
                                   [<0.5558.0>,
                                    {param_query,
                                     "select allow, ipaddr, username, clientid, access, topic from MqttAcl where ipaddr = ? or username = ? or username = '$all' or clientid = ?",
                                     ["127.0.0.1",<<"user_name">>,
                                      <<"client">>],
                                     no_filtermap_fun,default_timeout},
                                    infinity]}}
** Callback mode = [state_functions,state_enter]
** Queued = [{cast,
                 {incoming,
                     {mqtt_packet,
                         {mqtt_packet_header,3,false,2,true},
                         {mqtt_packet_publish,<<"dm/status">>,48094,undefined},
                         <<"Online\n">>}}}]
** Stacktrace =
**  [{gen_server,call,3,[{file,"gen_server.erl"},{line,223}]},
     {mysql,query_call,2,
            [{file,"/tmp/emqx/v3.2.1/_checkouts/mysql/src/mysql.erl"},
             {line,751}]},
     {emqx_acl_mysql,do_check_acl,5,
                     [{file,"/tmp/emqx/v3.2.1/_checkouts/emqx_auth_mysql/src/emqx_acl_mysql.erl"},
                      {line,40}]},
     {emqx_acl_mysql,check_acl,5,
                     [{file,"/tmp/emqx/v3.2.1/_checkouts/emqx_auth_mysql/src/emqx_acl_mysql.erl"},
                      {line,31}]},
     {emqx_hooks,do_run_fold,3,
                 [{file,"/tmp/emqx/v3.2.1/_checkouts/emqx/src/emqx_hooks.erl"},
                  {line,131}]},
     {emqx_access_control,do_check_acl,3,
                          [{file,"/tmp/emqx/v3.2.1/_checkouts/emqx/src/emqx_access_control.erl"},
                           {line,59}]},
     {emqx_access_control,check_acl,3,
                          [{file,"/tmp/emqx/v3.2.1/_checkouts/emqx/src/emqx_access_control.erl"},
                           {line,50}]},
     {emqx_protocol,do_acl_check,5,
                    [{file,"/tmp/emqx/v3.2.1/_checkouts/emqx/src/emqx_protocol.erl"},
                     {line,1047}]}]

2019-07-22 20:07:36.483 [error] client@127.0.0.1:49204 crasher:
    initial call: emqx_channel:init/1
    pid: <0.10238.0>
    registered_name: []
    exception exit: {noproc,
                        {gen_server,call,
                            [<0.5558.0>,
                             {param_query,
                                 "select allow, ipaddr, username, clientid, access, topic from MqttAcl where ipaddr = ? or username = ? or username = '$all' or clientid = ?",
                                 ["127.0.0.1",<<"user_name">>,<<"client">>],
                                 no_filtermap_fun,default_timeout},
                             infinity]}}
      in function  gen_server:call/3 (gen_server.erl, line 223)
      in call from mysql:query_call/2 (/tmp/emqx/v3.2.1/_checkouts/mysql/src/mysql.erl, line 751)
      in call from emqx_acl_mysql:do_check_acl/5 (/tmp/emqx/v3.2.1/_checkouts/emqx_auth_mysql/src/emqx_acl_mysql.erl, line 40)
      in call from emqx_acl_mysql:check_acl/5 (/tmp/emqx/v3.2.1/_checkouts/emqx_auth_mysql/src/emqx_acl_mysql.erl, line 31)
      in call from emqx_hooks:do_run_fold/3 (/tmp/emqx/v3.2.1/_checkouts/emqx/src/emqx_hooks.erl, line 131)
      in call from emqx_access_control:do_check_acl/3 (/tmp/emqx/v3.2.1/_checkouts/emqx/src/emqx_access_control.erl, line 59)
      in call from emqx_access_control:check_acl/3 (/tmp/emqx/v3.2.1/_checkouts/emqx/src/emqx_access_control.erl, line 50)
      in call from emqx_protocol:do_acl_check/5 (/tmp/emqx/v3.2.1/_checkouts/emqx/src/emqx_protocol.erl, line 1047)
    ancestors: [<0.4243.0>,<0.4242.0>,esockd_sup,<0.4068.0>]
    message_queue_len: 0
    messages: []
    links: [<0.4243.0>,<0.10242.0>]
    dictionary: [{rand_seed,
                      {#{bits => 58,jump => #Fun<rand.8.10897371>,
                         next => #Fun<rand.5.10897371>,type => exrop,
                         uniform => #Fun<rand.6.10897371>,
                         uniform_n => #Fun<rand.7.10897371>,
                         weak_low_bits => 1},
                       [237205485413575794|220086341180577563]}},
                  {force_shutdown_policy,
                      #{max_heap_size => 838860800,message_queue_len => 8000}},
                  {acl_cache_size,1},
                  {acl_keys_q,{[{publish,<<"dm/status">>}],[]}},
                  {{publish,<<"dm/status">>},{allow,1563826056462}},
                  {incoming_bytes,165},
                  {guid,{1563826056464360,268568599996414,2}},
                  {'$logger_metadata$',
                      #{client_id => <<"client">>,
                        peername => "127.0.0.1:49204"}}]
    trap_exit: true
    status: running
    heap_size: 28690
    stack_size: 27
    reductions: 505812
  neighbours:

2019-07-22 20:07:36.484 [error] supervisor: 'esockd_connection_sup - <0.4243.0>'
    errorContext: connection_crashed
    reason: {noproc,
                {gen_server,call,
                    [<0.5558.0>,
                     {param_query,
                         "select allow, ipaddr, username, clientid, access, topic from MqttAcl where ipaddr = ? or username = ? or username = '$all' or clientid = ?",
                         ["127.0.0.1",<<"user_name">>,<<"client">>],
                         no_filtermap_fun,default_timeout},
                     infinity]}}
    offender: [{pid,<0.10238.0>},
               {name,connection},
               {mfargs,{emqx_channel,start_link,
                                     [[{deflate_options,[]},
                                       {max_conn_rate,500},
                                       {active_n,100},
                                       {zone,external}]]}}]




```

**Comment by chan1600** [comment]
The issue exists with TLS port 8883

**Comment by fuji4** [comment]
Seems that I have the same problem with the Plugin emqx_auth_pgsql.
OS: Ubuntu 18.04
EMQX 3.2.2

**Comment by chan1600** [comment]
More log update. Could it be related to heap size issue?
Not sure if it is related. However, my MySQL database setting is set to kill idle connect every 1 min

2019-08-31 11:49:55.371 [error] devicename@24.123.123.123:57982 crasher:
    initial call: emqx_channel:init/1
    pid: <0.14894.22>
    registered_name: []
    exception exit: {noproc,
                        {gen_server,call,
                            [<0.32371.21>,
                             {param_query,
                                 "select is_superuser from MqttUser where username = ? limit 1",
                                 [<<"devicename">>],
                                 no_filtermap_fun,default_timeout},
                             infinity]}}
      in function  gen_server:call/3 (gen_server.erl, line 223)
      in call from mysql:query_call/2 (/tmp/emqx/v3.2.1/_checkouts/mysql/src/mysql.erl, line 751)
      in call from emqx_auth_mysql:is_superuser/2 (/tmp/emqx/v3.2.1/_checkouts/emqx_auth_mysql/src/emqx_auth_mysql.erl, line 65)
      in call from emqx_auth_mysql:check/2 (/tmp/emqx/v3.2.1/_checkouts/emqx_auth_mysql/src/emqx_auth_mysql.erl, line 47)
      in call from emqx_hooks:do_run_fold/3 (/tmp/emqx/v3.2.1/_checkouts/emqx/src/emqx_hooks.erl, line 131)
      in call from emqx_access_control:authenticate/1 (/tmp/emqx/v3.2.1/_checkouts/emqx/src/emqx_access_control.erl, line 31)
      in call from emqx_protocol:process/2 (/tmp/emqx/v3.2.1/_checkouts/emqx/src/emqx_protocol.erl, line 401)
      in call from emqx_channel:handle_incoming/3 (/tmp/emqx/v3.2.1/_checkouts/emqx/src/emqx_channel.erl, line 433)
    ancestors: [<0.22746.21>,<0.22745.21>,esockd_sup,<0.22539.21>]
    message_queue_len: 1
    messages: [{cancel_timer,#Ref<0.604909242.2089811969.212046>,14983}]
    links: [<0.22746.21>]
    dictionary: [{'$logger_metadata$',
                      #{client_id => <<"devicename">>,
                        peername => "24.123.123.123:57982"}},
                  {{publish,<<"client/devicename/connect">>},
                   {allow,1567252195358}},
                  {acl_cache_size,1},
                  {acl_keys_q,
                      {[{publish,<<"client/devicename/connect">>}],[]}},
                  {rand_seed,
                      {#{bits => 58,jump => #Fun<rand.8.10897371>,
                         next => #Fun<rand.5.10897371>,type => exrop,
                         uniform => #Fun<rand.6.10897371>,
                         uniform_n => #Fun<rand.7.10897371>,
                         weak_low_bits => 1},
                       [116160788309018662|252679084593609741]}},
                  {force_shutdown_policy,
                      #{max_heap_size => 838860800,message_queue_len => 8000}},
                  {incoming_bytes,124}]
    trap_exit: true
    status: running
    heap_size: 17731
    stack_size: 27
    reductions: 355014
  neighbours:
2019-08-31 11:49:55.372 [error] supervisor: 'esockd_connection_sup - <0.22746.21>'
    errorContext: connection_crashed
    reason: {noproc,
                {gen_server,call,
                    [<0.32371.21>,
                     {param_query,
                         "select is_superuser from MqttUser where username = ? limit 1",
                         [<<"devicename">>],
                         no_filtermap_fun,default_timeout},
                     infinity]}}
    offender: [{pid,<0.14894.22>},
               {name,connection},
               {mfargs,{emqx_channel,start_link,
                                     [[{deflate_options,[]},
                                       {max_conn_rate,500},
                                       {active_n,100},
                                       {zone,external}]]}}]
2019-08-31 11:49:55.526 [error] devicename@24.123.123.123:57984 ** State machine <0.14900.22> terminating
** Last event = {cast,
                    {incoming,
                        {mqtt_packet,
                            {mqtt_packet_header,1,false,0,false},
                            {mqtt_packet_connect,<<"MQIsdp">>,3,false,true,
                                true,2,true,60,undefined,
                                <<"devicename">>,undefined,
                           <<"client/devicename/connect">>,
                                <<"Offline">>,<<"devicename">>,
                                <<"oudvlyEUrIFbwAVl24M32By3nejnD4zg">>},
                            undefined}}}
** When server state  = {idle,
                         {state,esockd_transport,
                          {ssl_socket,#Port<0.16267>,
                           {sslsocket,
                            {gen_tcp,#Port<0.16267>,tls_connection,undefined},
                            [<0.14902.22>,<0.14901.22>]}},
                          {{24,87,216,241},57984},
                          undefined,running,100,
                          {pstate,external,#Fun<emqx_channel.0.83793538>,
                           {{172,31,19,67},8883},
                           {{24,87,216,241},57984},
                           undefined,4,<<"MQTT">>,<<>>,false,<0.14900.22>,
                           undefined,undefined,undefined,undefined,false,#{},
                           undefined,undefined,undefined,false,
                           #{msg => 0,pkt => 0},
                           #{msg => 0,pkt => 0},
                           false,undefined,
                           #{from_client => 0,to_client => 0},
                           emqx_channel,#{},undefined},
                          {none,#{max_size => 268435456,version => 3}},
                          {emqx_gc,
                           #{cnt => {1000,999},oct => {1048576,1048450}}},
                          undefined,undefined,undefined,undefined,true,
                          #Ref<0.604909242.2089811969.212092>,15000}}
** Reason for termination = exit:{noproc,
                                  {gen_server,call,
                                   [<0.2406.22>,
                                    {param_query,
                                     "select password from MqttUser where username = ? limit 1",
                                     [<<"B696D78109BA54E5">>],
                                     no_filtermap_fun,default_timeout},
                                    infinity]}}
** Callback mode = [state_functions,state_enter]
** Stacktrace =
**  [{gen_server,call,3,[{file,"gen_server.erl"},{line,223}]},
     {mysql,query_call,2,
            [{file,"/tmp/emqx/v3.2.1/_checkouts/mysql/src/mysql.erl"},
             {line,751}]},
     {emqx_auth_mysql,check,2,
                      [{file,"/tmp/emqx/v3.2.1/_checkouts/emqx_auth_mysql/src/emqx_auth_mysql.erl"},
                       {line,33}]},
     {emqx_hooks,do_run_fold,3,
                 [{file,"/tmp/emqx/v3.2.1/_checkouts/emqx/src/emqx_hooks.erl"},
                  {line,131}]},
     {emqx_access_control,authenticate,1,
                          [{file,"/tmp/emqx/v3.2.1/_checkouts/emqx/src/emqx_access_control.erl"},
                           {line,31}]},
     {emqx_protocol,process,2,
                    [{file,"/tmp/emqx/v3.2.1/_checkouts/emqx/src/emqx_protocol.erl"},
                     {line,401}]},
     {emqx_channel,handle_incoming,3,
                   [{file,"/tmp/emqx/v3.2.1/_checkouts/emqx/src/emqx_channel.erl"},
                    {line,433}]},
     {gen_statem,call_state_function,5,[{file,"gen_statem.erl"},{line,1660}]}]

**Comment by HJianBo** [comment]
It seems that the MySQL connection process is down. 

And I have checked the MySQL driver, the default keep-alive interval is 60s.  So you must keep the `interactive_timeout` and `wait_timeout` params of MySQL bigger than 60s

**Comment by chan1600** [comment]
> It seems that the MySQL connection process is down.
> 
> And I have checked the MySQL driver, the default keep-alive interval is 60s. So you must keep the `interactive_timeout` and `wait_timeout` params of MySQL bigger than 60s

Ok. I would switch my interactive_timeout and wait_timeout from 60 to 120s. I will test it again. Thank you.

**Comment by chan1600** [comment]
Have been running the broker for 3 days. Not seeing the issue now. Would reopen issue again if any problem.
