### ISSUE TITLE
publish and subscribe slowly

### ISSUE THREAD

**Issue by QQHARRY** [emqx/emqx#2714]
#### Environment

- OS: CentOS Linux release 7.6.1810 (Core)
- Erlang/OTP: 
- EMQ: EMQ X v3.2.0 

#### Description
1. The connection can established very fast, but the publish and subscribe is too slow to finish (about 5~6s)
2. Some times it needs 5 or 6 seconds for the subscriber to receive the message, but some times it is fast.
3. It works good at the beginning, and the system has been running for about 1 week, to peek count of clients is not more than 10. I have tried to solve this problem by restarting the emqx, but failed.

**Comment by jinfahua** [comment]
Can you reproduce the problem within intranet access? For example, pub and sub at the same sever where EMQ X is installed.

**Comment by QQHARRY** [comment]
> Can you reproduce the problem within intranet access? For example, pub and sub at the same sever where EMQ X is installed.

No, the EMQ X has installed on a cloud server.Actually, client can do pub and sub quickly at the several beginning  days. Now not only pub/sub action takes long time but also transmit a message after pub/sub successfully.BTW one of the client is installed on the same server with EMQ X,and this client also hard to pub/sub.

**Comment by terry-xiaoyu** [comment]
@QQHARRY You could get the logs of one of your client/topic by tracing it, see https://developer.emqx.io/docs/broker/v3/en/commands.html#trace.

I suggest you check the statistics of the ACL database you're using.
