### ISSUE TITLE
emqx_auth_mysql cannot connect to mysql 8.0

### ISSUE THREAD

**Issue by fanxueqiang** [emqx/emqx#2719]
#### Environment

- OS: centos7
- Erlang/OTP: 22.0
- EMQ: 3.2.1

#### Description

安装完毕后启动服务，在Dashboard中配置emqx_auth_mysql插件后，点击启动返回：
Request failed with status code 500。
然后查看日志有如下输出：
2019-07-25 08:58:04.883 [error] [Plugins] Load plugin emqx_auth_mysql failed, cannot start plugin emqx_auth_mysql for {bad_return,
                                                                                       {{emqx_auth_mysql_app,
                                                                                         start,
                                                                                         [normal,
                                                                                          []]},
                                                                                        {'EXIT',
                                                                                         {{badmatch,
                                                                                           {error,
                                                                                            {shutdown,
                                                                                             {failed_to_start_child,
                                                                                              emqx_auth_mysql,
                                                                                              {shutdown,
                                                                                               {failed_to_start_child,
                                                                                                worker_sup,
                                                                                                {shutdown,
                                                                                                 {failed_to_start_child,
                                                                                                  {worker,
                                                                                                   1},
                                                                                                  {{auth_method,
                                                                                                    <<"caching_sha2_password">>},
                                                                                                   [{mysql_protocol,
                                                                                                     build_handshake_response,
                                                                                                     5,
                                                                                                     [{file,
                                                                                                       "/emqx_temp/emqx_rel/_checkouts/mysql/src/mysql_protocol.erl"},
                                                                                                      {line,
                                                                                                       386}]},
                                                                                                    {mysql_protocol,
                                                                                                     handshake,
                                                                                                     7,
                                                                                                     [{file,
                                                                                                       "/emqx_temp/emqx_rel/_checkouts/mysql/src/mysql_protocol.erl"},
                                                                                                      {line,
                                                                                                       72}]},
                                                                                                    {mysql_conn,
                                                                                                     init,
                                                                                                     1,
                                                                                                     [{file,
                                                                                                       "/emqx_temp/emqx_rel/_checkouts/mysql/src/mysql_conn.erl"},
                                                                                                      {line,
                                                                                                       108}]},
                                                                                                    {gen_server,
                                                                                                     init_it,
                                                                                                     2,
                                                                                                     [{file,
                                                                                                       "gen_server.erl"},
                                                                                                      {line,
                                                                                                       374}]},
                                                                                                    {gen_server,
                                                                                                     init_it,
                                                                                                     6,
                                                                                                     [{file,
                                                                                                       "gen_server.erl"},
                                                                                                      {line,
                                                                                                       342}]},
                                                                                                    {proc_lib,
                                                                                                     init_p_do_apply,
                                                                                                     3,
                                                                                                     [{file,
                                                                                                       "proc_lib.erl"},
                                                                                                      {line,
                                                                                                       249}]}]}}}}}}}}},
                                                                                          [{emqx_auth_mysql_app,
                                                                                            start,
                                                                                            2,
                                                                                            [{file,
                                                                                              "/emqx_temp/emqx_rel/_checkouts/emqx_auth_mysql/src/emqx_auth_mysql_app.erl"},
                                                                                             {line,
                                                                                              36}]},
                                                                                           {application_master,
                                                                                            start_it_old,
                                                                                            4,
                                                                                            [{file,
                                                                                              "application_master.erl"},
                                                                                             {line,
                                                                                              277}]}]}}}}
2019-07-25 08:58:04.998 [error] PUT /api/v3/nodes/emqx@127.0.0.1/plugins/emqx_auth_mysql/load error: badarg, stacktrace:
[{jsx_parser,value,4,
             [{file,"/emqx_temp/emqx_rel/_checkouts/jsx/src/jsx_parser.erl"},
              {line,163}]},
 {minirest_handler,jsonify,4,
                   [{file,"/emqx_temp/emqx_rel/_checkouts/minirest/src/minirest_handler.erl"},
                    {line,152}]},
 {minirest,handle_request,2,
           [{file,"/emqx_temp/emqx_rel/_checkouts/minirest/src/minirest.erl"},
            {line,94}]},
 {minirest,init,2,
           [{file,"/emqx_temp/emqx_rel/_checkouts/minirest/src/minirest.erl"},
            {line,86}]},
 {cowboy_handler,execute,2,
                 [{file,"/emqx_temp/emqx_rel/_checkouts/cowboy/src/cowboy_handler.erl"},
                  {line,41}]},
 {cowboy_stream_h,execute,3,
                  [{file,"/emqx_temp/emqx_rel/_checkouts/cowboy/src/cowboy_stream_h.erl"},
                   {line,296}]},
 {cowboy_stream_h,request_process,3,
                  [{file,"/emqx_temp/emqx_rel/_checkouts/cowboy/src/cowboy_stream_h.erl"},
                   {line,274}]},
 {proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,249}]}]

然后尝试配置etc/plugins/emqx_auth_mysql.conf之后再次命令行启动服务依然返回上面的错误

**Comment by zhanghongtong** [comment]
Mysql8.0 USES the `caching_sha2_password ` plugins by default for account password configuration. You need to change the password plugins to `mysql_native_password `

**Comment by fanxueqiang** [comment]
怎么配置呢？

**Comment by fanxueqiang** [comment]
> Mysql8.0 uses the `caching_sha2_password ` plugins by default for account password configuration. You need to change the password plugins to `mysql_native_password `

怎么配置呢？

**Comment by zhanghongtong** [comment]
```
## Switch to mysql database
mysql> use mysql
Reading table information for completion of table and column names
You can turn off this feature to get a quicker startup with -A

Database changed

## View the user table
mysql> select user, host, plugin from user;
+------------------+-----------+-----------------------+
| user             | host      | plugin                |
+------------------+-----------+-----------------------+
| root             | %         | caching_sha2_password |
| mysql.infoschema | localhost | caching_sha2_password |
| mysql.session    | localhost | caching_sha2_password |
| mysql.sys        | localhost | caching_sha2_password |
| root             | localhost | caching_sha2_password |
+------------------+-----------+-----------------------+

## Change password plugin
mysql> ALTER USER 'your_username'@'your_host' IDENTIFIED WITH mysql_native_password BY 'your_password';
Query OK, 0 rows affected (0.01 sec)

## Refresh
mysql> FLUSH PRIVILEGES;
Query OK, 0 rows affected (0.00 sec)
```

**Comment by fanxueqiang** [comment]
> ```
> ## Switch to mysql database
> mysql> use mysql
> Reading table information for completion of table and column names
> You can turn off this feature to get a quicker startup with -A
> 
> Database changed
> 
> ## View the user table
> mysql> select user, host, plugin from user;
> +------------------+-----------+-----------------------+
> | user             | host      | plugin                |
> +------------------+-----------+-----------------------+
> | root             | %         | caching_sha2_password |
> | mysql.infoschema | localhost | caching_sha2_password |
> | mysql.session    | localhost | caching_sha2_password |
> | mysql.sys        | localhost | caching_sha2_password |
> | root             | localhost | caching_sha2_password |
> +------------------+-----------+-----------------------+
> 
> ## Change password plugin
> mysql> ALTER USER 'your_username'@'your_host' IDENTIFIED WITH mysql_native_password BY 'your_password';
> Query OK, 0 rows affected (0.01 sec)
> 
> ## Refresh
> mysql> FLUSH PRIVILEGES;
> Query OK, 0 rows affected (0.00 sec)
> ```

mysql8.0的配置改了之后还是无法启动，依然报这个错

**Comment by zhanghongtong** [comment]
@fanxueqiang Please provide more information

**Comment by ykeer** [comment]
遇到了同样的问题。
PS：mysql password plugins is already mysql_native_password

**Comment by pollux611** [comment]
同样，修改mysql_native_password后依然连接不上

**Comment by zhanghongtong** [comment]
@pollux611 Add a line below `[mysqld]` in the `my.cnf` configuration file
```
default_authentication_plugin=mysql_native_password
```
Restart MySQL server and retry

**Comment by pollux611** [comment]
> @pollux611 Add a line below `[mysqld]` in the `my.cnf` configuration file
> 
> ```
> default_authentication_plugin=mysql_native_password
> ```
> 
> Restart MySQL server and retry

修改默认加密方式重启后好用了，多谢

**Comment by zhanghongtong** [comment]
@pollux611 You're welcome :)
