### ISSUE TITLE
How to change the default port, such as 18083 and 1883

### ISSUE THREAD

**Issue by ai-Lemon** [emqx/emqx#2720]
#### Environment

- OS: 
- Erlang/OTP: 
- EMQ: 

#### Description

*A description of the issue*

**Comment by jinfahua** [comment]
Please refer to the doc - https://developer.emqx.io/docs/broker/v3/en/config.html#mqtt-listeners-parameter-description

**Comment by ai-Lemon** [comment]
@jinfahua  thank you very much，but I also modified the parameters according to the above method, and then restarted EMQ to report the error: "[error] Syntax error in c:/emqx/data/configs/app.2019.07.26.10.24.06.conf after line 1 column 1, parsing incomplete",I don’t know how to solve this.

**Comment by jinfahua** [comment]
What's the content of file ``c:/emqx/data/configs/app.2019.07.26.10.24.06.conf`` ?

**Comment by terry-xiaoyu** [comment]
All issues should have basic info like OTP version and emqx version.

**Comment by ai-Lemon** [comment]
I know the reason for the problem. I modified the .conf file in Windows. Whether the .conf file has changed or not, I would report an error if I saved it again. Now I don't know how to Jie this problem.

**Comment by ai-Lemon** [comment]
Now I can successfully implement the function through notepda++ modification.
