### ISSUE TITLE
Node 'emqx@127.0.0.1' not responding to pings

### ISSUE THREAD

**Issue by chenyf** [emqx/emqx#2721]
#### Environment

- OS:  ubuntu 16.04
- Erlang/OTP:  R21/10.3
- EMQ:  3.2.0

#### Description
1、 下载 deb 包，安装完成，启动成功。dashboard 可以查看； 
2、 执行 sudo emqx_ctl status
报错：
Node 'emqx@127.0.0.1' not responding to pings.

无法停止 emqx， 也无法重启

**Comment by tigercl** [comment]
Maybe you can provide logs in .../emqx/log so that we can help you better

**Comment by chenyf** [comment]
卸载了重装以后，可以了

**Comment by kumaralg2** [comment]
> 卸载了重装以后，可以了

How to uninstall the emqx?
