### ISSUE TITLE
subscribe question

### ISSUE THREAD

**Issue by feiyanke** [emqx/emqx#2722]
I have clients who subscribe the topic with wildcard like message/+ and there are thousands of clients publish their messages like message/device1, message/device2, message/device3 etc.
However, we don't want all the subscribe clients to get messages form all devices. How can we make one client just get message/device1, message/device2, etc., and another client get message/device3, message/device4 etc..
Thank you very much for your help.

**Comment by jerry-chao** [comment]
maybe you can try share subscription $share/message/+
