### ISSUE TITLE
Number of connections listed on dashboard is not equal to the number of TCP connections got by netstat

### ISSUE THREAD

**Issue by qiuqiu00** [emqx/emqx#2725]
#### Environment

- OS: Linux
- Erlang/OTP: R21/10.3
- EMQ: v3.1.2

#### Description

dashboard实际连接数只有50几个，服务器真正的连接数会慢慢增加（客户端使用4G模块，断连重启ip可能会更改）
以下是运行一段时间后服务器的tcp连接
tcp        0      0 172.18.124.151:1883     117.132.193.142:64558   ESTABLISHED
tcp        0      0 172.18.124.151:1883     218.204.252.207:40122   ESTABLISHED
tcp        0      0 172.18.124.151:1883     117.132.194.215:13242   ESTABLISHED
tcp        0      0 172.18.124.151:1883     221.178.127.123:15660   ESTABLISHED
tcp        0      0 172.18.124.151:1883     223.104.255.20:41759    ESTABLISHED
tcp        0      0 172.18.124.151:1883     218.204.252.161:43542   ESTABLISHED
tcp        0      0 172.18.124.151:1883     120.78.177.106:49177    ESTABLISHED
tcp        0      0 172.18.124.151:1883     117.132.195.241:50994   ESTABLISHED
tcp        0      0 172.18.124.151:1883     117.132.196.141:65288   ESTABLISHED
tcp        0      0 172.18.124.151:1883     117.132.194.95:53370    ESTABLISHED
tcp        0      0 172.18.124.151:1883     117.132.194.101:36582   ESTABLISHED
tcp        0      0 172.18.124.151:1883     117.132.195.106:10653   ESTABLISHED
tcp        0      0 172.18.124.151:1883     223.104.255.111:36888   ESTABLISHED
tcp        0      0 172.18.124.151:1883     120.78.177.106:60172    ESTABLISHED
tcp        0      0 172.18.124.151:1883     117.132.193.77:44271    ESTABLISHED
tcp        0      0 172.18.124.151:1883     120.78.177.106:64045    ESTABLISHED
tcp        0      0 172.18.124.151:1883     221.178.124.4:47505     ESTABLISHED
tcp        0      0 172.18.124.151:1883     117.132.194.123:22077   ESTABLISHED
tcp        0      0 172.18.124.151:1883     223.104.254.112:30850   ESTABLISHED
tcp        0      0 172.18.124.151:1883     117.132.195.153:49415   ESTABLISHED
tcp        0      0 172.18.124.151:1883     221.178.126.173:31700   ESTABLISHED
tcp        0      0 172.18.124.151:1883     117.132.194.1:31974     ESTABLISHED
tcp        0      0 172.18.124.151:1883     117.132.198.26:36472    ESTABLISHED
tcp        0      0 172.18.124.151:1883     223.104.254.155:41672   ESTABLISHED
tcp        0      0 172.18.124.151:1883     112.96.240.19:21173     ESTABLISHED
tcp        0      0 172.18.124.151:1883     117.132.195.154:29783   ESTABLISHED
tcp        0      0 172.18.124.151:1883     223.104.254.78:10497    ESTABLISHED
tcp        0      0 172.18.124.151:1883     223.104.254.113:53832   ESTABLISHED
tcp        0      0 172.18.124.151:1883     223.104.254.79:28330    ESTABLISHED
tcp        0      0 172.18.124.151:1883     221.178.124.145:2418    ESTABLISHED
tcp        0      0 172.18.124.151:1883     223.104.254.106:52956   ESTABLISHED
tcp        0      0 172.18.124.151:1883     120.78.177.106:49212    ESTABLISHED
tcp        0      0 172.18.124.151:1883     117.132.196.244:16184   ESTABLISHED
tcp        0      0 172.18.124.151:1883     117.132.194.247:43979   ESTABLISHED
tcp        0      0 172.18.124.151:1883     117.132.192.19:49913    ESTABLISHED
tcp        0      0 172.18.124.151:1883     117.132.192.228:15135   ESTABLISHED
tcp        0      0 172.18.124.151:1883     117.132.194.79:28755    ESTABLISHED
tcp        0      0 172.18.124.151:1883     117.132.194.75:53530    ESTABLISHED
tcp        0      0 172.18.124.151:1883     218.204.252.72:11110    ESTABLISHED
tcp        0      0 172.18.124.151:1883     120.78.177.106:59618    ESTABLISHED
tcp        0      0 172.18.124.151:1883     221.178.125.131:11442   ESTABLISHED
tcp        0      0 172.18.124.151:1883     221.178.127.224:11765   ESTABLISHED
tcp        0      0 172.18.124.151:1883     120.78.177.106:64041    ESTABLISHED
tcp        0      0 172.18.124.151:1883     117.132.195.236:15045   ESTABLISHED
tcp        0      0 172.18.124.151:1883     117.132.194.105:62483   ESTABLISHED
tcp        0      0 172.18.124.151:1883     223.104.255.132:3850    ESTABLISHED
tcp        0      0 172.18.124.151:1883     117.132.194.205:64595   ESTABLISHED
tcp        0      0 172.18.124.151:1883     221.178.124.64:17002    ESTABLISHED
tcp        0      0 172.18.124.151:1883     117.132.192.21:9328     ESTABLISHED
tcp        0      0 172.18.124.151:1883     223.104.255.33:21060    ESTABLISHED
tcp        0      0 172.18.124.151:1883     117.132.194.78:39817    ESTABLISHED
tcp        0      0 172.18.124.151:1883     117.132.196.39:40694    ESTABLISHED
tcp        0      0 172.18.124.151:1883     117.132.198.42:57065    ESTABLISHED
tcp        0      0 172.18.124.151:1883     117.132.195.241:50486   ESTABLISHED
tcp        0      0 172.18.124.151:1883     117.132.194.33:18412    ESTABLISHED
tcp        0      0 172.18.124.151:1883     117.132.194.237:49079   ESTABLISHED
tcp        0      0 172.18.124.151:1883     117.132.195.176:36906   ESTABLISHED
tcp        0      0 172.18.124.151:1883     221.178.127.174:26074   ESTABLISHED
tcp        0      0 172.18.124.151:1883     218.204.252.38:12823    ESTABLISHED
tcp        0      0 172.18.124.151:1883     120.78.177.106:59607    ESTABLISHED
tcp        0      0 172.18.124.151:1883     218.204.252.162:8222    ESTABLISHED
tcp        0      0 172.18.124.151:1883     117.132.194.252:10126   ESTABLISHED
tcp        0      0 172.18.124.151:1883     120.78.177.106:49188    ESTABLISHED
tcp        0      0 172.18.124.151:1883     223.104.255.4:60228     ESTABLISHED
tcp        0      0 172.18.124.151:1883     223.104.255.74:56447    ESTABLISHED
tcp        0      0 172.18.124.151:1883     120.78.177.106:49180    ESTABLISHED
tcp        0      0 172.18.124.151:1883     117.132.197.136:17644   ESTABLISHED
tcp        0      0 172.18.124.151:1883     223.104.255.128:52052   ESTABLISHED
tcp        0      0 172.18.124.151:1883     117.132.193.24:23820    ESTABLISHED
tcp        0      0 172.18.124.151:1883     221.178.124.199:47200   ESTABLISHED
tcp        0      0 172.18.124.151:1883     218.204.252.115:7685    ESTABLISHED
tcp        0      0 172.18.124.151:1883     221.178.124.21:53680    ESTABLISHED
tcp        0      0 172.18.124.151:1883     221.178.124.247:41935   ESTABLISHED
tcp        0      0 172.18.124.151:1883     117.132.193.246:6190    ESTABLISHED
tcp        0      0 172.18.124.151:1883     117.132.193.67:41159    ESTABLISHED
tcp        0      0 172.18.124.151:1883     117.132.193.146:16527   ESTABLISHED
tcp        0      0 172.18.124.151:1883     218.204.252.166:52143   ESTABLISHED
tcp        0      0 172.18.124.151:1883     223.104.255.96:24756    ESTABLISHED
tcp        0      0 172.18.124.151:1883     221.178.124.27:10536    ESTABLISHED
tcp        0      0 172.18.124.151:1883     117.132.193.92:55691    ESTABLISHED
tcp        0      0 172.18.124.151:1883     223.104.254.123:28100   ESTABLISHED
tcp        0      0 172.18.124.151:1883     223.104.254.113:33937   ESTABLISHED
tcp        0      0 172.18.124.151:1883     120.78.177.106:61517    ESTABLISHED
tcp        0      0 172.18.124.151:1883     117.132.197.99:39150    ESTABLISHED
tcp        0      0 172.18.124.151:1883     117.132.194.79:40250    ESTABLISHED
tcp        0      0 172.18.124.151:1883     221.178.124.6:25323     ESTABLISHED
tcp        0      0 172.18.124.151:1883     117.132.192.135:29189   ESTABLISHED
tcp        0      0 172.18.124.151:1883     223.104.255.185:44612   ESTABLISHED
tcp        0      0 172.18.124.151:1883     117.132.193.10:63698    ESTABLISHED
tcp        0      0 172.18.124.151:1883     223.104.255.91:27303    ESTABLISHED
tcp        0      0 172.18.124.151:1883     223.104.255.139:32896   ESTABLISHED
tcp        0      0 172.18.124.151:1883     221.178.126.37:3636     ESTABLISHED
tcp        0      0 172.18.124.151:1883     223.104.254.118:19151   ESTABLISHED
tcp        0      0 172.18.124.151:1883     218.204.253.116:12228   ESTABLISHED
tcp        0      0 172.18.124.151:1883     117.132.194.0:8579      ESTABLISHED
tcp        0      0 172.18.124.151:1883     223.104.255.199:56802   ESTABLISHED
tcp        0      0 172.18.124.151:1883     223.104.254.56:6240     ESTABLISHED
tcp        0      0 172.18.124.151:1883     117.132.198.110:55940   ESTABLISHED
tcp        0      0 172.18.124.151:1883     223.104.255.6:3450      ESTABLISHED
tcp        0      0 172.18.124.151:1883     223.104.255.107:16640   ESTABLISHED
tcp        0      0 172.18.124.151:1883     221.178.127.139:26979   ESTABLISHED
tcp        0      0 172.18.124.151:1883     221.178.125.87:51065    ESTABLISHED
tcp        0      0 172.18.124.151:1883     120.78.177.106:64031    TIME_WAIT  
tcp        0      0 172.18.124.151:1883     117.132.198.228:14736   ESTABLISHED
tcp        0      0 172.18.124.151:1883     221.178.127.149:31505   ESTABLISHED
tcp        0      0 172.18.124.151:1883     117.132.191.122:34674   ESTABLISHED
tcp        0      0 172.18.124.151:1883     221.178.127.80:61039    ESTABLISHED
tcp        0      0 172.18.124.151:1883     221.178.126.188:64452   ESTABLISHED
tcp        0      0 172.18.124.151:1883     117.132.196.32:44429    ESTABLISHED
tcp        0      0 172.18.124.151:1883     221.178.127.163:53112   ESTABLISHED
tcp        0      0 172.18.124.151:1883     117.132.194.18:30912    ESTABLISHED
tcp        0      0 172.18.124.151:1883     117.132.191.196:61373   ESTABLISHED
tcp        0      0 172.18.124.151:1883     223.104.255.185:13700   ESTABLISHED
tcp        0      0 172.18.124.151:1883     223.104.254.140:12224   ESTABLISHED
tcp        0      0 172.18.124.151:1883     223.104.255.219:54660   ESTABLISHED
tcp        0      0 172.18.124.151:1883     117.132.196.32:32971    ESTABLISHED 
tcp        0      0 172.18.124.151:1883     223.104.254.28:61134    ESTABLISHED
tcp        0      0 172.18.124.151:1883     112.96.248.157:25743    ESTABLISHED
tcp        0      0 172.18.124.151:1883     221.178.125.12:52371    ESTABLISHED
tcp        0      0 172.18.124.151:1883     117.132.195.77:44799    ESTABLISHED
tcp        0      0 172.18.124.151:1883     117.132.195.166:7931    ESTABLISHED
tcp        0      0 172.18.124.151:1883     223.104.255.211:21149   ESTABLISHED
tcp        0      0 172.18.124.151:1883     223.104.254.101:28445   ESTABLISHED
tcp        0      0 172.18.124.151:1883     221.178.124.210:64965   ESTABLISHED
tcp        0      0 172.18.124.151:1883     117.132.196.7:18614     ESTABLISHED
tcp        0      0 172.18.124.151:1883     117.132.195.11:5503     ESTABLISHED
tcp        0      0 172.18.124.151:1883     221.178.124.105:50330   ESTABLISHED
tcp        0      0 172.18.124.151:1883     117.132.195.122:26169   ESTABLISHED
tcp        0      0 172.18.124.151:1883     223.104.255.101:3407    ESTABLISHED
tcp        0      0 172.18.124.151:1883     223.104.254.173:54966   ESTABLISHED
tcp        0      0 172.18.124.151:1883     218.204.253.124:64663   ESTABLISHED
tcp        0      0 172.18.124.151:1883     223.104.254.152:29390   ESTABLISHED
tcp        0      0 172.18.124.151:1883     223.104.254.74:32180    ESTABLISHED
tcp        0      0 172.18.124.151:1883     120.78.177.106:64028    TIME_WAIT  
tcp        0      0 172.18.124.151:1883     221.178.124.150:54933   ESTABLISHED
tcp        0      0 172.18.124.151:1883     117.132.192.253:17765   ESTABLISHED
tcp        0      0 172.18.124.151:1883     112.96.248.66:31046     ESTABLISHED
tcp        0      0 172.18.124.151:1883     117.132.194.87:63976    ESTABLISHED
tcp        0      0 172.18.124.151:1883     117.132.193.65:38820    ESTABLISHED
tcp        0      0 172.18.124.151:1883     117.132.193.197:20400   ESTABLISHED
tcp        0      0 172.18.124.151:1883     223.104.255.233:4833    ESTABLISHED
tcp        0      0 172.18.124.151:1883     218.204.252.186:56986   ESTABLISHED
tcp        0      0 172.18.124.151:1883     223.104.255.56:26759    ESTABLISHED
tcp        0      0 172.18.124.151:1883     221.178.126.9:41227     ESTABLISHED
tcp        0      0 172.18.124.151:1883     117.132.195.53:59930    ESTABLISHED
tcp        0      0 172.18.124.151:1883     117.132.195.192:17478   ESTABLISHED 
tcp        0      0 172.18.124.151:1883     221.178.124.174:38159   ESTABLISHED
tcp        0      0 172.18.124.151:1883     117.132.191.216:45551   ESTABLISHED
tcp        0      0 172.18.124.151:1883     221.178.126.144:56800   ESTABLISHED
tcp        0      0 172.18.124.151:1883     117.132.192.97:16903    ESTABLISHED
tcp        0      0 172.18.124.151:1883     117.132.195.240:44576   ESTABLISHED
tcp        0      0 172.18.124.151:1883     218.204.253.206:36324   ESTABLISHED
tcp        0      0 172.18.124.151:1883     117.132.193.232:15885   ESTABLISHED
tcp        0      0 172.18.124.151:1883     117.132.195.215:50817   ESTABLISHED
tcp        0      0 172.18.124.151:1883     117.132.195.93:37646    ESTABLISHED
tcp        0      0 172.18.124.151:1883     117.132.191.147:44781   ESTABLISHED 
tcp        0      0 172.18.124.151:1883     120.78.177.106:64040    ESTABLISHED
tcp        0      0 172.18.124.151:1883     117.132.193.207:41444   ESTABLISHED
tcp        0      0 172.18.124.151:1883     223.104.255.133:29462   ESTABLISHED
tcp        0      0 172.18.124.151:1883     120.78.177.106:64046    ESTABLISHED
tcp        0      0 172.18.124.151:1883     117.132.193.112:2954    ESTABLISHED
tcp        0      0 172.18.124.151:1883     221.178.124.63:33433    ESTABLISHED
tcp        0      0 172.18.124.151:1883     223.104.255.160:63229   ESTABLISHED
tcp        0      0 172.18.124.151:1883     120.78.177.106:49171    ESTABLISHED
tcp        0      0 172.18.124.151:1883     218.204.252.196:53172   ESTABLISHED
tcp        0      0 172.18.124.151:1883     120.78.177.106:64010    TIME_WAIT  
tcp        0      0 172.18.124.151:1883     223.104.255.152:37506   ESTABLISHED
tcp        0      0 172.18.124.151:1883     221.178.124.4:47475     ESTABLISHED
tcp        0      0 172.18.124.151:1883     120.78.177.106:49213    ESTABLISHED
tcp        0      0 172.18.124.151:1883     223.104.255.53:63884    ESTABLISHED
tcp        0      0 172.18.124.151:1883     223.104.254.4:41252     ESTABLISHED
tcp        0      0 172.18.124.151:1883     223.104.254.63:38655    ESTABLISHED
tcp        0      0 172.18.124.151:1883     221.178.126.182:13156   ESTABLISHED
tcp        0      0 172.18.124.151:1883     218.204.253.155:14897   ESTABLISHED
tcp        0      0 172.18.124.151:1883     223.104.254.169:54554   ESTABLISHED
tcp        0      0 172.18.124.151:1883     223.104.254.181:58185   ESTABLISHED
tcp        0      0 172.18.124.151:1883     117.132.194.21:13820    ESTABLISHED
tcp        0      0 172.18.124.151:1883     223.104.255.122:56828   ESTABLISHED
tcp        0      0 172.18.124.151:1883     221.178.127.89:16204    ESTABLISHED
tcp        0      0 172.18.124.151:1883     218.204.253.228:9254    ESTABLISHED
tcp        0      0 172.18.124.151:1883     117.132.198.96:36475    ESTABLISHED
tcp        0      0 172.18.124.151:1883     117.132.197.188:14004   ESTABLISHED
tcp        0      0 172.18.124.151:1883     221.178.124.8:28232     ESTABLISHED
tcp        0      0 172.18.124.151:1883     221.178.127.173:29288   ESTABLISHED
tcp        0      0 172.18.124.151:1883     221.178.124.99:2619     ESTABLISHED
tcp        0      0 172.18.124.151:1883     221.178.127.206:49762   ESTABLISHED
tcp        0      0 172.18.124.151:1883     223.104.254.68:60662    ESTABLISHED
tcp        0      0 172.18.124.151:1883     221.178.126.71:52132    ESTABLISHED
tcp        0      0 172.18.124.151:1883     120.78.177.106:49181    ESTABLISHED
tcp        0      0 172.18.124.151:1883     223.104.255.224:50736   ESTABLISHED
tcp        0      0 172.18.124.151:1883     221.178.124.164:59040   ESTABLISHED
tcp        0      0 172.18.124.151:1883     223.104.255.179:23396   ESTABLISHED
tcp        0      0 172.18.124.151:1883     223.104.255.33:22523    ESTABLISHED
tcp        0      0 172.18.124.151:1883     117.132.193.30:39472    ESTABLISHED
tcp        0      0 172.18.124.151:1883     120.78.177.106:49170    ESTABLISHED
tcp        0      0 172.18.124.151:1883     221.178.127.182:56153   ESTABLISHED
tcp        0      0 172.18.124.151:1883     223.104.254.56:18864    ESTABLISHED
tcp        0      0 172.18.124.151:1883     218.204.252.245:3773    ESTABLISHED
tcp        0      0 172.18.124.151:1883     117.132.197.233:18457   ESTABLISHED
tcp        0      0 172.18.124.151:1883     221.178.124.172:48741   ESTABLISHED
tcp        0      0 172.18.124.151:1883     218.204.252.234:28690   ESTABLISHED
tcp        0      0 172.18.124.151:1883     223.104.255.193:5601    ESTABLISHED
tcp        0      0 172.18.124.151:1883     223.104.254.21:48108    ESTABLISHED
tcp        0      0 172.18.124.151:1883     112.96.248.153:21789    ESTABLISHED
tcp        0      0 172.18.124.151:1883     117.132.193.221:53682   ESTABLISHED 
tcp        0      0 172.18.124.151:1883     223.104.254.144:13545   ESTABLISHED
tcp        0      0 172.18.124.151:1883     221.178.125.250:19669   ESTABLISHED
tcp        0      0 172.18.124.151:1883     221.178.125.235:60629   ESTABLISHED
tcp        0      0 172.18.124.151:1883     221.178.125.191:4119    ESTABLISHED
tcp        0      0 172.18.124.151:1883     223.104.254.145:7214    ESTABLISHED
tcp        0      0 172.18.124.151:1883     218.204.253.151:50281   ESTABLISHED
tcp        0      0 172.18.124.151:1883     221.178.126.31:54085    ESTABLISHED
tcp        0      0 172.18.124.151:1883     221.178.124.250:60201   ESTABLISHED
tcp        0      0 172.18.124.151:1883     218.204.252.138:28739   ESTABLISHED
tcp        0      0 172.18.124.151:1883     117.132.194.196:65042   ESTABLISHED
tcp        0      0 172.18.124.151:1883     221.178.125.104:51571   ESTABLISHED
tcp        0      0 172.18.124.151:1883     223.104.255.46:30510    ESTABLISHED
tcp        0      0 172.18.124.151:1883     223.104.254.189:44088   ESTABLISHED
tcp        0      1 172.18.124.151:1883     223.104.255.185:55190   FIN_WAIT1  
tcp        0      0 172.18.124.151:1883     223.104.255.242:5259    ESTABLISHED
tcp        0      0 172.18.124.151:1883     223.104.254.42:63292    ESTABLISHED
tcp        0      0 172.18.124.151:1883     117.132.193.241:5536    ESTABLISHED
tcp        0      0 172.18.124.151:1883     223.104.254.157:9037    ESTABLISHED
tcp        0      0 172.18.124.151:1883     223.104.255.141:44567   ESTABLISHED
tcp        0      0 172.18.124.151:1883     221.178.127.212:47245   ESTABLISHED
tcp        0      0 172.18.124.151:1883     120.78.177.106:64035    TIME_WAIT  
tcp        0      0 172.18.124.151:1883     221.178.126.42:8400     ESTABLISHED
tcp        0      0 172.18.124.151:1883     117.132.191.30:62774    ESTABLISHED
tcp        0      0 172.18.124.151:1883     223.104.254.153:59544   ESTABLISHED

**Comment by shipengtang** [comment]
Yes, I've met the question as you too

**Comment by terry-xiaoyu** [comment]
@qiuqiu00 Hi, are you using auth plugins like `emqx_auth_mysql`? And could you post a screen shot of you dashboard page?

**Comment by qiuqiu00** [comment]
没有使用 emqx_auth_mysql

**Comment by qiuqiu00** [comment]
没有使用 emqx_auth_mysql
![火狐截图_2019-07-26T08-44-37 702Z](https://user-images.githubusercontent.com/40254226/61939513-042db300-afc6-11e9-9f70-b71f71e85a06.png)

**Comment by terry-xiaoyu** [comment]
@qiuqiu00 What kind of authentication are you using? Do you know how to reproduce this issue?

**Comment by qiuqiu00** [comment]
使用的是最基础的emqx_auth_username插件认证
先前发现的时候重启过服务器的，连接清理过
现在也有这个问题，现在dashboard 52个连接，服务器上已经67个了。

**Comment by terry-xiaoyu** [comment]
@qiuqiu00 Could you post the output of command `emqx_ctl listeners` ? And what are the errors in your log file emqx.log.N?

**Comment by qiuqiu00** [comment]
![image](https://user-images.githubusercontent.com/40254226/61943632-74403700-afce-11e9-94fb-ae5c3e44f6ec.png)
错误基本都是这样的
![image](https://user-images.githubusercontent.com/40254226/61943821-e3b62680-afce-11e9-8608-9cd86d9ba872.png)

**Comment by Gilbert-Wong** [comment]
Could you please attach your logs file here?

**Comment by terry-xiaoyu** [comment]
@qiuqiu00 

Hi, that's the fault of you MQTT client, which establishes TCP connections but no subsequent MQTT CONNECT packets are sent to emqx.

You may ask for help from your SDK developers.

**Comment by qiuqiu00** [comment]
连接变多是这个原因造成的？没有有办法拦截？客户端那边是要求服务器端解决，因为还有一个不可控的4G模块

**Comment by terry-xiaoyu** [comment]
The client will be disconnected after 15s if no CONNECT packet is received. You could change the default timeout interval (15s) as you wish, by changing the configuration: `zone.external.idle_timeout`.

We'll solve the problems and help you in case of bugs, but no other services would be provided if you are using the open source version of emqx. Check out the [Enterprise EMQ X](https://www.emqx.io/downloads#enterprise) if you like.
