### ISSUE TITLE
The issue about acl file

### ISSUE THREAD

**Issue by tungyi** [emqx/emqx#2726]
#### Environment

- OS: Windows 7 SP1
- Erlang/OTP: 10.3
- EMQ: 3.2.1

#### Description

Hello!

I have created an account/pwd with API (/api/v3/auth_username), This is working well.
But I still set its topic permissions for each account. So I need to modify the acl file (etc/acl.conf), and then restart emqx. It also works well.

My problem is the following: 

If I don't want to restart emqx.

May I create an account with its topic permissions by calling API?
Or 
May I have any method to modify the acl file with calling API?

**Comment by tigercl** [comment]
You can make the modified `etc/acl.conf` work by using `./emqx_ctl acl reload`, see [acl reload] (https://developer.emqx.io/docs/broker/v3/cn/commands.html#acl). And we are sorry that so far you can only manually modify `etc/acl.conf`.

**Comment by mononym** [comment]
You can use the Mnesia ACL feature which includes an API to update the ACL data: https://docs.emqx.io/en/broker/v4.3/advanced/acl-mnesia.html#acl-rules
