### ISSUE TITLE
COAP Protocol Usage Problem

### ISSUE THREAD

**Issue by chenguosi** [emqx/emqx#2734]
#### Environment

- OS: centos7.6
- Erlang/OTP: OPT21
- EMQ: 3.2.1

#### Description

When I configure proxy subscription with module of EMQ, COAP client and EMQ establish connection through PUT method of COAP protocol. However, when pushing the subject of proxy subscription to COAP client through EMQ, it can not reach the client correctly.

**Comment by jerry-chao** [comment]
@chenguosi  did you connect through coap protocol to EMQ and waiting for messages from EMQ .
The receiver establish connection with PUT method like this 
```
libcoap/examples/coap-client -m put -e 1234  "coap://127.0.0.1/mqtt/topic1?c=client1&u=tom&p=secret"
```
The sender is something MQTT Client or Coap Client or  HTTP Api etc.

**Comment by chenguosi** [comment]
yes

**Comment by jerry-chao** [comment]
If you want to receive some msg as MQTT subscribe , you can try the next command
```
libcoap/examples/coap-client -m get -s 10 "coap://127.0.0.1/mqtt/topic1?c=client1&u=tom&p=secret"
```
And PUT method is something like MQTT publish.

**Comment by chenguosi** [comment]
I am a UDP request initiated by SOCKET tool. The message used is the content of PUT request grabbed by LIBCODE plug-in. The module module module is also configured on EMQ, and the proxy subscription theme of the device is set. SOCKET did not receive any information after I sent the subject of proxy subscription with EMQ. But if I send a GET request for a proxy subscription topic with the SOCKET tool, I can receive it.

**Comment by jerry-chao** [comment]
> I am a UDP request initiated by SOCKET tool. The message used is the content of PUT request grabbed by LIBCODE plug-in. The module module module is also configured on EMQ, and the proxy subscription theme of the device is set. SOCKET did not receive any information after I sent the subject of proxy subscription with EMQ. But if I send a GET request for a proxy subscription topic with the SOCKET tool, I can receive it.
I cannot understand what is LIBCODE plug-in and what's module module module is configured on EMQ and how the proxy subscription theme is set. Can you give some example? @chenguosi

**Comment by chenguosi** [comment]
I need to spend some time demonstrating the screenshots. I'll show you later.

**Comment by jerry-chao** [comment]
ok, thanks. I am trying to read some COAP doc. I want to use COAP and We can studying together.

**Comment by chenguosi** [comment]
Sorry, I've been dealing with other things before and I haven't had time to give you a screenshot demo. I uploaded a word document, and then there are my specific steps, you can refer to see if you can locate the problem.
[coap协议演示.docx](https://github.com/emqx/emqx/files/3456227/coap.docx)

**Comment by jerry-chao** [comment]
ok, i will try to reappear the problem tomorrow

**Comment by jerry-chao** [comment]
@chenguosi I have read your doc. Your want to put(publish) something to one topic(TopicA) and to observe(a/b/%c/#) topic through mod_subscription at the same time.  Mayb you want to reduce the request times by this way. But it does not work. The msg which is received by mqtt_adapter and then it will be dropped because there are no subscribers.   

https://github.com/emqx/emqx-coap/blob/73583492d4ba1965cdfea145060897deb2c71fd8/src/emqx_coap_mqtt_adapter.erl#L320

Even though you can change the logic and gen_coap is not supportted for PUT method with observe.

Maybe you should divide it into put and get Method.

**Comment by chenguosi** [comment]
@jerry-chao 
Hello, COAP protocol has four message types, CON, NON, ACK and RST. CON message types will have ACK response return, using NON will not produce ACK response. But when I use the EMQX-COAP plug-in, the put and get methods are sent using the CON type. How do I send NON-type messages?
