### ISSUE TITLE
emqx as windows service --> error!

### ISSUE THREAD

**Issue by boerge42** [emqx/emqx#2738]
#### Environment

- OS: Windows Server 2016 Standard
- Erlang/OTP: 21 [erts-10.3] [64-bit]
- EMQ: 3.2.1

#### Description

--> emqx.cmd start

...emqx works fine!

--> emqx.cmd stop

I want to start empx as windows service:

--> emqx.cmd install

Service is registered, but at startup, the following error messages arrive in the eventlog and the service stops again:

- emqx_v3.2.1: Erlang machine stopped instantly (distribution name conflict?). The service is not restarted, ignoring OnFail option.

- The emqx_v3.2.1 service terminated with the following error: The process terminated unexpectedly.

What can I do?

Thanks...

**Comment by gilbertwong96** [comment]
Please execute the `erts-10.4\bin\erlsrv.exe list` and show me the erlang services you registered.

**Comment by boerge42** [comment]
D:\Applications\emqx>bin\emqx.cmd install
D:\Applications\emqx\erts-10.3\bin\erlsrv.exe: Service emqx_v3.2.1 added to system.
[SC] ChangeServiceConfig SUCCESS

D:\Applications\emqx>erts-10.3\bin\erlsrv.exe list
Service (S)Name Prio    OnFail  Args
emqx_v3.2.1     emqx@127.0.0.1  default restart -boot D:\Applications\emqx\releases\v3.2.1\emqx   -config d:/Applications/emqx/data/configs/app.2019.08.05.10.34.06.config -args_file d:/Applications/emqx/data/configs/vm.2019.08.05.10.34.06.args -vm_args d:/Applications/emqx/data/configs/vm.2019.08.05.10.34.06.args  -mnesia dir 'd:/Applications/emqx/data/mnesia/emqx@127.0.0.1'

**Comment by dy86** [comment]
I have the same problem....

**Comment by gilbertwong96** [comment]
This issue has been resolved in emqx v3.2.2 via setting emqx service as delayed-auto service. Please try with the latest windows version of emqx.

**Comment by dy86** [comment]
> This issue has been resolved in emqx v3.2.2 via setting emqx service as delayed-auto service. Please try with the latest windows version of emqx.

I'm using the emqx v3.2.2 for windows 10 , although it's displaying the v3.2.1 version

Can you give the correct emqx v3.2.2 download link? thank you.

**Comment by Eluso** [comment]
https://www.emqx.io/downloads

**Comment by sitsh** [comment]
windows 2016
v3.2.2  emqx install

start service error

logs
2019-08-14 18:07:21.174 [error] crasher:
    initial call: application_master:init/4
    pid: <0.158.0>
    registered_name: []
    exception exit: {bad_return,
                     {{emqx_app,start,[normal,[]]},
                      {'EXIT',
                       {{badmatch,
                         {error,
                          {shutdown,
                           {failed_to_start_child,emqx_router_sup,
                            {shutdown,
                             {failed_to_start_child,helper,
                              {{badmatch,
                                {error,{not_active_local,emqx_routing_node}}},
                               [{emqx_router_helper,init,1,
                                 [{file,
                                   "c:/emqx/ce/emqx-rel/_build/emqx/lib/emqx/src/emqx_router_helper.erl"},
                                  {line,95}]},
                                {gen_server,init_it,2,
                                 [{file,"gen_server.erl"},{line,374}]},
                                {gen_server,init_it,6,
                                 [{file,"gen_server.erl"},{line,342}]},
                                {proc_lib,init_p_do_apply,3,
                                 [{file,"proc_lib.erl"},{line,249}]}]}}}}}}},
                        [{emqx_app,start,2,
                          [{file,
                            "c:/emqx/ce/emqx-rel/_build/emqx/lib/emqx/src/emqx_app.erl"},
                           {line,32}]},
                         {application_master,start_it_old,4,
                          [{file,"application_master.erl"},{line,277}]}]}}}}
      in function  application_master:init/4 (application_master.erl, line 138)
    ancestors: [<0.157.0>]
    message_queue_len: 1
    messages: [{'EXIT',<0.159.0>,normal}]
    links: [<0.157.0>,<0.43.0>]
    dictionary: []
    trap_exit: true
    status: running
    heap_size: 987
    stack_size: 27
    reductions: 297
  neighbours:

**Comment by gilbertwong96** [comment]
Hi, @sitsh did you execute `emqx install` as administrator?

**Comment by sitsh** [comment]
> Hi, @sitsh did you execute `emqx install` as administrator?

yes 
2016 login user  as administrator，
Right click cmd to run as administrator and do not prompt permission to upgrade。

**Comment by boerge42** [comment]
> After the version v3.2.0 is returned, the installation works normally.

ditto ..., the error occurs from version 3.2.1 on

**Comment by renerlemes** [comment]
The error occurs in version 3.2.4 too

**Comment by Fellerson** [comment]
Hi

is it still the same issue ? I installed it as a service, without issue, it starts, but when i make the ping i don't get the pong. If i stop the Windows Service and start it manually from CMD it works
