### ISSUE TITLE
emqx start error centos7.2

### ISSUE THREAD

**Issue by Eluso** [emqx/emqx#2742]
#### Environment

- OS: CentOS7.2.1511
- Erlang/OTP: erts-10.3.5.1
- EMQ: emqx-ee-centos7-v3.2.0
- openssl:openssl-1.0.1e-42.el7.9.x86_64
#### Description

*A description of the issue*
./bin/emqx console
Exec: /opt/emqx/erts-10.3.5.1/bin/erlexec -boot /opt/emqx/releases/v3.2.0/emqx -mode embedded -boot_var ERTS_LIB_DIR /opt/emqx/erts-10.3.5.1/../lib -mnesia dir "/opt/emqx/data/mnesia/emqx@127.0.0.1" -config /opt/emqx/data/configs/app.2019.08.01.22.27.53.config -args_file /opt/emqx/data/configs/vm.2019.08.01.22.27.53.args -vm_args /opt/emqx/data/configs/vm.2019.08.01.22.27.53.args -- console
Root: /opt/emqx
/opt/emqx
Erlang/OTP 21 [erts-10.3.5.1] [source] [64-bit] [smp:2:2] [ds:2:2:10] [async-threads:32] [hipe]

{"Kernel pid terminated",application_controller,"{application_start_failure,kernel,{{shutdown,{failed_to_start_child,kernel_safe_sup,{on_load_function_failed,crypto}}},{kernel,start,[normal,[]]}}}"}
Kernel pid terminated (application_controller) ({application_start_failure,kernel,{{shutdown,{failed_to_start_child,kernel_safe_sup,{on_load_function_failed,crypto}}},{kernel,start,[normal,[]]}}})

Crash dump is being written to: log/crash.dump...done

update to openssl-1.0.2k-16.el7_6.1.x86_64 fix

**Comment by zhanghongtong** [comment]
Please install openssl above version 1.1.1
