### ISSUE TITLE
Auto upgrade

### ISSUE THREAD

**Issue by berrywira** [emqx/emqx#275]
Hi,

Can I upgrade to new version emqttd without turn off the service (Live update)?

**Comment by erylee** [comment]
Hi Berry,

Cannot. emqttd 0.10.x changed the mnesia data dir to avoid the collision when node name changed. 

Have to deploy the new release and merge your configuration(such as username, acl…) manually.

Regards
Feng

**Comment by berrywira** [comment]
Hi,

when emqttd was stable, it will same deploy manually?

**Comment by erylee** [comment]
@berrywira, will support live upgrade after 1.0 released:)

**Comment by berrywira** [comment]
Ok Thanks. :)

**Comment by zmstone** [comment]
hot beam upgrade is supported since 4.0
