### ISSUE TITLE
Development of custom plugin for EMQX

### ISSUE THREAD

**Issue by kabazakra** [emqx/emqx#2750]
Hi,

I am curious, in case of custom plugin development (for example, emqx-plugin-template), should I always rebuild EMQX broker (emqx-rel project) or there is a way to just put plugin's bin and config into the folder on the server and run some command to load it into EMQX? What is the best practice here? What options do I have?

**Comment by gilbertwong96** [comment]
Hi, @kabazakra. You have to rebuild the EMQ X broker. And I recommend an emqx plugin template to speed up the development of emqx plugin https://github.com/emqx/rebar3_emqx_plugin

**Comment by kabazakra** [comment]
Thanks, @gilbertwong96 .

Switched to the latest master. Trying to run

./bin/emqx console
or 
./bin/emqx start
See an error :

vm.args needs to have a -name parameter.
  -sname is not supported.

**Comment by SanjayChakrapani** [comment]
Hi @kabazakra. Did you get the solution because I'm also getting same error when I'm trying start EMQX

root@DESKTOP-HB0CBLN:~# emqx start
vm.args needs to have a -name parameter.
  -sname is not supported.
