### ISSUE TITLE
Setting log config not working as expected

### ISSUE THREAD

**Issue by Wayde2014** [emqx/emqx#2753]
#### Environment

- OS:  Ubuntu 16.04 
- Erlang/OTP: R20/9.1.5
- EMQ:  2.3.11 (run in docker，official image)

#### Description
In the production environment, I found that subscribers often receive delays when they receive messages, for a few minutes or even hours. I want to see the clues by looking at the broker debug level log.
After modifying the log-related configuration, it is found that the log file size does not take effect. It is always the default 1M, and the log rotation will be disordered.
And once the container is rebuilt, the value of log.console will always be reset to console. The container is found in the data/app.conf configuration as log.console=console, size and other log configuration items as I set.

**Comment by Wayde2014** [comment]
The configuration is as follows, please help me to see if it is not set up, thank you very much.

_node.name = 6d0c877e0353@172.30.8.2
node.cookie = emqsecretcookie
node.smp = auto
node.kernel_poll = on
node.async_threads = 32
node.process_limit = 2097152
node.max_ports = 1048576
node.dist_buffer_size = 8MB
node.max_ets_tables = 2097152
node.fullsweep_after = 1000
node.crash_dump = log/crash.dump
node.proto_dist = inet_tcp
node.dist_net_ticktime = 60
node.dist_listen_min = 6369
node.dist_listen_max = 6379
**log.dir = log
log.console = file
log.console.level = debug
log.console.file = log/console.log
log.console.size = 104857600
log.console.count = 10
log.info.file = log/info.log
log.info.size = 104857600
log.info.count = 10
log.error.file = log/error.log
log.error.size = 104857600
log.error.count = 10
log.crash = on
log.crash.file = log/crash.log
log.syslog = on
log.syslog.level = debug**
mqtt.allow_anonymous = true
mqtt.acl_nomatch = allow
mqtt.acl_file = etc/acl.conf
mqtt.cache_acl = true
mqtt.max_clientid_len = 1024
mqtt.max_packet_size = 128KB
mqtt.websocket_protocol_header = on
mqtt.keepalive_backoff = 0.75
mqtt.conn.force_gc_count = 100
mqtt.client.idle_timeout = 30s
mqtt.client.max_publish_rate = 256
mqtt.client.enable_stats = off
mqtt.session.max_subscriptions = 0
mqtt.session.upgrade_qos = off
mqtt.session.max_inflight = 32
mqtt.session.retry_interval = 20s
mqtt.session.max_awaiting_rel = 1000
mqtt.session.await_rel_timeout = 30s
mqtt.session.enable_stats = on
mqtt.session.expiry_interval = 2h
mqtt.session.ignore_loop_deliver = false
mqtt.mqueue.type = simple
mqtt.mqueue.max_length = 10000
mqtt.mqueue.low_watermark = 20%
mqtt.mqueue.high_watermark = 60%
mqtt.mqueue.store_qos0 = true
mqtt.broker.sys_interval = 1m
mqtt.pubsub.pool_size = 32
mqtt.pubsub.async = true
mqtt.bridge.max_queue_len = 10000
mqtt.bridge.ping_down_interval = 1s
mqtt.plugins.etc_dir =etc/plugins/
mqtt.plugins.loaded_file = data/loaded_plugins
listener.tcp.external = 0.0.0.0:1883
listener.tcp.external.acceptors = 64
listener.tcp.external.max_clients = 1000000
listener.tcp.external.access.1 = allow all
listener.tcp.external.backlog = 1024
listener.tcp.external.send_timeout = 15s
listener.tcp.external.send_timeout_close = on
listener.tcp.external.nodelay = true
listener.tcp.external.reuseaddr = true
listener.tcp.internal = 127.0.0.1:11883
listener.tcp.internal.acceptors = 128
listener.tcp.internal.max_clients = 1024000
listener.tcp.internal.backlog = 512
listener.tcp.internal.send_timeout = 5s
listener.tcp.external.send_timeout_close = on
listener.tcp.internal.nodelay = false
listener.tcp.internal.reuseaddr = true
listener.ssl.external = 8883
listener.ssl.external.acceptors = 32
listener.ssl.external.max_clients = 500000
listener.ssl.external.access.1 = allow all
listener.ssl.external.handshake_timeout = 15s
listener.ssl.external.keyfile = etc/certs/key.pem
listener.ssl.external.certfile = etc/certs/cert.pem
listener.ssl.external.reuseaddr = true
listener.ws.external = 8083
listener.ws.external.acceptors = 16
listener.ws.external.max_clients = 250000
listener.ws.external.access.1 = allow all
listener.ws.external.backlog = 1024
listener.ws.external.send_timeout = 15s
listener.ws.external.send_timeout_close = on
listener.ws.external.nodelay = true
listener.ws.external.reuseaddr = true
listener.wss.external = 8084
listener.wss.external.acceptors = 128
listener.wss.external.max_clients = 1024000
listener.wss.external.access.1 = allow all
listener.wss.external.handshake_timeout = 15s
listener.wss.external.keyfile = etc/certs/key.pem
listener.wss.external.certfile = etc/certs/cert.pem
listener.wss.external.backlog = 1024
listener.wss.external.send_timeout = 15s
listener.wss.external.send_timeout_close = on
listener.wss.external.reuseaddr = true
listener.api.mgmt = 0.0.0.0:8080
listener.api.mgmt.acceptors = 128
listener.api.mgmt.max_clients = 1024000
listener.api.mgmt.access.1 = allow all
listener.api.mgmt.backlog = 512
listener.api.mgmt.send_timeout = 15s
listener.api.mgmt.send_timeout_close = on
sysmon.long_gc = false
sysmon.long_schedule = 240
sysmon.large_heap = 8MB
sysmon.busy_port = false
sysmon.busy_dist_port = true_

**Comment by zhanghongtong** [comment]
You can set the log level through the environment variable when creating the container,just like this
```
$ docker run -it -e EMQX_LOG__LEVEL=debug --rm emqx/emqx:v3.2.2
node.max_ports=1048576
listener.tcp.external.acceptors=64
log.level=debug
listener.ssl.external.acceptors=32
node.process_limit=2097152
node.max_ets_tables=2097152
listener.ws.external.acceptors=16
node.name=f881bd74eef0@172.17.0.2
emqx v3.2.1 is started successfully!
              {mfargs,{prometheus_histogram,start_link,[]}},
              {restart_type,permanent},
              {shutdown,5000},
              {child_type,worker}]
2019-08-06 02:51:58.793 [info] application: prometheus
    started_at: 'f881bd74eef0@172.17.0.2'
2019-08-06 02:51:58.839 [info] application: luerl
    started_at: 'f881bd74eef0@172.17.0.2'
2019-08-06 02:51:58.839 [info] application: xmerl
    started_at: 'f881bd74eef0@172.17.0.2'
['2019-08-06T02:52:05Z']:emqx start
```

**Comment by Wayde2014** [comment]
> You can set the log level through the environment variable when creating the container,just like this
> 
> ```
> $ docker run -it -e EMQX_LOG__LEVEL=debug --rm emqx/emqx:v3.2.2
> node.max_ports=1048576
> listener.tcp.external.acceptors=64
> log.level=debug
> listener.ssl.external.acceptors=32
> node.process_limit=2097152
> node.max_ets_tables=2097152
> listener.ws.external.acceptors=16
> node.name=f881bd74eef0@172.17.0.2
> emqx v3.2.1 is started successfully!
>               {mfargs,{prometheus_histogram,start_link,[]}},
>               {restart_type,permanent},
>               {shutdown,5000},
>               {child_type,worker}]
> 2019-08-06 02:51:58.793 [info] application: prometheus
>     started_at: 'f881bd74eef0@172.17.0.2'
> 2019-08-06 02:51:58.839 [info] application: luerl
>     started_at: 'f881bd74eef0@172.17.0.2'
> 2019-08-06 02:51:58.839 [info] application: xmerl
>     started_at: 'f881bd74eef0@172.17.0.2'
> ['2019-08-06T02:52:05Z']:emqx start
> ```

Thank you for your prompt reply.
However, my current version is 2.3.11. Do I need to upgrade to solve this problem?

**Comment by zhanghongtong** [comment]
@Wayde2014  You're welcome. 
2.3.11 is too old. You are recommended to upgrade to the latest version 3.2.2

**Comment by Wayde2014** [comment]
> @Wayde2014 You're welcome.
> 2.3.11 is too old. You are recommended to upgrade to the latest version 3.2.2

Thanks, I got it.
