### ISSUE TITLE
I get Many qos2.dropped msgs

### ISSUE THREAD

**Issue by alvinh2** [emqx/emqx#2759]
#### Environment

- OS: win 7
- Erlang/OTP: 
- EMQ: 3.2.0

#### Description
I have a server thread and 200 clients thread; 
At qos2 ,when server send  msgs to clients, some client cann't receive all message , On EMQX Dashboard ,I see many qos2.dropped msgs. But at qos 1, the system is working very well. Can you help me? 

*A description of the issue*

**Comment by danyanya** [comment]
@alvinh2 
Have you found any solution?
Cuz I've the same issue on 

- Ubuntu 18.04
- EMQ 3.01

**Comment by terry-xiaoyu** [comment]
```

## Maximum QoS2 packets (Client -> Broker) awaiting PUBREL, 0 means no limit.
##
## Value: Number
zone.external.max_awaiting_rel = 100

## The QoS2 messages (Client -> Broker) will be dropped if awaiting PUBREL timeout.
##
## Value: Duration
zone.external.await_rel_timeout = 300s
```

If the above configurations solve your problem, then it is caused by the inflight qos2 messages exceed the max values. This is probably an evidence of slow consumers.
