### ISSUE TITLE
Cannot Scale EMQX beyond 250 connections [ even with 16GB Machine ]

### ISSUE THREAD

**Issue by Jeyanthinath** [emqx/emqx#2762]
#### Environment

- OS: Ubuntu 18
- Erlang/OTP: NA
- EMQ: v3.2.2

#### Description

Initally I was running a emqx on the aws t2.micro and tried a load testing , it failed after reaching 200 connections eventhough I tweaked almost all the connection parameters to high it is not passing over the connection limit of 200, I though there would be some ways to increase the memory allocated to it , but after viewing this thread https://github.com/emqx/emqx/issues/1989 I found out there is no way to increase the memory, as the connections will consume the memory on the fly.

But after load test also the `(total) in Memory Info` of the attached screenshot is not increasing more than 150M.
<img width="1222" alt="Screenshot 2019-08-06 at 5 23 34 PM" src="https://user-images.githubusercontent.com/2253649/62537863-184b9d00-b86f-11e9-8cae-d70c7a45b890.png">

So  I thought machine power was the issue and I moved from `t2.micro (1CPU , 1GB RAM)` to `t2.xlarge (4CPU, 16GB RAM)` with the below attached configuration , but still no drastic performance improvement, it moved up from a 200 to 250 connections. 

I even tried the https://github.com/emqx/emqx-docs-en/blob/master/source/tune.rst, still no luck.

With the latest machine, while load testing after 250 connections, the connections will dropped continuously to less than ten.

After changing almost all parameters in configuration file, still I note that *The memory is not getting used after 250M , don't know why*

I know I am missing some understanding here  so,  can you please help me figuring out this issue, because Mosquitto MQTT with 1GB RAM performing on par with the 16GB RAM Machine. 

[emqx.conf.txt](https://github.com/emqx/emqx/files/3472072/emqx.conf.txt)

**Comment by Jeyanthinath** [comment]
Any update ?

**Comment by turtleDeng** [comment]
Please provide a log file.

**Comment by albinantony2904** [comment]
I also have the same issue when trying to create multiple clients from Django app. After 250 clients I am not able to create any more clients.

**Comment by albinantony2904** [comment]
> Any update ?

Did you found any solution

**Comment by HJianBo** [comment]
Hi guys, Could you provide more details after the connection connecting failed! i.g: error log?

If can not find any more error logs, Plz ensure that the MQTT packet arrives at the EMQ host.

**Comment by HJianBo** [comment]
Hi, guys! Any remaining question here?

**Comment by Jeyanthinath** [comment]
@HJianBo we are now able to do more connections, thanks for your response, 

there are no pending question on this front :)
