### ISSUE TITLE
emqx plugins conf not written when changed on dashboard

### ISSUE THREAD

**Issue by MavBoss86** [emqx/emqx#2763]
#### Environment

- OS: Ubuntu 18.04
- Erlang/OTP: R21/10.3
- EMQ: 3.2.x

#### Description

After upgrade emqx from 2.3.6 to 3.2.x version, when we change some information on the dashboard plugin window this changes are not written on the conf file of the plugin file : for example, changing the http plugin on the dashboard does not change the file emqx_auth_plugin.conf on the /etc/emqx/plugin folder. So if I then upgrade to another version, the settings are not retained (and the installation not ask me which file to bring).

This happens on the 3.2.0 - 3.2.1 and 3.2.2.

**Comment by turtleDeng** [comment]
Sorry, it is not supported to modify the plugin configuration in the dashboard. You can modify the plugin configuration file and then use 
```
emqx_ctl plugins reload xxx
```

**Comment by HJianBo** [comment]
Hi, guys The ability to change the configuration on Dashboard has been abolished since v4.0-rc.2

**Comment by HJianBo** [comment]
A more recommended approach is to set the broker by modifying the conf files.

The related docs:  https://docs.emqx.io/broker/v3/en/config.html or README.md of plugin repository
