### ISSUE TITLE
EMQX 3.2.1 zone configuration

### ISSUE THREAD

**Issue by gsngsngsn** [emqx/emqx#2765]
#### Environment

- OS: 
- Erlang/OTP: 
- EMQ:  3.2.1

#### Description

Setting up zone configure like this:"
zone.test.idle_timeout = 15s
zone.test.publish_limit = 10, 100
listener.tcp.test = 0.0.0.0:1888
....
"
But no port or anything happened. 

https://developer.emqx.io/docs/broker/v3/en/config.html#mqtt-zones-parameter-configuration
It seems like EMQX allows customized zone field "zone.$name.xxx" , such as zone.test, so that I can allow it to listen to extra ports and handle those port in a different sets of rules (eg. diff limits on publishing message, flapping etc etc).

I am wondering if I have missed sth or this is not supported yet.

**Comment by gsngsngsn** [comment]
Hi there, I am wondering if this means that the feature is not implemented yet, and might be released during 3.3?

**Comment by gsngsngsn** [comment]
Any news?

**Comment by HJianBo** [comment]
Hi, @gsngsngsn sorry for late reply

I have try to add a new zone, it works for me. Just add the following 3 lines:
```properties
zone.test.idle_timeout = 15s
zone.test.publish_limit = 10,100m

listener.tcp.test = 0.0.0.0:1884
```

And, start it with `./bin/emqx console`

```
Start mqtt:tcp listener on 0.0.0.0:1884 successfully.
```

Obviously it works.

Can you share your failed conf files to me ?
