### ISSUE TITLE
emqx_auth_http doesn't work when cleanSession = False and client connect at second time

### ISSUE THREAD

**Issue by wenkaigu** [emqx/emqx#2795]
#### Environment

- OS: Ubuntu
- Erlang/OTP: 
- EMQ:  3.2.1

#### Description
We have enabled emqx_auth_http for user authorization . we have set the acl action from ignore to disconnect.  

When our client connect to emqx server with wrong username and password while setting cleanSession = False, then client was able to connect to emqx server and was disconnected immediately.  
However, when we use the same client connect to server again with same wrong username and password before the session is expired, we are able to connect to emqx server and it seems emqx_auth_http is not called. 

Please suggest, as in such case, we expect the emqx_auth_http should disconnect the client again.

Regards，
Wenkai Gu

**Comment by HJianBo** [comment]
Hi, @wenkaigu I can't reproduce this issue as mentioned steps. It always disconnected by ACL deny.  I have tested it with these options of `emqx.conf`:

```properties
allow_anonymous = false
zone.external.acl_deny_action = disconnect
```


So:

1. Could you provider more details, logs or explicit steps?
2. Make sure the emqx_auth_http ACL request has sent to HTTP Server or not

**Comment by wenkaigu** [comment]
Hi, 

Thanks for the quick response. We notice a difference between our config file and yours. 

We have set the value as below:
allow_anonymous = true
zone.external.acl_deny_action = disconnect

The reason why we put allow_anonymous = true is because we have some legacy clients connecting to our EMQX server without username & password.  So as of now, we allow client connect to our server without username/password or with a correct username/password. We will return HTTP code as 400 only for the clients who provide username/password but the username/password isn't correct.

Is the "allow_anonymous = true" the reason?

Regards,
Wenkai Gu

**Comment by HJianBo** [comment]
> Is the "allow_anonymous = true" the reason?
I'm not sure.

Could you provide the two scenarios debug log for me ?

**Comment by wenkaigu** [comment]
Hi,

Never Mind. It seems a bug with our client. It prints 'subscribe success' wrongly as it actually isn't. 

I checked in EMQX dashboard and find my session, however, no topic listed there. So emqx works correctly. Thanks. 

I am closing the issue as well. 

Regards，
Wenkai
