### ISSUE TITLE
Parse failed for function_clause

### ISSUE THREAD

**Issue by JaxSONG** [emqx/emqx#2796]
hi, i use emqx and feel confused with this broblem, and i can't find any solution for this, can you help me to find the root cause and how to fix it?

#### Environment

- OS:  Linux X3399
- Erlang/OTP: Erlang
- EMQ:  v3.1.2

#### Description

*A description of the issue*
`2019-08-15 08:17:39.458 [error] WRA2019204F075EDB26@192.168.2.1:47438 [Connection] Parse failed for function_clause
Stacktrace:[{emqx_frame,parse_packet,
                        [{mqtt_packet_header,6,false,3,false},
                         <<104,101,97,114,116,147,223,115,101,110,115,111,114,
                           95,115,110,58,87,82,65,50,48,49,57,50,48,52,70,48,
                           55,53,69,68,66,50,54,44,115,105,103,110,97,108,58,45>>,
                         #{max_packet_size => 1048576,version => 4}],
                        [{file,"src/emqx_frame.erl"},{line,128}]},
            {emqx_frame,parse_frame,4,
                        [{file,"src/emqx_frame.erl"},{line,109}]},
            {emqx_connection,process_incoming,3,
                             [{file,"src/emqx_connection.erl"},{line,392}]},
            {gen_statem,call_state_function,5,
                        [{file,"gen_statem.erl"},{line,1660}]},
            {gen_statem,loop_event_state_function,6,
                        [{file,"gen_statem.erl"},{line,1023}]},
            {proc_lib,wake_up,3,[{file,"proc_lib.erl"},{line,259}]}]
Error data:<<102,45,104,101,97,114,116,147,223,115,101,110,115,111,114,95,115,
             110,58,87,82,65,50,48,49,57,50,48,52,70,48,55,53,69,68,66,50,54,
             44,115,105,103,110,97,108,58,45,57,50,44,104,117,98,95,115,110,58,
             87,82,65,50,48,49,57,50,48,52,70,48,55,53,69,68,66,50,54,50,90,0,
             11,115,104,101,108,102,45,104,101,97,114,116,79,191,115,101,110,
             115,111,114,95,115,110,58,87,82,65,50,48,49,57,50,48,52,70,48,55,
             53,69,68,66,50,54,44,115,105,103,110,97,108,58,45,57,50,44,104,
             117,98,95,115,110,58,87,82,65,50,48,49,57,50,48,52,70,48,55,53,69,
             68,66,50,54,50,90,0,11,115,104,101,108,102,45,104,101,97,114,116,
             147,223,115,101,110,115,111,114,95,115,110,58,87,82,65,50,48,49,
             57,50,48,52,70,48,55,53,69,68,66,50,54,44,115,105,103,110,97,108,
             58,45,57,50,44,104,117,98,95,115,110,58,87,82,65,50,48,49,57,50,
             48,52,70,48,55,53,69,68,66,50,54,50,90,0,11,115,104,101,108,102,
             45,104,101,97,114,116,79,191,115,101,110,115,111,114,95,115,110,
             58,87,82,65,50,48,49,57,50,48,52,70,48,55,53,69,68,66,50,54,44,
             115,105,103,110,97,108,58,45,57,50,44,104,117,98,95,115,110,58,87,
             82,65,50,48,49,57,50,48,52,70,48,55,53,69,68,66,50,54,50,119,0,20,
             114,97,119,45,100,101,118,105,99,101,45,104,101,97,114,116,98,101,
             97,116,253,239,123,32,34,115,110,34,58,32,34,87,73,65,50,48,49,57,
             48,56,65,68,49,65,52,54,52,53,52,66,34,44,32,34,112,114,111,116,
             111,95,118,101,114,34,58,32,34,49,46,48,46,48,34,44,32,34,105,100,
             34,58,32,49,44,32,34,104,117,98,95,115,110,34,58,32,34,87,82,65,
             50,48,49,57,50,48,52,70,48,55,53,69,68,66,50,54,34,32,125,50,119,
             0,20,114,97,119,45,100,101,118,105,99,101,45,104,101,97,114,116,
             98,101,97,116,202,247,123,32,34,115,110,34,58,32,34,87,73,65,50,
             48,49,57,48,56,54,70,55,67,65,52,57,67,48,50,34,44,32,34,112,114,
             111,116,111,95,118,101,114,34,58,32,34,49,46,48,46,48,34,44,32,34,
             105,100,34,58,32,50,44,32,34,104,117,98,95,115,110,34,58,32,34,87,
             82,65,50,48,49,57,50,48,52,70,48,55,53,69,68,66,50,54,34,32,125,
             50,119,0,20,114,97,119,45,100,101,118,105,99,101,45,104,101,97,
             114,116,98,101,97,116,209,123,123,32,34,115,110,34,58,32,34,87,73,
             65,50,48,49,57,48,56,55,53,67,68,55,70,56,48,48,69,34,44,32,34,
             112,114,111,116,111,95,118,101,114,34,58,32,34,49,46,48,46,48,34,
             44,32,34,105,100,34,58,32,51,44,32,34,104,117,98,95,115,110,34,58,
             32,34,87,82,65,50,48,49,57,50,48,52,70,48,55,53,69,68,66,50,54,34,
             32,125,50,119,0,20,114,97,119,45,100,101,118,105,99,101,45,104,
             101,97,114,116,98,101,97,116,220,189,123,32,34,115,110,34,58,32,
             34,87,73,65,50,48,49,57,48,56,54,55,49,57,49,66,55,67,57,53,34,44,
             32,34,112,114,111,116,111,95,118,101,114,34,58,32,34,49,46,48,46,
             48,34,44,32,34,105,100,34,58,32,52,44,32,34,104,117,98,95,115,110,
             34,58,32,34,87,82,65,50,48,49,57,50,48,52,70,48,55,53,69,68,66,50,
             54,34,32,125,50,119,0,20,114,97,119,45,100,101,118,105,99,101,45,
             104,101,97,114,116,98,101,97,116,218,94,123,32,34,115,110,34,58,
             32,34,87,73,65,50,48,49,57,48,56,70,55,51,69,57,53,68,70,51,56,34,
             44,32,34,112,114,111,116,111,95,118,101,114,34,58,32,34,49,46,48,
             46,48,34,44,32,34,105,100,34,58,32,53,44,32,34,104,117,98,95,115,
             110,34,58,32,34,87,82,65,50,48,49,57,50,48,52,70,48,55,53,69,68,
             66,50,54,34,32,125,50,119,0,20,114,97,119,45,100,101,118,105,99,
             101,45,104,101,97,114,116,98,101,97,116,109,47,123,32,34,115,110,
             34,58,32,34,87,73,65,50,48,49,57,48,56,52,65,66,69,56,67,55,68,57,
             53,34,44,32,34,112,114,111,116,111,95,118,101,114,34,58,32,34,49,
             46,48,46,48,34,44,32,34,105,100,34,58,32,54,44,32,34,104,117,98,
             95,115,110,34,58,32,34,87,82,65,50,48,49,57,50,48,52,70,48,55,53,
             69,68,66,50,54,34,32,125,50,119,0,20,114,97,119,45,100,101,118,
             105,99,101,45,104,101,97,114,116,98,101,97,116,130,151,123,32,34,
             115,110,34,58,32,34,87,73,65,50,48,49,57,48,56,69,52,53,65,57,57,
             48,67,53,65,34,44,32,34,112,114,111,116,111,95,118,101,114,34,58,
             32,34,49,46,48,46,48,34,44,32,34,105,100,34,58,32,55,44,32,34,104,
             117,98,95,115,110,34,58,32,34,87,82,65,50,48,49,57,50,48,52,70,48,
             55,53,69,68,66,50,54,34,32,125,50,119,0,20,114,97,119,45,100,101,
             118,105,99,101,45,104,101,97,114,116,98,101,97,116,245,75,123,32,
             34,115,110,34,58,32,34,87,73,65,50,48,49,57,48,56,52,66,48,65,66,
             55,51,52,69,48,34,44,32,34,112,114,111,116,111,95,118,101,114,34,
             58,32,34,49,46,48,46,48,34,44,32,34,105,100,34,58,32,56,44,32,34,
             104,117,98,95,115,110,34,58,32,34,87,82,65,50,48,49,57,50,48,52,
             70,48,55,53,69,68,66,50,54,34,32,125,50,119,0,20,114,97,119,45,
             100,101,118,105,99,101,45,104,101,97,114,116,98,101,97,116,206,
             165,123,32,34,115,110,34,58,32,34,87,73,65,50,48,49,57,48,56,70,
             49,55,66,57,49,55,51,50,65,34,44,32,34,112,114,111,116,111,95,118,
             101,114,34,58,32,34,49>>`

**Comment by JaxSONG** [comment]
any update?

**Comment by gilbertwong96** [comment]
Sorry for so late response, could you please show me the packet you sent to the emqx? It is difficult to locate the problem if I cannot reproduce the problem you encountered.

**Comment by albinantony2904** [comment]
I have the same issue

`2019-08-23 05:18:22.463 [error] 103.214.235.221:37792 [Connection] Parse failed for function_clause
Stacktrace:[{emqx_frame,parse_utf8_string,
                        [<<1,1,1>>],
                        [{file,"src/emqx_frame.erl"},{line,359}]},
            {emqx_frame,parse_packet,3,
                        [{file,"src/emqx_frame.erl"},{line,129}]},
            {emqx_frame,parse_frame,4,
                        [{file,"src/emqx_frame.erl"},{line,109}]},
            {emqx_connection,process_incoming,3,
                             [{file,"src/emqx_connection.erl"},{line,392}]},
            {gen_statem,call_state_function,5,
                        [{file,"gen_statem.erl"},{line,1660}]},
            {gen_statem,loop_event_state_function,6,
                        [{file,"gen_statem.erl"},{line,1023}]},
            {proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,249}]}]
Error data:<<22,3,1,1,1,1,0,0,253,3,3,147,159,21,60,124,252,10,132,131,198,86,
             110,215,17,149,243,69,140,40,15,24,146,171,240,47,109,74,91,84,88,
             200,97,0,0,128,192,47,192,43,192,48,192,44,0,158,192,39,0,103,192,
             40,0,107,192,36,192,20,192,10,0,165,0,163,0,161,0,159,0,106,0,105,
             0,104,0,57,0,56,0,55,0,54,192,50,192,46,192,42,192,38,192,15,192,
             5,0,157,0,61,0,53,192,35,192,19,192,9,0,164,0,162,0,160,0,64,0,63,
             0,62,0,51,0,50,0,49,0,48,192,49,192,45,192,41,192,37,192,14,192,4,
             0,156,0,60,0,47,192,18,192,8,0,22,0,19,0,16,0,13,192,13,192,3,0,
             10,0,255,1,0,0,84,0,11,0,4,3,0,1,2,0,10,0,28,0,26,0,23,0,25,0,28,
             0,27,0,24,0,26,0,22,0,14,0,13,0,11,0,12,0,9,0,10,0,35,0,0,0,13,0,
             32,0,30,6,1,6,2,6,3,5,1,5,2,5,3,4,1,4,2,4,3,3,1,3,2,3,3,2,1,2,2,2,
             3,51,116,0,0>>`

**Comment by JaxSONG** [comment]
> Sorry for so late response, could you please show me the packet you sent to the emqx? It is difficult to locate the problem if I cannot reproduce the problem you encountered.

It is happened in irregularity way, and we send a lot of data can not locate the packet we send to emqx when this problem happened

**Comment by turtleDeng** [comment]
@JaxSONG  What is the MQTT Version you are using?

**Comment by turtleDeng** [comment]
@albinantony2904 
The MQTT protocol requires the use of UTF8 encoding format, please use the correct encoding format.

**Comment by RodaBVB** [comment]
#### Environment
- OS: Ubuntu 16.04.5 LTS
- Erlang/OTP: 18
- EMQ: 3.2.2

#### Topology
- 2x EMQX in cluster (8vCPU, 15GB RAM each) ~50K clients

I am also facing the same issue, any reason why this error is occurring ?

Errors / Exceptions happening by Brookes:

```
(emqx@10.122.53.46)1> 2020-03-24 08:19:46.086 [error] 10.122.249.12:36319 [Channel] Parse failed for function_clause
    Stacktrace:[{emqx_frame,parse_utf8_string,
           [<<1,1,73>>],
           [{file,
                "/tmp/emqx/v3.2.2/_checkouts/emqx/src/emqx_frame.erl"},
            {line,378}]},
       {emqx_frame,parse_packet,3,
           [{file,
                "/tmp/emqx/v3.2.2/_checkouts/emqx/src/emqx_frame.erl"},
            {line,148}]},
       {emqx_frame,parse_frame,4,
           [{file,
                "/tmp/emqx/v3.2.2/_checkouts/emqx/src/emqx_frame.erl"},
            {line,126}]},
       {emqx_channel,process_incoming,3,
           [{file,
                "/tmp/emqx/v3.2.2/_checkouts/emqx/src/emqx_channel.erl"},
            {line,408}]},
       {gen_statem,call_state_function,5,
           [{file,"gen_statem.erl"},{line,1660}]},
       {gen_statem,loop_event_state_function,6,
           [{file,"gen_statem.erl"},{line,1023}]},
       {proc_lib,init_p_do_apply,3,
           [{file,"proc_lib.erl"},{line,249}]}]
Error data:<<22,3,1,1,73,1,0,1,69,3,3,94,45,48,63,28,224,122,102,252,80,186,55,
             64,105,152,168,231,202,58,216,195,208,188,247,148,191,85,20,188,
             49,231,147,0,0,172,192,48,192,44,192,40,192,36,192,20,192,10,0,
             165,0,163,0,161,0,159,0,107,0,106,0,105,0,104,0,57,0,56,0,55,0,54,
             0,136,0,135,0,134,0,133,192,50,192,46,192,42,192,38,192,15,192,5,
             0,157,0,61,0,53,0,132,192,47,192,43,192,39,192,35,192,19,192,9,0,
             164,0,162,0,160,0,158,0,103,0,64,0,63,0,62,0,51,0,50,0,49,0,48,0,
             154,0,153,0,152,0,151,0,69,0,68,0,67,0,66,192,49,192,45,192,41,
             192,37,192,14,192,4,0,156,0,60,0,47,0,150,0,65,0,7,192,17,192,7,
             192,12,192,2,0,5,0,4,192,18,192,8,0,22,0,19,0,16,0,13,192,13,192,
             3,0,10,0,255,1,0,0,112,0,0,0,23,0,21,0,0,18,109,113,116,116,45,
             111,111,46,116,101,108,101,107,111,109,46,115,105,0,11,0,4,3,0,1,
             2,0,10,0,28,0,26,0,23,0,25,0,28,0,27,0,24,0,26,0,22,0,14,0,13,0,
             11,0,12,0,9,0,10,0,35,0,0,0,13,0,32,0,30,6,1,6,2,6,3,5,1,5,2,5,3,
             4,1,4,2,4,3,3,1,3,2,3,3,2,1,2,2,2,3,0,15,0,1,1>> 
```
Can you explain this  in more detail?

**Comment by moluzhui** [comment]
I have the same issue. This happens when I use the `EMQ X Edge` bridge to bridge messages to `EMQ X Broker`.

```
2020-07-21 10:41:36.752 [warning] [Alarm Handler] New Alarm: cpu_high_watermark, Alarm Info: 100.0
2020-07-21 10:42:36.759 [warning] [Alarm Handler] New Alarm: cpu_high_watermark, Alarm Info: 100.0
2020-07-21 10:42:44.323 [error] 192.168.0.77:5106 [Channel] Parse failed for function_clause

                 Stacktrace:[{emqx_frame,parse_packet,
                                 [{mqtt_packet_header,4,false,3,true},
                                  <<"T / HTTP/1.1\r\nHost: 192.168.0.59:8888\r\nUser-Agent: avast! Antivirus\r\n">>,
                                  #{max_size => 5242880,version => 4}],
                                 []},
                             {emqx_frame,parse_frame,4,[]},
                             {emqx_channel,process_incoming,3,[]},
                             {gen_statem,call_state_function,5,[]},
                             {gen_statem,loop_event_state_function,6,[]},
                             {proc_lib,init_p_do_apply,3,[]}]
Error data:<<"GET / HTTP/1.1\r\nHost: 192.168.0.59:8888\r\nUser-Agent: avast! Antivirus\r\nAccept: */*\r\nAccept-Encoding: deflate, gzip\r\n\r\n">>
2020-07-21 10:43:36.768 [warning] [Alarm Handler] New Alarm: cpu_high_watermark, Alarm Info: 100.0
2020-07-21 10:44:36.776 [warning] [Alarm Handler] New Alarm: cpu_high_watermark, Alarm Info: 100.0
```
