### ISSUE TITLE
how to reload config without restarting broker 

### ISSUE THREAD

**Issue by liqiangno1** [emqx/emqx#2809]
#### Environment

- OS: centos7
- Erlang/OTP:  R21/10.3.5.1
- EMQ: 3.2.2

#### Description
is there a web api or shell command to reload config?

**Comment by gilbertwong96** [comment]
For now, emqx does not support this feature.

**Comment by zmstone** [comment]
feature in 5.0

**Comment by Gypsying** [comment]
> feature in 5.0

any method to support reload config in 5.0.x?
