### ISSUE TITLE
Http publish not working in v3.2.0

### ISSUE THREAD

**Issue by radumazi** [emqx/emqx#2816]
#### Environment

- OS: using the docker image emqx/emqx:v3.2.0
- Erlang/OTP: 
- EMQ: v.3.2.0

#### Description

Hello,

I have an eqmx cluster deployed to kubernetes, and I want to publish via http. I followed the example here https://github.com/emqx/emqx/wiki/HTTP-Publish

`curl --basic -u user:pass -d "qos=1&retain=0&topic=/a/b/c&message=hello from http..." -k http://emqx-emqx-chart:8083/mqtt/publish -v`

returns **404 Not Found**

For double checking, the command 
`curl --basic -u user:pass -d "qos=1&retain=0&topic=/a/b/c&message=hello from http..." -k http://emqx-emqx-chart:8083/mqtt -v`

returns **426 Upgrade Required** , as expected

Thank you

**Comment by turtleDeng** [comment]
@radumazi Please read the API usage documentation. https://docs.emqx.io/broker/v3/en/rest.html#publish-subscribe

**Comment by radumazi** [comment]
@turtleDeng Thank you very much, that page in the wiki led me off. It's the first result that comes up when you google "emqx http publish", and the other results are not pointing to the rest api either. Maybe you should remove that page from the wiki, it will probably mislead other people too.
Again, thank you, have a nice day!
