### ISSUE TITLE
Message Statistics base on specific topics.  

### ISSUE THREAD

**Issue by gsngsngsn** [emqx/emqx#2822]
#### Environment

- OS: centos9
- Erlang/OTP: 
- EMQ: 3.2.1

#### Description

Hi there, I am wondering if EMQX provide statistics regarding specific topics. Or even topics with wildcards. 

For example, I would like to know the number && bytes that are going through (send & receive) topics that match certain pattern, for example "/topic/test/**". 

Is it possible to do so within the current release? I see that we can get states base on what "$SYS" provide but not on specific topics.

**Comment by gsngsngsn** [comment]
Any news?

**Comment by gilbertwong96** [comment]
Hi, @gsngsngsn, sorry for so late response, you cannot do that within the current release, the reason we have no schedule to implement this is that this feature would cost a lot of performance.

**Comment by gsngsngsn** [comment]
@gilbertwong96 thanks.

I guess we will have to implement as our local plugin or stone. 

I saw a tag changed to 4.0-alpha.2 though, does that mean you are planning to have such feature in the future?

**Comment by wivwiv** [comment]
@gsngsngsn 

We support it in v4.1. However, for performance reasons, topic statistics still does not support wildcards.

![image](https://user-images.githubusercontent.com/25006774/83317064-afe60600-a25c-11ea-8c03-4c466faf56c6.png)
