### ISSUE TITLE
 ./bin/emqx_ctl status

### ISSUE THREAD

**Issue by gftao** [emqx/emqx#2823]
#### Environment

- OS: 
- Erlang/OTP: 
- EMQ:  3.2.2

#### Description
./bin/emqx_ctl status
![image](https://user-images.githubusercontent.com/5326060/63500119-d2900500-c4fb-11e9-8f09-3965da70d179.png)

**Comment by tigercl** [comment]
Hi, @gftao, this error means that your host has run out of available ports. Please optimize the kernel parameters.
