### ISSUE TITLE
What is the difference between listener.tcp.internal and listener.tcp.external?

### ISSUE THREAD

**Issue by xlb0479** [emqx/emqx#2843]
#### Environment

- OS:  Ubuntu
- Erlang/OTP:  22
- EMQ:  3.2

#### Description

According to `emqx.conf` and the `Listeners` sector, there are `listener.tcp.external` and `listener.tcp.internal`. What is the difference between these two configs?

I know client connect to emqx broker at port 1883 as the default value of `listener.tcp.external`,  what is the use case of `listener.tcp.internal`?

If my client is a local instance with emqx broker, should I use `listener.tcp.internal`?

**Comment by gilbertwong96** [comment]
Generally, the external zone is preferred.

**Comment by phanimahesh** [comment]
listener.tcp.internal specifies the internal tcp listener. This is assigned to zone internal, and can be setup to have different permissions/behaviour compared to the external listener. It is needed/useful only when you have different "kinds" of traffic that must be distinguished, for example, external traffic with subscription only rights or strict acls, and internal traffic with a different acls or no acls.
