### ISSUE TITLE
Docker containers exit when /opt/emqttd/bin/emqttd_ctl status fails

### ISSUE THREAD

**Issue by matzuba** [emqx/emqx#2849]
#### Environment

- OS:  RHEL 7.6
- Erlang/OTP: 
- EMQ:  2.3.11

#### Description

NGINX --> DOCKER -- custom image with EMQ installed

I am seeing an issue where containers will exit.  This is caused by the /opt/emqttd/bin/emqttd_ctl status failing/reporting that emq is down.  When i log into the container or check from the host, emq is not actually down but whatever the status check is doing fails 5 odd times and exit the container.

What conditions would cause the container to exit? 
What is the status script actually checking and what does it require to be successful?  to be able to open a sockert for a ping test?  I have noticed it fails if a file handler (EMFILE) limit has been reached.

I have noticed the docker containers have a very high load of 300% plus and status check will flap and wait like it eventually gets a connection to do the test and then it will fail again.  Would high CPU load prevent the status check from running?

I have approxs 160K simulanteous  client connecting and have followed the tuning guide

**Comment by zhanghongtong** [comment]
Hi @matzuba, I suggest you upgrade EMQX version to 3.2.2, 2.3.11 is too old
