### ISSUE TITLE
connect successfully, but didn't create a session

### ISSUE THREAD

**Issue by EchoXBR** [emqx/emqx#2852]
#### Environment

- OS: CentOS 7.03
- Erlang/OTP: R21/10.2.1
- EMQ: 3.0.1

#### Description

*A description of the issue*
when my android's device connect successfully by mqtt  protocol,emq's console can only find a connect,can't find a session.
This phenomenon is accidental, I do not know how to troubleshoot the problem.
Now I only have about 200 devices connected .

**Comment by EchoXBR** [comment]
I have found ther error log in /var/log/emqx/
`[error] 86966102256381@113.102.165.126:13431 [SM] More than one session found: [<0.23768.2104>,<0.26586.2205>]`
I wonder if sessions don't automatically close

**Comment by EchoXBR** [comment]
I also find some other error info like `Failed to open session: client_id_unavailable` , What causes this error?

**Comment by terry-xiaoyu** [comment]
@EchoXBR 3.0.1 is too old and many bug fixes has been made since then. Could you upgrade to 3.2.2 and try again?

**Comment by terry-xiaoyu** [comment]
You problem is probably caused by two or more clients connected to the emqx cluster using the same client-id. They are conflicting on the session creation.

**Comment by EchoXBR** [comment]
Thank you for your reply.
I've actually tried to connect to emqx with two same client-id, but only one will connect to successfully create the session.not like I mentioned above.
The version seems to be old, I will try to upgrade to 3.2.2 and then try to run it again. In fact, we found this problem very passive, and the customer informed us after the problem occurred
