### ISSUE TITLE
emqtt_bench

### ISSUE THREAD

**Issue by danzonger** [emqx/emqx#2854]
#### Environment

- OS: Centos7
- Erlang/OTP: 21
- EMQ: 3.2

#### Description

*A description of the issue*
执行 ./emqtt_bench conn -c 100 -i 10 -h 106.52.169.18 -p 1883
escript: exception error: undefined function counters:new/2
  in function  emqtt_bench:init/0 (/opt/emqtt_benchmark/src/emqtt_bench.erl, line 216)
  in call from emqtt_bench:start/2 (/opt/emqtt_benchmark/src/emqtt_bench.erl, line 207)
  in call from escript:run/2 (escript.erl, line 758)
  in call from escript:start/1 (escript.erl, line 277)
  in call from init:start_em/1 
  in call from init:do_boot/3

**Comment by danzonger** [comment]
需要安装最新的erl 21.3

**Comment by turtleDeng** [comment]
Thank you for your feedback.
https://github.com/emqx/emqtt-bench/commit/6db9bfc4fd953c4e5ace9ff35c152095a973bf24
