### ISSUE TITLE
The load suddenly becomes high

### ISSUE THREAD

**Issue by memacs** [emqx/emqx#2855]
#### Environment

- OS: CentOS 7
- Erlang/OTP:  21 erts-10.2.1
- EMQ: emqx-3.1.rc1

#### Description

早上突然集群中的10台机器负载飙到10(8核12G的机器)，这个应该怎么排查呢？

emqx怎么进到remsh里面，执行etop来查看为什么负载高了呢？

还请指导

**Comment by memacs** [comment]
集群上连着25万左右的客户端，但是客户端在线数并没有增长，也没发现其他异常的监控。网络流量也没有增长。

**Comment by turtleDeng** [comment]
Please use English to open issue and provide more log information.

**Comment by xyz361** [comment]
@memacs You can send an E-mail to contact@emqx.io . If you can, you can leave some other contact information in E-mail , such as wechat .
