### ISSUE TITLE
emqx enterprise  protocol'inet_tcp':register/listen error:eaddrinuse

### ISSUE THREAD

**Issue by killer-p** [emqx/emqx#2858]
#### Environment

- OS: centos 7
- Erlang/OTP: 
- EMQ: emqx enterprise

#### Description
我安装了emqx企业版，也按说明书在指定位置放了授权文件，启动emqx后无法连接到服务器，也不知道是具体什么原因，现在就是无法连接到18083和1883

when i send ./emqx console 
it return :protocol'inet_tcp':register/listen error:eaddrinuse
what casue the error

*A description of the issue*

**Comment by HJianBo** [comment]
Hello, @killer-p The `error:eaddrinuse` means that some tcp port has been used. Plz check it;

All used port on https://docs.emqx.io/broker/v3/cn/guide.html

**Comment by turtleDeng** [comment]
Please use English to open issue.
