### ISSUE TITLE
Dashboard displays "URL Not Found"

### ISSUE THREAD

**Issue by CNHanghang** [emqx/emqx#2862]
#### Environment

- OS: Win10
- Erlang/OTP: 
- EMQ: EMQ X Broker

#### Description

进入Dashboard后，有界面，但界面中没有名称版本等信息，而且页面上方显示“URL Not Found”，不清楚哪里有问题。谢谢。
emq服务已经启动，客户端可以与它通信，但web控制界面无信息。
"URL Not Found" is displayed at the top of the web.

**Comment by turtleDeng** [comment]
Please use English to open issue and check if port 8080 is occupied.

**Comment by johnyaozy** [comment]
我遇到相同的情况，EMQ X Broker v4.1.1，原因是emqx_management未启动，原因是端口被占用。修改配置文件etc/plugins/emqx_management.conf  management.listener.http 不冲突则能正常使用。

**Comment by CNHanghang** [comment]
您好。
问题已解决，十分感谢！



在 2020-07-15 11:04:26，"johnyaozy" <notifications@github.com> 写道：

我遇到相同的情况，EMQ X Broker v4.1.1，原因是emqx_management未启动，原因是端口被占用。修改配置文件etc/plugins/emqx_management.conf management.listener.http 不冲突则能正常使用。
