### ISSUE TITLE
EMQX3.2开源版本配置的集群下无法实现多节点消息同步问题

### ISSUE THREAD

**Issue by zy742594821** [emqx/emqx#2864]
#### Environment

- OS: 
- Erlang/OTP: 
- EMQ: 

#### Description

*A description of the issue*
1.使用MQTT.FX给集群节点node1发送消息(主题:testtopic)，使用java客户端连接node2,订阅主题(testtopic)，收不到消息。而集群确实好的。

2.使用Dashboard发送、订阅消息却能收到。

**Comment by turtleDeng** [comment]
Please use English to open issue.
