### ISSUE TITLE
[query] allow only mqtt version 3.1.1 clients

### ISSUE THREAD

**Issue by kiranpradeep** [emqx/emqx#2865]
This is only a query and not a bug.

I like to deny mqtt 3.1 and mqtt 5.0 clients. I tried looking into _emqx.conf_ with no results. As per issue #1930, emqx could return 'unacceptable protocol version'. Is it possible with a configuration option?

**Comment by terry-xiaoyu** [comment]
There's no configurations for that. You can deny the clients by client_id/username in your authentication plugins.

I think add support for checking protocol_name and protocol_version in authentication is a good idea.
