### ISSUE TITLE
emqx as windows service --> stop the service too slow  

### ISSUE THREAD

**Issue by yanghuabin1202** [emqx/emqx#2866]
#### Environment

- OS: Windows 10 Pro
- Erlang/OTP: [erts-10.4][64-bit]
- EMQ: EMQ X Broker 3.2.0

#### Description

I have registered the emqx as a windwos service and started it. When i want to stop it this emqx service, I have must to wait a long time almost 40s  for the emqx service to completely close. 
I want to kown why it so slowly and how can i make it quick!

thinks!

**Comment by turtleDeng** [comment]
Thanks for your feedback, you can try emqx3.2.2 version.

**Comment by renerlemes** [comment]
@yanghuabin1202 I installed it as a service, but when I start the service, it starts correctly, but after a few seconds it stops. Would you help me?

**Comment by yanghuabin1202** [comment]
> @yanghuabin1202 I installed it as a service, but when I start the service, it starts correctly, but after a few seconds it stops. Would you help me?

What version of emqx are you using? you better use newer version of emqx. I also encountered this kind of problem when i use the old emqx. Try the latest version。

**Comment by renerlemes** [comment]
I’m using the 3.2.4 version

**Comment by turtleDeng** [comment]
Sorry, you can try to use emqx4.x version, it is built on windows server 2019 through github actions/

**Comment by yanghuabin1202** [comment]
ok，thanks! I will try it. Now, i try to develop the plugin about emqx,but i never sucess to compile eqmx4.x on windows. Are you convenient to let me add you qq or WeChat friends？I wish I could ask you some questions.

**Comment by HJianBo** [comment]
Hi @yanghuabin1202 you can send me your WeChat id to heeejianbo@gmail.com

BTW, we will release the guide for developing on Window
