### ISSUE TITLE
emqx3.2.2 fail to start

### ISSUE THREAD

**Issue by killer-p** [emqx/emqx#2867]
#### Environment
centos7

- OS: 
- Erlang/OTP: 
- EMQ: 

#### Description
!
![image](https://user-images.githubusercontent.com/54734292/64174383-b68d4b80-ce8b-11e9-9365-e8724e455439.png)

*A description of the issue*

**Comment by zhanghongtong** [comment]
@killer-p Please install openssl above 1.1.1 and try again

**Comment by 52HZWU** [comment]
I also encountered similar problems
![image](https://user-images.githubusercontent.com/53888910/69847468-2e63ea00-12b2-11ea-8ca0-1c2fe5aaecec.png)

**Comment by HJianBo** [comment]
Hi guys, any news to here? Have you started successfully @52HZWU ?
