### ISSUE TITLE
How to statistics error log

### ISSUE THREAD

**Issue by EchoXBR** [emqx/emqx#2871]
## Environment

- OS: CentOS 7.3
- Erlang/OTP: R21/10.3.5.1
- EMQ: 3.2.2

#### Description

There's a lot of conflicting data in 'emqx.log.5'  and 'erlang.log.5'  like this
`2019-09-04 16:45:47.770 [warning] 86375804019311@120.41.170.18:7329 [Channel] Clientid '86375804019311' conflict with <0.20101.348>`
`2019-09-04 16:45:47.772 [warning] 86375804019311 [Session] Connection <0.20101.348> kickout <0.19673.348>`

I want to statistics how many client appear the kickout and how to solve this question
#

**Comment by EchoXBR** [comment]
4.0-alpha.2 version can solve this question?

**Comment by EchoXBR** [comment]
And how can I know which clientid appear the "kickout" action?

**Comment by turtleDeng** [comment]
```
emqx_ctl listeners
```

**Comment by EchoXBR** [comment]
'emqx_ctl listeners' can know conflict's sum,I also want to know which clientID  appear the "kickout" action

**Comment by turtleDeng** [comment]
Sorry, cliteid statistics are not supported.
