### ISSUE TITLE
about management api  "/api/v3/connections" request method type

### ISSUE THREAD

**Issue by coding-cgs** [emqx/emqx#2874]
#### Environment

- OS: centos
- Erlang/OTP: R21/10.3.5.1
- EMQ: 3.2.2

#### Description

*A description of the issue*
"/api/v3/connections"  this api is must be use "GET" method or is can use "POST" method ?

**Comment by HJianBo** [comment]
Afraid not, according to the RESTful specification, the Connections list method should be GET.

And this behavior should not change
