### ISSUE TITLE
Dashboard error : Url Not Found

### ISSUE THREAD

**Issue by cocoaway** [emqx/emqx#2881]
#### Environment

- OS: Linux Ubuntu 19.04
- Erlang/OTP: 22
- EMQ: master / 0.0.0+build.1.ref8a9a461 (emqx v4.0-alpha.2)

#### Description

*A description of the issue*
The dashboard generates errors (URL Not Found) when you access:
- Connections
- Sessions

Unable to view information.
![Url Not Found error](https://user-images.githubusercontent.com/5250613/64474568-e16eec80-d176-11e9-88a9-ea2994af6d31.jpg)

**Comment by turtleDeng** [comment]
Sorry, v4.0-alpha.2 does not support viewing sessions, we will support it in v4.0-beta.1.

**Comment by turtleDeng** [comment]
Thanks for your feedback, we have fixed it in v4.0-beta.1
