### ISSUE TITLE
Clean install Win10 Websocket test not working

### ISSUE THREAD

**Issue by Kortenbach** [emqx/emqx#2882]
#### Environment

- OS: Win 10
- Erlang/OTP: Don't know, used the installer
- EMQ: Don't know, used the installer

#### Description

When I install emqx and I go to the dashboard-->Tools-->Websocket I am not able to connect to the broker. Not with Chrome / FireFox or Edge. Broker IP:127.0.0.1 port:8083

**Comment by turtleDeng** [comment]
Please provide a detailed log.

**Comment by Kortenbach** [comment]
I gave up on EMQ. Using Mosquitto now...
