### ISSUE TITLE
shared subscription performance issue

### ISSUE THREAD

**Issue by shihuc** [emqx/emqx#2883]
#### Environment

- OS: CentOS7.3
- Erlang/OTP: 
- EMQ: V3.0.1

#### Description

Shared supscription performance is not good.

I deployed two EMQX node in cluster mode, server configuration is 4C16G200G, and, 2 application A and 2 appplication B work as comsumer subscibed these two EMQX node. Application A has 4 instances and application B has 2 instances, each instance subscibed these two EMQX node with shared subscription mode.

In the condition as what I do described above, I find that the EMQX server has a high load, memory consuming is to high and the EMQX process is broken and emqx application return with some error log like below:

> 2019-09-07 13:42:56.835 [error] 0ac7462d46fd4b1a931d8a38cfd479f9 ** Generic server <0.3212.0> terminating ^M
** Last message in was {'$gen_cast',^M
                           {subscribe,<0.3209.0>,^M
                               {1,undefined,^M
                                [{<<"/sys/#">>,^M
                                  #{nl => 0,qos => 0,rap => 0,rc => 0,rh => 0,^M
                                    share => <<"dc1">>}}]}}}^M
** When Server state == {state,15000,true,local,^M
                            <<"0ac7462d46fd4b1a931d8a38cfd479f9">>,^M
                            <<"super_admin">>,<0.3209.0>,undefined,1,0,#{},^M
                            false,^M
                            {emqx_inflight,32,{0,nil}},^M
                            20000,undefined,^M
                            {mqueue,true,1000,0,0,none,infinity,^M
                                {queue,[],[],0}},^M
                            #{},100,300000,undefined,0,undefined,true,^M
                            undefined,^M
                            {emqx_gc,^M
                                #{cnt => {1000,1000},^M
                                  oct => {1048576,1048576}}},^M
                            {1567,834970,846112},^M
                            undefined,undefined}^M
** Reason for termination == ^M
** {{timeout,{gen_server,call,^M
                         [emqx_shared_sub,^M
                          {subscribe,<<"dc1">>,<<"/sys/#">>,<0.3212.0>}]}},^M
    [{gen_server,call,2,[{file,"gen_server.erl"},{line,215}]},^M
     {emqx_session,'-handle_cast/2-fun-0-',4,^M
                   [{file,"src/emqx_session.erl"},{line,465}]},^M
     {emqx_session,handle_cast,2,[{file,"src/emqx_session.erl"},{line,454}]},^M
     {gen_server,try_dispatch,4,[{file,"gen_server.erl"},{line,637}]},^M
     {gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,711}]},^M
     {proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,249}]}]}^M
2019-09-07 13:43:01.180 [error] b98c44ec5d3f48ddb8fc379a2c2b2578 ** Generic server <0.3218.0> terminating ^M
** Last message in was {'$gen_cast',^M
                           {subscribe,<0.3216.0>,^M
                               {1,undefined,^M
                                [{<<"/sys/#">>,^M
                                  #{nl => 0,qos => 0,rap => 0,rc => 0,rh => 0,^M
                                    share => <<"dc1">>}}]}}}^M
** When Server state == {state,15000,true,local,^M
                            <<"b98c44ec5d3f48ddb8fc379a2c2b2578">>,^M
                            <<"super_admin">>,<0.3216.0>,undefined,1,0,#{},^M
                            false,^M
                            {emqx_inflight,32,{0,nil}},^M
                            20000,undefined,^M
                            {mqueue,true,1000,0,0,none,infinity,^M
                                {queue,[],[],0}},^M
                            #{},100,300000,undefined,0,undefined,true,^M
                            undefined,^M
                            {emqx_gc,^M
                                #{cnt => {1000,1000},^M
                                  oct => {1048576,1048576}}},^M
                            {1567,834974,987475},^M
                            undefined,undefined}^M
** Reason for termination == ^M
** {{timeout,{gen_server,call,^M
                         [emqx_shared_sub,^M
                          {subscribe,<<"dc1">>,<<"/sys/#">>,<0.3218.0>}]}},^M
    [{gen_server,call,2,[{file,"gen_server.erl"},{line,215}]},^M
     {emqx_session,'-handle_cast/2-fun-0-',4,^M
                   [{file,"src/emqx_session.erl"},{line,465}]},^M
     {emqx_session,handle_cast,2,[{file,"src/emqx_session.erl"},{line,454}]},^M
     {gen_server,try_dispatch,4,[{file,"gen_server.erl"},{line,637}]},^M
     {gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,711}]},^M
{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,249}]}]}^M
===== Sat Sep  7 13:51:32 CST 2019
2019-09-07 13:51:32.391 [error] 0ac7462d46fd4b1a931d8a38cfd479f9@10.95.198.21:59378 [SM] Failed to discard <0.3212.0>: {{timeout,^M
                                     {gen_server,call,^M
                                      [emqx_shared_sub,^M
                                       {subscribe,<<"dc1">>,<<"/sys/#">>,^M
                                        <0.3212.0>}]}},^M
                                    {gen_server,call,^M
                                     [<0.3212.0>,^M
                                      {discard,<0.3222.0>},^M
                                      infinity]}}^M
Lock owner DOWN: <0.3222.0>^M
2019-09-07 13:51:41.069 [error] 0ac7462d46fd4b1a931d8a38cfd479f9@10.95.198.21:59378 Process packet error - einval^M

if we reduce the application instance number, the resouce consumed by EMQX will reduce too. but, in our application, application A and B should support high throughput and high availablibity.

currently, the TPS is near 2W/s.

can you help to give some solution to fix this problem?

**Comment by turtleDeng** [comment]
Sorry, your machine configuration can only support up to W/s TPS.
Please don't subscribe to the /sys/# topic, it will receive all system messages.

**Comment by shihuc** [comment]
> Sorry, your machine configuration can only support up to 2W/s TPS.
> Please don't subscribe to the /sys/# topic, it will receive all system messages.

Hi， 
Will topic /sys/# receive all system mesages? really?  Is this topic same as topic $SYS/#?

And, in my emqx cluster with two emqx node, i find that the load has a big difference between them, one node CPU is 60%, but the other is about 80%, why? the application which subcribed the EMQX node with the same code. (PS: the cluster is setup with manual mode)

**Comment by turtleDeng** [comment]
Sorry, I got it wrong, I thought you were subscribed to $SYS/#.
If the node load is not balanced, you can check if the number of connections is the same.
It is recommended that you upgrade to 3.2.2 to improve cluster message performance.

**Comment by shihuc** [comment]
These days, I test our application performance, I find EMQX always meets these problem.

> 2019-09-11 20:44:38.916 [error] 39346787c9bc4afd990a16a2700995fd@10.95.198.25:40038 [Channel] Shutdown exceptionally due to message_queue_too_long
2019-09-11 20:44:49.827 [warning] [SYSMON] large_heap warning: pid = <0.5103.0>, info: [{old_heap_block_size,6189440},
                                             {heap_block_size,3581853},
                                             {mbuf_size,0},
                                             {stack_size,29},
                                             {old_heap_size,2848687},
                                             {heap_size,1048794}]
[{initial_call,{proc_lib,init_p,5}},
 {current_function,{lists,foldl,3}},
 {registered_name,[]},
 {status,running},
 {message_queue_len,57631},
 {group_leader,<0.2133.0>},
 {priority,normal},
 {trap_exit,true},
 {reductions,1536664490},
 {last_calls,false},
 {catchlevel,2},
 {trace,0},
 {suspending,[]},
 {sequential_trace_token,[]},
 {error_handler,error_handler},
 {memory,83275744},
 {total_heap_size,9775308},
 {heap_size,3581853},
 {stack_size,34},
 {min_heap_size,233}]
2019-09-11 20:44:50.300 [error] 9001547605ec46648b3c485103233946@10.95.198.26:58460 [Channel] Shutdown exceptionally due to message_queue_too_long
2019-09-11 20:44:57.398 [error] b34a92025fbc4c89bbe54ca22e74199f@10.95.198.25:40110 [Channel] Shutdown exceptionally due to message_queue_too_long
2019-09-11 20:44:57.922 [error] a74b0c24136b4c5899dc866fe57d9173@10.95.198.25:40112 [Channel] Shutdown exceptionally due to message_queue_too_long
2019-09-11 20:45:05.640 [error] 4f930fb242734f9ba22ce57c753c482b@10.95.198.26:58442 [Channel] Shutdown exceptionally due to message_queue_too_long
2019-09-11 20:45:30.424 [error] 39346787c9bc4afd990a16a2700995fd@10.95.198.25:40116 [Channel] Shutdown exceptionally due to message_queue_too_long
2019-09-11 20:45:32.180 [error] a74b0c24136b4c5899dc866fe57d9173@10.95.198.25:40126 [Channel] Shutdown exceptionally due to message_queue_too_long
2019-09-11 20:45:32.376 [error] b34a92025fbc4c89bbe54ca22e74199f@10.95.198.25:40128 [Channel] Shutdown exceptionally due to message_queue_too_long
2019-09-11 20:45:51.497 [error] 9001547605ec46648b3c485103233946@10.95.198.26:33234 [Channel] Shutdown exceptionally due to message_queue_too_long

this above log is got based the configuration like this:
device number 60, 200 msg per second, and 6 consumers with share subscription in two servers. the other 2 consumers with share subscription in the other two servers. these two kinds of consumer do different tasks.

And the emqx.conf configuration keeps the default values except below items:
1. allow_annoymous
2. node.name
3. listener.ssl.external.keyfile 
4. listener.ssl.external.certfile
5. listener.ssl.external.cacertfile
6. listener.ssl.external.verify
7. listener.ssl.external.fail_if_no_peer_cert

Can you give me some suggestion to fix the performance about the issue thrown like above log, how to optimize the emqx.conf configuration?
Our two EMQX node with V3.2.2 software, the server memory is very free.
[tkiot@tkiot-emq-broker1 emqx]$ free -h
              total        used        free      shared  buff/cache   available
Mem:            15G        536M         14G         17M        556M         14G
Swap:           15G        150M         15G

Thanks for your help.

**Comment by HJianBo** [comment]
Hi, @shihuc Sorry for the late reply.

The `message_queue_too_long` shutdown error means that a lot of PUBLISH messages are piled up waiting to be sent. 
So, make sure your subscriber up to the sent speed

**Comment by zmstone** [comment]
Hi @hughjfchen 

Could you describe your scenario in a new github discussion https://github.com/emqx/emqx/discussions

This thread was created for v3, the previous discussions are likely not relevant for v5
