### ISSUE TITLE
EMQX3.2.1 throwing back error code 135 Not authorized when reconnecting from client side.

### ISSUE THREAD

**Issue by gsngsngsn** [emqx/emqx#2889]
#### Environment

- OS: 
- Erlang/OTP:  
- EMQ: 3.2.1

#### Description

EMQX throwing back error code 135 Not authorized when reconnecting from client side. 

1. Client (mqttjs) has established connection with EMQX cluster and running fine. 
2. Client goes to silent (device aslepp or whatever) for a while, no pingreq being sent for a while (not sure how long this period should be, anywhere I can configure this? session lifetime maybe?)
3. Client awake and start sending pingreq again.

Problem: 
4. Client didnt get any pingresp from server, so it starts event "close" and "reconnect"
5. Serverside throw back Error 135 Not authorized right away. 

Why am I getting 135 in this case? according to the docs, mqtt should automatically reconnect to the service right?

Other info: 
- Auth: I have enabled http auth that checks username & pw
- System: config, all tuned according to https://docs.emqx.io/broker/v3/en/tune.html
- running a helm created k8s cluster of 5 nodes emqx. 
- CPU & MEM: shouldnt be a problem since right now we have reroute our traffic back to old tunnel and only ~1000 connection running.

**Comment by gsngsngsn** [comment]
any ideas?

**Comment by tigercl** [comment]
Hi, @gsngsngsn.
Sorry for later reply. The server sends `PINGRESP` only if receive `PINGREQ` from client. You'd better set `keepalive` field in your CONNECT packet according to the asleep time of your device. 

MQTT Server return 135 to client because of your HTTP server returns code that is not equal to 200.
