### ISSUE TITLE
ubuntu apt update error

### ISSUE THREAD

**Issue by datafeng** [emqx/emqx#2890]
#### Environment

- OS: ubuntu 18.04
- Erlang/OTP: 
- EMQ: 3.2.2

#### Description

*A description of the issue*

每次升级的时候都是提示这个错误，即使这次处理好了，后面还是会出来。

ln: 无法创建符号链接'/usr/bin/emqx': 文件已存在
dpkg: 处理软件包 emqx (--configure)时出错：
 installed emqx package post-installation script subprocess returned error exit status 1
在处理时有错误发生：
 emqx
E: Sub-process /usr/bin/dpkg returned an error code (1)

**Comment by zhanghongtong** [comment]
Thanks for your feedback, we will fix this issue in the next version

**Comment by turtleDeng** [comment]
Thanks for your feedback, it has been fixed in v4.0-beta.1.

**Comment by datafeng** [comment]
![image](https://raw.githubusercontent.com/datafeng/files/master/emqxupdateerr.png)
很讨厌每次update系统都要处理这个。。
