### ISSUE TITLE
function clause error in emqx_frame:parse_packet

### ISSUE THREAD

**Issue by khodadadi** [emqx/emqx#2891]
#### Environment

- OS: debian 9
- Erlang/OTP: 21
- EMQ: 3.2.0

#### Description
                 [Channel] Parse failed for function_clause

                 Stacktrace:[{emqx_frame,parse_packet,
                                 [{mqtt_packet_header,5,false,0,false},
                                  <<79,88,89,32,84,67,80,52,32,49,57,50,46,49,
                                    54,56,46,48,46,49,51,57,32,49,57,50,46,49,
                                    54,56,46,48,46,50,53,48,32,51,51,50,56,57,
                                    32,56,56,56,51,13,10,16,79,0,4,77,81,84,84,
                                    4,194,0,60,0,24,53,99,48,53,50,54,49,56,97,
                                    55,52,97,100,56,48,52,101,49,55>>,
                                  #{max_size => 524288,version => 4}],
                                 [{file,
                                      "/emqx/_checkouts/emqx/src/emqx_frame.erl"},
                                  {line,147}]},
                             {emqx_frame,parse_frame,4,
                                 [{file,
                                      "/emqx/_checkouts/emqx/src/emqx_frame.erl"},
                                  {line,126}]},
                             {emqx_channel,process_incoming,3,
                                 [{file,
                                      "/emqx/_checkouts/emqx/src/emqx_channel.erl"},
                                  {line,397}]},
                             {gen_statem,call_state_function,5,
                                 [{file,"gen_statem.erl"},{line,1586}]},
                             {gen_statem,loop_event_state_function,6,
                                 [{file,"gen_statem.erl"},{line,967}]},
                             {proc_lib,init_p_do_apply,3,
                                 [{file,"proc_lib.erl"},{line,249}]}]

**Comment by turtleDeng** [comment]
The received packet is not an MQTT packet. Check whether the packet is correct.

**Comment by turtleDeng** [comment]
Thanks for your feedback, we will close this issue.
