### ISSUE TITLE
emqx build for Ubuntu with arm64

### ISSUE THREAD

**Issue by mzy2240** [emqx/emqx#2894]
#### Environment

- OS: Ubuntu
- Erlang/OTP: ?
- EMQ: 3.x

#### Description

*A description of the issue*
Do we have any stable way to build emqx for arm64 in Ubuntu?

**Comment by gilbertwong96** [comment]
OTP 21.3 and EMQ 3.4.0 is recommended.

**Comment by mzy2240** [comment]
Hi Gilbert, thanks for your reply. However, do you have any resources on how to install OTP 21.3? I tried to compile from source but failed.

**Comment by gilbertwong96** [comment]
Maybe this is what you want: https://github.com/kerl/kerl

**Comment by mzy2240** [comment]
Thanks! Though it seems that it is not as simple as it says...
