### ISSUE TITLE
How to convert bin to json

### ISSUE THREAD

**Issue by liu-xinhui** [emqx/emqx#2895]
- OS: linux
- Erlang/OTP: 
- EMQ: 3.1

#### Description
Iot device send bin data,how to convert to json,then send to app

I look up official documents about rule engine,all the examples are JSON,Is there an example of bin?

**Comment by terry-xiaoyu** [comment]
Use the `emqx rule engine` + `emqx schema registry` for this.

**Comment by terry-xiaoyu** [comment]
Checkout this tutorial for schema registry in enterprise emqx: https://docs.emqx.io/tutorial/v3/cn/rule_engine/schema_register.html

**Comment by alexandrim0** [comment]
Hello!

Are you planning to support cbor as well as protobuf?
This binary protocol better for IoT than JSON.
It would be nice!

Thank you!
