### ISSUE TITLE
emqx_auth_mysql certificateless connection _'%C' error

### ISSUE THREAD

**Issue by qkater** [emqx/emqx#2896]
#### Environment

- OS:  win10
- Erlang/OTP:  10.4
- EMQ:    3.2.2

#### Description
启用mysql插件，sql语句中若包含 '%C'，例如：
auth.mysql.auth_query = select password from mqtt_user where username = '%u' and '%C' <> 'any' limit 1

测试：
1.通过【8883】端口带证书连接则正常
2.通过【1883】端口普通连接则会报错，报错如图：
![微信截图_20190912161440](https://user-images.githubusercontent.com/12907377/64766551-be7a7900-d578-11e9-9d79-c7329f84db08.png)

验证：将 '%C' 内容去掉，例如：
auth.mysql.auth_query = select password from mqtt_user where username = '%u' limit 1
则不论通过哪个端口，不论有无证书，都能正常连接。

（auth.mysql.super_query 亦然）

**Comment by HJianBo** [comment]
Hi, @qkater Thanks for your report this.

It has been fixed by https://github.com/emqx/emqx-auth-mysql/pull/172, you will see it at next version

**Comment by qkater** [comment]
@HJianBo 那么请问，现在，当没有证书时，传递给mysql的 %C  是什么值呢？

**Comment by turtleDeng** [comment]
Thanks for your feedback, we have fixed it in v3.2.4.
