### ISSUE TITLE
can not create private namespace using mountpoint

### ISSUE THREAD

**Issue by rajanmodi30** [emqx/emqx#2900]
#### Environment

- OS: Ubuntu 16.04
- Erlang/OTP: 
- EMQ: 3.2.2

#### Description

My etc/emqx.conf:
```
## All the topics will be prefixed with the mountpoint path if this option is enabled.
##
## Variables in mountpoint path:
##  - %c: clientid
##  - %u: username
##
## Value: String
zone.external.mountpoint = %u/
```
I have 2 users, 'test1' and 'test2'. When a client logged in with 'test1' username publishes message "Hello" on topic 'topic1', both 'test1' and 'test2', subscribed to topic 'topic1' receive the message "Hello". I wish to create separate namespaces for users 'test1' and 'test2'. Please guide how I can implement private isolated namespaces in EMQX.

**Comment by turtleDeng** [comment]
Sorry, this is a bug, we have fixed it in 3.2.3, you can compile 3.2.3 via source, or wait for our next 4.0.0release.
