### ISSUE TITLE
Access denied when trying to download v3.2.3

### ISSUE THREAD

**Issue by fuji4** [emqx/emqx#2907]
#### Environment

- OS: Ubuntu 18.04
- Erlang/OTP: 
- EMQ: 3.2.3

#### Description

I wanted to download new version 3.2.3 from https://packages.emqx.io/emqx-ce/v3.2.3/emqx-ubuntu18.04-v3.2.3_amd64.deb, but I always get HTTP 403 Forbidden:

<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>01043C1A9E37527F</RequestId>
<HostId>
uEw9Z4Y0oSZQySQ0y/+fHaQYx2EVI8DVtE7yNu/t2p6PJctaD0yCBdIWoQlDqcTvFE7RPGKfo08=
</HostId>
</Error>

**Comment by drony** [comment]
same for me for latest version
