### ISSUE TITLE
add multiple publish limit

### ISSUE THREAD

**Issue by rajanmodi30** [emqx/emqx#2909]
#### Environment

- OS: ubuntu 16.04
- Erlang/OTP: 
- EMQ: 3.2.3

#### Description

i would like to add multiple publish limit like 10 messages per minute, 100 messages per hour and maybe 1000 messages per month .
so can i add multiple options.
below is the only setting i could find in the emqx.conf file
```
##Publish limit for the external MQTT connections.
##Value: Number,Duration
##Example: 10 messages per minute.
zone.external.publish_limit = 10,1m
```

**Comment by HJianBo** [comment]
Not yet support

The options designed for Publish Rate Limit to implement Flow Control, not a publish quota. So for one connection, it has only one configuration for Publish Limit
