### ISSUE TITLE
Unable to Deny Anonymous Connections

### ISSUE THREAD

**Issue by andrfish** [emqx/emqx#2911]
#### Environment

- OS: Ubuntu 16.04.1 LTS
- Erlang/OTP: R21/10.3
- EMQ: 3.2.2

#### Description

Hello,

I have a broker setup with EMQ X, and wanted to use the emqx_auth_username plugin to allow users only to connect. I have set the

allow_anonymous

flag to false in the etc/emqx.conf file, and have the ACL to deny on failure but it still allows anonymous users to connect. I also verified that the plugin is loaded and I can connect with a username I made using it. Any suggestions or settings to check? Thanks in advance!

**Comment by HJianBo** [comment]
Hi, @andrfish Can you paste the username you made and cmd result by `./bin/emqx_ctl plugins list|grep active=true` ?

**Comment by andrfish** [comment]
> Hi, @andrfish Can you paste the username you made and cmd result by `./bin/emqx_ctl plugins list|grep active=true` ?

Apologies for the late response, the notification got directed to my junk folder for some reason.
The username I'm using is psaasuser and the output of your command there is as follows:
**Plugin(emqx_auth_clientid, version=3.2.2, description=EMQ X Authentication with ClientId/Password, active=true)
Plugin(emqx_auth_username, version=3.2.2, description=EMQ X Authentication with Username and Password, active=true)**
Plugin(emqx_dashboard, version=3.2.2, description=EMQ X Web Dashboard, active=true)
Plugin(emqx_management, version=3.2.2, description=EMQ X Management API and CLI, active=true)
Plugin(emqx_recon, version=3.2.2, description=EMQ X Recon Plugin, active=true)
Plugin(emqx_retainer, version=3.2.2, description=EMQ X Retainer, active=true)
Plugin(emqx_rule_engine, version=3.2.2, description=EMQ X Rule Engine, active=true)

**Comment by andrfish** [comment]
Hello, just a friendly bump in case you had any ideas. We may end up switching to an SSL connection instead if we aren't able to get this to work.

**Comment by andrfish** [comment]
Bump

**Comment by HJianBo** [comment]
Hi @andrfish I'm very sorry for late reply.

Now it seems to be too late, and all the advice has no effect. Apologize to you :(

If you have not resolved it, you can try to update the latest version, e.g: v3.2.7  or v4.0.5
