### ISSUE TITLE
HOW TO UPDATE DATAS INTO MYSQL

### ISSUE THREAD

**Issue by killer-p** [emqx/emqx#2913]
#### Environment

- OS: 
- Erlang/OTP: 
- EMQ: 

#### Description
![image](https://user-images.githubusercontent.com/54734292/65236251-c8692280-db0a-11e9-8cc2-4d68f32e3f3e.png)
SQL模板具体应该怎么写，我试了几种写法都不成功
*A description of the issue*

**Comment by terry-xiaoyu** [comment]
The mysql rule-engine resource/actions are included in the emqx-enterprise.

All questions about enterprise emqx should be handled by the help-desks of emqx enterprise team. Please check out the contact lists from `https://www.emqx.io`. WeChat or QQ is also available.
