### ISSUE TITLE
code optimize

### ISSUE THREAD

**Issue by memacs** [emqx/emqx#2915]
#### Environment

- OS: 
- Erlang/OTP: 
- EMQ: master

#### Description

https://github.com/emqx/emqx/blob/master/src/emqx_metrics.erl#L366-L371 

the
```
                          Idx = reserved_idx(Name),
                          Metric = #metric{name = Name, type = Type, idx = reserved_idx(Name)},
```

maybe can  be changed to

```
                          Idx = reserved_idx(Name),
                          Metric = #metric{name = Name, type = Type, idx = Idx},
```

**Comment by terry-xiaoyu** [comment]
@memacs Thanks. Could you create a pull request to our emqx project (develop branch)?

**Comment by tigercl** [comment]
@memacs Thanks for your feedback again, I have updated the newest code.
