### ISSUE TITLE
Why does emq take up more and more memory and cannot be automatically reclaimed and released

### ISSUE THREAD

**Issue by xuhaohaoxu** [emqx/emqx#2916]
#### Environment

- OS: 
- Erlang/OTP: 
- EMQ: 2.3.11

#### Description

Windows version of emq, during the use of a short period of time, memory will increase, even if all the clients are closed, will slowly increase memory, what is the reason

**Comment by turtleDeng** [comment]
We optimized windows in version 3.2, it is recommended to upgrade to 3.2.X.

**Comment by turtleDeng** [comment]
Thanks for your participation, we will close this issue.
