### ISSUE TITLE
EMQX error

### ISSUE THREAD

**Issue by albinantony2904** [emqx/emqx#2920]
#### Environment

- OS: Ubuntu 18.04
- EMQX: 3.2.0 

#### Description

Faced an issue while installing EMQX in an aws ubuntu server. The following error message occured when i typed emqx_ctl in the ubuntu terminal.

=ERROR REPORT==== 20-Sep-2019::11:19:20.012540 ===
Error when reading /home/ubuntu/.erlang.cookie: eacces
=SUPERVISOR REPORT==== 20-Sep-2019::11:19:20.014699 ===
    supervisor: {local,net_sup}
    errorContext: start_error
    reason: {"Error when reading /home/ubuntu/.erlang.cookie: eacces",
             [{auth,init_cookie,0,[{file,"auth.erl"},{line,286}]},
              {auth,init,1,[{file,"auth.erl"},{line,140}]},
              {gen_server,init_it,2,[{file,"gen_server.erl"},{line,374}]},
              {gen_server,init_it,6,[{file,"gen_server.erl"},{line,342}]},
              {proc_lib,init_p_do_apply,3,
                        [{file,"proc_lib.erl"},{line,249}]}]}
    offender: [{pid,undefined},
               {id,auth},
               {mfargs,{auth,start_link,[]}},
               {restart_type,permanent},
               {shutdown,2000},
               {child_type,worker}]
=CRASH REPORT==== 20-Sep-2019::11:19:20.014596 ===
  crasher:
    initial call: auth:init/1
    pid: <0.81.0>
    registered_name: []
    exception error: "Error when reading /home/ubuntu/.erlang.cookie: eacces"
      in function  auth:init_cookie/0 (auth.erl, line 286)
      in call from auth:init/1 (auth.erl, line 140)
      in call from gen_server:init_it/2 (gen_server.erl, line 374)
      in call from gen_server:init_it/6 (gen_server.erl, line 342)
    ancestors: [net_sup,kernel_sup,<0.46.0>]
    message_queue_len: 0
    messages: []
    links: [<0.79.0>]
    dictionary: []
    trap_exit: true
    status: running
    heap_size: 1598
    stack_size: 27
    reductions: 2295
  neighbours:

escript: exception error: no match of right hand side value 
                 {error,
                     {{shutdown,
                          {failed_to_start_child,auth,
                              {"Error when reading /home/ubuntu/.erlang.cookie: eacces",
                               [{auth,init_cookie,0,
                                    [{file,"auth.erl"},{line,286}]},
                                {auth,init,1,[{file,"auth.erl"},{line,140}]},
                                {gen_server,init_it,2,
                                    [{file,"gen_server.erl"},{line,374}]},
                                {gen_server,init_it,6,
                                    [{file,"gen_server.erl"},{line,342}]},
                                {proc_lib,init_p_do_apply,3,
                                    [{file,"proc_lib.erl"},{line,249}]}]}}},
                      {child,undefined,net_sup_dynamic,
                          {erl_distribution,start_link,
                              [['emqx_maint_10544@127.0.0.1',longnames],
                               false]},
                          permanent,1000,supervisor,
                          [erl_distribution]}}}
  in function  nodetool__escript__1568__978359__808144__2:'-main/1-fun-4-'/1 (/usr/lib/emqx/bin/nodetool, line 23)
  in call from nodetool__escript__1568__978359__808144__2:do_with_ret/3 (/usr/lib/emqx/bin/nodetool, line 142)
  in call from nodetool__escript__1568__978359__808144__2:main/1 (/usr/lib/emqx/bin/nodetool, line 20)
  in call from escript:run/2 (escript.erl, line 758)
  in call from escript:start/1 (escript.erl, line 277)
  in call from init:start_em/1 
  in call from init:do_boot/3

**Comment by turtleDeng** [comment]
No access, please delete this file /home/ubuntu/.erlang.cookie

**Comment by turtleDeng** [comment]
Thank you for your participation, I will close the issue.
