### ISSUE TITLE
Connection Refused when connecting mqqt client with mqqt protcol port 1883 ?

### ISSUE THREAD

**Issue by MuhammadMattiullah** [emqx/emqx#2926]
#### Description
I have lifted the emqx server after following the installation and user guide. Management Console is running on localhost:18083 but mqqt protocol port is not running on 1883 as its a default port of EMQX broker.
i am looking at the running ports using this command(losf -i tcp). Its showing all the default ports running on EMQX except 1883 port which is mqtt protocol port.
Kindly guide me how to lift this mqtt protocol port ?
Thanks

**Comment by turtleDeng** [comment]
1883 is the default port of the MQTT protocol. Please check if other MQTT Brokers are enabled.

**Comment by MuhammadMattiullah** [comment]
Thanks for your response. Much appreciated.
I have checked it twice but port 1883 is not running. No other  brokers are running on this port but still emqx is not lifting this port for mqtt protocol.

**Comment by turtleDeng** [comment]
Sorry to reply to you so late, do you still have problems?

**Comment by turtleDeng** [comment]
Thanks for your participation, we will close this issue, if there is any problem, you can restart to open it.
