### ISSUE TITLE
EMQX on Windows

### ISSUE THREAD

**Issue by ncg81** [emqx/emqx#2927]
The EMQX docs are laden with tips regarding EMQX performance tweaking on Linux (Linux Kernel Parameters, TCP Stack Parameters etc). Any tips for Windows based deployments?

**Comment by turtleDeng** [comment]
Sorry, it is not recommended to deploy the production environment on windows.

**Comment by ncg81** [comment]
Basically anything non Linux/FreeBSD is for dev purposes only... Thank you for the feedback @turtleDeng, it's clear now.
