### ISSUE TITLE
Max concurrent connection less than around 16350? 

### ISSUE THREAD

**Issue by yongchen77** [emqx/emqx#2929]
#### Environment

- OS: Windows 10 / Windows Server 2019/ Ubuntu Server 18.04 
- Erlang/OTP:  R22/10.4
- EMQ: 3.2.1, 3.2.3 stable

#### Description
No matter what operation system or hardware configuration, i can only reach less than around 16350 concurrent connections using default configuation on single node. Is this a limitation, or anything i need to config?

Please help.

**Comment by turtleDeng** [comment]
No restrictions on 16350, please check your test machine program.

**Comment by yongchen77** [comment]
Thanks. This should be a client enviroment problem, I can get higher max connections when running 2 bench tools on 2 computers.
