### ISSUE TITLE
How can i retrieve broker connect, disconnect, publish and subscribe event functions 

### ISSUE THREAD

**Issue by MuhammadMattiullah** [emqx/emqx#2930]
#### Description
I want to use broker event function (connect, disconnect, publish and subscribe) for adding a custom logic into broker. 
Kindly guide me how can i achieve this in emq X broker ?

**Comment by turtleDeng** [comment]
Yes,You can use the hook mechanism to customize your needs,
You can also use the rules engine to configure your business logic.

**Comment by MuhammadMattiullah** [comment]
Thankyou so much for your response. Much appreciated!
Are you talking about webhook plugin ?
also rule engine is not supported for EMQ X broker as per mentioned in their official docs.
Basically i want to add custom logic on the events thats why i am looking for an option.
Like if i wanted to disconnect a client and all such scenario

**Comment by MuhammadMattiullah** [comment]
and thanku very much for quick responses!
Rule engine is supported only for EMQ Enterprise and EMQ Plateform.@turtleDeng

**Comment by turtleDeng** [comment]
Disconnect client can use RESTAPI
The rule engine is also supported by open source, but the enterprise version has more rich actions.
You are welcome to try  EMQ Enterprise or customize it based on EMQX.

**Comment by turtleDeng** [comment]
Thanks for your feedback, we will close it.
