### ISSUE TITLE
Is the <TopicID> returned by the subscription pre-defined or random?

### ISSUE THREAD

**Issue by code-horse** [emqx/emqx#2931]
#### Environment

- OS: Window 7
- EMQ: 3.2.2

#### Description
Is the <TopicID> returned by the subscription pre-defined or random?
test: at+mqttsnreg=101,"topic1"
return: +mqttsnreg: 101,1,3,"topic1"
3 generation rules, please tell me, thank you.

**Comment by turtleDeng** [comment]
Sorry, I don't know your question, please describe the details.

**Comment by code-horse** [comment]
1. Establish a connection
2. Register topicname, at this time the returned topicID is predefined or the server is randomly assigned.
The first registration returns:
At+mqttsnreg=101,"topic1"
+mqttsnreg: 101,1,5,"topic1"
The second registration returns:
At+mqttsnreg=101,"topic2"
+mqttsnreg: 101,1,9,"topic2"
What are the rules for generating 5 and 9?

**Comment by turtleDeng** [comment]
Sorry, we can't understand your question, I will close this issue, welcome to discuss EMQX related issues together.

**Comment by xyz361** [comment]
The topicid does not exist. You can check it out here  https://github.com/hui6075/mqtt_v5/blob/master/mqtt/0309-SUBACK.md .
