### ISSUE TITLE
Api to send message directly to a device with its clientid without publishing a message to any topic

### ISSUE THREAD

**Issue by khoshbin** [emqx/emqx#2932]
#### Environment

- OS:  Centos 7
- Erlang/OTP: 
- EMQ:  3

#### Description

I want to know if there is any api to send message directly to a device with its clientid without publishing a message to any topic?

*A description of the issue*
We need a way to send a message directly from server to a device without needing to create a topic for each device.

**Comment by turtleDeng** [comment]
Sorry, the MQTT protocol is to route messages through topic, so the theme must be used.

**Comment by khoshbin** [comment]
Yes, It is not part of mqtt protocol.But some brokers(like IBM's) have internal api to do this.It is great feature to be added to your EMQ

**Comment by turtleDeng** [comment]
mod_subscription can automatically help clients subscribe to their own unique theme, and you can turn it on and send messages to the client's unique subject.
The documentation is available at https://docs.emqx.io/broker/v3/en/config.html#proxy-subscription-module.

**Comment by khoshbin** [comment]
This is great. it was awesome if there was also a database counterpart too.Then dynamically a subscription could be added or removed according to business rules.

**Comment by turtleDeng** [comment]
EMQX Enterprise Support,You can get it through our official website.https://www.emqx.io/en/downloads

**Comment by turtleDeng** [comment]
Thanks for your feedback, we will close it.
