### ISSUE TITLE
Zombifying the QMQTT client weakens EMQX as a product

### ISSUE THREAD

**Issue by ghost** [emqx/emqx#2933]
Hello EMQX **Product** Team,

Assuming that [qmqtt](https://github.com/emqx/qmqtt) is an official EMQX client (it being hosted under EMQX root github repo, I assume it is), I would like to point out that the decision to zombify the **qmqtt** Qt client as explained [here](https://github.com/emqx/qmqtt/issues/189) and  [here](https://github.com/emqx/qmqtt/issues/188) in favor of Qt's official MQTT client (**QtMqtt**), **weakens EMQX as a product**.

**Please allow me to explain how**:

I am convinced that you are aware of the fact that **QtMqtt** is published under GPLv3, meaning that anyone linking against it **must** embrace Stallman's delusions of reality and GPLv3 their application.

For software applications that either:

a) depend on selling the actual software as opposed to services around the software **or**
b) link against closed source commercial libraries **or**
c) are developed by people who are not willing to have Stallman's delusions forced down their throats

GPLv3 is a clear: **No, I won't touch that with a pole!**. In such cases one can either: 

1) reach down the pocket and pay thousands or tens of thousands of dollars/year for a Qt commercial license just for the privilege of linking against **QtMqtt** (not really worth it, isn't it ?)
2) hack one's way around the issue by incorporating some 3rd party C++ MQTT client which have as a general rule limited feature and cross platform support (on top of bugs that is :-) ) **or**
3) dump the entire MQTT stack and find another non-MQTT based approach

There are other options, but none of them robust nor elegant and I choose to omit them for brevity.

Points **1)** and **3)** above are relevant to the issue at hand:

- Choosing option **1)** reduces the odds that one would pay for EMQX Enterprise. Not optimal for EMQX as a product. **Wouldn't you prefer to maximize the odds** that people actually **pay you** instead of some other company?

- Choosing option **3)** reduces the odds that one would pay for EMQX Enterprise to as close to 0 (zero) as allowed by the known laws of mathematics.

In closing, I would like to mention that the Development Team's decision to place the **qmqtt** client in maintenance mode **is correct in it's own domain**. After all, there is already a Qt client, developed and maintained by Qt themselves so why not freeing some dev resources and focus on other things. The points made above offer a possible answer to the "**why not?**" question. 

Regards.

**Comment by zmstone** [comment]
replying to ghost: thank you for the advice
