### ISSUE TITLE
emqx bench run sub pub as same time can server max clients num

### ISSUE THREAD

**Issue by googlefan** [emqx/emqx#2934]
#### Environment

- OS: centos  8c16G
- Erlang/OTP: 22
- EMQ: 3.2.3

#### Description

*I used emqx_bench to test emqx's profile, I run pub and sub as a same time.The sub clients was set 300, and the server's cpu was very high, and drop down a few minutes later.  I want to know how many clients can emqx server as a same time?*

command
emqtt_bench sub  -c 300 -t topic -q 1
emqtt_bench pub  -c 3000 -I 10000 -t topic -s 256 -q 1

**Comment by turtleDeng** [comment]
300 subscribers subscribe to the same topic, 3000 publishers send a message 10 seconds, which is equivalent to TPS is 90K/S
Your host configuration, QOS1 scene can support 40K/S TPS, please adjust your test scenario.

**Comment by googlefan** [comment]
thank you .And how many TPS can QOS0 /QOS2 support ?

**Comment by turtleDeng** [comment]
Probably in
QOS0 60K/S TPS
QOS2 10K/S TPS
