### ISSUE TITLE
Disconnecting unknown client from broker but it keeps on reconnecting

### ISSUE THREAD

**Issue by MuhammadMattiullah** [emqx/emqx#2935]
I am disconnecting / kicking out an unknown client from the connection cluster using the API (DELETE api/v3/connections/${clientid}).
When i disconnect the specific client using the above API. It disconnect a client from cluster and then again the client reconnects from the broker.
Please guide me how can i stop this reconnecting behavior of client ?

**Comment by turtleDeng** [comment]
Please add an Environment when you mention the issue.
#### Environment

- OS: 
- Erlang/OTP: 
- EMQ: 

#### Description

The client has a reconnection mechanism, you can bannedA API.
For more usage, please see https://docs.emqx.io/broker/v3/en/rest.html#list-all-ban-records-in-the-cluster
