### ISSUE TITLE
ACL wildcard subscribe

### ISSUE THREAD

**Issue by enzokwai** [emqx/emqx#2936]
#### Environment

- OS: Ubuntu 18.04 
- Erlang/OTP: 
- EMQ: 3.2.3

#### Description

I am new to EMQ and was using mosquitto.

When i was using mosquitto i am able to use ACL to limit user to subscribe certain topic but still can subscribe # topic.

e.g. 

user1
topic read user1/#

user1 still able to subscribe # but only able to get user1/# topic

but in emqx i need to explicitly subscribe to user/# but not #

Am i able to config emqx to behave the same way as mosquitto do?

**Comment by turtleDeng** [comment]
Of course, please see the documentation https://docs.emqx.io/broker/v3/en/guide.html#authentication-and-access-control

**Comment by enzokwai** [comment]
Thanks for your reply.

I have read the document and try to config but not success

I have add follow in my acl
{allow, {user, "user1"}, subscribe, ["user1/#"]}.

but in my client i only can subscribe to user1/# but not #

**Comment by turtleDeng** [comment]
```
%%--------------------------------------------------------------------
%%
%% [ACL](http://emqtt.io/docs/v2/config.html#allow-anonymous-and-acl-file)
%%
%% -type who() :: all | binary() |
%%                {ipaddr, esockd_access:cidr()} |
%%                {client, binary()} |
%%                {user, binary()}.
%%
%% -type access() :: subscribe | publish | pubsub.
%%
%% -type topic() :: binary().
%%
%% -type rule() :: {allow, all} |
%%                 {allow, who(), access(), list(topic())} |
%%                 {deny, all} |
%%                 {deny, who(), access(), list(topic())}.
%%
%%--------------------------------------------------------------------
{allow, {user, "dashboard"}, subscribe, ["$SYS/#"]}.
{allow, {ipaddr, "127.0.0.1"}, pubsub, ["$SYS/#", "#"]}.
{deny, all, subscribe, ["$SYS/#", {eq, "#"}]}.
{allow, all}.
```

Default ACL rule, forbidden subscription#
```
{deny, all, subscribe, ["$SYS/#", {eq, "#"}]}.
```

**Comment by enzokwai** [comment]
But if i remove that line, i am really getting all topic rather than the sub-tree assign to that account

**Comment by turtleDeng** [comment]
```
%%--------------------------------------------------------------------
%%
%% [ACL](http://emqtt.io/docs/v2/config.html#allow-anonymous-and-acl-file)
%%
%% -type who() :: all | binary() |
%%                {ipaddr, esockd_access:cidr()} |
%%                {client, binary()} |
%%                {user, binary()}.
%%
%% -type access() :: subscribe | publish | pubsub.
%%
%% -type topic() :: binary().
%%
%% -type rule() :: {allow, all} |
%%                 {allow, who(), access(), list(topic())} |
%%                 {deny, all} |
%%                 {deny, who(), access(), list(topic())}.
%%
%%--------------------------------------------------------------------
{allow, {user, "user1"}, subscribe, ["#"]}.
{allow, {user, "dashboard"}, subscribe, ["$SYS/#"]}.
{allow, {ipaddr, "127.0.0.1"}, pubsub, ["$SYS/#", "#"]}.
{deny, all, subscribe, ["$SYS/#", {eq, "#"}]}.
{allow, all}.
```

**Comment by enzokwai** [comment]
Thanks for your reply.

Your example really grant every topic "#" to user1

What i was doing in mosquitto is when i only grant a sub-topic (e.g. "user1/#") to user1, then such client can still subscribe to all topic ("#"), the broker just filter topic within user1/# to the client
