### ISSUE TITLE
Disable nagle algorithm

### ISSUE THREAD

**Issue by pantxisto** [emqx/emqx#2938]
#### Environment

- OS: Windows 10
- Erlang/OTP: 
- EMQ: 3.2.3

#### Description

Hello,

I´m trying to disable nagle algorithm because I need to send a lot of small packets instantaneally. I try to set this configurations to true withouth success:
listener.tcp.external.nodelay = true
listener.tcp.internal.nodelay = true
listener.ssl.external.nodelay = true
listener.ws.external.nodelay = true
listener.wss.external.nodelay = true

Am I doing something wrong or I need to change another configuration?

Thank You.

**Comment by terry-xiaoyu** [comment]
@pantxisto 
Hi. How do you verify if the Aagle algorithm is disabled or not? The TCP will sent the small packets if you set those configs.
