### ISSUE TITLE
emq server take more and more cpu load

### ISSUE THREAD

**Issue by u-tec-com** [emqx/emqx#2940]
#### Environment

- OS: ubuntu 18.04
- Erlang/OTP: R20/9.0
- EMQ: 2.3.9

#### Description
run emq server over 2 weeks with about 7k devices online.
the cpu load keep increasing. from 10% to 40%.
the device client is not changed and the network package almost the same.

**Comment by turtleDeng** [comment]
Sorry, we are no longer updated 2.3.9, I suggest you upgrade to v3.2.3

**Comment by u-tec-com** [comment]
thanks turtle.

Is anyone else has the similar issue? and the new version fixed this issue?

**Comment by turtleDeng** [comment]
We have done a lot of CPU and memory optimization in the 3.x version, I hope I can help you.

**Comment by 907474646** [comment]
I also found it in v2.3.11 ,may be the bug is in emqttd_sm module,when a client was kicked out  ,but the last session data in dict was not released. I try to resolved these problems,

**Comment by turtleDeng** [comment]
Thanks for your participation, we will close this issue.
