### ISSUE TITLE
EMQX throwing error when MQTT SSL enabled

### ISSUE THREAD

**Issue by fair18** [emqx/emqx#2941]
#### Environment

- OS: Kubernetes
- EMQ: 3.2.3

#### Description

I deployed EMQ on Kubernetes cluster and it seems everything works fine without SSL, but when I enable SSL the broker starts throwing an exception with the error and continue working. Ingress is nginx controller. I have also tested with version 3.0.1 and haven't seen any error with SSL. 

#################ERROR
2019-09-26 18:04:07.262 [error] crasher:
    initial call: emqx_channel:init/1
    pid: <0.2217.0>
    registered_name: []
    exception error: no match of right hand side value {error,closed}
      in function  emqx_channel:init/1 (/emqx_rel/_checkouts/emqx/src/emqx_channel.erl, line 152)
    ancestors: [<0.1793.0>,<0.1792.0>,esockd_sup,<0.1354.0>]
    message_queue_len: 0
    messages: []
    links: [<0.1793.0>]
    dictionary: []
    trap_exit: true
    status: running
    heap_size: 4185
    stack_size: 27
    reductions: 5112
  neighbours:
2019-09-26 18:04:07.263 [error] supervisor: 'esockd_connection_sup - <0.1793.0>'
    errorContext: connection_crashed
    reason: {{badmatch,{error,closed}},
             [{emqx_channel,init,1,
                            [{file,"/emqx_rel/_checkouts/emqx/src/emqx_channel.erl"},
                             {line,152}]},
              {proc_lib,init_p_do_apply,3,
                        [{file,"proc_lib.erl"},{line,249}]}]}
    offender: [{pid,<0.2217.0>},
               {name,connection},
               {mfargs,{emqx_channel,start_link,
                                     [[{deflate_options,[]},
                                       {max_conn_rate,500},
                                       {active_n,100},
                                       {zone,external}]]}}]

**Comment by mciocan** [comment]
I have the same kind of errors. Same setup: LetsEncrypt, kubernetes, emx@v3.2.3, nginx ingress controller(tcp). 
`
2019-09-30 12:55:21.146 [error] crasher:
    initial call: emqx_channel:init/1
    pid: <0.12069.0>
    registered_name: []
    exception error: no match of right hand side value {error,closed}
      in function  emqx_channel:init/1 (/emqx_rel/_checkouts/emqx/src/emqx_channel.erl, line 152)
    ancestors: [<0.1853.0>,<0.1852.0>,esockd_sup,<0.1354.0>]
    message_queue_len: 0
    messages: []
    links: [<0.1853.0>]
    dictionary: []
    trap_exit: true
    status: running
    heap_size: 2586
    stack_size: 27
    reductions: 5180
  neighbours:`

**Comment by mciocan** [comment]
Tested also with v3.2.3, v3.2.2, v3.2.1, v3.2.0, v3.1.2, v3.1.0 and the error is the same.
Only with v3.0.1 is ok.

**Comment by csbzy** [comment]
same issue at v3.2.3, any update?

**Comment by turtleDeng** [comment]
The problem has been fixed and will be in v4.0-beta.2 version
https://github.com/emqx/emqx/pull/2963
