### ISSUE TITLE
Issue with Banned Api. Getting success response from Banned APi but still banned list count is 0

### ISSUE THREAD

**Issue by MuhammadMattiullah** [emqx/emqx#2943]
#### Environment

- OS: Ubuntu 18.04
- EMQX: 3.2.1

#### Description

Hello Team, I am facing an issue when using Banned Api. I have scenario that if some unknown client trying to connect EMQ X broker then i want to block that client so it won't be reconnecting again. 
I am using the Banned Api for this purpose like below:

**POST**  http://localhost:8080/api/v3/banned/
**Request body:**
{
    "who": "mqttjs_ab9069449e",
    "as": "client_id",
    "reason": "banned the clientId",
    "desc": "normal banned",
    "until": 1536146187
}

Getting 200 status with Ok response and when i list the banned clients using Get Api (http://localhost:8080/api/v3/banned/) but its showing the count 0 and not banning the client as the same client again publish the data into the broker.
Please guide me that how can i implement the banned Api according to my scenario

**Comment by terry-xiaoyu** [comment]
@MuhammadMattiullah Hi, have you tried to set the `until` to a timestamp that much later than the current time? The API would ban the client_id until the timestamp you gave.
