### ISSUE TITLE
$local subscription not working when migrated from v2.3.7 to v3.2.3

### ISSUE THREAD

**Issue by abejoe** [emqx/emqx#2944]
#### Environment

- OS: alpine:3.7(docker image)
- Erlang/OTP: 22  
- EMQ: v3.2.3

#### Description
I recently migrated from v2.3.7 to v3.2.3
In my previous version(v2.3.7), the topics subscribed were like `$local/$share/group/<topic_name>` and `$local/$share/group/<topic_name>/#`

Now I updated it to v3.2.3 and now when i subscribe, the subscriptions are shown in dashboard and messages are received by the broker but not sent. Messages are published to `<topic_name>` and `<topic_name>/<subtopics>`. When i subscribe using the pattern `$share/group/<topic_name>` or` $share/<topic_name>`, then its is sent to the subscriber. 
It is not being sent only when i use the prefix `$local`

Kindly provide an explanation/solution for this behaviour or let me know if u need any extra information regarding this.

**Comment by turtleDeng** [comment]
3.x version no longer supports $local subscriptions，And support cluster shared subscriptions.

**Comment by turtleDeng** [comment]
Thanks for your feedback, we will close this issue.
