### ISSUE TITLE
using Mosquitto Auth database for emqx

### ISSUE THREAD

**Issue by nika-chkhikvishvili** [emqx/emqx#2945]
#### Environment

- OS: 
- Erlang/OTP: 
- EMQ: 

#### Description

We are using Mosquitto broker for our clients , we decided to swap it with emqx.
can we use mosquito sql auth data for emqx sql authentication.

**Comment by turtleDeng** [comment]
Sorry, I can't understand your mosquito sql, our EMQX has a powerful authentication plugin, you can check it in detail https://docs.emqx.io/broker/v3/en/guide.html#authentication-and-access-control

**Comment by turtleDeng** [comment]
Thanks for your feedback, we will close this issue.
