### ISSUE TITLE
Getting a "Not found"  in the connections REST API, not working

### ISSUE THREAD

**Issue by rajanmodi30** [emqx/emqx#2948]
#### Environment

- OS: ubuntu 16.04
- Erlang/OTP: 
- EMQ: 3.2.3

#### Description

We have connected 3 clients, it is showing 3 "connections count" in EMQX dashboard and also showing in the list of clients in EMQX dashboard. Getting a "Not found"  in the below REST API:

```
GET api/v3/emqx@127.0.0.1/subscriptions
GET api/v3/connections
```
Also, there is no REST API to list clients in a node?

**Comment by turtleDeng** [comment]
Sorry, does not support 
```
GET api/v3/connections
```
Please use 
```
GET api/v3/nodes/${node}/connections
```

**Comment by rajanmodi30** [comment]
getting the same "Not found" with:
```
GET api/v3/nodes/${node}/connections
GET api/v3/nodes/emqx@127.0.0.1/connections
```

**Comment by turtleDeng** [comment]
![conn](https://user-images.githubusercontent.com/1830077/66634498-c85acf00-ec3f-11e9-8774-f53dae424f89.jpg)

**Comment by turtleDeng** [comment]
Check if your 8080 port and emqx_management plugin are enabled.

**Comment by turtleDeng** [comment]
Thanks for your feedback, we will close this issue.
