### ISSUE TITLE
Does emqx support the latest version of raspberry PI? Raspbian GNU/Linux 10 (buster)

### ISSUE THREAD

**Issue by 547176052** [emqx/emqx#2953]
pi@raspberrypi:~ $ cat /etc/os-release
PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"
NAME="Raspbian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"

**Comment by zhanghongtong** [comment]
@547176052 Thanks for your feedback, we plan to support Raspbian10 in the next version.

**Comment by tigercl** [comment]
@547176052 We have supported it, you can get it on [edge](https://www.emqx.io/downloads#edge).
