### ISSUE TITLE
When the data is persisted to mysql by rules, the failure occurs after a period of time.

### ISSUE THREAD

**Issue by wxgaidj** [emqx/emqx#2955]
#### Environment

- OS: linux centos 7
- Erlang/OTP:  
- EMQ:   3.2.2

#### Description
使用企业版，通过规则获取数据持久化到mysql时，一段时间后出现失败得情况
重启MQTT恢复正常。

`2019-10-03 23:42:18.073 [error] 8360000000123431@10.252.100.100:34322 Apply rule rule:c410b9db failed: {take_action_failed,
                                  {<<"data_to_mysql_1569408006644474747">>,
                                   {noproc,
                                    {gen_statem,call,
                                     [<0.25650.1>,
                                      {try_batch,
                                       {data_to_mysql_1569408006644474747,
                                        [<<"8360000000123431">>,
                                         <<"8360000000123431,1570117055,26.5,26.5,26.5,56,55,55,23">>]},
                                       #Fun<emqx_backend_mysql_actions.17.119727872>},
                                      infinity]}},
                                   [{gen,do_call,4,
                                     [{file,"gen.erl"},{line,177}]},
                                    {gen_statem,call_dirty,4,
                                     [{file,"gen_statem.erl"},{line,592}]},
                                    {emqx_backend_mysql_actions,
                                     '-on_action_create_data_to_mysql/2-fun-2-',
                                     5,
                                     [{file,
                                       "/emqx_temp/emqx_enterprise_rel/_checkouts/emqx_backend_mysql/src/emqx_backend_mysql_actions.erl"},
                                      {line,241}]},
                                    {emqx_rule_runtime,take_action,3,
                                     [{file,
                                       "/emqx_temp/emqx_enterprise_rel/_checkouts/emqx_rule_engine/src/emqx_rule_runtime.erl"},
                                      {line,228}]},
                                    {lists,map,2,
                                     [{file,"lists.erl"},{line,1239}]},
                                    {emqx_rule_runtime,apply_rule,2,
                                     [{file,
                                       "/emqx_temp/emqx_enterprise_rel/_checkouts/emqx_rule_engine/src/emqx_rule_runtime.erl"},
                                      {line,154}]},
                                    {emqx_rule_runtime,apply_rules,2,
                                     [{file,
                                       "/emqx_temp/emqx_enterprise_rel/_checkouts/emqx_rule_engine/src/emqx_rule_runtime.erl"},
                                      {line,132}]},
                                    {emqx_rule_runtime,on_message_publish,2,
                                     [{file,
                                       "/emqx_temp/emqx_enterprise_rel/_checkouts/emqx_rule_engine/src/emqx_rule_runtime.erl"},
                                      {line,90}]}]}}. Statcktrace:
[{emqx_rule_runtime,take_action,3,
                    [{file,"/emqx_temp/emqx_enterprise_rel/_checkouts/emqx_rule_engine/src/emqx_rule_runtime.erl"},
                     {line,234}]},
 {lists,map,2,[{file,"lists.erl"},{line,1239}]},
 {emqx_rule_runtime,apply_rule,2,
                    [{file,"/emqx_temp/emqx_enterprise_rel/_checkouts/emqx_rule_engine/src/emqx_rule_runtime.erl"},
                     {line,154}]},
 {emqx_rule_runtime,apply_rules,2,
                    [{file,"/emqx_temp/emqx_enterprise_rel/_checkouts/emqx_rule_engine/src/emqx_rule_runtime.erl"},
                     {line,132}]},
 {emqx_rule_runtime,on_message_publish,2,
                    [{file,"/emqx_temp/emqx_enterprise_rel/_checkouts/emqx_rule_engine/src/emqx_rule_runtime.erl"},
                     {line,90}]},
 {emqx_hooks,do_run_fold,3,
             [{file,"/emqx_temp/emqx_enterprise_rel/_checkouts/emqx/src/emqx_hooks.erl"},
              {line,131}]},
 {emqx_broker,publish,1,
              [{file,"/emqx_temp/emqx_enterprise_rel/_checkouts/emqx/src/emqx_broker.erl"},
               {line,198}]},
 {emqx_session,publish,3,
               [{file,"/emqx_temp/emqx_enterprise_rel/_checkouts/emqx/src/emqx_session.erl"},
                {line,267}]}]`

**Comment by turtleDeng** [comment]
Thanks for your feedback, already fixed in v3.4.0.
