### ISSUE TITLE
eheap_alloc Crash dump

### ISSUE THREAD

**Issue by Zhang-Xianglong** [emqx/emqx#2956]
#### Environment

- OS: 
- Erlang/OTP: 
- EMQ: 

#### Description

#2190

**Comment by turtleDeng** [comment]
Sorry, we can't analyze the problem from the information you gave. We recommend that you use the latest version.

**Comment by Zhang-Xianglong** [comment]
@turtleDeng Sorry for bothering. Log size 4-5G(https://pan.baidu.com/s/18KAButdIlaJEPMpi14zXcQ 
    passwd:7r1e), this problem has already appeared for the second time, can you give me some guidance, memory leak caused by configuration error or some other possible reasons?
And is there a tool to analyze the crash log?
If you recommend me to use the new version, does it mean that version 2.X.X is no longer maintained, and which version you recommend is stable for production.

**Comment by turtleDeng** [comment]
Yes, the 2.X version is no longer updated
It is recommended to use version V3.2.3 or use the enterprise version.

**Comment by Zhang-Xianglong** [comment]
@turtleDeng Thanks. And is there a tool to analyze the crash log?

**Comment by turtleDeng** [comment]
http://erlang.org/doc/apps/observer/crashdump_ug.html

**Comment by turtleDeng** [comment]
Thanks for your feedback, we will close this issue.
