### ISSUE TITLE
Ask a question about a pub and sub relationship

### ISSUE THREAD

**Issue by sdvdxl** [emqx/emqx#2958]
咨询一个pub和sub关系的问题。

pub 受 sub 接收速度的影响么？

另外，如果qos是2的时候， pub 的 pubrel等确认信息是什么时候发送到pub client的，是先把消息发给sub client，确认之后再发给 pub client的，还是收到就交互确认信息，确认结束后再发给 sub client？ 这个是跟broker 的实现有关，还是怎么规范的

谢谢

**Comment by turtleDeng** [comment]
https://docs.emqx.io/broker/v3/cn/protocol.html#qos2

**Comment by sdvdxl** [comment]
这个意思是，qos2 的情况下，如果客户端pubrel没有发送（恰好断网了），那么sub 客户端是不会收到消息的么？

**Comment by turtleDeng** [comment]
The EMQ X 2.X version is released according to the above figure.
The EMQ X 3.X and above, after receiving the publish, send it directly to the subscriber.

**Comment by sdvdxl** [comment]
> The EMQ X 2.X version is released according to the above figure.
The EMQ X 3.X and above, after receiving the publish, send it directly to the subscriber.

> qos2 的情况下，如果客户端pubrel没有发送（恰好断网了）

这样的话，2.x 的话，sub 客户端收不到消息，3.x sub 客户端可以收到，是这样吧？

**Comment by turtleDeng** [comment]
yes

**Comment by turtleDeng** [comment]
Thanks for your feedback, we will close this issue.
