### ISSUE TITLE
What is the strategy about ACL cache?

### ISSUE THREAD

**Issue by shihuc** [emqx/emqx#2961]
#### Environment

- OS: CentOS
- Erlang/OTP: 
- EMQ: V3.2.3

#### Description

In my load test environment, the acl is based on mysql, but I find that the mysql is very busy.
I find the root cause is from ACL query. This is not nice to all my subsystem of my application.

my question about this are:
1) can I configure the acl cache to be alive all the time, not dead.???
2) is there some API to clear the cache when I want to clear the unused ACL data from the EMQ memory.???

Thanks!

**Comment by terry-xiaoyu** [comment]
The ACL result is cached per clients, and it will be cleaned if one of the following conditions is met:

1. No publish/subscribe message is received from the client in the seconds configured by `acl_cache_ttl` in the emqx.conf

2. The client disconnected.

There's no API for clearing all the cache entries for clients but it is planned. I am not sure if it will be implemented in the next minor/patch version update.
