### ISSUE TITLE
Unable to use IPv6 on emqx

### ISSUE THREAD

**Issue by zacsonskaria** [emqx/emqx#2962]
#### Environment

- OS: Amazon Linux 2
- Erlang/OTP: R21/10.2 
- EMQ: v3.0.0

#### Description

I am trying to use IPv6 on emqx with the below configuration, however it does not seems to work (unable to connect using IPv6 address). My goal is to have IPv4 and IPv6 available on the same broker. 
Also while using emq@::1 as the node.name, the login in the dashboard fails.

node.name = emq@::1
node.proto_dist = inet6_tcp
listener.tcp.external= 1883

**Comment by zacsonskaria** [comment]
I have tried multiple options, but none of them worked so far. IPv6 never worked for me.
Configuration I have tried are as below.
**Combination 1**
node.name = emq@::1
node.proto_dist = inet6_tcp
listener.tcp.external= ::1:1883
listener.tcp.external.reuseaddr = true
listener.ws.external = ::1:8083
**Combination 2**
node.name = emq@::1
node.proto_dist = inet6_tcp
listener.tcp.external= 127.0.0.1:1883
listener.tcp.external.reuseaddr = true
listener.ws.external = 127.0.0.1:8083

**Comment by tigercl** [comment]
Hi, @zacsonskaria.
IPv6 has been supported in [emqx v3.2.4](https://www.emqx.io/cn/downloads#broker).

**Comment by zacsonskaria** [comment]
> Hi, @zacsonskaria.
> IPv6 has been supported in [emqx v3.2.4](https://www.emqx.io/cn/downloads#broker).

I hope IPv6 was already supported in emqx 3.0.0. I am trying to connect devices to the emqx server using IPv6 address.
