### ISSUE TITLE
CoAP Subscribe Error

### ISSUE THREAD

**Issue by TomazCebekAstron** [emqx/emqx#2966]
#### Environment

- OS:  Embeded/Windows/Linux
- Erlang/OTP:  ?
- EMQ:  EMQX 3.1 community edition

#### Description
With any CoAP client I can publish...

When we subsribe with any CoAP client to the Broker (any topic). The server closes the connection to the client... No matter how many times I tried it always happens...

It must be a problem of the CoAP plugin.

**Comment by TomazCebekAstron** [comment]
It worked normaly on the EMQTT 2.3...

**Comment by TomazCebekAstron** [comment]
Will try to update the broker to the beta version and see if it works...

**Comment by TomazCebekAstron** [comment]
With the beta version it seems to be working now.

**Comment by terry-xiaoyu** [comment]
@TomazCebekAstron Have you tried the 3.2.3 (the latest version of the 3.2.x for now) ? The 3.1 is too long for us to support and any bug fixes would go into 3.2.x.

**Comment by HJianBo** [comment]
Hi @TomazCebekAstron We have released the `v4.1.1` and fix some unstable problems for `emqx-coap` plugin. Plz try it if you interested
