### ISSUE TITLE
share subscription has bug when load is high

### ISSUE THREAD

**Issue by shihuc** [emqx/emqx#2967]
#### Environment

- OS: CentOS
- Erlang/OTP: 
- EMQ: V3.2.3

#### Description

We have two EMQX node (4C16G100G) in cluster mode, and 6 consumer application for load balance to consume the message in share subscription style.

I find when devices are not so huge, the message can be subscribed normally, but when device number are too many (20000+), the consumer application will lose message, can not subscribe all the message sent by client producer.

PS:
In our application, one topic will be subscibed 12 times (6 application subscribe the topic on each EMQX node, so ,there are 12 times)

What is wrong? is there some restrication in share subscription?

**Comment by turtleDeng** [comment]
Sorry, please describe it clearly.
TPS to publish messages, subscribed topics, and how many client subscriptions

**Comment by shihuc** [comment]
> Sorry, please describe it clearly.
> TPS to publish messages, subscribed topics, and how many client subscriptions

TPS is 4000,
topic number is 20000 totally, one for each device
there 16 client subscriptions (4 in application A, 12 in application B, both A and B use share subscription in two group)

PS:
After I restart the emqx cluster, the problem disappear..., but, before i restart emqx cluster, only restart application B, the lose message problem is still there.
