### ISSUE TITLE
Message posting problem

### ISSUE THREAD

**Issue by promission** [emqx/emqx#2968]
#### Environment

- OS: CentOS 6/7
- Erlang/OTP: 20
- EMQ: 2.2

#### Description

The client and the broker are connected normally, and the subscribed topic has been receiving messages normally. However, the message is published using the paho client (the connection state of the client is intentionally printed before the release: ["msg": "Get the connection status to the client: true"]), and suddenly there is a problem that the release cannot be made. This problem has happened twice.
What could be caused by this, please ask for help, thank you.
I think it should have nothing to do with the configuration of mqtt.pubsub.pool_size.

**Comment by turtleDeng** [comment]
Sorry, I can't understand what you mean. If the message can't be sent, please provide the LOG file.

**Comment by promission** [comment]
> Sorry, I can't understand what you mean. If the message can't be sent, please provide the LOG file.


Emqttd/log xiàmiàn de error.Log hé erlang.Log dōu méiyǒu fāxiàn xiāoxī fābù de yìcháng rìzhì. Dànshì kèhù duān yǔ broker de liánjiē shì zhèngcháng,broker shōu bù dào kèhù duān fāsòng de xiāoxī (hòutái yèmiàn zhōng,RecvMsg zhèlǐ de shùliàng yīzhí bù biànle, nándào shì kèhù duāndì liánjiē jiǎsǐle ma, dànshì kěyǐ zhèngcháng jiēshōu dào xiāoxī.)
展开
136/5000
The error log and erlang.log under emqttd/log did not find the exception log of the message. However, the connection between the client and the broker is normal, and the broker cannot receive the message sent by the client. (In the background page, the number of RecvMsg here has not changed. Is the connection of the client suspended, but the message can be received normally.)

**Comment by promission** [comment]
> Sorry, I can't understand what you mean. If the message can't be sent, please provide the LOG file.

The error log and erlang.log under emqttd/log did not find the exception log of the message. However, the connection between the client and the broker is normal, and the broker cannot receive the message sent by the client. (In the background page, the number of RecvMsg here has not changed. Is the connection of the client suspended, but the message can be received normally.)

**Comment by promission** [comment]
> Sorry, I can't understand what you mean. If the message can't be sent, please provide the LOG file.

I tracked this client and found only "SEND PUBLISH(Q1, R0, D1", no "RECV"。
![1](https://user-images.githubusercontent.com/20593197/66796262-ba57c780-ef39-11e9-9234-69e3e5c5a136.png)

**Comment by turtleDeng** [comment]
Consumer news has blocked, please check your consumer processing power.
