### ISSUE TITLE
Question of re-connecting after disconnect with bridge

### ISSUE THREAD

**Issue by eggb4by** [emqx/emqx#2969]
#### Environment

- OS: Centos
- Erlang/OTP: 
- EMQ: 3.2.3

#### Description
我在虚拟机里搭了两个emqx
192.168.114.158 edge
192.168,114.159 master

edge bridge到master
{client1}---pub--->[edge]---bridge--->[master]---sub--->{client2}消息是通的
然后我把master网络关掉，过段时间重新打开
client1再发消息，发现client2那边就收不到了，需要重新sub一下master才可以

这个是什么原因，求教

**Comment by gilbertwong96** [comment]
```config
## Start type of the bridge.
##
## Value: enum
## manual
## auto
bridge.mqtt.aws.start_type = manual
```

Which start type you chose ?

**Comment by eggb4by** [comment]
> ```
> ## Start type of the bridge.
> ##
> ## Value: enum
> ## manual
> ## auto
> bridge.mqtt.aws.start_type = manual
> ```
> 
> Which start type you chose ?

bridge.mqtt.edge1.start_type = auto

**Comment by scofieldyhr** [comment]
@gilbertwong96 如果停止master，然后重新启动，测试发现这段时间的消息不会上传的，这个有办法解决么？或者是我有哪些没有配置好的？

**Comment by eggb4by** [comment]
> @gilbertwong96 如果停止master，然后重新启动，测试发现这段时间的消息不会上传的，这个有办法解决么？或者是我有哪些没有配置好的？

I have the same issue, too @gilbertwong96

**Comment by gilbertwong96** [comment]
https://github.com/emqx/emqx-bridge-mqtt/blob/cc13095bbcb8aa84b17fae167a1235ebd814c687/etc/emqx_bridge_mqtt.conf#L165-L170

Gilbert Wong
