### ISSUE TITLE
The coap subscriber sometimes can't receive messages

### ISSUE THREAD

**Issue by xyz361** [emqx/emqx#2973]
#### Environment

- OS: ALL
- Erlang/OTP: 
- EMQ: V 3

#### Description

Use a coap client to subscribe to a topic and send it to another client via qos 0 without problems .
But if another client sends a qos 1 message , the coap subscriber will not receive it .
Then use the client to send qos 0 message , the coap subscriber will not receive it , too .

**Comment by HJianBo** [comment]
This issue has fixed at v4.0.0
