### ISSUE TITLE
MQTT-SN reconnect failed

### ISSUE THREAD

**Issue by bx0829** [emqx/emqx#2976]
#### Environment

- OS: 
- Erlang/OTP: 
- EMQ: EMQ X Broker 3.2.2

#### Description
on EMQ-->Sessions page,when the CleanStart is false,the device with same clientID can not be reconnected after disconnecting

**Comment by terry-xiaoyu** [comment]
I has been long time since 3.x released. Reopen this if it is reproduced on 4.2.x
