### ISSUE TITLE
zone.external.publish_limit not work!

### ISSUE THREAD

**Issue by CaineZhu** [emqx/emqx#2979]
#### Environment

- OS: 
- Erlang/OTP: 
- EMQ: EMQ X Broker v3.1.1

#### Description
config emqx.conf like this and then reboot emqx but not work

```
## Value: Number,Duration
## Example: 10 messages per minute.
zone.external.publish_limit = 10,1m

```

**Comment by HJianBo** [comment]
Hi @CaineZhu sorry for the late reply here.

In the v3.x, some clarification is needed for `publish_limit`:

- In the first, the `publish_limit` only works on MQTT/TCP and MQTT/SSL client.
- And the `publish_limit`  capability depends on a key argument named `active_n`, which shows the Broker will check the Publish Limit after receiving N TCP packets.

In other words, if you set `active_n=100` and `publish_limit=10,1m`. It means the Broker will check whether the client beyond publish limit after receiving 100 PUBLISH packets ( If the client only sends PUBLISH message during this time ).

 So, it seems the `publish_limit` conf not works.

The more friendly value for `active_n` should be equal to the Number of `publish_limit`

**Comment by CaineZhu** [comment]
It's work! ths!
