### ISSUE TITLE
Frequency connection lost or disconnection

### ISSUE THREAD

**Issue by roke1845** [emqx/emqx#2980]
#### Environment

- OS: CentOS 7.6
- Erlang/OTP: R20/9.0
- EMQ: 2.3.8

#### Description

Our EMQ architecture is 3 nodes behind HAproxy.

I subscribe a topic with with wildcard # such as test/# or test/A/#.

It is often disconnection or connection lost.

https://imgur.com/TPfmRD8

Log output kickout frequency.

Oct 16, 2019 @ 11:30:11.343 | 2019-10-16 11:30:08.987 [warning] <0.2512.10>@emqttd_session:handle_cast:529 Session(rogertest-0): kickout <0.2511.10>
  | Oct 16, 2019 @ 11:30:11.242 | 2019-10-16 11:30:10.296 [warning] <0.27617.6>@emqttd_session:handle_cast:529 Session(rogertest-0): kickout <0.27616.6>
  | Oct 16, 2019 @ 11:30:11.242 | 2019-10-16 11:30:07.857 [warning] <0.27578.6>@emqttd_session:handle_cast:529 Session(rogertest-0): kickout <0.27577.6>

**Comment by turtleDeng** [comment]
LOG alert prompts you to use the same clientid to log in repeatedly.

**Comment by roke1845** [comment]
I had changed the clientid, the issue was happened

https://imgur.com/a/6ktWnzx

**Comment by jjuu** [comment]
The client_id may conflict.

**Comment by turtleDeng** [comment]
Thanks for your participation, we will close this issue, if you have any questions, you can continue to open.
