### ISSUE TITLE
Unable to store incoming payload to InfluxDB

### ISSUE THREAD

**Issue by BananaGorilla98** [emqx/emqx#2982]
#### Environment

- OS:  Ubuntu 16.04
- EMQ: EMQX Enterprise 3.4.1

#### Description

Hi, I am new here. I was trying to store those accepted payloads to InfluxDB on my server. I have  set up a rule engine and the action set to "data_to_influxdb" with my server's influxDB. The connection is checked before the rule engine was confirmed.

When the payload message was sent, the status on Dashboard stated it succeeded. But the payload message was not able to be found in the influxDB with the same measurement name. 
May I ask does anyone encounter this similar issue? And how to solve it?

**Comment by tigercl** [comment]
@BananaGorilla98 Sorry for rule engine of v3.4.1 maybe wrong, I suggest you upgrade to v3.4.2

**Comment by BananaGorilla98** [comment]
Thanks, @tigercl. I have solved the issue by update the emqx-ee to version 3.4.2.
