### ISSUE TITLE
ACL is not works for publish.  

### ISSUE THREAD

**Issue by xiemeilong** [emqx/emqx#2984]
#### Environment

- OS: docker image emqx/emqx:latest
- EMQ: 3.2.3

#### Description

ACL is not works for publish.  
I have set EMQX_ACL_NOMATCH: deny,  also set rules in redis. All work for subscription  but not for publish.

**Comment by xiemeilong** [comment]
It's not a bug? It's a missing feature?!

**Comment by terry-xiaoyu** [comment]
Would this answer help?

https://github.com/emqx/emqx/issues/3024#issuecomment-552081142

**Comment by k32** [comment]
Hello,
Authorization has been completely reworked in the latest versions of EMQ X. Please try to upgrade to the latest version and check the issue has been fixed.
