### ISSUE TITLE
Bad network clients cause too many time_wait connections

### ISSUE THREAD

**Issue by zjalen** [emqx/emqx#2986]
#### Environment

- OS: CentOS 7
- Erlang/OTP: R21/10.3.2
- EMQ: 3.1.0

#### Description

I have a program which running on `raspiberry`. Recently I found some of them in bad network environment. The client reconnect when the connection lost.I found many **time_wait** connections on server.And many connect messages of one device appear in the same time.Sometimes the time_wait connections number will be thousands.The server can't be connected then.

I know this situation is caused by client.But I don't know if there is a way to avoid from server.Could someone give me a suggestion?

我遇到了一个情况，使用 `python`  `paho-mqtt` 客户端运行在 **树莓派** 的情况下，使用 `loop_forever()` 保持客户端持续运行。但我发现在网络情况特别差的时候，服务器会出现大量的 **time_wait** 连接，有时候多达数千个，导致服务器无法正常使用。我记录了上下线的记录，发现同一个客户端同一时间也会有多条上线信息到达。这个情况是客户端引起的，但我的使用方式应该是正常的，不知道大家是否有遇到过，如何避免这个情况，或者有没有好的建议？

client:  python  paho-mqtt loop_forever

**Comment by turtleDeng** [comment]
You can try to modify the kernel parameters of TCP.

**Comment by zjalen** [comment]
@turtleDeng I have tried edit the file `/etc/sysctl.conf`.
```bash
net.ipv4.tcp_tw_reuse = 1
net.ipv4.tcp_tw_recycle = 1
net.ipv4.tcp_fin_timeout = 15
```
The number of **time_wait** connections has become dozens. But I am still worried about much more clients will cause server exceptions.

**Comment by turtleDeng** [comment]
Thanks for your participation, we will close this issue.
