### ISSUE TITLE
auth_mysql invalid

### ISSUE THREAD

**Issue by guogenfang** [emqx/emqx#2987]
#### Environment

- OS: centos7
- Erlang/OTP: 
- EMQ: 3.2.3

#### Description

*A description of the issue*

插件配置完启动提示“启动成功”，但是客户端连接随便输入用户名密码都可以连接，emqx stop 提示Plugin emqx_auth_mysql is not started

**Comment by turtleDeng** [comment]
Please provide a detailed LOG

**Comment by turtleDeng** [comment]
Thank you for your use, we will close it and reopen if there are any problems.
