### ISSUE TITLE
EMQ X issues a Will message after connecting Android MqttService for a period of time

### ISSUE THREAD

**Issue by hugo2017** [emqx/emqx#2988]
#### Environment

- OS: Centos 7
- Erlang/OTP: 
- EMQ: R3.0

#### Description
客户端使用官方的Android MqttService，其采用了AlarmPing、WAKE_LOCK等方式保持连接活跃，实际开发测试中发现一段时间没有使用后，EMQX会发布WIll消息，认为该客户端已经掉线。而在emqx dashboard 连接中可以看到该客户端是连接中。

由于方案是利用Will消息机制，实现在线状态的更新，此情况导致方案无法实现。

**Comment by turtleDeng** [comment]
Please provide detailed LOG.

**Comment by turtleDeng** [comment]
Thank you for your use, we will close it and reopen if there are any problems.
