### ISSUE TITLE
How to create a topic?

### ISSUE THREAD

**Issue by rainbow57** [emqx/emqx#2990]
#### Environment

- OS: Ubuntu 16.04
- Erlang/OTP: 
- EMQ: EMQ Broker V 3.1

#### Description
大家好，我在阿里云服务器上使用docker安装了EMQ Broker V3.1 ，现在可以通过18083端口访问Dashboard，使用客户端测试过也可以连接上。接下来要做什么呢？我想创建几个主题，但发现Dashboard上的主题页面没有新增功能，需要做什么配置吗？

**Comment by turtleDeng** [comment]
Please read the MQTT protocol, the client can subscribe to the topic.

**Comment by rainbow57** [comment]
Got it, Thanks for your help 👍
