### ISSUE TITLE
IPv4 TO IPv6

### ISSUE THREAD

**Issue by cherubstar** [emqx/emqx#2991]
#### Environment

- OS: CentOS 7
- Erlang/OTP: 
- EMQ: v3.2.3

#### Description

*A description of the issue*
The system communication environment is IPv6. I want to change the default IPv4 monitoring of emqx to IPv6 monitoring, but I don't know how to change it. Port 18083 can't be accessed through IPv6 at present.

**Comment by xyz361** [comment]
@wivwiv

**Comment by turtleDeng** [comment]
Thank you for your feedback, we have fixed it, will be in release v3.2.4

**Comment by cherubstar** [comment]
Excuse me,I want to know when this problem can be solved, because this software is needed at present.

**Comment by turtleDeng** [comment]
Thanks for your feedback, we have fixed it in v3.2.4.
