### ISSUE TITLE
The $SYS topic for connected/disconnect has bug

### ISSUE THREAD

**Issue by shihuc** [emqx/emqx#2993]
#### Environment

- OS: CentOS 7
- Erlang/OTP: 
- EMQ: V3.2.3

#### Description

1. I use MySQL to do Auth and ACL.
2. Wirte a client program base on paho（java）, use an unexisted username and password (which means that there is no such account in the mqtt_user table) to do connect to the broker.
3. Write an application to Subscribe the topic "$SYS/brokers/emqx@10.95.198.38/clients/+/connected" and "$SYS/brokers/emqx@10.95.198.38/clients/+/disconnected", here my emqx node is emqx@10.95.198.38.

The client can not connect to the broker with reason "Not authorized to connect", it is correct.
BUT, in my application, it subscribed two messages as below:

> Qos : 0, Topic :$SYS/brokers/emqx@10.95.198.38/clients/1_tdrsl86w9vk/connected, ClientId: emqXmonitor
Sub : {"clean_start":true,"clientid":"1_tdrsl86w9vk","connack":135,"ipaddress":"10.95.177.137","keepalive":60,"proto_name":"MQTT","proto_ver":4,"ts":1571885601356,"username":"tdrsl86w9vk"}

Qos : 0, Topic :$SYS/brokers/emqx@10.95.198.38/clients/1_tdrsl86w9vk/connected, ClientId: emqXmonitor
Sub : {"clean_start":true,"clientid":"1_tdrsl86w9vk","connack":135,"ipaddress":"10.95.177.137","keepalive":60,"proto_name":"MQIsdp","proto_ver":3,"ts":1571885601371,"username":"tdrsl86w9vk"}

EMQX refuse the connection of client because of unexisted user, why does not give the application one disconnected event instead with a connected again? 
In my opinion, the second connected message should be a disconnected message, right?

**Comment by shihuc** [comment]
> emqx believes that only the completion and successful mqtt connected, will allow the release of the disconnected event, if no connection is completed, will not trigger the disconnected event.

even though, you can not give the connected event twice, right?

**Comment by turtleDeng** [comment]
Sorry, because EMQ doesn't involve business, it will send a connection message every time you connect. You can decide whether to receive disconnected based on your connected connack.
```
{"clean_start":true,
"clientid":"1_tdrsl86w9vk",
"connack":135,
"ipaddress":"10.95.177.137",
"keepalive":60,
"proto_name":"MQIsdp",
"proto_ver":3,
"ts":1571885601371,
"username":"tdrsl86w9vk"}
```

**Comment by shihuc** [comment]
> Sorry, because EMQ doesn't involve business, it will send a connection message every time you connect. You can decide whether to receive disconnected based on your connected connack.
> 
> ```
> {"clean_start":true,
> "clientid":"1_tdrsl86w9vk",
> "connack":135,
> "ipaddress":"10.95.177.137",
> "keepalive":60,
> "proto_name":"MQIsdp",
> "proto_ver":3,
> "ts":1571885601371,
> "username":"tdrsl86w9vk"}
> ```

Thanks very much.
I test this case again, and, I find the connack just has two kinds of value, 0 for real successful connection, and 135 for "Not authorized to connect" connect.
Is there any other value for connack except 0 and 135?

**Comment by HJianBo** [comment]
About all values of CONNACK, you can see MQTT v3.1.1  and  v5.0 protocol spec

http://docs.oasis-open.org/mqtt/mqtt/v3.1.1/os/mqtt-v3.1.1-os.html#_Toc398718033
https://docs.oasis-open.org/mqtt/mqtt/v5.0/os/mqtt-v5.0-os.html#_Toc3901075

**Comment by turtleDeng** [comment]
We will close this issue, if there are any problems, you can reopen.
