### ISSUE TITLE
Conflicting release: (expecting bionic but getting)

### ISSUE THREAD

**Issue by donyzhai** [emqx/emqx#2994]
#### Environment

- OS: ubuntu 18.04
- Erlang/OTP: 
- EMQ: 

#### Description
执行：sudo add-apt-repository \
>     "deb [arch=amd64] https://repos.emqx.io/emqx-ce/deb/ubuntu/ \
>     $(lsb_release -cs) \
>     stable"
或者执行：
sudo add-apt-repository \
>     "deb [arch=amd64] https://repos.emqx.io/emqx-ce/deb/ubuntu/ \
>     bionic \
>     stable"
都会报错：W: 冲突的发行版：https://repos.emqx.io/emqx-ce/deb/ubuntu bionic InRelease (期望 bionic 但得到 )

etc/apt/soruces.list 文件如下：
![image](https://user-images.githubusercontent.com/15155218/67464743-77eb6480-f676-11e9-9c6e-d75b11c893b0.png)

*A description of the issue*

**Comment by zhanghongtong** [comment]
@donyzhai You need delete `deb [arch=amd64] https://repos.emqx.io/emqx-ce/deb/ubuntu/ bionic stable` in `etc/apt/soruces.list` first

**Comment by donyzhai** [comment]
It's done! Thank you
