### ISSUE TITLE
emq x broker and udp/tcp

### ISSUE THREAD

**Issue by gdillen** [emqx/emqx#2995]
#### Environment

- OS: N/A
- Erlang/OTP: N/A
- EMQ: N/A

#### Description

Hi,

Does EMQ X Broker supports  UDP and/or TCP  messages ingesting (NB-IoT)?

Thanks.

**Comment by turtleDeng** [comment]
Yes, mqtt protocol is carried on TCP, lwm2m protocol is carried on UDP,https://github.com/emqx/emqx-lwm2m.

**Comment by turtleDeng** [comment]
Thank you for your participation, I will close this issue.
