### ISSUE TITLE
 emqx Dashboard loop URL Not Found .404 监控页面无法使用

### ISSUE THREAD

**Issue by bitsz** [emqx/emqx#2996]
#### Environment

- OS: centos7
- Erlang/OTP:  otp_src_19.3
- EMQ: 3.2.3

#### Description

访问Dashboard时，所有的连接都url not found。视乎存在于/api/**路由。

![image](https://user-images.githubusercontent.com/20807514/67546496-205cff80-f72f-11e9-9ba6-c427bae23881.png)
该怎样解决这个问题？

**Comment by OneKingPC** [comment]
我遇到的情况是端口被占用了，在etc/plugins目录下的emqx_management.conf。
![image](https://user-images.githubusercontent.com/13903399/67612977-8a7eae80-f7da-11e9-8ce0-6aa80a394217.png)

**Comment by turtleDeng** [comment]
Thanks for your feedback.
