### ISSUE TITLE
Auto check SSL option on Websocket Tool if that is opened with HTTPS.

### ISSUE THREAD

**Issue by PMExtra** [emqx/emqx#3002]
![20191029205752](https://user-images.githubusercontent.com/11289158/67769995-7237b980-fa90-11e9-904b-631de2c17f7e.png)

The SSL option should be auto checked if the page is opened with HTTPS, otherwise the security error will be caused:
> SecurityError: Failed to construct 'WebSocket': An insecure WebSocket connection may not be initiated from a page loaded over HTTPS.

The port has been set to 8084 (from 8083) automatically if HTTPS. So I think the SSL check box should be auto checked with the suitable port.

--- 分割线 ---
避免我的塑料英语表达有误我再用中文说一次，Dashboard中的Websocket工具应当在HTTPS环境下自动勾选SSL选项，因为浏览器不允许HTTPS页面建立未加密的ws连接。而且现在已经会在HTTPS环境下自动把端口号从8083修改成8084了，那么SSL选项也应该配套自动勾选。

**Comment by turtleDeng** [comment]
Thank you for your comments, we will support it in the next version.

**Comment by tigercl** [comment]
@PMExtra It has bee fixed in emqx-v3.2.6, thanks for your feedback again.
