### ISSUE TITLE
v3 REST API 401

### ISSUE THREAD

**Issue by qxqxq** [emqx/emqx#3004]
#### Environment

- OS: mac os 
- Erlang/OTP: 19
- EMQ: 3.1.1

- OS: ubuntu16.04
- Erlang/OTP: 21
- EMQ: 3.1.1

#### Description

*A description of the issue*

curl -v --basic -u admin:public -k http://localhost:8080/api/v3/brokers
*   Trying 127.0.0.1...
* Connected to localhost (127.0.0.1) port 8080 (#0)
* Server auth using Basic with user 'admin'
> GET /api/v3/brokers HTTP/1.1
> Host: localhost:8080
> Authorization: Basic YWRtaW46cHVibGlj
> User-Agent: curl/7.47.0
> Accept: */*
> 
< HTTP/1.1 401 Unauthorized
* Authentication problem. Ignoring this.
< WWW-Authenticate: Basic Realm="minirest-server"
< content-length: 12
< date: Wed, 30 Oct 2019 01:41:52 GMT
< server: Cowboy
< 
* Connection #0 to host localhost left intact

or
url = 'http://127.0.0.1:8080/api/v3/auth_clientid'
ret = requests.get(url, auth=('admin', 'public'))
print(ret)        # <Response [401]>
print(ret.text)     # UNAUTHORIZED
print(ret.status_code) # 401

**Comment by zhanghongtong** [comment]
@qxqxq The HTTP requests to the REST API are protected with HTTP Basic authentication. You can create an application in Dashboard, using appid and appsecret to authenticate. For example:
```
curl -v --basic -u <appid>:<appsecret> -k http://localhost:8080/api/v3/brokers
```

**Comment by qxqxq** [comment]
> @qxqxq通过HTTP Basic身份验证保护对REST API的HTTP请求。您可以在Dashboard中使用appid和appsecret进行身份验证来创建应用程序。例如：
> 
> ```
> curl -v --basic -u <appid>:<appsecret> -k http://localhost:8080/api/v3/brokers
> ```

**Comment by qxqxq** [comment]
谢谢您的帮助，问题已经解决。

**Comment by qxqxq** [comment]
Thank you for your help. The problem has been solved.
