### ISSUE TITLE
What is the purpose of the EMQ X HTTP publishing interface client_id

### ISSUE THREAD

**Issue by qxqxq** [emqx/emqx#3006]
#### Environment

- OS: mac os
- Erlang/OTP:19 
- EMQ: 3.2.4

#### Description

*A description of the issue*

{"code": 0, "data": [
    {"clean_start": true, "client_id": "02", "conn_mod": "emqx_channel", "connected_at": "2019-10-31 11:00:20",
     "heap_size": 610, "ipaddress": "192.168.245.99", "is_bridge": false, "keepalive": 60, "mailbox_len": 0,
     "node": "emqx@127.0.0.1", "peercert": "nossl", "port": 51169, "proto_name": "MQTT", "proto_ver": 4, "recv_cnt": 6,
     "recv_msg": 0, "recv_oct": 134, "recv_pkt": 8, "reductions": 15461, "send_cnt": 13, "send_msg": 5, "send_oct": 82,
     "send_pend": 0, "send_pkt": 13, "username": "admin2", "zone": "external"},
    {"clean_start": true, "client_id": "01", "conn_mod": "emqx_channel", "connected_at": "2019-10-31 11:00:17",
     "heap_size": 610, "ipaddress": "192.168.245.99", "is_bridge": false, "keepalive": 60, "mailbox_len": 0,
     "node": "emqx@127.0.0.1", "peercert": "nossl", "port": 51166, "proto_name": "MQTT", "proto_ver": 4, "recv_cnt": 6,
     "recv_msg": 0, "recv_oct": 134, "recv_pkt": 8, "reductions": 8976, "send_cnt": 8, "send_msg": 0, "send_oct": 27,
     "send_pend": 0, "send_pkt": 8, "username": "admin1", "zone": "external"}],
 "meta": {"page": 1, "limit": 10000, "count": 2}}

data = {
  "topic": "02",
  "payload": "hello",
  "qos": 0,
  "client_id": "01"
}
or
data = {
  "topic": "02",
  "payload": "hello",
  "qos": 0,
  "client_id": "05"
}
or
data = {
  "topic": "02",
  "payload": "hello",
  "qos": 0,
}

The current online "client_id" only has "01" and "02".
But 'client_id' can be arbitrary or nonexistent when I use the EMQ X HTTP publishing interface.
So I don't quite understand what 'client_id' does.

**Comment by turtleDeng** [comment]
ClientId is an optional parameter, in front of the publish ClientId.

**Comment by turtleDeng** [comment]
Thank you for your participation, we will close this issue.
