### ISSUE TITLE
how many topics can one client subscribe?

### ISSUE THREAD

**Issue by shihuc** [emqx/emqx#3009]
#### Environment

- OS: CentOS
- Erlang/OTP: 
- EMQ: V3.2.3

#### Description

In my test environment, my application subscribe more than 1 topic, sometimes, it subscrbes more than 1000 topics. All the subscription mode is share subsciption.

Then, I met one issue, that my application can not get all the message from the topic which my application subscribed. what I mean, for example, if I publish 10 messages, there are 3 or 4 messages will lost.

When this problem happend, if to reboot the EMQX, the problem will disappear.

What is wrong? I guess the topic number has some restrication for one consumer client, or something else impact the subscription logic.

How to fix this problem? I can not reboot EMQX always....

**Comment by turtleDeng** [comment]
By default, there is no limit to the number of topics a client can subscribe to, and emqx provides a configuration to control the number of subscription topics.
```
## Maximum number of subscriptions allowed, 0 means no limit.
max_subscriptions = 0
```

**Comment by turtleDeng** [comment]
Thank you for your participation, I will close this issue.
