### ISSUE TITLE
Client implemented by python failed to connect to emqx

### ISSUE THREAD

**Issue by aidenpierce2** [emqx/emqx#3015]
#### Environment

- OS: 
- Erlang/OTP: 
- EMQ: 

#### Description

*A description of the issue*
服务器没有问题，小程序与测试的websocket连接，订阅均正常，尝试使用官方demo，使用python连接emqx时无反应 也无报错,请问是咋回事？
参考文章: https://www.jianshu.com/p/b76dbc675141
实例代码: 

# _*_ coding:   utf-8 _*_

import paho.mqtt.client as mqtt
import random
import time
import json

MQTTHOST = "127.0.0.1";
MQTTPOERT = 1883;
MQTTHEART = 60;
client_id = "publish";

# 连接MQTT服务器
def on_connect(client, userdata, flags, rc):
  print("Connected with result code "+str(rc))

# 消息处理函数
def on_message(client, userdata, msg):
  print(msg.topic+" "+str(msg.payload))

# # uploadSpeed函数
# def make_uploadSpeed():
# 	randomUploadSpeed = random.uniform(100.00, 1000.00);
# 	uploadSpeedUtil = "kb/s";
# 	while True:
# 		time.sleep(2);
# 		data = {
# 			"uploadSpeed": randomUploadSpeed,
# 			"unit": uploadSpeedUtil
# 		};
# 		param = json.dumps(data)
# 		# on_mqtt_publish("uploadSpeed", param, 1);
# 		pass
#
# # downLoadSpeed函数
# def make_downLoadSpeed():
# 	randomUploadSpeed = random.uniform(100.00, 1000.00);
# 	uploadSpeedUtil = "kb/s";
# 	while True:
# 		time.sleep(2);
# 		data = {
# 			"downLoadSpeed": randomUploadSpeed,
# 			"unit": uploadSpeedUtil
# 		};
# 		param = json.dumps(data)
# 		# on_mqtt_publish("downLoadSpeed", param, 1);
# 		pass
#
# def main():
client = mqtt.Client()
client.on_connect = on_connect
client.on_message = on_message
# client.connect(MQTTHOST, MQTTPOERT, MQTTHEART)
client.connect("127.0.0.1", 1883, 600)
client.publish('emqtt', payload='Hello,EMQ!', qos=0)
client.loop_start()

# if __name__ == '__main__':
#     main()

**Comment by tigercl** [comment]
Hi, @aidenpierce2. Using `./emqx_ctl log set-level debug` to open debug log, then try again. You can try to analyze it (location: .../emqx/log/emqx.log) or send it to us.

**Comment by aidenpierce2** [comment]
thanks  all, i had solve this problem!
