### ISSUE TITLE
EMQ X Dashboard does not open with 18084 port (HTTPS)

### ISSUE THREAD

**Issue by ismailozturk07** [emqx/emqx#3019]
- OS: Ubuntu 16.04
- EMQ: 3.2.3

I did the installation. Mqtt connection is OK. Let's Encrypt works with the ssl 8883 connection. But the Dashboard does not open with 18084 port.
I made the emq x settings mentioned in the link below.
https://medium.com/@emqtt/using-lets-encrypt-certificates-in-emq-b11e0e57efa6

I have performed the instructions here. what is the problem?

**Comment by tigercl** [comment]
Hi, @ismailozturk07. Does emqx have any error log?

**Comment by joko2020** [comment]
> * OS: Ubuntu 16.04
> * EMQ: 3.2.3
> 
> I did the installation. Mqtt connection is OK. Let's Encrypt works with the ssl 8883 connection. But the Dashboard does not open with 18084 port.
> I made the emq x settings mentioned in the link below.
> https://medium.com/@emqtt/using-lets-encrypt-certificates-in-emq-b11e0e57efa6
> 
> I have performed the instructions here. what is the problem?

same as me no error in page just white blank screen if I use https://domain.name:18084, but if I put https://domain.name:18084/#/login the login page appear but cannot login with "network error"

**Comment by SuvabBaral** [comment]
@ismailozturk07 @joko2020  How did you fix this issue?

**Comment by zmstone** [comment]
Hi @SuvabBaral 

This thread was about EMQX v3.
If you have trouble setting up HTTPS listener for v5, you can maybe refer to this doc:
https://www.emqx.io/docs/en/latest/configuration/listener.html#configure-ssl-listener

If it still doesn't work, please feel free to collect logs from EMQX and create a new issue.

**Comment by zmstone** [comment]
dashboard listener doc is here: https://www.emqx.io/docs/en/latest/configuration/dashboard.html

worth adding:
> certfile: This sets the path to the file containing the SSL/TLS certificate for the listener.

this file can contain the full certificate chain, server certificate being the first, followed by the issuer certificates (intermediate CA) and so on, all the way up to the root (however root certificate is optional in this file).

**Comment by zmstone** [comment]
there is also a video about EMQX TLS in general, which includes a very detailed explanation about certificate chains and how they are mapped to EMQX certfile configs using let's encrypt issued certificates as example.

https://www.youtube.com/watch?v=HRqJLi7-9KU
