### ISSUE TITLE
Parse failed for function_clause

### ISSUE THREAD

**Issue by tanglifeng** [emqx/emqx#3020]
#### Environment

- OS: centos 7
- Erlang/OTP: 
- EMQ: 3.0.1

#### Description

*A description of the issue*
2019-08-29 22:13:11.644 [error] 10.33.32.97:53668 Parse failed for function_clause
Error data:<<"GET / HTTP/1.1\r\nConnection: Close\r\nHost: 202.90.21.97\r\nPragma: no-cache\r\nUser-Agent: Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 5.1; Trident/4.0)\r\nAccept: image/gif, image/x-xbitmap, image/jpeg, image/pjpeg, image/png, */*\r\nAccept-Language: en\r\nAccept-Charset: iso-8859-1,*,utf-8\r\n\r\n">>
2019-08-29 22:13:11.693 [error] 10.33.32.97:53670 Parse failed for function_clause
Error data:<<"GET login?hsgid=00000000-0000-0000-0000-000000000000&hasFP=1 HTTP/1.1\r\nHost: 202.90.21.97:1881\r\nAccept-Charset: iso-8859-1,utf-8;q=0.9,*;q=0.1\r\nAccept-Language: en\r\nConnection: Close\r\nAccept-Encoding: gzip\r\nClient-ATV-Sharing-Version: 1.2\r\nClient-DAAP-Version: 3.13\r\nClient-iTunes-Sharing-Version: 3.15\r\nViewer-Only-Client: 1\r\nUser-Agent: Remote/1021\r\nPragma: no-cache\r\nAccept: image/gif, image/x-xbitmap, image/jpeg, image/pjpeg, image/png, */*\r\n\r\n">>
2019-08-29 22:14:49.252 [error] 10.33.32.97:53784 Parse failed for function_clause
Error data:<<"GET / HTTP/1.1\r\nHost: 202.90.21.97:1881\r\nAccept-Charset: iso-8859-1,utf-8;q=0.9,*;q=0.1\r\nAccept-Language: en\r\nConnection: Keep-Alive\r\nUser-Agent: Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 5.1; Trident/4.0)\r\nPragma: no-cache\r\nAccept: image/gif, image/x-xbitmap, image/jpeg, image/pjpeg, image/png, */*\r\n\r\n">>
2019-09-21 15:09:54.177 [error] 10.33.32.97:24320 Parse failed for function_clause
Error data:<<0,30,0,6,1,0,0,1,0,0,0,0,0,0,7,118,101,114,115,105,111,110,4,98,
             105,110,100,0,0,16,0,3>>
2019-09-21 15:09:54.300 [error] 10.33.32.97:24322 Parse failed for function_clause
Error data:<<0,12,0,0,16,0,0,0,0,0,0,0,0,0>>

**Comment by turtleDeng** [comment]
Please check your message format. You can see from the LOG that your MQTT 1883 port has received the HTTP request message.

**Comment by turtleDeng** [comment]
Thank you for your participation, we will close this issue
