### ISSUE TITLE
Parse failed for {badmatch,<<>>}

### ISSUE THREAD

**Issue by tanglifeng** [emqx/emqx#3021]
#### Environment

- OS: 
- Erlang/OTP: 
- EMQ: 

#### Description

*A description of the issue*

2019-09-21 15:10:01.980 [error] 10.33.32.97:24334 Parse failed for {badmatch,<<>>}
Error data:<<22,3,0,0,83,1,0,0,79,3,0,63,71,215,247,186,44,238,234,178,96,126,
             243,0,253,130,123,185,213,150,200,119,155,230,196,219,60,61,219,
             111,239,16,110,0,0,40,0,22,0,19,0,10,0,102,0,5,0,4,0,101,0,100,0,
             99,0,98,0,97,0,96,0,21,0,18,0,9,0,20,0,17,0,8,0,6,0,3,1,0>>
2019-09-21 15:10:02.093 [error] 10.33.32.97:24336 Parse failed for {badmatch,<<>>}
Error data:<<22,3,0,0,105,1,0,0,101,3,3,85,28,167,228,114,97,110,100,111,109,
             49,114,97,110,100,111,109,50,114,97,110,100,111,109,51,114,97,110,
             100,111,109,52,0,0,12,0,47,0,10,0,19,0,57,0,4,0,255,1,0,0,48,0,13,
             0,44,0,42,0,1,0,3,0,2,6,1,6,3,6,2,2,1,2,3,2,2,3,1,3,3,3,2,4,1,4,3,
             4,2,1,1,1,3,1,2,5,1,5,3,5,2>>
2019-09-21 15:10:12.789 [error] 10.33.32.97:24364 Parse failed for function_clause
Error data:<<48,12,2,1,1,96,7,2,1,2,4,0,128,0>>
2019-09-21 15:10:12.896 [error] 10.33.32.97:24368 Parse failed for function_clause
Error data:<<"OPTIONS sip:nm SIP/2.0\r\nVia: SIP/2.0/TCP nm;branch=foo\r\nFrom: <sip:nm@nm>;tag=root\r\nTo: <sip:nm2@nm2>\r\nCall-ID: 50000\r\nCSeq: 42 OPTIONS\r\nMax-Forwards: 70\r\nContent-Length: 0\r\nContact: <sip:nm@nm>\r\nAccept: application/sdp\r\n\r\n">>
2019-09-21 15:10:33.603 [error] 10.33.32.97:24404 Parse failed for function_clause
Error data:<<0,3,0,1,0,0,0,0,0,0,0,2,0,0,0,0,15,0>>

**Comment by turtleDeng** [comment]
Please check your message format. You can see from the LOG that your MQTT 1883 port has received the HTTP request message.

**Comment by turtleDeng** [comment]
The same problem is https://github.com/emqx/emqx/issues/3020
