### ISSUE TITLE
modbus gateway implementation?

### ISSUE THREAD

**Issue by jianglinchun** [emqx/emqx#3022]
#### Environment

- OS:  Any
- Erlang/OTP:  Any
- EMQ: Any

#### Description

* has any one tried this plugin? https://github.com/emqx/emqx-modbus

**Comment by HJianBo** [comment]
@jianglinchun Yes, we will release an initiatory edition at EMQ X v4.x

**Comment by jianglinchun** [comment]
@HJianBo thank you so much. This is a great news. :)

**Comment by HJianBo** [comment]
We are sorry to inform you that there are no plans to support this protocol in emqx at this time. modbus and other industrial protocols are supported by neuron products exclusively. For more information see: https://www.emqx.io/products/neuron

**Comment by jianglinchun** [comment]
@HJianBo thank you so much for your reply. I had wrote my own Modbus poll and bridge the data to mqtt.
And I'm quite sure neuron will be a great product for IOT edge devices & server.
Looking forward to more details about neuron and hope we could have further cooperation in IOT industry and business opportunities.

btw:I'm trying to implementing profibus/profinet && cc-link standard protocols.
