### ISSUE TITLE
ACL is not available in V3???

### ISSUE THREAD

**Issue by shihuc** [emqx/emqx#3024]
#### Environment

- OS: CentOS 7
- Erlang/OTP: 
- EMQ: V3.2.3/V3.2.4

#### Description

ACL access 1(subscribe),2(publish) is not available,

My configuration is based on mysql for auth/acl. The configuration is like this:

> ## Allow anonymous authentication by default if no auth plugins loaded.
##
## Value: true | false
allow_anonymous = false

##
## Value: allow | deny
acl_nomatch = deny

##
## Value: File Name
acl_file = /etc/emqx/acl.conf

##
##
## Value: on | off
enable_acl_cache = on

##
## Default: 32
acl_cache_max_size = 32

##
## Default: 1 minute
acl_cache_ttl = 1m

##
## Default: ignore
acl_deny_action = ignore

and, the mqtt_acl table is configured like this:

> mysql> select * from mqtt_acl;
+----+-------+-----------+-----------+----------+--------+---------+
| id | allow | ipaddr    | username  | clientid | access | topic   |
+----+-------+-----------+-----------+----------+--------+---------+
|  1 |     1 | NULL      | $all      | NULL     |      2 | #       |
|  2 |     0 | NULL      | $all      | NULL     |      1 | $SYS/#  |
|  3 |     0 | NULL      | $all      | NULL     |      1 | eq #    |
|  5 |     1 | 127.0.0.1 | NULL      | NULL     |      2 | $SYS/#  |
|  6 |     1 | 127.0.0.1 | NULL      | NULL     |      2 | #       |
|  7 |     1 | NULL      | dashboard | NULL     |      1 | $SYS/#  |
|  8 |     1 | NULL      | water     | NULL     |      1 | hello/# |
|  9 |     1 | NULL      | shihuc    | NULL     |      2 | hello/# |
+----+-------+-----------+-----------+----------+--------+---------+

I sub and pub with user water at topic hello/1, they both work, it is not right.

In V2, the access is subscribe, then it can not publish, if it is publish, then it can not subscribe, but in V3, it works not like this.

What is wrong? is there something configuration incorrect?

Please help!!!

**Comment by terry-xiaoyu** [comment]
@shihuc The ACL records listed in your table will be evaluated from the top to bottom. So it might be your first ACL record that allows all the publish messages.

**Comment by shihuc** [comment]
> @shihuc The ACL records listed in your table will be evaluated from the top to bottom. So it might be your first ACL record that allows all the publish messages.

Thanks for your relpy.
BUT, I  remove the others unuesd ACL rules, only leave two I create as below:

> +----+-------+--------+----------+----------+--------+---------+
| id | allow | ipaddr | username | clientid | access | topic   |
+----+-------+--------+----------+----------+--------+---------+
|  8 |     1 | NULL   | water    | NULL     |      1 | hello/# |
|  9 |     1 | NULL   | shihuc   | NULL     |      2 | world/# |
+----+-------+--------+----------+----------+--------+---------+

and then, use water as the publisher to publish at topic world/2, use shihuc as the subscriber to subscribe at topic world/2, unfortunately, the publisher and the subscriber are both OK...

In EMQX principle of ACL, the publisher can not publish successfully, the subscriber can not subscribe neighter.

Please do the above cases as what I described, I think it has something wrong, this ACL feature is very  useful, if it does not work in V3, it is a bad news.

**Comment by terry-xiaoyu** [comment]
@shihuc Hi, I tried myself just now and it works.

Please check the following points:

1. auth mysql plugins is on.

2. set `enable_acl_cache = off` in emqx.conf, to ensure that acl cache not impact our test result.

3. only one configuration record in the etc/acl.conf: `{deny, all}.`, to ensure that we only read the acl rules from the mysql tables, not acl.conf.

4. restart emqx to ensure the above configs are loaded.

Hope this helps.

**Comment by alexandrim0** [comment]
Hello!

I tried to use acl.conf and auth\ACL with HTTP plugin and acl.conf file does not works if plugin is enabled. All requests go to plugin first and it stops them.
If ACL plugin disabled then acl.conf file works fine.
It could be the same issue. Is it?

**Comment by k32** [comment]
Hello,
This version of EMQ X is very old. EMQ X authorization has been rewritten and improved since. Please upgrade to the latest version and check if this issue persists.
