### ISSUE TITLE
Google Protobuf Plugin development

### ISSUE THREAD

**Issue by ShaheeraFatima** [emqx/emqx#3026]
I want to make a plug-in for google protobuf. Is it possible to make one using JS or is it must to do it with Erlang? Kindly guide me for both.

**Comment by terry-xiaoyu** [comment]
The `schema-registry` in our enterprise-emqx is out of box. It now supports protobuf, avro and user-customized schema. Have a try at `https://www.emqx.io/downloads`, you could get a free license for one month.

Or you could write your own erlang plugin. In our schema registry, we used the awesome [protobuf library](https://github.com/tomas-abrahamsson/gpb) by [tomas-abrahamsson](https://github.com/tomas-abrahamsson/gpb/commits?author=tomas-abrahamsson).

JS plugin is not supported, but you could use the web-hook plugin forwarding the messages/events to your own web server and then handle them in your JS code.
