### ISSUE TITLE
Emqx_Bridge_Kafka loading Issue

### ISSUE THREAD

**Issue by sourjya123** [emqx/emqx#3030]
I have enterprise emq in my environment. In that emq kafka bridge is also available. When I am loading the Emqx_Bridge_Kafka using below command

./bin/emqx_ctl plugins load emqx_bridge_kafka

I am getting the following error:

=ERROR REPORT==== 13-Nov-2019::00:12:27.890394 ===
[Plugins] Load plugin emqx_bridge_kafka failed, cannot start plugin emqx_bridge_kafka for {bad_return,
                                                                                           {{emqx_bridge_kafka_app,
                                                                                             start,
                                                                                             [normal,
                                                                                              []]},
                                                                                            {'EXIT',
                                                                                             {badarg,
                                                                                              [{jsx_decoder,
                                                                                                value,
                                                                                                4,
                                                                                                [{file,
                                                                                                  "/emqx_temp/emqx_enterprise_rel/_checkouts/jsx/src/jsx_decoder.erl"},
                                                                                                 {line,
                                                                                                  234}]},
                                                                                               {emqx_bridge_kafka,
                                                                                                parse_hook,
                                                                                                3,
                                                                                                [{file,
                                                                                                  "/emqx_temp/emqx_enterprise_rel/_checkouts/emqx_bridge_kafka/src/emqx_bridge_kafka.erl"},
                                                                                                 {line,
                                                                                                  215}]},
                                                                                               {emqx_bridge_kafka,
                                                                                                load,
                                                                                                1,
                                                                                                [{file,
                                                                                                  "/emqx_temp/emqx_enterprise_rel/_checkouts/emqx_bridge_kafka/src/emqx_bridge_kafka.erl"},
                                                                                                 {line,
                                                                                                  46}]},
                                                                                               {emqx_bridge_kafka_app,
                                                                                                start,
                                                                                                2,
                                                                                                [{file,
                                                                                                  "/emqx_temp/emqx_enterprise_rel/_checkouts/emqx_bridge_kafka/src/emqx_bridge_kafka_app.erl"},
                                                                                                 {line,
                                                                                                  34}]},
                                                                                               {application_master,
                                                                                                start_it_old,
                                                                                                4,
                                                                                                [{file,
                                                                                                  "application_master.erl"},
                                                                                                 {line,
                                                                                                  277}]}]}}}}
load plugin error: {emqx_bridge_kafka,
                    {bad_return,
                     {{emqx_bridge_kafka_app,start,[normal,[]]},
                      {'EXIT',
                       {badarg,
                        [{jsx_decoder,value,4,
                          [{file,
                            "/emqx_temp/emqx_enterprise_rel/_checkouts/jsx/src/jsx_decoder.erl"},
                           {line,234}]},
                         {emqx_bridge_kafka,parse_hook,3,
                          [{file,
                            "/emqx_temp/emqx_enterprise_rel/_checkouts/emqx_bridge_kafka/src/emqx_bridge_kafka.erl"},
                           {line,215}]},
                         {emqx_bridge_kafka,load,1,
                          [{file,
                            "/emqx_temp/emqx_enterprise_rel/_checkouts/emqx_bridge_kafka/src/emqx_bridge_kafka.erl"},
                           {line,46}]},
                         {emqx_bridge_kafka_app,start,2,
                          [{file,
                            "/emqx_temp/emqx_enterprise_rel/_checkouts/emqx_bridge_kafka/src/emqx_bridge_kafka_app.erl"},
                           {line,34}]},
                         {application_master,start_it_old,4,
                          [{file,"application_master.erl"},{line,277}]}]}}}}}

Can you please let me know the root cause. It is really urgent for me.

**Comment by HJianBo** [comment]
```
{badarg,
[{jsx_decoder,
value,
4,
[{file,
"/emqx_temp/emqx_enterprise_rel/_checkouts/jsx/src/jsx_decoder.erl"},
{line,
234}]},
{emqx_bridge_kafka,
parse_hook,
3,
```
Please check the emqx_bridge_kafka.conf hook configurations. It  may not a valid format

**Comment by sourjya123** [comment]
I am posting the hook configuration here. 

bridge.kafka.hook.client.connected.1     = {"topic": "client_connected"}
bridge.kafka.hook.client.disconnected.1  = {"topic": "client_disconnected"}
bridge.kafka.hook.session.subscribed.1   = {"filter": "#", "topic":"session_subscribed"}
bridge.kafka.hook.session.unsubscribed.1 = {"filter":"#", "topic":"session_unsubscribed"}
bridge.kafka.hook.message.publish.1      = {"filter":"#", "topic":"message_publish"}
bridge.kafka.hook.message.delivered.1    = {"filter":"#", "topic":"message_deliver"}
bridge.kafka.hook.message.acked.1        = {"filter":"#", "topic":"message_acked"}

**Comment by HJianBo** [comment]
Which version do you use?

**Comment by sourjya123** [comment]
I am using emqx3.2.2 enterprise version.

**Comment by sourjya123** [comment]
Plugin(emqx_bridge_kafka, version=3.2.2, description=EMQ X Kafka Backend, active=false)

**Comment by HJianBo** [comment]
This line should be
```
bridge.kafka.hook.message.deliver.1      = {"filter":"#", "topic":"message_deliver"}
```

Not
```
bridge.kafka.hook.message.delivered.1 = {"filter":"#", "topic":"message_deliver"}
```

**Comment by sourjya123** [comment]
I have changed it, but still getting the below issue

=ERROR REPORT==== 13-Nov-2019::02:43:58.656550 ===
[Plugins] Load plugin emqx_bridge_kafka failed, cannot start plugin emqx_bridge_kafka for {bad_return,
                                                                                           {{emqx_bridge_kafka_app,
                                                                                             start,
                                                                                             [normal,
                                                                                              []]},
                                                                                            {'EXIT',
                                                                                             {badarg,
                                                                                              [{jsx_decoder,
                                                                                                value,
                                                                                                4,
                                                                                                [{file,
                                                                                                  "/emqx_temp/emqx_enterprise_rel/_checkouts/jsx/src/jsx_decoder.erl"},
                                                                                                 {line,
                                                                                                  234}]},
                                                                                               {emqx_bridge_kafka,
                                                                                                parse_hook,
                                                                                                3,
                                                                                                [{file,
                                                                                                  "/emqx_temp/emqx_enterprise_rel/_checkouts/emqx_bridge_kafka/src/emqx_bridge_kafka.erl"},
                                                                                                 {line,
                                                                                                  215}]},
                                                                                               {emqx_bridge_kafka,
                                                                                                load,
                                                                                                1,
                                                                                                [{file,
                                                                                                  "/emqx_temp/emqx_enterprise_rel/_checkouts/emqx_bridge_kafka/src/emqx_bridge_kafka.erl"},
                                                                                                 {line,
                                                                                                  46}]},
                                                                                               {emqx_bridge_kafka_app,
                                                                                                start,
                                                                                                2,
                                                                                                [{file,
                                                                                                  "/emqx_temp/emqx_enterprise_rel/_checkouts/emqx_bridge_kafka/src/emqx_bridge_kafka_app.erl"},
                                                                                                 {line,
                                                                                                  34}]},
                                                                                               {application_master,
                                                                                                start_it_old,
                                                                                                4,
                                                                                                [{file,
                                                                                                  "application_master.erl"},
                                                                                                 {line,
                                                                                                  277}]}]}}}}
load plugin error: {emqx_bridge_kafka,
                    {bad_return,
                     {{emqx_bridge_kafka_app,start,[normal,[]]},
                      {'EXIT',
                       {badarg,
                        [{jsx_decoder,value,4,
                          [{file,
                            "/emqx_temp/emqx_enterprise_rel/_checkouts/jsx/src/jsx_decoder.erl"},
                           {line,234}]},
                         {emqx_bridge_kafka,parse_hook,3,
                          [{file,
                            "/emqx_temp/emqx_enterprise_rel/_checkouts/emqx_bridge_kafka/src/emqx_bridge_kafka.erl"},
                           {line,215}]},
                         {emqx_bridge_kafka,load,1,
                          [{file,
                            "/emqx_temp/emqx_enterprise_rel/_checkouts/emqx_bridge_kafka/src/emqx_bridge_kafka.erl"},
                           {line,46}]},
                         {emqx_bridge_kafka_app,start,2,
                          [{file,
                            "/emqx_temp/emqx_enterprise_rel/_checkouts/emqx_bridge_kafka/src/emqx_bridge_kafka_app.erl"},
                           {line,34}]},
                         {application_master,start_it_old,4,
                          [{file,"application_master.erl"},{line,277}]}]}}}}}

**Comment by sourjya123** [comment]
The hook config is given below:

## Bridge Kafka Hooks
## ${topic}: the kafka topics to which the messages will be published.
## ${filter}: the mqtt topic (may contain wildcard) on which the action will be performed .
bridge.kafka.hook.client.connected.1     = {"topic": "client_connected"}
bridge.kafka.hook.client.disconnected.1  = {"topic": "client_disconnected"}
bridge.kafka.hook.session.subscribed.1   = {"filter": "#", "topic": "session_subscribed"}
bridge.kafka.hook.session.unsubscribed.1 = {"filter": "#", "topic": "session_unsubscribed"}
bridge.kafka.hook.message.publish.1      = {"filter": "#", "topic": "message_publish"}
bridge.kafka.hook.message.deliver.1      = {"filter":"#", "topic":"message_deliver"}
bridge.kafka.hook.message.acked.1        = {"filter": "#", "topic": "message_acked"}

**Comment by sourjya123** [comment]
After commenting the hook config if I run it, Its giving same error. Can you please help me in this.

**Comment by HJianBo** [comment]
Do you have reload plugin by following cmd:
```
./bin/emqx_ctl plugins reload emqx_bridge_kafka
```

**Comment by sourjya123** [comment]
yes I have this plugin if I do plugin list. But ./bin/emqx_ctl plugins reload emqx_bridge_kafka this command is throwing the above error.

**Comment by sourjya123** [comment]
So space issue was there. I removed it and got loaded. Thanks for your help. :D :)

**Comment by sourjya123** [comment]
bridge.kafka.hook.message.publish.1      = {"filter":"+/+/DEVICE_MESSAGES","topic":"DEVICE_MESSAGES"}
can I have like this with wild card. So whatever comes from emq to +/+/DEVICE_MESSAGES it will be mapped to DEVICE_MESSAGES of kafka topic

**Comment by HJianBo** [comment]
Yes, it will

**Comment by sourjya123** [comment]
can I have multiple filter like {"filter":"+/+/DEVICE_MESSAGES","topic":"DEVICE_MESSAGES"} ?
ex,
bridge.kafka.hook.message.publish.1 ={"filter":"+/+/DEVICE_PROFILE","topic":"DEVICE_PROFILE"}
bridge.kafka.hook.message.publish.1 ={"filter":"+/+/DMS_MESSAGES","topic":"DMS_MESSAGES"}

So my question is bridge.kafka.hook.message.publish.1 this should be same or I can have anything like
bridge.kafka.hook.message.profile_publish.1 = {"filter":"+/+/DEVICE_PROFILE","topic":"DEVICE_PROFILE"}

bridge.kafka.hook.message.message_publish.1 = {"filter":"+/+/DEVICE_MESSAGE","topic":"DEVICE_MESSAGE"}

**Comment by akshaykootta** [comment]
While publishing data to EMQX using 
_mosquitto_pub -h localhost -p 1883 -t mcd/11.22.33.44/DEVICE_MESSAGES -q 2 -m "hello how are you"_

I m getting the Kafka Message 
_null@@@{"client_id":"mosq-Lsdo2ZXDVXMuufiS64","username":"","topic":"mcd/11.22.33.44/DEVICE_MESSAGES","payload":"aGVsbG8gaG93IGFyZSB5b3U=","qos":2,"node":"emqx@127.0.0.1","ts":1573645333502}_



The payload seems encrypted . How do i decrypt it to the actual message which i have to use it for further processing.

**Comment by HJianBo** [comment]
@sourjya123 Just increasing the hook No. e,g:
```
bridge.kafka.hook.message.publish.1 ={"filter":"+/+/DEVICE_PROFILE","topic":"DEVICE_PROFILE"}
bridge.kafka.hook.message.publish.2 ={"filter":"+/+/DMS_MESSAGES","topic":"DMS_MESSAGES"}
```

@akshaykootta  The payload will be encoded by `bridge.kafka.encode_payload_type` option.   You should decode it by same method

**Comment by sourjya123** [comment]
So there is no option to stop encoding and pass the same data? If it is encoded by Base64 do I have to decode somewhere or in the config file I can mention the decode part?

**Comment by HJianBo** [comment]
No, It must be encoded by some method. base64 is the default option if you comment it.

The Decode operation should present on the backend of Kafka subscribers

**Comment by sourjya123** [comment]
ok. Another question is:

mosquitto_pub -h localhost -p 1883 -t mcd/11.22.33.44/DEVICE_MESSAGES -q 2 -m "hello how are you"

null@@@{"client_id":"mosq-Lsdo2ZXDVXMuufiS64","username":"","topic":"mcd/11.22.33.44/DEVICE_MESSAGES","payload":"aGVsbG8gaG93IGFyZSB5b3U=","qos":2,"node":"emqx@127.0.0.1","ts":1573645333502}

why kafka subscriber is getting null as key?

**Comment by HJianBo** [comment]
Yes,  E.g:
```
## key:
## Option: ${clientid} | ${username} | ${topic}
## Example: bridge.kafka.hook.message.publish.1 = {"filter":"#", "topic":"MessagePublish", "key":"${topic}"}
```

**Comment by sourjya123** [comment]
null@@@{"client_id":"mosq-Lv6VxbaumMRBzVElXW","username":"","topic":"mcd/11.22.33.44/DEVICE_MESSAGES","payload":"aGVsbG8gaG93","qos":2,"node":"emqx@127.0.0.1","ts":1573716105044}

still I am getting same null after providing 
bridge.kafka.hook.message.publish.1      = {"filter":"+/+/DEVICE_MESSAGES", "topic":"DEVICE_MESSAGES","key":"${topic}"}

Is it proper configuration?

**Comment by sourjya123** [comment]
I am getting now this error when I have multiple publish hook

2019-11-13 23:51:19.850 [error] Producer DEVICE_STATUS-0 (pid = <0.2515.0>) down
reason: {function_clause,
            [{kpro_compress,compress,
                 [compression,
                  [[<<224,1>>,
                    [<<0>>,
                     <<0>>,
                     <<0>>,
                     <<1>>,
                     [<<210,1>>,
                      <<"{\"client_id\":\"mosq-aTxZEloZaZGWsfCY3a\",\"username\":\"undefined\",\"node\":\"emqx@127.0.0.1\",\"ts\":1573717879836}">>],
                     [<<0>>]]]]],
                 [{file,
                      "/emqx_temp/emqx_enterprise_rel/_checkouts/kafka_protocol/src/kpro_compress.erl"},
                  {line,41}]},
             {kpro_batch,encode_tx,4,
                 [{file,
                      "/emqx_temp/emqx_enterprise_rel/_checkouts/kafka_protocol/src/kpro_batch.erl"},
                  {line,78}]},
             {kpro_batch,encode,3,
                 [{file,
                      "/emqx_temp/emqx_enterprise_rel/_checkouts/kafka_protocol/src/kpro_batch.erl"},
                  {line,47}]},
             {kpro_req_lib,produce,5,
                 [{file,
                      "/emqx_temp/emqx_enterprise_rel/_checkouts/kafka_protocol/src/kpro_req_lib.erl"},
                  {line,206}]},
             {wolff_producer,send_to_kafka,1,
                 [{file,
                      "/emqx_temp/emqx_enterprise_rel/_checkouts/wolff/src/wolff_producer.erl"},
                  {line,333}]},
             {wolff_producer,handle_info,2,
                 [{file,
                      "/emqx_temp/emqx_enterprise_rel/_checkouts/wolff/src/wolff_producer.erl"},
                  {line,192}]},
             {gen_server,try_dispatch,4,[{file,"gen_server.erl"},{line,637}]},
             {gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,711}]}]}

**Comment by sourjya123** [comment]
My kafka is working fine. Bridge is also getting loaded properly. But after sending data from emq the data is not reaching to kafka. Saying the above error

**Comment by HJianBo** [comment]
Have you tried to disable compression?

And could you paste all of emqx_bridge_kafka.conf content?

**Comment by sourjya123** [comment]
yes I can paste the conf.. yes I tried the compression once.

**Comment by HJianBo** [comment]
If you want to compression it, you can set it's value with:
```
## no_compression | gzip  | snappy  | lz4
bridge.kafka.producer.compression = no_compression
```

**Comment by sourjya123** [comment]
[emqx_bridge_kafka.txt](https://github.com/emqx/emqx/files/3846028/emqx_bridge_kafka.txt)


As u can see
bridge.kafka.hook.message.publish.1      = {"filter":"+/+/DEVICE_MESSAGES",  "topic":"DEVICE_MESSAGES", "key":"${topic}"}
bridge.kafka.hook.message.publish.2      = {"filter":"+/+/DEVICE_PROFILE",  "topic":"DEVICE_PROFILE", "key":"${topic}"}
bridge.kafka.hook.message.publish.3      = {"filter":"+/+/DMS_MESSAGES",  "topic":"DMS_MESSAGES", "key":"${topic}"}

Will it work like that? 
And key is also not working.

I am getting from the kafka as below
null@@@{"client_id":"mosq-RuisgoAVzS7iooPa5d","username":"","topic":"mcd/11.22.33.44/DEVICE_MESSAGES","payload":"ZnJvbSBFbXE=","qos":2,"node":"emqx@127.0.0.1","ts":1573728102943}

Still the key is null.

**Comment by sourjya123** [comment]
For DEVICE_PROFILE and DMS_MESSAGES I am not getting data from kafka. Is there any wrong configuration for :
bridge.kafka.hook.message.publish.2 = {"filter":"+/+/DEVICE_PROFILE", "topic":"DEVICE_PROFILE", "key":"${topic}"}
bridge.kafka.hook.message.publish.3 = {"filter":"+/+/DMS_MESSAGES", "topic":"DMS_MESSAGES", "key":"${topic}"}

Please let me know.

**Comment by HJianBo** [comment]
In the first, as you have shown in the conf file:
```
bridge.kafka.hook.message.publish.1      = {"filter":"+/+/DEVICE_MESSAGES",  "topic":"DEVICE_MESSAGES", "key":"${topic}"}
bridge.kafka.hook.message.publish.1      = {"filter":"+/+/DEVICE_PROFILE",  "topic":"DEVICE_PROFILE", "key":"${topic}"}
bridge.kafka.hook.message.publish.1      = {"filter":"+/+/DMS_MESSAGES",  "topic":"DMS_MESSAGES", "key":"${topic}"}
``` 

The hooks ID is duplicated, Plz make sure it has been fixed.

After updating the conf file, plz reload it by `emqx_ctl plugins reload emqx_bridge_kafka`

**Comment by sourjya123** [comment]
I made it 1,2,3 and reloaded. But still its not working
And why the key is coming null?

**Comment by HJianBo** [comment]
> Is there any option so I can send data from Kafka to emq?

No, Not supported now. Using another MQTT Client to Produces theses messages may be a good choice now

**Comment by sourjya123** [comment]
Ok. Thanks for the information.

**Comment by sourjya123** [comment]
Can we get this feature from emq?

**Comment by HJianBo** [comment]
Afraid not

**Comment by sourjya123** [comment]
Can we get this feature from emq?

**Comment by sourjya123** [comment]
One question what are the encoding algorithms are available except Base64?

**Comment by HJianBo** [comment]
Only base64 is now supported

**Comment by sourjya123** [comment]
Hi, One question I have. If my micro services are subscribed to Kafka topic and based on load if I scale up those, along with that emq-kafka bridge has to be scaled up? Because if I put all the topic mapping in one config file then based on my micro service I cant scale up each bridge configuration separately.  

eg, let say my micro service is subscribed to DEVICE_PROFILE topic. Based on load I scaled up my micro service.
Now in emq-kafka bridge 3 mappings are available
1. +/+/DEVICE_PROFILE ----> DEVICE_PROFILE
2. +/+/DEVICE_MESSAGES ----> DEVICE_MESSAGES 
3. +/+/DEVICE_STATUS ----> DEVICE_STATUS

So based on my scaling of micro service which is subscribed to DEVICE_PROFILE, I need to scale up the emq-kafka bridge which has mapping 1. Since that configuration all 1,2,3 are present, all will get scaled up when I dont need +/+/DEVICE_MESSAGES ----> DEVICE_MESSAGES this mapping to get scaled up.

Please let me know your suggestion. Or we dont need to scale the plugin since it is a bridge.
