### ISSUE TITLE
Bridge with ssl connection

### ISSUE THREAD

**Issue by FBigardi** [emqx/emqx#3032]
#### Environment

- OS: Ubuntu 16
- Erlang/OTP:  1.22.0.7-1
- EMQ: Version 3.4.1 Relase 3.2

#### Description
I have a remote server with a emqx broker installed and a gateway with a emqx-edge installed. I want to connect the emqx-edge to emqx in bridge but using a SSL connection. My certificate are self-signed. Are there a way to connect emqx-edge with emqx using a ssl connection self signed?

**Comment by terry-xiaoyu** [comment]
@FBigardi 

The emqx-edge is actually a simplified emqx, so bridging edge to emqx is the same as bridging emqx to another emqx. 

Configure the ssl related info in `etc/plugins/emqx_bridge_mqtt.conf` at the emqx-edge side:

https://github.com/emqx/emqx-bridge-mqtt/blob/cc13095bbcb8aa84b17fae167a1235ebd814c687/etc/emqx_bridge_mqtt.conf#L66

And you also need to configure the corresponding ssl info in `emqx.conf` in at the emqx side.
