### ISSUE TITLE
Plugin emqx_auth_username is running，but client can still connect anonymously

### ISSUE THREAD

**Issue by soitif** [emqx/emqx#3037]
#### Environment

- OS: CentOS
- Erlang/OTP: R21/10.3
- EMQ: 3.2.4

#### Description

*A description of the issue*
开启了emqx_auth_username插件，但是还是能够匿名登录
根据描述任何一个认证插件开启，匿名登录就无效了，但是开启emqx_auth_username后，匿名登录好像还是有用的。

**Comment by HJianBo** [comment]
Nope.

The Auth Chain can be described as:

- The Default Authentication Result equal to `allow_anonymous` value
- An **Auth Plugin** will **Ignore** an authentication request if the key not match
- An **Auth Plugin** will **Deny** an authentication request if the password not match
- An **Auth Plugin** will **Aceppt** an authentication request if the key and password is correct
