### ISSUE TITLE
EMQX not working with UTF-16 Path

### ISSUE THREAD

**Issue by Haldoryn** [emqx/emqx#3045]
#### Environment

- OS: Windows 7
- Erlang/OTP: 10.3
- EMQ: v3.2.3

#### Description
I have the EMQX broker installed in a directory with a UTF-16 char.
It will not start the broker and while listing the error shows the install path until this UTF-16 char. 

--> E:\testÖtest\bin\emqx start
Could not load module E:\test
Could not load module E:\test
Could not load module E:\test

**Comment by tigercl** [comment]
Hi, @Haldoryn. We recommend using paths with full English character. I hope it helps you.

**Comment by Haldoryn** [comment]
Yes it helps but that does not fix your bug

**Comment by turtleDeng** [comment]
Sorry, TUF-16 Path is not supported.
