### ISSUE TITLE
emqx_backend_mysql persistence of qos 0

### ISSUE THREAD

**Issue by crom1e** [emqx/emqx#3050]
#### Environment

- OS:  ubuntu 16.04
- Erlang/OTP: 
- EMQ: 3.4.4 EE

#### Description
 I'm using the default plugin conf for mysql, that states QOS > 0 will be stored

```
## Store Publish Message QOS > 0
backend.mysql.hook.message.publish.1     = {"topic": "#", "action": {"function": "on_message_publish"}, "pool": "pool1"}
```
I have a lot of QOS 0 messages i'd like to keep as well. 

Is there a way to store messages with qos>=0 (0, 1 and 2)  with the data persistence plugins?

**Comment by HJianBo** [comment]
What's meaning for **persistence**? 

Did you use to deliver offline messages? or just store these

About the former, the `on_message_publish` function is only storing qos1, qos2 message in any backend* plugins. It is designed for offline messages, so we do not store qos0 messages.

**Comment by crom1e** [comment]
The idea was to store all data passing thru the broker, on all QOS'es. But if this is out of the scope of the backend plugins, I'll figure something else out.

**Comment by HJianBo** [comment]
You can try `on_message_store ` function
```
backend.mysql.hook.message.publish.1     = {"topic": "#", "action": {"function": "on_message_store"}, "pool": "pool1"}
```

**Comment by turtleDeng** [comment]
Thank you for your participation, we talk about closing this issue.
