### ISSUE TITLE
Documentation : User guide for setting up IPv6

### ISSUE THREAD

**Issue by zacsonskaria** [emqx/emqx#3051]
#### Environment

OS: Amazon Linux 2
Erlang/OTP: R21/10.2
EMQ: v3.0.0

#### Description

Can someone post the user guide steps or configurations to use IPv6 on emqx?
Can we use IPv4 and IPv6 simultaneously on the same node? If so, how to configure that?

**Comment by tigercl** [comment]
@zacsonskaria Sorry for the lack of user guide. If you mean device connected to emqx, you should change default `listener.tcp.external = 0.0.0.0:1883` to `listener.tcp.external = ::1:1883` in emqx.conf. If dashboard or HTTP API,  you should setup `*.listener.http.inet6` to true in plugins/emqx_dashboard.conf and plugins/emqx_management.conf.

**Comment by zacsonskaria** [comment]
Thanks @tigercl . Can we use both IPv4 and IPv6 listener simultaneously for a node?

**Comment by tigercl** [comment]
@zacsonskaria Of course. If emqx, making a copy of all `listener.tcp.external.*` items, then replace `external` with `ipv6`(example) and set `listener.tcp.ipv6 = ::1:<Any Port You Want>`, you will get one listener for IPv4 and another for IPv6. If dashboard of HTTP API, just setting `*.listener.http.ipv6_only = false`.

**Comment by ankitgsa** [comment]
@tigercl I'm having trouble connecting over ipv6, I'm unable to even make a connection using ipv6. Can you please provide some documentation? 
![Capture](https://user-images.githubusercontent.com/9132101/69606248-545a6780-0ff0-11ea-930a-6533b74a9111.PNG)
![Capture1](https://user-images.githubusercontent.com/9132101/69606249-545a6780-0ff0-11ea-8caa-d0d19c92677f.PNG)

**Comment by tigercl** [comment]
@zacsonskaria Sorry, WebSocket tool in dashboard don't support IPv6 yet, we will fix it in next version. It is recommended that you use other client tools first, we are sorry for the inconvenience.

**Comment by Gopi-Kasodariya** [comment]
For IPv6 connection, I have changed listener.tcp.external = 0.0.0.0:1883 to listener.tcp.external = ::1:1883 in emqx.conf
But still it is not accepting IPv6 connection.
<img width="1434" alt="Screen Shot 2022-07-06 at 1 58 21 PM" src="https://user-images.githubusercontent.com/73532205/177506116-7d155ec1-caee-4342-819c-b9e78944395f.png">
