### ISSUE TITLE
Client subscribe to topic '#' error

### ISSUE THREAD

**Issue by lexuanloc** [emqx/emqx#3052]
#### Environment

- OS: Ubuntu 18.04
- Erlang/OTP: R22/V10.5
- EMQ: 3.2.3

#### Description
The client wants to receive data from all topics by subscribing to topic '#'. But the subscription is not successful.

**Comment by tigercl** [comment]
@lexuanloc There is default ACL rule in etc/acl.conf:
`{deny, all, subscribe, ["$SYS/#", {eq, "#"}]}.`
It means that emqx refuse all clients to subscribe `#`. If you need a special client to subscribe `#`, You can add `{allow, {client, "ClientID"}, subscribe, [{eq, "#"}]}.` to the front.

**Comment by lexuanloc** [comment]
thanks @tigercl
