### ISSUE TITLE
publish message to a client by clientid?

### ISSUE THREAD

**Issue by mikawudi** [emqx/emqx#3053]
#### Environment

- OS: CentOS7
- Erlang/OTP: 21
- EMQ: 3.2.5

#### Description

i want to publish message to a client by clientid,
now only way is evey client connect to broker than subscribe client/{$clientId}
but when i have million user it will create million topic....it will impact on performance?
any better way to do this?

thanks~

**Comment by mariusstaicu** [comment]
you can use topics like {client-id}/command and send messages straight to that particular client id. 
From what I understand, topics are much more lightweight than connections, so if your broker supports 1 million connections, it will also support 5 million topics.

Someone can correct me if I'm wrong.

**Comment by zhanghongtong** [comment]
@mariusstaicu is right,  @mikawudi you can use it with confidence

**Comment by mikawudi** [comment]
ok~thanks for everyone

**Comment by yecao007** [comment]
是不是可以有什么方案接口可以像socket.io的socket.io :sockets.socket(socketid).emit('message', ' your msg');这样的?
