### ISSUE TITLE
Issue with shared subscription after nodes comes up again which went down earlier.

### ISSUE THREAD

**Issue by jayjamba** [emqx/emqx#3059]
#### Environment

- OS: CentOS Linux 7
- Erlang/OTP: 
- EMQ: 3.2.5

Hi,
I am connecting to emqx cluster through eclipse paho client(mentioned below). Our emqx is deployed on 3 machines (192.168.0.1, 192.168.0.2 and 192.168.0.3) and is clustered.

Through my java code I am publishing message every one minute to one shared topic : $share/mygroup/My-Topic and in that application I have also subscribed to the given shared topic.

I have started 3 instances of my application on 8081, 8082 and 8083. So the message is received on either of the ports i.e. 8081, 8082 or 8083.

Now, I turned off emqx node of 192.168.0.1, but still my application on all 3 ports runs fine - publishing and receiving message every one minute.

I turned off emqx node of 192.168.0.2 and my application on all 3 ports still runs fine - publishing and receiving message every one minute.

**Now my problem starts** when I turn ON emqx node of 192.168.0.1 (it joins the cluster back), here my application publishes to given shared topic but its not received on any of the ports i.e. 8081, 8082 or 8083. The message is getting dropped.

Now, I also turned ON emqx node of 192.168.0.2 (this also joins the cluster back), here again my application still publishes to given shared topic but its not received on any of the ports i.e. 8081, 8082 or 8083. Here also the message is getting dropped.

Not sure if I am missing some config changes in my emqx.conf or in eclipse paho java client.

My Eclipse paho java client is :
public MqttClient getClient() throws MqttException {
	final MqttClient mqttClient = new MqttClient("tcp://192.168.0.1:1883", MqttClient.generateClientId());
	final MqttConnectOptions connectOptions = new MqttConnectOptions();
	connectOptions.setCleanSession(false);
	connectOptions.setAutomaticReconnect(true);
	connectOptions.setServerURIs(new String[] { "tcp://192.168.0.1:1883", "tcp://192.168.0.2:1883", "tcp://192.168.0.3:1883" });
	mqttClient.connect(connectOptions);
	return mqttClient;
}

Changes done in my emqx.conf in all 3 machines are mentioned below, rest all values of properties are the default ones :

node.name=emqx@192.168.0.1 (on 192.168.0.1),
node.name=emqx@192.168.0.2 (on 192.168.0.2),
node.name=emqx@192.168.0.3 (on 192.168.0.3)

node.dist_listen_min = 6369
node.dist_listen_max = 7369

zone.external.max_awaiting_rel = 0
zone.external.await_rel_timeout = 600s

I tried the same scenario with HiveMQ client as well, but the same issue is observed. Below is my HiveMQ client code:

final Mqtt5BlockingClient client = Mqtt5Client.builder().identifier(UUID.randomUUID().toString())
	.serverHost("192.168.0.1").serverPort(1883).addDisconnectedListener(context -> {
		System.out.println(context.getCause());
		context.getReconnector().reconnect(true).delay(5, TimeUnit.SECONDS);
		System.out.println(context.getReconnector().getAttempts());
		if (context.getReconnector().getAttempts() > 5) {
			context.getReconnector().transportConfig().serverHost("192.168.0.2").applyTransportConfig();
		}
	}).buildBlocking();

**Comment by jayjamba** [comment]
Hi,
Did you get a chance to look into this ?

**Comment by tigercl** [comment]
@jayjamba Sorry for late reply. Which node is your application connected to? And if you want to use shared subscription, you need subscribe `$share/:group/:topic` and publish to `:topic`.

**Comment by jayjamba** [comment]
Hi tigercl,
I think you didn't get my problem. I never said I have issues with shared subscription. I am subscribing to the topic as you mentioned and publishing to topic as you mentioned. 
**My problem is** - its not working when I explicitly put my one of the EMQ nodes (of cluster) down, then start that node again. My existing subscribers never receive the message if my node comes up again.
I request you to please read my whole scenario explained in my first post again for more clarification.

Thanks.

**Comment by tigercl** [comment]
@jayjamba Hi, I tried what you said, put one node down and start it again, then my client continue to publish messages and all subscribers receive messages at random. By the way, when a node terminates, all clients connected to that node also disconnect. So you need to reconnect to node after the node is restarted.

**Comment by jayjamba** [comment]
which client do you use to connect ? Can you share the code of your client ? I am using Eclipse Paho Java client. 
Btw clients connected to the node, which really went down, are still Up in my case because it internally connects to the other node which is UP in the cluster and is able to receive the published messages. 
My problem starts when the node gets UP again, so the client which got connected to the other node after the first node's failure also stop receiving messages, which was working fine. I believe the broker is sending messages to some offline clients and hence the messages are getting lost.

**Comment by tigercl** [comment]
@jayjamba This is normal If your publisher is connecting to the dead node:
> so the client which got connected to the other node after the first node's failure also stop receiving messages.

The MQTT client I used is [emqtt](https://github.com/emqx/emqtt/tree/cli). The commands I use are as follows:
```
./emqtt_cli sub -t '$share/group/hello' --protocol-version 5 -h [:host] -p [:port]
./emqtt_cli pub -t 'hello' -q 0 --payload "hello world"
```
