### ISSUE TITLE
Issue with loading emqx_auth_username.conf 

### ISSUE THREAD

**Issue by Utkagr** [emqx/emqx#3060]
#### Environment

- OS: Ubuntu 16.04
- Erlang/OTP: 
- EMQ: v3.2.5

#### Description

We're trying to provide *user authentication* details mentioned below
```
auth.user.1.username="user1" . 
auth.user.1.password="pwd1" . 
```
by replicating them into values_production.yaml file of helm chart like

```
emqxConfig: {
    EMQX_ALLOW_ANONYMOUS : "false",
    EMQX_LOADED_PLUGINS: "emqx_recon,emqx_retainer,emqx_management,emqx_dashboard,emqx_auth_username",
    EMQX_DASHBOARD__DEFAULT_USER__LOGIN : "user1",
    EMQX_DASHBOARD__DEFAULT_USER__PASSWORD : "pwd1"
}
```
But this isn't working as expected. And this issue is not just with the helm or kubernetes thing. 

We used a single host broker of emqx and tried these
- defined the user auth inside the etc/plugins/emqx_auth_username.conf file
- restarted the emqx_ctl (./bin/emqx_ctl restart) 

and still got the following error.
>2019-11-26T14:15:27.280949+05:30 [error] You've tried to set auth.user.1.username, but there is no setting with that name.
2019-11-26T14:15:27.281066+05:30 [error] Did you mean one of these?
2019-11-26T14:15:27.328039+05:30 [error] auth.mysql.username
2019-11-26T14:15:27.328090+05:30 [error] auth.pgsql.username
2019-11-26T14:15:27.328127+05:30 [error] mqtt.sn.username
2019-11-26T14:15:27.328311+05:30 [error] You've tried to set auth.user.1.password, but there is no setting with that name.
2019-11-26T14:15:27.328358+05:30 [error] Did you mean one of these?
2019-11-26T14:15:27.423364+05:30 [error] auth.redis.password
2019-11-26T14:15:27.423469+05:30 [error] auth.mongo.password
2019-11-26T14:15:27.423555+05:30 [error] auth.mysql.password
2019-11-26T14:15:27.476735+05:30 [error] Error generating configuration in phase transform_datatypes
2019-11-26T14:15:27.476881+05:30 [error] Conf file attempted to set unknown variable: auth.user.1.password
2019-11-26T14:15:27.476948+05:30 [error] Conf file attempted to set unknown variable: auth.user.1.username

Any help would be appreciated!

Reference [doc](https://docs.emqx.io/tutorial/v3/en/security/auth.html#authentication-and-authentication-chain)

**Comment by alexandrim0** [comment]
Hi there!

I has found the same issue. I seems, like that syntax does not work anymore, at least from version 3.

**Comment by HJianBo** [comment]
Hi guys,  we forget to update the Authentication documents

After the v3.1-rc.2, the feature of default users defined at `emqx_auth_username.conf` has been removed.

So, it just supports creating users by [REST APIs](https://github.com/emqx/emqx-auth-username) now

**Comment by Utkagr** [comment]
Hi HJianBo, I wonder why it was removed in the first place. Did it have security-related issues? 
Also, now that the authentication is only possible via REST APIs, it does bring integration challenges with kubernetes and what not, right? Any developments on that front to make the process easier? Thanks

**Comment by rasaffie** [comment]
You can find more info on this issue: https://github.com/emqx/emqx-auth-username/issues/98

**Comment by HJianBo** [comment]
Hi, @Utkagr We restore this feature at v3.2.7 and we will update the references docs.

Thanks for your contribution!

**Comment by alexandrim0** [comment]
Thank you!
Now it works as expected!

**Comment by alexandrim0** [comment]
As I can see while emqx starts the entrypoint bash script parse only 3 of 6.
I`m using emqx in docker. So I checked config file inside of container and there only 3 users.

.env like this and also I had try exactly the same:
EMQX_AUTH__USER__PASSWORD_HASH=plain
EMQX_AUTH__USER__1__USERNAME=user1
EMQX_AUTH__USER__1__PASSWORD=password1
EMQX_AUTH__USER__2__USERNAME=user2
EMQX_AUTH__USER__2__PASSWORD=password2
EMQX_AUTH__USER__3__USERNAME=user3
EMQX_AUTH__USER__3__PASSWORD=password3
EMQX_AUTH__USER__4__USERNAME=user4
EMQX_AUTH__USER__4__PASSWORD=password4

**Comment by HJianBo** [comment]
Yes, the defect is because of the default of the `emqx_auth_username.conf` only 3 pairs:

```confs
## Examples:
##auth.user.1.username = admin
##auth.user.1.password = public
##auth.user.2.username = feng@emqtt.io
##auth.user.2.password = public
##auth.user.3.username = name~!@#$%^&*()_+
##auth.user.3.password = pwsswd~!@#$%^&*()_+
```

**The ENV just rigidly modify the existed lines, rather than add more new lines** So, it can not set beyond 3 pair usernames.

A workaround method is that you can mount a wannted `emqx_auth_username.conf` to  the emqx container
