### ISSUE TITLE
Node 'emqx@127.0.0.1' not responding to pings.

### ISSUE THREAD

**Issue by doncici** [emqx/emqx#3061]
#### Environment

- OS: 
- Erlang/OTP: 
- EMQ: 

#### Description

*A description of the issue*

after install the emq.rpm ,input **emqx start** 
**it returned emqx v3.2.2 is started successfully!**

but when I input **emqx_ctl status**
It returned **Node 'emqx@127.0.0.1' not responding to pings.**

then I input **emqx console**
it returned  **2019-11-27 11:00:35.087 [critical] The license certificate is e
xpired! System shutdown!**
![image](https://user-images.githubusercontent.com/58241861/69689974-506c3980-1105-11ea-9191-04c541fa9266.png)

**Comment by turtleDeng** [comment]
EMQX EnterprisePlease apply for trial version license on the official website

**Comment by doncici** [comment]
> EMQX EnterprisePlease apply for trial version license on the official website

thanks a lot ,dude

**Comment by doncici** [comment]
> EMQX EnterprisePlease apply for trial version license on the official website
兄弟，杭州的啊，我这里部署后又遇到一个新问题，
两台部署broker版本，然后集群，
现在一台部署的没有问题，
另一台，启动后，用emqx_ctl 就报下面这样的回复
![image](https://user-images.githubusercontent.com/58241861/69706561-f1251e00-1132-11ea-80a8-f3dd880aebd0.png)
然后控制台也不正常，用rpm 和zip都安装了，一样，报以上一样的错误，麻烦指点一下，谢谢

**Comment by doncici** [comment]
> EMQX EnterprisePlease apply for trial version license on the official website
解决了，8080端口占用
