### ISSUE TITLE
kick out connection not working

### ISSUE THREAD

**Issue by xlb0479** [emqx/emqx#3062]
#### Environment

- OS: 
- Erlang/OTP: 
- EMQ: 

#### Description

1. I use `emqx_ctl clients kick` with exit code 0 but connection still alive(heartbeat bytes captured)
2. I use emq management api `DELETE /api/v3/connections/:clientid` with http 500 and server log as follow:
`2019-11-27 15:27:06.302 [error] DELETE /api/v3/connections/mqttjs_146d7e1695 error: function_clause, stacktrace:
[{emqx_mgmt,return,
            [{error,not_found}],
            [{file,"src/emqx_mgmt.erl"},{line,454}]},
 {minirest_handler,dispatch,3,[{file,"src/minirest_handler.erl"},{line,55}]},
 {minirest,handle_request,2,[{file,"src/minirest.erl"},{line,66}]},
 {minirest,init,2,[{file,"src/minirest.erl"},{line,51}]},
 {cowboy_handler,execute,2,[{file,"src/cowboy_handler.erl"},{line,37}]},
 {cowboy_stream_h,execute,3,[{file,"src/cowboy_stream_h.erl"},{line,274}]},
 {cowboy_stream_h,request_process,3,
                  [{file,"src/cowboy_stream_h.erl"},{line,252}]},
 {proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,249}]}]`

**Comment by HJianBo** [comment]
Hi, @xlb0479 Which version do you use?

**Comment by HJianBo** [comment]
Hi, @xlb0479 We can't reproduce it. It should work well in the 4.x

Thanks for your feedback. let me know if there are any problems
