### ISSUE TITLE
emqx3.2.2 fail to start

### ISSUE THREAD

**Issue by 52HZWU** [emqx/emqx#3065]
#### Environment

- OS: maxOS
- Erlang/OTP: 
- EMQ: 

#### Description
![image](https://user-images.githubusercontent.com/53888910/69849100-c663d280-12b6-11ea-90c0-bc609b44cdb0.png)

 openssl   2.8.3

**Comment by HJianBo** [comment]
Hi @52HZWU It started successfully on my mac:

```
- openssl: LibreSSL 2.8.3
- OS: macos10.15
```

You can try to execute the following cmd to make sure the crypto.so can be loaded
```bash
cd emqx-3.2.2
otool -L lib/crypto-4.4.1/priv/lib/crypto.so
```

**Comment by 52HZWU** [comment]
Hi @HJianBo  I tried it as you said, or did it fail.
<img width="1440" alt="截屏2019-11-30下午6 41 04" src="https://user-images.githubusercontent.com/53888910/69899462-66962600-13a1-11ea-9c0a-62e98b763fde.png">

**Comment by HJianBo** [comment]
The crypto.so seems to can be loaded correctly.  it must have some unknown wrongs on there.

Have you tried to use `openssl v1.1.1` instead of  `LibreSSL 2.8.3`?

**Comment by cbz** [comment]
Seeing the same error:

```
[aas@shrimp:/opt/emqx$ ./bin/emqx console
Exec: /opt/emqx/erts-10.1/bin/erlexec -boot /opt/emqx/releases/v4.0-beta.4/emqx -mode embedded -boot_var ERTS_LIB_DIR /opt/emqx/erts-10.1/../lib -mnesia dir "/opt/emqx/data/mnesia/emqx@127.0.0.1" -config /opt/emqx/data/configs/app.2019.12.03.14.52.51.config -args_file /opt/emqx/data/configs/vm.2019.12.03.14.52.51.args -vm_args /opt/emqx/data/configs/vm.2019.12.03.14.52.51.args -start_epmd false -epmd_module ekka_epmd -proto_dist ekka -- console
Root: /opt/emqx
/opt/emqx
Erlang/OTP 21 [erts-10.1] [source] [smp:4:4] [ds:4:4:10] [async-threads:32]

Starting emqx on node emqx@127.0.0.1
[os_mon] memory supervisor port (memsup): Erlang has closed
[os_mon] cpu supervisor port (cpu_sup): Erlang has closed
{"Kernel pid terminated",application_controller,"{application_start_failure,emqx,{bad_return,{{emqx_app,start,[normal,[]]},{'EXIT',{{badmatch,{error,{shutdown,{failed_to_start_child,emqx_kernel_sup,{shutdown,{failed_to_start_child,emqx_metrics,{undef,[{counters,new,[1024,[write_concurrency]],[]},{emqx_metrics,init,1,[{file,\"/tmp/emqx-rel/_checkouts/emqx/src/emqx_metrics.erl\"},{line,359}]},{gen_server,init_it,2,[{file,\"gen_server.erl\"},{line,374}]},{gen_server,init_it,6,[{file,\"gen_server.erl\"},{line,342}]},{proc_lib,init_p_do_apply,3,[{file,\"proc_lib.erl\"},{line,249}]}]}}}}}}},[{emqx_app,start,2,[{file,\"/tmp/emqx-rel/_checkouts/emqx/src/emqx_app.erl\"},{line,34}]},{application_master,start_it_old,4,[{file,\"application_master.erl\"},{line,277}]}]}}}}}"}
Kernel pid terminated (application_controller) ({application_start_failure,emqx,{bad_return,{{emqx_app,start,[normal,[]]},{'EXIT',{{badmatch,{error,{shutdown,{failed_to_start_child,emqx_kernel_sup,{sh

Crash dump is being written to: log/crash.dump...done
```

```
haas@shrimp:/opt/emqx$  openssl version
OpenSSL 1.1.1  11 Sep 2018
```

**Comment by HJianBo** [comment]
Not exactly, the newer reported error is
```
{failed_to_start_child,emqx_metrics,{undef,[{counters,new,[1024 ...
```

you should use OTP 22 to compile it, not 21

**Comment by 52HZWU** [comment]
hi @HJianBo  I have another problem here，During ACL_http authentication，Can still post messages if authentication fails


![image](https://user-images.githubusercontent.com/53888910/70145985-34a3fd00-16dc-11ea-9ca0-f9663d640bf5.png)


![image](https://user-images.githubusercontent.com/53888910/70146026-4f767180-16dc-11ea-8e87-29775cf9efdf.png)

![image](https://user-images.githubusercontent.com/53888910/70146044-5b623380-16dc-11ea-92ea-22d966c3d43a.png)

It was published successfully。

**Comment by 52HZWU** [comment]
Already understand the problem
