### ISSUE TITLE
Can the inbuilt ACL (say MongoDB or Redis extensions) be circumvented?

### ISSUE THREAD

**Issue by utkarshns** [emqx/emqx#3066]
#### Environment

- OS: CentOS 7 
- Erlang/OTP: 21
- EMQ: 3.2.2

#### Concern
With proper configuration is it possible to probably punch hole in the security layer of emq?
How robustly is the ACL and AUTH thing tested by the emqx team?

PS: So far, I haven't faced any malfunctions or unexpected auth ever. Just curious.

**Comment by tigercl** [comment]
@utkarshns Each of our authentication plug-ins has associated test cases.
