### ISSUE TITLE
Why does emqx takes 12 minutes to startup?

### ISSUE THREAD

**Issue by alexe100** [emqx/emqx#3067]
#### Environment

- OS: ubuntu 18
- Erlang/OTP: 22
- EMQ: emqx-ubuntu16.04-v3.0.0_amd64.deb

#### Description

I have setup a 2 node cluster on ubuntu18 boxes with nginx L.B. and it works... If I stop one of the emqx nodes the service continues ok. however, it I stop both emqx nodes and then if I start just one of the two emqx nodes,  the messaging service will just be availabel again more or less 12 minutes later (no manual intervention, just stop machines and start ne of them and wait for the service using mosquitto_pub/sub clients).

To be sure about the time taken to startup, I reset a emqx machine and then I ssh into it and executed command:
$sudo lsof -i -P -n | grep LISTEN
and port 1883 starts to listen more or less 12 minuts after boot.

How to accelerate emqx boot?

PS: if instead stop both machines and start just one I reset both machines then the service is available soon. It seems that problem just happen when the emqx cluster is make with just one machine (after stop both)

Thanks a lot
Alex

**Comment by HJianBo** [comment]
Hi, @alexe100 I guess the 99% time-consuming used to discover other nodes of the cluster

Which cluster strategy do you use?

**Comment by HJianBo** [comment]
Close it due to outdated.

Please reopen it if you have any updates
