### ISSUE TITLE
不能下发hex  数据

### ISSUE THREAD

**Issue by allenhan** [emqx/emqx#3097]
#### Environment

- OS: 
- Erlang/OTP: 
- EMQ: 2.3.11

#### Description

下发设备将数据转成hex 发给emq，发现订阅端收不到。
dashboard的 界面统计接收包那一项 也未发现有统计到。所以是不是emq 收到hex的时候出现问题了？

**Comment by allenhan** [comment]
ps：emq log 未发现任何报错

**Comment by terry-xiaoyu** [comment]
emqx won't parse the mqtt payload. You could capture the packages to see if they are sent to emqx  using network analysing tools like tcpdump.
