### ISSUE TITLE
Can I write as   {allow, {user, "%u"}, subscribe, "test/%u"}.   in etc/acl.conf?Why not supported?

### ISSUE THREAD

**Issue by emqxuserwhh** [emqx/emqx#3101]
Can I write as   {allow, {user, "%u"}, subscribe, "test/%u"}.   in etc/acl.conf?Why not supported?

**Comment by tigercl** [comment]
@emqxuserwhh Sorry, we don't support this feature yet. We'll let you know when we're ready to implement it.

**Comment by emqxuserwhh** [comment]
Thanks!



---Original---

**Comment by wivwiv** [comment]
@emqxuserwhh 

```
{allow, all, subscribe, ["test/%u"]}.
{deny, all, subscribe, ["test/+"]}.
```

**Comment by and-dzh3** [comment]
@wivwiv It's not working solution 
and this Feature will be very helpful

**Comment by and-dzh3** [comment]
@wivwiv Can you please explain this syntax ?

**Comment by wivwiv** [comment]
@and-dzh3 
The rule is from bottom to top for reading.

```bash
# 2. Allow all users from sub to `test/%u` , Devices can sub to topics with their own username.
{allow, all, subscribe, ["test/%u"]}.

# 1. Deny all users from sub to `test/+`. So, one device cannot sub to another device's topic.
{deny, all, subscribe, ["test/+"]}.
```

So, the `emqx_user_1` can't sub to `test/emqx_user_2`、`test/emqx_user_3` but 
 `test/emqx_user_1`.

**Comment by and-dzh3** [comment]
@wivwiv Thanks, and same structure works for publishing?

**Comment by wivwiv** [comment]
Yes, change subscribe to `pubsub` or `publish`. And test it a few more times and you'll use it
