### ISSUE TITLE
/api/v3/mqtt/publish  push display success,but don't find topic in Dashboard

### ISSUE THREAD

**Issue by phyzhou** [emqx/emqx#3104]
#### Environment

- OS: CentOS6.5 / Win10
- Erlang/OTP:  R21/10.3
- EMQ: 4.0-rc.1

#### Description
Request : 
URL :http://127.0.0.1:8081/api/v3/mqtt/publish
Authorization : Basic Auth, create an application in Dashboard, use APPID,and APPSecret
Body:
{
  "topic": "test/123",
  "payload": "hello",
  "qos": 2,
  "retain": false,
  "client_id": "client_ab9069449e1212"
}

Response:
{
    "code": 0
}

Then login  Dashboard with admin/public
Click the column of Topics
But none topic .

**Comment by phyzhou** [comment]
![TIM截图20191213151839](https://user-images.githubusercontent.com/4231707/70778337-03eb5400-1dbd-11ea-91b2-eb2da43e2ba4.png)

![image](https://user-images.githubusercontent.com/4231707/70778419-35641f80-1dbd-11ea-9997-dc4bd5959b3f.png)

**Comment by tigercl** [comment]
@phyzhou If you want to subscribe to a topic, you should use `api/v3/mqtt/subscribe` rather than `api/v3/mqtt/publish`.

**Comment by turtleDeng** [comment]
Thank you for your participation, we will close this issue.
