### ISSUE TITLE
Remove the 'sessions.persistent.count', 'sessions.persistent.max' stats

### ISSUE THREAD

**Issue by emqplus** [emqx/emqx#3109]
#### Environment

- OS: ALL
- Erlang/OTP: R21+
- EMQ: 4.0-rc.1+

#### Description

The 'sessions.persistent.count', 'sessions.persistent.max' stats should be removed in v4.0 release

**Comment by turtleDeng** [comment]
Thanks for your feedback, we have removed in emqx-v4.0-rc.3.
