### ISSUE TITLE
Add port number to http auth tokens

### ISSUE THREAD

**Issue by Eric24** [emqx/emqx#3118]
A feature request: It would be useful to have the port number the connection came in on as one of the tokens available to the http auth plugin. This would allow authorization to be dependent upon whether the client connected on a plain or SSL port.

**Comment by HJianBo** [comment]
Obviously, it is. @Eric24 Thanks very much for your suggestion.

We plan to implement it at 4.0.rc.3 in the emqx_auth_http plugin.

**Comment by HJianBo** [comment]
Hi, @Eric24 we have released v4.0-rc.3. Please check the `etc/plugins/emqx_auth_http.conf`
