### ISSUE TITLE
EMQX Edge Bridge keepalive configure

### ISSUE THREAD

**Issue by BananaGorilla98** [emqx/emqx#3119]
#### Environment

- OS: Raspbian-buster
- Erlang/OTP: 
- EMQ: 

#### Description

*A description of the issue*
Hi. I am currently using EMQX Edge for my project and I have faced this bug while I was configuring emqx_bridge_mqtt.conf file. 

There is an option for keepalive and it is 60s by default. When I connected my edge to the broker, the keepalive changed to 60000s. The keepalive changed back to 60s when the keepalive option is set to 0.06s in the configure file. :')

May I know if this bug can be fixed since it is quite confusing when configuring the edge? Thanks in advanced.

**Comment by turtleDeng** [comment]
keepalive value must be an integer + unit
## d-day
## h-hour
## m-minute
## s-second
## ms-milliseconds

**Comment by turtleDeng** [comment]
Thanks for your feedback, we have fixed it in v4.0-rc.3.
