### ISSUE TITLE
EMQX Edge fails to start bridge

### ISSUE THREAD

**Issue by BananaGorilla98** [emqx/emqx#3120]
#### Environment

- OS: Raspbian-buster
- Erlang/OTP: 
- EMQ: EMQX Edge v3.2.7

#### Description

Hi. I am currently using EMQX Edge for my project. The EMQX Edge was installed in my Raspberry pi 4. The bridge connection to my EMQX Broker was working perfectly until I shutdown-ed without stopping the EMQX Edge. The bridge failed to start after I turned on the Rpi again. The attached screenshot is from the log about the failure.

![微信图片_20191218145449](https://user-images.githubusercontent.com/54273658/71062812-6326db00-21a6-11ea-9fb7-1189f4983956.png)

This problem has been solved after deleting the files in /var/lib/emqx/emqx_aws_bridge/. The bridge started normally and worked again. May I know if this bug can be fixed since I need to shut down my Rpi without stop the EMQX Edge in my project? 

Thanks in advance and have a nice day.

**Comment by turtleDeng** [comment]
Sorry, you can't see the reason in the log, you can turn on the debug log.

**Comment by turtleDeng** [comment]
We have optimized the edge a lot in emqx4.X, it is recommended that you use the latest 4.0.6, we will close this issue, if there are any problems, you can reopen.
