### ISSUE TITLE
How do I implement synchronization requests based on applications and devices

### ISSUE THREAD

**Issue by lingkejia** [emqx/emqx#3121]
#### Environment

- OS: 
- Erlang/OTP: 
- EMQ: 

#### Description

*A description of the issue*

基于EMQX服务能否实现应用端访问设备端某个服务主题同步等待请求结果？

**Comment by HJianBo** [comment]
Obviously not. The MQTT protocol is an async PUB/SUB mechanism, but the MQTT protocol is not good at this scenario.

But, there is a workaround solution to implement your sync waiting logic over the MQTT layer

For example:

```
func fetch_device_state(DeviceId) {

     send_subscribe_request_to_broker("topic/of/response/" ++ DeviceId);
     send_request_publish_to_broker("topic/of/request/" ++ DeviceId);
     
     Result = block_process_and_waiting_response();

     // another process wake me

     return Result; 
}

```
