### ISSUE TITLE
Modify topic before retransmit

### ISSUE THREAD

**Issue by Zhang-Xianglong** [emqx/emqx#3123]
#### Environment

- OS: 
- Erlang/OTP: 
- EMQ: v3.2.3

#### Description

Hi, is there a way to modify topic before retransmit in configuration, such as publish or bridge. Thanks.

**Comment by HJianBo** [comment]
No, there are not any plugins to implement it.

According to the MQTT protocol,  the duplicated flag of PUBLISH will be set to 1 if it retransmits.  Maybe it helps you
