### ISSUE TITLE
can emqx-edge-raspbian10-v4.0-rc.2 support dashboard?

### ISSUE THREAD

**Issue by HBProlove** [emqx/emqx#3124]
#### Environment
1、raspberry pi 4B
2、raspbian10

- OS: 
- Erlang/OTP: 
- EMQ: 

#### Description

*A description of the issue*

**Comment by tigercl** [comment]
Sorry, this feature is not currently supported

**Comment by tigercl** [comment]
@HBProlove This feature will be supported in the next release.

**Comment by HBProlove** [comment]
When can the next version be released ?
 



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "tigercl"<notifications@github.com&gt;; 
发送时间: 2019年12月20日(星期五) 下午3:50
收件人: "emqx/emqx"<emqx@noreply.github.com&gt;; 
抄送: "PROLOVE"<250304692@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [emqx/emqx] can emqx-edge-raspbian10-v4.0-rc.2 support dashboard? (#3124)




@HBProlove This feature will be supported in the next release.

**Comment by tigercl** [comment]
@HBProlove Next week ^-^

**Comment by HBProlove** [comment]
look forward to using , thanks .

 



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "tigercl"<notifications@github.com&gt;; 
发送时间: 2019年12月20日(星期五) 下午4:19
收件人: "emqx/emqx"<emqx@noreply.github.com&gt;; 
抄送: "PROLOVE"<250304692@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [emqx/emqx] can emqx-edge-raspbian10-v4.0-rc.2 support dashboard? (#3124)




@HBProlove Next week ^-^

**Comment by turtleDeng** [comment]
Thank you for your participation, already supported in v4.0-rc.3.
