### ISSUE TITLE
topic filter issue

### ISSUE THREAD

**Issue by feiyanke** [emqx/emqx#3125]
#### Environment

- OS: CentOS 7
- EMQ: 3.2.7

#### Description
I use only **one** client to subscribe two topic filter: `/device1/+`  and `/+/event` .
Then another client pulich message of topic `/device1/event` . 
And then, the subscriber received **two same** messages of topic `/device1/event` . 

The question is:
In this kind of case, the broker found one topic matched more than one topic filter of one client,
the expected behavior is: just publish the topic message to the client **only once**, and let client itself to disptch the message to the related topic listeners. 
I have tested this case with the HiveMQ, which behave match above exactly.

If the broker publish the message more than once, whatever the qos is, the client actually can not know how many times the publisher make the message. It doesn't make sense.

**Comment by tigercl** [comment]
@feiyanke I don't think the broker should try to predict the behavior of the client. Each subscription on the client should be independent. All you need is one message, but others may wonder that they've subscribed to two topics and received only one message. You should redesign the topics to suit your needs.

**Comment by feiyanke** [comment]
But If I receive two same messages, how can I know which is for `/device1/+` and which is for `/+/event` .

**Comment by HJianBo** [comment]
You can't distinguish these. So It is necessary for the subscriber to create independent subscription relationship

**Comment by tigercl** [comment]
@feiyanke Maybe you can use `Subscription Identifier` in MQTT v5.0 for your purpose, and we will introduce this feature in the emqx v4.1.0.

**Comment by HJianBo** [comment]
Because the problem has been resolved, so closed the issue.

Please reopen it if you have any problems
