### ISSUE TITLE
duplicate subscribe

### ISSUE THREAD

**Issue by manbusky** [emqx/emqx#3127]
- OS: 
- EMQ: 2.3.11

Found duplicate subscription  from one client on EMQ dashboard, and found  
missed some message over this subscription at the same time.   

QoS:              1
topicFilter:    $share/groupName/+/parent/child

But could not multiple appearance again now.

Question: Why would duplicate subscriptions be allowed at some time ?

**Comment by HJianBo** [comment]
Nope, The current system is not allowed duplicated subscription for a client id. Could you give more detials to reproduce it ? Thanks

**Comment by manbusky** [comment]
I found duplicated subscriptions with the same filter in the EMQ dashboard according to the client id, but unfortunately I forgot to leave a screenshot. At that time, because I found that the some message was lost, so I restarted the subscriber service and then the service returned to normal;

I'm not sure if this version (2.3.11)  have such a bug. So share it for everyone to discuss.

**Comment by HJianBo** [comment]
After a discussion with other team members, it seems a legacy problem at v2.3.11.

Our current efforts are focused on the 4.0 release, so 2.x is no longer being maintained. So you could upgrade the emqx to v3.27

**Comment by manbusky** [comment]
will upgrade to v3.2.7.
