### ISSUE TITLE
Question: how to handle same client_id connect event

### ISSUE THREAD

**Issue by leaxoy** [emqx/emqx#3131]
If first connect a client with client id a, then connect another client also with client id a, how emqx deal with?

1. Invalidate first client, then use second client.
2. Ack not valid client id to second client.

**Comment by tigercl** [comment]
@leaxoy The first. You can try it yourself.

**Comment by leaxoy** [comment]
@tigercl  Thank you a lot, I tried previously to find the code refer this but failed .

**Comment by leaxoy** [comment]
Another question, when to check ACL?
1. every time when publish msg.
2. at regular intervals.

**Comment by HJianBo** [comment]
Hi, @leaxoy Thanks for your attention here, but about these questions you can see our documentation and try it:https://docs.emqx.io/broker/v3/cn/

It is a more fast way to figure out these.
