### ISSUE TITLE
how to  modify  size for erlang.log

### ISSUE THREAD

**Issue by 907474646** [emqx/emqx#3132]
#### Environment

- OS: linux
- Erlang/OTP: 20/9.1
- EMQ:2.3.11 

#### Description

*A description of the issue*

Refer to  document ,we can find the way to modify  the size for console.log   by modify emq.conf with log.console.size = 1048576000,but how to modify the size for erlang.log ?Did you have one who can help me ?

**Comment by HJianBo** [comment]
Hi, @907474646  In actually, the `erlang.log` files are written by Erlang VM. 

You can change it with :
```
RUN_ERL_LOG_MAXSIZE=1073741824
export RUN_ERL_LOG_MAXSIZE
```

about the more information, you can see http://erlang.org/doc/man/run_erl.html

**Comment by 907474646** [comment]
> Hi, @907474646 In actually, the `erlang.log` files are written by Erlang VM.
> 
> You can change it using the following envs, then restart emqx :
> 
> ```
> RUN_ERL_LOG_MAXSIZE=1073741824
> export RUN_ERL_LOG_MAXSIZE
> ```
> 
> about the more information, you can see http://erlang.org/doc/man/run_erl.html

Many thanks !
