### ISSUE TITLE
emqx_kafka_bridge,Failed to execute

### ISSUE THREAD

**Issue by JoshRong** [emqx/emqx#3133]
#### Environment

- OS: 
- Erlang/OTP: 
- EMQ: 4.0-rc.3

#### emqx_kafka_bridge

*A description of the issue*
When I execute the "emqx console" command, the emqx Kafka bridge will report an error,
How can I solve this problem

Failed to execute {fun emqx_kafka_bridge:on_client_connected/4,
                           [[{bridges,[{bootstrap_broker_host,"localhost"},
                                       {bootstrap_broker_port,9092},
                                       {query_api_versions,false},
                                       {reconnect_cool_down_seconds,10},
                                       {producer_partition,1}]}]]}([#{anonymous =>
                                                                          true,
                                                                      auth_result =>
                                                                          success,
                                                                      clientid =>
                                                                          <<"josh1577170534686">>,
                                                                      is_bridge =>
                                                                          false,
                                                                      is_superuser =>
                                                                          false,
                                                                      mountpoint =>
                                                                          undefined,
                                                                      peercert =>
                                                                          nossl,
                                                                      peerhost =>
                                                                          {116,
                                                                           252,
                                                                           173,
                                                                           101},
                                                                      protocol =>
                                                                          mqtt,
                                                                      sockport =>
                                                                          1883,
                                                                      username =>
                                                                          undefined,
                                                                      zone =>
                                                                          external},
                                                                    0,
                                                                    #{clean_start =>
                                                                          true,
                                                                      clientid =>
                                                                          <<"josh1577170534686">>,
                                                                      conn_mod =>
                                                                          emqx_connection,
                                                                      conn_props =>
                                                                          undefined,
                                                                      connected_at =>
                                                                          1577170535,
                                                                      expiry_interval =>
                                                                          0,
                                                                      keepalive =>
                                                                          10,
                                                                      peercert =>
                                                                          nossl,
                                                                      peername =>
                                                                          {{116,
                                                                            252,
                                                                            173,
                                                                            101},
                                                                           52653},
                                                                      proto_name =>
                                                                          <<"MQTT">>,
                                                                      proto_ver =>
                                                                          4,
                                                                      receive_maximum =>
                                                                          32,
                                                                      sockname =>
                                                                          {{172,
                                                                            16,
                                                                            85,
                                                                            165},
                                                                           1883},
                                                                      socktype =>
                                                                          tcp,
                                                                      username =>
                                                                          undefined}]): {function_clause,
                                                                                         [{emqx_kafka_bridge,
                                                                                           on_client_connected,
                                                                                           [#{anonymous =>
                                                                                               true,
                                                                                              auth_result =>
                                                                                               success,
                                                                                              clientid =>
                                                                                               <<"josh1577170534686">>,
                                                                                              is_bridge =>
                                                                                               false,
                                                                                              is_superuser =>
                                                                                               false,
                                                                                              mountpoint =>
                                                                                               undefined,
                                                                                              peercert =>
                                                                                               nossl,
                                                                                              peerhost =>
                                                                                               {116,
                                                                                                252,
                                                                                                173,
                                                                                                101},
                                                                                              protocol =>
                                                                                               mqtt,
                                                                                              sockport =>
                                                                                               1883,
                                                                                              username =>
                                                                                               undefined,
                                                                                              zone =>
                                                                                               external},
                                                                                            0,
                                                                                            #{clean_start =>
                                                                                               true,
                                                                                              clientid =>
                                                                                               <<"josh1577170534686">>,
                                                                                              conn_mod =>
                                                                                               emqx_connection,
                                                                                              conn_props =>
                                                                                               undefined,
                                                                                              connected_at =>
                                                                                               1577170535,
                                                                                              expiry_interval =>
                                                                                               0,
                                                                                              keepalive =>
                                                                                               10,
                                                                                              peercert =>
                                                                                               nossl,
                                                                                              peername =>
                                                                                               {{116,
                                                                                                 252,
                                                                                                 173,
                                                                                                 101},
                                                                                                52653},
                                                                                              proto_name =>
                                                                                               <<"MQTT">>,
                                                                                              proto_ver =>
                                                                                               4,
                                                                                              receive_maximum =>
                                                                                               32, 
                                                                                              sockname =>
                                                                                               {{172,
                                                                                                 16,
                                                                                                 85,
                                                                                                 165},
                                                                                                1883},
                                                                                              socktype =>
                                                                                               tcp,
                                                                                              username =>
                                                                                               undefined},
                                                                                            [{bridges,
                                                                                              [{bootstrap_broker_host,
                                                                                                "localhost"},
                                                                                               {bootstrap_broker_port,
                                                                                                9092},
                                                                                               {query_api_versions,
                                                                                                false},
                                                                                               {reconnect_cool_down_seconds,
                                                                                                10},
                                                                                               {producer_partition,
                                                                                                1}]}]],
                                                                                           [{file,
                                                                                             "/home/emqx-rel/_checkouts/emqx_kafka_bridge/src/emqx_kafka_bridge.erl"},
                                                                                            {line,
                                                                                             114}]},
                                                                                          {emqx_hooks,
                                                                                           safe_execute,
                                                                                           2,
                                                                                           [{file,
                                                                                             "/home/emqx-rel/_checkouts/emqx/src/emqx_hooks.erl"},
                                                                                            {line,
                                                                                             164}]},
                                                                                          {emqx_hooks,
                                                                                           do_run,
                                                                                           2,
                                                                                           [{file,
                                                                                             "/home/emqx-rel/_checkouts/emqx/src/emqx_hooks.erl"},
                                                                                            {line,
                                                                                             130}]},
                                                                                          {emqx_channel,
                                                                                           return_connack,
                                                                                           2,
                                                                                           [{file,
                                                                                             "/home/emqx-rel/_checkouts/emqx/src/emqx_channel.erl"},
                                                                                            {line,
                                                                                             631}]},
                                                                                          {emqx_connection,
                                                                                           with_channel,
                                                                                           3,
                                                                                           [{file,
                                                                                             "/home/emqx-rel/_checkouts/emqx/src/emqx_connection.erl"},
                                                                                            {line,
                                                                                             535}]},
                                                                                          {emqx_connection,
                                                                                           process_msg,
                                                                                           3,
                                                                                           [{file,
                                                                                             "/home/emqx-rel/_checkouts/emqx/src/emqx_connection.erl"},
                                                                                            {line,
                                                                                             282}]},
                                                                                          {proc_lib,
                                                                                           wake_up,
                                                                                           3,
                                                                                           [{file,
                                                                                             "proc_lib.erl"},
                                                                                            {line,
                                                                                             259}]}]}

**Comment by turtleDeng** [comment]
Sorry, emqx_kafka_bridge is unofficial and cannot help you.
