### ISSUE TITLE
Distinguish of connected and disconnected state.

### ISSUE THREAD

**Issue by sourjya123** [emqx/emqx#3134]
#### Environment

- OS: 
- Erlang/OTP: 
- EMQ: 

#### Description

*A description of the issue*

Hi 
Using emq_bridge_kafka I can get data to client_connected and client_disconnected when device goes online and offline. 

when client goes online in client_connected topic I am getting below data:

{"client_id":"Sourjya","username":"undefined","node":"emqx@127.0.0.1","ts":1577100657608}

But from this data how can I distinguish that this client is online?

Based on the data I need to show online status in html page. So I want some payload so I will get to know that this particular client is online.

**Comment by HJianBo** [comment]
Afraid not. In the current version (below emqx-ee v2.4.7), You can distinguish it only by the topic of Kafka

**Comment by sourjya123** [comment]
Which emqx-ee version I have to install so that I can distinguish?

**Comment by HJianBo** [comment]
We will have to discuss whether is it necessary to implement it in the next version

**Comment by sourjya123** [comment]
So if I have same topic for getting the status of each device(online/offline) I cant distinguish right?
My requirement is, using the same topic I should be able to distinguish that the particular client is online or offline. Is it possible?

**Comment by HJianBo** [comment]
Yes. BUT Why are you need the same topic to handle `Connected/Discconected` event?

In the current, it is necessary to use difference topic, otherwise, you can't distinguish it

**Comment by sourjya123** [comment]
Ok let say I have 2 different topic to handle Connected/Discconected event. Now million of clients will be connected. That I can distinguish from Connected kafka topic using clientId. But if the same client comes online and goes offline how can I check the client is now online or offline?

**Comment by HJianBo** [comment]
Just set the client state to offline after consuming a client Disconnect event. These events both have the client-id field in the payload

**Comment by sourjya123** [comment]
we cant set anything in the message like online or offline in the payload?

**Comment by sourjya123** [comment]
now my kafka disconnected topic has disconnect event for a particular client. I set the client state to offline. Now my application has to show the offline in the UI. But in time of showing offline, the device comes on. Again my application will consume from connected topic and show it in UI. So time between online and offline for a paricular client will be faster than showing it to UI. So when offline is there in UI by that time already online event is there in connected topic. So there is a time gap. How can I slve this issue?

**Comment by HJianBo** [comment]
> Again my application will consume from connected topic and show it in UI. So time between online and offline for a paricular client will be faster than showing it to UI. 
That's no problem there,  The gap is acceptable as long as it is properly updated to online status when it receives a online event

**Comment by sourjya123** [comment]
Ok. Now if my client comes online then I can get it from clientconnected topic. But if I want to send some data with that like client geographic location, or some client details then how can I set that when it comes online.

**Comment by sourjya123** [comment]
Any update?

**Comment by sourjya123** [comment]
Please let me know

**Comment by turtleDeng** [comment]
You can define a topic for data reporting, send data to the topic  for data reporting, and then push to kafka for consumption through
```
bridge.kafka.hook.message.publish.1 == {"filter":"#", "topic":"xxx"}
```
