### ISSUE TITLE
Error "Unexpected timeout: emit_stats" occurred if there are some connection loads

### ISSUE THREAD

**Issue by jinrm** [emqx/emqx#3137]
#### Environment

- OS: centos 7
- Erlang/OTP: R22/10.5
- EMQ: 4.0 rc3

#### Description

I saw the error in the log during the performance test against EMQ X 4.0 rc.3. The problem can be reproduced when cps = 500.

**Comment by HJianBo** [comment]
Thanks, @jinrm could you paste the related log lines

**Comment by jinrm** [comment]
2019-12-26 17:37:03.899 [error] <<"1086c5dcd0ef664d8b31320">>@192.168.0.18:8262 [Channel] Unexpected timeout: emit_stats

@HJianBo

**Comment by turtleDeng** [comment]
Thanks for your feedback, we have fixed it in emqx-v4.0-rc.4.
