### ISSUE TITLE
EMQX is down unexpectedly

### ISSUE THREAD

**Issue by FlyCodeXD** [emqx/emqx#3140]
#### Environment

- OS: Ubuntu 18
- Erlang/OTP: 
- EMQ: 最新版本

#### Description

*A description of the issue*

大概半年时间都运行很好，最近频繁宕机，重启服务器后没有任何链接也会宕机。请问下可能的原因是什么。还有请问日志如何查看。

**Comment by FlyCodeXD** [comment]
都是基本配置，没有改过。连接数一般也就30左右。很奇怪，最近频繁宕机。

**Comment by HJianBo** [comment]
Hi, @FlyCodeXD Is the latest version meaning v3.2.7?

 Could you paste the error log or crash.dump file to here

**Comment by FlyCodeXD** [comment]
thank you for your reply。
The version I use is：EMQ X Broker emqx-ubuntu18.04-v4.0-rc.3_amd64
Which log do you want? I don't know which one because there are too many logs. Also I don't know the location of crash.dump, can you tell me?
Below is the list of logs
/var/log/emqx# ls
alert.log.1 &nbsp; &nbsp; &nbsp; debug.log.1 &nbsp; &nbsp; &nbsp;emergency.log.idx &nbsp;emqx.log.siz &nbsp;error.log.idx &nbsp;warning.log.1
alert.log.idx &nbsp; &nbsp; debug.log.2 &nbsp; &nbsp; &nbsp;emergency.log.siz &nbsp;erlang.log.1 &nbsp;error.log.siz &nbsp;warning.log.idx
alert.log.siz &nbsp; &nbsp; debug.log.3 &nbsp; &nbsp; &nbsp;emqx.log.1 &nbsp; &nbsp; &nbsp; &nbsp; erlang.log.2 &nbsp;info.log.1 &nbsp; &nbsp; warning.log.siz
critical.log.1 &nbsp; &nbsp;debug.log.idx &nbsp; &nbsp;emqx.log.2 &nbsp; &nbsp; &nbsp; &nbsp; erlang.log.3 &nbsp;info.log.idx
critical.log.idx &nbsp;debug.log.siz &nbsp; &nbsp;emqx.log.3 &nbsp; &nbsp; &nbsp; &nbsp; erlang.log.5 &nbsp;info.log.siz
critical.log.siz &nbsp;emergency.log.1 &nbsp;emqx.log.idx &nbsp; &nbsp; &nbsp; error.log.1 &nbsp; run_erl.log









------------------&nbsp;原始邮件&nbsp;------------------
发件人: "JianBo He"<notifications@github.com&gt;; 
发送时间: 2019年12月28日(星期六) 晚上11:22
收件人: "emqx/emqx"<emqx@noreply.github.com&gt;; 
抄送: "谁持白羽静风尘&apos;"<923803855@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [emqx/emqx] 您好，请问emqx原来有很长一段时间运行很好，最近频繁宕机是什么原因 (#3140)




Hi, @FlyCodeXD Is the latest version meaning v3.2.7?
 
Could you paste the error log or crash.dump file to here

**Comment by HJianBo** [comment]
Can you compress the `/var/log/emqx` directory and email to me? (heeejianbo@gmail.com)

**Comment by HJianBo** [comment]
Hi, @FlyCodeXD Any updates for there?

**Comment by HJianBo** [comment]
Close it for outdated

Please reopen it if you have any updates
