### ISSUE TITLE
Can I use HTTPS to publish a message to be authenticated using TLS client certificate?

### ISSUE THREAD

**Issue by xiongyu0523** [emqx/emqx#3143]
#### Environment

- OS: Ubuntu 18.04
- EMQ: 3.2.7

#### Description

I know the EMQ support client authentication at transport layer using mutual TLS, and EMQ support HTTP API to publish a message to broker. I want to know

1) Does it support HTTPS instead of HTTP? If yes, how can I configure it?
2) If 1) is fine, can I authenticate my client using mutual TLS authentication?

My use case is a sensor sending sensitivity telemetry (need to be secured) and need to be authenticated at TLS level using client certificates. 

Now I use AWS IoT Core PaaS can support this scenario. I want to check the possibility of using EMQ.

Thanks

**Comment by tigercl** [comment]
@xiongyu0523 Sorry for late reply, if you want to use HTTPS API, you should uncomment configurations about https in profile(`.../etc/plugins/emqx_management.conf`).

**Comment by xiongyu0523** [comment]
@tigercl Thanks. I want to enable client authentication with HTTPS. My follow-up questions are:

1) Should I place each client.crt in this folder to let server verify whether the client is a 'registered' client? I do not see a configuration options related to client certificate path but there do have client-cert.pem and .key in the default certs folder. (What is client-key.pem used for? Server should have no client keys). I want to server can verify if the CN of client certificate is already in server's db (registered), better to not verify based on certificate's thumbprint (SHA1 or SHA256)

2) My clients are signed by a different CA, as there is only one cacert path option, so I should merge my client CA and the CA signing the server together, right?

3) I do not need additional application level authentications (all plugins), so i can keep allow_anonymous true, right?

**Comment by xiongyu0523** [comment]
I see broker (EMQ and Mosquitto) are focusing on authentication at application level. But What usually we do for IoT tiny device is to authenticate the client (device) at transport level using TLS mutual authentication, this force the device uses best practices of X.509 certificate and hardware root-of-trust, not username and password.

**Comment by tigercl** [comment]
@xiongyu0523 Of course you can use SSL to connect your device.
1. Server doesn't need client's certificate.
2. But you can let clients with different CA certificates connect to different ports.
3. Yep.

**Comment by xiongyu0523** [comment]
1. OK
2. I do not understand. All my devices are signed by one CA, just different from the one signing server certificate. Can I chain the two CA certificates into a single .pem file and store in cert folder?
3. I need authenticate clients by its client certificate CN. The device need have a certificate issued by trusted CA and also it is a known device (its CN is in server's database). How can I leverage existing configuration to do this?

**Comment by bchhabra2490** [comment]
@xiongyu0523 Were you able to connect to emqx broker over ssl? I am facing an issue while using the broker over ssl.

**Comment by bchhabra2490** [comment]
How to connect to emqx broker with domain?
