### ISSUE TITLE
there is no emqtt docker？

### ISSUE THREAD

**Issue by k332772194** [emqx/emqx#3146]
#### Environment

- OS: 
- Erlang/OTP: 
- EMQ: 

#### Description

*A description of the issue*

**Comment by HJianBo** [comment]
Hi, @k332772194 We will make a docker image for emqtt. Thanks for your suggestions!

**Comment by HJianBo** [comment]
We will release an .rpm package in the recent days, you can directly install it.

Thanks for your feedback there
