### ISSUE TITLE
Repository broken? Hash sum mismatch

### ISSUE THREAD

**Issue by communig8-public** [emqx/emqx#3148]
I noticed the repository was updated today and now I'm getting a hash sum mismatch installing via apt on ubuntu.

**Comment by DapperDivers** [comment]
Seconded! This happened a few months ago with another one of the updates.  Any news or workarounds on this would be amazing.

**Comment by communig8-public** [comment]
Seems to have been fixed now. "apt install emqx" is working again, no hash sum problems.
Thanks

**Comment by HJianBo** [comment]
Thanks for your feedback.

If you have any questions here, let me known

**Comment by jozeblackblox** [comment]
It happend again:

...
Err:6 https://repos.emqx.io/emqx-ce/deb/ubuntu bionic/stable amd64 Packages
  Hash Sum mismatch
  Hashes of expected file:
   - Filesize:3578 [weak]
   - SHA512:544374a51766ede29e304e1d61c8dea4d66e04431017fa76f9af6602041d6fbdbce41cbf14ec428029a5dc4607be2d0fa7fda553ad1db8f1f4626411ccd2e90a
   - SHA256:9f291372ace480faf455922a54f8cb821e588325a24e5e5c3d3141df1612d1b7
   - SHA1:a357d84de47854a3be0b3611cb9a87c118f9bb77 [weak]
   - MD5Sum:0cd2fe6d0ba71f894fb33273237164f8 [weak]
  Hashes of received file:
   - SHA512:676962a45b537c646ea42b2c4466e917476a9e10ace9ef146d6c387598daae378f1d75915b78d60a0f9849a5c473c5caf88ac9668b5bac3b9e0fe3060e1ccb47
   - SHA256:9007f168165003bb1036d7e1dab7ec7ddebfa30970fc1152826fe0cb0d005c87
   - SHA1:9ecae7c4d68ed97ead5ab9c764c028fd63defb7e [weak]
   - MD5Sum:591022669895fbef73f2c0468347bbe5 [weak]
   - Filesize:3578 [weak]
  Last modification reported: Fri, 06 Mar 2020 10:17:09 +0000
  Release file created at: Fri, 06 Mar 2020 04:23:37 +0000

**Comment by zhanghongtong** [comment]
@jozeblackblox 
I'm sorry for the issue. It should have been solved by now. Please try again

**Comment by bferg88** [comment]
This appears to have happened again today.

**Comment by bulolo** [comment]
This appears to have happened again today.
