### ISSUE TITLE
Dashboard admin password resets to default after leaving cluster

### ISSUE THREAD

**Issue by communig8-public** [emqx/emqx#3155]
#### Environment

- OS: Ubuntu 18.04.3 LTS (AWS EC2)
- Erlang/OTP: R21/10.3.5.4
- EMQ: 3.2.7

#### Description

If the password for the admin dashboard user is changed from the default "public" via the dashboard or cli (emqx_ctl admins passwd admin newpasswd) and the server is then joined to a cluster and then leaves that cluster, the password is reset to the default (public). This is also the case of the default password is changed in /etc/emqx/plugins/emqx_dashboard.conf.

**Comment by HJianBo** [comment]
This is an unavoidable situation. It just temporary changes by dashboard or cli

The database of emqx (named Mnesia) will be reset after joining or leaving a cluster. Because we should keep consistency of the admin user table in the cluster. 

Therefore, it is better to modify the configuration file directly and ensure consistency across the cluster

**Comment by communig8-public** [comment]
As I mentioned "...This is also the case of the default password is changed in /etc/emqx/plugins/emqx_dashboard.conf." !!

**Comment by communig8-public** [comment]
Also this a rather big security issue.

**Comment by communig8-public** [comment]
I have found that if I set the password in the configuration after EMQ X is installed but before it is first started, the new default password is used when the server leaves the cluster. If the configuration is updated after the first run of EMQ X it seems the original default password "public" gets remembered.

**Comment by zmstone** [comment]
@HJianBo we need to check if this is still the case for 4.x

**Comment by HJianBo** [comment]
Yes, after leaving the cluster, this password is reset and keeps the same value as in the configuration file.

>  If the configuration is updated after the first run of EMQ X it seems the original default password "public" gets remembered

I did not reproduce it in 4.x. I'm guessing it's not restarting the plugin or emqx to get the new password after changing emqx_dashboard.conf

**Comment by HJianBo** [comment]
So, we still have the possibility of security risks after the node leaves the cluster. If we just use emqx_ctl/HTTP-API to change the dashboard password?

**Comment by zmstone** [comment]
> As I mentioned "...This is also the case of the default password is changed in /etc/emqx/plugins/emqx_dashboard.conf." !!

@HJianBo could you check if this is still the case?

**Comment by zmstone** [comment]
> I did not reproduce it in 4.x. I'm guessing it's not restarting the plugin or emqx to get the new password after changing emqx_dashboard.conf

Ok missed this. Thanks for checking.
Then we can close this issue

**Comment by zmstone** [comment]
> > I did not reproduce it in 4.x. I'm guessing it's not restarting the plugin or emqx to get the new password after changing emqx_dashboard.conf
> 
> Ok missed this. Thanks for checking. Then we can close this issue

sorry, I might be wrong
password is stored in 3 places, config file, db, and app env,
the problem seem to be: when update from cli, only db is changed, but not app env.
