### ISSUE TITLE
Already set ”acl_deny_action = disconnect“，clients subscribe to topics without permissions，EMQX does not close the connection with the client

### ISSUE THREAD

**Issue by izhangwu** [emqx/emqx#3156]
#### Environment

- OS: Centos7.2
- Erlang/OTP: R21/10.3.5.1
- EMQ: 3.2.0

#### Description
emqx配置了关闭匿名登录和匿名认证以及acl拒绝策略为disconnect
![image](https://user-images.githubusercontent.com/51317834/71758857-ee5edb00-2edf-11ea-853c-0d095dc13872.png)
![image](https://user-images.githubusercontent.com/51317834/71758860-fcacf700-2edf-11ea-97b9-c07cd592fd60.png)
![image](https://user-images.githubusercontent.com/51317834/71758880-0b93a980-2ee0-11ea-8c1f-b935b8bbee34.png)

认证和访问控制插件完全采用和依赖于mysql，并且注释掉了acl.conf全部内容

启动emqx，mysql访问控制插件。测试步骤如下
1.启动一个共享订阅客户端S订阅系统上下线主题
2.让一个客户端A连接上emqx，先订阅一个有权限的主题，在订阅一个没有权限的主题
3.让另外一个客户端B发布A有订阅权限的主题消息“111”

结果：
1。客户端A订阅没有权限的主题抛出异常，却收到有权限的主题消息“111”
2.共享订阅客户端S只收到客户端A连接上线消息，断定客户端A没有出现断开重连

![TIM图片20200104110437](https://user-images.githubusercontent.com/51317834/71759024-0df70300-2ee2-11ea-99ac-accc2ca2fa83.png)

**Comment by xyz361** [comment]
Environment
OS: Centos7.2
Erlang / OTP: R21 / 10.3.5.1
EMQ: 3.2.0

Description：
Emqx is configured to turn off anonymous login and anonymous authentication and acl rejection policy to disconnect .
![image](https://user-images.githubusercontent.com/37579443/71759113-1ef44400-2ee3-11ea-9845-3863c102ff16.png)
![image](https://user-images.githubusercontent.com/37579443/71759116-27e51580-2ee3-11ea-9974-3a706c419b26.png)
![image](https://user-images.githubusercontent.com/37579443/71759118-2ca9c980-2ee3-11ea-9928-4713c1505147.png)



The authentication and access control plug-ins are fully adopted and dependent on mysql, and commented out the entire content of acl.conf .

Start emqx with mysql auth plugin . 
The test steps are as follows:
1. Launch a shared subscription client S subscription system
2. Let a client A connect to emqx, first subscribe to a topic with permissions, and subscribe to a topic without permissions
3. Let another client B publish the topic message "111" that A has subscription rights

Result:
1. Client A subscribes to a topic without permission throws an exception, but receives a permission message "111"
2. The shared subscription client S only received the connection and online message of client A, and concluded that client A did not disconnect and reconnect.

![image](https://user-images.githubusercontent.com/37579443/71759123-33d0d780-2ee3-11ea-950d-8f594c5b3939.png)

**Comment by tigercl** [comment]
@xyz361 Maybe the ACL rule you set not be matched, you can set the log level to warning to confirm whether the rule is working, or show me your topic and rule.

**Comment by izhangwu** [comment]
> @xyz361 @izhangwu Maybe the ACL rule you set not be matched, you can set the log level to warning to confirm whether the rule is working, or show me your topic and rule.

**Comment by izhangwu** [comment]
> @xyz361 @izhangwu Maybe the ACL rule you set not be matched, you can set the log level to warning to confirm whether the rule is working, or show me your topic and rule.

I'm sure the ACL rule is working, because when client A subscribes to a topic without permission, an exception is thrown, and there is no problem when subscribing to a topic with permission.

Below is my java code
`public class DeviceSubscribeAcl {

    private static Logger logger = LoggerFactory.getLogger(DeviceSubscribeAcl.class);

    public static void main(String[] args) {

        String host = "tcp://192.168.38.153";

        String username = "iot_connect_test";
        String password = "123456";
        String client_id = "iot_connect_test";

        String sub_topic = "111/"+client_id+"/app2dev1111111";
        String sub_topic2 = "111/"+client_id+"/app2dev";


        try {
            // host为主机名，client_id一般以客户端唯一标识符表示，MemoryPersistence设置clientid的保存形式，默认为以内存保存
            MqttClient client = new MqttClient(host, client_id);
            // MQTT的连接设置
            MqttConnectOptions options = new MqttConnectOptions();
            // 设置是否清空session,默认为true，这里如果设置为false表示服务器会保留客户端的连接记录，这里设置为true表示每次连接到服务器都以新的身份连接
            options.setCleanSession(true);
            // 设置连接的用户名,可以不设置
            options.setUserName(username);
            // 设置连接的密码
            options.setPassword(password.toCharArray());
            // 设置超时时间 单位为秒，emqx连接超时时间为一分钟
            options.setConnectionTimeout(10);
            // 设置会话心跳时间 单位为秒 服务器会每隔1.5*T周期内判断设备的在线状态
            options.setKeepAliveInterval(60);
            client.connect(options);
            logger.info("connect successful");


            client.setCallback(new MqttCallback() {

                @Override
                public void connectionLost(Throwable cause) {
                    logger.info("{}，mqtt broker miss",cause.getMessage());
                }

                @Override
                public void messageArrived(String topic, MqttMessage message) throws Exception {
                    logger.info("messageArrived->{}->{}",topic,new String(message.getPayload()));
                }

                @Override
                public void deliveryComplete(IMqttDeliveryToken token) {
                    logger.info("deliveryComplete->{}",token.isComplete());
                }
            });
            client.subscribe(sub_topic2);
            client.subscribe(sub_topic);


        }catch (Exception e){
            logger.error(e.getMessage());
        }

    }
}`

At this time, I used another client B to publish a message on the subject that the client A has permission to, and client A received the message. At first I suspected that it was possible that the client was forcibly disconnected by EMQX and reconnected, so that it could receive the topic message released by client B, so there was the above test where I used another client to subscribe to the topic of online and offline End A subscription does not have the topic EMQX without permissions and will not force close the MQTT connection

Below are the records in my ACL rules and Mysql
`select allow, ipaddr, username, clientid, access, topic from mqtt_acl where ipaddr = '%a' or username = '%u' or  clientid = '%c'`

![image](https://user-images.githubusercontent.com/51317834/71761323-73f48200-2f04-11ea-974c-c6cfd1f4703a.png)

**Comment by tigercl** [comment]
@izhangwu You should not judge whether the rule working based on whether the client throws an exception. The easiest way is checking emqx logs in warning level.

**Comment by izhangwu** [comment]
> @izhangwu You should not judge whether the rule working based on whether the client throws an exception. The easiest way is checking emqx logs in warning level.

OK, I opened the log level as warning according to your prompt, and cleared the log. Repeated my operation above, and then check the log, the screenshot is as follows

![image](https://user-images.githubusercontent.com/51317834/71762117-bbc8d880-2f07-11ea-8db0-ef10ab09feb8.png)

**Comment by tigercl** [comment]
@izhangwu Sorry, I just noticed that the configuration you modified is `acl_deny_action`, we have a higher priority configuration named `zone.*.acl_deny_action`, if it be set, emqx will use its value rather than `acl_deny_action`. You should comment `zone.*.acl_deny_action` or set it to `disconnect` rather than default `ignore`. And you can see server sent disconnect packet to client if you set log level to debug when the configuration is correct.

**Comment by izhangwu** [comment]
> @izhangwu Sorry, I just noticed that the configuration you modified is `acl_deny_action`, we have a higher priority configuration named `zone.*.acl_deny_action`, if it be set, emqx will use its value rather than `acl_deny_action`. You should comment `zone.*.acl_deny_action` or set it to `disconnect` rather than default `ignore`. And you can see server sent disconnect packet to client if you set log level to debug when the configuration is correct.

It's ok, it's resolved, thank you very much
