### ISSUE TITLE
Management monitoring API cannot make cross-domain requests

### ISSUE THREAD

**Issue by lingkejia** [emqx/emqx#3158]
#### Environment

- OS: Centos
- Erlang/OTP: 
- EMQ: V3.2.2

#### Description

*A description of the issue*

在前端项目使用 axios 请求管理监控 API 提示跨域请求错误，请问在哪里可以配置跨域？

**Comment by HJianBo** [comment]
Can you give me a specific API path? We will check it

**Comment by ysfscream** [comment]
@lingkejia Hi, if you are in development mode you can configure proxy for front-end project.

```javascript
```
