### ISSUE TITLE
payload message check

### ISSUE THREAD

**Issue by xiaoshuaishuai** [emqx/emqx#3159]
Whether emq supports payload body check such as ws MQTT TCP connection, such as sensitive words, etc. If there is an illegal payload, it will not be published. I know how HTTP publishing can be checked, but if I want the client to use ws or MQTT connections after the message goes straight to emq, I want to ask if there is a pointcut similar to the acl, but the acl does not contain payload, only topic and access

**Comment by HJianBo** [comment]
Hi, @xiaoshuaishuai Broker is not supported checking payload content.

Or you can implement by yourself: [emqx_web_hook](https://github.com/emqx/emqx-web-hook)

**Comment by HJianBo** [comment]
Hi, @xiaoshuaishuai Sorry to tell you. We have no plan to implement it at the recent versions
