### ISSUE TITLE
emqx broker can't start on Alibaba Cloud Elastic Compute Service

### ISSUE THREAD

**Issue by saiyn** [emqx/emqx#3161]
![fuck-aliy](https://user-images.githubusercontent.com/7022424/72025267-8a0e9380-32b2-11ea-986b-d6a335d76f7c.png)

env is show as screen shot above

I follow the steps in [https://docs.emqx.io/broker/v3/en/install.html#ubuntu](url) and try v3,2.5 and  v3.2.7 with deb way and repository way, all fail to start emqx.
 I change the log level to debug and log is as below:

[erlang_log.tar.gz](https://github.com/emqx/emqx/files/4037868/erlang_log.tar.gz)

and for your convenient, I post screenshot of log here

![emq_log](https://user-images.githubusercontent.com/7022424/72025718-f8a02100-32b3-11ea-9ffd-e4d966d816ae.png)

**Comment by HJianBo** [comment]
Hi, @saiyn It seems the configurations do not match error.

Do you have to check why are you introduce the `bridge.kafka.*` options?

(In general, the community edition does not include the emqx_bridge_kafka plugin

**Comment by saiyn** [comment]
hi @HJianBo , thanks your help, but i do noting except for steps list on the doc, and could you tell me how can i close these options?
and I did the same thing on a aws ec2 and very thing is ok there, and actually i have build and used the emqx broker service on the aws ec2 for couple months.

**Comment by saiyn** [comment]
since you mentioned the community edition does not include the emqx_bridge_kafka plugin, i think the problem maybe that i actually dpkg -i a enterprise version by mistake, and then i dpkg -r to remove that. and then i install a community version.
so i think maybe something related to the enterprise version still leave behind
could you tell me how i can make things back to ok?

**Comment by zhanghongtong** [comment]
@saiyn Hi, you can try `dpkg-p emqx` and `dpkg-p emqx-ee` to remove the previously installed version and reinstall emqx

**Comment by saiyn** [comment]
problem is gone after i clean the system, thanks for your help

**Comment by zhanghongtong** [comment]
You're welcome :)
