### ISSUE TITLE
[WS Channel] Frame error: Other type of data frame

### ISSUE THREAD

**Issue by enrahmad** [emqx/emqx#3172]
#### Environment

- OS: Ubuntu 18.04 
- Erlang/OTP: 22
- EMQ: EMQX 3.2.7

#### Description

When I see the log ```tail -f emqx.log.2``` I find many error like this
2020-01-10 12:44:37.070 [error] xxx.xxx.17.194:45025 [WS Channel] Frame error: Other type of data frame
2020-01-10 12:44:37.096 [error] xxx.xxx.17.194:47779 [WS Channel] Frame error: Other type of data frame

Can you explain to me, what the error want?

**Comment by tigercl** [comment]
@enrahmad Your client sends text data rather than binary data.

**Comment by rajapulau** [comment]
Hi @tigercl 

what do you mean binary data? can you explain it?

**Comment by tigercl** [comment]
@rajapulau Sorry for late reply. The date frame types in WebSocket are ping, pong, binary, text, etc. The type of date frames you send is neither binary nor ping or pong.
