### ISSUE TITLE
can emqx work well under redhat7.3？

### ISSUE THREAD

**Issue by lixianshang** [emqx/emqx#3177]
#### Environment

- OS: redhat7.3
- Erlang/OTP: 22
- EMQ: emq-centos7-v4.0.0.zip

#### Description

*A description of the issue*
there is no available package for redhat, so I use package for centos instead.

bin/emqx console
starts and crashes what will be the reason

Erlang/OTP 22 [erts-10.5] [source] [64-bit] [smp:32:32] [ds:32:32:10] [async-threads:32] [hipe]

{"Kernel pid terminated",application_controller,"{application_start_failure,kernel,{{shutdown,{failed_to_start_child,kernel_safe_sup,{on_load_function_failed,crypto}}},{kernel,start,[normal,[]]}}}"}
Kernel pid terminated (application_controller) ({application_start_failure,kernel,{{shutdown,{failed_to_start_child,kernel_safe_sup,{on_load_function_failed,crypto}}},{kernel,start,[normal,[]]}}})

Crash dump is being written to: log/crash.dump...done

**Comment by HJianBo** [comment]
Have you tried to upgrade your openssl above to v1.1.1?

**Comment by lixianshang** [comment]
> It should work. Have you tried to upgrade your openssl above to v1.1.1?

I have already upgraded my openssl to 1.1.1c, but the same error still occured. I can't find available package for red hat In EMQ official website，does it mean that EMQX group do not test it under red hat yet？

**Comment by HJianBo** [comment]
Yes, we not packing release package especially for RedHat. @turtleDeng @zhanghongtong  Do we plan to support it?
