### ISSUE TITLE
Failed to start emqx daemon after editing emqx.conf

### ISSUE THREAD

**Issue by bkrajendra** [emqx/emqx#3180]
#### Environment

- OS: Centos7
- Erlang/OTP: 21
- EMQ: 4.0

#### Description

This happened multiple time earlier also.
I stopped using emqx because of this.

The issue is, if I edit any part of emqx.conf file in /etc/emqx/emqx.conf
earlier I used to edit it with my cpanel editor, so I thought that might be the case.
But then I replaced entire file from github, edited file with nano and replaced all platform variables 
but still getting same error.

Error:
```
● emqx.service - emqx daemon
   Loaded: loaded (/usr/lib/systemd/system/emqx.service; enabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Tue 2020-01-14 16:51:45 IST; 1min 45s ago
  Process: 9707 ExecStop=/bin/sh /usr/bin/emqx stop (code=exited, status=1/FAILURE)
  Process: 24294 ExecStart=/bin/sh /usr/bin/emqx start (code=exited, status=1/FAILURE)
 Main PID: 1407 (code=killed, signal=TERM)

Jan 14 16:51:21 cpanel.iocare.in systemd[1]: Starting emqx daemon...
Jan 14 16:51:45 cpanel.iocare.in systemd[1]: emqx.service: control process exited, code=exited status=1
Jan 14 16:51:45 cpanel.iocare.in systemd[1]: Failed to start emqx daemon.
Jan 14 16:51:45 cpanel.iocare.in systemd[1]: Unit emqx.service entered failed state.
Jan 14 16:51:45 cpanel.iocare.in systemd[1]: emqx.service failed.

```
I dont know whats this issue about.
Please help.

**Comment by bkrajendra** [comment]
Using command
```
> nano -w /etc/emqx/emqx.conf
```

resolved my issue of editing.
But this is really hectic to edit each and every part with nano.
Can we create some plugin to edit few options using web UI?

**Comment by HJianBo** [comment]
I guess the content and format of emqx.conf is corrupted. I'm not familiar to nano/cpanel editor, But we recommend using vi/vim to edit *.conf

And, you can see the details log in the `/var/log/emqx/` directory

---

> Can we create some plugin to edit few options using web UI?

Nope, not support yet
