### ISSUE TITLE
Do emqx-team have a plan to use golang to instead of erlang int the cloud computing era?

### ISSUE THREAD

**Issue by sodwell** [emqx/emqx#3181]
#### Environment

- OS: 
- Erlang/OTP: 
- EMQ: 

#### Description

*A description of the issue*

**Comment by emqplus** [comment]
@sodwell No. See: #2577  
And we have a plan to release the `Hamler` programming language in this year.

**Comment by sodwell** [comment]
Wait and see your "Hamler".
