### ISSUE TITLE
4.0 Dashboard error: 404 Not Found with certain clientId

### ISSUE THREAD

**Issue by gsngsngsn** [emqx/emqx#3182]
#### Environment

- OS: 
- Erlang/OTP: 
- EMQ:  4.0.0

#### Description

With clientid = "project/xxxxx/client/ccccc/user/zxcv/device/current_device_id_test"

dashboard has a problem navigate to its detail page, showing 404 page not found:
https://emq.xxx.xxx/#/clients/project/xxxxx/client/ccccc/user/zxcv/device/current_device_id_test
![404](https://user-images.githubusercontent.com/3394919/72416695-3fa97d00-37b2-11ea-8b60-96375392524d.jpeg)

While other clientid such as "1112ec16-15ba-4626-80f0-b30f7cd2a36d" works well. 
https://emq.xxxx.xxx/#/clients/1112ec16-15ba-4626-80f0-b30f7cd2a36d

----

Another problem, which I believe cause by the same problem here, is that the clean session button won't work on the same clientId:
![wrongurl](https://user-images.githubusercontent.com/3394919/72416765-623b9600-37b2-11ea-9e7c-d8282cb74012.jpg)

**Comment by ysfscream** [comment]
@gsngsngsn Hi, thanks for your feedback. This is a bug and I will fix it as soon as possible. If it works normally, I will tell you here.

**Comment by HJianBo** [comment]
Hi, guys it has released at v4.0.1

Thanks for your contributions
