### ISSUE TITLE
4.0.0 not sending DISCONNECT packet to client with mqtt v5.0 when getting session takeover. 

### ISSUE THREAD

**Issue by gsngsngsn** [emqx/emqx#3183]
#### Environment

- OS: 
- Erlang/OTP: 
- EMQ: 4.0.0

#### Description
- client-side mqtt protocol version: 5.0, mqtt.js 
![Screenshot from 2020-01-15 16-34-37](https://user-images.githubusercontent.com/3394919/72418002-f3137100-37b4-11ea-949e-312364ae1bf3.png)

- emqx debug level: debug

scenario: 
- 2 client with same clientid : yollollllllllllllllll
- 1st client connect and pub&rec 2 message. 
- 2nd client connect and pub& rec 2 message.

Expecting: 
- 1st client receive a disconnect packet with code 142 according to [mqtt 5 protocol](https://docs.oasis-open.org/mqtt/mqtt/v5.0/os/mqtt-v5.0-os.html#_Toc3901208)

Actual:
- 1st client got close without receiving any packet. (we can see ping packet, sub & pub packets)
![Screenshot from 2020-01-15 16-33-45](https://user-images.githubusercontent.com/3394919/72417917-d37c4880-37b4-11ea-9849-6da3ba5f0ef6.png)
-  the debug log from emqx show no sign of sending out disconnect packet too. 
[trace_yollollllllllllllllll.log](https://github.com/emqx/emqx/files/4063826/trace_yollollllllllllllllll.log)

**Comment by emqplus** [comment]
@tigercl @HJianBo Pls check the issue.

**Comment by gsngsngsn** [comment]
Thx for reviewing this.

This feature is quite important IMHO, since this is almost the only way that the broker communicates with the client regarding what client should/should not do when disconnecting it.

**Comment by gsngsngsn** [comment]
BTW, the webhook provided shows only the following message:
`"session_terminated" reason:"tcp_closed"`
Instead of what I was expecting: session.takeovered introduced from https://github.com/emqx/emqx/pull/3138.

Currently running emqx v4.0.0

**Comment by HJianBo** [comment]
@gsngsngsn Thanks for your feedback!

Q1: I have tested it on 1883, but not reproduce this bug. The reason code for 0x8E can be sent correctly

[mqtt5.cap.txt](https://github.com/emqx/emqx/files/4070020/mqtt5.cap.txt) (Try to open it with Wireshark and filter with `mqtt && tcp.stream == 0`)

Which channel are you connect the broker? by MQTT/TCP or MQTT/WS?

Q2: The `takeover` events should not trigger any events. Plz make sure it

**Comment by gsngsngsn** [comment]
@HJianBo thanks for the info.

## 1. Q1: yes I have tried both 1883 and wss && ws. None of them work for me. 

This time I build it as a simple docker (docker start -p 18083:18083 -p 1883:1883  emqx/emqx:v4.0.0), same result. 

`
/opt/emqx $ ./bin/emqx_ctl status
Node '0c9100847d55@172.17.0.3' is started
emqx 4.0.0 is running
`

I use Wireshark too and what I am currently seeing is that the emqx server is not sending out disconnect packet like the one you have there. 

![lADPBE1XY1l51gbNArvNBNo_1242_699](https://user-images.githubusercontent.com/3394919/72594686-fdfc0c00-3942-11ea-8a6a-e6e995be285d.jpg)

we can see logs in debug log from EMQX (2020-01-17 07:56:46.445 [debug] <<"test">>@172.17.0.1:34154 [MQTT] Terminated due to {shutdown,takeovered} )
but from packet capture there is no disconnect. 

The client is also v5 protocol mqtt 

![Screenshot from 2020-01-17 16-08-01](https://user-images.githubusercontent.com/3394919/72594891-8da1ba80-3943-11ea-8e40-d412b43eb4c1.png)

## 2. Q2 then when will the webhook session.takeovered be triggered?

What else might be the factor in this case?
And what is should look like in emqx debug log when actual Disconnect packet is being sent?"

**Comment by HJianBo** [comment]
Hi, @gsngsngsn We have reproduced it. Thanks for your contribution

It was released at v4.0.1.
