### ISSUE TITLE
emqx cluster configure Load balancer on GCP

### ISSUE THREAD

**Issue by yuvarajan1989k** [emqx/emqx#3191]
#### Environment

- OS:  ubuntu 18.04 
- Erlang/OTP: 
- EMQ:  4.0.0

#### Description

                                                                                           
 Android device    --------- >   HTTPS Load balancer GCP --------------> EMQX cluster
 ------------------(443)--------------------------------------(1883)-------------------

I am trying for the above setup to work. Technically is it possible ? Kindly advice me on this if any one achieved on this.

From the android log, 
Making connection to push notification server: ssl://********:443

And then it said, connection lost.

**Comment by tigercl** [comment]
@yuvarajan1989k Could you provide logs of emqx in `.../emqx/log`?

**Comment by yuvarajan1989k** [comment]
@tigercl 

thanks for looking into this. PFA for the logs.
[emqx.log.1.tar.gz](https://github.com/emqx/emqx/files/4074804/emqx.log.1.tar.gz)

**Comment by tigercl** [comment]
@yuvarajan1989k It seems that port 1883, which is used to receive MQTT messages, received HTTP messages.

**Comment by yuvarajan1989k** [comment]
@tigercl HTTP messages that must be from the port 8083(wss). 

i am not able to get it working when i use ssl/tcp transport type.

**Comment by HJianBo** [comment]
Hi @yuvarajan1989k 

First of all, emqx can accept TCP or Websocket based connection. The TCP/SSL based client should connect to 1883/8883,  Websocket/Websocket-SSL client should connect 8083/8084


> Android device --------- > HTTPS Load balancer GCP --------------> EMQX cluster
> ----------------(443)--------------------------------------(1883)-------------------

According to the log files, the ` HTTPS Load balancer GCP`  is connected to the wrong port. It should connect to 8083/8084 instead of 1883/8883 if the `GCP` just support ws/wss proxy

**Comment by yuvarajan1989k** [comment]
@HJianBo  i have tested with GCP HTTPS load balancer with below setup and its working. 

   Android device ----------> HTTPS load Balancer GCP -------------> EMQX Broker
   <(wss://LB IP: 443)---443-> |----------------------|<--8083----------->

But i can see that the clients got disconnected every 8 sec.  do i need to fine tune any settings for websocket ?

**Comment by HJianBo** [comment]
@yuvarajan1989k So sorry late reply here. 

You should check the Proxy (HTTPS load Balancer GCP) configuration options. It should have some option, for example, named `tcp_connection_timeout`. It should bigger than the `keepalive` value of the MQTT clients on the broker.
