### ISSUE TITLE
Cluster Node cannot leave when in auto-discovery mode

### ISSUE THREAD

**Issue by communig8-public** [emqx/emqx#3211]
#### Environment

- OS: Ubuntu 18.04.3 LTS (GNU/Linux 4.15.0-1057-aws x86_64)
- Erlang/OTP: R22/10.5.2
- EMQ: 4.0.0 (also happened in 3.2.7)

#### Description

With a Node which is configured for auto-discovery e.g. dns, use of the "emqx_ctl cluster leave" just causes the Node to rejoin the Cluster after it has left. It would make sense that having specifically asked the Node to Leave the Cluster it would not re-join until specifically requested to join again.

**Comment by emqplus** [comment]
@communig8-public The './bin/emqx_ctl cluster leave' CLI only works for manual cluster strategy. I will discuss the requirement with team later.
