### ISSUE TITLE
Reach the limit number of messages/sec

### ISSUE THREAD

**Issue by adicatur** [emqx/emqx#3217]
#### Environment

- OS: 18.04
- Erlang/OTP: 22.0
- EMQ: 3.2.7

#### Description

We have a stress test with some tester server 50%pub and 50%sub on EMQX with spec 36vCPU and RAM 72GB, 
We also try another higher EMQX server spec but max reach for SUB 80.xxx messages/sec, 
Are there some ways to increase the number of messages/sec?

**Comment by turtleDeng** [comment]
You provide your test scenarios, subscribed topics, and published message sizes.

**Comment by HJianBo** [comment]
Hi, @adicatur How is the test going now?

**Comment by turtleDeng** [comment]
Thanks for your participation, we will close this issue.
