### ISSUE TITLE
"Start bridge failed." AWS IoT Core

### ISSUE THREAD

**Issue by sgoveia** [emqx/emqx#3220]
#### Environment

- OS: Mac
- Erlang/OTP: 
- EMQ: Docker v4.0.1

#### Description

*A description of the issue*
please see this issue: https://github.com/emqx/emqx-bridge-mqtt/issues/57

**Comment by turtleDeng** [comment]
Duplicate issue is already at https://github.com/emqx/emqx-bridge-mqtt/issues/57, I will close this issue.
