### ISSUE TITLE
Should LWT be sent with loss of client internet?

### ISSUE THREAD

**Issue by hgascoigne** [emqx/emqx#3221]
#### Environment
- EMQ: 4.0.1

#### Description
Using the default config of EMQX and the default config of MQTT.js connecting using a websocket, should I expect my last will be sent after disabling my computer's network connection? If I understand correctly, this should happen after 90s but never seems to happen.

**Comment by briangruber** [comment]
I can confirm. Here is a simple test case:

Visit this test client: http://www.hivemq.com/demos/websocket-client/ and run the test with a EMQ broker, and then the default public hivemq broker to see the difference.

**Computer A:**
Step 1: Set a last will message and topic (e.g. `my-last-will`)
Step 2: Connect to the broker 

**Computer B:** 
Step 1: Connect to the broker
Step 2: Subscribe to the last will topic of Computer A (e.g. `my-last-will`)

**Test:**
1. Kill the WIFI on Computer A.
2. Wait for the keepalive time period to expire

**Expected Results:**
Computer B should receive the Last Will Message.

**Actual Results:**
- Running this with a `emqx` broker, computer B never receives the last will message.
- However, do the same test with the default `hivemq` broker and computer B does get the last will message.

**Comment by zhengyupan** [comment]
Hi @hgascoigne, hi @briangruber ,
Can you provide more details about how to reproduce this issue? I repeated the test and it works just fine for me. To preproduce the case described by briangruber, I also used the ws tool from HiveMQ, I sent one normal message and then killed the browser, and the will message works, please see the following screenshots:
<img width="689" alt="Screenshot 2020-01-24 00 40 31" src="https://user-images.githubusercontent.com/3228288/73034318-d0342d00-3e44-11ea-824d-20815bfbe822.png">

<img width="1038" alt="Screenshot 2020-01-24 00 39 52" src="https://user-images.githubusercontent.com/3228288/73034298-c14d7a80-3e44-11ea-9ae2-da79895cd0b3.png">

**Comment by briangruber** [comment]
It works fine if you kill the browser or even close the tab. But if you kill your WiFi or unplug your network connection it will not work. You will need to devices to test this.

**Comment by zhengyupan** [comment]
Hi @briangruber ,
Thank you for the input. I repeated the steps as your description using two devices, but it still works for me.
I still cannot reproduce this issue... 
In the following screenshots you can see the wifi was killed and the ws client in browser showed also disconnected, the will message was received by subscriber after timeout.

![WechatIMG188](https://user-images.githubusercontent.com/3228288/73056670-eca98700-3e8f-11ea-9328-0a47bcdaa927.png)

<img width="685" alt="Screenshot 2020-01-24 09 44 19" src="https://user-images.githubusercontent.com/3228288/73056711-05b23800-3e90-11ea-8cde-6fe3758d777b.png">

**Comment by zhengyupan** [comment]
Hi @briangruber ,
now I can reproduce this issue, it occurs only on release 4.0.1, not on 4.0 rc4 or earlier.
We will come back here once this is fixed.
Thanks for the input!

**Comment by turtleDeng** [comment]
Thanks for your feedback, we have fixed it in v4.0.2.
