### ISSUE TITLE
ClientId in on_message_publish()

### ISSUE THREAD

**Issue by drasko** [emqx/emqx#3222]
Is there a way to fetch `ClientId` in [`on_message_publish()`](https://github.com/emqx/emqx-plugin-template/blob/696122218b600c6f35f6b3fb161615eb18e03aca/src/emqx_plugin_template.erl#L148) handler?

If not - how can we know which client is actually publishing this message?

**Comment by turtleDeng** [comment]
Please refer to https://github.com/emqx/emqx-plugin-template/blob/master/src/emqx_plugin_template.erl#L148
```
Message#message.from
```

**Comment by drasko** [comment]
[This one](https://github.com/emqx/emqx/blob/0bad7dd64c592584821148dd64a883b3ce9b5db1/include/emqx.hrl#L63) I guess.

Thanks.
