### ISSUE TITLE
raise error on_message_deliver, a safe practice?

### ISSUE THREAD

**Issue by ovidiusimionica** [emqx/emqx#3223]
#### Environment

- OS: Linux
- Erlang/OTP: 
- EMQ: 3.2 

#### Description
In relation to [https://github.com/emqx/emqx/issues/1580](https://github.com/emqx/emqx/issues/1580)
we have a business case were the subscriber uses a wildcard subscription, and the plugin needs to deny/allow delivery of a particular message based on its payload and the subscriber username combo.

we are able to return a nil as message from the hook which will raise an error, and as result the message is not delivered to that particular subscriber.
e.g:
`3:17:42.186 [error] GenServer #PID<0.2452.0> terminating
emqx.devops         | ** (FunctionClauseError) no function clause matching in :emqx_packet.from_message/2
emqx.devops         |     (emqx) /emqx_temp/emqx-rel/_build/emqx/lib/emqx/src/emqx_packet.erl:114: :emqx_packet.from_message(:undefined, :nil)
`

*A description of the issue*

My question is: do you see this being unsafe, having side effects on stability of the broker?
From our tests so far it looks ok.
Thanks.

**Comment by HJianBo** [comment]
Hi, @ovidiusimionica I think it is an unsafe practice, The `nil` will cause a process crash error. That causes the client's connection process to shut down.

I think a good practice is supporting stop PUBLISH/Deliver messages in the hook return value.

We will discuss it later. Thanks for your feedback

**Comment by ovidiusimionica** [comment]
Hi @HJianBo ,

thank you very much for the information. I am looking forward for this possibility on the hook, it will be valuable addition enabling some enterprise usecase. I'm a fan of your team's work and the great speed of new releases!

I'll keep an eye on the hook's api for updates

Thanks.

**Comment by HJianBo** [comment]
Sorry, @ovidiusimionica After a team discussion, we no plan to add this feature :)

Maybe you can fork and modify it
