### ISSUE TITLE
[CM] Failed to discard {noproc, {gen_server,call,[<0.6687.0>,discard,infinity]}} & {{shutdown,tcp_closed},{gen_server,call, [<0.7138.0>,discard,infinity]}}

### ISSUE THREAD

**Issue by arvindh123** [emqx/emqx#3224]
#### Environment

- OS:  Windows Server 2016
- Erlang/OTP:   22 [erts-10.6] [64-bit]
- EMQ: 4.0.0

#### Description
Error :
**2020-01-27 11:08:59.591 [error] <<"bench-pub-EMSDev300-eid_30-70386781">>@10.87.1.75:56066 [CM] Failed to discard <0.7076.0>: {noproc,
                                    {gen_server,call,
                                     [<0.7076.0>,discard,infinity]}}
2020-01-27 11:09:07.186 [error] <<"bench-pub-Test500-eid_37-36166122">>@10.87.1.200:50668 [CM] Failed to discard <0.7138.0>: {{shutdown,tcp_closed},
                                    {gen_server,call,
                                     [<0.7138.0>,discard,infinity]}}**
What I did:
A Go Lang program running one machine which does
-> Establish 1000 connection to EMQX  server ( from one machine 1000 connection is eastabished to EMQX server) 
-> Each connection successfully connected to EMQX server
-> Each connection publish 1000 topics in, Basically its a goroutine, which run concurrently,
-> After some times , getting the following error ::  
**2020-01-27 11:08:59.591 [error] <<"bench-pub-EMSDev300-eid_30-70386781">>@10.87.1.75:56066 [CM] Failed to discard <0.7076.0>: {noproc,
                                    {gen_server,call,
                                     [<0.7076.0>,discard,infinity]}}
2020-01-27 11:09:07.186 [error] <<"bench-pub-Test500-eid_37-36166122">>@10.87.1.200:50668 [CM] Failed to discard <0.7138.0>: {{shutdown,tcp_closed},
                                    {gen_server,call,
                                     [<0.7138.0>,discard,infinity]}}**
Why I'm getting this error , How can I over come this error.

**=====================Log File Starts=============================**
2020-01-27 10:32:27.879 [error] Failed to start Ranch listener 'http:management' in ranch_tcp:listen([{cacerts,'...'},{key,'...'},{cert,'...'},{port,8081},{nodelay,true},{send_timeout_close,true},{send_timeout,15000},{backlog,512}]) for reason eacces (permission denied)

2020-01-27 10:32:27.879 [error]     supervisor: {<0.510.0>,ranch_listener_sup}
    errorContext: start_error
    reason: {listen_error,'http:management',eacces}
    offender: [{pid,undefined},
               {id,ranch_acceptors_sup},
               {mfargs,
                   {ranch_acceptors_sup,start_link,
                       ['http:management',ranch_tcp]}},
               {restart_type,permanent},
               {shutdown,infinity},
               {child_type,supervisor}]
2020-01-27 10:32:27.879 [error]   crasher:
    initial call: supervisor:ranch_acceptors_sup/1
    pid: <0.512.0>
    registered_name: []
    exception exit: {listen_error,'http:management',eacces}
      in function  ranch_acceptors_sup:listen_error/5 (c:/emqx/ee/emqx-enterprise-rel/_build/emqx/lib/ranch/src/ranch_acceptors_sup.erl, line 66)
      in call from supervisor:init/1 (supervisor.erl, line 295)
      in call from gen_server:init_it/2 (gen_server.erl, line 374)
      in call from gen_server:init_it/6 (gen_server.erl, line 342)
    ancestors: [<0.510.0>,ranch_sup,<0.153.0>]
    message_queue_len: 0
    messages: []
    links: [<0.510.0>]
    dictionary: [{logger,error_logger}]
    trap_exit: true
    status: running
    heap_size: 2586
    stack_size: 27
    reductions: 7494
  neighbours:

2020-01-27 10:32:27.879 [error]   crasher:
    initial call: application_master:init/4
    pid: <0.507.0>
    registered_name: []
    exception exit: {bad_return,
                     {{emqx_mgmt_app,start,[normal,[]]},
                      {'EXIT',
                       {{badmatch,{error,eacces}},
                        [{minirest,start_http,3,
                          [{file,
                            "c:/emqx/ee/emqx-enterprise-rel/_build/emqx/lib/minirest/src/minirest.erl"},
                           {line,47}]},
                         {lists,foreach,2,[{file,"lists.erl"},{line,1338}]},
                         {emqx_mgmt_app,start,2,
                          [{file,
                            "c:/emqx/ee/emqx-enterprise-rel/_build/emqx/lib/emqx_management/src/emqx_mgmt_app.erl"},
                           {line,30}]},
                         {application_master,start_it_old,4,
                          [{file,"application_master.erl"},{line,277}]}]}}}}
      in function  application_master:init/4 (application_master.erl, line 138)
    ancestors: [<0.506.0>]
    message_queue_len: 1
    messages: [{'EXIT',<0.508.0>,normal}]
    links: [<0.506.0>,<0.43.0>]
    dictionary: []
    trap_exit: true
    status: running
    heap_size: 987
    stack_size: 27
    reductions: 240
  neighbours:

2020-01-27 10:32:27.879 [error] [Plugins] Load plugin emqx_management failed, cannot start plugin emqx_management for {bad_return,
                                                                                       {{emqx_mgmt_app,
                                                                                         start,
                                                                                         [normal,
                                                                                          []]},
                                                                                        {'EXIT',
                                                                                         {{badmatch,
                                                                                           {error,
                                                                                            eacces}},
                                                                                          [{minirest,
                                                                                            start_http,
                                                                                            3,
                                                                                            [{file,
                                                                                              "c:/emqx/ee/emqx-enterprise-rel/_build/emqx/lib/minirest/src/minirest.erl"},
                                                                                             {line,
                                                                                              47}]},
                                                                                           {lists,
                                                                                            foreach,
                                                                                            2,
                                                                                            [{file,
                                                                                              "lists.erl"},
                                                                                             {line,
                                                                                              1338}]},
                                                                                           {emqx_mgmt_app,
                                                                                            start,
                                                                                            2,
                                                                                            [{file,
                                                                                              "c:/emqx/ee/emqx-enterprise-rel/_build/emqx/lib/emqx_management/src/emqx_mgmt_app.erl"},
                                                                                             {line,
                                                                                              30}]},
                                                                                           {application_master,
                                                                                            start_it_old,
                                                                                            4,
                                                                                            [{file,
                                                                                              "application_master.erl"},
                                                                                             {line,
                                                                                              277}]}]}}}}
2020-01-27 10:32:30.864 [critical] The license is expired! System shutdown!
2020-01-27 10:32:30.879 [error]     supervisor: {local,gr_counter_sup}
    errorContext: child_terminated
    reason: killed
    offender: [{pid,<0.730.0>},
               {id,gr_lager_default_tracer_counters},
               {mfargs,{gr_counter,start_link,
                                   [gr_lager_default_tracer_counters]}},
               {restart_type,transient},
               {shutdown,brutal_kill},
               {child_type,worker}]
2020-01-27 10:32:30.879 [error]     supervisor: {local,gr_param_sup}
    errorContext: child_terminated
    reason: killed
    offender: [{pid,<0.729.0>},
               {id,gr_lager_default_tracer_params},
               {mfargs,{gr_param,start_link,[gr_lager_default_tracer_params]}},
               {restart_type,transient},
               {shutdown,brutal_kill},
               {child_type,worker}]
2020-01-27 10:34:35.271 [error] Failed to start Ranch listener 'http:management' in ranch_tcp:listen([{cacerts,'...'},{key,'...'},{cert,'...'},{port,8081},{nodelay,true},{send_timeout_close,true},{send_timeout,15000},{backlog,512}]) for reason eacces (permission denied)

2020-01-27 10:34:35.271 [error]     supervisor: {<0.503.0>,ranch_listener_sup}
    errorContext: start_error
    reason: {listen_error,'http:management',eacces}
    offender: [{pid,undefined},
               {id,ranch_acceptors_sup},
               {mfargs,
                   {ranch_acceptors_sup,start_link,
                       ['http:management',ranch_tcp]}},
               {restart_type,permanent},
               {shutdown,infinity},
               {child_type,supervisor}]
2020-01-27 10:34:35.271 [error]   crasher:
    initial call: application_master:init/4
    pid: <0.500.0>
    registered_name: []
    exception exit: {bad_return,
                     {{emqx_mgmt_app,start,[normal,[]]},
                      {'EXIT',
                       {{badmatch,{error,eacces}},
                        [{minirest,start_http,3,
                          [{file,
                            "c:/emqx/ee/emqx-enterprise-rel/_build/emqx/lib/minirest/src/minirest.erl"},
                           {line,47}]},
                         {lists,foreach,2,[{file,"lists.erl"},{line,1338}]},
                         {emqx_mgmt_app,start,2,
                          [{file,
                            "c:/emqx/ee/emqx-enterprise-rel/_build/emqx/lib/emqx_management/src/emqx_mgmt_app.erl"},
                           {line,30}]},
                         {application_master,start_it_old,4,
                          [{file,"application_master.erl"},{line,277}]}]}}}}
      in function  application_master:init/4 (application_master.erl, line 138)
    ancestors: [<0.499.0>]
    message_queue_len: 1
    messages: [{'EXIT',<0.501.0>,normal}]
    links: [<0.499.0>,<0.43.0>]
    dictionary: []
    trap_exit: true
    status: running
    heap_size: 987
    stack_size: 27
    reductions: 240
  neighbours:

2020-01-27 10:34:35.271 [error]   crasher:
    initial call: supervisor:ranch_acceptors_sup/1
    pid: <0.505.0>
    registered_name: []
    exception exit: {listen_error,'http:management',eacces}
      in function  ranch_acceptors_sup:listen_error/5 (c:/emqx/ee/emqx-enterprise-rel/_build/emqx/lib/ranch/src/ranch_acceptors_sup.erl, line 66)
      in call from supervisor:init/1 (supervisor.erl, line 295)
      in call from gen_server:init_it/2 (gen_server.erl, line 374)
      in call from gen_server:init_it/6 (gen_server.erl, line 342)
    ancestors: [<0.503.0>,ranch_sup,<0.153.0>]
    message_queue_len: 0
    messages: []
    links: [<0.503.0>]
    dictionary: [{logger,error_logger}]
    trap_exit: true
    status: running
    heap_size: 2586
    stack_size: 27
    reductions: 7494
  neighbours:

2020-01-27 10:34:35.287 [error] [Plugins] Load plugin emqx_management failed, cannot start plugin emqx_management for {bad_return,
                                                                                       {{emqx_mgmt_app,
                                                                                         start,
                                                                                         [normal,
                                                                                          []]},
                                                                                        {'EXIT',
                                                                                         {{badmatch,
                                                                                           {error,
                                                                                            eacces}},
                                                                                          [{minirest,
                                                                                            start_http,
                                                                                            3,
                                                                                            [{file,
                                                                                              "c:/emqx/ee/emqx-enterprise-rel/_build/emqx/lib/minirest/src/minirest.erl"},
                                                                                             {line,
                                                                                              47}]},
                                                                                           {lists,
                                                                                            foreach,
                                                                                            2,
                                                                                            [{file,
                                                                                              "lists.erl"},
                                                                                             {line,
                                                                                              1338}]},
                                                                                           {emqx_mgmt_app,
                                                                                            start,
                                                                                            2,
                                                                                            [{file,
                                                                                              "c:/emqx/ee/emqx-enterprise-rel/_build/emqx/lib/emqx_management/src/emqx_mgmt_app.erl"},
                                                                                             {line,
                                                                                              30}]},
                                                                                           {application_master,
                                                                                            start_it_old,
                                                                                            4,
                                                                                            [{file,
                                                                                              "application_master.erl"},
                                                                                             {line,
                                                                                              277}]}]}}}}
2020-01-27 10:54:31.026 [warning] [Alarm Handler] New Alarm: system_memory_high_watermark, Alarm Info: []
2020-01-27 10:54:55.757 [error] <<"bench-pub-Test500-eid_23-100436275">>@10.87.1.200:50279 [CM] Failed to discard <0.2506.0>: {noproc,
                                    {gen_server,call,
                                     [<0.2506.0>,discard,infinity]}}
2020-01-27 10:54:55.819 [error] <<"bench-pub-Test500-eid_23-100436275">>@10.87.1.200:50281 [CM] Failed to discard <0.2511.0>: {noproc,
                                    {gen_server,call,
                                     [<0.2511.0>,discard,infinity]}}
2020-01-27 11:03:20.388 [error] <<"bench-pub-Test500-eid_15-939104554">>@10.87.1.3:55698 [CM] Failed to discard <0.4310.0>: {{shutdown,tcp_closed},
                                    {gen_server,call,
                                     [<0.4310.0>,discard,infinity]}}
2020-01-27 11:03:27.483 [error] <<"bench-pub-Test500-eid_7-1154016842">>@10.87.1.3:55907 [CM] Failed to discard <0.4388.0>: {noproc,
                                    {gen_server,call,
                                     [<0.4388.0>,discard,infinity]}}
2020-01-27 11:03:27.498 [error] <<"bench-pub-Test500-eid_0-2019727887">>@10.87.1.3:55908 [CM] Failed to discard <0.4387.0>: {noproc,
                                    {gen_server,call,
                                     [<0.4387.0>,discard,infinity]}}
2020-01-27 11:07:01.325 [error] <<"bench-pub-EMSDev300-eid_7-608140205">>@10.87.1.75:55983 [CM] Failed to discard <0.5580.0>: {noproc,
                                    {gen_server,call,
                                     [<0.5580.0>,discard,infinity]}}
2020-01-27 11:07:03.310 [error] <<"bench-pub-Test500-eid_93-1100440517">>@10.87.1.200:50524 [CM] Failed to discard <0.5609.0>: {noproc,
                                    {gen_server,call,
                                     [<0.5609.0>,discard,infinity]}}
2020-01-27 11:07:18.656 [error] <<"bench-pub-Test500-eid_97-1000017184">>@10.87.1.200:50526 [CM] Failed to discard <0.5739.0>: {noproc,
                                    {gen_server,call,
                                     [<0.5739.0>,discard,infinity]}}
2020-01-27 11:07:19.172 [error] <<"bench-pub-Test500-eid_97-1000017184">>@10.87.1.200:50533 [CM] Failed to discard <0.5757.0>: {noproc,
                                    {gen_server,call,
                                     [<0.5757.0>,discard,infinity]}}
2020-01-27 11:07:19.375 [error] <<"bench-pub-Test500-eid_97-1000017184">>@10.87.1.200:50535 [CM] Failed to discard <0.5763.0>: {noproc,
                                    {gen_server,call,
                                     [<0.5763.0>,discard,infinity]}}
2020-01-27 11:07:20.812 [error] <<"bench-pub-EMSDev300-eid_66-494577938">>@10.87.1.75:55993 [CM] Failed to discard <0.5776.0>: {noproc,
                                    {gen_server,call,
                                     [<0.5776.0>,discard,infinity]}}
2020-01-27 11:07:25.344 [error] <<"bench-pub-EMSDev300-eid_83-1828644497">>@10.87.1.75:55997 [CM] Failed to discard <0.5815.0>: {noproc,
                                    {gen_server,call,
                                     [<0.5815.0>,discard,infinity]}}
2020-01-27 11:07:45.550 [error] <<"bench-pub-EMSDev300-eid_65-774938156">>@10.87.1.75:56017 [CM] Failed to discard <0.6254.0>: {noproc,
                                    {gen_server,call,
                                     [<0.6254.0>,discard,infinity]}}
2020-01-27 11:07:45.722 [error] <<"bench-pub-Test500-eid_18-1439609312">>@10.87.1.200:50559 [CM] Failed to discard <0.6237.0>: {noproc,
                                    {gen_server,call,
                                     [<0.6237.0>,discard,infinity]}}
2020-01-27 11:07:58.802 [error] <<"bench-pub-EMSDev300-eid_60-422478917">>@10.87.1.75:56026 [CM] Failed to discard <0.6415.0>: {{shutdown,tcp_closed},
                                    {gen_server,call,
                                     [<0.6415.0>,discard,infinity]}}
2020-01-27 11:07:59.115 [error] <<"bench-pub-Test500-eid_0-2019727887">>@10.87.1.200:50580 [CM] Failed to discard <0.6410.0>: {{shutdown,tcp_closed},
                                    {gen_server,call,
                                     [<0.6410.0>,discard,infinity]}}
2020-01-27 11:08:09.460 [error] <<"bench-pub-Test500-eid_33-1966930476">>@10.87.1.200:50590 [CM] Failed to discard <0.6534.0>: {{shutdown,tcp_closed},
                                    {gen_server,call,
                                     [<0.6534.0>,discard,infinity]}}
2020-01-27 11:08:09.772 [error] <<"bench-pub-Test500-eid_73-1855913139">>@10.87.1.200:50593 [CM] Failed to discard <0.6540.0>: {noproc,
                                    {gen_server,call,
                                     [<0.6540.0>,discard,infinity]}}
2020-01-27 11:08:11.569 [error] <<"bench-pub-Test500-eid_51-1632137862">>@10.87.1.200:50602 [CM] Failed to discard <0.6557.0>: {noproc,
                                    {gen_server,call,
                                     [<0.6557.0>,discard,infinity]}}
2020-01-27 11:08:11.694 [error] <<"bench-pub-Test500-eid_13-1629163505">>@10.87.1.200:50604 [CM] Failed to discard <0.6567.0>: {noproc,
                                    {gen_server,call,
                                     [<0.6567.0>,discard,infinity]}}
2020-01-27 11:08:13.898 [error] <<"bench-pub-EMSDev300-eid_62-91551882">>@10.87.1.75:56038 [CM] Failed to discard <0.6587.0>: {noproc,
                                    {gen_server,call,
                                     [<0.6587.0>,discard,infinity]}}
2020-01-27 11:08:14.132 [error] <<"bench-pub-EMSDev300-eid_62-91551882">>@10.87.1.75:56040 [CM] Failed to discard <0.6593.0>: {noproc,
                                    {gen_server,call,
                                     [<0.6593.0>,discard,infinity]}}
2020-01-27 11:08:19.867 [error] <<"bench-pub-Test500-eid_16-216895989">>@10.87.1.200:50610 [CM] Failed to discard <0.6632.0>: {noproc,
                                    {gen_server,call,
                                     [<0.6632.0>,discard,infinity]}}
2020-01-27 11:08:21.868 [error] <<"bench-pub-Test500-eid_0-2019727887">>@10.87.1.200:50615 [CM] Failed to discard <0.6650.0>: {noproc,
                                    {gen_server,call,
                                     [<0.6650.0>,discard,infinity]}}
2020-01-27 11:08:21.868 [error] <<"bench-pub-Test500-eid_0-2019727887">>@10.87.1.200:50615 [CM] Failed to discard <0.6661.0>: {noproc,
                                    {gen_server,call,
                                     [<0.6661.0>,discard,infinity]}}
2020-01-27 11:08:24.243 [error] <<"bench-pub-EMSDev300-eid_94-1542624959">>@10.87.1.75:56046 [CM] Failed to discard <0.6687.0>: {noproc,
                                    {gen_server,call,
                                     [<0.6687.0>,discard,infinity]}}
2020-01-27 11:08:59.498 [error] <<"bench-pub-EMSDev300-eid_30-70386781">>@10.87.1.75:56065 [CM] Failed to discard <0.7070.0>: {noproc,
                                    {gen_server,call,
                                     [<0.7070.0>,discard,infinity]}}
2020-01-27 11:08:59.591 [error] <<"bench-pub-EMSDev300-eid_30-70386781">>@10.87.1.75:56066 [CM] Failed to discard <0.7076.0>: {noproc,
                                    {gen_server,call,
                                     [<0.7076.0>,discard,infinity]}}
**2020-01-27 11:09:07.186 [error] <<"bench-pub-Test500-eid_37-36166122">>@10.87.1.200:50668 [CM] Failed to discard <0.7138.0>: {{shutdown,tcp_closed},
                                    {gen_server,call,
                                     [<0.7138.0>,discard,infinity]}}**
**=====================Log File Ends=============================**

**Comment by emqplus** [comment]
@arvindh123 Do you tune the Kernel to support more than 1K concurrent connections?

The tune guide: https://docs.emqx.io/broker/latest/en/tune.html#tuning-guide

**Comment by arvindh123** [comment]
No , I didn't tuned Kernel, The tune guide have already gone through, but here its windows server, so I don't know to tune the kernel in windows. If anybody know in windows, please guide me.

**Comment by emqplus** [comment]
@HJianBo Please check if the `noproc` exception should be ignored?

**Comment by arvindh123** [comment]
I tried the same thing with EMQX 3.2.7 , 
I am getting the below warnings 

**2020-01-27 15:31:13.310 [warning] <<"bench-pub-Test500-eid_0-2019727887">>@10.87.60.253:54491 [Channel] Discarded by bench-pub-Test500-eid_0-2019727887:<0.4847.0>**

**2020-01-27 15:31:13.310 [warning] <<"bench-pub-Test500-eid_1-1427131847">>@10.87.60.253:54492 [Channel] Discarded by bench-pub-Test500-eid_1-1427131847:<0.4850.0>**

**2020-01-27 15:31:13.310 [warning] <<"bench-pub-Test500-eid_6-1106410694">>@10.87.60.253:54500 [Channel] Discarded by bench-pub-Test500-eid_6-1106410694:<0.4868.0>**

What does this warning means ? Weather the Client is getting disconnected and trying to connect with same client ID ?

**Comment by emqplus** [comment]
@arvindh123 The logs mean there are two MQTT connections with the same clientId. The later `CONNECT` kicked out the older one. In EMQX 4.0 release, there is a race condition issue, that an unnecessary `error` log is printed when kicking out an older disconnecting client.

**Comment by emqplus** [comment]
@HJianBo Please submit an PR to fix the issue.

**Comment by arvindh123** [comment]
Thanks @emqplus

**Comment by arvindh123** [comment]
@emqplus , In EMQX 4.0, the both errors  **noproc** and **shutdown,tcp_closed** are unnecessary error log? and the both errors are printed when kicking out an older disconnecting client.?

**2020-01-27 17:54:12.203 [error] <<"bench-pub-Test500-eid_25-602113115">>@10.87.1.200:53146 [CM] Failed to discard <0.21079.0>: {noproc,
                                     {gen_server,call,
                                      [<0.21079.0>,discard,infinity]}}**
**2020-01-27 17:54:14.074 [error] <<"bench-pub-Test500-eid_46-150360866">>@10.87.1.200:53149 [CM] Failed to discard <0.21119.0>: {{shutdown,tcp_closed},
                                     {gen_server,call,
                                      [<0.21119.0>,discard,infinity]}}
}**

**Comment by HJianBo** [comment]
Yes, These are unnecessary logs. This content actually means that the session kicked out successfully, We're just not dealing with race conditions completely.

We will submit a PR to fix it.  Thanks for your feedback @arvindh123

**Comment by HJianBo** [comment]
Hi, @arvindh123 We have fixed it and released v4.0.3
