### ISSUE TITLE
Client session management

### ISSUE THREAD

**Issue by sreeram103610** [emqx/emqx#3226]
#### Environment

- OS: Ubuntu 18.04
- Erlang/OTP:  #22.2
- EMQ: 4.0.1

#### Description ####

I've gone through the documentation for emq clustering but i couldn't find a clear explanation for how session management is done. I understand topics table is shared among clustered nodes but client connection information is not? What happens if a node goes down? Would it loose all the info about client sessions it was managing?

**Comment by turtleDeng** [comment]
Thank you for your participation.
In emqx4.0, connection and session are merged.
Session management is in the client, you can view it through the dashboard.
If a node fails, the session of this node will be lost.
If you need to make high availability, then it is recommended that you choose a persistence solution.

**Comment by turtleDeng** [comment]
Thank you for your participation, we will close this issue, if there are any problems, you can reopen.
