### ISSUE TITLE
Does emqx supports both cert based auth and password based auth simultaneously  ?

### ISSUE THREAD

**Issue by Jeyanthinath** [emqx/emqx#3227]
Does emqx supports both cert based auth and password based auth simultaneously ?

I have some devices doesn't have cert auth capabilities , but some do , so I want to enable either one of those. can I enable these type of auth.

I don't see a documentation regarding this

**Comment by tigercl** [comment]
@Jeyanthinath Sorry for late reply, you can modify `emqx.conf` to meet your needs. `emqx` supports different configurations for clients accessing through different ports. For example, The listener named `listener.*.internal` will use configuration named `zone.internal.*`. You can add new zones or new listeners for yourself just like those that already exist.

**Comment by HJianBo** [comment]
Hi, @Jeyanthinath Any question remaining here?

**Comment by Jeyanthinath** [comment]
Hi @tigercl thanks for the help. @HJianBo nope , 

Thanks guys for the great support ❤️
