### ISSUE TITLE
RabbitMQ Configuration Not Working

### ISSUE THREAD

**Issue by beraybentesen** [emqx/emqx#3229]
The following is the configuration, however it is not working and I don't know how to debug. 

`EMQX_BRIDGE__MQTT__AWS__ADDRESS: "rabbitclusterip:1883"
  EMQX_BRIDGE__MQTT__AWS__PROTO_VER: "mqttv4"
  EMQX_BRIDGE__MQTT__AWS__CLIENT_ID: "emqx"
  EMQX_BRIDGE__MQTT__AWS__CLEAN_START: "true"
  EMQX_BRIDGE__MQTT__AWS__USERNAME: "rabbit"
  EMQX_BRIDGE__MQTT__AWS__PASSWORD: "123456"
  EMQX_BRIDGE__MQTT__AWS__CLEAN_START: "true"
  EMQX_BRIDGE__MQTT__AWS__MOUNTPOINT: "/bridge/aws/${node}/"
  EMQX_BRIDGE__MQTT__AWS__SSL: "off"
  EMQX_BRIDGE__MQTT__AWS__KEEPALIVE: "60s"
  EMQX_BRIDGE__MQTT__AWS__FORWARDS: "$SYS/brokers/emqx@127.0.0.1/metricss/messages/received"
  EMQX_BRIDGE__MQTT__AWS__TOPIC: "+,$SYS/brokers/emqx@127.0.0.1/clients/+/connected,$SYS/brokers/emqx@127.0.0.1/clients/+/disconnected,$SYS/brokers/emqx@127.0.0.1/metricss/messages/received"
  EMQX_BRIDGE__MQTT__BRIDGE__MODE: "false"
  EMQX_BRIDGE__MQTT__AWS__MAX_INFLIGHT_BATCHES: "8"
  EMQX_BRIDGE__MQTT__AWS__QUEUE__REPLAYQ_DIR: "data/emqx_aws_bridge/"`

**Comment by turtleDeng** [comment]
Thank you for your participation, please provide detailed version and log.

**Comment by beraybentesen** [comment]
Hi, 

Version 4.0.1

Debug log: It stuck on [Bridge] Bridge emqx_bridge_worker_aws is connecting..... 

However I am able to connect through mqtt ide or by programmatically with the same credentials.

**Comment by beraybentesen** [comment]
I also found that the following error from the rabbitmq log :

MQTT connection "ip -> ip" will terminate because peer closed TCP connection

**Comment by beraybentesen** [comment]
Hi @tigercl ;

I am able to see connection and queue but data is not published to the queue. No error in the logs (both emqx and rabbitmq) so is there any chance you might help us ? Thank you.

**Comment by turtleDeng** [comment]
Message bridged to rabbitmq with topic /bridge/aws/${node}/${topic}

```
EMQX_BRIDGE__MQTT__AWS__ADDRESS: "rabbitclusterip:1883"
EMQX_BRIDGE__MQTT__AWS__PROTO_VER: "mqttv4"
EMQX_BRIDGE__MQTT__AWS__CLIENT_ID: "emqx"
EMQX_BRIDGE__MQTT__AWS__CLEAN_START: "true"
EMQX_BRIDGE__MQTT__AWS__USERNAME: "rabbit"
EMQX_BRIDGE__MQTT__AWS__PASSWORD: "123456"
EMQX_BRIDGE__MQTT__AWS__CLEAN_START: "true"
EMQX_BRIDGE__MQTT__AWS__MOUNTPOINT: "/bridge/aws/${node}/"
EMQX_BRIDGE__MQTT__AWS__SSL: "off"
EMQX_BRIDGE__MQTT__AWS__KEEPALIVE: "60s"
EMQX_BRIDGE__MQTT__AWS__FORWARDS: "$SYS/brokers/emqx@127.0.0.1/metricss/messages/received"
EMQX_BRIDGE__MQTT__AWS__TOPIC: "+,$SYS/brokers/emqx@127.0.0.1/clients/+/connected,$SYS/brokers/emqx@127.0.0.1/clients/+/disconnected,$SYS/brokers/emqx@127.0.0.1/metricss/messages/received"
EMQX_BRIDGE__MQTT__BRIDGE__MODE: "false"
EMQX_BRIDGE__MQTT__AWS__MAX_INFLIGHT_BATCHES: "8"
EMQX_BRIDGE__MQTT__AWS__QUEUE__REPLAYQ_DIR: "data/emqx_aws_bridge/"
```
You can read the configuration instructions to determine what each configuration does
https://github.com/emqx/emqx-bridge-mqtt/blob/master/etc/emqx_bridge_mqtt.conf

**Comment by beraybentesen** [comment]
Could you please confirm that the syntax "$SYS/brokers/emqx@127.0.0.1/metricss/messages/received" and "+,$SYS/brokers/emqx@127.0.0.1/clients/+/connected,$SYS/brokers/emqx@127.0.0.1/clients/+/disconnected,$SYS/brokers/emqx@127.0.0.1/metricss/messages/received" are same for the version 4 ? 

It was working on version 3.

**Comment by turtleDeng** [comment]
Sorry, there is no EMQX_BRIDGE__MQTT__AWS__TOPIC configuration in both 3.X and 4.X
You can read the configuration instructions to determine what each configuration does
https://github.com/emqx/emqx-bridge-mqtt/blob/master/etc/emqx_bridge_mqtt.conf

**Comment by beraybentesen** [comment]
@turtleDeng I solved the problem by updating the configuration for version 4.+. 

However, it seems `$SYS/brokers/${node}/clients/${clientid}/connected ` not working. I assume it is correct regarding the documentation. Could you please check the syntax ? Thanks,

**Comment by turtleDeng** [comment]
If you do n’t know the specific node name, you can use wildcards to subscribe
```
$SYS/brokers/+/clients/+/connected
```

**Comment by turtleDeng** [comment]
Thanks for your participation, we will close this issue.
