### ISSUE TITLE
kubernetes ssl(8883) with letsencrypt

### ISSUE THREAD

**Issue by rauntska** [emqx/emqx#3231]
Hi,

Im running emqx as a container in azure kubernetes. Got a separate persistentVolume mapped for configuration loading.

Would really love to setup the ssl communication for port 8883. So far i've read that you can set it up using the configuration in:
```
listener.ssl.external.keyfile = etc/certs/server.key
listener.ssl.external.certfile = etc/certs/server-cert.pem
```

Although it would be superb to be able to use letsencrypt to avoid manual cert updating every year. I've read that letencrypt can be set up using ingress and cert-manager, however im not sure if this will work since the configuration still expects a path to the cert ? 

How should the general setup/ config be if using letsencrypt for port 8883.

Thanks, Rauno

**Comment by zhanghongtong** [comment]
Hi, @rauntska 
You can run letsencrypt in a separate pod and share the certificate path generated by letsencrypt with emqx pods through volume

**Comment by HJianBo** [comment]
@rauntska It seems an outdated issue. Do you resolve this problem? This [post](https://www.emqx.io/blog/using-lets-encrypt-certificates-in-emq) maybe help to you

I close it first, Plz let me known if you have more problems

**Comment by Tautcius** [comment]
> @rauntska It seems an outdated issue. Do you resolve this problem? This [post](https://www.emqx.io/blog/using-lets-encrypt-certificates-in-emq) maybe help to you
> 
> I close it first, Plz let me known if you have more problems

Could you please give update how to map certificate files in kubernetes or with Helm chart?
