### ISSUE TITLE
Web interface not accessible after starting EMQX

### ISSUE THREAD

**Issue by rgaufman** [emqx/emqx#3232]
#### Environment

- OS: Ubuntu 18.04.4 LTS
- Erlang/OTP: provided by package?
- EMQ: emqx-ee-ubuntu18.04-v3.4.5_amd64.deb

#### Description

EMQx was operating well with around 600 clients, I needed to restart it to change the ACL config, it started up but not working correctly, the web interface is reporting:

```
wget http://timeline.is:18083
--2020-02-03 19:38:11--  http://timeline.is:18083/
Resolving timeline.is (timeline.is)... 109.74.192.189
Connecting to timeline.is (timeline.is)|109.74.192.189|:18083... connected.
HTTP request sent, awaiting response... 500 Internal Server Error
2020-02-03 19:38:13 ERROR 500: Internal Server Error.
```

I'm not seeing any errors and clients annoy connect reliably and those that connect die after a while:

```
Cause: Errno::EPIPE: Broken pipe
```

emqx is eating around 180% CPU:

```
  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND
31182 emqx      20   0 2557000 399372   6860 S 180.8  9.9  35:32.75 /usr/lib/emqx/erts-10.3.5.4/bin/beam.smp -spp true -e 256000 -Q 1024000 -P 2048000 -A 32 -zdbbl 8192 --+
```

Any ideas?

**Comment by rgaufman** [comment]
it seems after around 15 minutes, the load stabilised to 150% cpu and now messages are being delivered, but web interface still throwing ERROR 500

**Comment by tigercl** [comment]
@rgaufman Could you provide the log of emqx so that we can help you find the problem?

**Comment by rgaufman** [comment]
Nothing at all in the logs, the log-level is set to error, if I set it to info, everything crawls to a halt, how would I troubleshoot?

Before restarting EMQx, CPU was low, now it is this:

<img width="306" alt="Screenshot 2020-02-04 at 09 27 39" src="https://user-images.githubusercontent.com/33842342/73731573-a4605380-4730-11ea-8ed3-c286461fa950.png">

Tearing my hair out, tried upgrading to latest 3.x version: 3.4.5 which didn't help, and possibly is what caused the high CPU?

**Comment by HJianBo** [comment]
Hi, @rgaufman  Thanks for your feedback. It could also be a normal drain on resources if nothing goes wrong.

Before that, we need to clarify the next few questions：
1. Whether dashboard can't be accessed before and after the restart
2. How many cores and memory on the host
3. After restarting emqx, will the client immediately reconnect and subscribe to a large number of topics? Do these topics have many levels and contain wildcards?
4. After stabilization, the approximate amount of message throughput in emqx

**Comment by rgaufman** [comment]
I tried everything and eventually the only thing that would resolve it is to completely delete the mnesia database and re-create it from an older backup :(
