### ISSUE TITLE
Debug log level problem.

### ISSUE THREAD

**Issue by RodaBVB** [emqx/emqx#3241]
#### Environment

- OS: Ubuntu 16.04.5 LTS
- Erlang/OTP: 18 
- EMQ: 3.2.2

**Topology**

- 2x EMQX in cluster (4vCPU, 4GB RAM each)

#### Description

Client publishes a payload containing an apostrophe (’), In broker logs when verbosity is set to "Debug", a loss of parsing occurs. See the logs below.

If necessary I can share you a small nodejs application that runs subscribe/publish messages and reproduce this problem.

**Test case 1, working:**
Payload: { "payload_message" : "Payload without apostrophe, working" }

```
(emqx@127.0.0.1)1> 2020-02-07 09:41:34.571 [debug] client_mqtt@127.0.0.1:41206 [Protocol] RECV PUBLISH(Q0, R0, D0, Topic=topic, PacketId=undefined, Payload=<<"{ \"payload_message\" : \"Payload without apostrophe, working\" }">>)
(emqx@127.0.0.1)1> 2020-02-07 09:41:34.572 [info] client_mqtt@127.0.0.1:41206 PUBLISH to topic: <<"{ \"payload_message\" : \"Payload without apostrophe, working\" }">>
(emqx@127.0.0.1)1> 2020-02-07 09:41:34.572 [debug] client_mqtt@127.0.0.1:41206 [Protocol] SEND PUBLISH(Q0, R0, D0, Topic=topic, PacketId=undefined, Payload=<<"{ \"payload_message\" : \"Payload without apostrophe, working\" }">>)
2020-02-07 09:41:34.571 [debug] client_mqtt@127.0.0.1:41206 [Protocol] RECV PUBLISH(Q0, R0, D0, Topic=topic, PacketId=undefined, Payload=<<"{ \"payload_message\" : \"Payload without apostrophe, working\" }">>)
2020-02-07 09:41:34.572 [info] client_mqtt@127.0.0.1:41206 PUBLISH to topic: <<"{ \"payload_message\" : \"Payload without apostrophe, working\" }">>
2020-02-07 09:41:34.572 [debug] client_mqtt@127.0.0.1:41206 [Protocol] SEND PUBLISH(Q0, R0, D0, Topic=topic, PacketId=undefined, Payload=<<"{ \"payload_message\" : \"Payload without apostrophe, working\" }">>)
```
**Test case 2, not working:**
Payload: { "payload_message" : "Payload with apostrophe, not working  (’)" } 
```
(emqx@127.0.0.1)1> 2020-02-07 09:41:48.640 [debug] client_mqtt@127.0.0.1:41208 [Protocol] RECV PUBLISH(Q0, R0, D0, Topic=topic, PacketId=undefined, Payload=<<123,32,34,112,97,121,108,111,97,100,
(emqx@127.0.0.1)1> 2020-02-07 09:41:48.641 [info] client_mqtt@127.0.0.1:41208 PUBLISH to topic: <<123,32,34,112,97,121,108,111,97,100,95,109,101,115,115,97,
(emqx@127.0.0.1)1> 2020-02-07 09:41:48.641 [debug] client_mqtt@127.0.0.1:41208 [Protocol] SEND PUBLISH(Q0, R0, D0, Topic=topic, PacketId=undefined, Payload=<<123,32,34,112,97,121,108,111,97,100,
2020-02-07 09:41:48.640 [debug] client_mqtt@127.0.0.1:41208 [Protocol] RECV PUBLISH(Q0, R0, D0, Topic=topic, PacketId=undefined, Payload=<<123,32,34,112,97,121,108,111,97,100,
2020-02-07 09:41:48.641 [info] client_mqtt@127.0.0.1:41208 PUBLISH to topic: <<123,32,34,112,97,121,108,111,97,100,95,109,101,115,115,97,
2020-02-07 09:41:48.641 [debug] client_mqtt@127.0.0.1:41208 [Protocol] SEND PUBLISH(Q0, R0, D0, Topic=topic, PacketId=undefined, Payload=<<123,32,34,112,97,121,108,111,97,100,
```
**Note:** 
Please copy/paste this payload for test, only this specific ’ symbol not working
![Screenshot from 2020-02-07 09-56-06](https://user-images.githubusercontent.com/20912951/74015033-28644680-4990-11ea-9cce-b24040c751ad.png)

**Comment by tigercl** [comment]
@RodaBVB Sorry for late reply and thanks for your feedback.  I tried to send the payload with the apostrophe you gave in emqx v3.2.2 and v4.0.2,  but this special character only affects printing and does not affect internal parsing. So you can tell me what client you used, so that I can reproduce this problem.

**Comment by RodaBVB** [comment]
Try this:

Problem is reproducible with our custom NodeJS mqtt_client script which is attached [mqtt_client.zip](https://github.com/emqx/emqx/files/4243878/mqtt_client.zip)

Requires NodeJS 8.7.0. After unpack, execute by running: node index.js

**Emqx configure:** 
allow all in acl.conf file `{allow, all}.` and set log level to debug. 

**Note:**

Problematic payload is located in test.json, try with and without an apostrophe. 

`{ "payload_message" : "Payload with apostrophe, not working  (’)" }` or
`{ "payload_message" : "Payload without apostrophe, working" }`

**Comment by HJianBo** [comment]
Hi, @RodaBVB Some complex visible string will be printed with the original bytes. The logs only supported printing standard ASCII chars.

We have no plans to optimize these kinds of problems. Thanks for your feedback there :)
