### ISSUE TITLE
Allow wildcards on the Who section of the ACL rules

### ISSUE THREAD

**Issue by lcofre** [emqx/emqx#3242]
#### Environment

- OS: Ubuntu 18.04.3 LTS
- Erlang/OTP: 
- EMQ: docker tag v4.0.2

#### Description

As [explained here](https://github.com/emqx/emqx/issues/2677#issuecomment-509485016) the ACL rules in acl.conf do not allow the wildcards "%c" and "%u" in the Who section.

I would like to request this to be allowed. "%c" and "%u" are already allowed in Topics sections so it seems reasonable to allow it also in the Who section.

Currently I implemented the behaviour using the emqx-auth-mongo plugin, but I am facing performance issues because of accessing the external mongodb database in the ACL check. I also need an extra process inserting the ACL rules to the database.
This change would greatly simplify my ACL implementation.

Thanks very much for your help in this matter.

**Comment by HJianBo** [comment]
> "%c" and "%u" are already allowed in Topics sections so it seems reasonable to allow it also in the Who section.

I don't think that's reasonable. WHO, TOPIC section is not equivalent.

For example:
```
{allow, all, subscribe, ["%u/#"]}.
```

It indicates all users are allowed to subscribe `<username>/#` topic. (i.g:  `foo` can subscribe `foo/#`). 

But I don't know exactly what it does if we put wildcards in the WHO section?

**Comment by lcofre** [comment]
That's exactly what I need
```
{allow, all, subscribe, ["prefix/%u/#"]}.
```

Was this always the behaviour? Look at the answer I got in this issue https://github.com/emqx/emqx/issues/2677#issuecomment-509485016

Thanks a million for your help @HJianBo !

**Comment by HJianBo** [comment]
Yes, it does. The previous answer is outdate! You can try it later

I'll close it. Please reopen it If you have any remaining problems

**Comment by lcofre** [comment]
That's excellent @HJianBo! Thanks very much, it working perfectly for me.

Can you point me to the PR, commit or issue that made the change? I went through the release notes but can't find it.

Thanks again!

**Comment by HJianBo** [comment]
I haven't found this yet, but I remember that both 4.x and 3.x should be supported
