### ISSUE TITLE
Disconnected client receives messages on shared subscription

### ISSUE THREAD

**Issue by mariusstaicu** [emqx/emqx#3243]
#### Environment

OS: GKE OS
Erlang/OTP: 21.2
EMQ: v4.0.1

#### Description

I have a cluster emqx setup on Kubernetes. 
I am consuming with 3 clients from multiple topics using shared subscription with both qos 0 and qos 1.

I have also zone.external.mqueue.store.qos0 = false. All clients have clean session = false.

Whenever I take an mqtt client down, the broker saves the session and stores 1/3 of qos 1 messages in mqueue of disconnected client and also drops 1/3 of qos0 messages. Both which seem to me incorrect. Why save shared messages for a disconnected client. Why not make the rest of clients in the shared group receive the messages which cannot be received by disconnected client ? 

The question is: Shouldn't shared subscription balance only between connected(active) clients in a shared group ? The current behavior shows that clients in a shared subscription receive messages no matter if they're connected or not.

**Comment by tigercl** [comment]
@mariusstaicu Because the `Clean Session` is false. I  think our operation is in accordance with the MQTT spec:
> If the Server is in the process of sending a QoS 1 message to its chosen subscribing Client and the connection to that Client breaks before the Server has received an acknowledgement from the Client, the Server MAY wait for the Client to reconnect and retransmit the message to that Client. If the Client'sSession terminates before the Client reconnects, the Server SHOULD send the Application Message to another Client that is subscribed to the same Shared Subscription. It MAY attempt to send the message to another Client as soon as it loses its connection to the first Client.

**Comment by mariusstaicu** [comment]
Right, wasn't aware of that. Thanks for enlightening me. Then it seems more apropriate to use clean session true for shared subscription.

**Comment by mariusstaicu** [comment]
Ok, I have the following case: 
Two instances (client-0 and client-1) consuming on shared subscription with clean session false and expiry 90 seconds. 
Client-1 disconnects, some of the QOS 1 messages intended for client-1 are retained in mqueue as expected. The session for client-1 expires before client-1 reconnects. The retained messages are not sent to client-0 as expected according to 
> If the Client'sSession terminates before the Client reconnects, the Server SHOULD send the Application Message to another Client that is subscribed to the same Shared Subscription

instead they are lost.

Also, I know this is from MQTT 5.0 protocol and I'm using a v3.1.1 compatible client. My question is: will this work if I use a mqtt 5.0 compatible client ?

**Comment by nishant-logistiq** [comment]
> Ok, I have the following case: Two instances (client-0 and client-1) consuming on shared subscription with clean session false and expiry 90 seconds. Client-1 disconnects, some of the QOS 1 messages intended for client-1 are retained in mqueue as expected. The session for client-1 expires before client-1 reconnects. The retained messages are not sent to client-0 as expected according to
> 
> > If the Client'sSession terminates before the Client reconnects, the Server SHOULD send the Application Message to another Client that is subscribed to the same Shared Subscription
> 
> instead they are lost.
> 
> Also, I know this is from MQTT 5.0 protocol and I'm using a v3.1.1 compatible client. My question is: will this work if I use a mqtt 5.0 compatible client ?

@mariusstaicu Is this issue resolved? I am facing a similar issue. If this resolved kindly share the steps you had taken to resolve this.

**Comment by zmstone** [comment]
> If the Client'sSession terminates before the Client reconnects, the Server SHOULD send the Application Message to another Client that is subscribed to the same Shared Subscription

Has been fixed since 5.0.9: https://github.com/emqx/emqx/pull/9104

**Comment by mariusstaicu** [comment]
Yeah, fixed by upgrade.
