### ISSUE TITLE
Node not responding/ can't assign name to EMQX

### ISSUE THREAD

**Issue by kilianbr** [emqx/emqx#3244]
#### Environment

- OS: Raspbian GNU/Linux 10 (buster)"
- Erlang/OTP: [can't find destribution, used emqx/emqx:latest image]
- EMQ: 4.0.2

#### Description

Hello everyone, 
I'm troubling changing the hostname of my broker to get emqx running. If I set the hostname of my broker, there's an error message about my host-node not responding to pings. I can ping the given 

![image](https://user-images.githubusercontent.com/47358065/74158920-2feb5000-4c1b-11ea-82bd-1f8018e4d9fa.png)

My config file looks like the following: 
```
docker run -d --name emqx -p 1883:1883 -p 18083:18083 -p 8083:8083 -p 4369:4369 -p 5369:5369 -p 6369:6369 \
>  -e EMQX_NODE__NAME=4pi2@1.0.0.42 \
>  -e EMQX_NODE__COOKIE=somepw \
>  -e EMQX_RETAINER__EXPIRY_INTERVAL=7s \
>  -e EMQX_OS_MON__CPU_HIGH_WATERMARK=100% \
>  -e EMQX_LOG__TO=console \
>  -e EMQX_LISTENER__TCP__INTERNAL=127.0.0.1:11883 \
>  emqx/emqx:latest
```

**Working without specification**
If I change my config file to the following wothout specification of the hostname: 

 ```
docker run -d --name emqx -p 1883:1883 -p 18083:18083 -p 8083:8083 -p 4369:4369 -p 5369:5369 -p 6369:6369 \
>  -e EMQX_NODE__COOKIE=somepw  \
>  -e EMQX_RETAINER__EXPIRY_INTERVAL=7s \
>  -e EMQX_OS_MON__CPU_HIGH_WATERMARK=100% \
>  -e EMQX_LOG__TO=console \
>  -e EMQX_LISTENER__TCP__INTERNAL=127.0.0.1:11883 \
>  emqx/emqx:latest
```
Emqx just starts fine with the following output: 

![image](https://user-images.githubusercontent.com/47358065/74157986-91aaba80-4c19-11ea-82b6-ee697e1260ee.png)

**Comment by kilianbr** [comment]
Ok I found out that the assigment of the hostname doesnt seem to work. 
![image](https://user-images.githubusercontent.com/47358065/74162555-41375b00-4c21-11ea-90ba-da4f019673fa.png)

Can anybody tell me if theres a general malfunction about that, or is my assigned hostname 4pi2 just too short?

**Comment by kilianbr** [comment]
Last edit: Turns out emqx assigns the ContainerID instead of the Container-Name, like described in the docs:
![grafik](https://user-images.githubusercontent.com/47358065/74220532-28c25180-4cb0-11ea-9e86-1b25bdbf56eb.png)

**Comment by zhanghongtong** [comment]
Hi, @kilianbr 
The name of Nodename is "name@network address", so you need to make sure that the part after the "@" symbol is the address of the container. "1.0.0.42" does not look like the container's IP, so the ping failed

**Comment by kilianbr** [comment]
Hi @zhanghongtong, thanks for your response. Ok I understand, can you tell me if there where any changes from emqx 3.2.2 to emqx 4.0.2 which affected that behaviour? If I use EMQX 3.2.2 I am able to name my node and host like that and everything just works fin. 

![grafik](https://user-images.githubusercontent.com/47358065/74309835-00982880-4d6c-11ea-9ebf-c8b5251ddd2c.png)

**Comment by zhanghongtong** [comment]
Hi, @kilianbr 
No matter which version, the "@" symbol in nodename should be followed by the network address of the container. I'm not sure how you created it in 3.2.2.

**Comment by kilianbr** [comment]
Ok thanks @zhanghongtong . If I run 

`docker run -d --name emqx -p 1883:1883 -p 18083:18083 -p 8083:8083 -p 4369:4369 -p 5369:5369 -p 6369:6369 \
 -e EMQX_NODE__COOKIE=somepw \
 -e EMQX_RETAINER__EXPIRY_INTERVAL=7s \
 -e EMQX_OS_MON__CPU_HIGH_WATERMARK=100% \
 -e EMQX_LOG__TO=console \
 -e EMQX_LISTENER__TCP__INTERNAL=127.0.0.1:11883 \
 -e EMQX_LISTENER__TCP__INTERNAL=127.0.0.1:11883 \
 emqx/emqx:latest`

EMQX  name@network address should take the name of the container **emqx**:  
![image](https://user-images.githubusercontent.com/47358065/74311919-d5fc9e80-4d70-11ea-87db-760d1e635d63.png)

but takes the container ID instead: 
![image](https://user-images.githubusercontent.com/47358065/74312076-368bdb80-4d71-11ea-8eb2-6d801f2e23de.png)

Am I missing something or isn't that the intended behaviour when created without name and host specification?

**Comment by zhanghongtong** [comment]
If the environment variable "EMQX_NAME" is not configured when creating the container, the default value of "EMQX_NAME" is obtained by `hostname` command, you can check out our [docker-entrypoint.sh](https://github.com/emqx/emqx-rel/blob/fab4d6b764462164283f6b54d6c39d8c4a522c0a/deploy/docker/docker-entrypoint.sh#L32)
