### ISSUE TITLE
Windows installer url not available for EMQ X 4.0.2 version

### ISSUE THREAD

**Issue by kedar-hatkar** [emqx/emqx#3245]
#### Environment

- OS: Windows 10
- Erlang/OTP: 
- EMQ X: 4.0.2

#### Description

I am unable to locate windows installer setup file on EMQ website as well as Github release.

**Comment by HJianBo** [comment]
Hi, @kedar-hatkar The Windows release package is going to have to wait a while, and we're working on it

**Comment by HJianBo** [comment]
Hi, @kedar-hatkar We have uploaded windows packages

Thanks for your attention
