### ISSUE TITLE
TLS connection problem

### ISSUE THREAD

**Issue by DeadL1ne** [emqx/emqx#3247]
#### Environment

- OS: Ubuntu 18.04.2 LTS
- Erlang/OTP: 
- EMQ: 4.0.1

#### Description
I want to enable One-way authentication over MQTT SSL and my configuration looks like this:

    listener.ssl.external.keyfile = /etc/letsencrypt/live/abc.xyz.com/privkey.pem
    listener.ssl.external.certfile = /etc/letsencrypt/live/abc.xyz.com/fullchain.pem
    ##listener.ssl.external.cacertfile = /etc/emqx/certs/MyRootCA.pem

where privkey and fullchain were got from Let's Encrypt

I'm using library Paho and write client on Java. When I try to connect from my own outside client I getting error: causejavax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target. I think it's related with this issue(https://github.com/emqx/emqx/issues/2397). But I've already had commented listener.ssl.external.cacertfile property. My client code looks like this:

            String  broker = "ssl://abc.xyz.com:8883";
            MqttClient sampleClient = new MqttClient(broker, clientId, persistence);
            MqttConnectOptions connOpts = new MqttConnectOptions();
            connOpts.setCleanSession(true);
            connOpts.setUserName("1");
            SSLContext sslContext = SSLContext.getInstance("TLSv1.2");
            sslContext.init(null, null, null);
            connOpts.setSocketFactory(sslContext.getSocketFactory());
            System.out.println("Connecting to broker:" + broker);
            sampleClient.connect(connOpts);
            System.out.println("Connected");
            String topic = "topic";
            System.out.println("Subscribe to topic:" + topic);
            sampleClient.subscribe(topic);

**Comment by tigercl** [comment]
@DeadL1ne Sorry for late reply, I hope this document about ssl can help you:
https://www.emqx.io/blog/emqx-server-ssl-tls-secure-connection-configuration-guide

**Comment by DeadL1ne** [comment]
@tigercl, I've already read this document and also read article from https://medium.com/@emqtt/using-lets-encrypt-certificates-in-emq-b11e0e57efa6. When I set cacert when initialize SSLContext it works fine. Should I always send this certificate to all clients which want to establish SSL connection? I think do it manually is't the best pracrice. Maybe you could tell me how to do it in right way? When I don't send certificate I get this error in emqx logs:

    [error]     supervisor: 'esockd_connection_sup - <0.1584.0>'
        errorContext: connection_shutdown
        reason: {ssl_error,
                {tls_alert,
                    {certificate_unknown,
                        "TLS server: In state certify received CLIENT ALERT: Fatal - Certificate Unknown\n"}}}
        offender: [{pid,<0.1697.0>},
               {name,connection},
               {mfargs,
                   {emqx_connection,start_link,
                       [[{deflate_options,[]},
                         {max_conn_rate,500},
                         {active_n,100},
                         {zone,external}]]}}]

**Comment by tigercl** [comment]
@DeadL1ne  When you use a self-signed CA certificate, you need to specify the CA certificate for each client.

**Comment by DeadL1ne** [comment]
@tigercl Yes I understood it, but I use Let's Encrypt certificate and my broker's settings that are shown in the 1st post(https://github.com/emqx/emqx/issues/3247#issue-563938406) and if I don't attach certificate from client side, I'm getting SSL error(https://github.com/emqx/emqx/issues/3247#issuecomment-585696140)

**Comment by tigercl** [comment]
@DeadL1ne Sorry for late reply. I don’t know much about Let's Encrypt, but if you must specify a CA certificate for the client to use normally, it means that it's a self-signed CA certificate. You can verify it with `openssl s_server` and `openssl s_client`.

**Comment by hnuzhoulin** [comment]
I'm currently using EMQX 4.2.6 and encountered the same issue. A big thank you to the previous Medium article shared; it helped me resolve the problem. The key point is to merge the CA certificate from the certificate authority into the chain.pem file, which is then used as the cacertfile configuration for EMQX. The command I used is:

`cat /etc/ssl/certs/DST_Root_CA_X3.pem /etc/letsencrypt/live/$domain/chain.pem > ca.pem`
