### ISSUE TITLE
The issue about EMQ X cluster running in K8S Deployment

### ISSUE THREAD

**Issue by wenzhenxi** [emqx/emqx#3252]
使用K8S Deployment 运行EMQX 使用官网K8S配置方式

但是一旦增加了配置项文件就不行了：
cluster.k8s.address_type = hostname  

但是通过helm是可以的，这个配置项是通过helm的配置找到

最终发现原因是 /usr/bin/docker-entrypoint.sh 中的这段代码

 (sed -n "/^${LOCAL_IP}/"p /etc/hosts | grep -e "$(hostname).*.${EMQX_CLUSTER__K8S__NAMESPACE}.${EMQX_CLUSTER__K8S__SUFFIX}" -o)

通过helm运行的容器中 /etc/hosts 会比一般的多一个hostname?

为什么这样设计，使用Deployment要怎么运行集群呢？

**Comment by wenzhenxi** [comment]
如果换成 ip 会出现 2020-02-17 11:20:46.826 [error]
** Cannot get connection id for node 'emqx-broker-dev-7f46d4b7d5-zpwkf@172.25.3.222'

**Comment by wenzhenxi** [comment]
用 dns 也会疯狂重启

**Comment by tigercl** [comment]
Use K8S Deployment to run EMQX with configuration method from EMQ X official website.

But once I add the configuration item:
cluster.k8s.address_type = hostname

But it is possible through helm, this configuration item is found through the configuration of helm.

It turned out that the reason was this piece of code in `/usr/bin/docker-entrypoint.sh`:

```
(sed -n "/ ^ $ {LOCAL_IP} /" p / etc / hosts | grep -e "$ (hostname). *. $ {EMQX_CLUSTER__K8S__NAMESPACE}. $ {EMQX_CLUSTER__K8S__SUFFIX}" -o)
```

Why `/etc/ hosts` in a container running through helm will have one more hostname than usual?

Why is it designed this way, how to run a cluster with Deployment?

**Comment by zhanghongtong** [comment]
Hi @wenzhenxi 
EMQ X helm package uses `StatefulSet` to deploy pods, and each Pod in StatefulSet has a fixed DNS format, `cluster.k8s.address_type = hostname` is to read the DNS in the Pod of StatefulSet, so `Deployment` cannot be used, we recommend you to use EMQ X helm package directly for Deployment

**Comment by wenzhenxi** [comment]
Yes, I See The Helm Config using StatefulSet, But not support Deployment such type ？

**Comment by zhanghongtong** [comment]
@wenzhenxi You can set `cluster.k8s.address_type=ip` and use `Deployment` to deploy the cluster

**Comment by zhanghongtong** [comment]
This issue has not been updated in a long time, I will close it, if you have any questions, please feel free to open it

**Comment by spokc** [comment]
Hi, we're using k8s `Deployment` with `cluster.k8s.address_type=ip`. But we're getting this error while auto clustering using k8s
```
Cannot get connection id for node :"emq-d6877b46c-fdhzp@XX.XX.X.XXX
```

**Comment by Rory-Z** [comment]
Hi, @spokc 
Please make sure that all of emqx's `node.name` the string before the "@" is consistent, and set it to the value of `cluster.k8s.app_name`

**Comment by ciprian90** [comment]
Hi,
@Rory-Z 
Doesn't that refer to the pod name? I have the same problem (just as @spokc ). The Pod names are auto-generated by ReplicaSet.
