### ISSUE TITLE
The sum of received and sent messages is not equal in EMQ server cluster 

### ISSUE THREAD

**Issue by woheme** [emqx/emqx#3254]
#### Environment

- OS: Ubuntu 16.04
- Erlang/OTP: 
- EMQ: v3.2.3

#### Description

*A description of the issue*
The sum of received and sent messages is not equal in EMQ server cluster ,
there have 2 EMQ sever cluster with ETCD,publisher is 2000 tboxs,receiver is 3 Business platform gateway。2000 boxes send messages every second。

A EMQ dashboard info:
qos2.received 400400
qos2.sent 267148

A EMQ dashboard info:
qos2.received 399600
qos2.sent 133682

400400+399600 not equeal 267148+133682

**Comment by woheme** [comment]
anyone can solve the problem?

**Comment by HJianBo** [comment]
Hi @woheme  The `qos2.received` is not necessarily equal to `qos2.sent`, E.g:

1. One Qos2 message will be forward to two or more clients.
2. The QoS level for downlink message may be Qos0 or Qos1. It does not completely equal to the PUBLISH QoS level. see:  [MQTT 3.8.4-6](http://docs.oasis-open.org/mqtt/mqtt/v3.1.1/os/mqtt-v3.1.1-os.html#_Toc398718067)
