### ISSUE TITLE
Create Cluster between Raspberry Pi's as nodes.  

### ISSUE THREAD

**Issue by kilianbr** [emqx/emqx#3255]
#### Environment

- OS: Linux Buster
- Erlang/OTP: default
- EMQ: 4.0.2 

#### Description
My issue is related to [/issues/3244]. 
I'm running EMQX on two different Raspberry Pi's 4. 
I created the EMQX container using the following command: 

> `docker run -d --name emqx -p 1883:1883 -p 18083:18083 -p 8083:8083 -p 4369:4369 -p 5369:5369 -p 6369:6369  
>    -e EMQX_NODE__COOKIE=somepw
>    -e EMQX_RETAINER__EXPIRY_INTERVAL=7s
>    -e EMQX_OS_MON__CPU_HIGH_WATERMARK=100% 
>    -e EMQX_LOG__TO=console 
>    -e EMQX_LISTENER__TCP__INTERNAL=127.0.0.1:11883
>     emqx/emqx:v4.0.2`

Config RPI4_2: 
![grafik](https://user-images.githubusercontent.com/47358065/74725972-f8922a00-523e-11ea-82a7-a579fe29881d.png)

RPI4_3: 
![grafik](https://user-images.githubusercontent.com/47358065/74725942-ec0dd180-523e-11ea-95d1-03fa77415a31.png)

If I exec into the EMQX Container I'm able to ping the raspberry pi's from the other one like this: 
![grafik](https://user-images.githubusercontent.com/47358065/74726120-368f4e00-523f-11ea-951e-450c40592d87.png) 
and the other way around.

Now I tried to create a cluster following this tutorial: https://docs.emqx.io/tutorial/v3/en/cluster/setup_start.html , which doesn't work. 
I'm not sure if i've got a problem because they both have the same container IP assigned which looks like the following: 
![grafik](https://user-images.githubusercontent.com/47358065/74726326-8c63f600-523f-11ea-82e7-b6cc1c7793cd.png)
and on the other one: 
![grafik](https://user-images.githubusercontent.com/47358065/74731724-e4ebc100-5248-11ea-9e90-0b05ff36a7a0.png)

Output trying to build the cluster: 
![grafik](https://user-images.githubusercontent.com/47358065/74730989-73f7d980-5247-11ea-8ce2-23f8a93f3915.png)

One appraoch we thought about to create the cluster was to change the containers subnet to 1.0.0.x and then assigning static ip's for the containers following this tutorial: https://blog.alejandrocelaya.com/2017/04/21/set-specific-ip-addresses-to-docker-containers-created-with-docker-compose/ .
But that looks a bit laborious. Can you think of an easier way to cluster two Raspberry Pi's which are connected over an wifi network? Are we missing something?  

Edit: In the described related issue we used Version EMQX 3.0.2 and we were able to create the cluster as described.

**Comment by HJianBo** [comment]
Hi, @kilianbr Sorry for the late reply.

The `Ignore.` result message is meaning that the Node joins itself.

The node `284...@172.17.0.2` should join to `15c...@172.17.0.3` instead of itself.

( BTW,  the IP of 2nd node is duplicated 1st node

**Comment by HJianBo** [comment]
Hi, @kilianbr Do you have resolved it?

**Comment by kilianbr** [comment]
Hi, @HJianBo- thanks for your reply. I have to admit that my work packets have slightly changed in the meantime and I can't try the solution at the moment. I will come back at it later and report back. Since I'm running EMQX in the inside of an docker container, I'm a bit uncertain in my case of the IP matter. They are assigned automatically, if I set them to static I may provoke sideeffects to my network, but I guess I will find out! 
Thanks again for your help.

**Comment by HJianBo** [comment]
Yes. The fixed static IP Address is not a good plan for creating a cluster between docker containers.

The best practice is dependent on a third-party service to get this dynamic IP Address. e.g: `etcd`, `k8s`, etc.

**Comment by HJianBo** [comment]
Close it first.

Please let me know if you have any questions :)
