### ISSUE TITLE
emqttd custom plugin with emqx

### ISSUE THREAD

**Issue by yuvarajan1989k** [emqx/emqx#3256]
Hi,

we are migrating from emqttd to emqx. there is a custom plugin (developed using this http://emqtt.io/docs/v2/plugins.html#plugin-development-guide). i want to use the same plugin in emqx ?  whats the recommended approach to use this with emqx

**Comment by tigercl** [comment]
@yuvarajan1989k There is currently no good upgrade plan for custom plugins. You may need to spend some effort to complete the adaptation of the plugin, please refer to https://docs.emqx.io/broker/latest/cn/plugins.html#emq-x.
