### ISSUE TITLE
EMQ X is wrong after upgrade to 4.0.2

### ISSUE THREAD

**Issue by datafeng** [emqx/emqx#3257]
#### Environment

- OS: ubuntu 18.04
- Erlang/OTP: emqx/emqx:latest
- EMQ: 4.02

#### Description
1.Dashboard打不开了，18083端口这个管理系统打不开了。。
2.重启命令的时候也发现异常。。
Node 'emqx@127.0.0.1' not responding to pings.
![image](https://user-images.githubusercontent.com/6417549/74798365-94d43380-5308-11ea-85c9-d0856d370061.png)

*A description of the issue*

**Comment by tigercl** [comment]
1.Dashboard listening on 18083 cannot be opened.
2.An exception was also found when restarting the command:
`Node 'emqx@127.0.0.1' not responding to pings.`

**Comment by tigercl** [comment]
It seems that EMQ X is not start yet.

**Comment by datafeng** [comment]
> It seems that EMQ X is not start yet.

I am sure it's running and mqtt service is normal.

**Comment by kapoorsarthak** [comment]
i am having the same issue. When i change the node.name in /etc/emqx.conf and after that try to do emqx_ctl it gives me an error. **Node 'emqx@52.66.135.195' not responding to pings.**

**Comment by HJianBo** [comment]
Hi, @kapoorsarthak After changing the `name.node` You should restart emqx first for using `emqx_ctl` commands

**Comment by kapoorsarthak** [comment]
Yes i have even tried doing that. PFB the steps i followed and still got the error.

1. Installed fresh EMQX.

**Comment by kapoorsarthak** [comment]
@HJianBo i have made 2 folders on my machine and started 1st node with the node.name **emqx1@127.0.0.1**  the result is the the emqx starts , but parallel when i try to start the 2nd emqx node with the node.name **emqx2@127.0.0.2** it gives me an error that **Node 'emqx2@127.0.0.2' not responding to pings.** even after restarting the emqx. The reason i am doing this is to achieve clustering on the same machine.

**Comment by HJianBo** [comment]
Yes, It is possible on the same machine. But you should ensure that the listeners' ADDRESS and PORT of emqx.conf is no conflict.

For example:
```
listener.tcp.external = 0.0.0.0:1883
```

Sets a different `node.name` is not enough. Maybe you can try [one_more_emqx.sh](https://github.com/terry-xiaoyu/one_more_emqx)

**Comment by HJianBo** [comment]
Hi, @datafeng Is your problem has solved? Or Add my WeChat to help us to figure out that :) 

**WeChat ID**：Lo_Alone

**Comment by kapoorsarthak** [comment]
@HJianBo what is the script `one_more_emqx.sh` for. Can you guide me how do clustering on a single machine, With all the steps involved. I wanted to know how many changes will i have to make! Or only the changes you have told me so far will work?
