### ISSUE TITLE
Why is the configuration information in the MySQL plug-in on the control panel missing after restarting the service？

### ISSUE THREAD

**Issue by Chenfengf** [emqx/emqx#3258]
#### Environment

- OS: 
- Erlang/OTP: 
- EMQ: 

#### Description

*A description of the issue*
Why is there no configuration information in MySQL plug-in on the control panel after restarting the service? Every time I restart the service, I need to add the MySQL plug-in configuration information again

**Comment by tigercl** [comment]
@Chenfengf Configurations modified through the dashboard are only valid during this running. If you want the configuration to take effect permanently, you need to modify the configuration file.
