### ISSUE TITLE
Some problems of ACL rule

### ISSUE THREAD

**Issue by Chenfengf** [emqx/emqx#3259]
#### Environment

- OS: 
- Erlang/OTP: 
- EMQ: 

#### Description

*A description of the issue*

现在subscribe是1 public 是2 subpub是3，为什么从0开始定义呢
Now the subscribe is 1 public is 2 and the subscribe is 3. Why is it defined from 0

**Comment by HJianBo** [comment]
There is no extra reason. We just follow the naming convention in Erlang
