### ISSUE TITLE
Sending null instead of undefind for `emqx-auth-http`

### ISSUE THREAD

**Issue by GopherJ** [emqx/emqx#3262]
#### Environment

- OS: Deepin@15.5
- Erlang/OTP: 
- EMQ: 4.0

#### Description

*A description of the issue*
see https://github.com/emqx/emqx-auth-http/issues/179

Sorry I'm not sure where to put this issue, at the beginning I think it should be issue of `emqx-auth-http` but maybe it should be here ?

**Comment by HJianBo** [comment]
Yeh, you are right. It is a bad return value, we plan to improve it at v4.1.0.

Thanks for your feedback

**Comment by HJianBo** [comment]
The 4.1-alpha.2 has tagged, Plz try it later
