### ISSUE TITLE
Whether the action of the rule engine can use wildcards

### ISSUE THREAD

**Issue by gongroc** [emqx/emqx#3264]
我想实现用规则引擎监听到某一个topic之后，将该条信息转发到其他多个主题，转发的目标主题是动态的。
比如：
监听到 /a/# 的topic内容，转发到 /a/xxx/c 或者  /a/xxx/d 
设置了转向主题为 /a/+/+ 报错
这种方式好像不允许

有什么办法可以实现么？

**Comment by gongroc** [comment]
设置重定向主题时指定具体主题报错如下：

Bad Arguments: {invalid_ejson,{<<"name">>,<<"republish">>}}

**Comment by HJianBo** [comment]
@gongroc Can you share your rule details to help me reproduce it. Thanks

**Comment by HJianBo** [comment]
Hi, @gongroc Any update there?

**Comment by HJianBo** [comment]
In the MQTT protocol spec, the PUBLISH operation is not allowed to a `Wildcard Topic`. So this not is a way to implement your requirements.

According to your description, the subscriber just should subscribe to the `a/+/+` topic. The Rule-Engine should republish these messages to a specific topic, e.g: `a/x/y`.

Maybe you should think more about this type of Topic design. It should be working and enough. 

I'll first it first. Plz let me known if you have any questions. Thanks @gongroc
