### ISSUE TITLE
emqx配置集群后，使用阿里云负载均衡访问，多个设备连接时会出现有的设备无法订阅消息的问题？

### ISSUE THREAD

**Issue by lihongwen1** [emqx/emqx#3265]
使用阿里云配置负载均衡，配置emqx1和emqx2为集群，设备A发布的消息，如何保证其他设备都能收到该消息？现在的问题是设备A经过负载均衡连接的emqx1，设备B可能连接的是emqx2，这样设备B就无法订阅接收到设备A发布的消息。怎么配置才能使设备B无论何时连接都能接收到设备B发布的消息？

**Comment by HJianBo** [comment]
> 现在的问题是设备A经过负载均衡连接的emqx1，设备B可能连接的是emqx2，这样设备B就无法订阅接收到设备A发布的消息。

Device B must be able to receive messages from A, If the emqx cluster status is right.

Please see: https://docs.emqx.io/broker/latest/cn/cluster.html

**Comment by lihongwen1** [comment]
> > 现在的问题是设备A经过负载均衡连接的emqx1，设备B可能连接的是emqx2，这样设备B就无法订阅接收到设备A发布的消息。
> 
> Device B must be able to receive messages from A, If the emqx cluster status is right.
> 
> Please see: https://docs.emqx.io/broker/latest/cn/cluster.html

找到原因了，是因为两台阿里云服务器之间5369端口没开通

**Comment by datafeng** [comment]
> > > 现在的问题是设备A经过负载均衡连接的emqx1，设备B可能连接的是emqx2，这样设备B就无法订阅接收到设备A发布的消息。
> > 
> > 
> > Device B must be able to receive messages from A, If the emqx cluster status is right.
> > Please see: https://docs.emqx.io/broker/latest/cn/cluster.html
> 
> 找到原因了，是因为两台阿里云服务器之间5369端口没开通

想问下，这两个服务器是在两个账号，内网不互通的吗？
不知道如果两个节点不在一个局域网是否会正常。

**Comment by HJianBo** [comment]
DO NOT try to create an EMQ X cluster over an external network, which introduces a number of stability issues.
