### ISSUE TITLE
Client will lost connection after apply a acl rules

### ISSUE THREAD

**Issue by weiguang-fan** [emqx/emqx#3266]
#### Environment

- OS: centos 7.5
- Erlang/OTP: 
- EMQ: 4.0.2

#### Description
Client will lost connection with broker and pop out message "Broker connection lost: Resetting client" when client try publish any topic message.

EMQX configuration:
#####emqx.conf 
acl_nomatch = deny

acl_deny_action = ignore

#####acl.conf
{allow, {user, "dashboard"}, subscribe, ["$SYS/#"]}.

{allow, all, publish, ["/+/%c/#"]}

{deny, all, subscribe, ["$SYS/#", {eq, "#"}]}.

{deny, all}

**Comment by HJianBo** [comment]
It is indeed a BUG and we plan to fix it in 4.0.4.

Thanks for your feedback

**Comment by HJianBo** [comment]
See: https://github.com/emqx/emqx/pull/3286

**Comment by HJianBo** [comment]
Hi @weiguang-fan 4.0.4 has released in the last week. Plz try it later

**Comment by zsafder** [comment]
it still not working for me in 4.0.6
