### ISSUE TITLE
ubuntu apt upgrade 4.0.2 to 4.0.3 the emqx restart order is not take effect

### ISSUE THREAD

**Issue by datafeng** [emqx/emqx#3267]
#### Environment

- OS: ubuntu 18.04
- Erlang/OTP: 
- EMQ: 4.0.2 to 4.0.3

#### Description

*A description of the issue*
I make apt upgrade 4.0.2 to 4.0.3, then run emqx restart is not take effect..
it must run emqx stop first, and run emqx start...

![image](https://user-images.githubusercontent.com/6417549/75088893-15579600-558e-11ea-85b6-48b37679bdfe.png)

**Comment by tigercl** [comment]
@datafeng Sorry for late reply. We don't support cross-version restart yet.
