### ISSUE TITLE
Rule Engines NOT support ${x} as table name when save data_to_mysql  

### ISSUE THREAD

**Issue by weiguang-fan** [emqx/emqx#3269]
#### Environment

- OS:  Centos 7.5
- Erlang/OTP: 
- EMQ:  EMQX EE 3.4.5

#### Description
From application requirements, we need to create a dedicate table for each device,  and use "client id" as table name. When we create a rule like this, EMQX popout error like this:"_Bad Arguments: {init_action_failure,[{{init_action_failure,'emqx@127.0.0.1'},{{emqx_backend_mysql_actions,on_action_create_data_to_mysql},prepare_sql_failed}}]}_"

**error log:**
2020-02-24 09:56:08.822 [error] [RuleEngine MySql] Prepare Statement: <<"INSERT INTO ? (`msg`)  VALUES (?);\n">>, {1064,<<"42000">>,<<"You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '? (`msg` at line 1">>}^M
2020-02-24 09:56:08.822 [error] cluster_call error found, ResL: [{{init_action_failure,'emqx@127.0.0.1'},^M
                                  {{emqx_backend_mysql_actions,^M
                                       on_action_create_data_to_mysql},^M
                                   prepare_sql_failed}}]^M

// **test condition**
*A description of the issue*
{   // rule
        SELECT
            payload.msg AS msg,
            client_id AS device_id         
        FROM
          "message.publish"
        WHERE
          topic =~ '/dev_type/+/msg' 
 }

Action:
{
INSERT INTO ${device_id} (`msg`)   
VALUES(${msg});
}

**Comment by terry-xiaoyu** [comment]
The error msg `"You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '? (msg at line 1"` indicates the problem.

`INSERT INTO ${device_id} (msg) VALUES(${msg});` has syntax errors so it is not acceptable by MySQL.

**Comment by weiguang-fan** [comment]
**"You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '? (msg at line 1" **  the ?  wil  be replaced by ${device_id} as table name, in database this table is exist and accessable.  This error is caused by the table name is dynamic changable when execute SQL.
