### ISSUE TITLE
Report an error during compilation and check the source code to find that the library file is missing

### ISSUE THREAD

**Issue by gdhua** [emqx/emqx#3270]
/src/emqx_router.erl 编译时文件报错,提示少了文件,
位置在第24行代码:-include_lib("ekka/include/ekka.hrl").  仓库不存在ekka/include/ekka.hrl文件

**Comment by HJianBo** [comment]
Hi, @gdhua What's the repository and version used? And could you paste your compile command there?

**Comment by HJianBo** [comment]
Close it first. Plz reopen it If you remaining any questions :)
