### ISSUE TITLE
Can't create resources via Dashboard when deploy using docker cause host is service name, not IP

### ISSUE THREAD

**Issue by 04116** [emqx/emqx#3273]
#### Environment

- OS: Docker
- Erlang/OTP: 
- EMQ: 3.2.6

#### Description

*A description of the issue*
Dear emqx team,
At the dashboard, when providing the service name of docker, its failure to verify.
I can still create a resource by emqx_ctl. But what is the right way?
Thank so much,

**Comment by HJianBo** [comment]
@04116 I can't figure out it. Could you provide more details description of it? It may help us to reproduce it.

Thanks!

**Comment by 04116** [comment]
![Screenshot from 2020-02-29 08-49-49](https://user-images.githubusercontent.com/36094827/75598770-ec288f80-5ad0-11ea-95ff-24a620c2b9e5.png)
![Screenshot from 2020-02-29 08-45-49](https://user-images.githubusercontent.com/36094827/75598685-42490300-5ad0-11ea-9146-479664d1d37f.png)
![Screenshot from 2020-02-29  @08-52-59](https://user-images.githubusercontent.com/36094827/75598767-e8950880-5ad0-11ea-8fea-d7d17aa85515.png)

@HJianBo let's see. I use docker-compose to create emqx container

**Comment by ysfscream** [comment]
@04116 Hi, I think it should be a problem with the form validation, because it's not a normal URL format. We will fix it at v4.0.4. Thanks for your report!

**Comment by 04116** [comment]
@ysfscream yes, it is.
