### ISSUE TITLE
Using docker to run emqx, cpu will have high occupancy every 15 seconds

### ISSUE THREAD

**Issue by zcl7692387** [emqx/emqx#3274]
#### Environment

- OS: centos7.4 64 docker 19.03.6
- Erlang/OTP: 10.5.6
- EMQ: 4.0.3
docker运行命令:
docker run -d --name emqx31 -p 1883:1883 -p 8083:8083 -p 8883:8883 -p 8084:8084 -p 18083:18083 --restart=always  emqx/emqx

#### Description

*A description of the issue*

**Comment by zhanghongtong** [comment]
@zcl7692387 I can't figure out it. Could you provide more details description of it? It may help us to reproduce it.

Thanks!

**Comment by HJianBo** [comment]
Hi, guys :). It has fixed at v4.0.5
