### ISSUE TITLE
MQTT-SN subscriptions dropped out

### ISSUE THREAD

**Issue by martinezcp** [emqx/emqx#3275]
#### Environment

- OS: Raspbian 4.19.97
- Erlang/OTP: 22/10.6
- EMQ: 4.02

#### Description

I have some devices connected through MQTT-SN which require to keep the subscriptions after they are disconnected from the gateway. I am pretty sure I have something not configured but I cannot find it.

I am trying with command line clients in order to see if everything is working or not. It works fine with the MQTT but it is not with MQTT-SN.

This works and keep subsription after disconnecting the client (Client receives messages after reconnecting)
   
    mosquitto_sub -h 127.0.0.1 -p 11883 -q 1 -t "topic/test" -i "test_mqtt" -c

This works and client receives messages while it is connected but broker does not keep the subscription after disconnected. Neither it receives messages after reconnecting.

    ./mqtt-sn-sub -h 127.0.0.1 -p 5224 -q 1 -t "topic/test" -i "test_sn" -c

I think I need to update something in order to keep subscriptions for the SN part.

If I connect both clients, disconnect them and publish a message with:

    mosquitto_pub -h 127.0.0.1 -p 11883 -q 1 -t "topic/test" -m "hello"

After reconnecting both clients, the mqtt is the only one receiving the message.

Whenever I connect a SN client, the log shows the following:

    2020-02-28 09:59:51.492 [error] <<"test_sn">> MQTT-SN(127.0.0.1:35358): StateName: idle, Unexpected Event: {cast,
                                                              {event,
                                                               connected}}
    2020-02-28 09:59:51.499 [error] <<"test_sn">> MQTT-SN(127.0.0.1:35358): StateName: connected, Unexpected Event: {cast,
                                                                   {event,
                                                                    updated}}

**Comment by HJianBo** [comment]
Hi, @martinezcp It is a bug to handle the `Clean Session` mechanism.  We will sorry to bring trouble for you.

We plan to fix it at next next version (may 4.1.beta.1 or 4.0.5

Thanks for your report here :)

**Comment by HJianBo** [comment]
Hi, @martinezcp We have fixed it in v4.0.5
