### ISSUE TITLE
Server memory usage is high when using SSL connections

### ISSUE THREAD

**Issue by xianghao1986** [emqx/emqx#3277]
#### Environment

- OS: centos7.6
- Erlang/OTP: 
- EMQ: 4.0.3

#### Description

*A description of the issue*

测试SSL连接时，
专门针对EMQX/SSL连接做了压力测试，
EMQX服务器：8核CPU，32G内存。
SSL双向认证：
keepalive =300秒，20万连接时，CPU占用70%，内存占用31G，网络(in/out)占用（0.47M/0.5M）。
TCP协议：
keepalive =300秒，20万连接时，CPU占用10%，内存占用2G，网络(in/out)占用（0.14M/0.08M）。
官方文档说SSL只会增加CPU资源的占用，但从实际数据看，内存占用也增加了很多，这是为什么呢。

**Comment by HJianBo** [comment]
Hi, @xianghao1986 Thanks for your feedback there :)

**Comment by xianghao1986** [comment]
have you confirmed the problem？

**Comment by tigercl** [comment]
@xianghao1986 SSL connections will consume more CPU and memory than TCP connections. We usually recommend that you use the proxy to terminate the TSL connection.

**Comment by xianghao1986** [comment]
> @xianghao1986 SSL connections will consume more CPU and memory than TCP connections. We usually recommend that you use LB to terminate the TLS connection.

But, When we use the nginx to terminate the TLS connection, how to break through the single server port restrictions?

**Comment by HJianBo** [comment]
Maybe you should using  a number of Ethernet card as the Proxy Client to connect EMQ X Broker
