### ISSUE TITLE
Missing nodes in dashboard dropdown for V4.0.3

### ISSUE THREAD

**Issue by Oegma2** [emqx/emqx#3278]
#### Environment

- OS: Ubuntu 18.04
- Erlang/OTP: 22.2.7
- EMQ: 4.0.3

#### Description
When we set up a single or clustered version for EMQ V4.0.3, the drop-down on the top right is missing the nodes - showing blank/empty space - so we can't select a specific node as per the previous dashboards. In V4.0.2 and lower, the drop-down shows our nodes in the cluster and also provides an All Nodes option

Only in the latest V4.0.3 have we found this bug 

Tested in different browsers - same issue
Tested this with a single node - same issue
Tested this in 3 node cluster - same issue

![image](https://user-images.githubusercontent.com/6543872/75554668-79250780-5a43-11ea-9f40-6dfcc01f3d06.png)

**Comment by HJianBo** [comment]
Thanks @Oegma2 It is a bug actually. We will fix it at v4.0.4

I am very sorry for the trouble  :(

**Comment by Oegma2** [comment]
> Thanks @Oegma2 It is a bug actually. We will fix it at v4.0.4
> 
> I am very sorry for the trouble :(

Hi @HJianBo - Thanks for the quick reply. Glad I could help 

Do you have any **timeline** for when v4.0.4 will be released? 

Eager to upgrade our cluster from V3.0.1 to V4.0.3 - we had some issues with stale sessions using V3.0.1 if our client using cleansession=false and belief that been fix in V4.0.3

**Comment by HJianBo** [comment]
Yea maybe ends of this week.

We also hope that you can upgrade to 4.x, which is a great version and we have made many improvements to Session.

If you have any Suggestions or Question in this progress,  let us know please

**Comment by Oegma2** [comment]
> Yea maybe ends of this week.
> 
> We also hope that you can upgrade to 4.x, which is a great version and we have made many improvements to Session.
> 
> If you have any Suggestions or Question in this progress, let us know please

Thanks a lot, @HJianBo for the update - looking forward to upgrading to V4

**Comment by HJianBo** [comment]
Hi guys, This fix has released at 4.0.4!!

**Comment by Oegma2** [comment]
Hi @HJianBo 

Thanks for the quick release of V4.0.4 - I've tested the new version and the drop-down now shows the different nodes 

Still missing the option for **All Nodes** as in V3, but we can **definitely work** with V4.0.4

_Looking forward to testing this in QA, STAGING and moving into PROD with V4.0.4_

**Comment by HJianBo** [comment]
Congratulations! Welcome to submit an issue or PR If you have any question :)
