### ISSUE TITLE
Difference of zone.internal and zone.external

### ISSUE THREAD

**Issue by EthsonLiu** [emqx/emqx#3282]
I see the  `zone.internal` and `zone.external`, what's the difference of `internal`  and `external`?

**Comment by tigercl** [comment]
@EthsonLiu Hi, sorry for late reply. 

A Zone defines a set of configuration items (such as the maximum number of connections, etc.). The Listener can specify the use of a zone through the configuration item `listener.<Protocol>. <Listener Name>.zone` to use all the configurations under the zone. Multiple Listeners can share the same Zone. Zone naming rules are `zone.<Zone Name>.xxx`,` Zone Name` can be named at will, but it is also recommended to use all lowercase English words, `xxx` is a specific configuration item.

There are three available values for each of our configuration items, which are global values, the values set in the zone, and the default values. Their priority is: Zone > Global> Default.

**Comment by EthsonLiu** [comment]
我还是中文问吧。

配置文件里有很多值都是用 internal 和 external 修饰的，比如，

```
zone.external.enable_stats
zone.internal.enable_stats 

zone.internal.enable_acl
zone.external.enable_acl

...
```

除了 internal 和 external ，其它都是一样的。

所以我问的是  internal 和 external 作用域在哪里？

**Comment by tigercl** [comment]
@EthsonLiu zone is used to define a set of configurations, the listener uses `listener.<Protocol>. <Listener Name>.zone` to specify which set of configurations to use.

**Comment by EthsonLiu** [comment]
又重新看了下文档，好像有点懂了。
