### ISSUE TITLE
How to connect with Modbus device

### ISSUE THREAD

**Issue by mcoder2014** [emqx/emqx#3283]
#### Environment

- OS: Linux
- Erlang/OTP: Any 
- EMQ: broker 4.0.2

#### Description

How to connect the modbus device with the EMQ X broker?
I can't find relative documention about it.

**Comment by EthsonLiu** [comment]
modbus 怎么和 emq 扯到一起了。modbus 是通用的 plc 通讯协议，emq 则是走的 mqtt/websocket。

**Comment by mcoder2014** [comment]
或者 emq x Edge 平台，我觉得emq x broker 和 emq x edge 差不多，插件应该两个都可以支持，因为官方的介绍中说有对工业协议的支持，所以想要了解下是否如何建立 Modbus 连接。
> MQTT, CoAP, HTTP 以及 Modbus 各种工业协议支持 [link](https://www.emqx.io/cn/products/edge)

作为物联网网关来讲，支持的协议越多越好呀。

**Comment by EthsonLiu** [comment]
还真有。。。。是我以前看漏了。我看到的文档确实没看到有介绍 modbus 设备的。

**Comment by HJianBo** [comment]
Hello guys, thanks for your suggestion there :)

We plan to introduce the Modbus connector plugin in the v4.1.0 version. It may come next month.

**Comment by HJianBo** [comment]
Duplicated https://github.com/emqx/emqx/issues/3022
