### ISSUE TITLE
emqx out of memory when using SSL (>40GB RAM used)

### ISSUE THREAD

**Issue by joliver82** [emqx/emqx#3289]
#### Environment

- OS: Alpine 3.10.4
- Erlang/OTP: 
- EMQ: 4.0.3
(Docker emqx/emqx:v4.0.3)

#### Description

I'm trying to calculate the maximum number of concurrent connections possible to emqx. I reached ~700K without ssl running multiple emqtt_bench in different docker containers without much effort and I assume I could get even much more.

When trying to get the same numbers the memory usage of emqx server gets really high until the it gets killed because OOM.

By default ssl max connections is set to 102400 so I had to set the required docker environment vars and also I want to use client certificate auth so I changed it as follows:

        EMQX_LISTENER__SSL__EXTERNAL__ACCEPTORS: "128"
        EMQX_LISTENER__SSL__EXTERNAL__MAX_CONNECTIONS: "2048000"
        EMQX_LISTENER__SSL__EXTERNAL__MAX_CONN_RATE: "5000"
        EMQX_LISTENER__SSL__EXTERNAL__CACERTFILE: "etc/certs/cacert.pem"
        EMQX_LISTENER__SSL__EXTERNAL__DHFILE: "etc/certs/dh-params.pem"
        EMQX_LISTENER__SSL__EXTERNAL__VERIFY: "verify_peer"
        EMQX_LISTENER__SSL__EXTERNAL__FAIL_IF_NO_PEER_CERT: "true"

At some point, I cannot tell you how many connections are established then, the server gets killed.

In fact, I made some more tests with less connections and it's using much more memory if using ssl, ~700K concurrent connections use ~9GB ram while ~60K ssl connections use ~8GB

**Comment by tigercl** [comment]
@joliver82 SSL connections will consume more CPU and memory than TCP connections. We usually recommend that you use the proxy to terminate the TSL connection.

**Comment by joliver82** [comment]
Thanks for you comment @tigercl. I know encrypted connections use more resources but I don't think increasing memory usage by ~800% is reasonable, other software like webservers don't use that much for SSL connections instead ~150-200% as far as I've tested

**Comment by tigercl** [comment]
@joliver82 Sorry for the inconvenience caused to you, we have fixed this issue in [emqx v4.0.5](https://github.com/emqx/emqx/releases).

**Comment by joliver82** [comment]
Thanks @tigercl it's working better now, I've spent some time testing it again and reached ~350K concurrent connections before OOM in this server (32GB ram). Maybe there's still some issue here with memory management in ssl connections. If using haproxy + emqx I can reach ~550K using 16GB in total (8.5 for haproxy and 7.5 fo emqx).
