### ISSUE TITLE
EMQX $events fields

### ISSUE THREAD

**Issue by kozelok** [emqx/emqx#3296]
#### Environment

- OS: GCP Container OS
- Erlang/OTP:  Latest
- EMQ:  4.0.4

#### Description

Currently, the data presented via $events is not all the message data available. Is it possible to expose all available data in the events, specifically MQTTv5 CorrelationID.

I want to capture the correlationID in dropped and delivered events for traceability.

**Comment by HJianBo** [comment]
Hi @kozelok We have released that at v4.2-alpha.1. Thanks for your recommendation
