### ISSUE TITLE
Don't print large payloads!

### ISSUE THREAD

**Issue by ThomasArts** [emqx/emqx#3297]
In a fork of this project we ran into serious performance problems and memory spikes of 60GB. This could be traced down to logging large binaries. Even if log level not selected, a large string was computed and then discarded.

In your code:
https://github.com/emqx/emqx/blob/1276afe96a0b17aa2c7ddba746ee68eaca54cd51/src/emqx_packet.erl#L445

you could limit the size of the binary by using something like this:
io_lib:format("~s, Payload=~W", [format_variable(Variable), Payload, 256]).

where 256 is the size you see in the constructed string

**Comment by tigercl** [comment]
@ThomasArts In the latest version, we have added a configuration item that limits the log print length. You can find it in `emqx.conf`:
`# log.chars_limit = 8192`
This configuration item is commented by default, that is, it does not take effect.

**Comment by HJianBo** [comment]
Hi, @ThomasArts Has your problem been solved? Or have better advice here?

In my opinion, the global chars_limit for the log is very convenient. You don't need hardcode or setting options for any log lines.

**Comment by k32** [comment]
This issue has been fixed in the latest version.
