### ISSUE TITLE
Wrong javascript client documentation

### ISSUE THREAD

**Issue by housheng4** [emqx/emqx#3298]
#### Environment

- OS: 
- Erlang/OTP: 
- EMQ: 

#### Description

The official website's client programming Javascript unsubscribe function is missing one letter, it should be unsubscribe, and the unubscribe on the official website is printed as undefined

**Comment by HJianBo** [comment]
Hi, @housheng4 Thanks for your feedback :)

@wivwiv

> https://docs.emqx.io/tutorial/latest/cn/client_dev/javascript.html
> https://docs.emqx.io/tutorial/latest/en/client_dev/javascript.html

**Comment by wivwiv** [comment]
Updated and fixed
https://docs.emqx.io/tutorial/latest/cn/client_dev/javascript.html
https://docs.emqx.io/tutorial/latest/en/client_dev/javascript.html
