### ISSUE TITLE
JWT Plugin

### ISSUE THREAD

**Issue by kozelok** [emqx/emqx#3300]
#### Environment

- OS: Google COS
- Erlang/OTP: Latest
- EMQ: 4.0.4

#### Description

We are currently in process of migrating from Google IOT to EMQx. One roadblock we have ran into is using default acl.conf with JWT. Is it possible to set the clientid or username from a token claim? This would allow us to use the built in acl.conf to manage static topic permissions as before.

**Comment by HJianBo** [comment]
> Is it possible to set the clientid or username from a token claim? 

No, It not supported now. Does **Google IoT** will get username or clientid from JWT Claim?

**Comment by HJianBo** [comment]
Hi, @kozelok Do you have any progress now?
