### ISSUE TITLE
Login with username and password

### ISSUE THREAD

**Issue by fjbcken** [emqx/emqx#3301]
#### Environment

- OS: docker
- Erlang/OTP: 
- EMQ: 4.0.2

#### Description

*A description of the issue*

請問一下我用docker建置環境，現在想讓裝置進來要輸入帳號密碼，請問要到哪邊設定?
插件那邊我已經有打開

EMQ X Authentication with Username and Password 

我看文檔說要去修改etc/plugins/emqx_auth_username.conf ，但是我進容器後找不到這個檔案
請問是免費版的不能用嗎?

**Comment by turtleDeng** [comment]
https://www.emqx.io/cn/blog/emqx-auth-username-user-guide.

**Comment by HJianBo** [comment]
Hi, @fjbcken The emqx_auth_username is completely supported in the open-source edition.

The conf file is located at `/opt/emqx/etc/emqx_auth_username.conf` :)

**Comment by fjbcken** [comment]
多謝!
想在請教一下現在我有設一組帳號了，也可以登入
但是我試了一下 不用打帳密一樣可以登入 這是哪邊還要設定嗎?

mqtt.allow_anonymous = true 這個我已經改成true了

**Comment by HJianBo** [comment]
Close it first. 

If you have any problems. let me known or open a new issue
