### ISSUE TITLE
function parse_cidr/3 undefined

### ISSUE THREAD

**Issue by yiwuwang** [emqx/emqx#3303]
#### Environment

- OS: centos7.3
- Erlang/OTP: Erlang (SMP,ASYNC_THREADS,HIPE) (BEAM) emulator version 5.10.4
- EMQ: v2.3.3

#### Description

When I compile the source, I get an error: function parse_cidr / 3 undefined
So what caused it?

details：src/esockd_cidr.erl:61: syntax error before: rc/esockd_cidr.erl:65: syntax error before: rc/esockd_cidr.erl:56: function parse_addr/1 undefined
src/esockd_cidr.erl:57: function parse_cidr/3 undefined
src/esockd_cidr.erl:130: Warning: function start_mask/2 is unused
src/esockd_cidr.erl:138: Warning: function end_mask/2 is unused
src/esockd_cidr.erl:160: Warning: function bmask/2 is unused
src/esockd_cidr.erl:165: Warning: function calc_end_address/2 is unused
src/esockd_cidr.erl:168: Warning: function bor_with_mask/2 is unused
src/esockd_cidr.erl:173: Warning: function band_with_mask/2 is unused
src/esockd_cidr.erl:178: Warning: function bit_count/1 is unused
make[2]: *** [ebin/esockd.app] Error 1
make[1]: *** [app] Error 2

**Comment by HJianBo** [comment]
Hi, @yiwuwang  You compile emqx v2.x by Erlang/OTP 19+ instead of Erlang/OTP R16 (erts5.10.4)

**Comment by yiwuwang** [comment]
@HJianBo There was a problem with installing erlang during the replacement process, which is a big project for me, so I gave up and used the emqx compiled by the official website. Thank you anyway
