### ISSUE TITLE
Consumer gets the ClientID of the producer sent by the message

### ISSUE THREAD

**Issue by ye32007** [emqx/emqx#3306]
#### Environment

- OS: centos7.2
- Erlang/OTP: R21/10.3
- EMQ: 3.2.7

#### Description

*A description of the issue*
多个producer使用不同的cleintId进行鉴权并保持连接，发送消息到emqx。这个是时候我使用一个consumer去消费这些消息，这个时候consumer如何知道这个消息是哪个producer产生的呢?消息里面是否有cleintId？

**Comment by tigercl** [comment]
@ye32007 In your case we usually recommend using the topic rewrite feature. Example:
Producer `myclient` publish to `a/b` -> EMQ X rewrite `a/myclient/b` -> Consumer subscribe `a/+/b`.

**Comment by HJianBo** [comment]
Afraid can't. On the consumer side, the PUBLISH message of  the MQTT protocol does not contain any information with the publisher. 

And the **Topic Rewrite** will cause extra performance costs.

In my opinion, a workaround is putting the Client Id to the message's topic when you produce any messages.

i.e:  `/some-prefix/<client-id>/send`

Then the consumer should subscribe to the `/some-prefix/+/send` topic for receiving all messages and parse the topic to get the producer's ID.

**Comment by saeidakbari** [comment]
@tigercl @HJianBo Vernemq also have the same feature called topic modifier that can be used to modify the topics with patterns but the difference between that and emqx topic rewrite is that vernemq allow users to have access to parameters called clientid or username but emqx is just a simple regex
