### ISSUE TITLE
Better way to handle messages?

### ISSUE THREAD

**Issue by ashishtaldeokar** [emqx/emqx#3308]
#### Environment

- OS: Ubuntu 18.04
- Erlang/OTP: 
- EMQ: 3.2

#### Description

*What would be a better way to handle more messages?*

I am using emqx webhook callbacks extensively
so all my sensors publish data to the broker, and I use webhooks to post data to a cluster of NodeJs apps which further pushes data to a message queue (RabbitMQ / Kafka) for processing by multiple workers and so on. (Shown in the diagram as approach 1)

The reason I'm doing this is my workload is huge (~400 messages/sec), and I don't want one process (Shown in the diagram as approach 2) that would subscribe to /# topics and cause a bottleneck.

**I am not facing any issues as of now** but since I will be scaling out further I need to know if I am doing it correctly.

![Blank Diagram](https://user-images.githubusercontent.com/13741332/76535069-4eee3380-64a0-11ea-92ab-eee637778a9e.png)

**Comment by tigercl** [comment]
@ashishtaldeokar If your power of consumption may be bottlenecked, then we recommend that you use shared subscriptions.

**Comment by ashishtaldeokar** [comment]
@tigercl this is exactly what I needed, thank you. using this [emqx doc](https://docs.emqx.io/tutorial/latest/en/advanced/share_subscribe.html).
