### ISSUE TITLE
Authentication chain slow working.

### ISSUE THREAD

**Issue by NikolayVasilyev** [emqx/emqx#3309]
#### Environment

- OS: Debian 10
- Erlang/OTP: Eshell V10.2.4
- EMQ:  4.0.2 

#### Description

Hi, everyone.

I need to have an HTTP authentication hook in my project.
But aside of that I need to have a `guest` user to pub/sub when the HTTP authentication service is not started yet. 
So, I have two authentication plugins activated: `emqx_auth_username` and `emqx_auth_http`.

It is said [here](https://docs.emqx.io/tutorial/latest/en/security/auth.html) that:
"""
When multiple authentication plugins are enabled, EMQ X will authenticate clients with plugin enable sequence.
"""
In `data/loaded_plugins` the sequence of plugins is the following:
```
...
{emqx_auth_username,true}.
{emqx_auth_http,true}.
```

For a guest user `/test/#` topics are allowed
And this command is working as expected without an HTTP authentication server is running:
```
$ mosquitto_pub -m "hello" -r -t "test/test" -u guest -P guest; mosquitto_sub -t "test/test" -u guest -P guest
```

But very slow! About 5 seconds.

In EMQ X log a see the following message:
```
(nikolay_pc@10.238.100.170)1> 2020-03-13 19:05:29.393 [error] <<"mosqpub|11469-debian">>@127.0.0.1:47774 [ACL http] Request ACL url http://127.0.0.1:8991/mqtt/acl, error: {failed_connect,
                                                                   [{to_address,
                                                                     {"127.0.0.1",
                                                                      8991}},
                                                                    {inet,
                                                                     [inet],
                                                                     econnrefused}]}
2020-03-13 19:05:29.394 [info] <<"mosqpub|11469-debian">>@127.0.0.1:47774 PUBLISH to test/test: <<"hello">>
2020-03-13 19:05:29.397 [error] <<"mosqsub|11470-debian">>@127.0.0.1:47778 [ACL http] Request ACL url http://127.0.0.1:8991/mqtt/acl, error: {failed_connect,
                                                                   [{to_address,
                                                                     {"127.0.0.1",
                                                                      8991}},
                                                                    {inet,
                                                                     [inet],
                                                                     econnrefused}]}
```
It looks like EMQ X is still asking for a HTTP authentication before checking with `emqx_auth_username` plugin.

Is plugin authentication is done as a chain of allow/deny/ignore sequence of done in parallel?
As it is said in documentation it should be a some kind of authentication chain.

Thanks.

**Comment by HJianBo** [comment]
There may be a misunderstanding. 

**Authentication and ACL are two separate chains.**  According to your logs, **Authentication** is running as expected, because of these connections is not sending the Authentication request by `emqx_auth_http` plugin.

In this case, the `emqx_auth_http` need to send a ***ACL checking*** to some a web server, because of the `emqx_auth_username` is not provided ACL function.

**Comment by NikolayVasilyev** [comment]
Thanks for reply.

It has become clearer now, but not completely obvious.

So, the authentication takes place as documented.
When it comes to check ACL the broker first asks with HTTP hook and only
when it fails it makes another try with internal `etc/acl.conf`.

Is there a way to change the ACL check sequence?

Thanks.

**Comment by HJianBo** [comment]
> when it fails it makes another try with internal etc/acl.conf.

When it **Matched** it will return the result (Allow/Deny) directly. If it gets an `Ignore`  result it makes another try with internal etc/acl.conf.

> Is there a way to change the ACL check sequence?

Nope. Or you can comment the acl_req options to disable `emqx_auth_http` ACL checking:

```
#auth.http.acl_req = http://127.0.0.1:8991/mqtt/acl
#auth.http.acl_req.method = get
#auth.http.acl_req.params = access=%A,username=%u,clientid=%c,ipaddr=%a,topic=%t,mountpoint=%m

```

**Comment by HJianBo** [comment]
Close it first. Plz reopen it if you have any questions :)
