### ISSUE TITLE
Failed to join the cluster

### ISSUE THREAD

**Issue by benandpao** [emqx/emqx#3310]
#### Environment
PC1:
- OS: Ubuntu18.04
- Erlang/OTP: R22/10.5.2
- EMQ: 4.0.4

PC2:
- OS: winserver-2008
- Erlang/OTP: R22/10.6
- EMQ: 4.0.4

configure：

cluster.discovery = static
emqx@192.168.147.118,emqx@192.168.147.116,emqx@192.168.147.115,emqx@10.0.1.170

#### Description
两台winserver里面的emqx可以自动集群，两台Ubuntu里面的emqx也可以自动集群。但是winserver里面的emqx无法与Ubuntu里面的emqx建立集群。
原因可能是建立集群的端口不同导致的。在winserver里面的端口是4369，在Ubuntu里面端口是4370。如果是这样，该如何更改集群的端口，使不同系统之间能够建立集群？

Emqx in two winservers can cluster automatically, and emqx in two Ubuntu can cluster automatically. But emqx in winserver cannot cluster with emqx in Ubuntu.
The reason may be that the ports of the cluster are different. Port 4369 in winserver and 4370 in Ubuntu.
 If so, how to change the ports of the cluster so that clusters can be established between different systems?

See  error message

`test@ubuntu-thinkstation-p710:~$ sudo emqx_ctl cluster join emqx@192.168.147.118
[sudo] test 的密码： 

Failed to join the cluster: {node_down,'emqx@192.168.147.118'}
`
View emqx port。 Port 4369 not started found ，but port 4370 started。
See  message
`
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
tcp        0      0 0.0.0.0:902             0.0.0.0:*               LISTEN      3356/vmware-authdla 
tcp        0      0 127.0.0.1:11883         0.0.0.0:*               LISTEN      1789/beam.smp       
tcp        0      0 0.0.0.0:8081            0.0.0.0:*               LISTEN      1789/beam.smp       
tcp        0      0 0.0.0.0:5938            0.0.0.0:*               LISTEN      2933/teamviewerd    
tcp        0      0 0.0.0.0:4370            0.0.0.0:*               LISTEN      1789/beam.smp       
tcp        0      0 127.0.0.1:8307          0.0.0.0:*               LISTEN      3421/vmware-hostd   
tcp        0      0 127.0.0.1:5939          0.0.0.0:*               LISTEN      2933/teamviewerd    
tcp        0      0 0.0.0.0:8883            0.0.0.0:*               LISTEN      1789/beam.smp       
tcp        0      0 0.0.0.0:8083            0.0.0.0:*               LISTEN      1789/beam.smp       
tcp        0      0 0.0.0.0:8084            0.0.0.0:*               LISTEN      1789/beam.smp       
tcp        0      0 127.0.0.53:53           0.0.0.0:*               LISTEN      1100/systemd-resolv 
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      1510/sshd           
tcp        0      0 0.0.0.0:8118            0.0.0.0:*               LISTEN      1789/beam.smp       
tcp        0      0 127.0.0.1:631           0.0.0.0:*               LISTEN      1152/cupsd          
tcp        0      0 0.0.0.0:5369            0.0.0.0:*               LISTEN      1789/beam.smp       
tcp        0      0 0.0.0.0:443             0.0.0.0:*               LISTEN      3421/vmware-hostd   
tcp        0      0 0.0.0.0:1883            0.0.0.0:*               LISTEN      1789/beam.smp       
tcp6       0      0 :::902                  :::*                    LISTEN      3356/vmware-authdla 
tcp6       0      0 :::5938                 :::*                    LISTEN      2933/teamviewerd    
tcp6       0      0 :::22                   :::*                    LISTEN      1510/sshd           
tcp6       0      0 ::1:631                 :::*                    LISTEN      1152/cupsd          
tcp6       0      0 :::443                  :::*                    LISTEN      3421/vmware-hostd   
udp        0      0 127.0.0.53:53           0.0.0.0:*                           1100/systemd-resolv 
udp        0      0 0.0.0.0:631             0.0.0.0:*                           1269/cups-browsed   
udp        0      0 0.0.0.0:33808           0.0.0.0:*                           1098/systemd-timesy 
udp        0      0 0.0.0.0:5353            0.0.0.0:*                           1221/avahi-daemon:  
udp        0      0 0.0.0.0:42552           0.0.0.0:*                           1221/avahi-daemon:  
udp6       0      0 :::5353                 :::*                                1221/avahi-daemon:  
udp6       0      0 :::41635                :::*                                1221/avahi-daemon:  

`

*A description of the issue*

 But I don't know how to change the port

**Comment by benandpao** [comment]
Port 4370 started。

**Comment by HJianBo** [comment]
Hi @benandpao  We don't recommend construct a cluster between different operation system :)
