### ISSUE TITLE
The same client connected to version 3.1 is normal, but abnormal when connecting to version 4.0

### ISSUE THREAD

**Issue by Gavinwgq** [emqx/emqx#3315]
#### Environment

- OS: win10
- Erlang/OTP: 
- EMQ: 4.0

#### Description
使用hivemq-client 1.1.4版本连接emq3.1版本正常，连接4.0版本提示错误（ConnAck 中Maximum QoS 返回值为2），联系客户端作者，得到如下反馈：
Followed by a Byte with a value of either 0 or 1. It is a Protocol Error to include Maximum QoS more than once, or to have a value other than 0 or 1. If the Maximum QoS is absent, the Client uses a Maximum QoS of 2.
可查看 https://docs.oasis-open.org/mqtt/mqtt/v5.0/os/mqtt-v5.0-os.html#_Toc3901084

**Comment by HJianBo** [comment]
Hi, @Gavinwgq We will fix it in v4.0.5. Thanks for your feedback

**Comment by HJianBo** [comment]
Duplicated: https://github.com/emqx/emqx/issues/3304

**Comment by HJianBo** [comment]
Fixed at v4.0.5
