### ISSUE TITLE
WEB UI does not operate for 2 minutes and cannot receive messages

### ISSUE THREAD

**Issue by 894827077** [emqx/emqx#3316]
#### Environment

- OS: 
- Erlang/OTP: 
- EMQ: 

#### Description

*A description of the issue*

**Comment by 894827077** [comment]
还有 硬件技术那边一直连接上后 一会就断开了  有大佬知道的吗

**Comment by turtleDeng** [comment]
Please provide detailed LOG.

**Comment by HJianBo** [comment]
Close it due to it may outdated. Plz reopen it if you have any problems
