### ISSUE TITLE
problem with websocket connection

### ISSUE THREAD

**Issue by khodadadi** [emqx/emqx#3324]
#### Environment

- OS: Debian 10
- Erlang/OTP: 21
- EMQ: 4.0.5

#### Description
hi
in the websocket connection, after client connected, all session messages that obtained from old channel, sent as one websocket message instead of send one mqtt packet by one websocket message. this behaviour is efficient but cause old clients not work properly.
this problem does not exist in emqx 3 and emq 2.

**Comment by tigercl** [comment]
@khodadadi We apologize for the inconvenience caused by our changes to your use. We will add a configuration item in the next release to choose whether to send one websocket message or send one mqtt packet by one websocket message.

**Comment by khodadadi** [comment]
thanks

**Comment by khodadadi** [comment]
hi @tigercl 
has a problem?  4.1-alpha.2 released.

**Comment by tigercl** [comment]
@khodadadi Sorry for late reply. We have fixed this problem on 4.2-rc.1. You can set `listener.ws/wss.<Listener Name>.mqtt_piggyback` to single to solve your problem. If you need to use it in a production environment, it is recommended to wait another one to two weeks before we will release the official version of 4.2.0.

**Comment by HJianBo** [comment]
https://github.com/emqx/emqx/pull/3673

**Comment by khodadadi** [comment]
thanks
@tigercl  @HJianBo
