### ISSUE TITLE
when open emqx_web_hook and emqx_rule_engine,console print error

### ISSUE THREAD

**Issue by czy-1** [emqx/emqx#3326]
#### Environment

- OS: windows 10
- Erlang/OTP: 22 [erts-10.7] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1]
- EMQ: 4.0.5

#### Description

*A description of the issue*

edit emqx_rule_engine.conf
rule_engine.events.client_connected = on

run
bin\emqx_ctl plugins reload emqx_rule_engine
bin\emqx_ctl plugins load emqx_web_hook

when client connected,console has this error
 [error] <<"5">>@127.0.0.1:11760 [Hooks] Failed to execute {emqx_web_hook,on_message_publish,[{undefined}]}: {function_clause,
                                                                             [{emqx_web_hook,
                                                                               on_message_publish,
                                                                               [{message,
                                                                                 <<0,5,161,
                                                                                   66,125,
                                                                                   58,246,
                                                                                   184,244,
                                                                                   67,0,0,
                                                                                   2,176,0,
                                                                                   1>>,
                                                                                 1,
                                                                                 emqx_events,
                                                                                 #{event =>
                                                                                    true,
                                                                                   sys =>
                                                                                    true},
                                                                                 undefined,
                                                                                 <<"$events/client_connected">>,
                                                                                 <<"{\"username\":\"5\",\"timestamp\":1584681824483,\"sockname\":\"127.0.0.1:1883\",\"proto_ver\":4,\"proto_name\":\"MQTT\",\"peername\":\"127.0.0.1:11760\",\"node\":\"emqx@127.0.0.1\",\"mountpoint\":\"undefined\",\"keepalive\":120,\"is_bridge\":false,\"expiry_interval\":0,\"event\":\"client.connected\",\"connected_at\":1584681824,\"clientid\":\"5\",\"clean_start\":true}">>,
                                                                                 1584681824483},
                                                                                {undefined}],
                                                                               [{file,
                                                                                 "d:/a/emqx-rel/emqx-rel/_build/emqx/lib/emqx_web_hook/src/emqx_web_hook.erl"},
                                                                                {line,
                                                                                 253}]},
                                                                              {emqx_hooks,
                                                                               safe_execute,
                                                                               2,
                                                                               [{file,
                                                                                 "d:/a/emqx-rel/emqx-rel/_build/emqx/lib/emqx/src/emqx_hooks.erl"},
                                                                                {line,
                                                                                 164}]},
                                                                              {emqx_hooks,
                                                                               do_run_fold,
                                                                               3,
                                                                               [{file,
                                                                                 "d:/a/emqx-rel/emqx-rel/_build/emqx/lib/emqx/src/emqx_hooks.erl"},
                                                                                {line,
                                                                                 143}]},
                                                                              {emqx_broker,
                                                                               publish,
                                                                               1,
                                                                               [{file,
                                                                                 "d:/a/emqx-rel/emqx-rel/_build/emqx/lib/emqx/src/emqx_broker.erl"},
                                                                                {line,
                                                                                 202}]},
                                                                              {emqx_broker,
                                                                               safe_publish,
                                                                               1,
                                                                               [{file,
                                                                                 "d:/a/emqx-rel/emqx-rel/_build/emqx/lib/emqx/src/emqx_broker.erl"},
                                                                                {line,
                                                                                 214}]},
                                                                              {emqx_rule_events,
                                                                               may_publish_and_apply,
                                                                               3,
                                                                               [{file,
                                                                                 "d:/a/emqx-rel/emqx-rel/_build/emqx/lib/emqx_rule_engine/src/emqx_rule_events.erl"},
                                                                                {line,
                                                                                 261}]},
                                                                              {emqx_hooks,
                                                                               safe_execute,
                                                                               2,
                                                                               [{file,
                                                                                 "d:/a/emqx-rel/emqx-rel/_build/emqx/lib/emqx/src/emqx_hooks.erl"},
                                                                                {line,
                                                                                 164}]},
                                                                              {emqx_hooks,
                                                                               do_run,
                                                                               2,
                                                                               [{file,
                                                                                 "d:/a/emqx-rel/emqx-rel/_build/emqx/lib/emqx/src/emqx_hooks.erl"},
                                                                                {line,
                                                                                 130}]}]}

**Comment by tigercl** [comment]
@czy-1 Sorry for the inconvenience caused to you, we will fix it in next release.
