### ISSUE TITLE
mqttjiar package mqttv-1.2.0.jar can not connected to emqx in Android 8.0 and above

### ISSUE THREAD

**Issue by SmallRedMonster** [emqx/emqx#3329]
Android 8.0以上版本测试 无法打开这个后台服务。
 Not allowed to start service Intent { cmp=com.chdl.cjs/org.eclipse.paho.android.service.MqttService }: app is in background uid UidRecord{727fd5e u0a170 SVC  idle change:idle|uncached procs:1 seq(0,0,0)}
有什么解决办法么？

**Comment by SmallRedMonster** [comment]
jar包mqttv3-1.2.0  这个情况在debug模式下会出现。但是release没问题

**Comment by Eluso** [comment]
Need more info/log,check debug and release use same class?
