### ISSUE TITLE
host URI mqtt://.. support

### ISSUE THREAD

**Issue by beraybentesen** [emqx/emqx#3331]
We are trying to use Ruby client library which is not supporting URI schema tcp://...

Is it possible to connect with different URI schema ? 

Thanks,

**Comment by HJianBo** [comment]
Nope. I thin that is the Client feture, not Broker. The Ruby client should parse the `tcp://..` schema to a IP addr and Port. Then connect to it. These steps is unknown for Broker!!!

**Comment by beraybentesen** [comment]
@HJianBo thank you for quick response. I will be fixing problem at the client side.
