### ISSUE TITLE
EMQ X can't communicate with C/Java Node

### ISSUE THREAD

**Issue by wwhai** [emqx/emqx#3334]
EMQ默认使用EKKA实现集群策略，但是目前有需求是使用EPMD，通过研究文档和资料发现EKKA不兼容EPMD，导致外部程序无法和Erlang通信，所以目前想了解一下，如果采用了EPMD以后，会不会对EMQ造成一些问题？

================================================
EMQ uses EKKA by default to implement the cluster strategy, but currently there is a need to use EPMD. 

Through researching documents and materials, it is found that EKKA is not compatible with EPMD, resulting in external programs being unable to communicate with Erlang. Cause some problems to EMQ?

**Comment by HJianBo** [comment]
EPMD is complete compatibility from emqx. You don't have to worry about this kind of problem

In addition, The ekka has no plan to support all features of epmd to communicate with Erlang Port or C/Java node.

If you have these requirements, Plz enable epmd instead of `ekkd-epmd`

**Comment by wwhai** [comment]
> EPMD is complete compatibility from emqx. You don't have to worry about this kind of problem
> 
> In addition, The ekka has no plan to support all features of epmd to communicate with C/Java node.
> 
> If you have these requirements, Plz enable epmd instead of `ekkd-epmd`

Thank you,my bigbobo.
