### ISSUE TITLE
Request super user url error

### ISSUE THREAD

**Issue by beraybentesen** [emqx/emqx#3336]
[Auth http] Request superuser url http://127.0.0.1:8080/mqtt/superuser, error: {failed_connect,
                                                                                [{to_address,
                                                                                  {"127.0.0.1",
                                                                                   8080}},
                                                                                 {inet,
                                                                                  [inet],
                                                                                  econnrefused}]}

I am not doing superuser call, and can connect from different libraries.

**Comment by tigercl** [comment]
@beraybentesen Please modify the port in the `emqx_auth_http.conf`. The 8080 port has been already occupied by emqx.

**Comment by tigercl** [comment]
@beraybentesen I'm sorry that I didn't read your log clearly just now. `econnrefused` means connection refused by the server. You can comment items about superuse in `emqx.conf`, if you have did it, you should reload the plugin.

**Comment by beraybentesen** [comment]
Thanks, setting ack_timeout on the client library fixed the problem.
