### ISSUE TITLE
Setting rate limit per client

### ISSUE THREAD

**Issue by beraybentesen** [emqx/emqx#3337]
Is is possible to set limits for connected client ? Max 20 per minute e.g.

**Comment by tigercl** [comment]
@beraybentesen I think `publish_limit` and `rate_limit` in `emqx.conf` can meet your needs.

**Comment by beraybentesen** [comment]
@tigercl I believe that it is a general limit. Let's say there is a device subscribed and publishing event and you want to rate it's limit via the rest api.
