### ISSUE TITLE
source code compile failed

### ISSUE THREAD

**Issue by ohmygd** [emqx/emqx#3338]
#### Environment

- OS: windows10
- Erlang/OTP:  22.1
- EMQ: 3.2.7 or latest

#### Description
in linux , i download emq 3.2.7 source code, download rebar3, make, everything is fine.

but when i'm in windows, use idea set rebar3 configure, use idea to compile the source code, it turns to be Hook for app_compile failed, i tried the latest emq version, it still have the problem.

i have tried many times, but useless, there's no help i can get online,

Please, Thank you.

**Comment by HJianBo** [comment]
We have not compiled it with IDEA. And do not recommend compile it with windows. It has a lot of annoying tools to configure.


Some guides on windows:

0. Try to compile it with PowerShell
1. Install `scoop` for PowerShell
2. Install the necessary tools
    ```
    scoop install git
    scoop bucket add extras
    scoop install vcredist
    scoop install erlang make grep
    ``` 
3. Install the MinGW-64: [Download](https://osdn.net/projects/mingw/downloads/68260/mingw-get-setup.exe/), [Guides](http://www.mingw.org/wiki/Getting_Started) and setup it's envs

After complete all of these setups, you can clone the `emqx-rel` repository and  run`make` to compile it

**Comment by ohmygd** [comment]
> We have not compiled it with IDEA. And do not recommend compile it with windows. It has a lot of annoying tools to configure.
> Some guides on windows:
> 
> Try to compile it with PowerShell
> Install scoop for PowerShell
> Install the necessary tools
> scoop install git
> scoop bucket add extras
> scoop install vcredist
> scoop install erlang make grep
> 
> 
> Install the MinGW-64: Download, Guides and setup it's envs
> 
> After complete all of these setups, you can clone the emqx-rel repository and  runmake to compile it

Thanks.  
so what's the tool the official recommanded for erlang, for emq if i don't use idea, i use it for the emqx/emqx, so i can debug to learn how the emq works. i can get the src directory

**Comment by HJianBo** [comment]
Nope.  

Usually, we debug the system more by printing logs or [dbg]() tools.  If you want to step through the execution of the program, the IDEA may be the best tool in the current.

I believe it should work in IDEA if it can be compiled on PowerShell. Maybe you need to take some time to configure it

**Comment by HJianBo** [comment]
Close it first. 

Please let me know if you have others problem
