### ISSUE TITLE
use source code to compile but it failed

### ISSUE THREAD

**Issue by kasikoliu** [emqx/emqx#3339]
Environment:
OS: ubuntu 16.04
Erlang/OTP: Erlang/OTP 21 [erts-10.3]
EMQ: emqx-rel 4.0.0

Description 
 I download the emqx 4.0 rel code and compile, but failed.
compile  information as following:
root@ubuntuinit-virtual-machine:~/emqx-rel# make
===> Plugin rebar3_run not available. It will not be used.
===> Verifying dependencies...
===> Fetching emqx (from {git,"https://github.com/emqx/emqx",{tag,"v4.0.0"}})
===> Plugin coveralls not available. It will not be used.
===> Plugin coveralls not available. It will not be used.
===> Fetching emqx_auth_clientid (from {git,"https://github.com/emqx/emqx-auth-clientid",
                              {tag,"v4.0.0"}})
===> Fetching emqx_auth_http (from {git,"https://github.com/emqx/emqx-auth-http",
                          {tag,"v4.0.0"}})
===> Fetching emqx_auth_jwt (from {git,"https://github.com/emqx/emqx-auth-jwt",
                         {tag,"v4.0.0"}})
===> Fetching emqx_auth_ldap (from {git,"https://github.com/emqx/emqx-auth-ldap",
                          {tag,"v4.0.0"}})
===> Fetching emqx_auth_mongo (from {git,"https://github.com/emqx/emqx-auth-mongo",
                           {tag,"v4.0.0"}})
===> Fetching emqx_auth_mysql (from {git,"https://github.com/emqx/emqx-auth-mysql",
                           {tag,"v4.0.0"}})
===> Fetching emqx_auth_pgsql (from {git,"https://github.com/emqx/emqx-auth-pgsql",
                           {tag,"v4.0.0"}})
===> Fetching emqx_auth_redis (from {git,"https://github.com/emqx/emqx-auth-redis",
                           {tag,"v4.0.0"}})
===> Fetching emqx_auth_username (from {git,"https://github.com/emqx/emqx-auth-username",
                              {tag,"v4.0.0"}})
===> Fetching emqx_bridge_mqtt (from {git,"https://github.com/emqx/emqx-bridge-mqtt",
                            {tag,"v4.0.0"}})
===> Fetching emqx_coap (from {git,"https://github.com/emqx/emqx-coap",{tag,"v4.0.0"}})
===> Fetching emqx_dashboard (from {git,"https://github.com/emqx/emqx-dashboard",
                          {tag,"v4.0.0"}})
===> Fetching emqx_delayed_publish (from {git,"https://github.com/emqx/emqx-delayed-publish",
                                {tag,"v4.0.0"}})
===> Fetching emqx_lua_hook (from {git,"https://github.com/emqx/emqx-lua-hook",
                         {tag,"v4.0.0"}})
===> Fetching emqx_lwm2m (from {git,"https://github.com/emqx/emqx-lwm2m",{tag,"v4.0.0"}})
===> Fetching emqx_management (from {git,"https://github.com/emqx/emqx-management",
                           {tag,"v4.0.0"}})
===> Fetching emqx_plugin_template (from {git,"https://github.com/emqx/emqx-plugin-template",
                                {tag,"v4.0.0"}})
===> Fetching emqx_psk_file (from {git,"https://github.com/emqx/emqx-psk-file",
                         {tag,"v4.0.0"}})
===> Fetching emqx_recon (from {git,"https://github.com/emqx/emqx-recon",{tag,"v4.0.0"}})
===> Fetching emqx_reloader (from {git,"https://github.com/emqx/emqx-reloader",
                         {tag,"v4.0.0"}})
===> Fetching emqx_retainer (from {git,"https://github.com/emqx/emqx-retainer",
                         {tag,"v4.0.0"}})
===> Fetching emqx_rule_engine (from {git,"https://github.com/emqx/emqx-rule-engine",
                            {tag,"v4.0.0"}})
===> Plugin rebar3_proper not available. It will not be used.
===> Plugin rebar3_proper not available. It will not be used.
===> Fetching emqx_sn (from {git,"https://github.com/emqx/emqx-sn",{tag,"v4.0.0"}})
===> Plugin coveralls not available. It will not be used.
===> Plugin coveralls not available. It will not be used.
===> Fetching emqx_statsd (from {git,"https://github.com/emqx/emqx-statsd",{tag,"v4.0.0"}})
===> Fetching emqx_stomp (from {git,"https://github.com/emqx/emqx-stomp",{tag,"v4.0.0"}})
===> Plugin coveralls not available. It will not be used.
===> Plugin coveralls not available. It will not be used.
===> Fetching emqx_web_hook (from {git,"https://github.com/emqx/emqx-web-hook",
                         {tag,"v4.0.0"}})
===> Package not found in any repo: recon 2.5.0
Makefile:50: recipe for target 'emqx' failed
make: *** [emqx] Error 1

I don't know what to do with the problem,please help me.

**Comment by HJianBo** [comment]
Could you access the `hex.pm`?

The `recon` and some other libraries are hosting on it. You must make sure you can access it.

Or clone it into `/_build/emqx/lib` by manually

**Comment by kasikoliu** [comment]
> Could you access the `hex.pm`?
> 
> The `recon` and some other libraries are hosting on it. You must make sure you can access it.
> 
> Or clone it into `/_build/emqx/lib` by manually

Thanks for your reply. 
Yes, My browser can access hex.pm.
Many emqx eps have lost ,but rebar3 can't download package from hex.pm.
What do you think have made this happen?

**Comment by HJianBo** [comment]
The biggest possibility is that pm.hex is blocked outside the wall if you are located in CHINA. In this case, you should set a proxy for accessing `hex.pm` :)

**Comment by kasikoliu** [comment]
> The biggest possibility is that pm.hex is blocked outside the wall if you are located in CHINA. In this case, you should set a proxy for accessing `hex.pm` :)

Yes,It works. the machine can automatically download the require libs now.
Thanks for your help.
