### ISSUE TITLE
Persistend Session ignoring ACL permission

### ISSUE THREAD

**Issue by Klabau** [emqx/emqx#3340]
#### Environment

- OS: Kubernetes/Docker
- EMQ: emqx/emqx:v4.0.3
- Plugins: emqx_management, emqx_rule_engine, emqx_recon, emqx_retainer, emqx_auth_mongo, emqx_dashboard

#### Description

Broker setup with emqx_auth_mongo plugin. I created two clients: _client1_ and _client2_, both with password protection and topic subscription privilege for _client1_: _topic/client1_ and _client2_: _topic/client2_.  
  
Authentication works all fine. Both clients are not able to subscribe to topics of the other.  
  
Problem:
1. Create a persistent session with _client1_ and assign him with the client id _clientIdOfClient1_ and subscribe to _topic/client1_
2. Close connection
3. Create a persistent session with _client2_ and assign him with _client1_' client id _clientIdOfClient1_
4. _client2_ will now receive all messages published to _topic/client1_ even if he has no privileges to do so.

Is this a bug?  
If no: is there any way to double check the authentication with emqx_auth_mongo plugin?

**Comment by Klabau** [comment]
Update: username/password authentication is still working - _client2_ is not able to connect with _clientIdOfClient1_ and bad password . Only acl permission is not respected...

**Comment by HJianBo** [comment]
Haha, This is a very strange result actually. Thanks for your feedback there. We will discuss the security problems.

In the current version,  The ACL rules based on the `clientid`  is better practice

**Comment by HJianBo** [comment]
Why are the `clientIdOfClient1` will use a different username?

Has practical usage scenarios for you?

**Comment by Klabau** [comment]
@HJianBo I was just trying to be lazy and reuse the username as a clients id, so i would not need to save a randomized id until next login 😁 

But with this in mind, the clientId needs to be handled as a secret, which might be an additional security issue at some point.

Is there any documentation about why it is better to use a clientid for acl permission?

**Comment by HJianBo** [comment]
>  I was just trying to be lazy and reuse the username as a clients id, so i would not need to save a randomized id until next login

Maybe you can enable this option:
```
# emqx.conf
zone.external.use_username_as_clientid = true
```

The v4.0 docs are under production. It may take some weeks
