### ISSUE TITLE
Symantec antivirus blocking jiffy.dll hence unable to login in dashboard

### ISSUE THREAD

**Issue by kedar-hatkar** [emqx/emqx#3349]
#### Environment

- OS: Windows 10
- Erlang/OTP: 
- EMQ: 4.0.4

#### Description

This issue started from EMQ X broker software version 4.0.4 and continue in 4.0.5. Symantec antivirus is blocking emqx\lib\jiffy-1.0.2\priv\jiffy.dll file. Since this file is blocked and quarantine in anti virus folder, i am not able to login in dashboard page with default credentials.

Anti virus says there is not enough information about this file to recommend it. Is this file safe to allow it in antivirus?

I can use EMQ X 4.0.3 version successfully and log in dashboard.

**Comment by HJianBo** [comment]
Sorry, @kedar-hatkar I didn't think it will cause this kind of problem. But I think this file is should be safe enough if you download this package from the official website. The `jiffy.dll` is necessary for encoding/decoding JSON in emqx.

**Comment by HJianBo** [comment]
Close it first. 

If you have any problems, let me known

**Comment by himanga** [comment]
This just happened to me as well: the file was blocked during install and then unable to open the dashboard.  Are there any plans to address this or would we need an exception in Symantec in order to use emqx?
