### ISSUE TITLE
emqx always  receive  message from   Mqtt Bridge problem

### ISSUE THREAD

**Issue by leexuzee0** [emqx/emqx#3350]
#### Environment

- OS: ubuntu 18.04
- Erlang/OTP: R22/10.52
- EMQ:  emqx broker 4.05   and emqx broker 4.03

#### Description

*A description of the issue*

I  had deployed emqx broker 4.03  and emqx broker 4.05  on two machine .  And I send message from emqx broker 4.05  to emqx broker 4.03  through  Rule Engine and   bridge_mqtt action handle.  At first is work fine but later on I find Rule Engine Matched number in emqx broker 4.05   had not increased yet,but 
emqx broker 4.03 still can receve message. I think is very strange,I don't konw why?

Thanks!

here is my config

emqx broker 4.05  

 Basic Info
Topic:
temp_humi/#
Description:
SQL:
SELECT payload FROM "temp_humi/#"

Action Handler 
data_to_mqtt_broker | Resource: resource:4da40493

Details
ID
resource:4da40493
Resource Type
bridge_mqtt
Description
Configuration
username
admin
ssl
off
retry_interval
20s
reconnect_interval
30s
proto_ver
mqttv4
password
public
mountpoint
dgoffice_emqx/
keyfile
etc/certs/client-key.pem
keepalive
60s
disk_cache
on
clientid
bridge_aws
ciphers
ECDHE-ECDSA-AES256-GCM-SHA384,ECDHE-RSA-AES256-GCM-SHA384
certfile
etc/certs/client-cert.pem
cacertfile
etc/certs/cacert.pem
bridge_mode
true
address
10.0.0.100:1883

and here is the message pag of emqx broker 4.03
![图片](https://user-images.githubusercontent.com/38236268/77812721-1bd1b400-70de-11ea-889a-830051b66d0b.png)

**Comment by leexuzee0** [comment]
I found the  Action handle  in  Rule Engine  every 5 seconds  trigger  once  ,but  my message 3 secondes once, so the messages from emqx  were delayed. 
How can I let Action handle of emqx  trigger in time?

**Comment by leexuzee0** [comment]
here is two picuter , one from emqx 4.0.5,other from emqx 4.0.3, you can see the message delay so mush in emqx 4.0.3
![图片](https://user-images.githubusercontent.com/38236268/78202905-1bfbf600-74c8-11ea-854c-ea240074afbe.png)
![图片](https://user-images.githubusercontent.com/38236268/78202929-2b7b3f00-74c8-11ea-9c45-15fbf2469325.png)

**Comment by turtleDeng** [comment]
Sorry, I did not reply to you in time.
From the above situation, your 2 questions
1 Rule engine statistics are incorrect?
2 Message passing through the rules engine is delayed?

**Comment by leexuzee0** [comment]
Thank you very much!
I found Message passing through the rules engine was  delayed.
And here is my SQL statements for  Rule engine

SELECT payload FROM "temp_humi/#"


now I solve the problem by subscribe message in my nodejs serve.

**Comment by wwhai** [comment]
> Thank you very much!
> I found Message passing through the rules engine was delayed.
> And here is my SQL statements for Rule engine
> 
> SELECT payload FROM "temp_humi/#"
> 
> now I solve the problem by subscribe message in my nodejs serve.

———
What’s  process latter? Are you face this problem again?

**Comment by HJianBo** [comment]
Close it first.

Plz open it or open a new one, if you have any updates

**Comment by saqib-cielo** [comment]
Emqx as a bridge with AWS Iot broker behaving unexpectedly(getting duplicate messages burst with any Qos level), normally happen when we start publishing messages with some pace, check all config params but no luck, did anyone came across similar issue.
