### ISSUE TITLE
EMQX start fail using docker (without detials fails logs)

### ISSUE THREAD

**Issue by GeeMing** [emqx/emqx#3351]
#### Environment

- OS: 
```sh
$ lsb_release -a

Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.4 LTS
Release:	18.04
Codename:	bionic
```

- Erlang/OTP: 
- EMQ: `v4.0.4-alpine3.10-amd64`

#### Description

I start up a emqx server using following cmd:
```sh
docker run --name emqx-tst -p 1883:1883 -p 8083:8083 -p 8883:8883 -p 8084:8084 -p 18083:18083 emqx/emqx:v4.0.4-alpine3.10-amd64
```
but eventually fail with this limited log infomation on terminal:
```sh
node.max_ports=1048576
listener.tcp.external.acceptors=64
listener.ssl.external.acceptors=32
node.process_limit=2097152
node.max_ets_tables=2097152
listener.ws.external.acceptors=16
node.name=fd944d79e05d@172.17.0.2

=====
===== LOGGING STARTED Sat Mar 28 03:02:19 UTC 2020
=====
['2020-03-28T03:02:59Z']:emqx exit abnormally
```
I had tried using normal deb pkg to install the emqx, and it can start up properly. 
And, start up a emqx container without directly running emqx service but a shell, then manually start emqx using `emqx start`, will also able to run properly.

This issue may vary from PC to PC, the same version of EMQX and OS (same vbox VM files),  one can startup successfully, some not.

But with this limited information, I cannot determine what's going on, any solution/suggestion? Thanks!

extra log/info:
logs in `/opt/emqx/log`:
`erlang.log.1 `
```
=====
===== LOGGING STARTED Sat Mar 28 03:02:19 UTC 2020
=====

=====
===== LOGGING STARTED Sat Mar 28 03:15:06 UTC 2020
=====
```

`run_erl.log`
```
run_erl [1849] Sat Mar 28 03:15:06 2020
Args before exec of shell:
run_erl [1849] Sat Mar 28 03:15:06 2020
argv[0] = sh
run_erl [1849] Sat Mar 28 03:15:06 2020
argv[1] = -c
run_erl [1849] Sat Mar 28 03:15:06 2020
argv[2] = exec "/opt/emqx/bin/emqx" "console"
```

**Comment by zhanghongtong** [comment]
Hi, @GeeMing 
When the container startup is not successful, could you please package `/opt/emqx/data` directory in the container as an attachment and share with us

**Comment by GeeMing** [comment]
Hi,@zhanghongtong

**Comment by lukecyca** [comment]
I had exactly the same issue. Any progress on this?

**Comment by zmstone** [comment]
Hi. I am having a look into this.
It seems to me `run_erl` exited with some unexpected error.
it's hard to tell what exactly went wrong.
Could you help to add a `-x` option to the `emqx` script ?

1. Make a copy of the `emqx` script to `tmp/emqx` in host:

```
docker create --name emqx-tmp emqx/emqx:v4.0.4-alpine3.10-amd64
docker cp emqx-tmp:/opt/emqx/bin/emqx /tmp/emqx
docker rm emqx-tmp
```
2. Edit the file, change line 5 to `set -ex`

3. Start emqx container with the file mounted. i.e. execute `docker run` with option `-v /tmp/emqx:/opt/emqx/bin/emqx`

4. Inspect `/opt/emqx/log/erlang.log.1` inside the container in case it fails to start.

**Comment by zmstone** [comment]
FYI. Will make it easier by fixing this issue: https://github.com/emqx/emqx-rel/issues/600

**Comment by GeeMing** [comment]
Sorry buddy, as the day goes by I can't reproduce the issue again : ( 
As you said, anyone who suffered the same issue can use `-x` option to investigate more.

I think the issue could be closed now.

**Comment by zmstone** [comment]
@lukecyca Feel free to reopen or create a new issue if this is still an issue for you.
