### ISSUE TITLE
emqtt_bench error during testing

### ISSUE THREAD

**Issue by ZJXAWC** [emqx/emqx#3353]
#### Environment

- OS: centos
- Erlang/OTP: lastest
- EMQ: lastest

#### Description
使用emqtt_bench测试一段时间后总会出错，不知道是压测软件的问题还是服务器问题？
服务器是1核2g 1m,测试命令为：
./emqtt_bench pub -t t -h ip -c 20 -I 1000 
./emqtt_bench sub -t t -h ip -c 20

=ERROR REPORT==== 29-Mar-2020::22:22:07.416288 ===
** State machine <0.121.0> terminating
** Last event = {cast,{mqtt_packet,{mqtt_packet_header,14,false,0,false},
                                   {mqtt_packet_disconnect,141,#{}},
                                   undefined}}
** When server state  = {connected,
                            {state,undefined,<0.120.0>,undefined,
                                "193.112.74.45",1883,[],emqtt_sock,
                                #Port<0.20>,[],60000,false,
                                <<"MacBook-Pro_bench_sub_13_4262958857">>,
                                true,<<"user">>,<<"psw">>,5,<<"MQTT">>,
                                300,#Ref<0.3727803350.876871682.83679>,false,
                                false,false,
                                {mqtt_msg,0,false,false,undefined,undefined,
                                    undefined,undefined},
                                #{'Maximum-Packet-Size' => 1048576,
                                  'Retain-Available' => 1,
                                  'Shared-Subscription-Available' => 1,
                                  'Subscription-Identifier-Available' => 1,
                                  'Topic-Alias-Maximum' => 65535,
                                  'Wildcard-Subscription-Available' => 1},
                                [],
                                #{<<"t">> =>
                                      #{nl => 0,qos => 0,rap => 0,rh => 0}},
                                infinity,#{},#{},true,30000,undefined,0,
                                undefined,0,4,
                                {none,#{max_size => 268435455,version => 5}}}}
** Reason for termination = exit:{disconnected,141,#{}}
** Callback mode = state_functions
** Stacktrace =
**  [{gen_statem,loop_state_callback_result,11,
                 [{file,"gen_statem.erl"},{line,1284}]},
     {proc_lib,wake_up,3,[{file,"proc_lib.erl"},{line,259}]}]

**Comment by ZJXAWC** [comment]
貌似当订阅消息总数到360000就会出错。
recv(900001): total=360000, rate=400(msg/sec)
然后下面就报错。

**Comment by tigercl** [comment]
@ZJXAWC Hi. Sorry for late reply, it is recommended to specify the `-k 0` option for the subscriber.

**Comment by HJianBo** [comment]
Close it first. 

Please let me know if you have any updates
