### ISSUE TITLE
What is default user/password for <host>:8081/api/v4/mqtt/publish

### ISSUE THREAD

**Issue by tmpm697** [emqx/emqx#3355]
#### Environment

- OS: Archlinux
- Erlang/OTP: 
- EMQX: 4.0.5

#### Description

With default standalone setup of one emqx node, I'm trying to access `<host>:8081/api/v4/mqtt/publish` but it asks for user/password. I tried admin/public but wrong accoung.

As fresh installation on ubuntu 18.04, I haven't touched or enabled anything. So `emqx_auth_username` plugin not enabled.

Follow this [guide](https://docs.emqx.io/broker/v3/en/rest.html#basic-authentication):
```
The HTTP requests to the REST API are protected with HTTP Basic authentication
```

I tried to access `<host>:8081/api/v4/mqtt/publish` use `AppName`/`AppId`, `AppId/AppSecret` but not work.
1. I haven't enabled `emqx_auth_username` auth plugin, why REST API are protected with HTTP basic authentication by default?
2. What is account to access `<host>:8081/api/v4/mqtt/publish`?
3. How to secure `<host>:8081/api/v4/mqtt/publish`?

**Comment by mcoder2014** [comment]
The default AppId and AppSercet are "Admin" and "public", same with dashboard. You can create new in dashboard->MANAGEMENT->Applications.

[doc](https://docs.emqx.io/broker/latest/en/rest.html#basic-authentication)
