### ISSUE TITLE
apt repository does not have a Release file

### ISSUE THREAD

**Issue by victorclaessen** [emqx/emqx#3356]
#### Environment

- OS: Debian 10
- Erlang/OTP: n/a
- EMQ: 4

#### Description

This error presents itself on following the [Debian install instructions](https://docs.emqx.io/broker/v4/en/install.html#debian)

    root@felice-control:/etc/apt/sources.list.d# apt update                                             |
    Hit:1 http://security.debian.org/debian-security buster/updates InRelease                           |
    Hit:2 http://deb.debian.org/debian buster InRelease                                                 |
    Hit:3 http://deb.debian.org/debian buster-updates InRelease                                         |
    Ign:4 https://repos.emqx.io/emqx-ce/deb/debian buster InRelease                                     |
    Err:5 https://repos.emqx.io/emqx-ce/deb/debian buster Release                                       |
      404  Not Found [IP: 13.227.198.74 443]                                                            |
    Reading package lists... Done                                                                       |
    E: The repository 'https://repos.emqx.io/emqx-ce/deb/debian buster Release' does not have a Release |
    file.                                                                                               |
    N: Updating from such a repository can't be done securely, and is therefore disabled by default.    |
    N: See apt-secure(8) manpage for repository creation and user configuration details. 

While manually browsing the repo, I noticed that indeed these is no Release file on the Debian repository. The [raspbian repository ](http://ec2-13-57-33-89.us-west-1.compute.amazonaws.com:8081/emqx-ce/deb/raspbian/dists/buster/) does seem to have one.

**Comment by zhanghongtong** [comment]
Hi, @victorclaessen 
Thanks for your feedback, now  you can install emqx on debian 10 via apt repository

**Comment by victorclaessen** [comment]
I still get this warning

    W: Conflicting distribution: https://repos.emqx.io/emqx-ce/deb/debian buster InRelease (expected buster but got )
but it works. Thank you
