### ISSUE TITLE
clientid is unique,but always remind conflict and kickout

### ISSUE THREAD

**Issue by EchoXBR** [emqx/emqx#3357]
#### Environment

- OS: CentOS 7.6 64位
- Erlang/OTP: R21/10.3.5.1
- EMQ: 3.2.2

#### Description

There's a lot of conflicting data in 'emqx.log.5' and 'erlang.log.5' like this
2020-03-31 09:33:27.532 [warning] 86375804013709@14.115.175.74:10959 [Channel] Clientid '86375804013709' conflict with <0.18406.1216>
2020-03-31 09:33:27.534 [warning] 86375804013709 [Session] Connection <0.18406.1216> kickout <0.5694.1211>

I'm sure the clientid is not conflict

**Comment by tigercl** [comment]
@EchoXBR These logs do not indicate that your client ID conflicts, but that your old session was taken over by a new process when the client reconnected.

**Comment by RodaBVB** [comment]
#### Environment
- OS: Ubuntu 16.04.5 LTS
- Erlang/OTP: 18
- EMQ: 3.2.2

#### Topology
- 2x EMQX in cluster (8vCPU, 15GB RAM each) ~50K clients

Hi @tigercl 

I am also facing the same warnings, any reason why this warning is occurring ?
```
(emqx@10.122.53.46)1> 2020-03-24 08:14:01.391 [warning] client-00000000001@10.122.249.12:58311 [Channel] Clientid 'client-00000000001' conflict with <0.9918.127>
(emqx@10.122.53.46)1> 2020-03-24 08:14:01.393 [warning] client-00000000001 [Session] Connection <0.9918.127> kickout <0.16717.111>
(emqx@10.122.53.46)1> 2020-03-24 08:14:43.282 [warning] client-00000000002@10.122.249.12:64671 [Channel] Clientid 'client-00000000002' conflict with <0.10271.127>
(emqx@10.122.53.46)1> 2020-03-24 08:14:43.284 [warning] client-00000000002 [Session] Connection <0.10271.127> kickout <0.30523.126>
(emqx@10.122.53.46)1> 2020-03-24 08:15:08.328 [warning] client-00000000002@10.122.249.12:58735 [Channel] Clientid 'client-00000000002' conflict with <0.10375.127>
(emqx@10.122.53.46)1> 2020-03-24 08:15:08.330 [warning] client-00000000002 [Session] Connection <0.10375.127> kickout <0.10271.127>
(emqx@10.122.53.46)1> 2020-03-24 08:15:29.704 [warning] client-00000000003@10.122.249.12:20767 [Channel] Clientid 'client-00000000003' conflict with <0.10434.127>
(emqx@10.122.53.46)1> 2020-03-24 08:15:29.706 [warning] client-00000000003 [Session] Connection <0.10434.127> kickout <0.13045.42>
```
Can you explain this  in more detail?

**Comment by EchoXBR** [comment]
I don't why client can appear many connectionLost
''
 java.io.EOFException
	at org.eclipse.paho.client.mqttv3.internal.CommsReceiver.run(CommsReceiver.java:190)
	at java.lang.Thread.run(Thread.java:764)
Caused by: java.io.EOFException
	at java.io.DataInputStream.readByte(DataInputStream.java:270)
	at org.eclipse.paho.client.mqttv3.internal.wire.MqttInputStream.readMqttWireMessage(MqttInputStream.java:92)
	at org.eclipse.paho.client.mqttv3.internal.CommsReceiver.run(CommsReceiver.java:137)
	... 1 more
''
In this connectionLost callback I try to reconnect, then the server will show the conflict log and kitout,,client will reconnect,it will goto Infinite loop

now I don't handle the connecttionLost callback....so ther is no conflict and kitout
but I still don't know why there are many connectionLost callback...
