### ISSUE TITLE
zone.internal and zone.external config difference in emqx.conf

### ISSUE THREAD

**Issue by 303489429** [emqx/emqx#3361]
#### Environment

- OS: LINUX CentOS 7
- Erlang/OTP: 
- EMQ:  4.0.5

#### Description

*A description of the issue*
question 1 ：zone.internal. and zone.external. What is the difference between the two configurations。

**Comment by tigercl** [comment]
@303489429  You can get more information about zone in [issue#3282](https://github.com/emqx/emqx/issues/3282).

**Comment by tmpm697** [comment]
https://docs.emqx.io/tutorial/latest/en/config/zone.html
