### ISSUE TITLE
no match of right hand side value errors many times

### ISSUE THREAD

**Issue by sudhamab** [emqx/emqx#3362]
#2601 ## Environment

- OS:  Ubuntu 18.04.2 LTS
- Erlang/OTP: 20
- EMQ: 3.1.2

#### Description
EMQX Team, hope you all are safe in these crucial times globally. Thank you for building a great system like EMQX. 

We keep seeing thousands of such log messages in the error logs. Also, many of our messages seem to be getting dropped even with QOS2.  But not sure if it's because of this error or things like "max_mqueue_len". Would be grateful if you can help us resolve this error

I read in one of the github issues that the user permissions on the ssl certs did not have 'emqx' as owner but we do. So wondering why this error is coming so many times.  

Thanks so much in advance! 

*A description of the issue*
```
2020-03-31 05:57:47.488 [error] supervisor: 'esockd_connection_sup - <0.1708.0>'
    errorContext: connection_crashed
    reason: {{badmatch,{error,tls_alert}},
             [{emqx_connection,init,1,
                               [{file,"src/emqx_connection.erl"},{line,146}]},
              {proc_lib,init_p_do_apply,3,
                        [{file,"proc_lib.erl"},{line,249}]}]}
    offender: [{pid,<0.14859.104>},
               {name,connection},
               {mfargs,
                   {emqx_connection,start_link,
                       [[{deflate_options,[]},
                         {max_conn_rate,500},
                         {active_n,100},
                         {zone,external}]]}}]
2020-03-31 06:14:11.096 [error] crasher:
    initial call: emqx_connection:init/1
    pid: <0.17139.104>
    registered_name: []
    exception error: no match of right hand side value {error,tls_alert}
      in function  emqx_connection:init/1 (src/emqx_connection.erl, line 146)
    ancestors: [<0.1708.0>,<0.1707.0>,esockd_sup,<0.1364.0>]
    message_queue_len: 0
    messages: []
    links: [<0.1708.0>]
    dictionary: []
    trap_exit: false
    status: running
    heap_size: 4185
    stack_size: 27
    reductions: 5751
  neighbours:
```

**Comment by zhanghongtong** [comment]
Hi, @sudhamab 
We have fixed this issue in version 3.2.4, and we recommend that you upgrade the version of emqx

**Comment by sudhamab** [comment]
thank  you @zhanghongtong  ! Any reference for how to upgrade to this? It's been a while since I set this up 

Also a few months ago, Zhengyu Pan  from your team had shared with us a patch of code for some other issue we were facing. 

So I will have to check with and without that and I am afraid to mess anything up. 

Would be grateful for your advise

**Comment by zhanghongtong** [comment]
You're welcome :)

**Comment by sudhamab** [comment]
hi @zhanghongtong please could you confirm whats the easiest way for me to update to this version? 

I looked at this 
[EMQX doc for upgrading ](https://docs.emqx.io/broker/v3/en/upgrade.html)
but it does not have instructions for 3.2.x

And it's not clear if I should run 
sudo apt upgrade emqx OR 
sudo apt install emqx 
first? 

PLEASE NOTE THAT
1. we have applied some patch to the code. so not sure if sudo apt upgrade will work 
2. The first time i installed i ran the following commands to install 
```
sudo add-apt-repository     "deb [arch=amd64] https://repos.emqx.io/emqx-ce/deb/ubuntu/ \
$(lsb_release -cs) \
stable"

sudo apt update

sudo apt install emqx
```
3. we are using the http plugin as well 

I don't want to mess up so please advise

**Comment by zhanghongtong** [comment]
Hi, @sudhamab 
Sorry, we don't have a smooth upgrade plan, I suggest you upgrade in the test environment first and make sure they work properly
As for the import and export function of the updated data, we plan to implement it in version 4.1
