### ISSUE TITLE
Question: Will the message denied by ACL when I publish one message throuh REST Api?

### ISSUE THREAD

**Issue by mcoder2014** [emqx/emqx#3363]
#### Environment

- OS:  Debian
- Erlang/OTP: 
- EMQ: broker 4.0.3

#### Description

I prepared to use the datebase mysql controlling the ACL of my MQTT clients. I want to `deny all` by default, and add the pub/sub auth of some topics for the needed MQTT clients. 

Sometimes, I need to send control message through REST Api, will the message be denied by my acl setting? Or the the message through the REST publish Api will publish directly? `http://10.227.20.138:8081/api/v4/mqtt/publish`

**Comment by HJianBo** [comment]
Yes, the messages through the REST publish Api will publish directly
