### ISSUE TITLE
Client subscribed/unsubscibed events.

### ISSUE THREAD

**Issue by itmay** [emqx/emqx#3365]
#### Environment

- OS: Debian
- Erlang/OTP: R20/9.0
- EMQ: 2.3.11

#### Description

*It's not a issue, but a question. Is it possible to get events about client subscribed / unsubscribed over MQTT? Similar to $SYS topic and connected/disconnected? I can use web hook plugin, but I'm looking for posibility to use only MQTT.*

**Comment by HJianBo** [comment]
Nope. It is not possible to get sub/unsub events from the `$SYS` system messages. The web-hook is the only way to get those events.

**Comment by HJianBo** [comment]
Close it first. If you want it. You can open a Feature-Request to ours. And Describe your scenario for why are you need it.

Thanks
