### ISSUE TITLE
What is the max length of username and password  to make the connection?

### ISSUE THREAD

**Issue by mcoder2014** [emqx/emqx#3366]
#### Environment

- OS: Linux
- Erlang/OTP: 22 
- EMQ: 4.0.3 broker

#### Description

In some projects, they use a few strings to combine a longer string as `username`, such as the method [Aliyun](https://help.aliyun.com/document_detail/73742.html) used. They make `deviceName+"&"+productKey` as username, `sign_hmac(deviceSecret,content)` as password. In our application, the combined string maybe a little long, more than 100 bits. 

Is there any limitation about the `username` and `password` ? If I use the emqx_auth_http to do the ACL work, is there any limitation length?

**Comment by HJianBo** [comment]
Nope. There is not any limitation in emqx.

In the MQTT protocol spec, the allowed max length of username or password is `65535`
