### ISSUE TITLE
HTTP request error

### ISSUE THREAD

**Issue by EchoXBR** [emqx/emqx#3367]
#### Environment

OS: CentOS 7.6 64位
Erlang/OTP: R22/10.5
EMQ: 4.0.5

#### Description

what's the reason for the error in emqx.log
- 

- 2020-04-03 13:39:52.375 [error] 113.235.120.45:37078 [WebHook] HTTP request error: {failed_connect,
                                  [{to_address,{"127.0.0.1",8080}},
                                   {inet,[inet],econnrefused}]}
2020-04-03 13:39:52.377 [error] <<"86375804159751">>@113.235.120.45:37078 [WebHook] HTTP request error: {failed_connect,
                                  [{to_address,{"127.0.0.1",8080}},
                                   {inet,[inet],econnrefused}]}
2020-04-03 13:39:52.378 [error] <<"86375804159751">>@113.235.120.45:37078 [WebHook] HTTP request error: {failed_connect,
                                  [{to_address,{"127.0.0.1",8080}},
                                   {inet,[inet],econnrefused}]}

**Comment by HJianBo** [comment]
That log means that the `web-hook` can't send the event to the backend.

Please make sure the `127.0.0.1 :8080` address is reachable

**Comment by EchoXBR** [comment]
ok thanks
