### ISSUE TITLE
Need to enable subscribe only for wss and pubsub for mqtt using emqx.conf

### ISSUE THREAD

**Issue by Jeyanthinath** [emqx/emqx#3369]
How to enable acl in such a way , the wss users can only subscribe to certain topics, but pubsub for mqtt/ssl , using `emqx.conf` ?

I see the configuration 

```
listener.wss.external.access.1 = allow all
``` 
but its not supporting something like 
```
listener.wss.external.access.1 = allow all subscribe
                                           (or)
listener.wss.external.access.1 = allow all subscribe ["#"]
```

**Comment by tigercl** [comment]
@Jeyanthinath You can see the relevant configuration in `etc/acl.conf` like:
```
{allow, {ipaddr, "127.0.0.1"}, pubsub, ["$SYS/#", "#"]}.
```

**Comment by Jeyanthinath** [comment]
@tigercl thanks for the reply, 

will this configuration work on `emqx.conf`?
```
listener.wss.external.access.1 = {allow, all, subscribe, ["#"]}.
```
its throwing error for me!

From what I understand the above row will `allow only the localhost to pubsub on all topics (on both websocket and mqtt ports [1883, 8883, 8083, 8084])`. Also the acl.conf will be applied to all the connections (mqtt, mqtts, ws & wss) if I am not wrong.

But I want to `block only publish (not subscribe)` only for "web-socket secure" port `8084` 

**My use case:**
* allow mqtts to connect to emqx using self signed cert for both pubsub  -> (working)
* block all the publish on wss (subscribe should be allowed) from browser -> (I need help)

**Comment by tigercl** [comment]
@Jeyanthinath Sorry you cannot use it this way, this configuration item can only be set to the following format:
```
allow/deny all/<CIDR>
```
