### ISSUE TITLE
Unexpected sock_closed error

### ISSUE THREAD

**Issue by EchoXBR** [emqx/emqx#3370]
#### Environment

- OS: CentOS 7
- Erlang/OTP: 10.5
- EMQ: 4.0.5

#### Description

I update from 3.2.2 to 4.0.5 for my online environment,but I found a logs of error log like this

```
[error] <<"86375804026983">>@121.207.223.212:1153 [Channel] Unexpected sock_closed: einval

```
Is there something wrong with the configuration?

**Comment by tigercl** [comment]
@EchoXBR This error will not affect the using, but we will confirm and fix it as soon as possible.

**Comment by EchoXBR** [comment]
But in my android client,there are many connectionLost log like this
```
connectionLost已断开连接 (32109) - java.io.EOFException
	at org.eclipse.paho.client.mqttv3.internal.CommsReceiver.run(CommsReceiver.java:190)
	at java.lang.Thread.run(Thread.java:764)
Caused by: java.io.EOFException
	at java.io.DataInputStream.readByte(DataInputStream.java:270)
	at org.eclipse.paho.client.mqttv3.internal.wire.MqttInputStream.readMqttWireMessage(MqttInputStream.java:92)
	at org.eclipse.paho.client.mqttv3.internal.CommsReceiver.run(CommsReceiver.java:137)
	... 1 more
```

**Comment by tigercl** [comment]
@EchoXBR The log `Unexpected sock_closed: ...` will only appear after the connection has been disconnected. Please confirm the reason for disconnection.

**Comment by qiufujian** [comment]
Hello, I have a question with emqx 4.0.0. I also receive lots of logs like above in my online environment. What conditions will cause the connection to be disconnected?

**Comment by tigercl** [comment]
@qiufujian Sorry for late reply. It is recommended that you create a separate issue to discuss it, thanks.

**Comment by dengyumin** [comment]
> 

请问你最后是如何解决该问题的呀？

**Comment by Fyee** [comment]
@EchoXBR 请问你解决了吗？遇到了同样的问题
