### ISSUE TITLE
ERROR：“0xc000007”

### ISSUE THREAD

**Issue by zy19970** [emqx/emqx#3373]
#### Environment

- OS: Win server2016
- Erlang/OTP: 
- EMQ: 4.0.5

#### Description
run “./bin/emqx start”
ERROR：“0xc000007”

**Comment by zhanghongtong** [comment]
Please provide more information

**Comment by zhanghongtong** [comment]
This issue has not been updated for a long time. I will close it. If you have any questions, you can open it at any time
