### ISSUE TITLE
publish fail when message size > 1M

### ISSUE THREAD

**Issue by PearceDuan** [emqx/emqx#3375]
#### Environment

- OS: `Linux pearce 4.15.0-91-generic #92~16.04.1-Ubuntu SMP Fri Feb 28 14:57:22 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`
- Erlang/OTP:  `OTP22`
- EMQ: v4.0.0

#### Description

After change the default config(./_build/emqx/rel/emqx/etc/emqx.conf) `mqtt.max_packet_size` from 1M to 10MB, I still got an error when publish message size > 1M

LOG INFO:  

- server side
  no error log
- client side got an error
`pub error:  write tcp 192.168.113.61:57460->192.168.130.63:1883: write: connection reset by peer`

**Comment by HJianBo** [comment]
Hi @PearceDuan I can't reproduce this problem after modified the `mqtt.max_packet_size ` to `10MB`

I think this error is reported by the Client? If emqx determines that the message size exceeds the limit, it will print the following log:
```
(emqx@127.0.0.1)1> 2020-04-10 09:11:55.244 [error] <<"mosq-gMJMdbvzt9MpqGB4yy">>@127.0.0.1:51701 [MQTT]
Parse failed for frame_too_large
[{emqx_frame,parse_remaining_len,5,
             [{file,"/Users/denghaigui/Desktop/work/git/4.0_dev/v4.0.5/emqx-rel/_checkouts/emqx/src/emqx_frame.erl"},
              {line,132}]},
```


So, Plz check it again or provide more details to help me reproduce it

**Comment by PearceDuan** [comment]
@HJianBo just to verify the `mqtt.max_packet_size` param have an effect, I test a scenario below:

Change mqtt.max_packet_size enough samll(mqtt.max_packet_size=1KB), than try to publish a message (size between 1K-2K)
* Expect result: publish fail 
* Real result: publish success

seems the params mqtt.max_packet_size take no effect? 
if I miss something?
thanks for your reply

**Comment by HJianBo** [comment]
Maybe you can try exec `emqx_zone:mqtt_frame_options(external).`

If it print a different value with previous, Plz check `zone.external.max_packet_size` option

**Comment by PearceDuan** [comment]
@HJianBo 
I make a stupid mistake!
change the config and run it in local env , but test-client connect with another env
now I will close this issue.
Thanks!
