### ISSUE TITLE
State machine <0.14065.4548> terminating

### ISSUE THREAD

**Issue by blue-aurora** [emqx/emqx#3377]
#### Environment

- OS: cat /etc/redhat-release
- Erlang/OTP: erts-10.3
- EMQ: emqx 3.2.7

#### Description
# etc/emqx.conf
broker.shared_subscription_strategy = random
#issue
Our emqx cluster consists of 3 nodes, each server has 16 core CPU and 32G memory. I use the shared subscription model and use the Eclipse Paho client to subscribe to mqtt messages. But the subscription service often loses connection with emqx borker. View erlang.log and found the following error.
#erlang.log.1
2020-xx-xx 00:03:29.528 [error] <<"xxxxx">>@xxxx:54260 ** State machine <0.14065.4548> terminating
2020-xx-xx 00:07:36.587 [error] <<"xxx">>@xxxx:54428 ** State machine <0.22089.4558> terminating

**Comment by HJianBo** [comment]
Hi @blue-aurora This log can not figure out the reason for connection loses

Could you give me more details logs? or email the log directory to me?

**Comment by blue-aurora** [comment]
hi @HJianBo  this is  details logs 。
2020-04-10 13:18:52.626 [error] <<"xxxxxxxxxxxx">>@xx.xx.xx.3:33954 ** State machine <0.29000.4512> terminating
** Last event = {info,
                    {deliver,
                        [{publish,56677,
                             {message,
                                 <<0,5,162,232,222,128,115,132,178,153,81,18,
                                   69,26,0,19>>,
                                 1,<<"clientxxxxxxxxxxxxxxxx">>,
                                 #{dup => false,retain => false},
                                 #{allow_publish => true,
                                   peername => {{xx,xx,xx,120},63744},
                                   proto_ver => 4,
                                   username => <<"clientxxxxxxxxxxxxxxxx">>},
                                 <<"xxx/pinü">>,<<>>,
                                 {1586,495932,625797}}}]}}
** When server state  = {connected,
                            {state,esockd_transport,#Port<0.15724552>, 
                                {{xx,xx,xx,3},33954},
                                undefined,running,1000,
                                {pstate,external,
                                    #Fun<emqx_channel.1.118122990>,
                                    {{xx,xx,xx,157},1883},
                                    {{xx,xx,xx,3},33954},
                                    nossl,4,<<"MQTT">>,
                                    <<"xxxxxxxxxxxx">>,false,
                                    <0.29000.4512>,undefined,undefined,
                                    <<"xxxxxxxxxxxx">>,<0.22928.4698>,
                                    true,#{},undefined,undefined,80,false,
                                    #{msg => 0,pkt => 318816},
                                    #{msg => 318817,pkt => 318819},
                                    true,
                                    {1586,494789,626240},
                                    #{from_client => 0,to_client => 0},
                                    emqx_channel,
                                    #{anonymous => false,
                                      auth_result => success,
                                      client_id => <<"xxxxxxxxxxxx">>,
                                      is_superuser => false,
                                      mountpoint => undefined,
                                      peername => {{xx,xx,xx,3},33954},
                                      sockname => {{xx,xx,xx,157},1883},
                                      username => <<"xxxxxxxxxxxx">>,
                                      ws_cookie => undefined,zone => external},
                                    undefined},
                                {none,#{max_size => 3145728,version => 4}},
                                {emqx_gc,
                                    #{cnt => {80000,20627},
                                      oct => {314572800,312454926}}},
                                {keepalive,#Fun<emqx_channel.4.118122990>,
                                    1272321,60,
                                    {keepalive,check},
                                    #Ref<0.2496915134.3570663425.60499>,0},
                                undefined,undefined,undefined,true,
                                #Ref<0.2496915134.2577661954.7887>,600000}}
** Reason for termination = error:badarg
** Callback mode = [state_functions,state_enter]
** Stacktrace =
**  [{erlang,byte_size,[{error,<<"xxx/pin">>,<<"ü">>}],[]},
     {emqx_frame,serialize_utf8_string,1,
                 [{file,"/emqx_temp/emqx_rel/_checkouts/emqx/src/emqx_frame.erl"},
                  {line,636}]},
     {emqx_frame,serialize_variable,2,
                 [{file,"/emqx_temp/emqx_rel/_checkouts/emqx/src/emqx_frame.erl"},
                  {line,458}]},
     {emqx_frame,serialize,2,
                 [{file,"/emqx_temp/emqx_rel/_checkouts/emqx/src/emqx_frame.erl"},
                  {line,396}]},
     {emqx_channel,'-do_init/3-fun-0-',4,
                   [{file,"/emqx_temp/emqx_rel/_checkouts/emqx/src/emqx_channel.erl"},
                    {line,169}]},
     {emqx_protocol,send,2,
                    [{file,"/emqx_temp/emqx_rel/_checkouts/emqx/src/emqx_protocol.erl"},
                     {line,708}]},
     {emqx_protocol,deliver,2,
                    [{file,"/emqx_temp/emqx_rel/_checkouts/emqx/src/emqx_protocol.erl"},
                     {line,610}]},
     {emqx_channel,connected,3,
                   [{file,"/emqx_temp/emqx_rel/_checkouts/emqx/src/emqx_channel.erl"},
                    {line,245}]}]

**Comment by HJianBo** [comment]
The message's topic must be a UTF8 string instead of  `"xxx/pinü"`

**Comment by blue-aurora** [comment]
Does emqx.conf have configuration items to filter non-UTF8 encoded topics?

**Comment by HJianBo** [comment]
Sorry. Not yet
