### ISSUE TITLE
EQMX not started as a service

### ISSUE THREAD

**Issue by krab22** [emqx/emqx#3378]
#### Environment

- OS: Fedora 31
- Erlang/OTP: Eshell V10.5
- EMQ: EMQX

#### Description

EMQX does not start as a service. It starts successfully from the console.
` LOGGING STARTED Wed Apr  8 13:12:55 +05 2020
Exec: /usr/lib/emqx/erts-10.5/bin/erlexec -boot /usr/lib/emqx/releases/v4.0.5/emqx -mode embedded -boot_var ERTS_LIB_DIR /usr/lib/emqx/erts-10.5/../lib -mnesia dir "/var/lib/emqx/mnesia/emqx@127.0.0.1" -config /var/lib/emqx/configs/app.2020.04.08.13.12.56.config -args_file /var/lib/emqx/configs/vm.2020.04.08.13.12.56.args -vm_args /var/lib/emqx/configs/vm.2020.04.08.13.12.56.args -start_epmd false -epmd_module ekka_epmd -proto_dist ekka -- console
Root: /usr/lib/emqx
/usr/lib/emqx
Starting emqx on node emqx@127.0.0.1
Start http:management listener on 8081 successfully.
Start http:dashboard listener on 18083 successfully.
Start mqtt:tcp listener on 0.0.0.0:11883 successfully.
Start mqtt:tcp listener on 0.0.0.0:1883 successfully.
Start mqtt:ssl listener on 0.0.0.0:8883 successfully.
EMQ X Broker 4.0.5 is running now!
Eshell V10.5  (abort with ^G)
(emqx@127.0.0.1)1> Stop mqtt:tcp listener on 0.0.0.0:11883 successfully.
(emqx@127.0.0.1)1> Stop mqtt:tcp listener on 0.0.0.0:1883 successfully.
(emqx@127.0.0.1)1> Stop mqtt:ssl listener on 0.0.0.0:8883 successfully.
(emqx@127.0.0.1)1> [os_mon] memory supervisor port (memsup): Erlang has closed
[os_mon] cpu supervisor port (cpu_sup): Erlang has closed
`
What could be the problem?

**Comment by zhanghongtong** [comment]
Hi, @krab22 
We have not released the Fedora 31 installation package, did you compile it yourself?

**Comment by krab22** [comment]
Installed the package for CentOS

**Comment by krab22** [comment]
Everything got up fine - in any case dnf did not swear

**Comment by zhanghongtong** [comment]
Hi, @krab22 apologies for the delay
Does this problem still exist?

**Comment by 2p4b** [comment]
Was this issue solved?

**Comment by Rory-Z** [comment]
@2p4b This issue has been inactive for a long time. If you have any questions, please create a new issue.
