### ISSUE TITLE
Generic server disksup terminating

### ISSUE THREAD

**Issue by gm19900510** [emqx/emqx#3379]
#### Environment

- OS: ubuntu 18.04
- Erlang/OTP: Erlang/OTP 21
- EMQ: V3.2.7

#### Description

2020-04-11 04:06:03.588 [error] ** Generic server disksup terminating 
** Last message in was timeout
** When Server state == [{data,[{"OS",{unix,linux}},
                                {"Timeout",1800000},
                                {"Threshold",80},
                                {"DiskData",
                                 [{"/",37206272,25},
                                  {"/dev",65536,0}, 
                                  {"/sys/fs/cgroup",7617916,0},
                                  {"/etc/localtime",37206272,25},
                                  {"/dev/shm",65536,0},
                                  {"/sys/firmware",7617916,0}]}]}]
** Reason for termination == 
** {badarg,[{erlang,port_close,[#Port<0.9>],[]},
            {disksup,terminate,2,[{file,"disksup.erl"},{line,169}]},
            {gen_server,try_terminate,3,[{file,"gen_server.erl"},{line,673}]},
            {gen_server,terminate,10,[{file,"gen_server.erl"},{line,858}]},
            {proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,249}]}]}

2020-04-11 04:06:03.629 [error] ** Generic server disksup terminating 
** Last message in was timeout
** When Server state == [{data,[{"OS",{unix,linux}},
                                {"Timeout",1800000},
                                {"Threshold",80},
                                {"DiskData",[]}]}]
** Reason for termination == 
** {badarg,[{erlang,port_close,[#Port<0.58528>],[]},
            {disksup,terminate,2,[{file,"disksup.erl"},{line,169}]},
            {gen_server,try_terminate,3,[{file,"gen_server.erl"},{line,673}]},
            {gen_server,terminate,10,[{file,"gen_server.erl"},{line,858}]},
            {proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,249}]}]}

2020-04-11 04:06:03.633 [error] ** Generic server disksup terminating 
** Last message in was timeout
** When Server state == [{data,[{"OS",{unix,linux}},
                                {"Timeout",1800000},
                                {"Threshold",80},
                                {"DiskData",[]}]}]
** Reason for termination == 
** {badarg,[{erlang,port_close,[#Port<0.58529>],[]},
            {disksup,terminate,2,[{file,"disksup.erl"},{line,169}]},
            {gen_server,try_terminate,3,[{file,"gen_server.erl"},{line,673}]},
            {gen_server,terminate,10,[{file,"gen_server.erl"},{line,858}]},
            {proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,249}]}]}

2020-04-11 04:06:03.638 [error] ** Generic server disksup terminating 
** Last message in was timeout
** When Server state == [{data,[{"OS",{unix,linux}},
                                {"Timeout",1800000},
                                {"Threshold",80},
                                {"DiskData",[]}]}]
** Reason for termination == 
** {badarg,[{erlang,port_close,[#Port<0.58530>],[]},
            {disksup,terminate,2,[{file,"disksup.erl"},{line,169}]},
            {gen_server,try_terminate,3,[{file,"gen_server.erl"},{line,673}]},
            {gen_server,terminate,10,[{file,"gen_server.erl"},{line,858}]},
            {proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,249}]}]}

2020-04-11 04:06:03.642 [error] ** Generic server disksup terminating 
** Last message in was timeout
** When Server state == [{data,[{"OS",{unix,linux}},
                                {"Timeout",1800000},
                                {"Threshold",80},
                                {"DiskData",[]}]}]
** Reason for termination == 
** {badarg,[{erlang,port_close,[#Port<0.58531>],[]},
            {disksup,terminate,2,[{file,"disksup.erl"},{line,169}]},
            {gen_server,try_terminate,3,[{file,"gen_server.erl"},{line,673}]},
            {gen_server,terminate,10,[{file,"gen_server.erl"},{line,858}]},
            {proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,249}]}]}

[os_mon] memory supervisor port (memsup): Erlang has closed
[os_mon] cpu supervisor port (cpu_sup): Erlang has closed
2020-04-11 04:06:03.677 [error] <<"paho38944260136811">>@192.168.104.234:51869 [Channel] Session <0.3663.3> termiated: killed
2020-04-11 04:06:03.677 [error] <<"paho38944378296979">>@192.168.104.234:51886 [Channel] Session <0.3496.3> termiated: killed
2020-04-11 04:06:03.677 [error] <<"mqttjs_4cd53b4e">>@192.168.42.179:51836 [WS Channel] Session <0.3584.0> termiated: killed
2020-04-11 04:06:03.678 [error] <<"mqttjs_b43471f6">>@192.168.42.13:58949 [WS Channel] Session <0.2459.0> termiated: killed
2020-04-11 04:06:03.678 [error] <<"mqttjs_20129fad">>@192.168.42.179:51855 [WS Channel] Session <0.3727.0> termiated: killed
2020-04-11 04:06:03.692 [error] <<"mqttjs_68875f54">>@192.168.42.13:58930 [WS Channel] Session <0.2232.0> termiated: killed
Stop mqtt:ws listener on 0.0.0.0:8083 successfully.
Stop mqtt:ssl listener on 0.0.0.0:8883 successfully.
Stop mqtt:wss listener on 0.0.0.0:8084 successfully.
{"Kernel pid terminated",application_controller,"{application_terminated,os_mon,shutdown}"}

Kernel pid terminated (application_controller) ({application_terminated,os_mon,shutdown})

Crash dump is being written to: /var/log/emqx/crash.dump...done

**Comment by HJianBo** [comment]
I guess it should have some problems in your disk at that moment?
