### ISSUE TITLE
The connection does not exist in the Linux system and cannot be kicked out

### ISSUE THREAD

**Issue by mopybird** [emqx/emqx#3380]
#### Environment

- OS: Linux iZbp1dvbubas8h7zjrrr2eZ 4.4.0-139-generic #165-Ubuntu SMP Wed Oct 24 10:58:50 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
- Erlang/OTP: 
- EMQ: 2.3.11

#### Description

*A description of the issue*
终端无法连接上mqtt服务器，查询终端，发现连接：
Client(866289032709737, clean_sess=true, username=xxxx, peername=39.144.14.106:63464, connected_at=1586276269)

但是这个连接使用netstat或者lsof都查不到：
netstat -ano | grep "39.144.14.106:63464"

kick该连接报异常
Reason:{noproc,{gen_server2,call,[<10186.3004.1154>,kick]}}, get_stacktrace:[{gen_server2,
                                                                              call,
                                                                              2,
                                                                              [{file,
                                                                                "src/gen_server2.erl"},
                                                                               {line,
                                                                                332}]},
                                                                             {emqttd_ctl,
                                                                              run,
                                                                              1,
                                                                              [{file,
                                                                                "src/emqttd_ctl.erl"},
                                                                               {line,
                                                                                83}]},
                                                                             {rpc,
                                                                              '-handle_call_call/6-fun-0-',
                                                                              5,
                                                                              [{file,
                                                                                "rpc.erl"},
                                                                               {line,
                                                                                197}]}]
RPC to emq1883@127.0.0.1 error: {noproc,
                                 {gen_server2,call,[<10186.3004.1154>,kick]}}

我该怎么把这个连接释放掉，重启就算了，生产环境，没法重启。

**Comment by HJianBo** [comment]
In general, The process doesn't take any side effect on other clients if the client connection has down. Don't worry it will cause any bad effects.


I think you should use the APIs/CLs to kick it or just ignore it.

If you really need to delete it directly, You can take some of the more dangerous operation, that you can attach to the emqx services and execute `emqttd_cm:unreg(<<"866289032709737">>).`

**Comment by mopybird** [comment]
没办法不理它，终端连不上来。
使用cli我试过，杀不掉，报异常。
其他方式应该怎么做，有没有详细点的指南？

**Comment by HJianBo** [comment]
Can you dig out the reason for the client connecting error?

---

You can:
1. `./bin/emqttd attach`
2.  Typing`emqttd_cm:unreg(<<"866289032709737">>).`  and `ENTER` to delete client sessions.
3. Typing `CTRL+D`

I don't ensure that ut can work normally, you should first test in other environments

**Comment by mopybird** [comment]
还没有。终端设备在用户那里，已经让用户寄回来了。


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"JianBo He"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月12日(星期天) 上午10:10
收件人:&nbsp;"emqx/emqx"<emqx@noreply.github.com&gt;;
抄送:&nbsp;"哈哈儿"<32899523@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [emqx/emqx] 连接在linux系统不存在，无法kick掉。 (#3380)





 
Can you dig out the reason for the client connecting error?
 
 
You can:
  
./bin/emqttd attach
 
Typingemqttd_cm:unreg(<<"866289032709737"&gt;&gt;).  and ENTER to delete client sessions.
 
Typing CTRL+D
  
I don't ensure that ut can work normally, you should first test in other environments

**Comment by HJianBo** [comment]
Hi, @mopybird Any updates for there?

**Comment by HJianBo** [comment]
Close it first. If you have any updates, plz reopen it  ;-)
