### ISSUE TITLE
child_terminated mqtt bridge

### ISSUE THREAD

**Issue by beraybentesen** [emqx/emqx#3384]
Version 4.0.5. Same config on different VM works well. 

Manually joined to cluster, node name changed to emqx@publicIP

Trying to connect to RabbitMQ. 

In addition to error, the following forwarding also not working : 

=+,$SYS/brokers/emqx@127.0.0.1/clients/+/connected,$SYS/brokers/emqx@127.0.0.1/clients/+/disco$

Full error : 

2020-04-12 05:13:25.055 [error]     supervisor: {local,emqx_bridge_mqtt_sup}
    errorContext: child_terminated
    reason: {timeout,{gen_server,call,[<0.1576.0>,{subscribe,<<"+">>}]}}
    offender: [{pid,<0.2859.0>},
               {id,aws},
               {mfargs,
                   {emqx_bridge_worker,start_link,
                       [aws,
                        [{address,"35.246.220.71:1883"},
                         {batch_size,32},
                         {bridge_mode,false},
                         {clean_start,false},
                         {clientid,"bridge_frankfurt"},
                         {connect_module,emqx_bridge_mqtt},
                         {forward_mountpoint,"bridge/aws/${node}/"},
                         {forwards,
                             ["+",
                              "$SYS/brokers/emqx@127.0.0.1/clients/+/connected",
                              "$SYS/brokers/emqx@127.0.0.1/clients/+/disconnected"]},
                         {keepalive,60},
                         {max_inflight_size,32},
                         {password,"RAjRy29hsokk"},
                         {proto_ver,v4},
                         {queue,
                             #{max_total_size => 5368709120,
                               replayq_dir => "/var/lib/emqx/emqx_aws_bridge/",
                               replayq_seg_bytes => 10485760}},
                         {reconnect_delay_ms,5000},
                         {retry_interval,5000},
                         {ssl,false},
                         {ssl_opts,[{versions,[tlsv1,'tlsv1.1','tlsv1.2']}]},
                         {start_type,auto},
                         {subscriptions,[]},
                         {username,"user"}]]}},
               {restart_type,permanent},
               {shutdown,5000},
               {child_type,worker}]

**Comment by beraybentesen** [comment]
I can confirm that issue exist after clustering. (Both kubernetes and manually)

Any idea what might cause this ?

**Comment by turtleDeng** [comment]
Sorry, did not reply to you in time
You use K8S automatic clustering, the MQTT used is bridged to rabbitmq, is the clientid of each node connected to rabbitmq the same?

**Comment by turtleDeng** [comment]
Thanks for your feedback, we will close this issue, if there is any, you can reopen it.
