### ISSUE TITLE
Unable to remove Retained message

### ISSUE THREAD

**Issue by rajenpal033** [emqx/emqx#3388]
I have few retained messages, which I want to delete completely. I tried using the method mentioned in some of the blogs as, send empty message to the same topic. So I sent blank('') as well as null message using retained = true | false  and qos = 0 | 1 | 2. The messages were sent successfully as I was able to receive that blank message from another client. Restarted the emqx service. But the previous retained message still remains. So, I was wondering, what am I missing?
FYI : I have latest version of emqx.

Regards.

**Comment by tigercl** [comment]
You can use the [trace command](https://docs.emqx.io/broker/latest/en/commands.html#trace) to trace the client and topic, it will usually give you some help.

**Comment by rajenpal033** [comment]
After I restarted the server itself, the problem seems to be gone.
