### ISSUE TITLE
Bridge Forwarding Problem

### ISSUE THREAD

**Issue by beraybentesen** [emqx/emqx#3389]
6 manually clustered nodes are connected to the RabbitMQ. Each forwards same message.

After disconnecting clients, rabbitmq still receives same data. Tried purging rabbitmq, recreated queue etc. I see 0 connected client but still receiving the messages. 

Any idea ?

**Comment by turtleDeng** [comment]
Do you forward emqx messages to rabbitmq or rabbitmq messages to emqx?
Is there any client connection, or is the acceptance message emqx or rabbitmq?

**Comment by berayb** [comment]
Forwarding emqx messages to the RabbitMQ. No client connection on each node. I had to restart each node to fix this problem but it was a production killer issue.

**Comment by turtleDeng** [comment]
Are you saying that the emqx node does not see the connection?

**Comment by turtleDeng** [comment]
Thanks for your feedback, we will close this issue, if there is any, you can reopen it.
