### ISSUE TITLE
select is_superuser cause lock table

### ISSUE THREAD

**Issue by eshxcmhk** [emqx/emqx#3390]
#### Environment

- OS: CentOS 7
- Erlang/OTP: 21.3
- EMQ: 4.0.5

#### Description

*A description of the issue*
```auth.pgsql.super_query = select is_superuser from users.users where username = '%u' limit 1```会导致锁表，在修改表结构时无法成功

**Comment by tigercl** [comment]
@eshxcmhk We have not found any problems yet, can you provide more detailed description?

**Comment by eshxcmhk** [comment]
> @eshxcmhk We have not found any problems yet, can you provide more detailed description?

After exec the sql of ```alter table users.users add "aaa" int4;``` , there is no response.
Exec ```select state, query, wait_event_type, wait_event, * from pg_stat_activity where state='active'```, Result：
```
active	select is_superuser from users.users where username = $1 limit 1		
active	select is_superuser from users.users where username = $1 limit 1		
active	select is_superuser from users.users where username = $1 limit 1		
active	select state, query, wait_event_type, wait_event, * from pg_stat_activity where state='active'		
active	alter table users.users add "aaa" int4	Lock	relation
```

**Comment by zgldh** [comment]
Yes the emqx_auth_pgsql locks tables but never release.
Maybe due to this issue, this plugin does not do auth work.
![image](https://user-images.githubusercontent.com/312404/114306601-d9272200-9b0e-11eb-9a9f-10c9e68387b6.png)

**Comment by zmstone** [comment]
How many rows do you have in the table ?

**Comment by zmstone** [comment]
and which postgres version ?

**Comment by zgldh** [comment]
PostgreSQL 11
EMQX 4.2.7

There are only 10 rows in mqtt_user table.

**Comment by zmstone** [comment]
Hi @zgldh do you have very heavy auth load?
what's the pool size ` auth.pgsql.pool` (default 8).
could you send the table description? in `psql` command line tool: `\d+ users.users`

For reference:

I tested with concurrent 40 processes running
`select is_superuser from mqtt_user where username = $1 limit 1`
in a busy loop on 20 connections towards postgres.

If I put `alter table mqtt_user add column aaa int4;` between `begin;` and `commit;`
then I am able to see the queries pending on the DDL transaction to complete:

```
 state  |                                            query                                             | wait_event_type | wait_event
--------+----------------------------------------------------------------------------------------------+-----------------+------------
 active | select is_superuser from mqtt_user where username = $1 limit 1                               | Lock            | relation
 active | select state, query, wait_event_type, wait_event from pg_stat_activity where state='active'; |                 |
 active | select is_superuser from mqtt_user where username = $1 limit 1                               | Lock            | relation
 active | select is_superuser from mqtt_user where username = $1 limit 1                               | Lock            | relation
 ....
```
but they were able to resume right after the `commit;`.
