### ISSUE TITLE
Makefile:57: erlang.mk: No such file or directory make: *** No rule to make target 'erlang.mk'.  Stop.

### ISSUE THREAD

**Issue by K-945** [emqx/emqx#3399]
**What happened**:
您好，我在使用emq3.0.1源码编译时候出现了这个问题，使用了make命令后，不能正常编译
**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:

- EMQ X version (e.g. `emqx_ctl status`): 

- Hardware configuration (e.g. `lscpu`):
- OS (e.g. `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Erlang/OTP version : 
- Others:

**Comment by qingchuwudi** [comment]
There is a command in the **Makefile**:
```bash
$(shell [ -f erlang.mk ] || curl -s -o erlang.mk https://raw.githubusercontent.com/emqx/erlmk/master/erlang.mk)
include erlang.mk
```

The file `erlang.mk` will be downloaded when you execute the command of `make`. 
And make sure your network can visit the website of `https://raw.githubusercontent.com/emqx/erlmk/master/erlang.mk`.

**Comment by HJianBo** [comment]
@Mr007Z Any updates for there?
