### ISSUE TITLE
Questions about using emqx_bridge_kafka

### ISSUE THREAD

**Issue by K-945** [emqx/emqx#3400]
**Please describe your problem in detail, if necessary, you can upload the log file through the attachment**:
hey,friend!
![image](https://user-images.githubusercontent.com/48827771/79692537-4efc0300-8298-11ea-87bc-4fc26b287416.png)

I use the mqtt client to send messages, but Kafka consumes different messages.
![image](https://user-images.githubusercontent.com/48827771/79692546-5b805b80-8298-11ea-9e23-b5d9ce2a667d.png)

**Comment by turtleDeng** [comment]
```
## kafka payload type
## Option:  base64 | plain
## bridge.kafka.encode_payload_type = plain
```
The default production payload is base64, you can configure it to be plain

**Comment by turtleDeng** [comment]
Thank you for your participation, we talk about closing this issue.
