### ISSUE TITLE
The deleted user can still connect to server.

### ISSUE THREAD

**Issue by CYJason2000** [emqx/emqx#3401]
**What happened**: The deleted user can still connect to server.

**What you expected to happen**: The deleted user can‘t connect to server.

**How to reproduce it (as minimally and precisely as possible)**: 1. Create a user "user1" in /etc/emqx/plugins/emqx_auth_username.conf, and enable it like the document says. 2. Change the username and password to "user2", then enable it as the same way of "user1". 3. "user1" can still connect to the server! Even so after restarting emqx and the auth_username plugin.

**Anything else we need to know?**:  Reboot, emqx restart and restart plugin don't help.

**Environment**:

- EMQ X version (e.g. `emqx_ctl status`): 4.0.5

- Hardware configuration (e.g. `lscpu`): Intel(R) Xeon(R) Platinum 8163 CPU @ 2.50GHz
- OS (e.g. `cat /etc/os-release`):"Ubuntu 18.04.4 LTS"
- Kernel (e.g. `uname -a`):4.15.0-96-generic #97-Ubuntu
- Erlang/OTP version : 
- Others:

**Comment by tigercl** [comment]
@CYJason2000 The authentication information in the configuration file will be written to the database when the plugin starts, so "user1" is not deleted.

**Comment by CYJason2000** [comment]
Thanks. So the API is the only way to delete a user.
