### ISSUE TITLE
The server received the message and did not reply

### ISSUE THREAD

**Issue by Breeze-Wu** [emqx/emqx#3403]
**Environment**
OS: Windows
EMQ: 2.2

**Description**
Test the sending and receiving stability of mqttpub within 12 hours. Send 5 bytes of packets every 5 seconds. During the verification process, there is no puback on the server, which will appear about 4 hours later. The maximum waiting time is 60s

**Comment by tigercl** [comment]
@Breeze-Wu It is recommended to use a newer version likes [v3.2.7](https://www.emqx.io/downloads#broker) or [v4.0.5](https://www.emqx.io/downloads#broker).
