### ISSUE TITLE
ENOTCONN Error

### ISSUE THREAD

**Issue by kozelok** [emqx/emqx#3405]
**Environment**:

- EMQ X version (e.g. `emqx_ctl status`): 4.0.5
- Hardware configuration (e.g. `lscpu`): 8/30GB ram
- OS (e.g. `cat /etc/os-release`): Docker Image(Provided by emqx team)
- Kernel (e.g. `uname -a`): (Provided by emqx team)- Others:

**What happened and what you expected to happen**: There not to be any disconnects.

**How to reproduce it (as minimally and precisely as possible)**:
100k Publishers sending 8KB messages for a combined throughput of 20K/s.
18 Local shared queue subscribers(Same queue)
At 10K 8kb messages, there is no issue. At 20k, emqx starts throwing **enotconn** errors.
**Anything else we need to know?**: 
The clients are using paho Golang library. There are no errors reported by the client.

**Comment by kozelok** [comment]
Attaching config.
[emqx.conf.zip](https://github.com/emqx/emqx/files/4512645/emqx.conf.zip)

**Comment by tigercl** [comment]
@kozelok Can you provide emqx.log when the error occurs?

**Comment by qingchuwudi** [comment]
**ENOTCONN** is most likely there are problems on you client.

Reference: [What causes the ENOTCONN error?](https://stackoverflow.com/a/17052699)

**Comment by turtleDeng** [comment]
Thanks for your feedback, please provide emqx related LOG first.
Your error may be caused by emqx memory protection. In detail, you can solve it by modifying the configuration https://docs.emqx.io/broker/latest/en/configuration/configuration.html#zoneexternalforceshutdownpolicy

**Comment by kozelok** [comment]
Hello,

Than you for your help, we figured out the issue!
