### ISSUE TITLE
vm.args needs to have a -name parameter.

### ISSUE THREAD

**Issue by SanjayChakrapani** [emqx/emqx#3408]
I recently installed EMQx for my mqtt project, for a week everything was working but suddenly this error came up 

root@DESKTOP-HB0CBLN:~# emqx start
vm.args needs to have a -name parameter.
  -sname is not supported.

no matter what I did this was not going, I didn't modify any files before. So I simply uninstalled and reinstalled back, then it was working fine for a day after the same problem began.

I am using WSL on Windows10 (Ubuntu 18.04 )
I did all update and upgrade, there is nothing but EMQX app in this WSL.
I am new to Ubuntu so I don't know what this means.

Please help me if anyone knows
Thank you

**Comment by zhanghongtong** [comment]
Hi @SanjayChakrapani 
EMQ X installation path must not contain any Spaces, please check your installation path

**Comment by chenxushuo** [comment]
But i used emqx/emqx:v3.1.2 on docker,almost get this error!

**Comment by chenxushuo** [comment]
I fix it， disk used over 100%。。。
