### ISSUE TITLE
reload certificates

### ISSUE THREAD

**Issue by daenney** [emqx/emqx#3414]
I found #1111 which added support for reloading certificates. But what I can't figure out is how to use it. `emqx_ctl` doesn't seem to have a `listener restart` option, only stop.

How do I go about actually restarting a listener, for when a TLS certificate is updated?

**Comment by tigercl** [comment]
@daenney For some reasons, we removed this feature, but we are planning to support it again.

**Comment by joltmode** [comment]
@tigercl this hassn't been closed for quite some time now - any ETA's? Or maybe it's in already?

**Comment by daenney** [comment]
I'd still like to see this feature.

**Comment by zmstone** [comment]
If you are to change the paths of the certificate files for `keyfile`, `certfile`, `cacertfile`, then listener restart is required.
Otherwise OTP has a pem cache which is refreshed every 2 minutes.

**Comment by daenney** [comment]
Are you sure? My config doesn't change, but when I filed the issue it definitely didn't reload anything. I tried both symlinking and copying the files last time, but neither seemed to work.

**Comment by zmstone** [comment]
> Are you sure? My config doesn't change, but when I filed the issue it definitely didn't reload anything. I tried both symlinking and copying the files last time, but neither seemed to work.

I’m pretty sure about `cacertfile`.
Not entirely sure about `keyfile` and `cerfile` as I myself have not tested it before.
I’ll run some tests.

**Comment by zmstone** [comment]
I just did some tests with EMQ X 4.3.11 in docker.
the steps are:

## generate test certs
I use a collection of openssl commands for testing

* clone `https://github.com/zmstone/tls-scripts` 
* execute `./generate-certgs.sh`
* `cd <datetime-dir>` wehre `<datetime-dir>` is where the cert files are generated to 
* `ls` should list these files `ca.pem      client.key  client.pem  server.key  server.pem`

we'll use the `server.key` and `server.pem` pair to start EMQ X
and then replace `client.key` and `client.pem` pair to test auto pem reload.

## start EMQ X using `server.key` and `server.pem`

* Start EMQ X in docker container: `docker run --rm -it --network host --name emqx -v /path/to/generated/certs:/certs emqx/emqx:4.3.11 bash`, starting from now, below commands are executed inside the container.
* Make a copy of the `/certs/` dir and change owner to `emqx`: 
```
sudo cp -r /certs/ /opt/emqx/etc/certs2
sudo chown -R emqx:emqx /opt/emqx/etc/certs2
```
* configure EMQ X to read from `certs2`
```
export EMQX_listener__ssl__external__keyfile="etc/certs2/server.key"
export EMQX_listener__ssl__external__certfile="etc/certs2/server.pem"
emqx start
```

## Test pem refresh on the fly
* `openssl s_client -showcerts -connect localhost:8883 </dev/null`
should print out 
```
Server certificate
subject=C = SE, ST = Stockholm, O = MyOrgName, OU = MyService, CN = localhost
```
* Overwrite `server.*` with `client.*`
```
/opt/emqx/etc/certs2/
mv client.key server.key
mv client.pem server.pem
```
* wait for a while
* inspect again which certs are sent by the server `openssl s_client -showcerts -connect localhost:8883 </dev/null`
should print the new cert as (note that `OU` is changed to `MyServiceClient`):
`subject=C = SE, ST = Stockholm, L = Stockholm, O = MyOrgName, OU = MyServiceClient, CN = localhost`
