### ISSUE TITLE
How to close log trace

### ISSUE THREAD

**Issue by BaiMaGod** [emqx/emqx#3415]
日志追踪打开后，如何关闭？

**Comment by tigercl** [comment]
@BaiMaGod You can use the following commands:
```
./emqx_ctl trace stop client <ClientId>
./emqx_ctl trace stop topic <Topic>
```

**Comment by BaiMaGod** [comment]
> @BaiMaGod您可以使用以下命令：
> 
> ```
> ./emqx_ctl trace stop client <ClientId>
> ./emqx_ctl trace stop topic <Topic>
> ```

谢谢
