### ISSUE TITLE
How to clear trace log?

### ISSUE THREAD

**Issue by BaiMaGod** [emqx/emqx#3416]
The log file for the log trace output is too large.
The log file size did not change after the log was cleared with the echo "" > topic.log command,
And before the log file appears a lot of '@' symbol, the log file downloads to the Windows system to open, the file shows a lot of space symbol.
How do I clean the log file correctly?

**Comment by tigercl** [comment]
@BaiMaGod You can delete it directly.

**Comment by BaiMaGod** [comment]
可是删除之后，并没有新的日志文件生成。
我新建了一个同名文件，也没有新的topic消息输出到该日志文件。

**Comment by terry-xiaoyu** [comment]
emqx_ctl trace stop  topic  <Topic>

Docs can be found here: https://docs.emqx.io/broker/latest/cn/advanced/cli.html#trace-命令

**Comment by BaiMaGod** [comment]
@terry-xiaoyu  你意思是如果我要清空跟踪日志文件，就需要先停止跟踪，把原日志文件删除，再开启日志追踪？

**Comment by terry-xiaoyu** [comment]
@BaiMaGod That's right. And we may add some more configurations for tracing in the future, such as max size of a single file, or log file rotation. But you could always do that by 3rd party log rotation tools such as [logrotate](https://linux.die.net/man/8/logrotate).

BTW, we only accept **English issues** as it would be friendly to the search engine.

**Comment by BaiMaGod** [comment]
@terry-xiaoyu  Thank you. My problem has been solved.
