### ISSUE TITLE
The Raspberry Pi 3B + board is equipped with a 16G SD card and tested with emqtt_bench. The client starts to have problems around 3000, is it normal?

### ISSUE THREAD

**Issue by kick7** [emqx/emqx#3419]
具体操作指令：./emqtt_bench conn -c 5000 -i 10
错误显示：
![1587977589(1)](https://user-images.githubusercontent.com/16188239/80353250-ab1de300-88a7-11ea-9707-cee72d260cea.png)

**Comment by tigercl** [comment]
@scard13 How about the resource usage on the Raspberry Pi?

**Comment by tigercl** [comment]
@scard13 How about the resource usage on the Raspberry Pi?

**Comment by scard13** [comment]
![1](https://user-images.githubusercontent.com/16188239/80435540-5f168100-892f-11ea-81ae-4f5833d25e6b.png)
![2](https://user-images.githubusercontent.com/16188239/80435542-6047ae00-892f-11ea-90bd-76ed2ce98100.png)
![3](https://user-images.githubusercontent.com/16188239/80435545-60e04480-892f-11ea-9ab5-d39c2b378593.png)

**Comment by scard13** [comment]
![1](https://user-images.githubusercontent.com/16188239/80435565-705f8d80-892f-11ea-898c-cb25bf8ddde1.png)
![2](https://user-images.githubusercontent.com/16188239/80435567-7190ba80-892f-11ea-829a-831711a24177.png)
![3](https://user-images.githubusercontent.com/16188239/80435570-72295100-892f-11ea-9134-44a4e3a9f857.png)

**Comment by scard13** [comment]
![1](https://user-images.githubusercontent.com/16188239/80435639-ae5cb180-892f-11ea-9fd6-ef61028e061c.png)
![2](https://user-images.githubusercontent.com/16188239/80435640-af8dde80-892f-11ea-8a27-5483882cc749.png)
![3](https://user-images.githubusercontent.com/16188239/80435643-af8dde80-892f-11ea-9e06-561e719834f8.png)

**Comment by tigercl** [comment]
@scard13 It may be the operating system limitation of Raspberry Pi, please refer to the following document to optimize: https://docs.emqx.io/broker/v3/en/tune.html.
