### ISSUE TITLE
otp version should be set must > 21.3

### ISSUE THREAD

**Issue by hchw** [emqx/emqx#3421]
i use emqx for  self project
found emqx_connection.erl
use Transport:setopts(Socket, [{active, N}])
when Transport is ssl  it will crash in otp < 21.3
so  you better replace {minimum_otp_vsn, "21.0"}.  to {minimum_otp_vsn, "21.3"}.
in rebar.config

**Comment by tigercl** [comment]
@hchw Thank you very much for your feedback, we will fix it as soon as possible.

**Comment by tigercl** [comment]
@hchw Can you provide the emqx version that you found the issue?

**Comment by tigercl** [comment]
Thanks for your feedback, we have fixed it in emqx v4.0-beta.2.
