### ISSUE TITLE
Problems with rules and APIs in the cluster

### ISSUE THREAD

**Issue by JoshRong** [emqx/emqx#3423]
**Environment**:

- EMQ X version (e.g. `emqx_ctl status`): emqx-v4.1.0-alpha.1
- Hardware configuration (e.g. `lscpu`):x86_64
- OS (e.g. `cat /etc/os-release`):Centos 7.6
- Kernel (e.g. `uname -a`):3.10.0-1062.12.1.el7.x86_64
- Erlang/OTP version (in case you build emqx from source code): 22.1
- Others:

**What happened and what you expected to happen**:
I have two servers with two public IPs.They made a static cluster with each other.When I use http api to access my public IP: XXX.XXX.XXX:8081, Internal Error is displayed on the webpage. The relevant errors reported in the log are:
This is feedback from s1.emqx.io machine：
2020-04-24 00:15:32.119 [error] GET /api/v4/clients error: {badmatch,
                            {error,
                             {badrpc,
                              {'EXIT',
                               {undef,
                                [{emqx_mgmt_api,do_query,
                                  ['emqx@s2.emqx.io',
                                   {emqx_channel_info,
                                    [{{'$1',#{},'_'},[],['$1']}],
                                    []},
                                   0,10001],
                                  []},
                                 {rpc,'-handle_call_call/6-fun-0-',5,
                                  [{file,"rpc.erl"},{line,197}]}]}}}}}, stacktrace:
[{emqx_mgmt_api,do_cluster_query,5,
This is feedback from s2emqx.io machine：
2020-04-24 00:15:32.119 [error] GET /api/v4/clients error: {badmatch,
                            {error,
                             {badrpc,
                              {'EXIT',
                               {undef,
                                [{emqx_mgmt_api,do_query,
                                  ['emqx@s1.emqx.io',
                                   {emqx_channel_info,
                                    [{{'$1',#{},'_'},[],['$1']}],
                                    []},
                                   0,10001],
                                  []},
                                 {rpc,'-handle_call_call/6-fun-0-',5,
                                  [{file,"rpc.erl"},{line,197}]}]}}}}}, stacktrace:
[{emqx_mgmt_api,do_cluster_query,5,

The above is the error in API. When I cancel the cluster, the HTTP API function becomes available.

Another question is about resource rules.When I create a resource, I can succeed. But it failed when I created the rule.

This is my execute command：
emqx_ctl rules create \
     "SELECT username as u, payload FROM \"message.publish\" where u='Steven'" \
     '[{"name":"data_to_webserver", "params": {"$resource":  "resource:ca1eec3c"}}]' \
     -d "Forward publish msgs from steven to webserver"

This is the error log：
2020-04-28 13:12:17.988 [error] cluster_call error found, ResL: [{{init_action_failure,'emqx@s1.emqx.io'},
                                  {{emqx_web_hook_actions,
                                       on_action_create_data_to_webserver},
                                   badarg}},
                                 {{init_action_failure,'emqx@s2.emqx.io'},
                                  {{emqx_web_hook_actions,
                                       on_action_create_data_to_webserver},
                                   badarg}}]

These are the two problems I found, I want to know how to solve.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Comment by HJianBo** [comment]
Have you try the latest version v4.1-beta.1. It should be fixed :)

**Comment by JoshRong** [comment]
I used the latest version and found that the problem has been solved
