### ISSUE TITLE
HTTPs Settings are not working for EMQX management plugin

### ISSUE THREAD

**Issue by mntolia** [emqx/emqx#3424]
OS: Ubuntu 18
EMQX:4.2

So I set the https settings in the emqx_management.conf file like this:
```
management.listener.https = 8081
management.listener.https.acceptors = 2
management.listener.https.max_clients = 512
management.listener.https.backlog = 512
management.listener.https.send_timeout = 15s
management.listener.https.send_timeout_close = on
management.listener.https.certfile = etc/certs/cert.pem
management.listener.https.keyfile = etc/certs/privkey.pem
management.listener.https.cacertfile = etc/certs/chain.pem
```
This is the same setting I am using for the dashboard config. It works fine in the dashboard but does not work in the the management.

When I send a GET request to https://url:8081/api/v4/, the server does not give any response. In the dashboard, it shows the listener is active.

**Comment by tigercl** [comment]
@mntolia Can you provide the `emqx.log`? It will help us analyze the problem.

**Comment by mntolia** [comment]
The log doesn't say anything about the management plugin. This is the log after I reverted to HTTPs and restarted the broker:
```
2020-05-01 20:38:20.329 [critical] [EMQ X] emqx shutdown for normal
2020-05-01 20:38:20.652 [error] cluster_call error found, ResL: [{{init_action_failure,'emqx@127.0.0.1'},
                                  {{emqx_web_hook_actions,
                                       on_action_create_data_to_webserver},
                                   badarg}}]
2020-05-01 20:38:20.653 [critical] Can not re-build rule: {init_action_failure,
                           [{{init_action_failure,'emqx@127.0.0.1'},
                             {{emqx_web_hook_actions,
                                  on_action_create_data_to_webserver},
                              badarg}}]},Fix the issue and establish it manually.
Stacktrace: [{emqx_rule_engine,cluster_call,2,
                 [{file,
                      "/emqx-rel/_build/emqx-pkg/lib/emqx_rule_engine/src/emqx_rule_engine.erl"},
                  {line,371}]},
             {lists,foreach,2,[{file,"lists.erl"},{line,1338}]},
             {emqx_rule_engine,'-refresh_rules/0-lc$^0/1-0-',1,
                 [{file,
                      "/emqx-rel/_build/emqx-pkg/lib/emqx_rule_engine/src/emqx_rule_engine.erl"},
                  {line,288}]},
             {emqx_rule_engine,refresh_rules,0,
                 [{file,
                      "/emqx-rel/_build/emqx-pkg/lib/emqx_rule_engine/src/emqx_rule_engine.erl"},
                  {line,293}]},
             {emqx_rule_engine_app,start,2,
                 [{file,
                      "/emqx-rel/_build/emqx-pkg/lib/emqx_rule_engine/src/emqx_rule_engine_app.erl"},
                  {line,33}]},
             {application_master,start_it_old,4,
                 [{file,"application_master.erl"},{line,277}]}]
```
![image](https://user-images.githubusercontent.com/10390224/80840171-5cab7400-8c1a-11ea-8da1-d7609f58528f.png)

When I send a request to the endpoint, the server does not give any response. When I revert back to HTTP I get a response.

**Comment by tigercl** [comment]
@mntolia Sorry for late reply. How did you restart emqx, Can HTTP still be accessed normally when you configure it as HTTPs? It will helps us confirm whether your configuration has been reloaded.

**Comment by mntolia** [comment]
> @mntolia Sorry for late reply. How did you restart emqx, Can HTTP still be accessed normally when you configure it as HTTPs? It will helps us confirm whether your configuration has been reloaded.

No problem. 

I restarted with `service emqx restart` command.

And No, the endpoints can't be accessed with HTTP when HTTPs is configured.
