### ISSUE TITLE
emqx edge http api 401 Unauthorized 

### ISSUE THREAD

**Issue by moluzhui** [emqx/emqx#3426]
**Please describe your problem in detail, if necessary, you can upload the log file through the attachment**:
I want to query the information using the `rest API` under the `emqx-edge:v3.2.4 docker container`.

```
docker ps

e5e01525c4e7  emqx/emqx-edge:v3.2.4  "/usr/bin/docker-ent…"   39 minutes ago  Up 39 minutes          1883/tcp, 4369/tcp, 5369/tcp, 6369/tcp, 8083-8084/tcp, 8883/tcp, 11883/tcp, 18083/tcp, 0.0.0.0:8081->8080/tcp    edge-broker
```

However, HTTP/1.1 401 Unauthorized occurs when performing the following rest API test
```
curl -v --basic -u admin:public -k http://localhost:8081/api/v3/brokers
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 8081 (#0)
* Server auth using Basic with user 'admin'
> GET /api/v3/brokers HTTP/1.1
> Host: localhost:8081
> Authorization: Basic YWRtaW46cHVibGlj
> User-Agent: curl/7.58.0
> Accept: */*
> 
< HTTP/1.1 401 Unauthorized
* Authentication problem. Ignoring this.
< WWW-Authenticate: Basic Realm="minirest-server"
< content-length: 12
< date: Wed, 29 Apr 2020 07:43:23 GMT
< server: Cowboy
< 
* Connection #0 to host localhost left intact
```

Aren't the underlying `default appid` and `appsecret` `admin` and `public`?

Am I missing some configuration?

**Comment by tigercl** [comment]
@moluzhui  emqx-edge:v3.2.4 doesn't have dashboard feature for some reason. Please switch to v3.2.6 at least.

**Comment by moluzhui** [comment]
@tigercl I don't need to use `dashboard feature `, I want to use the [REST API](https://docs.emqx.io/docs/broker/v3/cn/rest.html) to get some statistics. such as `api/v3/metrics/`.

**Comment by tigercl** [comment]
@moluzhui Sorry for late reply. I noticed that you mapped port 8081 to 8080, please check your mapping.

**Comment by zhanghongtong** [comment]
Hi, @moluzhui 
Our version 3.x does not provide the default admin user in REST API and we recommend you upgrade to 4.0.6
