### ISSUE TITLE
emqx broker 4.0.6 can not use http api ( port 8081 is already opened)

### ISSUE THREAD

**Issue by GuYang0902** [emqx/emqx#3428]
**Environment**:

- EMQ X version:EMQ X Broker v4.0.6
- Hardware configuration:Intel(R) Xeon(R) CPU E5-2680 v4 @ 2.40GHz
- OS:centos 7
- Others: install emqx with this shell:curl https://repos.emqx.io/install_emqx.sh | bash

**What happened and what you expected to happen**:
ENV
![emq_env](https://user-images.githubusercontent.com/22129002/80661794-44c0dc80-8ac2-11ea-9580-1063389736fe.png)
can not get any message
![emqissue](https://user-images.githubusercontent.com/22129002/80661699-f90e3300-8ac1-11ea-896f-f1d46bd4c0e0.png)

**Comment by turtleDeng** [comment]
Thank you for your participation, please check whether your firewall opens port 8081

**Comment by turtleDeng** [comment]
Thanks for your feedback, we will close this issue, if there is any, you can reopen it.
