### ISSUE TITLE
clienId contains characters (#+) will cause topoic reveicer Exception

### ISSUE THREAD

**Issue by kgdngitfk** [emqx/emqx#3429]
**Environment**:

- EMQ X version (e.g. `emqx_ctl status`): 
- Hardware configuration (e.g. `lscpu`):
- OS (e.g. `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Erlang/OTP version (in case you build emqx from source code): 
- Others:

**What happened and what you expected to happen**:
a clientId is "dev#OnlineStatusClient" which contains the wildcard "#", when connect is legal
but the subscriber subscribed the topoc "$SYS/brokers/+/clients/#" will receive the disconnect message from the toppic
"$SYS/brokers/emqx@127.0.0.1/clients/dev#OnlineStatusClient/disconnected"  which well cause 
mqtt client library  paho  throw Exception and developer confused, so shoud we refuse connect when the clientId contains wildcard?

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Comment by turtleDeng** [comment]
Yes, (#, +) is a keyword of the MQTT protocol. If the clientid contains (#, +), the stitched topic is an illegal MQTT topic
