### ISSUE TITLE
Can this be used on Arduino Nano?

### ISSUE THREAD

**Issue by kevin0598** [emqx/emqx#3434]
i have a project that it need me to use MQTT-SN but i want to implement it on Arduino Nano as microcontroller,so can i implemented it at Arduino nano?

and can i use Windows as my OS?

**Comment by tigercl** [comment]
@kevin0598 We don't support Arduino Nano yet, but you can deploy emqx on Windows.

**Comment by kevin0598** [comment]
Thank you for answering my question
