### ISSUE TITLE
why is undefined for session data ?

### ISSUE THREAD

**Issue by 303489429** [emqx/emqx#3435]
**Please describe your problem in detail, if necessary, you can upload the log file through the attachment**:
![image](https://user-images.githubusercontent.com/16587700/81135907-7b986600-8f8c-11ea-8190-cee4e9c0e1d1.png)
![image](https://user-images.githubusercontent.com/16587700/81135981-c0bc9800-8f8c-11ea-9692-bfcd29551c6f.png)
why is undefined ?
version:2.3.1

**Comment by turtleDeng** [comment]
Please check your session statistics configuration
```
## Enable per session statistics.
##
## Value: on | off
mqtt.session.enable_stats = on
```

**Comment by 303489429** [comment]
![image](https://user-images.githubusercontent.com/16587700/81780504-372b3e00-9529-11ea-9e4f-8732b0577aa2.png)
