### ISSUE TITLE
KeepAlive Backoff

### ISSUE THREAD

**Issue by kozelok** [emqx/emqx#3437]
Hello,

Can you please explain the setting zone.$name.keepalive_backoff?

Based on documentation the default is keep alive * 2 * .75.

So if my clients have a keep alive of 1200 seconds(20 minutes),  it sounds like the broker will "disconnect" client at 1800 seconds(30 minutes)?

If I wanted the broker to kick client out at 1230 seconds(20 minutes+30 seconds), would I set this value to .504?

Thank you

**Comment by tigercl** [comment]
@kozelok You're right, but the backoff corresponding to 1230 seconds should be 0.5125. 1200 * 0.5125 * 2 = 1230.
