### ISSUE TITLE
Shared Subscription for $SYS

### ISSUE THREAD

**Issue by kozelok** [emqx/emqx#3438]
**What would you like to be added/modified**:
Shared subscriptions to $SYS/connected or $SYS/disconnected along with "hash" routing strategy all go to 1 client. Essentially this is valid since there is only one source client, EMQx.
**Why is this needed**:
I would like to have shared subscription with hashing so that all connected/disconnected events go to a particular client in order.

**Comment by tigercl** [comment]
@kozelok You can try to use `round_robin` strategy, I think it can meet your needs.

**Comment by kozelok** [comment]
@tigercl  That is a strategy that can work, but we also want to keep the hashing strategy for other topics. If it is possible to feature request "hashed based on client" publishes to $SYS connected or $events/connected || $events/disconnected topics.

**Comment by zmstone** [comment]
you can trigger connect disconnect events from rule engine and use the republish action to send events with a particular topic, then the shared sub strategy can be configured to use hash_topic`.
here is an example;


![image](https://github.com/emqx/emqx/assets/164324/185c7ce7-f3f5-4e4c-9e57-0130e91b1057)
