### ISSUE TITLE
About flapping_clean_interval and allow_anonymous configuration items

### ISSUE THREAD

**Issue by scikstack** [emqx/emqx#3439]
这两个配置是什么意思?
在哪些情况下能用?

**Comment by scikstack** [comment]
allow_anonymous  这个知道了.但是另一个不知道

**Comment by tigercl** [comment]
@scikstack `flapping_clean_interval` configuration item is generally used in conjunction with `flapping_threshold`. Its purpose is to specify how long clients that are detected as abnormal will be banned.

**Comment by scikstack** [comment]
@tigercl 

其目的是指定被禁止检测为异常的客户端的时间.

抱歉 我英文不行, 我还是没有理解

1. 被禁止检测什么意思?
2. 客户端突然下线, 算是异常客户端吗?

**Comment by tigercl** [comment]
@scikstack For example, clients that frequently go online and offline for more than a certain number of times in a short time.

**Comment by scikstack** [comment]
@tigercl 明白了 谢谢
