### ISSUE TITLE
The features of clearing ACL cache and kicking client in v3.2.7

### ISSUE THREAD

**Issue by ghost** [emqx/emqx#3442]
**About clearing the acl cache**
I use mysql authentication. How can I remove a user's topic from the acl cache when I delete it?

**About the kick off function**
Is there a logoff feature in this version?

**Comment by scikstack** [comment]
@tigercl 我找到了 踢下线的功能, 但是我还是没找到 手动清空 acl 缓存的命令.

**Comment by scikstack** [comment]
@tigercl 我在测试中发现一个问题, 不清楚这个问题是不是正常现象.

我在 数据库中 某用户没有给他设置任何 ACL 规则. 当用户连接后, 我创建一个新的 acl 规则并允许该规则.

但是用户还是无法订阅该 topic, 要等到缓存到期后, 才能订阅成功. 

这种情况属于正常现象吗?

**Comment by scikstack** [comment]
After the account is connected, will all the ACL rules be cached? Or will it be cached when it is used?

**Comment by terry-xiaoyu** [comment]
If you are using 3.x of emqx, the only way to clear the ACL cache is to wait it expire or disconnect the client and connect it again. The TTL of ACL cache can be configured by `acl_cache_ttl` in the `emqx.conf` file, which default to 1 min.

Using emqx after 4.0.6, you could clear all the ACL caches of all of the connections by the command line tool: `emqx_ctl acl reload`.

**Comment by terry-xiaoyu** [comment]
The ACL result will only be cached after the first time it publishes/subscribes a topic. And the ACL cache would expire if:

- there's no any publish/subscribe message received from the same client after the interval defined in `acl_cache_ttl`;

- or the session of the client is removed because the client disconnected and the session has expired.

**Comment by scikstack** [comment]
> The ACL result will only be cached after the first time it publishes/subscribes a topic. And the ACL cache would expire if:
> 
> * there's no any publish/subscribe message received from the same client after the interval defined in `acl_cache_ttl`;
> * or the session of the client is removed because the client disconnected and the session has expired.

感谢您的回答, 我是否可以这样理解?

> 每个用户都有一个 acl 缓存, 被验证成功的 acl 规则都会放到这个缓存中.
> 当在 时间间隔 中又认证成功了一个 acl 规则, 则会重新设置 时间间隔为 `acl_cache_ttl` 的值.
> 如果 在此 时间间隔 期间没有做 acl 规则认证或这段时间的认证都是失败的, 等到 时间间隔 过了之后, 就会清空这个缓存.
> 而不是 每一个 acl 规则都有 一个 属于自己的  时间间隔.

是在抱歉, 因为我不会 Erlang 看不懂源码, 否则就不会问了.

我的表达能力不是很好, 看起来可能很费劲.
