### ISSUE TITLE
Using time -v to measure resource consumption 

### ISSUE THREAD

**Issue by NewBermuda** [emqx/emqx#3449]
Hi everybody! I need some help to measure the resource consumption of the EMQ X Broker.
So I'm using Apache JMeter and the MQTT Plugin to load test EMQ X.
I'd like to get the CPU and peak RAM usage using time -v.
The scenario I'm testing is having a single client connect to EMQ X and subscribe to an increasing number of topics (up to 100000 topics).
However, the results are getting dont' really make sense.
```
Protocol 'ekka': register/listen error: Command exited with non-zero status 1
	Command being timed: "timeout 90 emqx foreground"
	User time (seconds): 19.03
	System time (seconds): 1.12
	Percent of CPU this job got: 53%
	Elapsed (wall clock) time (h:mm:ss or m:ss): 0:37.65
	Average shared text size (kbytes): 0
	Average unshared data size (kbytes): 0
	Average stack size (kbytes): 0
	Average total size (kbytes): 0
	Maximum resident set size (kbytes): 107488
	Average resident set size (kbytes): 0
	Major (requiring I/O) page faults: 0
	Minor (reclaiming a frame) page faults: 80644
	Voluntary context switches: 13557
	Involuntary context switches: 69462
	Swaps: 0
	File system inputs: 0
	File system outputs: 272
	Socket messages sent: 0
	Socket messages received: 0
	Signals delivered: 0
	Page size (bytes): 4096
	Exit status: 1
```
I get basically the same result for every number of topics.
There's no change in resource consumption if it's 10 or 10000 topics.
Do you have an explanation for this? Am I doing in something when measuring the usage? 
I'm using emqx foreground so the process could be measured by time -v.
So this is the bash script I'm using to measure it: 

```
sudo time -v timeout 90 emqx foreground 2>> $local/server_results/test1/emqx_$b.txt &

# process for load testing

sleep 5
sudo timeout 90 ~/Downloads/apache-jmeter-5.2.1/bin/jmeter -n -t $local/testplans/csv.jmx -Jport=$a & : 

sleep 125 && kill %!

```

I'm guessing these are only the statistics for the start-up process?
How could I get the statistics of the broker itself during operation using time -v?
Or are memory and CPU statistics only available in the enterprise edition?

Would be thankful for any advice!

**Comment by HJianBo** [comment]
Hi @NewBermuda I can not understand these output content. 

Usually, we use the `./bin/emqx_ctl vm` to get the broker running stats
