### ISSUE TITLE
relooping of messages when bridge is enabled

### ISSUE THREAD

**Issue by saumilsdk** [emqx/emqx#3450]
I have set **ignore_loop_deliver = true** but even then messages are sent from bridge to aws iot broker even if message is coming from broker.

**Comment by tigercl** [comment]
@saumilsdk Hi. What version are you using?

**Comment by saumilsdk** [comment]
Hi @tigercl I have installed emqx recently and have latest version.
```
ubuntu@ip:~$ emqx_ctl broker
sysdescr  : EMQ X Broker
version   : 4.0.6
uptime    : 41 seconds
datetime  : 2020-05-10 15:40:17
ubuntu@ip-172-31-85-254:~$ 
```

**Comment by saqib-cielo** [comment]
Emqx as a bridge with AWS Iot broker behaving unexpectedly(getting duplicate messages burst with any Qos level), normally happen when we start publishing messages with some pace, check all config params but no luck, did anyone came across similar issue.
