### ISSUE TITLE
What may be the cause of excessive memory usage？

### ISSUE THREAD

**Issue by 303489429** [emqx/emqx#3451]
![image](https://user-images.githubusercontent.com/16587700/81462922-628bf100-91e8-11ea-97f4-eb03726b6de5.png)
![image](https://user-images.githubusercontent.com/16587700/81462935-7fc0bf80-91e8-11ea-9d5b-78abd4f61159.png)
version：2.3.1

**Comment by tigercl** [comment]
@303489429 You can check whether it is because the subscribers are not online and the messages are accumulated in the message queue, so the memory consumption of this node is abnormally high. Or you can check the detailed memory usage through `./emqx_ctl vm`.

**Comment by 303489429** [comment]
![image](https://user-images.githubusercontent.com/16587700/81467484-78f77400-920b-11ea-996b-74bec850700d.png)
![image](https://user-images.githubusercontent.com/16587700/81467494-890f5380-920b-11ea-8108-9c7b0968067b.png)
@tigercl  No data backlog .

**Comment by 303489429** [comment]
@tigercl 206 node with the same configuration have more sessions, but they are stable

**Comment by HJianBo** [comment]
I guess there is a binary leak problem maybe. It has fixed at the latest version


If the memory can't release for a long time, you can try:
1. Attach to emqttd backend console with `./bin/emqttd attach`
2. Garbage collection manually: `erlang:garbage_collect().`
3. Type `Ctrl+D` to exist the console mode
4. Check the usage again

Hope it works for you :)

**Comment by 303489429** [comment]
> I guess there is a binary leak problem. It has fixed at the latest version
> 
> If the memory can't release for a long time, you can try:
> 
> 1. Attach to emqttd backend console with `./bin/emqttd attach`
> 2. Garbage collection manually: `erlang:garbage_collect().`
> 3. Type `Ctrl+D` to exit the console mode
> 4. Check the usage again
> 
> Hope it works for you :)

**Comment by 303489429** [comment]
hi @HJianBo :
./emqttd attach
Can't access pipe directory /tmp/root_erl_pipes/emq@172.16.17.205/: No such file or directory
What's the reason ? Is there any other way ? thanks

**Comment by HJianBo** [comment]
Please ensure the `/tmp/root_erl_pipes/emq@172.16.17.205/` has existed and you can access it.

But it may be deleted by others. in that case, sorry it must restart it. That's a bug below of 3.x

**Comment by 303489429** [comment]
@HJianBo Thank you .
