### ISSUE TITLE
cannot running on ARM64 because of error:erts-10.3.4/bin/run_erl: not found

### ISSUE THREAD

**Issue by KerwinKoo** [emqx/emqx#3454]
I want to run emqx under [Kylin](http://www.kylinos.cn/) OS, but it didn't work.  
when I run command `./bin/emqx start`,  
It shows :
```
./bin/emqx: 323: ./bin/emqx: /home/test/docker_emq/emqx/erts-10.3.4/bin/run_erl: not found
```
but the file `/home/test/docker_emq/emqx/erts-10.3.4/bin/run_erl` exists in right path. And run
`file /home/test/docker_emq/emqx/erts-10.3.4/bin/run_erl` it shows:

```
/home/test/docker_emq/emqx/erts-10.3.4/bin/run_erl: 
ELF 64-bit LSB shared object, ARM aarch64, version 1 (SYSV), dynamically linked, interpreter /lib/ld-, stripped
```

This error also existed when running `./bin/emqx restart` or `./bin/emqx ping` ...

## Details

- EMQ X version (e.g. `emqx_ctl status`): 
`v3.0.1` downloaded from 3.0.1-release [emqx-docker-v3.0.1-arm64v8.zip](https://github.com/emqx/emqx/releases/download/v3.0.1/emqx-docker-v3.0.1-arm64v8.zip)

`v3.1.1` dowloaded from [emqx-edge-docker-v3.1.1-arm64v8.zip](https://github.com/emqx/emqx/releases/download/v3.1.1/emqx-edge-docker-v3.1.1-arm64v8.zip) , copy all files from docker into Kylin local host.

- Hardware configuration (e.g. `lscpu`):

```
Architecture:          aarch64
Byte Order:            Little Endian
CPU(s):                4
On-line CPU(s) list:   0-3
Thread(s) per core:    1
Core(s) per socket:    2
Socket(s):             2
Model name:            Phytium,FT2000A,4-Core
CPU max MHz:           2600.0000
CPU min MHz:           1900.0000
BogoMIPS:              3456.00
Flags:                 fp asimd evtstrm aes pmull sha1 sha2 crc32
```

- OS (e.g. `cat /etc/os-release`):

```
NAME="Kylin"
VERSION="4.0.2 (juniper)"
ID=kylin
ID_LIKE=debian
PRETTY_NAME="Kylin 4.0.2"
VERSION_ID="4.0.2"
HOME_URL="http://www.kylinos.cn/"
SUPPORT_URL="http://www.kylinos.cn/content/service/service.html"
BUG_REPORT_URL="http://www.kylinos.cn/"
UBUNTU_CODENAME=juniper
```

- Kernel (e.g. `uname -a`):

```
Linux test-FT2000 4.4.131-20191113.kylin.desktop-generic #kylin SMP Wed Nov 13 14:27:05 CST 2019 aarch64 aarch64 aarch64 GNU/Linux
```

- Others:

**How to reproduce it (as minimally and precisely as possible)**:

Perhaps need an CPU FT2000 computer?

**Anything else we need to know?**:

Please help me running emqx under Kylin ARM64, Any emqx version that newer than V3.0.0.

**Comment by HJianBo** [comment]
Hi @KerwinKoo Thanks for you feedback we will try to reproduce it :)

**Comment by zhanghongtong** [comment]
Hi, @KerwinKoo 
We are sorry that we do not have the installation package of Kylin OS, maybe you can try to compile EMQ X by yourself using the project [emqx/emqx-rel](https://github.com/emqx/emqx-rel/), or you can use our [docker images](https://hub.docker.com/r/emqx/emqx)

**Comment by zhanghongtong** [comment]
This issue has not been updated for a long time. I will close it. If you have any questions, you can open it at any time
