### ISSUE TITLE
cluster

### ISSUE THREAD

**Issue by lijian213** [emqx/emqx#3457]
etcd cluster 
 
[error] 10.10.10.183:59248 [MQTT]
Parse failed for function_clause
[{emqx_frame,parse_packet,
             [{mqtt_packet_header,5,false,0,false},
              <<79,88,89,32,84,67,80,52,32,49,49,49,46,49,50,50,46,50,54,46,49,
                51,55,32,49,55,50,46,49,55,46,48,46,57,32,57,50,57,53,32,49,56,
                56,51,13,10,16,108,0,6,77,81,73,115,100,112,3,194,0,15,0,37,48,
                95,57,48,48,49,50,53,49,49,95,121,111,121,111,95,56,51,48,50>>,
              #{max_size => 10485760,strict_mode => false,version => 4}],
             [{file,"/emqx_rel/_build/emqx/lib/emqx/src/emqx_frame.erl"},
              {line,164}]},
 {emqx_frame,parse_frame,4,
             [{file,"/emqx_rel/_build/emqx/lib/emqx/src/emqx_frame.erl"},
              {line,142}]},
 {emqx_connection,parse_incoming,3,
                  [{file,"/emqx_rel/_build/emqx/lib/emqx/src/emqx_connection.erl"},
                   {line,503}]},
 {emqx_connection,handle_msg,2,
                  [{file,"/emqx_rel/_build/emqx/lib/emqx/src/emqx_connection.erl"},
                   {line,496}]},
 {emqx_connection,process_msg,3,
                  [{file,"/emqx_rel/_build/emqx/lib/emqx/src/emqx_connection.erl"},
                   {line,284}]},
 {proc_lib,wake_up,3,[{file,"proc_lib.erl"},{line,259}]}]
Frame data:<<16,108,0,6,77,81,73,115,100,112,3,194,0,15,0,37,48,95,57,48,48,49,
             50,53,49,49,95,121,111,121,111,95,56,51,48,50,57,54,51,95,49,53,
             56,57,48,49,54,57,54,54,54,56,57,0,21,57,48,48,49,50,53,49,49,95,
             121,111,121,111,95,56,51,48,50,57,54,51,0,32,66,99,65,85,67,65,
             112,118,84,98,101,116,115,53,74,101,114,71,122,104,51,100,54,50,
             90,48,107,104,90,71,104,107>>

**Comment by tigercl** [comment]
@lijian213 This is usually caused by the wrong message you sent, and we are optimizing these log outputs to make it more readable.
