### ISSUE TITLE
Need to enable only bridge and nothing else

### ISSUE THREAD

**Issue by saumilsdk** [emqx/emqx#3460]
I wanted to run only the emqx mqtt-sn bridge which will be connecting a different MQTT broker I hosted on aws. Is it possible to disable everything else but emqx-sn and emqx-bridge plugins? 
Basically i don't want to run MQTT server.

**Comment by tigercl** [comment]
@saumilsdk You can stop plugins that you don’t need to use like `emqx_rule_engine`, but emqx broker must be running, it's the foundation of everything.

**Comment by saumilsdk** [comment]
hi @tigercl i don't need emqx broker if it is acting like a bridge. I could disable the listener on 1883 and still bridge works. Only thing i want is to stop relooping of messages when bridge mode is enabled. Whenever i send one publish to emqx on mqtt-sn port, it goes on infinite loop.

**Comment by HJianBo** [comment]
The infinite loop that may be caused by your configurations is not right. Have you resolved it ?

Or Share me your emqx_bridge_mqtt.conf

**Comment by saumilsdk** [comment]
Hi @HJianBo here is the bridge config I have. As a setup, i have emqx-sn running as gateway to receive data from IOT devices, emqx-bridge to bridge emqx-sn and aws iot broker (mqtt) to send data to cloud.

```
bridge.mqtt.emqx2.start_type = auto

bridge.mqtt.emqx2.address = a3itfXXXX.iot.us-east-1.amazonaws.com:8883

bridge.mqtt.emqx2.proto_ver = mqttv4

bridge.mqtt.emqx2.clientid = bridge_emqx2

bridge.mqtt.emqx2.clean_start = true

bridge.mqtt.emqx2.ssl = on

bridge.mqtt.emqx2.cacertfile = /etc/mqtt/certs/rootCA.pem

bridge.mqtt.emqx2.certfile = /etc/mqtt/certs/cert.crt

bridge.mqtt.emqx2.keyfile = /etc/mqtt/certs/private.key

bridge.mqtt.emqx2.ciphers = ECDHE-ECDSA-AES256-GCM-SHA384,ECDHE-RSA-AES256-GCM-SHA384

PSK-AES128-CBC-SHA,PSK-AES256-CBC-SHA,PSK-3DES-EDE-CBC-SHA,PSK-RC4-SHA

bridge.mqtt.emqx2.keepalive = 60s

bridge.mqtt.emqx2.tls_versions = tlsv1.2,tlsv1.1,tlsv1

bridge.mqtt.emqx2.forwards = #

bridge.mqtt.emqx2.subscription.1.topic = #

bridge.mqtt.emqx2.subscription.1.qos = 1

bridge.mqtt.emqx2.reconnect_interval = 30s

bridge.mqtt.emqx2.retry_interval = 20s

bridge.mqtt.emqx2.max_inflight_size = 32
```

**Comment by HJianBo** [comment]
The forwards and subscription topics configuration is wrong. Plz add a mountpoint for each 
```
bridge.mqtt.emqx2.forwards = #
bridge.mqtt.emqx2.subscription.1.topic = #
```

E.g:
```
bridge.mqtt.aws.forward_mountpoint = bridge/aws/${node}/
bridge.mqtt.aws.receive_mountpoint = receive/aws/
```

**Comment by moluzhui** [comment]
> The forwards and subscription topics configuration is wrong. Plz add a mountpoint for each
> 
> ```
> bridge.mqtt.emqx2.forwards = #
> bridge.mqtt.emqx2.subscription.1.topic = #
> ```
> 
> E.g:
> 
> ```
> bridge.mqtt.aws.forward_mountpoint = bridge/aws/${node}/
> bridge.mqtt.aws.receive_mountpoint = receive/aws/
> ```

`receive_mountpoint = receive/aws/` is it a `required parameter` for subscription.1. Topic? I remember that only forword_mounpoint is needed in `version 3`, and no receive_mountpoint exists

**Comment by HJianBo** [comment]
Nope, They are an optional parameter. It just a good practice for MQTT-Bridge

**Comment by saumilsdk** [comment]
@HJianBo even after adding mountpoint messages are looping and also mountpoint prefix getting added over and over while using emqx-sn with bridge

**Comment by saqib-cielo** [comment]
Emqx as a bridge with AWS Iot broker behaving unexpectedly(getting duplicate messages burst with any Qos level), normally happen when we start publishing messages with some pace, check all config params but no luck, did anyone came across similar issue.
