### ISSUE TITLE
MQTT version 5 - Wrong maximum Qos

### ISSUE THREAD

**Issue by gaborauth** [emqx/emqx#3461]
**Environment**:

- EMQ X version (e.g. `emqx_ctl status`): 4.0.1
- Hardware configuration (e.g. `lscpu`): Intel Core Processor (Haswell, no TSX, IBRS)
- OS (e.g. `cat /etc/os-release`): CentOS Linux 7 (Core)
- Kernel (e.g. `uname -a`):3.10.0-1062.12.1.el7.x86_64
- Erlang/OTP version (in case you build emqx from source code): 
- Others:

**What happened and what you expected to happen**:

I'm trying to connect to the EMQX with HiveMQ Java client with MQTT5 protocol but the EMQX sends back wrong maximum Qos:

```Exception while decoding CONNACK: wrong maximum Qos```

I've checked the CONNACK response, and the maximum Qos is 2, which is not allowed here.

I've found a closed issue about this problem: https://github.com/emqx/emqx/issues/1848

Is there any workaround? Maybe the bug sneaked back? Or it is a HiveMQ client bug?

**How to reproduce it (as minimally and precisely as possible)**:

Try to connect with HiveMQ client.

**Anything else we need to know?**:

**Comment by tigercl** [comment]
@gaborauth Thanks for your feedback, we have fixed it in [v4.0.5](https://github.com/emqx/emqx/releases/tag/v4.0.5).

**Comment by gaborauth** [comment]
> @gaborauth Thanks for your feedback, we have fixed it in [v4.0.5](https://github.com/emqx/emqx/releases/tag/v4.0.5).

Oh... I tried to find an issue about the problem... :)

Thank you! I will update! :)

**Comment by anaconda875** [comment]
Hi @tigercl, unfortunately I got the same issue when trying to connect to emq x version 4.3 that running on docker.
