### ISSUE TITLE
I saw /api/v4/users in the HTTP interface, and the actual external request is indeed 404

### ISSUE THREAD

**Issue by Y-A-K-E** [emqx/emqx#3463]
在EMQ控制台

直接点HTTP接口 **/api/v4/users/**
是能成功返回数据的.

> 请求地址 : /api/v4/users/
> 响应数据 :
> [
>     {
>         "username": "admin",
>         "tags": "administrator"
>     },
>     {
>         "username": "test",
>         "tags": "viewer"
>     }
> ]

----------
1,我删除EMQ默认的应用
2,新建一个应用.
3,用php curl .启用basic认证. 并用新app的appID /密钥.  请求 **/api/v4/** 是有结果的.
4,同一测试环境,只是修改url请求为get  **/api/v4/clients** 也是有结果的(虽然结果是空)
5,依然是同一环境,只是修改了url请求为 get   **/api/v4/users/**  页面却返回 404 .

6,直接浏览器访问 **/api/v4/users/**  ,使用app的appID /密钥 登陆.也是返回404

请问我是哪里设置的问题么?还是我应该启用什么插件?

**Comment by tigercl** [comment]
@Y-A-K-E Sorry for the inconvenience that the information on the dashboard has not been updated in time. Please refer to the [official website document](https://docs.emqx.io/broker/latest/en/advanced/http-api.html#endpoint-brokers).
