### ISSUE TITLE
emqx could not find the network path in win7 when execute ./emqx start

### ISSUE THREAD

**Issue by honglei** [emqx/emqx#3464]
E:\PythonLibs\FileTransferServicce\Code\tools\emqx>\\bin\\emqx start
找不到网络路径。

E:\PythonLibs\FileTransferServicce\Code\tools\emqx>ipconfig

Windows IP 配置

无线局域网适配器 无线网络连接 10:

   媒体状态  . . . . . . . . . . . . : 媒体已断开
   连接特定的 DNS 后缀 . . . . . . . :

无线局域网适配器 无线网络连接 9:

   媒体状态  . . . . . . . . . . . . : 媒体已断开
   连接特定的 DNS 后缀 . . . . . . . :

无线局域网适配器 无线网络连接 8:

   连接特定的 DNS 后缀 . . . . . . . :
   IPv6 地址 . . . . . . . . . . . . : 240e:b0:8c:ed28:90af:f51b:cc8e:9c4b
   临时 IPv6 地址. . . . . . . . . . : 240e:b0:8c:ed28:5db5:e68d:6ddd:91e8
   本地链接 IPv6 地址. . . . . . . . : fe80::90af:f51b:cc8e:9c4b%36
   IPv4 地址 . . . . . . . . . . . . : 192.168.43.248
   子网掩码  . . . . . . . . . . . . : 255.255.255.0
   默认网关. . . . . . . . . . . . . : fe80::76d2:1dff:fe63:39f8%36
                                       192.168.43.1

以太网适配器 本地连接 4:

   连接特定的 DNS 后缀 . . . . . . . :
   本地链接 IPv6 地址. . . . . . . . : fe80::b59f:2120:ee90:6290%27
   IPv4 地址 . . . . . . . . . . . . : 10.1.0.79
   子网掩码  . . . . . . . . . . . . : 255.255.255.0
   IPv4 地址 . . . . . . . . . . . . : 10.2.0.76
   子网掩码  . . . . . . . . . . . . : 255.255.255.0
   IPv4 地址 . . . . . . . . . . . . : 10.4.0.191
   子网掩码  . . . . . . . . . . . . : 255.255.0.0
   IPv4 地址 . . . . . . . . . . . . : 10.5.0.191
   子网掩码  . . . . . . . . . . . . : 255.255.255.0
   IPv4 地址 . . . . . . . . . . . . : 10.65.39.191
   子网掩码  . . . . . . . . . . . . : 255.255.255.0
   IPv4 地址 . . . . . . . . . . . . : 10.65.49.191
   子网掩码  . . . . . . . . . . . . : 255.255.255.0
   IPv4 地址 . . . . . . . . . . . . : 10.65.101.5
   子网掩码  . . . . . . . . . . . . : 255.255.255.0
   IPv4 地址 . . . . . . . . . . . . : 172.20.0.239
   子网掩码  . . . . . . . . . . . . : 255.255.0.0
   IPv4 地址 . . . . . . . . . . . . : 172.20.1.239
   子网掩码  . . . . . . . . . . . . : 255.255.255.0
   IPv4 地址 . . . . . . . . . . . . : 192.164.3.191
   子网掩码  . . . . . . . . . . . . : 255.255.255.0
   IPv4 地址 . . . . . . . . . . . . : 192.168.2.199
   子网掩码  . . . . . . . . . . . . : 255.255.0.0
   IPv4 地址 . . . . . . . . . . . . : 192.168.11.199
   子网掩码  . . . . . . . . . . . . : 255.255.0.0
   IPv4 地址 . . . . . . . . . . . . : 192.168.90.233
   子网掩码  . . . . . . . . . . . . : 255.255.255.0
   IPv4 地址 . . . . . . . . . . . . : 192.168.99.233
   子网掩码  . . . . . . . . . . . . : 255.255.255.0
   IPv4 地址 . . . . . . . . . . . . : 192.168.253.109
   子网掩码  . . . . . . . . . . . . : 255.255.255.0
   默认网关. . . . . . . . . . . . . : 192.168.99.1

以太网适配器 VirtualBox Host-Only Network:

   连接特定的 DNS 后缀 . . . . . . . :
   本地链接 IPv6 地址. . . . . . . . : fe80::e059:880a:bced:d1c4%31
   IPv4 地址 . . . . . . . . . . . . : 192.168.56.1
   子网掩码  . . . . . . . . . . . . : 255.255.255.0
   默认网关. . . . . . . . . . . . . :

以太网适配器 VMware Network Adapter VMnet8:

   连接特定的 DNS 后缀 . . . . . . . :
   本地链接 IPv6 地址. . . . . . . . : fe80::cce3:a61e:4786:ec1e%35
   IPv4 地址 . . . . . . . . . . . . : 192.168.158.1
   子网掩码  . . . . . . . . . . . . : 255.255.255.0
   默认网关. . . . . . . . . . . . . :

隧道适配器 isatap.{C1125C16-7731-4C20-ACC2-BF0F422DB162}:

   媒体状态  . . . . . . . . . . . . : 媒体已断开
   连接特定的 DNS 后缀 . . . . . . . :

隧道适配器 isatap.{30069D6D-932E-4D28-ACF4-F6179E9BF91B}:

   媒体状态  . . . . . . . . . . . . : 媒体已断开
   连接特定的 DNS 后缀 . . . . . . . :

隧道适配器 Teredo Tunneling Pseudo-Interface:

   媒体状态  . . . . . . . . . . . . : 媒体已断开
   连接特定的 DNS 后缀 . . . . . . . :

隧道适配器 isatap.{3DDE20E4-CC51-4669-BA55-2514BA22332E}:

   媒体状态  . . . . . . . . . . . . : 媒体已断开
   连接特定的 DNS 后缀 . . . . . . . :

隧道适配器 isatap.{D53AFE43-90EB-4854-9874-0A88486D6F5D}:

   媒体状态  . . . . . . . . . . . . : 媒体已断开
   连接特定的 DNS 后缀 . . . . . . . :

隧道适配器 isatap.{04C3D3D6-EDF4-40AA-9F58-F9AD7715B11D}:

   媒体状态  . . . . . . . . . . . . : 媒体已断开
   连接特定的 DNS 后缀 . . . . . . . :

隧道适配器 isatap.{C63B06FD-4CD1-40B9-A716-14FC731093FD}:

   媒体状态  . . . . . . . . . . . . : 媒体已断开
   连接特定的 DNS 后缀 . . . . . . . :

**Environment**:

- EMQ X version (e.g. `emqx_ctl status`): emqx-windows-v4.0.7.zip
- Hardware configuration (e.g. `lscpu`):Win7 x64
- OS (e.g. `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Erlang/OTP version (in case you build emqx from source code): 
- Others:

**Comment by zhanghongtong** [comment]
Hi, @honglei 
We are sorry that we do not currently support multi-network card environments on Windows. We suggest you try it on Linux

**Comment by honglei** [comment]
@zhanghongtong  Can I explicitly  assgin  a network-card to emqx under Windows?

**Comment by zhanghongtong** [comment]
@honglei Sorry, I don't know much about Windows. I don't know what to do

**Comment by honglei** [comment]
@zhanghongtong Can I config emqx to listen on certain IP addr so as to bypass this problem?

**Comment by zhanghongtong** [comment]
You can try to modify our listener, something like `listener.tcp.external`, but I'm not sure if it will work

**Comment by zhanghongtong** [comment]
This issue has not been updated for a long time. I will close it. If you have any questions, you can open it at any time
