### ISSUE TITLE
join cluster fail

### ISSUE THREAD

**Issue by yspyhp** [emqx/emqx#3466]
Failed to deploy the cluster manually, please help to check
node1 macOS
![image](https://user-images.githubusercontent.com/23613386/82043928-02f97e00-96df-11ea-93b3-4e2971ee3433.png)
node2 windows
![image](https://user-images.githubusercontent.com/23613386/82044971-dfcfce00-96e0-11ea-904e-60ac515bb4de.png)

cookie
![image](https://user-images.githubusercontent.com/23613386/82044319-b6627280-96df-11ea-9923-f5735994aeea.png)

fail message
![image](https://user-images.githubusercontent.com/23613386/82044869-b747d400-96e0-11ea-9c52-2af1d38ab94c.png)

Network situation
node1 ping node2
![image](https://user-images.githubusercontent.com/23613386/82045144-2de4d180-96e1-11ea-82b3-1b09cb2a254b.png)
node2 ping node1
![image](https://user-images.githubusercontent.com/23613386/82045264-5ff63380-96e1-11ea-8e80-8a17b0029ad0.png)

Please have a look. Thank you！

**Comment by tigercl** [comment]
@yspyhp Whether node 1 and node 2 have the same cookie?

**Comment by tigercl** [comment]
@yspyhp Whether node 1 and node 2 have the same cookie?

**Comment by yspyhp** [comment]
是的，他们是相同的cookie

**Comment by tigercl** [comment]
@yspyhp Can you provide configuration files (`emqx.conf`) on two nodes?

**Comment by yspyhp** [comment]
[node1.zip](https://github.com/emqx/emqx/files/4642830/node1.zip)
[node2.zip](https://github.com/emqx/emqx/files/4642844/node2.zip)

**Comment by xiamo0** [comment]
i have same question,who solved it? help me.thanks!

**Comment by marutha** [comment]
Could that be anything related to firewall? epmd port is opened in both the nodes?

**Comment by spring2maz** [comment]
Hi @yspyhp 
This is likely due to firewall blocking on the clustering ports.
depending on your configuration, you may need to open port 4369, 4370 and 5369 to each other.
ref: https://github.com/emqx/emqx/issues/3592#issuecomment-661987546

**Comment by spring2maz** [comment]
Closing this issue. please reopen if it it's something else.
