### ISSUE TITLE
long_schedule warning

### ISSUE THREAD

**Issue by morestart** [emqx/emqx#3469]
**Environment**:

- EMQ X version (e.g. `emqx_ctl status`): 4.0.6
- Hardware configuration (e.g. `lscpu`):
- OS (e.g. `cat /etc/os-release`): Ubuntu1804
- Kernel (e.g. `uname -a`):
Linux ubuntu 5.3.0-51-generic #44~18.04.2-Ubuntu SMP Thu Apr 23 14:27:18 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
- Erlang/OTP version (in case you build emqx from source code): 
- Others:

**What happened and what you expected to happen**:
[warning] [SYSMON] long_schedule warning: pid = <0.5840.9>, info: [{timeout,3695},
                                                {in,undefined},
                                                {out,{proc_lib,exit_p,3}}]
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Comment by tigercl** [comment]
@morestart This warning indicates that a process has been running for too much time, which means that the real-time performance of the entire system is being affected. Usually it will recover by itself, but if it continues to appear, then you need to pay attention to whether the CPU usage is too high.
