### ISSUE TITLE
how to upgrade EMQ via docker without losing configs?

### ISSUE THREAD

**Issue by zhongjiewu** [emqx/emqx#3470]
How can I upgrade EMQ docker's version without losing my configs such as the admin password?

**Comment by zhanghongtong** [comment]
Hi, @zhongjiewu 
If it's a 4.0. X upgraded to 4.1.X, unfortunately, we don't have a smooth upgrade plan at the moment :(

**Comment by zhongjiewu** [comment]
Even upgrading 4.1-beta.2 to 4.1-rc.1 is not possible for me easily. I only mounted the data folder but it still won't start. Is this expected?
Also, i found it difficult to locate log about main program (not in the console). I think it will be better if the docker entrypoint tails the main program's log rather than showing the `emqx console`.

**Comment by zhanghongtong** [comment]
Upgrading 4.1-beta.2 to 4.1-rc.1 should be very easy, please share the error you started to facilitate our troubleshooting

**Comment by zhanghongtong** [comment]
> Also, i found it difficult to locate log about main program (not in the console). I think it will be better if the docker entrypoint tails the main program's log rather than showing the emqx console.

I don’t understand, our log files are stored in the `/opt/emqx/log` directory

**Comment by zhanghongtong** [comment]
This issue has not been updated for a long time. I will close it. If you have any questions, you can open it at any time
