### ISSUE TITLE
The server received the message and did not reply

### ISSUE THREAD

**Issue by Breeze-Wu** [emqx/emqx#3471]
Environment
OS: Windows
EMQ: 4.0.5

Description
Test the sending and receiving stability of mqttpub within 12 hours. Send 5 bytes of packets every 5 seconds. During the verification process, there is no puback on the server, which will appear about 4 hours later. The maximum waiting time is 60s

question:
1.The ability of the server to process pub messages per minute

**Comment by tigercl** [comment]
@Breeze-Wu It's impossible normally. I suggest you capture network packages to determine where the problem is.
