### ISSUE TITLE
Posting message by message publishing API (/api/v4/mqtt/publish)  cannot receive `message.acked` feedback

### ISSUE THREAD

**Issue by Sniper001** [emqx/emqx#3472]
问题描述： 调用消息发布接口(/api/v4/mqtt/publish)向broker发布消息，client端可以正常收到消息，并且可以正常监听到message.publish和message.delivered事件，但是收不到message.acked事件；
然后使用paho mqtt sdk去给broker发布消息，消息可以正常收到，message.publish、message.delivered、message.acked三个事件也可以正常监听到；
请问这两种方式发布消息时emqx broker处理有啥区别呢，还是说有其他需要配置的地方，谢谢！

**Comment by tigercl** [comment]
@Sniper001 To trigger this event, EMQ X Broker needs to receive the MQTT Publish message, but `/api/v4/publish` API directly enters the sending process.
