### ISSUE TITLE
Multiple emqx nodes are deployed on a single server

### ISSUE THREAD

**Issue by ChinaChenjinlin** [emqx/emqx#3473]
#### Environment
on the centos7, 

#### Description
I  start 3 node services on one server, by modifying the port, I succeed; Group them together a cluster;
However, the subscribed message could not be received. Port 4396 has not been changed;
Did it cause it?

**Comment by HJianBo** [comment]
Hi @ChinaChenjinlin  Could you show me the `./bin/emqx_ctl cluster status` result for each node?

**Comment by HJianBo** [comment]
In the current version, Only 2 nodes are allowed to start on a single machine

**Comment by ChinaChenjinlin** [comment]
OK, I just got 2 nodes on one machine;  It's nodes A and B; starting success, and  group a cluster, on the dashboard, I can see the two nodes, but I publish the message on node A; then subscriber the message on the node B; but nothing on the node B. The problem is the same as the problem with the three nodes,

**Comment by ChinaChenjinlin** [comment]
![图片](https://user-images.githubusercontent.com/44959543/82514266-e4b0d980-9b47-11ea-8139-c27eba4e0ccb.png)

**Comment by ChinaChenjinlin** [comment]
another problem, at the nodes A and B cluster, if I publish the message on the A; and connect the A node useing a client, the client received messages will be repeated,  repeate one; if three nodes; repeate two.

**Comment by HJianBo** [comment]
Could you share with me the node  A and B's emqx.conf?

**Comment by ChinaChenjinlin** [comment]
OK, The A node remains configured; I modified the B node configuration as follows

first file is etc/emqx.conf
modified  rpc.tcp_server_port = 5369 is 5469
modified  rpc.tcp_client_port = 5369 is 5469
modified  node.dist_listen_min = 6369 is 7369
modified  node.dist_listen_max = 6369  is 7369
modified  listener.tcp.external = 0.0.0.0:1883 is 1983
modified  listener.tcp.internal = 127.0.0.1:11883 is 11983
modified  listener.ssl.external = 8883 is 8983
modified  listener.ws.external = 8083 is 8183
modified  listener.wss.external = 8084 is 8184

second file is etc/plugins/emqx_dashboard.conf
modified  dashboard.listen.http = 18083 is 18183

Third file is etc/plugins/emqx_management.conf
modified  management.listen.http = 8080 is 8180

**Comment by HJianBo** [comment]
Which emqx version? I'll try it

**Comment by ChinaChenjinlin** [comment]
V3.1.2

**Comment by ChinaChenjinlin** [comment]
cluster is manual

**Comment by HJianBo** [comment]
Something error  in rpc confs
In node A it should be:
```
rpc.tcp_server_port = 5369
rpc.tcp_client_port = 5469
```

Node B:
```
rpc.tcp_server_port = 5469
rpc.tcp_client_port = 5369
```

They should be symmetrical

**Comment by HJianBo** [comment]
We may enhance these confs later

**Comment by HJianBo** [comment]
Hi guys, we have fixed it in the https://github.com/emqx/emqx/pull/3696. 

After v4.2-rc.2, you can set the gen_rpc discovery strategy to `stateless` to support the deployment of multiple emqx nodes on a signle machine.
