### ISSUE TITLE
Batch Kick and Shutdown

### ISSUE THREAD

**Issue by kozelok** [emqx/emqx#3482]
**What would you like to be added/modified**:
1. An api for batch kicking clients from a single server(Not cluster).
2. Batch Ban Api that allows you to specify a list of devices to ban in one go.
3. Shutdown via emqxctl to gracefully kick clients over 30seconds-1 minutes while declining new connections. 
**Why is this needed**:
1&2. This would be an optimization when you need to kick a large number of devices off at once.
3. There is currently no way to gracefully shutdown a server. When you are holding a large number of connection(500K), it causes unnecessary high load on all servers during a rolling update/restart.

**Comment by id** [comment]
Must be fixed now @tigercl @wivwiv ?

**Comment by zmstone** [comment]
see `/clients/kickout/bulk`
![image](https://github.com/emqx/emqx/assets/164324/0f54f950-abfb-4da9-b6ac-7e8602595ae5)

**Comment by zmstone** [comment]
doc: http://localhost:18083/api-docs/index.html#/Clients/post_clients_kickout_bulk

**Comment by zmstone** [comment]
To the described kick & graceful shutdown, it looks like something the node rebalance and node evacuation feature can meet.
See more here:
https://docs.emqx.com/en/enterprise/latest/deploy/cluster/rebalancing.html#node-evacuation-and-cluster-load-rebalancing
