### ISSUE TITLE
Unexpected cpu usage rate (80%+) at a rather low load [emqx v4.0.*]

### ISSUE THREAD

**Issue by gsngsngsn** [emqx/emqx#3484]
**Please describe your problem in detail, if necessary, you can upload the log file through the attachment**:

**version**: emqx v4.0.7 (v4+)
**env**: k8s clustered 5 pod with 6cpu & 20G
current **load**: 0.5M connection, 1M session as average, 300packets/sec 

**Problem**: CPU usage will soon raise to 80+% at at rather normal load. 
And I finally got a scenario might be helpful to pin point the problem.

**Scene**
1 of the 5 nodes are running at a rather low cpu usage (30%+) for couple days and then shoot up to match the others (80%).

![painInTheAss](https://user-images.githubusercontent.com/3394919/82803906-ea921c00-9eb3-11ea-8900-a52fb66d634b.png)
the blue line above, is running @ 30% load for days, which is what it used to be before upgrading to v4.0*.

- when a pod has low cpu usage:
cpu reduction
[high_cpu_pod.txt](https://github.com/emqx/emqx/files/4676985/high_cpu_pod.txt)
[low_cpu_pod_low.txt](https://github.com/emqx/emqx/files/4676986/low_cpu_pod_low.txt)
metrics:
[metrics_low.txt](https://github.com/emqx/emqx/files/4676989/metrics_low.txt)

- after that pod's cpu usage pumped up:
cpu reduction: 
[low_cpu_pod_hight.txt](https://github.com/emqx/emqx/files/4676994/low_cpu_pod_hight.txt)
metrics:
[metrics_high.txt](https://github.com/emqx/emqx/files/4676997/metrics_high.txt)

----

The have similar amount of clients & sessions and Messages **Sent**, however their counts on message **publish**  && related are different:
~40% more messages.publish count from the high cpu load pod. 

And there is more.... by counting the current rate of msgs metrics, the low cpu% pod has higher counts in everything....

![strange3](https://user-images.githubusercontent.com/3394919/82810387-f1735b80-9ec0-11ea-936e-97a4d493cf1a.jpg)
The circled instance is the pod with lower cpu load. Even if the stupid k8s mapped the instance name wrong, there are still 2 instance with low throughput but only 1 instance has low cpu load.

----

Any guess?

**Comment by gsngsngsn** [comment]
ok, interesting turn around.. 

Today we have a different scene which 1 pod has high cpu consumption while the others remains at a low %.
[cpu_low_qcxn2.log](https://github.com/emqx/emqx/files/4680208/cpu_low_qcxn2.log)
[cpu_high_5m219.txt](https://github.com/emqx/emqx/files/4680209/cpu_high_5m219.txt)

![webwxgetmsgimg (2)](https://user-images.githubusercontent.com/3394919/82866841-42845d80-9f5c-11ea-886c-9e584c926f46.jpeg)
![webwxgetmsgimg (1)](https://user-images.githubusercontent.com/3394919/82866842-43b58a80-9f5c-11ea-8124-5656513435e4.jpeg)
![webwxgetmsgimg](https://user-images.githubusercontent.com/3394919/82866843-444e2100-9f5c-11ea-8af3-278caac0ced4.jpeg)

**Comment by zmstone** [comment]
Hi @gsngsngsn 

Sorry for the long silence.

In general, unbalanced cpu load typically means unbalanced connection rate/count among the cluster members,

There might be some interesting correlation to find in the metrics if you collect EMQ X Prometheus metrics.

EMQ X 4.0 is out of the maintenance window.
We’d recommend an upgrade to 4.3.
