### ISSUE TITLE
Deployed on window10, the path contains spaces to start abnormally

### ISSUE THREAD

**Issue by violetmoon027** [emqx/emqx#3485]
The path of the windows system installation contains spaces, and the path will be split at startup.
For example: C:\iot edge\emqx
Tip: 此时不应该有\iot
**Environment**:

- EMQ X version :  V4.1-rcc.2
- OS : Window10 Professional

same bugs for :
https://github.com/emqx/emqx/issues/1487

**Comment by tigercl** [comment]
@violetmoon027 Sorry, we do not support paths with spaces yet.

**Comment by violetmoon027** [comment]
I studied the script, If you want to solve the space problem, it should be solved by setting quotes to the path variable,  But I am not sure if the path contains spaces will cause other exceptions.
Especially some problems hidden inside the program.

**Comment by zhanghongtong** [comment]
Hi, @violetmoon027 
We tried to solve this problem before, but it didn't work out, maybe you can contribute to us PR, you can get the code to start the script in the [emqx/emqx-rel](https://github.com/emqx/emqx-rel/)

**Comment by ancienter** [comment]
I have the same problem

**Comment by zhanghongtong** [comment]
Hi, @ancienter 
Plaease make sure there are no spaces in the installation path

**Comment by zhanghongtong** [comment]
This issue has not been updated in a long time, I will close it, if you have any questions, you can reopen it at any time
