### ISSUE TITLE
An exception will appear in the form of service installation on windows 10

### ISSUE THREAD

**Issue by violetmoon027** [emqx/emqx#3486]
**Environment**:

- EMQ X version : v4.1-rc.2 
- OS : Window10 Professional

**What happened and what you expected to happen**:
Start cmd as administrator, Run the command in the installation root directory：
ex:
C:\emqx> bin\emqx.cmd install
C:\emqx\erts-10.7\bin\erlsrv.exe: A service with the name emqx_v4.1-rc.2 alread exists.

C:\emqx> erts-10.7\bin\erlsrv.exe remove emqx_v4.1-rc.2
erts-10.7\bin\erlsrv.exe: Unable to remove service (not enough privileges?)
Error: ¾ä±úÎÞÐ§¡£

C:\emqx>sc query emqx_v4.1-rc.2
[SC] EnumQueryServicesStatus:OpenService 失败 1060:

指定的服务未安装。

**How to reproduce it (as minimally and precisely as possible)**:
Download and install 

**Anything else we need to know?**:
none

**Comment by violetmoon027** [comment]
@tigercl @farhadi @callbay   

  this problem is very import,Please help me resolve this issue as soon as possible. 
   thank you very much.

**Comment by zhanghongtong** [comment]
Sorry for the late reply. Have you solved your problem?
