### ISSUE TITLE
ACL : client that already subscribe cannot manipulate by acl mysql 

### ISSUE THREAD

**Issue by momonchi** [emqx/emqx#3487]
I'm using paho for android. 
In Publish, acl working perfectly as expected even changing allow value.
But my concern, when client already subscribe to topic "a/b/#" allow 1, and suddenly change this to allow 0 and still receiving the message from topic "a/b/#".

Already tried the acl cache off and cache on and set 3 secs.
And also tried clear cache through broker and API.

I just wan't to know if there's a way to change dynamically and client will not receiving any message from that topic?

Thanks in advance.

**Comment by tigercl** [comment]
@momonchi The ACL check is for the action of subscribing. Changing the ACL will not affect the subscription that has been completed.

**Comment by momonchi** [comment]
@tigercl Thank you for the response. Now i understand. I just confused, because I have a mosquitto broker and the auth handle the dynamic changes in mysql acl. If the user is not allowed even the subscribe was triggered, client will not receive any message from that topic.

I'am just sharing this exp, hopefully this also will available in the emqx broker for the dynamic receiving.

**Comment by wivwiv** [comment]
@momonchi 
Checking ACL dynamically is a huge overhead, which means checking ACL when every message arrives.
If you change the ACL, you can unsubscribe to the topic using the  REST API.

https://docs.emqx.io/broker/latest/en/advanced/http-api.html#endpoint-do-unsubscribe

**Comment by shaojun** [comment]
@wivwiv the provided suggestion is more like a 'admin force client to unsubscribe topics for reload acl' operation, will this operation trigger any notification on client side? then the client can re-subscribe.

**Comment by wivwiv** [comment]
@shaojun 
This is more like that the administrator controls the topic according to the ACL to ensure that the existing subscription list conforms to the ACL, and there is no need to re-subscribe to trigger the ACL check.
In order to maintain high performance, there is no better solution. pls try to plan ACL in advance.
