### ISSUE TITLE
CLI: resources create error

### ISSUE THREAD

**Issue by dstmath** [emqx/emqx#3488]
OS: debian 10
emqx: 4.1-rc2

/usr/bin/emqx_ctl resources create 'web_hook' -c '{"url": "http://host-name/chats"}' -d 'forward msgs to host-name/chats'

RPC to emqx@127.0.0.1 error: undef

**Comment by tigercl** [comment]
@dstmath Could you provide the log (`emqx.log.*`) in case of error?

**Comment by dstmath** [comment]
@tigercl 
`2020-05-27 08:36:22.079 [error] [Ctl] CMD Error:undef, Stacktrace:[{getopt,parse_and_check,[[{type,undefined,undefined,atom,"Resource Type"},{config,99,"config",{binary,<<"{}">>},"Config"},{descr,100,"descr",{binary,<<>>},"Description"}],["web_hook","-c","{\"url\": \"http://host-name/chats\"}","-d","forward msgs to host-name/chats"]],[]},{emqx_rule_engine_cli,with_opts,4,[{file,"/emqx-rel/_build/emqx-pkg/lib/emqx_rule_engine/src/emqx_rule_engine_cli.erl"},{line,320}]},{emqx_ctl,run_command,2,[{file,"/emqx-rel/_build/emqx-pkg/lib/emqx/src/emqx_ctl.erl"},{line,105}]},{rpc,'-handle_call_call/6-fun-0-',5,[{file,"rpc.erl"},{line,197}]}]`

**Comment by dstmath** [comment]
@tigercl I have tried the command:
`$ ./bin/emqx_ctl resources create 'webhook1' 'web_hook' -c '{"url": "http://host-name/chats"}' -d 'forward msgs to host-name/chats'
`
got the same error.

**Comment by dstmath** [comment]
@tigercl Any progress??

**Comment by terry-xiaoyu** [comment]
@dstmath The fix will be included in 4.1-rc3.
