### ISSUE TITLE
Kick out the specified client

### ISSUE THREAD

**Issue by Eric-Sunjian** [emqx/emqx#3491]
I want to know that 'whether the client know that the broker closed the connection?',is there a specific error code?

**Comment by Eric-Sunjian** [comment]
I used the HTTP API to kick out  the specified client .

**Comment by tigercl** [comment]
@Eric-Sunjian Clients will receive DISCONNECT packet with `0x00 - Normal disconnection` reason code.

**Comment by zhanglc** [comment]
@tigercl seems like the server just close the tcp connnection. no mqtt package send by emqx server.

![image](https://user-images.githubusercontent.com/4049133/98212525-ae90d600-1f7e-11eb-8d96-cc55aa70c76f.png)

**Comment by zmstone** [comment]
@HJianBo there should at least be a clarification if this is intended behavior.
Otherwise follow up with a fix
Thanks

**Comment by zmstone** [comment]
Latest v5 behaviour:

For MQTT v5 clients, the server sends DISCONNECT packet with error code `RC_ADMINISTRATIVE_ACTION` (or `0x98`, or `152`).
For MQTT v3 clients, the server disconnects the socket.
