### ISSUE TITLE
We need the configuration document of the Windows platform compilation environment!!!

### ISSUE THREAD

**Issue by yanghuabin1202** [emqx/emqx#3495]
**Please describe your problem in detail, if necessary, you can upload the log file through the attachment**:
We use emqx on windows platform，compiling with source code always fails. I hope emqx can provide some document abort compiling on windows platform. thanks!!!

**Comment by HJianBo** [comment]
Of course, We will publish it later

**Comment by yanghuabin1202** [comment]
thank you very much！hope to see from Offical Blog very soon!
