### ISSUE TITLE
emqx fail to start

### ISSUE THREAD

**Issue by Breeze-Wu** [emqx/emqx#3497]
Environment
OS: Windows
EMQ: 4.0.5

Description
emqx fail to start  system report that program fail to start 0xc000007b
I use directx to repair system file ,emqx is not to start
question:
1.How can i do ,thanks!

**Comment by zhanghongtong** [comment]
Hi, @Breeze-Wu 
It is recommended that you install Visual Studio 2019 and try again

**Comment by zhanghongtong** [comment]
This issue has not been updated for a long time, I will close it, if you have any questions, you are welcome to open it at any time
