### ISSUE TITLE
EMQX can't storing messages in mqtt_msg table

### ISSUE THREAD

**Issue by the-pythonistaa** [emqx/emqx#3498]
#### Environment

- OS: CentOS Linux release 7.7.1908 (Core)
- Erlang/OTP: Erlang/OTP 22 [erts-10.7.1] [source] [64-bit]
- EMQ: Version: 4.0.8 

#### Description

anyone can help me to store published messages into postgres from client, i have followed https://docs.emqx.io/tutorial/latest/en/backend/postgres.html#postgresql-message-table article but the after creation of table it won't be storing the messages which i am publishing. i have created table for storing client status using created the mqtt_client table, which is working fine. 

here, are the logs when i connect client and publish and subscribe the message.

```
> 2020-05-27 05:52:33.519 [error] <<"LOCUST_RTR_MACID_62">>@IP_ADDRESS:51453 Lookup retain error: {error,error,<<"26000">>,invalid_sql_statement_name,
>                             <<"prepared statement \"lookup_sub\" does not exist">>,
>                             [{file,<<"prepare.c">>},
>                              {line,<<"514">>},
>                              {routine,<<"FetchPreparedStatement">>},
>                              {severity,<<"ERROR">>}]}
> 2020-05-27 05:52:33.827 [error] <<"LOCUST_RTR_MACID_62">>@IP_ADDRESS:51453 Lookup msg error: {error,error,<<"26000">>,invalid_sql_statement_name,
>                          <<"prepared statement \"query_ack\" does not exist">>,
>                          [{file,<<"prepare.c">>},
>                           {line,<<"514">>},
>                           {routine,<<"FetchPreparedStatement">>},
>                           {severity,<<"ERROR">>}]}
> 2020-05-27 05:52:33.829 [error] <<"LOCUST_RTR_MACID_62">>@IP_ADDRESS:51453 Lookup retain error: {error,error,<<"26000">>,invalid_sql_statement_name,
>                             <<"prepared statement \"lookup_retain\" does not exist">>,
>                             [{file,<<"prepare.c">>},
>                              {line,<<"514">>},
>                              {routine,<<"FetchPreparedStatement">>},
>                              {severity,<<"ERROR">>}]}

![image](https://user-images.githubusercontent.com/20423235/83008009-23f09600-a032-11ea-8c8e-c5dc910e1cb5.png)


```

**Comment by tigercl** [comment]
@NirajPanchasara Sorry to bother you, we suggest you use the rule engine, please refer to https://docs.emqx.io/broker/latest/en/rule/rule-example.html#create-postgresql-rules.

**Comment by NirajPanchasara** [comment]
@tigercl i have tried with set rules, i can store it, but the retain field is giving error while "$events/message_delivered" fired and insert the entry to table, tbh mqtt_client table is working fine with storing and all pgsql backend config file is also fine.

**Comment by NirajPanchasara** [comment]
@tigercl i am on trial version of emqc enterprise, is there any issue ?
