### ISSUE TITLE
Authentication value of rc 4 and 5

### ISSUE THREAD

**Issue by qxqxq** [emqx/emqx#3499]
The value of rc indicates success or not:
            0: Connection successful
            1: Connection refused - incorrect protocol version
            2: Connection refused - invalid client identifier
            3: Connection refused - server unavailable
            4: Connection refused - bad username or password
            5: Connection refused - not authorised
            6-255: Currently unused.

I opened the following plugin
Plugin(emqx_auth_clientid, version=3.2.4, description=EMQ X Authentication with ClientId/Password, active=true)
Plugin(emqx_auth_http, version=3.2.4, description=EMQ X Authentication/ACL with HTTP API, active=false)
Plugin(emqx_auth_jwt, version=3.2.4, description=EMQ X Authentication with JWT, active=false)
Plugin(emqx_auth_ldap, version=3.2.4, description=EMQ X Authentication/ACL with LDAP, active=false)
Plugin(emqx_auth_mongo, version=3.2.4, description=EMQ X Authentication/ACL with MongoDB, active=false)
Plugin(emqx_auth_mysql, version=3.2.4, description=EMQ X Authentication/ACL with MySQL, active=true)
Plugin(emqx_auth_pgsql, version=3.2.4, description=EMQ X Authentication/ACL with PostgreSQL, active=false)
Plugin(emqx_auth_redis, version=3.2.4, description=EMQ X Authentication/ACL with Redis, active=false)
Plugin(emqx_auth_username, version=3.2.4, description=EMQ X Authentication with Username and Password, active=true)
Plugin(emqx_bridge_mqtt, version=3.2.4, description=EMQ X Bridge to mqtt broker, active=true)
Plugin(emqx_coap, version=3.2.4, description=EMQ X CoAP Gateway, active=false)
Plugin(emqx_dashboard, version=3.2.4, description=EMQ X Web Dashboard, active=true)
Plugin(emqx_delayed_publish, version=3.2.4, description=EMQ X Delayed Publish, active=false)
Plugin(emqx_lua_hook, version=3.2.4, description=EMQ X Lua Hooks, active=false)
Plugin(emqx_lwm2m, version=3.2.4, description=EMQ X LwM2M Gateway, active=false)
Plugin(emqx_management, version=3.2.4, description=EMQ X Management API and CLI, active=true)
Plugin(emqx_psk_file, version=3.2.4, description=EMQX PSK Plugin from File, active=false)
Plugin(emqx_recon, version=3.2.4, description=EMQ X Recon Plugin, active=true)
Plugin(emqx_reloader, version=3.2.4, description=EMQ X Reloader Plugin, active=false)
Plugin(emqx_retainer, version=3.2.4, description=EMQ X Retainer, active=true)
Plugin(emqx_rule_engine, version=3.2.4, description=EMQ X Rule Engine, active=true)
Plugin(emqx_sn, version=3.2.4, description=EMQ X MQTT SN Plugin, active=false)
Plugin(emqx_statsd, version=3.2.4, description=Statsd for EMQ X, active=false)
Plugin(emqx_stomp, version=3.2.4, description=EMQ X Stomp Protocol Plugin, active=false)
Plugin(emqx_web_hook, version=3.2.4, description=EMQ X Webhook Plugin, active=false)

Disable anonymous authentication in the configuration file etc/emqx.conf: mqtt.allow_anonymous = false.

Rc means 5 when I enter an incorrect username or password. When is rc going to be 4？

How can I tell by rc whether a username or a clientid or a password is incorrect or if I'm blacklisted.

Thanks.

**Comment by HJianBo** [comment]
Hi, @qxqxq Thanks for your report here.

It should return ` not authorized` if the server got an ` incorrect username or password`. We will fit it at v4.1.0

**Comment by HJianBo** [comment]
Hi guys, the v4.1.0 has released. Plz try it
