### ISSUE TITLE
Maximum number of connections

### ISSUE THREAD

**Issue by morestart** [emqx/emqx#3501]
![image](https://user-images.githubusercontent.com/35556811/83272983-7ed6e880-a1fe-11ea-8435-c03a26a6c9b3.png)
想问下这里面连接数2/9是最多支持九个客户端连接嘛，主题最多47个？

**Comment by tigercl** [comment]
@morestart I'm sorry for bothering you, it means the historical maximum, we are considering improving it.

**Comment by morestart** [comment]
> @morestart I'm sorry for bothering you, it means the historical maximum, we are considering improving it.

意思就是历史上最多有九个客户端而不是系统本身只能连九个是吗？

**Comment by tigercl** [comment]
@morestart Yes, you're right.

**Comment by morestart** [comment]
> @morestart Yes, you're right.

thanks
