### ISSUE TITLE
enable tls and mysql verification failed for '%c' and '%u' is 'undefind'

### ISSUE THREAD

**Issue by Maxshi2005** [emqx/emqx#3502]
#### Environment

- OS: ubuntu16.04
- Erlang/OTP: 
- EMQ: v4.0.0
- pull image: $ docker pull emqx/emqx:v4.0.0  

#### Description

* with following settings to enable tls, "%u" is valid but could get the value of “%c” and "%d"  :
  listener.ssl.external.cacertfile = /path/root_cert.pem
  listener.ssl.external.certfile = /path/server_cert.pem
  listener.ssl.external.keyfile = /path/server_key.pem
  listener.ssl.external.verify = verify_peer
  listener.ssl.external.fail_if_no_peer_cert = true
  listener.ssl.external.peer_cert_as_username = cn
  auth.mysql.auth_query = select password from mqtt_user where '%u' = username    limit 1
* official doc say: listener.ssl.external.peer_cert_as_username default value is 'cn',  but we have to set it to "cn" explicitly， other wise it doesn't work.

**Comment by HJianBo** [comment]
It is a bug actually. We have fixed it at https://github.com/emqx/emqx/pull/3417
