### ISSUE TITLE
After deploying emqx in kubernetes by helm，but its helmchart only have a few configures，I want change configures in emqx.conf and emqx_auth_mysql.conf

### ISSUE THREAD

**Issue by lcwus2** [emqx/emqx#3507]
I deployed emqx in kubernetes by helm，but its helmchart only have a few configures，I want change some configures in emqx.conf and emqx_auth_mysql.conf.How could I do with emqx chart？(btw, is there some docs about emqx's chart)

**Comment by zhanghongtong** [comment]
Hi, @lcwus2 
You can modify the environment variable by modifying the `emqxConfig` in [value.yaml](https://github.com/emqx/emqx-rel/blob/master/deploy/charts/emqx/values.yaml#L32), `emqx.conf` and `emqx_auth_mysql.conf` can modify the configuration by setting the environment variable, you can view our [container documentation](https://github.com/emqx/emqx-rel/blob/master/deploy/docker/README.md#configuration)

**Comment by lcwus2** [comment]
that helps a lot.
but I have another question, I set plugins like this `  EMQX_LOADED_PLUGINS: emqx_management，emqx_auth_mysql，emqx_recon，emqx_retainer，emqx_dashboard,
    emqx_rule_engine, emqx_auth_username`, and after that data/loaded_plugins file 
![image](https://user-images.githubusercontent.com/30100640/83851796-7114ec00-a745-11ea-81d8-2222d931e71c.png)
and before this code, data/loaded_plugins file 
![image](https://user-images.githubusercontent.com/30100640/83851875-8b4eca00-a745-11ea-8e27-6e878067daf6.png)
Does this really works?

**Comment by lcwus2** [comment]
I try to change `auth.mysql.auth_query` , 
before I set this,
![image](https://user-images.githubusercontent.com/30100640/83866318-3a959c00-a75a-11ea-8282-2380e0de1f73.png)
but after I set this,
![image](https://user-images.githubusercontent.com/30100640/83866084-d541ab00-a759-11ea-81e2-e9e7d4582fb4.png)
it seems like two same `auth.mysql.auth_query`

**Comment by zhanghongtong** [comment]
> that helps a lot.
> but I have another question, I set plugins like this ` EMQX_LOADED_PLUGINS: emqx_management，emqx_auth_mysql，emqx_recon，emqx_retainer，emqx_dashboard, emqx_rule_engine, emqx_auth_username`, and after that data/loaded_plugins file
> ![image](https://user-images.githubusercontent.com/30100640/83851796-7114ec00-a745-11ea-81d8-2222d931e71c.png)
> `emqx_management. emqx_auth_mysql. emqx_recon. emqx_retainer. emqx_dashboard. emqx_rule_engine. emqx_auth_username. `
> and before this code, data/loaded_plugins file
> ![image](https://user-images.githubusercontent.com/30100640/83851875-8b4eca00-a745-11ea-8e27-6e878067daf6.png)
> `{emqx_management, true}. {emqx_recon, true}. {emqx_retainer, true}. {emqx_dashboard, true}. {emqx_rule_engine, true}. {emqx_bridge_mqtt, false}. `
> Does this really works?

Yes, it works, and EMQX supports both configuration formats

**Comment by zhanghongtong** [comment]
>  it seems like two same `auth.mysql.auth_query`

This appears to be the result of `/usr/bin/docker-entrypoint.sh` being executed twice
