### ISSUE TITLE
Incorrect doc of listener.ssl.external.tls_versions default value

### ISSUE THREAD

**Issue by ypji** [emqx/emqx#3512]
https://docs.emqx.io/broker/latest/en/configuration/configuration.html#listenersslexternaltlsversions

It says that the default value of the `listener.ssl.external.tls_versions` is `tlsv1.2,tlsv1.1,tlsv1`, but the actual result is `tlsv1.2`  only. If I want to enable the tlsv1.1 and tlsv1, I need to define this **default** value manually.

My EMQX version is `4.0.7`.

**Comment by tigercl** [comment]
@ypji Sorry, it should be that our documentation has not been updated in time. At present, this is indeed the case, you need to modify the configuration file.

**Comment by ypji** [comment]
```
listener.ssl.external.tls_versions default = tlsv1.2,tlsv1.1,tlsv1
```

You need to specify the above line on your config file. @alexandrim0 

BTW, I dare not upgrade the software to a new version anymore, SHOCKED!

**Comment by alexandrim0** [comment]
My case is different.
https://github.com/emqx/emqx/issues/3708

**Comment by alexandrim0** [comment]
The root of my problem was in config. Thank you @ypji 
But there was a trouble with checking because client (ubuntu 20.04) was unable to use tls < 1.2
