### ISSUE TITLE
Certificate expired repos.emqx.io

### ISSUE THREAD

**Issue by NielsH** [emqx/emqx#3515]
Hi,

We get the following running `apt-get update`
```
Err:13 https://repos.emqx.io/emqx-ce/deb/debian buster Release
  Certificate verification failed: The certificate is NOT trusted. The certificate chain uses expired certificate.  Could not handshake: Error in the certificate verification. [IP: 13.227.223.100 443]
```

Please see:

https://dev.ssllabs.com/ssltest/analyze.html?d=repos.emqx.io&s=52.84.52.101&latest

![image](https://user-images.githubusercontent.com/848114/83731000-1fd40200-a64a-11ea-9b1e-43385c691acc.png)

Could you check this?

Cheers

Niels

**Comment by HJianBo** [comment]
Hi @NielsH Thanks for your feedback. We will check it later :)

**Comment by spring2maz** [comment]
Seems to be resolved:

```
$ curl -v -L https://repos.emqx.io/emqx-ce/deb/debian
....
* Server certificate:
*  subject: CN=*.emqx.io
*  start date: Jun  4 00:00:00 2020 GMT
*  expire date: Sep  6 00:00:00 2022 GMT
```
