### ISSUE TITLE
Mongodb login verification, whether an account can be added and can only be logged in once, and the login of another device will kick the earliest device offline

### ISSUE THREAD

**Issue by jhhe66** [emqx/emqx#3517]
mongodb登录验证，是否可以增加一个账号只能登录一次，另外一个设备登录则把最早的设备踢下线

**What would you like to be added/modified**:

**Why is this needed**:

**Comment by HJianBo** [comment]
Hi, @jhhe66 I can understand whats your meanings.

Assume the Devices (设备登录) is an MQTT client. The broker has implemented that. It will kick out old MQTT clients if a new client login successfully with the same Client ID.


If not, please give me more details requirements, thanks :)
