### ISSUE TITLE
errorContext: connection_shutdown,"TLS server: In state hello at tls_record.erl:477 generated SERVER ALERT: Fatal - Unexpected Message\n"

### ISSUE THREAD

**Issue by lcwus2** [emqx/emqx#3519]
**Please describe your problem in detail, if necessary, you can upload the log file through the attachment**:
![image](https://user-images.githubusercontent.com/30100640/83905332-10f96680-a794-11ea-939f-7214bf763f60.png)
I enabled tls,but have error like this

**Comment by HJianBo** [comment]
It seems your TLS handshake failed, due to an error handshake flow.

Plz check the TLS functional correctness for your client

**Comment by lcwus2** [comment]
I changed these ssl configuration:
  EMQX_LISTENER__SSL__EXTERNAL__CACERTFILE: /path/cacert.crt
  EMQX_LISTENER__SSL__EXTERNAL__CERTFILE: /path/cert.crt
  EMQX_LISTENER__SSL__EXTERNAL__FAIL_IF_NO_PEER_CERT: "true"
  EMQX_LISTENER__SSL__EXTERNAL__HANDSHAKE_TIMEOUT: 15s
  EMQX_LISTENER__SSL__EXTERNAL__KEYFILE: /path/key.pem
  EMQX_LISTENER__SSL__EXTERNAL__PEER_CERT_AS_USERNAME: cn
  EMQX_LISTENER__SSL__EXTERNAL__VERIFY: verify_peer

**Comment by HJianBo** [comment]
Does it work?

These confs is a two-way TLS handshake. The client is also two-way TLS?

**Comment by lcwus2** [comment]
yes,  and I enabled mysql plugin, but I changed configuration auth_query like this `EMQX_AUTH__MYSQL__AUTH_QUERY: select password from mqtt_user where '%u' like concat('%', username, '%') limit 1`
but in emqx_auth_mysql.conf , there are two same configuration 
![image](https://user-images.githubusercontent.com/30100640/83935728-c22cea80-a7ee-11ea-9fcb-f3d84aeaec51.png)

**Comment by spring2maz** [comment]
@lcwus2 It seems the TLS issue is resolved, and the mysql auth config issue is something else ?
If so, do you mind closing this issue and create a new one to follow up ?
