### ISSUE TITLE
emqtt_bench is often interrupted

### ISSUE THREAD

**Issue by JoshRong** [emqx/emqx#3522]
**Environment**:

- EMQ X version (e.g. `emqx_ctl status`): Master
- Hardware configuration (e.g. `lscpu`):CPU：4 ； Memory Capacity：8G
- OS (e.g. `cat /etc/os-release`):CentOS Linux7.6
- Kernel (e.g. `uname -a`): 3.10.0-1062.12.1.el7.x86_64
- Erlang/OTP version (in case you build emqx from source code): 22.1
- Others:emqtt_bench:0.3.1

**What happened and what you expected to happen**:
When I use emqtt_bench, the number of connections reaches a little over 30,000，emqtt_bench will interrupt and keep reporting errors。The error content is as follows:

client(49974): connect error - eaddrnotavail
=ERROR REPORT==== 8-Jun-2020::01:10:14.121049 ===
** State machine <0.159.0> terminating
** Last event = {{call,{<0.158.0>,#Ref<0.3523279616.1837629441.44040>}},
                 {connect,emqtt_sock}}
** When server state  = {initialized,
                            {state,undefined,<0.158.0>,undefined,
                                "192.168.0.246",1883,[],emqtt_sock,undefined,
                                [{ip,{192,168,0,137}}],
                                60000,false,
                                <<"192.168.0.137_bench_conn_49974_2540911447">>,
                                true,undefined,undefined,4,<<"MQTT">>,1800,
                                undefined,false,false,false,
                                {mqtt_msg,0,false,false,undefined,undefined,
                                    undefined,undefined},
                                #{},[],#{},infinity,#{},#{},true,30000,
                                undefined,0,undefined,undefined,1,
                                {none,#{max_size => 268435455,version => 4}}}}
** Reason for termination = exit:eaddrnotavail
** Callback mode = state_functions
** Stacktrace =
**  [{gen_statem,loop_state_callback_result,11,
                 [{file,"gen_statem.erl"},{line,1306}]},
     {proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,249}]}]
** Client <0.158.0> stacktrace
** [{gen,do_call,4,[{file,"gen.erl"},{line,167}]},
    {gen_statem,call_dirty,4,[{file,"gen_statem.erl"},{line,619}]},
    {emqtt_bench,connect,4,
                 [{file,"/home/emqtt-bench/src/emqtt_bench.erl"},{line,307}]}]

=CRASH REPORT==== 8-Jun-2020::01:10:14.121527 ===
  crasher:
    initial call: emqtt:init/1
    pid: <0.159.0>
    registered_name: []
    exception exit: eaddrnotavail
      in function  gen_statem:loop_state_callback_result/11 (gen_statem.erl, line 1306)
    ancestors: [<0.158.0>]
    message_queue_len: 1
    messages: [{'EXIT',<0.158.0>,normal}]
    links: []
    dictionary: []
    trap_exit: true
    status: running
    heap_size: 2586
    stack_size: 27
    reductions: 12728
  neighbours:

I want to know why this is happening and how to solve it。

**Comment by JoshRong** [comment]
I have tuned the system according to the official documentation

**Comment by JoshRong** [comment]
I just tested, the number of connections to 32517 will be wrong

**Comment by tigercl** [comment]
@JoshRong Any error log in emqx broker?

**Comment by JoshRong** [comment]
> @JoshRong emqx代理中是否有错误日志？

I just tested it, and there is no error in emq broker. When the number of connections reaches 32517, it stops directly.

**Comment by JoshRong** [comment]
Using docker seems to solve the problem, but it is difficult to configure multiple network cards with docker

**Comment by JoshRong** [comment]
@tigercl  Hello, did you find a solution to the problem?

**Comment by HJianBo** [comment]
@JoshRong  The `eaddrnotavail` error means that the `emqtt` cannot assign requested address. It is a Client-side error for some reason.

Did you perform the tuning script on the client machine?

**Comment by JoshRong** [comment]
> @JoshRong 该`eaddrnotavail`错误表示`emqtt`无法分配请求的地址。由于某种原因，这是客户端错误。
> 
> 您是否在客户端计算机上执行了调整脚本？
> 
> 然后Plz提供您的基准命令。

Yes, I am on a client machine with 4 cores and 8G memory. I have tuned the client machine.
This is my command:./emqtt_bench conn -h 192.168.0.246 -c 50000 --ifaddr 192.168.0.161 -i 100 -k 1800

My client and server are on the same network。

**Comment by JoshRong** [comment]
@HJianBo Did you find the problem?

**Comment by HJianBo** [comment]
Sorry, @JoshRong I have no idea there. But the problem should be caused by the client's machine, such as some configuration or OS

We will try to reproduce it, It may take some time

**Comment by spring2maz** [comment]
`eaddrnotavail` can be caused by client side running out of available ports.
e.g. in my case (ubuntu), it's 
```
sysctl net.ipv4.ip_local_port_range
net.ipv4.ip_local_port_range = 32768    60999
```
That gives me about `28,231` available ports.
You can perhaps try to adjust it.

**Comment by HJianBo** [comment]
Hi @JoshRong Does this parameter take effect?

**Comment by JoshRong** [comment]
> Hi @JoshRong Does this parameter take effect?
I tried this solution very early, and it has no effect.
