### ISSUE TITLE
Emqttd wildcard certificate error.

### ISSUE THREAD

**Issue by yuvarajan1989k** [emqx/emqx#3523]
Hi,

After i updated the new certificate. i am getting the below error. but i am able to connect using port 8883. i am pointing to the new certificate. kindly assist me on this.

OS:- Ubuntu 16.

SSL: certify: ssl_alert.erl:88:Fatal error: certificate expired

**Comment by tigercl** [comment]
@yuvarajan1989k Sorry for late reply. Have you verified your new certificate?

**Comment by yuvarajan1989k** [comment]
yes. but in the client, intermediate cert got expired. is there any way to ignore the certificate error and make it work without updating the certificate ?

**Comment by spring2maz** [comment]
Hi.
I am not entirely sure what exact scenario this issue happened.
If this is server complaining that a client is sending an expired certificate (or intermediate CA certificate), I guess you can try disable verification on the server side.
I believe `listener.ssl.external.verify = verify_none` should do.

**Comment by yuvarajan1989k** [comment]
Disabling the verification on the server-side does not work. my EMQTT version is 2.2

**Comment by spring2maz** [comment]
Sorry, I did not verify this.
When server has `verify_none`, client does not have to send the CA certificate (which is expired in your case).
If your client is Erlang, `cacertfile` in ssl option can be undefined.

**Comment by yuvarajan1989k** [comment]
i would like to clarify the below one. do i need to look for this option on the server-side configuration ? or in the client side ?

If your client is Erlang, cacertfile in ssl option can be undefined.

**Comment by spring2maz** [comment]
`listener.ssl.external.verify = verify_none` is for EMQTT, I checked version 2.2, there is this config.
This will make EMQTT skip or ignore verifying client's certificates,
My assumption was, `verify_none` should make EMQTT skip or ignore expired certificates.

However you said it did not help.
> Disabling the verification on the server-side does not work. my EMQTT version is 2.2

So I am now suggesting that the client should not need to send its CA certificate in TLS handshake.
If EMQTT is correctly configured to `verify_none`, it should not complain about missing certificates.
However this client behavior is out of EMQTT's control, and whether or not it's configurable on the client side very much depends on their implementations.
For Erlang Clients, it's the `cacertfile` SSL option to be absence.

**Comment by spring2maz** [comment]
From security point of view, CA certificate renewal is highly recommended.
However if you do not care (e.g. only needed TLS for encryption), please continue reading:

If your client must have a CA certificate provided, here is a workaround:
You may generate a self-signed certificate and sign a new certificate for your client.
Then configure EMQTT not to verify client certificates.

**Comment by yuvarajan1989k** [comment]
thanks for the speedy update.

I have around 80k clients, it's very difficult to update the certificate on all clients. Below cause this issue.

FYI:-

https://support.sectigo.com/articles/Knowledge/Sectigo-AddTrust-External-CA-Root-Expiring-May-30-2020

**Comment by yuvarajan1989k** [comment]
Also i tested in broker version 4.1.0 , getting the below error

2020-06-14 15:50:31.424 [notice] TLS server: In state hello at tls_record.erl:477 generated SERVER ALERT: Fatal - Unexpected Message

2020-06-14 15:50:31.424 [error]     supervisor: 'esockd_connection_sup - <0.1630.0>'
    errorContext: connection_shutdown
    reason: {ssl_error,
                {tls_alert,
                    {unexpected_message,
                        "TLS server: In state hello at tls_record.erl:477 generated SERVER ALERT: Fatal - Unexpected Message\n"}}}
    offender: [{pid,<0.1728.0>},
               {name,connection},
               {mfargs,
                   {emqx_connection,start_link,
                       [[{deflate_options,[]},
                         {max_conn_rate,500},
                         {active_n,100},
                         {zone,external}]]}}]

**Comment by yuvarajan1989k** [comment]
Emqx version:- 4.1.0

Scenario:-
-------------
want to ignore the client certificate while connecting to the broker.

Server-side configuration:-
----------------------------------
listener.ssl.external.verify = verify_none
listener.ssl.external.keyfile = etc/certs/private.key
listener.ssl.external.certfile = etc/certs/combined.pem

Steps:-

1. using mosquito client to check.
    mosquitto_sub -h 127.0.0.1 -t 'abc' -p 8883 -d

Server log:-
`020-06-15 01:19:42.648 [error]     supervisor: 'esockd_connection_sup - <0.1630.0>'
    errorContext: connection_shutdown
    reason: {ssl_error,
                {tls_alert,
                    {unexpected_message,
                        "TLS server: In state hello at tls_record.erl:477 generated SERVER ALERT: Fatal - Unexpected Message\n"}}}
    offender: [{pid,<0.1988.0>},
               {name,connection},
               {mfargs,
                   {emqx_connection,start_link,
                       [[{deflate_options,[]},
                         {max_conn_rate,500},
                         {active_n,100},
                         {zone,external}]]}}]
2020-06-15 01:19:43.652 [notice] TLS server: In state hello at tls_record.erl:477 generated SERVER ALERT: Fatal - Unexpected Message
`

While connecting using mosquito clients, it said connecting. Also, I instruct the server to don't look for client certificate. But I can see the above error logs. 

Please correct me, if i am doing anything wrong. thanks.

**Comment by spring2maz** [comment]
Hi. How is the client is instructed to perform TLS handshake in your test ? 
This command line `mosquitto_sub -h 127.0.0.1 -t 'abc' -p 8883 -d` seems to me is a TCP client trying to connect TLS port.
According to https://mosquitto.org/man/mosquitto_sub-1.html, you need to provide TLS options in the command line.
e.g. `--keyfrom` to provide a private key, `--capath` for CA certificates, `--cert` for client certificate,  or maybe `--insecure` to disable TLS validation.

**Comment by yuvarajan1989k** [comment]
--insecure (disable TLS validation) made a trick. thank you.

**Comment by spring2maz** [comment]
Have you tried to append the expired certificate to `etc/certs/cacert.pem` 
and configure `listener.ssl.external.cacertfile = etc/certs/cacert.pem`?

**Comment by yuvarajan1989k** [comment]
Yes, i tried with new certificate.
