### ISSUE TITLE
Whether to support multi-lua script file parsing

### ISSUE THREAD

**Issue by LvCodeing** [emqx/emqx#3524]
What I want is, according to different products, use different analysis methods (), and different analysis methods are placed in different lua script files.

for example:
# main.lua
function register_hook()
    return "on_message_publish"
end

function default(clientid, username, topic, payload, qos, retain)
    return topic, payload, qos, retain
end

function on_message_publish(clientid, username, topic, payload, qos, retain)
	 if topic == "A" then
	     return func_a(clientid, username, topic, payload, qos, retain);
         else if  if topic == "B" then
	     return func_b(clientid, username, topic, payload, qos, retain);
	 else 
	     return default(clientid, username, topic, payload, qos, retain);
	end
end

# A.lua 
function func_a(clientid, username, topic, payload, qos, retain)
    return topic, payload, qos, retain
end

# B.lua 
function func_b(clientid, username, topic, payload, qos, retain)
    return topic, payload, qos, retain
end

**Comment by tigercl** [comment]
@LvCodeing Yes, we support it.

**Comment by LvCodeing** [comment]
> @LvCodeing Yes, we support it.

Which version has already supported this feature?

**Comment by LvCodeing** [comment]
> @LvCodeing Yes, we support it.

I have used v4.1.0 and v3.4.3 versions, neither seems to support it. I repeat my needs: use different protocol parsing methods according to different products, and these parsing methods are scattered in different lua script files (main.lua, A.lua, and B.lua). The above example uses the on_message_publish method.

**Comment by LvCodeing** [comment]
> @LvCodeing Yes, we support it.

I have used v4.1.0 and v3.4.3 versions, neither seems to support it. I repeat my needs: use different protocol parsing methods according to different products, and these parsing methods are scattered in different lua script files (main.lua, A.lua, and B.lua). The above example uses the on_message_publish method.

**Comment by LvCodeing** [comment]
> @LvCodeing Yes, we support it.

I have used v4.1.0 and v3.4.3 versions, neither seems to support it. I repeat my needs: use different protocol parsing methods according to different products, and these parsing methods are scattered in different lua script files (main.lua, A.lua, and B.lua). The above example uses the on_message_publish method.

**Comment by xyz361** [comment]
@HJianBo Please help to solve this problem~

**Comment by HJianBo** [comment]
Hi, @LvCodeing Sorry for the late reply there :(

In the current version(below v4.1.0), we don't support the function call that crossed the file.

There are two workarounds:
1.  Put all function to a script.
2. Register Hook at each script file (similar `main.lua`)

**Comment by LvCodeing** [comment]
> In the current version(below v4.1.0), we don't support the function call that crossed the file.

First of all, thank you very much for your reply. I have tried both v3.4.3 and v4.1.0, and neither seems to support cross-file access.

**Comment by LvCodeing** [comment]
> 2. Register Hook at each script file (similar `main.lua`)

https://github.com/emqx/emqx-lua-hook  
README.md

Each lua script could export several functions binding with emqx hooks, triggered by message publish, topic subscribe, client connect, etc. Different lua scripts may export same type function, binding with a same event. But their order being triggered is not guaranteed.

**Comment by HJianBo** [comment]
It should be **Alphabetical order**. Is that so?
