### ISSUE TITLE
Json payload publish from API 

### ISSUE THREAD

**Issue by mtimoleon** [emqx/emqx#3528]
With emqx versions prior to 4.0.2, before the change of json encode/decode from jsx to jiffy (see pr #3213) we could post a message from postman like:

```
{
    "topic": "commands/r03/list/countUserLists",
    "payload": '{
        "id": "pxx",
        "name": "pxx-postman",
        "dateIssued": "{{timestamp}}",
        "dataType": "json",
        "data": {
        	"userId":"6d079ab3-a985-3dc7-8086-3dc32dc08cb9",
        	"operationId":1
        }
      }',
    "qos": 2,
    "retain": false,
    "client_id": "postman"
}
``` 
and it was posted correctly. After this change we get bad request (400) response. Removing single quotes in payload value cause clients disconnection from broker.

Is there any other way to post json payload from api plugin in the new versions > 4.0.1 ?
Thank you.

**Comment by tigercl** [comment]
@mtimoleon Sorry for late reply, we changed the field name of the client identifier, now the field name is called 'clientid'.

**Comment by mtimoleon** [comment]
Hello, the problem is not in `clientid` property name. The problem is in `payload` value:
```
'{
        "id": "pxx",
        "name": "pxx-postman",
        "dateIssued": "{{timestamp}}",
        "dataType": "json",
        "data": {
        	"userId":"6d079ab3-a985-3dc7-8086-3dc32dc08cb9",
        	"operationId":1
        }
      }'
```
You see, using single quotes to pass the object was working with versions prior 4.0.2 . Now it is not working. Broker responds with bad request.

**Comment by tigercl** [comment]
@mtimoleon Sorry for the inconvenience, but this data is originally invalid Json, you should use the following format:
```
{
    "payload": "{\"id\": \"pxx\"}"
}
```

**Comment by mtimoleon** [comment]
@tigercl Thank you it is working this way. Do you thing there is a chance to implement it accepting a json as payload? Something like this:
```
 {
"payload": {"id":"pxx"}
}
```
It would be very convenient for developers posting messages from postman and similar tools. Stringified json is not human easy readable.

Thank you.
