### ISSUE TITLE
Persistent conversation and offline message support

### ISSUE THREAD

**Issue by vegadvarsha30** [emqx/emqx#3529]
As per the documentation of EMQX Broker Features List (https://docs.emqx.io/broker/latest/en/introduction/checklist.html), it should provide Persistent conversation and offline message functionality.

But I tested on version 4.1.0, and it doesn't persistent messages sent and deliver them to client on subscribe.

Steps:
1) Connect client A to emqx node using Clean Session = false and MQTT 3.1.1/5.0
2) Connect client B to emqx node using Clean Session = false and MQTT 3.1.1/5.0
3) Subscribe client B to topic X
4) Client A publishes some messages to the topic X with qos = 1
5) Client B receives the messages
6) Disconnect client B
7) Client A publishes more messages to the topic X with qos = 1
8) Connect client B again with Clean Session = false and MQTT 3.1.1/5.0
9) Subscribe client B to topic X

Expected: Client B should receive messages sent in step 7
Actual: Client B doesn't receive the messages

Either my understanding about the feature is incorrect or it looks like it is Enterprise feature and not part of EMQX broker.

**Comment by tigercl** [comment]
@vegadvarsha30 Sorry for the inconvenience, these are the features of the enterprise version.

**Comment by vegadvarsha30** [comment]
Can you please amend the documentation, so others will not get confused in future.

**Comment by dwi-iwb** [comment]
Sorry but it is still unclear to me if there exists any session persistence at all in the Open Source Version.

Am I correct in my understanding that the sequenz described by @vegadvarsha30 is impossible to achieve with the 
OSS Version?

> Steps:
> 
> 1. Connect client A to emqx node using Clean Session = false and MQTT 3.1.1/5.0
> 2. Connect client B to emqx node using Clean Session = false and MQTT 3.1.1/5.0
> 3. Subscribe client B to topic X
> 4. Client A publishes some messages to the topic X with qos = 1
> 5. Client B receives the messages
> 6. Disconnect client B
> 7. Client A publishes more messages to the topic X with qos = 1
> 8. Connect client B again with Clean Session = false and MQTT 3.1.1/5.0
> 9. Subscribe client B to topic X
> 
> Expected: Client B should receive messages sent in step 7
> Actual: Client B doesn't receive the messages

My understanding of the persistence featureset of the Enterprise Version was, that it guarantes me persistence through broker restarts... but general session persistence should be possible in the OSS version as long as the broker is not restarted.
Thanks for clarification.

**Comment by zhanghongtong** [comment]
Hi, @vegadvarsha30

Sorry, we made a mistake, this is a feature included in the EMQX open source version

The MQTT 5.0 CONNECT message contains the Session Expiry Interval attribute. I want to confirm whether the interval between two connections of clinet B is less than the value of this attribute

**Comment by terry-xiaoyu** [comment]
@vegadvarsha30 I tried to reproduce the issue on v4.1.0 using the procedure you provided but failed.

Could you turn on the debug log using `emqx_ctl log set-level debug`,test it again, and post your logs here if you managed to reproduce it.

**Comment by dwi-iwb** [comment]
Thanks for the correction.

Follwing this I did some more testing.

My main setup for test is MQTT.fx on two different systems. (But I was told the other day that we are experiencing the issue on a some of our Test-IoT devices aswell.)

I followed the test sequence as describe by @vegadvarsha30 .
- Devices: `dwi-A` & `dwi-B`
- Payload: `test_message` sent while both connected, `test_message_2` send while `dwi-B` was disconnecte, `adsfafasfd233333` is a retained message

Looking into the logs, at least for me everything looks fine. MQTT.fx seems to be an unfavorbale tool for testing this.

[emqx-emqx-0-1594371953826954000.log](https://github.com/emqx/emqx/files/4902372/emqx-emqx-0-1594371953826954000.log)

**Comment by terry-xiaoyu** [comment]
We are developing our mqtt client for the reasons you mentioned, you could get it [here](https://mqttx.app).

You could submit issues at (https://github.com/emqx/MQTTX) if you get into any problem.

For your IoT devices you could always inspect the emqx debug logs to get more detailed info, or use `emqx_ctl trace` if you are on a production system that there're too many concurrent devices connected.

**Comment by vegadvarsha30** [comment]
Thanks for looking into it. Verified its working as expected.
