### ISSUE TITLE
webhook Content-Type can't bo modify 

### ISSUE THREAD

**Issue by merlinMeng** [emqx/emqx#3532]
**Environment**:
4.1
- EMQ X version (e.g. `emqx_ctl status`): 
- Hardware configuration (e.g. `lscpu`):
- OS (e.g. `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Erlang/OTP version (in case you build emqx from source code): 
- Others:

**What happened and what you expected to happen**:
I add rescoure about webhook, and when I add content-Type that is not application/json, It will overwrite to application/json.
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Comment by tigercl** [comment]
@merlinMeng Sorry for late reply. This header is fixed currently.

**Comment by merlinMeng** [comment]
It doesn't matter!.
I want to modify this fixed header value, Can you tell me which files  need modify? 
thank you

**Comment by tigercl** [comment]
@merlinMeng You can search for `application/json` in the source code of `emqx-web-hook` plugin.

**Comment by HJianBo** [comment]
Hi @merlinMeng  The `webhook` will serialize all events to a JSON string and pass it to a backend server. So the `Content-Type` is fixed as `application/json`. It is reasonable, I think.

Why are your need to override it?
