### ISSUE TITLE
MySQL ACL is not working

### ISSUE THREAD

**Issue by mntolia** [emqx/emqx#3535]
I am using EMQX 4.0.6 on Ubuntu 18

I am using the MYSQL Auth/ACL plugin for EMQX. The authentication part of it is working fine but the ACL is not working. 
This is the table:
![image](https://user-images.githubusercontent.com/10390224/84656764-d54b6300-af30-11ea-9577-7d0612b1580c.png)
The is_superuser for this user is set to 0.

Both the tables are in the same database.

With this username, I am able to subscribe to other topics beyond what I mentioned in that table. I checked the logs and it does show anything related to ACL. 

I have modified the query in the emqx_auth_mysql.conf file:
`auth.mysql.acl_query = select allow, ipaddr, username, clientid, access, topic from aliv_mqtt_acl where username = '%u' or username = '$all'`

Even then it did not work. I restarted the broker several times. What could be the issue?

**Comment by HJianBo** [comment]
Hi @mntolia There may be several reasons for this

1. ACL cache was not flushed:
    * You can reconnect it with `clean_session=true`
    * Or, disable acl_cache by `enable_acl_cache` and restart broker

2. The ACL rule from MySQL not match your Client.
    * You can modify the default rules to deny Client ACL missed, It is useful to debug your AUTH plugin. e.g:
    ```
     %% acl.conf
     {deny, all}.
    ```

**Comment by mntolia** [comment]
> Hi @mntolia There may be several reasons for this
> 
> 1. ACL cache was not flushed:
>    
>    * You can reconnect it with `clean_session=true`
>    * Or, disable acl_cache by `enable_acl_cache` and restart broker
> 2. The ACL rule from MySQL not match your Client.
>    
>    * You can modify the default rules to deny Client ACL missed, It is useful to debug your AUTH plugin. e.g:
>    
>    ```
>     %% acl.conf
>     {deny, all}.
>    ```

Thanks. I did that and it worked.
