### ISSUE TITLE
close ssl error 

### ISSUE THREAD

**Issue by yqfclid** [emqx/emqx#3538]
I use emqx 4.0.4
client hold a ssl connection with emqx
client force quit 
emqx got this
```
Unexpected info: {<0.12173.0>,ssl_close_timeout}
```
and the emqx_connection of client does not be closed and it exist in ets table emqx_channel all the time
is this a bug of emqx?

**Comment by tigercl** [comment]
@yqfclid Thank you very much for finding and reporting this issue, it is indeed a bug and we will fix it as soon as possible!

**Comment by HJianBo** [comment]
Hi, @yqfclid This `ssl_close_timeout` message has been handled in v4.1.0. It should not interfere with the closing of the connection process.  Do you set clean_session to false?

**Comment by yqfclid** [comment]
Yes, you are right, client set clean_session to No. Thanks for your help

**Comment by HJianBo** [comment]
So,  Don't worry about it. There is no error occurs. We have handled it at v4.1.0. Maybe you can try it later

Anyway, thanks for your feedback there :)
