### ISSUE TITLE
When the go language uses emqx, it can receive messages normally at first, and then it suddenly stops receiving messages after a while

### ISSUE THREAD

**Issue by 1084077463** [emqx/emqx#3539]
In the method of subscription processing, if the received content is not processed by using the cooperation procedure, the program will block after a period of time and cannot receive the message. Even if there's always news on the subject. It may be because the processing speed of the message is less than the sending speed of the data, which will cause blocking for a long time.

If this kind of data throughput is large, how to deal with the data reasonably and the report will not block?

**Comment by tigercl** [comment]
@1084077463 Adjusting the configuration of the maximum length of the message queue does not solve the fundamental problem, usually we recommend that your consumption speed matches the production speed of the message. Maybe you can have one process only receive messages, and multiple processes process messages.
