### ISSUE TITLE
emqx3.2.3  service crashed  for benchmark test, only 5000 terminals simulate

### ISSUE THREAD

**Issue by yangyongzhen** [emqx/emqx#3540]
benchmark test, only 5000 terminals simulate, emqx  service crashed
**Environment**:
Ubuntu linux 18.04 x64 virtural machine huawei yun
- EMQ X version (e.g. `emqx_ctl status`): 
emqx version；3.2.3 ，emqx_ctl status not response
- Hardware configuration (e.g. `lscpu`):
- OS (e.g. `cat /etc/os-release`):
NAME="Ubuntu"
VERSION="18.04.3 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.3 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic

- Kernel (e.g. `uname -a`):
Linux ecs-x-medium-2-linux-20200222093024 4.15.0-65-generic #74-Ubuntu SMP Tue Sep 17 17:06:04 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
- Erlang/OTP version (in case you build emqx from source code): 
just ,wget https://www.emqx.io/downloads/broker/v3.2.3/emqx-ubuntu18.04-v3.2.3_amd64.deb
sudo dpkg -i emqx-ubuntu18.04-v3.2.3_amd64.deb
- Others:

**What happened and what you expected to happen**:
just run go run main.go ,a simple goloang code to  test mqtt 
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
root@ecs-x-medium-2-linux-20200222093024:/var/log/emqx# cat emqx.log.1
2020-06-17 10:26:50.431 [error] mqtt:tcp failed to listen on 1883 - eaddrinuse (address already in use)
2020-06-17 10:26:50.431 [error] crasher:
    initial call: esockd_listener:init/1
    pid: <0.1629.0>
    registered_name: []
    exception exit: eaddrinuse
      in function  gen_server:init_it/6 (gen_server.erl, line 358)
    ancestors: [<0.1626.0>,esockd_sup,<0.1355.0>]
    message_queue_len: 0
    messages: []
    links: [<0.1626.0>]
    dictionary: []
    trap_exit: true
    status: running
    heap_size: 987
    stack_size: 27
    reductions: 5989
  neighbours:
2020-06-17 17:14:16.948 [error] nmapTWWXYLTNURFGCBUN@117.40.196.21:45349 ** State machine <0.5196.0> terminating
** Last event = {cast,
                    {incoming,
                        {mqtt_packet,
                            {mqtt_packet_header,8,false,1,false},
                            {mqtt_packet_subscribe,2,undefined,
                                [{<<"$SYS/#">>,
                                  #{nl => 0,qos => 0,rap => 0,rc => 0,
                                    rh => 0}},
                                 {<<"#">>,
                                  #{nl => 0,qos => 0,rap => 0,rc => 0,
                                    rh => 0}}]},
                            undefined}}}
** When server state  = {connected,
                            {state,esockd_transport,#Port<0.89>,
                                {{117,40,196,21},45349},
                                undefined,running,100,
                                {pstate,external,
                                    #Fun<emqx_channel.0.102180930>,
                                    {{192,168,0,70},1883},
                                    {{117,40,196,21},45349},
                                    nossl,4,<<"MQTT">>,
                                    <<"nmapTWWXYLTNURFGCBUN">>,false,
                                    <0.5196.0>,undefined,undefined,undefined,
                                    <0.5198.0>,false,#{},undefined,undefined,
                                    30,false,
                                    #{msg => 0,pkt => 1},
                                    #{msg => 0,pkt => 1},
                                    true,
                                    {1592,385256,848365},
                                    #{from_client => 0,to_client => 0},
                                    emqx_channel,
                                    #{anonymous => true,
                                      auth_result => success,
                                      client_id => <<"nmapTWWXYLTNURFGCBUN">>,
                                      mountpoint => undefined,
                                      peername => {{117,40,196,21},45349},
                                      sockname => {{192,168,0,70},1883},
                                      username => undefined,
                                      ws_cookie => undefined,zone => external},
                                    undefined},
                                {none,#{max_size => 1048576,version => 4}},
                                {emqx_gc,
                                    #{cnt => {1000,998},
                                      oct => {1048576,1048525}}},
                                {keepalive,#Fun<emqx_channel.3.102180930>,34,
                                    23,
                                    {keepalive,check},
                                    #Ref<0.2699398881.405274625.47156>,0},
                                undefined,undefined,undefined,true,
                                #Ref<0.2699398881.405274625.47146>,15000}}
** Reason for termination = error:function_clause
** Callback mode = [state_functions,state_enter]
** Stacktrace =
**  [{emqx_protocol,'-check_sub_acl/2-fun-0-',
                    [{<<"$SYS/#">>,
                      #{nl => 0,qos => 0,rap => 0,rc => 0,rh => 0}},
                     {error,[{<<"#">>,
                              #{nl => 0,qos => 0,rap => 0,rc => 135,
                                rh => 0}}]}],
                    [{file,"/emqx_temp/emqx_rel/_checkouts/emqx/src/emqx_protocol.erl"},
                     {line,906}]},
     {emqx_protocol,process,2,
                    [{file,"/emqx_temp/emqx_rel/_checkouts/emqx/src/emqx_protocol.erl"},
                     {line,505}]},
     {emqx_channel,handle_incoming,3,
                   [{file,"/emqx_temp/emqx_rel/_checkouts/emqx/src/emqx_channel.erl"},
                    {line,433}]},
     {gen_statem,call_state_function,5,[{file,"gen_statem.erl"},{line,1586}]},
     {gen_statem,loop_event_state_function,6,
                 [{file,"gen_statem.erl"},{line,967}]},
     {proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,249}]}]
2020-06-17 17:14:16.962 [error] nmapTWWXYLTNURFGCBUN@117.40.196.21:45349 crasher:
    initial call: emqx_channel:init/1
    pid: <0.5196.0>
    registered_name: []
    exception error: no function clause matching
                     emqx_protocol:'-check_sub_acl/2-fun-0-'({<<"$SYS/#">>,
                                                              #{nl => 0,
                                                                qos => 0,
                                                                rap => 0,
                                                                rc => 0,
                                                                rh => 0}},
                                                             {error,
                                                              [{<<"#">>,
                                                                #{nl => 0,
                                                                  qos => 0,
                                                                  rap => 0,
                                                                  rc => 135,
                                                                  rh => 0}}]}) (/emqx_temp/emqx_rel/_checkouts/emqx/src/emqx_protocol.erl, line 906)
      in function  emqx_protocol:process/2 (/emqx_temp/emqx_rel/_checkouts/emqx/src/emqx_protocol.erl, line 505)
      in call from emqx_channel:handle_incoming/3 (/emqx_temp/emqx_rel/_checkouts/emqx/src/emqx_channel.erl, line 433)
      in call from gen_statem:call_state_function/5 (gen_statem.erl, line 1586)
      in call from gen_statem:loop_event_state_function/6 (gen_statem.erl, line 967)
    ancestors: [<0.1609.0>,<0.1608.0>,esockd_sup,<0.1355.0>]
    message_queue_len: 1
    messages: [{'EXIT',#Port<0.89>,normal}]
    links: [<0.5198.0>,<0.1609.0>]
    dictionary: [{'$logger_metadata$',
                      #{client_id => <<"nmapTWWXYLTNURFGCBUN">>,
                        peername => "117.40.196.21:45349"}},
                  {acl_cache_size,1},
                  {acl_keys_q,{[{subscribe,<<"#">>}],[]}},
                  {force_shutdown_policy,
                      #{max_heap_size => 838860800,message_queue_len => 8000}},
                  {guid,{1592385256948596,268564305024076,1}},
                  {incoming_bytes,51},
                  {{subscribe,<<"#">>},{deny,1592385256948}}]
    trap_exit: true
    status: running
    heap_size: 17731
    stack_size: 27
    reductions: 408747
  neighbours:
2020-06-17 17:14:16.963 [error] supervisor: 'esockd_connection_sup - <0.1609.0>'
    errorContext: connection_crashed
    reason: {function_clause,
                [{emqx_protocol,'-check_sub_acl/2-fun-0-',
                     [{<<"$SYS/#">>,
                       #{nl => 0,qos => 0,rap => 0,rc => 0,rh => 0}},
                      {error,
                          [{<<"#">>,
                            #{nl => 0,qos => 0,rap => 0,rc => 135,rh => 0}}]}],
                     [{file,
                          "/emqx_temp/emqx_rel/_checkouts/emqx/src/emqx_protocol.erl"},
                      {line,906}]},
                 {emqx_protocol,process,2,
                     [{file,
                          "/emqx_temp/emqx_rel/_checkouts/emqx/src/emqx_protocol.erl"},
                      {line,505}]},
                 {emqx_channel,handle_incoming,3,
                     [{file,
                          "/emqx_temp/emqx_rel/_checkouts/emqx/src/emqx_channel.erl"},
                      {line,433}]},
                 {gen_statem,call_state_function,5,
                     [{file,"gen_statem.erl"},{line,1586}]},
                 {gen_statem,loop_event_state_function,6,
                     [{file,"gen_statem.erl"},{line,967}]},
                 {proc_lib,init_p_do_apply,3,
                     [{file,"proc_lib.erl"},{line,249}]}]}
    offender: [{pid,<0.5196.0>},
               {name,connection},
               {mfargs,{emqx_channel,start_link,
                                     [[{deflate_options,[]},
                                       {max_conn_rate,1000},
                                       {active_n,100},
                                       {zone,external}]]}}]
2020-06-17 18:23:07.378 [warning] MQTT_FX_Client@1.192.121.130:2056 [Channel] Discarded by MQTT_FX_Client:<0.6507.0>
2020-06-17 18:23:16.267 [warning] MQTT_FX_Client@1.192.121.130:2057 [Channel] Discarded by MQTT_FX_Client:<0.6514.0>
2020-06-17 18:23:28.371 [warning] MQTT_FX_Client@1.192.121.130:2058 [Channel] Discarded by MQTT_FX_Client:<0.6521.0>
2020-06-17 18:23:41.923 [warning] MQTT_FX_Client@1.192.121.130:2059 [Channel] Discarded by MQTT_FX_Client:<0.6530.0>
2020-06-17 18:23:47.690 [warning] MQTT_FX_Client@1.192.121.130:2060 [Channel] Discarded by MQTT_FX_Client:<0.6535.0>
2020-06-18 10:51:00.982 [warning] go-Subscribe-client sampï¼� 0-1592446127 [Session] The PUBACK PacketId 3799 is not found
2020-06-18 10:51:00.982 [warning] go-Subscribe-client sampï¼� 0-1592446127 [Session] The PUBACK PacketId 3800 is not found
2020-06-18 10:51:00.983 [warning] go-Subscribe-client sampï¼� 0-1592446127 [Session] The PUBACK PacketId 3801 is not found
2020-06-18 10:51:00.984 [warning] go-Subscribe-client sampï¼� 0-1592446127 [Session] The PUBACK PacketId 3802 is not found
2020-06-18 10:51:00.984 [warning] go-Subscribe-client sampï¼� 0-1592446127 [Session] The PUBACK PacketId 3803 is not found
2020-06-18 10:51:00.993 [warning] go-Subscribe-client sampï¼� 4-1592446127 [Session] The PUBACK PacketId 3794 is not found
2020-06-18 10:51:00.994 [warning] go-Subscribe-client sampï¼� 4-1592446127 [Session] The PUBACK PacketId 3795 is not found
2020-06-18 10:51:00.995 [warning] go-Subscribe-client sampï¼� 2-1592446127 [Session] The PUBACK PacketId 3799 is not found
2020-06-18 10:51:00.995 [warning] go-Subscribe-client sampï¼� 2-1592446127 [Session] The PUBACK PacketId 3800 is not found
2020-06-18 10:51:00.995 [warning] go-Subscribe-client sampï¼� 4-1592446127 [Session] The PUBACK PacketId 3796 is not found
2020-06-18 10:51:00.995 [warning] go-Subscribe-client sampï¼� 4-1592446127 [Session] The PUBACK PacketId 3797 is not found
2020-06-18 10:51:00.995 [warning] go-Subscribe-client sampï¼� 4-1592446127 [Session] The PUBACK PacketId 3798 is not found
2020-06-18 10:51:00.997 [warning] go-Subscribe-client sampï¼� 2-1592446127 [Session] The PUBACK PacketId 3801 is not found
2020-06-18 10:51:00.997 [warning] go-Subscribe-client sampï¼� 2-1592446127 [Session] The PUBACK PacketId 3802 is not found
2020-06-18 10:51:00.997 [warning] go-Subscribe-client sampï¼� 2-1592446127 [Session] The PUBACK PacketId 3803 is not found
2020-06-18 10:51:00.999 [warning] go-Subscribe-client sampï¼� 1-1592446127 [Session] The PUBACK PacketId 3799 is not found
2020-06-18 10:51:00.999 [warning] go-Subscribe-client sampï¼� 1-1592446127 [Session] The PUBACK PacketId 3800 is not found
2020-06-18 10:51:01.000 [warning] go-Subscribe-client sampï¼� 1-1592446127 [Session] The PUBACK PacketId 3801 is not found
2020-06-18 10:51:01.000 [warning] go-Subscribe-client sampï¼� 1-1592446127 [Session] The PUBACK PacketId 3802 is not found
2020-06-18 10:51:01.000 [warning] go-Subscribe-client sampï¼� 1-1592446127 [Session] The PUBACK PacketId 3803 is not found
2020-06-18 10:51:01.011 [warning] go-Subscribe-client sampï¼� 3-1592446127 [Session] The PUBACK PacketId 3794 is not found
2020-06-18 10:51:01.011 [warning] go-Subscribe-client sampï¼� 3-1592446127 [Session] The PUBACK PacketId 3795 is not found
2020-06-18 10:51:01.011 [warning] go-Subscribe-client sampï¼� 3-1592446127 [Session] The PUBACK PacketId 3796 is not found
2020-06-18 10:51:01.011 [warning] go-Subscribe-client sampï¼� 3-1592446127 [Session] The PUBACK PacketId 3797 is not found
2020-06-18 10:51:01.012 [warning] go-Subscribe-client sampï¼� 3-1592446127 [Session] The PUBACK PacketId 3798 is not found
root@ecs-x-medium-2-linux-20200222093024:/var/log/emqx#

my test code is:
package main

import (
	"flag"
	"fmt"
	"sync"
	"time"

	mqtt "github.com/eclipse/paho.mqtt.golang"
)

//创建全局mqtt publish消息处理 handler
var messagePubHandler mqtt.MessageHandler = func(client mqtt.Client, msg mqtt.Message) {
	fmt.Printf("Pub Client Topic : %s \n", msg.Topic())
	fmt.Printf("Pub Client msg : %s \n", msg.Payload())
}

//创建全局mqtt sub消息处理 handler
var messageSubHandler mqtt.MessageHandler = func(client mqtt.Client, msg mqtt.Message) {
	fmt.Printf("Sub Client Topic : %s \n", msg.Topic())
	fmt.Printf("Sub Client msg : %s \n", msg.Payload())
}

//连接失败数
var failNums = 0

/**
*
* 连接任务和发布消息方法
 */
func mqttConnPubMsgTask(taskId int, waitGroup *sync.WaitGroup) {
	defer waitGroup.Done()
	//设置连接参数
	clinetOptions := mqtt.NewClientOptions().AddBroker("tcp://121.36.253.86:1883").SetUsername("admin").SetPassword("public")
	//设置客户端ID
	clinetOptions.SetClientID(fmt.Sprintf("go-Publish-client-samp： %d-%d", taskId, time.Now().Unix()))
	//设置handler
	clinetOptions.SetDefaultPublishHandler(messagePubHandler)
	//设置连接超时
	clinetOptions.SetConnectTimeout(time.Duration(60) * time.Second)
	//创建客户端连接
	client := mqtt.NewClient(clinetOptions)

	//客户端连接判断
	if token := client.Connect(); token.WaitTimeout(time.Duration(60)*time.Second) && token.Wait() && token.Error() != nil {
		failNums++
		fmt.Printf("[Pub] mqtt connect error, taskId: %d, fail_nums: %d, error: %s \n", taskId, failNums, token.Error())
		return
	}

	i := 0

	for {
		i++
		time.Sleep(time.Duration(3) * time.Second)
		text := fmt.Sprintf("this is test msg #%d from task :%d", i, taskId)
		//fmt.Printf("start publish msg to mqtt broker, taskId: %d, count: %d \n", taskId, i)
		//发布消息
		token := client.Publish("go-test-topic", 1, false, text)
		fmt.Printf("[Pub] end publish msg to mqtt broker, taskId: %d, count: %d\n", taskId, i)
		token.Wait()
	}

	client.Disconnect(250)
	fmt.Println("[Pub] task is ok")

}

/***
*
* 连接任务和消息订阅方法
 */
func mqttConnSubMsgTask(taskId int, waitGroup *sync.WaitGroup) {
	defer waitGroup.Done()
	//设置连接参数
	clinetOptions := mqtt.NewClientOptions().AddBroker("tcp://121.36.253.86:1883").SetUsername("admin").SetPassword("public")
	//设置客户端ID
	clinetOptions.SetClientID(fmt.Sprintf("go-Subscribe-client samp： %d-%d", taskId, time.Now().Unix()))
	//设置连接超时
	clinetOptions.SetConnectTimeout(time.Duration(60) * time.Second)
	//创建客户端连接
	client := mqtt.NewClient(clinetOptions)

	//客户端连接判断
	if token := client.Connect(); token.WaitTimeout(time.Duration(60)*time.Second) && token.Wait() && token.Error() != nil {
		failNums++
		fmt.Printf("[Sub] mqtt connect error, taskId: %d, fail_nums: %d, error: %s \n", taskId, failNums, token.Error())
		return
	}

	//i := 0

	//for {
	//	i++
	time.Sleep(time.Duration(3) * time.Second)
	//fmt.Printf("start publish msg to mqtt broker, taskId: %d, count: %d \n", taskId, i)
	//发布消息
	token := client.Subscribe("go-test-topic", 1, messageSubHandler)
	fmt.Printf("[Sub] end Subscribe msg to mqtt broker, taskId: %d, count: %d \n", taskId, 1)
	token.Wait()
	//}
	select {}

	//client.Disconnect(250)
	//fmt.Println("[Sub] task is ok")

}

/***
* 创建客户端连接
 */
func main() {
	clientNum := flag.Uint64("clientNum", 5000, "client nums")
	flag.Parse()
	nums := int(*clientNum)
	waitGroup := sync.WaitGroup{}

	for i := 0; i < nums; i++ {
		fmt.Printf("client num : %s \n", i)
		waitGroup.Add(1)
		time.Sleep(3 * time.Millisecond)
		//调用连接和发布消息
		go mqttConnPubMsgTask(i, &waitGroup)
		//订阅
		go mqttConnSubMsgTask(i, &waitGroup)
	}

	waitGroup.Wait()
}

**Comment by tigercl** [comment]
@yangyongzhen I see the first few lines of the log show that the port 1883 is already occupied.

**Comment by yangyongzhen** [comment]
> @tigercl ,yes,it is. the 1883 port is occupied, but the first line is not a new log. I found this problem and repaired it,then,I do the test by a simple code writen by golang. if you can do the same test,you will find the same problem

**Comment by tigercl** [comment]
@yangyongzhen It seems that the client reconnected using `Clean Session = ture`, but the new connection is still using the state of the previous connection

**Comment by HJianBo** [comment]
Hi @yangyongzhen This is indeed the crash log included a BUG. It happens when denied to subscribe to a topic. In this case, it is `$SYS/#` and `#`.

We have fixed it at v4.1.0. Maybe you can try it :)
