### ISSUE TITLE
Protocol 'ekka': register/listen error: eaddrinuse

### ISSUE THREAD

**Issue by GhostNoc** [emqx/emqx#3541]
This error occurs when I start the second emqx instance.
Protocol 'ekka': register/listen error: eaddrinuse

I already changed ports of tcp http ws wss ssl management dashboard.

one host only can start only one emqx?

**Comment by HJianBo** [comment]
Hi @GhostNoc if you want to start more emqx instance on a machine. Apart from what you mentioned, you should change the following port to listen to the RPC request
```
rpc.tcp_server_port = 5369
```

Or you can use the convenient script to create an emqx instance copy: https://github.com/terry-xiaoyu/one_more_emqx

PS: **On a single machine is only allowed to start the two instances**

**Comment by GhostNoc** [comment]
> Hi @GhostNoc if you want to start more emqx instance on a machine. Apart from what you mentioned, you should change the following port to listen to the RPC request
> 
> ```
> rpc.tcp_server_port = 5369
> ```
> 
> Or you can use the convenient script to create an emqx instance copy: https://github.com/terry-xiaoyu/one_more_emqx
> 
> PS: **On a single machine is only allowed to start the two instances**

I also modified this port ,and I started two instances separately and found that the same port occupied is 4370

**Comment by HJianBo** [comment]
You must modify the node name with a suffix. E.g: `emqx2@127.0.0.1`, or `yourname2@127.0.0.1`

**Comment by GhostNoc** [comment]
> You must modify the node name with a suffix. E.g: `emqx2@127.0.0.1`, or `yourname2@127.0.0.1`

I also modified node name. the first instance node name is `emqx@127.0.0.1`,another is `emqxtest@127.0.0.1`. The first emqx is installed with a package manager, the second is installed with zip

**Comment by HJianBo** [comment]
Hammm.. it must be a numeric suffix

**Comment by GhostNoc** [comment]
> Hammm.. it must be a numeric suffix



> Hammm.. it must be a numeric suffix

I am extremely grateful you，this way is working
