### ISSUE TITLE
docker-build fail 

### ISSUE THREAD

**Issue by LvCodeing** [emqx/emqx#3543]
DOCKER BUILD: Build Docker image.
DOCKER BUILD: build version -> v3.4.3.
DOCKER BUILD: build from -> .
DOCKER BUILD: arch - amd64.
DOCKER BUILD: qemu arch - x86_64.
DOCKER BUILD: docker repo - emqx/emqx
DOCKER BUILD: emqx name - emqx.
DOCKER BUILD: emqx version - v3.4.3.
## Prepare qemu to build images other then x86_64 on travis
PREPARE: Qemu
Setting /usr/bin/qemu-alpha-static as binfmt interpreter for alpha
Setting /usr/bin/qemu-arm-static as binfmt interpreter for arm
Setting /usr/bin/qemu-armeb-static as binfmt interpreter for armeb
Setting /usr/bin/qemu-sparc-static as binfmt interpreter for sparc
Setting /usr/bin/qemu-sparc32plus-static as binfmt interpreter for sparc32plus
Setting /usr/bin/qemu-sparc64-static as binfmt interpreter for sparc64
Setting /usr/bin/qemu-ppc-static as binfmt interpreter for ppc
Setting /usr/bin/qemu-ppc64-static as binfmt interpreter for ppc64
Setting /usr/bin/qemu-ppc64le-static as binfmt interpreter for ppc64le
Setting /usr/bin/qemu-m68k-static as binfmt interpreter for m68k
Setting /usr/bin/qemu-mips-static as binfmt interpreter for mips
Setting /usr/bin/qemu-mipsel-static as binfmt interpreter for mipsel
Setting /usr/bin/qemu-mipsn32-static as binfmt interpreter for mipsn32
Setting /usr/bin/qemu-mipsn32el-static as binfmt interpreter for mipsn32el
Setting /usr/bin/qemu-mips64-static as binfmt interpreter for mips64
Setting /usr/bin/qemu-mips64el-static as binfmt interpreter for mips64el
Setting /usr/bin/qemu-sh4-static as binfmt interpreter for sh4
Setting /usr/bin/qemu-sh4eb-static as binfmt interpreter for sh4eb
Setting /usr/bin/qemu-s390x-static as binfmt interpreter for s390x
Setting /usr/bin/qemu-aarch64-static as binfmt interpreter for aarch64
Setting /usr/bin/qemu-aarch64_be-static as binfmt interpreter for aarch64_be
Setting /usr/bin/qemu-hppa-static as binfmt interpreter for hppa
Setting /usr/bin/qemu-riscv32-static as binfmt interpreter for riscv32
Setting /usr/bin/qemu-riscv64-static as binfmt interpreter for riscv64
Setting /usr/bin/qemu-xtensa-static as binfmt interpreter for xtensa
Setting /usr/bin/qemu-xtensaeb-static as binfmt interpreter for xtensaeb
Setting /usr/bin/qemu-microblaze-static as binfmt interpreter for microblaze
Setting /usr/bin/qemu-microblazeel-static as binfmt interpreter for microblazeel
Setting /usr/bin/qemu-or1k-static as binfmt interpreter for or1k
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   636  100   636    0     0    357      0  0:00:01  0:00:01 --:--:--   357
100 1630k  100 1630k    0     0  24935      0  0:01:06  0:01:06 --:--:-- 22489
/home/dev/services/emqx-rel/deploy/docker
Sending build context to Docker daemon  140.1MB
Step 1/25 : ARG BUILD_FROM=erlang:21.3.6-alpine
Step 2/25 : ARG RUN_FROM=alpine:3.9
Step 3/25 : FROM ${BUILD_FROM} AS builder
 ---> beb062f80d99
Step 4/25 : ARG QEMU_ARCH=x86_64
 ---> Running in c8e45e58c65c
Removing intermediate container c8e45e58c65c
 ---> ce2e8296ec05
Step 5/25 : COPY deploy/docker/tmp/qemu-$QEMU_ARCH-stati* /usr/bin/
 ---> 773128b899d2
Step 6/25 : COPY . /emqx_rel
 ---> 89254e408833
Step 7/25 : RUN apk add git     curl     gcc     make     perl     ncurses-dev     openssl-dev     coreutils     bsd-compat-headers     libc-dev
 ---> Running in 71eda55f17d1
fetch http://dl-cdn.alpinelinux.org/alpine/v3.9/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.9/community/x86_64/APKINDEX.tar.gz
(1/29) Installing bsd-compat-headers (0.7.1-r0)
(2/29) Installing libattr (2.4.47-r7)
(3/29) Installing libacl (2.2.52-r5)
(4/29) Installing coreutils (8.30-r0)
(5/29) Installing nghttp2-libs (1.35.1-r2)
(6/29) Installing libssh2 (1.9.0-r1)
(7/29) Installing libcurl (7.64.0-r3)
(8/29) Installing curl (7.64.0-r3)
(9/29) Installing binutils (2.31.1-r2)
(10/29) Installing gmp (6.1.2-r1)
(11/29) Installing isl (0.18-r0)
(12/29) Installing libgomp (8.3.0-r0)
(13/29) Installing libatomic (8.3.0-r0)
(14/29) Installing libgcc (8.3.0-r0)
(15/29) Installing mpfr3 (3.1.5-r1)
(16/29) Installing mpc1 (1.0.3-r1)
(17/29) Installing libstdc++ (8.3.0-r0)
(18/29) Installing gcc (8.3.0-r0)
(19/29) Installing expat (2.2.8-r0)
(20/29) Installing pcre2 (10.32-r1)
(21/29) Installing git (2.20.4-r0)
(22/29) Installing musl-dev (1.1.20-r5)
(23/29) Installing libc-dev (0.7.1-r0)
(24/29) Installing make (4.2.1-r2)
(25/29) Installing pkgconf (1.6.0-r0)
(26/29) Installing ncurses-dev (6.1_p20190105-r0)
(27/29) Installing openssl-dev (1.1.1g-r0)
(28/29) Installing libbz2 (1.0.6-r7)
(29/29) Installing perl (5.26.3-r1)
Executing busybox-1.29.3-r10.trigger
OK: 185 MiB in 51 packages
Removing intermediate container 71eda55f17d1
 ---> f432e84bf1b4
Step 8/25 : ARG EMQX_DEPS_DEFAULT_VSN=develop
 ---> Running in 280f95a0e4e5
Removing intermediate container 280f95a0e4e5
 ---> e55dd8dcc385
Step 9/25 : ARG EMQX_NAME=emqx
 ---> Running in 529c07a538eb
Removing intermediate container 529c07a538eb
 ---> e934c32a0f05
Step 10/25 : RUN cd /emqx_rel && make ${EMQX_NAME}
 ---> Running in 52fb0ca9de25
ln -snf _build/emqx/lib ./_checkouts
/emqx_rel/rebar3 as emqx release
===> Plugin rebar3_run not available. It will not be used.
=ERROR REPORT==== 19-Jun-2020::07:39:04.887210 ===
Loading of /emqx_rel/_build/default/plugins/rebar3_run/ebin/rebar3_run.beam failed: badfile

=ERROR REPORT==== 19-Jun-2020::07:39:04.887202 ===
beam/beam_load.c(1878): Error loading module rebar3_run:
  This BEAM file was compiled for a later version of the run-time system than 21.
  To fix this, please recompile this module with an 21 compiler.
  (Use of opcode 164; this emulator supports only up to 163.)

===> Verifying dependencies...
===> Compiling jsx
===> Failed to restore /emqx_rel/_checkouts/jsx/.rebar3/rebar_compiler_erl/source.dag file. Discarding it.

===> Compiling coveralls
===> Failed to restore /emqx_rel/_build/default/plugins/coveralls/.rebar3/rebar_compiler_erl/source.dag file. Discarding it.

===> "/emqx_rel/_checkouts/mysql/ebin/mysql.app" is missing kernel from applications list
===> "/emqx_rel/_checkouts/mysql/ebin/mysql.app" is missing stdlib from applications list
=ERROR REPORT==== 19-Jun-2020::07:39:06.167984 ===
Loading of /emqx_rel/_build/default/plugins/rebar3_proper/ebin/rebar3_proper_prv.beam failed: badfile

=ERROR REPORT==== 19-Jun-2020::07:39:06.167975 ===
beam/beam_load.c(1878): Error loading module rebar3_proper_prv:
  This BEAM file was compiled for a later version of the run-time system than 21.
  To fix this, please recompile this module with an 21 compiler.
  (Use of opcode 164; this emulator supports only up to 163.)

===> Failed creating providers. Run with DEBUG=1 for stacktrace or consult rebar3.crashdump.
make: *** [Makefile:51: emqx] Error 1
The command '/bin/sh -c cd /emqx_rel && make ${EMQX_NAME}' returned a non-zero code: 2
Makefile:38: recipe for target 'build' failed
make[1]: *** [build] Error 2
make[1]: Leaving directory '/home/dev/services/emqx-rel/deploy/docker'
Makefile:114: recipe for target 'emqx-docker-build' failed
make: *** [emqx-docker-build] Error 2

**Comment by xyz361** [comment]
@zhanghongtong Rory Z help~

**Comment by spring2maz** [comment]
```
/emqx_rel/_build/default/plugins/rebar3_run/ebin/rebar3_run.beam failed: badfile
```
```
This BEAM file was compiled for a later version of the run-time system than 21.
````

This 2 errors make me wonder if `_build` directory preexisted before building docker image.
Maybe try deleting `_build` dir and try again.

**Comment by zhanghongtong** [comment]
Hi, @xyz361 
Has this issue been solved?

**Comment by xyz361** [comment]
I have to see if this problem is solved . @zhanghongtong 
Hi,@LvCodeing 
Has this issue been solved?

**Comment by zhanghongtong** [comment]
@xyz361 Please run `make distclean` and retry `make emqx-docker-build`

**Comment by LvCodeing** [comment]
> I have to see if this problem is solved . @zhanghongtong
> Hi,@LvCodeing
> Has this issue been solved?

Hi，Everybody，It seems that the problem still exists。

**Comment by zhanghongtong** [comment]
Hi, @LvCodeing 
Are you using our [emqx-rel v3.4.3](https://github.com/emqx/emqx-rel/tree/v3.4.3/deploy/docker) code to build? Are there any changes? I just built it again, it is normal

**Comment by LvCodeing** [comment]
> Hi, @LvCodeing
> Are you using our [emqx-rel v3.4.3](https://github.com/emqx/emqx-rel/tree/v3.4.3/deploy/docker) code to build? Are there any changes? I just built it again, it is normal

OS: Ubuntu 16.04
Erlang/OTP 22 [erts-10.7] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1] [hipe]

Because the v3.4.3 version is not maintained, I have tested it in the v4.1.1 version. The make operation is normal, but the make docker operation fails:

sudo make emqx-docker-build
/home/dev/Documents/work/v4.1/emqx-rel/rebar3 as emqx get-deps
escript: Not an archive file
Makefile:75: recipe for target 'deps-emqx' failed
make: *** [deps-emqx] Error 127

**Comment by zhanghongtong** [comment]
@LvCodeing After `make`, you need to `make distclean` first and then `make emqx-docker-build`

**Comment by LvCodeing** [comment]
> @LvCodeing After `make`, you need to `make distclean` first and then `make emqx-docker-build`

According to your steps, it is indeed successful, that is, it is slow to make docker and not easy to succeed.
