### ISSUE TITLE
Haproxy backend can't connect wss port 8084

### ISSUE THREAD

**Issue by loik620** [emqx/emqx#3545]
Environment
OS:
Distributor ID: CentOS
Description: CentOS 7.8

EMQX: 3.2.3

Description:
For load balance EMQ cluster,I use the haproxy connect EMQ. 
First,I use the sign-self CA through browser to verification EMQ's wss port(8084), then connect to  wss://mymqtt:8084/mqtt totally no problem.
Second,I add haproxy  at the first line,backend connect to Emq ws port 8083, adding the ssl and crt parameters to a bind line in a frontend section ,then connect the haproxy port 1994 also perfect.

And the issue is come about connect false,When haproxy backend connect to Emq wss port,it will show "Connect failed onmymqtt:1994". I'm no ideal how to verification between haproxy and EMQ wws.

Can somebody please help to solve this problem,Thanks~

**Comment by spring2maz** [comment]
Hi @loik620 
Is your HAproxy configured to work at layer 7 and terminate TLS, hence forwarding to ws port 8083?
Or is your HAproxy configured to work at layer 4? in this case, HAproxy should require no certificate.
Or (which would sound odd) is it to work at layer 7, and re-encrypt towards EMQX wss port ?

**Comment by loik620** [comment]
HI @spring2maz 

thanks for your respond, My haproxy config is setting mode http in frontend ,the backend I did't set any one.
My another question about normal architecture, how to config the haproy+emq with wss?

here is my haproxy config :
##### Emq server with WWS frontend config #####
frontend EMQ_Stag_wws
    bind *:1994 ssl crt /etc/haproxy/certs/emqx.pem 
    mode http
    default_backend EMQ_Stag_wws_backend


# EMQ server portocal with HTTPs backend config
backend EMQ_Stag_wws_backend
    #mod http
    balance roundrobin
    #cookie emq-stag insert indirect nocache
    server Mqtt00_wss mymqtt:8084 
    server Mqtt01_wss mymqtt:8084 
    server Mqtt02_wss mymqtt:8084 



 I'm looking forward the respond! Many thanks

**Comment by spring2maz** [comment]
A typical setup on layer 7 is for HAproxy to terminate TLS.
`Client --(https)--> HAproxy --(http)--> Backend.`
In this setup, TLS handshake is between `Client` and `HAproxy`, and `Backend` should be a plaintext TCP listener (http).
Meaning, if you are to follow this practice, you should try to configure with `ws` port (not `wss`)

I am not quite familiar with HAproxy configuration though.
But I guess, even if this is not what you wanted, you can try to start from there.
i.e. try to make HAproxy work with `ws` port.
This will be the base to work on top if after all you need encryption between HAproxy and Backend.
Does this sound like something for you worth trying ?

**Comment by loik620** [comment]
Hi @spring2maz

Thanks your reply! It already work on your suggest then backend connect to ws port(8083).
And got many confuse how to encrypt between haproxy and emq, should I setting any emqx config about wss?
Whether the haproxy need take CA to backend verify wss, or wss can catch frontend ca direct?

**Comment by spring2maz** [comment]
Hi @loik620 
It is a common practice for HAproxy to terminate TLS.
However, if you indeed need encryption between HAproxy and backend, there are two options.
1. Make HAproxy work at layer 4, then it does not know anything about TLS/SSL, everything is TCP to it
e.g. https://www.digitalocean.com/community/tutorials/how-to-use-haproxy-as-a-layer-4-load-balancer-for-wordpress-application-servers-on-ubuntu-14-04
2. Configure HAproxy to re-encrypt towards backend
e.g. https://serverfault.com/questions/738045/haproxy-to-terminate-ssl-also-send-ssl-to-backend-server

A disclaimer though: I have no experience in running HAproxy.

Whether or not HAproxy should verify EMQX's server certificate, is, I believe configurable (e.g. `verify none` in the above example)
Whether or not EMQX should verify HAproxy's client certificate is also configurable.
set `listener.ssl.external.verify = verify_none` to have it disabled.

**Comment by loik620** [comment]
Hi @spring2maz 

Many thanks for your option!
I'm try the method 2.) Awesome! it can work for me,

and the solution just only for haproxy backend config, the setting  "ssl verify none" let haproxy doesn't verify to wss,
It make me confused whether encrypt between haproxy and wss port ?

Thanks for your reply!

**Comment by spring2maz** [comment]
Once TLS handshake is successful, traffic between the peers is always encrypted.
Certificate verification is to check if the peer is who they claim to be (i.e. trusted or not)
to avoid for example man-in-the-middle attack.
You may find articles like this one https://geekflare.com/tls-101/ helpful to understand how TLS works.

In case you need full security, the easiest way to go is to have all nodes' (client, HAproxy and EMQX)
certificates issued by the same CA, then import this CA to operating system's trust collection.

Here is an article which demos how to import certificate in various different operating systems:
https://manuals.gfi.com/en/kerio/connect/content/server-configuration/ssl-certificates/adding-trusted-root-certificates-to-the-server-1605.html
