### ISSUE TITLE
The connect keepalive timeout spent more than expected.

### ISSUE THREAD

**Issue by AylaAsia-GaryJin** [emqx/emqx#3547]
**Environment**:
zone.external.keepalive_backoff = 0.75
zone.external.server_keepalive = 60
- EMQ X version (e.g. `emqx_ctl status`):  4.0.5
- Hardware configuration (e.g. `lscpu`):
- OS (e.g. `cat /etc/os-release`): Ubuntu 16.04
- Kernel (e.g. `uname -a`):
- Erlang/OTP version (in case you build emqx from source code):  22.1-alpine
- Others:

**What happened and what you expected to happen**:
 When client stop sent PINGREQ to the broker, the broker should kick out client in 90s (keepalive * backoff * 2) according to your given configuration, but it spent about 140s.
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Comment by tigercl** [comment]
@AylaAsia-GaryJin Due to some historical reasons, at present, we have made a very accurate check. When the client does not send a packet, the actual time range of disconnection is between Keepalive * Backoff * 2 and Keepalive * Backoff * 3.

**Comment by Panl99** [comment]
I would like to know which versions this issue affects as I also ran into this issue, V4.3.5
