### ISSUE TITLE
EMQX_MQTT__CACHE_ACL is not found for setting mqtt.cache_acl = true

### ISSUE THREAD

**Issue by jayaraj** [emqx/emqx#3549]
**Environment**: Docker emqx/emqx

- EMQ X version (e.g. `emqx_ctl status`):
Node 'emqx@192.168.192.5' is started
emqx 4.1.0 is running

- Hardware configuration (e.g. `lscpu`):
Architecture:        x86_64
CPU op-mode(s):      32-bit, 64-bit
Byte Order:          Little Endian
Address sizes:       46 bits physical, 48 bits virtual
CPU(s):              1
On-line CPU(s) list: 0
Thread(s) per core:  1
Core(s) per socket:  1
Socket(s):           1
NUMA node(s):        1
Vendor ID:           GenuineIntel
CPU family:          6
Model:               63
Model name:          Intel(R) Xeon(R) CPU @ 2.30GHz
Stepping:            0
CPU MHz:             2300.000
BogoMIPS:            4600.00
Hypervisor vendor:   KVM
Virtualization type: full
L1d cache:           32K
L1i cache:           32K
L2 cache:            256K
L3 cache:            46080K
NUMA node0 CPU(s):   0
Flags:               fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx pdpe1gb rdtscp lm constant_tsc rep_good nopl xtopology nonstop_tsc cpuid tsc_known_freq pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt aes xsave avx f16c rdrand hypervisor lahf_lm abm invpcid_single pti ssbd ibrs ibpb stibp fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid xsaveopt arat md_clear arch_capabilities

- OS (e.g. `cat /etc/os-release`):
PRETTY_NAME="Debian GNU/Linux 10 (buster)"
NAME="Debian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

- Kernel (e.g. `uname -a`):
Linux 15fe70527bf4 4.19.0-9-cloud-amd64 #1 SMP Debian 4.19.118-2 (2020-04-29) x86_64 Linux
- Erlang/OTP version (in case you build emqx from source code): 
- Others:

**What happened and what you expected to happen**:
I am not to set mqtt.cache_acl = true, If try to update config it restarts. i would like to know how to stop acl validation more than once for auth.http.acl_req.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Comment by zhanghongtong** [comment]
Hi, @jayaraj 
We don't have `mqtt.cache_acl`, so I guess you can check and edit  `enable_acl_cache`

**Comment by jayaraj** [comment]
Hi,

This Document is referring to that issue  https://docs.emqx.io/tutorial/latest/en/security/acl.html

ACL Cache
## Whether to cache ACL rules. After setting the cache,it can speed up the acquisition of ACL records.
mqtt.cache_acl = true
Copy
After the ACL rule is matched, it will have a cache in the memory to avoid accessing the external storage device when the ACL needs to be verified next time, thus speeding up the access. The cache of the ACL in the memory is valid only during the period when the connection is established and exists. If the connection is disconnected, the ACL information corresponding to the connection is deleted. The user can delete the ACL information through the REST API provided by EMQ X.

**Comment by jayaraj** [comment]
enable_acl_cache = on  is not working. I am getting acl validation request for every msg published

**Comment by zhanghongtong** [comment]
> Hi,
> 
> This Document is referring to that issue https://docs.emqx.io/tutorial/latest/en/security/acl.html
> 
> ACL Cache
> ## Whether to cache ACL rules. After setting the cache,it can speed up the acquisition of ACL records.
> 
> mqtt.cache_acl = true
> Copy
> After the ACL rule is matched, it will have a cache in the memory to avoid accessing the external storage device when the ACL needs to be verified next time, thus speeding up the access. The cache of the ACL in the memory is valid only during the period when the connection is established and exists. If the connection is disconnected, the ACL information corresponding to the connection is deleted. The user can delete the ACL information through the REST API provided by EMQ X.

This is our document error, thank you for correcting us.
CC @wivwiv Please update the document

**Comment by jayaraj** [comment]
What about Caching Valid ACL Sessions . enable_acl_cache = on is not working

**Comment by zhanghongtong** [comment]
> What about Caching Valid ACL Sessions . enable_acl_cache = on is not working

CC @terry-xiaoyu

**Comment by terry-xiaoyu** [comment]
@jayaraj Hi.

Please also set `acl_nomatch` to `deny`.

If that does not work, you could verify if your settings are taking effect by attaching to the erlang shell:

1. attach into your docker container

2. ./bin/emqx attach 

3. `emqx_acl_cache:is_enabled().`
`true`

4. `emqx_zone:get_env(external, acl_nomatch).`
`deny`

5. If you want to exit the shell, **DO NOT** `Ctrl + C`. Press `Ctl + D`. 

If the 3rd and 4th steps return the correct value as shown above, then your have correctly configured the acl. In this case you could trace the code. Again attach to the erlang shell:

```
dbg:tracer(), dbg:p(all, c), dbg:tp(emqx_acl_cache, get_acl_cache, '_', cx).
```

After this you publish messages and there should be some printsout in the erlang shell, if the acl cache function was triggered.

**Comment by jayaraj** [comment]
/opt/emqx $ ./bin/emqx attach
Attaching to //opt/emqx/data/emqx_erl_pipes/emqx@192.168.192.5/erlang.pipe.2 (^D to exit)

^Lemqx_acl_cache:is_enabled().
true
(emqx@192.168.192.5)2> emqx_zone:get_env(external, acl_nomatch).
deny
(emqx@192.168.192.5)3> [Quit]
/opt/emqx $ exit

/opt/emqx $ ./bin/emqx attach
Attaching to //opt/emqx/data/emqx_erl_pipes/emqx@192.168.192.5/erlang.pipe.2 (^D to exit)

^L(<0.1813.0>) call emqx_acl_cache:get_acl_cache(publish,<<"tower/FFFE9C65F92DD3E1/3831373671386115/event">>) ({emqx_access_control,
                                                                                                              check_acl_cache,
                                                                                                              3})
(emqx@192.168.192.5)4> (<0.1813.0>) returned from emqx_acl_cache:get_acl_cache/2 -> allow
(emqx@192.168.192.5)4> (<0.1813.0>) call emqx_acl_cache:get_acl_cache(publish,<<"tower/FFFE9C65F92DD3E1/3831373671386115/data">>) ({emqx_access_control,
                                                                                                             check_acl_cache,
                                                                                                             3})
(emqx@192.168.192.5)4> (<0.1813.0>) returned from emqx_acl_cache:get_acl_cache/2 -> allow
(emqx@192.168.192.5)4> (<0.1813.0>) call emqx_acl_cache:get_acl_cache(publish,<<"tower/FFFE9C65F92DD3E1/3831373671386115/event">>) ({emqx_access_control,
                                                                                                              check_acl_cache,
                                                                                                              3})
(emqx@192.168.192.5)4> (<0.1813.0>) returned from emqx_acl_cache:get_acl_cache/2 -> allow
(emqx@192.168.192.5)4> (<0.1813.0>) call emqx_acl_cache:get_acl_cache(publish,<<"tower/FFFE9C65F92DD3E1/3831373671386115/data">>) ({emqx_access_control,
                                                                                                             check_acl_cache,
                                                                                                             3})
(emqx@192.168.192.5)4> (<0.1813.0>) returned from emqx_acl_cache:get_acl_cache/2 -> allow
(emqx@192.168.192.5)4> (<0.1813.0>) call emqx_acl_cache:get_acl_cache(publish,<<"tower/FFFE9C65F92DD3E1/3332323355386a0a/event">>) ({emqx_access_control,
                                                                                                              check_acl_cache,
                                                                                                              3})
(emqx@192.168.192.5)4> (<0.1813.0>) returned from emqx_acl_cache:get_acl_cache/2 -> not_found
(emqx@192.168.192.5)4> (<0.1813.0>) call emqx_acl_cache:get_acl_cache(publish,<<"tower/FFFE9C65F92DD3E1/3332323355386a0a/data">>) ({emqx_access_control,
                                                                                                             check_acl_cache,
                                                                                                             3})
(emqx@192.168.192.5)4> (<0.1813.0>) returned from emqx_acl_cache:get_acl_cache/2 -> not_found
(emqx@192.168.192.5)4> (<0.1813.0>) call emqx_acl_cache:get_acl_cache(publish,<<"tower/FFFE9C65F92DD3E1/3831373671386115/event">>) ({emqx_access_control,
                                                                                                              check_acl_cache,
                                                                                                              3})
(emqx@192.168.192.5)4> (<0.1813.0>) returned from emqx_acl_cache:get_acl_cache/2 -> allow
(emqx@192.168.192.5)4> (<0.1813.0>) call emqx_acl_cache:get_acl_cache(publish,<<"tower/FFFE9C65F92DD3E1/3831373671386115/data">>) ({emqx_access_control,
                                                                                                             check_acl_cache,
                                                                                                             3})
(emqx@192.168.192.5)4> (<0.1813.0>) returned from emqx_acl_cache:get_acl_cache/2 -> allow
(emqx@192.168.192.5)4> (<0.1813.0>) call emqx_acl_cache:get_acl_cache(publish,<<"tower/FFFE9C65F92DD3E1/3332323355386a0a/event">>) ({emqx_access_control,
                                                                                                              check_acl_cache,
                                                                                                              3})
(emqx@192.168.192.5)4> (<0.1813.0>) returned from emqx_acl_cache:get_acl_cache/2 -> allow
(emqx@192.168.192.5)4> (<0.1813.0>) call emqx_acl_cache:get_acl_cache(publish,<<"tower/FFFE9C65F92DD3E1/3332323355386a0a/data">>) ({emqx_access_control,
                                                                                                             check_acl_cache,
                                                                                                             3})
(emqx@192.168.192.5)4> (<0.1813.0>) returned from emqx_acl_cache:get_acl_cache/2 -> allow
(emqx@192.168.192.5)4>

**Comment by jayaraj** [comment]
Any updates on this issue. Is there any configuration i have missed.
