### ISSUE TITLE
Bridge disconnects after sending a message that has no matching subscribers

### ISSUE THREAD

**Issue by fuegas** [emqx/emqx#3553]
**Environment**:

- EMQ X version (e.g. `emqx_ctl status`): 4.0.7

- Hardware configuration (e.g. `lscpu`):
```
Architecture:        x86_64
CPU op-mode(s):      32-bit, 64-bit
Byte Order:          Little Endian
Address sizes:       46 bits physical, 48 bits virtual
CPU(s):              2
On-line CPU(s) list: 0,1
Thread(s) per core:  1
Core(s) per socket:  1
Socket(s):           2
NUMA node(s):        1
Vendor ID:           GenuineIntel
CPU family:          6
Model:               85
Model name:          Intel(R) Xeon(R) Gold 5218 CPU @ 2.30GHz
Stepping:            7
CPU MHz:             2300.033
BogoMIPS:            4600.06
Hypervisor vendor:   Xen
Virtualization type: full
L1d cache:           32K
L1i cache:           32K
L2 cache:            1024K
L3 cache:            22528K
NUMA node0 CPU(s):   0,1
Flags:               fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush acpi mmx fxsr sse sse2 ss ht syscall nx pdpe1gb rdtscp lm constant_tsc rep_good nopl cpuid pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch cpuid_fault invpcid_single pti intel_ppin ssbd ibrs ibpb stibp fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm mpx rdseed adx smap clflushopt clwb xsaveopt xsavec xgetbv1 xsaves pku ospke md_clear flush_l1d
```

- OS (e.g. `cat /etc/os-release`):
```
PRETTY_NAME="Debian GNU/Linux 10 (buster)"
NAME="Debian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```

- Kernel (e.g. `uname -a`):
```
4.19.0-8-amd64 #1 SMP Debian 4.19.98-1 (2020-01-26) x86_64 GNU/Linux
```

We're using a bridge between two clusters (both running EMQX 4.0.7) to forward messages. However, when it sends a message the bridge stops working and raises the following error:
```
(emqx@172.31.164.18)1> 2020-06-22 12:51:50.211 [info] [Bridge] Bridge emqx_bridge_worker_NAME diconnected
reason={puback_error_code,16}
(emqx@172.31.164.18)1> 2020-06-22 12:51:50.211 [error] ** State machine <0.1983.0> terminating
** Last event = {cast,{mqtt_packet,{mqtt_packet_header,4,false,0,false},
                                   {mqtt_packet_puback,2,16,#{}},
                                   undefined}}
```

So, the reason given is: `{puback_error_code,16}`. When we take a look at the source code handling the puback:

```erlang
handle_puback(Parent, #{packet_id := PktId, reason_code := RC}) ->
    RC =:= ?RC_SUCCESS orelse error({puback_error_code, RC}),
    Parent ! {batch_ack, PktId},
    ok.
```
It matches `RC` to `RC_SUCCESS` and must match type and value. The definition for `RC_SUCCESS` is:
```erlang
-define(RC_SUCCESS,                                16#00).
...
-define(RC_NO_MATCHING_SUBSCRIBERS,                16#10).
```
From the error code we receive a `RC_NO_MATCHING_SUBSCRIBERS`. 

My question is: should a message with no matching subscribes disconnect a forwarding bridge and stop it from working at all?

If we try to restart the bridge, it sees some messages need to be forwarded, receives the `RC_NO_MATCHING_SUBSCRIBERS` code and disconnects the bridge again. How can we resolve this issue?

**Comment by tigercl** [comment]
@fuegas I'm sorry it took so long to get back to you because we were on vacation. This is indeed a bug and we will fix it as soon as possible.

**Comment by fuegas** [comment]
Hi @tigercl, thanks for the reply, we'll await the update.

**Comment by fuegas** [comment]
I just noticed the bug is added to the 4.1.1 milestone, but we've reported it for 4.0.7. Can you make the fix available in the 4.0.X series as well please?

**Comment by turtleDeng** [comment]
Hi guys, the v4.1.1 has released. Plz try it

**Comment by fuegas** [comment]
Hi @turtleDeng, as requested, will this be backported to 4.0.X? If so, we test a new version easily, else we'll need to upgrade and change our provision first.

**Comment by HJianBo** [comment]
Sorry @fuegas , The 4.1.x is not compatible wit 4.0.x directly. Maybe you should modify some confs for upgrading to v4.1.1 from 4.0.x.
