### ISSUE TITLE
No $SYS Topics

### ISSUE THREAD

**Issue by louisburton** [emqx/emqx#3555]
Hi, I have a 3 node cluster of EMQ X Broker (Docker 3.2.3) deployed to AWS ECS (via DNS). 
When I subscribe to `$SYS/brokers` on this cluster I have no brokers. Shouldn't it at least give itself as a node?
When I subscribe in the same way to my old single node on an EC2 instance (Docker 2.3.9) the topic responds fine. 
I can confirm the ACL server responds with the connection being authorized, config is identical to the old server.

The cluster does work.
The Dashboard successfully shows me the nodes.
<img width="1439" alt="dashboard" src="https://user-images.githubusercontent.com/5257921/85782257-5cad8900-b71e-11ea-847c-6d0f82963348.png">

The REST API successfully shows me the nodes.
```
curl --basic -u id:pw -k http://mqtt.platform.eu-west-1.mycloud:8080/api/v3/brokers
| jq '.'
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   672  100   672    0     0  11267      0 --:--:-- --:--:-- --:--:-- 11389
{
  "code": 0,
  "data": [
    {
      "datetime": "2020-06-25 19:01:47",
      "node": "mqttcluster@10.17.18.59",
      "node_status": "Running",
      "otp_release": "R21/10.3.5.4",
      "sysdescr": "EMQ X Broker",
      "uptime": "62 days,11 hours, 21 minutes, 44 seconds",
      "version": "3.2.3"
    },
    {
      "datetime": "2020-06-25 19:01:47",
      "node": "mqttcluster@10.17.34.206",
      "node_status": "Running",
      "otp_release": "R21/10.3.5.4",
      "sysdescr": "EMQ X Broker",
      "uptime": "62 days,11 hours, 22 minutes, 35 seconds",
      "version": "3.2.3"
    },
    {
      "datetime": "2020-06-25 19:01:47",
      "node": "mqttcluster@10.17.39.136",
      "node_status": "Running",
      "otp_release": "R21/10.3.5.4",
      "sysdescr": "EMQ X Broker",
      "uptime": "62 days,11 hours, 22 minutes, 51 seconds",
      "version": "3.2.3"
    }
  ]
}
```
The `$SYS` topics do not.
```
mqttcli sub -t '$SYS/brokers' --d --host mqtt.platform.eu-west-1.mycloud --port 1883
INFO[0000] Broker URI: tcp://mqtt.platform.eu-west-1.mycloud:1883
INFO[0000] Topic: $SYS/brokers
INFO[0000] connecting...
INFO[0000] client connected
```
I have tried connecting directly to the IP of each node in the cluster too, but get the same behaviour of no response.
The same thing to my old retired standalone node gives an expected response of :
```
INFO[0000] client connected
INFO[0000] topic:$SYS/brokers / msg:8779e30c9db9@172.18.0.3
8779e30c9db9@172.18.0.3
```
Other CLI clients don't even connect to the `$SYS/brokers` topic.
The Websocket Tool in the dashboard will subscribe to topics listed in the dashboard fine, but it won't subscribe to `$SYS/brokers` which isn't even listed.

I don't know enough about how the $SYS topics are populated, does anyone have any ideas on why I might not be getting a node list on this cluster? Is there a configuration I must add, a module I haven't activated?
We have applications that rely on subscriptions to these topics.

Would welcome any advice/tips as I think I'm at a dead end, and I'm guessing it's specific to my setup and the way the $SYS topic is published to?
Thanks!

Config values:
```
broker.sys_interval = 1m
broker.sys_heartbeat = 30s
```
```
EMQX_ACL_NOMATCH | deny
EMQX_ALLOW_ANONYMOUS | false
EMQX_AUTH__HTTP__ACL_REQ | http://mqauth.platform.eu-west-1.mycloud:8080/acl
EMQX_AUTH__HTTP__ACL_REQ__METHOD | post
EMQX_AUTH__HTTP__AUTH_REQ | http://mqauth.platform.eu-west-1.mycloud:8080/connect
EMQX_AUTH__HTTP__AUTH_REQ__METHOD | post
EMQX_AUTH__HTTP__SUPER_REQ | http://mqauth.platform.eu-west-1.mycloud:8080/superuser
EMQX_AUTH__HTTP__SUPER_REQ__METHOD | post
EMQX_CLUSTER__DISCOVERY | dns
EMQX_CLUSTER__DNS__APP | mqttcluster
EMQX_CLUSTER__DNS__NAME | mqtt.platform.eu-west-1.mycloud
EMQX_CLUSTER__NAME | mqttcluster
EMQX_LISTENER__API__MGMT | 0.0.0.0:8080
EMQX_LISTENER__TCP__EXTERNAL | 0.0.0.0:1883
EMQX_LISTENER__WS__EXTERNAL | 8083
EMQX_LOADED_PLUGINS | emqx_recon,emqx_retainer,emqx_management,emqx_dashboard,emqx_auth_http
EMQX_LOG__LEVEL | debug
EMQX_NAME | mqttcluster
```

**Comment by tigercl** [comment]
@louisburton If you can get the node information under the cluster through the rest api, the cluster is fine. Please check whether your subscription is successful, because there are default ACL rules that do not allow clients outside the machine to subscribe to system topics.

**Comment by louisburton** [comment]
Hi @tigercl - thanks for the pointer. Unfortunately, I'm not sure this is the issue.
The MQTT cluster requests to `EMQX_AUTH__HTTP__ACL_REQ` return with success, as I observe in the logs.
I can even emulate the ACL requests via cURL from my local machine:
```
curl -i -X POST -H "Content-Type: application/x-www-form-urlencoded" -d 'access=1&clientid=myid&username=$my_power_user&topic=$SYS/brokers&ipaddr=82.27.72.131' http://mqauth.platform.eu-west-1.mycloud:8080/acl
HTTP/1.1 200 OK
Date: Mon, 29 Jun 2020 11:13:42 GMT
Content-Length: 15
Content-Type: text/plain; charset=utf-8

{"status":"OK"}
```

Also, if it was to do with local IPs, wouldn't at least the EMQ X Dashboard Websocket Tool be able to connect? It can connect to other topics okay.

**Comment by louisburton** [comment]
@zhanghongtong unsure if you're familiar with this configuration at all also, but any other guidance or tips for troubleshooting would be greatly appreciated.
I suspect I must be missing something simple, but it's not proving obvious to me - especially when using an administrator user that's basically allowed permissions on any topic matching `.*` and no IP restrictions. Reinforced by the fact that we use an identically configured ACL service on our older 2.3.9 standalone node, and that allows `$SYS` subscription fine with the same credentials.

**Comment by zhanghongtong** [comment]
Hi, @louisburton 
Can you show the `etc/acl.conf` file in your container ?
And I noticed that the address of your mqtt host is `mqtt.platform.eu-west-1.mycloud`, is this a load-balanced address?

**Comment by louisburton** [comment]
I can't actually shell into the container because it's running on ECS Fargate.
The image though is the same as the [EMQX provided one](https://hub.docker.com/layers/emqx/emqx/v3.2.3/images/sha256-ac6b7f6067102634f084a9aef127f16e6f7173fd666f672323b98040428e80b2?context=explore), and thus should be [this](https://github.com/emqx/emqx/blob/v3.2.3/etc/acl.conf) - but I had thought it would be unused because of the config for the `emqx_auth_http` plugin.
Generally speaking I can also see logging on our mqauth component, receiving authentication requests correctly from the mqtt cluster and responding successfully, and providing access - showing that for other use cases `emqx_auth_http` is working fine with our auth component providing access.
Is it possible that only the `$SYS` topics do not go via `emqx_auth_http`? & this behaviour differs from `2.3.9` to `3.2.3`?
I appreciate that it's behaving a bit like it's falling back to the acl.conf for the $SYS topic...
I have `EMQX_LOG__LEVEL` set to `debug` already, but actually I see no logs hit system out, and thus I do not see if this would have given a clue - I suspect file based logging is occurring only (& due to fargate usage I can't shell to see this).

`mqtt.platform.eu-west-1.mycloud` corresponds to A records with 3 IPS, I believe this corresponds to `dns` clustering guidance [here](https://docs.emqx.io/tutorial/latest/en/cluster/dns.html#auto-cluster-by-dns).
![image](https://user-images.githubusercontent.com/5257921/86112450-e1eac200-babf-11ea-8325-d44d518fac2d.png)

**Comment by zhanghongtong** [comment]
> The image though is the same as the EMQX provided one, and thus should be this - but I had thought it would be unused because of the config for the emqx_auth_http plugin.

Even if `emqx_auth_http` is enabled, emqx will still check the `etc/acl.conf` file, I think this is the reason why your subscription failed, because `etc/acl.conf` prevents you from subscribing

I'm sorry I don't know the behavior of emqx 2.3.9, this version is too early

**Comment by louisburton** [comment]
Upon further investigation, and a better understanding of the authentication fall through, our problem did actually reside in our own HTTP auth component. 
Although the `EMQX_AUTH__HTTP__ACL_REQ` behaviour was working fine, giving positive permissions without needing to fall through to the acl.conf, our `EMQX_AUTH__HTTP__SUPER_REQ` endpoint was not behaving correctly. It seems this wasn't used in the same way in `2.3.9` and so we observe the issue only after upgrade. Upon giving an appropriate response from this endpoint, our issue is resolved.

Thanks for taking the time to try and understand/help.
