### ISSUE TITLE
EMQX  on AWS autoscaling

### ISSUE THREAD

**Issue by yuvarajan1989k** [emqx/emqx#3556]
Hi,

Is it recommended to run emqx on AWS autoscaling group ?

Below is my 

> **Architecture**

  Clients  -------------------->   AWS LB ---------------> Autoscaling group(emqx)

**Comment by tigercl** [comment]
@yuvarajan1989k Sorry for late reply. This is supported, you can use it with confidence

**Comment by yuvarajan1989k** [comment]
@tigercl  thanks for the update.
