### ISSUE TITLE
source code can not compilation in otp23.02 version 

### ISSUE THREAD

**Issue by erl-go-java** [emqx/emqx#3557]
I use otp23.02 version, emqx4.0 version, then, make it, There is an error：
**emqx-rel/c_src/bcrypt_port.c:20:10: fatal error: erl_interface.h: No such file or directory
 #include <erl_interface.h>**
In erlang website，I find otp23 **Removed the deprecated parts of erl_interface**
The official website explains as follows：
**erl_interface: Removed the deprecated parts of erl_interface (erl_interface.h and essentially all C functions with prefix erl_).**

**Comment by HJianBo** [comment]
Hi @erl-go-java OTP 23.x is not supported in below v4.1.x. Plz use OTP-22 to compile it

**Comment by erl-go-java** [comment]
Hi @HJianBo in future, as v4.2.x will be supported

**Comment by HJianBo** [comment]
We have in dealing with these compiled problems.  After finished, we will tell you in there :-)

**Comment by erl-go-java** [comment]
@HJianBo thank you

**Comment by HJianBo** [comment]
Hi guys, We have supported it in the newest master
