### ISSUE TITLE
unable to verify the first carificate 

### ISSUE THREAD

**Issue by lastincisor** [emqx/emqx#3563]
**Please describe your problem in detail, if necessary, you can upload the log file through the attachment**:
系统 win 10 
emqx  3.2.1

emqx 证书配置 
listener.ssl.external.keyfile = etc/certs/ssl/server.key
listener.ssl.external.certfile = etc/certs/ssl/server-cert.pem

##listener.ssl.external.cacertfile = etc/certs/ssl/root-cacert.pem
##listener.ssl.external.dhfile = etc/certs/dh-params.pem
##listener.ssl.external.verify = verify_peer
##listener.ssl.external.fail_if_no_peer_cert = true

证书参考
https://www.emqx.io/cn/blog/emqx-server-ssl-tls-secure-connection-configuration-guide
配置生成，双向认证已经成功。 

使用单项认证报 unable to verify the first carificate

**Comment by tigercl** [comment]
@lastincisor Did you use the openssl command to verify the certificate according to the documentation?

**Comment by lastincisor** [comment]
@tigercl  验证过，证书都没有问题。

[ssl.zip](https://github.com/emqx/emqx/files/4851059/ssl.zip)

**Comment by spring2maz** [comment]
the certs look good.
but why was this commented out ?
`##listener.ssl.external.cacertfile = etc/certs/ssl/root-cacert.pem`

**Comment by lastincisor** [comment]
本来是没有注释的。 但是也不成功。
后来看到这个 https://github.com/emqx/emqx/issues/2397
尝试了一下 也是不行
