### ISSUE TITLE
When the 4G module sends a 1kb data every interval of 500ms, the client will be disconnected

### ISSUE THREAD

**Issue by cfplwewe** [emqx/emqx#3566]
2020-07-03 19:07:12.387 [error] <<"600Test|securemode=3,signmethod=hmacsha1|">>@221.178.124.87:34914 [Channel] Unexpected incoming: {mqtt_packet,
                                   {mqtt_packet_header,0,true,0,true},
                                   undefined,undefined}

**Comment by HJianBo** [comment]
Hello @cfplwewe It seems the Broker received an invalid MQTT stream. Please check your client, or Capture the network traffic to diagnose it :)
