### ISSUE TITLE
Random duplicate message burst while bridging with AWS Iot 

### ISSUE THREAD

**Issue by sak-hack** [emqx/emqx#3567]
Emqx as a bridge with AWS Iot broker behaving unexpectedly(getting random duplicate messages burst with any Qos level), normally happen when a client publishing messages with some pace, checked all config params but no luck, did anyone came across similar issue.

Attached emqx.conf and emqx_bridge_mqtt.conf.
[emqx_configs.zip](https://github.com/emqx/emqx/files/4870470/emqx_configs.zip)

Thanks in advance!

**Comment by saqib-cielo** [comment]
For emqx_bridge_mqtt.conf, instead of mqttv3, we also tried with mqttv4 as per AWS Iot compatible mqtt version that is 3.1.1 but it didn't solved the issue. Not sure what else we are doing wrong.

**Comment by boykom** [comment]
Hello!
We are faced the same issue.

**Comment by HJianBo** [comment]
Hi @sak-hack What's the emqx?

**Comment by sak-hack** [comment]
> Hi @sak-hack What's the emqx?

I meant EMQ Broker

**Comment by HJianBo** [comment]
Sorry I misled you. I meant what is the specific version number of EMQ X you are using? It helps me recreate the problem.

**Comment by sak-hack** [comment]
EMQ X 4.1.0, Any update regarding this issue in the latest releases?
