### ISSUE TITLE
lost connection after 20s

### ISSUE THREAD

**Issue by KeZhimin** [emqx/emqx#3572]
use Paho's client  connect emqx, but every 20 second, the client report 'lost connection, retrying'.    how can I troubleshoot this problem.  any ideas?
![image](https://user-images.githubusercontent.com/7068010/86694675-6b5d3f80-c03e-11ea-9311-ba734752ea26.png)

**Comment by tigercl** [comment]
@KeZhimin Can you provide logs in emqx(../log/emqx.log.*)?

**Comment by HJianBo** [comment]
Hello guys, any update?

**Comment by k32** [comment]
Unfortunately, there is not enough information to investigate the issue. Please feel free to reopen if it's still relevant and you manage to collect the logs.
