### ISSUE TITLE
Subscribe again, the client conflicts go offline

### ISSUE THREAD

**Issue by LvCodeing** [emqx/emqx#3573]
- EMQ 3.4.3
- Erlang/OTP 22.3
- Others:

Call api interface, parameters:
http://ip:port/api/v3/mqtt/subscribe
http://ip:port/api/v3/mqtt/unsubscribe

{
  "topic": "test_topic",
  "qos": 1,
  "client_id": "mqttjs_ab9069449e"
}

When subscribing, unsubscribing, or subscribing, a subid_conflict exception is reported, and each time it inevitably occurs, the client goes offline.

** Reason for termination ==
** {subid_conflict,
       [{emqx_broker_helper,register_sub,2,
            [{file,
                 "/Users/zsh/Documents/work/erWorkspace/emqx-rel/_checkouts/emqx/src/emqx_broker_helper.erl"},
             {line,64}]},
        {emqx_broker,subscribe,3,
            [{file,
                 "/Users/zsh/Documents/work/erWorkspace/emqx-rel/_checkouts/emqx/src/emqx_broker.erl"},
             {line,128}]},
        {emqx_session,do_subscribe,5,
            [{file,
                 "/Users/zsh/Documents/work/erWorkspace/emqx-rel/_checkouts/emqx/src/emqx_session.erl"},
             {line,1145}]},
        {emqx_session,'-handle_cast/2-fun-0-',5,
            [{file,
                 "/Users/zsh/Documents/work/erWorkspace/emqx-rel/_checkouts/emqx/src/emqx_session.erl"},
             {line,475}]},
        {emqx_session,handle_cast,2,
            [{file,
                 "/Users/zsh/Documents/work/erWorkspace/emqx-rel/_checkouts/emqx/src/emqx_session.erl"},
             {line,469}]},
        {gen_server,try_dispatch,4,[{file,"gen_server.erl"},{line,637}]},
        {gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,711}]},
        {proc_lib,wake_up,3,[{file,"proc_lib.erl"},{line,259}]}]}

**Comment by wwhai** [comment]
> * EMQ 3.4.3
> * Erlang/OTP 22.3
> * Others:
> 
> Call api interface, parameters:
> http://ip:port/api/v3/mqtt/subscribe
> http://ip:port/api/v3/mqtt/unsubscribe
> 
> {
> "topic": "test_topic",
> "qos": 1,
> "client_id": "mqttjs_ab9069449e"
> }
> 
> When subscribing, unsubscribing, or subscribing, a subid_conflict exception is reported, and each time it inevitably occurs, the client goes offline.
> 
> ** Reason for termination ==
> ** {subid_conflict,
> [{emqx_broker_helper,register_sub,2,
> [{file,
> "/Users/zsh/Documents/work/erWorkspace/emqx-rel/_checkouts/emqx/src/emqx_broker_helper.erl"},
> {line,64}]},
> {emqx_broker,subscribe,3,
> [{file,
> "/Users/zsh/Documents/work/erWorkspace/emqx-rel/_checkouts/emqx/src/emqx_broker.erl"},
> {line,128}]},
> {emqx_session,do_subscribe,5,
> [{file,
> "/Users/zsh/Documents/work/erWorkspace/emqx-rel/_checkouts/emqx/src/emqx_session.erl"},
> {line,1145}]},
> {emqx_session,'-handle_cast/2-fun-0-',5,
> [{file,
> "/Users/zsh/Documents/work/erWorkspace/emqx-rel/_checkouts/emqx/src/emqx_session.erl"},
> {line,475}]},
> {emqx_session,handle_cast,2,
> [{file,
> "/Users/zsh/Documents/work/erWorkspace/emqx-rel/_checkouts/emqx/src/emqx_session.erl"},
> {line,469}]},
> {gen_server,try_dispatch,4,[{file,"gen_server.erl"},{line,637}]},
> {gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,711}]},
> {proc_lib,wake_up,3,[{file,"proc_lib.erl"},{line,259}]}]}

Sorry we can’t represent this exception，can you help give your operation enviroument and steps for us？

**Comment by LvCodeing** [comment]
Steps:
1. Subscribe to the topic through the api interface (http://ip:port/api/v3/mqtt/subscribe)
2. Cancel the subscription topic through the api interface (http://ip:port/api/v3/mqtt/unsubscribe)
3. Subscribe to the topic through the api interface (http://ip:port/api/v3/mqtt/subscribe)

parameter:
{
"topic": "test_topic",
"qos": 1,
"client_id": "mqttjs_ab9069449e"
}
Then the client mqttjs_ab9069449e will lose the connection, and the connection will be lost when binding for the second time.

**Comment by LvCodeing** [comment]
> > * EMQ 3.4.3
> > * Erlang/OTP 22.3
> > * Others:
> > 
> > Call api interface, parameters:
> > http://ip:port/api/v3/mqtt/subscribe
> > http://ip:port/api/v3/mqtt/unsubscribe
> > {
> > "topic": "test_topic",
> > "qos": 1,
> > "client_id": "mqttjs_ab9069449e"
> > }
> > When subscribing, unsubscribing, or subscribing, a subid_conflict exception is reported, and each time it inevitably occurs, the client goes offline.
> > ** Reason for termination ==
> > ** {subid_conflict,
> > [{emqx_broker_helper,register_sub,2,
> > [{file,
> > "/Users/zsh/Documents/work/erWorkspace/emqx-rel/_checkouts/emqx/src/emqx_broker_helper.erl"},
> > {line,64}]},
> > {emqx_broker,subscribe,3,
> > [{file,
> > "/Users/zsh/Documents/work/erWorkspace/emqx-rel/_checkouts/emqx/src/emqx_broker.erl"},
> > {line,128}]},
> > {emqx_session,do_subscribe,5,
> > [{file,
> > "/Users/zsh/Documents/work/erWorkspace/emqx-rel/_checkouts/emqx/src/emqx_session.erl"},
> > {line,1145}]},
> > {emqx_session,'-handle_cast/2-fun-0-',5,
> > [{file,
> > "/Users/zsh/Documents/work/erWorkspace/emqx-rel/_checkouts/emqx/src/emqx_session.erl"},
> > {line,475}]},
> > {emqx_session,handle_cast,2,
> > [{file,
> > "/Users/zsh/Documents/work/erWorkspace/emqx-rel/_checkouts/emqx/src/emqx_session.erl"},
> > {line,469}]},
> > {gen_server,try_dispatch,4,[{file,"gen_server.erl"},{line,637}]},
> > {gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,711}]},
> > {proc_lib,wake_up,3,[{file,"proc_lib.erl"},{line,259}]}]}
> 
> Sorry we can’t represent this exception，can you help give your operation enviroument and steps for us？

Steps:
1. Subscribe to the topic through the api interface (http://ip:port/api/v3/mqtt/subscribe)
2. Cancel the subscription topic through the api interface (http://ip:port/api/v3/mqtt/unsubscribe)
3. Subscribe to the topic through the api interface (http://ip:port/api/v3/mqtt/subscribe)

parameter:
{
"topic": "test_topic",
"qos": 1,
"client_id": "mqttjs_ab9069449e"
}
Then the client mqttjs_ab9069449e will lose the connection, and the connection will be lost when binding for the second time.

**Comment by LvCodeing** [comment]
> > * EMQ 3.4.3
> > * Erlang/OTP 22.3
> > * Others:
> > 
> > Call api interface, parameters:
> > http://ip:port/api/v3/mqtt/subscribe
> > http://ip:port/api/v3/mqtt/unsubscribe
> > {
> > "topic": "test_topic",
> > "qos": 1,
> > "client_id": "mqttjs_ab9069449e"
> > }
> > When subscribing, unsubscribing, or subscribing, a subid_conflict exception is reported, and each time it inevitably occurs, the client goes offline.
> > ** Reason for termination ==
> > ** {subid_conflict,
> > [{emqx_broker_helper,register_sub,2,
> > [{file,
> > "/Users/zsh/Documents/work/erWorkspace/emqx-rel/_checkouts/emqx/src/emqx_broker_helper.erl"},
> > {line,64}]},
> > {emqx_broker,subscribe,3,
> > [{file,
> > "/Users/zsh/Documents/work/erWorkspace/emqx-rel/_checkouts/emqx/src/emqx_broker.erl"},
> > {line,128}]},
> > {emqx_session,do_subscribe,5,
> > [{file,
> > "/Users/zsh/Documents/work/erWorkspace/emqx-rel/_checkouts/emqx/src/emqx_session.erl"},
> > {line,1145}]},
> > {emqx_session,'-handle_cast/2-fun-0-',5,
> > [{file,
> > "/Users/zsh/Documents/work/erWorkspace/emqx-rel/_checkouts/emqx/src/emqx_session.erl"},
> > {line,475}]},
> > {emqx_session,handle_cast,2,
> > [{file,
> > "/Users/zsh/Documents/work/erWorkspace/emqx-rel/_checkouts/emqx/src/emqx_session.erl"},
> > {line,469}]},
> > {gen_server,try_dispatch,4,[{file,"gen_server.erl"},{line,637}]},
> > {gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,711}]},
> > {proc_lib,wake_up,3,[{file,"proc_lib.erl"},{line,259}]}]}
> 
> Sorry we can’t represent this exception，can you help give your operation enviroument and steps for us？

OS: ubuntu16.04
Version: EMQX 3.4.3
Erlang/OTP 22.3

Steps:
1. Subscribe to the topic through the api interface (http://ip:port/api/v3/mqtt/subscribe)
2. Cancel the subscription topic through the api interface (http://ip:port/api/v3/mqtt/unsubscribe)
3. Subscribe to the topic through the api interface (http://ip:port/api/v3/mqtt/subscribe)

parameter:
{
"topic": "test_topic",
"qos": 1,
"client_id": "mqttjs_ab9069449e"
}
Then the client mqttjs_ab9069449e will lose the connection, and the connection will be lost when binding for the second time.

**Comment by terry-xiaoyu** [comment]
Does the same problem exist on 4.0.x or 4.1.x ? We are now working on 4.0 and later, all the bug fixes will only go into 4.0 by default. 

For enterprise issues, you could talk to our customer services directly.

**Comment by LvCodeing** [comment]
> Does the same problem exist on 4.0.x or 4.1.x ? We are now working on 4.0 and later, all the bug fixes will only go into 4.0 by default.
> 
> For enterprise issues, you could talk to our customer services directly.

This problem does not exist in v4.0 and v4.1.
