### ISSUE TITLE
emqx v4.1 Out of memory

### ISSUE THREAD

**Issue by xujiaja** [emqx/emqx#3575]
During the pressure test,We found that the emq process was killed by linux.However, no more than memory was found in the log and panel，Please tell me why

**Comment by xujiaja** [comment]
![image](https://user-images.githubusercontent.com/23472286/86872993-05d98380-c110-11ea-84e4-24d13c8e7b02.png)

**Comment by terry-xiaoyu** [comment]
Before submitting the issue, please provide the OS version, emqx version and other information as the issue template described. 

And we also want to know what scenario you are testing, i.e. the number of the subscribers and publishers, what topics they were subscribing to, what's the publishing rate/speed, if you are testing on a single node or cluster, etc. And the error logs you might found in log/ dir, named `emqx.log.*`.

You may also need to inspect the memory used by emqx using `top` or `free` as your test running.
