### ISSUE TITLE
client connect failed     : Parse failed for function_clause

### ISSUE THREAD

**Issue by ssy478131165** [emqx/emqx#3576]
**Please describe your problem in detail, if necessary, you can upload the log file through the attachment**:
2020-07-08 20:55:31.578 [error] 223.104.255.246:15514 [MQTT] 
Parse failed for function_clause
[{emqx_frame,parse_utf8_string,[<<4,77,81,84,84,4,194,0,100,0,66,55,54,48,48,84,101,115,116,84,101,115,116,56>>],[{file,"d:/a/emqx-rel/emqx-rel/_build/emqx/lib/emqx/src/emqx_frame.erl"},{line,419}]},{emqx_frame,parse_packet,3,[{file,"d:/a/emqx-rel/emqx-rel/_build/emqx/lib/emqx/src/emqx_frame.erl"},{line,165}]},{emqx_frame,parse_frame,4,[{file,"d:/a/emqx-rel/emqx-rel/_build/emqx/lib/emqx/src/emqx_frame.erl"},{line,142}]},{emqx_connection,parse_incoming,3,[{file,"d:/a/emqx-rel/emqx-rel/_build/emqx/lib/emqx/src/emqx_connection.erl"},{line,508}]},{emqx_connection,handle_msg,2,[{file,"d:/a/emqx-rel/emqx-rel/_build/emqx/lib/emqx/src/emqx_connection.erl"},{line,501}]},{emqx_connection,process_msg,3,[{file,"d:/a/emqx-rel/emqx-rel/_build/emqx/lib/emqx/src/emqx_connection.erl"},{line,284}]},{proc_lib,wake_up,3,[{file,"proc_lib.erl"},{line,259}]}]
Frame data:<<16,152,0,4,77,81,84,84,4,194,0,100,0,66,55,54,48,48,84,101,115,116,84,101,115,116,56,57,56,54,48,55,66,55,49,48,49,57,56,48,48,48,54,55,54,52,124,115,101,99,117,114,101,109,111,100,101,61,51,44,115,105,103,110,109,101,116,104,111,100,61,104,109,97,99,115,104,97,49,124,0,30,55,49,48,49,57,56,48,48,48,54,55,54,52,38,69,107,122,117,87,87,107,77,99,55,89,66,56,121,71,54,0,40,102,52,98,54,50,56,56,52,53,99,49,56,99,53,50,52,56,51,55,98,54,99,49,97,98,97,50,51,98,49,56,97,50,48,50,99,55,49,53,51>>

**Comment by tigercl** [comment]
@ssy478131165 This means that there is a problem with the packets received by the agent and cannot be parsed correctly. I'm sorry for the inconvenience, we are planning to improve this part of the log.
