### ISSUE TITLE
Persistent Sessions

### ISSUE THREAD

**Issue by dwi-iwb** [emqx/emqx#3577]
I am having problems with session persistence and after reading  #3529 I am wondering if this feature is even available as part of the OSS version.

I am looking for basic session persistence & message queing as part of QoS 1 message delivery, exactly as described in #3529 :

> Steps:
> 
> 1. Connect client A to emqx node using Clean Session = false and MQTT 3.1.1/5.0
> 2. Connect client B to emqx node using Clean Session = false and MQTT 3.1.1/5.0
> 3. Subscribe client B to topic X
> 4. Client A publishes some messages to the topic X with qos = 1
> 5. Client B receives the messages
> 6. Disconnect client B
> 7. Client A publishes more messages to the topic X with qos = 1
> 8. Connect client B again with Clean Session = false and MQTT 3.1.1/5.0
> 9. Subscribe client B to topic X

My understanding of the ["Data persistence" featureset](https://docs.emqx.io/broker/latest/en/introduction/checklist.html) of the Enterprise Version was, that it guarantes me persistence through broker restarts... but session persistence & message queing should be possible in the OSS version as long as the broker is not restarted.

(Kubernetes | clusterd | 3 nodes)

Thanks for clarification.

**Comment by tigercl** [comment]
@dwi-iwb Sorry for late reply. As you might expect, persistent session and message queue functions are provided in the open source version.

**Comment by terry-xiaoyu** [comment]
@dwi-iwb Do you have the same issue as https://github.com/emqx/emqx/issues/3529 ? Have you tested the same reproducing procedure listed in that issue?

**Comment by dwi-iwb** [comment]
Follow up in #3529
