### ISSUE TITLE
EMQ Proxy Protocol 

### ISSUE THREAD

**Issue by watchworld** [emqx/emqx#3578]
**Environment**:
public cloud
- EMQ X version (e.g. `emqx_ctl status`): 4.0
- Hardware configuration (e.g. `lscpu`):4cpu 8gb
- OS (e.g. `cat /etc/os-release`):centos7
- Kernel (e.g. `uname -a`):3.10
- Erlang/OTP version (in case you build emqx from source code): 
- Others:

**What happened and what you expected to happen**: use haproxy loadblance emqx，need fetch client ip，I find the function no freindly. because if I connect emq server，the connection failed. 

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Comment by tigercl** [comment]
@watchworld You need to set `listener.tcp.<Listener Name>.proxy_protocol` in `emqx.conf` to `true`, and append `check-send-proxy send-proxy-v2` to server field in backend session in `haproxy.cfg`.
