### ISSUE TITLE
Subscription via TCP can not receive message published via SSL

### ISSUE THREAD

**Issue by morganwu** [emqx/emqx#3579]
- EMQ X version (e.g. `emqx_ctl status`):  4.0.7
- Hardware configuration (e.g. `lscpu`): x86_64
- OS (e.g. `cat /etc/os-release`):NAME="Ubuntu"  VERSION="18.04.4 LTS (Bionic Beaver)"
- Kernel (e.g. `uname -a`): Linux VM-0-10-ubuntu 4.15.0-99-generic 

I subscribed '/test' via both TCP and SSL, then published message to '/test' via SSL, the subscription via SSL received the message but the TCP did not. Is this normal? Or maybe I misconfigured anything? Thanks.

**Comment by tigercl** [comment]
@morganwu This is of course abnormal, please confirm whether you have successfully subscribed or whether you have used shared subscription. Also you can use `emqx_ctl trace start client <ClientID> <File>` to trace behavior of clients.
