### ISSUE TITLE
TLS server: In state hello received UNDEFINED ALERT: Fatal - Unexpected Message\n

### ISSUE THREAD

**Issue by lastincisor** [emqx/emqx#3580]
**Please describe your problem in detail, if necessary, you can upload the log file through the attachment**:
线上环境 
centos 6 
emqx broker 4,0.7

单项认证 报错 
2020-07-10 17:20:43.018 [error]     supervisor: 'esockd_connection_sup - <0.1666.0>'
    errorContext: connection_shutdown
    reason: {ssl_error,
                {tls_alert,
                    {unexpected_message,
                        "TLS server: In state hello received UNDEFINED ALERT: Fatal - Unexpected Message\n"}}}
    offender: [{pid,<0.6503.0>},
               {name,connection},
               {mfargs,
                   {emqx_connection,start_link,
                       [[{deflate_options,[]},
                         {max_conn_rate,500},

该证书及验证方式在测试环境正常

测试环境 
os  centos 6
emqx broker 4.0.4

**Comment by terry-xiaoyu** [comment]
It means that the TLS handshake failed when emqx expecting a `client_hello`. You may have to capture the TLS packets flow  using tcpdump / wireshark to get more details about the issue.

BTW, emqx is not good at handling the TLS connections for now, as it may causes much more memory usage than TCP. A better solution is using a load balancer (such as haproxy) which terminates the TLS connections, and then forward the connections to emqx via TCP.

**Comment by spring2maz** [comment]
This looks very much likely that the client did not perform TLS handshake,
i.e. it must have sent application data directly after connection establishment.

@lastincisor We'd like to see your test instructions on the client side.
e.g. if it's command line tool, how was it run with which options etc.
