### ISSUE TITLE
Client disconnect and reconnect fail in Emqx Group version 4.1.0 

### ISSUE THREAD

**Issue by Astonl** [emqx/emqx#3582]
There four nodes in my test emqx group.Environment infomation as follow：

1. version: EMQX Broker 4.1.0
2. OS：centos7.2 
3. Networkk Construct：SLB（Ali）-> Emqx Group

Question：
i create 3000 thread(in six vm-computer<2core * 4cpu * 8g > and each 500 ) mqtt client connect to emqx broker group . each client publish one message to topic every 10s. Today(running about 48h ) i find all client disconnet to cloud due to error:
`com.mqtt.MqttClient -130284238 [MQTT Ping: 1594279267199] ERROR com.mqtt.MqttClient  - mqttClient connect fail by error: MqttException (0) - java.net.UnknownHostException: {a.b.cn}`
Then i check emqx server log. as follow:

`2020-07-11 06:20:26.415 [error] 106.14.80.184:36066 [MQTT] 

**Parse failed for function_clause**

[{emqx_frame,parse_packet,[{mqtt_packet_header,4,false,3,true},<<"T / HTTP/1.1\r\nConnection: Upgrade, HTTP2-Settings\r\nUpgrade: h2c\r\nHTTP">>,#{max_size => 1048576,strict_mode => false,version => 4}],[{file,"/emqx-rel/_build/emqx/lib/emqx/src/emqx_frame.erl"},{line,164}]},{emqx_frame,parse_frame,4,[{file,"/emqx-rel/_build/emqx/lib/emqx/src/emqx_frame.erl"},{line,142}]},{emqx_connection,parse_incoming,3,[{file,"/emqx-rel/_build/emqx/lib/emqx/src/emqx_connection.erl"},{line,508}]},{emqx_connection,handle_msg,2,[{file,"/emqx-rel/_build/emqx/lib/emqx/src/emqx_connection.erl"},{line,501}]},{emqx_connection,process_msg,3,[{file,"/emqx-rel/_build/emqx/lib/emqx/src/emqx_connection.erl"},{line,284}]},{proc_lib,wake_up,3,[{file,"proc_lib.erl"},{line,259}]}]
Frame data:<<"GET / HTTP/1.1\r\nConnection: Upgrade, HTTP2-Settings\r\nUpgrade: h2c\r\nHTTP2-Settings: AAMAAABkAARAAAAAAAIAAAAA\r\nUser-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36\r\n\r\n">>`

what's more :

`2020-07-11 02:52:34.836 [error] 101.133.148.169:53882 [MQTT] 

**Parse failed for frame_too_large**

[{emqx_frame,parse_remaining_len,5,[{file,"/emqx-rel/_build/emqx/lib/emqx/src/emqx_frame.erl"},{line,132}]},{emqx_connection,parse_incoming,3,[{file,"/emqx-rel/_build/emqx/lib/emqx/src/emqx_connection.erl"},{line,508}]},{emqx_connection,handle_msg,2,[{file,"/emqx-rel/_build/emqx/lib/emqx/src/emqx_connection.erl"},{line,501}]},{emqx_connection,process_msg,3,[{file,"/emqx-rel/_build/emqx/lib/emqx/src/emqx_connection.erl"},{line,284}]},{proc_lib,wake_up,3,[{file,"proc_lib.erl"},{line,259}]}]
Frame data:<<205,239,209,97,145,3>>`

and

`2020-07-11 02:50:35.379 [error] 101.133.148.169:59056 [MQTT] 

**Parse failed for {badmatch,<<>>}**

[{emqx_frame,parse_packet,3,[{file,"/emqx-rel/_build/emqx/lib/emqx/src/emqx_frame.erl"},{line,177}]},{emqx_frame,parse_frame,4,[{file,"/emqx-rel/_build/emqx/lib/emqx/src/emqx_frame.erl"},{line,142}]},{emqx_connection,parse_incoming,3,[{file,"/emqx-rel/_build/emqx/lib/emqx/src/emqx_connection.erl"},{line,508}]},{emqx_connection,handle_msg,2,[{file,"/emqx-rel/_build/emqx/lib/emqx/src/emqx_connection.erl"},{line,501}]},{emqx_connection,process_msg,3,[{file,"/emqx-rel/_build/emqx/lib/emqx/src/emqx_connection.erl"},{line,284}]},{proc_lib,wake_up,3,[{file,"proc_lib.erl"},{line,259}]}]
Frame data:<<22,3,0,0,105,1,0,0,101,3,3,85,28,167,228,114,97,110,100,111,109,49,114,97,110,100,111,109,50,114,97,110,100,111,109,51,114,97,110,100,111,109,52,0,0,12,0,47,0,10,0,19,0,57,0,4,0,255,1,0,0,48,0,13,0,44,0,42,0,1,0,3,0,2,6,1,6,3,6,2,2,1,2,3,2,2,3,1,3,3,3,2,4,1,4,3,4,2,1,1,1,3,1,2,5,1,5,3,5,2>>
2020-07-11 02:50:35.380 [error]     supervisor: 'esockd_connection_sup - <0.1658.0>'
    errorContext: connection_shutdown
    reason: {badmatch,<<>>}
    offender: [{pid,<0.5066.108>},
               {name,connection},
               {mfargs,
                   {emqx_connection,start_link,
                       [[{deflate_options,[]},
                         {max_conn_rate,1000},
                         {active_n,100},
                         {zone,external}]]}}]`

i make sure domain name and network available。

**Comment by terry-xiaoyu** [comment]
@Astonl Are you connecting to EMQX broker via websocket? The ws port defaults to `8083`, did you connect your clients to the correct port?

**Comment by Astonl** [comment]
I‘m use tcp and port : 1838. After 48 hours of normal operation, all the clients are suddenly offline.

**Comment by HJianBo** [comment]
Hi @Astonl These logs will not lead to all clients disconnected. It just a serial of parsing MQTT frame error.

But, according to your client logs. It is a `java.net.UnknownHostException`, This may be a key reason that lead to this problem：

```
com.mqtt.MqttClient -130284238 [MQTT Ping: 1594279267199] ERROR com.mqtt.MqttClient - mqttClient connect fail by error: MqttException (0) - java.net.UnknownHostException: {a.b.cn}
```

**Comment by Astonl** [comment]
Thanks for you. By create a test tool to trace the reflect between IP and  domain name , i find a router reboot by itself every day. Problem closed.
