### ISSUE TITLE
Include MSVCR120.dll in lib folder

### ISSUE THREAD

**Issue by kedar-hatkar** [emqx/emqx#3584]
**Environment**:

- EMQ X version : 4.1.1
- OS: Windows Server 2016 64 bit

**What happened and what you expected to happen**:
While installing EMQX broker using emqx install method, we get following error

![EMQX error](https://user-images.githubusercontent.com/60394147/87227152-95a05b80-c3b6-11ea-861d-5bdbd28f0f36.png)

It seems that EMQX has dependency on MSVCR120.dll. I have downloaded this dll from https://www.microsoft.com/en-in/download/details.aspx?id=40784

After installing missing dll, i am able to install EMQX broker.  

Windows 10 has this dll preloaded in system folder. But Windows server version >= 2016 does not include it by default may be.

Hence can you include MSVCR120.dll in lib folder so that EMQX service can use it directly from lib folder?

**Comment by tigercl** [comment]
@kedar-hatkar Thank you very much for your suggestions, we will evaluate the necessity of this change as soon as possible and give you feedback.

**Comment by tigercl** [comment]
@kedar-hatkar Sorry, we will not consider providing these library files in the installation package for the time being, but we provide a solution in the [FAQ](https://docs.emqx.io/broker/latest/en/faq/error.html).

**Comment by Zapnologica** [comment]
I am receiving a similar issue now:

![image](https://user-images.githubusercontent.com/3656913/212801244-9d943be0-d1a8-406d-8286-0f11d80c6966.png)

**Comment by kedar-hatkar** [comment]
@Zapnologica 

VCRUNTIME140.dll issue is observed for EMQX newer version >=5.0.3

Please find my solution link 
https://github.com/emqx/emqx/issues/8555#issuecomment-1195643010
