### ISSUE TITLE
OS envrionment variable in emqx_bridge_mqtt.conf file

### ISSUE THREAD

**Issue by gercorri** [emqx/emqx#3585]
Hi I am using balenaOS on edge devices which are running EMQX Edge in a docker container using the a the mqtt bridge plugin to forward topics to and EMQX broker I have running in AWS. 

The edge devices have an environment called $BALENA_DEVICE_NAME_AT_INIT. When I open a shell to the emqx edge docker container and type echo $BALENA_DEVICE_NAME_AT_INIT it returns the correct name of the device. I want to use this name as the Client ID in the emqx_bridge_mqtt.conf but no matter what way I enter it the client id displayed on the broker is always the literal text and not the value of the environment variable.

e.g. if $BALENA_DEVICE_NAME_AT_INIT = device1 then it want to be able to enter bridge.mqtt.aws.clientid = ${BALENA_DEVICE_NAME_AT_INIT} in the config file so that the client id shown in the broker is device 1, however the actual client id showing in the broker is ${BALENA_DEVICE_NAME_AT_INIT}. I have also tried $BALENA_DEVICE_NAME_AT_INIT but this doesn't work either.

Does nayone have a suggestion as to how I can use this varibale in the emqx_bridge_mqtt.conf file?

Thanks.

**Comment by zhanghongtong** [comment]
Hi, @gercorri 
Sorry, we currently do not support the way of passing the key of environment variables into the configuration file.

**Comment by gercorri** [comment]
Hi @zhanghongtong , thanks for the clarification.

**Comment by zhanghongtong** [comment]
@gercorri You're welcome :)
