### ISSUE TITLE
why the last will message  has been sent

### ISSUE THREAD

**Issue by seqwait** [emqx/emqx#3588]
when i  sub topics 
$SYS/brokers/+/clients/+/disconnected
and last will message,  why the last will message  has been sent 
i can not recv disconnected message  until i unsub last will message!

**Comment by tigercl** [comment]
@seqwait What version of emqx are you using? If the version is higher than v3, then you can use the [tracer command](https://docs.emqx.io/broker/latest/en/advanced/cli.html) to trace your client, and then view the generated log, or provide the log to us for analysis.
