### ISSUE TITLE
Unable to form a cluster (manually) with two existing emqx broker nodes

### ISSUE THREAD

**Issue by reddygsc** [emqx/emqx#3592]
I  tried to form a cluster using two existing emqx brokers. I have done following steps as discussed in 
https://docs.emqx.io/tutorial/latest/en/cluster/setup_start.html#manage-the-emq-x-cluster-manually

1. Cookie is same
2. Names are in name@domain format
3. opened the ports as well,  as discussed in https://github.com/emqx/emqx/issues/1576

Still unable to form a cluster.

When i tried to execute command:
emqx_ctl join cluster emqx@node2 

the command is failing with following error:
failed to join the cluster {"node_down", }
Similar to this issue : https://github.com/emqx/emqx/issues/3466

Can you please help me with solving this issue

**Comment by HJianBo** [comment]
Hi @reddygsc First of all, What's emqx version and OS edition?

The `node_down` error means that These nodes don't communicate with each other. 

1. Ensure all nodes have started, and cookie
2. The following ports in `etc/emqx.conf` can be connected on each node
    ```
    node.dist_listen_min = 6369
    node.dist_listen_max = 6369
    ```
3. Execute the cluster command. It should be successful

**Comment by reddygsc** [comment]
Hi @HJianBo 

Both nodes i am trying cluster have, 

   OS edition : Ubuntu 18.04

   EMQX version: 4.1.0

Cookie is left same as default (Emqxsecretcookie)

port 6369 is open in both nodes as well.

Then i tried to cluster through command,  but it is failing. 

Can you please help me out here ?

**Comment by spring2maz** [comment]
If I understand correctly @HJianBo , the nodes should also be able to connect each other's EPMD port
In EMQX's case, it's `ekka_dist`, which by default listens on port `4370`.
And in case of node names being `node1` and `node2`, they might be listening at port `4371` and `4372`.

**Comment by spring2maz** [comment]
Edit: EMQX v4.1.0 is indeed by default using ekka for port mapping.
However I was wrong about 4370 being the name registration port.
It is actually the base port for `ekka_dist`.

To be clear, there are two different scenarios :

If EMQX is started with environment variable `WITH_EPMD` set:

1. Configure `node.dist_listen_min` and `node.dist_listen_max` to make port ranges in firewall rules more manageable. e.g.  set both to `6369`
2. Ensure Erlang's default EPMD port `4369` at each node is reachable from other nodes.

If `WITH_EPMD` is not set:

Ensure port `4371` at `node1` is reachable from other nodes, and `4372` for `node2` and so on.
If there is no number suffix in the node name (short name, the part before the `@` sign in the long name), then it's port `4370`.

**Comment by HJianBo** [comment]
Cool! @spring2maz This is a very detailed instruction.

**Comment by reddygsc** [comment]
i did try with opening all ports. It is working now. Thanks @spring2maz @HJianBo
