### ISSUE TITLE
How to listen for when new subscriptions occur?

### ISSUE THREAD

**Issue by little-eagle** [emqx/emqx#3593]
I am aware of this command which gives all of the subscriptions:

` ./bin/emqx_ctl subscriptions list`

So one option is for me to poll this every couple of seconds.

However what I'm really looking for is an "event based" way to be notified everytime a subscribes or unsubscribe occurs and to be told what the topic is. Any ideas? 

Thanks

**Comment by tigercl** [comment]
@little-eagle The `emqx-web-hook` plugin should be able to help you. Please refer to [Web-Hook](https://docs.emqx.io/broker/latest/en/advanced/webhook.html).

**Comment by little-eagle** [comment]
Thank you. I'm reading this now, very helpful.
