### ISSUE TITLE
emqx with etcd 3.4

### ISSUE THREAD

**Issue by yuvarajan1989k** [emqx/emqx#3594]
Hi,

I was trying to do autoclustering setup with etcd 3.4 . In the logs, i do see below error.

`2020-07-15 07:56:33.547 [error] Ekka(AutoCluster): AutoCluster stopped for lock error: {404,
                                                        "404 page not found\n"}`

When i use emqx with etcd2.0, it works fine.  my emqx version is 4.1.1

**Comment by zhanghongtong** [comment]
Hi, @yuvarajan1989k 
The log shows that when emqx access the etcd API, a 404 error is returned, please check your cluster configuration

**Comment by yuvarajan1989k** [comment]
Okay i will do that.  i was wondering that, does emqx support the latest version of etcd ?

**Comment by zhanghongtong** [comment]
Hi, @yuvarajan1989k 
I just [checked the code](https://github.com/emqx/ekka/blob/584a9c3cf8651e18af453c08a133d831cc2c040c/src/ekka_cluster_etcd.erl#L163), unfortunately, we currently only support 2.x version of etcd, we will update the support for etcd later

**Comment by yuvarajan1989k** [comment]
Any idea for the time frame. I m in the mid of my work.  thank you

**Comment by zhanghongtong** [comment]
CC @tigercl

**Comment by fizzse** [comment]
when will etcd3.4 be supported?

**Comment by DDDHuang** [comment]
Etcd3.4 will supported in version 5.0
