### ISSUE TITLE
When did start supporting ubuntu20.04 installation

### ISSUE THREAD

**Issue by zhuqiyun** [emqx/emqx#3595]

**Comment by zhanghongtong** [comment]
Hi, @zhuqiyun 
We plan to provide the installation package of ubuntu 20.04 in version 4.2.0

**Comment by seguidor777** [comment]
Hey there, Is EMQX v4.2.5 fully supported on Ubuntu 20.04? I cannot connect via SSL and I'm not sure if I'm missing to configure something to make it work

**Comment by k32** [comment]
Hello @seguidor777 ,
Could you create a new issue, and supply more details about your setup. Which method did you use to install the broker, emqx.log and erlang.log files, etc. to help us troubleshoot your problem?

**Comment by seguidor777** [comment]
https://github.com/emqx/emqx/issues/5555
