### ISSUE TITLE
Dashboard SSL/TLS

### ISSUE THREAD

**Issue by berayb** [emqx/emqx#3596]
https://docs.emqx.io/tutorial/latest/en/cluster/balancer.html

SSL/TLS works after following this example. Is it possible to activate the 18084 port the same way?

Thanks,

**Comment by spring2maz** [comment]
Hi @berayb 
I am not quite following your question.
The link you shared is a tutorial for load balancing MQTT (or web-socket) 
connections between EMQX nodes in the cluster.
By 'SSL/TSL works', do you mean you made load balancer terminate TLS?
As for 18084 I suppose it's the https listener for dashboard.
If you have a load balancer which terminates TLS, I suppose port 18083 (http) should work just fine.

**Comment by berayb** [comment]
Hi @spring2maz, we are able to connect through 8883 port with the guidance at that link. The load balancer manage the certification. However, if we apply the same method for 18084 and enable the config, the broker crashes.

**Comment by spring2maz** [comment]
Hi @berayb 
I was confused because it's 18083/HTTP (not 18084/HTTPS) described in the linked document.
Could you paste the crash logs so we can understand better on what went wrong in your case ?

**Comment by berayb** [comment]
Hi @spring2maz, you may see the configuration in the config file of the dashboard plugin. It expects folder path but it is handled by load balancer in this case.

**Comment by spring2maz** [comment]
hi @berayb 

Do you mean these configs?

```
## The port that the Dashboard HTTPS listener will bind.
##
## Value: Port
##
## Examples: 18084
## dashboard.listener.https = 18084

## Path to the file containing the user's private PEM-encoded key.
##
## Value: File
## dashboard.listener.https.keyfile = etc/certs/key.pem

## Path to a file containing the user certificate.
##
## Value: File
## dashboard.listener.https.certfile = etc/certs/cert.pem
```

If you have this enabled, emqx dashboard will listen on port 10804 for TLS handsakes.

If you make load balancer terminate TLS (assuming this is what implied in your reply: "The load balancer manage the certification"), the target listener should be plaintext. For MQTT, it's port 1883, for dashboard it's port 10803.
`mqtt client <--- tls ---> LB:8883 <--- plaintext ---> EMQX:1883`
`web browser <--- https ---> LB:18083 <--- http ---> EMQX:18083`

If want you want is actually to use https between LB:18084 and EMQX:18084?
`web browser <--- https ---> LB:18084 <--- https ---> EMQX:18084`
then you'll have to make LB re-encrypt traffic towards EMQX
which I may not be able to help based on my limited knowledge in AWS load balancers.

**Comment by spring2maz** [comment]
To be more clear about my last update in the reply above:
This might work:

`web browser <--- TCP ---> LB:1808x <--- TCP ---> EMQX:18084`

in such case, the LB listener works at TCP layer, https is transparent to it.
