### ISSUE TITLE
listener.tcp.external.max_conn_rate not working

### ISSUE THREAD

**Issue by AylaAsia-GaryJin** [emqx/emqx#3598]
**Environment**:

- EMQ X version (e.g. `emqx_ctl status`): 4.0.5 (build image from the source code emqx-rel)
- Hardware configuration (e.g. `lscpu`):
- OS (e.g. `cat /etc/os-release`): Ubuntu 16.04.6
- Kernel (e.g. `uname -a`):
- Erlang/OTP version (in case you build emqx from source code): 22.1
- Others:

**What happened and what you expected to happen**:
Happened: ``listener.tcp.external.max_conn_rate=10`` and make new connections increase 20 per second, but all the connections connected.
Expected: half of the connections connect failed.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Comment by HJianBo** [comment]
It does not work on multiple acceptors (e.g: `listener.tcp.external.acceptors = 8`)

We will try to fix it at v4.2-alpha.3

**Comment by heyouzhi** [comment]
@HJianBo   你好，请问 这里 max_conn_rate 在配置多个 acceptors时不生效的问题有没有计划准备修复？

这里max_conn_rate参数非常有用。尤其是在网络波动，影响到了很多设备，设备大面积掉线重连时emqx机器的负载将会非常高，跑满cpu,导致emq对消息收发响应及其缓慢。
如果这个参数能限制设备建立链接的速度，就可以限制住机器的负载，保护服务端。
