### ISSUE TITLE
HTTP Auth Plugin Delay

### ISSUE THREAD

**Issue by amalikctec** [emqx/emqx#3601]
**Environment**:

- EMQ X version (e.g. `emqx_ctl status`): 4.1.0
- Hardware configuration (e.g. `lscpu`): , Intel Corei5 @2.3GHZ, x86_64
- OS (e.g. `cat /etc/os-release`): Ubuntu 18.04.4 LTS (Bionic Beaver)
- Kernel (e.g. `uname -a`): 5.3.0-62-generic
- Erlang/OTP version (in case you build emqx from source code): 
- Others:

**What happened and what you expected to happen**:
I ran a container using the latest emqx docker image and enable the emqx_auth_http plugin. If the plugin is enabled it takes 5-10 seconds for a client to connect to the server now (even though the auth web server is ran locally). The client should be able to to connect quickly.

**How to reproduce it (as minimally and precisely as possible)**:
1. Run a container using the following script (replace the EMQX_AUTH__HTTP__AUTH_REQ variable with your setting).
[emqx_docker_run.zip](https://github.com/emqx/emqx/files/4937210/emqx_docker_run.zip)

2. Run the following node.js auth web service locally.
[emqx_auth.zip](https://github.com/emqx/emqx/files/4937217/emqx_auth.zip)

3. Open the emqx dasboard. Go to Tools -> Websocket and click Connect. You will see a delay of ~10 seconds before the client's status changes to connected status (even though the service sent a 200 status 10 seconds ago)

**Anything else we need to know?**:

**Comment by tigercl** [comment]
@amalikctec Can you provide the debug log in emqx?

**Comment by amalikctec** [comment]
Found the issue after looking at the logs. 

After performing the client authentication (which passes), emqx performs the super user authorization specified here:
https://docs.emqx.io/broker/v4.1/en/advanced/auth-http.html

The delay is caused by the fact that this endpoint has not been configured and it eventually logs the following error:
2020-07-20 09:26:55.317 [error] <<"mqttjs_221fb132f7">>@172.17.0.1:47386 [Auth http] Request superuser url http://127.0.0.1:8991/mqtt/superuser, error: {failed_connect,
                                                                                [{to_address,
                                                                                  {"127.0.0.1",
                                                                                   8991}},
                                                                                 {inet,
                                                                                  [inet],
                                                                                  econnrefused}]}

The delay is resolved by configuring the endpoint. Although the value returned by the web service has no bearing on the results of the connect operation.

Here are the updated scripts and log:
[emqx_docker_run.zip](https://github.com/emqx/emqx/files/4946958/emqx_docker_run.zip)
[emqx_auth.zip](https://github.com/emqx/emqx/files/4946962/emqx_auth.zip)
[emqx.txt](https://github.com/emqx/emqx/files/4946967/emqx.txt)

**Comment by HJianBo** [comment]
okay, We will consider turning off this configuration by default.

**Comment by HJianBo** [comment]
Hi @amalikctec It has released in 4.2-beta.1. Thanks for your suggestion

**Comment by amalikctec** [comment]
happy to help!
