### ISSUE TITLE
Manually package the Docker image, the operation crashes and fails.

### ISSUE THREAD

**Issue by LvCodeing** [emqx/emqx#3604]
- EMQ X version ：4.0.7
- OS ：ubuntu:16.04
- Erlang/OTP version: 22.3
- Others:

The EMQX docker image emqx/emqxv4.0.7-alpine3.10-amd64 is generated successfully, but it runs abnormally. After running for a few seconds, the mirroring operation was stopped and a crash exception occurred.

**Comment by zhanghongtong** [comment]
Hi, @LvCodeing 
Please show the crashed container log

**Comment by LvCodeing** [comment]
> Hi, @LvCodeing
> Please show the crashed container log

There are 2 erts file directories in the mirror file, as follows:
bin data erts-10.7 erts-10.7.2.1 etc lib log releases

The content of the crash file:
[链接:https://pan.baidu.com/s/1bCoQAC27isrmm8nFq0EP7Q  密码:9dbu]

=erl_crash_dump:0.5
Mon Jul 20 01:52:32 2020
Slogan: Kernel pid terminated (application_controller) ({application_start_failure,kernel,{{shutdown,{failed_to_start_child,kernel_safe_sup,{on_load_function_failed,bcrypt_nif}}},{kernel,start,[normal,[]]}}})
System version: Erlang/OTP 22 [erts-10.7.2.1] [source] [64-bit] [smp:4:4] [ds:4:4:8] [async-threads:4]
Compiled: Fri Jul 10 19:50:14 2020
Taints: 
Atoms: 44531
Calling Thread: scheduler:1
=scheduler:1
Scheduler Sleep Info Flags: 
Scheduler Sleep Info Aux Work: THR_PRGR_LATER_OP
Current Port: 
Run Queue Max Length: 0
Run Queue High Length: 0
Run Queue Normal Length: 0
Run Queue Low Length: 0
Run Queue Port Length: 0
Run Queue Flags: OUT_OF_WORK | HALFTIME_OUT_OF_WORK | NONEMPTY | EXEC
Current Process: <0.0.0>
Current Process State: Running
Current Process Internal State: ACT_PRIO_NORMAL | USR_PRIO_NORMAL | PRQ_PRIO_NORMAL | ACTIVE | RUNNING
Current Process Program counter: 0x00007fa43b29fa80 (init:sleep/1 + 64)
Current Process CP: 0x00007fa43b29c0b8 (init:boot_loop/2 + 1944)
Current Process Limited Stack Trace:
0x00007fa4329fca20:SReturn addr 0xD780E838 (<terminate process normally>)
=scheduler:2
Scheduler Sleep Info Flags: SLEEPING | POLL_SLEEPING | WAITING
Scheduler Sleep Info Aux Work: 
Current Port: 
Run Queue Max Length: 0
Run Queue High Length: 0
Run Queue Normal Length: 0
Run Queue Low Length: 0
Run Queue Port Length: 0
Run Queue Flags: OUT_OF_WORK | HALFTIME_OUT_OF_WORK
Current Process: 
=scheduler:3
Scheduler Sleep Info Flags: SLEEPING | TSE_SLEEPING | WAITING
Scheduler Sleep Info Aux Work: 
Current Port: 
Run Queue Max Length: 0
Run Queue High Length: 0
Run Queue Normal Length: 0
Run Queue Low Length: 0
Run Queue Port Length: 0
Run Queue Flags: OUT_OF_WORK | HALFTIME_OUT_OF_WORK
Current Process: 
=scheduler:4
Scheduler Sleep Info Flags: SLEEPING | TSE_SLEEPING | WAITING
Scheduler Sleep Info Aux Work: 
Current Port: 
Run Queue Max Length: 0
Run Queue High Length: 0
Run Queue Normal Length: 0
Run Queue Low Length: 0
Run Queue Port Length: 0
Run Queue Flags: OUT_OF_WORK | HALFTIME_OUT_OF_WORK
Current Process: 
=dirty_cpu_scheduler:5
Scheduler Sleep Info Flags: SLEEPING | TSE_SLEEPING | WAITING
Scheduler Sleep Info Aux Work: 
Current Process: 
=dirty_cpu_scheduler:6
Scheduler Sleep Info Flags: SLEEPING | TSE_SLEEPING | WAITING
Scheduler Sleep Info Aux Work: 
Current Process: 
=dirty_cpu_scheduler:7
Scheduler Sleep Info Flags: SLEEPING | TSE_SLEEPING | WAITING
Scheduler Sleep Info Aux Work: 
Current Process: 
=dirty_cpu_scheduler:8
Scheduler Sleep Info Flags: SLEEPING | TSE_SLEEPING | WAITING
Scheduler Sleep Info Aux Work: 
Current Process: 
=dirty_cpu_run_queue
Run Queue Max Length: 0
Run Queue High Length: 0
Run Queue Normal Length: 0
Run Queue Low Length: 0
Run Queue Port Length: 0
Run Queue Flags: OUT_OF_WORK | HALFTIME_OUT_OF_WORK
=dirty_io_scheduler:9
Scheduler Sleep Info Flags: SLEEPING | TSE_SLEEPING | WAITING
Scheduler Sleep Info Aux Work: 
Current Process: 
=dirty_io_scheduler:10
Scheduler Sleep Info Flags: SLEEPING | TSE_SLEEPING | WAITING
Scheduler Sleep Info Aux Work: 
Current Process: 
=dirty_io_scheduler:11
Scheduler Sleep Info Flags: SLEEPING | TSE_SLEEPING | WAITING
Scheduler Sleep Info Aux Work: 
Current Process: 
=dirty_io_scheduler:12
Scheduler Sleep Info Flags: SLEEPING | TSE_SLEEPING | WAITING
Scheduler Sleep Info Aux Work: 
Current Process: 
=dirty_io_scheduler:13
Scheduler Sleep Info Flags: SLEEPING | TSE_SLEEPING | WAITING
Scheduler Sleep Info Aux Work: 
Current Process: 
=dirty_io_scheduler:14
Scheduler Sleep Info Flags: SLEEPING | TSE_SLEEPING | WAITING
Scheduler Sleep Info Aux Work: 
Current Process: 
=dirty_io_scheduler:15
Scheduler Sleep Info Flags: SLEEPING | TSE_SLEEPING | WAITING
Scheduler Sleep Info Aux Work: 
Current Process: 
=dirty_io_scheduler:16
Scheduler Sleep Info Flags: SLEEPING | TSE_SLEEPING | WAITING
Scheduler Sleep Info Aux Work: 
Current Process: 
=dirty_io_run_queue
Run Queue Max Length: 0
Run Queue High Length: 0
Run Queue Normal Length: 0
Run Queue Low Length: 0
Run Queue Port Length: 0
Run Queue Flags: OUT_OF_WORK | HALFTIME_OUT_OF_WORK
=memory
total: 117074264
processes: 25787816
processes_used: 25622896
system: 91286448
atom: 1525929
atom_used: 1501734
binary: 25336
code: 31357032
ets: 33565848
=hash_table:atom_tab
size: 51437
used: 29772
objs: 44530
depth: 7
=index_table:atom_tab
size: 45056
limit: 1048576
entries: 44531
=hash_table:module_code
size: 797
used: 797
objs: 1217
depth: 3
=index_table:module_code
size: 2048
limit: 65536
entries: 1217
=hash_table:export_list
size: 12853
used: 9831
objs: 18369
depth: 8
=index_table:export_list
size: 18432
limit: 524288
entries: 18369
=hash_table:export_list
size: 12853
used: 9768
objs: 18135
depth: 8
=hash_table:process_reg
size: 23
used: 5
objs: 5
depth: 1
=hash_table:fun_table
size: 4813
used: 3891
objs: 7686
depth: 7
=hash_table:node_table
size: 11
used: 1
objs: 1
depth: 1
=hash_table:dist_table
size: 11
used: 2
objs: 2
depth: 1
=allocated_areas
sys_misc: 57672
static: 1053984
atom_space: 753848 729653
atom_table: 772081
module_table: 444360
export_table: 751260
export_list: 3232944
register_table: 300
fun_table: 38618
module_refs: 58032
loaded_code: 26831818
dist_table: 971
node_table: 251
bits_bufs_size: 0
bif_timer: 0
process_table: 25165824
port_table: 12582912
ets_misc: 33554432
=allocator:sys_alloc
option e: true
option m: libc
=allocator:temp_alloc[0]
versions: 2.1 3.0
option e: true
option t: 5
option ramv: false
option atags: false
option sbct: 524288
option asbcst: 4145152
option rsbcst: 90
option rsbcmt: 80
option rmbcmt: 100
option mmbcs: 131072
option mmsbc: 256
option mmmbc: 18446744073709551615
option lmbcs: 10485760
option smbcs: 1048576
option mbcgs: 10
option acul: 0
option mbsd: 3
option as: gf
mbcs blocks: 0 5 5
mbcs blocks size: 0 10904 10904
mbcs carriers: 1 1 1
mbcs mseg carriers: 0
mbcs sys_alloc carriers: 1
mbcs carriers size: 131072 131072 131072
mbcs mseg carriers size: 0
mbcs sys_alloc carriers size: 131072
sbcs blocks: 0 0 0
sbcs blocks size: 0 0 0
sbcs carriers: 0 0 0
sbcs mseg carriers: 0
sbcs sys_alloc carriers: 0
sbcs carriers size: 0 0 0
sbcs mseg carriers size: 0
sbcs sys_alloc carriers size: 0
temp_alloc calls: 1777
temp_free calls: 1777
temp_realloc calls: 1
mseg_alloc calls: 0
mseg_dealloc calls: 0
mseg_realloc calls: 0
sys_alloc calls: 1
sys_free calls: 0
sys_realloc calls: 0
=allocator:temp_alloc[1]
versions: 0.9 3.0
option e: true
option t: 5
option ramv: false
option atags: false
option sbct: 524288
option asbcst: 4145152
option rsbcst: 90
option rsbcmt: 80
option rmbcmt: 100
option mmbcs: 131072
option mmsbc: 256
option mmmbc: 18446744073709551615
option lmbcs: 10485760
option smbcs: 1048576
option mbcgs: 10
option acul: 0
option as: af
mbcs blocks: 1 5 5
mbcs blocks size: 65544 635480 635480
mbcs carriers: 1 2 2
mbcs mseg carriers: 0
mbcs sys_alloc carriers: 1
mbcs carriers size: 131072 1179648 1179648
mbcs mseg carriers size: 0
mbcs sys_alloc carriers size: 131072
sbcs blocks: 0 0 0
sbcs blocks size: 0 0 0
sbcs carriers: 0 0 0
sbcs mseg carriers: 0
sbcs sys_alloc carriers: 0
sbcs carriers size: 0 0 0
sbcs mseg carriers size: 0
sbcs sys_alloc carriers size: 0
temp_alloc calls: 35642
temp_free calls: 35641
temp_realloc calls: 19
mseg_alloc calls: 4
mseg_dealloc calls: 4
mseg_realloc calls: 0
sys_alloc calls: 1
sys_free calls: 0
sys_realloc calls: 0
=allocator:temp_alloc[2]
versions: 0.9 3.0
option e: true
option t: 5
option ramv: false
option atags: false
option sbct: 524288
option asbcst: 4145152
option rsbcst: 90
option rsbcmt: 80
option rmbcmt: 100
option mmbcs: 131072
option mmsbc: 256
option mmmbc: 18446744073709551615
option lmbcs: 10485760
option smbcs: 1048576
option mbcgs: 10
option acul: 0
.......

binary_find_trap
binary_copy_trap
binary
bif_return_trap
big
band
bag
badsig
badmatch
badmap
badkey
badfun
badfile
badarity
badarith
badarg
backtrace_depth
backtrace
awaiting_unload
awaiting_load
await_sched_wall_time_modifications
await_result
await_proc_exit
await_port_send_result
await_microstate_accounting_modifications
await_exit
auto_connect
attributes
atom_used
atom
asynchronous
async
asn1
arity
arg0
args
apply
anycrlf
any
andthen
andalso
and
anchored
amd64
already_loaded
allow_passive_connect
alloc_util_allocators
allocator_sizes
allocator
allocated_areas
allocated
alloc_sizes
alloc_info
all_names
all_but_first
all
alive
active_tasks_all
active_tasks
active
ac
absoluteURI
abs_path
abort
'EXIT'
'UP'
'DOWN'
'3RT$'
undefined_lambda
undefined_function
nocatch
undefined
exit
error
throw
return
call
normal
timeout
infinity
''
'$end_of_table'
'nonode@nohost'
'_'
true
false
=end

**Comment by zhanghongtong** [comment]
> There are 2 erts file directories in the mirror file, as follows:
> bin data erts-10.7 erts-10.7.2.1 etc lib log releases

Please check your emqx docker image, our image only has erts-10.5.6

**Comment by LvCodeing** [comment]
Docker image file download:emqx.v4.0.7-alpine3.10-amd64.tar*
链接:https://pan.baidu.com/s/1Rq2cfdn4O3YkKj8g99t89A  密码:2844

**Comment by zhanghongtong** [comment]
We have not provided a download of Baidu Cloud Disk, please get our image from [docker hub](https://hub.docker.com/r/emqx/emqx) or [emqx.io](https://www.emqx.io/downloads#broker)

**Comment by LvCodeing** [comment]
> We have not provided a download of Baidu Cloud Disk, please get our image from [docker hub](https://hub.docker.com/r/emqx/emqx) or [emqx.io](https://www.emqx.io/downloads#broker)

It's all because I didn't make it clear. The emqx.v4.0.7-alpine3.10-amd64.tar file is a docker file generated by me through the make emqx-docker-build command. It does not mean that this file is provided by the government. It is necessary that you can run my docker and you will know all the abnormal conditions.

**Comment by zhanghongtong** [comment]
Hi, @LvCodeing 
Please ensure that your code is clean. The reason for the two `erts` directories is because the code has been polluted. Please execute `make distclean` before `make emqx-docker-build`, and ensure that there is no `_build` and `_packages` directories in the code root directory.

**Comment by LvCodeing** [comment]
> Hi, @LvCodeing
> Please ensure that your code is clean. The reason for the two `erts` directories is because the code has been polluted. Please execute `make distclean` before `make emqx-docker-build`, and ensure that there is no `_build` and `_packages` directories in the code root directory.

I tried again and confirmed that the _build and _packages directories do not exist. Steps:
1.git clone https://github.com/emqx/emqx-rel.git
2.sudo make distclean
3.sudo make emqx-docker-build
However, it failed in the end, the specific error message:
===> Fetching gen_coap (from {git,"https://github.com/emqx/gen_coap",{tag,"v0.2.3"}})
===> Fetching gen_rpc (from {git,"https://github.com/emqx/gen_rpc",{tag,"2.4.1"}})
===> Fetching gproc v0.8.0
===> Downloaded package, caching at /root/.cache/rebar3/hex/hexpm/packages/gproc-0.8.0.tar
===> Fetching jiffy (from {git,"https://github.com/emqx/jiffy",{tag,"1.0.2"}})
===> Failed to fetch and copy dep: {git,"https://github.com/emqx/jiffy",
                                   {tag,"1.0.2"}}
===> Failed to fetch and copy dep: {git,"https://github.com/emqx/jiffy",
                                   {tag,"1.0.2"}}
make: *** [Makefile:51: emqx] Error 1
The command '/bin/sh -c cd /emqx_rel && make ${EMQX_NAME}' returned a non-zero code: 2
Makefile:37: recipe for target 'build' failed
make[1]: *** [build] Error 2
make[1]: Leaving directory '/home/dev/Documents/work/erWorkspace/v4.0/emqx-rel-docker/deploy/docker'
Makefile:116: recipe for target 'emqx-docker-build' failed
make: *** [emqx-docker-build] Error 2

**Comment by zhanghongtong** [comment]
> Failed to fetch and copy dep: {git,"https://github.com/emqx/jiffy", {tag,"1.0.2"}}

This error is that the `emqx/jiffy` project is not obtained. Generally speaking, it is caused by a poor network. It is recommended to check whether the network can quickly access GitHub

**Comment by LvCodeing** [comment]
> > Failed to fetch and copy dep: {git,"https://github.com/emqx/jiffy", {tag,"1.0.2"}}
> 
> This error is that the `emqx/jiffy` project is not obtained. Generally speaking, it is caused by a poor network. It is recommended to check whether the network can quickly access GitHub

===> Downloaded package, caching at /root/.cache/rebar3/hex/hexpm/packages/jsx-2.10.0.tar
===> Linking _build/default/plugins/jsx to _build/emqx/plugins/jsx
===> Compiling jsx
===> Compiling coveralls
===> Fetching emqx_statsd (from {git,"https://github.com/emqx/emqx-statsd",{tag,"v4.0.7"}})
===> Fetching emqx_stomp (from {git,"https://github.com/emqx/emqx-stomp",{tag,"v4.0.7"}})
===> Fetching emqx_web_hook (from {git,"https://github.com/emqx/emqx-web-hook",
                         {tag,"v4.0.7"}})
===> Failed to fetch and copy dep: {git,"https://github.com/emqx/emqx-web-hook",
                                   {tag,"v4.0.7"}}
make: *** [Makefile:51: emqx] Error 1
The command '/bin/sh -c cd /emqx_rel && make ${EMQX_NAME}' returned a non-zero code: 2
Makefile:37: recipe for target 'build' failed
make[1]: *** [build] Error 2
make[1]: Leaving directory '/home/servers/test/emqx-rel/deploy/docker'
Makefile:116: recipe for target 'emqx-docker-build' failed
make: *** [emqx-docker-build] Error 2

**Comment by LvCodeing** [comment]
> > Failed to fetch and copy dep: {git,"https://github.com/emqx/jiffy", {tag,"1.0.2"}}
> 
> This error is that the `emqx/jiffy` project is not obtained. Generally speaking, it is caused by a poor network. It is recommended to check whether the network can quickly access GitHub

I performed the above operation on the Alibaba Cloud server with a bandwidth of 10M. I tried several times and reported the following error. Each retry starts from the beginning and cannot start at the last error position.

===> Fetching emqx_statsd (from {git,"https://github.com/emqx/emqx-statsd",{tag,"v4.0.7"}})
===> Fetching emqx_stomp (from {git,"https://github.com/emqx/emqx-stomp",{tag,"v4.0.7"}})
===> Fetching emqx_web_hook (from {git,"https://github.com/emqx/emqx-web-hook",
                         {tag,"v4.0.7"}})
===> Failed to fetch and copy dep: {git,"https://github.com/emqx/emqx-web-hook",
                                   {tag,"v4.0.7"}}
make: *** [Makefile:51: emqx] Error 1
The command '/bin/sh -c cd /emqx_rel && make ${EMQX_NAME}' returned a non-zero code: 2
Makefile:37: recipe for target 'build' failed
make[1]: *** [build] Error 2
make[1]: Leaving directory '/home/servers/test/emqx-rel/deploy/docker'
Makefile:116: recipe for target 'emqx-docker-build' failed
make: *** [emqx-docker-build] Error 2

**Comment by zhanghongtong** [comment]
@LvCodeing 
If the make fails due to network reasons, you do not need to execute `make distclean` between the two `make emqx-docker-build`, so that you can continue to pull the dependencies from the failed location

**Comment by LvCodeing** [comment]
> @LvCodeing
> If the make fails due to network reasons, you do not need to execute `make distclean` between the two `make emqx-docker-build`, so that you can continue to pull the dependencies from the failed location

What bandwidth is required to compile emqx docker? The home network and the company's network have not been successful.

**Comment by LvCodeing** [comment]
Step 16/26 : COPY --from=builder /emqx_rel/_build/emqx*/rel/emqx /opt/emqx
 ---> d907425f38c5
Step 17/26 : RUN ln -s /opt/emqx/bin/* /usr/local/bin/
 ---> Running in b2fb49e2da24
Removing intermediate container b2fb49e2da24
 ---> 1d84ea070ad3
Step 18/26 : RUN apk add --no-cache curl ncurses-libs openssl sudo libstdc++
 ---> Running in fb60e8a49af6
fetch http://dl-cdn.alpinelinux.org/alpine/v3.10/main/x86_64/APKINDEX.tar.gz
WARNING: Ignoring http://dl-cdn.alpinelinux.org/alpine/v3.10/main/x86_64/APKINDEX.tar.gz: temporary error (try again later)
fetch http://dl-cdn.alpinelinux.org/alpine/v3.10/community/x86_64/APKINDEX.tar.gz
WARNING: Ignoring http://dl-cdn.alpinelinux.org/alpine/v3.10/community/x86_64/APKINDEX.tar.gz: temporary error (try again later)
ERROR: unsatisfiable constraints:
  curl (missing):
    required by: world[curl]
  libstdc++ (missing):
    required by: world[libstdc++]
  ncurses-libs (missing):
    required by: world[ncurses-libs]
  openssl (missing):
    required by: world[openssl]
  sudo (missing):
    required by: world[sudo]
The command '/bin/sh -c apk add --no-cache curl ncurses-libs openssl sudo libstdc++' returned a non-zero code: 5
Makefile:37: recipe for target 'build' failed
make[1]: *** [build] Error 5
make[1]: Leaving directory '/home/servers/test/emqx-rel/deploy/docker'
Makefile:116: recipe for target 'emqx-docker-build' failed
make: *** [emqx-docker-build] Error 2

**Comment by zhanghongtong** [comment]
Hi, @LvCodeing 
For some reasons, your network access to github and alpine's software repo is not so smooth, you need to solve it yourself

**Comment by LvCodeing** [comment]
> Hi, @LvCodeing
> For some reasons, your network access to github and alpine's software repo is not so smooth, you need to solve it yourself

Now that the network problem has been solved, I fetch my own warehouse code when it fails every time, as follows:

===> Linking _build/default/plugins/jsx to _build/emqx/plugins/jsx
===> Compiling jsx
===> Compiling coveralls
===> Fetching emqx_auth_clientid (from {git,"https://github.com/emqx/emqx-auth-clientid",
                              {tag,"v4.0.7"}})
===> Fetching emqx_auth_http (from {git,"https://github.com/emqx/emqx-auth-http",
                          {tag,"v4.0.7"}})
===> Fetching emqx_auth_jwt (from {git,"https://github.com/emqx/emqx-auth-jwt",
                         {tag,"v4.0.7"}})
===> Fetching emqx_auth_ldap (from {git,"https://github.com/emqx/emqx-auth-ldap",
                          {tag,"v4.0.7"}})
===> Fetching emqx_auth_mongo (from {git,"https://github.com/emqx/emqx-auth-mongo",
                           {tag,"v4.0.7"}})
===> Fetching emqx_auth_mysql (from {git,"https://github.com/emqx/emqx-auth-mysql",
                           {tag,"v4.0.7"}})
===> Fetching emqx_auth_pgsql (from {git,"https://github.com/emqx/emqx-auth-pgsql",
                           {tag,"v4.0.7"}})
===> Fetching emqx_auth_redis (from {git,"https://github.com/LvCodeing/emqx-auth-redis.git",
                           {tag,"v4.0.7"}})
===> Failed to fetch and copy dep: {git,"https://github.com/LvCodeing/emqx-auth-redis.git",
                                   {tag,"v4.0.7"}}
make: *** [Makefile:51: emqx] Error 1
The command '/bin/sh -c cd /emqx_rel && make ${EMQX_NAME}' returned a non-zero code: 2
make[1]: *** [build] Error 2
make: *** [emqx-docker-build] Error 2

**Comment by LvCodeing** [comment]
Hi, @zhanghongtong
Pulling emqx-auth-redis alone has no task problem

Martin-MacBook:Downloads zsh$ git clone https://github.com/LvCodeing/emqx-auth-redis.git
Cloning into 'emqx-auth-redis'...
remote: Enumerating objects: 27, done.
remote: Counting objects: 100% (27/27), done.
remote: Compressing objects: 100% (23/23), done.
remote: Total 27 (delta 1), reused 24 (delta 1), pack-reused 0
Unpacking objects: 100% (27/27), done.

**Comment by HJianBo** [comment]
Hi, @LvCodeing  Using ``Makefile`` to pull project dependencies during compilation is no different than using git to pull the project manually.  **The point is that, for a well-known reason, in some areas, it is very difficult for the host to access some external resources. You should need a proxy or minor repository to speed up this progress**

If it fails, you have to retry it again and again, or manually pull the failed repository. E.g:

```
cd _checkout
git clone -b v4.0.7  https://github.com/LvCodeing/emqx-auth-redis.git emqx_auth_redis
```
