### ISSUE TITLE
Client Online and Offline Events

### ISSUE THREAD

**Issue by Eric-Sunjian** [emqx/emqx#3606]
I subscribed to the SYSTEM TOPICS "$SYS/brokers/emqx@127.0.0.1/clients/+/connected" and "$SYS/brokers/emqx@127.0.0.1/clients/+/disconnected" using QOS 2 . 
Then i received message :'{"username":"test","ts":1594630342083,"sockport":8083,"proto_ver":4,"proto_name":"MQTT","keepalive":60,"ipaddress":"47.97.196.235","expiry_interval":0,"connected_at":1594630342,"connack":0,"clientid":"mqtts_99379cc2","clean_start":true}' 
with TOPIC:'$SYS/brokers/emqx@127.0.0.1/clients/mqtts_99379cc2/connected'.

But I have not received the message that the client is offline.

This happens very rarely

**CentOS Linux release 7.6.1810 (Core)**:

- EMQ X version (e.g. `emqx_ctl status`): 4.0.6
- Hardware configuration (e.g. `lscpu`):
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                16
On-line CPU(s) list:   0-15
Thread(s) per core:    2
Core(s) per socket:    8

- OS (e.g. `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):Linux a207016 3.10.0-957.1.3.el7.x86_64
- Erlang/OTP version (in case you build emqx from source code): 
- Others:

**What happened and what you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Comment by tigercl** [comment]
@Eric-Sunjian This feature usually does not cause problems, how do you confirm that the device is offline?

**Comment by HJianBo** [comment]
Or please check the process to see if any errors appear.

**Comment by Eric-Sunjian** [comment]
> @Eric-Sunjian This feature usually does not cause problems, how do you confirm that the device is offline?

I used Command line interface 'emqx_ctl clients list',and did not see the device online
