### ISSUE TITLE
HTTP ACL parameter undefined

### ISSUE THREAD

**Issue by Baloneo** [emqx/emqx#3608]
**Environment**:

- EMQ X version (e.g. `emqx_ctl status`): 4.0.7
- Hardware configuration (e.g. `lscpu`): x86_64
- OS (e.g. `cat /etc/os-release`):ubuntu 18.04
- Kernel (e.g. `uname -a`):4.15.0-99-generic
- Erlang/OTP version (in case you build emqx from source code): 
- Others:

**What happened and what you expected to happen**:
The mqtt client can't see it in the dashboard.But always have http acl request, and request parameters are undefined. (It is available under normal circumstances, I configured the acl file correctly. )
```
username:undefined, topic:/sub/product/1/XXXX/set, access:1, clientID:undefined, ipAddr:59.41.94.137, protocol:mqtt, mountpoint:undefined
```

Abnormal connection disconnect reason:
```
"reason":"function_clause"
```

**How to reproduce it (as minimally and precisely as possible)**:
The anomaly occurred twice, but I can't reproduce it yet.

**Anything else we need to know?**:
You can see that the number of tcp connections has this abnormal connection. But The mqtt client can't see it in the dashboard.

**Comment by tigercl** [comment]
@Baloneo Can you provide your ACL configuration content and the actual HTTP request content?

**Comment by Baloneo** [comment]
ACL Config
```
##--------------------------------------------------------------------
## ACL request.
##
## Variables:
##  - %A: 1 | 2, 1 = sub, 2 = pub
##  - %u: username
##  - %c: clientid
##  - %a: ipaddress
##  - %r: protocol
##  - %m: mountpoint
##  - %t: topic
##
## Value: URL
auth.http.acl_req = http://127.0.0.1:7000/api/v1/emqx/mqtt/acl
## Value: post | get | put
auth.http.acl_req.method = post
## Value: Params
auth.http.acl_req.params = access=%A,username=%u,clientid=%c,ipaddr=%a,topic=%t,mountpoint=%m,protocol=%r

```

http request handler
```
func Acl(c *gin.Context) {
	username := c.PostForm("username")
	topic := c.PostForm("topic")
	access := c.PostForm("access")
	clientID := c.PostForm("clientid")
	ipAddr := c.PostForm("ipaddr")
	mountpoint := c.PostForm("mountpoint")
	protocol := c.PostForm("protocol")

	fmt.Printf("ACL: username:%s, topic:%s, access:%s, clientID:%s, ipAddr:%s, protocol:%s, mountpoint:%s\n", username, topic, access, clientID, ipAddr, protocol, mountpoint)

```

**Comment by Baloneo** [comment]
> @Baloneo Can you provide your ACL configuration content and the actual HTTP request content?

**Comment by Baloneo** [comment]
This problem seems to occur when a non-utf8 message is received.

**Comment by tigercl** [comment]
@Baloneo Under normal circumstances, the `clientid` will not be undefined. I just confirmed this, so I don’t know if you can provide network packet capture data?

**Comment by tigercl** [comment]
@Baloneo Messages that are not utf-8 encoded do cause some strange problems, please use utf-8.

**Comment by Baloneo** [comment]
Difficult to reproduce, mqtt client is an embedded device, sometimes the client will send non-utf-8 will appear this problem, resulting in HTTP ACL check failure, theoretically the connection will be disconnected, but the heartbeat package is still there, resulting in the embedded device can not know whether the mqtt connection is broken. I think this undefined is created by emqx.

**Comment by Baloneo** [comment]
Why is the heartbeat of non-utf-8, mqtt heartbeat still, and http ACL getting undefined.

> @Baloneo Messages that are not utf-8 encoded do cause some strange problems, please use utf-8.

**Comment by Baloneo** [comment]
cat /var/log/emqx/emqx.log.1
```
2020-08-01 14:52:23.711 [error] <<"39B3100">>@61.140.74.152:28280 [MQTT]
Parse failed for function_clause
[{emqx_frame,parse_packet,[{mqtt_packet_header,4,false,1,true},<<65,84,43,87,83,76,81,13,192,0,192,0,192,0,192,0,192,0,192,0,192,0,192,0,192,0,192,0,192,0,192,0,192,0,67,89,65,84,43,87,83,76,81,13,192,0,192,0,192,0,192,0,192,0,192,0,192,0,192,0,192,0,192,0,192,0,67,89,65,84,43,87,83,76,81,13,192,0,192,0,67,89,65,84,43,87,83,76,81>>,#{max_size => 1048576,strict_mode => false,version => 4}],[{file,"/emqx-rel/_build/emqx-pkg/lib/emqx/src/emqx_frame.erl"},{line,164}]},{emqx_frame,parse_frame,4,[{file,"/emqx-rel/_build/emqx-pkg/lib/emqx/src/emqx_frame.erl"},{line,142}]},{emqx_connection,parse_incoming,3,[{file,"/emqx-rel/_build/emqx-pkg/lib/emqx/src/emqx_connection.erl"},{line,508}]},{emqx_connection,handle_msg,2,[{file,"/emqx-rel/_build/emqx-pkg/lib/emqx/src/emqx_connection.erl"},{line,501}]},{emqx_connection,process_msg,3,[{file,"/emqx-rel/_build/emqx-pkg/lib/emqx/src/emqx_connection.erl"},{line,284}]},{proc_lib,wake_up,3,[{file,"proc_lib.erl"},{line,259}]}]
Frame data:<<"AT+WSLQ\r">>

```
