### ISSUE TITLE
EMQX cluster load balancing

### ISSUE THREAD

**Issue by AhmarRG** [emqx/emqx#3609]
We are running emqx cluster on k8s.
When a new node in cluster is up, we want the connections to go to node with less connections (so all nodes share equal burden)
How can we do the connections balancing across nodes? so that the load remains same on all nodes.

**Comment by spring2maz** [comment]
Hi @AhmarRG 

We have documented an incomplete list of LBs that can be used together with EMQX.
https://docs.emqx.io/tutorial/latest/en/cluster/balancer.html

I believe what you are after is a so called 'least connections' balancing strategy.

Examples:

k8s: https://kubernetes.io/docs/concepts/services-networking/service/
> IPVS provides more options for balancing traffic to backend Pods; these are:
    rr: round-robin
    lc: least connection (smallest number of open connections)

HAproxy: https://www.digitalocean.com/community/tutorials/an-introduction-to-haproxy-and-load-balancing-concepts
> leastconn
Selects the server with the least number of connections–it is recommended for longer sessions. Servers in the same backend are also rotated in a round-robin fashion.
