### ISSUE TITLE
Parse failed for function_clause

### ISSUE THREAD

**Issue by hutuxiansheng** [emqx/emqx#3612]
emqx windows v4.1.0

use mqtt client connect emqx<TLS>，emqx close client。log msg：

2020-07-22 14:42:35.126 [error] 10.1.8.154:60406 [MQTT] 
Parse failed for function_clause
[{emqx_frame,parse_utf8_string,[<<0,43,105,111,116,45,115,100,107,45,114,116,108,56,55,50,48,99,102,59,50,49,48,49,48,52,48,54,59,49,116,111,86>>],[{file,"d:/a/emqx-rel/emqx-rel/_build/emqx/lib/emqx/src/emqx_frame.erl"},{line,419}]},{emqx_frame,parse_packet,3,[{file,"d:/a/emqx-rel/emqx-rel/_build/emqx/lib/emqx/src/emqx_frame.erl"},{line,193}]},{emqx_frame,parse_frame,4,[{file,"d:/a/emqx-rel/emqx-rel/_build/emqx/lib/emqx/src/emqx_frame.erl"},{line,142}]},{emqx_connection,parse_incoming,3,[{file,"d:/a/emqx-rel/emqx-rel/_build/emqx/lib/emqx/src/emqx_connection.erl"},{line,508}]},{emqx_connection,handle_msg,2,[{file,"d:/a/emqx-rel/emqx-rel/_build/emqx/lib/emqx/src/emqx_connection.erl"},{line,501}]},{emqx_connection,process_msg,3,[{file,"d:/a/emqx-rel/emqx-rel/_build/emqx/lib/emqx/src/emqx_connection.erl"},{line,284}]},{proc_lib,wake_up,3,[{file,"proc_lib.erl"},{line,259}]}]
Frame data:<<16,64,0,6,77,81,73,115,100,112,3,130,0,240,0,17,105,111,116,45,115,100,107,45,114,116,108,56,55,50,48,99,102,0,43,105,111,116,45,115,100,107,45,114,116,108,56,55,50,48,99,102,59,50,49,48,49,48,52,48,54,59,49,116,111,86,102,59,50,49,52,55,52,56,51,54,52,55>>
2020-07-22 14:42:38.486 [error] 10.1.8.154:60407 [MQTT] 
Parse failed for function_clause
[{emqx_frame,parse_utf8_string,[<<0,43,105,111,116,45,115,100,107,45,114,116,108,56,55,50,48,99,102,59,50,49,48,49,48,52,48,54,59,66,114,48,108>>],[{file,"d:/a/emqx-rel/emqx-rel/_build/emqx/lib/emqx/src/emqx_frame.erl"},{line,419}]},{emqx_frame,parse_packet,3,[{file,"d:/a/emqx-rel/emqx-rel/_build/emqx/lib/emqx/src/emqx_frame.erl"},{line,193}]},{emqx_frame,parse_frame,4,[{file,"d:/a/emqx-rel/emqx-rel/_build/emqx/lib/emqx/src/emqx_frame.erl"},{line,142}]},{emqx_connection,parse_incoming,3,[{file,"d:/a/emqx-rel/emqx-rel/_build/emqx/lib/emqx/src/emqx_connection.erl"},{line,508}]},{emqx_connection,handle_msg,2,[{file,"d:/a/emqx-rel/emqx-rel/_build/emqx/lib/emqx/src/emqx_connection.erl"},{line,501}]},{emqx_connection,process_msg,3,[{file,"d:/a/emqx-rel/emqx-rel/_build/emqx/lib/emqx/src/emqx_connection.erl"},{line,284}]},{proc_lib,wake_up,3,[{file,"proc_lib.erl"},{line,259}]}]
Frame data:<<16,64,0,6,77,81,73,115,100,112,3,130,0,240,0,17,105,111,116,45,115,100,107,45,114,116,108,56,55,50,48,99,102,0,43,105,111,116,45,115,100,107,45,114,116,108,56,55,50,48,99,102,59,50,49,48,49,48,52,48,54,59,66,114,48,108,110,59,50,49,52,55,52,56,51,54,52,55>>
2020-07-22 14:42:41.494 [error] 10.1.8.154:60408 [MQTT] 
Parse failed for function_clause

**Comment by zhanghongtong** [comment]
Hi, @hutuxiansheng 
The reason for this error is that the message contains content that cannot be parsed into a utf8 string, please check your message
