### ISSUE TITLE
EMQ X replaces MQTT properties when node connects using "topic-alias-maximum" property

### ISSUE THREAD

**Issue by tarek-asishm** [emqx/emqx#3614]
**Environment 1**:
- **Container environment**:
    - **EMQ X version:**  emqx 4.1.1
    - **Hardware configuration:** x86_64
    - **OS**: Alpine Linux v3.11
    - **Kernel:** 5.3.0-62-generic
- **Host environment**:
    - **Docker version**: 19.03.12
    - **Hardware configuration:** x86_64
    -**OS**: Ubuntu 18.04
    - **Kernel:**  5.3.0-62-generic

**Environment 2**:
- **Container environment**:
    - **EMQ X version:** emqx 4.1.1 
    - **Hardware configuration:** ARMv7 Processor rev 3 (v7l)
    - **OS**: Alpine Linux
    - **Kernel:**5.4.51-v7l+
- **Host environment**:
    - **Docker version**: 19.03.12
    - **Hardware configuration:** armv7l
    -**OS**: Raspbian GNU/Linux 10 (buster) 
    - **Kernel:** 5.4.51-v7l+

Every time a node connects using "topic-alias-maximum" property, emqx broker replaces all properties that this node should receive (sent by other nodes to a topic that the first node is subscribed to)  by topic-alias so, we loose the rest of the properties. In the image below, you can see the same MQTT packet published to a node connected with "topic-alias-maximum" (image on the right side) property and to another node connected without "topic-alias-maximum" property (image on the left side). Payload is exactly the same in both cases but not the properties. 

![mqtt_packet](https://user-images.githubusercontent.com/62397396/88173889-a4430a00-cc23-11ea-8986-06acfd9e8605.png)

As MQTT v5 specification, topic-alias-maximum can be used by both, nodes and broker, to indicate the maximum value of topic alias they accept, but in any case topic alias should replace the rest of properties.

**Comment by zhanghongtong** [comment]
Hi, @tarek-asishm 
This is a bug, we are working on it, thanks for your feedback

**Comment by HJianBo** [comment]
Hi @tarek-asishm We have fixed at v4.1.2
