### ISSUE TITLE
请问可以实现单点登录吗？

### ISSUE THREAD

**Issue by jandykwan** [emqx/emqx#3615]
**Please describe your problem in detail, if necessary, you can upload the log file through the attachment**:
我目录使用mysql数据库认证，我想问问系统可以配置单点登录吗？谢谢。

**Comment by HJianBo** [comment]
In the emqx cluster, the Client ID is unique. That is,  if the cluster accepped a client, it will kick out the old one used same Client ID

**Comment by spring2maz** [comment]
Hi @jandykwan 
We have a emqx-auth-http plugin which performs username/password authentication against the configured URL.
I am not sure if the current scheme of emqx-auth-http can be used out-of-the box with your SSO solution in use, but worth having a look.
There is also a emqx-auth-jwt plugin, again, I am not entirely sure if your SSO solution can be integrated with EMQX's token validation scheme.
