### ISSUE TITLE
Broker won't send retain when subscribing with '+' and '#'

### ISSUE THREAD

**Issue by 0xfadeef** [emqx/emqx#3621]
**Environment**:
- EMQ X version: 4.1.1
- OS: Ubuntu 20.04
- Protocol: MQTT 3.1.1, MQTT 5
- Others: run in Docker v. 19.03.8

**What happened and what you expected to happen**:
Retain messages are not delivered when client subscribes with topic filter, containing both '+' and '#' (i.e., `foo/bar/+/.../#`).

**How to reproduce it (as minimally and precisely as possible)**:
Publish a message with QoS 1 and retain flag set to 1 to a topic `foo/bar/baz`. Then subscribe to `foo/+/#`. Message won't be delivered. Retain messages published *after* subscription is made are delivered as expected.

**Comment by 0xfadeef** [comment]
Reproducible on EMQX version 4.1.2.

**Comment by HJianBo** [comment]
Thanks,  @0xfadeef We will fix it at v4.1.3

**Comment by HJianBo** [comment]
see: https://github.com/emqx/emqx-retainer/pull/146

**Comment by HJianBo** [comment]
Hi @0xfadeef The v4.1.3 has released yesterday. Plz try it
