### ISSUE TITLE
emqx_auth_redis won't support redis cluster

### ISSUE THREAD

**Issue by qiuzhefeng** [emqx/emqx#3622]
vesion3.2.0
Redis Cluster: 127.0.0.1:6379,127.0.0.2:6379,127.0.0.3:6379,127.0.0.4:6379,127.0.0.5:6379,127.0.0.6:6379
Authentication is not available

**Environment**:

- EMQ X version (e.g. `emqx_ctl status`): 
- Hardware configuration (e.g. `lscpu`):
- OS (e.g. `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Erlang/OTP version (in case you build emqx from source code): 
- Others:

**What happened and what you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Comment by HJianBo** [comment]
@qiuzhefeng Can you give me more detailed logs for emqx_auth_redis?
