### ISSUE TITLE
Data missing

### ISSUE THREAD

**Issue by sunmerben** [emqx/emqx#3623]
#### Environment

- OS: Ubuntu
- Erlang/OTP: 
- EMQ: 

#### Description
Send data like below, found one data missing in server site. Does anyone have similar issue?
*A description of the issue*
[I 20200723 03:26:49 adapter_mqtt:287] Client 170803000202S19920S2D62 :SEND>>> Done, packet number : 30356:2020-07-23T03:26:49.345475Z|0|3.000322|0.
[I 20200723 03:26:52 adapter_mqtt:287] Client 170803000202S19920S2D62 :SEND>>> Done, packet number : 30357:2020-07-23T03:26:52.346106Z|0|3.000631|0.
[I 20200723 03:26:56 adapter_mqtt:287] Client 170803000202S19920S2D62 :SEND>>> Done, packet number : 30358:2020-07-23T03:26:56.345922Z|0|3.999816|0.
[I 20200723 03:26:57 adapter_mqtt:287] Client 170803000202S19920S2D62 :SEND>>> Done, packet number : 30359:None
[I 20200723 03:26:59 adapter_mqtt:287] Client 170803000202S19920S2D62 :SEND>>> Done, packet number : 30360:2020-07-23T03:26:59.345653Z|0|2.999731|0.
[I 20200723 03:27:03 adapter_mqtt:287] Client 170803000202S19920S2D62 :SEND>>> Done, packet number : 30361:2020-07-23T03:27:03.345744Z|0|4.000091|0.
[I 20200723 03:27:07 adapter_mqtt:287] Client 170803000202S19920S2D62 :SEND>>> Done, packet number : 30362:2020-07-23T03:27:07.346428Z|0|4.000684|0.
[I 20200723 03:27:10 adapter_mqtt:287] Client 170803000202S19920S2D62 :SEND>>> Done, packet number : 30363:2020-07-23T03:27:10.346407Z|0|2.999979|0.
[I 20200723 03:27:13 adapter_mqtt:287] Client 170803000202S19920S2D62 :SEND>>> Done, packet number : 30364:2020-07-23T03:27:13.345983Z|0|2.999576|0.
[I 20200723 03:27:16 adapter_mqtt:287] Client 170803000202S19920S2D62 :SEND>>> Done, packet number : 30365:2020-07-23T03:27:16.346358Z|0|3.000375|0.
[I 20200723 03:27:20 adapter_mqtt:287] Client 170803000202S19920S2D62 :SEND>>> Done, packet number : 30366:2020-07-23T03:27:20.345256Z|0|3.998898|0.
[I 20200723 03:27:23 adapter_mqtt:287] Client 170803000202S19920S2D62 :SEND>>> Done, packet number : 30367:2020-07-23T03:27:23.346041Z|0|3.000785|0.
[I 20200723 03:27:26 adapter_mqtt:287] Client 170803000202S19920S2D62 :SEND>>> Done, packet number : 30368:2020-07-23T03:27:26.344610Z|0|2.998569|0.
[I 20200723 03:27:30 adapter_mqtt:287] Client 170803000202S19920S2D62 :SEND>>> Done, packet number : 30369:2020-07-23T03:27:30.344012Z|0|3.999402|0.

**Comment by terry-xiaoyu** [comment]
You could set the log level to debug and see if the message is received by emqx. 

```
emqx_ctl log set-level debug
```
