### ISSUE TITLE
The emqx bridge configure multiple subscription topics by env in EMQ X Edge container

### ISSUE THREAD

**Issue by moluzhui** [emqx/emqx#3624]
**Please describe your problem in detail, if necessary, you can upload the log file through the attachment**:
I switched from EMQx3.2.4 to EMQX4.1.1. 

In the EMQX-Edge: V3.2.4 container, I set up the bridged multiple subscription topics with a configuration similar to the following
```
EMQX_BRIDGE__MQTT__AWS__SUBSCRIPTION__1__TOPIC=cmd/321/#
EMQX_BRIDGE__MQTT__AWS__SUBSCRIPTION__1__QOS=2
EMQX_BRIDGE__MQTT__AWS__SUBSCRIPTION__2__TOPIC=cmd/123/#
EMQX_BRIDGE__MQTT__AWS__SUBSCRIPTION__2__QOS=2
```
But it seems that `bridge.mqtt.aws.subscription.2.topic` and `bridge.mqtt.aws.subscription.2.qos` configuration has been deleted in EMQ X Edge V4.1.1 bridge conf.

The subscription configuration in **EMQ X Edge v4.1.1** emqx_bridge_mqtt.conf  is as follows
```
## Need to subscribe to AWS topics
##
## Value: String
bridge.mqtt.aws.subscription.1.topic = cmd/321/#

## Need to subscribe to AWS topics QoS.
##
## Value: Number
bridge.mqtt.aws.subscription.1.qos = 2

## A mountpoint that receives messages from AWS IoTHUB
##
## Value: String
## bridge.mqtt.aws.receive_mountpoint = receive/aws/
```
The subscription configuration in EMQ X Edge v3.2.4 emqx_bridge_mqtt.conf  is as follows
```
## TLS versions used by the bridge.
##
## Value: String
bridge.mqtt.aws.tls_versions = tlsv1.2,tlsv1.1,tlsv1

## Subscriptions of the bridge topic.
##
## Value: String
bridge.mqtt.aws.subscription.1.topic = cmd/321/#

## Subscriptions of the bridge qos.
##
## Value: Number
bridge.mqtt.aws.subscription.1.qos = 2

## Subscriptions of the bridge topic.
##
## Value: String
bridge.mqtt.aws.subscription.2.topic = cmd/123/#

## Subscriptions of the bridge qos.
##
## Value: Number
bridge.mqtt.aws.subscription.2.qos = 2

## Start type of the bridge.
##
## Value: enum
## manual
## auto
bridge.mqtt.aws.start_type = auto
```

My project requires the configuration of **multiple bridging subscription topics and qos** . Then how can I implement it via envs.list?

I would appreciate it if you could tell me how to solve it?

**Comment by tigercl** [comment]
@moluzhui You can add unlimited subscriptions in the configuration file, as long as the indexs are different, example:

```
bridge.mqtt.aws.subscription.1.topic = cmd/321/#
bridge.mqtt.aws.subscription.1.qos = 2

bridge.mqtt.aws.subscription.2.topic = cmd/456/#
bridge.mqtt.aws.subscription.2.qos = 1

bridge.mqtt.aws.subscription.3.topic = cmd/789/#
bridge.mqtt.aws.subscription.3.qos = 0
```

**Comment by moluzhui** [comment]
> @moluzhui You can add unlimited subscriptions in the configuration file, as long as the indexs are different, example:
> 
> ```
> bridge.mqtt.aws.subscription.1.topic = cmd/321/#
> bridge.mqtt.aws.subscription.1.qos = 2
> 
> bridge.mqtt.aws.subscription.2.topic = cmd/456/#
> bridge.mqtt.aws.subscription.2.qos = 1
> 
> bridge.mqtt.aws.subscription.3.topic = cmd/789/#
> bridge.mqtt.aws.subscription.3.qos = 0
> ```

**Comment by moluzhui** [comment]
Thank you for your answer. I will be based on your answers to modify `emqx_bridge_mqtt.conf` and `mounted` to the `emqx - edge: v4.1.1 / opt/emqx/etc/plugins/emqx_bridge_mqtt.conf by docker run -v ...`
