### ISSUE TITLE
republish topic add payload message

### ISSUE THREAD

**Issue by erl-go-java** [emqx/emqx#3627]
hi,I want to use republish topic function to add payload message
for example:
  emqx receive topic "/hello" have payload "{"msg": "hello"}", I want to use republish topic function and send the topic to "/hello/to" and the payload "{"msg":hello, "time":time}".
  what should i do it? thanks

**Comment by HJianBo** [comment]
see: https://docs.emqx.io/broker/latest/en/rule/rule-engine.html#publish-message

**Comment by erl-go-java** [comment]
> see: https://docs.emqx.io/broker/latest/en/rule/rule-engine.html#publish-message

good, it work for me. thank you!
