### ISSUE TITLE
树莓派下Dashborad的统计信息不更新

### ISSUE THREAD

**Issue by troycui** [emqx/emqx#3631]
**Environment**:

- EMQ X version (e.g. `emqx_ctl status`): V4.1.1/V4.1.2
- Hardware configuration (e.g. `lscpu`): Raspberry PI 4B
- OS (e.g. `cat /etc/os-release`): Raspberry OS
- Kernel (e.g. `uname -a`):
- Erlang/OTP version (in case you build emqx from source code): 22.1.6
- Others: I tried Ubuntu on Raspberry PI without issue, only the Raspberry OS has issue.

**What happened and what you expected to happen**:
![4](https://user-images.githubusercontent.com/25068947/88622846-393b7c80-d0d6-11ea-92c7-c41ae65b8d20.png)
![3](https://user-images.githubusercontent.com/25068947/88622856-3ccf0380-d0d6-11ea-95bf-9c873831b20f.png)
![2](https://user-images.githubusercontent.com/25068947/88622859-3d679a00-d0d6-11ea-8290-e2edddf7f604.png)
![1](https://user-images.githubusercontent.com/25068947/88622860-3e003080-d0d6-11ea-815f-b8fc20dabfd5.png)

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Comment by HJianBo** [comment]
Hi @troycui  You should fill in your server address instead of `broker.emqx.io:1883`

You can server's host input-box by:

<img width="688" alt="image" src="https://user-images.githubusercontent.com/13825269/88663697-92270700-d10e-11ea-9349-7e22c4b97bec.png">

**Comment by troycui** [comment]
Thanks for update, I don’t know why you close this with such reason.

Did you check my screen shot carefully? I already connect to my local EMQX server and I can send and receive message as well.

The issue is the Dashboard is not showing the statistics data.

Please reopen this issue.

Troy Cui
ERP Specialist

[WAI]

Troy.Cui@waiglobal.com<mailto:Troy.Cui@waiglobal.com>

WAIglobal Shanghai

215 DeBao Road, WGQ, Free Trade Zone

Pudong, Shanghai, 200131, China

Skype:  Troy.Cui



Mobile:

+86 13818699609



Phone:

+86 021 50482700 Ext 865



Fax:

+86 021 50482722

www.waiglobal.com<http://www.waiglobal.com/>


[cid:image007.png@01D609D4.47650D90]<https://www.linkedin.com/company/waiglobal>[cid:image008.png@01D609D4.47650D90]<https://www.facebook.com/Waiglobal-Corp-114350320007234/>[cid:image009.png@01D608C8.1BFC76A0]<https://twitter.com/WAIglobal1>
