### ISSUE TITLE
How to block the links of censys

### ISSUE THREAD

**Issue by liping17** [emqx/emqx#3635]
How to block the links of censys

**Comment by zhanghongtong** [comment]
Please provide more information

**Comment by liping17** [comment]
看到有censys用户名的链接客户端，应该是这个https://censys.io/地址过来的扫描。
想启用用户名密码屏蔽，如下：
![image](https://user-images.githubusercontent.com/46994788/88870848-0239a800-d249-11ea-8469-b09427562546.png)
启用后，仍然可以用任意用户名密码进行连接

**Comment by liping17** [comment]
allow_anonymous = true 没有配置
