### ISSUE TITLE
EMQX DNS Autocluster in AWS No Longer Working from v3 to v4

### ISSUE THREAD

**Issue by louisburton** [emqx/emqx#3636]
In `v3.2.3`, an ECS (Fargate) deployed EMQX cluster worked fine, with nodes correctly seeing each other (port 6369 open). This was configured to autocluster via DNS, with 3 appropriate A records in DNS (AWS Route53), TTL is 300 seconds. This all works fine as expected in `v3.2.3`.
Changing solely the version to `v4.1.2`, the nodes all run successfully and process messages successfully, however they no longer see each other in the cluster. 

The Node names I can confirm in both versions are of the same format (`mqttcluster@<ipv4>`), however in `v3.2.3` the `node.name` in emqx.conf is populated equivalently (whereas it isn't in `v4.1.2` due to [this change](https://github.com/emqx/emqx-rel/commit/09b4438c083d101134a36e5fced0b89f34acddf0#r40997875)). I've confirmed this value doesn't make a difference to the problem however, even if populated in `v4.1.2`, which I suspect is specific to manually clustered setups.

`v4.1.2` dashboard of a single node, only seeing itself.
![image](https://user-images.githubusercontent.com/5257921/88809202-c00e5900-d1ab-11ea-895e-6f35036ae836.png)

Cluster settings:
```
...
EMQX_CLUSTER__DISCOVERY | dns
EMQX_CLUSTER__DNS__APP | mqttcluster
EMQX_CLUSTER__DNS__NAME | mqtt.platform.eu-west-1.mycloud
EMQX_CLUSTER__NAME | mqttcluster
EMQX_LISTENER__API__MGMT | 0.0.0.0:8080
EMQX_LISTENER__TCP__EXTERNAL | 0.0.0.0:1883
EMQX_LISTENER__WS__EXTERNAL | 8083
EMQX_LOADED_MODULES | emqx_mod_acl_internal,emqx_mod_presence,emqx_mod_topic_metrics
EMQX_LOADED_PLUGINS | emqx_recon,emqx_retainer,emqx_management,emqx_dashboard,emqx_auth_http
EMQX_NAME | mqttcluster
```

Exposed ports:
Host Port | Container Port | Protocol
-- | -- | --
18083 | 18083 | tcp
1883 | 1883 | tcp
4369 | 4369 | tcp
6000 | 6000 | tcp
6001 | 6001 | tcp
6002 | 6002 | tcp
6003 | 6003 | tcp
6004 | 6004 | tcp
6005 | 6005 | tcp
6006 | 6006 | tcp
6007 | 6007 | tcp
6008 | 6008 | tcp
6009 | 6009 | tcp
6010 | 6010 | tcp
6011 | 6011 | tcp
6012 | 6012 | tcp
6013 | 6013 | tcp
6014 | 6014 | tcp
6015 | 6015 | tcp
6016 | 6016 | tcp
6017 | 6017 | tcp
6018 | 6018 | tcp
6019 | 6019 | tcp
6020 | 6020 | tcp
6021 | 6021 | tcp
6369 | 6369 | tcp
5369 | 5369 | tcp
8083 | 8083 | tcp
8084 | 8084 | tcp
8883 | 8883 | tcp
11883 | 11883 | tcp

Have I missed something? Or is there a configuration change I need to be aware of? 
Is there a way I can further debug this? (bearing in mind I can't shell into Fargate)
Thanks! 🙏

**Comment by zhanghongtong** [comment]
CC @turtleDeng @terry-xiaoyu 
Do you have any ideas?

**Comment by terry-xiaoyu** [comment]
@louisburton Could you inspect what tcp ports your emqx is listening on? Is it listening on tcp port 4370? If so, also export the port out of the docker container.

**Comment by louisburton** [comment]
No, I had 4369 open.
I can only see a reference to 4370 in the config under a [multicast port value](https://github.com/emqx/emqx/blob/v4.1.2/etc/emqx.conf#L74), and we are clustering via DNS not multicast.

I also can't see any reference to listening on `4370` in my logs, and I'm not sure why this would be different to `v3.2.3`?
![image](https://user-images.githubusercontent.com/5257921/89032129-e3601200-d32b-11ea-8016-e768027646d4.png)

However, I can confirm, just making the sole change of opening `4370` when upgrading has resolved my issue so the cluster sees all the nodes fine again. Thanks for the suggestion @terry-xiaoyu . I am confused, but the issue is resolved :)

**Comment by spring2maz** [comment]
v4.1.2 by default does *not* require EPMD (which listens on 4369), unless environment `WITH_EPMD` is set to a non-empty value.
When `WITH_EPMD` is not set, It listens on port `4370+offset` for clustering. 
`offset` is the node name suffix.
for instance, if the node is named `emqx-1` then the port would be `4371`,
if the node name ends with 0 or has no number suffix, it uses port `4370`.
Also, when `WITH_EPMD` is not set, the `dist_listen_min` and `dist_listen_max` configs has no effect.

@terry-xiaoyu I have noticed 2 issue reports about this, do we have it well documented anywhere ?

**Comment by louisburton** [comment]
Very helpful explanation. Thanks @spring2maz.
I didn't spot this documented change, but perhaps I missed something (although I did search for `4370` port references).

Have a good weekend guys 👍
