### ISSUE TITLE
Failed to connect to EMQ X Broker with paho.mqtt.cpp library

### ISSUE THREAD

**Issue by zacario-li** [emqx/emqx#3639]
**Please describe your problem in detail, if necessary, you can upload the log file through the attachment**:
首先，我再阿里云上，自己安装了emqx，我用paho python写脚本，一切正常，没有什么问题，正常收发。
当我用paho.mqtt.cpp这个库连接，奇怪的事情发生了，我一connect，马上就会获得-3这个错误，我抓了log看，服务端把我的connection给断开了，没有理由的断开了。
然而，我做了一个实验，我在局域网里面安装一个emqx，一起又都正常，实在是搞不明白为什么，不知道各位有没有遇到过这种情况。

**Comment by tigercl** [comment]
@zacario-li Could you provide emqx log when the device requests connection?

**Comment by zacario-li** [comment]
> @zacario-li Could you provide emqx log when the device requests connection?

where can I get the log?
