### ISSUE TITLE
emqx is safe? unkown client id in client list, why?????

### ISSUE THREAD

**Issue by liajt** [emqx/emqx#3646]
![image](https://user-images.githubusercontent.com/18021523/89244466-20344d80-d639-11ea-8c77-e092c5166990.png)
**Please describe your problem in detail, if necessary, you can upload the log file through the attachment**:

**Comment by terry-xiaoyu** [comment]
Which client has no clientid? Is your screenshot the clients do has their clientids, but no usernames.
