### ISSUE TITLE
`peer_cert_as_username` and `use_username_as_clientid` having no effect

### ISSUE THREAD

**Issue by dwi-iwb** [emqx/emqx#3647]
The settings `peer_cert_as_username` and `use_username_as_clientid` seem to have no effect. My situation is similiar to issue #2972 , although I am currently running version 4.0.7.

Log (debug) of `peer_cert_as_username = true` but `use_username_as_clientid = false`:
```
(app@emqx-0.emqx-headless.emqx.svc.cluster.local)1> 2020-08-04 08:49:01.460 [debug 127.0.0.1:34052 [MQTT RECV CONNECT(Q0, R0, D0, ClientId=dwi, ProtoName=MQTT, ProtoVsn=4, CleanStart=true, KeepAlive=60, Username=undefined, Password=undefined)
```

I am currently trying to create a configuration where a client device authenticates itself at the broker using a client certificate (CN = SerialNr of the device).
More important though is the ACL configuration. I am trying to set it up in a way, where a device/certificate is only able to access its "own" topic (levels) -> deviceType/SerialNr/#.

I am using both zones (zone.internal + zone.external), the above described setup is running on zone.external.
**Zone.internal** is running the following setup: Istio Ingress Gateway as LB + TLS Termination -> Port 1883, using MongoDB for authentication and ACL. (works)

**Zone.external**: Istio -> TLS Passthrough (works) -> Authentication using ClientCert (works) -> Use CN as Username (not working) -> allow_anonymous -> Standard ACL (file) rule: `{allow, all, pubsub, ["deviceType/1/%u/#"]}`.

Plugins:
`emqx_management,emqx_recon,emqx_retainer,emqx_dashboard,emqx_auth_mongo,emqx_auth_username`

Config:
```
allow_anonymous = false
acl_nomatch = deny
acl_deny_action = disconnect
zone.internal.allow_anonymous = false
zone.external.allow_anonymous = true (added manualy)
zone.external.enable_acl = on
zone.external.acl_deny_action = ignore
listener.tcp.external.peer_cert_as_username = cn
listener.ssl.external.zone = external
listener.ssl.external.peer_cert_as_username = cn
listener.ssl.external.tls_versions = tlsv1.2
listener.ssl.external.verify = verify_peer
listener.ssl.external.fail_if_no_peer_cert = true
```
I also tried setting `zone.external.use_username_as_clientid = true` because I guessed it is at a similiar position in the processing chain, but this is also not working.

I can verify, that every setting works as expected except for the two.

I used my own client & server certificates, aswell crating new ones following your [blog post](https://www.emqx.io/blog/enable-two-way-ssl-for-emqx) on the topic.

**Comment by tigercl** [comment]
@dwi-iwb This is indeed a bug, thank you for your feedback, we will fix it in the next version (4.1.*). We will notify you in time , when we fixed it.

**Comment by HJianBo** [comment]
@tigercl I think this bug has been fixed at 4.0.4. I have tried to reproduce the problem, I succeeded in getting the Cert's CN

@dwi-iwb This log is no problem. It just prints your CONNECT content instead of the eventually assigned username
```
2020-08-04 08:49:01.460 [debug 127.0.0.1:34052 [MQTT RECV CONNECT(Q0, R0, D0, ClientId=dwi, ProtoName=MQTT, ProtoVsn=4, CleanStart=true, KeepAlive=60, Username=undefined, Password=undefined)
```

You can get the *eventually assigned username* with `./bin/emqx_ctl clients list`.


> Istio -> TLS Passthrough (works) -> Authentication using ClientCert (works) -> Use CN as Username (not working)
What is the port of the Broker that the Istio proxy is pointing to? Is 8883?

**Comment by dwi-iwb** [comment]
@HJianBo thank you for your answer.
JLooking at the output of `emqx_ctl clients list` shows that `listener.tcp.external.peer_cert_as_username = cn` is working correctly. Nonetheless `zone.external.use_username_as_clientid = true` ( also checking through `emqx_ctl clients list`) seems not to work.
Yes Istio is routing to 8883.

**Comment by HJianBo** [comment]
But I can't reproduce it...

In my case, the client is `mosquitto_sub` with the default client's cert in the `etc/certs/client-*`:
``` bash
$ mosquitto_sub -i clientidA -t t/Client/a -p 8883 --cert etc/certs/client-cert.pem --key etc/certs/client-key.pem --cafile etc/certs/cacert.pem --insecure -d
Client clientidA sending CONNECT
Client clientidA received CONNACK (0)
Client clientidA sending SUBSCRIBE (Mid: 1, Topic: t/Client/a, QoS: 0, Options: 0x00)
Client clientidA received SUBACK
Subscribed (mid: 1): 0
```

The `emqx_ctl clients list` is:
```
Client(Client, username=Client, peername=127.0.0.1:52026, clean_start=true, keepalive=60, session_expiry_interval=0, subscriptions=1, inflight=0, awaiting_rel=0, delivered_msgs=0, enqueued_msgs=0, dropped_msgs=0, connected=true, created_at=1596619666, connected_at=1596619666)
```

As you can see, the `clientid` and `username` is `Client` (that euqals to the client's cert's CN) Are you sure you didn't miss anything?

Or sharing me your emqx.conf to help me reproducing it

**Comment by dwi-iwb** [comment]
@HJianBo you were right. I had a typo in my helm chart's `values.yaml`.
Everything is working perfectly fine now. (verrfied through `emqx_ctl clients list`)
ACL is also working like a charm with `%u` (username) or `%c` (clientid).
Thanks a lot for your help!
