### ISSUE TITLE
How to set ReceiveMaximum properties in CONNACK？

### ISSUE THREAD

**Issue by DrmagicE** [emqx/emqx#3648]
I have set both `zone.internal.max_inflight `and `zone.internal.max_inflight` to 1. But I still got unset receive maximum property in connack which means default to  65,535.

**Comment by tigercl** [comment]
@DrmagicE Thank you for your feedback. We currently do not support the Receive Maximum in the CONNACK message. Sorry for the inconvenience caused to your use. We will support it as soon as possible.
