### ISSUE TITLE
Failed to set session expiration time

### ISSUE THREAD

**Issue by LvCodeing** [emqx/emqx#3649]
**Environment**:

- EMQ X version : v4.0.10
- OS (e.g. `cat /etc/os-release`):ubuntu16.04
- Kernel :GNU/Linux 4.15.0-112-generic x86_64
- Erlang/OTP version : otp22.3 

How does emqx set session clean = YES?

**Comment by zhanghongtong** [comment]
Hi, @LvCodeing 
I don't understand what you mean, `CleanSession = 1` is set by the client in the CONNECT packet, please check the MQTT agreement
