### ISSUE TITLE
Check ACL Hook priority

### ISSUE THREAD

**Issue by saeid-ir** [emqx/emqx#3655]
**Environment**:

- EMQ X version (e.g. `emqx_ctl status`): 
v4.1.3
- OS (e.g. `cat /etc/os-release`):
Docker

**What happened and what you expected to happen**:
Hi
As what the docs say in Hooks section `client.check_acl` should be executed before publish/subscribe hooks.
But when I debug it I realized that it happens after `client.subscribe` and before `message.publish`.
So one of them is definitely a bug 
**How to reproduce it (as minimally and precisely as possible)**:
Check with simple debug plugin (e.g : `emqx-template-plugin`

**Comment by HJianBo** [comment]
I think you misunderstood the document

Plz see: https://docs.emqx.io/broker/latest/en/advanced/hooks.html#hookpoint

```
client.check_acl: Before `publish/subscribe` operation is executed
client.subscribe: After receiving the subscription message, and before executing client.check_acl

message.publish: Before the server publishes (routes) the message
```

**Comment by saeidakbari** [comment]
If it is correct in this manner the doc should not say `Before publish/subscribe` because the only hook of publishing messages that can be matched to what the doc says is `message.publish`.

I think the doc needs some clarification.

**Comment by saeidakbari** [comment]
If I understand right this is the way that hooks are executed :
`client.subscribe` -> `client.check_acl` -> rest of the hooks
`client.check_acl` -> `message.publish` -> rest of the hooks

The logical reason would be that `message.publish` happens before `client.check_acl` so in this way custom plugins can be made for modifying topics and ... before authorization. the same scenario that we have on our systems that username have to be appended before every topic.

**Comment by HJianBo** [comment]
I understand, but there is no design for this hook to be executed before `check_acl` (e.g. client.publish).
