### ISSUE TITLE
Kubernetes cluster issue

### ISSUE THREAD

**Issue by Zhiw** [emqx/emqx#3664]
**Environment**:

- EMQ X version (e.g. `emqx_ctl status`): v4.1.3
- OS (e.g. `cat /etc/os-release`): Docker

**What happened and what you expected to happen**:
I built a three-node emqx cluster with Kubernetes, and I ran a test:
- 50 connections
- 50 TPS: 25 sub and 25 pub
- payload size: 1024 bytes

and after about 24 hours, the cluster crashed.
Here are the log files:
[log-0.zip](https://github.com/emqx/emqx/files/5067244/log-0.zip)
[log-1.zip](https://github.com/emqx/emqx/files/5067245/log-1.zip)
[log-2.zip](https://github.com/emqx/emqx/files/5067249/log-2.zip)

Thanks a lot.

**Comment by k32** [comment]
Hello,

Sorry for a slow answer. The cluster has experienced a network partition that lead to split brain of the database that could not be healed automatically. I will take a look at whether autoheal procedure could be improved.

**Comment by k32** [comment]
P.S. Upon closer inspection of the logs, it appears that all nodes lost connectivity between each other at some point.
As documented here, EMQ X tries to find majority partition before doing autoheal: https://docs.emqx.io/en/broker/v4.3/advanced/cluster.html#network-partition-autoheal
However, in your case the cluster has been split in 3 equal parts, so autoheal refused to run. I submitted https://github.com/emqx/ekka/issues/105 with more details.
