### ISSUE TITLE
How can i get an EMQX with gmssl.

### ISSUE THREAD

**Issue by marshal123** [emqx/emqx#3665]
Under the trend of localization, the project team expects to compile an EMQX based on the national secret algorithm（SM2/SM3/SM4）. Is there any guidance?
GmSSL ( http://gmssl.org ）It is a branch of OpenSSL that supports national secret algorithm and standard, and adds support for SM2 / SM3 / SM4 algorithm.
How do I combine GMSSL and EMQX?

**Comment by spring2maz** [comment]
EMQX is built in Erlang/OTP (on top of the beam virtual machine), such support will have to be provided from Erlang's crypto library.
If GmSSL is compatible to OpenSSL, one should be able to compile Erlang/OTP with it (as how it can be compiled with LibreSSL).
EMQ currently has no plan supporting it, we look forward to Erlang/OTP contributions from gmssl community.

**Comment by Kracker1911** [comment]
https://www.emqx.io/cn/blog/emqx-sm-iot-security-solution
@spring2maz This article released at 11 Aug. Does it means that Gm-TLS of EMQX exists now?

**Comment by zmstone** [comment]
Hi. @Kracker1911 the solution from this article requires a security gateway in front of EMQX brokers.
That is, EMQX itself does not support GM-TLS / GM-DTLS,
it's the gateway which supports them and terminate them before forwarding to EMQX in a secure, private network.
EMQ is in partnership with security gateway providers, you are welcome to contact us for more supports.
