### ISSUE TITLE
Authentication issuse

### ISSUE THREAD

**Issue by pk178** [emqx/emqx#3666]
#### Environment

- OS: Windows Server 2016
- Erlang/OTP: 10.7
- EMQ: 4.1.2

#### Description

*A description of the issue*

I configured authentication using user name and password as description here, but didn't work: https://docs.emqx.io/tutorial/v3/en/security/auth.html#authentication

What I did:
1. Disable anoymous login: "allow_anonymous = false"
2. Add user name + password to file "emqx_auth_username.conf"
3. Enable authentication plug-in: emqx_ctl plugins load emqx_auth_username
4. Restart emqx services, then try to connect to emqx server without username and password, connection successed

**Comment by terry-xiaoyu** [comment]
It should be working if you have set the `allow_anonymous = true` in emqx.conf.

I suggest you set `log.level = debug` in emqx.conf and stop emqx and then start it from console, without any auth plugins:

```
emqx_ctl plugins unload emqx_auth_username
emqx stop
emqx console
```

And then see if your client can connect to it. Logs will show up on the console.

The latest doc:
https://docs.emqx.io/broker/latest/en/advanced/auth.html#anonymous-authentication
