### ISSUE TITLE
acl rules does not work properly

### ISSUE THREAD

**Issue by southfly** [emqx/emqx#3669]
> acl.conf
```
{allow, {user, "mqtt"}, pubsub, ["/test/#"]}.

{allow, {user, "south"}, pubsub , ["$SYS/#", "#"]}}.

{allow, {user, "dashboard"}, subscribe, ["$SYS/#", "#"]}.

{allow, {ipaddr, "127.0.0.1"}, pubsub, ["$SYS/#", "#"]}.

{allow, all}.
```
> emqx.conf
```
acl_nomatch = deny
acl_file = /etc/emqx/acl.conf
acl_deny_action = ignore
```

user "mqtt" subscribe "/test/hello" failed, and also user "south" subscribe "/test/hello" failed.

does '#' means wildcards?

i use mqttx client v1.3.3, emqx v4.1.3, centos 7.8.2003.

https://docs.emqx.io/broker/latest/en/advanced/acl-file.html

**Comment by terry-xiaoyu** [comment]
I tried your acl.conf but got from the emqx console:

```
2020-08-16 10:27:58.335 [alert] [ACL_INTERNAL] Failed to read etc/acl.conf: {20,erl_parse,
                                             ["syntax error before: ","'}'"]}
```

So I corrected you acl.conf by removing the extra '}' at the end of the second line, then it works well:

```
{allow, {user, "south"}, pubsub, ["$SYS/#", "#"]}.
```

**Comment by southfly** [comment]
谢谢，
