### ISSUE TITLE
Session across Cluster Nodes for QoS 1

### ISSUE THREAD

**Issue by Ju-Ru** [emqx/emqx#3674]
Hello, 

I would like to understand in a bit more detail the behavior to expect in case of cluster node failures and sessions across nodes for QoS level 1/2. 

For the cluster setup, you mention that sessions [are synchronized across nodes](https://docs.emqx.io/broker/v3/en/cluster.html#session-across-nodes) in the wiki. Can you explain what the expected behavior in case of a sudden node failure (e.g. hardware outage / forceful shutdown of node) would be in case of QoS 1 client sessions (assuming clients automatically reconnect to the cluster)? 

Some questions that would be interesting in this context:
- Can you share some more information on how the session synchronization is implemented? 
- What happens in case of a node failure with regard to QoS 1 messages that were routed already but not yet delivered to clients that were connected to a failed node? Would other nodes keep a copy of the messages in case such a client reconnects to one of the other nodes?
- Depending on your answer to the previous questions, are there other cases that would be problematic for high-availability setups in that QoS 1 messages might not be delivered?

**Comment by tigercl** [comment]
@Ju-Ru This is a design in the 3.0 period. Assuming that the connection and the session are not on the same node, if the node where the session is located crashes, the state information such as the QoS 1 message that has not been confirmed in the session will be lost after the node restarts, and the connection will also be is closed. If the connected node crashes and the client reconnects after the node restarts, it will continue to use the session state on the other node. In the 4.0 period, we carried out a redesign, and now a client connection and session will only exist on the same node.

**Comment by Ju-Ru** [comment]
@tigercl Thanks for the details. I now also located the[ v4 cluster documentation](https://docs.emqx.io/broker/v4/en/advanced/cluster.html). 

- Are there any plans to reintroduce some kind of high availability support for QoS 1 messages in case of broker instance failures? 
- Could you share any details on why the support was dropped in v4?
- Are there any other recommendations how to achieve a QoS 1 semantic with EMQX clusters for failure scenarios? 
- In the same line, is there a possibility to migrate sessions in a more controlled scenario, such as a broker instance upgrade?

**Comment by tigercl** [comment]
@Ju-Ru In fact, we have not yet supported any mechanism to preserve session state when a node crashes, but we are considering introducing it in 5.0.

**Comment by anupbvr** [comment]
@tigercl does this design change limits the availability of offline messages for a persisted subscriber, on following cases, 

- If the load balancer switches the nodes for a client re-connect (in a cluster environment), can client continue to get his offline messages queued on the previous node?

-When a node gracefully exit a cluster. Does the presistant session and messages will be moves to other active node, so that client recieve it, when reconnected back to the new active node ? 

Are you planning to tag confirm this to 5.0 mile stone ?
