### ISSUE TITLE
Emqx broker not able to connect with wss.

### ISSUE THREAD

**Issue by Ajithhd** [emqx/emqx#3678]
Emqx

- OS: 
- Erlang/OTP: 
- EMQ: 

My emqx broker not connect with wss..i installed emqx on google cloud and got a certificate from godaddy..i added cert configuration certificate file in emqx.conf..what is the solutions s?

*A description of the issue*

**Comment by tigercl** [comment]
@Ajithhd You can refer to this blog: [Enable SSL/TLS for EMQ X MQTT broker](https://www.emqx.io/blog/emqx-server-ssl-tls-secure-connection-configuration-guide).
