### ISSUE TITLE
ERR_CONNECTION_RESET when open Monitor on Dashboard

### ISSUE THREAD

**Issue by eshxcmhk** [emqx/emqx#3685]
**Environment**:

- EMQ X version (e.g. `emqx_ctl status`): 4.1.3
- Hardware configuration (e.g. `lscpu`):80 cpu
- OS (e.g. `cat /etc/os-release`):CentOS 7.8 
- Kernel (e.g. `uname -a`):x86_64
- Erlang/OTP version (in case you build emqx from source code): default in rpm package

**What happened and what you expected to happen**:
GET http://192.168.1.3:18083/api/v4/brokers/emqx@127.0.0.1?_=1598238249369 net::ERR_CONNECTION_RESET
**How to reproduce it (as minimally and precisely as possible)**:
start the emqx, open dashboard in browser, it happened.
**Anything else we need to know?**:
there is no other web services

**Comment by tigercl** [comment]
@eshxcmhk Can you confirm that emqx is running? And everything is normal in the log?

**Comment by eshxcmhk** [comment]
> @eshxcmhk Can you confirm that emqx is running? And everything is normal in the log?

Yes, except for this error, everything works fine, and no exceptions are found in the debug log when you turn it on.

**Comment by tigercl** [comment]
@eshxcmhk What is the status of the listeners on port 18083 when you run `./bin/emqx_ctl listeners` command to list all the listeners?

**Comment by eshxcmhk** [comment]
> @eshxcmhk What is the status of the listeners on port 18083 when you run `./bin/emqx_ctl listeners` command to list all the listeners?

```
listener on mqtt:tcp:0.0.0.0:1883
  acceptors       : 8
  max_conns       : 1024000
  current_conn    : 1
  shutdown_count  : [{tcp_closed,2},{idle_timeout,1},{not_authorized,8},{function_clause,2}]
listener on http:dashboard:18083
  acceptors       : 4
  max_conns       : 512
  current_conn    : 0
  shutdown_count  : []
listener on http:management:8081
  acceptors       : 2
  max_conns       : 512
  current_conn    : 0
  shutdown_count  : []
listener on mqtt:ws:8083:8083
  acceptors       : 4
  max_conns       : 102400
  current_conn    : 0
  shutdown_count  : []
```

**Comment by tigercl** [comment]
@eshxcmhk It seems that there is no problem. Can you initiate a request through `curl` command?

**Comment by eshxcmhk** [comment]
> @eshxcmhk It seems that there is no problem. Can you initiate a request through `curl` command?

send request with postman, the result:
```
{
    "data": {
        "version": "4.1.3",
        "uptime": "2 days, 3 hours, 21 minutes, 51 seconds",
        "sysdescr": "EMQ X Broker",
        "otp_release": "R22/10.7",
        "node_status": "Running",
        "node": "emqx@127.0.0.1",
        "datetime": "2020-08-26 14:51:20"
    },
    "code": 0
}
```
but Still wrong in dashboard,the browser console print:
```
Error: Network Error
    at FtD3.e.exports (vendor.5cedbbc3e1297a4b039a.js:19)
    at XMLHttpRequest.d.onerror (vendor.5cedbbc3e1297a4b039a.js:19)
w @ app.88ef3d8a120a93fc3b3d.js:1
Promise.then(异步)
XmWM.l.request @ vendor.5cedbbc3e1297a4b039a.js:30
l.<computed> @ vendor.5cedbbc3e1297a4b039a.js:30
(匿名) @ vendor.5cedbbc3e1297a4b039a.js:19
e.$httpGet @ app.88ef3d8a120a93fc3b3d.js:1
loadData @ 16.cac14bf01c2463f006f8.js:1
```
```
GET http://192.168.1.3:18083/api/v4/nodes?_=1598424752985 net::ERR_CONNECTION_RESET 
      vendor.5cedbbc3e1297a4b039a.js:19
(匿名) | @ | vendor.5cedbbc….js:19
-- | -- | --
  | e.exports | @ | vendor.5cedbbc….js:19
  | e.exports | @ | vendor.5cedbbc….js:46
  | Promise.then(异步) |   |  
  | XmWM.l.request | @ | vendor.5cedbbc….js:30
  | l.<computed> | @ | vendor.5cedbbc….js:30
  | (匿名) | @ | vendor.5cedbbc….js:19
  | e.$httpGet | @ | app.88ef3d8….js:1
  | loadData | @ | 16.cac14bf….js:1
```
```
Uncaught (in promise) Network Error
Promise.then(异步)
loadData @ 16.cac14bf01c2463f006f8.js:1
```
```
app.88ef3d8a120a93fc3b3d.js:1 Error: Network Error
    at FtD3.e.exports (vendor.5cedbbc3e1297a4b039a.js:19)
    at XMLHttpRequest.d.onerror (vendor.5cedbbc3e1297a4b039a.js:19)
```

**Comment by tigercl** [comment]
@eshxcmhk Have you tried to access with other browsers?

**Comment by eshxcmhk** [comment]
> @eshxcmhk Have you tried to access with other browsers?

Yes, i tried with Edge, Chrome, Safari. result with Safari:
```
[Error] Error: Network Error  f w  http://192.168.1.3:18083/static/js/app.88ef3d8a120a93fc3b3d.js
（匿名函数） — vendor.5cedbbc3e1297a4b039a.js:19:145436
（匿名函数） — vendor.5cedbbc3e1297a4b039a.js:19:101431

	w (app.88ef3d8a120a93fc3b3d.js:1:44501)
	promiseReactionJob
[Error] Failed to load resource: 网络连接已中断。 (metrics, line 0)   http://192.168.1.3:18083/api/v4/nodes/emqx@127.0.0.1/metrics?_=1598495969590
[Error] Unhandled Promise Rejection: Network Error
	（匿名函数）
	promiseReactionJob
```
