### ISSUE TITLE
Web user login verification plug-in is slow and takes 10 seconds in emqx 4.1

### ISSUE THREAD

**Issue by hubusercc** [emqx/emqx#3689]
你好：问题描述：服务器server2016,emqx4.1。匿名登陆验证时很快；启用web用户插件时在错误的用户登入验证时返回很快，正确的用户登入时返回很忙，大概10秒左右。用postman测试web接口很快。请问下这种是否正常？如何优化？

**Comment by tigercl** [comment]
**Environment:**

- EMQ X Version: 4.1
- OS: Windows server 2016

**What happened and what you expected to happen**:
Anonymous login verification is very fast; when the web user plugin is enabled, it returns quickly when the wrong user login verification, and the correct user login is very busy, about 10 seconds. Testing the web interface with postman is very fast. Is this normal? How to optimize?

**Comment by tigercl** [comment]
@hubusercc Can you confirm whether the time is consumed on the emqx broker or on the web server?
