### ISSUE TITLE
API to Manage ACL

### ISSUE THREAD

**Issue by outminder** [emqx/emqx#3691]
#### Environment

- OS: 
- Erlang/OTP: 
- EMQ: 

#### Description

*A description of the issue*

Is there API which can be used to manage ACL on topics?

**Comment by tigercl** [comment]
@outminder We do not currently provide these APIs, maybe you can describe your needs in detail, we will discuss whether it is necessary to implement it.

**Comment by k32** [comment]
Hello,

I believe this feature has been added, at least for the `emqx_auth_mnesia` plugin: https://docs.emqx.io/en/broker/v4.3/advanced/acl-mnesia.html#use-the-http-api-to-manage-acl-rules

Please feel free to reopen the issue if you have further questions, or if you're interested in an API for a different ACL plugin.
