### ISSUE TITLE
Cluster messages are not passing between nodes.

### ISSUE THREAD

**Issue by migalenkom** [emqx/emqx#3695]
I created a cluster according to this documentation 
https://docs.emqx.io/tutorial/v3/en/cluster/setup_start.html

1) node.name = emqx@192.168.130.44
2) node.name = emqx@192.168.153.64
3) node.cookie = emqxsecretcookie
4) cluster.discovery = manual
5) On second instance I run  `sudo emqx_ctl cluster join emqx@192.168.130.44`
and cluster status shows me that node was added successfully.
```
sudo emqx_ctl cluster status
Cluster status: [{running_nodes,['emqx@192.168.130.44',
                                 'emqx@192.168.153.64']}]
```
When I do command below on `emqx@192.168.130.44` it successfully adds a message to the queue but doesn't work on the second instance `emqx@192.168.153.64` it returns exit status 0 but nothing is added to the queue.

`mosquitto_pub -u test -P test -q 2 --quiet   -t "tl/all/agents/vpn_connect/json"   -m '{"vpn_details":{"common_name":"name1", "config":"/etc/openvpn/test.is.3.conf", "daemon":"0", "daemon_log_redirect":"0", "dev":"tun4", "ifconfig_broadcast":"10.2.191.255", "ifconfig_local":"10.2.160.1", "ifconfig_netmask":"255.255.224.0", "ifconfig_pool_netmask":"255.255.224.0", "ifconfig_pool_remote_ip":"10.2.160.3"}, "path":"/agents/vpn_connect", "method":"post"}'`

Could you please point me what should I do to allow passing messages between cluster nodes?

**Comment by haowanxing** [comment]
same as this one #3694

**Comment by terry-xiaoyu** [comment]
@migalenkom 

What's the emqx version?

Is your MQTT client connected to `emqx@192.168.130.44` and subscribed to `tl/all/agents/vpn_connect/json` ?

**Comment by migalenkom** [comment]
updated emqx to the latest version and that fixed the issue, thanks for the help.

**Comment by rgaufman** [comment]
We had this issue today after Linode decided to migrate our host for maintenance reasons which I guess got the databases out of sync. In our case, moving the old mnesia database out of the way fixed the problem.
