### ISSUE TITLE
emqx_ctl returning "No commands available." after EMQX update

### ISSUE THREAD

**Issue by rgaufman** [emqx/emqx#3699]
**Environment**:

- EMQ X version 4.1.4
- Hardware configuration (e.g. `lscpu`): Linode VPS
- OS (e.g. `cat /etc/os-release`): Ubuntu 18.04.5 LTS
- Kernel (e.g. `uname -a`): Linux ctrl-01.timeline.is 5.6.14-x86_64-linode135 #1 SMP PREEMPT Fri May 22 14:57:20 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
- Erlang/OTP version (in case you build emqx from source code): 
- Others:

**What happened and what you expected to happen**:
After updating from EMQX 3.2.7 to EMQX 4.1.4 we suddenly get:

```
root@ctrl-01:~# emqx_ctl status
No commands available.
```

The server is up and clients are trying to connect, but can't run emqx_ctl

**Comment by terry-xiaoyu** [comment]
@rgaufman You may have your old version of emqx running so one of the port is in use. Kill the old process if that is the case. Also check if 8081 is used by some other process.

Then start your new emqx by `emqx console` and inspect the output to make sure all the ports is listened correctly.

**Comment by alanjiang** [comment]
Protocol 'ekka': register/listen error: eaddrinuse

**Comment by zmstone** [comment]
Hi @alanjiang 
Which versions in your case?
If it’s not exactly the same, could you create a new issue.
eaddrinuse is a known issue, but we need to know more information before suggesting fixes

**Comment by alanjiang** [comment]
@zmstone  , I also get the problem.  If i run "/app/emqx/bin/emqx_ctl status", it echos as : 
No commands available.

**Comment by zmstone** [comment]
Is it after upgrade?
Which version is it you upgraded from and to?

**Comment by alanjiang** [comment]
Not upgrade, i install this version all the same.

**Comment by alanjiang** [comment]
Just only one of my 3 nodes can execute the emqx cmd

**Comment by alanjiang** [comment]
![image](https://user-images.githubusercontent.com/8122752/127447683-08112d64-4db3-4b3e-a27c-9f646065d24f.png)

**Comment by zmstone** [comment]
It's likely you have another emqx node running in this node.
could share the output of this command `ps -ef | grep beam` ?

**Comment by zmstone** [comment]
btw, 4.1 is pretty old. we recommend version 4.3, the latest at this moment is 4.3.6

**Comment by alanjiang** [comment]
> It's likely you have another emqx node running in this node.
> could share the output of this command `ps -ef | grep beam` ?

![image](https://user-images.githubusercontent.com/8122752/127601668-880c9b40-175d-431d-8dea-a5935de875e9.png)

**Comment by alanjiang** [comment]
![image](https://user-images.githubusercontent.com/8122752/127601951-69b89e70-b34e-49e8-a3a0-92b2f5d68df1.png)
