### ISSUE TITLE
MQTT V5 Session Expiry Interval in CONNECT does not work

### ISSUE THREAD

**Issue by rqg0717** [emqx/emqx#3702]
**Environment**:
- EMQ X version (e.g. `emqx_ctl status`): 4.1.4
- Hardware configuration (e.g. `lscpu`): Processor	Intel(R) Xeon(R) CPU E5-1620 v3 @ 3.50GHz, 3501 Mhz, 4 Core(s), 8 Logical Processor(s)
- OS (e.g. `cat /etc/os-release`): Microsoft Windows 10 Enterprise  Version 10.0.17763 Build 17763
- Kernel (e.g. `uname -a`): Version 10.0.17763 Build 17763
- Erlang/OTP version (in case you build emqx from source code):  N/A
- Others:

**What happened and what you expected to happen**:
set Session Expiry Interval to 2,592,000 seconds (30 days) and CleanStart = false using Paho MQTT v1.3.5 client but after successfully connected to the broker, it still shows Session Expiry Interval is 0 on Dashboard->Clients
the client is able to publish to or subscribe of topics with no issues.
 
**How to reproduce it (as minimally and precisely as possible)**:
1. set Session Expiry Interval to 2,592,000 seconds (30 days) on client
2. it shows Session Expiry Interval is 0 on emqx dashboard.

**Comment by tigercl** [comment]
@rqg0717 The setting of the `Session Expiry Interval` field should be no problem, maybe you can use the trace command to view the content of the message actually received by emqx. You can execute the following command and then view the log in the file or provide it to us:
`trace start client <ClientId> <File> [<Level>]`

**Comment by tigercl** [comment]
@rqg0717 By the way, have you configured the `server_keepalive` configuration item in emqx.conf.

**Comment by rqg0717** [comment]
@tigercl the trace command returns the following error: 
`[error] trace clientid CLIENTID_42: "Cannot trace at a log level (debug) lower than the primary log level (warning)"`
BTW, `server_keepalive` is not set.

**Comment by rqg0717** [comment]
@tigercl found the following log in emqx.log.1:
`2020-09-02 09:48:29.130 [error] <<"CLIENTID_42">>@172.25.41.37:62331   crasher:
    initial call: cowboy_tls:connection_process/4
    pid: <0.625.0>
    registered_name: []
    exception error: no case clause matching {error,timeout}
      in function  cowboy_websocket:websocket_send_close/2 (d:/a/emqx-rel/emqx-rel/_build/emqx/lib/cowboy/src/cowboy_websocket.erl, line 640)
      in call from cowboy_websocket:websocket_close/3 (d:/a/emqx-rel/emqx-rel/_build/emqx/lib/cowboy/src/cowboy_websocket.erl, line 623)
    ancestors: [<0.435.0>,<0.434.0>,ranch_sup,<0.151.0>]
    message_queue_len: 2
    messages: [{timeout,#Ref<0.352065425.2903506946.132867>,emit_stats},
                  {deliver,<<"/genfare/TVM/broadcast">>,
                           {message,<<0,5,174,85,186,70,210,80,242,234,0,0,1,
                                      242,0,1>>,
                                    0,<<"MQTT_TVM_001">>,
                                    #{dup => false,retain => false},
                                    #{peerhost => {172,25,41,37},
                                      proto_ver => 4,protocol => mqtt,
                                      username => <<"admin@genfare">>},
                                    <<"/genfare/TVM/broadcast">>,
                                    <<"this is a test.">>,1599058104210}}]
    links: [<0.435.0>]
    dictionary: [{recv_msg,1},
                  {recv_pkt,5},
                  {incoming_pubs,1},
                  {guid,{1599058093991000,267086836269681,1}},
                  {recv_cnt,5},
                  {acl_keys_q,
                      {[{publish,<<"/genfare/TVM/test">>},
                        {subscribe,<<"/genfare/TVM/test">>}],
                       [{subscribe,<<"/genfare/TVM/broadcast">>}]}},
                  {incoming_bytes,10485934},
                  {send_cnt,6},
                  {{publish,<<"/genfare/TVM/test">>},{allow,1599058093991}},
                  {outgoing_bytes,10485872},
                  {send_oct,10485872},
                  {'$logger_metadata$',
                      #{clientid => <<"CLIENTID_42">>,
                        peername => "172.25.41.37:62331"}},
                  {outgoing_pubs,1},
                  {rand_seed,
                      {#{bits => 58,jump => #Fun<rand.13.8986388>,
                         next => #Fun<rand.10.8986388>,type => exsss,
                         uniform => #Fun<rand.11.8986388>,
                         uniform_n => #Fun<rand.12.8986388>},
                       [162922621712639256|275954805816861056]}},
                  {recv_oct,10485934},
                  {send_msg,1},
                  {send_pkt,6},
                  {{subscribe,<<"/genfare/TVM/test">>},{allow,1599058085835}},
                  {acl_cache_size,3},
                  {{subscribe,<<"/genfare/TVM/broadcast">>},
                   {allow,1599058085694}}]
    trap_exit: true
    status: running
    heap_size: 2586
    stack_size: 27
    reductions: 3309587
  neighbours:

2020-09-02 09:48:29.131 [error] Ranch listener 'mqtt:wss:443' had connection process started with cowboy_tls:start_link/4 at <0.625.0> exit with reason: {{case_clause,{error,timeout}},[{cowboy_websocket,websocket_send_close,2,[{file,"d:/a/emqx-rel/emqx-rel/_build/emqx/lib/cowboy/src/cowboy_websocket.erl"},{line,640}]},{cowboy_websocket,websocket_close,3,[{file,"d:/a/emqx-rel/emqx-rel/_build/emqx/lib/cowboy/src/cowboy_websocket.erl"},{line,623}]},{proc_lib,wake_up,3,[{file,"proc_lib.erl"},{line,259}]}]}
`
