### ISSUE TITLE
Does emqx support docker swarm mode?

### ISSUE THREAD

**Issue by danieljfarrell** [emqx/emqx#3703]
I can see the example on your docker page https://hub.docker.com/r/emqx/emqx which shows how to use emqx with docker-compose. Does emqx also support running in swarm mode to distribute nodes across replicas?

**Comment by zhanghongtong** [comment]
Yes, emqx supports docker swarm mode, but you need to configure it yourself, we do not provide examples for the time being, or you can consider k8s

**Comment by danieljfarrell** [comment]
Is there a technical reason for supporting it but not showing examples? Maybe it is not as reliable as other approaches? Thanks! I will investigate further.

**Comment by AmnaSnene** [comment]
@danieljfarrell I'm still interested in running emqx in swarm mode. Did you figure out an example?

**Comment by danieljfarrell** [comment]
No I didn't get any further. I ended up using VerneMQ https://github.com/vernemq/vernemq

**Comment by AmnaSnene** [comment]
I'm benchmarking MQTT brokers in cluster mode at the edge (on raspberry pi's). I already used VerneMQ. Maybe I will opt for manual installation with EMQX.

**Comment by pedroetb** [comment]
I have been using EMQX `v4.4` into a Docker Swarm cluster, and now my deployment configuration have been migrated to EMQX `v5` (tested with `v5.5.1`).

<https://gitlab.com/pedroetb-projects/emqx>

Single Swarm service is deployed, with desired number of replicas. Also, I'm exposing MQTT TCP listener (1883) via Traefik TCP router and using NFS storage.

Hope this helps someone!

**Comment by vigor-victorlee** [comment]
Hi pedroetb, Thanks for the info. I am new to emqx space, could you show your way step-by-step how to set things up with https://gitlab.com/redmic-project/docker/docker-deploy & https://gitlab.com/redmic-project/gitlab-ci-templates ?

Thanks

**Comment by pedroetb** [comment]
@vigor-victorlee thanks for asking!

I'm using [docker-deploy](https://gitlab.com/redmic-project/docker/docker-deploy) as a custom deployment tool. Basically, it acts as a link between repository / CI pipelines and your server via SSH, sending deployment resources (`compose.yaml` and `.env` in this case) and setting up Swarm services (EMQX in this case).

To configure and run docker-deploy, I'm using my own fork of [gitlab-ci-templates](https://gitlab.com/pedroetb-projects/gitlab-ci-templates). It defines GitLab CI jobs to perform deployments running docker-deploy, and also has my custom environments and variable values (secret values are defined using GitLab project variables).

So, to follow this way, you can setup your own repository for deployment and customize both EMQX configuration and CI jobs if needed. You can define a larger `.gitlab-ci.yml` file without using templates too (may be easier to understand what are them doing this way first) or use another CI tool like GitHub Actions.

If you find any problem with them or need more info, please open an issue there to avoid flooding this EMQX issue.
