### ISSUE TITLE
How to upgrade EMQ from 3.2.7 to the latest version and keep my configuration.

### ISSUE THREAD

**Issue by xyz361** [emqx/emqx#3707]
**Please describe your problem in detail, if necessary, you can upload the log file through the attachment**:

Currently, I have installed the EMQ X Broker v3.2.7 in ubuntu 18.04, And we have set up our own configuration in the emqx.conf file, ACL rules in acl.conf file and user authentications in emqx_auth_username.conf.

Now we want to upgrade it to the latest version 4.1.4. It is possible to upgrade with all the setups and configurations, Which we have already made.

How can we upgrade to the latest version?

**Comment by tigercl** [comment]
@xyz361 Sorry for late reply. The current 3.x version does not support a smooth upgrade to 4.x, you must manually uninstall and install the latest version, sorry for the inconvenience caused to you. We have added data import and export functions in version 4.1, which supports exporting data from the old version and then importing it to the new version. In version 4.2, the hot upgrade function between revisions is supported.

**Comment by xyz361** [comment]
OK. Thank You for your response.
