### ISSUE TITLE
tls ecc two way - bugs

### ISSUE THREAD

**Issue by jingc1413** [emqx/emqx#3710]
**Environment**:

- EMQ X version (e.g. `emqx_ctl status`): 
       Node 'mqtt@192.168.80.2' is started
       emqx 4.0.7 is running
- Hardware configuration (e.g. `lscpu`):
       docker 
- OS (e.g. `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
        Linux mqtt 4.15.0-76-generic #86-Ubuntu SMP Fri Jan 17 17:24:28 UTC 2020 x86_64 Linux
- Erlang/OTP version (in case you build emqx from source code): 
- Others:

**What happened and what you expected to happen**:
       openssl 

**Environment**:

- EMQ X version (e.g. `emqx_ctl status`): 
       Node 'mqtt@192.168.80.2' is started
       emqx 4.0.7 is running
- Hardware configuration (e.g. `lscpu`):
       docker 
- OS (e.g. `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
        Linux mqtt 4.15.0-76-generic #86-Ubuntu SMP Fri Jan 17 17:24:28 UTC 2020 x86_64 Linux
- Erlang/OTP version (in case you build emqx from source code): 
- Others:

**What happened and what you expected to happen**:
       openssl self-signed certificate, One-way authenticatio is success, buf Two-way authentication is failed
       then, i genrate rsa certificate, it works.

**How to reproduce it (as minimally and precisely as possible)**:
11
**Anything else we need to know?**:
    i use this method:
        openssl s_client -tls1 -connect 127.0.0.1:8899 -CAfile cacert.pem  -cert cert.pem -key key.pem -showcerts
       openssl s_server -CAfile cacert.pem -cert cert.pem -key key.pem -tls1 -accept 8899 -debug
    it works

**Comment by tigercl** [comment]
@jingc1413 You can refer to the following URL: https://www.emqx.io/blog/enable-two-way-ssl-for-emqx.
