### ISSUE TITLE
Cannot bind broker external port to 443

### ISSUE THREAD

**Issue by youyudekucaizi** [emqx/emqx#3711]
**Please describe your problem in detail, if necessary, you can upload the log file through the attachment**:
Hi guys:
  For the consideration of port hiding, we want to change  listener.tcp.external port from 1883 to 443. However, once I changed the port to 443 and run emqx restart. it doesn't work. We are sure that the port 443 was not be occupied. Can someone tell me the reason? And also if I change the port to 1884 and run emqx restart ,it will work properly. So, is there some limitations about the external tcp listener port? My current emqx version is v4.0.10. any suggestions would be greatly appreciated.

**Comment by tigercl** [comment]
@youyudekucaizi What you said does not work, is the listener can not be started or still use the previous configuration. Any error log in `.../log/emqx.log.*`?

**Comment by spring2maz** [comment]
I guss it is because 443 is a privileged port, unless emqx is started by super user(root), it will not have permission to bind.
There are few workarounds such as in this thread
https://stackoverflow.com/questions/413807/is-there-a-way-for-non-root-processes-to-bind-to-privileged-ports-on-linux

I’d say iptables (or other means of forwarding) is the easiest and most straightforward way

**Comment by youyudekucaizi** [comment]
> @youyudekucaizi What you said does not work, is the listener can not be started or still use the previous configuration. Any error log in `.../log/emqx.log.*`?

The listener can not be started. Not use the previous configuration. Even though I run as root, the listener cannot be bound to port 443. The log is as shown below:
<img width="419" alt="Snipaste_2020-09-08_09-57-35" src="https://user-images.githubusercontent.com/28330414/92425462-eddaba80-f1b9-11ea-89c8-208c511f244f.png">

**Comment by youyudekucaizi** [comment]
> I guss it is because 443 is a privileged port, unless emqx is started by super user(root), it will not have permission to bind.
> There are few workarounds such as in this thread
> https://stackoverflow.com/questions/413807/is-there-a-way-for-non-root-processes-to-bind-to-privileged-ports-on-linux
> 
> I’d say iptables (or other means of forwarding) is the easiest and most straightforward way

> Thank you for your reply. But even I run as root, I still cannot bind the port to 443.

**Comment by spring2maz** [comment]
Hi the error code `eacces` means access not permitted.
Was emqx installed from a deb or rpm package?
Could please check if `RUNNER_USER` is set to `emqx` in the file `$(which emqx)`?
Emqx start script drops privileges by `su - $RUNNER_USER`
So please make sure runner user is set to root (if you insist running it with root)

Another reason (which I am not confident if it applies to root user) is SELinux.

**Comment by vaart3333** [comment]
This problem still has no solution?

**Comment by id** [comment]
@vaart3333 please checkout comment from @spring2maz
