### ISSUE TITLE
Didnt recieve Webhook plugin disconnect event if client disconnects after 5min period

### ISSUE THREAD

**Issue by Ayesha262** [emqx/emqx#3718]
When client disconnects within 5 min period then he receives disconnect event as follows, but in case of disconnection after 5 min, no disconnect event is received

emqx.log.1
2020-09-09 12:53:05.001 [debug] <<"TestClient7f715062c8524">>@202.163.113.248:45360 [WebHook] Send to: "http://localhost:3010/internal/events", params: 
2020-09-09 12:53:05.002 [debug] <<"TestClient7f715062c8524">>@202.163.113.248:45360 [MQTT] Terminated due to {shutdown,tcp_closed}

erlang.log.1
(emqx@172.31.28.127)1> 2020-09-09 12:53:34.930 [debug] API publish Params:[{<<"topics">>,<<"profile/appA/UserB">>},
                    {<<"qos">>,0},
                    {<<"payload">>,
                     <<"{\"id\":0,\"type\":\"USRPU\",\"from\":\"UserB\",\"data\":\"{\\\"is_online\\\":false}\",\"created\":1599656014925}">>},
                    {<<"clientid">>,<<"UserB">>}]
(emqx@172.31.28.127)1> 2020-09-09 12:53:34.931 [info] PUBLISH to profile/appA/UserB: <<"{\"id\":0,\"type\":\"USRPU\",\"from\":\"UserB\",\"data\":\"{\\\"is_online\\\":false}\",\"created\":1599656014925}">>

emqx config:
emqx-4.1.1
zone.internal.enable_acl = on
zone.internal.allow_anonymous = false
zone.external.acl_deny_action = disconnect
zone.external.session_expiry_interval = 5m
acl_deny_action = disconnect
acl_cache_ttl = 5m

**Comment by tigercl** [comment]
@Ayesha262 Is it convenient for you to use the trace command to obtain a complete debug log and send it to us for our analysis? You can refer to the following documents: https://docs.emqx.io/broker/latest/en/advanced/cli.html.

**Comment by Ayesha262** [comment]
These trace logs shows emqx is not getting terminate notification in case we disconnect existing client after 5 min

trace logs of ClientX disconnected within 5min
[TestClientX_trace.log](https://github.com/emqx/emqx/files/5199755/TestClientX_trace.log)


trace logs of ClientY disconnected after 7min
[TestClientY_trace.log](https://github.com/emqx/emqx/files/5199758/TestClientY_trace.log)

**Comment by tigercl** [comment]
@Ayesha262 It seems that emqx has not received any disconnection packets. Can you make sure that the logic of the two disconnections is the same?
