### ISSUE TITLE
Questions about qos1 qos2 mqueue

### ISSUE THREAD

**Issue by vito11** [emqx/emqx#3719]
Hi, I notice that there is a mqueue with a default length of 1000 to store Qos1 and Qos2 packets.  And I have two questions about this mqueue.

1. How to set the max retain time for mqueue? (I have a requirement that if client doesn't  receive these packets in a specific time period,  mqueue should drop all the stored packets)

2. is each mqueue owned by each topic ? or owned by each client_id? 

Thanks!

**Comment by turtleDeng** [comment]
Thank you for participating

1 MQTT V3 does not support message expiration, MQTT V5 can use the Message-Expiry-Interval attribute

2 Each client has a queue

**Comment by vito11** [comment]
Many thanks for your support
