### ISSUE TITLE
High CPU usage with small amount of clients

### ISSUE THREAD

**Issue by nightwolfz** [emqx/emqx#3722]
I have a EMQX cluster with only about 1000 clients connected to it (~8000 subscriptions in total).

Sending 10 kb/s binary compressed data to each client

[https://pasteboard.co/JqWTqMy.png](https://pasteboard.co/JqWTqMy.png)

Just wondering if this kind of CPU usage is normal?  If I turn on http_auth plugin, it jumps to 1800+%

**Comment by nightwolfz** [comment]
Some things I tried tweaking:

- followed tuning guide
- set logging level to error
- disabled most plugins
- node.async_threads  from 4 all the way to 256
- different listener settings
- rec, snd and other buffers

**Comment by tigercl** [comment]
@nightwolfz The CPU usage in the picture is normal, but I don’t understand why it rises so much after loading http_auth plugin. Are your clients repeating connections frequently?

**Comment by nightwolfz** [comment]
Thanks @tigercl I believe since the publishers (running on the same machine as EMQX) are connected through websockets and websockets don't have an internal zone, then I imagine every publish goes through ACL.

Is there anyway to setup an internal zone for websockets or let EMQX know that some IPs (like 192.168....) can skip ACL?  Thanks

**Comment by nightwolfz** [comment]
Guess I'll move to TCP
