### ISSUE TITLE
mqtt客户端无法接收到broker的消息

### ISSUE THREAD

**Issue by Jakecy** [emqx/emqx#3723]
你好，我这里有一个单节点的broker(v4.1.3)，俩个客户端：一个是java应用集成了mqtt，另一个是paho客户端工具，俩个客户端监听同一个topic，当我向此topic发送消息时，pah客户端工具可以收到消息通知，而java应用却无法收到消息或者收到的消息延迟很高(有的消息延迟了31分钟)。

请问，emqx提供的有没有工具或命令，可以帮助我查看下，broker有没有把消息转发出去，以及当前的消息队列的使用情况？借以找到问题的缘由，如能答复，万分感谢！

**Comment by iampastor** [comment]
看日志就可以了

**Comment by Jakecy** [comment]
日志已经看过了，没有看到相关的东西，刚tcpdump抓包已经找到问题了，谢谢。

**Comment by iampastor** [comment]
打开debug日志应该可以的，不客气

**Comment by antelop304** [comment]
> 日志已经看过了，没有看到相关的东西，刚tcpdump抓包已经找到问题了，谢谢。
什么问题导致的呀，我们现在也遇到一样的问题，也是一段时间后，客户端可以收到消息，java程序收不到

**Comment by iwilsonlee** [comment]
> 日志已经看过了，没有看到相关的东西，刚tcpdump抓包已经找到问题了，谢谢。

@Jakecy 请问可以说一下问题接法吗？我这边也遇到了同样的问题
