### ISSUE TITLE
emqx v4.1.2 execute emqx.cmd install failed

### ISSUE THREAD

**Issue by fissssssh** [emqx/emqx#3725]
I want to install eqmx on windows as a service, but `emqx.cmd install` throw 
```shell
emqx\bin>emqx.cmd install
emqx\erts-10.7\bin\erlsrv.exe: Unable to register emqx_v4.1.2 service with service manager.
Error: ¾Ü¾ø·ÃÎÊ¡£
[SC] OpenService FAILED 1060:
The specified service does not exist as an installed service.
```

**Comment by tigercl** [comment]
@GhostNoc Just execute `./emqx start`, maybe you can refer to this document: https://docs.emqx.io/broker/latest/en/getting-started/install.html##zip. Sincerely hope it can help you.

**Comment by GhostNoc** [comment]
> @GhostNoc Just execute `./emqx start`, maybe you can refer to this document: https://docs.emqx.io/broker/latest/en/getting-started/install.html##zip. Sincerely hope it can help you.

I know `./emqx start` can start it, and I hope it can automatically start with the windows

**Comment by turtleDeng** [comment]
Please run cmd as an administrator to install.
