### ISSUE TITLE
How to get the Client TLS Certificate when the client connecting EMQ with TLS/SSL?

### ISSUE THREAD

**Issue by BruceOfChina** [emqx/emqx#3726]
客户端通过TLS/SSL连接到EMQ服务器的时候，如何通过EMQ或者EMQ的插件获取到客户端连接时的证书？

**Comment by tigercl** [comment]
@BruceOfChina This behavior is currently not supported. Would you please talk about why you want to do this?

**Comment by BruceOfChina** [comment]
Because I need to authenticate the content of Client TLS Certificate, so I have to get the client TLS Certificate first.

**Comment by tigercl** [comment]
@BruceOfChina We provide `%C` and `%d` options to get common name and subject of client TLS certificate. Take http authentication plugin as an example, You can configure it like this:
`auth.http.auth_req.params = clientid=%c,username=%u,password=%P,common_name=%C,subject=%d`.

**Comment by BruceOfChina** [comment]
yes, I have realised this. But only this is not enough.

**Comment by tigercl** [comment]
@BruceOfChina That may not meet your needs at the moment, what information do you need? We can consider this demand.

**Comment by BruceOfChina** [comment]
I want to compile the EMQ source code in windows environment. How to get the EMQ source code that can be compiled in windows?

**Comment by BruceOfChina** [comment]
auth.http.auth_req.params = clientid=%c,username=%u,password=%P,common_name=%C,subject=%d,

Besides this information, I also need the content and serial number of client TLS, how can I get the information.

**Comment by HJianBo** [comment]
Sorry, @BruceOfChina  It just supports `%C` `%d` now.

We plan to support more parameters in 5.0
