### ISSUE TITLE
What is the maximum topic length of emqx?

### ISSUE THREAD

**Issue by youyudekucaizi** [emqx/emqx#3727]
Hi,guys:
  What is the maximum topic length of emqx? It seems that it is not the length of 65535?

**Comment by tigercl** [comment]
@youyudekucaizi Currently we do not limit the maximum length of topics.

**Comment by youyudekucaizi** [comment]
@tigercl  We found that the topic maximum length is 4096.When the topic length exceeds 4096, EMQX will force to close the socket due to topic_name_invalid according to EMQX log. So how can we change this length? The MQTT protocol states that the maximum topic length is 65535? Why emqx doesn't follow protocol specification? Is length 4096 hard corded in EMQX? Thanks in advance.

**Comment by youyudekucaizi** [comment]
@tigercl We found that the topic maximum length is 4096.When the topic length exceeds 4096, EMQX will force to close the socket due to topic_name_invalid according to EMQX log as shown below. So how can we change this length? The MQTT protocol states that the maximum topic length is 65535.Why emqx doesn't follow protocol specification? Is length 4096 hard corded in EMQX? Thanks in advance.
<img width="582" alt="Snipaste_2020-09-21_10-37-22" src="https://user-images.githubusercontent.com/28330414/93729322-9a735e00-fbf6-11ea-8daf-06424c16fed3.png">

**Comment by tigercl** [comment]
@youyudekucaizi Sorry for the wrong answer. I reconfirmed it and it may be a bug. It is currently a fixed limit value that cannot be modified. We will fix it as soon as possible.

**Comment by HJianBo** [comment]
Fixed https://github.com/emqx/emqx/pull/3962/files
