### ISSUE TITLE
Pingresp not sent?

### ISSUE THREAD

**Issue by GopherJ** [emqx/emqx#3730]
**Please describe your problem in detail, if necessary, you can upload the log file through the attachment**:

I'm currently using paho.mqtt.golang + emqx broker 4.1, `pingresp not received` error has been raised if I use tls, if I remove tls and connect to emqx broker on 1883, it works normally.

I'm using [this script](https://github.com/GopherJ/cfg/tree/master/cert) to generate certificate, the generated certificate works normally with mosquitto, which means my IOT devices can bridge normally to cloud emqx broker.

However, it's not the case with `paho.mqtt.golang` + `emqx 4.1 & 4.2`, I suspect this is more a problem on `paho.mqtt.golang` side but since if I remove ssl, things got better, I'm then wondering if emqx didn't give a pingresp very quickly in ssl case?

**Comment by GopherJ** [comment]
See also: https://github.com/eclipse/paho.mqtt.golang/issues/453

**Comment by tigercl** [comment]
@GopherJ Sorry for late reply, in my understanding, whether TLS is used or not will not affect the sending of PINRESP packets, maybe you can judge where the problem happened by capturing packets.

**Comment by GopherJ** [comment]
hi @tigercl I see emqx is throwing out this error:

```
2020-09-23 13:06:17.004 [error]     supervisor: 'esockd_connection_sup - <0.1824.0>'
    errorContext: connection_shutdown
    reason: {ssl_error,
                {tls_alert,
                    {bad_certificate,
                        "TLS server: In state certify received CLIENT ALERT: Fatal - Bad Certificate\n "}}}
    offender: [{pid,<0.20406.8>},
               {name,connection},
               {mfargs,
                   {emqx_connection,start_link,
                       [[{deflate_options,[]},
                         {max_conn_rate,500},
                         {active_n,100},
                         {zone,external}]]}}]
```

any idea on the reason? the certificates work at the beginning but after a period, emqx is reporting this

**Comment by GopherJ** [comment]
@tigercl please do you have any idea? I need to quickly identify the problem, I'm not sure if it comes from emqx or paho.mqtt.golang yet

**Comment by GopherJ** [comment]
Close because I got it reproduced using `paho.mqtt.golang + mosquitto`, it should be on `paho.mqtt.golang` side
