### ISSUE TITLE
how to use broker.shared_subscription_strategy  with "$queue/" subscription

### ISSUE THREAD

**Issue by dante1234** [emqx/emqx#3734]
**Please describe your problem in detail, if necessary, you can upload the log file through the attachment**:
my emqx version is 3.0 ,  not single node 
i use shared subscription without group to subscribe  topic;   and set the "broker.shared_subscription_strategy" to "hash";  

Is it the right way to use it ?   my test show that it doesn't take effect .

**Comment by dante1234** [comment]
the emqx.conf doesn't take effect when i use 'emqx restart' to restart emq;

**Comment by tigercl** [comment]
@dante1234 The previous version does have problems with reloading the configuration. It is recommended to use `./emqx stop + ./emqx start` or use a newer version.

**Comment by dante1234** [comment]
ok.  Thanks anyway
