### ISSUE TITLE
ignore_loop_deliver causing issues

### ISSUE THREAD

**Issue by hexuallyactive** [emqx/emqx#3738]
**Environment**:

- EMQ X version: 4.2
- Hardware configuration: any
- OS: ubuntu 16.04

**What happened and what you expected to happen**:

EMQX 3.x correctly uses ignore_loop_deliver=true, but 4.x does not, and instead ends up filling the inflight window, and then once full will start filling the mqueue until full.  This results in no messages being delivered at all from other client publishes.

**How to reproduce it (as minimally and precisely as possible)**:

- zone.external.ignore_loop_deliver = true
- start a client subscribed to test/#
- start publishing messages from the same client to test/1
- clients in both cases are using 3.11 protocol version

**Comment by tigercl** [comment]
@hexuallyactive Thank you for your feedback, we will confirm and fix this issue as soon as possible, and you will see it fixed as early as v4.2.1.

**Comment by HJianBo** [comment]
It has released in v4.2.1 : https://github.com/emqx/emqx/pull/3741
