### ISSUE TITLE
what does it means `active: exited` status? Shall I pay attention to it?

### ISSUE THREAD

**Issue by GopherJ** [emqx/emqx#3739]
**Please describe your problem in detail, if necessary, you can upload the log file through the attachment**:

I have a broker running on a ubuntu18.04 production server, this morning I found the systemd status becomes:

![image](https://user-images.githubusercontent.com/33961674/94243451-b25d2180-ff17-11ea-9b69-5426d6b6eff2.png)

Is this a normal state?

**Comment by tigercl** [comment]
@GopherJ This is the last time you log out, you don’t need to pay special attention to it.

**Comment by GopherJ** [comment]
ok thanks
