### ISSUE TITLE
change rest api password

### ISSUE THREAD

**Issue by khoshbin** [emqx/emqx#3743]
**Please describe your problem in detail, if necessary, you can upload the log file through the attachment**:
I changed dashboard admin user and also default password in etc/plugins/emq_dashboard.conf
But rest api password has not chnaged yet , it is public yet

**Comment by tigercl** [comment]
@khoshbin Sorry for the inconvenience. We use AppID and AppSecret for REST API authentication, which is located in Dashboard -> General -> Application.

**Comment by khoshbin** [comment]
thanks
