### ISSUE TITLE
emqx oom 

### ISSUE THREAD

**Issue by zibuyu1995** [emqx/emqx#3744]
Crash on a running emqx cluster

**Environment**:

- EMQ X version (e.g. `emqx_ctl status`): 4.1.1 
- OS (e.g. `cat /etc/os-release`): linux

**Emqx log**
![3291601275509_ pic_hd](https://user-images.githubusercontent.com/17525759/94413098-3419ad00-01ad-11eb-9271-d3fdf851b1a2.jpg)
![3301601275558_ pic_hd](https://user-images.githubusercontent.com/17525759/94413106-367c0700-01ad-11eb-8dd4-c203435b84da.jpg)

**Linux log**
![3121601277276_ pic_hd](https://user-images.githubusercontent.com/17525759/94413275-7347fe00-01ad-11eb-8853-e1ea91e47dc7.jpg)

**Comment by terry-xiaoyu** [comment]
We may need to keep watching this problem. The OOM issue was probably caused by a long mailbox, and eventually the Erlang VM was killed by the system.

Set the `force_shutdown_policy` to prevent this:

```
zone.external.force_shutdown_policy = 2000|32MB
```
