### ISSUE TITLE
JSON Log format

### ISSUE THREAD

**Issue by dr460neye** [emqx/emqx#3755]
**What would you like to be added/modified**:

Add an option to change log output to json format.
Support fields:
- level: for log level ( info, debug, error, warning )
- timestamp: as unix timestamp or as iso standard
- additional attributes, depending on each message

**Why is this needed**:

In modern orchestrated environments, fluentd, logstash or other log collectors are in use. Meanwhile it gets an industry standard, thats logs for production systems are beeing provided in json format. In specific in fully orchestrated environments, you try to keep "one log format" for all applications, to keep the zoo under control.

**Comment by tigercl** [comment]
@dr460neye Sorry for not responding in time because of vacation. We will discuss this feature and reply to you in time.

**Comment by JohnRoesler** [comment]
I would also very much like to see this feature added. As noted, it would highly useful when integrating into my existing logging pipeline to have emqx in json format similar to all my other applications' logs.

**Comment by JohnRoesler** [comment]
Any updates to share on when this might get added to emqx?

**Comment by zmstone** [comment]
Hi. @JohnRoesler 
This is not planed for 4.x releases, we will add it in v5.0.
Our goal is to have v5.0 released in 2021 Q1

**Comment by Hyvi** [comment]
Q1 will be end,  the feature has been supported ?

**Comment by k32** [comment]
Hello,
Yes, this feature has been added in EMQX `4.3`.
Now you can set `log.formatter` parameter to `json`.
