### ISSUE TITLE
emqx_auth_username plugin issues

### ISSUE THREAD

**Issue by yuvarajan1989k** [emqx/emqx#3758]
Hi,

I am running emqx in the GCP autoscale group with emqx_auth_username plugin enabled. it was working fine without any issues. suddenly my authentication was not working, when I check, the plugin was not starting up. I don't understand the error. 

FYI:- below is the error. 
`[Ctl] CMD Error:{aborted,{no_exists,[emqx_auth_username,[{{emqx_auth_username,'$1','_'},[],['$1']}]]}}, Stacktrace:[{mnesia,abort,1,[{file,"mnesia.erl"},{line,355}]},{mnesia,dirty_all_keys,1,[{file,"mnesia.erl"},{line,1960}]},{emqx_auth_username,cli,1,[{file,"/emqx-rel/_build/emqx/lib/emqx_auth_username/src/emqx_auth_username.erl"},{line,51}]},{emqx_ctl,run_command,2,[{file,"/emqx-rel/_build/emqx/lib/emqx/src/emqx_ctl.erl"},{line,105}]},{rpc,'-handle_call_call/6-fun-0-',5,[{file,"rpc.erl"},{line,197}]}]
RPC to mqtt-prod1-pq0b@10.0.6.101 error: {aborted,
                                          {no_exists,
                                           [emqx_auth_username,
                                            [{{emqx_auth_username,'$1','_'},
                                              [],
                                              ['$1']}]]}}`

**Comment by tigercl** [comment]
@yuvarajan1989k Looks like the plugin has crashed and stopped before? Can you provide more logs for our analysis?

**Comment by yuvarajan1989k** [comment]
Hi ,

[error] [Plugins] Load plugin emqx_auth_username failed, cannot start plugin emqx_auth_username for {bad_return,{{emqx_auth_username_app,start,[normal,[]]},{'EXIT',{{badmatch,{system_limit,emqx_auth_username,{'mqtt-prod1-dg2c@10.0.6.26',none_active}}},[{emqx_auth_username,init,1,[{file,"/emqx-rel/_build/emqx/lib/emqx_auth_username/src/emqx_auth_username.erl"},{line,129}]},{emqx_auth_username_app,start,2,[{file,"/emqx-rel/_build/emqx/lib/emqx_auth_username/src/emqx_auth_username_app.erl"},{line,38}]},{application_master,start_it_old,4,[{file,"application_master.erl"},{line,277}]}]}}}}

Here is the log.

Thanks.

**Comment by aniston** [comment]
Hello,
I seem to be having a similar issue with emqx_auth_username plugin not starting with EMQX Broker Version 4.2.9 on a Debian 10 (4.19.171-2)
- normally after the broker gets an apt update of the EMQX version this plugin does not load automatically, manually loading it does work and retains its configuration as well.

anyone else experiencing similar behavior ?
