### ISSUE TITLE
Problem Mysql ACL

### ISSUE THREAD

**Issue by sergioxdev** [emqx/emqx#3759]
Hi Guys

I have the following problem when i try to apply the following setting it doesn't work:
-- Allow clients to subscribe to the topic of /smarthome/${clientid}/temperature with their own Client ID
INSERT INTO mqtt_acl (allow, ipaddr, username, clientid, access, topic) VALUES (1, NULL, NULL, NULL, 1, '/smarthome/%c/temperature');

----------------------
acl.conf
----------------------
{allow, {user, "dashboard"}, subscribe, ["$SYS/#"]}.
{allow, {ipaddr, "127.0.0.1"}, pubsub, ["$SYS/#", "#"]}.
{deny, all, subscribe, ["$SYS/#", {eq, "#"}]}.
%%{allow, all}.

----------------------
sql
----------------------
INSERT INTO `mqtt_acl` (`id`, `allow`, `ipaddr`, `username`, `clientid`, `access`, `topic`) VALUES
(1, 0, NULL, '$all', NULL, 1, '$SYS/#'),
(2, 1, NULL, 'bot', 'bot, 3, 'chbot'),
(3, 1, NULL, NULL, 'NULL, 3, 'chmsg/%c/message');

the bot manages to access the topic chbot, but any client gives me the following error
<<"client1">>@  [Channel] Cannot subscribe chmsg/client1/message due to Not authorized.
<<"client2">>@  [Channel] Cannot subscribe chmsg/client2/message due to Not authorized.

if I change the permissions on the database as follows:
(3, 1, NULL, NULL, 'NULL, 3, 'chmsg/%c/#');

the bot manages to access the topic chbot, but any client gives me the following error
<<"client1">>@  [Channel] Cannot subscribe chmsg/client1/message due to Not authorized.
<<"client2">>@  [Channel] Cannot subscribe chmsg/client2/message due to Not authorized.

if I change the permissions on the database as follows, it works:
(3, 1, NULL, 'client1', 'client1', 3, 'chmsg/client1/#'),
(4, 1, NULL, 'client2', 'client2', 3, 'chmsg/client2/#');

if I change the permissions on the database as follows, it works
(3, 1, NULL, 'client1', 'client1', 3, 'chmsg/client1/message'),
(4, 1, NULL, 'client2', 'client2', 3, 'chmsg/client2/message');

what am I doing wrong?

**Comment by tigercl** [comment]
@sergioxdev If you want to allow or deny all clients to subscribe or publish a topic, please use placeholder `$all` other than `NULL`.

**Comment by sergioxdev** [comment]
@tigercl just tested it works thanks so much.
