### ISSUE TITLE
Document/Guide for adding new database as storage

### ISSUE THREAD

**Issue by jixuan1989** [emqx/emqx#3772]
Hi, Currently EMQx supports writing data into InfluxDB, OpenTSDB, Timescale etc..
Is there some guide to add a new database as the storage layer?

If possible, I think supporting writing time series data into Apache IoTDB can be an option.

**Comment by tigercl** [comment]
@jixuan1989 Of course, you may need to refer to the following documents: https://docs.emqx.io/broker/latest/en/advanced/hooks.html, https://docs.emqx.io/broker/latest/en/advanced/plugins.html.

**Comment by jixuan1989** [comment]
Thanks @tigercl , will have a look and see whether we can do that.. (most of contributors in our community are familiar with Java rather than c/c++..)
