### ISSUE TITLE
Why appear Terminated for badarg sometimes?

### ISSUE THREAD

**Issue by apolloyang2017** [emqx/emqx#3775]
#### Environment

- OS: CentOS7 64bit
- Erlang/OTP: 
- EMQ: v3.2.7

#### Description
Why appear Terminated for badarg sometimes? the following is trace log:
2020-10-14 15:11:45.437 [debug] <<"server1">>@192.168.200.13:32814 [Channel] Terminated for badarg
2020-10-14 15:11:45.438 [info] <<"server1">>@192.168.200.13:32814 [Protocol] Shutdown for badarg
2020-10-14 15:11:45.438 [error] <<"server1">>@192.168.200.13:32814 ** State machine <0.6370.92> terminating
** Last event = {info,
                    {deliver,
                        [{publish,8445,
                             {message,
                                 <<0,5,177,156,62,132,123,185,59,190,49,0,23,
                                   50,235,118>>,
                                 1,<<"onenetstateless0">>,
                                 #{dup => false,retain => false},
                                 #{allow_publish => true,
                                   peername => {{192,168,200,10},54160},
                                   proto_ver => 4,
                                   username => <<"onenetstateless">>},
                                 <<47,99,50,115,47,109,101,115,115,97,103,101,
                                   47,0,104,0,4,95,134,164,176,0,2,0,20,105,82,
                                   101,109,111,116,101,50>>,
                                 <<"1E090046006C00010B0047000400002BC30046000F060D01050000000000190019010000001F00020014006800045F86A4B0000200146952656D6F74653230303531303030313833373615">>,
                                 {1602,659505,437626}}}]}}
** When server state  = {connected,
                            {state,esockd_transport,#Port<0.656416>,
                                {{192,168,200,13},32814},
                                undefined,running,100,
                                {pstate,external,
                                    #Fun<emqx_channel.1.118122990>,
                                    {{192,168,200,2},1883},
                                    {{192,168,200,13},32814},
                                    nossl,4,<<"MQTT">>,<<"server1">>,false,
                                    <0.6370.92>,undefined,undefined,
                                    <<"dashboard">>,<0.6373.92>,true,#{},
                                    undefined,undefined,60,false,
                                    #{msg => 8096,pkt => 16613},
                                    #{msg => 8444,pkt => 16613},
                                    true,
                                    {1602,652159,510731},
                                    #{from_client => 0,to_client => 0},
                                    emqx_channel,
                                    #{anonymous => true,
                                      auth_result => success,
                                      client_id => <<"server1">>,
                                      mountpoint => undefined,
                                      peername => {{192,168,200,13},32814},
                                      sockname => {{192,168,200,2},1883},
                                      username => <<"dashboard">>,
                                      ws_cookie => undefined,zone => external},
                                    undefined},
                                {none,#{max_size => 1048576,version => 4}},
                                {emqx_gc,
                                    #{cnt => {1000,970},
                                      oct => {1048576,1043801}}},
                                {keepalive,#Fun<emqx_channel.4.118122990>,
                                    2479884,45,
                                    {keepalive,check},
                                    #Ref<0.807121377.2069364740.174790>,0},
                                undefined,undefined,undefined,true,
                                #Ref<0.807121377.2069364740.174876>,15000}}
** Reason for termination = error:badarg
** Callback mode = [state_functions,state_enter]
** Stacktrace =
**  [{erlang,byte_size,
             [{error,<<47,99,50,115,47,109,101,115,115,97,103,101,47,0,104,0,4,
                       95>>,
                     <<134,164,176,0,2,0,20,105,82,101,109,111,116,101,50>>}],
             []},
     {emqx_frame,serialize_utf8_string,1,
                 [{file,"/emqx_rel/_checkouts/emqx/src/emqx_frame.erl"},
                  {line,636}]},
     {emqx_frame,serialize_variable,2,
                 [{file,"/emqx_rel/_checkouts/emqx/src/emqx_frame.erl"},
                  {line,458}]},
     {emqx_frame,serialize,2,
                 [{file,"/emqx_rel/_checkouts/emqx/src/emqx_frame.erl"},
                  {line,396}]},
     {emqx_channel,'-do_init/3-fun-0-',4,
                   [{file,"/emqx_rel/_checkouts/emqx/src/emqx_channel.erl"},
                    {line,169}]},
     {emqx_protocol,send,2,
                    [{file,"/emqx_rel/_checkouts/emqx/src/emqx_protocol.erl"},
                     {line,708}]},
     {emqx_protocol,deliver,2,
                    [{file,"/emqx_rel/_checkouts/emqx/src/emqx_protocol.erl"},
                     {line,610}]},
     {emqx_channel,connected,3,
                   [{file,"/emqx_rel/_checkouts/emqx/src/emqx_channel.erl"},
                    {line,245}]}]

2020-10-14 15:11:45.439 [notice] <<"server1">> [Session] Conn <0.6370.92> is discarded by <0.13862.92>
2020-10-14 15:11:45.440 [debug] <<"server1">>@192.168.200.13:55042 [Protocol] SEND CONNACK(Q0, R0, D0, AckFlags=0, ReasonCode=0)
2020-10-14 15:11:45.442 [debug] <<"server1">>@192.168.200.13:55042 [Channel] RECV <<130,29,0,1,0,24,36,115,104,97,114,101,47,115,101,114,118,101,
                 114,47,47,99,50,115,47,114,112,99,47,35,1>>
2020-10-14 15:11:45.442 [debug] <<"server1">>@192.168.200.13:55042 [Protocol] RECV SUBSCRIBE(Q1, R0, D0, PacketId=1, TopicFilters=[{<<"$share/server//c2s/rpc/#">>,#{nl => 0,qos => 1,rap => 0,rc => 0,rh => 0}}])
2020-10-14 15:11:45.443 [debug] <<"server1">>@192.168.200.13:55042 [Protocol] SEND SUBACK(Q0, R0, D0, PacketId=1, ReasonCodes=[1])
2020-10-14 15:11:45.444 [debug] <<"server1">>@192.168.200.13:55042 [Channel] RECV <<130,37,0,1,0,32,36,115,104,97,114,101,47,115,101,114,118,101,
                 114,47,47,99,50,115,47,97,115,121,110,99,95,114,101,112,108,
                 121,47,35,1>>
2020-10-14 15:11:45.444 [debug] <<"server1">>@192.168.200.13:55042 [Protocol] RECV SUBSCRIBE(Q1, R0, D0, PacketId=1, TopicFilters=[{<<"$share/server//c2s/async_reply/#">>,#{nl => 0,qos => 1,rap => 0,rc => 0,rh => 0}}])
2020-10-14 15:11:45.440 [error] <<"server1">>@192.168.200.13:32814   crasher:
    initial call: emqx_channel:init/1
    pid: <0.6370.92>
    registered_name: []
    exception error: bad argument
      in function  byte_size/1
         called as byte_size({error,<<47,99,50,115,47,109,101,115,115,97,103,
                                      101,47,0,104,0,4,95>>,
                                    <<134,164,176,0,2,0,20,105,82,101,109,
                                      111,116,101,50>>})
      in call from emqx_frame:serialize_utf8_string/1 (/emqx_rel/_checkouts/emqx/src/emqx_frame.erl, line 636)
      in call from emqx_frame:serialize_variable/2 (/emqx_rel/_checkouts/emqx/src/emqx_frame.erl, line 458)
      in call from emqx_frame:serialize/2 (/emqx_rel/_checkouts/emqx/src/emqx_frame.erl, line 396)
      in call from emqx_channel:'-do_init/3-fun-0-'/4 (/emqx_rel/_checkouts/emqx/src/emqx_channel.erl, line 169)
      in call from emqx_protocol:send/2 (/emqx_rel/_checkouts/emqx/src/emqx_protocol.erl, line 708)
      in call from emqx_protocol:deliver/2 (/emqx_rel/_checkouts/emqx/src/emqx_protocol.erl, line 610)
      in call from emqx_channel:connected/3 (/emqx_rel/_checkouts/emqx/src/emqx_channel.erl, line 245)
    ancestors: [<0.1638.0>,<0.1637.0>,esockd_sup,<0.1356.0>]
    message_queue_len: 4
    messages: [{'EXIT',#Port<0.656416>,normal},
                  {deliver,
                      [{publish,8446,
                           {message,
                               <<0,5,177,156,62,132,126,59,59,190,92,0,24,226,
                                 31,161>>,
                               1,emqx_mod_presence,
                               #{dup => false,retain => false,sys => true},
                               #{allow_publish => true},
                               <<"$SYS/brokers/30d337a4ca44@192.168.200.2/clients/server1/disconnected">>,
                               <<"{\"clientid\":\"server1\",\"username\":\"dashboard\",\"reason\":\"badarg\",\"ts\":1602659505438}">>,
                               {1602,659505,438268}}}]},
                  {shutdown,discard,{<<"server1">>,<0.13862.92>}},
                  {'EXIT',<0.6373.92>,{shutdown,discarded}}]
    links: [<0.1638.0>]
    dictionary: [{{publish,<<"test">>},{allow,1602659501558}},
                  {{publish,
                       <<"/s2c/rpc_resp/iRemote2005100018517/1602659475">>},
                   {allow,1602659475414}},
                  {acl_keys_q,
                      {[{publish,
                            <<"/s2a/message/iSurpassApp/dryer/notification/thing.event.property.post/iRemote2005100024238/1">>},
                        {publish,<<"test">>},
                        {publish,<<"/s2i/report">>},
                        {publish,
                            <<"/s2a/message/iSurpassApp/washer/notification/thing.event.Online/iRemote2005100018517/0">>},
                        {publish,
                            <<"/s2a/message/iSurpassApp/washer/notification/thing.event.property.post/iRemote2005100018517/1">>},
                        {publish,
                            <<"/s2c/rpc_resp/iRemote2005100018517/1602659475">>},
                        {publish,
                            <<"/s2a/message/iSurpassApp/washer/notification/thing.event.Online/iRemote2005100018552/0">>},
                        {publish,
                            <<"/s2c/rpc_resp/iRemote2005100018552/1602659471">>},
                        {publish,
                            <<"/s2a/message/iSurpassApp/washer/notification/thing.event.Online/iRemote2005100018346/0">>},
                        {publish,
                            <<"/s2c/rpc_resp/iRemote2005100018346/1602659471">>},
                        {publish,
                            <<"/s2a/message/iSurpassApp/washer/notification/thing.event.property.post/iRemote2005100018445/1">>},
                        {publish,
                            <<"/s2a/message/iSurpassApp/washer/notification/thing.event.property.post/iRemote2005100018439/1">>}],
                       [{publish,
                            <<"/s2a/message/iSurpassApp/washer/notification/thing.event.property.post/iRemote2005100018420/1">>},
                        {publish,
                            <<"/s2a/async_reply/iSurpassApp/nbwasher-1602659447872">>},
                        {publish,
                            <<"/s2c/async_stateless/iRemote2005100018420/nbwasher-1602659447872-1-1">>},
                        {publish,
                            <<"/s2a/message/iSurpassApp/washer/notification/thing.event.property.post/iRemote2005100018370/1">>}]}},
                  {{publish,
                       <<"/s2c/async_stateless/iRemote2005100018420/nbwasher-1602659447872-1-1">>},
                   {allow,1602659449447}},
                  {{publish,
                       <<"/s2c/rpc_resp/iRemote2005100018346/1602659471">>},
                   {allow,1602659471067}},
                  {{publish,
                       <<"/s2a/message/iSurpassApp/washer/notification/thing.event.property.post/iRemote2005100018445/1">>},
                   {allow,1602659467235}},
                  {{publish,
                       <<"/s2a/message/iSurpassApp/washer/notification/thing.event.property.post/iRemote2005100018420/1">>},
                   {allow,1602659447663}},
                  {{publish,
                       <<"/s2a/message/iSurpassApp/dryer/notification/thing.event.property.post/iRemote2005100024238/1">>},
                   {allow,1602659502457}},
                  {{publish,
                       <<"/s2a/message/iSurpassApp/washer/notification/thing.event.Online/iRemote2005100018346/0">>},
                   {allow,1602659471079}},
                  {{publish,<<"/s2i/report">>},{allow,1602659475440}},
                  {'$logger_metadata$',
                      #{client_id => <<"server1">>,
                        peername => "192.168.200.13:32814"}},
                  {acl_cache_size,16},
                  {guid,{1602659505438267,65688773335266,8097}},
                  {force_shutdown_policy,
                      #{max_heap_size => 838860800,message_queue_len => 8000}},
                  {{publish,
                       <<"/s2a/message/iSurpassApp/washer/notification/thing.event.property.post/iRemote2005100018370/1">>},
                   {allow,1602659462078}},
                  {{publish,
                       <<"/s2a/async_reply/iSurpassApp/nbwasher-1602659447872">>},
                   {allow,1602659449417}},
                  {{publish,
                       <<"/s2a/message/iSurpassApp/washer/notification/thing.event.Online/iRemote2005100018517/0">>},
                   {allow,1602659475436}},
                  {rand_seed,
                      {#{bits => 58,jump => #Fun<rand.8.10897371>,
                         next => #Fun<rand.5.10897371>,type => exrop,
                         uniform => #Fun<rand.6.10897371>,
                         uniform_n => #Fun<rand.7.10897371>,
                         weak_low_bits => 1},
                       [173298407226321175|86703464878275481]}},
                  {incoming_bytes,22411},
                  {{publish,
                       <<"/s2a/message/iSurpassApp/washer/notification/thing.event.Online/iRemote2005100018552/0">>},
                   {allow,1602659471627}},
                  {{publish,
                       <<"/s2a/message/iSurpassApp/washer/notification/thing.event.property.post/iRemote2005100018517/1">>},
                   {allow,1602659475434}},
                  {{publish,
                       <<"/s2c/rpc_resp/iRemote2005100018552/1602659471">>},
                   {allow,1602659471618}},
                  {incoming_pubs,63},
                  {{publish,
                       <<"/s2a/message/iSurpassApp/washer/notification/thing.event.property.post/iRemote2005100018439/1">>},
                   {allow,1602659465310}}]
    trap_exit: true
    status: running
    heap_size: 10958
    stack_size: 27
    reductions: 23640601
  neighbours:

**Comment by tigercl** [comment]
@apolloyang2017 This is usually due to the fact that the received message does not conform to the protocol specification, but this log is indeed difficult to understand, and we are also ready to optimize it.
