### ISSUE TITLE
[emqx-auth-http] superuser authentication process

### ISSUE THREAD

**Issue by Joe-zhuo** [emqx/emqx#3776]
how to enable superuser authentication process in version 4.2.0 ?

**Comment by HJianBo** [comment]
Hi, @Joe-zhuo Just need to enable the supuser quert confs on `etc/plugins/emqx_auth_http.conf.

For example:

``` properties
## Value: URL
auth.http.super_req = http://127.0.0.1:8991/mqtt/superuser

## Value: post | get | put
auth.http.super_req.method = post

## It only works when method=pos
## Value: json | x-www-form-urlencoded
auth.http.super_req.content_type = x-www-form-urlencoded

## Variables:
##  - %u: username
##  - %c: clientid
##  - %a: ipaddress
##  - %r: protocol
##  - %P: password
##  - %p: sockport of server accepted
##  - %C: common name of client TLS cert
##  - %d: subject of client TLS cert
##
## Value: Params
auth.http.super_req.params = clientid=%c,username=%u

```

**Comment by Joe-zhuo** [comment]
I already enable query confs on etc/plugins/emqx_auth_http.conf like your example,but when mqtt client connect , emqx did not call auth.http.super_req url . only call two other auth.http.auth_req urls.  I see "The emqx-auth-http plugin disables super user authentication requests by default" in emqx v4.2.0 changes . Does it have any effect?

**Comment by Joe-zhuo** [comment]
ok,thanks!
