### ISSUE TITLE
[Bug] docker environment parse error if value contains '&'

### ISSUE THREAD

**Issue by PMExtra** [emqx/emqx#3781]
When I set `EMQX_DASHBOARD__DEFAULT_USER__PASSWORD=123&`
I got `dashboard.default_user.password = 123dashboard.default_user.password = public` in `etc/plugins/emqx_dashboard.conf` instead of expected `dashboard.default_user.password = 123&`
And the line will repeat one more time after every restart.

**Comment by zhanghongtong** [comment]
Hi, @PMExtra 
You need to set `EMQX_DASHBOARD__DEFAULT_USER__PASSWORD="123\&"`, like this:

```
docker run -d -e EMQX_DASHBOARD__DEFAULT_USER__PASSWORD="123\&" emqx/emqx:4.2.1 
```

**Comment by PMExtra** [comment]
Shall we support these special characters in environment variables?
I think most of productions will read environment as plain text, so what's the use case of that?

**Comment by zhanghongtong** [comment]
We use [docker-entrypoint.sh](https://github.com/emqx/emqx-rel/blob/master/deploy/docker/docker-entrypoint.sh) to update the configuration file in the container. In `/bin/sh`, the use of special symbols requires adding an escape character, so you need to add `\` before the `&`

**Comment by PMExtra** [comment]
I know that, but I can't understand why do you use `eval` here.

**Comment by PMExtra** [comment]
Sorry it's my fault, I think it may caused by `sed` instead `eval`.

**Comment by PMExtra** [comment]
I've read it.
In this case, the `&` may be a keyword in `sed` instead of `sh`.
I think the docker-entrypoint.sh has several security risks, such as set `EMQX_VARIALE=$(command)` to break the system, fetch sensitive data or escalate privilege. (Sometimes we permit some ops to configure environments in CI/CD platform, but we don't want they can get full access)
On the other hand, It can also cause damage inadvertently.

I want to make a pull request later that try to use bash [parameter expansion](https://www.gnu.org/software/bash/manual/html_node/Shell-Parameter-Expansion.html) to replace `eval`, and use perl to replace `sed` because perl [quotemeta](https://perldoc.perl.org/functions/quotemeta).
Do you approve it?

**Comment by zhanghongtong** [comment]
@PMExtra Yes, it is my honor, we welcome you to contribute code
