### ISSUE TITLE
Inconsistent display of emqx connections

### ISSUE THREAD

**Issue by sakufo** [emqx/emqx#3782]
**Please describe your problem in detail, if necessary, you can upload the log file through the attachment**:
emqx version: 3.2.2
Now I log in to the Dashboard, in Overview-->Connections Count is 30818
Then open Listeners-->mqtt:tcp 0.0.0.0:1883 and see Current Connections as 65368
I execute netstat -an | grep 1883 | wc -l on the operating system, and the value obtained is close to the value seen in the Listeners menu.

Please help answer what might be caused by this. thank you very much

**Comment by sakufo** [comment]
![1](https://user-images.githubusercontent.com/9942967/96666519-e0544b00-1389-11eb-9107-43ee561a4a93.jpg)
![2](https://user-images.githubusercontent.com/9942967/96666522-e1857800-1389-11eb-8079-1075c209db26.jpg)

**Comment by HJianBo** [comment]
Hi @sakufo Such a situation is possible. The `Connections Count` in the Overview page is the amount of `MQTT connected connections`, which means these clients had sent CONNECT packet and permitted access. But on the Listener page, This count is the amount of `established TCP connections`; They've only completed the TCP handshake.
