### ISSUE TITLE
Failed to start emqx-auth-pgsql plugin

### ISSUE THREAD

**Issue by yxlwfds** [emqx/emqx#3789]
emx版本4.2.1 非企业版
在启动pgsql验证插件时
emqx_auth_pgsql | EMQ X Authentication/ACL with PostgreSQL
-- | --

出了下面提示

{emqx_auth_pgsql, {bad_return, {{emqx_auth_pgsql_app,start,[normal,[]]}, {'EXIT', {{badmatch, {error, {shutdown, {failed_to_start_child,emqx_auth_pgsql, {shutdown, {failed_to_start_child,worker_sup, {shutdown,{failed_to_start_child,{worker,1},econnrefused}}}}}}}}, [{emqx_auth_pgsql_app,start,2, [{file, "/emqx-rel/_checkouts/emqx_auth_pgsql/src/emqx_auth_pgsql_app.erl"}, {line,37}]}, {application_master,start_it_old,4, [{file,"application_master.erl"},{line,277}]}]}}}}}

**Comment by wwhai** [comment]
The `econnrefused ` means pgsql server not allow connect,please check your *pgsql port* and *network firewall config*.

**Comment by leqii-com** [comment]
emqx_auth_pgsql 启动失败，解决了吗？跟你问题一样。

**Comment by zmstone** [comment]
`econnrefused` suggests that the endpoint server refuses to accept the connection.
likely the configured endpoint (server) is **NOT** listening on the port.

**Comment by leqii-com** [comment]
我的错误提示是：
{emqx_auth_pgsql, {bad_return, {{emqx_auth_pgsql_app,start,[normal,[]]}, {'EXIT', {{badmatch, {error, {shutdown, {failed_to_start_child,emqx_auth_pgsql, {shutdown, {failed_to_start_child,worker_sup, {shutdown, {failed_to_start_child, {worker,1}, invalid_authorization_specification}}}}}}}}, [{emqx_auth_pgsql_app,start,2, [{file,"emqx_auth_pgsql_app.erl"},{line,37}]}, {application_master,start_it_old,4, [{file,"application_master.erl"},{line,277}]}]}}}}}
@zmstone  can you help me ?

**Comment by zmstone** [comment]
seems to be the same issue as this:
https://github.com/emqx/emqx-auth-pgsql/issues/17

**Comment by zmstone** [comment]
I quote here:

```
I used to give access permission to my ip from the line follows in pg_hba.conf:
# IPv4 local connections:
host all all <my_ip_address>/32 thrust
Then I got the error I had posted, but I have changed it by:
# IPv4 local connections:`
host all all 127.0.0.1/32 md5
```

**Comment by zmstone** [comment]
maybe not the exact reason, but `invalid_authorization_specification` suggests it's a bad configuration on the server side.
I noticed the `thrust` typo too, maybe should be `trust` instead
