### ISSUE TITLE
What happens if the backend persistence crash when clients keep connecting and publishing?

### ISSUE THREAD

**Issue by DrmagicE** [emqx/emqx#3793]
Does the broker reject the connections and close all connected client until the backend persistence back online?
If the broker keep serving and store persistence data in memory, there will be a risk of getting "inconsistent session state".
How emq handle such problem?

**Comment by shaojun** [comment]
similar question for rule engine, if a rule of 'calling an outside web service' for each publish on a topic had been configured, with the publish contantly fired, once the web service is down, what is the behavior.

**Comment by turtleDeng** [comment]
If the backend resource is disconnected, the message will not be written to the backend resource, and the client can still publish and receive messages normally.

**Comment by shaojun** [comment]
@turtleDeng what is the potential impact? like the performance impact? does emqx keep trying to re-connect on following every publish request all the way?

**Comment by DrmagicE** [comment]
If a persistent client (cleanSession=false)  subscribes some topics and disconnects while the backend resource is down,  and restart EMQ.
Can it resume the session when reconnect to emq? It it can, it will lose the subscriptions and get an inconsistent session.

**Comment by DrmagicE** [comment]
Hi there, can someone answer these questions?  Thanks a lot. @turtleDeng
