### ISSUE TITLE
python paho.mqtt.client lose messages

### ISSUE THREAD

**Issue by qxqxq** [emqx/emqx#3794]
**Please describe your problem in detail, if necessary, you can upload the log file through the attachment**:
Environment
OS: Ubuntu 18.04
Erlang/OTP: 21
EMQ: 4.05

python paho.mqtt.client 

When a client receives a lot of messages and each on_message takes a lot of time to process, it will lose messages. What should be done? What I can think of now is using multiple client Shared subscriptions to reduce the number of messages received by a single client, or having on_message do fewer things to reduce the time spent on on_message. Is there any other good way to solve this? How many messages can a single client receive at the same time? Thank you very much!

**Comment by qxqxq** [comment]
If the on_message takes 1 second, can a single client only receive one message per second?

**Comment by tigercl** [comment]
@qxqxq Usually we recommend starting from the second aspect first, such as changing the message processing to non-blocking.

**Comment by qxqxq** [comment]
Python paho.mqtt.client on_message is blocking mode, right? Is there a non-blocking mode?

**Comment by qxqxq** [comment]
with self._callback_mutex:
            self._on_message = func
I see. Thank you very much.
