### ISSUE TITLE
Clustered emqx setup issue (Using helm install)

### ISSUE THREAD

**Issue by saurabhprakash** [emqx/emqx#3797]
**Environment**:

- EMQ X version (e.g. `emqx_ctl status`):  emqx:v4.1.1
- OS (e.g. `cat /etc/os-release`): Ubuntu 18

**What happened and what you expected to happen**: On starting up with 3 node cluster, node 1 is started, but on start of 2nd node always stopping with "emqx exit abnormally"

**Please find logs**:

> `broker.sys_interval=60s

cluster.k8s.address_type=hostname

cluster.k8s.address_type=hostname

node.max_ports=1048576

module.subscription.1.topic=clients/%c

cluster.k8s.suffix=svc.cluster.local

cluster.k8s.suffix=svc.cluster.local

listener.ws.external.idle_timeout=360s

listener.tcp.external.acceptors=64

log.level=debug

auth.http.super_req=http://backend:4040/portal/super/check

auth.http.auth_req.method=post

module.subscription=on

auth.http.auth_req.params=clientid=%c,username=%u,password=%P

auth.http.acl_req=http://backend:4040/portal/acl/check

allow_anonymous=false

listener.ssl.external.acceptors=32

node.process_limit=2097152

node.max_ets_tables=2097152

cluster.k8s.service_name=my-emqx-headless

cluster.k8s.service_name=my-emqx-headless

module.subscription.1.qos=2

cluster.discovery=k8s

cluster.discovery=k8s

listener.ws.external.acceptors=16

auth.http.super_req.method=post

cluster.k8s.app_name=my-emqx

cluster.k8s.app_name=my-emqx

auth.http.super_req.params=clientid=%c,username=%u,password=%P

auth.http.acl_req.method=get

cluster.k8s.apiserver=https://kubernetes.default.svc:443

cluster.k8s.apiserver=https://kubernetes.default.svc:443

auth.http.acl_req.params=access=%A,username=%u,password=%P,clientid=%c,topic=%t

cluster.k8s.namespace=default

cluster.k8s.namespace=default

auth.http.auth_req=http://backend:4040/portal/auth/check

EMQX_LOADED_PLUGINS="emqx_recon,emqx_retainer,emqx_management,emqx_dashboard,emqx_auth_http"

EMQ X Broker v4.1.1 is started successfully!

=====

===== LOGGING STARTED Mon Oct 26 12:18:01 UTC 2020

=====

Exec: /opt/emqx/erts-10.7.1/bin/erlexec -boot /opt/emqx/releases/v4.1.1/emqx -mode embedded -boot_var ERTS_LIB_DIR /opt/emqx/erts-10.7.1/../lib -mnesia dir "/opt/emqx/data/mnesia/my-emqx@my-emqx-1.my-emqx-headless.default.svc.cluster.local" -config /opt/emqx/data/configs/app.2020.10.26.12.18.02.config -args_file /opt/emqx/data/configs/vm.2020.10.26.12.18.02.args -vm_args /opt/emqx/data/configs/vm.2020.10.26.12.18.02.args -start_epmd false -epmd_module ekka_epmd -proto_dist ekka -- console

Root: /opt/emqx

/opt/emqx

2020-10-26 12:18:06.397 [info] event=server_setup_successfully driver=tcp socket="#Port<0.9>"

2020-10-26 12:18:06.398 [info] event=start

Starting emqx on node my-emqx@my-emqx-1.my-emqx-headless.default.svc.cluster.local

2020-10-26 12:18:06.408 [notice]     alarm_handler: {set,{system_memory_high_watermark,[]}}

['2020-10-26T12:18:13Z']:emqx start

['2020-10-26T12:18:13Z']:emqx not running, waiting for recovery in 20 seconds

['2020-10-26T12:18:18Z']:emqx not running, waiting for recovery in 15 seconds

['2020-10-26T12:18:23Z']:emqx not running, waiting for recovery in 10 seconds

['2020-10-26T12:18:28Z']:emqx not running, waiting for recovery in 5 seconds

['2020-10-26T12:18:33Z']:emqx not running, waiting for recovery in 0 seconds

=====

===== LOGGING STARTED Mon Oct 26 12:18:01 UTC 2020

=====

Exec: /opt/emqx/erts-10.7.1/bin/erlexec -boot /opt/emqx/releases/v4.1.1/emqx -mode embedded -boot_var ERTS_LIB_DIR /opt/emqx/erts-10.7.1/../lib -mnesia dir "/opt/emqx/data/mnesia/my-emqx@my-emqx-1.my-emqx-headless.default.svc.cluster.local" -config /opt/emqx/data/configs/app.2020.10.26.12.18.02.config -args_file /opt/emqx/data/configs/vm.2020.10.26.12.18.02.args -vm_args /opt/emqx/data/configs/vm.2020.10.26.12.18.02.args -start_epmd false -epmd_module ekka_epmd -proto_dist ekka -- console

Root: /opt/emqx

/opt/emqx

2020-10-26 12:18:06.397 [info] event=server_setup_successfully driver=tcp socket="#Port<0.9>"

2020-10-26 12:18:06.398 [info] event=start

Starting emqx on node my-emqx@my-emqx-1.my-emqx-headless.default.svc.cluster.local

2020-10-26 12:18:06.408 [notice]     alarm_handler: {set,{system_memory_high_watermark,[]}}

['2020-10-26T12:18:38Z']:emqx exit abnormally`

**Comment by tigercl** [comment]
@saurabhprakash Please try to start with `./emqx console` and provide us with the output log of the console.

**Comment by saurabhprakash** [comment]
Output of "./emqx console"
`/opt/emqx $ emqx console
Exec: /opt/emqx/erts-10.7.1/bin/erlexec -boot /opt/emqx/releases/v4.1.1/emqx -mode embedded -boot_var ERTS_LIB_DIR /opt/emqx/erts-10.7.1/../lib -mnesia dir "/opt/emqx/data/mnesia/my-emqx@my-emqx-0.my-emqx-headless.default.svc.cluster.local" -config /opt/emqx/data/configs/app.2020.11.05.08.05.33.config -args_file /opt/emqx/data/configs/vm.2020.11.05.08.05.33.args -vm_args /opt/emqx/data/configs/vm.2020.11.05.08.05.33.args -start_epmd false -epmd_module ekka_epmd -proto_dist ekka -- console
Root: /opt/emqx
/opt/emqx
Protocol 'ekka': register/listen error: eaddrinuse`

**Comment by tigercl** [comment]
@saurabhprakash Sorry for not replying to you in time, do you start multiple nodes on one host?

**Comment by xianchaoZou** [comment]
I also encountered such a problem！！！！  

This problem occurs if all three nodes are deleted pod.

Environment variable BINDIR is not set
Environment variable BINDIR is not set


=====
===== LOGGING STARTED Thu Dec  9 06:19:17 UTC 2021
=====
Exec: /opt/emqx/erts-10.5.6/bin/erlexec -boot /opt/emqx/releases/v4.0.7/emqx -mode embedded -boot_var ERTS_LIB_DIR /opt/emqx/erts-10.5.6/../lib -mnesia dir "/opt/emqx/data/mnesia/iotemqx@iotemqx-iot-emqx-1.iotemqx-iot-emqx-headless.iot.svc.cluster.local" -config /opt/emqx/data/configs/app.2021.12.09.06.19.18.config -args_file /opt/emqx/data/configs/vm.2021.12.09.06.19.18.args -vm_args /opt/emqx/data/configs/vm.2021.12.09.06.19.18.args -start_epmd false -epmd_module ekka_epmd -proto_dist ekka -- console
Root: /opt/emqx
/opt/emqx
Starting emqx on node iotemqx@iotemqx-iot-emqx-1.iotemqx-iot-emqx-headless.iot.svc.cluster.local
['2021-12-09T06:19:29Z']:emqx start
['2021-12-09T06:19:29Z']:emqx not running, waiting for recovery in 20 seconds
['2021-12-09T06:19:34Z']:emqx not running, waiting for recovery in 15 seconds
['2021-12-09T06:19:39Z']:emqx not running, waiting for recovery in 10 seconds
['2021-12-09T06:19:44Z']:emqx not running, waiting for recovery in 5 seconds
['2021-12-09T06:19:49Z']:emqx not running, waiting for recovery in 0 seconds
=====
===== LOGGING STARTED Thu Dec  9 06:19:17 UTC 2021
=====
Exec: /opt/emqx/erts-10.5.6/bin/erlexec -boot /opt/emqx/releases/v4.0.7/emqx -mode embedded -boot_var ERTS_LIB_DIR /opt/emqx/erts-10.5.6/../lib -mnesia dir "/opt/emqx/data/mnesia/iotemqx@iotemqx-iot-emqx-1.iotemqx-iot-emqx-headless.iot.svc.cluster.local" -config /opt/emqx/data/configs/app.2021.12.09.06.19.18.config -args_file /opt/emqx/data/configs/vm.2021.12.09.06.19.18.args -vm_args /opt/emqx/data/configs/vm.2021.12.09.06.19.18.args -start_epmd false -epmd_module ekka_epmd -proto_dist ekka -- console
Root: /opt/emqx
/opt/emqx
Starting emqx on node iotemqx@iotemqx-iot-emqx-1.iotemqx-iot-emqx-headless.iot.svc.cluster.local
['2021-12-09T06:19:54Z']:emqx exit abnormally
