### ISSUE TITLE
cluster:node_down

### ISSUE THREAD

**Issue by moziie** [emqx/emqx#3798]
problem:
When I create a cluster according to the documentation,
https://docs.emqx.net/broker/latest/cn/getting-started/cluster.html
use "emqx_ctl cluster join emqx@127.21.0.8"
give this: Failed to join the cluster: {node_down,'emq@127.21.0.8'}
open port: 4370 (ekka model) and cookie is same. 
please help me,ths
**Environment**:
- EMQ X version (e.g. `emqx_ctl status`): 
**1/Node 'emq@127.21.0.8' is started
     emqx 4.2.0 is running
2/Node 'emq@127.21.0.3' is started
    emqx 4.2.0 is running**
- Hardware configuration (e.g. `lscpu`):
**Architecture:        x86_64
CPU op-mode(s):      32-bit, 64-bit
Byte Order:          Little Endian
CPU(s):              8
On-line CPU(s) list: 0-7
Thread(s) per core:  1
Core(s) per socket:  8
Socket(s):           1
NUMA node(s):        1
Vendor ID:           AuthenticAMD
CPU family:          23
Model:               49
Model name:          AMD EPYC 7K62 48-Core Processor
Stepping:            0
CPU MHz:             2595.124
BogoMIPS:            5190.24
Hypervisor vendor:   KVM
Virtualization type: full
L1d cache:           32K
L1i cache:           32K
L2 cache:            4096K
L3 cache:            16384K
NUMA node0 CPU(s):   0-7
Flags:               fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm rep_good nopl cpuid extd_apicid tsc_known_freq pni pclmulqdq ssse3 fma cx16 sse4_1 sse4_2 x2apic movbe popcnt aes xsave avx f16c rdrand hypervisor lahf_lm cmp_legacy cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw topoext ibpb vmmcall fsgsbase bmi1 avx2 smep bmi2 rdseed adx smap clflushopt sha_ni xsaveopt xsavec xgetbv1 arat**
- OS (e.g. `cat /etc/os-release`):
NAME="CentOS Linux"
VERSION="8 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="8"
PLATFORM_ID="platform:el8"
PRETTY_NAME="CentOS Linux 8 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:8"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-8"
CENTOS_MANTISBT_PROJECT_VERSION="8"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="8"
- Kernel (e.g. `uname -a`):
Linux VM-0-8-centos 4.18.0-80.el8.x86_64 #1 SMP Tue Jun 4 09:19:46 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
- Erlang/OTP version (in case you build emqx from source code): 
Erlang (SMP,ASYNC_THREADS,HIPE) (BEAM) emulator version 10.4.4

**Comment by zmstone** [comment]
` Failed to join the cluster: {node_down,'emq@127.21.0.8'}` ?
there is a `x` missing in the node name

**Comment by moziie** [comment]
update the emqx.conf  node.name = emqx@127.21.0.8 and then restart emqx.
sudo emqx_ctl status:
1/Node 'emqx@127.21.0.3' is started
emqx 4.2.0 is running
2/Node 'emqx@127.21.0.8' is started
emqx 4.2.0 is running
excute this:-sudo emqx_ctl cluster join emqx@127.21.0.8
also:Failed to join the cluster: {node_down,'emqx@127.21.0.8'}
please help me^^,how can i fix this.

**Comment by moziie** [comment]
@zmstone

**Comment by HJianBo** [comment]
@moziie It looks like you have the correct configuration. You can try the following to check your machine status:
  - Use `telnet` to check if the peer port 4370 is accessible.
  - Check the logs to see if there is any relevant log output.
  - Run `netstat -natlp|grep LISTEN` to see that you are listening on the port (or paste it here)

**Comment by moziie** [comment]
> @moziie It looks like you have the correct configuration. You can try the following to check your machine status:
> 
> * Use `telnet` to check if the peer port 4370 is accessible.
> * Check the logs to see if there is any relevant log output.
> * Run `netstat -natlp|grep LISTEN` to see that you are listening on the port (or paste it here)

1/port 4370 is open.
2/logs:name<emqx.log.1> info this:----
2020-10-28 08:37:02.390 [error] 
** Cannot get connection id for node 'emqx@127.21.0.3'
3/netstat -natlp|grep LISTEN
**127.21.0.3:**
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      457/sshd            
tcp        0      0 0.0.0.0:15672           0.0.0.0:*               LISTEN      28055/beam.smp      
tcp        0      0 0.0.0.0:6040            0.0.0.0:*               LISTEN      16016/taosd         
tcp        0      0 0.0.0.0:23000           0.0.0.0:*               LISTEN      26890/fdfs_storaged 
tcp        0      0 0.0.0.0:6041            0.0.0.0:*               LISTEN      16016/taosd         
tcp        0      0 0.0.0.0:5370            0.0.0.0:*               LISTEN      29620/beam.smp      
tcp        0      0 0.0.0.0:1883            0.0.0.0:*               LISTEN      29620/beam.smp      
tcp        0      0 0.0.0.0:18083           0.0.0.0:*               LISTEN      29620/beam.smp      
tcp        0      0 0.0.0.0:25672           0.0.0.0:*               LISTEN      28055/beam.smp      
tcp        0      0 0.0.0.0:22122           0.0.0.0:*               LISTEN      21924/fdfs_trackerd 
tcp        0      0 127.0.0.1:11883         0.0.0.0:*               LISTEN      29620/beam.smp      
tcp        0      0 0.0.0.0:6030            0.0.0.0:*               LISTEN      16016/taosd         
tcp        0      0 0.0.0.0:80              0.0.0.0:*               LISTEN      28706/nginx: master 
tcp        0      0 0.0.0.0:8081            0.0.0.0:*               LISTEN      29620/beam.smp      
tcp        0      0 0.0.0.0:4369            0.0.0.0:*               LISTEN      26048/epmd          
tcp        0      0 0.0.0.0:4370            0.0.0.0:*               LISTEN      29620/beam.smp      
tcp        0      0 0.0.0.0:8883            0.0.0.0:*               LISTEN      29620/beam.smp      
tcp        0      0 0.0.0.0:8083            0.0.0.0:*               LISTEN      29620/beam.smp      
tcp        0      0 0.0.0.0:6035            0.0.0.0:*               LISTEN      16016/taosd         
tcp        0      0 0.0.0.0:8084            0.0.0.0:*               LISTEN      29620/beam.smp      
tcp6       0      0 :::3000                 :::*                    LISTEN      31815/grafana-serve 
tcp6       0      0 :::5672                 :::*                    LISTEN      28055/beam.smp      
tcp6       0      0 :::4369                 :::*                    LISTEN      26048/epmd          
**127.21.0.8:**
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      23488/sshd          
tcp        0      0 0.0.0.0:15672           0.0.0.0:*               LISTEN      741419/beam.smp     
tcp        0      0 0.0.0.0:23000           0.0.0.0:*               LISTEN      31111/fdfs_storaged 
tcp        0      0 0.0.0.0:3001            0.0.0.0:*               LISTEN      3804233/nginx: mast 
tcp        0      0 0.0.0.0:5370            0.0.0.0:*               LISTEN      4086442/beam.smp    
tcp        0      0 0.0.0.0:1883            0.0.0.0:*               LISTEN      4086442/beam.smp    
tcp        0      0 0.0.0.0:18083           0.0.0.0:*               LISTEN      4086442/beam.smp    
tcp        0      0 0.0.0.0:25672           0.0.0.0:*               LISTEN      741419/beam.smp     
tcp        0      0 0.0.0.0:22122           0.0.0.0:*               LISTEN      31088/fdfs_trackerd 
tcp        0      0 127.0.0.1:11883         0.0.0.0:*               LISTEN      4086442/beam.smp    
tcp        0      0 0.0.0.0:6379            0.0.0.0:*               LISTEN      420482/redis-server 
tcp        0      0 0.0.0.0:80              0.0.0.0:*               LISTEN      3804233/nginx: mast 
tcp        0      0 0.0.0.0:8081            0.0.0.0:*               LISTEN      4086442/beam.smp    
tcp        0      0 0.0.0.0:4369            0.0.0.0:*               LISTEN      741659/epmd         
tcp        0      0 0.0.0.0:4370            0.0.0.0:*               LISTEN      4086442/beam.smp    
tcp        0      0 0.0.0.0:8883            0.0.0.0:*               LISTEN      4086442/beam.smp    
tcp        0      0 0.0.0.0:8083            0.0.0.0:*               LISTEN      4086442/beam.smp    
tcp        0      0 0.0.0.0:8084            0.0.0.0:*               LISTEN      4086442/beam.smp    
tcp6       0      0 127.0.0.1:6005          :::*                    LISTEN      4089442/java        
tcp6       0      0 :::5050                 :::*                    LISTEN      3815254/java        
tcp6       0      0 127.0.0.1:7005          :::*                    LISTEN      3593080/java        
tcp6       0      0 :::7070                 :::*                    LISTEN      3593080/java        
tcp6       0      0 :::9091                 :::*                    LISTEN      4072356/java        
tcp6       0      0 :::8100                 :::*                    LISTEN      3559623/java        
tcp6       0      0 :::8200                 :::*                    LISTEN      3559737/java        
tcp6       0      0 :::5672                 :::*                    LISTEN      741419/beam.smp     
tcp6       0      0 :::3306                 :::*                    LISTEN      1974618/mysqld      
tcp6       0      0 :::6379                 :::*                    LISTEN      420482/redis-server 
tcp6       0      0 :::8300                 :::*                    LISTEN      3559819/java        
tcp6       0      0 :::6060                 :::*                    LISTEN      4089442/java        
tcp6       0      0 127.0.0.1:5005          :::*                    LISTEN      3815254/java        
tcp6       0      0 :::8400                 :::*                    LISTEN      3559973/java        
tcp6       0      0 :::4369                 :::*                    LISTEN      741659/epmd         
tcp6       0      0 :::8500                 :::*                    LISTEN      3810127/java        
so why this prompt appears:"Cannot get connection id for node 'emqx@127.21.0.3"
and where is the problem, ths

**Comment by zmstone** [comment]
ah, ok, it's a loopback address, meaning you are running two nodes in the same host?
in this case, you'll have to assign different node names (with a number suffix) for them
e.g. emqx1@127... and emqx2@127...
without a number suffix they will both try to listen on port 4370

**Comment by zmstone** [comment]
hm, ok, it seems they are two different hosts after all? 
maybe don't use loopback address.

**Comment by moziie** [comment]
> hm, ok, it seems they are two different hosts after all?
> maybe don't use loopback address.

I am using two hosts, one of the external network address is 49.112.47.96, hostname: VM-0-3-centos, the internal network address is 127.21.0.3, the other external network address is 49.112.118.98, hostname: VM-0-8 -centos, intranet address 127.21.0.8;
When I use emqx@49.112.47.96 and emqx@49.112.118.98 to configure node.name, emqx cannot be started successfully, I can start emqx by changing the address to the intranet address, but I cannot join the cluster, but these are two server instances.
emmm...how to modify the loopback address?I am not sure how to deal with this problem, please give me specific steps. Thank you

**Comment by zmstone** [comment]
Communication between external IPs are probably strictly prohibited by firewalls etc.
And we do not recommend exposing erlang distribution to the internet.
Private network IPs are `10.`, `172.`, and `192.168.`, see: https://en.wikipedia.org/wiki/Private_network.

Not sure how your VMs and network are provisioned, you should probably consult your network admin for this.

**Comment by moziie** [comment]
oh,thanks,I made a mistake,the private network IPs I write wrong, now it`s ok.thanks a lot!
