### ISSUE TITLE
Same inputs name for login and password on authorization page

### ISSUE THREAD

**Issue by reverse-engineering-dev** [emqx/emqx#3799]
hi, boths login and password fields are same name: input.el-input__inner
![image](https://user-images.githubusercontent.com/72131351/97316131-13a74600-1872-11eb-8dbe-af1618d56de5.png)
![image](https://user-images.githubusercontent.com/72131351/97316311-43eee480-1872-11eb-846f-98f542029f6e.png)
I cannot use software for autocomplete because input fields don't have name. 
![image](https://user-images.githubusercontent.com/72131351/97317034-122a4d80-1873-11eb-9faf-5494ae56b842.png)

**Comment by ysfscream** [comment]
Do you mean to add a name attribute to the input?

**Comment by reverse-engineering-dev** [comment]
> 
> 
> Do you mean to add a name attribute to the input?

Yes
