### ISSUE TITLE
Third-party system combined with emqx development

### ISSUE THREAD

**Issue by bgzyy** [emqx/emqx#3800]
## 第三方系统结合 Emqx 开发
1. 通过第三方系统结合 Emqx 开发，第三方系统调用 Broker 的 API 完成业务开发，当 Edge 桥接到 Broker 且 Edge 没有公网，如何通过第三方系统去管理 Edge 上的设备（强制设备下线），在 Edge 端创建规则、资源等

**Comment by tigercl** [comment]
@bgzyy It is currently not directly supported, unless you deploy an HTTP server that is on the same LAN as the edge and can access the public network to forward the received HTTP requests to the edge.

**Comment by bgzyy** [comment]
好的，谢谢！
