### ISSUE TITLE
Configurable (or larger) certificate depth on SSL.

### ISSUE THREAD

**Issue by zhengyupan** [emqx/emqx#3805]
**What would you like to be added/modified**:
configurable max depth of a X.509 certificate.
**Why is this needed**:
 In some cases, between the RootCA and the peer certificate there are multiple level of intermediate CAs, which results in a certificate chain. 
The current (4.2.2) and earlier EMQ X releases support a limited and fixed depth value. When the certificate chain is long, the SSL handshake ends up with this error: 

```
reason: {ssl_error,
{tls_alert,
{handshake_failure,
"TLS server: In state certify at ssl_handshake.erl:1783 generated SERVER ALERT: Fatal - Handshake Failure\n {bad_cert,max_path_length_reached}"}}}   
```

**Comment by zmstone** [comment]
```
 allowed_cert_chain_length() = integer()
Maximum number of non-self-issued intermediate certificates that can follow the peer certificate in a valid certification path. So, if depth is 0 the PEER must be signed by the trusted ROOT-CA directly; if 1 the path can be PEER, CA, ROOT-CA; if 2 the path can be PEER, CA, CA, ROOT-CA, and so on. The default value is 1.
```

**Comment by zmstone** [comment]
We can maybe increase this to 5.
Not sure how useful it is to make it configurable.

**Comment by terry-xiaoyu** [comment]
@zmstone Agree, That's also what I suggested. If so, I will hard code the value to 5 in the emqx.schema.

**Comment by HJianBo** [comment]
Hi guys, we have introduced this feature in 4.2.4. We're working on the release package, so you can try it later
