### ISSUE TITLE
Can I enable or disable acl dynamically

### ISSUE THREAD

**Issue by supermareo** [emqx/emqx#3809]
**Please describe your problem in detail, if necessary, you can upload the log file through the attachment**:
At present, I use emqx_auth_redis online, and I'm going to enable redis acl in productin environment. If there is a problem, I hope to close ACL dynamically. Is that supported in  v4.2.2?

**Comment by tigercl** [comment]
@supermareo Sorry, it is not currently supported. We will consider implementing it.

**Comment by supermareo** [comment]
> @supermareo Sorry, it is not currently supported. We will consider implementing it.

OK.Thanks.
