### ISSUE TITLE
EMQX HTTP API and MQTT performance comparsion

### ISSUE THREAD

**Issue by gbaranski** [emqx/emqx#3810]
Hello, have anyone compared performance of [EMQXs HTTP API](https://docs.emqx.io/broker/latest/en/advanced/http-api.html#endpoint-telemetry) and with normal MQTT connection with EMQX? I would like to just publish messages but I got no idea which protocol should I use.

Thanks

**Comment by tigercl** [comment]
@gbaranski It is recommended to use MQTT connection, the current performance of HTTP API is not suitable for frequent requests, we are preparing to optimize it.

**Comment by gbaranski** [comment]
Thank u very much :) , closing
