### ISSUE TITLE
Storage mounting problem

### ISSUE THREAD

**Issue by Aaron-23** [emqx/emqx#3811]
**Environment**:

- EMQ X version (e.g. `emqx_ctl status`): 4.0
- Hardware configuration (e.g. `lscpu`):
- OS (e.g. `cat /etc/os-release`): docker
- Kernel (e.g. `uname -a`): 3.10
- Erlang/OTP version (in case you build emqx from source code): 
- Others:

When using docker to deploy emqx, the storage cannot be started normally when the storage is mounted

The docker command I used is as follows
```bash
docker run -d --name emqx -p 1883:1883 -p 8083:8083 -p 8883:8883 -p 8084:8084 -p 18083:18083 emqx/emqx:v4.0.0
```
Without mounting the storage, everything is normal. When I mounted the following storage, the following error occurred

![image](https://user-images.githubusercontent.com/50609288/98062013-28926380-1e88-11eb-8010-04eb1b1a3ae8.png)

```bash
$ kubectl logs -f  361d504f62ead99aae5fe75ee040d8d6-deployment-78dfcfc5c5-6gsn6 -n e58dcfb46d72493fbabd16dfaa7676d4
ls: /opt/emqx/etc/plugins: No such file or directory
ls: /opt/emqx/etc/plugins: No such file or directory
ls: /opt/emqx/etc/plugins: No such file or directory
ls: /opt/emqx/etc/plugins: No such file or directory
ls: /opt/emqx/etc/plugins: No such file or directory
ls: /opt/emqx/etc/plugins: No such file or directory
ls: /opt/emqx/etc/plugins: No such file or directory
ls: /opt/emqx/etc/plugins: No such file or directory
ls: /opt/emqx/etc/plugins: No such file or directory
ls: /opt/emqx/etc/plugins: No such file or directory
ls: /opt/emqx/etc/plugins: No such file or directory
ls: /opt/emqx/etc/plugins: No such file or directory
ls: /opt/emqx/etc/plugins: No such file or directory
ls: /opt/emqx/etc/plugins: No such file or directory
ls: /opt/emqx/etc/plugins: No such file or directory
vm.args needs to have a -setcookie parameter.
ls: /opt/emqx/log/erlang.log.*: No such file or directory
tail: invalid number '-2'
```

**Comment by zhanghongtong** [comment]
Hi, @Aaron-23 
We provide a helm chart to quickly deploy emqx on kubernetes, we recommend that you use our [helm chart](https://github.com/emqx/emqx-rel/tree/master/deploy/charts/emqx) to deploy

**Comment by Aaron-23** [comment]
@zhanghongtong I want to deploy on the paas platform. Helm cannot be used on the platform. Is there any other storage mounting solution?

**Comment by zhanghongtong** [comment]
@Aaron-23 
First of all, the volume mount will clear the files in the container directory, so you should not mount the `/opt/emqx/lib` directory and the `/opt/emqx/etc` directory.
About data you can mount `/opt/emqx/data/mnesia` instead of the `/opt/emqx/data` directory

**Comment by zhanghongtong** [comment]
@Aaron-23 
Most cloud vendor platforms support the helm chart in some ways. It is recommended that you consult your cloud provider

**Comment by Aaron-23** [comment]
@zhanghongtong Okay, when I only mount the `/opt/emqx/data/mnesia` data directory, the problem is solved, thank you very much!
