### ISSUE TITLE
Auth passowrd can't contain '$' symbol,but can endwith '$'

### ISSUE THREAD

**Issue by sunmenglin** [emqx/emqx#3812]
**Environment**:

- EMQ X version (e.g. `emqx_ctl status`):   emqx 4.2.1
- Hardware configuration (e.g. `lscpu`):  x86_64 32-bit, 64-bit
- OS (e.g. `cat /etc/os-release`):  CentOS Linux 7 (Core)
- Kernel (e.g. `uname -a`):   3.10.0-1127.18.2.el7.x86_64
- Erlang/OTP version (in case you build emqx from source code): 
- Others:

**What happened and what you expected to happen**:
   I enabled emqx_auth_mysql, and set auth.mysql.password_hash = sha256. then I sha256 my passowrd of contained '$' symbol. I connect to server:1881, the client occour error: "Error: Connection refused: Not authorized", and log error: "Client mqttx_e2d253a4 (Username: 'emqx') login failed for not_authorized"

**How to reproduce it (as minimally and precisely as possible)**:
```
# echo -n "123456$78" | sha256sum
07ba38d7a9affba269a613da6d99a7ffa4d128ce38f5e24ee5a7383b796b58b2  -
```
and update mqtt_user table in mysql. connect the server, occur error.
```
# echo -n "123456$" | sha256sum 
018e0113eeaf80aea2fe2a277cdc2d0823b065af0fdd23bc73c14e86a8991c9f  -
```
and update mqtt_user table in mysql. connect the server, success.

**Anything else we need to know?**:

**Comment by tigercl** [comment]
@sunmenglin Sorry for late reply, I think it is indeed a problem, we will fix it as soon as possible, you can see this fix as early as 4.2.3.

**Comment by tigercl** [comment]
@sunmenglin Hi, I don’t know if your problem has been solved, but after my test just now, I think you should use single quotes instead of double quotes when the text you need to encrypt contains $ character. In fact, this will get two different results, like this:

```
# echo -n "123456$78" | sha256sum
8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92  -
# echo -n '123456$78' | sha256sum
5613d196d2c47fd114f343293f7a3da540c30cdff1a19ec47b96c2223b9743ed  -
```

**Comment by sunmenglin** [comment]
> @sunmenglin Hi, I don’t know if your problem has been solved, but after my test just now, I think you should use single quotes instead of double quotes when the text you need to encrypt contains $ character. Because this will get two different results, like this:
> 
> ```
> # echo -n "123456$78" | sha256sum
> 8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92  -
> # echo -n '123456$78' | sha256sum
> 5613d196d2c47fd114f343293f7a3da540c30cdff1a19ec47b96c2223b9743ed  -
> ```

Thank you very much! It is my neglect that the different of single quotes and double quotes in bash shell. so sorry.
