### ISSUE TITLE
ACL not working when connect with CoAP 

### ISSUE THREAD

**Issue by AylaAsia-GaryJin** [emqx/emqx#3813]
**Please describe your problem in detail, if necessary, you can upload the log file through the attachment**:
EMQ X version: 4.0.5 (20201110 even latest version 4.2.2)

`emqx.conf`:
```
acl_nomatch = deny
```

acl.conf:
```
%% v3 simple mode
%% device subscribe rule
{allow, {user, "V3/OB"}, subscribe, ["V3/DOWN/OB/%c"]}.
{allow, {user, "V3/PT"}, subscribe, ["V3/DOWN/%c"]}.
%% device publish rule
{allow, {user, "V3/OB"}, publish, ["V3/UP/OB/%c"]}.
{allow, {user, "V3/PT"}, publish, ["V3/UP/%c"]}.
```
Which means device connect with `V3/PT` only could pub topic `V3/UP/{clientId}` and sub topic `V3/DOWN/{clientId}`

Enable CoAP plugin and expose 5683/udp. My pub / sub command (through `libcoap`) are:
* publish command:
```
./coap-client -m put -e 1234  "coap://127.0.0.1/mqtt/topic1?c=AC0050W000000595&u=V3/PT&p=123456"
```
* subscribe command:
```
./coap-client -m get -s 10000 "coap://127.0.0.1/mqtt/topic1?c=AC0050W000000595&u=V3/PT&p=123456"
```
Success got expected message which is not allowed by acl.conf, seems acl not working which is worked when connect with mqtt.

How should I do to make acl.conf work?

**Comment by AylaAsia-GaryJin** [comment]
There is another question: two device with same connecting information could connect in same time when one through mqtt another through CoAP, but they can't connect in same time when through mqtt, any solutions to make these situation same result? Thanks.

**Comment by AylaAsia-GaryJin** [comment]
Rate limit is not working either.

**Comment by HJianBo** [comment]
Sorry @AylaAsia-GaryJin In the current version (Version 4.2.x and below), the `emqx-coap` plugin doesn't compliance with ACL rules.  We will try to implement it on the next version

**Comment by AylaAsia-GaryJin** [comment]
@HJianBo Alright, waiting for your good news.

**Comment by HJianBo** [comment]
We have tagged 4.3-alpha.1, which contains the fix. The official release will probably come in 1-2 months.
