### ISSUE TITLE
The java version set ops to 2 does not take effect

### ISSUE THREAD

**Issue by luo199393** [emqx/emqx#3815]
Hello: version 4.0 and 4.2.2 open source version of the broker, currently set ops in java, the ops value in the query result of the subscription information API (GET /api/v4/subscriptions) is 1.

你好：版本4.0和4.2.2开源版本broker，目前在java设置ops为，订阅信息API（GET /api/v4/subscriptions）查询结果中ops值为1。

**Comment by tigercl** [comment]
@luo199393 Sorry for not replying to you in time, have you modified the `max_qos_allowed` configuration item in the `emqx.conf`?

**Comment by luo199393** [comment]
> @ luo199393对不起，您未及时答复您，您是否修改了中的`max_qos_allowed`配置项`emqx.conf`？

你好，下面是我修改的配置文件emqx.conf的内容
1、编辑文件vi /etc/emqx/emqx.conf

2、搜索内容node.name的配置，配置为当前ip地址
node.name = emqx1@192.168.8.58

3、搜索内容cluster.discovery，配置集群模式，这里使用静态模式
cluster.discovery = static

4、配置多节点地址cluster.static.seeds
注：emqx1@192.168.8.58需要和node.name的值相同
cluster.static.seeds = emqx1@192.168.8.58,emqx2@192.168.8.57

如你上面所说，max_qos_allowed值没有修改过，默认值是2

**Comment by luo199393** [comment]
> @ luo199393对不起，您未及时答复您，您是否修改了中的`max_qos_allowed`配置项`emqx.conf`？

Hello, the following is the content of the configuration file emqx.conf I modified
1. Edit the file vi /etc/emqx/emqx.conf

2. Search the configuration of the content node.name and configure it as the current ip address
node.name = emqx1@192.168.8.58

3. Search for the content cluster.discovery, configure the extended mode, and use the static mode here
cluster.discovery = static

4. Configure multi-cluster address cluster.static.seeds Note: emqx1@192.168.8.58 needs to be the same value as node.name
cluster.static.seeds = emqx1 @ 192.168.8.58, emqx2 @ 192.168.8.57

As you said above, the max_qos_allowed value has not been modified, the default value is 2
