### ISSUE TITLE
QoS persistence on disk

### ISSUE THREAD

**Issue by drasko** [emqx/emqx#3817]
**Please describe your problem in detail, if necessary, you can upload the log file through the attachment**:
Hi all - is [this](https://github.com/emqx/emqx/issues/1481#issuecomment-424848360) still the case, or something changed in the meantime?

VerneMQ uses LevelDB for QoS persistnace. Can QoS messages be persisted on a disk with EMQX and what underlying technology do you use?

**Comment by zmstone** [comment]
Hi @drasko 
Yes, it is still the case, only available in enterprise edition.
It is in our roadmap to provide a fully featured message storage engine for open source edition, but it's hard to give an ETA at the current stage.

**Comment by k32** [comment]
This feature has been merged to 5.0 branch.

**Comment by drasko** [comment]
@k32 if I understood well, now this feature is open-sourced?

**Comment by k32** [comment]
Mnesia backend for message persistence is now opensource in EMQX 5.0 beta.

**Comment by drasko** [comment]
AFAIk, Mnesia is in RAM. This issue is about on-disk persistence. Is this enabled in open-source version or not?

**Comment by k32** [comment]
Mnesia itself has multiple backends. We support RAM, disk_copies and RocksDB.
