### ISSUE TITLE
 I'd like to inquire. Regarding EMQX SYS Topic

### ISSUE THREAD

**Issue by pcsgod** [emqx/emqx#3825]
Nice to meet you.

We are developing a program using EMQX service.

I'm using SYS Topic to determine the user's connection status.

Use EMQX 2EA as a cluster.

 

The connection status of the user connected to EMQX Node 1

I want to know in the node of EMQX number 2. 

Isn't there any way to use SYS Topic?

**Comment by HJianBo** [comment]
Yes, in the Node 2, you can get all the connections status on Node 1. Just subscribe the $SYS topic on Node2. see: https://docs.emqx.io/broker/latest/en/advanced/system-topic.html#client-online-and-offline-events

BTW, The permission for subscribing to a  $SYS topic has defined in a group of ACL rules. see: https://docs.emqx.io/broker/latest/en/advanced/acl-file.html#acl-file

**Comment by pcsgod** [comment]
Thank you for your reply.

What I want to do is...

If you do a 1-node/2-node subscription in WAS 1, and then a 1-node/2-node subscription in WAS 2, 

Because Client subscribe to both sides of the was at the end, they are processed simultaneously in two was.

It should not be processed at the same time.

Is there any way?

**Comment by zainsyedz** [comment]
Are the messages in SYS topic for client connected/disconnected retained messages and what is qos for them?
