### ISSUE TITLE
Questions in a cluster environment.

### ISSUE THREAD

**Issue by jiny28** [emqx/emqx#3826]
How to subscribe to all nodes? If you only subscribe to one node, what to do if the node goes down.

**Comment by HJianBo** [comment]
Hi @jiny28 In a typical scenario, the front of the EMQ X cluster is proxied from having a load-balanced server:

```
                   +----------+           / ------- [ emqx 1 ]
[ Client ] ----->  |  HAProxy |  --------+--------  [ emqx 2 ]
                   +----------+           \ ------- [ emqx 3 ]
```

So, your client just need connected to the Proxy Server. Whatever the reason for the broken link, just reconnect.
