### ISSUE TITLE
get server assigned client_id on the client side

### ISSUE THREAD

**Issue by mlmarius** [emqx/emqx#3829]
**Please describe your problem in detail, if necessary, you can upload the log file through the attachment**:
Hi! I'm trying to build some RPC functionality in my system using EMQX but in order to do that, I figure that I require that the client making the RPC request knows it's server assigned client_id so that it can push that with the RPC payload so that the other side knows where to send the response. How can I get the server assigned client_id on my client? Using paho-mqtt on Python. Thanks!

**Comment by tigercl** [comment]
@mlmarius Sorry for not replying to you in time, when the client uses an empty client id, the server will assign a client id to it, but whether to return the assigned client id to the client depends on the MQTT protocol version, if you need It, then you need to use MQTT 5。
