### ISSUE TITLE
EMQX  2.4.3 dashboard : request failed with status code 500 error

### ISSUE THREAD

**Issue by dgkirankumar** [emqx/emqx#3832]
**Environment**:

- EMQ X version 4.2.3
- Hardware configuration (e.g. `lscpu`):
- OS 
 System Version: macOS 10.15.5 (19F101)
      Kernel Version: Darwin 19.5.0
      Boot Volume: Macintosh HD
      Boot Mode: Normal
      Computer Name: OKC1234’s MacBook Pro
      User Name: OKC1234 (okc1234)
      Secure Virtual Memory: Enabled
      System Integrity Protection: Enabled
      Time since boot: 7 days 1:50
- Kernel : Darwin OKC1234s-MacBook-Pro.local 19.5.0 Darwin Kernel Version 19.5.0: Tue May 26 20:41:44 PDT 2020; root:xnu-6153.121.2~2/RELEASE_X86_64 x86_6
- Erlang/OTP version (in case you build emqx from source code): 
  Erlang/OTP 23 [erts-11.1.3] [source] [64-bit] [smp:16:16] [ds:16:16:10] [async-threads:1] [hipe] [dtrace]
- Others:

**What happened and what you expected to happen**:
    I took the git hub source of emqx-rel. built it locally on my machine and started emqx broker. broker started successfully
. But when i go to dashbaord keep getting  request failed with status code 500 error.
1. not able to view the metrics
2. not able to add rule
3. not able to view plugins

**How to reproduce it (as minimally and precisely as possible)**:
  in macos 

  1. git clone https://github.com/emqx/emqx-rel
  2. install erlang version 23
  3. go to folder emqx-rel
  4. git checkout master
  5. export EMQX_DEPS_DEFAULT_VSN=v4.2.3
  6. make
  7 on successful build 
  8. Go to /Users/okc1234/emqx-rel/_build/emqx/rel
  9. run bin/emqx start
 10. Go to http://localhost:18083/#/
 11. try to navigate through monitor clients etc

you will see the error as [attached](url)
![image](https://user-images.githubusercontent.com/62382166/99635670-51118480-2a68-11eb-82be-3b8686bfe74c.png)

**Anything else we need to know?**:

**Comment by zmstone** [comment]
Hi. @dgkirankumar 
Could you paste here the crash logs in `/Users/okc1234/emqx-rel/_build/emqx/rel/log` ?

**Comment by dgkirankumar** [comment]
Exec: /Users/okc1234/emqx-rel/_build/emqx/rel/emqx/erts-11.1.3/bin/erlexec -boot /Users/okc1234/emqx-rel/_build/emqx/rel/emqx/releases/4.2.3/emqx -mode embedded -boot_var ERTS_LIB_DIR /Users/okc1234/emqx-rel/_build/emqx/rel/emqx/erts-11.1.3/../lib -mnesia dir "/Users/okc1234/emqx-rel/_build/emqx/rel/emqx/data/mnesia/emqx@127.0.0.1" -config /Users/okc1234/emqx-rel/_build/emqx/rel/emqx/data/configs/app.2020.11.19.13.37.25.config -args_file /Users/okc1234/emqx-rel/_build/emqx/rel/emqx/data/configs/vm.2020.11.19.13.37.25.args -vm_args /Users/okc1234/emqx-rel/_build/emqx/rel/emqx/data/configs/vm.2020.11.19.13.37.25.args -start_epmd false -epmd_module ekka_epmd -proto_dist ekka -- console
Root: /Users/okc1234/emqx-rel/_build/emqx/rel/emqx
/Users/okc1234/emqx-rel/_build/emqx/rel/emqx
Erlang/OTP 23 [erts-11.1.3] [source] [64-bit] [smp:16:16] [ds:16:16:8] [async-threads:4] [hipe] [dtrace]

Starting emqx on node emqx@127.0.0.1
Start http:management listener on 8081 successfully.
Start http:dashboard listener on 18083 successfully.
Start mqtt:tcp listener on 127.0.0.1:11883 successfully.
Start mqtt:tcp listener on 0.0.0.0:1883 successfully.
Start mqtt:ws listener on 0.0.0.0:8083 successfully.
Start mqtt:ssl listener on 0.0.0.0:8883 successfully.
Start mqtt:wss listener on 0.0.0.0:8084 successfully.
EMQ X Broker 4.2.3 is running now!
2020-11-19 13:37:29.432 [warning] [Alarm Handler] Alarm high_system_memory_usage is activated, System memory usage is higher than 70%
Eshell V11.1.3  (abort with ^G)
(emqx@127.0.0.1)1> 2020-11-19 13:37:40.826 [error] GET /api/v4/nodes error: badarg, stacktrace:
[{erlang,element,[2,false],[]},
 {emqx_vm,container_value,4,[{file,"emqx_vm.erl"},{line,313}]},
 {emqx_vm,container_size,3,[{file,"emqx_vm.erl"},{line,295}]},
 {emqx_vm,'-get_memory_once/1-fun-0-',3,[{file,"emqx_vm.erl"},{line,272}]},
 {lists,foldl,3,[{file,"lists.erl"},{line,1267}]},
 {emqx_vm,get_memory_once,1,[{file,"emqx_vm.erl"},{line,275}]},
 {emqx_vm,get_memory,0,[{file,"emqx_vm.erl"},{line,245}]},
 {emqx_mgmt,node_info,1,[{file,"emqx_mgmt.erl"},{line,173}]}]

**Comment by dgkirankumar** [comment]
when i clicked on monitor on left panel got below error

2020-11-19 13:38:10.881 [error] GET /api/v4/nodes error: badarg, stacktrace:
[{erlang,element,[2,false],[]},
 {emqx_vm,container_value,4,[{file,"emqx_vm.erl"},{line,313}]},
 {emqx_vm,container_size,3,[{file,"emqx_vm.erl"},{line,295}]},
 {emqx_vm,'-get_memory_once/1-fun-0-',3,[{file,"emqx_vm.erl"},{line,272}]},
 {lists,foldl,3,[{file,"lists.erl"},{line,1267}]},
 {emqx_vm,get_memory_once,1,[{file,"emqx_vm.erl"},{line,275}]},
 {emqx_vm,get_memory,0,[{file,"emqx_vm.erl"},{line,245}]},
 {emqx_mgmt,node_info,1,[{file,"emqx_mgmt.erl"},{line,173}]}]

**Comment by dgkirankumar** [comment]
Hi @zmstone 

Thanks for looking into this issue quickly.

However i am able to resolve my issue by changing erlang version

when issue occurred erlang version was 23

but i recompiled with version 22

Now it is working as expected.

thanks
Kiran

**Comment by zmstone** [comment]
Hi @dgkirankumar 
This is because emqx is not compatible with OTP 23.
We have not started testing it out on OTP 23 yet.
Please rebuild it on OPT 22 for now.

As for this bug, we'll follow up with a fix ASAP.
