### ISSUE TITLE
How to track exact message size of published services?

### ISSUE THREAD

**Issue by kilianbr** [emqx/emqx#3833]
#### Environment

- OS: Debian Buster
- Erlang/OTP: -
- EMQ: 4

#### Description

Hi!
Sorry if I have overlooked something, but I wasn't able to find any information about my question. 
I want to track the data exchange and therefore the exact data size of my published services. Is there any option to see how big published services are actually?
I do know about the maximum size but that is not what I am looking for.

Best regards!

**Comment by HJianBo** [comment]
In fact, in the production environment, we don't track/record the size of each message.

There is a workaround method that you can trace the debug log for a specified client ID or topic. You can see all the contents of this message payload... Of course, there is a way to know the size of the message as well.

I know, it's a stupid way...

**Comment by kilianbr** [comment]
Hi @HJianBo, thanks for the answer. In the end the solution for my problem was very easy and emqx unrelated. I just found out that I can use Wireshark for this matter.
Results look as below and I'm able to determine the exact size (bitewise) of every message.
![grafik](https://user-images.githubusercontent.com/47358065/100106989-7a1b8600-2e69-11eb-9858-b326b3bad60a.png)

Feel free to close or delete the issue, since it's not directly emqx related.
Best regards!

**Comment by HJianBo** [comment]
Okay, if there are any other questions, feel free to submit a new issue or discuss!
