### ISSUE TITLE
EMQX (3 nodes) to Mosquitto - bridge triples messages

### ISSUE THREAD

**Issue by gmaslowski** [emqx/emqx#3834]
**Please describe your problem in detail, if necessary, you can upload the log file through the attachment**:
Deployment: Kubernetes, 3 replicas, Helm Chart
EMQX version 4.1.1

As in topic description, I have a bridge from EMQX to Mosquitto, but every message sent to EMQX, gets transfered over the bridge to Mosquito three times. Are the bridges created in the context of one broker? I thought that creating a bridge will have "cluster context".

**Comment by endianjoakim** [comment]
I experienced something similar, see https://github.com/emqx/emqx-bridge-mqtt/issues/93#issuecomment-669727956 for solution.

**Comment by gmaslowski** [comment]
Thanks @endianjoakim . That solves it!
