### ISSUE TITLE
EMQX Cluster  Does not work in Enterprise version

### ISSUE THREAD

**Issue by outminder** [emqx/emqx#3835]
**Environment**:

- EMQ X version (e.g. `emqx_ctl status`): 
**Node 'emqx3@10.19.12.182' is started
emqx 4.2.0 is running** 

- Hardware configuration (e.g. `lscpu`):
**Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                2
On-line CPU(s) list:   0,1
Thread(s) per core:    2
Core(s) per socket:    1
Socket(s):             1
NUMA node(s):          1
Vendor ID:             AuthenticAMD
CPU family:            23
Model:                 1
Model name:            AMD EPYC 7571
Stepping:              2
CPU MHz:               2199.946
BogoMIPS:              4399.89
Hypervisor vendor:     KVM
Virtualization type:   full
L1d cache:             32K
L1i cache:             64K
L2 cache:              512K
L3 cache:              8192K
NUMA node0 CPU(s):     0,1**

- OS (e.g. `cat /etc/os-release`):
**NAME="Red Hat Enterprise Linux Server"
VERSION="7.8 (Maipo)"
ID="rhel"
ID_LIKE="fedora"**

- Kernel (e.g. `uname -a`):
- Erlang/OTP version (in case you build emqx from source code): 
- Others:

**What happened and what you expected to happen**:
I have used the emqx-ee-centos7-4.2.0-x86_64.zip package on my RHEL version 7.8. I have setup 3 brokers on 3 different nodes. emqx1@10.19.0.40, emqx2@10.19.1.31 & emqx3@10.19.12.182 . All 3 servers are up and running. The cluster port configuration range specified in the /etc/emqx.conf file is 
**node.dist_listen_min = 6369
node.dist_listen_max = 6379**
I have opened the firewall for port 4369 and for the range 6369-7369. The session cookie is same across all the 3 broker nodes. But when I try to run  the below command it fails with node down
@ip-10-19-12-182 emqx]$ ./bin/emqx_ctl cluster join emqx1@10.19.0.40
Failed to join the cluster: {node_down,'emqx1@10.19.0.40'}

Please let me know what is the cause of this failure?

**Comment by zmstone** [comment]
Hi @outminder 
EPMD is by default disabled in v4.x (set `WITH_EPMD` in environment variable to enable).
By default, the nodes connect each other without EPMD.
The default base port is `4370`, the port offset from the base is the node name suffix.
i.e. for node `emqx1` the node listens port `4371` and so on.
If your nodes are running in different (virtual) hosts,
it's perhaps easier to manage if the nodes are assigned with the same name,
so that the Erlang distribution port number is the same for all node.

**Comment by outminder** [comment]
@zmstone thanks, let me test this out 
export $WITH_EPMD=true and enabling port 4370, 4371, 4372 & 4373.

**Comment by outminder** [comment]
It works after enabling the EPMD (I should have figured this out), and it worked without opening 4370-4373, maybe I misunderstood what you are trying to say

**Comment by zmstone** [comment]
4370 based port is fixed port mapping, so it does not require EPMD.

WITH_EPMD=true enables the dynamic port mapping, this is when min~max port range configs take effect.
