### ISSUE TITLE
emqx dashboard url not found

### ISSUE THREAD

**Issue by wangxu-alvin** [emqx/emqx#3840]
after start emqx and login emqx dashboard, emqx dashboard always prompt url not found. The chrome console shows the error like below:
![微信截图_20201123115728](https://user-images.githubusercontent.com/2033862/99928225-2898cb80-2d83-11eb-8d96-0c9efd6c2df6.png)

Failed to load resource: the server responded with a status of 404 (Not Found)
http://10.24.11.231:18083/api/v4/nodes?_=1606103618930

**Environment**:
emqx-centos7-4.2.3-x86_64.zip

- EMQ X version (e.g. `emqx_ctl status`): 
```
[root@localhost emqx]# ./bin/emqx_ctl status
Usage: emqx_ctl
--------------------------------------------------------------------------------------------------------------
recon memory                                                          # recon_alloc:memory/2
recon allocated                                                       # recon_alloc:memory(allocated_types, current|max)
recon bin_leak                                                        # recon:bin_leak(100)
recon node_stats                                                      # recon:node_stats(10, 1000)
recon remote_load Mod                                                 # recon:remote_load(Mod)
recon proc_count Attr N                                               # recon:proc_count(Attr, N)
--------------------------------------------------------------------------------------------------------------
retainer info                                                         # Show the count of retained messages
retainer topics                                                       # Show all topics of retained messages
retainer clean                                                        # Clean all retained messages
retainer clean <Topic>                                                # Clean retained messages by the specified topic filter
--------------------------------------------------------------------------------------------------------------
admins add <Username> <Password> <Tags>                               # Add dashboard user
admins passwd <Username> <Password>                                   # Reset dashboard user password
admins del <Username>                                                 # Delete dashboard user
--------------------------------------------------------------------------------------------------------------
telemetry enable                                                      # Enable telemetry
telemetry disable                                                     # Disable telemetry
telemetry get data                                                    # Get reported telemetry data
--------------------------------------------------------------------------------------------------------------
rules list                                                            # List all rules
rules show <RuleId>                                                   # Show a rule
rules create                                                          # Create a rule
rules delete <RuleId>                                                 # Delete a rule
--------------------------------------------------------------------------------------------------------------
rule-actions list                                                     # List actions
rule-actions show <ActionId>                                          # Show a rule action
--------------------------------------------------------------------------------------------------------------
resources create                                                      # Create a resource
resources list [-t <ResourceType>]                                    # List resources
resources show <ResourceId>                                           # Show a resource
resources delete <ResourceId>                                         # Delete a resource
--------------------------------------------------------------------------------------------------------------
resource-types list                                                   # List all resource-types
resource-types show <Type>                                            # Show a resource-type
```

- Hardware configuration (e.g. `lscpu`):
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                8
On-line CPU(s) list:   0-7
Thread(s) per core:    1
Core(s) per socket:    2
座：                 4
NUMA 节点：         1
厂商 ID：           GenuineIntel
CPU 系列：          6
型号：              63
型号名称：        Intel(R) Xeon(R) CPU E5-2630 v3 @ 2.40GHz
步进：              2
CPU MHz：             2397.223
BogoMIPS：            4794.44
超管理器厂商：  VMware
虚拟化类型：     完全
L1d 缓存：          32K
L1i 缓存：          32K
L2 缓存：           256K
L3 缓存：           20480K
NUMA 节点0 CPU：    0-7
Flags:                 fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts mmx fxsr sse sse2 ss ht syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts nopl xtopology tsc_reliable nonstop_tsc aperfmperf eagerfpu pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm abm epb fsgsbase tsc_adjust bmi1 avx2 smep bmi2 invpcid xsaveopt dtherm ida arat pln pts

- OS (e.g. `cat /etc/os-release`): 
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

- Kernel (e.g. `uname -a`):
Linux localhost.localdomain 3.10.0-862.el7.x86_64 #1 SMP Fri Apr 20 16:44:24 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

- Erlang/OTP version (in case you build emqx from source code): 
- Others:

**What happened and what you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Comment by HJianBo** [comment]
Here is a very weird phenomenon...

Is the `emqx_management` plugin started? Could you check the `data/loaded_plugins` file? Does it contained `{emqx_management, true}` line?

**Comment by wangxu-alvin** [comment]
There is {emqx_management, true} in the file.  I also tried other versions of emqx on this machine , they are:

- emqx-centos7-v4.0.7.zip

- emqx-centos7-v4.1.4.zip

- emqx-centos7-4.2.3-x86_64.rpm

- curl https://repos.emqx.io/install_emqx.sh | bash

the same problem occurred. 

Is there any necessary component needed for centos 7.8. I believe it must be some problems about my environment.
I executed install_emqx.sh on ALi cloud centos7 system and installed deb package on another ubuntu server those all worked fine.

![微信截图_20201124102353](https://user-images.githubusercontent.com/2033862/100041827-18492500-2e45-11eb-838b-dcca4b923bfa.png)

**Comment by wangxu-alvin** [comment]
the api information of the dashboard with 404 error is accessible, see the picture below
![api_accessable](https://user-images.githubusercontent.com/2033862/100080757-2b79e600-2e81-11eb-9267-05ff5b5f2458.png)
but the api information of the dashboard without error is not accessible

Is it a clue for the problem?

**Comment by HJianBo** [comment]
If the `. /bin/emqx_ctl status` does not print the correct version information, then emqx_management must have failed to start. Could you check the 8080 or 8081 is being listened by beam.smp?

**Comment by wangxu-alvin** [comment]
Yep, it is because of 8081 port occupation. 
Thanks a lot.
