### ISSUE TITLE
mysql acl emqx_auth_mysql

### ISSUE THREAD

**Issue by qxqxq** [emqx/emqx#3846]
**Please describe your problem in detail, if necessary, you can upload the log file through the attachment**:
Environment
OS: Ubuntu 18.04
Erlang/OTP: 21
EMQ: 4.05

python paho.mqtt.client

I started the emqx_auth_mysql plug-in to verify the ACL.

acl.conf：
{deny, all}.

emqx.conf:
allow_anonymous = false
acl_nomatch = deny                                
acl_file = etc/acl.conf

emqx_auth_mysql.conf:
auth.mysql.acl_query = select allow, ipaddr, username, clientid, access, topic from mqtt_acl where ipaddr = '%a' or username = '%u' or username = '$all' or clientid = '%c' or clientid = '%u'

mysql:
![image](https://user-images.githubusercontent.com/44389330/100070909-6fff8480-2e75-11eb-80fb-f1b2f8df20fa.png)

client = mqtt.Client(client_id='')
client.username_pw_set(username='bl73L6zx', password='xxxx')

I can connect normally, but I cannot subscribe to any Topic. At this point the rc returned from the subscription is 0. I can only subscribe to topics if I specify client_id.
ex:
client = mqtt.Client(client_id='bl73L6zx')

First of all, I don't understand why the condition of SQL statement has been used clientid = '%u' and still can't pass acl.
Second, why does a RC that is subscribed always return 0 regardless of whether it has permission or not.

Later I tried to change mysql to something like this, which would still not allow ACL validation without specifying client_id.

mysql:
![image](https://user-images.githubusercontent.com/44389330/100071003-86a5db80-2e75-11eb-951f-34426d81a484.png)

I need your help. Thank you very much!

**Comment by HJianBo** [comment]
Hi @qxqxq 
>  why does a RC that is subscribed always return 0 regardless of whether it has permission or not.

In any case, as long as RC is equal to 0, the subscription is successful. This may be due to other ACL rules that allow this subscription operation.

Are there any other rules that will match this Subscrbe Operation? Example:
```erlang
%% By default, the acl.conf allows IP 127.0.0.1 with all PUBSUB permissions.
{allow, {ipaddr, "127.0.0.1"}, pubsub, ["$SYS/#", "#"]}.
```

**Comment by qxqxq** [comment]
Acl.conf has only {deny, all}.

**Comment by qxqxq** [comment]
Why can't you get through the ACL in the case of a connection using Username?
