### ISSUE TITLE
Connection getting reset by broker

### ISSUE THREAD

**Issue by Vdm1994** [emqx/emqx#3849]
Environment:

Kubernetes v1.17.4
Docker image: emqx/emqx:4.2.1
Emqx cluster nodes(pods) : 3

Host machine:
CPU core - 16
RAM : 32GB
OS : Ubuntu 18.04

No. of request per sec ~3000 (Connection on tcp)

Tuning parameters as per doc
Environment variables set for pod
EMQX_CLUSTER__K8S__ADDRESS_TYPE: hostname
EMQX_CLUSTER__K8S__APISERVER: https://kubernetes.default.svc:443
EMQX_CLUSTER__K8S__SUFFIX: svc.cluster.local
EMQX_ZONE__EXTERNAL__RATE_LIMIT__CONN_MESSAGES_IN: 5000,1s
EMQX_ZONE__EXTERNAL__RATE_LIMIT__CONN_BYTES_IN: 5000KB,1S

Description:

Issue observed, is that after a certain number of connection Near anytime after 2K+ connection gets reset by Broker.
in pcap TCP ZERO WINDOW message is initiated from broker towards client

All messages published are

    with qos0
    from same kubernetes cluster but from different pods (we are not using emqtt_bench but using Eclipse Paho C client to publish the messages).

can anyone suggest what i need to do to support more number of messages per second ?

**Comment by HJianBo** [comment]
Duplicated https://github.com/emqx/emqx/issues/3848
