### ISSUE TITLE
On high Message inflow rate, broker is closing connection. 

### ISSUE THREAD

**Issue by jayshah3008** [emqx/emqx#3850]
Environment:

Kubernetes v1.17.4
Docker image: emqx/emqx:4.2.1
Emqx cluster nodes(pods) : 3 also with 1

Host machine:
CPU core - 16
RAM : 32GB
OS : Ubuntu 18.04

No. of request Msg 4000 msg/sec  (Connection on tcp)

Tuning parameters as per doc
Environment variables set for pod
EMQX_CLUSTER__K8S__ADDRESS_TYPE: hostname
EMQX_CLUSTER__K8S__APISERVER: https://kubernetes.default.svc:443
EMQX_CLUSTER__K8S__SUFFIX: svc.cluster.local
EMQX_ZONE__EXTERNAL__RATE_LIMIT__CONN_MESSAGES_IN: 5000,1s
EMQX_ZONE__EXTERNAL__RATE_LIMIT__CONN_BYTES_IN: 5000KB,1S

Also, Reconnect on client was enabled. 

Description:

Issue observed,  after a  number of connection Near anytime after 4k msg/sec gets reset by Broker.
in pcap TCP ZERO WINDOW message is initiated from broker towards client. 

Qos = 0 

can anyone suggest what i need to do to support more number of messages per second ?

**Comment by tigercl** [comment]
@jayshah3008 What is the average size of your message？

**Comment by jayshah3008** [comment]
Message size : 1500 BYtes on an average
Message Rate: 4000 Msg/Sec
Num. Connections: 1 Client

**Comment by sharechat-dhruvsehgal** [comment]
@jayshah3008 , were you able to resolve this issue?
