### ISSUE TITLE
Subscriber cannot Receive Message when connected to different broker

### ISSUE THREAD

**Issue by outminder** [emqx/emqx#3853]
**Please describe your problem in detail, if necessary, you can upload the log file through the attachment**:
Hi, I have 3 modes cluster and the emqx_ctl cluster status shows the 3 nodes in the running nodes
`Cluster status: #{running_nodes =>
                      ['emqx1@10.19.0.40','emqx2@10.19.1.31',
                       'emqx3@10.19.12.182'],
                  stopped_nodes => []}
`
I start my subscriber mosquitto_sub listening on host 10.19.0.40 and publish on 10.19.1.31, the subscriber which is listening on different host does not receive the message. It only receives when I start the subscriber on the same node where I am publishing. I thought by default the behavior of clustering will share the subscriber details to other brokers. I am using the default configuration, only changes are the node name and the cookie.

Do I need to enable anything to make this work? Thanks

**Comment by zmstone** [comment]
Hi @outminder 
could you check if you are able to see a consistent number of connected clients from management dashboard pages when connect the browser to different nodes ?

**Comment by zmstone** [comment]
and check if port `5369` is reachable between the nodes.
this is the inter-broker message passing port.

**Comment by outminder** [comment]
@zmstone Here's the output of clients list 
```
./bin/emqx_ctl clients list
Client(mosq-r1ejSAd1ZDf9RzrBpR, username=undefined, peername=10.19.2.211:60380, clean_start=true, keepalive=60, session_expiry_interval=0, subscriptions=1, inflight=0, awaiting_rel=0, delivered_msgs=0, enqueued_msgs=0, dropped_msgs=0, connected=true, created_at=1606413478063, connected_at=1606413478062)
```
I can only see this on the broker where it is connected and I think this is a normal behavior.
I have only enabled **4369** and not **5369** . I will enable **5369** and check.

**Comment by outminder** [comment]
@zmstone Just an info, I don't see this port **5369** being mentioned anywhere in the emqx.conf or in cluster.conf. I am using the package emqx-ee-centos7-4.2.0-x86_64.zip . Shouldn't this be part of config file?

**Comment by zmstone** [comment]
should be `rpc.tcp_client_port` and `rpc.tcp_server_port`
I'll have a look into the package later.

**Comment by zmstone** [comment]
its located in `etc/rpc.conf` for enterprise edition.

**Comment by zmstone** [comment]
@outminder is the issue resolved ?

**Comment by outminder** [comment]
@zmstone, yes this is resolved, I changed the rpc discovery from stateless to manual and opened port 5369 in the firewall. Thanks
