### ISSUE TITLE
HTTP API Response Bug

### ISSUE THREAD

**Issue by berayb** [emqx/emqx#3855]
Desc: Clustered two nodes that run on Ubuntu servers. Using HTTP API two get rule information. 

The response comes from one of the nodes randomly which yields 0 for statistics sometimes.

![Screen Shot 2020-11-27 at 23 20 19](https://user-images.githubusercontent.com/56160056/100482024-20d08280-3107-11eb-828b-11ea4b5f9f44.png)

I supposed that it should sync the info across nodes.

**Comment by tigercl** [comment]
@berayb Sorry for not replying to you in time. At present, data such as hit count in the rule engine are independent of each other between nodes, not global. Hope to solve your problem.
