### ISSUE TITLE
Docker - EMQX 4.2.3 dashboard : Request failed with status code 400

### ISSUE THREAD

**Issue by sergioxdev** [emqx/emqx#3856]
**Environment**:

- EMQ X version (e.g. `emqx_ctl status`): 4.2.3
- OS (e.g. `cat /etc/os-release`): Centos + Plesk + Docker
- Kernel (e.g. `uname -a`): Linux 3.10.0-1160.6.1.el7.x86_64 GNU/Linux

**What happened and what you expected to happen**:
**How to reproduce it (as minimally and precisely as possible)**:
when I try from the dashboard to activate a module or a plugin, 
through the start or enable buttons, I have the following error
return Request failed with status code 400

---Log---
node.max_ports=1048576
listener.tcp.external.acceptors=64
listener.ssl.external.acceptors=32
node.process_limit=2097152
node.max_ets_tables=2097152
listener.ws.external.acceptors=16
EMQ X Broker 4.2.3 is started successfully!
['2020-11-27T23:08:32Z']:emqx start
Start http:management listener on 8081 successfully.
Start http:dashboard listener on 18083 successfully.
Start mqtt:tcp listener on 127.0.0.1:11883 successfully.
Start mqtt:tcp listener on 0.0.0.0:1883 successfully.
Start mqtt:ws listener on 0.0.0.0:8083 successfully.
Start mqtt:ssl listener on 0.0.0.0:8883 successfully.
Start mqtt:wss listener on 0.0.0.0:8084 successfully.
EMQ X Broker 4.2.3 is running now!
Eshell V10.7.2.1  (abort with ^G)
(851e6fbdf4cf@172.17.0.3)1> node.max_ports=1048576
listener.tcp.external.acceptors=64
listener.ssl.external.acceptors=32
node.process_limit=2097152
node.max_ets_tables=2097152
listener.ws.external.acceptors=16
EMQ X Broker 4.2.3 is started successfully!
['2020-11-27T23:17:38Z']:emqx start
Start mqtt:tcp listener on 127.0.0.1:11883 successfully.
Start mqtt:tcp listener on 0.0.0.0:1883 successfully.
Start mqtt:ws listener on 0.0.0.0:8083 successfully.
Start mqtt:ssl listener on 0.0.0.0:8883 successfully.
Start mqtt:wss listener on 0.0.0.0:8084 successfully.
EMQ X Broker 4.2.3 is running now!
Eshell V10.7.2.1  (abort with ^G)
(851e6fbdf4cf@172.17.0.3)1> 2020-11-27 23:29:33.370 [error] Params error: {{1,truncated_json},
               [{jiffy,decode,2,[{file,"jiffy.erl"},{line,71}]},
                {minirest_handler,json_decode,1,
                                  [{file,"minirest_handler.erl"},{line,175}]},
                {minirest_handler,parse_params,1,
                                  [{file,"minirest_handler.erl"},{line,130}]},
                {minirest_handler,dispatch,2,
                                  [{file,"minirest_handler.erl"},{line,79}]},
                {minirest,handle_request,2,[{file,"minirest.erl"},{line,112}]},
                {minirest,init,2,[{file,"minirest.erl"},{line,104}]},
                {cowboy_handler,execute,2,
                                [{file,"cowboy_handler.erl"},{line,41}]},
                {cowboy_stream_h,execute,3,
                                 [{file,"cowboy_stream_h.erl"},{line,320}]}]}

**Anything else we need to know?**:

in order to activate the mysql plugin I had to use it from cli:
docker exec -it emqx emqx_ctl plugins load emqx_auth_mysql

**Comment by tigercl** [comment]
@sergioxdev It seems that this is caused by an incomplete HTTP request received by emqx. We have not been able to reproduce this problem for the time being. We suggest you to check your network status.

**Comment by sergioxdev** [comment]
@tigercl I thank you in advance I add more info hoping it will help

the operations I perform on a test server are:

1. I install the emqx image from the docker panel present on plesk
https://hub.docker.com/r/emqx/emqx/
2. I map ports and volumes persistently
3. I edit the following files:

- emqx.conf
zone.internal.bypass_auth_plugins = false
acl_nomatch = deny
allow_anonymous = false

- emqx_dashboard.conf
dashboard.default_user.password = xxxxxx

- emqx_auth_mysql.conf
auth.mysql.username = xxxxxx
auth.mysql.password = xxxxxx
auth.mysql.database = xxxxxx

- acl.conf
%%{allow, all}.


I noticed:
1. the dashboard password remains: public,
as if dashboard.default_user.password, was not set
2. the problem already highlighted above
to solve I run:

docker exec -it emqx emqx_ctl plugins load emqx_auth_mysql
docker exec -it emqx emqx_ctl modules load emqx_mod_topic_metrics

or alternatively added in the following files:
- loaded_plugins
{emqx_auth_mysql,true}.
- loaded_modules
{emqx_mod_topic_metrics,true}.

apart from the problem of enabling modules and plugins, the rest of the dashboard without working properly

**Comment by tigercl** [comment]
@sergioxdev Sorry for not fully understanding what you mean. “The rest of the dashboard is not working”, what does it mean?

**Comment by sergioxdev** [comment]
@tigercl I am testing the functioning of emqx

above I just reported the configurations, which I set on the test machine,
I encountered 2 problems, and they are:

1. at the first access to the dashboard even if I have set the password in the file:

emqx_dashboard.conf
dashboard.default_user.password = xxxxxx

I have to enter the password: public, otherwise I cannot access the dashboard,
even if I set the password on "dashboard.default_user.password" it doesn't work,
in order to replace it, I have to change it from the dashboard.

2. Using the dashboard, plugins and modules cannot be activated, because it returns the following error:
return Request failed with status code 400

in order to activate a module or a plugin I had to do it in the following 2 ways:
- cli commands
- modify the "loaded_plugins, loaded_modules" files
as already written above

I continued to test the dashboard, and I found only these 2 malfunctions all the other commands work for example.
- kick out client - ok
- create rule - ok
- web socket - ok

**Comment by tigercl** [comment]
@sergioxdev Because of some unreasonable design, the default user information in the configuration file is read and written into the database when emqx is started for the first time, and the data in the database is read first during subsequent startups. After startup, modify it through HTTP API or command line interface.
Regarding the problem that the dashboard cannot start the plugin, we are sorry that we have not reproduced it yet. According to your previous description, it should be caused by an incomplete HTTP request, so you may need to cooperate with the crawling of network packets to find more problems.
