### ISSUE TITLE
Help me to control access via mysql database.

### ISSUE THREAD

**Issue by nipunahasanka** [emqx/emqx#3857]
Hello guys,
I'm a newbie to EMQ X. I have successfully installed and run the EMQ X broker. Anonymouse mode is connecting well. Then I turned off the anonymous mode and activated to MySQL auth module after setting up database configuration and database table and inserts of users and ACL also. Then I can log in to MQTT successfully and invalid usernames and passwords are blocking successfully. I checked the connection over WS on http://tools.emqx.io. 

**But I have an issue, I can't understand how to control access to sub, pub, or subpub using MySQL ACL. I used example ACL rules to make deny user "admin2" to subscribe topic "x". My attempt was failed. I really waited for understanding why this for 10 hours. But I failed to control them.** 

**Please anyone could help me understand this and control access over MySQL?**
Thanks in advance.

**Comment by tigercl** [comment]
@nipunahasanka Hope these two documents can help you: 
1. https://docs.emqx.io/broker/latest/en/advanced/acl-mysql.html
2. https://docs.emqx.io/broker/latest/en/advanced/auth-mysql.html
