### ISSUE TITLE
Several questions about mqtt documents (nginx, alarms, cluster)

### ISSUE THREAD

**Issue by wuzl807924995** [emqx/emqx#3861]
我试了一下用nginx链接最新版本的emq(4.2.1) ,并且粗略尝试了一下,下面有几个问题

在网页控制台我发现每个客户端都会有一个端口(nginx服务器代理的端口)是不是意味着端口耗尽的时候就无法链接新的客户端?
集群模式好像是类似elasticsearch那种无主的星状网络？如何避免脑裂,以及在中间一台机器宕机的情况下如何保证他的数据在分发到集群的其他机器上？
关于大盘警告,在2.x版本上有见到过警告一列(alarms),3.x版本好像没有见到过,4.x又有了？官网也没有关于这个方面的文档介绍

**Comment by tigercl** [comment]
@wuzl807924995 
1. Yes, the port will be consumed, but it can be solved by setting multiple IPs for the network card.
2. emqx may have split brain, but it also has self-healing ability.
3. We will add warning documents as soon as possible, thanks for your feedback.
