### ISSUE TITLE
EMQX Enterprise HTTP API - GET /api/v4/clients returns clients on whichever node is hit

### ISSUE THREAD

**Issue by Kidsan** [emqx/emqx#3865]
**Please describe your problem in detail, if necessary, you can upload the log file through the attachment**:

I have the requirement to query the cluster for a list of clients connected to it (across all broker nodes). The documentation available [here](https://docs.emqx.io/enterprise/latest/en/advanced/http-api.html#endpoint-get-clients) states that this returns all clients under the cluster, however I have found that it actually only returns the clients on the node that the request hits. When I issue a GET request to /api/v4/clients via the LoadBalancer my cluster sits behind, the request is routed round-robin to a node and I get the list of clients on that node only. I have the same requirement to get a list of subscriptions active on the cluster (not on one node), using /api/v4/subscriptions which has this same issue (result is per node, not cluster)

Is it possible to get this information via a HTTP request? Do I have to continuously spam the request to build a picture client-side of all active clients or subscriptions? I appreciate any help with this.

**Comment by tigercl** [comment]
@Kidsan Sorry for not responding to you in time, can you provide us with the enterprise version you are using?

**Comment by Kidsan** [comment]
Sorry for not including it originally. We are running v4.0.5

**Comment by tigercl** [comment]
@Kidsan We probably have not released the enterprise version of version 4.0.5, so you should use the open source version? It used to be a bug, but we have fixed it in subsequent versions. We recommend that you use our latest 4.2.3.

**Comment by Kidsan** [comment]
@tigercl thank you for your help, I've tested with version 4.2.1 and confirmed the requests work as I need.
We are running this in kubernetes - I notice the image on dockerhub doesn't have 4.2.3.
I will look to upgrading this in production, I'm happy that this issue is closed. Thank you.
