### ISSUE TITLE
Use `map_get` function  in Rule Engine, the default values are not as expected

### ISSUE THREAD

**Issue by linG5821** [emqx/emqx#3866]
**Environment**:

- EMQ X version : 4.2.2
- Hardware configuration: 8c 16g
- OS :centos 7.8.2003
- Docker : 19.03.13
- Kernel (e.g. `uname -a`): 3.10.0-1127.13.1.el7.x86_64

**What happened and what you expected to happen**:
For example (not expected):

Send Data Payload
case 1:
`
{
"msgId": 1002,
"params": {
"convertTemp": 20,
"engineSpeed": 42,
"hydOilTem": 30
}
}
`
case 2:
`
{
"msgId": 1002,
"params": {
"convertTemp": 20,
"engineSpeed": 42,
}
}
`

my rule sql
`
SELECT
  payload,
  map_get('engineWorkTime', payload.params, -1) as payload.params.engineWorkTime,
  map_get('hydOilTem', payload.params, -1) as payload.params.hydOilTem
FROM
  "xxxxx/#"
`

The expected results
case 1:
`
{
"msgId": 1002,
"params": {
"convertTemp": 20,
"engineSpeed": 42,
"engineWorkTime": -1,
"hydOilTem": 30
}
}
`
case 2:
`
{
"msgId": 1002,
"params": {
"convertTemp": 20,
"engineSpeed": 42,
"engineWorkTime": -1,
"hydOilTem": -1
}
}
`
The actual results

case 1:
`
{
"msgId": 1002,
"params": {
"convertTemp": 20,
"engineSpeed": 42,
"hydOilTem": 30
}
}
`
case 2:
`
{
"msgId": 1002,
"params": {
"convertTemp": 20,
"engineSpeed": 42,
"hydOilTem": -1
}
}
`

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

I'm trying to change the order of the two map_get functions,  It always seems that the last function will get the default value

if my rule sql looks like this, I can get the right answer, but the nodes are different:
`
SELECT
  payload,
  map_get('engineWorkTime', payload.params, -1) as engineWorkTime,
  map_get('hydOilTem', payload.params, -1) as hydOilTem
FROM
  "xxxxx/#"
`

**Comment by terry-xiaoyu** [comment]
@linG5821  Thank you, the fix for this would be included in the emqx 4.2.4.
