### ISSUE TITLE
The emqx_auth_redis plugin is used, redis has enabled password verification, and the password auth.redis.password = 123456 is configured in emqx_auth_redis.conf, and an error will be reported when the plugin starts

### ISSUE THREAD

**Issue by glen8** [emqx/emqx#3867]
使用了emqx_auth_redis插件，redis开启了密码验证，在emqx_auth_redis.conf 配置了密码 auth.redis.password = 123456，插件启动就会报错
**Environment**:

- EMQ X version (e.g. `emqx_ctl status 4.2.3`): 
- Hardware configuration (e.g. `lscpu`):
- OS (e.g. `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Erlang/OTP version (in case you build emqx from source code): 
- Others:

**What happened and what you expected to happen**:
Reload plugin emqx_auth_redis error: {emqx_auth_redis,
                                      {bad_return,
                                       {{emqx_auth_redis_app,start,
                                         [normal,[]]},
                                        {'EXIT',
                                         {{badmatch,
                                           {error,
                                            {shutdown,
                                             {failed_to_start_child,
                                              emqx_auth_redis,
                                              {shutdown,
                                               {failed_to_start_child,
                                                worker_sup,
                                                {shutdown,
                                                 {failed_to_start_child,
                                                  {worker,1},
                                                  {noproc,
                                                   {gen_server,call,
                                                    [eredis_client,
                                                     {send,
                                                      ["AUTH"," \"",
                                                       <<"123456">>,
                                                       "\"\r\n"]}]}}}}}}}}}},
                                          [{emqx_auth_redis_app,start,2,
                                            [{file,"emqx_auth_redis_app.erl"},
                                             {line,30}]},
                                           {application_master,start_it_old,
                                            4,
                                            [{file,"application_master.erl"},
                                             {line,277}]}]}}}}}.
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Comment by tigercl** [comment]
@glen8 Sorry for the inconvenience, this should be a bug, we will fix it as soon as possible.

**Comment by HJianBo** [comment]
Hi guys this bug will be fixed on 4.2.4

**Comment by HJianBo** [comment]
Recently, we have released the v4.2.4. Wait a little while and then you can download and try it
