### ISSUE TITLE
EMQX 4.1.0 HTTP API - GET /api/v4/clients returns internal error, we have 3 emq server makeup cluster, and less than 10000 clients

### ISSUE THREAD

**Issue by panzhao163** [emqx/emqx#3868]
[error] GET /api/v4/clients error: {badkey,conn_state}, stacktrace:
[{maps,get,[conn_state,#{}],[]},
 {emqx_mgmt,item,2,
            [{file,"/emqx-rel/_build/emqx-pkg/lib/emqx_management/src/emqx_mgmt.erl"},
             {line,774}]},
 {emqx_mgmt_api_clients,format,1,
                        [{file,"/emqx-rel/_build/emqx-pkg/lib/emqx_management/src/emqx_mgmt_api_clients.erl"},
                         {line,162}]},
 {lists,map,2,[{file,"lists.erl"},{line,1239}]},
 {lists,map,2,[{file,"lists.erl"},{line,1239}]},
 {emqx_mgmt_api,select_table,5,
                [{file,"/emqx-rel/_build/emqx-pkg/lib/emqx_management/src/emqx_mgmt_api.erl"},
                 {line,177}]},
 {emqx_mgmt_api,do_cluster_query,6,
                [{file,"/emqx-rel/_build/emqx-pkg/lib/emqx_management/src/emqx_mgmt_api.erl"},
                 {line,130}]},
 {emqx_mgmt_api,cluster_query,3,
                [{file,"/emqx-rel/_build/emqx-pkg/lib/emqx_management/src/emqx_mgmt_api.erl"},
                 {line,118}]}]

**Comment by tigercl** [comment]
@panzhao163 Sorry for not responding to you in time, can you provide us with the emqx version you are using?

**Comment by panzhao163** [comment]
> @panzhao163 Sorry for not responding to you in time, can you provide us with the emqx version you are using?

@tigercl    EMQX version:   4.1.0

**Comment by HJianBo** [comment]
What protocol type is the client connected on emqx? Is it only MQTT or else?

**Comment by panzhao163** [comment]
@HJianBo  different clients, different  type,  tcp, ws and ssl,    GET /api/v4/clients returns internal error by chance, not always

**Comment by HJianBo** [comment]
Thanks for your report. We will try to fix it in 4.3.0

**Comment by panzhao163** [comment]
@HJianBo  ok, thank u

**Comment by HJianBo** [comment]
Hi @panzhao163 We have released this fix into 4.3-beta.1 Thanks for your feedback
