### ISSUE TITLE
complie emqx_retainer error

### ISSUE THREAD

**Issue by linany** [emqx/emqx#3872]
**erlang version:** Erlang/OTP 21 [erts-10.3.5.13] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1] [hipe]
**ubuntu18.04**
root@li-virtual-machine:~/emqx/emqx_rel# make
Makefile:55: "the value of app_vsn is v3.1.2"
 DEP    emqx_retainer
make[1]: 进入目录“/root/emqx/emqx_rel/deps/emqx”
make[2]: 进入目录“/root/emqx/emqx_rel/deps/cuttlefish”
./rebar get-deps
==> getopt (get-deps)
==> neotoma (get-deps)
==> cuttlefish (get-deps)
./rebar compile
==> getopt (compile)
==> neotoma (compile)
==> cuttlefish (compile)
./rebar skip_deps=true escriptize
==> cuttlefish (escriptize)
make[2]: 离开目录“/root/emqx/emqx_rel/deps/cuttlefish”
make[2]: 进入目录“/rootemqx/emqx_rel/deps/jsx”
make[2]: 离开目录“/root/emqx/emqx_rel/deps/jsx”
make[2]: 进入目录“/root/emqx/emqx_rel/deps/gproc”
make[2]: 离开目录“/root/emqx/emqx_rel/deps/gproc”
make[2]: 进入目录“/root/emqx/emqx_rel/deps/gen_rpc”
make[3]: 进入目录“/root/emqx/emqx_rel/deps/ssl_verify_fun”
./rebar3  compile
===> Verifying dependencies...
===> Compiling ssl_verify_fun
make[3]: 离开目录“/root/emqx/emqx_rel/deps/ssl_verify_fun”
make[2]: 离开目录“/root/emqx/emqx_rel/deps/gen_rpc”
make[2]: 进入目录“/root/emqx/emqx_rel/deps/ekka”
make[2]: 离开目录“/root/emqx/emqx_rel/deps/ekka”
make[2]: 进入目录“/root/emqx/emqx_rel/deps/esockd”
 GEN    rebar.config
make[2]: 离开目录“/root/emqx/emqx_rel/deps/esockd”
make[2]: 进入目录“/root/emqx/emqx_rel/deps/cowboy”
make[3]: 进入目录“/root/emqx/emqx_rel/deps/cowlib”
make[3]: 离开目录“/root/emqx/emqx_rel/deps/cowlib”
make[3]: 进入目录“/root/emqx/emqx_rel/deps/ranch”
make[3]: 离开目录“/root/emqx/emqx_rel/deps/ranch”
 GEN    rebar.config
make[2]: 离开目录“/root/emqx/emqx_rel/deps/cowboy”
make[2]: 进入目录“/root/emqx/emqx_rel/deps/replayq”
make[2]: 离开目录“/root/emqx/emqx_rel/deps/replayq”
make[1]: 离开目录“/root/emqx/emqx_rel/deps/emqx”
make[1]: 进入目录“/root/emqx/emqx_rel/deps/emqx_retainer”
 DEP    clique
{"init terminating in do_boot",{undef,[{rebar_utils,wordsize,[],[]},{erl_eval,do_apply,6,[{file,"erl_eval.erl"},{line,680}]},{erl_eval,expr,5,[{file,"erl_eval.erl"},{line,232}]},{erl_eval,expr,5,[{file,"erl_eval.erl"},{line,233}]},{erl_eval,expr_list,6,[{file,"erl_eval.erl"},{line,888}]},{erl_eval,expr,5,[{file,"erl_eval.erl"},{line,429}]},{erl_eval,exprs,5,[{file,"erl_eval.erl"},{line,126}]},{init,start_it,1,[]}]}}
init terminating in do_boot ({undef,[{rebar_utils,wordsize,[],[]},{erl_eval,do_apply,6,[{_},{_}]},{erl_eval,expr,5,[{_},{_}]},{erl_eval,expr,5,[{_},{_}]},{erl_eval,expr_list,6,[{_},{_}]},{erl_eval,exp

Crash dump is being written to: erl_crash.dump...done
make[2]: 进入目录“/root/emqx/emqx_rel/deps/clique”
make[2]: *** 无目标。 停止。
make[2]: 离开目录“/root/emqx/emqx_rel/deps/clique”
../../erlang.mk:341: recipe for target 'deps' failed
make[1]: *** [deps] Error 2
make[1]: 离开目录“/root/emqx/emqx_rel/deps/emqx_retainer”
erlang.mk:339: recipe for target 'deps' failed
make: *** [deps] Error 2

这个错误是什么引起的？一直编译不过，求大神指点。

**Comment by tigercl** [comment]
@linany What is the version of the rebar script you are using？

**Comment by linany** [comment]
> 
> 
> @linany What is the version of the rebar script you are using？

rebar 3.14.2 on Erlang/OTP 21 Erts 10.3.5.13

**Comment by HJianBo** [comment]
Are you comfortable using the new emqx version? For example 4.2.3
