### ISSUE TITLE
When will it support client-side abnormal behavior detection? Such as topic scanning (request to send or subscribe to a large number of topics) and sending of undeliverable messages (topics without subscribers)

### ISSUE THREAD

**Issue by MingShanshui** [emqx/emqx#3873]
**What would you like to be added/modified**:

**Why is this needed**:

**Comment by tigercl** [comment]
@MingShanshui Thank you very much for your feedback, we will consider supporting them in version 5.0.

**Comment by zmstone** [comment]
There is ACL.
Not sure if we'll do more about it.
