### ISSUE TITLE
Emqx Cluster migration

### ISSUE THREAD

**Issue by alinanasir01** [emqx/emqx#3875]
We are migrating our Emqx cluster
Previously we used rabbitmq and that had a feature called federation for automatically populates duplicate queues on all clusters during migrations , is there any such feature available for Emqx ?

**Comment by tigercl** [comment]
@alinanasir01 Sorry, we do not support this feature for the time being. Currently we only provide the migration of data such as the rule engine. You can refer to the document: https://docs.emqx.io/broker/latest/en/advanced/data-import-and-export.html

**Comment by zmstone** [comment]
There is MQTT bridge.
