### ISSUE TITLE
Bridge emqtt to RabbitMQ

### ISSUE THREAD

**Issue by dophlin** [emqx/emqx#388]
Is that possible to bridge emqtt to RabbitMQ?
If yes, how should I point RabbitMQ node inside the bridge query?
Thanks in advance

**Comment by erylee** [comment]
hi @dophlin, it's easy to bridge to RabbitMQ, I think. I will plan this feature.

**Comment by dophlin** [comment]
Hi @erylee, that would be a great feature, it helps us to think about using emqtt in our enterprise area. Thank you.

**Comment by dophlin** [comment]
Hi @erylee, in order to bridge emqttd to rabbitmq, I started to bridge emqttd with mosquitto as a test. Since I am familiar with mosquitto I can easily bridge mosquitto with emqttd by using mosquitto configuration file but in contrast, when I try to make emqttd to bridge with mosquitto it fails. In fact, I don't know what I should replace with "emqttd2@127.0.0.1" inside emqttd_ctl command.

./bin/emqttd_ctl bridges start ???@127.0.0.1 topic/#

Do you have any idea?
Thanks

**Comment by erylee** [comment]
hi @dophlin, about bridge of the emqttd broker: http://docs.emqtt.com/en/latest/bridge.html
emqttd can only bridge to another emqttd broker, cannot bridge to mosquitto.

**Comment by dophlin** [comment]
Thank you @erylee, So it seems there is not any chance to bridge emqttd to RabbitMQ or any other Message Handler!?

**Comment by erylee** [comment]
Hi @dophlin, I plan to develop a plugin to bridge emqttd to RabbitMQ. For we decide to tag 1.0 soon, I am writing documents for the project these days. The RabbitMQ bridge will be released after 1.0 ready.

**Comment by JoeFerrucci** [comment]
The 1.0 release was two days ago :+1: I didn't see the RabbitMQ bridge. 
What's the status on that?

**Comment by amirkheirabadi** [comment]
Hi @emqplus, the current release is 2.2.
I really need Rabbit Bridge. any idea when it will be released?

**Comment by turtleDeng** [comment]
@dophlin 
emqx-enterprise support message bridge to RabbitMQ
https://www.emqx.io/downloads/emq/enterprise?osType=Linux
