### ISSUE TITLE
PUBCOMP and CONNACK spam, SUBACK with QoS 3.

### ISSUE THREAD

**Issue by ProtonGustave** [emqx/emqx#3880]
**Environment**:

- EMQ X version:  emqx 4.2.2
- Hardware: AWS EC2 instance(8gb RAM, 4 cores)
- OS: Ubuntu 18.04.3 LTS
- Kernel: Linux ip-172-31-0-6 5.4.0-1029-aws #30~18.04.1-Ubuntu SMP Tue Oct 20 11:09:25 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

**What happened and what you expected to happen**:
At some point(randomly, but in this [logs](https://github.com/emqx/emqx/files/5651269/global_alerts_logs.txt) it happened in 6 hours after start) server starts to spam client with nonsense packets. We don't use QoS 1 and 2 at application level(except start and will messages which use QoS 1), but at some point server send SUBACK with granted QoS level 3.
I don't understand few things here:
1. Why we get a SUBACK if we were just publishing from client side for last few hours, there was no disconnections, there is no some additional subscriptions at client side, just on script start.
2. QoS level 3, there is no level 3 in MQTT specs.(maybe client-side packet parser is not doing it job correct, but i see it in logs)
Then i receive a lot of CONNACK(with QoS 2, which is not good too), PUBREL, PUBCOMP... and it all ends with error on client side packet parser lib.
This is how it looks from emqx logs, a lot of messages like this:
```
2020-12-06 19:33:32.969 [warning] <<"global_alerts">>@172.31.5.119:37648 [Channel] The PUBCOMP PacketId 14882 is not found
2020-12-06 19:33:32.975 [warning] <<"global_alerts">>@172.31.5.119:37648 [Channel] The PUBCOMP PacketId 14896 is not found
```
**How to reproduce it (as minimally and precisely as possible)**:
I don't know, i just run nodejs script as usual, using last [mqtt](https://npmjs.com/package/mqtt) package available as a mqtt client. It happens for a bunch of my scripts(at least 4).
**Anything else we need to know?**:
I'm trying to gather more logs right now(from emqx side and from client script side).

**Comment by HJianBo** [comment]
This is not logical, and I suspect it is caused by one of the parties not being able to handle the TCP stream properly. For example, mqttjs cannot handle packet splitting.

While doing this experiment, would you be handy to use Wireshark/tcpdump to capture the network trafiic to see what is actually happening?
