### ISSUE TITLE
Scaling issue: in opensource not able to go beyond 1.6 to 1.8 lakh per pod/ per node

### ISSUE THREAD

**Issue by dgkirankumar** [emqx/emqx#3881]
**Environment**:

- EMQ X version (e.g. `emqx_ctl status`): emqx 4.2.3 is running
- Hardware configuration (e.g. `lscpu`): Running 3 node cluster on Google. Docker based deployment

Architecture:        x86_64
CPU op-mode(s):      32-bit, 64-bit
Byte Order:          Little Endian
CPU(s):              8
On-line CPU(s) list: 0-7
Thread(s) per core:  2
Core(s) per socket:  4
Socket(s):           1
NUMA node(s):        1
Vendor ID:           GenuineIntel
CPU family:          6
Model:               85
Model name:          Intel(R) Xeon(R) CPU @ 2.00GHz
Stepping:            3
CPU MHz:             2000.184
BogoMIPS:            4000.36
Hypervisor vendor:   KVM
Virtualization type: full
L1d cache:           32K
L1i cache:           32K
L2 cache:            1024K
L3 cache:            39424K
NUMA node0 CPU(s):   0-7
Flags:               fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse s
se2 ss ht syscall nx pdpe1gb rdtscp lm constant_tsc rep_good nopl xtopology nonstop_tsc cpuid tsc_known_freq pni pc
lmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dno
wprefetch invpcid_single pti ssbd ibrs ibpb stibp fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm mpx 
avx512f avx512dq rdseed adx smap clflushopt clwb avx512cd avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves arat md_
clear arch_capabilities

- OS (e.g. `cat /etc/os-release`):
BUILD_ID=12871.1200.0
NAME="Container-Optimized OS"
KERNEL_COMMIT_ID=c46f8a87c479cd2e964513992d3eab92eff5c160
GOOGLE_CRASH_ID=Lakitu
VERSION_ID=81
BUG_REPORT_URL="https://cloud.google.com/container-optimized-os/docs/resources/support-policy#contact_us"
PRETTY_NAME="Container-Optimized OS from Google"
VERSION=81
GOOGLE_METRICS_PRODUCT_ID=26
HOME_URL="https://cloud.google.com/container-optimized-os/docs"
ID=cos
- Kernel (e.g. `uname -a`):
Linux gke-mqtt-cluster-mqtt-2edb1332-5nmc 4.19.112+ #1 SMP Wed Sep 23 07:53:39 PDT 2020 x86_64 Intel(R) Xeon(R) CPU
 @ 2.00GHz GenuineIntel GNU/Linux
- Erlang/OTP version (in case you build emqx from source code): 22
- Others:

**What happened and what you expected to happen**:
we are doing scalability testing. we were expecting each pod should be able to hold 1 million connections

![image](https://user-images.githubusercontent.com/62382166/101348973-9203f880-38b2-11eb-9fd6-8ae543c2b023.png)

After reaching these numbers, our connections stop dropping. and pods get restarting. Dashboard becomes inaccessible. But connections are not terminated.

We are also not able to go beyond this number(1.6 lakh to 1.8 lakh connections)

**How to reproduce it (as minimally and precisely as possible)**:
 1. Launch a cluster of three machines ( 8 core, 50 GB ubuntu machines)
 2. Docker based deployment to this cluster.(max 3 pods)
 3. Run the mqtt bench ( 100 nodes, 100 pods / node, 700 connections/pod)

**Anything else we need to know?**:

**Comment by HJianBo** [comment]
Have you tuned the container host machine according to this tutorial? https://docs.emqx.io/en/broker/latest/tutorial/tune.html#linux-kernel-tuning

**Comment by dgkirankumar** [comment]
In vm we have done all the parameter tuning. On individual machine we were able to scale. But when we deploy through docker image in K8s cluster(all the cluster vms are tuned as per guidelines) it hit the limitation of 1.6-1.8 lakh per node
