### ISSUE TITLE
PHP Script reading on emqx cluster

### ISSUE THREAD

**Issue by tpharaoh** [emqx/emqx#3884]
I hope the setup is clear...

I have a load balancer, and currently 2 servers behind it. each server has nginx, php, symfony console command

Load balancer is using nginx stream to balance between my webservers, and I was able to use it to load balance between the 2 emqx instances.

Scenario 1:
Client > Load Balancer > emqx1 (which syncs to emqx2)
*symfony php is designed to read from mqtt localhost and run some calculations and insert into a DB. Qestion: if emqx syncs to both instances, won't there be a duplicate here? Or can I specify certain paths to NOT Sync? ideally: /incoming/client_id would not need to sync

Scenario 2:
Symfony PHP Cron Job > Publishes to mqtt, syncronizes. now all nodes have the data. Lets assume /outgoing/client_id
Now client connects via load balancer and can be on any node, so he will get the data. This part seems to work as expencted

So, my main worry is scenario 1. How to ensure the PHP script does not get duplicates. It seems if the /incoming path is not syncronized I would not have an issue. Is there something else I should try?

**Comment by tpharaoh** [comment]
https://docs.emqx.io/en/broker/latest/advanced/retransmission.html#message-sequence

sorry for my ignorance, but if I subscribe with QoS 0, it would only pick up those which were sent to this insance right?

**Comment by HJianBo** [comment]
emqx is a message broker server, and all messages to emqx1 may be routed to emqx2 as long as a client on emqx2 is subscribed to the topic.

**Comment by HJianBo** [comment]
So don't worry. As long as the messages on your topic are not duplicated, and as long as only one subscriber is receiving the messages and writing them to the database, the messages will not be duplicated.

However, if you have multiple subscribers to `incoming/x/y/z`, then all subscribers will receive each message on the topic, regardless of which node the subscriber is connected to.

If you only need one of the subscribers to receive messages, then you need to use the shared subscriptions. see: https://docs.emqx.io/en/broker/latest/advanced/shared-subscriptions.html
