### ISSUE TITLE
Cannot receive messages republished by rule engine in shared subscription mode

### ISSUE THREAD

**Issue by kevinmakui** [emqx/emqx#3889]
Env: EMQX 4.1.0, CentOS 7.6

Rule engine republishes messages to topic some/topic, clients can receive messages from some/topic but not from $shared/g/some/topic or $queue/some/topic. Shared subscription works well with messages published by normal MQTT client(MQTTX, mqtt.fx etc.)

somebody can help?

**Comment by terry-xiaoyu** [comment]
@tigercl The shared subscriptions are prefixed by `$share/` not `$shared/`.

I tested it just now with the latest emqx and works well.

**Comment by kevinmakui** [comment]
Sorry, it was $share/g/some/topic. Upgraded to 4.2.3, it works now. thanks!
