### ISSUE TITLE
ACL: "You have an error in your SQL syntax" but SQL query runs fine on database

### ISSUE THREAD

**Issue by AlexGodbehere** [emqx/emqx#3890]
I'm trying to configure ACLs using the MySQL extension. I have EMQX running using docker and my `docker-compose.yml` file defines the ACL rules as follows:

```
 # ACL
EMQX_ALLOW_ANONYMOUS: "false"
EMQX_AUTH__MYSQL__ACL_QUERY: "select true as allow, null as ipaddr, '%u' as username, null as clientid, (mqtt_auth.acl_roles.rw & 3) as access, replace(mqtt_auth.acl_roles.topic,'%g',mqtt_auth.groups.name) as topic from mqtt_auth.nodes inner join mqtt_auth.acl_roles on mqtt_auth.nodes.role_id=mqtt_auth.acl_roles.role_id inner join mqtt_auth.groups on mqtt_auth.groups.id = mqtt_auth.nodes.group_id where mqtt_auth.nodes.username='%u';"
EMQX_ENABLE_ACL_CACHE: 'off'
EMQX_ACL_CACHE_TTL: '30s'
EMQX_ACL_NOMATCH: deny
```

The query runs fine if I run it directly against the database as follows:

```sql
select true as allow, null as ipaddr, 'testnode' as username, null as clientid, (mqtt_auth.acl_roles.rw & 3) as access, replace(mqtt_auth.acl_roles.topic,'%g',mqtt_auth.groups.name) as topic from mqtt_auth.nodes inner join mqtt_auth.acl_roles on mqtt_auth.nodes.role_id=mqtt_auth.acl_roles.role_id inner join mqtt_auth.groups on mqtt_auth.groups.id = mqtt_auth.nodes.group_id where mqtt_auth.nodes.username='testnode';
```
![image](https://user-images.githubusercontent.com/6726523/101602676-625e0900-39f6-11eb-8008-148262961757.png)

But I get an error from EMQX when trying to subscribe to a topic

```
<<"You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'auth.mysql.acl_query = select true as allow, null as ipaddr, ? as username, null' at line 1">>
```

Unfortunately the log output seems to cut off the entire query so I can't see what it's complaining about. I'm stumped because the query is valid and runs successfully in isolation. Have I got any errors with substitutions?

**Comment by wwhai** [comment]
> I'm trying to configure ACLs using the MySQL extension. I have EMQX running using docker and my `docker-compose.yml` file defines the ACL rules as follows:
> 
> ```
>  # ACL
> EMQX_ALLOW_ANONYMOUS: "false"
> EMQX_AUTH__MYSQL__ACL_QUERY: "select true as allow, null as ipaddr, '%u' as username, null as clientid, (mqtt_auth.acl_roles.rw & 3) as access, replace(mqtt_auth.acl_roles.topic,'%g',mqtt_auth.groups.name) as topic from mqtt_auth.nodes inner join mqtt_auth.acl_roles on mqtt_auth.nodes.role_id=mqtt_auth.acl_roles.role_id inner join mqtt_auth.groups on mqtt_auth.groups.id = mqtt_auth.nodes.group_id where mqtt_auth.nodes.username='%u';"
> EMQX_ENABLE_ACL_CACHE: 'off'
> EMQX_ACL_CACHE_TTL: '30s'
> EMQX_ACL_NOMATCH: deny
> ```
> 
> The query runs fine if I run it directly against the database as follows:
> 
> ```sql
> select true as allow, null as ipaddr, 'testnode' as username, null as clientid, (mqtt_auth.acl_roles.rw & 3) as access, replace(mqtt_auth.acl_roles.topic,'%g',mqtt_auth.groups.name) as topic from mqtt_auth.nodes inner join mqtt_auth.acl_roles on mqtt_auth.nodes.role_id=mqtt_auth.acl_roles.role_id inner join mqtt_auth.groups on mqtt_auth.groups.id = mqtt_auth.nodes.group_id where mqtt_auth.nodes.username='testnode';
> ```
> 
> ![image](https://user-images.githubusercontent.com/6726523/101602676-625e0900-39f6-11eb-8008-148262961757.png)
> 
> But I get an error from EMQX when trying to subscribe to a topic
> 
> ```
> <<"You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'auth.mysql.acl_query = select true as allow, null as ipaddr, ? as username, null' at line 1">>
> ```
> 
> Unfortunately the log output seems to cut off the entire query so I can't see what it's complaining about. I'm stumped because the query is valid and runs successfully in isolation. Have I got any errors with substitutions?

Can you try `emqx console` and show console log for us?

**Comment by AlexGodbehere** [comment]
Trying to run the `console` gives me the following error:
```
/opt/emqx $ emqx consol
Usage: emqx {start|start_boot <file>|ertspath|foreground|stop|restart|reboot|pid|ping|console|console_clean|console_boot <file>|attach|remote_console|upgrade|downgrade|install|uninstall|versions|escript|rpc|rpcterms|eval|root_dir}
/opt/emqx $ emqx console
Exec: /opt/emqx/erts-10.7.2.1/bin/erlexec -boot /opt/emqx/releases/4.2.3/emqx -mode embedded -boot_var ERTS_LIB_DIR /opt/emqx/erts-10.7.2.1/../lib -mnesia dir "/opt/emqx/data/mnesia/factoryplus_emqx@10.0.1.72" -config /opt/emqx/data/configs/app.2020.12.10.09.22.51.config -args_file /opt/emqx/data/configs/vm.2020.12.10.09.22.51.args -vm_args /opt/emqx/data/configs/vm.2020.12.10.09.22.51.args -start_epmd false -epmd_module ekka_epmd -proto_dist ekka -- console
Root: /opt/emqx
/opt/emqx
Protocol 'ekka': register/listen error: eaddrinuse
```

**Comment by AlexGodbehere** [comment]
It turns out that `emqx stop` needs to be called before `emqx console`. Once the console is running and I attempt to subscribe to the topic, the same error is output to the console:

```
(emqx@127.0.0.1)1> 2020-12-10 09:26:29.740 [error] <<"mqttx_6615ad5f">>@143.167.166.70:59297 [MySQL] do_check_acl error: {1064,<<"42000">>,<<"You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'auth.mysql.acl_query = select true as allow, null as ipaddr, ? as username, null' at line 1">>}
```

**Comment by wwhai** [comment]
> 42000

**Comment by AlexGodbehere** [comment]
Hi @wwhai. Thanks for the suggestion but after changing null to `null` still results in the same error. For completeness, my query is now:

```sql
EMQX_AUTH__MYSQL__ACL_QUERY: "select true as allow, `null` as ipaddr, '%u' as username, `null` as clientid, (mqtt_auth.acl_roles.rw & 3) as access, replace(mqtt_auth.acl_roles.topic,'%g',mqtt_auth.groups.name) as topic from mqtt_auth.nodes inner join mqtt_auth.acl_roles on mqtt_auth.nodes.role_id=mqtt_auth.acl_roles.role_id inner join mqtt_auth.groups on mqtt_auth.groups.id = mqtt_auth.nodes.group_id where mqtt_auth.nodes.username='%u';"
```

And to re-iterate, the query runs fine when running directly against the database as above.

**Comment by AlexGodbehere** [comment]
Ok, I've narrowed this down to the `(mqtt_auth.acl_roles.rw & 3)` portion of the query, or more specifically accessing the field on the joined table. If I reduce the query to the following then the ACL works as expected.

```sql
select 1 as allow, NULL as ipaddr, '%u' as username, NULL as clientid, 3 as access, '/test' as topic from nodes inner join acl_roles on nodes.role_id=acl_roles.role_id
```

As soon as I replace `3` with `acl_roles.rw` I get the same error. Has anyone had the ACL query working using a relationship before?

**Comment by wwhai** [comment]
> Ok, I've narrowed this down to the `(mqtt_auth.acl_roles.rw & 3)` portion of the query, or more specifically accessing the field on the joined table. If I reduce the query to the following then the ACL works as expected.
> 
> ```sql
> select 1 as allow, NULL as ipaddr, '%u' as username, NULL as clientid, 3 as access, '/test' as topic from nodes inner join acl_roles on nodes.role_id=acl_roles.role_id
> ```
> 
> As soon as I replace `3` with `acl_roles.rw` I get the same error. Has anyone had the ACL query working using a relationship before?

What the `acl_roles.rw` type, and can show your sql for us?

**Comment by AlexGodbehere** [comment]
The `acl_roles.rw` column is a `tinyint` containing `5` and `7`s. Adding a new column named `emqx_rw` containing `1` and `3s` fixed it. Looks like `(mqtt_auth.acl_roles.rw & 3)` was the culprit.
