### ISSUE TITLE
Reason for termination = error:badarg

### ISSUE THREAD

**Issue by blue-aurora** [emqx/emqx#3891]
Environment
OS: CentOS7 64bit
Erlang/OTP:
EMQ: v3.2.7

My emqx consumer service was suddenly disconnected from eqmx, and it took 20 minutes to reconnect to emqx.
My consumer's QoS = 1, but all the data was lost during the loss of connection.
This is the exception log：

2020-12-09 08:12:53.238 [error] <<"consumer_account">>@xx.xxx.xxx.xxx:52398 ** State machine <0.14478.4059> terminating
** Last event = {info,
                    {deliver,
                        [{publish,19121,
                             {message,
                                 <<0,5,181,252,235,162,141,247,137,63,245,0,
                                   117,10,0,0>>,
                                 1,emqx_mod_presence,
                                 #{dup => false,retain => false,sys => true},
                                 #{allow_publish => true},
                              
                                 {1607,472773,238274}}}]}}
** When server state  = {connected,
                            {state,esockd_transport,#Port<0.250784773>,
                                {{xx,xx,xxx,245},52398},
                                undefined,running,300,
                                {pstate,external,
                                    #Fun<emqx_channel.1.118122990>,
                                    {{172,16,4,159},1883},
                                    {{xx,xx,xxx,245},52398},
                                    nossl,3,<<"MQIsdp">>,
                                    <<"consumer_account">>,false,
                                    <0.14478.4059>,undefined,undefined,
                                    <<"consumer_account">>,<0.15956.3772>,
                                    false,#{},undefined,undefined,80,false,
                                    #{msg => 0,pkt => 2059587564},
                                    #{msg => 2059587567,pkt => 2059587569},
                                    true,
                                    {1602,31613,649881},
                                    #{from_client => 0,to_client => 0},
                                    emqx_channel,
                                    #{anonymous => false,
                                      auth_result => success,
                                      client_id => <<"consumer_account">>,
                                      is_superuser => false,
                                      mountpoint => undefined,
                                      peername => {{xx,xx,xxx,245},52398},
                                      sockname => {{172,16,4,159},1883},
                                      username => <<"consumer_account">>,
                                      ws_cookie => undefined,zone => external},
                                    undefined},
                                {none,#{max_size => 3145728,version => 3}},
                                {emqx_gc,
                                    #{cnt => {80000,35567},
                                      oct => {314572800,312880411}}},
                                {keepalive,#Fun<emqx_channel.4.118122990>,
                                    8238309451,60,
                                    {keepalive,check},
                                    #Ref<0.1272251979.1863319554.88850>,0},
                                undefined,undefined,undefined,true,
                                #Ref<0.1272251986.3652452353.120143>,600000}}
** Reason for termination = error:badarg
** Callback mode = [state_functions,state_enter]
** Stacktrace =
**  [{erlang,byte_size,
             
             []},
     {emqx_frame,serialize_utf8_string,1,
                 [{file,"/emqx_temp/emqx_rel/_checkouts/emqx/src/emqx_frame.erl"},
                  {line,636}]},
     {emqx_frame,serialize_variable,2,
                 [{file,"/emqx_temp/emqx_rel/_checkouts/emqx/src/emqx_frame.erl"},
                  {line,458}]},
     {emqx_frame,serialize,2,
                 [{file,"/emqx_temp/emqx_rel/_checkouts/emqx/src/emqx_frame.erl"},
                  {line,396}]},
     {emqx_channel,'-do_init/3-fun-0-',4,
                   [{file,"/emqx_temp/emqx_rel/_checkouts/emqx/src/emqx_channel.erl"},
                    {line,169}]},
     {emqx_protocol,send,2,
                    [{file,"/emqx_temp/emqx_rel/_checkouts/emqx/src/emqx_protocol.erl"},
                     {line,708}]},
     {emqx_protocol,deliver,2,
                    [{file,"/emqx_temp/emqx_rel/_checkouts/emqx/src/emqx_protocol.erl"},
                     {line,610}]},
     {emqx_channel,connected,3,
                   [{file,"/emqx_temp/emqx_rel/_checkouts/emqx/src/emqx_channel.erl"},
                    {line,245}]}]

2020-12-09 08:12:53.933 [error] <<"consumer_account">>@xx.xxx.xxx.xxx:48758 ** State machine <0.13958.7735> terminating

**Comment by tigercl** [comment]
@blue-aurora It seems that there may be some special characters in your Payload that cause the message serialization to fail. In addition, if you want to get messages during the disconnection after reconnecting, it is recommended to use a persistent session, that is, specify Clean Start or Clean Session as true when connecting.
