### ISSUE TITLE
 Hash Sum mismatch

### ISSUE THREAD

**Issue by bulolo** [emqx/emqx#3908]
Err:8 https://repos.emqx.io/emqx-ce/deb/ubuntu ./xenial/stable amd64 Packages
  Hash Sum mismatch
Fetched 8,837 B in 2s (3,836 B/s)
Reading package lists... Done
E: Failed to fetch https://repos.emqx.io/emqx-ce/deb/ubuntu/dists/./xenial/stable/binary-amd64/Packages.gz  Hash Sum mismatch
E: Some index files failed to download. They have been ignored, or old ones used instead.

**Comment by zhanghongtong** [comment]
Hi, @bulolo 
Please provide your operation steps, server system version and other information

**Comment by Rory-Z** [comment]
This issue has not been updated for a long time, I will close it, if there are any problems, you can open it at any time
