### ISSUE TITLE
Dashboard Metrics reset after restart

### ISSUE THREAD

**Issue by berayb** [emqx/emqx#3910]
How to persist dashboard metrics to prevent data loss after broker restart?

**Comment by tigercl** [comment]
@berayb We do not support the persistence of these data for the time being. Would you please tell us why you need this feature? We will seriously evaluate its importance.

**Comment by berayb** [comment]
@tigercl Thanks, we use the metrics for BI purposes for our business. Even though we collect the information from broker periodically, it may cause a loss of data.

**Comment by HJianBo** [comment]
Hi @berayb You can use the `emqx_statsd` or `emqx_promethus` plugin to push these metrics data into your data analysis system
