### ISSUE TITLE
Failed to start when configuring mysql authentication, prompt auth_method,<<"caching_sha2_password">>},  [{mysql_protocol,build_handshake_response,5,

### ISSUE THREAD

**Issue by iot1688** [emqx/emqx#3911]
#### Environment

- OS: windows server 2012R2 64位
- Erlang/OTP: 
- EMQ: emqx-windows-4.2.2
- mysql:mysql-8.0.22-winx64

#### Description
你好，配置mysql认证一直无法启动，提示如下失败：
{emqx_auth_mysql, {bad_return, {{emqx_auth_mysql_app,start,[normal,[]]}, {'EXIT', {{badmatch, {error, {shutdown, {failed_to_start_child,emqx_auth_mysql,
 {shutdown, {failed_to_start_child,worker_sup, {shutdown, {failed_to_start_child, {worker,1}, {{auth_method,<<"caching_sha2_password">>}, 
[{mysql_protocol,build_handshake_response,5, [{file, "d:/a/emqx-rel/emqx-rel/_build/emqx/lib/mysql/src/mysql_protocol.erl"}, {line,386}]}, 
{mysql_protocol,handshake,7, [{file, "d:/a/emqx-rel/emqx-rel/_build/emqx/lib/mysql/src/mysql_protocol.erl"}, {line,72}]}, {mysql_conn,init,1,
 [{file, "d:/a/emqx-rel/emqx-rel/_build/emqx/lib/mysql/src/mysql_conn.erl"}, {line,111}]}, {gen_server,init_it,2,[{file,"gen_server.erl"},{line,374}]}, {gen_server,init_it,6,
[{file,"gen_server.erl"},{line,342}]}, {proc_lib,init_p_do_apply,3, [{file,"proc_lib.erl"},{line,249}]}]}}}}}}}}}, [{emqx_auth_mysql_app,start,2, 
[{file, "d:/a/emqx-rel/emqx-rel/_build/emqx/lib/emqx_auth_mysql/src/emqx_auth_mysql_app.erl"}, {line,38}]}, {application_master,start_it_old,4,
 [{file,"application_master.erl"},{line,277}]}]}}}}}

-----
参考MySQL认证这章节配置过程配置了emq的参数，mysql里也配置成了mysql_native_password
二者均重启过多次，也卸载过重装这两个服务，一直提示无法启动MySQL认证。

麻烦帮忙分析，感谢！

![QQ图片20201214092955](https://user-images.githubusercontent.com/66653296/102030779-f82ad700-3dee-11eb-916b-744add307c67.jpg)

**Comment by HJianBo** [comment]
This post maybe help you https://docs.emqx.cn/cn/broker/latest/faq/error.html#emq-x-无法连接-mysql-8-0

**Comment by iot1688** [comment]
@HJianBo 你好，这篇文章昨天参考过了

**Comment by HJianBo** [comment]
Cound you try to telnet the mysql port? e.g: 
```
telnet 127.0.0.1 3306
```

What's the output for this cmd?

**Comment by iot1688** [comment]
@HJianBo 使用Navicat 15 for MySQL这个工具可以正常使用3306
![微信图片_20201215173918](https://user-images.githubusercontent.com/66653296/102197995-d15ac680-3efc-11eb-818d-808f9a822a40.png)

**Comment by HJianBo** [comment]
My guess is that it may be because your mysql service configuration has not been changed correctly.

Can you run the telnet command you mentioned last time? It will output some useful information after a successful connection.

**Comment by iot1688** [comment]
> 我的猜测是，这可能是因为您的mysql服务配置未正确更改。
> 
> 您可以运行上次提到的telnet命令吗？连接成功后，它将输出一些有用的信息。

你好，刚过去试了下，返回J
caching_sha2_passwordM&'sl]
这个，这种要怎么配置掉？查数据库情况显示的确是native密码方式，按你说的验证缺还是caching的方式。
这哪步出问题了呢？配置是按文档的配置的

**Comment by iot1688** [comment]
重装了下系统，插件密码终于换过来了
