### ISSUE TITLE
【http api】api/v4/subscriptions

### ISSUE THREAD

**Issue by vincentchivas** [emqx/emqx#3912]
I use "api/v4/subscriptions" to get subscriptions.
 curl -i --basic -u admin:public -X GET "http://localhost:8081/api/v4/subscriptions?_page=1&_limit=10"
can get:
{"meta":{"page":1,"limit":10,"hasnext":false,"count":2},"data":[{"topic":"groupCode/p4201112007280372/device/+/+/alarm","qos":1,"node":"emqx@127.0.0.1","clientid":"web-b1fb7449-b831-4c11-a945-5f6fa50b5c4e"},{"topic":"groupCode/p4201112007280372/device/1/2/alarm","qos":1,"node":"emqx@127.0.0.1","clientid":"web-b1fb7449-b831-4c11-a945-5f6fa50b5c4e"}],"code":0}

and when I use "topic" parameter query, I get empty result.  I have test that when topic contains "+" pattern，query result got nothing.
curl -i --basic -u admin:public -X GET "http://localhost:8081/api/v4/subscriptions?_page=1&_limit=10&topic=groupCode/p4201112007280372/device/+/+/alarm"
{"data":[],"code":0}

**Environment**:

- EMQ X version (e.g. `emqx_ctl status`): 4.2.3
- Hardware configuration (e.g. `lscpu`):
- OS (e.g. `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Erlang/OTP version (in case you build emqx from source code): 
- Others:

**What happened and what you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Comment by HJianBo** [comment]
This is because you don't urlencode the topic parameter. `+` should be replaced with `%2b`. Just like:
```
curl -i --basic -u admin:public -X GET "http://localhost:8081/api/v4/subscriptions？_page=1&_limit=10&topic=groupCode/p4201112007280372/device/%2b/%2b/alarm"
```
