### ISSUE TITLE
Websocket messages are getting dropped

### ISSUE THREAD

**Issue by Sayanc93** [emqx/emqx#3920]
We have bi-directional traffic and have been trying emqx as broker. 
Our clients establishes websocket connections to broker via AWS ALB and our game engine subscribes to broker via TCP.

Game engine subscribes to about 1200 topics for multi-cast subscriptions when game starts it subscribes to each player's MQTT topics for unicast broadcasts.

We've been perf-testing on one c5.4xlarge machine with maxed out emqx.conf on ws/tcp external configurations since we didn't notice emqx taking too much CPU on load testing.

We have tuned our machine according to tuning guide on MQTT docs

On perf-testing, we found MQTT connections scaling fine but broker dropping messages drastically and also adding latencies, although the connections are being maintained fine

the websocket configs are these- 
```
listener.ws.external.acceptors = 100
listener.ws.external.max_connections = 1024000
listener.ws.external.max_conn_rate = 100000
listener.ws.external.active_n = 10000
listener.ws.external.recbuf = 10MB
listener.ws.external.sndbuf = 10MB
listener.ws.external.buffer = 10MB
```

We have similar configuration for tcp.external.

Is it because we're just using one node for bi-directional traffic that it can't take the load? 

We've been testing with burst traffic of 2k and 20k users on WS port. It's dropping messages for both the numbers

**Comment by tigercl** [comment]
@Sayanc93 Is it convenient for you to tell me which version of emqx you use and how often each user sends messages? In addition, too large a value of acceptors may have a negative impact on performance. It is usually recommended to configure it to the same size as your CPU core.

**Comment by Sayanc93** [comment]
Hi @tigercl thanks for the reply. We're using the latest stable version of emqx which is v4.2.4. Your input on acceptor pool is helpful. Do you think that might be the reason for this?

**Comment by tigercl** [comment]
@Sayanc93 The reason for discarding messages may be that the number of messages accumulated on the connection has exceeded the maximum length of the message queue. You can check the current message queue length of the client on the client details page of the Dashboard. Usually this problem is caused by slow reception at the subscriber.
