### ISSUE TITLE
Document bug

### ISSUE THREAD

**Issue by hehejiuhuizhe** [emqx/emqx#3924]
In   https://docs.emqx.cn/cn/broker/latest/advanced/http-api.html#%E6%8E%A5%E5%8F%A3%E5%AE%89%E5%85%A8 .It says "默认的 AppID 和 AppSecret 是：amdin/public", the "amdin" shoud be "admin"

**Comment by hehejiuhuizhe** [comment]
The english version has the same problem.

**Comment by tigercl** [comment]
@hehejiuhuizhe Thank you very much for your feedback, we will correct it as soon as possible.
