### ISSUE TITLE
EMQX

### ISSUE THREAD

**Issue by mntolia** [emqx/emqx#3932]
**Environment**:

- EMQ X version (e.g. `emqx_ctl status`): 4.2.0 & 4.2.4
- Hardware configuration (e.g. `lscpu`): x86_64
- OS (e.g. `cat /etc/os-release`): CentOS Linux 7
- Kernel (e.g. `uname -a`): Linux kwikpay-test-server-do-26oct-1603750894133 3.10.0-1127.10.1.el7.x86_64 #1 SMP Wed Jun 3 14:28:03 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

Getting this error while starting EMQX:
Redirecting to /bin/systemctl status emqx.service
● emqx.service - emqx daemon
   Loaded: loaded (/usr/lib/systemd/system/emqx.service; enabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Thu 2020-12-17 12:31:47 UTC; 6min ago

Dec 17 12:31:45 kwikpay-test-server-do-26oct-1603750894133 systemd[1]: Starting emqx daemon...
Dec 17 12:31:47 kwikpay-test-server-do-26oct-1603750894133 systemd[1]: emqx.service: control process exited, code=exited status=1
Dec 17 12:31:47 kwikpay-test-server-do-26oct-1603750894133 systemd[1]: Failed to start emqx daemon.
Dec 17 12:31:47 kwikpay-test-server-do-26oct-1603750894133 systemd[1]: Unit emqx.service entered failed state.
Dec 17 12:31:47 kwikpay-test-server-do-26oct-1603750894133 systemd[1]: emqx.service failed.

Tried both version 4.2.0 & 4.2.4. The EMQX server is not starting. I am using root user.

**Comment by tigercl** [comment]
@mntolia What is the output when you start it with the `./emqx console` command?

**Comment by mntolia** [comment]
> @mntolia What is the output when you start it with the `./emqx console` command?

```
[root@kwikpay-test-server-do-26oct-1603750894133 prashant.s]# emqx
Usage: emqx {start|start_boot <file>|ertspath|foreground|stop|restart|reboot|pid|ping|console|console_clean|console_boot <file>|attach|remote_console|upgrade|downgrade|install|uninstall|versions|escript|rpc|rpcterms|eval|root_dir}
[root@kwikpay-test-server-do-26oct-1603750894133 prashant.s]#
```

**Comment by HJianBo** [comment]
Hi @mntolia Please execute `emqx console` instead of `emqx`

**Comment by mntolia** [comment]
Hi @HJianBo @tigercl ,
I managed to get it to start after reinstalling and restarting it a few times. But the rule engine is not starting in the dashboard. I am getting this error:
```
{emqx_rule_engine, {bad_return, {{emqx_rule_engine_app,start,[normal,[]]}, {'EXIT', {{bad_type, {action,data_to_mqtt_broker,'message.publish', emqx_bridge_mqtt, [bridge_mqtt,bridge_rpc], emqx_bridge_mqtt_actions, on_action_create_data_to_mqtt_broker,undefined,false, #{'$resource' => #{description => #{en => <<"Bind a resource to this action">>, zh => <<231,187,153,229,138,168,228,189,156, 231,187,145,229,174,154,228,184,128, 228,184,170,232,181,132,230,186,144>>}, required => true, title => #{en => <<"Resource ID">>, zh => <<232,181,132,230,186,144,32,73,68>>}, type => string}, payload_tmpl => #{default => <<>>, description => #{en => <<"The payload template, variable interpolation is supported. If using empty template (default), then the payload will be all the available vars in JOSN format">>, zh => <<230,182,136,230,129,175,229,134,133, 229,174,185,230,168,161,230,157,191, 239,188,140,230,148,175,230,140,129, 229,143,152,233,135,143,227,128,130, 232,139,165,228,189,191,231,148,168, 231,169,186,230,168,161,230,157,191, 239,188,136,233,187,152,232,174,164, 239,188,137,239,188,140,230,182,136, 230,129,175,229,134,133,229,174,185, 228,184,186,32,74,83,79,78,32,230, 160,188,229,188,143,231,154,132,230, 137,128,230,156,137,229,173,151,230, 174,181>>}, input => textarea,order => 1,required => false, title => #{en => <<"Payload Template">>, zh => <<230,182,136,230,129,175,229,134,133, 229,174,185,230,168,161,230,157,191>>}, type => string}}, #{en => <<"Data bridge to MQTT Broker">>, zh => <<230,161,165,230,142,165,230,149,176,230,141,174, 229,136,176,32,77,81,84,84,32,66,114,111,107, 101,114>>}, #{en => <<"Bridge Data to MQTT Broker">>, zh => <<230,161,165,230,142,165,230,149,176,230,141, 174,229,136,176,32,77,81,84,84,32,66,114,111, 107,101,114>>}}}, [{emqx_rule_registry,trans,2, [{file, "/emqx-rel/_build/emqx-pkg/lib/emqx_rule_engine/src/emqx_rule_registry.erl"}, {line,425}]}, {emqx_rule_engine,load_provider,1, [{file, "/emqx-rel/_build/emqx-pkg/lib/emqx_rule_engine/src/emqx_rule_engine.erl"}, {line,78}]}, {emqx_rule_engine,'-load_providers/0-lc$^0/1-0-',1, [{file, "/emqx-rel/_build/emqx-pkg/lib/emqx_rule_engine/src/emqx_rule_engine.erl"}, {line,73}]}, {emqx_rule_engine,load_providers,0, [{file, "/emqx-rel/_build/emqx-pkg/lib/emqx_rule_engine/src/emqx_rule_engine.erl"}, {line,73}]}, {emqx_rule_engine_app,start,2, [{file, "/emqx-rel/_build/emqx-pkg/lib/emqx_rule_engine/src/emqx_rule_engine_app.erl"}, {line,31}]}, {application_master,start_it_old,4, [{file,"application_master.erl"},{line,277}]}]}}}}}
```

**Comment by terry-xiaoyu** [comment]
Remove all the dir and files under `data/mnesia/` directory of you emqx's installation path.

**Comment by HJianBo** [comment]
It looks like it's already an expired issue, so I'll go ahead and close it. 
Please feel free to open it If there are any updates.
