### ISSUE TITLE
Connect RIOT-OS client to MQTT-SN (using IPv6)

### ISSUE THREAD

**Issue by thanosmanolis** [emqx/emqx#3945]
**Environment**

- OS: Arch Linux
- Erlang/OTP: R22/10.7
- EMQ: v4.2.4
 
**Description**
Hello, I am new to IOT in general so it is surely a newbie question. I am trying to connect a RIOT-OS MQTT-SN client to the emqx broker using [this](https://github.com/RIOT-OS/RIOT/tree/master/examples/emcute_mqttsn) example. This link has instructions for the [Mosquitto RSMB](https://github.com/eclipse/mosquitto.rsmb), so I tried to apply the same configuration for EMQX-SN gateway and I failed.

I want to connect using port 1885 for MQTT-SN and 1886 for MQTT and also enabling IPv6. I tried doing the following changes to the config files but it still won't connect. I would really appreciate if you could show me my mistake, or maybe something I should have read first before even trying to do it? 

Here are the changes I made to the config files:

**emqx.conf**
node.proto_dist = inet6_tcp
listener.tcp.external= ::1:1886
listener.tcp.external.reuseaddr = true

**plugins/emqx_sn.conf**
mqtt.sn.port = ::1:1885

I've also tried many other changes I saw in other issues about enabling IPv6 but with no luck whatsoever. For example I also tried setting _node.name = emqx@::1_ but when I do that emqx won't start.

**Comment by wwhai** [comment]
> **Environment**
> 
> * OS: Arch Linux
> * Erlang/OTP: R22/10.7
> * EMQ: v4.2.4
> 
> **Description**
> Hello, I am new to IOT in general so it is surely a newbie question. I am trying to connect a RIOT-OS MQTT-SN client to the emqx broker using [this](https://github.com/RIOT-OS/RIOT/tree/master/examples/emcute_mqttsn) example. This link has instructions for the [Mosquitto RSMB](https://github.com/eclipse/mosquitto.rsmb), so I tried to apply the same configuration for EMQX-SN gateway and I failed.
> 
> I want to connect using port 1885 for MQTT-SN and 1886 for MQTT and also enabling IPv6. I tried doing the following changes to the config files but it still won't connect. I would really appreciate if you could show me my mistake, or maybe something I should have read first before even trying to do it?
> 
> Here are the changes I made to the config files:
> 
> **emqx.conf**
> node.proto_dist = inet6_tcp
> listener.tcp.external= ::1:1886
> listener.tcp.external.reuseaddr = true
> 
> **plugins/emqx_sn.conf**
> mqtt.sn.port = ::1:1885
> 
> I've also tried many other changes I saw in other issues about enabling IPv6 but with no luck whatsoever. For example I also tried setting _node.name = emqx@::1_ but when I do that emqx won't start.

Unfortunately, Ipv6 is not supported at current, But we will add this feature in next version , Please keep your  attention to next version.

**Comment by thanosmanolis** [comment]
Oh ok, I though that IPv6 was supported since v3.2.4 but I guess not for the MQTT-SN gateway? Thanks for the reply anyway, should I leave this issue open?

**Comment by wwhai** [comment]
> > Unfortunately, Ipv6 is not supported at current, But we will add this feature in next version , Please keep your attention to next version.
> 
> Oh ok, I though that IPv6 was supported since v3.2.4 but I guess not for the MQTT-SN gateway? Thanks for the reply anyway. Should I resolve this issue?

Ok, you can close it.
