### ISSUE TITLE
Can the data be returned synchronously

### ISSUE THREAD

**Issue by yuehuaxw** [emqx/emqx#3953]
**Please describe your problem in detail, if necessary, you can upload the log file through the attachment**:
当使用MQTT时，如何做到数据的同步返回？

**Comment by tigercl** [comment]
@yuehuaxw Sorry I didn’t understand what you mean, can you describe your needs more specifically.

**Comment by yuehuaxw** [comment]
> @yuehuaxw对不起，我不明白您的意思，能否更具体地描述您的需求。

你好，目前我的需求为：

**Comment by yuehuaxw** [comment]
> @yuehuaxw对不起，我不明白您的意思，能否更具体地描述您的需求。

感谢您在百忙中可以回复我的信息，目前我的需求为：客户端向物联网硬件设备发起请求，期望通过EMQ的MQTT协议来实现数据的同步返回， 而并非异步轮询获取请求结果

**Comment by HJianBo** [comment]
Sorry, but in essence, MQTT as a PUB/SUB protocol does not support this synchronous Request/Response mode.

You need your own layer of encapsulation on top of that.

**Comment by yuehuaxw** [comment]
Thank You

JianBo He <notifications@github.com> 于2020年12月25日周五 下午7:25写道：
