### ISSUE TITLE
A question about ACL placeholders

### ISSUE THREAD

**Issue by 88888888888888888888** [emqx/emqx#3954]
**Please describe your problem in detail, if necessary, you can upload the log file through the attachment**:
情况是这样的,我想ACL有一个特殊的需求,不可以使用用户名也可以使用clientID,用一个数据库的另外的新增字段来做ACL那么没有这样的占位符,我该如何构建一个属于我自己的占位符

**Comment by 88888888888888888888** [comment]
大概就是我该如何构建一个自定义的ACL占位符

**Comment by tigercl** [comment]
@88888888888888888888 We are sorry that we do not support you to do this at present, if you really want a placeholder that you define yourself, you need to modify the source code.

**Comment by 88888888888888888888** [comment]
Ok, thank you.
