### ISSUE TITLE
The CPU went up but couldn't get off

### ISSUE THREAD

**Issue by linany** [emqx/emqx#3956]
Environment

    OS: Ubuntu 18.04.5 LTS
    Erlang/OTP:
    EMQ: emqx v3.1.2
Description

Emqx ran normally for two days, with CPU usage around 30% and the number of connected devices unchanged.All of a sudden it hits a problem and the CPU goes up to 150% and never gets off.How do I troubleshoot this problem?
 `2020-12-23 17:52:30.679 [error] candtu-200:CC039E2865DFD4A13B0F@117.136.15.233:56292 [Connection] Parse failed for function_clause
Stacktrace:[{emqx_frame,parse_packet,
                        [{mqtt_packet_header,12,true,2,true},
                         <<34,168,187,227,138,28,116,185,206,59,172,231,146,
                           201,121,119,92,157,70,221,29,215,36,83,119,199,117,
                           9,220,181,158,75,70,220,145,37,248,253,218,53,251,
                           104,199,168,60,238,142,201,230,238,216,12,238,90,
                           207,37,35,238,254,42,238,30,116,115,247,237,82,238,
                           190,91,28,112,157,215,213,206,51,90,209,165,187,243,
                           172,70,116,57,239,206,179,61,232,242,186,218,121,
                           110,45,186,188,174,118,14,173,68,183,175,43,172,148,
                           245,82,247,171,157,207,246,162,19,247,185,46,116,
                           237,154,253,187,243,133,118,116,226,190,216,140,78,
                           220,151,27,208,109,247,101,167,187,49,4,157,184,214,
                           115,201,180,107,62,127,119,110,238,231,238,86,23,
                           119,183,21,5,92,231,188,187,172,231,146,73,119,151,
                           245,92,50,237,154,125,180,43,36,140,186,187,142,173,
                           166,238,174,227,43,2,110,190,99,222,93,214,223,31,
                           35,238,3,157,248,253,218,53,159,191,187,30,244,115,
                           247,97,31,119,31,241,6,220,191,204,107,61,151,140,
                           184,53,3,14,215,49,239,226,62,238,46,233,230,238,
                           178,14,238,254,167,12,157,184,214,115,201,244,188,
                           202,29,105,253,156,109,215,15,56,106,114,93,237,58,
                           140,69,36,215,213,174,159,240,127,144,251,100,115,
                           98,50,117,155,173,231,146,105,215,172,115,115,82,44,
                           117,155,111,141,162,110,115,114,120,192,205,199,161,
                           169,151,218,71,205,214,115,201,228,188,205,229,25,
                           248,13,196,157,146,138,174,134,195,62,176,94,246,
                           207,159,155,221,73,232,114,31,53,79,143,71,151,251,
                           183,185,83,221,103,136,107,61,151,76,187,102,255,54,
                           119,229,114,247,211,44,238,118,167,83,119,183,245,
                           92,50,233,238,182,158,75,166,93,115,93,237,190,164,
                           156,186,187,99,93,212,221,125,121,81,192,45,176,214,
                           7,191,196,58,239,46,82,199,73,220,87,213,113,106,
                           215,204,187,187,56,5,253,48,222,225,175,235,188,251,
                           141,68,116,185,206,187,75,226,208,237,117,206,119,
                           186,59,93,232,196,109,86,199,169,93,199,188,123,114,
                           208,137,219,162,246,29,113,247,246,161,219,174,115,
                           222,61,214,115,201,164,187,231,228,10,50,247,62,0,
                           49,47,100,50,115,47,116,101,108,109,97,122,120,103,
                           47,99,97,110,100,116,117,45,50,48,48,47,67,67,48,51,
                           57,69,50,56,54,53,68,70,68,52,65,49,51,66,48,70,47,
                           114,97,119,29,16,22,4,0,0,16,0,3,1,0,0,0,1,0,0,0,1,
                           0,0,31,44,120,1,109,220,15,124,150,243,254,199,241,
                           201,48,204,49,12,195,176,24,134,97,24,134,209,48,12,
                           211,25,134,97,216,97,135,97,216,63,12,83,119,181,
                           106,213,170,187,90,181,106,213,86,171,86,173,186,
                           171,187,90,181,218,93,173,182,214,93,13,195,48,12,
                           115,204,105,142,33,12,59,252,222,223,235,250,125,
                           239,239,229,124,222,247,227,113,30,143,245,58,185,
                           159,215,231,123,93,223,235,94,147,43,232,168,77,23,
                           60,244,214,158,230,160,160,163,190,15,10,10,10,193,
                           255,236,151,213,91,27,208,127,64,64,15,25,122,100,
                           202,16,87,144,213,219,234,209,15,219,221,250,237,
                           175,217,221,95,141,254,147,234,217,65,217,214,255,
                           97,247,3,21,232,63,170,126,176,192,206,86,31,17,222,
                           131,46,221,17,167,117,162,107,247,220,128,59,34,194,
                           143,46,221,17,103,250,208,165,59,34,210,139,110,187,
                           133,78,247,233,96,116,226,102,15,160,19,247,153,62,
                           116,226,230,116,163,19,247,249,14,116,226,174,141,
                           70,39,238,250,8,116,237,70,153,121,55,132,162,19,
                           119,19,134,97,110,131,27,157,172,243,159,201,232,
                           210,29,121,68,2,186,116,71,30,25,139,46,221,145,193,
                           141,232,114,222,145,71,123,208,165,59,242,222,108,
                           116,226,254,61,3,93,187,231,30,121,215,144,81,214,
                           245,48,242,190,84,116,226,62,144,132,78,220,7,227,
                           209,229,58,143,156,23,133,78,220,249,225,232,218,
                           141,130,235,178,221,133,184,190,153,91,61,136,78,
                           220,69,253,232,182,91,132,83,161,94,106,95,140,252,
                           38,9,95,16,247,144,58,78,237,154,235,121,228,183,49,
                           232,135,241,79,235,125,103,239,163,145,223,69,162,
                           19,247,251,48,116,57,175,235,186,44,116,233,186,174,
                           79,71,215,174,185,...>>,
                         #{max_packet_size => 262144,version => 4}],
                        [{file,"src/emqx_frame.erl"},{line,128}]},
            {emqx_frame,parse_frame,4,
                        [{file,"src/emqx_frame.erl"},{line,109}]},
            {emqx_connection,process_incoming,3,
                             [{file,"src/emqx_connection.erl"},{line,392}]},
            {gen_statem,call_state_function,5,
                        [{file,"gen_statem.erl"},{line,1660}]},
            {gen_statem,loop_event_state_function,6,
                        [{file,"gen_statem.erl"},{line,1023}]},
            {proc_lib,wake_up,3,[{file,"proc_lib.erl"},{line,...}]}]
Error data:<<117,156,218,117,204,91,211,140,78,220,197,13,232,196,93,82,143,78,
             220,67,131,232,196,253,182,31,93,187,230,252,86,126,215,131,78,
             220,239,59,209,137,251,163,31,93,158,223,57,55,68,162,75,119,78,
             98,24,186,118,205,231,239,156,155,131,209,165,59,103,216,0,186,
             116,231,220,210,135,46,231,157,83,150,136,78,220,137,113,232,218,
             53,223,215,205,41,143,70,39,238,148,8,116,226,186,67,209,201,188,
             239,103,162,19,183,51,13,93,187,102,157,231,124,148,140,78,220,
             174,4,116,226,126,26,139,46,221,185,209,37,232,210,157,123,97,30,
             186,118,205,191,167,155,27,147,141,46,221,185,151,100,160,75,119,
             110,108,42,58,113,11,170,208,137,91,228,70,215,174,185,158,231,
             190,90,138,78,220,226,98,116,226,190,17,130,46,207,239,92,95,35,
             58,113,119,122,208,181,107,174,171,185,205,181,232,196,221,83,137,
             78,220,214,114,116,233,206,251,155,58,78,233,206,179,254,94,153,
             116,231,157,52,72,221,121,167,244,83,119,222,169,61,1,183,192,186,
             91,225,151,184,95,205,203,84,199,73,220,39,212,113,18,55,203,133,
             46,231,157,247,84,17,186,156,119,94,118,14,186,60,191,243,86,52,
             160,19,183,190,30,93,187,230,252,206,91,93,141,78,92,79,5,58,113,
             215,149,161,19,119,160,19,157,184,191,249,209,181,107,246,209,188,
             65,31,58,113,255,240,162,75,183,42,168,14,221,118,11,29,235,92,
             117,199,0,186,116,171,82,250,208,181,107,230,173,186,187,27,93,
             186,85,169,29,232,196,29,222,138,78,220,153,17,232,196,157,29,138,
             78,220,57,56,104,230,206,197,177,48,183,170,23,157,184,95,38,160,
             19,247,171,88,116,226,126,29,133,78,230,253,38,28,157,204,123,40,
             4,93,186,243,227,212,113,74,119,254,85,234,56,181,107,246,239,252,
             248,46,116,233,206,191,182,29,93,186,243,19,154,209,137,59,178,24,
             157,184,163,114,209,137,59,38,11,157,184,99,211,209,137,59,206,
             236,223,66,156,34,245,82,251,119,254,254,120,124,65,220,131,49,
             232,196,125,59,18,157,184,239,134,161,19,247,189,96,116,57,239,
             130,...>>
`

**Comment by linany** [comment]
Hi, I found out today that EMQX CPU usage has been around 160%.The number of threads increased from 76 to 80, and the CPU usage of threads that used to consume a lot of CPU went to 0.0%, but it didn't kill it all the time.Process memory footprint increased by 40M.

**Comment by tigercl** [comment]
@linany The log you provided indicates that EMQ X Broker has received wrong messages. If such errors are frequent, a large number of logs will also cause the CPU usage to increase.

**Comment by linany** [comment]
> 
> 
> @linany The log you provided indicates that EMQ X Broker has received wrong messages. If such errors are frequent, a large number of logs will also cause the CPU usage to increase.

Thank you for your answer.
The latter error is gone and the CPU is still not down.At the same time, I tried to disable the log output, but it still didn't work.

**Comment by tigercl** [comment]
@linany Sorry for not responding to you in time, do you currently have clients publishing and subscribing to messages? Or is it completely idle? Does emqx generate other error logs at this time? And I don’t quite understand what you mean by "cannot work"?

**Comment by linany** [comment]
> 
> 
> @linany Sorry for not responding to you in time, do you currently have clients publishing and subscribing to messages? Or is it completely idle? Does emqx generate other error logs at this time? And I don’t quite understand what you mean by "cannot work"?

"cannot work" I mean that there is no improvement by modifying log levels。
I have 26 devices, all of which are connected and sending data normally except one.The exception device sent a packet that was too large to interpret, and the Broker disconnected the device.
After disconnection, the device initiates reconnection, and the broker's logs are as follows:

`2020-12-27 07:43:32.663 [error] candtu-200:C1039E2865DFD4A1310E@223.104.96.5:13063 [Protocol] Failed to open session: client_id_unavailable
2020-12-27 07:43:32.664 [notice] candtu-200:C1039E2865DFD4A1310E@223.104.96.5:13063 {emqx_my_plugin,103} :client candtu-200:C1039E2865DFD4A1310E connected, connack: 128, conn_attrs:#{clean_start => true,client_id => <<"candtu-200:C1039E2865DFD4A1310E">>,conn_mod => emqx_connection,connected_at => {1609,26212,657950},credentials => #{auth_result => success,client_id => <<"candtu-200:C1039E2865DFD4A1310E">>,cn => undefined,dn => undefined,mountpoint => undefined,password => <<"eyJhbGciOiJIUzI1IsInR5cCI6IkpXVCJ9.eyJyb2xlIjoiREVWSUNFIiwib3duZXIiOiJ0ZWxtYXp4ZyIsInV1aWQiOiJhMWQzMDRiMy1mYmJiLTRmNjEtODYwMi1kN2M1ZDRhNzk1ZmUiLCJkZXZpY2VzIjpbeyJkZXZ0eXBlIjoiY2FuZHR1LTIwMCIsImRldmlkIjoiQzEwMzlFMjg2NURGRDRBMTMxMEUifV0sInVzZXJuYW1lIjoiY2FuZHR1LTIwMCIsImNsaWVudGlwIjoiOjpmZmZmOjE3Mi4xOS4wLjE2IiwiaXNzdWVyIjoiaHR0cHM6Ly93d3cuemxnY2xvdWQuY29tIiwiZXhwIjoxNjA5ODkwMjEyLCJpYXQiOjE2MDkwMjYyMTJ9.icdRgcMyJ9ac4irgGyfeAOc5CqztSU_eYIpsVIBOeIo">>,peername => {{223,104,96,5},13063},username => <<"::ffff:172.19.0.16">>,ws_cookie => undefined,zone => external},is_bridge => false,keepalive => 60,peercert => nossl,peername => {{223,104,96,5},13063},proto_name => <<"MQTT">>,proto_ver => 4,username => <<"::ffff:172.19.0.16">>,zone => external}`

The log above shows that opening the session failed, but the 'client.connected' hook has been called.The connection is failed for the device and the device continues to initiate a reconnection.
