### ISSUE TITLE
Hash Sum Mismatch

### ISSUE THREAD

**Issue by berayb** [emqx/emqx#3960]
For Ubuntu 20.04: 

Failed to fetch https://repos.emqx.io/emqx-ce/deb/ubuntu/dists/./focal/stable/binary-amd64/Packages.gz  Hash Sum mismatch
   Hashes of expected file:
    - Filesize:2285 [weak]
    - SHA512:6dfde67ce6c61d1fba01dbb915cf41735416532077f90e476f60c6133f6e4aa17881e11a5310399e4d996dc8e83d33806531156de6123bbd5b9662a59659734e
    - SHA256:bf8f965eced3cb396095f823ef2c82d2610d8e04bcd18c7d0e605ec98d2735bf
    - SHA1:67ef4b2b2a1674d75082575d96326e1bbb63e55d [weak]
    - MD5Sum:2de231958310ff0251896cfb75d658af [weak]
   Hashes of received file:
    - SHA512:e0978efbe631d4ba09c48967651ae1ea70e60ce17ff593d1177eaaa72182f06d53aa12c01d1fa88a4dc4e3a195b2962478bd71e647b574f5b121d73a91abf2f9
    - SHA256:f2e9b7dbd384587d7f2280dfb68b22b4288be55a118bfd67b59a8bc835cf7f45
    - SHA1:3811d706a2e52e4ce8d845e8e61b3e5693b094d2 [weak]
    - MD5Sum:38467054a1a9e15546e29293f7e009ad [weak]
    - Filesize:2285 [weak]
   Last modification reported: Sun, 27 Dec 2020 08:16:28 +0000
   Release file created at: Fri, 25 Dec 2020 14:40:54 +0000

**Comment by zhanghongtong** [comment]
Hi, @berayb 
Sorry to have you with this problem, we updated the CDN service yesterday, you can now try again to see if issue has been resolved
