### ISSUE TITLE
data lost

### ISSUE THREAD

**Issue by beyondyinjl2** [emqx/emqx#3961]
Environment: EMQ X Broker version v4.2
The backlog of subscribed topics is more than 1 million, and the data is lost?

**Comment by tigercl** [comment]
@beyondyinjl2 Sorry I didn’t understand what you mean, is it convenient to describe your issue in more detail?

**Comment by beyondyinjl2** [comment]
We do stress test on emq 4000 per second, such as: aaa/XX/XX, xx are dynamic topics (aaa/300/100, aaa/301/200), topics send data, subscribers subscribe to aaa/#, If the subscriber's performance is poor, part of the emq backlog will be lost, and only the latest data will be received
