### ISSUE TITLE
[error] ** Generic server disksup terminating

### ISSUE THREAD

**Issue by shy-stone** [emqx/emqx#3968]
Environment
OS: CentOS Linux release 7.6.1810 (Core)
Erlang/OTP: System version: Erlang/OTP 21 [erts-10.3.5.1] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:32] [hipe]
EMQ: emqx 3.2.2
2020-12-24 10:43:12.841 [error] ** Generic server disksup terminating
** Last message in was timeout
** When Server state == [{data,[{"OS",{unix,linux}},
                                {"Timeout",1800000},
                                {"Threshold",80},
                                {"DiskData",
                                 [{"/",103078876,16},
                                  {"/dev",16379452,0},
                                  {"/dev/shm",16389908,0},
                                  {"/run",16389908,10},
                                  {"/sys/fs/cgroup",16389908,0},
                                  {"/mvsp",1031986328,84},
                                  {"/run/user/0",3277984,0}]}]}]
** Reason for termination ==
** {badarg,[{erlang,port_close,[#Port<0.10>],[]},
            {disksup,terminate,2,[{file,"disksup.erl"},{line,169}]},
            {gen_server,try_terminate,3,[{file,"gen_server.erl"},{line,673}]},
            {gen_server,terminate,10,[{file,"gen_server.erl"},{line,858}]},
            {proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,249}]}]}
2020-12-24 10:43:12.847 [error] crasher:
    initial call: disksup:init/1
    pid: <0.1378.0>
    registered_name: disksup
    exception error: bad argument
      in function  port_close/1
         called as port_close(#Port<0.10>)
      in call from disksup:terminate/2 (disksup.erl, line 169)
      in call from gen_server:try_terminate/3 (gen_server.erl, line 673)
      in call from gen_server:terminate/10 (gen_server.erl, line 858)
    ancestors: [os_mon_sup,<0.1376.0>]
    message_queue_len: 0
    messages: []
    links: [<0.1377.0>]
    dictionary: [{{disk_almost_full,"/mvsp"},set}]
    trap_exit: true
    status: running
    heap_size: 6772
    stack_size: 27
    reductions: 28456183
  neighbours:
2020-12-24 10:43:12.848 [error] supervisor: {local,os_mon_sup}
    errorContext: child_terminated
    reason: {badarg,[{erlang,port_close,[#Port<0.10>],[]},
                     {disksup,terminate,2,[{file,"disksup.erl"},{line,169}]},
                     {gen_server,try_terminate,3,
                                 [{file,"gen_server.erl"},{line,673}]},
                     {gen_server,terminate,10,
                                 [{file,"gen_server.erl"},{line,858}]},
                     {proc_lib,init_p_do_apply,3,
                               [{file,"proc_lib.erl"},{line,249}]}]}
    offender: [{pid,<0.1378.0>},
               {id,disksup},
               {mfargs,{disksup,start_link,[]}},
               {restart_type,permanent},
               {shutdown,2000},
               {child_type,worker}]
2020-12-24 10:43:12.849 [error] supervisor: {local,os_mon_sup}
    errorContext: start_error
    reason: {eagain,[{erlang,open_port,
                             [{spawn,"sh -s disksup 2>&1"},[stream]],
                             []},
                     {disksup,init,1,[{file,"disksup.erl"},{line,114}]},
                     {gen_server,init_it,2,
                                 [{file,"gen_server.erl"},{line,374}]},
                     {gen_server,init_it,6,
                                 [{file,"gen_server.erl"},{line,342}]},
                     {proc_lib,init_p_do_apply,3,
                               [{file,"proc_lib.erl"},{line,249}]}]}
    offender: [{pid,<0.1378.0>},
               {id,disksup},
               {mfargs,{disksup,start_link,[]}},
               {restart_type,permanent},
               {shutdown,2000},
               {child_type,worker}]
2020-12-24 10:43:12.849 [error] crasher:
    initial call: disksup:init/1
    pid: <0.28851.239>
    registered_name: []
    exception error: eagain
      in function  open_port/2
         called as open_port({spawn,"sh -s disksup 2>&1"},[stream])
      in call from disksup:init/1 (disksup.erl, line 114)
      in call from gen_server:init_it/2 (gen_server.erl, line 374)
      in call from gen_server:init_it/6 (gen_server.erl, line 342)
    ancestors: [os_mon_sup,<0.1376.0>]
    message_queue_len: 0
    messages: []
    links: [<0.1377.0>]
    dictionary: []
    trap_exit: true
    status: running
    heap_size: 376
    stack_size: 27
    reductions: 240
  neighbours:
2020-12-24 10:43:12.850 [error] supervisor: {local,os_mon_sup}
    errorContext: start_error
    reason: {eagain,[{erlang,open_port,
                             [{spawn,"sh -s disksup 2>&1"},[stream]],
                             []},
                     {disksup,init,1,[{file,"disksup.erl"},{line,114}]},
                     {gen_server,init_it,2,
                                 [{file,"gen_server.erl"},{line,374}]},
                     {gen_server,init_it,6,
                                 [{file,"gen_server.erl"},{line,342}]},
                     {proc_lib,init_p_do_apply,3,
                               [{file,"proc_lib.erl"},{line,249}]}]}
    offender: [{pid,{restarting,<0.1378.0>}},
               {id,disksup},
               {mfargs,{disksup,start_link,[]}},
               {restart_type,permanent},

**Comment by shy-stone** [comment]
2020-12-24 10:43:12.841 [error] ** Generic server disksup terminating
** Last message in was timeout
** When Server state == [{data,[{"OS",{unix,linux}},
                                {"Timeout",1800000},
                                {"Threshold",80},
                                {"DiskData",
                                 [{"/",103078876,16},
                                  {"/dev",16379452,0},
                                  {"/dev/shm",16389908,0},
                                  {"/run",16389908,10},
                                  {"/sys/fs/cgroup",16389908,0},
                                  {"/mvsp",1031986328,84},
                                  {"/run/user/0",3277984,0}]}]}]
** Reason for termination ==
** {badarg,[{erlang,port_close,[#Port<0.10>],[]},
            {disksup,terminate,2,[{file,"disksup.erl"},{line,169}]},
            {gen_server,try_terminate,3,[{file,"gen_server.erl"},{line,673}]},
            {gen_server,terminate,10,[{file,"gen_server.erl"},{line,858}]},
            {proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,249}]}]}
[os_mon] memory supervisor port (memsup): Erlang has closed
[os_mon] cpu supervisor port (cpu_sup): Erlang has closed

Stop mqtt:tcp listener on 127.0.0.1:11883 successfully.
Stop mqtt:tcp listener on 0.0.0.0:1883 successfully.
Stop mqtt:ws listener on 0.0.0.0:8083 successfully.
Stop mqtt:ssl listener on 0.0.0.0:8883 successfully.
Stop mqtt:wss listener on 0.0.0.0:8084 successfully.
{"Kernel pid terminated",application_controller,"{application_terminated,os_mon,shutdown}"}^M
Kernel pid terminated (application_controller) ({application_terminated,os_mon,shutdown})^M
^M
Crash dump is being written to: log/crash.dump...done^

**Comment by shy-stone** [comment]
hi,the server is aliyun-ecs,at the moment,nobody do anything

**Comment by tigercl** [comment]
@shy-stone Do you confirm whether the disk is full？

**Comment by shy-stone** [comment]
I confirm the disk was not full at the moment, and there are logs
2020-12-24 10:43:12.841 [error] ** Generic server disksup terminating
** Last message in was timeout
** When Server state == [{data,[{"OS",{unix,linux}},
{"Timeout",1800000},
{"Threshold",80},
{"DiskData",
[{"/",103078876,16},
{"/dev",16379452,0},
{"/dev/shm",16389908,0},
{"/run",16389908,10},
{"/sys/fs/cgroup",16389908,0},
{"/mvsp",1031986328,84},
{"/run/user/0",3277984,0}]}]}]

**Comment by k32** [comment]
Hello,

`disksup` server is not a part of EMQ X, it is a part of OTP. If this problem is still relevant, please try to upgrade EMQ X and OTP to the new versions.
