### ISSUE TITLE
Can not use console to print logs

### ISSUE THREAD

**Issue by WorldWay** [emqx/emqx#3975]
I cloned emqx:4.1.0 and added some plugins,then make on centos 7.6 and build with docker.
My docker file:
![image](https://user-images.githubusercontent.com/24239063/103335466-f3814680-4aaf-11eb-8458-8844508944a8.png)
If I use ./_build/emqx/rel/emqx/bin/emqx console instead to print logs,I will get error like this:
![image](https://user-images.githubusercontent.com/24239063/103335553-34795b00-4ab0-11eb-9ab0-190369d002fe.png)

I running this on Kubernetes 1.17.9 + Istio 1.6.10,but not inject side for it.
If I don't use console,the logs will not be collected to my elasticsearch automatically.

what can I do for it next step?

**Comment by zhanghongtong** [comment]
Hi, @WorldWay 
Maybe you can try `./_build/emqx/rel/emqx/bin/emqx foreground `

**Comment by WorldWay** [comment]
thank you,it has worked well
