### ISSUE TITLE
Web Socket Global Listener

### ISSUE THREAD

**Issue by berayb** [emqx/emqx#3989]
Hi, 

Is it possible to listen to web sockets globally without providing authentication for a single client?

For example, in a dashboard scenario, it is necessary to subscribe to multiple clients as well as the same client which is not possible with a current authentication.

Thanks,

**Comment by tigercl** [comment]
@berayb I think the `allow_anonymous` configuration item can help you, please read [Authentication](https://docs.emqx.io/en/broker/latest/advanced/auth.html#authentication-method) to learn more.
But about the last point you mentioned, I don’t understand what you mean too much.

**Comment by berayb** [comment]
@tigercl thanks, allowing anonymous connection is not an option. We need to listen to multiple clients with the same client. However, the broker kicks out since we are running on multiple containers.
