### ISSUE TITLE
Does mqtt eliminate SSH through nginx plus agent mean that heartbeat detection is to detect the online condition of nginx

### ISSUE THREAD

**Issue by dhw-daniel** [emqx/emqx#3990]
mqtt version 3.2.3

At present, we find that our mqtt cluster can still see this client in the cluster when the client is disconnected，
The client is an mqtt cluster connected through nginx plus，
Heartbeat detection is 60 seconds

**Comment by HJianBo** [comment]
I think this is more of a Nginx problem. Does the tcp connection from Nginx to emqx still exist after the client is disconnected?

**Comment by dhw-daniel** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
