### ISSUE TITLE
emqx exit abnormally

### ISSUE THREAD

**Issue by chiris414362444** [emqx/emqx#3993]
Start emqx with stateful set. When all pods of emqx are deleted at the same time, emqx pod can't be started normally any more. However, if the pod is rolling-update, it can be started normally.
![image](https://user-images.githubusercontent.com/22514434/103861997-3919c100-50f9-11eb-8532-618ed6d8879d.png)
![image](https://user-images.githubusercontent.com/22514434/103862051-58185300-50f9-11eb-8efc-0fb540776f3d.png)

After deleting PVC of emqx, it can be restarted.
helm packages: [helm-emqx-test.tar.gz](https://github.com/emqx/emqx/files/5780073/helm-emqx-test.tar.gz)

**Comment by chiris414362444** [comment]
reference issue: https://github.com/emqx/emqx/issues/3568

**Comment by zhanghongtong** [comment]
Hi，@chiris414362444
This is a bug, we plan to fix it in 4.3.0

**Comment by zhanghongtong** [comment]
CC @HJianBo

**Comment by HJianBo** [comment]
We have tagged 4.3-alpha.1, which contains the fix. The official release will probably come in 1-2 months.

**Comment by chiris414362444** [comment]
> We have tagged 4.3-alpha.1, which contains the fix. The official release will probably come in 1-2 months.
@HJianBo 
Hi, I have verified this problem with version 4.3.1, but there will still be problems. It seems to be accidental. The log is as follows:
![image](https://user-images.githubusercontent.com/22514434/118430117-ea62e000-b705-11eb-83dd-8061aa152a8c.png)

Chart I use: [charts/emqx](https://github.com/emqx/emqx/tree/master/deploy/charts/emqx) 
AppVersion: 4.3.1
Kubernetes version: v1.19.4

**Comment by ctellechea2001** [comment]
@chiris414362444 Did you found the solution? I have the same issue on my Kubernetes Cluster with PVC persistence. Thanks!

**Comment by ctellechea2001** [comment]
@Rory-Z @HJianBo Did you found the solution? If you need to reproduce the error you can run the following steps:

- Install minikube (https://minikube.sigs.k8s.io/docs/start/). That is to simulate the Kubernetes Cluster in a local environment.
- Run: **helm install my-emqx emqx/emqx --set service.type=NodePort --set persistence.enabled=true**
- Run **minikube stop**: that command simulate that all pods are stopped together at the same time.
- Run: **minikube start**
- After that all the pods are going to be stopped.

Exec: /opt/emqx/erts-11.1.8/bin/erlexec -noshell -noinput +Bd -boot /opt/emqx/releases/4.3.5/start -mode embedded -boot_var ERTS_LIB_DIR /opt/emqx/erts-11.1.8/../lib -mnesia dir "/opt/emqx/data/mnesia/my-emqx@my-emqx-0.my-emqx-headless.emqx.svc.cluster.local" -config /opt/emqx/data/configs/app.2021.07.23.17.51.25.config -args_file /opt/emqx/data/configs/vm.2021.07.23.17.51.25.args -vm_args /opt/emqx/data/configs/vm.2021.07.23.17.51.25.args -start_epmd false -epmd_module ekka_epmd -proto_dist ekka -- foreground
Root: /opt/emqx
Starting emqx on node my-emqx@my-emqx-0.my-emqx-headless.emqx.svc.cluster.local
2021-07-23T17:51:58.350855+00:00 [warning] ekka_mnesia: still waiting for table(s): [emqx_resource,mqtt_app,emqx_rule,emqx_banned,mqtt_admin]
2021-07-23T17:52:28.351871+00:00 [warning] ekka_mnesia: still waiting for table(s): [emqx_resource,mqtt_app,emqx_rule,emqx_banned,mqtt_admin]
2021-07-23T17:52:58.352872+00:00 [warning] ekka_mnesia: still waiting for table(s): [emqx_resource,mqtt_app,emqx_rule,emqx_banned,mqtt_admin]
2021-07-23T17:53:28.353902+00:00 [warning] ekka_mnesia: still waiting for table(s): [emqx_resource,mqtt_app,emqx_rule,emqx_banned,mqtt_admin]
2021-07-23T17:53:58.354912+00:00 [warning] ekka_mnesia: still waiting for table(s): [emqx_resource,mqtt_app,emqx_rule,emqx_banned,mqtt_admin]
2021-07-23T17:54:28.355920+00:00 [warning] ekka_mnesia: still waiting for table(s): [emqx_resource,mqtt_app,emqx_rule,emqx_banned,mqtt_admin]

carlos@(minikube:emqx): k get pods
NAME        READY   STATUS    RESTARTS   AGE
my-emqx-0   0/1     Running   0          6m2s
my-emqx-1   0/1     Running   1          81m
my-emqx-2   0/1     Running   1          81m
carlos@(minikube:emqx):

If you want to resolve the issue you need to delete all the PVC.

carlos@(minikube:emqx): k get pvc
NAME                  STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   AGE
emqx-data-my-emqx-0   Bound    pvc-53b6cecd-2e91-4e50-9dee-ff8762a46047   20Mi       RWO            standard       83m
emqx-data-my-emqx-1   Bound    pvc-46dafb8b-0ba8-43c3-a37e-17481af2576c   20Mi       RWO            standard       83m
emqx-data-my-emqx-2   Bound    pvc-3e0e0e3f-e423-4b05-a6a9-ed8ddc6a1c67   20Mi       RWO            standard       83m
carlos@(minikube:emqx):
