### ISSUE TITLE
emqx-psk-pgsql, a plugin for device (D)TLS PSK authentication using PostgreSQL 

### ISSUE THREAD

**Issue by endianjoakim** [emqx/emqx#3998]
Hi there, let me first thank you for making great and useful software! We use EMQx a lot and love it. 

**What would you like to be added/modified**:
 I would request the EMQx team to take over development and maintenance of the `emqx-psk-pgsql` plugin we created, and bring it into the public EMQx repositories. 

You can find the plugin here: https://gitlab.endian.se/endian/score/emqx-psk-pgsql

**Why is this needed**:
We use PSK authentication for devices and needed a way to dynamically add/remove/update PSKs for individual devices. We could not use the `emqx-auth-pgsql` for this purpose since it does not use the correct hooks for TLS PSK authentication. 

As you can see we used other EMQx plugins as a template for this plugin, so the code should be familiar. 

Thanks

**Comment by HJianBo** [comment]
Thanks for your suggestion @endianjoakim 

I think this feature is very useful. We will discuss the way this feature is implemented :)

**Comment by endianjoakim** [comment]
Any news on this?

**Comment by zmstone** [comment]
> Any news on this?

Hi @endianjoakim 

Thank you for this.
we are picking this up, will get back to you in one/two weeks.

**Comment by zmstone** [comment]
Hi again @endianjoakim 

Some updates.
With the previous PRs and finally this https://github.com/emqx/emqx/pull/4362 merged,
to include a thrid party plugin in EMQX release, all one will need is to set an environment variable `EMQX_EXTRA_PLUGINS`.

We'll start reviewing plugins from the community and have them referenced from the main project soon.

**Comment by endianjoakim** [comment]
Thanks for the update @zmstone! 

I do have a question related to Enterprise EMQx, will these community plugins be available there? 

We've considered the Enterprise version but have been blocked by our `emqx-psk-pgsql` plugin not being available.

**Comment by zmstone** [comment]
Excellent question. Let's move the discussion here:
https://github.com/emqx/emqx/discussions/4380

**Comment by zmstone** [comment]
As for this specific plugin, if you'd like to have it in Enterprise edition, maybe @endianjoakim you can reach out to our sales team?
The next enterprise release in plan is e4.3.0.

**Comment by endianjoakim** [comment]
Thank you, I will consider this. Is there a date planned for the e4.3.0 release?

**Comment by zmstone** [comment]
we are releasing opensource v4.3.0 soon in this month.
e4.3.0 should be ready May, but it's hard to say at this moment

**Comment by zmstone** [comment]
EMQX
