### ISSUE TITLE
Unable to start emqx broker

### ISSUE THREAD

**Issue by greeedy** [emqx/emqx#4006]
**Please describe your problem in detail, if necessary, you can upload the log file through the attachment**:
On starting emqx broker on my VM(Virtual Machine), 

I am getting the below error:

`bin/emqx: 392: bin/emqx: /root/emqx_v1/erts-10.7.2.5/bin/run_erl: Exec format error`

The same code I am able to run on my local machine, not sure if I am missing some packages on the VM.
Please help in getting this resolved.

**Comment by HJianBo** [comment]
Could you give me some basic infomations?

**Environment**:
- EMQ X version (e.g. `emqx_ctl status`): 
- Hardware configuration (e.g. `lscpu`):
- OS (e.g. `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Erlang/OTP version (in case you build emqx from source code): 
- Others:

**Comment by greeedy** [comment]
**emqx_ctl status:** 
./emqx_v1/bin/emqx_ctl: 28: ./emqx_v1/bin/emqx_ctl: /root/emqx_v1/erts-10.7.2.5/bin/escript: Exec format error

**lscpu**
Architecture:        x86_64
CPU op-mode(s):      32-bit, 64-bit
Byte Order:          Little Endian
CPU(s):              8
On-line CPU(s) list: 0-7
Thread(s) per core:  2
Core(s) per socket:  4
Socket(s):           1
NUMA node(s):        1
Vendor ID:           GenuineIntel
CPU family:          6
Model:               85
Model name:          Intel(R) Xeon(R) CPU @ 2.00GHz
Stepping:            3
CPU MHz:             2000.158
BogoMIPS:            4000.31
Hypervisor vendor:   KVM
Virtualization type: full
L1d cache:           32K
L1i cache:           32K
L2 cache:            1024K
L3 cache:            39424K
NUMA node0 CPU(s):   0-7
Flags:               fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx pdpe1gb rdtscp lm constant_tsc rep_good nopl xtopology nonstop_tsc cpuid tsc_known_freq pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch invpcid_single pti ssbd ibrs ibpb stibp fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm mpx avx512f avx512dq rdseed adx smap clflushopt clwb avx512cd avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves arat md_clear arch_capabilities

**cat /etc/os-release**
NAME="Ubuntu"
VERSION="18.04.5 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.5 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic

**uname -a**
Linux okc-emqbroker-image-2 5.4.0-1032-gcp #34~18.04.1-Ubuntu SMP Thu Dec 10 09:14:10 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

Yes, we are building emqx from source code only:
**erlang/otp version:**
Erlang/OTP 23

**dpkg -l| grep erlang**
ii  erlang                             1:23.2.1-1                                  all          Concurrent, real-time, distributed functional language
ii  erlang-appmon                      1:23.1-1                                    amd64        Erlang/OTP application monitor
ii  erlang-asn1                        1:23.1-1                                    amd64        Erlang/OTP modules for ASN.1 support
ii  erlang-base                        1:23.1-1                                    amd64        Erlang/OTP virtual machine and base applications
ii  erlang-common-test                 1:23.1-1                                    amd64        Erlang/OTP application for automated testing
ii  erlang-crypto                      1:23.1-1                                    amd64        Erlang/OTP cryptographic modules
ii  erlang-debugger                    1:23.1-1                                    amd64        Erlang/OTP application for debugging and testing
ii  erlang-dev                         1:23.1-1                                    amd64        Erlang/OTP development libraries and headers
ii  erlang-dialyzer                    1:23.1-1                                    amd64        Erlang/OTP discrepancy analyzer application
ii  erlang-diameter                    1:23.1-1                                    amd64        Erlang/OTP implementation of RFC 3588 protocol
ii  erlang-edoc                        1:23.1-1                                    amd64        Erlang/OTP module for generating documentation
ii  erlang-eldap                       1:23.1-1                                    amd64        Erlang/OTP LDAP library
ii  erlang-erl-docgen                  1:23.1-1                                    amd64        Erlang/OTP documentation stylesheets
ii  erlang-et                          1:23.1-1                                    amd64        Erlang/OTP event tracer application
ii  erlang-eunit                       1:23.1-1                                    amd64        Erlang/OTP module for unit testing
ii  erlang-examples                    1:23.1-1                                    all          Erlang/OTP application examples
ii  erlang-ftp                         1:23.1-1                                    amd64        This module implements a client for file transfer
ii  erlang-gs                          1:23.1-1                                    amd64        Erlang/OTP graphics system
ii  erlang-ic                          1:23.1-1                                    amd64        Erlang/OTP IDL compiler
ii  erlang-ic-java                     1:23.1-1                                    all          Erlang/OTP IDL compiler (Java classes)
ii  erlang-inets                       1:23.1-1                                    amd64        Erlang/OTP Internet clients and servers
ii  erlang-inviso                      1:23.1-1                                    amd64        Erlang/OTP trace tool
ii  erlang-jinterface                  1:23.1-1                                    all          Java communication tool to Erlang
ii  erlang-megaco                      1:23.1-1                                    amd64        Erlang/OTP implementation of Megaco/H.248 protocol
ii  erlang-mnesia                      1:23.1-1                                    amd64        Erlang/OTP distributed relational/object hybrid database
ii  erlang-mode                        1:23.1-1                                    all          Erlang major editing mode for Emacs
ii  erlang-observer                    1:23.1-1                                    amd64        Erlang/OTP application for investigating distributed systems
ii  erlang-odbc                        1:23.1-1                                    amd64        Erlang/OTP interface to SQL databases
ii  erlang-os-mon                      1:23.1-1                                    amd64        Erlang/OTP operating system monitor
ii  erlang-parsetools                  1:23.1-1                                    amd64        Erlang/OTP parsing tools
ii  erlang-percept                     1:23.1-1                                    amd64        Erlang/OTP concurrency profiling tool
ii  erlang-pman                        1:23.1-1                                    amd64        Erlang/OTP process manager
ii  erlang-public-key                  1:23.1-1                                    amd64        Erlang/OTP public key infrastructure
ii  erlang-reltool                     1:23.1-1                                    amd64        Erlang/OTP release management tool
ii  erlang-runtime-tools               1:23.1-1                                    amd64        Erlang/OTP runtime tracing/debugging tools
ii  erlang-snmp                        1:23.1-1                                    amd64        Erlang/OTP SNMP applications
ii  erlang-src                         1:23.1-1                                    all          Erlang/OTP applications sources
ii  erlang-ssh                         1:23.1-1                                    amd64        Erlang/OTP implementation of SSH protocol
ii  erlang-ssl                         1:23.1-1                                    amd64        Erlang/OTP implementation of SSL
ii  erlang-syntax-tools                1:23.1-1                                    amd64        Erlang/OTP modules for handling abstract Erlang syntax trees
ii  erlang-test-server                 1:23.1-1                                    amd64        Erlang/OTP server for automated application testing
ii  erlang-tftp                        1:23.1-1                                    amd64        This is a complete implementation of the following IETF standards:
ii  erlang-toolbar                     1:23.1-1                                    amd64        Erlang/OTP graphical toolbar
ii  erlang-tools                       1:23.1-1                                    amd64        Erlang/OTP various tools
ii  erlang-tv                          1:23.1-1                                    amd64        Erlang/OTP table viewer
ii  erlang-typer                       1:23.1-1                                    amd64        Erlang/OTP code type annotator
ii  erlang-wx                          1:23.1-1                                    amd64        Erlang/OTP bindings to wxWidgets
ii  erlang-xmerl                       1:23.1-1                                    amd64        Erlang/OTP XML tools

Please take a look, and let me know if you need some other info as well.

**Comment by zmstone** [comment]
Hi.
Please use the latest OTP 22 release to build EMQX.
e.g. `OTP-22.3.4.13`

OTP 23 is work-in-progress so far.

**Comment by k32** [comment]
OTP 23 support has been added.
