### ISSUE TITLE
bind emqx-dashboard plugin only to localhost or specific ip

### ISSUE THREAD

**Issue by aniston** [emqx/emqx#4010]
Is it possible to bind the emqx-dashboard plugin only to localhost or a specific ip, if not can this be implemented ?

**Comment by HJianBo** [comment]
Hi @aniston  Thanks for your feedback. We plan to implement it in v4.3.0

**Comment by aniston** [comment]
Hello @HJianBo , thanks for the message, will be eagerly waiting for the v4.3.0.

best regards till then.

**Comment by aniston** [comment]
> Hi @aniston Thanks for your feedback. We plan to implement it in v4.3.0

Hi @HJianBo seems like this feature did not make it into the v4.3 release ! or did i miss something ?
in `/etc/emqx/plugins/emqx_dashboard.conf` seems to be no mention of an IP to bind to.

**Comment by zmstone** [comment]
new binding will be supported in EMQ X 5.0

**Comment by aniston** [comment]
@zmstone , good to know and thanks for the Update, looking forward to the release version of EMQx v5.0
