### ISSUE TITLE
docker emqx v4.2.5 Unable to start emqx broker

### ISSUE THREAD

**Issue by lowmanisbusy** [emqx/emqx#4011]
listener.ssl.external.acceptors=32
sed: can't move '/opt/emqx/etc/emqx.confHEJDBc' to '/opt/emqx/etc/emqx.conf': Resource busy

volumes like that:

   volumes:
      - /etc/timezone:/etc/timezone
      - /etc/localtime:/etc/localtime
      - /usr/emqx/etc/emqx.conf:/opt/emqx/etc/emqx.conf

**Comment by lowmanisbusy** [comment]
when I use emqx:v3.2.2, it was start successfully，but if I use v4.2.5，the problem as above。。。。。。actually, I can't chinese really well。。。。手动狗头.gif

**Comment by lowmanisbusy** [comment]
docker image v4.2.0 is right

**Comment by Rory-Z** [comment]
Hi，@lowmanisbusy
Sorry, this is a bug introduced in version v4.2.4, and we'll fix it in the next release

**Comment by HJianBo** [comment]
Hi @lowmanisbusy We have released 4.2.7 which includes a fix for this problem.
