### ISSUE TITLE
listener.ssl.external.cacertfile cache/hot-reloading

### ISSUE THREAD

**Issue by bgrosse-midokura** [emqx/emqx#4013]
**What would you like to be added/modified**:

When I change the contents of `listener.ssl.external.cacertfile`, I would like that emqx would reload it, given some conditions.

**What I don't need**:

Given the above, I do not need to re-check certs for existing connections, this could be done via "kick" API or similar.

**Why is this needed**:

Additional client CAs might be created after emqx is running, and be added live without restarting emqx.

**What have I tried**:

Verified that `cacertfile` _does_ get reloaded without restarting when the first client connects, after having zero clients connected.

`emqx eval "ssl:clear_pem_cache()"` prints `ok` but has no effect. I suspect it has to do with erlang process context.

Restart listener: Patching `emqx-management`, I added a `restart` and `stop` in addition to `start` directive. `restart` has no effect on the `cacertfile` cache, `start` followed by `stop` leaves emqx in a bad state, i.e. all connections produce some error. 

Simply restarting emqx. This is my current workaround, but it takes 10-20s to start up which is not so good.

**Implementation ideas**:
1. `listener.ssl.external.cacertfile_cache` config option to never use cache, perhaps call `https://erlang.org/doc/man/ssl.html#clear_pem_cache-0` before accepting a connection.
2. enhance `emqx-management` to allow calling `ssl:clear_pem_cache`, probably somewhere in esockd/transport.

I don't really have experience with erlang, so I would like to get two things out of this issue:
1. get some insight one the whole thing (how to approach, details) from someone who has expertise on the matter
2. find out if something like this could be accepted as a PR

Thank you, great software!

**Comment by yqfclid** [comment]
maybe can use ```ssl:clear_pem_cache()```  after changing certificate files.

**Comment by bgrosse-midokura** [comment]
@yqfclid as I saidI traid `emqx eval "ssl:clear_pem_cache()"`, which appears to do _something_ as I get `ok` and not some error, but has no effect. So far I _think_ that I must execute that line inside the process that deals with SSL connections, but I'm not familiar with erlang or its OTP.

**Comment by bgrosse-midokura** [comment]
meanwhile I'm using https://github.com/emqx/emqx-management/pull/307 as a workaround

**Comment by HJianBo** [comment]
Hi guys, this feature has introduced into 4.3-beta.1.

In 4.3, you can replace the certificate file and restart the listener to reload it. i.e:
```
./bin/emqx_ctl listeners restart mqtt:tcp:external
```

BTW, in 4.3, this command only works on MQTT listeners. For other types of listeners, you can restart the plugin for this purpose.

Thanks for @bgrosse-midokura contributions 👍
