### ISSUE TITLE
I don't have connections left menu enabled

### ISSUE THREAD

**Issue by jesuslieras** [emqx/emqx#4026]
I am working ubuntu 18.04 emqx v4.2.6.
I can't see ( connections ) left menu dashboard. Can you help me, please.

attached dashboard image
![Xconnections EMQ](https://user-images.githubusercontent.com/77561291/104830916-bd2e2000-5840-11eb-8ab6-56b36d3bdabb.jpg)

**Comment by HJianBo** [comment]
Hi @jesuslieras Since emqx 3 or emqx 4 Connections has been renamed Clients
