### ISSUE TITLE
CPU Info not showing on web dashboard

### ISSUE THREAD

**Issue by Zapnologica** [emqx/emqx#4034]
#### Environment

- OS:  Window Server 2020
- Erlang/OTP:    R22/10.7
- EMQ:   4.2.3

#### Description

We have 3 windows nodes running in azure virtual server environment, however, for some reason, the CPU usage does not show on the dashboard. It only shows 0.00 /0.00 /0.00 /

![Screenshot 2021-01-19 133604](https://user-images.githubusercontent.com/3656913/105029759-6f413400-5a5b-11eb-95e7-cbc5b2aee510.jpg)

**Comment by tigercl** [comment]
@Zapnologica Sorry, this feature currently only supports UNIX systems.
