### ISSUE TITLE
Shared subscription, subscribed topic is inconsistent with the received topic!

### ISSUE THREAD

**Issue by kunsyliu** [emqx/emqx#4035]
**What would you like to be added/modified**:
共享订阅 回调topic 由现在的 ：topic/*，改成 $queue/topic/*

**Why is this needed**:
共享订阅 topic ：$queue/topic/*  但emq 实际回调时topic 是：topic/* ,

paho mqtt 客户端，没办法通过回调的topic 关联上监听器。

**Comment by YiuTerran** [comment]
你用的Java客户端？golang的是没问题的，Java的话你可以考虑用hivemq那个客户端

**Comment by tigercl** [comment]
@kunsyliu When client A subscribed topic `$queue/topic`, and client B publishes the message with topic `topic`，this message will be forwarded to client A, So the topic of the message received by the client is naturally `topic` instead of `$queue/topic`.

**Comment by zmstone** [comment]
now the hook point callbacks will receive a `#share{}` record.
https://github.com/emqx/emqx/blob/755b59b7fe21870e4d000387bda8bce1c91cf8a4/apps/emqx/include/emqx_mqtt.hrl#L62
