### ISSUE TITLE
Load Management

### ISSUE THREAD

**Issue by tpharaoh** [emqx/emqx#4038]
**Please describe your problem in detail, if necessary, you can upload the log file through the attachment**:
I am testing a load with the following settings:
400,000 total messages
2000 simultaneous connections
200 messages per connection

All 400000 messages get sent successfully in 1min 18s

The subscribers process ~18000 messages (the subscriber is a PHP script, which does some checks and saves to DB)

Around this point the emqx instance crashes, so the messages are lost. Around 18-20k make it to DB. The PHP script is running behind supervisord and will run as long emqx instance is it.

I am testing on a rather low powered DigitalOcean instance. But I read others in the forum able to manage such loads

emqx version 2.4.6 (recently updated)
settings are all default, except for 2 settings
zone.external.max_mqueue_len = 10000
zone.external.rate_limit.conn_messages_in = 1000,10s

**Comment by tpharaoh** [comment]
I tested the following change
zone.external.max_mqueue_len = 0
zone.external.rate_limit.conn_messages_in = 100000,10s

I improved by 7000 messages before it crashed

**Comment by tigercl** [comment]
@tpharaoh I think you should reduce the configuration. According to your description, at least 382,000 messages were cached when EMQ X Broker crashed. In your scenario, there are a total of 2,000 connections, and each connection allows 10,000 messages to accumulate, which means you allow EMQ X Broker to cache up to 20 million messages, obviously this will cause insufficient memory.

**Comment by k32** [comment]
Hello,

emqx version 2.4.6 is very old, there have been numerous performance improvement ever since. Please feel free to create a new issue if you face problems with the performance on the latest stable version of the broker (4.3.8).
