### ISSUE TITLE
emqx connect to fail mysql

### ISSUE THREAD

**Issue by wxp584** [emqx/emqx#4045]
**windows**:

- EMQ X version (e.g. `emqx_ctl status`): 
- Hardware configuration (e.g. `lscpu`):
- OS (e.g. `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Erlang/OTP version (in case you build emqx from source code): 
- Others:

**What happened and what you expected to happen**:
My emqx and mysql always fail to authenticate。

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
_I have followed the method provided in the FAQ and it still fails。_

**Comment by tigercl** [comment]
@wxp584 Sorry for not responding to you in time, can you provide more logs so that we can provide you with better support?
