### ISSUE TITLE
What did make the difference in dashboard? EMQX 4.2.6 in docker container emqx/emqx:latest

### ISSUE THREAD

**Issue by peace4j** [emqx/emqx#4048]
We are trying EMQX docker container recently.
I pulled the image emqx/emqx:latest and created a container from it. There's a difference in the dashboard between two tests but don't know why. 
The difference is in the menu items.
They look like this:
![dif1](https://user-images.githubusercontent.com/6525244/105450719-0f929500-5cb6-11eb-889f-0daf6a43855f.jpg)

They were running in the same host, same configuration, even same user name and password, same clients.
Just don't know what lead to this. Any advice would be appreciated.

Best regards,

peace4j

**Comment by tigercl** [comment]
@peace4j Sorry for not being able to get more information in the screenshot you provided, I think you just expanded the `General` item.

**Comment by peace4j** [comment]
> 
> 
> @peace4j Sorry for not being able to get more information in the screenshot you provided, I think you just expanded the `General` item.

Some time, I login the dashboard, the menu looks like the right one.
While some time I login, the menu looks like the left one.

I did nothing change to the configuration. But I don't know how it happens.
Yesterday and the day before yesterday, it happened again. Yesterday , it looked like the left one, with "general" item apears.
Now I login dashboard, it looks like the right one, without the "general" item.

Environment:  emqx 4.2.6 in container created from official docker image.
