### ISSUE TITLE
HTTP Data import failed

### ISSUE THREAD

**Issue by qzheng527** [emqx/emqx#4063]
**Environment**:
Ubuntu 20.04

- EMQ X version (e.g. `emqx_ctl status`):  Docker image (4.2.4)
- Hardware configuration (e.g. `lscpu`):  Intel(R) Core(TM) i7-4790K
- OS (e.g. `cat /etc/os-release`): Ubuntu 20.04
- Kernel (e.g. `uname -a`): 5.4.2
- Erlang/OTP version (in case you build emqx from source code): 
- Others:

**What happened and what you expected to happen**:
HTTP data upload/import failed.

$ curl -i --basic -u admin:public -X POST "http://localhost:8081/api/v4/data/import" -d @/tmp/test.json
HTTP/1.1 200 OK
content-length: 37
content-type: application/json
date: Mon, 25 Jan 2021 02:42:29 GMT
server: Cowboy

{"message":"missing_required_params"}

I would expect this could work.

Other HTTP commands such as below could work successfully.

$ curl -i --basic -u admin:public -X POST "http://localhost:8081/api/v4/data/export"
HTTP/1.1 200 OK
content-length: 139
content-type: application/json
date: Mon, 25 Jan 2021 02:43:46 GMT
server: Cowboy

{"data":{"size":388,"node":"emqx@node2.emqx.io","filename":"emqx-export-2021-1-25-2-43-47.json","created_at":"2021-1-25 2:43:47"},"code":0}

**How to reproduce it (as minimally and precisely as possible)**:
100% reproducible

**Anything else we need to know?**:

I came with a docker-compose stack for the cluster emqx+tdengine usage.
I 'd like to make it all automatically but stuck at the importing data.
Using command 'emqx_ctrl data import' could work in the HEALTHCHECK command but I would like add it to the init.sh in curl container.

Here are part of the content of my docker-compose file.

version: '3'

services:
  emqx1:
    image: emqx/emqx:4.2.4
    environment:
    - "EMQX_NAME=emqx"
    - "EMQX_HOST=node1.emqx.io"
    - "EMQX_CLUSTER__DISCOVERY=static"
    - "EMQX_CLUSTER__STATIC__SEEDS=emqx@node1.emqx.io, emqx@node2.emqx.io"
      #ports:
      #- "18085:18083"
      #- "1885:1883"
    volumes:
      - ./emqx/export_data.json:/tmp/export_data.json
        #    healthcheck:
        #test: ["CMD-SHELL", "emqx_ctl data import /tmp/export_data.json || exit 1"]
        #interval: 15s
        #timeout: 5s
        #retries: 2
    networks:
      emqx-bridge:
        aliases:
        - node1.emqx.io

  emqx2:
    image: emqx/emqx:4.2.4
    environment:
    - "EMQX_NAME=emqx"
    - "EMQX_HOST=node2.emqx.io"
    - "EMQX_CLUSTER__DISCOVERY=static"
    - "EMQX_CLUSTER__STATIC__SEEDS=emqx@node1.emqx.io, emqx@node2.emqx.io"
      #    ports:
      #- "18086:18083"
      #- "1886:1883"
    volumes:
      - ./emqx/export_data.json:/tmp/export_data.json
        #healthcheck:
        #test: ["CMD-SHELL", "emqx_ctl data import /tmp/export_data.json || exit 1"]
        #interval: 15s
        #timeout: 5s
        #retries: 2
    networks:
      emqx-bridge:
        aliases:
        - node2.emqx.io

  haproxy:
    image: haproxy
    volumes:
    - ./haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
    ports:
      - "18083:18083"
      - "1883:1883"
      - "8081:8081"
    depends_on:
      - emqx1
      - emqx2
    networks:
      - emqx-bridge

  tdengine:
    image: tdengine/tdengine
    networks:
      emqx-bridge:
        aliases:
        - db.tdengine
    ports:
      - "6030-6041:6030-6041"

  curl:
    image: curlimages/curl
    environment:
      td_user: root
      td_passwd: taosdata
      td_sql: db.tdengine:6041/rest/sql
    depends_on:
      - tdengine
      - haproxy
    command: ["sh", "/init.sh"]
    volumes:
      - ./init/init.sh:/init.sh
    networks:
      - emqx-bridge

networks:
  emqx-bridge:
    driver: bridge

volumes:
  grafana_data: {}

**Comment by tigercl** [comment]
@qzheng527 Sorry for not replying to you in time, the return result of the HTTP request has told you that the required  parameters are missing, you can refer to this document: https://docs.emqx.io/en/broker/latest/advanced/data-import-and-export.html.

**Comment by qzheng527** [comment]
@tigercl 
I strictly followed the document as you mentioned.
I tried the upload command.

$ curl -i --basic -u admin:public -X POST "http://localhost:8081/api/v4/data/import" -d @/tmp/test.json
HTTP/1.1 200 OK
content-length: 37
content-type: application/json
date: Mon, 25 Jan 2021 02:42:29 GMT
server: Cowboy

{"message":"missing_required_params"}

Could you please tell me which parameters I missed?
Thanks.

**Comment by tigercl** [comment]
@qzheng527 Is it convenient for you to provide the content in the `/tmp/test.json` file?

**Comment by qzheng527** [comment]
@tigercl 
It is the content of my test.json.

{"version":"4.2","date":"2021-01-11 02:48:32","rules":[{"id":"tdengine_bridge","rawsql":"SELECT\n  *\nFROM\n  \"Servo\"","actions":[{"id":"data_to_webserver_1610333201193561681","name":"data_to_webserver","fallbacks":[],"args":{"payload_tmpl":"INSERT INTO demo.Servo VALUES(\n  now,\n  ${payload.slave_0_6064},\n  ${payload.slave_0_607A},\n  ${payload.slave_0_6079},\n  ${payload.slave_0_6078},\n  ${payload.slave_0_606C}\n)","path":"","$resource":"tdengine_db"}}],"enabled":true,"description":""}],"resources":[{"id":"tdengine_db","type":"web_hook","config":{"content_type":"application/json","headers":{"Authorization":"Basic cm9vdDp0YW9zZGF0YQ=="},"method":"POST","url":"http://db.tdengine:6041/rest/sql"},"created_at":null,"description":""}],"blacklist":[],"apps":[{"id":"admin","secret":"public","name":"Default","desc":"Application user","status":true,"expired":"undefined"}],"users":[{"username":"admin","password":"IxNGbDFbpP6cMdH8/TdarPVzwgg=","tags":"administrator"}],"auth_clientid":[],"auth_username":[],"auth_mnesia":[],"acl_mnesia":[],"schemas":[]}

**Comment by srinivaskada** [comment]
@tigercl and @qzheng527 we are also facing the same issue.
Is there any workaround?
Thanks!

**Comment by k32** [comment]
@srinivaskada Could you please post the exact error that you're getting and the logs from the EMQX cluster?

**Comment by srinivaskada** [comment]
@k32 
curl -i --basic -u admin:public -X POST "http://localhost:18083/api/v4/data/import" --data-binary @emqx-settings-local.json
HTTP/1.1 100 Continue

HTTP/1.1 200 OK
content-length: 37
content-type: application/json
date: Sat, 29 May 2021 09:48:25 GMT
server: Cowboy

{"message":"missing_required_params"}

**Comment by k32** [comment]
@srinivaskada Could you collect the logs from the EMQX cluster? (`log/emqx.log.*`)
Which exact version of EMQX are you using?
Could you post the contents of the json file?

**Comment by srinivaskada** [comment]
@k32 

1. Could you collect the logs from the EMQX cluster? (log/emqx.log.*)
>>
/opt/emqx/log $ ls
emqx.log.1    emqx.log.idx  emqx.log.siz  erlang.log.1  run_erl.log

/opt/emqx/log $ cat emqx.log.1 
2021-05-29 09:43:55.305 [critical] ===============================================================================
2021-05-29 09:43:55.305 [critical] This is an evaluation license that is restricted to 10 concurrent connections.
2021-05-29 09:43:55.305 [critical] If you already have a paid license, please apply it now.
2021-05-29 09:43:55.305 [critical] Or you could visit https://www.emqx.io/license to get a trial license.
2021-05-29 09:43:55.305 [critical] ===============================================================================

/opt/emqx/log $ cat emqx.log.idx 

/opt/emqx/log $ cat emqx.log.siz 
?

/opt/emqx/log $ 


2. Which exact version of EMQX are you using?
>> docker image emqx/emqx-ee:4.2.0

3. Could you post the contents of the json file?
>>
{"version":"4.2","date":"2021-05-11 15:13:08","modules":[{"id":"module:90022734","type":"redis_authentication","config":{"type":"single","super_cmd":"HGET mqtt_user:%u is_superuser","server":"redis:6379","sentinel":"","query_timeout":"5s","pool_size":8,"password_hash":"plain","password":"","database":0,"auto_reconnect":true,"auth_cmd":"HMGET mqtt_user:%u password","acl_cmd":"HGETALL mqtt_acl:%u"},"enabled":true,"created_at":"undefined","description":{"zh":"Redis 认证/访问控制","en":"Redis AUTH/ACL"}},{"id":"module:11b51d3e","type":"recon","config":{},"enabled":true,"created_at":"undefined","description":""},{"id":"module:a70730f3","type":"internal_acl","config":{"acl_rule_file":"etc/acl.conf"},"enabled":true,"created_at":"undefined","description":""},{"id":"module:1f4cef35","type":"retainer","config":{"storage_type":"ram","max_retained_messages":0,"max_payload_size":"1MB","expiry_interval":0},"enabled":true,"created_at":"undefined","description":""},{"id":"module:1fd8ae59","type":"hot_confs","config":{},"enabled":true,"created_at":"undefined","description":""},{"id":"module:1f026882","type":"presence","config":{"qos":0},"enabled":true,"created_at":"undefined","description":""}],"rules":[],"resources":[{"id":"resource:036659","type":"bridge_kafka","config":{"cacertfile":{"filename":"","file":""},"certfile":{"filename":"","file":""},"compression":"no_compression","keyfile":{"filename":"","file":""},"max_batch_bytes":"1024KB","min_metadata_refresh_interval":"3s","password":"","query_api_versions":true,"send_buffer":"1024KB","servers":"kafka:9092","ssl":false,"sync_timeout":"3s","username":"","verify":false},"created_at":null,"description":""}],"blacklist":[],"apps":[{"id":"admin","secret":"public","name":"Default","desc":"Application user","status":true,"expired":"undefined"}],"users":[{"username":"admin","password":"xSE09YVA7gkzUn/ryv/yWznNBag=","tags":"administrator"}],"auth_mnesia":[],"acl_mnesia":[],"schemas":[]}

**Comment by k32** [comment]
Thanks for the info. Indeed, the documentation on how to use the REST API for data importing is wrong. The API expects a JSON embedded inside another JSON for some reason. I edited your file like this:
```
{
  "file": "{\"acl_mnesia\": [], \"apps\": [{\"desc\": \"Application user\", \"expired\": \"undefined\", \"id\": \"admin\", \"name\": \"Default\", \"secret\": \"public\", \"status\": true}], \"auth_mnesia\": [], \"blacklist\": [], \"date\": \"2021-05-11 15:13:08\", \"modules\": [{\"config\": {\"acl_cmd\": \"HGETALL mqtt_acl:%u\", \"auth_cmd\": \"HMGET mqtt_user:%u password\", \"auto_reconnect\": true, \"database\": 0, \"password\": \"\", \"password_hash\": \"plain\", \"pool_size\": 8, \"query_timeout\": \"5s\", \"sentinel\": \"\", \"server\": \"redis:6379\", \"super_cmd\": \"HGET mqtt_user:%u is_superuser\", \"type\": \"single\"}, \"created_at\": \"undefined\", \"description\": {\"en\": \"Redis AUTH/ACL\", \"zh\": \"Redis 认证/访问控制\"}, \"enabled\": true, \"id\": \"module:90022734\", \"type\": \"redis_authentication\"}, {\"config\": {}, \"created_at\": \"undefined\", \"description\": \"\", \"enabled\": true, \"id\": \"module:11b51d3e\", \"type\": \"recon\"}, {\"config\": {\"acl_rule_file\": \"etc/acl.conf\"}, \"created_at\": \"undefined\", \"description\": \"\", \"enabled\": true, \"id\": \"module:a70730f3\", \"type\": \"internal_acl\"}, {\"config\": {\"expiry_interval\": 0, \"max_payload_size\": \"1MB\", \"max_retained_messages\": 0, \"storage_type\": \"ram\"}, \"created_at\": \"undefined\", \"description\": \"\", \"enabled\": true, \"id\": \"module:1f4cef35\", \"type\": \"retainer\"}, {\"config\": {}, \"created_at\": \"undefined\", \"description\": \"\", \"enabled\": true, \"id\": \"module:1fd8ae59\", \"type\": \"hot_confs\"}, {\"config\": {\"qos\": 0}, \"created_at\": \"undefined\", \"description\": \"\", \"enabled\": true, \"id\": \"module:1f026882\", \"type\": \"presence\"}], \"resources\": [{\"config\": {\"cacertfile\": {\"file\": \"\", \"filename\": \"\"}, \"certfile\": {\"file\": \"\", \"filename\": \"\"}, \"compression\": \"no_compression\", \"keyfile\": {\"file\": \"\", \"filename\": \"\"}, \"max_batch_bytes\": \"1024KB\", \"min_metadata_refresh_interval\": \"3s\", \"password\": \"\", \"query_api_versions\": true, \"send_buffer\": \"1024KB\", \"servers\": \"kafka:9092\", \"ssl\": false, \"sync_timeout\": \"3s\", \"username\": \"\", \"verify\": false}, \"created_at\": null, \"description\": \"\", \"id\": \"resource:036659\", \"type\": \"bridge_kafka\"}], \"rules\": [], \"schemas\": [], \"users\": [{\"password\": \"xSE09YVA7gkzUn/ryv/yWznNBag=\", \"tags\": \"administrator\", \"username\": \"admin\"}], \"version\": \"4.2\"}",
  "filename": "foo.json"
}
```

And it was imported. However, I am pretty sure it should not work like this, and should accept the original file. I will submit another issue to get this API reworked.

As a workaround you can use CLI command for data import.

**Comment by srinivaskada** [comment]
It worked! 👍 
@k32 Thank you for the quick response.
