### ISSUE TITLE
Rule engine slow down performance 25%

### ISSUE THREAD

**Issue by JaylinYu** [emqx/emqx#4076]
- EMQ X version (e.g. `emqx_ctl status`): 
- 4.3.0
- Hardware configuration (e.g. `lscpu`):
- Intel(R) Core(TM) i7-10710U CPU @ 1.10GHz
- OS (e.g. `cat /etc/os-release`):
- ubuntu 20.04
- Kernel (e.g. `uname -a`):
- Linux jaylin-XPS-playgorund 5.8.0-38-generic #43~20.04.1-Ubuntu SMP Tue Jan 12 16:39:47 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

rule engine causes performance degradation even when there is no rules configured.

**Comment by HJianBo** [comment]
@JaylinYu We have fixed and released it to 4.3-beta.1
