### ISSUE TITLE
Some questions for emqx-edge

### ISSUE THREAD

**Issue by clh-cod** [emqx/emqx#4090]
Excuse me,I have some questions for emqx-edge.
1.what is the maximum cache time for emqx-edge?
2.Where can I see the cached data?
Thanks a lot!

**Comment by HJianBo** [comment]
EMQX Edge does not cache any data, it is more like an edge-side gateway. It is responsible for exchanging messages between edge-side devices and bridging the needed data to the cloud. All these operations are in real-time.

**Comment by HJianBo** [comment]
In addition, edge-side we have a whole set of solution products, and most of them are open source you can refer to: https://github.com/emqx/edge-stack

**Comment by clh-cod** [comment]
![image](https://user-images.githubusercontent.com/69289383/106084508-75b96500-6159-11eb-8a48-1aa730ae0c14.png)
Official documents say so

**Comment by clh-cod** [comment]
Maybe I didn't express myself clearly,I want to ask when emqx-edge bridge data to emqx-broker,while the network is disconnected,where can I see the cached data?

**Comment by HJianBo** [comment]
This depends on the configuration of the queue in emqx_bridge_mqtt.conf. see:

```
## Base directory for replayq to store messages on disk
## If this config entry is missing or set to undefined,
## replayq works in a mem-only manner.
##
## Value: String
bridge.mqtt.aws.queue.replayq_dir = {{ platform_data_dir }}/replayq/emqx_aws_bridge/

## Replayq segment size
##
## Value: Bytesize
bridge.mqtt.aws.queue.replayq_seg_bytes = 10MB

## Replayq max total size
##
## Value: Bytesize
bridge.mqtt.aws.queue.max_total_size = 5GB
```

**Comment by clh-cod** [comment]
```
bridge.mqtt.aws.queue.replayq_seg_bytes = 10MB
bridge.mqtt.aws.queue.max_total_size = 5GB
```
Can I configure the cache size? If I configure this field,whether it will affect the performance of emqx-edge?

**Comment by HJianBo** [comment]
Yes, you can. It is limited by the amount of memory or disk you have. But I think this default configuration is sufficient
