### ISSUE TITLE
How does bridge plugin works?

### ISSUE THREAD

**Issue by LLLLimbo** [emqx/emqx#4091]
**Please describe your problem in detail, if necessary, you can upload the log file through the attachment**:
Does it forward message to cloud as a mqtt client ?

**Comment by tigercl** [comment]
@LLLLimbo Yes, you are right, please refer to the following documents for more information: https://docs.emqx.io/en/broker/latest/advanced/bridge.html

**Comment by LLLLimbo** [comment]
> @LLLLimbo Yes, you are right, please refer to the following documents for more information: https://docs.emqx.io/en/broker/latest/advanced/bridge.html

thanks
