### ISSUE TITLE
Multi-tenancy support

### ISSUE THREAD

**Issue by leoandrea7** [emqx/emqx#4104]
Any plan to support multi-tenancy in emqx?

**Comment by tigercl** [comment]
@leoandrea7 Currently we support coarse-grained multi-tenancy through the Zone & Listener mechanism. I don’t know if it can meet your needs. You can refer to: https://docs.emqx.io/en/broker/latest/getting-started/config.html#zone-listener.

**Comment by leoandrea7** [comment]
Zone & Listener mechanisms are good features, but it can't be consider as multi-tenancy. 
Multi-tenancy should be managed by emqx-broker and cannot be responsibility of the user to configure segregation. 
I know that multi-tenancy is very hard to implement and it will take a long time, but I'd like to know if its support has been planned.
Thanks.

**Comment by zmstone** [comment]
I might be wrong here, pease correct me if that's the case @tigercl 

at the current state, in emqx, we do not have a resource quota booking syb-system to support multi-tenancy.
It has been discussed internally in different channels, but we have not yet get the chance to prioritise it.

Our next focus is to improve cluster scalability and stability.

**Comment by wwhai** [comment]
> Any plan to support multi-tenancy in emqx?

 Multi-tenancy is part of business system, EMQX is a broker; such mysql or nginx can't support this feature, It's depends on your business manage system.

**Comment by zmstone** [comment]
> > Any plan to support multi-tenancy in emqx?
> 
> Multi-tenancy is part of business system, EMQX is a broker; such mysql or nginx can't support this feature, It's depends on your business manage system.

EMQ X must at least provide a resource consumption booking system to support a pricing model for multi-customer platform such as SaaS.
Whether or not to fully feature the entire business flow is perhaps debatable.

And to be fully transparent here, since EMQ provides SaaS (check it out here: https://cloud.emqx.io/),
whether or not we will provide this feature in EMQ X open-source edition is also a question mark.

**Comment by zmstone** [comment]
I am closing this issue for now.
Feel free to continue commenting though, if there are more to discuss.

**Comment by zmstone** [comment]
An update: multitenancy is supported now: https://www.emqx.com/en/cloud/serverless-mqtt
Not opensource though.
