### ISSUE TITLE
Showing "codeMsg": "bad_request", "code"   :"4.00" when observing a self-defined resource

### ISSUE THREAD

**Issue by threekami** [emqx/emqx#4130]
Showing "codeMsg": "bad_request", "code"   :"4.00" when observing a self-defined resource: /32000/0/6, while other default objects /3/0 have values.

**Comment by tigercl** [comment]
@threekami I'm sorry I didn't understand what you mean. Could you describe it in detail?

**Comment by HJianBo** [comment]
Resolved/Duplicated on https://github.com/emqx/emqx-lwm2m/issues/107
