### ISSUE TITLE
Error when publishing large payloads

### ISSUE THREAD

**Issue by magallardo** [emqx/emqx#4132]
**Please describe your problem in detail, if necessary, you can upload the log file through the attachment**:
I am trying to publish a big payload and getting a "Parse failed for frame_too_large" error.

I have tried the same payload with Mosquitto MQTT and it works fine.  Is any limits to the payload size in emqx? 

I am attaching the error from the console.

Thanks,
Marcelo

[emqxerror.log](https://github.com/emqx/emqx/files/5907085/emqxerror.log)

**Comment by magallardo** [comment]
@tigercl Thanks for the prompt response.

Could you please indicate what is the default max_packet_size?  Also, I am running the docker image for emqx.  Can I provide that parameter in the docker-compose file? 

Thanks,
Marcelo

**Comment by tigercl** [comment]
@magallardo The default limit is 1MB.

**Comment by k32** [comment]
Hello,
There have been great improvements in the handling of large frames in this PR: https://github.com/emqx/emqx/pull/4802
It's been released in 4.3
