### ISSUE TITLE
Rule engine cannot process MySQL params if it contains apostrophes

### ISSUE THREAD

**Issue by terry-xiaoyu** [emqx/emqx#4135]
**Environment**:

- EMQ X version (e.g. `emqx_ctl status`): enterprise 4.2.3
- Erlang/OTP version (in case you build emqx from source code): 22.3.0
- Others:

Hello Everybody,

While trying the rule_engine to mysql it seems there is a bug when the payload contains apostrophe like "someone's example", as escaping the apostrophe is not handled correctly.
and this is happening when the function
SQLParamPart = emqx_rule_utils:proc_sql_param_str(SQLParamPartTks, Msg), is called (emqx_backend_mysql_actions.erl /line 415).

//Best Regards
Wisam

**How to reproduce it (as minimally and precisely as possible)**:

Try to insert string values into MySQL with apostrophes like:

`INSERT INTO Persons VALUES ('Gates's Phone', 18267854320)`

And make sure we've enabled the **batch insertion**.

**Comment by HJianBo** [comment]
This issue has been fixed and released into 4.3-beta.1
