### ISSUE TITLE
Failed to read emqx_auth_redis.conf

### ISSUE THREAD

**Issue by HALOXIAO** [emqx/emqx#4138]
Env:
Win10、CentOS8
Redis version：5.0.3
emq version：4.2.3

desc ：
defaulit conf success;
if i change acl_file 
![1612338440(1)](https://user-images.githubusercontent.com/45111269/106714672-22528580-6637-11eb-84a5-d56cd169ac04.png)
log：
![微信截图_20210203154819](https://user-images.githubusercontent.com/45111269/106714768-42824480-6637-11eb-8f27-bdfea8c23bf7.png)

i can connect my redis

maybe it's a bug ?

**Comment by tigercl** [comment]
@HALOXIAO If you have checked the default acl_file, which is the content of `acl.conf`, you will find that its format is completely different from `emqx_auth_redis.conf`. So if you want to specify other file names, please follow the format in `acl.conf`.
