### ISSUE TITLE
Want to create Rule and Resources to Send data to Web API

### ISSUE THREAD

**Issue by hellohasib** [emqx/emqx#4141]
Hi,

I have been using EMQX Enterprise trial in my PC to receive data from client(Publisher). I have created rule and resource that can process JSON data sent from my client and can insert the data to MySQL Table. Meanwhile I have created some APIs with Node JS and express that can send/ receive data via postman. 

I want to know, instead of sending my Data to MySQL, I want to POST directly to my API. My POST API url is like, http://localhost:8012/api/customer/new. Can I do it? If anyone has done something like this before, would love to know your experience.

Thanks.

**Comment by terry-xiaoyu** [comment]
Then you could have a try the webhook resource.

**Comment by HJianBo** [comment]
Close it first, if you have any updates please re-open it
