### ISSUE TITLE
Error when using raspberrypi and docker to start emqx-ee4.2.3

### ISSUE THREAD

**Issue by wanziyu** [emqx/emqx#4145]
- EMQ X version :4.2.3
- OS : raspbian
- CPU: ARMV7

When I use the docker command "docker run -d --name emqx-ee -p 1883:1883 -p 8083:8083 -p 8883:8883 -p 8084:8084 -p 18083:18083 emqx/emqx-ee:4.2.3". 

The emqx is failed and the docker logs are: 

node.max_ports=1048576
listener.tcp.external.acceptors=64
listener.ssl.external.acceptors=32
node.process_limit=2097152
node.max_ets_tables=2097152
listener.ws.external.acceptors=16
node.name=c776c7dec9c6@172.17.0.3

=====
===== LOGGING STARTED Thu Feb  4 04:11:57 UTC 2021
=====
2021-02-04T04:12:01.103237+00:00 [error] Error generating configuration in phase apply_translations
2021-02-04T04:12:01.103523+00:00 [error] Translation for 'emqx.zones' found invalid configuration: force_shutdown_policy: heap-size 128MB is too large
['2021-02-04T04:12:38Z']:emqx exit abnormally

How can I use raspberrypi4B to start emqx-ee?

**Comment by Rory-Z** [comment]
Hi，@wanziyu
The reason for the startup failure is that the default value of `zone.internal.force_shutdown_policy` is too large, you can make it smaller
