### ISSUE TITLE
How could i get clientId when messageArrived

### ISSUE THREAD

**Issue by Narvie** [emqx/emqx#4152]
How could i get clientId when messageArrived,
I'm using paho mqtt on server side.
Thanks a lot

**Comment by terry-xiaoyu** [comment]
If you're using the python mqtt client library for example, you could get the client_id from the `client` instance. You could always get the information from the online docs for your library.

**Comment by Narvie** [comment]
> If you're using the python mqtt client library for example, you could get the client_id from the `client` instance. You could always get the information from the online docs for your library.

你好，看得出我可以用汉语了。  
我用的emqx broker，设备端向服务端指定topic发送报文消息，服务端有几个client订阅了指定的topic，接到消息后对消息进行业务处理。
现想要在服务端接到消息时能判断出是哪一个设备，在服务端的client接到设备端发来的消息时，无法获得设备端的clientId。
在阅读文档和相关代码后没有找到解决方案。请指教，谢谢
