### ISSUE TITLE
No Local

### ISSUE THREAD

**Issue by sm2017** [emqx/emqx#4153]
I am using `mqtt@4.2.6` for a nodejs application

```js
const options = {nl :true};
client.subscribe(topic, options, callback)
```

I set `nl` to `true`

>`nl` No Local MQTT 5.0 flag (If the value is true, Application Messages MUST NOT be forwarded to a connection with a ClientID equal to the ClientID of the publishing connection)

Whenever I publish a message to the topic, the publisher get the message in message listener too, What's wrong here

**Comment by terry-xiaoyu** [comment]
Not sure this is the fault of your Node.JS MQTT lib, I tried it using [emqtt](https://github.com/emqx/emqtt) and it works as expected:

In the emqx's erlang console (you could attach to the console by `emqx attach`, and type `Ctrl+D` to quit):

```
{ok, T1} = emqtt:start_link([{host, "localhost"},
                             {clientid, <<"client1">>},
                             {username, <<"testuser1">>},
                             {password, <<"pass1">>},
                             {proto_ver, v5}
                             ]).

{ok, _} = emqtt:connect(T1).
emqtt:subscribe(T1, <<"t">>, [{nl, true}, {qos, 0}]).
emqtt:publish(T1, <<"t">>, <<"body">>, [{qos, 0}, {retain, false}]).

flush().

```

No PUBLISH msgs are received by the publisher itself.

**Comment by sm2017** [comment]
I found the problem, The client used MQTT v4 by default I set v5 and it works now
