### ISSUE TITLE
Log trace failed if client-id is too long

### ISSUE THREAD

**Issue by edison20201018** [emqx/emqx#4157]
```
trace start client 'fooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo' log/abc.log warning

RPC to emqx@127.0.0.1 error: system_limit
```

The command works on short client-ids though.

**Comment by terry-xiaoyu** [comment]
Creating the log handler failed when converting the client-id to the handler id (list_to_atom), if the client-id is too long (longer than 255 characters).

**Comment by terry-xiaoyu** [comment]
Then we may need one more argument to the CLI to let the user assign a log handler id, like:

```
trace start client foo 'fooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo' log/abc.log warning
```
Above example will create a log handler with id `foo`.

**Comment by terry-xiaoyu** [comment]
As another approach we could use UUID as handler-id. But this way we have to maintain a mapping between the handler-ids and client-ids. The problem becomes more complicated if the process maintaining the mapping crashed and restarted.

Hash is also not applicable as we have to solve the conflicts.

**Comment by zmstone** [comment]
is it possible not to use binary() for tracing (instead of atom()) ?
if not, sha it to avoid having to maintain a mapping.

**Comment by terry-xiaoyu** [comment]
@zmstone It's not possible avoid using atoms: https://erlang.org/doc/man/logger.html#add_handler-3

Then SHA looks like a good option.
