### ISSUE TITLE
Decoded data to InfluxDB results with undefined 

### ISSUE THREAD

**Issue by muhsin1975** [emqx/emqx#4161]
My devices are forwarding binary data in protobuf format and I am able to decode it using schema registry. I can handle the fields in the data. I tested it by republishing the decoded data to websocket. Althoug i can read any attribute of the republished data, when i forward it to influxdb the same field's data is written as undefined.
My schema is

message FBDATA{
  required double paketID=1;
  required double timestamp=2;
  required double x_state=3;
  required double y_state=4;
  required double yaw_state=5;
  required double velocity=6;
  required double v_state=7;
  required double omega_state=8;
  required double lifter_state=9;
  required double x_prev_target=10;
  required double yaw_prev_target=11;
  required double up_camera_x_state=12;
  required double up_camera_y_state=13;
  required double up_camera_angle_state=14; 
  required double temperature=15;
  required double battery_status=16;
  required double kalman_feed_angle_encoders=17;
  required double kalman_feed_angle_imu=18;
  required double kalman_response=19;
  required fixed32 qrCode=20;  
  required bytes  motionActionOrientation=21;
 
}

my rule is

SELECT

  schema_decode('SCHEMA_FBDATA',  payload,  'FBDATA') AS feedback,clientid
FROM
  "FBDATA/#"

I can read ${feedback.x_state} through websocket but when i send it to influx measurement i see undefined
time                agent x_state
----                ----- -------
1612796397660000000 Bot0  undefined
1612796399661000000 Bot0  undefined
> 
Thanx

P.S.I am able to save the data to cassandra db. via rule

**Comment by muhsin1975** [comment]
![rule](https://user-images.githubusercontent.com/56269599/107330492-acc93800-6ac2-11eb-8fbc-5efc2d1477cf.png)
![websocket](https://user-images.githubusercontent.com/56269599/107330511-b5ba0980-6ac2-11eb-9329-fd784664b805.png)
Rule and websocket screenshots attached

**Comment by terry-xiaoyu** [comment]
First I want to confirm what's the emqx version you are using. Always make sure you are using the latest enterprise version (it's 4.2.3 for now) as it contains the lasted bug fixes.

And you could add a `inspect` action beside the two actions you've added. This way when the action is triggered, the params and envs will be printed to the emqx console for debugging. You could get the prints from `log/erlang.log.*` files.

Post the prints out here after you get them :-)

**Comment by muhsin1975** [comment]
emqx version is 4.2.3 output of inspect is;
inspect]
        Selected Data: #{<<"clientid">> => <<"Bot0">>,
                         <<"feedback">> =>
                             #{battery_status => 99.98,
                               kalman_feed_angle_encoders => 0.0,
                               kalman_feed_angle_imu => 0.0,
                               kalman_response => 0.0,lifter_state => 0.0,
                               motionActionOrientation => <<1,0,0>>,
                               omega_state => 0.0,paketID => 0.0,
                               qrCode => 290,temperature => 20.0,
                               timestamp => 1612882965.4080868,
                               up_camera_angle_state => 0.0,
                               up_camera_x_state => 0.0,
                               up_camera_y_state => 0.0,v_state => 0.0,
                               velocity => 0.0,x_prev_target => 0.0,
                               x_state => 19.25,y_state => 11.2,
                               yaw_prev_target => 0.0,yaw_state => 0.0}}
        Envs: #{'__bindings__' =>
                    #{'Id' => <<"inspect_1612871974170951258">>,
                      'Params' => #{}},
                clientid => <<"Bot0">>,event => 'message.publish',
                flags => #{dup => false,retain => false},
                headers =>
                    #{peerhost => <<"192.168.1.85">>,properties => #{},
                      proto_ver => 5,protocol => mqtt,username => undefined},
                id => <<"5BAE60F8EAF30FE0C0200470D00C9">>,
                metadata => #{rule_id => <<"rule:f9557856">>},
                node => '15c3cb036304@172.17.0.2',
                payload =>
                    <<9,0,0,0,0,0,0,0,0,17,24,30,90,5,169,8,216,65,25,0,0,0,0,
                      0,64,51,64,33,102,102,102,102,102,102,38,64,41,0,0,0,0,0,
                      0,0,0,49,0,0,0,0,0,0,0,0,57,0,0,0,0,0,0,0,0,65,0,0,0,0,0,
                      0,0,0,73,0,0,0,0,0,0,0,0,81,0,0,0,0,0,0,0,0,89,0,0,0,0,0,
                      0,0,0,97,0,0,0,0,0,0,0,0,105,0,0,0,0,0,0,0,0,113,0,0,0,0,
                      0,0,0,0,121,0,0,0,0,0,0,52,64,129,1,31,133,235,81,184,
                      254,88,64,137,1,0,0,0,0,0,0,0,0,145,1,0,0,0,0,0,0,0,0,
                      153,1,0,0,0,0,0,0,0,0,165,1,34,1,0,0,170,1,3,1,0,0>>,
                peerhost => <<"192.168.1.85">>,pub_props => #{},
                publish_received_at => 1612872149806,qos => 0,
                timestamp => 1612872149807,topic => <<"FBDATA/Bot0">>,
                username => undefined}
        Action Init Params: #{}

**Comment by muhsin1975** [comment]
Hello... were u able to find chance to have a look at the issue ?

**Comment by muhsin1975** [comment]
I found a way to solve the issue. I changed the query to 
select
    schema_decode('SCHEMA_FBDATA',  payload,  'FBDATA') as feedback, clientid,
    feedback.x_state as x_state
    FROM
  "FBDATA/#"

and use ${x_state} in fields list to influx. It is working in this way. So the problem was at the ${feedback.} part of the decleration. May be you wish to check it.
Thanks for the support
