### ISSUE TITLE
Shared subscription behavior in combination with clean start

### ISSUE THREAD

**Issue by frank-montyne** [emqx/emqx#4171]
**What would you like to be added/modified**:
See scenario below.

**Why is this needed**:
Autoscaling of ingestion using multiple shared subscription subscribers with clean start false.

 At this point in time there is only one MQTT server that does this as one would expect: HiveMQ
EMQX and VerneMQ require fixed subscriber id's to work at all but the following scenario works in a completely unusable fashion:
 
Scenario:
subscriber1: clientId = "c1", topic = "$share/group1/topic1/#", cleanStart = false, sessionExpiryInterval = 1 day, max QoS = 2
subscriber2: clientId = "c2", topic = "$share/group1/topic1/#", cleanStart = false, sessionExpiryInterval = 1 day, max QoS = 2
publisher: clientId = "p1", topic = "topic1", cleanStart = true (irrelevant for a publisher), QoS = 1
 
Start subscriber1 and subscriber2
Publish 100 messages
Expected result: subscriber1 and subscriber2 get each a subset of the messages published
EMQX: OK
VerneMQ: OK
HiveMQ: OK
 
Disconnect subscriber1
Publish 100 messages
Expected result: subscriber2 gets all the messages published
EMQX: OK after setting EMQX_BROKER__SHARED_DISPATCH_ACK_ENABLED=true 
VerneMQ: OK
HiveMQ: OK

Disconnect subscriber2
Publish 100 messages
Expected result: all messages should be buffered at the server side
EMQX: OK 
VerneMQ: OK
HiveMQ: OK
 
Restart subscriber1 with the same parameters
Publish 100 messages
Expected result: subscriber1 gets all the messages published
EMQX: NOT OK, only a subset of the messages are received. Also you need to restart the subscriber1 with the same clientId, if not, no messages are received.
VerneMQ: NOT OK, only a subset of the messages are received. Also you need to restart the subscriber1 with the same clientId, if not, no messages are received.
HiveMQ: OK, all messages are received. The subscriber1 can also be restarted with another clientId, the messages will still be received.

Restart subscriber2
Expected result: subscriber2 gets no messages since subscriber1 already got them all
EMQX: NOT OK, the remaining messages are received. Also you need to restart the subscriber2 with the same clientId, if not, no messages are received.
VerneMQ: NOT OK, the remaining messages are received. Also you need to restart the subscriber2 with the same clientId, if not, no messages are received.
HiveMQ: OK, no messages are received. The subscriber2 can also be restarted with another clientId.
 
When using shared subscriptions in combination with cleanStart = false, sessionExpiryInterval = x seconds, max QoS > 0 the client id of the subscriber should be irrelevant. The session parameters should be hooked to the shared topic subscription, not the client id. This is the only workable solution in environments like Kubernetes where pods are being created/deleted to scale up/scale down ingestion. A pod in this case is roughly equivalent to a shared subscriber. It's also important that in this case the subscriber client id can be a random string otherwise this becomes a management nightmare.

At this point HiveMQ is the only MQTT server that has an implementation that is suitable for scenario's like this one.    
This is an important feature to support for dynamically scalable deployments.

Thanks,
Frank Montyne

**Comment by zmstone** [comment]
Hi @frank-montyne 

EMQX currently does not provide message queueing outside of client sessions.
i.e. messages for shared subscription in EMQX is designed to be sent (and stored) in per-client sessions.
Once a message is sent to a session, other clients (identified by a different ID) can not 'steal' it.

I agree that this is a reasonable requirement, however it's hard to say when we will have the resource to develop it.

**Comment by frank-montyne** [comment]
Thanks for the reply. Like I said in dynamically scalable environments like Kubernetes this is almost a must in order to be usable. I hope this feature will be come available in the near future.

**Comment by frank-montyne** [comment]
Any progress already on this feature request?

**Comment by zhangli2946** [comment]
@frank-montyne 
Consumers leave "the group" before disconnecting from broker. 
Ensuring at lease one consumer keeps alive in "the group",  messages will be rehashed to those alive.

**Comment by zhangli2946** [comment]
![image](https://user-images.githubusercontent.com/3656511/165198771-dbb4b2bc-3e52-4aea-9349-10d850f847ec.png)

The consumers works just fine when enabling those lines

**Comment by rod2j** [comment]
This is the must have feature that will prevent us to ever use Emqx. 
We need elactic scaling. Sticking a message to a client session (offline) that might never come back is just not compatible with modern infrastructure as @frank-montyne explained it before. 
I'm seriously considering dropping MQTT all at once, completly, from device, edge to cloud.

**Comment by zmstone** [comment]
EMQX v5 now sends queued messages from an expiring session to other alive sessions in the group.

For QoS 0 messages, no redelivery
For QoS 1 messages, inflight message (sent but not acked) are also redelivered.
For QOS 2 messages, only queued messages are redelivered.

NOTE:  `EMQX_BROKER__SHARED_DISPATCH_ACK_ENABLED` is dprecated.
