### ISSUE TITLE
Doc: wrong acl reload command & missing acl placeholder

### ISSUE THREAD

**Issue by gbrehmer** [emqx/emqx#4174]
**Environment**:

- EMQ X version (e.g. `emqx_ctl status`): 4.2.7

Please update documentation:
- fix acl reload command `./bin/emqx_ctl acl reload` (https://docs.emqx.io/en/broker/latest/advanced/acl-file.html) - current one is `./bin/emqx_ctl modules reload emqx_mod_acl_internal`
- missing placeholder documentation for internal acl file: because placeholder has changed between each major emq/emqx version (%u -> $u -> %u), it should be explicitly documented on the internal or overall acl page. because I used emqx-auth-http plugin I thought acl check by http call was the cause for my acl errors and it takes me some time to find the root cause.

**Comment by zmstone** [comment]
Thank you for reporting this @gbrehmer
We will prioritise this change soon.

**Comment by HJianBo** [comment]
Hi guys, I have opened  https://github.com/emqx/emqx-docs/pull/640 for it. Pls review it
