### ISSUE TITLE
listener.ws.external.proxy_address_header and listener.ws.external.proxy_port_header not working

### ISSUE THREAD

**Issue by dsilletti** [emqx/emqx#4184]
**Environment**:

- EMQ X version: 4.2.7 Official Docker container

**What happened and what you expected to happen**:

I configured emqx according to the last user guide wit the following env variables in my docker-compose file:
      - EMQX_listener__ws__external__proxy_address_header=X-Forwarded-For
      - EMQX_listener__ws__external__proxy_port_header=X-Forwarded-Port

nginx is also configured according to the guide as follows:

        proxy_set_header X-Forwarded-Port $server_port;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

but I still have the nginx private IP address in the client list.

**How to reproduce it (as minimally and precisely as possible)**:

Configure emqx 4.2.7 broker with:
- EMQX_listener__ws__external__proxy_address_header=X-Forwarded-For
- EMQX_listener__ws__external__proxy_port_header=X-Forwarded-Port

and nginx with:

proxy_set_header X-Forwarded-Port $server_port;
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

**Comment by dsilletti** [comment]
any update on this issue? Thanks

**Comment by zmstone** [comment]
Hi @dsilletti 
I can't seem to find `EMQX_listener__ws__external__proxy_` configs in the code base.
Which user guide did you follow ?

So far I managed to find some info:
1. There are not such configs in EMQ X
2. The config `EMQX_listener__ws__external__proxy_protocol` should be set `true` for EMQ X to read proxy headers
3. The underlying HTTP server implementation follows the HAProxy binary PROXY protocol: https://www.haproxy.org/download/1.8/doc/proxy-protocol.txt. But not the (deprecated?) `X-Forwarded-` http headers.
I am not sure how exactly nginx is to be configured though.

**Comment by dsilletti** [comment]
Hi @zmstone,
I am using emqx 4.2 and I configured the listener.ws.external.proxy_address_header and listener.ws.external.proxy_port_header according to the official emqx broker v4.2 guide: 
https://docs.emqx.io/en/broker/v4.2/configuration/configuration.html#listener-ws-external-proxy-address-header and https://docs.emqx.io/en/broker/v4.2/configuration/configuration.html#listener-ws-external-proxy-port-header 
These options are in the official guide so I don't think are deprecated, the nginx config is sending the correct headers but on emqx dashboard I cannot see the real client IP address and port.
NGINX can forward the proxy protocol from a load balancer but cannot generate it so proxy protocol it's not an option with a standalone NGINX frontend

**Comment by zmstone** [comment]
Hi. @dsilletti 
The configs have been deleted since 1790cde9 (released in v4.1.0), but the document was not updated.
In fact, before v4.1.0, the configs were added but for some reason, the code was never implemented to make use of the headers.
Sorry for the lack of competence here, but I would recommend you to give `EMQX_listener__ws__external__proxy_protocol=true` a try.

And add `proxy_protocol on;` to nginx config. 
ref: https://docs.nginx.com/nginx/admin-guide/load-balancer/using-proxy-protocol/#proxy-protocol-for-a-tcp-connection-to-an-upstream

Sorry for my mistake, we will add back the headers config and make use headers if they are present as a supplement to proxy protocol.

**Comment by zmstone** [comment]
Hi again @dsilletti 

I will start working on the supports for HTTP headers soon.
So users can use either http proxy and tcp load balancing.

**Comment by dsilletti** [comment]
Hi @zmstone, this is a great news!
Thank you for your support
