### ISSUE TITLE
Hot Upgrade for major and minor versions

### ISSUE THREAD

**Issue by Kidsan** [emqx/emqx#4193]
**What would you like to be added/modified**:
I would like to be able to upgrade my EMQX cluster in place for major and minor versions.

**Why is this needed**:
With 4.2.0 you added support for hot upgrades of patch versions, but extending this to major (or at least minor) versions would be hugely useful. I am running a cluster in production on Kubernetes, and upgrading from 4.0.X to 4.2.X ended up requiring production downtime because the pods couldn't be updated in place as far as I could see.

**Comment by terry-xiaoyu** [comment]
Hot upgrading between major (or even minor) versions is almost not possible, as it requires too large cost on maintaining and testing work.

When releasing a new version we have to consider both the hot-upgrading and backward compatibility, that's hard especially when some of the data structure or configuration is changed. For major releases even the backward compatibility is not passible as the architecture is changed, For those reasons, I suspect no software claims that they support hot-upgrade between `major` releases.

**Comment by Kidsan** [comment]
I understand that major versions may be unrealistic, but I would think that minor version upgrading should be evaluated. By definition a minor update shouldn't be a breaking change. At the very least I would think there should be a suggestion made on how upgrades in production can be done (in my case on Kubernetes) without downtime or with minimised downtime.

**Comment by terry-xiaoyu** [comment]
That would be nice, we may support hot-upgrading between minor versions in some degree, maybe after 5.0 but I'm not sure.
It is difficult for two reasons:

- Some of the internal data structure may have to be changed, for fixing an issue or adding a feature. To support hot upgrading for this is possible but need lots of testing work - again it is about cost.

- The Erlang OTP it self may have critical issues that need to upgrade, and we cannot do hot upgrade in this case. The minor version is a good place to upgrade Erlang OTP versions.

**Comment by Kidsan** [comment]
@terry-xiaoyu That makes sense, thanks for the info.
