### ISSUE TITLE
ACL and rewrite are handled differently for subscribe and publish

### ISSUE THREAD

**Issue by MikaelElkiaer** [emqx/emqx#4200]
**Environment**:

- EMQ X version (e.g. `emqx_ctl status`): 4.2.7
- Hardware configuration (e.g. `lscpu`): N/A
- OS (e.g. `cat /etc/os-release`): N/A
- Kernel (e.g. `uname -a`): N/A
- Erlang/OTP version (in case you build emqx from source code):  N/A
- Others: Via Docker version

**What happened and what you expected to happen**:
Having the rewrite rules:
```
module.rewrite.sub.rule.1 = # ^([a-f0-9]{24}.*)$ prefix/$1
module.rewrite.pub.rule.1 = # ^([a-f0-9]{24}.*)$ prefix/$1
```
The subscription topic and the publish topic are both rewritten as expected.
However, combining this with HTTP ACL, it differs when the topic is checked up against the ACL endpoint.
For subscription, it is done after rewriting. So checking up against the topic `prefix/#` works fine.
For publish, it is done before rewriting. So doing the same check up against the topic `prefix/#` will not work, as the publish topic has not been rewritten yet.

**How to reproduce it (as minimally and precisely as possible)**:
Using the rewrite rules above, along with an ACL that will only allow `prefix/#` topic.
Subscription will work, publish will not.

**Anything else we need to know?**:

**Comment by tigercl** [comment]
@MikaelElkiaer Thank you very much for your feedback. This is indeed an unreasonable implementation. We will fix this issue in subsequent versions. Thanks again for your contribution to our project.

**Comment by Rory-Z** [comment]
Hi, @MikaelElkiaer Sorry for delay

> For subscription, it is done after rewriting. So checking up against the topic prefix/# works fine.

This is inconsistent with my test results, I created the following rewrite rule
```
module.rewrite.sub.rule.1 = # ^(.*)$ prefix/$1
module.rewrite.pub.rule.1 = # ^(.*)$ prefix/$1
```
 and I created the following acl rule
```
{allow, all, pubsub, ["prefix/#"]}.

{deny, all}.
```
and I subscribe `test` topic, and I'm failed.

This shows that our acl check is performed before rewriting, not after rewriting, this is consistent with publish behavior

**Comment by MikaelElkiaer** [comment]
Could the behaviour be different for HTTP ACL? Because that is the one I'm using, where I am seeing the behaviour I described.

**Comment by Rory-Z** [comment]
@MikaelElkiaer Okay, I will test http acl later

**Comment by Rory-Z** [comment]
Hi, @MikaelElkiaer Sorry for delay

This is a bug, we will fix this on next version
