### ISSUE TITLE
SSL/TLS don't working

### ISSUE THREAD

**Issue by XxKavosxX** [emqx/emqx#4202]
Please, can you guys help-me? I have tried this tutorial 

[emqx-server-ssl-tls-secure-connection-configuration-guide](https://www.emqx.io/blog/emqx-server-ssl-tls-secure-connection-configuration-guide)

Currently i'm running the emqx-edge on my RaspberryPi3B+ at fixed IP = 192.168.0.5.

And using the MQTTX (with the my_root_ca.pem as the tutorial) from my PC (same localnetwork) to connect to the broker. 

But i still can't connect to the broker

MQTTX client return

`Error: read ECONNRESET`

The log

/var/etc/emqx/emqx.log.1

`
2021-02-18 08:08:23.533 [error]     supervisor: 'esockd_connection_sup - <0.1356.0>'
    errorContext: connection_shutdown
    reason: {ssl_error,
                {options,{keyfile,"/etc/emqx/certs/emqx.key",{error,eacces}}}}
    offender: [{pid,<0.1438.0>},
               {name,connection},
               {mfargs,
                   {emqx_connection,start_link,
                       [[{deflate_options,[]},
                         {max_conn_rate,500},
                         {active_n,100},
                         {zone,external}]]}}]`

**Comment by zmstone** [comment]
`eacces` indicates file permission issue.
please make sure the users which runs `emqx` service should have permission to read.

**Comment by XxKavosxX** [comment]
> `eacces` indicates file permission issue.
> please make sure the users which runs `emqx` service should have permission to read.

@zmstone , trying that

Ensuring all privileges with  `$sudo chmod -R 777 .`   to the `/etc/emqx/certs`  folder

MQTTX client return

`Error [ERR_TLS_CERT_ALTNAME_INVALID]: Hostname/IP does not match certificate's altnames: IP: 192.168.0.5 is not in the cert's list`

**Comment by zmstone** [comment]
MQTTX client is trying to validate the hostname.
You may either
1. create cert for the real host (192.168.0.5)
2. disable verification in MQTTX

**Comment by XxKavosxX** [comment]
I recreate all the certs

openssl.cnf:

**[req]
default_bits  = 2048
distinguished_name = req_distinguished_name
req_extensions = req_ext
x509_extensions = v3_req
prompt = no
[req_distinguished_name]
countryName = CN
stateOrProvinceName = Zhejiang
localityName = Hangzhou
organizationName = EMQX
commonName = Server certificate
[req_ext]
subjectAltName = @alt_names
[v3_req]
subjectAltName = @alt_names
[alt_names]
IP.1 = 192.168.0.5**

Ensured the R+W privileges to the folder `/etc/emqx/certs`

Restarted the broker `service emqx restart`

And still getting the same error 

`Error [ERR_TLS_CERT_ALTNAME_INVALID]: Hostname/IP does not match certificate's altnames: IP: 192.168.0.5 is not in the cert's list`

Nothing in the emqx.log.1

**Comment by zmstone** [comment]
is it 192.1680.5 as the hostname in MQTTX ?

**Comment by XxKavosxX** [comment]
No MQTTX are running on my PC at IP=192.168.0.13

**Comment by zmstone** [comment]
I mean, which endpoint did you use to connect from MQTTX  GUI?
Is it a hostname or the exact IP?

**Comment by XxKavosxX** [comment]
That's my MQTTX client

![image](https://user-images.githubusercontent.com/12784642/108365023-95b5d480-71ab-11eb-8b25-255dad18a7ec.png)

CA cert copied from RaspberryPi

![image](https://user-images.githubusercontent.com/12784642/108365134-b7af5700-71ab-11eb-9141-da6951eb9dc6.png)

**Comment by zmstone** [comment]
could you try to inspect the certificate by this command
`openssl s_client -connect 192.168.0.5:8883 </dev/null 2>/dev/null | openssl x509 -noout -text`

**Comment by XxKavosxX** [comment]
`Certificate:
    Data:
        Version: 1 (0x0)
        Serial Number:
            7f:32:5b:99:03:f5:52:1e:6b:70:99:6b:fd:4a:7b:b9:e8:fe:73:84
        Signature Algorithm: sha256WithRSAEncryption
        Issuer: C = BR, ST = ST, L = CT, O = RE, OU = E, CN = myname, emailAddress = my@email.com
        Validity
            Not Before: Feb 18 13:41:14 2021 GMT
            Not After : Feb 16 13:41:14 2031 GMT
        Subject: C = CN, ST = Zhejiang, L = Hangzhou, O = EMQX, CN = Server certificate
        Subject Public Key Info:
            Public Key Algorithm: rsaEncryption
                RSA Public-Key: (2048 bit)
                Modulus:
                    00:ab:ff:52:d1:6d:18:6c:04:d8:ef:8d:10:0d:53:
                    4e:01:af:0d:35:77:1f:08:53:25:6a:28:6c:a4:21:
                    70:6c:c2:9c:b4:13:2e:04:81:89:6a:5f:f7:e0:9b:
                    0d:6c:68:27:70:03:c4:5a:dc:78:4f:1a:7f:7d:f5:
                    04:7c:89:ee:5d:9a:1c:95:a3:e8:58:0c:2e:7e:f2:
                    42:2a:5b:2d:f9:be:f3:e6:4b:7b:e4:85:8d:ef:ed:
                    91:d4:60:3c:8f:6c:ec:15:e1:1f:27:d0:05:0b:f6:
                    30:75:a2:3b:29:28:f3:c9:40:4d:a4:ec:b2:ef:4d:
                    be:23:f1:c5:f4:00:20:47:ed:32:19:4b:b3:18:5d:
                    f6:10:4d:48:ff:a7:ef:a7:3f:05:8e:a0:48:35:64:
                    0b:50:9b:7f:3c:1b:4d:b9:28:9a:1e:58:27:9a:33:
                    c8:44:32:2d:93:b6:1a:12:dd:5d:b9:ba:53:b0:af:
                    7f:79:10:80:64:c5:e2:d6:17:71:39:aa:7e:a4:0c:
                    23:0f:ff:cf:95:1a:37:6a:a4:ac:58:3f:97:35:3a:
                    53:21:8a:cf:dc:ae:0a:c4:b0:90:20:d3:46:90:bb:
                    c3:32:dc:47:08:c6:ea:01:4d:9e:2c:1b:4b:a3:a0:
                    e5:57:68:18:4a:2c:d8:80:9b:2c:2b:a6:63:c2:81:
                    6d:b1
                Exponent: 65537 (0x10001)
`
...
`
    Signature Algorithm: sha256WithRSAEncryption
         30:f6:82:b1:88:4a:90:a0:89:3e:e1:c2:4e:4f:c3:d8:44:15:
         44:ba:33:39:d8:d2:c8:d0:fa:f2:75:25:4c:b3:39:82:11:89:
         68:a3:9a:a6:8b:1e:8a:73:48:fb:44:74:88:ad:29:da:49:13:
         4f:04:e9:7c:28:42:c2:f0:26:5e:8a:6d:e6:68:55:c1:00:71:
         0a:4c:b1:4a:f9:1c:50:33:29:d3:90:cd:23:70:fa:20:92:70:
         d0:1e:0e:c6:22:34:be:cf:12:58:37:d2:45:65:98:7b:55:23:
         17:8a:80:be:b1:f1:61:7a:e9:b1:ec:0b:f7:f9:a1:08:72:89:
         b8:c8:3f:0d:59:4d:97:ab:46:03:b1:72:ce:da:70:1b:50:6e:
         e3:b0:19:eb:bc:b3:cb:59:54:4e:b0:c8:08:34:53:78:8b:df:
         45:86:ae:cb:37:f6:0f:6a:78:bf:cc:fa:32:ee:c1:ed:1e:2b:
         78:e7:b2:e5:c4:ad:1d:60:89:11:00:05:0f:1c:01:fa:20:6c:
         a8:b3:95:20:31:4c:a0:53:cc:c9:d1:5a:20:23:db:75:54:2e:
         a9:52:90:76:ec:81:49:92:86:80:98:a8:a4:96:6d:07:89:2f:
         33:cd:3d:96:e3:8b:87:fd:9d:fc:e5:f8:4f:3b:d6:10:fc:83:
         55:0b:42:f5`

**Comment by zmstone** [comment]
It seems the alternative name did take effect when you generated the cert.
otherwise there should be `            X509v3 Subject Alternative Name:` in the output

**Comment by XxKavosxX** [comment]
If i uncheck the `SSL secure`, it connects

![image](https://user-images.githubusercontent.com/12784642/108368968-e6c7c780-71af-11eb-8735-0b6ae4a82778.png)

![image](https://user-images.githubusercontent.com/12784642/108369126-170f6600-71b0-11eb-8bbb-c08ed6009eec.png)

**Comment by zmstone** [comment]
I'll experiment a bit and get back to you.

**Comment by XxKavosxX** [comment]
Ok, my RaspberryPi is running Raspibian 10, and my PC windows 10, if it matters

**Comment by zmstone** [comment]
@XxKavosxX could you try to re-generate the certificate with this command:
```
openssl x509 -req -in ./emqx.csr -CA my_root_ca.pem -CAkey my_root_ca.key -CAcreateserial -out emqx.pem -days 3650 -sha256 -extensions v3_req -extfile openssl.cnf
```

I believe `-extensions v3_req -extfile openssl.cnf` is missing in the tutorial.

**Comment by XxKavosxX** [comment]
`openssl genrsa -out my_root_ca.key 2048`

`openssl req -x509 -new -nodes -key my_root_ca.key -sha256 -days 3650 -out my_root_ca.pem`

`openssl genrsa -out emqx.key 2048`

`openssl.cnf` :
[req]
default_bits  = 2048
distinguished_name = req_distinguished_name
req_extensions = req_ext
x509_extensions = v3_req
prompt = no
[req_distinguished_name]
countryName = CN
stateOrProvinceName = Zhejiang
localityName = Hangzhou
organizationName = EMQX
commonName = Server certificate
[req_ext]
subjectAltName = @alt_names
[v3_req]
subjectAltName = @alt_names
[alt_names]
IP.1 = 192.168.0.5

`openssl req -new -key ./emqx.key -config openssl.cnf -out emqx.csr`

`openssl x509 -req -in ./emqx.csr -CA my_root_ca.pem -CAkey my_root_ca.key -CAcreateserial -out emqx.pem -days 3650 -sha256 -extensions v3_req -extfile openssl.cnf`

`sudo chmod -R 777 .`   in /etc/emqx/certs folder

`$sudo service emqx restart`

AND you FIXED IT!

![image](https://user-images.githubusercontent.com/12784642/108373393-b5052f80-71b4-11eb-829e-85788dd4a21b.png)

![image](https://user-images.githubusercontent.com/12784642/108373219-7e2f1980-71b4-11eb-94fc-0a638d511514.png)

**Comment by XxKavosxX** [comment]
@zmstone  Thank you for your help !!

**Comment by AliHaider104** [comment]
Hey! I have a question. If I installed EMQX Broker on Prem in Machine 1. Is it possible to send data to that broker from an MQTT client on machine 2?
