### ISSUE TITLE
How to deal with the array format of payload?

### ISSUE THREAD

**Issue by RalphLuo** [emqx/emqx#4207]
payload data:
[{"frmt":10,"ver":10,"cid":"Client1001","datas":[{"cf":1,"nm":"C1_smart200_Tag1","ad":0,"vt":2,"v":4896.0,"t":"2021-01-25 15:26:17.908","q":0},{"cf":1,"nm":"C1_smart200_Tag2","ad":0,"vt":2,"v":9781.0,"t":"2021-01-25 15:26:17.908","q":0},{"cf":1,"nm":"C1_smart200_IoStatus","ad":0,"vt":1,"v":1,"t":"2021-01-25 15:26:11.286","q":0}]}]

I don't know how to write rule engine SQL,i hope test output are as follows:

[{"vt":2,"v":4896,"t":"2021-01-25 15:26:17.908","q":0,"nm":"C1_smart200_Tag1","cf":1,"ad":0},{"vt":2,"v":9781,"t":"2021-01-25 15:26:17.908","q":0,"nm":"C1_smart200_Tag2","cf":1,"ad":0},{"vt":1,"v":1,"t":"2021-01-25 15:26:11.286","q":0,"nm":"C1_smart200_IoStatus","cf":1,"ad":0}]

![111](https://user-images.githubusercontent.com/1762679/108470923-a2c6e680-72c5-11eb-8a5a-b096b9af4277.png)
![222](https://user-images.githubusercontent.com/1762679/108470927-a65a6d80-72c5-11eb-908e-63c71acc1a9e.png)
![333](https://user-images.githubusercontent.com/1762679/108470932-a8bcc780-72c5-11eb-9f10-ab405d50a5a1.png)

**Comment by zmstone** [comment]
Hi we have a `jq` kind of query implementation planned, but no such support so far.

**Comment by terry-xiaoyu** [comment]
I find that you just want to get the array from the object with key named "datas".

```
[
  {
    "vt": 2,
    "v": 4896,
    "t": "2021-01-25 15:26:17.908",
    "q": 0,
    "nm": "C1_smart200_Tag1",
    "cf": 1,
    "ad": 0
  },
  {
    "vt": 2,
    "v": 9781,
    "t": "2021-01-25 15:26:17.908",
    "q": 0,
    "nm": "C1_smart200_Tag2",
    "cf": 1,
    "ad": 0
  },
  {
    "vt": 1,
    "v": 1,
    "t": "2021-01-25 15:26:11.286",
    "q": 0,
    "nm": "C1_smart200_IoStatus",
    "cf": 1,
    "ad": 0
  }
]
```

If that's want you want, and you then want to **do actions for each of the element** in the output array, please checkout the `FOREACH` syntax here: https://docs.emqx.cn/broker/latest/rule/rule-engine.html#sql-语句
