### ISSUE TITLE
monitor client connection process

### ISSUE THREAD

**Issue by M-Keidler-GROB** [emqx/emqx#4209]
introduction: I had a bug in our mqtt client. when the connection to the broker get lost for some reason (e.g. network issues) the client was intend to do a reconnect. unfortunatly it did not a reconnect it generates a new instance of the client with the same client ID like the still existing client. As long as the network connection issues exist, the backend system generates more and more new client instances. Having multiple clients with the same client ID stresses the broker a bit. after a few hours the broker crashes. We searched for the problem but we as not able to figure it out in a timely manner.

my question is, how can in monitor issues while clients try to connect to the broker. my favorite solution would be a metric like connection trys per second/minute/hour ... or better succesfull connection trys and unsuccesfull connection trys. is this information somewhere provide within emqx? 

BTW: the bug is fixed an we will switch to random client ids soon.

Thanks a lot!

**Comment by tigercl** [comment]
@M-Keidler-GROB Using a completely random client identifier or a fixed and unique client identifier is the correct implementation. In addition, you can get the client offline notification message by subscribing to the system topic.
