### ISSUE TITLE
Feature request: Force ACL cache eviction

### ISSUE THREAD

**Issue by supery-chen** [emqx/emqx#4215]
**What would you like to be added/modified**:
 @希望能够提供批量清除客户端acl缓存功能🙇‍
We wish to have a command line (or REST API) to force evict for all (or a batch of)  ACL cache entries.

**Why is this needed**:
我们目前业务存在这种使用场景，需要清除多个客户端的缓存，目前需要调用多次api接口，影响效率，同时也增大了失败的可能性
In our use case, we need to evict cache for many clients with one API call for each.
such approach is not efficient and has an increased fail rate.

**Comment by zmstone** [comment]
this is a reasonable feature.
to have it delivered quicker, pull requests are welcome.

**Comment by zmstone** [comment]
we are here to help even if you have absolute 0 experience in Erlang.

**Comment by supery-chen** [comment]
sorry, I've never used Erlang😂

**Comment by zmstone** [comment]
@supery-chen totally fine. wanna give it a try ?

**Comment by sh3d2** [comment]
hi,

i'd like to use that feature too, so im gonna give it a go at implementing it (with my next to none erlang experience).

first question: 
why was process dictionary used as cache storage instead of ets? 

not that it makes a difference, 5min ago i didnt know process dictionary existed.

@zmstone any pointers on how to develop emqx plugins locally without having to compilet the whole emqx-rel after every change? i managed to setup https://github.com/benoitc/rebar3_path_deps for local deps.

**Comment by zmstone** [comment]
I'm afraid I need @HJianBo to help answering the question why process dictionary is used.
Because if I were to implement it, I'd have chose ETS (with a cleaner process).

WRT plugin development, I'd recommend basing on the latest master branch. (currently 4.3-beta.1)
More details here : https://github.com/emqx/emqx/blob/master/lib-extra/README.md

Otherwise, in `emqx-rel` project, you can use rebar3 `_checkouts` feature.
https://blog.erlware.org/rebar3-features-part-6-_checkouts-2/
i.e. symlink it to your git clone.

**Comment by sh3d2** [comment]
ok, one more question. im just trying to understand the way acl cache works: 

https://github.com/emqx/emqx/blob/master/src/emqx_access_control.erl#L53

```
check_acl_cache(ClientInfo, PubSub, Topic) ->
    case emqx_acl_cache:get_acl_cache(PubSub, Topic) of
        not_found ->
            AclResult = do_check_acl(ClientInfo, PubSub, Topic),
            emqx_acl_cache:put_acl_cache(PubSub, Topic, AclResult),
            AclResult;
        AclResult -> AclResult
    end.
````

i do not see how client info is included in the cache. does that mean that cache item isnt tied to a "clientid" in any way? is this a bug, or im simply missing something

**Comment by HJianBo** [comment]
Hi @zmstone The original design took into account the following things:
1. a faster process dictionary.
2. No additional management code is needed. When a process exits, the cache disappears at the same time.
We have to store ACL cache for each client. This makes it faster to execute publish/subscribe each time.

So, we put this cache in the process dictionary of each process.

I think the use of ETS does not reduce the complexity of processing ACL cache (the only advantage it has is the enhanced ability to manage the cache, but we don't use it at the moment)

**Comment by zmstone** [comment]
Thank you @HJianBo .
Now I understand why it was PD used.
I believe ETS can be another layer of cache for remotely resided ACL rules such as mysql, postgres etc. However that's a different story.

@sh3d2 to answer your question
> i guess theres a per channel process (?) instance of acl cache therefore theres no need to store clientinfo

If you are looking at 4.x code, I believe for each MQTT client, there is only one process (the connection process) which concerns ACL cache.

**Comment by zmstone** [comment]
For the force eviction, I suppose we should avoid a design by enumerating on all clients and send them a message?

We should perhaps create a really cheap-to-check flag such as [persistent_term](https://erlang.org/doc/man/persistent_term.html),
which can be set globally and read by client processes so they can discard cache immediately.

e.g. to set the flag: `emqx_acl_cache:set_force_eviction(erlang:system_time()).`
then the clients should read this flag before they visit the cache,
if it's not seem before (i.e. newly set), then discard all cache in PD.

**Comment by zmstone** [comment]
> does that imply the cache can only be discarded per node and not cluster-wide?

Yes. But we can make a `cluster_call` to set the same flag to all nodes in the cluster.
The timing will be slightly different on different nodes, but should not be a big problem, I suppose.

**Comment by sh3d2** [comment]
above pr is just the basics now, as im dealing with concepts in erlang im learning on the fly. any feedback will be much appreciated. 

My idea of further work on this is to:
* add rest/cli to issue a acl discard request.
* send it to all nodes as `persistent_term` already read from above pr. 

Is keeping current state of the `discard key` inside process dict a good idea, or is there a better way?

**Comment by k32** [comment]
The corresponding PR has been merged, closing the issue.
