### ISSUE TITLE
Why listener.wss.external.max_connections is set to 16 by default?

### ISSUE THREAD

**Issue by hehejiuhuizhe** [emqx/emqx#4235]
In the default config ,the "listener.wss.external.max_connections" is only 16, while "listener.ssl.external.max_connections" is 102400 and "listener.tcp.external.max_connections" is 1024000. Why is the number so small? Can I set it to a big number, like 102400?

**Comment by tigercl** [comment]
@hehejiuhuizhe Of course, you can adjust these configuration items according to your own hardware configuration and the number of devices.

**Comment by zmstone** [comment]
16 is likely some safe tune-down for edge.
we believe this is not quite reasonable as default.
We will try to find a sweet spot on some common VM setup and update this number.

**Comment by hehejiuhuizhe** [comment]
Thanks for your reply.
