### ISSUE TITLE
emqx_auth_mysql  can not connect azure mysql 

### ISSUE THREAD

**Issue by hustdamon** [emqx/emqx#4244]
**Issue**:
1.Encrypted connectivity using Transport Layer Security (TLS 1.2) in Azure Database for MySQL
   https://docs.microsoft.com/en-us/azure/mysql/flexible-server/how-to-connect-tls-ssl
2.emqx_auth_mysql  can not connect azure mysql server  (only support TLS 1.2 )

**Environment**:

1. EMQ X version 
   emqx-ubuntu18.04-4.2.7-x86_64.deb
2. Hardware configuration (e.g. `lscpu`):
   Architecture:        x86_64
   CPU op-mode(s):      32-bit, 64-bit
   Byte Order:          Little Endian
   CPU(s):              2
   On-line CPU(s) list: 0,1
   Thread(s) per core:  1
   Core(s) per socket:  2
   Socket(s):           1
   NUMA node(s):        1
   Vendor ID:           GenuineIntel
   CPU family:          6
   Model:               79
   Model name:          Intel(R) Xeon(R) CPU E5-2673 v4 @ 2.30GHz
   Stepping:            1
   CPU MHz:             2294.686
   BogoMIPS:            4589.37
   Hypervisor vendor:   Microsoft
   Virtualization type: full
   L1d cache:           32K
   L1i cache:           32K
   L2 cache:            256K
   L3 cache:            51200K
   NUMA node0 CPU(s):   0,1
   Flags:               fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht 
                           syscall nx pdpe1gb rdtscp lm constant_tsc rep_good nopl xtopology cpuid pni pclmulqdq ssse3 fma cx16 pcid 
                           sse4_1 sse4_2 movbe popcnt aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch invpcid_single 
                           pti fsgsbase bmi1 hle avx2 smep bmi2 erms invpcid rtm rdseed adx smap xsaveopt md_clear

**Log**:
   2021-02-26 09:07:55.387 [debug] Right Hand Side Substitutions
   2021-02-26 09:07:55.387 [debug] Applying Datatypes
   2021-02-26 09:07:55.388 [debug] Validation
   2021-02-26 09:07:55.388 [debug] Applied 1:1 Mappings
   2021-02-26 09:07:55.388 [debug] Running translation for emqx_auth_mysql.server
   2021-02-26 09:07:55.388 [debug] Running translation for emqx_auth_mysql.password_hash
   2021-02-26 09:07:55.388 [debug] Applied Translations
   2021-02-26 09:07:55.514 [error] [MySQL] Can't connect to MySQL server: 3159 - <<"Connections using insecure transport 
   are prohibited while --require_secure_transport=ON.">>
   2021-02-26 09:07:55.516 [error] [Plugins] Load plugin emqx_auth_mysql failed, cannot start plugin emqx_auth_mysql for 
   {bad_return,{{emqx_auth_mysql_app,start,[normal,[]]},{'EXIT',{{badmatch,{error,{shutdown, 
   {failed_to_start_child,emqx_auth_mysql,{shutdown,{failed_to_start_child,worker_sup,{shutdown,{failed_to_start_child, 
   {worker,1},{3159,<<"HY000">>,<<"Connections using insecure transport are prohibited while -- 
   require_secure_transport=ON.">>}}}}}}}}},[{emqx_auth_mysql_app,start,2,[{file,"emqx_auth_mysql_app.erl"},{line,38}]}, 
   {application_master,start_it_old,4,[{file,"application_master.erl"},{line,277}]}]}}}}
   2021-02-26 09:07:55.516 [notice]     application: emqx_auth_mysql
    exited: {bad_return,
             {{emqx_auth_mysql_app,start,[normal,[]]},
              {'EXIT',
               {{badmatch,
                 {error,
                  {shutdown,
                   {failed_to_start_child,emqx_auth_mysql,
                    {shutdown,
                     {failed_to_start_child,worker_sup,
                      {shutdown,
                       {failed_to_start_child,
                        {worker,1},
                        {3159,<<"HY000">>,
                         <<"Connections using insecure transport are prohibited while --require_secure_transport=ON.">>}}}}}}}}},
                [{emqx_auth_mysql_app,start,2,
                  [{file,"emqx_auth_mysql_app.erl"},{line,38}]},
                 {application_master,start_it_old,4,
                  [{file,"application_master.erl"},{line,277}]}]}}}}
    type: temporary

**emqx_auth_mysql.conf**:

   ......
   ## Mysql ssl configuration.
   ##
   ## Value: on | off
   auth.mysql.ssl = on
   ## CA certificate.
   ##
   ## Value: File
   auth.mysql.ssl.cafile  = /etc/emqx/certs/DigiCertGlobalRootCA.crt.pem

    ## Client ssl certificate.
    ##
    ## Value: File
    ## auth.mysql.ssl.certfile = path to your clientcert file

    ## Client ssl keyfile.
    ##
    ## Value: File
    ## auth.mysql.ssl.keyfile = path to your clientkey file
   ......

BR,
Damon

**Comment by wwhai** [comment]
> Connections using insecure transport are prohibited while --
> require_secure_transport=ON

## Try floowing:
Reason: This error occurs when the user is trying to add a SSL-supported monitor(i.e --require_secure_transport option enabled) as a non-SSL monitor in Applications Manager.

Solution: To overcome this issue follow the steps given below:
Execute the following query in the corresponding mysql shell script:
ALTER USER '<user>'@'<host/Ip-address>' REQUIRE <tls_option>; [ tls_option: { SSL | X509 | CIPHER 'cipher' | ISSUER 'issuer' | SUBJECT 'subject' } ]
Add client certificates along with its root certificates in AppManagerHome/working/cert/apm.keytore.
Add the monitor by enabling 'SSL' option in Add New Monitor page. If the monitor has already been added, update the 'SSL' option in Edit Monitor page.

---
https://pitstop.manageengine.com/portal/en/kb/articles/how-to-fix-connections-using-insecure-transport-are-prohibited-while-require-secure-transport-on-in-mysql
