### ISSUE TITLE
[Error] Force to close the socket due to keepalive_timeout

### ISSUE THREAD

**Issue by yuantao1880** [emqx/emqx#4251]
#### Environment

- OS: Centos7.5
- Erlang/OTP: 
- EMQ: emqx 4.2.7

#### Description
emqx Client connected via 127.0.0.1 disappeare frequently by the error as " Force to close the socket due to keepalive_timeout"，i wonder what has going wrong, Thanks!
*A description of the issue*
![image](https://user-images.githubusercontent.com/48791623/109459001-e3c6b400-7a98-11eb-8e8e-af9fe865a661.png)

**Comment by tigercl** [comment]
@yuantao1880 It seems that your client did not send `PINGREQ` packets in time.
