### ISSUE TITLE
windows restart 

### ISSUE THREAD

**Issue by RoutineZ** [emqx/emqx#4273]
**Please describe your problem in detail, if necessary, you can upload the log file through the attachment**:
EMQx: 4.2.7
OS: windows10

Everytime I restart my pc, I need to run the commond "emqx start" or "emqx console", then the Broker works well.

If I run "emqx_ctl status" first ,then it gives the report bellows: 
=INFO REPORT==== 3-Mar-2021::09:18:01.972000 ===
Protocol 'inet_tcp': register/listen error: econnrefused

=SUPERVISOR REPORT==== 3-Mar-2021::09:18:01.972000 ===
    supervisor: {local,net_sup}
    errorContext: start_error
    reason: {'EXIT',nodistribution}
    offender: [{pid,undefined},
               {id,net_kernel},
               {mfargs,{net_kernel,start_link,
                                   [['emqx_maint_16276@127.0.0.1',longnames],
                                    false]}},
               {restart_type,permanent},
               {shutdown,2000},
               {child_type,worker}]
=CRASH REPORT==== 3-Mar-2021::09:18:01.972000 ===
  crasher:
    initial call: net_kernel:init/1
    pid: <0.80.0>
    registered_name: []
    exception exit: {error,badarg}
      in function  gen_server:init_it/6 (gen_server.erl, line 358)
    ancestors: [net_sup,kernel_sup,<0.46.0>]
    message_queue_len: 0
    messages: []
    links: [#Port<0.3>,<0.77.0>]
    dictionary: [{longnames,true}]
    trap_exit: true
    status: running
    heap_size: 1598
    stack_size: 27
    reductions: 3610
  neighbours:

escript: exception error: no match of right hand side value
                 {error,
                     {{shutdown,
                          {failed_to_start_child,net_kernel,
                              {'EXIT',nodistribution}}},
                      {child,undefined,net_sup_dynamic,
                          {erl_distribution,start_link,
                              [['emqx_maint_16276@127.0.0.1',longnames],
                               false]},
                          permanent,1000,supervisor,
                          [erl_distribution]}}}
  in function  nodetool__escript__1614__734279__837000__4:'-main/1-fun-3-'/1 (D:\zrt\software\emqx\bin\nodetool, line 28)
  in call from nodetool__escript__1614__734279__837000__4:do_with_ret/3 (D:\zrt\software\emqx\bin\nodetool, line 145)
  in call from nodetool__escript__1614__734279__837000__4:main/1 (D:\zrt\software\emqx\bin\nodetool, line 25)
  in call from escript:run/2 (escript.erl, line 758)
  in call from escript:start/1 (escript.erl, line 277)
  in call from init:start_em/1 (init.erl, line 1109)
  in call from init:do_boot/3 (init.erl, line 817)

is there way to Auto start when I restart my pc?

**Comment by wwhai** [comment]
Tcp `econnrefused `, may be your port is in useing?
