### ISSUE TITLE
two way SSL should work without password on the right

### ISSUE THREAD

**Issue by HJianBo** [emqx/emqx#4305]
**What would you like to be added/modified**:

This request was first mentioned @KrYpToDeN on https://github.com/emqx/emqx/issues/4033#issuecomment-791902122

If a client connects to emqx using two-way SSL, it does not need to provide fields such as username or password to request additional authorization.

In the current,  we have to turn on `allow_anonymous` or configure a fixed username and password (i.e: emqx_auth_username, etc) to allow this type of client.

**Why is this needed**:
It is possible to allow no authentication chain after using SSL connection?

**Comment by zmstone** [comment]
Does this imply we need is a new config like `allow_anonymous_when_mutual_tls_authenticated` ?

**Comment by HJianBo** [comment]
> Does this imply we need is a new config like `allow_anonymous_when_mutual_tls_authenticated` ?

Yeah, I think so.

**Comment by KrYpToDeN** [comment]
Hello, guys.
@zmstone , @HJianBo , @tigercl , @wivwiv , @emqplus 

Tell me, please, could you release it?
should we expect an update?

**Comment by KrYpToDeN** [comment]
Hello @HJianBo 

Could you consider this topic, please?

**Comment by HJianBo** [comment]
Sorry, @KrYpToDeN I've been busy with other things lately.

As @tigercl mentioned, there is a temporary workaround in the current version (e.g: 4.2.x) to add a new `zone` and `listener` to accept these two-way SSL connections.

e.g
```

## Configure a zone called `twossl`
zone.twossl.allow_anonymous = true
zone.twossl.bypass_auth_plugins = true
...

## Put the SSL listener in twossl zone
listener.ssl.external.zone = twossl
```

**Comment by KrYpToDeN** [comment]
> Sorry, @KrYpToDeN I've been busy with other things lately.
> 
> As @tigercl mentioned, there is a temporary workaround in the current version (e.g: 4.2.x) to add a new `zone` and `listener` to accept these two-way SSL connections.
> 
> e.g
> 
> ```
> 
> ## Configure a zone called `twossl`
> zone.twossl.allow_anonymous = true
> zone.twossl.bypass_auth_plugins = true
> ...
> 
> ## Put the SSL listener in twossl zone
> listener.ssl.external.zone = twossl
> ```

Hello, @HJianBo 

It's all right, Thank you very much.

But, how can i check ALC via MySQL now?

SSL clients now have unlimited access. 

`auth.mysql.acl_query = select allow, ipaddr, username, clientid, access, topic from mqtt_acl where ipaddr = '%a' or username = '%u' or username = '$all' or clientid = '%c'`

**Comment by KrYpToDeN** [comment]
Hello, @HJianBo 

Do you have any ideas?
I think, it's the last problem with auth.

**Comment by KrYpToDeN** [comment]
> Sorry, @KrYpToDeN I've been busy with other things lately.
> 
> As @tigercl mentioned, there is a temporary workaround in the current version (e.g: 4.2.x) to add a new `zone` and `listener` to accept these two-way SSL connections.
> 
> e.g
> 
> ```
> 
> ## Configure a zone called `twossl`
> zone.twossl.allow_anonymous = true
> zone.twossl.bypass_auth_plugins = true
> ...
> 
> ## Put the SSL listener in twossl zone
> listener.ssl.external.zone = twossl
> ```

Hello, @HJianBo .

Could you help me to solve my problem, above?

`It's all right, Thank you very much.

But, how can i check ALC via MySQL now?

SSL clients now have unlimited access.

auth.mysql.acl_query = select allow, ipaddr, username, clientid, access, topic from mqtt_acl where ipaddr = '%a' or username = '%u' or username = '$all' or clientid = '%c'

MySQL ACL don't work

I think it's because username is underfined.
I checked via logs and via - zone.twossl.use_username_as_clientid = true, which restarts all SLL clients one by one.`

**Comment by bhaveshgohel** [comment]
Hello friends,
I have the same issue. I use ACL file instead of Mysql ACL and have the same issue.

Is there is any workaround on how to restirct client with SSL (and no password) to only pubsub to certain mqtt path ?

**Comment by cferrera** [comment]
Almost an year later and this issue is still open, do we have any updates or new workarounds to solve it?

**Comment by zmstone** [comment]
> Hello friends, I have the same issue. I use ACL file instead of Mysql ACL and have the same issue.
> 
> Is there is any workaround on how to restirct client with SSL (and no password) to only pubsub to certain mqtt path ?

the rules are username/client-ID/source-IP based, so no. this is not possible.
a workaround would be to use x509 cert common name as client ID or username, then create rules based on the used-client-ID or username.

**Comment by zmstone** [comment]
> Almost an year later and this issue is still open, do we have any updates or new workarounds to solve it?
Hi @cferrera 
The workaround is to move SSL listener to another zone, e.g. `etxternal_tls` then allow anonymous for the entire zone.

**Comment by zmstone** [comment]
I guess the message from @wivwiv is: no, we will not implement this feature.
