### ISSUE TITLE
emqtt-bench test load balance get half of messages

### ISSUE THREAD

**Issue by jimmy0** [emqx/emqx#4311]
#### Environment

- OS: Centos 7.9
- Erlang/OTP: 
- EMQ:  4.2.7 

#### Description

*A description of the issue*

The load balance's ip is 192.168.0.105, and has 2 emqx servers.
subscribe to loadbance:  /root/a/emqtt-bench/emqtt_bench sub -t t -h 192.168.0.105 -c 50 --ifaddr 192.168.1.171
print out:
recv(7001): total=1700, rate=1250(msg/sec)
recv(8001): total=2950, rate=1250(msg/sec)
recv(9001): total=4200, rate=1250(msg/sec)
recv(10001): total=5450, rate=1250(msg/sec)

publish to loadbance: /root/a/emqtt-bench/emqtt_bench pub -t t -h 192.168.0.105 -c 50 -I 1000 -s 256  --ifaddr 192.168.1.172
print out:
sent(2001): total=50, rate=50(msg/sec)
sent(3001): total=100, rate=50(msg/sec)
sent(4001): total=150, rate=50(msg/sec)
sent(5001): total=200, rate=50(msg/sec)
sent(6001): total=250, rate=50(msg/sec

It seems the subscribe must be 2500(msg/sec), not the 1250(msg/sec)?

**Comment by tigercl** [comment]
@jimmy0 Do these two EMQ X Brokers form a cluster correctly?

**Comment by jimmy0** [comment]
@tigercl the load balance bought from aliyun.

**Comment by jimmy0** [comment]
@tigercl  yes. I have done a connection test to the cluster successfully.

**Comment by tigercl** [comment]
@jimmy0 Does the cluster work normally when you are not using load balancing?

**Comment by jimmy0** [comment]
@tigercl yes. When I test the emqx server directly using emqtt-bench, the subscribe print correctly , 2500(msg/sec)

**Comment by tigercl** [comment]
@jimmy0 Can you provide details about the configuration of LB？

**Comment by qzhuyan** [comment]
@jimmy0 any updates on this?

**Comment by qzhuyan** [comment]
close due to inactive.
