### ISSUE TITLE
Fail to start emqx extension module

### ISSUE THREAD

**Issue by yanggao025** [emqx/emqx#4315]
多语言扩展钩子  模块启动失败  扩展语言是Java服务~  有没有大佬遇到同样的问题  烦请指点一二  小弟感激不尽

**Comment by tigercl** [comment]
@yanggao025 Could you provide some logs about the failure？So that we can analyze the issue more accurately.

**Comment by HJianBo** [comment]
Have you tried v4.3-beta.1?

In the v4.3-beta.1 We have enhanced the implementation of the extension hook.

**Comment by yanggao025** [comment]
失败日志： #{channel => "exhook:module:c865202c"}},6000]}
2021-03-11 19:32:50.397 [error] [ExHook] Load server <<"module:c865202c">> failed: timeout

> @ yanggao025您能否提供有关故障的日志？以便我们可以更准确地分析问题。

**Comment by HJianBo** [comment]
Is the server address it is configured to access?
