### ISSUE TITLE
Could emqx_prometheu provide node status metrics?

### ISSUE THREAD

**Issue by jiangyin97** [emqx/emqx#4326]
![image](https://user-images.githubusercontent.com/80656989/111094888-2e572e80-8577-11eb-9192-00b8566dd39a.png)

There are no metrics about emqx running state, such as emqx_node_status.

**Comment by tigercl** [comment]
@jiangyin97 There should be no at present, please tell us what kind of node status you need? For example, is the node running or something else? Maybe we implement it in the future.

**Comment by jiangyin97** [comment]
Such as node health, died or running. At present, I can not judge whether the node is running normally from metrics.

**Comment by zmstone** [comment]
We can provide metrics about node being UP (but not down).
e.g. we can add a `node_up` metric which provides a UNIX epoch as value in each scrape.

However, I'm not sure if it makes much sense because there are other indicators of
node being up/down, e.g. prometheus can scrape, the node is up, if it failed to do so, that's probably an indicator of node being down.
and prometheus has builtin metics for scraping failures etc.

For other health check metrics, we are open to suggestions.

**Comment by jiangyin97** [comment]
I'm sorry. Maybe I made a mistake. I hope you can provide the running status of emqx, not the server node.

Emqx uses pushgateway to push monitoring data. When emqx dies, the prometheus will not get any indicators of emqx, so that we can not monitor the death of emqx application.

**Comment by zmstone** [comment]
Sorry I was not ware that we use pushgateway. (still a lot to learn about our own product :).

Is it the case that pushgateway caches the last data points and continue serving the data ?
As a short term solution, is it possible to configure pushgateway with a TTL ?

As a long term solution, I think we need a native scraping endpoint for prometheus, as a plugin.

**Comment by jiangyin97** [comment]
I think rabbit-prometheus, the plug-in of rabbitmq, is very good. Can it be used as a reference?

**Comment by zmstone** [comment]
> I think rabbit-prometheus, the plug-in of rabbitmq, is very good. Can it be used as a reference?

We'll have a look.

If you (or anyone else) is interested in taking a deeper dive, please send a EIP to us.
https://github.com/emqx/eip

**Comment by zmstone** [comment]
Hi @jiangyin97 
I believe emqx already supports prometheus scraping.

`curl -f "admin:public@127.0.0.1:8081/api/v4/emqx_prometheus?type=prometheus"`
this command gives me outputs like this:
```
# TYPE erlang_vm_ets_limit gauge
erlang_vm_ets_limit 256000
# TYPE erlang_vm_logical_processors gauge
erlang_vm_logical_processors 20
# TYPE erlang_vm_logical_processors_available gauge
erlang_vm_logical_processors_available 20
# TYPE erlang_vm_logical_processors_online gauge
erlang_vm_logical_processors_online 20
# TYPE erlang_vm_port_count gauge
erlang_vm_port_count 18
# TYPE erlang_vm_port_limit gauge
erlang_vm_port_limit 1048576
# TYPE erlang_vm_process_count gauge
erlang_vm_process_count 408
```

**Comment by zmstone** [comment]
closing this for now.
