### ISSUE TITLE
When the connection volume of EMQ x broker is large, the client connection protocol type will change from mqtt v3.1.1 to mqisdp v3

### ISSUE THREAD

**Issue by 2605373904** [emqx/emqx#4342]
**Environment**:
- EMQ X version: 4.1.0
- CentOS7

Problem description：
When the connection volume of EMQ X Broker is large, the client connection protocol type will change from mqtt v3.1.1 to mqisdp v3
Can the change of client protocol type to mqisdp V3 be interpreted as the change of client protocol from mqtt 3.1.1 to version 3.1？

**Comment by tigercl** [comment]
@2605373904 Sorry, I didn’t understand the purpose of doing this. Can you describe it in detail?

**Comment by 2605373904** [comment]
Sorry, my English is not very good!
Our company is using EMQ x broker products and has encountered a problem
Problem phenomenon：
    In the process of using EMQ x broker, we find that when the number of clients connecting to EMQ increases, we can view the connection information of this client in the EMQ dashboard page. The connection protocol of this client shown in the dashboard page is mqisdp v3
My doubt：
    1. Why does the client connection protocol change from mqtt v3.1.1 to mqisdp V3 when EMQ x broker is under great pressure?
    2. There are differences between mqtt v3.1.1 and mqisdp v3?

**Comment by tigercl** [comment]
@2605373904 We should have never done such a treatment. If this phenomenon is indeed the case, then it should be a BUG. Can you confirm that the client whose protocol version is v3 shows that the protocol version is v3.1.1 before the number of connections increases?

**Comment by 2605373904** [comment]
I can confirm that
    I have done a lot of tests. When the connection volume is large, the client connection protocol will change from mqtt v3.1.1 to mqisdp v3
    When the QPS of EMQ x broker is very small, the connection protocol used by new clients to connect to EMQ x broker is mqtt v3.1.1.
    When the QPS of EMQ x broker is large, the new client uses mqisdp V3 to connect with EMQ x broker.

As long as the connection volume of EMQ x broker QPS is large, this problem will occur 100%

EMQ X version: Enterprise 4.1.0

**Comment by 2605373904** [comment]
Problem recurrence steps:
testing environment:
    1.operating system:centos7 
    2.EMQ X version: Enterprise 4.1.0
    3.snapshoot server:It is used to receive and store client information, and it is also a client user subscribing to client information
    4.air conditioner:Internet of things devices
After the snapshot server connects to the EMQ x broker as a client, it uses the pressure test tool to simulate a large number of clients connecting to the EMQ x broker. Before the pressure test, snapshot server uses mqtt v3.1.1 connection protocol as a client. When the QPS is large, the connection protocol of snapshot server to EMQ becomes mqisdp v3

**Comment by zmstone** [comment]
Hi @2605373904 I’m glad you sorted this out.
This is a very interesting case study.

We recommend you to use the latest (enterprise) version 4.1 series, which is 4.1.2.
Or even better: 4.2

If you identify any issues during the test, you are welcome to create issues here.
If you have questions, the better place to ask is in gitgub discussions: https://github.com/emqx/emqx/discussions
