### ISSUE TITLE
Node 'emqx1@127.0.0.1' not responding to pings.

### ISSUE THREAD

**Issue by lanling233** [emqx/emqx#4356]
能正常启动与访问，但运行 emqx stop 命令报错
求原因和解决方法

**Comment by tigercl** [comment]
@lanling233 If possible, you'd better provide some emqx logs so that we can better analyze the problem.

**Comment by zmstone** [comment]
@lanling233 你跑的哪个版本，在什么操作系统上？

**Comment by k32** [comment]
Closing due to lack of updates. Please feel free to submit a new issue if you manage to reproduce it on the current version of the broker.
