### ISSUE TITLE
bridge mqtt infinite loop bug

### ISSUE THREAD

**Issue by berayb** [emqx/emqx#4369]
Version: 4.2.8 
OS : Ubuntu 18.04
System: 8core 48GB Memory

The problem: When MQTT Bridge to RabbitMQ is enabled, it publishes messages infinitely. 
Logs : [error] [Bridge] Can't be found from the inflight:23287...

**Comment by HJianBo** [comment]
How do you configuring the Bridge for RabbitMQ? Can you paste the configurations?

The open-source version does not include the bridge. Are you sure you are using the open-source version v4.2.8?

**Comment by berayb** [comment]
@HJianBo , thanks for the reply. That is not an enterprise feature, a classic MQTT bridge. 

Some config in addition to authentication info:

bridge.mqtt.aws.forwards =$share/${group_id}/+,$share/${group_id}/$SYS/brokers/+/clients/+/connected,$share/${group_id}/$SYS/brokers/+/clients/+/disconnected

bridge.mqtt.aws.start_type = auto

bridge.mqtt.aws.bridge_mode = false

bridge.mqtt.aws.clean_start = false

bridge.mqtt.aws.queue.replayq_dir = /var/lib/emqx/emqx_aws_bridge/

bridge.mqtt.aws.queue.max_total_size = 5GB

**Comment by openedhardware** [comment]
Any update here?

I have a very similar issue with the bridge enabled.

My configuration is here - https://github.com/emqx/emqx/issues/4396

**Comment by matthewGEA** [comment]
Forwarding the path used for shared subscriptions didn't make sense:

bridge.mqtt.aws.forwards =$share/${group_id}/+,$share/${group_id}/$SYS/brokers/+/clients/+/connected,$share/${group_id}/$SYS/brokers/+/clients/+/disconnected

What about just trying:
bridge.mqtt.aws.forwards =+,$SYS/brokers/+/clients/+/connected,$SYS/brokers/+/clients/+/disconnected
