### ISSUE TITLE
Deny PingReq when MQTT not connected

### ISSUE THREAD

**Issue by terry-xiaoyu** [emqx/emqx#4370]
**Environment**:

- EMQ X version (e.g. `emqx_ctl status`): 4.3.0
- OS (e.g. `cat /etc/os-release`): Mac OS X
- Erlang/OTP version (in case you build emqx from source code): 23.0
- Others:

**What happened and what you expected to happen**:

The MQTT Broker should disconnect any connection that sends any other messages before the MQTT is connected. But if a client keep sending MQTT ping request, the emqx would reply it with ping responses and the connection is alive.

**How to reproduce it (as minimally and precisely as possible)**:

Start an MQTT client that sends PingReq packets without CONNECT be sent before.

**Comment by realyan** [comment]
I also met this problem the day before yesterday, and I gave feedback on issues

**Comment by terry-xiaoyu** [comment]
@realyan Would be fixed in 4.3.0
