### ISSUE TITLE
The force_shutdown_policy option does not always take effect

### ISSUE THREAD

**Issue by HJianBo** [emqx/emqx#4399]
**Environment**:

- EMQ X version (e.g. `emqx_ctl status`): 3-v4.3-rc.1

**What happened and what you expected to happen**:
I'm performing a shared subscription stress test on a 2C8G machine. EMQ X crashes due to OOM when the subscription client can't receive the more messages

**How to reproduce it (as minimally and precisely as possible)**:

The `force_shutdown_policy ` option:
```
zone.external.force_shutdown_policy = 3000|30MB
```

Sub Client:
```
./emqtt_bench sub -h 192.168.0.100 -c 3 -t "\$share/grp/topic1"  -q 1
```

Pub Client:
```
./emqtt_bench pub -h 192.168.0.100 -t topic1 -c 8000 -s 10240 -q 1
```

**Anything else we need to know?**:

I've looked at the three subscriber processes using `observer_cli` and their message_queue_len OR memory have exceeded the configuration requirements, but the processes are still alive.
<img width="1256" alt="image" src="https://user-images.githubusercontent.com/13825269/111963834-efa11580-8b2e-11eb-9b8c-f7c078d79081.png">

**Comment by HJianBo** [comment]
I have tried setting `kill => true`:
https://github.com/emqx/emqx/blob/b6894ae4c2f656587f7f7f53a52008abf75ba0bc/src/emqx_misc.erl#L189

But this seems to cause another problem: the process will be killed by the VM directly, so `emqx_connection:terminate` will not be called. This will cause the device to be in the wrong state in the broker.

**Comment by zmstone** [comment]
the oom shutdown message is a loopback to `self()`, meaning it will not have a chance to shutdown until the message is received.

**Comment by zmstone** [comment]
> As @terry-xiaoyu pointed, I have tried setting `kill => true`:
> https://github.com/emqx/emqx/blob/b6894ae4c2f656587f7f7f53a52008abf75ba0bc/src/emqx_misc.erl#L188-L191
> 
> But this seems to cause another problem: the process will be killed by the VM directly, so `emqx_connection:terminate` will not be called. This will cause the client to be wrong state in the broker.

`emqx_connection` does not trap exit, so I am not sure if the terminate callback is called at all anyway.

**Comment by zmstone** [comment]
> > As @terry-xiaoyu pointed, I have tried setting `kill => true`:
> > https://github.com/emqx/emqx/blob/b6894ae4c2f656587f7f7f53a52008abf75ba0bc/src/emqx_misc.erl#L188-L191
> > 
> > But this seems to cause another problem: the process will be killed by the VM directly, so `emqx_connection:terminate` will not be called. This will cause the client to be wrong state in the broker.
> 
> `emqx_connection` does not trap exit, so I am not sure if the terminate callback is called at all anyway even during normal shutdown.

Sorry, this is not true. because I can see this debug log: `?LOG(debug, "Terminated due to ~p", [Reason]),`
