### ISSUE TITLE
Stop emqx failed

### ISSUE THREAD

**Issue by terry-xiaoyu** [emqx/emqx#4414]
Cannot stop emqx when using java hook plugin:

![image](https://user-images.githubusercontent.com/11696433/112124167-04e47580-8bfd-11eb-9845-7c832965df83.png)

And here is the result of `ps -ef | grep emqx`:

![image](https://user-images.githubusercontent.com/11696433/112124239-19c10900-8bfd-11eb-8621-4c2b05c3e462.png)

**Environment**:

- EMQ X version (e.g. `emqx_ctl status`): 4.3-beta.1
- OS (e.g. `cat /etc/os-release`): CentOS 8

**What happened and what you expected to happen**:

Cannot stop the emqx instance when `ps -ef | grep emqx` returns multiple lines.

**How to reproduce it (as minimally and precisely as possible)**:

See above.

**Comment by zmstone** [comment]
`| grep -v remsh` ?
