### ISSUE TITLE
helm chart deploy instance only accepts EMQX_BRIDGE__MQTT__AWS for bridge name

### ISSUE THREAD

**Issue by mloebl** [emqx/emqx#4424]
**Environment**:

- EMQ X version (e.g. `emqx_ctl status`):  4.2.8 
- Hardware configuration (e.g. `lscpu`): arm64
- OS (e.g. `cat /etc/os-release`): Ubuntu
- Kernel (e.g. `uname -a`): 5.4.0-1030-raspi

- Others:  k3s 1.20.4+k3s1

**What happened and what you expected to happen**:  Specifying other EMQX_BRIDGE__MQTT__ in env configuration has no effect unless called, EMQX_BRIDGE__MQTT__AWS__  , cannot specify other names either

**How to reproduce it (as minimally and precisely as possible)**:
In the values.yaml I specify the following for the helm chart under `emqxConfig:`
```
  EMQX_BRIDGE__MQTT__TEST__START_TYPE: "auto"
  EMQX_BRIDGE__MQTT__TEST__ADDRESS: "x.x.x.x:1883"
  EMQX_BRIDGE__MQTT__TEST__MOUNTPOINT: "/"
  EMQX_BRIDGE__MQTT__TEST__SUBSCRIPTION__1__TOPIC: "/#"
  EMQX_BRIDGE__MQTT__TEST__USERNAME: "testuser"
  EMQX_BRIDGE__MQTT__TEST__PASSWORD: "password"
  EMQX_BRIDGE__MQTT__TEST__PROTO_VER: "mqttv3"
```
Deploy the helm chart and watch the first node as it comes up, there will be no mentions of the above bridge when watching the logs.  If I change them all to `EMQX_BRIDGE__MQTT__AWS`, I them see what I expected on startup:

```
bridge.mqtt.aws.address=x.x.x.x:1883
bridge.mqtt.aws.forwards=/#
bridge.mqtt.aws.password=***secret***
bridge.mqtt.aws.proto_ver=mqttv3
bridge.mqtt.aws.subscription.1.topic=/#
bridge.mqtt.aws.username=testuser
````

Same is noted with bridges list, only "aws" shows up in the list . Maybe this is expected?  Config map seem to be loaded fine in k8s, but not passing through to the emqx configuration it appears.  

**Anything else we need to know?**:
Possible I am misunderstanding the documentation in https://github.com/emqx/emqx-bridge-mqtt  which leads me to believe I can set the name after  EMQX_BRIDGE__MQTT .  Next issue is now trying to figure out why afte rsetting this, the emqx-bridge-mqtt plugin won't start and getting a `parse_config_file_failed` when using the above with `EMQX_BRIDGE__MQTT__AWS`

**Comment by Rory-Z** [comment]
Hi, @mloebl 
Sorry, we only support modifying existing configurations with environment variables.
@zmstone @z8674558 Is there a way we can add a new configuration with environment variables?

**Comment by z8674558** [comment]
In the next release (v4.3.0), you should be able to add new ones because we stopped looking for the corresponding variable in `.conf` file using sed. Instead we read environment variables in Erlang runtime.

**Comment by Rory-Z** [comment]
@z8674558 I tried the docker image of `emqx/emqx:4.3-rc.1`, which still can't add a new configuration by environment variables

**Comment by z8674558** [comment]
@Rory-Z I could. try `docker run --env EMQX_LISTENER__TCP__CUSTOM=2000 -it emqx/emqx:4.3-rc.1` and you will see `Start mqtt:tcp:custom listener on 0.0.0.0:2000 successfully.` in the console.

**Comment by zmstone** [comment]
`bridge.mqtt.$name.address` is called 'fuzzy' match in the config parser (cuttlefish).
`EMQX_LISTENER__TCP__CUSTOM` ('fuzzy' word at the end) seems to work fine.
@z8674558 will have a look if there is something wrong with it when the fuzzy word is in the middle

**Comment by z8674558** [comment]
@Rory-Z 

I tried
```
$ EMQX_BRIDGE__MQTT__TEST__ADDRESS="127.0.0.1:1883" \
EMQX_BRIDGE__MQTT__TEST__MOUNTPOINT="/" \
EMQX_BRIDGE__MQTT__TEST__SUBSCRIPTION__1__TOPIC="/#" \
EMQX_BRIDGE__MQTT__TEST__SUBSCRIPTION__1__QOS=1 \
EMQX_BRIDGE__MQTT__TEST__USERNAME="testuser" \
EMQX_BRIDGE__MQTT__TEST__PASSWORD="password" \
EMQX_BRIDGE__MQTT__TEST__CLIENTID="bridge" \
EMQX_BRIDGE__MQTT__TEST__PROTO_VER="mqttv3" \
EMQX_BRIDGE__MQTT__TEST__FORWARDS="topic1/#" \
EMQX_BRIDGE__MQTT__TEST__FORWARD__MOUNTPOINT="a/b" \
EMQX_BRIDGE__MQTT__TEST__RECEIVE_MOUNTPOINT="c/d" \
_build/emqx/rel/emqx/bin/emqx console
```
and the variables loaded successfully when I turned on the plugin. How did you test?

**Comment by Rory-Z** [comment]
@z8674558 I create env file
```
$ cat env
EMQX_LOADED_PLUGINS="emqx_bridge_mqtt"
EMQX_BRIDGE__MQTT__TEST__ADDRESS="127.0.0.1:1883"
EMQX_BRIDGE__MQTT__TEST__MOUNTPOINT="/"
EMQX_BRIDGE__MQTT__TEST__SUBSCRIPTION__1__TOPIC="/#"
EMQX_BRIDGE__MQTT__TEST__SUBSCRIPTION__1__QOS=1
EMQX_BRIDGE__MQTT__TEST__USERNAME="testuser"
EMQX_BRIDGE__MQTT__TEST__PASSWORD="password"
EMQX_BRIDGE__MQTT__TEST__CLIENTID="bridge"
EMQX_BRIDGE__MQTT__TEST__PROTO_VER=mqttv3
EMQX_BRIDGE__MQTT__TEST__FORWARDS="topic1/#"
EMQX_BRIDGE__MQTT__TEST__FORWARD__MOUNTPOINT="a/b"
EMQX_BRIDGE__MQTT__TEST__RECEIVE_MOUNTPOINT="c/d"
```
and I run ` docker run -it --rm --env-file env emqx/emqx:4.3-rc.1 bash`, it worked, cool !

@mloebl  You can look forward to our version 4.3.0, or try 4.3-rc.1

**Comment by Rory-Z** [comment]
> `bridge.mqtt.$name.address` is called 'fuzzy' match in the config parser (cuttlefish).
> `EMQX_LISTENER__TCP__CUSTOM` ('fuzzy' word at the end) seems to work fine.
> @z8674558 will have a look if there is something wrong with it when the fuzzy word is in the middle

 the fuzzy word is in the middle it still worked , cool !

**Comment by zmstone** [comment]
awesome support @Rory-Z and @z8674558 
i'm still not quite following what's missing in @mloebl's helm chart deployment.
could you share more details ?

**Comment by mloebl** [comment]
Thank you guys for the quick response on this!  On a semi related topic, do the helm charts support the `tag:` option?  I tried this to test the new version, but doesn't seem to be respecting `tag` it and still pulling 4.2.8:

```
  image:
  repository: emqx/emqx
  tag: 4.3-rc.1
  pullPolicy: IfNotPresent
```

**Comment by Rory-Z** [comment]
> Thank you guys for the quick response on this! On a semi related topic, do the helm charts support the `tag:` option? I tried this to test the new version, but doesn't seem to be respecting `tag` and still pulling 4.2.8:
> 
> ```
>   image:
>     repository: emqx/emqx
>     tag: 4.3-rc.1
>     pullPolicy: IfNotPresent
> ```

@mloebl Sorry, helm chart doesn't support this, but you can clone this repos and checkout to v4.3-rc.1 tag, and run `helm instsall emqx deplo  deploy/charts/emqx`, but v4.3-rc.1 is not stable version, the docker image has some issues, you can keep an eye on us subsequent releases

**Comment by mloebl** [comment]
Thank you @Rory-Z , I'll be patient them for 4.3 . I see 4.2.9 came out, so hoping 4.3.0 isn't too far behind it (not sure your current release cycle.)  Thank you guys again for the help!

**Comment by zmstone** [comment]
@mloebl thank you for your quick feedbacks too.
I'm closing this issue now.
for questions, you are welcome to ask here: https://github.com/emqx/emqx/discussions
