### ISSUE TITLE
EMQX 4.3-rc.1 Docker image does not set config file variables from environment variables

### ISSUE THREAD

**Issue by umeat** [emqx/emqx#4427]
**Environment**:

EMQX 4.3-rc.1, running in Docker (emqx/emqx:4.3-rc.1)

**What happened and what you expected to happen**:

Environment variables aren't converted to configuration file options as described in the documentation: https://hub.docker.com/r/emqx/emqx.

In older versions, variables would be written to EMQX config files. For example, setting `EMQX_ACL_NOMATCH=deny` would set the emqx.conf "acl_nomatch" to deny.

Note, `EMQX_LOADED_PLUGINS` at least does work as expected.

**How to reproduce it (as minimally and precisely as possible)**:

```
docker run -d -e EMQX_LOADED_PLUGINS=emqx_auth_http -e EMQX_AUTH__HTTP__AUTH_REQ__URL=http://emqx-auth:8000/auth -e EMQX_ACL_NOMATCH=deny --name emqx -p 1883:1883 emqx/emqx:4.3-rc.1

docker exec -it emqx sh
> cat /opt/emqx/etc/plugins/emqx_auth_http.conf
```

With the above you can see that the variable `auth.http.auth_req.url` is not set in the emqx_auth_http.conf file.

Whereas doing the same thing with image emqx/emqx:4.2.8 does work.

**Comment by Rory-Z** [comment]
Hi, @umeat In 4.3, the environment variable is set directly into the emqx application, rather than modifying the config file
```
docker run -it --rm  -e EMQX_LOADED_PLUGINS=emqx_auth_http -e EMQX_AUTH__HTTP__AUTH_REQ__URL=http://emqx-auth:8000/auth -e EMQX_ACL_NOMATCH=deny --name emqx -p 1883:1883 emqx/emqx:4.3-rc.1 bash

bash-5.0$ emqx console
(e0f93f70c9df@172.17.0.3)1> application:get_env(emqx_auth_http, auth_req).
{ok,[{path,"/auth"},
     {headers,[{"content-type",
                "application/x-www-form-urlencoded"}]},
     {timeout,5000},
     {pool_name,'emqx_auth_http/auth_req'},
     {pool_opts,[{host,"emqx-auth"},
                 {port,8000},
                 {pool_size,32},
                 {pool_type,random},
                 {connect_timeout,5000},
                 {retry,5},
                 {retry_timeout,1000},
                 {transport_opts,[inet]}]},
     {url,"http://emqx-auth:8000/auth"},
     {method,post},
     {params,[{"clientid","%c"},
              {"username","%u"},
              {"password","%P"}]}]}
```

**Comment by Rory-Z** [comment]
@z8674558 Is there any way we can make it easy for users to view their config changes ?

**Comment by z8674558** [comment]
@Rory-Z at this moment no. maybe we should print values from environment variables when the load of plugin, like `echo_value` in v4.2.x?
https://github.com/emqx/emqx-rel/blob/eee3fb9e1cb52a17b6b02f7d8169fe80b7e4e31d/deploy/docker/docker-entrypoint.sh#L106

**Comment by Rory-Z** [comment]
@z8674558 Maybe we can print out to the log file instead of in the shell

**Comment by zmstone** [comment]
this is done in `cuttlefish` which does not have a logging support.
for overrides at boot time, the app.config is generated by `cuttlefish` command
but not generated inside the emqx node where there is a proper logging system.

maybe a feature for cuttlefish to have a configurable logging callback.
e.g. `stdio | fun((Level, Fmt, Args) -> ok)`

**Comment by umeat** [comment]
Thanks for that. I see now that it is running with the correct config. 

I must be running into a different issue - but `emqx_ctl status` isn't working. I get `Node 'emqx@127.0.0.1' not responding to pings.` and nothing in the logs about it. Has something changed in 4.3 about that?

Also has the ACL API endpoint changed again in this version? It was /api/v4/emqx_acl then it was /api/v4/mqtt_acl, and now both of those return "Not found."

**Comment by zmstone** [comment]
@umeat the 'ping not responding' issue is a work in progress 
a workaround is to issue the command like `EMQX_NODE_NAME=name@ip emqx_ctl status`

**Comment by zmstone** [comment]
@umeat could you create a new issue for the acl endpoint ?
I'm closing this one.

**Comment by umeat** [comment]
Sure thing - thanks very much. That work around works for me.
