### ISSUE TITLE
Last Will Message from lost/restarted nodes

### ISSUE THREAD

**Issue by gbrehmer** [emqx/emqx#443]
To determine the current client connection status we want to use "last will message". But in case of a node restart/shutdown, the "last will message" has not sent out. What is purposed way to get such a functionality?

**Comment by erylee** [comment]
@gbrehmer What type of application? Current release of the broker will not persist Last Will Messages.

**Comment by gbrehmer** [comment]
main use case is to monitor high amount of devices with several sensors. the current connection status indicates, whether last received sensor data is in sync with device and device is applicable to receive commands from the service (bidirectional communication).
I saw that the list of connected devices is part of the HTTP API. nevertheless, the message driven approach by getting offline status message automatically by "last will message" would better fit.

**Comment by gbrehmer** [comment]
@emqplus 
Can you please document which information is currently persisted to disk, so it will be restored after node or complete cluster restart? I assume currently persistent sessions (subscriptions, offline/not acked messages?) & retained messages are persisted.

**Comment by turtleDeng** [comment]
Thank you for your participation, you can use the enterprise version for persistent operations 

https://www.emqx.io/downloads#enterprise
