### ISSUE TITLE
Way to save data to sql server

### ISSUE THREAD

**Issue by xiezhuojin** [emqx/emqx#4442]
**What would you like to be added/modified**:
A way to import data to sql server
**Why is this needed**:
Recently, my company ask me to create mqtt client to receive data then dump them to their sql server and they recommand me this project. After reading the docs, I found emqx is quite promising in my project. But these is one thing that brother, that is there is no way to import data to sql server. Is that a way to write a plugin to do that?

**Comment by zmstone** [comment]
hi @xiezhuojin 

we have a data sink module for sql server in enterprise edition, but not opensource.
At the moment, we do not have a clear plan with regards to whether or not disclose the plugin to the community or when.
If you are interested, you are welcome to reach out to EMQ's sales team.

For plugin development, the open source team is here to help if you are to develop your own plugin.
