### ISSUE TITLE
Way to stop sending messages of "publishing" via webhook after call the webapi publish/publish_batch

### ISSUE THREAD

**Issue by Robin2009** [emqx/emqx#4460]
Hi there,

I've activated the webhook plugin successfully and it works will, so each time when emqx borker received a message (say, pub by a client) it will call the api of my service and send the data to me along with the original client's information.  cool.

And when I want to send message to clients I just call the api "POST /api/v4/mqtt/publish" or "POST api/v4/mqtt/publish_batch", works fine as well. 

Here's the question, my service'll receive 100 messages after publish some data to 100 topics in batch, but that's actually quite unnecessary , as I just perform such an action-I know exxectlly what'd happend.  

So, is it possible to let emqx "don't" forward those events back to the service which just publish datas to raise those events? 

Or , is there any better implementation/suggestion for my work? 

Tks. Orz...

**Comment by zmstone** [comment]
Hi @Robin2009 
This does not seem to be supported if I am not mistaken.

As far as I can tell, we only have a hardcoded topic filter which drops messages sent to `$SYS/#` topics.
It would be useful if we can add configurable topic filters.

**Comment by Robin2009** [comment]
Thank you so much, that sounds cool. 


I guess this would help:

Parameters for publish_batch api: 
`
 "tag":"my_batch_publish",
[
		{
			"topic": "a/b/c",
			"payload": "Hello World",
			"qos": 1,
			"retain": false,
			"clientid": "example",
		},
		{
			"topic": "a/b/c",
			"payload": "Hello World Again",
			"qos": 0,
			"retain": false,
			"clientid": "example",
		}
	]
`

and **inside the emqx** (since it's not defined in the standard mqtt protocol ) each message should contains this extra parame just like this: 
`
{
	"topic": "a/b/c",
	"payload": "Hello World",
	"qos": 1,
	"retain": false,
	"clientid": "example",

       "tag":"my_batch_publish",
}
`

and now the configuration of webhook would look like ::
`
web.hook.rule.message.publish.1 = {"action": "on_message_publish", "topic": "a/b/c", "filter_no_pass_on_tag":"my_batch_publish"}
`

I'm not sure if this's the proper way to solve my problem. Just my personal opinion.

Again, I just wish emqx would possibly **not forward** my batch(or single) publish events via webhook after I call the publish(_batch) api.

**Comment by Robin2009** [comment]
Hi @zmstone . Thanks for the reply.
Sorry I didn't make my point clearly enough.
![image](https://user-images.githubusercontent.com/6648354/113079569-c5300780-9181-11eb-82e1-777da57407a0.png)

I hope my server could still receive the events raised due to the client a/b sent something to the broker.  ( ② , ③ )
But I don't want the broker forward those events to my server after my server pushed messages to the broker in batch. ( ① )  so my server need not to handle the callbacks from webhook plugin cause they're in huge numbers and  meaningless to me. 

Ok, I probably know what I truly need: 
`web.hook.rule.message.publish.1 = {"action": "on_message_publish", "clientid": " ^ clientid_of_my_server "}`

Is it possible ? Or it's been supported already?

**Comment by zmstone** [comment]
Hi @Robin2009 
If you configure the webhook actions to only act on `my/namespace/#` topics.
and the messages in `pulbish_batch` is produced to a different topic e.g. `no/loopback/to/server`
then the blue arrow labled `(1) msg_pub by My Server` should not happen.

**Comment by Robin2009** [comment]
Sure.  I think I know what mean, yet that's not what i mean to do. 
My server and the devices should both be able to  publish data to a same topic for some reason in my case. 
Once the webhook plugin has been activated, my server will be notified of the pub_event due to whoever published something to this topic. 
My server needs to receive the event which contains "who/when/what" information via webhook if the "who" represents a device.
But my server doesn't want to receive the event if the "who" represents itself. 

Anyway, thanks for your patient.  I should find some workaround on my issue. 👍🏻

**Comment by zmstone** [comment]
A MQTT client can subscribe multiple topics, or you can make server and other subscribers subscribe at different levels.
e.g. 
Sever subscribes to `my/namespace/#`, and publishes to `my/othernamespace/foo`
Other clients subscribe to `my/namespace/#` and `my/othernamespace/#` to receive messages from both publishers and server.

Or
Server subscribes to `my/namespace/clientpubs/#` and publishes to `my/namespace/serverpubs/foo`
Clients subscribe to `my/namespace/#` to receive messages from both publisheers and server.

**Comment by Robin2009** [comment]
@zmstone Thanks for taking the time on this issue. Allow me to explain my question in Chinese in the end please. I'm not that confident with my English, hope you understand. 


在我的场景中:
有一个topic. 比如就叫` /my/namespace/foo`
有两个设备,其clientId分别为 c01和c02. 它们都向`/my/namespace/foo`定时publish一些数据.
有我自己的服务器, 它也会偶尔向该topic中publish一些数据.
此外还有一些subscriber在订阅这个topic. 

为了获知设备publish操作的详情(尤其是设备的clientId/username/ipaddress/payload), 我打开了emqx的webhook插件, 并让其把message.publish的事件详情发给我的服务器上的某个api接口. 当设备向`/my/namespace/foo`发布数据时, 我可以获取这些信息.

当我的服务器在向该topic中publish数据时, webhook也把message.publish事件详情发我了.我的api不得不也对这些回调做处理.
但实际上我并不需要这些信息, 因为这就是我的服务器刚刚通过web api发布给emqx broker的消息,  目前我的做法是在我的api中通过clientId/username来对请求做过滤, 如果message.publish.clientid/username是我的服务器时, 直接跳过. 但当我调用 `/api/v4/mqtt/publish或/api/v4/mqtt/publish_batch`接口批量发布数据时, 我的api接口会收到大量的请求. 这对我的服务器来说其实是一种性能浪费. 我想如果webhook此时不要调我的api就最好了.

所以如果在webhook插件中可以通过配置类似 `^clientId`的方式来过滤掉某个clientId(比如就是我的服务器使用的clientId)的事件, 这样我的服务器就不会收到这些因为它刚刚通过`/api/v4/mqtt/publish或/api/v4/mqtt/publish_batch`批量publish而引发的message.publish的事件回调. 

我明白您的意思. 我可以理解为, 我在设计使用topic时并没有遵循一些最佳实践. 比如对这个topic而言, 我的服务器实际上即是publisher同时也是subscriber. 但目前我还没有确定, 应该如何应对这样的场景. 

还是感谢您的耐心, 也感谢有emqx这样的工具.

**Comment by zmstone** [comment]
我们的建议是修改subscriber的行为让它们订阅两个不一样的topic。
或者修改publisher行为使用另一个topic。

如果publisher或subscriber都不可控，或很难进行升级，是否可以复制一份我们的webhook代码自己修改一下，变成一个第三方插件？这样具有极大的灵活性，但要求你们自己来构建项目

**Comment by Robin2009** [comment]
@zmstone 
收到. 受教了. 应该会尝试一下.
感谢您的建议 👍🏻
