### ISSUE TITLE
When calling API service, 503 appears occasionally

### ISSUE THREAD

**Issue by uuuuuuuu-s** [emqx/emqx#4469]
**Please describe your problem in detail, if necessary, you can upload the log file through the attachment**:
When calling API service, 503 appears occasionally

**Comment by 15300357128** [comment]
`POST http://emqx-prod:8081/api/v4/mqtt/publish` resulted in a `503 Service Unavailable`

**Comment by zmstone** [comment]
Hi @15300357128 
is it a cluster in k8s or is there a proxy or load-balancer in front of the node(s) ?
