### ISSUE TITLE
Can't delete topic metrics in dashboard

### ISSUE THREAD

**Issue by xiezhuojin** [emqx/emqx#4472]
**Environment**:
debian10 with docker install running emqx open sorce edition

- EMQ X version (e.g. `emqx_ctl status`): 
4.3 rc2
- Hardware configuration (e.g. `lscpu`):
- OS (e.g. `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Erlang/OTP version (in case you build emqx from source code): 
- Others:

**What happened and what you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Comment by tigercl** [comment]
@xiezhuojin It looks like it is running normally on my machine, do you see any error messages?

**Comment by xiezhuojin** [comment]
@tigercl I created a topic metric on dashboard and tried to delete it, then these was a pop up message saying "URL Not Found". I tried to look at the HTTP requset, which is a DELETE request to /topic-metrics/${topic}, but it return 404. After using ```emqx_ctl modules list``` to check emqx_mod_topic_metrics is indeed loaded then looked into the code, I guest these is something wrong with https://github.com/emqx/emqx/blob/master/lib-ce/emqx_modules/src/emqx_mod_topic_metrics.erl. Anyway, I hope this is helpful to you though I'm not good at erlang.

**Comment by tigercl** [comment]
@xiezhuojin After my reconfirmation, this is indeed a bug. Thanks very much for your feedback, we will fix it as soon as possible and will notify you in this issue after the fix.
