### ISSUE TITLE
Rules are only effective on one node after creation

### ISSUE THREAD

**Issue by HJianBo** [emqx/emqx#4487]
**Environment**:

- EMQ X version (e.g. `emqx_ctl status`):  v4.3.rc.1 - v4.3-rc.3
- Hardware configuration (e.g. `lscpu`):
- OS (e.g. `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Erlang/OTP version (in case you build emqx from source code): 
- Others:

**What happened and what you expected to happen**:

In the others node, the `emqx_hooks` ETS table not included hooked record:

RULES:
```
SELECT * FROM "t/#"
```

NODE1:
```
(emqx@192.168.0.239)2> ets:tab2list(emqx_hooks).
[{hook,'message.publish',
       [{callback,{emqx_rule_events,on_message_publish,
                                    [#{enabled => false,ignore_sys_message => true,qos => 1}]},
                  undefined,0}]},
 {hook,'client.connect',
       [{callback,{fun emqx_license:check/2,[]},undefined,0}]}]
```

NODE2:
```
(emqx@192.168.0.173)4> ets:tab2list(emqx_hooks).
[{hook,'client.connect',
       [{callback,{fun emqx_license:check/2,[]},undefined,0}]}]
```

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Comment by terry-xiaoyu** [comment]
The original PR: https://github.com/emqx/emqx/pull/4160/files
