### ISSUE TITLE
how to use emqx_auth_username plugin in v4.3.0

### ISSUE THREAD

**Issue by zhangchaoxu** [emqx/emqx#4490]
in lastest version v4.3.0
i can not find file emqx_auth_username.conf in /etc/emqx/plugins.
and the plugin is not work after i download the file from https://github.com/emqx/emqx-auth-username/tree/master/etc.
what should i for if i want to use emqx_auth_username plugin in v4.3.0.

Thanks

**Comment by zmstone** [comment]
hi @zhangchaoxu 
`emqx_auth_username` and `emqx_auth_clientid` are merged to `emqx_auth_mnesia`
we are working on data export from 4.0~4.2, and import to 4.3.

**Comment by zhangchaoxu** [comment]
fine, just work after i use emqx_auth_mnesia, please update wiki doc for detail, thanks

**Comment by zmstone** [comment]
@zhangchaoxu yeah, doc updates are a bit lagging behind. thanks for the tip.

**Comment by zmstone** [comment]
related: https://github.com/emqx/emqx-docs/pull/730
