### ISSUE TITLE
SSL Resumption Support

### ISSUE THREAD

**Issue by Nishant-Pathak** [emqx/emqx#451]
Hi,

Does emqtt support ssl resumption (both session id and ticket). Is there a way to verify it?  We used ssyze for both https and xmpp, but seems there is no such tool for mqtt.
## 

Thanks

**Comment by bangarharshit** [comment]
+1. Tracking it. Its super important since ssl frequently timed out without this and would love to know how to test this?

**Comment by bangarharshit** [comment]
We have verified with sslyze - session id is supported and session ticket is not supported. Closing it.

**Comment by erylee** [comment]
@bangarharshit @Nishant-Pathak I will check this feature in 0.17 release.

**Comment by mpoornima** [comment]
Does this work in a clustered setup too? As in if a client connects to a broker `node1`, disconnects and reconnects to `node2`, does the resume happen in this case?

**Comment by bangarharshit** [comment]
Good point. We didn't think of it (as none of the mqtt clients support it) but I believe it willl not work. You will probably need something like haproxy to be reliable. Use non secure session between haproxy and emqtt. I guess ssl resumption will be it's responsibility and looks to me it should work then - https://kura.io/2014/02/22/haproxy-stateful-ssl-session-resumption/.

**Comment by zmstone** [comment]
closing it for inactivity.

Although now with TLS 1.3 in place, session resumption seem to be quite straightforward to implement.
ref: https://erlang.org/doc/apps/ssl/using_ssl.html#session-tickets-and-session-resumption-in-tls-1.3
