### ISSUE TITLE
emqx does not compile in Alpine 3.13

### ISSUE THREAD

**Issue by cocoaway** [emqx/emqx#4524]
**Environment**:

- EMQ X version (e.g. `emqx_ctl status`): latest
- Hardware configuration (e.g. `lscpu`): alpine 3.13 on virtual machine
- OS (e.g. `cat /etc/os-release`): Alpine 3.13
- Kernel (e.g. `uname -a`):
- Erlang/OTP version (in case you build emqx from source code): Alpine erlang-dev package
- Others:

**What happened and what you expected to happen**:
run make, start compiling, immediatly after 
Compiling emqx_web_hook
===> Compiling emqx_dashboard
===> Compiling emqx_modules
===> Compiling emqx_telemetry
===> [relup_helper] running gen_appups
===> **Uncaught error in rebar_core. Run with DIAGNOSTIC=1 to see stacktrace or consult rebar3.crashdump**
===> When submitting a bug report, please include the output of `rebar3 report "your command"`
make: *** [Makefile:69: emqx] Error 1

**How to reproduce it (as minimally and precisely as possible)**:
cd emqx
make

**Anything else we need to know?**:

**Comment by zmstone** [comment]
Odd, we have alpine in our ci pipeline.
Could you set `export DIAGNOSTIC=1`, and send the error messages?

**Comment by cocoaway** [comment]
Hi,

made make with `export DIAGNOSTIC=1`
 ...

===> Solving Release emqx-4.3-rc.3-2a9a5e74
===> Uncaught error in rebar_core. Run with DIAGNOSTIC=1 to see stacktrace or consult rebar3.crashdump
===> Uncaught error: {badmatch,{error,enoent}}
===> Stack trace to the error location:
[{rlx_resolve,to_app,3,
              [{file,"/src/_build/default/lib/relx/src/rlx_resolve.erl"},
               {line,197}]},
 {rlx_resolve,find_app_in_code_path,2,
              [{file,"/src/_build/default/lib/relx/src/rlx_resolve.erl"},
               {line,180}]},
 {rlx_resolve,subset,6,
              [{file,"/src/_build/default/lib/relx/src/rlx_resolve.erl"},
               {line,66}]},
 {rlx_resolve,solve_release,2,
              [{file,"/src/_build/default/lib/relx/src/rlx_resolve.erl"},
               {line,47}]},
 {relx,build_release_,3,
       [{file,"/src/_build/default/lib/relx/src/relx.erl"},{line,170}]},
 {relx,build_release,3,
       [{file,"/src/_build/default/lib/relx/src/relx.erl"},{line,77}]},
 {rebar_relx,do,2,[{file,"rebar_relx.erl"},{line,67}]},
 {rebar_core,do,2,[{file,"rebar_core.erl"},{line,155}]},
 {rebar_prv_do,do_task,5,[{file,"rebar_prv_do.erl"},{line,75}]},
 {rebar_core,do,2,[{file,"rebar_core.erl"},{line,155}]},
 {rebar_prv_do,do_task,5,[{file,"rebar_prv_do.erl"},{line,75}]},
 {rebar_core,do,2,[{file,"rebar_core.erl"},{line,155}]},
 {rebar3,run_aux,2,[{file,"rebar3.erl"},{line,181}]},
 {rebar3,main,1,[{file,"rebar3.erl"},{line,66}]},
 {escript,run,2,[{file,"escript.erl"},{line,758}]},
 {escript,start,1,[{file,"escript.erl"},{line,277}]},
 {init,start_em,1,[]},
 {init,do_boot,3,[]}]
===> When submitting a bug report, please include the output of `rebar3 report "your command"`
make: *** [Makefile:69: emqx] Error 1




here is the content of  `rebar3.crashdump` 


Error: {badmatch,{error,enoent}}
[{rlx_resolve,to_app,3,
              [{file,"/src/_build/default/lib/relx/src/rlx_resolve.erl"},
               {line,197}]},
 {rlx_resolve,find_app_in_code_path,2,
              [{file,"/src/_build/default/lib/relx/src/rlx_resolve.erl"},
               {line,180}]},
 {rlx_resolve,subset,6,
              [{file,"/src/_build/default/lib/relx/src/rlx_resolve.erl"},
               {line,66}]},
 {rlx_resolve,solve_release,2,
              [{file,"/src/_build/default/lib/relx/src/rlx_resolve.erl"},
               {line,47}]},
 {relx,build_release_,3,
       [{file,"/src/_build/default/lib/relx/src/relx.erl"},{line,170}]},
 {relx,build_release,3,
       [{file,"/src/_build/default/lib/relx/src/relx.erl"},{line,77}]},
 {rebar_relx,do,2,[{file,"rebar_relx.erl"},{line,67}]},
 {rebar_core,do,2,[{file,"rebar_core.erl"},{line,155}]},
 {rebar_prv_do,do_task,5,[{file,"rebar_prv_do.erl"},{line,75}]},
 {rebar_core,do,2,[{file,"rebar_core.erl"},{line,155}]},
 {rebar_prv_do,do_task,5,[{file,"rebar_prv_do.erl"},{line,75}]},
 {rebar_core,do,2,[{file,"rebar_core.erl"},{line,155}]},
 {rebar3,run_aux,2,[{file,"rebar3.erl"},{line,181}]},
 {rebar3,main,1,[{file,"rebar3.erl"},{line,66}]},
 {escript,run,2,[{file,"escript.erl"},{line,758}]},
 {escript,start,1,[{file,"escript.erl"},{line,277}]},
 {init,start_em,1,[]},
 {init,do_boot,3,[]}]

**Comment by zmstone** [comment]
hi @cocoaway 
This is unfortunately not quite helpful to identify which app caused the crash.

You said "Alpine erlang-dev package"  could you be more specific on which exact OTP version it is?
If you are not sure, you can run this command to inspect:
`docker run -it --rm <your-erlang-image-name> erl -noshell -eval 'io:format("~s~n", [erlang:system_info(otp_release)]),init:stop(0).'`

I have tested it with our build image like below:
`docker run -it --rm emqx/build-env:erl23.2.7-alpine-amd64 bash -c 'git clone https://github.com/emqx/emqx.git; cd emqx; make'`

**Comment by zmstone** [comment]
@cocoaway btw it requires `bash` to build and run emqx

**Comment by cocoaway** [comment]
@zmstone 
bash is intalled

apk info erlang-dev
erlang-dev-23.1.5-r0 description:
General-purpose programming language and runtime environment (development files)


I'm trying to compile emqx on a native Alpine distro not with docker.

**Comment by zmstone** [comment]
could you compare the outputs of below commands:
`ls _build/emqx/lib/ | xargs echo | tr ' ' '\n' | sort`
`find _build/{emqx,default}/lib/ -maxdepth 3 -name '*.app' | xargs -I{} basename -s .app -- {} | sort`

If everything is fine, the commands should print 68 lines, and two outputs should be identical.
If not, please proved the diff.

**Comment by cocoaway** [comment]
Hi,
the command `find _build/{emqx,default}/lib/ -maxdepth 3 -name '*.app' | xargs -I{} basename -s .app -- {} | sort` returns a lot of :  


Usage: basename FILE [SUFFIX]

Strip directory path and .SUFFIX from FILE
BusyBox v1.32.1 () multi-call binary.



The command `ls _build/emqx/lib/ | xargs echo | tr ' ' '\n' | sort`  returns a list of filenames : 

base64url
bcrypt
bson
cowboy
cowlib
cuttlefish
ecpool
ehttpc
ekka
eldap2
emqtt
emqx
emqx_auth_http
emqx_auth_jwt
emqx_auth_ldap
emqx_auth_mnesia
emqx_auth_mongo
emqx_auth_mysql
emqx_auth_pgsql
emqx_auth_redis
emqx_bridge_mqtt
emqx_coap
emqx_dashboard
emqx_exhook
emqx_exproto
emqx_lua_hook
emqx_lwm2m
emqx_management
emqx_modules
emqx_plugin_libs
emqx_prometheus
emqx_psk_file
emqx_recon
emqx_retainer
emqx_rule_engine
emqx_sasl
emqx_sn
emqx_stomp
emqx_telemetry
emqx_web_hook
epgsql
eredis
eredis_cluster
esockd
gen_coap
gen_rpc
getopt
gpb
gproc
grpc
gun
jiffy
jose
luerl
lwm2m_coap
minirest
mongodb
mysql
observer_cli
pbkdf2
poolboy
prometheus
ranch
recon
replayq
rulesql
snabbkaffe
ssl_verify_fun

**Comment by zmstone** [comment]
please send output of command
find _build/{emqx,default}/lib/ -maxdepth 3 -name '*.app'

**Comment by cocoaway** [comment]
`find _build/{emqx,default}/lib/ -maxdepth 3 -name '*.app'`


_build/emqx/lib/emqx_retainer/ebin/emqx_retainer.app
_build/emqx/lib/emqx_auth_ldap/ebin/emqx_auth_ldap.app
_build/emqx/lib/emqx_sasl/ebin/emqx_sasl.app
_build/emqx/lib/emqx_stomp/ebin/emqx_stomp.app
_build/emqx/lib/emqx_auth_jwt/ebin/emqx_auth_jwt.app
_build/emqx/lib/emqx_auth_mnesia/ebin/emqx_auth_mnesia.app
_build/emqx/lib/emqx_rule_engine/ebin/emqx_rule_engine.app
_build/emqx/lib/emqx_psk_file/ebin/emqx_psk_file.app
_build/emqx/lib/emqx_telemetry/ebin/emqx_telemetry.app
_build/emqx/lib/emqx_web_hook/ebin/emqx_web_hook.app
_build/emqx/lib/emqx_auth_pgsql/ebin/emqx_auth_pgsql.app
_build/emqx/lib/emqx_auth_redis/ebin/emqx_auth_redis.app
_build/emqx/lib/emqx_prometheus/ebin/emqx_prometheus.app
_build/emqx/lib/emqx_sn/ebin/emqx_sn.app
_build/emqx/lib/emqx_modules/ebin/emqx_modules.app
_build/emqx/lib/emqx_dashboard/ebin/emqx_dashboard.app
_build/emqx/lib/emqx_auth_mysql/ebin/emqx_auth_mysql.app
_build/emqx/lib/emqx_auth_http/ebin/emqx_auth_http.app
_build/emqx/lib/emqx/ebin/emqx.app
_build/emqx/lib/emqx_plugin_libs/ebin/emqx_plugin_libs.app
_build/emqx/lib/emqx_management/ebin/emqx_management.app
_build/emqx/lib/emqx_bridge_mqtt/ebin/emqx_bridge_mqtt.app
_build/emqx/lib/emqx_exproto/ebin/emqx_exproto.app
_build/emqx/lib/emqx_lwm2m/ebin/emqx_lwm2m.app
_build/emqx/lib/emqx_auth_mongo/ebin/emqx_auth_mongo.app
_build/emqx/lib/emqx_exhook/ebin/emqx_exhook.app
_build/emqx/lib/emqx_lua_hook/ebin/emqx_lua_hook.app
_build/emqx/lib/emqx_coap/ebin/emqx_coap.app
_build/emqx/lib/emqx_recon/ebin/emqx_recon.app
_build/default/lib/gproc/ebin/gproc.app
_build/default/lib/gpb/ebin/gpb.app
_build/default/lib/mysql/ebin/mysql.app
_build/default/lib/jiffy/ebin/jiffy.app
_build/default/lib/mongodb/ebin/mongodb.app
_build/default/lib/ehttpc/ebin/ehttpc.app
_build/default/lib/esockd/ebin/esockd.app
_build/default/lib/ranch/ebin/ranch.app
_build/default/lib/base64url/ebin/base64url.app
_build/default/lib/grpc/ebin/grpc.app
_build/default/lib/luerl/ebin/luerl.app
_build/default/lib/poolboy/ebin/poolboy.app
_build/default/lib/jose/ebin/jose.app
_build/default/lib/rulesql/ebin/rulesql.app
_build/default/lib/emqtt/ebin/emqtt.app
_build/default/lib/cowlib/ebin/cowlib.app
_build/default/lib/gen_coap/ebin/gen_coap.app
_build/default/lib/bson/ebin/bson.app
_build/default/lib/cowboy/ebin/cowboy.app
_build/default/lib/snabbkaffe/ebin/snabbkaffe.app
_build/default/lib/cuttlefish/ebin/cuttlefish.app
_build/default/lib/replayq/ebin/replayq.app
_build/default/lib/ssl_verify_fun/ebin/ssl_verify_fun.app
_build/default/lib/observer_cli/ebin/observer_cli.app
_build/default/lib/prometheus/ebin/prometheus.app
_build/default/lib/epgsql/ebin/epgsql.app
_build/default/lib/getopt/ebin/getopt.app
_build/default/lib/pbkdf2/ebin/pbkdf2.app
_build/default/lib/bcrypt/ebin/bcrypt.app
_build/default/lib/recon/ebin/recon.app
_build/default/lib/gun/ebin/gun.app
_build/default/lib/minirest/ebin/minirest.app
_build/default/lib/eredis_cluster/ebin/eredis_cluster.app
_build/default/lib/eldap2/ebin/eldap2.app
_build/default/lib/gen_rpc/ebin/gen_rpc.app
_build/default/lib/ecpool/ebin/ecpool.app
_build/default/lib/ekka/ebin/ekka.app
_build/default/lib/lwm2m_coap/ebin/lwm2m_coap.app
_build/default/lib/eredis/ebin/eredis.app

**Comment by zmstone** [comment]
Thank you.
It seems all EMQ applications are compiled correctly.
Could you send the output of this command `find _build/emqx/rel/emqx/lib/ -name '*.app' -type f | sort`

**Comment by zmstone** [comment]
Hi @cocoaway 

I have just merged this PR: https://github.com/emqx/emqx/pull/4530
It will now print the error details about which Erlang app caused the crash.

Could you try to pull the latest `master` branch and try again with below commands:

```
export DIAGNOSTIC=1
make
```

**Comment by cocoaway** [comment]
Hi @zmstone ,

===> Solving Release emqx-4.3-rc.3-41168065
escript: exception error: no function clause matching
                 rlx_resolve:format_error({bad_app_file,
                                           "/usr/lib/erlang/lib/observer-2.9.5/ebin/observer.app",
                                           {error,enoent}}) (/src/_build/default/lib/relx/src/rlx_resolve.erl, line 10)
  in function  rebar3:handle_error/2 (rebar3.erl, line 346)
  in call from escript:run/2 (escript.erl, line 758)
  in call from escript:start/1 (escript.erl, line 277)
  in call from init:start_em/1
  in call from init:do_boot/3
make: *** [Makefile:69: emqx] Error 127

**Comment by cocoaway** [comment]
@zmstone Here is the full log of make
[log.txt](https://github.com/emqx/emqx/files/6291532/log.txt)

**Comment by zmstone** [comment]
Thank you @cocoaway 
Will be fixed in #4533

**Comment by cocoaway** [comment]
@zmstone Thanks to you !
