### ISSUE TITLE
Can data stream names and rule names support Chinese names?

### ISSUE THREAD

**Issue by feng-crazy** [emqx/emqx#4539]
This is because the name of the Kuiper stream must match the name of the device type, and the device type supports Chinese in the system.

**Comment by HJianBo** [comment]
Hi, @feng-crazy Very happy to hear your advice.

Can you give an example? For example, what kind of rule would need to be created?

**Comment by zmstone** [comment]
rule names are also used as identifiers internally. 
starting from v5.5, one can add tags and descriptions to rules which will allow free text as long as they are utf8 encoded.
