### ISSUE TITLE
subscription lose sometimes

### ISSUE THREAD

**Issue by seqwait** [emqx/emqx#4546]
**Environment**:
- EMQ X version v4.0.0:

 a client subscribe some sys topic after N day the subscribe topics missed and how investigate the question? now i must  used crontab check  'http://localhost:18083/api/v4/subscriptions/clientId' if checked lose i reconn and resub!

**Comment by tigercl** [comment]
@seqwait Sorry for taking so long to reply to you. Will your client re-subscribe to related topics after reconnecting? I guess it was disconnected in the middle.

**Comment by tigercl** [comment]
Since no one responded for a long time, I closed this issue. If you need to continue, you can reopen it at any time.
