### ISSUE TITLE
Message retransmission ‘message.delivered’ hooked

### ISSUE THREAD

**Issue by DDDHuang** [emqx/emqx#4557]
- EMQ X version (e.g. `emqx_ctl status`):  4.X

When message retransmission (dup message ), ‘message.delivered’ should not be hooked

**Comment by terry-xiaoyu** [comment]
But if the `dup` flag was set correctly, someone could distinguish the `message.delievered` event triggered by the normal message-sending and the ones triggered by retranslations.
