### ISSUE TITLE
install fail

### ISSUE THREAD

**Issue by doncici** [emqx/emqx#4562]
**Please describe your problem in detail, if necessary, you can upload the log file through the attachment**:
现在有个问题，在尝试安装emqx broker 4.2稳定版的时候，启动报错
now i got a issue, when I am trying to install emqx broker4.2 stable version ,i got following issue .
![image](https://user-images.githubusercontent.com/58241861/114649297-d7c64700-9d12-11eb-85b1-eb0c8efa008c.png)

然后再尝试安装其他低版本的时候，相关依赖包又报错
and when i am trying to install older version ,there is issue about the dependency package.
![image](https://user-images.githubusercontent.com/58241861/114649354-f3c9e880-9d12-11eb-93ef-5f1baa627dd8.png)
哪位大神帮忙看一下呀，
thanks a lot 
[crash.txt](https://github.com/emqx/emqx/files/6307984/crash.txt)

**Comment by HJianBo** [comment]
Plz see: https://docs.emqx.cn/broker/v4.3/faq/error.html#openssl-版本不正确

**Comment by doncici** [comment]
> Plz see: [https://docs.emqx.cn/broker/v4.3/faq/error.html#openssl-版本不正确](https://docs.emqx.cn/broker/v4.3/faq/error.html#openssl-%E7%89%88%E6%9C%AC%E4%B8%8D%E6%AD%A3%E7%A1%AE)

谢谢，问题解决了，因为我8.0的操作系统 装错了版本
