### ISSUE TITLE
测试非加密连接时，可以支持每秒建立700个连接；加密连接时只能支持每秒100个连接，请问有什么办法可以改善吗？

### ISSUE THREAD

**Issue by CH1NL1ANG** [emqx/emqx#4567]
**Please describe your problem in detail, if necessary, you can upload the log file through the attachment**:

**Comment by CH1NL1ANG** [comment]
问题表现为，测试加密连接时，每秒超过100个连接，服务器的CPU会飚到非常高，客户端这边提示connect error

**Comment by yogkang** [comment]
SSL 的连接可定是会耗 CPU 。我想了解下你那边是 tcp 最高压测出来的每秒连接数是多少。
