### ISSUE TITLE
community plugin build problem

### ISSUE THREAD

**Issue by sh3d2** [emqx/emqx#4568]
**Environment**:

- EMQ X version (e.g. `emqx_ctl status`):  EMQ X Broker 4.3-rc.3-28a41eb7 is running now!
- Erlang/OTP version (in case you build emqx from source code):  Erlang/OTP 23 [erts-11.1.4] [source] [64-bit] [smp:4:4] [ds:4:4:8] [async-threads:4] [hipe] [dtrace]

**What happened and what you expected to happen**:

When developing a community plugin (following the plugin development guide) one is not able to use emqx-logger. 
With 
```
-include_lib("emqx/include/logger.hrl").
```
 build fails with 
```
===> Compiling emqx_topic_manager
===> Compiling _build/default/lib/emqx_topic_manager/src/emqx_topic_manager.erl failed
emqx_topic_manager.erl:23: can't find include lib "emqx/include/emqx.hrl"; Make sure emqx is in your app file's 'applications' list
emqx_topic_manager.erl:24: can't find include lib "emqx/include/logger.hrl"; Make sure emqx is in your app file's 'applications' list
emqx_topic_manager.erl:25: can't find include lib "emqx/include/types.hrl"; Make sure emqx is in your app file's 'applications' list

```

and for 
```
-include("logger.hrl").
```
fails with 
```
===> Compiling emqx_topic_manager
===> Compiling _build/default/lib/emqx_topic_manager/src/emqx_topic_manager.erl failed
_build/default/lib/emqx_topic_manager/src/emqx_topic_manager.erl:none: undefined parse transform 'emqx_logger'

make: *** [emqx] Error 1

```

i expect the plugin to build ok 😄 

**How to reproduce it (as minimally and precisely as possible)**:

Just try to use logger inside an extra-plugin

**Anything else we need to know?**:

i understand, that its a matter of plugin being compiled before emqx (thus the parse transform error) but im not able to figure out how to make it work:( 

im happy to try to fix it, just dont know where to start, any pointers will be much appreciated

**Comment by zmstone** [comment]
Hi @sh3d2 
You can try `include` not `include_lib`.
ref: https://github.com/emqx/emqx/blob/master/rebar.config.erl#L51-L52

**Comment by sh3d2** [comment]
i did try that 
```
-include("logger.hrl").
```

results in 
```
===> Compiling emqx_topic_manager
===> Compiling _build/default/lib/emqx_topic_manager/src/emqx_topic_manager.erl failed
_build/default/lib/emqx_topic_manager/src/emqx_topic_manager.erl:none: undefined parse transform 'emqx_logger'

make: *** [emqx] Error 1
```

**Comment by zmstone** [comment]
For logging, I'd recommend not to use emqx_logger.
logger should do just fine.

**Comment by sh3d2** [comment]
> For logging, I'd recommend not to use emqx_logger.
> logger should do just fine.

out of curiosity whats the reason behind that?

As for logger, will it respect log levels and targets set in `emqx.conf`? I guess (even a) custom developed plugin should follow general emqx log settings

**Comment by zmstone** [comment]
The log level settings in emqx.conf is global.
The parse-transform in emqx_logger makes use of some module attributes and add them as log line prefix see: https://github.com/emqx/emqx/blob/4a388400a54db5a258fcb6dfede7b909e47b1b06/src/emqx_logger.erl#L229-L231

We can add log metadata without module attributes or parse-transform.

**Comment by sh3d2** [comment]
actually the module attribute way of setting log prefix looked pretty slick ;) 

anyways, logging works just fine with `logger` alone.

**Comment by zmstone** [comment]
We are moving to structured logging. e.g json.
And we may as we

**Comment by sh3d2** [comment]
> We are moving to structured logging. e.g json.

great idea. it will make analysing emqx logs with ie ELK much easier 👍
