### ISSUE TITLE
[emqx_auth_http] Disable ACL not possible with current master / 4.3.x

### ISSUE THREAD

**Issue by gbrehmer** [emqx/emqx#4602]
Plugin can not be loaded, if I want to disable ACL requests:

I'm using Docker and disable ACL by setting ENV variables (works with 4.2.x):
```
EMQX_AUTH__HTTP__ACL_REQ__URL: ""
EMQX_AUTH__HTTP__ACL_REQ__METHOD: ""
```

Error on load:
```
2021-04-16 10:38:50.685 [alert] [Plugins] Plugin emqx_auth_http load failed with {function_clause,
                                                  [{emqx_plugins,
                                                    apply_configs,
                                                    [{error,
                                                      transform_datatypes,
                                                      {errorlist,
                                                       [{error,
                                                         {transform_type,
                                                          "auth.http.acl_req.method"}},
                                                        {error,
                                                         {enum_name,
                                                          {[],
                                                           ["post",
                                                            "get"]}}}]}}],
                                                    [{file,"emqx_plugins.erl"},
                                                     {line,240}]},
                                                   {emqx_plugins,load_plugin,
                                                    2,
                                                    [{file,"emqx_plugins.erl"},
                                                     {line,263}]},
                                                   {lists,foreach,2,
                                                    [{file,"lists.erl"},
                                                     {line,1342}]},
                                                   {emqx_app,start,2,
                                                    [{file,"emqx_app.erl"},
                                                     {line,43}]},
                                                   {application_master,
                                                    start_it_old,4,
                                                    [{file,
                                                      "application_master.erl"},
                                                     {line,277}]}]}
```

btw new Parameter headers can not be overridden with ENV Variables because HTTP Header name contains hyphens (e.g. content-type)

**Comment by gbrehmer** [comment]
resulting conf file part (after applying docker env props):
```
## HTTP URL API path for ACL Request
##
## Value: URL
##
## Examples: http://127.0.0.1:80/mqtt/acl, https://[::1]:80/mqtt/acl
# auth.http.acl_req.url = http://127.0.0.1:80/mqtt/acl

## HTTP Request Method for ACL Request
##
## Value: post | get
# auth.http.acl_req.method = post

## HTTP Request Headers for ACL Request, Content-Type header is configured by default.
## The possible values of the Content-Type header: application/x-www-form-urlencoded, application/json
##
## Examples: auth.http.acl_req.headers.accept = */*
# auth.http.acl_req.headers.content-type = application/x-www-form-urlencoded

## Parameters used to construct the request body or query string parameters
## When the request method is GET, these parameters will be converted into query string parameters
## When the request method is POST, the final format is determined by content-type
##
## Available Variables:
##  - %u: username
##  - %c: clientid
##  - %a: ipaddress
##  - %r: protocol
##  - %P: password
##  - %p: sockport of server accepted
##  - %C: common name of client TLS cert
##  - %d: subject of client TLS cert
##
## Value: <K1>=<V1>,<K2>=<V2>,...
# auth.http.acl_req.params = access=%A,username=%u,clientid=%c,ipaddr=%a,topic=%t,mountpoint=%m
```

**Comment by zmstone** [comment]
hi @gbrehmer 

thank you for reporting this.
we'll fix it asap.

this is a bug in env variable override.

As a workaround, you can modify the config file instead of using env override.

**Comment by gbrehmer** [comment]
Ah I realized that docker entrypoint was changed too, I'm still using a copy from "old" emqx-rel https://github.com/emqx/emqx-rel/blob/master/deploy/docker/docker-entrypoint.sh - there properties can be disabled by setting empty string, then properties will be commented out. Has this been changed with 4.3.x?

**Comment by z8674558** [comment]
Hi. In v4.3, we replace variables in Erlang runtime instead of rewriting config files by `sed`.
https://github.com/emqx/cuttlefish/blob/c16a4bbe330f11062839fe087d23d9ded9b9cdde/src/cuttlefish_generator.erl#L52
We are now fixing it to unset existing fields when env variable is set to "".

**Comment by gbrehmer** [comment]
thanks for clarification, so my bug report was a little bit misleading because I used the outdated mechanism. sorry for that.  Is there  a workaround for unsetting variables until fix is available? I tried uncommenting in conf file and setting empty value, both seems not to work for ACL-props from emqx_auth_http plugin

**Comment by zmstone** [comment]
> thanks for clarification, so my bug report was a little bit misleading because I used the outdated mechanism. sorry for that. Is there a workaround for unsetting variables until fix is available? I tried commenting-out in conf file and setting empty value, both seems not to work for ACL-props from emqx_auth_http plugin

No worries, I figured that you were probably assuming the old way.
It should work by commenting out the line like this: `# auth.http.acl_req.url = http://127.0.0.1:80/mqtt/acl`
but do not set environment variable.

I tested it yesterday, it should work.
You can evaluate `os:getenv("EMQX_AUTH__HTTP__ACL_REQ__URL")` from Erlang console to double check.

**Comment by zmstone** [comment]
https://github.com/emqx/cuttlefish/pull/26
the fix has been merged thank you @z8674558 for the quick action.
I am testing it on master branch now.

**Comment by gbrehmer** [comment]
> It should work by commenting out the line like this: `# auth.http.acl_req.url = http://127.0.0.1:80/mqtt/acl`
> but do not set environment variable.
> 
> I tested it yesterday, it should work.

It's working for `auth.http.acl_req.url` but if I change `auth.http.acl_req.method` the following error occurs, probably a plugin-specific problem.

```
2021-04-16 10:38:50.685 [alert] [Plugins] Plugin emqx_auth_http load failed with {function_clause,
                                                  [{emqx_plugins,
                                                    apply_configs,
                                                    [{error,
                                                      transform_datatypes,
                                                      {errorlist,
                                                       [{error,
                                                         {transform_type,
                                                          "auth.http.acl_req.method"}},
                                                        {error,
                                                         {enum_name,
                                                          {[],
                                                           ["post",
                                                            "get"]}}}]}}],
                                                    [{file,"emqx_plugins.erl"},
                                                     {line,240}]},
                                                   {emqx_plugins,load_plugin,
                                                    2,
                                                    [{file,"emqx_plugins.erl"},
                                                     {line,263}]},
                                                   {lists,foreach,2,
                                                    [{file,"lists.erl"},
                                                     {line,1342}]},
                                                   {emqx_app,start,2,
                                                    [{file,"emqx_app.erl"},
                                                     {line,43}]},
                                                   {application_master,
                                                    start_it_old,4,
                                                    [{file,
                                                      "application_master.erl"},
                                                     {line,277}]}]}
```

**Comment by zmstone** [comment]
acl is disabled if `auth.http.acl_req.url` is commented out
you can leave the post method unchanged.
will update the doc.

**Comment by gbrehmer** [comment]
> acl is disabled if `auth.http.acl_req.url` is commented out

If I disable only acl, I got this error on publish/connect:

```
2021-04-17 13:15:21.673 [error] <<"dev-wa48-2-8docker">>@10.3.10.192:47254 [ACL http] Request ACL path /, error: {badarg,[]}
2021-04-17 13:15:21.675 [error]   crasher:
    initial call: gun:proc_lib_hack/5
    pid: <0.2645.0>
    registered_name: []
    exception exit: {badarg,[]}
      in function  gun:proc_lib_hack/5 (gun.erl, line 654)
    ancestors: [gun_sup,<0.1815.0>]
    message_queue_len: 0
    messages: []
    links: [<0.1816.0>]
    dictionary: []
    trap_exit: false
    status: running
    heap_size: 376
    stack_size: 28
    reductions: 225
  neighbours:
```

**Comment by zmstone** [comment]
Hi @gbrehmer 
which version are you running ?
if it's commented out, the `clieng.check_acl` hook should not be registered.
evaluate `emqx_hooks:lookup('client.check_acl').` in Erlang console to double check.
`application:get_all_env(emqx_auth_http).` to inspect the plugin's configs.

could you share the outputs of above two commands ?

**Comment by gbrehmer** [comment]
> which version are you running ?

current master (custom build with private build pipeline)

> evaluate `emqx_hooks:lookup('client.check_acl').` in Erlang console to double check.

```
...
 {acl_req,[{path,"/"},
           {headers,[{"content-type",
                      "application/x-www-form-urlencoded"}]},
           {timeout,5000},
           {pool_name,'emqx_auth_http/acl_req'},
           {pool_opts,[{host,[]},
                       {port,80},
                       {pool_size,32},
                       {pool_type,random},
                       {connect_timeout,5000},
                       {retry,5},
                       {retry_timeout,1000},
                       {transport_opts,[inet]}]},
           {url,[]},
           {method,post},
           {params,[{"access","%A"},
                    {"username","%u"},
                    {"clientid","%c"},
                    {"ipaddr","%a"},
                    {"topic","%t"},
                    {"mountpoint","%m"}]}]},
...
```

so it  seems that commenting out is not enough?

**Comment by zmstone** [comment]
Hi @gbrehmer

Could you check if you have:
1. unset the environment variable (if still running old version cuttlefish, before v3.3.3)
2. it's the correct file to comment out, if you have modified the source code, delete `_build` directory and try again
  or make sure you have modified the conf file in `_build/emqx/rel/emqx/etc/plugins/`
3. make sure application `emqx_auth_http` is restarted after config change

**Comment by gbrehmer** [comment]
I can not find any mistake:

I'm still using old docker entrypoint script which updates the config files based on env varibales.
I've checked the conf file in the running docker container:

```
...
## Examples: http://127.0.0.1:80/mqtt/acl, https://[::1]:80/mqtt/acl
# auth.http.acl_req.url = http://127.0.0.1:80/mqtt/acl

## HTTP Request Method for ACL Request
##
## Value: post | get
auth.http.acl_req.method = post
..
```

as you can see url is commented out, otherwise the default url will be set, but as you can see in my previous post, url is not set at all (only empty array). It is possible that url is immutable or the checker wether url is set or not is faulty?
I can check non docker build but that is not our target environment.

**Comment by zmstone** [comment]
I think commenting it out should work, manually or script doesn’t matter.
But cuttlefish also does it (override twice).

Then there was a bug in cuttlefish which overrides with empty string.

This is why I asked if you have pulled cuttlefish v3.3.3 in your build

**Comment by gbrehmer** [comment]
Ah now I understand, because I use old docker entrypoint with env variables, both mechanisms - old and new -  are used. Yes still using 3.3.2. okay then 3.3.3 should fix it. I can change my entrypoint script and env variables in the meantime

**Comment by zmstone** [comment]
If you need to keep using docker entrypoint override (May I ask what the reason is?), maybe you can try a different prefix (other than `EMQX_` if it’s for your own config.

**Comment by zmstone** [comment]
Thank you for the bug reports and patience with us.

**Comment by gbrehmer** [comment]
We will switch to new mechanism, but I'm little bit confused regarding new mechanism: 
The new mechanism uses the environment variables directly and if I understand the cuttlefish bug report, the fix was only for 4.2 or our approach.
How do I set the environment variable to disable the url?

**Comment by zmstone** [comment]
> We will switch to new mechanism, but I'm little bit confused regarding new mechanism:
> The new mechanism uses the environment variables directly and if I understand the cuttlefish bug report, the fix was only for 4.2 or our approach.
> How do I set the environment variable to disable the url?

in 4.2, env overrides were supported by `sed` replacements for cuttlefish config (.conf) files which is slow and error prone.
in 4.3, env overrides were done by cuttlefish in memory
to make the overrides observable, node boot time overrides are printed to console, and plugin config overrides are logged to emqx logs (info level).

Now back to the bug, before cuttlefish v3.3.3, `EMQX_CONF__NAME=""` is mapped to `{conf_name, ""}`.
after the fix, it maps to `{conf_name, undefined}` which has the same effect as commenting out the line.

With cuttlefish v3.3.3, you can set `-e EMQX_AUTH__HTTP__ACL_REQ__URL=""` to disable auth-http ACL checks.

**Comment by gbrehmer** [comment]
sentence from pull request was confusing: "to be backward compatible to 4.2.x" 
`-e EMQX_AUTH__HTTP__ACL_REQ__URL=""` is still the way to go? Or 3.3.3 fixes both: backward compatibility and handling of of empty values for disabling settings

**Comment by zmstone** [comment]
Ah, sorry, should have been more clear. It fixes both.
Although it’s the same underlying problem.
I.e using empty string is not backward compatible to old behavior, but also, arguably more important: a bug made it unable to disable auth-http acl check from environment variables
