### ISSUE TITLE
MQTT Subscription Resource option missing from 4.3

### ISSUE THREAD

**Issue by matthewGEA** [emqx/emqx#4621]
The "MQTT Subscription" option for a Rules Engine resource is missing in 4.3-rc.3 and rc.4. Using the docker container.  Configured as a multicast discovery cluster.

I didn't try 4.3-rc alpha, beta, rc.1 or rc.2.

![image](https://user-images.githubusercontent.com/46966648/115124672-6811bf80-9f91-11eb-88f8-d14b37033033.png)

**Comment by matthewGEA** [comment]
I checked the docker container for 4.3-beta.1 and it the "MQTT Subscription" is missing there as well.

**Comment by tigercl** [comment]
@matthewGEA Sorry, this is a feature of the Enterprise Edition.

**Comment by matthewGEA** [comment]
I don't see how to create an MQTT Subscription resource in Enterprise Edition.  I am running version 4.2.5 (docker image) and only see the following Resource option when filtering for "mqtt":
![image](https://user-images.githubusercontent.com/46966648/115338393-bf21bb00-a170-11eb-8ce8-2497efe16f58.png)

**Comment by wivwiv** [comment]
Do you want to subscribe to remote broker topics?
like `AWS IoT Hub -> EMQ X`

You can use plugin `emqx_bridge_mqtt`

In rule engine the data is fanout.

**Comment by matthewGEA** [comment]
I have used the `emqx_bridge_mqtt` for subscriptions.  I want to know more about the "MQTT Subscribe" resource within the Rules Engine.

This note seen in the [release notes for version 4.2.0](https://docs.emqx.io/en/broker/v4.2/changes/changes-4.2.html#version-4-2-0):

> The rule engine supports the creation of subscriptions for MQTT bridges

In version 4.2.11, there exists a Rules Engine resource called "MQTT Subscribe"
![image](https://user-images.githubusercontent.com/46966648/115818805-8d586080-a3cb-11eb-91b3-888907ea723b.png)

I just found [this commit](https://github.com/emqx/emqx/commit/2fb5dbd54688e25561b3a25af9230f647a89f943#diff-5f4a3449ec365fbf8ccac63353794d481c104cd80350143f8fb9b023f48b5910) which has some description of why it was being dropped.

The main feature I was hoping to discover was a cluster-aware subscription, where in the case of a cluster, if any node goes down that the subscription continues.  With the MQTT bridge plugin, if the node that has the bridge setup goes down then the bridge is lost and must be setup on one of the remaining nodes.

Maybe having each node subscribe to a shared subscription so all nodes in the cluster can have the subscription active so data would not be duplicated?

**Comment by HJianBo** [comment]
> I just found this commit which has some description of why it was being dropped.

Yes, we have removed this feature after v4.3. You should use `emqx-bridge-mqtt` to replace it.

> Maybe having each node subscribe to a shared subscription so all nodes in the cluster can have the subscription active so data would not be duplicated?

Yes.  you should manually set the subscription topic to be a shared. For example:

```
bridge.mqtt.aws.clientid=cluster_a_bridge_worker_${node}
bridge.mqtt.aws.subscription.1.topic=$shared/bridge-grp/test/#
bridge.mqtt.aws.receive_mountpoint=receive/cluster-b/
```
