### ISSUE TITLE
community plugin deps missing 

### ISSUE THREAD

**Issue by sh3d2** [emqx/emqx#4633]
**Environment**:

- EMQ X version (e.g. `emqx_ctl status`): EMQ X Broker 4.3-rc.4-ad630f49 
- Hardware configuration (e.g. `lscpu`):
- OS (e.g. `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Erlang/OTP version (in case you build emqx from source code): Erlang/OTP 23 [erts-11.1.4] [source] [64-bit] [smp:4:4] [ds:4:4:8] [async-threads:4] [hipe] [dtrace]

- Others:

**What happened and what you expected to happen**:
when a custom plugin has its own deps ex:

```
➜  emqx git:(master) ✗ cat lib-extra/emqx-topic-manager/rebar.config 
{deps, [  {amqp_client, {git, "git://github.com/jbrisbin/amqp_client.git", {tag, "rabbitmq-3.6.2"}}}
]}.

{erl_opts, [debug_info]}.

```

after `make` i get the following error when starting the plugin:

```
EMQ X Broker 4.3-rc.4-ad630f49 is running now!
Eshell V11.1.4  (abort with ^G)
(emqx@127.0.0.1)1> 2021-04-19 12:04:42.577 [error] [Plugins] Load plugin emqx_topic_manager failed, cannot start plugin emqx_topic_manager for {bad_return,{{emqx_topic_manager_app,start,[normal,[]]},{'EXIT',{{badmatch,{error,{shutdown,{failed_to_start_child,emqx_topic_manager_publisher,{shutdown,{failed_to_start_child,worker_sup,{shutdown,{failed_to_start_child,{worker,1},{undef,[{amqp_connection,start,[{amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"localhost",undefined,0,0,10,infinity,none,[fun amqp_auth_mechanisms:plain/3,fun amqp_auth_mechanisms:amqplain/3],[],[]}],[]},{emqx_topic_manager_publisher,connect,1,[{file,"emqx_topic_manager_publisher.erl"},{line,22}]},{ecpool_worker,connect_internal,1,[{file,"ecpool_worker.erl"},{line,252}]},{ecpool_worker,init,1,[{file,"ecpool_worker.erl"},{line,125}]},{gen_server,init_it,2,[{file,"gen_server.erl"},{line,417}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,385}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,226}]}]}}}}}}}}},[{emqx_topic_manager_app,start,2,[{file,"emqx_topic_manager_app.erl"},{line,31}]},{application_master,start_it_old,4,[{file,"application_master.erl"},{line,277}]}]}}}}
2021-04-19 12:04:47.800 [error] [Plugins] Load plugin emqx_topic_manager failed, cannot start plugin emqx_topic_manager for {bad_return,{{emqx_topic_manager_app,start,[normal,[]]},{'EXIT',{{badmatch,{error,{shutdown,{failed_to_start_child,emqx_topic_manager_publisher,{shutdown,{failed_to_start_child,worker_sup,{shutdown,{failed_to_start_child,{worker,1},{undef,[{amqp_connection,start,[{amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"localhost",undefined,0,0,10,infinity,none,[fun amqp_auth_mechanisms:plain/3,fun amqp_auth_mechanisms:amqplain/3],[],[]}],[]},{emqx_topic_manager_publisher,connect,1,[{file,"emqx_topic_manager_publisher.erl"},{line,22}]},{ecpool_worker,connect_internal,1,[{file,"ecpool_worker.erl"},{line,252}]},{ecpool_worker,init,1,[{file,"ecpool_worker.erl"},{line,125}]},{gen_server,init_it,2,[{file,"gen_server.erl"},{line,417}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,385}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,226}]}]}}}}}}}}},[{emqx_topic_manager_app,start,2,[{file,"emqx_topic_manager_app.erl"},{line,31}]},{application_master,start_it_old,4,[{file,"application_master.erl"},{line,277}]}]}}}}

```

and `amqp_client` is missing in `_build/emqx/rel/emqx/lib` unless manually added to `emqx/rebar.config` and `emqx/rebar.config.erl`

**How to reproduce it (as minimally and precisely as possible)**:

add a dependency to a plugin thats not already in emqx dependencies

**Anything else we need to know?**:

looks like plugins `app.src` is not taken into account when building a release. 
```
{application, emqx_topic_manager,
 [{description, "EMQ X Topic manager plugin"},
  {vsn, "git"},
  {modules, []},
  {registered, [emqx_topic_manager_sup]},
  {applications, [kernel,stdlib,eredis,eredis_cluster,ecpool,foo]},
  {mod, {emqx_topic_manager_app,[]}},
  {env, []},
```
even though i added a non-existent app `foo` build still passes

**Comment by zmstone** [comment]
Hi @sh3d2 
The release of extra apps is controlled by `EMQX_EXTRA_PLUGINS` environment variable.

**Comment by zmstone** [comment]
sorry. you mean deps of extra apps.

**Comment by sh3d2** [comment]
> sorry. you mean deps of extra apps.

thats exactly what i mean ;)

**Comment by zmstone** [comment]
have you tried to putting amqp client to this list: 
`{applications, [kernel,stdlib,eredis,eredis_cluster,ecpool,foo]},`

**Comment by sh3d2** [comment]
> have you tried to putting amqp client to this list:
> `{applications, [kernel,stdlib,eredis,eredis_cluster,ecpool,foo]},`

yup, no joy. looks like that file is ignored during release

**Comment by zmstone** [comment]
is `emqx_topic_manager ` pulled by rebar3 to `_build/default/lib`
or do you have a local clone in lib-extra ?

**Comment by sh3d2** [comment]
```
➜  lib-extra git:(master) ✗ ll *topic*
lrwxr-xr-x  1 user  staff    40B Apr 13 14:57 emqx-topic-manager -> ../_build/default/lib/emqx_topic_manager


```

**Comment by zmstone** [comment]
there is perhaps something wrong with rebar3 app discovery with this, I'll try to investigate.
could you try not to use symlink?

**Comment by sh3d2** [comment]
same thing when `lib-extra/emqx-plugin-dir` is a local copy

**Comment by zmstone** [comment]
> same thing when `lib-extra/emqx-plugin-dir` is a local copy

Sorry. I mean let rebar3 download it, do not symlink it from lib-extra to `../_build/default/lib/emqx_topic_manager`

**Comment by zmstone** [comment]
`rm -rf _build/default/lib/emqx_topic_manager` so it will force a re-download and re-discover.
nontheless, amqp_client should be added to applications list

**Comment by sh3d2** [comment]
started off clean. `_build` removed, no symlinks alltogether. still no `amqp_client`

**Comment by sh3d2** [comment]
@zmstone removed everything, started from scratch and... it worked 😕  
so yeah... _im a moron it seems_
anyway thanks for the discussion.

**Comment by zmstone** [comment]
@sh3d2 my guess is rebar3 was bing lazy, and did not try to re-discover the dependencies.
not entirely sure if the symlink matters.
I'll try to have a closer look whn time allows.

**Comment by sh3d2** [comment]
@zmstone thats my guess too. it worked after i push-added `amqp_client` to applications in the plugin repository. local (symlinked or not) change seemed not to make any difference. after rebar fetched the plugin with proper applications in the `app.src` everything worked ok
