### ISSUE TITLE
Dockerized EMQ X should use manual gen_rpc and Erlang distribution port 

### ISSUE THREAD

**Issue by k32** [emqx/emqx#4647]
**Environment**:

- EMQ X version (e.g. `emqx_ctl status`): 
- Hardware configuration (e.g. `lscpu`):
- OS (e.g. `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Erlang/OTP version (in case you build emqx from source code): 
- Others:

**What happened and what you expected to happen**:
EMQ X uses `static` port allocation strategy by default for `gen_rpc` and erlang distribution. This strategy recognizes node names like `emqx1`, `emqx2`, ... and uses the node number as a port offset. In Docker the node name can be random, but at the same time there are never multiple instances of emqx process per container. `manual` port allocation strategy should be used as the default in docker.

**How to reproduce it (as minimally and precisely as possible)**:
Start EMQ X docker container without specifying `EMQX_NODE_NAME` environment variable. Sometimes the node refuses to start.

**Anything else we need to know?**:

**Comment by zmstone** [comment]
see also: https://github.com/emqx/emqx/pull/4670
