### ISSUE TITLE
Can split some fields in topic with rule engine？

### ISSUE THREAD

**Issue by Bevr2020** [emqx/emqx#4655]
假如我往主题aa/bb/cc中发送消息，我想把bb的截取成指定key名称的消息格式，如{"t2":"bb"}，发送到其他指定主题topic，请问目前支持这样的功能？

**Comment by mnkhbmb** [comment]
I need to split some fields in topic with rule enigne too?

Any help :)

**Comment by HJianBo** [comment]
Sure, e.g:
```
SELECT nth(2, tokens(topic,'/')) as second_attr
FROM *
```

**Comment by mnkhbmb** [comment]
Thanks for replying
I'm trying to query (SELECT   clientid,    topic,    username,    payload FROM   "stat/#" WHERE topic=~'#/#/RESULT") or 
(WHERE topic like '%RESULT' ).  It doesn't seem to work. 
what should i do? 
What if I get a topic that only ends with RESULT?
