### ISSUE TITLE
Message order not preserved across the cluster

### ISSUE THREAD

**Issue by matthewGEA** [emqx/emqx#4658]
I see that [#3046](https://github.com/emqx/emqx/issues/3046) was addressed a while ago, but maybe that handles a slower packet use-case?

Keeping packet order across the cluster is a critical requirement for our application.

**Environment**:
Docker container EMQX version 4.2.11

**What happened and what you expected to happen**:
- Given two clustered brokers
- Given a client is subscribed to a topic with multiple subtopics on one of the brokers
- When a 2nd client publishes a series of data to that topic on the opposite broker in the cluster
- Then the subscribed client occasionally receive messages out of order, per the order the different topics were published

**How to reproduce it (as minimally and precisely as possible)**:
Create a cluster with 2 nodes
Connect 20-40 clients to one of the nodes
Have a client publish a sequence number in the payload.  Each client shall make use of a sequence number that increments by 1 with any message published by that client.  The client's global sequence number should be shared across at least two sub-topics
For example client1 publishes the following sequence:
    allclients/client1/topic/subtopic1 where payload = 0
    allclients/client1/topic/subtopic1 where payload = 1
    allclients/client1/topic/subtopic1 where payload = 2
    allclients/client1/topic/_**subtopic2**_ where payload = 3
    allclients/client1/topic/subtopic1 where payload = 4
Publish messages with QOS 0 at a rate of 1 message / 50ms
Have the other 20-40 clients publishing simultaneously to increase load on the broker
Connect a monitoring client to the opposite node in the cluster, have this client subscribed to the allclients/# to receive all the subtopics
Note that at a rate of about 10 times per minute, two packets from a client are swapped (for example, a packet with sequence# 10 arrives at the monitoring client right before the packet with sequence# 9)

**Anything else we need to know?**:
Packets always arrive correctly when the monitoring client is connected to the same node of the cluster where all publishing clients are connected.
Packets arrive correctly when the monitoring client is connected to a remote broker where the local broker (directly connected to the publishing clients) is bridged (publishing) to the remote broker using the bridge plugin.

**Comment by tigercl** [comment]
@matthewGEA Thanks for your feedback. Actually, the behavior of EMQ X should be a little different from what you expected. EMQ X can guarantee the order of messages under the same topic, but it cannot guarantee the order of messages between different topics.

**Comment by terry-xiaoyu** [comment]
Set `rpc.tcp_client_num = 1` if you want keep a strict message order between nodes.

**Comment by zmstone** [comment]
We should set default to 1?

**Comment by ertanden** [comment]
Could you please clarify the ordering guarantees? Regardless of clustering, I think the order needs to be guaranteed in case of;

- QoS0, 1 publisher, 1 topic, 1 subscriber

Do we still need `rpc.tcp_client_num = 1` configuration? Wouldn't that affect the performance of inter-cluster communication?
