### ISSUE TITLE
EMQX Broker version 4.2.11 Windows Download file listed as 4.2.1.zip

### ISSUE THREAD

**Issue by matthewGEA** [emqx/emqx#4663]
![image](https://user-images.githubusercontent.com/46966648/115905646-6124fa00-a434-11eb-9264-77f2e813b5e5.png)

AND
From this webpage:
https://www.emqx.io/downloads/broker/v4.2.11/
![image](https://user-images.githubusercontent.com/46966648/115905608-52d6de00-a434-11eb-956b-d107307fad1a.png)

**Comment by Rory-Z** [comment]
Hi, @matthewGEA Thank you for your feedback, we will fix this issue later

**Comment by matthewGEA** [comment]
This never was fixed... still present on:

Version 4.2.12 May 7, 2021 https://github.com/emqx/emqx/releases/download/v4.2.12/emqx-windows-4.2.1.zip
Version 4.2.13 Jun 7, 2021 https://github.com/emqx/emqx/releases/download/v4.2.13/emqx-windows-4.2.1.zip
Version 4.2.14 Aug 2, 2021 https://github.com/emqx/emqx/releases/download/v4.2.14/emqx-windows-4.2.1.zip

**Comment by zmstone** [comment]
@matthewGEA oops.
Sorry this was overlooked.
4.2 community edition has gone out of maintenance window.
I’m afraid we will not go back to fix the windows package name.
