### ISSUE TITLE
emqx_auth_username plugin is missed from /emqx/lib  

### ISSUE THREAD

**Issue by cocoaway** [emqx/emqx#4668]
**Environment**:

- EMQ X version (e.g. `emqx_ctl status`): 4.3-rc.3-41168065
- Hardware configuration (e.g. `lscpu`): Virtual Machine 
- OS (e.g. `cat /etc/os-release`):Alpine Linux v3.13
- Kernel (e.g. `uname -a`): Linux alp-va 4.19.118-0-vanilla #1-Alpine SMP Thu Apr 23 11:16:44 UTC 2020 x86_64 Linux
- Erlang/OTP version (in case you build emqx from source code):  erlang-23.1.5-r0
- Others:

**What happened and what you expected to happen**:
emqx_auth_username  is not listed in dashboard plugin list.
emqx_auth_username  is not present in /emqx/lib dir

It was expected to find emqx_auth_username-4.3.0 in /emqx/lib
 

**How to reproduce it (as minimally and precisely as possible)**:
`./bin/emqx_ctl plugins load emqx_auth_username`
> `./bin/emqx_ctl: not found`

**Anything else we need to know?**:

**Comment by tigercl** [comment]
@cocoaway Sorry to trouble you. Starting from 4.3, we have removed the `emqx_auth_clientid` and `emqx_auth_username` plugins. They have been replaced by `emqx_auth_mnesia`.

**Comment by cocoaway** [comment]
@tigercl I'm tring to understand the new plugin.

I've modified the `emqx_auth_mnesia` conf in this way : 

```
## Password hash.
##
## Value: plain | md5 | sha | sha256 | sha512
#auth.mnesia.password_hash = sha256
auth.mnesia.password_hash = plain

##--------------------------------------------------------------------
## Username Authentication
##--------------------------------------------------------------------

## Examples:
##auth.user.1.username = admin
##auth.user.1.password = public
##auth.user.2.username = feng@emqtt.io
##auth.user.2.password = public
##auth.user.3.username = name~!@#$%^&*()_+
##auth.user.3.password = pwsswd~!@#$%^&*()_+

auth.user.1.username = alfa
auth.user.1.password = beta

```

The plugin starts correctly.

I test the connection with mosquitto, I want to subscribe a topic

`mosquitto_sub -h 192.168.1.181  -u alfa -P beta   -t test/gamma`

but I receive 
`Connection error: Connection Refused: bad user name or password.`

If I try to insert the lines : 

```
## Auth as username or auth as clientid.
##
## Value: username | clientid
auth.mnesia.as = username
```
on the head of `emqx_auth_mnesia.conf` , when the plugin is started from dasboard is generated an error

`parse_config_file_failed`



**May I have an example how to write the conf file to be able to enable user alfa with password beta ?**

Thank you.

**Comment by zmstone** [comment]
Hi @cocoaway 
there was a bug in the config reader.
it has been fixed here: https://github.com/emqx/emqx/pull/4692
included in 4.3-rc.5 release

**Comment by zmstone** [comment]
this config is outdated in documentation.
will follow up with an update to the doc site.
```
## Auth as username or auth as clientid.
##
## Value: username | clientid
auth.mnesia.as = username
```

**Comment by cocoaway** [comment]
@zmstone 
Hi, the mnesia_auth plugin does not recognize authorized user from non authorized.

I've set the `emqx_auth_mnesia.conf` with :  
```
auth.user.1.username = alfa
auth.user.1.password = beta
```

then tested with mosquitto.

It is possible to connect and publish / subscribe as anonymous user.

`mosquitto_sub -h (emqx address) -t /test -d ` , in a console and the connection is accepted from the broker
```
Client (null) sending CONNECT
Client (null) received CONNACK (0)
Client (null) sending SUBSCRIBE (Mid: 1, Topic: /test, QoS: 0, Options: 0x00)
Client (null) received SUBACK
Subscribed (mid: 1): 0
```

Now I can publish all that I want to the emqx broker, even id I'm not using username and password !

**Comment by zmstone** [comment]
Hi @cocoaway I'll have a look soon.

**Comment by cocoaway** [comment]
Hi Zaiming,

Have you any news on authentication with Mnesia?

Thank you.


cocoaway
Il 6 mag 2021, 11:03 +0200, Zaiming (Stone) Shi ***@***.***>, ha scritto:

**Comment by k32** [comment]
Hi,

Could you run `bin/node_command` and attach the resulting archive?

> It is possible to connect and publish / subscribe as anonymous user.

Could you run the following command in the EMQ X installation directory: `grep -E 'allow_anonymous|acl_' etc/emqx.conf` and attach the results?

**Comment by cocoaway** [comment]
Hi,
`bin/node_command ` is not clear,as there is no node_command executable in /bin.

`grep -E 'allow_anonymous|acl_' etc/emqx.conf` returns

```
allow_anonymous = true
acl_nomatch = allow
acl_file = etc/acl.conf
enable_acl_cache = on
acl_cache_max_size = 32
acl_cache_ttl = 1m
acl_deny_action = ignore
zone.external.acl_deny_action = ignore
zone.internal.allow_anonymous = true
zone.internal.acl_deny_action = ignore
```

and here is probably my misunderstanding. If I activate an authentication plugin, are anonymous accesses not disabled by default?

**Comment by k32** [comment]
> bin/node_command is not clear,as there is no node_command executable in /bin.

Sorry, my mistake. I meant "`bin/node_dump` command"

> If I activate an authentication plugin, are anonymous accesses not disabled by default?

No, I think you need to explicitly disable anonymous access in the emqx.conf

**Comment by cocoaway** [comment]
@k32 sorry, but I can't find `bin/node_dump` .

This is emqx /bin dir content :

```
cuttlefish                                 emqx_ctl                                   no_dot_erlang.boot
cuttlefish-4.3-rc.5-4bdcdfb9               emqx_ctl-4.3-rc.5-4bdcdfb9                 nodetool
emqx                                       emqx_ctl.cmd                               nodetool-4.3-rc.5-4bdcdfb9
emqx-4.3-rc.5-4bdcdfb9                     install_upgrade.escript
emqx.cmd                                   install_upgrade.escript-4.3-rc.5-4bdcdfb9
```

**Comment by zmstone** [comment]
The script was added after rc.5
If you are building a fork, please rebase on v4.3.1

**Comment by rgaufman** [comment]
Just to understand, emqx_auth_username plugin was removed?
