### ISSUE TITLE
SQL Server 2014

### ISSUE THREAD

**Issue by AngeloBestetti** [emqx/emqx#467]
Will be nice if we have plugin for SQL Server 2014

**Comment by AngeloBestetti** [comment]
Hi Feng, any news about this Feature?

**Comment by sicode** [comment]
什么时候可以支持？

**Comment by AngeloBestetti** [comment]
We are already using 2016, I would like to have this MSSQL 2016 plugin, with that I can put the ACL table in "Memory Optimized" SQL Feature now.

**Comment by Gilbert-Wong** [comment]
@AngeloBestetti , Sorry for that we have no schedule to implement plugin for SQL Server on windows. However, ms have release linux edition of sql server , we are planning to implement this plugin for linux sql server in the future.

**Comment by tungshido** [comment]
> @AngeloBestetti , Sorry for that we have no schedule to implement plugin for SQL Server on windows. However, ms have release linux edition of sql server , we are planning to implement this plugin for linux sql server in the future.

Hi GilbertWong96, I saw on pricing file of EMQ has "Data persistence to MS SQL DB(plan)". So this is for Linux SQL server?

**Comment by gilbertwong96** [comment]
Sorry, I have left emqx organization and have no idea about the MS SQL DB solution for EMQ. But the odbc driver is integrated in Erlang/OTP, I suppose it is not difficult  to implement it by your self.

Gilbert Wong
