### ISSUE TITLE
共享订阅不起作用

### ISSUE THREAD

**Issue by hfhtsoft** [emqx/emqx#4674]
#### Environment

- OS:  Docker 
- Erlang/OTP:  R22/10.7.2.6
- EMQ:  4.2.10

#### Description
用MQTT.fx或者Pythonpaho.mqtt，订阅和发布信息到 $queue/at/test 中 QoS 1，无法接收到数据。Dashboard中监控队列，显示数据已经被丢弃。
使用普通topic名字则可以正常接收。
请问使用共享订阅是否需要对EMQX服务做一些相关的配置？
谢谢。

![1.PNG](https://i.loli.net/2021/04/26/x2qIZpyt5GRQz6w.png)

![2.PNG](https://i.loli.net/2021/04/26/Ga1eK7Xo9kvYdyh.png)

![3.PNG](https://i.loli.net/2021/04/26/ykdsKN2lRgtJV7u.png)

![4.PNG](https://i.loli.net/2021/04/26/ZGxTwsdSkezyhJO.png)

![5.PNG](https://i.loli.net/2021/04/26/euWCHBr8h3QMbJg.png)

**Comment by HJianBo** [comment]
mqtt.fx has incorrect support for shared subscriptions. You can try the [MQTTX](https://mqttx.app) client we provide.
