### ISSUE TITLE
Trying to reassign port the http port in docker

### ISSUE THREAD

**Issue by csinatsch** [emqx/emqx#4697]
Hello :) How can I reassign the http port from 8080 to a new port (say, 9090) because 8080 is needed for another service running on my server. I've tried remapping with the argument in my docker run command -p 9090:8080 or -e EMQX_LISTENER__API__MGMT=9090 but both seem to get ignored and 8080 is still being used by emqx.

Thank you!

**Comment by zmstone** [comment]
Hi @csinatsch which version are you running ?

**Comment by zmstone** [comment]
as far as I know, the management API listens on port 8081 by default not 8080
and the override variable is `EMQX_MANAGEMENT__LISTENER__HTTP` not `EMQX_LISTENER__API__MGMT`

**Comment by csinatsch** [comment]
Hi @zmstone I was running an outdated version that docker had pulled. The new version does run 8081. Thank you for the override variable also incase 8081 is also taken. Thank you again!
