### ISSUE TITLE
Response time of the use case of Paho Java

### ISSUE THREAD

**Issue by gtahubb** [emqx/emqx#4718]
**the dependency is org.eclipse.paho.client.mqttv3. If it is 1.2.0 and the previous version, the response time is around 50ms, and if it is a later version, it is 350ms.**:

**Comment by k32** [comment]
Hello,
I assume the latency changed after you updated paho plugin in your client application? https://mvnrepository.com/artifact/org.eclipse.paho/org.eclipse.paho.client.mqttv3

Did you change anything in the EMQ X installation?

**Comment by gtahubb** [comment]
> Hello,
> I assume the latency changed after you updated paho plugin in your client application? https://mvnrepository.com/artifact/org.eclipse.paho/org.eclipse.paho.client.mqttv3
> 
> Did you change anything in the EMQ X installation?
Download it and use it directly

**Comment by k32** [comment]
Could you please clarify the problem? Do I understand correctly that you updated the dependency of your java application, and it changed the latency.
Did you change version of EMQ X, or some configuration of the broker?

**Comment by qzhuyan** [comment]
If possible, could you send us the tcpdump file so that we can check if there are any differences in the MQTT message?
