### ISSUE TITLE
emqx_auth_mongo  failed to execute

### ISSUE THREAD

**Issue by shen-hj** [emqx/emqx#4758]
emqx_auth_mongo.conf:
auth.mongo.auth_query.collection = iot_mqtt_user
auth.mongo.auth_query.password_hash = plain
auth.mongo.auth_query.password_field = password
auth.mongo.auth_query.selector = username=%u
auth.mongo.super_query = off                                       
auth.mongo.super_query.collection = iot_mqtt_user                            
auth.mongo.super_query.super_field = is_superuser      
auth.mongo.super_query.selector = username=%u      

When I use Mongo Authentication, I report an error：

(5c97575e7fa0@10.0.33.2)1> 2021-05-08 03:43:05.835 [warning] <<"mqttjs_1e4fb416f3">>@10.0.33.1:57426 [Channel] Client mqttjs_1e4fb416f3 (Username: 'emqx') login failed for not_authorized
(5c97575e7fa0@10.0.33.2)1> 2021-05-08 03:43:16.713 [error] <<"mqttjs_1e4fb416f3">>@10.0.33.1:57668 [Hooks] Failed to execute {fun emqx_auth_mongo:check/3,[#{authquery => {authquery,<<"iot_mqtt_user">>,[<<"password">>],plain,[{<<"username">>,<<"%u">>}]},pool => emqx_auth_mongo,superquery => {superquery,<<"''">>,<<"is_superuser">>,[{<<"username">>,<<"%u">>}]}}]}: {{{<<"Can't pass authentification">>,[{mc_auth_logic,scram_sha_1_auth,5,[{file,"mc_auth_logic.erl"},{line,55}]},{mc_worker,auth_if_credentials,5,[{file,"mc_worker.erl"},{line,219}]},{mc_worker,init,1,[{file,"mc_worker.erl"},{line,54}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,249}]}]},{gen_server,call,[<0.7074.0>,{query,<<"iot_mqtt_user">>,false,false,true,false,false,0,-1,#{<<"username">> => <<"admin">>},#{}},infinity]}},[{gen_server,call,3,[{file,"gen_server.erl"},{line,223}]},{mc_connection_man,request_worker,2,[{file,"mc_connection_man.erl"},{line,42}]},{mc_connection_man,read_one,2,[{file,"mc_connection_man.erl"},{line,33}]},{poolboy,transaction,3,[{file,"poolboy.erl"},{line,76}]},{emqx_auth_mongo,check,3,[{file,"emqx_auth_mongo.erl"},{line,47}]},{emqx_hooks,safe_execute,2,[{file,"emqx_hooks.erl"},{line,164}]},{emqx_hooks,do_run_fold,3,[{file,"emqx_hooks.erl"},{line,143}]},{emqx_access_control,authenticate,1,[{file,"emqx_access_control.erl"},{line,77}]}]}
(5c97575e7fa0@10.0.33.2)1> 2021-05-08 03:43:16.714 [warning] <<"mqttjs_1e4fb416f3">>@10.0.33.1:57668 [Channel] Client mqttjs_1e4fb416f3 (Username: 'admin') login failed for not_authorized
(5c97575e7fa0@10.0.33.2)1> 2021-05-08 03:43:55.244 [error] ** Generic server <0.7072.0> terminating 
** Last message in was {'EXIT',<0.30270.0>,
                           {<<"Can't pass authentification">>,
                            [{mc_auth_logic,scram_sha_1_auth,5,
                                 [{file,"mc_auth_logic.erl"},{line,55}]},
                             {mc_worker,auth_if_credentials,5,
                                 [{file,"mc_worker.erl"},{line,219}]},
                             {mc_worker,init,1,
                                 [{file,"mc_worker.erl"},{line,54}]},
                             {proc_lib,init_p_do_apply,3,
                                 [{file,"proc_lib.erl"},{line,249}]}]}}
** When Server state == {state,<0.7073.0>,
                               [<0.30270.0>],
                               {[],[]},
                               #Ref<0.4252332622.1775632386.250825>,1,0,0,
                               lifo}
** Reason for termination ==
** {{badmatch,{error,eaddrinuse}},
    [{poolboy,new_worker,1,[{file,"poolboy.erl"},{line,275}]},
     {poolboy,handle_info,2,[{file,"poolboy.erl"},{line,249}]},
     {gen_server,try_dispatch,4,[{file,"gen_server.erl"},{line,637}]},
     {gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,711}]},
     {proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,249}]}]}

(5c97575e7fa0@10.0.33.2)1> 2021-05-08 03:43:55.246 [error] ** Generic server <0.1998.0> terminating 
** Last message in was {'EXIT',<0.30271.0>,
                           {<<"Can't pass authentification">>,
                            [{mc_auth_logic,scram_sha_1_auth,5,
                                 [{file,"mc_auth_logic.erl"},{line,55}]},
                             {mc_worker,auth_if_credentials,5,
                                 [{file,"mc_worker.erl"},{line,219}]},
                             {mc_worker,init,1,
                                 [{file,"mc_worker.erl"},{line,54}]},
                             {proc_lib,init_p_do_apply,3,
                                 [{file,"proc_lib.erl"},{line,249}]}]}}
** When Server state == {state,<0.1999.0>,
                               [<0.30271.0>],
                               {[],[]},
                               #Ref<0.4252332622.1775632388.244212>,1,0,0,
                               lifo}
** Reason for termination ==
** {{badmatch,{error,eaddrinuse}},
    [{poolboy,new_worker,1,[{file,"poolboy.erl"},{line,275}]},
     {poolboy,handle_info,2,[{file,"poolboy.erl"},{line,249}]},
     {gen_server,try_dispatch,4,[{file,"gen_server.erl"},{line,637}]},
     {gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,711}]},
     {proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,249}]}]}

**Comment by terry-xiaoyu** [comment]
`not_authorized` means that your mongo db is connected but the authentication procedure failed. This maybe because the mongdb's password or username is not correct, or you've set another auth_source db rather than `mqtt`, if please check the configuration for `backend.mongo.pool1.auth_source`.
