### ISSUE TITLE
Node 'emqx@10.2.11.111' not responding to pings.

### ISSUE THREAD

**Issue by 2605373904** [emqx/emqx#4762]
**Environment**:

- EMQ X version: 
        emqx-centos7-v4.1.0.x86_64.rpm

**What happened and what you expected to happen**:
        emqx_ctl emqx

**Comment by k32** [comment]
Is EMQ X service running while you're using the command?
Can you show 
1) EMQ X service logs
2) Output of `ps aux | grep -E 'erl|emq'`
3) `systemctl status emqx`
