### ISSUE TITLE
"[warning] ehttpc: Received gun_down with closed" after upgrading to emqx >= v4.2.11 

### ISSUE THREAD

**Issue by dsilletti** [emqx/emqx#4766]
- EMQ X version: 4.2.11, 4.2.12, 4.3.0 official docker containers
- OS: Docker version 20.10.6, build 370c289 on Ubuntu 20.04.2 LTS (Focal Fossa)
- Kernel Linux 5.4.0-72-generic #80-Ubuntu SMP Mon Apr 12 17:35:00 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

upgrading to to emqx >= v4.2.11  I get continuosly this warning: [warning] ehttpc: Received gun_down with closed.
v4.2.10 and previous releases do not have this issue.

EMQX config:

allow_anonymous=false
listener.ssl.external=
listener.ssl.external.acceptors=32
listener.ssl.external.max_connections=102400
listener.tcp.external=0.0.0.0:1883
listener.tcp.external.acceptors=64
listener.tcp.external.max_connections=1024000
listener.tcp.internal=0.0.0.0:11883
listener.wss.external=
listener.wss.external.acceptors=16
listener.wss.external.max_connections=102400
listener.ws.external=0.0.0.0:8080
listener.ws.external.acceptors=16
listener.ws.external.max_connections=102400
mqtt.max_packet_size=1KB
node.max_ets_tables=2097152
node.max_ports=1048576
node.process_limit=2097152
acl_deny_action=disconnect
acl_file=etc/acl.conf
acl_nomatch=deny
dashboard.default_user.login=admin
dashboard.default_user.password=***secret***
listener.tcp.external.proxy_protocol=on
mqtt.max_clientid_len=256
mqtt.max_qos_allowed=0
mqtt.retain_available=false
zone.external.enable_acl=on
zone.external.rate_limit.conn_bytes_in=512KB,10s
zone.external.rate_limit.conn_messages_in=128,10s
EMQX_LOADED_PLUGINS=emqx_recon emqx_retainer emqx_management emqx_dashboard emqx_auth_http

**Comment by k32** [comment]
Could you attach the full EMQ X logs containing the error?

**Comment by dsilletti** [comment]
`Starting mqtt-broker ... done
Attaching to mqtt-broker
mqtt-broker        | EMQX_LOADED_PLUGINS=emqx_recon emqx_retainer emqx_management emqx_dashboard emqx_auth_http
mqtt-broker        | acl_deny_action = "disconnect"
mqtt-broker        | acl_file = "etc/acl.conf"
mqtt-broker        | acl_nomatch = "deny"
mqtt-broker        | allow_anonymous = "false"
mqtt-broker        | listener.ssl.external = []
mqtt-broker        | listener.ssl.external.acceptors = "32"
mqtt-broker        | listener.ssl.external.max_connections = "102400"
mqtt-broker        | listener.tcp.external = "0.0.0.0:1883"
mqtt-broker        | listener.tcp.external.acceptors = "64"
mqtt-broker        | listener.tcp.external.max_connections = "1024000"
mqtt-broker        | listener.tcp.external.proxy_protocol = "on"
mqtt-broker        | listener.tcp.internal = "0.0.0.0:11883"
mqtt-broker        | listener.ws.external = "0.0.0.0:8080"
mqtt-broker        | listener.ws.external.acceptors = "16"
mqtt-broker        | listener.ws.external.max_connections = "102400"
mqtt-broker        | listener.ws.external.proxy_address_header = "X-Forwarded-For"
mqtt-broker        | listener.ws.external.proxy_port_header = "X-Forwarded-Port"
mqtt-broker        | listener.wss.external = []
mqtt-broker        | listener.wss.external.acceptors = "16"
mqtt-broker        | listener.wss.external.max_connections = "102400"
mqtt-broker        | log.to = "console"
mqtt-broker        | mqtt.max_clientid_len = "256"
mqtt-broker        | mqtt.max_packet_size = "1KB"
mqtt-broker        | mqtt.max_qos_allowed = "0"
mqtt-broker        | mqtt.retain_available = "false"
mqtt-broker        | node.max_ets_tables = "2097152"
mqtt-broker        | node.max_ports = "1048576"
mqtt-broker        | node.name = "emqx@172.18.0.12"
mqtt-broker        | node.process_limit = "2097152"
mqtt-broker        | rpc.port_discovery = "manual"
mqtt-broker        | zone.external.enable_acl = "on"
mqtt-broker        | zone.external.rate_limit.conn_bytes_in = "512KB,10s"
mqtt-broker        | zone.external.rate_limit.conn_messages_in = "128,10s"
mqtt-broker        | Exec: /opt/emqx/erts-11.1.8/bin/erlexec -noshell -noinput +Bd -boot /opt/emqx/releases/4.3.0/start -mode embedded -boot_var ERTS_LIB_DIR /opt/emqx/erts-11.1.8/../lib -mnesia dir "/opt/emqx/data/mnesia/emqx@172.18.0.12" -config /opt/emqx/data/configs/app.2021.05.08.15.13.25.config -args_file /opt/emqx/data/configs/vm.2021.05.08.15.13.25.args -vm_args /opt/emqx/data/configs/vm.2021.05.08.15.13.25.args -start_epmd false -epmd_module ekka_epmd -proto_dist ekka -- foreground
mqtt-broker        | Root: /opt/emqx
mqtt-broker        | Starting emqx on node emqx@172.18.0.12
mqtt-broker        | Start http:management listener on 8081 successfully.
mqtt-broker        | Start http:dashboard listener on 18083 successfully.
mqtt-broker        | Start mqtt:tcp:internal listener on 0.0.0.0:11883 successfully.
mqtt-broker        | Start mqtt:tcp:external listener on 0.0.0.0:1883 successfully.
mqtt-broker        | Start mqtt:ws:external listener on 0.0.0.0:8080 successfully.
mqtt-broker        | EMQ X Broker 4.3.0 is running now!
mqtt-broker        | 2021-05-08T15:13:33.909235+00:00 [warning] ehttpc: Received gun_down with closed
mqtt-broker        | 2021-05-08T15:13:38.927046+00:00 [warning] ehttpc: Received gun_down with closed
mqtt-broker        | 2021-05-08T15:13:43.950885+00:00 [warning] ehttpc: Received gun_down with closed
mqtt-broker        | 2021-05-08T15:13:46.972854+00:00 [warning] ehttpc: Received gun_down with closed
mqtt-broker        | 2021-05-08T15:13:47.974027+00:00 [warning] ehttpc: Received gun_down with closed
mqtt-broker        | 2021-05-08T15:13:47.974253+00:00 [warning] ehttpc: Received gun_down with closed
mqtt-broker        | 2021-05-08T15:13:47.974352+00:00 [warning] ehttpc: Received gun_down with closed
mqtt-broker        | 2021-05-08T15:13:48.975426+00:00 [warning] ehttpc: Received gun_down with closed
mqtt-broker        | 2021-05-08T15:13:51.996849+00:00 [warning] ehttpc: Received gun_down with closed
mqtt-broker        | 2021-05-08T15:13:52.006145+00:00 [warning] ehttpc: Received gun_down with closed
mqtt-broker        | 2021-05-08T15:13:52.006366+00:00 [warning] ehttpc: Received gun_down with closed
mqtt-broker        | 2021-05-08T15:13:52.006393+00:00 [warning] ehttpc: Received gun_down with closed
mqtt-broker        | 2021-05-08T15:13:53.999452+00:00 [warning] ehttpc: Received gun_down with closed
mqtt-broker        | 2021-05-08T15:13:56.019703+00:00 [warning] ehttpc: Received gun_down with closed
mqtt-broker        | 2021-05-08T15:13:57.020854+00:00 [warning] ehttpc: Received gun_down with closed
mqtt-broker        | 2021-05-08T15:13:57.039081+00:00 [warning] ehttpc: Received gun_down with closed
mqtt-broker        | 2021-05-08T15:13:57.039091+00:00 [warning] ehttpc: Received gun_down with closed
mqtt-broker        | 2021-05-08T15:13:58.022053+00:00 [warning] ehttpc: Received gun_down with closed
mqtt-broker        | 2021-05-08T15:14:01.052896+00:00 [warning] ehttpc: Received gun_down with closed
mqtt-broker        | 2021-05-08T15:14:01.052910+00:00 [warning] ehttpc: Received gun_down with closed
mqtt-broker        | 2021-05-08T15:14:02.053994+00:00 [warning] ehttpc: Received gun_down with closed
mqtt-broker        | 2021-05-08T15:14:02.054227+00:00 [warning] ehttpc: Received gun_down with closed
mqtt-broker        | 2021-05-08T15:14:02.062924+00:00 [warning] ehttpc: Received gun_down with closed
mqtt-broker        | 2021-05-08T15:14:06.086126+00:00 [warning] ehttpc: Received gun_down with closed
mqtt-broker        | 2021-05-08T15:14:06.086279+00:00 [warning] ehttpc: Received gun_down with closed
mqtt-broker        | 2021-05-08T15:14:07.087009+00:00 [warning] ehttpc: Received gun_down with closed
mqtt-broker        | 2021-05-08T15:14:07.087208+00:00 [warning] ehttpc: Received gun_down with closed
mqtt-broker        | 2021-05-08T15:14:07.087293+00:00 [warning] ehttpc: Received gun_down with closed`

**Comment by k32** [comment]
Thanks for the logs. 

Could you clarify:
> upgrading to to emqx >= v4.2.11
Does it mean you use `emqx_ctl data import/export` feature?

Do you have any webhooks configured?

**Comment by dsilletti** [comment]
You are welcome.

by upgrading I mean I switched from EMQX official docker container 4.2.10 to the EMQX  official docker container v4.2.11, v4.2.12 or v4.3.30 and I noticed this warning.
If I switch back to v4.2.10 or previuos releases this warning disappear.
I have nothing special configured, I am using the http auth plugin to authenticate the mqtt clients and I am using an ACL file.
The EMQX broker is working with no apparent issues except this continuos warning.

**Comment by gbrehmer** [comment]
We have the same warnings and setup (emq auth http)

**Comment by tigercl** [comment]
@dsilletti The original intention of this log is to print the reason for the disconnection of the HTTP long connection. Your log seems to be that the peer, that is, the HTTP Server, actively closed the connection. Can I understand the specific reason? Does it not support long connections?

**Comment by gbrehmer** [comment]
Ah sorry my warning is slightly different:
`2021-05-11T08:19:03.830545+00:00 [warning] ehttpc: Received gun_down with normal`
what means `normal` instead of `closed`?

> This is probably a setting you need to adjust on the AuthN server side. In the test setup it should be ok to raise idle connection timeout of the server or the front proxy.
Because connections are kept open forever? There is no idleConnectionTimeout on client side?

**Comment by k32** [comment]
> Because connections are kept open forever? There is no idleConnectionTimeout on client side?

Yes, ehttpc uses a connection pool.

**Comment by dsilletti** [comment]
Hi, ok I increased the HTTP Server keepalive timeout and the warnings are appearing less often, according to the timeout.
What is the suggested http keepalive timeout to use with the http auth plugin?

**Comment by dsilletti** [comment]
Hi @tigercl, so in EMQ X v4.2.10 and previous releases the behavior was the same but this warning was not implemented?

**Comment by k32** [comment]
Yes, this is correct. Later versions of brocker won't print the warning if the reason is not abnormal.
