### ISSUE TITLE
EMQX_LOADED_PLUGINS fails with 4.3 in kubernetes

### ISSUE THREAD

**Issue by mloebl** [emqx/emqx#4769]
**Environment**:

- EMQ X version (e.g. `emqx_ctl status`):  4.3
- Hardware configuration (e.g. `lscpu`):  aarch64
- OS (e.g. `cat /etc/os-release`): Ubuntu 20.04.2 LTS
- Kernel (e.g. `uname -a`): 5.4.0-1034-raspi
- Erlang/OTP version (in case you build emqx from source code): 
- Others:

**What happened and what you expected to happen**:
Testing 4.3 with my existing 4.2 values.yml , I have the following set in the helm chart:
`EMQX_LOADED_PLUGINS: "emqx_bridge_mqtt,emqx_auth_ldap"`
and also tried:
`EMQX_LOADED_PLUGINS: "emqx_bridge_mqtt emqx_auth_ldap"`

When it starts up, get the following error, then the container stops:
`mv: can't remove '/opt/emqx/data/loaded_plugins': Resource busy`

**How to reproduce it (as minimally and precisely as possible)**:
Set a value for EMQX_LOADED_PLUGINS in the helm chart

**Anything else we need to know?**:

Running in k3s v1.20.6+k3s1

**Comment by zmstone** [comment]
seems to be this `mv`: https://github.com/emqx/emqx/blob/v4.3.0/deploy/docker/docker-entrypoint.sh#L100-L101
in commit aadd1ba11, we should have used `cat tmpfile > "$file"` instead.

@z8674558

**Comment by zmstone** [comment]
@mloebl thank you for reporting it.
as a workaround, please try to enable/disable plugins from configmap:
https://github.com/emqx/emqx/blob/v4.3.0/deploy/charts/emqx/values.yaml#L77-L84

**Comment by mloebl** [comment]
Looks like I need to update my yaml with the configmap settings, thank you!

**Comment by zmstone** [comment]
@mloebl were you using configmap?
as @z8674558 pointed out in an other thread. k8s configmap is made readonly by default.
so if you are using configmap, you may not be able to override loaded plugins from environment variables anyway.

nonetheless, the fix is necessary because same will happen to docker run file-volume mounts
