### ISSUE TITLE
Online Documentation v4.3.0 outdated

### ISSUE THREAD

**Issue by gbrehmer** [emqx/emqx#4770]
ref: https://docs.emqx.io/en/broker/v4.3/configuration/configuration.html

e.g. documentation missing for:
- rpc.port_discovery
- rpc.tcp_server_port
- rpc.tcp_client_port

contains still the old names

**Comment by gbrehmer** [comment]
and is https://github.com/emqx/emqx/blob/29bbc0802bc146143f4d373a38282e4b65c9eb37/etc/emqx.conf#L331-L332 still valid? because with docker image this property is by default set to `manual`
Probably this should be documented to (because previously I had to open the stateless Port based on node name in our inter-node-FW)

**Comment by zmstone** [comment]
thank you @gbrehmer will update the doc.

**Comment by zmstone** [comment]
related: https://github.com/emqx/emqx/pull/4772
