### ISSUE TITLE
Bearer Token support for Web socket upgrade request

### ISSUE THREAD

**Issue by outminder** [emqx/emqx#4776]
**Please describe your problem in detail, if necessary, you can upload the log file through the attachment**:
I found jwt plugin and http plugin, don't think these can be utilized to fetch the bearer token for validation. Does EMQx support Bearer token for webscoket HTTP upgrade request.?

**Comment by terry-xiaoyu** [comment]
No it can't. The JWT plugin is just for verifying the TOKEN from username or client-id field of MQTT CONNECT message.
