### ISSUE TITLE
Parse failed for frame_too_large Error Report when publish

### ISSUE THREAD

**Issue by beyondWater** [emqx/emqx#4783]
**Environment**:

- EMQ X version (v4.2.7): 
- OS (centos 7):
mqtt.max_packet_size = 2MB

**the error is fail to publish message to emqx broker, and error log report Parse failed for frame_too_large**:

[{emqx_frame,parse_remaining_len,5,[{file,"emqx_frame.erl"},{line,134}]},{emqx_connection,parse_incoming,3,[{file,"emqx_connection.erl"},{line,522}]},{emqx_connection,handle_msg,2,[{file,"emqx_connection.erl"},{line,515}]},{emqx_connection,process_msg,3,[{file,"emqx_con
nection.erl"},{line,293}]},{proc_lib,wake_up,3,[{file,"proc_lib.erl"},{line,259}]}]Frame data:<<48,201,181,140,1,0,20,100,101,118,105,99,101,47,98,105,110,95,114,101,115,112,111,110,115,101,49,99,49,48,34,66,105,110,77,101,115,115,97,103,101,34,53,123,115,52,34,116,105,109,101,34,115,53,34,100,101,118,105,100,34,115,51,34,101,120,116,34,115,55,34,99,1
11,110,116,101,120,116,34,115,51,34,114,97,119,34,125,111,48,123,115,49,55,34,50,48,50,49,48,53,49,49,49,52,48,49,52,52,49,57,52,34,115,49,51,34,73,79,84,49,49,48,48,49,65,45,48,50,49,34,109,55,123,115,49,53,34,105,111,116,95,116,111,116,97,108,95,99,111,117,110,116,34,115,55,34,50,51,49,48,52,55,57,34,115,49,54,34,105,111,116,95,112,105,101,99,101,95,111,102,102,115,101,116,34,117,48,115,49,53,34,105,111,116,95,98,117,115,105,110,101,115,115,95,105,100,34,115,51,54,34,56,98,100,53,55,52,99,48,45,97,54,54,52,45,52,99,48,48,45,98,100,100,98,45,55,51,100,101,55,97,101,50,55,54,50,49,34,115,49,53,34,105,111,116,95,109,115,103,95,99,97,116,97,108,111,103,34,115,49,50,34,98,105,110,45,114,101,115,112,111,110,115,101,34,115,57,34,99,111,109,109,97,110,100,73,100,34,115,49,55,34,50,48,50,49,48,53,49,49,49,52,48,49,48,53,49,49,51,34,115,55,34,99,111,109,109,97,110,100,34,115,50,57,34,105,111,116,95,97,99,107,95,114,101,99,118,95,102,105,108,101,95,102,114,111,109,95,100,101,118,105,99,101,34,115,49,48,34,105,111,116,95,109,115,103,95,105,100,34,115,49,50,34,100,56,52,48,98,50,101,54,53,53,56,53,34,125,109,55,123,115,55,34,99,111,110,116,101,120,116,34,115,51,54,34,56,98,100,53,55,52,99,48,45,97,54,54,52,45,52,99,48,48,45,98,100,100,98,45,55,51,100,101,55,97,101,50,55,54,50,49,34,115,49,52,34,102,105,108,101,85,112,108,111,97,100,84,121,112,101,34,115,54,34,83,121,115,116,101,109,34,115,52,34,112,97,116,104,34,115,51,55,34,47,98,97,99,107,117,112,47,73,79,84,49,49,48,48,49,65,45,48,50,49,95,66,97,99,107,117,112,95,50,48,50,49,48,53,49,49,34,115,52,34,116,97,115,107,34,101,115,50,49,34,99,111,109,109,97,110,100,66,97,99,107,117,112,83,121,115,116,101,109,73,100,34,115,49,55,34,50,48,50,49,48,53,49,49,49,52,48,48,48,52,51,48,52,34,115,56,34,102,105,108,101,78,97,109,101,34,115,50,57,34,73,79,84,49,49,48,48,49,65,45,48,50,49,95,66,97,99,107,117,112,95,50,48,50,49,48,53,49,49,34,115,54,34,109,111,100,117,108,101,34,101,125,97,53,49,50,49,53,57,123,105,57,57,59,105,53,48,59,105,53,50,59,105,51,52,59,105,54,57,59,105,49,50,48,59,105,57,57,59,105,49,48,52,59,105,57,59,105,49,49,57,59,105,49,51,48,59,105,49,50,57,59,105,57,50,59,105,51,55,59,105,49,52,54,59,105,49,51,56,59,105,51,54,59,105,57,49,59,105,49,48,57,59,105,51,48,59,105,49,49,52,59,105,56,49,59,105,55,50,59,105,50,49,50,59,105,50,50,49,59,105,49,57,48,59,105,56,52,59,105,49,52,59,105,50,48,52,59,105,49,49,56,59,105,49,55,51,59,105,53,51,59,105,49,49,56,59,105,49,48,48,59,105,49,53,53,59,105,49,54,56,59,105,50,52,57>>2021-05-11 14:33:47.189 [error] message=channel_closed driver=tcp socket="#Port<0.350972>" action=stopping
2021-05-11 14:33:47.190 [error] message=channel_closed driver=tcp socket="#Port<0.350466>" action=stopping
2021-05-11 16:00:15.763 [error] <<"08b9785d0f87891c">>@192.168.1.10:20306 [MQTT]

**Comment by terry-xiaoyu** [comment]
You can set the `zone.external.max_packet_size` to a larger value if you got `frame_too_large`.
