### ISSUE TITLE
Whether the same clientID subscribing to different topics will receive messages from other topics？

### ISSUE THREAD

**Issue by NumboZhang** [emqx/emqx#4785]
**Enviroment**
EMQ X Broker VERSION 4.2.8
Ubuntu 18.04

I have a Clientid named "Consumer" and  started two processes with the same ClientID to receive message from different topic, such as processA subcribe topicA and processB subcribe topicB. 
But I received unexpected message: processA receive message from topicB and processB also receive message from topicA. It looks like the message was received at random.
I use golang with github.com/eclipse/paho.mqtt.golang to connect EMQ, Is this a normal phenomenon? How does that work?

**Comment by terry-xiaoyu** [comment]
Actually you cannot start different connections to the broker using the same client-id. Or the behavior is undefined.

**Comment by NumboZhang** [comment]
> Actually you cannot start different connections to the broker using the same client-id. Or the behavior is undefined.
thanks for your reply!
yeah I change different clientID and solve the problem. I think there should be more obvious hints to avoid this problem.

now I use two connection to receive topicA message with different clientID, they all subcirbe  $share/groupA/topicA, but they all receive same message. Is there anything that needs extra configuration？

**Comment by terry-xiaoyu** [comment]
> now I use two connection to receive topicA message with different clientID,

I don't think this will happen. Try to disconnect the connections an reconnect them again, and subscribe the topic `$share/groupA/topicA` again. Make sure the `cleansession = true` when you sending CONNECT messages.

**Comment by NumboZhang** [comment]
> > now I use two connection to receive topicA message with different clientID,
> 
> I don't think this will happen. Try to disconnect the connections an reconnect them again, and subscribe the topic `$share/groupA/topicA` again. Make sure the `cleansession = true` when you sending CONNECT messages.


It works when I add cleansession to connection configuration!
thank you so much!
