### ISSUE TITLE
WS with Proxy Protocol capture wrong client-ip since emqx >= 4.2.11

### ISSUE THREAD

**Issue by minhpq331** [emqx/emqx#4815]
**Environment**:

- EMQ X version (e.g. `emqx_ctl status`): 4.2.11 on Docker alpine
- OS (e.g. `cat /etc/os-release`): Ubuntu 20.04.2 LTS (Focal Fossa)
- Kernel (e.g. `uname -a`): 5.4.0-67-generic #75-Ubuntu SMP Fri Feb 19 18:03:38 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

**What happened and what you expected to happen**:

- Use HAproxy with proxy protocol from wss 8084 to EMQ X ws 8083
- Connect to HAproxy 8084 successfully
- Client-IP in dashboard is **HAproxy IP** !!!

It happens since EMQ X 4.2.11. Work correctly (capture correct client-ip) with EMQ X 4.2.10 using the very same configs. Proxy 8883 to 1883 with the same SSL configs works correctly with both versions.

**How to reproduce it (as minimally and precisely as possible)**:

- HAProxy config:
```
frontend mqtt-ws-8084
        mode tcp
        maxconn 50000
        timeout client 2h
        option clitcpka
        option srvtcpka
        bind 0.0.0.0:8084 ssl crt /etc/haproxy/certs/example.com.pem no-sslv3
        default_backend mqtt-ws-8083

backend mqtt-ws-8083
        mode tcp
        balance roundrobin
        timeout server 2h
        timeout check  5s
        server mqtt-stg <emqx-ip>:8083 check-send-proxy send-proxy-v2 check inter 10s fall 2 rise 5
```
- EMQ X configs:
```
listener.ws.external.proxy_protocol=on
```

**Anything else we need to know?**:

- I'm using Let's Encrypt wildcard certificate to terminate SSL

**Comment by zmstone** [comment]
thank you for reporting this @minhpq331 
we'll fix it in the next bug fix release.
as a workaround before the fix, please configure haproxy to send certificate common name
by changing `send-proxy-v2` to `send-proxy-v2-ssl-cn`

@Rory-Z  FYI. 28810b62c should handle the case when `ssl` filed in missing.

**Comment by zmstone** [comment]
ah, can't set two milestones. this should be fixed in 4.3.2 and 4.2.13

**Comment by zmstone** [comment]
sorry, 4.2.12 is next release.

**Comment by minhpq331** [comment]
Thank you guys. Your workaround is working (y). Keep on your awesome works.
