### ISSUE TITLE
EMQX broker-4.3.1 can't start up on OS WinServer2016Standard X64

### ISSUE THREAD

**Issue by yuanmengxiaotu** [emqx/emqx#4818]
**Environment**:

- EMQ X version (e.g. `emqx_ctl status`): EMQX broker-4.3.1 for windows released on 15/5/2021
- Hardware configuration (e.g. `lscpu`):Intel Xeon E5640
- OS (e.g. `cat /etc/os-release`):WinServer2016Standard X64
- Kernel (e.g. `uname -a`):
- Erlang/OTP version (in case you build emqx from source code): 
- Others:

**What happened and what you expected to happen**:
EMQXbroker can startup successfully,but it didn't

**How to reproduce it (as minimally and precisely as possible)**:
Startup EMQX broker WinServer2016Standard X64

**Anything else we need to know?**:
EMQX broker-4.2.1 work normally on this environment

[log.zip](https://github.com/emqx/emqx/files/6490865/log.zip)

**Comment by zmstone** [comment]
@yuanmengxiaotu could you share your `emqx.conf` and generated config in `data/configs/app.<timestamp>.config` ?
NOTE: there are passwords and secrets in them, please make sure to obfuscate

**Comment by yuanmengxiaotu** [comment]
@zmstone  all the configuratios are default values, i didn't change anyone

**Comment by zmstone** [comment]
Hi @yuanmengxiaotu 
Sort I do not have a winserver 2016 for testing. 
The boot script generates a config file before starts up the service, could you please share the generated config file? It should be as data/configs/app.<timestamp>.config

**Comment by yuanmengxiaotu** [comment]
HI @zmstone
I have attached the config file Please check 
[Desktop.zip](https://github.com/emqx/emqx/files/6499131/Desktop.zip)

**Comment by yuanmengxiaotu** [comment]
@zmstone  
I try it again, both the version V4.2.12 and V4.3.0 work normally on the same environment, just the V4.3.1 can't start up

**Comment by zmstone** [comment]
@yuanmengxiaotu the config seem to be fine.
could you try to start it with command: `/path/to/install/bin/emqx console` and paste the output ?

**Comment by yuanmengxiaotu** [comment]
@zmstone 
The output is saved in the file emqx.log.1 wich attached as log.zip in the issue description  above

**Comment by zmstone** [comment]
@yuanmengxiaotu yes I noticed the log. the log hinted a boot argument missing.
the boot arguments are usually printed to elrang.log.1, but it's not found in your zip (which I am not sure why)
if you run `/path/to/install/bin/emqx console`, the printouts on console can help me locate the issue.
thank you for your patience

**Comment by yuanmengxiaotu** [comment]
@zmstone 
ok, i run it with command F:\emqx-windows-4.3.1\emqx\bin>emqx console ,the attachment is the output which printed on the console
![123](https://user-images.githubusercontent.com/84300815/118629154-e61aed80-b7ff-11eb-9a09-38d994cb1247.png)

**Comment by zmstone** [comment]
Hi @yuanmengxiaotu we have found the issue.
will fix it in 4.3.2
