### ISSUE TITLE
Failed to open file: /Users/wangyanan/Files/code/emqx/_build/emqx/rel/emqx/bin/cuttlefish

### ISSUE THREAD

**Issue by wangynustc** [emqx/emqx#4828]
When I build EMQ X from source code and do "./bin/emqx start"，I got an error with error measege: Failed to open file: /Users/wangyanan/Files/code/emqx/_build/emqx/rel/emqx/bin/cuttlefish

EMQ X start failed. How can I solve this issue and start EMQ successfully.

**Comment by wangynustc** [comment]
There is no file named cuttlefish in bin directory.

**Comment by k32** [comment]
Hello,
Which version of EMQ X are you building? Could you please share the git hash if you cloned the repo. 
Could you show the foll log of the build process?

**Comment by wangynustc** [comment]
> git remote -v                                                                   ff4ac624 [ff4ac624]
origin	git@github.com:emqx/emqx.git (fetch)
origin	git@github.com:emqx/emqx.git (push)

**Comment by wangynustc** [comment]
The steps I build EMQ X is :
1. git clone git@github.com:emqx/emqx.git
2. emqx
3. git checkout $(git describe --abbrev=0 --tags)
4. make
5. cd _build/emqx/rel/emqx
6. ./bin/emqx start
Then I got the error

**Comment by k32** [comment]
Could you run `make && echo "Success!"` and post the output?

**Comment by wangynustc** [comment]
> make && echo "Success"
===> Plugin er_coap_client does not export init/1. It will not be used.
===> Plugin er_coap_client does not export init/1. It will not be used.
===> Verifying dependencies...
===> Skipping cowboy (from {git,"https://github.com/emqx/cowboy",{tag,"2.7.1"}}) as an app of the same name has already been fetched
===> Skipping cowlib v2.8.0 as an app of the same name has already been fetched
===> Skipping esockd (from {git,"https://github.com/emqx/esockd",{tag,"5.7.4"}}) as an app of the same name has already been fetched
===> Skipping esockd (from {git,"https://github.com/emqx/esockd",{tag,"5.7.4"}}) as an app of the same name has already been fetched
===> Skipping getopt (from {git,"https://github.com/emqx/getopt.git",{tag,"v1.0.2"}}) as an app of the same name has already been fetched
===> Skipping gproc v0.8.0 as an app of the same name has already been fetched
===> Skipping gproc v0.8.0 as an app of the same name has already been fetched
===> Skipping gun (from {git,"https://github.com/emqx/gun",{tag,"1.3.4"}}) as an app of the same name has already been fetched
===> Skipping gun (from {git,"https://github.com/emqx/gun",{tag,"1.3.4"}}) as an app of the same name has already been fetched
===> Skipping jiffy (from {git,"https://github.com/emqx/jiffy",{branch,"1.0.5"}}) as an app of the same name has already been fetched
===> Skipping pbkdf2 (from {git,"https://github.com/emqx/erlang-pbkdf2.git",{tag,"2.0.3"}}) as an app of the same name has already been fetched
===> Skipping poolboy (from {git,"https://github.com/devinus/poolboy.git",{branch,"1.5.1"}}) as an app of the same name has already been fetched
===> Skipping poolboy (from {git,"https://github.com/comtihon/poolboy.git",
                   {branch,"master"}}) as an app of the same name has already been fetched
===> Skipping recon v2.5.1 as an app of the same name has already been fetched
===> Analyzing applications...
===> Compiling emqx
===> Compiling emqx_auth_http
===> Compiling emqx_auth_jwt
===> Compiling emqx_auth_ldap
===> Compiling emqx_auth_mnesia
===> Compiling emqx_auth_mongo
===> Compiling emqx_auth_mysql
===> Compiling emqx_auth_pgsql
===> Compiling emqx_auth_redis
===> Compiling emqx_bridge_mqtt
===> Compiling emqx_coap
===> Compiling emqx_exhook
===> Compiling emqx_exproto
===> Compiling emqx_lua_hook
===> Compiling emqx_lwm2m
===> Compiling emqx_management
===> Compiling emqx_plugin_libs
===> Compiling emqx_prometheus
===> Compiling emqx_psk_file
===> Compiling emqx_recon
===> Compiling emqx_retainer
===> Compiling emqx_rule_engine
===> Compiling emqx_sasl
===> Compiling emqx_sn
===> Compiling emqx_stomp
===> Compiling emqx_web_hook
===> Compiling emqx_dashboard
===> Compiling emqx_modules
===> Compiling emqx_telemetry
===> Plugin er_coap_client does not export init/1. It will not be used.
===> Verifying dependencies...
===> Skipping cowboy (from {git,"https://github.com/emqx/cowboy",{tag,"2.7.1"}}) as an app of the same name has already been fetched
===> Skipping cowlib v2.8.0 as an app of the same name has already been fetched
===> Skipping esockd (from {git,"https://github.com/emqx/esockd",{tag,"5.7.4"}}) as an app of the same name has already been fetched
===> Skipping esockd (from {git,"https://github.com/emqx/esockd",{tag,"5.7.4"}}) as an app of the same name has already been fetched
===> Skipping getopt (from {git,"https://github.com/emqx/getopt.git",{tag,"v1.0.2"}}) as an app of the same name has already been fetched
===> Skipping gproc v0.8.0 as an app of the same name has already been fetched
===> Skipping gproc v0.8.0 as an app of the same name has already been fetched
===> Skipping gun (from {git,"https://github.com/emqx/gun",{tag,"1.3.4"}}) as an app of the same name has already been fetched
===> Skipping gun (from {git,"https://github.com/emqx/gun",{tag,"1.3.4"}}) as an app of the same name has already been fetched
===> Skipping jiffy (from {git,"https://github.com/emqx/jiffy",{branch,"1.0.5"}}) as an app of the same name has already been fetched
===> Skipping pbkdf2 (from {git,"https://github.com/emqx/erlang-pbkdf2.git",{tag,"2.0.3"}}) as an app of the same name has already been fetched
===> Skipping poolboy (from {git,"https://github.com/devinus/poolboy.git",{branch,"1.5.1"}}) as an app of the same name has already been fetched
===> Skipping poolboy (from {git,"https://github.com/comtihon/poolboy.git",
                   {branch,"master"}}) as an app of the same name has already been fetched
===> Skipping recon v2.5.1 as an app of the same name has already been fetched
===> Analyzing applications...
===> Compiling emqx
===> Compiling emqx_auth_http
===> Compiling emqx_auth_jwt
===> Compiling emqx_auth_ldap
===> Compiling emqx_auth_mnesia
===> Compiling emqx_auth_mongo
===> Compiling emqx_auth_mysql
===> Compiling emqx_auth_pgsql
===> Compiling emqx_auth_redis
===> Compiling emqx_bridge_mqtt
===> Compiling emqx_coap
===> Compiling emqx_exhook
===> Compiling emqx_exproto
===> Compiling emqx_lua_hook
===> Compiling emqx_lwm2m
===> Compiling emqx_management
===> Compiling emqx_plugin_libs
===> Compiling emqx_prometheus
===> Compiling emqx_psk_file
===> Compiling emqx_recon
===> Compiling emqx_retainer
===> Compiling emqx_rule_engine
===> Compiling emqx_sasl
===> Compiling emqx_sn
===> Compiling emqx_stomp
===> Compiling emqx_web_hook
===> Compiling emqx_dashboard
===> Compiling emqx_modules
===> Compiling emqx_telemetry
===> [relup_helper] running gen_appups
===> Assembling release emqx-4.3.1...
===> Release successfully assembled: _build/emqx/rel/emqx
Success

**Comment by zmstone** [comment]
I suspect the build was half-done previously.
please try `make clean`
and then `make` again.

**Comment by k32** [comment]
Do you still get the error?

**Comment by wangynustc** [comment]
EMQ X started successfully, thanks a lot!!!
