### ISSUE TITLE
emqx broker-4.3.1 can't start on aws EC2

### ISSUE THREAD

**Issue by hehejiuhuizhe** [emqx/emqx#4829]
I use "sudo yum install emqx" to install emqx-4.3.1. When I use "sudo emqx start", it gives "/usr/lib/emqx/bin/cuttlefish: error while loading shared libraries: libtinfo.so.5: cannot open shared object file: No such file or directory". How can I resolve it?

**Comment by k32** [comment]
Do you use CentOS or Fedora? Which version?

**Comment by hehejiuhuizhe** [comment]
> Do you use CentOS or Fedora? Which version?

uname -a
Linux ip-xxx.us-west-2.compute.internal 4.14.231-173.361.amzn2.x86_64 #1 SMP Mon Apr 26 20:57:08 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

 cat /proc/version
Linux version 4.14.231-173.361.amzn2.x86_64 (mockbuild@ip-xxx) (gcc version 7.3.1 20180712 (Red Hat 7.3.1-12) (GCC)) #1 SMP Mon Apr 26 20:57:08 UTC 2021

I think it's like CentOS.

**Comment by k32** [comment]
I think it could be an Amazon Linux too. Could you run `yum repolist` as well?

**Comment by hehejiuhuizhe** [comment]
> I think it could be an Amazon Linux too. Could you run `yum repolist` as well?
![image](https://user-images.githubusercontent.com/29495241/118649487-22594880-b816-11eb-86e0-f581d49c45cc.png)

**Comment by k32** [comment]
I see, thanks. Looks like you're using Amazon Linux indeed. Not sure if our yum packages are compatible with it: https://docs.emqx.io/en/broker/v4.3/getting-started/install.html#installation

As a workaround you can either try to create an EC2 instance using one of the AMIs supported by EMQ X (from the list above), or build it from source. 

@zmstone What do you think about native Amazon Linux support?

**Comment by hehejiuhuizhe** [comment]
I remove the 4.3.1, and try 4.3.0, 4.2.0, failed to start. And emqx-4.1.0 start ok

**Comment by zmstone** [comment]
How was it installed ?
from yum command or rpm command?

**Comment by k32** [comment]
I can reproduce this error in amzonlinuz docker, but given that it's a different distro, it's not entirely surprising that it ships with different versions of system libraries.

**Comment by k32** [comment]
...And I can reproduce it on CentOS 8 too. Now it's a packaging bug.

**Comment by k32** [comment]
You're trying to install a CentOS package on Amazon Linux. As far as I know, these distros are not binary-compatible, they ship with different versions of libraries, so RPMs are not interchangeable. It is recommended to use CentOS if you're planning to use the binary package. 
Did you use the same EC2 instance for installing emqx-4.1.0?

**Comment by hehejiuhuizhe** [comment]
> How was it installed ?
> from yum command or rpm command?

from yum

**Comment by hehejiuhuizhe** [comment]
> You're trying to install a CentOS package on Amazon Linux. As far as I know, these distros are not binary-compatible, they ship with different versions of libraries, so RPMs are not interchangeable. It is recommended to use CentOS if you're planning to use the binary package.
> Did you use the same EC2 instance for installing emqx-4.1.0?

Yes, the same EC2 instance. I used to install emqx-4.0.4 on another EC2 instance and it works.

**Comment by hehejiuhuizhe** [comment]
I use yum because I want to use service to manage emqx and run it on boot. And it's convenient.

**Comment by hehejiuhuizhe** [comment]
![image](https://user-images.githubusercontent.com/29495241/118749593-6852f280-b890-11eb-9b88-7ef19e13eb70.png)
I find there is libtinfo.so.6 instead of libtinfo.so.5.

**Comment by hehejiuhuizhe** [comment]
Ok , it runs. I create a symbolic link: ln -s  /usr/lib64/libtinfo.so.6.0 /usr/lib/libtinfo.so.6

**Comment by hehejiuhuizhe** [comment]
Thanks for your help.
