### ISSUE TITLE
when the emqx_auth_redis is started, then default authentication not works when ACLs do not match

### ISSUE THREAD

**Issue by huanxue-shen** [emqx/emqx#4835]
sysdescr  : EMQ X Broker
version   : 4.1.0

the configration is:
acl_nomatch = allow
acl_file = etc/acl.conf

I can't sub/pub when the topic is not match the ACL rules  in redis

**Comment by DDDHuang** [comment]
Last Auth&ACL depend on `etc/acl.conf` . Check 'etc/acl.conf' file is consistent with your expectations.

**Comment by huanxue-shen** [comment]
acl.conf:
{allow, {user, "dashboard"}, subscribe, ["$SYS/#"]}.
{allow, {ipaddr, "127.0.0.1"}, pubsub, ["$SYS/#", "#"]}.
{deny, all, subscribe, ["$SYS/#", {eq, "#"}]}.
{allow, all}
such as topic "test" is not in redis, when  emqx_auth_redis is started, then i can't sub the topic , but when the plugin is closed, i can sub it.

**Comment by DDDHuang** [comment]
Check ACl info in your redis service. Reference [doc](https://docs.emqx.io/en/broker/v4.3/advanced/auth-redis.html#salting-rules-and-hash-methods) , part `auth query cmd`.

**Comment by huanxue-shen** [comment]
redis atuh ACL feature is disabled and i use emqx_atuh_jwt plugin instead  of it .
