### ISSUE TITLE
emqx_lwm2m config option lwm2m.publish_update_when not recognized. 

### ISSUE THREAD

**Issue by endianjoakim** [emqx/emqx#4838]
**Environment**:

- EMQ X version (e.g. `emqx_ctl status`): 4.3.1
- Hardware configuration (e.g. `lscpu`): -
- OS (e.g. `cat /etc/os-release`): -
- Kernel (e.g. `uname -a`): -
- Erlang/OTP version (in case you build emqx from source code): -
- Others: Running docker release `4.3.1` in Kubernetes

**What happened and what you expected to happen**:

I'm configuring the LwM2M plugin to always publish the `UPDATE` messages on MQTT. See https://github.com/emqx/emqx/pull/4201

In the emqx log I get this message:
```
$ emqx_ctl plugins load emqx_lwm2m

=ERROR REPORT==== 20-May-2021::13:36:23.465091 ===
You've tried to set lwm2m.publish_update_when, but there is no setting with that name.

```

Relevant part in `etc/plugins/emqx_lwm2m.conf`:
```
##--------------------------------------------------------------------
## LwM2M Gateway
##--------------------------------------------------------------------

lwm2m.publish_update_when = always
```

I've reproduced the config from this: https://github.com/emqx/emqx/commit/1be62b7cbbf9194588bd2875e5057a039cff7f76#diff-2a8749546e8ec1d13d655a0954259e922d334a2e34a2974329b1aec8c38fea18R51, but he plugin refuse to start because of the issue.

**Comment by tigercl** [comment]
@endianjoakim Sorry for late reply. In fact, the name of this configuration item should be `update_msg_publish_condition`. I'm sorry that the content of this PR misled you.

**Comment by endianjoakim** [comment]
Ah, thanks, verified that it works as expected. 😄 👍
