### ISSUE TITLE
Support OTP24

### ISSUE THREAD

**Issue by tjangdra** [emqx/emqx#4847]
#### Environment

- OS: Ubuntu 20.04.2 LTS
- Erlang/OTP: Erlang/OTP 24 [erts-12.0.1] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit]

- EMQ: X broker (master branch)

#### Description

Tried to compile EMQX broker and got the following error

==> Compiling apps/emqx_rule_engine/src/emqx_rule_runtime.erl failed
emqx_rule_runtime.erl:137:11: ambiguous call of overridden auto-imported BIF alias/1
 - use erlang:alias/1 or "-compile({no_auto_import,[alias/1]})." to resolve name clash
emqx_rule_runtime.erl:157:11: ambiguous call of overridden auto-imported BIF alias/1
 - use erlang:alias/1 or "-compile({no_auto_import,[alias/1]})." to resolve name clash
emqx_rule_runtime.erl:161:11: ambiguous call of overridden auto-imported BIF alias/1
 - use erlang:alias/1 or "-compile({no_auto_import,[alias/1]})." to resolve name clash

**Comment by k32** [comment]
Hi,

`alias` is a new BIF introduced in OTP24. Currently we don't have an official build/test pipeline for OTP24. For the time being, it's recommended to use OTP23 instead.
