### ISSUE TITLE
Cluster Failing to accept more connections, Timing out on Topic Subscription

### ISSUE THREAD

**Issue by tiaan-lg** [emqx/emqx#4856]
**Environment**: Windows Server 2019

- EMQ X version (e.g. `emqx_ctl status`): 4.2.7
- Hardware configuration (e.g. `lscpu`): Intel(R) Xeon(R) Platinum 8171M CPU @ 2.60GHz
- OS (e.g. `cat /etc/os-release`): Version 1809 build 17763.1935
- Other: Running 2 nodes in a Cluster behind a Load Balancer

**What happened and what you expected to happen**: Connections started dropping from 16000 down to 7000 and the 7000 connections were not able to subscribe to topics, even on adding an additional node to the cluster the max connections across nodes did not increase

**How to reproduce it (as minimally and precisely as possible)**: This happened sporadically and we are not sure how to reproduce it, as it was fixed by clearing everything and resetting up the broker

**Anything else we need to know?**: The Error in the Log files are as follows

`[error] <<"33709826">>@10.99.60.39:61908   crasher:
    initial call: emqx_connection:init/4
    pid: <0.20099.25>
    registered_name: []
    exception exit: {timeout,
                        {gen_server,call,
                            [<0.19631.0>,{subscribe,<<"RPC/33709826/+/+">>}]}}
      in function  emqx_connection:terminate/2 (emqx_connection.erl, line 433)
    ancestors: [<0.19779.0>,<0.19778.0>,esockd_sup,<0.140.0>]
    message_queue_len: 1
    messages: [{tcp,#Port<0.183476>,
                       <<16,47,0,4,77,81,84,84,4,194,0,240,0,8,51,51,55,48,
                         57,56,50,54,0,11,102,115,107,110,101,116,119,111,
                         114,107,115,0,12,102,115,107,64,51,108,51,99,116,
                         114,48,110>>}]
    links: [<0.19779.0>]
    dictionary: [{acl_cache_size,1},
                  {'$logger_metadata$',
                      #{clientid => <<"33709826">>,
                        peername => "10.99.60.39:61908"}},
                  {acl_keys_q,{[{subscribe,<<"RPC/33709826/+/+">>}],[]}},
                  {recv_pkt,2},
                  {{subscribe,<<"RPC/33709826/+/+">>},{allow,1621849756646}},
                  {incoming_bytes,72},
                  {send_pkt,1},
                  {outgoing_bytes,4},
                  {guid,{1621849755600768,255417829576323,0}}]
    trap_exit: false
    status: running
    heap_size: 987
    stack_size: 27
    reductions: 3675
  neighbours:`

Attached are the log files from the one node for more info

[emqx.log](https://github.com/emqx/emqx/files/6531771/emqx.log)
[emqx2.log](https://github.com/emqx/emqx/files/6531778/emqx2.log)
[emqx.3.log](https://github.com/emqx/emqx/files/6531781/emqx.3.log)
[emqx.4.log](https://github.com/emqx/emqx/files/6531783/emqx.4.log)

**Comment by tiaan-lg** [comment]
Our issue appears to very similar to the one explained here
https://github.com/emqx/emqx/issues/2960

**Comment by zmstone** [comment]
subscribe timeout has been fixed in 4.2.11
recommended version 4.3.1 for so far the most performant version wrt wildcard subscription handling

**Comment by tiaan-lg** [comment]
Can you please suggest or point me to docs on the best way of updating versions on EMQX, since we can not afford to lose the entire cluster

**Comment by tiaan-lg** [comment]
> subscribe timeout has been fixed in 4.2.11
> recommended version 4.3.1 for so far the most performant version wrt wildcard subscription handling

When I try to run version 4.3.1 it does not work, with the following error

`2021-05-24T15:40:38.113000+02:00 [error] application_controller: unterminated atom starting with '': '
2021-05-24T15:40:38.113000+02:00 [error] crasher: initial call: application_master:init/4, pid: <0.178.0>, registered_name: [], exit: {{bad_return,{{emqx_app,start,[normal,[]]},{'EXIT',{aborted,{application_load_error,{bad_environment_value,"'"}}}}}},[{application_master,init,4,[{file,"application_master.erl"},{line,138}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,226}]}]}, ancestors: [<0.177.0>], message_queue_len: 1, messages: [{'EXIT',<0.179.0>,normal}], links: [<0.177.0>,<0.44.0>], dictionary: [], trap_exit: true, status: running, heap_size: 376, stack_size: 28, reductions: 270; neighbours:`

**Comment by zmstone** [comment]
Sorry, didn’t notice that are running on windows. There is a bug in windows boot command which is fixed and going to be released in 4.3.2

**Comment by zmstone** [comment]
closing this issue. 4.3.2 will be released in a fee days
