### ISSUE TITLE
emqx:4.3.1 Win10 Enterprise 20H2 failed to start

### ISSUE THREAD

**Issue by dapeng17951** [emqx/emqx#4862]
emqx:4.3.1 Win10 Enterprise 20H2 failed to start
The mqtt client can connect with 127.0.0:1883, but cannot use native IP such as:192.168.0.1, while Dashboard under any ip cannot be enabled
**Environment**:

- EMQ X version (e.g. `emqx_ctl status`): 
- Hardware configuration (e.g. `lscpu`):
- OS (e.g. `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Erlang/OTP version (in case you build emqx from source code): 
- Others:

**What happened and what you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Comment by zmstone** [comment]
Windows boot issue has been fixed. We will release 4.3.2 this week

**Comment by zmstone** [comment]
Sorry this seem to be a different issue?

**Comment by zmstone** [comment]
@dapeng17951 could you be more specific on which exact step the error happened? The client cannot connect, or cannot subscribe?
