### ISSUE TITLE
webhook is error

### ISSUE THREAD

**Issue by sxl920624** [emqx/emqx#4905]
#### Environment

- OS: CentOS7.5
- Erlang/OTP: 
- EMQ: emqx-4.2.5

#### Description

webhook callback failed with following log messages：

[error] <<"server">>@172.27.58.133:63567 [Hooks] Failed to execute {emqx_web_hook,on_message_delivered,[{undefined}]}: {{shutdown,{gen_server,call,[<0.1732.0>,{post,{"/iot/action",[{<<"content-type">>,<<"application/json">>}],<<123,34,117,115,101,114,110,97,109,101,34,58,34,105,111,116,95,115,101,114,118,101,114,34,44,34,116,115,34,58,49,54,50,50,53,51,49,51,48,57,48,57,57,44,34,116,111,112,105,99,34,58,34,99,108,105,101,110,116,47,115,101,114,118,101,114,34,44,34,114,101,116,97,105,110,34,58,102,97,108,115,101,44,34,113,111,115,34,58,49,44,34,112,97,121,108,111,97,100,34,58,34,123,92,34,99,111,109,109,97,110,100,92,34,58,92,34,65,83,95,68,69,86,73,67,69,95,68,69,84,65,73,76,92,34,44,92,34,99,111,109,109,97,110,100,83,110,92,34,58,92,34,92,34,44,92,34,99,111,110,116,101,120,116,92,34,58,92,34,123,92,92,92,34,98,97,99,107,76,105,103,104,116,92,92,92,34,58,92,92,92,34,49,48,48,92,92,92,34,44,92,92,92,34,100,97,121,115,92,92,92,34,58,91,48,44,49,44,49,44,49,44,49,44,49,44,48,93,44,92,92,92,34,100,101,118,105,99,101,65,100,100,114,101,115,115,92,92,92,34,58,92,92,92,34,228,184,173,229,155,189,233,135,141,229,186,134,229,184,130,230,184,157,229,140,151,229,140,186,229,164,167,231,171,185,230,158,151,232,161,151,233,129,147,230,152,159,229,133,137,228,186,140,232,183,175,92,92,92,34,44,92,92,92,34,100,101,118,105,99,101,83,110,92,92,92,34,58,92,92,92,34,80,49,51,50,66,83,50,48,49,52,48,54,48,48,48,51,50,56,92,92,92,34,44,92,92,92,34,100,101,118,105,99,101,84,105,109,101,92,92,92,34,58,92,92,92,34,50,48,50,49,45,48,54,45,48,49,32,49,53,58,48,56,58,50,57,92,92,92,34,44,92,92,92,34,100,101,118,105,99,101,84,121,112,101,92,92,92,34,58,92,92,92,34,86,51,49,49,48,55,92,92,92,34,44,92,92,92,34,102,114,101,101,83,112,97,99,101,92,92,92,34,58,92,92,92,34,51,46,48,52,71,92,92,92,34,44,92,92,92,34,104,101,105,103,104,116,92,92,92,34,58,49,57,50,48,44,92,92,92,34,105,112,92,92,92,34,58,92,92,92,34,49,57,50,46,49,54,56,46,49,49,48,46,49,48,92,92,92,34,44,92,92,92,34,105,115,76,97,110,100,115,99,97,112,101,92,92,92,34,58,49,44,92,92,92,34,110,97,109,101,92,92,92,34,58,92,92,92,34,98,117,105,108,100,101,114,92,92,92,34,44,92,92,92,34,110,111,119,80,108,97,110,73,100,92,92,92,34,58,92,92,92,34,49,49,54,48,55,92,92,92,34,44,92,92,92,34,110,111,119,80,114,111,103,114,97,109,73,100,92,92,92,34,58,92,92,92,34,49,49,50,54,51,92,92,92,34,44,92,92,92,34,112,108,97,121,83,116,97,116,117,115,92,92,92,34,58,92,92,92,34,80,76,65,89,92,92,92,34,44,92,92,92,34,112,111,119,101,114,69,110,97,98,108,101,92,92,92,34,58,116,114,117,101,44,92,92,92,34,112,111,119,101,114,79,102,102,84,105,109,101,92,92,92,34,58,92,92,92,34,49,56,58,51,48,58,48,48,92,92,92,34,44,92,92,92,34,112,111,119,101,114,79,110,84,105,109,101,92,92,92,34,58,92,92,92,34,48,56,58,52,53,58,48,48,92,92,92,34,44,92,92,92,34,116,111,116,97,108,83,112,97,99,101,92,92,92,34,58,92,92,92,34,51,46,54,52,71,92,92,92,34,44,92,92,92,34,118,101,114,115,105,111,110,92,92,92,34,58,92,92,92,34,66,79,69,95,105,71,97,108,108,101,114,121,51,50,95,86,51,49,49,48,55,95,86,53,46,48,50,46,48,48,92,92,92,34,44,92,92,92,34,118,101,114,115,105,111,110,67,111,100,101,92,92,92,34,58,50,48,50,49,48,53,49,49,44,92,92,92,34,118,111,108,117,109,101,92,92,92,34,58,92,92,92,34,52,92,92,92,34,44,92,92,92,34,119,105,100,116,104,92,92,92,34,58,49,48,56,48,125,92,34,44,92,34,109,97,99,92,34,58,92,34,68,52,57,69,51,66,50,69,66,65,65,54,92,34,125,34,44,34,110,111,100,101,34,58,34,101,109,113,120,64,49,55,50,46,50,55,46,53,56,46,49,50,55,34,44,34,102,114,111,109,95,117,115,101,114,110,97,109,101,34,58,34,105,111,116,95,117,115,101,114,95,49,48,48,48,49,34,44,34,102,114,111,109,95,99,108,105,101,110,116,95,105,100,34,58,34,68,52,57,69,51,66,50,69,66,65,65,54,34,44,34,99,108,105,101,110,116,105,100,34,58,34,115,101,114,118,101,114,34,44,34,97,99,116,105,111,110,34,58,34,109,101,115,115,97,103,101,95,100,101,108,105,118,101,114,101,100,34,125>>},5000},6000]}},[{gen_server,call,3,[{file,"gen_server.erl"},{line,223}]},{emqx_web_hook,send_http_request,2,[{file,"emqx_web_hook.erl"},{line,329}]},{emqx_web_hook,with_filter,3,[{file,"emqx_web_hook.erl"},{line,355}]},{emqx_hooks,safe_execute,2,[{file,"emqx_hooks.erl"},{line,164}]},{emqx_hooks,do_run_fold,3,[{file,"emqx_hooks.erl"},{line,143}]},{emqx_channel,do_deliver,2,[{file,"emqx_channel.erl"},{line,812}]},{emqx_channel,handle_out,3,[{file,"emqx_channel.erl"},{line,737}]},{emqx_connection,with_channel,3,[{file,"emqx_connection.erl"},{line,556}]}]}

**Comment by terry-xiaoyu** [comment]
Seems that the webhook plugins was shutting down or restarting when the error occurred.

**Comment by qzhuyan** [comment]
@sxl920624 do you need more help on this?

**Comment by sxl920624** [comment]
> @sxl920624 do you need more help on this?

yes，we have a lot of error。

2021-09-04 12:01:49.190 [error] <<"D4D2D6A0DB1B">>@localhost:8080 [Channel] Unexpected info: {#Ref<0.8777091.300679169.11057>,ignored}
2021-09-04 12:01:49.190 [error] ehttpc: Unexpected call: {post,{"/iot/action",
                                [{<<"content-type">>,<<"application/json">>}],
                                <<"{\"username\":\"iot-user-Funbook C1\",\"proto_ver\":4,\"node\":\"emqx@172.27.58.127\",\"keepalive\":60,\"ipaddress\":\"10.244.0.0\",\"clientid\":\"C1SACH031818000990\",\"action\":\"client_connect\"}">>},
                               5000}
