### ISSUE TITLE
Dropped metric: Delivery v.s. The Message Data 

### ISSUE THREAD

**Issue by jmettes** [emqx/emqx#4906]
Hi,

What is the difference between the dropped metrics in the Delivery section and The Messages Data section? Is the Delivery section about outgoing messages delivered to subscribers, and The Messages Data about incoming published messages?

![image](https://user-images.githubusercontent.com/587870/120287713-da9ceb80-c302-11eb-8f03-fc81a7f5cbb0.png)
![image](https://user-images.githubusercontent.com/587870/120287737-e12b6300-c302-11eb-8251-0b39f5c03319.png)

**Comment by Rory-Z** [comment]
Hi, @jmettes 
"the message data dropped" means the messages dropped due to no subscribers
"delivery.dropped" means dropped messages when delivered to subscribers

**Comment by qzhuyan** [comment]
@jmettes I think the issue is resolved, thus I close the ticket.

Feel feel to reopen the issue if you need more help.
