### ISSUE TITLE
Message not replicating according to the Subscription Table

### ISSUE THREAD

**Issue by tpharaoh** [emqx/emqx#4911]
According to the docs on the subscription table, messages should be routed based on subscribers?
https://docs.emqx.io/en/broker/v4.2/advanced/cluster.html#subscription-table-topics-subscribers

node1 10.110.0.4
node2 10.110.0.5
node3 10.110.0.6
On my cluster I have the below line in topics table
http://mqtt1:18083/#/topics

tcommand/086BD7FFFED24613 | emqx@10.110.0.6

However, when I publish to node1, it does not route to node3 as it should. I tried each QOS setting just to be sure

Side topic,
is there a way to use the rule engine to send to specific nodes? Because ideally I'd like certain topics (device/#) to never replicate, and command/# to always replicate

**Comment by tigercl** [comment]
@tpharaoh Sorry, the rule engine cannot help you solve this problem. It is recommended to change your topic design, such as subscribing to `node/{node}/device/#`.

**Comment by tpharaoh** [comment]
By design shouldn't the message have replicated to all nodes?

**Comment by tigercl** [comment]
It may be that I did not understand what you mean. If you need a message to be forwarded to a node, the premise is that a client connects to this node and subscribes to the corresponding topic.
The final purpose of the message being forwarded to the node is to deliver the message to the subscriber. 
So if none of the devices connected to this node subscribe to topic a, then the message of topic a will not be forwarded to this node.

**Comment by zmstone** [comment]
@tpharaoh messages are only forwarded to the nodes where subscribers connected to it (or have a session in it).
if you can see a route from a topic to a node, but a message is not delivered to the consumer on that node?
you may want to check the rpc port opening between the nodes. ref: https://docs.emqx.io/en/broker/v4.3/advanced/cluster.html#firewall-settings

**Comment by zmstone** [comment]
btw there should be error logs if nodes can not reach each other on the rpc ports.

**Comment by tpharaoh** [comment]
I'll take a closer look.

My subscription table shows the node and the subscription of a device on
node3
the publish happened on node 1

In the meantime, I made a workaround by saving the node of connected device
to the database and publishing to the same node. It works, but I think
its not a 100% redundant solution
