### ISSUE TITLE
ubuntu 20.04tls 4.2 update to 4.3 start error

### ISSUE THREAD

**Issue by datafeng** [emqx/emqx#4946]
emxq start error:
![image](https://user-images.githubusercontent.com/6417549/120954562-07795480-c782-11eb-9455-7f32ef38eb3b.png)

**Environment**:
ubuntu 20.04 TLS

- EMQ X version (e.g. `emqx_ctl status`): 
- Hardware configuration (e.g. `lscpu`):
- OS (e.g. `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Erlang/OTP version (in case you build emqx from source code): 
- Others:

**What happened and what you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Comment by datafeng** [comment]
暂时解决办法是注释掉了那两行配置~~

**Comment by datafeng** [comment]
另外一台服务器升级完停止服务的时候也会提示错误：
root@ff:/etc/apt# emqx stop
ok
=ERROR REPORT==== 5-Jun-2021::15:54:17.893014 ===
REPORT_CB/1 CRASH: #{}; Reason: {error,
                                 {badfun,#Fun<emqx_plugins.25.38990593>},
                                 [{error_handler,undefined_lambda,3,
                                   [{file,"error_handler.erl"},{line,65}]}]}

**Comment by turtleDeng** [comment]
Thank you for your feedback, please provide the upgrade steps

**Comment by datafeng** [comment]
> Thank you for your feedback, please provide the upgrade steps

apt update
apt upgrade
emqx stop
emqx start
emqx_ctl status

**Comment by seguidor777** [comment]
Hello, I'm facing this same issue, can anybody please help me?
