### ISSUE TITLE
long_schedule warning before emqx service went out of service

### ISSUE THREAD

**Issue by mangostain** [emqx/emqx#4949]
**Environment**:

- EMQ X version (e.g. `emqx_ctl status`):  4.2.7
- Hardware configuration (e.g. `lscpu`): google cloud 512ram
- OS (e.g. `cat /etc/os-release`): ubuntu 20.04
- Kernel (e.g. `uname -a`): 5.4.0-1040-gcp #43-Ubuntu SMP Fri Mar 19 17:49:48 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

- Erlang/OTP version (in case you build emqx from source code): 
- Others:

**What happened and what you expected to happen**:
The EMQX service went out of service after long_schedule warning, the warning time matches with the last good mqtt message time received
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

According to the log, at the time it went out of service the log appears this:

2021-06-07 00:23:28.280 [warning] [SYSMON] long_schedule warning: pid = 

<0.14059.56>, info: [{timeout,778},
                                                  {in,undefined},
                                                  {out,undefined}]
undefined

but all other services (nginx, pm2, nodejs, etc) was running and okay

The problem was solved typing: emqx_ctl restart 

Working fine for 3 months...How to avoid this event the next time? Thanks!

**Comment by k32** [comment]
Hello,

Unfortunately, with the information available it is hard to say what caused the error, because the event doesn't contain any information about the location. `long_schedule` system monitor event means the Erlang VM couldn't preempt some process in a long time. This could be caused by many reasons.

Can you attach more logs: run_erl.log* emqx.log.* erlang.log.* from the time of the fault?

**Comment by mangostain** [comment]
run_erl.log --> some lines that were created after i restarted the crashed server
emqx.log.1 -- > Previous post
erland.log.1 --> next text


===== ALIVE Sun Jun  6 23:51:07 -04 2021

===== ALIVE Mon Jun  7 00:06:07 -04 2021

===== ALIVE Mon Jun  7 00:21:07 -04 2021
2021-06-07 00:23:28.280 [warning] [SYSMON] long_schedule warning: pid = <0.14059.56>, info: [{timeout,778},
                                                  {in,undefined},
                                                  {out,undefined}]
undefined
(emqx@127.0.0.1)1>
===== Mon Jun  7 00:35:27 -04 2021
[os_mon] memory supervisor port (memsup): Erlang has closed^M

=====

Thank you!

**Comment by k32** [comment]
Can you attach the files, please?

**Comment by mangostain** [comment]
But the files has some sensitive data? Theres no danger to public here?

**Comment by k32** [comment]
There should not be any sensitive data printed in the logs.

**Comment by mangostain** [comment]
The crash was on Mon Jun 7 00:35:27
The manual emqx service restart was on Mon Jun 7 10:30 aprox

[run_erl.log](https://github.com/emqx/emqx/files/6619031/run_erl.log)

[erlang.log](https://github.com/emqx/emqx/files/6619049/erlang.log)
[emqx.log](https://github.com/emqx/emqx/files/6619051/emqx.log)

**Comment by k32** [comment]
Thanks for the logs. Unfortunately, they don't contain any clues about the issue. As I mentioned before, `long_schedule` is a very generic kind of warning.
If the problem reproduces, can you collect some data before restarting the service? 

1. Information about CPU load (`uptime`) memory (`free`) and network connections (`netstat -tun | wc -l`) 
2. BEAM VM dump. It can be collected by logging in to the EMQX shell `emqx remote_console` and typing `halt("manual").` This will *stop the EMQX daemon* and dump its state to `log/crash.dump` file. Please note that the contents of this file might contain sensitive information.

Please feel free to reopen the issue if you the problem happens again. Right now, not much can be said about the possible cause, unfortunately.

**Comment by mangostain** [comment]
Hello again.... It is possible to be a RAM issue? My google cloud server is 512MB Ram, I remember before restarting the emqx service it was 450/576MB.... but now it's around 403MB/576MB.... What do you think? Thanks! Close the ticket after your reply

**Comment by k32** [comment]
I can't give a definite answer. It depends in the traffic volume.
