### ISSUE TITLE
EMQ X integration to InfluxDB

### ISSUE THREAD

**Issue by timhallinflux** [emqx/emqx#4959]
The current integration approach between EMQ X and InfluxDB is based on two things:
- UDP
- JSON formatted messages

InfluxDB OSS v1.x supports both of these.  However, InfluxDB Cloud does not support either.  InfluxDB OSS v2 has been released since November and also does not support UDP or JSON formatted messages.

Ideally, we could work together to upgrade the integration to leverage an HTTP-based integration between EMQ X which would allow for users to use either InfluxDB OSS v2 or InfluxDB Cloud.

**Comment by zmstone** [comment]
Hi @timhallinflux 
Thank you for reporting this.
Is http api the only way forward with new version influxdb?

**Comment by timhallinflux** [comment]
yes.

**Comment by zmstone** [comment]
sorry for the delayed reply.
we have been testing a bit with webhook.

converting this thread to a discussion.
