### ISSUE TITLE
use plugins emqx_auth_redis, After running for a few hours, failed for not_authorized

### ISSUE THREAD

**Issue by imkos** [emqx/emqx#4960]
**Environment**:

- EMQ X version (e.g. `emqx_ctl status`): 
- 4.3.3/4.2.12
- OS (e.g. `cat /etc/os-release`):
- k8s Cluster 1.20

#redis
  EMQX_AUTH__REDIS__SERVER: redis-external:6379
  EMQX_AUTH__REDIS__PASSWORD: lexar!20140109@860819#
  EMQX_AUTH__REDIS__DATABASE: "1"
  EMQX_AUTH__REDIS__PASSWORD_HASH: sha256,salt
  EMQX_AUTH__REDIS__AUTH_CMD: HMGET mqtt_user:%u password salt
  EMQX_ALLOW_ANONYMOUS: "false"
  EMQX_ACL_NOMATCH: deny

[Redis] do_check_acl error: tcp_closed
[Redis] Command: "HMGET mqtt_user:%u password salt" failed: tcp_closed
[Channel] Client *** (Username: '****') login failed for not_authorized

[root@node1 ~]# ipvsadm -lnc|grep 6379
TCP 05:54  ESTABLISHED 10.244.1.131:33307 10.97.106.32:6379  10.244.1.121:6379
TCP 05:54  ESTABLISHED 10.244.1.131:34995 10.97.106.32:6379  10.244.1.121:6379
TCP 13:27  ESTABLISHED 10.244.1.48:40412  10.97.106.32:6379  10.244.1.121:6379
TCP 05:54  ESTABLISHED 10.244.1.131:45147 10.97.106.32:6379  10.244.1.121:6379
TCP 11:16  ESTABLISHED 10.244.1.52:49206  10.97.106.32:6379  10.244.1.121:6379
TCP 11:16  ESTABLISHED 10.244.1.175:47604 10.97.106.32:6379  10.244.1.121:6379
TCP 02:53  ESTABLISHED 10.244.1.129:36549 10.97.106.32:6379  10.244.1.121:6379
TCP 14:27  ESTABLISHED 10.244.1.96:40456  10.97.106.32:6379  10.244.1.121:6379
TCP 02:53  ESTABLISHED 10.244.1.131:43947 10.97.106.32:6379  10.244.1.121:6379

[root@node1 ~]# kubectl get pods -o wide|grep emqx
emqx-0                                1/1     Running     0          24h    10.244.1.129   node1   <none>           <none>
emqx-1                                1/1     Running     0          24h    10.244.1.130   node1   <none>           <none>
emqx-2                                1/1     Running     0          24h    10.244.1.131   node1   <none>           <none>

emqx-0, emqx-1 no redis connection.

**Comment by terry-xiaoyu** [comment]
From you error logs I suspect the clients were denied because the connection crashed between emqx and the redis server.

```
[Redis] do_check_acl error: tcp_closed
[Redis] Command: "HMGET mqtt_user:%u password salt" failed: tcp_closed
[Channel] Client *** (Username: '****') login failed for not_authorized
```

**Comment by imkos** [comment]
I suspect emqx_auth_redis plug-in for redis connection did not do ping/pong heartbeat, causing the connection to be disconnected, but the plug-in still thinks that the old connection can still be used

**Comment by zmstone** [comment]
Closing this issue. Latest EMQX (5.5) now `PING` all nodes for periodic health check.
https://github.com/emqx/emqx/blob/ed8660cb681a03a07b6d4f5faa59dc35a9518314/apps/emqx_redis/src/emqx_redis.erl#L245
