### ISSUE TITLE
Mask password field in Dashboard --> Websocket page

### ISSUE THREAD

**Issue by michaelcplusplus** [emqx/emqx#4970]
**What would you like to be added/modified**:
Please mask the password field.
**Why is this needed**:
Securty reason

![image](https://user-images.githubusercontent.com/24432169/121381529-16a8ff80-c946-11eb-9e90-1246cc900c20.png)

**Comment by DDDHuang** [comment]
Thank you very much for your suggestion, we have added the requirement and will add this feature in the later version

**Comment by qzhuyan** [comment]
@DDDHuang I assign the ticket to you, feel free to drive it.
