### ISSUE TITLE
Cancel delayed publish message

### ISSUE THREAD

**Issue by DDDHuang** [emqx/emqx#4984]
**What would you like to be added/modified**:

Cancel delayed publish message.

**Why is this needed**:

Information changed before delayed publish. Like cancel order before goods delivery.

**Comment by qzhuyan** [comment]
@DDDHuang what is the status of this ticket? 

 Any implementation proposal? Are you working on it?

**Comment by DDDHuang** [comment]
Down

**Comment by t2wu** [comment]
> Down

What does "down" mean?

**Comment by DDDHuang** [comment]
> > Down
> 
> What does "down" mean?

Sorry. I mean , Already completed

**Comment by DDDHuang** [comment]
> > Down
> 
> What does "down" mean?

This is a new feature in version 5.0. Already available in `rc.4` version.
