### ISSUE TITLE
emqx ratelimit problem

### ISSUE THREAD

**Issue by mopybird** [emqx/emqx#4988]
#### Environment

- OS:  linux
- Erlang/OTP: 
- EMQ: v4.2

#### Description

*A description of the issue*

我的终端5秒钟publish一条报文，
rate limit配置为 {ratelimit,[{conn_messages_in,{100,10}}]}]}
但是每隔10分钟会收到限速告警，按照这个参数，10秒钟不可能有100条报文额

2021-06-14T06:28:36.690006+08:00 [warning] 862167051704777@223.104.255.197:28010 [MQTT] Pause 100ms due to rate limit
2021-06-14T06:38:11.010043+08:00 [warning] 862167051704777@223.104.255.197:28010 [MQTT] Pause 100ms due to rate limit

**Comment by mopybird** [comment]
I have a setup of emqx with this config in v4.1
I have a setup of emqx with this config in v4.1

EMQX_ZONE__EXTERNAL__PUBLISH_LIMIT: 100,10s
EMQX_LISTENER__SSL__EXTERNAL: 8883
EMQX_STATSD__INTERVAL: "1000"
EMQX_LISTENER__TCP__EXTERNAL__MAX_CONN_RATE: 2000
EMQX_LISTENER__TCP__EXTERNAL__ACTIVE_N: 100

my clients for sure sending fewer packets then described in rate-limiting config
but logs show that : [MQTT] Pause 100ms due to rate limit
EMQX_ZONE__EXTERNAL__PUBLISH_LIMIT: 100,10s
EMQX_LISTENER__SSL__EXTERNAL: 8883
EMQX_STATSD__INTERVAL: "1000"
EMQX_LISTENER__TCP__EXTERNAL__MAX_CONN_RATE: 2000
EMQX_LISTENER__TCP__EXTERNAL__ACTIVE_N: 100

my clients for sure sending fewer packets then described in rate-limiting config
but logs show that : [MQTT] Pause 100ms due to rate limit

**Comment by HJianBo** [comment]
**As action-n gets larger, the accuracy of rate checking on short time intervals gets lower.**

This is due to the current checking mechanism: we only check the rate limit once every N TCP messages we receive (N is equal to the value of active-n)

When action_n is set to 1, this means that the rate check is completely accurate.

However, the lower the value of action_n, it results in lower network I/O efficiency of EMQ X.

**Comment by mopybird** [comment]
但是我能确定，publish报文的速率非常低，就算是每action_n一次，也远远达不到10秒100条报文，除了每5分钟的一个心跳publish，就没有其他的publish。给人的感觉算法就是每次检测rate limit的时候，都必须停留100ms

**Comment by HJianBo** [comment]
Yes, you are right. I have reproduced this issue in v4.2.8.

This is really a problem with our checking mechanism, which causes it to look like the rate limiting results will be strange.


One temporary solution is to adjust active_n to be less than the value of Burst in `publish_limit`.

**Comment by mopybird** [comment]
ok, I try it.
thank you very much
