### ISSUE TITLE
Some LwM2M resources returning signed data in MQTT payload, change from v4.2.7

### ISSUE THREAD

**Issue by endianjoakim** [emqx/emqx#4989]
**Environment**: `Kubernetes/docker`

- EMQ X version (e.g. `emqx_ctl status`): 
- Hardware configuration (e.g. `lscpu`): `32cpu`
- OS (e.g. `cat /etc/os-release`): `alpine-3.12.7`
- Kernel (e.g. `uname -a`): `Linux ng-iot-emqx-0 5.4.89+ #1 SMP Sat Feb 13 19:45:14 PST 2021 x86_64 Linux`
- Erlang/OTP version (in case you build emqx from source code):  -
- Others:

```
Plugin(emqx_lwm2m, description=EMQ X LwM2M Gateway, active=true)
```

**What happened and what you expected to happen**:
We're testing `v4.3.1`. There is a change since `v4.2.7` in the `emqx-lwm2m` app where an objects resource is suddenly treated as signed 8 bit. 

Relevant LwM2M XML:
```xml
                <Item ID="7">
                    <Name>speed_limit</Name>
                    <Operations>RW</Operations>
                    <MultipleInstances>Single</MultipleInstances>
                    <Mandatory>Mandatory</Mandatory>
                    <Type>Integer</Type>
                    <RangeEnumeration>50 - 200</RangeEnumeration>
                    <Units></Units>
                    <Description><![CDATA[Max Speed limit for the vehicle]]></Description>
                </Item>
```

Note: LwM2M XML can not specify `Unsigned` data type for resources.  

Since the change, device connecting to `EMQx v4.3.1`:
```
write /34120/0/7=129
read /34120/0/7 > ReadResponse Content 2.05 {'/34120/0/7': -127}
```

The same device, running the same firmware connecting to `EMQx v4.2.7`:
```
write /34120/0/7=129
read /34120/0/7 > ReadResponse Content 2.05 {'/34120/0/7': 129}
```

We cant find any configuration that would cause this. Any ideas of what goes wrong?

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Comment by endianjoakim** [comment]
Any progress on this?

**Comment by endianjoakim** [comment]
Have anyone had time to investigate this?

**Comment by endianjoakim** [comment]
This is still an issue in `v4.3.6`

```
2021-08-05 14:59:13 lwm2m/urn:imei:12341234/dn {"reqID":6103492312,"msgType":"write","data":{"path":"/34120/0/7","type":"Integer","value":129}}
2021-08-05 14:59:13 lwm2m/urn:imei:12341234/up/resp {"reqID":6103492312,"msgType":"write","data":{"reqPath":"/34120/0/7","codeMsg":"changed","code":"2.04"}}
2021-08-05 14:59:15 lwm2m/urn:imei:12341234/dn {"reqID":99103492334,"msgType":"read","data":{"path":"/34120/0/7"}}
2021-08-05 14:59:15 lwm2m/urn:imei:12341234/up/resp {"reqID":99103492334,"msgType":"read","data":{"reqPath":"/34120/0/7","content":[{"value":-127,"path":"/34120/0/7"}],"codeMsg":"content","code":"2.05"}}
```

**Comment by zmstone** [comment]
Hi @endianjoakim 
I'm quite new to LW.
Is `Integer` an 8-bit signed number in this protocol ?

**Comment by endianjoakim** [comment]
Thanks for responding. 

It's signed but not necessarily 8-bit. It does not really matter though, since there was a change in EMQx version from `4.2.7` to `4.3.1` that cause this behaviour to change. 

I think this is the offending commit: https://github.com/emqx/emqx/commit/f8fbd3e3dbbba2db60a295358aae15e275812556

**Comment by endianjoakim** [comment]
It seems this bug was raised, https://github.com/emqx/emqx/issues/4499. However, the fix does not take the valid range into consideration.  

E.g our resource definition:
```xml
                <Item ID="7">
                    <Name>speed_limit</Name>
                    <Operations>RW</Operations>
                    <MultipleInstances>Single</MultipleInstances>
                    <Mandatory>Mandatory</Mandatory>
                    <Type>Integer</Type>
                    <RangeEnumeration>50 - 200</RangeEnumeration>
                    <Units></Units>
                    <Description><![CDATA[Max Speed limit for the vehicle]]></Description>
                </Item>
```

This clearly states the values must be between `50 - 200`. `200` means it needs at least `9` signed bits to be represented, so it should be considered a `16` bit signed value.

**Comment by zmstone** [comment]
Thank you @endianjoakim 
I am confused.
If the valid range is `[50, 200]`, isn't `129` valid?
why is `-127` to be expected ?

**Comment by zmstone** [comment]
Ah, sorry, I read it the other way around. It was 129 in 4.2 but now negative in 4.3.

**Comment by zmstone** [comment]
Hi @endianjoakim 
the fix will be included in the next release 4.3 bug fix release

**Comment by endianjoakim** [comment]
Thanks for the quick turnaround! Appreciate it 🙏

**Comment by endianjoakim** [comment]
I've tested v4.3.7 which contain this fix, however I'm getting the same results. I'm writing `129` to the device, and receive `-127` back. 

```bash
2021-08-09 13:20:28 lwm2m/urn:imei:12341234/dn {"reqID":6103492312,"msgType":"write","data":{"path":"/34120/0/7","type":"Integer","value":129}}
2021-08-09 13:20:29 lwm2m/urn:imei:12341234/up/resp {"reqID":6103492312,"msgType":"write","data":{"reqPath":"/34120/0/7","codeMsg":"changed","code":"2.04"}}
2021-08-09 13:20:29 lwm2m/urn:imei:12341234/dn {"reqID":99103492334,"msgType":"read","data":{"path":"/34120/0/7"}}
2021-08-09 13:20:29 lwm2m/urn:imei:12341234/up/resp {"reqID":99103492334,"msgType":"read","data":{"reqPath":"/34120/0/7","content":[{"value":-127,"path":"/34120/0/7"}],"codeMsg":"content","code":"2.05"}}
```

Looking at the fix, https://github.com/emqx/emqx/pull/5425, it still does not take the allowed range into consideration. 
Also, the problem is how the TLV values are interpreted when READING from the device, not WRITING.

**Comment by zmstone** [comment]
@terry-xiaoyu please correct if I'm wrong.
We believed it was a bug in TLV encoder (when WRITING) because, int the old code:
`129` was encoded as a single byte, which in fact should have been two: `0, 129`.
This single byte was then decoded as 8 bit single-byte integer which is `-127`.
The correct encoding for `-127` should be 2 bytes: `255, 129`.

As for the range in the schema, I believe it's for data validation, not for serialisation
so we took the easy way out: the broker just passes the numbers through transparently.

When EMQ X is parsing TLV binary, the decoder simply trust the data provided by the writer,
e.g. in this case, if it's `129` of `Integer` type, the data writer should have provided
`2` for length, followed by `0,129` for Value.
If the writer for some reason provided `1` for length and `129` for data,
then the value is decoded as `-127`.

@endianjoakim Could you help me to understand how you tested it?
e.g. how exactly is the WRITE done and how is the read observed.

**Comment by endianjoakim** [comment]
@zmstone I'm testing using `mosquitto_sub`

```
mosquitto_pub -t "lwm2m/urn:imei:12341234/dn" -m '{"reqID":6103492312,"msgType":"write","data":{"path":"/34120/0/7","type":"Integer","value":129}}'
sleep 1.0
mosquitto_pub -t "lwm2m/urn:imei:12341234/dn" -m '{"reqID":99103492334,"msgType":"read","data":{"path":"/34120/0/7"}}'
```

**Comment by terry-xiaoyu** [comment]
> @terry-xiaoyu please correct if I'm wrong.
> We believed it was a bug in TLV encoder (when WRITING) because, int the old code:
> `129` was encoded as a single byte, which in fact should have been two: `0, 129`.
> If this single byte is then decoded as 8 bit integer, it'll result in `-127`.
> The correct encoding for `-127` should be 2 bytes: `255, 129`.
> 
> As for the range in the schema, I believe it's for data validation, not for serialisation
> so we took the easy way out: the broker just passes the numbers through transparently.
> 
> When EMQ X is parsing TLV binary, the decoder simply trust the data provided by the writer,
> e.g. in this case, if it's `129` of `Integer` type, the data writer should have provided
> `2` for length, followed by `0,129` for Value.
> If the writer for some reason provided `1` for length and `129` for data,
> then the value is decoded as `-127`.
> 
> @endianjoakim Could you help me to understand how you tested it?
> e.g. how exactly is the WRITE done and how is the read observed.

Yes, you're right, we rely on the device to reply the `correct` length of the data.

I tested with the [wakaama client](https://github.com/eclipse/wakaama) and the resource Id `/1/0/1`:

Send the following MQTT message to emqx broker:
```
Topic: lwm2m/868744031573276/dn

{
    "reqID": "2",
    "msgType": "write",
    "data": {
        "path": "/1/0/1",
        "type": "Integer",
        "value": 129
    }
}
```

Before 4.3.7 the WRITE will fail and the wakaama client will return badarg because it received -127 instead. And the READ command get -127:


Send:
```
Topic: lwm2m/868744031573276/dn

{
    "reqID": "2",
    "msgType": "read",
    "data": {
        "path": "/1/0/1"
    }
}
```

Get:
```
Topic: lwm2m/868744031573276/up/resp

{"reqID":"2","msgType":"read","data":{"reqPath":"/1/0/1","content":[{"value":-127,"path":"/1/0/1"}],"codeMsg":"content","code":"2.05"}}
```

So I thought I've reproduced the issue and I believed it is the encoder that sent incorrect integer to the device, then I fixed that issue.

**Comment by terry-xiaoyu** [comment]
@endianjoakim 

I've no experience in zephyr and don't know how to set up a testing environment using it. Could you go into the emqx console by `emqx attach`, and debug the function call emqx_lwm2m_tlv:parse/1 ?

```
dbg:tracer().
dbg:p(all, c).
dbg:tpl(emqx_lwm2m_tlv, parse, '_', cx).
```

After tracing the function using the above commands, send the lwm2m command `WRITE /34120/0/7` again.

**Comment by zmstone** [comment]
Please use `emqx remote_console` instead of `emqx attach`

**Comment by endianjoakim** [comment]
The logs show:
```
(<0.10374.0>) call emqx_lwm2m_tlv:parse(<<193,7,129>>) ({emqx_lwm2m_message,
                                                         tlv_to_json,2})
(<0.10374.0>) returned from emqx_lwm2m_tlv:parse/1 -> [#{tlv_resource_with_value =>
                                                             7,
                                                         value => <<129>>}]
```

**Comment by terry-xiaoyu** [comment]
The TLV value of the WRITE command can be found if you enable the debug log, using `emqx_ctl log set-level debug`, like:

```
2021-08-10T10:42:56.674093+08:00 [debug] LWM2M-PROTO: Deliver To CoAP(<0.1996.0>), CoapRequest: {coap_message,con,put,undefined,<<>>,[{uri_path,[<<"1">>,<<"0">>,<<"1">>]},{content_format,<<"application/vnd.oma.lwm2m+tlv">>}],<<194,1,0,129>>}
```

**Comment by terry-xiaoyu** [comment]
This is the dbg output of the parser (it parses the READ command) I tested with wakaama:

```
(emqx@127.0.0.1)4> (<0.1966.0>) call emqx_lwm2m_tlv:parse(<<194,1,0,129>>) ({emqx_lwm2m_message,
                                                          tlv_to_json,2})
(<0.1966.0>) returned from emqx_lwm2m_tlv:parse/1 -> [#{tlv_resource_with_value =>
                                                            1,
                                                        value => <<0,129>>}]
```

We could see that the TLV data is `<<194,1,0,129>>`, with uses 2 bytes for the integer `129`. But in your case the TLV data is `<<193,7,129>>`, which is the TLV representation of integer -127. 

If the WRITE command sent by emqx is correct (`<<194,1,0,129>>`), then I think it is your lwm2m client that sent the wrong TLV data.

**Comment by endianjoakim** [comment]
@terry-xiaoyu Thank you, we've found a potential issue in Zephyr. Looking into it.

**Comment by endianjoakim** [comment]
@terry-xiaoyu Thanks for your support! We'll fix this issue in Zephyr, see linked Zephyr bug. This issue can be closed.
