### ISSUE TITLE
WebHook timeout

### ISSUE THREAD

**Issue by igolubic** [emqx/emqx#4990]
**Environment**:

- EMQ X version (e.g. `emqx_ctl status`):  4.3.3
- Hardware configuration (e.g. `lscpu`): Docker
- OS (e.g. `cat /etc/os-release`): Alpine Linux, 3.12.7 (Docker native)
- Kernel (e.g. `uname -a`): Linux 0f5b067a3e67 4.19.128-microsoft-standard #1 SMP Tue Jun 23 12:58:10 UTC 2020 x86_64 Linux

**Issue:**

I have configured EMQX with Docker (all other features are working fine), first .env file configuration for Webhooks didn't work:
`EMQX_WEB__HOOK__URL=http://backend:3000/v1/mqtt-webhook`
but I manually configured emqx_web_hook.conf file in my Docker container (set to: web.hook.url = http://backend:3000/v1/mqtt-webhook). 
Configured to publish when a client gets connected or disconnected. When clients tries to connect (using MQTT.fx) it takes some time to connect, but in log files of EMQX it throws this error: 

`2021-06-14T12:26:01.133352+00:00 [error] 664bc76d3f5f48f2a466933b7a4cc6d5@172.18.0.1:57246 [WebHook] HTTP request error: timeout
`

only after this error is thrown MQTT client connects to the broker.

I have tried cURL POST request to the same endpoint from the container, and it works, so containers are communicating.

**Comment by zmstone** [comment]
Hi @igolubic 
Could you check:
1. if there are firewall rules blocking emqx node to access backedn:3000
2. if the `backend` host is resolvable to an ipv6 address, but not reachable from the v6 stack

**Comment by igolubic** [comment]
Hi, @zmstone
As mentioned, manual requests from the container are passing without any issue, so the container that runs the broker can access the backend service.

**Comment by zmstone** [comment]
Hi 
Still need a check on 2.
Emqx tries to use ipv6 when it’s resolvable,
If the http server refuses the connection, everything is fine. But if the firewall silently drops the connection , it may hang.

**Comment by igolubic** [comment]
Hi,
Any idea how to check this in Docker? We tested this on staging instance, and if FQDN is provided it resolves, and works. But for the local development environment, it is still causing issues. 
Tried with **backend** as an endpoint, and also with **localhost** with Proxy. Same thing. 

As I got it, EMQX prioritizes ipv6?

**Comment by zmstone** [comment]
To test out if it’s an ipv6 issue, you can try to use backend’s ipv4 address in configuration.

When ipv6 is available, emqx tries to connect it, it’s ok if the address is not being listened on, then emqx will fallback to ipv4. But it may hang until tomeout if the connection is being dropped by fw etc.
However I am not entirely sure if this is the reason of this issue.

**Comment by zmstone** [comment]
closing due to inactive for weeks.
