### ISSUE TITLE
I can't get into "localhost:18083"

### ISSUE THREAD

**Issue by wyihe** [emqx/emqx#4992]
### Use process
After `emqx start`, No errors,And i use `emqx console` cmd shows emqx is started!;
if i 'emqx stop', cmd shows `Node 'emqx@127.0.0.1' not responding to pings.`
After these operator, file /log/emqx.log.1 is NULL;

### Picture
![image](https://user-images.githubusercontent.com/72311031/121983967-bfcb7c00-cdc4-11eb-8887-a4e2edf57a25.png)
![image](https://user-images.githubusercontent.com/72311031/121983979-c4903000-cdc4-11eb-97ea-ef4963d34537.png)
![image](https://user-images.githubusercontent.com/72311031/121984006-d07bf200-cdc4-11eb-8e34-18c7df7e0962.png)
![image](https://user-images.githubusercontent.com/72311031/121984018-d540a600-cdc4-11eb-905d-fe58372389c7.png)

**Comment by k32** [comment]
Hello,
Could you start emqx using `emqx console` command and post the output?
