### ISSUE TITLE
Subscribe rest api is not working on cluster level

### ISSUE THREAD

**Issue by Ayesha262** [emqx/emqx#4999]
**Environment**

- OS: CentOS Linux 7
- Erlang/OTP: R22/10.7
- EMQ: EMQ X Broker 4.1.1

**Description**

Why isn't subscribe api working on cluster level?
i have deployed emqx cluster on prod environment stack and the following scenario is not working on it, is this an issue or a feature?
1. Create a cluster comprising two nodes via docker compose
2. Connect a user to a node 1.
3. Subscribe that user to a topic on node 1.
4. Subscription will be successful
5. Subscribe that user to a topic on node 2 -> You will get the "channel_not_found" error
 
**P.S**
docker compose file to create cluster and script to test scenario is attached in zip folder.

Prerequisites to run the test:
- node version v8.10.0
- node modules : mqtt, inquirer, request
- docker

Procedure to run the test:
1. download the attached zip
2. extract the files
3. open terminal and cd into the extracted folder and run the following commands:
docker-compose -p my_emqx up -d
node test_scenario.js

[test-files.zip](https://github.com/emqx/emqx/files/6655439/test-files.zip)

**Comment by tigercl** [comment]
@Ayesha262 First, when you need to subscribe to a topic on another node, you do not need to change the URL of the HTTP request. In addition, there is indeed a problem with the cluster support of the subscription API, but it has been fixed in the newer version, you can try 4.2.12 or 4.3.3.

**Comment by Ayesha262** [comment]
Thanks you for replying. I can confirm that issue got resolved with 4.3.3.
Regarding changing of url, we are accessing cluster via load balancer. Then to illustrate the behavior I requested the different node in my example.
