### ISSUE TITLE
Upgrade from 4.1.1 to 4.3.3 without downtime

### ISSUE THREAD

**Issue by Ayesha262** [emqx/emqx#5035]
**Environment**

- OS: CentOS Linux 7
- Erlang/OTP: R22/10.7
- EMQ: EMQ X Broker 4.1.1

**Description**
We are running EMQX broker version4.1.1 on Prod environment and planning to upgrade to version 4.3.3.
Is there a way to do this minor upgrade without any downtime?

**Comment by k32** [comment]
Hello,

This hot upgrade path is not supported. From documentation https://docs.emqx.io/en/broker/v4.3/advanced/relup.html#hot-upgrade :

> Currently EMQ X Broker only supports hot upgrade of Patch version (Patch version is the third digit of the version number). That is, it currently supports hot upgrades from 4.2.0 -> 4.2.1, 4.2.0 -> 4.2.2, ..., etc., but 4.2.x cannot be hot upgraded to 4.3.0 or 5.0.

There are significant changes in the internal states of the process and the database schemas that are too hard to migrate in the runtime.
