### ISSUE TITLE
How to use HAProxy serves as a LB for EMQ X cluster？

### ISSUE THREAD

**Issue by Bevr2020** [emqx/emqx#5036]
**Please describe your problem in detail, if necessary, you can upload the log file through the attachment**:
emqx 4.3.3
node1： emqx@10.20.178.249
node2：emqx@10.20.178.80

haproxy：10.20.178.80
![image](https://user-images.githubusercontent.com/62202698/122552476-f1fd0800-d068-11eb-80df-e2e93f90a24c.png)

emqx.conf: 
------------------------------------
node.name = emqx@10.20.178.249

cluster.discovery = static

cluster.static.seeds = emqx@10.20.178.249, emqx@10.20.178.80

listener.tcp.external.proxy_protocol = on

-------------------------------------------

I try to connect 10.20.178.80:1889, haproxy works , but emqx error?
![image](https://user-images.githubusercontent.com/62202698/122552853-6d5eb980-d069-11eb-84cf-088f4eec2e9c.png)

![image](https://user-images.githubusercontent.com/62202698/122552717-39839400-d069-11eb-9192-b9b31d9c8ee3.png)

how can i fix this problem? help me,thank you.

**Comment by sh3d2** [comment]
hi @Bevr2020 
you have `proxy protocol` enabled in emqx configuration and not in haproxy.
you can either:
* disable proxy protocol in emqx by setting `listener.tcp.external.proxy_protocol = off`, or
* enable proxy protocol in haproxy by appending `send-proxy` argument in your tcp backend definition, more details here https://www.haproxy.com/blog/using-haproxy-with-the-proxy-protocol-to-better-secure-your-database/#5-send-proxy (although its about configuring haproxy for a percona db server, same principle applies to emqx and haproxy)

ps. i dont think its a good idea to distribute dashboard connections between nodes in cluster. i'd just connect to a specific node to manage the cluster (and you can manage the whole cluster from any node)

**Comment by Bevr2020** [comment]
@sh3d2 thx,it works.

**Comment by sh3d2** [comment]
perfect. could you please close the issue @Bevr2020 now when its all resolved?
