### ISSUE TITLE
cann't modify emqx.conf file with notepad or visual studio

### ISSUE THREAD

**Issue by gzalexhe** [emqx/emqx#5042]
**Environment**:

- EMQ X version (e.g. `emqx_ctl status`): 
- Hardware configuration (e.g. `lscpu`):
- OS (e.g. `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Erlang/OTP version (in case you build emqx from source code): 
- Others:

**What happened and what you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Comment by qzhuyan** [comment]
close due to lack of information.

@gzalexhe check the permission on the file.

You are welcomed to reopen the ticket with more information provided.

**Comment by gzalexhe** [comment]
I also use the ubuntu version,and it do the job correct.
so ,the reason is windows version is not work correct,
but so many people use the windows version,i hope you can fix it in windows version.

> elcomed to reopen the ticket with more informatio

**Comment by gzalexhe** [comment]
and i use the administrator right 　to open the emqx.conf file，and save with utf-8mode,but,it also
cann't work accurately.

**Comment by k32** [comment]
Could you provide the logs so we can investigate the issue?

**Comment by qzhuyan** [comment]
> and i use the administrator right 　to open the emqx.conf file，and save with utf-8mode,but,it also
> cann't work accurately.

do you mean after you save the file, emqx has issue to get started? 
can you attach the file after modified?

**Comment by gzalexhe** [comment]
step1：download the emqx4.3.0 windows version by zip file.
step2:unzip the file to emqx0701 directory.
step3: modify the file etc/emqx.conf&nbsp; with visual studio ass fllow:
listener.ssl.external.keyfile = etc/certs/mqttfullteem.fullteem.com.key
listener.ssl.external.certfile = etc/certs/mqttfullteem.fullteem.com.pem
step4:use the administrator&nbsp;&nbsp;authority to open the cmd commond,and cd emqx0701\bin and run :emqx start
step5:use chrome,enter: localhost:18083,can see the dashboard.but in websocket，cann't not open it with ssl.


later,i download the ubuntu version,and do it with&nbsp;above-mentioned，it work correctly


why？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "emqx/emqx"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年7月1日(星期四) 下午4:57
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [emqx/emqx] cann't modify emqx.conf file with notepad or visual studio (#5042)





  
and i use the administrator right 　to open the emqx.conf file，and save with utf-8mode,but,it also
 cann't work accurately.
  
do you mean after you save the file, emqx has issue to get started?
 can you attach the file after modified?

**Comment by k32** [comment]
What does `emqx start` command prints in the console when you run this command?

**Comment by gzalexhe** [comment]
please see the attach png file




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "emqx/emqx"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年7月1日(星期四) 下午5:38
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [emqx/emqx] cann't modify emqx.conf file with notepad or visual studio (#5042)





 
What does emqx start command prints in the console when you run this command?

**Comment by k32** [comment]
Sorry, I don't see the attached file. Are you using email reply to comment in the thread? I don't think github supports email attachments.

**Comment by gzalexhe** [comment]
please see the png attach file.i can see it rightly。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "emqx/emqx"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年7月1日(星期四) 下午5:45
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [emqx/emqx] cann't modify emqx.conf file with notepad or visual studio (#5042)





 
Sorry, I don't see the attached file. Are you using email reply to comment in the thread? I don't think github supports email attachments.

**Comment by k32** [comment]
Could you open this link: https://github.com/emqx/emqx/issues/5042 and point out where the attached file is?
Could you paste the output in plain text, rather than attach a screenshot?

**Comment by gzalexhe** [comment]
sorry,i find that the email engine is not compatible wiht  tencent qq mailbox engine。so i attach the png files in guthub mailbox engine。hope you can see it

**Comment by k32** [comment]
Hello again, @gzalexhe 
Could you try reproducing the issue again, and collecting `log/emqx.log` files?

**Comment by qzhuyan** [comment]
close due to inactivity.
