### ISSUE TITLE
Setting EMQX_NODE__NAME for docker container has no effect

### ISSUE THREAD

**Issue by haimiko** [emqx/emqx#5043]
**Environment**:

- EMQ X version 4.1.3
- Hardware configuration (e.g. `lscpu`):
- OS: Alpine Linux 3.11.6
- Kernel (e.g. `uname -a`): 5.4.0-51-generic
- Erlang/OTP version (in case you build emqx from source code): 
- Others:

**What happened and what you expected to happen**:
I set the **EMQX_NODE__NAME=emqx@172.18.0.2** environment variable in the docker config,  etc/emqx.conf got set correctly by the entry script:
```
/opt/emqx $ grep node.name  etc/emqx.conf
## The App name is used to build 'node.name' with IP address.
## will create a path in etcd: v2/keys/<prefix>/<cluster.name>/<node.name>
## The app name helps build 'node.name'.
node.name = emqx@172.18.0.2
```
however the application isn't picking it up.
```
/opt/emqx $ emqx_ctl status
Node '01728c48fade@172.18.0.2' is started
emqx 4.1.3 is running
```

I believe the bug is in bin/emqx:
```
if [ ! -z "$EMQX_NODE_NAME" ];   
```
should be
```
if [ ! -z "$EMQX_NODE__NAME" ]; 
```

Adding a second environment variable EMQX_NODE_NAME with the same value resolves the issue.

**Comment by k32** [comment]
Hello,

You need to use `EMQX_NODE_NAME` variable (which maps `node_name` config variable) instead of `EMQX_NODE__NAME` (which maps to an _unused_ `node.name` config).

**Comment by haimiko** [comment]
Then the docker documentation needs to be fixed.

**Comment by zmstone** [comment]
Hi @haimiko 
Which document did you mean?

**Comment by haimiko** [comment]
https://hub.docker.com/r/emqx/emqx-ee  search for EMQX_NODE__NAME found in
the table.

**Comment by zmstone** [comment]
thank you, this pr has it fixed, and we’ll sync it to dockerhub soon.
https://github.com/emqx/emqx/pull/5083

**Comment by elcreator** [comment]
https://hub.docker.com/_/emqx here it should be fixed too (maybe together with all other usages of __ instead of _)
