### ISSUE TITLE
CPU high load when in docker and using plugin with MongoDB authentication

### ISSUE THREAD

**Issue by seksity** [emqx/emqx#5044]
**Environment**:

- EMQ X version (e.g. `emqx_ctl status`): `4.3.3`
- Hardware configuration (e.g. `lscpu`): `Intel i7`
- OS (e.g. `cat /etc/os-release`): `MacOS BigSur 11.4`
- Kernel (e.g. `uname -a`): `Darwin Seksits-MBP 20.5.0 Darwin Kernel Version 20.5.0: Sat May  8 05:10:33 PDT 2021; root:xnu-7195.121.3~9/RELEASE_X86_64 x86_64`
- Erlang/OTP version (in case you build emqx from source code): `-`
- Others:

**What happened and what you expected to happen**:
I testing EMQX v4.3.3 in docker by follows: https://www.emqx.io/downloads#broker

when I setting emqx.conf:
`allow_anonymous = false`

And configuration in `emqx_auth_mongo.conf` and enable plugins `emqx_auth_mongo` in dashboard.

When restart the docker emqx container I getting the High Load CPU. And when stop the mongo plugin it will back to normal

**How to reproduce it (as minimally and precisely as possible)**: 

> Start 'emqx_auth_mongo` in dashboard

**Anything else we need to know?**:  --

**Comment by qzhuyan** [comment]
Are there any traffic running through the broker? 

Or you just enable the plugin on idle machine then running into high load ?

**Comment by seksity** [comment]
Hi,

@qzhuyan I just enable the plugin on idle machine, not yet have trading to broker. 

But now I can scope down to fixed the problem. 

If you follows the step as in: `https://www.emqx.io/downloads#broker`, then start the authentication plugin (in my case MongoDB plugin) it will cause the CPU high load. 

After I investigate, I guess may it cause of problem as below:-
1. Because I testing by running MongoDB in docker too, So if follows `https://www.emqx.io/downloads#broker` then the EMQX in docker not yet link to the same docker network of MongoDB database -- then have some problem to CPU high load

So, I fix it by using create EMQX in `docker-compose.yml` and link EMQX container to the same docker network of MongDB container, then Start the `emqx_auth_mongo` plugin in the dashboard that it NOT happen CPU high load anymore.

I not sure WHY during EMQX cannot connect to MongoDB database, It making CPU high load on that time.

**Comment by seksity** [comment]
Another Question.....

As I testing to create docker-compose in cluster as follows: `https://docs.emqx.io/en/broker/v4.3/getting-started/install.html#install-emq-x-in-docker-contain-a-simple-docker-compose-cluster`

It create (2)node of EMQX cluster in docker with the same port setting.

So, How can I using dashboard to works with any EMQX cluster?

**Comment by qzhuyan** [comment]
thanks for the update.

> EMQX in docker not yet link to the same docker network of MongoDB database -- then have some problem to CPU high load

I think I managed to reproduce the issue in Linux with a 4 core machine, I can see the cpu bumps from 0 to 14 by just enabling the `emqx_backend_mongodb` plugin without having a connectable mongodb. I will dig into it...

**Comment by qzhuyan** [comment]
> It create (2)node of EMQX cluster in docker with the same port setting.

> So, How can I using dashboard to works with any EMQX cluster?

You can manage any node in the same cluster through the dashboard.

Most pages has a dropdown that you can select the node you want to operate.

**Comment by seksity** [comment]
@qzhuyan Thank you.

As I test with docker-compose cluster, if I use example docker-compose as in:-
`https://docs.emqx.io/en/broker/v4.3/getting-started/install.html#install-emq-x-in-docker-contain-a-simple-docker-compose-cluster`

It not define ports in docker-compose, that if I build and run docker container from that docker-compose file, it will create docker container, BUT I CANNOT browse to EMQX dashboard at `http://localhost:18083`

So, I define the ports in docker-compose file as belows:-

> ports: 
>             - 1883:1883/tcp
>             - 8081:8081/tcp
>             - 8083:8083/tcp
>             - 8084:8084/tcp
>             - 8883:8883/tcp
>             - 18083:18083/tcp

Then, Re-Build and Run docker container form docker-compose file, That will create new docker container and CAN browse to EMQX dashboard.

**Comment by seksity** [comment]
> > It create (2)node of EMQX cluster in docker with the same port setting.
> 
> > So, How can I using dashboard to works with any EMQX cluster?
> 
> You can manage any node in the same cluster through the dashboard.
> 
> Most pages has a dropdown that you can select the node you want to operate.

I not found any information EMQX cluster in docker about port opened for browse to dashboard in the EMQ Docs. 
Refer to:-

> https://docs.emqx.io/en/broker/v4.3/getting-started/install.html#install-emq-x-in-docker-contain-a-simple-docker-compose-cluster

The docker containers both in cluster is open port 18083, but not yet defined ports to external docker world like:-

> Node #1
> `
> ports:
>         - 38083:18083/tcp
> `

I not sure do it need to defined port above or not?
