### ISSUE TITLE
RPC bridge: unable to setup correctly

### ISSUE THREAD

**Issue by phaabe** [emqx/emqx#5051]
Trying to activate an RPC bridge using the basic example from
https://docs.emqx.io/en/broker/v4.3/advanced/bridge.html#rpc-bridging-example

This error occurs:
```
$ emqx_ctl bridges list
RPC to emqx@127.0.0.1 error: {{{case_clause,'emqx@127.0.0.1'},
                               [{emqx_bridge_rpc,poke,1,
                                    [{file,"emqx_bridge_rpc.erl"},{line,97}]},
                                {emqx_bridge_rpc,start,1,
                                    [{file,"emqx_bridge_rpc.erl"},{line,43}]},
                                {emqx_bridge_connect,start,2,
                                    [{file,"emqx_bridge_connect.erl"},
                                     {line,55}]},
                                {emqx_bridge_worker,do_connect,1,
                                    [{file,"emqx_bridge_worker.erl"},
                                     {line,440}]},
                                {emqx_bridge_worker,connecting,1,
                                    [{file,"emqx_bridge_worker.erl"},
                                     {line,332}]},
                                {gen_statem,loop_state_callback,11,
                                    [{file,"gen_statem.erl"},{line,1166}]},
                                {proc_lib,init_p_do_apply,3,
                                    [{file,"proc_lib.erl"},{line,226}]}]},
                              {gen_statem,call,
                                  [<12326.21302.0>,status,infinity]}}
```
**Things checked**
- [x] `telnet <ip from second node> 5370`

Configuration : `emqx_bridge_mqtt.conf`
```
bridge.mqtt.<name>.address = <clustername>@<ip from second node>
bridge.mqtt.<name>.forwards = topic/#
bridge.mqtt.<name>.forward_mountpoint = bridge/<xyz>/${node}/
```

**Unclear**
- [ ]  must something be configured at the second node?
- [ ] how to proceed else?

**Comment by zmstone** [comment]
Hi @phaabe 
which exact version are you using ?
and could share what is configured here: `bridge.mqtt.<name>.address = <clustername>@<ip from second node>`

BTW: are you starting two nodes on one host?
if you are testing bridge to another node in a different host, the node name should not be 127.0.0.1

**Comment by phaabe** [comment]
EMQ X Broker 4.3.1 on both nodes. They are installed on different hosts.

About `bridge.mqtt.<name>.address = <clustername>@<ip from second node>`:
<clustername> is the same as configured in `/etc/emqx/emqx.conf`:
`cluster.name = <clustername>`

Is this correct?

**Comment by k32** [comment]
Hello,
Sorry for the long delay. How is `node.name` configured on your nodes? It looks like you're using the default setting:  `emqx@127.0.0.1` which is fine for a singleton node, but should be changed for the cluster. You need to configure this value to `<nodename>@<FWDN or external IP>` like described here https://docs.emqx.io/en/broker/v4.3/configuration/configuration.html#node-name
