### ISSUE TITLE
Unable to connect to mqtt over ws using helm charts in master

### ISSUE THREAD

**Issue by mm-e1** [emqx/emqx#5055]
**Environment**:

- EMQ X version: 4.3.0 (helm)

**What happened and what you expected to happen**:
I am unable to connect to mqtt over websockets when using the included [helm charts](https://github.com/emqx/emqx/tree/master/deploy/charts/emqx) in master

**How to reproduce it (as minimally and precisely as possible)**:
Install the helm chart and try to connect to mqtt over websockets. Connecting to mqtt over websockets does not work. In the pod logs, there are errors regarding `cowboy`. Sorry for not being able to provide logs.  

**Anything else we need to know?**:
If I change `version` and `appVersion` to `v4.1.1` in the [chart file](https://github.com/emqx/emqx/blob/master/deploy/charts/emqx/Chart.yaml), connecting to mqtt over websockets work. This leads me to believe there may be a bug in 4.3.0.

**Comment by qzhuyan** [comment]
@mm-e1 can you provide some logs? which client do you use?

**Comment by qzhuyan** [comment]
close due to inactiviey.
