### ISSUE TITLE
Mac OS  can't  start server

### ISSUE THREAD

**Issue by xleili** [emqx/emqx#5058]
**Please describe your problem in detail, if necessary, you can upload the log file through the attachment**:
系统：Mac OS
安装方法
1:用官网的的wget https://www.emqx.cn/downloads/broker/v4.3.3/emqx-macos-4.3.3-amd64.zip，unzip 后，用./bin/emqx console 启动报错{"Kernel pid terminated",application_controller,"{application_start_failure,kernel,{{shutdown,{failed_to_start_child,kernel_safe_sup,{on_load_function_failed,crypto}}},{kernel,start,[normal,[]]}}}"}
Kernel pid terminated (application_controller) ({application_start_failure,kernel,{{shutdown,{failed_to_start_child,kernel_safe_sup,{on_load_function_failed,crypto}}},{kernel,start,[normal,[]]}}})
，然后用【https://docs.emqx.cn/broker/v4.3/faq/error.html#openssl-版本不正确】其中Mac的描述$ cd /usr/local/Cellar/emqx/<version>/ 路径不存在，尝试直接用【$ brew install openssl@1.1】安装之后也报和之前一样的错。
2:用官网：
brew tap emqx/emqx
brew install emqx
emqx start
服务还是启不起来，报错如下【/opt/homebrew/bin/emqx: line 8: /usr/local/Cellar/emqx/4.2.0/releases/emqx_vars: No such file or directory】。

我用4.1.2的zip包也试过，还是启不起来

**Comment by zmstone** [comment]
> 我用4.1.2的zip包也试过，还是启不起来

4.1.2 也是提示类似这样的错误吗 “/opt/homebrew/bin/emqx: line 8: /usr/local/Cellar/emqx/4.2.0/releases/emqx_vars: No such file or directory” ？

**Comment by zmstone** [comment]
btw。4.1，4.2都比较老了，建议使用 4.3.3

**Comment by zmstone** [comment]
4.3.3 的 openssl 的问题正在调查

**Comment by zmstone** [comment]
could you run `brew config` command to find the root path for brew install dir,
and see if there is a openssl installation like this: `/usr/local/Cellar/openssl@1.1/1.1.1j`

**Comment by xleili** [comment]
> > 我用4.1.2的zip包也试过，还是启不起来
> 
> 4.1.2 也是提示类似这样的错误吗 “/opt/homebrew/bin/emqx: line 8: /usr/local/Cellar/emqx/4.2.0/releases/emqx_vars: No such file or directory” ？

这个版本我只装zip包的，所以没报这个错。

**Comment by xleili** [comment]
> could you run `brew config` command to find the root path for brew install dir,
> and see if there is a openssl installation like this: `/usr/local/Cellar/openssl@1.1/1.1.1j`

![image](https://user-images.githubusercontent.com/85657333/122902494-1286d400-d381-11eb-90f0-e6554fd23eb0.png)

**Comment by xleili** [comment]
应该是那个路径那？

**Comment by zmstone** [comment]
Could you check if you have openssl installed in `/opt/homebrew/Cellar`  and which version.

**Comment by zmstone** [comment]
and `brew info` command ?
mine for reference:
```
brew info openssl
openssl@1.1: stable 1.1.1k (bottled) [keg-only]
Cryptography and SSL/TLS Toolkit
https://openssl.org/
/usr/local/Cellar/openssl@1.1/1.1.1j (8,071 files, 18.5MB)
  Poured from bottle on 2021-03-01 at 17:01:44
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/openssl@1.1.rb
License: OpenSSL
==> Caveats
A CA file has been bootstrapped using certificates from the system
keychain. To add additional certificates, place .pem files in
  /usr/local/etc/openssl@1.1/certs

and run
  /usr/local/opt/openssl@1.1/bin/c_rehash

openssl@1.1 is keg-only, which means it was not symlinked into /usr/local,
because macOS provides LibreSSL.
```

**Comment by xleili** [comment]
thank you for your patient!
I have checked the openssl version by the command "brew info",this image is the information. 
![image](https://user-images.githubusercontent.com/85657333/123024572-d6e51c00-d40b-11eb-8f51-49fc186e000e.png)

[question1] is it necessary to keep all openssl path and version  same like you?
[question2]  if I want to instal emqx on Red Hat 4.8.5-44,which install package should use? or red-hat is still not supported?

**Comment by zmstone** [comment]
which macos version are you using ?
and could you share the output of this command: `sysctl -n machdep.cpu.brand_string`

**Comment by zmstone** [comment]
for question 2: to run emqx on redhat, you can try install RPM package for centos.
I am not quite sure which centos version is compatible to red hat 4.8.5 though

**Comment by xleili** [comment]
I think I found the issue，is there any difference between cloud and edge？ I installed cloud package for Mac. could you support some document links which  can make me know more about emqx.
![image](https://user-images.githubusercontent.com/85657333/123412593-562d4800-d5e4-11eb-8534-db56cde2c5f8.png)

**Comment by zmstone** [comment]
Edge is more lightweight comparing to cloud.
We unfortunately do not provide edge package for MacOS.
