### ISSUE TITLE
4.3.3: Shared subscription-The state is not released when the connection is disconnected

### ISSUE THREAD

**Issue by junerleer2** [emqx/emqx#5063]
**Environment**:

Official mirror
- EMQ X version (e.g. `emqx_ctl status`): 4.3.3
- Hardware configuration (e.g. `lscpu`):3x Node Cluster, 1x CPU, 2GB RAM per node

- OS (e.g. `cat /etc/os-release`): Docker Alpine 3.12.7
- Kernel (e.g. `uname -a`):--
- Erlang/OTP version (in case you build emqx from source code): --
- Others:--

**What happened and what you expected to happen**:
doc: https://docs.emqx.io/en/broker/v4.3/advanced/shared-subscriptions.html
topic : we use  Shared subscription, the topic is  $share/tas/sys/product/+/status
business server: 2 node,  subscribe the topic
problem: when we restart one of our business server,   use script to pressure test.  lost one-third of subscription data
analysy process：
1. restart emqx  cluster  no data lost
2. restart  business server, reproduce the problem
3. enter emqx cluster, we found  an invalid  share route
![image](https://user-images.githubusercontent.com/86290139/122916885-f76f9080-d38f-11eb-99bd-89fa34a0fcb7.png)

**How to reproduce it (as minimally and precisely as possible)**:
restart one of any share subscirbe client

**Anything else we need to know?**:

**Comment by zmstone** [comment]
hi @junerleer2 
are you using Clean Session = false? in the subscriber clients?

**Comment by junerleer2** [comment]
we  use  cleanSession:true

**Comment by junerleer2** [comment]
not only my business server can reproduce the issue, Other official client tool can reproduce too.
such as  “mqttx” "mqttfx"

**Comment by tigercl** [comment]
@junerleer2 I tried it on `MQTTX`, and it did not reproduce your problem, and in my impression,`MQTT.fx` does not support shared subscriptions.

**Comment by zmstone** [comment]
Hi @junerleer2 
you mentioned you have 2 nodes cluster?
Could you elaborate why there are 3 different IPs in the screenshot ?

**Comment by zmstone** [comment]
> Hi @junerleer2
> you mentioned you have 2 nodes cluster?
> Could you elaborate why there are 3 different IPs in the screenshot ?

sorry, never mind, it's 3x nodes.

**Comment by zmstone** [comment]
> when we restart one of our business server, use script to pressure test. 

does this happen only during the stress test ?
in which case it might be due to high load causing a delay in unsubscribe.

**Comment by tigercl** [comment]
Due to the previous incorrect implementation, when the same client establishes multiple shared subscriptions, it can only cancel the first subscription correctly, and the remaining shared subscriptions will not be cleared correctly. These ghost subscriptions are the cause of message loss.

We fixed this problem in [emqx#5098](https://github.com/emqx/emqx/pull/5098) and released 4.3.5 and 4.2.13 versions.
