### ISSUE TITLE
Internal error when creating a user through the API with Mnesia

### ISSUE THREAD

**Issue by victorct-pronto** [emqx/emqx#5079]
**Environment**:

- EMQ X version (e.g. `emqx_ctl status`): 4.3.4
- Hardware configuration (e.g. `lscpu`): 
```
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
Address sizes:                   46 bits physical, 48 bits virtual
CPU(s):                          2
On-line CPU(s) list:             0,1
Thread(s) per core:              2
Core(s) per socket:              1
Socket(s):                       1
NUMA node(s):                    1
Vendor ID:                       GenuineIntel
CPU family:                      6
Model:                           85
Model name:                      Intel(R) Xeon(R) Platinum 8259CL CPU @ 2.50GHz
Stepping:                        7
CPU MHz:                         2499.998
BogoMIPS:                        4999.99
Hypervisor vendor:               KVM
Virtualization type:             full
L1d cache:                       32 KiB
L1i cache:                       32 KiB
L2 cache:                        1 MiB
L3 cache:                        35.8 MiB
NUMA node0 CPU(s):               0,1
Vulnerability Itlb multihit:     KVM: Vulnerable
Vulnerability L1tf:              Mitigation; PTE Inversion
Vulnerability Mds:               Vulnerable: Clear CPU buffers attempted, no microcode; SMT Host state unknown
Vulnerability Meltdown:          Mitigation; PTI
Vulnerability Spec store bypass: Vulnerable
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Full generic retpoline, STIBP disabled, RSB filling
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx pdpe1gb rdtscp l
                                 m constant_tsc rep_good nopl xtopology nonstop_tsc cpuid tsc_known_freq pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movb
                                 e popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch invpcid_single pti fsgsbase tsc_adjust b
                                 mi1 avx2 smep bmi2 erms invpcid mpx avx512f avx512dq rdseed adx smap clflushopt clwb avx512cd avx512bw avx512vl xsaveopt xsavec xge
                                 tbv1 xsaves ida arat pku ospke
```

- OS (e.g. `cat /etc/os-release`):
```
NAME="Ubuntu"
VERSION="20.04.2 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.2 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```
- Kernel (e.g. `uname -a`):

`Linux ip-XXXXX 5.4.0-1045-aws #47-Ubuntu SMP Tue Apr 13 07:02:25 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`

**What happened and what you expected to happen**:

I loaded the mnesia plugin, and when creating a user following the [tutorial](https://docs.emqx.io/en/broker/v4.3/advanced/auth-mnesia.html#authentication-rules) (which the url is wrong, the one that appears on the dashboard is /api/v4/auth_username  not /api/v4/auth_user) it gives an internal error:

2021-06-23T18:52:23.367145+00:00 [error] POST /api/v4/auth_username error: function_clause, stacktrace:, [{emqx_http_lib,uri_decode,[undefined],[{file,"emqx_http_lib.erl"},{line,44}]},{emqx_auth_mnesia_api,do_add_username,1,[{file,"emqx_auth_mnesia_api.erl"},{line,192}]},{emqx_auth_mnesia_api,add_username,2,[{file,"emqx_auth_mnesia_api.erl"},{line,178}]},{minirest_handler,dispatch,2,[{file,"minirest_handler.erl"},{line,84}]},{minirest,handle_request,2,[{file,"minirest.erl"},{line,116}]},{minirest,init,2,[{file,"minirest.erl"},{line,108}]},{cowboy_handler,execute,2,[{file,"cowboy_handler.erl"},{line,41}]},{cowboy_stream_h,execute,3,[{file,"cowboy_stream_h.erl"},{line,320}]},{cowboy_stream_h,request_process,3,[{file,"cowboy_stream_h.erl"},{line,302}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,226}]}]

**How to reproduce it (as minimally and precisely as possible)**:

Install a cluster, and activate the mnesia plugin for authentication, then try to create a user through the API.

**Anything else we need to know?**:

**Comment by k32** [comment]
Hi! 
Thanks for the bug report. It looks like your request is missing mandatory `"username"' parameter. 
Crashing with an internal error is not great, of course. We are working on migrating EMQX REST API to swagger, which hopefully will result in meaningful error messages for all requests.

**Comment by k32** [comment]
P.S. As for wrong URL in the documentation, it should be fixed now.

**Comment by qzhuyan** [comment]
@victorct-pronto Have your tried with adding the `username` in request body?

**Comment by k32** [comment]
Closing for now. Please feel free to reopen if the provided solution doesn't work for you.
