### ISSUE TITLE
get metrics of particular topic 

### ISSUE THREAD

**Issue by iammehrabalam** [emqx/emqx#508]
emqttd giving me metrics of all topics combine but I want to know the metrics of the **particular topic**.

metrics like
- qos0 sent
- qos0 received
- qos1 received
- qos1 sent

etc..

**Comment by erylee** [comment]
Hi @iammehrabalam, plan to support this feature by a management plugin.

**Comment by iammehrabalam** [comment]
@erylee   
Is it possible to store acknowledgement of subscriber it sent after receiving a message from the broker?
I have a use case to know how many subscribers successfully receive the message from broker.

**Comment by erylee** [comment]
@iammehrabalam, please check the 'message.acked' hook in https://github.com/emqtt/emqttd_plugin_template/blob/master/src/emqttd_plugin_template.erl

**Comment by DataEngg** [comment]
@erylee 
I am new to MQTT, can you tell me how would I use hook to get the information about ack message via using any client library or by using something else..

**Comment by anujbansal** [comment]
@erylee I saw the code that you pointed. Is there a way we could trigger a Python method or some DB trigger so that we are able to capture the acknowledgement in our DB?

**Comment by deepaksood619** [comment]
@Gilbert-Wong When is this going to be implemented, are there any plans for the same. Or are there any workarounds to achieve this using 3rd party plugins, either in any collection agents like telegraf or prometheus?

**Comment by Gilbert-Wong** [comment]
Sorry, @deepaksood619 . After discussion of our team, we decide not to implement this feature in the foreseeable future.

**Comment by HJianBo** [comment]
Hello guys, the metrics of a particular topic are included in v4.1.0
