### ISSUE TITLE
Please allow creating dashboard users via configuration file

### ISSUE THREAD

**Issue by JohnRoesler** [emqx/emqx#5080]
**What would you like to be added/modified**:

Every time i restart my emqx kubernetes cluster I have to login first as admin user and then create a viewer only user. I would like to have that in configuration so that the cluster starts with it.

**Why is this needed**:

To removal a painful manual task when deploying a new version of emqx.

**Comment by k32** [comment]
Hello,
Have you tried data import API? https://docs.emqx.io/en/broker/v4.3/advanced/data-import-and-export.html#example
The import file includes the information about users.

**Comment by JohnRoesler** [comment]
@k32 i will try that, ty

**Comment by k32** [comment]
Please feel free to reopen the issue if this approach doesn't work for you.
