### ISSUE TITLE
Is there a way to circumvent the plaintext transmission of api/v3/auth interface parameters?

### ISSUE THREAD

**Issue by tanglifeng** [emqx/emqx#5088]
emqx 登陆dashboard后台时候，在输入账号，密码调用 api/v3/auth 接口，参数直接明文传输存在风险，是否可以使用密文传输？

![emqx-err](https://user-images.githubusercontent.com/22926447/123363420-0c713d00-d5a5-11eb-88f3-6da0f2434b83.png)

**Comment by tigercl** [comment]
@tanglifeng It is recommended to use https.

**Comment by qzhuyan** [comment]
I think this is a bug, EMQX should never transmit secrets in plaintext.

@tanglifeng thanks for reporting.

**Comment by zmstone** [comment]
use https!
