### ISSUE TITLE
Which version of the coap plugin can be used normally

### ISSUE THREAD

**Issue by 601950157** [emqx/emqx#5089]
在使用emq3\emq4.0.0的过程中，coap插件无法正常工作，请问哪个版本的EMQ的coap插件可以正常使用

**Comment by 601950157** [comment]
4.0.5版本的coap插件也同样无法正常工作

**Comment by tigercl** [comment]
@601950157 Sorry for late reply. It is recommended to use our latest stable version 4.3.4, and it is best to explain the specific error so that we can help you.
