### ISSUE TITLE
The number of connections can only reach 2000+, according to the official configuration file

### ISSUE THREAD

**Issue by mark630235** [emqx/emqx#5093]
#### Environment

- OS: 
- Erlang/OTP: 
- EMQ: 

#### Description
按照系统调优配置的系统
https://docs.emqx.cn/broker/v4.0/tutorial/tune.html#linux-%E6%93%8D%E4%BD%9C%E7%B3%BB%E7%BB%9F%E5%8F%82%E6%95%B0

目前只能达到两千的量
![image](https://user-images.githubusercontent.com/17892109/123383181-74378000-d5c5-11eb-87bd-6355b7a40f72.png)

可能是那里有问题？？

**Comment by mark630235** [comment]
配置文件基本是按照官方提供的配置的

**Comment by qzhuyan** [comment]
Is the emqx running in docker?

**Comment by mark630235** [comment]
no

> Is the emqx running in docker?

no , running in Ecs

**Comment by qzhuyan** [comment]
Are you testing the number of connections with a loadgen or? could that be the fd limit from loadgen?

also find the pid of emqx then check the limit of that pid by 

cat /proc/58001/limits  #where 58001 is the pid of emqx

**Comment by mark630235** [comment]
> Are you testing the number of connections with a loadgen or? could that be the fd limit from loadgen?
> 
> also find the pid of emqx then check the limit of that pid by
> 
> `cat /proc/58001/limits` #where 58001 is the pid of emqx

![image](https://user-images.githubusercontent.com/17892109/123732177-14461f80-d8cc-11eb-859e-1387c413ec74.png)

**Comment by mark630235** [comment]
> Is the emqx running in docker?
> 
> Are you testing the number of connections with a loadgen or? could that be the fd limit from loadgen?

I test by emqtt_bench in []( https://docs.emqx.cn/broker/v4.3/tutorial/benchmark.html)

**Comment by mark630235** [comment]
> Is the emqx running in docker?
> 
> Are you testing the number of connections with a loadgen or? could that be the fd limit from loadgen?

I test it by  emqtt_bench ; https://docs.emqx.cn/broker/v4.3/tutorial/benchmark.html

**Comment by mark630235** [comment]
> > Is the emqx running in docker?
> > Are you testing the number of connections with a loadgen or? could that be the fd limit from loadgen?
> 
> I test it by emqtt_bench ; https://docs.emqx.cn/broker/v4.3/tutorial/benchmark.html

![image](https://user-images.githubusercontent.com/17892109/123732709-e31a1f00-d8cc-11eb-81f6-7425fb34003c.png)

**Comment by qzhuyan** [comment]
Have you tuned the machine which runs the emqtt bench as well for the os parameters? 

Another thing is, When you say you run emqx in ECS is it AWS ECS? I know some cloud provider limits the number of connections by the size of the instances/container(but still 2000 is too low), worth to try to run emqtt bench on same host against localhost so that it won't be captured in cloud env.

**Comment by mark630235** [comment]
> Have you tuned the machine which runs the emqtt bench as well for the os parameters?
> 
> Another thing is, When you say you run emqx in ECS is it AWS ECS? I know some cloud provider limits the number of connections by the size of the instances/container(but still 2000 is too low), worth to try to run emqtt bench on same host against localhost so that it won't be captured in cloud env.

I am running EMQX 4.0.3 on AliCloud ECS.

**Comment by qzhuyan** [comment]
@manifest any updates? Have you checked the tunning of emqtt bench?

**Comment by qzhuyan** [comment]
close due to inactive.
