### ISSUE TITLE
EMQX_AUTH__HTTP__AUTH_REQ is working in 4.2 version and not working in 4.3

### ISSUE THREAD

**Issue by shahmuratov** [emqx/emqx#5101]
**Environment**:

- EMQ X version (e.g. `emqx_ctl status`): 4.2.12 and 4.3.4
- Hardware configuration (e.g. `lscpu`): docker container
- OS (e.g. `cat /etc/os-release`): docker on windows
- Kernel (e.g. `uname -a`): -
- Erlang/OTP version (in case you build emqx from source code): 
- Others:

**What happened and what you expected to happen**:
I've spinned up docker image with latest tag and specifically with all versions from 4.3.1 to 4.3.4. I've provided env var EMQX_AUTH__HTTP__AUTH_REQ=http://host.docker.internal:8991/Callback/Emq/Auth . In logs I don't see this env var recognized and when I try to do request it is trying to connect to default url.
If I use 4.2.12 version everything work fine.

**How to reproduce it (as minimally and precisely as possible)**:
```services:
    emqx:
      image: emqx/emqx:4.3.4
      ports:
        - 1883:1883
        - 8083:8083
        - 18083:18083
      environment:
        - EMQX_NAME=emqx
        - EMQX_ALLOW_ANONYMOUS=false
        - EMQX_LOADED_PLUGINS=emqx_recon,emqx_retainer,emqx_management,emqx_dashboard,emqx_auth_http
        - EMQX_AUTH__HTTP__AUTH_REQ=http://host.docker.internal:8991/Callback/Emq/Auth
        - EMQX_AUTH__HTTP__AUTH_REQ__PARAMS=clientid=%c,password=%P
        - EMQX_AUTH__HTTP__AUTH_REQ__METHOD=post
        - EMQX_AUTH__HTTP__SUPER_REQ=http://host.docker.internal:8991/Callback/Emq/SuperUser
        - EMQX_AUTH__HTTP__SUPER_REQ__PARAMS=clientid=%c
        - EMQX_AUTH__HTTP__SUPER_REQ__METHOD=get
        - EMQX_AUTH__HTTP__ACL_REQ=http://host.docker.internal:8991/Callback/Emq/Acl
        - EMQX_AUTH__HTTP__ACL_REQ__PARAMS=access=%A,clientid=%c,topic=%t
        - EMQX_AUTH__HTTP__ACL_REQ__METHOD=get
  ```   

use this docker-compose.yaml

**Anything else we need to know?**:
-

**Comment by tigercl** [comment]
@shahmuratov Sorry, this is because the name of the configuration item has changed, please refer to: [EMQ X Auth HTTP Configuration](https://github.com/emqx/emqx/blob/main-v4.3/apps/emqx_auth_http/etc/emqx_auth_http.conf).
