### ISSUE TITLE
EMQX_AUTH_HTTP plugin response custom info to client

### ISSUE THREAD

**Issue by young138120** [emqx/emqx#5107]
Environment: emqx broker 4.3.3 
same as the title
client a connect to server，if success ，the custom auth server want to reponse some custom info by user properties。client a will get the custom to do some thing

so ，how can i do this feature

**Comment by yangjwInRiver** [comment]
by the way，
can i use http-auth plugin to authenticate and redis-auth to acl

**Comment by tigercl** [comment]
@young138120 This is a great idea, but unfortunately we do not yet support this feature. I will include him in our demand pool. Would it be convenient for you to disclose more details so that we can discuss this demand internally.

**Comment by young138120** [comment]
it is bad news
so can i have other way to get the custom data in the version？

**Comment by tigercl** [comment]
@young138120 Sorry, we do not currently support.

**Comment by qzhuyan** [comment]
> it is bad news
> so can i have other way to get the custom data in the version？

can you show us exactly what do you want to achive to help us understand the requirement? 
A restapi req/response flow chart would be great!

**Comment by young138120** [comment]
> > it is bad news
> > so can i have other way to get the custom data in the version？
> 
> @young138120
> can you show us exactly what do you want to achive to help us understand the requirement?
> A restapi req/response flow chart would be great!

![image](https://user-images.githubusercontent.com/11519151/126761367-1b2ad47a-805b-4a0b-a5db-51070f7ae9ce.png)

connack can not support payload。
so what is better save custom data？

**Comment by zmstone** [comment]
Hi @young138120 

I'm afraid passing user data via auth is something we will not implement.
