### ISSUE TITLE
WebHook Plugin parameter problem

### ISSUE THREAD

**Issue by young138120** [emqx/emqx#5120]
**Environment**:

- EMQ X version (e.g. `emqx_ctl status`): 4.3.3
- Hardware configuration (e.g. `lscpu`): 3x Node in k8s
- OS (e.g. `cat /etc/os-release`): ubuntu 16.04.6 LTS 
- Kernel (e.g. `uname -a`):--
- Erlang/OTP version (in case you build emqx from source code): --
- Others:--

**What happened and what you expected to happen**:
i use webhook plugin to accept connected event. connected_at param is int type in doc(https://docs.emqx.cn/broker/v4.3/advanced/webhook.html#webhook-%E4%BA%8B%E4%BB%B6%E5%8F%82%E6%95%B0),
but i get the exception:
 nested exception is com.fasterxml.jackson.databind.JsonMappingException: Numeric value (1624870060249) out of range of int
 at [Source: (PushbackInputStream); line: 1, column: 167] (through reference chain: com.yitu.ispd.utils.mqtt.webhook.dto.WebHookActionDTO["connected_at"])]

now i change to long，it is work。
is it a bug？or doc not update ？

**Comment by tigercl** [comment]
@young138120 Sorry, the type in the document refers to the json type rather than the data type in the code, but there is indeed an error in the document. The time unit of connected_at is actually not seconds but milliseconds.

**Comment by young138120** [comment]
ok， get it
