### ISSUE TITLE
brew services start not working

### ISSUE THREAD

**Issue by stevesuh** [emqx/emqx#5127]
**Environment**:

- EMQ X version (e.g. `emqx_ctl status`): 4.2.0
- Hardware configuration (e.g. `lscpu`):
- OS (e.g. `cat /etc/os-release`): OSX 11.4 Big Sur
- Kernel (e.g. `uname -a`):
- Erlang/OTP version (in case you build emqx from source code): 
- Others:

**What happened and what you expected to happen**:
```
daniel.stone@CFAL-C02DC2D0MD6P update-cdn % brew services start emqx/emqx/emqx 
Bootstrap failed: 5: Input/output error
Error: Failure while executing; `/bin/launchctl bootstrap gui/501 /Users/daniel.stone/Library/LaunchAgents/homebrew.mxcl.emqx.plist` exited with 5.
```
Running it as sudo causes it to appear to succeed, but the service is never started.

**How to reproduce it (as minimally and precisely as possible)**:
Run the brew services command above.

**Anything else we need to know?**:
emqx start works.

**Comment by Rory-Z** [comment]
Hi，@stevesuh 
Sorry, we don't support brew services start at this time
Maybe you can contribute PR to us on [this project](https://github.com/emqx/homebrew-emqx)
