### ISSUE TITLE
Rule Engine: undefined payload when the action type is republish

### ISSUE THREAD

**Issue by xigua88-66** [emqx/emqx#5130]
**Environment**:

- EMQ X version:  V4.2.9
- Hardware configuration: x86_64 64bit
        
![image](https://user-images.githubusercontent.com/54090607/123758545-9c8aeb80-d8f1-11eb-818a-dc35d56f9734.png)

- OS: CentOS 7
- Kernel : Linux bigdata01 3.10.0-957.el7.x86_64 #1 SMP Thu Nov 8 23:39:32 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

**What happened and what you expected to happen**:
1.I try to use SQL rules to trigger an event when the gpu_util value is greater than the limit value, and send a message to a new topic
2.But when the event is triggered, the payload received by the new topic is undefined

**SQL Rule**：
    `FOREACH
  payload.detail
DO
    clientid,
    item.mem as mem,
    item.gpu_util as gpu_util
INCASE
    item.gpu_util >= 20
FROM
  "bridge/env/inside/GPU/#"`
image:
    
![image](https://user-images.githubusercontent.com/54090607/123759501-89c4e680-d8f2-11eb-8bdd-b0a273e1493b.png)

**MQTT Payload**:
    `{
	"count": 2,
	"detail": [{
		"mem": 24268,
		"gpu_util": 48,
		"version": 11010,
		"mem_usage": 6317,
		"model_type": "GeForce RTX 3090"
	}, {
		"mem": 24268,
		"gpu_util": 0,
		"version": 11010,
		"mem_usage": 2,
		"model_type": "GeForce RTX 3090"
	}],
	"create_time": "2021-06-29 15:53:24"
}`
image:
    
![image](https://user-images.githubusercontent.com/54090607/123759575-9a755c80-d8f2-11eb-942c-86fe0ff9c59f.png)
.
**Subscribed payload**：
![image](https://user-images.githubusercontent.com/54090607/123759787-cee91880-d8f2-11eb-9b6b-2f3c6c79ff84.png)

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Comment by xigua88-66** [comment]
**Action Type**:
![image](https://user-images.githubusercontent.com/54090607/123761662-9ea27980-d8f4-11eb-98e5-f898d7b08eea.png)
![image](https://user-images.githubusercontent.com/54090607/123761695-a82be180-d8f4-11eb-8342-eac5b72bffa3.png)

**Comment by terry-xiaoyu** [comment]
The `payload_tmpl` parameter of the `republish` action is set to `${payload}`, but there's no such field in the input of the action.

All the available fields in your example are: `clientid, mem, gup_util`.

**Comment by xigua88-66** [comment]
Get！
Thanks！

**Comment by qzhuyan** [comment]
@xigua88-66 I think your issue is resolved, I close the issue then.

Feel free to reopen it in case you need more help.
