### ISSUE TITLE
My MQTT broker does not allow me to use wildcard #

### ISSUE THREAD

**Issue by VeraMasiasMiguel** [emqx/emqx#5164]
Dear, currently I have installed MQTT Broker version 4.3.5 on CentOS 7.
When I finished the installation, I entered the dashboard-> Tool-> Websocket, I connected to the broker, and then I subscribed to the topic "testtopic / #" and I was disconnected from the Broker and it showed me the following message "Connect failed on XXX.XXX.XXX.XXX: 8030 ".

I repeated the connection and subscribed to another topic without a wildcard, and it was possible to subscribe normally.
I went to the emqx.conf file and modified that the following options.
mqtt.wildcard_subscription = true
zone.external.wildcard_subscription = true
restart broker with "systemctl restart emqx" but it doesn't work.

I tried enabling acl in the acl.conf file which has only the following lines:
{allow, all, subscribe, ["$ SYS / #", {eq, "#"}]}.
{allow, all}.
In the emqx.conf file enable the following:
acl_nomatch = deny
acl_file = /etc/emqx/acl.conf
Restart the Broker, and the results were not satisfactory.

My 4.3.5 installation does not allow me to subscribe to wildcards. Would you kindly tell me that I need to modify for the wildcard subscription to work?
Thank you. Greetings.

**Comment by VeraMasiasMiguel** [comment]
Hello, the result is

sudo emqx_ctl listeners
mqtt:ssl:external
  listen_on       : 0.0.0.0:8883
  acceptors       : 16
  max_conns       : 102400
  current_conn    : 0
  shutdown_count  : [{function_clause,1},{ssl_closed,5},{ssl_upgrade_timeout,6}]
mqtt:tcp:external
  listen_on       : 0.0.0.0:1883
  acceptors       : 8
  max_conns       : 1024000
  current_conn    : 2
  shutdown_count  : [{function_clause,9},{takeovered,2},{tcp_closed,7},{protocol_error,1}]
mqtt:tcp:internal
  listen_on       : 127.0.0.1:11883
  acceptors       : 4
  max_conns       : 1024000
  current_conn    : 0
  shutdown_count  : []
http:dashboard
  listen_on       : 0.0.0.0:18083
  acceptors       : 4
  max_conns       : 512
  current_conn    : 0
  shutdown_count  : []
http:management
  listen_on       : 0.0.0.0:8081
  acceptors       : 2
  max_conns       : 512
  current_conn    : 0
  shutdown_count  : []
mqtt:ws:external
  listen_on       : 0.0.0.0:8083
  acceptors       : 4
  max_conns       : 102400
  current_conn    : 1
  shutdown_count  : []
mqtt:wss:external
  listen_on       : 0.0.0.0:8084
  acceptors       : 4
  max_conns       : 16
  current_conn    : 0
  shutdown_count  : []

**Comment by k32** [comment]
Hello,

Thanks for the information. It looks like the problem that you're seeing is not related to the authorization. Your client tries to connect to port 8030:

>  I was disconnected from the Broker and it showed me the following message "Connect failed on XXX.XXX.XXX.XXX: 8030 ".

But EMQ X doesn't have any listeners configured on this port. Please specify the correct port in the client.

**Comment by VeraMasiasMiguel** [comment]
Hello, yes it connects

![image](https://user-images.githubusercontent.com/54821471/124552678-7ab1cd00-ddf9-11eb-841a-3091fb19a6ea.png)

As I mention in the title of the problem. I subscribe to the Topic with wildcard, and it disconnects.


![image](https://user-images.githubusercontent.com/54821471/124553197-13484d00-ddfa-11eb-8df0-ec3b22b969a1.png)

If I subscribe to a topic without a wildcard, this one works.
![image](https://user-images.githubusercontent.com/54821471/124553253-23602c80-ddfa-11eb-9740-d5d4e924e1ed.png)

I can't use wildcards, please help  @k32

**Comment by k32** [comment]
Thanks for the clarification. I tried to reproduce the problem with the same acl.conf, but without success. 

Do you enable other authentication/authorization plugins, such as `emqx_auth_mnesia`?

**Comment by VeraMasiasMiguel** [comment]
Hello, the emqx_auth_mnesia plugin I have stopped.

![image](https://user-images.githubusercontent.com/54821471/124649659-648a2800-de5e-11eb-9df9-de0ac28aaa2a.png)

Enable the emqx_auth_mnesia plugin the results were not satisfactory.

Only these plugins I have working

![image](https://user-images.githubusercontent.com/54821471/124649973-ce0a3680-de5e-11eb-9261-350c47e4cadd.png)

These modules I have enabled

![image](https://user-images.githubusercontent.com/54821471/124650163-09a50080-de5f-11eb-99e2-57627e4ace4e.png)

I remain attentive to any information requested.

**Comment by WatsonMing** [comment]
I had the same problem

**Comment by k32** [comment]
Sorry, I still can't reproduce the problem. Could you reproduce the error again, with debug logs enabled (`log.level = debug` in emqx.conf), and send the screenshot where I can see all the fields highlighted in red simultaneously (you can obscure the hostnames if you wish, but please show the ports).

Also, please attach the latest `emqx.log` file.
![Screenshot_20210707_152017](https://user-images.githubusercontent.com/10274441/124766990-b488ed80-df37-11eb-863c-60c9bcc2f47d.png)

**Comment by VeraMasiasMiguel** [comment]
Hello
Edit the emqx.conf file
![image](https://user-images.githubusercontent.com/54821471/124773104-3eb65f00-df02-11eb-89a9-cabcb661b900.png)

Restart the Broker
![image](https://user-images.githubusercontent.com/54821471/124773009-29d9cb80-df02-11eb-809b-fa3cef021494.png)

I made the connection, and I subscribed to the wildcard topic.
Connection failed.
![image](https://user-images.githubusercontent.com/54821471/124772309-8983a700-df01-11eb-9f0e-5f28c2244fdb.png)

I logged in, and subscribed to topic without wildcard.
The connection worked.
![image](https://user-images.githubusercontent.com/54821471/124774567-88537980-df03-11eb-92f3-75f4c9e255db.png)

I attach the .log file
[emqx_log.txt](https://github.com/emqx/emqx/files/6777845/emqx_log.txt)

**Comment by WatsonMing** [comment]
I can't find the problem, but the docker method can be used

**Comment by k32** [comment]
Hello,
Thanks for the logs, I am studying them.

**Comment by k32** [comment]
@VeraMasiasMiguel Thanks for your patience. This error looks similar to https://github.com/emqx/emqx/issues/4704. Have you performed an upgrade from 4.2 to 4.3.5?
