### ISSUE TITLE
Passwords printed in logs in plaintext

### ISSUE THREAD

**Issue by umeat** [emqx/emqx#5179]
I created an issue in the plugin but it doesn't seem to have been seen - and since it's in the EMQX logs it's relevant to this project as well.

https://github.com/emqx/emqx-auth-http/issues/262

**Comment by tigercl** [comment]
@umeat We are planning to improve this part. Regarding the timeout problem, the possible reasons are: HTTP Server response is slow, the network is poor, and the request volume is too large.
