### ISSUE TITLE
why changing password does not need old password?

### ISSUE THREAD

**Issue by mainulquraishi** [emqx/emqx#5184]
I was reading the authentication (using internal data sources) procedures (Username / client ID / mnesia). In each of these procedures, it is mentioned that the user's password can be changed with an HTTP PUT request using only the user name. That mean's anybody who knows my user name can change my password and get access. Also, even the user names can be found by `GET api/v4/auth_username` command. 

Am I missing something or these are the weakness of these procedures?

**Comment by DDDHuang** [comment]
API use [Basic access authentication](https://en.wikipedia.org/wiki/Basic_access_authentication). Change password will delivery username & password(old) in header.
