### ISSUE TITLE
False to Build EMQ X Broker from github on Windows

### ISSUE THREAD

**Issue by anhln8x** [emqx/emqx#5186]
**Environment**:

- EMQ X version (e.g. `emqx_ctl status`):  https://github.com/emqx/emqx.git
- Hardware configuration (e.g. `lscpu`): Intel(R) Xeon(R) 64 bit
- OS (e.g. `cat /etc/os-release`): Windows 10 Pro
- Kernel (e.g. `uname -a`): Windows NT kernel
- Erlang/OTP version (in case you build emqx from source code): Erlang/OTP 24
- Others:  Bash (Cygwin), JDK-16.0.1

**What happened and what you expected to happen**:

With installation documentation: https://github.com/emqx/emqx/blob/master/Windows.md

I followed installation documentation exactly.

I tried to rebuild EMQ X source code many times with command: make 

I always get this error:
_Analyzing applications...
...
Compiling emqx_exhook
[relup_helper] running gen_appups
operable program or batch file.not recognized as an internal or external command,
...
←[1mUncaught error in rebar_core. Run with DIAGNOSTIC=1 to see stacktrace or consult rebar3.crashdump
←[0mWhen submitting a bug report, please include the output of `rebar3 report "your command"`
make: *** [Makefile:78: emqx] Error 1_

Check rebar3.crashdump:

Error: {badmatch,{error,enoent}}
[{rlx_assemble,create_release,3,
               [{file,"/src/_build/default/lib/relx/src/rlx_assemble.erl"},
                {line,266}]},
 {rlx_assemble,do,2,
               [{file,"/src/_build/default/lib/relx/src/rlx_assemble.erl"},
                {line,20}]},
 {relx,build_release_,3,
       [{file,"/src/_build/default/lib/relx/src/relx.erl"},{line,171}]},
 {relx,build_release,3,
       [{file,"/src/_build/default/lib/relx/src/relx.erl"},{line,77}]},
 {rebar_relx,do,2,[{file,"rebar_relx.erl"},{line,67}]},
 {rebar_core,do,2,[{file,"rebar_core.erl"},{line,155}]},
 {rebar_prv_do,do_task,5,[{file,"rebar_prv_do.erl"},{line,75}]},
 {rebar_core,do,2,[{file,"rebar_core.erl"},{line,155}]},
 {rebar_prv_do,do_task,5,[{file,"rebar_prv_do.erl"},{line,75}]},
 {rebar_core,do,2,[{file,"rebar_core.erl"},{line,155}]},
 {rebar3,run_aux,2,[{file,"rebar3.erl"},{line,181}]},
 {rebar3,main,1,[{file,"rebar3.erl"},{line,66}]},
 {escript,run,2,[{file,"escript.erl"},{line,750}]},
 {escript,start,1,[{file,"escript.erl"},{line,277}]},
 {init,start_em,1,[{file,"init.erl"},{line,1190}]},
 {init,do_boot,3,[{file,"init.erl"},{line,888}]}]

**How to reproduce it (as minimally and precisely as possible)**:

- Install Visual Studio Community 2019
- Config Path environment
- Install JDK-16.0.1
- Install Erlang/OTP 24
- Install Cygwin
- Install Scoop
- Install Tools: git curl make jq zip unzip
- Clone the repo: git clone https://github.com/emqx/emqx.git
- Start CMD or Powershell for VS 2019 (administrator)
- Execute vcvarsall.bat x86_amd64 to load environment variables
- Change to emqx directory and execute make
- Run: Make

**Anything else we need to know?**:

Full console: 
[emqx.txt](https://github.com/emqx/emqx/files/6781888/emqx.txt)

Please help me find the problem, thanks

**Comment by zmstone** [comment]
Hi.
The latest master branch is not quite stable yet on otp 24.
Could you try it on otp23

**Comment by anhln8x** [comment]
Hi @zmstone 

I removed otp 24 and installed otp 23.2 , try clone the repo and make. But i still get the same error.

Compiling emqx_modules
Compiling emqx_bridge_mqtt
[relup_helper] running gen_appups
operable program or batch file.not recognized as an internal or external command,
...
←[1mUncaught error in rebar_core. Run with DIAGNOSTIC=1 to see stacktrace or consult rebar3.crashdump
←[0mWhen submitting a bug report, please include the output of `rebar3 report "your command"`
make: *** [Makefile:78: emqx] Error 1

Did I do something wrong?

Thanks

**Comment by zmstone** [comment]
hi @anhln8x are you building `master` branch ? 
I'll try to reproduce it and get back to you soon.
in the mean time, you can try to build `main-v4.3` branch which is currently our stable release branch.

**Comment by anhln8x** [comment]
Hi @zmstone 

That's right, i'm building the master branch, i will try again with main-v4.3 now.

Thankyou!
