### ISSUE TITLE
How does a client subscribe to the presence of another client?

### ISSUE THREAD

**Issue by zhengguoxin** [emqx/emqx#5190]
emq上的设备上线、下线状态，目前可以通过http api由客户端轮询获取，请问客户端如何通过mqtt订阅emq上设备的状态呢？谢谢！

**Comment by terry-xiaoyu** [comment]
Here are the sys topics that will be published when a client connected or disconnected:
https://docs.emqx.cn/broker/v4.3/advanced/system-topic.html#客户端上下线事件
