### ISSUE TITLE
Use of variables in http auth request headers

### ISSUE THREAD

**Issue by AlbinDavid** [emqx/emqx#5199]
**etc/plugins/emqx_auth_http.conf**

I'm trying to use token-based authentication. In which I need to send the token in headers. I tried using the values as used in req.params
```
auth.http.auth_req.params = clientid=%c,username=%u,password=%P    **--> using this as reference**                               
1.auth.http.auth_req.headers.access-token =%u (sending the token in username)
2.auth.http.auth_req.headers.access-token =username=%u
3.auth.http.auth_req.headers.access-token =auth.http.auth_req.params.username
```

But in the server the header (access-token) is just the string and the value is **not passed**

What is the correct way to pass the value in the headers?

**Comment by terry-xiaoyu** [comment]
What version of the emqx you are using?

**Comment by tigercl** [comment]
@AlbinDavid Currently we do not support the use of placeholders in HTTP Headers. Putting the authentication information in the HTTP Body cannot meet your needs?
