### ISSUE TITLE
about emqx_web_hook plugin

### ISSUE THREAD

**Issue by jiaqiubo** [emqx/emqx#5205]
When responding to the CLIENT_CONNECTED event using the EMQX_WEB_HOOK plug-in,
Call the HTTP API interface/API /v4/ MQTT /subscribe to subscribe the topic for the connected user
Returns {"message":"channel_not_found","code":112} at this point the user session should have been established

使用 emqx_web_hook 插件，响应 client_connected 事件时，
调用 HTTP API 接口的 /api/v4/mqtt/subscribe 为连接用户订阅主题
返回 {"message":"channel_not_found","code":112} 此时应该是用户 session 应已建立

**Comment by terry-xiaoyu** [comment]
Try the `/api/v4/mqtt/subscribe` API manually to see if it returns the same error as above.

**Comment by jiaqiubo** [comment]
If the session exists (connected or disconnected), i can subscribe normally.
So, whether the session was not created when the client.connected event was triggered.
What can I do about it.
