### ISSUE TITLE
Consider creating a new Git repository for the Helm chart

### ISSUE THREAD

**Issue by onedr0p** [emqx/emqx#5206]
**What would you like to be added/modified**:

I would like to see an [emqx/emqx-charts](https://github.com/emqx/emqx-charts) repository, using the [chart-releaser-action](https://github.com/helm/chart-releaser-action) github action you could host the charts on github releases.

**Why is this needed**:

The application and helm chart have different release cycles and could be decoupled.

**Comment by Rory-Z** [comment]
Hi，@onedr0p
Thank you for your idea, but when emqx is updated, it may not be compatible with previous helm charts, so the version of helm chart is updated with emqx, I think publish helm chart and emqx synchronously is good, which makes our release process simple
In addition, we have plans to develop emqx operator, emqx operator will replace emqx helm chart, emqx operator will have separate repositorie and release plans
