### ISSUE TITLE
Question emqx with node.js server ko

### ISSUE THREAD

**Issue by qiwalker** [emqx/emqx#5207]
hi

kindly advice
is it possible to use mini pc Minix z83 - 4 plus (windows10) for Emqx broker for handle 100 connection and node.js server ?

thanks

**Comment by k32** [comment]
Hello,

The resource footprint of a single connection in EMQ X is negligible, what actually matters is the amount of data transferred over the connections.

**Comment by qiwalker** [comment]
hi 
thx for promp reply
my node using pubsub and max buffer is 50
data publish data is MacAddress+temperature value

**Comment by qzhuyan** [comment]
@qiwalker you also need to consider the number of subscribers and publishers. 

>publish data is MacAddress+temperature value and data publish every 3 second
is it from one connection or from all the connections? 

BTW, we don't know what runs in your nodejs so we cannot estimate.
