### ISSUE TITLE
How do you SELECT on a topic that contains a specified sub-string using rule engine?

### ISSUE THREAD

**Issue by zhengguoxin** [emqx/emqx#5208]
比如topic是 abc 开头，或者中间含有 abc 的，要转发：

select * from '*abc*'

这样好像不行，请教如何解决，谢谢！！！！！！！！！！！！！

**Comment by terry-xiaoyu** [comment]
It can't select on partial of a topic, but you can select on the topic "#" and use `WHERE` to filter the topics, like:

```
select * from "#" WHERE regex_match(topic, '.*abc.*')
```

**Comment by terry-xiaoyu** [comment]
Please make sure asking questions in **English**, it should be explained in the github issue template.
