### ISSUE TITLE
emqx4.0.13 version, after disabling anonymous authentication or changing the port number, restarting will cause an error "syntax error"

### ISSUE THREAD

**Issue by ZhangLianda** [emqx/emqx#5210]
D:\ emqx\ bin>emqx restart
2021-07-12T07:58:03.125000+08:00 [error] Syntax error in d:/emqx/data/configs/app.2021.07.12.07.58.02. conf after line 1 column 1, parsing incomplete

**Comment by qzhuyan** [comment]
@ZhangLianda how do you change the config? via env override or GUI? 

would you mind upload the file `d:/emqx/data/configs/app.2021.07.12.07.58.02. conf` for analysis?  (remember to mask sensitive information)

**Comment by ZhangLianda** [comment]
##--------------------------------------------------------------------
## Authentication/Access Control
##--------------------------------------------------------------------

## Allow anonymous authentication by default if no auth plugins loaded.
## Notice: Disable the option in production deployment!
##
## Value: true | false
**allow_anonymous = true**

to:

##--------------------------------------------------------------------
## Authentication/Access Control
##--------------------------------------------------------------------

## Allow anonymous authentication by default if no auth plugins loaded.
## Notice: Disable the option in production deployment!
##
## Value: true | false
**allow_anonymous = false**

**Comment by ZhangLianda** [comment]
[app.2021.07.12.17.50.00.txt](https://github.com/emqx/emqx/files/6800406/app.2021.07.12.17.50.00.txt)

**Comment by k32** [comment]
The format of the `app.2021.07.12.07.58.02.conf` is invalid. It looks like the source configuration file from `etc` directory was copied as is to the `data/configs` directory instead of being translated to `eterm` format. Do you see the same problem on a clean install?

**Comment by ZhangLianda** [comment]
yes，the same problem occurs when I perform a clean installation in the virtual machine

**Comment by k32** [comment]
Do you edit any files during clean install? Do you see the same error on a more recent version of EMQ X, e.g. 4.3 ?

**Comment by ZhangLianda** [comment]
I haven't modified any files or parameters, other than allow_anonymous

**Comment by turtleDeng** [comment]
Windows Please pay attention to the file encoding format @ZhangLianda

**Comment by qzhuyan** [comment]
close due to inactivity.

**Comment by zeratul1990** [comment]
got the same problem when i edit the file with notepad.
i read the file in ultraedit as hex file,the edited file got a EF BB BF at the very beginning. save the file in utf8 *without bom* would be enough

**Comment by zmstone** [comment]
> got the same problem when i edit the file with notepad.
> i read the file in ultraedit as hex file,the edited file got a EF BB BF at the very beginning. save the file in utf8 _without bom_ would be enough

Ah, the bom, thank you for reporting this.
I’ve added this to our backlog for a follow up fix.
