### ISSUE TITLE
emqx:4.3.0 exhook grpc too slow？

### ISSUE THREAD

**Issue by Bevr2020** [emqx/emqx#5217]
**Please describe your problem in detail, if necessary, you can upload the log file through the attachment**:
when i start emqx exhook plugins using java grpc, how can i improve the grpc call method(like onClientConnected, onClientAuthenticate) speed? how can i configure the grpc client ? grpc server has configured threadpool, however now the method call speed is 20 times per second at most, Too Slow.

help me plz. thx

**Comment by k32** [comment]
Hello,

Please share the following information:
1) Do you run any business logic in the request handler?
2) Which libraries do you use? Which async primitives do you use? 
Writing a gRPC server in Java can be done in a number of different ways, we need to know more about your specific case. Can you share some code of your service, etc.
3) Can you share some characteristics of the hardware that you're using.
