### ISSUE TITLE
Failed to compile emqx with emqx-auth-http plugin.

### ISSUE THREAD

**Issue by sushantAtAws** [emqx/emqx#5224]
Hi, 
My aim is to develop a plugin and compile emqx with that plugin. As the first step, I am trying to build emqx with the 1st party plugins provided: emqx-auth-http

I followed the instructions in the lib-extra/README. 

**Environment**:

- EMQ X version (e.g. `emqx_ctl status`):  <Cannot compile>
- Hardware configuration (e.g. `lscpu`): x86_64
- OS (e.g. `cat /etc/os-release`): NAME="Ubuntu" VERSION="20.04.2 LTS (Focal Fossa)"
- Kernel (e.g. `uname -a`): Linux ip-172-31-53-162 5.4.0-1045-aws #47-Ubuntu SMP Tue Apr 13 07:02:25 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
- Erlang/OTP version (in case you build emqx from source code): Erlang/OTP 22 [erts-10.6.4]
- Others:

**What happened and what you expected to happen**:
Build failed. 

Error/Output:
```
===> Evaluating config writer ./rebar.config.erl
===> Uncaught error in rebar_core. Run with DIAGNOSTIC=1 to see stacktrace or consult rebar3.crashdump
===> Uncaught error: {badmatch,{error,{1,erl_parse,"bad term"}}}
===> Stack trace to the error location:
[{'rebar.config',extra_deps,0,[{file,"/tmp/rebar.config.erl"},{line,30}]},
 {'rebar.config',deps,1,[{file,"/tmp/rebar.config.erl"},{line,26}]},
 {'rebar.config',do,2,[{file,"/tmp/rebar.config.erl"},{line,8}]},
 {rebar_config,consult_file,1,[{file,"rebar_config.erl"},{line,245}]},
 {rebar3,init_config,0,[{file,"rebar3.erl"},{line,206}]},
 {rebar3,run,1,[{file,"rebar3.erl"},{line,100}]},
 {rebar3,main,1,[{file,"rebar3.erl"},{line,66}]},
 {escript,run,2,[{file,"escript.erl"},{line,758}]}]
```

Expected: emqx compiled with the plugin.

**How to reproduce it (as minimally and precisely as possible)**:

Modify lib-extra/plugins:
```
{erlang_plugins,
  [ {emqx-auth-http, {git, "https://github.com/emqx/emqx-auth-http", {tag, "4.2.13"}}}
  ]
}.

{elixir_plugins,
  [ {emqx_elixir_plugin, {git, "https://github.com/emqx/emqx-elixir-plugin.git", {branch, "3.0.0"}}}
  ]
}.
```

Execute:
```
export EMQX_EXTRA_PLUGINS=emqx-auth-http
DIAGNOSTIC=1 make
```

**Anything else we need to know?**:
-------

Rebar3 report
 version 3.16.1+build.5060.ref6e79ef6c
 generated at 2021-07-14T00:23:29+00:00
-----------------
Task: make
Entered as:
  make
-----------------
Operating System: x86_64-pc-linux-gnu
ERTS: Erlang/OTP 22 [erts-10.6.4] [source] [64-bit] [smp:1:1] [ds:1:1:10] [async-threads:1]
Root Directory: /usr/lib/erlang
Library directory: /usr/lib/erlang/lib
-----------------
Loaded Applications:
bbmustache: 1.10.0
certifi: 2.6.1
cf: 0.3.1
common_test: 1.18.1
compiler: 7.5.2
crypto: 4.6.4
cth_readable: 1.5.1
dialyzer: 4.1.1
edoc: 0.11
erlware_commons: 1.5.0
eunit: 2.4
eunit_formatters: 0.5.0
getopt: 1.0.1
hipe: 3.19.2
inets: 7.1.2
kernel: 6.5.1
providers: 1.8.1
public_key: 1.7.1
relx: 4.4.0
sasl: 3.4.1
snmp: 5.4.5
ssl_verify_fun: 1.1.6
stdlib: 3.11.2
syntax_tools: 2.2.1
tools: 3.3

-----------------
Escript path: /usr/local/bin/rebar3
Providers:
  app_discovery as clean compile compile cover ct deps dialyzer do edoc escriptize eunit get-deps help install install_deps list lock new path pkgs release relup report repos shell state tar tree unlock update upgrade upgrade upgrade version xref

**Comment by zmstone** [comment]
Syntax error, Use underscores emqx_auth_http:
```
{erlang_plugins,
  [ {emqx_auth_http, {git, "https://github.com/emqx/emqx-auth-http", {tag, "4.2.13"}}}
  ]
}.
```
Also, 4.3 emqx is not compatible with 4.2 plugins. Please copy the code from `apps` dir.
