### ISSUE TITLE
Build files: too many files given

### ISSUE THREAD

**Issue by mkrusemark** [emqx/emqx#5230]
**Environment**: Archlinux with GCC-11 but even GCC-10 fails

- EMQ X version (e.g. `emqx_ctl status`): main-4.3 
- Hardware configuration (e.g. `lscpu`): -
- OS (e.g. `cat /etc/os-release`):  Archlinux
- Kernel (e.g. `uname -a`): -
- Erlang/OTP version (in case you build emqx from source code): 24
- Others:

**What happened and what you expected to happen**:
Build works

**How to reproduce it (as minimally and precisely as possible)**:
run make

**Anything else we need to know?**:
#12 182.0 cc1: error: too many filenames given; type 'cc1 --help' for usage
#12 182.0 cc1: fatal error: CMakeFiles/quicer_static.dir/c_src/quicer_nif.c.d: No such file or directory
#12 182.0 compilation terminated.

**Comment by DDDHuang** [comment]
OTP version `24` is not yet supported, please use 22 or 23 and try again

**Comment by qzhuyan** [comment]
EMQ X version is 5.0

link to  https://github.com/emqx/quic/issues/46

We will soon bump the quic version to solve it.

**Comment by qzhuyan** [comment]
FIx is on the master branch.
