### ISSUE TITLE
404  Not Found [IP: 13.224.96.50 443] on ´apt update´...

### ISSUE THREAD

**Issue by jayjupdhig** [emqx/emqx#5231]
...as described on your manual.

Entries in sources.list:

```
deb [arch=amd64] https://repos.emqx.io/emqx-ce/deb/ubuntu/ buster stable
# deb-src [arch=amd64] https://repos.emqx.io/emqx-ce/deb/ubuntu/ buster stable
```

Thanks in advance for your feedback...

**Comment by jayjupdhig** [comment]
Still a problem with that:

deb [arch=amd64] https://repos.emqx.io/emqx-ce/deb/debian/ buster stable
# deb-src [arch=amd64] https://repos.emqx.io/emqx-ce/deb/debian/ buster stable


Output:

W: Konflikt bei Distribution: https://repos.emqx.io/emqx-ce/deb/debian buster InRelease (buster erwartet, aber  bekommen)


Why?

**Comment by Rory-Z** [comment]
Hi, jayjupdhig
There is no `buster` version of ubuntu, maybe you should use `bionic` in ubuntu ?

**Comment by jayjupdhig** [comment]
I need debian 10

**Comment by Rory-Z** [comment]
> W: Konflikt bei Distribution: https://repos.emqx.io/emqx-ce/deb/debian buster InRelease (buster erwartet, aber bekommen)

This is just a warning message, you can ignore it
Or update the source of emqx in your sources.list to : `deb [arch=amd64] https://repos.emqx.io/emqx-ce/deb/debian/ ./buster stable`

**Comment by Rory-Z** [comment]
I will close this issue and if you have any questions, you can always open it
