### ISSUE TITLE
Failed to start LSB: Erlang MQTT Broker.

### ISSUE THREAD

**Issue by jayjupdhig** [emqx/emqx#5238]
**root@debian10-emqx:~# service emqx status**
● emqx.service - LSB: Erlang MQTT Broker
   Loaded: loaded (/etc/init.d/emqx; generated)
   Active: failed (Result: exit-code) since Thu 2021-07-15 11:28:25 CEST; 13min ago
     Docs: man:systemd-sysv-generator(8)
  Process: 343 ExecStart=/etc/init.d/emqx start (code=exited, status=1/FAILURE)

Jul 15 11:27:57 debian10-emqx su[487]: (to emqx) root on none
Jul 15 11:27:57 debian10-emqx su[487]: pam_unix(su-l:session): session opened for user emqx by (uid=0)
Jul 15 11:28:25 debian10-emqx emqx[343]: Starting emqx:EMQ X Broker 4.3.5 failed to start within 15 seconds,
Jul 15 11:28:25 debian10-emqx emqx[343]: see the output of '/usr/bin/emqx console' for more information.
Jul 15 11:28:25 debian10-emqx emqx[343]: If you want to wait longer, set the environment variable
Jul 15 11:28:25 debian10-emqx emqx[343]: WAIT_FOR_ERLANG to the number of seconds to wait.
Jul 15 11:28:25 debian10-emqx emqx[343]:  failed!
Jul 15 11:28:25 debian10-emqx systemd[1]: emqx.service: Control process exited, code=exited, status=1/FAILURE
Jul 15 11:28:25 debian10-emqx systemd[1]: emqx.service: Failed with result 'exit-code'.
Jul 15 11:28:25 debian10-emqx systemd[1]: Failed to start LSB: Erlang MQTT Broker.

So i remember right, i followed all steps in your installation manual for Debian 10...

Thank you very much for your feedbacks! :-)

**Comment by k32** [comment]
Hello,
Can you share the contents of /var/log

**Comment by jayjupdhig** [comment]
Here...

[emqx.zip](https://github.com/emqx/emqx/files/6823062/emqx.zip)

Thank you very much!! :-)

**Comment by k32** [comment]
Thanks for the logs.
```
Failed to start mqtt listener mqtt:wss:external on 0.0.0.0:8084: eaddrinuse
```
EMQ X couldn't start because anther service was listening on port 8084. You can change the value of `listener.wss.external` parameter to a free port.
I hope this helps.

**Comment by jayjupdhig** [comment]
Thank you too!! Now i disabled that Websocket SSL service with commenting out: 

´#listener.wss.external = 8084´

:-)

**Comment by Singh2901** [comment]
hi I am also getting same error while starting EMQX, But error is different. Can you help me with some solution?

=====
===== LOGGING STARTED Fri Mar 24 15:22:50 IST 2023
=====
/usr/lib/emqx/bin/nodetool: /usr/local/lib/libz.so.1: version `ZLIB_1.2.7.1' not found (required by /usr/lib/emqx/bin/nodetool)

**Comment by id** [comment]
@Singh2901 please create a new issue and share details about your environment as well as installation method and emqx version.
