### ISSUE TITLE
规则引擎是否能解析单精度整数数组

### ISSUE THREAD

**Issue by eleleme** [emqx/emqx#5245]
假设一条消息需要发送两个单精度整数

(1).to_bytes(4,byteorder='little', signed=True).hex()
Out[20]: '01000000'
(-1).to_bytes(4,byteorder='little', signed=True).hex()
Out[21]: 'ffffffff'
(-2).to_bytes(4,byteorder='little', signed=True).hex()
Out[22]: 'feffffff'

**Comment by terry-xiaoyu** [comment]
Duplicate this to https://github.com/emqx/emqx/issues/5247
