### ISSUE TITLE
规则引擎解析整数数组

### ISSUE THREAD

**Issue by eleleme** [emqx/emqx#5246]
假设一条消息需要传递3个有符号整数（每个占有4个byte）分别为1，-1，-2，使用小端模式对应的十六进制字符串分别为01000000,ffffffff,feffffff，如果pyload=01000000fffffffffeffffff, 有没有本地函数可以提取出这三个整数，然后转成json对象类似下面的格式：{"key1":1,"key2":-1,"key3":-2}。最终这个json对象被转发到其他topic上

**Comment by Rory-Z** [comment]
I will close this issue because the same issue exists: https://github.com/emqx/emqx/issues/5247
