### ISSUE TITLE
Can the rule engine handle arrays?

### ISSUE THREAD

**Issue by eleleme** [emqx/emqx#5247]
假设一条消息需要传递3个有符号整数（每个占有4个byte）分别为1，-1，-2，使用小端模式对应的十六进制字符串分别为01000000,ffffffff,feffffff，如果pyload=01000000fffffffffeffffff, 有没有本地函数可以提取出这三个整数，然后转成json对象类似下面的格式：{"key1":1,"key2":-1,"key3":-2}。最终这个json对象被转发到其他topic上

**Comment by terry-xiaoyu** [comment]
Try this SQL code snippet:

```
SELECT 

subbits(payload, 1, 64, 'bits', 'unsigned', 'big') as firstIntStr,
subbits(hexstr2bin(firstIntStr), 1, 32, 'integer', 'signed', 'little') as firstInt

FROM "your/topic"

```

You will get firstInt with value 1. The function `subbits(Value, StartPos, Length, ...)` get the sub bits with the specified length.

Use the same way to get the other two integers in your example.

**Comment by terry-xiaoyu** [comment]
Always post your issues in English please.

**Comment by terry-xiaoyu** [comment]
BTW, there's no `for-loop` syntax support in the current implementation of SQL. We plan to support it but I don't know the time.

**Comment by wivwiv** [comment]
@terry-xiaoyu 
Rule execution should not be blocked. Is there a better idea for the pipeline in the 5.0+? Create an EIP
![image](https://user-images.githubusercontent.com/25006774/126415926-e728cf75-bad6-4fe1-bef5-bedd505a16ba.png)
