### ISSUE TITLE
How to map a user with a specific topic for read / write on it?

### ISSUE THREAD

**Issue by jayjupdhig** [emqx/emqx#5265]
Hi

I can't see any menu in the web GUI for that - do i need to do with via SSH and config files as described here?
-> https://docs.emqx.io/en/broker/v4.3/configuration/configuration.html#cluster

thx for feedback.

kind regards, Jan

**Comment by jayjupdhig** [comment]
Maybe the question is too complex...?

**Comment by zmstone** [comment]
hi

do you mean to allow a specific MQTT client user to exclusively publish/subscribe a given topic ?

**Comment by jayjupdhig** [comment]
Hi

Exactly...

**Comment by zmstone** [comment]
I think what you are looking for is: https://docs.emqx.io/en/broker/v4.3/advanced/acl-file.html

**Comment by jayjupdhig** [comment]
So im right - not possible via web GUI?

**Comment by zmstone** [comment]
You are right, there is no way to update ACL rules from GUI.

**Comment by jayjupdhig** [comment]
Thank you for your feedback. Is it (configure ACLs via web GUI) possible in the commercial (not open-source) version?

**Comment by zmstone** [comment]
@jayjupdhig not yet
It will be made configurable from GUI in version 5 though.

**Comment by jayjupdhig** [comment]
Thank you very much for your feedback - sounds really interesting!! :-)

Can you say me (more or less) when the first v5 beta will be available? Then we can use and test it and report you some bugs and hints for improvements...

**Comment by zmstone** [comment]
Hard to say, maybe September

**Comment by jayjupdhig** [comment]
Sounds nice - thank you very much for your feedback!! :-)

**Comment by zmstone** [comment]
You can find beta.3 packages here
https://github.com/emqx/emqx/releases/tag/v5.0-beta.3
