### ISSUE TITLE
emqx:4.3.0 exhook grpc too slow？

### ISSUE THREAD

**Issue by Bevr2020** [emqx/emqx#5268]
when i start emqx exhook plugins using java grpc, how can i improve the grpc call method(like onClientConnected, onClientAuthenticate) frequency? how can i configure the exhook grpc client ? grpc server has configured threadpool, however now the method call speed is 20 times per second at most, Too Slow.
![image](https://user-images.githubusercontent.com/62202698/126253434-c19063da-5c39-4eba-b888-060553ee5c61.png)
![image](https://user-images.githubusercontent.com/62202698/126253436-2ac36011-ff69-45a5-bc0f-c5bc279b17de.png)
![image](https://user-images.githubusercontent.com/62202698/126253443-67efcc65-4526-4128-b0ec-f146ba2cc06a.png)
1: i do not run any business logic
2: as exhook logs show, the grpc callback is slow, nearly 50-100ms between method callback, is there any configure for exhook grpc client?

**Comment by qzhuyan** [comment]
@Bevr2020 can you provide information about your setup?

hardware, software and network?
