### ISSUE TITLE
build from source

### ISSUE THREAD

**Issue by moziie** [emqx/emqx#5269]
选择从源码构建的时候，按照此方法执行命令
git clone https://github.com/emqx/emqx.git
cd emqx
make
_build/emqx/rel/emqx/bin console
在编译的过程中会提示错误，请问如何分析该错误
make[3]: 离开目录“/home/java/emqx/_build/default/lib/quicer/c_build”
make[3]: 进入目录“/home/java/emqx/_build/default/lib/quicer/c_build”
[  4%] Building C object submodules/msquic/src/platform/CMakeFiles/platform.dir/datapath_epoll.c.o
/home/java/emqx/_build/default/lib/quicer/submodules/msquic/src/platform/datapath_epoll.c: In function 'CxPlatSocketSendInternal':
/home/java/emqx/_build/default/lib/quicer/submodules/msquic/src/platform/datapath_epoll.c:2449:9: error: dereferencing type-punned pointer will break strict-aliasing rules [-Werror=strict-aliasing]
         *(int *)CMSG_DATA(CMsg) = SendData->ECN;
         ^
/home/java/emqx/_build/default/lib/quicer/submodules/msquic/src/core/frame.c: In function 'QuicFrameLog':
/home/java/emqx/_build/default/lib/quicer/submodules/msquic/src/core/frame.c:1742:9: error: dereferencing type-punned pointer will break strict-aliasing rules [-Werror=strict-aliasing]
         QuicTraceLogVerbose(
         ^~~~~~~~~~~~~~~~~~~
/home/java/emqx/_build/default/lib/quicer/submodules/msquic/src/core/frame.c:1764:9: error: dereferencing type-punned pointer will break strict-aliasing rules [-Werror=strict-aliasing]
         QuicTraceLogVerbose(
         ^~~~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors
make[3]: *** [submodules/msquic/src/platform/CMakeFiles/platform.dir/build.make:82：submodules/msquic/src/platform/CMakeFiles/platform.dir/datapath_epoll.c.o] 错误 1
make[3]: 离开目录“/home/java/emqx/_build/default/lib/quicer/c_build”
make[2]: *** [CMakeFiles/Makefile2:341：submodules/msquic/src/platform/CMakeFiles/platform.dir/all] 错误 2
make[2]: *** 正在等待未完成的任务....
cc1: all warnings being treated as errors
make[3]: *** [submodules/msquic/src/core/CMakeFiles/core.dir/build.make:199：submodules/msquic/src/core/CMakeFiles/core.dir/frame.c.o] 错误 1
make[3]: 离开目录“/home/java/emqx/_build/default/lib/quicer/c_build”
make[2]: *** [CMakeFiles/Makefile2:314：submodules/msquic/src/core/CMakeFiles/core.dir/all] 错误 2
make[2]: 离开目录“/home/java/emqx/_build/default/lib/quicer/c_build”
make[1]: *** [Makefile:149：all] 错误 2
make[1]: 离开目录“/home/java/emqx/_build/default/lib/quicer/c_build”
===> Hook for compile failed!
make: *** [Makefile:78：emqx] 错误 1

所使用的系统是统信uos，64位，16核64G配置
该机器安装erlang版本如下 Erlang/OTP 21 [erts-10.2.4] [source] [64-bit] [smp:16:8] [ds:16:8:10] [async-threads:1]
Eshell V10.2.4  (abort with ^G)

我的问题，请问是哪里出的问题，我应该i如何进行调试

**Comment by qzhuyan** [comment]
Looks like some compiler warning fails the build.

what is your GCC version? 

you can also try to build without quic support with 
```
BUILD_WITHOUT_QUIC=1 make
```

**Comment by moziie** [comment]
gcc version: gcc (GCC) 7.1.0 ，我尝试了 BUILD_WITHOUT_QUIC=1 make，make过程中提示错误与之前的一样，下面是完整的信息：
root@fw03:/home/java/emqx# BUILD_WITHOUT_QUIC=1 make
===> Plugin er_coap_client does not export init/1. It will not be used.
===> Verifying dependencies...
===> Skipping cowlib v2.11.0 as an app of the same name has already been fetched
===> Skipping emqx_http_lib (from {git,"https://github.com/emqx/emqx_http_lib",
                         {tag,"0.2.1"}}) as an app of the same name has already been fetched
===> Skipping esockd (from {git,"https://github.com/emqx/esockd",{tag,"5.7.4"}}) as an app of the same name has already been fetched
===> Skipping esockd (from {git,"https://github.com/emqx/esockd",{tag,"5.7.4"}}) as an app of the same name has already been fetched
===> Skipping gen_rpc (from {git,"https://github.com/emqx/gen_rpc",{tag,"2.5.0"}}) as an app of the same name has already been fetched
===> Skipping getopt (from {git,"https://github.com/emqx/getopt.git",{tag,"v1.0.2"}}) as an app of the same name has already been fetched
===> Skipping getopt v1.0.2 as an app of the same name has already been fetched
===> Skipping gpb v4.17.7 as an app of the same name has already been fetched
===> Skipping gproc v0.8.0 as an app of the same name has already been fetched
===> Skipping gproc v0.8.0 as an app of the same name has already been fetched
===> Skipping gun (from {git,"https://github.com/emqx/gun",{tag,"1.3.4"}}) as an app of the same name has already been fetched
===> Skipping gun (from {git,"https://github.com/emqx/gun",{tag,"1.3.4"}}) as an app of the same name has already been fetched
===> Skipping hocon (from {git,"https://github.com/emqx/hocon.git",{tag,"0.3.2"}}) as an app of the same name has already been fetched
===> Skipping pbkdf2 (from {git,"https://github.com/emqx/erlang-pbkdf2.git",{tag,"2.0.3"}}) as an app of the same name has already been fetched
===> Skipping poolboy (from {git,"https://github.com/devinus/poolboy.git",{branch,"1.5.1"}}) as an app of the same name has already been fetched
===> Skipping poolboy (from {git,"https://github.com/comtihon/poolboy.git",
                   {branch,"master"}}) as an app of the same name has already been fetched
===> Skipping recon v2.5.1 as an app of the same name has already been fetched
===> Skipping replayq (from {git,"https://github.com/emqx/replayq",{tag,"0.3.1"}}) as an app of the same name has already been fetched
===> Skipping snabbkaffe (from {git,"https://github.com/kafka4beam/snabbkaffe",
                      {tag,"0.14.0"}}) as an app of the same name has already been fetched
===> Skipping snabbkaffe (from {git,"https://github.com/kafka4beam/snabbkaffe.git",
                      {ref,"2f2f6ad09b97e33ba66b195665cef17d04598abd"}}) as an app of the same name has already been fetched
===> Skipping cowboy v2.8.0 as an app of the same name has already been fetched
===> Skipping gun v1.3.3 as an app of the same name has already been fetched
===> Skipping jsx v2.9.0 as an app of the same name has already been fetched
===> Skipping ranch v2.0.0 as an app of the same name has already been fetched
===> Skipping cowboy v2.3.0 as an app of the same name has already been fetched
===> Compiling c_src/async_queue.c
===> Compiling c_src/bcrypt.c
===> Compiling c_src/bcrypt_nif.c
===> Compiling c_src/blowfish.c
-- CMAKE Version: 3.18.0
-- Source Dir: /home/java/emqx/_build/default/lib/quicer/submodules/msquic
-- Host System name: Linux
-- Setting policy 0091
-- System name: Linux
-- System version: 4.19.90-3-server-sw64-aere
-- Platform version: 
-- Build type: RelWithDebInfo
-- QUIC Platform: linux
-- Version Build ID: 0
-- Version Suffix: -private
-- Disabling client certificate tests
-- Disabling deferred certificate tests
-- Disabling tracing
-- Found libatomic: /usr/lib/libatomic.so
-- Configuring for OpenSSL
-- Configuring done
-- Generating done
-- Build files have been written to: /home/java/emqx/_build/default/lib/quicer/c_build
make[1]: 进入目录“/home/java/emqx/_build/default/lib/quicer/c_build”
make[2]: 进入目录“/home/java/emqx/_build/default/lib/quicer/c_build”
make[3]: 进入目录“/home/java/emqx/_build/default/lib/quicer/c_build”
make[3]: 离开目录“/home/java/emqx/_build/default/lib/quicer/c_build”
make[3]: 进入目录“/home/java/emqx/_build/default/lib/quicer/c_build”
make[3]: 进入目录“/home/java/emqx/_build/default/lib/quicer/c_build”
make[3]: 离开目录“/home/java/emqx/_build/default/lib/quicer/c_build”
[  0%] Built target mkdir_openssl_build
make[3]: 离开目录“/home/java/emqx/_build/default/lib/quicer/c_build”
make[3]: 进入目录“/home/java/emqx/_build/default/lib/quicer/c_build”
make[3]: 离开目录“/home/java/emqx/_build/default/lib/quicer/c_build”
make[3]: 进入目录“/home/java/emqx/_build/default/lib/quicer/c_build”
[  1%] Built target OpenSSL_Build
[  2%] Building C object submodules/msquic/src/core/CMakeFiles/core.dir/frame.c.o
make[3]: 进入目录“/home/java/emqx/_build/default/lib/quicer/c_build”
make[3]: 离开目录“/home/java/emqx/_build/default/lib/quicer/c_build”
make[3]: 进入目录“/home/java/emqx/_build/default/lib/quicer/c_build”
[  4%] Building C object submodules/msquic/src/platform/CMakeFiles/platform.dir/datapath_epoll.c.o
/home/java/emqx/_build/default/lib/quicer/submodules/msquic/src/platform/datapath_epoll.c: In function 'CxPlatSocketSendInternal':
/home/java/emqx/_build/default/lib/quicer/submodules/msquic/src/platform/datapath_epoll.c:2449:9: error: dereferencing type-punned pointer will break strict-aliasing rules [-Werror=strict-aliasing]
         *(int *)CMSG_DATA(CMsg) = SendData->ECN;
         ^
/home/java/emqx/_build/default/lib/quicer/submodules/msquic/src/core/frame.c: In function 'QuicFrameLog':
/home/java/emqx/_build/default/lib/quicer/submodules/msquic/src/core/frame.c:1742:9: error: dereferencing type-punned pointer will break strict-aliasing rules [-Werror=strict-aliasing]
         QuicTraceLogVerbose(
         ^~~~~~~~~~~~~~~~~~~
/home/java/emqx/_build/default/lib/quicer/submodules/msquic/src/core/frame.c:1764:9: error: dereferencing type-punned pointer will break strict-aliasing rules [-Werror=strict-aliasing]
         QuicTraceLogVerbose(
         ^~~~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors
make[3]: *** [submodules/msquic/src/platform/CMakeFiles/platform.dir/build.make:82：submodules/msquic/src/platform/CMakeFiles/platform.dir/datapath_epoll.c.o] 错误 1
make[3]: 离开目录“/home/java/emqx/_build/default/lib/quicer/c_build”
make[2]: *** [CMakeFiles/Makefile2:341：submodules/msquic/src/platform/CMakeFiles/platform.dir/all] 错误 2
make[2]: *** 正在等待未完成的任务....
cc1: all warnings being treated as errors
make[3]: *** [submodules/msquic/src/core/CMakeFiles/core.dir/build.make:199：submodules/msquic/src/core/CMakeFiles/core.dir/frame.c.o] 错误 1
make[3]: 离开目录“/home/java/emqx/_build/default/lib/quicer/c_build”
make[2]: *** [CMakeFiles/Makefile2:314：submodules/msquic/src/core/CMakeFiles/core.dir/all] 错误 2
make[2]: 离开目录“/home/java/emqx/_build/default/lib/quicer/c_build”
make[1]: *** [Makefile:149：all] 错误 2
make[1]: 离开目录“/home/java/emqx/_build/default/lib/quicer/c_build”
===> Hook for compile failed!

make: *** [Makefile:78：emqx] 错误 1

**Comment by qzhuyan** [comment]
my mistake, please do 

`make clean-all`
`rm -f rebar.lock`

then 
```
export BUILD_WITHOUT_QUIC=1  EMQX_BUILD_WITHOUT_QUIC=1 
make emqx
```

For the GCC warnings, I think you can try to disable them in your OS.

**Comment by moziie** [comment]
got it ,thank you very much
