### ISSUE TITLE
The question of Inflight and Queue?

### ISSUE THREAD

**Issue by SmilyWu** [emqx/emqx#5274]
The client sends many messages to the broker from the same topic, but after the client connects, it does not consume the messages in the queue (or there is no queue at all), only consumes a reserved message. How can it be complete? Thank you~

**Comment by qzhuyan** [comment]
>  reserved message

Do you mean retained message?

> The client sends many messages to the broker from the same topic, but after the client connects, it does not consume 

What do you mean after the client connects? Do you mean another client or?

**Comment by SmilyWu** [comment]
> > 保留消息
> 
> 你的意思是保留消息？
> 
> > 客户端从同一个topic向broker发送很多消息，但是客户端连接后不消费
> 
> 客户端连接后是什么意思？你是说另一个客户还是？

It's not a message reservation, it's a message queue. How can we store more messages and automatically consume these historical messages after the client connects

**Comment by SmilyWu** [comment]
> > reserved message
> 
> Do you mean retained message?
> 
> > The client sends many messages to the broker from the same topic, but after the client connects, it does not consume
> 
> What do you mean after the client connects? Do you mean another client or?


Should offline messages be stored in the database first?

**Comment by qzhuyan** [comment]
EMQX is a message broker, not a message queue. you can bridge message to kafka.

**Comment by zmstone** [comment]
Hi @SmilyWu 
As @qzhuyan noted, MQTT protocol does not persist messages without any subscriber for the purpose of replay.
messages delivered to persisted session will be sent to a subscriber, however it requires the subscriber to subscribe to a topic at prior to its offline.
