### ISSUE TITLE
Can emqx grpc configure connection pool

### ISSUE THREAD

**Issue by zuodengchao** [emqx/emqx#5309]

**Comment by turtleDeng** [comment]
Which plugin are you using?

**Comment by zuodengchao** [comment]
> Which plugin are you using?

emqx_exhook and emqx_exproto

**Comment by turtleDeng** [comment]
Sorry, connection pool is not supported

**Comment by zmstone** [comment]
Pooling is supported in 5.0

**Comment by HJianBo** [comment]
This feature has been recently implemented in 4.4. Currently 4.4-beta.1 has been released, but the official release may have to wait a bit longer.

Thanks for your suggestion @zuodengchao :)
