### ISSUE TITLE
Cannot delete ClientID with special characters？

### ISSUE THREAD

**Issue by zy-Info** [emqx/emqx#5311]
such as Something like this：7yz79FBKlQ3Aj78V|securemode=3,signmethod=hmacsha1,timestamp=1627263653|
Cannot call interface delete？

**Comment by Rory-Z** [comment]
Hi，@zy-Info
Are you saying it can't be deleted through the API? Or can't call emqx_ctl? If you have a related log, please share it

**Comment by zy-Info** [comment]
CloseableHttpClient httpClient = HttpClients.createDefault();
        String httpUrl = URLEncoder.encode("7yz79FBKlQ3Aj78V|securemode=3,signmethod=hmacsha1,timestamp=1627263653|", "UTF-8");
        HttpDelete httpDelete = new HttpDelete("http://127.0.0.1:8081/api/v4/clients/"+ httpUrl);
        RequestConfig requestConfig = RequestConfig.custom().setConnectTimeout(35000).setConnectionRequestTimeout(35000).setSocketTimeout(60000).build();
        httpDelete.setConfig(requestConfig);
        httpDelete.setHeader("Content-type", "application/json");
        httpDelete.setHeader("DataEncoding", "UTF-8");
        //httpDelete.setHeader("Authorization", "Basic " + Base64.getUrlEncoder().encodeToString((auth.getBytes(Charset.forName("US-ASCII")))));


        CloseableHttpResponse httpResponse = null;
        try {
            httpResponse = httpClient.execute(httpDelete);
            HttpEntity entity = httpResponse.getEntity();
            String result = EntityUtils.toString(entity);
            System.out.println(result);
        } catch (ClientProtocolException e) {
            // TODO Auto-generated catch block
            e.printStackTrace();
        } catch (IOException e) {
            // TODO Auto-generated catch block
            e.printStackTrace();
        } finally {
            if (httpResponse != null) {
                try {
                    httpResponse.close();
                } catch (IOException e) {
                    // TODO Auto-generated catch block
                    e.printStackTrace();
                }
            }
            if (null != httpClient) {
                try {
                    httpClient.close();
                } catch (IOException e) {
                    e.printStackTrace();
                }
            }
        }
I call the interface of emqx through the above method to delete the ClientID, but it cannot be deleted. Because the ClientID contains special characters. I can't delete the ClientID either by calling emqx through postmap

**Comment by Rory-Z** [comment]
@zy-Info Apologize for the delay
I don't know much about java, is your clientid `7yz79FBKlQ3Aj78V|securemode=3,signmethod=hmacsha1,timestamp=1627263653|`? Can you show me the value after the urlencode?
