### ISSUE TITLE
Documentation of data that is persisted to disk and still available after node/cluster restart

### ISSUE THREAD

**Issue by gbrehmer** [emqx/emqx#533]
(copied from issue #443 comment: https://github.com/emqtt/emqttd/issues/443#issuecomment-214213517)
Can you please document which information is currently persisted to disk, so it will be restored after node or complete cluster restart? I assume currently persistent sessions (subscriptions, offline/not acked messages?) & retained messages are persisted.

**Comment by emqplus** [comment]
@gbrehmer, Thanks for your suggestion. I will add a section about persistence in 'Design' document.

**Comment by lucaslafarga** [comment]
I didn't see anything about persistence in the documents, so I guess you have not updated it yet. My question is: is there any way of configuring the persistence of retained messages?
In our case we are interested in not persisting those messages. We can delete the file retained_message.DCD manually to achieve the same result, but ideally this should be configurable.

**Comment by Xyon75** [comment]
Same problem here: is there some way to delete persistant messages when restarting the server?

**Comment by maecky** [comment]
Did anyone figure this out? I would also like to be able to delete persistent / retained message on reboot?

**Comment by turtleDeng** [comment]
@gbrehmer 
The emqx-enterprise supports message persistence to the DB.
https://www.emqx.io/downloads/emq/enterprise?osType=Linux
