### ISSUE TITLE
Enviroment Variables is not Working in EMQX Docker Images 4.3.5

### ISSUE THREAD

**Issue by ctellechea2001** [emqx/emqx#5352]
Steps to reproduce the error:

1) https://github.com/emqx/emqx-rel/tree/master/deploy/docker

docker run -d --name emqx -p 18083:18083 -p 1883:1883 -p 4369:4369 \
    -e EMQX_LISTENER__TCP__EXTERNAL=1883 \
    -e EMQX_LOADED_PLUGINS="emqx_auth_redis" \
    -e EMQX_AUTH__REDIS__SERVER="your.redis.server:6379" \
    -e EMQX_AUTH__REDIS__PASSWORD="password_for_redis" \
    -e EMQX_AUTH__REDIS__PASSWORD_HASH=plain \
    emqx/emqx:latest

If you pass the Environment Variables to the docker container you should see those values in the correct configuration inside the container.

2) **docker exec -ti 60b7bc0770c6 sh**
**cd etc/plugins/**
**ls**
acl.conf.paho          emqx_auth_ldap.conf    emqx_auth_mysql.conf   emqx_bridge_mqtt.conf  emqx_exhook.conf       emqx_lwm2m.conf        emqx_psk_file.conf     emqx_rule_engine.conf  emqx_stomp.conf
emqx_auth_http.conf    emqx_auth_mnesia.conf  emqx_auth_pgsql.conf   emqx_coap.conf         emqx_exproto.conf      emqx_management.conf   emqx_recon.conf        emqx_sasl.conf         emqx_telemetry.conf
emqx_auth_jwt.conf     emqx_auth_mongo.conf   emqx_auth_redis.conf   emqx_dashboard.conf    emqx_lua_hook.conf     emqx_prometheus.conf   emqx_retainer.conf     emqx_sn.conf           emqx_web_hook.conf
**cat emqx_auth_redis.conf | grep "server"**
**auth.redis.server = 127.0.0.1:6379**

in the auth.redis.server of the  emqx_auth_redis.conf file we cannot see the value of the enviroment variable. This is not happening in the previous docker version like v4.1.1.

if you check the enviroment in the docker you will see the correct value

**env | grep "REDIS"**
EMQX_AUTH__REDIS__PASSWORD_HASH=plain
EMQX_AUTH__REDIS__SERVER=your.redis.server:6379
EMQX_AUTH__REDIS__PASSWORD=password_for_redis

**Conclusion:** The enviroment value is OK inside de docker but is not being written in the configurations files (emqx_auth_redis.conf).

Do you know if it is a bug o how to fix that?

Thanks!

**Comment by ctellechea2001** [comment]
EMQ X Plugins Configuration

**The environment variables which with EMQX_ prefix are mapped to all emqx plugins' configuration file, . get replaced by __.**

![image](https://user-images.githubusercontent.com/45426180/127565539-77f62fe9-a1ea-4690-9154-36d0d8e0af33.png)

**Comment by zmstone** [comment]
hi @ctellechea2001 
I tested locally with an additional environment variable on top of yours: `-e EMQX_LOG__LEVEL=info`
```
#!/bin/bash

docker run -d --name emqx -p 18083:18083 -p 1883:1883 \
-e EMQX_LOG__LEVEL=info \
-e EMQX_LISTENER__TCP__EXTERNAL=1883 \
-e EMQX_LOADED_PLUGINS="emqx_auth_redis" \
-e EMQX_AUTH__REDIS__SERVER="your.redis.server:6379" \
-e EMQX_AUTH__REDIS__PASSWORD="password_for_redis" \
-e EMQX_AUTH__REDIS__PASSWORD_HASH=plain \
emqx/emqx:latest
```

and I can see the overrides are logged:

```
2021-07-29T21:30:38.068816+00:00 [info] [Plugins] auth.redis.password = "password_for_redis"
2021-07-29T21:30:38.068900+00:00 [info] [Plugins] auth.redis.password_hash = "plain"
2021-07-29T21:30:38.068965+00:00 [info] [Plugins] auth.redis.server = "your.redis.server:6379"
```

btw, port 4369 is not needed for 4.3

**Comment by zmstone** [comment]
starting from 4.3, environment variables are logged, but not persisted back to the .conf files.

**Comment by ctellechea2001** [comment]
@zmstone  Ok, Thank you!! I didn't know that new behavior in the new version. 

We checked that because with the same exactly configuration in V4.1.1 everything is working fine, but if I change to 4.3.5 We are getting errors the login failed for not autorized

dev-emqx-0 emqx 2021-07-29T20:00:27.023003+00:00 [warning] camara-08138281234@181.98.224.203:40412 [Channel] Client camara-08138281234 (Username: 'event-logger') **login failed for not_authorized**
dev-emqx-0 emqx 2021-07-29T20:00:27.023123+00:00 [debug] camara-08138281234@181.98.224.203:40412 **[MQTT] SEND CONNACK(Q0, R0, D0, AckFlags=0, ReasonCode=5)**
dev-emqx-0 emqx 2021-07-29T20:00:27.023322+00:00 [info] camara-08138281234@181.98.224.203:40412 file: emqx_connection.erl, line: 520, mfa: {emqx_connection,terminate,2}, msg: terminate, pid: <0.2570.0>, reason: {shutdown,not_authorized}

We discovered in the log files that in 4.3.5 is happening the following error. The emqx_auth_username was not loaded.

**2021-07-30T14:34:32.966151+00:00 [alert] [Plugins] cannot_find_plugins: [emqx_auth_username,emqx_statsd]**

emqx_auth_username.conf file with users is passing as parameters in the Helm Chart

         - name: emqx-users
            mountPath: /opt/emqx/etc/plugins/emqx_auth_username.conf
            subPath: emqx_auth_username.conf

Do you know what it is happening in the latest version?

Thanks!

**Comment by zmstone** [comment]
`emqx_auth_username` and `emqx_auth_clientid` are deleted from 4.3 release.
The functionalities are merged to `emqx_auth_mnesia`.

Please find more details here:
https://docs.emqx.io/en/broker/v4.3/changes/upgrade-4.3.html#upgrade-to-version-4-3
https://docs.emqx.io/en/broker/v4.3/advanced/auth-mnesia.html#authentication-rules

If you have a lot of data to upgrade, there are tools to help:
https://docs.emqx.io/en/broker/v4.3/advanced/data-import-and-export.html
