### ISSUE TITLE
emqx cluster split brain issue

### ISSUE THREAD

**Issue by haimiko** [emqx/emqx#5367]
**Environment**:

- EMQ X version (e.g. `emqx_ctl status`):  4.3.1
- Hardware configuration (e.g. `lscpu`):   Intel(R) Xeon(R) CPU E5-2698 v4 @ 2.20GHz
- OS (e.g. `cat /etc/os-release`):  Ubuntu 18.04
- Kernel (e.g. `uname -a`):  4.15.0-136-generic
- Erlang/OTP version (in case you build emqx from source code): 
- Others:

**What happened and what you expected to happen**:  3 node cluster, when one node's network gets disconnected for at least 10min, when network comes back online  it does not show up in the "running_nodes" list on other other cluster members but does  locally and all nodes continue to serve MQTT however one of the nodes isn't replicating to the other 2 nodes.

**How to reproduce it (as minimally and precisely as possible)**:
Example.  I have 3 clustered nodes.   emq01, emq02, emq03
***Before network outage emqx_ctl cluster status shows this:
```
Cluster status: #{running_nodes =>
                      ['emq01@10.11.11.1','emq02@10.11.12.1','emq03@10.11.13.1'],
                         stopped_nodes => []}
```
***After shutting down network for emq03 for 10min then bringing the network online without restarting emqx,  cluster status on node emq01 and emq02 look like this:
```
Cluster status: #{running_nodes =>
                      ['emq01@10.11.11.1','emq02@10.11.12.1'],
                         stopped_nodes => []}
```
on node emq03 cluster status looks like this:
```
 emqx_ctl cluster status
Cluster status: #{running_nodes => [''emq03@10.11.13.1'],stopped_nodes => []}
```

And now 03 accepts connections but will not replicate to 01/02 and vice versa until I manually rejoin 03 back into the cluster and recycle emqx on all cluster members.

**Anything else we need to know?**:

**Comment by k32** [comment]
Hello,

Sorry for a late answer. EMQ X uses ekka application to resolve network partitions. This application has autoheal feature that automatically connects the minority of the partition to the majority.  
Ekka also has autoclean feature that removes the stopped nodes from the cluster after a set period of time. Since the nodes were disconnected for a long time (10 minutes), my guess is that the autoclean ran on both partitions and disconnected the cluster permanently. You can avoid this situation by setting `cluster.autoheal` to `on`, and setting `cluster.autoclean` to a large number. 

I hope this helps.

**Comment by haimiko** [comment]
That helps with the auto-clean, however if the network comes back online and the emqx service isn't restarted then you still have a split-brain scenario.

**Comment by k32** [comment]
Could you dump the ekka application settings, so I could inspect them? It can be done by running

```
application:get_all_env(ekka).
```
In the EMQ X shell.

**Comment by haimiko** [comment]
not returning anything.
```
root@emq01:~# emqx remote_console
Erlang/OTP 23 [erts-11.1.8] [emqx] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1]

Eshell V11.1.8  (abort with ^G)
(emq01@10.11.11.1)1> application:get_all_env(ekka)
(emq01@10.11.11.1)1> application:get_all_env(ekka)
(emq01@10.11.11.1)1>
```

**Comment by zmstone** [comment]
Hi @haimiko Erlang expressions should end with a dot `application:get_all_env(ekka).`

**Comment by haimiko** [comment]
```
[{cluster_name,emqxcl},
 {{callback,prepare},fun emqx:shutdown/1},
 {cluster_discovery,{manual,[]}},
 {proto_dist,inet_tcp},
 {cluster_autoclean,35996400000},
 {{callback,reboot},fun emqx:reboot/0},
 {cluster_autoheal,true}]
```

**Comment by k32** [comment]
Thanks. Do you still observe the issue with these settings?

**Comment by haimiko** [comment]
Yes I do.  When the node that loses network connectivity comes back it is
isolated in its own cluster.

**Comment by haimiko** [comment]
BTW.  Recycling the service, after the network comes back, fixes the issue,
assuming that clean.autoclean is set really high..

**Comment by k32** [comment]
I might have managed to reproduce the problem. Just to confirm that we are on the same page, could you please check the following things:
1) After you reconnect the node to the network, you never see messages like this in the logs: `[critical] [EMQ X] emqx shutdown for heal`
2) After you reconnect the node to the network, try running `net_adm:ping('emq02@10.11.13.1').` on one of the nodes from the larger partition. Does it trigger restart of the node running on `10.11.13.1`?

**Comment by haimiko** [comment]
Yes on all counts.

**Comment by k32** [comment]
Thanks for your help. The problem was that the nodes didn't send heartbeats to the stopped nodes, and therefore they never attempted to discover whether they are up again. A very small patch fixes the problem.

**Comment by haimiko** [comment]
Excellent!  Which version will this be fixed in?

**Comment by k32** [comment]
4.3.9 and 5.0

**Comment by haimiko** [comment]
Thanks!

**Comment by haimiko** [comment]
> 4.3.9 and 5.0

Is there an estimated release date for 4.3.9?

**Comment by k32** [comment]
There are no concrete plans yet.

**Comment by AlessandroBravo** [comment]
I had a similar issue with an old version running on DigitalOcean. 

**Environment:**
- EMQ X version (e.g. emqx_ctl status): 4.0.1
- Hardware configuration (e.g. lscpu): Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz
- OS (e.g. cat /etc/os-release): Ubuntu 18.04.5
- Kernel (e.g. uname -a): 4.15.0-121-generic

The output from `emqx_ctl cluster status`:
Node 1:
```
Cluster status: #{running_nodes =>
                      ['emqx@10.90.10.1','emqx@10.90.10.3'],
                  stopped_nodes => []}
```

Node 2:
```
Cluster status: #{running_nodes =>
                      ['emqx@10.90.10.2'],
                  stopped_nodes => ['emqx@10.90.101',
                       'emqx@10.90.10.3']}
```

Node 3:
```
Cluster status: #{running_nodes =>
                      ['emqx@10.90.10.1','emqx@10.90.10.3'],
                  stopped_nodes => []}
```

Configuration:
```
cluster.autoheal = on
cluster.autoclean = 2m
```


Recycling the service (as @haimiko already pointed out) on the second node resolved the problem.
