### ISSUE TITLE
SIMCOM IOT device losses connection, shows crash in log

### ISSUE THREAD

**Issue by tpharaoh** [emqx/emqx#5383]
We have an IOT device, using SIMCOM 7020. Randomly the device looses connection and does not properly restart. I am not sure if this is related. But I see this message often, and I also see timeouts to my cluster. But, I don't think it should be related because timestamp doesn't add up.

EMQX 4.2.3

```
2021-08-01 06:52:57.093 [error]   crasher:
    initial call: gen_rpc_client:init/1
    pid: <0.31231.12>
    registered_name: []
    exception exit: {badrpc,timeout}
      in function  gen_server:init_it/6 (gen_server.erl, line 358)
    ancestors: [gen_rpc_client_sup,gen_rpc_sup,<0.1359.0>]
    message_queue_len: 1
    messages: [{{cast,emqx_broker,dispatch,
                       [<<"device/#">>,
                        {delivery,<0.31039.12>,
                            {message,
                                <<0,5,200,121,230,232,61,81,178,37,12,0,121,63,
                                  0,42>>,
                                0,<<"086BD7FFFED2462F">>,
                                #{dup => false,retain => false},
                                #{peerhost => {10,110,0,2},
                                  properties => #{},proto_ver => 3,
                                  protocol => mqtt,username => undefined},
                                <<"device/telemetry/462F/086BD60B">>,
                                <<"[{\"value\":57210,\"unit\":\"L\"},{\"value\":10,\"unit\":\"L\"}]">>,
                                1627800774130}}]},
                   undefined}]
    links: [<0.1364.0>]
    dictionary: []
    trap_exit: true
    status: running
    heap_size: 987
    stack_size: 27
    reductions: 12653
  neighbours:
```

[this issue may be related, but the solution was not posted](https://github.com/emqx/emqx/issues/3589)

**Comment by zmstone** [comment]
Hi @tpharaoh 

This timeout is perhaps a sign of system overload.
however, without more details, it's really hard to be sure.
could you give us more information as the issue template suggested ?
more info about your use case should also help
e.g. how many clients do you have in total
how many nodes do you have in the cluster

about your device's connection loss,
do you have its MQTT client id? if it's possible for you to enable debug-level logging
we should be able to figure out more.
or if you upgrade to 4.3 (latest is 4.3.6), you can trace log based on the client ID.

**Comment by tpharaoh** [comment]
Ok.

Perhaps you can close this request. I will make the following steps based
on your suggestion:
1) update emqx to newer version (currently 4.2.6)
2) search log based on client ID

As far as your question, we have a small cluster, since its used only for
dev, we have 2 devices connected. 3 Digital Ocean servers, a small, 5e
droplet. One of the devices was doing a load test at the time, so it
generated, around 60 messages per minute. Roughly 6000-7000/hour

As far as the device connection loss, our hardware programmer seems to have
located several issues in the SIMCOM 7020 itself. It does not always detect
with connection is lost, and so it continues using a closed connection. We
will try a workaround where he detects a failure and re-initialize the
connection.

**Comment by zmstone** [comment]
Thank your @tpharaoh for the updates.
I'm closing this issue.
Please feel free to reopen or create a new one.
