### ISSUE TITLE
Docker images with latest tag points to older version

### ISSUE THREAD

**Issue by bgsuello** [emqx/emqx#5403]
Hi,

The latest docker image hosted in docker hub points to older version of emqx which is `4.2.14` but the actual latest version is `4.3.6` at the time of this writing.

When I did a configuration change via helm on my local setup without specifying image version for repository `emqx/emqx`, it results to unexpected behavior.

Is this intentional?

I'm expecting that the latest tag points to the latest highest version not the latest updated version.

Thanks,

**Comment by Rory-Z** [comment]
Thanks for your feedback, the latest tag is now pointing to 4.3.6
