### ISSUE TITLE
如果某节点长期掉线，再恢复时不会自动加入原来的集群

### ISSUE THREAD

**Issue by 410853222** [emqx/emqx#5416]
If a node is dropped for a long time, it will not automatically join the original cluster when it is restored
the EMQX_CLUSTER__DISCOVERY=static

**Environment**:
docker

/opt/emqx $ emqx_ctl status
Node '3c10fd16f677@172.132.0.33' is started
emqx 4.2.2 is running
/opt/emqx $ 

如果某节点长期掉线，再恢复时不会自动加入原来的集群（static集群），是不是一个bug？
如果不能自动加入集群，则必须手动执行bin/emqx_ctl cluster join node1@172.0.0.11 ，这在自动化运维时非常糟糕

**Comment by qzhuyan** [comment]
@410853222 we have similar issue #4535 which is already fixed in 4.2.12.

Could you try with 4.2.12 and come back with emqx logs if it is not working.
