### ISSUE TITLE
SSL for XAMPP Server and EMQX Broker in same VPS Server

### ISSUE THREAD

**Issue by mnhpias** [emqx/emqx#5420]
#### Environment

- OS: Windows Server 2019
- Erlang/OTP: Erlang/OTP 22 [erts-10.4] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1]
- EMQ: emqx 4.2.7

#### Description

*A description of the issue*

I have a VPS server, in which both XAMPP and EMQX Broker are running simultaneously. I've configured SSL for XAMPP using win-acme ( Let's Encrypt). I've the following files from win-acme:

domain.com-chain.pem
domain.com-chain-only.pem
domain.com-crt.pem
domain.com-key.pem

Can I use these to confugure SSL for EMQX ?

**Comment by zmstone** [comment]
Hi @mnhpias I am converting this to a discussion
