### ISSUE TITLE
Two Way ssl not working in k8s : emqx  4.2.13

### ISSUE THREAD

**Issue by and-dzh3** [emqx/emqx#5424]
### Discussed in https://github.com/emqx/emqx/discussions/5419

<div type='discussions-op-text'>

<sup>Originally posted by **and-dzh3** August  5, 2021</sup>
Hi 
I want setup authentication in emqx broker with cn from self-signed certificate 
i issued for  clients certificate and base on username and certificate cn , give them acl rules where they can publish massages 
running emqx on k8s .
Broker receives trafic after ssl of load on AWS load balancer. 

my Error :
`10.100.10.9:32978 [Channel] Client test (Username: 'test') login failed for not_authorized`

  EMQX_CLUSTER__K8S__ADDRESS_TYPE: "hostname"
  EMQX_CLUSTER__K8S__SUFFIX: "svc.cluster.local"
  EMQX_CLUSTER__K8S__APP_NAME: "emqx"
  EMQX_CLUSTER__K8S__SERVICE_NAME: "emqx"
  EMQX_CLUSTER__K8S__NAMESPACE: "emqx"
  EMQX_ALLOW_ANONYMOUS: "false" ##allow_anonymous
  EMQX_LISTENER__TCP__EXTERNAL__PEER_CERT_AS_USERNAME: cn
  EMQX_LISTENER__SSL__EXTERNAL__PEER_CERT_AS_USERNAME: cn
  EMQX_LISTENER__SSL__EXTERNAL__FAIL_IF_NO_PEER_CERT: true
  EMQX_LISTENER__SSL__EXTERNAL__VERIFY: verify_peer
  EMQX_LISTENER__SSL__EXTERNAL__KEYFILE: /etc/certs/emqx.key
  EMQX_LISTENER__SSL__EXTERNAL__CERTFILE: /etc/certs/emqx.pem
  EMQX_LISTENER__SSL__EXTERNAL__CACERTFILE: /etc/certs/ca.pem

loaded plagins "emqx_recon,emqx_retainer,emqx_management,emqx_dashboard,emqx_statsd"

client certificate generation with ca.pem same as in emqx roker  

openssl x509 -req -in ./client.csr -CA ca.pem -CAkey ca.key -CAcreateserial -out client.pem -days 3650 -sha256
Signature ok
subject=/CN=test
Getting CA Private Key

what I can do for enabling wanted functionality </div>

**Comment by qzhuyan** [comment]
Looks like the TLS connection success while the user auth failed at the MQTT level.

**Comment by and-dzh3** [comment]
ok thanks, but how to debug or fix it? do I need to configure or enable some extra plugins?

**Comment by qzhuyan** [comment]
@and-dzh3 could this page help you?
https://docs.emqx.io/en/broker/v4.3/advanced/auth.html

**Comment by qzhuyan** [comment]
@and-dzh3 any updates?

**Comment by k32** [comment]
No updates for 14+ days, closing.
