### ISSUE TITLE
Non-stop crashing on much retain data. Critical BUG

### ISSUE THREAD

**Issue by igor-d-n** [emqx/emqx#5431]
**Environment**:

- EMQ X version (e.g. `emqx_ctl status`): 4.3.6

- Hardware configuration (e.g. `lscpu`): 
Architecture:        x86_64
CPU op-mode(s):      32-bit, 64-bit
CPU(s):              4

- OS (e.g. `cat /etc/os-release`):
NAME="Ubuntu"
VERSION="18.04.5 LTS (Bionic Beaver)"

- Kernel (e.g. `uname -a`): Linux production-4-8-40gb 4.15.0-65-generic 74-Ubuntu SMP Tue Sep 17 17:06:04 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

**What happened and what you expected to happen**:
Some error in processing big retain data. When you trying to subscribe to big chunk of topics with retain you get this:
2021-08-06T22:01:44.755427+00:00 [error] Process:          <0.1550.23> on node 'd63e4b5093bc@172.19.0.7', Context:          maximum heap size reached, Max Heap Size:    8388608, Total Heap Size:  9054807, Kill:             false, Error Logger:     true, GC Info:          [{old_heap_block_size,3581853},{heap_block_size,5472277},{mbuf_size,703},{recent_size,1878537},{stack_size,25},{old_heap_size,0},{heap_size,2487364},{bin_vheap_size,107999},{bin_vheap_block_size,159072},{bin_old_vheap_size,0},{bin_old_vheap_block_size,75110}]

And connection reestablishing all the time. It's really serious bug! 
I corrected node.dist_buffer_size = 64MB and not effect! It's impossible to process retain messages on subscription at all!

**How to reproduce it (as minimally and precisely as possible)**:
Try to make much retain topics with some data and them subscribe with # to all of them.

**Anything else we need to know?**:

**Comment by qzhuyan** [comment]
@igor-d-n 

`node.dist_buffer_size = 64MB` is not the pam to turn, it has nothing to do with heap size.

pls check the value of `zone.external.force_shutdown_policy` and also  find file `vm.args` and ensure the value of `+hmax` is large enough.

**Comment by igor-d-n** [comment]
zone.external.force_shutdown_policy was not set. Set it to zone.external.force_shutdown_policy = 128000|64MB

in vw.args set +hmax 83886080

But it's the same errors:
```
2021-08-09T10:05:36.197884+00:00 [error] Process:          <0.2155.0> on node 'e31d08797262@172.22.0.9', Context:          maximum heap size reached, Max Heap Size:    8388608, Total Heap Size:  8596446, Kill:             false, Error Logger:     true, GC Info:          [{old_heap_block_size,0},{heap_block_size,8596446},{mbuf_size,0},{recent_size,1580911},{stack_size,21},{old_heap_size,0},{heap_size,4110421},{bin_vheap_size,13},{bin_vheap_block_size,46422},{bin_old_vheap_size,0},{bin_old_vheap_block_size,46422}]
2021-08-09T10:06:53.466444+00:00 [warning] [SYSMON] large_heap warning: pid = <0.1722.0>, info: [{old_heap_block_size,7427328}, {heap_block_size,999631}, {mbuf_size,0}, {stack_size,32}, {old_heap_size,5664001}, {heap_size,165116}], [{initial_call,{proc_lib,init_p,5}},{current_function,{lists,fmerge2_2,5}},{registered_name,emqx_pool_9},{status,running},{message_queue_len,0},{group_leader,<0.1569.0>},{priority,normal},{trap_exit,false},{reductions,1827367},{last_calls,false},{catchlevel,3},{trace,0},{suspending,[]},{sequential_trace_token,[]},{error_handler,error_handler},{memory,67416720},{total_heap_size,8426959},{heap_size,...},{...}|...]
2021-08-09T10:06:53.569910+00:00 [error] Process:          <0.2187.0> on node 'e31d08797262@172.22.0.9', Context:          maximum heap size reached, Max Heap Size:    8388608, Total Heap Size:  11450939, Kill:             false, Error Logger:     true, GC Info:          [{old_heap_block_size,2984878},{heap_block_size,6785622},{mbuf_size,1680520},{recent_size,625009},{stack_size,94},{old_heap_size,199569},{heap_size,2487303},{bin_vheap_size,13},{bin_vheap_block_size,46422},{bin_old_vheap_size,0},{bin_old_vheap_block_size,46422}]
```

**Comment by qzhuyan** [comment]
The size is word size. In 64bit system, one word is 8 bytes.   So 64MB = 8M words.

On the other hand, the client is slow at processing which build a queue in emqx and emqx decides to kill it which is better than bringing down the whole node due to out of memory.

Bumping heap size is just temp solution, I think you need to make client run faster or find other solutions such like shared subscribtions.

**Comment by igor-d-n** [comment]
Thanks for reply.

> The size is word size. In 64bit system, one word is 8 bytes. So 64MB = 8M words.
> 
It was set to 0 = no limit and it's crushing with MaxHeapSize 8Mb I changed it to 1Gb and it's doing the same. Why it's working so?

> On the other hand, the client is slow at processing which build a queue in emqx and emqx decides to kill it which is better than bringing down the whole node due to out of memory.
> 
But server has about 70-80% memory free... May be it's good, but why it's not possible to set time **and** memory limit for that? Sometimes it's better to just add few Gbs of memory than refactoring all service from scratch.

> Bumping heap size is just temp solution, I think you need to make client run faster or find other solutions such like shared subscriptions.
Client can't be slow - it's just subscriber for all data from localhost. I think it's problem in emqx it self. Why it always stuck at 8mb? It's too small for many cases and way it can't just process data in chunk instead of just putting it all in buffer. In future i think i'll remove retain but it's not correct work for broker to use always 8Mb heap size for all processes without any way to change it.

**Comment by zmstone** [comment]
The current implementation in EMQ X retainer is to match, and read all possible message for the subscriber.
This query is done in memory, hence the excessive use of heap size especially when there are large volume (size * count).

We will refactor retainer the future to maybe send retained messages in a read, send then read more loop.

This is not to say though, it will make subscribing to `#` a less worse practice. ;-)

**Comment by igor-d-n** [comment]
> The current implementation in EMQ X retainer is to match, and read all possible message for the subscriber.
> This query is done in memory, hence the excessive use of heap size especially when there are large volume (size * count).
> 
Ok, but how I can increase heap size for such operations? Now main problem is that it's imposible: +hmax or other options do not affect this.

> We will refactor retainer the future to maybe send retained messages in a read, send then read more loop.
> 
> This is not to say though, it will make subscribing to `#` a less worse practice. ;-)
I understand that it's not good but if I need logging all data? I need skip retain somehow or process it. Now I just can't establish connection if there is much retain data.

**Comment by zmstone** [comment]
We’ll discuss it and see if we can work out a mitigation or a easy fix for this issue before we can refactor it.

**Comment by qzhuyan** [comment]
| Ok, but how I can increase heap size for such operations? Now main problem is that it's imposible: +hmax or other options do not affect this.

@igor-d-n Does the client connect to the default zone? which transport? 

zone.external.force_shutdown_policy  is for `default` zone

**Comment by igor-d-n** [comment]
@qzhuyan 
Transport - mqtt tcp 1883 port
zone - don't know, I think it's default because it was not changed in configs

I'm using docker and do no changes in config except this:
```
- EMQX_LOADED_PLUGINS="emqx_management,emqx_auth_mysql,emqx_recon,emqx_retainer,emqx_dashboard"
- EMQX_ACL_FILE=/dev/null
- EMQX_ALLOW_ANONYMOUS=false
- EMQX_ACL_NOMATCH=deny
- EMQX_LOG__LEVEL=warning
- EMQX_AUTH__MYSQL__SERVER=....
- EMQX_AUTH__MYSQL__DATABASE=....
- EMQX_AUTH__MYSQL__USERNAME=...
- EMQX_AUTH__MYSQL__PASSWORD=...
- EMQX_AUTH__MYSQL__PASSWORD_HASH=sha256
- EMQX_AUTH__MYSQL__AUTH_QUERY=....
- EMQX_AUTH__MYSQL__SUPER_QUERY=....
- EMQX_AUTH__MYSQL__ACL_QUERY=....
```
And default vm.args file when trying to set heap:
```
######################################################################
## Erlang VM Args for EMQ X Broker
######################################################################

## NOTE:
##
## Arguments configured in this file might be overridden by configs from `emqx.conf`.
##
## Some basic VM arguments are to be configured in `emqx.conf`,
## such as `node.name` for `-name` and `node.cooke` for `-setcookie`.

## Sets the maximum number of simultaneously existing processes for this system.
+P 2097152

## Sets the maximum number of simultaneously existing ports for this system.
+Q 1048576

## Sets the maximum number of ETS tables
+e 262144

## Sets the maximum number of atoms the virtual machine can handle.
#+t 1048576

## Set the location of crash dumps
#-env ERL_CRASH_DUMP log/crash.dump

## Set how many times generational garbages collections can be done without
## forcing a fullsweep collection.
-env ERL_FULLSWEEP_AFTER 1000

## Heartbeat management; auto-restarts VM if it dies or becomes unresponsive
## (Disabled by default..use with caution!)
#-heart

## Specify the erlang distributed protocol.
## Can be one of: inet_tcp, inet6_tcp, inet_tls
#-proto_dist inet_tcp

## Specify SSL Options in the file if using SSL for Erlang Distribution.
## Used only when -proto_dist set to inet_tls
#-ssl_dist_optfile etc/ssl_dist.conf

## Specifies the net_kernel tick time in seconds.
## This is the approximate time a connected node may be unresponsive until
## it is considered down and thereby disconnected.
-kernel net_ticktime 120

## Sets the distribution buffer busy limit (dist_buf_busy_limit).
+zdbbl 131072

## Sets default scheduler hint for port parallelism.
+spp true

## Sets the number of threads in async thread pool. Valid range is 0-1024.
## Increase the parameter if there are many simultaneous file I/O operations.
+A 4

## Sets the default heap size of processes to the size Size.
#+hms 233

## Sets the default binary virtual heap size of processes to the size Size.
#+hmbs 46422

## Sets the default maximum heap size of processes to the size Size.
## Defaults to 0, which means that no maximum heap size is used.
##For more information, see process_flag(max_heap_size, MaxHeapSize).
+hmax 0

## Sets the default value for process flag message_queue_data. Defaults to on_heap.
#+hmqd on_heap | off_heap

## Sets the number of IO pollsets to use when polling for I/O.
#+IOp 1

## Sets the number of IO poll threads to use when polling for I/O.
## Increase this for the busy systems with many concurrent connection.
+IOt 4

## Sets the number of scheduler threads to create and scheduler threads to set online.
#+S 8:8

## Sets the number of dirty CPU scheduler threads to create and dirty CPU scheduler threads to set online.
#+SDcpu 8:8

## Sets the number of dirty I/O scheduler threads to create.
+SDio 8

## Suggested stack size, in kilowords, for scheduler threads.
#+sss 32

## Suggested stack size, in kilowords, for dirty CPU scheduler threads.
#+sssdcpu 40

## Suggested stack size, in kilowords, for dirty IO scheduler threads.
#+sssdio 40

## Sets scheduler bind type.
## Can be one of: u, ns, ts, ps, s, nnts, nnps, tnnps, db
#+sbt db

## Sets a user-defined CPU topology.
#+sct L0-3c0-3p0N0:L4-7c0-3p1N1

## Sets the mapping of warning messages for error_logger
#+W w

## Sets time warp mode: no_time_warp | single_time_warp | multi_time_warp
#+C no_time_warp

## Prevents loading information about source filenames and line numbers.
#+L

## Specifies how long time (in milliseconds) to spend shutting down the system.
## See: http://erlang.org/doc/man/erl.html
-shutdown_time 30000

## patches dir
-pa data/patches
```

> have you tried to set it to 0 instead?
>
Yes, as i saw it's default and first i didn't change it. Than I experemented with different values and saw that setting it for small values getting emqx to crash but setting it to big values has no effect for process Max Heap Size.

**Comment by qzhuyan** [comment]
@igor-d-n 
I think it is the `zone.external.force_shutdown_policy` in the emqx config file that does the trick.

I think in your last post it was set to 64MB (8M words), have you tried to bump that value instead?

**Comment by igor-d-n** [comment]
> @igor-d-n
> I think it is the `zone.external.force_shutdown_policy` in the emqx config file that does the trick.
> 
> I think in your last post it was set to 64MB (8M words), have you tried to bump that value instead?

@qzhuyan thank you!
Yes! It's working so! It was unexpected. So in logs size is not size in bytes it's size in "words"? Absolutely unexpected) 
There is no info in documentations that its default value is 8M. May be it's better to add there it? 

Close this post if it useless now if you want.

**Comment by zmstone** [comment]
Thank you for the report @igor-d-n, and @qzhuyan for the excellent support.
I'm closing this issue now as the crashing loop is resolved @igor-d-n 
Retainer enhancement feature request has been created in our jira (not public so far).

Please note though, the `force_shutdown_policy` config affects all clients in the entire `zone`.
if you do not have a lot of subscribers which subscribe to `#`,
it perhaps make sense to create a dedicated zone for these subscribers
and leave the default config for `external` zone which serves the other regular clients.

**Comment by zmstone** [comment]
Hi again. 
FYI.
in 5.0 (currently in alpha release stage),
there is a flow control added for retained message reader.
