### ISSUE TITLE
EMQ X Authentication/ACL with PostgreSQL don't work

### ISSUE THREAD

**Issue by PedroPini** [emqx/emqx#5432]
**Environment**:

- EMQ X version (e.g. `emqx_ctl status`):  4.3.5

**What happened and what you expected to happen**: I'm using the docker version of emqx, the broker works fine. I've been trying to use the Postgres authentication, I did the setup and starts but it doesn't validate.

**How to reproduce it (as minimally and precisely as possible)**:
emqx:
    restart: always
    image: emqx/emqx:4.3.5
    ports:
      - 18083:18083
      - 1883:1883
      - 8083:8083
      - 8084:8084
      - 8883:8883
    volumes:
      - ./vol-emqx-data:/opt/emqx/data
      #- ./vol-emqx-log:/opt/emqx/log
      - ./vol-emqx-etc/emqx_auth_pgsql.conf:/opt/emqx/etc/plugins/emqx_auth_pgsql.conf
      - ./vol-emqx-etc/emqx.conf:/opt/emqx/etc/plugins/emqx.conf

**Anything else we need to know?**:

**Comment by qzhuyan** [comment]
Could you please attach the logs of emqx with debug level?

Refer to 
https://docs.emqx.io/en/broker/v4.3/getting-started/log.html

**Comment by k32** [comment]
No updates for 14+ days, closing.
