### ISSUE TITLE
Does emqx support a node rejoining a cluster?

### ISSUE THREAD

**Issue by clannon** [emqx/emqx#5449]
We had a cluster with 3 nodes before, and for some reason later, leave a node alone. This comes a cluster with 2 nodes and a single node while they are already providing services. Now we decide to let the separated node rejoin the cluster...

In the [official documents](https://docs.emqx.cn/broker/v4.2/advanced/cluster.html), I only find how to create a cluster or leave a node. In our situation, will just typing the command "emqx_ctl cluster join emqx01@xxxx" on the separated node machine be ok?

**Comment by clannon** [comment]
> 
> 
> @clannon depends on how the cluster node discovery is configured. yes. `emqx_ctl cluster join emqx01@xxxx ` should be sufficient if three nodes are configured and aligned with the nodes in the cluster.
> 
> For cluster node discovery you can refer to:
> https://docs.emqx.io/en/broker/v4.3/getting-started/cluster.html#node-discovery-and-autocluster

Thanks!

We created the cluster using manual strategy. When the third node was separated, we used the command "emqx_ctl cluster leave", and changed cluster.name, node.name, node.cookie and the emqx_auth_mysql plugin. We will restore the configs before typing the join command.

The data seemed lost on the third node when it was separated, because we found the dashbord password was reset. Does that mean the data will also be lost when it rejoins the cluster? Should we give a notice to the clients better to stop?

**Comment by qzhuyan** [comment]
@clannon

After join the cluster, the 3rd node should pull the latest data (shared cluster wide data ) from other nodes.

Depends on the size of data,  it can create extra load on the existing two nodes.

**Comment by clannon** [comment]
> 
> 
> @clannon
> 
> After join the cluster, the 3rd node should pull the latest data (shared cluster wide data ) from other nodes.
> 
> Depends on the size of data, it can create extra load on the existing two nodes.

Got it! Thank you very much!
