### ISSUE TITLE
消息丢弃

### ISSUE THREAD

**Issue by qq50015883** [emqx/emqx#5464]
**Please describe your problem in detail, if necessary, you can upload the log file through the attachment**:
消息丢失，连接断开，原因未知。

主题监控里面看到的是消息丢失

**Comment by qq50015883** [comment]
![image](https://user-images.githubusercontent.com/19347797/129143275-1e0cd1dd-3606-495d-8bd7-9b14056e38a0.png)

**Comment by qzhuyan** [comment]
@qq50015883 can you enable the debugging and provide debug logs?

https://docs.emqx.io/en/broker/v4.3/getting-started/log.html#log-format
