### ISSUE TITLE
Windows 10 Service Start Failed on Boot

### ISSUE THREAD

**Issue by obi458** [emqx/emqx#547]
Windows 10 Pro Version 1511 Build 10586.218

Using download version for windows of emqttd.

On windows boot service start failed, 
starting service manually service start successfully!

The errors are(windows log):
The emqttd01d1a85c30679f50 service terminated with the following error: 
The configuration registry key could not be read.
emqttd01d1a85c30679f50: Could not get registry keys for erlang service.

Seems an erlang problem!

**Comment by Gilbert-Wong** [comment]
Sorry for so late response, It will be fixed in this [pr](https://github.com/emqx/emqx-rel/pull/378) and released with emqx 3.2.

**Comment by Gilbert-Wong** [comment]
Sorry, @obj458, actually, the windows service start failure problem has been resolved in emqx 3.2-rc.2
