### ISSUE TITLE
Needed some understanding on using rest for publishing

### ISSUE THREAD

**Issue by yashjain4411** [emqx/emqx#5485]
**Please describe your problem in detail, if necessary, you can upload the log file through the attachment**:
Hi everyone,

I had one problem statement. Suppose we have multiple clusters each consisting of x emqx nodes. Now for publishing we will need to send messages to every cluster. I am thinking of 2 possible approaches , 1 is using autoscaling group of publishers which can be emqx nodes/cluster and we can setup bridges to send messages to every cluster from here. Other solution is we can write services and use rest to publish messages to every cluster. I wanted to understand can there can be performance issue in using rest over brigdes

**Comment by qzhuyan** [comment]
Bridge among cluster will be be cheaper I would say.
