### ISSUE TITLE
Implement session hibernation

### ISSUE THREAD

**Issue by phanimahesh** [emqx/emqx#549]
Quoting from previous discussion,

```
[14/04/16, 23:48:59] J Phani Mahesh: If a client disconnected and hasn’t reconnected in a while, we can save the session process state to mnesia and exit the session process. On connection we can try to load up saved session state and continue.
[14/04/16, 23:49:11] J Phani Mahesh: This can allow session persistence between emqttd restarts
```

Proposal: Have a soft-timeout for session inactivity and dump the session to mnesia. Load from mnesia on reconnection.

Advantages:
1. If a client disconnects and reconnects to a new node in a cluster, we have session migration essentially for free.
2. We can have ridiculously long sessions spanning months, reliably even when emqttd is restarted.
3. When dealing with a lot of devices with low activity, memory footprint is greatly reduced.

Also, #548 benefits from this. If session state is in mnesia most of the time additional state can be dumped into mnesia too.

**Comment by joltmode** [comment]
What is the actual status on this?

As I currently understand, if EMQ gets restarted, persistent session data will get lost as currently it is only being stored in memory?

**Comment by HJianBo** [comment]
Yes, it is always lost on all of the versions.

@emqplus Maybe we can try to implement the @phanimahesh 's idea?

**Comment by zmstone** [comment]
Connection process hibernation is already in place. 

WRT message persistence: it is becoming more and more clear to us over the past few months: we should/will not store messages in mnesia.
We are currently investigating other storage engine to provide message persistence with high-availability.
