### ISSUE TITLE
Mnesia ACL not working properly

### ISSUE THREAD

**Issue by roysG** [emqx/emqx#5496]
**Environment**:

- EMQ X version (e.g. `emqx_ctl status`):  4.3.5
- Hardware configuration (e.g. `lscpu`):
Architecture:        x86_64
CPU op-mode(s):      32-bit, 64-bit
Byte Order:          Little Endian
CPU(s):              1
On-line CPU(s) list: 0
Thread(s) per core:  1
Core(s) per socket:  1
Socket(s):           1
NUMA node(s):        1
Vendor ID:           GenuineIntel
CPU family:          6
Model:               63
Model name:          DO-Regular
Stepping:            2
CPU MHz:             2294.524
BogoMIPS:            4589.04
Virtualization:      VT-x
Hypervisor vendor:   KVM
Virtualization type: full
L1d cache:           32K
L1i cache:           32K
L2 cache:            4096K
NUMA node0 CPU(s):   0
Flags:               fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss syscall nx rdtscp lm constant_tsc arch_perfmon rep_good nopl cpuid tsc_known_freq pni pclmulqdq vmx ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm abm cpuid_fault invpcid_single pti ssbd ibrs ibpb tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid xsaveopt md_clear

- OS (e.g. `cat /etc/os-release`):
NAME="Ubuntu"
VERSION="18.04.5 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.5 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic

- Kernel (e.g. `uname -a`):
Linux mqtt1 4.15.0-147-generic #151-Ubuntu SMP Fri Jun 18 19:21:19 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

**What happened and what you expected to happen**:
I run the api command of "ACL Mnesia". 
I tried to run queries get and post but i always get: "Not found"

This is the command i send:
http://ip:18083/api/v4/emqx_acl and i should get: 
Of course i connect with the correct credntials authentication. other request works without problem.

My stack is built with 3 server and i did load balance between them according to your instructions.

**Comment by k32** [comment]
Hello,

This looks like a documentation issue. Starting from 4.3, enterprise and opensource versions of the mnesia authentication plugin were merged, and the API was changed. It looks like only CN version of the docs was updated: https://docs.emqx.cn/broker/v4.3/advanced/acl-mnesia.html#%E4%BD%BF%E7%94%A8-http-api-%E7%AE%A1%E7%90%86-acl-%E8%A7%84%E5%88%99
While this is being fixed, you can refer to the API schema...
https://github.com/emqx/emqx/blob/4.3.6/apps/emqx_auth_mnesia/src/emqx_acl_mnesia_api.erl#L29

**Comment by qzhuyan** [comment]
@roysG No updates for 20days, we close the ticket for now. feel free to open a new one if you need more help.
