### ISSUE TITLE
Redis ACL does not support topic filter subscription

### ISSUE THREAD

**Issue by flex380** [emqx/emqx#5497]
测试发现如果使用Redis ACL验证方式的话,不支持主题过滤器订阅
例如: MQTT.client.subscribe('dziot/+');
无法接收到任何消息, 如果换成: MQTT.client.subscribe('dziot/8d2c379b811fb8d388320be2ca2ef32a'); 就可以接收消息

**Comment by xe5700** [comment]
似乎mysql acl验证方式也有问题，只有$SYS/#这个系统自带的规则有用

**Comment by flex380** [comment]
我没测试其它的验证方式, 不过这可能是同一个问题引起的;

**Comment by xe5700** [comment]
看错了其实没有这个问题，只是我用MQTT explorer测试 订阅#不会把全部主题显示出来而已。

**Comment by qzhuyan** [comment]
@flex380 have you enabled  to allow wildcard subscription in the ACL?

**Comment by qzhuyan** [comment]
Pls update your issue in English please.

**Comment by flex380** [comment]
> @flex380 have you enabled to allow wildcard subscription in the ACL?

yes, i have enabled to allow wildcard subscription, like this:
mqtt.wildcard_subscription = true

**Comment by qzhuyan** [comment]
what is the verion of EMQX? 
Does subscreibe call success?
there are more configs, like per zone. 
Could you please enable debug logs and send us the logs? thanks!

**Comment by flex380** [comment]
> what is the verion of EMQX?
> Does subscreibe call success?
> there are more configs, like per zone.
> Could you please enable debug logs and send us the logs? thanks!

thanks for reply, my broker version is 4.3.7
yes, subscreibe call is successful.
