### ISSUE TITLE
group by with id and window

### ISSUE THREAD

**Issue by sysword** [emqx/emqx#5499]
**Please describe your problem in detail, if necessary, you can upload the log file through the attachment**:
i notice this sql "SELECT count(*) FROM demo GROUP BY ID, TUMBLINGWINDOW(ss, 10);" and i want to know what will happen when an event occured, will it do window agg first and then group items in window results by id or just send them to different windows by id?

**Comment by k32** [comment]
Hello,

Could you please give more context about your question?

**Comment by qzhuyan** [comment]
@terry-xiaoyu maybe you can understand the question here?
