### ISSUE TITLE
Allow cookie based auth in HTTP Publish

### ISSUE THREAD

**Issue by phanimahesh** [emqx/emqx#550]
The title says it all. The reasons are similar to usecases for cookie auth on websocket connections, which was implemented previously.

I have patched our emqttd to support cookie auth for HTTP Publish API, and it has been running in production for a few weeks, but haven't found time to separate the code into a clean patch yet. I'll send a PR on monday to close this.

**Comment by emqplus** [comment]
@phanimahesh, Thanks. I am considering to implement a Zone-Based authentication:

```
Listener -> Zone -> Authentication/ACL
                           -> Session/Queue
                           -> MQTT Parameters
                           -> Rate Limit
```

What's your opinion?

**Comment by Gilbert-Wong** [comment]
Our latest emqx adopt http basic authentication method for rest api publish, and we have no schedule to do acl/auth check for publish api.
