### ISSUE TITLE
100% High CPU on v4.3.6 vs v4.2.6

### ISSUE THREAD

**Issue by mogupta** [emqx/emqx#5506]
**Please describe your problem in detail, if necessary, you can upload the log file through the attachment**:
I run EMQX in production with ~5500 IOT devices.  we were using v4,2,6 docker image before without any trouble. Now when we route the traffic to EMQX v4.3.6 the CPU gets to 100% and never recovers from the peak CPU. Also the devices never come online. 

I would appreciate if you could point me in the right direction. I have tried to load test with 5000 clients, EMQX v4.3.6 works fine with mnseia auth and acl. but with production load CPU utilization never goes down. 

In test environment everything works fine with ~5 clients.

**Comment by k32** [comment]
Hello,
Could you login to the EMQ X shell, run `observer_cli:start()` command and post the output?

**Comment by mogupta** [comment]
Hello @k32 , sorry for the late reply. I am using EMQX in a docker container. Not sure how I can run this command ? 
I tried the following
`docker exec -it emqx_emqxn1.1.r9z1xkd71e2shnpehqcokk84n bash`
bash `observer_cli:start()`

Result :  
`bash-5.0$ observer_cli:start()`
`>`
`>`
`>`

**Comment by k32** [comment]
Hello,
You need to run this command in the Erlang shell, rather than bash shell: 
```
docker exec -it .... bin/emqx remote_console
```

**Comment by mogupta** [comment]
![image](https://user-images.githubusercontent.com/479667/131425195-9d60b12e-5df6-4d52-86db-00b00bf19e45.png)

Empty response

**Comment by k32** [comment]
You need to copy the command including full stop at the end: `observer_cli:start()**.**`

**Comment by mogupta** [comment]
![image](https://user-images.githubusercontent.com/479667/131469782-08583960-f8ad-4032-aee2-f961e4f8cb5f.png)

**Comment by k32** [comment]
Thanks. Could you switch to `reductions` tab? Type `rr` and then press enter.

**Comment by mogupta** [comment]
See below. some times reductions value fluctuates widely, not sure why . Please compare reductions values below
![image](https://user-images.githubusercontent.com/479667/131479805-b0bedb7b-f496-4ece-9672-6fafa2580f60.png)

![image](https://user-images.githubusercontent.com/479667/131479957-58d023e6-defc-4ad2-8313-7a4fcb6d3a19.png)

**Comment by k32** [comment]
Is this a screenshot from the production environment where you see 100% CPU load?

**Comment by mogupta** [comment]
yes but their is no load right now. Since the new version is not stable. Do you want to divert actual traffic to it and sent screenshots again ?

**Comment by mogupta** [comment]
@k32 please advise. Having the new version run in production causes the entire system to stop working.  But I can try to divert the load  to the new version at midnight and share the above screenshots again ?

**Comment by k32** [comment]
Hello,
Sorry for late reply. Before we mess with the production traffic, could you collect some information from the broker that is currently under load:
1) emqx_ctl broker metrics
2) emqx_ctl routes list
3) emqx_ctl clients list
4) emqx_ctl plugins list

**Comment by mogupta** [comment]
emqx_ctl broker metrics
`https://pastebin.com/sTt4fh9C`

emqx_ctl routes list - Note- I have removed prefix e.g `/13ychfk2cf8479283cybek ` from the topics for security reasons. All topic starts with `/{some alphanumeric}` (mongodb id)
`https://paste2.org/UfVek1KJ` 

emqx_ctl clients list
I haven't included it for security reasons. Please let me know if you still need it. I will find a way. 

emqx_ctl plugins list
`https://paste2.org/z7PmFdAL`

**Comment by mogupta** [comment]
@k32 Also wanted to let you know that I am using mnesia authentication and ACL. 

`Under load tests`
If I use sha256 for encryption CPU usage is 100% for few minutes and then it gets normal (under 20%) on 8 Core/ 16 thread VPS
if I use plain for encryption CPU usage is under 50% for few minutes and then it gets normal (under 20%) on 8 Core/ 16 thread VPS

`In production`
new version - The CPU stays at 100% on the new version . I waited for 15+ minutes on 8 Core/ 16 thread VPS (on plain mnseia encryption) 
old version - The CPU usage is under 50% for few minutes and then it gets normal (under 20%) on 8 Core/ 16 thread VPS

**Comment by mogupta** [comment]
![image](https://user-images.githubusercontent.com/479667/131942040-8ee011b4-c276-4679-98c4-32d40b89bb96.png)

**Comment by qzhuyan** [comment]
In https://paste2.org/z7PmFdAL
| Plugin(emqx_retainer, description=EMQ X Retainer, active=true)

@mogupta are you using the function of Retained Messages ? 

I find the retainer plugin is enabled and you have 11k retained topics/messages, which can cause high load. 

If you don't need Retained Messages, you can try to disable it in the plugin.

We have perf improvements for Retained Messages in 5.0 by the way.

note, 4.3.6 enabled retained plugin by default.

**Comment by mogupta** [comment]
@qzhuyan no change in result. CPU is 100% as usual . The newer version dashboard keep reporting higher and higher number of clients connected . right now I have ~5500 active devices but it keeps reports high and higher number as the time passes . CPU stays at 100% . the dip in the CPU usage is because of docker container restart 

I tried to run ` observer_cli:start().` on the new instance but it never gave me an output. I guess because of the high CPU

Going forward:- How about I setup a new 3x powerful server and see if the it can sustain the load . We can then debug which process is consuming high CPU? 

![image](https://user-images.githubusercontent.com/479667/132145403-ceaef2e8-da7f-41b4-8240-cca213f6bcbf.png)

**Comment by mogupta** [comment]
@zhengyupan @k32  I tried a  DO 16 core droplet and it worked. The load was able to drop the CPU from 100% to 10% in about 2 minutes. I tried with and without retained plugin , results are exactly the same. please see below. 

**With retained plugin**
![DO with retained](https://user-images.githubusercontent.com/479667/132779148-6be879e2-6220-48d2-a6d9-b1900e43b2cc.PNG)


**Without retained plugin**
![DO wo retained](https://user-images.githubusercontent.com/479667/132779107-d4aff361-96c0-490c-ac41-f8be2232d0da.PNG)

Having a 16 core CPU for just starting up is an overkill for a small number of clients I tried `observer_cli:start().` but the command line was unresponsive during the booting up process.

Here is the screenshot where the CPU gets stable
![before restart (stable)](https://user-images.githubusercontent.com/479667/132779315-86dc6b2d-f022-47ab-93f4-f4d89c38498a.PNG)

**Comment by zmstone** [comment]
It’s maybe mnesia data repair.
Could you please check how big the data volume is in the `data` dir?

**Comment by mogupta** [comment]
@zmstone data is only 7MB. when migrating to v4.3.6 I am using a complete new docker volume , migrating existing users with a script.

**Comment by zmstone** [comment]
Are the clients very aggressively trying to connect / reconnect?
How many topics do the clients subscribe to?
You have cut the prefixes in the shared routes, are the prefixes unique for each client? Or mostly shared among the clients?

**Comment by mogupta** [comment]
Clients are retrying every 30 seconds
Each client subscribe to average 4 topics
Each client subscribe to `/{mongodb device Id}/${topic}` these prefixes are unique to each client. 
Also I am using uuidv4 as mqtt password. e.g. `22ba02c0-74f7-11e8-b5fc-3d0026b01d06`
username is `abc-{mongodb device id}`

**Comment by zmstone** [comment]
check:
It’s a single node cluster 
Not many wildcard subscriptions 
Topics start with a root "/"
With/without retainer no difference 
Auth mnesia, no other auth plugin enabled 

More questions:
Do you have any rules created?
ACL config?

**Comment by qzhuyan** [comment]
Is it a cluster ? How do you do migration?

**Comment by mogupta** [comment]
> check:
> It’s a single node cluster
> Not many wildcard subscriptions
> Topics start with a root "/"
> With/without retainer no difference
> Auth mnesia, no other auth plugin enabled
> 
> More questions:
> Do you have any rules created?
> ACL config?

 It’s a single node cluster   yes
Not many wildcard subscriptions all clients subscribe with either /# or /topic 
Topics start with a root "/"   yes
With/without retainer no difference  yes
Auth mnesia, no other auth plugin enabled  yes

Do you have any rules created?  No
ACL config? yes all clients have /deviceId/#  pubsub ACL permissions

**Comment by mogupta** [comment]
> Is it a cluster ? How do you do migration?

Nope, I migrate by starting with a clean install . then using a script to add users and ACL configs

**Comment by mogupta** [comment]
Here is a quick way to reproduce the issue.

1. Create a single node cluster using docker-compose
2. Create 5000 client users and their ACL with mnesia HTTP API
3. load test with the following code . Here we subscribe to /deviceId/# on connect and every 0 to 5 minutes interval send 3 messages

```
client.on('connect', function () {
   client.subscribe(`/${device._id}/#`);
        setInterval(() => {
            client.publish(`/${device._id}`, Math.round(Math.random() * 100000) + '')
            client.publish(`/${device._id}/info`, Math.round(Math.random() * 100000) + '');
            client.publish(`/${device._id}/status`, Math.round(Math.random() * 100000) + '');
        }, Math.round(Math.random() * 5 * 60 * 1000));
    })
```

Results n i5-8400 6 core 
v4.2.6
![f3](https://user-images.githubusercontent.com/479667/132932773-04349220-3f8c-4bb5-a031-ebe2963b39ea.PNG)
Barely stays at 100% CPU 

v4.3.6
![f2](https://user-images.githubusercontent.com/479667/132932777-42400e48-50bf-4a88-b91d-d89619188b10.PNG)
Stays at 100% CPU for about 1 minute. If we increase number of subscription topics to 5, instead of using /#, It stays at 100% for around 5 minutes

**Comment by zmstone** [comment]
Thanks for the steps to reproduce.
Could you help to quick verify without the root ‘/‘?
I.e. just `${device._id}/#`

**Comment by mogupta** [comment]
@zmstone 
With 5000 clients ( did much better but not better than old emqx version)
![image](https://user-images.githubusercontent.com/479667/132945328-524b409b-d289-4b2a-8668-0ec6a4e8c6ba.png)

With 5000 clients and 5 subscriptions

**Comment by mogupta** [comment]
@zmstone found and tested the option `listener.tcp.external.max_conn_rate`

Results
max_conn_rate= 20 ,  5000 clients, 6 subscriptions . 
![6 sub, 2 pub, max 20, 5000 clients](https://user-images.githubusercontent.com/479667/133028022-0d99d7e8-aaa6-402c-8313-ed8397f8c9f2.PNG)

max_conn_rate= 50,  5000 clients, 6 subscriptions . 
![6 sub, 2 pub, max 50, 5000 clients](https://user-images.githubusercontent.com/479667/133028038-2db25180-24ef-417c-ad7b-e196e8ea330d.PNG)

max_conn_rate= 100,  5000 clients, 6 subscriptions . 
![6 sub, 2 pub, max 100, 5000 clients](https://user-images.githubusercontent.com/479667/133028052-b8633fd3-0ea1-4f9e-b260-4d64ee061287.PNG)

`max_conn_rate` should be limiting the CPU usage.  but its not

**Comment by zmstone** [comment]
Hi @mogupta 
Did you change default configs for below two keys:
`broker.perf.route_lock_type` and  `broker.perf.trie_compaction` ?

**Comment by mogupta** [comment]
Nope

**Comment by zmstone** [comment]
@qzhuyan Need you help with a deeper investigation.

**Comment by qzhuyan** [comment]
| Not many wildcard subscriptions all clients subscribe with either /# or /topic
@mogupta how many clients subscribes `/#` ? If there are many it could create a high lock contetions during subscriptions.

Could you reproduce the issue with emqtt_bench tool with `-i 0` in your test env ? emqtt_bench default uses 10ms delay in between, `-i 0` change it to no delay.

**Comment by qzhuyan** [comment]
In 
| emqx_ctl broker metrics
| https://pastebin.com/sTt4fh9C

There are 350k conns and 500k subs that are handled, are we really talking about 5k clients?

@mogupta  Could you dump the metrics before and after your test/migration?

```
emqx_ctl broker metrics
```

**Comment by mogupta** [comment]
> In
> | emqx_ctl broker metrics
> | https://pastebin.com/sTt4fh9C
> 
> There are 350k conns and 500k subs that are handled, are we really talking about 5k clients?
> 
> @mogupta Could you dump the metrics before and after your test/migration?
> 
> ```
> emqx_ctl broker metrics
> ```

https://pastebin.com/axaKQL1L

**Comment by mogupta** [comment]
> | Not many wildcard subscriptions all clients subscribe with either /# or /topic
> @mogupta how many clients subscribes `/#` ? If there are many it could create a high lock contetions during subscriptions.
![image](https://user-images.githubusercontent.com/479667/133193535-a23ee9ef-c8a1-43f3-867d-adcf799a88a4.png)

About 400 clients subscribe to /{deviceId}/# . See screenshot for real production stats

> Could you reproduce the issue with emqtt_bench tool with `-i 0` in your test env ? emqtt_bench default uses 10ms delay in between, `-i 0` change it to no delay.

I tried with this option. But cou;dn't reproduce the issue. My clients connect and subscribe on connect . The benchmark tool doesn't do that as per my understanding. it either connects or send pubs or subs right ? This isn't a real world benchmark ?

**Comment by qzhuyan** [comment]
> https://pastebin.com/axaKQL1L

5k clients but 25k subs? 

About emqtt bench, it can mostly generate the traffic pattern in load test. Which part do you think it is missing?

**Comment by mogupta** [comment]
> > https://pastebin.com/axaKQL1L
> 
> 5k clients but 25k subs?
Yes. Each client subscribes to an average 5 topics. This has changed in the past 6 months. Old IOT devices connect with either /# or 5 topics . newer ones connect with only 1 sub. 

> 
> About emqtt bench, it can mostly generate the traffic pattern in load test. Which part do you think it is missing?
How do I connect 5K clients and right after connection how do I sub and pub ? From the emqx_bench ocs I can see that I can only do conn/ sub / pub one at a time ? If I have this solution I will try to reproduce the issue with emqx_bench. You can try my node script if that works for you ? 

Question 
How can I limit new connection requests so that we allow only a small number of clients to connect every second to make sure CPU doesn't reach a 100% 
Similarly how to limit pub and subs when all clients are trying to connect simultaneously.

**Comment by qzhuyan** [comment]
> How do I connect 5K clients and right after connection how do I sub and pub ? From the emqx_bench ocs I can see that I can only do conn/ sub / pub one at a time ? If I have this solution I will try to reproduce the issue with emqx_bench. You can try my node script if that works for you ?

with the following command, it can stimulate your scenario
it starts 5k clients simultaneously each one connects to $emqx then subscribes to 5 wildcard topics that have clientid embedded (with `%c`)


```
emqtt_bench sub  $emqx -t "/#" -t "/topic1/%c/+" -t "/topic2/%c/+" -t "/topic3/%c/+" -t "/topic4/%c/+" -c 5000 --prefix "prefix$nodeid"  -i 0
```

let me know if it can reproduce the issue or not.

**Comment by mogupta** [comment]
I was able to reproduce the issue

command used
`sudo docker run -it emqx-bench sub $emqx -t "5b35f87b9ae5e600a4cd080e/a" -t "5b35f87b9ae5e600a4cd080e/b" -t "5b35f87b9ae5e600a4cd080e/c" -t "5b35f87b9ae5e600a4cd080e/d" -h 192.168.29.198 -p 21883 -u device-5b35f87b9ae5e600a4cd080e -P 22ba0 -c 5000 -i 0`

with v4.2.6
![image](https://user-images.githubusercontent.com/479667/133213238-bd024dcf-9ad9-47d6-8a9f-73630f6de59e.png)

with v4.3.6
![image](https://user-images.githubusercontent.com/479667/133213324-01c3f88f-cebf-43f4-94ce-5b66f9a27454.png)

**Comment by qzhuyan** [comment]
@mogupta just curious why not use '%c' in the topic?

From
![](https://user-images.githubusercontent.com/479667/133193535-a23ee9ef-c8a1-43f3-867d-adcf799a88a4.png)

I can see there are many topics.

And just for confirmation, are the clients in real-world use the same username&password?

**Comment by qzhuyan** [comment]
For
> ![](https://user-images.githubusercontent.com/479667/133213238-bd024dcf-9ad9-47d6-8a9f-73630f6de59e.png)


pls include the timeline also the meaning for each color such like %user %sys %ide etc...

**Comment by mogupta** [comment]
> @mogupta just curious why not use '%c' in the topic?

I wanted to test on real AUTH and ACL data stored in Mnesia.  Since I cannot (not sure) run emqx_bench using a pre stored databases (like I can do in nodejs) that is why used one of the 5000 clients username password stored in mnesia. 

> From
> ![](https://user-images.githubusercontent.com/479667/133193535-a23ee9ef-c8a1-43f3-867d-adcf799a88a4.png)
> 
> I can see there are many topics.
> 
> And just for confirmation, are the clients in real-world use the same username&password?

Nope

**Comment by mogupta** [comment]
> For
> 
> > ![](https://user-images.githubusercontent.com/479667/133213238-bd024dcf-9ad9-47d6-8a9f-73630f6de59e.png)
> 
> pls include the timeline also the meaning for each color such like %user %sys %ide etc...

![image](https://user-images.githubusercontent.com/479667/133216771-590ddd4c-d8e4-4b6a-bde5-0a6121e25553.png)

![image](https://user-images.githubusercontent.com/479667/133216693-bb9af2ea-08ee-4625-9f59-7e4517c3c1a8.png)

**Comment by qzhuyan** [comment]
could you run and send us the output?
```
emqx eval 'mnesia:table_info(emqx_user,all)'
```

**Comment by mogupta** [comment]
> could you run and send us the output?
> 
> ```
> emqx eval 'mnesia:table_info(emqx_user,all)'
> ```

[{access_mode,read_write},
 {active_replicas,['emqx@node1.emqx.io']},
 {all_nodes,['emqx@node1.emqx.io']},
 {arity,4},
 {attributes,[login,password,created_at]},
 {checkpoints,[]},
 {commit_work,[]},
 {cookie,{{1631356396510602300,-576460752303423391,1},'emqx@node1.emqx.io'}},
 {cstruct,{cstruct,emqx_user,set,[],
                   ['emqx@node1.emqx.io'],
                   [],[],0,read_write,false,[],[],false,emqx_user,
                   [login,password,created_at],
                   [],[],
                   [{ets,[{read_concurrency,true}]}],
                   {{1631356396510602300,-576460752303423391,1},
                    'emqx@node1.emqx.io'},
                   {{2,0},[]}}},
 {disc_copies,['emqx@node1.emqx.io']},
 {disc_only_copies,[]},
 {external_copies,[]},
 {frag_properties,[]},
 {index,[]},
 {index_info,{index,set,[]}},
 {load_by_force,false},
 {load_node,'emqx@node1.emqx.io'},
 {load_order,0},
 {load_reason,local_only},
 {local_content,false},
 {majority,false},
 {master_nodes,[]},
 {memory,247204},
 {ram_copies,[]},
 {record_name,emqx_user},
 {record_validation,{emqx_user,4,set}},
 {size,9850},
 {snmp,[]},
 {storage_properties,[{ets,[{read_concurrency,true}]}]},
 {storage_type,disc_copies},
 {subscribers,[]},
 {type,set},
 {user_properties,[]},
 {version,{{2,0},[]}},
 {where_to_commit,[{'emqx@node1.emqx.io',disc_copies}]},
 {where_to_read,'emqx@node1.emqx.io'},
 {where_to_wlock,{['emqx@node1.emqx.io'],false}},
 {where_to_write,['emqx@node1.emqx.io']},
 {wild_pattern,{emqx_user,'_','_','_'}}]

**Comment by mogupta** [comment]
Any updates guys? @k32 @zmstone @qzhuyan

**Comment by qzhuyan** [comment]
> Any updates guys? @k32 @zmstone @qzhuyan 
 
I think we have enough information to start to work on it. I put this ticket in my backlog.

I will try to reproduce the issue in my local env first.

But from what I understand the perf issue is not related to subscribe calls. I suspect something in the Mnesia auth plug-in.

Would be helpful if you could try to disable the mnesia auth plugin and check how it performs.

**Comment by mogupta** [comment]
Tried mongodb plugin with plain hashing Here is the result. Maximum 60% CPU usage with my nodejs script
![image](https://user-images.githubusercontent.com/479667/133914689-ff9541fb-131b-4c08-be84-fba8f05d92ac.png)

**Comment by mogupta** [comment]
Migrating to redis. Here is the test result with 10K clients. Awesome performance

![image](https://user-images.githubusercontent.com/479667/133965328-11d01fb9-7fde-4458-b24d-f8cc075702f7.png)
