### ISSUE TITLE
emqA forwards messages to emqB failed

### ISSUE THREAD

**Issue by zhengguoxin** [emqx/emqx#5535]
- EMQ X version (e.g. `emqx_ctl status`): 4.3.5
- OS (e.g. `cat /etc/os-release`): docker + ubuntu
- Erlang/OTP version (in case you build emqx from source code): 23.2.7.2-emqx-2/11.1.8
- Others:

see as below:
[http://1234bot.com/aaaPic/hLQ5rx.png](url)

the clients are connected to emqA, i need to forwards all clients messages to emqB。but i received nothing in emqB after congfiged.

**Comment by k32** [comment]
Hello,
Could you run `emqx_ctl cluster status` command on both emqA and emqB?

**Comment by zhengguoxin** [comment]
This problem can be closed because data can actually be received, but only undefined. You can refer to another question I asked: https://github.com/emqx/emqx/issues/5543  thank you！
