### ISSUE TITLE
Bad Arguments when Web Hook Resource path contains query params

### ISSUE THREAD

**Issue by bgsuello** [emqx/emqx#5537]
**Environment**:
- EMQ X version:  `4.3.7`

**What happened and what you expected to happen**:
- When path contains query params in rules actions, ex: 
`objects/messages?sv=2019-02-02&st=2021-08-21T17%3A59%3A49Z&se=2031-08-22T17%3A59%3A00Z&sp=a&sig=at1cYuD%2BCdnwhHeDns%3D`

**How to reproduce it (as minimally and precisely as possible)**:
- Create a rule with webhook resource and set the path in actions to a value that contains a query params

**Anything else we need to know?**:
- I'm sending the payload via webhook to Azure Storage.

**Comment by mntolia** [comment]
Has this issue been fixed?

**Comment by zmstone** [comment]
It is now supported in EMQX v5.
for example (based on v5.5):

<img width="1084" alt="image" src="https://github.com/emqx/emqx/assets/164324/7b348ce9-8043-4a7c-aab0-e61ed9ad9e22">
