### ISSUE TITLE
always disconnect with code 145

### ISSUE THREAD

**Issue by gam2046** [emqx/emqx#5541]
Running 4.2.14 in Docker

Here are some relevant environment variable configurations :

```
    - "EMQX_NAME=emqx"
    - "EMQX_HOST=1.2.3.4"
    - "EMQX_CLUSTER__DISCOVERY=dns"
    - "EMQX_CLUSTER__DNS__NAME=example.com"
    - "EMQX_CLUSTER__DNS__APP=emqx"
    - "EMQX_CLUSTER__PROTO_DIST=inet_tcp"
    - "EMQX_ALLOW_ANONYMOUS=false"
    - "EMQX_MQTT__MAX_PACKET_SIZE=5MB"
    - "EMQX_MQTT__IGNORE_LOOP_DELIVER=true"
    - "EMQX_ZONE__EXTERNAL__MAX_PACKET_SIZE=5MB"
    - "EMQX_LISTENER__TCP__EXTERNAL__SEND_TIMEOUT=5s"
    - "EMQX_LISTENER__TCP__EXTERNAL__BACKLOG=10240"
    - "EMQX_ZONE__EXTERNAL__ACL_DENY_ACTION=disconnect"
    - "EMQX_AUTH__HTTP__AUTH_REQ=http://emq-acl:8080/login"
    - "EMQX_AUTH__HTTP__AUTH_REQ__METHOD=post"
    - "EMQX_AUTH__HTTP__AUTH_REQ__PARAMS=c=%c,u=%u,p=%P"
    - "EMQX_AUTH__HTTP__ACL_REQ=http://emq-acl:8080/acl"
    - "EMQX_AUTH__HTTP__ACL_REQ__METHOD=post"
    - "EMQX_AUTH__HTTP__ACL_REQ__PARAMS=c=%c,u=%u,p=%P,t=%t,a=%A"
    - "EMQX_BROKER__SHARED_DISPATCH_ACK_ENABLED=true"
    - "EMQX_ZONE__EXTERNAL__MAX_AWAITING_REL=0"
    - "EMQX_ZONE__EXTERNAL__AWAIT_REL_TIMEOUT=10s"
    - "EMQX_ZONE__EXTERNAL__MAX_MQUEUE_LEN=0"
    - "EMQX_ZONE__EXTERNAL__MAX_INFLIGHT=0"
    - "EMQX_LISTENER__TCP__EXTERNAL__MAX_CONN_RATE=20000"
    - "EMQX_LISTENER__WS__EXTERNAL__PROXY_PORT_HEADER=X-Forwarded-Port"
    - "EMQX_LISTENER__WSS__EXTERNAL__VERIFY=verify_none"
    - "EMQX_BROKER__ROUTE_BATCH_CLEAN=on"
    - "EMQX_SYSMON__LONG_GC=1000ms"
```

When there are about 1000~2000 client (Eclipse Paho C v5) devices sending messages to topic A at the same time, another client (Eclipse Paho Java v5) subscribed to topic A will often be disconnected, then reconnected, and disconnected again. the disconnect status code returned by the Java side is usually 145, at this time if restart the Java side of the client, or restart EMQX can work properly for a period of time, and then disconnected and reconnected again.

How should I troubleshoot this? Does it have anything to do with the fact that the EMQX CPU usage is usually very high (>90%) when this happens?

This is some configuration information on the Java side (written in Kotlin)

```kotlin
val clientId = "test_client"
val mPersistence = MemoryPersistence()
val mClient = MqttAsyncClient("tcp://example.com:1883", clientId, this.mPersistence)
val options = with(MqttConnectionOptions()) {
                    isCleanStart = false
                    keepAliveInterval = 5
                    userName = "test"
                    password = "test".toByteArray()
                    isAutomaticReconnect = true
                    sessionExpiryInterval = 60
                    setAutomaticReconnectDelay(1, 5)
                    receiveMaximum = 65535
                    maximumPacketSize = null
                    this
                }
mClient.connect(options)
```

This document (https://www.emqx.com/en/blog/mqtt5-new-features-reason-code-and-ack ) shows that 145 means `Packet Identifier in use`, so how should this be resolved?

**Comment by k32** [comment]
Hello,
Your clients should have unique `clientId`s . From MQTT specification:

```
If validation is successful the Server performs the following steps.
1.     If the ClientId represents a Client already connected to the Server then the Server MUST disconnect the existing Client [MQTT-3.1.4-2].
```
...

**Comment by gam2046** [comment]
> If validation is successful the Server performs the following steps.
> 1.     If the ClientId represents a Client already connected to the Server then the Server MUST disconnect the existing Client

The client ID is unique, the Java client was originally able to connect to EMQX normally, but after running for a while, maybe a few hours or a few days, it will automatically fail to reconnect and the above message will appear.

**Comment by k32** [comment]
Ok, I am not very familiar with the Java interface. From the code snippet it looked like clientId is a constant. In this case, could you share emqx.log file from your broker nodes?
