### ISSUE TITLE
Nodejs Cluster with MQTT client

### ISSUE THREAD

**Issue by ambaradhikari** [emqx/emqx#5554]
I have a nodejs engine that uses MQTT to subscribe to messages from many IoT devices. As the number of IoT devices has increased, I want to run the nodejs engine in a cluster mode. This results in every cluster receiving all the MQTT messages. Is there a way to avoid this? A way in which one MQTT message will be received only once and the load of servicing the messages can be equally distributed.
Setup:
Nodejs Engine with MQTT client running via pm2 in an EC2 instance.
MQTT broker running in another EC2 instance.

**Comment by k32** [comment]
Hello,
Could you clarify how do you integrate the nodejs engine with EMQ X? Are you using rule engine "data to web server" feature?

**Comment by ambaradhikari** [comment]
yes.. Node engine is running  MQTT Client (for communication with the IoT devices using publish and subscribe) and REST APIs(for communicating with the Mobile App or Webpages)..

**Comment by k32** [comment]
Sorry, it's still not clear to me how EMQX broker fits into the picture. Could you provide a simplified diagram of your services?

**Comment by ambaradhikari** [comment]
i am running MQTT client in the node engine using npm package mqtt..  
and when i use pm2 to create cluster of node server engine, then each cluster will have its own Mqtt client.. 
and when IoT devices publishes a message, then all the clusters of node engine will receive the data..

**Comment by k32** [comment]
I see, thanks. Perhaps using shared subscription will help? https://docs.emqx.io/en/broker/v4.3/advanced/shared-subscriptions.html#shared-subscription

**Comment by ambaradhikari** [comment]
Thank you .. it helped..
