### ISSUE TITLE
"username not found" "password error" -- login error msg seems too specific

### ISSUE THREAD

**Issue by zhangflonf** [emqx/emqx#5563]
**Environment**:

- EMQ X version (e.g. `emqx_ctl status`):  4.3.5
- Hardware configuration (e.g. `lscpu`): vm
- OS (e.g. `cat /etc/os-release`): ubuntu 18.04
- Kernel (e.g. `uname -a`): Linux hndx-Standard-PC-i440FX-PIIX-1996 5.4.0-42-generic #46~18.04.1-Ubuntu SMP Fri Jul 10 07:21:24 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
- Erlang/OTP version (in case you build emqx from source code): 
- Others:

**What happened and what you expected to happen**:
When doing security check, I tried to use different username/passwords to login, and found that when username is false, it shows error msg "username not found"; when password is false, it shows error msg "password error" -- it's too specific that attacker can attempt a Exhaustive Attack to figure out username.

**How to reproduce it (as minimally and precisely as possible)**:
Log in with false username/password.

**Anything else we need to know?**:
Advise that error msg can be "username/password error", to improve security. Or if there is anyway working around this issue, it would be of great help if you could let me know.

Thanks a lot!

**Comment by k32** [comment]
Hello,
Thanks, this makes sense.
