### ISSUE TITLE
Error transforming datatype for: cluster.autoclean, such as "5m0s"

### ISSUE THREAD

**Issue by kiragoo** [emqx/emqx#5565]
While developing the operator about emqx, the serialization of time.Duration such as "5m" is "5m0s", for example the filed of cluster.autoclean. 
In the phase transform_datatypes, the emqx application returns errors. 
The details of the log as following :
 $ kubectl logs -f emqx-sample-0 
2021-08-25T08:09:04.631504+00:00 [error] Error generating configuration in phase transform_datatypes
2021-08-25T08:09:04.631577+00:00 [error] Error transforming datatype for: cluster.autoclean
2021-08-25T08:09:04.631640+00:00 [error] Invalid duration value: 5m0s
cluster.autoclean = "5m0s"
cluster.autoheal = "on"
cluster.discovery = "k8s"
cluster.name = "emqxample"
cluster.proto_dist = "inet_tcp"
listener.ssl.external.acceptors = "32"
listener.ssl.external.max_connections = "102400"
listener.tcp.external.acceptors = "64"
listener.tcp.external.max_connections = "1024000"
listener.ws.external.acceptors = "16"
listener.ws.external.max_connections = "102400"
listener.wss.external.acceptors = "16"
listener.wss.external.max_connections = "102400"
log.to = "console"
node.max_ets_tables = "2097152"
node.max_ports = "1048576"
node.name = "emqx-sample-0@172.19.98.51"
node.process_limit = "2097152"
rpc.port_discovery = "manual"
**Environment**:
 - Container
 - docker
- EMQ X version (e.g. `emqx_ctl status`): emqx: 4.3.7

**Comment by Rory-Z** [comment]
Fixed in 4.3.8
