### ISSUE TITLE
Support networking.k8s.io/v1 for ingress

### ISSUE THREAD

**Issue by joggeli34** [emqx/emqx#5604]
Ingresses should use the stable api "networking.k8s.io/v1". The v1beta1 will be deprecated more and more (for example nginx-ingress-1.0.0 already removed support)

**Comment by qzhuyan** [comment]
@joggeli34 thanks for reporting we will have a update on it.

**Comment by AlexanderBabel** [comment]
@qzhuyan I created a PR that fixes this issue. Can you please review it? #5677
