### ISSUE TITLE
You've tried to set exhook.request_timeout, but there is no setting with that name

### ISSUE THREAD

**Issue by hydaizd** [emqx/emqx#5624]
This error occurred when I added the configuration exhook. request_timeout = 3s to the emqx_exhook. conf file.
This configuration is available in apps/emqx_exhook/etc/emqx_exhook.conf. If I want to change this value, what should I do?

**Comment by k32** [comment]
Hello, 
Which version of EMQ X are you using?

**Comment by hydaizd** [comment]
The EMQ X version is 4.3.5

**Comment by HJianBo** [comment]
Hi, @hydaizd These options are included in 4.3.8 and we are planning to release it. You may need to wait a while.

Or you can just compile the `main-v4.3` branch to get the latest v4.3.x version.

**Comment by hydaizd** [comment]
OK, Thanks
