### ISSUE TITLE
Authentication fail in plain mode

### ISSUE THREAD

**Issue by wallace-hu** [emqx/emqx#5672]
Hi  I am using emqx enterprise version 4.3.1, and  testing the mnesia authentication function. 
 
When i config the mnesia plugin with below setting:

```
## Password hash.
##
## Value: plain | md5 | sha | sha256 | sha512
auth.mnesia.password_hash = sha256

##--------------------------------------------------------------------
## ClientId Authentication
##--------------------------------------------------------------------

## Examples
auth.client.1.clientid = test_id
auth.client.1.password = test_passwd
```

Then using the MQTT.fx with plain clientid and password  connecting the EMQX ,It succeed.

But if i modify the auth.mnesia.password_hash = plain.  then use the same plain clientid and password,  I got failed connection.

So my question is that what is the difference between "plain" and "sha256" mode. In my understanding,  If using "plain" mode, I should use the plain clientid <test_id> and password<test_passwd>  in the connection.

While if using "sha256", I should use  clientid<test_id> and the sha256 encrypted  password<a89293c100fd6f945750883727a7bcdb98bfc4020b231285aca2127d41654627>.

It seems i got wrong understanding,  What should i do if i want to take the sha256 encrypted text when connecting to the EMQ?

**Comment by k32** [comment]
Hello,

You need to re-create all users after changing the hashing method. `emqx_auth_mnesia` plugin cannot change the existing hashes.
