### ISSUE TITLE
V4.3.2 开启HTTP ACL 发布权限控制问题

### ISSUE THREAD

**Issue by paulcai** [emqx/emqx#5680]
我开启了HTTP ACL ，订阅的时候，后台返回 403 能正常阻断没有权限的订阅，但是，向主题发布消息的，我后台同样返回 403 主题却显示发布成功，订阅失败和发布成功截图如下，有哪位大神知道是什么原因导致么，已经排查了半天了！！

![1](https://user-images.githubusercontent.com/10895021/132438001-e8df55d9-cad4-4321-b16d-6a3c7997a2a9.png)

![2](https://user-images.githubusercontent.com/10895021/132438012-c3372133-fa6c-4825-85db-6e94f7aea998.png)

**Comment by tigercl** [comment]
@paulcai Publish and subscribe are the same ACL processing code, do you use other ACL plugins? And it’s best to check whether your server really returned 403 by capturing packets.

**Comment by paulcai** [comment]
> @paulcai Publish and subscribe are the same ACL processing code, do you use other ACL plugins? And it’s best to check whether your server really returned 403 by capturing packets.

![3](https://user-images.githubusercontent.com/10895021/132453542-145d5028-1139-4e4c-9c1a-6e1bf1826ee0.png)
![4](https://user-images.githubusercontent.com/10895021/132453553-89a06f1e-1493-4d2d-968e-021e84676597.png)

**Comment by qzhuyan** [comment]
@paulcai could you provide debug log?
