### ISSUE TITLE
question about Rule in dashboard

### ISSUE THREAD

**Issue by peterpanBest** [emqx/emqx#5697]
SELECT
  payload as data,
  clientid
FROM
  "pub/topic/system"

JSON: 
{
    clientid: ${clientid}
}

i cant get this json, but 

JSON: 
{
    data: ${data}
}

i can get this json, so what's wrong i did ?
Thanks !

**Comment by qzhuyan** [comment]
@peterpanBest which EMQX version are you using?

**Comment by peterpanBest** [comment]
@qzhuyan 
My EMQ X Broker version is v4.3.5

**Comment by k32** [comment]
Hello,
I cannot reproduce this problem with the SQL tester tool. I get the following results with the SQL query that you provided:
```
{
  "data": "{\"msg\":\"hello\"}",
  "clientid": "c_emqx"
}
```
Could you show a screenshot of your rule in the rule engine?

**Comment by peterpanBest** [comment]
@k32 Hello, Thanks for ur help ！
