### ISSUE TITLE
HTTP API: POST /api/v4/mqtt/publish Needs to  support  MQTT 5.0 user properties 

### ISSUE THREAD

**Issue by lynn2009** [emqx/emqx#5702]
Need to enhance the POST /api/v4/mqtt/publish API to support MQTT 5.0 user properties.

Truly support MQTT5.0

**Comment by zmstone** [comment]
user properties is now supported in v5.

https://docs.emqx.com/en/enterprise/v5.5/admin/api-docs.html#tag/Publish/paths/~1publish/post

<img width="1080" alt="image" src="https://github.com/emqx/emqx/assets/164324/74e82a40-c566-4177-803f-bb127c7d83e2">
