### ISSUE TITLE
Ack of message delivered to recipients

### ISSUE THREAD

**Issue by 87sanchavan** [emqx/emqx#571]
Hi there ,

We are using emqttd for group chat where images and video will be sent.  We are uploading medias on AWS S3 and sending its thumbnail as part of message to emqttd. 

We want to delete  images/videos from AWS S3 once they delivered to recipients . so my question how would we know that thumbnails are received by users so we can delete the media files from AWS S3.

Regards
Sanjay

**Comment by Gilbert-Wong** [comment]
@87sanchavan So sorry for late response, if you want to send thumbnail as payload of mqtt publish message to client and ensure that the thumbnails are recevied by users, you should set the message qos lager than 0. For example, qos 1 or qos 2, these qos level would ensure that the message has been received by users.
