### ISSUE TITLE
4.3.x web hook post fail.

### ISSUE THREAD

**Issue by GordonHuangYong** [emqx/emqx#5716]
1. the checking of posting data with curl successfully!
使用curl命令提交数据是正常的;
```
curl -i  -X POST "http://sound.xxxxxx.com/mqtt/emqConnectStatus.do" -H 'Content-Type: application/json;' -d '{ 
  "username": "debug",
  "timestamp": 1631371183768,
  "sockname": "0.0.0.0:1883",
  "reason": "debug",
  "proto_ver": 5,
  "proto_name": "MQTT",
  "peername": "192.168.0.10:56431",
  "node": "emqx@127.0.0.1",
  "mountpoint": "undefined",
  "metadata": {
    "rule_id": "test_ruleead5d37c"
  },
  "keepalive": 60,
  "is_bridge": false,
  "expiry_interval": 3600,
  "event": "client.connected",
  "connected_at": 1631371183768,
  "clientid": "wt2000_866714044943685x",
  "clean_start": true
}'
HTTP/1.1 200 
Server: nginx
Date: Sat, 11 Sep 2021 14:40:08 GMT
Content-Length: 0
Connection: keep-alive
```
2. but posted fail with resources(web hook)
但是emqx 规则中的资源(web_hook)提交错误, 日志如下.
```
[warning] wt2000_866714044943685x@101.232.78.103:60654 HTTP request failed with path: <<"/mqtt/emqConnectStatus.do">> status code: 400
```
this is the rule blew
```
SELECT * FROM "$events/client_connected","$events/client_disconnected" WHERE 1
```
this is the resource setting
![image](https://user-images.githubusercontent.com/20039800/132953275-13ea83f6-e945-4004-b890-497538cd4d4a.png)

3. after downgrade to 4.2.14, and then data can be posted successfully
降级到4.2.14后, 发现webhook资源提交到成功

**Environment**:

- EMQ X version (e.g. `emqx_ctl status`): 4.3.8
- Hardware configuration (e.g. `lscpu`):
```
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                2
On-line CPU(s) list:   0,1
Thread(s) per core:    2
Core(s) per socket:    1
Socket(s):             1
NUMA node(s):          1
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 79
Model name:            Intel(R) Xeon(R) CPU E5-2682 v4 @ 2.50GHz
Stepping:              1
CPU MHz:               2499.996
BogoMIPS:              4999.99
Hypervisor vendor:     KVM
Virtualization type:   full
L1d cache:             32K
L1i cache:             32K
L2 cache:              256K
L3 cache:              40960K
NUMA node0 CPU(s):     0,1
Flags:                 fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx pdpe1gb rdtscp lm constant_tsc rep_good nopl nonstop_tsc eagerfpu pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch invpcid_single ibrs ibpb stibp fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm rdseed adx smap xsaveopt arat spec_ctrl intel_stibp
```
- OS (e.g. `cat /etc/os-release`):
```
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
```
- Kernel (e.g. `uname -a`):
```
Linux iZuf6busydk4rcc7ki2l7kZ 3.10.0-1062.12.1.el7.x86_64 #1 SMP Tue Feb 4 23:02:59 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by qzhuyan** [comment]
looks like it is the web application that handles `emqConnectStatus.do` reply with `400 Bad requests`.

Could you enable debug log to check what content emqx has sent to the web server? 

Could you also share the config file `etc/plugins/emqx_web_hooks.conf`?

**Comment by GordonHuangYong** [comment]
> looks like it is the web application that handles `emqConnectStatus.do` reply with `400 Bad requests`.
> 
> Could you enable debug log to check what content emqx has sent to the web server?
> 
> Could you also share the config file `etc/plugins/emqx_web_hooks.conf`?

1. Here is the log without code 400
[emqx.log (2).1.zip](https://github.com/emqx/emqx/files/7159228/emqx.log.2.1.zip)


2. you can get the content I posted by this rule blew; or have a look a the `curl` command 

```
SELECT * FROM "$events/client_connected","$events/client_disconnected" WHERE 1

```
3. the plugin `emqx_web_hook` is never ever started

**Comment by qzhuyan** [comment]
@GordonHuangYong 
From the log I can see the web hook is enabled and exhook(grpc) is enabled as well, is it intended?

anyway, both WebHooks and exhook runs timeout with some retries.

Also connection can be established but get closed due to idle time. 

Looks like the issue is on the http server side that hooks are calling.

**Comment by qzhuyan** [comment]
I close the ticket since there aren’t much we can do at emqx side. 
Feel free to reopen it if it is needed.

**Comment by shishirong** [comment]
@GordonHuangYong 请问找到根本原因了吗？我也遇到了这个问题，试过4.4.x, 4.3.x, 4.2.14版本都是报错。
```
2022-06-17T07:44:30.995253+00:00 [warning] mqttx_7e044c93@172.17.0.1:48652 HTTP request failed with path: <<"/testHook">> status code: 400
```
