### ISSUE TITLE
emqx 4.3.8 start failed on mac os 11.4

### ISSUE THREAD

**Issue by GordonHuangYong** [emqx/emqx#5723]
![image](https://user-images.githubusercontent.com/20039800/133056688-ee9634fb-88d2-49b2-bb7c-c3d231dd3cb9.png)
![image](https://user-images.githubusercontent.com/20039800/133056705-6795a6f6-b473-4d89-8f49-d1f8238653a4.png)

**Environment**: 

- EMQ X version (e.g. `emqx_ctl status`): v4.3.8
- Hardware configuration (e.g. `lscpu`):
![image](https://user-images.githubusercontent.com/20039800/133057169-9506b35c-9373-4dbc-bf43-9d2c440d5b4d.png)

- Kernel (e.g. `uname -a`):
 Darwin HuangYongs-Mac-mini.local 20.5.0 Darwin Kernel Version 20.5.0: Sat May  8 05:10:33 PDT 2021; root:xnu-7195.121.3~9/RELEASE_X86_64 x86_64

**Comment by qzhuyan** [comment]
after you press “打开”, is it working? or you are complaining about the security warnings?

**Comment by GordonHuangYong** [comment]
not working ! just popping again and again
![image](https://user-images.githubusercontent.com/20039800/133057984-cdd83dd8-be8e-42b5-b8fa-012421104102.png)
![image](https://user-images.githubusercontent.com/20039800/133058024-6f0e2d95-f4bc-4ca3-92c6-54bec23f1b46.png)
![image](https://user-images.githubusercontent.com/20039800/133058051-6049f77b-4d4a-4e2c-bd98-75ab98a3ba7f.png)
![image](https://user-images.githubusercontent.com/20039800/133058081-19bf2e29-1bb0-4611-932e-327346691488.png)

**Comment by GordonHuangYong** [comment]
after "打开" and run 'emqx start', again an gain, 
it finally start successfully

**Comment by qzhuyan** [comment]
thanks for reporting, looks like there are many confirmations are needed for different parts of emqx executable.
