### ISSUE TITLE
web hook url with port failed

### ISSUE THREAD

**Issue by GordonHuangYong** [emqx/emqx#5724]
if setting url with port ; showing error blew
```
Bad Arguments: {error,{init_resource,[{{emqx_web_hook_actions,on_resource_create},{error,{error,check_http_connectivity_failed},[{emqx_web_hook_actions,on_resource_create,2,[{file,"emqx_web_hook_actions.erl"},{line,204}]},{emqx_rule_engine,'-init_resource/4-fun-0-',4,[{file,"emqx_rule_engine.erl"},{line,526}]},{emqx_rule_engine,init_resource,4,[{file,"emqx_rule_engine.erl"},{line,526}]},{erpc,execute_call,4,[{file,"erpc.erl"},{line,416}]}]}}]}}
```
![image](https://user-images.githubusercontent.com/20039800/133061486-6da9a2c3-2cdb-42e1-aee9-2400994553a5.png)

**Environment**:

- EMQ X version (e.g. `emqx_ctl status`): v4.3.8
- Hardware configuration (e.g. `lscpu`):
- OS (e.g. `cat /etc/os-release`):
![image](https://user-images.githubusercontent.com/20039800/133061441-ff38f9a5-3dad-4997-bc81-d8f16434a8c5.png)

- Kernel (e.g. `uname -a`):
Darwin HuangYongs-Mac-mini.local 20.5.0 Darwin Kernel Version 20.5.0: Sat May  8 05:10:33 PDT 2021; root:xnu-7195.121.3~9/RELEASE_X86_64 x86_64
- Erlang/OTP version (in case you build emqx from source code): 
- Others:

**What happened and what you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Comment by k32** [comment]
Hello,
This error means EMQ X cannot access the URL. Can you check whether or not the URL is correct, firewall allows EMQX process to make outgoing connection to the specified address and port, and whether or not you can access this URL from a different process, such as your browser or curl.

**Comment by GordonHuangYong** [comment]
The domain is fake;
I modify the file /etc/hosts, and add the content blew
```
 127.0.0.1 w21.waytronic.tech
```
I make it working on computer only.

**Comment by k32** [comment]
When a new webhook is created, EMQ X first checks that it can access the URL, and shows the error if it can't reach it. The check is done by sending a GET request to the specified url. So you need to run a web server on the specified port.
