### ISSUE TITLE
Cannot build with Elixir plugins

### ISSUE THREAD

**Issue by sashaafm** [emqx/emqx#5729]
Hello,

 I’m trying to add Elixir plugins to `v4.3.8` and I’m having this error when running `make`:
 ```
===> Unable to run pre hooks for 'compile', command 'find_elixir_libs' in namespace 'mix' not found.
make: *** [Makefile:77: emqx] Error 1
```

I'm following the [docs](https://docs.emqx.io/en/broker/v4.3/advanced/plugins.html#plugin-development) and my Dockerfile looks like this:
```
ARG BUILD_FROM=elixir:1.9
ARG RUN_FROM=elixir:1.9-slim
ARG GITHUB_TOKEN
FROM ${BUILD_FROM} AS builder

RUN mix local.hex --force && mix local.rebar --force

RUN apt update \
    && apt install -y -f git \
                         curl \
                         gcc \
                         g+++ \
                         make \
                         perl \
                         libncurses5-dev \
                         libncursesw5-dev \
                         openssl \
                         build-essential

RUN git clone --depth 1 --branch v4.3.8 https://github.com/emqx/emqx.git

COPY plugins /emqx/lib-extra/plugins
COPY loaded_plugins.tmpl /emqx/data/loaded_plugins.tmpl

WORKDIR emqx

ENV EMQX_EXTRA_PLUGINS=emqx_cluster_stats,emqx_kafka_bridge,emqx_presence_acl

RUN make
```

not sure what the problem is as I couldn't find much stuff about this `find_elixir_libs` Mix command. 

If someone could help I’d be grateful

**Comment by k32** [comment]
Hello,

Currently support of building EMQ X with mix is work in progress, and not yet ready for general use. Instead, please refer to the following instruction: https://github.com/emqx/emqx-elixir-plugin

**Comment by sashaafm** [comment]
Hello @k32, this is exactly what I'm doing. I've got two plugins based on that repo and I'm following the instructions of using the Elixir plugins group to fetch them.

**Comment by k32** [comment]
The instruction doesn't involve running `mix` command, though.

**Comment by sashaafm** [comment]
@k32 the mix command comes from `rebar.config.erl` as can be seen here: https://github.com/emqx/emqx/blob/c3229572570a3431dbb0e8f9c0e78e2f52d9e426/rebar.config.erl#L71

I'm at straws at what's happening here. Could this be related to the `rebar3` version being used? My Docker image has `rebar 3.16.1 on Erlang/OTP 22 Erts 10.7.2.13`

**Comment by k32** [comment]
EMQ X uses a patched rebar3 from a fork. The makefile should download it to the build directory, if not present. Could you check if `rebar3` file is present in the build directory prior to invocation of `make`?

**Comment by sashaafm** [comment]
@k32 looks like it exists:
```
root@0e14fa1e24b4:/emqx# find . -name "rebar3"
./_build/default/lib/ssl_verify_fun/rebar3
./_build/default/lib/poolboy/rebar3
./_build/default/lib/prometheus_process_collector/rebar3
./_build/default/lib/emqtt/rebar3
./_build/default/lib/gen_rpc/rebar3
./_build/default/lib/cuttlefish/rebar3
./_build/default/plugins/rebar3_elvis_plugin/rebar3
./rebar3
```

**Comment by sashaafm** [comment]
I've manually altered the forked `rebar3` version in the `Makefile`:
```
root@0e14fa1e24b4:/emqx# ./rebar3 --version
===> Plugin er_coap_client does not export init/1. It will not be used.
rebar 3.16.1-emqx-1 on Erlang/OTP 22 Erts 10.7.2.13
```

However, when running `make` now I get this error:
```
===> Dependency failure: source for emqx_presence_acl does not contain a recognizable project and can not be built
make: *** [Makefile:77: emqx] Error 1
```

does this provide any clue?

**Comment by k32** [comment]
> does this provide any clue?

This error is thrown by rebar3 when it doesn't recognize the directory structure of the application. Is `emqx_presence_acl` an Elixir application?

**Comment by k32** [comment]
Could you show the diff between your `rebar.config` and the `v4.3.8` branch?

**Comment by zmstone** [comment]
likely `rebar_mix` plugin has changed

**Comment by zmstone** [comment]
@sashaafm please apply below diff to give it a try.
I'll send a pr to fix it in `main-4.3` branch
```
diff --git a/rebar.config.erl b/rebar.config.erl
index 974e13bf..901027d2 100644
--- a/rebar.config.erl
+++ b/rebar.config.erl
@@ -93,7 +93,7 @@ plugins(HasElixir) ->
       %% emqx main project does not require port-compiler
       %% pin at root level for deterministic
     , {pc, {git, "https://github.com/emqx/port_compiler.git", {tag, "v1.11.1"}}}
-    | [ rebar_mix || HasElixir ]
+    | [ {rebar_mix, "v0.4.0"} || HasElixir ]
     ]
     %% test plugins are concatenated to default profile plugins
     %% otherwise rebar3 test profile runs are super slow
```

**Comment by sashaafm** [comment]
@zmstone I did the change you suggested and now it seems to go further into `make` and gives the following error:
```
===> Application needed for release not found: poison
make: *** [Makefile:77: emqx] Error 1
```

`poison` is one of the dependencies of one of the Elixir plugins. Do I need to declare plugin dependencies somewhere?

**Comment by sashaafm** [comment]
@k32 the diff shows no differences:
```
diff --git a/Users/sashaafm/Desktop/v4.3.8_rebar_config b/Users/sashaafm/Desktop/container_rebar_config
index 6a51762..a2c58a0 100644
--- a/Users/sashaafm/Desktop/v4.3.8_rebar_config
+++ b/Users/sashaafm/Desktop/container_rebar_config
@@ -68,4 +68,4 @@
   {emqx_schema_registry,add_schema,1},
   emqx_exhook_pb, % generated code for protobuf
   emqx_exproto_pb % generated code for protobuf
-]}.
\ No newline at end of file
+]}.
```

and yes `presence_emqx_acl` is an Elixir library which follows `emqx_elixir_plugin` structure.

**Comment by zmstone** [comment]
I'm not sure why, but dependency the elixir plugin is not resolved recursively.

@sashaafm you can try to add poison to rebar.config

however there might be some issue with Elixir protocol consolidation
I tried to compile with below diff, it worked, but not sure if you'll need elixir protocol consolidation or not.

```
diff --git a/rebar.config b/rebar.config
index a2c58a05..7aa5544f 100644
--- a/rebar.config
+++ b/rebar.config
@@ -55,6 +55,7 @@
     , {recon, {git, "https://github.com/ferd/recon", {tag, "2.5.1"}}}
     , {observer_cli, "1.6.1"} % NOTE: depends on recon 2.5.1
     , {getopt, "1.0.1"}
+    , {poison, "5.0.0"}
     , {snabbkaffe, {git, "https://github.com/kafka4beam/snabbkaffe.git", {tag, "0.13.0"}}}
     ]}.

diff --git a/rebar.config.erl b/rebar.config.erl
index 901027d2..2e91c660 100644
--- a/rebar.config.erl
+++ b/rebar.config.erl
@@ -63,9 +63,6 @@ config(HasElixir) ->
     , {profiles, profiles()}
     , {project_app_dirs, project_app_dirs()}
     , {plugins, plugins(HasElixir)}
-    | [ {provider_hooks, [ {pre,  [{compile, {mix, find_elixir_libs}}]}
-                         , {post, [{compile, {mix, consolidate_protocols}}]}
-                         ]} || HasElixir ]
     ].

 is_cover_enabled() ->
@@ -93,7 +90,7 @@ plugins(HasElixir) ->
       %% emqx main project does not require port-compiler
       %% pin at root level for deterministic
     , {pc, {git, "https://github.com/emqx/port_compiler.git", {tag, "v1.11.1"}}}
-    | [ {rebar_mix, "v0.4.0"} || HasElixir ]
+    | [ {rebar_mix, "0.5.0"} || HasElixir ]
     ]
     %% test plugins are concatenated to default profile plugins
     %% otherwise rebar3 test profile runs are super slow
```

**Comment by zmstone** [comment]
I will not pin rebar_mix "0.5.0" in my PR before we (or someone can help) to figure out how to make protocol consolidation work.
