### ISSUE TITLE
(feat) Env From file in Helm Chart

### ISSUE THREAD

**Issue by lupaulus** [emqx/emqx#5779]
**What would you like to be added/modified**:

- Adding environment variables as secrets from helm values file.  

**Why is this needed**:

To add a user, that has credentials stored inside Kubernetes Secrets for security.

Linked to my PR : [Here](https://github.com/emqx/emqx/pull/5778)

**Comment by qzhuyan** [comment]
@lupaulus thanks for the nice PR, since the PR is merged, I closed the ticket.
