### ISSUE TITLE
HELM chart 4.4.0 not compatible with EMQx 4.3.8

### ISSUE THREAD

**Issue by isehuetdk** [emqx/emqx#5786]
### Subject of the issue
Installing HELM chart 4.4.0 with application version 4.3.8 using the persistent mode. 
The deployment fails eventually, pods in running but not ready state. 
NAME                       READY   STATUS    RESTARTS   AGE
pod/emqx-test-0   0/1     Running   0          7m30s
pod/emqx-test-1   0/1     Pending   0          7m30s
pod/emqx-test-2   0/1     Pending   0          7m30s

```
Readiness probe failed: Get "http://10.11.12.199:18083/api/v5/status": dial tcp 10.11.12.199:18083: connect: connection refused
Readiness probe failed: HTTP probe failed with statuscode: 404
```

In the logs I can see the following:
```
Start http:management listener on 8081 successfully.
Start http:dashboard listener on 18083 successfully.
2021-09-22T12:01:04.912723+00:00 [warning] [Ctl] CMD acl is overidden by {emqx_acl_mnesia_cli,cli}
2021-09-22T12:01:05.056233+00:00 [alert] [Modules] Failed to read: "data/loaded_modules", error: enoent
Start mqtt:tcp:internal listener on 127.0.0.1:11883 successfully.
Start mqtt:tcp:external listener on 0.0.0.0:1883 successfully.
Start mqtt:ws:external listener on 0.0.0.0:8083 successfully.
Start mqtt:ssl:external listener on 0.0.0.0:8883 successfully.
Start mqtt:wss:external listener on 0.0.0.0:8084 successfully.
EMQ X Broker 4.3.8 is running now!
```

### Your environment

- EMQ X version (e.g. `emqx_ctl status`): 4.3.8
- Hardware configuration (e.g. `lscpu`): 
- OS (e.g. `cat /etc/os-release`): Ubuntu 20.04.2 LTS
- Kernel (e.g. `uname -a`): 5.4.0-77-generic
- Erlang/OTP version (in case you build emqx from source code): 
- Others: HELM chart version 4.4.0

### Steps to reproduce
Pull helm chart from GitHub https://github.com/emqx/emqx/tree/master/deploy/charts/emqx and deploy using Helm 3.0

### Expected behaviour
When using the helm chart available on `https://repos.emqx.io/charts` and install it as per below, it installs Chart version 4.3.8 and works smoothly
```
helm repo add emqx https://repos.emqx.io/charts
helm install my-emqx emqx/emqx
```

### Actual behaviour
See above in description.

Furthermore, the chart 4.4.0 is missing Ingress details on HTTP API ingress for the ingressClassName.

```
spec:
{{- if and .Values.ingress.mgmt.ingressClassName (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion) }}
  ingressClassName: {{ .Values.ingress.mgmt.ingressClassName }}
{{- end }}
  rules:
  {{- range $host := .Values.ingress.mgmt.hosts }}
  - host: {{ $host }}
    http:
      paths:
      - path: /
        {{- if (semverCompare ">=1.18-0" $.Capabilities.KubeVersion.GitVersion) }}
        pathType: ImplementationSpecific
        {{- end }}
        backend:
          {{- if semverCompare ">=1.19-0" $.Capabilities.KubeVersion.GitVersion }}
          service:
            name: {{ include "emqx.fullname" $ }}
            port:
              number: {{ $.Values.service.mgmt }}
          {{- else }}
          serviceName: {{ include "emqx.fullname" $ }}
          servicePort: {{ $.Values.service.mgmt }}
          {{- end }}
  {{- end -}}
  {{- if .Values.ingress.mgmt.tls }}
  tls:
    {{- toYaml .Values.ingress.mgmt.tls | nindent 4 }}
  {{- end }}
---
{{- end }}
```

**Comment by JSchulte01** [comment]
A work around for this is to replace the readiness probe in the `StatefulSet.yaml` with:

```
readinessProbe:
    httpGet:
        path: /status
        port: 8081
```

Which is the old Readiness probe

**Comment by isehuetdk** [comment]
Hi @JSchulte01 
Thanks for your input. That fixed the issue. Which release will that be fixed? Just to update the HELM chart at the respective time.

**Comment by qzhuyan** [comment]
@isehuetdk 

The link you refer to is on `master` branch, that is for emqx 5.0 , for fetching the helm chart for emqx 4.3.8 pls use `main-v4.3` branch.

Is there anything you want us to backport to 4.3?

**Comment by isehuetdk** [comment]
Hi @qzhuyan ,
Not entirely. When pulling the standard HELM chart I get version 4.3.8.
The branch you are referring to is version 4.3.0 - so older. Somewhere I can find the helm definition of release 4.3.8?

**Comment by qzhuyan** [comment]
That is because 5.0 is not published yet.

I close the ticket then.
