### ISSUE TITLE
wx error 2021-09-24T16:51:25.984000+08:00 [error]  [MQTT/WS]  Parse failed for function_clause

### ISSUE THREAD

**Issue by laolaolulu** [emqx/emqx#5800]
#### Environment

- OS: 
- Erlang/OTP: 
- EMQ: 
2021-09-24T16:51:25.984000+08:00 [error]  [MQTT/WS] 
Parse failed for function_clause
[{emqx_frame,parse_utf8_string,[<<81,84,84,4,0,0,60,0,9,119,120,99,108,105,101>>],[{file,"emqx_frame.erl"},{line,438}]},{emqx_frame,parse_packet,3,[{file,"emqx_frame.erl"},{line,199}]},{emqx_frame,parse_frame,4,[{file,"emqx_frame.erl"},{line,163}]},{emqx_ws_connection,parse_incoming,2,[{file,"emqx_ws_connection.erl"},{line,533}]},{emqx_ws_connection,websocket_handle,2,[{file,"emqx_ws_connection.erl"},{line,329}]},{cowboy_websocket,handler_call,6,[{file,"cowboy_websocket.erl"},{line,487}]},{proc_lib,wake_up,3,[{file,"proc_lib.erl"},{line,236}]}]
Frame data: <<"wxclient1">>

#### Description

  var mqttc = mqtt.connect('wx://test.com/mqtt', {
        // clientId: `wxclient${user.phone}`,
        clientId: `wxclient1`,
        port: 8083,
        protocolVersion: 4, //MQTT连接协议版本
        clean: false,
        reconnectPeriod: 1000, //1000毫秒，两次重新连接之间的间隔
        connectTimeout: 30 * 1000, //1000毫秒，两次重新连接之间的间隔
        resubscribe: true
      });

*A description of the issue*

**Comment by k32** [comment]
Hello,
Could you please provide the following details:
1. Version of the EMQ X broker that you're using
2. What action from the client triggers the error?
3. Full emqx.log file that contains the error

**Comment by laolaolulu** [comment]
微信小程序连接出错,上面就是完整日志;用的windows开源版

**Comment by JimMoen** [comment]
The **first part** of variable header (protocol name) in CONNECT Packet should be like this
`0x00, 0x04, 0x4D, 0x51, 0x54, 0x54`.
See here:[Connect packet Variable Header](http://docs.oasis-open.org/mqtt/mqtt/v3.1.1/os/mqtt-v3.1.1-os.html#_Toc398718030)
