### ISSUE TITLE
Increase concurrent connection to 100K in mqtt:ssl protocol

### ISSUE THREAD

**Issue by ambaradhikari** [emqx/emqx#5809]
Hi,

I am trying to connect 100K connection which will be active at the same time.. but when i try to simulate i am not able to create connection more than 1000... can you please let us know what changes have to be done so that around 100k connection is active at the same time mqtt:ssl protoc0l..

below is the changes i did in the etc/emqx.conf file ,
listener.ssl.external.max_conn_rate = 102390
but this change did not help..

///////////////////
##
## Value: Number
listener.ssl.external.max_connections = 102400

##
## Value: Number
listener.ssl.external.max_conn_rate = 102390
/////////////////////

please let me know how to go about this issue..

**Comment by k32** [comment]
Hello,

We have a page that describes all the configuration changes needed to support large amount of connections: https://docs.emqx.io/en/broker/v4.3/tutorial/tune.html
I hope this helps.

**Comment by ambaradhikari** [comment]
yes that helped..

I followed those steps and connection was better.. but after 17K or 18K the "http://<serverIP>:18083/#/listeners" page does not refresh and shows error.. and my client creation code also hangs or stop.. 
i am running the broker in AWS EC2 instance with 32GB RAM , 8vCPUS with 256 GB hard disk with ubuntu 20.04 OS..

How do i proceed from there..

**Comment by k32** [comment]
You can try to employ HAProxy to terminate TLS: https://www.emqx.com/en/blog/mqtt-broker-clustering-part-2-sticky-session-load-balancing
It's going to reduce CPU load.

**Comment by ambaradhikari** [comment]
the problem was i was running all the clients from one public IP address.. so once i distributed 100k client creation across several servers it was able to connect and was able to reach 100K concurrent connection..

thanks for the help..
