### ISSUE TITLE
Wechat program works in debug mode, but it does not work in production env (real device)

### ISSUE THREAD

**Issue by laolaolulu** [emqx/emqx#5828]
2021-09-28T13:46:43.949000+08:00 [error] Ranch listener 'mqtt:wss:8084', connection process <0.2501.0>, stream 1 had its request process <0.2502.0> exit with reason function_clause and stacktrace []

2021-09-28T13:47:14.828000+08:00 [error]   crasher:
    initial call: cowboy_stream_h:request_process/3
    pid: <0.2519.0>
    registered_name: []
    exception error: function_clause
    ancestors: [<0.2518.0>,<0.428.0>,<0.427.0>,ranch_sup,<0.169.0>]
    message_queue_len: 0
    messages: []
    links: [<0.2518.0>]
    dictionary: []
    trap_exit: false
    status: running
    heap_size: 2586
    stack_size: 28
    reductions: 4815
  neighbours:

**Comment by qzhuyan** [comment]
Just curious, since we updated the issue template recently. do you have a problem with the issue template? 
[click "New issue"]  and then [Support Needed -> get started]

We could not help out without necessary informations.

**Comment by laolaolulu** [comment]
请问微信小程序正式环境是否不能使用非443端口?
