### ISSUE TITLE
Not able to establish SSL MQTT Bridge

### ISSUE THREAD

**Issue by tomaszwolek** [emqx/emqx#5841]
I configured MQTT Bridge (using emqx_bridge_mqtt.conf) to existing external broker which use TLS encryption (v1.2) and standard MQTT authentication (username,password,clientID). I generated Client Cert and added internal CA cert.
I also changed bridge.mqtt.*.verify = false
The bridge fails to start and generates errors in log as attached below.

### Your environment

Otherwise please provide below info:
- EMQ X version: 4.3.8
- If cluster: standalone
- Hardware configuration (e.g. `lscpu`): VM, 4vCPU, 16GB RAM
- OS (e.g. `cat /etc/os-release`): Windows 2016 but testes also in CentOS 8
- Kernel :
- Erlang/OTP version (in case you build emqx from source code): emqx installed from binary zip package
- Others: 

### LOG File
[emqx-log.txt](https://github.com/emqx/emqx/files/7250336/emqx-log.txt)

**Comment by qzhuyan** [comment]
@tomaszwolek could you attach the `emqx_bridge_mqtt.conf` file?

From log file we can see two issues:

1. permission issue of emqx data dir
1. the bridge was configured to forward to a http port instead of mqtt port?

**Comment by tomaszwolek** [comment]
@qzhuyan bridge conf attached.
[emqx_bridge.zip](https://github.com/emqx/emqx/files/7276598/emqx_bridge.zip)
1. It's a bit odd as i tested this on both Win and Linux and got the same error
2. the bridge is configured to connect to external MQTT broker running as a cluster behind load balancer. we already establish MQTT bridge from a different solution that way and it works. I've seen a chunk of HTTP message in the error log and indeed it is suspicious.

**Comment by tomaszwolek** [comment]
@zmstone the log in the original post was copied from /emqx/log directory 
i've noticed that the mentioned log messages appear after emqx_ctl bridges start sbx (which is the name of the bridge)
i was configuring this bridge through the conf file and not from the rule-engine console. which BTW i also tried and didn't work and gave some other hard to understand errors

**Comment by zmstone** [comment]
Hi @tomaszwolek 
As @qzhuyan pointed out, the other errors seem to be caused by the bridge MQTT client failed to parse an HTTP response.
`mq-broker-diiot-sbx.apps.nonprd.caas.local:443` is likely an HTTP listener.

For the first error from rule-engine, it seems to be an `eio` (IO error) when trying to create a sub directory in data dir.
to investigate further, could you share the outputs of `bin/node_dump` script ?

**Comment by zmstone** [comment]
@tomaszwolek Sorry, I forgot that's a bash script which is probably not possible to run on Windows.
Where do you have your emqx installed ? is there any special characters in the path ? like white space, etc.
If not, could you share the config file? emqx.conf (remember to obfuscate it if you have passwords in it)

**Comment by tomaszwolek** [comment]
@zmstone I'm running it from command line with elevated permissions. files are in C:\Temp\emqx so there are no special characters in the path. Config file attached, but i didn't modify it from the defaults
[emqx.conf.zip](https://github.com/emqx/emqx/files/7295473/emqx.conf.zip)
