### ISSUE TITLE
Dashboard 404 on docker image 5.0-beta.1

### ISSUE THREAD

**Issue by mattholy** [emqx/emqx#5870]
### Subject of the issue
Dashboard 404 on docker image 5.0-beta.1

### Your environment

For EMQ X 4.3 or newer, please provide the log archive generated by [node_dump tool](https://github.com/emqx/emqx/blob/master/bin/node_dump) 

- EMQ X version (e.g. `emqx_ctl status`): 5.0-beta.1

### Steps to reproduce
`docker run -d --name emqx -p 18083:18083 -p 1883:1883 emqx/emqx:latest`
then visit dashboard

### Expected behaviour
A website should appear?

### Actual behaviour
receive code 404

**Comment by mattholy** [comment]
the only thing i found in `cat emqx.log.1` is
`2021-10-02T08:19:26.646426+00:00 [warning] Description: "Authenticity is not established by certificate path validation", Reason: "Option {verify, verify_peer} and cacertfile/cacerts is missing"`

**Comment by zmstone** [comment]
hi
Beta.1 is not fully stable yet (mostly the API and dashboard), which is why we have dashboard disabled for now.

**Comment by zmstone** [comment]
Please find more details in this discussion:
https://github.com/emqx/emqx/discussions/5864
