### ISSUE TITLE
latest version of emqx do not have "sudo emqx_ctl users" command

### ISSUE THREAD

**Issue by ambaradhikari** [emqx/emqx#5873]
Hi,
we have installed 4.3.5 version of emqx and the following command was not available "sudo emqx_ctl users" . since this command is not available, we can not set username and password ("sudo emqx_ctl users add <username> <password>) for additional authentication..

But when we have installed emqx earlier (with version 4.1.4), the command ("sudo emqx_ctl users") was available and was able to set username and password.

can you please guide us and let us know how can we get the options available in the latest or at-least in 4.3.5 version of emqx..

Regards
Ambar

**Comment by k32** [comment]
Please note that some CLI commands are added by the plugins. You need to load `emqx_auth_mnesia` plugin in order for `emqx_ctl user add/list/...` commands to appear.

**Comment by ambaradhikari** [comment]
thanks.. that helped.. used dashboard UI at 18083 port number to enable plugging..

**Comment by k32** [comment]
Great!
