### ISSUE TITLE
DASHBOARD PROBLEM blank white page / no login page when using HTTPS

### ISSUE THREAD

**Issue by joko2020** [emqx/emqx#5880]
### Subject of the support
Emqx dashboard working find if accessing via HTTP on port 18083 but if i use HTTPS the login page displayed white blank screen. **I tried with chrome, firefox & opera with the same issue** .
### Step to produce for letsencrypt certificates 
After certificates was successfully created i also implement solved problem from  [See web site](https://community.letsencrypt.org/t/apache-emqx-emqx-problem/137093/10)
`chmod 0755 /etc/letsencrypt/{live,archive} chgrp emqx /etc/letsencrypt/live/mydomain/privkey.pem chgrp emqx /etc/letsencrypt/archive/mydomain/privkey1.pem chmod 0640 /etc/letsencrypt/live/mydomain/privkey.pem chmod 0640 /etc/letsencrypt/archive/mydomaint/privkey1.pem`

Error/Warning printout if any. 

using inspect element of browser found

Failed to load resource: net::ERR_CONNECTION_RESET........`https://mydomain:18084/static/css/font-awesome.min.css`
Failed to load resource: net::ERR_CONNECTION_RESET........`https://mydomain:18084/static/css/iconfont.css`
Failed to load net::ERR_CONNECTION_CLOSED :`https://mydomain:18084/static/css/app.1495f134b9420661c25a03fc6be1c155.css`
Failed to load resource: net::ERR_CONNECTION_RESET........`https://mydomain:18084/static/js/env.js`
Failed to load resource: net::ERR_CONNECTION_RESET`https://mydomain:18084/static/js/manifest.f72a5c400fac2e53484f.js`
Failed to load resource: net::ERR_CONNECTION_RESET `https://mydomain:18084/static/js/vendor.7837b8f015b7d486b74f.js`
Failed to load resource: net::ERR_CONNECTION_RESET `https://mydomain:18084/static/js/app.89a3e38c9ff09e717e6c.js`
### Your environment

For EMQ X 4.3 or newer, please provide the log archive generated by [node_dump tool](https://github.com/emqx/emqx/blob/master/bin/node_dump) 
## node_dump doesn't work in my environment 

Otherwise please provide below info:
- EMQ X version ( `Node 'emqx@127.0.0.1' 4.3.6 is started`):
- If cluster (e.g. 3 X 4Core16GB):
- Hardware configuration (
`Architecture:        x86_64
 CPU op-mode(s):      32-bit, 64-bit
 Byte Order:          Little Endian
 Address sizes:       46 bits physical, 48 bits virtual
 CPU(s):              1
 On-line CPU(s) list: 0
 Thread(s) per core:  1
 Core(s) per socket:  1
 Socket(s):           1
 Vendor ID:           GenuineIntel
 CPU family:          6
 Model:               85
 Model name:          Intel(R) Xeon(R) Silver 4214 CPU @ 2.20GHz
 Stepping:            7
 CPU MHz:             2695.349
 BogoMIPS:            4400.00
 Virtualization:      VT-x
 Hypervisor vendor:   Parallels
 Virtualization type: container
 L1d cache:           32 KiB
 L1i cache:           32 KiB
 L2 cache:            1 MiB
 L3 cache:            16.5 MiB
`
 )
 

- OS (e.g. `NAME="Ubuntu"
VERSION="20.04.3 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.3 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
`):
- Kernel ( `Linux myhostname 5.4.0 #1 SMP Tue Aug 25 11:59:26 MSK 2020 x86_64 x86_64 x86_64 GNU/Linux`):
- Erlang/OTP version (in case you build emqx from source code): 
- Others:
**emqx_dashboard.conf for HTTPS**
##--------------------------------------------------------------------
dashboard.listener.https = 18084
dashboard.listener.https.acceptors = 2
dashboard.listener.https.max_clients = 512
dashboard.listener.https.keyfile = etc/letsencrypt/live/mydomain/privkey.pem
dashboard.listener.https.certfile = etc/letsencrypt/live/mydomain/fullchain.pem
`

 `LOG File`
BLANK /EMPTY log file from /var/log/emqx/emqx.log.1

LOG from /var/log/emqx/erlang.log.1
` LOGGING STARTED Thu Oct  7 05:44:44 UTC 2021

Exec: /usr/lib/emqx/erts-11.1.8/bin/erlexec -boot /usr/lib/emqx/releases/4.3.6/start -mode embedded -boot_var ERTS_LIB_DIR /usr/lib/emqx/erts-11.1.8/../lib -mnesia dir "/var/lib/emqx/mnesia/emqx@127.0.0.1" -config /var/lib/emqx/configs/app.2021.10.07.05.44.52.config -args_file /var/lib/emqx/configs/vm.2021.10.07.05.44.52.args -vm_args /var/lib/emqx/configs/vm.2021.10.07.05.44.52.args -start_epmd false -epmd_module ekka_epmd -proto_dist ekka -- console
Root: /usr/lib/emqx
/usr/lib/emqx
Erlang/OTP 23 [erts-11.1.8] [emqx] [64-bit] [smp:1:1] [ds:1:1:8] [async-threads:4]

Starting emqx on node emqx@127.0.0.1
Start http:management listener on 8081 successfully.
Start http:dashboard listener on 18083 successfully.
Start https:dashboard listener on 18084 successfully.
Start mqtt:tcp:internal listener on 127.0.0.1:11883 successfully.
Start mqtt:tcp:external listener on 0.0.0.0:7883 successfully.
Start mqtt:ws:external listener on 0.0.0.0:8083 successfully.
Start mqtt:ssl:external listener on 0.0.0.0:8883 successfully.
Start mqtt:wss:external listener on 0.0.0.0:8084 successfully.
EMQ X Broker 4.3.6 is running now!
Eshell V11.1.8  (abort with ^G)
(emqx@127.0.0.1)1>
===== Thu Oct  7 05:56:30 UTC 2021
Stop http:management listener on 0.0.0.0:8081 successfully.
[os_mon] memory supervisor port (memsup): Erlang has closed
[os_mon] cpu supervisor port (cpu_sup): Erlang has closed

=====
===== LOGGING STARTED Thu Oct  7 05:56:49 UTC 2021
=====
Exec: /usr/lib/emqx/erts-11.1.8/bin/erlexec -boot /usr/lib/emqx/releases/4.3.6/start -mode embedded -boot_var ERTS_LIB_DIR /usr/lib/emqx/erts-11.1.8/../lib -mnesia dir "/var/lib/emqx/mnesia/emqx@127.0.0.1" -config /var/lib/emqx/configs/app.2021.10.07.05.56.57.config -args_file /var/lib/emqx/configs/vm.2021.10.07.05.56.57.args -vm_args /var/lib/emqx/configs/vm.2021.10.07.05.56.57.args -start_epmd false -epmd_module ekka_epmd -proto_dist ekka -- console
Root: /usr/lib/emqx
/usr/lib/emqx
Erlang/OTP 23 [erts-11.1.8] [emqx] [64-bit] [smp:1:1] [ds:1:1:8] [async-threads:4]

Starting emqx on node emqx@127.0.0.1
Start http:management listener on 8081 successfully.
Start http:dashboard listener on 18083 successfully.
Start https:dashboard listener on 18084 successfully.
Start mqtt:tcp:internal listener on 127.0.0.1:11883 successfully.
Start mqtt:tcp:external listener on 0.0.0.0:7883 successfully.
Start mqtt:ws:external listener on 0.0.0.0:8083 successfully.
Start mqtt:ssl:external listener on 0.0.0.0:8883 successfully.
Start mqtt:wss:external listener on 0.0.0.0:8084 successfully.
EMQ X Broker 4.3.6 is running now!
Eshell V11.1.8  (abort with ^G)
(emqx@127.0.0.1)1>
===== ALIVE Thu Oct  7 06:12:05 UTC 2021

===== ALIVE Thu Oct  7 06:27:06 UTC 2021`

**Comment by k32** [comment]
Hello,
Could you open developer console in the browser (usually it's done by pressing F12 key), switch to "Network" tab and reproduce the problem. Then take a screenshot of the content of the developer console.

**Comment by joko2020** [comment]
Ok i'll try

**Comment by k32** [comment]
@joko2020 Did emqx print anything in `/var/log/emqx/emqx.log.X` (where X is the number of the latest log file) when you refreshed the page?

**Comment by k32** [comment]
Interesting. Can you run `curl -v https://localhost:18084` on this server and post the output?

**Comment by joko2020** [comment]
> Also, `sudo netstat -tnlp`

![image](https://user-images.githubusercontent.com/76042786/136603421-072539b7-f99e-4738-821d-beb693d439ac.png)

**Comment by k32** [comment]
I see. So the connection settings are correct, but what about path to the certificate? Could you share your emqx.conf, or the relevant parts `dashboard.listener.https.*`?

**Comment by k32** [comment]
Can you locate where the files are stored in the file system (Maybe in **/**etc/letsencrypt ?) and copy the full paths to the config file?

**Comment by joko2020** [comment]
ok ### problem solved , in correct path to certificate is causing the error .
@k32 thanks a lot for treatment , for trace the error.
