### ISSUE TITLE
no actions.failure in promethues

### ISSUE THREAD

**Issue by xpunch** [emqx/emqx#5889]
### Subject of the issue
actions.failure not pushed to prometheus.

### Your environment
- EMQ X version (e.g. `emqx_ctl status`):
  4.2.6 
### Steps to reproduce
api/v4/emqx_prometheus?type=prometheus

### Expected behaviour
action and rule metrics

### Actual behaviour
no related metrics

**Comment by xpunch** [comment]
https://docs.emqx.io/en/broker/v4.3/advanced/metrics-and-stats.html#metrics-stats
actions.failure is list in your docuement, but missing in metrics.

**Comment by zmstone** [comment]
it's a doc error.
the failure count has been split to `actions.error` and `actions.exception`
