### ISSUE TITLE
There are no logs in the log directory when running through docker

### ISSUE THREAD

**Issue by tomhunts** [emqx/emqx#5903]
### Subject of the support
I start the corresponding container through docker compose,

Configuring "log.to = both or file" in the official container does not take effect. Other configuration items are OK. When it is configured as file, the corresponding log file is not found in the directory of the log file. When it is configured as both, you can see the corresponding logs through docker logs, but there is still no corresponding log file output in the directory. in any way the log file is empty.

Error/Warning printout if any. 

### Your environment

The following is my log output configuration：emqx.conf

log.to = both
log.level = debug
log.dir = log
log.file = emqx.log
log.formatter = text
log.rotation = on
log.rotation.size = 100MB
log.rotation.count = 50
log.error.file = error.log

Official docker image:  emqx / emqx: 4.3.8
Docker version; 20.10.6
docker-compose config:
emqx:
    image: emqx/emqx:4.3.8
    container_name: emqx
    environment:
      - EMQX_NAME=emqx
      - EMQX_HOST=10.100.50.140
    network_mode: "host"
    restart: always

### LOG File
running is ok an working ok,but no logfile

We look forward to receiving corresponding help. Thank you very much

**Comment by k32** [comment]
> Can you see any logs in the docker container in the log path?

Yes, the log files are located in `/opt/emqx/log/` directory in the container. 

> Does this command only support outputting the corresponding log to the console and does not support recording the corresponding log to a file.

It supports logging to both file and console.

**Comment by tomhunts** [comment]
> > Can you see any logs in the docker container in the log path?
> 
> Yes, the log files are located in `/opt/emqx/log/` directory in the container.
> 
> > Does this command only support outputting the corresponding log to the console and does not support recording the corresponding log to a file.
> 
> It supports logging to both file and console.

I tried to recompile the docker image, change the commands in it, and found that the log file appeared. Here is my dockerfile
```
FROM emqx/emqx:4.3.8
WORKDIR /opt/emqx
CMD ["/opt/emqx/bin/emqx","start"]
```
Thank you for your help. At present, it is caused by the problem of starting the command.

But now it is found that the docker container has been restarted, and there is no error in the log. I changed CMD to
```
CMD ["/opt/emqx/bin/emqx","start","&&","top"]
```
It is found that the container is still restarting. I'm trying to solve the present problem.

**Comment by tomhunts** [comment]
> Hi docker runs in `forground` mode. in `forground` mode, there is a environment variable defaults `EMQX_LOG__TO` to `console` this is why changing config file will not take effect because environment variable override sits on the top layer. https://github.com/emqx/emqx/blob/v4.3.8/bin/emqx#L615
> 
> You should be able to make `forground` mode log to file by setting `EMQX_LOG__TO` to either `both` (to log to both console and file) or `file` (to only log to file) .
> 
> Daemon mode (when start by `emqx start`), has no `EMQX_LOG__TO` override, that's why it worked for you.
Thank you for your help. It should be such a problem.

Then why does the official image start using the foreground method. I think in most cases, users will modify the output mode or path of the configuration file. Such problems will cause some trouble for new users.

Can you briefly talk about deep considerations?


> Hi docker runs in `forground` mode. in `forground` mode, there is a environment variable defaults `EMQX_LOG__TO` to `console` this is why changing config file will not take effect because environment variable override sits on the top layer. https://github.com/emqx/emqx/blob/v4.3.8/bin/emqx#L615
> 
> You should be able to make `forground` mode log to file by setting `EMQX_LOG__TO` to either `both` (to log to both console and file) or `file` (to only log to file) .
> 
> Daemon mode (when start by `emqx start`), has no `EMQX_LOG__TO` override, that's why it worked for you.

Thank you for your help. It should be such a problem.

Then why does the official image start using the foreground method. I think in most cases, users will modify the output mode or path of the configuration file. Such problems will cause some trouble for new users.

Can you briefly talk about deep considerations?
Anyway, thank you again for your answer.

**Comment by zmstone** [comment]
We would not recommend you building you own image.
add `-e EMQX_LOG__TO=file` to your docker run option should make it log to file.

Other configs you can either set more env or mount the config file.

**Comment by tomhunts** [comment]
> Sure. For docker to run in foreground mode, it’s because docker containers are supervised by docker daemon, or other orchestration tools such as k8s, there is no need to spwan off as a daemon and supervise it inside the container.
> 
> This keeps the entrypoint simple. So that as soon as the main precess exits, the container is stopped. Otherwise there would be a need for a “supervisor” of the emqx process. Or a simplified supervisor just runs a sleep loop or a `top` command.
> 
> Why by default logging to console for docker: Most of the docker deployments nowadays are running in k8s which collects container standard output logs. Many people also integrate k8s logs with log indexers. if logged to file, one would need to run another program (log forwarder) inside the container to send the file outside of the container. Running multiple programs in docker is not really a good practices

As you said, use the foreground command to run. My question is, what about other logs? Only emqx logs will be sent to the console. Will other error logs and Erlang logs be sent to the corresponding log directory? Then why don't I see the corresponding log file in the log directory. If all logs are typed in the console, there is no way to distinguish the logs, which is contrary to the original log file.
