### ISSUE TITLE
Make Prometheus endpoint configurable (path and port)

### ISSUE THREAD

**Issue by sashaafm** [emqx/emqx#5922]
**What would you like to be added/modified**:
Version: `4.3.8`
The `emqx_prometheus` app (which seems to be bundled into EMQ X itself as seen in the sources) forces the Prometheus metrics endpoint to be `/api/v4/emqx_prometheus`. There should be an easy way to configure both the endpoint's path and port (e.g., environment variables). For example:
- `EMQX_PROMETHEUS__PATH`: defines the path for metrics scraping.
- `EMQX_PROMETHEUS__PORT`: defines the port for metrics scraping.

**Why is this needed**:
The current `emqx_prometheus`  is less than ideal because:
- There's no way to configure the endpoint: Prometheus default endpoint for scraping is `/metrics`. Sometimes a user may not have the freedom to target a different endpoint (e.g., company policy, lack of permissions or fixed infrastructure).
- It sits behind EMQ X's REST API: the metrics endpoint may not belong to EMQ X's REST API as it's a different component altogether not directly related to the broker itself. Furthermore, the REST API forces the usage of Basic Auth when performing requests which I'm not even sure it's possible to do so from Prometheus side.

**Comment by zmstone** [comment]
A super late follow-up: Starting from EMQX v5, OpenAPI (Swagger) spec is employed for EMQX API.
meaning all API endpoints are static.

Given that this can be resolved with a reverse proxy as a workaround, I'm closing this issue.
