### ISSUE TITLE
Haproxy not distributing load equally 

### ISSUE THREAD

**Issue by mogupta** [emqx/emqx#5946]
### Subject of the support
Haproxy not distributing load equally . Added haproxy config at the bottom. this is mostly derived from the documentation provided on your website. not many changes from the original. 

Error/Warning printout if any. 
![image](https://user-images.githubusercontent.com/479667/137714171-a18d9b6b-4150-493c-8d0a-e6889c4219a2.png)

### Your environment

Otherwise please provide below info:
- EMQ X version (e.g. `emqx_ctl status`): 4.3.8
- If cluster (e.g. 3 X 4Core16GB):  4Core 8GB
- Hardware configuration (e.g. `lscpu`): Xeon
- OS (e.g. `cat /etc/os-release`):  Ubuntu 18
- Kernel (e.g. `uname -a`):
- Erlang/OTP version (in case you build emqx from source code): 
- Others:

### Haproxy config
```
backend emqx_cluster
    mode tcp
    balance source
    timeout server 120s
    timeout check 5000
    server emqx_node_1 "${SERVER_1}:1883" check inter 10000 fall 2 rise 5 weight 1
    server emqx_node_2 "${SERVER_2}:1883" check inter 10000 fall 2 rise 5 weight 1

frontend frontend_emqx_tcp
    bind *:1883
    mode tcp
    maxconn 50000
    timeout client 600s
    default_backend emqx_cluster

frontend frontend_emqx_ws
    bind *:1884 name http
    default_backend backend_emqx_ws

backend backend_emqx_ws
    mode http
    balance roundrobin
    server websrv1 "${SERVER_1}:8083" maxconn 10000 weight 10 cookie websrv1 check
    server websrv2 "${SERVER_2}:8083" maxconn 10000 weight 10 cookie websrv2 check

```

**Comment by coder4803** [comment]
My guess is (as @k32 wrote) that node2n has started later than the other node and then it has also restarted later.
Additionally my opinion is that round robin is not good balancing method for MQTT. It will cause a lot of unnecessary session takeovers which may be problem if there are a lot of reconnecting clients. I would recommend to use "source" or more advanced sticky sessions. Of course in some cases round robin is enough (for example if all clients connect with clean session = true).

**Comment by k32** [comment]
Is your haproxy facing the internet directly, or there is a middleman in between (e.g. AWS ELB or the like)?

**Comment by mogupta** [comment]
I am using docker swarm to host emqx and haproxy. I have changed the haproxy published port mode to `host` which disables docker routing . 
![image](https://user-images.githubusercontent.com/479667/138082007-96e03f9d-0d39-4347-8737-86ccd7098ed4.png)
