### ISSUE TITLE
ApplicationMessage.ResponseTopic is empty after mqtt5 subscribes to the response topic after using the bridge, no problem in non-bridged mode

### ISSUE THREAD

**Issue by laolaolulu** [emqx/emqx#5956]
### Subject of the support
Describe your issue here.

Error/Warning printout if any. 

### Your environment

For EMQ X 4.3 or newer, please provide the log archive generated by [node_dump tool](https://github.com/emqx/emqx/blob/master/bin/node_dump) 

Otherwise please provide below info:
- EMQ X version (e.g. `emqx_ctl status`):
- If cluster (e.g. 3 X 4Core16GB):
- Hardware configuration (e.g. `lscpu`):
- OS (e.g. `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Erlang/OTP version (in case you build emqx from source code): 
- Others:

### LOG File

Missing log file can delay the handling of the issue.

**Comment by HJianBo** [comment]
Hi @laolaolulu Plz provide more detailed & basic information to help us understand what's the problem you got

i.e: What's your MQTT client framework?

BTW, it's helpful if you can provide the tcpdump file on the bridge mode

**Comment by laolaolulu** [comment]
> Hi @laolaolulu Plz provide more detailed & basic information to help us understand what's the problem you got
> 
> i.e: What's your MQTT client framework?
> 
> BTW, it's helpful if you can provide the tcpdump file on the bridge mode

客户端使用的  [mqttnet](https://github.com/chkr1011/MQTTnet)
[emqx_bridge_mqtt.txt](https://github.com/emqx/emqx/files/7377674/emqx_bridge_mqtt.txt)

**Comment by HJianBo** [comment]
In general, the `bridge.mqtt.aws.bridge_mode` option is turned off.

The meaning of this configuration is whether emqx-bridge-mqtt uses bridge mode when creating a bridged connection. Whether it works or not depends on whether the MQTT Broker on the other side supports bridge mode, not on whether it is a 5.0 protocol.

The benefit of this configuration item is that for the MQTT Broker on the opposite end, it can distinguish which connections are bridged and which are not. However, this configuration is not a standard protocol and is only supported by some MQTT Brokers.

So, sometimes when this configuration is turned on, it may not be possible to connect.

**Comment by laolaolulu** [comment]
我的边缘服务器emqx桥接的中心服务器emqx;但经过桥接后请求响应模式无效了;我需要发布消息后判断客户端是否接收成功;但客户端在内网中,我用了一台边缘服务器做桥接
