### ISSUE TITLE
Inconsistent user management in HTTP API 

### ISSUE THREAD

**Issue by inteldon** [emqx/emqx#5962]
I'm using the latest emqx docker container. I used this link to create new users and update their passwords following the examples in: 
1.  Add authentication data
2. Check the added authentication data 
3. Change the password of the specified user name 
4.  Check the specified username information

### Steps to reproduce
From the above four steps: 

1. added a new user with "api/v4/auth_username" link 
I added new user with params: `{"username":"testu", "password":"testpass"}` 
The response was `{"code":0}` 

I repeated the process to check if it worked (same request with same username/password pair)
The response was 200 
`{"message":"existed"}`

2. Checked if user was added "api/v4/auth_username" 
The response was 200 
`{"meta":{"page":1,"limit":10,"count":1},"data":[{"username":"testu"}],"code":0}`
This proved to me that the user has been added 

### Expected behaviour
In step #3 the expected behavior is the same as the link. I should get a password change confirmation with a `{"code":0}` response 

In step #4 the expected behavior is the same as the link. I should get a `{"code":0, "data":{"username":"testu", "password":"someRandomText"}` 

### Actual behaviour
Steps 3 and 4 are where the problems happen: 

3. I tried changing the password with the link "api/v4/auth_username/${username}" 
I used the parameters: {"testu", "pestp"}
The response was 200 
`{"message":"noexisted"}` 

4. I tried checking if the username was added using "api/v4/auth_username/${username}"
I got response 200 
`{"data":{},"code":0}`

Missing log file can delay the handling of the issue. This issue can be replicated with a docker container from emqx and simple curl or python api requests to the running application.

**Comment by inteldon** [comment]
Hello! Any news? is someone going to work on this?

**Comment by inteldon** [comment]
Hello? Does anyone in your company care to fix such an important component of your system?

**Comment by tigercl** [comment]
@inteldon Hi. I'm very sorry that I've been so focused on development activities lately that I haven't been able to get back to you in time. I noticed in your description that the parameters used when trying to update the password are:

```
{"testu", "pestp"}
```

I think something is wrong here, you should use the following parameters:

```
{"password", "new password"}
```

By the way, it should help us more if you can provide a specific version of the problem found.
