### ISSUE TITLE
Session state stored for clean session

### ISSUE THREAD

**Issue by mtappler** [emqx/emqx#600]
When testing "session take over" in MQTT, I came across an issue related to the following test sequence:
1. I connect to the emqtt-broker with client identifier "Client1" and clean session set to 1
2. I subscribe to the topic "my_topic" with "Client1"
3. I open another TCP/IP-connection and send another CONNNECT-packet with client identifier "Client1". Until here, everything works as expected: the first client gets disconnected and the second connection is successful.
4. In the last step, I publish a message with the new TCP/IP-connection to "my_topic"
   Now I receive this message with the new TCP/IP-connection (as if I am subscribed) which I think is a violation of the spec. according to:

> If CleanSession is set to 1, the Client and Server MUST discard any previous Session and start a new one. This Session lasts as long as the Network Connection. State data associated with this Session MUST NOT be reused in any subsequent Session [MQTT-3.1.2-6].

Since the first connection was started as a clean connection its subscriptions must not be stored which apparently happened.

**Comment by emqplus** [comment]
Hi @mtappler, the design is right for the CleanSession flag of your new connection is 0, I think.

**Comment by mtappler** [comment]
I think that the new connection should not have an effect here. 

Consider together the portion of the spec. cited above:
> If CleanSession is set to 1, the Client and Server MUST discard any previous Session and start a new one. This Session lasts as long as the Network Connection. State data associated with this Session MUST NOT be reused in any subsequent Session [MQTT-3.1.2-6].

Hence, according to the second sentence there is no session for client identifier "Client1" after closing the connection at Step 3.

Then there is [MQTT-3.1.2-4] which says:
> If CleanSession is set to 0 ...  If there is no Session associated with the Client identifier the Server MUST create a new Session. ...

So after the reconnect before Step 4, we have a new session with client identifier "Client1". Therefore I would say that it is a different session and thus the subscription data from the first session must not be reused according to  [MQTT-3.1.2-6].

However, I know that this is an unusual case which is actually discussed in the non-normative comment at the bottom of Page 25 of the spec.:
> Typically, a Client will always connect using CleanSession set to 0 or CleanSession set to 1 and not swap between the two values...
