### ISSUE TITLE
Performance issue with emqx_retainer

### ISSUE THREAD

**Issue by coder4803** [emqx/emqx#6014]
### Subject of the issue
Wildcard subscriptions causing high performance hit when there are a lot of retained messages stored in different topics.

### Your environment
- EMQ X version 4.3.5
- OS: Ubuntu 20.04

### Steps to reproduce
1. For reference, you can check how big performance hit it causes **without** retained messages stored. Just make 1000 subscriptions to different topics (following cause roughly the same performance hit; no hit at all). 
  1.1. "test/topic/+/X", where X runs from 1 to 1000).
  1.2. "test/topic/number/X", where X runs from 1 to 1000.

2. To reproduce the issue, please add retained messages to e.g. ~100k topics (it doesn't really matter what topics are used). Then run following subscriptions (1000 subscriptions for each, X runs from 1 to 1000)
  2.1. "test/topic/+/X - **This is very slow**
  2.2. "test/topic/number/X - This is quite fast
  2.3. "other/+/topic/X" - **This is very slow too.**

So it doesn't matter if the subscription even matches with retained values/topics (the last test).

### Expected behaviour
Number of retained messages should not (significantly) affect the effort required to handle a wildcard subscription.

### Actual behaviour
Increasing number of retained messages affects significantly to the effort required to handle a wildcard subscription.

The behavior points out that the retain cache is implemented as some kind of key-value table (I do not understand Erlang but I checked the source code and it looked also like that). Would it be possible to use some kind of trie instead of a table?

Storing data in a trie on a disk might not be that simple but at least in my case memory is enough. I also think that file format could still be key-value table although memory format is changed to some kind of trie.

Please let me know if you need more information.

**Comment by coder4803** [comment]
Hello!

Any comments on this issue? Do you think this could be fixed with reasonable amount of work? Are there some architectural obstacles on this?

I re-checked the code and for me it seems that retain-plugin is relying on some _backend_ for storing the messages. I started to wonder if _backend_ is a part of the emqx _core_. Is that _backend_ a vital part when synchronizing retained messages with a new node joining into a cluster?

This issue basically prevents of using retained messages and wild card subscriptions at the same time. If one of them are not used (or the amounts are not big) there is no real performance problem.

**Comment by zmstone** [comment]
Hi @coder4803 
It’s explained here https://github.com/emqx/emqx/discussions/6130

**Comment by zmstone** [comment]
The current implementation is based on Erlang's builtin DB's pattern match, it may fallback to a full table scan for wildcards.
we'll have a look if there is a quick remedy for this.

**Comment by coder4803** [comment]
Hello!

Any new for this issue? Have you had time to check if this could be fixed with reasonable effort? And do you think the fix could be included to 4.3.x branch?

**Comment by zmstone** [comment]
Hi @coder4803 
Sorry, we could not prioritise this for now.
In case the fix can be done without changing the underlying table schema, it will be included in a 4.3.x release.

**Comment by gaxx** [comment]
Hello!

If I have understood correctly there won't be retainer-plugin performance improvements in 4.x series. Are you planning to change this in 5.0 (or is it already done there)?

I was going to test this quickly my self but realized that plugins are not shipped with release packages anymore. Seems that I have to compile the whole thing my self. Am I correct? Is there some existing tutorial for that or is plugin_template the best documentation?

**Comment by zmstone** [comment]
Hi @gaxx 
Yes, this is included in v5 (latest release v5.0.0-rc.4), you are welcome to download a package for test
packages are released as build assets https://github.com/emqx/emqx/releases/tag/v5.0.0-rc.4

Add this config (to emqx.conf) to fit your wildcard patterns.

```
retainer.backend.index_specs = {
    ##   Retainer index specifications: list of arrays of positive ascending integers. Each array specifies an index. Numbers in an index specification are 1-based word positions in topics. Words from spe
    ## @path retainer.backend.index_specs
    ## @type [[integer()]]
    ## @default
    [ [1, 2, 3], [1, 3], [2, 3], [3] ]
}
```

**Comment by gaxx** [comment]
Great to have a fix for that, thanks!

Unfortunately I didn't fully get the logic behind defining those "indexes". Is there some documentation or list of examples?

For example I am trying to figure out how to optimize subscriptions like A/B/C/+/E/F. Seems that at least adding [5] optimizes that but I am not sure if it is the optimal for it.

If I understood correctly A/B/+/D/+/F/G would require [4, 6] but when is [1, 2, 3] needed (one of the default indexes)?

**Comment by Clocen** [comment]
I have similar use case as @gaxx but with 6 deep topic structure so I am very happy to hear there are improvements made to this! However, I understood the definition other way around as @gaxx e.g.:

A/B/+/D/+/F should be configured as
[1,2,4,6]

@zmstone - could you kindly confirm which way is the correct way?

> Add this config (to emqx.conf) to fit your wildcard patterns.
> ```
> retainer.backend.index_specs = {
>     ## Retainer index specifications: list of arrays of positive ascending integers. 
>     ## Each array specifies an index.
>     ## Numbers in an index specification are 1-based word positions in topics.
>     ## Words from specified positions will be used for indexing.
>     ## For example, it is good to have `[2, 4]` index to optimize `+/X/+/Y/...`  topic wildcard subscriptions.
>     [ [1, 2, 3], [1, 3], [2, 3], [3] ]
> }
> ```

**Comment by zmstone** [comment]
> Great to have a fix for that, thanks!
> 
> Unfortunately I didn't fully get the logic behind defining those "indexes". Is there some documentation or list of examples?
> 
> For example I am trying to figure out how to optimize subscriptions like A/B/C/+/E/F. Seems that at least adding [5] optimizes that but I am not sure if it is the most optimal for it.
> 
> If I understood correctly A/B/+/D/+/F/G would require [4, 6] but when is [1, 2, 3] needed (one of the default indexes)?
> 
> So probably I misunderstood the logic completely...
Hi
In this case, `A/B/+/D/+/F/G`, the most effective index is `[1, 2, 4, 6, 7]`,
the default config is being exhaustive for 4-level wildcard topics.

**Comment by gaxx** [comment]
Thanks for confirmation your @zmstone .

I tested this more and seems that for example index definition like [1, 2, 3, 5, 6, 7, 8] works for both (and everything between)
`A/B/C/+/E`
and
`A/B/C/+/E/F/G/H`
I don't know if this works due to my (limited) test or if it works in general.

**Comment by savonarola** [comment]
Hello! @gaxx this is intended to work. I.e. having index like `[1, 2, 3, 5, 6, 7, 8]`, there is no need to have indices like `[1]`, `[1, 2]`, `[1, 2, 3]`, `[1, 2, 3, 5]`, `[1, 2, 3, 5, 6]`,  or `[1, 2, 3, 5, 6, 7]`,
