### ISSUE TITLE
Rule Action Handler not supporting variables from Rule SQL ${Var}

### ISSUE THREAD

**Issue by Kinhus** [emqx/emqx#6055]
### Subject of the issue
I am having problems with Rule Action Handler. I would like to use a variable I get from Rule, but it's not letting me create the rule if the path is a variable or a combination of a string and a variable. 
I tried with Path name ${msg} and /edit${msg}.
See the picture below. 

### Your environment
EMQ X Broker 4.3.8

### Steps to reproduce
Use a variable ${Var} in the Path field of Action Handler settings. It won't let you create the rule.

### Expected behavior
I should allow you to create the rule and use the variable from the Rule SQL for Path.

### Actual behaviour
![EMQX error](https://user-images.githubusercontent.com/80819736/140062718-555cd6c7-5cca-4fa1-8266-7bd444d33097.jpg)

An error log is: 
Bad Arguments: {init_action,[{{init_action_failure,'emqx@127.0.0.1'},{{emqx_web_hook_actions,on_action_create_data_to_webserver},{error,{case_clause,{error,{invalid_uri,"{"}}},[{emqx_web_hook_actions,merge_path,2,[{file,"emqx_web_hook_actions.erl"},{line,315}]},{emqx_web_hook_actions,parse_action_params,1,[{file,"emqx_web_hook_actions.erl"},{line,301}]},{emqx_web_hook_actions,on_action_create_data_to_webserver,2,[{file,"emqx_web_hook_actions.erl"},{line,246}]},{emqx_rule_engine,'-init_action/4-fun-0-',4,[{file,"emqx_rule_engine.erl"},{line,535}]},{emqx_rule_engine,init_action,4,[{file,"emqx_rule_engine.erl"},{line,535}]},{erpc,execute_call,4,[{file,"erpc.erl"},{line,416}]}]}}}]}

**Comment by zmstone** [comment]
placeholders in URL is now supported in v5. here is an example in 5.5

<img width="887" alt="image" src="https://github.com/emqx/emqx/assets/164324/81f4d229-3cc1-428c-916c-7df6b1b453aa">
