### ISSUE TITLE
EMQX tag 4.3.9 missing from public ECR

### ISSUE THREAD

**Issue by onedr0p** [emqx/emqx#6079]
### Subject of the issue

4.3.9 is missing from ECR

https://gallery.ecr.aws/emqx/emqx

### Your environment

For EMQ X 4.3 or newer, please provide the log archive generated by [node_dump tool](https://github.com/emqx/emqx/blob/master/bin/node_dump) 

- EMQ X version (e.g. `emqx_ctl status`): 
- Hardware configuration (e.g. `lscpu`):
- OS (e.g. `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Erlang/OTP version (in case you build emqx from source code): 
- Others:

### Steps to reproduce
Tell us how to reproduce this issue. 

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

Missing log file can delay the handling of the issue.

**Comment by qzhuyan** [comment]
@Rory-Z I am unsure if this is pushed by us? https://gallery.ecr.aws/emqx/emqx

**Comment by Rory-Z** [comment]
> @Rory-Z I am unsure if this is pushed by us? https://gallery.ecr.aws/emqx/emqx

Hi, @qzhuyan I'm not sure, at least it wasn't pushed by the developers

**Comment by Rory-Z** [comment]
@onedr0p We have pushed out the latest version of emqx, thanks for the heads up!

**Comment by Rory-Z** [comment]
@qzhuyan I'll add this to the GitHub action to automatically update it when release

**Comment by zmstone** [comment]
@Rory-Z please make sure it’s automated.

**Comment by onedr0p** [comment]
We seem to be missing 5.x.x tags on ECR

https://gallery.ecr.aws/emqx/emqx

**Comment by zmstone** [comment]
Hi @onedr0p 
thank you for reporting it, it will be fixed here, and the next release 5.0.3 will be pushed to ecr.
https://github.com/emqx/emqx/pull/8430

**Comment by onedr0p** [comment]
thank you very much! dockerhub is quite annoying with 100 pulls/6 hours, I wish you all would drop it entirely and use GHCR + Quay instead.
