### ISSUE TITLE
开启验证后，无法使用1883端口通过验证，但8083可以

### ISSUE THREAD

**Issue by prodcd** [emqx/emqx#6122]
使用Docker安装，最新版4.3.9与4.3.8。
尝试过开启MySQL与Mnesia 认证，插件也已开启。在关闭匿名认证后"allow_anonymous = false"无法连接1883，返回“RC=5 CONNACK return code”。但可以通过8083成功登录。

Use Docker install ，latest 4.3.9 and 4.3.8 version.
try use mysql and mnesia auth mode, and plugins has been opened.if turn "allow_anonymous = false",then 1883 port return "RC=5 CONNACK return code",but 8083 port can login.

**Comment by zmstone** [comment]
@prodcd 
could you enable debug log to see if you can find any useful information.

**Comment by prodcd** [comment]
I run docker use command `docker run -d --name emqx -p 1883:1883 -p 8081:8081 -p 8083:8083 -p 8883:8883 -p 8084:8084 -p 18083:18083 emqx/emqx`,and edit file "/opt/emqx/etc/emqx.conf",bug the "/opt/emqx/log" path is empty.

```
vi /opt/emqx/etc/emqx.conf

log.to = file
log.level = debug <-edit this
log.dir = log
log.file = emqx.log

emqx restart
<- log path is empty

docker restart emqx
<- log path is empty

emqx reboot
<- log path is empty
```

**Comment by zmstone** [comment]
```
docker run -d --name emqx -e EMQX_LOG__LEVEL=debug-p 1883:1883 -p 8081:8081 -p 8083:8083 -p 8883:8883 -p 8084:8084 -p 18083:18083 emqx/emqx:4.3.10
docker logs -f emqx
```

**Comment by prodcd** [comment]
@zmstone Thinks.From the log,I've found the problem.I use mqtt tool's bug.Its "username" refers to the wrong variable.When it logs in, it sends password/password,not username/password.
