### ISSUE TITLE
emqx docker container don't keep the .json setting after restart

### ISSUE THREAD

**Issue by wallace-hu** [emqx/emqx#6178]
I pull and run a emqx docker image and import a .json setting file from the browser UI http:\\myip:1803/通用->备份->上传并恢复., 
Then i can find the rules and resources which defined in the .json(which was exported which command emqx_ctl data export from another emqx platform) file.

But if i restart the docker, The setting disappeared and i have to redo the restore action again.  Doesn't the emqx save the setting to the docker volumes ?(Using the emqx_ctl data import xxx.json also have the problem, When the docker restarted , the setting was lost.)
 
So my problem is how to make the setting saved in the container.

**Comment by zmstone** [comment]
The data dir is a docker `VOLUME`, that’s why it’s not saved for the container by default.

Options:
1. create a docker volume and mount it to the container.
2. configure data_dir to another place then you can commit a running container with the data persisted as a part of the image 
3. Bind a host dir as volume for the container

**Comment by wallace-hu** [comment]
> The data dir is a docker `VOLUME`, that’s why it’s not saved for the container by default.
> 
> Options:
> 
> 1. create a docker volume and mount it to the container.
> 2. configure data_dir to another place then you can commit a running container with the data persisted as a part of the image
> 3. Bind a host dir as volume for the container
Thanks for the quick reply, 
Do you mean that the <_emqx_ctl data import xxxx.json_ >command doesn't import the .json settings to the default volumes?
Then which directory does it import the setting to? 

I use the default volumes emqx official docker images used as below:
root@wallace-VirtualBox:/# docker inspect --format=’{{.Mounts}}’  832a0d2cfcfd
’[{volume 90bcb07dbaa5338f6ee7f1c73af6e3ced081d57ea7025da7d4bf1c0094cd41e2 /var/lib/docker/volumes/90bcb07dbaa5338f6ee7f1c73af6e3ced081d57ea7025da7d4bf1c0094cd41e2/_data /opt/emqx/data local  true } {volume 4e20c14adadffe1b7d3b3a7121303c707f4157817f68b0e6e06a1647554e2852 /var/lib/docker/volumes/4e20c14adadffe1b7d3b3a7121303c707f4157817f68b0e6e06a1647554e2852/_data /opt/emqx/etc local  true } {volume 5f5f02281e31f591de369ded0a013e63172e939e9afe229702a0d009ecb63de2 /var/lib/docker/volumes/5f5f02281e31f591de369ded0a013e63172e939e9afe229702a0d009ecb63de2/_data /opt/emqx/log local  true }]’
root@wallace-VirtualBox:/#

**Comment by zmstone** [comment]
it imports and stores data in /opt/emqx/data/mnesia
You can add `-v host/dir:/opt/emqx/data` to docker run.

**Comment by zmstone** [comment]
And, in case you didn’t notice, it needs a static node name.
Data is actually stored in
/opt/emqx/data/mnesia/<node-name>

**Comment by wallace-hu** [comment]
Please help check my steps per the advice, something goes wrong :
1. create the directory and set the access privilage.
   mkdir  /var/lib/docker/volumes/emqx/configs
   chmod 777  /var/lib/docker/volumes
2. run the emqx docker the the volume
. docker run -d --name demo -p 1883:1883 -p 8083:8083 -p 8883:8883 -p 8084:8084  -p 18083:18083 -v /var/lib/docker/volumes/emqx:/opt/emqx/data 2445b5debc4c
7cc9f4a2d5d53d8d04a1e090e3affc961d064f377950b57998b4a29ff77c4c7b

3.  check the docker status after 10 seconds , it existed.
docker ps -a
CONTAINER ID   IMAGE          COMMAND                  CREATED          STATUS                    PORTS                                       NAMES
7cc9f4a2d5d5   2445b5debc4c   "/usr/bin/docker-ent…"   11 seconds ago   Exited (1) 1 second ago                                           demo

4. check the error log
root@wallace-VirtualBox:/var/lib/docker/volumes# docker logs 7cc9f4a2d5d5
listener.ssl.external.acceptors = "32"
listener.ssl.external.max_connections = "102400"
listener.tcp.external.acceptors = "64"
listener.tcp.external.max_connections = "1024000"
listener.ws.external.acceptors = "16"
listener.ws.external.max_connections = "102400"
listener.wss.external.acceptors = "16"
listener.wss.external.max_connections = "102400"
log.to = "console"
node.max_ets_tables = "2097152"
node.max_ports = "1048576"
node.name = "7cc9f4a2d5d5@172.17.0.2"
node.process_limit = "2097152"
rpc.port_discovery = "manual"
Starting emqx on node 7cc9f4a2d5d5@172.17.0.2
2021-11-16T09:30:04.034021+00:00 [error] crasher: initial call: application_master:init/4, pid: <0.2149.0>, registered_name: [], exit: {{eacces,{emqx_app,start,[normal,[]]}},[{application_master,init,4,[{file,"application_master.erl"},{line,138}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,226}]}]}, ancestors: [<0.2148.0>], message_queue_len: 1, messages: [{'EXIT',<0.2150.0>,normal}], links: [<0.2148.0>,<0.2009.0>], dictionary: [], trap_exit: true, status: running, heap_size: 376, stack_size: 28, reductions: 268; neighbours:
[os_mon] memory supervisor port (memsup): Erlang has closed
[os_mon] cpu supervisor port (cpu_sup): Erlang has closed
{"Kernel pid terminated",application_controller,"{application_start_failure,emqx,{eacces,{emqx_app,start,[normal,[]]}}}"}
Kernel pid terminated (application_controller) ({application_start_failure,emqx,{eacces,{emqx_app,start,[normal,[]]}}})

Crash dump is being written to: log/crash.dump...done


What is wrong happened?

**Comment by wallace-hu** [comment]
> now it's safe to delete the container (with `--rm` run option), and start it with the same args to see the old data persisted in the named volume.
Thanks for the advice, I will follow it.
