### ISSUE TITLE
Plugin activation problem because of right of folder

### ISSUE THREAD

**Issue by lpaulusLohr** [emqx/emqx#6182]
### Environment
Environment
EMQ: 4.3.10

By Helm deployement

### Repetition steps

> helm3 search repo emqx
```
NAME            CHART VERSION   APP VERSION     DESCRIPTION                             
emqx/emqx       4.3.5           4.3.5           A Helm chart for EMQ X                  
emqx/emqx-ee    4.2.6           4.2.6           A Helm chart for EMQ X Enterprise       
emqx/kuiper     0.9.0           0.9.0           A lightweight IoT edge analytic software
add env EMQX_LOADED_PLUGINS to values.yaml

emqxConfig:
  EMQX_CLUSTER__K8S__APISERVER: "https://kubernetes.default.svc:443"
  ## The address type is used to extract host from k8s service.
  ## Value: ip | dns | hostname
  ## Note：Hostname is only supported after v4.0-rc.2
  EMQX_CLUSTER__K8S__ADDRESS_TYPE: "hostname"
  EMQX_CLUSTER__K8S__SUFFIX: "svc.cluster.local"
  ## if EMQX_CLUSTER__K8S__ADDRESS_TYPE eq dns
  # EMQX_CLUSTER__K8S__SUFFIX: "pod.cluster.local"
  EMQX_LOADED_PLUGINS: "emqx_recon emqx_retainer emqx_management emqx_dashboard emqx_auth_mnesia"
```
> run helm3 install connliu -n connliu emqx/emqx -f values.yaml

> kubectl get pod -n connliu
```
NAME             READY   STATUS             RESTARTS   AGE
connliu-emqx-0   0/1     CrashLoopBackOff   1          8s
```
> kubectl logs -n connliu  connliu-emqx-0 emqx 
```
/usr/bin/docker-entrypoint.sh: line 101: /opt/emqx/data/loaded_plugins: Read-only file system
```
Normal helm install
> helm3 install  connliu -n connliu  emqx/emqx
```
NAME: connliu
LAST DEPLOYED: Fri Jul 16 11:39:49 2021
NAMESPACE: connliu
STATUS: deployed
REVISION: 1
TEST SUITE: None
```
> kubectl get pod -n connliu 
```
NAME             READY   STATUS    RESTARTS   AGE
connliu-emqx-0   1/1     Running   0          13s
```
> kubectl exec -it -n connliu connliu-emqx-0 -- ls -l /opt/emqx/data/
```
total 24
drwxrwxr-x    2 emqx     emqx          4096 Jul 16 03:39 configs
-rw-r--r--    1 root     emqx           177 Jul 16 03:39 loaded_modules
-rw-r--r--    1 root     emqx           169 Jul 16 03:39 loaded_plugins
drwxrwsrwx    3 root     emqx          4096 Jul 16 03:39 mnesia
drwxrwxr-x    2 emqx     emqx          4096 Jun 28 06:57 patches
drwxrwxr-x    2 emqx     emqx          4096 Jun 28 06:57 scripts
```
The permissions of directories loaded_modules and loaded_plugins are different from others

Custom EMQX_LOADED_PLUGINS docker install
> docker run -d --name emqx -p 18083:18083 -e EMQX_LOADED_PLUGINS="emqx_dashboard" emqx/emqx:4.3.10
```
189f7061d4e8ca2a96211baf3930ff0770e5f6deb3c264f3405287b59ac4e20d
```
> docker exec emqx ls -l /opt/emqx/data/
```
total 24
drwxrwxr-x    2 emqx     emqx          4096 Jul 16 03:34 configs
-rw-rw-r--    1 emqx     emqx            58 Jun 28 06:54 loaded_modules
-rw-rw-r--    1 emqx     emqx           192 Jul 16 03:34 loaded_plugins
drwxrwxr-x    3 emqx     emqx          4096 Jul 16 03:34 mnesia
drwxrwxr-x    2 emqx     emqx          4096 Jun 28 06:57 patches
drwxrwxr-x    2 emqx     emqx          4096 Jun 28 06:57 scripts
```

**Comment by coder4803** [comment]
I faced the same problem. This access right problem probably explains also why loaded plugins are not persisted over pod restart (like they are persisted in a traditional virtual machine setup) even if persistence is enabled.

**Comment by Rory-Z** [comment]
Hi, @lpaulusLohr In helm's value.yaml, we provide the [emqxLoadedPlugins](https://github.com/emqx/emqx/blob/v4.3.10/deploy/charts/emqx/values.yaml#L85) configuration, which allows you to set the plugins you want to enable

**Comment by Rory-Z** [comment]
Hi, @coder4803 You can refer to [this reply](https://github.com/emqx/emqx/issues/6182#issuecomment-972898620) for the plugin settings, and for the persistence issue, can you create a new issue to describe it in detail?

**Comment by lpaulusLohr** [comment]
@Rory-Z With using `emqxLoadedPlugins`, my env values `EMQX_AUTH__MNESIA__1__LOGIN` and `EMQX_AUTH__MNESIA__1__PASSWORD` are not working like in the version I have in production 4.2.13

**Comment by Rory-Z** [comment]
@lpaulusLohr The auth mnesia plugin was refactored in version 4.3, @tigercl , do we have a Changelog for that?

**Comment by zmstone** [comment]
please find the changes here:
https://docs.emqx.io/en/broker/v4.3/changes/upgrade-4.3.html#data-migration

closing this issue. feel free to create a new one if the doc does not help.
