### ISSUE TITLE
online and offline information of device in EMQ

### ISSUE THREAD

**Issue by ambaradhikari** [emqx/emqx#6194]
i want to determine whether the client is online or offline using "$sys" command referred from the below link..
https://emqx.medium.com/how-to-get-the-online-and-offline-information-of-device-in-emq-6025ab7043db

so i used "$SYS/brokers/+/clients/+/+" topic which i subscribed to .. but i did not get any message when i am connecting or disconnecting any client in that MQTT..

can you let me know how to proceed further..

below is the code snippet which used in node js , where publish and subscribe works , but "$sys" command i do not get any response in message.

//////////////
client.on('connect', function (connack) {
    console.log('MQTT connection is successful : ',hostName);
    client.publish("TestSimulation/MQTTS","hello 12345 TestSimulation MQTTS");
    client.subscribe("TestSimulation/+");
    // $SYS/brokers/+/clients/+/+
    client.subscribe("$SYS/brokers/+/clients/+/+");
});

client.on('message', async function (topic, message) {
    console.log('MQTT topic = ',topic);
    console.log('MQTT message = ',message.toString());
});
/////////////

**Comment by qzhuyan** [comment]
did you sub "$SYS/brokers/+/clients/+/+"); first from one client A
, then connect to emqx from another client B?

Client A should receive the $SYS message of client B from the broker.

**Comment by k32** [comment]
I cannot reproduce the issue on emqx 4.3.10:
```
$ emqtt_cli sub -t '$SYS/brokers/+/clients/+/+'

Client emqtt-me-emq-d36ed822a26a7a64b252 sent CONNECT
Client emqtt-me-emq-d36ed822a26a7a64b252 subscribed to $SYS/brokers/+/clients/+/+
{"username":"undefined","ts":1637152662848,"sockport":1883,"proto_ver":5,"proto_name":"MQTT","keepalive":300,"ipaddress":"127.0.0.1","expiry_interval":0,"connected_at":1637152662848,"connack":0,"clientid":"emqtt-me-emq-72ab61b15418c0a1c8ab","clean_start":true}
{"username":"undefined","ts":1637152662852,"sockport":1883,"reason":"normal","proto_ver":5,"proto_name":"MQTT","ipaddress":"127.0.0.1","disconnected_at":1637152662852,"clientid":"emqtt-me-emq-72ab61b15418c0a1c8ab"}
{"username":"undefined","ts":1637152663795,"sockport":1883,"proto_ver":5,"proto_name":"MQTT","keepalive":300,"ipaddress":"127.0.0.1","expiry_interval":0,"connected_at":1637152663795,"connack":0,"clientid":"emqtt-me-emq-d534a01933c8c7fa7002","clean_start":true}
{"username":"undefined","ts":1637152663798,"sockport":1883,"reason":"normal","proto_ver":5,"proto_name":"MQTT","ipaddress":"127.0.0.1","disconnected_at":1637152663798,"clientid":"emqtt-me-emq-d534a01933c8c7fa7002"}
{"username":"undefined","ts":1637152664606,"sockport":1883,"proto_ver":5,"proto_name":"MQTT","keepalive":300,"ipaddress":"127.0.0.1","expiry_interval":0,"connected_at":1637152664606,"connack":0,"clientid":"emqtt-me-emq-d54beb4194bfdf641a8a","clean_start":true}
{"username":"undefined","ts":1637152664609,"sockport":1883,"reason":"normal","proto_ver":5,"proto_name":"MQTT","ipaddress":"127.0.0.1","disconnected_at":1637152664609,"clientid":"emqtt-me-emq-d54beb4194bfdf641a8a"}
{"username":"undefined","ts":1637152665461,"sockport":1883,"proto_ver":5,"proto_name":"MQTT","keepalive":300,"ipaddress":"127.0.0.1","expiry_interval":0,"connected_at":1637152665461,"connack":0,"clientid":"emqtt-me-emq-4aa4ebeb7628f6614ab2","clean_start":true}
{"username":"undefined","ts":1637152665465,"sockport":1883,"reason":"normal","proto_ver":5,"proto_name":"MQTT","ipaddress":"127.0.0.1","disconnected_at":1637152665465,"clientid":"emqtt-me-emq-4aa4ebeb7628f6614ab2"}{"username":"undefined","ts":1637152662852,"sockport":1883,"reason":"normal","proto_ver":5,"proto_name":"MQTT","ipaddress":"127.0.0.1","disconnected_at":1637152662852,"clientid":"emqtt-me-emq-72ab61b15418c0a1c8ab"}
{"username":"undefined","ts":1637152663795,"sockport":1883,"proto_ver":5,"proto_name":"MQTT","keepalive":300,"ipaddress":"127.0.0.1","expiry_interval":0,"connected_at":1637152663795,"connack":0,"clientid":"emqtt-me-emq-d534a01933c8c7fa7002","clean_start":true}
{"username":"undefined","ts":1637152663798,"sockport":1883,"reason":"normal","proto_ver":5,"proto_name":"MQTT","ipaddress":"127.0.0.1","disconnected_at":1637152663798,"clientid":"emqtt-me-emq-d534a01933c8c7fa7002"}
{"username":"undefined","ts":1637152664606,"sockport":1883,"proto_ver":5,"proto_name":"MQTT","keepalive":300,"ipaddress":"127.0.0.1","expiry_interval":0,"connected_at":1637152664606,"connack":0,"clientid":"emqtt-me-emq-d54beb4194bfdf641a8a","clean_start":true}
```

**Comment by ambaradhikari** [comment]
@qzhuyan :- i tried the same steps.. did not get any message on connect or disconnect..
@qzhuyan @k32 :- do i have to enable any module or plugin from 18083 page??

**Comment by k32** [comment]
No, this works in the default configuration. Could you describe the full sequence of your actions. Do you see `MQTT connection is successful ` log message? Do you connect or disconnect another client after you see this message in the logs?

**Comment by ambaradhikari** [comment]
@k32 :- 
-->yes i see "MQTT connection is successful" log message..
this is my code snippet..
/////////////////
client.on('connect', function (connack) {
console.log('MQTT connection is successful : ',hostName);
client.publish("TestSimulation/MQTTS","hello 12345 TestSimulation MQTTS");
client.subscribe("TestSimulation/+");
// $SYS/brokers/+/clients/+/+
client.subscribe("$SYS/brokers/+/clients/+/+");
});

client.on('message', async function (topic, message) {
console.log('MQTT topic = ',topic);
console.log('MQTT message = ',message.toString());
});
/////////////////

and other publish and subscribe is working from other client and working fine an i am getting messages also.. only for "$SYS" i am not getting any response on message..

**Comment by k32** [comment]
Which version of EMQ X are you running?

**Comment by ambaradhikari** [comment]
@k32 :- 4.1.4

**Comment by k32** [comment]
This version is old and unsupported, can you try this on 4.3.10?

**Comment by ambaradhikari** [comment]
ok.. i will try..

**Comment by ambaradhikari** [comment]
@k32 :- 
updated to version 4.3.5.. facing same issue..

**Comment by ambaradhikari** [comment]
@k32 :- its working fine now with version 4.3.5..
had to do change in acl.conf file (https://docs.emqx.io/en/broker/v4.3/advanced/acl-file.html)..
by default "#SYS" was allowed only for clients who are connected to local host..

i changed the acl.conf from this(chnages in 3rd line):-
/////////////
{allow, {user, "dashboard"}, subscribe, ["$SYS/#"]}.

{allow, {ipaddr, "127.0.0.1"}, pubsub, ["$SYS/#", "#"]}.

{deny, all, subscribe, ["$SYS/#", {eq, "#"}]}.

{allow, all}.
/////////////
to
/////////////
{allow, {user, "dashboard"}, subscribe, ["$SYS/#"]}.

{allow, {ipaddr, "127.0.0.1"}, pubsub, ["$SYS/#", "#"]}.

{allow, all, pubsub, ["$SYS/#"]}.

{allow, all}.
/////////////


Thanks for the help..
