### ISSUE TITLE
Parse failed  for function_clause when I use Nginx LB and Set the "proxy_protocol on;

### ISSUE THREAD

**Issue by wangxw** [emqx/emqx#6222]
### Subject of the issue
Describe your issue here.
Parse failed  for function_clause when I use Nginx LB and Set the "proxy_protocol on;
then I start a EMQX cluseter and config LB by nginx, like this:
` server {
        listen 8883 ssl;  #
        ssl_handshake_timeout 15s;
        ssl_certificate     /etc/nginx/ssl/andon/andon.cn.pem;
        ssl_certificate_key /etc/nginx/ssl/andon/andon.cn.key;
        proxy_connect_timeout 10s;
        proxy_timeout 88s;
        #set_real_ip_from 172.21.0.0/16;
      
        proxy_pass emqx_broker_tcp_ssl;
        proxy_buffer_size 3M;
        #proxy_protocol on;
        tcp_nodelay on;
    }
`
the cluster is work OK ,but EMQX do not show the client real IP addr.
so  set  nginx   **“proxy_protocol on”**

then, I can't link success to the cluster, the log :

2021-11-18T17:10:16.024193+08:00 [error] 172.21.0.9:50224 [MQTT] , Parse failed for function_clause, [{emqx_frame,parse_packet,[{mqtt_packet_header,5,false,0,false},<<"OXY TCP4 112.9.120.88 172.21.0.9 15625 8883\r\n"...>>,#{max_size => 1048576,strict_mode => false,version => 4}],[{file,"emqx_frame.erl"},{line,204}]},{emqx_frame,parse_frame,4,[{file,"emqx_frame.erl"},{line,181}]},{emqx_connection,parse_incoming,3,[{file,"emqx_connection.erl"},{line,625}]},{emqx_connection,handle_msg,2,[{file,"emqx_connection.erl"},{line,618}]},{emqx_connection,process_msg,2,[{file,"emqx_connection.erl"},{line,364}]},{emqx_connection,handle_recv,3,[{file,"emqx_connection.erl"},{line,328}]},{proc_lib,wake_up,3,[{file,"proc_lib.erl"},{line,236}]}], Frame data:<<16,43,0,4,77,81,84,84,4,194,0,0,0,14,109,113,116,116,120,...>>

I guess does the proxy_protocol=on cause the  'mqtt_packet_header' add a real-ip? ( 112.9.120.88 172.21.0.9 looks like Added real IP)

If  I Comment out “proxy_protocol=on”  the cluster is work OK.

### Your environment

For EMQ X 4.3 or newer, please provide the log archive generated by [node_dump tool](https://github.com/emqx/emqx/blob/master/bin/node_dump) 

- EMQ X 4.3.5
- Hardware configuration (e.g. `lscpu`):
- OS (e.g. `cat /etc/os-release`): Centos 7.6
- Kernel (e.g. `uname -a`):  
- Erlang/OTP version (in case you build emqx from source code): 
- Others: Nginx 1.16.1

### Steps to reproduce
Tell us how to reproduce this issue. 

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

Missing log file can delay the handling of the issue.

**Comment by zmstone** [comment]
I’m not sure what binary proxy protocol nginx uses.
But emqx supports haproxy’s v2 binary protocol 
Haproxy example for ref: https://emqx.medium.com/sticky-session-load-balancing-mqtt-broker-clustering-part-2-cfe7e72f3969

**Comment by zmstone** [comment]
Mind this config: EMQX_LISTENER__TCP__EXTERNAL__PROXY_PROTOCOL=on

**Comment by wangxw** [comment]
> Mind this config: EMQX_LISTENER__TCP__EXTERNAL__PROXY_PROTOCOL=on
thanks， you got it！
I remove ‘#’  from “## listener.tcp.external.proxy_protocol = on” and “## listener.ssl.external.proxy_protocol = on”
then set the nginx config ：     proxy_protocol on;
the backend server get real IP addr 
I think “## listener.tcp.external.proxy_protocol = on”  should  the  default configuration value，but it's not。

**Comment by zmstone** [comment]
It can’t be default, because 
If we turn it on, non proxy will not work.

**Comment by roysG** [comment]
> > Mind this config: EMQX_LISTENER__TCP__EXTERNAL__PROXY_PROTOCOL=on
> 
> thanks， you got it！ I remove ‘#’ from “## listener.tcp.external.proxy_protocol = on” and “## listener.ssl.external.proxy_protocol = on” then set the nginx config ： proxy_protocol on; the backend server get real IP addr I think “## listener.tcp.external.proxy_protocol = on” should the default configuration value，but it's not。

AWSOME
