### ISSUE TITLE
User info

### ISSUE THREAD

**Issue by ajagnanan** [emqx/emqx#623]
I'm currently creating a custom auth plugin using oauth. I was looking for a way to store the access token after doing my login request for use in subsequent requests. Is this possible? If so, how I store this? 

Thanks.

**Comment by emqplus** [comment]
Hi @ajagnanan, I will check if the current auth_mod could support oauth.

**Comment by ajagnanan** [comment]
Is there a "current user" variable maybe? An object that gets associated with the client id and is available throughout all events. It could be managed by emqtt and passed in as an arg for hooks.

**Comment by ajagnanan** [comment]
Is it possible to get the username in the subscribe / publish hooks?

**Comment by emqplus** [comment]
Lookup the mqtt_client object by ClientId:

```
emqttd_cm:lookup(ClientId)
```

**Comment by yandooo** [comment]
@emqplus would you mind to suggest how to hook in properly into emqttd if there is need to pass custom authentication token between auth plugin and ACL plugin? The idea is to have auth plugin which `checks()` by user\pwd if client has access and needs to store some security information that will be analyzed by custom ACL plugin later.

This method returns record of type `#mqqt_client` which has all fields reserved for emqttd broker:

```
emqttd_cm:lookup(ClientId)
```
is there any way on how to carry state for clientId without rebuilding\modifying emqttd?

**Comment by yandooo** [comment]
To answer my question above. No way to carry state. For this purpose use shared EST table.

**Comment by Son-Lam** [comment]
Hello,

Would you mind update the timeline of this feature.

Best Regards,

**Comment by Gilbert-Wong** [comment]
Sorry for late response ,You could refer the code in other emqx-auth-* plugin, firstly register your auth mod to emqx and then implement your auth function by yourself.
