### ISSUE TITLE
Emqx disconnection logs without client id

### ISSUE THREAD

**Issue by YashJainSC** [emqx/emqx#6237]
I am getting this types of logs in my emqx setup

2021-11-19T09:08:57.473010+00:00 [info] ********IP:PORT****** file: emqx_connection.erl, line: 520, mfa: {emqx_connection,terminate,2}, msg: terminate, pid: <0.18856.2>, reason: {shutdown,tcp_closed}

Notice that logs don't have ClientId in them. 

There are so may logs of this type. Can you explain what this means. We have a load balancer ahead of emqx setups and we know the ips in the logs are of lbs

**Comment by qzhuyan** [comment]
`{shutdown,tcp_closed} `means the connection is closed by peer (load balancer)

**Comment by YashJainSC** [comment]
@qzhuyan but shouldn't the logs contain clientId as well, there are some disconnections logs which have ClientId@IP:PORT

**Comment by YashJainSC** [comment]
@qzhuyan can you please reply on above point

**Comment by qzhuyan** [comment]
Sorry for late reply. The support ticket is missing lots of information, even EMQX version is not mentioned.

At this stage maybe you could enable debug log by 
```
emqx_ctl log set-level debug
```

**Comment by YashJainSC** [comment]
Hey @qzhuyan , sorry for not adding enough info.

EMQx version: 4.3.8
Kernel: Linux emqx-0 5.4.129+ #1 SMP Thu Jul 8 19:57:33 PDT 2021 x86_64 Linux
OS: Alpine Linux v3.12

We have setup a single cluster of 8 emqx nodes behind a load balancer.

**Comment by YashJainSC** [comment]
@qzhuyan please can you check this

The problem is we are getting lot of this types of tcp_closed logs but no client is using that port on the load balancer to connect

**Comment by qzhuyan** [comment]
Which LB do you use? Is the LB configured to use a connections pool?

Depends on how you configure the LB, Maybe it is just LB closing idle connections.

**Comment by HJianBo** [comment]
Yes **it is just a TCP porting connection from LB or a temporary connection that does not send any MQTT connecting request**

In this scenario, we can't get your clientid, so here we can only print the IP and port. Don't worry, as soon as we receive your clientid, all the logs about it will carry the clientid; but until then, we can only use the ip and port to identify it.

**Comment by HJianBo** [comment]
If there are a lot of such logs, you need to check if the probing frequency of your LB is too high, or if there is a malicious client that is constantly trying to consume your tcp network connection resources without sending any MQTT related messages.

**Comment by zmstone** [comment]
Thank you for the investigation @HJianBo 
@YashJainSC we believe this should be a debug level log instead, it's fixed in this PR https://github.com/emqx/emqx/pull/6358

If your load balancer supports proxyprotocol, you can have it enabled, so EMQ X can get the real IP of the client.
https://docs.emqx.io/en/broker/v4.3/configuration/configuration.html#listener-tcp-external-proxy-protocol

**Comment by YashJainSC** [comment]
Yes @HJianBo thanks for your comment, it was lb probing only. We will make required changes to probing frequency.
