### ISSUE TITLE
Helm chart inputs

### ISSUE THREAD

**Issue by arseni-meteor** [emqx/emqx#6263]
### Subject of the support
Pass acl.conf and certificates when deploying K8s with the provided helm charts

Error/Warning printout if any. 
None

### Your environment
AWS EKS

I want to deploy EMQX using EKS, and set custom ACL rules and certificates.
I was able to change the default ACL and add my certificate by mounting a '/opt/emqx/etc' folder with my configuration.
Now I want to use the provided [helm charts](https://github.com/emqx/emqx/tree/ef0bdf641a941374283bd720dcd1caabc27923f1/deploy/charts/emqx), yet I see only an option to specify the 'emqxLicneseSecretName',
can you suggest a proper way to change the 'opt/emqx/etc/acl.conf' file and add my certificates to 'opt/emqx/etc/certificates' ?

I've added my acl.conf file (renamed to acl.txt)
[acl.txt](https://github.com/emqx/emqx/files/7584109/acl.txt)

Thank you!
Arseni

**Comment by qzhuyan** [comment]
It is doable by defining a configmap as in this helm chart 
https://github.com/emqx/emqx/blob/main-v4.3/deploy/charts/emqx/templates/StatefulSet.yaml#L69-L74

**Comment by arseni-meteor** [comment]
Looks great! Thank you
Is there a similar way to pass the certificates? I couldn't find it in the StatefulSet.yaml
