### ISSUE TITLE
规则

### ISSUE THREAD

**Issue by YangJiawei** [emqx/emqx#6276]
### Subject of the issue
```
动作类型保存数据到 MySQL (data_to_mysql)
保存数据到 MySQL 数据库
5000
SQL 模板

INSERT INTO mqtt_mpu(username,clientid,topic,payload,qos,peerhost,timestamp) 
SELECT ${username},${clientid},${topic},${payload},${qos},${peerhost},FROM_UNIXTIME(${timestamp}/1000) 
FROM DUAL WHERE EXISTS (SELECT * FROM mqtt_user WHERE username=${username})

async 启用批量插入 true 10 100 资源 IDresource:796207
```

响应动作为如果在数据表`mqtt_user`中存在该用户，则把数据插入到`mqtt_mpu`表中。实际测试的时候使用关键字`SELECT`就会报错，该怎么解决？！

### Your environment

For EMQ X 4.3 or newer, please provide the log archive generated by [node_dump tool](https://github.com/emqx/emqx/blob/master/bin/node_dump) 

- EMQ X version (e.g. `emqx_ctl status`): emqx-ee-centos7-4.3.5-amd64.zip

**Comment by jacknotepad** [comment]
试试把批量插入改成false

**Comment by YangJiawei** [comment]
关闭批量可以了，所以批量把这一条指令识别成了多条？

**Comment by jacknotepad** [comment]
您的邮件，我已接收。
