### ISSUE TITLE
Protocol 'ekka': register/listen error: eaddrinuse

### ISSUE THREAD

**Issue by jiangxuhui** [emqx/emqx#6296]
when i do this:
emqx console
bash-5.0$ emqx console
log.to = "console"
Protocol 'ekka': register/listen error: eaddrinuse

Protocol 'ekka': register/listen error: eaddrinuse

### Subject of the issue
Describe your issue here.

- EMQ X version :4.39
-os ： ununtu18.04

### Steps to reproduce
Tell us how to reproduce this issue. 

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

Missing log file can delay the handling of the issue.

**Comment by zmstone** [comment]
eaddrinuse hints the port is being used.
Are you trying to start more than 1 EMQX in the same machine?

**Comment by k32** [comment]
Note that `emqx console` command _starts_ a new version of the broker and attaches to its console. If you want to attach to an EMQX broker that is already running, you need to use `emqx remote_console` command instead.

**Comment by Undertone0809** [comment]
@k32 I want to ask you for help. I also have the same question(I only have one instance). Actually, I only run once on server and get this error. Moreover, I can run emqx image normally and my mqtt service works normally.I can not browser `IP:18083`.  My port has not conflict. I reborn the docker but failed. I delete the image and restart it but failed. I have tried a lots methods but I can not find the reason.

**Comment by Undertone0809** [comment]
> @k32 I want to ask you for help. I also have the same question. Actually, I only run once on server and get this error(I only have one instance). Moreover, I can run emqx image normally and my mqtt service works normally.I can not browser `IP:18083`. My port has not conflict. I reborn the docker but failed. I delete the image and restart it but failed. I have tried a lots methods but I can not find the reason.

I have solved the problem. I install `emqx/emqx:latest` but run failed. But I install `emqx/emqx:5.0.12` and run `emqx start` successfully. It confused me a lot. I want to know the reason why?

**Comment by k32** [comment]
Which operating system are you using? If you're on Linux, you can run `sudo netstat -tnlp` command to see which process listens on the ports that EMQX uses.

**Comment by Undertone0809** [comment]
> Which operating system are you using? If you're on Linux, you can run `sudo netstat -tnlp` command to see which process listens on the ports that EMQX uses.

centos. My process seem works normally.

![image](https://user-images.githubusercontent.com/72488598/208970140-55a62ce6-60e9-4bcd-a946-b1ebc067adfa.png)

**Comment by k32** [comment]
It seems like you mapped some service to port 18083 in docker. You can run `docker ps | grep 18083` to find which container is using the port and remap it to a different one.

**Comment by Undertone0809** [comment]
> Which operating system are you using? If you're on Linux, you can run `sudo netstat -tnlp` command to see which process listens on the ports that EMQX uses.

I install `emqx/emqx:latest` but run failed before. Error msg is :
```
Protocol 'ekka': register/listen error: eaddrinuse
```
Now I install `emqx/emqx:5.0.12` and run `emqx start` . The error is:
```
Protocol 'ekka': register/listen error: "port 4370 is in use
```

**Comment by Undertone0809** [comment]
> It seems like you mapped some service to port 18083 in docker. You can run `docker ps | grep 18083` to find which container is using the port and remap it to a different one.

My 18083 port is used by emqx. I run the following command to run the instance.
```
docker run -d --name emqx -p 1883:1883 -p 8083:8083 -p 8084:8084 -p 8883:8883 -p 18083:18083 emqx/emqx:5.0.12
```

![image](https://user-images.githubusercontent.com/72488598/208971063-4c88d963-b40d-427c-a473-1af87ef607bb.png)

**Comment by k32** [comment]
So you already have one emqx instance running on the machine in docker? You cannot start another EMQX process (without changing ports/or listen IPs the configuration) in this case on the same machine. 
You either need to stop the container (shown in the docker ps), or start the new instance of EMQX in docker and remap the ports to different values.

**Comment by Undertone0809** [comment]
> So you already have one emqx instance running on the machine in docker? You cannot start another EMQX process (without changing ports/or listen IPs the configuration) in this case on the same machine. You either need to stop the container (shown in the docker ps), or start the new instance of EMQX in docker and remap the ports to different values.

I only run one instance on the machine. My first step is:
```
docker run -d --name emqx -p 1883:1883 -p 8083:8083 -p 8084:8084 -p 8883:8883 -p 18083:18083 emqx/emqx:5.0.12
```
After that, I enter the container and input the following command:
```
emqx start
```
Is there anything wrong?

**Comment by Undertone0809** [comment]
Oh god! What am I doing. It's done. Thanks for your help. It's seem doesn't run `emqx start` enter container. I was misinterpreted by the documentation to think that `emqx start` was running after starting the container.

**Comment by k32** [comment]
I see. Indeed, `emqx start` starts a new EMQX broker process in the background on the local machine. To start a container you need `docker run ...` command.
