### ISSUE TITLE
win10 启动不了emq

### ISSUE THREAD

**Issue by xxxxxxming** [emqx/emqx#6313]
emq版本: v4.3.10 开源版
服务器版本: windows10 专业版

我按照文档下载了emq,并且将它解压到了我的D盘根目录下面,然后进入bin 下面执行: 
emqx start, 它没有任何反应,查看log 文件夹,也没有日志产生;输入 emqx ping,提示:Node 'emq@127.0.0.1' not responding to pings. 执行 emqx console, 它首先会弹出如下图界面,然后就直接关闭了.
![微信截图_20211126150918](https://user-images.githubusercontent.com/47131915/143543884-3a7ba559-5ae0-4d43-837e-cbe229054a18.png)
请大佬们帮帮忙看下问题!

**Comment by qzhuyan** [comment]
@xxxxxxming pls try `emqx console` to get more informative errors for troubleshooting.

**Comment by zmstone** [comment]
`emqttd` 古早以前的名字。
这表明你启动的不是新安装的版本，现在叫 emqx

**Comment by 45677491** [comment]
请问一下有没有解决问题？

**Comment by zmstone** [comment]
@45677491 请问用的哪个版本？ 
4.3 有问题的话，建议开一个新的issue我们跟进调查

**Comment by mikite** [comment]
win10专业版也是这样的现象，启动不起来

**Comment by twjer** [comment]
> 

这个确实是这样的，但是我换了其他版本的win10家庭中文版可以运行起来，暂不清楚是win10防火墙,自带杀毒软件的问题还是其他问题
