### ISSUE TITLE
Backup of Sessions, Subscriptions and Messages in free version

### ISSUE THREAD

**Issue by on-delete** [emqx/emqx#6332]
As per the documentation, i understood that all sessions, subscriptions and messages will be backed up into e.g. a database and that the broker instances are stateless. And that this is a enterprise only feature, so we cannot use it in our free version.

Will this behaviour changed with the new EMQX 5 version? Will this become free, or is this a feature that will still be in the enterprise edition only? We need to persist sessions over a broker restart so that no message get lost on these occasions.

**Comment by zmstone** [comment]
Yes. There is going to be a on-disk persistent session support in version 5
