### ISSUE TITLE
Guidance on using emqttd for a chat app

### ISSUE THREAD

**Issue by pranavmehta** [emqx/emqx#634]
I would like to leverage emqttd to build a whatsapp like chat app. Seeking some architectural guidance here, because I have zero experience with Erlang. 

My question really is around the recommended server side architecture, on how to process messages that are exchanged between the clients. I need to apply some business rules (filter specific words, check if the recipient has blocked the sender, etc etc. I understand there is the template plugin I can leverage, but Ideally, I'd like to do the processing outside of Earlang entirely. I'd also like to store the message in an external database for archival purposes 

I am thinking of creating 1 topic for each user that it subscribes to (readonly) for all incoming messages.  The message payload contain the additional metadata as to who is the real intended recipient, message content, etc. All users also publish only to a fixed set of topics.

I will then set up clients (in my prefered language of development) that listen to the topics where messages are published to, do the business rules processing and takes the appropriate action further, like publishing it to the intended recipient users topic, dropping the message, throttle the number of messages, whatever my business rules require. This is where I also archive the messages for future use

Would this be a reasonable architecture? Would it work at scale? Any better design / best practices recommendations?

Thanks! 

PS: Awesome, awesome project!

**Comment by emqplus** [comment]
Hi @pranavmehta, we built an emqchat app based on emqttd broker. We defined two types of topics for private/group chat:

```
Private Chat Topic: chat/user/${uid}/inbox

Group Chat Topic: chat/room/${room}/inbox
```

**Comment by pranavmehta** [comment]
Thanks a lot for the response. Your suggestion makes a lot of sense.

Can you please make some recommendation regarding processing the messages before they are delivered to the recipient? Would you recommend having dedicated "listener" clients on the server that received all messages from the mobile devices, processes them and puts its in the intended users inbox? In this approach I am using emqttd for bi-directional messaging

Or you you recommend a standard REST API that all users post messages to, which in turn does the processing and puts the message to the recipient's inbox? In this approach, I am using emqttd purely to  push messages downstream from the server to the handsets.

Your feedback is very much appreciated. Thanks a lot!

**Comment by pavankumarkatakam** [comment]
Hi @pranavmehta, have tried the both approaches and can you share me the advantages and disadvantages of both.

**Comment by pavankumarkatakam** [comment]
@pranavmehta, I choose first way since HTTP API add overhead
