### ISSUE TITLE
pvc with Helm - permission denied

### ISSUE THREAD

**Issue by arseni-meteor** [emqx/emqx#6348]
### Subject of the issue
Getting a permission denied error when creating an EMQX cluster with helm.

EMQ X version 4.3.9
K8s Cluster

### Steps to reproduce
I've created a basic PV and PVC,
**PV:**
`apiVersion: v1
kind: PersistentVolume
metadata:
  name: emqx-pv
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/ubuntu/pv"`
**PVC:**
`apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: emqx-pvc
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi`
And started the cluster with helm (using this [guide](https://www.emqx.com/en/blog/rapidly-deploy-emqx-clusters-on-kubernetes-via-helm#deploy-a-persistent-emq-x-cluster)) with this command:
`helm install emqx-pepper -f values_cert.yaml emqx/emqx --version 4.3.9 --set persistence.enabled=true --set persistence.existingClaim=emqx-pvc`
Yet the pods don't run and I keep getting this error:
`2021-12-02T01:15:21.380770+00:00 [error] Error creating /opt/emqx/data/configs: permission denied`
And the pods get stuck at a CrashLoopBackOff state..

### Expected behaviour
Running pods with a directory at '/opt/emqx/data/mnesia' of my pv

### Actual behaviour
The pods keep crushing and giving the following error:
`2021-12-02T01:15:21.380770+00:00 [error] Error creating /opt/emqx/data/configs: permission denied`

Any ideas why the PVC don't work?

**Comment by qzhuyan** [comment]
@arseni-meteor I see the PV is having `storageClassName: manual`, what is the type of storage class it is, maybe you should check the permission from there?

**Comment by qzhuyan** [comment]
Could you run ``` kubectl get storageclass ```  to check the Volume Plugin in use?

**Comment by arseni-meteor** [comment]
Sure
ubuntu@ip-10-63-49-154:~$ kubectl get storageclass
NAME            PROVISIONER             RECLAIMPOLICY   VOLUMEBINDINGMODE      ALLOWVOLUMEEXPANSION   AGE
gp2 (default)   kubernetes.io/aws-ebs   Delete          WaitForFirstConsumer   false                  108d

**Comment by qzhuyan** [comment]
Could you open a console in emqx pod and check the permission there?

**Comment by giridhar08** [comment]
I am getting the same issue as above. Are you able to resolve this issue?
