### ISSUE TITLE
规则的命中速度

### ISSUE THREAD

**Issue by coolhlm** [emqx/emqx#6352]
1.规则的命中速度是如何计算出来的?( 比如连续命中2条,命中速度是0.2,但是5min平均速度是0.01)
![image](https://user-images.githubusercontent.com/30930127/144346929-38798035-03b4-48a5-beb1-843d5e04ede6.png)

2.如果有多个emqx节点(集群),可以把各个节点命中速度求和取平均值作为集群的命中速度么?

3.多个节点的情况,客户端连接($events/client_connected事件)是随机连到一个节点,还是轮询的?

**Comment by zmstone** [comment]
sorry for the late reply.

message rate is calculated locally.
rate is not very accurate when it's low.
