### ISSUE TITLE
After restart, One clinet can't be kicked,and timeout.

### ISSUE THREAD

**Issue by curtiseng** [emqx/emqx#6367]
### Subject of the issue
After restart, One clinet can't be kicked by dashbord and emqx_ctl.
```
./emqx_ctl clients kick alarm-crane-d989abe9-4baa-4b9e-af48-4e3cd7d346af
RPC to emqx@127.0.0.1 failed: timeout
```

### Your environment

- EMQ X version (e.g. `emqx_ctl status`): emqx 4.2.11
- OS (e.g. `cat /etc/os-release`): Ubuntu 18.04.1 LTS
- Kernel (e.g. `uname -a`): Linux 4.15.0-29-generic

### Steps to reproduce
Restart the emqx.

### Expected behaviour
Clean client seesion.

### Actual behaviour
Timeout.

Missing log file can delay the handling of the issue.

**Comment by k32** [comment]
Hello,

This problem has been fixed by this PR: https://github.com/emqx/emqx/commit/831f2eda0cfa7352b608c334be434c4f549d7ceb
It has been released in 4.3.9
