### ISSUE TITLE
Feature-Request: Retained Message should not be sent again after connection-outage with cleanSession=false

### ISSUE THREAD

**Issue by gbrehmer** [emqx/emqx#6402]
**What would you like to be added/modified**:
Possibility to change behavior from retained messages if `Clean-Session` is `false`: already received retained messages should not be sent out a second time if the client had a connection outage (like on service restart or network problems).
Probably this was already the case with emqttd 2.x and was changed with late 2.x or version 3. This new behavior should not be set as default behavior, because it is not defined in the mqtt standard. It would be fine for us if its an opt-in feature :)

**Why is this needed**:
We have some standard retained messages like "device-status". If a backend service must be restarted, the device status must be processed from all devices again instead of only changed devices during connection break (offline messages)
We also use retained messages as a fallback/as a kind of storage, if we want explicitly process all retained messages again, we could use `Clean-Session=true`

**Comment by zmstone** [comment]
@HJianBo didn't we recently have a fix for this in 4.3?

**Comment by HJianBo** [comment]
We only send Retain messages for all topics matched by the subscription after the client initiates a subscription request.

I just checked the v2.3.11 implementation and we didn't identify if this was a newly created subscription relationship, so we sent Retain messages for that topic whenever we received a subscription request from a client.

This is a bug that we fixed in 4.3.x and 4.2.x. We make a determination if this is a new subscription relationship (e.g., it is a new topic, or uses a different QoS), and if so, we deliver the Retaine message for the topic matched by the subscription request.

@gbrehmer We recommend that you consider upgrading to the latest version of 4.3, such as 4.3.10, because we have no maintenance plans for v2.x and v3 in the near future.

**Comment by gbrehmer** [comment]
We use the latest version 4.3.10, but currently we are resubscribing the same topics to be sure that no subscriptions from session was lost. We well check this again, because as you said and If I understand it correctly it should already work as requested:
In the following cases no existing retained message should be sent out twice (like after connecteion loss)
- If we make no new subscription request (because subscription is still alive due to session context)
- if we make exactly the same subscription request (same QoS and topic)

It is possible that if there are some limits raised, that this behavior changes? We have >200k retained messages and 10 backend clients, which each subscribes to 25 wildcard topics. so each client/session has access to 20k retained messages

**Comment by gbrehmer** [comment]
> We have >200k retained messages and 10 backend clients, which each subscribes to 25 wildcard topics.

those subscriptions are wildcard subscriptions (<1>/<2>/#)

**Comment by gbrehmer** [comment]
we have to resubscribe to each topic, because we can not be sure wether connection outages was because of a broker outage (which can lost all sessions)

**Comment by gbrehmer** [comment]
further hints: we are subscribing to all topics at once (by providing a list of topic/QoS levels)

I've tested with several servers (out test and stage system, public emqx test server) and clients:
1. connect to broker with clean session = false
2. publish a retained message QoS 1
3. Subscribe to Wildcard Topic QoS 1
4. Receives Retained Message
5. Disconnect Client
6. Checked emqx dashboard: disconnected client still exists, subscription is listed
7. Reconnect to broker with same client-id and username
8. Resubscribe to Wildcard Topic QoS 1
9. Receives retained message again (<-- this is unwanted)

**Comment by HJianBo** [comment]
@gbrehmer Thanks for your detailed reproduce steps.

This is indeed a bug. According to the mqtt-3.1.1 specification, this message is should not be delivered. We will fix it soon in the next version.

**Comment by gbrehmer** [comment]
It is possible to drop this bugfix as 4.3.11 in the next days? :)

**Comment by zmstone** [comment]
Hi @gbrehmer 
4.3.11 will be cut early next week, I'm afraid this fix will miss this release cut.

**Comment by gbrehmer** [comment]
ok is a 4.3.12 planned or is the fix only for 4.4 or 5.0 available

**Comment by zmstone** [comment]
yes, there will be a 4.3.12, but unsure about the release date now.
we are releasing 4.4.0 soon, so the fix will be ported to 4.4.1.
5.0 is on beta.3, we are targeting GA in April.

**Comment by HJianBo** [comment]
After a team discussion, we believe that the previous implementation was correct. So I may have misjudged and this is not a bug.

In the MQTT-v3.1.1 Spec:
> If a Server receives a SUBSCRIBE Packet containing a Topic Filter that is identical to an existing Subscription’s Topic Filter then it MUST completely replace that existing Subscription with a new Subscription. The Topic Filter in the new Subscription will be identical to that in the previous Subscription, although its maximum QoS value could be different. **Any existing retained messages matching the Topic Filter MUST be re-sent**, but the flow of publications MUST NOT be interrupted [MQTT-3.8.4-3].

**So, for the MQTT v3.1.1 protocol implementation, we resend the retain message associated with this topic as long as 
we receive a subscription request.**

In the 5.0 Spec, a new subscription parameter `Retain Handling` has been introduced. You can set it to 1 to completely resolve the issue you experienced.
> - If Retain Handling is set to 0 the Server MUST send the retained messages matching the Topic Filter of the subscription to the Client [MQTT-3.3.1-9].
> - If Retain Handling is set to 1 then if the subscription did not already exist, the Server MUST send all retained message matching the Topic Filter of the subscription to the Client, and if the subscription did exist the Server MUST NOT send the retained messages. [MQTT-3.3.1-10].
> - If Retain Handling is set to 2, the Server MUST NOT send the retained messages [MQTT-3.3.1-11].

**Comment by gbrehmer** [comment]
@HJianBo  thanks for your explanation, we will switch to mqttv5 in our backend services

**Comment by gbrehmer** [comment]
@HJianBo 
Sorry I have to reopen this topic. 
We have tested it now, and it does not work in the reconnect use-case:

working use-case:
1. connect with clean-session = false
2. send retained message to topic test (QoS 1)
3. subscribe to topic test with retain handling = 1 -> received retained message = OK
4. resubscribe to same topic with same settings -> no more messages = OK

not working use-case
1. connect with clean-session = false
2. send retained message to topic test (QoS 1)
3. subscribe to topic test with retain handling = 1 -> received retained message = OK
4. disconnect
5. connect with clean-session = false (same client-id)
6. subscribe to topic test with retain handling = 1 -> received retained message = NOT OK

**Comment by gbrehmer** [comment]
same results with 4.4.9 and 5.0.8. It seems that subscriptions are gone with disconnection also for active session clients (clean_session = false)

**Comment by gbrehmer** [comment]
sorry....we have to set session expiry parameter, I thought that by default session will not expire. It's working if I set this parameter

**Comment by gbrehmer** [comment]
probably the javadoc from Paho is wrong: "By default this value is null and so will not be sent, in this case, the session will not expire."
https://github.com/eclipse/paho.mqtt.java/blob/f4e0db802a4433645ef011e711646a09ec9fae89/org.eclipse.paho.mqttv5.client/src/main/java/org/eclipse/paho/mqttv5/client/MqttConnectionOptions.java#L515
I will raise a bug there
