### ISSUE TITLE
Maximum heap size reached

### ISSUE THREAD

**Issue by ybronshtein** [emqx/emqx#6406]
### Maximum heap size reached
Reopen of issue 5717
EMQX crash when during large download/upload.
We're sending a file from device ID 1PC4200AB6000000000069 , the filesize is 1.2MB .
It is received by the broker but failed with the error "maximum heap size reached".
Please look at lines 488 and 489 of the attached log.

### Your environment
Kubernetes 1.15
For EMQ X 4.3 or newer, please provide the log archive generated by [node_dump tool](https://github.com/emqx/emqx/b
[e2eemqx-0.log](https://github.com/emqx/emqx/files/7677864/e2eemqx-0.log)
lob/master/bin/node_dump) 

- EMQ X version (e.g. `emqx_ctl status`): 4.3.8
- Hardware configuration (e.g. `lscpu`): 
- OS (e.g. `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Erlang/OTP version (in case you build emqx from source code): 
- Others:

### Steps to reproduce
Tell us how to reproduce this issue. 

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

Missing log file can delay the handling of the issue.

**Comment by zmstone** [comment]
sorry for the late reply.
maximum heap size is controlled by this config
`zone.external.force_shutdown_policy = 10000|64MB`
this example config means the process is killed if it accumulates more than `10000` messages in its internal receiving queue, or allocated more than 64MB for its heap space.

**Comment by sushantAtAws** [comment]
@zmstone 
Is there any log which tells us if the process is being killed because of any of this reason (messages or size)? 

I have this config:
```
{force_shutdown_policy,
        #{max_heap_size => 8388608,message_queue_len => 10000}},
```
Is this size in bytes?

Also, what is the difference between zone.external vs zone.internal?

**Comment by zmstone** [comment]
` #{max_heap_size => 8388608,message_queue_len => 10000}` is the internal format translated from the force_shutdown_policy config in emqx.conf 

8388608 is the number of “word”s in Erlang but not bytes. One word is 8 bytes in 64bit systems.

‘internal’ ‘external’ are config/security zone names which you are free to change or add new ones.

internal is usually used for internal access, e.g. listeners listen on the loopback address, or a private ip.

**Comment by kadarpik** [comment]
I still see this issue, no configuration change helps, I can not publish  400 KB payload even.

2023-02-02T01:13:25.461915+02:00 [error] Process:            <0.2785.0> on node 'emqx@127.0.0.1', Context:            maximum heap size reached, Max Heap Size:      6291456,

**Comment by zhongwencool** [comment]
Hi @kadarpik   Did you set the log to debug level?
If so, you can change debug to warning or try v4.3.16 or v4.4.5
we fixed a similar problem https://github.com/emqx/emqx/issues/9867
 in v4.3.16 and v4.4.5.

**Comment by javadoge** [comment]
I also encountered the same problem，emqx version ：5.x

Context:            maximum heap size reached, Max Heap Size:      6291456, Total Heap Size:    9100325, Kill:               true, Error Logger:       true, Message Queue Len:  0, GC Info:            [{old_heap_block_size,3581853},{heap_block_size,5472277},{mbuf_size,59456},{recent_size,822523},{stack_size,62},{old_heap_size,0},{heap_size,2474138},{bin_vheap_size,205405},{bin_vheap_block_size,220491},{bin_old_vheap_size,0},{bin_old_vheap_block_size,46422}]
