### ISSUE TITLE
Wrong maximum Qos

### ISSUE THREAD

**Issue by anaconda875** [emqx/emqx#6429]
### Subject of the issue
wrong maximum Qos

### Your environment

For EMQ X 4.3 or newer, please provide the log archive generated by [node_dump tool](https://github.com/emqx/emqx/blob/master/bin/node_dump) 

- EMQ X version (e.g. `emqx_ctl status`): 4.3
- Hardware configuration (e.g. `lscpu`): Core i5 6440HQ
- OS (e.g. `cat /etc/os-release`): Windows 10
- Kernel (e.g. `uname -a`):
- Erlang/OTP version (in case you build emqx from source code): 
- Others: I'm running EMQ X on Docker

### Steps to reproduce
I'm trying to connect to the EMQX with HiveMQ Java client with MQTT5 protocol:
- Depedency: 
            groupId: com.hivemq
            artifactId: hivemq-mqtt-client
            version: 1.2.1

- Code:
        Mqtt5BlockingClient mqtt5BlockingClient = MqttClient.builder()
                    .automaticReconnect()
                    .initialDelay(500, TimeUnit.MILLISECONDS)
                    .maxDelay(2, TimeUnit.MINUTES)
                    .applyAutomaticReconnect()
                    .identifier("deviceID" + "-pub")
                    .addDisconnectedListener(mqttClientDisconnectedContext -> {
                        System.out.println("Disconnected");
                        System.out.println("error" + mqttClientDisconnectedContext.getCause());
                        System.out.println("counter " + mqttClientDisconnectedContext.getReconnector().getAttempts());
                    })
                    .serverHost("localhost")
                    .serverPort(1883)
                    .useMqttVersion5()
                    .simpleAuth()
                    .username("admin")
                    .password("public".getBytes())
                    .applySimpleAuth()
                    .buildBlocking();
            mqtt5BlockingClient.connect();   ------------------------------------------> THIS LINE

### Expected behaviour
I expect that at least I can connect to the EMQ X

### Actual behaviour
The EMQX sends back wrong maximum Qos:
Exception while decoding CONNACK: wrong maximum Qos
![image](https://user-images.githubusercontent.com/10293078/145702891-d868df0a-162d-4b67-8d0a-34d27af91ab2.png)
As you can see the maximumQosCode is 2.

**Comment by zmstone** [comment]
Thank you for reporting the issue @anaconda875 

this seem to be a bug in the code.

> 3.2.2.3.4 Maximum QoS
36 (0x24) Byte, Identifier of the Maximum QoS.
Followed by a Byte with a value of either 0 or 1. It is a Protocol Error to include Maximum QoS more than once, or to have a value other than 0 or 1. If the Maximum QoS is absent, the Client uses a Maximum QoS of 2.

**Comment by HJianBo** [comment]
@anaconda875 Could you give me your emqx exact version number?  This bug has been fixed on 4.0.5 https://github.com/emqx/emqx/pull/3321

**Comment by anaconda875** [comment]
@HJianBo, very sorry, my fault. The version is 4.0. After I upgrade to 4.1.5 it get fixed

**Comment by HJianBo** [comment]
Please feel to free. if you have any question here.

**Comment by zmstone** [comment]
> @HJianBo, very sorry, my fault. The version is 4.0. After I upgrade to 4.1.5 it get fixed

Hi @anaconda875 just FYI. 4.1 is no longer in maintenance window.
Please consider adopting the latest 4.3.
