### ISSUE TITLE
Global routing table limit

### ISSUE THREAD

**Issue by rahulbhanushali** [emqx/emqx#644]
The docs state that the global routing table has a max limit of 10 million records. 

"Cluster of emqttd broker could support 10
million size of global routing table now. We could use the Consistent Hash or DHT to partition the routing table, and evolve the cluster to larger size."

Questions
1.  The global routing table contains the topics and the nodes subscribing to each of the topic.  So if i have 10 nodes in the cluster each subscribing to 1 million unique topics  I would reach this limit?  Or am i interpreting this incorrectly. 
2.  What exactly "subscriptions are stored only in local nodes"  means (read it in the docs) ?
3. The documentation does not shed any light on partitioning the routing table.  So if the limit is 10 million how can I partition the  routing table to increase the limit?

**Comment by rahulbhanushali** [comment]
Do this limit still exist with the newer release of emqtt?

**Comment by Gilbert-Wong** [comment]
Sorry for late response, @rahulbhanushali , it is awkward to answer your question so lately.
1. In the latest emqx release, there is no such limit again.
2. It means the subscriptions can only be stored in local node, they could not be backup or migrated across different nodes.
3. The routing table partition has been implemented in latest emqx release.
