### ISSUE TITLE
cluster join rejected. Invalid challenge reply

### ISSUE THREAD

**Issue by lytmkai** [emqx/emqx#6440]
**I'm using emqx 4.3.10 on two centos server, firewall both disabled.  when cluster join, got follow error :**
`[root@elasticsearch emqx]# ./bin/emqx_ctl cluster join emqx@192.168.1.178`
`Failed to join the cluster: {node_down,'emqx@192.168.1.178'}`

**Check logs only got follow error :**
`[root@GitServer emqx]# tail -f emqx.log.1`
`2021-12-13T20:04:16.679935+08:00 [error] ** Connection attempt from node 'emqx@192.168.1.45' rejected. Invalid challenge reply. **
`

please help, thanks.

**Comment by zmstone** [comment]
Invalid challenge hints you have different cookies.
set `node.cookie` in emqx.conf
or set `EMQX_NODE_COOKIE` environment variable.
