### ISSUE TITLE
Bad handling of Receive Maximum

### ISSUE THREAD

**Issue by mladedav** [emqx/emqx#6447]
### Receive Maximum Exceeded is handled incorrectly
Sometimes emqx returns PUBREC packets with code 147, which should be used only in DISCONNECT packets.

Furthermore it should not send it in my case because there is no value for Receive Maximum sent in the CONNACK packet and therefore 65535 should be used as a default value. I have at most 4096 QoS 2 packets in-flight at that time. 4096 QoS 1 packets were acknowledged prior to that and therefore should not be an issue either.

### Your environment

- EMQ X version 4.3.10
- Hardware configuration (e.g. `lscpu`): Docker - the command is not working there
- OS (e.g. `cat /etc/os-release`): 
NAME="Alpine Linux"
ID=alpine
VERSION_ID=3.12.8
PRETTY_NAME="Alpine Linux v3.12"
HOME_URL="https://alpinelinux.org/"
BUG_REPORT_URL="https://bugs.alpinelinux.org/"
- Kernel (e.g. `uname -a`): Linux 8e607787baf1 5.4.72-microsoft-standard-WSL2 #1 SMP Wed Oct 28 23:40:43 UTC 2020 x86_64 Linux

### Steps to reproduce
Send 4096 QoS 2 messages in a short time interval.

### Expected behaviour
Get one of the supported codes or a DISCONNECT packet.

### Actual behaviour
Sends PUBREC with non-existent status code (not supported for this packet type).

**Comment by HJianBo** [comment]
Hi, @mladedav Thanks for your report.
This bug should have been introduced in a very early version (probably when 4.0 was released)

We plan to fix it in the next release, probably in 4.3.12 and 4.4.1

**Comment by mladedav** [comment]
@HJianBo Thank you.

Have you also tried reproducing the second part? To my knowledge I haven't exceeded the receive maximum quota so there may be another issue and I worry that the fix will result in receiving DISCONNECT packets when the broker should still accept messages.

For the record it happens only with QoS 2 and not Qos 1.
