### ISSUE TITLE
Value is not reflecting in emqx_auth_redis.conf file

### ISSUE THREAD

**Issue by VaibhavMishra2069** [emqx/emqx#6457]
I have docker-compose.file. We are passing redis server, redis password but these values are not coming in emqx_auth_redis.conf file, so emqx is not able to connect with redis.

version: '3'
services:
emqx:
image: emqx/emqx:4.3.10
restart: always
environment:
- EMQX_LOG__LEVEL=info
- EMQX_LOADED_PLUGINS=emqx_auth_redis
- EMQX_AUTH__REDIS__SERVER= <-server-ip->:6380
- EMQX_AUTH__REDIS__PASSWORD= <-password->
- EMQX_AUTH__REDIS__AUTH_CMD=HMGET mqtt_user:%u password salt
- EMQX_AUTH__REDIS__PASSWORD_HASH=salt,sha256
- EMQX_AUTH__REDIS__SSL=on
- EMQX_AUTH__REDIS__TYPE=single

**Comment by k32** [comment]
Hello, 
The configuration handing has been slightly changed in 4.3. Starting from this version the environment variables don't modify the contents of the configuration files, instead they are applied in memory. So there should be another reason why the brocker doesn't connect to redis.
