### ISSUE TITLE
Emqx crashes on Android 12

### ISSUE THREAD

**Issue by mohammadfazelp** [emqx/emqx#6482]
It seems that the emqx needs to be updated to support android version 12 because it crashes at the beginning.

![Screenshot 2021-12-18 114355](https://user-images.githubusercontent.com/23038405/146634680-c132ee75-870c-4490-9505-a6cf33b937e4.png)

**Comment by zmstone** [comment]
Hello.

By the look of the stacktrace, it seems to be a paho MQTT client library crashed.
I’m afraid you have reported the issue to the wrong place.

EMQ X is the MQTT message broker which does not run on android.
Maybe EMQ X is the MQTT broker which you connect from android ?

**Comment by mohammadfazelp** [comment]
Please take a look at this link @zmstone 
https://www.emqx.com/en/blog/android-connects-mqtt-using-kotlin

**Comment by zmstone** [comment]
Yes.
> Open build.gradle of the project, add dependencies Eclipse Paho Java Client and Eclipse Paho Android Service to the section dependencies.

It's an issue of Eclipse Paho Java client, not EMQ X the broker.
@Zhiw you seem to be the author of hat article, is there a better place to track this issue ?
