### ISSUE TITLE
how to hook publish to clientID(session) ?

### ISSUE THREAD

**Issue by roytan883** [emqx/emqx#650]
I want design a  push system based on emqttd. 

But for iphone users, the APP's network connection will be closed by iOS system when the APP at background. Then the APP's mqtt layer can't receive any message, the push will fail . So in such scenario, my push system should push message to APNS. (for iphone user, my push system should push to emqttd and APNS both, then APP client should ignore the duplicate message)

for example: 
Clients A, B , C has subscribed topic T. And client C's clientID is "ios-zxcvxzcvsdf", i want add a hook here which can hook any message send to client ID string start with "ios-". Then in the hook can push this message to APNS server .

(hook sending to the clientID message: means ignore the client online status. The hook should active just before publish to the client session)

I read the emqttd_plugin_template.erl , find the on_message_publish() don't have ClientId parameter. 
Can you add new hook or tell me how to hook session message?

```
%% transform message and return
on_message_publish(Message = #mqtt_message{topic = <<"$SYS/", _/binary>>}, _Env) ->
    {ok, Message};

on_message_publish(Message, _Env) ->
    io:format("publish ~s~n", [emqttd_message:format(Message)]),
    {ok, Message}.

on_message_delivered(ClientId, Message, _Env) ->
    io:format("delivered to client ~s: ~s~n", [ClientId, emqttd_message:format(Message)]),
    {ok, Message}.

on_message_acked(ClientId, Message, _Env) ->
    io:format("client ~s acked: ~s~n", [ClientId, emqttd_message:format(Message)]),
    {ok, Message}.
```

**Comment by freecnpro** [comment]
If I understand correctly, you need this: https://github.com/emqtt/emqttd/blob/master/include/emqttd.hrl#L119

**Comment by roytan883** [comment]
i need hook message before publish it to client session, not online status.
A --> Topic --> (hook here) --> B 

the hook should provide free agrs: topic, message, targetClientId(B)

**Comment by freecnpro** [comment]
https://github.com/emqtt/emqttd/blob/master/src/emqttd_server.erl#L101
emqttd will call emqttd:run_hooks('message.publish', [], Msg) before publish to client session

**Comment by roytan883** [comment]
the message publish  hook don't have targetClientID !!!
```
on_message_publish(Message = #mqtt_message{topic = <<"$SYS/", _/binary>>}, _Env) ->
    {ok, Message};

on_message_publish(Message, _Env) ->
    io:format("publish ~s~n", [emqttd_message:format(Message)]),
    {ok, Message}.
```

**need receiver's clientID (targetClientID), not publisher's ID.**
```
from            :: binary() | atom(),     %% ClientId of the publisher
```

**those two hook has target ClientId, why publish hook don't have???**
```
on_message_delivered(ClientId, Message, _Env) ->
on_message_acked(ClientId, Message, _Env) ->
```

**Comment by roytan883** [comment]
I think there should have four kinds of publish message hook:
**1, before publish to topic (fromID, topic, msg)
2, after publish to topic (fromID, topic, msg)
3, before publish to specific session (fromID, topic, msg, toID), msg not send to session yet
4, after publish to specific session (fromID, topic, msg, toID), msg has sent to session, may on fly or in session queue>**

currently , I need the third hook **"3, before publish to specific session"**

then in this hook, I can parse the toID whether if send to APNS

**Comment by roytan883** [comment]
If hook **3** is impossible, hook **4** is also OK. I just need a hook to get the **"toID"**.
**on_message_delivered** and **on_message_acked** seems inappropriate, they have **"toID"**, but they depend on network result, if client is offline the two hooks will not fire.

**Comment by roytan883** [comment]
???

**Comment by freecnpro** [comment]
If you prefer, you can add your own hook in https://github.com/emqtt/emqttd/blob/master/src/emqttd_pubsub.erl#L121

**Comment by roytan883** [comment]
So currently, emqttd not support **hook 3 and 4 ？**

**Comment by jayareddyd** [comment]
Hi, Any progress on adding hook before publish so that push notifications can be sent to registered subscribers

**Comment by Gilbert-Wong** [comment]
Current emqx hook design should satisfy your guys' requirement.
