### ISSUE TITLE
Need to understand what does reason: {shutdown,discarded} means

### ISSUE THREAD

**Issue by YashJainSC** [emqx/emqx#6523]
EMQx version: 4.3.8
Kernel: Linux emqx-0 5.4.129+ SMP Thu Jul 8 19:57:33 PDT 2021 x86_64 Linux
OS: Alpine Linux v3.12

Hello ,We are sending connection request to broker with clean session = true every time. I wanted to understand what this particular log means.

`CLIENT@ip:port file: emqx_connection.erl, line: 520, mfa: {emqx_connection,terminate,2}, msg: terminate, pid: <0.6879.18>, reason: {shutdown,discarded}`

**Comment by thalesmg** [comment]
Hi @YashJainSC !

When a client connects to the broker using `clean_session = true`, it means that any sessions that might exist for that particular client_id should be discarded and a new one created.  So, `{shutdown, discarded}` means that: an existing session is being discarded by the new client connection.

**Comment by YashJainSC** [comment]
@thalesmg the previous connect request was also with clean_session = true so there wasn't any session for the user

**Comment by thalesmg** [comment]
Even when the previous connection is started with `clean_session = true`, a session is created which holds the client information for that connection, such as subscriptions.  That does not mean that such session is a _persistent_ session.
