### ISSUE TITLE
MQTT client keepalive problem

### ISSUE THREAD

**Issue by seksity** [emqx/emqx#6545]
### Subject of the issue
I using EMQX with Node.JS application and MQTT client [https://www.npmjs.com/package/mqtt#example](url)
When Node.JS MQTT client try to connect to EMQX with options KEEPALIVE 30seconds, It FAILED for connection

IF REMOVE KEEPALIVE option, connection is successfully

### Your environment
MacOS 12.1
EMQX 4.3.10
Node.JS v16.13.0
MQTT client v4.3.10

For EMQ X 4.3 or newer, please provide the log archive generated by [node_dump tool](https://github.com/emqx/emqx/blob/master/bin/node_dump) 

- EMQ X version (e.g. `emqx_ctl status`):  4.3.10
- Hardware configuration (e.g. `lscpu`): Intel
- OS (e.g. `cat /etc/os-release`): MacOS 12.1
- Kernel (e.g. `uname -a`): Darwin Seksit 21.2.0 Darwin Kernel Version 21.2.0: Sun Nov 28 20:28:54 PST 2021; root:xnu-8019.61.5~1/RELEASE_X86_64 x86_64
- Erlang/OTP version (in case you build emqx from source code): 
- Others:

### Steps to reproduce
Using Node.JS application with MQTT client [https://www.npmjs.com/package/mqtt#example](url), try to CONNECT to EMQX on the local server with KEEPALIVE with some seconds (i.e. 30seconds) 

### Expected behaviour
MQTT client successful connect to EMQX

### Actual behaviour
Loop to try connect to EMQX i.e. Connecting, Failed(Offline), Close, Reconnect
NOTE: IF REMOVE KEEPALIVE option, connection is successfully

Missing log file can delay the handling of the issue.

**Comment by HJianBo** [comment]
It looks like it's just the client-side errors. Does the problem still exist? If so, you can paste your sample code to facilitate our reproduction of the issue
