### ISSUE TITLE
Feature Request: Unsubscribe hooks following client disconnected

### ISSUE THREAD

**Issue by hiimdoublej-swag** [emqx/emqx#6548]
**What would you like to be added/modified**:

A toggle that when it's turned on, the broker will send `session.unsubscribed` webhooks/hooks following a `client.disconnected` trigger.

**Why is this needed**:

This will be very helpful for people that need to track per-topic member presence. With this feature, people who are interested in topic presence status (occupied/empty) can store it themselves. I don't think there's a possible way to have this right now.

Long term speaking, topic event hooks (`topic.occupied`, `topic.vacant`) actually fits this scenario better, but the suggested option here would do just fine.

**Comment by HJianBo** [comment]
That sounds like a good feature. thanks for your feedback!!
We will discuss this feature and its possible implementation. You may have to wait a while for the feature to be implemented and released.

**Comment by hiimdoublej-swag** [comment]
Well, as things stand now, my organization has given up on using EMQX, therefore I'm closing this. If anyone else needs this then please open another one, thanks for everything.
