### ISSUE TITLE
Reproducible bug: emqx_ctl retainer topics error: badarg

### ISSUE THREAD

**Issue by willww64** [emqx/emqx#6559]
### Subject of the issue
`emqx_ctl retainer topics` always output `error: badarg`

This issue is same as #6317 , but I provide a reproducible docker-compose.yml and scripts. 

### Your environment

For EMQ X 4.3 or newer, please provide the log archive generated by [node_dump tool](https://github.com/emqx/emqx/blob/master/bin/node_dump) 

[node_dump_20211228_084203.tar.gz](https://github.com/emqx/emqx/files/7783782/node_dump_20211228_084203.tar.gz)

- EMQ X version (e.g. `emqx_ctl status`): 4.3.11
- Hardware configuration (e.g. `lscpu`): amd64
- OS (e.g. `cat /etc/os-release`): archlinux
- Kernel (e.g. `uname -a`): 5.15.11-arch2-1
- Erlang/OTP version (in case you build emqx from source code): 
- Others:

### Steps to reproduce
https://github.com/willww64/emqx-ctl-retainer-topics-badarg.git

Clone this project, see README.md for details.

Prerequisite: docker / docker-compose / bash

Run:

```
./reproduce.sh
```

Output:

```
......
RPC to emqx@192.168.135.3 error: badarg
```

### Expected behaviour
show topics that contain retained messages

### Actual behaviour
RPC to emqx@192.168.135.3 error: badarg

**Comment by k32** [comment]
Could you specify the version here explicitly (e.g. emqx/emqx:4.3.11):
https://github.com/willww64/emqx-ctl-retainer-topics-badarg/blob/master/docker-compose.yml#L5

**Comment by willww64** [comment]
> Could you specify the version here explicitly (e.g. emqx/emqx:4.3.11): https://github.com/willww64/emqx-ctl-retainer-topics-badarg/blob/master/docker-compose.yml#L5

I've updated my code and rerun the reproduce script, results are same.

**Comment by k32** [comment]
Thanks, I can confirm the bug. The following error message can be seen in the logs:
```
2021-12-29T14:58:48.984929+00:00 [error] [Ctl] CMD Error:badarg, Stacktrace:[{io_lib,format,["~s~n",[['',<<"haha">>]]],[{file,"io_lib.erl"},{line,187}]},{emqx_ctl,format,2,[{file,"emqx_ctl.erl"},{line,160}]},{emqx_ctl,print,2,[{file,"emqx_ctl.erl"},{line,144}]},{lists,foreach,2,[{file,"lists.erl"},{line,1342}]},{emqx_ctl,run_command,2,[{file,"emqx_ctl.erl"},{line,105}]},{erpc,execute_call,4,[{file,"erpc.erl"},{line,416}]}]
```

**Comment by k32** [comment]
Thanks for an elaborate reproduction instruction, the fix is underway.

**Comment by k32** [comment]
Fixed on 4. branch. The implementation on the 5.0 is different, so it is not affected by this bug.
