### ISSUE TITLE
Push Notification Service (APNS/GCM) With emqttd 

### ISSUE THREAD

**Issue by prakashr87** [emqx/emqx#656]
Hi,
            Actually we are using emqtt (Erlang) as MQTT Broker and Java for Push Notification Service (APNS/GCM). So now we are planning to change Push Notification Service from Java to Erlang. Is there any possibility (like plugin)  to use Push Notification Service with Emqtt(Erlang) ?

**Comment by prakashr87** [comment]
Hi,
     Waiting for the reply...
Thanks.

**Comment by roytan883** [comment]
[how to hook publish to clientID(session) ?](https://github.com/emqtt/emqttd/issues/650)

for APNS， need  a hook before(or after) push to client session. Then if the clientID is "ios-xxxx", just push it to APNS server by other skill nodejs or java.

GCM can be the same
