### ISSUE TITLE
Failed to config forwarding engine (by sql) in dockerfile

### ISSUE THREAD

**Issue by zhengguoxin** [emqx/emqx#6681]
### Subject of the support
when i execute to build a emqx dockerfile with a forwarding engine:
![image](https://user-images.githubusercontent.com/24664658/148669437-5b66428b-037d-400b-a21b-b789135b11ec.png)

But always prompt failure:
![image](https://user-images.githubusercontent.com/24664658/148669495-3fcd0279-2936-47f4-a7b8-d8ac8adfddae.png)

Please help give advice,thx!!!

### Your environment
docker emqx/emqx:4.3.11

**Comment by zmstone** [comment]
Hi.

The new CMD replaces https://github.com/emqx/emqx/blob/6d12bb8e1744d6b8faacba0e4792436037085387/deploy/docker/Dockerfile#L68

it’s not possible to run emqx_ctl before emqx is started.
If you are to add more boot steps, maybe do it in another script and run it from here https://github.com/emqx/emqx/blob/6d12bb8e1744d6b8faacba0e4792436037085387/deploy/docker/docker-entrypoint.sh#L66
The script can be for example:

```
#!/usr/bin/env bash 
# start in daemon mode
emqx start
emqx_ctl …
# do not exit
while true; do sleep; done
```

**Comment by zhengguoxin** [comment]
done! thank you !
