### ISSUE TITLE
Session List extraction

### ISSUE THREAD

**Issue by jrupani** [emqx/emqx#674]
I have been trying to extract the active sessions using the session list command. From broker stats, I can see that the session count is close to 200k. But the session list command fails to print all the session and throws an error after listing around 60-70k sessions only. The error is - [ RPC to emqttd@127.0.0.1 failed: timeout]. I need to get the session list in order to extract the number of ready messages in the queues to analyse their distribution.

**Comment by jrupani** [comment]
@emqplus @huangdan Hi, I am using the broker on our production server and need to monitor the number of messages in user queues. It is quite urgent and I would appreciate if you could help me out.

**Comment by Gilbert-Wong** [comment]
There is no queue like what in rabbitmq in emqx, maybe you want to record the number of messages for each subscriber?
