### ISSUE TITLE
Using the emqx_auth_mysql plugin does not have the desired effect

### ISSUE THREAD

**Issue by ArcherTrister** [emqx/emqx#6750]
### Subject of the issue
Describe your issue here.
Use the emqx_auth_mysql plugin and use the default config, the connection is successful when connecting to mqtt without entering a username and password.
### Your environment

For EMQ X 4.3 or newer, please provide the log archive generated by [node_dump tool](https://github.com/emqx/emqx/blob/master/bin/node_dump) 

- EMQ X version (e.g. `emqx_ctl status`): 4.3.11
- Hardware configuration (e.g. `lscpu`):I9
- OS (e.g. `cat /etc/os-release`):win10
- Kernel (e.g. `uname -a`):
- Erlang/OTP version (in case you build emqx from source code): 
- Others:

### Steps to reproduce
Tell us how to reproduce this issue. 
① Use the emqx_auth_mysql plugin and use the default config
② Connecting to mqtt without entering a username and password.
### Expected behaviour
Tell us what should happen
Auth failed

### Actual behaviour
Tell us what happens instead
Auth succeeded
Missing log file can delay the handling of the issue.

**Comment by HJianBo** [comment]
Hi, Pls provide the `emqx.conf` and `emqx_auth_myslq.conf`

**Comment by ArcherTrister** [comment]
> Hi, Pls provide the `emqx.conf` and `emqx_auth_myslq.conf`

I use the default configuration

**Comment by zmstone** [comment]
allow_anonymous should be set to false

**Comment by ArcherTrister** [comment]
> allow_anonymous should be set to false

thank you
