### ISSUE TITLE
ARM64 can not bridge with TLS

### ISSUE THREAD

**Issue by duongxinh2003** [emqx/emqx#6751]
### Support bridge MQTT Broker in ARM64 architecture
Hi, when I set up the bridge from the arm64 chipset, it failed to bridge.

Error/Warning printout if any. 

### Your environment

For EMQ X 4.3 or newer, please provide the log archive generated by [node_dump tool](https://github.com/emqx/emqx/blob/master/bin/node_dump) 

Otherwise please provide below info:
- EMQ X version (e.g. `emqx_ctl status`): 4.3.11
- If cluster (e.g. 3 X 4Core16GB): 1 x 1 core 2gb
- Hardware configuration (e.g. `lscpu`): aarch64
- OS (e.g. `cat /etc/os-release`): Debian 9
- Kernel (e.g. `uname -a`): Linux 4.9.0-14-arm64 `#1` SMP Debian 4.9.240-2 (2020-10-30) aarch64 GNU/Linux
- Erlang/OTP version (in case you build emqx from source code): 23.2.7.2-emqx-3/11.1.8
- Others:

### LOG File
`2022-01-14T05:21:18.585822+00:00 [error] [Bridge Connect] Failed to connect with module=emqx_bridge_mqtt, config=[{username,"user"},{subscriptions,[]},{start_type,manual},{ssl_opts,[{versions,['tlsv1.3','tlsv1.2','tlsv1.1',tlsv1]},{keyfile,"/etc/emqx/certs/client-key.pem"},{ciphers,["TLS_AES_256_GCM_SHA384","TLS_AES_128_GCM_SHA256","TLS_CHACHA20_POLY1305_SHA256","TLS_AES_128_CCM_SHA256","TLS_AES_128_CCM_8_SHA256","ECDHE-ECDSA-AES256-GCM-SHA384","ECDHE-RSA-AES256-GCM-SHA384","ECDHE-ECDSA-AES256-SHA384","ECDHE-RSA-AES256-SHA384","ECDHE-ECDSA-DES-CBC3-SHA","ECDH-ECDSA-AES256-GCM-SHA384","ECDH-RSA-AES256-GCM-SHA384","ECDH-ECDSA-AES256-SHA384","ECDH-RSA-AES256-SHA384","DHE-DSS-AES256-GCM-SHA384","DHE-DSS-AES256-SHA256","AES256-GCM-SHA384","AES256-SHA256","ECDHE-ECDSA-AES128-GCM-SHA256","ECDHE-RSA-AES128-GCM-SHA256","ECDHE-ECDSA-AES128-SHA256","ECDHE-RSA-AES128-SHA256","ECDH-ECDSA-AES128-GCM-SHA256","ECDH-RSA-AES128-GCM-SHA256","ECDH-ECDSA-AES128-SHA256","ECDH-RSA-AES128-SHA256","DHE-DSS-AES128-GCM-SHA256","DHE-DSS-AES128-SHA256","AES128-GCM-SHA256","AES128-SHA256","ECDHE-ECDSA-AES256-SHA","ECDHE-RSA-AES256-SHA","DHE-DSS-AES256-SHA","ECDH-ECDSA-AES256-SHA","ECDH-RSA-AES256-SHA","AES256-SHA","ECDHE-ECDSA-AES128-SHA","ECDHE-RSA-AES128-SHA","DHE-DSS-AES128-SHA","ECDH-ECDSA-AES128-SHA","ECDH-RSA-AES128-SHA","AES128-SHA"]},{certfile,"/etc/emqx/certs/client-cert.pem"},{cacertfile,"/etc/emqx/certs/cacert.pem"}]},{ssl,true},{retry_interval,20},{proto_ver,v4},{password,'***'},{max_inflight,32},{keepalive,60},{forward_mountpoint,"bridge/aws/${node}/"},{clientid,"bridge_aws"},{clean_start,true},{bridge_mode,true},{batch_size,32},{address,"x.x.x.x:8883"}], reason:{options,{insufficient_crypto_support,{'tlsv1.3',{versions,['tlsv1.3','tlsv1.2','tlsv1.1',tlsv1]}}}}`

**Comment by qzhuyan** [comment]
Could pls check your libssl version on your OS. to support tlsv1.3, we need openssl1.1

**Comment by duongxinh2003** [comment]
> Could you pls check your libssl version on your OS. to support tlsv1.3, we need openssl1.1
This is my OpenSSL version:
`OpenSSL 1.1.0l  10 Sep 2019`

**Comment by zmstone** [comment]
the error `insufficient_crypto_support` unfortunately is not very helpful.
I had a quick look into Erlang/OTP source code, it seems your OpenSSL version does not provide all default ciphers required by EMQ X. But I'm not sure which one(s) exactly.
For best security, please upgrade to openssl 1.1.1
Otherwise you can remove tlsv1.3 and these ciphers from EMQ X config. `"TLS_AES_256_GCM_SHA384","TLS_AES_128_GCM_SHA256","TLS_CHACHA20_POLY1305_SHA256","TLS_AES_128_CCM_SHA256","TLS_AES_128_CCM_8_SHA256",`

**Comment by duongxinh2003** [comment]
Thank @zmstone . I just upgraded OpenSSL to 1.1.1l and it works normally!
