### ISSUE TITLE
Is it possible to add the `connected_at` field for WebHook event notification

### ISSUE THREAD

**Issue by HJianBo** [emqx/emqx#6765]
你好，请问有没有可能在webhook插件实现中的clien离线返回中加入ConnInfo中connected_at字段？我看了一下代码似乎是可行的。
https://github.com/emqx/emqx/blob/main-v4.3/apps/emqx_web_hook/src/emqx_web_hook.erl#L139

这样业务侧在接收到离线回调时就可以辨明这个连接曾经建立的时间，这样就是可以作为一个连接session区分的手段，业务侧就可以以此来过滤状态不一致带来的问题。

---
Hi, is it possible to add the connected_at field in ConnInfo to the clien offline return in the webhook plugin implementation? I've looked at the code and it seems to work.
https://github.com/emqx/emqx/blob/main-v4.3/apps/emqx_web_hook/src/emqx_web_hook.erl#L139

This way the business side can identify when the connection was established when receiving the offline callback, so that it can be used as a means of connection session differentiation, and the business side can use this to filter the problems caused by inconsistent state.

_Originally posted by @DOGTT in https://github.com/emqx/emqx/issues/6453#issuecomment-1014277227_

**Comment by HJianBo** [comment]
Hi @DOGTT It does seem like an optimization that could be added. Thanks for your feedback!

**Comment by DOGTT** [comment]
thanks,this will be very helpful~
