### ISSUE TITLE
Getting Generic server SSL error in emqx 

### ISSUE THREAD

**Issue by VaibhavMishra2069** [emqx/emqx#6784]
We are getting below error in emqx logs every 5-10 seconds.

[error] Generic server <0.2030.0> terminating. Reason: {unhandled_message,{ssl_closed,{sslsocket,{gen_tcp,#Port<0.27>,tls_connection,undefined},[<0.2032.0>,<0.2031.0>]}}}. Last message: {ssl_closed,{sslsocket,{gen_tcp,#Port<0.27>,tls_connection,undefined},[<0.2032.0>,<0.2031.0>]}}. State: {state,"<redis host>",6380,<<"redis password">>,<<"0">>,undefined,3000,5000,{sslsocket,{gen_tcp,#Port<0.27>,tls_connection,undefined},[<0.2032.0>,<0.2031.0>]},{pstate,undefined,undefined},{[],[]}}.

Version of emqx: 4.3.10
Redis-- Azure Cache redis(With cluster enabled)

Note: we are using emqx_auth_redis to authenticate the clients

**Comment by k32** [comment]
Hello,
1. Could you provide more logs surrounding the error message? 
2. Does client authentication work despite the error messages? 
3. What is the rate of clients connecting and disconnecting, i.e. how often does the broker make requests towards redis?

**Comment by Keshavgoyal788** [comment]
I am also facing the same issue with emqx logs while using emqx_auth_redis. Please provide some help in same.

**Comment by zmstone** [comment]
It looks like Redis server closed the ssl connection.
we can perhaps improve the logging

**Comment by Aravindms369** [comment]
I am also facing the same issue while using emqx_auth_redis. As part of the latest azure update, we have also updated the CA cert(DigiCert Global Root G2 root certificate) for redis cache. Still, we are getting the SSL connection error.

Version of emqx: 4.3.10
Redis-- Azure Cache redis(With cluster enabled)

@k32 
1. Could you provide more logs surrounding the error message?
**Answer:**

[error] crasher: initial call: eredis_client:init/1 registered_name: [], exit: {{unhandled_message,{ssl_closed,{sslsocket,{gen_tcp,tls_connection,undefined},},[{gen_server,handle_common_reply,8,[{file,"gen_server.erl"},{line,805}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,226}]}]}, eredis_cluster_pool,eredis_cluster_sup,], message_queue_len: 0, messages: [], links: [], dictionary: [{options,[{ssl_options,[{cacertfile,"ca-cert-DigiCert_Global_Root_G2.pem"{verify,verify_none}]}]},{transport,ssl}], trap_exit: false, status: running, heap_size: 6772, stack_size: 28, reductions: 25158; neighbours:

2. Does client authentication work despite the error messages?
**Answer**

Yes. all client operations are working fine even though we are getting this error.

Please provide some help in same.

**Comment by zmstone** [comment]
@Aravindms369 thank you for sharing the logs.
We’ll try to fix it in the next release

**Comment by Aravindms369** [comment]
Thanks @zmstone 
Can you please also consider the suggestion that this should not be error logs if the connection is closed?

**Comment by zmstone** [comment]
@Aravindms369 
This is a bug in the redis client, after the fix, there will be no such crashes, nothing to log either.

**Comment by zmstone** [comment]
This is not done until the dependency is updated in this repo.

**Comment by Aravindms369** [comment]
Hi @zmstone

With the latest release of emqx(4.4.3) also I am still facing the Generic server terminating issue and eredis client ssl error which is mentioned in the above comments.

Please provide some help in the same.

**Comment by zmstone** [comment]
sorry. The dependency had a new version released, but not updated to emqx.

**Comment by gsychev** [comment]
@Aravindms369 , Hi!
Please, try the `v4.4.4`

**Comment by Aravindms369** [comment]
@zmstone Do we have any other stable version in which this issue is fixed?

**Comment by zmstone** [comment]
@Aravindms369 this is unrelated to the issue you are seeing.
