### ISSUE TITLE
emqx_cluster_rpc retry should be handled in emqx_resource

### ISSUE THREAD

**Issue by k32** [emqx/emqx#6817]
_Originally posted by @qzhuyan in https://github.com/emqx/emqx/pull/6809#discussion_r788518469_

**Comment by zmstone** [comment]
the latest version does not call `emqx_resource:create` directly any more.
all resource creation are wrapped by higher level implementations such as `emqx_bridge` or `emqx_connector`, 
which calls into create_local, then the retry is performed by cluster_rpc catch-up mechanism in other nodes.
