### ISSUE TITLE
Windows: EMQX crash in crypto.dll 

### ISSUE THREAD

**Issue by michaelcplusplus** [emqx/emqx#6853]
### Subject of the issue
EMQX broker does not start on Microsoft Windows Server 2019 Datacenter.
The crash is caused by OpenSSL 1.0.2d

Further information by intel:
https://www.intel.com/content/www/us/en/developer/articles/troubleshooting/openssl-sha-crash-bug-requires-application-update.html
OpenSSL* 1.0.2 beta (Jun 2014) to OpenSSL 1.0.2k (Jan 2017) contain bugs that either cause a crash or bad SHA (Secure Hash Algorithm) values on processors with the SHA extensions, such as the recently released 10th Generation processor. 

**Workaround:**
OpenSSL provides an environment variable control for enabling features, including one that modifies the Intel® CPU identification, OPENSSL_ia32cap:
`set OPENSSL_ia32cap=:~0x20000000`

### Your environment

- EMQ X version (e.g. `emqx_ctl status`): 4.2.12
- OS (e.g. `cat /etc/os-release`): Microsoft Windows Server 2019 Datacenter
- Others: Processortype
![image](https://user-images.githubusercontent.com/24432169/150950797-9612030d-68ab-4504-ae49-f75b3ab377c4.png)

-

### Steps to reproduce
Start erlang 
`"erts-10.4\bin\erl.exe"  -boot **"releases\4.2.12\start_clean"`
`1> crypto:hash(sha, <<"hello">>).`

Crash in Erlang VM.

Faulting application name: erl.exe, version: 0.0.0.0, time stamp: 0x5ebb20c5
Faulting module name: crypto.dll, version: 0.0.0.0, time stamp: 0x5ebb2227
Exception code: 0xc0000005
Fault offset: 0x0000000000019063
Faulting process id: 0x19bc
Faulting application start time: 0x01d80eb92cf132ff
Faulting application path: C:\emqx\erts-10.4\bin\erl.exe
Faulting module path: c:\emqx\lib\crypto-4.5\priv\lib\crypto.dll
Report Id: c9545485-b58b-43b2-8721-833c132e050e
Faulting package full name: 
Faulting package-relative application ID:

Exception code: 0xc0000005 Access violation error.

**Comment by zmstone** [comment]
Hi @michaelcplusplus 
EMQ X 4.2 community edition is out of maintenance window.
could you maybe try EMQ X 4.3 ?

**Comment by michaelcplusplus** [comment]
EMQ X 4.3: the same problem. The crypto library in EMQ X 4.3 hast the same version:
```
"erts-11.0\bin\erl.exe"  -boot "releases\4.3.11\start_clean"
Eshell V11.0  (abort with ^G)
1> crypto:info_lib().
[{<<"OpenSSL">>,268443727,<<"OpenSSL 1.0.2d 9 Jul 2015">>}]
```


```
Event log  :
Faulting application name: erl.exe, version: 0.0.0.0, time stamp: 0x5ebb20c5
Faulting module name: crypto.dll, version: 0.0.0.0, time stamp: 0x5ebb2227
Exception code: 0xc0000005
Fault offset: 0x0000000000019063
Faulting process id: 0x19bc
Faulting application start time: 0x01d80eb92cf132ff
Faulting application path: C:\Temp\emqx-windows-4.3.11\emqx\erts-11.0\bin\erl.exe
Faulting module path: c:\Temp\emqx-windows-4.3.11\emqx\lib\crypto-4.7\priv\lib\crypto.dll
Report Id: c9545485-b58b-43b2-8721-833c132e050e
Faulting package full name: 
Faulting package-relative application ID:

Exception code: 0xc0000005 Access violation error. 

```

**Comment by zmstone** [comment]
Hi @michaelcplusplus 
The crypto.dll is from the pre-built Erlang in github CI action.
Will see if we can find a newer Erlang.

**Comment by michaelcplusplus** [comment]
The workaround with the environment variable also solves the problem.
`set OPENSSL_ia32cap=:~0x20000000`
Therefore there is no hurry.

**Comment by zmstone** [comment]
we have upgraded to 23.3.4.13 for windows build in github.
i believe this issues is resolved.

**Comment by peng362860648** [comment]
thanks,Your answer solves my problem

**Comment by DominicBortmes** [comment]
the env var workaround also works for an even older eqmx version with 3.1.2. It uses the exact same openssl version OpenSSL 1.0.2d 9 Jul 2015
