### ISSUE TITLE
Invalidation of JWT tokens prior to expiration

### ISSUE THREAD

**Issue by haimiko** [emqx/emqx#6858]
**What would you like to be added/modified**:
Ability to invalidate JWT token before expiration without having to change global JWT secret.  One possible implementation would be possibly to tie in the JWT auth into the MYSQL auth allowing JWT to query if the encoded username could be used as a tokenid in MYSQL .
Possibly something like  this:
`auth.mysql.auth_query = select username from jwttokens where tokenid = '%u' limit 1`

**Why is this needed**:
Rather than set short expirations on JWT tokens we could simply delete token ids from the database thus allowing more control over tokens.

**Comment by zmstone** [comment]
it's possible to enable more than one auth plugins.
maybe enable auth-mysql in addition to auth-jwt.

**Comment by haimiko** [comment]
I've thought of that as well, only I'm unsure how to tie in the jwt username verification into the mysql auth plugin.   I will experiment .

**Comment by zmstone** [comment]
you can use auth-mysql as a blacklist.
return a bad password for blacklisted users (token revoked).
for the ones that are not blacklisted, they will continue to auth-jwt.

however, this relies on the auth-mysql plugin is booted earlier than auth-jwt.
and once it restarted, it will be positioned behind auth-jwt.
--- i.e. there is no deterministic order for auth plugins in 4.x.
