### ISSUE TITLE
EMQ Cluster start order issue

### ISSUE THREAD

**Issue by Easonme** [emqx/emqx#694]
Problem description:
The test environment is composed of  two nodes:
version:emqttd-centos64-1.1.2-beta-20160630
NodeA: node name: emqttd@192.168.20.137
NodeB: node name: emqttd@192.168.20.138
Clusted by: ./bin/emqttd_ctl cluster join emqttd@192.168.20.138

When the cluster environment is completed, then  I stop two nodes (all nodes are down to simulate the situation)
Then I started to recover,I start emqttd on A node .but the emqtt service on  port 1883 can not normally listen to and provide services.
when the B node is started, and then start the emqtt on the A . This time the emqtt service on node A start normally.

so i have questions:
Does the emqttd cluster node have a master or slave relationship or role definition, so that it will affect the sequence of the cluster to start?

**Comment by Gilbert-Wong** [comment]
So sorry for so late response. Yes, I have checked this issue and reproduced this problem, we would fix it in emqx3.1 release.

**Comment by Gilbert-Wong** [comment]
It has been fixed in emqx3.1 beta1.
