### ISSUE TITLE
Client disconnected by emqx in 2 hours

### ISSUE THREAD

**Issue by ourdark** [emqx/emqx#7013]
### Subject of the issue
I have same situation here, client auto disconnected after 2 hours around.
I am using docker emqx latest version(4.3.11), and **zone.external.session_expiry_interval = 365d**

### Your environment

For EMQ X 4.3 or newer, please provide the log archive generated by [node_dump tool](https://github.com/emqx/emqx/blob/master/bin/node_dump) 

- EMQ X version (e.g. `emqx_ctl status`): Node 'xxx@xxx' 4.3.8 is started
- Hardware configuration (e.g. `lscpu`): 
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                4
On-line CPU(s) list:   0-3
Thread(s) per core:    1
Core(s) per socket:    4
Socket(s):             1
NUMA node(s):          1
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 85
Model name:            Intel(R) Xeon(R) Silver 4216 CPU @ 2.10GHz
Stepping:              7
CPU MHz:               2095.075
BogoMIPS:              4190.15
Hypervisor vendor:     Microsoft
Virtualization type:   full
L1d cache:             32K
L1i cache:             32K
L2 cache:              1024K
L3 cache:              22528K
NUMA node0 CPU(s):     0-3
Flags:                 fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx lm constant_tsc rep_good nopl eagerfpu pni pclmulqdq ssse3 fma cx16 sse4_1 sse4_2 movbe popcnt aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch fsgsbase bmi1 hle avx2 smep bmi2 erms rtm xsaveopt
- OS (e.g. `cat /etc/os-release`):NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

- Kernel (e.g. `uname -a`):Linux xxx 3.10.0-1160.49.1.el7.x86_64 #1 SMP Tue Nov 30 15:51:32 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
- Erlang/OTP version (in case you build emqx from source code): 
- Others: Docker version 20.10.12, build e91ed57
- OS in Docker
bash-5.0$ cat /etc/os-release
NAME="Alpine Linux"
ID=alpine
VERSION_ID=3.12.8
PRETTY_NAME="Alpine Linux v3.12"
HOME_URL="https://alpinelinux.org/"
BUG_REPORT_URL="https://bugs.alpinelinux.org/"

### Steps to reproduce
Tell us how to reproduce this issue. 

### Expected behaviour
The client consumer continurious run without any interruption

### Actual behaviour
Client in disconnect state and consuming empty message

Missing log file can delay the handling of the issue.
### Logs
the cosumer log shows(garbled):

v񬏾~𾊙񁀿ÿÿÿÿÿÿÿÿÿÿ2console-consumer-9092consumerrangeEconsumer-console-consumer-9092-1-c1628a93-dfa8-495c-aa1c-664ef4cf8d06~䢯nsumer-console-consumer-9092-1-c1628a93-dfa8-495c-aa1c-664ef4cf8d06ÿÿ consumer-console-consumer-9092-1/192.168.0.228ఈhelloÿÿÿÿhelloÿÿÿÿq/}~񋛁~񋞿ÿÿÿÿÿÿÿÿÿÿÿÿÿ~2console-consumer-9092consumerÿÿÿÿ~񋚂QPy|z~򀾊򁀿ÿÿÿÿÿÿÿÿÿÿÿ>2console-consumer-9092

**Comment by qzhuyan** [comment]
what is the transport in use? what is the value to keep alive on transport layer?

**Comment by ourdark** [comment]
@qzhuyan 
I am using org.fusesource.mqtt-client JAVA version, MQTT protocol connect to 1883.
The keep alive value already set to 11s(default 15)

**Comment by HJianBo** [comment]
> zone.external.session_expiry_interval = 365d

Can you share how you configured it?

**Comment by ourdark** [comment]
> Can you share how you configured it?

current we mannualy update docker on each node.

docker exec -it emqx /bin/bash
vi /etc/emqx.conf

`## Default session expiry interval for MQTT V3.1.1 connections.
##                           
## Value: Duration
## -d: day                         
## -h: hour
## -m: minute 
## -s: second                   
##                           
## Default: 2h, 2 hours  
zone.external.session_expiry_interval = 365d
`
exit

docker restart emqx

Then the dashboard(18083) will show Expiry interval(s): 31536000(this require mqtt client set cleanSession to false)

**Comment by qzhuyan** [comment]
> Client in disconnect state and consuming empty message

 Do you mean the tcp connection is still alive and client recvied disconnect message from emqx? What do you mean on "empty message"?

Will be helpful if you could enable debug logging on emqx and upload it. 
https://www.emqx.io/docs/en/v4.3/getting-started/log.html#control-log-output

**Comment by ourdark** [comment]
@qzhuyan 
The connection is alive and emqx set it's state to "disconnected" state around 2 hours, this supose to be "connected" stated all the time. In that case org.fusesource.mqtt-client still can pull(by receive method) messages which is null.

I think it's reasonable no message/error for clients with disconnected state, I am struggling with why it's disconnected.

**Comment by ourdark** [comment]
I changed my client to https://www.emqx.io/docs/en/v4.3/development/java.html#paho-java-usage-example and test it, everything works fine for now, the client working for hours without interruption.

I do think the causal is acknowledge principles, since mqttv3 auto ack but org.fusesource.mqtt-client not. 

Guess emqx disconnected client when un-acked message to to certain degree, right?

Anyway, mqttv3 is working.

**Comment by zmstone** [comment]
hi @ourdark 
I’m glad that the issue has been resolved on your side.
However it would be great if we knew better why it disconnected when you were using the other lib.
Few things still puzzles me:
* was it a graceful disconnect (my sending MQTT disconnect packet) or was it a direct socket close?
* which side, client or broker initiated the disconnect 
* was the client sending heartbeats? What’s the interval?

With debug level log turned on, we’ll be easier to answer these questions.

Above being said, please feel free to close the issue if you don’t want to continue the investigation

**Comment by ourdark** [comment]
@zmstone 

As much as I know, 

- I would say it's not a TCP/MQTT protocol disconnect, connection in emqx "disconnected" state, that "disconnected" state is not define in MQTT 3.1 protocol. Instead, the TCP connection still alive which see on emqx dashboard(also client and client channel still working), client receive no message. 

- I didn't dig into org.fusesource.mqtt-client, could not say it's will not him on somewhat condition(possibly not). Still believe emqx broker transform "disconnected" state, that is emqx implemented feature, and set it on condition. 

We pretty sure about activities all the time, keeplive 11s, thousands of messages per-second. no one initiate a disconnect in protocol.

Would enable debug log on test env, any progress would let you know.

**Comment by ourdark** [comment]
addtional remark, as metioned above, subscriber ack every message with org.fusesource.mqtt-client, it seem works for fine. no disconnected state happens,

**Comment by ourdark** [comment]
Close issue since find a way to work out this problem.
