### ISSUE TITLE
emqtt 2.0 beta3 cannot start on service

### ISSUE THREAD

**Issue by Sephiroth-Wang** [emqx/emqx#702]
Hi team,

I try to use latest emqtt 2.0 beta3 on my windows 7, however as I use service install then start it.
It's appear "Windows cannot start the emqtt 2.0 service on Local Computer, Error 1067: The process terminated unexpectedly."

But the previous version 1.1.2 work perfectly.

**Comment by useruseri** [comment]
I have faced this problem, i will appreciate who can help us on this issue.
with regards

**Comment by domimuller** [comment]
I'm facing the same problem: emqttd starts in console mode, but not as a Windows service, neither from "services.msc" nor by calling "bin\emqttd start".

In the System Event Log, I can see the following message, which could be helpful for the knowledgeful specialist: "emqttd_2.0: Not enough parameters for erlang service."

Kind regards

**Comment by huangdan** [comment]
This version does not support win7

**Comment by seymour-bootay** [comment]
Has there been any progress on this issue or a work around?

**Comment by Gilbert-Wong** [comment]
Sorry for late response, @zhanghongtong  would help you resolve this problem.

**Comment by Gilbert-Wong** [comment]
Hi, @Sephiroth-Wang, Sorry for so late response, this issue has been resolved in emqx3.0-rc.2.
