### ISSUE TITLE
emqx broker client create，about python sdk

### ISSUE THREAD

**Issue by wttt-py** [emqx/emqx#7025]
I wrote a python script to create client and push messages.；
when I create 5000 client everything is ok~；
when I create 10000 or 15555 only 8600+；
That's why？ please check it , thanks~
![1](https://user-images.githubusercontent.com/83765757/154215987-2f32fc98-1268-4cb8-bedf-b3bd097ac1ec.png)
![2](https://user-images.githubusercontent.com/83765757/154215993-b84c5b42-d60f-4b31-b742-5bdf484c5528.png)
![3](https://user-images.githubusercontent.com/83765757/154215994-3e8e4a67-fae9-402d-b9f9-46723b2cd90b.png)
![4](https://user-images.githubusercontent.com/83765757/154215996-78f999c6-cf49-4309-ae6f-f3a117fb1127.png)

**Comment by wttt-py** [comment]
After more than 8000, it will remain at around 8600 and no longer increase

**Comment by zmstone** [comment]
likely the client has drained all available source ports.
you can create some virtual IPs to get around it.

**Comment by wttt-py** [comment]
may not this reason ， use emqtt-bench can reach the upper limit
![5](https://user-images.githubusercontent.com/83765757/154228326-2232b167-54a7-483d-8001-ebd921fec1b5.png)

**Comment by wttt-py** [comment]
> likely the client has drained all available source ports. you can create some virtual IPs to get around it.
may not this reason ， use emqtt-bench can reach the upper limit
![5](https://user-images.githubusercontent.com/83765757/154228512-1016ebc2-e997-447a-b9c2-39c328edee9b.png)

**Comment by qzhuyan** [comment]
have you checked this 
https://www.emqx.io/docs/en/v4.3/tutorial/tune.html

You need to ensure that you don't have limitaion in the OS both on the emqx and the python clients side

**Comment by wttt-py** [comment]
> have you checked this https://www.emqx.io/docs/en/v4.3/tutorial/tune.html
> 
> You need to ensure that you don't have limitaion in the OS both on the emqx and the python clients side
I have adjusted the parameters of the client and server according to the official emqx documentation, but the problem still exists，The log of emqx also has no output.
That's my script
[mqtt_push.txt](https://github.com/emqx/emqx/files/8085762/mqtt_push.txt)

**Comment by qzhuyan** [comment]
could you enable debugging on emqx and provide the logs?
https://www.emqx.io/docs/en/v4.3/getting-started/log.html

**Comment by qzhuyan** [comment]
Please also check the return values of a function call in the python script, if they return errors, you never know.

**Comment by wttt-py** [comment]
> could you enable debugging on emqx and provide the logs? https://www.emqx.io/docs/en/v4.3/getting-started/log.html


Thanks for the reminding, I adjusted the log level and some code, how can I solve the timeout problem?
![6](https://user-images.githubusercontent.com/83765757/154615495-00378883-7b0e-49d6-8928-8a69cd4fa9d7.jpg)

**Comment by qzhuyan** [comment]
glad to know it works now. close the issue now.
