### ISSUE TITLE
Not being able to change node name with EMQX_NODE__NAME 

### ISSUE THREAD

**Issue by ddcfgmv** [emqx/emqx#7029]
### Subject of the support
I am trying to implement an EMQX cluster in multicast mode, but i would like to set the node names with the environment variable EMQX_NODE_NAME rather than with the config files. So i do the following:

export EMQX_NODE_NAME=emqx@127.0.0.2
systemctl restart emqx.service

But if i check the status of that service:
systemctl status emqx.service

It shows that the node is taking the default node.name from the config file:

feb 16 10:15:21 debian8 systemd[1]: Started EMQ X Broker.
feb 16 10:15:24 debian8 emqx[11264]: Exec: /usr/lib/emqx/erts-10.5.2/bin/erlexec -noshell -noinput +Bd -boot /usr/lib/emqx/releases/v4.0.7/emqx -mode embedded -boot_var ERTS_LIB_DIR /usr/lib/emqx/erts-10...
feb 16 10:15:24 debian8 emqx[11264]: Root: /usr/lib/emqx
feb 16 10:15:25 debian8 emqx[11264]: **Starting emqx on node emqx@127.0.0.1**
feb 16 10:15:25 debian8 emqx[11264]: Start http:management listener on 8081 successfully.
feb 16 10:15:25 debian8 emqx[11264]: Start http:dashboard listener on 18083 successfully.
feb 16 10:15:25 debian8 emqx[11264]: Start mqtt:tcp listener on 127.0.0.1:11883 successfully.
feb 16 10:15:25 debian8 emqx[11264]: Start mqtt:tcp listener on 0.0.0.0:1883 successfully.
feb 16 10:15:25 debian8 emqx[11264]: Start mqtt:ssl listener on 0.0.0.0:8883 successfully.
feb 16 10:15:25 debian8 emqx[11264]: EMQ X Broker 4.0.7 is running now!

And if i check with emqx_ctl status it says that the node (as defined in the environment var) is not responding to pings.

I have also tried to comment the node.name line in the config file, but then it is not able to start the service.

### Your environment

For EMQ X 4.3 or newer, please provide the log archive generated by [node_dump tool](https://github.com/emqx/emqx/blob/master/bin/node_dump) 

Otherwise please provide below info:
- EMQ X version (e.g. `emqx_ctl status`): 4.0.7
- OS (e.g. `cat /etc/os-release`): Debian 8
- Kernel (e.g. `uname -a`): Linux debian8 3.16.0-6-amd64 #1 SMP Debian 3.16.56-1+deb8u1 (2018-05-08) x86_64 GNU/Linux

**Comment by thalesmg** [comment]
Hi @ddcfgmv !

`EMQX_NODE_NAME` is config present in 4.3.  EMQX version 4.0.7 is quite old and unsupported by now, and it has some incompatible changes in config compared to 4.3.  Could you try to upgrade to the latest (4.3.12) and apply the configuration again?

For reference: https://www.emqx.io/docs/en/v4.3/configuration/configuration.html#node-name

**Comment by thalesmg** [comment]
Also, please note that the systemd service unit won't inherit the environment variables from your session (set by `export XXX`).

You'll need to edit `/etc/emqx/emqx.conf` and add your custom configs, such as the node name, there.

**Comment by ddcfgmv** [comment]
Hi @thalesmg,
Thanks for answering. I will check if i can upgrade to the latest version. But wouldn't there be a way to configure these names without having to modify the configuration files for each machine?

**Comment by thalesmg** [comment]
If the `emqx` executable were to be invoke directly, then it should pick up environment variables from your user's session.  Like so:

```sh
env EMQX_NODE_NAME=mynode@myhost emqx console
```

But systemd does not inherit the environment of the user invoking `start/stop/restart`, so the only option is to set the configuration files for each machine, unfortunately.

**Comment by ddcfgmv** [comment]
Ok! i will check it. Very thankful

**Comment by thalesmg** [comment]
Also, note that setting the node name in an environment variable will not persist between server/node restarts.  You'll need the configuration to persist that.

If you just want to make a quick one-off test in your node, then directly starting EMQX should work with the environment variable approach.

For example:

```sh
systemctl stop emqx
env EMQX_NODE_NAME=mynode@myhost emqx console
```

Feel free to open another issue if you encounter other problems.  :slightly_smiling_face:
