### ISSUE TITLE
Error: INSTALLATION FAILED: template: emqx/templates/configmap.env.yaml:14:9: executing "emqx/templates/configmap.env.yaml" at <ne $value nil>: error calling ne: incompatible types for comparison

### ISSUE THREAD

**Issue by east4ming** [emqx/emqx#7070]
Helm install emqx 4.4.0, then:
Error: INSTALLATION FAILED: template: emqx/templates/configmap.env.yaml:14:9: executing "emqx/templates/configmap.env.yaml" at <ne $value nil>: error calling ne: incompatible types for comparison

### Subject of the issue
Error: INSTALLATION FAILED: template: emqx/templates/configmap.env.yaml:14:9: executing "emqx/templates/configmap.env.yaml" at <ne $value nil>: error calling ne: incompatible types for comparison

### Your environment

- k8s 1.21.7
- helm 3

### Steps to reproduce
```bash
> helm repo add emqx https://repos.emqx.io/charts
"emqx" has been added to your repositories
> helm install emqx emqx/emqx --namespace emqx --wait
Error: INSTALLATION FAILED: template: emqx/templates/configmap.env.yaml:14:9: executing "emqx/templates/configmap.env.yaml" at <ne $value nil>: error calling ne: incompatible types for comparison
```

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

Missing log file can delay the handling of the issue.

**Comment by joggeli34** [comment]
Why is this issue closed? Did you find a solution to that? I'm still getting this error with the chart 4.4.1

**Comment by MLStoltzenburg** [comment]
Same problem with me.
I'm trying version 4.4.1.

Error: INSTALLATION FAILED: template: emqx/templates/configmap.env.yaml:14:9: executing "emqx/templates/configmap.env.yaml" at <ne $value nil>: error calling ne: incompatible types for comparison
