### ISSUE TITLE
emqx charts  is unavalible

### ISSUE THREAD

**Issue by qinrong** [emqx/emqx#7100]
### Subject of the issue
helm install my-emqx emqx/emqx
[ERROR] templates/: parse error at (emqx/templates/StatefulSet.yaml:1): unclosed action

### Your environment
v1.23.3+k3s1
ubuntu: Linux test-s-04 5.4.0-99-generic #112-Ubuntu SMP Thu Feb 3 13:50:55 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

**Comment by qzhuyan** [comment]
Which helm chart do you use?

**Comment by qinrong** [comment]
https://repos.emqx.io/charts

**Comment by qzhuyan** [comment]
Are you running with helm3?  Which helm version do you use?
I could not reproduce the same error locally, could you provide the command line outputs?

Would be good if you could run with `--debug` so that we could get more insights.

**Comment by qinrong** [comment]
Error: UPGRADE FAILED: error validating "": error validating data: ValidationError(StatefulSet.spec.template.spec.volumes[3]): unknown field "hostpath" in io.k8s.api.core.v1.Volume




Emqx do not support hostpath?
| |
覃蓉
|
|
***@***.***
|




On 02/27/2022 04:42，William ***@***.***> wrote：

Are you running with helm3? Which helm version do you use?
I could not reproduce the same error locally, could you provide the command line outputs?

Would be good if you could run with --debug so that we could get more insights.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by qzhuyan** [comment]
@qinrong 

You need to check with your system admin about the `hostpath` volume support in your Kubernates cluster. There is not much we could do for this.

Since this is out of domain of emqx, I close the ticket now.
