### ISSUE TITLE
Difference between the 2 Debian10 installer version of EMQX 5.0 Beta3?

### ISSUE THREAD

**Issue by jayjupdhig** [emqx/emqx#7105]
Hi there

I heard that the GUI of EMQX Beta 5.0 has now the functionality not just to CREATE USERS - is has now also the feature to configure THEIR PERMISSIONS. (?)

- What's the difference between 'emqx-5.0-beta.3-otp24.1.5-3-debian10-amd64.deb' and 'emqx-edge-5.0-beta.3-otp24.1.5-3-debian10-amd64.deb' ?

- Is one of that 2 installers above also compatible to Debian 11.x (instead of Debian 10.x) ?
  -> When i remember right: Earlier installations of your stable 4.x versions are also "officially" only supported on Debian 10 - but it was also working on Debian 11. How is that with Beta 5.0 versions?

- Is that Beta 5.0 version a trial of the commercial or of "community" edition? On the "release" section of your GitHub site, i can only read the word "Community" on stable / released 4.x versions. (?) 

Thank you very much for your feedback(s).

Kind regards from Switzerland,
Jan

**Comment by jayjupdhig** [comment]
OH - now i saw that there are 3 different kinds of EMQX:

1.) Edge (seems to be a "minimal" version)
2.) OpenSource -> emqx-5.0-beta.3-otp24.1.5-3-debian10-amd64.deb must be the right one in my case?
3.) "Enterprise" (=commercial closed-source version)

Until now, i was successful with installation on current Debian 11.x version with 'dpki -i emqx-5.0-beta.3-otp24.1.5-3-debian10-amd64.deb'... service works too when i look on it with "service emqx status" (or the "systemctl" equivalent)

If i'm right, the issue may be closed... :-)

**Comment by thalesmg** [comment]
Hi @jayjupdhig !

It is as you have noticed: the edge version is slightly smaller (with fewer dependencies included) and the enterprise is currently closed source, but will be brought gradually to this repository under [BSL](https://github.com/emqx/emqx/blob/f173a2f61fee0ed5db8be28b26352cccbdba865d/lib-ee/BSL.txt).

Since you apparently want to try EMQX out, the Community version is the right one for you.  Glad that the Debian 10 version is working for you, but we have not tested nor built it against Debian 11.

If you face problems while trying it out, please feel free to open another issue.  :slightly_smiling_face:

**Comment by thalesmg** [comment]
Hi @jayjupdhig !

It is as you have noticed: the edge version is slightly smaller (with fewer dependencies included) and the enterprise is currently closed source.

Since you apparently want to try EMQX out, the Community version is the right one for you. Glad that the Debian 10 version is working for you, but we have not tested nor built it against Debian 11.

If you face problems while trying it out, please feel free to open another issue. :slightly_smiling_face:

**Comment by jayjupdhig** [comment]
Thank you very very much for your fast feedback!! :-)

**Comment by jayjupdhig** [comment]
![image](https://files.slack.com/files-pri/T01JYNPBP2T-F03426CV8PP/image.png)

The language resource text are all not defined yet - or it this a Debian 11 issue...?
(Which i don't think...?)


With best regards from Switzerland,
Jan

**Comment by thalesmg** [comment]
That is quite strange.  I've made a quick test using the Docker image for Debian 11, and it worked just fine:

![Screenshot 2022-02-23 at 10-01-15 EMQ X Broker](https://user-images.githubusercontent.com/16166434/155324365-a5df465e-7979-4458-8b1a-584c64b5fb1a.png)

**Comment by jayjupdhig** [comment]
I installed it via **'dpkg -i emqx-5.0-beta.3-otp24.1.5-3-debian10-amd64.deb'** on a fresh Debian 11 installation with (but with bullseye-backports Kernel 5.15.x)

**Comment by jayjupdhig** [comment]
...if there are some questions, so please don't hesitate to ask me. :-)

**Comment by jayjupdhig** [comment]
Should i report a bug or was this already done by EMQX dev team? Thx for feedback.

Kind regards from Switzerland, Jan

**Comment by jayjupdhig** [comment]
**OR, in another way:** How can i install it with docker container, as described by you, @thalesmg  ... ?

Thank you very very much for your feedback :-)

**Comment by jayjupdhig** [comment]
There seems to be no docker image to download on https://www.emqx.io/downloads ...

I tried (try and error) the URL https://www.emqx.io/downloads/broker/v5.0.0/emqx-docker-5.0-beta.3-otp24.1.5-3-debian10-amd64.zip to download the Docker 5.0 Beta3 image - but i just got a http 404 error... 

![image](https://user-images.githubusercontent.com/42765391/156146066-08ffe899-491d-462b-83e7-cf88278756fc.png)

**Comment by jayjupdhig** [comment]
And i found that on Google after entering keyword 'emqx-docker-5.0-beta.3-otp24.1.5-3-debian10-amd64.zip' in Google, but there is also no 5.0 beta3 docker image file... 


https://gitcode.net/mirrors/emqtt/emqttd/-/releases?from_codechina=yes

**Comment by zmstone** [comment]
Hi. you can browse and download non docker packages here : https://www.emqx.com/downloads/broker
doker images are published to dokcerhub. you can find all the tags here: https://hub.docker.com/r/emqx/emqx/tags

**Comment by jayjupdhig** [comment]
Thank you very much. Non-docker (.deb) version has, as already said, problems with its resource texts (-> screenshot) - at least in Debian 11...

**Comment by zmstone** [comment]
yes, that I am aware of but haven’t got time to troubleshoot.
We’ll follow up from #7158

**Comment by jayjupdhig** [comment]
Then that is the current opensource release version 5.0.3, that right so i think?
-> https://github.com/emqx/emqx/releases/download/v5.0.3/emqx-5.0.3-debian11-amd64.deb

Thanks in advance for your feedback(s).

**Comment by jayjupdhig** [comment]
That file does not work on Debian 11...

Note: I use backports-kernel on that system - maybe that's the reason for that behavior?

![image](https://user-images.githubusercontent.com/42765391/178268503-cf8c0777-9dd9-46b6-ae97-1a6c78dfa4a8.png)

**Comment by jayjupdhig** [comment]
OH - i've forgot the "dpkg -i ... " thing - so you can ignore my last posts ;-)
