### ISSUE TITLE
Username and password for mqtt client

### ISSUE THREAD

**Issue by kenpeter** [emqx/emqx#714]
I have an android app. It asks user to input username and password. Once login, I pass user's username and password to the mqtt client library in android. Now it is able to pub sub in channel. I don't want to store the plain password in the database within android. I thought I can store the plain password in a global variable, but when the app is close. (for iphone, it is the app got swiped out). The global variable will be lost.

I have a look at authquery in emqttd_plugin_mysql, the default query is select the hash password from the mqtt_user table, then compare the one the mqtt client submits.

I thought of jason web token, but I saw most of the mqtt client. the connection function only accept plain username and password. Any suggestion?

**Comment by 51systems** [comment]
You will have to store some kind of secret on the android device. Here's an example app that uses the android keystore to securely store secrets:
http://www.androidauthority.com/use-android-keystore-store-passwords-sensitive-information-623779/

**Comment by zhengyupan** [comment]
@kenpeter Hi, you can use JWT, we have a jwt auth plug for it:
https://github.com/emqx/emqx-auth-jwt
