### ISSUE TITLE
Current .deb installer has not resource (language) texts in its Web GUI - only placeholders

### ISSUE THREAD

**Issue by jayjupdhig** [emqx/emqx#7158]
Hi there

I tried to install the current .deb file on Debian 11 (even its not "officially" supportet by EMQX)... seems to work (service), but in it's Web GUI there are not language texts - only their placeholders.

As described here: https://github.com/emqx/emqx/issues/7105

Thank you very much,
Jan

**Comment by jayjupdhig** [comment]
Screenshot here:

![155283166-610401f0-d379-4638-ac59-6d23bd360c77](https://user-images.githubusercontent.com/42765391/155955156-fa03ae7b-ecf0-4118-b443-90a796be4df9.png)

If there are any questions, so please don't hesitate to ask me. Thanks.

**Comment by jayjupdhig** [comment]
-> https://github.com/emqx/emqx/issues/7105

**Comment by jayjupdhig** [comment]
OR, in another way: How can i install it with docker container, as described @thalesmg ... ?

**Comment by zmstone** [comment]
it seems to be just fine when I tested with debian10 deb package in debian11 (docker)

@jayjupdhig have you tested different versions of EMQX on the same endpoint? maybe try to visit with a fresh browser cache. e.g. incognito mode.

@ysfscream maybe you have some insights in why this happens ?

**Comment by ysfscream** [comment]
Thanks, @zmstone, and sorry for my late reply.

@jayjupdhig Hi, could you please open your browser's console to easily see what error messages are reported that you can let me know about?

**Comment by thalesmg** [comment]
> OR, in another way: How can i install it with docker container, as described @thalesmg ... ?

I simply downloaded the package from the [Releases page](https://github.com/emqx/emqx/releases/tag/v5.0-beta.3) into the official `debian:11` container and installed it like so:

```sh
wget https://github.com/emqx/emqx/releases/download/v5.0-beta.3/emqx-5.0-beta.3-otp24.1.5-3-debian10-amd64.deb
docker run --rm -it -v $PWD:/foo -p 1883:1883 -p 18083:18083 debian:11 bash
# inside the container
apt update -q && apt install -yq libatomic1 && dpkg -i /foo/emqx-5.0-beta.3-otp24.1.5-3-debian10-amd64.deb 
```

Then, for running it, you might want to do:

```sh
# inside the container, assuming you are still root from entering the container
su emqx
env EMQX_TELEMETRY__ENABLE=false emqx console
```

**Comment by jayjupdhig** [comment]
Different way, but same result as non-docker only with "dpkg -i ... ":

![image](https://user-images.githubusercontent.com/42765391/156767128-661c518b-863a-4809-98e4-2ff85922e8fc.png)

@ysfscream : I already reverted the snapshot, but, so i wrote here, with docker it results in the same issue.

So it's easily to reproduce - with and without docker...

And there are no errors in Chome dev tools:

1.)

![image](https://user-images.githubusercontent.com/42765391/156767363-363303ff-1a3b-4704-9967-064a11c80ec3.png)

2.) 

![image](https://user-images.githubusercontent.com/42765391/156767415-1abeb913-bab2-48ee-9349-13daba2bbbed.png)

(For the main page on http://10.5.121.176:18083/dashboard/overview ... )

With kind regards from Switzerland,
Jan

**Comment by jayjupdhig** [comment]
...and it seems that there are 2 texts on the same position:

![image](https://user-images.githubusercontent.com/42765391/156767890-63efed6b-db5d-4555-91e3-692b9b0f996a.png)

**Comment by jayjupdhig** [comment]
If you need more information, so please don't hesitate to ask me. thanks.

with kind regard from switzerland,
jan

**Comment by ysfscream** [comment]
Oh, this looks a bit strange. What do switching browsers look like if no error is reported in the console, for example with Firefox? But I think the effect will be the same, maybe a file is missing in the build, in which case we can only look forward to the next beta version to fix it.

**Comment by jayjupdhig** [comment]
After a restart, nothing works anymore...

![image](https://user-images.githubusercontent.com/42765391/157218495-bf5c890b-73eb-4132-a590-81584b92ae2e.png)

**Comment by zmstone** [comment]
Hi @jayjupdhig the install error seems to be due to the file is missing?

**Comment by jayjupdhig** [comment]
OH - thank you very very much!!

**Comment by ysfscream** [comment]
@jayjupdhig You may need to pick the language again at the top.

**Comment by jayjupdhig** [comment]
Oh - thank you very very much. Will look on it ASAP!! :-)

**Comment by jayjupdhig** [comment]
'You may need to pick the language again at the top.'

Seems to work!! :-)

->

![image](https://user-images.githubusercontent.com/42765391/164239828-187ad855-3434-4bd3-8179-a02a423342ab.png)

Thank you very very much - now i can finally test your v5... :-)

**Comment by jayjupdhig** [comment]
But the login screen does still have the same issue (so no cookie where the language change will be set, respectively not english [in general] as default language)

But, so i think at least, i can live with that... ;-)

**Comment by jayjupdhig** [comment]
One question more: Is it correctly that i can't save admin user language permanently (with persistence on DB or file system) so i don't need to change the language after every admin login?

It would be nice if we can define the language permanently e.g. in a user account settings page in EMQX 5 web GUI... :-)

**Comment by jayjupdhig** [comment]
AND: Is it not possible yet to configure users and their rights/permissions (or user groups and their rights/permissions and then map users to them) in the current RC1 version? Or is that not planned for the release...?

I've fund the menu where i can create a 2nd user (beside admin) - but now i ask me they are only Web GUI users (admin and non-admin?) or are they also users that i can use for MQTT server connection auth to publich to topics OR subscribe from topics...?

And i've also seen 2 menu links "authorization" and "authentication" - but nothing to map user(group) perimissions/rights.

Maybe i understood it wrong which features v5 will have...?

**Comment by jayjupdhig** [comment]
Now i've found how to create users...

1.) 

![image](https://user-images.githubusercontent.com/42765391/164249624-3e390570-b6d0-4c03-bcf9-087aa7afd5c0.png)


2.)

![image](https://user-images.githubusercontent.com/42765391/164249675-ec872a87-8ccf-4299-9ef7-68a3f5b72113.png)

**Comment by jayjupdhig** [comment]
ACL is the correct word so i think ;-)

**Comment by jayjupdhig** [comment]
???

**Comment by zmstone** [comment]
Hi @jayjupdhig 

Thank you so much for the issue reports.
It would be great if you can report each issue separately for more clear / focused follow ups.

**Comment by zmstone** [comment]
@jayjupdhig if you don't mind,
I'm inclined to close this thread as the issue in the title has been fixed.
and we can follow up each other issues in new threads.

**Comment by jayjupdhig** [comment]
OK thx. :-)

Will open a new one ASAP! :-)

**Comment by jayjupdhig** [comment]
HERE...
-> https://github.com/emqx/emqx/issues/7757

Thanks again!! :-)
