### ISSUE TITLE
查询符合规则的设备的在线总数

### ISSUE THREAD

**Issue by jsw-davidhuang** [emqx/emqx#7201]
有一个需求，就是服务器要定时记录设备的在线数，目前设备的clientID和app的clientID都是有某种规律的，例如device-xxxx，app-xxxx，但是我需要记录的时候筛选出设备有多少个在线，APP有多少在线，这样能做到吗？应该怎么做？

**Comment by lafirest** [comment]
You can use the **WebHook** or **System Topic** to listen to the client connections or lost connections, then manage this data by yourself logic, see the URL below for details
https://www.emqx.io/docs/en/v4.3/advanced/webhook.html#trigger-rule
https://www.emqx.io/docs/en/v4.3/advanced/system-topic.html#client-online-and-offline-events
