### ISSUE TITLE
Pub to sub latency high (in seconds) with clean session false as compared to clean session true(in milli seconds)

### ISSUE THREAD

**Issue by dhruvjain99** [emqx/emqx#7226]
### Subject of the issue
During the test, we observed that with clean-session=false(2nd time connecting i.e. when the cluster already has the client sessions from the first run), the pub to sub latency was quite high as compared to the clean-session=true. The pub to sub latency is high only during the time when the connections are getting established. Once the connections get established (1M in our case), the pub to sub latency dropped back to normal.

The following is the pub to sub latency graph in case of clean-session=true. Unit is microseconds. On an average we can say that p99 is 51ms.
![image](https://user-images.githubusercontent.com/51796498/156967590-dd493f14-e446-431c-90da-93523c0f759d.png)

The below graph is for clean-session=false. The drop in latency is after 1M connections are established. Post the drop the p99 is same as clean-session=true i.e. 51ms.
![image](https://user-images.githubusercontent.com/51796498/156967650-abe4dc3a-ac64-42bf-8285-ad72fd808874.png)

Both the tests involve same scenarios and QoS 0. So there are no saved messages.

### Your environment
The benchmark was performed on a cluster of 6 emqx nodes (8 core CPU and 32GB RAM) (GCP n2-standard-8).

- EMQ X version (e.g. `emqx_ctl status`): 4.3.5
- Hardware configuration (e.g. `lscpu`): 
```
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
Address sizes:                   46 bits physical, 48 bits virtual
CPU(s):                          8
On-line CPU(s) list:             0-7
Thread(s) per core:              2
Core(s) per socket:              4
Socket(s):                       1
NUMA node(s):                    1
Vendor ID:                       GenuineIntel
CPU family:                      6
Model:                           79
Model name:                      Intel(R) Xeon(R) CPU @ 2.20GHz
Stepping:                        0
CPU MHz:                         2199.998
BogoMIPS:                        4399.99
Hypervisor vendor:               KVM
Virtualization type:             full
L1d cache:                       128 KiB
L1i cache:                       128 KiB
L2 cache:                        1 MiB
L3 cache:                        55 MiB
NUMA node0 CPU(s):               0-7
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Mitigation; PTE Inversion
Vulnerability Mds:               Mitigation; Clear CPU buffers; SMT Host state unknown
Vulnerability Meltdown:          Mitigation; PTI
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl and seccomp
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Full generic retpoline, IBPB conditional, IBRS_FW, STIBP conditional, RSB filling
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Mitigation; Clear CPU buffers; SMT Host state unknown
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx pdpe1gb rdtscp lm constant_tsc rep_good nopl xtopology nonstop_tsc
                                 cpuid tsc_known_freq pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch invpcid_single pti ssbd ibrs i
                                 bpb stibp fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm rdseed adx smap xsaveopt arat md_clear arch_capabilities
```
- OS (e.g. `cat /etc/os-release`):
```
NAME="Ubuntu"
VERSION="20.04.2 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.2 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```
- Kernel (e.g. `uname -a`): `Linux VM_NAME 5.11.0-1023-gcp #25~20.04.1-Ubuntu SMP Mon Nov 15 15:54:39 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`
- Others: Cluster of 6 VMs (emqx nodes) each with the above configuration

### Steps to reproduce
Traffic pattern is as follows.
- 1M subscribers with 2000 rps connect rate
- 300 publishers
- 3000 rps send/receive rate
- 500 rps connect/disconnect rate
- QoS 0 for both pub and sub
- There is a unique topic for each subscribe to which it is subscribing. And 300 publishers are publishing to random topics out of all the topics which the subscribers are subscribed to, at the rate of 10rps per publisher making it to 3000 rps in total.

Also, we have noticed the same behaviour at 700k subscribers as well.

### Expected behaviour
Pub to sub latency should be in milli seconds (< 100ms) throughout the test even during the time connections are getting established.

### Actual behaviour
Pub to sub latency is in the order of seconds during the time connections are getting established.

**Comment by qzhuyan** [comment]
Could you describe how do you measure the "pub to sub latency" ? Are the clients in this loop part of the clients that are sending connects with clean-session=false?

**Comment by qzhuyan** [comment]
Are the clients that are sending CONNECT (with clean-session=false) messages are part of 'pub to sub latency' measurements?

**Comment by dhruvjain99** [comment]
"pub to sub latency" measurements are only for PUBLISH messages - "client x" to broker and broker to "client y". For CONNECT messages we have "connack latency" graph. 

We have two pools of clients. Both the pools connect with clean-session=false. One pool of clients once connected send a SUBSCRIBE message to subscribe to a topic and wait for messages. The other pool of clients once connected continuously publish messages at the rate of 10rps.

**Comment by qzhuyan** [comment]
>One pool of clients once connected send a SUBSCRIBE message to subscribe to a topic and wait for messages. The other pool of clients once connected continuously publish messages at the rate of 10rps.

I need to get better understanding about your traffic model. 

Do you mean the client always connect with a 'clean-session=false', no matter if it did connect before ?

or you connect them with 'clean-session=true' then disconnect and then again reconnect with 'clean-session=false'?

**Comment by dhruvjain99** [comment]
Think of it as a fresh emqx cluster without any clients. I run one scenario for 25 mins as described below with clean-session=false.
- 1M subscribers (In order to create 1M subscribers, we'll be creating clients(connect and subscribe) at the rate of 2k rps)
- 300 publishers
- 3000 rps send/receive message rate
- 500 rps connect/disconnect rate - A pool of clients continuously connecting and disconnecting to simulate 500 rps connect/disconnect.
- QoS 0 for both pub and sub

Now after the above scenario finishes, the emqx cluster will have offline queues (sessions). Now if I restart the above scenario, the pub to sub latency will be high in the order of seconds till we reach 1M subscriber clients i.e. till the connections are getting created.

**Comment by qzhuyan** [comment]
Ok. before you restart the scenario, did you wait for all clients to get offline? there will be some clean-up in emqx that might be heavy depending on the how session looks like.

I guess you use a loadbalancer, do you enable sticky sessions?

Do you have monitoring on emqx nodes? like CPU usage, Memory, network IO? 

Could you try with a smaller cluster like 3 nodes?

I don't know about GCP but in AWS VM instance they do limit the network IO which is bad for a large cluster.

Could you provide logs?

**Comment by dhruvjain99** [comment]
> Ok. before you restart the scenario, did you wait for all clients to get offline? there will be some clean-up in emqx that might be heavy depending on the how session looks like.

Yes, we waited for all the clients to get offline.

> I guess you use a loadbalancer, do you enable sticky sessions?

Yes, we tried both with/without sticky sessions.

> Do you have monitoring on emqx nodes? like CPU usage, Memory, network IO?

Yes, we had monitoring for the VM node on which the EMQX was running. All the metrics were within limits.

> Could you try with a smaller cluster like 3 nodes?

At present, we have halted the evaluation of EMQX for our use-cases. I would suggest you try it once and let us all know the results. If in the future, we resume the evaluation, I'll let you know the results.

**Comment by qzhuyan** [comment]
@dhruvjain99 Sorry we don't have enough information to reproduce/investigate the issue you reported. I close the issue for now, if you have more info or want to continue troubleshoot the issue just reopen it or create new one.
