### ISSUE TITLE
The old disconnect notification message is later than the new connection notification message

### ISSUE THREAD

**Issue by imkos** [emqx/emqx#7240]
emqx: 4.3.10
RT:
![image](https://user-images.githubusercontent.com/17872894/157260319-f936b0c7-3333-4b86-ad8a-ae13842759b1.png)

**Comment by zmstone** [comment]
@imkos 
are the events originated from the same EMQX node ?

@HJianBo 
are these events async ?
is there a way to serialise it?

**Comment by imkos** [comment]
After the device terminal is upgraded, the firmware version is also upgraded, the clientID has changed, but the serialization of the device remains unchanged, it is the same device terminal

**Comment by HJianBo** [comment]
But, it is a different client for emqx.  The better design is that they should have the same `clientid` whatever firmware version is.


_btw, another possible reason is that the previous client has not sent DISCONNECT packet to emqx to notify it has disconnected_

**Comment by zmstone** [comment]
this is not something we can fix as the events are independent especially when the client changes clientid.
