### ISSUE TITLE
Missing DISCONNECT packet when kicking client

### ISSUE THREAD

**Issue by fracasula** [emqx/emqx#7241]
#### Environment

- EMQ: Dockerized 4.4.1

#### Description

Hey guys, I just came across this issue and wanted to double check with you in case I'm missing something.

I'm kicking out a client with a `DELETE /api/v4/clients/<CLIENT_ID>` but on the client side the connection is closed with a generic error because the client is not getting a `DISCONNECT`.

I see this in the `emqx` logs:

> [emqx] 2022-03-08T16:34:25.165263+00:00 [info] 57ce28e8-c990-4e3d-8635-0b1c3a8050e6@172.17.0.1:36452 file: emqx_connection.erl, line: 552, mfa: {emqx_connection,terminate,2}, msg: terminate, pid: <0.2014.0>, reason: {shutdown,kicked}

When kicking a client with [vernemq](https://github.com/vernemq/vernemq) I'm getting a `DISCONNECT` so I thought I'd check with you.

Here are the MQTT protocol specs: https://docs.oasis-open.org/mqtt/mqtt/v5.0/os/mqtt-v5.0-os.html#_Toc3901205

> The DISCONNECT packet is the final MQTT Control Packet sent from the Client or the Server. It indicates the reason why the Network Connection is being closed. The Client or Server MAY send a DISCONNECT packet before closing the Network Connection. If the Network Connection is closed without the Client first sending a DISCONNECT packet with Reason Code 0x00 (Normal disconnection) and the Connection has a Will Message, the Will Message is published. Refer to [section 3.1.2.5](https://docs.oasis-open.org/mqtt/mqtt/v5.0/os/mqtt-v5.0-os.html#_Toc479576982) for further details.

I would expect a `DISCONNECT` with Reason Code `152` (i.e. `0x98`) "Administrative action". What do you think?

**Comment by HJianBo** [comment]
Yes, it is a bug. We will fix it in the next release (v4.4.2). Thanks for your feedback.

**Comment by fracasula** [comment]
> Yes, it is a bug. We will fix it in the next release (v4.3.13, v4.4.2). Thanks for your feedback.

Thanks @HJianBo that's good news! Do you know already when to expect the next release?
