### ISSUE TITLE
EMQX Entry point for the helm chart

### ISSUE THREAD

**Issue by arseni-meteor** [emqx/emqx#7242]
### Subject of the issue
Addition of entry point to the EMQX HELM chart configuration

- EMQ X version (e.g. `emqx_ctl status`):  4.4

### Steps to reproduce
Install EMQX using the HELM charts

### Expected behaviour
Being able to configure the entry point of EMQX using the HELM charts

### Actual behaviour
Can't [configure](https://github.com/emqx/emqx/blob/85d87a768ad4ae743458853b7e1d54a5af39d48f/deploy/charts/emqx/templates/StatefulSet.yaml#L126) the entry point. As the HELM chart values yaml has the [emqxConfig](https://github.com/emqx/emqx/blob/87b05b28426bde2a10ea690a27105b86792fcc3a/deploy/charts/emqx/values.yaml#L53) field, allowing also to configure the [bridge](https://hub.docker.com/r/emqx/emqx) fields, I was not able to set it to any non-static value, even to an env-variable. This limits a lot the use of the HELM chart for specific configurations. I thought that a simple and fast solution would be to add the option to configure the entry-point ([here](https://github.com/emqx/emqx/blob/85d87a768ad4ae743458853b7e1d54a5af39d48f/deploy/charts/emqx/templates/StatefulSet.yaml#L126)), which would allow changing those values.

I would need to have an option to configure something like this:

    entrypoint: 
      - "/bin/bash"
      - "-c"
      # Compgen loop is required to set hostname to environment variables
      # Sed is to rewrite bridge name, if name is the same messages get duplicated
      - "echo $$@ && for path in $$(compgen -e) ; do eval \"$$path=\\\"$${!path//\\\"/\\\\\\\"}\\\"\"; done && printenv && echo $$@ && echo success! && /usr/bin/docker-entrypoint.sh && sed -i \"s/bridge.mqtt.aws./bridge.mqtt.$$HOSTNAME./g\" /opt/emqx/etc/plugins/emqx_bridge_mqtt.conf && /usr/bin/docker-entrypoint.sh /usr/bin/start.sh"

Thank you

**Comment by art-pepper** [comment]
Having the same problem, I don't have the option to set up emqxConfig with fields that need to be dynamic such as:
```yaml
EMQX_MODULE__REWRITE__PUB__RULE__1: "t/+ ^t/(.+)$$ t/$$HOSTNAME/\\$$1"
EMQX_MODULE__REWRITE__SUB__RULE__1: "t/+ ^t/(.+)$$ t/$$HOSTNAME/\\$$1"
EMQX_MODULE__REWRITE__SUB__RULE__2: "t/+/+ ^t/(.+)/(.+)$$ t/$$HOSTNAME/\\$$1/\\$$2"
EMQX_MODULE__REWRITE__PUB__RULE__2: "r/+/+/+/+ ^r/(.+)/(.+)/(.+)/(.+)$$ r/$$HOSTNAME/\\$$1/\\$$2/\\$$3/\\$$4"
EMQX_MODULE__REWRITE__PUB__RULE__3: "r/reg/+ ^r/reg/(.+)$$ r/$$HOSTNAME/reg/\\$$1"
EMQX_BRIDGE__MQTT__AWS__FORWARDS: "r/$$HOSTNAME/#"
EMQX_BRIDGE__MQTT__AWS__SUBSCRIPTION__1__TOPIC: "t/*"
EMQX_BRIDGE__MQTT__AWS__SUBSCRIPTION__2__TOPIC: "t/$$HOSTNAME/*"
EMQX_BRIDGE__MQTT__AWS__SUBSCRIPTION__3__TOPIC: "t/$$HOSTNAME/reg/*"
```
Unless there is a different possible solution for dynamic environment variables, I guess starting with enabling setting up a custom entrypoint in the StatefulSet will be helpful.

**Comment by Rory-Z** [comment]
Hi, guys, this is a good idea
We will add entry point for `EMQX` helm chart in next version

**Comment by Rory-Z** [comment]
Hi, guys, I just check [`values.yaml`](https://github.com/emqx/emqx/blob/main-v4.4/deploy/charts/emqx/values.yaml) for EMQX helm chart, maybe you can use `extraArgs` like this:
```
extraArgs:
  - "/bin/bash"
  - "-c"
  - "printenv && /opt/emqx/bin/emqx foreground"
```
Please let me know if it meets your expectations, thanks

**Comment by zmstone** [comment]
seems to be answered by Rory, but no feedback for a long time.
