### ISSUE TITLE
"emqx start" fial, but "emqx console" does

### ISSUE THREAD

**Issue by 18580543261** [emqx/emqx#7247]
### Subject of the support
=================problem===================
"emqx start" fial, but "emqx console" does

=================emqx start===================
/opt/emqx/bin $ emqx start
EMQ X Broker 4.3.12 failed to start within 15 seconds,
see the output of '/usr/local/bin/emqx console' for more information.
If you want to wait longer, set the environment variable
WAIT_FOR_ERLANG to the number of seconds to wait.

=================emqx console===================
/opt/emqx/bin $ emqx console
allow_anonymous = "false"
log.to = "console"
Erlang/OTP 23 [erts-11.1.8] [emqx] [64-bit] [smp:2:2] [ds:2:2:8] [async-threads:4]

Starting emqx on node emqx@127.0.0.1
2022-03-09T02:10:41.148052+00:00 [warning] [Alarm Handler] Alarm high_system_memory_usage is activated, System memory usage is higher than 70.0%
Start mqtt:tcp:internal listener on 127.0.0.1:11883 successfully.
Start mqtt:tcp:external listener on 0.0.0.0:1883 successfully.
Start mqtt:ws:external listener on 0.0.0.0:8083 successfully.
Start mqtt:ssl:external listener on 0.0.0.0:8883 successfully.
Start mqtt:wss:external listener on 0.0.0.0:8084 successfully.
Start http:management listener on 8081 successfully.
Start http:dashboard listener on 18083 successfully.
EMQ X Broker 4.3.12 is running now!
Eshell V11.1.8  (abort with ^G)
====================================

waht is the problem?

Error/Warning printout if any. 

### Your environment

For EMQ X 4.3 or newer, please provide the log archive generated by [node_dump tool](https://github.com/emqx/emqx/blob/master/bin/node_dump) 

Otherwise please provide below info:
- EMQ X version (e.g. `emqx_ctl status`): 4.3.12
- If cluster (e.g. 3 X 4Core16GB): no
- Hardware configuration (e.g. `lscpu`): 
- OS (e.g. `cat /etc/os-release`): docker - image: emqx/emqx:4.3.12
- Kernel (e.g. `uname -a`):
- Erlang/OTP version (in case you build emqx from source code): 
- Others:
docker-compose:
innobase-emqx:
    image: emqx/emqx:4.3.12
    container_name: emqx
    depends_on:
      - innobase-django
    volumes:
      - ./logs/emqx:/opt/emqx/log:rw
      - ./emqx/scripts/:/opt/emqx/scripts/:ro
      - ./emqx/etc/emqx.conf:/opt/emqx/etc/emqx.conf:ro
      - ./emqx/etc/plugins/emqx_auth_http.conf:/opt/emqx/etc/plugins/emqx_auth_http.conf:ro
      - ./emqx/etc/plugins/emqx_web_hook.conf:/opt/emqx/etc/plugins/emqx_web_hook.conf:ro
      - ./emqx/etc/plugins/emqx_management.conf:/opt/emqx/etc/plugins/emqx_management.conf:ro
      
    command:
      /bin/bash -c  "tail -f /dev/null"
    ports:
      - "1883:1883"
      - "8081:8081"
      - "8083:8083"
      - "8883:8883"
      - "8084:8084"
      - "18083:18083"
    env_file:
      - .env
    environment:
      EMQX_ALLOW_ANONYMOUS: "false"
      EMQX_LOADED_PLUGINS: "emqx_management,emqx_auth_http,emqx_web_hook,emqx_recon,emqx_retainer,emqx_dashboard"
      EMQX_MANAGEMENT__DEFAULT_APPLICATION__SECRET: "Innobase_admin"
      EMQX_AUTH__HTTP__AUTH_REQ__URL: "${EMQX_BACKEND_ADDR}/api/innobase_mqtt_iot/mqtt/login/"
      EMQX_AUTH__HTTP__ACL_REQ__URL: "${EMQX_BACKEND_ADDR}/api/innobase_mqtt_iot/mqtt/can_publish/"
      EMQX_AUTH__HTTP__SUPER_REQ__URL: "${EMQX_BACKEND_ADDR}/api/innobase_mqtt_iot/mqtt/is_superuser/"
      EMQX_AUTH__HTTP__SUPER_REQ__PARAMS: "clientid=%c,username=%u"
      EMQX_AUTH__HTTP__SUPER_REQ__METHOD: "post"
      EMQX_AUTH__HTTP__SUPER_REQ__HEADERS__CONTENT_TYPE: "application/x-www-form-urlencoded"
      EMQX_WEB__HOOK__URL: "${EMQX_BACKEND_ADDR}/api/innobase_mqtt_iot/mqtt/hook/emqx_hook/"
    networks:
      network:
        ipv4_address: ${IP_EMQX}

### LOG File

Missing log file can delay the handling of the issue.

**Comment by zmstone** [comment]
as the log hints: 
```
If you want to wait longer, set the environment variable
WAIT_FOR_ERLANG to the number of seconds to wait.
```
