### ISSUE TITLE
emqx_packet:format(Packet) may affect performance

### ISSUE THREAD

**Issue by yqfclid** [emqx/emqx#7250]
emqx 4.0.4
在模块emqx_connection 和 emqx_ws_connection 中，以下代码是不是有点问题，?LOG(debug, "SEND ~s", [emqx_packet:format(Packet)]),这样的代码会使得程序运行emqx_packet:format(Packet)，而io_lib:format在Packet很大的时候会很耗时，会影响到进程的正常消息处理，降低进程处理消息的速度，在流量很大的情况下造成消息堆积

```
serialize_and_inc_stats_fun(#state{serialize = Serialize}) ->
    fun(Packet) ->
        case Serialize(Packet) of
            <<>> -> ?LOG(warning, "~s is discarded due to the frame is too large!",
                         [emqx_packet:format(Packet)]),
                    ok = emqx_metrics:inc('delivery.dropped.too_large'),
                    ok = emqx_metrics:inc('delivery.dropped'),
                    <<>>;
            Data -> ?LOG(debug, "SEND ~s", [emqx_packet:format(Packet)]),
                    ok = inc_outgoing_stats(Packet),
                    Data
        end
    end.
```
```
handle_incoming(Packet, State) when is_record(Packet, mqtt_packet) ->
    ok = inc_incoming_stats(Packet),
    ?LOG(debug, "RECV ~s", [emqx_packet:format(Packet)]),
    with_channel(handle_in, [Packet], State);
```

**Comment by zmstone** [comment]
in 4.3 there is a configurable format depth limit  and a total bytes limit for logger.
4.0 is out of the maint window, fixes are not ported back anymore, please consider upgrading

**Comment by yqfclid** [comment]
I am sorry and maybe I am stupid. My question is io_lib:format/2 will costs lots of time when packet is large or has long depths, finally affect emqx's performance. The code means emqx_packet:format(Packet) will execute regardless of the log level and emqx_packet:format(Packet) calls io_lib:format/2.My question is nothing to do with logger and I find emqx has the same code in 4.3.10.

**Comment by zmstone** [comment]
The ?LOG macro wraps the fmt string and arg list into a lambda which is only evaluated when logging level is allowed 

https://github.com/emqx/emqx/blob/7a1d22e79f743fc3d481034de2119cd06c115686/include/logger.hrl#L46

**Comment by yqfclid** [comment]
Got it. Thanks for your reply.
