### ISSUE TITLE
默认用户名admin如何修改

### ISSUE THREAD

**Issue by sunnyinchina** [emqx/emqx#7259]
由于网络安全要求，默认用户名admin需要修改为非常见、简单的用户名，
但是plugins/emqx_dashboard.conf这里面把admin修改为其他名称，重启emqx，依然不生效。
请问如何修改？

**Comment by zhongwencool** [comment]
一般都可能通过命令行，或HTTP API增删用户。


emqx在第一次启动时会把emqx_dashboard.conf的用户名密码写到内置的数据库中，
在以后的启动中就会直接用数据库里的用户和密码，所以当你写emqx_dashboard.conf后重启也不会再写了。
你需要用命令行修改用户密码，或删除旧的，增加新用户。

```bash
[root@VM-8-11-centos emqx]# ./bin/emqx_ctl admins
admins add <Username> <Password> <Tags>                               # Add dashboard user
admins passwd <Username> <Password>                                   # Reset dashboard user password
admins del <Username>                                                 # Delete dashboard user
```

计划于后续版本加入，当emqx_dashboard.conf密码与数据库不一致时，日志警告，如何修复密码。

**Comment by sunnyinchina** [comment]
emqx 开源版 windows上下载并未启动，就直接修改了emqx_dashboard.conf中admin用户名为aaaaaa和密码bbbbbbb，结果启动后还是admin，public可以登录，并且增加了新用户aaaaaa和密码bbbbbbb，故软件存在bug

**Comment by zhongwencool** [comment]
> emqx 开源版 windows上下载并未启动，就直接修改了emqx_dashboard.conf中admin用户名为aaaaaa和密码bbbbbbb，结果启动后还是admin，public可以登录，并且增加了新用户aaaaaa和密码bbbbbbb，故软件存在bug

非常感谢反馈 ：）
1. admin/public可以登录，应该是你的机器上已经运行启动过，已经把admin写入到数据库中了。
   可以通过以下方式验证。
   下载一个全新的emqx，在不启动前修改admin，确保data/mnesia/目录为空的情况后启动emqx，尝试使用admin/public是无法登录的。
2. 后期加的新用户，启动时会自动加入数据库，所以能登录是预期行为。

**Comment by sunnyinchina** [comment]
下载一个全新的emqx，就直接修改了emqx_dashboard.conf中admin用户名为aaaaaa和密码bbbbbbb，结果admin，public可以登录，并且增加了新用户aaaaaa和密码bbbbbbb，故存在bug

**Comment by zhongwencool** [comment]
麻烦提供一下全新emqx的版本及下载连接。
我这边试了4.4.1是正常的，
请确保：启动前一定要把旧节点停掉 且 data/mnesia/目录为空

**Comment by zmstone** [comment]
@sunnyinchina 一旦数据库被初始化，配置文件就不再使用了，修改只能通过API。
@zhongwencool 建议的步骤是删掉数据库，重新初始化，生产环境请谨慎使用
