### ISSUE TITLE
Max Clients in MQTT protocol

### ISSUE THREAD

**Issue by DataEngg** [emqx/emqx#726]
Hi @emqplus , @turtleDeng 

Initially I have set the max clients to 1000K  in emqttd.config. Our machine has 8 GB memory with 4 core, I am able to connect 120K concurrent connection easily but when it exceeds 8 GB memory emqttd terminates itself. What I thought is set a max client per machine would be far better.

To overcome such problem I have setup 2 Machine of 8 GB server, clustered them together as well as start a bridge too for a single topic and set a max client in emqttd.config file as 80K only in both of the machine. Now whats happens both of the machines are still consuming whole memory when less number of clients get connected to individual machine.

There are three problems:- 

1) I don't know why it is consuming whole memory  when less number of clients are connected in a a machine

2) Why less number of clients get connected in individual machine. When I have set to 80K as a max client then only 40K max client get connected to an individual machine.

3) After reaching to max limit client started disconnection from EMQTT Server.

Please reply soon :(

After attaching emqttd console i got following error

20:57:30.625 [error] Failed to start connection on 0.0.0.0:17576 - maxlimit
20:57:30.627 [error] Failed to start connection on 0.0.0.0:17576 - maxlimit
20:57:30.627 [error] Failed to start connection on 0.0.0.0:17576 - maxlimit
20:57:30.630 [error] Failed to start connection on 0.0.0.0:17576 - maxlimit

It looks like users are not allowed to connect when it reach to max limit

**Comment by turtleDeng** [comment]
http://emqtt.com/docs/v2/tune.html

**Comment by DataEngg** [comment]
Thanks @turtleDeng .. but i did all this tunning earlier in all machines

**Comment by DataEngg** [comment]
@emqplus @turtleDeng 

Please help me out

**Comment by turtleDeng** [comment]
http://emqtt.io/docs/v2/tune.html#emqttd-broker

**Comment by DataEngg** [comment]
@turtleDeng 

I have already done tuning , nothing left to do and set the max clients  according to the server size because server can't handle more than 100K clients

**Comment by DataEngg** [comment]
@turtleDeng 

It looks like Server can handle 100K concurrent clients at a time but user more than 100K client would be able to connect to server by kicking out other clients, so in server it looks like there are only 100K clients but other information like routes, subscriber and session count can be increased which causes memory to be utilized.

**Comment by DataEngg** [comment]
@turtleDeng 

When i set max client to 1000K then i started receiving an error 

=ERROR REPORT==== 17-Oct-2016::05:25:45 ===
** Generic server <0.1805.0> terminating
** Last message in was {inet_async,#Port<0.11884>,4070,
                           {ok,<<16,52,0,4,77,81,84,84,4,0,84,96,0,40,56,53,
                                 56,52,57,100,50,54,57,100,98,49,99,99,53,97,
                                 52,57,57,49,56,98,53,101,98,99,97,102,101,
                                 54,52,99,53,52,98,49,53,52,56,97>>}}
** When Server state == {client_state,
                            {esockd_connection,
                                [#Port<0.11884>,
                                 #Fun<esockd_transport.2.94509882>,[]]},
                            ["43.225.248.19",58,"44583"],
                            {{43,225,248,19},44583},
                            {43,225,248,19},
                            44583,true,running,undefined,
                            #Fun<emqttd_parser.0.27418187>,
                            {proto_state,
                                {{43,225,248,19},44583},
                                #Fun<emqttd_client.0.128174639>,false,
                                undefined,<0.1805.0>,undefined,undefined,
                                undefined,undefined,undefined,undefined,512,
                                undefined,undefined,undefined},
                            [{max_clientid_len,512},{max_packet_size,65536}],
                            undefined}
** Reason for termination ==
** {{timeout,
        {gen_server2,call,
            [<0.277.0>,
             {start_session,
                 {false,<<"85849d269db1cc5a49918b5ebcafe64c54b1548a">>,
                     <0.1805.0>}},
             120000]}},
    [{gen_server2,call,3,[{file,"src/gen_server2.erl"},{line,340}]},
     {emqttd_protocol,process,2,[{file,"src/emqttd_protocol.erl"},{line,149}]},
     {emqttd_client,received,2,[{file,"src/emqttd_client.erl"},{line,265}]},
     {gen_server,try_dispatch,4,[{file,"gen_server.erl"},{line,601}]},
     {gen_server,handle_msg,5,[{file,"gen_server.erl"},{line,667}]},
     {proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}

**Comment by DataEngg** [comment]
@huangdan  Can you help me in this. Can't we set max number of clients per machine instead of maximum concurrent clients.

**Comment by fleapapa** [comment]
Hi there,
Is this issue still outstanding? 

We need to deploy a production system with ~2M clients which act both as publishers and subscribers simultaneously. We also need to enable TLS between the clients and (clustered) MQTT brokers. If this "kick-out" issue is there, the TLS re-handshaking may incur quite some overhead to our servers.

Could anyone confirm the issue is still there or already resolved?

Thanks!

**Comment by Gilbert-Wong** [comment]
So sorry for late response. Is this issue still outstanding, and how did you config your etc/emq.conf?
