### ISSUE TITLE
登录安全风险

### ISSUE THREAD

**Issue by sunnyinchina** [emqx/emqx#7260]
登录时，会提示“用户名不存在Username Not Found”或者“Password Error”两种情况，据此可枚举出系统中存在的账号信息，存在中等安全楼的弄风险，强烈建议登录页面错误提示信息将上述两种情况统一提示“用户名或者密码错误”。

**Comment by zmstone** [comment]
已在4.3最新版本中修复

**Comment by sunnyinchina** [comment]
请问4.4版本中为何没修复该bug？

**Comment by zmstone** [comment]
对不起，弄错了。

**Comment by zhongwencool** [comment]
开源版本4.3.x上已修复了，企业版预计在e4.3.8/e4.4.2上修复。
