### ISSUE TITLE
quic stream will be disconnected after a period of normal communication

### ISSUE THREAD

**Issue by InasaXia** [emqx/emqx#7286]
### Subject of the issue
Quic stream will be closed after a period of normal communication.

log:
```
msg: mqtt_packet_sent, packet: DISCONNECT(Q0, R0, D0),ReasonCode=129
msg: socket_force_closed, reason: [hint: malformed_utf8_string,parsed_length: 49152,remaining_bytes_length: 70]

```
### Your environment

- EMQ X version (e.g. `emqx_ctl status`): EMQ X 5.0-beta.3 Released
- OS (e.g. `cat /etc/os-release`): centos7.x
- Kernel (e.g. `uname -a`): 5.6.2

**Comment by qzhuyan** [comment]
malformed_utf8_string means the mqtt message is malformed.

Could you provide us the debug logs?
