### ISSUE TITLE
EMQ cluster for Production environment, best practices

### ISSUE THREAD

**Issue by adarshlal** [emqx/emqx#734]
Hi,

Can you please share the best practices for a setting up EMQ cluster for production environment.
What should be the right configuration.

Thanks in advance.

**Comment by StarpTech** [comment]
Im also looking for a short guide. Thanks.

**Comment by emqplus** [comment]
@StarpTech @adarshlal Cooking a guide to deploy EMQ cluster on AWS, which will be released with EMQ version 2.2

**Comment by pawantejwani** [comment]
@emqplus thanks, waiting for the docs to come 😃

**Comment by sohailgerman92** [comment]
@emqplus Is the documentation ready ? Because i am about to start with clustering and that will guide me in better ways

**Comment by gihad** [comment]
@emqplus I would also appreciate any documentation on deploy on AWS. Even better if there is some automation done for it (e.g.: Cloudformation, Ansible)

**Comment by emqplus** [comment]
Hi @gihad, Deployment Guid of EMQ X: http://emqx-enterprise-docs-en.readthedocs.io/en/latest/deploy.html

**Comment by gihad** [comment]
@emqplus What is EMQ X? Is there a link to a website with information about it? I can only find links to emqtt here: http://emqtt.io/downloads

**Comment by Gilbert-Wong** [comment]
The default config of emqx is recommended config. You could also refer our (official docs)[http://emqtt.io/docs/v3/index.html] to customize your config
