### ISSUE TITLE
Trace packet feature/Qos 2 messages in clustered mode

### ISSUE THREAD

**Issue by adarshlal** [emqx/emqx#735]
Hi,

We have setup a 3 node cluster of EMQTT broker. 
I was testing the trace packet feature. The feature is working fine in a single node. 
If I am starting the trace in one node and publish or subscribe from another node in the same cluster, the message is not traced/logged in the trace file.

I have the similar issue for QoS 2 messages delivery also. 
1. I am subscribing to topic in one node of the cluster with QoS 2. 
2. I am publishing message to the same topic into another node in the cluster (QoS=2).
   The message is not received in the subscriber end.

But the QoS=1 and QoS=0 messages are received correctly.

Is there any configuration that needs to be enabled to get these work among the different nodes of the cluster?

Thanks in advance.

**Comment by huangdan** [comment]
hi,@adarshlal
According to your description, we cannot reproduce your problem ,
Please tell me, which version you are using

**Comment by Gilbert-Wong** [comment]
There should be no such problem in the latest emqx3.0.0 release. Please try latest version of emqx.
