### ISSUE TITLE
Ubuntu packages not available for emqx from version 4.3.5 onwards

### ISSUE THREAD

**Issue by s-mittelberger** [emqx/emqx#7377]
#### Environment

- OS: Ubuntu 18.04 (verified also on Ubuntu 20.04)
- Erlang/OTP: not relevant
- EMQ: not relevant

#### Description

We installed emqx on our Ubuntu 18.04 machines using the deb package repo at https://repos.emqx.io/emqx-ce/deb/ubuntu.

We noticed that the latest version obtainable from there is 4.3.5. All releases newer than that are missing.
We verified the same thing also on Ubuntu 20.04.

Has a decision been made to not support deb package based installation anymore? Can this be fixed?

**Comment by zmstone** [comment]
Hi @s-mittelberger-pexta 
Sorry for the inconvenience. Before we can fix it, please download the packages from https://www.emqx.com/en/try?product=broker

**Comment by s-mittelberger-pexta** [comment]
Hi @zmstone 
Thanks for your reply. OK, will do.
Can you already give an ETA until when it will be fixed?

**Comment by zmstone** [comment]
@s-mittelberger-pexta unsure yet.
We are investigating a more professional tool/platform to host the repos.

**Comment by AlessandroBravo** [comment]
Hi @zmstone 
Any updates on this issue?
Thanks in advance.

**Comment by zmstone** [comment]
Hi @AlessandroBravo 

We have signed up packagecloud.io to be our new hosting service.
Once it's deployed and tested, we'll update [docs.](https://www.emqx.io/docs/en/v4.3/)

**Comment by zmstone** [comment]
As we are still testing it, it's not ready to be announced yet,
nonetheless, there is actually a package uploaded already,
you are welcome to give it a try.
https://packagecloud.io/emqx/emqx-community

**Comment by AlessandroBravo** [comment]
Hi @zmstone,

thanks for the quick answer.

I'll try in the next couple of days.

**Comment by id** [comment]
https://packagecloud.io/emqx/emqx is up and running.
