### ISSUE TITLE
subscription module, equivalent of "stored" in version 2

### ISSUE THREAD

**Issue by R-Masoumi** [emqx/emqx#738]
I'm trying to find the functionality where client will subscribe to previously subscribed topics upon reconnect, the subscription module on older version seems to have a "stored" value where it does exactly this (found it on another issue):

%% Subscribe topics automatically when client connected
     {subscription, [
    %%    %% Subscription from stored table
       stored,
]},

but I can't find it's equivalent in version 2, emq.conf. does the functionality exist in the new version? what do I need to add to activate  "Subscription from stored table" in this config?

 ## Enable subscription module
 ##  Subscribe topics automatically when client connected
mqtt.module.subscription = on
mqtt.module.subscription.topics = client/%c=1,$user/%u=1

alternatively is there any way to add a dynamic list (for instance fetched from a Redis query) to mqtt.module.subscription.topics ?

**Comment by turtleDeng** [comment]
Sorry, can not be dynamically added, only through the configuration to modify！

**Comment by nogitsune** [comment]
is "Subscription from stored table" removed in the latest version as well?

**Comment by Gilbert-Wong** [comment]
This feature has been moved in to enterprise edition of emqx.
