### ISSUE TITLE
Parse failed for function_clause, [{emqx_frame,parse_packet,[{mqtt_packet _header,7,false,0,false}

### ISSUE THREAD

**Issue by Aniready** [emqx/emqx#7390]
My java program suddenly reported an error(MqttException:Client is not connected)，and  Emqx reports the following errors.
When I change the client ID and reconnect, I can connect successfully without error.
Can anyone tell me what the mistake is？

### Your environment

- EMQ X version (e.g. `emqx_ctl status`): 4.3.8
- OS (e.g. `cat /etc/os-release`):centos7
- Erlang/OTP version (in case you build emqx from source code): 23.2.7.2-emqx-2/11.1.8
### error log

2022-03-22T16:23:07.356801+08:00 [error] 1647263405750-publish@10.29.64.149:60152 [Channel] Unexpected frame error: function_clause
2022-03-22T16:23:07.356944+08:00 [error] 1647263405750-publish@10.29.64.149:60152 [MQTT] , Parse failed for function_clause, [{emqx_frame,parse_packet,[{mqtt_packet
_header,7,false,0,false},<<"62KuU3FTjyfisMI2jypoeR7ySbbFj0z+VT7RHHt8j5rRuG0IMR3DlfNbzMSCY32nvxWoUpbh">>,#{max_size => 2097152,strict_mode => false,version => 4}],[{file,"emqx
_frame.erl"},{line,204}]},{emqx_frame,parse_frame,4,[{file,"emqx_frame.erl"},{line,181}]},{emqx_connection,parse_incoming,3,[{file,"emqx_connection.erl"},{line,625}]},{emqx_c
onnection,handle_msg,2,[{file,"emqx_connection.erl"},{line,618}]},{emqx_connection,process_msg,2,[{file,"emqx_connection.erl"},{line,364}]},{emqx_connection,handle_recv,3,[{f
ile,"emqx_connection.erl"},{line,328}]},{proc_lib,wake_up,3,[{file,"proc_lib.erl"},{line,236}]}], Frame data:<<"pH62KuU3FTjyfisMI2jypoeR7ySbbFj0z+VT7RHHt8j5rRuG0IMR3DlfNbzMSC
Y32nvxWoUpbhu4NaP74v0wc1gR8ZtLkzlllHuWvXmFaMJznxWSRHGMdzWY4kce9sP3FSv6lGAVUgBjWkbP9wynhR5qQRhnBJ5HzWHUNJt3YNKmGswDNhef71oy4XH7q2nlEajAyf4rcw7VDA5JpWrYRSIwScNWzJ6w3MO1RxSLK5Vu
CPiiBOiOIx2qGtoDGyMMH2eawlxE0mwBgfk0Q8ZHIIIqKQqwBwAw+KoUbbDYrHz/evEZRscEc1qQVjDsMsfA8VuyezJbIPgGrtbywmJYQX4J7ipUwF2rwnxUTInpD3bW8AVo5d1AHtHyKlEdpFjMe8g968i8+5q3"...>>

**Comment by Aniready** [comment]
Recovery process ：
Restart emqx
Restart Java program
then the Error disappears

**Comment by zmstone** [comment]
The client sent an unexpected `PUBCOMP(7)` message.

For MQTT protocol version 4, the ID should be a 16bit integer, but the client sent
`62KuU3FTjyfisMI2jypoeR7ySbbFj0z+VT7RHHt8j5rRuG0IMR3DlfNbzMSCY32nvxWoUpbh`
which looks like a part of a base64 encoded payload ?

It's likely that the message was not really a `PUBCOMP`, but malformed.

**Comment by zmstone** [comment]
@JimMoen For this `function_clause` exception, we should improve the logging message.

**Comment by Aniready** [comment]
> 
I know this may be a protocol frame format error, but this program has been running, and this problem was found recently. It is the error reported by the program reconnection times. After the appeal operation, the error disappeared;i use java package is"org.eclipse.paho.client.mqttv3"; Can you give some preventive measures or suggestions for this mistake?thank you.

**Comment by Aniready** [comment]
> The client sent an unexpected message.`PUBCOMP(7)`
> 
> For MQTT protocol version 4, the ID should be a 16bit integer, but the client sent which looks like a part of a base64 encoded payload ?`62KuU3FTjyfisMI2jypoeR7ySbbFj0z+VT7RHHt8j5rRuG0IMR3DlfNbzMSCY32nvxWoUpbh`
> 
> It's likely that the message was not really a , but malformed.`PUBCOMP`

I know this may be a protocol frame format error, but this program has been running, and this problem was found recently. It is the error reported by the program reconnection times. After the appeal operation, the error disappeared;i use java package is"org.eclipse.paho.client.mqttv3"; Can you give some preventive measures or suggestions for this mistake?thank you.

**Comment by zmstone** [comment]
Hi @Aniready 
we unfortunately have very limited experience in programming using the paho library.
If I have to guess, it’s perhaps because the underlying send buffer is not cleared when reconnect.
