### ISSUE TITLE
The official website document and ACL file have different rules

### ISSUE THREAD

**Issue by Hcreak** [emqx/emqx#7399]
### Subject of the issue
I followed the document (https://www.emqx.io/docs/en/v4.3/advanced/acl-file.html#acl-conf-writing-rules) to configure the ACL file. But can't start emqx now. Because I used `clientid` in the second position of the tuple.

The different syntax rules of acl.conf are included in the comments at the top:
```
%%--------------------------------------------------------------------
%% [ACL](https://docs.emqx.io/broker/v3/en/config.html)
%%
%% -type(who() :: all | binary() |
%%                {ipaddr, esockd_access:cidr()} |
%%                {client, binary()} |
%%                {user, binary()}).
%%
%% -type(access() :: subscribe | publish | pubsub).
%%
%% -type(topic() :: binary()).
%%
%% -type(rule() :: {allow, all} |
%%                 {allow, who(), access(), list(topic())} |
%%                 {deny, all} |
%%                 {deny, who(), access(), list(topic())}).
%%--------------------------------------------------------------------
```
I change to `client` in the second position of the tuple. Then start emqx normally.

Both the Chinese page and the English page have this error.

### Your environment

- EMQ X version (e.g. `emqx_ctl status`):  **4.3.3**

### Expected behaviour
The official website document need to fix this bug.

**Comment by thalesmg** [comment]
Hi @Hcreak !

Thanks for reporting this.  It's indeed a documentation problem: the correct configuration key is `client` and not `clientid`.

We'll follow up with a doc fix.

**Comment by thalesmg** [comment]
The current docs for v4.4 have been updated with the fix:

![image](https://user-images.githubusercontent.com/16166434/167457981-92e32553-d086-40dc-bb6c-6a2358acd4a0.png)

I'm closing this issue now.  Thanks again for the report!
