### ISSUE TITLE
Windows emqx_4.4.1 self exited after 2 days。

### ISSUE THREAD

**Issue by renguifeng** [emqx/emqx#7410]
Ranch listener 'mqtt:ws:8083' had connection process started with cowboy_clear:start_link/4 at <0.2437.8> exit with reason: {{case_clause,{error,closed}},[{cowboy_websocket,websocket_send_close,2,[{file,"cowboy_websocket.erl"},{line,640}]},{cowboy_websocket,websocket_close,3,[{file,"cowboy_websocket.erl"},{line,623}]},{proc_lib,wake_up,3,[{file,"proc_lib.erl"},{line,236}]}]}

**Comment by zmstone** [comment]
the log you shared doesn't seem to be related to the service went down.
could you see if there are more logs in `log` dir?
maybe a crash dump?

**Comment by renguifeng** [comment]
no any  crash  dump in the log dir，the blow file  is  the whole log。
[log.zip](https://github.com/emqx/emqx/files/8348785/log.zip)

**Comment by renguifeng** [comment]
> no any crash dump in the log dir，the  file is the whole log。 [log.zip](https://github.com/emqx/emqx/files/8348785/log.zip)

**Comment by renguifeng** [comment]
maybe the problem was related to the server hardware。

**Comment by renguifeng** [comment]
very thanks ，it was because the server was power off。
