### ISSUE TITLE
EMQX process crashed!

### ISSUE THREAD

**Issue by zh1an** [emqx/emqx#7415]
### Subject of the issue
In `powershell`, execute command `./emqx start`, then, int short time(no more than 10sec), `erl.exe` process will be crashed. No log.

Check Windows event, there was shown that crypto.dll crased.

**NOTE:** The software can't be run on our latest batch of computers.

### Your environment

For EMQ X 4.3 or newer, please provide the log archive generated by running `node_dump` (The `node_dump` script can be found in `/<path-to-installation-of-emqx>/bin` if you installed emqx from source or zip ball).

- EMQ X version (e.g. `emqx_ctl status`):  v4.4.1
- Hardware configuration (e.g. `lscpu`): 
- OS (e.g. `cat /etc/os-release`): windows 10
- Kernel (e.g. `uname -a`): 
- Erlang/OTP version (in case you build emqx from source code): 
- Others:

### Steps to reproduce
Tell us how to reproduce this issue. 

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

Missing log file can delay the handling of the issue.

![c2c11d5ca6e5b0e93edc510acc54e6e](https://user-images.githubusercontent.com/30436038/160076482-9f5f4cc0-c121-463a-bd8b-86bab1714b5b.png)

![b1e6ac97b1228cbbc52e16d922b0da2](https://user-images.githubusercontent.com/30436038/160076504-e46a0a56-cdb2-4f03-8762-daef3c8fc478.png)

![615fd7c62504037cecaa9f80e72379f](https://user-images.githubusercontent.com/30436038/160076521-e6860e7e-d812-4230-a3b0-8da5d5ca6d0c.png)

**Comment by zh1an** [comment]
after executing `./emqx console`, there was a window showing, but in multi seconds, this window because no response crashed.

**Comment by zmstone** [comment]
Hi @zh1an 
The package is built on Windows 2019.
The DLL module released in the package is perhaps not quite compatible.

**Comment by zmstone** [comment]
We have switched to a newer version Erlang in later builds.
https://github.com/emqx/emqx/pull/7488
Could you give the latest 4.4 version a try?
