### ISSUE TITLE
macOS: Build failed with QUIC

### ISSUE THREAD

**Issue by sekfung** [emqx/emqx#7428]
### Subject of the issue
Build Failed

### Your environment

For EMQ X 4.3 or newer, please provide the log archive generated by running `node_dump` (The `node_dump` script can be found in `/<path-to-installation-of-emqx>/bin` if you installed emqx from source or zip ball).

- EMQ X version (e.g. `emqx_ctl status`):  master latest 
- Hardware configuration (e.g. `lscpu`):
- OS (e.g. `cat /etc/os-release`):   macOS Monterey 12.3
- Kernel (e.g. `uname -a`):  Darwin Kernel Version 21.4.0
- Erlang/OTP version (in case you build emqx from source code):  24.3.2
- Others:

### Steps to reproduce
After executing **make** cmd, I got these error log
```log
~/IoT/emqx/_build/default/lib/quicer/msquic/src/platform/datapath_kqueue.c:1984:14: error: variable 'TailBuffer' set but not used [-Werror,-Wunused-but-set-variable]
    uint8_t* TailBuffer = SendData->Buffers[SendData->BufferCount - 1].Buffer;
             ^
1 error generated.
make[3]: *** [msquic/src/platform/CMakeFiles/platform.dir/datapath_kqueue.c.o] Error 1
make[2]: *** [msquic/src/platform/CMakeFiles/platform.dir/all] Error 2
make[2]: *** Waiting for unfinished jobs....
```

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

Missing log file can delay the handling of the issue.

**Comment by sekfung** [comment]
> @sekfung Could you provide the mac version, gcc version? As a workaround, you could build with `make clean-all; BUILD_WITHOUT_QUIC=1 make`

@qzhuyan OK. 
mac version:  12.3 (21E230),  Intel CPU
gcc version: 
```bash
gcc --version
Apple clang version 13.1.6 (clang-1316.0.21.2)
Target: x86_64-apple-darwin21.4.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

`make clean-all; BUILD_WITHOUT_QUIC=1 make`,  it works. And this command  `make clean-all; make`,   it was failed. 

the error log is same as the above.

**Comment by sekfung** [comment]
Sorry, my mistake.

my mac gcc links to clang previously, so when I switch gcc again, the error is the same.

```log
~/IoT/emqx/_build/default/lib/quicer/msquic/src/platform/datapath_kqueue.c:1984:14: error: variable 'TailBuffer' set but not used [-Werror,-Wunused-but-set-variable]
[ 67%] Building C object msquic/src/platform/CMakeFiles/platform.dir/tls_openssl.c.o
    uint8_t* TailBuffer = SendData->Buffers[SendData->BufferCount - 1].Buffer;
             ^
1 error generated.
make[3]: *** [msquic/src/platform/CMakeFiles/platform.dir/datapath_kqueue.c.o] Error 1
make[3]: *** Waiting for unfinished jobs....
make[2]: *** [msquic/src/platform/CMakeFiles/platform.dir/all] Error 2
make[1]: *** [all] Error 2
```

```bash
gcc --version
gcc-11 (Homebrew GCC 11.2.0_3) 11.2.0
Copyright (C) 2021 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**Comment by qzhuyan** [comment]
@sekfung no worry, I just want to get the compiler version to reproduce.

**Comment by id** [comment]
The issue has been addressed in https://github.com/microsoft/msquic/pull/2566
