### ISSUE TITLE
Cluster unavailable when a broker is removed from cluster

### ISSUE THREAD

**Issue by alejandrojn-ncg** [emqx/emqx#7445]
### Subject of the support
Hi all!

I'm running an EMQX cluster v4.4.1 in Kubernetes (EKS v1.21.5). Every time a broker Pod is deleted and removed from the cluster (ie. when doing a rolling update) the remaining brokers become unreachable for 2 minutes approximately. During that time, no events are received from the publishers causing the events sent on that period to be lost.

I've tried setting the cluster discovery to k8s and to dns, the behaviour is always the same.

How can I prevent that from happening?

Please let me know if you need more information about my set up.
Thanks a lot!!
### LOG File

Environment info and logs in the dump file
[node_dump_20220329_084310.tar.gz](https://github.com/emqx/emqx/files/8369766/node_dump_20220329_084310.tar.gz)

**Comment by zmstone** [comment]
Hi @alejandrojn-ncg 

Thank you for sharing the node_dump file.
From which node at which point in time was the node dump created?
Confirm check: you have 8G RAM for each node ?

Also, I'd like to know how many nodes do you have in the cluster.
and approximately how many clients connected to each.

**Comment by alejandrojn-ncg** [comment]
The node dump was created from the remaining node just right after another node (Pod) was deleted.
Yes, each k8s worker nodes have 8Gb of RAM. The emqx pods don't have any resource limit. 
For this test, there was 2 nodes in the cluster and 1 of them was deleted to replicate the issue. There was only 1 publisher and 2 subscribers connected to the cluster
I've been able to replicate the issue on clusters with 3 and 4 nodes and the result is always the same. When a node suddenly leaves the cluster, the remaining nodes become unavailable.

You can find the related logs since 2022-03-29T08:38 on the node dump.

Please let me know if you need more information.
Thanks a lot for your help!

**Comment by zmstone** [comment]
@alejandrojn-ncg 
And the node dump is taken right after the other pod is killed ?

So far, I haven't been able to find anything useful to diagnose this issue.
I think we need to rule out network issue first.

Could you try to start a pod which runs some comman-line MQTT client
in the same internal network as EMQX nodes running and test connectivity by connecting to the EMQX pod directly ?

**Comment by alejandrojn-ncg** [comment]
Hi! Yes, the node dump is taken from the remaining node just right after another node (Pod) was deleted.

I think we can rule out connectivity issues because the brokers are able to form a cluster, so they are able to see and connect to each other. Publishers and subscribers are able to connect to any broker inside the cluster.

The issue starts only when one of the brokers is suddenly killed, the remaining brokers get stuck like trying to find the missing broker. After some minutes, the remaining nodes within the cluster start working just find again, but during the period of downtime, no events are processed.

You can find the related logs since 2022-03-29T08:38 on the node dump.

Please let me know if you need more information or if you need me to run another test.
Thanks a lot for your help!

**Comment by zmstone** [comment]
Hi. 

Could you please describe a bit more on how you verified the message loss?

You have 3 clients and two brokers, 
I suppose the one publisher is publishing messages to the two subscribers?
And if the clients are connected to different brokers, when one pod is killed, the other client also stopped receiving any message?

**Comment by alejandrojn-ncg** [comment]
Hi! Yes, there is 1 publisher sending messages with QoS 0 every few seconds and 2 subscribers.
When a pod is killed clients loose connection to the remaining broker and all messages are lost during, even though the clients were not connected to the recently killed pod. After a few minutes, connection is reestablished for all client.
Also, when a Pod is killed, dashboard or admin interface stop responding.

For your questions, I'm assuming this is not a regular behaviour, am I missing something in the config?

Thanks!
BR

**Comment by zmstone** [comment]
Hi @alejandrojn-ncg 
Thank you for the information.

We noticed similar behaviour when the cluster is heavily loaded and the sudden loss of a node in the cluster would cause a flood of client status updates to the rest of the cluster. In such case, it may give the other nodes a hiccup.

But you have only 3 clients, so it is indeed quite irregular.

Is it true that all your observations are from outside of the EKS environment?
I wonder if there could be something wrong with the load balancing.
