### ISSUE TITLE
EMQX not work with istio in k8s when listeners.tcp.default.proxy_protocol is true

### ISSUE THREAD

**Issue by sekfung** [emqx/emqx#7485]
### Subject of the support

EMQX not work with istio in k8s when listeners.tcp.default.proxy_protocol is true.

I want to get the client real ip in emqx, so I set `EMQX_LISTENERS__TCP__DEFAULT__PROXY_PROTOCOL: true` in emqxConfig,  but it made the client can not connect the broker. if I comment that , it can work.

### Your environment

- EMQ X version: master latest
- k8s version: 1.20.6
- istio: 1.12.5

**values.yaml** 
emqxConfig:
  EMQX_LISTENERS__TCP__DEFAULT__PROXY_PROTOCOL: 'true'

**Comment by zmstone** [comment]
I'm not quite familiar with istio.
Does it support proxy protocol v2? 
If it supports, is it enabled in your config?
ref: https://www.haproxy.org/download/1.8/doc/proxy-protocol.txt
