### ISSUE TITLE
Shared subscription not working on clustered nodes

### ISSUE THREAD

**Issue by hijklmno** [emqx/emqx#752]
Hi EMQTT team,

I have two EMQTT nodes in a cluster:
```
$ ./bin/emqttd_ctl cluster status
Cluster status: [{running_nodes,['emqttd@10.0.1.64','emqttd@10.0.1.173']}]
```

When I subscribe two clients to one node, the shared subscription works fine. However, when I subscribe two clients to different nodes, the shared subscription is not being distributed:
Subscriber 1:
```
mosquitto_sub -t '$queue/test/thistopic' -h 10.0.1.64 -v
```

Subscriber 2:
```
mosquitto_sub -t '$queue/test/thistopic' -h 10.0.1.173 -v
```

Publisher:
```
mosquitto_pub -t 'test/thistopic' -m 'asdf' -h 10.0.1.173
```

Results:  

Subscriber 1 | Subscriber 2 | Publisher | Results
------------ | ------------- | ------------ | ------------- 
10.0.1.173	 | 10.0.1.173	 | 10.0.1.173	 | Shared
10.0.1.64	 | 10.0.1.64	 | 10.0.1.64	 | Shared
10.0.1.64	 | 10.0.1.64	 | 10.0.1.173	 | Shared
10.0.1.173	 | 10.0.1.173	 | 10.0.1.64	 | Shared
10.0.1.64	 | 10.0.1.173	 | 10.0.1.64	 | Duplicated
10.0.1.173	 | 10.0.1.64	 | 10.0.1.173	 | Duplicated

Please advise on how I can get shared subscription when subscribing across multiple nodes in a cluster.

**Comment by emqplus** [comment]
@hijklmno, The broker does not support shared subscriptions across clustered nodes. You could use the Local Shared Subscription if you want to consume the incoming MQTT messages 
the load-balance way. For example:

Subscriber 1:

```
mosquitto_sub -t '$local/$queue/test/thistopic' -h 10.0.1.64 -v
```
Subscriber 2:

```
mosquitto_sub -t '$local/$queue/test/thistopic' -h 10.0.1.173 -v
```

**Comment by hijklmno** [comment]
Thank you @emqplus. Local shared subscriptions will be difficult to manage when we have emqttd and our subscribers on autoscaling. Do we know if shared subscriptions across clustered nodes is on the roadmap?

**Comment by emqplus** [comment]
@hijklmno, no plan still.

**Comment by BinLi-OW** [comment]
@emqplus , This seems to be a great feature for the common use case, is there any update plan for this feature?

**Comment by emqplus** [comment]
@BinLi-OW Plan to improve the shared subscription design in 2.4 release:)

**Comment by Shawn-ye** [comment]
So I guess the subscription of topic starts with `$share` won't be broadcasted to the other nodes also?

**Comment by zhengyupan** [comment]
Hi @hijklmno, now shared subscription is part of MQTT 5 standard. We also improved the implementation of shared subscription, now it works cluster-wide.
