### ISSUE TITLE
Default value of rpc.port_discovery is not listed in documentation

### ISSUE THREAD

**Issue by matthewGEA** [emqx/emqx#7521]
Running emqx v4.4.2 docker container

I see this value when inspecting the value within emqx.conf after loading:
```
bash-5.1$ cat /opt/emqx/etc/emqx.conf | grep rpc.port_discovery -C 5
## - stateless: discover ports in a stateless manner.
##   If node name is `emqx<N>@127.0.0.1`, where the `<N>` is an integer,
##   then the listening port will be `5370 + <N>`
##
## Defaults to `stateless`.
rpc.port_discovery = stateless

## TCP port number for RPC server to listen on.
##
## Only takes effect when `rpc.port_discovery` = `manual`.
##
## NOTE: All nodes in the cluster should agree to this same config.
##
## Value: Port [1024-65535]
#rpc.tcp_server_port = 5369
```

I also see this value in the console when starting emqx:
`rpc.port_discovery = "manual"`

Documentation without a default value specified is here:
https://www.emqx.io/docs/en/v4.4/configuration/configuration.html#rpc-port-discovery

**Comment by thalesmg** [comment]
Hi @matthewGEA !

The table representation for the possible values in the documentation is indeed strange and does not show the default value correctly.

However, in the description for `rpc.port_discovery`, one can see that the default value is described:

![2022-04-06_17-50](https://user-images.githubusercontent.com/16166434/162068627-7fc51016-efdf-47a0-a4ee-fbd2c9afcf82.png)
