### ISSUE TITLE
Stranger errors

### ISSUE THREAD

**Issue by roysG** [emqx/emqx#7533]
1.
Error: 2022-04-06T17:15:52.467664+00:00 [error] Generic server <0.1048.829> terminating. Reason: killed. Last message: {'EXIT',<0.1088.829>,killed}. State: {state,{<0.1048.829>,poolboy_sup},simple_one_for_one,{[mc_worker],#{mc_worker => {child,undefined,mc_worker,{mc_worker,start_link,[[{host,"[host-shard-00-01.eeud1.mongodb.net](http://host-shard-00-02.eeud5.mongodb.net/)"},{port,27017},{database,...},{...}|...]]},temporary,5000,worker,[mc_worker]}}},{mapsets,#{<0.860.829> => []}},0,1,[],0,poolboy_sup,{mc_worker,[{host,"[host-shard-00-01.eeud1.mongodb.net](http://host-shard-00-02.eeud5.mongodb.net/)"},{port,27017},{database,<<"open"...>>},{auth_source,<<...>>},{login,...},{...}|...]}}.

2.
Error: 2022-04-06T17:12:43.481286+00:00 [error] crasher: initial call: mc_worker:init/1, pid: <0.28773.886>, registered_name: [], exit: {tcp_closed,[{gen_server,handle_common_reply,8,[{file,"gen_server.erl"},{line,805}]},{proc_lib,wake_up,3,[{file,"proc_lib.erl"},{line,236}]}]}, ancestors: [<0.1849.0>,<0.1847.0>,<0.1844.0>,<0.1842.0>,<0.1841.0>,<0.1839.0>,emqx_auth_mongo_sup,<0.1837.0>], message_queue_len: 0, messages: [], links: [<0.1849.0>], dictionary: [], trap_exit: false, status: running, heap_size: 2586, stack_size: 28, reductions: 21634; neighbours:

3.
Error: 2022-04-06T17:08:31.465442+00:00 [error] Generic server <0.26032.883> terminating. Reason: tcp_closed. Last message: {ssl_closed,{sslsocket,{gen_tcp,#Port<0.5351109>,tls_connection,undefined},[<0.26431.883>,<0.26479.883>]}}. State: {state,{sslsocket,{gen_tcp,#Port<0.5351109>,tls_connection,undefined},[<0.26431.883>,<0.26479.883>]},#{},<<>>,{conn_state,unsafe,master,<<"admin">>,<<"admin">>},undefined,#Fun<mc_worker.0.76890317>,ssl}.

What all these types of errors?
Are these robots trying to authenticate or something else?

Can i stop it?

**Comment by zmstone** [comment]
Hi @roysG 
Theses all look like mongodb clients failing to connect or getting disconnected, maybe network, maybe server maintenance.
Which version are you on?

If it does not stop (keep spamming the logs)?
In 4.3.13, we have fixed a dead loop logging, but there is one fixed but not made it to 4.3.13.
https://github.com/emqx/mongodb-erlang/pull/27/files
 -- this one will be released in 4.3.14

If you are running 4.3.13 or 4.4.2, you can try to stop it by restarting the mongodb plugin or resource.

**Comment by roysG** [comment]
I run version:  4.3.5	permanent

**Comment by roysG** [comment]
The cluster is on production, please suggest the best proper way to update to fixed version.
Thanks

**Comment by zmstone** [comment]
hi @roysG unless the logs are flooded with such errors, there is no action required.
Otherwise it might be due to the above mentioned bug, we’ll have to wait for the next release.
