### ISSUE TITLE
EMQX v5.0.0-rc.1 support quic protocol issues?

### ISSUE THREAD

**Issue by Gypsying** [emqx/emqx#7581]
#### Environment

- OS: CentOS Linux release 7.4.1708 (Core)
- EMQ: [EMQ X Community Edition v5.0.0-rc.1](https://github.com/emqx/emqx/releases/tag/v5.0.0-rc.1)

#### Description

Hi everyone,
I'm glad to hear that emqx v5 support quic protocol, i will have a try to play with it;
But there are too much changed with the older emqx version, and i can't find any document about emqx v5...

@zmstone @tigercl @Rory-Z 
Could you provide more documents about quic protocol supported?
Or provide some client access demo?

Any help will be appreciated!!!

**Comment by Gypsying** [comment]
I try to use [quic-go](https://github.com/lucas-clemente/quic-go/tree/master/example/client) to access emqx quic port(https://x.x.x.x:14567/), 
but i always got error: *Peer closed connection with error: CRYPTO_ERROR (0x178): tls: no application protocol*.

I don't know why and how to solve this....

Any help will be appreciated!!!

**Comment by Gypsying** [comment]
ping...

**Comment by qzhuyan** [comment]
@Gypsying MQTT5.0 supports to run mqtt over quic but not http over quic.
