### ISSUE TITLE
Client cannot connect with protocolId set

### ISSUE THREAD

**Issue by LuGrInaut** [emqx/emqx#7606]
Hello there,

I'm trying to connect to a EMQX Cloud Broker Deployment via a Nodejs application. However at connection time it throws an error when protocolId or protocolVersion is set. If I remove this two settings it works.

![rec](https://user-images.githubusercontent.com/90252420/163123724-173ffa18-f220-4840-925e-a9fa1e9130e1.png)

Currently we are using a mosquitto mqtt broker where it runs without problems. As I have some old applications running where I dont have access to and cannot change the connection settings it would be great to know if emqx does not support this or if there is a workaround or something.

Broker: EMQX Cloud Standard Deployment
Client: NodeJS v14 with mqtt-npm-package v4.3.6

Thanks,
Lukas

**Comment by ieQu1** [comment]
Hello @LuGrInaut ,

EMQX does support MQTT v3.1 (3), and we have tests that verify that, also I've just double-checked that using my local instance.
This problem may be related to the particular settings of the broker running in the cloud. The cloud is managed by a different team, I assume you have some way to contact the support?

**Comment by LuGrInaut** [comment]
Hello @ieQu1,

I just noticed that a ticket can be raised on the clouds dashboard. I may ask there for further advice.
Thank you.
