### ISSUE TITLE
Parse failed for function_clause -- how to fix

### ISSUE THREAD

**Issue by kiddyt00** [emqx/emqx#7607]
how do I fix the error below,anyone help
### Subject of the support
I found some error in my emqx cluster,every error not such same,like 
Parse failed for function_clause
Parse failed for {badmatch,<<>>}
Parse failed for frame_too_large
[warning] <<"etsme-E1100200024219000305-ebox">>@10.100.90.128:35419 [Channel] The PUBACK PacketId 1 is not found.

for me device is a blackbox to me ,hao can I get more info at the emqx-server,some error display the client-id,hao can I get more info

Error/Warning printout if any. 
[{emqx_frame,parse_utf8_string,[<<1,2,0>>],[{file,"emqx_frame.erl"},{line,438}]},{emqx_frame,parse_packet,3,[{file,"emqx_frame.erl"},{line,184}]},{emqx_frame,parse_frame,4,[{file,"emqx_frame.erl"},{line,163}]},{emqx_connection,parse_incoming,3,[{file,"emqx_connection.erl"},{line,551}]},{emqx_connection,handle_msg,2,[{file,"emqx_connection.erl"},{line,544}]},{emqx_connection,process_msg,3,[{file,"emqx_connection.erl"},{line,313}]},{proc_lib,wake_up,3,[{file,"proc_lib.erl"},{line,236}]}]
Frame data:<<22,3,1,2,0,1,0,1,252,3,3,181,112,227,128,206,128,144,36,23,16,237,203,122,196,4,198,236,148,49,203,166,247,254,254,243,198,68,108,145,196,201,63,32,93,92,177,163,15,14,22,61,175,76,190,212,135,139,144,254,166,238,182,184,119,131,60,228,204,244,177,22,169,124,106,102,0,62,19,2,19,3,19,1,192,44,192,48,0,159,204,169,204,168,204,170,192,43,192,47,0,158,192,36,192,40,0,107,192,35,192,39,0,103,192,10,192,20,0,57,192,9,192,19,0,51,0,157,0,156,0,61,0,60,0,53,0,47,0,255,1,0,1,117,0,11,0,4,3,0,1,2,0,10,0,12,0,10,0,29,0,23,0,30,0,25,0,24,0,35,0,0,0,16,0,14,0,12,2,104,50,8,104,116,116,112,47,49,46,49,0,22,0,0,0,23,0,0,0,13,0,48,0,46,4,3,5,3,6,3,8,7,8,8,8,9,8,10,8,11,8,4,8,5,8,6,4,1,5,1,6,1,3,3,2,3,3,1,2,1,3,2,2,2,4,2,5,2,6,2,0,43,0,9,8,3,4,3,3,3,2,3,1,0,45,0,2,1,1,0,51,0,38,0,36,0,29,0,32,142,51,130,62,201,30,53,140,4,53,64,239,33,89,129,169,16,100,143,250,2,36,0,211,168,229,103,99,23,106,3,113,0,21,0,202,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0>>
2022-04-10 05:40:57.923 [warning] <<"etsme-E1100200024219000305-ebox">>@10.100.90.128:35419 [Channel] The PUBACK PacketId 1 is not found.
2022-04-10 19:30:44.707 [warning] <<"etsme-E1100200014219000023-ebox">>@172.16.142.249:59897 [Channel] The PUBACK PacketId 1 is not found.
2022-04-10 22:49:22.170 [error] 10.100.245.128:18901 [MQTT] 
Parse failed for function_clause
[{emqx_frame,parse_packet,[{mqtt_packet_header,4,false,3,true},<<"T / HTTP/1.1\r\nUser-Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:">>,#{max_size => 1048576,strict_mode => false,version => 4}],[{file,"emqx_frame.erl"},{line,183}]},{emqx_frame,parse_frame,4,[{file,"emqx_frame.erl"},{line,163}]},{emqx_connection,parse_incoming,3,[{file,"emqx_connection.erl"},{line,551}]},{emqx_connection,handle_msg,2,[{file,"emqx_connection.erl"},{line,544}]},{emqx_connection,process_msg,3,[{file,"emqx_connection.erl"},{line,313}]},{proc_lib,wake_up,3,[{file,"proc_lib.erl"},{line,236}]}]
Frame data:<<"GET / HTTP/1.1\r\nUser-Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:36.0) Gecko/20100101 Firefox/36.0\r\nHost: emqx.etsme.com:31884\r\nConnection: Keep-Alive\r\nAccept-Encoding: gzip\r\n\r\n">>
2022-04-11 01:24:52.138 [error] 10.100.62.128:59556 [MQTT] 
Parse failed for {badmatch,<<>>}
[{emqx_frame,parse_packet,3,[{file,"emqx_frame.erl"},{line,196}]},{emqx_frame,parse_frame,4,[{file,"emqx_frame.erl"},{line,163}]},{emqx_connection,parse_incoming,3,[{file,"emqx_connection.erl"},{line,551}]},{emqx_connection,handle_msg,2,[{file,"emqx_connection.erl"},{line,544}]},{emqx_connection,process_msg,3,[{file,"emqx_connection.erl"},{line,313}]},{proc_lib,wake_up,3,[{file,"proc_lib.erl"},{line,236}]}]
Frame data:<<22,3,0,0,105,1,0,0,101,3,3,85,28,167,228,114,97,110,100,111,109,49,114,97,110,100,111,109,50,114,97,110,100,111,109,51,114,97,110,100,111,109,52,0,0,12,0,47,0,10,0,19,0,57,0,4,0,255,1,0,0,48,0,13,0,44,0,42,0,1,0,3,0,2,6,1,6,3,6,2,2,1,2,3,2,2,3,1,3,3,3,2,4,1,4,3,4,2,1,1,1,3,1,2,5,1,5,3,5,2>>
2022-04-11 01:24:52.218 [error] 10.100.62.128:36301 [MQTT] 
Parse failed for frame_too_large
[{emqx_frame,parse_remaining_len,5,[{file,"emqx_frame.erl"},{line,153}]},{emqx_connection,parse_incoming,3,[{file,"emqx_connection.erl"},{line,551}]},{emqx_connection,handle_msg,2,[{file,"emqx_connection.erl"},{line,544}]},{emqx_connection,process_msg,3,[{file,"emqx_connection.erl"},{line,313}]},{proc_lib,wake_up,3,[{file,"proc_lib.erl"},{line,236}]}]
Frame data:<<0,164,255,83,77,66,114,0,0,0,0,8,1,64,0,0,0,0,0,0,0,0,0,0,0,0,0,0,64,6,0,0,1,0,0,129,0,2,80,67,32,78,69,84,87,79,82,75,32,80,82,79,71,82,65,77,32,49,46,48,0,2,77,73,67,82,79,83,79,70,84,32,78,69,84,87,79,82,75,83,32,49,46,48,51,0,2,77,73,67,82,79,83,79,70,84,32,78,69,84,87,79,82,75,83,32,51,46,48,0,2,76,65,78,77,65,78,49,46,48,0,2,76,77,49,46,50,88,48,48,50,0,2,83,97,109,98,97,0,2,78,84,32,76,65,78,77,65,78,32,49,46,48,0,2,78,84,32,76,77,32,48,46,49,50,0>>
2022-04-11 01:25:17.624 [error] 10.100.62.128:8416 [MQTT] 
Parse failed for frame_too_large
[{emqx_frame,parse_remaining_len,5,[{file,"emqx_frame.erl"},{line,131}]},{emqx_connection,parse_incoming,3,[{file,"emqx_connection.erl"},{line,551}]},{emqx_connection,handle_msg,2,[{file,"emqx_connection.erl"},{line,544}]},{emqx_connection,process_msg,3,[{file,"emqx_connection.erl"},{line,313}]},{proc_lib,wake_up,3,[{file,"proc_lib.erl"},{line,236}]}]
Frame data:<<0,253,206,250,11,176,160,0,0,0,77,77,83,20,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,18,0,0,0,1,0,3,0,240,240,240,240,11,0,4,0,28,0,3,0,78,0,83,0,80,0,108,0,97,0,121,0,101,0,114,0,47,0,57,0,46,0,48,0,46,0,48,0,46,0,50,0,57,0,56,0,48,0,59,0,32,0,123,0,48,0,48,0,48,0,48,0,65,0,65,0,48,0,48,0,45,0,48,0,65,0,48,0,48,0,45,0,48,0,48,0,97,0,48,0,45,0,65,0,65,0,48,0,65,0,45,0,48,0,48,0,48,0,48,0,65,0,48,0,65,0,65,0,48,0,65,0,65,0,48,0,125,0,0,0,224,109,223,95>>
2022-04-11 01:26:28.014 [error] 10.100.62.128:1006 [MQTT] 
Parse failed for function_clause
[{emqx_frame,parse_packet,[{mqtt_packet_header,0,false,0,false},<<19,132,95,132,0,0,0,0,0,0,0,2,0,1,134,160,0,0,0,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0>>,#{max_size => 1048576,strict_mode => false,version => 4}],[{file,"emqx_frame.erl"},{line,183}]},{emqx_frame,parse_frame,4,[{file,"emqx_frame.erl"},{line,163}]},{emqx_connection,parse_incoming,3,[{file,"emqx_connection.erl"},{line,551}]},{emqx_connection,handle_msg,2,[{file,"emqx_connection.erl"},{line,544}]},{emqx_connection,process_msg,3,[{file,"emqx_connection.erl"},{line,313}]},{proc_lib,wake_up,3,[{file,"proc_lib.erl"},{line,236}]}]
Frame data:<<0,40,19,132,95,132,0,0,0,0,0,0,0,2,0,1,134,160,0,0,0,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0>>
2022-04-11 06:06:10.554 [error] 10.100.245.128:47130 [MQTT] 
Parse failed for function_clause
[{emqx_frame,parse_packet,[{mqtt_packet_header,0,false,0,false},<<0,6,1,0,0,1,0,0,0,0,0,0,7,118,101,114,115,105,111,110,4,98,105,110,100,0,0,16,0,3>>,#{max_size => 1048576,strict_mode => false,version => 4}],[{file,"emqx_frame.erl"},{line,183}]},{emqx_frame,parse_frame,4,[{file,"emqx_frame.erl"},{line,163}]},{emqx_connection,parse_incoming,3,[{file,"emqx_connection.erl"},{line,551}]},{emqx_connection,handle_msg,2,[{file,"emqx_connection.erl"},{line,544}]},{emqx_connection,process_msg,3,[{file,"emqx_connection.erl"},{line,313}]},{proc_lib,wake_up,3,[{file,"proc_lib.erl"},{line,236}]}]
Frame data:<<0,30,0,6,1,0,0,1,0,0,0,0,0,0,7,118,101,114,115,105,111,110,4,98,105,110,100,0,0,16,0,3>>
2022-04-11 06:06:18.303 [error] 10.100.245.128:9297 [MQTT] 
Parse failed for {badmatch,<<>>}
[{emqx_frame,parse_packet,3,[{file,"emqx_frame.erl"},{line,196}]},{emqx_frame,parse_frame,4,[{file,"emqx_frame.erl"},{line,163}]},{emqx_connection,parse_incoming,3,[{file,"emqx_connection.erl"},{line,551}]},{emqx_connection,handle_msg,2,[{file,"emqx_connection.erl"},{line,544}]},{emqx_connection,process_msg,3,[{file,"emqx_connection.erl"},{line,313}]},{proc_lib,wake_up,3,[{file,"proc_lib.erl"},{line,236}]}]
Frame data:<<22,3,0,0,105,1,0,0,101,3,3,85,28,167,228,114,97,110,100,111,109,49,114,97,110,100,111,109,50,114,97,110,100,111,109,51,114,97,110,100,111,109,52,0,0,12,0,47,0,10,0,19,0,57,0,4,0,255,1,0,0,48,0,13,0,44,0,42,0,1,0,3,0,2,6,1,6,3,6,2,2,1,2,3,2,2,3,1,3,3,3,2,4,1,4,3,4,2,1,1,1,3,1,2,5,1,5,3,5,2>>
2022-04-11 06:06:28.566 [error] 10.100.245.128:47645 [MQTT] 
<img width="960" alt="exmq-err" src="https://user-images.githubusercontent.com/22384775/163128634-67dba089-ec63-4e61-bc03-673db5fac21a.png">

### Your environment

For EMQ X 4.3 or newer, please provide the log archive generated by [node_dump tool](https://github.com/emqx/emqx/blob/master/bin/node_dump) 

Otherwise please provide below info:
- EMQ X version (e.g. `emqx_ctl status`):4.3-rc.3
- If cluster (e.g. 3 X 4Core16GB):3X4C 16G (k8s cluster)
- Hardware configuration (e.g. `lscpu`):
- OS (e.g. `cat /etc/os-release`):
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

- Kernel (e.g. `uname -a`):
Linux etsme-k8s-m1 3.10.0-1127.19.1.el7.x86_64 #1 SMP Tue Aug 25 17:23:54 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

- Erlang/OTP version (in case you build emqx from source code): 
R23/11.1.8
- Others:
k8s:1.19.5
### LOG File

Missing log file can delay the handling of the issue.

**Comment by lafirest** [comment]
It looks like you are sending HTTP messages to the MQTT port

**Comment by kiddyt00** [comment]
> It looks like you are sending HTTP messages to the MQTT port

so can not send http message to mqtt port? it's not allowed?any solution to this scene

**Comment by zmstone** [comment]
http and mqtt are different protocols.

**Comment by zmstone** [comment]
If you want to try an rc release of emqx,
Please give the 5.0.0-rc.1 a try

**Comment by kiddyt00** [comment]
> If you want to try an rc release of emqx, Please give the 5.0.0-rc.1 a try

my purpose to let the device execute the command like "curl http://example.com/api",so I send the request body as a message through the emqx rpc channel，and let the device bash to execute the command "curl http://example.com/api",anyway I think it will work，but some message got the error ，I just want to know the way I did can work？

**Comment by zmstone** [comment]
Hi @kiddyt00 
if your requirement is to publish messages using HTTP API, you can try emqx 5.0's APIs.
here is an example, start EMQX, and visit this URL (change the ip address) to see the API specification (which is swagger).
`http://192.168.31.216:18083/api-docs/index.html#/publish/post_publish`

or execute this:
```
curl --user admin:public -X 'POST' \
  'http://192.168.31.216:18083/api/v5/publish' \
  -H 'accept: application/json' \
  -H 'Content-Type: application/json' \
  -d '{
  "topic": "api/example/topic",
  "qos": "0",
  "from": "api_example_client",
  "payload": "hello emqx api",
  "retain": false
}'
```
