### ISSUE TITLE
Application for cooperation from Goodrain open source community

### ISSUE THREAD

**Issue by zzzhangqi** [emqx/emqx#7609]
Hello,I'm from the open source community [Goodrain](https://github.com/goodrain).The open source project we operate is [Rainbond](https://github.com/goodrain/rainbond).Our [website](https://www.rainbond.com/).

We have many users using emqx.So we provide a choice for these users through Rainbond through our own application market mechanism.One-click deployment of emqx available for production.This kind of deployment is very popular with community users.

Therefore, a possibility of cooperation is hereby put forward,We are willing to submit an one-click deployment emqx document to your website or blog,Help more users who need both cloud native application management platform and emqx to understand this possibility and its convenience.

You can watch the way we worked with [Nacos](https://nacos.io/zh-cn/blog/use-nacos-with-rainbond.html) and [Apollo](https://www.apolloconfig.com/#/zh/deployment/third-party-tool-rainbond) in the past.

Looking forward to the reply from the operators of the emqx community!😚

**Comment by zmstone** [comment]
Hi @zzzhangqi 
you are welcome to submit a blog post draft as a pull request here: https://github.com/emqx/blog

**Comment by zmstone** [comment]
I'm closing this issue here
