### ISSUE TITLE
python端exhook插件开发时，怎么获取消息的from属性的值？

### ISSUE THREAD

**Issue by frh10** [emqx/emqx#7627]
环境信息

EMQX 版本：4.2.14
操作系统及版本：win10
其他
问题描述
exhook插件里是通过grpc连接python端的，在python的OnMessagePublish方法里能获取到发布的消息，现在我想知道消息的from是什么，怎么获取？

因为from是python的关键字，直接用message.from会报错；
如果用message[“from”]，又会报错’Message’ object is not subscriptable

**Comment by lafirest** [comment]
Please explain what 'From' means here, the publisher clientId or username or a function parameter ? It seems to be defined by your SDK
