### ISSUE TITLE
Dashboard ingress definition in helm chart is not compatible with AWS ALB

### ISSUE THREAD

**Issue by luzhkovvv** [emqx/emqx#7634]
### Subject of the issue
Helm chart dashboard ingress definition contains the following code:
```
      paths:
      - path: /
        {{- if (semverCompare ">=1.18-0" $.Capabilities.KubeVersion.GitVersion) }}
        pathType: ImplementationSpecific
        {{- end }}
```
`path: /` is 100% valid only for `pathType: Prefix` . For `ImplementationSpecific` it depends on ingress controller. For nginx it is ok, but for AWS ALB `pathType: ImplementationSpecific` requires `path: /*` to be specified to get a working configuration.
Either `path` or `pathType` should be made configurable via values to make it compatible with AWS ALB (and probably extend compatibility with some other ingress controllers).

### Your environment

For EMQ X 4.3 or newer, please provide the log archive generated by running `node_dump` (The `node_dump` script can be found in `/<path-to-installation-of-emqx>/bin` if you installed emqx from source or zip ball).

- EMQ X version (e.g. `emqx_ctl status`):  4.4.2 (the same for master branch chart)
- Hardware configuration (e.g. `lscpu`):
- OS (e.g. `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Erlang/OTP version (in case you build emqx from source code): 
- Others: AWS EKS k8s 1.21, aws load balancer controller 2.2.1

### Steps to reproduce
Enable dashboard ingress via vaules, specify ALB ingress class using annotations and deploy helm chart in AWS EKS.

### Expected behaviour
Dashboard is working

### Actual behaviour
Only the root page of the dashboard is loaded, with all other resources getting default response, because AWS ALB only performs full path matching with current config, not matching of prefixes.

**Comment by zmstone** [comment]
@Rory-Z could you help to have a look ?

**Comment by Rory-Z** [comment]
Sure, I will create a PR later
