### ISSUE TITLE
http ACL和认证插件能够解析json响应来判断授权状态

### ISSUE THREAD

**Issue by cloudicen** [emqx/emqx#7638]
**What would you like to be added/modified**:
http ACL和认证插件能够自定义授权响应处理方法。比如解析json格式的响应，针对响应体的某些返回字段来判断授权状态。
**Why is this needed**:
许多框架拥有统一的http响应，其HTTP Status Code统一设置为200，具体响应的状态是通过在json响应体中设置code等字段体现的，这样与emqx的认证插件集成的时候就很麻烦。

**Comment by lafirest** [comment]
Thanks for your input, we'll discuss this

**Comment by wivwiv** [comment]
The http-auth has always been the plug-in with the most users. Considering the compatibility, we will not change the way it is used in 4.x. If you want to know how to implement authentication in your HTTP framework, you can tell us what framework you are using.

We've implemented this suggestion in the upcoming 5.0 release, and we hope it helps you.

**Comment by cloudicen** [comment]
Appreciate that ! And currently I just use redis-auth instead of adding a middle layer.
