### ISSUE TITLE
Error During Hot Upgrade From 4.2.3 to 4.4.3.

### ISSUE THREAD

**Issue by holopekochan** [emqx/emqx#7659]
I am attempting to upgrade my emqx from 4.2.3 to 4.4.3.
I am using root for the upgrade, however, I am stuck. Cannot even do uninstall as well.
Does anyone have the same issue? How to solve the problem? Thanks

```
root@abc:/usr/lib/emqx/releases# sudo emqx uninstall 4.4.3
Release 4.4.3 is marked unpacked, uninstalling it
ERROR: release_handler:remove_release failed: eacces
root@abc:/usr/lib/emqx/releases# sudo emqx upgrade 4.4.3
Release 4.4.3 is already unpacked, now installing.
escript: exception error: no match of right hand side value {error,eacces}
root@abc:/usr/lib/emqx/releases# sudo emqx versions
Installed versions:
* 4.4.3	unpacked
* 4.2.3	permanent
```

**Comment by zmstone** [comment]
Hi @holopekochan this upgrade path is not supported.
For hot upgrade, it’s only possible to upgrade between patch versions, e.g. from 4.4.0 to 4.4.3
