### ISSUE TITLE
Error while running ./bin/emqx_ctl status

### ISSUE THREAD

**Issue by naikvidish** [emqx/emqx#7682]
### Subject of the support

I downloaded the prebuilt zip for windows (`curl https://www.emqx.com/en/downloads/broker/4.4.3/emqx-4.4.3-otp24.2.1-windows-amd64.zip -o emqx.zip`)
Unzipped and ran `./bin/emqx start`
Tried checking the status with `./bin/emqx_ctl status` but got this error:

```
escript: exception error: no match of right hand side value false
  in function  nodetool__escript__1650__412329__334798__5:add_libs_dir/0 (C:\Users\Administrator\emqx\emqx\bin\nodetool, line 293)
  in call from nodetool__escript__1650__412329__334798__5:main/1 (C:\Users\Administrator\emqx\emqx\bin\nodetool, line 22)
  in call from escript:run/2 (escript.erl, line 750)
  in call from escript:start/1 (escript.erl, line 277)
  in call from init:start_em/1 (init.erl, line 1191)
  in call from init:do_boot/3 (init.erl, line 889)
```

### Your environment

For EMQ X 4.3 or newer, please provide the log archive generated by [node_dump tool](https://github.com/emqx/emqx/blob/master/bin/node_dump) 

Otherwise please provide below info:
- EMQ X version (e.g. `emqx_ctl status`): (Downloaded 4.4.3)
- If cluster (e.g. 3 X 4Core16GB): N/A
- Hardware configuration (e.g. `lscpu`):
- OS (e.g. `cat /etc/os-release`): Windows server 2019 (AWS EC2)
- Kernel (e.g. `uname -a`):
- Erlang/OTP version (in case you build emqx from source code): 
- Others:

### LOG File

Missing log file can delay the handling of the issue.

**Comment by lafirest** [comment]
Using './bin/emqx start' maybe not start correctly and without notification. Please try using the './bin/emqx console' to start EMQX, it will output errors during startup

**Comment by naikvidish** [comment]
Thanks for the response!

It looks like powershell is having issues running `.\bin\emqx_ctl status`. 
Same thing worked on cmd and outputs `Node 'emqx@127.0.0.1' 4.4.3 is started`.

Thanks!

**Comment by naikvidish** [comment]
I also have one more question. 
I tried to build emqx from source in windows and got this as the last few lines of output:
```
Assembling release emqx-4.4.3...
--
There are missing function calls in the release.
Make sure all applications needed at runtime are included in the release.
emqx_misc:ipv6_probe/1 calls undefined function gen_tcp:ipv6_probe/0
emqx_passwd:hash/2 calls undefined function bcrypt:hashpw/2
Release successfully assembled: _build/emqx/rel/emqx

```

Can you tell me what am I missing here? 
Running the broker works fine and it I get the output that it is started in `emqx_ctl status` (in cmd).

**Comment by naikvidish** [comment]
Thanks for the replies @lafirest! 
Closing this issue
