### ISSUE TITLE
Unable to connect to websocket 

### ISSUE THREAD

**Issue by inteldon** [emqx/emqx#7684]
Hi I'm using Ubuntu 20.04 with EMQX version 4.3.5 

I used the default emqx.conf configuration and I can't connect to the websocket. I tried several clients through web browsers and the EMQX admin, but the result was the same. See below for a picture of the EMQX dashboard. 

![image](https://user-images.githubusercontent.com/28794155/164135545-4f923fcd-cb92-4e59-9ba7-d0886d6b0c85.png)

All connections to mqtt port 1883 is working, just websocket isn't working, is there documentation or configuration recommendation to make it work better? Please help. 

Thanks

**Comment by lafirest** [comment]
Please check first if port 8083  is open and in listening

**Comment by inteldon** [comment]
> Please check first if port 8083 is open and in listening

Hi checked my port was open, now I use port 8085 (updated that on my emqx.conf) and I tested all my firewall rules in ubuntu and my server host, and the port is open. I used a third party port checker and it's open, please see the screenshot below. 

![image](https://user-images.githubusercontent.com/28794155/164844194-a7560208-b5c2-4456-b033-fcb6c7be6d98.png)


Thanks

**Comment by zmstone** [comment]
Do you have https enabled for the dashboard?
Otherwise some debug level logs will help to find the cause

**Comment by inteldon** [comment]
No, this is a test dashboard using only http, will upgrade to https later. Are there particular settings in emqx.conf that I need to change? 

I used the debug mode and here are my observations: 
- I can connect to ws through the emqx dashboard 
- No external client can connect to ws://mywebsite.com:8085

To see if my server setup was blocking ws type connections, I tried a test and wrote a websocket server using nodejs on port 8087, then tried connecting from external clients, the observation was:  
- All external clients can connect to a test ws://mywebsite.com:8087 that I wrote using nodejs 

So I verified that my firewall rules are ok, and that my server setup is not blocking websocket connections, they are only blocked on the EMQX server. 

Can you please help in adjusting the settings to allow for those connections?

**Comment by zmstone** [comment]
Could you share the debug logs when connecting from external clients?

**Comment by inteldon** [comment]
The issue is resolved. After several tests I found out that my url string was not being parsed correctly by the mqtt client. It is working now. Thanks.

**Comment by V4yukon** [comment]
what's the operation solved the issue,can you share for me ?Thank you, please.
