### ISSUE TITLE
How to bridge EMQ to mosquitto?

### ISSUE THREAD

**Issue by shon-penteer** [emqx/emqx#769]
#### Environment

- OS: CentOS
- EMQ: v2.0-rc.3

#### Description

Hi,

Is it possible to bridge EMQ to Mosquitto?

Publisher --> EMQ Broker --[Bridge]--> Mosquitto Broker --> Subscriber

In the docs I only saw how to bridge Mosquitto to EMQ.

Thanks,
Shon

**Comment by turtleDeng** [comment]
You can find how to bridge mosquitto here http://emqtt.io/docs/v2/bridge.html

**Comment by emqplus** [comment]
@shon-penteer  Cannot bridge EMQ to Mosquitto.

**Comment by shon-penteer** [comment]
Thanks,
@emqplus Will this feature be available in the near future?

**Comment by emqplus** [comment]
@shon-penteer We could support this feature if more users star this issue, I think.

**Comment by shon-penteer** [comment]
Is there a workaround I can use meanwhile, or a direction I can be pointed to solve the issue of bridging EMQ to Mosquitto myself?

**Comment by emqplus** [comment]
@shon-penteer Write a python bridge: EMQ -> Python Bridge -> Mosquitto

**Comment by pritstift** [comment]
Have the same Issue. Bridged rsmb to EMQ and wanted to bridge EMQ to rsmb also, since the mqtt-sn plugin seems not like working correctly.

**Comment by pritstift** [comment]
Just for the case someone comes across while trying to EMQ to rsmb (And maybe this should be added to the documentation):

You can make rsmb subscribe topics on the EMQ broker like in the following way(see [rsmb documentation](https://github.com/MichalFoksa/rsmb/blob/master/rsmb/doc/gettingstarted.htm)
```
connection emqttd
        address 127.0.0.1:1883
        topic r/# in "" ""
        topic w/# out "" ""
```

**Comment by zhengyupan** [comment]
Hi @shon-penteer , this function is implemented in V3.0. From this version on, the EQM X can connect to other MQTT broker using a bridge. Currently the V3 is in beta phase, you can check it out and try. 
The configuration of bridge is in the emqx.conf file, includes the broker address, port, clientid, prefix,  ssl-setups and etc. The file is quite self-explaining. If there is any uncertainty or bugs found please contact us again. Thanks!

============
## Bridge address: node name for local bridge, host:port for remote.
##
## Value: String
## Example: emqx@127.0.0.1,  127.0.0.1:1883
bridge.edge.address = 127.0.0.1:1883

## Protocol version of the bridge.
##
## Value: Enum
## - mqtt5
## - mqtt3
bridge.edge.proto_ver = mqtt3

## The ClientId of a remote bridge.
##
## Value: String
bridge.edge.client_id = bridge_edge

## The Clean start flag of a remote bridge.
##
## Value: boolean
bridge.edge.clean_start = false

## The username for a remote bridge.
##
## Value: String
bridge.edge.username = user

## The password for a remote bridge.
##
## Value: String
bridge.edge.password = passwd

## Mountpoint of the bridge.
##
## Value: String
## bridge.edge.mountpoint = bridge/edge/

## Ping interval of a down bridge.
##
## Value: Duration
## Default: 10 seconds
bridge.edge.keepalive = 10s

## Subscriptions of the bridge topic.
##
## Value: String
bridge.edge.subscription.1.topic = #

## Subscriptions of the bridge qos.
##
## Value: Number
bridge.edge.subscription.1.qos = 1

## The pending message queue of a bridge.
##
## Value: Number
bridge.edge.max_pending_messages = 10000

## Start type of the bridge.
##
## Value: enum
## manual
## auto
bridge.edge.start_type = manual

## Bridge reconnect count.
##
## Value: Number
bridge.edge.reconnect_count = 10

## Bridge reconnect time.
##
## Value: Duration
## Default: 30 seconds
bridge.edge.reconnect_time = 30s

## PEM-encoded CA certificates of the bridge.
##
## Value: File
## bridge.edge.cacertfile = cacert.pem

## SSL Certfile of the bridge.
##
## Value: File
## bridge.edge.certfile = cert.pem

## SSL Keyfile of the bridge.
##
## Value: File
## bridge.edge.keyfile = key.pem

## SSL Ciphers used by the bridge.
##
## Value: String
## bridge.edge.ciphers = ECDHE-ECDSA-AES256-GCM-SHA384,ECDHE-RSA-AES256-GCM-SHA384

## TLS versions used by the bridge.
##
## Value: String
## bridge.edge.tls_versions = tlsv1.2,tlsv1.1,tlsv1

**Comment by dophlin** [comment]
@zhengyupan I cannot find the configuration you pointed in the emqx.conf. Is it still supported to bridge emqx to mosquitto through emqx.conf?

**Comment by phanimahesh** [comment]
Yes. The value after bridge can be anything, all these settings together define a bridge named edge. The default configuration has commented bridges with names aws, azure etc. Use one of those as a template.
