### ISSUE TITLE
Where can i find a guide / manual for EMQX v5.x?

### ISSUE THREAD

**Issue by jayjupdhig** [emqx/emqx#7757]
Is it similar version to 4.x? (not 100% at all i.m.o.)
-> https://www.emqx.io/docs/en/v4.4/advanced/acl-file.html

More infos about my question HERE:
-> https://github.com/emqx/emqx/issues/7158 

Thank you very very much for your feedbacks! :-)

**Comment by zmstone** [comment]
Hi. The docs are still under construction.
Judging by the timeline, we’ll likely have to release it before the docs are fully ready.
The 5.0 version has acl “file” configureable from the dashboard UI directly. 
you should be able to find it in “Access Control “ -> “Authorzation” -> Add

**Comment by jayjupdhig** [comment]
Thank you very much for your feedback!! :-)

**Comment by zmstone** [comment]
I take that as issue resolved :)
