### ISSUE TITLE
An improvement for loging

### ISSUE THREAD

**Issue by congleetea** [emqx/emqx#776]
@emqplus An improvement for loging:
https://github.com/emqtt/emqttd/blob/master/include/emqttd_internal.hrl#L37~L53 and https://github.com/emqtt/emqttd/blob/master/src/emqttd_ws_client.erl#L123. 

I think it is better to locate the code if output the module and lines like blow:
`
 lager:error("~p:~p:Unexpected Request: ~p", [?MODULE, ?LINE, Req]),
`

**Comment by turtleDeng** [comment]
Log directory below the file, will record the module and line
