### ISSUE TITLE
Bug: v5 API /api/v5/authentication/password_based:redis/status return 500

### ISSUE THREAD

**Issue by sekfung** [emqx/emqx#7763]
### Subject of the issue
Describe your issue here.

### Your environment

For EMQ X 4.3 or newer, please provide the log archive generated by running `node_dump` (The `node_dump` script can be found in `/<path-to-installation-of-emqx>/bin` if you installed emqx from source or zip ball).

- EMQ X version (e.g. `emqx_ctl status`):  master latest
- Hardware configuration (e.g. `lscpu`):
- OS (e.g. `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Erlang/OTP version (in case you build emqx from source code): 
- Others:

### Steps to reproduce
1. Create Authentication  and select redis as backend
2. Set redis client config, and conencted
3. Refresh browser,  it tips  500 Network error

### Expected behaviour
return 200 ok

### Actual behaviour
![image](https://user-images.githubusercontent.com/43331641/165093338-7aa04312-346e-4259-8b80-4c720fd2596d.png)

![image](https://user-images.githubusercontent.com/43331641/165093600-21c14316-748b-4674-9754-51b4f79907f7.png)

**Error Response**
```log
invalid json term: #{metrics => {error_info,#{module => erl_stdlib_errors}},
                     node_metrics =>
                         [#{metrics =>
                                #{failed => 0,matched => 0,rate => 0.0,
                                  rate_last5m => 0.0,rate_max => 0.0,
                                  success => 0},
                            node =>
                                'emqx-wjgsqp@emqx-wjgsqp-0.emqx-wjgsqp-headless.emqx.svc.cluster.local'},
                          #{metrics =>
                                #{failed => 0,matched => 0,rate => 0.0,
                                  rate_last5m => 0.0,rate_max => 0.0,
                                  success => 0},
                            node =>
                                'emqx-wjgsqp@emqx-wjgsqp-1.emqx-wjgsqp-headless.emqx.svc.cluster.local'},
                          #{metrics =>
                                #{failed => 0,matched => 0,rate => 0.0,
                                  rate_last5m => 0.0,rate_max => 0.0,
                                  success => 0},
                            node =>
                                'emqx-wjgsqp@emqx-wjgsqp-2.emqx-wjgsqp-headless.emqx.svc.cluster.local'}],
                     node_status =>
                         [#{node =>
                                'emqx-wjgsqp@emqx-wjgsqp-0.emqx-wjgsqp-headless.emqx.svc.cluster.local',
                            status => connected},
                          #{node =>
                                'emqx-wjgsqp@emqx-wjgsqp-1.emqx-wjgsqp-headless.emqx.svc.cluster.local',
                            status => connected},
                          #{node =>
                                'emqx-wjgsqp@emqx-wjgsqp-2.emqx-wjgsqp-headless.emqx.svc.cluster.local',
                            status => connected}],
                     status => connected}
```

Missing log file can delay the handling of the issue.

**Comment by lafirest** [comment]
500 means some error occur in related codes, you could check EMQX logs to find where and what happened, or you can paste it here for us to help you

**Comment by zmstone** [comment]
@sekfung please pull this patch to test: https://github.com/emqx/emqx/pull/7775

**Comment by sekfung** [comment]
> @sekfung please pull this patch to test: #7775

thx, it solved.

**Comment by sekfung** [comment]
@zmstone Sorry I could not find any error message in console or log file,  even if i had rollback my code

**Comment by zmstone** [comment]
thank you for the feedback, closed the issue for now
