### ISSUE TITLE
Messages are being dropped. Want to know what factors it depends on?

### ISSUE THREAD

**Issue by bchhabra2490** [emqx/emqx#7776]
### Subject of the issue
Messages are being dropped by emqx broker. I Want to know what factors it depends on? 

<img width="1214" alt="image" src="https://user-images.githubusercontent.com/9590073/165301953-88a90671-dcca-4b30-ba84-57a7951050c2.png">

### Your environment

- EMQ X version (e.g. `emqx_ctl status`):  3.2.3
- Hardware configuration (e.g. `lscpu`): AWS EC2 t3.medium
- OS (e.g. `cat /etc/os-release`): ubuntu
- Kernel (e.g. `uname -a`):Linux  #76~18.04.1-Ubuntu SMP Mon Mar 28 17:49:57 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
- Erlang/OTP version (in case you build emqx from source code): R21/10.3.5.4
- Others:
 
What are the configuration keys in emqx.conf I should change to decrease drop rate?
<img width="1229" alt="image" src="https://user-images.githubusercontent.com/9590073/165302587-c13d3aa6-3c65-4c6e-8e5d-83bd3f53227b.png">

**Comment by zmstone** [comment]
a message is dropped when there is no subscriber found for this message.

**Comment by zmstone** [comment]
subscribers may disconnect for many different reasons
e.g. 
* heartbeat not sent
* network issue

**Comment by gbrehmer** [comment]
@bchhabra2490 prometheus counters contains the different reasons:
```
# TYPE emqx_delivery_dropped_no_local counter
emqx_delivery_dropped_no_local 0
# TYPE emqx_delivery_dropped_too_large counter
emqx_delivery_dropped_too_large 0
# TYPE emqx_delivery_dropped_qos0_msg counter
emqx_delivery_dropped_qos0_msg 0
# TYPE emqx_delivery_dropped_queue_full counter
emqx_delivery_dropped_queue_full 0
# TYPE emqx_delivery_dropped_expired counter
emqx_delivery_dropped_expired 0
```
