### ISSUE TITLE
Inconsistent data of concurrent paging query client

### ISSUE THREAD

**Issue by sysword** [emqx/emqx#7870]
### Subject of the issue
    因为客户端数量比较多，所以进行了分页，第一次查询获得数量，每次limit 1000，计算页数之后并发查询每一页，使用过程中发现并发请求返回的数据不一致，甚至并发请求同一页时返回的数据也不一致

```
并发查询同一页
index1: device-133-1013 device-133-1019 device-133-102 ...
index2: device-10.162.66.133-101 device-133-1018 device-133-1020 ...
index3: device-133-1013 device-133-1019 device-133-102 ...
index4: device-133-1013 device-133-1019 device-133-102 ...
index5: device-10.162.66.133-101 device-133-1018 device-133-1020 ...
```

### Your environment

- EMQ X version (e.g. `emqx_ctl status`):  4.3.11

### Steps to reproduce
并发分页请求之后排序进行对比

### Expected behaviour
请求正常，获得总页数之后并发查询能够查询到全部clients

**Comment by HJianBo** [comment]
Since here the data is obtained by querying from each node on the cluster separately. So when multiple queries are made, if a time lag exists, the returned data is likely to be different.

**Comment by zmstone** [comment]
Thank you for the clarification @HJianBo .
Hope this answers your questions?
Closing this issue as it’s not actionable.

**Comment by sysword** [comment]
@HJianBo @zmstone thanks for the answer, but if i want to query all the clients, how can i accomplish that? query page by page is much slower ?

**Comment by sysword** [comment]
i tested if i make concurrent paging query client to same node always, the result num is correct, can you help me confirm whether this is expected？

**Comment by zmstone** [comment]
The clients may come and go at any time. I’m afraid there is always a risk of missing some clients by enumerating the clients (page or not doesn’t really make a big difference).
The underlying issue is the lack of an atomic snapshot of all client ids at a given time.
