### ISSUE TITLE
Fuzzy matching mechanism problem

### ISSUE THREAD

**Issue by ZHOUAXING927** [emqx/emqx#7893]
### Subject of the issue

模糊匹配机制问题 
Fuzzy matching mechanism problem

### Steps to reproduce
![QUF {3V{_{ {K(47@TLDBS7](https://user-images.githubusercontent.com/59408787/167236930-7ac5749f-e414-4caf-b612-f64e9754c180.jpg)
![SPMAR5V~)J@$_%0RI29ZVQ6](https://user-images.githubusercontent.com/59408787/167236935-949f448b-0249-4d99-8258-d79f8c39fabf.jpg)
### Expected behaviour
期望得到：每个模糊匹配收到一条.
expect  : One is received for each fuzzy match.

### Actual behaviour
实际得到：每个模糊匹配收到了三条.
actual:  Three were received for each fuzzy match.

**Comment by lafirest** [comment]
I think maybe what you want is '+'  not  '#'?
The '#' means match any remaining part

**Comment by ZHOUAXING927** [comment]
> 
我知道 '#'代表全匹配
可是我 发送一次消息，应该是接收到三次，
我希望得到是，发送一条消息，每个订阅拿到一次，而不是每个订阅拿到三次。
The '#' means match any remaining part
I know ,
But is it reasonable to send one message and receive nine?
I hope it should be three, one for each subscription, not three.

**Comment by ZHOUAXING927** [comment]
> I think maybe what you want is '+' not '#'? The '#' means match any remaining part

假设我现在必须这样匹配订阅，有什么办法可以得到我想要的吗？
Assuming I have to match subscriptions like this, is there any way I can get what I want?

**Comment by lafirest** [comment]
Do you mean:
1. You have a subscriber, and it subscribes to three fuzzy topics:
   a. 110/#
   b. 110/110/#
   c. 110/110/110/#
2. You have another publisher, and it publishes a message with the topic 110/110/110/110
3.  At last you got three messages per fuzzy topic?

**Comment by lafirest** [comment]
I just tested with MQTTX and EMQX 5.0 and can't reproduce what you said.
Could you retry this with MQTTX?
https://mqttx.app/

**Comment by ZHOUAXING927** [comment]
> 


> I just tested with MQTTX and EMQX 5.0 and can't reproduce what you said. Could you retry this with MQTTX? https://mqttx.app/
![image](https://user-images.githubusercontent.com/59408787/167243434-6ceee9b7-87bc-43b4-87ea-43545aae9936.png)


结果是一样的
The result is the same.

**Comment by ZHOUAXING927** [comment]
emqx version: 4.4.3 for Windows
MQTT version:
![image](https://user-images.githubusercontent.com/59408787/167243500-9dce1f05-a678-4726-b64e-d747c6577873.png)

**Comment by lafirest** [comment]
> > 
> 
> > I just tested with MQTTX and EMQX 5.0 and can't reproduce what you said. Could you retry this with MQTTX? https://mqttx.app/
> > ![image](https://user-images.githubusercontent.com/59408787/167243434-6ceee9b7-87bc-43b4-87ea-43545aae9936.png)
> 
> 结果是一样的 The result is the same.

Sorry, I don't understand what your expectations are.
You subscribe to three fuzzy topics and got three matched messages, everything is correct here.
I guess what you want is to simplify the theme?
For example simplify these three topics:  '110/#'  '110/110/#' '110/110/110/#' as one and, only got one matched message?

**Comment by ZHOUAXING927** [comment]
Maybe you can try to reproduce my problem again.

1. Subscribe  "110/#"    "110/110/#"    "110/110/110/#"
2. Pubilsh   ”110/110/110/110“    a  message  ("Pubilsh"  only once).
3.  You will find "110/#" received three ，  "110/110/#" received three ， "110/110/110/#" received three .
4. Is this reasonable?

**Comment by lafirest** [comment]
> 2\. 110/110/110/110

<img width="832" alt="image" src="https://user-images.githubusercontent.com/22971499/167245413-bc5721d3-1414-4296-8908-ea8d0d07f644.png">
As you can see everything is correct.
I tested with EMQX version 4.4.3 and Erlang OTP 24 on macOS.
Do you enable some other plugins or modules?
Could you please record the screen and post it at https://askemq.com/ with some detailed information, thanks

**Comment by ZHOUAXING927** [comment]
Didn't you send one and received it three ？
Maybe this software is more intuitive
http://www.mqttfx.jensd.de/

**Comment by HJianBo** [comment]
@ZHOUAXING927 How about to use Wireshark to capture the more transmission details? It is more useful to identify how many messages delivered for the subscribed client

**Comment by lafirest** [comment]
> Didn't you send one and received it three ？ Maybe this software is more intuitive http://www.mqttfx.jensd.de/

<img width="1137" alt="image" src="https://user-images.githubusercontent.com/22971499/167336291-75bceb6b-36c5-4782-bac7-b3a09e6e5953.png">

I'm sure everything is correct here, you can see this log screenshot, here correctly received 3 messages, no more, no less.
