### ISSUE TITLE
How can I dynamically cancel a client topic subscription in real time?

### ISSUE THREAD

**Issue by renwanly** [emqx/emqx#791]
#### Environment

- OS: CentOS 7
- Erlang/OTP: 
- EMQ: 2.0

#### Description
When a client subscribes to a topic, the ACL allows it to subscribe. The client keeps the session alive. For some reason, the client's subscription authorization needs to be retracted. How can I tell EMQ to cancel the subscription for this client?
REF #783 

Furthermore, if the client first publishes a message on a topic, the ACL allows it to be published. But for some reason canceled its publishing rights, how to clear the ACL for this client's authorization cache?

Chinese:
客户端订阅一个主题，ACL允许其订阅。该客户端保持会话。因某种原因，此客户端对此主题的订阅权需要回收。我如何告知EMQ取消此客户端对此主题的订阅呢？
参考 #783，可能是我没有在前一问题中表述清楚导致被误解。

进一步，如果某客户端在一个主题中发布了一条消息，此时ACL允许其发布。此后，因某种原因需要取消此客户端对此主题的消息发布权限。如何告知EMQ仅针对此客户端消除授权缓存？

**Comment by renwanly** [comment]
Furthermore, if the client first publishes a message on a topic, the ACL allows it to be published. But for some reason canceled its publishing rights, how to clear the ACL for this client's authorization cache?

**Comment by zhengyupan** [comment]
Hi @renwanly ,
you can use rest api to unsbu a topic, please refer to this link: https://developer.emqx.io/docs/emq/v3/en/rest.html#publish-subscribe
