### ISSUE TITLE
Action Handler headers are reset to default when editing

### ISSUE THREAD

**Issue by CodyErekson** [emqx/emqx#7924]
### Subject of the issue
When I edit an existing rule, the form does not populate with the existing headers, so when it is saved the headers are overwritten with the default.

### Your environment

For EMQ X 4.3 or newer, please provide the log archive generated by running `node_dump` (The `node_dump` script can be found in `/<path-to-installation-of-emqx>/bin` if you installed emqx from source or zip ball).

- EMQ X version (e.g. `emqx_ctl status`): 4.4.1
- Hardware configuration (e.g. `lscpu`): Cluster of 2x AWS EC2 t2-medium
- OS (e.g. `cat /etc/os-release`): Debian
- Kernel (e.g. `uname -a`): Linux node2.mqtt.ffly.net 4.19.0-19-cloud-amd64 #1 SMP Debian 4.19.232-1 (2022-03-07) x86_64 GNU/Linux
- Erlang/OTP version (in case you build emqx from source code): 
- Others:

### Steps to reproduce
Create a rule that has a 'data_to_webserver' action handler. Set some header values. Confirm the settings, then edit the action handler. 

### Expected behaviour
The contents of the header form will include all previously defined headers.

### Actual behaviour
The contents of the header form will have reverted to default, containing only "content-type:application/json"
![Screenshot from 2022-05-11 12-02-22](https://user-images.githubusercontent.com/1250796/167927202-d592a02a-aa0c-45b1-9cb5-1dba9e30ca87.png)

**Comment by zhongwencool** [comment]
Already fix in `v4.4.3` and `v4.3.14`.
Please try the latest version.
