### ISSUE TITLE
Publish was broken by timeout error after a few publish. Happens only when sending data on multiple topics

### ISSUE THREAD

**Issue by melgo-tb** [emqx/emqx#7934]
I have an application which streams real time financial data when I am trying to publish data on a common topic it is working without any issues, But when I try publishing using a dynamic topic based on  the data after a few seconds the publish keeps timing out (30 secs). I am using emqx (4.3) as a broker. 

`func onTick(tick kitemodels.Tick) {

	instr := instrMap[fmt.Sprint(tick.InstrumentToken)]
	tickdata := appdata.TickData{	
		Timestamp:          tick.Timestamp,
		LastTradeTime:      tick.LastTradeTime,
		LastPrice:          tick.LastPrice,
		Symbol:             instr,
	}

	go pubsub.Publish(instr, tickdata)

}
`
```
func Publish(topic string, tickdata interface{}) {
	start := time.Now()
	b, err := json.Marshal(tickdata)
	if err != nil {
		fmt.Println(err)
		return
	}
	token := client.Publish(topic, 1, false, b)
	go func() {
		_ = token.Wait()
		if token.Error() != nil {
			fmt.Println("Error While publish", token.Error())
		}
	}()
	elapsed := time.Since(start)
	log.Printf("Publish took %s ", elapsed)
}
```
 
Is is something to do with the broker configuration, I had checked for rate limits but there was none set

**Comment by zmstone** [comment]
Could you share some of the topics in use for our reference?
Also, how big is the payload? And at what rate is it published?

**Comment by zmstone** [comment]
Also, QoS in use?

**Comment by zmstone** [comment]
Could you enable debug level logging in EMQX and share the logs?

**Comment by melgo-tb** [comment]
@zmstone

**Comment by melgo-tb** [comment]
Resting the auth settings has fixed the issue, @zmstone thanks for helping out!
