### ISSUE TITLE
Centos + Plesk + Docker - WSS not connect

### ISSUE THREAD

**Issue by erennyuksell** [emqx/emqx#7936]
### Subject of the support
when I try from the dashboard to connect over wss it's not connecting
![1](https://user-images.githubusercontent.com/43651689/168068142-e16a3def-39a7-4efd-b6bf-586eb2a38d9d.PNG)
![2](https://user-images.githubusercontent.com/43651689/168061845-f2224cf7-6b7b-48bc-9255-891d1473ab21.PNG)

### Your environment
- EMQ X version (e.g. `emqx_ctl status`):4.4.3
- OS (e.g. `cat /etc/os-release`):Centos + Plesk + Docker
- Kernel (e.g. `uname -a`):
- Erlang/OTP version (in case you build emqx from source code): 
- Others:

### LOG File

https://pastebin.pl/view/9eeb8195

**Comment by erennyuksell** [comment]
I changed the log file.

**Comment by ieQu1** [comment]
Hello,
Sorry for late responce. Looking at the errors:
```
{cacertfile,"/usr/local/psa/var/modules/letsencrypt/etc/live/example.com/chain.pem",{error,enoent}}}},
```
`enoent` indicates that the file doesn't exist. Could you verify that `/usr/local/psa/var/modules/letsencrypt/etc/live/example.com/chain.pem` file exists on the server?

**Comment by erennyuksell** [comment]
> Hello, Sorry for late responce. Looking at the errors:
> 
> ```
> {cacertfile,"/usr/local/psa/var/modules/letsencrypt/etc/live/example.com/chain.pem",{error,enoent}}}},
> ```
> 
> `enoent` indicates that the file doesn't exist. Could you verify that `/usr/local/psa/var/modules/letsencrypt/etc/live/example.com/chain.pem` file exists on the server?

Hello,
Thanks for your answer.  
my new log file https://pastebin.pl/view/f122a8bd and verification that the file is on the server
![Ekran Alıntısı](https://user-images.githubusercontent.com/43651689/169809838-d1761767-b0e6-4bb6-91d9-07ee62fdc489.PNG)

**Comment by erennyuksell** [comment]
I solved the problem. It's related to docker volume mapping. Container could not access certificate files.
