### ISSUE TITLE
Please publish latest RC's to docker-hub

### ISSUE THREAD

**Issue by voycey** [emqx/emqx#7976]
### What would you like to be added or enhanced?

Current Release Candidates are not pushed to Docker Hub - please publish these to Docker Hub but don't update ":latest" tag to point to them

### Why is this needed?

Those of us deploying via Helm we have to manage local charts which can diverge from the published material over time, it also makes the ability to deploy to clouds much easier.

**Comment by troyweber** [comment]
I am looking for the same thing!

**Comment by tigercl** [comment]
@voycey @troyweber Thanks for your feedback, we will consider publishing the RC for major and minor versions to Docker Hub so you can try it out early.

**Comment by Rory-Z** [comment]
@tigercl @zmstone Do we need to publish the RC version of EMQX 4 to the docker hub ? Or just only EMQX 5

**Comment by zmstone** [comment]
We can publish all rc releases

**Comment by Rory-Z** [comment]
> We can publish all rc releases

Ping @tigercl

**Comment by voycey** [comment]
@tigercl @Rory-Z Can this be looked at please? Also can all recent releases be published via Helm? 5.0.6 is not available via https://repos.emqx.io/charts

**Comment by tigercl** [comment]
@voycey Hi, we will fix it in 5.0.7.

**Comment by id** [comment]
Pre-release versions of emqx/emqx docker image are now published automatically to docker hub.
Helm chart releases are pushed automatically to the charts repo with each release.
