### ISSUE TITLE
Rules do not run on MQTTv5 (Invalid ejson) - User Properties not supported?

### ISSUE THREAD

**Issue by voycey** [emqx/emqx#7978]
### What happened?

Everything works with MQTT v3.1.1 - there are no user properties being included here.

However when I switch to MQTT v5 and send a User Property I get the following errors:

```
emqx
2022-05-18T02:20:31.839185+00:00 [error] office-mqtt-3@10.10.0.5:36131 Take action <<"data_to_webserver_1652840379149763857">> failed, continue next action, reason: {error,{invalid_ejson,{<<"hash">>,<<"d138993c91f833602075e625ba657aa40f0970ceaf1b29ff5f5d743d757b4bd4">>}},[{jiffy,encode,2,[{file,"jiffy.erl"},{line,99}]},{emqx_json,encode,1,[{file,"emqx_json.erl"},{line,58}]},{emqx_web_hook_actions,on_action_data_to_webserver,2,[{file,"emqx_web_hook_actions.erl"},{line,261}]},{emqx_rule_runtime,take_action,5,[{file,"emqx_rule_runtime.erl"},{line,263}]},{emqx_rule_runtime,'-take_actions/4-lc$^0/1-0-',4,[{file,"emqx_rule_runtime.erl"},{line,254}]},{emqx_rule_runtime,do_apply_rule,2,[{file,"emqx_rule_runtime.erl"},{line,131}]},{emqx_rule_runtime,apply_rule,2,[{file,"emqx_rule_runtime.erl"},{line,64}]},{emqx_rule_runtime,apply_rule_discard_result,2,[{file,"emqx_rule_runtime.erl"},{line,58}]},{emqx_rule_runtime,apply_rules,2,[{file,"emqx_rule_runtime.erl"},{line,54}]},{emqx_rule_events,on_message_publish,2,[{file,"emqx_rule_events.erl"},{line,101}]},{emqx_hooks,safe_execute,2,[{file,"emqx_hooks.erl"},{line,207}]},{emqx_hooks,do_run_fold,3,[{file,"emqx_hooks.erl"},{line,186}]},{emqx_broker,publish,1,[{file,"emqx_broker.erl"},{line,201}]},{emqx_channel,do_publish,3,[{file,"emqx_channel.erl"},{line,603}]},{emqx_connection,with_channel,3,[{file,"emqx_connection.erl"},{line,694}]},{emqx_connection,process_msg,2,[{file,"emqx_connection.erl"},{line,394}]}]}

```

The items are sent correctly when subscribing to the MQTT topic:

![image](https://user-images.githubusercontent.com/1065098/168944258-4df374ca-3f78-46d4-a37f-2596e283d20f.png)

I can receive it just fine in MQTTX so it is a valid MQTT payload.

However the rules engine seems to do some additional processing on this and fails to do so accurately.

User Properties are one of the main features that people upgrade to MQTTv5 for, this absolutely needs to be supported for this to be useful.

### What did you expect to happen?

Rules should process MQTTv5 messages and include the User Properties in the JSON that is sent out via Webhook (or other rule output).

### How can we reproduce it (as minimally and precisely as possible)?

Use MQTTv5
Create a User Property item that is sent for each payload.
Create a rule to send to webhook

### EMQX version

<details>
sysdescr  : EMQ X Broker
version   : 4.4.3
uptime    : 45 minutes, 35 seconds
datetime  : 2022-05-18 02:40:19
</details>

### OS version

<details>

```console
NAME="Alpine Linux"
ID=alpine
VERSION_ID=3.15.1
PRETTY_NAME="Alpine Linux v3.15"
HOME_URL="https://alpinelinux.org/"
BUG_REPORT_URL="https://bugs.alpinelinux.org/"

Linux emqx-0 5.4.170+ #1 SMP Wed Mar 23 10:13:41 PDT 2022 x86_64 Linux
```

</details>

### Log files

<details>
bash-5.1$ cat conf.dump
========================================================
    /opt/emqx/bin/emqx eval 'emqx_node_dump:app_env_dump()'
========================================================
[{{env,gen_rpc,ssl_client_options},[]},
 {{env,kernel,net_ticktime},120},
 {{env,emqx_retainer,stop_publish_clear_msg},false},
 {{env,kernel,logger},
  [{handler,console,logger_std_h,
       #{config => #{type => standard_io},
         filters =>
             [{drop_progress_reports,{fun logger_filters:progress/2,stop}}],
         formatter =>
             {emqx_logger_textfmt,
                 #{chars_limit => unlimited,single_line => true,
                   template =>
                       [time," [",level,"] ",
                        {clientid,
                            [{peername,
                                 [clientid,"@",peername," "],
                                 [clientid," "]}],
                            [{peername,[peername," "],[]}]},
                        msg,"\n"]}},
         level => warning}}]},
 {{env,gen_rpc,ssl_server_port},5369},
 {{env,emqx,plugins_etc_dir},"etc/plugins/"},
 {{env,emqx,global_gc_interval},900},
 {{env,ekka,proto_dist},inet_tcp},
 {{env,emqx,broker_sys_interval},60000},
 {{env,emqx,retain_available},true},
 {{env,emqx_retainer,max_payload_size},1048576},
 {{env,emqx,enable_acl_cache},true},
 {{env,gen_rpc,socket_sndbuf},1048576},
 {{env,emqx_rule_engine,events},[]},
 {{env,ekka,cluster_discovery},
  {k8s,
      [{apiserver,"https://kubernetes.default.svc:443"},
       {service_name,"emqx-headless"},
       {address_type,hostname},
       {app_name,"emqx"},
       {namespace,"default"},
       {suffix,"svc.cluster.local"}]}},
 {{env,bcrypt,default_log_rounds},12},
 {{env,emqx_web_hook,pool_size},32},
 {{env,gen_rpc,client_config_per_node},{internal,#{}}},
 {{env,emqx_exhook,request_failed_action},deny},
 {{env,emqx,wildcard_subscription},true},
 {{env,emqx,max_topic_levels},128},
 {{env,kernel,error_logger},silent},
 {{env,observer_cli,plugins},[]},
 {{env,gen_rpc,rpc_module_control},disabled},
 {{env,gen_rpc,socket_recbuf},1048576},
 {{env,kernel,inet_dist_listen_min},4370},
 {{env,emqx_web_hook,headers},[{<<"content-type">>,<<"application/json">>}]},
 {{env,emqx,telemetry},
  [{enabled,false},
   {url,"https://telemetry-emqx-io.bigpar.vercel.app/api/telemetry"},
   {report_interval,604800}]},
 {{env,mnesia,dir},
  "/opt/emqx/data/mnesia/emqx@emqx-0.emqx-headless.default.svc.cluster.local"},
 {{env,emqx,zones},
  [{external,
       [{use_username_as_clientid,false},
        {upgrade_qos,false},
        {strict_mode,false},
        {session_expiry_interval,7200},
        {retry_interval,30},
        {mqueue_store_qos0,true},
        {mqueue_priorities,none},
        {mqueue_default_priority,highest},
        {max_subscriptions,0},
        {max_mqueue_len,1000},
        {max_inflight,32},
        {max_awaiting_rel,100},
        {latency_samples,10},
        {keepalive_backoff,0.75},
        {ignore_loop_deliver,false},
        {idle_timeout,15000},
        {force_shutdown_policy,
            #{max_heap_size => 8388608,message_queue_len => 10000}},
        {force_gc_policy,#{bytes => 16777216,count => 16000}},
        {enable_stats,true},
        {enable_flapping_detect,false},
        {enable_ban,true},
        {enable_acl,true},
        {conn_congestion_min_alarm_sustain_duration,60000},
        {conn_congestion_alarm_enabled,false},
        {bypass_auth_plugins,false},
        {await_rel_timeout,300},
        {acl_deny_action,ignore}]},
   {internal,
       [{use_username_as_clientid,false},
        {upgrade_qos,false},
        {strict_mode,false},
        {session_expiry_interval,7200},
        {retry_interval,30},
        {mqueue_store_qos0,true},
        {mqueue_priorities,none},
        {mqueue_default_priority,lowest},
        {max_subscriptions,0},
        {max_mqueue_len,10000},
        {max_inflight,128},
        {max_awaiting_rel,1000},
        {latency_samples,10},
        {keepalive_backoff,0.75},
        {ignore_loop_deliver,false},
        {idle_timeout,15000},
        {force_shutdown_policy,
            #{max_heap_size => 8388608,message_queue_len => 10000}},
        {enable_stats,true},
        {enable_flapping_detect,false},
        {enable_ban,false},
        {enable_acl,false},
        {conn_congestion_min_alarm_sustain_duration,60000},
        {conn_congestion_alarm_enabled,false},
        {bypass_auth_plugins,true},
        {await_rel_timeout,300},
        {allow_anonymous,true},
        {acl_deny_action,ignore}]}]},
 {{env,emqx_exhook,servers},
  [{default,[{scheme,http},{host,"127.0.0.1"},{port,9000}]}]},
 {{env,gen_rpc,max_batch_size},256},
 {{env,emqx,os_mon},
  [{cpu_check_interval,60},
   {cpu_high_watermark,80.0},
   {cpu_low_watermark,60.0},
   {mem_check_interval,60},
   {sysmem_high_watermark,70.0},
   {procmem_high_watermark,5.0}]},
 {{env,emqx,modules},
  [{emqx_mod_presence,[{qos,1}]},
   {emqx_mod_subscription,[]},
   {emqx_mod_rewrite,[]},
   {emqx_mod_topic_metrics,[]},
   {emqx_mod_delayed,[]},
   {emqx_mod_trace,[]},
   {emqx_mod_slow_subs,
       [{threshold,500},
        {expire_interval,300000},
        {top_k_num,10},
        {stats_type,whole},
        {notice_interval,0},
        {notice_qos,0},
        {notice_batch_size,500}]},
   {emqx_mod_acl_internal,[{acl_file,"etc/acl.conf"}]}]},
 {{env,emqx,modules_loaded_file},"data/loaded_modules"},
 {{env,emqx_exhook,hook_priority},0},
 {{env,emqx,vm_mon},
  [{check_interval,30},
   {process_high_watermark,80.0},
   {process_low_watermark,60.0}]},
 {{env,gen_rpc,tcp_client_num},1},
 {{env,gen_rpc,socket_keepalive_count},9},
 {{env,gen_rpc,connect_timeout},5000},
 {{env,emqx_management,listeners},
  [{http,8081,
       [{backlog,512},
        {send_timeout,15000},
        {send_timeout_close,true},
        {nodelay,true},
        {inet6,false},
        {ipv6_v6only,false},
        {num_acceptors,2},
        {max_connections,512}]}]},
 {{env,ssl,protocol_version},['tlsv1.3','tlsv1.2']},
 {{env,gen_rpc,ssl_server_options},[]},
 {{env,gen_rpc,driver},tcp},
 {{env,gen_rpc,tcp_client_port},5369},
 {{env,emqx_telemetry,url},"https://telemetry.emqx.io/api/telemetry"},
 {{env,ekka,{callback,reboot}},fun emqx:reboot/0},
 {{env,crypto,rand_cache_size},896},
 {{env,emqx,shared_subscription},true},
 {{env,emqx_web_hook,keyfile},[]},
 {{env,emqx_retainer,storage_type},ram},
 {{env,emqx,shared_subscription_strategy_per_group},#{}},
 {{env,gen_rpc,socket_keepalive_idle},900},
 {{env,emqx,listeners},
  [#{listen_on => {{127,0,0,1},11883},
     name => "internal",
     opts =>
         [{deflate_options,[]},
          {tcp_options,
              [{backlog,512},
               {send_timeout,5000},
               {send_timeout_close,true},
               {recbuf,65536},
               {sndbuf,65536},
               {high_watermark,1048576},
               {nodelay,false},
               {reuseaddr,true}]},
          {acceptors,4},
          {max_connections,1024000},
          {max_conn_rate,1000},
          {active_n,1000},
          {zone,internal},
          {proxy_address_header,<<>>},
          {proxy_port_header,<<>>},
          {supported_subprotocols,[]}],
     proto => tcp},
   #{listen_on => {{0,0,0,0},1883},
     name => "external",
     opts =>
         [{deflate_options,[]},
          {tcp_options,
              [{backlog,1024},
               {send_timeout,15000},
               {send_timeout_close,true},
               {high_watermark,1048576},
               {nodelay,true},
               {reuseaddr,true}]},
          {acceptors,64},
          {max_connections,1024000},
          {max_conn_rate,1000},
          {active_n,100},
          {zone,external},
          {proxy_address_header,<<>>},
          {proxy_port_header,<<>>},
          {supported_subprotocols,[]},
          {access_rules,[{allow,all}]}],
     proto => tcp},
   #{listen_on => 8083,name => "external",
     opts =>
         [{deflate_options,[]},
          {tcp_options,
              [{backlog,1024},
               {send_timeout,15000},
               {send_timeout_close,true},
               {nodelay,true}]},
          {acceptors,16},
          {mqtt_path,"/mqtt"},
          {max_connections,102400},
          {max_conn_rate,1000},
          {active_n,100},
          {zone,external},
          {proxy_address_header,<<"x-forwarded-for">>},
          {proxy_port_header,<<"x-forwarded-port">>},
          {fail_if_no_subprotocol,true},
          {supported_subprotocols,["mqtt","mqtt-v3","mqtt-v3.1.1","mqtt-v5"]},
          {mqtt_piggyback,multiple},
          {check_origin_enable,false},
          {allow_origin_absence,true},
          {check_origins,
              [<<"http://localhost:18083">>,<<"http://127.0.0.1:18083">>]},
          {access_rules,[{allow,all}]}],
     proto => ws},
   #{listen_on => 8883,name => "external",
     opts =>
         [{deflate_options,[]},
          {tcp_options,
              [{backlog,1024},
               {send_timeout,15000},
               {send_timeout_close,true},
               {high_watermark,1048576},
               {nodelay,true},
               {reuseaddr,true}]},
          {ssl_options,
              [{ciphers,
                   ["TLS_AES_256_GCM_SHA384","TLS_AES_128_GCM_SHA256",
                    "TLS_CHACHA20_POLY1305_SHA256","TLS_AES_128_CCM_SHA256",
                    "TLS_AES_128_CCM_8_SHA256",
                    "ECDHE-ECDSA-AES256-GCM-SHA384",
                    "ECDHE-RSA-AES256-GCM-SHA384","ECDHE-ECDSA-AES256-SHA384",
                    "ECDHE-RSA-AES256-SHA384","ECDHE-ECDSA-DES-CBC3-SHA",
                    "ECDH-ECDSA-AES256-GCM-SHA384",
                    "ECDH-RSA-AES256-GCM-SHA384","ECDH-ECDSA-AES256-SHA384",
                    "ECDH-RSA-AES256-SHA384","DHE-DSS-AES256-GCM-SHA384",
                    "DHE-DSS-AES256-SHA256","AES256-GCM-SHA384",
                    "AES256-SHA256","ECDHE-ECDSA-AES128-GCM-SHA256",
                    "ECDHE-RSA-AES128-GCM-SHA256","ECDHE-ECDSA-AES128-SHA256",
                    "ECDHE-RSA-AES128-SHA256","ECDH-ECDSA-AES128-GCM-SHA256",
                    "ECDH-RSA-AES128-GCM-SHA256","ECDH-ECDSA-AES128-SHA256",
                    "ECDH-RSA-AES128-SHA256","DHE-DSS-AES128-GCM-SHA256",
                    "DHE-DSS-AES128-SHA256","AES128-GCM-SHA256",
                    "AES128-SHA256","ECDHE-ECDSA-AES256-SHA",
                    "ECDHE-RSA-AES256-SHA","DHE-DSS-AES256-SHA",
                    "ECDH-ECDSA-AES256-SHA","ECDH-RSA-AES256-SHA",
                    "AES256-SHA","ECDHE-ECDSA-AES128-SHA",
                    "ECDHE-RSA-AES128-SHA","DHE-DSS-AES128-SHA",
                    "ECDH-ECDSA-AES128-SHA","ECDH-RSA-AES128-SHA",
                    "AES128-SHA"]},
               {handshake_timeout,15000},
               {depth,10},
               {keyfile,"etc/certs/key.pem"},
               {certfile,"etc/certs/cert.pem"},
               {reuse_sessions,true}]},
          {acceptors,32},
          {max_connections,102400},
          {max_conn_rate,500},
          {active_n,100},
          {zone,external},
          {proxy_address_header,<<>>},
          {proxy_port_header,<<>>},
          {supported_subprotocols,[]},
          {access_rules,[{allow,all}]}],
     proto => ssl},
   #{listen_on => 8084,name => "external",
     opts =>
         [{deflate_options,[]},
          {tcp_options,
              [{backlog,1024},
               {send_timeout,15000},
               {send_timeout_close,true},
               {nodelay,true}]},
          {ssl_options,
              [{ciphers,
                   ["TLS_AES_256_GCM_SHA384","TLS_AES_128_GCM_SHA256",
                    "TLS_CHACHA20_POLY1305_SHA256","TLS_AES_128_CCM_SHA256",
                    "TLS_AES_128_CCM_8_SHA256",
                    "ECDHE-ECDSA-AES256-GCM-SHA384",
                    "ECDHE-RSA-AES256-GCM-SHA384","ECDHE-ECDSA-AES256-SHA384",
                    "ECDHE-RSA-AES256-SHA384","ECDHE-ECDSA-DES-CBC3-SHA",
                    "ECDH-ECDSA-AES256-GCM-SHA384",
                    "ECDH-RSA-AES256-GCM-SHA384","ECDH-ECDSA-AES256-SHA384",
                    "ECDH-RSA-AES256-SHA384","DHE-DSS-AES256-GCM-SHA384",
                    "DHE-DSS-AES256-SHA256","AES256-GCM-SHA384",
                    "AES256-SHA256","ECDHE-ECDSA-AES128-GCM-SHA256",
                    "ECDHE-RSA-AES128-GCM-SHA256","ECDHE-ECDSA-AES128-SHA256",
                    "ECDHE-RSA-AES128-SHA256","ECDH-ECDSA-AES128-GCM-SHA256",
                    "ECDH-RSA-AES128-GCM-SHA256","ECDH-ECDSA-AES128-SHA256",
                    "ECDH-RSA-AES128-SHA256","DHE-DSS-AES128-GCM-SHA256",
                    "DHE-DSS-AES128-SHA256","AES128-GCM-SHA256",
                    "AES128-SHA256","ECDHE-ECDSA-AES256-SHA",
                    "ECDHE-RSA-AES256-SHA","DHE-DSS-AES256-SHA",
                    "ECDH-ECDSA-AES256-SHA","ECDH-RSA-AES256-SHA",
                    "AES256-SHA","ECDHE-ECDSA-AES128-SHA",
                    "ECDHE-RSA-AES128-SHA","DHE-DSS-AES128-SHA",
                    "ECDH-ECDSA-AES128-SHA","ECDH-RSA-AES128-SHA",
                    "AES128-SHA"]},
               {depth,10},
               {keyfile,"etc/certs/key.pem"},
               {certfile,"etc/certs/cert.pem"},
               {reuse_sessions,true}]},
          {acceptors,16},
          {mqtt_path,"/mqtt"},
          {max_connections,102400},
          {max_conn_rate,1000},
          {active_n,100},
          {zone,external},
          {proxy_address_header,<<"x-forwarded-for">>},
          {proxy_port_header,<<"x-forwarded-port">>},
          {fail_if_no_subprotocol,true},
          {supported_subprotocols,["mqtt","mqtt-v3","mqtt-v3.1.1","mqtt-v5"]},
          {mqtt_piggyback,multiple},
          {check_origin_enable,false},
          {allow_origin_absence,true},
          {check_origins,
              [<<"https://localhost:8084">>,<<"https://127.0.0.1:8084">>]},
          {access_rules,[{allow,all}]}],
     proto => wss}]},
 {{env,gen_rpc,rpc_module_list},[]},
 {{env,gen_rpc,default_client_driver},tcp},
 {{env,gen_rpc,socket_buffer},1048576},
 {{env,emqx,acl_deny_action},ignore},
 {{env,emqx,flapping_detect_policy},
  #{banned_interval => 300,duration => 60000,threshold => 30}},
 {{env,emqx_exhook,auto_reconnect},60000},
 {{env,bcrypt,pool_size},4},
 {{env,emqx,max_clientid_len},65535},
 {{env,emqx,allow_anonymous},true},
 {{env,gen_rpc,send_timeout},5000},
 {{env,emqx_web_hook,certfile},[]},
 {{env,emqx,shared_subscription_strategy},random},
 {{env,emqx,broker_sys_heartbeat},30000},
 {{env,emqx_dashboard,default_user_passwd},"********"},
 {{env,kernel,logger_sasl_compatible},false},
 {{env,bcrypt,mechanism},nif},
 {{env,gen_rpc,async_call_inactivity_timeout},infinity},
 {{env,gen_rpc,port_discovery},manual},
 {{env,emqx,acl_nomatch},allow},
 {{env,kernel,error_logger_format_depth},100},
 {{env,runtime_tools,ttb_autostart_module},ttb_autostart},
 {{env,emqx,acl_cache_ttl},60000},
 {{env,os_mon,start_os_sup},false},
 {{env,emqx,route_lock_type},key},
 {{env,emqx,max_qos_allowed},2},
 {{env,emqx,trie_compaction},true},
 {{env,emqx_web_hook,cacertfile},[]},
 {{env,emqx,session_locking_strategy},quorum},
 {{env,gen_rpc,client_inactivity_timeout},infinity},
 {{env,ekka,cluster_name},emqxcl},
 {{env,emqx,strict_mode},false},
 {{env,emqx_web_hook,encoding_of_payload_field},plain},
 {{env,gen_rpc,call_receive_timeout},15000},
 {{env,emqx,route_batch_clean},false},
 {{env,emqx,sysmon},
  [{long_schedule,240},
   {long_gc,0},
   {large_heap,8388608},
   {busy_port,false},
   {busy_dist_port,true}]},
 {{env,emqx_rule_engine,ignore_sys_message},true},
 {{env,emqx,rpc_mode},async},
 {{env,emqx_retainer,expiry_interval},0},
 {{env,emqx,max_packet_size},1048576},
 {{env,emqx_telemetry,enabled},true},
 {{env,gen_rpc,tcp_server_port},5369},
 {{env,gen_rpc,authentication_timeout},5000},
 {{env,emqx_web_hook,path},"/"},
 {{env,emqx_management,default_application_id},"admin"},
 {{env,os_mon,start_cpu_sup},true},
 {{env,ekka,{callback,prepare}},fun emqx:shutdown/1},
 {{env,ekka,cluster_autoclean},300000},
 {{env,ssl,dtls_protocol_version},['dtlsv1.2']},
 {{env,emqx,expand_plugins_dir},"etc/plugins/"},
 {{env,emqx_management,max_row_limit},10000},
 {{env,emqx,acl_file},"etc/acl.conf"},
 {{env,gen_rpc,socket_keepalive_interval},75},
 {{env,emqx_web_hook,url},"http://127.0.0.1:80"},
 {{env,emqx_telemetry,report_interval},604800},
 {{env,emqx_retainer,max_retained_messages},0},
 {{env,emqx_management,default_application_secret},"********"},
 {{env,os_mon,start_memsup},true},
 {{env,os_mon,start_disksup},true},
 {{env,observer_cli,scheduler_usage},disable},
 {{env,emqx_dashboard,default_user_username},"admin"},
 {{env,crypto,fips_mode},false},
 {{env,emqx,enable_session_registry},true},
 {{env,emqx,max_topic_alias},65535},
 {{env,emqx_exhook,request_timeout},5000},
 {{env,kernel,shell_docs_ansi},auto},
 {{env,kernel,inet_dist_listen_max},4370},
 {{env,emqx,data_dir},"data"},
 {{env,emqx,shared_dispatch_ack_enabled},false},
 {{env,gen_rpc,sbcast_receive_timeout},15000},
 {{env,kernel,logger_level},warning},
 {{env,gen_rpc,server_inactivity_timeout},infinity},
 {{env,emqx_web_hook,pool_opts},
  [{host,{127,0,0,1}},
   {port,80},
   {enable_pipelining,true},
   {pool_size,32},
   {pool_type,hash},
   {connect_timeout,5000},
   {retry,5},
   {retry_timeout,1000},
   {transport_opts,[{ipv6_probe,true}]}]},
 {{env,emqx_web_hook,verify},false},
 {{env,jose,crypto_fallback},true},
 {{env,emqx,backtrace_depth},16},
 {{env,ekka,cluster_autoheal},true},
 {{env,emqx,acl_cache_max_size},32},
 {{env,emqx_web_hook,enable_pipelining},true},
 {{env,gen_rpc,ssl_client_port},5370},
 {{env,emqx,alarm},
  [{actions,[log,publish]},{size_limit,1000},{validity_period,86400}]},
 {{env,emqx_dashboard,listeners},
  [{http,18083,
       [{num_acceptors,4},
        {max_connections,512},
        {inet6,false},
        {ipv6_v6only,false}]}]},
 {{env,emqx,ignore_loop_deliver},false},
 {{env,emqx,plugins_loaded_file},"data/loaded_plugins"}]

bash-5.1$ cat sysinfo.txt
========================================================
    /opt/emqx/bin/emqx_ctl broker
========================================================
sysdescr  : EMQ X Broker
version   : 4.4.3
uptime    : 48 minutes, 2 seconds
datetime  : 2022-05-18 02:42:47

========================================================
    /opt/emqx/bin/emqx eval 'emqx_node_dump:sys_info()'
========================================================
#{otp_version => "24.1.5",release => "4.4.3"}

========================================================
    uname -a
========================================================
Linux emqx-0 5.4.170+ #1 SMP Wed Mar 23 10:13:41 PDT 2022 x86_64 Linux

========================================================
    uptime
========================================================
 02:42:52 up 19:12,  load average: 0.04, 0.07, 0.10

========================================================
    free
========================================================
              total        used        free      shared  buff/cache   available
Mem:        4029400      585420     2594280       37340      849700     3217584
Swap:             0           0           0

========================================================
    netstat -tnl
========================================================
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State
tcp        0      0 127.0.0.1:11883         0.0.0.0:*               LISTEN
tcp        0      0 0.0.0.0:8081            0.0.0.0:*               LISTEN
tcp        0      0 0.0.0.0:4370            0.0.0.0:*               LISTEN
tcp        0      0 0.0.0.0:8883            0.0.0.0:*               LISTEN
tcp        0      0 0.0.0.0:8083            0.0.0.0:*               LISTEN
tcp        0      0 0.0.0.0:8084            0.0.0.0:*               LISTEN
tcp        0      0 0.0.0.0:5369            0.0.0.0:*               LISTEN
tcp        0      0 0.0.0.0:1883            0.0.0.0:*               LISTEN
tcp        0      0 0.0.0.0:18083           0.0.0.0:*               LISTEN

========================================================
    /opt/emqx/bin/emqx_ctl plugins list
========================================================
Plugin(emqx_auth_http, description=EMQ X Authentication/ACL with HTTP API, active=false)
Plugin(emqx_auth_jwt, description=EMQ X Authentication with JWT, active=false)
Plugin(emqx_auth_ldap, description=EMQ X Authentication/ACL with LDAP, active=false)
Plugin(emqx_auth_mnesia, description=EMQ X Authentication with Mnesia, active=false)
Plugin(emqx_auth_mongo, description=EMQ X Authentication/ACL with MongoDB, active=false)
Plugin(emqx_auth_mysql, description=EMQ X Authentication/ACL with MySQL, active=false)
Plugin(emqx_auth_pgsql, description=EMQ X Authentication/ACL with PostgreSQL, active=false)
Plugin(emqx_auth_redis, description=EMQ X Authentication/ACL with Redis, active=false)
Plugin(emqx_bridge_mqtt, description=EMQ X Bridge to MQTT Broker, active=false)
Plugin(emqx_coap, description=EMQ X CoAP Gateway, active=false)
Plugin(emqx_dashboard, description=EMQ X Web Dashboard, active=true)
Plugin(emqx_exhook, description=EMQ X Extension for Hook, active=true)
Plugin(emqx_exproto, description=EMQ X Extension for Protocol, active=false)
Plugin(emqx_lua_hook, description=EMQ X Lua Hooks, active=false)
Plugin(emqx_lwm2m, description=EMQ X LwM2M Gateway, active=false)
Plugin(emqx_management, description=EMQ X Management API and CLI, active=true)
Plugin(emqx_prometheus, description=Prometheus for EMQ X, active=false)
Plugin(emqx_psk_file, description=EMQX PSK Plugin from File, active=false)
Plugin(emqx_recon, description=EMQ X Recon Plugin, active=true)
Plugin(emqx_retainer, description=EMQ X Retainer, active=true)
Plugin(emqx_rule_engine, description=EMQ X Rule Engine, active=true)
Plugin(emqx_sasl, description=EMQ X SASL, active=false)
Plugin(emqx_sn, description=EMQ X MQTT-SN Plugin, active=false)
Plugin(emqx_stomp, description=EMQ X Stomp Protocol Plugin, active=false)
Plugin(emqx_telemetry, description=EMQ X Telemetry, active=true)
Plugin(emqx_web_hook, description=EMQ X WebHook Plugin, active=true)

========================================================
    /opt/emqx/bin/emqx_ctl modules list
========================================================
Module(emqx_mod_delayed, description=EMQ X Delayed Publish Module, active=true)
Module(emqx_mod_topic_metrics, description=EMQ X Topic Metrics Module, active=true)
Module(emqx_mod_subscription, description=EMQ X Subscription Module, active=true)
Module(emqx_mod_acl_internal, description=EMQ X Internal ACL Module, active=true)
Module(emqx_mod_rewrite, description=EMQ X Topic Rewrite Module, active=true)
Module(emqx_mod_presence, description=EMQ X Presence Module, active=true)
Module(emqx_mod_trace, description=EMQ X Trace Module, active=true)
Module(emqx_mod_slow_subs, description=EMQ X Slow Subscribers Statistics Module, active=true)

========================================================
    /opt/emqx/bin/emqx_ctl vm all
========================================================
cpu/load1               : 0.04
cpu/load5               : 0.08
cpu/load15              : 0.11
memory/total            : 137008288
memory/processes        : 32533272
memory/processes_used   : 32532768
memory/system           : 104475016
memory/atom             : 1433929
memory/atom_used        : 1412436
memory/binary           : 116248
memory/code             : 41492830
memory/ets              : 36767416
process/limit           : 2097152
process/count           : 511
io/max_fds              : 1048576
io/active_fds           : 0
ports/count           : 21
ports/limit           : 1048576

========================================================
    /opt/emqx/bin/emqx_ctl listeners
========================================================
mqtt:ssl:external
  listen_on       : 0.0.0.0:8883
  acceptors       : 32
  max_conns       : 102400
  current_conn    : 0
  shutdown_count  : []
mqtt:tcp:external
  listen_on       : 0.0.0.0:1883
  acceptors       : 64
  max_conns       : 1024000
  current_conn    : 2
  shutdown_count  : [{normal,2}]
mqtt:tcp:internal
  listen_on       : 127.0.0.1:11883
  acceptors       : 4
  max_conns       : 1024000
  current_conn    : 0
  shutdown_count  : []
http:dashboard
  listen_on       : 0.0.0.0:18083
  acceptors       : 4
  max_conns       : 512
  current_conn    : 0
  shutdown_count  : []
http:management
  listen_on       : 0.0.0.0:8081
  acceptors       : 2
  max_conns       : 512
  current_conn    : 0
  shutdown_count  : []
mqtt:ws:external
  listen_on       : 0.0.0.0:8083
  acceptors       : 16
  max_conns       : 102400
  current_conn    : 0
  shutdown_count  : []
mqtt:wss:external
  listen_on       : 0.0.0.0:8084
  acceptors       : 16
  max_conns       : 102400
  current_conn    : 0
  shutdown_count  : []
</details>

**Comment by voycey** [comment]
Is there any update on this one? This is a blocker for us!

Seems related to: https://github.com/emqx/emqx/issues/8029

**Comment by gsychev** [comment]
@voycey , Hi, sorry for the late feedback on this issue, the developer it was originally assigned to went on a vacation...
Considering the problem, could you please provide the SQL rule which is affected by this issue.

**Comment by voycey** [comment]
Any of them, `select * from #` was basically what I was doing but any of the rules will have the same problem
________________________________

**Comment by voycey** [comment]
Any of them, `select * from #` was basically what I was doing but any of the rules will have the same problem, the error is in how it is handling the MQTTv5 User Properties header as indicated by the error message. Please test this

**Comment by voycey** [comment]
Hi @zmstone,

Sorry I missed this response as I was away on leave, does this mean it is solved for running of rules? I can see that they are not duplicated but I havent had a chance to test this yet, I will try and do this sometime this week and report back!

Thanks!

**Comment by zmstone** [comment]
Yes. The headers are removed 
https://github.com/emqx/emqx/pull/8260
