### ISSUE TITLE
EMQX 4.4.3 Import does not work on Docker

### ISSUE THREAD

**Issue by qtkite** [emqx/emqx#7990]
### What happened?

If you deploy EMQ (4.4.3) on a docker, create some sample rules and export it to a .json file as documented here:
https://www.emqx.io/docs/en/v4.3/advanced/data-import-and-export.html#example

Then attempt to restart the docker or try running the import instructions on another device you will get an "not_found" message.

This error occurs with **both** the HTTP API and the CLI method.

Using CLI Method:

```
bash$ ./emqx_ctl data import /opt/emqx/bin/test.json
The emqx data import failed: not_found while reading /opt/emqx/bin/test.json.
```

Using HTTP method:
```
$ curl -i --basic -u admin:public -X POST "http://172.25.2.150:8081/api/v4/data/import" -d @test2.json
HTTP/1.1 200 OK
content-length: 23
content-type: application/json
date: Thu, 19 May 2022 05:05:16 GMT
server: Cowboy

{"message":"not_found"}
```

However, if you export the file - then immediately import it - it works successfully. It only does not work once you wipe the EMQ image and restart it or trying it onto another device.

I am also not using a mounted file system for my docker image since I expect to be able to import configs.

Sample JSON file:

```
{"filename":"emqx-export-2022-5-19-4-3-53.json","file":"{\"version\":\"4.4\",\"rules\":[{\"id\":\"rule:387279\",\"rawsql\":\"SELECT\\n  payload.msg as msg\\nFROM\\n  \\\"t/#\\\"\\nWHERE\\n  msg = 'hello'\",\"actions\":[{\"id\":\"data_to_webserver_1652929037602901507\",\"name\":\"data_to_webserver\",\"fallbacks\":[],\"args\":{\"path\":\"\",\"method\":\"POST\",\"headers\":{\"content-type\":\"application/json\"},\"body\":\"\",\"$resource\":\"resource:020535\"}}],\"enabled\":true,\"description\":\"\"}],\"resources\":[{\"id\":\"resource:020535\",\"type\":\"web_hook\",\"config\":{\"cacertfile\":{\"filename\":\"\",\"file\":\"\"},\"certfile\":{\"filename\":\"\",\"file\":\"\"},\"connect_timeout\":\"5s\",\"enable_pipelining\":true,\"keyfile\":{\"filename\":\"\",\"file\":\"\"},\"pool_size\":8,\"request_timeout\":\"5s\",\"url\":\"http://google.com\",\"verify\":false},\"created_at\":1652929138137,\"description\":\"\"},{\"id\":\"resource:977815\",\"type\":\"bridge_rpc\",\"config\":{\"address\":\"emqx2@127.0.0.1\",\"batch_size\":32,\"disk_cache\":\"off\",\"mountpoint\":\"bridge/emqx/${node}/\",\"pool_size\":8,\"reconnect_interval\":\"30s\"},\"created_at\":1652929138144,\"description\":\"\"}],\"blacklist\":[],\"apps\":[{\"id\":\"admin\",\"secret\":\"public\",\"name\":\"Default\",\"desc\":\"Application user\",\"status\":true,\"expired\":\"undefined\"}],\"users\":[{\"username\":\"admin\",\"password\":\"B5N4HerqrKz101B8vvcsi853DJc=\",\"tags\":\"administrator\"}],\"auth_mnesia\":[],\"acl_mnesia\":[],\"date\":\"2022-05-19 03:33:13\"}"}
```

### What did you expect to happen?

EMQ should load the Json config successfully.

### How can we reproduce it (as minimally and precisely as possible)?

Deploy an EMQX Image using docker. 
Setup some sample Rules and Resource settings. 
Export it to a JSON file. 
Restart the docker so it is essentially a new instance.
Attempt to import the config you just exported.

### Anything else we need to know?

From docker logs <container id>

EMQ X Broker 4.4.3 is running now!
2022-05-19T03:49:30.045419+00:00 [error] POST /api/v4/data/import error: {badmap,[]}, stacktrace:, [{maps,merge,[[],#{}],[{error_info,#{module => erl_stdlib_errors}}]},{emqx_mgmt_data_backup,import,2,[{file,"emqx_mgmt_data_backup.erl"},{line,789}]},{emqx_mgmt_api_data,import,2,[{file,"emqx_mgmt_api_data.erl"},{line,91}]},{minirest_handler,dispatch,2,[{file,"minirest_handler.erl"},{line,90}]},{minirest,handle_request,2,[{file,"minirest.erl"},{line,116}]},{minirest,init,2,[{file,"minirest.erl"},{line,108}]},{cowboy_handler,execute,2,[{file,"cowboy_handler.erl"},{line,41}]},{cowboy_stream_h,execute,3,[{file,"cowboy_stream_h.erl"},{line,318}]},{cowboy_stream_h,request_process,3,[{file,"cowboy_stream_h.erl"},{line,302}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,226}]}]

### EMQX version

<details>

```console
$ ./bin/emqx_ctl broker
sysdescr  : EMQ X Broker
version   : 4.4.3
uptime    : 1 hours, 5 minutes, 38 seconds
datetime  : 2022-05-19 04:53:29
```

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
PRETTY_NAME="Ubuntu 21.10"
NAME="Ubuntu"
VERSION_ID="21.10"
VERSION="21.10 (Impish Indri)"
VERSION_CODENAME=impish
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=impish

$ uname -a
Linux cisco 5.13.0-22-generic #22-Ubuntu SMP Fri Nov 5 13:21:36 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux


```

</details>

### Log files

<details>

</details>

I was also looking at the source code for relevance:
https://github.com/emqx/emqx-management/blob/3e5600ca340612177ea39d00f7203816cf8ffddb/src/emqx_mgmt_cli.erl#L622

Seems to be the line that gets triggered when I try importing via command line. I also verified my Json file is correct.

**Comment by thalesmg** [comment]
Hi @qtkite !

Thanks for the report.  Without using your provided example file, I have not been able to reproduce the issue using the HTTP API, but I observed the problem using the CLI.

The reason you couldn't make the HTTP API work is that your json is that it contains a `filename` key that points to an inexistent file in EMQX's backup directory, since after a restart such file will not exist anymore.

You can either provide _only_ the path to a file inside the container, or upload the file itself as the POST body:

```sh
# backup.json here is the exported file as-is.
curl -vXPOST \
     -su admin:public \
     -d @backup.json \
     http://localhost:8081/api/v4/data/import 

# alternative: provide a path to a file that is readable inside the
# container.  Note we are not reading the file as the POST body.
curl -vXPOST \
     -su admin:public \
     -d '{"filename":"/path/to/backup.json"}' \
     http://localhost:8081/api/v4/data/import 
```

As for the CLI issue, that seems to be a bug indeed.  We'll follow up with a fix for that.

**Comment by qtkite** [comment]
> Hi @qtkite !
> 
> Thanks for the report. Without using your provided example file, I have not been able to reproduce the issue using the HTTP API, but I observed the problem using the CLI.
> 
> The reason you couldn't make the HTTP API work is that your json is that it contains a `filename` key that points to an inexistent file in EMQX's backup directory, since after a restart such file will not exist anymore.
> 
> You can either provide _only_ the path to a file inside the container, or upload the file itself as the POST body:
> 
> ```shell
> # backup.json here is the exported file as-is.
> curl -vXPOST \
>      -su admin:public \
>      -d @backup.json \
>      http://localhost:8081/api/v4/data/import 
> 
> # alternative: provide a path to a file that is readable inside the
> # container.  Note we are not reading the file as the POST body.
> curl -vXPOST \
>      -su admin:public \
>      -d '{"filename":"/path/to/backup.json"}' \
>      http://localhost:8081/api/v4/data/import 
> ```
> 
> As for the CLI issue, that seems to be a bug indeed. We'll follow up with a fix for that.

Hi, so how can I import a config file to another device if that key does not exist in the backup directory. I tried 
```
curl -vXPOST \
     -su admin:public \
     -d @backup.json \
     http://localhost:8081/api/v4/data/import 
```
however, I just get a "not_found" message response. 
Just to confirm are you running 4.4.3 and not "latest" from docker?

**Comment by thalesmg** [comment]
Yes, I've used 4.4.3.

I tried again, and can confirm that the option using the raw `@backup.json` file does work on docker.  

The `filename` one indeed did not work after trying again, I might've experimented with the fixed version when testing.

**Comment by qtkite** [comment]
Do you mind sharing your backup.json for comparison?

**Comment by thalesmg** [comment]
Sure, it's just a fresh export from a blank container :smiley_cat: 

```json
{"version":"4.4","rules":[],"resources":[],"blacklist":[],"apps":[{"id":"admin","secret":"public","name":"Default","desc":"Application user","status":true,"expired":"undefined"}],"users":[{"username":"admin","password":"w7FsSsjYbjZFw3WgnITbvnFfwOQ=","tags":"administrator"}],"auth_mnesia":[],"acl_mnesia":[],"date":"2022-05-20 12:04:37"}
```

**Comment by qtkite** [comment]
Thanks, I was uploading the entire json file returned by the server. Not just the data under the "file" key.
