### ISSUE TITLE
EMQX 4.4.3 not run CentOS 8 (RPM | ZIP)

### ISSUE THREAD

**Issue by rootqa** [emqx/emqx#7995]
### What happened?

We are testing stable version of EMQX (4.4.3) on CentOS 8 and Debian 11 and had problems in both cases, installing it with both RPM and ZIP version.

### What did you expect to happen?

EMQX not start and crash dump occurs.

### How can we reproduce it (as minimally and precisely as possible)?

1. Install Centos 8 or Debian 11
2. if Centos 8 first install repos rpm.
$ wget https://www.emqx.com/en/downloads/broker/4.4.3/emqx-4.4.3-otp24.1.5-3-el8-amd64.rpm
3. Install software:
$ yum install emqx-4.4.3-otp24.1.5-3-el8-amd64.rpm
4. emqx start

Log:

{"init terminating in do_boot",{undef,[{crypto,start,[],[]},{init,start_em,1,[]},{init,do_boot,3,[]}]}}
init terminating in do_boot ({undef,[{crypto,start,[],[]},{init,start_em,1,[]},{init,do_boot,3,[]}]})

Crash dump is being written to: erl_crash.dump...done
FATAL: Unable to start Erlang.
Please make sure openssl-1.1.1 (libcrypto) and libncurses are installed.
Also ensure it's running on the correct platform,
this EMQX release is built for 24.1.5-3-x86_64-pc-linux-gnu-64-el8

### Anything else we need to know?

openssl and ncurses installed (ldconfig run)

### EMQX version

<details>

emqx 4.4.3

</details>

### OS version

<details>

# cat /etc/redhat-release
CentOS Linux release 8.5.2111

</details>

### Log files
<details><code>
odule: cuttlefish_error
7F78CDF9A028:t2:A5:error,A7:timeout
7F78CDF9A040:t2:A5:error,A7:enotsup
7F78CDF9A070:t2:A5:error,A7:request
7F78CDF9A0F8:t3:A5:error,H7F78CDF9A118,N
7F78CDF9A118:t2:A5:error,AB:interrupted
emqx_packets_unsubscribe_error
emqx_packets_subscribe_error
emqx_packets_subscribe_auth_error
emqx_packets_publish_error
emqx_packets_publish_auth_error
emqx_packets_connack_error
emqx_packets_connack_auth_error
raise_error_if_le_label_found
raise_error_if_quantile_label_found
'-v_msg_error_response/3-fun-0-'
v_msg_error_response
merge_msg_error_response
skip_64_error_response
skip_32_error_response
skip_group_error_response
skip_length_delimited_error_response
skip_varint_error_response
d_field_error_response_error_message
d_field_error_response_error_code
dg_read_field_def_error_response
dfp_read_field_def_error_response
decode_msg_error_response
d_field_server_reflection_response_error_response
e_mfield_server_reflection_response_error_response
error_message
encode_msg_error_response
gpb_type_error
mk_type_error
gpb_error
grpc_error
process_error
unicode_error
handle_connect_error
select_error
authentication_error
sentinel_error
update_errors
'-fun.decode_error_extra/2-'
decode_error_extra
error_in_assignment
substring_error
trim_error
array_subscript_error
syntax_error_or_access_rule_violation
grouping_error
windowing_error
system_error
config_file_error
fdw_error
fdw_function_sequence_error
plpgsql_error
sync_on_error
username_or_password_error
gen_tcp_error
tcp_opts_error
telemetry_data_encode_error
doeach_error
select_and_transform_error
select_and_collect_error
match_incase_error
match_conditions_error
get_actions_error
'actions.error'
lex_error
inc_actions_error
cutkey_error
public_key_error
error_to_reason
parse_error_packet
http_to_connack_error
error_stream_not_found
error_stream_closed
error_frame
login_or_passcode_error
internal_server_error
coap_error
gun_error
substitutionGroup_error
return_schema_error
error_path
validation_error_all
schema_error
ucs_error
error_missing_element_declaration_in_DTD
validity_constraint_error_ID_Attribute_Default
error_scanning_entity_ref
error_more_than_one_ID_def
error_missing_declaration_in_DTD
error_reading_file
error_fetching_external_resource
error_fetching_external_source
error_fetching_DTD
sax_simple_dom_error
event_receiver_error
fatal_error
xmerl_sax_old_dom_error
do_error_return
error_call
assert_error
badarg_error
lua_error
error_opening_bcrypt_file
error_logger_queue_len
log_error
merge_error
error_recs
error_fun
exit_on_error
backend_init_error
last_error
fix_error
application_load_error
remote_collect_error
mnesia_error
local_fallback_error
fallback_error_function
error_desc
error_description
dirty_rpc_error_tag
combine_error
topic_name_error
unspecified_error
implementation_specific_error
password_error
'packets.unsubscribe.error'
'packets.subscribe.error'
'packets.subscribe.auth_error'
'packets.connack.auth_error'
'packets.connack.error'
'packets.publish.auth_error'
'packets.publish.error'
fmt_error
connack_error
exit_on_sock_error
frame_error
sock_error
request_error
early_error_time
'An error occurred when using the sendfile function.'
error_terminate
error_response
early_error
make_error_log
'An error has occurred on the socket.'
'A socket error occurred when retrieving the client TLS certificate.'
'A socket error occurred when retrieving the sock name.'
'A socket error occurred when retrieving the peer name.'
parse_port_error
parse_ipv6_error
parse_ipv4_error
listen_error
connection_error
error_code
no_error
flow_control_error
compression_error
connect_error
parse_error_code
protocol_error
frame_size_error
return_ok_or_error
recv_proxy_info_error
connection_shutdown_error
socket_error
external_source_error
gproc_error
maybe_log_file_error
error1
'-fun.is_error/1-'
errorlist_maybe
contains_error
translation_unknown_error
'-to_error/2-lc$^0/1-0-'
is_error
to_error
errorlist
'socket read error'
'file position error'
'file read error'
file_format_error
pre_string_error
report_internal_error
'-format_error_reason/1-anonymous-0-'
'-format_error_reason/1-anonymous-1-'
'-report_errors/1-anonymous-0-'
no_error_module_mismatch
ignore_native_errors
not_werror
format_error_reason
write_error
float_error_state
checkerror
clearerror
format_error_1
fclearerror
fcheckerror
error_disk_log_size
error_disk_log
no_error_log
error_old
error_new
error_to_exit
mod_error_logging
error_log
status_server_error_50x
maybe_error
headers_error
streaming_error
error_connecting
error_sending
init_error
size_error
'-error_entry/5-fun-0-'
'-error_report_entry/5-fun-0-'
error_log_format
do_error_entry
error_report_entry
error_entry
os_sup_errortag
memsup_port_error
alert_decode_error
unexpected_error
handshake_decode_error
ssl_error
format_packet_error
deliver_packet_error
transport_error
error_tag
encoding_error
crl_parse_error
decode_error
decrypt_error
file_error_format
revert_error_marker
error_backup_file
error_write_file
error_read_file_info
error_open_output
error_text_1
error_text
syntax_error
finfo_add_error
lay_error_info
error_marker_info
error_read_file
errormsg
error_marker
io_error
mask_error
scope_error
handle_error
notsup_to_error
nif_stub_error
'-format_error/1-lc$^0/1-0-'
print_error
'-format_error/1-fun-3-'
'-format_error/1-fun-2-'
'-format_error/1-fun-1-'
'-format_error/1-fun-0-'
'-format_errors/1-fun-0-'
error_reading
error_add_appl
tar_error
parse_error
error_mandatory_application
warnings_treated_as_errors
is_my_error_report
werror
'heart:set_cmd() error'
error_action
delete_error_logger_mf
add_error_logger_mf
error_logger_mf_maxfiles
error_logger_mf_maxbytes
get_error_logger_mf
sasl_error_logger
error_logger_mf_dir
abort_on_error
format_child_log_error_single
error_type_iter
error_type
'-compile_errors/1-fun-0-'
fread_error
compile_errors
command_error
'-maybe_error_logger/2-fun-0-'
'-maybe_error_logger/2-fun-1-'
throw_file_error
maybe_error_logger
throw_error
'-format_errors/1-lc$^1/1-1-'
'-format_errors/1-lc$^0/1-0-'
'-report_errors/1-fun-0-'
list_errors
format_errors
errors
char_error
call_error
warnings_as_errors
arg_error
return_errors
scan_error
no_stderror
standard_error_sup
recv_error
proto_error
register_error
mk_monitor_nodes_error
query_retries_error
qfmterror
formatter_error
error_logger_notice_header
error_notify
error_notify_new
maybe_notify_error
'$#erlang-history-file-error'
handle_open_error
sync_error
handle_recv_error
handle_recv_error_decode
is_arg_error
ac_error
file_error_close
get_own_nodes_with_errors
error_string
error_status
cache_error
do_format_error
make_error
errorContext
'-separate_error_info/1-fun-0-'
separate_error_info
error_handling
'-pack_errors/1-fun-0-'
'-pack_errors/1-fun-1-'
'-pack_errors/1-fun-2-'
'-func_line_error/3-fun-0-'
func_line_error
add_lint_error
add_error
pack_errors
yeccerror
yecc_error_type
return_error
error_bad_decl
stop_error
start_error
report_error
invalid_unicode_error
config_error
handle_make_term_error
'load error'
transform_error
checksum_error
read_error
shutdown_error
format_error
error_logger_format_depth
error_logger_tty_true
error_logger_tty_false
error_info
error_msg
cuttlefish_error
error_logger_tty_h
error_logger_file_h
erl_error
unknown_error
version_error
buf_error
mem_error
stream_error
ets_info_binary_error
remote_spawn_error
std_error
error_report
file_error
port_error
peer_error
data_error
throw_on_error
standard_error
'bootfile format error'
udp_error
tcp_error
nif_error
format_error_int
report_errors
open_error
internal_error
http_error
error_only
error_logger
error_handler
error
</code>
</details>

**Comment by rootqa** [comment]
ZIP version:

# ./emqx start
{"init terminating in do_boot",{undef,[{crypto,start,[],[]},{init,start_em,1,[]},{init,do_boot,3,[]}]}}
init terminating in do_boot ({undef,[{crypto,start,[],[]},{init,start_em,1,[]},{init,do_boot,3,[]}]})

Crash dump is being written to: erl_crash.dump...done
FATAL: Unable to start Erlang.
Please make sure openssl-1.1.1 (libcrypto) and libncurses are installed.
Also ensure it's running on the correct platform,
this EMQX release is built for 24.1.5-3-x86_64-pc-linux-gnu-64-el8

**Comment by ieQu1** [comment]
Hello,

1. CentOS 8 has reached end of life: https://www.centos.org/centos-linux-eol/ I don't think anything will work properly there.
2. As for debian, please make sure you've installed `libssl1.1` package.

**Comment by amnonbb** [comment]
Rocky Linux 8.6 - same problem

**Comment by zmstone** [comment]
4.4.3 is built on openssl version `1.1.1n`, which seems not quite compatible with `1.1.1k` (rocky linux default)

**Comment by zmstone** [comment]
for ref: this is how openssl is built for EMQX release
https://github.com/emqx/emqx-builder/blob/main-4.4/get-openssl.sh

**Comment by amnonbb** [comment]
It's will be good to notify some way about openssl version limit. Because from error message not possible to understand what really problem.

**Comment by zmstone** [comment]
> It's will be good to notify some way about openssl version limit. Because from error message not possible to understand what really problem.

But this is a bug in the release pipeline, breaking compatibility wasn’t our intention.
Now that the packages are rebuilt (please download from emqx.io but not GitHub release asset) I’m closing this issue.
