### ISSUE TITLE
Recommend way to run emqttd 2.0 on windows

### ISSUE THREAD

**Issue by michaelcplusplus** [emqx/emqx#803]
#### Environment

- OS: Windows 7
- Erlang/OTP: 18.3
- EMQ: 2.0.2

#### Description

What is the recommended way to run emqttd 2.0.2 on windows.

In console mode everything works fine:
bin\emqttd console
The memory usage is fine.

If I run it in the windows service mode 
bin\emqttd start
than the broker memory usage grows endless.

I want to run it with a tool like nssm.exe in a windows service mode. 
How to do this?

**Comment by michaelcplusplus** [comment]
The following solution works for me:

Modification in **emqttd.cmd**
:: Start a console
:console
@call :create_mnesia_dir
@call :generate_app_config
@set args=%sys_config% %args_file% %generated_config_args% -mnesia dir '%mnesia_dir%'
:: @start "%rel_name% console" %werl% -boot "%boot_script%" %args%
%erl_exe% -noinput -boot "%boot_script%" %args%
@goto :eof

Create a new batchfile 
**start_emqttd.cmd**
cd c:\emqttd\emqttd-2.0.4\
bin\emqttd console > my.log

Install the batchfile start_emqttd.cmd with nssm.exe as windows service.
Start and stop of the windows service works fine.
The memory consumption is fine.

Does anyone have any recommendations about this solution.

Best regards 
Michael

**Comment by scytalezero** [comment]
Thanks very much for sharing; this is working for me currently on Windows. I'm running it with pm2 but the result is the same.

**Comment by sinegole** [comment]
This is not added in 2.3-beta.3 version yet. Please can someone fix this problem. How you expect to people use this if can't install.

**Comment by michaelcplusplus** [comment]
Now I work with the following solution:

- Extract the content of the zip emqttd-windows10-v2.2.0.zip in a directory
c:\emqttd\emqttd-windows10-v2.2.0

- Make the configurations in the emq.conf file
c:\emqttd\emqttd-windows10-v2.2.0\etc\emq.conf

- Start once the broker via the 
bin\emqttd console

- Stop the broker

- Rename the generated config file in c:\emqttd\emqttd-windows10-v2.2.0\data\configs\
app.2017.10.12.10.31.53.config -> app.config
vm.2017.10.12.10.31.53.args -> vm.args 
app.2017.10.12.10.31.52.conf -> app.conf


- Put this command in a batch file

`"c:\emqttd\emqttd-windows10-v2.2.0\erts-8.3\bin\erl.exe" -noinput -boot "c:\emqttd\emqttd-windows10-v2.2.0\releases\2.2\emqttd"    -config c:/emqttd/emqttd-windows10-v2.2.0/data/configs/app.config -args_file c:/emqttd/emqttd-windows10-v2.2.0/data/configs/vm.args -vm_args c:/emqttd/emqttd-windows10-v2.2.0/data/configs/vm.args  -mnesia dir 'c:/emqttd/emqttd-windows10-v2.2.0/data/mnesia/hydra1@127.0.0.1'`


- Start the batch file with nssm.exe

**Comment by epopoee** [comment]
had problems with installing the batch file as nssm service. Analyzing my problems I found that when running "emqttd console" emqttd launches an erl.exe, which finally starts a werl.exe process, which really does the job. I grabbed the werl.exe command line from process properties in Process Explorer:
`"C:\emqttd\emqttd-windows10-v2.3-rc.1\erts-8.3\bin\werl.exe"  -boot "C:\emqttd\emqttd-windows10-v2.3-rc.1\releases\2.3\emqttd"    -config c:/emqttd/emqttd-windows10-v2.3-rc.1/data/configs/app.2017.10.17.17.06.43.config -args_file c:/emqttd/emqttd-windows10-v2.3-rc.1/data/configs/vm.2017.10.17.17.06.43.args -vm_args c:/emqttd/emqttd-windows10-v2.3-rc.1/data/configs/vm.2017.10.17.17.06.43.args  -mnesia dir 'c:/emqttd/emqttd-windows10-v2.3-rc.1/data/mnesia/emq@127.0.0.1')`

Using this I installed an nssm service with 
- Application Path:
`"C:\emqttd\emqttd-windows10-v2.3-rc.1\erts-8.3\bin\werl.exe"`
- Application Arguments: 
`-boot "C:\emqttd\emqttd-windows10-v2.3-rc.1\releases\2.3\emqttd"    -config c:/emqttd/emqttd-windows10-v2.3-rc.1/data/configs/app.2017.10.17.17.06.43.config -args_file c:/emqttd/emqttd-windows10-v2.3-rc.1/data/configs/vm.2017.10.17.17.06.43.args -vm_args c:/emqttd/emqttd-windows10-v2.3-rc.1/data/configs/vm.2017.10.17.17.06.43.args  -mnesia dir 'c:/emqttd/emqttd-windows10-v2.3-rc.1/data/mnesia/emq@127.0.0.1')`

and very important: 
- Application Startup Directory: 
`C:\emqttd\emqttd-windows10-v2.3-rc.1`

The latter enables werl.exe to find config files in C:\emqttd\emqttd-windows10-v2.3-rc.1\etc.

**Comment by emqplus** [comment]
@michaelcplusplus @epopoee Thanks for the contributions. Would you like to submit a PR for `emq-relx` project? I'd like to merge the fix to `windows` branch.

**Comment by michaelcplusplus** [comment]
My solution is just a manual woraround.
I can not initiate a pull request for these manual steps.

**Comment by epopoee** [comment]
Fully agree with Michael

Von: Michael [mailto:notifications@github.com]
Gesendet: Dienstag, 9. Januar 2018 09:26
An: emqtt/emqttd
Cc: Eike Pögel; Mention
Betreff: Re: [emqtt/emqttd] Recommend way to run emqttd 2.0 on windows (#803)


My solution is just a manual woraround.
I can not initiate a pull request for these manual steps.

**Comment by twmarr** [comment]
Is there an ETA on When this would be fixed so that manual steps do not have to be done?

**Comment by emqplus** [comment]
@twmarr Considering to support HotConfig and workaround this issue on windows platform.

**Comment by fengbozs** [comment]
@michaelcplusplus @epopoee Thank you very much for solving my problem, but by installing the service in this way, port 18083 did not open properly (emqttd 2.3.11)？

**Comment by michaelcplusplus** [comment]
Don't have this problem. Maybe You have a port conflict.

**Comment by yasithab** [comment]
You do not need to do any modifications in **emqttd.cmd** script if you are using the latest builds. Tested on EMQ 2.3.11 and 3.0.1. Please find the complete configuration guide [here](https://notebook.yasithab.com/windows/configure-emqtt-as-a-windows-service).
