### ISSUE TITLE
Docker image (alpine) install tzdata package

### ISSUE THREAD

**Issue by xray-bit** [emqx/emqx#8052]
### What would you like to be added or enhanced?

目前 Docker 镜像内没有 tzdata 包，导致时区设置无法生效。

### Why is this needed?

Dashboard 内的时间与当地时间有时差。（日志时间是否有时差暂未测试）

**Comment by lafirest** [comment]
@xray-bit 
A workaround is manually install in alpine by `apk add tzdata`, or crate a new Dockerfile

**Comment by zmstone** [comment]
https://github.com/emqx/emqx/pull/8671
