### ISSUE TITLE
esp8266 ssl connect problem

### ISSUE THREAD

**Issue by shsjshentao** [emqx/emqx#806]
#### Environment

- OS: centos 6.7
- Erlang/OTP:  18
- EMQ:  2.0-rc3

#### Description

hardware esp8266 always encounter ssl connection problem. It sometimes got stuck in reconnection process to 8883 port and got none response. 
And i tried it is ok in the Baidu IOT platform. It can reconnect properly all the time.
The following is the emq crash report when problem happens.

=CRASH REPORT====
  crasher:
    initial call: emqttd_client:init/1
    pid: <0.10002.4>
    registered_name: []
    exception error: {{ssl_error,timeout},[{esockd_connection,upgrade,1,[{file,"src/esockd_connection.erl"},{line,113}]},{emqttd_client,init,1,[{file,"src/emqttd_client.erl"},{line,76}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,240}]}]}
    ancestors: [<0.8143.4>,<0.8142.4>,esockd_sup,<0.7946.4>]
    messages: []
    links: [<0.8143.4>]
    dictionary: []
    trap_exit: false
    status: running
    heap_size: 610
    stack_size: 27
    reductions: 2965
  neighbours:

**Comment by emqplus** [comment]
@shsjshentao please tune the `mqtt.listener.ssl.handshake_timeout` in etc/emq.conf:

```
mqtt.listener.ssl.handshake_timeout = 15000
```

**Comment by shsjshentao** [comment]
i have tried  to set 5,15 and 10000. And the problem still happen.

**Comment by emqplus** [comment]
@shsjshentao please discuss the issue with Rui Wang who is the author of NodeMCU:)

**Comment by vowstar** [comment]
@shsjshentao I've tested emq SSL and it is no problem with esp8266.
Please provide which SDK you use under esp8266?(ESP_NONOS_SDK or ESP_RTOS_SDK?)
And provide the SDK version.

Note: please try `espconn_secure_set_size` before `espconn_secure_accept`, and set SSL buffer size to 8192.
```
Function:
Set buffer size of encrypted data (SSL)
Note:
Buffer size default to be 2Kbytes. If need to change, please call this API before
espconn_secure_accept (ESP8266 as TCP SSL server) or espconn_secure_connect (ESP8266 as
TCP SSL client)
Prototype:
bool espconn_secure_set_size (uint8 level, uint16 size)
Parameters:
uint8 level : set buffer for ESP8266 SSL server/client:
0x01 SSL client;
0x02 SSL server;
0x03 both SSL client and SSL server
uint16 size : buffer size, range: 1 ~ 8192, unit: byte, default to be 2048
Return:
true : Success
false : Failure
```

EMQ support TLS1.1 and TLS1.2, the default SDK only support TLS1.1.
If you want use TLS1.2, you can try mbedtls, it support TLS1.2.

Note: SSL (may) required 20kB of esp8266 ram. Please check heap before do SSL.

**Comment by shsjshentao** [comment]
@vowstar 

SDK version: ESP8266 NONOS SDK V2.0.0 20160810
example program：esp_mqtt_proj
condition：SSL one-way authentication、close CA authentication，sometimes will get stuck in client handshake start.

Log information:

MQTT_InitConnection
MQTT_InitClient
TCP: Connect to ip  121.43.109.135:8883
please start sntp first !
client handshake start.
pm open,type:2 0
