### ISSUE TITLE
Using HTTP API for message distribution, response time is too long 

### ISSUE THREAD

**Issue by abhello** [emqx/emqx#8069]
### What happened?

使用http pai 向该主题发送消息耗时很长，需要6秒多，但是发给其他主题就很快，基本秒发，请问这是怎么回事？
![3SUIC% )ZS_EL{C(@QV41P9](https://user-images.githubusercontent.com/17737525/170679520-c5ce7db8-ac41-4f6d-be7d-707aa93290f0.png)
![image](https://user-images.githubusercontent.com/17737525/170679654-5eb5c42c-5a8e-4ea0-90ec-8a2a83dc8d66.png)

### What did you expect to happen?

感谢

### EMQX version

<details>

```console
$ ./bin/emqx_ctl broker
# paste output here
```

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Log files

<details>

</details>

**Comment by lafirest** [comment]
@abhello  Hello, Did you enable some other module/plugin/hooks? 
Maybe you can trace this topic to find the reason why.

The `trace` doc:
https://www.emqx.io/docs/en/v4.3/getting-started/log.html#log-trace-2

**Comment by HJianBo** [comment]
Hi @abhello Sorry for lately reply here. Is this true for all topics publish or only for some special topics?
