### ISSUE TITLE
Does broker support TLS-PSK based encryption option?

### ISSUE THREAD

**Issue by sanket-kulkarni-vmware** [emqx/emqx#809]
I haven't find TL-PSK based encryption option for the broker. Can you please confirm?

**Comment by HarishHothi** [comment]
Hi
   I was evaluating emqtt broker for our IoT product. We need to support TLS-PSK based encryption. Is there any planned road-map to include this feature?

**Comment by imZack** [comment]
Any updates?

**Comment by andy2046** [comment]
@emqplus hi Feng, may I check with you the progress for this enhancement? thanks.

**Comment by Gilbert-Wong** [comment]
This feature has been implemented in emqx 3.1-beta2. Thanks for your advice.
