### ISSUE TITLE
系统重启无法自动拉起服务

### ISSUE THREAD

**Issue by krystal23** [emqx/emqx#8109]
### What happened?

error:(no logger present) unexpected logger message: {log,error,"~s~n",["beam/beam_load.c(2314): Error loading function xmerl_sax_parser_latin1:parse_content/4: op i_call x:\n  no specific operation found\n"],#{error_logger=>#{emulator=>true,tag=>error},gl=><0.0.0>,pid=><0.722.0>,time=>1653965105290765}}

{"init terminating in do_boot",{load_failed,[xmerl_sax_parser_latin1]}}

init terminating in do_boot ({load_failed,[xmerl_sax_parser_latin1]})

### What did you expect to happen?

手动拉起

### EMQX version

<details>

```console
$ ./bin/emqx_ctl broker
# paste output here
```

</details>
v4.1.2

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>
cenots7

### Log files

<details>
(no logger present) unexpected logger message: {log,error,"~s~n",["beam/beam_load.c(2314): Error loading function xmerl_sax_parser_latin1:parse_content/4: op i_call x:\n  no specific operation found\n"],#{error_logger=>#{emulator=>true,tag=>error},gl=><0.0.0>,pid=><0.722.0>,time=>1653965105290765}}

{"init terminating in do_boot",{load_failed,[xmerl_sax_parser_latin1]}}

init terminating in do_boot ({load_failed,[xmerl_sax_parser_latin1]})
</details>

**Comment by zmstone** [comment]
Looks like a corrupted installation.
Maybe consider reinstall, and upgrade to latest version 4.4. 4.1 is no longer in maintenance
