### ISSUE TITLE
Helm Chart Source Code

### ISSUE THREAD

**Issue by mindrunner** [emqx/emqx#8128]
### What would you like to be added or enhanced?

The Helm chart source code in `master` branch looks very different to the source I am getting when downloading via `helm pull`. 
Can someone please clarify?

Some things I noted:

- In `master` branch a recent commit seemed to have removed mgmt ingress support. What is the reason for that? How am I supposed to expose the management api?

- The `helm pull` chart v4.4.4 was supposed to include monitoring support for prometheus. However, the `service-monitor.yml` is not part of the chart templates. I kinda looks like someone put it into the wrong folder. 

### Why is this needed?

consistency

**Comment by zmstone** [comment]
Hi @mindrunner 
Master branch is release (candidate  at the moment) for 5.0
Please check `main-v4.4` branch.

**Comment by mindrunner** [comment]
Cool, that makes more sense then!

Still:
- https://github.com/emqx/emqx/commit/628b57038d5692a524519c39b69ed341ab5ea272#r75249088

Also, chart version in `master` is `4.4.1`

**Comment by zmstone** [comment]
probably because 5.0 branched off from 4.4.1
we have not managed to fix helm for 5.0 yet.

**Comment by mindrunner** [comment]
Still confused. `main` branch shows outdated chart (`4.4.1`). Where is the source for chart `5.0.3` hosted?

**Comment by Rory-Z** [comment]
> Still confused. `main` branch shows outdated chart (`4.4.1`). Where is the source for chart `5.0.3` hosted?

Hi, @mindrunner Never mind the version in Chart.yaml for the main branch, it is inaccurate.

**Comment by mindrunner** [comment]
got it, thanks
