### ISSUE TITLE
How does docker start HTTP authentication?

### ISSUE THREAD

**Issue by bbhxwl** [emqx/emqx#8130]
How does docker start HTTP authentication?

**Comment by lafirest** [comment]
You can enable the plugin by `emqx_ctl` or the dashboard, and start your HTTP Authn server before this.

**Comment by bbhxwl** [comment]
> You can enable the plugin by `emqx_ctl` or the dashboard, and start your HTTP Authn server before this.

```
etc/plugins/emqx_auth_http.conf
```
I understand the wrong path.
I thought it was down the path
/etc/plugins/emqx_auth_http.conf

**Comment by zmstone** [comment]
is this still an issue ? or can be closed ?
