### ISSUE TITLE
I can successfully connect with c\mqttnet, but the subscription keeps making mistakes.

### ISSUE THREAD

**Issue by bbhxwl** [emqx/emqx#8137]
### What happened?

I can successfully connect with c\mqttnet, but the subscription keeps making mistakes.
But I can successfully subscribe to other people's mqtts by connecting them with csharp?

Even if you use web tools and WS connection, the subscription will be very slow in a few seconds.

### What did you expect to happen?

But I can successfully subscribe to other people's mqtts by connecting them with csharp?

### EMQX version

docker run -itd  --restart=always --name emqx -p 1883:1883 -p 8081:8081 -p 8083:8083 -p 8883:8883 -p 8084:8084 -p 18083:18083 emqx:latest 

 Today's latest version

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Log files

<details>

</details>

**Comment by tigercl** [comment]
@bbhxwl Hi. We may need more information to help you locate this issue:
1. The reason code in the SUBACK received by the client when subscribing fails. The method of obtaining is determined by your client library implementation
2. EMQX logs, you can view them through `docker logs`
