### ISSUE TITLE
How do I set up the WSS protocol? Access using HTTPS website?

### ISSUE THREAD

**Issue by bbhxwl** [emqx/emqx#8172]
### What would you like to be added or enhanced?

How do I set up the WSS protocol? Access using HTTPS website?

### Why is this needed?

![image](https://user-images.githubusercontent.com/26525599/173000411-81bbff2f-16db-47cf-bec1-ceae124cce83.png)

**Comment by melgo-tb** [comment]
@bbhxwl this worked for me.

Use certbot to generate SSL certificates ([https://certbot.eff.org/])
`sudo certbot certonly --standalone -d example.com `

It generates the below files at /etc/letsencrypt/live/$domain
## the issued certificate 
cert.pem
## the certificate with intermediate certificates
fullchain.pem
## the cert chain between issued certificate and CA certificat
## intermediate certificates
chain.pem
## Private key for the certificate

Copy the certificates from  /etc/letsencrypt/live/$domain to /etc/emqx/certs

Edit the following lines of emqx.conf :


```
listener.wss.external.keyfile = /etc/emqx/certs/privkey.pem
listener.wss.external.certfile = /etc/emqx/certs/fullchain.pem
listener.wss.external.cacertfile = /etc/emqx/certs/chain.pem
```

**Comment by zmstone** [comment]
@melgo-tb  thank you for the solution.
@bbhxwl could you check if the suggested configurations work for you?

**Comment by bbhxwl** [comment]
> @melgo-tb thank you for the solution. @bbhxwl could you check if the suggested configurations work for you?

I don't know the recommended configuration. I use the emqx deployed by docker, and then use the nginx reverse proxy to set the WSS
