### ISSUE TITLE
emqttd_ctl REST API

### ISSUE THREAD

**Issue by brylie** [emqx/emqx#820]
# Context
Many EMQ configuration steps are done via the [`emqttd_ctl` command line utility](http://emqtt.io/docs/v2/commands.html). However, third party services, which may be running over the Internet, do not have an easy way to access EMQ via command prompt.

# Idea
> As a systems integrator
I would like to control EMQ via a REST API
so that I can manage EMQ from within our project code

It would be useful to configure EMQ via an HTTP REST API. For example, the REST API could closely resemble the structure of `emqttd_ctl` commands.

**Comment by emqplus** [comment]
@brylie Yeah, we are working on the Monitor/Management/Control APIs these days:) A preview screenshot of the monitor dashboard: 

![Uploading 3866666C264878DBFD7A61536BA40829.png…]()

**Comment by brylie** [comment]
> we are working on the Monitor/Management/Control APIs these days:)

Will these APIs be accessible via REST? Where may we see the work in progress?

Specifically, we may need an endpoint to create EMQ **HTTP users**, for authentication and creating ACL rules.

**Comment by brylie** [comment]
@emqplus the dashboard looks very nice. Great work :smiley: 

Could you please respond to the question(s) regarding the EMQ management REST API?

**Comment by brylie** [comment]
Based on a question in a different issue, here are a couple of API design guides that I have found recently:

- Google [Api Design Guide](https://cloud.google.com/apis/design/)
- Zalando [RESTful API guidelines](https://github.com/zalando/restful-api-guidelines)

**Comment by willin** [comment]
mark

**Comment by zhengyupan** [comment]
Hi @brylie , A REST API is available since v2.3, please refer to this link for details:
https://emq-docs-en.readthedocs.io/en/latest/rest.html
