### ISSUE TITLE
After updating emqx from 4.3.10 to 4.4.4 errors are coming

### ISSUE THREAD

**Issue by Aravindms369** [emqx/emqx#8200]
### Discussed in https://github.com/emqx/emqx/discussions/8199

<div type='discussions-op-text'>

<sup>Originally posted by **Aravindms369** June 13, 2022</sup>
emqx: 4.4.4

I have migrated my emqx from 4.3.10 to 4.4.4 for removing the e-redis client error and generic server terminating error. After migration we are receiving below errors in the logs. device operations are working fine.

**[warning]** [SYSMON] long_schedule warning: pid = <****>, info: [{timeout,366}, {in,{prim_inet,accept0,3}}, {out, {ranch_conns_sup, start_protocol,2}}], [{memory,***},{total_heap_size,**},{heap_size,**},{stack_size,9},{min_heap_size,*},{initial_call,{ranch_acceptor,loop,4}},{current_stacktrace,[{ranch_conns_sup,start_protocol,2,[{file,"ranch_conns_sup.erl"},{line,72}]},{ranch_acceptor,loop,4,[{file,"ranch_acceptor.erl"},{line,34}]}]},{registered_name,[]},{status,waiting},{message_queue_len,0},{group_leader,<**>},{priority,normal},{trap_exit,false},{reductions,104139702},{last_calls,false},{catchlevel,0},{trace,0},{suspending,[]},{sequential_trace_token,[]},{error_handler,error_handler}]

**[error]** supervisor: 'esockd_connection_sup - <***>', errorContext: connection_shutdown, reason: {ssl_error,{tls_alert,{certificate_required,"TLS server: In state wait_cert at tls_handshake_1_3.erl:1475 generated SERVER ALERT: Fatal - Certificate required\n certificate_required"}}}, offender: [{pid,<****>},{name,connection},{mfargs,{emqx_connection,start_link,[[{deflate_options,[]},{max_conn_rate,500},{active_n,100},{zone,external},{proxy_address_header,<<>>},{proxy_port_header,<<>>},{supported_subprotocols,[]}]]}}]

**[error]** supervisor: 'esockd_connection_sup - <****>', errorContext: connection_shutdown, reason: {ssl_error,{tls_alert,{unexpected_message,"TLS server: In state hello at tls_record.erl:558 generated SERVER ALERT: Fatal - Unexpected Message\n {unsupported_record_type,71}"}}}, offender: [{pid,<****>},{name,connection},{mfargs,{emqx_connection,start_link,[[{deflate_options,[]},{max_conn_rate,500},{active_n,100},{zone,external},{proxy_address_header,<<>>},{proxy_port_header,<<>>},{supported_subprotocols,[]}]]}}]

please help to resolve the same.</div>

**Comment by zmstone** [comment]
the long schedule warning can be solved by throwing more CPU resource at it.
the other two errors are emitted from OTP ssl library, likely some malfunctioning clients not able to complete SSL handshake.

**Comment by Aravindms369** [comment]
Thank you @zmstone for the reply.

**Comment by Aravindms369** [comment]
Hi @zmstone

Thanks for the reply.

We have not found any particular client that is malfunctioning. As of now every client and all operations are working fine only.

In 4.3.10 we didn't observe this issue. There is more number of clients so its difficult to check on them one by one.

**Comment by zmstone** [comment]
thanks. Ok to close the issue?

**Comment by Aravindms369** [comment]
For now, we can close this issue. If these logs are persisting we can re-open this issue.
Thanks.

**Comment by Aravindms369** [comment]
Hi @zmstone 

Can we change the log level of these error logs to warning/debug?

**Comment by Aravindms369** [comment]
@zmstone Thanks for the reply.
