### ISSUE TITLE
redis authentication failing

### ISSUE THREAD

**Issue by Aravindms369** [emqx/emqx#8201]
### Discussed in https://github.com/emqx/emqx/discussions/8196

<div type='discussions-op-text'>

<sup>Originally posted by **Aravindms369** June 13, 2022</sup>
emqx-version:4.3.10
redis - Azure redis cache

we are getting below logs while client trying to connect to redis through emqx_auth_redis plugin for authentication:

The errors are repeating for a particular clients only.

[warning] ****@**** [Channel] Client **** (Username: '****') login failed for not_authorized
[error] ****@**** [Redis] Auth from redis failed: not_authorized

What all are the scenarios in which we can get these authentication errors?

Please help in the same to resolve.</div>

**Comment by zmstone** [comment]
Closed issue.
Let’s follow up from the discussion
