### ISSUE TITLE
Publish to Hex.pm

### ISSUE THREAD

**Issue by varnerac** [emqx/emqx#823]
It'd be nice to publish emqttd to the Hex package manager, since it can be embedded in other Erlang apps.

**Comment by emqplus** [comment]
@varnerac We cannot publish the emqttd package to hex.pm for there are some dependencies missed.

**Comment by varnerac** [comment]
What dependencies?

**Comment by emqplus** [comment]
Dependencies:

```
DEPS = gproc lager gen_logger esockd mochiweb

dep_gproc       = git https://github.com/uwiger/gproc
dep_getopt      = git https://github.com/jcomellas/getopt v0.8.2
dep_lager       = git https://github.com/basho/lager master
dep_gen_logger  = git https://github.com/emqtt/gen_logger
dep_esockd      = git https://github.com/emqtt/esockd master
dep_mochiweb    = git https://github.com/emqtt/mochiweb
```

**Comment by Gilbert-Wong** [comment]
Hex package support would be finished before 3.1-beta.1 release.

**Comment by Gilbert-Wong** [comment]
Hi, @varnerac, ecpool, ekka, emqx_ct_helpers, esockd and replayq have been released on hex.pm. However, we have no plan to publish emqx package on hex.pm for now.
