### ISSUE TITLE
MacOS executable not recognized as valid, developer not identified by Apple.

### ISSUE THREAD

**Issue by cocoaway** [emqx/emqx#8250]
### What happened?

The executable was compiled for macOS but without the necessary permissions as Apple developer.

Security and privacy raises the error in macOS Catalina.

erl, erlexec etc ... are classified as unauthorized apps.

### What did you expect to happen?

That the app runs without raising security exceptions.

### How can we reproduce it (as minimally and precisely as possible)?

Download the emqx-5.0.0-rc.4-otp24.2.1-1-macos10-amd64.tar.gz file from your github repo, unzip and run ./emqx start from the / bin dir.

The error window opens immediately with the request to move the app to the trash bin.

### EMQX version

5.0.0-rc.4

### OS version

macOS Catalina 10.15

### Log files

<details>

</details>

**Comment by zmstone** [comment]
Hi @cocoaway 
We are working on it.

**Comment by zmstone** [comment]
Starting from 5.0.9, macOS packages will be signed.
fixed in: https://github.com/emqx/emqx/pull/8897
