### ISSUE TITLE
plugin config file endwith .config doesn't copy to etc/plugins/  when do make

### ISSUE THREAD

**Issue by helloyan** [emqx/emqx#8258]
### What would you like to be added or enhanced?

when do make ,plugin config file endwith .conf can copy to  etc/plugins/  ,but .config can't ,  can support it ?

### Why is this needed?

don't need copy it manually

**Comment by lafirest** [comment]
Hi, @helloyan , Does there has some must reason to use the `.config` extensions?

**Comment by helloyan** [comment]
it's origin format of erlang, when develop plugins, it's more flexible

**Comment by lafirest** [comment]
@wivwiv Hi,
There has a simple feature

**Comment by wivwiv** [comment]
I think so. how do you think @zmstone

**Comment by helloyan** [comment]
make emqx-pkg / emqx-zip also depend on the .conf file , if i use .config, it report error
![image](https://user-images.githubusercontent.com/1699033/174299586-0649d286-f326-4827-a1fc-c65efe9fa25e.png)

**Comment by zmstone** [comment]
Hi @helloyan 
Always happy to see plug-in developments from the community.
From the information so far, I’m not sure what you are trying to achieve,
Would be good if you can share your source code.
Or provide the git diff you applied on top of emqx 4.4.4.

**Comment by helloyan** [comment]
i don't known how to change the makefile, if i use the change_emqx.conf in etc/ like below, when use this plugin in emqx 4.4.4, " make "  will copy change_emqx.conf to  _build/emqx/rel/emqx/etc/plugins/change_emqx.conf  automatically
![image](https://user-images.githubusercontent.com/1699033/174428106-86f73118-50f7-492a-9458-71358bceb400.png)

but when i use change_emqx.config, it won't
![image](https://user-images.githubusercontent.com/1699033/174428061-33386389-fd20-49cf-8f81-50c392e76ce8.png)

so i want it copy the change_emqx.config in Makefile

**Comment by zmstone** [comment]
Plugin config files copy logic is defined in rebar.config.erl. 
I guess you can add a new wildcard pattern here:
https://github.com/emqx/emqx/blob/b7762ede6eab2ada1fc176642d51c41ca30423c5/rebar.config.erl#L401-L410

**Comment by helloyan** [comment]
![image](https://user-images.githubusercontent.com/1699033/174469317-729087dc-0ca5-4ad5-8d5f-dcb347f5539d.png)

I change the code and now it's ok
