### ISSUE TITLE
Storing persistent client sessions after broker restart.

### ISSUE THREAD

**Issue by sanket-kulkarni-vmware** [emqx/emqx#827]
#### Environment

- OS: CentOS 6
- Erlang/OTP: 19
- EMQ: Erlang MQTT Broker 2.0.3

I am facing the issue to store persistent client sessions after broker restart. Does this feature currently not present in the broker or I missing some configuration?

**Comment by emqplus** [comment]
@sanket-kulkarni-vmware The broker will not persist sessions.

**Comment by sanket-kulkarni-vmware** [comment]
@emqplus Thank you for the clarification. Could you please share what is planned release date for 2.0.5 version?

**Comment by emqplus** [comment]
Plan to tag 2.0.5 this Friday.

**Comment by sanket-kulkarni-vmware** [comment]
@emqplus: I have tested EMQTT 2.0.5 version for this feature but looks like this feature is not incorporated into it or do I need to make changes into config file to work this feature?

**Comment by turtleDeng** [comment]
@sanket-kulkarni-vmware The broker will not persist sessions.
