### ISSUE TITLE
EMQ disconnects clients on publishing messages

### ISSUE THREAD

**Issue by mfick76** [emqx/emqx#828]
#### Environment

- OS: Debian 8.6
- Erlang/OTP: esl-erlang_19.2-1~debian~jessie_amd64.deb
- EMQ: emqttd-2.0.3

#### Description

I have a setup where the broker is running on a single linux server using the settings from the optimization guide "tuning emq". 
On the client side I use the PAHO C Library.
The test program connects 10 ! clients to Server (mqtt 1883) and then starts to send as many messages as possible (no subscriber active). 

It's a simple for(;;) MQTTClient_publish(...)

For some reason the server disconnects my clients as seen below:
   published 97 messages in 1 second
   published 101 messages in 1 second
   published 93 messages in 1 second
   v_MQTTClient_connectionLost client=client_00001 cause=(null)
   Connecting
   Connected
   published 144 messages in 1 second
   published 350 messages in 1 second

If I exchange emqttd with Mosquitto the client is not disconnected, so I seems to be on the server side! 

What's going wrong ?

**Comment by emqplus** [comment]
@mfick76 `./bin/emqttd_ctl listeners` to check the `shutdown_count`, for example:

```
listener on mqtt:tcp:1883
  acceptors       : 8
  max_clients     : 1024
  current_clients : 0
  shutdown_count  : [{closed,1}]
```

**Comment by Tabrizian** [comment]
I have this problem too. Is there anyway to fix it?
