### ISSUE TITLE
On v5.0.0 alpine docker image, http authentication ${password} variable not being substituted 

### ISSUE THREAD

**Issue by atlantis** [emqx/emqx#8318]
### What happened?

When I receive the HTTP request from my web app, the $(username) variable in the HTTP body setting is substituted just fine, but not the password, so I get:

`{"password" => "${password}", "username" => "bob"}`

### What did you expect to happen?

`{"password" => "mypasswordhere", "username" => "bob"}`

### Anything else we need to know?

I'm connecting from a MQTT v3 client if that matters?

### EMQX version

<details>

sysdescr  : EMQX
version   : 5.0.0
datetime  : 2022-06-24T22:36:30.946687927+00:00
uptime    : 32 minutes, 0 seconds
</details>

### OS version

<details>

NAME="Alpine Linux"
ID=alpine
VERSION_ID=3.15.1
PRETTY_NAME="Alpine Linux v3.15"
HOME_URL="https://alpinelinux.org/"
BUG_REPORT_URL="https://bugs.alpinelinux.org/"
Linux 7028b4e97709 5.10.47-linuxkit #1 SMP Sat Jul 3 21:51:47 UTC 2021 x86_64 Linux
</details>

### Log files

<details>

</details>

**Comment by atlantis** [comment]
here's the client command I'm using: `mosquitto_sub -h 127.0.0.1 -p 1883 -u bob -P mypasswordhere -t #`

**Comment by zmstone** [comment]
Hi @atlantis 
Thank you for the report.
We’ll looking into it.
Could you share the `authentication` block of the config ? If it’s created from the dashboard, it can be found in data/configs/cluster-override.conf`

**Comment by atlantis** [comment]
Whoops my bad! I had http set up as authorization rather than authentication... thanks for your time!
