### ISSUE TITLE
EMQX 5.0 Access Control Authentication HTTP Server disconnected

### ISSUE THREAD

**Issue by dsilletti** [emqx/emqx#8322]
### What happened?

using EMQX 5.0 Docker container, if the EMQX container starts before the HTTP Authentication container, the backend status in EMQX HTTP Authentication page remains disconnected and it does not reconnect until I disable and enable the HTTP Server Authentication. 

My Control Authentication HTTP Server settings:

Connect timeout: 30 seconds
Request timeout: 5 seconds

### What did you expect to happen?

The EMQX 5.0 Authentication HTTP client should reconnect automatically to the Authentication Server if gets disconnected or if is not reachable on startup. 

### EMQX version

EMQX 5.0.0 official Docker container

### OS version

- Ubuntu 20.04.4 LTS
- Docker 20.10.17 (swarm mode)

**Comment by atlantis** [comment]
Just noticed this as well - definitely problematic for a production environment if a human has to reset it after a network blip. Version 5 and the new dashboard are really great overall tho!

**Comment by zmstone** [comment]
fixed in: https://github.com/emqx/emqx/pull/8371
v5.0.1 is being released now.

**Comment by dsilletti** [comment]
@zmstone Unfortunately the fix broke completely the authentication (and probably the authorization as well)

Plese see https://github.com/emqx/emqx/issues/8389

**Comment by zmstone** [comment]
> @zmstone Unfortunately the fix broke completely the authentication (and probably the authorization as well)
> 
> Plese see #8389

Thank you for the quick feedback.
I have indeed noticed some compatibility break changes made in the fix.
Commented in #8389.
Let’s follow up from there
