### ISSUE TITLE
DST Root CA X3 Expiration (September 2021) and i cant make a wss connection

### ISSUE THREAD

**Issue by EgHubs** [emqx/emqx#8343]
### What happened?

I'm trying to make my connection on wss
i have read through the documates and here is what I did

1-installing with the following link
[https://www.emqx.io/docs/en/v3.0/install.html#ubuntu](https://www.emqx.io/docs/en/v3.0/install.html#ubuntu)

2- changed emqx.conf as follows

> allow_anonymous=true

3- changed the emqx_auth_mnesia.conf file as follows

> ## The second group of authentication data
> auth.user.2.username = id
> auth.user.2.password = passwd

then 

`§ emqx_ctl plugins load emqx_auth_mnesia
`

now I can access the MQTT with the id and passwd with 8083 port 

Now when I try to try to make it over SSL I followed the following article to get the cert files with letsencrypt
[https://emqx.medium.com/using-lets-encrypt-certificates-in-emq-b11e0e57efa6](https://emqx.medium.com/using-lets-encrypt-certificates-in-emq-b11e0e57efa6)
and I did the following
skipped the producing of the cert files as I already have a running server with these cert files on the same exact domain
so I just pointed to these cert files from emqx.conf
I don't really care about securing the dashboard right now so also I will skip this for now(tried and failed also)
so I will just continue to point my files for was and SSL as follows

> listener.wss.external.keyfile = /etc/letsencrypt/live/$domain/privkey.pem
> listener.wss.external.certfile = /etc/letsencrypt/live/$domain/fullchain.pem

and tried to connect over port 8084 with SSL checked on the dashboard and i failed, also tried with a program called mqtt explorer and failed to connect
also tried 

> listener.ssl.external.keyfile = /etc/letsencrypt/live/$domain/privkey.pem
> listener.ssl.external.certfile = /etc/letsencrypt/live/$domaion/fullchain.pem

and still won't work
so i decided to try to add ca.pem file
So first we have a paragraph that is talking about **Mutual certificate authentication**
In this paragraph, you talking about the **DST_Root_CA_X3.pem** file which is deprecated and doesn't exist in my folder file as stated [here](https://letsencrypt.org/docs/dst-root-ca-x3-expiration-september-2021/)
so I tried to use the new file
cat /etc/ssl/certs/ISRG_Root_X1.pem /etc/letsencrypt/live/domainname.com/chain.pem > ca.pem
and added it in the conf file in both was and SSL and failed to connect
like the following

> listener.wss.external.cacertfile = /etc/letsencrypt/live/$domain/ca.pem
> listener.ssl.external.keyfile = /etc/letsencrypt/live/$domain/privkey.pem
> listener.ssl.external.certfile = /etc/letsencrypt/live/$domaion/fullchain.pem
> listener.ssl.external.cacertfile = /etc/letsencrypt/live/$domaion/ca.pem

and still can't get in when i try to connect with the following
`mosquitto_sub -t abc -h localhost -p 8883 -d  --cafile /etc/letsencrypt/live/mydomain.com/ca.pem -u "id2" -P "passwd"
`
it just keep giving me the following

> Client null sending CONNECT
> Client null sending CONNECT
> Client null sending CONNECT
> Client null sending CONNECT

what I'm doing wrong?
What should I do?

### What did you expect to happen?

To be able to generate the following
1-MQTT with wss
2-MQTT with was with mutual cert to try to use it in the esp8266 
but for the pas part I have noticed some examples of that that they use something like this
`static const char *fingerprint PROGMEM = "44 14 9A 3F C3 E9 F1 F3 84 1A B4 9F B6 4D 19 8A B2 92 31 D6";
`
where can I get that, I opened the ca.pem file and there is nothing similar
It was like this

> -----BEGIN CERTIFICATE-----
> MIIFazCCA1OgAwIBAgIRAIIQz7DSQONZRGPgu2OCiwAwDQYJKoZIhvcNAQELBQAw
> anything
> anything
> anything
> anything
> anything
> anything
> anything
> anything
> anything
> anything
> emyPxgcYxn/eR44/KJ4EBs+lVDR3veyJm+kXQ99b21/+jh5Xos1AnX5iItreGCc=
> -----END CERTIFICATE-----
> -----BEGIN CERTIFICATE-----
> MIIFFjCCAv6gAwIBAgIRAJErCErPDBinU/bWLiWnX1owDQYJKoZIhvcNAQELBQAw
> anything
> anything
> anything
> anything
> anything
> anything
> anything
> anything
> anything
> anything
> MldlTTKB3zhThV1+XWYp6rjd5JW1zbVWEkLNxE7GJThEUG3szgBVGP7pSWTUTsqX
> nLRbwHOoq7hHwg==
> -----END CERTIFICATE-----
> 
> -----BEGIN CERTIFICATE-----
> MIIFYDCCBEigAwIBAgIQQAF3ITfU6UK47naqPGQKtzANBgkqhkiG9w0BAQsFADA/
> anything
> anything
> anything
> anything
> anything
> anything
> anything
> anything
> anything
> anything
> Dfvp7OOGAN6dEOM4+qR9sdjoSYKEBpsr6GtPAQw4dy753ec5
> -----END CERTIFICATE-----

thanks in advance

### How can we reproduce it (as minimally and precisely as possible)?

already described

### EMQX version

<details>

```console
sysdescr  : EMQ X Broker
version   : 4.3.5
uptime    : 21 minutes, 13 seconds
datetime  : 2022-06-29 09:45:33
```

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
NAME="Ubuntu"
VERSION="20.04.4 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.4 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
$ uname -a
Linux xxxx 5.4.0-121-generic #137-Ubuntu SMP Wed Jun 15 13:33:07 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```

</details>

### Log files

<details>
there is no bin folder in my EMQX folder!
that's what in it

> acl.conf  certs  emqx.conf  lwm2m_xml  plugins  psk.txt  ssl_dist.conf  vm.args

</details>

**Comment by zmstone** [comment]
> 400 BAD_PLUGIN_INFO:bad_name_vsn:emqx_auth_mnesia.tar.gz

For 5.0, a plugin has to be built by a rebar plugin.
you can find the template rebar3 project here:
https://github.com/emqx/emqx-plugin-template

**Comment by zmstone** [comment]
```
listener.ssl.external.keyfile = /etc/letsencrypt/live/$domain/privkey.pem
listener.ssl.external.certfile = /etc/letsencrypt/live/$domaion/fullchain.pem
listener.ssl.external.cacertfile = /etc/letsencrypt/live/$domaion/ca.pem
```
this configuration seem to be fine, but please confirm:
the fist certificate in fullchain.pem should be the server's certificate
Also please check if emqx runner user (user `emqx` when installed from rpm or deb package) has the read permission to the files (including the parent dirs), and only the runner user has permission to read the private key.

**Comment by zmstone** [comment]
execute: `openssl s_client -showcerts -connect localhost:8883 < /dev/null` for quick verification if the listener started ok also to inspect handshake procedure.

**Comment by zmstone** [comment]
> the repo states to see the docs at the last line without any given link
I dug through the docs and I can`t find any
Do you mean [this](https://www.emqx.io/docs/en/v4.3/advanced/plugins.html#compile-and-publish-the-plugin)?
I guess I will wait until the docs have been updated so I can use v5.0.

Sorry, for how to deploy, the doc isn't quite ready.
However, you seem to have already found how to do it from the dashboard,
from the BAD_REQUEST message, it seems the package name is not following `name-vsn.tar.gz` format. e.g. `my_plugin-0.1.0.tar.gz`.
Actually, If it's built from the new rebar3 project, the package should have this name.

**Comment by zmstone** [comment]
> i`ve tried to move all cert files to the /etc/emqx/certs/
to make sure that it's not a permission error.

this is a good call.
with the default certs, you should be able to observe below outputs from openssl command:
```
CONNECTED(00000003)
Can't use SSL_get_servername
depth=0 C = CN, ST = hangzhou, O = EMQ, CN = Server
verify error:num=20:unable to get local issuer certificate
verify return:1
depth=0 C = CN, ST = hangzhou, O = EMQ, CN = Server
verify error:num=21:unable to verify the first certificate
verify return:1
---
Certificate chain
 0 s:C = CN, ST = hangzhou, O = EMQ, CN = Server
   i:C = CN, ST = hangzhou, O = EMQ, CN = RootCA
---
Server certificate
-----BEGIN CERTIFICATE-----
xxxxxx
-----END CERTIFICATE-----
subject=C = CN, ST = hangzhou, O = EMQ, CN = Server

issuer=C = CN, ST = hangzhou, O = EMQ, CN = RootCA

---
No client certificate CA names sent
Peer signing digest: SHA256
Peer signature type: RSA-PSS
Server Temp Key: X25519, 253 bits
---
SSL handshake has read 1347 bytes and written 363 bytes
Verification error: unable to verify the first certificate
---
New, TLSv1.3, Cipher is TLS_AES_256_GCM_SHA384
Server public key is 2048 bit
Secure Renegotiation IS NOT supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
Early data was not sent
Verify return code: 21 (unable to verify the first certificate)
---
DONE
```
So we know better now that it's probably something with the certificates.

**Comment by zmstone** [comment]
If I try openssl on the plaintext TCP port, it's this:
```
> openssl s_client localhost:1883 </dev/null
CONNECTED(00000003)
write:errno=0
---
no peer certificate available
---
No client certificate CA names sent
---
SSL handshake has read 0 bytes and written 283 bytes
Verification: OK
---
New, (NONE), Cipher is (NONE)
Secure Renegotiation IS NOT supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
Early data was not sent
Verify return code: 0 (ok)
---
```
so maybe the ssl listener was not configured with ssl options.
could you share your configs ?

**Comment by zmstone** [comment]
> just found this [package](https://github.com/emqx/rebar3_emqx_plugin) which states that I have to install erlang and then install rebar3 so I can make a plugin which I tried but it takes more than 1.3 GB of server memory which is a lot of stuff to do to just get the tar.zip for your plugins, which I guess they should be available to download from a single command am I getting this right?

This is like 3 years old (before I joined the project),
I myself doesn't know it existed until now.
To develop your own plugin for 5.0, https://github.com/emqx/emqx-plugin-template is the only reference you need to take.
(Please Ignore the last line in README, when the document is in place, it'll be screenshots from the dashboard Plugin management UI).
<img width="855" alt="image" src="https://user-images.githubusercontent.com/164324/176499348-d7fe047d-2caa-4767-b333-c74d177dbc0b.png">

**Comment by zmstone** [comment]
>Steps to reproduce that file I have mentioned
1- updated to emqx 5 by removing the old package with
dpkg -P emqx
2- installed and started the new v5 package with the following link
https://www.emqx.io/downloads?os=Ubuntu
3- download the plugin folder from the following [link](https://github.com/emqx/emqx/tree/69abca17f236106adc05577b3017436d2d31818f/apps/emqx_auth_mnesia)
4- used the following command to make the tar package
tar -czf emqx_auth_mnesia-4.3.5.tar.gz emqx_auth_mnesia

I'm testing it out.

**Comment by zmstone** [comment]
wait, you are uploading the source code tar.gz ?
Just to get somethings clear before we go deeper:
* for mnesia auth, it's a builtin feature now in 5.0,(not a plugin), you can find how to use it in Accesson Control -> Authentication
<img width="530" alt="image" src="https://user-images.githubusercontent.com/164324/176500803-2acf585f-ab14-4312-9bdd-51568e67ede2.png">
* For your own plugin, you'll need to actually build a binary package instead of downloading the source code like "3- download the plugin folder from the following [link](https://github.com/emqx/emqx/tree/69abca17f236106adc05577b3017436d2d31818f/apps/emqx_auth_mnesia)"

**Comment by zmstone** [comment]
Hi.
Do you mean both 8883 (with the default certs) and 8084 (with your certs) are not working ?
For 5.0, the log file is `/var/log/emqx/emqx.log`

**Comment by zmstone** [comment]
some errors in the beginning are because HTTP request was sent to MQTT listener.

`{ssl_error,{options,{keyfile,"/etc/emqx/certsx/key.pem",{error,enoent}}}},` this error indicates there is no such a file `/etc/emqx/certsx/key.pem`

**Comment by zmstone** [comment]
> [error] at_state: <<"clean">>, input_bytes: <<"GET /mqtt HTTP/1.1\r\nSec-WebSocket-Version: 13\r\nSec-WebSocket-Key: 

This is because http(websocket) request was sent to a MQTT listener.
If you wish to test two websocket listeners?
You can change the listener name from `listeners.ssl.default`  to: `listeners.wss.myzome`

**Comment by zmstone** [comment]
> reason: {ssl_error,{tls_alert,{unexpected_message,"TLS server: In state hello at tls_record.erl:564 generated SERVER ALERT: Fatal - Unexpected Message\n 

this is SSL server failed to parse SSL messages. 
perhaps plaintext tcp packets were sent to the server’s SSL listener?

**Comment by zmstone** [comment]
> but please if you have time check these permissions if they vulnerable by any means

The private key should not need ANY write permission. 600

**Comment by zmstone** [comment]
Hi
The file names doesn’t matter.
What matters is the file content.
certfile has to contain the full chain, and the first certificate in this file has to be the certificate for the server (emqx ssl or wss listener) and followed by the issuer’s certificate (intermediate ca certificates) all the way to the root. (Well, Root is actually optional)
cacertfile should only contain the trusted root ca certificates.

from your configs, you have tried to enable `ssl` listener, also `wss` listener.
SSL listener talks MQTT protocol over TLS over TCP.
WSS stands for secure websocket, it’s MQTT over HTPP protocol over TLS over TCP.

You’ll have be clear which transport layer you want to test.

From the logs you shared, there seemed to be http request sent to the ssl listener, but not wss listener. Hence my first reply.

And there seem to be not secured TCP packets sent to the ssl listener causing TLS handshake to fail. Hence my second reply.

**Comment by zmstone** [comment]
You can find my email in git commit history.
If you write to me, we can set up a zoom call with screen share to troubleshoot.
It’ll be much easier for both of us.

**Comment by zmstone** [comment]
two issues:
1. private key path typo, the file doesn't exist
2. wss connection request was sent to ssl port.

For EMQX to improve: if private key file does not exist, write an error log.
