### ISSUE TITLE
The node service of emqx dashboard uses memory abnormally

### ISSUE THREAD

**Issue by imkos** [emqx/emqx#8404]
### What happened?

RT:

![image](https://user-images.githubusercontent.com/17872894/177066160-67921db6-4ddf-4d48-bfbd-88a971026f52.png)

### What did you expect to happen?

The memory display of emqx dashboard is normal

### EMQX version

emqx:4.4.5

**Comment by zmstone** [comment]
It seems to be the ram usage info from docker host?
@qzhuyan  @Rory-Z please help to correct me if I’m wrong:

if ram limit is applied from cgroup settings, I believe EMQX 4.4.5 has the ability to pick up the numbers:
https://docs.docker.com/config/containers/resource_constraints/

**Comment by imkos** [comment]
emqx: <=4.4.4
The memory value shows the memory used by the service, not the real-time memory of the host.
![image](https://user-images.githubusercontent.com/17872894/177108501-6a31bc30-dc4b-4560-ba94-1208a5486d7d.png)

**Comment by zmstone** [comment]
Hi @imkos 

This is an intentional change.
The new memory info display is consistent to CPU info: display the system wide used/total.

BTW. Used/Total in the old version were actually `CurrentlyUsed/MaxUsed` of Erlang virtual machine.
