### ISSUE TITLE
[error]: {scan_error,<<"illegal characters \"/v\" line_number 197 in_file /etc/emqx/emqx.conf">>}

### ISSUE THREAD

**Issue by hydaizd** [emqx/emqx#8417]
### What happened?

当我把emqx服务从4.4.4升级到5.0.2时，emqx服务启动不了了，报如下错误：
```shell
[error]: {scan_error,<<"illegal characters \"/v\" line_number 197 in_file /etc/emqx/emqx.conf">>}

ERROR: call_hocon_failed: -s emqx_conf_schema -c /etc/emqx/emqx.conf multi_get node.data_dir node.name node.cookie node.db_backend cluster.proto_dist
```
查看了下emqx.conf文件，197行对应的配置为：
```shell
node.data_dir = /var/lib/emqx
```
配置文件升级后我没有做任何更改，但是emqx服务启动不了了，这是啥问题呢？

### What did you expect to happen?

升级到5.0.2后，emqx服务能正常启动。

### EMQX version

<details>

```console
$ ./bin/emqx_ctl broker
# paste output here
```

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Log files

<details>

</details>

**Comment by lafirest** [comment]
@hydaizd 
I'm so sorry, but 5.0 and 4.x configurations are not compatible, currently, you cannot upgrade directly from 4.x to 5.0

**Comment by lafirest** [comment]
https://www.emqx.io/docs/en/v5.0/deploy/upgrade-from-v4.html
@hydaizd 
`EMQX 5.0 is not backward compatible with 4.x in management APIs and clustering APIs, however most of the functionalities are not significantly changed.`
