### ISSUE TITLE
Better commit messages

### ISSUE THREAD

**Issue by klausenbusk** [emqx/emqx#843]
I think the commit message (quality) could be improved, the current level looks a bit unprofessionally :/

Most of the commits message doesn't even seems to be sentences but keywords.

http://chris.beams.io/posts/git-commit/ is worth reading.. :) + https://github.com/erlang/otp/wiki/Writing-good-commit-messages
Ex:
https://github.com/emqtt/emq-auth-mysql/commit/bdaee2705f444a06df263b378ab741a09af51b8a
https://github.com/emqtt/emq-auth-mysql/commit/85509ed20e95b66aae59a8a95c599ecc7592de81
https://github.com/emqtt/emq-auth-mysql/commit/be6e6f6d0203e75edaeea134e07339d26e5f6dad
https://github.com/emqtt/emqttd/commit/318a52a5af91f40b170e3773f1cbcd67c21ad854
https://github.com/emqtt/emqttd/commit/d7c5706b179584af61d21eaa5945a2109dd535b0

**Comment by emqplus** [comment]
@klausenbusk Happy New Year:) Thanks for you advice. We will improve the project management of EMQ.
