### ISSUE TITLE
Shared subscription round_robin behaviour remarks

### ISSUE THREAD

**Issue by fridayy** [emqx/emqx#8454]
#### Environment

- OS: linux 5.18.7-arch1-1
- Erlang/OTP:  24.3.4
- EMQ: v4.4.4 and master

#### Description

Hello guys, first and foremost thank you for your great work on emqx! 

I've got a few remarks regarding the behaviour and implementation of the shared subscription round_robin strategy. I don't think this is necessarily a bug but something that needs to be discussed or maybe I've got something wrong alltogether here - I hope that's alright.

### Current state

The current implementation of the round_robin strategy stores an randomly initialized counter in the process dictionary of the connection process:
```
do_pick_subscriber(Group, Topic, round_robin, _ClientId, _SourceTopic, Count) ->
    Rem =
        case erlang:get({shared_sub_round_robin, Group, Topic}) of
            %% is undefined in case of a new connection
            %% Count = number of subscribers for group/topic combination
            undefined -> rand:uniform(Count) - 1;
            N -> (N + 1) rem Count
        end,
    _ = erlang:put({shared_sub_round_robin, Group, Topic}, Rem),
    Rem + 1.
```
This counter is then used to select a subscriber that should receive the next message. For a single publisher that keeps the connection alive and N subscribers this mechanism works fine.

![1](https://user-images.githubusercontent.com/4015125/177997694-63e3b061-ef21-43b8-8c51-8f999d7ff589.png)

However if there 2 publishers and 2 subscribers it might happen that both counters are initialized at 0. This has the consequence that the first subscriber will receive the first two messages and the second subscriber will receive the next 2 messages. If there are many more publishers and you are unlucky subscribers may get flooded with many messages in alternating fashion - which is not unlikely if the subscriber count is low.

![2](https://user-images.githubusercontent.com/4015125/177997680-ece30fdf-0f7e-4c2f-8855-32a7048da557.png)

This is especially troublesome if subscribers perform expensive tasks and you need the load to be evenly spread between the subscribers (our use case).

From this follows that if publishers work in fire and forget fashion (connect, publish, disconnect) the round_robin strategy behaves pretty much like the random strategy. Which is not ideal if you need predictable load balancing - which would be a neat feature to have.

### Proposed solution

A naive and quick solution would be to store a monotonically increasing counter for each group/topic combination (as long as there are subscribers) which would probably work fine for a single emqx instance. As I've not yet had the time to inform myself how exactly emqx clustering works. I can only make uneducated guesses and don't know if something like a distributed round robin implementation is required for consistency sake.

[Something like this, but you guys are the experts certainly not me.](https://github.com/fridayy/emqx/commit/d9da54f1cca14d00fc78723765c880d0c18bd281)

Anyhow if you decide that this is not really an issue and works as designed it would be cool if the behaviour could be documented as it could be surprising to some people. For us it certainly was.

I hope everything was understandable and I am happy to hear your thoughts and feedback on this!

With best regards and have a nice weekend,
Benjamin

**Comment by zmstone** [comment]
Hi @fridayy 

Reasons behind the current design:
1. Avoid many clients bumping one counter concurrently. Arguably we already have a lot of counters bumped concurrently by millions of concurrent clients, so this argument is not very strong.
2. When clustered, it is an absolute no to synchronise counters across the nodes, so the round-robin will be pseudo anyway.

I do see your point though, after all, not all of our open source edition users need clustering.
Since you seem to already made the changes, maybe you can help to send it in as a PR?
We'd be happy to accept it after a bit of review from my colleagues.

Please add a new strategy config, maybe name it `roundrobin_per_node`

**Comment by zmstone** [comment]
And thank you for the tip on the documentation, we'll update it.

**Comment by fridayy** [comment]
Hi @zmstone!

Thank you for your quick reply, very much appreciated. 

> Avoid many clients bumping one counter concurrently. Arguably we already have a lot of counters bumped concurrently by millions of concurrent clients, so this argument is not very strong.

I see your point and I really think a non-counter approach would be far better but certainly more effort. If you have clues or ideas I am eager to learn.

> When clustered, it is an absolute no to synchronise counters across the nodes, so the round-robin will be pseudo anyway.

Okay thanks for clearing that up. That confirms my assumption how it would behave in a cluster configuration. Yeah I totally agree with you, distributed round robin using a counter would be awful.

> Since you seem to already made the changes, maybe you can help to send it in as a PR?
We'd be happy to accept it after a bit of review from my colleagues.

Sure would be my pleasure and an honor to contribute. Looking forward to your feedback on the PR.

**Comment by lafirest** [comment]
> 

@fridayy 
I think we can just hash the publisher pid as the start offset, although this isn't the best solution

**Comment by lafirest** [comment]
> hi @lafirest I am not sure if I get it (sorry!): Wouldn't you still get duplicate start offsets (as long as the modulo approach is used)? And messages would be still be round-robin'd differently for each connection.
> 
> I would suggest not couple the round robin algorithm in any way to the publisher/connection. Publishers/connections should not influence the mechanism. Regardless of who published the message, the message should be evenly and predictably round-robin'd among the subscribers in a specific group.

Yes, I think you are right, but the correct way would generate new shared data for each group, I'm not sure if it's worth it

**Comment by fridayy** [comment]
> > hi @lafirest I am not sure if I get it (sorry!): Wouldn't you still get duplicate start offsets (as long as the modulo approach is used)? And messages would be still be round-robin'd differently for each connection.
> > I would suggest not couple the round robin algorithm in any way to the publisher/connection. Publishers/connections should not influence the mechanism. Regardless of who published the message, the message should be evenly and predictably round-robin'd among the subscribers in a specific group.
> 
> Yes, I think you are right, but the correct way would generate new shared data for each group, I'm not sure if it's worth it

Indeed and I share your struggle. It really depends on the use-case. Our scenario is many fire and forget publishers that publish messages to many shared topics with a low subscriber count. The subscribers perform computational heavy work so it would be nice if the load gets evenly balanced. Maybe one might consider this a little bit exotic. 
Before emqx we were using mosquitto which performed round robin as expected but for various reasons we surely want to keep using emqx. 
Anyway in the end its up to you guys to decide this and I am very thankful for your insights and taking the time to discuss this matter. :+1:
