### ISSUE TITLE
optional rocksdb

### ISSUE THREAD

**Issue by zmstone** [emqx/emqx#8457]
### What would you like to be added or enhanced?

we need to make rocksdb dependency optional.
similar to BUILD_WITHOUT_QUICK

### Why is this needed?

* A developer who do not wish to use rocksdb should not be forced to build its source code (e.g. RaspberryPI users)
* When rocksdb dynamic lib is not present, EMQX should be able to boot.
* When rocksdb is not present, the default rocksdb backend mnesia tables (if any) should either fallback to a disk_copy backend, or do not create the table at all.
* Features depending on rocksdb should be optional.

**Comment by ieQu1** [comment]
Part1: https://github.com/emqx/mria/pull/96/files
