### ISSUE TITLE
v5 Windows build fails in Makefile

### ISSUE THREAD

**Issue by MikeDombo** [emqx/emqx#8467]
### What happened?

I'm trying to upgrade from v4.3 to v5 on Windows currently and the command `make -j` fails with the error `Makefile:1: *** target pattern contains no '%'.  Stop.`. Changing line 1 to `$(sh $(CURDIR)/scripts/git-hooks-init.sh)` bypasses that error, but then I get the error: `Makefile:81: *** multiple target patterns.  Stop.`

I'm using make installed by chocolatey, the version is 4.3.

### What did you expect to happen?

I expect that EMQX will be built as described by: https://github.com/emqx/emqx/blob/master/Windows.md.

### EMQX version

<details>

```console
$ ./bin/emqx_ctl broker
# paste output here
```

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Log files

<details>

</details>

**Comment by MikeDombo** [comment]
Seems that it works when `bash` is on the PATH properly. By default on Windows, `bash` is now a valid executable in C:\Windows\System32 and System32 is early in the PATH resolution.

**Comment by zmstone** [comment]
Hi @MikeDombo 
Thanks for reporting this.
I’m not sure how actionable this is for EMQX team.
Would you say it’s good enough if we put this `PATH` note in Windows.md?
Or other suggestions are welcome too.

**Comment by MikeDombo** [comment]
Yes, the instructions are accurate, specifically the "validate" step. I'd probably suggest saying that the cygwin bin in the PATH needs to come before Windows/system32 which is where the wsl binary is.

**Comment by MikeDombo** [comment]
Also I don't know why it built fine in the exact same environment with EMQX v4, but it doesn't really matter.

**Comment by zmstone** [comment]
> y it built fine in the exact same environment with EMQX v4, but it

Thank you for your clarification.
I'll update the doc.

**Comment by zmstone** [comment]
https://github.com/emqx/emqx/pull/8504
