### ISSUE TITLE
mailbox too many case sometime message unreceived

### ISSUE THREAD

**Issue by seqwait** [emqx/emqx#8474]
### What happened?

today I find sometimes I cannot receive messages and  some messages are too slow to receive, I don't know what happens
I just find the mailbox greater than zero, how to fix this problem?
 

### What did you expect to happen?

message receive and faster

### EMQX version

<details>

```console
sysdescr  : EMQ X Broker
version   : 4.0.0
uptime    : 8 days, 3 hours, 6 minutes, 18 seconds
datetime  : 2022-07-13 12:28:52
```

</details>

### OS version

<details>

```console
NAME="CentOS Linux"
VERSION="8"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="8"
PLATFORM_ID="platform:el8"
PRETTY_NAME="CentOS Linux 8"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:8"
HOME_URL="https://centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"
CENTOS_MANTISBT_PROJECT="CentOS-8"
CENTOS_MANTISBT_PROJECT_VERSION="8"
```

</details>

### Log files

<details>

</details>

**Comment by qzhuyan** [comment]
4.0.0 is too old. Could you try with newer version like 4.3.x?
