### ISSUE TITLE
EMQX throw Internal Server Error

### ISSUE THREAD

**Issue by HeavenTonight** [emqx/emqx#8487]
### What happened?

EMQX throw Internal Server Error in create resource,request url no have scheme
![emq-error](https://user-images.githubusercontent.com/44971607/178955189-17886f02-d5c3-403a-977b-80e30ede7f0e.png)

EMQX version
![emq-version](https://user-images.githubusercontent.com/44971607/178954609-8dc0d303-a242-4f6c-8a08-f9190396b9ea.png)

### What did you expect to happen?

At least do not throw Internal Server Error (code 500),not have any message for this operate。

### EMQX version

<details>

```console
$ ./bin/emqx_ctl broker
# paste output here
```
V4.4.4 and V4.3.8
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Log files

<details>

</details>

**Comment by qzhuyan** [comment]
@HeavenTonight Could you give more info on how to reproduce the issue? An example of a RestAPI call would be appreciated.
