### ISSUE TITLE
Add support for custom clientid for MQTT bridges

### ISSUE THREAD

**Issue by aronsky** [emqx/emqx#8498]
### What would you like to be added or enhanced?

In EMQX v4, I could set the clientid to be used for bridge connections (via the `bridge.mqtt.$NAME.clientid` configuration field). I can't set this field in EMQX 5.

### Why is this needed?

I am attempting to connect to a server that only supports connections from clients with specifically formatted client IDs.

**Comment by zmstone** [comment]
hi @aronsky 
In v4, the configured client id is just a prefix, a random suffix is assigned to avoid client id clashing when EMQX is clustered.
(unless cluster_singleton is used).

For v5, it's a relatively small change to support client ID prefix configuration, but cluster_singleton is not going to be supported.

We'd like to know if adding a prefix configuration will suite your requirements.

**Comment by brnaba-aws** [comment]
hi @zmstone,
in v4 the random suffix can be disabled by setting `Append GUID` to false, no?
I'm working with Greengrass and in order to establish a secure connection between EMQX and Greengrass MQTT broker, the client id needs to be static.

**Comment by aronsky** [comment]
Hi @zmstone,
A prefix should work, though as @brnaba-aws mentioned, if disabling the suffix is possible, it'll be even better.

**Comment by zmstone** [comment]
we'll maybe introduce two configs:
`bridges.mqtt.$name.clientid = string()`
and
`bridges.mqtt.$name.clientid_suffix = none | random | node_name`

**Comment by aronsky** [comment]
Sounds perfect to me.

**Comment by philippdzm** [comment]
Exactly the same situation here. Is there any other way to overwrite the client id through configuration?

**Comment by tom-tschiller** [comment]
We've run into the same problem while updating to version 5.0. The possibility to set a prefix for the client ID would be very helpful for us. Without it we cannot update.

By the way, I was surprised, that the example for creating a connector using the API proposes to set a value for "clientid": https://www.emqx.io/docs/en/v5.0/admin/api.html#/Connectors/post_connectors. It's accepted, but it seems to be ignored.

**Comment by ShinigamiBoss** [comment]
@aronsky it's almost passed a year and I am encounting the same problem with the Client Id (I need the possibility to set a custom one).
Is there any news regarding this feature?
Thanks for any info/news

**Comment by aronsky** [comment]
@ShinigamiBoss I'm not the maintainer of this project or the issue, just the reporter. I've long since set up my MQTT differently, and the requested feature is no longer required for me.

**Comment by philippdzm** [comment]
For me this is still blocking me from upgrading to version 5. 
I cannot change the requirements on the other side.
Would still be happy about @zmstone 's proposal above (https://github.com/emqx/emqx/issues/8498#issuecomment-1189936686)

**Comment by id** [comment]
@wivwiv FYI

**Comment by flyfire-cn** [comment]
> bridges.mqtt.$name.clientid

bridges.mqtt.$name.clientid = string()
bridges.mqtt.$name.clientid_suffix = none | random | node_name

我现在使用的emqx5.3.2,这两个参数现在是不是可使用了呢？我连接阿里云的mqtt,需要固定clientId.
I am now using emqx5.3.2, are these two parameters available now? I connect the mqtt of Alibaba Cloud and need a fixed clientId.

**Comment by zmstone** [comment]
Hi @flyfire-cn 

We will add a support to configure a pool of Client IDs which are pre-allocated for EMQX's bridge connections to use.
This will be implemented maybe in version 5.7.x

**Comment by jonathandavidhopper** [comment]
For bridging to AWS IoT we need the Client ID to match the associated AWS ThingID, for each originating Device... Not sure a pool of Client IDs will support this...

**Comment by zmstone** [comment]
Hi @jonathandavidhopper 
If the pool only contains one ThingID it should still work, but the drawbacks are:
1. there would be only one connection towards the remote broker
2. when clustered, all matching messages will have to be forwarded to the selected node (which acquired the ThingID).

**Comment by zmstone** [comment]
This feature is planed in 5.8.

**Comment by alext-extracellular** [comment]
Just wanted to add that I think this feature is really important, because it seems right now it is not possible to bridge EMQX to Azure IOT Hub due to this problem. Azure is expecting a fixed ClientID that matches their internal DeviceID. EMQX will generate random suffixes which cause it to always fail client authentication. Unless someone knows a workaround, this is making it impossible for me to use EMQX right now, and I would really love to use it.

**Comment by id** [comment]
5.8.1

**Comment by zmstone** [comment]
Sorry, this has missed the release 5.8.1.
It turned out to be a quite an intrusive change when having to deal with clustering.
We will have to re-iterate on the design.

**Comment by thalesmg** [comment]
Added in #14404 , due to be released in 5.8.5.
