### ISSUE TITLE
How can I dynamically cancel a client topic subscription in real time? 

### ISSUE THREAD

**Issue by renwanly** [emqx/emqx#852]
Environment

    OS: CentOS 7
    Erlang/OTP:
    EMQ: 2.0.5

Description

English:
When a client subscribes to a topic, the ACL allows it to subscribe. The client keeps the session alive. For some reason, the client's subscription authorization needs to be retracted. How can I tell EMQ to cancel the subscription for this client?

Chinese:
客户端订阅一个主题，ACL允许其订阅。该客户端保持会话。因某种原因，需要回收此客户端对此主题的订阅权。我如何告知EMQ取消此客户端对此主题的订阅呢？

**Comment by turtleDeng** [comment]
@renwanly emqx3.0 support REST API clear ACL cache, http://emqtt.io/docs/v2/rest.html#clear-the-acl-of-a-specified-client-in-the-cluster
