### ISSUE TITLE
websocket can't connect successfully

### ISSUE THREAD

**Issue by shanjunmei** [emqx/emqx#8521]
### What happened?

current latest version,all default configuration,tcp port ：1883 can work fine ,but port websocket can't connect successfully,telnet test port is open (both mqtt.js/mqtt box can't access normal)

### What did you expect to happen?

-

### How can we reproduce it (as minimally and precisely as possible)?

-

### EMQX version

<details>

```console
$ ./bin/emqx_ctl broker
# paste output here
```

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Log files

<details>

</details>

**Comment by ieQu1** [comment]
Hi,
Does EMQX print any logs when you try to connect? What error does the client throw when the connectino fails?

**Comment by shanjunmei** [comment]
> 

nothing found ,even use logtrace

**Comment by shanjunmei** [comment]
The test found that if mqttbox does not select the broker to be compatible with v3, it will not be able to connect. After selecting it, it can, so emqx is not compatible with v5 client?

**Comment by zmstone** [comment]
@shanjunmei 
thank you for reporting it.
we'll try to reproduce it.
Would be nice if you can help to turn on debug level logging and share the logs with us.
