### ISSUE TITLE
Configuring emqx_rule_engine plugin events events cannot take effect

### ISSUE THREAD

**Issue by mijjjj** [emqx/emqx#8533]
### What happened?

My meqx version is 4.3.5, started via docker. Configured in environment variables
EMQX_RULE-ENGINE__EVENTS__CLIENT_CONNECTED: on, qos1
EMQX_RULE-ENGINE__EVENTS__CLIENT_DISCONNECTED: on, qos1
Or configure it in the configuration file /opt/emqx/etc/plugins/emqx_rule_engine.conf

Subscribe via Subscription Super Admin
$events/client_connected
Didn't receive the notification of the client going offline

### What did you expect to happen?

Receive notification of client going offline

### EMQX version

4.4

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Log files

<details>

</details>

**Comment by zmstone** [comment]
Hi. 
`EMQX_RULE-ENGINE__EVENTS__CLIENT_CONNECTED` is not a valid environment variable name (mind the `-`).
Please try `EMQX_RULE_ENGINE__EVENTS__CLIENT_CONNECTED`.

**Comment by mijjjj** [comment]
Using the EMQX_RULE_ENGINE__EVENTS__CLIENT_CONNECTED environment variable injection still fails to take effect, and subscribing to $events/client_connected still fails to receive the client online message

**Comment by mijjjj** [comment]
![image](https://user-images.githubusercontent.com/37797122/180378606-343a650e-592f-41b1-889b-529a7ad5020a.png)
This is my docker configuration diagram

**Comment by zmstone** [comment]
Hi @mijjjj `$event` topics are 'virutal' topics, they do not exist in the routing table, so no client can subscribe to it.

**Comment by zmstone** [comment]
Hi @mijjjj 
I was not able to reproduce it.
Tried to run with this command:
`docker run --network host --rm -it -e EMQX_RULE_ENGINE__EVENTS__CLIENT_CONNECTED='on, qos1' emqx/emqx:4.4.8 bash`
and created a debug rule like this:
`SELECT * FROM "$events/client_connected"` with a `inspect` action (for debug)

Then connect a client, I was able to see printouts in the console.
