### ISSUE TITLE
on_message_publish hooks allows event to happen when returning false

### ISSUE THREAD

**Issue by pmitchell-vmware** [emqx/emqx#8535]
Hi, I'm having issues with the lua-hook "on_message_publish".  I'm trying to prevent certain messages from being published, but using `return false` doesn't seem to affect anything. I can change the payload to something different, but it does not prevent the message from being published, as intended. 

I have tried using the source versions 4.4.5 and 4.3.16 of EMQX.

Here is some sample code.

```
function register_hook()
    return  "on_message_publish"
end


function on_message_publish(clientid, username, topic, payload, qos, retain)
    local loc_username = username
    local loc_topic = topic

    if loc_username == "mitchell" then
        return false
    else
        return topic, payload, qos, retain
    end
end
```

**Comment by zmstone** [comment]
Hi @pmitchell-vmware 
Thank you for reporting this issue.
The repo emqx/emqx-lua-hook is deprecated as, for 4.3 and 4.4 the code has been moved to main-v4.3 main-v4.4 branch in this (emqx/emqx) repo.
So I made a GitHub issue transfer.

we will look into this.

**Comment by pmitchell-vmware** [comment]
What is the alternative to emqx-lua-hook since it's deprecated?

**Comment by savonarola** [comment]
@pmitchell-vmware Hello!
It's the repo that is deprecated, not the functionality. The Lua functionality is now the part of the main EMQX repo.

We have implemented the fix in https://github.com/emqx/emqx/pull/8540, it is going to be merged.

**Comment by ieQu1** [comment]
Hello,
I see that @savonarola 's PR has been merged, so closing the issue.
