### ISSUE TITLE
EMQX Auth/ACL Auth timeouts

### ISSUE THREAD

**Issue by YashJainSC** [emqx/emqx#8566]
### What happened?

We are noticing intermittent spikes in timeout errors

logs:

`ClientIp@ip:ports [Auth http] Request auth path: /service/v1/emqx/auth, error: timeout`

Also noticing this logs whenever timeouts error occure

`ehttpc: Received 'gun_error' message from unknown stream ref`

I am not sure whether this is due to connection timeout or request timeout, how to figure that out ?

Anything we can do here, currently we are using default settings, will increasing pool size help ? currently for auth + acl auth APIs we have about ~4000 requests per second

### What did you expect to happen?

We expected no timeouts as auth service doesn't have any issue

### How can we reproduce it (as minimally and precisely as possible)?

Maybe trying a load test with auth enabled at a higher ops, as we were not facing this when load was not high enough, but as soon as we started scaling it happened

### EMQX version

4.3.11

### OS version

OS: Alpine Linux v3.12

**Comment by qzhuyan** [comment]
@terry-xiaoyu Is this the one you are fixing?

**Comment by terry-xiaoyu** [comment]
It is request timeout, that is, emqx sends an HTTP request but response is not received in a specified time period.

Increasing the pool size will help I think, but this requires your HTTP server support accepting large amount of concurrent connections.

**Comment by zmstone** [comment]
> ehttpc: Received 'gun_error' message from unknown stream ref

This error has been fixed in later version EMQX.
However I am not sure if this is related to the timeouts.
