### ISSUE TITLE
Shared subscriptions cannot subscribe to topics starting with "/"

### ISSUE THREAD

**Issue by mijjjj** [emqx/emqx#8577]
### What happened?

In version 5.0.3, I subscribed to "$share/abc/a/b/c" using the shared subscription, using the topic "/a/b/c" to publish cannot be subscribed to, but using "a/b/c" can be subscribed to Subscribe to, it can be used normally with version 4.3. How do I subscribe to /a/b/c using a shared subscription

### What did you expect to happen?

Subscribe to "$share/abc/a/b/c" to subscribe to topics published by "/a/b/c"

### EMQX version

5.0

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Log files

<details>

</details>

**Comment by ieQu1** [comment]
Hello,

`/a/b/c` and `a/b/c` are different topics per MQTT standard, so EMQX 5.0 behavior is correct.
To create a shared subscription to `/a/b/c` topic your clients should subscribe to `$share/group//a/b/c` instead.
I hope this helps.

**Comment by zmstone** [comment]
Hi @westforkfab  
I think you should remove the leading `/` in this topic, `/notifications/devices/#`
or should add a leading `/` to the shared sub topic: `$share/devg//notifications/devices/#`

**Comment by westforkfab** [comment]
Hi @zmstone 

Thank you for your reply.

I did the following in the ACL section

```
$share/devg//notifications/devices/#
```

The clients subscribe using the following syntax:
```
-t "$share/devg//notifications/devices/#"
```

The publisher:
```
-t /notifications/devices/123123
```

but still not working. Wondering if it's a limitation of the free version

**Comment by zmstone** [comment]
I'm quite sure there is no such limitation of the free version.

could you share the output of below commands:
```
emqx eval 'emqx_router:match_routes(<<"/notifications/devices/123123">>)'
```

**Comment by westforkfab** [comment]
### Subscribers
```
mosquitto_sub <skipping host, credentials> -i client1 -t "$share/devg/notifications/devices/#"

mosquitto_sub <skipping host, credentials> -i client2 -t "$share/devg/notifications/devices/#"
```

### Publisher
```
mosquitto_pub <skipping host, credentials> -i publisher -t /notifications/devices/123123 -m "{'status': 'all good'}" -k 120
```

No messages were received by the subscribers.

### ACL
```
{allow, {username, "SUBCLIENT"}, subscribe, ["$share/devg/notifications/devices/#"]}.

{allow, {username, "PUBLISHER"}, publish, ["/notifications/devices/#"]}.

```






LOGS
```
2024-03-08T17:53:00.899291+01:00 [info] msg: authorization_permission_allowed, mfa: emqx_access_control:log_result/5(186), peername: x.y.z.w:48412, clientid: client1, topic: /devg/notifications/devices/#, username: SUBCLIENT, action: SUBSCRIBE(Q0), source: 'authorization.no_match' config
2024-03-08T17:53:04.289471+01:00 [info] msg: authorization_permission_allowed, mfa: emqx_access_control:log_result/5(186), peername: x.y.z.w:48420, clientid: client2, topic: /devg/notifications/devices/#, username: SUBCLIENT, action: SUBSCRIBE(Q0), source: 'authorization.no_match' config
2024-03-08T17:55:14.166988+01:00 [info] msg: authorization_permission_allowed, mfa: emqx_access_control:log_result/5(186), peername: x.y.z.w:53658, clientid: publisher, topic: /notifications/devices/123123, username: PUBLISHER, action: PUBLISH(Q0,R0), source: file
```

### OUTPUT of emqx eval
```
 emqx eval 'emqx_router:match_routes(<<"/notifications/cpe/123123">>)'
escript: exception error: no match of right hand side value
                 {error,{1,erl_parse,["syntax error before: ","'/'"]}}
  in function  nodetool__escript__1709__916343__506076__3:parse_eval_args/1 (/usr/lib/emqx/bin/nodetool, line 223)
  in call from nodetool__escript__1709__916343__506076__3:do/1 (/usr/lib/emqx/bin/nodetool, line 175)
  in call from escript:run/2 (escript.erl, line 750)
  in call from escript:start/1 (escript.erl, line 277)
  in call from init:start_em/1
  in call from init:do_boot/3
```

**Comment by zmstone** [comment]
ah, you have to quote the topic in single quotes in shell, otherwise double quotes will be evaluated with string interpolation:

try this:
```
mosquitto_sub <skipping host, credentials> -i client2 -t '$share/devg/notifications/devices/#'
```

**Comment by zmstone** [comment]
> emqx eval 'emqx_router:match_routes(<<"/notifications/cpe/123123">>)'
escript: exception error: no match of right hand side value

As for this exception, but I don't know what happened.
1. You pasted `cpe` while I asked for `devices`
2. The syntax error is odd, maybe due to non-ascii code typed in the shell ?

But this doesn't matter any more, as the issue was caused by quoting in your shell.

**Comment by westforkfab** [comment]
Apologies, the "cpe" is my fault (incorrect copy and paste).

Now it's "working" meaning the one client receive the message all the time. It looks some kind of persistance but I can't find where I can disable it to have pure round robin.

**Comment by zmstone** [comment]
It’s for each publishing client to round robin the subscribers. 
if you run one shot commands, it will be a different connection each time.
If one connection consistently publishes, you should be able to observe differently
