### ISSUE TITLE
update docs for docker-compose cluster example using EMQX_CLUSTER__STATIC__SEEDS

### ISSUE THREAD

**Issue by slaesh** [emqx/emqx#8581]
### What happened?

https://www.emqx.io/docs/en/v5.0/deploy/install.html#running-emqx-in-docker

example docker-compose says to use 

```
- "EMQX_CLUSTER__DISCOVERY_STRATEGY=static"
- "EMQX_CLUSTER__STATIC__SEEDS=emqx@node1.emqx.io, emqx@node2.emqx.io"
```

but it actually should be:

```
- "EMQX_CLUSTER__DISCOVERY_STRATEGY=static"
- "EMQX_CLUSTER__STATIC__SEEDS=[emqx@node1.emqx.io, emqx@node2.emqx.io]"
```

### What did you expect to happen?

please update the docs

### EMQX version

at least for v5, probably for the rest too?

**Comment by ieQu1** [comment]
Hello,
Thanks for the bugreport, fix is here: https://github.com/emqx/emqx-docs/pull/1319

**Comment by ieQu1** [comment]
The PR has been merged, so the changes will appear on the website soon.
