### ISSUE TITLE
EMQX 5.0.3 rate limit not working

### ISSUE THREAD

**Issue by IanChiu628** [emqx/emqx#8582]
### What happened?

Hi 

I'm using EMQX v5.0.3 docker version. I'm trying to use `rate limit` feature and following [this document](https://www.emqx.io/docs/en/v5.0/admin/cfg.html#limiter) to set it up
However, I found that it is not working as I thought. I set `bytes_in` and `message_in` with a very low value and EMQX still can process a lot of messages.
Could you please take a look and advise how to fix them? Thanks!

I set up EMQX rate limit like this:
```shell
docker run -d --name emqx \
-e EMQX_LIMITER__BYTES_IN__RATE=1/s \
-e EMQX_LIMITER__BYTES_IN__BURST=0 \
-e EMQX_LIMITER__MESSAGE_IN__RATE=1/s \
-e EMQX_LIMITER__MESSAGE_IN__BURST=0 \
-p 1883:1883 -p 8083:8083 -p 8084:8084 -p 8883:8883 -p 18083:18083 \
emqx/emqx:5.0.3
```

I tested with MQTT.js
```js
import * as mqtt from "mqtt";

const HOST = "127.0.0.1";
const BROKER_HOST_MQTT = `mqtt://${HOST}:1883`;

const client = mqtt.connect(
    BROKER_HOST_MQTT,
    {
        reconnectPeriod: 0, // disable auto reconnect
        protocolId: 'MQTT',
        protocolVersion: 5,
        username: "simulator",
        password: "123"
    }
);

client.on("connect", (connack) => {
    console.log("connected");
    client.subscribe("test/topic", (err) => {
        if (!err) {
            for (let i=0;i<1000;i++) {
                client.publish("test/topic", `Hello ${i}`);
            }
        }
    });
});

client.on("disconnect", (packet) => {
    console.log("disconneted");
    console.log(packet);
});

client.on("error", (error) => {
    console.log("error");
    console.log(error);
});

client.on("close", () => {
    console.log("close");
});

client.on("message", (topic, message, packet) => {
    console.log(topic);
    console.log(message.toString());
});
```

### What did you expect to happen?

I expect that only the first message can be processed by EMQX, the other message may be hung for a while like the document says.

### How can we reproduce it (as minimally and precisely as possible)?

Use the mqtt.js code I pasted.

### EMQX version

<details>

```console
$ ./bin/emqx_ctl broker
# paste output here
sysdescr  : EMQX
version   : 5.0.3
datetime  : 2022-07-27T08:48:46.616833098+00:00
uptime    : 3 minutes, 53 seconds
```
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
BuildNumber  Caption                      OSArchitecture  Version
19044        Microsoft Windows 10 Professional  64 bits         10.0.19044
```

</details>

### Log files

<details>

</details>

**Comment by lafirest** [comment]
@IanChiu628 Hi, The user interface and documents of the limiter are still at work. The limiter of the EMQX 5.0 is the C/S architecture. The configuration of the limiter only sets the service part. If you want to limit your connection, you also need to bind the service's name  in the listener configuration

**Comment by IanChiu628** [comment]
Hi @lafirest,
Thanks for looking into it. I do find the `limiter` field in `listeners.tcp.$name`. It seems like we should put the bucket_name of the limiter into this `limiter` field.
So, for `bytes_in` and `message_in` limiter, I should configure the `bucket` field for them and put the corresponding buctet_name in listeners. Is it correct?

However, I still not quite enough on understanding the limiter. In the document, it says the `bytes_in` is used to limit the inbound bytes rate for this EMQX node. When I set it with a low value, it should still limit the `bytes_in` even if I didn't bind to a listener because all listeners are in the same EMQX node. Could you please correct me if I was wrong?

BTW, may I suggest adding the value format for limiter fields in the document? Currently, I can't easy to know what value should be placed in the field. For example, the `rate` field says the format is `emqx_limter_schema:rate()`. But I have no idea to set it with "1000/s".

Thank you again for resolving my beginner questions.

**Comment by lafirest** [comment]
> Hi @lafirest, Thanks for looking into it. I do find the `limiter` field in `listeners.tcp.$name`. It seems like we should put the bucket_name of the limiter into this `limiter` field. So, for `bytes_in` and `message_in` limiter, I should configure the `bucket` field for them and put the corresponding buctet_name in listeners. Is it correct?
> 
> However, I still not quite enough on understanding the limiter. In the document, it says the `bytes_in` is used to limit the inbound bytes rate for this EMQX node. When I set it with a low value, it should still limit the `bytes_in` even if I didn't bind to a listener because all listeners are in the same EMQX node. Could you please correct me if I was wrong?
> 
> BTW, may I suggest adding the value format for limiter fields in the document? Currently, I can't easy to know what value should be placed in the field. For example, the `rate` field says the format is `emqx_limter_schema:rate()`. But I have no idea to set it with "1000/s".
> 
> Thank you again for resolving my beginner questions.

Now, the user interface of the limiter is not easy to understand, so we have redesigned it.
But in any case, the setting on the listener is required, because we assume that there should no limit on the system by default.
The documentation and examples will be added soon

**Comment by IanChiu628** [comment]
@lafirest Thanks! Looking forward to the new documentation and examples :star_struck: I'll try the limiter setting with the listeners.

**Comment by lafirest** [comment]
@IanChiu628 
The documentation of limiter has been updated, maybe you can try it on 5.0.8

**Comment by IanChiu628** [comment]
@lafirest 
Thanks for the update!

**Comment by Gypsying** [comment]
> 



> @IanChiu628 Hi, The user interface and documents of the limiter are still at work. The limiter of the EMQX 5.0 is the C/S architecture. The configuration of the limiter only sets the service part. If you want to limit your connection, you also need to bind the service's name in the listener configuration

How to `bind the service's name in the listener configuration` ?

**Comment by lafirest** [comment]
> > 
> 
> > @IanChiu628 Hi, The user interface and documents of the limiter are still at work. The limiter of the EMQX 5.0 is the C/S architecture. The configuration of the limiter only sets the service part. If you want to limit your connection, you also need to bind the service's name in the listener configuration
> 
> How to `bind the service's name in the listener configuration` ?

@Gypsying 
What version are you using, the configuration of the limiter is not yet stable now, but I can show an example with your version and your want.
