### ISSUE TITLE
dashboard don't connect  exhook_server

### ISSUE THREAD

**Issue by Mr-NB** [emqx/emqx#8583]
### What happened?

![image](https://user-images.githubusercontent.com/35053330/181220941-e637c642-dfcb-467b-848c-f2fd14f01115.png)
![image](https://user-images.githubusercontent.com/35053330/181221212-77a6fb8b-7bfb-4090-9eb3-0eca3d10a3d3.png)

### What did you expect to happen?

can connect

### EMQX version

<details>

```console
v5.0.3
```

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Log files

<details>

</details>

**Comment by ieQu1** [comment]
Hello,

Could you please attach logs from the EMQX broker collected around time you configure the exhook; without logs we cannot do anything.
