### ISSUE TITLE
webhook: client connected/disconnected - payload is empty

### ISSUE THREAD

**Issue by HaJrad** [emqx/emqx#8585]
### What happened?

I would like to send the events of clients connected or disconnected to my backend. This how my configuration looks like
![Screen Shot 2022-07-27 at 15 38 24](https://user-images.githubusercontent.com/71495081/181263674-6a3eac54-a5b7-4d9c-b19c-5b22ac474f01.png)
![Screen Shot 2022-07-27 at 15 38 09](https://user-images.githubusercontent.com/71495081/181263683-16108993-7272-420a-a417-b6a3f4eed5e4.png)
![Screen Shot 2022-07-27 at 15 37 39](https://user-images.githubusercontent.com/71495081/181263685-8b50bd00-8ed2-4725-8ee3-22d764b6ab55.png)
 

### What did you expect to happen?

Not an empty body in the POST request

### How can we reproduce it (as minimally and precisely as possible)?

I created the webhook (data bridge) and the rule over the dashboard. The SQL query for the client connected and disconnected I used the template in the dashboard.

### Anything else we need to know?

In production we use 4.3.3 and it works as expected.

### EMQX version

<details>

sysdescr  : EMQX
version   : 5.0.3
datetime  : 2022-07-27T13:39:06.114809989+00:00
uptime    : 1 hours, 17 minutes, 22 seconds

</details>

### OS version

<details>
$ cat /etc/os-release
NAME="Ubuntu"
VERSION="20.04.4 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.4 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
$ uname -a
Linux ip-xxx-xxx-xxx-xx 5.15.0-1015-aws #19~20.04.1-Ubuntu SMP Wed Jun 22 19:07:51 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
</details>

### Log files

<details>
127.0.0.1 - - [27/Jul/2022 15:35:44] "POST / HTTP/1.1" 200 -
INFO:root:POST request,
Path: /
Headers:
Host: 3ebc-195-243-119-210.ngrok.io:443
Content-Length: 9
Content-Type: application/json
X-Forwarded-For: 18.185.20.81
X-Forwarded-Proto: https
Accept-Encoding: gzip

Body:
undefined

</details>

**Comment by ieQu1** [comment]
Hello,
This event doesn't contain "payload" field, this is why the body of the POST request is empty.
This is what the connect event looks like:
``` 
#{clean_start => false,
clientid => <<"foo">>,
conn_props => #{},
connected_at => 1658935050593,
event => 'client.connected',
expiry_interval => 7200,
is_bridge => false,
keepalive => 60,
metadata => #{rule_id => <<"rule_fg6o">>},
mountpoint => undefined,
node => 'emqx@127.0.0.1',
peername => <<"127.0.0.1:35724">>,
proto_name => <<"MQTT">>,proto_ver => 4,
receive_maximum => 32,
sockname => <<"127.0.0.1:1883">>,
timestamp => 1658935050593,
username => undefined}
```
You can either select one of these fields found in the above snippet or leave body empty to add all fields to the HTTP request as JSON.
I hope this helps.

**Comment by HaJrad** [comment]
Sorry that I didn't use the right word here! I can create a new ticket if you would like. But what I actually mean is that the body of the post request is received empty.
I'm expecting, according to the documentation 
https://www.emqx.io/docs/en/v5.0/data-integration/rule-sql-events-and-fields.html#mqtt-events
on client_disconnected:
`{
  "username": "u_emqx",
  "reason": "normal",
  "node": "emqx@127.0.0.1",
  "disconnected_at": 1645003578536,
  "clientid": "c_emqx"
}`
and on client_connected:
`{
  "username": "u_emqx",
  "keepalive": 60,
  "is_bridge": false,
  "clientid": "c_emqx"
}
`

**Comment by ieQu1** [comment]
Hi @HaJrad ,
Yes, I explained why this happens. As I said, if you leave the "Body" field on picture 3 empty (instead of `${payload}`), you will get the expected result.

**Comment by HaJrad** [comment]
@ieQu1 thanks a lot! that was helpful

**Comment by Kakomis** [comment]
HI @ieQu1, I've created a rule from emqx dashboard 4.3.22 as you can see: 
![Screenshot 2023-02-05 at 19-05-33 Dashboard](https://user-images.githubusercontent.com/44932514/216859261-469afe45-3134-4319-ac4e-e29cefb59295.png)
![Screenshot 2023-02-05 at 19-06-46 Dashboard](https://user-images.githubusercontent.com/44932514/216859322-b29e2675-98d8-4acd-a52a-d0dffe6ab604.png)

And that is the resource conn:1:
![Screenshot 2023-02-05 at 19-07-48 Dashboard](https://user-images.githubusercontent.com/44932514/216859396-8bad9508-80ff-48b9-b454-df3676dbc964.png)

When rule is triggered it make a request to my api endpoint, however, it sends an empty body, and I don't know why.

I hope you can help me with this.

**Comment by HaJrad** [comment]
@Kakomis the body shoud be empty

**Comment by Kakomis** [comment]
HI @HaJrad with empty body, the result is the same. 
![Screenshot 2023-02-06 at 12-58-54 Dashboard](https://user-images.githubusercontent.com/44932514/217061414-fe066b1b-62c2-4f24-9696-657d6347059b.png)

When action is Inspect, this is what I get: 

```
[inspect]
	Selected Data: #{<<"clientid">> =>
                             <<"web_63d1fd5f48864d84dc6b84a9_9a43289ba4">>,
                         <<"username">> => <<"b58e6b192a">>}
	Envs: #{'__bindings__' =>
                    #{'Id' => <<"inspect_1675710295179771293">>,
                      'Params' => #{}},
                clean_start => true,
                clientid => <<"web_63d1fd5f48864d84dc6b84a9_9a43289ba4">>,
                conn_props => #{},connected_at => 1675710314928,
                event => 'client.connected',expiry_interval => 0,
                is_bridge => false,keepalive => 60,
                metadata =>
                    #{action_name => inspect,resource_id => undefined,
                      rule_id => <<"rule:080098">>},
                mountpoint => undefined,node => 'demo-rv4p@127.0.0.1',
                peername => <<"172.21.0.1:37126">>,proto_name => <<"MQTT">>,
                proto_ver => 4,receive_maximum => 32,
                sockname => <<"172.21.0.3:8083">>,timestamp => 1675710314928,
                username => <<"b58e6b192a">>}
	Action Init Params: #{}

```

**Comment by HaJrad** [comment]
@Kakomis in the body I see the above logs, I could see that you're getting the 
 `clientid: web_63d1fd5f48864d84dc6b84a9_9a43289ba4`
 and `username: b58e6b192a`
  what are you expecting to get ?
