### ISSUE TITLE
Using EMQX_DASHBOARD__DEFAULT_PASSWORD env variable to set admin password?

### ISSUE THREAD

**Issue by billimek** [emqx/emqx#8627]
### What happened?

EMQX Dashboard seems to only accept the default `admin` / `public` username/password, despite setting `EMQX_DASHBOARD__DEFAULT_PASSWORD` env variable.

<img width="547" alt="image" src="https://user-images.githubusercontent.com/6393612/182251812-cf804dec-9f7a-435b-b465-2251b899bab9.png">

When attempting to use the password defined by `EMQX_DASHBOARD__DEFAULT_PASSWORD`, the dashboard page gives the error of `Some error occurred`

### What did you expect to happen?

Dashboard login of admin user to work with the `EMQX_DASHBOARD__DEFAULT_PASSWORD` env variable value.

### How can we reproduce it (as minimally and precisely as possible)?

Define `EMQX_DASHBOARD__DEFAULT_PASSWORD` to some value in the docker runtime

### EMQX version

<details>

```console
$ ./bin/emqx_ctl broker
sysdescr  : EMQX
version   : 5.0.3
datetime  : 2022-08-01T21:48:54.335787260+00:00
uptime    : 4 minutes, 6 seconds
```

</details>

... Helm chart 5.0.3

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
$ uname -a
Linux emqx-0 5.4.0-122-generic #138-Ubuntu SMP Wed Jun 22 15:00:31 UTC 2022 x86_64 GNU/Linux
```

</details>

### Log files

<details>

</details>

**Comment by dsilletti** [comment]
Good point, as workaround I added this section in the cluster-override.conf

dashboard {
  default_password = "mypassword"
  default_username = "admin"
  listeners {
    http {bind = 18083}
  }
}

**Comment by techmantel** [comment]
Just to make it clear for future readers, this means that the env vars should look like this:
```
EMQX_DASHBOARD__DEFAULT_USERNAME=admin
EMQX_DASHBOARD__DEFAULT_PASSWORD=passwd
```

**Comment by tkeksa** [comment]
I am unsuccessfully trying to use EMQX_DASHBOARD__DEFAULT_PASSWORD with EMQX 5.3.1 in Docker. Should it work?

**Comment by ozanerturk** [comment]
In emqx/emqx:4.3.22
`EMQX_ADMIN_PASSWORD=passwod `
works for me

**Comment by zmstone** [comment]
> I am unsuccessfully trying to use EMQX_DASHBOARD__DEFAULT_PASSWORD with EMQX 5.3.1 in Docker. Should it work?

It should work, however it only works on the initial setup, if the admin user is already initialized in the database (emqx booted for the first time), setting this env variable again will take no effect.

> In emqx/emqx:4.3.22
EMQX_ADMIN_PASSWORD=mypassword 
works for me

That's for 4.3, 5.x config has a different layout. Thanks for sharing though.

**Comment by coriolanweihrauch** [comment]
For those on 5.8+ who struggle with this:

**Peristance**
If you create a volume, this will only apply to the first boot
```yaml
    volumes:
      - wata_emqx_data:/opt/emqx/data
```
Make sure to delete the volume if you want to test these settings

You can set it in 2 ways:

**ENV**
```yaml
    environment:
        EMQX_DASHBOARD__DEFAULT_USERNAME: "admin"
        EMQX_DASHBOARD__DEFAULT_PASSWORD: "passwd"
```

**hocon file**
```yaml
    volumes:
      - ./emqx/cluster-override.conf:/opt/emqx/data/configs/cluster-override.conf
```

cluster-override.conf:
```hocon
dashboard {
    default_username = "admin"
    default_password = "passwd"
  }
```

See https://docs.emqx.com/en/emqx/latest/configuration/dashboard.html for file content

**Comment by zmstone** [comment]
Hi @coriolanweihrauch 
thank you for sharing, I have made and update to your comment though.
`cluster-overrride.conf` is deprecated, please use `etc/base.hocon` instead.
