### ISSUE TITLE
superuser not effect?

### ISSUE THREAD

**Issue by shanjunmei** [emqx/emqx#8632]
### What happened?

still check acl rule

### What did you expect to happen?

-

### EMQX version

<details>

```console
$ ./bin/emqx_ctl broker
# paste output here
```

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Log files

<details>

</details>

**Comment by chang196700** [comment]
update to 5.0.4
ref #8446

**Comment by zmstone** [comment]
@chang196700 thank you for the hint
