### ISSUE TITLE
EMQX 5.0.x Deleting default listeners is not persistent

### ISSUE THREAD

**Issue by dsilletti** [emqx/emqx#8657]
### What happened?

Deleting the default listeners is not persistent, changes saved in cluster-override.conf do not remove the deleted listeners when the container is restarted.

### What did you expect to happen?

the deleted default listeners should disappear also after the container restart

### How can we reproduce it (as minimally and precisely as possible)?

use a persistent cluster-override.conf file, delete a default listener and redeploy the container

### EMQX version

Official 5.0.4 container

<details>

```console
$ ./bin/emqx_ctl broker
sysdescr  : EMQX
version   : 5.0.4
datetime  : 2022-08-06T14:50:59.580922745+00:00
uptime    : 29 minutes, 1 seconds
```

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
$ uname -a
Linux 9f54f6667627 5.4.0-122-generic #138-Ubuntu SMP Wed Jun 22 15:00:31 UTC 2022 x86_64 GNU/Linux

```

</details>

### Log files

<details>

</details>

**Comment by zmstone** [comment]
Hi @dsilletti 
this is a known limitation.
one can disable the listener for now.
we'll keep this issue open though.
