### ISSUE TITLE
 MQTTX to support enhanced authentication

### ISSUE THREAD

**Issue by haoranyang2022** [emqx/emqx#8661]
### What would you like to be added or enhanced?

 MQTTX to support enhanced authentication

### Why is this needed?

Want to complete a enhanced authentication connection with EMQX

**Comment by tigercl** [comment]
@haoranyang2022 Hi, thanks a lot for your feedback, but EMQX and MQTTX are maintained by two different teams, so you need to submit your suggestions under the MQTTX project: https://github.com/emqx/MQTTX
