### ISSUE TITLE
some node too many memory usage

### ISSUE THREAD

**Issue by seqwait** [emqx/emqx#8676]
### What happened?

I have 4 nodes that use docker swarm 
the emqx version: emqx/emqx:v4.0.0
one of the nodes (emqx@node3.emqx.io) uses too much memory although the node3 is the lowest load balance  and
why ? 

|node |load balance |memory useage | connections|
| :-----| ----: | ----:|----:|
| emqx1| weight: 2| 766.21M / 1.44G |  680 / 1339|
| emqx2| weight: 2| 725.79M / 1.81G| 670 / 2009|
| emqx3| weight: 1| 6.89G / 8.33G |  327 / 2639|
| emqx4| weight: 4| 1012.74M / 1.67G |  1363 / 2235|

### What did you expect to happen?

node3 used memory go down

### EMQX version

 docker: emqx/emqx:v4.0.0

### OS version (node3)

<details>

```console

NAME="Alibaba Cloud Linux"
VERSION="3 (Soaring Falcon)"
ID="alinux"
ID_LIKE="rhel fedora centos anolis"
VERSION_ID="3"
PLATFORM_ID="platform:al8"
PRETTY_NAME="Alibaba Cloud Linux 3 (Soaring Falcon)"
ANSI_COLOR="0;31"
HOME_URL="https://www.aliyun.com/"
</details>

**Comment by terry-xiaoyu** [comment]
What is the output of `./bin/emqx_ctl vm` ?

We also have an profile tool named observer_cli, you can start it by entering the remote console using `./bin/emqx remote_console`, and then type `observer_cli:start().`.

**Comment by zmstone** [comment]
> 

It's 4.0.0, there is no observer_cli there.
This version is old, we have stopped supporting it, please consider upgrading to 4.4 or 5.0 @seqwait
