### ISSUE TITLE
EMQX 4.4.1 Community Edition - Memory Leak

### ISSUE THREAD

**Issue by PaulGobin** [emqx/emqx#8695]
#### Environment

- OS:  Windows Server 2019 - 3 nodes in  Azure, 64G  RAM
- Erlang/OTP: 
- EMQ: Version 4.4.1 Community Edition

#### Description

*A description of the issue*

On Fri, 12 Aug at 12:41 AM , emqx <support@emqxassist.freshdesk.com> wrote: 
Hi paul.gobin,

_Thank you for using EMQX Cloud!
From the logs, it seems that EMQX may have a memory leak. For better technical help, we recommend you to report your issue at https://github.com/emqx/emqx/issues._

Best regards,
The EMQX Cloud Team

**Comment by terry-xiaoyu** [comment]
Maybe a duplicate to https://github.com/emqx/emqx/issues/8729

**Comment by zmstone** [comment]
closing it. let's follow up in #8729
