### ISSUE TITLE
If I want to set a fixed account password automatically when starting, is there any way?

### ISSUE THREAD

**Issue by bbhxwl** [emqx/emqx#8714]
If I want to set a fixed account password automatically when starting, is there any way?

**Comment by thalesmg** [comment]
You can change the default password for the dashboard user before starting the node for the first time:

https://www.emqx.io/docs/en/v5.0/admin/api.html#change-default-user-password

**Comment by bbhxwl** [comment]
> You can change the default password for the dashboard user before starting the node for the first time:
> 
> https://www.emqx.io/docs/en/v5.0/admin/api.html#change-default-user-password

Is there a way to default one when starting? I mean, the default mqtt ClientID and account password

**Comment by zmstone** [comment]
Hi.
There is so far no way to bootstrap builtin database with username passwords.
Marking this as a feature request.

**Comment by AaronAutomation** [comment]
> Hi. There is so far no way to bootstrap builtin database with username passwords. Marking this as a feature request.

Can you not mount acl.conf?

**Comment by zmstone** [comment]
> > Hi. There is so far no way to bootstrap builtin database with username passwords. Marking this as a feature request.
> 
> Can you not mount acl.conf?

acl.conf is great for ACL (authorization), but not for authentication.

**Comment by zmstone** [comment]
similar issue/discussion
* https://github.com/emqx/emqx/issues/11068
* https://github.com/emqx/emqx/discussions/12496

We do not have plan to support MQTT credentials bootstrapping from environment variables (or a file).
In v5.5, there is a [REST API to import](https://docs.emqx.com/en/enterprise/v5.5/admin/api-docs.html#tag/Authentication/paths/~1authentication~1%7Bid%7D~1import_users/post) users.

And if you call the [API to list](https://docs.emqx.com/en/enterprise/v5.5/admin/api-docs.html#tag/Authentication/paths/~1authentication~1%7Bid%7D~1users/get
) it first, you can write a bootstrap script to only import once (when list returns empty)

**Comment by zmstone** [comment]
After some discussion in the team, we might be able to provide a bootstrap from file option.
Internal ref: [ER-248](https://emqx.atlassian.net/browse/ER-248)

**Comment by id** [comment]
One more related issue: https://github.com/emqx/emqx/issues/9148

**Comment by mvanhil** [comment]
Any idea when this would be implemented? :-)

**Comment by id** [comment]
@mvanhil will be released in 5.7.2

**Comment by jmaxmarno** [comment]
@id tracking this as well - any guess as to when this 5.7.2 release might be coming?

**Comment by id** [comment]
@jmaxmarno the plan is to release it on this week.

**Comment by id** [comment]
Released in 5.7.2
https://github.com/emqx/emqx/releases/tag/v5.7.2
https://github.com/emqx/emqx/pull/13336
