### ISSUE TITLE
Cluster Sessions - Publish

### ISSUE THREAD

**Issue by satrox28** [emqx/emqx#874]
#### Environment

- OS: Ubuntu 16.04
- Erlang/OTP: 1.92
- EMQ: 2.0.6

#### Description

We have a 2node cluster(each connected to 1000 clients which are subscribing to an individual topic)behind an AWS load balancer.

 If 1node fails,during that period if we publish messages to all the clients which where connected previously to both nodes. 

We are trying to reconnect the disconnected clients from our code without re-subscribing,  in this case will all the messages be delivered?.

Do the sessions will be stored across both nodes?. Are the sessions will be stored in a RAM or Disk.

**Comment by satrox28** [comment]
Do you have any update on this, will this feature be added on next release?.

**Comment by satrox28** [comment]
Any update on this?

**Comment by Gilbert-Wong** [comment]
Hi, @satrox28 , so sorry for so late reply. The session could not be stored across nodes in emqx cluster mode. Maybe it would be resolved in emqx 4.0 release.
