### ISSUE TITLE
Integration with couchbase

### ISSUE THREAD

**Issue by wuqunfei** [emqx/emqx#879]
#### Couchbase is very popular NOSQL system

*Can we consider to integrate with couchbase as another auth plugin, I also can join your developing, but I am not an erlang developer*

https://github.com/chitika/cberl is an erlang client base on C++ library https://developer.couchbase.com/documentation/server/4.1/sdks/c-2.4/c-intro.html

So could you give some guide to help me to do it, in the end, I will definitely open source to you.

**Comment by emqplus** [comment]
@wuqunfei Welcome to join the EMQ open source team:)  Please clone [emq-auth-http](https://github.com/emqtt/emq-auth-http) and check how to develop your own auth plugin

**Comment by wuqunfei** [comment]
@emqplus so nice to hear, let me understand emq-auth-http and learn some basic skill erlang to start it. I will keep working on it.
