### ISSUE TITLE
EMQX5.0.4: Redis AuthN will deny the unknown users instead of passing it to next Authenticator

### ISSUE THREAD

**Issue by qinl2017** [emqx/emqx#8800]
#### Environment

- OS: linux
- Erlang/OTP: 
- EMQ: 5.0.4

#### Description

我在配置文件配了两个认证链，第一个是redis，第二个是http，redis中找不到后，直接提示没有权限。
(I have two authenticatior in the configuration file, the first one is redis and the second one is http. If the user is not being found in redis, the AuthN will returned as no permission.)

**Comment by HJianBo** [comment]
方便贴下你的配置吗？

**Comment by qinl2017** [comment]
> 方便贴下你的配置吗？

![1661395024062](https://user-images.githubusercontent.com/31644623/186561591-0879499e-74f9-44a6-8428-3abf1c6b1380.jpg)
@HJianBo

**Comment by HJianBo** [comment]
找不到的意思是 redis 中没有这个 username ?，然后理论上来说，应该走到 auth-http 的认证器上，但是现在没有走？
试下最新的 5.0.6，里面的日志更全一些：
1. 开下 DEBUG 日志，看看里面认证的执行情况
2. 看下 Dashboard 的统计情况
3. 最后是认证成功还是失败了？

**Comment by qinl2017** [comment]
> 

是这个意思，我换成5.0.6了还是不行，以下是5.0.6的日志：
![image](https://user-images.githubusercontent.com/31644623/186566946-42f8890c-cda6-4f6c-b792-8e48530f0fe9.png)
Dashboard上显示的是失败：
![image](https://user-images.githubusercontent.com/31644623/186567017-694fe7bc-547f-42ad-b2b4-2419e4d373c9.png)
@HJianBo

**Comment by HJianBo** [comment]
看下 `HMGET mqtt:71e11.. passwrod_hash salt is_superuser` 在 Redis 上执行的话，返回的内容是什么？

**Comment by qinl2017** [comment]
> 看下 `HMGET mqtt:71e11.. passwrod_hash salt is_superuser` 在 Redis 上执行的话，返回的内容是什么？

![image](https://user-images.githubusercontent.com/31644623/186582944-df2b7c2c-b7cf-448d-8d0b-2355a35ec44e.png)
如果redis里没有这个key的话，是返回这个。 @HJianBo

**Comment by HJianBo** [comment]
感谢，这看起来是个 BUG 晚点我会修复它，并发布在后续的 5.0.x 版本中

**Comment by qinl2017** [comment]
> 感谢，这看起来是个 BUG 晚点我会修复它，并发布在后续的 5.0.x 版本中 Thanks, this looks like a bug I'll fix it later

好的，感谢
