### ISSUE TITLE
emqx_web_hook

### ISSUE THREAD

**Issue by yyhuang19** [emqx/emqx#8814]
### What happened?

Packets sent to the server may be lost or in the wrong order.Sometimes the delay is very high.

### What did you expect to happen?

Packets sent to the server may be lost or in the wrong order.Sometimes the delay is very high.

### EMQX version

<details>

```console
$ ./bin/emqx_ctl broker
# paste output here
```
4.4.4
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Log files

<details>

</details>

**Comment by terry-xiaoyu** [comment]
Could you provide the detailed procedure to reproduce the issue?

Please try to send messages from large amount of MQTT clients, not a single MQTT client. And also enlarge the pool size of webhook, to enhance the throughput.
