### ISSUE TITLE
EMQ5.0.4中auth_redis是否支持客户端不传密码进行连接

### ISSUE THREAD

**Issue by qinl2017** [emqx/emqx#8815]
### What would you like to be added or enhanced?

auth_redis认证时，可否将password_hash设置为非必选?

### Why is this needed?

在配置了auth_redis认证后，客户端若密码为空，提示bad username or password。我们之前用的是4.1.x版本，用的http认证方式，设备连接时，没有配置密码，现想升级到5.0.x，并用auth_redis方式认证，但客户端若密码为空，提示bad username or password，这样会影响之前所有设备的连接。

**Comment by zmstone** [comment]
5.0 一旦开启了认证，就不会允许匿名。
您可以通过添加另外一个监听器，并且把这个监听器的 enable_auth 设置成 false，来允许这些密码为空的客户端接入。
