### ISSUE TITLE
Delay of publishing connected/disconnected status

### ISSUE THREAD

**Issue by sasiNiranjana** [emqx/emqx#883]
#### Environment

- OS: Ubuntu 14.04
- Erlang/OTP: 19.2
- EMQ: 2.0.7

#### Description

I am using mosquito as my current broker in order to power my IOT project but I am planing to move forward with EMQTT since I have discovered much more powerful features in it. I have a very few uncleared areas to get cleared and describing my issues as follows.

1. According to my project specifications, it is very important for me to get the online/offline status of the connected devices. In mosquito, what I did is nothing but tailing the log of mosquito broker to get the message of connection status and pass that value to my REST API. I did the same implementation in my EMQTT test using hooks to call the same API. When I measured the time which it takes to reflect the status in the database, I realized that mosquito implementation is happening in an instant but EMQTT one is delaying around 20 seconds than mosquito. (Keep alive time for the devices is 15 seconds and I tested by dropping the internet connection for the device) . I would like to know the reason for this delay. Is it because of the keep alive time or the hook?

2. In the MQTT specifications, it is clearly mentioned that also the client has a responsibility to store the data of the session when it  is connected with the clean session flag is equal to false so that it does not require to re subscribe to the same topics it has subscribed before. My question is if one of my clients connects to EMQTT with clean session false and subscribes to a topic then all of a sudden something happens in the server and it is getting stopped. In this scenario, will the session data which was created before for my client be still available when the server is back? In another words, will the session data be available across multiple restart attempts on the server side? Is it saved in memory or in the hard disk as a separate file?

**Comment by zhengyupan** [comment]
Hi @sasiNiranjana:
 For the question 1, according to MQTT protocol, the broker is not aware of the connection lost of a client at once, if ti doesn't expressly 'disconnects' from the broker. The broker can be sure of the client connection is lost only when the client doesn't send ping in an agreed interval. I believe this is where the delay comes.
For the question 2, the open source edition of EMQ X saves the session in memory, it will go lost when the broker stops. Besides the open source edition, we have also an EMQ X Enterprise edition, which support date persistence on backend DB. It stores the session on DB, thus the sessions don't go lost even when the broker is restarted.
