### ISSUE TITLE
MQTT connection hangs and cannot be kicked out

### ISSUE THREAD

**Issue by stayhungry001** [emqx/emqx#8836]
### What happened?

EMQX版本： Broker 4.4.3
客户端-->EMQX --> 服务端 --> EMQX --> 客户端的场景，客户端消息投递到了服务端，服务端消息也投递出来了，但是客户端没有收到来自服务端的消息。在控制台手动kickout客户端，无法剔除客户端，查看日志发现如下错误：
2022-08-30T02:51:28.441660+00:00 [warning] [CM] kicked_an_unknown_session 202208061840195168245
服务端对接了多个客户端，就一个客户端有问题，其他客户端都正常通信。
最后通过重启客户端后恢复。

### What did you expect to happen?

客户端和服务端可以正常通过EMQX通信。

### How can we reproduce it (as minimally and precisely as possible)?

无

### EMQX version

<details>

```console
$ ./bin/emqx_ctl broker
bash-5.1$ emqx_ctl broker
sysdescr  : EMQ X Broker
version   : 4.4.3
uptime    : 4 days, 4 hours, 0 minutes, 51 seconds
datetime  : 2022-08-30 12:14:12
```

</details>

### OS version

<details>

```console
使用emqx operator部署的emqx三节点集群。

</details>


### Log files

<details>

</details>

**Comment by zmstone** [comment]
@stayhungry001 
Could be that a node left the cluster (or due to high load congested the communication, hence considered dead by other nodes) and missed some routing updates.

Are you using shared subscription?
Do you have logs from EMQX ?
