### ISSUE TITLE
Unable to scale concurrent connection

### ISSUE THREAD

**Issue by satyendrakumarsingh** [emqx/emqx#8843]
### What happened?

Running 3 node in a cluster for 1 million connection benchmark but each node have limitation of only 12K subscription/topic/connections.

![image](https://user-images.githubusercontent.com/16490760/187482494-03a7b30f-5e4e-4802-95d6-355b80eab8a0.png)

Below are the node details.

**sarvesh@emqx-1:~/EMQX$ sudo emqx_ctl vm**

cpu/load1               : 0.09
cpu/load5               : 0.03
cpu/load15              : 0.01
memory/total            : 126405456
memory/processes        : 39425448
memory/processes_used   : 39423832
memory/system           : 86980008
memory/atom             : 1917297
memory/atom_used        : 1914167
memory/binary           : 3482808
memory/code             : 44751950
memory/ets              : 8886360
process/limit           : 2097152
process/count           : 468
io/max_fds              : 1048576
io/active_fds           : 0
ports/count             : 23
ports/limit             : 1048576

**sarvesh@emqx-2:~/EMQX$ sudo emqx_ctl vm**

cpu/load1               : 0.06
cpu/load5               : 0.11
cpu/load15              : 0.07
memory/total            : 120136152
memory/processes        : 36136520
memory/processes_used   : 36131112
memory/system           : 83999632
memory/atom             : 1917297
memory/atom_used        : 1914189
memory/binary           : 352360
memory/code             : 44751822
memory/ets              : 9036408
process/limit           : 2097152
process/count           : 471
io/max_fds              : 1048576
io/active_fds           : 0
ports/count             : 26
ports/limit             : 1048576
 

**sarvesh@emqx:~/EMQX$ sudo emqx_ctl vm**

cpu/load1               : 0.00
cpu/load5               : 0.02
cpu/load15              : 0.00
memory/total            : 123085944
memory/processes        : 38052528
memory/processes_used   : 38051112
memory/system           : 85033416
memory/atom             : 1917297
memory/atom_used        : 1914189
memory/binary           : 1493088
memory/code             : 44751870
memory/ets              : 8930160
process/limit           : 2097152
process/count           : 471
io/max_fds              : 1048576
io/active_fds           : 0
ports/count             : 26
ports/limit             : 1048576

### What did you expect to happen?

I want to understand what configuration is wrong in above node setup.

### How can we reproduce it (as minimally and precisely as possible)?

Able to produce it with each load test, getting broker offline or connection lost / unable to connect to broker.

### EMQX version

<details>

```console
$ ./bin/emqx_ctl broker

sarvesh@emqx-1:~/EMQX$ emqx_ctl broker

sysdescr  : EMQX
version   : 5.0.6
datetime  : 2022-08-30T21:26:40.643521440+05:30
uptime    : 2 hours, 5 minutes, 57 seconds
```
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
sarvesh@emqx-1:~/EMQX$ cat /etc/os-release
NAME="Ubuntu"
VERSION="20.04.5 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.5 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```

</details>

### Log files

<details>

</details>

**Comment by zmstone** [comment]
Hi @satyendrakumarsingh 

Would be helpful if you can provide the node dump (when the system is about to reach its limit) for investigation.

**Comment by satyendrakumarsingh** [comment]
@zmstone and @qzhuyan ,

Thanks for your revert, After re-installation I am able to test single node upto 300K connection at 500 TPS and 8K message pub sub.

Will share 1000K+ plus test result soon and in case any help required I will get back to you guys.

Thanks for the quick revert, for now I am closing this thread.
