### ISSUE TITLE
HTTP Publish doesn't pass clientId to HTTP Auth/ACL Plugin

### ISSUE THREAD

**Issue by chimit** [emqx/emqx#886]
#### Environment

- OS: macOS 10.12.3 (16D32)
- Erlang/OTP: 
- EMQ: 2.0.7

#### Description

I'm using **emqttd** with HTTP Auth/ACL Plugin. For common MQTT clients it works perfect, but it doesn't work correctly when I try to publish an event through HTTP Publish.

Here are my HTTP Auth/ACL Plugin settings:
```
##--------------------------------------------------------------------
## HTTP Auth/ACL Plugin
##--------------------------------------------------------------------

## Variables: %u = username, %c = clientid, %a = ipaddress, %P = password, %t = topic

auth.http.auth_req = http://server.app/auth
auth.http.auth_req.method = post
auth.http.auth_req.params = client_id=%c
```
Here is what I'm trying to publish through HTTP Publish using the Postman app:

![2017-02-07 15 27 19](https://cloud.githubusercontent.com/assets/839349/22681768/00ae7886-ed4a-11e6-85a4-d03325baace5.png)

I always get:
```
15:19:51.731 [error] HTTP Auth failure: username=user, reason={http_code,404}
```

So I checked what does **emqttd** send to my auth server. The variable (`client_id`) which should include `client` provided by Postman is empty. Here is a log from my auth server:
```
[2017-02-07 07:19:51] Request: Array
(
    [client_id] => undefined
)
```

**Comment by chimit** [comment]
#887

**Comment by chimit** [comment]
Here is one more problem: all users are authenticated as Superusers even if `auth.http.super_req` returns Error 4xx. So currently emq_auth_http plugin is insecure.

**Comment by turtleDeng** [comment]
@chimit http publish api not support superuser auth

**Comment by chimit** [comment]
@turtleDeng you are wrong. On HTTP Publish an emqtt broker makes an HTTP request to the http://127.0.0.1:8080/mqtt/superuser endpoint. You can see it in the emqtt console.

Anyway, if it doesn't support superuser and acl why all these settings exist in the emq-auth-http plugin?
https://github.com/emqtt/emq-auth-http/blob/master/etc/emq_auth_http.conf

**Comment by StarpTech** [comment]
@turtleDeng is it planned to support ACL for the HTTP Publish api?

**Comment by StarpTech** [comment]
@chimit try the new release if you comment out the superuser section in emq_auth_http.conf the ACL and auth endpoints will be called.

**Comment by StarpTech** [comment]
@turtleDeng I tested with emqttd-2.1.0-beta.1 the clientId is not passed to the `/mqtt/auth` endpoint just username and password.

**Comment by emqplus** [comment]
@StarpTech The HTTP Publish API will be moved to Management/Monitor Plugin in 2.2. release.

**Comment by StarpTech** [comment]
@emqplus any plan when it will be released?

**Comment by Gilbert-Wong** [comment]
Sorry , we have no schedule to do acl/auth check for emqx_management publish api, if you have access to emqx_management, I suppose that it is unnecessary to do acl and auth check.
