### ISSUE TITLE
Bug: v5.0.7 topic metrics api return 404

### ISSUE THREAD

**Issue by sekfung** [emqx/emqx#8869]
### What happened?

topic:  user/update/error
api path: https://xxx.xxx.com/api/v5/mqtt/topic_metrics/user%2Fupdate%2Ferror

GET, DELETE method api both return 404

<img width="692" alt="image" src="https://user-images.githubusercontent.com/43331641/188001956-01b1cc2b-95b6-4a4f-a582-655cdd376eb1.png">

After created,  I couldn't delete it

### What did you expect to happen?

it would be successful

### EMQX version

<details>

```console
$ ./bin/emqx_ctl broker
# paste output here
```

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Log files

<details>

</details>

**Comment by ieQu1** [comment]
Hello,

EMQX doesn't collect topic metrics by default because it's expensive (there could be hundreds of thousands of topics), so metrics must be enabled for the particular topic using POST to `/api/v5/mqtt/topic_metrics` API.

You can refer to the swagger schema for mor details: http://xxx.xxx.com/api-docs/index.html#/MQTT/post_mqtt_topic_metrics

**Comment by JimMoen** [comment]
Please check whether topic metrics for the corresponding topic exists.
![image](https://user-images.githubusercontent.com/32241529/188528620-7785220d-45fa-4e69-a783-9e7a173c8d47.png)

---
Create a topic metrics.
```json
POST http://ip[:port]/api/v5/mqtt/topic_metric
{"topic": "user/update/error"}
```

**Comment by sekfung** [comment]
![image](https://user-images.githubusercontent.com/43331641/188537654-580eab6d-7d20-478e-ad73-c11a5beec293.png)

Hi, @JimMoen, the topic is not exists, but it still display on my dashboard, and i can not delete it.

I create a new topic, the problem is still

**Comment by fnhieu** [comment]
The issue is still here.
