### ISSUE TITLE
BUG reports

### ISSUE THREAD

**Issue by MQTTactic** [emqx/emqx#8873]
Hello, 

Dear developers of EMQX,  as we study EMQX, we have discovered some new security flaws that would lead to unauthorized access to the topics that are managed by EMQX. The details of these flaws have been sent to you last month but no response. Consequently, we want to check that the email “[security@emqx.io](mailto:security@emqx.io)” is correct and that these security flaws are confirmed? 

Thanks! If you need any further information, please email me back at [MQTTactic@gmail.com](mailto:MQTTactic@gmail.com). @

**Comment by ieQu1** [comment]
Hi,
Thanks for the report, we'll take a look.

**Comment by zmstone** [comment]
Hi @MQTTactic 
Thank you for the reports, and sorry for the late response.
I have tried to reply all your emails.
To sum up, most of the issues are very good thoughts and are potential security risks.
All of them seem to have means to mitigate (which are included in the reply).
 
I'm closing this issue from here. Let's follow up from the email thread.
