### ISSUE TITLE
MQTT connection is killed if it received too many messages

### ISSUE THREAD

**Issue by zhou-hao** [emqx/emqx#8899]
### What happened?

单个客户端订阅数据时, 如果推送的消息量较大,(目前测试为 1w/s), 客户端会被断开连接,但是断开的时机不太固定.
默认是否有什么配置来限制客户端订阅收到的数据量?

### What did you expect to happen?

不会断开连接

### EMQX version

docker
<details>

```console
$ ./bin/emqx_ctl broker
listener.ssl.external.acceptors = "32"
listener.ssl.external.max_connections = "102400"
listener.tcp.external.acceptors = "64"
listener.tcp.external.max_connections = "1024000"
listener.ws.external.acceptors = "16"
listener.ws.external.max_connections = "102400"
listener.wss.external.acceptors = "16"
listener.wss.external.max_connections = "102400"
log.to = "console"
node.max_ets_tables = "2097152"
node.max_ports = "1048576"
node.name = "f89229179e24@172.17.0.3"
node.process_limit = "2097152"
rpc.port_discovery = "manual"
Starting emqx on node f89229179e24@172.17.0.3
2022-09-06T06:29:33.006087+00:00 [warning] [Alarm Handler] Alarm high_system_memory_usage is activated, System memory usage is higher than 70.0%
Start mqtt:tcp:internal listener on 127.0.0.1:11883 successfully.
Start mqtt:tcp:external listener on 0.0.0.0:1883 successfully.
Start mqtt:ws:external listener on 0.0.0.0:8083 successfully.
Start mqtt:ssl:external listener on 0.0.0.0:8883 successfully.
Start mqtt:wss:external listener on 0.0.0.0:8084 successfully.
Start http:management listener on 8081 successfully.
Start http:dashboard listener on 18083 successfully.
EMQ X Broker 4.4.0 is running now!
```

</details>

### OS version

MacOS 11.6.7

### Log files

<details>

</details>

**Comment by zhongwencool** [comment]
没有配置限制客户端订阅收到的数据量。

可以检查下emqx的日志，有没有断开相关的日志，如果是异常断开，会出现在日志里的。

**Comment by 445990772** [comment]
> 没有配置限制客户端订阅收到的数据量。
> 
> 可以检查下emqx的日志，有没有断开相关的日志，如果是异常断开，会出现在日志里的。

我本地测试的时候发现了一条info日志显示的
![4b56b8f0e305fb70658007af2cd6a71](https://user-images.githubusercontent.com/9440839/188592546-d4595eab-59f7-4f2a-8d3e-6889c14e42d7.jpg)
这个设备随后就断开和emq的连接了 是因为这个message_queue里面的数据过长导致的吗？

**Comment by zhou-hao** [comment]
<img width="1565" alt="image" src="https://user-images.githubusercontent.com/7791838/188625653-1dd7652f-4281-4f10-ac46-fb96ecd94894.png">

**Comment by lafirest** [comment]
> > 没有配置限制客户端订阅收到的数据量。
> > 可以检查下emqx的日志，有没有断开相关的日志，如果是异常断开，会出现在日志里的。
> 
> 我本地测试的时候发现了一条info日志显示的 ![4b56b8f0e305fb70658007af2cd6a71](https://user-images.githubusercontent.com/9440839/188592546-d4595eab-59f7-4f2a-8d3e-6889c14e42d7.jpg) 这个设备随后就断开和emq的连接了 是因为这个message_queue里面的数据过长导致的吗？

This is the forced shutdown policy triggered due to your process accumulates too many messages. 
See the ` zone.external.force_shutdown_policy` at https://www.emqx.io/docs/en/v4.3/configuration/configuration.html#authacl for details

**Comment by 445990772** [comment]
> > > 没有配置限制客户端订阅收到的数据量。
> > > 可以检查下emqx的日志，有没有断开相关的日志，如果是异常断开，会出现在日志里的。
> > 
> > 
> > 我本地测试的时候发现了一条info日志显示的 ![4b56b8f0e305fb70658007af2cd6a71](https://user-images.githubusercontent.com/9440839/188592546-d4595eab-59f7-4f2a-8d3e-6889c14e42d7.jpg) 这个设备随后就断开和emq的连接了 是因为这个message_queue里面的数据过长导致的吗？
> 
> This is the forced shutdown policy triggered due to your process accumulates too many messages. See the ` zone.external.force_shutdown_policy` at https://www.emqx.io/docs/en/v4.3/configuration/configuration.html#authacl for details

想问一下在大量数据写入的时候如何保留这些数据而不是丢弃？

**Comment by zhongwencool** [comment]
> 想问一下在大量数据写入的时候如何保留这些数据而不是丢弃？

得那得你的订阅客户端消费能力足够强。或者使用共享订阅。
如果消费不及时，消息就会一直累积在这个进程中，默认是当个数达到1000个时就断开。
你可以通过设置`mqtt.max_mqueue_len` 来调整这个1000值（甚至可以直接设置为infinity，这时此连接就会保持累积致整个机器内在消耗完后，节点挂掉）
