### ISSUE TITLE
Problem with EMQX 5.0.5-5.0.7 HTTP Auth

### ISSUE THREAD

**Issue by jinshu2604** [emqx/emqx#8910]
### What happened?

5.0.5-5.0.7三个版本中
在访问控制-授权菜单中，数据源使用HTTP Server，配置上自己的服务地址，无法回调。
在访问控制-认证菜单中，是没有问题的。

5.0.4版本都没有问题

### What did you expect to happen?
配置如下图，5.0.5-5.0.7三个版本中根本监听不到有授权回调的请求，5.0.4版本有请求。
![image](https://user-images.githubusercontent.com/58423617/188786050-3006bb89-8320-4572-a90b-864f6c4f0477.png)

### EMQX version

<details>

```console
$ ./bin/emqx_ctl broker
# paste output here
sysdescr  : EMQX
version   : 5.0.5 5.0.6 5.0.7

</details>


### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

emqx/emqx:5.0.4-amd64-alpine



### Log files

<details>

</details>

**Comment by lafirest** [comment]
@jinshu2604 Hello,
Can you set the log level to `debug` and then generate some authorization logs? If there are detailed logs, we can better investigate the problem

**Comment by jinshu2604** [comment]
> @jinshu2604 Hello, Can you set the log level to `debug` and then generate some authorization logs? If there are detailed logs, we can better investigate the problem
[emqx.txt](https://github.com/emqx/emqx/files/9503789/emqx.txt)

**Comment by lafirest** [comment]
This is a strange bug, we use `undefined` as the initial value of `mountpoint`, and then use `undefined` in authz to determine whether the placeholder exists, in fact, what we want here is null check

**Comment by geffzhang** [comment]
I've run into this problem too

**Comment by zmstone** [comment]
@savonarola seems to be an issue introduced in 64aa30ec631e37970db0568d1aea83e44987a9f3 ?

**Comment by savonarola** [comment]
We changed some logic to avoid silent interpolation of unset variables into "undefind", which can clash with the existing values and lead to security issues. May be this should be assigned to me.
