### ISSUE TITLE
Got incorrect clientId using exhooks

### ISSUE THREAD

**Issue by jinshu2604** [emqx/emqx#8929]
### What happened?

使用EMQX插件扩展中的ExHook功能，名称为client.connect的钩子，传来的mqtt版本与EMQX和MQTTX中不符。

### What did you expect to happen?

MQTTX工具选择版本3.1.1
![lQLPJxaqqyL9owLNAu3NBAGwCpeU3jgoRgoDGLCIZgBUAA_1025_749](https://user-images.githubusercontent.com/58423617/189082624-4d2dde57-ef1a-4a0f-a386-91948b46f8bb.png)
Dashboard中显示版本为3.1.1
![lQLPJxaqrAdGz2vNA6nNB4Cw8lf4iipprW8DGLH-ykCtAA_1920_937](https://user-images.githubusercontent.com/58423617/189082884-ce03fd77-a32a-4e6c-9900-b8eb7283d73e.png)
通过client.connect获取的版本为4
![lQLPJxaqq0pUcsfNAeHNBLCwOshE8pAkZWUDGLDJJ0AvAA_1200_481](https://user-images.githubusercontent.com/58423617/189083070-0133a4c3-61cf-404c-8e83-77166ded5e9d.png)

### EMQX version

<details>

```console
$ ./bin/emqx_ctl broker
# paste output here

emqx/emqx:5.0.7-amd64-alpine

</details>


### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Log files

<details>

</details>

**Comment by terry-xiaoyu** [comment]
It is 4. The MQTT Protocol uses the integer 4 to indicate version "3.1.1".
