### ISSUE TITLE
Dashboard - Lookup all online clients

### ISSUE THREAD

**Issue by jhaoheng** [emqx/emqx#897]
#### Environment

- OS: centos7
- Erlang/OTP: 18 
- EMQ: 2.0.7

#### Description

*A description of the issue*

I build two emq2.0.7 into a clusters and sub to one emq node.
Now i want to get all client from EMQ clusters.

I had see the change from 'http://emqtt.com/docs/v2/changes.html'
**2.0.3** : emq-dashboard#86: Lookup all online clients

but when i call the api, can't get all online clients.

I need to get the truth of client from EMQ clusters.

Thanks

**Comment by Linuturk** [comment]
I wanted to +1 this request. If the nodes are in a cluster, the connected client data should be shared between all nodes for consistent API and Dashboard interactions.

**Comment by zhengyupan** [comment]
Supported in new release 3.0

**Comment by fuji4** [comment]
> Supported in new release 3.0

Can't confirm this. I've installed v3.0.1 and when I query `/api/v3/connections/, I still get only the connections from the node I'm querying...

**Comment by zhengyupan** [comment]
@fuji4 Sorry, I got this wrong, it is not implemented yet.

**Comment by vytasmk** [comment]
So this issue could be updated/renamed to include not only _connections_ but also _sessions_ and _subsriptions_ as those endpoints also return information only from one node even when in dashboard "All nodes" is selected.

**Comment by HJianBo** [comment]
I have got this, and plan to fix it in the next version.

Just close it, because it duplicated at https://github.com/emqx/emqx-dashboard/issues/37.
