### ISSUE TITLE
Option to disable settings through dashboard

### ISSUE THREAD

**Issue by joggeli34** [emqx/emqx#8991]
### What would you like to be added or enhanced?

We are deploying the emqx in kubernetes with the helm chart. We use GitOps for all settings. So it would be nice to have an option  to disable the settings through the ui. 
The dashboard should still be visible for the status and clients. And probably also to see the settings but not to modify them.

### Why is this needed?

This should prevent to have different settings currently running then configured in the helm chart. This way, the git-repo with the configuration is the only "truth" for the applied settings.

**Comment by lafirest** [comment]
@wivwiv

**Comment by zmstone** [comment]
@joggeli34 

Do you mean a read-only dashboard ?

**Comment by joggeli34** [comment]
Yes, read-only for all the settings that can be done by the config-file.
But it could be handy to be able to do things like kickout sessions.

**Comment by zmstone** [comment]
Starting from 5.4, there is a `role` concept for dashboard users and API keys.
For dashboard, there are two kinds of pre-defined roles, `viewer` and `administrator`.
For APIs, there are three: `viewer`, `administrator` and `publisher`.

Not sure if this meets your requirements @joggeli34, but I am untagging the "Feature" label now.
