### ISSUE TITLE
Unable to send  file than over ~500kb with qos > 0

### ISSUE THREAD

**Issue by stanislav-sheev** [emqx/emqx#8993]
### What happened?

I am trying to send a file using console utility `mosquitto_pub -h 127.0.0.1 -p 8883 -t 'my-topic' -u bla-bla -P 'bla-bla' -i 'bla-bla' -k 2 -q 2 --capath /etc/ssl/certs/  -d  --insecure -s < /opt/emqx.png`
**and get an console error**
`Client bla-bla sending CONNECT
Client bla-bla received CONNACK
Client bla-bla sending PUBLISH (d0, q2, r0, m1, 'my-topic', ... (622534 bytes))
Error: The connection was lost.`
**BUT then i change qos to 0**
`mosquitto_pub -h 127.0.0.1 -p 8883 -t 'my-topic' -u bla-bla -P 'bla-bla' -i 'bla-bla' -q 0 --capath /etc/ssl/certs/  -d  --insecure -s < /opt/emqx.png`
the packet  sent successfully!!
`Client bla-bla sending CONNECT
Client bla-bla received CONNACK
Client bla-bla sending PUBLISH (d0, q0, r0, m1, 'my-topic', ... (622534 bytes))
Client bla-bla sending DISCONNECT`
**BUT then i try to send file < 300kb with qos >2 it also sends without error**
The dashboard settings 
Max Packet Size (Maximum MQTT packet size allowed) is 10 Mb.

### What did you expect to happen?

successful sending of the package

### How can we reproduce it (as minimally and precisely as possible)?

How can we reproduce it (as minimally and precisely as possible)?

### EMQX version

<details>

```console
$ ./bin/emqx_ctl broker
sysdescr  : EMQX
version   : 5.0.5
datetime  : 2022-09-16T19:58:12.511023225+00:00
uptime    : 34 minutes, 0 seconds
```

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 9 (stretch)"
NAME="Debian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"
VERSION_CODENAME=stretch
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Log files

<details>
Process:            <0.3135.0> on node 'emqx@127.0.0.1', Context:            maximum heap size reached, Max Heap Size:      6291456, Total Heap Size:    7221737, Kill:               true, Error Logger:       true, Message Queue Len:  0, GC Info:            [{old_heap_block_size,1727361},{heap_block_size,4712239},{mbuf_size,1245068},{recent_size,0},{stack_size,64},{old_heap_size,1246946},{heap_size,1264430},{bin_vheap_size,534},{bin_vheap_block_size,104109},{bin_old_vheap_size,154793},{bin_old_vheap_block_size,98315}]
</details>

**Comment by lafirest** [comment]
@stanislav-sheev, I think you can just increase `max_heap_size`, but I'm wondering why so much memory is being used, I'll look into this

**Comment by stanislav-sheev** [comment]
This is not an option .. The same file is sent or not depending on the value of QOS

**Comment by stanislav-sheev** [comment]
> @stanislav-sheev, I think you can just increase `max_heap_size`, but I'm wondering why so much memory is being used, I'll look into this
This is not an option .. The same file is sent or not depending on the value of QOS

**Comment by lafirest** [comment]
@stanislav-sheev 
Sorry for the late reply, after I investigated, I am sure there is no problem.
I guess maybe your MQTT broker wasn't EMQX but mosquitto, you can check your EMQX logs to verify this guess.
<img width="587" alt="image" src="https://github.com/emqx/emqx/assets/22971499/7bf71463-8c4b-4531-b9ad-b3cf3f41311c">
