### ISSUE TITLE
Accept XADD / Redis Streams as a data type for Redis - Either stand alone plugin or addition to Redis capability

### ISSUE THREAD

**Issue by xtianus79** [emqx/emqx#9010]
### What would you like to be added or enhanced?

[This blog post](https://redis.com/blog/youre-probably-thinking-about-redis-streams-wrong/) is a good explainer on the differences of H(hash)SET and X(Redis streams)ADD data sets. 

I wouldn't mind helping build the plugin but I would like to at least getting the starter plugin code for Redis as it stands now. Is that located anywhere? 

Redis streams should be the choice for this type of telemetry / data forwarding / messaging that is provided by the mqtt broker. Also, Redis is lightening fast. 

To me, it could be a stand alone plugin or it could add the functionality to the existing plugin now. With that said, I'd like to help either way and keep the offering with you guys. I only want to have usage and I'd be happy to contribute. 

What do you guys think? 

### Why is this needed?

Redis Streams makes perfect sense for MQTT IOT devices. More so than HSET

**Comment by terry-xiaoyu** [comment]
Here is the redis-auth plugin you can take as an example: `https://github.com/emqx/emqx/tree/main-v4.3/apps/emqx_auth_redis`.

Basically you need to create an erlang app under the apps dir, and then add the module attribute `-emqx_plugin(bridge).` in to your `apps/<app-name>/src/<app-name>_app.erl`.

We may support redis stream in the future, but you can create your own one before that.

**Comment by xtianus79** [comment]
@terry-xiaoyu thanks I was able to set it up through modules! works great.

<img width="767" alt="Screenshot 2022-10-10 151148" src="https://user-images.githubusercontent.com/8476336/195414194-587661a1-0586-4e41-b4c8-5a4d68722720.png">
