### ISSUE TITLE
Publishing messages from the HTTP API

### ISSUE THREAD

**Issue by tianxingxia** [emqx/emqx#9017]
### Discussed in https://github.com/emqx/emqx/discussions/8510

<div type='discussions-op-text'>
<sup>Originally posted by **AmirOsman2020** July 20, 2022</sup>
now I have a problem with use exhook, when client publish message, try reply message to client with http api，but find there have a 4 or 5 seconds delay, and emqx report some error log, like   "[error] [gRPC Client] Stream shutdown reason: {stream_error,cancel,'Stream reset by server.'}, stream: #stream{st={closed,idle}, buff_size=0, mqueue=[]}"
Amazing things is very in time when push message to another program with kafka, then publish message to client with http api.

**what makes the difference?**
</div>

**Comment by terry-xiaoyu** [comment]
I didn't see above discussion in #8510, do you mean you have a problem about exhook？

Could you describe more detailed about your question?

**Comment by tianxingxia** [comment]
>

**Comment by HJianBo** [comment]
It looks like there is a high latency in your HTTP API Publish calls due to exhook.

Can you check the configuration of your exhook and the running status of the corresponding grpc server?
