### ISSUE TITLE
client.authorize still cant not excute

### ISSUE THREAD

**Issue by Mark-jk** [emqx/emqx#9022]
### What happened?

5.0.8  changelog
 Fix the issue that the authorization would terminate the execution of the client.authorize hook when no rules were matched

when i upgrade the latest version 5.0.8 , this bug still happed.

### What did you expect to happen?

client.authorize still cant execute

### EMQX version

<details>

```console
$ ./bin/emqx_ctl broker
# paste output here
sysdescr  : EMQX
version   : 5.0.8
datetime  : 2022-09-21T18:40:19.853383578+00:00
uptime    : 26 minutes, 8 seconds
```

</details>

### Log files

![image](https://user-images.githubusercontent.com/7497349/191585024-007fdb3e-3071-4571-b732-556b23fb3f17.png)

**Comment by JimMoen** [comment]
Is that ExHook registered hooks?

**Comment by HJianBo** [comment]
Could you take some DEBUG logs for a Authz checking process?

**Comment by Mark-jk** [comment]
Thanks. I know what happened. I used Docker to run a new service. there is default file auth. When it closed, the callback is normal.

**Comment by HJianBo** [comment]
Thanks let me know
