### ISSUE TITLE
Can I have a user automatically subscribe to a topic?

### ISSUE THREAD

**Issue by bbhxwl** [emqx/emqx#9027]
### What would you like to be added or enhanced?

Can I have a user automatically subscribe to a topic?

I think only everyone can automatically subscribe to the same topic

### Why is this needed?

·

**Comment by HJianBo** [comment]
Do you mean that emqx adds a subscription for each client once connected?

In emqx v4.x, you can modify the following options in `emqx.conf` to implement it:
```bash 
##--------------------------------------------------------------------
## Subscription Module

## Subscribe the Topics automatically when client connected.
##
## Value: String
## module.subscription.1.topic = connected/%c/%u

## Qos of the proxy subscription.
##
## Value: 0 | 1 | 2
## Default: 0
## module.subscription.1.qos = 0

## No Local of the proxy subscription options.
## This configuration only takes effect in the MQTT V5 protocol.
##
## Value: 0 | 1
## Default: 0
## module.subscription.1.nl = 0

## Retain As Published of the proxy subscription options.
## This configuration only takes effect in the MQTT V5 protocol.
##
## Value: 0 | 1
## Default: 0
## module.subscription.1.rap = 0

## Retain Handling of the proxy subscription options.
## This configuration only takes effect in the MQTT V5 protocol.
##
## Value: 0 | 1 | 2
## Default: 0
## module.subscription.1.rh = 0
```

In emqx 5, you can add a `Auto Subscribe` topic to each clients by Dashboard:
![Screenshot from 2022-09-23 11-08-09](https://user-images.githubusercontent.com/13825269/191885270-8c05e26e-0ab1-426d-b04a-a675f99cce0e.png)

**Comment by bbhxwl** [comment]
> Do you mean that emqx adds a subscription for each client once connected?
> 
> In emqx v4.x, you can modify the following options in `emqx.conf` to implement it:
> 
> ```shell
> ##--------------------------------------------------------------------
> ## Subscription Module
> 
> ## Subscribe the Topics automatically when client connected.
> ##
> ## Value: String
> ## module.subscription.1.topic = connected/%c/%u
> 
> ## Qos of the proxy subscription.
> ##
> ## Value: 0 | 1 | 2
> ## Default: 0
> ## module.subscription.1.qos = 0
> 
> ## No Local of the proxy subscription options.
> ## This configuration only takes effect in the MQTT V5 protocol.
> ##
> ## Value: 0 | 1
> ## Default: 0
> ## module.subscription.1.nl = 0
> 
> ## Retain As Published of the proxy subscription options.
> ## This configuration only takes effect in the MQTT V5 protocol.
> ##
> ## Value: 0 | 1
> ## Default: 0
> ## module.subscription.1.rap = 0
> 
> ## Retain Handling of the proxy subscription options.
> ## This configuration only takes effect in the MQTT V5 protocol.
> ##
> ## Value: 0 | 1 | 2
> ## Default: 0
> ## module.subscription.1.rh = 0
> ```
> 
> In emqx 5, you can add a `Auto Subscribe` topic to each clients by Dashboard: ![Screenshot from 2022-09-23 11-08-09](https://user-images.githubusercontent.com/13825269/191885270-8c05e26e-0ab1-426d-b04a-a675f99cce0e.png)

docker run -itd  --restart=always --name emqx -p 1883:1883 -p 8081:8081 -p 8083:8083 -p 8883:8883 -p 8084:8084 -p 18083:18083 emqx:latest 
I may need an API interface to subscribe to different topics for a user. The version of 4 you posted above seems to be different. The version of 5 looks like. When I use the above command, why do I run version 4? How should I run version 5?

**Comment by lafirest** [comment]
> > Do you mean that emqx adds a subscription for each client once connected?
> > In emqx v4.x, you can modify the following options in `emqx.conf` to implement it:
> > ```shell
> > ##--------------------------------------------------------------------
> > ## Subscription Module
> > 
> > ## Subscribe the Topics automatically when client connected.
> > ##
> > ## Value: String
> > ## module.subscription.1.topic = connected/%c/%u
> > 
> > ## Qos of the proxy subscription.
> > ##
> > ## Value: 0 | 1 | 2
> > ## Default: 0
> > ## module.subscription.1.qos = 0
> > 
> > ## No Local of the proxy subscription options.
> > ## This configuration only takes effect in the MQTT V5 protocol.
> > ##
> > ## Value: 0 | 1
> > ## Default: 0
> > ## module.subscription.1.nl = 0
> > 
> > ## Retain As Published of the proxy subscription options.
> > ## This configuration only takes effect in the MQTT V5 protocol.
> > ##
> > ## Value: 0 | 1
> > ## Default: 0
> > ## module.subscription.1.rap = 0
> > 
> > ## Retain Handling of the proxy subscription options.
> > ## This configuration only takes effect in the MQTT V5 protocol.
> > ##
> > ## Value: 0 | 1 | 2
> > ## Default: 0
> > ## module.subscription.1.rh = 0
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > In emqx 5, you can add a `Auto Subscribe` topic to each clients by Dashboard: ![Screenshot from 2022-09-23 11-08-09](https://user-images.githubusercontent.com/13825269/191885270-8c05e26e-0ab1-426d-b04a-a675f99cce0e.png)
> 
> docker run -itd --restart=always --name emqx -p 1883:1883 -p 8081:8081 -p 8083:8083 -p 8883:8883 -p 8084:8084 -p 18083:18083 emqx:latest I may need an API interface to subscribe to different topics for a user. The version of 4 you posted above seems to be different. The version of 5 looks like. When I use the above command, why do I run version 4? How should I run version 5?

When you started EMQX version 5, you can find this `http://127.0.0.1:18083/api-docs/index.html#/Clients/post_clients__clientid__subscribe` API to suit your needs, note that `127.0.0.1` should be replace with the IP used by EMQX

**Comment by HJianBo** [comment]
It may be better to use the specified name:
```
sudo docker run -itd --restart=always --name emqx -p 1883:1883 -p 8081:8081 -p 8083:8083 -p 8883:8883 -p 8084:8084 -p 18083:18083 emqx/emqx:5.0.8
```
