### ISSUE TITLE
When will the Apple M1/M2 chip be supported?

### ISSUE THREAD

**Issue by 12343954** [emqx/emqx#9039]
<img style="width:100%;" alt="Screen Shot 2022-09-25 at 01 49 45" src="https://user-images.githubusercontent.com/1804003/192111999-68f89106-4146-424f-b5b6-f78d3c14fb1a.png">

very appreciate！

**Comment by zmstone** [comment]
Hi. It's a work-in-progress.

**Comment by 12343954** [comment]
> Hi. It's a work-in-progress.

good job，thank you very much！

**Comment by linz2h** [comment]
OTP 25 has already released for sometime with Arm64 JIT support. I think the EMQX team is testing it to meet the quality standard.

**Comment by id** [comment]
@12343954 quick fix is to install coreutils via Homebrew
```
brew install coreutils
```

But as @zmstone said it's going to be fixed soon.

**Comment by 12343954** [comment]
@id  Thank you for reply！Don't worry, I'll wait to fix it. 😄

**Comment by id** [comment]
@12343954 can you try now with the latest release?

**Comment by 12343954** [comment]
@id thank you!
follow the steps and stuck on the second one. 
what's the `realpath`?

<img width="1470" alt="image" src="https://user-images.githubusercontent.com/1804003/198255024-a6774a36-d266-47e9-8aac-df8f74b5d9a2.png">

**Comment by 12343954** [comment]
@id  very appreciate it！ 
I run the latest release directly, it's ok. ✅
But following the compiling steps, still can't compile. ❌

<img width="1470" alt="image" src="https://user-images.githubusercontent.com/1804003/198268257-0f59ff9c-8676-4e75-984a-a831e0f041a1.png">

**Comment by id** [comment]
@12343954 could you provide more details about compilation problem?

**Comment by id** [comment]
@12343954 and if you `unset LDFLAGS` and re-run make again?

**Comment by 12343954** [comment]
`unset LDFLAGS` ?  what should I do?

**Comment by id** [comment]
> `unset LDFLAGS` ? what should I do?

in your terminal:
```bash
unset LDFLAGS
make
```

**Comment by 12343954** [comment]
after set `unset LDFLAGS`, compilation is ok.
`./emqx start` is ok, but can not connect the mqtt server.

<img width="1472" alt="image" src="https://user-images.githubusercontent.com/1804003/198619463-b8f33ed4-e985-458d-a749-eb01ad393c10.png">

<img width="1470" alt="image" src="https://user-images.githubusercontent.com/1804003/198622722-26784d83-b6dc-4960-a91b-6fa1f8f54ed5.png">

**Comment by id** [comment]
It looks like you extracted files from the generated .tar.gz and run emqx from there. MacOS decided that it's a security threat and issued this warning. You can resolve it in Security & Privacy section of System Preferences
![image](https://user-images.githubusercontent.com/138221/198635375-152f439e-f9f3-4af0-a9d9-c301a4f32b8f.png)

But if you just run `_build/emqx/rel/emqx/bin/emqx console` from the same directory where you build emqx, it should work without warning.

**Comment by 12343954** [comment]
yes, I extracted files from the generated .tar.gz and run emqx.

according to your suggestion:
1. ✅ run `_build/emqx/rel/emqx/bin/emqx console`, it's ok. 
2. ✅ copy `_build/emqx/rel/emqx` to anywhere and run `./emqx console`, it's ok.
3. ❌ only run the extracted files from the generated .tar.gz is NOT ok , always show the above security warning(erlang_jq_port).

**Comment by id** [comment]
@12343954 

3. This is not something we can fix. MacOS Gatekeeper blocks binary files from executing unless they are signed by verified developer. We sign binaries when create .tar.gz in CI, but we cannot help you to sign binaries when you build them yourself as this requires our private key.

**Comment by id** [comment]
We are planning to start building .tar.gz with apple silicon binaries (signed by us) soon.
