### ISSUE TITLE
Docker - setting EMQX_ALLOW_ANONYMOUS=false prevent emqx_auth_mnesia loading

### ISSUE THREAD

**Issue by RobertoD91** [emqx/emqx#9043]
### What happened?

Using together `EMQX_ALLOW_ANONYMOUS=false` and `EMQX_LOADED_PLUGINS=emqx_auth_mnesia`  result in emqx_auth_mnesia plugin not loading.

### What did you expect to happen?

Login with credential

### How can we reproduce it (as minimally and precisely as possible)?

This work (but anonymous login is allow)

```Dockerfile
version: "3"

services:
  emqx:
    image: emqx:4.4
    ports:
      - "0.0.0.0:1883:1883"
    environment:
      #- EMQX_ALLOW_ANONYMOUS=false 
      - EMQX_auth__client__1__clientid=test
      - EMQX_auth__client__1__password=test
      - EMQX_auth__user__2__username=test
      - EMQX_auth__user__2__password=test
      - EMQX_LOADED_PLUGINS=emqx_auth_mnesia 
```

This don't work, i can't login:

```Dockerfile
version: "3"

services:
  emqx:
    image: emqx:4.4
    ports:
      - "0.0.0.0:1883:1883"
    environment:
      - EMQX_ALLOW_ANONYMOUS=false 
      - EMQX_auth__client__1__clientid=test
      - EMQX_auth__client__1__password=test
      - EMQX_auth__user__2__username=test
      - EMQX_auth__user__2__password=test
      - EMQX_LOADED_PLUGINS=emqx_auth_mnesia 
```

seems that plugin emqx_auth_mnesia don't start
```console
$ docker exec -it mqtt-emqx-1 /opt/emqx/bin/emqx_ctl plugins list
(...)
Plugin(emqx_auth_mnesia, description=EMQ X Authentication with Mnesia, active=false)
(...)
```
after `docker exec -it SOMETHING-emqx-1 /opt/emqx/bin/emqx_ctl plugins load emqx_auth_mnesia` the credential test/test work

### EMQX version

docker image emqx:4.4

**Comment by id** [comment]
@RobertoD91 [here](https://hub.docker.com/r/emqx/emqx/tags?page=1&name=4.4) is the list of our official images for 4.4 version. Could you try the latest one, `emqx/emqx:4.4.9`?

**Comment by id** [comment]
`emqx` images without `emqx/` prefix come from https://github.com/emqx/emqx-docker, and lagging behind `emqx/emqx`. We plan to address this discrepancy soon.
Thank you!
