### ISSUE TITLE
Add ACL rules to be loaded in using the Helm chart values for v5+

### ISSUE THREAD

**Issue by idelsink** [emqx/emqx#9052]
### What would you like to be added or enhanced?

Since [this commit](https://github.com/emqx/emqx/commit/b2b83866853993475d8db2a1a512197be4c23fc3) the ability to provide the Helm chart with custom ACL rules using a configuration file has been removed. Is it possible to get this feature back?

### Why is this needed?

This makes automatic deployment for a few ACL rules more simple.

**Comment by wivwiv** [comment]
In fact `acl.conf`  just like any other authz data source:

```
# etc/emqx.conf
# EMQX 5.0.x


authorization {
  deny_action = ignore
  no_match = allow
  sources =  [
    {
      type = file
      enable = true
      # This file is immutable to EMQX.
      # Once new rules are created from dashboard UI or HTTP API,
      # the file 'data/authz/acl.conf' is used instead of this one
      path = "etc/acl.conf"
    }
  ]
}

```

**Comment by idelsink** [comment]
@wivwiv but the Helm chart does not have a way to add additional volume mounts so we can mount the ACL rules in this file. See here: https://github.com/emqx/emqx/blob/master/deploy/charts/emqx/templates/StatefulSet.yaml#L127

Most charts have an `extraVolumeMounts` option, for example https://github.com/kubernetes/ingress-nginx/blob/main/charts/ingress-nginx/values.yaml#L513

**Comment by idelsink** [comment]
This feature is now available and working as expected :tada:
