### ISSUE TITLE
Actual documentation - Actual Logs 

### ISSUE THREAD

**Issue by SovnSkyrim** [emqx/emqx#9054]
### What would you like to be added or enhanced?

The documentation; especially for clusters; says nothing.
Example:
Autocluster based on DNS A records

Automatically discover and create clusters based on DNS A records:

cluster.discovery = dns
cluster.dns.name = localhost
cluster.dns.app  = ekka

This says nothing; what is name or app? And what are possible errors? Because right now I have a DNS Server running; and all I have is "2022-09-26T14:14:54.008188+00:00 [warning] Ekka(AutoCluster): discovery did not succeed; retrying in 5000 ms"
No idea if the issue is from my DNS server; no idea if its pinging the wrong domain; no idea if the config file is the issue... Nothing.

I'm also unsure why the docker documentation doesn't provide a few docker-compose to just test stuff around. Some Sysadmin solutions provide a whole VM so why is it so scarce for EMQX? 

### Why is this needed?

You're a leader in a field; yet you don't have in depth documentation and explanations; and the only good one is [outdated of about 3 years](https://github.com/emqx/emqx-tutorial/tree/master/en/cluster)

**Comment by SovnSkyrim** [comment]
I find it abysmal how [the page for the configuration file](https://www.emqx.io/docs/en/v5.0/admin/cfg.html#layered) does not say where said config file is. 
How is Docker the first thing you see when clicking on [Downloads](https://i.imgur.com/RE3B3Dh.jpg) yet there are no example docker-compose for this kind of setup; no videos explaining anything. The clustering which is the seller point number 1 with the number of contiguous calls (which are technically not handled by the application itself but by the third party load balancer which in itself feels super wrong) isn't even documented correctly as none of [the example objects](https://www.emqx.io/docs/en/v5.0/deploy/cluster/auto.html#node-discovery-and-autocluster) are able to be used in Docker or the configuration file.

There are non professional softwares with so much better documentation as to how to install and configure it; it's extremely sad to witness this.

**Comment by SovnSkyrim** [comment]
By the way; the [docker compose example file in the documentation](https://www.emqx.io/docs/en/v5.0/deploy/install.html#running-emqx-in-docker) will not work whatsoever.

You have 2 instances of EMQX that needs one another to start due to the seeds; resulting in neither initializing and throwing errors constantly. You would need to remove the seeds on emqx1; and make the second ely on the first with only the first one as seed; need both.

**Comment by lafirest** [comment]
@SovnSkyrim 
Sincerely thank you for your input, to be honest, how to build and maintain a good document is a challenge for us, but we will continue to improve it

**Comment by SovnSkyrim** [comment]
Start by describing what things are; 
example:
`cluster {
    discovery_strategy = etcd
    etcd {
        server = "http://127.0.0.1:2379"
        prefix = emqcl
        node_ttl = 1m
    }
}
`
what the fuck is prefix/node_ttl? Whats their naming conventions? Whats their purpose? 
Each page should have maximal info; not minimal, not everyone is a 10years of experience system administration engineer; I'm a fucking intern and I don't understand half of those variables, showing the cruel lack of explanation.

Examples shouldn't have emqx in their name; why? Because how do I know if it's mandatory for the program to recognize the input/output.
- "EMQX_CLUSTER__DNS__NAME=cluster.emqx-cluster.org"

Do I need emqx-cluster for emqx to recognize it? I dont know; and trying with and without doesn't fix the "cant connect" warning I get; so I still don't know.

Actual log files would be wonderful; there is no --verbose or --debug in the configuration file! Why? 
"2022-09-26T14:14:54.008188+00:00 [warning] Ekka(AutoCluster): discovery did not succeed; retrying in 5000 ms"
This error isn't telling me anything except "it does not work". I'd love to not rely on github issues and fix it by myself. 
"Server cannot be reached" would go immensely; or "port not open" or... something else.

Why are the only port described in the configuration files; the other for **OTHER PROJECTS**? All it's talking about is MySQL/MongoDB/PostgreSQL ports; not yours! THEIR DOCUMENTATION HAS IT. Talk about your own damn ports. It's not normal that I have to check "EMQX Security" to check what port is doing what. I don't care about securing something if it doesn't even work from the get go you know?

Explain how your program works.

The result of this is basically 3 days of me seeing different variants of this; just poking around in the config files trying random shit.

If you need examples; well I figured out [Grafana](https://grafana.com/docs/grafana/latest/setup-grafana/configure-grafana/) in a day just because they explain stuff; same for NGINX; because theres Docker-compose files to test. 

Neither of those are present making the learning curve & setup abysmally hard.

**Comment by SovnSkyrim** [comment]
If you just execute emqx on a machine; without "start" you get
`Usage: emqx {start|start_boot <file>|ertspath|foreground|stop|restart|reboot|pid|ping|console|console_clean|console_boot <file>|attach|remote_console|upgrade|downgrade|install|uninstall|versions|escript|rpc|rpcterms|eval|root_dir}`

What does it cost you to just put a little link to what those are; why do i have to guess what ertspath or console does; or start_boot??

I search the documentation; theres nothing; yeaye so all the time you spent making those is wasted because nobody uses them!
So cool!

**Comment by zmstone** [comment]
For the DNS discovery issue.
If you are using 5.0.
here is an example script for reference: https://github.com/emqx/emqx/blob/master/scripts/test-node-discovery-dns.sh

**Comment by zmstone** [comment]
> 

for 4.x it's more or less the same, network setup, but the configs are a bit different.
have to admit that a lot of the things are indeed not well documentd.

**Comment by SovnSkyrim** [comment]
Thank you; I'll try a few things. I've been alternating between etcd and dns as kubernetes is too much for my team; too complex and you cannot do mcast using docker containers; although I've manually installed EMQX/bind9/etcd on this VM now..
I am quite unsure what should be the output of the script you sent;
This appear:

./testdns.sh emqx/emqx:latest
9ddc473cb03911e54501448994e88b52ef9f7f3ab7d19012d90278d6786445d6
f19347c51bab6ae63929bce0dca3690defd8232245d9368d54aadd24f994f92d
e583cbb772b5af392a5f4544b4e4a410fa970f48fc90d838244d531ef9e7ad34
77076470e301cd677e3acddd98b27df0a08f68c3e62bde52f0a92d5644c8ba3a

And that's about it.

**Comment by SovnSkyrim** [comment]
The script provided does [not seem to create 2 instances of EMQX that are linked via DNS](https://i.imgur.com/Iqirxzu.jpg)

**Comment by zmstone** [comment]
> I search the documentation; theres this [page](https://www.emqx.io/docs/en/v5.0/admin/cli.html#the-ctl-commands); but despite using the V5.0 tag; it's completely outdated; as "emqx ctl status" does nothing! Yeaye! So all the time you spent making those is wasted because nobody uses them

I'm not sure what this "does nothing" accusation is about.
it prints out the running status of the node, and version information too.
it exits with `0` code so you konw the node is running, serves as a healthcheck for some users.
```
> ./_build/emqx/rel/emqx/bin/emqx ctl status
Node 'emqx@127.0.0.1' 5.0.8-gb2d69b85 is started
```

**Comment by zmstone** [comment]
> The script provided does [not seem to create 2 instances of EMQX that are linked via DNS](https://i.imgur.com/Iqirxzu.jpg) Although according to docker ps; they exist; and the dns provider too.

I see that you are trying to replicate the script for 4.3.18,
If you share your script, it would be much more helpful for me to start digging than a screenshot.

**Comment by zmstone** [comment]
Please try with this diff:
```
--- a/scripts/test-node-discovery-dns.sh
+++ b/scripts/test-node-discovery-dns.sh
@@ -66,10 +66,12 @@ start_emqx() {
         --ip "$IP" \
         --dns "$IP0" \
         -p "$DASHBOARD_PORT:18083" \
-        -e EMQX_LOG__CONSOLE_HANDLER__LEVEL=debug \
+        -e EMQX_NODE_NAME="emqx@${IP}" \
+        -e EMQX_LOG__LEVEL=debug \
         -e EMQX_NODE_COOKIE="$COOKIE" \
-        -e EMQX_cluster__discovery_strategy='dns' \
+        -e EMQX_cluster__discovery='dns' \
         -e EMQX_cluster__dns__name="$DOMAIN" \
+        -e EMQX_cluster__dns__app="emqx" \
         -e EMQX_cluster__dns__record_type="a" \
         "$IMAGE"
 }
```

**Comment by zmstone** [comment]
Made the script work for 4.x, see #9073

**Comment by zmstone** [comment]
created #9073 for DNS-based discovery logging refine.
@SovnSkyrim You are welcome to create more issues.
We'd appreciate the issues to be focused, and actionable.
If the scope is unclear, or if you have in general comments, you are welcome to create a discussion here https://github.com/emqx/emqx/discussions
