### ISSUE TITLE
Shared subscription strategy - sticky is not working on $SYS topic

### ISSUE THREAD

**Issue by IanChiu628** [emqx/emqx#9062]
### What happened?

Hi,

I run EMQX by docker. The dockerfile is:
```
FROM emqx/emqx:5.0.3

# Share subscriptions
ENV EMQX_BROKER__SHARED_SUBSCRIPTION_STRATEGY=sticky
```

And I use shared subscription on $SYS topic: `$share/pcs/$SYS/brokers/+/clients/+/connected`
However, it is not working as I expected. The `connected` message will be displayed on 2 MQTT clients randomly, not sticky on 1 MQTT client.

screenshot:
![image](https://user-images.githubusercontent.com/101156534/192496420-224ec4f0-7418-4bfc-a72f-2af6851f5bc8.png)
The left and middle MQTTx are the clients who subscribe to shared subscription. The right one is the client who will connect to EMQX.

### What did you expect to happen?

I expect that only one MQTT client will receive the `connected` message.

### How can we reproduce it (as minimally and precisely as possible)?

Run EMQX with this dockerfile:
```
FROM emqx/emqx:5.0.3

# Share subscriptions
ENV EMQX_BROKER__SHARED_SUBSCRIPTION_STRATEGY=sticky
```

Then start 3 MQTTx clients. 2 for shared subscription, 1 for the client who will connect to EMQX broker.
The topic shoule be used here is `$share/pcs/$SYS/brokers/+/clients/+/connected`

For example:
![image](https://user-images.githubusercontent.com/101156534/192496420-224ec4f0-7418-4bfc-a72f-2af6851f5bc8.png)
The left and middle MQTTx are the clients who subscribe to shared subscription. The right one is the client who will connect to EMQX.

### EMQX version

<details>

```console
$ ./bin/emqx_ctl broker
# paste output here
sysdescr  : EMQX
version   : 5.0.3
datetime  : 2022-09-27T10:12:25.630799155+00:00
uptime    : 1 hours, 8 minutes, 32 seconds
```

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
BuildNumber  Caption                   OSArchitecture  Version
19044        Microsoft Windows 10 Pro  64-bit          10.0.19044
```

</details>

### Log files

<details>

</details>

**Comment by JimMoen** [comment]
Thanks for feedback, we will start investigating this issue.

**Comment by lafirest** [comment]
@IanChiu628 
After JimMoen investigates, we determined that this is a bug, I will fix it in a future version

**Comment by IanChiu628** [comment]
Hi @JimMoen and @lafirest, 
Thank you for looking into it!

**Comment by zmstone** [comment]
Hi Sorry for the late.

Thank you for the clarification in the documetns @lafirest .

@IanChiu628 
Stickiness' life-cycle is bound to the connection's.
meaning, if the connection restarts, the stickiness is lost.

You can maybe try to use `topic_hash` strategy  ?

**Comment by IanChiu628** [comment]
@zmstone 

Thanks for the reply. May I ask another question to get more clear on this?
Do you mean that `sticky` strategy sticks for connection(clientId) instead of topic name?

For example,
Subscriber 1 and Subscriber 2 subscribe to topic `my/topic`. 
Publisher A and Publisher B publish message to topic `my/topic`. 
EMQX may let Subscriber 1 handle Publisher A, and Subscriber 2 handle Pulisher B. Is it correct?

I used to think that only Subscriber 1 will receive the message from Publisher A and B because they use the same topic.

**Comment by lafirest** [comment]
> 

@IanChiu628 
Yes, but not all are right. It just sticks for the connection, not the clientid, each connection will pick a subscriber to stick when the first time to deliver a message.
