### ISSUE TITLE
While connecting to emqx error 245 is returned for some clients

### ISSUE THREAD

**Issue by vignesh-futurehook** [emqx/emqx#9074]
### What happened?

 [error] crasher:
    initial call: emqx_channel:init/1
    pid: <0.12534.0>
    registered_name: []
    exception error: no match of right hand side value {error,closed}
      in function  emqx_channel:init/1 (/tmp/emqx/v3.2.0/_checkouts/emqx/src/emqx_channel.erl, line 151)
    ancestors: [<0.1623.0>,<0.1622.0>,esockd_sup,<0.1354.0>]
    message_queue_len: 0
    messages: []
    links: [<0.1623.0>]
    dictionary: []
    trap_exit: false
    status: running
    heap_size: 4185
    stack_size: 27
    reductions: 5811
  neighbours:
2022-09-29 06:58:45.817 [error] supervisor: 'esockd_connection_sup - <0.1623.0>'
    errorContext: connection_crashed
    reason: {{badmatch,{error,closed}},
             [{emqx_channel,init,1,
                            [{file,"/tmp/emqx/v3.2.0/_checkouts/emqx/src/emqx_channel.erl"},
                             {line,151}]},
              {proc_lib,init_p_do_apply,3,
                        [{file,"proc_lib.erl"},{line,249}]}]}
    offender: [{pid,<0.12534.0>},
               {name,connection},
               {mfargs,{emqx_channel,start_link,
                                     [[{deflate_options,[]},
                                       {max_conn_rate,500},
                                       {active_n,100},
                                       {zone,external}]]}}]

### What did you expect to happen?

why this is not connecting?

### EMQX version

<details>

```console
$ ./bin/emqx_ctl broker
# paste output here
```

</details>
EMQX VERSION - V3.2.0

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>
Ubuntu 16.04

### Log files

<details>

</details>

**Comment by lafirest** [comment]
@vignesh-futurehook 
Hello, versions before 4.2 (including) are no longer maintained, maybe you can upgrade your system

**Comment by vignesh-futurehook** [comment]
But i tried with latest version

**Comment by id** [comment]
@vignesh-futurehook could you post error and logs from the latest version?
