### ISSUE TITLE
ekka dns discovery logging refine

### ISSUE THREAD

**Issue by zmstone** [emqx/emqx#9075]
### What happened?

This is (one of) the follow up issue(s) for: https://github.com/emqx/emqx/issues/9054
(as the original issue is quite a long thread and lack of focus)

Dns discovery failure log should hint the underlying problems.
* Which DNS domain did it try to resolve (to find the nodes' IPs)
* What was the DNS resolution result

### What did you expect to happen?

logs with actionable information

### Anything else we need to know?

The DNS resolution API provided by Eralng/OTP is too 'robust',
it mostly do not fail (no error return), but return an empty list.

empty list might happen due to
* There is no such resolvable domain
* There is a timeout during DNS resolution
* DNS propagation delay (if the record was added shortly before but not replicated yet)

The least we can do is to log which domain it was used in the resolution,
and fact that the resolution returned an empty list.

### EMQX version

4.x and 5.0

**Comment by SovnSkyrim** [comment]
The following [instructions](https://github.com/emqx/emqx-tutorial/blob/master/en/cluster/dns.md) were followed but I was not able to link the nodes in such a way.

**Comment by zmstone** [comment]
I made this script to work with 4.3.18,
https://github.com/emqx/emqx/blob/master/scripts/test-node-discovery-dns.sh
Did you have a chance to try it out? Did it work for you?
Reason to ask is to narrow down the investigation scope.

**Comment by id** [comment]
@SovnSkyrim try to use this docker image reference `emqx/emqx:latest`
