### ISSUE TITLE
%c not functioning properly in ACL file

### ISSUE THREAD

**Issue by GunnarMorrigan** [emqx/emqx#9093]
### What happened?

When the ACL contains the following lines:
```

{allow, {clientid, "A"}, all, ["%c"]}.
{allow, all, all, ["%c"]}.
... (the other default things here)
{deny, all}.
```

A client with client id of 'A' is not allowed to subscribe to topic A.

`2022-10-04T12:06:38.698390+00:00 [warning] clientid: A, ipaddr: {IP}, line: 356, mfa: emqx_authz:authorize_non_superuser/5, msg: authorization_permission_denied, peername: IP, source: file, topic: A, username: undefined`

### What did you expect to happen?

All clients allowed to subscribe and publish to their own clientids topic.

### How can we reproduce it (as minimally and precisely as possible)?

Set ACL to that provided, connect on 1883 with the broker with client id X and subscribe to topic 'X'.

### EMQX version

<details>

```console
$ ./bin/emqx_ctl broker
sysdescr  : EMQX
version   : 5.0.8
datetime  : 2022-10-04T12:09:35.345484105+00:00
uptime    : 3 minutes, 15 seconds
```

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release

NAME="Red Hat Enterprise Linux"
VERSION="8.6 (Ootpa)"
ID="rhel"
ID_LIKE="fedora"
VERSION_ID="8.6"
PLATFORM_ID="platform:el8"
PRETTY_NAME="Red Hat Enterprise Linux 8.6 (Ootpa)"
ANSI_COLOR="0;31"

$ uname -a
Linux ...... 4.18.0-372.26.1.el8_6.x86_64 #1 SMP Sat Aug 27 02:44:20 EDT 2022 x86_64 x86_64 x86_64 GNU/Linux
```

</details>

### Log files

<details>

</details>

**Comment by zmstone** [comment]
Hi @GunnarPieter 
In version 5, the place holder is different than version 4, for clientid, it's `${clientid}` but not `%c`.

**Comment by GunnarPieter** [comment]
> Hi @GunnarPieter 
> 
> In version 5, the place holder is different than version 4, for clientid, it's `${clientid}` but not `%c`.

Ahh oke thanks :). The file itself also still had `%c` examples.
