### ISSUE TITLE
Subscribe with the same client id simultaneously

### ISSUE THREAD

**Issue by ig0r** [emqx/emqx#910]
Hi guys,

Is there any option that allows to subscribe different clients with the same client id simultaneously?

I've tried `mqtt.pubsub.by_clientid` but haven't noticed any difference - clients with the same client id just kick off each other.

I'd like to have several clients subscribed to a topic but have just a single client that receives a message from this. If that client crashes, one of other clients can start receiving messages. So, it'd be possible to do HA for mqtt clients but only one should working, not in parallel (sending to the 3rd party, or a database).

It works on VerneMQ - they have a specific settings for that.

I see several options but don't see any documentation on that: one I mentioned above `mqtt.pubsub.by_clientid` and `mqtt.pubsub.async`. Maybe combination of those two could help me to achieve what I want?

Thanks!

**Comment by emqplus** [comment]
@ig0r EMQ does not support duplicated client id. You can create shared subscriptions with different client ids to implement HA.

**Comment by ig0r** [comment]
@emqplus thanks! I will check it
