### ISSUE TITLE
Build problem: can't find include lib "mnesia/src/mnesia.hrl"

### ISSUE THREAD

**Issue by dezdeepblue** [emqx/emqx#9100]
### What happened?

When building EMQX from source, on Tinker Board, these problem occurs:
```
export` BUILD_WITHOUT_QUIC=1  EMQX_BUILD_WITHOUT_QUIC=1
make 
....
===> Compiling gpb
===> Compiling ranch
===> Compiling cowboy
===> Compiling grpc
===> Compiling mysql
===> Compiling jose
===> Compiling epgsql
===> Compiling jsx
===> Compiling snabbkaffe
===> Compiling replayq
===> Compiling sext
===> Compiling rocksdb
===> Compiling mnesia_rocksdb
===> Compiling gen_rpc
===> Compiling mria
===> Compiling _build/default/lib/mria/src/mria_activity.erl failed
mria_activity.erl:{22,14}: can't find include lib "mnesia/src/mnesia.hrl"

mria_activity.erl:70:12: record tidstore undefined
mria_activity.erl:71:20: variable 'Ets' is unbound

make: *** [Makefile:123: emqx] Error 1

```

### What did you expect to happen?

EMQX Installed 

### How can we reproduce it (as minimally and precisely as possible)?

I'm on the latest Armbian (22.08). 
The processor is RK3288-C, Arm32v7.
Erlang/OTP 24 [erts-12.2.1] [source] [smp:4:4] [ds:4:4:10] [async-threads:1]
I pulled the source from GitHub and followed the instruction

### EMQX version

<details>

```console
$ ./bin/emqx_ctl broker
# paste output here
```
N/A
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
PRETTY_NAME="Armbian 22.08.2 Jammy"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.1 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy


$ uname -a
# paste output here
Linux tinkerboard 5.15.69-rockchip #22.08.2 SMP PREEMPT Wed Sep 21 19:18:41 UTC 2022 armv7l armv7l armv7l GNU/Linux

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Log files

<details>
N/A
</details>

**Comment by ieQu1** [comment]
I see, thanks. It looks like the packaged version doesn't include this header file, which is internal to Mnesia.
We usually use OTP built from source: https://github.com/emqx/otp (See the build instruction here: https://www.erlang.org/doc/installation_guide/install)
Can you try this approach?

**Comment by ieQu1** [comment]
You may also use `BUILD_WITHOUT_ROCKSDB` flag when building EMQX.

**Comment by dezdeepblue** [comment]
> 

The OTP builds with error which is related to this [bug](https://bugs.gentoo.org/805176)
I couldn't find a way to resolv it.

**Comment by dezdeepblue** [comment]
> You may also use `BUILD_WITHOUT_ROCKSDB` flag when building EMQX.

I tried this with previously installed erlang, still builds with the same error

**Comment by ieQu1** [comment]
Sorry for late reply. Which OTP tag have you tried to build? I think currently we're building emqx 5.0 from `emqx-OTP-24.3.4` tag in the https://github.com/emqx/otp repo.
