### ISSUE TITLE
/api/v3/nodes/emqx@127.0.0.1/connections error

### ISSUE THREAD

**Issue by ZZZhsb** [emqx/emqx#9116]
### What happened?

hi, when i send http request will have error.
error log:
GET /api/v3/nodes/emqx@127.0.0.1/connections error: {badmap,[]}, stacktrace:
[{maps,merge,[[],#{}],[]},
 {emqx_mgmt_api_connections,format,1,
                            [{file,"/emqx_temp/emqx_rel/_checkouts/emqx_management/src/emqx_mgmt_api_connections.erl"},
                             {line,114}]},
 {emqx_mgmt_api,'-paginate/3-lc$^0/1-0-',2,
                [{file,"/emqx_temp/emqx_rel/_checkouts/emqx_management/src/emqx_mgmt_api.erl"},
                 {line,34}]},
 {emqx_mgmt_api,'-paginate/3-lc$^0/1-0-',2,
                [{file,"/emqx_temp/emqx_rel/_checkouts/emqx_management/src/emqx_mgmt_api.erl"},
                 {line,34}]},
 {emqx_mgmt_api,paginate,3,
                [{file,"/emqx_temp/emqx_rel/_checkouts/emqx_management/src/emqx_mgmt_api.erl"},
                 {line,34}]},
 {emqx_mgmt_api_connections,list,2,
                            [{file,"/emqx_temp/emqx_rel/_checkouts/emqx_management/src/emqx_mgmt_api_connections.erl"},
                             {line,85}]},
 {minirest_handler,dispatch,2,
                   [{file,"/emqx_temp/emqx_rel/_checkouts/minirest/src/minirest_handler.erl"},
                    {line,84}]},
 {minirest,handle_request,2,
           [{file,"/emqx_temp/emqx_rel/_checkouts/minirest/src/minirest.erl"},
            {line,94}]}]
-----------------------------------------------------------------------------------------------
And this will happend by chance, not always

### What did you expect to happen?

return right response

### EMQX version

emqx:3.2.7

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Log files

GET /api/v3/nodes/emqx@127.0.0.1/connections error: {badmap,[]}, stacktrace:
[{maps,merge,[[],#{}],[]},
 {emqx_mgmt_api_connections,format,1,
                            [{file,"/emqx_temp/emqx_rel/_checkouts/emqx_management/src/emqx_mgmt_api_connections.erl"},
                             {line,114}]},
 {emqx_mgmt_api,'-paginate/3-lc$^0/1-0-',2,
                [{file,"/emqx_temp/emqx_rel/_checkouts/emqx_management/src/emqx_mgmt_api.erl"},
                 {line,34}]},
 {emqx_mgmt_api,'-paginate/3-lc$^0/1-0-',2,
                [{file,"/emqx_temp/emqx_rel/_checkouts/emqx_management/src/emqx_mgmt_api.erl"},
                 {line,34}]},
 {emqx_mgmt_api,paginate,3,
                [{file,"/emqx_temp/emqx_rel/_checkouts/emqx_management/src/emqx_mgmt_api.erl"},
                 {line,34}]},
 {emqx_mgmt_api_connections,list,2,
                            [{file,"/emqx_temp/emqx_rel/_checkouts/emqx_management/src/emqx_mgmt_api_connections.erl"},
                             {line,85}]},
 {minirest_handler,dispatch,2,
                   [{file,"/emqx_temp/emqx_rel/_checkouts/minirest/src/minirest_handler.erl"},
                    {line,84}]},
 {minirest,handle_request,2,
           [{file,"/emqx_temp/emqx_rel/_checkouts/minirest/src/minirest.erl"},
            {line,94}]}]

**Comment by lafirest** [comment]
@ZZZhsb 
Hi, versions before 4.2 (including) are no longer maintained, maybe you can upgrade your EMQX

**Comment by ZZZhsb** [comment]
> @ZZZhsb Hi, versions before 4.2 (including) are no longer maintained, maybe you can upgrade your EMQX

ok，thank you
