### ISSUE TITLE
Please improve the official documentation

### ISSUE THREAD

**Issue by 13116176539** [emqx/emqx#9117]
### What would you like to be added or enhanced?

![image](https://user-images.githubusercontent.com/35992963/194700206-9fb3779c-a615-4695-9706-fb98ac4e788e.png)

![image](https://user-images.githubusercontent.com/35992963/194700187-aae37f46-88e2-46eb-baa4-c4440b074910.png)

点开是502
The marked links are broken

### Why is this needed?

需要看

**Comment by HJianBo** [comment]
感觉反馈，已经修复在https://github.com/emqx/emqx-docs/pull/1406

Thanks for your feedback. I have fixed it at https://github.com/emqx/emqx-docs/pull/1406
