### ISSUE TITLE
Limiting concurrent connections per user?

### ISSUE THREAD

**Issue by drejkus** [emqx/emqx#913]
Hello,
is it possble to limit concurrent connections from a single user (single username)?
Or maybe is it possible to set publish rate limit per user?

I'm thinking that a plugin with DB checking/writing probably might do that, but maybe there is a more efficient way...

And thank you for your great work!

**Comment by emqplus** [comment]
@drejkus I like this feature too and add it to the 2.2 release plan.

**Comment by youngvery** [comment]
这个功能最后的配置在哪里可以配置呢？默认下载的版本是不是都配置为不限制？

**Comment by kidswong999** [comment]
Hello, how is this feature going?

**Comment by terry-xiaoyu** [comment]
Planned in EMQ 3.0. Which will probably be released in few months.

**Comment by rohan061** [comment]
Hi is there any update on this feature?

**Comment by Gilbert-Wong** [comment]
Sorry, @rohan061  we have no schedule to implement this feature. Maybe you could implemented it in your  own business logic.
