### ISSUE TITLE
Password comes over in plain text through http Auth/ACL Is that normal or is there a way to stop that and obfuscate it based on a key or other mechanism

### ISSUE THREAD

**Issue by xtianus79** [emqx/emqx#9146]
### What happened?

Here is the return I have coming through the http service that is a POST request. 

``` javascript
 log req body  {
2022-10-12T17:29:51Z   [Information]     clientid: 'smithfamily:1234598',
2022-10-12T17:29:51Z   [Information]     username: 'test',
2022-10-12T17:29:51Z   [Information]     password: 'patient'
2022-10-12T17:29:51Z   [Information]   }
```

This is post and the [documentation ](https://docs.emqx.com/en/enterprise/v4.4/modules/http_authentication.html#authentication-request)says this. 

> DANGER
It is recommended to use the POST and PUT methods. When using the GET method, the plaintext password may be recorded in the server log during the transmission along with the URL.

### What did you expect to happen?

Ideally I would not want that to be in clear plain text. Is this the way this would come and is it an issue. Perhaps I am thinking of this wrong. 

### How can we reproduce it (as minimally and precisely as possible)?

Start an emqx service and you will see the password come through plain text. 

### EMQX version

<details>

```console
ee-4.4.8
```

</details>

### OS version

<details>

```console
# On Linux:
Kubernetes Linux

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Log files

<details>

</details>

**Comment by HJianBo** [comment]
We've had some plans to improve security recently. The problem mentioned in this issue is one of them.

If there are any updates, we will reply here.

Thanks for your report here :+1:

**Comment by lafirest** [comment]
@xtianus79 
Thanks for your input, this issue is planned
