### ISSUE TITLE
When terminating the mTLS to the load balancer can you still observe the client certificate. Perhaps on the load balancer observation?

### ISSUE THREAD

**Issue by xtianus79** [emqx/emqx#9147]
### What would you like to be added or enhanced?

So it is well documented that TLS termination is much better for performance and such that I have created the TLS termination in my AKS cluster. 

The thing is, you can't do anything with the certificate because it wont' be there at the server/broker. 

Not really a feature or bug but what is the suggestion to handle this. Is only username and password an option at that point? 

### Why is this needed?

broker / device security.

**Comment by HJianBo** [comment]
After a TLS termination, the broker only gets a part of the information about client's certificate. It is limited by [Proxy-Protocol-v2](https://www.haproxy.org/download/1.8/doc/proxy-protocol.txt).

that only defined the following fields we can used:
```
#define PP2_TYPE_ALPN           0x01
#define PP2_TYPE_AUTHORITY      0x02
#define PP2_TYPE_CRC32C         0x03
#define PP2_TYPE_NOOP           0x04
#define PP2_TYPE_UNIQUE_ID      0x05
#define PP2_TYPE_SSL            0x20
#define PP2_SUBTYPE_SSL_VERSION 0x21
#define PP2_SUBTYPE_SSL_CN      0x22
#define PP2_SUBTYPE_SSL_CIPHER  0x23
#define PP2_SUBTYPE_SSL_SIG_ALG 0x24
#define PP2_SUBTYPE_SSL_KEY_ALG 0x25
#define PP2_TYPE_NETNS          0x30
```

**However, in the current emqx implementation, only `PP2_SUBTYPE_SSL_CN` works properly in a TLS-terminated scenario,** e.g.
```
## Value: cn | dn | crt | pem | md5
listener.tcp.external.peer_cert_as_username = cn
```
or, use it in auth-http requests:
```
# etc/plugins/emqx_auth_http.conf
## Available Variables:
##  - %u: username
##  - %c: clientid
##  - %P: password
##  - %C: common name of client TLS cert
##  - %d: subject of client TLS cert
##  - ...
auth.http.auth_req.params = clientid=%c,username=%u,password=%P,cn=%C
```

I'm not quite sure whether a CN alone is enough, if there are other fields required, would you mind describing the usage scenario more clearly?

**Comment by id** [comment]
Proxy protocol does not support sending full client certificate when TLS is terminated by proxy (Load Balancer) https://www.haproxy.com/documentation/haproxy-configuration-manual/latest/#send-proxy-v2
