### ISSUE TITLE
No ack message lost after client reconnect.

### ISSUE THREAD

**Issue by keitsi** [emqx/emqx#9188]
### What happened?

Not ack message lost after client reconnect.

### What did you expect to happen?

Receive the not ack message after client reconnect as the message Qos is 2 and session still alive.

### How can we reproduce it (as minimally and precisely as possible)?

1. Connect to EMQX with setManualAcks(true) on java paho client.
2. Send a message to the subscribed topic, the message will repeat until messageArrivedComplete() called. 
3. Close the program and re-open, the not ack message never received again.

### Anything else we need to know?

We try this manual ack to ensure the message processed before ack. The purpose is to prevent messages lost when program exception crash or exit. 

### EMQX version

<details>

```console
$ ./bin/emqx_ctl broker
# sysdescr  : 

EMQ X Broker
version   : 4.4.9
uptime    : 10 days, 0 hours, 46 minutes, 51 seconds
datetime  : 2022-10-20 16:06:54
```

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
NAME="Alpine Linux"
ID=alpine
VERSION_ID=3.15.1
PRETTY_NAME="Alpine Linux v3.15"
HOME_URL="https://alpinelinux.org/"
BUG_REPORT_URL="https://bugs.alpinelinux.org/"

$ uname -a
Linux emqx01.com 3.10.0-514.el7.x86_64 #1 SMP Tue Nov 22 16:42:41 UTC 2016 x86_64 Linux

```

</details>

**Comment by tigercl** [comment]
@keitsi Hi. Sorry for not replying to you in time. 

EMQX's behavior in this regard should be time-tested, so I suggest you first use [EMQX's tracking function](https://www.emqx.io/docs/en/v4.4/getting-started/log.html#log-trace-2) to track your client, get detailed message sending and receiving logs, and then analyze the possible reasons.

If it is still difficult to obtain the truth, please provide us with your logs so that we can investigate with you.

**Comment by keitsi** [comment]
> @keitsi Hi. Sorry for not replying to you in time.
> 
> EMQX's behavior in this regard should be time-tested, so I suggest you first use [EMQX's tracking function](https://www.emqx.io/docs/en/v4.4/getting-started/log.html#log-trace-2) to track your client, get detailed message sending and receiving logs, and then analyze the possible reasons.
> 
> If it is still difficult to obtain the truth, please provide us with your logs so that we can investigate with you.

This may be due to the EMQX session being in memory. Once the broker restarts, it will lose all messages. Am I right?

**Comment by keitsi** [comment]
Sorry for not updating for so long, we have bypassed this manual ack solution. Will close this question, add more comments in case someone comes into the same issue.

It work only in Qos1 but not Qos2 if the subscriber restarted.
In Qos1: Broker will re-publish the message to subscriber if wait `PUBACK` timeout.
In Qos2: Broker will send `PUBREL` only,  if wait `PUBCOMP` timeout. The message stored in subscriber if message process failed, than Broker won't re-publish the message if the program restarted at this time(it re-publish message if `PUBREC` not received). That's why I can't get the no ack message after program restart and reconnect in Qos2 mode.


Following diagram show the different of Qos1 and Qos2.
![image](https://github.com/emqx/emqx/assets/488125/62cdd68a-b63b-4c7f-9b1e-1a1f9e78a900)

![image](https://github.com/emqx/emqx/assets/488125/5feb675f-3324-4af9-928b-a06e705386b5)

**Comment by keitsi** [comment]
> Sorry for not updating for so long, we have bypassed this manual ack solution. Will close this question, add more comments in case someone comes into the same issue.
> 
> It work only in Qos1 but not Qos2 if the subscriber restarted. In Qos1: Broker will re-publish the message to subscriber if wait `PUBACK` timeout. In Qos2: Broker will send `PUBREL` only, if wait `PUBCOMP` timeout. The message stored in subscriber if message process failed, than Broker won't re-publish the message if the program restarted at this time(it re-publish message if `PUBREC` not received). That's why I can't get the no ack message after program restart and reconnect in Qos2 mode.
> 
> Following diagram show the different of Qos1 and Qos2. ![image](https://private-user-images.githubusercontent.com/488125/248191761-62cdd68a-b63b-4c7f-9b1e-1a1f9e78a900.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcyMjM0ODYsIm5iZiI6MTcyNzIyMzE4NiwicGF0aCI6Ii80ODgxMjUvMjQ4MTkxNzYxLTYyY2RkNjhhLWI2M2ItNGM3Zi05YjFlLTFhMWY5ZTc4YTkwMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyNVQwMDEzMDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lZTk2OTExODU1YTg0OGEyZWNlMWM4OWM4NGNiY2IwMjVlMmEwODdhYTQ3NzIyZTM2MzNhMWQ3OWRkZjVkMzExJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.F7li_u_fnPwb4M_dCv877yLij4LuJMCb9HTNcflVJlU)
> 
> ![image](https://private-user-images.githubusercontent.com/488125/248187943-5feb675f-3324-4af9-928b-a06e705386b5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcyMjM0ODYsIm5iZiI6MTcyNzIyMzE4NiwicGF0aCI6Ii80ODgxMjUvMjQ4MTg3OTQzLTVmZWI2NzVmLTMzMjQtNGFmOS05MjhiLWEwNmU3MDUzODZiNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyNVQwMDEzMDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yMjE2NzY3OGJkYmVmNGVmNDAyZTdlOWJlN2JhZDkxZTc0NmVlOGQ4YTJiY2QyZmFmNWViMDQ1ZTMxNTQ3NjE1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.LRKzK0R71-IpS33Dr9UCJb-PpCSBEp7bA2ZMylR8vOk)

It proved to be a bug of paho mqtt client: https://github.com/eclipse/paho.mqtt.java/pull/995
Please try the hive mqtt client:  https://github.com/hivemq/hivemq-mqtt-client/tree/master
