### ISSUE TITLE
Import/Export settings

### ISSUE THREAD

**Issue by richard-scott** [emqx/emqx#9202]
### What would you like to be added or enhanced?

I like to have all my config settings in a text format somewhere in a file. So, when migrating from a Dev cluster to a Production cluster it would be great to have some way to export the current config in HOCON format that you could merge with the data in /etc/emqx/emqx.conf on your target cluster. 

### Why is this needed?

I can't find a way to use the CLI or API to export settings that can be saved into /etc/emqx/emqx.conf.

**Comment by tigercl** [comment]
@richard-scott Sorry for not replying to you in time. I see you mentioned that you want the export configuration to be in HOCON format, isn't the EMQX you use in the Dev cluster 5.0?

**Comment by richard-scott** [comment]
@tigercl yes, my dev cluster is v5.0.

**Comment by tigercl** [comment]
@richard-scott Hi. If you modify the configuration through Dashboard, then these configuration items will be saved in `cluster-override.conf`. If you directly modify `emqx.conf`, then obviously these configurations are in `emqx.conf`, you can directly copy these configuration files to the target machine for use.

But if you need to merge with the original configuration of the target machine, we are sorry that we have not provided this capability yet.

**Comment by richard-scott** [comment]
ok, thanks for the info.
