### ISSUE TITLE
FR: not closing but ignoring after proxy protocol timeout

### ISSUE THREAD

**Issue by daadu** [emqx/emqx#9205]
### What would you like to be added or enhanced?

I would like to congratulate the EMQX team for the excellent products you guys have built.

I was going through EMQX docs about proxy-protocol, and noticed `proxy_protocol_timeout` which will terminate TCP connection after this timeout.

Now for my use-case (and I am sure these will the same for many) - our cloud applications connect to the broker "internally" (without any LB) as well, in that case, I am afraid (have not confirmed this behaviour, but assuming based on docs) the connection will not be accepted. 

I suggest we can add another config (something like `proxy_protocol_timeout_action`) to decide what to do when timeout happens - close TCP, ignore, etc.

### Why is this needed?

To allow both types of connection LB proxied - for IoT devices and directly connected for internal applications.

**Comment by daadu** [comment]
Any update?

**Comment by ieQu1** [comment]
There is a better solution: it's possible to create two separate MQTT listeners for internal and external clients. For example, port 1883 can be dedicated to internal clients that connect directly without proxy protocol, and LB can connect to a listener on a port.
"Proxy protocol fallback" is not something that we are going to support.
