### ISSUE TITLE
MongoDB 6.0+ replicaset will not connect through the rules engine. It keeps giving an Authentication failure. 

### ISSUE THREAD

**Issue by xtianus79** [emqx/emqx#9227]
### What happened?

This is output from the attempt

```
"Authentication failed","attr":{"mechanism":"SCRAM-SHA-1","speculative":false,"principalName":"<my_user>","authenticationDatabase":"<my_database>","remote":"<redacted>:41076","extraInfo":{},"error":"AuthenticationFailed: SCRAM authentication failed, storedKey mismatch"}}
```

### What did you expect to happen?

This is a success when using mongo compass

```
"msg":"Authentication succeeded","attr":{"mechanism":"SCRAM-SHA-1","speculative":true,"principalName":"<my_user>","authenticationDatabase":"<my_database>","remote":"<redacted>:56601","extraInfo":{}}}

,"msg":"client metadata","attr":{"remote":"108.70.239.224:56599","client":"conn25328","doc":{"driver":{"name":"nodejs","version":"4.8.1"},"os":{"type":"Windows_NT","name":"win32","architecture":"x64","version":"10.0.22621"},"platform":"Node.js v16.5.0, LE (unified)|Node.js v16.5.0, LE (unified)","application":{"name":"mongosh 1.6.0"}}}}
```

### Anything else we need to know?

What's interesting is that I can get the root to connect but it's not associated to any data bases other than admin and that's not a writeable DB... 

```
"msg":"Authentication succeeded","attr":{"mechanism":"SCRAM-SHA-1","speculative":false,"principalName":"root","authenticationDatabase":"admin","remote":"<redacted>:37724","extraInfo":{}}}
```
And here it just disconnects right after

```
"msg":"Connection ended","attr":{"remote":"<redacted>:51560","uuid":"d","connectionId":26032,"connectionCount":19}}
{"t":{"$date":"2022-10-25T16:34:55.325+00:00"},"s":"I",  "c":"NETWORK",  "id":22944,   "ctx":"conn25969","msg":"Connection ended","attr":{"remote":"<redacted>:37726","uuid":"<redacted>","connectionId":25969,"connectionCount":18}}
{"t":{"$date":"2022-10-25T16:34:55.598+00:00"},"s":"I",  "c":"NETWORK",  "id":22944,   "ctx":"conn25971","msg":"Connection ended","attr":{"remote":"<redacted>:37732","uuid":"<redacted>","connectionId":25971,"connectionCount":17}}
{"t":{"$date":"2022-10-25T16:34:55.608+00:00"},"s":"I",  "c":"NETWORK",  "id":22944,   "ctx":"conn25968","msg":"Connection ended","attr":{"remote":"<redacted>:37724","uuid":"<redacted>","connectionId":25968,"connectionCount":16}}
{"t":{"$date":"2022-10-25T16:34:55.660+00:00"},"s":"I",  "c":"NETWORK",  "id":22944,   "ctx":"conn25975","msg":"Connection ended","attr":{"remote":"<redacted>:37738","uuid":"<redacted>","connectionId":25975,"connectionCount":15}}
{"t":{"$date":"2022-10-25T16:35:03.162+00:00"},"s":"I",  "c":"NETWORK",  "id":22943,   "ctx":"listener","msg":"Connection accepted","attr":{"remote":"<redacted>:53714","uuid":"<redacted>","connectionId":26033,"connectionCount":16}}
```

I don't know if it's the type of user. I can't figure out why compass works no problem but the Emqx connection won't

The client login and ip's work on the cli as well. So CLI works and Compass just not EMQX. 

### EMQX version

<details>

```console
[$ ./bin/emqx_ctl broker
# paste output here](emqx-ee:4.4.8)
```

</details>

### OS version

<details>

```console
# On Linux: Kubernetes AKS
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Log files

<details>

</details>

**Comment by lafirest** [comment]
@xtianus79 Hi,
If I remember correctly, now we only support MongoDB versions up to 4.8

**Comment by xtianus79** [comment]
@lafirest Oh wow. lol. Oh no. I mean, that's pretty far back. Would you update that to 6+? Is that something that would happen in the near future. This would really hamper my architecture plans. Is there anything else I could do in the mean-time?

**Comment by xtianus79** [comment]
Also, @lafirest I can fix it. Can you show me where the codebase is? meaning, I am assuming you would want a mongo legacy + mongo 6+ section. Perhaps that would be the easiest and quickest way. Shouldn't be too much of an update.

**Comment by lafirest** [comment]
@xtianus79 
Thanks, We already have a plan to update the mongo db driver

**Comment by xtianus79** [comment]
hi @lafirest has this been resolved?

**Comment by xtianus79** [comment]
@lafirest is there any update to this?

**Comment by lafirest** [comment]
> @lafirest is there any update to this?

@xtianus79 
Sorry for the late reply, it's in processing. I'm not sure when it will be released, but I think it will be soon.

**Comment by lafirest** [comment]
@xtianus79 
Hi, I think this issue will be fixed by this [PR](https://github.com/emqx/emqx/pull/9691)

**Comment by xtianus79** [comment]
this is great. Is this in the enterprise release? @lafirest

**Comment by xtianus79** [comment]
@lafirest will this be in the next release and do you know when that might be?

**Comment by lafirest** [comment]
@xtianus79 
This PR has already merged, you can have a try with a more recent version.

**Comment by xtianus79** [comment]
Hi, but I am using a controller via Kubernetes and I don't see any different version than the one that you have currently on the release list.

**Comment by xtianus79** [comment]
@lafirest is this update only going to be in starting with enterprise 5.0? It seems like a major upgrade and I want to prepare for the changes before I do that.

**Comment by lafirest** [comment]
@xtianus79 
Yes, the PR I mentioned just fixed the MongoDB driver. But what you want is the rule engine MongoDB backend, which is a feature of the enterprise version.

**Comment by xtianus79** [comment]
Hi @lafirest, understood. What I am trying to plan and figure out is if there will be a 4 version upgrade with this fix (which will make it easier for me) or do I have to upgrade to enterprise version 5?

Thanks.

**Comment by xtianus79** [comment]
This will be very welcome. Last question. When will this come out?

**Comment by id** [comment]
@xtianus79 [v4.4.15](https://github.com/emqx/emqx/releases/tag/v4.4.15) has been released on March 3rd.
You can check out what is the latest enterprise version [here](https://www.emqx.com/en/try?product=enterprise).

**Comment by xtianus79** [comment]
@id Thanks. I will be implementing now. I will let you know how it goes.

**Comment by xtianus79** [comment]
@id and @lafirest  I am happy to say... Boom mission accomplished! Thanks everyone. One little bug about the payload using the `${var}` principal isolated at the `payload` variable. It doesn't work but I will post that in another issue.
