### ISSUE TITLE
How to hook message.publish to specific topic

### ISSUE THREAD

**Issue by tkaarrela** [emqx/emqx#927]
Is there a way for a plugin to hook to specific topic's message.publish events?

I have couple of plugins, one which should handle messages on topic devices/clientid/A and another plugin that should handle messages on topic devices/clientid/B.

Currently both plugins handles all messages so I have if statements inside plugin where I pick messages to handle based on information if topic contains A or B in part of the topic name. 

It would be better if I could get rid of if statement and plugin would hook to listen messages published to related topic.

**Comment by phanimahesh** [comment]
As far as I know, no. Not currently.

The "if statement" as you call it would then move into emqttd. It will however remain. You can get rid of if in favor of pattern matching, (if clientid is of a known and fixed length).

It is however an interesting proposal. Matching on topics or topic patterns is common, and hooking only into a few topics also feels like a common use case. What are your thoughts, @emqplus? If you think it would add value, I can take this up for inclusion directly in emqttd or as a plugin wrapper providing a more convenient api with topic (or topic pattern) specific hooks

**Comment by emqplus** [comment]
@phanimahesh, I agree that we should enhance the emqttd_hooks APIs to support this feature.

**Comment by turtleDeng** [comment]
@tkaarrela 
emqx:hook(HookName, {Topic, Function}, [Params]).

```
emqx:hook('message.publish', {<<"test1">>,fun mod:fun/2}, [Params]).
emqx:hook('message.publish', {<<"test2">>,fun mod:fun/2}, [Params]).
```
