### ISSUE TITLE
EMQX 5.0.9 not available on packagecloud

### ISSUE THREAD

**Issue by FredericMa** [emqx/emqx#9315]
### What happened?

I tried to update from 5.0.8 to 5.0.9 via apt but it didn't work.

### What did you expect to happen?

I expected EMQX to be updated to version 5.0.9.

### How can we reproduce it (as minimally and precisely as possible)?

Use install script, which will install 5.0.8. Trying to update via apt has no effect.

### EMQX version

<details>

```console
$ ./bin/emqx_ctl broker
sysdescr  : EMQX
version   : 5.0.8
datetime  : 2022-11-06T21:54:34.434565596+00:00
uptime    : 37 minutes, 30 seconds
```

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
$ uname -a
Linux mqtt 5.15.60-2-pve #1 SMP PVE 5.15.60-2 (Tue, 04 Oct 2022 16:52:28 +0200) x86_64 GNU/Linux



### Log files

<details>

</details>

**Comment by tigercl** [comment]
@FredericMa Hi. Thank you very much for your feedback, we have fixed this issue.

Please use the `sudo apt-get update` command to update the package list and try to install it again.
