### ISSUE TITLE
PKCS 12 / PFX SSL Cert support

### ISSUE THREAD

**Issue by vidhill** [emqx/emqx#933]
#### Environment

- OS: Ubuntu 16.04
- Erlang/OTP: 
- EMQ: v2.0.7

#### Description
Hello, 
our platform is using combined a file.p12 cert file
-instead of the regular separate .key and .pem files

Does emq support certs in this pfx format?

It's not working for me atm but that could be my self signed cert..

**Comment by turtleDeng** [comment]
@vidhill 
```
openssl pkcs12 -in file.p12 -out cert.pem -nodes
openssl rsa -in cert.pem -out key.pem
```

**Comment by vidhill** [comment]
Yes, we had a look at doing that, 
our .p12 file was/is injected at startup so it was kind of difficult to extract before emq starts, 

We got cert and key .pem files in the meantime
