### ISSUE TITLE
clients API too slow in emqx 5.0.8. 

### ISSUE THREAD

**Issue by siniusxcode** [emqx/emqx#9341]
<img width="836" alt="스크린샷 2022-11-10 오후 5 35 19" src="https://user-images.githubusercontent.com/1418182/201042155-59fc7dc7-6d10-48e1-803a-6afd61d3b380.png">
<img width="857" alt="스크린샷 2022-11-10 오후 5 35 42" src="https://user-images.githubusercontent.com/1418182/201042168-6d9451e4-e2a2-4875-8d91-871b34e37868.png">
#### Environment

- OS: CentOS Linux release 7.5.1804 (Core) 
- Erlang/OTP: 22.2.6-1
- EMQ: 5.0.8

#### Description

I have two emqx clusters(4.0.7 and 5.0.8) of two vm servers(same spec: 12Cores, 16G) each.
Using another test server, I tried connecting 50,000 clients to cluster and calling clients API.

Result of response time for client API
5.0.8 : over 3s
4.0.7 : under 300ms

There is too much difference in response time between the two versions.
I want to use the 5.x version, but it is difficult to use because of this part.

**Comment by zhongwencool** [comment]
Thanks for reporting, We plan to fix this in the next version `5.0.10` 👍

**Comment by siniusxcode** [comment]
Thank you for your answer. By the way, I tested the same in version 5.0.10 now and the same problem still occurs. And I found some additional problems, I will register them as other issue.

**Comment by zhongwencool** [comment]
> Thank you for your answer. By the way, I tested the same in version 5.0.10 now and the same problem still occurs. And I found some additional problems, I will register them as other issue.

sorry for the wrong version. The next version is `5.0.11`
