### ISSUE TITLE
support for apple silicon macOS

### ISSUE THREAD

**Issue by chonwhite** [emqx/emqx#9343]
### What would you like to be added or enhanced?

Any plan to support the ARM version of macOS? https://www.emqx.io/downloads?os=macOS

### Why is this needed?

X86 version does not work on M1 & M2 macOS.

**Comment by tigercl** [comment]
@chonwhite Thanks for your feedback, we have done some preparations before this, I think we will provide installation packages for M1 & M2 in v4.4.12.

**Comment by chonwhite** [comment]
> @chonwhite Thanks for your feedback, we have done some preparations before this, I think we will provide installation packages for M1 & M2 in v4.4.12.

OK, cool; when will v4.4.12 be released?

**Comment by id** [comment]
arm64 binaries for MacOS are now available (since v5.0.12).

**Comment by id** [comment]
@chonwhite did you need that for v4.4.12?
