### ISSUE TITLE
stats API topics count is not correct in emqx 5.0.10

### ISSUE THREAD

**Issue by siniusxcode** [emqx/emqx#9349]
### What happened?

<img width="832" alt="스크린샷 2022-11-11 오후 1 30 44" src="https://user-images.githubusercontent.com/1418182/201264487-06f6e9c3-5ca1-4b92-a40e-565a505c6dd9.png">
<img width="805" alt="스크린샷 2022-11-11 오후 1 34 40" src="https://user-images.githubusercontent.com/1418182/201264513-31401a65-fc5e-4be4-9619-a6e2d5974411.png">

I have emqx 5.0.10 cluster of two vm servers.
Using another test server, I tried connecting and subscribing 60,000 clients to one node of cluster.
However, stats API seems to result in the topic count of the entire cluster.
And the dashboard doesn't seem to use the figures.

### What did you expect to happen?

I expected accurate topic count for each node to stats API.
And I wanted to check it on the dashboard.

### EMQX version

<details>

```console
$ ./bin/emqx_ctl broker

sysdescr  : EMQX
version   : 5.0.10
datetime  : 2022-11-11T13:51:16.810915030+09:00
uptime    : 1 hours, 40 minutes, 45 seconds
```

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Log files

<details>

</details>

**Comment by zhongwencool** [comment]
@ysfscream uses the wrong metrics`connection.count/max`, should be `topic.count/max`, Maybe we can plan to fix in the next version `5.0.11`

**Comment by ysfscream** [comment]
Hi, @siniusxcode Thanks for your feedback. This is a BUG in the Dashboard, currently fixed in the dev branch, look forward to the next version.

**Comment by siniusxcode** [comment]
@zhongwencool @ysfscream 
There is also a bug in stats API that does not provide topics.count per node. Please check.

**Comment by zhongwencool** [comment]
Not exactly, EMQX's topic is the same in each node. 
So we can subscribe one topic in NodeA, but send to this topic from another NodeB.

> @zhongwencool @ysfscream There is also a bug in stats API that does not provide topics.count per node. Please check.

**Comment by siniusxcode** [comment]
@zhongwencool 
Thank you for your answer. I was mistaken. It is correct that the topic is shared because it is a cluster structure.
