### ISSUE TITLE
Brokers in cluster does not share pending queued messages of persistent clients with each other. 

### ISSUE THREAD

**Issue by sanket-kulkarni-vmware** [emqx/emqx#936]
#### Environment

- OS: Ubuntu 16.04 LTS
- Erlang/OTP: 19
- EMQ:  2.0.4

Issue with EMQTT broker in HA setup: If one broker goes down then the queued messages of failed broker do not get transferred to the HA backup broker. 
I have a two broker setup in a clustered mode. 

Scenario Details: 
Step1: Consider one persistent client(clean session flag as False and client-id **test-client**) connected to the broker 1 and it has subscribed to the topic "**test/temp**". 
Step2: **test-client** gets disconnected from the broker same time broker 1 has received messages on topic **test/temp** from one of the connected clients.  
Step3: Broker-1 will hold the messages in the memory till **test-client** connects back to the broker 
Step4: Once it connects back broker-1 will pass all the pending messages which are there for **test-client**.  

In the above scenario, we see an issue if broker 1 crashes. In the case of a crash, the broker does not pass the pending messages to HA broker 2. As a result, the held messages are lost. 
In an HA setup, I would expect the held messages to be transferred to backup broker in case one of the broker crashes. Is there a way not to loose messages in a crash situation? 

Please let me know if above scenario is "works as expected" functionality or an issue that needs to be fixed.

**Comment by Gilbert-Wong** [comment]
Hi, @sanket-kulkarni-vmware , this issue has been resolved in emqx3.0.0 release. Hope the latest release of emqx could help you.
