### ISSUE TITLE
internals container allow anonymous

### ISSUE THREAD

**Issue by hesamdarbandi** [emqx/emqx#9371]
### What happened?

I have configured JWKS and it would work great with clients, but the problem is Kafka connector source doesn't work due to Jews and error is Not authorized to connect,
I just wondering how can configure to allow anonymous inside docker container calls.

my development environment is docker compose, thank you in advance for help

### What did you expect to happen?

I've expected to have a config for anonymous call inside the container

### EMQX version

<details>

```console
$ ./bin/emqx_ctl broker
# paste output here
```
5.0.10
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Log files

<details>

</details>

**Comment by tigercl** [comment]
@hesamdarbandi Sorry, I didn't fully understand your question. JWKS is used for MQTT client authentication, and our connection authentication with Kafka is another matter. The two should not be related.

**Comment by hesamdarbandi** [comment]
Actually, The two are related and I've found a solution that can define a new listener with enable_authn = "false" on the docker configuration

thanks your team in advance
