### ISSUE TITLE
If the value of a binary config field can also be treated as an integer, EMQX will throw a type error

### ISSUE THREAD

**Issue by lafirest** [emqx/emqx#9400]
### What happened?

Set a value by the env variable for a binary config field, if the value can be converted to an integer(e.g. `123456`), EMQX will throw a type error

### What did you expect to happen?

If the type of a field is binary/string, maybe we can use what we got instead of converting it

### How can we reproduce it (as minimally and precisely as possible)?

export EMQX_SYSMON__TOP__DB_PASSWORD=123456
make run

### EMQX version

<details>

```console
$ ./bin/emqx_ctl broker
# paste output here
In fact, it does not start at all
```

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux bookworm/sid"
NAME="Debian GNU/Linux"
VERSION_CODENAME=bookworm
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
$ uname -a
Linux DESKTOP-LH9I5M8 5.10.16.3-microsoft-standard-WSL2 #1 SMP Fri Apr 2 22:23:49 UTC 2021 x86_64 GNU/Linux

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Log files

<details>
2022-11-21T22:48:51.858674+08:00 [error] failed_to_check_schema: emqx_conf_schema
2022-11-21T22:48:51.860889+08:00 [error] #{kind => validation_error,path => "sysmon.top.db_password",reason => #{expected_type => <<"binary()">>},value => 123456}
ERROR: call_hocon_failed: -v -t 2022.11.21.22.48.51 -s emqx_conf_schema -c /home/firest/labori/emqx/_build/emqx/rel/emqx/etc/emqx.conf -d /home/firest/labori/emqx/_build/emqx/rel/emqx/data/configs generate
make: *** [Makefile:209: quickrun] Error 1
</details>

**Comment by zmstone** [comment]
quote will help.
