### ISSUE TITLE
The EMQX connection by MQTTX through SSL/TLS which is successful but the dashboard listener can not watch the connnection.  

### ISSUE THREAD

**Issue by Biaoshi** [emqx/emqx#9414]
### What happened?

The EMQX connection by MQTTX through SSL/TLS which is successful but the dashboard listener can not watch the connnection.  
The SSL/TLS certificate is a Self signed certificate by openssl.

### What did you expect to happen?

The dashboard can watch the connection.

### How can we reproduce it (as minimally and precisely as possible)?

make a connection through SSL/TLS.
enter ca.pem client.pem client.key in mqttx.
when it connected, watching the dashboard listener page. 

### Anything else we need to know?

None.

### EMQX version

<details>

```console
$ ./bin/emqx_ctl broker
# paste output here
```
sysdescr  : EMQX
version   : 5.0.9
datetime  : 2022-11-24T09:01:14.477587385+08:00
uptime    : 35 minutes, 20 seconds

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release

NAME="Ubuntu"
VERSION="18.04.6 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.6 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic

$ uname -a
Linux mqtt-svr 5.4.0-131-generic #147~18.04.1-Ubuntu SMP Sat Oct 15 13:10:18 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Log files

<details>

</details>
[node_dump_20221124_092327.tar.gz](https://github.com/emqx/emqx/files/10080132/node_dump_20221124_092327.tar.gz)

**Comment by Biaoshi** [comment]
![dashboard](https://user-images.githubusercontent.com/31428174/203674274-d629cbde-60da-482a-86d9-691354ee61e3.png)
![mqttx](https://user-images.githubusercontent.com/31428174/203674277-04794abb-8c02-4819-85fc-58e1492b212d.png)

**Comment by tigercl** [comment]
@Biaoshi Hi. Can you see this client in the client list?

**Comment by Biaoshi** [comment]
@tigercl  Hi, when I just try,  I can not connected successful.

Error: Client network socket disconnected before secure TLS connection was established

**Comment by Biaoshi** [comment]
I know how to resolve the "Error: Client network socket disconnected before secure TLS connection was established".

And I found I filled in the wrong ip address this moring, now I can watch the connection in dashborad listener page.

Thank you for your help!

**Comment by tigercl** [comment]
@Biaoshi Hi. The `unknown_ca` appears in your log, which means that the certificate verification failed.

Common reasons include:
1. Missing the intermediate CA certificate
2. Not specifying the Root CA certificate
3. Specifying the wrong Root CA certificate.

Can you provide your TLS configuration on client and server?

**Comment by Biaoshi** [comment]
> @Biaoshi Hi. The appears in your log, which means that the certificate verification failed.`unknown_ca`
> 
> Common reasons include:
> 
> 1. Missing the intermediate CA certificate
> 2. Not specifying the Root CA certificate
> 3. Specifying the wrong Root CA certificate.
> 
> Can you provide your TLS configuration on client and server?

The attachment includes the client certificates and the server certificates.

[client and server.zip](https://github.com/emqx/emqx/files/10088120/client.and.server.zip)
