### ISSUE TITLE
[helm] Update emqx helm chart version in public chart repo

### ISSUE THREAD

**Issue by leoandrea7** [emqx/emqx#9424]
Hi,
in public charts [repository](https://repos.emqx.io/charts), the latest emqx chart version is 5.0.3 while in github is [5.0.10](https://github.com/emqx/emqx/blob/master/deploy/charts/emqx/Chart.yaml). It is possible to update this? Thanks.

**Comment by id** [comment]
@leoandrea7 should be fixed in v5.0.11 https://github.com/emqx/emqx/pull/9375

**Comment by leoandrea7** [comment]
Ok thanks!
