### ISSUE TITLE
Upgrade from 4.1.5 to 5.0.9: listener.ssl.external.handshake_timeout

### ISSUE THREAD

**Issue by jkominiakgps** [emqx/emqx#9459]
### What happened?

Trying to upgrade from `4.1.5` to `5.0.9` and I do not see a corresponding configuration for `listener.ssl.external.handshake_timeout`.  Looking up to `4.4`, this setting is present.  We had this value configured to be greater then the default of `15s`, but I do not see a corresponding configuration for this in `listeners.ssl.default` or `listeners.ssl.default.ssl_options`.  I have tried setting this as `listeners.ssl.default.ssl_options.handshake_timeout`, but am receiving a schema validation error: `#{kind => validation_error,path => "listeners.ssl.default.ssl_options",reason => unknown_fields,unknown => <<"handshake_timeout">>,unmatched => <<"client_renegotiation,depth...">>}`.  How should I configure this value in `5.X`?  

### What did you expect to happen?

I should be able to configure the `listener.ssl.external.handshake_timeout` like I was able to in `4.X`.  

We need this as we have devices that take longer then `15 seconds` to complete the handshake.

### EMQX version

<details>

```console
$ ./bin/emqx_ctl broker
4.1.5
```

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
20.04.5 LTS (Focal Fossa)
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Log files

<details>

</details>

**Comment by tigercl** [comment]
@jkominiakgps Hi. Thanks for your feedback, this is indeed a bug and we will fix it in the next version, which is 5.0.12. While `handshake_timeout` is currently not configurable, it will still run with the default value of `15s`.

**Comment by jkominiakgps** [comment]
@tigercl Thank you for the quick reply!  Out of curiosity do you have an estimated release date for `5.0.12`?

**Comment by zmstone** [comment]
> @tigercl Thank you for the quick reply! Out of curiosity do you have an estimated release date for `5.0.12`?

Dec.9
