### ISSUE TITLE
Message dropped by "Cannot publish message to xxxx due to Not authorized." occasionally

### ISSUE THREAD

**Issue by stayhungry001** [emqx/emqx#9473]
### What happened?

我使用EMQX对接MySQL进行用户认证和ACL授权。近期经常出现消息丢失的情况。 近期将Debug开启后发现， 经常会在[notice] Application: emqx_auth_mysql. Exited: stopped. Type: temporary 之后出现某一、两个客户端出现消息丢失，报错如题。

### What did you expect to happen?

消息能可靠传输，不出现偶现的消息丢失情况。 

### How can we reproduce it (as minimally and precisely as possible)?

这个问题感觉是当前版本必现。

### EMQX version

Broker版本 4.4.3，使用Operator方式部署，认证信息接入到MySQL进行认证。 

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Log files

<details>

</details>

**Comment by tigercl** [comment]
@stayhungry001 Hi, can you provide more logs?
