### ISSUE TITLE
broker.shared_dispatch_ack_enabled Not active

### ISSUE THREAD

**Issue by mijjjj** [emqx/emqx#9476]
### What happened?

After configuring Broker.shared_dispatch_ack_enabled = True, the shared subscription message of no group setting will still be set up with the client subscription of Cleansession = FALSE, which makes other online clients unable to receive messages.

### What did you expect to happen?

Only the online client receives the subscription message

### EMQX version

5.0.11

### OS version

BuildNumber  Caption                   OSArchitecture  Version
22621        Microsoft Windows 11 Pro  64-bit          10.0.22621

### Log files

<details>

</details>

**Comment by tigercl** [comment]
@mijjjj Hi, have you restarted EMQX after modifying the configuration?

**Comment by tigercl** [comment]
I have not been able to reproduce this issue, maybe you can provide more detailed steps.

**Comment by zmstone** [comment]
Hi @mijjjj 
I am not quite sure I understand the issue description.
Anyways, `shared_dispatch_ack_enabled ` is now deprecated.
The new behavior is: For one session which subscribed to a shared topic, when it expires, shared-messages delivered to this session will be re-dispatched to other group member sessions.
This effectively eliminates the need for the dispatch (it was developed to avid delivering messages to disconnected sessions).
