### ISSUE TITLE
Bad format error when I run emqx_ctl command

### ISSUE THREAD

**Issue by terry-xiaoyu** [emqx/emqx#9489]
### What happened?

There is some errors and warnings when I run the `emqx_ctl` command:

```console
$ ./bin/emqx_ctl broker
stat: %R: bad format
!!!!
!!!! WARNING: ulimit -n is 256; 1024 is the recommended minimum.
!!!!
sysdescr    :     EMQX
version       :     5.0.11-g16aeba24
datetime    :     2022-12-07T15:57:44.378470360+08:00
uptime       :     6 minutes, 43 seconds
```

### What did you expect to happen?

1. There is an error `stat: %R: bad format` when I run `emqx_ctl` command.
2. It shows me `!!!! WARNING: ulimit -n is 256; 1024 is the recommended minimum.`, I know it is due to my ulimit setting but this warning msgs should only be shown in `emqx` command, not `emqx_ctl` command.
3. Could we consider optimize the above warning message, removing the scary `!!!!` signs?

### How can we reproduce it (as minimally and precisely as possible)?

Just run the `emqx_ctl` command on a Mac OSX with the default ulimit settings.

### EMQX version

<details>

```console
$ ./bin/emqx_ctl broker
stat: %R: bad format
!!!!
!!!! WARNING: ulimit -n is 256; 1024 is the recommended minimum.
!!!!
sysdescr    :     EMQX
version       :     5.0.11-g16aeba24
datetime    :     2022-12-07T15:57:44.378470360+08:00
uptime       :     6 minutes, 43 seconds
```

</details>

### OS version

iMac, Mac OSX.

### Log files

<details>

</details>

**Comment by id** [comment]
@terry-xiaoyu it might be that you have utils from `coreutils` homebrew package in your path overriding their default (BSD) versions.

**Comment by id** [comment]
Agree about the scary warning message.

**Comment by terry-xiaoyu** [comment]
For the `stat: %R` problem, Yes, it is very possible that the iMac has installed `coreutils` and put it to the beginning of the $PATH. But we still have to handle this situation, because many users would install `coreutils` on their Mac. We may need change to check the version of `stat` command directly instead of check the OS type.
