### ISSUE TITLE
service support externalTrafficPolicy in chart

### ISSUE THREAD

**Issue by fissssssh** [emqx/emqx#9515]
### What would you like to be added or enhanced?

service support externalTrafficPolicy in chart

### Why is this needed?

I want to get the client's real IP when service type is NodePort.

**Comment by Rory-Z** [comment]
Hi, @fissssssh, thanks for your feedback, we will finish it in next release

**Comment by Rory-Z** [comment]
Hi, @fissssssh The PR is merged, you will see them in EMQX 4.4.12 and EMQX 5.0.12, it will coming soon.
