### ISSUE TITLE
Clustered emqtt : Get all clients connected to the broker

### ISSUE THREAD

**Issue by msdevanms** [emqx/emqx#952]
#### Environment

- OS: 
- Erlang/OTP: 
- EMQ: 

#### Description

*https://github.com/emqtt/emqttd/issues/230 The same question but in clustered environment. Currently i am getting all connected clients list if and only if i call and merge list of each clustered emqtt . Because emqtt does not give whole clients list in a single call to one clustered machine. 

Eg scenario : system_A and system_B have clustered . To fetch the connected clients from system_A i can call http://system_A:18083/api/clients and for clients list from system_B i need to call http://system_B:18083/api/clients. My question is, since these machines are clustered why can't we get all connected list from single machine  ?
*

**Comment by Leen15** [comment]
Up on this. it should be very useful if dashboard could show all data aggregated (clients, sessions, topics, subscriptions) because it's a pain check every node of the cluster for every section.
