### ISSUE TITLE
[Management APIs] Wrong count in users permissions list request with fuzzy search

### ISSUE THREAD

**Issue by leoandrea7** [emqx/emqx#9532]
### What happened?

When try to exec [list of permissions](https://www.emqx.io/docs/en/v5.0/admin/api.html#/Authorization/get_authorization_sources_built_in_database_username) reqeust with `like_username` query param populated, the `count` field in the response is always 0 even if there are one or more results. But when try to exec the same request without `like_username` query param, the `count` field in the response is right.

### What did you expect to happen?

To have right count in response.

### How can we reproduce it (as minimally and precisely as possible)?

1. Create built_in database authorization (From dashboard: Authorization -> Create -> Built-in database)
2. Add permission with username: user1 (From dashboard: Authorization -> built-in database -> User Management tab -> Username Tab -> Add)
3. Execute curl: 
```curl GET '[YOUR EMQX URL]/api/v5/authorization/sources/built_in_database/username?like_username=us' --header 'Authorization: [YOUR AUTH]'```

### EMQX version

5.0.11

**Comment by zhongwencool** [comment]
Thanks for reporting.
For efficiency, the API does not return count for fuzzy lookups.
It will be added to the documentation later.
