### ISSUE TITLE
How the message is discarded the exhook/OnMessageDelivered 

### ISSUE THREAD

**Issue by greatewei** [emqx/emqx#9546]
### What would you like to be added or enhanced?

I hope that at the time of delivering the message to selectively discard the message

### Why is this needed?

Different side to subscribe to the same topic, to implement the points to push

**Comment by tigercl** [comment]
@greatewei Hi.
Why not try to achieve it with different topics?

**Comment by greatewei** [comment]
> @greatewei Hi. Why not try to achieve it with different topics?

Due to historical reasons, the client failed to fully upgrade

**Comment by tigercl** [comment]
@greatewei Maybe you can put it another way? When these devices connect and subscribe, cancel these subscriptions in the `client.subscribe` hook?

**Comment by greatewei** [comment]
> 
I hope the historical versions of the device can also receive the data.

**Comment by tigercl** [comment]
If you can selectively distribute, should you also be able to selectively unsubscribe?

**Comment by greatewei** [comment]
> 

Don't need to subscribe to the old version equipment, so they will not release to receive normal messages

**Comment by tigercl** [comment]
I understand what you mean, so far, I suggest you choose the first solution.

In addition, if you have a large number of historical devices, the additional performance loss caused by the second solution will be more.

**Comment by greatewei** [comment]
> I understand what you mean, so far, I suggest you choose the first solution.
> 
> In addition, if you have a large number of historical devices, the additional performance loss caused by the second solution will be more.

Exhook `message.Delivered`, will support messages discarded ?
 So the second scheme has the potential to achieve, We only for a simple judgment.

**Comment by tigercl** [comment]
If it's just achievable, it's certainly possible.

But if it is whether we will support this feature, I personally think that there is a lack of factors that can drive us.

If you still prefer the second option, I will feed this requirement back to our product team.

**Comment by greatewei** [comment]
> If it's just achievable, it's certainly possible.
> 
> But if it is whether we will support this feature, I personally think that there is a lack of factors that can drive us.
> 
> If you still prefer the second option, I will feed this requirement back to our product team.

The existing disadvantages of the first scheme: the push to subscribe to different Topic currently applied to end, can satisfy, but the subsequent according to different versions of the same end, or more dimensions change, subscribe to the Topic will become bloated, client need to release.

The advantage of the second solution is: change in the client does not need to carry on the Topic, all logical server implementation.

`message.Delivered` support messages discarded ,This will allow us to have better maintenance

**Comment by tigercl** [comment]
We do not recommend publishing different message content on the same topic and some clients may not be able to handle it. This sacrifices the flexibility of MQTT itself.

Perhaps a better solution is to ensure compatibility between versions?

**Comment by greatewei** [comment]
> We do not recommend publishing different message content on the same topic and some clients may not be able to handle it. This sacrifices the flexibility of MQTT itself.
> 
> Perhaps a better solution is to ensure compatibility between versions?

We is actually part of the scene does not want to specify the client receives the message

**Comment by tigercl** [comment]
So what I mean is try to keep the previous topic and message content unchanged.

**That is, try to use this way**

Old topic: 
```
{
  "old field": "xxx"
}
```

New Topic:

```
{
  "new field": "xxx"
}
```

**Instead of**

Old Topic:

```
{
  "old field": "xxx",
  "new field": "xxx"
}
```

**Comment by tigercl** [comment]
If so, it doesn't seem to have anything to do with the version? Even if it is the same version, do you need messages on the same topic to be delivered to only some clients?

Or am I misunderstanding? Can you go into more detail?

**Comment by tigercl** [comment]
If you use a new topic, the client of the old version should not receive the message without subscribing?

**Comment by greatewei** [comment]
> 

Using the new topic, the same message may need to push to more than one topic

**Comment by greatewei** [comment]
> If you use a new topic, the client of the old version should not receive the message without subscribing?
