### ISSUE TITLE
Better ACL cache configuration options

### ISSUE THREAD

**Issue by chandrasekharh** [emqx/emqx#955]
#### Environment

- OS: All supported 
- Erlang/OTP: 
- EMQ: 2.2

#### Description
Feature request to better control ACL caching. 

The mqtt.cache_acl is a good option to control ACL cache. However most of the times, it would be desirable to have granular control over the caching.  A lot of times, servers could be running for longer periods and clients could also be continuously connected. If the authentication or acl changes in the mean time, it would be nice to have some options to clear the cache and/or forcefully disconnect a client. 
Here are some desired features. 

1.) Options to configure time to live on each cache entry or in general to all the cache entries.   

2.) Clear the ACL cache "programatically" - for scenarios when a previously permitted access is granted and now it is revoked. An API would be nice. 

3.) Option to ACL clear cache  from the console or dashboard.

**Comment by phanimahesh** [comment]
The built in acl system is intended for ssimple use cases. It is not intended for serious production use. Don't get me wrong, it works, and has no known bugs, but it does not offer enough flexibility.

If the broker is expected to run for extended periods, with large number of clients, and a more sophisticated control is needed, please consider using one of the auth/acl plugins. http plugin allows you to specify a url, which will be queried and whose response will determine ACL allow/deny. various databases are supported through their respective plugins.

**Comment by chandrasekharh** [comment]
Yes - we tried the http auth plugin and are planning to use it for production. But even with that, it would be nice to have the caching option turned on so that the auth servers are not overloaded with acl requests for every publish that the clients make. At the same time we would like to have a way to clear the cache when something changes with the acl.

**Comment by tpiecora** [comment]
I am using mysql auth.  Do the cached ACLs ever expire?  Is there any way to clear the cache?  If There is an ever increasing number of users then will the cache eventually consume all the available memory?

**Comment by terry-xiaoyu** [comment]
The cache TTL config is available in R3.0, named`acl_cache_ttl` in etc/emqx.conf.
