### ISSUE TITLE
"local topic" field missing from EMQX Dashboard (MQTT Sink)

### ISSUE THREAD

**Issue by RiccardoMorandi** [emqx/emqx#9572]
Hello everyone, i was trying to create an **MQTT Sink** from EMQX dashboard.
I noticed that even if my broker was receiving messages, the sink wasn't working and it wans't sending messages to the other MQTT broker.
After some searches i found in the API documentation that exists a field named **"local topic"** that is not present in EMQX dashboard and so it cannot be edited from there. I managed to edit this field with API btw and now is working.

I expect the field to be added in future.

### EMQX version

<details>
EMQX 5.0.9
</details>

### OS version

<details>
Ubuntu Server 18.04.6
</details>

**Comment by zmstone** [comment]
Hi. @RiccardoMorandi 

Thank you for reporting it.

We have done a redesign of the MQTT bridge's UI and config layout in v5.0.12 (ported the Enterprise edition layout to opensource)
The new version works on older config file, but translates to new layout after you make some changes from the UI or API.
(stored to cluster_override.conf).

I'm closing this PR now, if there are any other issues, please feel free to open a new issue.

**Comment by Sladerix** [comment]
> Hi. @RiccardoMorandi
> 
> Thank you for reporting it.
> 
> We have done a redesign of the MQTT bridge's UI and config layout in v5.0.12 (ported the Enterprise edition layout to opensource) The new version works on older config file, but translates to new layout after you make some changes from the UI or API. (stored to cluster_override.conf).
> 
> I'm closing this PR now, if there are any other issues, please feel free to open a new issue.

I have installed the 5.0.12 and the “local topic” field is still missing in the dashboard

**Comment by Sladerix** [comment]
Ok, never mind I changed something random form the UI and now it has changed.

now the field is present.
