### ISSUE TITLE
Why does the scheduler thread occur 'context switch' frequently, even thought in the free period.

### ISSUE THREAD

**Issue by warlock-wu** [emqx/emqx#9588]
### What happened?

It shows CPU always has high loading,  thought  CPU is not busy.
When CPU is 20% used, then its loading is higher then 50%,  and when up to 50% used, then loading more than 85%.
By pidstat, it shows the scheduler thread always occur 'context switch'
I wonder if it is an exception?

EMQX version 4.3  in  8C32G PC and  about 10w clients.
![无标题](https://user-images.githubusercontent.com/52406206/208869156-c5051b2a-8cb9-42ba-95bc-c5c63f342f71.png)

### What did you expect to happen?

How to reduce the cpu loading?  Or  what's the performance about the CPU using and loading

### EMQX version

<details>

```console
$ ./bin/emqx_ctl broker
# paste output here
version 4.3.5

</details>


### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
x86_64 GNU/Linux
8C 32G

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Log files

<details>

</details>

**Comment by warlock-wu** [comment]
Payload size is less then 2k and the rate of messages  is not more than 10Mbps
I just want to know what the normal range of CPU loading is.

After trying the different parameters setting, I found the machine showed different cpu loading with the same testing  message rate.

listener.tcp.external.acceptors = 64
 node.async_threads = 8
external.active_n = 100

It seems the smaller 'external.active_n' ,the lower the CPU loading  and "async_threads" set to the number of the CPU core is better than others.

Would you help to clarify how to set a set of better parameters in 8C32G machine? 
 

> EMQX need to do network IO and also manage memory. context switching is quiet normal unless you don't have any work load.
> 
> What kind of work load do you have? rate of messaging and payload size?
> 
> I don't really understand following, pls clarify.
> 
> > When CPU is 20% used, then its loading is higher then 50%, and when up to 50% used, then loading more than 85%.

**Comment by qzhuyan** [comment]
> I just want to know what the normal range of CPU loading is.
we cannot give an estimation without full picture of the hardware, workload, the function you enabled in EMQX, and traffic pattern. 

If you want to lower the CPU usage, you could try to put some scheduler offline with VM args `+S 2:2` (with only two schedulers online) which will make fewer CPU cores work for EMQX.
