### ISSUE TITLE
Emqx logs authorization source plaintext password on start up

### ISSUE THREAD

**Issue by lschuer** [emqx/emqx#9589]
### What happened?

On startup the emqx logs the authorization sources configuration. The password is logged as plaintext. We configured the authorization source via environtment variables. 

These are the logs:

```
authorization.sources.1.query = EMQX_AUTHORIZATION__SOURCES__1__QUERY = "SELECT permission, action, topic FROM mqtt_acl WHERE username = ${username}"
authorization.sources.1.password = EMQX_AUTHORIZATION__SOURCES__1__PASSWORD = plain-password
authorization.sources.1.username = EMQX_AUTHORIZATION__SOURCES__1__USERNAME = doadmin
authorization.sources.1.database = EMQX_AUTHORIZATION__SOURCES__1__DATABASE = emqx
authorization.sources.1.server = EMQX_AUTHORIZATION__SOURCES__1__SERVER = postgres:25060
authorization.sources.1.enable = EMQX_AUTHORIZATION__SOURCES__1__ENABLE = true
authorization.sources.1.type = EMQX_AUTHORIZATION__SOURCES__1__TYPE = postgresql
```

### What did you expect to happen?

I expected the password to be hidden with **** like other passwords. As an example the logs for the dashboard user configuration:

```
dashboard.default_username = EMQX_DASHBOARD__DEFAULT_USERNAME = admin
dashboard.default_password = EMQX_DASHBOARD__DEFAULT_PASSWORD = ******
```

### How can we reproduce it (as minimally and precisely as possible)?

Configure an authorization source via envrionment variables like:

```
EMQX_AUTHORIZATION__SOURCES__1__ENABLE = true
EMQX_AUTHORIZATION__SOURCES__1__TYPE = postgresql
EMQX_AUTHORIZATION__SOURCES__1__SERVER = postgres
EMQX_AUTHORIZATION__SOURCES__1__USERNAME = doadmin
EMQX_AUTHORIZATION__SOURCES__1__PASSWORD = plain-password
EMQX_AUTHORIZATION__SOURCES__1__DATABASE = emqx
EMQX_AUTHORIZATION__SOURCES__1__QUERY = "SELECT permission, action, topic FROM mqtt_acl WHERE username = ${username}"
```

### EMQX version

5.0.12

**Comment by tigercl** [comment]
Hi, @lschuer 
Thanks for your feedback, we will fix it as soon as possible.

**Comment by zmstone** [comment]
will be fixed in https://github.com/emqx/emqx/pull/9608
btw, if it's `host:port` for the server, you'll have to quote it like this:

`export EMQX_AUTHORIZATION__SOURCES__1__SERVER = \"postgres:25060\"`
