### ISSUE TITLE
Persistent storage feature on Kubernetes, should I retain emqttd/data?

### ISSUE THREAD

**Issue by vidhill** [emqx/emqx#959]
#### Environment
Kubernetes
- OS: Alpine
- Erlang/OTP: 7.3.1 
- EMQ: v2.0.7

#### Description

Hello, 
We intend to run an EMQ cluster on Kubernetes... 
Kubernetes has a [persistant storage](https://kubernetes.io/docs/user-guide/persistent-volumes/) feature which allows data survive a re-start/crash of a container, 

I understand that most EMQ data is stored in memory (except for 'topics trees' is it?) 

Would there be any benefit to persisting any files? if so which would it be, maybe the `emqttd/data` folder?

**Comment by felipejfc** [comment]
+1

**Comment by kannach** [comment]
+1

**Comment by everydaynerd** [comment]
+1

**Comment by DavidHtx** [comment]
+1

**Comment by a3aanwisse** [comment]
+1

**Comment by Oduig** [comment]
+1

**Comment by popaaaandrei** [comment]
isn't this available only in enterprise version? :)

**Comment by Gilbert-Wong** [comment]
Yes, :)
