### ISSUE TITLE
Kubernetes EMQX MQTT Bridge singleton not available

### ISSUE THREAD

**Issue by Sladerix** [emqx/emqx#9601]
### What happened?

Hi everybody I've the latest version of EMQX on my Kubernetes cluster (5.0.12)

I need to create an MQTT Ingress that receives messages from another broker. 
There is also a client subscribed to a topic (e.g. `telemetry/#`) to EMQX.

The problem is that when a message is sent to that topic on the remote broker on EMQX arrive 4 messages (becuase we have 4 EMQX nodes in the cluster)...

We saw in the documentation that there is the `mode` field that accepts `cluster_shareload `and `cluster_singleton`.
Seems that the singleton option is the one I need to avoid duplicates... however i also saw that the option was removed a couple of months ago...

So.. the question is: How can I avoid messages duplication now?

Thanks in advance.

### What did you expect to happen?

To receive one message even if i've multiple emqx nodes

### EMQX version

<details>

```console
$ ./bin/emqx_ctl broker

sysdescr : EMQX
version : 5.0.12
datetime : 2022-12-22T13:48:11.961497675+00:00
uptime : 38 minutes, 25 seconds
```

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Log files

<details>

</details>

**Comment by tigercl** [comment]
Hi @Sladerix.
Have you configured `remote_topic` as a shared subscription topic?

**Comment by Sladerix** [comment]
> Hi @Sladerix.
> Have you configured `remote_topic` as a shared subscription topic?

Uhm no, how can I do it?

**Comment by tigercl** [comment]
For example, if you want to get news about the topic hello, then you should configure `remote_topic` to `$share/<Group Name>/hello`.

You can refer to this doc: [MQTT Bridge](https://www.emqx.io/docs/en/v5.0/data-integration/data-bridge-mqtt.html)

**Comment by Sladerix** [comment]
> For example, if you want to get news about the topic hello, then you should configure `remote_topic` to `$share/<Group Name>/hello`.
> 
> You can refer to this doc: [MQTT Bridge](https://www.emqx.io/docs/en/v5.0/data-integration/data-bridge-mqtt.html)

In the link reported there is nothing about "sharing" ($share)... Are you maybe referring to [Shared Subscription](https://www.emqx.io/docs/en/v5.0/advanced/shared-subscriptions.html)?

**Comment by Sladerix** [comment]
I tried some things but it does not work.

I tried to set the `remote_topic` of the Ingress Bridge to `$share/g1/telemtry/#` and then I tried to subscribe to:
- telemetry/#
- g1/telemetry/#
- $share/g1/telemetry/#

none of them works

<img width="1134" alt="Schermata 2023-01-03 alle 16 04 52" src="https://user-images.githubusercontent.com/6717214/210383921-4ee6f2a4-a7f7-489a-a3b1-0dee2086f7eb.png">

**Comment by tigercl** [comment]
Hi, @Sladerix 
Sorry for not noticing your reply.

Shared subscriptions are a feature of MQTT 5.0.

The group is determined by the `<Group>` in the topic `$share/<Group>/<Topic>` when you subscribed.

Messages will be delivered to all groups, but only one member of each group receives the message. For details, please refer to this blog: [Shared Subscription](https://www.emqx.com/en/blog/introduction-to-mqtt5-protocol-shared-subscription).

You can [track your original topic](https://www.emqx.io/docs/en/v5.0/observability/tracer.html) to see if any EMQX node in the cluster will still receive all the messages after you configure remote_topic as a shared subscription.

**Comment by Sladerix** [comment]
> 

hi thanks...
I was bridging with the RabbitMQ broker.. that supports up to MQTT 3.1 (so this the problem I think).


For the future:
I did not understand what topic should be a Subscriber subscribe to (which one of the following?):

1. `$share/<Group>/<Topic>`
2. `<Group>/<Topic>`
3. `<Topic>`

**Comment by tigercl** [comment]
The bridge of EMQX needs to use shared subscriptions, which can prevent nodes in the cluster from receiving duplicate messages.

Your client only needs to make a normal subscription.

```
                                   +-----------+
                                   |           |
                                   |EMQX Node 1|
                                   |           |
            Shared Subscription    |           |   Normal Subscription
RabbitMQ ------------------------->|EMQX Node 2| ----------------------> Your Client
             $share/Group/Topic    |           |          Topic
                                   |           |
                                   |EMQX Node 3|
                                   |           |
                                   +-----------+
```

**Comment by Sladerix** [comment]
> Your client only needs to make a normal subscription.
Ok that's what I missed!
Thanks


However, as I said before, I discovered that RabbitMQ supports up to MQTT 3.1, and you said that shared subscriptions are a feature of MQTT 5.0... so I can't test it now :(

Thanks anyway because surely can be useful to someone in the future (me included)
I am going to temporarily close this issue.

Thanks :D
