### ISSUE TITLE
5.0.12 and 13 State: degraded

### ISSUE THREAD

**Issue by sahinmersin** [emqx/emqx#9634]
### What happened?

Ubuntu 20.04.5 LTS install emqx-5.0.12-ubuntu20.04-amd64.deb and emqx-5.0.13-ubuntu20.04-amd64.deb is not working. emqx-5.0.10-ubuntu20.04-amd64.deb is work.

### What did you expect to happen?

Latest version is not working.

### EMQX version

sysdescr  : EMQX
version   : 5.0.10
datetime  : 2022-12-29T09:27:23.116763663+03:00
uptime    : 8 minutes, 22 seconds

### OS version

NAME="Ubuntu"
VERSION="20.04.5 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.5 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal

### Log files

<details>

</details>

**Comment by tigercl** [comment]
Hi @sahinmersin 
When you use `emqx console` command to run EMQX, what happens? Or, what is the log content output on the console?

**Comment by sahinmersin** [comment]
Hi @tigercl 
emqx console:
WARNING: Default (insecure) Erlang cookie is in use.
WARNING: Configure node.cookie in /etc/emqx/emqx.conf or override from environment variable EMQX_NODE__COOKIE
WARNING: Use the same config value for all nodes in the cluster.
log.file_handlers.default.enable = EMQX_LOG__FILE_HANDLERS__DEFAULT__ENABLE = false
log.console_handler.enable = EMQX_LOG__CONSOLE_HANDLER__ENABLE = true
Protocol 'ekka': register/listen error: "port 4370 is in use"

systemctl status emqx:
[os_mon] memory supervisor port (memsup): Erlang has closed
[os_mon] cpu supervisor port (cpu_sup): Erlang has closed

**Comment by tigercl** [comment]
The log indicates that port 4370 is occupied, which is why your startup failed.

You can check [this document](https://www.emqx.io/docs/en/v5.0/deploy/cluster/security.html#intra-cluster-communication-ports) to know how to change this port.

**Comment by zmstone** [comment]
It probably mean there is a EMQX service running.
`ps -ef | grep emqx` should list all the processes.
If the old installation is already deleted, you can kill the process using `kill` command.
