### ISSUE TITLE
emqx_authn_http resource stopped or disabled

### ISSUE THREAD

**Issue by mijjjj** [emqx/emqx#9683]
### What happened?

I tested that my http interface is normal, and it is normal to access emqx at the beginning after it is started, but after running for a period of time, there will be this prompt in about a few days, and then the mqtt client will not be able to connect

### What did you expect to happen?

The mqtt client connection is normal

### How can we reproduce it (as minimally and precisely as possible)?

I don't know how this error occurred, I can provide the configuration file

[emqx.txt](https://github.com/emqx/emqx/files/10349691/emqx.txt)

### EMQX version

5.0.13

### OS version

docker

### Log files

[01e66b9f7de360af1dd76763377d147e7e2d38cd3512b53e7f4082daffd868d0-json.log](https://github.com/emqx/emqx/files/10349682/01e66b9f7de360af1dd76763377d147e7e2d38cd3512b53e7f4082daffd868d0-json.log)

**Comment by mijjjj** [comment]
It returns to normal after restarting emqx

**Comment by mijjjj** [comment]
After restarting for a while, the same problem will appear again

**Comment by thalesmg** [comment]
Hi @mijjjj .

It seems from the logs that there was a connection timeout when checking the health of the HTTP server connection:

```
{"log":"2023-01-05T02:17:30.723344+00:00 [error] line: 409, mfa: emqx_connector_http:do_get_status/2, msg: ehttpc_health_check_failed, reason: connect_timeout, worker: \u003c0.2448.0\u003e\n","stream":"stdout","time":"2023-01-05T02:17:31.030745056Z"}
```

So, it seems that there seems to be some kind of network problem in the environment where EMQX is being run.

**Comment by mijjjj** [comment]
I started it with dokcer. I tested that the network access is normal. I don’t know why this error occurs, and it only appears after a period of normal use.

**Comment by zmstone** [comment]
Hi @mijjjj 
I don't think it's EMQX who encodes  `worker: <0.2448.0>\n"` to `worker: \u003c0.2448.0\u003e\n"`.
Rather the log collector listening to docker outputs trying to encode text to JSON ended up encoding special chars as escaped unicode code-points.

BTW. EMQX has a built-in JSON log formatter. 
`EMQX_LOG__CONSOLE_HANDLER__FORMATTER=json`

**Comment by zmstone** [comment]
I'm closing this issue, since I don't see it's actionable from our side. 
please feel free to reopen or create a new issue for more questions.
