### ISSUE TITLE
firewall configuration for eMQTTd cluster with ephemeral beam ports

### ISSUE THREAD

**Issue by zmang12** [emqx/emqx#974]
#### Environment

- OS: CentOS Linux release 7.3.1611 (Core)
- Erlang/OTP: erts-7.3
- EMQ: 2.0.7

#### Description

1. Setup three separate VMs (as eMQTT nodes) with the goal of running them in a cluster
2. Tested each one individually (NOT in cluster mode). Works fine. Am able to publish to topics, view dashboard, subscribe to topics
3. Next, tried to join these three nodes in a cluster. Here's what I observed:
4. firewall-cmd --list-ports (on Node 1 OR Node 2) 
8083/tcp 80/tcp 4369/tcp 8084/tcp 18083/tcp 1883/tcp 8883/tcp 22/tcp
5. From Node 1 (10.1.12.1):  run cluster join command to have Node 2 (10.1.12.2) join:
cd /opt/emqttd; ./bin/emqttd_ctl  cluster join emqttd@10.1.12.2;
Failed to join the cluster: {node_not_running,'emqttd@10.1.12.2'}
6. On checking if Node2 (10.1.12.2) is running, I found that it is up and running. 
7. netstat -npl| grep beam
tcp        0      0 0.0.0.0:8083            0.0.0.0:*               LISTEN      11794/beam
tcp        0      0 0.0.0.0:8883            0.0.0.0:*               LISTEN      11794/beam
tcp        0      0 0.0.0.0:8084            0.0.0.0:*               LISTEN      11794/beam
tcp        0      0 0.0.0.0:1883            0.0.0.0:*               LISTEN      11794/beam
tcp        0      0 0.0.0.0:38171           0.0.0.0:*               LISTEN      11794/beam
tcp        0      0 0.0.0.0:18083           0.0.0.0:*               LISTEN      11794/beam
8. Notice that ALL of the ports EXCEPT the random ephemeral port 38171 was opened in Node 2's firewall. 
9. Added 38171 to firewalld and opened it. Tried the same cluster join command - it worked. Node 1 and Node 2 are in the cluster. 
10. However, this isn't something one could automate - since that particular port (38171) is random. The next restart of emqttd would have a different port value. Hence, can't keep modifying the port that needs to be kept opened in the firewall. 
11. Also tried to shutdown the firewall (systemctl stop firewalld) and then tried the cluster join command. THis also works. 
12. Left the cluster (emqttd_ctl cluster leave) on Node 2. Restarted the Firewalld (systemctl start firewalld). Then tried to add Node 2 to the cluster from Node 1. This time even though the firewall was up, the cluster join command worked. 

Question:
1. What is the correct way to setup clusters accounting for this ephemeral port for beam? 
2. Is there a way to FIX the port for this particular beam process? Is it really an ephemeral port? 
3. Saw an earlier issue relating to this same question. It described editing eSockd acceptors. Any pointers to how this is to be done would be helpful.  https://github.com/emqtt/emqttd/wiki/FAQ#q1-is-port-4369-and-another-random-port-secure

**Comment by DemonGiggle** [comment]
I run emqttd 2.1.1 version. 
Just modify the following lines to limit the port for clustering usage.

```
etc/emq.conf

# set the port range in the next two lines
node.dist_listen_min = 20000
node.dist_listen_max = 21000
```

In the firewall setting, you can set the port range 2000~21000.

**Comment by hos7ein** [comment]
tnx @DemonGiggle 

it's worked for me.
