### ISSUE TITLE
Not able to set up EMQX within docker on M1

### ISSUE THREAD

**Issue by mezhang111** [emqx/emqx#9754]
### What happened?

Hi, I got the following error message when trying to set up EMQX with docker:

FATAL: Unable to start Erlang.

Please make sure openssl-1.1.1 (libcrypto) and libncurses are installed.

Also ensure it's running on the correct platform,

this EMQX release is built for 24.1.5-3-x86_64-pc-linux-gnu-64-debian11

Is EMQX image not supporting m1 chip?

### What did you expect to happen?

I want to be able to set up the docker container for EMQX

### EMQX version

emqx:4.4

### OS version

Mac OS Montery 12.0.1

### Log files

<details>

</details>

**Comment by id** [comment]
@mezhang111 could you tell which image tag exactly did you use? I just tried this on macbook with M1 chip, and it worked just fine

```
$ arch
arm64
$ docker run -it --rm emqx:4.4
Unable to find image 'emqx:4.4' locally
4.4: Pulling from library/emqx
934ce60d1040: Already exists
e8afc846b328: Pull complete
50de8caa1b20: Pull complete
bfe1c3a6f6e4: Pull complete
ed3192fef418: Pull complete
Digest: sha256:c59900e115b1dda693db21259665002b0fbcfb368ad8ccc5c5aa44b9de738a93
Status: Downloaded newer image for emqx:4.4
!!!!!!
WARNING: Default (insecure) Erlang cookie is in use.
Please set node.cookie in /opt/emqx/etc/emqx.conf or override from environment variable EMQX_NODE_COOKIE
NOTE: Use the same config value for all nodes in the cluster.
!!!!!!
Starting emqx on node 7bbb8604fddf@172.17.0.2
Start mqtt:tcp:internal listener on 127.0.0.1:11883 successfully.
Start mqtt:tcp:external listener on 0.0.0.0:1883 successfully.
Start mqtt:ws:external listener on 0.0.0.0:8083 successfully.
Start mqtt:ssl:external listener on 0.0.0.0:8883 successfully.
Start mqtt:wss:external listener on 0.0.0.0:8084 successfully.
Start http:management listener on 8081 successfully.
2023-01-13T15:42:26.799391+00:00 [warning] [Dashboard] Using default password for dashboard 'admin' user. Please use './bin/emqx_ctl admins' command to change it. NOTE: the default password in config file is only used to initialise the database record, changing the config file after database is initialised has no effect.
Start http:dashboard listener on 18083 successfully.
EMQ X Broker 4.4.14 is running now!
```

**Comment by mezhang111** [comment]
> @mezhang111 could you tell which image tag exactly did you use? I just tried this on macbook with M1 chip, and it worked just fine
> 
> ```
> $ arch
> arm64
> $ docker run -it --rm emqx:4.4
> Unable to find image 'emqx:4.4' locally
> 4.4: Pulling from library/emqx
> 934ce60d1040: Already exists
> e8afc846b328: Pull complete
> 50de8caa1b20: Pull complete
> bfe1c3a6f6e4: Pull complete
> ed3192fef418: Pull complete
> Digest: sha256:c59900e115b1dda693db21259665002b0fbcfb368ad8ccc5c5aa44b9de738a93
> Status: Downloaded newer image for emqx:4.4
> !!!!!!
> WARNING: Default (insecure) Erlang cookie is in use.
> Please set node.cookie in /opt/emqx/etc/emqx.conf or override from environment variable EMQX_NODE_COOKIE
> NOTE: Use the same config value for all nodes in the cluster.
> !!!!!!
> Starting emqx on node 7bbb8604fddf@172.17.0.2
> Start mqtt:tcp:internal listener on 127.0.0.1:11883 successfully.
> Start mqtt:tcp:external listener on 0.0.0.0:1883 successfully.
> Start mqtt:ws:external listener on 0.0.0.0:8083 successfully.
> Start mqtt:ssl:external listener on 0.0.0.0:8883 successfully.
> Start mqtt:wss:external listener on 0.0.0.0:8084 successfully.
> Start http:management listener on 8081 successfully.
> 2023-01-13T15:42:26.799391+00:00 [warning] [Dashboard] Using default password for dashboard 'admin' user. Please use './bin/emqx_ctl admins' command to change it. NOTE: the default password in config file is only used to initialise the database record, changing the config file after database is initialised has no effect.
> Start http:dashboard listener on 18083 successfully.
> EMQ X Broker 4.4.14 is running now!
> ```

The docker compose file is provided by DJI, and the image tag is:

emqx:
    image: emqx:4.4
    ports:
      - "18083:18083"
      - "1883:1883"
      - "8083:8083"
      - "8883:8883"
      - "8084:8084"
    environment:
      - EMQX_ALLOW_ANONYMOUS=true
    hostname: emqx-broker
    networks:
      - cloud_service_bridge

**Comment by id** [comment]
@mezhang111 could you post command line and full output from docker compose?

**Comment by mezhang111** [comment]
> 

I just explicitely pulled the newer image from docker hub now it is fine. Thanks!
