### ISSUE TITLE
Upgrade EMQX 5.0.11 to 5.0.12 crash erlang because of incorrect data bridges config

### ISSUE THREAD

**Issue by Frtrillo** [emqx/emqx#9786]
### What happened?

EMQX crash erlang and cant start after upgrading from <5.0.11 to >5.0.12
```
[os_mon] cpu supervisor port (cpu_sup): Erlang has closed
{"Kernel pid terminated",application_controller,"{application_start_failure,emqx_machine,{{shutdown,{failed_to_start_child,emqx_machine_boot,{'EXIT',{{failed_to_start_app,emqx_conf,{emqx_conf,{bad_return,{{emqx_conf_app,start,[normal,[]]},#{discarded_errors_count => 4,kind => validation_error,path => \"bridges.webhook.smartate-postCreateAlarm\",reason => unknown_fields,schema_module => emqx_conf_schema,unknown => \"direction\",unmatched => 

> \"local_topic,request,...\"}}}}},[{emqx_machine_boot,start_one_app,1,[{file,\"emqx_machine_boot.erl\"},{line,89}]},{lists,foreach,2,[{file,\"lists.erl\"},{line,1342}]},{emqx_machine_boot,post_boot,0,[{file,\"emqx_machine_boot.erl\"},{line,38}]},{supervisor,do_start_child_i,3,[{file,\"supervisor.erl\"},{line,414}]},{supervisor,do_start_child,2,[{file,\"supervisor.erl\"},{line,400}]},{supervisor,'-start_children/2-fun-0-',3,[{file,\"supervisor.erl\"},{line,384}]},{supervisor,children_map,4,[{file,\"supervisor.erl\"},{line,1250}]},{supervisor,init_children,2,[{file,\"supervisor.erl\"},{line,350}]},{gen_server,init_it,2,[{file,\"gen_server.erl\"},{line,423}]},{gen_server,init_it,6,[{file,\"gen_server.erl\"},{line,390}]},{proc_lib,init_p_do_apply,3,[{file,\"proc_lib.erl\"},{line,226}]}]}}}},{emqx_machine_app,start,[normal,[]]}}}"}

Kernel pid terminated (application_controller) ({application_start_failure,emqx_machine,{{shutdown,{failed_to_start_child,emqx_machine_boot,{'EXIT',{{failed_to_start_app,emqx_conf,{emqx_conf,{bad_return,{{emqx_conf_app,start,[normal,[]]},#{discarded_errors_count => 4,kind => validation_error,path => "bridges.webhook.smartate-postCreateAlarm",reason => unknown_fields,schema_module => emqx_conf_schema,unknown => "direction",unmatched => "local_topic,request,..."}}}}},[{emqx_machine_boot,start_one_app,1,[{file,"emqx_machine_boot.erl"},{line,89}]},{lists,foreach,2,[{file,"lists.erl"},{line,1342}]},{emqx_machine_boot,post_boot,0,[{file,"emqx_machine_boot.erl"},{line,38}]},{supervisor,do_start_child_i,3,[{file,"supervisor.erl"},{line,414}]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,400}]},{supervisor,'-start_children/2-fun-0-',3,[{file,"supervisor.erl"},{line,384}]},{supervisor,children_map,4,[{file,"supervisor.erl"},{line,1250}]},{supervisor,init_children,2,[{file,"supervisor.erl"},{line,350}]},

Crash dump is being written to: log/erl_crash.dump...done
```

### What did you expect to happen?

Update correctly

### How can we reproduce it (as minimally and precisely as possible)?

* install emqx 5.0.11 (or lower versions)
* create some data bridge rules with webhooks and http post requests 
* upgrade to emqx 0.12 or higher
* sudo apt-get upgrade emqx

### EMQX version

<details>

EMQX Community 5.0.11
</details>

### OS version

<details>
Ubuntu LTS 20.0.4
</details>

### Log files

<details>
```
[os_mon] cpu supervisor port (cpu_sup): Erlang has closed
{"Kernel pid terminated",application_controller,"{application_start_failure,emqx_machine,{{shutdown,{failed_to_start_child,emqx_machine_boot,{'EXIT',{{failed_to_start_app,emqx_conf,{emqx_conf,{bad_return,{{emqx_conf_app,start,[normal,[]]},#{discarded_errors_count => 4,kind => validation_error,path => \"bridges.webhook.smartate-postCreateAlarm\",reason => unknown_fields,schema_module => emqx_conf_schema,unknown => \"direction\",unmatched => 

> \"local_topic,request,...\"}}}}},[{emqx_machine_boot,start_one_app,1,[{file,\"emqx_machine_boot.erl\"},{line,89}]},{lists,foreach,2,[{file,\"lists.erl\"},{line,1342}]},{emqx_machine_boot,post_boot,0,[{file,\"emqx_machine_boot.erl\"},{line,38}]},{supervisor,do_start_child_i,3,[{file,\"supervisor.erl\"},{line,414}]},{supervisor,do_start_child,2,[{file,\"supervisor.erl\"},{line,400}]},{supervisor,'-start_children/2-fun-0-',3,[{file,\"supervisor.erl\"},{line,384}]},{supervisor,children_map,4,[{file,\"supervisor.erl\"},{line,1250}]},{supervisor,init_children,2,[{file,\"supervisor.erl\"},{line,350}]},{gen_server,init_it,2,[{file,\"gen_server.erl\"},{line,423}]},{gen_server,init_it,6,[{file,\"gen_server.erl\"},{line,390}]},{proc_lib,init_p_do_apply,3,[{file,\"proc_lib.erl\"},{line,226}]}]}}}},{emqx_machine_app,start,[normal,[]]}}}"}

Kernel pid terminated (application_controller) ({application_start_failure,emqx_machine,{{shutdown,{failed_to_start_child,emqx_machine_boot,{'EXIT',{{failed_to_start_app,emqx_conf,{emqx_conf,{bad_return,{{emqx_conf_app,start,[normal,[]]},#{discarded_errors_count => 4,kind => validation_error,path => "bridges.webhook.smartate-postCreateAlarm",reason => unknown_fields,schema_module => emqx_conf_schema,unknown => "direction",unmatched => "local_topic,request,..."}}}}},[{emqx_machine_boot,start_one_app,1,[{file,"emqx_machine_boot.erl"},{line,89}]},{lists,foreach,2,[{file,"lists.erl"},{line,1342}]},{emqx_machine_boot,post_boot,0,[{file,"emqx_machine_boot.erl"},{line,38}]},{supervisor,do_start_child_i,3,[{file,"supervisor.erl"},{line,414}]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,400}]},{supervisor,'-start_children/2-fun-0-',3,[{file,"supervisor.erl"},{line,384}]},{supervisor,children_map,4,[{file,"supervisor.erl"},{line,1250}]},{supervisor,init_children,2,[{file,"supervisor.erl"},{line,350}]},

Crash dump is being written to: log/erl_crash.dump...done
```
</details>

**Comment by zmstone** [comment]
This looks like a missed config migration for webhook bridge.
Could you share the file `data/configs/cluster-override.conf` with us?
Mind to redact the sensitive fields such as auth credentials etc, before sharing it.

**Comment by Frtrillo** [comment]
> This looks like a missed config migration for webhook bridge. Could you share the file `data/configs/cluster-override.conf` with us? Mind to redact the sensitive fields such as auth credentials etc, before sharing it.

Hello, sure:
<details>
authentication {
  backend = "built_in_database"
  mechanism = "password_based"
  password_hash_algorithm {name = "sha256", salt_position = "suffix"}
  user_id_type = "username"
}
authorization {
  cache {enable = true, ttl = "5m"}
  deny_action = "ignore"
  no_match = "deny"
  sources = [
    {
      enable = true
      path = "/var/lib/emqx/authz/acl.conf"
      type = "file"
    }
  ]
}
bridges {
  webhook {
    "smartate-postCreateAlarm" {
      body = "${payload}"
      connect_timeout = "5s"
      direction = "egress"
      enable = true
      enable_pipelining = 100
      headers {Authorization = "*redacted*", "content-type" = "application/json"}
      max_retries = 3
      method = "post"
      pool_size = 4
      pool_type = "random"
      request_timeout = "6s"
      ssl {
        ciphers = ""
        depth = 10
        enable = false
        reuse_sessions = true
        secure_renegotiate = true
        user_lookup_fun = "emqx_tls_psk:lookup"
        verify = "verify_peer"
        versions = ["tlsv1.3", "tlsv1.2", "tlsv1.1", "tlsv1"]
      }
      url = "*redacted*"
    }
    "smartate-postCreateHistoryLog" {
      body = "${payload}"
      connect_timeout = "5s"
      direction = "egress"
      enable = true
      enable_pipelining = 100
      headers {Authorization = "*redacted*", "content-type" = "application/json"}
      max_retries = 1
      method = "post"
      pool_size = 4
      pool_type = "random"
      request_timeout = "4s"
      ssl {
        ciphers = ""
        depth = 10
        enable = false
        reuse_sessions = true
        secure_renegotiate = true
        user_lookup_fun = "emqx_tls_psk:lookup"
        verify = "verify_peer"
        versions = ["tlsv1.3", "tlsv1.2", "tlsv1.1", "tlsv1"]
      }
      url = "*redacted*"
    }
    "smartgate-deviceInformationEvent" {
      body = "${payload}"
      connect_timeout = "5s"
      direction = "egress"
      enable = true
      enable_pipelining = 100
      headers {Authorization = "*redacted*", "content-type" = "application/json"}
      max_retries = 3
      method = "post"
      pool_size = 4
      pool_type = "random"
      request_timeout = "5s"
      ssl {
        ciphers = ""
        depth = 10
        enable = false
        reuse_sessions = true
        secure_renegotiate = true
        user_lookup_fun = "emqx_tls_psk:lookup"
        verify = "verify_peer"
        versions = ["tlsv1.3", "tlsv1.2", "tlsv1.1", "tlsv1"]
      }
      url = "*redacted*"
    }
    "smartgate-deviceOnlineStatus" {
      body = ""
      connect_timeout = "5s"
      direction = "egress"
      enable = true
      enable_pipelining = 100
      headers {Authorization = "*redacted*", "content-type" = "application/json"}
      max_retries = 1
      method = "post"
      pool_size = 4
      pool_type = "random"
      request_timeout = "5s"
      ssl {
        ciphers = ["TLS_AES_256_GCM_SHA384", "TLS_AES_128_GCM_SHA256", "TLS_CHACHA20_POLY1305_SHA256", "TLS_AES_128_CCM_SHA256", "TLS_AES_128_CCM_8_SHA256", "ECDHE-ECDSA-AES256-GCM-SHA384", "ECDHE-RSA-AES256-GCM-SHA384", "ECDHE-ECDSA-AES256-SHA384", "ECDHE-RSA-AES256-SHA384", "ECDH-ECDSA-AES256-GCM-SHA384", "ECDH-RSA-AES256-GCM-SHA384", "ECDH-ECDSA-AES256-SHA384", "ECDH-RSA-AES256-SHA384", "DHE-DSS-AES256-GCM-SHA384", "DHE-DSS-AES256-SHA256", "AES256-GCM-SHA384", "AES256-SHA256", "ECDHE-ECDSA-AES128-GCM-SHA256", "ECDHE-RSA-AES128-GCM-SHA256", "ECDHE-ECDSA-AES128-SHA256", "ECDHE-RSA-AES128-SHA256", "ECDH-ECDSA-AES128-GCM-SHA256", "ECDH-RSA-AES128-GCM-SHA256", "ECDH-ECDSA-AES128-SHA256", "ECDH-RSA-AES128-SHA256", "DHE-DSS-AES128-GCM-SHA256", "DHE-DSS-AES128-SHA256", "AES128-GCM-SHA256", "AES128-SHA256", "ECDHE-ECDSA-AES256-SHA", "ECDHE-RSA-AES256-SHA", "DHE-DSS-AES256-SHA", "ECDH-ECDSA-AES256-SHA", "ECDH-RSA-AES256-SHA", "ECDHE-ECDSA-AES128-SHA", "ECDHE-RSA-AES128-SHA", "DHE-DSS-AES128-SHA", "ECDH-ECDSA-AES128-SHA", "ECDH-RSA-AES128-SHA", "RSA-PSK-AES256-GCM-SHA384", "RSA-PSK-AES256-CBC-SHA384", "RSA-PSK-AES128-GCM-SHA256", "RSA-PSK-AES128-CBC-SHA256", "RSA-PSK-AES256-CBC-SHA", "RSA-PSK-AES128-CBC-SHA"]
        depth = 10
        enable = false
        reuse_sessions = true
        secure_renegotiate = true
        user_lookup_fun = "emqx_tls_psk:lookup"
        verify = "verify_none"
        versions = ["tlsv1.3", "tlsv1.2", "tlsv1.1", "tlsv1"]
      }
      url = "*redacted*"
    }
    "test-dumpsv2" {
      body = ""
      connect_timeout = "5s"
      direction = "egress"
      enable = false
      enable_pipelining = 100
      headers {"content-type" = "application/json"}
      max_retries = 3
      method = "post"
      pool_size = 4
      pool_type = "random"
      request_timeout = "5s"
      ssl {
        ciphers = ["TLS_AES_256_GCM_SHA384", "TLS_AES_128_GCM_SHA256", "TLS_CHACHA20_POLY1305_SHA256", "TLS_AES_128_CCM_SHA256", "TLS_AES_128_CCM_8_SHA256", "ECDHE-ECDSA-AES256-GCM-SHA384", "ECDHE-RSA-AES256-GCM-SHA384", "ECDHE-ECDSA-AES256-SHA384", "ECDHE-RSA-AES256-SHA384", "ECDH-ECDSA-AES256-GCM-SHA384", "ECDH-RSA-AES256-GCM-SHA384", "ECDH-ECDSA-AES256-SHA384", "ECDH-RSA-AES256-SHA384", "DHE-DSS-AES256-GCM-SHA384", "DHE-DSS-AES256-SHA256", "AES256-GCM-SHA384", "AES256-SHA256", "ECDHE-ECDSA-AES128-GCM-SHA256", "ECDHE-RSA-AES128-GCM-SHA256", "ECDHE-ECDSA-AES128-SHA256", "ECDHE-RSA-AES128-SHA256", "ECDH-ECDSA-AES128-GCM-SHA256", "ECDH-RSA-AES128-GCM-SHA256", "ECDH-ECDSA-AES128-SHA256", "ECDH-RSA-AES128-SHA256", "DHE-DSS-AES128-GCM-SHA256", "DHE-DSS-AES128-SHA256", "AES128-GCM-SHA256", "AES128-SHA256", "ECDHE-ECDSA-AES256-SHA", "ECDHE-RSA-AES256-SHA", "DHE-DSS-AES256-SHA", "ECDH-ECDSA-AES256-SHA", "ECDH-RSA-AES256-SHA", "ECDHE-ECDSA-AES128-SHA", "ECDHE-RSA-AES128-SHA", "DHE-DSS-AES128-SHA", "ECDH-ECDSA-AES128-SHA", "ECDH-RSA-AES128-SHA", "RSA-PSK-AES256-GCM-SHA384", "RSA-PSK-AES256-CBC-SHA384", "RSA-PSK-AES128-GCM-SHA256", "RSA-PSK-AES128-CBC-SHA256", "RSA-PSK-AES256-CBC-SHA", "RSA-PSK-AES128-CBC-SHA"]
        depth = 10
        enable = false
        reuse_sessions = true
        secure_renegotiate = true
        user_lookup_fun = "emqx_tls_psk:lookup"
        verify = "verify_none"
        versions = ["tlsv1.3", "tlsv1.2", "tlsv1.1", "tlsv1"]
      }
      url = "https://ptsv2.com/t/*redacted*/post"
    }
  }
}
delayed {enable = false, max_delayed_messages = 0}
retainer {
  backend {
    index_specs = [
      [1, 2, 3],
      [1, 3],
      [2, 3],
      [3]
    ]
    max_retained_messages = 0
    storage_type = "disc"
    type = "built_in_database"
  }
  enable = true
  flow_control {
    batch_deliver_limiter {
      capacity = "infinity"
      client {
        capacity = "infinity"
        divisible = false
        failure_strategy = "force"
        initial = "0"
        low_watermark = "0"
        max_retry_time = "10s"
        rate = "infinity"
      }
      initial = "0"
      rate = "infinity"
    }
    batch_deliver_number = 0
    batch_read_number = 0
  }
  max_payload_size = "50KB"
  msg_clear_interval = "48h"
  msg_expiry_interval = "168h"
  stop_publish_clear_msg = false
}
rule_engine {
  ignore_sys_message = true
  jq_function_default_timeout = "10s"
  rules {
    createAlarm {
      actions = ["webhook:smartate-postCreateAlarm"]
      description = "publica datos dispositivo y alarma en servidor"
      enable = true
      metadata {created_at = 1662976596699}
      sql = "SELECT\n  payload\nFROM\n  \"*redacted*"\nWHERE\n  *redacted*"
    }
    createHistoryLog {
      actions = ["webhook:smartate-postCreateHistoryLog"]
      description = ""
      metadata {created_at = 1663672544390}
      sql = "SELECT\n  *redacted*""
    }
    deviceConnections {
      actions = ["webhook:smartgate-deviceOnlineStatus"]
      description = ""
      enable = true
      metadata {created_at = 1662463132121}
      sql = "SELECT\n  clientid, event\nFROM\n  \"$events/client_connected\",*redacted*" WHERE *redacted* > '*redacted*"
    }
    postDeviceInformation {
      actions = ["webhook:smartgate-deviceInformationEvent"]
      description = "procesa info dispositivo a servidor"
      metadata {created_at = 1662976036721}
      sql = "SELECT\n  payload\n*redacted*WHERE\n  *redacted* = true"
    }
  }
}
topic_metrics = []
</details>
