### ISSUE TITLE
After upgraded to the new version, the authentication HTTP server will throw the `500` error

### ISSUE THREAD

**Issue by kerojiang** [emqx/emqx#9795]
### What happened?

从5.0.8版本更新到5.0.14版本，之前的版本有设置认证-http方式，更新后点击认证菜单页面直接报500错且无法取消http认证，也不能重新设置。
更新方式：1先卸载之前版本，2重新安装新版
系统环境:centos 7
emqx版本:官网下载的centos 7的emqx版本
报错截图:
![image](https://user-images.githubusercontent.com/5567031/213075999-8dc4af67-8254-413a-b972-abbecc6ea23c.png)

![image](https://user-images.githubusercontent.com/5567031/213077013-021a9052-d72f-4df3-9b9c-be6d98e405a6.png)

### What did you expect to happen?

解决http认证报错的问题

### EMQX version

<details>

```console
$ ./bin/emqx_ctl broker
sysdescr  : EMQX
version   : 5.0.14
datetime  : 2023-01-18T11:27:28.665757769+08:00
uptime    : 11 minutes, 0 seconds

```

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release

NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

$ uname -a

Linux wuliu_product_wundu01 3.10.0-1160.59.1.el7.x86_64 #1 SMP Wed Feb 23 16:47:03 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux


</details>


### Log files

<details>

</details>

**Comment by zhongwencool** [comment]
Please make sure to delete all old data from `5.0.8`.
It looks like you installed it via deb package. `rm -rf /var/lib/emqx/*`

**Comment by kerojiang** [comment]
> Please make sure to delete all old data from `5.0.8`. It looks like you installed it via deb package. `rm -rf /var/lib/emqx/*`

thanks. It sloved my problem
