### ISSUE TITLE
webhook 404 API_NOT_EXIST:Request Path Not Found

### ISSUE THREAD

**Issue by hihuangwei** [emqx/emqx#9813]
### What happened?

404 API_NOT_EXIST:Request Path Not Found 实际URL是存在的，点击连接测试，提示404

### What did you expect to happen?

404 API_NOT_EXIST:Request Path Not Found 实际URL是存在的，点击连接测试，提示404

### EMQX version

<details>

```console
$ ./bin/emqx_ctl broker
# paste output here
```

</details>

sysdescr  : EMQX
version   : 5.0.14
datetime  : 2023-01-19T07:29:07.258984493+00:00
uptime    : 11 minutes, 8 seconds

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

PRETTY_NAME="Ubuntu 22.04.1 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.1 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy

### Log files

<details>

</details>

**Comment by wemod123** [comment]
Got same issue when update from 5.0.12 to **5.0.14**, while previousely it's working, confirm this is a bug.

**Comment by hihuangwei** [comment]
更新到 5.0.15 已解决
