### ISSUE TITLE
Connection immediately closed only for port 1883

### ISSUE THREAD

**Issue by Shakerrry** [emqx/emqx#9829]
### What happened?

When I am trying to connect using the webclient or MQTTX, I get connected and then immediately disconnected and it is happening when using the 1883 port. The other ports are working fine, for example: ws 8083.
This is the error i get in broker logs (i replaced my ip on peername):
`2023-01-23T08:26:16.231584+00:00 [error] crasher: initial call: emqx_connection:init/4, pid: <0.4191.0>, registered_name: [], error: {badarith,[{emqx_connection,recvloop,2,[{file,"emqx_connection.erl"},{line,413}]},{proc_lib,wake_up,3,[{file,"proc_lib.erl"},{line,236}]}]}, ancestors: [<0.2191.0>,<0.2190.0>,esockd_sup,<0.1920.0>], message_queue_len: 1, messages: [{tcp,#Port<0.57>,<<16,48,0,4,77,81,84,84,4,194,0,60,0,14,109,113,116,116,120,95,99,55,101,54,98,53,102,57,0,6,115,116,101,102,97,110,0,12,84,117,114,110,105,110,97,108,116,49,52,33>>}], links: [<0.2191.0>,#Port<0.57>], dictionary: [{'$logger_metadata$',#{peername => "myip:51871"}}], trap_exit: false, status: running, heap_size: 610, stack_size: 29, reductions: 1131; neighbours:`

### What did you expect to happen?

I expect to connect to the EMQX broker on my instance. When using the cloud version I can connect on 1883 port too.

### EMQX version

<details>

```console
$ ./bin/emqx_ctl broker
sysdescr  : EMQX
version   : 5.0.14
datetime  : 2023-01-23T08:43:40.084204712+00:00
uptime    : 43 minutes, 47 seconds
```

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
NAME="Ubuntu"
VERSION="20.04.5 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.5 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
$ uname -a
Linux myhost 5.15.0-1028-aws #32~20.04.1-Ubuntu SMP Mon Jan 9 18:02:08 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
```

</details>

### Log files

<details>

</details>

**Comment by Shakerrry** [comment]
I have tried to create a new listener for TCP on other port using dashboard and the result is the same: it immediately disconnects (it does not get to the part of auth). The port is running by emqx (netstat command) and the error i get in logs is the one above.

**Comment by zmstone** [comment]
Hi @Shakerrry 
It looks like abut.
I'd like to collect more information though, did you set `idle_timeout` config?

**Comment by zmstone** [comment]
reproduced with:
```
docker run --rm -it -e EMQX_MQTT__IDLE_TIMEOUT='infinity' --net host emqx/emqx:5.0.14 bash
```

**Comment by Shakerrry** [comment]
Hello @zmstone
I confirm that I had setup idle_timeout to infinity. I changed it to other option (1 hour) and now it works. Thank you and sorry for late reply (holiday).
