### ISSUE TITLE
exist two client session with the same client id occurs on a single node

### ISSUE THREAD

**Issue by PureLo** [emqx/emqx#9860]
### What happened?

![image](https://user-images.githubusercontent.com/65882628/215313340-246881ea-98fb-4f33-9698-8d9bacba1f10.png)
![image](https://user-images.githubusercontent.com/65882628/215313346-93aa5b65-f131-435b-9c1f-31b2530c8f6a.png)
![image](https://user-images.githubusercontent.com/65882628/215313355-4c6a91a2-505a-407c-91cc-3e54db46de91.png)

The ip address displayed in the third picture is 192.168.30.154:20492
![image](https://user-images.githubusercontent.com/65882628/215313451-1ed549a4-f4a0-4540-935d-88412ba0800b.png)

### What did you expect to happen?

the same client id only exist one session

### EMQX version

<details>

```console
$ ./bin/emqx_ctl broker
sysdescr  : EMQ X Broker
version   : 4.0.7
uptime    : 22 hours, 1 minutes, 0 seconds
datetime  : 2023-01-29 15:41:41
```

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
NAME="Alpine Linux"
ID=alpine
VERSION_ID=3.10.5
PRETTY_NAME="Alpine Linux v3.10"
HOME_URL="https://alpinelinux.org/"
BUG_REPORT_URL="https://bugs.alpinelinux.org/"

$ uname -a
Linux localhost.localdomain 3.10.0-957.el7.x86_64 #1 SMP Thu Nov 8 23:39:32 UTC 2018 x86_64 Linux
</details>


### Log files

<details>

</details>

**Comment by qzhuyan** [comment]
EMQX version   : 4.0.7

Could you try a newer version? like 4.4.x ?

**Comment by lafirest** [comment]
just a mention #9409

**Comment by ddegasperi** [comment]
I've the same issue with emqx 5.0.16

**Comment by zmstone** [comment]
Hi @ddegasperi 
Sorry that this issue is closed due to the lack of correct labels.
I'm determined to get down to the bottom of this issue.

There had been a few similar issues reported on different versions, and we have failed to reproduce it
If possible, I'd like to have a online troubleshooting session with screen shared.
you can reach out to me in email which can be found in my github profile. (the same as my github handle, and @ gmail.com)

**Comment by zmstone** [comment]
@PureLo @ddegasperi  we have found the root cause for https://github.com/emqx/emqx/issues/9409 which has a similar observation.
Could you please let us know if you have a large amount of retained messages ? and if the lingering client is subscribing to a wildcard topic ?
