### ISSUE TITLE
Proposal for a new http based hook plugin (emq-http-hook)

### ISSUE THREAD

**Issue by vishr** [emqx/emqx#988]
I have been using https://github.com/emqtt/emq-auth-http and it works amazing, we are not tied to any database, key-value store or even programming language for authentication / acl. Similar to this plugin I would propose a http based hook to capture all the events and take action without a need to write a custom plugin. I liked the idea of https://github.com/emqtt/emq-lua-hook plugin but still we have to rely on lua vm and then 3rd-party modules, possibly - I am not even sure how to configure those.

I have done a small prototype https://github.com/labstack/emq-http-hook just enough for my need but it can be extended to write a complete plugin.

Appreciate your feedback.

PS: Ignore my Erlang skills - never programmed in it!

**Comment by vishr** [comment]
Is this the implementation https://github.com/emqtt/emq-web-hook?

**Comment by vishr** [comment]
I have a raised a PR https://github.com/emqtt/emq-web-hook/pull/1, please have a look.

**Comment by s4kibs4mi** [comment]
Hello @vishr ,
I have merged the PR. Thanks for the contribution :)
