### ISSUE TITLE
EMQX application stops due to "Out of memory"

### ISSUE THREAD

**Issue by RodaBVB** [emqx/emqx#9896]
### What happened?

**Environment**
-  EMQX version 4.3.5

**Topology**
2x EMQX nodes in cluster (16 vCPUs, 32GB RAM each)
There are 172k clients connected; every client is subscribed to 17 topics.
[emqx.conf.txt](https://github.com/emqx/emqx/files/10570430/emqx.conf.txt)

After some time of normal running, the application stopped working on **one** machine due to a lack of memory.

At all times, there are clients that are connecting and subscribing to the topics (and disconnecting) which is shown on the graph below (for one broker, it is the same with second broker):
![Screenshot from 2023-02-02 16-16-02](https://user-images.githubusercontent.com/20912951/216364258-3894c019-ecba-4653-8797-092ae9b86a51.png)

There is a **webhook** plugin enabled that sends requests on the "client_subscribe" event. At one point memory consumption starts increasing. It was noticed that when the webhook plugin was unloaded, memory consumption stops increasing (but does not decrease), but when it was reloaded again, after some time, memory consumption continues to increase which leads to the out-of-memory problem that stops the EMQX application. 
Note that this problem only occurs on one of the machines in the cluster, even though clients are connecting to both of the machines.

Below is the memory consumption graph of the problematic machine. Notice that growth started around 18th Jan (it is not known what causes this growth) and around 21th Jan the memory was overloaded which caused the OS to stop the app. After the reboot, everything worked fine for about a week, and on 29th Jan growth started again. 
![Screenshot from 2023-02-02 13-52-37](https://user-images.githubusercontent.com/20912951/216330167-4c3c5f02-3ea7-4e1a-a884-037e3ab90d02.png)
On the 30th Jan the webhook plugin was unloaded and the memory stopped increasing (see the attached image below). When the plugin is loaded again, memory starts increasing again which will eventually cause OOM problem.
![Screenshot from 2023-02-02 14-08-59](https://user-images.githubusercontent.com/20912951/216333616-e11790fd-4775-4892-8d56-f20620b4c841.png)

Below are tables with stats from both brokers.  Note that the problem is on EMQX_2.

**emqx_ctl vm memory** gives:
****
| EMQX_1 | EMQX_2 |
| ------------- | ------------- |
|  memory/total            : **13554204240** | memory/total            : **20927455376** |
| memory/processes        : **9337768624** | memory/processes        : **15112272184** |
| memory/processes_used   : **9337558448** | memory/processes_used   : **15112007736** |
| memory/system           : **4216435616** | memory/system           : **5815183192** |
| memory/atom             : **2408921** | memory/atom             : **2490857** |
| memory/atom_used        : **2397025** | memory/atom_used        : **2459946** |
| memory/binary           : **1925630432** | memory/binary           : **3354010664** |
| memory/code             : **33519893** | memory/code             : **33519893** |
| memory/ets              : **1794810784** | memory/ets              : **1792662256** |

**emqx_ctl recon memory** gives:
| EMQX_1 | EMQX_2 |
| ------------- | ------------- |
| usage/current       : **0.4887335880372839** | usage/current       : **0.5651953684652448** |
| usage/max           : **0.5727554556856673** | usage/max           : **0.5999234311411316** |
| used/current        : **7374838512** | used/current        : **12828765632** |
| used/max            : **14117834528** | used/max            : **20160410432** |
| allocated/current   : **15079870464** | allocated/current   : **22695661568** |
| allocated/max       : **24648974336** | allocated/max       : **33604972544** |
| unused/current      : **7704344840** | unused/current      : **9869033248** |
| unused/max          : **10531139808** | unused/max          : **13444562112** |

**emqx_ctl recon allocated** gives:

| EMQX_1 | EMQX_2 |
| ------------- | ------------- |
| binary_alloc/current: **2157760512** | binary_alloc/current: **3748057088** |
| driver_alloc/current: **160202752** | driver_alloc/current: **173047808** |
| eheap_alloc/current : **10575998976** | eheap_alloc/current : **15024746496** |
| ets_alloc/current   : **2327871488** | ets_alloc/current   : **2494332928** |
| fix_alloc/current   : **645693440** | fix_alloc/current   : **1054375936** |
| ll_alloc/current    : **114819072** | ll_alloc/current    : **128712704** |
| sl_alloc/current    : **557056** | sl_alloc/current    : **557056** |
| std_alloc/current   : **76578816** | std_alloc/current   : **89423872** |
| temp_alloc/current  : **2228224** | temp_alloc/current  : **2228224** |
| binary_alloc/max    : **2990649344** | binary_alloc/max    : **4657467392** |
| driver_alloc/max    : **246972416** | driver_alloc/max    : **257196032**  |
| eheap_alloc/max     : **17607745536** | driver_alloc/max    : **257196032** |
| ets_alloc/max       : **2580054016** | eheap_alloc/max     : **24367243264** |
| fix_alloc/max       : **714899456** | ets_alloc/max       : **2649260032** |
| ll_alloc/max        : **123207680** | fix_alloc/max       : **1111523328** |
| sl_alloc/max        : **87838720** | ll_alloc/max        : **132907008** |
| std_alloc/max       : **199262208** | sl_alloc/max        : **115265536** |
| temp_alloc/max      : **102846464** | temp_alloc/max      : **90992640** |

**emqx_ctl broker metrics**
| EMQX_1 | EMQX_2 |
| ------------- | ------------- |
| actions.error                 : **0** | actions.error                 : **0** |
| actions.exception             : **0** | actions.exception             : **0** |
| actions.retry                 : **0** | actions.retry                 :  **0** |
| actions.success               : **0** | actions.success               : **0** |
| actions.taken                 : **0** | actions.taken                 : **0** |
| bytes.received                : **43253566400** | bytes.received                : **41470504443** |
| bytes.sent                    : **187210307792** | bytes.sent                    : **132935790839** |
| client.acl.allow              : **43434661** | client.acl.allow              : **48423647** |
| client.acl.deny               : **164573** | client.acl.deny               : **170015** |
| client.acl.ignore             : **28061100** | client.acl.ignore             : **30162832** |
| client.auth.anonymous         : **0** | client.auth.anonymous         : **0** |
| client.auth.failure           : **93673** | client.auth.failure           : **79346** |
| client.auth.ignore            : **0** | client.auth.ignore            : **0** |
| client.auth.success           : **1931661** | client.auth.success           : **2693883** |
| client.authenticate           : **2025334** | client.authenticate           : **2773229** |
| client.check_acl              : **71660334** | client.check_acl              : **78756494** |
| client.connack                : **2021081** | client.connack                : **2755302** |
| client.connect                : **2025335** | client.connect                : **2773229** |
| client.connected              : **1931661** | client.connected              : **2693883** |
| client.disconnected           : **1759539** | client.disconnected           : **2505807** |
| client.subscribe              : **1913827** | client.subscribe              : **2710797** |
| client.unsubscribe            : **13238** | client.unsubscribe            : **16280** |
| delivery.dropped              : **0** | delivery.dropped              : **0** |
| delivery.dropped.expired      : **0** | delivery.dropped.expired      : **0** |
| delivery.dropped.no_local     : **0** | delivery.dropped.no_local     : **0** |
| delivery.dropped.qos0_msg     : **206037** | delivery.dropped.qos0_msg     : **282216** |
| delivery.dropped.queue_full   : **0** | delivery.dropped.queue_full   : **0** |
| delivery.dropped.too_large    : **0** | delivery.dropped.too_large    : **0** |
| messages.acked                : **82251559** | messages.acked                : **62162948** |
| messages.delayed              : **0** | messages.delayed              : **0** |
| messages.delivered            : **206377700** | messages.delivered            : **164549546** |
| messages.dropped              : **9610687** | messages.dropped              : **5757695** |
| messages.dropped.expired      : **0** | messages.dropped.expired      : **0** |
| messages.dropped.no_subscriber: **9610687** | messages.dropped.no_subscriber: **5757695** |
| messages.forward              : **12538780** | messages.forward              : **14345767** |
| messages.publish              : **124300556** | messages.publish              : **123806313** |
| messages.qos0.received        : **58206446** | messages.qos0.received        : **58101134** |
| messages.qos0.sent            : **124102078** | messages.qos0.sent            : **102363179** |
| messages.qos1.received        : **65906185** | messages.qos1.received        : **65524629** |
| messages.qos1.sent            : **77150168** | messages.qos1.sent            : **58490525** |
| messages.qos2.received        : **0** | messages.qos2.received        : **0** |
| messages.qos2.sent            : **0** | messages.qos2.sent            : **0** |
| messages.received             : **124112631** | messages.received             : **123625763** |
| messages.retained             : **47924** | messages.retained             : **47808** |
| messages.sent                 : **201252246** | messages.sent                 : **160853704** |
| packets.auth.received         : **0** | packets.auth.received         : **0** |
| packets.auth.sent             : **0** | packets.auth.sent             : **0** |
| packets.connack.auth_error    : **0** | packets.connack.auth_error    : **0** |
| packets.connack.error         : **93688** | packets.connack.error         : **79377** |
| packets.connack.sent          : **1404256** | packets.connack.sent          : **1890998** |
| packets.connect.received      : **2025335** | packets.connect.received      : **2773229** |
| packets.disconnect.received   : **1245921** | packets.disconnect.received   : **2010878** |
| packets.disconnect.sent       : **0** | packets.disconnect.sent       : **0** |
| packets.pingreq.received      : **1305775670** | packets.pingreq.received      : **1297893681** |
| packets.pingresp.sent         : **1305775670** | packets.pingresp.sent         : **1297893681** |
| packets.puback.inuse          : **0** | packets.puback.inuse          : **0** |
| packets.puback.missed         : **80** | packets.puback.missed         : **55** |
| packets.puback.received       : **82251639** | packets.puback.received       : **62163003** |
| packets.puback.sent           : **65906185** | packets.puback.sent           : **65524628** |
| packets.pubcomp.inuse         : **0** | packets.pubcomp.inuse         : **0** |
| packets.pubcomp.missed        : **0** | packets.pubcomp.missed        : **0** |
| packets.pubcomp.received      : **0** | packets.pubcomp.received      : **0** |
| packets.pubcomp.sent          : **0** | packets.pubcomp.sent          : **0** |
| packets.publish.auth_error    : **181765** | packets.publish.auth_error    : **173417** |
| packets.publish.dropped       : **0** | packets.publish.dropped       : **0** |
| packets.publish.error         : **181765** | packets.publish.error         : **173417** |
| packets.publish.inuse         : **0** | packets.publish.inuse         : **0** |
| packets.publish.received      : **124112631** | packets.publish.received      : **123625763** |
| packets.publish.sent          : **201252246** | packets.publish.sent          : **160853704** |
| packets.pubrec.inuse          : **0** | packets.pubrec.inuse          : **0** |
| packets.pubrec.missed         : **0** | packets.pubrec.missed         : **0** |
| packets.pubrec.received       : **0** | packets.pubrec.received       : **0** |
| packets.pubrec.sent           : **0** | packets.pubrec.sent           : **0** |
| packets.pubrel.missed         : **0** | packets.pubrel.missed         : **0** |
| packets.pubrel.received       : **0** | packets.pubrel.received       : **0** |
| packets.pubrel.sent           : **0** | packets.pubrel.sent           : **0** |
| packets.received              : **1517338330** | packets.received              : **1491193669** |
| packets.sent                  : **1576878824** | packets.sent                  : **1529750152** |
| packets.suback.sent           : **1913555** | packets.suback.sent           : **2710659** |
| packets.subscribe.auth_error  : **0** | packets.subscribe.auth_error  : **0** |
| packets.subscribe.error       : **0** | packets.subscribe.error       : **0** |
| packets.subscribe.received    : **1913828** | packets.subscribe.received    : **2710802** |
| packets.unsuback.sent         : **10096** | packets.unsuback.sent         : **12187** |
| packets.unsubscribe.error     : **0** | packets.unsubscribe.error     : **0** |
| packets.unsubscribe.received  : **13300** | packets.unsubscribe.received  : **16305** |
| rules.matched                 : **0** | rules.matched                 : **0** |
| session.created               : **1310578** | session.created               : **1811630** |
| session.discarded             : **153605** | session.discarded             : **154198** |
| session.resumed               : **616816** | session.resumed               : **864296** |
| session.takeovered            : **616098** | session.takeovered            : **865031** |
| session.terminated            : **1069870** | session.terminated            : **1569284** |
| webhook.client_connack        : **0** | webhook.client_connack        : **0** |
| webhook.client_connect        : **0** | webhook.client_connect        : **0** |
| webhook.client_connected      : **0** | webhook.client_connected      : **0** |
| webhook.client_disconnected   : **0** | webhook.client_disconnected   : **0** |
| webhook.client_subscribe      : **14938769** | webhook.client_subscribe      : **19962812** |
| webhook.client_unsubscribe    : **0** | webhook.client_unsubscribe    : **0** |
| webhook.message_acked         : **0** | webhook.message_acked         : **0** |
| webhook.message_delivered     : **0** | webhook.message_delivered     : **0** |
| webhook.message_publish       : **0** | webhook.message_publish       : **0** |
| webhook.session_subscribed    : **0** | webhook.session_subscribed    : **0** |
| webhook.session_terminated    : **0** | webhook.session_terminated    : **0** |
| webhook.session_unsubscribed  : **0** | webhook.session_unsubscribed  : **0** |

**emqx_ctl broker stats** :
| EMQX_1 | EMQX_2 |
| ------------- | ------------- |
|channels.count                : **87930** | channels.count                : **87652** |
|channels.max                  : **89112** | channels.max                  : **89762** |
|connections.count             : **87930** | connections.count             : **87652** |
|connections.max               : **89112** | connections.max               : **89762** |
|retained.count                : **8** | retained.count                : **8** |
|retained.max                  : **8** | retained.max                  : **8** |
|routes.count                  : **2389414** | routes.count                  : **2389453** |
|routes.max                    : **2425868** | routes.max                    : **2425868** |
|sessions.count                : **87930** | sessions.count                : **87652** |
|sessions.max                  : **89112** | sessions.max                  : **89762** |
|suboptions.count              : **1387083** | suboptions.count              : **1382804** |
|suboptions.max                : **1406126** | suboptions.max                : **1416558** |
|subscribers.count             : **1387035** | subscribers.count             : **1382812** |
|subscribers.max               : **1406143** | subscribers.max               : **1416565** |
|subscriptions.count           : **1387083** | subscriptions.count           : **1382804** |
|subscriptions.max             : **1406126** | subscriptions.max             : **1416558** |
|subscriptions.shared.count    : **2088** | subscriptions.shared.count    : **2088** |
|subscriptions.shared.max      : **2089** | subscriptions.shared.max      : **2089** |
|topics.count                  : **2389414** | topics.count                  : **2389453** |
|topics.max                    : **2425868** | topics.max                    : **2425868** |

Full Log files: 
[node_dump_20230202_131107.zip](https://github.com/emqx/emqx/files/10572890/node_dump_20230202_131107.zip)

Do you have any idea what could cause this issue? The suspect is on the webhook plugin since unloading the plugin stopped the growth of memory consumption.

### What did you expect to happen?

Explained in the question.

### EMQX version

<details>

```console
$ ./bin/emqx_ctl broker
sysdescr  : EMQ X Broker
version   : 4.3.5
uptime    : 11 days, 0 hours, 16 minutes, 4 seconds
datetime  : 2023-02-02 13:06:38
```

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
NAME="Ubuntu"
VERSION="20.04.5 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.5 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal

$ uname -a
Linux bpl-smweb-02 5.4.0-135-generic #152-Ubuntu SMP Wed Nov 23 20:19:22 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux


</details>


### Log files


[node_dump_20230202_131107.zip](https://github.com/emqx/emqx/files/10569008/node_dump_20230202_131107.zip)

**Comment by zmstone** [comment]
Hi @RodaBVB
Is your webhook configured to use https ?
if yes, it's likely caused by a known issue which has been fixed here https://github.com/emqx/emqx/pull/9145
Upgrade to v4.3.21 or later version should fix it.

**Comment by RodaBVB** [comment]
Hi @zmstone!
Thanks for the quick reply, but unfortunately we don't use HTTPS

This is the webhook configuration:

````
web.hook.url = http://@INTERNAL_DOMAIN_NAME@:@BROKER_ACL_PORT@/mqtt/actions
web.hook.headers.content-type = application/json
web.hook.body.encoding_of_payload_field = plain
web.hook.pool_size = 32

web.hook.rule.client.subscribe.1     = {"action": "on_client_subscribe"}
#web.hook.rule.client.unsubscribe.1   = {"action": "on_client_unsubscribe"}
#web.hook.rule.session.created.1      = {"action": "on_session_created"}
#web.hook.rule.session.subscribed.1   = {"action": "on_session_subscribed"}
#web.hook.rule.session.unsubscribed.1 = {"action": "on_session_unsubscribed"}
#web.hook.rule.session.terminated.1   = {"action": "on_session_terminated"}
#web.hook.rule.message.publish.1      = {"action": "on_message_publish"}
#web.hook.rule.message.delivered.1    = {"action": "on_message_delivered"}
#web.hook.rule.message.acked.1        = {"action": "on_message_acked"}
````
Are you sure the newer version will fix this problem. The system is big and in production and it is not easy to upgrade

**Comment by zmstone** [comment]
Hi @RodaBVB 

Thank you for getting back to us.
This means the client are not blocked indefinitely (which is what happens when the bug is in place).
Maybe it's the slow accumulation of requests due to head of line blocking.

In older version `ehttpc` (the HTTP client library we use in EMQX, for EMQX v4.3.5, it's 0.1.16)
`ehttpc` 0.2.0 introduced a major performance tuning which can prevent the higher level retries to overwhelm the lower level request backlog. ref: https://github.com/emqx/ehttpc/blob/main/changelog.md

I would recommend latest 4.3 (or even better 4.4), and enable this config:
```
## If the server supports pipelining (or streaming)
## Enable it by setting to 100, which means to allow maximum 100 requests sent before reply is received
web.hook.enable_pipelining = 100
```

**Comment by qzhuyan** [comment]
worth try to see what are the problematic processes, the majority of mem consumption is on the eheap.

try run
```
emqx eval 'observer_cli:start().'
```
Then press `mm` and `enter` to get sorted with memory usage on EMQX_2.

to quit, just press 'q' and then enter.

send us the screen shoot.

**Comment by RodaBVB** [comment]
Hi @qzhuyan  and @zmstone 

Unfortunately, we had to restart the EMQX due to a memory leak in this environment.
As soon as it gets reproduced next time, I'll share it with you.
Another option we are considering is to remove the EMQX webhook plugin.

**Comment by qzhuyan** [comment]
@RodaBVB we close this ticket for now. 

pls reopen it when you have more info or open an new one, thanks!
