### ISSUE TITLE
Dynamic mountpoint set when authenticating

### ISSUE THREAD

**Issue by richard-scott** [emqx/emqx#9953]
### What would you like to be added or enhanced?

I would like to suggest the ability to set the mountpoint of a connecting device during authentication.
It would be great if you could extend the user model to include a mountpoint field for this.

### Why is this needed?

As far as I can see, the current way to do this is to setup different port numbers for a listener that is setup as with a fixed mountpoint. This isn't very flexible and you have to remember the port number for the users that should use it.

**Comment by tigercl** [comment]
I think it's a good idea, what do you think? @wivwiv 

@richard-scott But in which field do you plan to put the mountpoint? Considering the versatility, I think it is more appropriate to put it in user attri properties of the connection packet.

**Comment by richard-scott** [comment]
@tigercl I was thinking that the authentication mechanism could set the desired mountpoint. For example, the HTTP Authentication would be extended to include the mountpoint in the HTTP response such as this  
  
`HTTP/1.1 200 OK`  
`Headers: Content-Type: application/json`  
`...`  
`Body:`  
`{`  
 `"result": "allow", // options: "allow" | "deny" | "ignore"`  
 `"is_superuser": true, // options: true | fals, default value: false`  
 `"mountpoint" "mqtt/"`  
`}`

**Comment by tigercl** [comment]
@richard-scott Got it. But what I mean is, do you want each client to specify its own mount point separately? This means that the client may need to carry this information in the CONNECT packet.

**Comment by richard-scott** [comment]
@tigercl No, I think it needs to be set server side only. An extra field in the user record in built in db would be great. Also getting this set from the response of an external auth provider would be awesome!

**Comment by tigercl** [comment]
@richard-scott I think I misunderstood your requirement earlier.

But finally this mountpoint field will still be returned to the client, right? So it seems to be the only way to return through the user properties of the CONNACK packet?

In addition, what I want to know is, after the client gets the mountpoint, what will it do with it?

**Comment by richard-scott** [comment]
The feature I'm describing is the dynamic configuration of the mountpoint element of a listener. The MQTT client connecting to the broker would have no knowledge of this mountpoint being used. Just like it does with your existing mountpoint feature.  
  
For example, I currently use this in my emqx.conf file:  
  
`listeners.tcp.default {`  
 `mountpoint = "${username}/"`  
`}`

I want to be able to change ${username}, for ${mountpoint} and have ${mountpoint} populated from the internal database, or an external [API](https://www.emqx.io/docs/en/v5.0/access-control/authn/http.html#http-request-and-response). When adding a user/password, you would have a new field of 'mountpoint' that you can choose to populate if required. Otherwise, a default of '/' should be used.

**Comment by tigercl** [comment]
@richard-scott Got it. It's a reasonable requirement, but I'm not sure if it can be implemented ASAP as we have other higher priority requirements at the moment. 

I will first feed this requirement back to the product team, and then make progress with you ASAP.

**Comment by tigercl** [comment]
I have another question, in fact, you won't have too many mountpoints, will you? So in most cases, hundreds of clients will use the same mountpoint.

This means that if the mountpoint is stored in the database, it will bring a lot of data redundancy.

So maybe we can consider whether there is another better way.

**Comment by richard-scott** [comment]
Thanks for the update. I'm not in a rush for this feature, but I am looking for a way to scale having different groups of clients while allowing the possibility of different groups using the same topic structure. For example:

Say we have 3 groups: car, bus, and train. Each group is owned and managed by a different organisation.

```
/car/1/status
/car/2/status
/bus/1/status
/bus/2/status
/train/1/status
/train/2/status
```

I also want to have other users/devices that have access to the root of each group:

```
/bus/
/car/
/train/
```

I was thinking that a distinct mount point would help, but maybe this is a thing for ACLs?

**Comment by tigercl** [comment]
Okay, considering your starting point is that you need to remember the mapping relationship between mountpoint and port, it is very inconvenient.

What do you think if we could display the mountpoint used by each listener directly on the Dashboard? In fact, this is already implemented in 5.0.

<img width="1715" alt="image" src="https://user-images.githubusercontent.com/15085956/219527499-c9721810-d7f2-4e8c-a1fb-e05a7dbe6a37.png">

**Comment by richard-scott** [comment]
I do not need to remember the port number. This feature would allow a mountpoint to be allocated per user rather than for each listener.

I do not feel that having multiple listeners is a great way of doing this as I can't find a way to have different authentication backends on each listener. From what I can see, any authenticated device can connect to any listener when using the built-in database for authentication as you can only have one built-in database in your cluster.

I have looked at ACLs but that would then require a client device coming to my service to re-write all their MQTT topics to include their group name at the start. This would not be good for existing IoT Devices as a new firmware binary would need to be distributed.

[VerneMQ](https://docs.vernemq.com/configuring-vernemq/db-auth#creating-the-mysql-tables) have a field in their authentication tables for the user's mountpoint. This is the kind of feature I want to be added.

**Comment by tigercl** [comment]
Got it.

**Comment by wivwiv** [comment]
A better way is to set **user property** instead of mountpoint in the authentication step and then select the variables from user property via placeholder in `emqx.conf`.

```sql
INSERT INTO mqtt_user (username, password, user_properties) VALUES ('emqx_u', '<password_hash>', '{ "dynamic_mountpoint": "foo_xxx" }');
-- Auth MySQL Query
-- The user_properties field will merge to the client's user properties
SELECT password, user_properties FROM emqx_user WHERE username = "${username}";

```
```bash
# emqx.conf
listeners.tcp.default {
  ...
  mountpoint = "${user_properties.dynamic_mountpoint}"
}
```

Don't worry, we'll make sure this works for MQTT v3.1.1 clients as well. If you are using an MQTT 5.0 client, you can also set the user property when the client is connecting.

### Why
- More flexible
- Supports other use cases

**Comment by richard-scott** [comment]
Will that work when using the Internal Database for authentication?

**Comment by wivwiv** [comment]
@richard-scott We are in the process of reviewing this proposal, and if it passes this is achievable.
