### ISSUE TITLE
EMQX does not support Push Gateway with Basic Auth.

### ISSUE THREAD

**Issue by sekfung** [emqx/emqx#9957]
### What happened?

basic auth not supported in emqx dashboard

### What did you expect to happen?

support basic auth

### EMQX version

<details>

```console
$ ./bin/emqx_ctl broker
#  v5.0.8
```

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Log files

<details>

</details>

**Comment by lafirest** [comment]
@sekfung 
Hi, could you please give some more detailed information like the reproduction steps?

**Comment by sekfung** [comment]
@lafirest I couldn't find anyway to set the basic auth token for push gateway server in dashboard

and my prometheus server has enabled the basic auth for the requests

Does EMQX support request http://username:password@host:9090 in this way ?

![image](https://user-images.githubusercontent.com/43331641/218358330-4c8be049-7ce7-4c6a-b157-f349ac30b464.png)

**Comment by lafirest** [comment]
@ysfscream 
We should allow users to custom the headers when creating Prometheus, in fact, the API has already supported this

**Comment by ysfscream** [comment]
@sekfung sorry about that. The dashboard looks like there is no support for this. Or you can set the configs by API first.

@lafirest And I will check this: https://github.com/emqx/emqx/pull/9722, this PR has already support that? The custom Headers.

**Comment by lafirest** [comment]
> @sekfung sorry about that. The dashboard looks like there is no support for this. Or you can set the configs by API first.
> 
> @lafirest And I will check this: #9722, this PR has already support that? The custom Headers.

Yes, I have checked that the `PUT /prometheus` had already supported headers.

**Comment by HJianBo** [comment]
Yes, it is, but it is only supported by the config file. How about expose these options in Dashboard @ysfscream

**Comment by ysfscream** [comment]
> Yes, it is, but it is only supported by the config file. How about expose these options in Dashboard @ysfscream

YES. It's already supported on EMQX Dashboard in the next EMQX 5.0.20 release. v5.0.20
