### ISSUE TITLE
安装了3.2.7 windows 版本的emqx，需要下载哪个版本的mqttx ？

### ISSUE THREAD

**Issue by zhaoguoping** [emqx/emqx#9995]
安装了3.2.7 windows 版本的emqx，需要下载哪个版本的mqttx ？

**Comment by zhaoguoping** [comment]
emqx官网提供的下载地址：https://www.emqx.com/zh/try?product=MQTTX

**Comment by tigercl** [comment]
你好，EMQX 和 MQTT X 的版本是没有关联性的，他们都是标准实现。无法连接你可以 [追踪](https://www.emqx.io/docs/zh/v4.4/getting-started/log.html#%E6%97%A5%E5%BF%97%E8%BF%BD%E8%B8%AA) 一下客户端看看。

另外 EMQX 3.2 版本已经超过我们的维护周期了，如果刚开始使用，建议安装最新版本比如 4.4 版本或者 5.0 版本。

**Comment by jinfahua** [comment]
Close the issue, it's not a problem.

**Comment by jinfahua** [comment]
Close the issue, it's not a problem.
